<span style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">An Exception was encountered at '<a href="#papermill-error-cell">In [23]</a>'.</span>

# open problems (task batch correction / label proj)

In [1]:
import pandas as pd
import requests
import json
from scib_metrics.benchmark import Benchmarker, BioConservation, BatchCorrection
import scanpy as sc
from scprint import scPrint
from scdataloader import Preprocessor
from scprint.tasks import Embedder, FinetuneBatchClass
from scprint.tasks.cell_emb import compute_classification
from scprint.utils import zero_shot_annotation_with_refinement
import numpy as np
import os

%load_ext autoreload
%autoreload 2

/lustre/fswork/projects/rech/xeg/uat95fg/scPRINT/.venv/lib/python3.12/site-packages/transformers/utils/hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(

→ connected lamindb: jkobject/scprint2

/lustre/fswork/projects/rech/xeg/uat95fg/simpler_flash/src/simpler_flash/layer_norm.py:1044: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd
/lustre/fswork/projects/rech/xeg/uat95fg/simpler_flash/src/simpler_flash/layer_norm.py:1107: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd

In [2]:
! uv pip list | grep scib #same version as OP

scib                       1.1.7
scib-metrics               0.5.6

In [3]:
LOC = "./data/" #"/pasteur/appa/scratch/jkalfon/data/spcrint_data/"

In [4]:
if not os.path.exists("data/results_batch.json"):
    url = "https://raw.githubusercontent.com/openproblems-bio/website/main/results/batch_integration/data/results.json"
    response = requests.get(url)

    with open("data/results_batch.json", "w") as f:
        f.write(response.text)

if not os.path.exists("data/results_label.json"):
    url = "https://raw.githubusercontent.com/openproblems-bio/website/main/results/label_projection/data/results.json"
    response = requests.get(url)

    with open("data/results_label.json", "w") as f:
        f.write(response.text)

print("File downloaded successfully!")

File downloaded successfully!

In [5]:
res = {}
with open("data/results_batch.json", "r") as f:
    data_batch = json.load(f)
for dataset in data_batch:
    dataset_id = dataset["dataset_id"]
    if dataset_id not in res:
        res[dataset_id] = {}
    res[dataset_id].update({dataset["method_id"]: dataset["metric_values"]})

In [6]:
res_label = {}
with open("data/results_label.json", "r") as f:
    data_label = json.load(f)
for dataset in data_label:
    dataset_id = dataset["dataset_id"]
    if dataset_id not in res_label:
        res_label[dataset_id] = {}
    res_label[dataset_id].update({dataset["method_id"]: dataset["metric_values"]})

res_label.keys()

dict_keys(['cellxgene_census/dkd', 'cellxgene_census/gtex_v9', 'cellxgene_census/hypomap', 'cellxgene_census/immune_cell_atlas', 'cellxgene_census/mouse_pancreas_atlas', 'cellxgene_census/tabula_sapiens', None])

In [7]:
pd.DataFrame(res_label["cellxgene_census/dkd"])

,knn,logistic_regression,majority_vote,mlp,naive_bayes,random_labels,scanvi,scanvi_scarches,scgpt_zeroshot,scimilarity,scimilarity_knn,seurat_transferdata,singler,true_labels,uce,xgboost,geneformer,scgpt_finetuned,scprint
accuracy,0.9490,0.9572,0.2954,0.9540,0.9269,0.1808,0.9570,0.9570,0.8486,0.8869,0.9553,0.9541,0.9147,1,0.1813,0.9644,NA,NA,NA
f1_macro,0.9286,0.9413,0.0351,0.9245,0.9181,0.0774,0.9360,0.9366,0.5239,0.6233,0.9292,0.9344,0.9027,1,0.0743,0.9225,NA,NA,NA
f1_micro,0.9490,0.9572,0.2954,0.9540,0.9269,0.1808,0.9570,0.9570,0.8486,0.8869,0.9553,0.9541,0.9147,1,0.1813,0.9644,NA,NA,NA
f1_weighted,0.9487,0.9567,0.1347,0.9529,0.9296,0.1801,0.9579,0.9567,0.8339,0.8655,0.9556,0.9544,0.9192,1,0.1790,0.9634,NA,NA,NA

In [8]:
pd.DataFrame(res["cellxgene_census/dkd"])

,batchelor_fastmnn,batchelor_mnn_correct,bbknn,combat,embed_cell_types,embed_cell_types_jittered,geneformer,harmony,harmonypy,liger,mnnpy,no_integration,no_integration_batch,pyliger,scalex,scanorama,scanvi,scgpt_zeroshot,scimilarity,scvi,shuffle_integration,shuffle_integration_by_batch,shuffle_integration_by_cell_type,uce,scgpt_finetuned,scprint
ari,0.7599,0.757,0.7666,0.7673,1,1,0.0024,0.7867,0.7655,0.7463,0.1674,0.5999,0.2884,0.6633,0.6177,0.2302,0.7806,0.7597,0.7103,0.8284,-0.0001,0.0069,0.5604,0.508,NA,NA
asw_batch,0.894,0.799,NA,0.9123,0.9593,0.9573,0.4736,0.9066,0.905,0.8743,0.8846,0.8913,0.7086,0.8876,0.8582,0.9048,0.9099,0.8888,0.8264,0.9166,0.9426,0.9005,0.9328,0.9286,NA,NA
asw_label,0.6657,0.6657,NA,0.613,0.9897,0.9897,0.364,0.6466,0.6463,0.6295,0.5027,0.6276,0.5116,0.6284,0.5917,0.5009,0.6334,0.6318,0.7111,0.5754,0.4945,0.4895,0.6276,0.587,NA,NA
cell_cycle_conservation,0.8574,0.8692,NA,0.7925,0.8104,0.8099,0.0527,0.8495,0.8466,0.6013,0.3797,0.8248,0.8609,0.4286,0.3481,0.3818,0.6302,0.7563,0.6936,0.5349,0.0667,0.0726,0.7069,0.8451,NA,NA
clisi,1,1,0.9622,0.9997,1,1,0.7461,1,1,0.9991,0.8921,0.9998,0.9968,0.9995,0.9939,0.8857,1,0.9994,0.9997,0.9992,0.7301,0.7424,0.9998,0.999,NA,NA
graph_connectivity,0.9745,0.9696,0.984,0.9728,1,1,0.0109,0.977,0.9765,0.9628,0.5458,0.9701,0.5229,0.968,0.9278,0.5459,0.9962,0.9631,0.971,0.9812,0.2488,0.2596,0.9703,0.9568,NA,NA
hvg_overlap,NA,0.4293,NA,0.6649,NA,NA,NA,NA,NA,NA,0.4056,NA,NA,NA,0.2665,0.2484,NA,NA,NA,NA,0.6462,1,0.668,NA,NA,NA
ilisi,0.272,0.2893,0.3526,0.1644,0.4348,0.4305,0,0.333,0.3319,0.4223,0.1732,0.0754,0.0076,0.4235,0.3097,0.2657,0.3153,0.2272,0.2297,0.303,0.4782,0.0755,0.4322,0.2298,NA,NA
isolated_label_asw,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
isolated_label_f1,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
kbet,0.3806,0.2482,NA,0.1687,0.949,0.9433,0,0.4251,0.4187,0.7526,0,0.1529,0.0946,0.7672,0.3209,0.0001,0.2521,0.235,0.2235,0.2538,0.4093,0.0113,0.9511,0.2174,NA,NA
nmi,0.829,0.8248,0.8228,0.8306,1,1,0.0315,0.8322,0.8233,0.8002,0.2288,0.7735,0.5322,0.7619,0.6992,0.2268,0.8646,0.7909,0.7877,0.8495,0.0013,0.015,0.761,0.7228,NA,NA
pcr,0.5339,0.5344,NA,0.9998,0.5898,0.5896,0,0.6805,0.6897,0.8142,0.6494,0,1,0.7925,0.9998,0.5585,0.6277,0.19,0.1773,0.6671,0.9975,0,0.7788,0,NA,NA

In [9]:
model_checkpoint_file = "../models/18hebyht-final-small.ckpt"

In [10]:
model = scPrint.load_from_checkpoint(
    model_checkpoint_file, precpt_gene_emb=None, gene_pos_file=None
)
model = model.to("cuda")

FYI: scPrint is not attached to a `Trainer`.

In [11]:
datasets = {
    "cellxgene_census/dkd": "https://datasets.cellxgene.cziscience.com/46d8d92b-32e0-4ca5-9907-4dbf519c7fc3.h5ad",  # 0.3  ['control_3']
    "cellxgene_census/gtex_v9": "https://datasets.cellxgene.cziscience.com/002308e1-0121-4aa1-b8f2-9d034cf44b0f.h5ad",  # 1gb ['GTEX-16BQI']
    "cellxgene_census/hypomap": "https://datasets.cellxgene.cziscience.com/d3be7423-d664-4913-89a9-a506cae4c28f.h5ad",  # 4gb ['SRR9000488']
    "cellxgene_census/mouse_pancreas_atlas": "https://datasets.cellxgene.cziscience.com/49243c50-bf0c-4b10-87f8-55ec9f455399.h5ad",  # 4gb ['mouse_pancreatic_islet_atlas_Hrovatin__VSG__MUC13639']
    # "cellxgene_census/immune_cell_atlas": "https://datasets.cellxgene.cziscience.com/78819b62-0699-4672-8dc8-d9317b04d255.h5ad",  # 3gb --> issue with scib (too large?)
    # 'cellxgene_census/tabula_sapiens': 'https://datasets.cellxgene.cziscience.com/5a495302-b7cd-4bf9-853e-95627b00bb03.h5ad' # 42gb --> too large for scib
}

test = {
    "cellxgene_census/dkd": ["control_3"],
    "cellxgene_census/gtex_v9": ["GTEX-16BQI"],
    "cellxgene_census/hypomap": ["SRR9000488"],
    "cellxgene_census/mouse_pancreas_atlas": [
        "mouse_pancreatic_islet_atlas_Hrovatin__VSG__MUC13639"
    ],
}

In [12]:
metrics = {}
metacell = model.expr_emb_style == "metacell"
model.mask_zeros = False

In [13]:
for name, url in list(datasets.items())[:]:
    print("doing ", name)
    if not os.path.exists(LOC + "temp/" + name + "_proc.h5ad"):
        adata = sc.read(LOC + name + ".h5ad", backup_url=url)
        preprocessor = Preprocessor(
            force_preprocess=True,
            skip_validate=True,
            # drop_non_primary=False,
            is_symbol=False,
            do_postp=metacell,
        )
        print("")
        adata = preprocessor(adata)
        if metacell:
            sc.pp.neighbors(adata, use_rep="X_pca")
        adata.write_h5ad(LOC + "temp/" + name + "_proc.h5ad")
    else:
        adata = sc.read(LOC + "temp/" + name + "_proc.h5ad")

    embed = Embedder(
        how="random expr",
        max_len=3200,
        num_workers=8,
        pred_embedding=["cell_type_ontology_term_id"],
        keep_all_labels_pred=True,
        doplot=False,
    )
    n_adata, _ = embed(model, adata)
    # cls regular
    loc = n_adata.obs.columns[n_adata.obs.columns.str.startswith("CL:")]
    pred = n_adata.obs.loc[:, loc]
    n_adata.obs["pred_cell_type_ontology_term_id"] = loc[pred.values.argmax(1)].values
    n_adata.obs["_ref_cls"] = loc[pred.values.argmax(1)].values
    metrics[name + "_ref_cls"] = compute_classification(
        n_adata,
        ["cell_type_ontology_term_id"],
        label_decoders=model.label_decoders,
        labels_hierarchy=model.labels_hierarchy,
    )
    n_adata_last = n_adata[n_adata.obs["donor_id"].isin(test[name])]
    metrics[name + "_cls"] = compute_classification(
        n_adata_last,
        ["cell_type_ontology_term_id"],
        label_decoders=model.label_decoders,
        labels_hierarchy=model.labels_hierarchy,
    )
    # cls ref
    for i in range(1):
        pred.iloc[:, :] = zero_shot_annotation_with_refinement(
            pred.values, n_adata, return_raw=True
        ).astype(np.float32)
    n_adata.obs["pred_cell_type_ontology_term_id"] = loc[
        zero_shot_annotation_with_refinement(pred.values, n_adata)
    ].values
    n_adata_last = n_adata[n_adata.obs["donor_id"].isin(test[name])]
    metrics[name + "_smooth_cls"] = compute_classification(
        n_adata_last,
        ["cell_type_ontology_term_id"],
        label_decoders=model.label_decoders,
        labels_hierarchy=model.labels_hierarchy,
    )
    # cls cluster
    if "seurat_clusters" in n_adata.obs:
        n_adata.obs["leiden"] = n_adata.obs["seurat_clusters"]
    if "leiden" not in n_adata.obs:
        sc.tl.leiden(n_adata, resolution=4.0)
    for i in n_adata.obs["leiden"].unique():
        n_adata.obs.loc[
            n_adata.obs["leiden"] == str(i), "pred_cell_type_ontology_term_id"
        ] = loc[pred[n_adata.obs["leiden"] == str(i)].values.sum(0).argsort()[::-1][0]]
    n_adata_last = n_adata[n_adata.obs["donor_id"].isin(test[name])]
    metrics[name + "_clust_cls"] = compute_classification(
        n_adata_last,
        ["cell_type_ontology_term_id"],
        label_decoders=model.label_decoders,
        labels_hierarchy=model.labels_hierarchy,
    )
    print(metrics)
    # batch correction
    # bm = Benchmarker(
    #    n_adata,
    #    batch_key="donor_id",  # "batch",  # batch, tech, assay_ontology_term_id, donor_id
    #    label_key="cell_type",  # celltype
    #    embedding_obsm_keys=["scprint_emb"],
    #    bio_conservation_metrics=BioConservation(),
    #    batch_correction_metrics=BatchCorrection(),
    #    n_jobs=10,
    # )
    # del n_adata, adata
    # bm.benchmark()
    # metrics[name + "_batch_corr"] = bm.get_results()
    # bm.plot_results_table(min_max_scale=False)
    # print(metrics[name + "_batch_corr"])

doing  cellxgene_census/dkd

/lustre/fswork/projects/rech/xeg/uat95fg/scdataloader/scdataloader/utils.py:427: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  organismdf = pd.concat(organismdf)

predict epoch start

  0%|          | 0/613 [00:00<?, ?it/s]

  0%|          | 1/613 [00:04<41:45,  4.09s/it]

  0%|          | 2/613 [00:04<19:40,  1.93s/it]

  0%|          | 3/613 [00:04<12:32,  1.23s/it]

  1%|          | 4/613 [00:05<09:11,  1.10it/s]

  1%|          | 5/613 [00:05<07:20,  1.38it/s]

  1%|          | 6/613 [00:06<06:13,  1.63it/s]

  1%|          | 7/613 [00:06<05:30,  1.83it/s]

  1%|▏         | 8/613 [00:06<05:02,  2.00it/s]

  1%|▏         | 9/613 [00:07<04:44,  2.12it/s]

  2%|▏         | 10/613 [00:07<04:32,  2.21it/s]

  2%|▏         | 11/613 [00:08<04:22,  2.29it/s]

  2%|▏         | 12/613 [00:08<04:16,  2.35it/s]

  2%|▏         | 13/613 [00:08<04:11,  2.38it/s]

  2%|▏         | 14/613 [00:09<04:08,  2.41it/s]

  2%|▏         | 15/613 [00:09<04:05,  2.44it/s]

  3%|▎         | 16/613 [00:10<04:03,  2.45it/s]

  3%|▎         | 17/613 [00:10<04:02,  2.46it/s]

  3%|▎         | 18/613 [00:10<04:01,  2.46it/s]

  3%|▎         | 19/613 [00:11<04:01,  2.46it/s]

  3%|▎         | 20/613 [00:11<04:00,  2.47it/s]

  3%|▎         | 21/613 [00:12<03:59,  2.47it/s]

  4%|▎         | 22/613 [00:12<03:59,  2.47it/s]

  4%|▍         | 23/613 [00:12<03:59,  2.47it/s]

  4%|▍         | 24/613 [00:13<03:59,  2.46it/s]

  4%|▍         | 25/613 [00:13<03:58,  2.47it/s]

  4%|▍         | 26/613 [00:14<03:57,  2.47it/s]

  4%|▍         | 27/613 [00:14<03:57,  2.47it/s]

  5%|▍         | 28/613 [00:15<03:56,  2.47it/s]

  5%|▍         | 29/613 [00:15<03:56,  2.47it/s]

  5%|▍         | 30/613 [00:15<03:56,  2.47it/s]

  5%|▌         | 31/613 [00:16<03:55,  2.47it/s]

  5%|▌         | 32/613 [00:16<03:55,  2.47it/s]

  5%|▌         | 33/613 [00:17<03:54,  2.47it/s]

  6%|▌         | 34/613 [00:17<03:54,  2.47it/s]

  6%|▌         | 35/613 [00:17<03:54,  2.47it/s]

  6%|▌         | 36/613 [00:18<03:53,  2.47it/s]

  6%|▌         | 37/613 [00:18<03:53,  2.47it/s]

  6%|▌         | 38/613 [00:19<03:53,  2.46it/s]

  6%|▋         | 39/613 [00:19<03:53,  2.46it/s]

  7%|▋         | 40/613 [00:19<03:52,  2.46it/s]

  7%|▋         | 41/613 [00:20<03:52,  2.46it/s]

  7%|▋         | 42/613 [00:20<03:51,  2.46it/s]

  7%|▋         | 43/613 [00:21<03:52,  2.45it/s]

  7%|▋         | 44/613 [00:21<03:51,  2.45it/s]

  7%|▋         | 45/613 [00:21<03:51,  2.46it/s]

  8%|▊         | 46/613 [00:22<03:50,  2.46it/s]

  8%|▊         | 47/613 [00:22<03:50,  2.46it/s]

  8%|▊         | 48/613 [00:23<03:49,  2.46it/s]

  8%|▊         | 49/613 [00:23<03:49,  2.46it/s]

  8%|▊         | 50/613 [00:23<03:48,  2.46it/s]

  8%|▊         | 51/613 [00:24<03:48,  2.46it/s]

  8%|▊         | 52/613 [00:24<03:47,  2.46it/s]

  9%|▊         | 53/613 [00:25<03:47,  2.46it/s]

  9%|▉         | 54/613 [00:25<03:46,  2.46it/s]

  9%|▉         | 55/613 [00:25<03:46,  2.46it/s]

  9%|▉         | 56/613 [00:26<03:45,  2.47it/s]

  9%|▉         | 57/613 [00:26<03:45,  2.46it/s]

  9%|▉         | 58/613 [00:27<03:45,  2.47it/s]

 10%|▉         | 59/613 [00:27<03:45,  2.46it/s]

 10%|▉         | 60/613 [00:28<03:44,  2.46it/s]

 10%|▉         | 61/613 [00:28<03:44,  2.46it/s]

 10%|█         | 62/613 [00:28<03:44,  2.46it/s]

 10%|█         | 63/613 [00:29<03:43,  2.46it/s]

 10%|█         | 64/613 [00:29<03:43,  2.46it/s]

 11%|█         | 65/613 [00:30<03:42,  2.46it/s]

 11%|█         | 66/613 [00:30<03:42,  2.46it/s]

 11%|█         | 67/613 [00:30<03:41,  2.46it/s]

 11%|█         | 68/613 [00:31<03:41,  2.46it/s]

 11%|█▏        | 69/613 [00:31<03:41,  2.46it/s]

 11%|█▏        | 70/613 [00:32<03:41,  2.46it/s]

 12%|█▏        | 71/613 [00:32<03:40,  2.45it/s]

 12%|█▏        | 72/613 [00:32<03:40,  2.46it/s]

 12%|█▏        | 73/613 [00:33<03:39,  2.46it/s]

 12%|█▏        | 74/613 [00:33<03:39,  2.46it/s]

 12%|█▏        | 75/613 [00:34<03:38,  2.46it/s]

 12%|█▏        | 76/613 [00:34<03:38,  2.45it/s]

 13%|█▎        | 77/613 [00:34<03:38,  2.46it/s]

 13%|█▎        | 78/613 [00:35<03:38,  2.45it/s]

 13%|█▎        | 79/613 [00:35<03:37,  2.46it/s]

 13%|█▎        | 80/613 [00:36<03:36,  2.46it/s]

 13%|█▎        | 81/613 [00:36<03:36,  2.46it/s]

 13%|█▎        | 82/613 [00:36<03:36,  2.46it/s]

 14%|█▎        | 83/613 [00:37<03:36,  2.45it/s]

 14%|█▎        | 84/613 [00:37<03:35,  2.46it/s]

 14%|█▍        | 85/613 [00:38<03:35,  2.45it/s]

 14%|█▍        | 86/613 [00:38<03:34,  2.45it/s]

 14%|█▍        | 87/613 [00:39<03:34,  2.45it/s]

 14%|█▍        | 88/613 [00:39<03:34,  2.45it/s]

 15%|█▍        | 89/613 [00:39<03:33,  2.45it/s]

 15%|█▍        | 90/613 [00:40<03:33,  2.45it/s]

 15%|█▍        | 91/613 [00:40<03:32,  2.45it/s]

 15%|█▌        | 92/613 [00:41<03:32,  2.45it/s]

 15%|█▌        | 93/613 [00:41<03:31,  2.46it/s]

 15%|█▌        | 94/613 [00:41<03:31,  2.45it/s]

 15%|█▌        | 95/613 [00:42<03:30,  2.46it/s]

 16%|█▌        | 96/613 [00:42<03:30,  2.46it/s]

 16%|█▌        | 97/613 [00:43<03:29,  2.46it/s]

 16%|█▌        | 98/613 [00:43<03:29,  2.46it/s]

 16%|█▌        | 99/613 [00:43<03:29,  2.46it/s]

 16%|█▋        | 100/613 [00:44<03:28,  2.45it/s]

 16%|█▋        | 101/613 [00:44<03:28,  2.46it/s]

 17%|█▋        | 102/613 [00:45<03:28,  2.46it/s]

 17%|█▋        | 103/613 [00:45<03:27,  2.45it/s]

 17%|█▋        | 104/613 [00:45<03:27,  2.45it/s]

 17%|█▋        | 105/613 [00:46<03:27,  2.45it/s]

 17%|█▋        | 106/613 [00:46<03:26,  2.45it/s]

 17%|█▋        | 107/613 [00:47<03:26,  2.45it/s]

 18%|█▊        | 108/613 [00:47<03:26,  2.45it/s]

 18%|█▊        | 109/613 [00:47<03:25,  2.45it/s]

 18%|█▊        | 110/613 [00:48<03:25,  2.45it/s]

 18%|█▊        | 111/613 [00:48<03:24,  2.45it/s]

 18%|█▊        | 112/613 [00:49<03:24,  2.45it/s]

 18%|█▊        | 113/613 [00:49<03:24,  2.45it/s]

 19%|█▊        | 114/613 [00:50<03:23,  2.45it/s]

 19%|█▉        | 115/613 [00:50<03:23,  2.45it/s]

 19%|█▉        | 116/613 [00:50<03:22,  2.45it/s]

 19%|█▉        | 117/613 [00:51<03:22,  2.45it/s]

 19%|█▉        | 118/613 [00:51<03:21,  2.45it/s]

 19%|█▉        | 119/613 [00:52<03:21,  2.45it/s]

 20%|█▉        | 120/613 [00:52<03:20,  2.45it/s]

 20%|█▉        | 121/613 [00:52<03:20,  2.45it/s]

 20%|█▉        | 122/613 [00:53<03:20,  2.45it/s]

 20%|██        | 123/613 [00:53<03:20,  2.45it/s]

 20%|██        | 124/613 [00:54<03:19,  2.45it/s]

 20%|██        | 125/613 [00:54<03:19,  2.45it/s]

 21%|██        | 126/613 [00:54<03:18,  2.45it/s]

 21%|██        | 127/613 [00:55<03:18,  2.44it/s]

 21%|██        | 128/613 [00:55<03:18,  2.45it/s]

 21%|██        | 129/613 [00:56<03:17,  2.45it/s]

 21%|██        | 130/613 [00:56<03:17,  2.45it/s]

 21%|██▏       | 131/613 [00:56<03:16,  2.45it/s]

 22%|██▏       | 132/613 [00:57<03:16,  2.45it/s]

 22%|██▏       | 133/613 [00:57<03:16,  2.45it/s]

 22%|██▏       | 134/613 [00:58<03:15,  2.45it/s]

 22%|██▏       | 135/613 [00:58<03:15,  2.45it/s]

 22%|██▏       | 136/613 [00:58<03:14,  2.45it/s]

 22%|██▏       | 137/613 [00:59<03:14,  2.45it/s]

 23%|██▎       | 138/613 [00:59<03:13,  2.45it/s]

 23%|██▎       | 139/613 [01:00<03:13,  2.45it/s]

 23%|██▎       | 140/613 [01:00<03:12,  2.45it/s]

 23%|██▎       | 141/613 [01:01<03:12,  2.45it/s]

 23%|██▎       | 142/613 [01:01<03:12,  2.45it/s]

 23%|██▎       | 143/613 [01:01<03:11,  2.45it/s]

 23%|██▎       | 144/613 [01:02<03:11,  2.45it/s]

 24%|██▎       | 145/613 [01:02<03:10,  2.45it/s]

 24%|██▍       | 146/613 [01:03<03:10,  2.45it/s]

 24%|██▍       | 147/613 [01:03<03:10,  2.45it/s]

 24%|██▍       | 148/613 [01:03<03:09,  2.45it/s]

 24%|██▍       | 149/613 [01:04<03:09,  2.45it/s]

 24%|██▍       | 150/613 [01:04<03:09,  2.45it/s]

 25%|██▍       | 151/613 [01:05<03:08,  2.45it/s]

 25%|██▍       | 152/613 [01:05<03:07,  2.45it/s]

 25%|██▍       | 153/613 [01:05<03:07,  2.45it/s]

 25%|██▌       | 154/613 [01:06<03:07,  2.45it/s]

 25%|██▌       | 155/613 [01:06<03:06,  2.45it/s]

 25%|██▌       | 156/613 [01:07<03:06,  2.45it/s]

 26%|██▌       | 157/613 [01:07<03:06,  2.45it/s]

 26%|██▌       | 158/613 [01:07<03:05,  2.45it/s]

 26%|██▌       | 159/613 [01:08<03:05,  2.45it/s]

 26%|██▌       | 160/613 [01:08<03:04,  2.45it/s]

 26%|██▋       | 161/613 [01:09<03:04,  2.45it/s]

 26%|██▋       | 162/613 [01:09<03:04,  2.45it/s]

 27%|██▋       | 163/613 [01:10<03:03,  2.45it/s]

 27%|██▋       | 164/613 [01:10<03:03,  2.45it/s]

 27%|██▋       | 165/613 [01:10<03:03,  2.44it/s]

 27%|██▋       | 166/613 [01:11<03:03,  2.44it/s]

 27%|██▋       | 167/613 [01:11<03:02,  2.44it/s]

 27%|██▋       | 168/613 [01:12<03:02,  2.44it/s]

 28%|██▊       | 169/613 [01:12<03:01,  2.44it/s]

 28%|██▊       | 170/613 [01:12<03:01,  2.45it/s]

 28%|██▊       | 171/613 [01:13<03:00,  2.45it/s]

 28%|██▊       | 172/613 [01:13<03:00,  2.45it/s]

 28%|██▊       | 173/613 [01:14<02:59,  2.45it/s]

 28%|██▊       | 174/613 [01:14<02:59,  2.45it/s]

 29%|██▊       | 175/613 [01:14<02:59,  2.45it/s]

 29%|██▊       | 176/613 [01:15<02:58,  2.45it/s]

 29%|██▉       | 177/613 [01:15<02:58,  2.45it/s]

 29%|██▉       | 178/613 [01:16<02:57,  2.45it/s]

 29%|██▉       | 179/613 [01:16<02:57,  2.45it/s]

 29%|██▉       | 180/613 [01:16<02:57,  2.45it/s]

 30%|██▉       | 181/613 [01:17<02:57,  2.44it/s]

 30%|██▉       | 182/613 [01:17<02:56,  2.44it/s]

 30%|██▉       | 183/613 [01:18<02:55,  2.44it/s]

 30%|███       | 184/613 [01:18<02:55,  2.44it/s]

 30%|███       | 185/613 [01:19<02:54,  2.45it/s]

 30%|███       | 186/613 [01:19<02:54,  2.45it/s]

 31%|███       | 187/613 [01:19<02:54,  2.45it/s]

 31%|███       | 188/613 [01:20<02:53,  2.45it/s]

 31%|███       | 189/613 [01:20<02:53,  2.44it/s]

 31%|███       | 190/613 [01:21<02:52,  2.45it/s]

 31%|███       | 191/613 [01:21<02:52,  2.45it/s]

 31%|███▏      | 192/613 [01:21<02:52,  2.44it/s]

 31%|███▏      | 193/613 [01:22<02:51,  2.44it/s]

 32%|███▏      | 194/613 [01:22<02:51,  2.44it/s]

 32%|███▏      | 195/613 [01:23<02:50,  2.45it/s]

 32%|███▏      | 196/613 [01:23<02:50,  2.44it/s]

 32%|███▏      | 197/613 [01:23<02:50,  2.44it/s]

 32%|███▏      | 198/613 [01:24<02:50,  2.44it/s]

 32%|███▏      | 199/613 [01:24<02:49,  2.44it/s]

 33%|███▎      | 200/613 [01:25<02:49,  2.44it/s]

 33%|███▎      | 201/613 [01:25<02:48,  2.44it/s]

 33%|███▎      | 202/613 [01:25<02:48,  2.44it/s]

 33%|███▎      | 203/613 [01:26<02:47,  2.44it/s]

 33%|███▎      | 204/613 [01:26<02:47,  2.44it/s]

 33%|███▎      | 205/613 [01:27<02:46,  2.45it/s]

 34%|███▎      | 206/613 [01:27<02:46,  2.45it/s]

 34%|███▍      | 207/613 [01:28<02:45,  2.45it/s]

 34%|███▍      | 208/613 [01:28<02:45,  2.45it/s]

 34%|███▍      | 209/613 [01:28<02:45,  2.45it/s]

 34%|███▍      | 210/613 [01:29<02:44,  2.44it/s]

 34%|███▍      | 211/613 [01:29<02:44,  2.44it/s]

 35%|███▍      | 212/613 [01:30<02:44,  2.44it/s]

 35%|███▍      | 213/613 [01:30<02:43,  2.45it/s]

 35%|███▍      | 214/613 [01:30<02:43,  2.45it/s]

 35%|███▌      | 215/613 [01:31<02:42,  2.45it/s]

 35%|███▌      | 216/613 [01:31<02:42,  2.44it/s]

 35%|███▌      | 217/613 [01:32<02:42,  2.44it/s]

 36%|███▌      | 218/613 [01:32<02:41,  2.44it/s]

 36%|███▌      | 219/613 [01:32<02:41,  2.44it/s]

 36%|███▌      | 220/613 [01:33<02:41,  2.44it/s]

 36%|███▌      | 221/613 [01:33<02:40,  2.44it/s]

 36%|███▌      | 222/613 [01:34<02:40,  2.44it/s]

 36%|███▋      | 223/613 [01:34<02:39,  2.44it/s]

 37%|███▋      | 224/613 [01:34<02:39,  2.44it/s]

 37%|███▋      | 225/613 [01:35<02:39,  2.44it/s]

 37%|███▋      | 226/613 [01:35<02:38,  2.44it/s]

 37%|███▋      | 227/613 [01:36<02:38,  2.44it/s]

 37%|███▋      | 228/613 [01:36<02:37,  2.44it/s]

 37%|███▋      | 229/613 [01:37<02:37,  2.44it/s]

 38%|███▊      | 230/613 [01:37<02:37,  2.44it/s]

 38%|███▊      | 231/613 [01:37<02:36,  2.44it/s]

 38%|███▊      | 232/613 [01:38<02:36,  2.44it/s]

 38%|███▊      | 233/613 [01:38<02:35,  2.44it/s]

 38%|███▊      | 234/613 [01:39<02:35,  2.44it/s]

 38%|███▊      | 235/613 [01:39<02:35,  2.44it/s]

 38%|███▊      | 236/613 [01:39<02:34,  2.44it/s]

 39%|███▊      | 237/613 [01:40<02:34,  2.44it/s]

 39%|███▉      | 238/613 [01:40<02:33,  2.44it/s]

 39%|███▉      | 239/613 [01:41<02:33,  2.44it/s]

 39%|███▉      | 240/613 [01:41<02:32,  2.44it/s]

 39%|███▉      | 241/613 [01:41<02:32,  2.44it/s]

 39%|███▉      | 242/613 [01:42<02:32,  2.44it/s]

 40%|███▉      | 243/613 [01:42<02:31,  2.44it/s]

 40%|███▉      | 244/613 [01:43<02:31,  2.44it/s]

 40%|███▉      | 245/613 [01:43<02:30,  2.44it/s]

 40%|████      | 246/613 [01:43<02:30,  2.44it/s]

 40%|████      | 247/613 [01:44<02:30,  2.44it/s]

 40%|████      | 248/613 [01:44<02:29,  2.44it/s]

 41%|████      | 249/613 [01:45<02:29,  2.44it/s]

 41%|████      | 250/613 [01:45<02:28,  2.44it/s]

 41%|████      | 251/613 [01:46<02:28,  2.44it/s]

 41%|████      | 252/613 [01:46<02:28,  2.44it/s]

 41%|████▏     | 253/613 [01:46<02:27,  2.44it/s]

 41%|████▏     | 254/613 [01:47<02:27,  2.44it/s]

 42%|████▏     | 255/613 [01:47<02:27,  2.43it/s]

 42%|████▏     | 256/613 [01:48<02:26,  2.44it/s]

 42%|████▏     | 257/613 [01:48<02:25,  2.44it/s]

 42%|████▏     | 258/613 [01:48<02:25,  2.44it/s]

 42%|████▏     | 259/613 [01:49<02:24,  2.44it/s]

 42%|████▏     | 260/613 [01:49<02:24,  2.44it/s]

 43%|████▎     | 261/613 [01:50<02:24,  2.44it/s]

 43%|████▎     | 262/613 [01:50<02:23,  2.44it/s]

 43%|████▎     | 263/613 [01:50<02:23,  2.44it/s]

 43%|████▎     | 264/613 [01:51<02:23,  2.44it/s]

 43%|████▎     | 265/613 [01:51<02:22,  2.44it/s]

 43%|████▎     | 266/613 [01:52<02:22,  2.44it/s]

 44%|████▎     | 267/613 [01:52<02:21,  2.44it/s]

 44%|████▎     | 268/613 [01:53<02:21,  2.44it/s]

 44%|████▍     | 269/613 [01:53<02:21,  2.44it/s]

 44%|████▍     | 270/613 [01:53<02:20,  2.44it/s]

 44%|████▍     | 271/613 [01:54<02:20,  2.44it/s]

 44%|████▍     | 272/613 [01:54<02:19,  2.44it/s]

 45%|████▍     | 273/613 [01:55<02:19,  2.44it/s]

 45%|████▍     | 274/613 [01:55<02:18,  2.44it/s]

 45%|████▍     | 275/613 [01:55<02:18,  2.44it/s]

 45%|████▌     | 276/613 [01:56<02:18,  2.44it/s]

 45%|████▌     | 277/613 [01:56<02:17,  2.44it/s]

 45%|████▌     | 278/613 [01:57<02:17,  2.44it/s]

 46%|████▌     | 279/613 [01:57<02:17,  2.44it/s]

 46%|████▌     | 280/613 [01:57<02:16,  2.43it/s]

 46%|████▌     | 281/613 [01:58<02:16,  2.43it/s]

 46%|████▌     | 282/613 [01:58<02:16,  2.43it/s]

 46%|████▌     | 283/613 [01:59<02:15,  2.43it/s]

 46%|████▋     | 284/613 [01:59<02:15,  2.43it/s]

 46%|████▋     | 285/613 [01:59<02:14,  2.43it/s]

 47%|████▋     | 286/613 [02:00<02:14,  2.43it/s]

 47%|████▋     | 287/613 [02:00<02:14,  2.43it/s]

 47%|████▋     | 288/613 [02:01<02:13,  2.43it/s]

 47%|████▋     | 289/613 [02:01<02:13,  2.43it/s]

 47%|████▋     | 290/613 [02:02<02:12,  2.43it/s]

 47%|████▋     | 291/613 [02:02<02:12,  2.43it/s]

 48%|████▊     | 292/613 [02:02<02:11,  2.43it/s]

 48%|████▊     | 293/613 [02:03<02:11,  2.43it/s]

 48%|████▊     | 294/613 [02:03<02:11,  2.43it/s]

 48%|████▊     | 295/613 [02:04<02:10,  2.43it/s]

 48%|████▊     | 296/613 [02:04<02:10,  2.43it/s]

 48%|████▊     | 297/613 [02:04<02:10,  2.43it/s]

 49%|████▊     | 298/613 [02:05<02:09,  2.43it/s]

 49%|████▉     | 299/613 [02:05<02:09,  2.43it/s]

 49%|████▉     | 300/613 [02:06<02:08,  2.43it/s]

 49%|████▉     | 301/613 [02:06<02:08,  2.43it/s]

 49%|████▉     | 302/613 [02:06<02:08,  2.43it/s]

 49%|████▉     | 303/613 [02:07<02:07,  2.43it/s]

 50%|████▉     | 304/613 [02:07<02:07,  2.43it/s]

 50%|████▉     | 305/613 [02:08<02:06,  2.43it/s]

 50%|████▉     | 306/613 [02:08<02:06,  2.43it/s]

 50%|█████     | 307/613 [02:09<02:06,  2.43it/s]

 50%|█████     | 308/613 [02:09<02:05,  2.42it/s]

 50%|█████     | 309/613 [02:09<02:05,  2.42it/s]

 51%|█████     | 310/613 [02:10<02:04,  2.43it/s]

 51%|█████     | 311/613 [02:10<02:04,  2.43it/s]

 51%|█████     | 312/613 [02:11<02:03,  2.43it/s]

 51%|█████     | 313/613 [02:11<02:03,  2.43it/s]

 51%|█████     | 314/613 [02:11<02:03,  2.43it/s]

 51%|█████▏    | 315/613 [02:12<02:02,  2.43it/s]

 52%|█████▏    | 316/613 [02:12<02:02,  2.43it/s]

 52%|█████▏    | 317/613 [02:13<02:02,  2.43it/s]

 52%|█████▏    | 318/613 [02:13<02:01,  2.43it/s]

 52%|█████▏    | 319/613 [02:13<02:01,  2.43it/s]

 52%|█████▏    | 320/613 [02:14<02:00,  2.42it/s]

 52%|█████▏    | 321/613 [02:14<02:00,  2.43it/s]

 53%|█████▎    | 322/613 [02:15<01:59,  2.43it/s]

 53%|█████▎    | 323/613 [02:15<01:59,  2.42it/s]

 53%|█████▎    | 324/613 [02:16<01:59,  2.43it/s]

 53%|█████▎    | 325/613 [02:16<01:58,  2.42it/s]

 53%|█████▎    | 326/613 [02:16<01:58,  2.43it/s]

 53%|█████▎    | 327/613 [02:17<01:57,  2.42it/s]

 54%|█████▎    | 328/613 [02:17<01:57,  2.43it/s]

 54%|█████▎    | 329/613 [02:18<01:57,  2.43it/s]

 54%|█████▍    | 330/613 [02:18<01:56,  2.43it/s]

 54%|█████▍    | 331/613 [02:18<01:56,  2.43it/s]

 54%|█████▍    | 332/613 [02:19<01:55,  2.43it/s]

 54%|█████▍    | 333/613 [02:19<01:55,  2.43it/s]

 54%|█████▍    | 334/613 [02:20<01:55,  2.42it/s]

 55%|█████▍    | 335/613 [02:20<01:54,  2.42it/s]

 55%|█████▍    | 336/613 [02:20<01:54,  2.42it/s]

 55%|█████▍    | 337/613 [02:21<01:53,  2.43it/s]

 55%|█████▌    | 338/613 [02:21<01:53,  2.43it/s]

 55%|█████▌    | 339/613 [02:22<01:53,  2.42it/s]

 55%|█████▌    | 340/613 [02:22<01:52,  2.42it/s]

 56%|█████▌    | 341/613 [02:23<01:52,  2.42it/s]

 56%|█████▌    | 342/613 [02:23<01:51,  2.42it/s]

 56%|█████▌    | 343/613 [02:23<01:51,  2.43it/s]

 56%|█████▌    | 344/613 [02:24<01:50,  2.43it/s]

 56%|█████▋    | 345/613 [02:24<01:51,  2.41it/s]

 56%|█████▋    | 346/613 [02:25<01:50,  2.42it/s]

 57%|█████▋    | 347/613 [02:25<01:49,  2.42it/s]

 57%|█████▋    | 348/613 [02:25<01:49,  2.42it/s]

 57%|█████▋    | 349/613 [02:26<01:49,  2.41it/s]

 57%|█████▋    | 350/613 [02:26<01:48,  2.42it/s]

 57%|█████▋    | 351/613 [02:27<01:48,  2.42it/s]

 57%|█████▋    | 352/613 [02:27<01:47,  2.42it/s]

 58%|█████▊    | 353/613 [02:28<01:47,  2.42it/s]

 58%|█████▊    | 354/613 [02:28<01:46,  2.42it/s]

 58%|█████▊    | 355/613 [02:28<01:46,  2.42it/s]

 58%|█████▊    | 356/613 [02:29<01:46,  2.42it/s]

 58%|█████▊    | 357/613 [02:29<01:45,  2.42it/s]

 58%|█████▊    | 358/613 [02:30<01:45,  2.42it/s]

 59%|█████▊    | 359/613 [02:30<01:44,  2.42it/s]

 59%|█████▊    | 360/613 [02:30<01:44,  2.42it/s]

 59%|█████▉    | 361/613 [02:31<01:43,  2.42it/s]

 59%|█████▉    | 362/613 [02:31<01:43,  2.42it/s]

 59%|█████▉    | 363/613 [02:32<01:43,  2.42it/s]

 59%|█████▉    | 364/613 [02:32<01:42,  2.42it/s]

 60%|█████▉    | 365/613 [02:32<01:42,  2.42it/s]

 60%|█████▉    | 366/613 [02:33<01:42,  2.42it/s]

 60%|█████▉    | 367/613 [02:33<01:41,  2.42it/s]

 60%|██████    | 368/613 [02:34<01:41,  2.42it/s]

 60%|██████    | 369/613 [02:34<01:41,  2.42it/s]

 60%|██████    | 370/613 [02:35<01:40,  2.42it/s]

 61%|██████    | 371/613 [02:35<01:40,  2.42it/s]

 61%|██████    | 372/613 [02:35<01:39,  2.42it/s]

 61%|██████    | 373/613 [02:36<01:39,  2.42it/s]

 61%|██████    | 374/613 [02:36<01:38,  2.42it/s]

 61%|██████    | 375/613 [02:37<01:38,  2.42it/s]

 61%|██████▏   | 376/613 [02:37<01:38,  2.42it/s]

 62%|██████▏   | 377/613 [02:37<01:37,  2.42it/s]

 62%|██████▏   | 378/613 [02:38<01:37,  2.42it/s]

 62%|██████▏   | 379/613 [02:38<01:36,  2.42it/s]

 62%|██████▏   | 380/613 [02:39<01:36,  2.42it/s]

 62%|██████▏   | 381/613 [02:39<01:36,  2.41it/s]

 62%|██████▏   | 382/613 [02:40<01:35,  2.41it/s]

 62%|██████▏   | 383/613 [02:40<01:35,  2.42it/s]

 63%|██████▎   | 384/613 [02:40<01:34,  2.42it/s]

 63%|██████▎   | 385/613 [02:41<01:34,  2.41it/s]

 63%|██████▎   | 386/613 [02:41<01:33,  2.42it/s]

 63%|██████▎   | 387/613 [02:42<01:33,  2.42it/s]

 63%|██████▎   | 388/613 [02:42<01:33,  2.42it/s]

 63%|██████▎   | 389/613 [02:42<01:32,  2.42it/s]

 64%|██████▎   | 390/613 [02:43<01:32,  2.42it/s]

 64%|██████▍   | 391/613 [02:43<01:31,  2.42it/s]

 64%|██████▍   | 392/613 [02:44<01:31,  2.42it/s]

 64%|██████▍   | 393/613 [02:44<01:30,  2.42it/s]

 64%|██████▍   | 394/613 [02:44<01:30,  2.42it/s]

 64%|██████▍   | 395/613 [02:45<01:30,  2.42it/s]

 65%|██████▍   | 396/613 [02:45<01:29,  2.42it/s]

 65%|██████▍   | 397/613 [02:46<01:29,  2.42it/s]

 65%|██████▍   | 398/613 [02:46<01:28,  2.42it/s]

 65%|██████▌   | 399/613 [02:47<01:28,  2.42it/s]

 65%|██████▌   | 400/613 [02:47<01:28,  2.42it/s]

 65%|██████▌   | 401/613 [02:47<01:27,  2.42it/s]

 66%|██████▌   | 402/613 [02:48<01:27,  2.42it/s]

 66%|██████▌   | 403/613 [02:48<01:26,  2.42it/s]

 66%|██████▌   | 404/613 [02:49<01:26,  2.42it/s]

 66%|██████▌   | 405/613 [02:49<01:25,  2.42it/s]

 66%|██████▌   | 406/613 [02:49<01:25,  2.42it/s]

 66%|██████▋   | 407/613 [02:50<01:25,  2.42it/s]

 67%|██████▋   | 408/613 [02:50<01:24,  2.42it/s]

 67%|██████▋   | 409/613 [02:51<01:24,  2.42it/s]

 67%|██████▋   | 410/613 [02:51<01:23,  2.42it/s]

 67%|██████▋   | 411/613 [02:51<01:23,  2.42it/s]

 67%|██████▋   | 412/613 [02:52<01:23,  2.42it/s]

 67%|██████▋   | 413/613 [02:52<01:22,  2.42it/s]

 68%|██████▊   | 414/613 [02:53<01:22,  2.42it/s]

 68%|██████▊   | 415/613 [02:53<01:21,  2.42it/s]

 68%|██████▊   | 416/613 [02:54<01:21,  2.42it/s]

 68%|██████▊   | 417/613 [02:54<01:21,  2.42it/s]

 68%|██████▊   | 418/613 [02:54<01:20,  2.42it/s]

 68%|██████▊   | 419/613 [02:55<01:20,  2.42it/s]

 69%|██████▊   | 420/613 [02:55<01:19,  2.42it/s]

 69%|██████▊   | 421/613 [02:56<01:19,  2.42it/s]

 69%|██████▉   | 422/613 [02:56<01:19,  2.41it/s]

 69%|██████▉   | 423/613 [02:56<01:18,  2.41it/s]

 69%|██████▉   | 424/613 [02:57<01:18,  2.41it/s]

 69%|██████▉   | 425/613 [02:57<01:17,  2.42it/s]

 69%|██████▉   | 426/613 [02:58<01:17,  2.42it/s]

 70%|██████▉   | 427/613 [02:58<01:17,  2.42it/s]

 70%|██████▉   | 428/613 [02:59<01:16,  2.42it/s]

 70%|██████▉   | 429/613 [02:59<01:16,  2.42it/s]

 70%|███████   | 430/613 [02:59<01:15,  2.41it/s]

 70%|███████   | 431/613 [03:00<01:15,  2.42it/s]

 70%|███████   | 432/613 [03:00<01:14,  2.42it/s]

 71%|███████   | 433/613 [03:01<01:14,  2.42it/s]

 71%|███████   | 434/613 [03:01<01:14,  2.42it/s]

 71%|███████   | 435/613 [03:01<01:13,  2.42it/s]

 71%|███████   | 436/613 [03:02<01:13,  2.42it/s]

 71%|███████▏  | 437/613 [03:02<01:12,  2.41it/s]

 71%|███████▏  | 438/613 [03:03<01:12,  2.41it/s]

 72%|███████▏  | 439/613 [03:03<01:12,  2.41it/s]

 72%|███████▏  | 440/613 [03:04<01:11,  2.41it/s]

 72%|███████▏  | 441/613 [03:04<01:11,  2.41it/s]

 72%|███████▏  | 442/613 [03:04<01:10,  2.41it/s]

 72%|███████▏  | 443/613 [03:05<01:10,  2.41it/s]

 72%|███████▏  | 444/613 [03:05<01:10,  2.41it/s]

 73%|███████▎  | 445/613 [03:06<01:09,  2.41it/s]

 73%|███████▎  | 446/613 [03:06<01:09,  2.41it/s]

 73%|███████▎  | 447/613 [03:06<01:08,  2.41it/s]

 73%|███████▎  | 448/613 [03:07<01:08,  2.41it/s]

 73%|███████▎  | 449/613 [03:07<01:08,  2.41it/s]

 73%|███████▎  | 450/613 [03:08<01:07,  2.41it/s]

 74%|███████▎  | 451/613 [03:08<01:07,  2.41it/s]

 74%|███████▎  | 452/613 [03:08<01:06,  2.41it/s]

 74%|███████▍  | 453/613 [03:09<01:06,  2.41it/s]

 74%|███████▍  | 454/613 [03:09<01:06,  2.41it/s]

 74%|███████▍  | 455/613 [03:10<01:05,  2.41it/s]

 74%|███████▍  | 456/613 [03:10<01:05,  2.41it/s]

 75%|███████▍  | 457/613 [03:11<01:04,  2.41it/s]

 75%|███████▍  | 458/613 [03:11<01:04,  2.41it/s]

 75%|███████▍  | 459/613 [03:11<01:03,  2.41it/s]

 75%|███████▌  | 460/613 [03:12<01:03,  2.41it/s]

 75%|███████▌  | 461/613 [03:12<01:02,  2.41it/s]

 75%|███████▌  | 462/613 [03:13<01:02,  2.41it/s]

 76%|███████▌  | 463/613 [03:13<01:02,  2.41it/s]

 76%|███████▌  | 464/613 [03:13<01:01,  2.41it/s]

 76%|███████▌  | 465/613 [03:14<01:01,  2.41it/s]

 76%|███████▌  | 466/613 [03:14<01:00,  2.42it/s]

 76%|███████▌  | 467/613 [03:15<01:00,  2.42it/s]

 76%|███████▋  | 468/613 [03:15<01:00,  2.42it/s]

 77%|███████▋  | 469/613 [03:16<00:59,  2.42it/s]

 77%|███████▋  | 470/613 [03:16<00:59,  2.41it/s]

 77%|███████▋  | 471/613 [03:16<00:58,  2.41it/s]

 77%|███████▋  | 472/613 [03:17<00:58,  2.41it/s]

 77%|███████▋  | 473/613 [03:17<00:57,  2.41it/s]

 77%|███████▋  | 474/613 [03:18<00:57,  2.41it/s]

 77%|███████▋  | 475/613 [03:18<00:57,  2.41it/s]

 78%|███████▊  | 476/613 [03:18<00:56,  2.41it/s]

 78%|███████▊  | 477/613 [03:19<00:56,  2.41it/s]

 78%|███████▊  | 478/613 [03:19<00:55,  2.41it/s]

 78%|███████▊  | 479/613 [03:20<00:55,  2.41it/s]

 78%|███████▊  | 480/613 [03:20<00:55,  2.41it/s]

 78%|███████▊  | 481/613 [03:21<00:54,  2.41it/s]

 79%|███████▊  | 482/613 [03:21<00:54,  2.41it/s]

 79%|███████▉  | 483/613 [03:21<00:53,  2.41it/s]

 79%|███████▉  | 484/613 [03:22<00:53,  2.41it/s]

 79%|███████▉  | 485/613 [03:22<00:53,  2.41it/s]

 79%|███████▉  | 486/613 [03:23<00:52,  2.41it/s]

 79%|███████▉  | 487/613 [03:23<00:52,  2.41it/s]

 80%|███████▉  | 488/613 [03:23<00:51,  2.41it/s]

 80%|███████▉  | 489/613 [03:24<00:51,  2.41it/s]

 80%|███████▉  | 490/613 [03:24<00:51,  2.40it/s]

 80%|████████  | 491/613 [03:25<00:50,  2.40it/s]

 80%|████████  | 492/613 [03:25<00:50,  2.40it/s]

 80%|████████  | 493/613 [03:25<00:49,  2.40it/s]

 81%|████████  | 494/613 [03:26<00:49,  2.40it/s]

 81%|████████  | 495/613 [03:26<00:49,  2.40it/s]

 81%|████████  | 496/613 [03:27<00:48,  2.40it/s]

 81%|████████  | 497/613 [03:27<00:48,  2.40it/s]

 81%|████████  | 498/613 [03:28<00:47,  2.40it/s]

 81%|████████▏ | 499/613 [03:28<00:47,  2.40it/s]

 82%|████████▏ | 500/613 [03:28<00:46,  2.41it/s]

 82%|████████▏ | 501/613 [03:29<00:46,  2.41it/s]

 82%|████████▏ | 502/613 [03:29<00:46,  2.41it/s]

 82%|████████▏ | 503/613 [03:30<00:45,  2.41it/s]

 82%|████████▏ | 504/613 [03:30<00:45,  2.41it/s]

 82%|████████▏ | 505/613 [03:30<00:44,  2.40it/s]

 83%|████████▎ | 506/613 [03:31<00:44,  2.40it/s]

 83%|████████▎ | 507/613 [03:31<00:44,  2.40it/s]

 83%|████████▎ | 508/613 [03:32<00:43,  2.40it/s]

 83%|████████▎ | 509/613 [03:32<00:43,  2.41it/s]

 83%|████████▎ | 510/613 [03:33<00:42,  2.41it/s]

 83%|████████▎ | 511/613 [03:33<00:42,  2.41it/s]

 84%|████████▎ | 512/613 [03:33<00:42,  2.40it/s]

 84%|████████▎ | 513/613 [03:34<00:41,  2.40it/s]

 84%|████████▍ | 514/613 [03:34<00:41,  2.40it/s]

 84%|████████▍ | 515/613 [03:35<00:40,  2.41it/s]

 84%|████████▍ | 516/613 [03:35<00:40,  2.41it/s]

 84%|████████▍ | 517/613 [03:35<00:39,  2.41it/s]

 85%|████████▍ | 518/613 [03:36<00:39,  2.41it/s]

 85%|████████▍ | 519/613 [03:36<00:39,  2.41it/s]

 85%|████████▍ | 520/613 [03:37<00:38,  2.41it/s]

 85%|████████▍ | 521/613 [03:37<00:38,  2.41it/s]

 85%|████████▌ | 522/613 [03:38<00:37,  2.41it/s]

 85%|████████▌ | 523/613 [03:38<00:37,  2.41it/s]

 85%|████████▌ | 524/613 [03:38<00:36,  2.41it/s]

 86%|████████▌ | 525/613 [03:39<00:36,  2.41it/s]

 86%|████████▌ | 526/613 [03:39<00:36,  2.40it/s]

 86%|████████▌ | 527/613 [03:40<00:35,  2.40it/s]

 86%|████████▌ | 528/613 [03:40<00:35,  2.40it/s]

 86%|████████▋ | 529/613 [03:40<00:34,  2.41it/s]

 86%|████████▋ | 530/613 [03:41<00:34,  2.41it/s]

 87%|████████▋ | 531/613 [03:41<00:34,  2.40it/s]

 87%|████████▋ | 532/613 [03:42<00:33,  2.40it/s]

 87%|████████▋ | 533/613 [03:42<00:33,  2.40it/s]

 87%|████████▋ | 534/613 [03:43<00:32,  2.41it/s]

 87%|████████▋ | 535/613 [03:43<00:32,  2.41it/s]

 87%|████████▋ | 536/613 [03:43<00:32,  2.41it/s]

 88%|████████▊ | 537/613 [03:44<00:31,  2.41it/s]

 88%|████████▊ | 538/613 [03:44<00:31,  2.41it/s]

 88%|████████▊ | 539/613 [03:45<00:30,  2.41it/s]

 88%|████████▊ | 540/613 [03:45<00:30,  2.40it/s]

 88%|████████▊ | 541/613 [03:45<00:29,  2.40it/s]

 88%|████████▊ | 542/613 [03:46<00:29,  2.41it/s]

 89%|████████▊ | 543/613 [03:46<00:29,  2.41it/s]

 89%|████████▊ | 544/613 [03:47<00:28,  2.41it/s]

 89%|████████▉ | 545/613 [03:47<00:28,  2.41it/s]

 89%|████████▉ | 546/613 [03:48<00:27,  2.41it/s]

 89%|████████▉ | 547/613 [03:48<00:27,  2.41it/s]

 89%|████████▉ | 548/613 [03:48<00:26,  2.41it/s]

 90%|████████▉ | 549/613 [03:49<00:26,  2.41it/s]

 90%|████████▉ | 550/613 [03:49<00:26,  2.41it/s]

 90%|████████▉ | 551/613 [03:50<00:25,  2.41it/s]

 90%|█████████ | 552/613 [03:50<00:25,  2.41it/s]

 90%|█████████ | 553/613 [03:50<00:24,  2.41it/s]

 90%|█████████ | 554/613 [03:51<00:24,  2.41it/s]

 91%|█████████ | 555/613 [03:51<00:24,  2.41it/s]

 91%|█████████ | 556/613 [03:52<00:23,  2.41it/s]

 91%|█████████ | 557/613 [03:52<00:23,  2.40it/s]

 91%|█████████ | 558/613 [03:53<00:22,  2.41it/s]

 91%|█████████ | 559/613 [03:53<00:22,  2.40it/s]

 91%|█████████▏| 560/613 [03:53<00:22,  2.40it/s]

 92%|█████████▏| 561/613 [03:54<00:21,  2.40it/s]

 92%|█████████▏| 562/613 [03:54<00:21,  2.40it/s]

 92%|█████████▏| 563/613 [03:55<00:20,  2.40it/s]

 92%|█████████▏| 564/613 [03:55<00:20,  2.40it/s]

 92%|█████████▏| 565/613 [03:55<00:20,  2.40it/s]

 92%|█████████▏| 566/613 [03:56<00:19,  2.40it/s]

 92%|█████████▏| 567/613 [03:56<00:19,  2.40it/s]

 93%|█████████▎| 568/613 [03:57<00:18,  2.40it/s]

 93%|█████████▎| 569/613 [03:57<00:18,  2.40it/s]

 93%|█████████▎| 570/613 [03:58<00:17,  2.40it/s]

 93%|█████████▎| 571/613 [03:58<00:17,  2.40it/s]

 93%|█████████▎| 572/613 [03:58<00:17,  2.40it/s]

 93%|█████████▎| 573/613 [03:59<00:16,  2.41it/s]

 94%|█████████▎| 574/613 [03:59<00:16,  2.40it/s]

 94%|█████████▍| 575/613 [04:00<00:15,  2.40it/s]

 94%|█████████▍| 576/613 [04:00<00:15,  2.40it/s]

 94%|█████████▍| 577/613 [04:00<00:14,  2.40it/s]

 94%|█████████▍| 578/613 [04:01<00:14,  2.41it/s]

 94%|█████████▍| 579/613 [04:01<00:14,  2.40it/s]

 95%|█████████▍| 580/613 [04:02<00:13,  2.40it/s]

 95%|█████████▍| 581/613 [04:02<00:13,  2.41it/s]

 95%|█████████▍| 582/613 [04:03<00:12,  2.40it/s]

 95%|█████████▌| 583/613 [04:03<00:12,  2.40it/s]

 95%|█████████▌| 584/613 [04:03<00:12,  2.40it/s]

 95%|█████████▌| 585/613 [04:04<00:11,  2.40it/s]

 96%|█████████▌| 586/613 [04:04<00:11,  2.40it/s]

 96%|█████████▌| 587/613 [04:05<00:10,  2.40it/s]

 96%|█████████▌| 588/613 [04:05<00:10,  2.40it/s]

 96%|█████████▌| 589/613 [04:05<00:10,  2.40it/s]

 96%|█████████▌| 590/613 [04:06<00:09,  2.40it/s]

 96%|█████████▋| 591/613 [04:06<00:09,  2.40it/s]

 97%|█████████▋| 592/613 [04:07<00:08,  2.40it/s]

 97%|█████████▋| 593/613 [04:07<00:08,  2.40it/s]

 97%|█████████▋| 594/613 [04:08<00:07,  2.40it/s]

 97%|█████████▋| 595/613 [04:08<00:07,  2.40it/s]

 97%|█████████▋| 596/613 [04:08<00:07,  2.40it/s]

 97%|█████████▋| 597/613 [04:09<00:06,  2.40it/s]

 98%|█████████▊| 598/613 [04:09<00:06,  2.40it/s]

 98%|█████████▊| 599/613 [04:10<00:05,  2.40it/s]

 98%|█████████▊| 600/613 [04:10<00:05,  2.40it/s]

 98%|█████████▊| 601/613 [04:10<00:04,  2.40it/s]

 98%|█████████▊| 602/613 [04:11<00:04,  2.40it/s]

 98%|█████████▊| 603/613 [04:11<00:04,  2.40it/s]

 99%|█████████▊| 604/613 [04:12<00:03,  2.40it/s]

 99%|█████████▊| 605/613 [04:12<00:03,  2.40it/s]

 99%|█████████▉| 606/613 [04:13<00:02,  2.40it/s]

 99%|█████████▉| 607/613 [04:13<00:02,  2.40it/s]

 99%|█████████▉| 608/613 [04:13<00:02,  2.40it/s]

 99%|█████████▉| 609/613 [04:14<00:01,  2.40it/s]

100%|█████████▉| 610/613 [04:14<00:01,  2.40it/s]

100%|█████████▉| 611/613 [04:15<00:00,  2.40it/s]

100%|█████████▉| 612/613 [04:15<00:00,  2.40it/s]

100%|██████████| 613/613 [04:15<00:00,  2.40it/s]

logging the anndata
AnnData object with n_obs × n_vars = 39176 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

too few cells to embed into a umap
too few cells to compute a clustering

PairwiseArrays with keys: connectivities, distances

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.090395 -19.692902 -18.762865 ... -20.443102 -20.487062 -20.76975 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.519642 -13.969489 -14.003035 ... -13.995768 -14.554915 -14.520956]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.216888 -15.876312 -16.959768 ... -16.812977 -16.081    -14.063531]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.755873 -16.099726 -15.628602 ... -16.726566 -17.095383 -16.942905]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.688446 -16.810373 -18.479784 ... -17.711079 -17.370481 -14.971293]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.466838 -13.889031 -13.89835  ... -13.951749 -14.510777 -14.458064]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.628846 -14.593231 -14.603876 ... -14.669912 -14.620396 -14.884999]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.588608 -17.548498 -18.289808 ... -18.793386 -20.49085  -21.385206]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-27.926188 -25.777412 -26.622488 ... -27.067282 -28.176249 -27.841902]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-25.00645  -21.58642  -22.053137 ... -22.027378 -24.413786 -23.48228 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.483633 -26.396978 -26.791729 ... -27.27866  -20.615479 -25.156038]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.694727 -27.151405 -26.775963 ... -24.46738  -16.865704 -20.467543]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.391503 -10.731298 -10.750776 ... -10.367852 -11.267826 -11.544152]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.071386  -7.912718  -7.470815  ... -8.505972  -6.7388935 -8.6676855]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.646545 -14.192816 -14.335227 ... -13.997816 -18.953602 -17.175892]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.147422 -14.263244 -13.998123 ... -13.282664 -14.394594 -13.485344]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.211643 -18.510069 -19.949966 ... -19.43738  -21.849108 -21.876602]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-26.96313  -23.307415 -23.172384 ... -23.077969 -27.346294 -26.166029]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.897828 -19.534695 -20.558144 ... -19.276909  -6.885348 -10.520694]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-29.960363 -26.909094 -26.182062 ... -26.28937  -30.623806 -27.669214]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.732429  -11.9088335 -12.998025  ... -12.759937  -11.206156
 -10.77341  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.968212 -16.952406 -16.280973 ... -17.591982 -17.337273 -17.506279]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.445386 -10.085013  -9.775162 ... -10.475886 -13.891128 -14.124639]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-24.132366 -16.601515 -16.12235  ... -17.486265 -24.66494  -24.069403]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.402447   -8.7975855  -8.893377  ...  -7.4350367 -11.984853
 -11.602263 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.765079 -11.552757 -11.366378 ... -11.663885 -14.064084 -12.702195]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.160524   -7.587823   -7.6833944 ...  -7.9129777 -13.559326
 -11.130671 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.205175   -8.25625    -8.04972   ...  -7.7909904 -12.654933
 -10.896645 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.605564   -6.0166903  -6.00205   ...  -5.8420787 -12.450722
 -10.238603 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.970159  -12.7536745 -12.176183  ... -12.995162  -15.630292
 -15.255522 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.708611 -10.524596  -9.314058 ... -11.690994 -12.592196 -10.684812]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.194515 -27.568888 -28.97735  ... -28.552708 -21.831837 -24.157516]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.792942 -19.395267 -19.075935 ... -21.641733 -20.120655 -20.2932  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.989347 -21.840197 -22.389307 ... -22.248169 -23.724766 -24.048004]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.274852   -9.0080385  -9.6324    ...  -8.102378  -14.16152
 -12.109624 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.687827 -21.043713 -20.718647 ... -19.746008 -16.523985 -14.885068]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.41077    -9.251881   -8.190344  ...  -8.586043  -14.330464
 -11.3966875]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.811752  -9.859746  -9.625772 ... -10.067447  -9.399759  -9.935793]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.579061 -21.088093 -20.96434  ... -20.78722  -16.025698 -16.476425]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.095395 -11.199788 -10.589361 ... -10.524048 -10.624375  -9.834696]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.183025 -19.477325 -19.55516  ... -19.625568 -20.032757 -20.04517 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.953402 -16.769417 -15.917876 ... -16.328096 -19.51524  -19.173826]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.377552 -17.14803  -17.403458 ... -18.133736 -19.37464  -21.112864]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.133385 -13.095644 -12.005755 ... -13.795999 -21.47108  -17.802225]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.720228 -14.654386 -13.858809 ... -15.216049 -17.06342  -16.189692]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.11408  -20.05661  -20.13821  ... -19.641441 -20.14348  -19.770945]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.055372 -13.305462 -13.261693 ... -13.414282 -14.150127 -13.95146 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.59256   -8.287161  -7.6938105 ... -8.517339  -9.257566  -8.776455 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.97212  -15.061255 -14.944189 ... -15.482549 -15.323552 -15.781719]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-24.931566 -20.840334 -20.699762 ... -21.432867 -24.864357 -24.41706 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.399833  -6.8683057 -6.621391  ... -6.485459  -5.1617346 -6.178872 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.859627 -11.593176 -11.017359 ... -10.555498  -9.84403   -9.390891]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.368454 -8.50925  -8.53394  ... -7.732654 -9.302211 -8.574562]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.62356  -13.506491 -12.587393 ... -14.193504 -18.594965 -17.334623]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.7448626 -6.810712  -6.760963  ... -7.2176237 -5.561349  -5.5820565]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.6679854 -7.906974  -7.7033176 ... -8.002698  -7.016972  -7.421867 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.1615095 -11.417455  -10.769886  ... -10.289373  -11.518069
 -11.291305 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.494963  -11.9472685 -10.675365  ... -13.556273  -19.354786
 -16.33596  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.999141 -15.445229 -15.272977 ... -14.892139 -16.016073 -15.141575]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.26628  -10.413406  -9.874905 ...  -9.344292 -12.680645 -11.951733]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.772834 -14.308843 -14.020482 ... -14.482863 -14.906532 -15.033559]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.666895 -10.63405  -10.111592 ...  -9.602863 -12.187247 -11.755597]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.17757   -9.778937  -9.139162 ...  -8.804689 -14.426374 -12.573845]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.751263   -8.207468   -7.8149633 ...  -7.6765976 -13.370484
 -11.357573 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.188049 -13.46873  -13.324882 ... -13.534362 -14.381115 -14.078163]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.182036  -10.054774   -9.578754  ...  -8.82275   -10.966517
  -9.7930565]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.204392  -13.5348015 -13.4753065 ... -13.5844965 -14.385815
 -14.119827 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.151927 -13.910999 -13.928847 ... -13.964664 -14.27766  -14.320682]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.6713176 -4.5630145 -4.735675  ... -5.0187426 -7.893821  -7.741197 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.303696   -7.3089757  -7.9610066 ...  -8.651513   -9.908406
 -10.118077 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.666546 -17.652767 -17.39818  ... -17.61689  -19.097673 -18.169119]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.243908 -10.035665 -10.018548 ...  -9.885235 -11.570509 -11.797649]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.729825   -8.072336   -7.874031  ...  -7.7781906 -10.060279
  -9.977979 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.428153  -9.044382  -9.204324 ...  -6.465492  -9.786458  -7.153315]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.601058 -10.061103 -10.145978 ... -11.164219  -8.75609  -11.345196]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.661184 -25.391003 -24.503593 ... -25.6924   -21.192135 -23.015017]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.420256 -13.020367 -12.797578 ... -14.754705 -19.905226 -19.804167]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.390737 -11.43163  -10.782858 ... -11.841508 -11.191931 -12.152096]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-24.569542 -22.57013  -22.597374 ... -23.371468 -24.177387 -26.251825]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.488783 -13.928177 -13.861837 ... -13.9359   -14.668672 -14.424108]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.690762 -20.921654 -21.626469 ... -22.454065 -23.294373 -23.228674]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.344374  -11.850904  -11.974176  ... -13.787234   -7.0987444
 -10.174082 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.956583  -10.920381  -11.061543  ... -10.7658415 -13.520681
 -11.512385 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.852323 -11.842274 -11.300353 ... -13.283327 -11.712642 -13.136639]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.748752 -10.224965  -9.84632  ...  -9.66311  -11.419073 -10.747079]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-28.130625 -22.526297 -21.582264 ... -22.221811 -28.297567 -25.525919]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.386026 -14.04686  -12.296326 ... -15.025417 -21.974968 -18.565395]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.308877 -13.990008 -14.044614 ... -14.073719 -14.414275 -14.40983 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.213125 -11.097888 -11.197989 ... -11.534902 -12.418026 -12.482988]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.301084 -13.709527 -13.594124 ... -13.655233 -14.506958 -14.200652]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-26.6545   -25.213955 -25.126772 ... -25.119566 -25.939407 -25.983713]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.3609815 -12.260031  -11.669182  ... -12.613887   -7.9755406
  -9.405458 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.1184244 -9.183431  -8.38528   ... -9.796584  -7.4035807 -8.019235 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.665876 -24.65951  -24.464537 ... -24.15123  -18.255636 -19.41017 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.194818  -7.392655  -7.4172993 ... -6.9759097 -9.052112  -8.682545 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-25.264406 -18.17452  -16.03302  ... -18.545668 -24.492603 -24.32366 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.804947 -10.376291  -9.742041 ...  -9.698635 -12.382003 -11.303777]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.068014 -17.479834 -17.40268  ... -19.337284 -23.288345 -19.855532]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.134052 -16.898558 -16.237865 ... -16.922    -19.259995 -18.555967]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.8076935 -11.025738  -10.403744  ... -10.449095  -12.548629
 -11.566587 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.363036   -8.518912   -6.8925524 ...  -9.38744   -10.036662
  -7.3401403]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.541502   -7.8919287  -7.7196193 ... -10.391556   -9.798887
 -11.9159975]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.451632 -13.94433  -13.7148   ... -16.989887  -9.92513  -12.879301]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.25555  -19.340555 -18.05793  ... -19.239433 -23.47151  -22.714931]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.671648 -11.880431 -10.630472 ... -10.520154 -15.340048 -12.496157]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.740889  -8.657141  -7.614369  ... -8.500511  -8.487308  -8.4589615]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.829424 -10.118261  -9.68558  ...  -9.046526 -13.094846 -11.304454]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.902312 -14.772581 -13.224398 ... -15.646929 -13.984884 -14.53682 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.101119  -9.149985  -7.588622  ... -9.540684  -7.71817   -7.1693993]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.860836  -12.7135725 -12.916574  ... -12.995955  -15.231051
 -15.27114  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.549611 -10.409878  -9.421451 ... -10.270436  -9.515598  -9.125491]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.325572 -11.958507 -10.613806 ... -11.328064 -12.180029 -11.510711]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 3.667035  -6.4560113 -5.539464  ... -5.9430013  3.5808392  1.3778316]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.6857295 -2.2774742 -2.056127  ... -2.5482872 -4.6047316 -3.5581796]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.29023  -10.162597  -9.231723 ...  -9.996535  -9.174826  -9.03042 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.2291455 -7.543774  -6.3336043 ... -7.2139206 -7.564626  -6.9830275]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.828282 -14.380418 -13.842643 ... -14.37384  -16.242178 -15.99839 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.894579  -8.457353  -7.5259323 ... -8.059725  -7.9069943 -7.5687323]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.6926723 -8.828109  -7.859224  ... -8.5204    -7.8220296 -7.444652 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.8661156 -5.6723037 -3.6550732 ... -5.4099045 -6.3783584 -6.0310493]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.799461   2.3630228  2.412734  ...  1.8989455 -5.012421  -3.5509784]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.8642797 -7.9141517 -6.6981573 ... -7.867254  -6.7155337 -8.396049 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.507132  -5.241406  -3.6980793 ... -5.263206  -6.4356723 -4.8968835]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.8618374 -7.9921026 -6.9387765 ... -7.9267554 -8.080195  -7.816004 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.456675 -15.025652 -14.380086 ... -14.672015 -12.885916 -12.910433]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.626746   -9.489959   -7.5658145 ... -10.042103  -13.75959
 -11.576105 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.628178 -11.210273 -10.484607 ... -10.348784 -13.839441 -12.655683]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.386324 -10.329354  -9.606844 ...  -9.609893 -11.698474 -10.644499]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.7512517 -3.0782468 -2.607456  ... -2.7086375 -4.7385206 -3.0287163]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.000547  -5.4799843 -4.6525207 ... -5.6598287 -5.3064914 -3.913567 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.700293  -15.1386595 -15.8008795 ... -14.99256   -14.561663
 -14.540252 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.677332 -17.08285  -15.926448 ... -16.345875 -22.229925 -20.721523]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.11444  -13.254279 -13.190686 ... -13.267634 -14.192082 -13.994458]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.481482 -13.91926  -13.872142 ... -13.947816 -14.565816 -14.477447]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.556637 -19.177572 -17.69715  ... -18.188036 -15.700892 -16.289503]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.9419775 -12.900835  -13.004961  ... -13.079166  -13.030724
 -13.15708  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-24.754429 -17.169561 -16.182844 ... -18.051031 -26.863274 -24.05598 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.817274 -16.165453 -17.102526 ... -16.763802 -20.195078 -18.905394]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.136215 -15.184347 -15.222737 ... -15.068464 -17.069128 -15.348802]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.970933 -10.53656   -9.422107 ...  -9.477091  -9.535119  -9.267268]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.76744  -10.181447  -9.012049 ...  -9.409116  -9.728015  -9.364546]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

PairwiseArrays with keys: connectivities, distances

{'cellxgene_census/dkd_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.6050132734327139, 'macro': 0.45858384601691754, 'micro': 0.6050132734327139, 'weighted': 0.5752358078815335}}, 'cellxgene_census/dkd_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5608184918529746, 'macro': 0.49302410982269285, 'micro': 0.5608184918529746, 'weighted': 0.5370188034467204}}, 'cellxgene_census/dkd_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5941644562334217, 'macro': 0.5355514243377841, 'micro': 0.5941644562334217, 'weighted': 0.5827613925424003}}, 'cellxgene_census/dkd_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5985221674876847, 'macro': 0.5, 'micro': 0.5985221674876847, 'weighted': 0.5985221674876847}}}
doing  cellxgene_census/gtex_v9

/lustre/fswork/projects/rech/xeg/uat95fg/scdataloader/scdataloader/utils.py:427: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  organismdf = pd.concat(organismdf)

predict epoch start

  0%|          | 0/3268 [00:00<?, ?it/s]

  0%|          | 1/3268 [00:04<4:00:44,  4.42s/it]

  0%|          | 2/3268 [00:04<1:52:02,  2.06s/it]

  0%|          | 3/3268 [00:05<1:10:52,  1.30s/it]

  0%|          | 4/3268 [00:05<51:31,  1.06it/s]

  0%|          | 5/3268 [00:06<40:50,  1.33it/s]

  0%|          | 6/3268 [00:06<34:23,  1.58it/s]

  0%|          | 7/3268 [00:06<30:18,  1.79it/s]

  0%|          | 8/3268 [00:07<27:36,  1.97it/s]

  0%|          | 9/3268 [00:07<25:57,  2.09it/s]

  0%|          | 10/3268 [00:08<24:42,  2.20it/s]

  0%|          | 11/3268 [00:08<23:49,  2.28it/s]

  0%|          | 12/3268 [00:08<23:12,  2.34it/s]

  0%|          | 13/3268 [00:09<22:46,  2.38it/s]

  0%|          | 14/3268 [00:09<22:29,  2.41it/s]

  0%|          | 15/3268 [00:10<22:18,  2.43it/s]

  0%|          | 16/3268 [00:10<22:10,  2.44it/s]

  1%|          | 17/3268 [00:10<22:06,  2.45it/s]

  1%|          | 18/3268 [00:11<22:04,  2.45it/s]

  1%|          | 19/3268 [00:11<22:02,  2.46it/s]

  1%|          | 20/3268 [00:12<21:59,  2.46it/s]

  1%|          | 21/3268 [00:12<21:57,  2.46it/s]

  1%|          | 22/3268 [00:12<21:56,  2.47it/s]

  1%|          | 23/3268 [00:13<21:55,  2.47it/s]

  1%|          | 24/3268 [00:13<21:55,  2.47it/s]

  1%|          | 25/3268 [00:14<21:54,  2.47it/s]

  1%|          | 26/3268 [00:14<21:55,  2.47it/s]

  1%|          | 27/3268 [00:14<21:53,  2.47it/s]

  1%|          | 28/3268 [00:15<21:54,  2.47it/s]

  1%|          | 29/3268 [00:15<21:55,  2.46it/s]

  1%|          | 30/3268 [00:16<21:53,  2.46it/s]

  1%|          | 31/3268 [00:16<21:54,  2.46it/s]

  1%|          | 32/3268 [00:16<21:53,  2.46it/s]

  1%|          | 33/3268 [00:17<21:52,  2.47it/s]

  1%|          | 34/3268 [00:17<21:50,  2.47it/s]

  1%|          | 35/3268 [00:18<21:50,  2.47it/s]

  1%|          | 36/3268 [00:18<21:53,  2.46it/s]

  1%|          | 37/3268 [00:18<21:54,  2.46it/s]

  1%|          | 38/3268 [00:19<21:52,  2.46it/s]

  1%|          | 39/3268 [00:19<21:51,  2.46it/s]

  1%|          | 40/3268 [00:20<21:52,  2.46it/s]

  1%|▏         | 41/3268 [00:20<21:52,  2.46it/s]

  1%|▏         | 42/3268 [00:21<21:50,  2.46it/s]

  1%|▏         | 43/3268 [00:21<21:51,  2.46it/s]

  1%|▏         | 44/3268 [00:21<21:51,  2.46it/s]

  1%|▏         | 45/3268 [00:22<21:52,  2.46it/s]

  1%|▏         | 46/3268 [00:22<21:50,  2.46it/s]

  1%|▏         | 47/3268 [00:23<21:48,  2.46it/s]

  1%|▏         | 48/3268 [00:23<21:50,  2.46it/s]

  1%|▏         | 49/3268 [00:23<21:50,  2.46it/s]

  2%|▏         | 50/3268 [00:24<21:50,  2.45it/s]

  2%|▏         | 51/3268 [00:24<21:49,  2.46it/s]

  2%|▏         | 52/3268 [00:25<21:49,  2.46it/s]

  2%|▏         | 53/3268 [00:25<21:50,  2.45it/s]

  2%|▏         | 54/3268 [00:25<21:48,  2.46it/s]

  2%|▏         | 55/3268 [00:26<21:47,  2.46it/s]

  2%|▏         | 56/3268 [00:26<21:46,  2.46it/s]

  2%|▏         | 57/3268 [00:27<21:45,  2.46it/s]

  2%|▏         | 58/3268 [00:27<21:44,  2.46it/s]

  2%|▏         | 59/3268 [00:27<21:42,  2.46it/s]

  2%|▏         | 60/3268 [00:28<21:42,  2.46it/s]

  2%|▏         | 61/3268 [00:28<21:43,  2.46it/s]

  2%|▏         | 62/3268 [00:29<21:42,  2.46it/s]

  2%|▏         | 63/3268 [00:29<21:44,  2.46it/s]

  2%|▏         | 64/3268 [00:29<21:43,  2.46it/s]

  2%|▏         | 65/3268 [00:30<21:45,  2.45it/s]

  2%|▏         | 66/3268 [00:30<21:43,  2.46it/s]

  2%|▏         | 67/3268 [00:31<21:44,  2.45it/s]

  2%|▏         | 68/3268 [00:31<21:43,  2.45it/s]

  2%|▏         | 69/3268 [00:32<21:42,  2.46it/s]

  2%|▏         | 70/3268 [00:32<21:42,  2.46it/s]

  2%|▏         | 71/3268 [00:32<21:40,  2.46it/s]

  2%|▏         | 72/3268 [00:33<21:40,  2.46it/s]

  2%|▏         | 73/3268 [00:33<21:40,  2.46it/s]

  2%|▏         | 74/3268 [00:34<21:40,  2.46it/s]

  2%|▏         | 75/3268 [00:34<21:40,  2.45it/s]

  2%|▏         | 76/3268 [00:34<21:40,  2.46it/s]

  2%|▏         | 77/3268 [00:35<21:41,  2.45it/s]

  2%|▏         | 78/3268 [00:35<21:40,  2.45it/s]

  2%|▏         | 79/3268 [00:36<21:39,  2.45it/s]

  2%|▏         | 80/3268 [00:36<21:38,  2.45it/s]

  2%|▏         | 81/3268 [00:36<21:39,  2.45it/s]

  3%|▎         | 82/3268 [00:37<21:41,  2.45it/s]

  3%|▎         | 83/3268 [00:37<21:41,  2.45it/s]

  3%|▎         | 84/3268 [00:38<21:39,  2.45it/s]

  3%|▎         | 85/3268 [00:38<21:40,  2.45it/s]

  3%|▎         | 86/3268 [00:38<21:38,  2.45it/s]

  3%|▎         | 87/3268 [00:39<21:38,  2.45it/s]

  3%|▎         | 88/3268 [00:39<21:38,  2.45it/s]

  3%|▎         | 89/3268 [00:40<21:37,  2.45it/s]

  3%|▎         | 90/3268 [00:40<21:36,  2.45it/s]

  3%|▎         | 91/3268 [00:40<21:38,  2.45it/s]

  3%|▎         | 92/3268 [00:41<21:37,  2.45it/s]

  3%|▎         | 93/3268 [00:41<21:36,  2.45it/s]

  3%|▎         | 94/3268 [00:42<21:35,  2.45it/s]

  3%|▎         | 95/3268 [00:42<21:33,  2.45it/s]

  3%|▎         | 96/3268 [00:43<21:34,  2.45it/s]

  3%|▎         | 97/3268 [00:43<21:35,  2.45it/s]

  3%|▎         | 98/3268 [00:43<21:34,  2.45it/s]

  3%|▎         | 99/3268 [00:44<21:34,  2.45it/s]

  3%|▎         | 100/3268 [00:44<21:33,  2.45it/s]

  3%|▎         | 101/3268 [00:45<21:32,  2.45it/s]

  3%|▎         | 102/3268 [00:45<21:32,  2.45it/s]

  3%|▎         | 103/3268 [00:45<21:32,  2.45it/s]

  3%|▎         | 104/3268 [00:46<21:32,  2.45it/s]

  3%|▎         | 105/3268 [00:46<21:32,  2.45it/s]

  3%|▎         | 106/3268 [00:47<21:31,  2.45it/s]

  3%|▎         | 107/3268 [00:47<21:32,  2.45it/s]

  3%|▎         | 108/3268 [00:47<21:29,  2.45it/s]

  3%|▎         | 109/3268 [00:48<21:29,  2.45it/s]

  3%|▎         | 110/3268 [00:48<21:29,  2.45it/s]

  3%|▎         | 111/3268 [00:49<21:30,  2.45it/s]

  3%|▎         | 112/3268 [00:49<21:28,  2.45it/s]

  3%|▎         | 113/3268 [00:49<21:28,  2.45it/s]

  3%|▎         | 114/3268 [00:50<21:28,  2.45it/s]

  4%|▎         | 115/3268 [00:50<21:27,  2.45it/s]

  4%|▎         | 116/3268 [00:51<21:27,  2.45it/s]

  4%|▎         | 117/3268 [00:51<21:26,  2.45it/s]

  4%|▎         | 118/3268 [00:52<21:28,  2.44it/s]

  4%|▎         | 119/3268 [00:52<21:32,  2.44it/s]

  4%|▎         | 120/3268 [00:52<21:31,  2.44it/s]

  4%|▎         | 121/3268 [00:53<21:29,  2.44it/s]

  4%|▎         | 122/3268 [00:53<21:27,  2.44it/s]

  4%|▍         | 123/3268 [00:54<21:27,  2.44it/s]

  4%|▍         | 124/3268 [00:54<21:26,  2.44it/s]

  4%|▍         | 125/3268 [00:54<21:24,  2.45it/s]

  4%|▍         | 126/3268 [00:55<21:23,  2.45it/s]

  4%|▍         | 127/3268 [00:55<21:22,  2.45it/s]

  4%|▍         | 128/3268 [00:56<21:20,  2.45it/s]

  4%|▍         | 129/3268 [00:56<21:23,  2.44it/s]

  4%|▍         | 130/3268 [00:56<21:22,  2.45it/s]

  4%|▍         | 131/3268 [00:57<21:21,  2.45it/s]

  4%|▍         | 132/3268 [00:57<21:20,  2.45it/s]

  4%|▍         | 133/3268 [00:58<21:20,  2.45it/s]

  4%|▍         | 134/3268 [00:58<21:19,  2.45it/s]

  4%|▍         | 135/3268 [00:58<21:18,  2.45it/s]

  4%|▍         | 136/3268 [00:59<21:18,  2.45it/s]

  4%|▍         | 137/3268 [00:59<21:16,  2.45it/s]

  4%|▍         | 138/3268 [01:00<21:16,  2.45it/s]

  4%|▍         | 139/3268 [01:00<21:18,  2.45it/s]

  4%|▍         | 140/3268 [01:01<21:17,  2.45it/s]

  4%|▍         | 141/3268 [01:01<21:17,  2.45it/s]

  4%|▍         | 142/3268 [01:01<21:16,  2.45it/s]

  4%|▍         | 143/3268 [01:02<21:16,  2.45it/s]

  4%|▍         | 144/3268 [01:02<21:16,  2.45it/s]

  4%|▍         | 145/3268 [01:03<21:14,  2.45it/s]

  4%|▍         | 146/3268 [01:03<21:16,  2.45it/s]

  4%|▍         | 147/3268 [01:03<21:16,  2.45it/s]

  5%|▍         | 148/3268 [01:04<21:16,  2.44it/s]

  5%|▍         | 149/3268 [01:04<21:18,  2.44it/s]

  5%|▍         | 150/3268 [01:05<21:17,  2.44it/s]

  5%|▍         | 151/3268 [01:05<21:15,  2.44it/s]

  5%|▍         | 152/3268 [01:05<21:13,  2.45it/s]

  5%|▍         | 153/3268 [01:06<21:13,  2.45it/s]

  5%|▍         | 154/3268 [01:06<21:12,  2.45it/s]

  5%|▍         | 155/3268 [01:07<21:11,  2.45it/s]

  5%|▍         | 156/3268 [01:07<21:11,  2.45it/s]

  5%|▍         | 157/3268 [01:07<21:10,  2.45it/s]

  5%|▍         | 158/3268 [01:08<21:09,  2.45it/s]

  5%|▍         | 159/3268 [01:08<21:09,  2.45it/s]

  5%|▍         | 160/3268 [01:09<21:09,  2.45it/s]

  5%|▍         | 161/3268 [01:09<21:08,  2.45it/s]

  5%|▍         | 162/3268 [01:09<21:10,  2.45it/s]

  5%|▍         | 163/3268 [01:10<21:08,  2.45it/s]

  5%|▌         | 164/3268 [01:10<21:07,  2.45it/s]

  5%|▌         | 165/3268 [01:11<21:07,  2.45it/s]

  5%|▌         | 166/3268 [01:11<21:07,  2.45it/s]

  5%|▌         | 167/3268 [01:12<21:05,  2.45it/s]

  5%|▌         | 168/3268 [01:12<21:05,  2.45it/s]

  5%|▌         | 169/3268 [01:12<21:06,  2.45it/s]

  5%|▌         | 170/3268 [01:13<21:05,  2.45it/s]

  5%|▌         | 171/3268 [01:13<21:06,  2.45it/s]

  5%|▌         | 172/3268 [01:14<21:06,  2.44it/s]

  5%|▌         | 173/3268 [01:14<21:06,  2.44it/s]

  5%|▌         | 174/3268 [01:14<21:05,  2.44it/s]

  5%|▌         | 175/3268 [01:15<21:05,  2.44it/s]

  5%|▌         | 176/3268 [01:15<21:06,  2.44it/s]

  5%|▌         | 177/3268 [01:16<21:06,  2.44it/s]

  5%|▌         | 178/3268 [01:16<21:08,  2.44it/s]

  5%|▌         | 179/3268 [01:16<21:06,  2.44it/s]

  6%|▌         | 180/3268 [01:17<21:04,  2.44it/s]

  6%|▌         | 181/3268 [01:17<21:04,  2.44it/s]

  6%|▌         | 182/3268 [01:18<21:04,  2.44it/s]

  6%|▌         | 183/3268 [01:18<21:03,  2.44it/s]

  6%|▌         | 184/3268 [01:19<21:02,  2.44it/s]

  6%|▌         | 185/3268 [01:19<21:03,  2.44it/s]

  6%|▌         | 186/3268 [01:19<21:02,  2.44it/s]

  6%|▌         | 187/3268 [01:20<21:02,  2.44it/s]

  6%|▌         | 188/3268 [01:20<21:01,  2.44it/s]

  6%|▌         | 189/3268 [01:21<21:02,  2.44it/s]

  6%|▌         | 190/3268 [01:21<21:02,  2.44it/s]

  6%|▌         | 191/3268 [01:21<21:01,  2.44it/s]

  6%|▌         | 192/3268 [01:22<21:01,  2.44it/s]

  6%|▌         | 193/3268 [01:22<21:00,  2.44it/s]

  6%|▌         | 194/3268 [01:23<21:00,  2.44it/s]

  6%|▌         | 195/3268 [01:23<20:59,  2.44it/s]

  6%|▌         | 196/3268 [01:23<21:00,  2.44it/s]

  6%|▌         | 197/3268 [01:24<20:58,  2.44it/s]

  6%|▌         | 198/3268 [01:24<20:58,  2.44it/s]

  6%|▌         | 199/3268 [01:25<20:58,  2.44it/s]

  6%|▌         | 200/3268 [01:25<20:59,  2.44it/s]

  6%|▌         | 201/3268 [01:25<20:57,  2.44it/s]

  6%|▌         | 202/3268 [01:26<20:57,  2.44it/s]

  6%|▌         | 203/3268 [01:26<20:56,  2.44it/s]

  6%|▌         | 204/3268 [01:27<20:55,  2.44it/s]

  6%|▋         | 205/3268 [01:27<20:56,  2.44it/s]

  6%|▋         | 206/3268 [01:28<20:56,  2.44it/s]

  6%|▋         | 207/3268 [01:28<20:56,  2.44it/s]

  6%|▋         | 208/3268 [01:28<20:55,  2.44it/s]

  6%|▋         | 209/3268 [01:29<20:56,  2.44it/s]

  6%|▋         | 210/3268 [01:29<20:56,  2.43it/s]

  6%|▋         | 211/3268 [01:30<20:54,  2.44it/s]

  6%|▋         | 212/3268 [01:30<20:53,  2.44it/s]

  7%|▋         | 213/3268 [01:30<20:52,  2.44it/s]

  7%|▋         | 214/3268 [01:31<20:52,  2.44it/s]

  7%|▋         | 215/3268 [01:31<20:51,  2.44it/s]

  7%|▋         | 216/3268 [01:32<20:51,  2.44it/s]

  7%|▋         | 217/3268 [01:32<20:51,  2.44it/s]

  7%|▋         | 218/3268 [01:32<20:50,  2.44it/s]

  7%|▋         | 219/3268 [01:33<20:53,  2.43it/s]

  7%|▋         | 220/3268 [01:33<20:53,  2.43it/s]

  7%|▋         | 221/3268 [01:34<20:51,  2.44it/s]

  7%|▋         | 222/3268 [01:34<20:50,  2.44it/s]

  7%|▋         | 223/3268 [01:35<20:52,  2.43it/s]

  7%|▋         | 224/3268 [01:35<20:50,  2.44it/s]

  7%|▋         | 225/3268 [01:35<20:48,  2.44it/s]

  7%|▋         | 226/3268 [01:36<20:48,  2.44it/s]

  7%|▋         | 227/3268 [01:36<20:48,  2.44it/s]

  7%|▋         | 228/3268 [01:37<20:49,  2.43it/s]

  7%|▋         | 229/3268 [01:37<20:50,  2.43it/s]

  7%|▋         | 230/3268 [01:37<20:48,  2.43it/s]

  7%|▋         | 231/3268 [01:38<20:47,  2.43it/s]

  7%|▋         | 232/3268 [01:38<20:47,  2.43it/s]

  7%|▋         | 233/3268 [01:39<20:46,  2.44it/s]

  7%|▋         | 234/3268 [01:39<20:45,  2.44it/s]

  7%|▋         | 235/3268 [01:39<20:44,  2.44it/s]

  7%|▋         | 236/3268 [01:40<20:44,  2.44it/s]

  7%|▋         | 237/3268 [01:40<20:42,  2.44it/s]

  7%|▋         | 238/3268 [01:41<20:43,  2.44it/s]

  7%|▋         | 239/3268 [01:41<20:44,  2.43it/s]

  7%|▋         | 240/3268 [01:41<20:43,  2.43it/s]

  7%|▋         | 241/3268 [01:42<20:42,  2.44it/s]

  7%|▋         | 242/3268 [01:42<20:44,  2.43it/s]

  7%|▋         | 243/3268 [01:43<20:42,  2.43it/s]

  7%|▋         | 244/3268 [01:43<20:40,  2.44it/s]

  7%|▋         | 245/3268 [01:44<20:40,  2.44it/s]

  8%|▊         | 246/3268 [01:44<20:40,  2.44it/s]

  8%|▊         | 247/3268 [01:44<20:40,  2.44it/s]

  8%|▊         | 248/3268 [01:45<20:41,  2.43it/s]

  8%|▊         | 249/3268 [01:45<20:40,  2.43it/s]

  8%|▊         | 250/3268 [01:46<20:41,  2.43it/s]

  8%|▊         | 251/3268 [01:46<20:41,  2.43it/s]

  8%|▊         | 252/3268 [01:46<20:39,  2.43it/s]

  8%|▊         | 253/3268 [01:47<20:41,  2.43it/s]

  8%|▊         | 254/3268 [01:47<20:39,  2.43it/s]

  8%|▊         | 255/3268 [01:48<20:39,  2.43it/s]

  8%|▊         | 256/3268 [01:48<20:37,  2.43it/s]

  8%|▊         | 257/3268 [01:48<20:36,  2.43it/s]

  8%|▊         | 258/3268 [01:49<20:37,  2.43it/s]

  8%|▊         | 259/3268 [01:49<20:38,  2.43it/s]

  8%|▊         | 260/3268 [01:50<20:39,  2.43it/s]

  8%|▊         | 261/3268 [01:50<20:37,  2.43it/s]

  8%|▊         | 262/3268 [01:51<20:39,  2.43it/s]

  8%|▊         | 263/3268 [01:51<20:39,  2.43it/s]

  8%|▊         | 264/3268 [01:51<20:38,  2.42it/s]

  8%|▊         | 265/3268 [01:52<20:36,  2.43it/s]

  8%|▊         | 266/3268 [01:52<20:36,  2.43it/s]

  8%|▊         | 267/3268 [01:53<20:35,  2.43it/s]

  8%|▊         | 268/3268 [01:53<20:35,  2.43it/s]

  8%|▊         | 269/3268 [01:53<20:35,  2.43it/s]

  8%|▊         | 270/3268 [01:54<20:34,  2.43it/s]

  8%|▊         | 271/3268 [01:54<20:34,  2.43it/s]

  8%|▊         | 272/3268 [01:55<20:32,  2.43it/s]

  8%|▊         | 273/3268 [01:55<20:31,  2.43it/s]

  8%|▊         | 274/3268 [01:55<20:31,  2.43it/s]

  8%|▊         | 275/3268 [01:56<20:31,  2.43it/s]

  8%|▊         | 276/3268 [01:56<20:29,  2.43it/s]

  8%|▊         | 277/3268 [01:57<20:30,  2.43it/s]

  9%|▊         | 278/3268 [01:57<20:28,  2.43it/s]

  9%|▊         | 279/3268 [01:58<20:28,  2.43it/s]

  9%|▊         | 280/3268 [01:58<20:30,  2.43it/s]

  9%|▊         | 281/3268 [01:58<20:29,  2.43it/s]

  9%|▊         | 282/3268 [01:59<20:29,  2.43it/s]

  9%|▊         | 283/3268 [01:59<20:29,  2.43it/s]

  9%|▊         | 284/3268 [02:00<20:28,  2.43it/s]

  9%|▊         | 285/3268 [02:00<20:29,  2.43it/s]

  9%|▉         | 286/3268 [02:00<20:29,  2.42it/s]

  9%|▉         | 287/3268 [02:01<20:29,  2.43it/s]

  9%|▉         | 288/3268 [02:01<20:29,  2.42it/s]

  9%|▉         | 289/3268 [02:02<20:33,  2.42it/s]

  9%|▉         | 290/3268 [02:02<20:33,  2.41it/s]

  9%|▉         | 291/3268 [02:02<20:32,  2.42it/s]

  9%|▉         | 292/3268 [02:03<20:30,  2.42it/s]

  9%|▉         | 293/3268 [02:03<20:31,  2.42it/s]

  9%|▉         | 294/3268 [02:04<20:29,  2.42it/s]

  9%|▉         | 295/3268 [02:04<20:27,  2.42it/s]

  9%|▉         | 296/3268 [02:05<20:26,  2.42it/s]

  9%|▉         | 297/3268 [02:05<20:24,  2.43it/s]

  9%|▉         | 298/3268 [02:05<20:23,  2.43it/s]

  9%|▉         | 299/3268 [02:06<20:26,  2.42it/s]

  9%|▉         | 300/3268 [02:06<20:25,  2.42it/s]

  9%|▉         | 301/3268 [02:07<20:26,  2.42it/s]

  9%|▉         | 302/3268 [02:07<20:24,  2.42it/s]

  9%|▉         | 303/3268 [02:07<20:23,  2.42it/s]

  9%|▉         | 304/3268 [02:08<20:22,  2.42it/s]

  9%|▉         | 305/3268 [02:08<20:21,  2.43it/s]

  9%|▉         | 306/3268 [02:09<20:29,  2.41it/s]

  9%|▉         | 307/3268 [02:09<20:27,  2.41it/s]

  9%|▉         | 308/3268 [02:10<20:24,  2.42it/s]

  9%|▉         | 309/3268 [02:10<20:24,  2.42it/s]

  9%|▉         | 310/3268 [02:10<20:23,  2.42it/s]

 10%|▉         | 311/3268 [02:11<20:21,  2.42it/s]

 10%|▉         | 312/3268 [02:11<20:21,  2.42it/s]

 10%|▉         | 313/3268 [02:12<20:20,  2.42it/s]

 10%|▉         | 314/3268 [02:12<20:20,  2.42it/s]

 10%|▉         | 315/3268 [02:12<20:17,  2.43it/s]

 10%|▉         | 316/3268 [02:13<20:17,  2.43it/s]

 10%|▉         | 317/3268 [02:13<20:17,  2.42it/s]

 10%|▉         | 318/3268 [02:14<20:17,  2.42it/s]

 10%|▉         | 319/3268 [02:14<20:23,  2.41it/s]

 10%|▉         | 320/3268 [02:14<20:21,  2.41it/s]

 10%|▉         | 321/3268 [02:15<20:18,  2.42it/s]

 10%|▉         | 322/3268 [02:15<20:16,  2.42it/s]

 10%|▉         | 323/3268 [02:16<20:15,  2.42it/s]

 10%|▉         | 324/3268 [02:16<20:14,  2.42it/s]

 10%|▉         | 325/3268 [02:17<20:17,  2.42it/s]

 10%|▉         | 326/3268 [02:17<20:15,  2.42it/s]

 10%|█         | 327/3268 [02:17<20:16,  2.42it/s]

 10%|█         | 328/3268 [02:18<20:15,  2.42it/s]

 10%|█         | 329/3268 [02:18<20:15,  2.42it/s]

 10%|█         | 330/3268 [02:19<20:13,  2.42it/s]

 10%|█         | 331/3268 [02:19<20:13,  2.42it/s]

 10%|█         | 332/3268 [02:19<20:12,  2.42it/s]

 10%|█         | 333/3268 [02:20<20:13,  2.42it/s]

 10%|█         | 334/3268 [02:20<20:12,  2.42it/s]

 10%|█         | 335/3268 [02:21<20:10,  2.42it/s]

 10%|█         | 336/3268 [02:21<20:10,  2.42it/s]

 10%|█         | 337/3268 [02:21<20:10,  2.42it/s]

 10%|█         | 338/3268 [02:22<20:11,  2.42it/s]

 10%|█         | 339/3268 [02:22<20:10,  2.42it/s]

 10%|█         | 340/3268 [02:23<20:10,  2.42it/s]

 10%|█         | 341/3268 [02:23<20:09,  2.42it/s]

 10%|█         | 342/3268 [02:24<20:07,  2.42it/s]

 10%|█         | 343/3268 [02:24<20:06,  2.42it/s]

 11%|█         | 344/3268 [02:24<20:06,  2.42it/s]

 11%|█         | 345/3268 [02:25<20:06,  2.42it/s]

 11%|█         | 346/3268 [02:25<20:06,  2.42it/s]

 11%|█         | 347/3268 [02:26<20:06,  2.42it/s]

 11%|█         | 348/3268 [02:26<20:05,  2.42it/s]

 11%|█         | 349/3268 [02:26<20:05,  2.42it/s]

 11%|█         | 350/3268 [02:27<20:04,  2.42it/s]

 11%|█         | 351/3268 [02:27<20:05,  2.42it/s]

 11%|█         | 352/3268 [02:28<20:04,  2.42it/s]

 11%|█         | 353/3268 [02:28<20:06,  2.42it/s]

 11%|█         | 354/3268 [02:29<20:04,  2.42it/s]

 11%|█         | 355/3268 [02:29<20:05,  2.42it/s]

 11%|█         | 356/3268 [02:29<20:04,  2.42it/s]

 11%|█         | 357/3268 [02:30<20:04,  2.42it/s]

 11%|█         | 358/3268 [02:30<20:02,  2.42it/s]

 11%|█         | 359/3268 [02:31<20:02,  2.42it/s]

 11%|█         | 360/3268 [02:31<20:08,  2.41it/s]

 11%|█         | 361/3268 [02:31<20:06,  2.41it/s]

 11%|█         | 362/3268 [02:32<20:04,  2.41it/s]

 11%|█         | 363/3268 [02:32<20:02,  2.42it/s]

 11%|█         | 364/3268 [02:33<20:03,  2.41it/s]

 11%|█         | 365/3268 [02:33<20:01,  2.42it/s]

 11%|█         | 366/3268 [02:33<20:02,  2.41it/s]

 11%|█         | 367/3268 [02:34<20:00,  2.42it/s]

 11%|█▏        | 368/3268 [02:34<20:00,  2.42it/s]

 11%|█▏        | 369/3268 [02:35<19:59,  2.42it/s]

 11%|█▏        | 370/3268 [02:35<19:59,  2.42it/s]

 11%|█▏        | 371/3268 [02:36<19:57,  2.42it/s]

 11%|█▏        | 372/3268 [02:36<19:57,  2.42it/s]

 11%|█▏        | 373/3268 [02:36<19:56,  2.42it/s]

 11%|█▏        | 374/3268 [02:37<19:54,  2.42it/s]

 11%|█▏        | 375/3268 [02:37<19:55,  2.42it/s]

 12%|█▏        | 376/3268 [02:38<19:55,  2.42it/s]

 12%|█▏        | 377/3268 [02:38<19:57,  2.41it/s]

 12%|█▏        | 378/3268 [02:38<19:56,  2.42it/s]

 12%|█▏        | 379/3268 [02:39<19:55,  2.42it/s]

 12%|█▏        | 380/3268 [02:39<19:55,  2.42it/s]

 12%|█▏        | 381/3268 [02:40<19:56,  2.41it/s]

 12%|█▏        | 382/3268 [02:40<19:54,  2.42it/s]

 12%|█▏        | 383/3268 [02:41<19:54,  2.42it/s]

 12%|█▏        | 384/3268 [02:41<19:52,  2.42it/s]

 12%|█▏        | 385/3268 [02:41<19:52,  2.42it/s]

 12%|█▏        | 386/3268 [02:42<19:52,  2.42it/s]

 12%|█▏        | 387/3268 [02:42<19:51,  2.42it/s]

 12%|█▏        | 388/3268 [02:43<19:53,  2.41it/s]

 12%|█▏        | 389/3268 [02:43<19:50,  2.42it/s]

 12%|█▏        | 390/3268 [02:43<19:50,  2.42it/s]

 12%|█▏        | 391/3268 [02:44<19:48,  2.42it/s]

 12%|█▏        | 392/3268 [02:44<19:48,  2.42it/s]

 12%|█▏        | 393/3268 [02:45<19:49,  2.42it/s]

 12%|█▏        | 394/3268 [02:45<19:49,  2.42it/s]

 12%|█▏        | 395/3268 [02:45<19:49,  2.41it/s]

 12%|█▏        | 396/3268 [02:46<19:49,  2.42it/s]

 12%|█▏        | 397/3268 [02:46<19:48,  2.42it/s]

 12%|█▏        | 398/3268 [02:47<19:47,  2.42it/s]

 12%|█▏        | 399/3268 [02:47<19:48,  2.41it/s]

 12%|█▏        | 400/3268 [02:48<19:47,  2.41it/s]

 12%|█▏        | 401/3268 [02:48<19:48,  2.41it/s]

 12%|█▏        | 402/3268 [02:48<19:46,  2.41it/s]

 12%|█▏        | 403/3268 [02:49<19:46,  2.41it/s]

 12%|█▏        | 404/3268 [02:49<19:45,  2.42it/s]

 12%|█▏        | 405/3268 [02:50<19:43,  2.42it/s]

 12%|█▏        | 406/3268 [02:50<19:45,  2.41it/s]

 12%|█▏        | 407/3268 [02:50<19:43,  2.42it/s]

 12%|█▏        | 408/3268 [02:51<19:44,  2.41it/s]

 13%|█▎        | 409/3268 [02:51<19:44,  2.41it/s]

 13%|█▎        | 410/3268 [02:52<19:43,  2.42it/s]

 13%|█▎        | 411/3268 [02:52<19:41,  2.42it/s]

 13%|█▎        | 412/3268 [02:53<19:42,  2.41it/s]

 13%|█▎        | 413/3268 [02:53<19:41,  2.42it/s]

 13%|█▎        | 414/3268 [02:53<19:41,  2.42it/s]

 13%|█▎        | 415/3268 [02:54<19:39,  2.42it/s]

 13%|█▎        | 416/3268 [02:54<19:41,  2.41it/s]

 13%|█▎        | 417/3268 [02:55<19:39,  2.42it/s]

 13%|█▎        | 418/3268 [02:55<19:40,  2.41it/s]

 13%|█▎        | 419/3268 [02:55<19:40,  2.41it/s]

 13%|█▎        | 420/3268 [02:56<19:39,  2.42it/s]

 13%|█▎        | 421/3268 [02:56<19:38,  2.42it/s]

 13%|█▎        | 422/3268 [02:57<19:39,  2.41it/s]

 13%|█▎        | 423/3268 [02:57<19:38,  2.41it/s]

 13%|█▎        | 424/3268 [02:57<19:38,  2.41it/s]

 13%|█▎        | 425/3268 [02:58<19:38,  2.41it/s]

 13%|█▎        | 426/3268 [02:58<19:37,  2.41it/s]

 13%|█▎        | 427/3268 [02:59<19:38,  2.41it/s]

 13%|█▎        | 428/3268 [02:59<19:36,  2.41it/s]

 13%|█▎        | 429/3268 [03:00<19:37,  2.41it/s]

 13%|█▎        | 430/3268 [03:00<19:36,  2.41it/s]

 13%|█▎        | 431/3268 [03:00<19:35,  2.41it/s]

 13%|█▎        | 432/3268 [03:01<19:34,  2.42it/s]

 13%|█▎        | 433/3268 [03:01<19:34,  2.41it/s]

 13%|█▎        | 434/3268 [03:02<19:33,  2.42it/s]

 13%|█▎        | 435/3268 [03:02<19:32,  2.42it/s]

 13%|█▎        | 436/3268 [03:02<19:31,  2.42it/s]

 13%|█▎        | 437/3268 [03:03<19:30,  2.42it/s]

 13%|█▎        | 438/3268 [03:03<19:28,  2.42it/s]

 13%|█▎        | 439/3268 [03:04<19:28,  2.42it/s]

 13%|█▎        | 440/3268 [03:04<19:29,  2.42it/s]

 13%|█▎        | 441/3268 [03:05<19:29,  2.42it/s]

 14%|█▎        | 442/3268 [03:05<19:29,  2.42it/s]

 14%|█▎        | 443/3268 [03:05<19:30,  2.41it/s]

 14%|█▎        | 444/3268 [03:06<19:30,  2.41it/s]

 14%|█▎        | 445/3268 [03:06<19:30,  2.41it/s]

 14%|█▎        | 446/3268 [03:07<19:31,  2.41it/s]

 14%|█▎        | 447/3268 [03:07<19:30,  2.41it/s]

 14%|█▎        | 448/3268 [03:07<19:30,  2.41it/s]

 14%|█▎        | 449/3268 [03:08<19:28,  2.41it/s]

 14%|█▍        | 450/3268 [03:08<19:26,  2.42it/s]

 14%|█▍        | 451/3268 [03:09<19:26,  2.42it/s]

 14%|█▍        | 452/3268 [03:09<19:27,  2.41it/s]

 14%|█▍        | 453/3268 [03:09<19:26,  2.41it/s]

 14%|█▍        | 454/3268 [03:10<19:27,  2.41it/s]

 14%|█▍        | 455/3268 [03:10<19:27,  2.41it/s]

 14%|█▍        | 456/3268 [03:11<19:26,  2.41it/s]

 14%|█▍        | 457/3268 [03:11<19:26,  2.41it/s]

 14%|█▍        | 458/3268 [03:12<19:25,  2.41it/s]

 14%|█▍        | 459/3268 [03:12<19:25,  2.41it/s]

 14%|█▍        | 460/3268 [03:12<19:25,  2.41it/s]

 14%|█▍        | 461/3268 [03:13<19:24,  2.41it/s]

 14%|█▍        | 462/3268 [03:13<19:23,  2.41it/s]

 14%|█▍        | 463/3268 [03:14<19:25,  2.41it/s]

 14%|█▍        | 464/3268 [03:14<19:23,  2.41it/s]

 14%|█▍        | 465/3268 [03:14<19:24,  2.41it/s]

 14%|█▍        | 466/3268 [03:15<19:22,  2.41it/s]

 14%|█▍        | 467/3268 [03:15<19:20,  2.41it/s]

 14%|█▍        | 468/3268 [03:16<19:20,  2.41it/s]

 14%|█▍        | 469/3268 [03:16<19:21,  2.41it/s]

 14%|█▍        | 470/3268 [03:17<19:19,  2.41it/s]

 14%|█▍        | 471/3268 [03:17<19:20,  2.41it/s]

 14%|█▍        | 472/3268 [03:17<19:20,  2.41it/s]

 14%|█▍        | 473/3268 [03:18<19:19,  2.41it/s]

 15%|█▍        | 474/3268 [03:18<19:18,  2.41it/s]

 15%|█▍        | 475/3268 [03:19<19:19,  2.41it/s]

 15%|█▍        | 476/3268 [03:19<19:18,  2.41it/s]

 15%|█▍        | 477/3268 [03:19<19:17,  2.41it/s]

 15%|█▍        | 478/3268 [03:20<19:18,  2.41it/s]

 15%|█▍        | 479/3268 [03:20<19:17,  2.41it/s]

 15%|█▍        | 480/3268 [03:21<19:22,  2.40it/s]

 15%|█▍        | 481/3268 [03:21<19:20,  2.40it/s]

 15%|█▍        | 482/3268 [03:22<19:18,  2.40it/s]

 15%|█▍        | 483/3268 [03:22<19:16,  2.41it/s]

 15%|█▍        | 484/3268 [03:22<19:16,  2.41it/s]

 15%|█▍        | 485/3268 [03:23<19:16,  2.41it/s]

 15%|█▍        | 486/3268 [03:23<19:15,  2.41it/s]

 15%|█▍        | 487/3268 [03:24<19:14,  2.41it/s]

 15%|█▍        | 488/3268 [03:24<19:15,  2.41it/s]

 15%|█▍        | 489/3268 [03:24<19:13,  2.41it/s]

 15%|█▍        | 490/3268 [03:25<19:13,  2.41it/s]

 15%|█▌        | 491/3268 [03:25<19:14,  2.41it/s]

 15%|█▌        | 492/3268 [03:26<19:13,  2.41it/s]

 15%|█▌        | 493/3268 [03:26<19:12,  2.41it/s]

 15%|█▌        | 494/3268 [03:27<19:12,  2.41it/s]

 15%|█▌        | 495/3268 [03:27<19:12,  2.41it/s]

 15%|█▌        | 496/3268 [03:27<19:11,  2.41it/s]

 15%|█▌        | 497/3268 [03:28<19:10,  2.41it/s]

 15%|█▌        | 498/3268 [03:28<19:10,  2.41it/s]

 15%|█▌        | 499/3268 [03:29<19:09,  2.41it/s]

 15%|█▌        | 500/3268 [03:29<19:10,  2.41it/s]

 15%|█▌        | 501/3268 [03:29<19:09,  2.41it/s]

 15%|█▌        | 502/3268 [03:30<19:07,  2.41it/s]

 15%|█▌        | 503/3268 [03:30<19:10,  2.40it/s]

 15%|█▌        | 504/3268 [03:31<19:09,  2.41it/s]

 15%|█▌        | 505/3268 [03:31<19:08,  2.40it/s]

 15%|█▌        | 506/3268 [03:32<19:07,  2.41it/s]

 16%|█▌        | 507/3268 [03:32<19:06,  2.41it/s]

 16%|█▌        | 508/3268 [03:32<19:04,  2.41it/s]

 16%|█▌        | 509/3268 [03:33<19:08,  2.40it/s]

 16%|█▌        | 510/3268 [03:33<19:08,  2.40it/s]

 16%|█▌        | 511/3268 [03:34<19:05,  2.41it/s]

 16%|█▌        | 512/3268 [03:34<19:05,  2.41it/s]

 16%|█▌        | 513/3268 [03:34<19:07,  2.40it/s]

 16%|█▌        | 514/3268 [03:35<19:04,  2.41it/s]

 16%|█▌        | 515/3268 [03:35<19:04,  2.40it/s]

 16%|█▌        | 516/3268 [03:36<19:03,  2.41it/s]

 16%|█▌        | 517/3268 [03:36<19:04,  2.40it/s]

 16%|█▌        | 518/3268 [03:36<19:04,  2.40it/s]

 16%|█▌        | 519/3268 [03:37<19:02,  2.41it/s]

 16%|█▌        | 520/3268 [03:37<19:02,  2.40it/s]

 16%|█▌        | 521/3268 [03:38<19:02,  2.41it/s]

 16%|█▌        | 522/3268 [03:38<19:01,  2.41it/s]

 16%|█▌        | 523/3268 [03:39<19:00,  2.41it/s]

 16%|█▌        | 524/3268 [03:39<18:59,  2.41it/s]

 16%|█▌        | 525/3268 [03:39<18:59,  2.41it/s]

 16%|█▌        | 526/3268 [03:40<19:06,  2.39it/s]

 16%|█▌        | 527/3268 [03:40<19:06,  2.39it/s]

 16%|█▌        | 528/3268 [03:41<19:06,  2.39it/s]

 16%|█▌        | 529/3268 [03:41<19:03,  2.40it/s]

 16%|█▌        | 530/3268 [03:42<19:02,  2.40it/s]

 16%|█▌        | 531/3268 [03:42<19:00,  2.40it/s]

 16%|█▋        | 532/3268 [03:42<19:01,  2.40it/s]

 16%|█▋        | 533/3268 [03:43<18:58,  2.40it/s]

 16%|█▋        | 534/3268 [03:43<18:59,  2.40it/s]

 16%|█▋        | 535/3268 [03:44<18:56,  2.40it/s]

 16%|█▋        | 536/3268 [03:44<18:56,  2.40it/s]

 16%|█▋        | 537/3268 [03:44<18:55,  2.40it/s]

 16%|█▋        | 538/3268 [03:45<18:57,  2.40it/s]

 16%|█▋        | 539/3268 [03:45<18:56,  2.40it/s]

 17%|█▋        | 540/3268 [03:46<18:55,  2.40it/s]

 17%|█▋        | 541/3268 [03:46<18:54,  2.40it/s]

 17%|█▋        | 542/3268 [03:46<18:56,  2.40it/s]

 17%|█▋        | 543/3268 [03:47<18:53,  2.40it/s]

 17%|█▋        | 544/3268 [03:47<18:54,  2.40it/s]

 17%|█▋        | 545/3268 [03:48<18:54,  2.40it/s]

 17%|█▋        | 546/3268 [03:48<18:53,  2.40it/s]

 17%|█▋        | 547/3268 [03:49<18:52,  2.40it/s]

 17%|█▋        | 548/3268 [03:49<18:50,  2.41it/s]

 17%|█▋        | 549/3268 [03:49<18:51,  2.40it/s]

 17%|█▋        | 550/3268 [03:50<18:49,  2.41it/s]

 17%|█▋        | 551/3268 [03:50<18:50,  2.40it/s]

 17%|█▋        | 552/3268 [03:51<18:51,  2.40it/s]

 17%|█▋        | 553/3268 [03:51<18:49,  2.40it/s]

 17%|█▋        | 554/3268 [03:51<18:51,  2.40it/s]

 17%|█▋        | 555/3268 [03:52<18:49,  2.40it/s]

 17%|█▋        | 556/3268 [03:52<18:49,  2.40it/s]

 17%|█▋        | 557/3268 [03:53<18:49,  2.40it/s]

 17%|█▋        | 558/3268 [03:53<18:52,  2.39it/s]

 17%|█▋        | 559/3268 [03:54<18:51,  2.40it/s]

 17%|█▋        | 560/3268 [03:54<18:50,  2.40it/s]

 17%|█▋        | 561/3268 [03:54<18:46,  2.40it/s]

 17%|█▋        | 562/3268 [03:55<18:46,  2.40it/s]

 17%|█▋        | 563/3268 [03:55<18:47,  2.40it/s]

 17%|█▋        | 564/3268 [03:56<18:49,  2.39it/s]

 17%|█▋        | 565/3268 [03:56<18:48,  2.39it/s]

 17%|█▋        | 566/3268 [03:56<18:46,  2.40it/s]

 17%|█▋        | 567/3268 [03:57<18:47,  2.40it/s]

 17%|█▋        | 568/3268 [03:57<18:47,  2.40it/s]

 17%|█▋        | 569/3268 [03:58<18:45,  2.40it/s]

 17%|█▋        | 570/3268 [03:58<18:44,  2.40it/s]

 17%|█▋        | 571/3268 [03:59<18:42,  2.40it/s]

 18%|█▊        | 572/3268 [03:59<18:42,  2.40it/s]

 18%|█▊        | 573/3268 [03:59<18:41,  2.40it/s]

 18%|█▊        | 574/3268 [04:00<18:42,  2.40it/s]

 18%|█▊        | 575/3268 [04:00<18:41,  2.40it/s]

 18%|█▊        | 576/3268 [04:01<18:41,  2.40it/s]

 18%|█▊        | 577/3268 [04:01<18:42,  2.40it/s]

 18%|█▊        | 578/3268 [04:01<18:39,  2.40it/s]

 18%|█▊        | 579/3268 [04:02<18:40,  2.40it/s]

 18%|█▊        | 580/3268 [04:02<18:40,  2.40it/s]

 18%|█▊        | 581/3268 [04:03<18:38,  2.40it/s]

 18%|█▊        | 582/3268 [04:03<18:39,  2.40it/s]

 18%|█▊        | 583/3268 [04:04<18:39,  2.40it/s]

 18%|█▊        | 584/3268 [04:04<18:38,  2.40it/s]

 18%|█▊        | 585/3268 [04:04<18:37,  2.40it/s]

 18%|█▊        | 586/3268 [04:05<18:37,  2.40it/s]

 18%|█▊        | 587/3268 [04:05<18:37,  2.40it/s]

 18%|█▊        | 588/3268 [04:06<18:35,  2.40it/s]

 18%|█▊        | 589/3268 [04:06<18:37,  2.40it/s]

 18%|█▊        | 590/3268 [04:06<18:39,  2.39it/s]

 18%|█▊        | 591/3268 [04:07<18:37,  2.39it/s]

 18%|█▊        | 592/3268 [04:07<18:34,  2.40it/s]

 18%|█▊        | 593/3268 [04:08<18:36,  2.40it/s]

 18%|█▊        | 594/3268 [04:08<18:35,  2.40it/s]

 18%|█▊        | 595/3268 [04:09<18:36,  2.39it/s]

 18%|█▊        | 596/3268 [04:09<18:35,  2.39it/s]

 18%|█▊        | 597/3268 [04:09<18:37,  2.39it/s]

 18%|█▊        | 598/3268 [04:10<18:35,  2.39it/s]

 18%|█▊        | 599/3268 [04:10<18:33,  2.40it/s]

 18%|█▊        | 600/3268 [04:11<18:31,  2.40it/s]

 18%|█▊        | 601/3268 [04:11<18:32,  2.40it/s]

 18%|█▊        | 602/3268 [04:12<18:30,  2.40it/s]

 18%|█▊        | 603/3268 [04:12<18:32,  2.40it/s]

 18%|█▊        | 604/3268 [04:12<18:31,  2.40it/s]

 19%|█▊        | 605/3268 [04:13<18:31,  2.40it/s]

 19%|█▊        | 606/3268 [04:13<18:30,  2.40it/s]

 19%|█▊        | 607/3268 [04:14<18:29,  2.40it/s]

 19%|█▊        | 608/3268 [04:14<18:29,  2.40it/s]

 19%|█▊        | 609/3268 [04:14<18:30,  2.39it/s]

 19%|█▊        | 610/3268 [04:15<18:30,  2.39it/s]

 19%|█▊        | 611/3268 [04:15<18:28,  2.40it/s]

 19%|█▊        | 612/3268 [04:16<18:26,  2.40it/s]

 19%|█▉        | 613/3268 [04:16<18:25,  2.40it/s]

 19%|█▉        | 614/3268 [04:17<18:26,  2.40it/s]

 19%|█▉        | 615/3268 [04:17<18:26,  2.40it/s]

 19%|█▉        | 616/3268 [04:17<18:25,  2.40it/s]

 19%|█▉        | 617/3268 [04:18<18:24,  2.40it/s]

 19%|█▉        | 618/3268 [04:18<18:24,  2.40it/s]

 19%|█▉        | 619/3268 [04:19<18:25,  2.40it/s]

 19%|█▉        | 620/3268 [04:19<18:26,  2.39it/s]

 19%|█▉        | 621/3268 [04:19<18:24,  2.40it/s]

 19%|█▉        | 622/3268 [04:20<18:26,  2.39it/s]

 19%|█▉        | 623/3268 [04:20<18:25,  2.39it/s]

 19%|█▉        | 624/3268 [04:21<18:25,  2.39it/s]

 19%|█▉        | 625/3268 [04:21<18:23,  2.40it/s]

logging
logging the anndata

 19%|█▉        | 626/3268 [04:22<18:58,  2.32it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 19%|█▉        | 627/3268 [04:22<18:43,  2.35it/s]

 19%|█▉        | 628/3268 [04:22<18:29,  2.38it/s]

 19%|█▉        | 629/3268 [04:23<18:21,  2.40it/s]

 19%|█▉        | 630/3268 [04:23<18:15,  2.41it/s]

 19%|█▉        | 631/3268 [04:24<18:10,  2.42it/s]

 19%|█▉        | 632/3268 [04:24<18:05,  2.43it/s]

 19%|█▉        | 633/3268 [04:24<18:03,  2.43it/s]

 19%|█▉        | 634/3268 [04:25<18:03,  2.43it/s]

 19%|█▉        | 635/3268 [04:25<18:01,  2.43it/s]

 19%|█▉        | 636/3268 [04:26<18:00,  2.44it/s]

 19%|█▉        | 637/3268 [04:26<17:58,  2.44it/s]

 20%|█▉        | 638/3268 [04:26<17:57,  2.44it/s]

 20%|█▉        | 639/3268 [04:27<17:59,  2.44it/s]

 20%|█▉        | 640/3268 [04:27<17:57,  2.44it/s]

 20%|█▉        | 641/3268 [04:28<17:56,  2.44it/s]

 20%|█▉        | 642/3268 [04:28<17:55,  2.44it/s]

 20%|█▉        | 643/3268 [04:29<17:57,  2.44it/s]

 20%|█▉        | 644/3268 [04:29<17:55,  2.44it/s]

 20%|█▉        | 645/3268 [04:29<17:55,  2.44it/s]

 20%|█▉        | 646/3268 [04:30<17:54,  2.44it/s]

 20%|█▉        | 647/3268 [04:30<17:55,  2.44it/s]

 20%|█▉        | 648/3268 [04:31<17:53,  2.44it/s]

 20%|█▉        | 649/3268 [04:31<17:53,  2.44it/s]

 20%|█▉        | 650/3268 [04:31<17:51,  2.44it/s]

 20%|█▉        | 651/3268 [04:32<17:51,  2.44it/s]

 20%|█▉        | 652/3268 [04:32<17:53,  2.44it/s]

 20%|█▉        | 653/3268 [04:33<17:51,  2.44it/s]

 20%|██        | 654/3268 [04:33<17:51,  2.44it/s]

 20%|██        | 655/3268 [04:33<17:51,  2.44it/s]

 20%|██        | 656/3268 [04:34<17:52,  2.44it/s]

 20%|██        | 657/3268 [04:34<17:53,  2.43it/s]

 20%|██        | 658/3268 [04:35<17:53,  2.43it/s]

 20%|██        | 659/3268 [04:35<17:51,  2.43it/s]

 20%|██        | 660/3268 [04:36<17:50,  2.44it/s]

 20%|██        | 661/3268 [04:36<17:49,  2.44it/s]

 20%|██        | 662/3268 [04:36<17:48,  2.44it/s]

 20%|██        | 663/3268 [04:37<17:48,  2.44it/s]

 20%|██        | 664/3268 [04:37<17:48,  2.44it/s]

 20%|██        | 665/3268 [04:38<17:49,  2.43it/s]

 20%|██        | 666/3268 [04:38<17:48,  2.43it/s]

 20%|██        | 667/3268 [04:38<17:49,  2.43it/s]

 20%|██        | 668/3268 [04:39<17:50,  2.43it/s]

 20%|██        | 669/3268 [04:39<17:49,  2.43it/s]

 21%|██        | 670/3268 [04:40<17:47,  2.43it/s]

 21%|██        | 671/3268 [04:40<17:45,  2.44it/s]

 21%|██        | 672/3268 [04:40<17:44,  2.44it/s]

 21%|██        | 673/3268 [04:41<17:43,  2.44it/s]

 21%|██        | 674/3268 [04:41<17:44,  2.44it/s]

 21%|██        | 675/3268 [04:42<17:43,  2.44it/s]

 21%|██        | 676/3268 [04:42<17:44,  2.43it/s]

 21%|██        | 677/3268 [04:42<17:44,  2.43it/s]

 21%|██        | 678/3268 [04:43<17:43,  2.44it/s]

 21%|██        | 679/3268 [04:43<17:42,  2.44it/s]

 21%|██        | 680/3268 [04:44<17:42,  2.44it/s]

 21%|██        | 681/3268 [04:44<17:42,  2.44it/s]

 21%|██        | 682/3268 [04:45<17:40,  2.44it/s]

 21%|██        | 683/3268 [04:45<17:40,  2.44it/s]

 21%|██        | 684/3268 [04:45<17:39,  2.44it/s]

 21%|██        | 685/3268 [04:46<17:40,  2.44it/s]

 21%|██        | 686/3268 [04:46<17:38,  2.44it/s]

 21%|██        | 687/3268 [04:47<17:39,  2.44it/s]

 21%|██        | 688/3268 [04:47<17:38,  2.44it/s]

 21%|██        | 689/3268 [04:47<17:38,  2.44it/s]

 21%|██        | 690/3268 [04:48<17:39,  2.43it/s]

 21%|██        | 691/3268 [04:48<17:38,  2.43it/s]

 21%|██        | 692/3268 [04:49<17:37,  2.43it/s]

 21%|██        | 693/3268 [04:49<17:36,  2.44it/s]

 21%|██        | 694/3268 [04:49<17:36,  2.44it/s]

 21%|██▏       | 695/3268 [04:50<17:35,  2.44it/s]

 21%|██▏       | 696/3268 [04:50<17:35,  2.44it/s]

 21%|██▏       | 697/3268 [04:51<17:33,  2.44it/s]

 21%|██▏       | 698/3268 [04:51<17:33,  2.44it/s]

 21%|██▏       | 699/3268 [04:52<17:34,  2.44it/s]

 21%|██▏       | 700/3268 [04:52<17:32,  2.44it/s]

 21%|██▏       | 701/3268 [04:52<17:33,  2.44it/s]

 21%|██▏       | 702/3268 [04:53<17:33,  2.44it/s]

 22%|██▏       | 703/3268 [04:53<17:32,  2.44it/s]

 22%|██▏       | 704/3268 [04:54<17:34,  2.43it/s]

 22%|██▏       | 705/3268 [04:54<17:33,  2.43it/s]

 22%|██▏       | 706/3268 [04:54<17:33,  2.43it/s]

 22%|██▏       | 707/3268 [04:55<17:31,  2.43it/s]

 22%|██▏       | 708/3268 [04:55<17:31,  2.43it/s]

 22%|██▏       | 709/3268 [04:56<17:30,  2.44it/s]

 22%|██▏       | 710/3268 [04:56<17:30,  2.44it/s]

 22%|██▏       | 711/3268 [04:56<17:30,  2.43it/s]

 22%|██▏       | 712/3268 [04:57<17:30,  2.43it/s]

 22%|██▏       | 713/3268 [04:57<17:30,  2.43it/s]

 22%|██▏       | 714/3268 [04:58<17:28,  2.44it/s]

 22%|██▏       | 715/3268 [04:58<17:28,  2.43it/s]

 22%|██▏       | 716/3268 [04:58<17:29,  2.43it/s]

 22%|██▏       | 717/3268 [04:59<17:28,  2.43it/s]

 22%|██▏       | 718/3268 [04:59<17:27,  2.44it/s]

 22%|██▏       | 719/3268 [05:00<17:25,  2.44it/s]

 22%|██▏       | 720/3268 [05:00<17:25,  2.44it/s]

 22%|██▏       | 721/3268 [05:01<17:25,  2.44it/s]

 22%|██▏       | 722/3268 [05:01<17:25,  2.44it/s]

 22%|██▏       | 723/3268 [05:01<17:31,  2.42it/s]

 22%|██▏       | 724/3268 [05:02<17:28,  2.43it/s]

 22%|██▏       | 725/3268 [05:02<17:28,  2.43it/s]

 22%|██▏       | 726/3268 [05:03<17:27,  2.43it/s]

 22%|██▏       | 727/3268 [05:03<17:27,  2.43it/s]

 22%|██▏       | 728/3268 [05:03<17:25,  2.43it/s]

 22%|██▏       | 729/3268 [05:04<17:26,  2.43it/s]

 22%|██▏       | 730/3268 [05:04<17:25,  2.43it/s]

 22%|██▏       | 731/3268 [05:05<17:24,  2.43it/s]

 22%|██▏       | 732/3268 [05:05<17:23,  2.43it/s]

 22%|██▏       | 733/3268 [05:05<17:22,  2.43it/s]

 22%|██▏       | 734/3268 [05:06<17:22,  2.43it/s]

 22%|██▏       | 735/3268 [05:06<17:21,  2.43it/s]

 23%|██▎       | 736/3268 [05:07<17:21,  2.43it/s]

 23%|██▎       | 737/3268 [05:07<17:24,  2.42it/s]

 23%|██▎       | 738/3268 [05:08<17:23,  2.42it/s]

 23%|██▎       | 739/3268 [05:08<17:21,  2.43it/s]

 23%|██▎       | 740/3268 [05:08<17:22,  2.43it/s]

 23%|██▎       | 741/3268 [05:09<17:20,  2.43it/s]

 23%|██▎       | 742/3268 [05:09<17:19,  2.43it/s]

 23%|██▎       | 743/3268 [05:10<17:18,  2.43it/s]

 23%|██▎       | 744/3268 [05:10<17:17,  2.43it/s]

 23%|██▎       | 745/3268 [05:10<17:17,  2.43it/s]

 23%|██▎       | 746/3268 [05:11<17:16,  2.43it/s]

 23%|██▎       | 747/3268 [05:11<17:17,  2.43it/s]

 23%|██▎       | 748/3268 [05:12<17:15,  2.43it/s]

 23%|██▎       | 749/3268 [05:12<17:16,  2.43it/s]

 23%|██▎       | 750/3268 [05:12<17:15,  2.43it/s]

 23%|██▎       | 751/3268 [05:13<17:17,  2.43it/s]

 23%|██▎       | 752/3268 [05:13<17:14,  2.43it/s]

 23%|██▎       | 753/3268 [05:14<17:14,  2.43it/s]

 23%|██▎       | 754/3268 [05:14<17:12,  2.44it/s]

 23%|██▎       | 755/3268 [05:15<17:12,  2.43it/s]

 23%|██▎       | 756/3268 [05:15<17:16,  2.42it/s]

 23%|██▎       | 757/3268 [05:15<17:14,  2.43it/s]

 23%|██▎       | 758/3268 [05:16<17:14,  2.43it/s]

 23%|██▎       | 759/3268 [05:16<17:13,  2.43it/s]

 23%|██▎       | 760/3268 [05:17<17:14,  2.42it/s]

 23%|██▎       | 761/3268 [05:17<17:13,  2.43it/s]

 23%|██▎       | 762/3268 [05:17<17:12,  2.43it/s]

 23%|██▎       | 763/3268 [05:18<17:11,  2.43it/s]

 23%|██▎       | 764/3268 [05:18<17:11,  2.43it/s]

 23%|██▎       | 765/3268 [05:19<17:10,  2.43it/s]

 23%|██▎       | 766/3268 [05:19<17:11,  2.43it/s]

 23%|██▎       | 767/3268 [05:19<17:08,  2.43it/s]

 24%|██▎       | 768/3268 [05:20<17:08,  2.43it/s]

 24%|██▎       | 769/3268 [05:20<17:09,  2.43it/s]

 24%|██▎       | 770/3268 [05:21<17:08,  2.43it/s]

 24%|██▎       | 771/3268 [05:21<17:09,  2.43it/s]

 24%|██▎       | 772/3268 [05:22<17:08,  2.43it/s]

 24%|██▎       | 773/3268 [05:22<17:08,  2.43it/s]

 24%|██▎       | 774/3268 [05:22<17:07,  2.43it/s]

 24%|██▎       | 775/3268 [05:23<17:07,  2.43it/s]

 24%|██▎       | 776/3268 [05:23<17:06,  2.43it/s]

 24%|██▍       | 777/3268 [05:24<17:05,  2.43it/s]

 24%|██▍       | 778/3268 [05:24<17:05,  2.43it/s]

 24%|██▍       | 779/3268 [05:24<17:05,  2.43it/s]

 24%|██▍       | 780/3268 [05:25<17:05,  2.43it/s]

 24%|██▍       | 781/3268 [05:25<17:05,  2.43it/s]

 24%|██▍       | 782/3268 [05:26<17:04,  2.43it/s]

 24%|██▍       | 783/3268 [05:26<17:03,  2.43it/s]

 24%|██▍       | 784/3268 [05:26<17:03,  2.43it/s]

 24%|██▍       | 785/3268 [05:27<17:02,  2.43it/s]

 24%|██▍       | 786/3268 [05:27<17:01,  2.43it/s]

 24%|██▍       | 787/3268 [05:28<17:00,  2.43it/s]

 24%|██▍       | 788/3268 [05:28<17:00,  2.43it/s]

 24%|██▍       | 789/3268 [05:29<17:00,  2.43it/s]

 24%|██▍       | 790/3268 [05:29<17:00,  2.43it/s]

 24%|██▍       | 791/3268 [05:29<17:00,  2.43it/s]

 24%|██▍       | 792/3268 [05:30<16:59,  2.43it/s]

 24%|██▍       | 793/3268 [05:30<16:59,  2.43it/s]

 24%|██▍       | 794/3268 [05:31<16:59,  2.43it/s]

 24%|██▍       | 795/3268 [05:31<16:58,  2.43it/s]

 24%|██▍       | 796/3268 [05:31<16:57,  2.43it/s]

 24%|██▍       | 797/3268 [05:32<16:57,  2.43it/s]

 24%|██▍       | 798/3268 [05:32<16:56,  2.43it/s]

 24%|██▍       | 799/3268 [05:33<16:57,  2.43it/s]

 24%|██▍       | 800/3268 [05:33<16:56,  2.43it/s]

 25%|██▍       | 801/3268 [05:33<16:57,  2.43it/s]

 25%|██▍       | 802/3268 [05:34<16:56,  2.43it/s]

 25%|██▍       | 803/3268 [05:34<16:57,  2.42it/s]

 25%|██▍       | 804/3268 [05:35<16:57,  2.42it/s]

 25%|██▍       | 805/3268 [05:35<16:59,  2.42it/s]

 25%|██▍       | 806/3268 [05:36<16:58,  2.42it/s]

 25%|██▍       | 807/3268 [05:36<16:56,  2.42it/s]

 25%|██▍       | 808/3268 [05:36<16:56,  2.42it/s]

 25%|██▍       | 809/3268 [05:37<16:54,  2.42it/s]

 25%|██▍       | 810/3268 [05:37<16:54,  2.42it/s]

 25%|██▍       | 811/3268 [05:38<16:54,  2.42it/s]

 25%|██▍       | 812/3268 [05:38<16:54,  2.42it/s]

 25%|██▍       | 813/3268 [05:38<16:52,  2.42it/s]

 25%|██▍       | 814/3268 [05:39<16:52,  2.42it/s]

 25%|██▍       | 815/3268 [05:39<16:51,  2.42it/s]

 25%|██▍       | 816/3268 [05:40<16:51,  2.42it/s]

 25%|██▌       | 817/3268 [05:40<16:51,  2.42it/s]

 25%|██▌       | 818/3268 [05:41<16:49,  2.43it/s]

 25%|██▌       | 819/3268 [05:41<16:48,  2.43it/s]

 25%|██▌       | 820/3268 [05:41<16:48,  2.43it/s]

 25%|██▌       | 821/3268 [05:42<16:48,  2.43it/s]

 25%|██▌       | 822/3268 [05:42<16:48,  2.42it/s]

 25%|██▌       | 823/3268 [05:43<16:49,  2.42it/s]

 25%|██▌       | 824/3268 [05:43<16:47,  2.43it/s]

 25%|██▌       | 825/3268 [05:43<16:46,  2.43it/s]

 25%|██▌       | 826/3268 [05:44<16:46,  2.43it/s]

 25%|██▌       | 827/3268 [05:44<16:47,  2.42it/s]

 25%|██▌       | 828/3268 [05:45<16:46,  2.42it/s]

 25%|██▌       | 829/3268 [05:45<16:45,  2.43it/s]

 25%|██▌       | 830/3268 [05:45<16:44,  2.43it/s]

 25%|██▌       | 831/3268 [05:46<16:44,  2.43it/s]

 25%|██▌       | 832/3268 [05:46<16:44,  2.42it/s]

 25%|██▌       | 833/3268 [05:47<16:43,  2.43it/s]

 26%|██▌       | 834/3268 [05:47<16:43,  2.43it/s]

 26%|██▌       | 835/3268 [05:48<16:42,  2.43it/s]

 26%|██▌       | 836/3268 [05:48<16:43,  2.42it/s]

 26%|██▌       | 837/3268 [05:48<16:42,  2.42it/s]

 26%|██▌       | 838/3268 [05:49<16:43,  2.42it/s]

 26%|██▌       | 839/3268 [05:49<16:41,  2.43it/s]

 26%|██▌       | 840/3268 [05:50<16:41,  2.43it/s]

 26%|██▌       | 841/3268 [05:50<16:40,  2.42it/s]

 26%|██▌       | 842/3268 [05:50<16:40,  2.43it/s]

 26%|██▌       | 843/3268 [05:51<16:40,  2.42it/s]

 26%|██▌       | 844/3268 [05:51<16:39,  2.43it/s]

 26%|██▌       | 845/3268 [05:52<16:40,  2.42it/s]

 26%|██▌       | 846/3268 [05:52<16:38,  2.42it/s]

 26%|██▌       | 847/3268 [05:52<16:39,  2.42it/s]

 26%|██▌       | 848/3268 [05:53<16:39,  2.42it/s]

 26%|██▌       | 849/3268 [05:53<16:39,  2.42it/s]

 26%|██▌       | 850/3268 [05:54<16:38,  2.42it/s]

 26%|██▌       | 851/3268 [05:54<16:37,  2.42it/s]

 26%|██▌       | 852/3268 [05:55<16:36,  2.42it/s]

 26%|██▌       | 853/3268 [05:55<16:37,  2.42it/s]

 26%|██▌       | 854/3268 [05:55<16:36,  2.42it/s]

 26%|██▌       | 855/3268 [05:56<16:36,  2.42it/s]

 26%|██▌       | 856/3268 [05:56<16:35,  2.42it/s]

 26%|██▌       | 857/3268 [05:57<16:35,  2.42it/s]

 26%|██▋       | 858/3268 [05:57<16:34,  2.42it/s]

 26%|██▋       | 859/3268 [05:57<16:33,  2.42it/s]

 26%|██▋       | 860/3268 [05:58<16:35,  2.42it/s]

 26%|██▋       | 861/3268 [05:58<16:33,  2.42it/s]

 26%|██▋       | 862/3268 [05:59<16:32,  2.42it/s]

 26%|██▋       | 863/3268 [05:59<16:32,  2.42it/s]

 26%|██▋       | 864/3268 [05:59<16:32,  2.42it/s]

 26%|██▋       | 865/3268 [06:00<16:31,  2.42it/s]

 26%|██▋       | 866/3268 [06:00<16:32,  2.42it/s]

 27%|██▋       | 867/3268 [06:01<16:30,  2.42it/s]

 27%|██▋       | 868/3268 [06:01<16:30,  2.42it/s]

 27%|██▋       | 869/3268 [06:02<16:32,  2.42it/s]

 27%|██▋       | 870/3268 [06:02<16:30,  2.42it/s]

 27%|██▋       | 871/3268 [06:02<16:30,  2.42it/s]

 27%|██▋       | 872/3268 [06:03<16:30,  2.42it/s]

 27%|██▋       | 873/3268 [06:03<16:30,  2.42it/s]

 27%|██▋       | 874/3268 [06:04<16:29,  2.42it/s]

 27%|██▋       | 875/3268 [06:04<16:29,  2.42it/s]

 27%|██▋       | 876/3268 [06:04<16:29,  2.42it/s]

 27%|██▋       | 877/3268 [06:05<16:28,  2.42it/s]

 27%|██▋       | 878/3268 [06:05<16:28,  2.42it/s]

 27%|██▋       | 879/3268 [06:06<16:27,  2.42it/s]

 27%|██▋       | 880/3268 [06:06<16:27,  2.42it/s]

 27%|██▋       | 881/3268 [06:07<16:26,  2.42it/s]

 27%|██▋       | 882/3268 [06:07<16:26,  2.42it/s]

 27%|██▋       | 883/3268 [06:07<16:26,  2.42it/s]

 27%|██▋       | 884/3268 [06:08<16:24,  2.42it/s]

 27%|██▋       | 885/3268 [06:08<16:25,  2.42it/s]

 27%|██▋       | 886/3268 [06:09<16:25,  2.42it/s]

 27%|██▋       | 887/3268 [06:09<16:26,  2.41it/s]

 27%|██▋       | 888/3268 [06:09<16:25,  2.42it/s]

 27%|██▋       | 889/3268 [06:10<16:26,  2.41it/s]

 27%|██▋       | 890/3268 [06:10<16:23,  2.42it/s]

 27%|██▋       | 891/3268 [06:11<16:24,  2.41it/s]

 27%|██▋       | 892/3268 [06:11<16:22,  2.42it/s]

 27%|██▋       | 893/3268 [06:11<16:21,  2.42it/s]

 27%|██▋       | 894/3268 [06:12<16:21,  2.42it/s]

 27%|██▋       | 895/3268 [06:12<16:22,  2.42it/s]

 27%|██▋       | 896/3268 [06:13<16:22,  2.42it/s]

 27%|██▋       | 897/3268 [06:13<16:20,  2.42it/s]

 27%|██▋       | 898/3268 [06:14<16:18,  2.42it/s]

 28%|██▊       | 899/3268 [06:14<16:17,  2.42it/s]

 28%|██▊       | 900/3268 [06:14<16:18,  2.42it/s]

 28%|██▊       | 901/3268 [06:15<16:17,  2.42it/s]

 28%|██▊       | 902/3268 [06:15<16:16,  2.42it/s]

 28%|██▊       | 903/3268 [06:16<16:15,  2.42it/s]

 28%|██▊       | 904/3268 [06:16<16:16,  2.42it/s]

 28%|██▊       | 905/3268 [06:16<16:16,  2.42it/s]

 28%|██▊       | 906/3268 [06:17<16:16,  2.42it/s]

 28%|██▊       | 907/3268 [06:17<16:15,  2.42it/s]

 28%|██▊       | 908/3268 [06:18<16:16,  2.42it/s]

 28%|██▊       | 909/3268 [06:18<16:17,  2.41it/s]

 28%|██▊       | 910/3268 [06:19<16:16,  2.42it/s]

 28%|██▊       | 911/3268 [06:19<16:15,  2.42it/s]

 28%|██▊       | 912/3268 [06:19<16:14,  2.42it/s]

 28%|██▊       | 913/3268 [06:20<16:15,  2.42it/s]

 28%|██▊       | 914/3268 [06:20<16:13,  2.42it/s]

 28%|██▊       | 915/3268 [06:21<16:13,  2.42it/s]

 28%|██▊       | 916/3268 [06:21<16:12,  2.42it/s]

 28%|██▊       | 917/3268 [06:21<16:13,  2.41it/s]

 28%|██▊       | 918/3268 [06:22<16:12,  2.42it/s]

 28%|██▊       | 919/3268 [06:22<16:12,  2.41it/s]

 28%|██▊       | 920/3268 [06:23<16:12,  2.42it/s]

 28%|██▊       | 921/3268 [06:23<16:12,  2.41it/s]

 28%|██▊       | 922/3268 [06:23<16:10,  2.42it/s]

 28%|██▊       | 923/3268 [06:24<16:10,  2.42it/s]

 28%|██▊       | 924/3268 [06:24<16:11,  2.41it/s]

 28%|██▊       | 925/3268 [06:25<16:11,  2.41it/s]

 28%|██▊       | 926/3268 [06:25<16:10,  2.41it/s]

 28%|██▊       | 927/3268 [06:26<16:10,  2.41it/s]

 28%|██▊       | 928/3268 [06:26<16:09,  2.41it/s]

 28%|██▊       | 929/3268 [06:26<16:07,  2.42it/s]

 28%|██▊       | 930/3268 [06:27<16:08,  2.42it/s]

 28%|██▊       | 931/3268 [06:27<16:07,  2.41it/s]

 29%|██▊       | 932/3268 [06:28<16:07,  2.41it/s]

 29%|██▊       | 933/3268 [06:28<16:06,  2.41it/s]

 29%|██▊       | 934/3268 [06:28<16:06,  2.41it/s]

 29%|██▊       | 935/3268 [06:29<16:06,  2.41it/s]

 29%|██▊       | 936/3268 [06:29<16:06,  2.41it/s]

 29%|██▊       | 937/3268 [06:30<16:05,  2.41it/s]

 29%|██▊       | 938/3268 [06:30<16:06,  2.41it/s]

 29%|██▊       | 939/3268 [06:31<16:04,  2.41it/s]

 29%|██▉       | 940/3268 [06:31<16:05,  2.41it/s]

 29%|██▉       | 941/3268 [06:31<16:06,  2.41it/s]

 29%|██▉       | 942/3268 [06:32<16:06,  2.41it/s]

 29%|██▉       | 943/3268 [06:32<16:04,  2.41it/s]

 29%|██▉       | 944/3268 [06:33<16:03,  2.41it/s]

 29%|██▉       | 945/3268 [06:33<16:02,  2.41it/s]

 29%|██▉       | 946/3268 [06:33<16:02,  2.41it/s]

 29%|██▉       | 947/3268 [06:34<16:01,  2.41it/s]

 29%|██▉       | 948/3268 [06:34<16:01,  2.41it/s]

 29%|██▉       | 949/3268 [06:35<16:01,  2.41it/s]

 29%|██▉       | 950/3268 [06:35<15:59,  2.41it/s]

 29%|██▉       | 951/3268 [06:36<16:00,  2.41it/s]

 29%|██▉       | 952/3268 [06:36<15:59,  2.41it/s]

 29%|██▉       | 953/3268 [06:36<15:58,  2.42it/s]

 29%|██▉       | 954/3268 [06:37<15:57,  2.42it/s]

 29%|██▉       | 955/3268 [06:37<15:58,  2.41it/s]

 29%|██▉       | 956/3268 [06:38<15:58,  2.41it/s]

 29%|██▉       | 957/3268 [06:38<15:58,  2.41it/s]

 29%|██▉       | 958/3268 [06:38<15:57,  2.41it/s]

 29%|██▉       | 959/3268 [06:39<15:56,  2.41it/s]

 29%|██▉       | 960/3268 [06:39<15:55,  2.41it/s]

 29%|██▉       | 961/3268 [06:40<15:54,  2.42it/s]

 29%|██▉       | 962/3268 [06:40<15:54,  2.42it/s]

 29%|██▉       | 963/3268 [06:40<15:55,  2.41it/s]

 29%|██▉       | 964/3268 [06:41<15:53,  2.42it/s]

 30%|██▉       | 965/3268 [06:41<15:53,  2.42it/s]

 30%|██▉       | 966/3268 [06:42<15:53,  2.41it/s]

 30%|██▉       | 967/3268 [06:42<15:54,  2.41it/s]

 30%|██▉       | 968/3268 [06:43<15:55,  2.41it/s]

 30%|██▉       | 969/3268 [06:43<15:53,  2.41it/s]

 30%|██▉       | 970/3268 [06:43<15:54,  2.41it/s]

 30%|██▉       | 971/3268 [06:44<15:52,  2.41it/s]

 30%|██▉       | 972/3268 [06:44<15:51,  2.41it/s]

 30%|██▉       | 973/3268 [06:45<15:50,  2.42it/s]

 30%|██▉       | 974/3268 [06:45<15:50,  2.41it/s]

 30%|██▉       | 975/3268 [06:45<15:50,  2.41it/s]

 30%|██▉       | 976/3268 [06:46<15:50,  2.41it/s]

 30%|██▉       | 977/3268 [06:46<15:50,  2.41it/s]

 30%|██▉       | 978/3268 [06:47<15:49,  2.41it/s]

 30%|██▉       | 979/3268 [06:47<15:48,  2.41it/s]

 30%|██▉       | 980/3268 [06:48<15:48,  2.41it/s]

 30%|███       | 981/3268 [06:48<15:48,  2.41it/s]

 30%|███       | 982/3268 [06:48<15:47,  2.41it/s]

 30%|███       | 983/3268 [06:49<15:47,  2.41it/s]

 30%|███       | 984/3268 [06:49<15:47,  2.41it/s]

 30%|███       | 985/3268 [06:50<15:49,  2.40it/s]

 30%|███       | 986/3268 [06:50<15:48,  2.41it/s]

 30%|███       | 987/3268 [06:50<15:48,  2.41it/s]

 30%|███       | 988/3268 [06:51<15:47,  2.41it/s]

 30%|███       | 989/3268 [06:51<15:47,  2.40it/s]

 30%|███       | 990/3268 [06:52<15:45,  2.41it/s]

 30%|███       | 991/3268 [06:52<15:45,  2.41it/s]

 30%|███       | 992/3268 [06:53<15:44,  2.41it/s]

 30%|███       | 993/3268 [06:53<15:44,  2.41it/s]

 30%|███       | 994/3268 [06:53<15:43,  2.41it/s]

 30%|███       | 995/3268 [06:54<15:43,  2.41it/s]

 30%|███       | 996/3268 [06:54<15:42,  2.41it/s]

 31%|███       | 997/3268 [06:55<15:41,  2.41it/s]

 31%|███       | 998/3268 [06:55<15:41,  2.41it/s]

 31%|███       | 999/3268 [06:55<15:40,  2.41it/s]

 31%|███       | 1000/3268 [06:56<15:41,  2.41it/s]

 31%|███       | 1001/3268 [06:56<15:39,  2.41it/s]

 31%|███       | 1002/3268 [06:57<15:39,  2.41it/s]

 31%|███       | 1003/3268 [06:57<15:38,  2.41it/s]

 31%|███       | 1004/3268 [06:57<15:39,  2.41it/s]

 31%|███       | 1005/3268 [06:58<15:39,  2.41it/s]

 31%|███       | 1006/3268 [06:58<15:40,  2.41it/s]

 31%|███       | 1007/3268 [06:59<15:39,  2.41it/s]

 31%|███       | 1008/3268 [06:59<15:38,  2.41it/s]

 31%|███       | 1009/3268 [07:00<15:38,  2.41it/s]

 31%|███       | 1010/3268 [07:00<15:37,  2.41it/s]

 31%|███       | 1011/3268 [07:00<15:37,  2.41it/s]

 31%|███       | 1012/3268 [07:01<15:35,  2.41it/s]

 31%|███       | 1013/3268 [07:01<15:35,  2.41it/s]

 31%|███       | 1014/3268 [07:02<15:37,  2.40it/s]

 31%|███       | 1015/3268 [07:02<15:35,  2.41it/s]

 31%|███       | 1016/3268 [07:02<15:35,  2.41it/s]

 31%|███       | 1017/3268 [07:03<15:35,  2.41it/s]

 31%|███       | 1018/3268 [07:03<15:33,  2.41it/s]

 31%|███       | 1019/3268 [07:04<15:32,  2.41it/s]

 31%|███       | 1020/3268 [07:04<15:30,  2.41it/s]

 31%|███       | 1021/3268 [07:05<15:31,  2.41it/s]

 31%|███▏      | 1022/3268 [07:05<15:31,  2.41it/s]

 31%|███▏      | 1023/3268 [07:05<15:31,  2.41it/s]

 31%|███▏      | 1024/3268 [07:06<15:30,  2.41it/s]

 31%|███▏      | 1025/3268 [07:06<15:30,  2.41it/s]

 31%|███▏      | 1026/3268 [07:07<15:30,  2.41it/s]

 31%|███▏      | 1027/3268 [07:07<15:29,  2.41it/s]

 31%|███▏      | 1028/3268 [07:07<15:29,  2.41it/s]

 31%|███▏      | 1029/3268 [07:08<15:30,  2.41it/s]

 32%|███▏      | 1030/3268 [07:08<15:29,  2.41it/s]

 32%|███▏      | 1031/3268 [07:09<15:29,  2.41it/s]

 32%|███▏      | 1032/3268 [07:09<15:31,  2.40it/s]

 32%|███▏      | 1033/3268 [07:10<15:30,  2.40it/s]

 32%|███▏      | 1034/3268 [07:10<15:29,  2.40it/s]

 32%|███▏      | 1035/3268 [07:10<15:27,  2.41it/s]

 32%|███▏      | 1036/3268 [07:11<15:27,  2.41it/s]

 32%|███▏      | 1037/3268 [07:11<15:26,  2.41it/s]

 32%|███▏      | 1038/3268 [07:12<15:26,  2.41it/s]

 32%|███▏      | 1039/3268 [07:12<15:25,  2.41it/s]

 32%|███▏      | 1040/3268 [07:12<15:24,  2.41it/s]

 32%|███▏      | 1041/3268 [07:13<15:24,  2.41it/s]

 32%|███▏      | 1042/3268 [07:13<15:23,  2.41it/s]

 32%|███▏      | 1043/3268 [07:14<15:23,  2.41it/s]

 32%|███▏      | 1044/3268 [07:14<15:22,  2.41it/s]

 32%|███▏      | 1045/3268 [07:15<15:23,  2.41it/s]

 32%|███▏      | 1046/3268 [07:15<15:22,  2.41it/s]

 32%|███▏      | 1047/3268 [07:15<15:21,  2.41it/s]

 32%|███▏      | 1048/3268 [07:16<15:21,  2.41it/s]

 32%|███▏      | 1049/3268 [07:16<15:22,  2.41it/s]

 32%|███▏      | 1050/3268 [07:17<15:22,  2.40it/s]

 32%|███▏      | 1051/3268 [07:17<15:21,  2.41it/s]

 32%|███▏      | 1052/3268 [07:17<15:20,  2.41it/s]

 32%|███▏      | 1053/3268 [07:18<15:19,  2.41it/s]

 32%|███▏      | 1054/3268 [07:18<15:18,  2.41it/s]

 32%|███▏      | 1055/3268 [07:19<15:18,  2.41it/s]

 32%|███▏      | 1056/3268 [07:19<15:18,  2.41it/s]

 32%|███▏      | 1057/3268 [07:19<15:16,  2.41it/s]

 32%|███▏      | 1058/3268 [07:20<15:18,  2.41it/s]

 32%|███▏      | 1059/3268 [07:20<15:17,  2.41it/s]

 32%|███▏      | 1060/3268 [07:21<15:16,  2.41it/s]

 32%|███▏      | 1061/3268 [07:21<15:15,  2.41it/s]

 32%|███▏      | 1062/3268 [07:22<15:14,  2.41it/s]

 33%|███▎      | 1063/3268 [07:22<15:14,  2.41it/s]

 33%|███▎      | 1064/3268 [07:22<15:15,  2.41it/s]

 33%|███▎      | 1065/3268 [07:23<15:13,  2.41it/s]

 33%|███▎      | 1066/3268 [07:23<15:13,  2.41it/s]

 33%|███▎      | 1067/3268 [07:24<15:13,  2.41it/s]

 33%|███▎      | 1068/3268 [07:24<15:13,  2.41it/s]

 33%|███▎      | 1069/3268 [07:24<15:14,  2.41it/s]

 33%|███▎      | 1070/3268 [07:25<15:12,  2.41it/s]

 33%|███▎      | 1071/3268 [07:25<15:12,  2.41it/s]

 33%|███▎      | 1072/3268 [07:26<15:14,  2.40it/s]

 33%|███▎      | 1073/3268 [07:26<15:12,  2.40it/s]

 33%|███▎      | 1074/3268 [07:27<15:12,  2.40it/s]

 33%|███▎      | 1075/3268 [07:27<15:11,  2.41it/s]

 33%|███▎      | 1076/3268 [07:27<15:11,  2.41it/s]

 33%|███▎      | 1077/3268 [07:28<15:11,  2.40it/s]

 33%|███▎      | 1078/3268 [07:28<15:10,  2.41it/s]

 33%|███▎      | 1079/3268 [07:29<15:10,  2.40it/s]

 33%|███▎      | 1080/3268 [07:29<15:10,  2.40it/s]

 33%|███▎      | 1081/3268 [07:29<15:09,  2.40it/s]

 33%|███▎      | 1082/3268 [07:30<15:08,  2.41it/s]

 33%|███▎      | 1083/3268 [07:30<15:08,  2.40it/s]

 33%|███▎      | 1084/3268 [07:31<15:07,  2.41it/s]

 33%|███▎      | 1085/3268 [07:31<15:07,  2.41it/s]

 33%|███▎      | 1086/3268 [07:32<15:08,  2.40it/s]

 33%|███▎      | 1087/3268 [07:32<15:07,  2.40it/s]

 33%|███▎      | 1088/3268 [07:32<15:05,  2.41it/s]

 33%|███▎      | 1089/3268 [07:33<15:06,  2.40it/s]

 33%|███▎      | 1090/3268 [07:33<15:05,  2.41it/s]

 33%|███▎      | 1091/3268 [07:34<15:04,  2.41it/s]

 33%|███▎      | 1092/3268 [07:34<15:04,  2.40it/s]

 33%|███▎      | 1093/3268 [07:34<15:05,  2.40it/s]

 33%|███▎      | 1094/3268 [07:35<15:04,  2.40it/s]

 34%|███▎      | 1095/3268 [07:35<15:05,  2.40it/s]

 34%|███▎      | 1096/3268 [07:36<15:04,  2.40it/s]

 34%|███▎      | 1097/3268 [07:36<15:04,  2.40it/s]

 34%|███▎      | 1098/3268 [07:37<15:02,  2.40it/s]

 34%|███▎      | 1099/3268 [07:37<15:02,  2.40it/s]

 34%|███▎      | 1100/3268 [07:37<15:03,  2.40it/s]

 34%|███▎      | 1101/3268 [07:38<15:01,  2.40it/s]

 34%|███▎      | 1102/3268 [07:38<15:00,  2.40it/s]

 34%|███▍      | 1103/3268 [07:39<15:00,  2.40it/s]

 34%|███▍      | 1104/3268 [07:39<14:59,  2.41it/s]

 34%|███▍      | 1105/3268 [07:39<14:58,  2.41it/s]

 34%|███▍      | 1106/3268 [07:40<14:59,  2.40it/s]

 34%|███▍      | 1107/3268 [07:40<14:58,  2.40it/s]

 34%|███▍      | 1108/3268 [07:41<14:58,  2.40it/s]

 34%|███▍      | 1109/3268 [07:41<14:57,  2.41it/s]

 34%|███▍      | 1110/3268 [07:42<14:58,  2.40it/s]

 34%|███▍      | 1111/3268 [07:42<14:57,  2.40it/s]

 34%|███▍      | 1112/3268 [07:42<14:57,  2.40it/s]

 34%|███▍      | 1113/3268 [07:43<14:57,  2.40it/s]

 34%|███▍      | 1114/3268 [07:43<14:56,  2.40it/s]

 34%|███▍      | 1115/3268 [07:44<14:55,  2.40it/s]

 34%|███▍      | 1116/3268 [07:44<14:55,  2.40it/s]

 34%|███▍      | 1117/3268 [07:44<14:54,  2.40it/s]

 34%|███▍      | 1118/3268 [07:45<14:54,  2.40it/s]

 34%|███▍      | 1119/3268 [07:45<14:52,  2.41it/s]

 34%|███▍      | 1120/3268 [07:46<14:53,  2.40it/s]

 34%|███▍      | 1121/3268 [07:46<14:53,  2.40it/s]

 34%|███▍      | 1122/3268 [07:47<14:54,  2.40it/s]

 34%|███▍      | 1123/3268 [07:47<14:53,  2.40it/s]

 34%|███▍      | 1124/3268 [07:47<14:54,  2.40it/s]

 34%|███▍      | 1125/3268 [07:48<14:54,  2.40it/s]

 34%|███▍      | 1126/3268 [07:48<14:53,  2.40it/s]

 34%|███▍      | 1127/3268 [07:49<14:53,  2.40it/s]

 35%|███▍      | 1128/3268 [07:49<14:52,  2.40it/s]

 35%|███▍      | 1129/3268 [07:49<14:51,  2.40it/s]

 35%|███▍      | 1130/3268 [07:50<14:50,  2.40it/s]

 35%|███▍      | 1131/3268 [07:50<14:50,  2.40it/s]

 35%|███▍      | 1132/3268 [07:51<14:49,  2.40it/s]

 35%|███▍      | 1133/3268 [07:51<14:48,  2.40it/s]

 35%|███▍      | 1134/3268 [07:52<14:47,  2.40it/s]

 35%|███▍      | 1135/3268 [07:52<14:48,  2.40it/s]

 35%|███▍      | 1136/3268 [07:52<14:48,  2.40it/s]

 35%|███▍      | 1137/3268 [07:53<14:47,  2.40it/s]

 35%|███▍      | 1138/3268 [07:53<14:46,  2.40it/s]

 35%|███▍      | 1139/3268 [07:54<14:46,  2.40it/s]

 35%|███▍      | 1140/3268 [07:54<14:45,  2.40it/s]

 35%|███▍      | 1141/3268 [07:54<14:47,  2.40it/s]

 35%|███▍      | 1142/3268 [07:55<14:45,  2.40it/s]

 35%|███▍      | 1143/3268 [07:55<14:46,  2.40it/s]

 35%|███▌      | 1144/3268 [07:56<14:46,  2.40it/s]

 35%|███▌      | 1145/3268 [07:56<14:46,  2.40it/s]

 35%|███▌      | 1146/3268 [07:57<14:44,  2.40it/s]

 35%|███▌      | 1147/3268 [07:57<14:44,  2.40it/s]

 35%|███▌      | 1148/3268 [07:57<14:43,  2.40it/s]

 35%|███▌      | 1149/3268 [07:58<14:43,  2.40it/s]

 35%|███▌      | 1150/3268 [07:58<14:41,  2.40it/s]

 35%|███▌      | 1151/3268 [07:59<14:41,  2.40it/s]

 35%|███▌      | 1152/3268 [07:59<14:40,  2.40it/s]

 35%|███▌      | 1153/3268 [07:59<14:41,  2.40it/s]

 35%|███▌      | 1154/3268 [08:00<14:40,  2.40it/s]

 35%|███▌      | 1155/3268 [08:00<14:40,  2.40it/s]

 35%|███▌      | 1156/3268 [08:01<14:40,  2.40it/s]

 35%|███▌      | 1157/3268 [08:01<14:39,  2.40it/s]

 35%|███▌      | 1158/3268 [08:02<14:38,  2.40it/s]

 35%|███▌      | 1159/3268 [08:02<14:39,  2.40it/s]

 35%|███▌      | 1160/3268 [08:02<14:38,  2.40it/s]

 36%|███▌      | 1161/3268 [08:03<14:38,  2.40it/s]

 36%|███▌      | 1162/3268 [08:03<14:41,  2.39it/s]

 36%|███▌      | 1163/3268 [08:04<14:38,  2.40it/s]

 36%|███▌      | 1164/3268 [08:04<14:37,  2.40it/s]

 36%|███▌      | 1165/3268 [08:04<14:38,  2.39it/s]

 36%|███▌      | 1166/3268 [08:05<14:37,  2.40it/s]

 36%|███▌      | 1167/3268 [08:05<14:36,  2.40it/s]

 36%|███▌      | 1168/3268 [08:06<14:36,  2.40it/s]

 36%|███▌      | 1169/3268 [08:06<14:34,  2.40it/s]

 36%|███▌      | 1170/3268 [08:07<14:34,  2.40it/s]

 36%|███▌      | 1171/3268 [08:07<14:33,  2.40it/s]

 36%|███▌      | 1172/3268 [08:07<14:32,  2.40it/s]

 36%|███▌      | 1173/3268 [08:08<14:31,  2.40it/s]

 36%|███▌      | 1174/3268 [08:08<14:31,  2.40it/s]

 36%|███▌      | 1175/3268 [08:09<14:31,  2.40it/s]

 36%|███▌      | 1176/3268 [08:09<14:31,  2.40it/s]

 36%|███▌      | 1177/3268 [08:09<14:30,  2.40it/s]

 36%|███▌      | 1178/3268 [08:10<14:30,  2.40it/s]

 36%|███▌      | 1179/3268 [08:10<14:30,  2.40it/s]

 36%|███▌      | 1180/3268 [08:11<14:31,  2.40it/s]

 36%|███▌      | 1181/3268 [08:11<14:29,  2.40it/s]

 36%|███▌      | 1182/3268 [08:12<14:30,  2.40it/s]

 36%|███▌      | 1183/3268 [08:12<14:29,  2.40it/s]

 36%|███▌      | 1184/3268 [08:12<14:28,  2.40it/s]

 36%|███▋      | 1185/3268 [08:13<14:28,  2.40it/s]

 36%|███▋      | 1186/3268 [08:13<14:27,  2.40it/s]

 36%|███▋      | 1187/3268 [08:14<14:26,  2.40it/s]

 36%|███▋      | 1188/3268 [08:14<14:26,  2.40it/s]

 36%|███▋      | 1189/3268 [08:14<14:27,  2.40it/s]

 36%|███▋      | 1190/3268 [08:15<14:26,  2.40it/s]

 36%|███▋      | 1191/3268 [08:15<14:26,  2.40it/s]

 36%|███▋      | 1192/3268 [08:16<14:30,  2.38it/s]

 37%|███▋      | 1193/3268 [08:16<14:29,  2.39it/s]

 37%|███▋      | 1194/3268 [08:17<14:27,  2.39it/s]

 37%|███▋      | 1195/3268 [08:17<14:27,  2.39it/s]

 37%|███▋      | 1196/3268 [08:17<14:24,  2.40it/s]

 37%|███▋      | 1197/3268 [08:18<14:24,  2.40it/s]

 37%|███▋      | 1198/3268 [08:18<14:24,  2.39it/s]

 37%|███▋      | 1199/3268 [08:19<14:22,  2.40it/s]

 37%|███▋      | 1200/3268 [08:19<14:23,  2.39it/s]

 37%|███▋      | 1201/3268 [08:19<14:22,  2.40it/s]

 37%|███▋      | 1202/3268 [08:20<14:21,  2.40it/s]

 37%|███▋      | 1203/3268 [08:20<14:22,  2.40it/s]

 37%|███▋      | 1204/3268 [08:21<14:21,  2.40it/s]

 37%|███▋      | 1205/3268 [08:21<14:21,  2.39it/s]

 37%|███▋      | 1206/3268 [08:22<14:22,  2.39it/s]

 37%|███▋      | 1207/3268 [08:22<14:19,  2.40it/s]

 37%|███▋      | 1208/3268 [08:22<14:19,  2.40it/s]

 37%|███▋      | 1209/3268 [08:23<14:19,  2.39it/s]

 37%|███▋      | 1210/3268 [08:23<14:20,  2.39it/s]

 37%|███▋      | 1211/3268 [08:24<14:18,  2.40it/s]

 37%|███▋      | 1212/3268 [08:24<14:19,  2.39it/s]

 37%|███▋      | 1213/3268 [08:24<14:18,  2.39it/s]

 37%|███▋      | 1214/3268 [08:25<14:17,  2.40it/s]

 37%|███▋      | 1215/3268 [08:25<14:16,  2.40it/s]

 37%|███▋      | 1216/3268 [08:26<14:16,  2.40it/s]

 37%|███▋      | 1217/3268 [08:26<14:16,  2.40it/s]

 37%|███▋      | 1218/3268 [08:27<14:15,  2.40it/s]

 37%|███▋      | 1219/3268 [08:27<14:14,  2.40it/s]

 37%|███▋      | 1220/3268 [08:27<14:14,  2.40it/s]

 37%|███▋      | 1221/3268 [08:28<14:14,  2.40it/s]

 37%|███▋      | 1222/3268 [08:28<14:14,  2.39it/s]

 37%|███▋      | 1223/3268 [08:29<14:14,  2.39it/s]

 37%|███▋      | 1224/3268 [08:29<14:14,  2.39it/s]

 37%|███▋      | 1225/3268 [08:29<14:12,  2.40it/s]

 38%|███▊      | 1226/3268 [08:30<14:11,  2.40it/s]

 38%|███▊      | 1227/3268 [08:30<14:12,  2.39it/s]

 38%|███▊      | 1228/3268 [08:31<14:12,  2.39it/s]

 38%|███▊      | 1229/3268 [08:31<14:12,  2.39it/s]

 38%|███▊      | 1230/3268 [08:32<14:12,  2.39it/s]

 38%|███▊      | 1231/3268 [08:32<14:10,  2.40it/s]

 38%|███▊      | 1232/3268 [08:32<14:11,  2.39it/s]

 38%|███▊      | 1233/3268 [08:33<14:10,  2.39it/s]

 38%|███▊      | 1234/3268 [08:33<14:11,  2.39it/s]

 38%|███▊      | 1235/3268 [08:34<14:09,  2.39it/s]

 38%|███▊      | 1236/3268 [08:34<14:10,  2.39it/s]

 38%|███▊      | 1237/3268 [08:34<14:10,  2.39it/s]

 38%|███▊      | 1238/3268 [08:35<14:10,  2.39it/s]

 38%|███▊      | 1239/3268 [08:35<14:07,  2.39it/s]

 38%|███▊      | 1240/3268 [08:36<14:07,  2.39it/s]

 38%|███▊      | 1241/3268 [08:36<14:07,  2.39it/s]

 38%|███▊      | 1242/3268 [08:37<14:07,  2.39it/s]

 38%|███▊      | 1243/3268 [08:37<14:06,  2.39it/s]

 38%|███▊      | 1244/3268 [08:37<14:05,  2.39it/s]

 38%|███▊      | 1245/3268 [08:38<14:03,  2.40it/s]

 38%|███▊      | 1246/3268 [08:38<14:04,  2.39it/s]

 38%|███▊      | 1247/3268 [08:39<14:04,  2.39it/s]

 38%|███▊      | 1248/3268 [08:39<14:04,  2.39it/s]

 38%|███▊      | 1249/3268 [08:40<14:04,  2.39it/s]

 38%|███▊      | 1250/3268 [08:40<14:03,  2.39it/s]

 38%|███▊      | 1251/3268 [08:40<14:03,  2.39it/s]

logging
logging the anndata

 38%|███▊      | 1252/3268 [08:41<14:38,  2.29it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 38%|███▊      | 1253/3268 [08:41<14:23,  2.33it/s]

 38%|███▊      | 1254/3268 [08:42<14:14,  2.36it/s]

 38%|███▊      | 1255/3268 [08:42<14:06,  2.38it/s]

 38%|███▊      | 1256/3268 [08:42<14:00,  2.39it/s]

 38%|███▊      | 1257/3268 [08:43<13:56,  2.40it/s]

 38%|███▊      | 1258/3268 [08:43<13:53,  2.41it/s]

 39%|███▊      | 1259/3268 [08:44<13:50,  2.42it/s]

 39%|███▊      | 1260/3268 [08:44<13:48,  2.42it/s]

 39%|███▊      | 1261/3268 [08:45<13:47,  2.43it/s]

 39%|███▊      | 1262/3268 [08:45<13:46,  2.43it/s]

 39%|███▊      | 1263/3268 [08:45<13:45,  2.43it/s]

 39%|███▊      | 1264/3268 [08:46<13:44,  2.43it/s]

 39%|███▊      | 1265/3268 [08:46<13:44,  2.43it/s]

 39%|███▊      | 1266/3268 [08:47<13:43,  2.43it/s]

 39%|███▉      | 1267/3268 [08:47<13:43,  2.43it/s]

 39%|███▉      | 1268/3268 [08:47<13:43,  2.43it/s]

 39%|███▉      | 1269/3268 [08:48<13:43,  2.43it/s]

 39%|███▉      | 1270/3268 [08:48<13:42,  2.43it/s]

 39%|███▉      | 1271/3268 [08:49<13:43,  2.43it/s]

 39%|███▉      | 1272/3268 [08:49<13:42,  2.43it/s]

 39%|███▉      | 1273/3268 [08:49<13:41,  2.43it/s]

 39%|███▉      | 1274/3268 [08:50<13:40,  2.43it/s]

 39%|███▉      | 1275/3268 [08:50<13:40,  2.43it/s]

 39%|███▉      | 1276/3268 [08:51<13:40,  2.43it/s]

 39%|███▉      | 1277/3268 [08:51<13:39,  2.43it/s]

 39%|███▉      | 1278/3268 [08:52<13:38,  2.43it/s]

 39%|███▉      | 1279/3268 [08:52<13:38,  2.43it/s]

 39%|███▉      | 1280/3268 [08:52<13:38,  2.43it/s]

 39%|███▉      | 1281/3268 [08:53<13:39,  2.42it/s]

 39%|███▉      | 1282/3268 [08:53<13:38,  2.43it/s]

 39%|███▉      | 1283/3268 [08:54<13:39,  2.42it/s]

 39%|███▉      | 1284/3268 [08:54<13:38,  2.42it/s]

 39%|███▉      | 1285/3268 [08:54<13:37,  2.43it/s]

 39%|███▉      | 1286/3268 [08:55<13:36,  2.43it/s]

 39%|███▉      | 1287/3268 [08:55<13:35,  2.43it/s]

 39%|███▉      | 1288/3268 [08:56<13:35,  2.43it/s]

 39%|███▉      | 1289/3268 [08:56<13:35,  2.43it/s]

 39%|███▉      | 1290/3268 [08:56<13:33,  2.43it/s]

 40%|███▉      | 1291/3268 [08:57<13:35,  2.42it/s]

 40%|███▉      | 1292/3268 [08:57<13:34,  2.43it/s]

 40%|███▉      | 1293/3268 [08:58<13:34,  2.43it/s]

 40%|███▉      | 1294/3268 [08:58<13:33,  2.43it/s]

 40%|███▉      | 1295/3268 [08:59<13:32,  2.43it/s]

 40%|███▉      | 1296/3268 [08:59<13:31,  2.43it/s]

 40%|███▉      | 1297/3268 [08:59<13:35,  2.42it/s]

 40%|███▉      | 1298/3268 [09:00<13:34,  2.42it/s]

 40%|███▉      | 1299/3268 [09:00<13:32,  2.42it/s]

 40%|███▉      | 1300/3268 [09:01<13:32,  2.42it/s]

 40%|███▉      | 1301/3268 [09:01<13:31,  2.42it/s]

 40%|███▉      | 1302/3268 [09:01<13:31,  2.42it/s]

 40%|███▉      | 1303/3268 [09:02<13:29,  2.43it/s]

 40%|███▉      | 1304/3268 [09:02<13:29,  2.43it/s]

 40%|███▉      | 1305/3268 [09:03<13:28,  2.43it/s]

 40%|███▉      | 1306/3268 [09:03<13:28,  2.43it/s]

 40%|███▉      | 1307/3268 [09:03<13:29,  2.42it/s]

 40%|████      | 1308/3268 [09:04<13:27,  2.43it/s]

 40%|████      | 1309/3268 [09:04<13:27,  2.42it/s]

 40%|████      | 1310/3268 [09:05<13:28,  2.42it/s]

 40%|████      | 1311/3268 [09:05<13:28,  2.42it/s]

 40%|████      | 1312/3268 [09:06<13:26,  2.42it/s]

 40%|████      | 1313/3268 [09:06<13:26,  2.43it/s]

 40%|████      | 1314/3268 [09:06<13:25,  2.43it/s]

 40%|████      | 1315/3268 [09:07<13:25,  2.42it/s]

 40%|████      | 1316/3268 [09:07<13:24,  2.43it/s]

 40%|████      | 1317/3268 [09:08<13:24,  2.42it/s]

 40%|████      | 1318/3268 [09:08<13:23,  2.43it/s]

 40%|████      | 1319/3268 [09:08<13:23,  2.42it/s]

 40%|████      | 1320/3268 [09:09<13:25,  2.42it/s]

 40%|████      | 1321/3268 [09:09<13:25,  2.42it/s]

 40%|████      | 1322/3268 [09:10<13:24,  2.42it/s]

 40%|████      | 1323/3268 [09:10<13:22,  2.42it/s]

 41%|████      | 1324/3268 [09:11<13:22,  2.42it/s]

 41%|████      | 1325/3268 [09:11<13:22,  2.42it/s]

 41%|████      | 1326/3268 [09:11<13:22,  2.42it/s]

 41%|████      | 1327/3268 [09:12<13:20,  2.43it/s]

 41%|████      | 1328/3268 [09:12<13:20,  2.42it/s]

 41%|████      | 1329/3268 [09:13<13:19,  2.43it/s]

 41%|████      | 1330/3268 [09:13<13:19,  2.42it/s]

 41%|████      | 1331/3268 [09:13<13:19,  2.42it/s]

 41%|████      | 1332/3268 [09:14<13:20,  2.42it/s]

 41%|████      | 1333/3268 [09:14<13:20,  2.42it/s]

 41%|████      | 1334/3268 [09:15<13:19,  2.42it/s]

 41%|████      | 1335/3268 [09:15<13:18,  2.42it/s]

 41%|████      | 1336/3268 [09:15<13:17,  2.42it/s]

 41%|████      | 1337/3268 [09:16<13:17,  2.42it/s]

 41%|████      | 1338/3268 [09:16<13:16,  2.42it/s]

 41%|████      | 1339/3268 [09:17<13:17,  2.42it/s]

 41%|████      | 1340/3268 [09:17<13:16,  2.42it/s]

 41%|████      | 1341/3268 [09:18<13:16,  2.42it/s]

 41%|████      | 1342/3268 [09:18<13:16,  2.42it/s]

 41%|████      | 1343/3268 [09:18<13:15,  2.42it/s]

 41%|████      | 1344/3268 [09:19<13:14,  2.42it/s]

 41%|████      | 1345/3268 [09:19<13:14,  2.42it/s]

 41%|████      | 1346/3268 [09:20<13:13,  2.42it/s]

 41%|████      | 1347/3268 [09:20<13:13,  2.42it/s]

 41%|████      | 1348/3268 [09:20<13:13,  2.42it/s]

 41%|████▏     | 1349/3268 [09:21<13:12,  2.42it/s]

 41%|████▏     | 1350/3268 [09:21<13:12,  2.42it/s]

 41%|████▏     | 1351/3268 [09:22<13:12,  2.42it/s]

 41%|████▏     | 1352/3268 [09:22<13:12,  2.42it/s]

 41%|████▏     | 1353/3268 [09:22<13:11,  2.42it/s]

 41%|████▏     | 1354/3268 [09:23<13:11,  2.42it/s]

 41%|████▏     | 1355/3268 [09:23<13:09,  2.42it/s]

 41%|████▏     | 1356/3268 [09:24<13:09,  2.42it/s]

 42%|████▏     | 1357/3268 [09:24<13:08,  2.42it/s]

 42%|████▏     | 1358/3268 [09:25<13:08,  2.42it/s]

 42%|████▏     | 1359/3268 [09:25<13:08,  2.42it/s]

 42%|████▏     | 1360/3268 [09:25<13:08,  2.42it/s]

 42%|████▏     | 1361/3268 [09:26<13:09,  2.42it/s]

 42%|████▏     | 1362/3268 [09:26<13:08,  2.42it/s]

 42%|████▏     | 1363/3268 [09:27<13:07,  2.42it/s]

 42%|████▏     | 1364/3268 [09:27<13:07,  2.42it/s]

 42%|████▏     | 1365/3268 [09:27<13:06,  2.42it/s]

 42%|████▏     | 1366/3268 [09:28<13:05,  2.42it/s]

 42%|████▏     | 1367/3268 [09:28<13:05,  2.42it/s]

 42%|████▏     | 1368/3268 [09:29<13:04,  2.42it/s]

 42%|████▏     | 1369/3268 [09:29<13:04,  2.42it/s]

 42%|████▏     | 1370/3268 [09:30<13:03,  2.42it/s]

 42%|████▏     | 1371/3268 [09:30<13:03,  2.42it/s]

 42%|████▏     | 1372/3268 [09:30<13:03,  2.42it/s]

 42%|████▏     | 1373/3268 [09:31<13:02,  2.42it/s]

 42%|████▏     | 1374/3268 [09:31<13:02,  2.42it/s]

 42%|████▏     | 1375/3268 [09:32<13:02,  2.42it/s]

 42%|████▏     | 1376/3268 [09:32<13:01,  2.42it/s]

 42%|████▏     | 1377/3268 [09:32<13:01,  2.42it/s]

 42%|████▏     | 1378/3268 [09:33<13:00,  2.42it/s]

 42%|████▏     | 1379/3268 [09:33<13:01,  2.42it/s]

 42%|████▏     | 1380/3268 [09:34<13:00,  2.42it/s]

 42%|████▏     | 1381/3268 [09:34<13:01,  2.41it/s]

 42%|████▏     | 1382/3268 [09:34<12:59,  2.42it/s]

 42%|████▏     | 1383/3268 [09:35<12:59,  2.42it/s]

 42%|████▏     | 1384/3268 [09:35<12:58,  2.42it/s]

 42%|████▏     | 1385/3268 [09:36<12:58,  2.42it/s]

 42%|████▏     | 1386/3268 [09:36<12:57,  2.42it/s]

 42%|████▏     | 1387/3268 [09:37<12:57,  2.42it/s]

 42%|████▏     | 1388/3268 [09:37<12:57,  2.42it/s]

 43%|████▎     | 1389/3268 [09:37<12:57,  2.42it/s]

 43%|████▎     | 1390/3268 [09:38<12:57,  2.42it/s]

 43%|████▎     | 1391/3268 [09:38<12:59,  2.41it/s]

 43%|████▎     | 1392/3268 [09:39<12:57,  2.41it/s]

 43%|████▎     | 1393/3268 [09:39<12:54,  2.42it/s]

 43%|████▎     | 1394/3268 [09:39<12:54,  2.42it/s]

 43%|████▎     | 1395/3268 [09:40<12:53,  2.42it/s]

 43%|████▎     | 1396/3268 [09:40<12:52,  2.42it/s]

 43%|████▎     | 1397/3268 [09:41<12:51,  2.42it/s]

 43%|████▎     | 1398/3268 [09:41<12:51,  2.42it/s]

 43%|████▎     | 1399/3268 [09:41<12:50,  2.43it/s]

 43%|████▎     | 1400/3268 [09:42<12:50,  2.42it/s]

 43%|████▎     | 1401/3268 [09:42<12:51,  2.42it/s]

 43%|████▎     | 1402/3268 [09:43<12:50,  2.42it/s]

 43%|████▎     | 1403/3268 [09:43<12:49,  2.42it/s]

 43%|████▎     | 1404/3268 [09:44<12:48,  2.42it/s]

 43%|████▎     | 1405/3268 [09:44<12:48,  2.42it/s]

 43%|████▎     | 1406/3268 [09:44<12:47,  2.43it/s]

 43%|████▎     | 1407/3268 [09:45<12:48,  2.42it/s]

 43%|████▎     | 1408/3268 [09:45<12:47,  2.42it/s]

 43%|████▎     | 1409/3268 [09:46<12:47,  2.42it/s]

 43%|████▎     | 1410/3268 [09:46<12:48,  2.42it/s]

 43%|████▎     | 1411/3268 [09:46<12:49,  2.41it/s]

 43%|████▎     | 1412/3268 [09:47<12:48,  2.41it/s]

 43%|████▎     | 1413/3268 [09:47<12:48,  2.42it/s]

 43%|████▎     | 1414/3268 [09:48<12:47,  2.42it/s]

 43%|████▎     | 1415/3268 [09:48<12:46,  2.42it/s]

 43%|████▎     | 1416/3268 [09:49<12:47,  2.41it/s]

 43%|████▎     | 1417/3268 [09:49<12:46,  2.42it/s]

 43%|████▎     | 1418/3268 [09:49<12:44,  2.42it/s]

 43%|████▎     | 1419/3268 [09:50<12:43,  2.42it/s]

 43%|████▎     | 1420/3268 [09:50<12:43,  2.42it/s]

 43%|████▎     | 1421/3268 [09:51<12:41,  2.42it/s]

 44%|████▎     | 1422/3268 [09:51<12:41,  2.42it/s]

 44%|████▎     | 1423/3268 [09:51<12:40,  2.43it/s]

 44%|████▎     | 1424/3268 [09:52<12:41,  2.42it/s]

 44%|████▎     | 1425/3268 [09:52<12:40,  2.42it/s]

 44%|████▎     | 1426/3268 [09:53<12:40,  2.42it/s]

 44%|████▎     | 1427/3268 [09:53<12:39,  2.42it/s]

 44%|████▎     | 1428/3268 [09:53<12:40,  2.42it/s]

 44%|████▎     | 1429/3268 [09:54<12:39,  2.42it/s]

 44%|████▍     | 1430/3268 [09:54<12:38,  2.42it/s]

 44%|████▍     | 1431/3268 [09:55<12:38,  2.42it/s]

 44%|████▍     | 1432/3268 [09:55<12:41,  2.41it/s]

 44%|████▍     | 1433/3268 [09:56<12:40,  2.41it/s]

 44%|████▍     | 1434/3268 [09:56<12:39,  2.41it/s]

 44%|████▍     | 1435/3268 [09:56<12:40,  2.41it/s]

 44%|████▍     | 1436/3268 [09:57<12:38,  2.41it/s]

 44%|████▍     | 1437/3268 [09:57<12:37,  2.42it/s]

 44%|████▍     | 1438/3268 [09:58<12:36,  2.42it/s]

 44%|████▍     | 1439/3268 [09:58<12:35,  2.42it/s]

 44%|████▍     | 1440/3268 [09:58<12:35,  2.42it/s]

 44%|████▍     | 1441/3268 [09:59<12:35,  2.42it/s]

 44%|████▍     | 1442/3268 [09:59<12:34,  2.42it/s]

 44%|████▍     | 1443/3268 [10:00<12:33,  2.42it/s]

 44%|████▍     | 1444/3268 [10:00<12:34,  2.42it/s]

 44%|████▍     | 1445/3268 [10:01<12:33,  2.42it/s]

 44%|████▍     | 1446/3268 [10:01<12:33,  2.42it/s]

 44%|████▍     | 1447/3268 [10:01<12:32,  2.42it/s]

 44%|████▍     | 1448/3268 [10:02<12:32,  2.42it/s]

 44%|████▍     | 1449/3268 [10:02<12:31,  2.42it/s]

 44%|████▍     | 1450/3268 [10:03<12:31,  2.42it/s]

 44%|████▍     | 1451/3268 [10:03<12:30,  2.42it/s]

 44%|████▍     | 1452/3268 [10:03<12:29,  2.42it/s]

 44%|████▍     | 1453/3268 [10:04<12:28,  2.42it/s]

 44%|████▍     | 1454/3268 [10:04<12:29,  2.42it/s]

 45%|████▍     | 1455/3268 [10:05<12:28,  2.42it/s]

 45%|████▍     | 1456/3268 [10:05<12:27,  2.42it/s]

 45%|████▍     | 1457/3268 [10:05<12:27,  2.42it/s]

 45%|████▍     | 1458/3268 [10:06<12:25,  2.43it/s]

 45%|████▍     | 1459/3268 [10:06<12:26,  2.42it/s]

 45%|████▍     | 1460/3268 [10:07<12:25,  2.42it/s]

 45%|████▍     | 1461/3268 [10:07<12:26,  2.42it/s]

 45%|████▍     | 1462/3268 [10:08<12:25,  2.42it/s]

 45%|████▍     | 1463/3268 [10:08<12:24,  2.42it/s]

 45%|████▍     | 1464/3268 [10:08<12:24,  2.42it/s]

 45%|████▍     | 1465/3268 [10:09<12:25,  2.42it/s]

 45%|████▍     | 1466/3268 [10:09<12:24,  2.42it/s]

 45%|████▍     | 1467/3268 [10:10<12:24,  2.42it/s]

 45%|████▍     | 1468/3268 [10:10<12:24,  2.42it/s]

 45%|████▍     | 1469/3268 [10:10<12:23,  2.42it/s]

 45%|████▍     | 1470/3268 [10:11<12:23,  2.42it/s]

 45%|████▌     | 1471/3268 [10:11<12:23,  2.42it/s]

 45%|████▌     | 1472/3268 [10:12<12:22,  2.42it/s]

 45%|████▌     | 1473/3268 [10:12<12:21,  2.42it/s]

 45%|████▌     | 1474/3268 [10:12<12:21,  2.42it/s]

 45%|████▌     | 1475/3268 [10:13<12:20,  2.42it/s]

 45%|████▌     | 1476/3268 [10:13<12:20,  2.42it/s]

 45%|████▌     | 1477/3268 [10:14<12:19,  2.42it/s]

 45%|████▌     | 1478/3268 [10:14<12:19,  2.42it/s]

 45%|████▌     | 1479/3268 [10:15<12:19,  2.42it/s]

 45%|████▌     | 1480/3268 [10:15<12:19,  2.42it/s]

 45%|████▌     | 1481/3268 [10:15<12:19,  2.42it/s]

 45%|████▌     | 1482/3268 [10:16<12:19,  2.42it/s]

 45%|████▌     | 1483/3268 [10:16<12:18,  2.42it/s]

 45%|████▌     | 1484/3268 [10:17<12:17,  2.42it/s]

 45%|████▌     | 1485/3268 [10:17<12:16,  2.42it/s]

 45%|████▌     | 1486/3268 [10:17<12:15,  2.42it/s]

 46%|████▌     | 1487/3268 [10:18<12:15,  2.42it/s]

 46%|████▌     | 1488/3268 [10:18<12:15,  2.42it/s]

 46%|████▌     | 1489/3268 [10:19<12:16,  2.42it/s]

 46%|████▌     | 1490/3268 [10:19<12:15,  2.42it/s]

 46%|████▌     | 1491/3268 [10:20<12:15,  2.42it/s]

 46%|████▌     | 1492/3268 [10:20<12:14,  2.42it/s]

 46%|████▌     | 1493/3268 [10:20<12:14,  2.42it/s]

 46%|████▌     | 1494/3268 [10:21<12:13,  2.42it/s]

 46%|████▌     | 1495/3268 [10:21<12:12,  2.42it/s]

 46%|████▌     | 1496/3268 [10:22<12:12,  2.42it/s]

 46%|████▌     | 1497/3268 [10:22<12:12,  2.42it/s]

 46%|████▌     | 1498/3268 [10:22<12:11,  2.42it/s]

 46%|████▌     | 1499/3268 [10:23<12:10,  2.42it/s]

 46%|████▌     | 1500/3268 [10:23<12:10,  2.42it/s]

 46%|████▌     | 1501/3268 [10:24<12:10,  2.42it/s]

 46%|████▌     | 1502/3268 [10:24<12:11,  2.41it/s]

 46%|████▌     | 1503/3268 [10:24<12:10,  2.42it/s]

 46%|████▌     | 1504/3268 [10:25<12:10,  2.41it/s]

 46%|████▌     | 1505/3268 [10:25<12:09,  2.42it/s]

 46%|████▌     | 1506/3268 [10:26<12:09,  2.41it/s]

 46%|████▌     | 1507/3268 [10:26<12:09,  2.42it/s]

 46%|████▌     | 1508/3268 [10:27<12:09,  2.41it/s]

 46%|████▌     | 1509/3268 [10:27<12:07,  2.42it/s]

 46%|████▌     | 1510/3268 [10:27<12:07,  2.42it/s]

 46%|████▌     | 1511/3268 [10:28<12:07,  2.41it/s]

 46%|████▋     | 1512/3268 [10:28<12:07,  2.41it/s]

 46%|████▋     | 1513/3268 [10:29<12:06,  2.41it/s]

 46%|████▋     | 1514/3268 [10:29<12:09,  2.41it/s]

 46%|████▋     | 1515/3268 [10:29<12:07,  2.41it/s]

 46%|████▋     | 1516/3268 [10:30<12:06,  2.41it/s]

 46%|████▋     | 1517/3268 [10:30<12:06,  2.41it/s]

 46%|████▋     | 1518/3268 [10:31<12:04,  2.41it/s]

 46%|████▋     | 1519/3268 [10:31<12:04,  2.41it/s]

 47%|████▋     | 1520/3268 [10:32<12:04,  2.41it/s]

 47%|████▋     | 1521/3268 [10:32<12:03,  2.41it/s]

 47%|████▋     | 1522/3268 [10:32<12:03,  2.41it/s]

 47%|████▋     | 1523/3268 [10:33<12:02,  2.42it/s]

 47%|████▋     | 1524/3268 [10:33<12:01,  2.42it/s]

 47%|████▋     | 1525/3268 [10:34<12:05,  2.40it/s]

 47%|████▋     | 1526/3268 [10:34<12:03,  2.41it/s]

 47%|████▋     | 1527/3268 [10:34<12:02,  2.41it/s]

 47%|████▋     | 1528/3268 [10:35<12:01,  2.41it/s]

 47%|████▋     | 1529/3268 [10:35<12:00,  2.41it/s]

 47%|████▋     | 1530/3268 [10:36<12:00,  2.41it/s]

 47%|████▋     | 1531/3268 [10:36<12:01,  2.41it/s]

 47%|████▋     | 1532/3268 [10:36<11:59,  2.41it/s]

 47%|████▋     | 1533/3268 [10:37<11:59,  2.41it/s]

 47%|████▋     | 1534/3268 [10:37<11:58,  2.41it/s]

 47%|████▋     | 1535/3268 [10:38<11:58,  2.41it/s]

 47%|████▋     | 1536/3268 [10:38<11:57,  2.41it/s]

 47%|████▋     | 1537/3268 [10:39<11:57,  2.41it/s]

 47%|████▋     | 1538/3268 [10:39<11:56,  2.41it/s]

 47%|████▋     | 1539/3268 [10:39<11:57,  2.41it/s]

 47%|████▋     | 1540/3268 [10:40<11:56,  2.41it/s]

 47%|████▋     | 1541/3268 [10:40<11:55,  2.41it/s]

 47%|████▋     | 1542/3268 [10:41<11:56,  2.41it/s]

 47%|████▋     | 1543/3268 [10:41<11:55,  2.41it/s]

 47%|████▋     | 1544/3268 [10:41<11:55,  2.41it/s]

 47%|████▋     | 1545/3268 [10:42<11:54,  2.41it/s]

 47%|████▋     | 1546/3268 [10:42<11:54,  2.41it/s]

 47%|████▋     | 1547/3268 [10:43<11:53,  2.41it/s]

 47%|████▋     | 1548/3268 [10:43<11:53,  2.41it/s]

 47%|████▋     | 1549/3268 [10:44<11:53,  2.41it/s]

 47%|████▋     | 1550/3268 [10:44<11:53,  2.41it/s]

 47%|████▋     | 1551/3268 [10:44<11:52,  2.41it/s]

 47%|████▋     | 1552/3268 [10:45<11:52,  2.41it/s]

 48%|████▊     | 1553/3268 [10:45<11:51,  2.41it/s]

 48%|████▊     | 1554/3268 [10:46<11:51,  2.41it/s]

 48%|████▊     | 1555/3268 [10:46<11:50,  2.41it/s]

 48%|████▊     | 1556/3268 [10:46<11:50,  2.41it/s]

 48%|████▊     | 1557/3268 [10:47<11:49,  2.41it/s]

 48%|████▊     | 1558/3268 [10:47<11:49,  2.41it/s]

 48%|████▊     | 1559/3268 [10:48<11:48,  2.41it/s]

 48%|████▊     | 1560/3268 [10:48<11:48,  2.41it/s]

 48%|████▊     | 1561/3268 [10:49<11:48,  2.41it/s]

 48%|████▊     | 1562/3268 [10:49<11:47,  2.41it/s]

 48%|████▊     | 1563/3268 [10:49<11:48,  2.41it/s]

 48%|████▊     | 1564/3268 [10:50<11:47,  2.41it/s]

 48%|████▊     | 1565/3268 [10:50<11:47,  2.41it/s]

 48%|████▊     | 1566/3268 [10:51<11:46,  2.41it/s]

 48%|████▊     | 1567/3268 [10:51<11:45,  2.41it/s]

 48%|████▊     | 1568/3268 [10:51<11:44,  2.41it/s]

 48%|████▊     | 1569/3268 [10:52<11:45,  2.41it/s]

 48%|████▊     | 1570/3268 [10:52<11:44,  2.41it/s]

 48%|████▊     | 1571/3268 [10:53<11:43,  2.41it/s]

 48%|████▊     | 1572/3268 [10:53<11:42,  2.41it/s]

 48%|████▊     | 1573/3268 [10:53<11:42,  2.41it/s]

 48%|████▊     | 1574/3268 [10:54<11:41,  2.42it/s]

 48%|████▊     | 1575/3268 [10:54<11:41,  2.41it/s]

 48%|████▊     | 1576/3268 [10:55<11:41,  2.41it/s]

 48%|████▊     | 1577/3268 [10:55<11:41,  2.41it/s]

 48%|████▊     | 1578/3268 [10:56<11:39,  2.41it/s]

 48%|████▊     | 1579/3268 [10:56<11:39,  2.41it/s]

 48%|████▊     | 1580/3268 [10:56<11:39,  2.41it/s]

 48%|████▊     | 1581/3268 [10:57<11:38,  2.42it/s]

 48%|████▊     | 1582/3268 [10:57<11:38,  2.41it/s]

 48%|████▊     | 1583/3268 [10:58<11:38,  2.41it/s]

 48%|████▊     | 1584/3268 [10:58<11:39,  2.41it/s]

 49%|████▊     | 1585/3268 [10:58<11:38,  2.41it/s]

 49%|████▊     | 1586/3268 [10:59<11:38,  2.41it/s]

 49%|████▊     | 1587/3268 [10:59<11:37,  2.41it/s]

 49%|████▊     | 1588/3268 [11:00<11:36,  2.41it/s]

 49%|████▊     | 1589/3268 [11:00<11:36,  2.41it/s]

 49%|████▊     | 1590/3268 [11:01<11:36,  2.41it/s]

 49%|████▊     | 1591/3268 [11:01<11:36,  2.41it/s]

 49%|████▊     | 1592/3268 [11:01<11:35,  2.41it/s]

 49%|████▊     | 1593/3268 [11:02<11:35,  2.41it/s]

 49%|████▉     | 1594/3268 [11:02<11:35,  2.41it/s]

 49%|████▉     | 1595/3268 [11:03<11:35,  2.41it/s]

 49%|████▉     | 1596/3268 [11:03<11:34,  2.41it/s]

 49%|████▉     | 1597/3268 [11:03<11:33,  2.41it/s]

 49%|████▉     | 1598/3268 [11:04<11:32,  2.41it/s]

 49%|████▉     | 1599/3268 [11:04<11:32,  2.41it/s]

 49%|████▉     | 1600/3268 [11:05<11:31,  2.41it/s]

 49%|████▉     | 1601/3268 [11:05<11:31,  2.41it/s]

 49%|████▉     | 1602/3268 [11:06<11:31,  2.41it/s]

 49%|████▉     | 1603/3268 [11:06<11:31,  2.41it/s]

 49%|████▉     | 1604/3268 [11:06<11:30,  2.41it/s]

 49%|████▉     | 1605/3268 [11:07<11:30,  2.41it/s]

 49%|████▉     | 1606/3268 [11:07<11:30,  2.41it/s]

 49%|████▉     | 1607/3268 [11:08<11:30,  2.41it/s]

 49%|████▉     | 1608/3268 [11:08<11:29,  2.41it/s]

 49%|████▉     | 1609/3268 [11:08<11:29,  2.41it/s]

 49%|████▉     | 1610/3268 [11:09<11:28,  2.41it/s]

 49%|████▉     | 1611/3268 [11:09<11:28,  2.41it/s]

 49%|████▉     | 1612/3268 [11:10<11:27,  2.41it/s]

 49%|████▉     | 1613/3268 [11:10<11:27,  2.41it/s]

 49%|████▉     | 1614/3268 [11:11<11:26,  2.41it/s]

 49%|████▉     | 1615/3268 [11:11<11:26,  2.41it/s]

 49%|████▉     | 1616/3268 [11:11<11:25,  2.41it/s]

 49%|████▉     | 1617/3268 [11:12<11:24,  2.41it/s]

 50%|████▉     | 1618/3268 [11:12<11:24,  2.41it/s]

 50%|████▉     | 1619/3268 [11:13<11:23,  2.41it/s]

 50%|████▉     | 1620/3268 [11:13<11:23,  2.41it/s]

 50%|████▉     | 1621/3268 [11:13<11:23,  2.41it/s]

 50%|████▉     | 1622/3268 [11:14<11:23,  2.41it/s]

 50%|████▉     | 1623/3268 [11:14<11:22,  2.41it/s]

 50%|████▉     | 1624/3268 [11:15<11:22,  2.41it/s]

 50%|████▉     | 1625/3268 [11:15<11:22,  2.41it/s]

 50%|████▉     | 1626/3268 [11:15<11:24,  2.40it/s]

 50%|████▉     | 1627/3268 [11:16<11:23,  2.40it/s]

 50%|████▉     | 1628/3268 [11:16<11:23,  2.40it/s]

 50%|████▉     | 1629/3268 [11:17<11:22,  2.40it/s]

 50%|████▉     | 1630/3268 [11:17<11:21,  2.40it/s]

 50%|████▉     | 1631/3268 [11:18<11:20,  2.41it/s]

 50%|████▉     | 1632/3268 [11:18<11:20,  2.40it/s]

 50%|████▉     | 1633/3268 [11:18<11:19,  2.41it/s]

 50%|█████     | 1634/3268 [11:19<11:19,  2.40it/s]

 50%|█████     | 1635/3268 [11:19<11:18,  2.41it/s]

 50%|█████     | 1636/3268 [11:20<11:19,  2.40it/s]

 50%|█████     | 1637/3268 [11:20<11:18,  2.40it/s]

 50%|█████     | 1638/3268 [11:20<11:17,  2.40it/s]

 50%|█████     | 1639/3268 [11:21<11:17,  2.41it/s]

 50%|█████     | 1640/3268 [11:21<11:15,  2.41it/s]

 50%|█████     | 1641/3268 [11:22<11:15,  2.41it/s]

 50%|█████     | 1642/3268 [11:22<11:14,  2.41it/s]

 50%|█████     | 1643/3268 [11:23<11:13,  2.41it/s]

 50%|█████     | 1644/3268 [11:23<11:13,  2.41it/s]

 50%|█████     | 1645/3268 [11:23<11:12,  2.41it/s]

 50%|█████     | 1646/3268 [11:24<11:11,  2.41it/s]

 50%|█████     | 1647/3268 [11:24<11:11,  2.41it/s]

 50%|█████     | 1648/3268 [11:25<11:11,  2.41it/s]

 50%|█████     | 1649/3268 [11:25<11:11,  2.41it/s]

 50%|█████     | 1650/3268 [11:25<11:11,  2.41it/s]

 51%|█████     | 1651/3268 [11:26<11:11,  2.41it/s]

 51%|█████     | 1652/3268 [11:26<11:11,  2.41it/s]

 51%|█████     | 1653/3268 [11:27<11:10,  2.41it/s]

 51%|█████     | 1654/3268 [11:27<11:10,  2.41it/s]

 51%|█████     | 1655/3268 [11:28<11:10,  2.41it/s]

 51%|█████     | 1656/3268 [11:28<11:10,  2.40it/s]

 51%|█████     | 1657/3268 [11:28<11:09,  2.41it/s]

 51%|█████     | 1658/3268 [11:29<11:08,  2.41it/s]

 51%|█████     | 1659/3268 [11:29<11:08,  2.41it/s]

 51%|█████     | 1660/3268 [11:30<11:07,  2.41it/s]

 51%|█████     | 1661/3268 [11:30<11:07,  2.41it/s]

 51%|█████     | 1662/3268 [11:30<11:07,  2.41it/s]

 51%|█████     | 1663/3268 [11:31<11:06,  2.41it/s]

 51%|█████     | 1664/3268 [11:31<11:06,  2.41it/s]

 51%|█████     | 1665/3268 [11:32<11:05,  2.41it/s]

 51%|█████     | 1666/3268 [11:32<11:06,  2.41it/s]

 51%|█████     | 1667/3268 [11:33<11:05,  2.41it/s]

 51%|█████     | 1668/3268 [11:33<11:05,  2.41it/s]

 51%|█████     | 1669/3268 [11:33<11:04,  2.41it/s]

 51%|█████     | 1670/3268 [11:34<11:04,  2.40it/s]

 51%|█████     | 1671/3268 [11:34<11:04,  2.40it/s]

 51%|█████     | 1672/3268 [11:35<11:04,  2.40it/s]

 51%|█████     | 1673/3268 [11:35<11:03,  2.40it/s]

 51%|█████     | 1674/3268 [11:35<11:03,  2.40it/s]

 51%|█████▏    | 1675/3268 [11:36<11:02,  2.40it/s]

 51%|█████▏    | 1676/3268 [11:36<11:02,  2.40it/s]

 51%|█████▏    | 1677/3268 [11:37<11:02,  2.40it/s]

 51%|█████▏    | 1678/3268 [11:37<11:01,  2.40it/s]

 51%|█████▏    | 1679/3268 [11:38<11:00,  2.40it/s]

 51%|█████▏    | 1680/3268 [11:38<11:00,  2.40it/s]

 51%|█████▏    | 1681/3268 [11:38<11:01,  2.40it/s]

 51%|█████▏    | 1682/3268 [11:39<11:01,  2.40it/s]

 51%|█████▏    | 1683/3268 [11:39<11:01,  2.39it/s]

 52%|█████▏    | 1684/3268 [11:40<11:00,  2.40it/s]

 52%|█████▏    | 1685/3268 [11:40<10:59,  2.40it/s]

 52%|█████▏    | 1686/3268 [11:40<10:58,  2.40it/s]

 52%|█████▏    | 1687/3268 [11:41<10:58,  2.40it/s]

 52%|█████▏    | 1688/3268 [11:41<10:57,  2.40it/s]

 52%|█████▏    | 1689/3268 [11:42<10:56,  2.41it/s]

 52%|█████▏    | 1690/3268 [11:42<10:56,  2.40it/s]

 52%|█████▏    | 1691/3268 [11:43<10:55,  2.41it/s]

 52%|█████▏    | 1692/3268 [11:43<10:55,  2.40it/s]

 52%|█████▏    | 1693/3268 [11:43<10:54,  2.41it/s]

 52%|█████▏    | 1694/3268 [11:44<10:55,  2.40it/s]

 52%|█████▏    | 1695/3268 [11:44<10:54,  2.40it/s]

 52%|█████▏    | 1696/3268 [11:45<10:53,  2.41it/s]

 52%|█████▏    | 1697/3268 [11:45<10:52,  2.41it/s]

 52%|█████▏    | 1698/3268 [11:45<10:52,  2.40it/s]

 52%|█████▏    | 1699/3268 [11:46<10:52,  2.40it/s]

 52%|█████▏    | 1700/3268 [11:46<10:52,  2.40it/s]

 52%|█████▏    | 1701/3268 [11:47<10:51,  2.41it/s]

 52%|█████▏    | 1702/3268 [11:47<10:52,  2.40it/s]

 52%|█████▏    | 1703/3268 [11:48<10:52,  2.40it/s]

 52%|█████▏    | 1704/3268 [11:48<10:51,  2.40it/s]

 52%|█████▏    | 1705/3268 [11:48<10:51,  2.40it/s]

 52%|█████▏    | 1706/3268 [11:49<10:50,  2.40it/s]

 52%|█████▏    | 1707/3268 [11:49<10:49,  2.40it/s]

 52%|█████▏    | 1708/3268 [11:50<10:49,  2.40it/s]

 52%|█████▏    | 1709/3268 [11:50<10:48,  2.40it/s]

 52%|█████▏    | 1710/3268 [11:50<10:48,  2.40it/s]

 52%|█████▏    | 1711/3268 [11:51<10:47,  2.40it/s]

 52%|█████▏    | 1712/3268 [11:51<10:47,  2.40it/s]

 52%|█████▏    | 1713/3268 [11:52<10:47,  2.40it/s]

 52%|█████▏    | 1714/3268 [11:52<10:46,  2.40it/s]

 52%|█████▏    | 1715/3268 [11:53<10:46,  2.40it/s]

 53%|█████▎    | 1716/3268 [11:53<10:46,  2.40it/s]

 53%|█████▎    | 1717/3268 [11:53<10:46,  2.40it/s]

 53%|█████▎    | 1718/3268 [11:54<10:45,  2.40it/s]

 53%|█████▎    | 1719/3268 [11:54<10:45,  2.40it/s]

 53%|█████▎    | 1720/3268 [11:55<10:44,  2.40it/s]

 53%|█████▎    | 1721/3268 [11:55<10:44,  2.40it/s]

 53%|█████▎    | 1722/3268 [11:55<10:43,  2.40it/s]

 53%|█████▎    | 1723/3268 [11:56<10:43,  2.40it/s]

 53%|█████▎    | 1724/3268 [11:56<10:42,  2.40it/s]

 53%|█████▎    | 1725/3268 [11:57<10:42,  2.40it/s]

 53%|█████▎    | 1726/3268 [11:57<10:42,  2.40it/s]

 53%|█████▎    | 1727/3268 [11:58<10:42,  2.40it/s]

 53%|█████▎    | 1728/3268 [11:58<10:40,  2.40it/s]

 53%|█████▎    | 1729/3268 [11:58<10:41,  2.40it/s]

 53%|█████▎    | 1730/3268 [11:59<10:40,  2.40it/s]

 53%|█████▎    | 1731/3268 [11:59<10:40,  2.40it/s]

 53%|█████▎    | 1732/3268 [12:00<10:38,  2.41it/s]

 53%|█████▎    | 1733/3268 [12:00<10:39,  2.40it/s]

 53%|█████▎    | 1734/3268 [12:00<10:40,  2.40it/s]

 53%|█████▎    | 1735/3268 [12:01<10:40,  2.39it/s]

 53%|█████▎    | 1736/3268 [12:01<10:39,  2.39it/s]

 53%|█████▎    | 1737/3268 [12:02<10:39,  2.39it/s]

 53%|█████▎    | 1738/3268 [12:02<10:38,  2.39it/s]

 53%|█████▎    | 1739/3268 [12:03<10:38,  2.40it/s]

 53%|█████▎    | 1740/3268 [12:03<10:36,  2.40it/s]

 53%|█████▎    | 1741/3268 [12:03<10:36,  2.40it/s]

 53%|█████▎    | 1742/3268 [12:04<10:39,  2.38it/s]

 53%|█████▎    | 1743/3268 [12:04<10:38,  2.39it/s]

 53%|█████▎    | 1744/3268 [12:05<10:36,  2.39it/s]

 53%|█████▎    | 1745/3268 [12:05<10:35,  2.40it/s]

 53%|█████▎    | 1746/3268 [12:05<10:34,  2.40it/s]

 53%|█████▎    | 1747/3268 [12:06<10:34,  2.40it/s]

 53%|█████▎    | 1748/3268 [12:06<10:33,  2.40it/s]

 54%|█████▎    | 1749/3268 [12:07<10:32,  2.40it/s]

 54%|█████▎    | 1750/3268 [12:07<10:33,  2.40it/s]

 54%|█████▎    | 1751/3268 [12:08<10:32,  2.40it/s]

 54%|█████▎    | 1752/3268 [12:08<10:32,  2.40it/s]

 54%|█████▎    | 1753/3268 [12:08<10:31,  2.40it/s]

 54%|█████▎    | 1754/3268 [12:09<10:30,  2.40it/s]

 54%|█████▎    | 1755/3268 [12:09<10:29,  2.40it/s]

 54%|█████▎    | 1756/3268 [12:10<10:29,  2.40it/s]

 54%|█████▍    | 1757/3268 [12:10<10:27,  2.41it/s]

 54%|█████▍    | 1758/3268 [12:10<10:29,  2.40it/s]

 54%|█████▍    | 1759/3268 [12:11<10:27,  2.40it/s]

 54%|█████▍    | 1760/3268 [12:11<10:28,  2.40it/s]

 54%|█████▍    | 1761/3268 [12:12<10:28,  2.40it/s]

 54%|█████▍    | 1762/3268 [12:12<10:27,  2.40it/s]

 54%|█████▍    | 1763/3268 [12:13<10:26,  2.40it/s]

 54%|█████▍    | 1764/3268 [12:13<10:27,  2.40it/s]

 54%|█████▍    | 1765/3268 [12:13<10:26,  2.40it/s]

 54%|█████▍    | 1766/3268 [12:14<10:25,  2.40it/s]

 54%|█████▍    | 1767/3268 [12:14<10:24,  2.40it/s]

 54%|█████▍    | 1768/3268 [12:15<10:24,  2.40it/s]

 54%|█████▍    | 1769/3268 [12:15<10:24,  2.40it/s]

 54%|█████▍    | 1770/3268 [12:15<10:24,  2.40it/s]

 54%|█████▍    | 1771/3268 [12:16<10:23,  2.40it/s]

 54%|█████▍    | 1772/3268 [12:16<10:24,  2.40it/s]

 54%|█████▍    | 1773/3268 [12:17<10:23,  2.40it/s]

 54%|█████▍    | 1774/3268 [12:17<10:23,  2.39it/s]

 54%|█████▍    | 1775/3268 [12:18<10:23,  2.40it/s]

 54%|█████▍    | 1776/3268 [12:18<10:23,  2.39it/s]

 54%|█████▍    | 1777/3268 [12:18<10:23,  2.39it/s]

 54%|█████▍    | 1778/3268 [12:19<10:22,  2.39it/s]

 54%|█████▍    | 1779/3268 [12:19<10:22,  2.39it/s]

 54%|█████▍    | 1780/3268 [12:20<10:22,  2.39it/s]

 54%|█████▍    | 1781/3268 [12:20<10:20,  2.40it/s]

 55%|█████▍    | 1782/3268 [12:20<10:20,  2.39it/s]

 55%|█████▍    | 1783/3268 [12:21<10:19,  2.40it/s]

 55%|█████▍    | 1784/3268 [12:21<10:19,  2.40it/s]

 55%|█████▍    | 1785/3268 [12:22<10:19,  2.39it/s]

 55%|█████▍    | 1786/3268 [12:22<10:20,  2.39it/s]

 55%|█████▍    | 1787/3268 [12:23<10:19,  2.39it/s]

 55%|█████▍    | 1788/3268 [12:23<10:19,  2.39it/s]

 55%|█████▍    | 1789/3268 [12:23<10:17,  2.39it/s]

 55%|█████▍    | 1790/3268 [12:24<10:16,  2.40it/s]

 55%|█████▍    | 1791/3268 [12:24<10:16,  2.40it/s]

 55%|█████▍    | 1792/3268 [12:25<10:15,  2.40it/s]

 55%|█████▍    | 1793/3268 [12:25<10:16,  2.39it/s]

 55%|█████▍    | 1794/3268 [12:25<10:15,  2.40it/s]

 55%|█████▍    | 1795/3268 [12:26<10:14,  2.40it/s]

 55%|█████▍    | 1796/3268 [12:26<10:14,  2.40it/s]

 55%|█████▍    | 1797/3268 [12:27<10:14,  2.39it/s]

 55%|█████▌    | 1798/3268 [12:27<10:13,  2.40it/s]

 55%|█████▌    | 1799/3268 [12:28<10:13,  2.40it/s]

 55%|█████▌    | 1800/3268 [12:28<10:12,  2.40it/s]

 55%|█████▌    | 1801/3268 [12:28<10:12,  2.39it/s]

 55%|█████▌    | 1802/3268 [12:29<10:11,  2.40it/s]

 55%|█████▌    | 1803/3268 [12:29<10:11,  2.40it/s]

 55%|█████▌    | 1804/3268 [12:30<10:10,  2.40it/s]

 55%|█████▌    | 1805/3268 [12:30<10:10,  2.40it/s]

 55%|█████▌    | 1806/3268 [12:30<10:10,  2.40it/s]

 55%|█████▌    | 1807/3268 [12:31<10:10,  2.39it/s]

 55%|█████▌    | 1808/3268 [12:31<10:09,  2.40it/s]

 55%|█████▌    | 1809/3268 [12:32<10:09,  2.39it/s]

 55%|█████▌    | 1810/3268 [12:32<10:08,  2.40it/s]

 55%|█████▌    | 1811/3268 [12:33<10:07,  2.40it/s]

 55%|█████▌    | 1812/3268 [12:33<10:06,  2.40it/s]

 55%|█████▌    | 1813/3268 [12:33<10:06,  2.40it/s]

 56%|█████▌    | 1814/3268 [12:34<10:06,  2.40it/s]

 56%|█████▌    | 1815/3268 [12:34<10:07,  2.39it/s]

 56%|█████▌    | 1816/3268 [12:35<10:06,  2.39it/s]

 56%|█████▌    | 1817/3268 [12:35<10:06,  2.39it/s]

 56%|█████▌    | 1818/3268 [12:35<10:05,  2.39it/s]

 56%|█████▌    | 1819/3268 [12:36<10:05,  2.39it/s]

 56%|█████▌    | 1820/3268 [12:36<10:04,  2.40it/s]

 56%|█████▌    | 1821/3268 [12:37<10:04,  2.39it/s]

 56%|█████▌    | 1822/3268 [12:37<10:03,  2.40it/s]

 56%|█████▌    | 1823/3268 [12:38<10:03,  2.39it/s]

 56%|█████▌    | 1824/3268 [12:38<10:02,  2.40it/s]

 56%|█████▌    | 1825/3268 [12:38<10:02,  2.40it/s]

 56%|█████▌    | 1826/3268 [12:39<10:02,  2.39it/s]

 56%|█████▌    | 1827/3268 [12:39<10:02,  2.39it/s]

 56%|█████▌    | 1828/3268 [12:40<10:01,  2.39it/s]

 56%|█████▌    | 1829/3268 [12:40<10:01,  2.39it/s]

 56%|█████▌    | 1830/3268 [12:40<10:01,  2.39it/s]

 56%|█████▌    | 1831/3268 [12:41<10:00,  2.39it/s]

 56%|█████▌    | 1832/3268 [12:41<09:59,  2.39it/s]

 56%|█████▌    | 1833/3268 [12:42<10:00,  2.39it/s]

 56%|█████▌    | 1834/3268 [12:42<10:01,  2.39it/s]

 56%|█████▌    | 1835/3268 [12:43<09:59,  2.39it/s]

 56%|█████▌    | 1836/3268 [12:43<09:58,  2.39it/s]

 56%|█████▌    | 1837/3268 [12:43<09:58,  2.39it/s]

 56%|█████▌    | 1838/3268 [12:44<09:57,  2.39it/s]

 56%|█████▋    | 1839/3268 [12:44<09:56,  2.39it/s]

 56%|█████▋    | 1840/3268 [12:45<09:56,  2.39it/s]

 56%|█████▋    | 1841/3268 [12:45<09:55,  2.40it/s]

 56%|█████▋    | 1842/3268 [12:46<09:56,  2.39it/s]

 56%|█████▋    | 1843/3268 [12:46<09:56,  2.39it/s]

 56%|█████▋    | 1844/3268 [12:46<09:56,  2.39it/s]

 56%|█████▋    | 1845/3268 [12:47<09:55,  2.39it/s]

 56%|█████▋    | 1846/3268 [12:47<09:55,  2.39it/s]

 57%|█████▋    | 1847/3268 [12:48<09:54,  2.39it/s]

 57%|█████▋    | 1848/3268 [12:48<09:54,  2.39it/s]

 57%|█████▋    | 1849/3268 [12:48<09:53,  2.39it/s]

 57%|█████▋    | 1850/3268 [12:49<09:53,  2.39it/s]

 57%|█████▋    | 1851/3268 [12:49<09:53,  2.39it/s]

 57%|█████▋    | 1852/3268 [12:50<09:52,  2.39it/s]

 57%|█████▋    | 1853/3268 [12:50<09:51,  2.39it/s]

 57%|█████▋    | 1854/3268 [12:51<09:50,  2.39it/s]

 57%|█████▋    | 1855/3268 [12:51<09:50,  2.39it/s]

 57%|█████▋    | 1856/3268 [12:51<09:50,  2.39it/s]

 57%|█████▋    | 1857/3268 [12:52<09:50,  2.39it/s]

 57%|█████▋    | 1858/3268 [12:52<09:49,  2.39it/s]

 57%|█████▋    | 1859/3268 [12:53<09:49,  2.39it/s]

 57%|█████▋    | 1860/3268 [12:53<09:47,  2.40it/s]

 57%|█████▋    | 1861/3268 [12:53<09:48,  2.39it/s]

 57%|█████▋    | 1862/3268 [12:54<09:48,  2.39it/s]

 57%|█████▋    | 1863/3268 [12:54<09:47,  2.39it/s]

 57%|█████▋    | 1864/3268 [12:55<09:46,  2.39it/s]

 57%|█████▋    | 1865/3268 [12:55<09:46,  2.39it/s]

 57%|█████▋    | 1866/3268 [12:56<09:45,  2.39it/s]

 57%|█████▋    | 1867/3268 [12:56<09:44,  2.40it/s]

 57%|█████▋    | 1868/3268 [12:56<09:44,  2.40it/s]

 57%|█████▋    | 1869/3268 [12:57<09:44,  2.39it/s]

 57%|█████▋    | 1870/3268 [12:57<09:44,  2.39it/s]

 57%|█████▋    | 1871/3268 [12:58<09:42,  2.40it/s]

 57%|█████▋    | 1872/3268 [12:58<09:42,  2.40it/s]

 57%|█████▋    | 1873/3268 [12:58<09:42,  2.39it/s]

 57%|█████▋    | 1874/3268 [12:59<09:42,  2.39it/s]

 57%|█████▋    | 1875/3268 [12:59<09:42,  2.39it/s]

 57%|█████▋    | 1876/3268 [13:00<09:41,  2.39it/s]

 57%|█████▋    | 1877/3268 [13:00<09:41,  2.39it/s]

logging
logging the anndata

 57%|█████▋    | 1878/3268 [13:01<10:03,  2.30it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 57%|█████▋    | 1879/3268 [13:01<09:54,  2.34it/s]

 58%|█████▊    | 1880/3268 [13:01<09:46,  2.37it/s]

 58%|█████▊    | 1881/3268 [13:02<09:41,  2.39it/s]

 58%|█████▊    | 1882/3268 [13:02<09:37,  2.40it/s]

 58%|█████▊    | 1883/3268 [13:03<09:34,  2.41it/s]

 58%|█████▊    | 1884/3268 [13:03<09:31,  2.42it/s]

 58%|█████▊    | 1885/3268 [13:03<09:29,  2.43it/s]

 58%|█████▊    | 1886/3268 [13:04<09:28,  2.43it/s]

 58%|█████▊    | 1887/3268 [13:04<09:28,  2.43it/s]

 58%|█████▊    | 1888/3268 [13:05<09:27,  2.43it/s]

 58%|█████▊    | 1889/3268 [13:05<09:26,  2.43it/s]

 58%|█████▊    | 1890/3268 [13:06<09:26,  2.43it/s]

 58%|█████▊    | 1891/3268 [13:06<09:25,  2.44it/s]

 58%|█████▊    | 1892/3268 [13:06<09:25,  2.43it/s]

 58%|█████▊    | 1893/3268 [13:07<09:24,  2.43it/s]

 58%|█████▊    | 1894/3268 [13:07<09:23,  2.44it/s]

 58%|█████▊    | 1895/3268 [13:08<09:23,  2.44it/s]

 58%|█████▊    | 1896/3268 [13:08<09:23,  2.44it/s]

 58%|█████▊    | 1897/3268 [13:08<09:23,  2.43it/s]

 58%|█████▊    | 1898/3268 [13:09<09:22,  2.44it/s]

 58%|█████▊    | 1899/3268 [13:09<09:22,  2.43it/s]

 58%|█████▊    | 1900/3268 [13:10<09:21,  2.44it/s]

 58%|█████▊    | 1901/3268 [13:10<09:21,  2.43it/s]

 58%|█████▊    | 1902/3268 [13:10<09:20,  2.44it/s]

 58%|█████▊    | 1903/3268 [13:11<09:20,  2.44it/s]

 58%|█████▊    | 1904/3268 [13:11<09:20,  2.44it/s]

 58%|█████▊    | 1905/3268 [13:12<09:20,  2.43it/s]

 58%|█████▊    | 1906/3268 [13:12<09:21,  2.43it/s]

 58%|█████▊    | 1907/3268 [13:13<09:19,  2.43it/s]

 58%|█████▊    | 1908/3268 [13:13<09:18,  2.43it/s]

 58%|█████▊    | 1909/3268 [13:13<09:18,  2.43it/s]

 58%|█████▊    | 1910/3268 [13:14<09:18,  2.43it/s]

 58%|█████▊    | 1911/3268 [13:14<09:17,  2.43it/s]

 59%|█████▊    | 1912/3268 [13:15<09:17,  2.43it/s]

 59%|█████▊    | 1913/3268 [13:15<09:16,  2.44it/s]

 59%|█████▊    | 1914/3268 [13:15<09:15,  2.44it/s]

 59%|█████▊    | 1915/3268 [13:16<09:14,  2.44it/s]

 59%|█████▊    | 1916/3268 [13:16<09:14,  2.44it/s]

 59%|█████▊    | 1917/3268 [13:17<09:14,  2.44it/s]

 59%|█████▊    | 1918/3268 [13:17<09:14,  2.44it/s]

 59%|█████▊    | 1919/3268 [13:17<09:14,  2.43it/s]

 59%|█████▉    | 1920/3268 [13:18<09:13,  2.44it/s]

 59%|█████▉    | 1921/3268 [13:18<09:13,  2.43it/s]

 59%|█████▉    | 1922/3268 [13:19<09:12,  2.43it/s]

 59%|█████▉    | 1923/3268 [13:19<09:13,  2.43it/s]

 59%|█████▉    | 1924/3268 [13:20<09:12,  2.43it/s]

 59%|█████▉    | 1925/3268 [13:20<09:11,  2.43it/s]

 59%|█████▉    | 1926/3268 [13:20<09:11,  2.43it/s]

 59%|█████▉    | 1927/3268 [13:21<09:10,  2.43it/s]

 59%|█████▉    | 1928/3268 [13:21<09:11,  2.43it/s]

 59%|█████▉    | 1929/3268 [13:22<09:10,  2.43it/s]

 59%|█████▉    | 1930/3268 [13:22<09:10,  2.43it/s]

 59%|█████▉    | 1931/3268 [13:22<09:10,  2.43it/s]

 59%|█████▉    | 1932/3268 [13:23<09:09,  2.43it/s]

 59%|█████▉    | 1933/3268 [13:23<09:09,  2.43it/s]

 59%|█████▉    | 1934/3268 [13:24<09:08,  2.43it/s]

 59%|█████▉    | 1935/3268 [13:24<09:07,  2.43it/s]

 59%|█████▉    | 1936/3268 [13:24<09:07,  2.43it/s]

 59%|█████▉    | 1937/3268 [13:25<09:06,  2.43it/s]

 59%|█████▉    | 1938/3268 [13:25<09:06,  2.44it/s]

 59%|█████▉    | 1939/3268 [13:26<09:05,  2.43it/s]

 59%|█████▉    | 1940/3268 [13:26<09:05,  2.44it/s]

 59%|█████▉    | 1941/3268 [13:26<09:05,  2.43it/s]

 59%|█████▉    | 1942/3268 [13:27<09:04,  2.43it/s]

 59%|█████▉    | 1943/3268 [13:27<09:04,  2.43it/s]

 59%|█████▉    | 1944/3268 [13:28<09:04,  2.43it/s]

 60%|█████▉    | 1945/3268 [13:28<09:04,  2.43it/s]

 60%|█████▉    | 1946/3268 [13:29<09:03,  2.43it/s]

 60%|█████▉    | 1947/3268 [13:29<09:03,  2.43it/s]

 60%|█████▉    | 1948/3268 [13:29<09:02,  2.43it/s]

 60%|█████▉    | 1949/3268 [13:30<09:02,  2.43it/s]

 60%|█████▉    | 1950/3268 [13:30<09:02,  2.43it/s]

 60%|█████▉    | 1951/3268 [13:31<09:01,  2.43it/s]

 60%|█████▉    | 1952/3268 [13:31<09:01,  2.43it/s]

 60%|█████▉    | 1953/3268 [13:31<09:01,  2.43it/s]

 60%|█████▉    | 1954/3268 [13:32<09:00,  2.43it/s]

 60%|█████▉    | 1955/3268 [13:32<09:00,  2.43it/s]

 60%|█████▉    | 1956/3268 [13:33<09:00,  2.43it/s]

 60%|█████▉    | 1957/3268 [13:33<08:59,  2.43it/s]

 60%|█████▉    | 1958/3268 [13:33<08:59,  2.43it/s]

 60%|█████▉    | 1959/3268 [13:34<08:58,  2.43it/s]

 60%|█████▉    | 1960/3268 [13:34<08:58,  2.43it/s]

 60%|██████    | 1961/3268 [13:35<08:58,  2.43it/s]

 60%|██████    | 1962/3268 [13:35<08:57,  2.43it/s]

 60%|██████    | 1963/3268 [13:36<08:56,  2.43it/s]

 60%|██████    | 1964/3268 [13:36<08:55,  2.43it/s]

 60%|██████    | 1965/3268 [13:36<08:55,  2.43it/s]

 60%|██████    | 1966/3268 [13:37<08:54,  2.43it/s]

 60%|██████    | 1967/3268 [13:37<08:54,  2.43it/s]

 60%|██████    | 1968/3268 [13:38<08:54,  2.43it/s]

 60%|██████    | 1969/3268 [13:38<08:54,  2.43it/s]

 60%|██████    | 1970/3268 [13:38<08:54,  2.43it/s]

 60%|██████    | 1971/3268 [13:39<08:53,  2.43it/s]

 60%|██████    | 1972/3268 [13:39<08:53,  2.43it/s]

 60%|██████    | 1973/3268 [13:40<08:52,  2.43it/s]

 60%|██████    | 1974/3268 [13:40<08:52,  2.43it/s]

 60%|██████    | 1975/3268 [13:40<08:52,  2.43it/s]

 60%|██████    | 1976/3268 [13:41<08:51,  2.43it/s]

 60%|██████    | 1977/3268 [13:41<08:51,  2.43it/s]

 61%|██████    | 1978/3268 [13:42<08:51,  2.43it/s]

 61%|██████    | 1979/3268 [13:42<08:50,  2.43it/s]

 61%|██████    | 1980/3268 [13:43<08:50,  2.43it/s]

 61%|██████    | 1981/3268 [13:43<08:49,  2.43it/s]

 61%|██████    | 1982/3268 [13:43<08:49,  2.43it/s]

 61%|██████    | 1983/3268 [13:44<08:49,  2.43it/s]

 61%|██████    | 1984/3268 [13:44<08:48,  2.43it/s]

 61%|██████    | 1985/3268 [13:45<08:49,  2.43it/s]

 61%|██████    | 1986/3268 [13:45<08:48,  2.43it/s]

 61%|██████    | 1987/3268 [13:45<08:48,  2.43it/s]

 61%|██████    | 1988/3268 [13:46<08:47,  2.43it/s]

 61%|██████    | 1989/3268 [13:46<08:48,  2.42it/s]

 61%|██████    | 1990/3268 [13:47<08:47,  2.42it/s]

 61%|██████    | 1991/3268 [13:47<08:46,  2.43it/s]

 61%|██████    | 1992/3268 [13:47<08:45,  2.43it/s]

 61%|██████    | 1993/3268 [13:48<08:45,  2.43it/s]

 61%|██████    | 1994/3268 [13:48<08:45,  2.43it/s]

 61%|██████    | 1995/3268 [13:49<08:44,  2.43it/s]

 61%|██████    | 1996/3268 [13:49<08:45,  2.42it/s]

 61%|██████    | 1997/3268 [13:50<08:43,  2.43it/s]

 61%|██████    | 1998/3268 [13:50<08:43,  2.43it/s]

 61%|██████    | 1999/3268 [13:50<08:42,  2.43it/s]

 61%|██████    | 2000/3268 [13:51<08:42,  2.43it/s]

 61%|██████    | 2001/3268 [13:51<08:42,  2.43it/s]

 61%|██████▏   | 2002/3268 [13:52<08:42,  2.42it/s]

 61%|██████▏   | 2003/3268 [13:52<08:41,  2.42it/s]

 61%|██████▏   | 2004/3268 [13:52<08:40,  2.43it/s]

 61%|██████▏   | 2005/3268 [13:53<08:41,  2.42it/s]

 61%|██████▏   | 2006/3268 [13:53<08:40,  2.42it/s]

 61%|██████▏   | 2007/3268 [13:54<08:40,  2.42it/s]

 61%|██████▏   | 2008/3268 [13:54<08:39,  2.42it/s]

 61%|██████▏   | 2009/3268 [13:54<08:39,  2.42it/s]

 62%|██████▏   | 2010/3268 [13:55<08:39,  2.42it/s]

 62%|██████▏   | 2011/3268 [13:55<08:37,  2.43it/s]

 62%|██████▏   | 2012/3268 [13:56<08:37,  2.43it/s]

 62%|██████▏   | 2013/3268 [13:56<08:37,  2.43it/s]

 62%|██████▏   | 2014/3268 [13:57<08:36,  2.43it/s]

 62%|██████▏   | 2015/3268 [13:57<08:36,  2.43it/s]

 62%|██████▏   | 2016/3268 [13:57<08:36,  2.42it/s]

 62%|██████▏   | 2017/3268 [13:58<08:35,  2.43it/s]

 62%|██████▏   | 2018/3268 [13:58<08:35,  2.43it/s]

 62%|██████▏   | 2019/3268 [13:59<08:35,  2.42it/s]

 62%|██████▏   | 2020/3268 [13:59<08:34,  2.42it/s]

 62%|██████▏   | 2021/3268 [13:59<08:34,  2.42it/s]

 62%|██████▏   | 2022/3268 [14:00<08:33,  2.43it/s]

 62%|██████▏   | 2023/3268 [14:00<08:33,  2.42it/s]

 62%|██████▏   | 2024/3268 [14:01<08:33,  2.42it/s]

 62%|██████▏   | 2025/3268 [14:01<08:33,  2.42it/s]

 62%|██████▏   | 2026/3268 [14:02<08:33,  2.42it/s]

 62%|██████▏   | 2027/3268 [14:02<08:32,  2.42it/s]

 62%|██████▏   | 2028/3268 [14:02<08:32,  2.42it/s]

 62%|██████▏   | 2029/3268 [14:03<08:31,  2.42it/s]

 62%|██████▏   | 2030/3268 [14:03<08:30,  2.42it/s]

 62%|██████▏   | 2031/3268 [14:04<08:29,  2.43it/s]

 62%|██████▏   | 2032/3268 [14:04<08:29,  2.43it/s]

 62%|██████▏   | 2033/3268 [14:04<08:29,  2.42it/s]

 62%|██████▏   | 2034/3268 [14:05<08:29,  2.42it/s]

 62%|██████▏   | 2035/3268 [14:05<08:28,  2.42it/s]

 62%|██████▏   | 2036/3268 [14:06<08:27,  2.43it/s]

 62%|██████▏   | 2037/3268 [14:06<08:27,  2.42it/s]

 62%|██████▏   | 2038/3268 [14:06<08:27,  2.42it/s]

 62%|██████▏   | 2039/3268 [14:07<08:26,  2.42it/s]

 62%|██████▏   | 2040/3268 [14:07<08:26,  2.43it/s]

 62%|██████▏   | 2041/3268 [14:08<08:25,  2.43it/s]

 62%|██████▏   | 2042/3268 [14:08<08:25,  2.43it/s]

 63%|██████▎   | 2043/3268 [14:09<08:25,  2.42it/s]

 63%|██████▎   | 2044/3268 [14:09<08:25,  2.42it/s]

 63%|██████▎   | 2045/3268 [14:09<08:25,  2.42it/s]

 63%|██████▎   | 2046/3268 [14:10<08:24,  2.42it/s]

 63%|██████▎   | 2047/3268 [14:10<08:24,  2.42it/s]

 63%|██████▎   | 2048/3268 [14:11<08:23,  2.42it/s]

 63%|██████▎   | 2049/3268 [14:11<08:22,  2.42it/s]

 63%|██████▎   | 2050/3268 [14:11<08:22,  2.42it/s]

 63%|██████▎   | 2051/3268 [14:12<08:22,  2.42it/s]

 63%|██████▎   | 2052/3268 [14:12<08:21,  2.42it/s]

 63%|██████▎   | 2053/3268 [14:13<08:21,  2.42it/s]

 63%|██████▎   | 2054/3268 [14:13<08:21,  2.42it/s]

 63%|██████▎   | 2055/3268 [14:13<08:21,  2.42it/s]

 63%|██████▎   | 2056/3268 [14:14<08:21,  2.42it/s]

 63%|██████▎   | 2057/3268 [14:14<08:20,  2.42it/s]

 63%|██████▎   | 2058/3268 [14:15<08:21,  2.41it/s]

 63%|██████▎   | 2059/3268 [14:15<08:20,  2.42it/s]

 63%|██████▎   | 2060/3268 [14:16<08:19,  2.42it/s]

 63%|██████▎   | 2061/3268 [14:16<08:18,  2.42it/s]

 63%|██████▎   | 2062/3268 [14:16<08:18,  2.42it/s]

 63%|██████▎   | 2063/3268 [14:17<08:17,  2.42it/s]

 63%|██████▎   | 2064/3268 [14:17<08:17,  2.42it/s]

 63%|██████▎   | 2065/3268 [14:18<08:20,  2.40it/s]

 63%|██████▎   | 2066/3268 [14:18<08:19,  2.41it/s]

 63%|██████▎   | 2067/3268 [14:18<08:17,  2.41it/s]

 63%|██████▎   | 2068/3268 [14:19<08:16,  2.42it/s]

 63%|██████▎   | 2069/3268 [14:19<08:15,  2.42it/s]

 63%|██████▎   | 2070/3268 [14:20<08:15,  2.42it/s]

 63%|██████▎   | 2071/3268 [14:20<08:15,  2.42it/s]

 63%|██████▎   | 2072/3268 [14:21<08:14,  2.42it/s]

 63%|██████▎   | 2073/3268 [14:21<08:13,  2.42it/s]

 63%|██████▎   | 2074/3268 [14:21<08:13,  2.42it/s]

 63%|██████▎   | 2075/3268 [14:22<08:13,  2.42it/s]

 64%|██████▎   | 2076/3268 [14:22<08:12,  2.42it/s]

 64%|██████▎   | 2077/3268 [14:23<08:12,  2.42it/s]

 64%|██████▎   | 2078/3268 [14:23<08:11,  2.42it/s]

 64%|██████▎   | 2079/3268 [14:23<08:10,  2.42it/s]

 64%|██████▎   | 2080/3268 [14:24<08:11,  2.42it/s]

 64%|██████▎   | 2081/3268 [14:24<08:10,  2.42it/s]

 64%|██████▎   | 2082/3268 [14:25<08:10,  2.42it/s]

 64%|██████▎   | 2083/3268 [14:25<08:10,  2.42it/s]

 64%|██████▍   | 2084/3268 [14:25<08:09,  2.42it/s]

 64%|██████▍   | 2085/3268 [14:26<08:08,  2.42it/s]

 64%|██████▍   | 2086/3268 [14:26<08:08,  2.42it/s]

 64%|██████▍   | 2087/3268 [14:27<08:07,  2.42it/s]

 64%|██████▍   | 2088/3268 [14:27<08:08,  2.42it/s]

 64%|██████▍   | 2089/3268 [14:28<08:07,  2.42it/s]

 64%|██████▍   | 2090/3268 [14:28<08:06,  2.42it/s]

 64%|██████▍   | 2091/3268 [14:28<08:06,  2.42it/s]

 64%|██████▍   | 2092/3268 [14:29<08:06,  2.42it/s]

 64%|██████▍   | 2093/3268 [14:29<08:05,  2.42it/s]

 64%|██████▍   | 2094/3268 [14:30<08:05,  2.42it/s]

 64%|██████▍   | 2095/3268 [14:30<08:05,  2.42it/s]

 64%|██████▍   | 2096/3268 [14:30<08:04,  2.42it/s]

 64%|██████▍   | 2097/3268 [14:31<08:04,  2.42it/s]

 64%|██████▍   | 2098/3268 [14:31<08:03,  2.42it/s]

 64%|██████▍   | 2099/3268 [14:32<08:03,  2.42it/s]

 64%|██████▍   | 2100/3268 [14:32<08:02,  2.42it/s]

 64%|██████▍   | 2101/3268 [14:33<08:03,  2.42it/s]

 64%|██████▍   | 2102/3268 [14:33<08:03,  2.41it/s]

 64%|██████▍   | 2103/3268 [14:33<08:03,  2.41it/s]

 64%|██████▍   | 2104/3268 [14:34<08:02,  2.41it/s]

 64%|██████▍   | 2105/3268 [14:34<08:02,  2.41it/s]

 64%|██████▍   | 2106/3268 [14:35<08:01,  2.41it/s]

 64%|██████▍   | 2107/3268 [14:35<08:01,  2.41it/s]

 65%|██████▍   | 2108/3268 [14:35<08:00,  2.42it/s]

 65%|██████▍   | 2109/3268 [14:36<08:00,  2.41it/s]

 65%|██████▍   | 2110/3268 [14:36<07:59,  2.41it/s]

 65%|██████▍   | 2111/3268 [14:37<07:58,  2.42it/s]

 65%|██████▍   | 2112/3268 [14:37<07:57,  2.42it/s]

 65%|██████▍   | 2113/3268 [14:37<07:57,  2.42it/s]

 65%|██████▍   | 2114/3268 [14:38<07:57,  2.42it/s]

 65%|██████▍   | 2115/3268 [14:38<07:57,  2.42it/s]

 65%|██████▍   | 2116/3268 [14:39<07:57,  2.41it/s]

 65%|██████▍   | 2117/3268 [14:39<07:56,  2.42it/s]

 65%|██████▍   | 2118/3268 [14:40<07:55,  2.42it/s]

 65%|██████▍   | 2119/3268 [14:40<07:55,  2.42it/s]

 65%|██████▍   | 2120/3268 [14:40<07:55,  2.41it/s]

 65%|██████▍   | 2121/3268 [14:41<07:54,  2.42it/s]

 65%|██████▍   | 2122/3268 [14:41<07:54,  2.42it/s]

 65%|██████▍   | 2123/3268 [14:42<07:54,  2.41it/s]

 65%|██████▍   | 2124/3268 [14:42<07:54,  2.41it/s]

 65%|██████▌   | 2125/3268 [14:42<07:53,  2.41it/s]

 65%|██████▌   | 2126/3268 [14:43<07:53,  2.41it/s]

 65%|██████▌   | 2127/3268 [14:43<07:52,  2.41it/s]

 65%|██████▌   | 2128/3268 [14:44<07:52,  2.41it/s]

 65%|██████▌   | 2129/3268 [14:44<07:51,  2.42it/s]

 65%|██████▌   | 2130/3268 [14:45<07:51,  2.42it/s]

 65%|██████▌   | 2131/3268 [14:45<07:51,  2.41it/s]

 65%|██████▌   | 2132/3268 [14:45<07:50,  2.41it/s]

 65%|██████▌   | 2133/3268 [14:46<07:50,  2.41it/s]

 65%|██████▌   | 2134/3268 [14:46<07:48,  2.42it/s]

 65%|██████▌   | 2135/3268 [14:47<07:48,  2.42it/s]

 65%|██████▌   | 2136/3268 [14:47<07:48,  2.42it/s]

 65%|██████▌   | 2137/3268 [14:47<07:48,  2.42it/s]

 65%|██████▌   | 2138/3268 [14:48<07:47,  2.42it/s]

 65%|██████▌   | 2139/3268 [14:48<07:47,  2.42it/s]

 65%|██████▌   | 2140/3268 [14:49<07:47,  2.41it/s]

 66%|██████▌   | 2141/3268 [14:49<07:46,  2.42it/s]

 66%|██████▌   | 2142/3268 [14:49<07:45,  2.42it/s]

 66%|██████▌   | 2143/3268 [14:50<07:46,  2.41it/s]

 66%|██████▌   | 2144/3268 [14:50<07:45,  2.41it/s]

 66%|██████▌   | 2145/3268 [14:51<07:45,  2.41it/s]

 66%|██████▌   | 2146/3268 [14:51<07:46,  2.41it/s]

 66%|██████▌   | 2147/3268 [14:52<07:45,  2.41it/s]

 66%|██████▌   | 2148/3268 [14:52<07:44,  2.41it/s]

 66%|██████▌   | 2149/3268 [14:52<07:46,  2.40it/s]

 66%|██████▌   | 2150/3268 [14:53<07:45,  2.40it/s]

 66%|██████▌   | 2151/3268 [14:53<07:43,  2.41it/s]

 66%|██████▌   | 2152/3268 [14:54<07:43,  2.41it/s]

 66%|██████▌   | 2153/3268 [14:54<07:42,  2.41it/s]

 66%|██████▌   | 2154/3268 [14:54<07:42,  2.41it/s]

 66%|██████▌   | 2155/3268 [14:55<07:41,  2.41it/s]

 66%|██████▌   | 2156/3268 [14:55<07:40,  2.41it/s]

 66%|██████▌   | 2157/3268 [14:56<07:40,  2.41it/s]

 66%|██████▌   | 2158/3268 [14:56<07:39,  2.41it/s]

 66%|██████▌   | 2159/3268 [14:57<07:39,  2.41it/s]

 66%|██████▌   | 2160/3268 [14:57<07:38,  2.41it/s]

 66%|██████▌   | 2161/3268 [14:57<07:38,  2.41it/s]

 66%|██████▌   | 2162/3268 [14:58<07:38,  2.41it/s]

 66%|██████▌   | 2163/3268 [14:58<07:38,  2.41it/s]

 66%|██████▌   | 2164/3268 [14:59<07:38,  2.41it/s]

 66%|██████▌   | 2165/3268 [14:59<07:38,  2.41it/s]

 66%|██████▋   | 2166/3268 [14:59<07:37,  2.41it/s]

 66%|██████▋   | 2167/3268 [15:00<07:37,  2.41it/s]

 66%|██████▋   | 2168/3268 [15:00<07:37,  2.41it/s]

 66%|██████▋   | 2169/3268 [15:01<07:36,  2.41it/s]

 66%|██████▋   | 2170/3268 [15:01<07:36,  2.41it/s]

 66%|██████▋   | 2171/3268 [15:02<07:35,  2.41it/s]

 66%|██████▋   | 2172/3268 [15:02<07:34,  2.41it/s]

 66%|██████▋   | 2173/3268 [15:02<07:34,  2.41it/s]

 67%|██████▋   | 2174/3268 [15:03<07:33,  2.41it/s]

 67%|██████▋   | 2175/3268 [15:03<07:34,  2.41it/s]

 67%|██████▋   | 2176/3268 [15:04<07:33,  2.41it/s]

 67%|██████▋   | 2177/3268 [15:04<07:32,  2.41it/s]

 67%|██████▋   | 2178/3268 [15:04<07:32,  2.41it/s]

 67%|██████▋   | 2179/3268 [15:05<07:31,  2.41it/s]

 67%|██████▋   | 2180/3268 [15:05<07:31,  2.41it/s]

 67%|██████▋   | 2181/3268 [15:06<07:31,  2.41it/s]

 67%|██████▋   | 2182/3268 [15:06<07:30,  2.41it/s]

 67%|██████▋   | 2183/3268 [15:07<07:30,  2.41it/s]

 67%|██████▋   | 2184/3268 [15:07<07:29,  2.41it/s]

 67%|██████▋   | 2185/3268 [15:07<07:29,  2.41it/s]

 67%|██████▋   | 2186/3268 [15:08<07:29,  2.41it/s]

 67%|██████▋   | 2187/3268 [15:08<07:28,  2.41it/s]

 67%|██████▋   | 2188/3268 [15:09<07:27,  2.41it/s]

 67%|██████▋   | 2189/3268 [15:09<07:28,  2.41it/s]

 67%|██████▋   | 2190/3268 [15:09<07:27,  2.41it/s]

 67%|██████▋   | 2191/3268 [15:10<07:27,  2.41it/s]

 67%|██████▋   | 2192/3268 [15:10<07:26,  2.41it/s]

 67%|██████▋   | 2193/3268 [15:11<07:26,  2.41it/s]

 67%|██████▋   | 2194/3268 [15:11<07:25,  2.41it/s]

 67%|██████▋   | 2195/3268 [15:11<07:25,  2.41it/s]

 67%|██████▋   | 2196/3268 [15:12<07:24,  2.41it/s]

 67%|██████▋   | 2197/3268 [15:12<07:24,  2.41it/s]

 67%|██████▋   | 2198/3268 [15:13<07:23,  2.41it/s]

 67%|██████▋   | 2199/3268 [15:13<07:24,  2.41it/s]

 67%|██████▋   | 2200/3268 [15:14<07:24,  2.40it/s]

 67%|██████▋   | 2201/3268 [15:14<07:23,  2.41it/s]

 67%|██████▋   | 2202/3268 [15:14<07:22,  2.41it/s]

 67%|██████▋   | 2203/3268 [15:15<07:22,  2.41it/s]

 67%|██████▋   | 2204/3268 [15:15<07:21,  2.41it/s]

 67%|██████▋   | 2205/3268 [15:16<07:21,  2.41it/s]

 68%|██████▊   | 2206/3268 [15:16<07:21,  2.40it/s]

 68%|██████▊   | 2207/3268 [15:16<07:20,  2.41it/s]

 68%|██████▊   | 2208/3268 [15:17<07:20,  2.41it/s]

 68%|██████▊   | 2209/3268 [15:17<07:19,  2.41it/s]

 68%|██████▊   | 2210/3268 [15:18<07:19,  2.41it/s]

 68%|██████▊   | 2211/3268 [15:18<07:18,  2.41it/s]

 68%|██████▊   | 2212/3268 [15:19<07:18,  2.41it/s]

 68%|██████▊   | 2213/3268 [15:19<07:17,  2.41it/s]

 68%|██████▊   | 2214/3268 [15:19<07:17,  2.41it/s]

 68%|██████▊   | 2215/3268 [15:20<07:16,  2.41it/s]

 68%|██████▊   | 2216/3268 [15:20<07:16,  2.41it/s]

 68%|██████▊   | 2217/3268 [15:21<07:15,  2.41it/s]

 68%|██████▊   | 2218/3268 [15:21<07:15,  2.41it/s]

 68%|██████▊   | 2219/3268 [15:21<07:15,  2.41it/s]

 68%|██████▊   | 2220/3268 [15:22<07:14,  2.41it/s]

 68%|██████▊   | 2221/3268 [15:22<07:14,  2.41it/s]

 68%|██████▊   | 2222/3268 [15:23<07:14,  2.41it/s]

 68%|██████▊   | 2223/3268 [15:23<07:14,  2.41it/s]

 68%|██████▊   | 2224/3268 [15:24<07:13,  2.41it/s]

 68%|██████▊   | 2225/3268 [15:24<07:13,  2.41it/s]

 68%|██████▊   | 2226/3268 [15:24<07:12,  2.41it/s]

 68%|██████▊   | 2227/3268 [15:25<07:12,  2.41it/s]

 68%|██████▊   | 2228/3268 [15:25<07:11,  2.41it/s]

 68%|██████▊   | 2229/3268 [15:26<07:11,  2.41it/s]

 68%|██████▊   | 2230/3268 [15:26<07:11,  2.41it/s]

 68%|██████▊   | 2231/3268 [15:26<07:11,  2.40it/s]

 68%|██████▊   | 2232/3268 [15:27<07:10,  2.41it/s]

 68%|██████▊   | 2233/3268 [15:27<07:09,  2.41it/s]

 68%|██████▊   | 2234/3268 [15:28<07:09,  2.41it/s]

 68%|██████▊   | 2235/3268 [15:28<07:09,  2.41it/s]

 68%|██████▊   | 2236/3268 [15:29<07:08,  2.41it/s]

 68%|██████▊   | 2237/3268 [15:29<07:08,  2.41it/s]

 68%|██████▊   | 2238/3268 [15:29<07:07,  2.41it/s]

 69%|██████▊   | 2239/3268 [15:30<07:07,  2.41it/s]

 69%|██████▊   | 2240/3268 [15:30<07:07,  2.41it/s]

 69%|██████▊   | 2241/3268 [15:31<07:07,  2.40it/s]

 69%|██████▊   | 2242/3268 [15:31<07:06,  2.40it/s]

 69%|██████▊   | 2243/3268 [15:31<07:06,  2.40it/s]

 69%|██████▊   | 2244/3268 [15:32<07:05,  2.41it/s]

 69%|██████▊   | 2245/3268 [15:32<07:05,  2.40it/s]

 69%|██████▊   | 2246/3268 [15:33<07:05,  2.40it/s]

 69%|██████▉   | 2247/3268 [15:33<07:04,  2.40it/s]

 69%|██████▉   | 2248/3268 [15:33<07:04,  2.40it/s]

 69%|██████▉   | 2249/3268 [15:34<07:04,  2.40it/s]

 69%|██████▉   | 2250/3268 [15:34<07:03,  2.40it/s]

 69%|██████▉   | 2251/3268 [15:35<07:03,  2.40it/s]

 69%|██████▉   | 2252/3268 [15:35<07:02,  2.40it/s]

 69%|██████▉   | 2253/3268 [15:36<07:01,  2.41it/s]

 69%|██████▉   | 2254/3268 [15:36<07:01,  2.41it/s]

 69%|██████▉   | 2255/3268 [15:36<07:01,  2.41it/s]

 69%|██████▉   | 2256/3268 [15:37<07:00,  2.41it/s]

 69%|██████▉   | 2257/3268 [15:37<07:00,  2.40it/s]

 69%|██████▉   | 2258/3268 [15:38<06:59,  2.41it/s]

 69%|██████▉   | 2259/3268 [15:38<06:58,  2.41it/s]

 69%|██████▉   | 2260/3268 [15:38<06:58,  2.41it/s]

 69%|██████▉   | 2261/3268 [15:39<06:58,  2.41it/s]

 69%|██████▉   | 2262/3268 [15:39<06:57,  2.41it/s]

 69%|██████▉   | 2263/3268 [15:40<06:57,  2.41it/s]

 69%|██████▉   | 2264/3268 [15:40<06:56,  2.41it/s]

 69%|██████▉   | 2265/3268 [15:41<06:56,  2.41it/s]

 69%|██████▉   | 2266/3268 [15:41<06:56,  2.41it/s]

 69%|██████▉   | 2267/3268 [15:41<06:55,  2.41it/s]

 69%|██████▉   | 2268/3268 [15:42<06:56,  2.40it/s]

 69%|██████▉   | 2269/3268 [15:42<06:55,  2.41it/s]

 69%|██████▉   | 2270/3268 [15:43<06:54,  2.41it/s]

 69%|██████▉   | 2271/3268 [15:43<06:54,  2.41it/s]

 70%|██████▉   | 2272/3268 [15:43<06:53,  2.41it/s]

 70%|██████▉   | 2273/3268 [15:44<06:54,  2.40it/s]

 70%|██████▉   | 2274/3268 [15:44<06:53,  2.40it/s]

 70%|██████▉   | 2275/3268 [15:45<06:53,  2.40it/s]

 70%|██████▉   | 2276/3268 [15:45<06:52,  2.41it/s]

 70%|██████▉   | 2277/3268 [15:46<06:51,  2.41it/s]

 70%|██████▉   | 2278/3268 [15:46<06:51,  2.41it/s]

 70%|██████▉   | 2279/3268 [15:46<06:51,  2.40it/s]

 70%|██████▉   | 2280/3268 [15:47<06:50,  2.40it/s]

 70%|██████▉   | 2281/3268 [15:47<06:50,  2.41it/s]

 70%|██████▉   | 2282/3268 [15:48<06:49,  2.41it/s]

 70%|██████▉   | 2283/3268 [15:48<06:49,  2.41it/s]

 70%|██████▉   | 2284/3268 [15:48<06:48,  2.41it/s]

 70%|██████▉   | 2285/3268 [15:49<06:48,  2.40it/s]

 70%|██████▉   | 2286/3268 [15:49<06:47,  2.41it/s]

 70%|██████▉   | 2287/3268 [15:50<06:47,  2.41it/s]

 70%|███████   | 2288/3268 [15:50<06:47,  2.40it/s]

 70%|███████   | 2289/3268 [15:51<06:47,  2.40it/s]

 70%|███████   | 2290/3268 [15:51<06:47,  2.40it/s]

 70%|███████   | 2291/3268 [15:51<06:46,  2.40it/s]

 70%|███████   | 2292/3268 [15:52<06:45,  2.40it/s]

 70%|███████   | 2293/3268 [15:52<06:45,  2.40it/s]

 70%|███████   | 2294/3268 [15:53<06:46,  2.40it/s]

 70%|███████   | 2295/3268 [15:53<06:45,  2.40it/s]

 70%|███████   | 2296/3268 [15:53<06:45,  2.40it/s]

 70%|███████   | 2297/3268 [15:54<06:44,  2.40it/s]

 70%|███████   | 2298/3268 [15:54<06:43,  2.40it/s]

 70%|███████   | 2299/3268 [15:55<06:43,  2.40it/s]

 70%|███████   | 2300/3268 [15:55<06:42,  2.40it/s]

 70%|███████   | 2301/3268 [15:56<06:42,  2.41it/s]

 70%|███████   | 2302/3268 [15:56<06:41,  2.40it/s]

 70%|███████   | 2303/3268 [15:56<06:41,  2.40it/s]

 71%|███████   | 2304/3268 [15:57<06:41,  2.40it/s]

 71%|███████   | 2305/3268 [15:57<06:40,  2.41it/s]

 71%|███████   | 2306/3268 [15:58<06:39,  2.41it/s]

 71%|███████   | 2307/3268 [15:58<06:39,  2.41it/s]

 71%|███████   | 2308/3268 [15:58<06:39,  2.40it/s]

 71%|███████   | 2309/3268 [15:59<06:38,  2.40it/s]

 71%|███████   | 2310/3268 [15:59<06:38,  2.41it/s]

 71%|███████   | 2311/3268 [16:00<06:37,  2.41it/s]

 71%|███████   | 2312/3268 [16:00<06:36,  2.41it/s]

 71%|███████   | 2313/3268 [16:01<06:36,  2.41it/s]

 71%|███████   | 2314/3268 [16:01<06:36,  2.41it/s]

 71%|███████   | 2315/3268 [16:01<06:36,  2.41it/s]

 71%|███████   | 2316/3268 [16:02<06:36,  2.40it/s]

 71%|███████   | 2317/3268 [16:02<06:35,  2.40it/s]

 71%|███████   | 2318/3268 [16:03<06:35,  2.40it/s]

 71%|███████   | 2319/3268 [16:03<06:35,  2.40it/s]

 71%|███████   | 2320/3268 [16:03<06:34,  2.40it/s]

 71%|███████   | 2321/3268 [16:04<06:34,  2.40it/s]

 71%|███████   | 2322/3268 [16:04<06:33,  2.40it/s]

 71%|███████   | 2323/3268 [16:05<06:33,  2.40it/s]

 71%|███████   | 2324/3268 [16:05<06:33,  2.40it/s]

 71%|███████   | 2325/3268 [16:06<06:32,  2.40it/s]

 71%|███████   | 2326/3268 [16:06<06:32,  2.40it/s]

 71%|███████   | 2327/3268 [16:06<06:31,  2.40it/s]

 71%|███████   | 2328/3268 [16:07<06:33,  2.39it/s]

 71%|███████▏  | 2329/3268 [16:07<06:32,  2.39it/s]

 71%|███████▏  | 2330/3268 [16:08<06:31,  2.39it/s]

 71%|███████▏  | 2331/3268 [16:08<06:30,  2.40it/s]

 71%|███████▏  | 2332/3268 [16:08<06:30,  2.40it/s]

 71%|███████▏  | 2333/3268 [16:09<06:29,  2.40it/s]

 71%|███████▏  | 2334/3268 [16:09<06:29,  2.40it/s]

 71%|███████▏  | 2335/3268 [16:10<06:28,  2.40it/s]

 71%|███████▏  | 2336/3268 [16:10<06:28,  2.40it/s]

 72%|███████▏  | 2337/3268 [16:11<06:27,  2.40it/s]

 72%|███████▏  | 2338/3268 [16:11<06:27,  2.40it/s]

 72%|███████▏  | 2339/3268 [16:11<06:26,  2.40it/s]

 72%|███████▏  | 2340/3268 [16:12<06:26,  2.40it/s]

 72%|███████▏  | 2341/3268 [16:12<06:26,  2.40it/s]

 72%|███████▏  | 2342/3268 [16:13<06:25,  2.40it/s]

 72%|███████▏  | 2343/3268 [16:13<06:26,  2.39it/s]

 72%|███████▏  | 2344/3268 [16:13<06:25,  2.40it/s]

 72%|███████▏  | 2345/3268 [16:14<06:24,  2.40it/s]

 72%|███████▏  | 2346/3268 [16:14<06:24,  2.40it/s]

 72%|███████▏  | 2347/3268 [16:15<06:23,  2.40it/s]

 72%|███████▏  | 2348/3268 [16:15<06:23,  2.40it/s]

 72%|███████▏  | 2349/3268 [16:16<06:23,  2.40it/s]

 72%|███████▏  | 2350/3268 [16:16<06:22,  2.40it/s]

 72%|███████▏  | 2351/3268 [16:16<06:21,  2.40it/s]

 72%|███████▏  | 2352/3268 [16:17<06:21,  2.40it/s]

 72%|███████▏  | 2353/3268 [16:17<06:21,  2.40it/s]

 72%|███████▏  | 2354/3268 [16:18<06:20,  2.40it/s]

 72%|███████▏  | 2355/3268 [16:18<06:20,  2.40it/s]

 72%|███████▏  | 2356/3268 [16:18<06:20,  2.40it/s]

 72%|███████▏  | 2357/3268 [16:19<06:19,  2.40it/s]

 72%|███████▏  | 2358/3268 [16:19<06:18,  2.40it/s]

 72%|███████▏  | 2359/3268 [16:20<06:18,  2.40it/s]

 72%|███████▏  | 2360/3268 [16:20<06:17,  2.40it/s]

 72%|███████▏  | 2361/3268 [16:21<06:17,  2.40it/s]

 72%|███████▏  | 2362/3268 [16:21<06:16,  2.40it/s]

 72%|███████▏  | 2363/3268 [16:21<06:17,  2.40it/s]

 72%|███████▏  | 2364/3268 [16:22<06:16,  2.40it/s]

 72%|███████▏  | 2365/3268 [16:22<06:16,  2.40it/s]

 72%|███████▏  | 2366/3268 [16:23<06:15,  2.40it/s]

 72%|███████▏  | 2367/3268 [16:23<06:15,  2.40it/s]

 72%|███████▏  | 2368/3268 [16:23<06:14,  2.40it/s]

 72%|███████▏  | 2369/3268 [16:24<06:14,  2.40it/s]

 73%|███████▎  | 2370/3268 [16:24<06:13,  2.40it/s]

 73%|███████▎  | 2371/3268 [16:25<06:13,  2.40it/s]

 73%|███████▎  | 2372/3268 [16:25<06:12,  2.40it/s]

 73%|███████▎  | 2373/3268 [16:26<06:13,  2.40it/s]

 73%|███████▎  | 2374/3268 [16:26<06:12,  2.40it/s]

 73%|███████▎  | 2375/3268 [16:26<06:12,  2.40it/s]

 73%|███████▎  | 2376/3268 [16:27<06:11,  2.40it/s]

 73%|███████▎  | 2377/3268 [16:27<06:11,  2.40it/s]

 73%|███████▎  | 2378/3268 [16:28<06:10,  2.40it/s]

 73%|███████▎  | 2379/3268 [16:28<06:10,  2.40it/s]

 73%|███████▎  | 2380/3268 [16:28<06:09,  2.40it/s]

 73%|███████▎  | 2381/3268 [16:29<06:09,  2.40it/s]

 73%|███████▎  | 2382/3268 [16:29<06:09,  2.40it/s]

 73%|███████▎  | 2383/3268 [16:30<06:08,  2.40it/s]

 73%|███████▎  | 2384/3268 [16:30<06:09,  2.40it/s]

 73%|███████▎  | 2385/3268 [16:31<06:08,  2.40it/s]

 73%|███████▎  | 2386/3268 [16:31<06:08,  2.39it/s]

 73%|███████▎  | 2387/3268 [16:31<06:07,  2.40it/s]

 73%|███████▎  | 2388/3268 [16:32<06:06,  2.40it/s]

 73%|███████▎  | 2389/3268 [16:32<06:06,  2.40it/s]

 73%|███████▎  | 2390/3268 [16:33<06:06,  2.39it/s]

 73%|███████▎  | 2391/3268 [16:33<06:05,  2.40it/s]

 73%|███████▎  | 2392/3268 [16:33<06:05,  2.40it/s]

 73%|███████▎  | 2393/3268 [16:34<06:04,  2.40it/s]

 73%|███████▎  | 2394/3268 [16:34<06:04,  2.40it/s]

 73%|███████▎  | 2395/3268 [16:35<06:04,  2.39it/s]

 73%|███████▎  | 2396/3268 [16:35<06:04,  2.39it/s]

 73%|███████▎  | 2397/3268 [16:36<06:03,  2.39it/s]

 73%|███████▎  | 2398/3268 [16:36<06:03,  2.40it/s]

 73%|███████▎  | 2399/3268 [16:36<06:01,  2.40it/s]

 73%|███████▎  | 2400/3268 [16:37<06:01,  2.40it/s]

 73%|███████▎  | 2401/3268 [16:37<06:01,  2.40it/s]

 74%|███████▎  | 2402/3268 [16:38<06:01,  2.40it/s]

 74%|███████▎  | 2403/3268 [16:38<06:00,  2.40it/s]

 74%|███████▎  | 2404/3268 [16:38<06:01,  2.39it/s]

 74%|███████▎  | 2405/3268 [16:39<06:00,  2.39it/s]

 74%|███████▎  | 2406/3268 [16:39<06:00,  2.39it/s]

 74%|███████▎  | 2407/3268 [16:40<05:59,  2.39it/s]

 74%|███████▎  | 2408/3268 [16:40<05:59,  2.39it/s]

 74%|███████▎  | 2409/3268 [16:41<05:58,  2.40it/s]

 74%|███████▎  | 2410/3268 [16:41<05:57,  2.40it/s]

 74%|███████▍  | 2411/3268 [16:41<05:57,  2.40it/s]

 74%|███████▍  | 2412/3268 [16:42<05:57,  2.40it/s]

 74%|███████▍  | 2413/3268 [16:42<05:57,  2.39it/s]

 74%|███████▍  | 2414/3268 [16:43<05:57,  2.39it/s]

 74%|███████▍  | 2415/3268 [16:43<05:56,  2.39it/s]

 74%|███████▍  | 2416/3268 [16:43<05:56,  2.39it/s]

 74%|███████▍  | 2417/3268 [16:44<05:56,  2.39it/s]

 74%|███████▍  | 2418/3268 [16:44<05:55,  2.39it/s]

 74%|███████▍  | 2419/3268 [16:45<05:54,  2.40it/s]

 74%|███████▍  | 2420/3268 [16:45<05:53,  2.40it/s]

 74%|███████▍  | 2421/3268 [16:46<05:53,  2.40it/s]

 74%|███████▍  | 2422/3268 [16:46<05:53,  2.39it/s]

 74%|███████▍  | 2423/3268 [16:46<05:53,  2.39it/s]

 74%|███████▍  | 2424/3268 [16:47<05:53,  2.39it/s]

 74%|███████▍  | 2425/3268 [16:47<05:52,  2.39it/s]

 74%|███████▍  | 2426/3268 [16:48<05:52,  2.39it/s]

 74%|███████▍  | 2427/3268 [16:48<05:51,  2.39it/s]

 74%|███████▍  | 2428/3268 [16:48<05:51,  2.39it/s]

 74%|███████▍  | 2429/3268 [16:49<05:51,  2.39it/s]

 74%|███████▍  | 2430/3268 [16:49<05:51,  2.39it/s]

 74%|███████▍  | 2431/3268 [16:50<05:50,  2.39it/s]

 74%|███████▍  | 2432/3268 [16:50<05:48,  2.40it/s]

 74%|███████▍  | 2433/3268 [16:51<05:49,  2.39it/s]

 74%|███████▍  | 2434/3268 [16:51<05:48,  2.39it/s]

 75%|███████▍  | 2435/3268 [16:51<05:49,  2.38it/s]

 75%|███████▍  | 2436/3268 [16:52<05:48,  2.38it/s]

 75%|███████▍  | 2437/3268 [16:52<05:49,  2.37it/s]

 75%|███████▍  | 2438/3268 [16:53<05:48,  2.38it/s]

 75%|███████▍  | 2439/3268 [16:53<05:47,  2.38it/s]

 75%|███████▍  | 2440/3268 [16:54<05:47,  2.39it/s]

 75%|███████▍  | 2441/3268 [16:54<05:46,  2.39it/s]

 75%|███████▍  | 2442/3268 [16:54<05:45,  2.39it/s]

 75%|███████▍  | 2443/3268 [16:55<05:45,  2.39it/s]

 75%|███████▍  | 2444/3268 [16:55<05:45,  2.39it/s]

 75%|███████▍  | 2445/3268 [16:56<05:44,  2.39it/s]

 75%|███████▍  | 2446/3268 [16:56<05:43,  2.39it/s]

 75%|███████▍  | 2447/3268 [16:56<05:42,  2.40it/s]

 75%|███████▍  | 2448/3268 [16:57<05:42,  2.40it/s]

 75%|███████▍  | 2449/3268 [16:57<05:41,  2.40it/s]

 75%|███████▍  | 2450/3268 [16:58<05:41,  2.40it/s]

 75%|███████▌  | 2451/3268 [16:58<05:40,  2.40it/s]

 75%|███████▌  | 2452/3268 [16:59<05:40,  2.40it/s]

 75%|███████▌  | 2453/3268 [16:59<05:40,  2.39it/s]

 75%|███████▌  | 2454/3268 [16:59<05:39,  2.40it/s]

 75%|███████▌  | 2455/3268 [17:00<05:39,  2.39it/s]

 75%|███████▌  | 2456/3268 [17:00<05:39,  2.39it/s]

 75%|███████▌  | 2457/3268 [17:01<05:38,  2.39it/s]

 75%|███████▌  | 2458/3268 [17:01<05:38,  2.39it/s]

 75%|███████▌  | 2459/3268 [17:01<05:38,  2.39it/s]

 75%|███████▌  | 2460/3268 [17:02<05:37,  2.39it/s]

 75%|███████▌  | 2461/3268 [17:02<05:37,  2.39it/s]

 75%|███████▌  | 2462/3268 [17:03<05:36,  2.39it/s]

 75%|███████▌  | 2463/3268 [17:03<05:36,  2.39it/s]

 75%|███████▌  | 2464/3268 [17:04<05:35,  2.39it/s]

 75%|███████▌  | 2465/3268 [17:04<05:35,  2.39it/s]

 75%|███████▌  | 2466/3268 [17:04<05:34,  2.40it/s]

 75%|███████▌  | 2467/3268 [17:05<05:34,  2.39it/s]

 76%|███████▌  | 2468/3268 [17:05<05:34,  2.39it/s]

 76%|███████▌  | 2469/3268 [17:06<05:33,  2.39it/s]

 76%|███████▌  | 2470/3268 [17:06<05:33,  2.40it/s]

 76%|███████▌  | 2471/3268 [17:06<05:32,  2.40it/s]

 76%|███████▌  | 2472/3268 [17:07<05:32,  2.40it/s]

 76%|███████▌  | 2473/3268 [17:07<05:32,  2.39it/s]

 76%|███████▌  | 2474/3268 [17:08<05:31,  2.39it/s]

 76%|███████▌  | 2475/3268 [17:08<05:30,  2.40it/s]

 76%|███████▌  | 2476/3268 [17:09<05:30,  2.39it/s]

 76%|███████▌  | 2477/3268 [17:09<05:30,  2.39it/s]

 76%|███████▌  | 2478/3268 [17:09<05:29,  2.40it/s]

 76%|███████▌  | 2479/3268 [17:10<05:29,  2.39it/s]

 76%|███████▌  | 2480/3268 [17:10<05:29,  2.40it/s]

 76%|███████▌  | 2481/3268 [17:11<05:28,  2.39it/s]

 76%|███████▌  | 2482/3268 [17:11<05:28,  2.39it/s]

 76%|███████▌  | 2483/3268 [17:11<05:27,  2.39it/s]

 76%|███████▌  | 2484/3268 [17:12<05:27,  2.39it/s]

 76%|███████▌  | 2485/3268 [17:12<05:27,  2.39it/s]

 76%|███████▌  | 2486/3268 [17:13<05:27,  2.39it/s]

 76%|███████▌  | 2487/3268 [17:13<05:26,  2.39it/s]

 76%|███████▌  | 2488/3268 [17:14<05:26,  2.39it/s]

 76%|███████▌  | 2489/3268 [17:14<05:26,  2.38it/s]

 76%|███████▌  | 2490/3268 [17:14<05:25,  2.39it/s]

 76%|███████▌  | 2491/3268 [17:15<05:25,  2.39it/s]

 76%|███████▋  | 2492/3268 [17:15<05:24,  2.39it/s]

 76%|███████▋  | 2493/3268 [17:16<05:24,  2.39it/s]

 76%|███████▋  | 2494/3268 [17:16<05:24,  2.39it/s]

 76%|███████▋  | 2495/3268 [17:17<05:23,  2.39it/s]

 76%|███████▋  | 2496/3268 [17:17<05:23,  2.39it/s]

 76%|███████▋  | 2497/3268 [17:17<05:22,  2.39it/s]

 76%|███████▋  | 2498/3268 [17:18<05:22,  2.38it/s]

 76%|███████▋  | 2499/3268 [17:18<05:22,  2.39it/s]

 76%|███████▋  | 2500/3268 [17:19<05:21,  2.39it/s]

 77%|███████▋  | 2501/3268 [17:19<05:21,  2.39it/s]

 77%|███████▋  | 2502/3268 [17:19<05:20,  2.39it/s]

 77%|███████▋  | 2503/3268 [17:20<05:20,  2.39it/s]

logging
logging the anndata

 77%|███████▋  | 2504/3268 [17:20<05:28,  2.32it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 77%|███████▋  | 2505/3268 [17:21<05:24,  2.35it/s]

 77%|███████▋  | 2506/3268 [17:21<05:21,  2.37it/s]

 77%|███████▋  | 2507/3268 [17:22<05:18,  2.39it/s]

 77%|███████▋  | 2508/3268 [17:22<05:16,  2.40it/s]

 77%|███████▋  | 2509/3268 [17:22<05:14,  2.41it/s]

 77%|███████▋  | 2510/3268 [17:23<05:13,  2.42it/s]

 77%|███████▋  | 2511/3268 [17:23<05:12,  2.42it/s]

 77%|███████▋  | 2512/3268 [17:24<05:11,  2.43it/s]

 77%|███████▋  | 2513/3268 [17:24<05:10,  2.43it/s]

 77%|███████▋  | 2514/3268 [17:24<05:10,  2.43it/s]

 77%|███████▋  | 2515/3268 [17:25<05:09,  2.43it/s]

 77%|███████▋  | 2516/3268 [17:25<05:08,  2.44it/s]

 77%|███████▋  | 2517/3268 [17:26<05:08,  2.43it/s]

 77%|███████▋  | 2518/3268 [17:26<05:08,  2.44it/s]

 77%|███████▋  | 2519/3268 [17:26<05:07,  2.43it/s]

 77%|███████▋  | 2520/3268 [17:27<05:07,  2.43it/s]

 77%|███████▋  | 2521/3268 [17:27<05:06,  2.43it/s]

 77%|███████▋  | 2522/3268 [17:28<05:06,  2.43it/s]

 77%|███████▋  | 2523/3268 [17:28<05:06,  2.43it/s]

 77%|███████▋  | 2524/3268 [17:29<05:05,  2.43it/s]

 77%|███████▋  | 2525/3268 [17:29<05:05,  2.44it/s]

 77%|███████▋  | 2526/3268 [17:29<05:04,  2.43it/s]

 77%|███████▋  | 2527/3268 [17:30<05:04,  2.44it/s]

 77%|███████▋  | 2528/3268 [17:30<05:03,  2.43it/s]

 77%|███████▋  | 2529/3268 [17:31<05:04,  2.43it/s]

 77%|███████▋  | 2530/3268 [17:31<05:03,  2.43it/s]

 77%|███████▋  | 2531/3268 [17:31<05:03,  2.43it/s]

 77%|███████▋  | 2532/3268 [17:32<05:02,  2.43it/s]

 78%|███████▊  | 2533/3268 [17:32<05:03,  2.43it/s]

 78%|███████▊  | 2534/3268 [17:33<05:02,  2.43it/s]

 78%|███████▊  | 2535/3268 [17:33<05:02,  2.42it/s]

 78%|███████▊  | 2536/3268 [17:33<05:01,  2.43it/s]

 78%|███████▊  | 2537/3268 [17:34<05:01,  2.43it/s]

 78%|███████▊  | 2538/3268 [17:34<05:00,  2.43it/s]

 78%|███████▊  | 2539/3268 [17:35<05:00,  2.43it/s]

 78%|███████▊  | 2540/3268 [17:35<04:59,  2.43it/s]

 78%|███████▊  | 2541/3268 [17:36<04:59,  2.43it/s]

 78%|███████▊  | 2542/3268 [17:36<04:59,  2.43it/s]

 78%|███████▊  | 2543/3268 [17:36<04:58,  2.43it/s]

 78%|███████▊  | 2544/3268 [17:37<04:58,  2.43it/s]

 78%|███████▊  | 2545/3268 [17:37<04:58,  2.43it/s]

 78%|███████▊  | 2546/3268 [17:38<04:57,  2.42it/s]

 78%|███████▊  | 2547/3268 [17:38<04:56,  2.43it/s]

 78%|███████▊  | 2548/3268 [17:38<04:56,  2.43it/s]

 78%|███████▊  | 2549/3268 [17:39<04:56,  2.43it/s]

 78%|███████▊  | 2550/3268 [17:39<04:55,  2.43it/s]

 78%|███████▊  | 2551/3268 [17:40<04:54,  2.43it/s]

 78%|███████▊  | 2552/3268 [17:40<04:54,  2.43it/s]

 78%|███████▊  | 2553/3268 [17:40<04:54,  2.43it/s]

 78%|███████▊  | 2554/3268 [17:41<04:53,  2.43it/s]

 78%|███████▊  | 2555/3268 [17:41<04:53,  2.43it/s]

 78%|███████▊  | 2556/3268 [17:42<04:52,  2.43it/s]

 78%|███████▊  | 2557/3268 [17:42<04:52,  2.43it/s]

 78%|███████▊  | 2558/3268 [17:43<04:52,  2.43it/s]

 78%|███████▊  | 2559/3268 [17:43<04:51,  2.43it/s]

 78%|███████▊  | 2560/3268 [17:43<04:51,  2.43it/s]

 78%|███████▊  | 2561/3268 [17:44<04:50,  2.43it/s]

 78%|███████▊  | 2562/3268 [17:44<04:50,  2.43it/s]

 78%|███████▊  | 2563/3268 [17:45<04:50,  2.43it/s]

 78%|███████▊  | 2564/3268 [17:45<04:49,  2.43it/s]

 78%|███████▊  | 2565/3268 [17:45<04:49,  2.43it/s]

 79%|███████▊  | 2566/3268 [17:46<04:49,  2.43it/s]

 79%|███████▊  | 2567/3268 [17:46<04:48,  2.43it/s]

 79%|███████▊  | 2568/3268 [17:47<04:48,  2.43it/s]

 79%|███████▊  | 2569/3268 [17:47<04:47,  2.43it/s]

 79%|███████▊  | 2570/3268 [17:47<04:47,  2.43it/s]

 79%|███████▊  | 2571/3268 [17:48<04:46,  2.43it/s]

 79%|███████▊  | 2572/3268 [17:48<04:46,  2.43it/s]

 79%|███████▊  | 2573/3268 [17:49<04:46,  2.43it/s]

 79%|███████▉  | 2574/3268 [17:49<04:45,  2.43it/s]

 79%|███████▉  | 2575/3268 [17:50<04:45,  2.43it/s]

 79%|███████▉  | 2576/3268 [17:50<04:45,  2.43it/s]

 79%|███████▉  | 2577/3268 [17:50<04:44,  2.43it/s]

 79%|███████▉  | 2578/3268 [17:51<04:44,  2.43it/s]

 79%|███████▉  | 2579/3268 [17:51<04:43,  2.43it/s]

 79%|███████▉  | 2580/3268 [17:52<04:43,  2.43it/s]

 79%|███████▉  | 2581/3268 [17:52<04:42,  2.43it/s]

 79%|███████▉  | 2582/3268 [17:52<04:42,  2.43it/s]

 79%|███████▉  | 2583/3268 [17:53<04:41,  2.43it/s]

 79%|███████▉  | 2584/3268 [17:53<04:41,  2.43it/s]

 79%|███████▉  | 2585/3268 [17:54<04:41,  2.43it/s]

 79%|███████▉  | 2586/3268 [17:54<04:41,  2.42it/s]

 79%|███████▉  | 2587/3268 [17:54<04:41,  2.42it/s]

 79%|███████▉  | 2588/3268 [17:55<04:40,  2.42it/s]

 79%|███████▉  | 2589/3268 [17:55<04:40,  2.42it/s]

 79%|███████▉  | 2590/3268 [17:56<04:39,  2.42it/s]

 79%|███████▉  | 2591/3268 [17:56<04:39,  2.43it/s]

 79%|███████▉  | 2592/3268 [17:57<04:38,  2.43it/s]

 79%|███████▉  | 2593/3268 [17:57<04:37,  2.43it/s]

 79%|███████▉  | 2594/3268 [17:57<04:37,  2.43it/s]

 79%|███████▉  | 2595/3268 [17:58<04:37,  2.43it/s]

 79%|███████▉  | 2596/3268 [17:58<04:36,  2.43it/s]

 79%|███████▉  | 2597/3268 [17:59<04:36,  2.42it/s]

 79%|███████▉  | 2598/3268 [17:59<04:36,  2.43it/s]

 80%|███████▉  | 2599/3268 [17:59<04:35,  2.43it/s]

 80%|███████▉  | 2600/3268 [18:00<04:35,  2.43it/s]

 80%|███████▉  | 2601/3268 [18:00<04:35,  2.42it/s]

 80%|███████▉  | 2602/3268 [18:01<04:34,  2.43it/s]

 80%|███████▉  | 2603/3268 [18:01<04:34,  2.42it/s]

 80%|███████▉  | 2604/3268 [18:01<04:33,  2.43it/s]

 80%|███████▉  | 2605/3268 [18:02<04:33,  2.43it/s]

 80%|███████▉  | 2606/3268 [18:02<04:32,  2.43it/s]

 80%|███████▉  | 2607/3268 [18:03<04:33,  2.42it/s]

 80%|███████▉  | 2608/3268 [18:03<04:32,  2.42it/s]

 80%|███████▉  | 2609/3268 [18:04<04:31,  2.42it/s]

 80%|███████▉  | 2610/3268 [18:04<04:32,  2.42it/s]

 80%|███████▉  | 2611/3268 [18:04<04:31,  2.42it/s]

 80%|███████▉  | 2612/3268 [18:05<04:31,  2.42it/s]

 80%|███████▉  | 2613/3268 [18:05<04:30,  2.42it/s]

 80%|███████▉  | 2614/3268 [18:06<04:30,  2.42it/s]

 80%|████████  | 2615/3268 [18:06<04:29,  2.42it/s]

 80%|████████  | 2616/3268 [18:06<04:29,  2.42it/s]

 80%|████████  | 2617/3268 [18:07<04:28,  2.42it/s]

 80%|████████  | 2618/3268 [18:07<04:28,  2.42it/s]

 80%|████████  | 2619/3268 [18:08<04:27,  2.42it/s]

 80%|████████  | 2620/3268 [18:08<04:27,  2.42it/s]

 80%|████████  | 2621/3268 [18:09<04:27,  2.42it/s]

 80%|████████  | 2622/3268 [18:09<04:26,  2.42it/s]

 80%|████████  | 2623/3268 [18:09<04:26,  2.42it/s]

 80%|████████  | 2624/3268 [18:10<04:26,  2.42it/s]

 80%|████████  | 2625/3268 [18:10<04:25,  2.42it/s]

 80%|████████  | 2626/3268 [18:11<04:25,  2.42it/s]

 80%|████████  | 2627/3268 [18:11<04:25,  2.41it/s]

 80%|████████  | 2628/3268 [18:11<04:24,  2.42it/s]

 80%|████████  | 2629/3268 [18:12<04:24,  2.41it/s]

 80%|████████  | 2630/3268 [18:12<04:24,  2.42it/s]

 81%|████████  | 2631/3268 [18:13<04:23,  2.42it/s]

 81%|████████  | 2632/3268 [18:13<04:22,  2.42it/s]

 81%|████████  | 2633/3268 [18:13<04:22,  2.42it/s]

 81%|████████  | 2634/3268 [18:14<04:21,  2.42it/s]

 81%|████████  | 2635/3268 [18:14<04:21,  2.42it/s]

 81%|████████  | 2636/3268 [18:15<04:21,  2.42it/s]

 81%|████████  | 2637/3268 [18:15<04:21,  2.42it/s]

 81%|████████  | 2638/3268 [18:16<04:20,  2.42it/s]

 81%|████████  | 2639/3268 [18:16<04:19,  2.42it/s]

 81%|████████  | 2640/3268 [18:16<04:19,  2.42it/s]

 81%|████████  | 2641/3268 [18:17<04:18,  2.43it/s]

 81%|████████  | 2642/3268 [18:17<04:17,  2.43it/s]

 81%|████████  | 2643/3268 [18:18<04:17,  2.43it/s]

 81%|████████  | 2644/3268 [18:18<04:17,  2.42it/s]

 81%|████████  | 2645/3268 [18:18<04:17,  2.42it/s]

 81%|████████  | 2646/3268 [18:19<04:17,  2.42it/s]

 81%|████████  | 2647/3268 [18:19<04:16,  2.42it/s]

 81%|████████  | 2648/3268 [18:20<04:16,  2.42it/s]

 81%|████████  | 2649/3268 [18:20<04:15,  2.42it/s]

 81%|████████  | 2650/3268 [18:20<04:15,  2.42it/s]

 81%|████████  | 2651/3268 [18:21<04:15,  2.42it/s]

 81%|████████  | 2652/3268 [18:21<04:14,  2.42it/s]

 81%|████████  | 2653/3268 [18:22<04:14,  2.42it/s]

 81%|████████  | 2654/3268 [18:22<04:14,  2.42it/s]

 81%|████████  | 2655/3268 [18:23<04:13,  2.42it/s]

 81%|████████▏ | 2656/3268 [18:23<04:13,  2.42it/s]

 81%|████████▏ | 2657/3268 [18:23<04:12,  2.42it/s]

 81%|████████▏ | 2658/3268 [18:24<04:12,  2.42it/s]

 81%|████████▏ | 2659/3268 [18:24<04:12,  2.42it/s]

 81%|████████▏ | 2660/3268 [18:25<04:11,  2.42it/s]

 81%|████████▏ | 2661/3268 [18:25<04:10,  2.42it/s]

 81%|████████▏ | 2662/3268 [18:25<04:10,  2.42it/s]

 81%|████████▏ | 2663/3268 [18:26<04:09,  2.42it/s]

 82%|████████▏ | 2664/3268 [18:26<04:09,  2.42it/s]

 82%|████████▏ | 2665/3268 [18:27<04:09,  2.42it/s]

 82%|████████▏ | 2666/3268 [18:27<04:08,  2.42it/s]

 82%|████████▏ | 2667/3268 [18:28<04:08,  2.42it/s]

 82%|████████▏ | 2668/3268 [18:28<04:07,  2.42it/s]

 82%|████████▏ | 2669/3268 [18:28<04:07,  2.42it/s]

 82%|████████▏ | 2670/3268 [18:29<04:06,  2.42it/s]

 82%|████████▏ | 2671/3268 [18:29<04:06,  2.42it/s]

 82%|████████▏ | 2672/3268 [18:30<04:06,  2.42it/s]

 82%|████████▏ | 2673/3268 [18:30<04:05,  2.42it/s]

 82%|████████▏ | 2674/3268 [18:30<04:05,  2.42it/s]

 82%|████████▏ | 2675/3268 [18:31<04:04,  2.42it/s]

 82%|████████▏ | 2676/3268 [18:31<04:04,  2.42it/s]

 82%|████████▏ | 2677/3268 [18:32<04:04,  2.42it/s]

 82%|████████▏ | 2678/3268 [18:32<04:03,  2.42it/s]

 82%|████████▏ | 2679/3268 [18:32<04:03,  2.42it/s]

 82%|████████▏ | 2680/3268 [18:33<04:03,  2.42it/s]

 82%|████████▏ | 2681/3268 [18:33<04:02,  2.42it/s]

 82%|████████▏ | 2682/3268 [18:34<04:02,  2.42it/s]

 82%|████████▏ | 2683/3268 [18:34<04:01,  2.42it/s]

 82%|████████▏ | 2684/3268 [18:35<04:01,  2.42it/s]

 82%|████████▏ | 2685/3268 [18:35<04:01,  2.42it/s]

 82%|████████▏ | 2686/3268 [18:35<04:00,  2.42it/s]

 82%|████████▏ | 2687/3268 [18:36<04:00,  2.41it/s]

 82%|████████▏ | 2688/3268 [18:36<04:00,  2.41it/s]

 82%|████████▏ | 2689/3268 [18:37<03:59,  2.41it/s]

 82%|████████▏ | 2690/3268 [18:37<03:59,  2.41it/s]

 82%|████████▏ | 2691/3268 [18:37<03:58,  2.42it/s]

 82%|████████▏ | 2692/3268 [18:38<03:58,  2.42it/s]

 82%|████████▏ | 2693/3268 [18:38<03:57,  2.42it/s]

 82%|████████▏ | 2694/3268 [18:39<03:57,  2.42it/s]

 82%|████████▏ | 2695/3268 [18:39<03:57,  2.42it/s]

 82%|████████▏ | 2696/3268 [18:40<03:56,  2.42it/s]

 83%|████████▎ | 2697/3268 [18:40<03:56,  2.41it/s]

 83%|████████▎ | 2698/3268 [18:40<03:55,  2.42it/s]

 83%|████████▎ | 2699/3268 [18:41<03:55,  2.42it/s]

 83%|████████▎ | 2700/3268 [18:41<03:54,  2.42it/s]

 83%|████████▎ | 2701/3268 [18:42<03:54,  2.42it/s]

 83%|████████▎ | 2702/3268 [18:42<03:53,  2.42it/s]

 83%|████████▎ | 2703/3268 [18:42<03:53,  2.42it/s]

 83%|████████▎ | 2704/3268 [18:43<03:53,  2.42it/s]

 83%|████████▎ | 2705/3268 [18:43<03:52,  2.42it/s]

 83%|████████▎ | 2706/3268 [18:44<03:52,  2.42it/s]

 83%|████████▎ | 2707/3268 [18:44<03:52,  2.42it/s]

 83%|████████▎ | 2708/3268 [18:44<03:51,  2.42it/s]

 83%|████████▎ | 2709/3268 [18:45<03:51,  2.42it/s]

 83%|████████▎ | 2710/3268 [18:45<03:50,  2.42it/s]

 83%|████████▎ | 2711/3268 [18:46<03:50,  2.42it/s]

 83%|████████▎ | 2712/3268 [18:46<03:50,  2.42it/s]

 83%|████████▎ | 2713/3268 [18:47<03:49,  2.42it/s]

 83%|████████▎ | 2714/3268 [18:47<03:49,  2.42it/s]

 83%|████████▎ | 2715/3268 [18:47<03:48,  2.42it/s]

 83%|████████▎ | 2716/3268 [18:48<03:48,  2.42it/s]

 83%|████████▎ | 2717/3268 [18:48<03:47,  2.42it/s]

 83%|████████▎ | 2718/3268 [18:49<03:47,  2.42it/s]

 83%|████████▎ | 2719/3268 [18:49<03:46,  2.42it/s]

 83%|████████▎ | 2720/3268 [18:49<03:46,  2.42it/s]

 83%|████████▎ | 2721/3268 [18:50<03:46,  2.42it/s]

 83%|████████▎ | 2722/3268 [18:50<03:45,  2.42it/s]

 83%|████████▎ | 2723/3268 [18:51<03:45,  2.42it/s]

 83%|████████▎ | 2724/3268 [18:51<03:44,  2.42it/s]

 83%|████████▎ | 2725/3268 [18:52<03:44,  2.42it/s]

 83%|████████▎ | 2726/3268 [18:52<03:44,  2.42it/s]

 83%|████████▎ | 2727/3268 [18:52<03:43,  2.42it/s]

 83%|████████▎ | 2728/3268 [18:53<03:43,  2.42it/s]

 84%|████████▎ | 2729/3268 [18:53<03:43,  2.42it/s]

 84%|████████▎ | 2730/3268 [18:54<03:42,  2.42it/s]

 84%|████████▎ | 2731/3268 [18:54<03:42,  2.41it/s]

 84%|████████▎ | 2732/3268 [18:54<03:42,  2.41it/s]

 84%|████████▎ | 2733/3268 [18:55<03:41,  2.41it/s]

 84%|████████▎ | 2734/3268 [18:55<03:41,  2.42it/s]

 84%|████████▎ | 2735/3268 [18:56<03:40,  2.42it/s]

 84%|████████▎ | 2736/3268 [18:56<03:40,  2.42it/s]

 84%|████████▍ | 2737/3268 [18:56<03:39,  2.42it/s]

 84%|████████▍ | 2738/3268 [18:57<03:39,  2.41it/s]

 84%|████████▍ | 2739/3268 [18:57<03:39,  2.41it/s]

 84%|████████▍ | 2740/3268 [18:58<03:38,  2.41it/s]

 84%|████████▍ | 2741/3268 [18:58<03:38,  2.41it/s]

 84%|████████▍ | 2742/3268 [18:59<03:38,  2.41it/s]

 84%|████████▍ | 2743/3268 [18:59<03:37,  2.41it/s]

 84%|████████▍ | 2744/3268 [18:59<03:37,  2.41it/s]

 84%|████████▍ | 2745/3268 [19:00<03:37,  2.41it/s]

 84%|████████▍ | 2746/3268 [19:00<03:36,  2.41it/s]

 84%|████████▍ | 2747/3268 [19:01<03:36,  2.41it/s]

 84%|████████▍ | 2748/3268 [19:01<03:35,  2.41it/s]

 84%|████████▍ | 2749/3268 [19:01<03:35,  2.41it/s]

 84%|████████▍ | 2750/3268 [19:02<03:34,  2.41it/s]

 84%|████████▍ | 2751/3268 [19:02<03:34,  2.41it/s]

 84%|████████▍ | 2752/3268 [19:03<03:33,  2.41it/s]

 84%|████████▍ | 2753/3268 [19:03<03:33,  2.41it/s]

 84%|████████▍ | 2754/3268 [19:04<03:33,  2.41it/s]

 84%|████████▍ | 2755/3268 [19:04<03:33,  2.41it/s]

 84%|████████▍ | 2756/3268 [19:04<03:32,  2.41it/s]

 84%|████████▍ | 2757/3268 [19:05<03:32,  2.41it/s]

 84%|████████▍ | 2758/3268 [19:05<03:31,  2.41it/s]

 84%|████████▍ | 2759/3268 [19:06<03:31,  2.41it/s]

 84%|████████▍ | 2760/3268 [19:06<03:30,  2.41it/s]

 84%|████████▍ | 2761/3268 [19:06<03:30,  2.41it/s]

 85%|████████▍ | 2762/3268 [19:07<03:30,  2.41it/s]

 85%|████████▍ | 2763/3268 [19:07<03:29,  2.41it/s]

 85%|████████▍ | 2764/3268 [19:08<03:28,  2.41it/s]

 85%|████████▍ | 2765/3268 [19:08<03:28,  2.41it/s]

 85%|████████▍ | 2766/3268 [19:08<03:28,  2.41it/s]

 85%|████████▍ | 2767/3268 [19:09<03:27,  2.41it/s]

 85%|████████▍ | 2768/3268 [19:09<03:27,  2.41it/s]

 85%|████████▍ | 2769/3268 [19:10<03:27,  2.41it/s]

 85%|████████▍ | 2770/3268 [19:10<03:26,  2.41it/s]

 85%|████████▍ | 2771/3268 [19:11<03:26,  2.41it/s]

 85%|████████▍ | 2772/3268 [19:11<03:25,  2.41it/s]

 85%|████████▍ | 2773/3268 [19:11<03:25,  2.41it/s]

 85%|████████▍ | 2774/3268 [19:12<03:24,  2.41it/s]

 85%|████████▍ | 2775/3268 [19:12<03:24,  2.41it/s]

 85%|████████▍ | 2776/3268 [19:13<03:23,  2.41it/s]

 85%|████████▍ | 2777/3268 [19:13<03:23,  2.41it/s]

 85%|████████▌ | 2778/3268 [19:13<03:23,  2.41it/s]

 85%|████████▌ | 2779/3268 [19:14<03:22,  2.41it/s]

 85%|████████▌ | 2780/3268 [19:14<03:22,  2.41it/s]

 85%|████████▌ | 2781/3268 [19:15<03:21,  2.41it/s]

 85%|████████▌ | 2782/3268 [19:15<03:21,  2.41it/s]

 85%|████████▌ | 2783/3268 [19:16<03:20,  2.41it/s]

 85%|████████▌ | 2784/3268 [19:16<03:20,  2.41it/s]

 85%|████████▌ | 2785/3268 [19:16<03:20,  2.41it/s]

 85%|████████▌ | 2786/3268 [19:17<03:19,  2.41it/s]

 85%|████████▌ | 2787/3268 [19:17<03:19,  2.41it/s]

 85%|████████▌ | 2788/3268 [19:18<03:18,  2.41it/s]

 85%|████████▌ | 2789/3268 [19:18<03:18,  2.41it/s]

 85%|████████▌ | 2790/3268 [19:18<03:18,  2.41it/s]

 85%|████████▌ | 2791/3268 [19:19<03:17,  2.41it/s]

 85%|████████▌ | 2792/3268 [19:19<03:17,  2.41it/s]

 85%|████████▌ | 2793/3268 [19:20<03:17,  2.40it/s]

 85%|████████▌ | 2794/3268 [19:20<03:16,  2.41it/s]

 86%|████████▌ | 2795/3268 [19:21<03:16,  2.41it/s]

 86%|████████▌ | 2796/3268 [19:21<03:15,  2.41it/s]

 86%|████████▌ | 2797/3268 [19:21<03:15,  2.41it/s]

 86%|████████▌ | 2798/3268 [19:22<03:14,  2.41it/s]

 86%|████████▌ | 2799/3268 [19:22<03:14,  2.41it/s]

 86%|████████▌ | 2800/3268 [19:23<03:14,  2.41it/s]

 86%|████████▌ | 2801/3268 [19:23<03:13,  2.41it/s]

 86%|████████▌ | 2802/3268 [19:23<03:13,  2.41it/s]

 86%|████████▌ | 2803/3268 [19:24<03:12,  2.41it/s]

 86%|████████▌ | 2804/3268 [19:24<03:12,  2.41it/s]

 86%|████████▌ | 2805/3268 [19:25<03:12,  2.41it/s]

 86%|████████▌ | 2806/3268 [19:25<03:11,  2.41it/s]

 86%|████████▌ | 2807/3268 [19:26<03:11,  2.41it/s]

 86%|████████▌ | 2808/3268 [19:26<03:11,  2.41it/s]

 86%|████████▌ | 2809/3268 [19:26<03:10,  2.41it/s]

 86%|████████▌ | 2810/3268 [19:27<03:10,  2.41it/s]

 86%|████████▌ | 2811/3268 [19:27<03:09,  2.41it/s]

 86%|████████▌ | 2812/3268 [19:28<03:09,  2.41it/s]

 86%|████████▌ | 2813/3268 [19:28<03:09,  2.41it/s]

 86%|████████▌ | 2814/3268 [19:28<03:08,  2.41it/s]

 86%|████████▌ | 2815/3268 [19:29<03:08,  2.41it/s]

 86%|████████▌ | 2816/3268 [19:29<03:07,  2.41it/s]

 86%|████████▌ | 2817/3268 [19:30<03:07,  2.41it/s]

 86%|████████▌ | 2818/3268 [19:30<03:06,  2.41it/s]

 86%|████████▋ | 2819/3268 [19:30<03:06,  2.41it/s]

 86%|████████▋ | 2820/3268 [19:31<03:05,  2.41it/s]

 86%|████████▋ | 2821/3268 [19:31<03:05,  2.41it/s]

 86%|████████▋ | 2822/3268 [19:32<03:05,  2.41it/s]

 86%|████████▋ | 2823/3268 [19:32<03:04,  2.41it/s]

 86%|████████▋ | 2824/3268 [19:33<03:04,  2.41it/s]

 86%|████████▋ | 2825/3268 [19:33<03:04,  2.41it/s]

 86%|████████▋ | 2826/3268 [19:33<03:03,  2.41it/s]

 87%|████████▋ | 2827/3268 [19:34<03:03,  2.40it/s]

 87%|████████▋ | 2828/3268 [19:34<03:02,  2.41it/s]

 87%|████████▋ | 2829/3268 [19:35<03:02,  2.41it/s]

 87%|████████▋ | 2830/3268 [19:35<03:02,  2.40it/s]

 87%|████████▋ | 2831/3268 [19:35<03:01,  2.41it/s]

 87%|████████▋ | 2832/3268 [19:36<03:01,  2.41it/s]

 87%|████████▋ | 2833/3268 [19:36<03:00,  2.41it/s]

 87%|████████▋ | 2834/3268 [19:37<03:00,  2.41it/s]

 87%|████████▋ | 2835/3268 [19:37<03:00,  2.40it/s]

 87%|████████▋ | 2836/3268 [19:38<02:59,  2.40it/s]

 87%|████████▋ | 2837/3268 [19:38<02:59,  2.40it/s]

 87%|████████▋ | 2838/3268 [19:38<02:59,  2.40it/s]

 87%|████████▋ | 2839/3268 [19:39<02:58,  2.40it/s]

 87%|████████▋ | 2840/3268 [19:39<02:58,  2.39it/s]

 87%|████████▋ | 2841/3268 [19:40<02:58,  2.40it/s]

 87%|████████▋ | 2842/3268 [19:40<02:57,  2.40it/s]

 87%|████████▋ | 2843/3268 [19:40<02:56,  2.40it/s]

 87%|████████▋ | 2844/3268 [19:41<02:56,  2.40it/s]

 87%|████████▋ | 2845/3268 [19:41<02:55,  2.41it/s]

 87%|████████▋ | 2846/3268 [19:42<02:55,  2.40it/s]

 87%|████████▋ | 2847/3268 [19:42<02:54,  2.41it/s]

 87%|████████▋ | 2848/3268 [19:43<02:54,  2.41it/s]

 87%|████████▋ | 2849/3268 [19:43<02:54,  2.40it/s]

 87%|████████▋ | 2850/3268 [19:43<02:53,  2.40it/s]

 87%|████████▋ | 2851/3268 [19:44<02:53,  2.40it/s]

 87%|████████▋ | 2852/3268 [19:44<02:53,  2.40it/s]

 87%|████████▋ | 2853/3268 [19:45<02:52,  2.40it/s]

 87%|████████▋ | 2854/3268 [19:45<02:52,  2.41it/s]

 87%|████████▋ | 2855/3268 [19:45<02:51,  2.40it/s]

 87%|████████▋ | 2856/3268 [19:46<02:51,  2.40it/s]

 87%|████████▋ | 2857/3268 [19:46<02:51,  2.40it/s]

 87%|████████▋ | 2858/3268 [19:47<02:50,  2.40it/s]

 87%|████████▋ | 2859/3268 [19:47<02:50,  2.40it/s]

 88%|████████▊ | 2860/3268 [19:48<02:49,  2.40it/s]

 88%|████████▊ | 2861/3268 [19:48<02:49,  2.40it/s]

 88%|████████▊ | 2862/3268 [19:48<02:48,  2.40it/s]

 88%|████████▊ | 2863/3268 [19:49<02:48,  2.40it/s]

 88%|████████▊ | 2864/3268 [19:49<02:48,  2.40it/s]

 88%|████████▊ | 2865/3268 [19:50<02:47,  2.40it/s]

 88%|████████▊ | 2866/3268 [19:50<02:47,  2.40it/s]

 88%|████████▊ | 2867/3268 [19:50<02:46,  2.40it/s]

 88%|████████▊ | 2868/3268 [19:51<02:46,  2.41it/s]

 88%|████████▊ | 2869/3268 [19:51<02:45,  2.41it/s]

 88%|████████▊ | 2870/3268 [19:52<02:45,  2.41it/s]

 88%|████████▊ | 2871/3268 [19:52<02:45,  2.40it/s]

 88%|████████▊ | 2872/3268 [19:53<02:44,  2.40it/s]

 88%|████████▊ | 2873/3268 [19:53<02:44,  2.40it/s]

 88%|████████▊ | 2874/3268 [19:53<02:43,  2.41it/s]

 88%|████████▊ | 2875/3268 [19:54<02:43,  2.40it/s]

 88%|████████▊ | 2876/3268 [19:54<02:43,  2.40it/s]

 88%|████████▊ | 2877/3268 [19:55<02:42,  2.40it/s]

 88%|████████▊ | 2878/3268 [19:55<02:42,  2.41it/s]

 88%|████████▊ | 2879/3268 [19:55<02:41,  2.40it/s]

 88%|████████▊ | 2880/3268 [19:56<02:41,  2.40it/s]

 88%|████████▊ | 2881/3268 [19:56<02:41,  2.40it/s]

 88%|████████▊ | 2882/3268 [19:57<02:40,  2.40it/s]

 88%|████████▊ | 2883/3268 [19:57<02:40,  2.41it/s]

 88%|████████▊ | 2884/3268 [19:58<02:40,  2.39it/s]

 88%|████████▊ | 2885/3268 [19:58<02:40,  2.39it/s]

 88%|████████▊ | 2886/3268 [19:58<02:39,  2.39it/s]

 88%|████████▊ | 2887/3268 [19:59<02:39,  2.39it/s]

 88%|████████▊ | 2888/3268 [19:59<02:38,  2.40it/s]

 88%|████████▊ | 2889/3268 [20:00<02:37,  2.40it/s]

 88%|████████▊ | 2890/3268 [20:00<02:37,  2.40it/s]

 88%|████████▊ | 2891/3268 [20:00<02:36,  2.40it/s]

 88%|████████▊ | 2892/3268 [20:01<02:36,  2.40it/s]

 89%|████████▊ | 2893/3268 [20:01<02:35,  2.41it/s]

 89%|████████▊ | 2894/3268 [20:02<02:35,  2.41it/s]

 89%|████████▊ | 2895/3268 [20:02<02:34,  2.41it/s]

 89%|████████▊ | 2896/3268 [20:03<02:34,  2.41it/s]

 89%|████████▊ | 2897/3268 [20:03<02:34,  2.41it/s]

 89%|████████▊ | 2898/3268 [20:03<02:33,  2.41it/s]

 89%|████████▊ | 2899/3268 [20:04<02:33,  2.41it/s]

 89%|████████▊ | 2900/3268 [20:04<02:32,  2.41it/s]

 89%|████████▉ | 2901/3268 [20:05<02:32,  2.41it/s]

 89%|████████▉ | 2902/3268 [20:05<02:31,  2.41it/s]

 89%|████████▉ | 2903/3268 [20:05<02:31,  2.41it/s]

 89%|████████▉ | 2904/3268 [20:06<02:31,  2.41it/s]

 89%|████████▉ | 2905/3268 [20:06<02:30,  2.41it/s]

 89%|████████▉ | 2906/3268 [20:07<02:30,  2.41it/s]

 89%|████████▉ | 2907/3268 [20:07<02:29,  2.41it/s]

 89%|████████▉ | 2908/3268 [20:08<02:29,  2.41it/s]

 89%|████████▉ | 2909/3268 [20:08<02:29,  2.40it/s]

 89%|████████▉ | 2910/3268 [20:08<02:29,  2.40it/s]

 89%|████████▉ | 2911/3268 [20:09<02:28,  2.40it/s]

 89%|████████▉ | 2912/3268 [20:09<02:28,  2.40it/s]

 89%|████████▉ | 2913/3268 [20:10<02:27,  2.40it/s]

 89%|████████▉ | 2914/3268 [20:10<02:27,  2.41it/s]

 89%|████████▉ | 2915/3268 [20:10<02:26,  2.41it/s]

 89%|████████▉ | 2916/3268 [20:11<02:26,  2.41it/s]

 89%|████████▉ | 2917/3268 [20:11<02:26,  2.40it/s]

 89%|████████▉ | 2918/3268 [20:12<02:25,  2.40it/s]

 89%|████████▉ | 2919/3268 [20:12<02:25,  2.40it/s]

 89%|████████▉ | 2920/3268 [20:13<02:24,  2.40it/s]

 89%|████████▉ | 2921/3268 [20:13<02:24,  2.40it/s]

 89%|████████▉ | 2922/3268 [20:13<02:24,  2.40it/s]

 89%|████████▉ | 2923/3268 [20:14<02:24,  2.39it/s]

 89%|████████▉ | 2924/3268 [20:14<02:23,  2.40it/s]

 90%|████████▉ | 2925/3268 [20:15<02:22,  2.40it/s]

 90%|████████▉ | 2926/3268 [20:15<02:22,  2.40it/s]

 90%|████████▉ | 2927/3268 [20:15<02:22,  2.40it/s]

 90%|████████▉ | 2928/3268 [20:16<02:21,  2.40it/s]

 90%|████████▉ | 2929/3268 [20:16<02:21,  2.40it/s]

 90%|████████▉ | 2930/3268 [20:17<02:20,  2.40it/s]

 90%|████████▉ | 2931/3268 [20:17<02:20,  2.40it/s]

 90%|████████▉ | 2932/3268 [20:18<02:19,  2.40it/s]

 90%|████████▉ | 2933/3268 [20:18<02:19,  2.40it/s]

 90%|████████▉ | 2934/3268 [20:18<02:18,  2.41it/s]

 90%|████████▉ | 2935/3268 [20:19<02:18,  2.41it/s]

 90%|████████▉ | 2936/3268 [20:19<02:18,  2.40it/s]

 90%|████████▉ | 2937/3268 [20:20<02:17,  2.40it/s]

 90%|████████▉ | 2938/3268 [20:20<02:17,  2.40it/s]

 90%|████████▉ | 2939/3268 [20:20<02:16,  2.40it/s]

 90%|████████▉ | 2940/3268 [20:21<02:16,  2.39it/s]

 90%|████████▉ | 2941/3268 [20:21<02:16,  2.40it/s]

 90%|█████████ | 2942/3268 [20:22<02:16,  2.39it/s]

 90%|█████████ | 2943/3268 [20:22<02:15,  2.40it/s]

 90%|█████████ | 2944/3268 [20:23<02:15,  2.39it/s]

 90%|█████████ | 2945/3268 [20:23<02:14,  2.40it/s]

 90%|█████████ | 2946/3268 [20:23<02:14,  2.40it/s]

 90%|█████████ | 2947/3268 [20:24<02:13,  2.40it/s]

 90%|█████████ | 2948/3268 [20:24<02:13,  2.40it/s]

 90%|█████████ | 2949/3268 [20:25<02:13,  2.40it/s]

 90%|█████████ | 2950/3268 [20:25<02:12,  2.40it/s]

 90%|█████████ | 2951/3268 [20:25<02:12,  2.40it/s]

 90%|█████████ | 2952/3268 [20:26<02:11,  2.40it/s]

 90%|█████████ | 2953/3268 [20:26<02:11,  2.40it/s]

 90%|█████████ | 2954/3268 [20:27<02:10,  2.40it/s]

 90%|█████████ | 2955/3268 [20:27<02:10,  2.40it/s]

 90%|█████████ | 2956/3268 [20:28<02:10,  2.40it/s]

 90%|█████████ | 2957/3268 [20:28<02:09,  2.40it/s]

 91%|█████████ | 2958/3268 [20:28<02:09,  2.40it/s]

 91%|█████████ | 2959/3268 [20:29<02:08,  2.40it/s]

 91%|█████████ | 2960/3268 [20:29<02:08,  2.40it/s]

 91%|█████████ | 2961/3268 [20:30<02:07,  2.40it/s]

 91%|█████████ | 2962/3268 [20:30<02:07,  2.40it/s]

 91%|█████████ | 2963/3268 [20:30<02:07,  2.40it/s]

 91%|█████████ | 2964/3268 [20:31<02:06,  2.40it/s]

 91%|█████████ | 2965/3268 [20:31<02:06,  2.40it/s]

 91%|█████████ | 2966/3268 [20:32<02:05,  2.40it/s]

 91%|█████████ | 2967/3268 [20:32<02:05,  2.40it/s]

 91%|█████████ | 2968/3268 [20:32<02:04,  2.40it/s]

 91%|█████████ | 2969/3268 [20:33<02:04,  2.40it/s]

 91%|█████████ | 2970/3268 [20:33<02:04,  2.40it/s]

 91%|█████████ | 2971/3268 [20:34<02:03,  2.40it/s]

 91%|█████████ | 2972/3268 [20:34<02:03,  2.40it/s]

 91%|█████████ | 2973/3268 [20:35<02:03,  2.40it/s]

 91%|█████████ | 2974/3268 [20:35<02:02,  2.40it/s]

 91%|█████████ | 2975/3268 [20:35<02:02,  2.40it/s]

 91%|█████████ | 2976/3268 [20:36<02:01,  2.40it/s]

 91%|█████████ | 2977/3268 [20:36<02:01,  2.40it/s]

 91%|█████████ | 2978/3268 [20:37<02:01,  2.40it/s]

 91%|█████████ | 2979/3268 [20:37<02:00,  2.39it/s]

 91%|█████████ | 2980/3268 [20:38<02:00,  2.39it/s]

 91%|█████████ | 2981/3268 [20:38<01:59,  2.39it/s]

 91%|█████████ | 2982/3268 [20:38<01:59,  2.40it/s]

 91%|█████████▏| 2983/3268 [20:39<01:58,  2.40it/s]

 91%|█████████▏| 2984/3268 [20:39<01:58,  2.40it/s]

 91%|█████████▏| 2985/3268 [20:40<01:58,  2.40it/s]

 91%|█████████▏| 2986/3268 [20:40<01:57,  2.39it/s]

 91%|█████████▏| 2987/3268 [20:40<01:57,  2.40it/s]

 91%|█████████▏| 2988/3268 [20:41<01:56,  2.40it/s]

 91%|█████████▏| 2989/3268 [20:41<01:56,  2.40it/s]

 91%|█████████▏| 2990/3268 [20:42<01:55,  2.40it/s]

 92%|█████████▏| 2991/3268 [20:42<01:55,  2.40it/s]

 92%|█████████▏| 2992/3268 [20:43<01:55,  2.40it/s]

 92%|█████████▏| 2993/3268 [20:43<01:54,  2.40it/s]

 92%|█████████▏| 2994/3268 [20:43<01:54,  2.40it/s]

 92%|█████████▏| 2995/3268 [20:44<01:53,  2.40it/s]

 92%|█████████▏| 2996/3268 [20:44<01:53,  2.40it/s]

 92%|█████████▏| 2997/3268 [20:45<01:52,  2.40it/s]

 92%|█████████▏| 2998/3268 [20:45<01:52,  2.40it/s]

 92%|█████████▏| 2999/3268 [20:45<01:52,  2.40it/s]

 92%|█████████▏| 3000/3268 [20:46<01:51,  2.40it/s]

 92%|█████████▏| 3001/3268 [20:46<01:51,  2.40it/s]

 92%|█████████▏| 3002/3268 [20:47<01:50,  2.40it/s]

 92%|█████████▏| 3003/3268 [20:47<01:50,  2.40it/s]

 92%|█████████▏| 3004/3268 [20:48<01:49,  2.40it/s]

 92%|█████████▏| 3005/3268 [20:48<01:49,  2.40it/s]

 92%|█████████▏| 3006/3268 [20:48<01:49,  2.40it/s]

 92%|█████████▏| 3007/3268 [20:49<01:49,  2.39it/s]

 92%|█████████▏| 3008/3268 [20:49<01:48,  2.40it/s]

 92%|█████████▏| 3009/3268 [20:50<01:48,  2.40it/s]

 92%|█████████▏| 3010/3268 [20:50<01:47,  2.40it/s]

 92%|█████████▏| 3011/3268 [20:50<01:47,  2.40it/s]

 92%|█████████▏| 3012/3268 [20:51<01:46,  2.40it/s]

 92%|█████████▏| 3013/3268 [20:51<01:46,  2.39it/s]

 92%|█████████▏| 3014/3268 [20:52<01:46,  2.39it/s]

 92%|█████████▏| 3015/3268 [20:52<01:45,  2.39it/s]

 92%|█████████▏| 3016/3268 [20:53<01:45,  2.40it/s]

 92%|█████████▏| 3017/3268 [20:53<01:44,  2.40it/s]

 92%|█████████▏| 3018/3268 [20:53<01:44,  2.40it/s]

 92%|█████████▏| 3019/3268 [20:54<01:44,  2.39it/s]

 92%|█████████▏| 3020/3268 [20:54<01:43,  2.40it/s]

 92%|█████████▏| 3021/3268 [20:55<01:43,  2.39it/s]

 92%|█████████▏| 3022/3268 [20:55<01:42,  2.39it/s]

 93%|█████████▎| 3023/3268 [20:55<01:42,  2.39it/s]

 93%|█████████▎| 3024/3268 [20:56<01:41,  2.39it/s]

 93%|█████████▎| 3025/3268 [20:56<01:41,  2.39it/s]

 93%|█████████▎| 3026/3268 [20:57<01:40,  2.40it/s]

 93%|█████████▎| 3027/3268 [20:57<01:40,  2.40it/s]

 93%|█████████▎| 3028/3268 [20:58<01:40,  2.40it/s]

 93%|█████████▎| 3029/3268 [20:58<01:39,  2.40it/s]

 93%|█████████▎| 3030/3268 [20:58<01:39,  2.40it/s]

 93%|█████████▎| 3031/3268 [20:59<01:38,  2.39it/s]

 93%|█████████▎| 3032/3268 [20:59<01:38,  2.40it/s]

 93%|█████████▎| 3033/3268 [21:00<01:38,  2.40it/s]

 93%|█████████▎| 3034/3268 [21:00<01:37,  2.39it/s]

 93%|█████████▎| 3035/3268 [21:00<01:37,  2.39it/s]

 93%|█████████▎| 3036/3268 [21:01<01:36,  2.40it/s]

 93%|█████████▎| 3037/3268 [21:01<01:36,  2.39it/s]

 93%|█████████▎| 3038/3268 [21:02<01:36,  2.39it/s]

 93%|█████████▎| 3039/3268 [21:02<01:35,  2.39it/s]

 93%|█████████▎| 3040/3268 [21:03<01:35,  2.39it/s]

 93%|█████████▎| 3041/3268 [21:03<01:35,  2.39it/s]

 93%|█████████▎| 3042/3268 [21:03<01:34,  2.39it/s]

 93%|█████████▎| 3043/3268 [21:04<01:34,  2.39it/s]

 93%|█████████▎| 3044/3268 [21:04<01:33,  2.39it/s]

 93%|█████████▎| 3045/3268 [21:05<01:33,  2.39it/s]

 93%|█████████▎| 3046/3268 [21:05<01:32,  2.39it/s]

 93%|█████████▎| 3047/3268 [21:05<01:32,  2.39it/s]

 93%|█████████▎| 3048/3268 [21:06<01:31,  2.39it/s]

 93%|█████████▎| 3049/3268 [21:06<01:31,  2.39it/s]

 93%|█████████▎| 3050/3268 [21:07<01:31,  2.39it/s]

 93%|█████████▎| 3051/3268 [21:07<01:30,  2.39it/s]

 93%|█████████▎| 3052/3268 [21:08<01:30,  2.39it/s]

 93%|█████████▎| 3053/3268 [21:08<01:29,  2.39it/s]

 93%|█████████▎| 3054/3268 [21:08<01:29,  2.39it/s]

 93%|█████████▎| 3055/3268 [21:09<01:29,  2.39it/s]

 94%|█████████▎| 3056/3268 [21:09<01:28,  2.39it/s]

 94%|█████████▎| 3057/3268 [21:10<01:28,  2.39it/s]

 94%|█████████▎| 3058/3268 [21:10<01:27,  2.39it/s]

 94%|█████████▎| 3059/3268 [21:10<01:27,  2.39it/s]

 94%|█████████▎| 3060/3268 [21:11<01:26,  2.39it/s]

 94%|█████████▎| 3061/3268 [21:11<01:26,  2.39it/s]

 94%|█████████▎| 3062/3268 [21:12<01:26,  2.38it/s]

 94%|█████████▎| 3063/3268 [21:12<01:26,  2.38it/s]

 94%|█████████▍| 3064/3268 [21:13<01:25,  2.39it/s]

 94%|█████████▍| 3065/3268 [21:13<01:24,  2.39it/s]

 94%|█████████▍| 3066/3268 [21:13<01:24,  2.39it/s]

 94%|█████████▍| 3067/3268 [21:14<01:24,  2.39it/s]

 94%|█████████▍| 3068/3268 [21:14<01:23,  2.39it/s]

 94%|█████████▍| 3069/3268 [21:15<01:23,  2.39it/s]

 94%|█████████▍| 3070/3268 [21:15<01:23,  2.38it/s]

 94%|█████████▍| 3071/3268 [21:16<01:22,  2.38it/s]

 94%|█████████▍| 3072/3268 [21:16<01:22,  2.38it/s]

 94%|█████████▍| 3073/3268 [21:16<01:21,  2.39it/s]

 94%|█████████▍| 3074/3268 [21:17<01:21,  2.38it/s]

 94%|█████████▍| 3075/3268 [21:17<01:20,  2.39it/s]

 94%|█████████▍| 3076/3268 [21:18<01:20,  2.38it/s]

 94%|█████████▍| 3077/3268 [21:18<01:19,  2.39it/s]

 94%|█████████▍| 3078/3268 [21:18<01:19,  2.38it/s]

 94%|█████████▍| 3079/3268 [21:19<01:19,  2.38it/s]

 94%|█████████▍| 3080/3268 [21:19<01:18,  2.38it/s]

 94%|█████████▍| 3081/3268 [21:20<01:18,  2.39it/s]

 94%|█████████▍| 3082/3268 [21:20<01:18,  2.38it/s]

 94%|█████████▍| 3083/3268 [21:21<01:17,  2.39it/s]

 94%|█████████▍| 3084/3268 [21:21<01:17,  2.39it/s]

 94%|█████████▍| 3085/3268 [21:21<01:16,  2.39it/s]

 94%|█████████▍| 3086/3268 [21:22<01:16,  2.39it/s]

 94%|█████████▍| 3087/3268 [21:22<01:15,  2.39it/s]

 94%|█████████▍| 3088/3268 [21:23<01:15,  2.39it/s]

 95%|█████████▍| 3089/3268 [21:23<01:14,  2.39it/s]

 95%|█████████▍| 3090/3268 [21:23<01:14,  2.39it/s]

 95%|█████████▍| 3091/3268 [21:24<01:14,  2.39it/s]

 95%|█████████▍| 3092/3268 [21:24<01:13,  2.39it/s]

 95%|█████████▍| 3093/3268 [21:25<01:13,  2.38it/s]

 95%|█████████▍| 3094/3268 [21:25<01:13,  2.38it/s]

 95%|█████████▍| 3095/3268 [21:26<01:12,  2.39it/s]

 95%|█████████▍| 3096/3268 [21:26<01:12,  2.39it/s]

 95%|█████████▍| 3097/3268 [21:26<01:11,  2.39it/s]

 95%|█████████▍| 3098/3268 [21:27<01:11,  2.38it/s]

 95%|█████████▍| 3099/3268 [21:27<01:10,  2.39it/s]

 95%|█████████▍| 3100/3268 [21:28<01:10,  2.39it/s]

 95%|█████████▍| 3101/3268 [21:28<01:10,  2.38it/s]

 95%|█████████▍| 3102/3268 [21:29<01:09,  2.39it/s]

 95%|█████████▍| 3103/3268 [21:29<01:09,  2.39it/s]

 95%|█████████▍| 3104/3268 [21:29<01:08,  2.39it/s]

 95%|█████████▌| 3105/3268 [21:30<01:08,  2.39it/s]

 95%|█████████▌| 3106/3268 [21:30<01:07,  2.39it/s]

 95%|█████████▌| 3107/3268 [21:31<01:07,  2.39it/s]

 95%|█████████▌| 3108/3268 [21:31<01:06,  2.39it/s]

 95%|█████████▌| 3109/3268 [21:31<01:06,  2.39it/s]

 95%|█████████▌| 3110/3268 [21:32<01:06,  2.39it/s]

 95%|█████████▌| 3111/3268 [21:32<01:05,  2.39it/s]

 95%|█████████▌| 3112/3268 [21:33<01:05,  2.38it/s]

 95%|█████████▌| 3113/3268 [21:33<01:05,  2.38it/s]

 95%|█████████▌| 3114/3268 [21:34<01:04,  2.38it/s]

 95%|█████████▌| 3115/3268 [21:34<01:04,  2.39it/s]

 95%|█████████▌| 3116/3268 [21:34<01:03,  2.39it/s]

 95%|█████████▌| 3117/3268 [21:35<01:03,  2.39it/s]

 95%|█████████▌| 3118/3268 [21:35<01:02,  2.39it/s]

 95%|█████████▌| 3119/3268 [21:36<01:02,  2.39it/s]

 95%|█████████▌| 3120/3268 [21:36<01:02,  2.38it/s]

 96%|█████████▌| 3121/3268 [21:36<01:01,  2.39it/s]

 96%|█████████▌| 3122/3268 [21:37<01:01,  2.38it/s]

 96%|█████████▌| 3123/3268 [21:37<01:00,  2.39it/s]

 96%|█████████▌| 3124/3268 [21:38<01:00,  2.38it/s]

 96%|█████████▌| 3125/3268 [21:38<00:59,  2.39it/s]

 96%|█████████▌| 3126/3268 [21:39<00:59,  2.38it/s]

 96%|█████████▌| 3127/3268 [21:39<00:59,  2.39it/s]

 96%|█████████▌| 3128/3268 [21:39<00:58,  2.39it/s]

 96%|█████████▌| 3129/3268 [21:40<00:58,  2.39it/s]

logging
logging the anndata

 96%|█████████▌| 3130/3268 [21:40<00:59,  2.31it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 96%|█████████▌| 3131/3268 [21:41<00:58,  2.34it/s]

 96%|█████████▌| 3132/3268 [21:41<00:57,  2.37it/s]

 96%|█████████▌| 3133/3268 [21:42<00:56,  2.39it/s]

 96%|█████████▌| 3134/3268 [21:42<00:55,  2.40it/s]

 96%|█████████▌| 3135/3268 [21:42<00:55,  2.41it/s]

 96%|█████████▌| 3136/3268 [21:43<00:54,  2.42it/s]

 96%|█████████▌| 3137/3268 [21:43<00:54,  2.42it/s]

 96%|█████████▌| 3138/3268 [21:44<00:53,  2.43it/s]

 96%|█████████▌| 3139/3268 [21:44<00:53,  2.43it/s]

 96%|█████████▌| 3140/3268 [21:44<00:52,  2.43it/s]

 96%|█████████▌| 3141/3268 [21:45<00:52,  2.43it/s]

 96%|█████████▌| 3142/3268 [21:45<00:52,  2.41it/s]

 96%|█████████▌| 3143/3268 [21:46<00:51,  2.42it/s]

 96%|█████████▌| 3144/3268 [21:46<00:51,  2.42it/s]

 96%|█████████▌| 3145/3268 [21:46<00:50,  2.42it/s]

 96%|█████████▋| 3146/3268 [21:47<00:50,  2.42it/s]

 96%|█████████▋| 3147/3268 [21:47<00:49,  2.42it/s]

 96%|█████████▋| 3148/3268 [21:48<00:49,  2.42it/s]

 96%|█████████▋| 3149/3268 [21:48<00:49,  2.43it/s]

 96%|█████████▋| 3150/3268 [21:49<00:48,  2.43it/s]

 96%|█████████▋| 3151/3268 [21:49<00:48,  2.43it/s]

 96%|█████████▋| 3152/3268 [21:49<00:47,  2.43it/s]

 96%|█████████▋| 3153/3268 [21:50<00:47,  2.43it/s]

 97%|█████████▋| 3154/3268 [21:50<00:46,  2.43it/s]

 97%|█████████▋| 3155/3268 [21:51<00:46,  2.43it/s]

 97%|█████████▋| 3156/3268 [21:51<00:46,  2.42it/s]

 97%|█████████▋| 3157/3268 [21:51<00:45,  2.42it/s]

 97%|█████████▋| 3158/3268 [21:52<00:45,  2.42it/s]

 97%|█████████▋| 3159/3268 [21:52<00:45,  2.42it/s]

 97%|█████████▋| 3160/3268 [21:53<00:44,  2.42it/s]

 97%|█████████▋| 3161/3268 [21:53<00:44,  2.42it/s]

 97%|█████████▋| 3162/3268 [21:53<00:43,  2.42it/s]

 97%|█████████▋| 3163/3268 [21:54<00:43,  2.42it/s]

 97%|█████████▋| 3164/3268 [21:54<00:42,  2.43it/s]

 97%|█████████▋| 3165/3268 [21:55<00:42,  2.42it/s]

 97%|█████████▋| 3166/3268 [21:55<00:42,  2.42it/s]

 97%|█████████▋| 3167/3268 [21:56<00:41,  2.42it/s]

 97%|█████████▋| 3168/3268 [21:56<00:41,  2.43it/s]

 97%|█████████▋| 3169/3268 [21:56<00:40,  2.42it/s]

 97%|█████████▋| 3170/3268 [21:57<00:40,  2.42it/s]

 97%|█████████▋| 3171/3268 [21:57<00:39,  2.43it/s]

 97%|█████████▋| 3172/3268 [21:58<00:39,  2.43it/s]

 97%|█████████▋| 3173/3268 [21:58<00:39,  2.43it/s]

 97%|█████████▋| 3174/3268 [21:58<00:38,  2.43it/s]

 97%|█████████▋| 3175/3268 [21:59<00:38,  2.43it/s]

 97%|█████████▋| 3176/3268 [21:59<00:37,  2.43it/s]

 97%|█████████▋| 3177/3268 [22:00<00:37,  2.43it/s]

 97%|█████████▋| 3178/3268 [22:00<00:37,  2.43it/s]

 97%|█████████▋| 3179/3268 [22:00<00:36,  2.43it/s]

 97%|█████████▋| 3180/3268 [22:01<00:36,  2.43it/s]

 97%|█████████▋| 3181/3268 [22:01<00:35,  2.43it/s]

 97%|█████████▋| 3182/3268 [22:02<00:35,  2.43it/s]

 97%|█████████▋| 3183/3268 [22:02<00:35,  2.43it/s]

 97%|█████████▋| 3184/3268 [22:03<00:34,  2.43it/s]

 97%|█████████▋| 3185/3268 [22:03<00:34,  2.43it/s]

 97%|█████████▋| 3186/3268 [22:03<00:33,  2.43it/s]

 98%|█████████▊| 3187/3268 [22:04<00:33,  2.43it/s]

 98%|█████████▊| 3188/3268 [22:04<00:32,  2.43it/s]

 98%|█████████▊| 3189/3268 [22:05<00:32,  2.43it/s]

 98%|█████████▊| 3190/3268 [22:05<00:32,  2.43it/s]

 98%|█████████▊| 3191/3268 [22:05<00:31,  2.43it/s]

 98%|█████████▊| 3192/3268 [22:06<00:31,  2.43it/s]

 98%|█████████▊| 3193/3268 [22:06<00:30,  2.43it/s]

 98%|█████████▊| 3194/3268 [22:07<00:30,  2.43it/s]

 98%|█████████▊| 3195/3268 [22:07<00:30,  2.43it/s]

 98%|█████████▊| 3196/3268 [22:07<00:29,  2.42it/s]

 98%|█████████▊| 3197/3268 [22:08<00:29,  2.43it/s]

 98%|█████████▊| 3198/3268 [22:08<00:28,  2.43it/s]

 98%|█████████▊| 3199/3268 [22:09<00:28,  2.43it/s]

 98%|█████████▊| 3200/3268 [22:09<00:28,  2.43it/s]

 98%|█████████▊| 3201/3268 [22:10<00:27,  2.42it/s]

 98%|█████████▊| 3202/3268 [22:10<00:27,  2.43it/s]

 98%|█████████▊| 3203/3268 [22:10<00:26,  2.43it/s]

 98%|█████████▊| 3204/3268 [22:11<00:26,  2.42it/s]

 98%|█████████▊| 3205/3268 [22:11<00:26,  2.42it/s]

 98%|█████████▊| 3206/3268 [22:12<00:25,  2.42it/s]

 98%|█████████▊| 3207/3268 [22:12<00:25,  2.42it/s]

 98%|█████████▊| 3208/3268 [22:12<00:24,  2.42it/s]

 98%|█████████▊| 3209/3268 [22:13<00:24,  2.42it/s]

 98%|█████████▊| 3210/3268 [22:13<00:23,  2.42it/s]

 98%|█████████▊| 3211/3268 [22:14<00:23,  2.42it/s]

 98%|█████████▊| 3212/3268 [22:14<00:23,  2.43it/s]

 98%|█████████▊| 3213/3268 [22:14<00:22,  2.42it/s]

 98%|█████████▊| 3214/3268 [22:15<00:22,  2.42it/s]

 98%|█████████▊| 3215/3268 [22:15<00:21,  2.42it/s]

 98%|█████████▊| 3216/3268 [22:16<00:21,  2.42it/s]

 98%|█████████▊| 3217/3268 [22:16<00:21,  2.41it/s]

 98%|█████████▊| 3218/3268 [22:17<00:20,  2.42it/s]

 99%|█████████▊| 3219/3268 [22:17<00:20,  2.42it/s]

 99%|█████████▊| 3220/3268 [22:17<00:19,  2.42it/s]

 99%|█████████▊| 3221/3268 [22:18<00:19,  2.42it/s]

 99%|█████████▊| 3222/3268 [22:18<00:18,  2.42it/s]

 99%|█████████▊| 3223/3268 [22:19<00:18,  2.42it/s]

 99%|█████████▊| 3224/3268 [22:19<00:18,  2.42it/s]

 99%|█████████▊| 3225/3268 [22:19<00:17,  2.42it/s]

 99%|█████████▊| 3226/3268 [22:20<00:17,  2.42it/s]

 99%|█████████▊| 3227/3268 [22:20<00:16,  2.42it/s]

 99%|█████████▉| 3228/3268 [22:21<00:16,  2.42it/s]

 99%|█████████▉| 3229/3268 [22:21<00:16,  2.42it/s]

 99%|█████████▉| 3230/3268 [22:22<00:15,  2.42it/s]

 99%|█████████▉| 3231/3268 [22:22<00:15,  2.42it/s]

 99%|█████████▉| 3232/3268 [22:22<00:14,  2.42it/s]

 99%|█████████▉| 3233/3268 [22:23<00:14,  2.42it/s]

 99%|█████████▉| 3234/3268 [22:23<00:14,  2.42it/s]

 99%|█████████▉| 3235/3268 [22:24<00:13,  2.42it/s]

 99%|█████████▉| 3236/3268 [22:24<00:13,  2.42it/s]

 99%|█████████▉| 3237/3268 [22:24<00:12,  2.42it/s]

 99%|█████████▉| 3238/3268 [22:25<00:12,  2.42it/s]

 99%|█████████▉| 3239/3268 [22:25<00:11,  2.42it/s]

 99%|█████████▉| 3240/3268 [22:26<00:11,  2.42it/s]

 99%|█████████▉| 3241/3268 [22:26<00:11,  2.42it/s]

 99%|█████████▉| 3242/3268 [22:26<00:10,  2.42it/s]

 99%|█████████▉| 3243/3268 [22:27<00:10,  2.42it/s]

 99%|█████████▉| 3244/3268 [22:27<00:09,  2.42it/s]

 99%|█████████▉| 3245/3268 [22:28<00:09,  2.42it/s]

 99%|█████████▉| 3246/3268 [22:28<00:09,  2.42it/s]

 99%|█████████▉| 3247/3268 [22:29<00:08,  2.42it/s]

 99%|█████████▉| 3248/3268 [22:29<00:08,  2.42it/s]

 99%|█████████▉| 3249/3268 [22:29<00:07,  2.42it/s]

 99%|█████████▉| 3250/3268 [22:30<00:07,  2.42it/s]

 99%|█████████▉| 3251/3268 [22:30<00:07,  2.42it/s]

100%|█████████▉| 3252/3268 [22:31<00:06,  2.42it/s]

100%|█████████▉| 3253/3268 [22:31<00:06,  2.42it/s]

100%|█████████▉| 3254/3268 [22:31<00:05,  2.42it/s]

100%|█████████▉| 3255/3268 [22:32<00:05,  2.42it/s]

100%|█████████▉| 3256/3268 [22:32<00:04,  2.42it/s]

100%|█████████▉| 3257/3268 [22:33<00:04,  2.42it/s]

100%|█████████▉| 3258/3268 [22:33<00:04,  2.42it/s]

100%|█████████▉| 3259/3268 [22:34<00:03,  2.41it/s]

100%|█████████▉| 3260/3268 [22:34<00:03,  2.42it/s]

100%|█████████▉| 3261/3268 [22:34<00:02,  2.42it/s]

100%|█████████▉| 3262/3268 [22:35<00:02,  2.42it/s]

100%|█████████▉| 3263/3268 [22:35<00:02,  2.42it/s]

100%|█████████▉| 3264/3268 [22:36<00:01,  2.43it/s]

100%|█████████▉| 3265/3268 [22:36<00:01,  2.42it/s]

100%|█████████▉| 3266/3268 [22:36<00:00,  2.42it/s]

100%|█████████▉| 3267/3268 [22:37<00:00,  2.42it/s]

100%|██████████| 3268/3268 [22:37<00:00,  2.75it/s]

100%|██████████| 3268/3268 [22:38<00:00,  2.41it/s]

logging the anndata
AnnData object with n_obs × n_vars = 8806 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

too few cells to embed into a umap
too few cells to compute a clustering

PairwiseArrays with keys: connectivities, distances

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.313553 -16.456562 -17.54121  ...  -9.149689 -11.025501 -12.867841]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.537111 -13.391066 -13.099134 ... -12.219165 -12.661721 -13.161593]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.021393  -12.559756  -18.260904  ...  -9.1115675 -11.933737
 -16.37192  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.830495  -13.591352  -14.133504  ...  -8.4875555  -9.952814
 -11.853613 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.056225 -13.033734 -18.696335 ... -11.917762 -14.873211 -19.179792]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.53296  -13.445616 -13.166917 ... -12.140463 -12.522409 -13.063645]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.008526 -13.226011 -13.146573 ... -11.528879 -11.783493 -12.662271]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.672924 -14.784079 -17.54039  ...  -8.752807 -12.284047 -14.606188]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.07393  -15.70155  -18.769396 ... -10.006373 -13.448662 -16.502705]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.12988  -14.179509 -16.996716 ... -11.856577 -13.564266 -18.268173]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.516667 -10.240792 -11.765215 ... -11.545297 -12.397875  -9.88297 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.0415   -18.08816  -21.404999 ...  -9.466547 -10.970091  -9.467515]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.746773 -14.430537 -14.211637 ...  -8.375742  -8.69049   -9.905355]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.8217053 -5.850671  -5.326108  ... -2.543342  -3.1089344 -4.641211 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.84374  -18.904928 -19.183899 ... -13.131413 -12.807542 -15.350346]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.678833  -10.093282  -10.4995165 ...  -7.2744193  -6.1696215
  -8.945775 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.231159   -8.793211  -11.219853  ... -14.4797535 -10.538647
 -13.904743 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.120308 -19.793407 -20.108303 ... -12.810735 -10.747266 -14.508576]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.694187 -18.347609 -23.043533 ... -13.633191 -12.366949 -16.488062]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.495102 -20.670628 -19.868767 ... -10.949408 -10.931889 -15.045186]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.160833 -14.457992 -12.1785   ... -14.198686 -14.653257 -13.606711]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.822746  -13.790758  -14.482371  ...  -8.639144  -10.1001625
 -11.925952 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.72666   -5.8257117 -4.241234  ... -3.466817  -2.1942616 -2.1074262]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.857753 -17.329098 -19.453423 ... -12.100156 -13.794935 -16.449429]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.001494 -10.523256 -12.75553  ...  -8.848454  -9.137233 -14.253107]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.4876175 -13.431938  -14.690016  ... -11.356205  -11.103222
 -12.895352 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.31406   -10.857999  -11.467131  ...  -5.1982956  -5.984997
  -8.030915 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.3809557 -10.11939   -10.877875  ...  -4.5725694  -5.2792654
  -6.804634 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.467521  -9.883853 -10.477803 ...  -4.252671  -5.243705  -7.015626]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.20393   -12.794331  -14.314945  ...  -6.130624   -6.6360135
  -9.176471 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.8268147 -5.801221  -5.829665  ... -6.7052803 -6.024957  -6.5825386]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -1.9267154   0.6841585  -2.8430765 ...  -7.184527   -9.312621
 -11.433011 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.1024457 -2.378989  -4.3259897 ... -3.4248188 -4.349545  -8.780247 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.677127 -16.708067 -16.66761  ... -19.228708 -17.447468 -20.844545]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.716991  -16.093235  -19.57281   ... -15.247811  -15.2092705
 -21.567835 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.486475  -12.5794115 -19.838179  ... -14.964124  -16.223486
 -22.023489 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.7082334 -7.382986  -7.5178633 ... -3.1663928 -3.7323034 -5.793276 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.034044  -6.6222353 -7.369943  ... -5.1613107 -4.3463516 -5.4827313]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.4927526  -9.10279   -11.826824  ...  -4.840817   -5.868207
  -8.632893 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.676357  -5.317315  -4.8087673 ... -1.9460746 -3.4894419 -5.079121 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.753466 -20.044275 -19.132607 ... -12.0173   -12.788252 -13.227004]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.401772  -12.859794  -13.687186  ...  -6.3868313  -8.030883
 -10.369984 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.127322 -16.81412  -15.098186 ... -15.273917 -14.1735   -16.615522]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.6050587 -8.861127  -7.6461883 ... -4.4458995 -3.11819   -2.9499114]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.209025 -10.730437 -11.982728 ...  -5.01339   -6.176621  -7.353279]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.408658  -14.252188  -15.436371  ... -12.202868  -11.4744835
 -13.747133 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.29705  -12.528204 -12.648659 ... -11.410267 -11.81772  -12.400094]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.512554  -6.903365  -4.6897416 ... -5.7406883 -4.5612826 -2.6502109]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.79891   -13.656379  -13.654985  ...  -7.6491146  -6.3847146
  -8.074842 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.830644 -17.322102 -16.421394 ... -15.322068 -12.226531 -13.379292]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.7189536 -7.3625884 -5.1940017 ... -4.095365  -2.9554875 -5.9765987]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.600267 -16.689384 -15.192123 ... -10.957816 -16.187664 -16.099049]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.141574  -12.311488  -12.444192  ...  -9.869324   -7.0021386
 -10.876474 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.287798 -24.832928 -27.022371 ... -13.902799 -15.166269 -18.620205]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.883649 -12.233099 -11.745179 ... -12.302529 -11.683156 -13.337753]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.737457  -7.919359  -6.7705207 ... -3.9927084 -4.3284326 -6.2248716]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.169533 -13.390114 -15.499684 ... -10.744356 -12.723472 -15.052253]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.966022 -14.210683 -14.816619 ...  -9.706611 -10.76186  -12.380015]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.821138 -17.666325 -18.41513  ... -14.611421 -13.049607 -16.710194]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.596209 -21.346632 -17.570816 ... -10.312347 -10.651429 -12.169579]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.8556657  -9.444192  -10.136835  ...  -5.178037   -4.3554335
  -6.4929013]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.743226  -11.069721  -10.572884  ...  -8.31353    -7.8913946
  -9.157677 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.036864  -13.861438  -12.781374  ... -10.687185   -9.1403265
 -11.693318 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.528589 -16.6877   -18.13083  ... -15.674165 -15.207284 -17.263943]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.809721 -14.941113 -15.438416 ... -14.341454 -13.566564 -14.553664]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.736378 -14.254102 -14.737342 ... -13.665479 -13.155586 -14.225114]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.178784 -14.202473 -16.24807  ... -17.011934 -16.202023 -17.97952 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.401333 -16.840487 -17.644207 ... -17.844196 -17.441545 -18.349846]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.752129 -16.036251 -16.987669 ... -17.020447 -16.088858 -16.976885]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.024765 -15.645372 -16.93515  ... -15.909815 -15.207782 -16.387062]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.007903   -6.8120904 -11.48611   ...  -7.8658795  -8.500483
  -9.396716 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.183355 -14.915947 -14.881809 ...  -6.956417  -7.018156  -8.982645]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.332095 -11.328539 -11.859549 ...  -8.559202  -8.941564 -10.998769]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.7587256 -7.125217  -7.5662694 ... -1.5426279 -3.3714113 -4.3370657]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.478391  -12.914263  -12.107806  ...  -7.8477383  -8.842743
 -11.197915 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.935717 -18.990425 -20.233618 ...  -7.941136 -10.490213 -14.007491]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.400163  -8.757366 -10.257514 ...  -4.880993  -6.426951  -8.225338]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.532015  -5.782399  -6.698625  ... -1.4186006 -4.089198  -5.1917367]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.993171 -15.356327 -14.976959 ...  -9.325595 -11.468557 -13.213216]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.8470554 -6.3040037 -7.1571884 ... -2.7878292 -5.4440036 -6.4291883]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.667932  -12.79893   -14.7095995 ... -10.948851  -12.983815
 -17.10132  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.2070413 -5.898876  -6.0753374 ... -2.729661  -5.123167  -6.189155 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.753082  -11.169312  -10.327309  ...  -6.5030403  -8.85937
  -9.689261 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.93619   -15.478789  -16.78151   ... -10.9336195 -11.76303
 -15.435272 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.426928 -15.611822 -15.662599 ... -14.320804 -15.821643 -17.114294]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.190619 -22.35193  -20.701647 ... -14.237029 -15.770497 -16.141201]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.661907  -4.0215154 -3.5620294 ... -2.8465772 -5.2905087 -5.183308 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.14738  -12.534699 -12.928224 ... -10.414625 -11.297315 -11.947402]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.9924135 -12.95824   -12.872379  ... -11.8360815 -12.117246
 -12.765139 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.7440515 -4.570213  -5.134054  ... -3.0664794 -5.1609306 -5.5936413]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.1195    -14.95428   -16.071234  ...  -7.7732563  -8.793403
  -8.126948 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.848333  -6.025325  -7.41327   ... -2.5234044 -2.9695268 -3.1832604]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.824675 -25.56619  -26.367838 ... -19.560036 -19.889183 -20.21684 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.58732   -8.863009  -7.374688 ...  -9.16615  -11.077439 -12.137048]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.209891  -11.47995    -9.2785015 ...  -5.303403   -8.350427

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.294045  -11.438001  -12.030429  ...  -4.5788565  -6.6698904
  -7.270344 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.582835 -12.485568 -12.549693 ... -11.410375 -12.003897 -12.616621]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.234608  -17.334526  -16.529848  ...  -7.6695585 -10.275659
 -12.442266 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.738997  -19.49813   -19.224419  ...  -9.6331835 -10.731951
 -13.68019  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.958438  -16.969975  -15.321076  ...  -7.3721485 -10.527546
 -12.769179 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.2438736 -5.533913  -7.173702  ... -2.9352012 -5.104341  -5.882895 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.054893  -8.397556  -8.671265 ...  -8.409323  -9.354291 -12.632768]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.357176 -14.127477 -13.847689 ...  -9.055271 -10.789137 -13.107084]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.986755  -4.9743996 -6.6974573 ... -2.7197828 -4.9392195 -5.7055345]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.972396  -8.168335  -8.81128  ...  -7.210331  -8.615672 -12.090547]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.547781  -6.05118   -7.6577845 ... -3.0154402 -5.324044  -6.0450788]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.323555   -5.7651916  -8.965109  ...  -7.639191   -7.147134
 -11.216151 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.8108263 -4.565009  -4.8624797 ... -2.2843182 -4.655698  -5.2882357]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.281433  -13.22569   -16.089476  ...  -8.205315   -6.7538557
  -9.157495 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.295568 -23.594555 -22.85663  ... -13.525884 -16.434628 -19.88872 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.574073 -15.483708 -17.16546  ... -11.440625 -13.372811 -16.381777]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.65068   -9.814107 -10.140637 ...  -7.086418  -5.547831  -8.954796]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.324812 -20.193802 -18.58269  ... -17.354603 -19.34509  -18.932955]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.279044  -6.5986114 -5.859443  ... -2.9537644 -5.3346295 -5.9622226]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.770917  -8.250326  -7.7168264 ... -4.7494073 -7.3561397 -8.295484 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.0148387 -6.21192   -6.4996142 ... -3.306443  -5.4698524 -6.504685 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.962516 -12.496115 -13.341032 ...  -7.627466  -9.373853 -10.851519]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.406567  -6.820724  -7.6390734 ... -2.099054  -4.5811677 -5.4449854]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.325049 -17.1307   -15.257262 ...  -8.405461  -9.045718  -8.937311]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.7081275 -5.7145147 -6.0804043 ... -2.543912  -4.8321333 -5.856075 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.872417   -8.726022  -10.509966  ...  -7.6629686  -6.824602
  -7.5838914]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.072983  -7.616136  -8.756207  ... -4.2531257 -5.5925603 -5.605857 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.8617134  -9.51933   -10.365828  ...  -4.213411   -4.9782844
  -7.129804 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.5884275 -3.884417  -3.9996216 ... -2.6271365 -4.8634043 -5.3235607]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.834146  -7.0608807 -5.373814  ... -2.9434557 -4.7275486 -5.6158314]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.252564  -5.368024  -6.764007  ... -3.1858726 -5.6330647 -6.611288 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.676027  -3.9790626 -4.017606  ... -2.7161193 -4.9989233 -5.413626 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.767716 -13.947867 -13.74176  ... -11.157527 -11.546901 -12.391886]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.441735 -13.327299 -13.395322 ... -11.50818  -12.304417 -13.066782]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.448208  -12.553319  -12.911748  ...  -9.6902895 -10.275672
 -10.813675 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.432052  -12.791719  -11.88661   ...  -8.1876135 -11.708687
 -12.160114 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.306563  -16.573805  -18.462875  ... -12.938051  -13.5027275
 -18.144762 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.66745   -7.384623  -7.7567587 ... -4.6030498 -6.940799  -7.077207 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.854057 -15.320561 -16.91932  ... -10.06268  -10.33018  -14.182999]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.688648 -17.449495 -18.651031 ...  -9.277545 -11.134441 -12.10365 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.886492 -17.363249 -19.833954 ...  -9.394465  -8.846934 -13.99441 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.558408  -10.351143  -10.181844  ...  -3.8123653  -5.1875253
  -6.2680764]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.363675  -9.620922  -9.950813  ... -3.9819608 -5.5124345 -5.468836 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.971422 -19.621428 -21.84779  ... -10.117096 -10.123064 -12.830496]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.196442  -9.358135  -9.162568  ... -7.2269588 -6.0849934 -7.8453856]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.998128 -13.631764 -11.068882 ...  -8.439072  -6.340104  -8.780842]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.92611  -20.722012 -19.256092 ... -10.170901 -11.440549 -14.179037]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.6299114 -6.9546747 -7.3787775 ... -3.7887077 -4.829698  -7.2868934]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.4128275 -15.506698  -15.501342  ...  -6.20107    -8.627754
  -8.806955 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.8185134 -8.798314  -8.256455  ... -4.7697406 -5.6970496 -7.6937594]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.874327  -7.7723975 -7.597058  ... -4.3328032 -5.0911345 -6.8693385]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.0189705 -11.659187  -11.326502  ...  -3.1648858  -5.1805077
  -6.725793 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.256001  -8.357407  -5.3117228 ... -4.7667885 -2.9376683 -5.8419585]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.016959 -12.013239 -11.334209 ... -10.817906 -10.449215 -10.931027]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.048026  -11.585385  -12.317549  ...  -5.2644153  -6.20826
  -8.100625 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.953734 -12.59487  -12.430275 ...  -9.959218 -10.232379 -11.082532]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.726015  -11.294277  -11.891628  ...  -5.0367785  -6.125993
  -7.9600763]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.083942  -10.802872  -10.92505   ...  -4.8814282  -6.073738
  -7.6404943]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.346023  -10.296172  -10.80073   ...  -4.9093904  -5.902458
  -7.551776 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.594323 -13.083912 -13.321988 ... -11.561706 -11.963827 -12.753442]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.1199245  -7.18903   -10.0034    ...  -4.4300704  -5.4836383
  -7.4190493]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.472715 -12.794481 -13.156213 ... -11.257142 -11.811176 -12.673459]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.417772 -13.348516 -13.128005 ... -12.22959  -12.599632 -13.103728]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.893025  -11.024259   -9.461907  ...  -5.202336   -5.153044
  -6.9693546]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.020254 -16.389616 -12.93518  ... -14.67322  -12.13478  -11.71698 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.798251 -17.306513 -19.544806 ... -11.498238 -12.105706 -16.929775]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.487821  -8.510237  -8.012664  ... -3.1711953 -5.4358177 -7.0868506]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.5854225 -8.999818  -8.966309  ... -2.7577102 -4.939414  -6.2285604]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.661083   -9.344368  -10.471646  ...  -4.1798472  -5.0647116
  -7.187291 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.3034263 -5.906986  -4.9447885 ... -3.7757034 -3.1748352 -1.6204726]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.748666  -11.708137  -11.320503  ...  -5.9440923  -9.341991
  -9.821737 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.811452 -15.670086 -17.65015  ...  -7.099242  -7.692819 -11.697153]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.464767  -4.1803865 -4.130771  ... -2.3867226 -3.850507  -4.617391 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.915976  -12.848851  -12.647292  ...  -8.831303   -6.9304004
 -10.439477 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.168087 -13.149936 -13.021673 ... -11.778093 -12.343178 -13.008298]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.702053  -9.617948 -11.537723 ...  -9.232551 -11.306099 -12.887511]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.354408  -7.295611  -9.4072    ... -4.849336  -5.6995945 -6.3216457]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.545834   -9.6746025 -11.483058  ...  -7.9889183  -6.848545
 -10.767543 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.7734895 -7.2524843 -4.8887224 ... -3.6296031 -2.8038132 -1.6694177]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.531062  -10.578858  -12.012666  ...  -4.5174403  -5.607939
  -8.561816 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.563187 -20.582218 -19.169704 ...  -6.113935  -9.480832 -12.852618]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.1820464 -8.148364  -5.3244457 ... -4.5112643 -2.788544  -5.3666215]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.4446945 -13.250838  -13.000822  ... -12.207482  -12.576209
 -13.0925665]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.381577  -11.093267  -12.467117  ...  -5.8885403  -7.5877004
  -8.879644 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.006673 -12.223007 -11.688936 ... -10.540107 -10.422309 -11.151796]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.54401  -21.063023 -21.726122 ... -11.093732 -10.57598  -12.049246]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.4405346 -7.552666  -8.350331  ... -2.6401637 -4.9199295 -5.6691475]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.218186  -7.165876  -8.108343  ... -2.6771944 -4.1743417 -4.6024504]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.195934 -19.07016  -17.920849 ... -12.95803  -13.744469 -11.989576]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.699947 -20.459843 -19.29913  ... -11.5588   -11.529076 -14.148992]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.600227  -15.450745  -16.491253  ...  -7.9178143  -7.7212343
  -8.588854 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.438153 -12.768531 -13.227954 ...  -8.711727 -10.07198  -11.788944]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.0806384 -6.3376527 -6.949867  ... -4.13383   -4.974067  -5.3749094]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.661614  -11.7535925 -12.148879  ...  -4.6417074  -6.859788
  -6.945399 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.289327  -13.671595   -7.5095625 ...  -7.155664   -6.130169
  -3.6825464]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.150206 -12.260858 -12.270487 ...  -9.483953  -9.200201 -11.142744]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.998932  -12.966702  -11.9959755 ...  -5.743947   -6.608518
  -7.8587832]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.416994  -11.043791  -10.668567  ...  -5.2476287  -6.196935
  -7.713755 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.645216  -19.167778  -17.638521  ...  -8.805141   -6.9037285
  -6.9521093]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.595866  -13.319446  -10.786211  ...  -6.3118196  -6.0533557
  -9.211551 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.7079463 -8.814068  -7.899478  ... -4.118256  -4.1563663 -5.9481134]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.9830236 -9.051578  -6.1362624 ... -4.86501   -3.1067672 -5.205939 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.593803  -9.1155205 -5.935508  ... -5.4391475 -2.8538134 -6.3727803]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.237792  -11.510847  -10.69382   ...  -5.974889   -6.3239083
  -7.166625 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.577475 -25.144058 -22.225912 ... -20.408792 -19.444584 -17.70209 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.2473607 -9.583049  -9.5855465 ... -5.779075  -4.624732  -6.895633 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.388828 -11.892059 -13.309134 ...  -9.181271  -8.527635 -11.774002]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.46849  -18.683533 -21.67956  ... -16.800129 -15.524911 -18.557755]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.915011 -11.452278 -13.071899 ...  -8.821319  -9.12377  -12.61343 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.016699 -13.079486 -12.975674 ... -11.805535 -12.279142 -12.83891 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.181221  -16.522795  -11.216232  ...  -7.801321   -6.406394
  -5.4068947]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.790213 -20.643501 -21.730589 ... -14.040528 -14.955629 -17.33108 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.248579  -12.850131  -12.198033  ... -10.8418255 -10.96183
 -11.260195 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.975168  -10.806874  -11.960301  ...  -4.3223495  -5.793486
  -6.7404943]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.497056  -17.988556  -16.951746  ... -13.559556  -12.504263
 -13.4005165]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.312729 -20.25668  -18.834492 ... -16.000036 -13.470518 -14.769172]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.6344466 -5.8596063 -6.979844  ... -2.265851  -2.5546682 -3.165414 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.416889  -10.734635  -10.659079  ...  -5.4685216  -6.075441
  -8.038712 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.105015 -20.199198 -18.074896 ... -18.652431 -16.549314 -18.304976]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.699833 -21.336224 -21.091867 ... -16.395401 -16.207178 -18.162308]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.73545   -12.758644  -12.4203005 ...  -8.364335   -8.055719
  -9.445879 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.76296   -5.4647145 -4.183359  ... -2.4641383 -4.8441553 -5.396755 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.7520704 -6.743439  -5.909848  ... -3.4920647 -5.390933  -6.433478 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.120556  -5.1397395 -5.9121823 ... -7.000127  -6.8401594 -9.79866  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.615794 -10.093012 -10.686434 ...  -9.008568  -8.015216 -10.925787]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.2342    -11.847133  -11.149319  ...  -8.342605   -7.3674245
 -10.340518 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.275033 -14.820042 -14.885346 ... -13.708241 -11.935448 -15.537035]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.056157  -9.544893  -9.4387045 ... -8.046038  -7.089079  -9.590881 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.856968 -10.93468  -12.101356 ...  -8.689705  -8.210637 -11.461457]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.095499 -20.336487 -21.58283  ... -18.801407 -18.010405 -20.191769]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.908271  -10.919722  -12.02238   ...  -7.020265   -5.8692765
  -8.458857 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.702467  -13.562489  -13.1798115 ... -12.340202  -12.761222
 -13.195387 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.65489  -14.175676 -16.744942 ... -12.903725 -12.179202 -15.574688]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.472535  -10.2186365 -10.611582  ...  -4.8124695  -5.863913
  -7.5734506]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.112922  -10.609979   -9.456037  ...  -4.2035117  -4.4724116
  -5.604296 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.841227 -22.775122 -18.259373 ... -10.352306 -11.52739  -15.380087]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.110837 -10.34005  -11.505312 ...  -9.849811  -8.755602 -11.276728]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.262802  -14.635116  -17.597784  ... -12.4423275 -14.050388
 -13.665684 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.043661 -13.025863 -12.779986 ... -11.890986 -12.173718 -12.715708]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.432256  -17.02031   -17.858059  ... -13.2373495 -14.125255
 -15.928505 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.849502 -16.560884 -15.979798 ...  -8.411679  -8.520286  -8.527541]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.840852   -7.4423413 -10.453085  ...  -5.1608353  -6.2853165
  -8.359913 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.703733 -15.887826 -12.045083 ... -12.668495  -8.569996 -11.914422]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.000457 -8.715593 -8.19871  ... -3.663211 -2.849683 -5.501627]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.387274 -24.094915 -21.969654 ...  -9.284918  -7.611194 -12.376166]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.840826 -19.35406  -15.929959 ... -16.82856  -14.985299 -13.786793]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.4586663  -9.287934  -10.153343  ...  -6.006257   -6.592481
  -7.2874556]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.662792  -7.2087655 -8.222887  ... -4.002235  -6.3761134 -7.1072516]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.833222 -13.379059 -12.129762 ... -12.683047 -12.684813 -12.955285]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.011076 -22.263931 -22.352684 ... -11.800682 -14.748218 -16.638674]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.121193 -14.366579 -15.089003 ...  -8.897015 -10.431538 -11.972125]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.020392 -10.251364  -9.703181 ... -12.555697 -11.221093 -12.55284 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.188231  -10.940408  -11.9359455 ...  -9.324719   -8.930495
 -11.958303 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.905717 -13.093347 -13.006213 ... -11.732159 -12.208599 -12.848759]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.797258 -17.216135 -17.286243 ... -15.357422 -14.383759 -17.751282]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.96189  -14.937541 -15.066174 ...  -7.73514   -6.71642  -11.042029]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.256498  -15.165072  -17.176489  ... -15.267454  -13.3474245
 -16.29013  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.823067  -9.671382 -10.133807 ...  -8.069595  -8.731982 -10.770454]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.302935 -10.388349 -11.201003 ...  -7.661155  -7.974349  -9.20442 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.877063  -2.6383877 -2.1586115 ... -3.0343556 -2.399719  -1.3747411]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.967256 -14.164053 -14.103035 ... -12.562353 -13.299418 -13.190895]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.923061 -21.453146 -19.6214   ...  -9.492871  -9.503495 -10.192853]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.900806 -11.286427 -11.5142   ...  -9.430961  -9.496679 -10.706762]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.562385  -17.156084  -18.69135   ... -15.6644745 -13.743634
 -17.724632 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.870947 -16.318562 -16.871412 ... -12.973069 -10.355842 -14.095038]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.483377 -16.628153 -18.096708 ... -17.308535 -15.414296 -19.330936]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.236573 -13.779682 -13.5514   ...  -9.265696  -9.393104  -9.868858]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.152708 -16.463673 -17.19429  ... -15.579977 -13.241903 -16.577816]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.400015  -11.9863615 -11.633685  ...  -5.5515423  -6.5523934
  -8.416281 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.518012 -8.463919 -8.899578 ... -8.739439 -9.919645 -8.839936]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.880367 -17.093168 -15.563739 ...  -9.538338  -7.741164  -9.305404]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.1709366 -8.777679  -7.9389706 ... -4.2735505 -3.6320062 -5.4701734]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.686199  -15.9313965 -17.915215  ... -10.877422  -10.930252
  -8.620603 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.796433  -8.745097  -8.988454  ... -5.1499195 -6.1499615 -6.587894 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.607502 -12.773605 -12.996625 ...  -8.724027 -10.309629  -8.288536]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.2898674 -10.536425  -11.091018  ...  -7.5591016  -6.814255
  -9.268599 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.628746  -17.905537  -20.614485  ... -14.141797  -14.8101225
 -16.60606  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.16314   -7.0668626 -7.480221  ... -3.9871862 -4.1471877 -6.257238 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.982712 -17.570175 -19.500702 ... -14.172141 -12.356291 -16.381353]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.834379  -8.276209  -4.7819724 ... -4.057797  -2.435882  -5.578008 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.000566 -11.682216 -12.155837 ... -10.421319 -10.732176 -11.744544]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.456544 -18.611996 -15.757086 ...  -9.292583  -7.904473  -9.496697]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.493169 -18.095598 -15.488452 ...  -9.693362  -8.885758  -9.4818  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.4314203 -6.3753643 -7.275992  ... -5.6115484 -5.880564  -6.662743 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.946096 -18.802187 -20.121622 ... -15.735903 -14.282546 -16.476406]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.102369  -7.2261114 -9.267603  ... -4.17461   -5.354988  -6.7451577]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.219416  -8.066881  -9.92942   ... -3.9086707 -4.490641  -7.6374416]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.691806 -13.070193 -13.041648 ...  -8.822485  -9.733283 -11.002629]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.9670787 -10.345049   -8.338891  ...  -3.7932627  -4.7932186
  -7.1293955]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.6913497  -0.23853973 -3.8097172  ... -5.8428574  -5.1080155
 -8.768723  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.09345  -15.426523 -13.380437 ...  -8.548617  -7.664197 -11.706662]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.230385   -9.81247   -10.040783  ...  -4.0052724  -4.8853474
  -7.2239976]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.396413 -10.371307 -10.104891 ...  -4.463395  -5.399117  -7.077993]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.712536 -13.271251 -13.131936 ...  -8.909022  -9.504246 -11.854139]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.747673  -7.6628194 -3.6666539 ... -5.3663316 -4.8107147 -2.9430633]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.1501827 -5.464266  -6.6246448 ... -1.5832559 -2.3992825 -2.4692354]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.709229 -14.844638 -15.530021 ... -11.343048  -9.781266 -11.347847]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.83471   -11.716666  -11.3961525 ...  -5.9422593  -6.941009
  -9.0376005]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.557417 -17.330572 -17.86895  ... -14.581028 -12.171317 -15.472772]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.639698  -11.778359  -13.052921  ...  -8.110916   -7.0798564
 -11.193718 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.99455  -17.850037 -18.62885  ... -15.999884 -14.985986 -17.176119]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.537653  -11.293518  -10.756188  ...  -5.940677   -6.9291787
  -8.59069  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.040693  -5.704355  -4.699502  ... -2.2399766 -1.3138942 -4.10154  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.572439 -14.691335 -13.941182 ... -10.606347  -9.702052 -11.521054]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.2870684 -6.9374447 -6.3206205 ... -3.0559115 -2.4431083 -5.364747 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.4246597 -6.858508  -6.2655764 ... -3.3670242 -2.7884471 -5.5464015]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.431715 -17.18591  -17.012121 ... -13.094996 -11.478864 -14.851941]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.633966 -10.739199 -10.264332 ...  -4.80019   -5.820944  -7.937773]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.279128 -14.475828 -14.858911 ... -14.111851 -13.624547 -15.631879]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.124127  -11.085174  -10.289686  ...  -5.173544   -5.8313236
  -7.6727953]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.7813706 -7.6031394 -6.454282  ... -3.1926153 -2.9718528 -5.76367  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.1610293 -7.381893  -8.264572  ... -6.4744563 -4.5468087 -6.6855245]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.997626  -6.6906557 -3.9423332 ... -4.9015455 -3.5594862 -6.8159266]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.827912  -11.576419  -11.393438  ...  -4.106537   -4.7959356
  -5.96179  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.41697   -10.960857  -10.2439785 ...  -3.5684705  -5.3199134
  -6.713424 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.111847  -15.2053995 -17.39569   ... -13.407798  -11.790202
 -17.025072 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.698197 -10.126634  -9.796738 ...  -6.497497  -7.097801  -9.453779]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.641362  -9.461681 -10.844058 ...  -8.119158  -7.413506 -10.727782]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.279486  -21.89087   -18.215557  ... -15.690324  -12.59843
 -14.1395855]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.94895   -13.219909  -13.219507  ... -11.520825  -11.9037895
 -12.609869 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.350634 -13.271669 -12.965182 ... -12.121568 -12.486815 -12.95769 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.332294 -17.727398 -17.080185 ... -12.140334 -10.227486 -15.222484]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.477374 -12.75626  -12.547732 ... -11.579241 -11.62753  -12.012015]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.396996  -12.26571   -10.479127  ...  -7.318023   -5.9786215
  -5.1426964]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.5882845 -13.950317  -15.094586  ... -12.290301  -11.715884
 -14.624563 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.43841   -9.244639  -9.217787 ...  -8.954362 -10.547087 -13.111081]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.54183   -7.5206203 -6.8360925 ... -3.5440977 -3.1375902 -6.0614114]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.4102745 -6.6560035 -6.017573  ... -2.993514  -2.39119   -5.1116014]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.522911 -20.40137  -20.076483 ... -14.619349 -16.757074 -17.321716]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.597213  -6.2468653 -5.4586096 ... -3.2287567 -2.6660008 -5.324669 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.642379  -15.651971  -14.606761  ... -11.391309   -8.929778
  -7.8843203]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.0714993 -6.10682   -3.325207  ... -3.7817519 -3.1162019 -5.630525 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.869385  -9.141173 -10.904962 ... -11.750169 -12.073131 -15.425505]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.580017 -18.402727 -19.199583 ... -14.27863  -12.713194 -15.886209]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.129901 -16.129416 -18.027464 ... -11.667304 -11.400648 -11.645129]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.991936  -18.707561  -15.735158  ...  -6.5937486  -6.858223
  -5.645112 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.356728 -19.66882  -21.511229 ... -14.686564  -9.561094 -14.915371]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.208356 -19.908045 -22.010862 ... -12.123962 -11.411202 -15.495105]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.06436  -22.460161 -23.290894 ... -13.810817 -13.495949 -18.433132]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.407601 -16.103561 -18.186934 ... -12.530688 -11.467586 -15.051501]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.154478  -10.773704  -11.45372   ...  -7.8351655  -6.940525
  -9.471658 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.345279  -9.550305  -9.215589  ... -7.35497   -6.2349386 -9.082229 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.059692 -17.515202 -19.473696 ... -13.32714  -13.000225 -17.385824]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.853927  -9.417185  -9.818268  ... -7.56705   -6.797821  -9.2694645]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.470445 -10.500851 -11.195634 ...  -8.290597  -7.528887 -10.275712]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.575862   -9.860738  -10.059921  ...  -7.5261006  -6.7495728
  -9.807565 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.971343  -9.727591 -10.38561  ...  -8.355512  -7.761947 -10.339701]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.937206  -9.68171   -9.747964 ...  -9.03202   -8.149738 -10.78419 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.56766   -8.647437  -9.481007  ... -7.230117  -6.4676156 -9.046944 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.2614594  -6.017709   -4.01456    ... -2.538673   -1.343027
 -0.29076535]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.189106  -16.723421  -17.433561  ... -14.278392  -14.061126
 -13.7930565]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.70481  -13.602265 -13.31118  ... -12.330173 -12.779114 -13.304597]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.376771 -14.3174   -14.204256 ... -12.524408 -12.220399 -13.23407 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.622474 -17.541563 -18.45575  ... -15.795818 -13.68112  -16.958645]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.380141  -10.3613405 -10.459988  ...  -6.8525047  -5.9201016
  -8.494826 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.21056  -15.872177 -15.979193 ... -14.015997 -10.205236 -13.370808]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.4298344 -8.359521  -9.356103  ... -6.556538  -6.123466  -9.260665 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.8375216 -11.6788845 -11.855057  ...  -6.7919073  -6.190464
  -9.306081 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.657811 -13.789847 -16.231682 ... -12.288597 -10.085818 -15.537539]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.771423  -19.634079  -20.91004   ... -14.060814  -13.7756195
 -17.31107  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.707077 -20.796175 -24.979856 ... -21.380922 -18.227198 -25.497995]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.790138 -14.978334 -16.99328  ... -15.286077 -14.078514 -17.368385]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.982258  -18.95541   -13.89992   ... -13.957264  -10.2100525
  -8.180259 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.8038225 -6.8725524 -3.9698    ... -3.5435216 -2.4126933 -1.3739785]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.475098 -11.917043 -11.438107 ...  -8.320286  -8.96328   -9.814563]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.015009  -13.58165   -12.578439  ...  -6.894612   -7.7799106
  -8.508437 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.082611  -10.409024  -10.073786  ...  -5.2627482  -6.3300786
  -7.862226 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.678049  -10.4020195 -10.5529    ...  -5.1211653  -6.1280847
  -7.8565073]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.532106  -10.756004  -11.57039   ...  -7.7644825  -6.940027
  -9.174966 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.472978 -13.332643 -12.49851  ...  -9.035296  -6.943619  -9.75858 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.378641  -8.584375  -7.8302107 ... -4.117287  -3.7252767 -5.9455366]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.34377   -16.03739   -17.868546  ... -14.94252   -15.1999855
 -18.85039  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.477879 -24.171982 -24.126286 ... -19.304752 -18.54441  -21.816622]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.550854 -13.51191  -14.454733 ...  -8.880686  -9.130664 -12.777418]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.476378  -9.499306  -8.854959 ...  -9.730551  -8.23424  -10.198997]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.531376 -15.251695 -13.711758 ... -11.16591   -9.268581 -10.307095]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.568898 -10.362127 -10.971663 ...  -8.540176  -7.742962 -10.707098]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.386899 -15.713565 -14.956614 ... -10.106887 -11.05186  -12.8582  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.6337175 -6.997305  -4.5145764 ... -3.3928483 -2.3767738 -1.2814418]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.09334  -13.500344 -12.597673 ... -16.371984 -15.473736 -16.209736]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.77746  -13.80466  -16.488272 ... -17.194473 -15.774511 -19.87206 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.019958 -13.834505 -13.664107 ... -10.063818  -9.631132 -11.460957]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.901565  -6.4479384 -8.34047   ... -1.9298553 -3.0873203 -3.023288 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.303673  -10.353358  -12.929473  ...  -6.161526   -7.6550937
  -7.4010243]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.369304  -13.4832115 -13.27603   ... -11.970571  -12.16188
 -12.63509  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.907627 -16.14526  -15.746335 ... -11.705882 -12.927716 -15.02972 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.6376944 -10.583523  -11.759478  ...  -7.87959    -7.0547943
 -10.875518 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.941286 -15.733571 -15.029286 ...  -8.550878 -11.712385 -12.090706]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.115567  -8.250597  -9.095846  ... -2.5365562 -4.364606  -5.701342 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

PairwiseArrays with keys: connectivities, distances

{'cellxgene_census/dkd_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.6050132734327139, 'macro': 0.45858384601691754, 'micro': 0.6050132734327139, 'weighted': 0.5752358078815335}}, 'cellxgene_census/dkd_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5608184918529746, 'macro': 0.49302410982269285, 'micro': 0.5608184918529746, 'weighted': 0.5370188034467204}}, 'cellxgene_census/dkd_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5941644562334217, 'macro': 0.5355514243377841, 'micro': 0.5941644562334217, 'weighted': 0.5827613925424003}}, 'cellxgene_census/dkd_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5985221674876847, 'macro': 0.5, 'micro': 0.5985221674876847, 'weighted': 0.5985221674876847}}, 'cellxgene_census/gtex_v9_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5690731903254497, 'macro': 0.3561412506114705, 'micro': 0.5690731903254497, 'weighted': 0.5111263506144524}}, 'cellxgene_census/gtex_v9_cls': {'cell_type_ontology_term_id': {'accuracy': 0.47340980187695514, 'macro': 0.4771516389245344, 'micro': 0.47340980187695514, 'weighted': 0.4105919407683359}}, 'cellxgene_census/gtex_v9_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.49930483142161974, 'macro': 0.45026649672378827, 'micro': 0.49930483142161974, 'weighted': 0.46767738060420655}}, 'cellxgene_census/gtex_v9_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.49930483142161974, 'macro': 0.45026649672378827, 'micro': 0.49930483142161974, 'weighted': 0.46767738060420655}}}
doing  cellxgene_census/hypomap

/lustre/fswork/projects/rech/xeg/uat95fg/scdataloader/scdataloader/utils.py:427: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  organismdf = pd.concat(organismdf)

predict epoch start

  0%|          | 0/6015 [00:00<?, ?it/s]

  0%|          | 1/6015 [00:06<11:20:05,  6.79s/it]

  0%|          | 2/6015 [00:07<5:03:59,  3.03s/it]

  0%|          | 3/6015 [00:07<3:03:40,  1.83s/it]

  0%|          | 4/6015 [00:08<2:07:05,  1.27s/it]

  0%|          | 5/6015 [00:08<1:35:51,  1.04it/s]

  0%|          | 6/6015 [00:08<1:16:58,  1.30it/s]

  0%|          | 7/6015 [00:09<1:05:08,  1.54it/s]

  0%|          | 8/6015 [00:09<57:15,  1.75it/s]

  0%|          | 9/6015 [00:10<52:20,  1.91it/s]

  0%|          | 10/6015 [00:10<48:41,  2.06it/s]

  0%|          | 11/6015 [00:10<46:09,  2.17it/s]

  0%|          | 12/6015 [00:11<44:24,  2.25it/s]

  0%|          | 13/6015 [00:11<43:09,  2.32it/s]

  0%|          | 14/6015 [00:12<42:20,  2.36it/s]

  0%|          | 15/6015 [00:12<41:46,  2.39it/s]

  0%|          | 16/6015 [00:12<41:19,  2.42it/s]

  0%|          | 17/6015 [00:13<41:04,  2.43it/s]

  0%|          | 18/6015 [00:13<40:53,  2.44it/s]

  0%|          | 19/6015 [00:14<40:47,  2.45it/s]

  0%|          | 20/6015 [00:14<40:45,  2.45it/s]

  0%|          | 21/6015 [00:14<40:38,  2.46it/s]

  0%|          | 22/6015 [00:15<40:36,  2.46it/s]

  0%|          | 23/6015 [00:15<40:33,  2.46it/s]

  0%|          | 24/6015 [00:16<40:34,  2.46it/s]

  0%|          | 25/6015 [00:16<40:33,  2.46it/s]

  0%|          | 26/6015 [00:16<40:31,  2.46it/s]

  0%|          | 27/6015 [00:17<40:31,  2.46it/s]

  0%|          | 28/6015 [00:17<40:33,  2.46it/s]

  0%|          | 29/6015 [00:18<40:34,  2.46it/s]

  0%|          | 30/6015 [00:18<40:34,  2.46it/s]

  1%|          | 31/6015 [00:18<40:33,  2.46it/s]

  1%|          | 32/6015 [00:19<40:31,  2.46it/s]

  1%|          | 33/6015 [00:19<40:31,  2.46it/s]

  1%|          | 34/6015 [00:20<40:30,  2.46it/s]

  1%|          | 35/6015 [00:20<40:30,  2.46it/s]

  1%|          | 36/6015 [00:20<40:29,  2.46it/s]

  1%|          | 37/6015 [00:21<40:30,  2.46it/s]

  1%|          | 38/6015 [00:21<40:28,  2.46it/s]

  1%|          | 39/6015 [00:22<40:26,  2.46it/s]

  1%|          | 40/6015 [00:22<40:30,  2.46it/s]

  1%|          | 41/6015 [00:23<40:29,  2.46it/s]

  1%|          | 42/6015 [00:23<40:29,  2.46it/s]

  1%|          | 43/6015 [00:23<40:28,  2.46it/s]

  1%|          | 44/6015 [00:24<40:26,  2.46it/s]

  1%|          | 45/6015 [00:24<40:26,  2.46it/s]

  1%|          | 46/6015 [00:25<40:24,  2.46it/s]

  1%|          | 47/6015 [00:25<40:27,  2.46it/s]

  1%|          | 48/6015 [00:25<40:26,  2.46it/s]

  1%|          | 49/6015 [00:26<40:27,  2.46it/s]

  1%|          | 50/6015 [00:26<40:25,  2.46it/s]

  1%|          | 51/6015 [00:27<40:26,  2.46it/s]

  1%|          | 52/6015 [00:27<40:25,  2.46it/s]

  1%|          | 53/6015 [00:27<40:24,  2.46it/s]

  1%|          | 54/6015 [00:28<40:26,  2.46it/s]

  1%|          | 55/6015 [00:28<40:29,  2.45it/s]

  1%|          | 56/6015 [00:29<40:28,  2.45it/s]

  1%|          | 57/6015 [00:29<40:23,  2.46it/s]

  1%|          | 58/6015 [00:29<40:24,  2.46it/s]

  1%|          | 59/6015 [00:30<40:25,  2.46it/s]

  1%|          | 60/6015 [00:30<40:24,  2.46it/s]

  1%|          | 61/6015 [00:31<40:23,  2.46it/s]

  1%|          | 62/6015 [00:31<40:21,  2.46it/s]

  1%|          | 63/6015 [00:31<40:20,  2.46it/s]

  1%|          | 64/6015 [00:32<40:25,  2.45it/s]

  1%|          | 65/6015 [00:32<40:24,  2.45it/s]

  1%|          | 66/6015 [00:33<40:22,  2.46it/s]

  1%|          | 67/6015 [00:33<40:23,  2.45it/s]

  1%|          | 68/6015 [00:34<40:23,  2.45it/s]

  1%|          | 69/6015 [00:34<40:25,  2.45it/s]

  1%|          | 70/6015 [00:34<40:23,  2.45it/s]

  1%|          | 71/6015 [00:35<40:23,  2.45it/s]

  1%|          | 72/6015 [00:35<40:23,  2.45it/s]

  1%|          | 73/6015 [00:36<40:22,  2.45it/s]

  1%|          | 74/6015 [00:36<40:22,  2.45it/s]

  1%|          | 75/6015 [00:36<40:24,  2.45it/s]

  1%|▏         | 76/6015 [00:37<40:25,  2.45it/s]

  1%|▏         | 77/6015 [00:37<40:24,  2.45it/s]

  1%|▏         | 78/6015 [00:38<40:23,  2.45it/s]

  1%|▏         | 79/6015 [00:38<40:22,  2.45it/s]

  1%|▏         | 80/6015 [00:38<40:22,  2.45it/s]

  1%|▏         | 81/6015 [00:39<40:23,  2.45it/s]

  1%|▏         | 82/6015 [00:39<40:22,  2.45it/s]

  1%|▏         | 83/6015 [00:40<40:24,  2.45it/s]

  1%|▏         | 84/6015 [00:40<40:24,  2.45it/s]

  1%|▏         | 85/6015 [00:40<40:23,  2.45it/s]

  1%|▏         | 86/6015 [00:41<40:22,  2.45it/s]

  1%|▏         | 87/6015 [00:41<40:25,  2.44it/s]

  1%|▏         | 88/6015 [00:42<40:23,  2.45it/s]

  1%|▏         | 89/6015 [00:42<40:23,  2.44it/s]

  1%|▏         | 90/6015 [00:42<40:22,  2.45it/s]

  2%|▏         | 91/6015 [00:43<40:22,  2.45it/s]

  2%|▏         | 92/6015 [00:43<40:22,  2.44it/s]

  2%|▏         | 93/6015 [00:44<40:20,  2.45it/s]

  2%|▏         | 94/6015 [00:44<40:17,  2.45it/s]

  2%|▏         | 95/6015 [00:45<40:18,  2.45it/s]

  2%|▏         | 96/6015 [00:45<40:19,  2.45it/s]

  2%|▏         | 97/6015 [00:45<40:21,  2.44it/s]

  2%|▏         | 98/6015 [00:46<40:21,  2.44it/s]

  2%|▏         | 99/6015 [00:46<40:21,  2.44it/s]

  2%|▏         | 100/6015 [00:47<40:20,  2.44it/s]

  2%|▏         | 101/6015 [00:47<40:18,  2.45it/s]

  2%|▏         | 102/6015 [00:47<40:18,  2.44it/s]

  2%|▏         | 103/6015 [00:48<40:19,  2.44it/s]

  2%|▏         | 104/6015 [00:48<40:17,  2.45it/s]

  2%|▏         | 105/6015 [00:49<40:20,  2.44it/s]

  2%|▏         | 106/6015 [00:49<40:17,  2.44it/s]

  2%|▏         | 107/6015 [00:49<40:14,  2.45it/s]

  2%|▏         | 108/6015 [00:50<40:14,  2.45it/s]

  2%|▏         | 109/6015 [00:50<40:12,  2.45it/s]

  2%|▏         | 110/6015 [00:51<40:17,  2.44it/s]

  2%|▏         | 111/6015 [00:51<40:15,  2.44it/s]

  2%|▏         | 112/6015 [00:51<40:15,  2.44it/s]

  2%|▏         | 113/6015 [00:52<40:14,  2.44it/s]

  2%|▏         | 114/6015 [00:52<40:15,  2.44it/s]

  2%|▏         | 115/6015 [00:53<40:14,  2.44it/s]

  2%|▏         | 116/6015 [00:53<40:13,  2.44it/s]

  2%|▏         | 117/6015 [00:54<40:16,  2.44it/s]

  2%|▏         | 118/6015 [00:54<40:13,  2.44it/s]

  2%|▏         | 119/6015 [00:54<40:15,  2.44it/s]

  2%|▏         | 120/6015 [00:55<40:15,  2.44it/s]

  2%|▏         | 121/6015 [00:55<40:12,  2.44it/s]

  2%|▏         | 122/6015 [00:56<40:13,  2.44it/s]

  2%|▏         | 123/6015 [00:56<40:11,  2.44it/s]

  2%|▏         | 124/6015 [00:56<40:10,  2.44it/s]

  2%|▏         | 125/6015 [00:57<40:11,  2.44it/s]

  2%|▏         | 126/6015 [00:57<40:06,  2.45it/s]

  2%|▏         | 127/6015 [00:58<40:04,  2.45it/s]

  2%|▏         | 128/6015 [00:58<40:03,  2.45it/s]

  2%|▏         | 129/6015 [00:58<40:05,  2.45it/s]

  2%|▏         | 130/6015 [00:59<40:08,  2.44it/s]

  2%|▏         | 131/6015 [00:59<40:05,  2.45it/s]

  2%|▏         | 132/6015 [01:00<40:08,  2.44it/s]

  2%|▏         | 133/6015 [01:00<40:05,  2.45it/s]

  2%|▏         | 134/6015 [01:00<40:04,  2.45it/s]

  2%|▏         | 135/6015 [01:01<40:06,  2.44it/s]

  2%|▏         | 136/6015 [01:01<40:05,  2.44it/s]

  2%|▏         | 137/6015 [01:02<40:03,  2.45it/s]

  2%|▏         | 138/6015 [01:02<40:00,  2.45it/s]

  2%|▏         | 139/6015 [01:03<39:59,  2.45it/s]

  2%|▏         | 140/6015 [01:03<40:03,  2.44it/s]

  2%|▏         | 141/6015 [01:03<40:01,  2.45it/s]

  2%|▏         | 142/6015 [01:04<39:59,  2.45it/s]

  2%|▏         | 143/6015 [01:04<40:00,  2.45it/s]

  2%|▏         | 144/6015 [01:05<40:01,  2.44it/s]

  2%|▏         | 145/6015 [01:05<39:59,  2.45it/s]

  2%|▏         | 146/6015 [01:05<40:01,  2.44it/s]

  2%|▏         | 147/6015 [01:06<40:02,  2.44it/s]

  2%|▏         | 148/6015 [01:06<40:02,  2.44it/s]

  2%|▏         | 149/6015 [01:07<40:05,  2.44it/s]

  2%|▏         | 150/6015 [01:07<40:01,  2.44it/s]

  3%|▎         | 151/6015 [01:07<39:59,  2.44it/s]

  3%|▎         | 152/6015 [01:08<40:00,  2.44it/s]

  3%|▎         | 153/6015 [01:08<39:57,  2.44it/s]

  3%|▎         | 154/6015 [01:09<39:57,  2.44it/s]

  3%|▎         | 155/6015 [01:09<39:55,  2.45it/s]

  3%|▎         | 156/6015 [01:09<39:57,  2.44it/s]

  3%|▎         | 157/6015 [01:10<39:56,  2.44it/s]

  3%|▎         | 158/6015 [01:10<39:56,  2.44it/s]

  3%|▎         | 159/6015 [01:11<39:55,  2.44it/s]

  3%|▎         | 160/6015 [01:11<39:55,  2.44it/s]

  3%|▎         | 161/6015 [01:12<39:56,  2.44it/s]

  3%|▎         | 162/6015 [01:12<39:58,  2.44it/s]

  3%|▎         | 163/6015 [01:12<39:55,  2.44it/s]

  3%|▎         | 164/6015 [01:13<39:54,  2.44it/s]

  3%|▎         | 165/6015 [01:13<39:55,  2.44it/s]

  3%|▎         | 166/6015 [01:14<39:56,  2.44it/s]

  3%|▎         | 167/6015 [01:14<39:57,  2.44it/s]

  3%|▎         | 168/6015 [01:14<39:58,  2.44it/s]

  3%|▎         | 169/6015 [01:15<39:55,  2.44it/s]

  3%|▎         | 170/6015 [01:15<39:55,  2.44it/s]

  3%|▎         | 171/6015 [01:16<39:52,  2.44it/s]

  3%|▎         | 172/6015 [01:16<39:53,  2.44it/s]

  3%|▎         | 173/6015 [01:16<39:51,  2.44it/s]

  3%|▎         | 174/6015 [01:17<39:50,  2.44it/s]

  3%|▎         | 175/6015 [01:17<39:48,  2.45it/s]

  3%|▎         | 176/6015 [01:18<39:47,  2.45it/s]

  3%|▎         | 177/6015 [01:18<39:50,  2.44it/s]

  3%|▎         | 178/6015 [01:19<39:50,  2.44it/s]

  3%|▎         | 179/6015 [01:19<39:49,  2.44it/s]

  3%|▎         | 180/6015 [01:19<39:47,  2.44it/s]

  3%|▎         | 181/6015 [01:20<39:47,  2.44it/s]

  3%|▎         | 182/6015 [01:20<39:46,  2.44it/s]

  3%|▎         | 183/6015 [01:21<39:49,  2.44it/s]

  3%|▎         | 184/6015 [01:21<39:50,  2.44it/s]

  3%|▎         | 185/6015 [01:21<39:49,  2.44it/s]

  3%|▎         | 186/6015 [01:22<39:51,  2.44it/s]

  3%|▎         | 187/6015 [01:22<39:51,  2.44it/s]

  3%|▎         | 188/6015 [01:23<39:52,  2.44it/s]

  3%|▎         | 189/6015 [01:23<39:48,  2.44it/s]

  3%|▎         | 190/6015 [01:23<39:50,  2.44it/s]

  3%|▎         | 191/6015 [01:24<39:46,  2.44it/s]

  3%|▎         | 192/6015 [01:24<39:48,  2.44it/s]

  3%|▎         | 193/6015 [01:25<39:44,  2.44it/s]

  3%|▎         | 194/6015 [01:25<39:46,  2.44it/s]

  3%|▎         | 195/6015 [01:25<39:49,  2.44it/s]

  3%|▎         | 196/6015 [01:26<39:49,  2.44it/s]

  3%|▎         | 197/6015 [01:26<39:53,  2.43it/s]

  3%|▎         | 198/6015 [01:27<39:51,  2.43it/s]

  3%|▎         | 199/6015 [01:27<39:50,  2.43it/s]

  3%|▎         | 200/6015 [01:28<39:50,  2.43it/s]

  3%|▎         | 201/6015 [01:28<39:49,  2.43it/s]

  3%|▎         | 202/6015 [01:28<39:48,  2.43it/s]

  3%|▎         | 203/6015 [01:29<39:45,  2.44it/s]

  3%|▎         | 204/6015 [01:29<39:47,  2.43it/s]

  3%|▎         | 205/6015 [01:30<39:45,  2.44it/s]

  3%|▎         | 206/6015 [01:30<39:47,  2.43it/s]

  3%|▎         | 207/6015 [01:30<39:44,  2.44it/s]

  3%|▎         | 208/6015 [01:31<39:45,  2.43it/s]

  3%|▎         | 209/6015 [01:31<39:43,  2.44it/s]

  3%|▎         | 210/6015 [01:32<39:43,  2.44it/s]

  4%|▎         | 211/6015 [01:32<39:42,  2.44it/s]

  4%|▎         | 212/6015 [01:32<39:42,  2.44it/s]

  4%|▎         | 213/6015 [01:33<39:43,  2.43it/s]

  4%|▎         | 214/6015 [01:33<39:41,  2.44it/s]

  4%|▎         | 215/6015 [01:34<39:42,  2.43it/s]

  4%|▎         | 216/6015 [01:34<39:40,  2.44it/s]

  4%|▎         | 217/6015 [01:35<39:40,  2.44it/s]

  4%|▎         | 218/6015 [01:35<39:41,  2.43it/s]

  4%|▎         | 219/6015 [01:35<39:39,  2.44it/s]

  4%|▎         | 220/6015 [01:36<39:39,  2.44it/s]

  4%|▎         | 221/6015 [01:36<39:37,  2.44it/s]

  4%|▎         | 222/6015 [01:37<39:39,  2.43it/s]

  4%|▎         | 223/6015 [01:37<39:39,  2.43it/s]

  4%|▎         | 224/6015 [01:37<39:40,  2.43it/s]

  4%|▎         | 225/6015 [01:38<39:40,  2.43it/s]

  4%|▍         | 226/6015 [01:38<39:40,  2.43it/s]

  4%|▍         | 227/6015 [01:39<39:37,  2.43it/s]

  4%|▍         | 228/6015 [01:39<39:35,  2.44it/s]

  4%|▍         | 229/6015 [01:39<39:34,  2.44it/s]

  4%|▍         | 230/6015 [01:40<39:35,  2.43it/s]

  4%|▍         | 231/6015 [01:40<39:35,  2.43it/s]

  4%|▍         | 232/6015 [01:41<39:36,  2.43it/s]

  4%|▍         | 233/6015 [01:41<39:34,  2.44it/s]

  4%|▍         | 234/6015 [01:41<39:35,  2.43it/s]

  4%|▍         | 235/6015 [01:42<39:35,  2.43it/s]

  4%|▍         | 236/6015 [01:42<39:34,  2.43it/s]

  4%|▍         | 237/6015 [01:43<39:36,  2.43it/s]

  4%|▍         | 238/6015 [01:43<39:36,  2.43it/s]

  4%|▍         | 239/6015 [01:44<39:36,  2.43it/s]

  4%|▍         | 240/6015 [01:44<39:36,  2.43it/s]

  4%|▍         | 241/6015 [01:44<39:34,  2.43it/s]

  4%|▍         | 242/6015 [01:45<39:34,  2.43it/s]

  4%|▍         | 243/6015 [01:45<39:32,  2.43it/s]

  4%|▍         | 244/6015 [01:46<39:32,  2.43it/s]

  4%|▍         | 245/6015 [01:46<39:32,  2.43it/s]

  4%|▍         | 246/6015 [01:46<39:34,  2.43it/s]

  4%|▍         | 247/6015 [01:47<39:31,  2.43it/s]

  4%|▍         | 248/6015 [01:47<39:35,  2.43it/s]

  4%|▍         | 249/6015 [01:48<39:33,  2.43it/s]

  4%|▍         | 250/6015 [01:48<39:33,  2.43it/s]

  4%|▍         | 251/6015 [01:48<39:36,  2.43it/s]

  4%|▍         | 252/6015 [01:49<39:33,  2.43it/s]

  4%|▍         | 253/6015 [01:49<39:32,  2.43it/s]

  4%|▍         | 254/6015 [01:50<39:29,  2.43it/s]

  4%|▍         | 255/6015 [01:50<39:32,  2.43it/s]

  4%|▍         | 256/6015 [01:51<39:30,  2.43it/s]

  4%|▍         | 257/6015 [01:51<39:29,  2.43it/s]

  4%|▍         | 258/6015 [01:51<39:26,  2.43it/s]

  4%|▍         | 259/6015 [01:52<39:26,  2.43it/s]

  4%|▍         | 260/6015 [01:52<39:26,  2.43it/s]

  4%|▍         | 261/6015 [01:53<39:26,  2.43it/s]

  4%|▍         | 262/6015 [01:53<39:27,  2.43it/s]

  4%|▍         | 263/6015 [01:53<39:28,  2.43it/s]

  4%|▍         | 264/6015 [01:54<39:31,  2.43it/s]

  4%|▍         | 265/6015 [01:54<39:27,  2.43it/s]

  4%|▍         | 266/6015 [01:55<39:24,  2.43it/s]

  4%|▍         | 267/6015 [01:55<39:22,  2.43it/s]

  4%|▍         | 268/6015 [01:55<39:25,  2.43it/s]

  4%|▍         | 269/6015 [01:56<39:22,  2.43it/s]

  4%|▍         | 270/6015 [01:56<39:20,  2.43it/s]

  5%|▍         | 271/6015 [01:57<39:20,  2.43it/s]

  5%|▍         | 272/6015 [01:57<39:21,  2.43it/s]

  5%|▍         | 273/6015 [01:58<39:22,  2.43it/s]

  5%|▍         | 274/6015 [01:58<39:21,  2.43it/s]

  5%|▍         | 275/6015 [01:58<39:22,  2.43it/s]

  5%|▍         | 276/6015 [01:59<39:22,  2.43it/s]

  5%|▍         | 277/6015 [01:59<39:26,  2.42it/s]

  5%|▍         | 278/6015 [02:00<39:24,  2.43it/s]

  5%|▍         | 279/6015 [02:00<39:25,  2.42it/s]

  5%|▍         | 280/6015 [02:00<39:23,  2.43it/s]

  5%|▍         | 281/6015 [02:01<39:21,  2.43it/s]

  5%|▍         | 282/6015 [02:01<39:21,  2.43it/s]

  5%|▍         | 283/6015 [02:02<39:22,  2.43it/s]

  5%|▍         | 284/6015 [02:02<39:21,  2.43it/s]

  5%|▍         | 285/6015 [02:02<39:20,  2.43it/s]

  5%|▍         | 286/6015 [02:03<39:20,  2.43it/s]

  5%|▍         | 287/6015 [02:03<39:20,  2.43it/s]

  5%|▍         | 288/6015 [02:04<39:18,  2.43it/s]

  5%|▍         | 289/6015 [02:04<39:18,  2.43it/s]

  5%|▍         | 290/6015 [02:05<39:17,  2.43it/s]

  5%|▍         | 291/6015 [02:05<39:21,  2.42it/s]

  5%|▍         | 292/6015 [02:05<39:23,  2.42it/s]

  5%|▍         | 293/6015 [02:06<39:25,  2.42it/s]

  5%|▍         | 294/6015 [02:06<39:22,  2.42it/s]

  5%|▍         | 295/6015 [02:07<39:21,  2.42it/s]

  5%|▍         | 296/6015 [02:07<39:19,  2.42it/s]

  5%|▍         | 297/6015 [02:07<39:20,  2.42it/s]

  5%|▍         | 298/6015 [02:08<39:23,  2.42it/s]

  5%|▍         | 299/6015 [02:08<39:20,  2.42it/s]

  5%|▍         | 300/6015 [02:09<39:20,  2.42it/s]

  5%|▌         | 301/6015 [02:09<39:18,  2.42it/s]

  5%|▌         | 302/6015 [02:10<39:17,  2.42it/s]

  5%|▌         | 303/6015 [02:10<39:16,  2.42it/s]

  5%|▌         | 304/6015 [02:10<39:16,  2.42it/s]

  5%|▌         | 305/6015 [02:11<39:14,  2.43it/s]

  5%|▌         | 306/6015 [02:11<39:15,  2.42it/s]

  5%|▌         | 307/6015 [02:12<39:14,  2.42it/s]

  5%|▌         | 308/6015 [02:12<39:14,  2.42it/s]

  5%|▌         | 309/6015 [02:12<39:13,  2.42it/s]

  5%|▌         | 310/6015 [02:13<39:15,  2.42it/s]

  5%|▌         | 311/6015 [02:13<39:12,  2.42it/s]

  5%|▌         | 312/6015 [02:14<39:13,  2.42it/s]

  5%|▌         | 313/6015 [02:14<39:15,  2.42it/s]

  5%|▌         | 314/6015 [02:14<39:15,  2.42it/s]

  5%|▌         | 315/6015 [02:15<39:18,  2.42it/s]

  5%|▌         | 316/6015 [02:15<39:13,  2.42it/s]

  5%|▌         | 317/6015 [02:16<39:17,  2.42it/s]

  5%|▌         | 318/6015 [02:16<39:16,  2.42it/s]

  5%|▌         | 319/6015 [02:17<39:14,  2.42it/s]

  5%|▌         | 320/6015 [02:17<39:14,  2.42it/s]

  5%|▌         | 321/6015 [02:17<39:13,  2.42it/s]

  5%|▌         | 322/6015 [02:18<39:10,  2.42it/s]

  5%|▌         | 323/6015 [02:18<39:11,  2.42it/s]

  5%|▌         | 324/6015 [02:19<39:12,  2.42it/s]

  5%|▌         | 325/6015 [02:19<39:12,  2.42it/s]

  5%|▌         | 326/6015 [02:19<39:11,  2.42it/s]

  5%|▌         | 327/6015 [02:20<39:09,  2.42it/s]

  5%|▌         | 328/6015 [02:20<39:13,  2.42it/s]

  5%|▌         | 329/6015 [02:21<39:13,  2.42it/s]

  5%|▌         | 330/6015 [02:21<39:17,  2.41it/s]

  6%|▌         | 331/6015 [02:21<39:12,  2.42it/s]

  6%|▌         | 332/6015 [02:22<39:13,  2.42it/s]

  6%|▌         | 333/6015 [02:22<39:11,  2.42it/s]

  6%|▌         | 334/6015 [02:23<39:08,  2.42it/s]

  6%|▌         | 335/6015 [02:23<39:05,  2.42it/s]

  6%|▌         | 336/6015 [02:24<39:08,  2.42it/s]

  6%|▌         | 337/6015 [02:24<39:08,  2.42it/s]

  6%|▌         | 338/6015 [02:24<39:07,  2.42it/s]

  6%|▌         | 339/6015 [02:25<39:08,  2.42it/s]

  6%|▌         | 340/6015 [02:25<39:09,  2.42it/s]

  6%|▌         | 341/6015 [02:26<39:10,  2.41it/s]

  6%|▌         | 342/6015 [02:26<39:08,  2.42it/s]

  6%|▌         | 343/6015 [02:26<39:06,  2.42it/s]

  6%|▌         | 344/6015 [02:27<39:02,  2.42it/s]

  6%|▌         | 345/6015 [02:27<39:02,  2.42it/s]

  6%|▌         | 346/6015 [02:28<39:01,  2.42it/s]

  6%|▌         | 347/6015 [02:28<39:01,  2.42it/s]

  6%|▌         | 348/6015 [02:29<39:00,  2.42it/s]

  6%|▌         | 349/6015 [02:29<39:03,  2.42it/s]

  6%|▌         | 350/6015 [02:29<39:02,  2.42it/s]

  6%|▌         | 351/6015 [02:30<39:03,  2.42it/s]

  6%|▌         | 352/6015 [02:30<39:03,  2.42it/s]

  6%|▌         | 353/6015 [02:31<39:00,  2.42it/s]

  6%|▌         | 354/6015 [02:31<38:58,  2.42it/s]

  6%|▌         | 355/6015 [02:31<38:59,  2.42it/s]

  6%|▌         | 356/6015 [02:32<39:00,  2.42it/s]

  6%|▌         | 357/6015 [02:32<39:01,  2.42it/s]

  6%|▌         | 358/6015 [02:33<39:04,  2.41it/s]

  6%|▌         | 359/6015 [02:33<39:03,  2.41it/s]

  6%|▌         | 360/6015 [02:33<39:07,  2.41it/s]

  6%|▌         | 361/6015 [02:34<39:05,  2.41it/s]

  6%|▌         | 362/6015 [02:34<39:04,  2.41it/s]

  6%|▌         | 363/6015 [02:35<39:03,  2.41it/s]

  6%|▌         | 364/6015 [02:35<39:03,  2.41it/s]

  6%|▌         | 365/6015 [02:36<39:01,  2.41it/s]

  6%|▌         | 366/6015 [02:36<38:59,  2.41it/s]

  6%|▌         | 367/6015 [02:36<38:57,  2.42it/s]

  6%|▌         | 368/6015 [02:37<38:58,  2.41it/s]

  6%|▌         | 369/6015 [02:37<38:59,  2.41it/s]

  6%|▌         | 370/6015 [02:38<39:00,  2.41it/s]

  6%|▌         | 371/6015 [02:38<39:15,  2.40it/s]

  6%|▌         | 372/6015 [02:38<39:09,  2.40it/s]

  6%|▌         | 373/6015 [02:39<39:02,  2.41it/s]

  6%|▌         | 374/6015 [02:39<39:00,  2.41it/s]

  6%|▌         | 375/6015 [02:40<38:58,  2.41it/s]

  6%|▋         | 376/6015 [02:40<38:58,  2.41it/s]

  6%|▋         | 377/6015 [02:41<38:58,  2.41it/s]

  6%|▋         | 378/6015 [02:41<38:55,  2.41it/s]

  6%|▋         | 379/6015 [02:41<38:57,  2.41it/s]

  6%|▋         | 380/6015 [02:42<38:56,  2.41it/s]

  6%|▋         | 381/6015 [02:42<39:00,  2.41it/s]

  6%|▋         | 382/6015 [02:43<38:59,  2.41it/s]

  6%|▋         | 383/6015 [02:43<38:55,  2.41it/s]

  6%|▋         | 384/6015 [02:43<38:54,  2.41it/s]

  6%|▋         | 385/6015 [02:44<38:53,  2.41it/s]

  6%|▋         | 386/6015 [02:44<38:54,  2.41it/s]

  6%|▋         | 387/6015 [02:45<38:53,  2.41it/s]

  6%|▋         | 388/6015 [02:45<38:58,  2.41it/s]

  6%|▋         | 389/6015 [02:46<38:54,  2.41it/s]

  6%|▋         | 390/6015 [02:46<38:52,  2.41it/s]

  7%|▋         | 391/6015 [02:46<38:47,  2.42it/s]

  7%|▋         | 392/6015 [02:47<38:48,  2.41it/s]

  7%|▋         | 393/6015 [02:47<38:48,  2.41it/s]

  7%|▋         | 394/6015 [02:48<38:50,  2.41it/s]

  7%|▋         | 395/6015 [02:48<38:49,  2.41it/s]

  7%|▋         | 396/6015 [02:48<38:48,  2.41it/s]

  7%|▋         | 397/6015 [02:49<38:49,  2.41it/s]

  7%|▋         | 398/6015 [02:49<38:50,  2.41it/s]

  7%|▋         | 399/6015 [02:50<38:48,  2.41it/s]

  7%|▋         | 400/6015 [02:50<38:50,  2.41it/s]

  7%|▋         | 401/6015 [02:50<38:47,  2.41it/s]

  7%|▋         | 402/6015 [02:51<38:50,  2.41it/s]

  7%|▋         | 403/6015 [02:51<38:48,  2.41it/s]

  7%|▋         | 404/6015 [02:52<38:46,  2.41it/s]

  7%|▋         | 405/6015 [02:52<38:51,  2.41it/s]

  7%|▋         | 406/6015 [02:53<38:48,  2.41it/s]

  7%|▋         | 407/6015 [02:53<38:46,  2.41it/s]

  7%|▋         | 408/6015 [02:53<38:45,  2.41it/s]

  7%|▋         | 409/6015 [02:54<38:44,  2.41it/s]

  7%|▋         | 410/6015 [02:54<38:43,  2.41it/s]

  7%|▋         | 411/6015 [02:55<38:43,  2.41it/s]

  7%|▋         | 412/6015 [02:55<38:42,  2.41it/s]

  7%|▋         | 413/6015 [02:55<38:44,  2.41it/s]

  7%|▋         | 414/6015 [02:56<38:46,  2.41it/s]

  7%|▋         | 415/6015 [02:56<38:45,  2.41it/s]

  7%|▋         | 416/6015 [02:57<38:45,  2.41it/s]

  7%|▋         | 417/6015 [02:57<38:44,  2.41it/s]

  7%|▋         | 418/6015 [02:58<38:43,  2.41it/s]

  7%|▋         | 419/6015 [02:58<38:43,  2.41it/s]

  7%|▋         | 420/6015 [02:58<38:42,  2.41it/s]

  7%|▋         | 421/6015 [02:59<38:43,  2.41it/s]

  7%|▋         | 422/6015 [02:59<38:43,  2.41it/s]

  7%|▋         | 423/6015 [03:00<38:43,  2.41it/s]

  7%|▋         | 424/6015 [03:00<38:40,  2.41it/s]

  7%|▋         | 425/6015 [03:00<38:39,  2.41it/s]

  7%|▋         | 426/6015 [03:01<38:49,  2.40it/s]

  7%|▋         | 427/6015 [03:01<38:44,  2.40it/s]

  7%|▋         | 428/6015 [03:02<38:42,  2.41it/s]

  7%|▋         | 429/6015 [03:02<38:39,  2.41it/s]

  7%|▋         | 430/6015 [03:03<38:40,  2.41it/s]

  7%|▋         | 431/6015 [03:03<38:39,  2.41it/s]

  7%|▋         | 432/6015 [03:03<38:40,  2.41it/s]

  7%|▋         | 433/6015 [03:04<38:39,  2.41it/s]

  7%|▋         | 434/6015 [03:04<38:39,  2.41it/s]

  7%|▋         | 435/6015 [03:05<38:37,  2.41it/s]

  7%|▋         | 436/6015 [03:05<38:36,  2.41it/s]

  7%|▋         | 437/6015 [03:05<38:33,  2.41it/s]

  7%|▋         | 438/6015 [03:06<38:32,  2.41it/s]

  7%|▋         | 439/6015 [03:06<38:31,  2.41it/s]

  7%|▋         | 440/6015 [03:07<38:33,  2.41it/s]

  7%|▋         | 441/6015 [03:07<38:34,  2.41it/s]

  7%|▋         | 442/6015 [03:08<38:32,  2.41it/s]

  7%|▋         | 443/6015 [03:08<38:35,  2.41it/s]

  7%|▋         | 444/6015 [03:08<38:32,  2.41it/s]

  7%|▋         | 445/6015 [03:09<38:34,  2.41it/s]

  7%|▋         | 446/6015 [03:09<38:33,  2.41it/s]

  7%|▋         | 447/6015 [03:10<38:33,  2.41it/s]

  7%|▋         | 448/6015 [03:10<38:34,  2.40it/s]

  7%|▋         | 449/6015 [03:10<38:31,  2.41it/s]

  7%|▋         | 450/6015 [03:11<38:30,  2.41it/s]

  7%|▋         | 451/6015 [03:11<38:30,  2.41it/s]

  8%|▊         | 452/6015 [03:12<38:29,  2.41it/s]

  8%|▊         | 453/6015 [03:12<38:29,  2.41it/s]

  8%|▊         | 454/6015 [03:12<38:34,  2.40it/s]

  8%|▊         | 455/6015 [03:13<38:31,  2.41it/s]

  8%|▊         | 456/6015 [03:13<38:31,  2.40it/s]

  8%|▊         | 457/6015 [03:14<38:28,  2.41it/s]

  8%|▊         | 458/6015 [03:14<38:29,  2.41it/s]

  8%|▊         | 459/6015 [03:15<38:28,  2.41it/s]

  8%|▊         | 460/6015 [03:15<38:27,  2.41it/s]

  8%|▊         | 461/6015 [03:15<38:26,  2.41it/s]

  8%|▊         | 462/6015 [03:16<38:26,  2.41it/s]

  8%|▊         | 463/6015 [03:16<38:27,  2.41it/s]

  8%|▊         | 464/6015 [03:17<38:29,  2.40it/s]

  8%|▊         | 465/6015 [03:17<38:33,  2.40it/s]

  8%|▊         | 466/6015 [03:17<38:28,  2.40it/s]

  8%|▊         | 467/6015 [03:18<38:24,  2.41it/s]

  8%|▊         | 468/6015 [03:18<38:28,  2.40it/s]

  8%|▊         | 469/6015 [03:19<38:29,  2.40it/s]

  8%|▊         | 470/6015 [03:19<38:25,  2.41it/s]

  8%|▊         | 471/6015 [03:20<38:31,  2.40it/s]

  8%|▊         | 472/6015 [03:20<38:30,  2.40it/s]

  8%|▊         | 473/6015 [03:20<38:29,  2.40it/s]

  8%|▊         | 474/6015 [03:21<38:24,  2.40it/s]

  8%|▊         | 475/6015 [03:21<38:24,  2.40it/s]

  8%|▊         | 476/6015 [03:22<38:25,  2.40it/s]

  8%|▊         | 477/6015 [03:22<38:23,  2.40it/s]

  8%|▊         | 478/6015 [03:22<38:19,  2.41it/s]

  8%|▊         | 479/6015 [03:23<38:25,  2.40it/s]

  8%|▊         | 480/6015 [03:23<38:22,  2.40it/s]

  8%|▊         | 481/6015 [03:24<38:20,  2.41it/s]

  8%|▊         | 482/6015 [03:24<38:20,  2.40it/s]

  8%|▊         | 483/6015 [03:25<38:22,  2.40it/s]

  8%|▊         | 484/6015 [03:25<38:21,  2.40it/s]

  8%|▊         | 485/6015 [03:25<38:19,  2.40it/s]

  8%|▊         | 486/6015 [03:26<38:15,  2.41it/s]

  8%|▊         | 487/6015 [03:26<38:19,  2.40it/s]

  8%|▊         | 488/6015 [03:27<38:17,  2.41it/s]

  8%|▊         | 489/6015 [03:27<38:26,  2.40it/s]

  8%|▊         | 490/6015 [03:27<38:25,  2.40it/s]

  8%|▊         | 491/6015 [03:28<38:24,  2.40it/s]

  8%|▊         | 492/6015 [03:28<38:24,  2.40it/s]

  8%|▊         | 493/6015 [03:29<38:22,  2.40it/s]

  8%|▊         | 494/6015 [03:29<38:22,  2.40it/s]

  8%|▊         | 495/6015 [03:30<38:20,  2.40it/s]

  8%|▊         | 496/6015 [03:30<38:19,  2.40it/s]

  8%|▊         | 497/6015 [03:30<38:25,  2.39it/s]

  8%|▊         | 498/6015 [03:31<38:22,  2.40it/s]

  8%|▊         | 499/6015 [03:31<38:18,  2.40it/s]

  8%|▊         | 500/6015 [03:32<38:20,  2.40it/s]

  8%|▊         | 501/6015 [03:32<38:18,  2.40it/s]

  8%|▊         | 502/6015 [03:32<38:16,  2.40it/s]

  8%|▊         | 503/6015 [03:33<38:15,  2.40it/s]

  8%|▊         | 504/6015 [03:33<38:15,  2.40it/s]

  8%|▊         | 505/6015 [03:34<38:14,  2.40it/s]

  8%|▊         | 506/6015 [03:34<38:14,  2.40it/s]

  8%|▊         | 507/6015 [03:35<38:11,  2.40it/s]

  8%|▊         | 508/6015 [03:35<38:12,  2.40it/s]

  8%|▊         | 509/6015 [03:35<38:11,  2.40it/s]

  8%|▊         | 510/6015 [03:36<38:11,  2.40it/s]

  8%|▊         | 511/6015 [03:36<38:07,  2.41it/s]

  9%|▊         | 512/6015 [03:37<38:09,  2.40it/s]

  9%|▊         | 513/6015 [03:37<38:09,  2.40it/s]

  9%|▊         | 514/6015 [03:37<38:08,  2.40it/s]

  9%|▊         | 515/6015 [03:38<38:09,  2.40it/s]

  9%|▊         | 516/6015 [03:38<38:09,  2.40it/s]

  9%|▊         | 517/6015 [03:39<38:09,  2.40it/s]

  9%|▊         | 518/6015 [03:39<38:10,  2.40it/s]

  9%|▊         | 519/6015 [03:40<38:07,  2.40it/s]

  9%|▊         | 520/6015 [03:40<38:07,  2.40it/s]

  9%|▊         | 521/6015 [03:40<38:07,  2.40it/s]

  9%|▊         | 522/6015 [03:41<38:08,  2.40it/s]

  9%|▊         | 523/6015 [03:41<38:08,  2.40it/s]

  9%|▊         | 524/6015 [03:42<38:07,  2.40it/s]

  9%|▊         | 525/6015 [03:42<38:09,  2.40it/s]

  9%|▊         | 526/6015 [03:42<38:09,  2.40it/s]

  9%|▉         | 527/6015 [03:43<38:12,  2.39it/s]

  9%|▉         | 528/6015 [03:43<38:11,  2.39it/s]

  9%|▉         | 529/6015 [03:44<38:12,  2.39it/s]

  9%|▉         | 530/6015 [03:44<38:12,  2.39it/s]

  9%|▉         | 531/6015 [03:45<38:10,  2.39it/s]

  9%|▉         | 532/6015 [03:45<38:08,  2.40it/s]

  9%|▉         | 533/6015 [03:45<38:10,  2.39it/s]

  9%|▉         | 534/6015 [03:46<38:05,  2.40it/s]

  9%|▉         | 535/6015 [03:46<38:04,  2.40it/s]

  9%|▉         | 536/6015 [03:47<38:02,  2.40it/s]

  9%|▉         | 537/6015 [03:47<38:05,  2.40it/s]

  9%|▉         | 538/6015 [03:47<38:02,  2.40it/s]

  9%|▉         | 539/6015 [03:48<38:03,  2.40it/s]

  9%|▉         | 540/6015 [03:48<38:01,  2.40it/s]

  9%|▉         | 541/6015 [03:49<38:02,  2.40it/s]

  9%|▉         | 542/6015 [03:49<38:02,  2.40it/s]

  9%|▉         | 543/6015 [03:50<38:02,  2.40it/s]

  9%|▉         | 544/6015 [03:50<38:00,  2.40it/s]

  9%|▉         | 545/6015 [03:50<37:58,  2.40it/s]

  9%|▉         | 546/6015 [03:51<37:57,  2.40it/s]

  9%|▉         | 547/6015 [03:51<37:58,  2.40it/s]

  9%|▉         | 548/6015 [03:52<37:56,  2.40it/s]

  9%|▉         | 549/6015 [03:52<37:58,  2.40it/s]

  9%|▉         | 550/6015 [03:52<37:56,  2.40it/s]

  9%|▉         | 551/6015 [03:53<37:57,  2.40it/s]

  9%|▉         | 552/6015 [03:53<37:57,  2.40it/s]

  9%|▉         | 553/6015 [03:54<37:55,  2.40it/s]

  9%|▉         | 554/6015 [03:54<37:54,  2.40it/s]

  9%|▉         | 555/6015 [03:55<37:51,  2.40it/s]

  9%|▉         | 556/6015 [03:55<37:53,  2.40it/s]

  9%|▉         | 557/6015 [03:55<37:54,  2.40it/s]

  9%|▉         | 558/6015 [03:56<38:00,  2.39it/s]

  9%|▉         | 559/6015 [03:56<37:59,  2.39it/s]

  9%|▉         | 560/6015 [03:57<38:05,  2.39it/s]

  9%|▉         | 561/6015 [03:57<38:00,  2.39it/s]

  9%|▉         | 562/6015 [03:57<38:03,  2.39it/s]

  9%|▉         | 563/6015 [03:58<38:01,  2.39it/s]

  9%|▉         | 564/6015 [03:58<38:03,  2.39it/s]

  9%|▉         | 565/6015 [03:59<38:01,  2.39it/s]

  9%|▉         | 566/6015 [03:59<38:01,  2.39it/s]

  9%|▉         | 567/6015 [04:00<38:04,  2.39it/s]

  9%|▉         | 568/6015 [04:00<38:09,  2.38it/s]

  9%|▉         | 569/6015 [04:00<38:05,  2.38it/s]

  9%|▉         | 570/6015 [04:01<38:03,  2.38it/s]

  9%|▉         | 571/6015 [04:01<37:58,  2.39it/s]

 10%|▉         | 572/6015 [04:02<37:55,  2.39it/s]

 10%|▉         | 573/6015 [04:02<37:53,  2.39it/s]

 10%|▉         | 574/6015 [04:03<37:51,  2.40it/s]

 10%|▉         | 575/6015 [04:03<37:48,  2.40it/s]

 10%|▉         | 576/6015 [04:03<37:49,  2.40it/s]

 10%|▉         | 577/6015 [04:04<37:51,  2.39it/s]

 10%|▉         | 578/6015 [04:04<37:48,  2.40it/s]

 10%|▉         | 579/6015 [04:05<37:45,  2.40it/s]

 10%|▉         | 580/6015 [04:05<37:46,  2.40it/s]

 10%|▉         | 581/6015 [04:05<37:44,  2.40it/s]

 10%|▉         | 582/6015 [04:06<37:49,  2.39it/s]

 10%|▉         | 583/6015 [04:06<37:47,  2.40it/s]

 10%|▉         | 584/6015 [04:07<37:48,  2.39it/s]

 10%|▉         | 585/6015 [04:07<37:45,  2.40it/s]

 10%|▉         | 586/6015 [04:08<37:46,  2.40it/s]

 10%|▉         | 587/6015 [04:08<37:47,  2.39it/s]

 10%|▉         | 588/6015 [04:08<37:46,  2.39it/s]

 10%|▉         | 589/6015 [04:09<37:48,  2.39it/s]

 10%|▉         | 590/6015 [04:09<37:48,  2.39it/s]

 10%|▉         | 591/6015 [04:10<37:46,  2.39it/s]

 10%|▉         | 592/6015 [04:10<37:42,  2.40it/s]

 10%|▉         | 593/6015 [04:10<37:43,  2.39it/s]

 10%|▉         | 594/6015 [04:11<37:46,  2.39it/s]

 10%|▉         | 595/6015 [04:11<37:43,  2.39it/s]

 10%|▉         | 596/6015 [04:12<37:45,  2.39it/s]

 10%|▉         | 597/6015 [04:12<37:45,  2.39it/s]

 10%|▉         | 598/6015 [04:13<37:44,  2.39it/s]

 10%|▉         | 599/6015 [04:13<37:40,  2.40it/s]

 10%|▉         | 600/6015 [04:13<37:42,  2.39it/s]

 10%|▉         | 601/6015 [04:14<37:42,  2.39it/s]

 10%|█         | 602/6015 [04:14<37:42,  2.39it/s]

 10%|█         | 603/6015 [04:15<37:44,  2.39it/s]

 10%|█         | 604/6015 [04:15<37:44,  2.39it/s]

 10%|█         | 605/6015 [04:15<37:44,  2.39it/s]

 10%|█         | 606/6015 [04:16<37:44,  2.39it/s]

 10%|█         | 607/6015 [04:16<37:43,  2.39it/s]

 10%|█         | 608/6015 [04:17<37:41,  2.39it/s]

 10%|█         | 609/6015 [04:17<37:43,  2.39it/s]

 10%|█         | 610/6015 [04:18<37:42,  2.39it/s]

 10%|█         | 611/6015 [04:18<37:38,  2.39it/s]

 10%|█         | 612/6015 [04:18<37:34,  2.40it/s]

 10%|█         | 613/6015 [04:19<37:36,  2.39it/s]

 10%|█         | 614/6015 [04:19<37:37,  2.39it/s]

 10%|█         | 615/6015 [04:20<37:36,  2.39it/s]

 10%|█         | 616/6015 [04:20<37:36,  2.39it/s]

 10%|█         | 617/6015 [04:20<37:34,  2.39it/s]

 10%|█         | 618/6015 [04:21<37:37,  2.39it/s]

 10%|█         | 619/6015 [04:21<37:38,  2.39it/s]

 10%|█         | 620/6015 [04:22<37:41,  2.39it/s]

 10%|█         | 621/6015 [04:22<37:37,  2.39it/s]

 10%|█         | 622/6015 [04:23<37:39,  2.39it/s]

 10%|█         | 623/6015 [04:23<37:36,  2.39it/s]

 10%|█         | 624/6015 [04:23<37:38,  2.39it/s]

 10%|█         | 625/6015 [04:24<37:34,  2.39it/s]

logging
logging the anndata

 10%|█         | 626/6015 [04:24<39:41,  2.26it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 10%|█         | 627/6015 [04:25<38:53,  2.31it/s]

 10%|█         | 628/6015 [04:25<38:17,  2.35it/s]

 10%|█         | 629/6015 [04:26<37:50,  2.37it/s]

 10%|█         | 630/6015 [04:26<37:31,  2.39it/s]

 10%|█         | 631/6015 [04:26<37:19,  2.40it/s]

 11%|█         | 632/6015 [04:27<37:09,  2.41it/s]

 11%|█         | 633/6015 [04:27<37:02,  2.42it/s]

 11%|█         | 634/6015 [04:28<36:58,  2.43it/s]

 11%|█         | 635/6015 [04:28<36:57,  2.43it/s]

 11%|█         | 636/6015 [04:28<36:54,  2.43it/s]

 11%|█         | 637/6015 [04:29<36:50,  2.43it/s]

 11%|█         | 638/6015 [04:29<36:51,  2.43it/s]

 11%|█         | 639/6015 [04:30<36:49,  2.43it/s]

 11%|█         | 640/6015 [04:30<36:48,  2.43it/s]

 11%|█         | 641/6015 [04:30<36:46,  2.44it/s]

 11%|█         | 642/6015 [04:31<36:47,  2.43it/s]

 11%|█         | 643/6015 [04:31<36:44,  2.44it/s]

 11%|█         | 644/6015 [04:32<36:44,  2.44it/s]

 11%|█         | 645/6015 [04:32<36:45,  2.43it/s]

 11%|█         | 646/6015 [04:33<36:45,  2.43it/s]

 11%|█         | 647/6015 [04:33<36:43,  2.44it/s]

 11%|█         | 648/6015 [04:33<36:41,  2.44it/s]

 11%|█         | 649/6015 [04:34<36:42,  2.44it/s]

 11%|█         | 650/6015 [04:34<36:40,  2.44it/s]

 11%|█         | 651/6015 [04:35<36:39,  2.44it/s]

 11%|█         | 652/6015 [04:35<36:36,  2.44it/s]

 11%|█         | 653/6015 [04:35<36:37,  2.44it/s]

 11%|█         | 654/6015 [04:36<36:42,  2.43it/s]

 11%|█         | 655/6015 [04:36<36:40,  2.44it/s]

 11%|█         | 656/6015 [04:37<36:40,  2.44it/s]

 11%|█         | 657/6015 [04:37<36:39,  2.44it/s]

 11%|█         | 658/6015 [04:37<36:42,  2.43it/s]

 11%|█         | 659/6015 [04:38<36:40,  2.43it/s]

 11%|█         | 660/6015 [04:38<36:41,  2.43it/s]

 11%|█         | 661/6015 [04:39<36:38,  2.44it/s]

 11%|█         | 662/6015 [04:39<36:40,  2.43it/s]

 11%|█         | 663/6015 [04:40<36:36,  2.44it/s]

 11%|█         | 664/6015 [04:40<36:35,  2.44it/s]

 11%|█         | 665/6015 [04:40<36:37,  2.43it/s]

 11%|█         | 666/6015 [04:41<36:36,  2.44it/s]

 11%|█         | 667/6015 [04:41<36:36,  2.43it/s]

 11%|█         | 668/6015 [04:42<36:39,  2.43it/s]

 11%|█         | 669/6015 [04:42<36:45,  2.42it/s]

 11%|█         | 670/6015 [04:42<36:40,  2.43it/s]

 11%|█         | 671/6015 [04:43<36:39,  2.43it/s]

 11%|█         | 672/6015 [04:43<36:37,  2.43it/s]

 11%|█         | 673/6015 [04:44<36:37,  2.43it/s]

 11%|█         | 674/6015 [04:44<36:34,  2.43it/s]

 11%|█         | 675/6015 [04:44<36:34,  2.43it/s]

 11%|█         | 676/6015 [04:45<36:34,  2.43it/s]

 11%|█▏        | 677/6015 [04:45<36:34,  2.43it/s]

 11%|█▏        | 678/6015 [04:46<36:33,  2.43it/s]

 11%|█▏        | 679/6015 [04:46<36:31,  2.43it/s]

 11%|█▏        | 680/6015 [04:47<36:31,  2.43it/s]

 11%|█▏        | 681/6015 [04:47<36:31,  2.43it/s]

 11%|█▏        | 682/6015 [04:47<36:31,  2.43it/s]

 11%|█▏        | 683/6015 [04:48<36:29,  2.44it/s]

 11%|█▏        | 684/6015 [04:48<36:31,  2.43it/s]

 11%|█▏        | 685/6015 [04:49<36:36,  2.43it/s]

 11%|█▏        | 686/6015 [04:49<36:35,  2.43it/s]

 11%|█▏        | 687/6015 [04:49<36:33,  2.43it/s]

 11%|█▏        | 688/6015 [04:50<36:31,  2.43it/s]

 11%|█▏        | 689/6015 [04:50<36:36,  2.42it/s]

 11%|█▏        | 690/6015 [04:51<36:32,  2.43it/s]

 11%|█▏        | 691/6015 [04:51<36:30,  2.43it/s]

 12%|█▏        | 692/6015 [04:51<36:28,  2.43it/s]

 12%|█▏        | 693/6015 [04:52<36:30,  2.43it/s]

 12%|█▏        | 694/6015 [04:52<36:28,  2.43it/s]

 12%|█▏        | 695/6015 [04:53<36:28,  2.43it/s]

 12%|█▏        | 696/6015 [04:53<36:29,  2.43it/s]

 12%|█▏        | 697/6015 [04:54<36:28,  2.43it/s]

 12%|█▏        | 698/6015 [04:54<36:27,  2.43it/s]

 12%|█▏        | 699/6015 [04:54<36:26,  2.43it/s]

 12%|█▏        | 700/6015 [04:55<36:26,  2.43it/s]

 12%|█▏        | 701/6015 [04:55<36:24,  2.43it/s]

 12%|█▏        | 702/6015 [04:56<36:26,  2.43it/s]

 12%|█▏        | 703/6015 [04:56<36:24,  2.43it/s]

 12%|█▏        | 704/6015 [04:56<36:23,  2.43it/s]

 12%|█▏        | 705/6015 [04:57<36:23,  2.43it/s]

 12%|█▏        | 706/6015 [04:57<36:22,  2.43it/s]

 12%|█▏        | 707/6015 [04:58<36:21,  2.43it/s]

 12%|█▏        | 708/6015 [04:58<36:22,  2.43it/s]

 12%|█▏        | 709/6015 [04:58<36:22,  2.43it/s]

 12%|█▏        | 710/6015 [04:59<36:22,  2.43it/s]

 12%|█▏        | 711/6015 [04:59<36:24,  2.43it/s]

 12%|█▏        | 712/6015 [05:00<36:22,  2.43it/s]

 12%|█▏        | 713/6015 [05:00<36:22,  2.43it/s]

 12%|█▏        | 714/6015 [05:01<36:21,  2.43it/s]

 12%|█▏        | 715/6015 [05:01<36:21,  2.43it/s]

 12%|█▏        | 716/6015 [05:01<36:23,  2.43it/s]

 12%|█▏        | 717/6015 [05:02<36:22,  2.43it/s]

 12%|█▏        | 718/6015 [05:02<36:25,  2.42it/s]

 12%|█▏        | 719/6015 [05:03<36:23,  2.43it/s]

 12%|█▏        | 720/6015 [05:03<36:23,  2.43it/s]

 12%|█▏        | 721/6015 [05:03<36:20,  2.43it/s]

 12%|█▏        | 722/6015 [05:04<36:20,  2.43it/s]

 12%|█▏        | 723/6015 [05:04<36:20,  2.43it/s]

 12%|█▏        | 724/6015 [05:05<36:19,  2.43it/s]

 12%|█▏        | 725/6015 [05:05<36:19,  2.43it/s]

 12%|█▏        | 726/6015 [05:05<36:19,  2.43it/s]

 12%|█▏        | 727/6015 [05:06<36:17,  2.43it/s]

 12%|█▏        | 728/6015 [05:06<36:16,  2.43it/s]

 12%|█▏        | 729/6015 [05:07<36:16,  2.43it/s]

 12%|█▏        | 730/6015 [05:07<36:16,  2.43it/s]

 12%|█▏        | 731/6015 [05:08<36:14,  2.43it/s]

 12%|█▏        | 732/6015 [05:08<36:13,  2.43it/s]

 12%|█▏        | 733/6015 [05:08<36:14,  2.43it/s]

 12%|█▏        | 734/6015 [05:09<36:12,  2.43it/s]

 12%|█▏        | 735/6015 [05:09<36:13,  2.43it/s]

 12%|█▏        | 736/6015 [05:10<36:11,  2.43it/s]

 12%|█▏        | 737/6015 [05:10<36:12,  2.43it/s]

 12%|█▏        | 738/6015 [05:10<36:11,  2.43it/s]

 12%|█▏        | 739/6015 [05:11<36:14,  2.43it/s]

 12%|█▏        | 740/6015 [05:11<36:14,  2.43it/s]

 12%|█▏        | 741/6015 [05:12<36:13,  2.43it/s]

 12%|█▏        | 742/6015 [05:12<36:12,  2.43it/s]

 12%|█▏        | 743/6015 [05:12<36:11,  2.43it/s]

 12%|█▏        | 744/6015 [05:13<36:11,  2.43it/s]

 12%|█▏        | 745/6015 [05:13<36:13,  2.43it/s]

 12%|█▏        | 746/6015 [05:14<36:13,  2.42it/s]

 12%|█▏        | 747/6015 [05:14<36:13,  2.42it/s]

 12%|█▏        | 748/6015 [05:15<36:12,  2.42it/s]

 12%|█▏        | 749/6015 [05:15<36:09,  2.43it/s]

 12%|█▏        | 750/6015 [05:15<36:10,  2.43it/s]

 12%|█▏        | 751/6015 [05:16<36:11,  2.42it/s]

 13%|█▎        | 752/6015 [05:16<36:09,  2.43it/s]

 13%|█▎        | 753/6015 [05:17<36:16,  2.42it/s]

 13%|█▎        | 754/6015 [05:17<36:15,  2.42it/s]

 13%|█▎        | 755/6015 [05:17<36:13,  2.42it/s]

 13%|█▎        | 756/6015 [05:18<36:10,  2.42it/s]

 13%|█▎        | 757/6015 [05:18<36:07,  2.43it/s]

 13%|█▎        | 758/6015 [05:19<36:06,  2.43it/s]

 13%|█▎        | 759/6015 [05:19<36:06,  2.43it/s]

 13%|█▎        | 760/6015 [05:19<36:06,  2.43it/s]

 13%|█▎        | 761/6015 [05:20<36:06,  2.42it/s]

 13%|█▎        | 762/6015 [05:20<36:09,  2.42it/s]

 13%|█▎        | 763/6015 [05:21<36:07,  2.42it/s]

 13%|█▎        | 764/6015 [05:21<36:07,  2.42it/s]

 13%|█▎        | 765/6015 [05:22<36:07,  2.42it/s]

 13%|█▎        | 766/6015 [05:22<36:07,  2.42it/s]

 13%|█▎        | 767/6015 [05:22<36:05,  2.42it/s]

 13%|█▎        | 768/6015 [05:23<36:07,  2.42it/s]

 13%|█▎        | 769/6015 [05:23<36:06,  2.42it/s]

 13%|█▎        | 770/6015 [05:24<36:04,  2.42it/s]

 13%|█▎        | 771/6015 [05:24<36:06,  2.42it/s]

 13%|█▎        | 772/6015 [05:24<36:04,  2.42it/s]

 13%|█▎        | 773/6015 [05:25<36:05,  2.42it/s]

 13%|█▎        | 774/6015 [05:25<36:02,  2.42it/s]

 13%|█▎        | 775/6015 [05:26<36:03,  2.42it/s]

 13%|█▎        | 776/6015 [05:26<36:01,  2.42it/s]

 13%|█▎        | 777/6015 [05:26<36:00,  2.42it/s]

 13%|█▎        | 778/6015 [05:27<36:12,  2.41it/s]

 13%|█▎        | 779/6015 [05:27<36:11,  2.41it/s]

 13%|█▎        | 780/6015 [05:28<36:08,  2.41it/s]

 13%|█▎        | 781/6015 [05:28<36:04,  2.42it/s]

 13%|█▎        | 782/6015 [05:29<36:03,  2.42it/s]

 13%|█▎        | 783/6015 [05:29<36:02,  2.42it/s]

 13%|█▎        | 784/6015 [05:29<36:03,  2.42it/s]

 13%|█▎        | 785/6015 [05:30<35:59,  2.42it/s]

 13%|█▎        | 786/6015 [05:30<35:59,  2.42it/s]

 13%|█▎        | 787/6015 [05:31<35:55,  2.43it/s]

 13%|█▎        | 788/6015 [05:31<35:57,  2.42it/s]

 13%|█▎        | 789/6015 [05:31<35:55,  2.42it/s]

 13%|█▎        | 790/6015 [05:32<35:54,  2.43it/s]

 13%|█▎        | 791/6015 [05:32<35:58,  2.42it/s]

 13%|█▎        | 792/6015 [05:33<35:57,  2.42it/s]

 13%|█▎        | 793/6015 [05:33<35:55,  2.42it/s]

 13%|█▎        | 794/6015 [05:34<35:53,  2.42it/s]

 13%|█▎        | 795/6015 [05:34<35:53,  2.42it/s]

 13%|█▎        | 796/6015 [05:34<35:52,  2.42it/s]

 13%|█▎        | 797/6015 [05:35<35:55,  2.42it/s]

 13%|█▎        | 798/6015 [05:35<35:55,  2.42it/s]

 13%|█▎        | 799/6015 [05:36<35:54,  2.42it/s]

 13%|█▎        | 800/6015 [05:36<35:54,  2.42it/s]

 13%|█▎        | 801/6015 [05:36<35:54,  2.42it/s]

 13%|█▎        | 802/6015 [05:37<35:53,  2.42it/s]

 13%|█▎        | 803/6015 [05:37<35:57,  2.42it/s]

 13%|█▎        | 804/6015 [05:38<35:56,  2.42it/s]

 13%|█▎        | 805/6015 [05:38<35:58,  2.41it/s]

 13%|█▎        | 806/6015 [05:38<36:01,  2.41it/s]

 13%|█▎        | 807/6015 [05:39<35:58,  2.41it/s]

 13%|█▎        | 808/6015 [05:39<35:55,  2.42it/s]

 13%|█▎        | 809/6015 [05:40<35:52,  2.42it/s]

 13%|█▎        | 810/6015 [05:40<35:51,  2.42it/s]

 13%|█▎        | 811/6015 [05:41<35:51,  2.42it/s]

 13%|█▎        | 812/6015 [05:41<35:51,  2.42it/s]

 14%|█▎        | 813/6015 [05:41<35:50,  2.42it/s]

 14%|█▎        | 814/6015 [05:42<35:51,  2.42it/s]

 14%|█▎        | 815/6015 [05:42<35:51,  2.42it/s]

 14%|█▎        | 816/6015 [05:43<35:51,  2.42it/s]

 14%|█▎        | 817/6015 [05:43<35:49,  2.42it/s]

 14%|█▎        | 818/6015 [05:43<35:47,  2.42it/s]

 14%|█▎        | 819/6015 [05:44<35:56,  2.41it/s]

 14%|█▎        | 820/6015 [05:44<35:52,  2.41it/s]

 14%|█▎        | 821/6015 [05:45<35:50,  2.42it/s]

 14%|█▎        | 822/6015 [05:45<35:48,  2.42it/s]

 14%|█▎        | 823/6015 [05:46<35:47,  2.42it/s]

 14%|█▎        | 824/6015 [05:46<35:45,  2.42it/s]

 14%|█▎        | 825/6015 [05:46<35:46,  2.42it/s]

 14%|█▎        | 826/6015 [05:47<35:46,  2.42it/s]

 14%|█▎        | 827/6015 [05:47<35:43,  2.42it/s]

 14%|█▍        | 828/6015 [05:48<35:41,  2.42it/s]

 14%|█▍        | 829/6015 [05:48<35:42,  2.42it/s]

 14%|█▍        | 830/6015 [05:48<35:40,  2.42it/s]

 14%|█▍        | 831/6015 [05:49<35:39,  2.42it/s]

 14%|█▍        | 832/6015 [05:49<35:42,  2.42it/s]

 14%|█▍        | 833/6015 [05:50<35:42,  2.42it/s]

 14%|█▍        | 834/6015 [05:50<35:41,  2.42it/s]

 14%|█▍        | 835/6015 [05:50<35:41,  2.42it/s]

 14%|█▍        | 836/6015 [05:51<35:41,  2.42it/s]

 14%|█▍        | 837/6015 [05:51<35:39,  2.42it/s]

 14%|█▍        | 838/6015 [05:52<35:42,  2.42it/s]

 14%|█▍        | 839/6015 [05:52<35:39,  2.42it/s]

 14%|█▍        | 840/6015 [05:53<35:39,  2.42it/s]

 14%|█▍        | 841/6015 [05:53<35:38,  2.42it/s]

 14%|█▍        | 842/6015 [05:53<35:37,  2.42it/s]

 14%|█▍        | 843/6015 [05:54<35:38,  2.42it/s]

 14%|█▍        | 844/6015 [05:54<35:42,  2.41it/s]

 14%|█▍        | 845/6015 [05:55<35:40,  2.42it/s]

 14%|█▍        | 846/6015 [05:55<35:38,  2.42it/s]

 14%|█▍        | 847/6015 [05:55<35:41,  2.41it/s]

 14%|█▍        | 848/6015 [05:56<35:39,  2.42it/s]

 14%|█▍        | 849/6015 [05:56<35:37,  2.42it/s]

 14%|█▍        | 850/6015 [05:57<35:36,  2.42it/s]

 14%|█▍        | 851/6015 [05:57<35:35,  2.42it/s]

 14%|█▍        | 852/6015 [05:57<35:35,  2.42it/s]

 14%|█▍        | 853/6015 [05:58<35:34,  2.42it/s]

 14%|█▍        | 854/6015 [05:58<35:33,  2.42it/s]

 14%|█▍        | 855/6015 [05:59<35:36,  2.42it/s]

 14%|█▍        | 856/6015 [05:59<35:35,  2.42it/s]

 14%|█▍        | 857/6015 [06:00<35:34,  2.42it/s]

 14%|█▍        | 858/6015 [06:00<35:31,  2.42it/s]

 14%|█▍        | 859/6015 [06:00<35:31,  2.42it/s]

 14%|█▍        | 860/6015 [06:01<35:30,  2.42it/s]

 14%|█▍        | 861/6015 [06:01<35:30,  2.42it/s]

 14%|█▍        | 862/6015 [06:02<35:31,  2.42it/s]

 14%|█▍        | 863/6015 [06:02<35:31,  2.42it/s]

 14%|█▍        | 864/6015 [06:02<35:31,  2.42it/s]

 14%|█▍        | 865/6015 [06:03<35:30,  2.42it/s]

 14%|█▍        | 866/6015 [06:03<35:32,  2.41it/s]

 14%|█▍        | 867/6015 [06:04<35:29,  2.42it/s]

 14%|█▍        | 868/6015 [06:04<35:30,  2.42it/s]

 14%|█▍        | 869/6015 [06:05<35:28,  2.42it/s]

 14%|█▍        | 870/6015 [06:05<35:28,  2.42it/s]

 14%|█▍        | 871/6015 [06:05<35:27,  2.42it/s]

 14%|█▍        | 872/6015 [06:06<35:28,  2.42it/s]

 15%|█▍        | 873/6015 [06:06<35:27,  2.42it/s]

 15%|█▍        | 874/6015 [06:07<35:28,  2.42it/s]

 15%|█▍        | 875/6015 [06:07<35:28,  2.41it/s]

 15%|█▍        | 876/6015 [06:07<35:31,  2.41it/s]

 15%|█▍        | 877/6015 [06:08<35:33,  2.41it/s]

 15%|█▍        | 878/6015 [06:08<35:29,  2.41it/s]

 15%|█▍        | 879/6015 [06:09<35:28,  2.41it/s]

 15%|█▍        | 880/6015 [06:09<35:25,  2.42it/s]

 15%|█▍        | 881/6015 [06:09<35:27,  2.41it/s]

 15%|█▍        | 882/6015 [06:10<35:27,  2.41it/s]

 15%|█▍        | 883/6015 [06:10<35:27,  2.41it/s]

 15%|█▍        | 884/6015 [06:11<35:26,  2.41it/s]

 15%|█▍        | 885/6015 [06:11<35:27,  2.41it/s]

 15%|█▍        | 886/6015 [06:12<35:27,  2.41it/s]

 15%|█▍        | 887/6015 [06:12<35:26,  2.41it/s]

 15%|█▍        | 888/6015 [06:12<35:24,  2.41it/s]

 15%|█▍        | 889/6015 [06:13<35:25,  2.41it/s]

 15%|█▍        | 890/6015 [06:13<35:22,  2.41it/s]

 15%|█▍        | 891/6015 [06:14<35:23,  2.41it/s]

 15%|█▍        | 892/6015 [06:14<35:22,  2.41it/s]

 15%|█▍        | 893/6015 [06:14<35:23,  2.41it/s]

 15%|█▍        | 894/6015 [06:15<35:24,  2.41it/s]

 15%|█▍        | 895/6015 [06:15<35:23,  2.41it/s]

 15%|█▍        | 896/6015 [06:16<35:22,  2.41it/s]

 15%|█▍        | 897/6015 [06:16<35:20,  2.41it/s]

 15%|█▍        | 898/6015 [06:17<35:19,  2.41it/s]

 15%|█▍        | 899/6015 [06:17<35:17,  2.42it/s]

 15%|█▍        | 900/6015 [06:17<35:19,  2.41it/s]

 15%|█▍        | 901/6015 [06:18<35:18,  2.41it/s]

 15%|█▍        | 902/6015 [06:18<35:21,  2.41it/s]

 15%|█▌        | 903/6015 [06:19<35:19,  2.41it/s]

 15%|█▌        | 904/6015 [06:19<35:19,  2.41it/s]

 15%|█▌        | 905/6015 [06:19<35:17,  2.41it/s]

 15%|█▌        | 906/6015 [06:20<35:19,  2.41it/s]

 15%|█▌        | 907/6015 [06:20<35:18,  2.41it/s]

 15%|█▌        | 908/6015 [06:21<35:17,  2.41it/s]

 15%|█▌        | 909/6015 [06:21<35:15,  2.41it/s]

 15%|█▌        | 910/6015 [06:22<35:15,  2.41it/s]

 15%|█▌        | 911/6015 [06:22<35:14,  2.41it/s]

 15%|█▌        | 912/6015 [06:22<35:12,  2.42it/s]

 15%|█▌        | 913/6015 [06:23<35:13,  2.41it/s]

 15%|█▌        | 914/6015 [06:23<35:14,  2.41it/s]

 15%|█▌        | 915/6015 [06:24<35:12,  2.41it/s]

 15%|█▌        | 916/6015 [06:24<35:11,  2.41it/s]

 15%|█▌        | 917/6015 [06:24<35:11,  2.41it/s]

 15%|█▌        | 918/6015 [06:25<35:11,  2.41it/s]

 15%|█▌        | 919/6015 [06:25<35:11,  2.41it/s]

 15%|█▌        | 920/6015 [06:26<35:10,  2.41it/s]

 15%|█▌        | 921/6015 [06:26<35:13,  2.41it/s]

 15%|█▌        | 922/6015 [06:26<35:11,  2.41it/s]

 15%|█▌        | 923/6015 [06:27<35:12,  2.41it/s]

 15%|█▌        | 924/6015 [06:27<35:18,  2.40it/s]

 15%|█▌        | 925/6015 [06:28<35:14,  2.41it/s]

 15%|█▌        | 926/6015 [06:28<35:13,  2.41it/s]

 15%|█▌        | 927/6015 [06:29<35:11,  2.41it/s]

 15%|█▌        | 928/6015 [06:29<35:12,  2.41it/s]

 15%|█▌        | 929/6015 [06:29<35:08,  2.41it/s]

 15%|█▌        | 930/6015 [06:30<35:08,  2.41it/s]

 15%|█▌        | 931/6015 [06:30<35:07,  2.41it/s]

 15%|█▌        | 932/6015 [06:31<35:06,  2.41it/s]

 16%|█▌        | 933/6015 [06:31<35:07,  2.41it/s]

 16%|█▌        | 934/6015 [06:31<35:05,  2.41it/s]

 16%|█▌        | 935/6015 [06:32<35:05,  2.41it/s]

 16%|█▌        | 936/6015 [06:32<35:05,  2.41it/s]

 16%|█▌        | 937/6015 [06:33<35:05,  2.41it/s]

 16%|█▌        | 938/6015 [06:33<35:03,  2.41it/s]

 16%|█▌        | 939/6015 [06:34<35:09,  2.41it/s]

 16%|█▌        | 940/6015 [06:34<35:07,  2.41it/s]

 16%|█▌        | 941/6015 [06:34<35:06,  2.41it/s]

 16%|█▌        | 942/6015 [06:35<35:06,  2.41it/s]

 16%|█▌        | 943/6015 [06:35<35:05,  2.41it/s]

 16%|█▌        | 944/6015 [06:36<35:04,  2.41it/s]

 16%|█▌        | 945/6015 [06:36<35:05,  2.41it/s]

 16%|█▌        | 946/6015 [06:36<35:04,  2.41it/s]

 16%|█▌        | 947/6015 [06:37<35:04,  2.41it/s]

 16%|█▌        | 948/6015 [06:37<35:05,  2.41it/s]

 16%|█▌        | 949/6015 [06:38<35:04,  2.41it/s]

 16%|█▌        | 950/6015 [06:38<35:04,  2.41it/s]

 16%|█▌        | 951/6015 [06:39<35:03,  2.41it/s]

 16%|█▌        | 952/6015 [06:39<35:05,  2.40it/s]

 16%|█▌        | 953/6015 [06:39<35:04,  2.41it/s]

 16%|█▌        | 954/6015 [06:40<35:02,  2.41it/s]

 16%|█▌        | 955/6015 [06:40<35:00,  2.41it/s]

 16%|█▌        | 956/6015 [06:41<34:59,  2.41it/s]

 16%|█▌        | 957/6015 [06:41<34:58,  2.41it/s]

 16%|█▌        | 958/6015 [06:41<35:01,  2.41it/s]

 16%|█▌        | 959/6015 [06:42<35:00,  2.41it/s]

 16%|█▌        | 960/6015 [06:42<35:02,  2.40it/s]

 16%|█▌        | 961/6015 [06:43<35:00,  2.41it/s]

 16%|█▌        | 962/6015 [06:43<35:00,  2.41it/s]

 16%|█▌        | 963/6015 [06:44<34:59,  2.41it/s]

 16%|█▌        | 964/6015 [06:44<34:59,  2.41it/s]

 16%|█▌        | 965/6015 [06:44<34:57,  2.41it/s]

 16%|█▌        | 966/6015 [06:45<34:55,  2.41it/s]

 16%|█▌        | 967/6015 [06:45<34:56,  2.41it/s]

 16%|█▌        | 968/6015 [06:46<34:57,  2.41it/s]

 16%|█▌        | 969/6015 [06:46<34:57,  2.41it/s]

 16%|█▌        | 970/6015 [06:46<34:57,  2.41it/s]

 16%|█▌        | 971/6015 [06:47<34:54,  2.41it/s]

 16%|█▌        | 972/6015 [06:47<34:53,  2.41it/s]

 16%|█▌        | 973/6015 [06:48<34:55,  2.41it/s]

 16%|█▌        | 974/6015 [06:48<34:54,  2.41it/s]

 16%|█▌        | 975/6015 [06:48<34:53,  2.41it/s]

 16%|█▌        | 976/6015 [06:49<34:52,  2.41it/s]

 16%|█▌        | 977/6015 [06:49<34:54,  2.41it/s]

 16%|█▋        | 978/6015 [06:50<34:51,  2.41it/s]

 16%|█▋        | 979/6015 [06:50<34:51,  2.41it/s]

 16%|█▋        | 980/6015 [06:51<34:48,  2.41it/s]

 16%|█▋        | 981/6015 [06:51<34:53,  2.40it/s]

 16%|█▋        | 982/6015 [06:51<34:55,  2.40it/s]

 16%|█▋        | 983/6015 [06:52<34:54,  2.40it/s]

 16%|█▋        | 984/6015 [06:52<34:51,  2.41it/s]

 16%|█▋        | 985/6015 [06:53<34:52,  2.40it/s]

 16%|█▋        | 986/6015 [06:53<34:51,  2.40it/s]

 16%|█▋        | 987/6015 [06:53<34:50,  2.41it/s]

 16%|█▋        | 988/6015 [06:54<34:51,  2.40it/s]

 16%|█▋        | 989/6015 [06:54<34:54,  2.40it/s]

 16%|█▋        | 990/6015 [06:55<34:53,  2.40it/s]

 16%|█▋        | 991/6015 [06:55<34:50,  2.40it/s]

 16%|█▋        | 992/6015 [06:56<34:49,  2.40it/s]

 17%|█▋        | 993/6015 [06:56<34:50,  2.40it/s]

 17%|█▋        | 994/6015 [06:56<34:48,  2.40it/s]

 17%|█▋        | 995/6015 [06:57<34:46,  2.41it/s]

 17%|█▋        | 996/6015 [06:57<34:45,  2.41it/s]

 17%|█▋        | 997/6015 [06:58<34:43,  2.41it/s]

 17%|█▋        | 998/6015 [06:58<34:44,  2.41it/s]

 17%|█▋        | 999/6015 [06:58<34:46,  2.40it/s]

 17%|█▋        | 1000/6015 [06:59<34:48,  2.40it/s]

 17%|█▋        | 1001/6015 [06:59<34:46,  2.40it/s]

 17%|█▋        | 1002/6015 [07:00<34:47,  2.40it/s]

 17%|█▋        | 1003/6015 [07:00<34:47,  2.40it/s]

 17%|█▋        | 1004/6015 [07:01<34:46,  2.40it/s]

 17%|█▋        | 1005/6015 [07:01<34:44,  2.40it/s]

 17%|█▋        | 1006/6015 [07:01<34:45,  2.40it/s]

 17%|█▋        | 1007/6015 [07:02<34:43,  2.40it/s]

 17%|█▋        | 1008/6015 [07:02<34:46,  2.40it/s]

 17%|█▋        | 1009/6015 [07:03<34:42,  2.40it/s]

 17%|█▋        | 1010/6015 [07:03<34:41,  2.40it/s]

 17%|█▋        | 1011/6015 [07:03<34:40,  2.40it/s]

 17%|█▋        | 1012/6015 [07:04<34:41,  2.40it/s]

 17%|█▋        | 1013/6015 [07:04<34:42,  2.40it/s]

 17%|█▋        | 1014/6015 [07:05<34:38,  2.41it/s]

 17%|█▋        | 1015/6015 [07:05<34:39,  2.40it/s]

 17%|█▋        | 1016/6015 [07:06<34:38,  2.40it/s]

 17%|█▋        | 1017/6015 [07:06<34:38,  2.40it/s]

 17%|█▋        | 1018/6015 [07:06<34:36,  2.41it/s]

 17%|█▋        | 1019/6015 [07:07<34:39,  2.40it/s]

 17%|█▋        | 1020/6015 [07:07<34:37,  2.40it/s]

 17%|█▋        | 1021/6015 [07:08<34:36,  2.41it/s]

 17%|█▋        | 1022/6015 [07:08<34:35,  2.41it/s]

 17%|█▋        | 1023/6015 [07:08<34:36,  2.40it/s]

 17%|█▋        | 1024/6015 [07:09<34:34,  2.41it/s]

 17%|█▋        | 1025/6015 [07:09<34:37,  2.40it/s]

 17%|█▋        | 1026/6015 [07:10<34:36,  2.40it/s]

 17%|█▋        | 1027/6015 [07:10<34:35,  2.40it/s]

 17%|█▋        | 1028/6015 [07:11<34:32,  2.41it/s]

 17%|█▋        | 1029/6015 [07:11<34:31,  2.41it/s]

 17%|█▋        | 1030/6015 [07:11<34:30,  2.41it/s]

 17%|█▋        | 1031/6015 [07:12<34:29,  2.41it/s]

 17%|█▋        | 1032/6015 [07:12<34:29,  2.41it/s]

 17%|█▋        | 1033/6015 [07:13<34:28,  2.41it/s]

 17%|█▋        | 1034/6015 [07:13<34:29,  2.41it/s]

 17%|█▋        | 1035/6015 [07:13<34:29,  2.41it/s]

 17%|█▋        | 1036/6015 [07:14<34:31,  2.40it/s]

 17%|█▋        | 1037/6015 [07:14<34:29,  2.41it/s]

 17%|█▋        | 1038/6015 [07:15<34:28,  2.41it/s]

 17%|█▋        | 1039/6015 [07:15<34:27,  2.41it/s]

 17%|█▋        | 1040/6015 [07:16<34:27,  2.41it/s]

 17%|█▋        | 1041/6015 [07:16<34:28,  2.40it/s]

 17%|█▋        | 1042/6015 [07:16<34:27,  2.40it/s]

 17%|█▋        | 1043/6015 [07:17<34:27,  2.40it/s]

 17%|█▋        | 1044/6015 [07:17<34:30,  2.40it/s]

 17%|█▋        | 1045/6015 [07:18<34:28,  2.40it/s]

 17%|█▋        | 1046/6015 [07:18<34:29,  2.40it/s]

 17%|█▋        | 1047/6015 [07:18<34:26,  2.40it/s]

 17%|█▋        | 1048/6015 [07:19<34:26,  2.40it/s]

 17%|█▋        | 1049/6015 [07:19<34:26,  2.40it/s]

 17%|█▋        | 1050/6015 [07:20<34:27,  2.40it/s]

 17%|█▋        | 1051/6015 [07:20<34:25,  2.40it/s]

 17%|█▋        | 1052/6015 [07:21<34:26,  2.40it/s]

 18%|█▊        | 1053/6015 [07:21<34:24,  2.40it/s]

 18%|█▊        | 1054/6015 [07:21<34:23,  2.40it/s]

 18%|█▊        | 1055/6015 [07:22<34:22,  2.40it/s]

 18%|█▊        | 1056/6015 [07:22<34:23,  2.40it/s]

 18%|█▊        | 1057/6015 [07:23<34:20,  2.41it/s]

 18%|█▊        | 1058/6015 [07:23<34:26,  2.40it/s]

 18%|█▊        | 1059/6015 [07:23<34:24,  2.40it/s]

 18%|█▊        | 1060/6015 [07:24<34:23,  2.40it/s]

 18%|█▊        | 1061/6015 [07:24<34:20,  2.40it/s]

 18%|█▊        | 1062/6015 [07:25<34:20,  2.40it/s]

 18%|█▊        | 1063/6015 [07:25<34:22,  2.40it/s]

 18%|█▊        | 1064/6015 [07:26<34:21,  2.40it/s]

 18%|█▊        | 1065/6015 [07:26<34:20,  2.40it/s]

 18%|█▊        | 1066/6015 [07:26<34:20,  2.40it/s]

 18%|█▊        | 1067/6015 [07:27<34:19,  2.40it/s]

 18%|█▊        | 1068/6015 [07:27<34:18,  2.40it/s]

 18%|█▊        | 1069/6015 [07:28<34:18,  2.40it/s]

 18%|█▊        | 1070/6015 [07:28<34:17,  2.40it/s]

 18%|█▊        | 1071/6015 [07:28<34:21,  2.40it/s]

 18%|█▊        | 1072/6015 [07:29<34:19,  2.40it/s]

 18%|█▊        | 1073/6015 [07:29<34:20,  2.40it/s]

 18%|█▊        | 1074/6015 [07:30<34:18,  2.40it/s]

 18%|█▊        | 1075/6015 [07:30<34:22,  2.40it/s]

 18%|█▊        | 1076/6015 [07:31<34:19,  2.40it/s]

 18%|█▊        | 1077/6015 [07:31<34:20,  2.40it/s]

 18%|█▊        | 1078/6015 [07:31<34:19,  2.40it/s]

 18%|█▊        | 1079/6015 [07:32<34:17,  2.40it/s]

 18%|█▊        | 1080/6015 [07:32<34:15,  2.40it/s]

 18%|█▊        | 1081/6015 [07:33<34:16,  2.40it/s]

 18%|█▊        | 1082/6015 [07:33<34:15,  2.40it/s]

 18%|█▊        | 1083/6015 [07:33<34:16,  2.40it/s]

 18%|█▊        | 1084/6015 [07:34<34:15,  2.40it/s]

 18%|█▊        | 1085/6015 [07:34<34:15,  2.40it/s]

 18%|█▊        | 1086/6015 [07:35<34:16,  2.40it/s]

 18%|█▊        | 1087/6015 [07:35<34:16,  2.40it/s]

 18%|█▊        | 1088/6015 [07:36<34:14,  2.40it/s]

 18%|█▊        | 1089/6015 [07:36<34:12,  2.40it/s]

 18%|█▊        | 1090/6015 [07:36<34:14,  2.40it/s]

 18%|█▊        | 1091/6015 [07:37<34:10,  2.40it/s]

 18%|█▊        | 1092/6015 [07:37<34:12,  2.40it/s]

 18%|█▊        | 1093/6015 [07:38<34:12,  2.40it/s]

 18%|█▊        | 1094/6015 [07:38<34:11,  2.40it/s]

 18%|█▊        | 1095/6015 [07:38<34:12,  2.40it/s]

 18%|█▊        | 1096/6015 [07:39<34:11,  2.40it/s]

 18%|█▊        | 1097/6015 [07:39<34:11,  2.40it/s]

 18%|█▊        | 1098/6015 [07:40<34:08,  2.40it/s]

 18%|█▊        | 1099/6015 [07:40<34:09,  2.40it/s]

 18%|█▊        | 1100/6015 [07:41<34:08,  2.40it/s]

 18%|█▊        | 1101/6015 [07:41<34:10,  2.40it/s]

 18%|█▊        | 1102/6015 [07:41<34:07,  2.40it/s]

 18%|█▊        | 1103/6015 [07:42<34:06,  2.40it/s]

 18%|█▊        | 1104/6015 [07:42<34:06,  2.40it/s]

 18%|█▊        | 1105/6015 [07:43<34:06,  2.40it/s]

 18%|█▊        | 1106/6015 [07:43<34:04,  2.40it/s]

 18%|█▊        | 1107/6015 [07:43<34:06,  2.40it/s]

 18%|█▊        | 1108/6015 [07:44<34:05,  2.40it/s]

 18%|█▊        | 1109/6015 [07:44<34:08,  2.39it/s]

 18%|█▊        | 1110/6015 [07:45<34:06,  2.40it/s]

 18%|█▊        | 1111/6015 [07:45<34:05,  2.40it/s]

 18%|█▊        | 1112/6015 [07:46<34:05,  2.40it/s]

 19%|█▊        | 1113/6015 [07:46<34:03,  2.40it/s]

 19%|█▊        | 1114/6015 [07:46<34:02,  2.40it/s]

 19%|█▊        | 1115/6015 [07:47<34:02,  2.40it/s]

 19%|█▊        | 1116/6015 [07:47<34:01,  2.40it/s]

 19%|█▊        | 1117/6015 [07:48<34:00,  2.40it/s]

 19%|█▊        | 1118/6015 [07:48<33:59,  2.40it/s]

 19%|█▊        | 1119/6015 [07:48<34:01,  2.40it/s]

 19%|█▊        | 1120/6015 [07:49<34:01,  2.40it/s]

 19%|█▊        | 1121/6015 [07:49<34:03,  2.40it/s]

 19%|█▊        | 1122/6015 [07:50<34:01,  2.40it/s]

 19%|█▊        | 1123/6015 [07:50<34:01,  2.40it/s]

 19%|█▊        | 1124/6015 [07:51<34:01,  2.40it/s]

 19%|█▊        | 1125/6015 [07:51<34:01,  2.39it/s]

 19%|█▊        | 1126/6015 [07:51<34:02,  2.39it/s]

 19%|█▊        | 1127/6015 [07:52<34:03,  2.39it/s]

 19%|█▉        | 1128/6015 [07:52<34:02,  2.39it/s]

 19%|█▉        | 1129/6015 [07:53<34:02,  2.39it/s]

 19%|█▉        | 1130/6015 [07:53<34:03,  2.39it/s]

 19%|█▉        | 1131/6015 [07:53<34:00,  2.39it/s]

 19%|█▉        | 1132/6015 [07:54<34:10,  2.38it/s]

 19%|█▉        | 1133/6015 [07:54<34:02,  2.39it/s]

 19%|█▉        | 1134/6015 [07:55<34:01,  2.39it/s]

 19%|█▉        | 1135/6015 [07:55<34:00,  2.39it/s]

 19%|█▉        | 1136/6015 [07:56<33:57,  2.39it/s]

 19%|█▉        | 1137/6015 [07:56<33:55,  2.40it/s]

 19%|█▉        | 1138/6015 [07:56<33:52,  2.40it/s]

 19%|█▉        | 1139/6015 [07:57<33:52,  2.40it/s]

 19%|█▉        | 1140/6015 [07:57<33:51,  2.40it/s]

 19%|█▉        | 1141/6015 [07:58<33:52,  2.40it/s]

 19%|█▉        | 1142/6015 [07:58<33:52,  2.40it/s]

 19%|█▉        | 1143/6015 [07:58<33:52,  2.40it/s]

 19%|█▉        | 1144/6015 [07:59<33:53,  2.39it/s]

 19%|█▉        | 1145/6015 [07:59<33:53,  2.39it/s]

 19%|█▉        | 1146/6015 [08:00<33:56,  2.39it/s]

 19%|█▉        | 1147/6015 [08:00<33:53,  2.39it/s]

 19%|█▉        | 1148/6015 [08:01<33:52,  2.40it/s]

 19%|█▉        | 1149/6015 [08:01<33:51,  2.40it/s]

 19%|█▉        | 1150/6015 [08:01<33:52,  2.39it/s]

 19%|█▉        | 1151/6015 [08:02<33:51,  2.39it/s]

 19%|█▉        | 1152/6015 [08:02<33:52,  2.39it/s]

 19%|█▉        | 1153/6015 [08:03<33:49,  2.40it/s]

 19%|█▉        | 1154/6015 [08:03<33:49,  2.40it/s]

 19%|█▉        | 1155/6015 [08:03<33:49,  2.39it/s]

 19%|█▉        | 1156/6015 [08:04<33:53,  2.39it/s]

 19%|█▉        | 1157/6015 [08:04<33:52,  2.39it/s]

 19%|█▉        | 1158/6015 [08:05<33:52,  2.39it/s]

 19%|█▉        | 1159/6015 [08:05<33:50,  2.39it/s]

 19%|█▉        | 1160/6015 [08:06<33:50,  2.39it/s]

 19%|█▉        | 1161/6015 [08:06<33:48,  2.39it/s]

 19%|█▉        | 1162/6015 [08:06<33:48,  2.39it/s]

 19%|█▉        | 1163/6015 [08:07<33:43,  2.40it/s]

 19%|█▉        | 1164/6015 [08:07<33:47,  2.39it/s]

 19%|█▉        | 1165/6015 [08:08<33:51,  2.39it/s]

 19%|█▉        | 1166/6015 [08:08<33:49,  2.39it/s]

 19%|█▉        | 1167/6015 [08:09<33:47,  2.39it/s]

 19%|█▉        | 1168/6015 [08:09<33:47,  2.39it/s]

 19%|█▉        | 1169/6015 [08:09<33:44,  2.39it/s]

 19%|█▉        | 1170/6015 [08:10<33:44,  2.39it/s]

 19%|█▉        | 1171/6015 [08:10<33:42,  2.40it/s]

 19%|█▉        | 1172/6015 [08:11<33:42,  2.39it/s]

 20%|█▉        | 1173/6015 [08:11<33:40,  2.40it/s]

 20%|█▉        | 1174/6015 [08:11<33:41,  2.40it/s]

 20%|█▉        | 1175/6015 [08:12<33:43,  2.39it/s]

 20%|█▉        | 1176/6015 [08:12<33:42,  2.39it/s]

 20%|█▉        | 1177/6015 [08:13<33:40,  2.39it/s]

 20%|█▉        | 1178/6015 [08:13<33:39,  2.39it/s]

 20%|█▉        | 1179/6015 [08:14<33:41,  2.39it/s]

 20%|█▉        | 1180/6015 [08:14<33:42,  2.39it/s]

 20%|█▉        | 1181/6015 [08:14<33:41,  2.39it/s]

 20%|█▉        | 1182/6015 [08:15<33:41,  2.39it/s]

 20%|█▉        | 1183/6015 [08:15<33:39,  2.39it/s]

 20%|█▉        | 1184/6015 [08:16<33:36,  2.40it/s]

 20%|█▉        | 1185/6015 [08:16<33:39,  2.39it/s]

 20%|█▉        | 1186/6015 [08:16<33:37,  2.39it/s]

 20%|█▉        | 1187/6015 [08:17<33:38,  2.39it/s]

 20%|█▉        | 1188/6015 [08:17<33:37,  2.39it/s]

 20%|█▉        | 1189/6015 [08:18<33:39,  2.39it/s]

 20%|█▉        | 1190/6015 [08:18<33:37,  2.39it/s]

 20%|█▉        | 1191/6015 [08:19<33:49,  2.38it/s]

 20%|█▉        | 1192/6015 [08:19<33:45,  2.38it/s]

 20%|█▉        | 1193/6015 [08:19<33:45,  2.38it/s]

 20%|█▉        | 1194/6015 [08:20<33:42,  2.38it/s]

 20%|█▉        | 1195/6015 [08:20<33:40,  2.39it/s]

 20%|█▉        | 1196/6015 [08:21<33:34,  2.39it/s]

 20%|█▉        | 1197/6015 [08:21<33:39,  2.39it/s]

 20%|█▉        | 1198/6015 [08:21<33:38,  2.39it/s]

 20%|█▉        | 1199/6015 [08:22<33:37,  2.39it/s]

 20%|█▉        | 1200/6015 [08:22<33:37,  2.39it/s]

 20%|█▉        | 1201/6015 [08:23<33:37,  2.39it/s]

 20%|█▉        | 1202/6015 [08:23<33:35,  2.39it/s]

 20%|██        | 1203/6015 [08:24<33:35,  2.39it/s]

 20%|██        | 1204/6015 [08:24<33:33,  2.39it/s]

 20%|██        | 1205/6015 [08:24<33:39,  2.38it/s]

 20%|██        | 1206/6015 [08:25<33:38,  2.38it/s]

 20%|██        | 1207/6015 [08:25<33:35,  2.39it/s]

 20%|██        | 1208/6015 [08:26<33:33,  2.39it/s]

 20%|██        | 1209/6015 [08:26<33:35,  2.38it/s]

 20%|██        | 1210/6015 [08:27<33:33,  2.39it/s]

 20%|██        | 1211/6015 [08:27<33:32,  2.39it/s]

 20%|██        | 1212/6015 [08:27<33:34,  2.38it/s]

 20%|██        | 1213/6015 [08:28<33:42,  2.37it/s]

 20%|██        | 1214/6015 [08:28<33:37,  2.38it/s]

 20%|██        | 1215/6015 [08:29<33:34,  2.38it/s]

 20%|██        | 1216/6015 [08:29<33:28,  2.39it/s]

 20%|██        | 1217/6015 [08:29<33:32,  2.38it/s]

 20%|██        | 1218/6015 [08:30<33:30,  2.39it/s]

 20%|██        | 1219/6015 [08:30<33:31,  2.38it/s]

 20%|██        | 1220/6015 [08:31<33:29,  2.39it/s]

 20%|██        | 1221/6015 [08:31<33:30,  2.38it/s]

 20%|██        | 1222/6015 [08:32<33:32,  2.38it/s]

 20%|██        | 1223/6015 [08:32<33:30,  2.38it/s]

 20%|██        | 1224/6015 [08:32<33:28,  2.39it/s]

 20%|██        | 1225/6015 [08:33<33:29,  2.38it/s]

 20%|██        | 1226/6015 [08:33<33:26,  2.39it/s]

 20%|██        | 1227/6015 [08:34<33:28,  2.38it/s]

 20%|██        | 1228/6015 [08:34<33:28,  2.38it/s]

 20%|██        | 1229/6015 [08:34<33:28,  2.38it/s]

 20%|██        | 1230/6015 [08:35<33:25,  2.39it/s]

 20%|██        | 1231/6015 [08:35<33:24,  2.39it/s]

 20%|██        | 1232/6015 [08:36<33:24,  2.39it/s]

 20%|██        | 1233/6015 [08:36<33:26,  2.38it/s]

 21%|██        | 1234/6015 [08:37<33:24,  2.39it/s]

 21%|██        | 1235/6015 [08:37<33:30,  2.38it/s]

 21%|██        | 1236/6015 [08:37<33:28,  2.38it/s]

 21%|██        | 1237/6015 [08:38<33:27,  2.38it/s]

 21%|██        | 1238/6015 [08:38<33:24,  2.38it/s]

 21%|██        | 1239/6015 [08:39<33:23,  2.38it/s]

 21%|██        | 1240/6015 [08:39<33:22,  2.38it/s]

 21%|██        | 1241/6015 [08:40<33:20,  2.39it/s]

 21%|██        | 1242/6015 [08:40<33:17,  2.39it/s]

 21%|██        | 1243/6015 [08:40<33:18,  2.39it/s]

 21%|██        | 1244/6015 [08:41<33:21,  2.38it/s]

 21%|██        | 1245/6015 [08:41<33:20,  2.38it/s]

 21%|██        | 1246/6015 [08:42<33:20,  2.38it/s]

 21%|██        | 1247/6015 [08:42<33:22,  2.38it/s]

 21%|██        | 1248/6015 [08:42<33:21,  2.38it/s]

 21%|██        | 1249/6015 [08:43<33:23,  2.38it/s]

 21%|██        | 1250/6015 [08:43<33:21,  2.38it/s]

 21%|██        | 1251/6015 [08:44<33:21,  2.38it/s]

logging
logging the anndata

 21%|██        | 1252/6015 [08:44<34:29,  2.30it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 21%|██        | 1253/6015 [08:45<33:57,  2.34it/s]

 21%|██        | 1254/6015 [08:45<33:33,  2.36it/s]

 21%|██        | 1255/6015 [08:45<33:17,  2.38it/s]

 21%|██        | 1256/6015 [08:46<33:04,  2.40it/s]

 21%|██        | 1257/6015 [08:46<32:54,  2.41it/s]

 21%|██        | 1258/6015 [08:47<32:55,  2.41it/s]

 21%|██        | 1259/6015 [08:47<32:50,  2.41it/s]

 21%|██        | 1260/6015 [08:47<32:46,  2.42it/s]

 21%|██        | 1261/6015 [08:48<32:46,  2.42it/s]

 21%|██        | 1262/6015 [08:48<32:44,  2.42it/s]

 21%|██        | 1263/6015 [08:49<32:42,  2.42it/s]

 21%|██        | 1264/6015 [08:49<32:42,  2.42it/s]

 21%|██        | 1265/6015 [08:50<32:40,  2.42it/s]

 21%|██        | 1266/6015 [08:50<32:41,  2.42it/s]

 21%|██        | 1267/6015 [08:50<32:38,  2.42it/s]

 21%|██        | 1268/6015 [08:51<32:39,  2.42it/s]

 21%|██        | 1269/6015 [08:51<32:42,  2.42it/s]

 21%|██        | 1270/6015 [08:52<32:41,  2.42it/s]

 21%|██        | 1271/6015 [08:52<32:44,  2.42it/s]

 21%|██        | 1272/6015 [08:52<32:40,  2.42it/s]

 21%|██        | 1273/6015 [08:53<32:38,  2.42it/s]

 21%|██        | 1274/6015 [08:53<32:38,  2.42it/s]

 21%|██        | 1275/6015 [08:54<32:36,  2.42it/s]

 21%|██        | 1276/6015 [08:54<32:35,  2.42it/s]

 21%|██        | 1277/6015 [08:54<32:34,  2.42it/s]

 21%|██        | 1278/6015 [08:55<32:32,  2.43it/s]

 21%|██▏       | 1279/6015 [08:55<32:34,  2.42it/s]

 21%|██▏       | 1280/6015 [08:56<32:34,  2.42it/s]

 21%|██▏       | 1281/6015 [08:56<32:34,  2.42it/s]

 21%|██▏       | 1282/6015 [08:57<32:32,  2.42it/s]

 21%|██▏       | 1283/6015 [08:57<32:33,  2.42it/s]

 21%|██▏       | 1284/6015 [08:57<32:31,  2.42it/s]

 21%|██▏       | 1285/6015 [08:58<32:31,  2.42it/s]

 21%|██▏       | 1286/6015 [08:58<32:30,  2.42it/s]

 21%|██▏       | 1287/6015 [08:59<32:29,  2.42it/s]

 21%|██▏       | 1288/6015 [08:59<32:28,  2.43it/s]

 21%|██▏       | 1289/6015 [08:59<32:29,  2.42it/s]

 21%|██▏       | 1290/6015 [09:00<32:29,  2.42it/s]

 21%|██▏       | 1291/6015 [09:00<32:29,  2.42it/s]

 21%|██▏       | 1292/6015 [09:01<32:31,  2.42it/s]

 21%|██▏       | 1293/6015 [09:01<32:31,  2.42it/s]

 22%|██▏       | 1294/6015 [09:02<32:31,  2.42it/s]

 22%|██▏       | 1295/6015 [09:02<32:31,  2.42it/s]

 22%|██▏       | 1296/6015 [09:02<32:28,  2.42it/s]

 22%|██▏       | 1297/6015 [09:03<32:27,  2.42it/s]

 22%|██▏       | 1298/6015 [09:03<32:27,  2.42it/s]

 22%|██▏       | 1299/6015 [09:04<32:28,  2.42it/s]

 22%|██▏       | 1300/6015 [09:04<32:27,  2.42it/s]

 22%|██▏       | 1301/6015 [09:04<32:26,  2.42it/s]

 22%|██▏       | 1302/6015 [09:05<32:26,  2.42it/s]

 22%|██▏       | 1303/6015 [09:05<32:27,  2.42it/s]

 22%|██▏       | 1304/6015 [09:06<32:26,  2.42it/s]

 22%|██▏       | 1305/6015 [09:06<32:25,  2.42it/s]

 22%|██▏       | 1306/6015 [09:06<32:24,  2.42it/s]

 22%|██▏       | 1307/6015 [09:07<32:24,  2.42it/s]

 22%|██▏       | 1308/6015 [09:07<32:25,  2.42it/s]

 22%|██▏       | 1309/6015 [09:08<32:26,  2.42it/s]

 22%|██▏       | 1310/6015 [09:08<32:27,  2.42it/s]

 22%|██▏       | 1311/6015 [09:09<32:25,  2.42it/s]

 22%|██▏       | 1312/6015 [09:09<32:24,  2.42it/s]

 22%|██▏       | 1313/6015 [09:09<32:25,  2.42it/s]

 22%|██▏       | 1314/6015 [09:10<32:25,  2.42it/s]

 22%|██▏       | 1315/6015 [09:10<32:26,  2.41it/s]

 22%|██▏       | 1316/6015 [09:11<32:30,  2.41it/s]

 22%|██▏       | 1317/6015 [09:11<32:25,  2.41it/s]

 22%|██▏       | 1318/6015 [09:11<32:25,  2.41it/s]

 22%|██▏       | 1319/6015 [09:12<32:24,  2.41it/s]

 22%|██▏       | 1320/6015 [09:12<32:22,  2.42it/s]

 22%|██▏       | 1321/6015 [09:13<32:20,  2.42it/s]

 22%|██▏       | 1322/6015 [09:13<32:20,  2.42it/s]

 22%|██▏       | 1323/6015 [09:13<32:18,  2.42it/s]

 22%|██▏       | 1324/6015 [09:14<32:19,  2.42it/s]

 22%|██▏       | 1325/6015 [09:14<32:18,  2.42it/s]

 22%|██▏       | 1326/6015 [09:15<32:17,  2.42it/s]

 22%|██▏       | 1327/6015 [09:15<32:16,  2.42it/s]

 22%|██▏       | 1328/6015 [09:16<32:16,  2.42it/s]

 22%|██▏       | 1329/6015 [09:16<32:19,  2.42it/s]

 22%|██▏       | 1330/6015 [09:16<32:17,  2.42it/s]

 22%|██▏       | 1331/6015 [09:17<32:16,  2.42it/s]

 22%|██▏       | 1332/6015 [09:17<32:15,  2.42it/s]

 22%|██▏       | 1333/6015 [09:18<32:15,  2.42it/s]

 22%|██▏       | 1334/6015 [09:18<32:13,  2.42it/s]

 22%|██▏       | 1335/6015 [09:18<32:14,  2.42it/s]

 22%|██▏       | 1336/6015 [09:19<32:13,  2.42it/s]

 22%|██▏       | 1337/6015 [09:19<32:13,  2.42it/s]

 22%|██▏       | 1338/6015 [09:20<32:25,  2.40it/s]

 22%|██▏       | 1339/6015 [09:20<32:23,  2.41it/s]

 22%|██▏       | 1340/6015 [09:21<32:19,  2.41it/s]

 22%|██▏       | 1341/6015 [09:21<32:16,  2.41it/s]

 22%|██▏       | 1342/6015 [09:21<32:16,  2.41it/s]

 22%|██▏       | 1343/6015 [09:22<32:15,  2.41it/s]

 22%|██▏       | 1344/6015 [09:22<32:15,  2.41it/s]

 22%|██▏       | 1345/6015 [09:23<32:14,  2.41it/s]

 22%|██▏       | 1346/6015 [09:23<32:13,  2.41it/s]

 22%|██▏       | 1347/6015 [09:23<32:11,  2.42it/s]

 22%|██▏       | 1348/6015 [09:24<32:11,  2.42it/s]

 22%|██▏       | 1349/6015 [09:24<32:11,  2.42it/s]

 22%|██▏       | 1350/6015 [09:25<32:09,  2.42it/s]

 22%|██▏       | 1351/6015 [09:25<32:07,  2.42it/s]

 22%|██▏       | 1352/6015 [09:26<32:11,  2.41it/s]

 22%|██▏       | 1353/6015 [09:26<32:09,  2.42it/s]

 23%|██▎       | 1354/6015 [09:26<32:08,  2.42it/s]

 23%|██▎       | 1355/6015 [09:27<32:07,  2.42it/s]

 23%|██▎       | 1356/6015 [09:27<32:05,  2.42it/s]

 23%|██▎       | 1357/6015 [09:28<32:06,  2.42it/s]

 23%|██▎       | 1358/6015 [09:28<32:04,  2.42it/s]

 23%|██▎       | 1359/6015 [09:28<32:07,  2.42it/s]

 23%|██▎       | 1360/6015 [09:29<32:06,  2.42it/s]

 23%|██▎       | 1361/6015 [09:29<32:05,  2.42it/s]

 23%|██▎       | 1362/6015 [09:30<32:05,  2.42it/s]

 23%|██▎       | 1363/6015 [09:30<32:07,  2.41it/s]

 23%|██▎       | 1364/6015 [09:30<32:06,  2.41it/s]

 23%|██▎       | 1365/6015 [09:31<32:07,  2.41it/s]

 23%|██▎       | 1366/6015 [09:31<32:05,  2.41it/s]

 23%|██▎       | 1367/6015 [09:32<32:06,  2.41it/s]

 23%|██▎       | 1368/6015 [09:32<32:03,  2.42it/s]

 23%|██▎       | 1369/6015 [09:33<32:05,  2.41it/s]

 23%|██▎       | 1370/6015 [09:33<32:03,  2.42it/s]

 23%|██▎       | 1371/6015 [09:33<32:02,  2.42it/s]

 23%|██▎       | 1372/6015 [09:34<32:05,  2.41it/s]

 23%|██▎       | 1373/6015 [09:34<32:05,  2.41it/s]

 23%|██▎       | 1374/6015 [09:35<32:04,  2.41it/s]

 23%|██▎       | 1375/6015 [09:35<32:02,  2.41it/s]

 23%|██▎       | 1376/6015 [09:35<32:01,  2.41it/s]

 23%|██▎       | 1377/6015 [09:36<31:59,  2.42it/s]

 23%|██▎       | 1378/6015 [09:36<32:01,  2.41it/s]

 23%|██▎       | 1379/6015 [09:37<32:01,  2.41it/s]

 23%|██▎       | 1380/6015 [09:37<31:59,  2.41it/s]

 23%|██▎       | 1381/6015 [09:38<31:58,  2.42it/s]

 23%|██▎       | 1382/6015 [09:38<31:56,  2.42it/s]

 23%|██▎       | 1383/6015 [09:38<31:54,  2.42it/s]

 23%|██▎       | 1384/6015 [09:39<31:56,  2.42it/s]

 23%|██▎       | 1385/6015 [09:39<31:53,  2.42it/s]

 23%|██▎       | 1386/6015 [09:40<31:53,  2.42it/s]

 23%|██▎       | 1387/6015 [09:40<31:52,  2.42it/s]

 23%|██▎       | 1388/6015 [09:40<31:52,  2.42it/s]

 23%|██▎       | 1389/6015 [09:41<31:52,  2.42it/s]

 23%|██▎       | 1390/6015 [09:41<31:51,  2.42it/s]

 23%|██▎       | 1391/6015 [09:42<31:50,  2.42it/s]

 23%|██▎       | 1392/6015 [09:42<31:48,  2.42it/s]

 23%|██▎       | 1393/6015 [09:42<31:48,  2.42it/s]

 23%|██▎       | 1394/6015 [09:43<31:47,  2.42it/s]

 23%|██▎       | 1395/6015 [09:43<31:47,  2.42it/s]

 23%|██▎       | 1396/6015 [09:44<31:48,  2.42it/s]

 23%|██▎       | 1397/6015 [09:44<31:47,  2.42it/s]

 23%|██▎       | 1398/6015 [09:45<31:48,  2.42it/s]

 23%|██▎       | 1399/6015 [09:45<31:49,  2.42it/s]

 23%|██▎       | 1400/6015 [09:45<31:48,  2.42it/s]

 23%|██▎       | 1401/6015 [09:46<31:48,  2.42it/s]

 23%|██▎       | 1402/6015 [09:46<31:48,  2.42it/s]

 23%|██▎       | 1403/6015 [09:47<31:47,  2.42it/s]

 23%|██▎       | 1404/6015 [09:47<31:49,  2.42it/s]

 23%|██▎       | 1405/6015 [09:47<31:48,  2.42it/s]

 23%|██▎       | 1406/6015 [09:48<31:48,  2.41it/s]

 23%|██▎       | 1407/6015 [09:48<31:48,  2.41it/s]

 23%|██▎       | 1408/6015 [09:49<31:47,  2.42it/s]

 23%|██▎       | 1409/6015 [09:49<31:46,  2.42it/s]

 23%|██▎       | 1410/6015 [09:50<31:47,  2.41it/s]

 23%|██▎       | 1411/6015 [09:50<31:47,  2.41it/s]

 23%|██▎       | 1412/6015 [09:50<31:45,  2.42it/s]

 23%|██▎       | 1413/6015 [09:51<31:44,  2.42it/s]

 24%|██▎       | 1414/6015 [09:51<31:42,  2.42it/s]

 24%|██▎       | 1415/6015 [09:52<31:44,  2.42it/s]

 24%|██▎       | 1416/6015 [09:52<31:42,  2.42it/s]

 24%|██▎       | 1417/6015 [09:52<31:40,  2.42it/s]

 24%|██▎       | 1418/6015 [09:53<31:39,  2.42it/s]

 24%|██▎       | 1419/6015 [09:53<31:40,  2.42it/s]

 24%|██▎       | 1420/6015 [09:54<31:41,  2.42it/s]

 24%|██▎       | 1421/6015 [09:54<31:38,  2.42it/s]

 24%|██▎       | 1422/6015 [09:54<31:40,  2.42it/s]

 24%|██▎       | 1423/6015 [09:55<31:39,  2.42it/s]

 24%|██▎       | 1424/6015 [09:55<31:39,  2.42it/s]

 24%|██▎       | 1425/6015 [09:56<31:37,  2.42it/s]

 24%|██▎       | 1426/6015 [09:56<31:37,  2.42it/s]

 24%|██▎       | 1427/6015 [09:57<31:37,  2.42it/s]

 24%|██▎       | 1428/6015 [09:57<31:37,  2.42it/s]

 24%|██▍       | 1429/6015 [09:57<31:43,  2.41it/s]

 24%|██▍       | 1430/6015 [09:58<31:41,  2.41it/s]

 24%|██▍       | 1431/6015 [09:58<31:41,  2.41it/s]

 24%|██▍       | 1432/6015 [09:59<31:38,  2.41it/s]

 24%|██▍       | 1433/6015 [09:59<31:38,  2.41it/s]

 24%|██▍       | 1434/6015 [09:59<31:42,  2.41it/s]

 24%|██▍       | 1435/6015 [10:00<31:42,  2.41it/s]

 24%|██▍       | 1436/6015 [10:00<31:38,  2.41it/s]

 24%|██▍       | 1437/6015 [10:01<31:39,  2.41it/s]

 24%|██▍       | 1438/6015 [10:01<31:37,  2.41it/s]

 24%|██▍       | 1439/6015 [10:02<31:39,  2.41it/s]

 24%|██▍       | 1440/6015 [10:02<31:35,  2.41it/s]

 24%|██▍       | 1441/6015 [10:02<31:34,  2.41it/s]

 24%|██▍       | 1442/6015 [10:03<31:31,  2.42it/s]

 24%|██▍       | 1443/6015 [10:03<31:31,  2.42it/s]

 24%|██▍       | 1444/6015 [10:04<31:32,  2.42it/s]

 24%|██▍       | 1445/6015 [10:04<31:33,  2.41it/s]

 24%|██▍       | 1446/6015 [10:04<31:32,  2.41it/s]

 24%|██▍       | 1447/6015 [10:05<31:30,  2.42it/s]

 24%|██▍       | 1448/6015 [10:05<31:29,  2.42it/s]

 24%|██▍       | 1449/6015 [10:06<31:28,  2.42it/s]

 24%|██▍       | 1450/6015 [10:06<31:29,  2.42it/s]

 24%|██▍       | 1451/6015 [10:06<31:26,  2.42it/s]

 24%|██▍       | 1452/6015 [10:07<31:27,  2.42it/s]

 24%|██▍       | 1453/6015 [10:07<31:25,  2.42it/s]

 24%|██▍       | 1454/6015 [10:08<31:26,  2.42it/s]

 24%|██▍       | 1455/6015 [10:08<31:23,  2.42it/s]

 24%|██▍       | 1456/6015 [10:09<31:24,  2.42it/s]

 24%|██▍       | 1457/6015 [10:09<31:24,  2.42it/s]

 24%|██▍       | 1458/6015 [10:09<31:24,  2.42it/s]

 24%|██▍       | 1459/6015 [10:10<31:22,  2.42it/s]

 24%|██▍       | 1460/6015 [10:10<31:22,  2.42it/s]

 24%|██▍       | 1461/6015 [10:11<31:30,  2.41it/s]

 24%|██▍       | 1462/6015 [10:11<31:28,  2.41it/s]

 24%|██▍       | 1463/6015 [10:11<31:26,  2.41it/s]

 24%|██▍       | 1464/6015 [10:12<31:25,  2.41it/s]

 24%|██▍       | 1465/6015 [10:12<31:25,  2.41it/s]

 24%|██▍       | 1466/6015 [10:13<31:25,  2.41it/s]

 24%|██▍       | 1467/6015 [10:13<31:24,  2.41it/s]

 24%|██▍       | 1468/6015 [10:14<31:22,  2.42it/s]

 24%|██▍       | 1469/6015 [10:14<31:25,  2.41it/s]

 24%|██▍       | 1470/6015 [10:14<31:23,  2.41it/s]

 24%|██▍       | 1471/6015 [10:15<31:21,  2.41it/s]

 24%|██▍       | 1472/6015 [10:15<31:23,  2.41it/s]

 24%|██▍       | 1473/6015 [10:16<31:23,  2.41it/s]

 25%|██▍       | 1474/6015 [10:16<31:22,  2.41it/s]

 25%|██▍       | 1475/6015 [10:16<31:24,  2.41it/s]

 25%|██▍       | 1476/6015 [10:17<31:20,  2.41it/s]

 25%|██▍       | 1477/6015 [10:17<31:21,  2.41it/s]

 25%|██▍       | 1478/6015 [10:18<31:23,  2.41it/s]

 25%|██▍       | 1479/6015 [10:18<31:20,  2.41it/s]

 25%|██▍       | 1480/6015 [10:18<31:20,  2.41it/s]

 25%|██▍       | 1481/6015 [10:19<31:17,  2.41it/s]

 25%|██▍       | 1482/6015 [10:19<31:20,  2.41it/s]

 25%|██▍       | 1483/6015 [10:20<31:17,  2.41it/s]

 25%|██▍       | 1484/6015 [10:20<31:16,  2.41it/s]

 25%|██▍       | 1485/6015 [10:21<31:18,  2.41it/s]

 25%|██▍       | 1486/6015 [10:21<31:23,  2.40it/s]

 25%|██▍       | 1487/6015 [10:21<31:20,  2.41it/s]

 25%|██▍       | 1488/6015 [10:22<31:17,  2.41it/s]

 25%|██▍       | 1489/6015 [10:22<31:16,  2.41it/s]

 25%|██▍       | 1490/6015 [10:23<31:16,  2.41it/s]

 25%|██▍       | 1491/6015 [10:23<31:15,  2.41it/s]

 25%|██▍       | 1492/6015 [10:23<31:16,  2.41it/s]

 25%|██▍       | 1493/6015 [10:24<31:12,  2.41it/s]

 25%|██▍       | 1494/6015 [10:24<31:13,  2.41it/s]

 25%|██▍       | 1495/6015 [10:25<31:13,  2.41it/s]

 25%|██▍       | 1496/6015 [10:25<31:12,  2.41it/s]

 25%|██▍       | 1497/6015 [10:26<31:11,  2.41it/s]

 25%|██▍       | 1498/6015 [10:26<31:11,  2.41it/s]

 25%|██▍       | 1499/6015 [10:26<31:10,  2.41it/s]

 25%|██▍       | 1500/6015 [10:27<31:10,  2.41it/s]

 25%|██▍       | 1501/6015 [10:27<31:12,  2.41it/s]

 25%|██▍       | 1502/6015 [10:28<31:14,  2.41it/s]

 25%|██▍       | 1503/6015 [10:28<31:15,  2.41it/s]

 25%|██▌       | 1504/6015 [10:28<31:12,  2.41it/s]

 25%|██▌       | 1505/6015 [10:29<31:14,  2.41it/s]

 25%|██▌       | 1506/6015 [10:29<31:11,  2.41it/s]

 25%|██▌       | 1507/6015 [10:30<31:13,  2.41it/s]

 25%|██▌       | 1508/6015 [10:30<31:11,  2.41it/s]

 25%|██▌       | 1509/6015 [10:31<31:08,  2.41it/s]

 25%|██▌       | 1510/6015 [10:31<31:05,  2.41it/s]

 25%|██▌       | 1511/6015 [10:31<31:07,  2.41it/s]

 25%|██▌       | 1512/6015 [10:32<31:06,  2.41it/s]

 25%|██▌       | 1513/6015 [10:32<31:05,  2.41it/s]

 25%|██▌       | 1514/6015 [10:33<31:06,  2.41it/s]

 25%|██▌       | 1515/6015 [10:33<31:05,  2.41it/s]

 25%|██▌       | 1516/6015 [10:33<31:08,  2.41it/s]

 25%|██▌       | 1517/6015 [10:34<31:07,  2.41it/s]

 25%|██▌       | 1518/6015 [10:34<31:07,  2.41it/s]

 25%|██▌       | 1519/6015 [10:35<31:05,  2.41it/s]

 25%|██▌       | 1520/6015 [10:35<31:03,  2.41it/s]

 25%|██▌       | 1521/6015 [10:35<31:03,  2.41it/s]

 25%|██▌       | 1522/6015 [10:36<31:04,  2.41it/s]

 25%|██▌       | 1523/6015 [10:36<31:01,  2.41it/s]

 25%|██▌       | 1524/6015 [10:37<31:00,  2.41it/s]

 25%|██▌       | 1525/6015 [10:37<30:59,  2.41it/s]

 25%|██▌       | 1526/6015 [10:38<30:59,  2.41it/s]

 25%|██▌       | 1527/6015 [10:38<30:59,  2.41it/s]

 25%|██▌       | 1528/6015 [10:38<31:00,  2.41it/s]

 25%|██▌       | 1529/6015 [10:39<30:58,  2.41it/s]

 25%|██▌       | 1530/6015 [10:39<30:57,  2.41it/s]

 25%|██▌       | 1531/6015 [10:40<30:58,  2.41it/s]

 25%|██▌       | 1532/6015 [10:40<30:58,  2.41it/s]

 25%|██▌       | 1533/6015 [10:40<30:59,  2.41it/s]

 26%|██▌       | 1534/6015 [10:41<30:58,  2.41it/s]

 26%|██▌       | 1535/6015 [10:41<30:57,  2.41it/s]

 26%|██▌       | 1536/6015 [10:42<30:56,  2.41it/s]

 26%|██▌       | 1537/6015 [10:42<30:55,  2.41it/s]

 26%|██▌       | 1538/6015 [10:43<30:55,  2.41it/s]

 26%|██▌       | 1539/6015 [10:43<30:58,  2.41it/s]

 26%|██▌       | 1540/6015 [10:43<30:57,  2.41it/s]

 26%|██▌       | 1541/6015 [10:44<30:57,  2.41it/s]

 26%|██▌       | 1542/6015 [10:44<30:58,  2.41it/s]

 26%|██▌       | 1543/6015 [10:45<31:01,  2.40it/s]

 26%|██▌       | 1544/6015 [10:45<30:57,  2.41it/s]

 26%|██▌       | 1545/6015 [10:45<30:55,  2.41it/s]

 26%|██▌       | 1546/6015 [10:46<30:54,  2.41it/s]

 26%|██▌       | 1547/6015 [10:46<30:55,  2.41it/s]

 26%|██▌       | 1548/6015 [10:47<30:54,  2.41it/s]

 26%|██▌       | 1549/6015 [10:47<30:54,  2.41it/s]

 26%|██▌       | 1550/6015 [10:48<30:51,  2.41it/s]

 26%|██▌       | 1551/6015 [10:48<30:51,  2.41it/s]

 26%|██▌       | 1552/6015 [10:48<30:50,  2.41it/s]

 26%|██▌       | 1553/6015 [10:49<30:54,  2.41it/s]

 26%|██▌       | 1554/6015 [10:49<30:53,  2.41it/s]

 26%|██▌       | 1555/6015 [10:50<30:53,  2.41it/s]

 26%|██▌       | 1556/6015 [10:50<30:53,  2.41it/s]

 26%|██▌       | 1557/6015 [10:50<30:51,  2.41it/s]

 26%|██▌       | 1558/6015 [10:51<30:50,  2.41it/s]

 26%|██▌       | 1559/6015 [10:51<30:51,  2.41it/s]

 26%|██▌       | 1560/6015 [10:52<30:49,  2.41it/s]

 26%|██▌       | 1561/6015 [10:52<30:53,  2.40it/s]

 26%|██▌       | 1562/6015 [10:53<30:51,  2.41it/s]

 26%|██▌       | 1563/6015 [10:53<30:51,  2.41it/s]

 26%|██▌       | 1564/6015 [10:53<30:49,  2.41it/s]

 26%|██▌       | 1565/6015 [10:54<30:46,  2.41it/s]

 26%|██▌       | 1566/6015 [10:54<30:47,  2.41it/s]

 26%|██▌       | 1567/6015 [10:55<30:45,  2.41it/s]

 26%|██▌       | 1568/6015 [10:55<30:44,  2.41it/s]

 26%|██▌       | 1569/6015 [10:55<30:45,  2.41it/s]

 26%|██▌       | 1570/6015 [10:56<30:47,  2.41it/s]

 26%|██▌       | 1571/6015 [10:56<30:46,  2.41it/s]

 26%|██▌       | 1572/6015 [10:57<30:45,  2.41it/s]

 26%|██▌       | 1573/6015 [10:57<30:49,  2.40it/s]

 26%|██▌       | 1574/6015 [10:57<30:47,  2.40it/s]

 26%|██▌       | 1575/6015 [10:58<30:45,  2.41it/s]

 26%|██▌       | 1576/6015 [10:58<30:43,  2.41it/s]

 26%|██▌       | 1577/6015 [10:59<30:41,  2.41it/s]

 26%|██▌       | 1578/6015 [10:59<30:42,  2.41it/s]

 26%|██▋       | 1579/6015 [11:00<30:42,  2.41it/s]

 26%|██▋       | 1580/6015 [11:00<30:42,  2.41it/s]

 26%|██▋       | 1581/6015 [11:00<30:41,  2.41it/s]

 26%|██▋       | 1582/6015 [11:01<30:44,  2.40it/s]

 26%|██▋       | 1583/6015 [11:01<30:42,  2.41it/s]

 26%|██▋       | 1584/6015 [11:02<30:41,  2.41it/s]

 26%|██▋       | 1585/6015 [11:02<30:39,  2.41it/s]

 26%|██▋       | 1586/6015 [11:02<30:39,  2.41it/s]

 26%|██▋       | 1587/6015 [11:03<30:38,  2.41it/s]

 26%|██▋       | 1588/6015 [11:03<30:39,  2.41it/s]

 26%|██▋       | 1589/6015 [11:04<30:38,  2.41it/s]

 26%|██▋       | 1590/6015 [11:04<30:39,  2.41it/s]

 26%|██▋       | 1591/6015 [11:05<30:39,  2.40it/s]

 26%|██▋       | 1592/6015 [11:05<30:37,  2.41it/s]

 26%|██▋       | 1593/6015 [11:05<30:37,  2.41it/s]

 27%|██▋       | 1594/6015 [11:06<30:38,  2.40it/s]

 27%|██▋       | 1595/6015 [11:06<30:37,  2.41it/s]

 27%|██▋       | 1596/6015 [11:07<30:38,  2.40it/s]

 27%|██▋       | 1597/6015 [11:07<30:36,  2.41it/s]

 27%|██▋       | 1598/6015 [11:07<30:35,  2.41it/s]

 27%|██▋       | 1599/6015 [11:08<30:35,  2.41it/s]

 27%|██▋       | 1600/6015 [11:08<30:34,  2.41it/s]

 27%|██▋       | 1601/6015 [11:09<30:39,  2.40it/s]

 27%|██▋       | 1602/6015 [11:09<30:37,  2.40it/s]

 27%|██▋       | 1603/6015 [11:10<30:38,  2.40it/s]

 27%|██▋       | 1604/6015 [11:10<30:36,  2.40it/s]

 27%|██▋       | 1605/6015 [11:10<30:38,  2.40it/s]

 27%|██▋       | 1606/6015 [11:11<30:34,  2.40it/s]

 27%|██▋       | 1607/6015 [11:11<30:33,  2.40it/s]

 27%|██▋       | 1608/6015 [11:12<30:33,  2.40it/s]

 27%|██▋       | 1609/6015 [11:12<30:35,  2.40it/s]

 27%|██▋       | 1610/6015 [11:12<30:31,  2.40it/s]

 27%|██▋       | 1611/6015 [11:13<30:31,  2.40it/s]

 27%|██▋       | 1612/6015 [11:13<30:30,  2.41it/s]

 27%|██▋       | 1613/6015 [11:14<30:29,  2.41it/s]

 27%|██▋       | 1614/6015 [11:14<30:31,  2.40it/s]

 27%|██▋       | 1615/6015 [11:15<30:33,  2.40it/s]

 27%|██▋       | 1616/6015 [11:15<30:29,  2.40it/s]

 27%|██▋       | 1617/6015 [11:15<30:28,  2.40it/s]

 27%|██▋       | 1618/6015 [11:16<30:27,  2.41it/s]

 27%|██▋       | 1619/6015 [11:16<30:26,  2.41it/s]

 27%|██▋       | 1620/6015 [11:17<30:28,  2.40it/s]

 27%|██▋       | 1621/6015 [11:17<30:27,  2.40it/s]

 27%|██▋       | 1622/6015 [11:17<30:34,  2.40it/s]

 27%|██▋       | 1623/6015 [11:18<30:32,  2.40it/s]

 27%|██▋       | 1624/6015 [11:18<30:34,  2.39it/s]

 27%|██▋       | 1625/6015 [11:19<30:31,  2.40it/s]

 27%|██▋       | 1626/6015 [11:19<30:29,  2.40it/s]

 27%|██▋       | 1627/6015 [11:20<30:25,  2.40it/s]

 27%|██▋       | 1628/6015 [11:20<30:28,  2.40it/s]

 27%|██▋       | 1629/6015 [11:20<30:34,  2.39it/s]

 27%|██▋       | 1630/6015 [11:21<30:29,  2.40it/s]

 27%|██▋       | 1631/6015 [11:21<30:26,  2.40it/s]

 27%|██▋       | 1632/6015 [11:22<30:26,  2.40it/s]

 27%|██▋       | 1633/6015 [11:22<30:26,  2.40it/s]

 27%|██▋       | 1634/6015 [11:22<30:26,  2.40it/s]

 27%|██▋       | 1635/6015 [11:23<30:23,  2.40it/s]

 27%|██▋       | 1636/6015 [11:23<30:23,  2.40it/s]

 27%|██▋       | 1637/6015 [11:24<30:24,  2.40it/s]

 27%|██▋       | 1638/6015 [11:24<30:25,  2.40it/s]

 27%|██▋       | 1639/6015 [11:25<30:22,  2.40it/s]

 27%|██▋       | 1640/6015 [11:25<30:21,  2.40it/s]

 27%|██▋       | 1641/6015 [11:25<30:19,  2.40it/s]

 27%|██▋       | 1642/6015 [11:26<30:19,  2.40it/s]

 27%|██▋       | 1643/6015 [11:26<30:17,  2.40it/s]

 27%|██▋       | 1644/6015 [11:27<30:19,  2.40it/s]

 27%|██▋       | 1645/6015 [11:27<30:17,  2.40it/s]

 27%|██▋       | 1646/6015 [11:27<30:17,  2.40it/s]

 27%|██▋       | 1647/6015 [11:28<30:19,  2.40it/s]

 27%|██▋       | 1648/6015 [11:28<30:21,  2.40it/s]

 27%|██▋       | 1649/6015 [11:29<30:17,  2.40it/s]

 27%|██▋       | 1650/6015 [11:29<30:17,  2.40it/s]

 27%|██▋       | 1651/6015 [11:30<30:16,  2.40it/s]

 27%|██▋       | 1652/6015 [11:30<30:15,  2.40it/s]

 27%|██▋       | 1653/6015 [11:30<30:13,  2.41it/s]

 27%|██▋       | 1654/6015 [11:31<30:11,  2.41it/s]

 28%|██▊       | 1655/6015 [11:31<30:12,  2.41it/s]

 28%|██▊       | 1656/6015 [11:32<30:11,  2.41it/s]

 28%|██▊       | 1657/6015 [11:32<30:13,  2.40it/s]

 28%|██▊       | 1658/6015 [11:32<30:13,  2.40it/s]

 28%|██▊       | 1659/6015 [11:33<30:14,  2.40it/s]

 28%|██▊       | 1660/6015 [11:33<30:13,  2.40it/s]

 28%|██▊       | 1661/6015 [11:34<30:12,  2.40it/s]

 28%|██▊       | 1662/6015 [11:34<30:11,  2.40it/s]

 28%|██▊       | 1663/6015 [11:35<30:11,  2.40it/s]

 28%|██▊       | 1664/6015 [11:35<30:10,  2.40it/s]

 28%|██▊       | 1665/6015 [11:35<30:12,  2.40it/s]

 28%|██▊       | 1666/6015 [11:36<30:11,  2.40it/s]

 28%|██▊       | 1667/6015 [11:36<30:10,  2.40it/s]

 28%|██▊       | 1668/6015 [11:37<30:09,  2.40it/s]

 28%|██▊       | 1669/6015 [11:37<30:09,  2.40it/s]

 28%|██▊       | 1670/6015 [11:37<30:09,  2.40it/s]

 28%|██▊       | 1671/6015 [11:38<30:15,  2.39it/s]

 28%|██▊       | 1672/6015 [11:38<30:08,  2.40it/s]

 28%|██▊       | 1673/6015 [11:39<30:07,  2.40it/s]

 28%|██▊       | 1674/6015 [11:39<30:06,  2.40it/s]

 28%|██▊       | 1675/6015 [11:40<30:09,  2.40it/s]

 28%|██▊       | 1676/6015 [11:40<30:07,  2.40it/s]

 28%|██▊       | 1677/6015 [11:40<30:06,  2.40it/s]

 28%|██▊       | 1678/6015 [11:41<30:06,  2.40it/s]

 28%|██▊       | 1679/6015 [11:41<30:09,  2.40it/s]

 28%|██▊       | 1680/6015 [11:42<30:07,  2.40it/s]

 28%|██▊       | 1681/6015 [11:42<30:06,  2.40it/s]

 28%|██▊       | 1682/6015 [11:42<30:05,  2.40it/s]

 28%|██▊       | 1683/6015 [11:43<30:04,  2.40it/s]

 28%|██▊       | 1684/6015 [11:43<30:07,  2.40it/s]

 28%|██▊       | 1685/6015 [11:44<30:05,  2.40it/s]

 28%|██▊       | 1686/6015 [11:44<30:03,  2.40it/s]

 28%|██▊       | 1687/6015 [11:45<30:01,  2.40it/s]

 28%|██▊       | 1688/6015 [11:45<30:01,  2.40it/s]

 28%|██▊       | 1689/6015 [11:45<30:01,  2.40it/s]

 28%|██▊       | 1690/6015 [11:46<30:01,  2.40it/s]

 28%|██▊       | 1691/6015 [11:46<30:02,  2.40it/s]

 28%|██▊       | 1692/6015 [11:47<30:03,  2.40it/s]

 28%|██▊       | 1693/6015 [11:47<30:01,  2.40it/s]

 28%|██▊       | 1694/6015 [11:47<30:00,  2.40it/s]

 28%|██▊       | 1695/6015 [11:48<30:00,  2.40it/s]

 28%|██▊       | 1696/6015 [11:48<30:02,  2.40it/s]

 28%|██▊       | 1697/6015 [11:49<30:00,  2.40it/s]

 28%|██▊       | 1698/6015 [11:49<29:59,  2.40it/s]

 28%|██▊       | 1699/6015 [11:50<29:58,  2.40it/s]

 28%|██▊       | 1700/6015 [11:50<29:58,  2.40it/s]

 28%|██▊       | 1701/6015 [11:50<29:58,  2.40it/s]

 28%|██▊       | 1702/6015 [11:51<29:59,  2.40it/s]

 28%|██▊       | 1703/6015 [11:51<29:57,  2.40it/s]

 28%|██▊       | 1704/6015 [11:52<29:56,  2.40it/s]

 28%|██▊       | 1705/6015 [11:52<29:54,  2.40it/s]

 28%|██▊       | 1706/6015 [11:52<29:56,  2.40it/s]

 28%|██▊       | 1707/6015 [11:53<29:58,  2.40it/s]

 28%|██▊       | 1708/6015 [11:53<29:58,  2.40it/s]

 28%|██▊       | 1709/6015 [11:54<29:55,  2.40it/s]

 28%|██▊       | 1710/6015 [11:54<29:57,  2.40it/s]

 28%|██▊       | 1711/6015 [11:55<29:53,  2.40it/s]

 28%|██▊       | 1712/6015 [11:55<29:55,  2.40it/s]

 28%|██▊       | 1713/6015 [11:55<29:54,  2.40it/s]

 28%|██▊       | 1714/6015 [11:56<29:55,  2.40it/s]

 29%|██▊       | 1715/6015 [11:56<29:54,  2.40it/s]

 29%|██▊       | 1716/6015 [11:57<29:53,  2.40it/s]

 29%|██▊       | 1717/6015 [11:57<29:52,  2.40it/s]

 29%|██▊       | 1718/6015 [11:57<29:52,  2.40it/s]

 29%|██▊       | 1719/6015 [11:58<29:53,  2.39it/s]

 29%|██▊       | 1720/6015 [11:58<29:55,  2.39it/s]

 29%|██▊       | 1721/6015 [11:59<30:04,  2.38it/s]

 29%|██▊       | 1722/6015 [11:59<30:00,  2.38it/s]

 29%|██▊       | 1723/6015 [12:00<29:56,  2.39it/s]

 29%|██▊       | 1724/6015 [12:00<29:54,  2.39it/s]

 29%|██▊       | 1725/6015 [12:00<29:54,  2.39it/s]

 29%|██▊       | 1726/6015 [12:01<29:52,  2.39it/s]

 29%|██▊       | 1727/6015 [12:01<29:50,  2.39it/s]

 29%|██▊       | 1728/6015 [12:02<29:50,  2.39it/s]

 29%|██▊       | 1729/6015 [12:02<29:52,  2.39it/s]

 29%|██▉       | 1730/6015 [12:02<29:51,  2.39it/s]

 29%|██▉       | 1731/6015 [12:03<29:53,  2.39it/s]

 29%|██▉       | 1732/6015 [12:03<29:51,  2.39it/s]

 29%|██▉       | 1733/6015 [12:04<29:49,  2.39it/s]

 29%|██▉       | 1734/6015 [12:04<29:48,  2.39it/s]

 29%|██▉       | 1735/6015 [12:05<29:51,  2.39it/s]

 29%|██▉       | 1736/6015 [12:05<29:50,  2.39it/s]

 29%|██▉       | 1737/6015 [12:05<29:48,  2.39it/s]

 29%|██▉       | 1738/6015 [12:06<29:46,  2.39it/s]

 29%|██▉       | 1739/6015 [12:06<29:46,  2.39it/s]

 29%|██▉       | 1740/6015 [12:07<29:47,  2.39it/s]

 29%|██▉       | 1741/6015 [12:07<29:46,  2.39it/s]

 29%|██▉       | 1742/6015 [12:08<29:47,  2.39it/s]

 29%|██▉       | 1743/6015 [12:08<29:45,  2.39it/s]

 29%|██▉       | 1744/6015 [12:08<29:44,  2.39it/s]

 29%|██▉       | 1745/6015 [12:09<29:42,  2.40it/s]

 29%|██▉       | 1746/6015 [12:09<29:41,  2.40it/s]

 29%|██▉       | 1747/6015 [12:10<29:40,  2.40it/s]

 29%|██▉       | 1748/6015 [12:10<29:40,  2.40it/s]

 29%|██▉       | 1749/6015 [12:10<29:39,  2.40it/s]

 29%|██▉       | 1750/6015 [12:11<29:39,  2.40it/s]

 29%|██▉       | 1751/6015 [12:11<29:39,  2.40it/s]

 29%|██▉       | 1752/6015 [12:12<29:42,  2.39it/s]

 29%|██▉       | 1753/6015 [12:12<29:38,  2.40it/s]

 29%|██▉       | 1754/6015 [12:13<29:38,  2.40it/s]

 29%|██▉       | 1755/6015 [12:13<29:38,  2.40it/s]

 29%|██▉       | 1756/6015 [12:13<29:40,  2.39it/s]

 29%|██▉       | 1757/6015 [12:14<29:36,  2.40it/s]

 29%|██▉       | 1758/6015 [12:14<29:40,  2.39it/s]

 29%|██▉       | 1759/6015 [12:15<29:39,  2.39it/s]

 29%|██▉       | 1760/6015 [12:15<29:40,  2.39it/s]

 29%|██▉       | 1761/6015 [12:15<29:41,  2.39it/s]

 29%|██▉       | 1762/6015 [12:16<29:41,  2.39it/s]

 29%|██▉       | 1763/6015 [12:16<29:38,  2.39it/s]

 29%|██▉       | 1764/6015 [12:17<29:37,  2.39it/s]

 29%|██▉       | 1765/6015 [12:17<29:36,  2.39it/s]

 29%|██▉       | 1766/6015 [12:18<29:36,  2.39it/s]

 29%|██▉       | 1767/6015 [12:18<29:35,  2.39it/s]

 29%|██▉       | 1768/6015 [12:18<29:34,  2.39it/s]

 29%|██▉       | 1769/6015 [12:19<29:34,  2.39it/s]

 29%|██▉       | 1770/6015 [12:19<29:33,  2.39it/s]

 29%|██▉       | 1771/6015 [12:20<29:40,  2.38it/s]

 29%|██▉       | 1772/6015 [12:20<29:39,  2.38it/s]

 29%|██▉       | 1773/6015 [12:20<29:38,  2.38it/s]

 29%|██▉       | 1774/6015 [12:21<29:35,  2.39it/s]

 30%|██▉       | 1775/6015 [12:21<29:33,  2.39it/s]

 30%|██▉       | 1776/6015 [12:22<29:31,  2.39it/s]

 30%|██▉       | 1777/6015 [12:22<29:32,  2.39it/s]

 30%|██▉       | 1778/6015 [12:23<29:31,  2.39it/s]

 30%|██▉       | 1779/6015 [12:23<29:31,  2.39it/s]

 30%|██▉       | 1780/6015 [12:23<29:28,  2.39it/s]

 30%|██▉       | 1781/6015 [12:24<29:28,  2.39it/s]

 30%|██▉       | 1782/6015 [12:24<29:26,  2.40it/s]

 30%|██▉       | 1783/6015 [12:25<29:29,  2.39it/s]

 30%|██▉       | 1784/6015 [12:25<29:30,  2.39it/s]

 30%|██▉       | 1785/6015 [12:25<29:34,  2.38it/s]

 30%|██▉       | 1786/6015 [12:26<29:33,  2.38it/s]

 30%|██▉       | 1787/6015 [12:26<29:34,  2.38it/s]

 30%|██▉       | 1788/6015 [12:27<29:30,  2.39it/s]

 30%|██▉       | 1789/6015 [12:27<29:30,  2.39it/s]

 30%|██▉       | 1790/6015 [12:28<29:28,  2.39it/s]

 30%|██▉       | 1791/6015 [12:28<29:28,  2.39it/s]

 30%|██▉       | 1792/6015 [12:28<29:26,  2.39it/s]

 30%|██▉       | 1793/6015 [12:29<29:26,  2.39it/s]

 30%|██▉       | 1794/6015 [12:29<29:23,  2.39it/s]

 30%|██▉       | 1795/6015 [12:30<29:23,  2.39it/s]

 30%|██▉       | 1796/6015 [12:30<29:23,  2.39it/s]

 30%|██▉       | 1797/6015 [12:31<29:28,  2.39it/s]

 30%|██▉       | 1798/6015 [12:31<29:27,  2.39it/s]

 30%|██▉       | 1799/6015 [12:31<29:25,  2.39it/s]

 30%|██▉       | 1800/6015 [12:32<29:23,  2.39it/s]

 30%|██▉       | 1801/6015 [12:32<29:24,  2.39it/s]

 30%|██▉       | 1802/6015 [12:33<29:24,  2.39it/s]

 30%|██▉       | 1803/6015 [12:33<29:23,  2.39it/s]

 30%|██▉       | 1804/6015 [12:33<29:20,  2.39it/s]

 30%|███       | 1805/6015 [12:34<29:19,  2.39it/s]

 30%|███       | 1806/6015 [12:34<29:19,  2.39it/s]

 30%|███       | 1807/6015 [12:35<29:18,  2.39it/s]

 30%|███       | 1808/6015 [12:35<29:18,  2.39it/s]

 30%|███       | 1809/6015 [12:36<29:18,  2.39it/s]

 30%|███       | 1810/6015 [12:36<29:17,  2.39it/s]

 30%|███       | 1811/6015 [12:36<29:18,  2.39it/s]

 30%|███       | 1812/6015 [12:37<29:17,  2.39it/s]

 30%|███       | 1813/6015 [12:37<29:18,  2.39it/s]

 30%|███       | 1814/6015 [12:38<29:16,  2.39it/s]

 30%|███       | 1815/6015 [12:38<29:17,  2.39it/s]

 30%|███       | 1816/6015 [12:38<29:17,  2.39it/s]

 30%|███       | 1817/6015 [12:39<29:17,  2.39it/s]

 30%|███       | 1818/6015 [12:39<29:15,  2.39it/s]

 30%|███       | 1819/6015 [12:40<29:15,  2.39it/s]

 30%|███       | 1820/6015 [12:40<29:16,  2.39it/s]

 30%|███       | 1821/6015 [12:41<29:20,  2.38it/s]

 30%|███       | 1822/6015 [12:41<29:17,  2.39it/s]

 30%|███       | 1823/6015 [12:41<29:17,  2.39it/s]

 30%|███       | 1824/6015 [12:42<29:15,  2.39it/s]

 30%|███       | 1825/6015 [12:42<29:14,  2.39it/s]

 30%|███       | 1826/6015 [12:43<29:11,  2.39it/s]

 30%|███       | 1827/6015 [12:43<29:11,  2.39it/s]

 30%|███       | 1828/6015 [12:43<29:10,  2.39it/s]

 30%|███       | 1829/6015 [12:44<29:13,  2.39it/s]

 30%|███       | 1830/6015 [12:44<29:11,  2.39it/s]

 30%|███       | 1831/6015 [12:45<29:09,  2.39it/s]

 30%|███       | 1832/6015 [12:45<29:06,  2.39it/s]

 30%|███       | 1833/6015 [12:46<29:07,  2.39it/s]

 30%|███       | 1834/6015 [12:46<29:07,  2.39it/s]

 31%|███       | 1835/6015 [12:46<29:09,  2.39it/s]

 31%|███       | 1836/6015 [12:47<29:06,  2.39it/s]

 31%|███       | 1837/6015 [12:47<29:10,  2.39it/s]

 31%|███       | 1838/6015 [12:48<29:09,  2.39it/s]

 31%|███       | 1839/6015 [12:48<29:07,  2.39it/s]

 31%|███       | 1840/6015 [12:48<29:07,  2.39it/s]

 31%|███       | 1841/6015 [12:49<29:11,  2.38it/s]

 31%|███       | 1842/6015 [12:49<29:10,  2.38it/s]

 31%|███       | 1843/6015 [12:50<29:09,  2.39it/s]

 31%|███       | 1844/6015 [12:50<29:09,  2.38it/s]

 31%|███       | 1845/6015 [12:51<29:09,  2.38it/s]

 31%|███       | 1846/6015 [12:51<29:07,  2.39it/s]

 31%|███       | 1847/6015 [12:51<29:05,  2.39it/s]

 31%|███       | 1848/6015 [12:52<29:05,  2.39it/s]

 31%|███       | 1849/6015 [12:52<29:03,  2.39it/s]

 31%|███       | 1850/6015 [12:53<29:02,  2.39it/s]

 31%|███       | 1851/6015 [12:53<29:02,  2.39it/s]

 31%|███       | 1852/6015 [12:54<29:03,  2.39it/s]

 31%|███       | 1853/6015 [12:54<29:04,  2.39it/s]

 31%|███       | 1854/6015 [12:54<29:03,  2.39it/s]

 31%|███       | 1855/6015 [12:55<29:04,  2.38it/s]

 31%|███       | 1856/6015 [12:55<29:02,  2.39it/s]

 31%|███       | 1857/6015 [12:56<29:01,  2.39it/s]

 31%|███       | 1858/6015 [12:56<29:02,  2.39it/s]

 31%|███       | 1859/6015 [12:56<29:03,  2.38it/s]

 31%|███       | 1860/6015 [12:57<28:59,  2.39it/s]

 31%|███       | 1861/6015 [12:57<29:01,  2.38it/s]

 31%|███       | 1862/6015 [12:58<29:00,  2.39it/s]

 31%|███       | 1863/6015 [12:58<29:01,  2.38it/s]

 31%|███       | 1864/6015 [12:59<28:57,  2.39it/s]

 31%|███       | 1865/6015 [12:59<28:58,  2.39it/s]

 31%|███       | 1866/6015 [12:59<28:56,  2.39it/s]

 31%|███       | 1867/6015 [13:00<28:57,  2.39it/s]

 31%|███       | 1868/6015 [13:00<28:56,  2.39it/s]

 31%|███       | 1869/6015 [13:01<28:58,  2.38it/s]

 31%|███       | 1870/6015 [13:01<28:56,  2.39it/s]

 31%|███       | 1871/6015 [13:01<28:56,  2.39it/s]

 31%|███       | 1872/6015 [13:02<28:56,  2.39it/s]

 31%|███       | 1873/6015 [13:02<28:57,  2.38it/s]

 31%|███       | 1874/6015 [13:03<28:54,  2.39it/s]

 31%|███       | 1875/6015 [13:03<28:53,  2.39it/s]

 31%|███       | 1876/6015 [13:04<28:54,  2.39it/s]

 31%|███       | 1877/6015 [13:04<28:57,  2.38it/s]

logging
logging the anndata

 31%|███       | 1878/6015 [13:04<30:06,  2.29it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 31%|███       | 1879/6015 [13:05<29:36,  2.33it/s]

 31%|███▏      | 1880/6015 [13:05<29:12,  2.36it/s]

 31%|███▏      | 1881/6015 [13:06<28:56,  2.38it/s]

 31%|███▏      | 1882/6015 [13:06<28:43,  2.40it/s]

 31%|███▏      | 1883/6015 [13:07<28:34,  2.41it/s]

 31%|███▏      | 1884/6015 [13:07<28:28,  2.42it/s]

 31%|███▏      | 1885/6015 [13:07<28:24,  2.42it/s]

 31%|███▏      | 1886/6015 [13:08<28:23,  2.42it/s]

 31%|███▏      | 1887/6015 [13:08<28:19,  2.43it/s]

 31%|███▏      | 1888/6015 [13:09<28:19,  2.43it/s]

 31%|███▏      | 1889/6015 [13:09<28:18,  2.43it/s]

 31%|███▏      | 1890/6015 [13:09<28:16,  2.43it/s]

 31%|███▏      | 1891/6015 [13:10<28:17,  2.43it/s]

 31%|███▏      | 1892/6015 [13:10<28:16,  2.43it/s]

 31%|███▏      | 1893/6015 [13:11<28:16,  2.43it/s]

 31%|███▏      | 1894/6015 [13:11<28:15,  2.43it/s]

 32%|███▏      | 1895/6015 [13:11<28:14,  2.43it/s]

 32%|███▏      | 1896/6015 [13:12<28:13,  2.43it/s]

 32%|███▏      | 1897/6015 [13:12<28:13,  2.43it/s]

 32%|███▏      | 1898/6015 [13:13<28:11,  2.43it/s]

 32%|███▏      | 1899/6015 [13:13<28:11,  2.43it/s]

 32%|███▏      | 1900/6015 [13:14<28:10,  2.43it/s]

 32%|███▏      | 1901/6015 [13:14<28:11,  2.43it/s]

 32%|███▏      | 1902/6015 [13:14<28:11,  2.43it/s]

 32%|███▏      | 1903/6015 [13:15<28:09,  2.43it/s]

 32%|███▏      | 1904/6015 [13:15<28:09,  2.43it/s]

 32%|███▏      | 1905/6015 [13:16<28:08,  2.43it/s]

 32%|███▏      | 1906/6015 [13:16<28:08,  2.43it/s]

 32%|███▏      | 1907/6015 [13:16<28:10,  2.43it/s]

 32%|███▏      | 1908/6015 [13:17<28:09,  2.43it/s]

 32%|███▏      | 1909/6015 [13:17<28:09,  2.43it/s]

 32%|███▏      | 1910/6015 [13:18<28:08,  2.43it/s]

 32%|███▏      | 1911/6015 [13:18<28:10,  2.43it/s]

 32%|███▏      | 1912/6015 [13:18<28:09,  2.43it/s]

 32%|███▏      | 1913/6015 [13:19<28:08,  2.43it/s]

 32%|███▏      | 1914/6015 [13:19<28:06,  2.43it/s]

 32%|███▏      | 1915/6015 [13:20<28:05,  2.43it/s]

 32%|███▏      | 1916/6015 [13:20<28:04,  2.43it/s]

 32%|███▏      | 1917/6015 [13:21<28:04,  2.43it/s]

 32%|███▏      | 1918/6015 [13:21<28:04,  2.43it/s]

 32%|███▏      | 1919/6015 [13:21<28:04,  2.43it/s]

 32%|███▏      | 1920/6015 [13:22<28:05,  2.43it/s]

 32%|███▏      | 1921/6015 [13:22<28:03,  2.43it/s]

 32%|███▏      | 1922/6015 [13:23<28:04,  2.43it/s]

 32%|███▏      | 1923/6015 [13:23<28:02,  2.43it/s]

 32%|███▏      | 1924/6015 [13:23<28:01,  2.43it/s]

 32%|███▏      | 1925/6015 [13:24<28:01,  2.43it/s]

 32%|███▏      | 1926/6015 [13:24<28:00,  2.43it/s]

 32%|███▏      | 1927/6015 [13:25<28:00,  2.43it/s]

 32%|███▏      | 1928/6015 [13:25<28:00,  2.43it/s]

 32%|███▏      | 1929/6015 [13:25<27:59,  2.43it/s]

 32%|███▏      | 1930/6015 [13:26<27:58,  2.43it/s]

 32%|███▏      | 1931/6015 [13:26<27:59,  2.43it/s]

 32%|███▏      | 1932/6015 [13:27<27:58,  2.43it/s]

 32%|███▏      | 1933/6015 [13:27<27:58,  2.43it/s]

 32%|███▏      | 1934/6015 [13:28<27:58,  2.43it/s]

 32%|███▏      | 1935/6015 [13:28<27:58,  2.43it/s]

 32%|███▏      | 1936/6015 [13:28<27:58,  2.43it/s]

 32%|███▏      | 1937/6015 [13:29<27:57,  2.43it/s]

 32%|███▏      | 1938/6015 [13:29<27:56,  2.43it/s]

 32%|███▏      | 1939/6015 [13:30<27:55,  2.43it/s]

 32%|███▏      | 1940/6015 [13:30<27:56,  2.43it/s]

 32%|███▏      | 1941/6015 [13:30<28:00,  2.42it/s]

 32%|███▏      | 1942/6015 [13:31<27:59,  2.42it/s]

 32%|███▏      | 1943/6015 [13:31<27:57,  2.43it/s]

 32%|███▏      | 1944/6015 [13:32<27:57,  2.43it/s]

 32%|███▏      | 1945/6015 [13:32<27:56,  2.43it/s]

 32%|███▏      | 1946/6015 [13:32<27:55,  2.43it/s]

 32%|███▏      | 1947/6015 [13:33<27:54,  2.43it/s]

 32%|███▏      | 1948/6015 [13:33<27:53,  2.43it/s]

 32%|███▏      | 1949/6015 [13:34<27:54,  2.43it/s]

 32%|███▏      | 1950/6015 [13:34<27:54,  2.43it/s]

 32%|███▏      | 1951/6015 [13:35<27:55,  2.43it/s]

 32%|███▏      | 1952/6015 [13:35<27:53,  2.43it/s]

 32%|███▏      | 1953/6015 [13:35<27:51,  2.43it/s]

 32%|███▏      | 1954/6015 [13:36<27:51,  2.43it/s]

 33%|███▎      | 1955/6015 [13:36<27:52,  2.43it/s]

 33%|███▎      | 1956/6015 [13:37<27:52,  2.43it/s]

 33%|███▎      | 1957/6015 [13:37<27:51,  2.43it/s]

 33%|███▎      | 1958/6015 [13:37<27:50,  2.43it/s]

 33%|███▎      | 1959/6015 [13:38<27:51,  2.43it/s]

 33%|███▎      | 1960/6015 [13:38<27:51,  2.43it/s]

 33%|███▎      | 1961/6015 [13:39<27:51,  2.43it/s]

 33%|███▎      | 1962/6015 [13:39<27:49,  2.43it/s]

 33%|███▎      | 1963/6015 [13:39<27:50,  2.43it/s]

 33%|███▎      | 1964/6015 [13:40<27:50,  2.43it/s]

 33%|███▎      | 1965/6015 [13:40<27:48,  2.43it/s]

 33%|███▎      | 1966/6015 [13:41<27:48,  2.43it/s]

 33%|███▎      | 1967/6015 [13:41<27:47,  2.43it/s]

 33%|███▎      | 1968/6015 [13:42<27:48,  2.43it/s]

 33%|███▎      | 1969/6015 [13:42<27:46,  2.43it/s]

 33%|███▎      | 1970/6015 [13:42<27:46,  2.43it/s]

 33%|███▎      | 1971/6015 [13:43<27:47,  2.42it/s]

 33%|███▎      | 1972/6015 [13:43<27:45,  2.43it/s]

 33%|███▎      | 1973/6015 [13:44<27:45,  2.43it/s]

 33%|███▎      | 1974/6015 [13:44<27:43,  2.43it/s]

 33%|███▎      | 1975/6015 [13:44<27:45,  2.43it/s]

 33%|███▎      | 1976/6015 [13:45<27:43,  2.43it/s]

 33%|███▎      | 1977/6015 [13:45<27:45,  2.42it/s]

 33%|███▎      | 1978/6015 [13:46<27:43,  2.43it/s]

 33%|███▎      | 1979/6015 [13:46<27:44,  2.42it/s]

 33%|███▎      | 1980/6015 [13:46<27:44,  2.42it/s]

 33%|███▎      | 1981/6015 [13:47<27:45,  2.42it/s]

 33%|███▎      | 1982/6015 [13:47<27:44,  2.42it/s]

 33%|███▎      | 1983/6015 [13:48<27:45,  2.42it/s]

 33%|███▎      | 1984/6015 [13:48<27:48,  2.42it/s]

 33%|███▎      | 1985/6015 [13:49<27:46,  2.42it/s]

 33%|███▎      | 1986/6015 [13:49<27:44,  2.42it/s]

 33%|███▎      | 1987/6015 [13:49<27:44,  2.42it/s]

 33%|███▎      | 1988/6015 [13:50<27:48,  2.41it/s]

 33%|███▎      | 1989/6015 [13:50<27:45,  2.42it/s]

 33%|███▎      | 1990/6015 [13:51<27:43,  2.42it/s]

 33%|███▎      | 1991/6015 [13:51<27:43,  2.42it/s]

 33%|███▎      | 1992/6015 [13:51<27:43,  2.42it/s]

 33%|███▎      | 1993/6015 [13:52<27:40,  2.42it/s]

 33%|███▎      | 1994/6015 [13:52<27:40,  2.42it/s]

 33%|███▎      | 1995/6015 [13:53<27:39,  2.42it/s]

 33%|███▎      | 1996/6015 [13:53<27:37,  2.43it/s]

 33%|███▎      | 1997/6015 [13:53<27:36,  2.43it/s]

 33%|███▎      | 1998/6015 [13:54<27:37,  2.42it/s]

 33%|███▎      | 1999/6015 [13:54<27:39,  2.42it/s]

 33%|███▎      | 2000/6015 [13:55<27:38,  2.42it/s]

 33%|███▎      | 2001/6015 [13:55<27:36,  2.42it/s]

 33%|███▎      | 2002/6015 [13:56<27:43,  2.41it/s]

 33%|███▎      | 2003/6015 [13:56<27:42,  2.41it/s]

 33%|███▎      | 2004/6015 [13:56<27:38,  2.42it/s]

 33%|███▎      | 2005/6015 [13:57<27:38,  2.42it/s]

 33%|███▎      | 2006/6015 [13:57<27:35,  2.42it/s]

 33%|███▎      | 2007/6015 [13:58<27:35,  2.42it/s]

 33%|███▎      | 2008/6015 [13:58<27:33,  2.42it/s]

 33%|███▎      | 2009/6015 [13:58<27:33,  2.42it/s]

 33%|███▎      | 2010/6015 [13:59<27:32,  2.42it/s]

 33%|███▎      | 2011/6015 [13:59<27:31,  2.43it/s]

 33%|███▎      | 2012/6015 [14:00<27:30,  2.43it/s]

 33%|███▎      | 2013/6015 [14:00<27:30,  2.42it/s]

 33%|███▎      | 2014/6015 [14:01<27:31,  2.42it/s]

 33%|███▎      | 2015/6015 [14:01<27:30,  2.42it/s]

 34%|███▎      | 2016/6015 [14:01<27:30,  2.42it/s]

 34%|███▎      | 2017/6015 [14:02<27:29,  2.42it/s]

 34%|███▎      | 2018/6015 [14:02<27:30,  2.42it/s]

 34%|███▎      | 2019/6015 [14:03<27:28,  2.42it/s]

 34%|███▎      | 2020/6015 [14:03<27:29,  2.42it/s]

 34%|███▎      | 2021/6015 [14:03<27:27,  2.42it/s]

 34%|███▎      | 2022/6015 [14:04<27:28,  2.42it/s]

 34%|███▎      | 2023/6015 [14:04<27:26,  2.42it/s]

 34%|███▎      | 2024/6015 [14:05<27:28,  2.42it/s]

 34%|███▎      | 2025/6015 [14:05<27:27,  2.42it/s]

 34%|███▎      | 2026/6015 [14:05<27:26,  2.42it/s]

 34%|███▎      | 2027/6015 [14:06<27:25,  2.42it/s]

 34%|███▎      | 2028/6015 [14:06<27:24,  2.42it/s]

 34%|███▎      | 2029/6015 [14:07<27:24,  2.42it/s]

 34%|███▎      | 2030/6015 [14:07<27:26,  2.42it/s]

 34%|███▍      | 2031/6015 [14:08<27:27,  2.42it/s]

 34%|███▍      | 2032/6015 [14:08<27:25,  2.42it/s]

 34%|███▍      | 2033/6015 [14:08<27:27,  2.42it/s]

 34%|███▍      | 2034/6015 [14:09<27:25,  2.42it/s]

 34%|███▍      | 2035/6015 [14:09<27:24,  2.42it/s]

 34%|███▍      | 2036/6015 [14:10<27:22,  2.42it/s]

 34%|███▍      | 2037/6015 [14:10<27:22,  2.42it/s]

 34%|███▍      | 2038/6015 [14:10<27:21,  2.42it/s]

 34%|███▍      | 2039/6015 [14:11<27:20,  2.42it/s]

 34%|███▍      | 2040/6015 [14:11<27:20,  2.42it/s]

 34%|███▍      | 2041/6015 [14:12<27:20,  2.42it/s]

 34%|███▍      | 2042/6015 [14:12<27:19,  2.42it/s]

 34%|███▍      | 2043/6015 [14:12<27:20,  2.42it/s]

 34%|███▍      | 2044/6015 [14:13<27:20,  2.42it/s]

 34%|███▍      | 2045/6015 [14:13<27:20,  2.42it/s]

 34%|███▍      | 2046/6015 [14:14<27:21,  2.42it/s]

 34%|███▍      | 2047/6015 [14:14<27:19,  2.42it/s]

 34%|███▍      | 2048/6015 [14:15<27:19,  2.42it/s]

 34%|███▍      | 2049/6015 [14:15<27:18,  2.42it/s]

 34%|███▍      | 2050/6015 [14:15<27:19,  2.42it/s]

 34%|███▍      | 2051/6015 [14:16<27:18,  2.42it/s]

 34%|███▍      | 2052/6015 [14:16<27:17,  2.42it/s]

 34%|███▍      | 2053/6015 [14:17<27:16,  2.42it/s]

 34%|███▍      | 2054/6015 [14:17<27:17,  2.42it/s]

 34%|███▍      | 2055/6015 [14:17<27:17,  2.42it/s]

 34%|███▍      | 2056/6015 [14:18<27:16,  2.42it/s]

 34%|███▍      | 2057/6015 [14:18<27:14,  2.42it/s]

 34%|███▍      | 2058/6015 [14:19<27:14,  2.42it/s]

 34%|███▍      | 2059/6015 [14:19<27:13,  2.42it/s]

 34%|███▍      | 2060/6015 [14:19<27:13,  2.42it/s]

 34%|███▍      | 2061/6015 [14:20<27:13,  2.42it/s]

 34%|███▍      | 2062/6015 [14:20<27:13,  2.42it/s]

 34%|███▍      | 2063/6015 [14:21<27:14,  2.42it/s]

 34%|███▍      | 2064/6015 [14:21<27:14,  2.42it/s]

 34%|███▍      | 2065/6015 [14:22<27:13,  2.42it/s]

 34%|███▍      | 2066/6015 [14:22<27:11,  2.42it/s]

 34%|███▍      | 2067/6015 [14:22<27:11,  2.42it/s]

 34%|███▍      | 2068/6015 [14:23<27:10,  2.42it/s]

 34%|███▍      | 2069/6015 [14:23<27:11,  2.42it/s]

 34%|███▍      | 2070/6015 [14:24<27:09,  2.42it/s]

 34%|███▍      | 2071/6015 [14:24<27:09,  2.42it/s]

 34%|███▍      | 2072/6015 [14:24<27:09,  2.42it/s]

 34%|███▍      | 2073/6015 [14:25<27:09,  2.42it/s]

 34%|███▍      | 2074/6015 [14:25<27:08,  2.42it/s]

 34%|███▍      | 2075/6015 [14:26<27:09,  2.42it/s]

 35%|███▍      | 2076/6015 [14:26<27:11,  2.41it/s]

 35%|███▍      | 2077/6015 [14:27<27:11,  2.41it/s]

 35%|███▍      | 2078/6015 [14:27<27:11,  2.41it/s]

 35%|███▍      | 2079/6015 [14:27<27:08,  2.42it/s]

 35%|███▍      | 2080/6015 [14:28<27:07,  2.42it/s]

 35%|███▍      | 2081/6015 [14:28<27:05,  2.42it/s]

 35%|███▍      | 2082/6015 [14:29<27:05,  2.42it/s]

 35%|███▍      | 2083/6015 [14:29<27:05,  2.42it/s]

 35%|███▍      | 2084/6015 [14:29<27:06,  2.42it/s]

 35%|███▍      | 2085/6015 [14:30<27:05,  2.42it/s]

 35%|███▍      | 2086/6015 [14:30<27:04,  2.42it/s]

 35%|███▍      | 2087/6015 [14:31<27:03,  2.42it/s]

 35%|███▍      | 2088/6015 [14:31<27:07,  2.41it/s]

 35%|███▍      | 2089/6015 [14:31<27:04,  2.42it/s]

 35%|███▍      | 2090/6015 [14:32<27:03,  2.42it/s]

 35%|███▍      | 2091/6015 [14:32<27:02,  2.42it/s]

 35%|███▍      | 2092/6015 [14:33<27:03,  2.42it/s]

 35%|███▍      | 2093/6015 [14:33<27:03,  2.42it/s]

 35%|███▍      | 2094/6015 [14:34<27:03,  2.42it/s]

 35%|███▍      | 2095/6015 [14:34<27:02,  2.42it/s]

 35%|███▍      | 2096/6015 [14:34<27:00,  2.42it/s]

 35%|███▍      | 2097/6015 [14:35<27:01,  2.42it/s]

 35%|███▍      | 2098/6015 [14:35<27:02,  2.41it/s]

 35%|███▍      | 2099/6015 [14:36<27:03,  2.41it/s]

 35%|███▍      | 2100/6015 [14:36<27:01,  2.41it/s]

 35%|███▍      | 2101/6015 [14:36<27:01,  2.41it/s]

 35%|███▍      | 2102/6015 [14:37<27:00,  2.41it/s]

 35%|███▍      | 2103/6015 [14:37<27:00,  2.41it/s]

 35%|███▍      | 2104/6015 [14:38<26:58,  2.42it/s]

 35%|███▍      | 2105/6015 [14:38<26:58,  2.42it/s]

 35%|███▌      | 2106/6015 [14:39<26:58,  2.42it/s]

 35%|███▌      | 2107/6015 [14:39<26:58,  2.42it/s]

 35%|███▌      | 2108/6015 [14:39<27:02,  2.41it/s]

 35%|███▌      | 2109/6015 [14:40<27:00,  2.41it/s]

 35%|███▌      | 2110/6015 [14:40<26:59,  2.41it/s]

 35%|███▌      | 2111/6015 [14:41<26:57,  2.41it/s]

 35%|███▌      | 2112/6015 [14:41<26:55,  2.42it/s]

 35%|███▌      | 2113/6015 [14:41<26:53,  2.42it/s]

 35%|███▌      | 2114/6015 [14:42<26:56,  2.41it/s]

 35%|███▌      | 2115/6015 [14:42<26:54,  2.42it/s]

 35%|███▌      | 2116/6015 [14:43<26:55,  2.41it/s]

 35%|███▌      | 2117/6015 [14:43<26:53,  2.42it/s]

 35%|███▌      | 2118/6015 [14:44<26:55,  2.41it/s]

 35%|███▌      | 2119/6015 [14:44<26:53,  2.41it/s]

 35%|███▌      | 2120/6015 [14:44<26:52,  2.42it/s]

 35%|███▌      | 2121/6015 [14:45<26:51,  2.42it/s]

 35%|███▌      | 2122/6015 [14:45<26:52,  2.41it/s]

 35%|███▌      | 2123/6015 [14:46<26:52,  2.41it/s]

 35%|███▌      | 2124/6015 [14:46<26:52,  2.41it/s]

 35%|███▌      | 2125/6015 [14:46<26:50,  2.42it/s]

 35%|███▌      | 2126/6015 [14:47<26:51,  2.41it/s]

 35%|███▌      | 2127/6015 [14:47<26:51,  2.41it/s]

 35%|███▌      | 2128/6015 [14:48<26:49,  2.42it/s]

 35%|███▌      | 2129/6015 [14:48<26:47,  2.42it/s]

 35%|███▌      | 2130/6015 [14:48<26:46,  2.42it/s]

 35%|███▌      | 2131/6015 [14:49<26:47,  2.42it/s]

 35%|███▌      | 2132/6015 [14:49<26:48,  2.41it/s]

 35%|███▌      | 2133/6015 [14:50<26:47,  2.41it/s]

 35%|███▌      | 2134/6015 [14:50<26:47,  2.42it/s]

 35%|███▌      | 2135/6015 [14:51<26:45,  2.42it/s]

 36%|███▌      | 2136/6015 [14:51<26:45,  2.42it/s]

 36%|███▌      | 2137/6015 [14:51<26:46,  2.41it/s]

 36%|███▌      | 2138/6015 [14:52<26:45,  2.41it/s]

 36%|███▌      | 2139/6015 [14:52<26:44,  2.42it/s]

 36%|███▌      | 2140/6015 [14:53<26:47,  2.41it/s]

 36%|███▌      | 2141/6015 [14:53<26:47,  2.41it/s]

 36%|███▌      | 2142/6015 [14:53<26:47,  2.41it/s]

 36%|███▌      | 2143/6015 [14:54<26:45,  2.41it/s]

 36%|███▌      | 2144/6015 [14:54<26:45,  2.41it/s]

 36%|███▌      | 2145/6015 [14:55<26:46,  2.41it/s]

 36%|███▌      | 2146/6015 [14:55<26:46,  2.41it/s]

 36%|███▌      | 2147/6015 [14:56<26:43,  2.41it/s]

 36%|███▌      | 2148/6015 [14:56<26:44,  2.41it/s]

 36%|███▌      | 2149/6015 [14:56<26:43,  2.41it/s]

 36%|███▌      | 2150/6015 [14:57<26:43,  2.41it/s]

 36%|███▌      | 2151/6015 [14:57<26:41,  2.41it/s]

 36%|███▌      | 2152/6015 [14:58<26:41,  2.41it/s]

 36%|███▌      | 2153/6015 [14:58<26:40,  2.41it/s]

 36%|███▌      | 2154/6015 [14:58<26:40,  2.41it/s]

 36%|███▌      | 2155/6015 [14:59<26:40,  2.41it/s]

 36%|███▌      | 2156/6015 [14:59<26:41,  2.41it/s]

 36%|███▌      | 2157/6015 [15:00<26:39,  2.41it/s]

 36%|███▌      | 2158/6015 [15:00<26:41,  2.41it/s]

 36%|███▌      | 2159/6015 [15:00<26:44,  2.40it/s]

 36%|███▌      | 2160/6015 [15:01<26:41,  2.41it/s]

 36%|███▌      | 2161/6015 [15:01<26:42,  2.41it/s]

 36%|███▌      | 2162/6015 [15:02<26:40,  2.41it/s]

 36%|███▌      | 2163/6015 [15:02<26:39,  2.41it/s]

 36%|███▌      | 2164/6015 [15:03<26:39,  2.41it/s]

 36%|███▌      | 2165/6015 [15:03<26:39,  2.41it/s]

 36%|███▌      | 2166/6015 [15:03<26:39,  2.41it/s]

 36%|███▌      | 2167/6015 [15:04<26:38,  2.41it/s]

 36%|███▌      | 2168/6015 [15:04<26:39,  2.41it/s]

 36%|███▌      | 2169/6015 [15:05<26:39,  2.40it/s]

 36%|███▌      | 2170/6015 [15:05<26:36,  2.41it/s]

 36%|███▌      | 2171/6015 [15:05<26:36,  2.41it/s]

 36%|███▌      | 2172/6015 [15:06<26:34,  2.41it/s]

 36%|███▌      | 2173/6015 [15:06<26:34,  2.41it/s]

 36%|███▌      | 2174/6015 [15:07<26:33,  2.41it/s]

 36%|███▌      | 2175/6015 [15:07<26:34,  2.41it/s]

 36%|███▌      | 2176/6015 [15:08<26:34,  2.41it/s]

 36%|███▌      | 2177/6015 [15:08<26:33,  2.41it/s]

 36%|███▌      | 2178/6015 [15:08<26:32,  2.41it/s]

 36%|███▌      | 2179/6015 [15:09<26:32,  2.41it/s]

 36%|███▌      | 2180/6015 [15:09<26:33,  2.41it/s]

 36%|███▋      | 2181/6015 [15:10<26:31,  2.41it/s]

 36%|███▋      | 2182/6015 [15:10<26:32,  2.41it/s]

 36%|███▋      | 2183/6015 [15:10<26:30,  2.41it/s]

 36%|███▋      | 2184/6015 [15:11<26:29,  2.41it/s]

 36%|███▋      | 2185/6015 [15:11<26:28,  2.41it/s]

 36%|███▋      | 2186/6015 [15:12<26:27,  2.41it/s]

 36%|███▋      | 2187/6015 [15:12<26:26,  2.41it/s]

 36%|███▋      | 2188/6015 [15:13<26:28,  2.41it/s]

 36%|███▋      | 2189/6015 [15:13<26:30,  2.41it/s]

 36%|███▋      | 2190/6015 [15:13<26:31,  2.40it/s]

 36%|███▋      | 2191/6015 [15:14<26:29,  2.41it/s]

 36%|███▋      | 2192/6015 [15:14<26:30,  2.40it/s]

 36%|███▋      | 2193/6015 [15:15<26:31,  2.40it/s]

 36%|███▋      | 2194/6015 [15:15<26:30,  2.40it/s]

 36%|███▋      | 2195/6015 [15:15<26:27,  2.41it/s]

 37%|███▋      | 2196/6015 [15:16<26:26,  2.41it/s]

 37%|███▋      | 2197/6015 [15:16<26:25,  2.41it/s]

 37%|███▋      | 2198/6015 [15:17<26:25,  2.41it/s]

 37%|███▋      | 2199/6015 [15:17<26:24,  2.41it/s]

 37%|███▋      | 2200/6015 [15:18<26:24,  2.41it/s]

 37%|███▋      | 2201/6015 [15:18<26:24,  2.41it/s]

 37%|███▋      | 2202/6015 [15:18<26:24,  2.41it/s]

 37%|███▋      | 2203/6015 [15:19<26:25,  2.40it/s]

 37%|███▋      | 2204/6015 [15:19<26:24,  2.41it/s]

 37%|███▋      | 2205/6015 [15:20<26:27,  2.40it/s]

 37%|███▋      | 2206/6015 [15:20<26:27,  2.40it/s]

 37%|███▋      | 2207/6015 [15:20<26:24,  2.40it/s]

 37%|███▋      | 2208/6015 [15:21<26:24,  2.40it/s]

 37%|███▋      | 2209/6015 [15:21<26:24,  2.40it/s]

 37%|███▋      | 2210/6015 [15:22<26:24,  2.40it/s]

 37%|███▋      | 2211/6015 [15:22<26:22,  2.40it/s]

 37%|███▋      | 2212/6015 [15:23<26:20,  2.41it/s]

 37%|███▋      | 2213/6015 [15:23<26:19,  2.41it/s]

 37%|███▋      | 2214/6015 [15:23<26:16,  2.41it/s]

 37%|███▋      | 2215/6015 [15:24<26:17,  2.41it/s]

 37%|███▋      | 2216/6015 [15:24<26:19,  2.40it/s]

 37%|███▋      | 2217/6015 [15:25<26:19,  2.40it/s]

 37%|███▋      | 2218/6015 [15:25<26:19,  2.40it/s]

 37%|███▋      | 2219/6015 [15:25<26:21,  2.40it/s]

 37%|███▋      | 2220/6015 [15:26<26:20,  2.40it/s]

 37%|███▋      | 2221/6015 [15:26<26:19,  2.40it/s]

 37%|███▋      | 2222/6015 [15:27<26:20,  2.40it/s]

 37%|███▋      | 2223/6015 [15:27<26:18,  2.40it/s]

 37%|███▋      | 2224/6015 [15:28<26:16,  2.40it/s]

 37%|███▋      | 2225/6015 [15:28<26:15,  2.41it/s]

 37%|███▋      | 2226/6015 [15:28<26:14,  2.41it/s]

 37%|███▋      | 2227/6015 [15:29<26:13,  2.41it/s]

 37%|███▋      | 2228/6015 [15:29<26:13,  2.41it/s]

 37%|███▋      | 2229/6015 [15:30<26:12,  2.41it/s]

 37%|███▋      | 2230/6015 [15:30<26:12,  2.41it/s]

 37%|███▋      | 2231/6015 [15:30<26:13,  2.40it/s]

 37%|███▋      | 2232/6015 [15:31<26:12,  2.41it/s]

 37%|███▋      | 2233/6015 [15:31<26:12,  2.41it/s]

 37%|███▋      | 2234/6015 [15:32<26:11,  2.41it/s]

 37%|███▋      | 2235/6015 [15:32<26:11,  2.40it/s]

 37%|███▋      | 2236/6015 [15:32<26:10,  2.41it/s]

 37%|███▋      | 2237/6015 [15:33<26:10,  2.41it/s]

 37%|███▋      | 2238/6015 [15:33<26:10,  2.40it/s]

 37%|███▋      | 2239/6015 [15:34<26:11,  2.40it/s]

 37%|███▋      | 2240/6015 [15:34<26:09,  2.41it/s]

 37%|███▋      | 2241/6015 [15:35<26:08,  2.41it/s]

 37%|███▋      | 2242/6015 [15:35<26:08,  2.41it/s]

 37%|███▋      | 2243/6015 [15:35<26:09,  2.40it/s]

 37%|███▋      | 2244/6015 [15:36<26:07,  2.41it/s]

 37%|███▋      | 2245/6015 [15:36<26:07,  2.41it/s]

 37%|███▋      | 2246/6015 [15:37<26:08,  2.40it/s]

 37%|███▋      | 2247/6015 [15:37<26:08,  2.40it/s]

 37%|███▋      | 2248/6015 [15:37<26:07,  2.40it/s]

 37%|███▋      | 2249/6015 [15:38<26:06,  2.40it/s]

 37%|███▋      | 2250/6015 [15:38<26:06,  2.40it/s]

 37%|███▋      | 2251/6015 [15:39<26:06,  2.40it/s]

 37%|███▋      | 2252/6015 [15:39<26:06,  2.40it/s]

 37%|███▋      | 2253/6015 [15:40<26:05,  2.40it/s]

 37%|███▋      | 2254/6015 [15:40<26:04,  2.40it/s]

 37%|███▋      | 2255/6015 [15:40<26:02,  2.41it/s]

 38%|███▊      | 2256/6015 [15:41<26:04,  2.40it/s]

 38%|███▊      | 2257/6015 [15:41<26:03,  2.40it/s]

 38%|███▊      | 2258/6015 [15:42<26:04,  2.40it/s]

 38%|███▊      | 2259/6015 [15:42<26:04,  2.40it/s]

 38%|███▊      | 2260/6015 [15:42<26:05,  2.40it/s]

 38%|███▊      | 2261/6015 [15:43<26:03,  2.40it/s]

 38%|███▊      | 2262/6015 [15:43<26:04,  2.40it/s]

 38%|███▊      | 2263/6015 [15:44<26:01,  2.40it/s]

 38%|███▊      | 2264/6015 [15:44<26:01,  2.40it/s]

 38%|███▊      | 2265/6015 [15:45<26:00,  2.40it/s]

 38%|███▊      | 2266/6015 [15:45<25:59,  2.40it/s]

 38%|███▊      | 2267/6015 [15:45<25:59,  2.40it/s]

 38%|███▊      | 2268/6015 [15:46<26:02,  2.40it/s]

 38%|███▊      | 2269/6015 [15:46<26:02,  2.40it/s]

 38%|███▊      | 2270/6015 [15:47<26:01,  2.40it/s]

 38%|███▊      | 2271/6015 [15:47<25:57,  2.40it/s]

 38%|███▊      | 2272/6015 [15:47<26:00,  2.40it/s]

 38%|███▊      | 2273/6015 [15:48<26:00,  2.40it/s]

 38%|███▊      | 2274/6015 [15:48<25:59,  2.40it/s]

 38%|███▊      | 2275/6015 [15:49<25:59,  2.40it/s]

 38%|███▊      | 2276/6015 [15:49<25:59,  2.40it/s]

 38%|███▊      | 2277/6015 [15:50<25:58,  2.40it/s]

 38%|███▊      | 2278/6015 [15:50<25:57,  2.40it/s]

 38%|███▊      | 2279/6015 [15:50<25:55,  2.40it/s]

 38%|███▊      | 2280/6015 [15:51<25:56,  2.40it/s]

 38%|███▊      | 2281/6015 [15:51<25:56,  2.40it/s]

 38%|███▊      | 2282/6015 [15:52<25:54,  2.40it/s]

 38%|███▊      | 2283/6015 [15:52<25:54,  2.40it/s]

 38%|███▊      | 2284/6015 [15:52<25:54,  2.40it/s]

 38%|███▊      | 2285/6015 [15:53<25:53,  2.40it/s]

 38%|███▊      | 2286/6015 [15:53<25:52,  2.40it/s]

 38%|███▊      | 2287/6015 [15:54<25:54,  2.40it/s]

 38%|███▊      | 2288/6015 [15:54<25:52,  2.40it/s]

 38%|███▊      | 2289/6015 [15:55<25:52,  2.40it/s]

 38%|███▊      | 2290/6015 [15:55<25:50,  2.40it/s]

 38%|███▊      | 2291/6015 [15:55<25:51,  2.40it/s]

 38%|███▊      | 2292/6015 [15:56<25:50,  2.40it/s]

 38%|███▊      | 2293/6015 [15:56<25:50,  2.40it/s]

 38%|███▊      | 2294/6015 [15:57<25:49,  2.40it/s]

 38%|███▊      | 2295/6015 [15:57<25:48,  2.40it/s]

 38%|███▊      | 2296/6015 [15:57<25:45,  2.41it/s]

 38%|███▊      | 2297/6015 [15:58<25:46,  2.40it/s]

 38%|███▊      | 2298/6015 [15:58<25:46,  2.40it/s]

 38%|███▊      | 2299/6015 [15:59<25:47,  2.40it/s]

 38%|███▊      | 2300/6015 [15:59<25:46,  2.40it/s]

 38%|███▊      | 2301/6015 [16:00<25:45,  2.40it/s]

 38%|███▊      | 2302/6015 [16:00<25:45,  2.40it/s]

 38%|███▊      | 2303/6015 [16:00<25:44,  2.40it/s]

 38%|███▊      | 2304/6015 [16:01<25:44,  2.40it/s]

 38%|███▊      | 2305/6015 [16:01<25:45,  2.40it/s]

 38%|███▊      | 2306/6015 [16:02<25:46,  2.40it/s]

 38%|███▊      | 2307/6015 [16:02<25:45,  2.40it/s]

 38%|███▊      | 2308/6015 [16:02<25:44,  2.40it/s]

 38%|███▊      | 2309/6015 [16:03<25:43,  2.40it/s]

 38%|███▊      | 2310/6015 [16:03<25:48,  2.39it/s]

 38%|███▊      | 2311/6015 [16:04<25:46,  2.40it/s]

 38%|███▊      | 2312/6015 [16:04<25:54,  2.38it/s]

 38%|███▊      | 2313/6015 [16:05<25:49,  2.39it/s]

 38%|███▊      | 2314/6015 [16:05<25:44,  2.40it/s]

 38%|███▊      | 2315/6015 [16:05<25:45,  2.39it/s]

 39%|███▊      | 2316/6015 [16:06<25:43,  2.40it/s]

 39%|███▊      | 2317/6015 [16:06<25:40,  2.40it/s]

 39%|███▊      | 2318/6015 [16:07<25:42,  2.40it/s]

 39%|███▊      | 2319/6015 [16:07<25:41,  2.40it/s]

 39%|███▊      | 2320/6015 [16:07<25:41,  2.40it/s]

 39%|███▊      | 2321/6015 [16:08<25:39,  2.40it/s]

 39%|███▊      | 2322/6015 [16:08<25:40,  2.40it/s]

 39%|███▊      | 2323/6015 [16:09<25:38,  2.40it/s]

 39%|███▊      | 2324/6015 [16:09<25:40,  2.40it/s]

 39%|███▊      | 2325/6015 [16:10<25:39,  2.40it/s]

 39%|███▊      | 2326/6015 [16:10<25:40,  2.39it/s]

 39%|███▊      | 2327/6015 [16:10<25:39,  2.40it/s]

 39%|███▊      | 2328/6015 [16:11<25:39,  2.39it/s]

 39%|███▊      | 2329/6015 [16:11<25:39,  2.39it/s]

 39%|███▊      | 2330/6015 [16:12<25:41,  2.39it/s]

 39%|███▉      | 2331/6015 [16:12<25:39,  2.39it/s]

 39%|███▉      | 2332/6015 [16:13<25:39,  2.39it/s]

 39%|███▉      | 2333/6015 [16:13<25:36,  2.40it/s]

 39%|███▉      | 2334/6015 [16:13<25:35,  2.40it/s]

 39%|███▉      | 2335/6015 [16:14<25:34,  2.40it/s]

 39%|███▉      | 2336/6015 [16:14<25:31,  2.40it/s]

 39%|███▉      | 2337/6015 [16:15<25:31,  2.40it/s]

 39%|███▉      | 2338/6015 [16:15<25:34,  2.40it/s]

 39%|███▉      | 2339/6015 [16:15<25:32,  2.40it/s]

 39%|███▉      | 2340/6015 [16:16<25:33,  2.40it/s]

 39%|███▉      | 2341/6015 [16:16<25:33,  2.40it/s]

 39%|███▉      | 2342/6015 [16:17<25:32,  2.40it/s]

 39%|███▉      | 2343/6015 [16:17<25:32,  2.40it/s]

 39%|███▉      | 2344/6015 [16:18<25:31,  2.40it/s]

 39%|███▉      | 2345/6015 [16:18<25:30,  2.40it/s]

 39%|███▉      | 2346/6015 [16:18<25:30,  2.40it/s]

 39%|███▉      | 2347/6015 [16:19<25:29,  2.40it/s]

 39%|███▉      | 2348/6015 [16:19<25:29,  2.40it/s]

 39%|███▉      | 2349/6015 [16:20<25:31,  2.39it/s]

 39%|███▉      | 2350/6015 [16:20<25:32,  2.39it/s]

 39%|███▉      | 2351/6015 [16:20<25:32,  2.39it/s]

 39%|███▉      | 2352/6015 [16:21<25:32,  2.39it/s]

 39%|███▉      | 2353/6015 [16:21<25:30,  2.39it/s]

 39%|███▉      | 2354/6015 [16:22<25:27,  2.40it/s]

 39%|███▉      | 2355/6015 [16:22<25:31,  2.39it/s]

 39%|███▉      | 2356/6015 [16:23<25:30,  2.39it/s]

 39%|███▉      | 2357/6015 [16:23<25:29,  2.39it/s]

 39%|███▉      | 2358/6015 [16:23<25:28,  2.39it/s]

 39%|███▉      | 2359/6015 [16:24<25:29,  2.39it/s]

 39%|███▉      | 2360/6015 [16:24<25:28,  2.39it/s]

 39%|███▉      | 2361/6015 [16:25<25:29,  2.39it/s]

 39%|███▉      | 2362/6015 [16:25<25:29,  2.39it/s]

 39%|███▉      | 2363/6015 [16:25<25:35,  2.38it/s]

 39%|███▉      | 2364/6015 [16:26<25:31,  2.38it/s]

 39%|███▉      | 2365/6015 [16:26<25:31,  2.38it/s]

 39%|███▉      | 2366/6015 [16:27<25:27,  2.39it/s]

 39%|███▉      | 2367/6015 [16:27<25:26,  2.39it/s]

 39%|███▉      | 2368/6015 [16:28<25:25,  2.39it/s]

 39%|███▉      | 2369/6015 [16:28<25:25,  2.39it/s]

 39%|███▉      | 2370/6015 [16:28<25:21,  2.40it/s]

 39%|███▉      | 2371/6015 [16:29<25:23,  2.39it/s]

 39%|███▉      | 2372/6015 [16:29<25:22,  2.39it/s]

 39%|███▉      | 2373/6015 [16:30<25:23,  2.39it/s]

 39%|███▉      | 2374/6015 [16:30<25:21,  2.39it/s]

 39%|███▉      | 2375/6015 [16:30<25:24,  2.39it/s]

 40%|███▉      | 2376/6015 [16:31<25:25,  2.39it/s]

 40%|███▉      | 2377/6015 [16:31<25:22,  2.39it/s]

 40%|███▉      | 2378/6015 [16:32<25:20,  2.39it/s]

 40%|███▉      | 2379/6015 [16:32<25:20,  2.39it/s]

 40%|███▉      | 2380/6015 [16:33<25:20,  2.39it/s]

 40%|███▉      | 2381/6015 [16:33<25:19,  2.39it/s]

 40%|███▉      | 2382/6015 [16:33<25:19,  2.39it/s]

 40%|███▉      | 2383/6015 [16:34<25:18,  2.39it/s]

 40%|███▉      | 2384/6015 [16:34<25:16,  2.39it/s]

 40%|███▉      | 2385/6015 [16:35<25:25,  2.38it/s]

 40%|███▉      | 2386/6015 [16:35<25:22,  2.38it/s]

 40%|███▉      | 2387/6015 [16:35<25:19,  2.39it/s]

 40%|███▉      | 2388/6015 [16:36<25:21,  2.38it/s]

 40%|███▉      | 2389/6015 [16:36<25:17,  2.39it/s]

 40%|███▉      | 2390/6015 [16:37<25:16,  2.39it/s]

 40%|███▉      | 2391/6015 [16:37<25:14,  2.39it/s]

 40%|███▉      | 2392/6015 [16:38<25:15,  2.39it/s]

 40%|███▉      | 2393/6015 [16:38<25:15,  2.39it/s]

 40%|███▉      | 2394/6015 [16:38<25:16,  2.39it/s]

 40%|███▉      | 2395/6015 [16:39<25:15,  2.39it/s]

 40%|███▉      | 2396/6015 [16:39<25:14,  2.39it/s]

 40%|███▉      | 2397/6015 [16:40<25:13,  2.39it/s]

 40%|███▉      | 2398/6015 [16:40<25:13,  2.39it/s]

 40%|███▉      | 2399/6015 [16:41<25:10,  2.39it/s]

 40%|███▉      | 2400/6015 [16:41<25:09,  2.40it/s]

 40%|███▉      | 2401/6015 [16:41<25:10,  2.39it/s]

 40%|███▉      | 2402/6015 [16:42<25:11,  2.39it/s]

 40%|███▉      | 2403/6015 [16:42<25:08,  2.39it/s]

 40%|███▉      | 2404/6015 [16:43<25:09,  2.39it/s]

 40%|███▉      | 2405/6015 [16:43<25:09,  2.39it/s]

 40%|████      | 2406/6015 [16:43<25:09,  2.39it/s]

 40%|████      | 2407/6015 [16:44<25:09,  2.39it/s]

 40%|████      | 2408/6015 [16:44<25:08,  2.39it/s]

 40%|████      | 2409/6015 [16:45<25:06,  2.39it/s]

 40%|████      | 2410/6015 [16:45<25:06,  2.39it/s]

 40%|████      | 2411/6015 [16:46<25:05,  2.39it/s]

 40%|████      | 2412/6015 [16:46<25:05,  2.39it/s]

 40%|████      | 2413/6015 [16:46<25:03,  2.40it/s]

 40%|████      | 2414/6015 [16:47<25:04,  2.39it/s]

 40%|████      | 2415/6015 [16:47<25:04,  2.39it/s]

 40%|████      | 2416/6015 [16:48<25:06,  2.39it/s]

 40%|████      | 2417/6015 [16:48<25:05,  2.39it/s]

 40%|████      | 2418/6015 [16:48<25:03,  2.39it/s]

 40%|████      | 2419/6015 [16:49<25:03,  2.39it/s]

 40%|████      | 2420/6015 [16:49<25:04,  2.39it/s]

 40%|████      | 2421/6015 [16:50<25:03,  2.39it/s]

 40%|████      | 2422/6015 [16:50<25:05,  2.39it/s]

 40%|████      | 2423/6015 [16:51<25:02,  2.39it/s]

 40%|████      | 2424/6015 [16:51<24:59,  2.40it/s]

 40%|████      | 2425/6015 [16:51<25:00,  2.39it/s]

 40%|████      | 2426/6015 [16:52<25:01,  2.39it/s]

 40%|████      | 2427/6015 [16:52<24:58,  2.39it/s]

 40%|████      | 2428/6015 [16:53<24:58,  2.39it/s]

 40%|████      | 2429/6015 [16:53<24:59,  2.39it/s]

 40%|████      | 2430/6015 [16:53<25:01,  2.39it/s]

 40%|████      | 2431/6015 [16:54<25:01,  2.39it/s]

 40%|████      | 2432/6015 [16:54<24:59,  2.39it/s]

 40%|████      | 2433/6015 [16:55<24:57,  2.39it/s]

 40%|████      | 2434/6015 [16:55<24:57,  2.39it/s]

 40%|████      | 2435/6015 [16:56<24:56,  2.39it/s]

 40%|████      | 2436/6015 [16:56<24:57,  2.39it/s]

 41%|████      | 2437/6015 [16:56<24:57,  2.39it/s]

 41%|████      | 2438/6015 [16:57<24:55,  2.39it/s]

 41%|████      | 2439/6015 [16:57<24:59,  2.39it/s]

 41%|████      | 2440/6015 [16:58<24:57,  2.39it/s]

 41%|████      | 2441/6015 [16:58<24:56,  2.39it/s]

 41%|████      | 2442/6015 [16:59<24:55,  2.39it/s]

 41%|████      | 2443/6015 [16:59<24:56,  2.39it/s]

 41%|████      | 2444/6015 [16:59<24:54,  2.39it/s]

 41%|████      | 2445/6015 [17:00<24:53,  2.39it/s]

 41%|████      | 2446/6015 [17:00<24:53,  2.39it/s]

 41%|████      | 2447/6015 [17:01<24:52,  2.39it/s]

 41%|████      | 2448/6015 [17:01<24:50,  2.39it/s]

 41%|████      | 2449/6015 [17:01<24:55,  2.38it/s]

 41%|████      | 2450/6015 [17:02<24:55,  2.38it/s]

 41%|████      | 2451/6015 [17:02<24:55,  2.38it/s]

 41%|████      | 2452/6015 [17:03<24:53,  2.39it/s]

 41%|████      | 2453/6015 [17:03<24:50,  2.39it/s]

 41%|████      | 2454/6015 [17:04<24:48,  2.39it/s]

 41%|████      | 2455/6015 [17:04<24:49,  2.39it/s]

 41%|████      | 2456/6015 [17:04<24:51,  2.39it/s]

 41%|████      | 2457/6015 [17:05<24:53,  2.38it/s]

 41%|████      | 2458/6015 [17:05<24:50,  2.39it/s]

 41%|████      | 2459/6015 [17:06<24:51,  2.38it/s]

 41%|████      | 2460/6015 [17:06<24:52,  2.38it/s]

 41%|████      | 2461/6015 [17:06<24:51,  2.38it/s]

 41%|████      | 2462/6015 [17:07<24:51,  2.38it/s]

 41%|████      | 2463/6015 [17:07<24:48,  2.39it/s]

 41%|████      | 2464/6015 [17:08<24:47,  2.39it/s]

 41%|████      | 2465/6015 [17:08<24:46,  2.39it/s]

 41%|████      | 2466/6015 [17:09<24:46,  2.39it/s]

 41%|████      | 2467/6015 [17:09<24:45,  2.39it/s]

 41%|████      | 2468/6015 [17:09<24:42,  2.39it/s]

 41%|████      | 2469/6015 [17:10<24:43,  2.39it/s]

 41%|████      | 2470/6015 [17:10<24:44,  2.39it/s]

 41%|████      | 2471/6015 [17:11<24:43,  2.39it/s]

 41%|████      | 2472/6015 [17:11<24:43,  2.39it/s]

 41%|████      | 2473/6015 [17:11<24:43,  2.39it/s]

 41%|████      | 2474/6015 [17:12<24:43,  2.39it/s]

 41%|████      | 2475/6015 [17:12<24:42,  2.39it/s]

 41%|████      | 2476/6015 [17:13<24:42,  2.39it/s]

 41%|████      | 2477/6015 [17:13<24:41,  2.39it/s]

 41%|████      | 2478/6015 [17:14<24:40,  2.39it/s]

 41%|████      | 2479/6015 [17:14<24:45,  2.38it/s]

 41%|████      | 2480/6015 [17:14<24:43,  2.38it/s]

 41%|████      | 2481/6015 [17:15<24:42,  2.38it/s]

 41%|████▏     | 2482/6015 [17:15<24:43,  2.38it/s]

 41%|████▏     | 2483/6015 [17:16<24:43,  2.38it/s]

 41%|████▏     | 2484/6015 [17:16<24:42,  2.38it/s]

 41%|████▏     | 2485/6015 [17:17<24:41,  2.38it/s]

 41%|████▏     | 2486/6015 [17:17<24:37,  2.39it/s]

 41%|████▏     | 2487/6015 [17:17<24:40,  2.38it/s]

 41%|████▏     | 2488/6015 [17:18<24:40,  2.38it/s]

 41%|████▏     | 2489/6015 [17:18<24:37,  2.39it/s]

 41%|████▏     | 2490/6015 [17:19<24:35,  2.39it/s]

 41%|████▏     | 2491/6015 [17:19<24:36,  2.39it/s]

 41%|████▏     | 2492/6015 [17:19<24:36,  2.39it/s]

 41%|████▏     | 2493/6015 [17:20<24:36,  2.39it/s]

 41%|████▏     | 2494/6015 [17:20<24:38,  2.38it/s]

 41%|████▏     | 2495/6015 [17:21<24:35,  2.39it/s]

 41%|████▏     | 2496/6015 [17:21<24:35,  2.38it/s]

 42%|████▏     | 2497/6015 [17:22<24:36,  2.38it/s]

 42%|████▏     | 2498/6015 [17:22<24:35,  2.38it/s]

 42%|████▏     | 2499/6015 [17:22<24:34,  2.39it/s]

 42%|████▏     | 2500/6015 [17:23<24:31,  2.39it/s]

 42%|████▏     | 2501/6015 [17:23<24:30,  2.39it/s]

 42%|████▏     | 2502/6015 [17:24<24:31,  2.39it/s]

 42%|████▏     | 2503/6015 [17:24<24:30,  2.39it/s]

logging
logging the anndata

 42%|████▏     | 2504/6015 [17:25<25:21,  2.31it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 42%|████▏     | 2505/6015 [17:25<24:59,  2.34it/s]

 42%|████▏     | 2506/6015 [17:25<24:46,  2.36it/s]

 42%|████▏     | 2507/6015 [17:26<24:31,  2.38it/s]

 42%|████▏     | 2508/6015 [17:26<24:22,  2.40it/s]

 42%|████▏     | 2509/6015 [17:27<24:15,  2.41it/s]

 42%|████▏     | 2510/6015 [17:27<24:10,  2.42it/s]

 42%|████▏     | 2511/6015 [17:27<24:06,  2.42it/s]

 42%|████▏     | 2512/6015 [17:28<24:04,  2.42it/s]

 42%|████▏     | 2513/6015 [17:28<24:05,  2.42it/s]

 42%|████▏     | 2514/6015 [17:29<24:02,  2.43it/s]

 42%|████▏     | 2515/6015 [17:29<24:00,  2.43it/s]

 42%|████▏     | 2516/6015 [17:29<24:00,  2.43it/s]

 42%|████▏     | 2517/6015 [17:30<23:59,  2.43it/s]

 42%|████▏     | 2518/6015 [17:30<23:57,  2.43it/s]

 42%|████▏     | 2519/6015 [17:31<23:59,  2.43it/s]

 42%|████▏     | 2520/6015 [17:31<24:00,  2.43it/s]

 42%|████▏     | 2521/6015 [17:32<24:00,  2.43it/s]

 42%|████▏     | 2522/6015 [17:32<23:59,  2.43it/s]

 42%|████▏     | 2523/6015 [17:32<23:59,  2.43it/s]

 42%|████▏     | 2524/6015 [17:33<23:57,  2.43it/s]

 42%|████▏     | 2525/6015 [17:33<23:57,  2.43it/s]

 42%|████▏     | 2526/6015 [17:34<23:57,  2.43it/s]

 42%|████▏     | 2527/6015 [17:34<23:56,  2.43it/s]

 42%|████▏     | 2528/6015 [17:34<23:56,  2.43it/s]

 42%|████▏     | 2529/6015 [17:35<23:54,  2.43it/s]

 42%|████▏     | 2530/6015 [17:35<23:55,  2.43it/s]

 42%|████▏     | 2531/6015 [17:36<23:55,  2.43it/s]

 42%|████▏     | 2532/6015 [17:36<23:55,  2.43it/s]

 42%|████▏     | 2533/6015 [17:36<23:56,  2.42it/s]

 42%|████▏     | 2534/6015 [17:37<23:55,  2.43it/s]

 42%|████▏     | 2535/6015 [17:37<23:54,  2.43it/s]

 42%|████▏     | 2536/6015 [17:38<23:55,  2.42it/s]

 42%|████▏     | 2537/6015 [17:38<23:54,  2.42it/s]

 42%|████▏     | 2538/6015 [17:39<23:53,  2.43it/s]

 42%|████▏     | 2539/6015 [17:39<23:53,  2.42it/s]

 42%|████▏     | 2540/6015 [17:39<23:51,  2.43it/s]

 42%|████▏     | 2541/6015 [17:40<23:50,  2.43it/s]

 42%|████▏     | 2542/6015 [17:40<23:51,  2.43it/s]

 42%|████▏     | 2543/6015 [17:41<23:51,  2.43it/s]

 42%|████▏     | 2544/6015 [17:41<23:53,  2.42it/s]

 42%|████▏     | 2545/6015 [17:41<23:52,  2.42it/s]

 42%|████▏     | 2546/6015 [17:42<23:54,  2.42it/s]

 42%|████▏     | 2547/6015 [17:42<23:52,  2.42it/s]

 42%|████▏     | 2548/6015 [17:43<23:49,  2.42it/s]

 42%|████▏     | 2549/6015 [17:43<23:48,  2.43it/s]

 42%|████▏     | 2550/6015 [17:43<23:47,  2.43it/s]

 42%|████▏     | 2551/6015 [17:44<23:47,  2.43it/s]

 42%|████▏     | 2552/6015 [17:44<23:47,  2.43it/s]

 42%|████▏     | 2553/6015 [17:45<23:49,  2.42it/s]

 42%|████▏     | 2554/6015 [17:45<23:47,  2.42it/s]

 42%|████▏     | 2555/6015 [17:46<23:47,  2.42it/s]

 42%|████▏     | 2556/6015 [17:46<23:48,  2.42it/s]

 43%|████▎     | 2557/6015 [17:46<23:48,  2.42it/s]

 43%|████▎     | 2558/6015 [17:47<23:47,  2.42it/s]

 43%|████▎     | 2559/6015 [17:47<23:45,  2.43it/s]

 43%|████▎     | 2560/6015 [17:48<23:45,  2.42it/s]

 43%|████▎     | 2561/6015 [17:48<23:45,  2.42it/s]

 43%|████▎     | 2562/6015 [17:48<23:45,  2.42it/s]

 43%|████▎     | 2563/6015 [17:49<23:43,  2.42it/s]

 43%|████▎     | 2564/6015 [17:49<23:44,  2.42it/s]

 43%|████▎     | 2565/6015 [17:50<23:43,  2.42it/s]

 43%|████▎     | 2566/6015 [17:50<23:43,  2.42it/s]

 43%|████▎     | 2567/6015 [17:51<23:42,  2.42it/s]

 43%|████▎     | 2568/6015 [17:51<23:41,  2.43it/s]

 43%|████▎     | 2569/6015 [17:51<23:40,  2.43it/s]

 43%|████▎     | 2570/6015 [17:52<23:42,  2.42it/s]

 43%|████▎     | 2571/6015 [17:52<23:40,  2.42it/s]

 43%|████▎     | 2572/6015 [17:53<23:40,  2.42it/s]

 43%|████▎     | 2573/6015 [17:53<23:39,  2.43it/s]

 43%|████▎     | 2574/6015 [17:53<23:38,  2.43it/s]

 43%|████▎     | 2575/6015 [17:54<23:40,  2.42it/s]

 43%|████▎     | 2576/6015 [17:54<23:39,  2.42it/s]

 43%|████▎     | 2577/6015 [17:55<23:39,  2.42it/s]

 43%|████▎     | 2578/6015 [17:55<23:37,  2.42it/s]

 43%|████▎     | 2579/6015 [17:55<23:37,  2.42it/s]

 43%|████▎     | 2580/6015 [17:56<23:36,  2.42it/s]

 43%|████▎     | 2581/6015 [17:56<23:35,  2.43it/s]

 43%|████▎     | 2582/6015 [17:57<23:39,  2.42it/s]

 43%|████▎     | 2583/6015 [17:57<23:38,  2.42it/s]

 43%|████▎     | 2584/6015 [17:58<23:37,  2.42it/s]

 43%|████▎     | 2585/6015 [17:58<23:36,  2.42it/s]

 43%|████▎     | 2586/6015 [17:58<23:37,  2.42it/s]

 43%|████▎     | 2587/6015 [17:59<23:37,  2.42it/s]

 43%|████▎     | 2588/6015 [17:59<23:37,  2.42it/s]

 43%|████▎     | 2589/6015 [18:00<23:35,  2.42it/s]

 43%|████▎     | 2590/6015 [18:00<23:35,  2.42it/s]

 43%|████▎     | 2591/6015 [18:00<23:32,  2.42it/s]

 43%|████▎     | 2592/6015 [18:01<23:32,  2.42it/s]

 43%|████▎     | 2593/6015 [18:01<23:30,  2.43it/s]

 43%|████▎     | 2594/6015 [18:02<23:31,  2.42it/s]

 43%|████▎     | 2595/6015 [18:02<23:30,  2.42it/s]

 43%|████▎     | 2596/6015 [18:02<23:31,  2.42it/s]

 43%|████▎     | 2597/6015 [18:03<23:30,  2.42it/s]

 43%|████▎     | 2598/6015 [18:03<23:31,  2.42it/s]

 43%|████▎     | 2599/6015 [18:04<23:34,  2.42it/s]

 43%|████▎     | 2600/6015 [18:04<23:31,  2.42it/s]

 43%|████▎     | 2601/6015 [18:05<23:31,  2.42it/s]

 43%|████▎     | 2602/6015 [18:05<23:33,  2.41it/s]

 43%|████▎     | 2603/6015 [18:05<23:32,  2.42it/s]

 43%|████▎     | 2604/6015 [18:06<23:30,  2.42it/s]

 43%|████▎     | 2605/6015 [18:06<23:28,  2.42it/s]

 43%|████▎     | 2606/6015 [18:07<23:29,  2.42it/s]

 43%|████▎     | 2607/6015 [18:07<23:27,  2.42it/s]

 43%|████▎     | 2608/6015 [18:07<23:26,  2.42it/s]

 43%|████▎     | 2609/6015 [18:08<23:25,  2.42it/s]

 43%|████▎     | 2610/6015 [18:08<23:28,  2.42it/s]

 43%|████▎     | 2611/6015 [18:09<23:25,  2.42it/s]

 43%|████▎     | 2612/6015 [18:09<23:22,  2.43it/s]

 43%|████▎     | 2613/6015 [18:09<23:22,  2.43it/s]

 43%|████▎     | 2614/6015 [18:10<23:24,  2.42it/s]

 43%|████▎     | 2615/6015 [18:10<23:24,  2.42it/s]

 43%|████▎     | 2616/6015 [18:11<23:26,  2.42it/s]

 44%|████▎     | 2617/6015 [18:11<23:24,  2.42it/s]

 44%|████▎     | 2618/6015 [18:12<23:25,  2.42it/s]

 44%|████▎     | 2619/6015 [18:12<23:25,  2.42it/s]

 44%|████▎     | 2620/6015 [18:12<23:24,  2.42it/s]

 44%|████▎     | 2621/6015 [18:13<23:24,  2.42it/s]

 44%|████▎     | 2622/6015 [18:13<23:24,  2.42it/s]

 44%|████▎     | 2623/6015 [18:14<23:26,  2.41it/s]

 44%|████▎     | 2624/6015 [18:14<23:24,  2.41it/s]

 44%|████▎     | 2625/6015 [18:14<23:22,  2.42it/s]

 44%|████▎     | 2626/6015 [18:15<23:22,  2.42it/s]

 44%|████▎     | 2627/6015 [18:15<23:23,  2.41it/s]

 44%|████▎     | 2628/6015 [18:16<23:21,  2.42it/s]

 44%|████▎     | 2629/6015 [18:16<23:20,  2.42it/s]

 44%|████▎     | 2630/6015 [18:17<23:18,  2.42it/s]

 44%|████▎     | 2631/6015 [18:17<23:17,  2.42it/s]

 44%|████▍     | 2632/6015 [18:17<23:16,  2.42it/s]

 44%|████▍     | 2633/6015 [18:18<23:17,  2.42it/s]

 44%|████▍     | 2634/6015 [18:18<23:19,  2.42it/s]

 44%|████▍     | 2635/6015 [18:19<23:20,  2.41it/s]

 44%|████▍     | 2636/6015 [18:19<23:22,  2.41it/s]

 44%|████▍     | 2637/6015 [18:19<23:19,  2.41it/s]

 44%|████▍     | 2638/6015 [18:20<23:19,  2.41it/s]

 44%|████▍     | 2639/6015 [18:20<23:18,  2.41it/s]

 44%|████▍     | 2640/6015 [18:21<23:17,  2.42it/s]

 44%|████▍     | 2641/6015 [18:21<23:15,  2.42it/s]

 44%|████▍     | 2642/6015 [18:21<23:14,  2.42it/s]

 44%|████▍     | 2643/6015 [18:22<23:12,  2.42it/s]

 44%|████▍     | 2644/6015 [18:22<23:12,  2.42it/s]

 44%|████▍     | 2645/6015 [18:23<23:12,  2.42it/s]

 44%|████▍     | 2646/6015 [18:23<23:13,  2.42it/s]

 44%|████▍     | 2647/6015 [18:24<23:13,  2.42it/s]

 44%|████▍     | 2648/6015 [18:24<23:13,  2.42it/s]

 44%|████▍     | 2649/6015 [18:24<23:11,  2.42it/s]

 44%|████▍     | 2650/6015 [18:25<23:10,  2.42it/s]

 44%|████▍     | 2651/6015 [18:25<23:09,  2.42it/s]

 44%|████▍     | 2652/6015 [18:26<23:10,  2.42it/s]

 44%|████▍     | 2653/6015 [18:26<23:11,  2.42it/s]

 44%|████▍     | 2654/6015 [18:26<23:10,  2.42it/s]

 44%|████▍     | 2655/6015 [18:27<23:10,  2.42it/s]

 44%|████▍     | 2656/6015 [18:27<23:12,  2.41it/s]

 44%|████▍     | 2657/6015 [18:28<23:11,  2.41it/s]

 44%|████▍     | 2658/6015 [18:28<23:09,  2.42it/s]

 44%|████▍     | 2659/6015 [18:29<23:09,  2.42it/s]

 44%|████▍     | 2660/6015 [18:29<23:08,  2.42it/s]

 44%|████▍     | 2661/6015 [18:29<23:07,  2.42it/s]

 44%|████▍     | 2662/6015 [18:30<23:07,  2.42it/s]

 44%|████▍     | 2663/6015 [18:30<23:08,  2.41it/s]

 44%|████▍     | 2664/6015 [18:31<23:06,  2.42it/s]

 44%|████▍     | 2665/6015 [18:31<23:07,  2.42it/s]

 44%|████▍     | 2666/6015 [18:31<23:06,  2.42it/s]

 44%|████▍     | 2667/6015 [18:32<23:08,  2.41it/s]

 44%|████▍     | 2668/6015 [18:32<23:05,  2.41it/s]

 44%|████▍     | 2669/6015 [18:33<23:05,  2.41it/s]

 44%|████▍     | 2670/6015 [18:33<23:06,  2.41it/s]

 44%|████▍     | 2671/6015 [18:33<23:04,  2.42it/s]

 44%|████▍     | 2672/6015 [18:34<23:03,  2.42it/s]

 44%|████▍     | 2673/6015 [18:34<23:02,  2.42it/s]

 44%|████▍     | 2674/6015 [18:35<23:03,  2.42it/s]

 44%|████▍     | 2675/6015 [18:35<23:04,  2.41it/s]

 44%|████▍     | 2676/6015 [18:36<23:06,  2.41it/s]

 45%|████▍     | 2677/6015 [18:36<23:04,  2.41it/s]

 45%|████▍     | 2678/6015 [18:36<23:03,  2.41it/s]

 45%|████▍     | 2679/6015 [18:37<23:04,  2.41it/s]

 45%|████▍     | 2680/6015 [18:37<23:02,  2.41it/s]

 45%|████▍     | 2681/6015 [18:38<23:01,  2.41it/s]

 45%|████▍     | 2682/6015 [18:38<23:01,  2.41it/s]

 45%|████▍     | 2683/6015 [18:38<22:59,  2.42it/s]

 45%|████▍     | 2684/6015 [18:39<22:58,  2.42it/s]

 45%|████▍     | 2685/6015 [18:39<22:56,  2.42it/s]

 45%|████▍     | 2686/6015 [18:40<22:57,  2.42it/s]

 45%|████▍     | 2687/6015 [18:40<22:56,  2.42it/s]

 45%|████▍     | 2688/6015 [18:41<22:56,  2.42it/s]

 45%|████▍     | 2689/6015 [18:41<22:55,  2.42it/s]

 45%|████▍     | 2690/6015 [18:41<22:55,  2.42it/s]

 45%|████▍     | 2691/6015 [18:42<22:56,  2.41it/s]

 45%|████▍     | 2692/6015 [18:42<22:55,  2.42it/s]

 45%|████▍     | 2693/6015 [18:43<22:56,  2.41it/s]

 45%|████▍     | 2694/6015 [18:43<22:56,  2.41it/s]

 45%|████▍     | 2695/6015 [18:43<22:56,  2.41it/s]

 45%|████▍     | 2696/6015 [18:44<22:56,  2.41it/s]

 45%|████▍     | 2697/6015 [18:44<22:55,  2.41it/s]

 45%|████▍     | 2698/6015 [18:45<22:57,  2.41it/s]

 45%|████▍     | 2699/6015 [18:45<22:56,  2.41it/s]

 45%|████▍     | 2700/6015 [18:46<22:54,  2.41it/s]

 45%|████▍     | 2701/6015 [18:46<22:54,  2.41it/s]

 45%|████▍     | 2702/6015 [18:46<22:55,  2.41it/s]

 45%|████▍     | 2703/6015 [18:47<22:54,  2.41it/s]

 45%|████▍     | 2704/6015 [18:47<22:53,  2.41it/s]

 45%|████▍     | 2705/6015 [18:48<22:52,  2.41it/s]

 45%|████▍     | 2706/6015 [18:48<22:51,  2.41it/s]

 45%|████▌     | 2707/6015 [18:48<22:53,  2.41it/s]

 45%|████▌     | 2708/6015 [18:49<22:53,  2.41it/s]

 45%|████▌     | 2709/6015 [18:49<22:53,  2.41it/s]

 45%|████▌     | 2710/6015 [18:50<22:51,  2.41it/s]

 45%|████▌     | 2711/6015 [18:50<22:49,  2.41it/s]

 45%|████▌     | 2712/6015 [18:50<22:48,  2.41it/s]

 45%|████▌     | 2713/6015 [18:51<22:49,  2.41it/s]

 45%|████▌     | 2714/6015 [18:51<22:47,  2.41it/s]

 45%|████▌     | 2715/6015 [18:52<22:47,  2.41it/s]

 45%|████▌     | 2716/6015 [18:52<22:48,  2.41it/s]

 45%|████▌     | 2717/6015 [18:53<22:46,  2.41it/s]

 45%|████▌     | 2718/6015 [18:53<22:50,  2.41it/s]

 45%|████▌     | 2719/6015 [18:53<22:48,  2.41it/s]

 45%|████▌     | 2720/6015 [18:54<22:48,  2.41it/s]

 45%|████▌     | 2721/6015 [18:54<22:48,  2.41it/s]

 45%|████▌     | 2722/6015 [18:55<22:47,  2.41it/s]

 45%|████▌     | 2723/6015 [18:55<22:45,  2.41it/s]

 45%|████▌     | 2724/6015 [18:55<22:45,  2.41it/s]

 45%|████▌     | 2725/6015 [18:56<22:42,  2.41it/s]

 45%|████▌     | 2726/6015 [18:56<22:42,  2.41it/s]

 45%|████▌     | 2727/6015 [18:57<22:42,  2.41it/s]

 45%|████▌     | 2728/6015 [18:57<22:41,  2.41it/s]

 45%|████▌     | 2729/6015 [18:58<22:41,  2.41it/s]

 45%|████▌     | 2730/6015 [18:58<22:41,  2.41it/s]

 45%|████▌     | 2731/6015 [18:58<22:40,  2.41it/s]

 45%|████▌     | 2732/6015 [18:59<22:39,  2.42it/s]

 45%|████▌     | 2733/6015 [18:59<22:39,  2.41it/s]

 45%|████▌     | 2734/6015 [19:00<22:38,  2.42it/s]

 45%|████▌     | 2735/6015 [19:00<22:37,  2.42it/s]

 45%|████▌     | 2736/6015 [19:00<22:37,  2.42it/s]

 46%|████▌     | 2737/6015 [19:01<22:36,  2.42it/s]

 46%|████▌     | 2738/6015 [19:01<22:36,  2.42it/s]

 46%|████▌     | 2739/6015 [19:02<22:36,  2.42it/s]

 46%|████▌     | 2740/6015 [19:02<22:35,  2.42it/s]

 46%|████▌     | 2741/6015 [19:03<22:39,  2.41it/s]

 46%|████▌     | 2742/6015 [19:03<22:39,  2.41it/s]

 46%|████▌     | 2743/6015 [19:03<22:37,  2.41it/s]

 46%|████▌     | 2744/6015 [19:04<22:36,  2.41it/s]

 46%|████▌     | 2745/6015 [19:04<22:36,  2.41it/s]

 46%|████▌     | 2746/6015 [19:05<22:35,  2.41it/s]

 46%|████▌     | 2747/6015 [19:05<22:34,  2.41it/s]

 46%|████▌     | 2748/6015 [19:05<22:34,  2.41it/s]

 46%|████▌     | 2749/6015 [19:06<22:34,  2.41it/s]

 46%|████▌     | 2750/6015 [19:06<22:33,  2.41it/s]

 46%|████▌     | 2751/6015 [19:07<22:33,  2.41it/s]

 46%|████▌     | 2752/6015 [19:07<22:33,  2.41it/s]

 46%|████▌     | 2753/6015 [19:07<22:33,  2.41it/s]

 46%|████▌     | 2754/6015 [19:08<22:35,  2.41it/s]

 46%|████▌     | 2755/6015 [19:08<22:32,  2.41it/s]

 46%|████▌     | 2756/6015 [19:09<22:31,  2.41it/s]

 46%|████▌     | 2757/6015 [19:09<22:30,  2.41it/s]

 46%|████▌     | 2758/6015 [19:10<22:31,  2.41it/s]

 46%|████▌     | 2759/6015 [19:10<22:31,  2.41it/s]

 46%|████▌     | 2760/6015 [19:10<22:30,  2.41it/s]

 46%|████▌     | 2761/6015 [19:11<22:29,  2.41it/s]

 46%|████▌     | 2762/6015 [19:11<22:29,  2.41it/s]

 46%|████▌     | 2763/6015 [19:12<22:27,  2.41it/s]

 46%|████▌     | 2764/6015 [19:12<22:28,  2.41it/s]

 46%|████▌     | 2765/6015 [19:12<22:29,  2.41it/s]

 46%|████▌     | 2766/6015 [19:13<22:30,  2.41it/s]

 46%|████▌     | 2767/6015 [19:13<22:28,  2.41it/s]

 46%|████▌     | 2768/6015 [19:14<22:28,  2.41it/s]

 46%|████▌     | 2769/6015 [19:14<22:28,  2.41it/s]

 46%|████▌     | 2770/6015 [19:15<22:27,  2.41it/s]

 46%|████▌     | 2771/6015 [19:15<22:27,  2.41it/s]

 46%|████▌     | 2772/6015 [19:15<22:27,  2.41it/s]

 46%|████▌     | 2773/6015 [19:16<22:25,  2.41it/s]

 46%|████▌     | 2774/6015 [19:16<22:25,  2.41it/s]

 46%|████▌     | 2775/6015 [19:17<22:24,  2.41it/s]

 46%|████▌     | 2776/6015 [19:17<22:23,  2.41it/s]

 46%|████▌     | 2777/6015 [19:17<22:23,  2.41it/s]

 46%|████▌     | 2778/6015 [19:18<22:23,  2.41it/s]

 46%|████▌     | 2779/6015 [19:18<22:23,  2.41it/s]

 46%|████▌     | 2780/6015 [19:19<22:24,  2.41it/s]

 46%|████▌     | 2781/6015 [19:19<22:23,  2.41it/s]

 46%|████▋     | 2782/6015 [19:20<22:22,  2.41it/s]

 46%|████▋     | 2783/6015 [19:20<22:22,  2.41it/s]

 46%|████▋     | 2784/6015 [19:20<22:20,  2.41it/s]

 46%|████▋     | 2785/6015 [19:21<22:20,  2.41it/s]

 46%|████▋     | 2786/6015 [19:21<22:20,  2.41it/s]

 46%|████▋     | 2787/6015 [19:22<22:19,  2.41it/s]

 46%|████▋     | 2788/6015 [19:22<22:18,  2.41it/s]

 46%|████▋     | 2789/6015 [19:22<22:20,  2.41it/s]

 46%|████▋     | 2790/6015 [19:23<22:20,  2.41it/s]

 46%|████▋     | 2791/6015 [19:23<22:20,  2.41it/s]

 46%|████▋     | 2792/6015 [19:24<22:19,  2.41it/s]

 46%|████▋     | 2793/6015 [19:24<22:19,  2.41it/s]

 46%|████▋     | 2794/6015 [19:25<22:20,  2.40it/s]

 46%|████▋     | 2795/6015 [19:25<22:21,  2.40it/s]

 46%|████▋     | 2796/6015 [19:25<22:22,  2.40it/s]

 47%|████▋     | 2797/6015 [19:26<22:18,  2.40it/s]

 47%|████▋     | 2798/6015 [19:26<22:19,  2.40it/s]

 47%|████▋     | 2799/6015 [19:27<22:18,  2.40it/s]

 47%|████▋     | 2800/6015 [19:27<22:18,  2.40it/s]

 47%|████▋     | 2801/6015 [19:27<22:15,  2.41it/s]

 47%|████▋     | 2802/6015 [19:28<22:16,  2.40it/s]

 47%|████▋     | 2803/6015 [19:28<22:15,  2.40it/s]

 47%|████▋     | 2804/6015 [19:29<22:14,  2.41it/s]

 47%|████▋     | 2805/6015 [19:29<22:13,  2.41it/s]

 47%|████▋     | 2806/6015 [19:30<22:15,  2.40it/s]

 47%|████▋     | 2807/6015 [19:30<22:13,  2.40it/s]

 47%|████▋     | 2808/6015 [19:30<22:14,  2.40it/s]

 47%|████▋     | 2809/6015 [19:31<22:14,  2.40it/s]

 47%|████▋     | 2810/6015 [19:31<22:15,  2.40it/s]

 47%|████▋     | 2811/6015 [19:32<22:13,  2.40it/s]

 47%|████▋     | 2812/6015 [19:32<22:15,  2.40it/s]

 47%|████▋     | 2813/6015 [19:32<22:12,  2.40it/s]

 47%|████▋     | 2814/6015 [19:33<22:11,  2.40it/s]

 47%|████▋     | 2815/6015 [19:33<22:11,  2.40it/s]

 47%|████▋     | 2816/6015 [19:34<22:12,  2.40it/s]

 47%|████▋     | 2817/6015 [19:34<22:10,  2.40it/s]

 47%|████▋     | 2818/6015 [19:35<22:09,  2.41it/s]

 47%|████▋     | 2819/6015 [19:35<22:08,  2.40it/s]

 47%|████▋     | 2820/6015 [19:35<22:09,  2.40it/s]

 47%|████▋     | 2821/6015 [19:36<22:08,  2.40it/s]

 47%|████▋     | 2822/6015 [19:36<22:06,  2.41it/s]

 47%|████▋     | 2823/6015 [19:37<22:06,  2.41it/s]

 47%|████▋     | 2824/6015 [19:37<22:03,  2.41it/s]

 47%|████▋     | 2825/6015 [19:37<22:02,  2.41it/s]

 47%|████▋     | 2826/6015 [19:38<22:02,  2.41it/s]

 47%|████▋     | 2827/6015 [19:38<22:01,  2.41it/s]

 47%|████▋     | 2828/6015 [19:39<22:02,  2.41it/s]

 47%|████▋     | 2829/6015 [19:39<22:03,  2.41it/s]

 47%|████▋     | 2830/6015 [19:39<22:04,  2.40it/s]

 47%|████▋     | 2831/6015 [19:40<22:08,  2.40it/s]

 47%|████▋     | 2832/6015 [19:40<22:06,  2.40it/s]

 47%|████▋     | 2833/6015 [19:41<22:06,  2.40it/s]

 47%|████▋     | 2834/6015 [19:41<22:06,  2.40it/s]

 47%|████▋     | 2835/6015 [19:42<22:06,  2.40it/s]

 47%|████▋     | 2836/6015 [19:42<22:03,  2.40it/s]

 47%|████▋     | 2837/6015 [19:42<22:01,  2.40it/s]

 47%|████▋     | 2838/6015 [19:43<22:00,  2.41it/s]

 47%|████▋     | 2839/6015 [19:43<22:00,  2.40it/s]

 47%|████▋     | 2840/6015 [19:44<21:59,  2.41it/s]

 47%|████▋     | 2841/6015 [19:44<21:59,  2.41it/s]

 47%|████▋     | 2842/6015 [19:44<21:58,  2.41it/s]

 47%|████▋     | 2843/6015 [19:45<21:58,  2.41it/s]

 47%|████▋     | 2844/6015 [19:45<21:57,  2.41it/s]

 47%|████▋     | 2845/6015 [19:46<21:58,  2.40it/s]

 47%|████▋     | 2846/6015 [19:46<22:00,  2.40it/s]

 47%|████▋     | 2847/6015 [19:47<22:01,  2.40it/s]

 47%|████▋     | 2848/6015 [19:47<21:58,  2.40it/s]

 47%|████▋     | 2849/6015 [19:47<21:56,  2.40it/s]

 47%|████▋     | 2850/6015 [19:48<21:59,  2.40it/s]

 47%|████▋     | 2851/6015 [19:48<21:58,  2.40it/s]

 47%|████▋     | 2852/6015 [19:49<21:56,  2.40it/s]

 47%|████▋     | 2853/6015 [19:49<21:55,  2.40it/s]

 47%|████▋     | 2854/6015 [19:49<21:55,  2.40it/s]

 47%|████▋     | 2855/6015 [19:50<21:54,  2.40it/s]

 47%|████▋     | 2856/6015 [19:50<21:55,  2.40it/s]

 47%|████▋     | 2857/6015 [19:51<21:53,  2.40it/s]

 48%|████▊     | 2858/6015 [19:51<21:53,  2.40it/s]

 48%|████▊     | 2859/6015 [19:52<21:54,  2.40it/s]

 48%|████▊     | 2860/6015 [19:52<21:54,  2.40it/s]

 48%|████▊     | 2861/6015 [19:52<21:52,  2.40it/s]

 48%|████▊     | 2862/6015 [19:53<21:52,  2.40it/s]

 48%|████▊     | 2863/6015 [19:53<21:51,  2.40it/s]

 48%|████▊     | 2864/6015 [19:54<21:50,  2.40it/s]

 48%|████▊     | 2865/6015 [19:54<21:50,  2.40it/s]

 48%|████▊     | 2866/6015 [19:54<21:56,  2.39it/s]

 48%|████▊     | 2867/6015 [19:55<21:55,  2.39it/s]

 48%|████▊     | 2868/6015 [19:55<21:54,  2.39it/s]

 48%|████▊     | 2869/6015 [19:56<21:56,  2.39it/s]

 48%|████▊     | 2870/6015 [19:56<21:54,  2.39it/s]

 48%|████▊     | 2871/6015 [19:57<21:52,  2.39it/s]

 48%|████▊     | 2872/6015 [19:57<21:51,  2.40it/s]

 48%|████▊     | 2873/6015 [19:57<21:50,  2.40it/s]

 48%|████▊     | 2874/6015 [19:58<21:50,  2.40it/s]

 48%|████▊     | 2875/6015 [19:58<21:48,  2.40it/s]

 48%|████▊     | 2876/6015 [19:59<21:47,  2.40it/s]

 48%|████▊     | 2877/6015 [19:59<21:45,  2.40it/s]

 48%|████▊     | 2878/6015 [19:59<21:49,  2.39it/s]

 48%|████▊     | 2879/6015 [20:00<21:48,  2.40it/s]

 48%|████▊     | 2880/6015 [20:00<21:47,  2.40it/s]

 48%|████▊     | 2881/6015 [20:01<21:46,  2.40it/s]

 48%|████▊     | 2882/6015 [20:01<21:45,  2.40it/s]

 48%|████▊     | 2883/6015 [20:02<21:44,  2.40it/s]

 48%|████▊     | 2884/6015 [20:02<21:43,  2.40it/s]

 48%|████▊     | 2885/6015 [20:02<21:43,  2.40it/s]

 48%|████▊     | 2886/6015 [20:03<21:46,  2.40it/s]

 48%|████▊     | 2887/6015 [20:03<21:43,  2.40it/s]

 48%|████▊     | 2888/6015 [20:04<21:42,  2.40it/s]

 48%|████▊     | 2889/6015 [20:04<21:42,  2.40it/s]

 48%|████▊     | 2890/6015 [20:04<21:43,  2.40it/s]

 48%|████▊     | 2891/6015 [20:05<21:41,  2.40it/s]

 48%|████▊     | 2892/6015 [20:05<21:40,  2.40it/s]

 48%|████▊     | 2893/6015 [20:06<21:38,  2.40it/s]

 48%|████▊     | 2894/6015 [20:06<21:38,  2.40it/s]

 48%|████▊     | 2895/6015 [20:07<21:38,  2.40it/s]

 48%|████▊     | 2896/6015 [20:07<21:38,  2.40it/s]

 48%|████▊     | 2897/6015 [20:07<21:38,  2.40it/s]

 48%|████▊     | 2898/6015 [20:08<21:37,  2.40it/s]

 48%|████▊     | 2899/6015 [20:08<21:36,  2.40it/s]

 48%|████▊     | 2900/6015 [20:09<21:36,  2.40it/s]

 48%|████▊     | 2901/6015 [20:09<21:36,  2.40it/s]

 48%|████▊     | 2902/6015 [20:09<21:35,  2.40it/s]

 48%|████▊     | 2903/6015 [20:10<21:33,  2.40it/s]

 48%|████▊     | 2904/6015 [20:10<21:33,  2.40it/s]

 48%|████▊     | 2905/6015 [20:11<21:34,  2.40it/s]

 48%|████▊     | 2906/6015 [20:11<21:34,  2.40it/s]

 48%|████▊     | 2907/6015 [20:12<21:34,  2.40it/s]

 48%|████▊     | 2908/6015 [20:12<21:34,  2.40it/s]

 48%|████▊     | 2909/6015 [20:12<21:34,  2.40it/s]

 48%|████▊     | 2910/6015 [20:13<21:32,  2.40it/s]

 48%|████▊     | 2911/6015 [20:13<21:31,  2.40it/s]

 48%|████▊     | 2912/6015 [20:14<21:30,  2.40it/s]

 48%|████▊     | 2913/6015 [20:14<21:32,  2.40it/s]

 48%|████▊     | 2914/6015 [20:14<21:31,  2.40it/s]

 48%|████▊     | 2915/6015 [20:15<21:31,  2.40it/s]

 48%|████▊     | 2916/6015 [20:15<21:31,  2.40it/s]

 48%|████▊     | 2917/6015 [20:16<21:31,  2.40it/s]

 49%|████▊     | 2918/6015 [20:16<21:29,  2.40it/s]

 49%|████▊     | 2919/6015 [20:17<21:29,  2.40it/s]

 49%|████▊     | 2920/6015 [20:17<21:29,  2.40it/s]

 49%|████▊     | 2921/6015 [20:17<21:29,  2.40it/s]

 49%|████▊     | 2922/6015 [20:18<21:30,  2.40it/s]

 49%|████▊     | 2923/6015 [20:18<21:29,  2.40it/s]

 49%|████▊     | 2924/6015 [20:19<21:27,  2.40it/s]

 49%|████▊     | 2925/6015 [20:19<21:27,  2.40it/s]

 49%|████▊     | 2926/6015 [20:19<21:26,  2.40it/s]

 49%|████▊     | 2927/6015 [20:20<21:25,  2.40it/s]

 49%|████▊     | 2928/6015 [20:20<21:25,  2.40it/s]

 49%|████▊     | 2929/6015 [20:21<21:25,  2.40it/s]

 49%|████▊     | 2930/6015 [20:21<21:24,  2.40it/s]

 49%|████▊     | 2931/6015 [20:22<21:24,  2.40it/s]

 49%|████▊     | 2932/6015 [20:22<21:23,  2.40it/s]

 49%|████▉     | 2933/6015 [20:22<21:23,  2.40it/s]

 49%|████▉     | 2934/6015 [20:23<21:23,  2.40it/s]

 49%|████▉     | 2935/6015 [20:23<21:22,  2.40it/s]

 49%|████▉     | 2936/6015 [20:24<21:24,  2.40it/s]

 49%|████▉     | 2937/6015 [20:24<21:23,  2.40it/s]

 49%|████▉     | 2938/6015 [20:24<21:22,  2.40it/s]

 49%|████▉     | 2939/6015 [20:25<21:21,  2.40it/s]

 49%|████▉     | 2940/6015 [20:25<21:21,  2.40it/s]

 49%|████▉     | 2941/6015 [20:26<21:22,  2.40it/s]

 49%|████▉     | 2942/6015 [20:26<21:21,  2.40it/s]

 49%|████▉     | 2943/6015 [20:27<21:20,  2.40it/s]

 49%|████▉     | 2944/6015 [20:27<21:20,  2.40it/s]

 49%|████▉     | 2945/6015 [20:27<21:24,  2.39it/s]

 49%|████▉     | 2946/6015 [20:28<21:23,  2.39it/s]

 49%|████▉     | 2947/6015 [20:28<21:22,  2.39it/s]

 49%|████▉     | 2948/6015 [20:29<21:20,  2.40it/s]

 49%|████▉     | 2949/6015 [20:29<21:18,  2.40it/s]

 49%|████▉     | 2950/6015 [20:29<21:18,  2.40it/s]

 49%|████▉     | 2951/6015 [20:30<21:16,  2.40it/s]

 49%|████▉     | 2952/6015 [20:30<21:18,  2.40it/s]

 49%|████▉     | 2953/6015 [20:31<21:17,  2.40it/s]

 49%|████▉     | 2954/6015 [20:31<21:16,  2.40it/s]

 49%|████▉     | 2955/6015 [20:32<21:15,  2.40it/s]

 49%|████▉     | 2956/6015 [20:32<21:15,  2.40it/s]

 49%|████▉     | 2957/6015 [20:32<21:14,  2.40it/s]

 49%|████▉     | 2958/6015 [20:33<21:13,  2.40it/s]

 49%|████▉     | 2959/6015 [20:33<21:14,  2.40it/s]

 49%|████▉     | 2960/6015 [20:34<21:14,  2.40it/s]

 49%|████▉     | 2961/6015 [20:34<21:13,  2.40it/s]

 49%|████▉     | 2962/6015 [20:34<21:13,  2.40it/s]

 49%|████▉     | 2963/6015 [20:35<21:11,  2.40it/s]

 49%|████▉     | 2964/6015 [20:35<21:11,  2.40it/s]

 49%|████▉     | 2965/6015 [20:36<21:11,  2.40it/s]

 49%|████▉     | 2966/6015 [20:36<21:11,  2.40it/s]

 49%|████▉     | 2967/6015 [20:37<21:10,  2.40it/s]

 49%|████▉     | 2968/6015 [20:37<21:12,  2.40it/s]

 49%|████▉     | 2969/6015 [20:37<21:11,  2.40it/s]

 49%|████▉     | 2970/6015 [20:38<21:10,  2.40it/s]

 49%|████▉     | 2971/6015 [20:38<21:09,  2.40it/s]

 49%|████▉     | 2972/6015 [20:39<21:10,  2.40it/s]

 49%|████▉     | 2973/6015 [20:39<21:09,  2.40it/s]

 49%|████▉     | 2974/6015 [20:39<21:09,  2.40it/s]

 49%|████▉     | 2975/6015 [20:40<21:09,  2.40it/s]

 49%|████▉     | 2976/6015 [20:40<21:07,  2.40it/s]

 49%|████▉     | 2977/6015 [20:41<21:09,  2.39it/s]

 50%|████▉     | 2978/6015 [20:41<21:06,  2.40it/s]

 50%|████▉     | 2979/6015 [20:42<21:05,  2.40it/s]

 50%|████▉     | 2980/6015 [20:42<21:04,  2.40it/s]

 50%|████▉     | 2981/6015 [20:42<21:04,  2.40it/s]

 50%|████▉     | 2982/6015 [20:43<21:04,  2.40it/s]

 50%|████▉     | 2983/6015 [20:43<21:05,  2.40it/s]

 50%|████▉     | 2984/6015 [20:44<21:04,  2.40it/s]

 50%|████▉     | 2985/6015 [20:44<21:03,  2.40it/s]

 50%|████▉     | 2986/6015 [20:44<21:02,  2.40it/s]

 50%|████▉     | 2987/6015 [20:45<21:02,  2.40it/s]

 50%|████▉     | 2988/6015 [20:45<21:01,  2.40it/s]

 50%|████▉     | 2989/6015 [20:46<21:03,  2.40it/s]

 50%|████▉     | 2990/6015 [20:46<21:02,  2.40it/s]

 50%|████▉     | 2991/6015 [20:47<21:03,  2.39it/s]

 50%|████▉     | 2992/6015 [20:47<21:01,  2.40it/s]

 50%|████▉     | 2993/6015 [20:47<21:01,  2.39it/s]

 50%|████▉     | 2994/6015 [20:48<21:02,  2.39it/s]

 50%|████▉     | 2995/6015 [20:48<21:03,  2.39it/s]

 50%|████▉     | 2996/6015 [20:49<21:02,  2.39it/s]

 50%|████▉     | 2997/6015 [20:49<21:01,  2.39it/s]

 50%|████▉     | 2998/6015 [20:50<21:00,  2.39it/s]

 50%|████▉     | 2999/6015 [20:50<20:58,  2.40it/s]

 50%|████▉     | 3000/6015 [20:50<20:57,  2.40it/s]

 50%|████▉     | 3001/6015 [20:51<20:58,  2.40it/s]

 50%|████▉     | 3002/6015 [20:51<20:57,  2.40it/s]

 50%|████▉     | 3003/6015 [20:52<20:56,  2.40it/s]

 50%|████▉     | 3004/6015 [20:52<20:56,  2.40it/s]

 50%|████▉     | 3005/6015 [20:52<20:55,  2.40it/s]

 50%|████▉     | 3006/6015 [20:53<20:56,  2.39it/s]

 50%|████▉     | 3007/6015 [20:53<20:55,  2.39it/s]

 50%|█████     | 3008/6015 [20:54<20:53,  2.40it/s]

 50%|█████     | 3009/6015 [20:54<20:54,  2.40it/s]

 50%|█████     | 3010/6015 [20:55<20:54,  2.40it/s]

 50%|█████     | 3011/6015 [20:55<20:54,  2.39it/s]

 50%|█████     | 3012/6015 [20:55<20:53,  2.40it/s]

 50%|█████     | 3013/6015 [20:56<20:52,  2.40it/s]

 50%|█████     | 3014/6015 [20:56<20:52,  2.40it/s]

 50%|█████     | 3015/6015 [20:57<20:52,  2.40it/s]

 50%|█████     | 3016/6015 [20:57<20:53,  2.39it/s]

 50%|█████     | 3017/6015 [20:57<20:52,  2.39it/s]

 50%|█████     | 3018/6015 [20:58<20:55,  2.39it/s]

 50%|█████     | 3019/6015 [20:58<20:54,  2.39it/s]

 50%|█████     | 3020/6015 [20:59<20:53,  2.39it/s]

 50%|█████     | 3021/6015 [20:59<20:53,  2.39it/s]

 50%|█████     | 3022/6015 [21:00<20:51,  2.39it/s]

 50%|█████     | 3023/6015 [21:00<20:50,  2.39it/s]

 50%|█████     | 3024/6015 [21:00<20:48,  2.40it/s]

 50%|█████     | 3025/6015 [21:01<20:48,  2.40it/s]

 50%|█████     | 3026/6015 [21:01<20:49,  2.39it/s]

 50%|█████     | 3027/6015 [21:02<20:49,  2.39it/s]

 50%|█████     | 3028/6015 [21:02<20:49,  2.39it/s]

 50%|█████     | 3029/6015 [21:02<20:48,  2.39it/s]

 50%|█████     | 3030/6015 [21:03<20:48,  2.39it/s]

 50%|█████     | 3031/6015 [21:03<20:49,  2.39it/s]

 50%|█████     | 3032/6015 [21:04<20:49,  2.39it/s]

 50%|█████     | 3033/6015 [21:04<20:48,  2.39it/s]

 50%|█████     | 3034/6015 [21:05<20:48,  2.39it/s]

 50%|█████     | 3035/6015 [21:05<20:48,  2.39it/s]

 50%|█████     | 3036/6015 [21:05<20:46,  2.39it/s]

 50%|█████     | 3037/6015 [21:06<20:46,  2.39it/s]

 51%|█████     | 3038/6015 [21:06<20:46,  2.39it/s]

 51%|█████     | 3039/6015 [21:07<20:46,  2.39it/s]

 51%|█████     | 3040/6015 [21:07<20:45,  2.39it/s]

 51%|█████     | 3041/6015 [21:07<20:45,  2.39it/s]

 51%|█████     | 3042/6015 [21:08<20:45,  2.39it/s]

 51%|█████     | 3043/6015 [21:08<20:46,  2.38it/s]

 51%|█████     | 3044/6015 [21:09<20:43,  2.39it/s]

 51%|█████     | 3045/6015 [21:09<20:43,  2.39it/s]

 51%|█████     | 3046/6015 [21:10<20:42,  2.39it/s]

 51%|█████     | 3047/6015 [21:10<20:42,  2.39it/s]

 51%|█████     | 3048/6015 [21:10<20:42,  2.39it/s]

 51%|█████     | 3049/6015 [21:11<20:45,  2.38it/s]

 51%|█████     | 3050/6015 [21:11<20:44,  2.38it/s]

 51%|█████     | 3051/6015 [21:12<20:43,  2.38it/s]

 51%|█████     | 3052/6015 [21:12<20:40,  2.39it/s]

 51%|█████     | 3053/6015 [21:13<20:41,  2.39it/s]

 51%|█████     | 3054/6015 [21:13<20:41,  2.39it/s]

 51%|█████     | 3055/6015 [21:13<20:41,  2.38it/s]

 51%|█████     | 3056/6015 [21:14<20:39,  2.39it/s]

 51%|█████     | 3057/6015 [21:14<20:41,  2.38it/s]

 51%|█████     | 3058/6015 [21:15<20:39,  2.39it/s]

 51%|█████     | 3059/6015 [21:15<20:39,  2.39it/s]

 51%|█████     | 3060/6015 [21:15<20:37,  2.39it/s]

 51%|█████     | 3061/6015 [21:16<20:39,  2.38it/s]

 51%|█████     | 3062/6015 [21:16<20:37,  2.39it/s]

 51%|█████     | 3063/6015 [21:17<20:37,  2.39it/s]

 51%|█████     | 3064/6015 [21:17<20:37,  2.39it/s]

 51%|█████     | 3065/6015 [21:18<20:37,  2.38it/s]

 51%|█████     | 3066/6015 [21:18<20:35,  2.39it/s]

 51%|█████     | 3067/6015 [21:18<20:34,  2.39it/s]

 51%|█████     | 3068/6015 [21:19<20:33,  2.39it/s]

 51%|█████     | 3069/6015 [21:19<20:34,  2.39it/s]

 51%|█████     | 3070/6015 [21:20<20:34,  2.39it/s]

 51%|█████     | 3071/6015 [21:20<20:36,  2.38it/s]

 51%|█████     | 3072/6015 [21:20<20:33,  2.39it/s]

 51%|█████     | 3073/6015 [21:21<20:34,  2.38it/s]

 51%|█████     | 3074/6015 [21:21<20:33,  2.38it/s]

 51%|█████     | 3075/6015 [21:22<20:34,  2.38it/s]

 51%|█████     | 3076/6015 [21:22<20:32,  2.39it/s]

 51%|█████     | 3077/6015 [21:23<20:32,  2.38it/s]

 51%|█████     | 3078/6015 [21:23<20:31,  2.39it/s]

 51%|█████     | 3079/6015 [21:23<20:31,  2.38it/s]

 51%|█████     | 3080/6015 [21:24<20:30,  2.39it/s]

 51%|█████     | 3081/6015 [21:24<20:29,  2.39it/s]

 51%|█████     | 3082/6015 [21:25<20:26,  2.39it/s]

 51%|█████▏    | 3083/6015 [21:25<20:27,  2.39it/s]

 51%|█████▏    | 3084/6015 [21:26<20:27,  2.39it/s]

 51%|█████▏    | 3085/6015 [21:26<20:27,  2.39it/s]

 51%|█████▏    | 3086/6015 [21:26<20:26,  2.39it/s]

 51%|█████▏    | 3087/6015 [21:27<20:24,  2.39it/s]

 51%|█████▏    | 3088/6015 [21:27<20:22,  2.39it/s]

 51%|█████▏    | 3089/6015 [21:28<20:23,  2.39it/s]

 51%|█████▏    | 3090/6015 [21:28<20:23,  2.39it/s]

 51%|█████▏    | 3091/6015 [21:28<20:23,  2.39it/s]

 51%|█████▏    | 3092/6015 [21:29<20:23,  2.39it/s]

 51%|█████▏    | 3093/6015 [21:29<20:24,  2.39it/s]

 51%|█████▏    | 3094/6015 [21:30<20:23,  2.39it/s]

 51%|█████▏    | 3095/6015 [21:30<20:22,  2.39it/s]

 51%|█████▏    | 3096/6015 [21:31<20:20,  2.39it/s]

 51%|█████▏    | 3097/6015 [21:31<20:22,  2.39it/s]

 52%|█████▏    | 3098/6015 [21:31<20:21,  2.39it/s]

 52%|█████▏    | 3099/6015 [21:32<20:21,  2.39it/s]

 52%|█████▏    | 3100/6015 [21:32<20:19,  2.39it/s]

 52%|█████▏    | 3101/6015 [21:33<20:22,  2.38it/s]

 52%|█████▏    | 3102/6015 [21:33<20:20,  2.39it/s]

 52%|█████▏    | 3103/6015 [21:33<20:20,  2.39it/s]

 52%|█████▏    | 3104/6015 [21:34<20:18,  2.39it/s]

 52%|█████▏    | 3105/6015 [21:34<20:20,  2.38it/s]

 52%|█████▏    | 3106/6015 [21:35<20:19,  2.39it/s]

 52%|█████▏    | 3107/6015 [21:35<20:19,  2.38it/s]

 52%|█████▏    | 3108/6015 [21:36<20:19,  2.38it/s]

 52%|█████▏    | 3109/6015 [21:36<20:21,  2.38it/s]

 52%|█████▏    | 3110/6015 [21:36<20:19,  2.38it/s]

 52%|█████▏    | 3111/6015 [21:37<20:19,  2.38it/s]

 52%|█████▏    | 3112/6015 [21:37<20:17,  2.38it/s]

 52%|█████▏    | 3113/6015 [21:38<20:17,  2.38it/s]

 52%|█████▏    | 3114/6015 [21:38<20:16,  2.38it/s]

 52%|█████▏    | 3115/6015 [21:38<20:15,  2.39it/s]

 52%|█████▏    | 3116/6015 [21:39<20:16,  2.38it/s]

 52%|█████▏    | 3117/6015 [21:39<20:15,  2.38it/s]

 52%|█████▏    | 3118/6015 [21:40<20:16,  2.38it/s]

 52%|█████▏    | 3119/6015 [21:40<20:16,  2.38it/s]

 52%|█████▏    | 3120/6015 [21:41<20:15,  2.38it/s]

 52%|█████▏    | 3121/6015 [21:41<20:16,  2.38it/s]

 52%|█████▏    | 3122/6015 [21:41<20:14,  2.38it/s]

 52%|█████▏    | 3123/6015 [21:42<20:14,  2.38it/s]

 52%|█████▏    | 3124/6015 [21:42<20:12,  2.38it/s]

 52%|█████▏    | 3125/6015 [21:43<20:12,  2.38it/s]

 52%|█████▏    | 3126/6015 [21:43<20:10,  2.39it/s]

 52%|█████▏    | 3127/6015 [21:44<20:11,  2.38it/s]

 52%|█████▏    | 3128/6015 [21:44<20:10,  2.39it/s]

 52%|█████▏    | 3129/6015 [21:44<20:10,  2.38it/s]

logging
logging the anndata

 52%|█████▏    | 3130/6015 [21:45<20:45,  2.32it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 52%|█████▏    | 3131/6015 [21:45<20:27,  2.35it/s]

 52%|█████▏    | 3132/6015 [21:46<20:14,  2.37it/s]

 52%|█████▏    | 3133/6015 [21:46<20:05,  2.39it/s]

 52%|█████▏    | 3134/6015 [21:46<19:57,  2.41it/s]

 52%|█████▏    | 3135/6015 [21:47<19:53,  2.41it/s]

 52%|█████▏    | 3136/6015 [21:47<19:50,  2.42it/s]

 52%|█████▏    | 3137/6015 [21:48<19:48,  2.42it/s]

 52%|█████▏    | 3138/6015 [21:48<19:45,  2.43it/s]

 52%|█████▏    | 3139/6015 [21:49<19:45,  2.43it/s]

 52%|█████▏    | 3140/6015 [21:49<19:43,  2.43it/s]

 52%|█████▏    | 3141/6015 [21:49<19:42,  2.43it/s]

 52%|█████▏    | 3142/6015 [21:50<19:45,  2.42it/s]

 52%|█████▏    | 3143/6015 [21:50<19:46,  2.42it/s]

 52%|█████▏    | 3144/6015 [21:51<19:43,  2.43it/s]

 52%|█████▏    | 3145/6015 [21:51<19:43,  2.42it/s]

 52%|█████▏    | 3146/6015 [21:51<19:42,  2.43it/s]

 52%|█████▏    | 3147/6015 [21:52<19:40,  2.43it/s]

 52%|█████▏    | 3148/6015 [21:52<19:40,  2.43it/s]

 52%|█████▏    | 3149/6015 [21:53<19:39,  2.43it/s]

 52%|█████▏    | 3150/6015 [21:53<19:40,  2.43it/s]

 52%|█████▏    | 3151/6015 [21:53<19:40,  2.43it/s]

 52%|█████▏    | 3152/6015 [21:54<19:40,  2.43it/s]

 52%|█████▏    | 3153/6015 [21:54<19:39,  2.43it/s]

 52%|█████▏    | 3154/6015 [21:55<19:39,  2.43it/s]

 52%|█████▏    | 3155/6015 [21:55<19:39,  2.43it/s]

 52%|█████▏    | 3156/6015 [21:56<19:39,  2.42it/s]

 52%|█████▏    | 3157/6015 [21:56<19:39,  2.42it/s]

 53%|█████▎    | 3158/6015 [21:56<19:37,  2.43it/s]

 53%|█████▎    | 3159/6015 [21:57<19:38,  2.42it/s]

 53%|█████▎    | 3160/6015 [21:57<19:38,  2.42it/s]

 53%|█████▎    | 3161/6015 [21:58<19:40,  2.42it/s]

 53%|█████▎    | 3162/6015 [21:58<19:38,  2.42it/s]

 53%|█████▎    | 3163/6015 [21:58<19:38,  2.42it/s]

 53%|█████▎    | 3164/6015 [21:59<19:36,  2.42it/s]

 53%|█████▎    | 3165/6015 [21:59<19:36,  2.42it/s]

 53%|█████▎    | 3166/6015 [22:00<19:34,  2.43it/s]

 53%|█████▎    | 3167/6015 [22:00<19:33,  2.43it/s]

 53%|█████▎    | 3168/6015 [22:00<19:35,  2.42it/s]

 53%|█████▎    | 3169/6015 [22:01<19:33,  2.43it/s]

 53%|█████▎    | 3170/6015 [22:01<19:32,  2.43it/s]

 53%|█████▎    | 3171/6015 [22:02<19:31,  2.43it/s]

 53%|█████▎    | 3172/6015 [22:02<19:30,  2.43it/s]

 53%|█████▎    | 3173/6015 [22:03<19:30,  2.43it/s]

 53%|█████▎    | 3174/6015 [22:03<19:30,  2.43it/s]

 53%|█████▎    | 3175/6015 [22:03<19:28,  2.43it/s]

 53%|█████▎    | 3176/6015 [22:04<19:28,  2.43it/s]

 53%|█████▎    | 3177/6015 [22:04<19:27,  2.43it/s]

 53%|█████▎    | 3178/6015 [22:05<19:28,  2.43it/s]

 53%|█████▎    | 3179/6015 [22:05<19:29,  2.42it/s]

 53%|█████▎    | 3180/6015 [22:05<19:29,  2.42it/s]

 53%|█████▎    | 3181/6015 [22:06<19:29,  2.42it/s]

 53%|█████▎    | 3182/6015 [22:06<19:28,  2.42it/s]

 53%|█████▎    | 3183/6015 [22:07<19:28,  2.42it/s]

 53%|█████▎    | 3184/6015 [22:07<19:27,  2.43it/s]

 53%|█████▎    | 3185/6015 [22:08<19:26,  2.43it/s]

 53%|█████▎    | 3186/6015 [22:08<19:25,  2.43it/s]

 53%|█████▎    | 3187/6015 [22:08<19:25,  2.43it/s]

 53%|█████▎    | 3188/6015 [22:09<19:25,  2.43it/s]

 53%|█████▎    | 3189/6015 [22:09<19:24,  2.43it/s]

 53%|█████▎    | 3190/6015 [22:10<19:24,  2.43it/s]

 53%|█████▎    | 3191/6015 [22:10<19:26,  2.42it/s]

 53%|█████▎    | 3192/6015 [22:10<19:28,  2.42it/s]

 53%|█████▎    | 3193/6015 [22:11<19:25,  2.42it/s]

 53%|█████▎    | 3194/6015 [22:11<19:24,  2.42it/s]

 53%|█████▎    | 3195/6015 [22:12<19:23,  2.42it/s]

 53%|█████▎    | 3196/6015 [22:12<19:23,  2.42it/s]

 53%|█████▎    | 3197/6015 [22:12<19:22,  2.42it/s]

 53%|█████▎    | 3198/6015 [22:13<19:21,  2.42it/s]

 53%|█████▎    | 3199/6015 [22:13<19:23,  2.42it/s]

 53%|█████▎    | 3200/6015 [22:14<19:22,  2.42it/s]

 53%|█████▎    | 3201/6015 [22:14<19:21,  2.42it/s]

 53%|█████▎    | 3202/6015 [22:15<19:20,  2.42it/s]

 53%|█████▎    | 3203/6015 [22:15<19:22,  2.42it/s]

 53%|█████▎    | 3204/6015 [22:15<19:20,  2.42it/s]

 53%|█████▎    | 3205/6015 [22:16<19:19,  2.42it/s]

 53%|█████▎    | 3206/6015 [22:16<19:20,  2.42it/s]

 53%|█████▎    | 3207/6015 [22:17<19:20,  2.42it/s]

 53%|█████▎    | 3208/6015 [22:17<19:19,  2.42it/s]

 53%|█████▎    | 3209/6015 [22:17<19:19,  2.42it/s]

 53%|█████▎    | 3210/6015 [22:18<19:18,  2.42it/s]

 53%|█████▎    | 3211/6015 [22:18<19:18,  2.42it/s]

 53%|█████▎    | 3212/6015 [22:19<19:18,  2.42it/s]

 53%|█████▎    | 3213/6015 [22:19<19:16,  2.42it/s]

 53%|█████▎    | 3214/6015 [22:19<19:15,  2.42it/s]

 53%|█████▎    | 3215/6015 [22:20<19:15,  2.42it/s]

 53%|█████▎    | 3216/6015 [22:20<19:15,  2.42it/s]

 53%|█████▎    | 3217/6015 [22:21<19:15,  2.42it/s]

 53%|█████▎    | 3218/6015 [22:21<19:16,  2.42it/s]

 54%|█████▎    | 3219/6015 [22:22<19:18,  2.41it/s]

 54%|█████▎    | 3220/6015 [22:22<19:16,  2.42it/s]

 54%|█████▎    | 3221/6015 [22:22<19:16,  2.42it/s]

 54%|█████▎    | 3222/6015 [22:23<19:15,  2.42it/s]

 54%|█████▎    | 3223/6015 [22:23<19:15,  2.42it/s]

 54%|█████▎    | 3224/6015 [22:24<19:14,  2.42it/s]

 54%|█████▎    | 3225/6015 [22:24<19:13,  2.42it/s]

 54%|█████▎    | 3226/6015 [22:24<19:13,  2.42it/s]

 54%|█████▎    | 3227/6015 [22:25<19:13,  2.42it/s]

 54%|█████▎    | 3228/6015 [22:25<19:15,  2.41it/s]

 54%|█████▎    | 3229/6015 [22:26<19:14,  2.41it/s]

 54%|█████▎    | 3230/6015 [22:26<19:13,  2.41it/s]

 54%|█████▎    | 3231/6015 [22:27<19:10,  2.42it/s]

 54%|█████▎    | 3232/6015 [22:27<19:09,  2.42it/s]

 54%|█████▎    | 3233/6015 [22:27<19:08,  2.42it/s]

 54%|█████▍    | 3234/6015 [22:28<19:07,  2.42it/s]

 54%|█████▍    | 3235/6015 [22:28<19:07,  2.42it/s]

 54%|█████▍    | 3236/6015 [22:29<19:08,  2.42it/s]

 54%|█████▍    | 3237/6015 [22:29<19:07,  2.42it/s]

 54%|█████▍    | 3238/6015 [22:29<19:07,  2.42it/s]

 54%|█████▍    | 3239/6015 [22:30<19:08,  2.42it/s]

 54%|█████▍    | 3240/6015 [22:30<19:07,  2.42it/s]

 54%|█████▍    | 3241/6015 [22:31<19:06,  2.42it/s]

 54%|█████▍    | 3242/6015 [22:31<19:06,  2.42it/s]

 54%|█████▍    | 3243/6015 [22:31<19:06,  2.42it/s]

 54%|█████▍    | 3244/6015 [22:32<19:06,  2.42it/s]

 54%|█████▍    | 3245/6015 [22:32<19:06,  2.42it/s]

 54%|█████▍    | 3246/6015 [22:33<19:05,  2.42it/s]

 54%|█████▍    | 3247/6015 [22:33<19:04,  2.42it/s]

 54%|█████▍    | 3248/6015 [22:34<19:03,  2.42it/s]

 54%|█████▍    | 3249/6015 [22:34<19:03,  2.42it/s]

 54%|█████▍    | 3250/6015 [22:34<19:01,  2.42it/s]

 54%|█████▍    | 3251/6015 [22:35<19:01,  2.42it/s]

 54%|█████▍    | 3252/6015 [22:35<18:59,  2.42it/s]

 54%|█████▍    | 3253/6015 [22:36<19:00,  2.42it/s]

 54%|█████▍    | 3254/6015 [22:36<19:01,  2.42it/s]

 54%|█████▍    | 3255/6015 [22:36<19:01,  2.42it/s]

 54%|█████▍    | 3256/6015 [22:37<19:03,  2.41it/s]

 54%|█████▍    | 3257/6015 [22:37<19:01,  2.42it/s]

 54%|█████▍    | 3258/6015 [22:38<19:00,  2.42it/s]

 54%|█████▍    | 3259/6015 [22:38<19:00,  2.42it/s]

 54%|█████▍    | 3260/6015 [22:38<18:59,  2.42it/s]

 54%|█████▍    | 3261/6015 [22:39<19:01,  2.41it/s]

 54%|█████▍    | 3262/6015 [22:39<19:00,  2.41it/s]

 54%|█████▍    | 3263/6015 [22:40<18:59,  2.42it/s]

 54%|█████▍    | 3264/6015 [22:40<18:58,  2.42it/s]

 54%|█████▍    | 3265/6015 [22:41<18:56,  2.42it/s]

 54%|█████▍    | 3266/6015 [22:41<18:56,  2.42it/s]

 54%|█████▍    | 3267/6015 [22:41<18:55,  2.42it/s]

 54%|█████▍    | 3268/6015 [22:42<18:55,  2.42it/s]

 54%|█████▍    | 3269/6015 [22:42<18:55,  2.42it/s]

 54%|█████▍    | 3270/6015 [22:43<18:56,  2.42it/s]

 54%|█████▍    | 3271/6015 [22:43<18:56,  2.41it/s]

 54%|█████▍    | 3272/6015 [22:43<18:54,  2.42it/s]

 54%|█████▍    | 3273/6015 [22:44<18:53,  2.42it/s]

 54%|█████▍    | 3274/6015 [22:44<18:51,  2.42it/s]

 54%|█████▍    | 3275/6015 [22:45<18:52,  2.42it/s]

 54%|█████▍    | 3276/6015 [22:45<18:53,  2.42it/s]

 54%|█████▍    | 3277/6015 [22:46<18:53,  2.41it/s]

 54%|█████▍    | 3278/6015 [22:46<18:53,  2.41it/s]

 55%|█████▍    | 3279/6015 [22:46<18:54,  2.41it/s]

 55%|█████▍    | 3280/6015 [22:47<18:52,  2.41it/s]

 55%|█████▍    | 3281/6015 [22:47<18:52,  2.41it/s]

 55%|█████▍    | 3282/6015 [22:48<18:51,  2.42it/s]

 55%|█████▍    | 3283/6015 [22:48<18:50,  2.42it/s]

 55%|█████▍    | 3284/6015 [22:48<18:50,  2.42it/s]

 55%|█████▍    | 3285/6015 [22:49<18:50,  2.41it/s]

 55%|█████▍    | 3286/6015 [22:49<18:49,  2.42it/s]

 55%|█████▍    | 3287/6015 [22:50<18:47,  2.42it/s]

 55%|█████▍    | 3288/6015 [22:50<18:47,  2.42it/s]

 55%|█████▍    | 3289/6015 [22:50<18:46,  2.42it/s]

 55%|█████▍    | 3290/6015 [22:51<18:46,  2.42it/s]

 55%|█████▍    | 3291/6015 [22:51<18:47,  2.42it/s]

 55%|█████▍    | 3292/6015 [22:52<18:48,  2.41it/s]

 55%|█████▍    | 3293/6015 [22:52<18:47,  2.41it/s]

 55%|█████▍    | 3294/6015 [22:53<18:45,  2.42it/s]

 55%|█████▍    | 3295/6015 [22:53<18:44,  2.42it/s]

 55%|█████▍    | 3296/6015 [22:53<18:43,  2.42it/s]

 55%|█████▍    | 3297/6015 [22:54<18:42,  2.42it/s]

 55%|█████▍    | 3298/6015 [22:54<18:42,  2.42it/s]

 55%|█████▍    | 3299/6015 [22:55<18:42,  2.42it/s]

 55%|█████▍    | 3300/6015 [22:55<18:41,  2.42it/s]

 55%|█████▍    | 3301/6015 [22:55<18:42,  2.42it/s]

 55%|█████▍    | 3302/6015 [22:56<18:41,  2.42it/s]

 55%|█████▍    | 3303/6015 [22:56<18:40,  2.42it/s]

 55%|█████▍    | 3304/6015 [22:57<18:40,  2.42it/s]

 55%|█████▍    | 3305/6015 [22:57<18:40,  2.42it/s]

 55%|█████▍    | 3306/6015 [22:58<18:39,  2.42it/s]

 55%|█████▍    | 3307/6015 [22:58<18:41,  2.42it/s]

 55%|█████▍    | 3308/6015 [22:58<18:39,  2.42it/s]

 55%|█████▌    | 3309/6015 [22:59<18:41,  2.41it/s]

 55%|█████▌    | 3310/6015 [22:59<18:40,  2.41it/s]

 55%|█████▌    | 3311/6015 [23:00<18:41,  2.41it/s]

 55%|█████▌    | 3312/6015 [23:00<18:40,  2.41it/s]

 55%|█████▌    | 3313/6015 [23:00<18:39,  2.41it/s]

 55%|█████▌    | 3314/6015 [23:01<18:38,  2.42it/s]

 55%|█████▌    | 3315/6015 [23:01<18:37,  2.42it/s]

 55%|█████▌    | 3316/6015 [23:02<18:36,  2.42it/s]

 55%|█████▌    | 3317/6015 [23:02<18:36,  2.42it/s]

 55%|█████▌    | 3318/6015 [23:02<18:39,  2.41it/s]

 55%|█████▌    | 3319/6015 [23:03<18:37,  2.41it/s]

 55%|█████▌    | 3320/6015 [23:03<18:36,  2.41it/s]

 55%|█████▌    | 3321/6015 [23:04<18:34,  2.42it/s]

 55%|█████▌    | 3322/6015 [23:04<18:35,  2.42it/s]

 55%|█████▌    | 3323/6015 [23:05<18:33,  2.42it/s]

 55%|█████▌    | 3324/6015 [23:05<18:33,  2.42it/s]

 55%|█████▌    | 3325/6015 [23:05<18:32,  2.42it/s]

 55%|█████▌    | 3326/6015 [23:06<18:34,  2.41it/s]

 55%|█████▌    | 3327/6015 [23:06<18:34,  2.41it/s]

 55%|█████▌    | 3328/6015 [23:07<18:34,  2.41it/s]

 55%|█████▌    | 3329/6015 [23:07<18:33,  2.41it/s]

 55%|█████▌    | 3330/6015 [23:07<18:33,  2.41it/s]

 55%|█████▌    | 3331/6015 [23:08<18:33,  2.41it/s]

 55%|█████▌    | 3332/6015 [23:08<18:32,  2.41it/s]

 55%|█████▌    | 3333/6015 [23:09<18:32,  2.41it/s]

 55%|█████▌    | 3334/6015 [23:09<18:30,  2.41it/s]

 55%|█████▌    | 3335/6015 [23:10<18:29,  2.42it/s]

 55%|█████▌    | 3336/6015 [23:10<18:28,  2.42it/s]

 55%|█████▌    | 3337/6015 [23:10<18:27,  2.42it/s]

 55%|█████▌    | 3338/6015 [23:11<18:27,  2.42it/s]

 56%|█████▌    | 3339/6015 [23:11<18:28,  2.41it/s]

 56%|█████▌    | 3340/6015 [23:12<18:27,  2.42it/s]

 56%|█████▌    | 3341/6015 [23:12<18:27,  2.41it/s]

 56%|█████▌    | 3342/6015 [23:12<18:26,  2.42it/s]

 56%|█████▌    | 3343/6015 [23:13<18:26,  2.41it/s]

 56%|█████▌    | 3344/6015 [23:13<18:26,  2.41it/s]

 56%|█████▌    | 3345/6015 [23:14<18:26,  2.41it/s]

 56%|█████▌    | 3346/6015 [23:14<18:26,  2.41it/s]

 56%|█████▌    | 3347/6015 [23:15<18:25,  2.41it/s]

 56%|█████▌    | 3348/6015 [23:15<18:25,  2.41it/s]

 56%|█████▌    | 3349/6015 [23:15<18:25,  2.41it/s]

 56%|█████▌    | 3350/6015 [23:16<18:25,  2.41it/s]

 56%|█████▌    | 3351/6015 [23:16<18:24,  2.41it/s]

 56%|█████▌    | 3352/6015 [23:17<18:23,  2.41it/s]

 56%|█████▌    | 3353/6015 [23:17<18:24,  2.41it/s]

 56%|█████▌    | 3354/6015 [23:17<18:23,  2.41it/s]

 56%|█████▌    | 3355/6015 [23:18<18:23,  2.41it/s]

 56%|█████▌    | 3356/6015 [23:18<18:21,  2.41it/s]

 56%|█████▌    | 3357/6015 [23:19<18:21,  2.41it/s]

 56%|█████▌    | 3358/6015 [23:19<18:20,  2.41it/s]

 56%|█████▌    | 3359/6015 [23:19<18:21,  2.41it/s]

 56%|█████▌    | 3360/6015 [23:20<18:20,  2.41it/s]

 56%|█████▌    | 3361/6015 [23:20<18:19,  2.41it/s]

 56%|█████▌    | 3362/6015 [23:21<18:20,  2.41it/s]

 56%|█████▌    | 3363/6015 [23:21<18:19,  2.41it/s]

 56%|█████▌    | 3364/6015 [23:22<18:19,  2.41it/s]

 56%|█████▌    | 3365/6015 [23:22<18:19,  2.41it/s]

 56%|█████▌    | 3366/6015 [23:22<18:20,  2.41it/s]

 56%|█████▌    | 3367/6015 [23:23<18:18,  2.41it/s]

 56%|█████▌    | 3368/6015 [23:23<18:19,  2.41it/s]

 56%|█████▌    | 3369/6015 [23:24<18:18,  2.41it/s]

 56%|█████▌    | 3370/6015 [23:24<18:16,  2.41it/s]

 56%|█████▌    | 3371/6015 [23:24<18:15,  2.41it/s]

 56%|█████▌    | 3372/6015 [23:25<18:15,  2.41it/s]

 56%|█████▌    | 3373/6015 [23:25<18:14,  2.41it/s]

 56%|█████▌    | 3374/6015 [23:26<18:15,  2.41it/s]

 56%|█████▌    | 3375/6015 [23:26<18:14,  2.41it/s]

 56%|█████▌    | 3376/6015 [23:27<18:15,  2.41it/s]

 56%|█████▌    | 3377/6015 [23:27<18:13,  2.41it/s]

 56%|█████▌    | 3378/6015 [23:27<18:13,  2.41it/s]

 56%|█████▌    | 3379/6015 [23:28<18:13,  2.41it/s]

 56%|█████▌    | 3380/6015 [23:28<18:12,  2.41it/s]

 56%|█████▌    | 3381/6015 [23:29<18:11,  2.41it/s]

 56%|█████▌    | 3382/6015 [23:29<18:12,  2.41it/s]

 56%|█████▌    | 3383/6015 [23:29<18:10,  2.41it/s]

 56%|█████▋    | 3384/6015 [23:30<18:11,  2.41it/s]

 56%|█████▋    | 3385/6015 [23:30<18:12,  2.41it/s]

 56%|█████▋    | 3386/6015 [23:31<18:10,  2.41it/s]

 56%|█████▋    | 3387/6015 [23:31<18:09,  2.41it/s]

 56%|█████▋    | 3388/6015 [23:32<18:10,  2.41it/s]

 56%|█████▋    | 3389/6015 [23:32<18:09,  2.41it/s]

 56%|█████▋    | 3390/6015 [23:32<18:09,  2.41it/s]

 56%|█████▋    | 3391/6015 [23:33<18:08,  2.41it/s]

 56%|█████▋    | 3392/6015 [23:33<18:08,  2.41it/s]

 56%|█████▋    | 3393/6015 [23:34<18:10,  2.40it/s]

 56%|█████▋    | 3394/6015 [23:34<18:10,  2.40it/s]

 56%|█████▋    | 3395/6015 [23:34<18:10,  2.40it/s]

 56%|█████▋    | 3396/6015 [23:35<18:07,  2.41it/s]

 56%|█████▋    | 3397/6015 [23:35<18:07,  2.41it/s]

 56%|█████▋    | 3398/6015 [23:36<18:05,  2.41it/s]

 57%|█████▋    | 3399/6015 [23:36<18:04,  2.41it/s]

 57%|█████▋    | 3400/6015 [23:36<18:04,  2.41it/s]

 57%|█████▋    | 3401/6015 [23:37<18:03,  2.41it/s]

 57%|█████▋    | 3402/6015 [23:37<18:03,  2.41it/s]

 57%|█████▋    | 3403/6015 [23:38<18:02,  2.41it/s]

 57%|█████▋    | 3404/6015 [23:38<18:01,  2.41it/s]

 57%|█████▋    | 3405/6015 [23:39<18:01,  2.41it/s]

 57%|█████▋    | 3406/6015 [23:39<18:00,  2.41it/s]

 57%|█████▋    | 3407/6015 [23:39<18:00,  2.41it/s]

 57%|█████▋    | 3408/6015 [23:40<18:02,  2.41it/s]

 57%|█████▋    | 3409/6015 [23:40<18:03,  2.40it/s]

 57%|█████▋    | 3410/6015 [23:41<18:02,  2.41it/s]

 57%|█████▋    | 3411/6015 [23:41<18:01,  2.41it/s]

 57%|█████▋    | 3412/6015 [23:41<18:01,  2.41it/s]

 57%|█████▋    | 3413/6015 [23:42<17:59,  2.41it/s]

 57%|█████▋    | 3414/6015 [23:42<18:00,  2.41it/s]

 57%|█████▋    | 3415/6015 [23:43<17:59,  2.41it/s]

 57%|█████▋    | 3416/6015 [23:43<17:59,  2.41it/s]

 57%|█████▋    | 3417/6015 [23:44<17:57,  2.41it/s]

 57%|█████▋    | 3418/6015 [23:44<17:57,  2.41it/s]

 57%|█████▋    | 3419/6015 [23:44<17:57,  2.41it/s]

 57%|█████▋    | 3420/6015 [23:45<17:56,  2.41it/s]

 57%|█████▋    | 3421/6015 [23:45<17:56,  2.41it/s]

 57%|█████▋    | 3422/6015 [23:46<17:57,  2.41it/s]

 57%|█████▋    | 3423/6015 [23:46<17:57,  2.41it/s]

 57%|█████▋    | 3424/6015 [23:46<17:56,  2.41it/s]

 57%|█████▋    | 3425/6015 [23:47<17:55,  2.41it/s]

 57%|█████▋    | 3426/6015 [23:47<17:54,  2.41it/s]

 57%|█████▋    | 3427/6015 [23:48<17:55,  2.41it/s]

 57%|█████▋    | 3428/6015 [23:48<17:54,  2.41it/s]

 57%|█████▋    | 3429/6015 [23:49<17:54,  2.41it/s]

 57%|█████▋    | 3430/6015 [23:49<17:54,  2.41it/s]

 57%|█████▋    | 3431/6015 [23:49<17:53,  2.41it/s]

 57%|█████▋    | 3432/6015 [23:50<17:52,  2.41it/s]

 57%|█████▋    | 3433/6015 [23:50<17:52,  2.41it/s]

 57%|█████▋    | 3434/6015 [23:51<17:52,  2.41it/s]

 57%|█████▋    | 3435/6015 [23:51<17:53,  2.40it/s]

 57%|█████▋    | 3436/6015 [23:51<17:53,  2.40it/s]

 57%|█████▋    | 3437/6015 [23:52<17:55,  2.40it/s]

 57%|█████▋    | 3438/6015 [23:52<17:53,  2.40it/s]

 57%|█████▋    | 3439/6015 [23:53<17:52,  2.40it/s]

 57%|█████▋    | 3440/6015 [23:53<17:51,  2.40it/s]

 57%|█████▋    | 3441/6015 [23:54<17:50,  2.40it/s]

 57%|█████▋    | 3442/6015 [23:54<17:49,  2.41it/s]

 57%|█████▋    | 3443/6015 [23:54<17:48,  2.41it/s]

 57%|█████▋    | 3444/6015 [23:55<17:47,  2.41it/s]

 57%|█████▋    | 3445/6015 [23:55<17:48,  2.40it/s]

 57%|█████▋    | 3446/6015 [23:56<17:47,  2.41it/s]

 57%|█████▋    | 3447/6015 [23:56<17:47,  2.41it/s]

 57%|█████▋    | 3448/6015 [23:56<17:47,  2.41it/s]

 57%|█████▋    | 3449/6015 [23:57<17:48,  2.40it/s]

 57%|█████▋    | 3450/6015 [23:57<17:47,  2.40it/s]

 57%|█████▋    | 3451/6015 [23:58<17:46,  2.40it/s]

 57%|█████▋    | 3452/6015 [23:58<17:47,  2.40it/s]

 57%|█████▋    | 3453/6015 [23:59<17:46,  2.40it/s]

 57%|█████▋    | 3454/6015 [23:59<17:45,  2.40it/s]

 57%|█████▋    | 3455/6015 [23:59<17:45,  2.40it/s]

 57%|█████▋    | 3456/6015 [24:00<17:44,  2.40it/s]

 57%|█████▋    | 3457/6015 [24:00<17:43,  2.40it/s]

 57%|█████▋    | 3458/6015 [24:01<17:43,  2.40it/s]

 58%|█████▊    | 3459/6015 [24:01<17:43,  2.40it/s]

 58%|█████▊    | 3460/6015 [24:01<17:47,  2.39it/s]

 58%|█████▊    | 3461/6015 [24:02<17:46,  2.40it/s]

 58%|█████▊    | 3462/6015 [24:02<17:45,  2.40it/s]

 58%|█████▊    | 3463/6015 [24:03<17:43,  2.40it/s]

 58%|█████▊    | 3464/6015 [24:03<17:42,  2.40it/s]

 58%|█████▊    | 3465/6015 [24:04<17:40,  2.40it/s]

 58%|█████▊    | 3466/6015 [24:04<17:39,  2.41it/s]

 58%|█████▊    | 3467/6015 [24:04<17:38,  2.41it/s]

 58%|█████▊    | 3468/6015 [24:05<17:38,  2.41it/s]

 58%|█████▊    | 3469/6015 [24:05<17:38,  2.41it/s]

 58%|█████▊    | 3470/6015 [24:06<17:39,  2.40it/s]

 58%|█████▊    | 3471/6015 [24:06<17:38,  2.40it/s]

 58%|█████▊    | 3472/6015 [24:06<17:38,  2.40it/s]

 58%|█████▊    | 3473/6015 [24:07<17:37,  2.40it/s]

 58%|█████▊    | 3474/6015 [24:07<17:37,  2.40it/s]

 58%|█████▊    | 3475/6015 [24:08<17:36,  2.40it/s]

 58%|█████▊    | 3476/6015 [24:08<17:35,  2.40it/s]

 58%|█████▊    | 3477/6015 [24:09<17:36,  2.40it/s]

 58%|█████▊    | 3478/6015 [24:09<17:36,  2.40it/s]

 58%|█████▊    | 3479/6015 [24:09<17:35,  2.40it/s]

 58%|█████▊    | 3480/6015 [24:10<17:34,  2.40it/s]

 58%|█████▊    | 3481/6015 [24:10<17:34,  2.40it/s]

 58%|█████▊    | 3482/6015 [24:11<17:33,  2.40it/s]

 58%|█████▊    | 3483/6015 [24:11<17:33,  2.40it/s]

 58%|█████▊    | 3484/6015 [24:11<17:36,  2.39it/s]

 58%|█████▊    | 3485/6015 [24:12<17:34,  2.40it/s]

 58%|█████▊    | 3486/6015 [24:12<17:32,  2.40it/s]

 58%|█████▊    | 3487/6015 [24:13<17:34,  2.40it/s]

 58%|█████▊    | 3488/6015 [24:13<17:32,  2.40it/s]

 58%|█████▊    | 3489/6015 [24:14<17:31,  2.40it/s]

 58%|█████▊    | 3490/6015 [24:14<17:30,  2.40it/s]

 58%|█████▊    | 3491/6015 [24:14<17:30,  2.40it/s]

 58%|█████▊    | 3492/6015 [24:15<17:29,  2.40it/s]

 58%|█████▊    | 3493/6015 [24:15<17:29,  2.40it/s]

 58%|█████▊    | 3494/6015 [24:16<17:28,  2.40it/s]

 58%|█████▊    | 3495/6015 [24:16<17:28,  2.40it/s]

 58%|█████▊    | 3496/6015 [24:16<17:28,  2.40it/s]

 58%|█████▊    | 3497/6015 [24:17<17:28,  2.40it/s]

 58%|█████▊    | 3498/6015 [24:17<17:27,  2.40it/s]

 58%|█████▊    | 3499/6015 [24:18<17:27,  2.40it/s]

 58%|█████▊    | 3500/6015 [24:18<17:27,  2.40it/s]

 58%|█████▊    | 3501/6015 [24:19<17:27,  2.40it/s]

 58%|█████▊    | 3502/6015 [24:19<17:28,  2.40it/s]

 58%|█████▊    | 3503/6015 [24:19<17:27,  2.40it/s]

 58%|█████▊    | 3504/6015 [24:20<17:26,  2.40it/s]

 58%|█████▊    | 3505/6015 [24:20<17:25,  2.40it/s]

 58%|█████▊    | 3506/6015 [24:21<17:24,  2.40it/s]

 58%|█████▊    | 3507/6015 [24:21<17:24,  2.40it/s]

 58%|█████▊    | 3508/6015 [24:21<17:24,  2.40it/s]

 58%|█████▊    | 3509/6015 [24:22<17:24,  2.40it/s]

 58%|█████▊    | 3510/6015 [24:22<17:24,  2.40it/s]

 58%|█████▊    | 3511/6015 [24:23<17:22,  2.40it/s]

 58%|█████▊    | 3512/6015 [24:23<17:24,  2.40it/s]

 58%|█████▊    | 3513/6015 [24:24<17:22,  2.40it/s]

 58%|█████▊    | 3514/6015 [24:24<17:22,  2.40it/s]

 58%|█████▊    | 3515/6015 [24:24<17:21,  2.40it/s]

 58%|█████▊    | 3516/6015 [24:25<17:20,  2.40it/s]

 58%|█████▊    | 3517/6015 [24:25<17:20,  2.40it/s]

 58%|█████▊    | 3518/6015 [24:26<17:18,  2.40it/s]

 59%|█████▊    | 3519/6015 [24:26<17:19,  2.40it/s]

 59%|█████▊    | 3520/6015 [24:26<17:18,  2.40it/s]

 59%|█████▊    | 3521/6015 [24:27<17:18,  2.40it/s]

 59%|█████▊    | 3522/6015 [24:27<17:17,  2.40it/s]

 59%|█████▊    | 3523/6015 [24:28<17:17,  2.40it/s]

 59%|█████▊    | 3524/6015 [24:28<17:16,  2.40it/s]

 59%|█████▊    | 3525/6015 [24:28<17:16,  2.40it/s]

 59%|█████▊    | 3526/6015 [24:29<17:17,  2.40it/s]

 59%|█████▊    | 3527/6015 [24:29<17:17,  2.40it/s]

 59%|█████▊    | 3528/6015 [24:30<17:16,  2.40it/s]

 59%|█████▊    | 3529/6015 [24:30<17:16,  2.40it/s]

 59%|█████▊    | 3530/6015 [24:31<17:15,  2.40it/s]

 59%|█████▊    | 3531/6015 [24:31<17:13,  2.40it/s]

 59%|█████▊    | 3532/6015 [24:31<17:14,  2.40it/s]

 59%|█████▊    | 3533/6015 [24:32<17:13,  2.40it/s]

 59%|█████▉    | 3534/6015 [24:32<17:13,  2.40it/s]

 59%|█████▉    | 3535/6015 [24:33<17:13,  2.40it/s]

 59%|█████▉    | 3536/6015 [24:33<17:13,  2.40it/s]

 59%|█████▉    | 3537/6015 [24:33<17:12,  2.40it/s]

 59%|█████▉    | 3538/6015 [24:34<17:12,  2.40it/s]

 59%|█████▉    | 3539/6015 [24:34<17:11,  2.40it/s]

 59%|█████▉    | 3540/6015 [24:35<17:10,  2.40it/s]

 59%|█████▉    | 3541/6015 [24:35<17:10,  2.40it/s]

 59%|█████▉    | 3542/6015 [24:36<17:09,  2.40it/s]

 59%|█████▉    | 3543/6015 [24:36<17:08,  2.40it/s]

 59%|█████▉    | 3544/6015 [24:36<17:07,  2.40it/s]

 59%|█████▉    | 3545/6015 [24:37<17:07,  2.40it/s]

 59%|█████▉    | 3546/6015 [24:37<17:07,  2.40it/s]

 59%|█████▉    | 3547/6015 [24:38<17:05,  2.41it/s]

 59%|█████▉    | 3548/6015 [24:38<17:07,  2.40it/s]

 59%|█████▉    | 3549/6015 [24:38<17:06,  2.40it/s]

 59%|█████▉    | 3550/6015 [24:39<17:06,  2.40it/s]

 59%|█████▉    | 3551/6015 [24:39<17:08,  2.40it/s]

 59%|█████▉    | 3552/6015 [24:40<17:07,  2.40it/s]

 59%|█████▉    | 3553/6015 [24:40<17:06,  2.40it/s]

 59%|█████▉    | 3554/6015 [24:41<17:05,  2.40it/s]

 59%|█████▉    | 3555/6015 [24:41<17:04,  2.40it/s]

 59%|█████▉    | 3556/6015 [24:41<17:04,  2.40it/s]

 59%|█████▉    | 3557/6015 [24:42<17:02,  2.40it/s]

 59%|█████▉    | 3558/6015 [24:42<17:03,  2.40it/s]

 59%|█████▉    | 3559/6015 [24:43<17:02,  2.40it/s]

 59%|█████▉    | 3560/6015 [24:43<17:02,  2.40it/s]

 59%|█████▉    | 3561/6015 [24:43<17:02,  2.40it/s]

 59%|█████▉    | 3562/6015 [24:44<17:01,  2.40it/s]

 59%|█████▉    | 3563/6015 [24:44<17:00,  2.40it/s]

 59%|█████▉    | 3564/6015 [24:45<16:59,  2.40it/s]

 59%|█████▉    | 3565/6015 [24:45<17:00,  2.40it/s]

 59%|█████▉    | 3566/6015 [24:46<17:00,  2.40it/s]

 59%|█████▉    | 3567/6015 [24:46<17:05,  2.39it/s]

 59%|█████▉    | 3568/6015 [24:46<17:03,  2.39it/s]

 59%|█████▉    | 3569/6015 [24:47<17:01,  2.39it/s]

 59%|█████▉    | 3570/6015 [24:47<17:00,  2.40it/s]

 59%|█████▉    | 3571/6015 [24:48<16:59,  2.40it/s]

 59%|█████▉    | 3572/6015 [24:48<16:58,  2.40it/s]

 59%|█████▉    | 3573/6015 [24:48<16:58,  2.40it/s]

 59%|█████▉    | 3574/6015 [24:49<16:57,  2.40it/s]

 59%|█████▉    | 3575/6015 [24:49<16:56,  2.40it/s]

 59%|█████▉    | 3576/6015 [24:50<16:55,  2.40it/s]

 59%|█████▉    | 3577/6015 [24:50<16:56,  2.40it/s]

 59%|█████▉    | 3578/6015 [24:51<16:55,  2.40it/s]

 60%|█████▉    | 3579/6015 [24:51<16:56,  2.40it/s]

 60%|█████▉    | 3580/6015 [24:51<16:57,  2.39it/s]

 60%|█████▉    | 3581/6015 [24:52<16:55,  2.40it/s]

 60%|█████▉    | 3582/6015 [24:52<16:53,  2.40it/s]

 60%|█████▉    | 3583/6015 [24:53<16:54,  2.40it/s]

 60%|█████▉    | 3584/6015 [24:53<16:53,  2.40it/s]

 60%|█████▉    | 3585/6015 [24:54<16:51,  2.40it/s]

 60%|█████▉    | 3586/6015 [24:54<16:51,  2.40it/s]

 60%|█████▉    | 3587/6015 [24:54<16:52,  2.40it/s]

 60%|█████▉    | 3588/6015 [24:55<16:51,  2.40it/s]

 60%|█████▉    | 3589/6015 [24:55<16:50,  2.40it/s]

 60%|█████▉    | 3590/6015 [24:56<16:51,  2.40it/s]

 60%|█████▉    | 3591/6015 [24:56<16:51,  2.40it/s]

 60%|█████▉    | 3592/6015 [24:56<16:51,  2.40it/s]

 60%|█████▉    | 3593/6015 [24:57<16:49,  2.40it/s]

 60%|█████▉    | 3594/6015 [24:57<16:49,  2.40it/s]

 60%|█████▉    | 3595/6015 [24:58<16:50,  2.39it/s]

 60%|█████▉    | 3596/6015 [24:58<16:49,  2.40it/s]

 60%|█████▉    | 3597/6015 [24:59<16:49,  2.39it/s]

 60%|█████▉    | 3598/6015 [24:59<16:48,  2.40it/s]

 60%|█████▉    | 3599/6015 [24:59<16:48,  2.40it/s]

 60%|█████▉    | 3600/6015 [25:00<16:48,  2.39it/s]

 60%|█████▉    | 3601/6015 [25:00<16:47,  2.40it/s]

 60%|█████▉    | 3602/6015 [25:01<16:47,  2.39it/s]

 60%|█████▉    | 3603/6015 [25:01<16:47,  2.39it/s]

 60%|█████▉    | 3604/6015 [25:01<16:47,  2.39it/s]

 60%|█████▉    | 3605/6015 [25:02<16:46,  2.39it/s]

 60%|█████▉    | 3606/6015 [25:02<16:45,  2.39it/s]

 60%|█████▉    | 3607/6015 [25:03<16:45,  2.39it/s]

 60%|█████▉    | 3608/6015 [25:03<16:46,  2.39it/s]

 60%|██████    | 3609/6015 [25:04<16:44,  2.39it/s]

 60%|██████    | 3610/6015 [25:04<16:49,  2.38it/s]

 60%|██████    | 3611/6015 [25:04<16:48,  2.38it/s]

 60%|██████    | 3612/6015 [25:05<16:46,  2.39it/s]

 60%|██████    | 3613/6015 [25:05<16:44,  2.39it/s]

 60%|██████    | 3614/6015 [25:06<16:43,  2.39it/s]

 60%|██████    | 3615/6015 [25:06<16:42,  2.39it/s]

 60%|██████    | 3616/6015 [25:06<16:42,  2.39it/s]

 60%|██████    | 3617/6015 [25:07<16:40,  2.40it/s]

 60%|██████    | 3618/6015 [25:07<16:40,  2.39it/s]

 60%|██████    | 3619/6015 [25:08<16:44,  2.38it/s]

 60%|██████    | 3620/6015 [25:08<16:42,  2.39it/s]

 60%|██████    | 3621/6015 [25:09<16:39,  2.39it/s]

 60%|██████    | 3622/6015 [25:09<16:40,  2.39it/s]

 60%|██████    | 3623/6015 [25:09<16:40,  2.39it/s]

 60%|██████    | 3624/6015 [25:10<16:41,  2.39it/s]

 60%|██████    | 3625/6015 [25:10<16:38,  2.39it/s]

 60%|██████    | 3626/6015 [25:11<16:40,  2.39it/s]

 60%|██████    | 3627/6015 [25:11<16:39,  2.39it/s]

 60%|██████    | 3628/6015 [25:11<16:38,  2.39it/s]

 60%|██████    | 3629/6015 [25:12<16:37,  2.39it/s]

 60%|██████    | 3630/6015 [25:12<16:39,  2.39it/s]

 60%|██████    | 3631/6015 [25:13<16:38,  2.39it/s]

 60%|██████    | 3632/6015 [25:13<16:38,  2.39it/s]

 60%|██████    | 3633/6015 [25:14<16:36,  2.39it/s]

 60%|██████    | 3634/6015 [25:14<16:35,  2.39it/s]

 60%|██████    | 3635/6015 [25:14<16:34,  2.39it/s]

 60%|██████    | 3636/6015 [25:15<16:35,  2.39it/s]

 60%|██████    | 3637/6015 [25:15<16:33,  2.39it/s]

 60%|██████    | 3638/6015 [25:16<16:33,  2.39it/s]

 60%|██████    | 3639/6015 [25:16<16:32,  2.39it/s]

 61%|██████    | 3640/6015 [25:16<16:32,  2.39it/s]

 61%|██████    | 3641/6015 [25:17<16:31,  2.39it/s]

 61%|██████    | 3642/6015 [25:17<16:32,  2.39it/s]

 61%|██████    | 3643/6015 [25:18<16:30,  2.39it/s]

 61%|██████    | 3644/6015 [25:18<16:31,  2.39it/s]

 61%|██████    | 3645/6015 [25:19<16:32,  2.39it/s]

 61%|██████    | 3646/6015 [25:19<16:32,  2.39it/s]

 61%|██████    | 3647/6015 [25:19<16:29,  2.39it/s]

 61%|██████    | 3648/6015 [25:20<16:29,  2.39it/s]

 61%|██████    | 3649/6015 [25:20<16:28,  2.39it/s]

 61%|██████    | 3650/6015 [25:21<16:29,  2.39it/s]

 61%|██████    | 3651/6015 [25:21<16:29,  2.39it/s]

 61%|██████    | 3652/6015 [25:22<16:28,  2.39it/s]

 61%|██████    | 3653/6015 [25:22<16:27,  2.39it/s]

 61%|██████    | 3654/6015 [25:22<16:27,  2.39it/s]

 61%|██████    | 3655/6015 [25:23<16:26,  2.39it/s]

 61%|██████    | 3656/6015 [25:23<16:26,  2.39it/s]

 61%|██████    | 3657/6015 [25:24<16:27,  2.39it/s]

 61%|██████    | 3658/6015 [25:24<16:25,  2.39it/s]

 61%|██████    | 3659/6015 [25:24<16:23,  2.39it/s]

 61%|██████    | 3660/6015 [25:25<16:24,  2.39it/s]

 61%|██████    | 3661/6015 [25:25<16:23,  2.39it/s]

 61%|██████    | 3662/6015 [25:26<16:23,  2.39it/s]

 61%|██████    | 3663/6015 [25:26<16:22,  2.39it/s]

 61%|██████    | 3664/6015 [25:27<16:23,  2.39it/s]

 61%|██████    | 3665/6015 [25:27<16:22,  2.39it/s]

 61%|██████    | 3666/6015 [25:27<16:25,  2.38it/s]

 61%|██████    | 3667/6015 [25:28<16:23,  2.39it/s]

 61%|██████    | 3668/6015 [25:28<16:23,  2.39it/s]

 61%|██████    | 3669/6015 [25:29<16:22,  2.39it/s]

 61%|██████    | 3670/6015 [25:29<16:25,  2.38it/s]

 61%|██████    | 3671/6015 [25:29<16:23,  2.38it/s]

 61%|██████    | 3672/6015 [25:30<16:23,  2.38it/s]

 61%|██████    | 3673/6015 [25:30<16:22,  2.38it/s]

 61%|██████    | 3674/6015 [25:31<16:21,  2.39it/s]

 61%|██████    | 3675/6015 [25:31<16:19,  2.39it/s]

 61%|██████    | 3676/6015 [25:32<16:18,  2.39it/s]

 61%|██████    | 3677/6015 [25:32<16:17,  2.39it/s]

 61%|██████    | 3678/6015 [25:32<16:16,  2.39it/s]

 61%|██████    | 3679/6015 [25:33<16:16,  2.39it/s]

 61%|██████    | 3680/6015 [25:33<16:17,  2.39it/s]

 61%|██████    | 3681/6015 [25:34<16:15,  2.39it/s]

 61%|██████    | 3682/6015 [25:34<16:16,  2.39it/s]

 61%|██████    | 3683/6015 [25:34<16:15,  2.39it/s]

 61%|██████    | 3684/6015 [25:35<16:15,  2.39it/s]

 61%|██████▏   | 3685/6015 [25:35<16:15,  2.39it/s]

 61%|██████▏   | 3686/6015 [25:36<16:14,  2.39it/s]

 61%|██████▏   | 3687/6015 [25:36<16:14,  2.39it/s]

 61%|██████▏   | 3688/6015 [25:37<16:13,  2.39it/s]

 61%|██████▏   | 3689/6015 [25:37<16:15,  2.39it/s]

 61%|██████▏   | 3690/6015 [25:37<16:19,  2.37it/s]

 61%|██████▏   | 3691/6015 [25:38<16:17,  2.38it/s]

 61%|██████▏   | 3692/6015 [25:38<16:15,  2.38it/s]

 61%|██████▏   | 3693/6015 [25:39<16:14,  2.38it/s]

 61%|██████▏   | 3694/6015 [25:39<16:13,  2.39it/s]

 61%|██████▏   | 3695/6015 [25:40<16:11,  2.39it/s]

 61%|██████▏   | 3696/6015 [25:40<16:11,  2.39it/s]

 61%|██████▏   | 3697/6015 [25:40<16:11,  2.39it/s]

 61%|██████▏   | 3698/6015 [25:41<16:10,  2.39it/s]

 61%|██████▏   | 3699/6015 [25:41<16:08,  2.39it/s]

 62%|██████▏   | 3700/6015 [25:42<16:08,  2.39it/s]

 62%|██████▏   | 3701/6015 [25:42<16:08,  2.39it/s]

 62%|██████▏   | 3702/6015 [25:42<16:08,  2.39it/s]

 62%|██████▏   | 3703/6015 [25:43<16:08,  2.39it/s]

 62%|██████▏   | 3704/6015 [25:43<16:07,  2.39it/s]

 62%|██████▏   | 3705/6015 [25:44<16:06,  2.39it/s]

 62%|██████▏   | 3706/6015 [25:44<16:06,  2.39it/s]

 62%|██████▏   | 3707/6015 [25:45<16:05,  2.39it/s]

 62%|██████▏   | 3708/6015 [25:45<16:06,  2.39it/s]

 62%|██████▏   | 3709/6015 [25:45<16:04,  2.39it/s]

 62%|██████▏   | 3710/6015 [25:46<16:04,  2.39it/s]

 62%|██████▏   | 3711/6015 [25:46<16:03,  2.39it/s]

 62%|██████▏   | 3712/6015 [25:47<16:04,  2.39it/s]

 62%|██████▏   | 3713/6015 [25:47<16:03,  2.39it/s]

 62%|██████▏   | 3714/6015 [25:47<16:04,  2.38it/s]

 62%|██████▏   | 3715/6015 [25:48<16:04,  2.38it/s]

 62%|██████▏   | 3716/6015 [25:48<16:05,  2.38it/s]

 62%|██████▏   | 3717/6015 [25:49<16:03,  2.39it/s]

 62%|██████▏   | 3718/6015 [25:49<16:03,  2.38it/s]

 62%|██████▏   | 3719/6015 [25:50<16:02,  2.39it/s]

 62%|██████▏   | 3720/6015 [25:50<16:01,  2.39it/s]

 62%|██████▏   | 3721/6015 [25:50<15:59,  2.39it/s]

 62%|██████▏   | 3722/6015 [25:51<16:00,  2.39it/s]

 62%|██████▏   | 3723/6015 [25:51<15:59,  2.39it/s]

 62%|██████▏   | 3724/6015 [25:52<15:59,  2.39it/s]

 62%|██████▏   | 3725/6015 [25:52<15:59,  2.39it/s]

 62%|██████▏   | 3726/6015 [25:52<15:59,  2.38it/s]

 62%|██████▏   | 3727/6015 [25:53<15:58,  2.39it/s]

 62%|██████▏   | 3728/6015 [25:53<15:56,  2.39it/s]

 62%|██████▏   | 3729/6015 [25:54<15:55,  2.39it/s]

 62%|██████▏   | 3730/6015 [25:54<15:57,  2.39it/s]

 62%|██████▏   | 3731/6015 [25:55<15:55,  2.39it/s]

 62%|██████▏   | 3732/6015 [25:55<15:54,  2.39it/s]

 62%|██████▏   | 3733/6015 [25:55<15:56,  2.39it/s]

 62%|██████▏   | 3734/6015 [25:56<15:55,  2.39it/s]

 62%|██████▏   | 3735/6015 [25:56<15:54,  2.39it/s]

 62%|██████▏   | 3736/6015 [25:57<15:56,  2.38it/s]

 62%|██████▏   | 3737/6015 [25:57<15:54,  2.39it/s]

 62%|██████▏   | 3738/6015 [25:58<15:54,  2.39it/s]

 62%|██████▏   | 3739/6015 [25:58<15:55,  2.38it/s]

 62%|██████▏   | 3740/6015 [25:58<15:54,  2.38it/s]

 62%|██████▏   | 3741/6015 [25:59<15:52,  2.39it/s]

 62%|██████▏   | 3742/6015 [25:59<15:52,  2.39it/s]

 62%|██████▏   | 3743/6015 [26:00<15:52,  2.39it/s]

 62%|██████▏   | 3744/6015 [26:00<15:53,  2.38it/s]

 62%|██████▏   | 3745/6015 [26:00<15:52,  2.38it/s]

 62%|██████▏   | 3746/6015 [26:01<15:52,  2.38it/s]

 62%|██████▏   | 3747/6015 [26:01<15:50,  2.39it/s]

 62%|██████▏   | 3748/6015 [26:02<15:51,  2.38it/s]

 62%|██████▏   | 3749/6015 [26:02<15:50,  2.39it/s]

 62%|██████▏   | 3750/6015 [26:03<15:49,  2.38it/s]

 62%|██████▏   | 3751/6015 [26:03<15:47,  2.39it/s]

 62%|██████▏   | 3752/6015 [26:03<15:49,  2.38it/s]

 62%|██████▏   | 3753/6015 [26:04<15:49,  2.38it/s]

 62%|██████▏   | 3754/6015 [26:04<15:51,  2.38it/s]

 62%|██████▏   | 3755/6015 [26:05<15:49,  2.38it/s]

logging
logging the anndata

 62%|██████▏   | 3756/6015 [26:05<16:18,  2.31it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 62%|██████▏   | 3757/6015 [26:06<16:05,  2.34it/s]

 62%|██████▏   | 3758/6015 [26:06<15:54,  2.36it/s]

 62%|██████▏   | 3759/6015 [26:06<15:46,  2.38it/s]

 63%|██████▎   | 3760/6015 [26:07<15:41,  2.39it/s]

 63%|██████▎   | 3761/6015 [26:07<15:36,  2.41it/s]

 63%|██████▎   | 3762/6015 [26:08<15:34,  2.41it/s]

 63%|██████▎   | 3763/6015 [26:08<15:31,  2.42it/s]

 63%|██████▎   | 3764/6015 [26:08<15:29,  2.42it/s]

 63%|██████▎   | 3765/6015 [26:09<15:27,  2.43it/s]

 63%|██████▎   | 3766/6015 [26:09<15:27,  2.43it/s]

 63%|██████▎   | 3767/6015 [26:10<15:25,  2.43it/s]

 63%|██████▎   | 3768/6015 [26:10<15:25,  2.43it/s]

 63%|██████▎   | 3769/6015 [26:10<15:25,  2.43it/s]

 63%|██████▎   | 3770/6015 [26:11<15:25,  2.43it/s]

 63%|██████▎   | 3771/6015 [26:11<15:27,  2.42it/s]

 63%|██████▎   | 3772/6015 [26:12<15:26,  2.42it/s]

 63%|██████▎   | 3773/6015 [26:12<15:25,  2.42it/s]

 63%|██████▎   | 3774/6015 [26:13<15:25,  2.42it/s]

 63%|██████▎   | 3775/6015 [26:13<15:25,  2.42it/s]

 63%|██████▎   | 3776/6015 [26:13<15:23,  2.42it/s]

 63%|██████▎   | 3777/6015 [26:14<15:22,  2.42it/s]

 63%|██████▎   | 3778/6015 [26:14<15:21,  2.43it/s]

 63%|██████▎   | 3779/6015 [26:15<15:21,  2.43it/s]

 63%|██████▎   | 3780/6015 [26:15<15:20,  2.43it/s]

 63%|██████▎   | 3781/6015 [26:15<15:20,  2.43it/s]

 63%|██████▎   | 3782/6015 [26:16<15:21,  2.42it/s]

 63%|██████▎   | 3783/6015 [26:16<15:21,  2.42it/s]

 63%|██████▎   | 3784/6015 [26:17<15:20,  2.42it/s]

 63%|██████▎   | 3785/6015 [26:17<15:19,  2.43it/s]

 63%|██████▎   | 3786/6015 [26:17<15:18,  2.43it/s]

 63%|██████▎   | 3787/6015 [26:18<15:17,  2.43it/s]

 63%|██████▎   | 3788/6015 [26:18<15:18,  2.43it/s]

 63%|██████▎   | 3789/6015 [26:19<15:17,  2.43it/s]

 63%|██████▎   | 3790/6015 [26:19<15:17,  2.43it/s]

 63%|██████▎   | 3791/6015 [26:20<15:16,  2.43it/s]

 63%|██████▎   | 3792/6015 [26:20<15:16,  2.42it/s]

 63%|██████▎   | 3793/6015 [26:20<15:16,  2.42it/s]

 63%|██████▎   | 3794/6015 [26:21<15:15,  2.43it/s]

 63%|██████▎   | 3795/6015 [26:21<15:16,  2.42it/s]

 63%|██████▎   | 3796/6015 [26:22<15:15,  2.42it/s]

 63%|██████▎   | 3797/6015 [26:22<15:14,  2.43it/s]

 63%|██████▎   | 3798/6015 [26:22<15:14,  2.42it/s]

 63%|██████▎   | 3799/6015 [26:23<15:15,  2.42it/s]

 63%|██████▎   | 3800/6015 [26:23<15:14,  2.42it/s]

 63%|██████▎   | 3801/6015 [26:24<15:13,  2.42it/s]

 63%|██████▎   | 3802/6015 [26:24<15:13,  2.42it/s]

 63%|██████▎   | 3803/6015 [26:25<15:12,  2.42it/s]

 63%|██████▎   | 3804/6015 [26:25<15:11,  2.43it/s]

 63%|██████▎   | 3805/6015 [26:25<15:11,  2.42it/s]

 63%|██████▎   | 3806/6015 [26:26<15:10,  2.43it/s]

 63%|██████▎   | 3807/6015 [26:26<15:11,  2.42it/s]

 63%|██████▎   | 3808/6015 [26:27<15:12,  2.42it/s]

 63%|██████▎   | 3809/6015 [26:27<15:11,  2.42it/s]

 63%|██████▎   | 3810/6015 [26:27<15:11,  2.42it/s]

 63%|██████▎   | 3811/6015 [26:28<15:09,  2.42it/s]

 63%|██████▎   | 3812/6015 [26:28<15:09,  2.42it/s]

 63%|██████▎   | 3813/6015 [26:29<15:09,  2.42it/s]

 63%|██████▎   | 3814/6015 [26:29<15:09,  2.42it/s]

 63%|██████▎   | 3815/6015 [26:29<15:07,  2.42it/s]

 63%|██████▎   | 3816/6015 [26:30<15:07,  2.42it/s]

 63%|██████▎   | 3817/6015 [26:30<15:06,  2.42it/s]

 63%|██████▎   | 3818/6015 [26:31<15:06,  2.42it/s]

 63%|██████▎   | 3819/6015 [26:31<15:05,  2.42it/s]

 64%|██████▎   | 3820/6015 [26:32<15:06,  2.42it/s]

 64%|██████▎   | 3821/6015 [26:32<15:06,  2.42it/s]

 64%|██████▎   | 3822/6015 [26:32<15:05,  2.42it/s]

 64%|██████▎   | 3823/6015 [26:33<15:05,  2.42it/s]

 64%|██████▎   | 3824/6015 [26:33<15:04,  2.42it/s]

 64%|██████▎   | 3825/6015 [26:34<15:04,  2.42it/s]

 64%|██████▎   | 3826/6015 [26:34<15:05,  2.42it/s]

 64%|██████▎   | 3827/6015 [26:34<15:04,  2.42it/s]

 64%|██████▎   | 3828/6015 [26:35<15:03,  2.42it/s]

 64%|██████▎   | 3829/6015 [26:35<15:05,  2.41it/s]

 64%|██████▎   | 3830/6015 [26:36<15:05,  2.41it/s]

 64%|██████▎   | 3831/6015 [26:36<15:04,  2.42it/s]

 64%|██████▎   | 3832/6015 [26:36<15:04,  2.41it/s]

 64%|██████▎   | 3833/6015 [26:37<15:03,  2.42it/s]

 64%|██████▎   | 3834/6015 [26:37<15:02,  2.42it/s]

 64%|██████▍   | 3835/6015 [26:38<15:01,  2.42it/s]

 64%|██████▍   | 3836/6015 [26:38<15:00,  2.42it/s]

 64%|██████▍   | 3837/6015 [26:39<15:00,  2.42it/s]

 64%|██████▍   | 3838/6015 [26:39<15:00,  2.42it/s]

 64%|██████▍   | 3839/6015 [26:39<15:00,  2.42it/s]

 64%|██████▍   | 3840/6015 [26:40<15:00,  2.41it/s]

 64%|██████▍   | 3841/6015 [26:40<15:02,  2.41it/s]

 64%|██████▍   | 3842/6015 [26:41<15:00,  2.41it/s]

 64%|██████▍   | 3843/6015 [26:41<14:59,  2.41it/s]

 64%|██████▍   | 3844/6015 [26:41<14:58,  2.42it/s]

 64%|██████▍   | 3845/6015 [26:42<14:58,  2.42it/s]

 64%|██████▍   | 3846/6015 [26:42<14:56,  2.42it/s]

 64%|██████▍   | 3847/6015 [26:43<14:56,  2.42it/s]

 64%|██████▍   | 3848/6015 [26:43<14:54,  2.42it/s]

 64%|██████▍   | 3849/6015 [26:44<14:54,  2.42it/s]

 64%|██████▍   | 3850/6015 [26:44<14:55,  2.42it/s]

 64%|██████▍   | 3851/6015 [26:44<14:54,  2.42it/s]

 64%|██████▍   | 3852/6015 [26:45<14:54,  2.42it/s]

 64%|██████▍   | 3853/6015 [26:45<14:54,  2.42it/s]

 64%|██████▍   | 3854/6015 [26:46<14:54,  2.42it/s]

 64%|██████▍   | 3855/6015 [26:46<14:53,  2.42it/s]

 64%|██████▍   | 3856/6015 [26:46<14:53,  2.42it/s]

 64%|██████▍   | 3857/6015 [26:47<14:53,  2.42it/s]

 64%|██████▍   | 3858/6015 [26:47<14:53,  2.41it/s]

 64%|██████▍   | 3859/6015 [26:48<14:52,  2.42it/s]

 64%|██████▍   | 3860/6015 [26:48<14:51,  2.42it/s]

 64%|██████▍   | 3861/6015 [26:48<14:49,  2.42it/s]

 64%|██████▍   | 3862/6015 [26:49<14:49,  2.42it/s]

 64%|██████▍   | 3863/6015 [26:49<14:48,  2.42it/s]

 64%|██████▍   | 3864/6015 [26:50<14:48,  2.42it/s]

 64%|██████▍   | 3865/6015 [26:50<14:48,  2.42it/s]

 64%|██████▍   | 3866/6015 [26:51<14:47,  2.42it/s]

 64%|██████▍   | 3867/6015 [26:51<14:47,  2.42it/s]

 64%|██████▍   | 3868/6015 [26:51<14:47,  2.42it/s]

 64%|██████▍   | 3869/6015 [26:52<14:48,  2.41it/s]

 64%|██████▍   | 3870/6015 [26:52<14:47,  2.42it/s]

 64%|██████▍   | 3871/6015 [26:53<14:47,  2.42it/s]

 64%|██████▍   | 3872/6015 [26:53<14:46,  2.42it/s]

 64%|██████▍   | 3873/6015 [26:53<14:47,  2.41it/s]

 64%|██████▍   | 3874/6015 [26:54<14:46,  2.41it/s]

 64%|██████▍   | 3875/6015 [26:54<14:45,  2.42it/s]

 64%|██████▍   | 3876/6015 [26:55<14:45,  2.42it/s]

 64%|██████▍   | 3877/6015 [26:55<14:44,  2.42it/s]

 64%|██████▍   | 3878/6015 [26:56<14:44,  2.42it/s]

 64%|██████▍   | 3879/6015 [26:56<14:45,  2.41it/s]

 65%|██████▍   | 3880/6015 [26:56<14:43,  2.42it/s]

 65%|██████▍   | 3881/6015 [26:57<14:43,  2.42it/s]

 65%|██████▍   | 3882/6015 [26:57<14:42,  2.42it/s]

 65%|██████▍   | 3883/6015 [26:58<14:41,  2.42it/s]

 65%|██████▍   | 3884/6015 [26:58<14:42,  2.42it/s]

 65%|██████▍   | 3885/6015 [26:58<14:40,  2.42it/s]

 65%|██████▍   | 3886/6015 [26:59<14:41,  2.42it/s]

 65%|██████▍   | 3887/6015 [26:59<14:40,  2.42it/s]

 65%|██████▍   | 3888/6015 [27:00<14:39,  2.42it/s]

 65%|██████▍   | 3889/6015 [27:00<14:39,  2.42it/s]

 65%|██████▍   | 3890/6015 [27:00<14:39,  2.42it/s]

 65%|██████▍   | 3891/6015 [27:01<14:38,  2.42it/s]

 65%|██████▍   | 3892/6015 [27:01<14:37,  2.42it/s]

 65%|██████▍   | 3893/6015 [27:02<14:38,  2.42it/s]

 65%|██████▍   | 3894/6015 [27:02<14:38,  2.42it/s]

 65%|██████▍   | 3895/6015 [27:03<14:36,  2.42it/s]

 65%|██████▍   | 3896/6015 [27:03<14:36,  2.42it/s]

 65%|██████▍   | 3897/6015 [27:03<14:35,  2.42it/s]

 65%|██████▍   | 3898/6015 [27:04<14:35,  2.42it/s]

 65%|██████▍   | 3899/6015 [27:04<14:35,  2.42it/s]

 65%|██████▍   | 3900/6015 [27:05<14:33,  2.42it/s]

 65%|██████▍   | 3901/6015 [27:05<14:32,  2.42it/s]

 65%|██████▍   | 3902/6015 [27:05<14:34,  2.42it/s]

 65%|██████▍   | 3903/6015 [27:06<14:34,  2.42it/s]

 65%|██████▍   | 3904/6015 [27:06<14:32,  2.42it/s]

 65%|██████▍   | 3905/6015 [27:07<14:32,  2.42it/s]

 65%|██████▍   | 3906/6015 [27:07<14:31,  2.42it/s]

 65%|██████▍   | 3907/6015 [27:08<14:32,  2.42it/s]

 65%|██████▍   | 3908/6015 [27:08<14:31,  2.42it/s]

 65%|██████▍   | 3909/6015 [27:08<14:31,  2.42it/s]

 65%|██████▌   | 3910/6015 [27:09<14:31,  2.42it/s]

 65%|██████▌   | 3911/6015 [27:09<14:29,  2.42it/s]

 65%|██████▌   | 3912/6015 [27:10<14:29,  2.42it/s]

 65%|██████▌   | 3913/6015 [27:10<14:28,  2.42it/s]

 65%|██████▌   | 3914/6015 [27:10<14:29,  2.42it/s]

 65%|██████▌   | 3915/6015 [27:11<14:28,  2.42it/s]

 65%|██████▌   | 3916/6015 [27:11<14:28,  2.42it/s]

 65%|██████▌   | 3917/6015 [27:12<14:27,  2.42it/s]

 65%|██████▌   | 3918/6015 [27:12<14:27,  2.42it/s]

 65%|██████▌   | 3919/6015 [27:12<14:27,  2.42it/s]

 65%|██████▌   | 3920/6015 [27:13<14:27,  2.42it/s]

 65%|██████▌   | 3921/6015 [27:13<14:28,  2.41it/s]

 65%|██████▌   | 3922/6015 [27:14<14:26,  2.42it/s]

 65%|██████▌   | 3923/6015 [27:14<14:25,  2.42it/s]

 65%|██████▌   | 3924/6015 [27:15<14:25,  2.42it/s]

 65%|██████▌   | 3925/6015 [27:15<14:25,  2.41it/s]

 65%|██████▌   | 3926/6015 [27:15<14:24,  2.42it/s]

 65%|██████▌   | 3927/6015 [27:16<14:25,  2.41it/s]

 65%|██████▌   | 3928/6015 [27:16<14:23,  2.42it/s]

 65%|██████▌   | 3929/6015 [27:17<14:25,  2.41it/s]

 65%|██████▌   | 3930/6015 [27:17<14:25,  2.41it/s]

 65%|██████▌   | 3931/6015 [27:17<14:24,  2.41it/s]

 65%|██████▌   | 3932/6015 [27:18<14:23,  2.41it/s]

 65%|██████▌   | 3933/6015 [27:18<14:23,  2.41it/s]

 65%|██████▌   | 3934/6015 [27:19<14:22,  2.41it/s]

 65%|██████▌   | 3935/6015 [27:19<14:20,  2.42it/s]

 65%|██████▌   | 3936/6015 [27:20<14:19,  2.42it/s]

 65%|██████▌   | 3937/6015 [27:20<14:20,  2.42it/s]

 65%|██████▌   | 3938/6015 [27:20<14:19,  2.42it/s]

 65%|██████▌   | 3939/6015 [27:21<14:18,  2.42it/s]

 66%|██████▌   | 3940/6015 [27:21<14:17,  2.42it/s]

 66%|██████▌   | 3941/6015 [27:22<14:18,  2.42it/s]

 66%|██████▌   | 3942/6015 [27:22<14:17,  2.42it/s]

 66%|██████▌   | 3943/6015 [27:22<14:16,  2.42it/s]

 66%|██████▌   | 3944/6015 [27:23<14:17,  2.41it/s]

 66%|██████▌   | 3945/6015 [27:23<14:17,  2.41it/s]

 66%|██████▌   | 3946/6015 [27:24<14:17,  2.41it/s]

 66%|██████▌   | 3947/6015 [27:24<14:17,  2.41it/s]

 66%|██████▌   | 3948/6015 [27:24<14:16,  2.41it/s]

 66%|██████▌   | 3949/6015 [27:25<14:15,  2.42it/s]

 66%|██████▌   | 3950/6015 [27:25<14:14,  2.42it/s]

 66%|██████▌   | 3951/6015 [27:26<14:13,  2.42it/s]

 66%|██████▌   | 3952/6015 [27:26<14:14,  2.41it/s]

 66%|██████▌   | 3953/6015 [27:27<14:13,  2.42it/s]

 66%|██████▌   | 3954/6015 [27:27<14:13,  2.41it/s]

 66%|██████▌   | 3955/6015 [27:27<14:14,  2.41it/s]

 66%|██████▌   | 3956/6015 [27:28<14:13,  2.41it/s]

 66%|██████▌   | 3957/6015 [27:28<14:13,  2.41it/s]

 66%|██████▌   | 3958/6015 [27:29<14:12,  2.41it/s]

 66%|██████▌   | 3959/6015 [27:29<14:12,  2.41it/s]

 66%|██████▌   | 3960/6015 [27:29<14:12,  2.41it/s]

 66%|██████▌   | 3961/6015 [27:30<14:11,  2.41it/s]

 66%|██████▌   | 3962/6015 [27:30<14:11,  2.41it/s]

 66%|██████▌   | 3963/6015 [27:31<14:10,  2.41it/s]

 66%|██████▌   | 3964/6015 [27:31<14:09,  2.42it/s]

 66%|██████▌   | 3965/6015 [27:32<14:07,  2.42it/s]

 66%|██████▌   | 3966/6015 [27:32<14:06,  2.42it/s]

 66%|██████▌   | 3967/6015 [27:32<14:07,  2.42it/s]

 66%|██████▌   | 3968/6015 [27:33<14:07,  2.41it/s]

 66%|██████▌   | 3969/6015 [27:33<14:07,  2.41it/s]

 66%|██████▌   | 3970/6015 [27:34<14:06,  2.41it/s]

 66%|██████▌   | 3971/6015 [27:34<14:05,  2.42it/s]

 66%|██████▌   | 3972/6015 [27:34<14:05,  2.42it/s]

 66%|██████▌   | 3973/6015 [27:35<14:04,  2.42it/s]

 66%|██████▌   | 3974/6015 [27:35<14:05,  2.41it/s]

 66%|██████▌   | 3975/6015 [27:36<14:06,  2.41it/s]

 66%|██████▌   | 3976/6015 [27:36<14:08,  2.40it/s]

 66%|██████▌   | 3977/6015 [27:37<14:06,  2.41it/s]

 66%|██████▌   | 3978/6015 [27:37<14:05,  2.41it/s]

 66%|██████▌   | 3979/6015 [27:37<14:03,  2.41it/s]

 66%|██████▌   | 3980/6015 [27:38<14:02,  2.42it/s]

 66%|██████▌   | 3981/6015 [27:38<14:02,  2.41it/s]

 66%|██████▌   | 3982/6015 [27:39<14:02,  2.41it/s]

 66%|██████▌   | 3983/6015 [27:39<14:01,  2.42it/s]

 66%|██████▌   | 3984/6015 [27:39<14:00,  2.42it/s]

 66%|██████▋   | 3985/6015 [27:40<14:00,  2.42it/s]

 66%|██████▋   | 3986/6015 [27:40<13:59,  2.42it/s]

 66%|██████▋   | 3987/6015 [27:41<13:59,  2.42it/s]

 66%|██████▋   | 3988/6015 [27:41<13:59,  2.42it/s]

 66%|██████▋   | 3989/6015 [27:41<13:59,  2.41it/s]

 66%|██████▋   | 3990/6015 [27:42<13:58,  2.42it/s]

 66%|██████▋   | 3991/6015 [27:42<13:59,  2.41it/s]

 66%|██████▋   | 3992/6015 [27:43<13:58,  2.41it/s]

 66%|██████▋   | 3993/6015 [27:43<13:58,  2.41it/s]

 66%|██████▋   | 3994/6015 [27:44<13:57,  2.41it/s]

 66%|██████▋   | 3995/6015 [27:44<13:56,  2.41it/s]

 66%|██████▋   | 3996/6015 [27:44<13:55,  2.42it/s]

 66%|██████▋   | 3997/6015 [27:45<13:56,  2.41it/s]

 66%|██████▋   | 3998/6015 [27:45<13:56,  2.41it/s]

 66%|██████▋   | 3999/6015 [27:46<13:55,  2.41it/s]

 67%|██████▋   | 4000/6015 [27:46<13:55,  2.41it/s]

 67%|██████▋   | 4001/6015 [27:46<13:54,  2.41it/s]

 67%|██████▋   | 4002/6015 [27:47<13:54,  2.41it/s]

 67%|██████▋   | 4003/6015 [27:47<13:54,  2.41it/s]

 67%|██████▋   | 4004/6015 [27:48<13:54,  2.41it/s]

 67%|██████▋   | 4005/6015 [27:48<13:56,  2.40it/s]

 67%|██████▋   | 4006/6015 [27:49<13:54,  2.41it/s]

 67%|██████▋   | 4007/6015 [27:49<13:53,  2.41it/s]

 67%|██████▋   | 4008/6015 [27:49<13:51,  2.41it/s]

 67%|██████▋   | 4009/6015 [27:50<13:52,  2.41it/s]

 67%|██████▋   | 4010/6015 [27:50<13:51,  2.41it/s]

 67%|██████▋   | 4011/6015 [27:51<13:51,  2.41it/s]

 67%|██████▋   | 4012/6015 [27:51<13:50,  2.41it/s]

 67%|██████▋   | 4013/6015 [27:51<13:51,  2.41it/s]

 67%|██████▋   | 4014/6015 [27:52<13:49,  2.41it/s]

 67%|██████▋   | 4015/6015 [27:52<13:49,  2.41it/s]

 67%|██████▋   | 4016/6015 [27:53<13:49,  2.41it/s]

 67%|██████▋   | 4017/6015 [27:53<13:48,  2.41it/s]

 67%|██████▋   | 4018/6015 [27:53<13:47,  2.41it/s]

 67%|██████▋   | 4019/6015 [27:54<13:48,  2.41it/s]

 67%|██████▋   | 4020/6015 [27:54<13:47,  2.41it/s]

 67%|██████▋   | 4021/6015 [27:55<13:46,  2.41it/s]

 67%|██████▋   | 4022/6015 [27:55<13:46,  2.41it/s]

 67%|██████▋   | 4023/6015 [27:56<13:45,  2.41it/s]

 67%|██████▋   | 4024/6015 [27:56<13:45,  2.41it/s]

 67%|██████▋   | 4025/6015 [27:56<13:45,  2.41it/s]

 67%|██████▋   | 4026/6015 [27:57<13:45,  2.41it/s]

 67%|██████▋   | 4027/6015 [27:57<13:44,  2.41it/s]

 67%|██████▋   | 4028/6015 [27:58<13:44,  2.41it/s]

 67%|██████▋   | 4029/6015 [27:58<13:44,  2.41it/s]

 67%|██████▋   | 4030/6015 [27:58<13:44,  2.41it/s]

 67%|██████▋   | 4031/6015 [27:59<13:43,  2.41it/s]

 67%|██████▋   | 4032/6015 [27:59<13:44,  2.41it/s]

 67%|██████▋   | 4033/6015 [28:00<13:43,  2.41it/s]

 67%|██████▋   | 4034/6015 [28:00<13:43,  2.41it/s]

 67%|██████▋   | 4035/6015 [28:01<13:41,  2.41it/s]

 67%|██████▋   | 4036/6015 [28:01<13:41,  2.41it/s]

 67%|██████▋   | 4037/6015 [28:01<13:40,  2.41it/s]

 67%|██████▋   | 4038/6015 [28:02<13:39,  2.41it/s]

 67%|██████▋   | 4039/6015 [28:02<13:39,  2.41it/s]

 67%|██████▋   | 4040/6015 [28:03<13:38,  2.41it/s]

 67%|██████▋   | 4041/6015 [28:03<13:37,  2.41it/s]

 67%|██████▋   | 4042/6015 [28:03<13:38,  2.41it/s]

 67%|██████▋   | 4043/6015 [28:04<13:37,  2.41it/s]

 67%|██████▋   | 4044/6015 [28:04<13:38,  2.41it/s]

 67%|██████▋   | 4045/6015 [28:05<13:37,  2.41it/s]

 67%|██████▋   | 4046/6015 [28:05<13:38,  2.41it/s]

 67%|██████▋   | 4047/6015 [28:06<13:38,  2.40it/s]

 67%|██████▋   | 4048/6015 [28:06<13:37,  2.41it/s]

 67%|██████▋   | 4049/6015 [28:06<13:37,  2.40it/s]

 67%|██████▋   | 4050/6015 [28:07<13:36,  2.41it/s]

 67%|██████▋   | 4051/6015 [28:07<13:34,  2.41it/s]

 67%|██████▋   | 4052/6015 [28:08<13:34,  2.41it/s]

 67%|██████▋   | 4053/6015 [28:08<13:34,  2.41it/s]

 67%|██████▋   | 4054/6015 [28:08<13:33,  2.41it/s]

 67%|██████▋   | 4055/6015 [28:09<13:33,  2.41it/s]

 67%|██████▋   | 4056/6015 [28:09<13:32,  2.41it/s]

 67%|██████▋   | 4057/6015 [28:10<13:32,  2.41it/s]

 67%|██████▋   | 4058/6015 [28:10<13:32,  2.41it/s]

 67%|██████▋   | 4059/6015 [28:11<13:32,  2.41it/s]

 67%|██████▋   | 4060/6015 [28:11<13:32,  2.41it/s]

 68%|██████▊   | 4061/6015 [28:11<13:32,  2.41it/s]

 68%|██████▊   | 4062/6015 [28:12<13:31,  2.41it/s]

 68%|██████▊   | 4063/6015 [28:12<13:30,  2.41it/s]

 68%|██████▊   | 4064/6015 [28:13<13:29,  2.41it/s]

 68%|██████▊   | 4065/6015 [28:13<13:30,  2.40it/s]

 68%|██████▊   | 4066/6015 [28:13<13:29,  2.41it/s]

 68%|██████▊   | 4067/6015 [28:14<13:28,  2.41it/s]

 68%|██████▊   | 4068/6015 [28:14<13:28,  2.41it/s]

 68%|██████▊   | 4069/6015 [28:15<13:28,  2.41it/s]

 68%|██████▊   | 4070/6015 [28:15<13:27,  2.41it/s]

 68%|██████▊   | 4071/6015 [28:16<13:27,  2.41it/s]

 68%|██████▊   | 4072/6015 [28:16<13:26,  2.41it/s]

 68%|██████▊   | 4073/6015 [28:16<13:25,  2.41it/s]

 68%|██████▊   | 4074/6015 [28:17<13:26,  2.41it/s]

 68%|██████▊   | 4075/6015 [28:17<13:26,  2.41it/s]

 68%|██████▊   | 4076/6015 [28:18<13:26,  2.40it/s]

 68%|██████▊   | 4077/6015 [28:18<13:25,  2.41it/s]

 68%|██████▊   | 4078/6015 [28:18<13:25,  2.41it/s]

 68%|██████▊   | 4079/6015 [28:19<13:24,  2.41it/s]

 68%|██████▊   | 4080/6015 [28:19<13:23,  2.41it/s]

 68%|██████▊   | 4081/6015 [28:20<13:23,  2.41it/s]

 68%|██████▊   | 4082/6015 [28:20<13:23,  2.41it/s]

 68%|██████▊   | 4083/6015 [28:20<13:21,  2.41it/s]

 68%|██████▊   | 4084/6015 [28:21<13:21,  2.41it/s]

 68%|██████▊   | 4085/6015 [28:21<13:21,  2.41it/s]

 68%|██████▊   | 4086/6015 [28:22<13:21,  2.41it/s]

 68%|██████▊   | 4087/6015 [28:22<13:21,  2.40it/s]

 68%|██████▊   | 4088/6015 [28:23<13:21,  2.40it/s]

 68%|██████▊   | 4089/6015 [28:23<13:21,  2.40it/s]

 68%|██████▊   | 4090/6015 [28:23<13:20,  2.40it/s]

 68%|██████▊   | 4091/6015 [28:24<13:21,  2.40it/s]

 68%|██████▊   | 4092/6015 [28:24<13:20,  2.40it/s]

 68%|██████▊   | 4093/6015 [28:25<13:19,  2.40it/s]

 68%|██████▊   | 4094/6015 [28:25<13:19,  2.40it/s]

 68%|██████▊   | 4095/6015 [28:25<13:19,  2.40it/s]

 68%|██████▊   | 4096/6015 [28:26<13:17,  2.40it/s]

 68%|██████▊   | 4097/6015 [28:26<13:17,  2.41it/s]

 68%|██████▊   | 4098/6015 [28:27<13:17,  2.40it/s]

 68%|██████▊   | 4099/6015 [28:27<13:18,  2.40it/s]

 68%|██████▊   | 4100/6015 [28:28<13:16,  2.40it/s]

 68%|██████▊   | 4101/6015 [28:28<13:16,  2.40it/s]

 68%|██████▊   | 4102/6015 [28:28<13:17,  2.40it/s]

 68%|██████▊   | 4103/6015 [28:29<13:19,  2.39it/s]

 68%|██████▊   | 4104/6015 [28:29<13:17,  2.40it/s]

 68%|██████▊   | 4105/6015 [28:30<13:17,  2.40it/s]

 68%|██████▊   | 4106/6015 [28:30<13:15,  2.40it/s]

 68%|██████▊   | 4107/6015 [28:30<13:15,  2.40it/s]

 68%|██████▊   | 4108/6015 [28:31<13:14,  2.40it/s]

 68%|██████▊   | 4109/6015 [28:31<13:14,  2.40it/s]

 68%|██████▊   | 4110/6015 [28:32<13:13,  2.40it/s]

 68%|██████▊   | 4111/6015 [28:32<13:12,  2.40it/s]

 68%|██████▊   | 4112/6015 [28:33<13:11,  2.40it/s]

 68%|██████▊   | 4113/6015 [28:33<13:12,  2.40it/s]

 68%|██████▊   | 4114/6015 [28:33<13:10,  2.40it/s]

 68%|██████▊   | 4115/6015 [28:34<13:10,  2.40it/s]

 68%|██████▊   | 4116/6015 [28:34<13:09,  2.41it/s]

 68%|██████▊   | 4117/6015 [28:35<13:10,  2.40it/s]

 68%|██████▊   | 4118/6015 [28:35<13:09,  2.40it/s]

 68%|██████▊   | 4119/6015 [28:35<13:09,  2.40it/s]

 68%|██████▊   | 4120/6015 [28:36<13:10,  2.40it/s]

 69%|██████▊   | 4121/6015 [28:36<13:09,  2.40it/s]

 69%|██████▊   | 4122/6015 [28:37<13:10,  2.39it/s]

 69%|██████▊   | 4123/6015 [28:37<13:08,  2.40it/s]

 69%|██████▊   | 4124/6015 [28:38<13:07,  2.40it/s]

 69%|██████▊   | 4125/6015 [28:38<13:06,  2.40it/s]

 69%|██████▊   | 4126/6015 [28:38<13:06,  2.40it/s]

 69%|██████▊   | 4127/6015 [28:39<13:05,  2.40it/s]

 69%|██████▊   | 4128/6015 [28:39<13:05,  2.40it/s]

 69%|██████▊   | 4129/6015 [28:40<13:04,  2.40it/s]

 69%|██████▊   | 4130/6015 [28:40<13:04,  2.40it/s]

 69%|██████▊   | 4131/6015 [28:40<13:03,  2.40it/s]

 69%|██████▊   | 4132/6015 [28:41<13:04,  2.40it/s]

 69%|██████▊   | 4133/6015 [28:41<13:03,  2.40it/s]

 69%|██████▊   | 4134/6015 [28:42<13:03,  2.40it/s]

 69%|██████▊   | 4135/6015 [28:42<13:02,  2.40it/s]

 69%|██████▉   | 4136/6015 [28:43<13:02,  2.40it/s]

 69%|██████▉   | 4137/6015 [28:43<13:01,  2.40it/s]

 69%|██████▉   | 4138/6015 [28:43<13:01,  2.40it/s]

 69%|██████▉   | 4139/6015 [28:44<13:00,  2.40it/s]

 69%|██████▉   | 4140/6015 [28:44<13:01,  2.40it/s]

 69%|██████▉   | 4141/6015 [28:45<13:00,  2.40it/s]

 69%|██████▉   | 4142/6015 [28:45<13:00,  2.40it/s]

 69%|██████▉   | 4143/6015 [28:45<12:59,  2.40it/s]

 69%|██████▉   | 4144/6015 [28:46<12:58,  2.40it/s]

 69%|██████▉   | 4145/6015 [28:46<12:58,  2.40it/s]

 69%|██████▉   | 4146/6015 [28:47<12:56,  2.41it/s]

 69%|██████▉   | 4147/6015 [28:47<12:56,  2.41it/s]

 69%|██████▉   | 4148/6015 [28:48<12:56,  2.41it/s]

 69%|██████▉   | 4149/6015 [28:48<12:56,  2.40it/s]

 69%|██████▉   | 4150/6015 [28:48<12:55,  2.40it/s]

 69%|██████▉   | 4151/6015 [28:49<12:55,  2.40it/s]

 69%|██████▉   | 4152/6015 [28:49<12:55,  2.40it/s]

 69%|██████▉   | 4153/6015 [28:50<12:56,  2.40it/s]

 69%|██████▉   | 4154/6015 [28:50<12:55,  2.40it/s]

 69%|██████▉   | 4155/6015 [28:50<12:54,  2.40it/s]

 69%|██████▉   | 4156/6015 [28:51<12:54,  2.40it/s]

 69%|██████▉   | 4157/6015 [28:51<12:53,  2.40it/s]

 69%|██████▉   | 4158/6015 [28:52<12:53,  2.40it/s]

 69%|██████▉   | 4159/6015 [28:52<12:52,  2.40it/s]

 69%|██████▉   | 4160/6015 [28:53<12:52,  2.40it/s]

 69%|██████▉   | 4161/6015 [28:53<12:51,  2.40it/s]

 69%|██████▉   | 4162/6015 [28:53<12:51,  2.40it/s]

 69%|██████▉   | 4163/6015 [28:54<12:51,  2.40it/s]

 69%|██████▉   | 4164/6015 [28:54<12:50,  2.40it/s]

 69%|██████▉   | 4165/6015 [28:55<12:50,  2.40it/s]

 69%|██████▉   | 4166/6015 [28:55<12:51,  2.40it/s]

 69%|██████▉   | 4167/6015 [28:55<12:50,  2.40it/s]

 69%|██████▉   | 4168/6015 [28:56<12:49,  2.40it/s]

 69%|██████▉   | 4169/6015 [28:56<12:48,  2.40it/s]

 69%|██████▉   | 4170/6015 [28:57<12:48,  2.40it/s]

 69%|██████▉   | 4171/6015 [28:57<12:48,  2.40it/s]

 69%|██████▉   | 4172/6015 [28:58<12:47,  2.40it/s]

 69%|██████▉   | 4173/6015 [28:58<12:46,  2.40it/s]

 69%|██████▉   | 4174/6015 [28:58<12:46,  2.40it/s]

 69%|██████▉   | 4175/6015 [28:59<12:46,  2.40it/s]

 69%|██████▉   | 4176/6015 [28:59<12:45,  2.40it/s]

 69%|██████▉   | 4177/6015 [29:00<12:45,  2.40it/s]

 69%|██████▉   | 4178/6015 [29:00<12:47,  2.39it/s]

 69%|██████▉   | 4179/6015 [29:00<12:46,  2.40it/s]

 69%|██████▉   | 4180/6015 [29:01<12:45,  2.40it/s]

 70%|██████▉   | 4181/6015 [29:01<12:45,  2.39it/s]

 70%|██████▉   | 4182/6015 [29:02<12:45,  2.40it/s]

 70%|██████▉   | 4183/6015 [29:02<12:44,  2.40it/s]

 70%|██████▉   | 4184/6015 [29:03<12:43,  2.40it/s]

 70%|██████▉   | 4185/6015 [29:03<12:44,  2.40it/s]

 70%|██████▉   | 4186/6015 [29:03<12:42,  2.40it/s]

 70%|██████▉   | 4187/6015 [29:04<12:43,  2.40it/s]

 70%|██████▉   | 4188/6015 [29:04<12:41,  2.40it/s]

 70%|██████▉   | 4189/6015 [29:05<12:41,  2.40it/s]

 70%|██████▉   | 4190/6015 [29:05<12:40,  2.40it/s]

 70%|██████▉   | 4191/6015 [29:05<12:40,  2.40it/s]

 70%|██████▉   | 4192/6015 [29:06<12:39,  2.40it/s]

 70%|██████▉   | 4193/6015 [29:06<12:39,  2.40it/s]

 70%|██████▉   | 4194/6015 [29:07<12:38,  2.40it/s]

 70%|██████▉   | 4195/6015 [29:07<12:38,  2.40it/s]

 70%|██████▉   | 4196/6015 [29:08<12:37,  2.40it/s]

 70%|██████▉   | 4197/6015 [29:08<12:38,  2.40it/s]

 70%|██████▉   | 4198/6015 [29:08<12:37,  2.40it/s]

 70%|██████▉   | 4199/6015 [29:09<12:37,  2.40it/s]

 70%|██████▉   | 4200/6015 [29:09<12:35,  2.40it/s]

 70%|██████▉   | 4201/6015 [29:10<12:35,  2.40it/s]

 70%|██████▉   | 4202/6015 [29:10<12:34,  2.40it/s]

 70%|██████▉   | 4203/6015 [29:10<12:34,  2.40it/s]

 70%|██████▉   | 4204/6015 [29:11<12:35,  2.40it/s]

 70%|██████▉   | 4205/6015 [29:11<12:34,  2.40it/s]

 70%|██████▉   | 4206/6015 [29:12<12:35,  2.39it/s]

 70%|██████▉   | 4207/6015 [29:12<12:34,  2.40it/s]

 70%|██████▉   | 4208/6015 [29:13<12:33,  2.40it/s]

 70%|██████▉   | 4209/6015 [29:13<12:32,  2.40it/s]

 70%|██████▉   | 4210/6015 [29:13<12:33,  2.40it/s]

 70%|███████   | 4211/6015 [29:14<12:32,  2.40it/s]

 70%|███████   | 4212/6015 [29:14<12:32,  2.40it/s]

 70%|███████   | 4213/6015 [29:15<12:32,  2.39it/s]

 70%|███████   | 4214/6015 [29:15<12:31,  2.40it/s]

 70%|███████   | 4215/6015 [29:15<12:31,  2.40it/s]

 70%|███████   | 4216/6015 [29:16<12:31,  2.39it/s]

 70%|███████   | 4217/6015 [29:16<12:30,  2.40it/s]

 70%|███████   | 4218/6015 [29:17<12:29,  2.40it/s]

 70%|███████   | 4219/6015 [29:17<12:29,  2.39it/s]

 70%|███████   | 4220/6015 [29:18<12:29,  2.39it/s]

 70%|███████   | 4221/6015 [29:18<12:28,  2.40it/s]

 70%|███████   | 4222/6015 [29:18<12:29,  2.39it/s]

 70%|███████   | 4223/6015 [29:19<12:28,  2.39it/s]

 70%|███████   | 4224/6015 [29:19<12:28,  2.39it/s]

 70%|███████   | 4225/6015 [29:20<12:27,  2.39it/s]

 70%|███████   | 4226/6015 [29:20<12:28,  2.39it/s]

 70%|███████   | 4227/6015 [29:20<12:26,  2.40it/s]

 70%|███████   | 4228/6015 [29:21<12:26,  2.40it/s]

 70%|███████   | 4229/6015 [29:21<12:25,  2.40it/s]

 70%|███████   | 4230/6015 [29:22<12:24,  2.40it/s]

 70%|███████   | 4231/6015 [29:22<12:24,  2.40it/s]

 70%|███████   | 4232/6015 [29:23<12:23,  2.40it/s]

 70%|███████   | 4233/6015 [29:23<12:23,  2.40it/s]

 70%|███████   | 4234/6015 [29:23<12:22,  2.40it/s]

 70%|███████   | 4235/6015 [29:24<12:22,  2.40it/s]

 70%|███████   | 4236/6015 [29:24<12:21,  2.40it/s]

 70%|███████   | 4237/6015 [29:25<12:22,  2.40it/s]

 70%|███████   | 4238/6015 [29:25<12:22,  2.39it/s]

 70%|███████   | 4239/6015 [29:25<12:22,  2.39it/s]

 70%|███████   | 4240/6015 [29:26<12:20,  2.40it/s]

 71%|███████   | 4241/6015 [29:26<12:20,  2.40it/s]

 71%|███████   | 4242/6015 [29:27<12:21,  2.39it/s]

 71%|███████   | 4243/6015 [29:27<12:20,  2.39it/s]

 71%|███████   | 4244/6015 [29:28<12:21,  2.39it/s]

 71%|███████   | 4245/6015 [29:28<12:19,  2.39it/s]

 71%|███████   | 4246/6015 [29:28<12:19,  2.39it/s]

 71%|███████   | 4247/6015 [29:29<12:18,  2.39it/s]

 71%|███████   | 4248/6015 [29:29<12:18,  2.39it/s]

 71%|███████   | 4249/6015 [29:30<12:16,  2.40it/s]

 71%|███████   | 4250/6015 [29:30<12:16,  2.40it/s]

 71%|███████   | 4251/6015 [29:31<12:16,  2.40it/s]

 71%|███████   | 4252/6015 [29:31<12:15,  2.40it/s]

 71%|███████   | 4253/6015 [29:31<12:14,  2.40it/s]

 71%|███████   | 4254/6015 [29:32<12:14,  2.40it/s]

 71%|███████   | 4255/6015 [29:32<12:15,  2.39it/s]

 71%|███████   | 4256/6015 [29:33<12:15,  2.39it/s]

 71%|███████   | 4257/6015 [29:33<12:15,  2.39it/s]

 71%|███████   | 4258/6015 [29:33<12:14,  2.39it/s]

 71%|███████   | 4259/6015 [29:34<12:15,  2.39it/s]

 71%|███████   | 4260/6015 [29:34<12:13,  2.39it/s]

 71%|███████   | 4261/6015 [29:35<12:12,  2.39it/s]

 71%|███████   | 4262/6015 [29:35<12:11,  2.40it/s]

 71%|███████   | 4263/6015 [29:36<12:11,  2.39it/s]

 71%|███████   | 4264/6015 [29:36<12:10,  2.40it/s]

 71%|███████   | 4265/6015 [29:36<12:09,  2.40it/s]

 71%|███████   | 4266/6015 [29:37<12:08,  2.40it/s]

 71%|███████   | 4267/6015 [29:37<12:09,  2.40it/s]

 71%|███████   | 4268/6015 [29:38<12:08,  2.40it/s]

 71%|███████   | 4269/6015 [29:38<12:08,  2.40it/s]

 71%|███████   | 4270/6015 [29:38<12:08,  2.40it/s]

 71%|███████   | 4271/6015 [29:39<12:09,  2.39it/s]

 71%|███████   | 4272/6015 [29:39<12:08,  2.39it/s]

 71%|███████   | 4273/6015 [29:40<12:08,  2.39it/s]

 71%|███████   | 4274/6015 [29:40<12:07,  2.39it/s]

 71%|███████   | 4275/6015 [29:41<12:06,  2.40it/s]

 71%|███████   | 4276/6015 [29:41<12:07,  2.39it/s]

 71%|███████   | 4277/6015 [29:41<12:07,  2.39it/s]

 71%|███████   | 4278/6015 [29:42<12:06,  2.39it/s]

 71%|███████   | 4279/6015 [29:42<12:06,  2.39it/s]

 71%|███████   | 4280/6015 [29:43<12:05,  2.39it/s]

 71%|███████   | 4281/6015 [29:43<12:05,  2.39it/s]

 71%|███████   | 4282/6015 [29:43<12:04,  2.39it/s]

 71%|███████   | 4283/6015 [29:44<12:05,  2.39it/s]

 71%|███████   | 4284/6015 [29:44<12:03,  2.39it/s]

 71%|███████   | 4285/6015 [29:45<12:03,  2.39it/s]

 71%|███████▏  | 4286/6015 [29:45<12:02,  2.39it/s]

 71%|███████▏  | 4287/6015 [29:46<12:02,  2.39it/s]

 71%|███████▏  | 4288/6015 [29:46<12:01,  2.39it/s]

 71%|███████▏  | 4289/6015 [29:46<12:02,  2.39it/s]

 71%|███████▏  | 4290/6015 [29:47<12:00,  2.39it/s]

 71%|███████▏  | 4291/6015 [29:47<12:01,  2.39it/s]

 71%|███████▏  | 4292/6015 [29:48<12:00,  2.39it/s]

 71%|███████▏  | 4293/6015 [29:48<12:00,  2.39it/s]

 71%|███████▏  | 4294/6015 [29:48<11:59,  2.39it/s]

 71%|███████▏  | 4295/6015 [29:49<12:00,  2.39it/s]

 71%|███████▏  | 4296/6015 [29:49<11:58,  2.39it/s]

 71%|███████▏  | 4297/6015 [29:50<11:59,  2.39it/s]

 71%|███████▏  | 4298/6015 [29:50<11:58,  2.39it/s]

 71%|███████▏  | 4299/6015 [29:51<11:57,  2.39it/s]

 71%|███████▏  | 4300/6015 [29:51<11:57,  2.39it/s]

 72%|███████▏  | 4301/6015 [29:51<11:57,  2.39it/s]

 72%|███████▏  | 4302/6015 [29:52<11:56,  2.39it/s]

 72%|███████▏  | 4303/6015 [29:52<11:56,  2.39it/s]

 72%|███████▏  | 4304/6015 [29:53<11:55,  2.39it/s]

 72%|███████▏  | 4305/6015 [29:53<11:55,  2.39it/s]

 72%|███████▏  | 4306/6015 [29:53<11:54,  2.39it/s]

 72%|███████▏  | 4307/6015 [29:54<11:54,  2.39it/s]

 72%|███████▏  | 4308/6015 [29:54<11:53,  2.39it/s]

 72%|███████▏  | 4309/6015 [29:55<11:53,  2.39it/s]

 72%|███████▏  | 4310/6015 [29:55<11:53,  2.39it/s]

 72%|███████▏  | 4311/6015 [29:56<11:53,  2.39it/s]

 72%|███████▏  | 4312/6015 [29:56<11:53,  2.39it/s]

 72%|███████▏  | 4313/6015 [29:56<11:53,  2.38it/s]

 72%|███████▏  | 4314/6015 [29:57<11:55,  2.38it/s]

 72%|███████▏  | 4315/6015 [29:57<11:54,  2.38it/s]

 72%|███████▏  | 4316/6015 [29:58<11:53,  2.38it/s]

 72%|███████▏  | 4317/6015 [29:58<11:52,  2.38it/s]

 72%|███████▏  | 4318/6015 [29:59<11:51,  2.39it/s]

 72%|███████▏  | 4319/6015 [29:59<11:51,  2.38it/s]

 72%|███████▏  | 4320/6015 [29:59<11:50,  2.38it/s]

 72%|███████▏  | 4321/6015 [30:00<11:49,  2.39it/s]

 72%|███████▏  | 4322/6015 [30:00<11:50,  2.38it/s]

 72%|███████▏  | 4323/6015 [30:01<11:49,  2.39it/s]

 72%|███████▏  | 4324/6015 [30:01<11:49,  2.38it/s]

 72%|███████▏  | 4325/6015 [30:01<11:48,  2.39it/s]

 72%|███████▏  | 4326/6015 [30:02<11:47,  2.39it/s]

 72%|███████▏  | 4327/6015 [30:02<11:48,  2.38it/s]

 72%|███████▏  | 4328/6015 [30:03<11:47,  2.38it/s]

 72%|███████▏  | 4329/6015 [30:03<11:46,  2.39it/s]

 72%|███████▏  | 4330/6015 [30:04<11:45,  2.39it/s]

 72%|███████▏  | 4331/6015 [30:04<11:43,  2.39it/s]

 72%|███████▏  | 4332/6015 [30:04<11:43,  2.39it/s]

 72%|███████▏  | 4333/6015 [30:05<11:43,  2.39it/s]

 72%|███████▏  | 4334/6015 [30:05<11:42,  2.39it/s]

 72%|███████▏  | 4335/6015 [30:06<11:42,  2.39it/s]

 72%|███████▏  | 4336/6015 [30:06<11:42,  2.39it/s]

 72%|███████▏  | 4337/6015 [30:06<11:41,  2.39it/s]

 72%|███████▏  | 4338/6015 [30:07<11:41,  2.39it/s]

 72%|███████▏  | 4339/6015 [30:07<11:40,  2.39it/s]

 72%|███████▏  | 4340/6015 [30:08<11:41,  2.39it/s]

 72%|███████▏  | 4341/6015 [30:08<11:40,  2.39it/s]

 72%|███████▏  | 4342/6015 [30:09<11:40,  2.39it/s]

 72%|███████▏  | 4343/6015 [30:09<11:40,  2.39it/s]

 72%|███████▏  | 4344/6015 [30:09<11:39,  2.39it/s]

 72%|███████▏  | 4345/6015 [30:10<11:40,  2.38it/s]

 72%|███████▏  | 4346/6015 [30:10<11:39,  2.39it/s]

 72%|███████▏  | 4347/6015 [30:11<11:37,  2.39it/s]

 72%|███████▏  | 4348/6015 [30:11<11:37,  2.39it/s]

 72%|███████▏  | 4349/6015 [30:12<11:37,  2.39it/s]

 72%|███████▏  | 4350/6015 [30:12<11:37,  2.39it/s]

 72%|███████▏  | 4351/6015 [30:12<11:37,  2.39it/s]

 72%|███████▏  | 4352/6015 [30:13<11:36,  2.39it/s]

 72%|███████▏  | 4353/6015 [30:13<11:36,  2.39it/s]

 72%|███████▏  | 4354/6015 [30:14<11:36,  2.39it/s]

 72%|███████▏  | 4355/6015 [30:14<11:35,  2.39it/s]

 72%|███████▏  | 4356/6015 [30:14<11:35,  2.39it/s]

 72%|███████▏  | 4357/6015 [30:15<11:34,  2.39it/s]

 72%|███████▏  | 4358/6015 [30:15<11:33,  2.39it/s]

 72%|███████▏  | 4359/6015 [30:16<11:33,  2.39it/s]

 72%|███████▏  | 4360/6015 [30:16<11:32,  2.39it/s]

 73%|███████▎  | 4361/6015 [30:17<11:32,  2.39it/s]

 73%|███████▎  | 4362/6015 [30:17<11:31,  2.39it/s]

 73%|███████▎  | 4363/6015 [30:17<11:32,  2.39it/s]

 73%|███████▎  | 4364/6015 [30:18<11:31,  2.39it/s]

 73%|███████▎  | 4365/6015 [30:18<11:33,  2.38it/s]

 73%|███████▎  | 4366/6015 [30:19<11:32,  2.38it/s]

 73%|███████▎  | 4367/6015 [30:19<11:31,  2.38it/s]

 73%|███████▎  | 4368/6015 [30:19<11:29,  2.39it/s]

 73%|███████▎  | 4369/6015 [30:20<11:30,  2.39it/s]

 73%|███████▎  | 4370/6015 [30:20<11:30,  2.38it/s]

 73%|███████▎  | 4371/6015 [30:21<11:29,  2.39it/s]

 73%|███████▎  | 4372/6015 [30:21<11:28,  2.39it/s]

 73%|███████▎  | 4373/6015 [30:22<11:31,  2.37it/s]

 73%|███████▎  | 4374/6015 [30:22<11:30,  2.37it/s]

 73%|███████▎  | 4375/6015 [30:22<11:29,  2.38it/s]

 73%|███████▎  | 4376/6015 [30:23<11:28,  2.38it/s]

 73%|███████▎  | 4377/6015 [30:23<11:27,  2.38it/s]

 73%|███████▎  | 4378/6015 [30:24<11:26,  2.38it/s]

 73%|███████▎  | 4379/6015 [30:24<11:26,  2.38it/s]

 73%|███████▎  | 4380/6015 [30:25<11:26,  2.38it/s]

 73%|███████▎  | 4381/6015 [30:25<11:25,  2.38it/s]

logging
logging the anndata

 73%|███████▎  | 4382/6015 [30:25<11:55,  2.28it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 73%|███████▎  | 4383/6015 [30:26<11:43,  2.32it/s]

 73%|███████▎  | 4384/6015 [30:26<11:34,  2.35it/s]

 73%|███████▎  | 4385/6015 [30:27<11:26,  2.38it/s]

 73%|███████▎  | 4386/6015 [30:27<11:21,  2.39it/s]

 73%|███████▎  | 4387/6015 [30:27<11:17,  2.40it/s]

 73%|███████▎  | 4388/6015 [30:28<11:14,  2.41it/s]

 73%|███████▎  | 4389/6015 [30:28<11:12,  2.42it/s]

 73%|███████▎  | 4390/6015 [30:29<11:11,  2.42it/s]

 73%|███████▎  | 4391/6015 [30:29<11:09,  2.43it/s]

 73%|███████▎  | 4392/6015 [30:30<11:09,  2.42it/s]

 73%|███████▎  | 4393/6015 [30:30<11:08,  2.43it/s]

 73%|███████▎  | 4394/6015 [30:30<11:07,  2.43it/s]

 73%|███████▎  | 4395/6015 [30:31<11:07,  2.43it/s]

 73%|███████▎  | 4396/6015 [30:31<11:06,  2.43it/s]

 73%|███████▎  | 4397/6015 [30:32<11:07,  2.42it/s]

 73%|███████▎  | 4398/6015 [30:32<11:06,  2.43it/s]

 73%|███████▎  | 4399/6015 [30:32<11:05,  2.43it/s]

 73%|███████▎  | 4400/6015 [30:33<11:05,  2.43it/s]

 73%|███████▎  | 4401/6015 [30:33<11:05,  2.43it/s]

 73%|███████▎  | 4402/6015 [30:34<11:03,  2.43it/s]

 73%|███████▎  | 4403/6015 [30:34<11:03,  2.43it/s]

 73%|███████▎  | 4404/6015 [30:34<11:03,  2.43it/s]

 73%|███████▎  | 4405/6015 [30:35<11:03,  2.43it/s]

 73%|███████▎  | 4406/6015 [30:35<11:02,  2.43it/s]

 73%|███████▎  | 4407/6015 [30:36<11:02,  2.43it/s]

 73%|███████▎  | 4408/6015 [30:36<11:02,  2.42it/s]

 73%|███████▎  | 4409/6015 [30:37<11:01,  2.43it/s]

 73%|███████▎  | 4410/6015 [30:37<11:01,  2.43it/s]

 73%|███████▎  | 4411/6015 [30:37<11:01,  2.43it/s]

 73%|███████▎  | 4412/6015 [30:38<11:00,  2.43it/s]

 73%|███████▎  | 4413/6015 [30:38<10:59,  2.43it/s]

 73%|███████▎  | 4414/6015 [30:39<10:59,  2.43it/s]

 73%|███████▎  | 4415/6015 [30:39<11:03,  2.41it/s]

 73%|███████▎  | 4416/6015 [30:39<11:01,  2.42it/s]

 73%|███████▎  | 4417/6015 [30:40<11:00,  2.42it/s]

 73%|███████▎  | 4418/6015 [30:40<11:00,  2.42it/s]

 73%|███████▎  | 4419/6015 [30:41<10:59,  2.42it/s]

 73%|███████▎  | 4420/6015 [30:41<10:59,  2.42it/s]

 73%|███████▎  | 4421/6015 [30:41<10:58,  2.42it/s]

 74%|███████▎  | 4422/6015 [30:42<10:57,  2.42it/s]

 74%|███████▎  | 4423/6015 [30:42<10:56,  2.42it/s]

 74%|███████▎  | 4424/6015 [30:43<10:55,  2.43it/s]

 74%|███████▎  | 4425/6015 [30:43<10:56,  2.42it/s]

 74%|███████▎  | 4426/6015 [30:44<10:55,  2.42it/s]

 74%|███████▎  | 4427/6015 [30:44<10:55,  2.42it/s]

 74%|███████▎  | 4428/6015 [30:44<10:54,  2.43it/s]

 74%|███████▎  | 4429/6015 [30:45<10:53,  2.43it/s]

 74%|███████▎  | 4430/6015 [30:45<10:53,  2.43it/s]

 74%|███████▎  | 4431/6015 [30:46<10:52,  2.43it/s]

 74%|███████▎  | 4432/6015 [30:46<10:51,  2.43it/s]

 74%|███████▎  | 4433/6015 [30:46<10:51,  2.43it/s]

 74%|███████▎  | 4434/6015 [30:47<10:51,  2.43it/s]

 74%|███████▎  | 4435/6015 [30:47<10:51,  2.43it/s]

 74%|███████▎  | 4436/6015 [30:48<10:51,  2.42it/s]

 74%|███████▍  | 4437/6015 [30:48<10:50,  2.43it/s]

 74%|███████▍  | 4438/6015 [30:48<10:49,  2.43it/s]

 74%|███████▍  | 4439/6015 [30:49<10:49,  2.43it/s]

 74%|███████▍  | 4440/6015 [30:49<10:49,  2.42it/s]

 74%|███████▍  | 4441/6015 [30:50<10:49,  2.42it/s]

 74%|███████▍  | 4442/6015 [30:50<10:48,  2.42it/s]

 74%|███████▍  | 4443/6015 [30:51<10:48,  2.42it/s]

 74%|███████▍  | 4444/6015 [30:51<10:48,  2.42it/s]

 74%|███████▍  | 4445/6015 [30:51<10:47,  2.42it/s]

 74%|███████▍  | 4446/6015 [30:52<10:47,  2.42it/s]

 74%|███████▍  | 4447/6015 [30:52<10:47,  2.42it/s]

 74%|███████▍  | 4448/6015 [30:53<10:46,  2.42it/s]

 74%|███████▍  | 4449/6015 [30:53<10:45,  2.42it/s]

 74%|███████▍  | 4450/6015 [30:53<10:46,  2.42it/s]

 74%|███████▍  | 4451/6015 [30:54<10:46,  2.42it/s]

 74%|███████▍  | 4452/6015 [30:54<10:45,  2.42it/s]

 74%|███████▍  | 4453/6015 [30:55<10:44,  2.42it/s]

 74%|███████▍  | 4454/6015 [30:55<10:46,  2.42it/s]

 74%|███████▍  | 4455/6015 [30:56<10:45,  2.42it/s]

 74%|███████▍  | 4456/6015 [30:56<10:44,  2.42it/s]

 74%|███████▍  | 4457/6015 [30:56<10:46,  2.41it/s]

 74%|███████▍  | 4458/6015 [30:57<10:45,  2.41it/s]

 74%|███████▍  | 4459/6015 [30:57<10:44,  2.42it/s]

 74%|███████▍  | 4460/6015 [30:58<10:43,  2.42it/s]

 74%|███████▍  | 4461/6015 [30:58<10:42,  2.42it/s]

 74%|███████▍  | 4462/6015 [30:58<10:42,  2.42it/s]

 74%|███████▍  | 4463/6015 [30:59<10:41,  2.42it/s]

 74%|███████▍  | 4464/6015 [30:59<10:41,  2.42it/s]

 74%|███████▍  | 4465/6015 [31:00<10:41,  2.42it/s]

 74%|███████▍  | 4466/6015 [31:00<10:41,  2.42it/s]

 74%|███████▍  | 4467/6015 [31:00<10:40,  2.42it/s]

 74%|███████▍  | 4468/6015 [31:01<10:39,  2.42it/s]

 74%|███████▍  | 4469/6015 [31:01<10:39,  2.42it/s]

 74%|███████▍  | 4470/6015 [31:02<10:40,  2.41it/s]

 74%|███████▍  | 4471/6015 [31:02<10:40,  2.41it/s]

 74%|███████▍  | 4472/6015 [31:03<10:39,  2.41it/s]

 74%|███████▍  | 4473/6015 [31:03<10:39,  2.41it/s]

 74%|███████▍  | 4474/6015 [31:03<10:38,  2.41it/s]

 74%|███████▍  | 4475/6015 [31:04<10:38,  2.41it/s]

 74%|███████▍  | 4476/6015 [31:04<10:37,  2.41it/s]

 74%|███████▍  | 4477/6015 [31:05<10:37,  2.41it/s]

 74%|███████▍  | 4478/6015 [31:05<10:36,  2.41it/s]

 74%|███████▍  | 4479/6015 [31:05<10:36,  2.41it/s]

 74%|███████▍  | 4480/6015 [31:06<10:37,  2.41it/s]

 74%|███████▍  | 4481/6015 [31:06<10:35,  2.41it/s]

 75%|███████▍  | 4482/6015 [31:07<10:34,  2.41it/s]

 75%|███████▍  | 4483/6015 [31:07<10:34,  2.42it/s]

 75%|███████▍  | 4484/6015 [31:08<10:33,  2.41it/s]

 75%|███████▍  | 4485/6015 [31:08<10:33,  2.41it/s]

 75%|███████▍  | 4486/6015 [31:08<10:32,  2.42it/s]

 75%|███████▍  | 4487/6015 [31:09<10:33,  2.41it/s]

 75%|███████▍  | 4488/6015 [31:09<10:32,  2.42it/s]

 75%|███████▍  | 4489/6015 [31:10<10:31,  2.42it/s]

 75%|███████▍  | 4490/6015 [31:10<10:30,  2.42it/s]

 75%|███████▍  | 4491/6015 [31:10<10:29,  2.42it/s]

 75%|███████▍  | 4492/6015 [31:11<10:29,  2.42it/s]

 75%|███████▍  | 4493/6015 [31:11<10:29,  2.42it/s]

 75%|███████▍  | 4494/6015 [31:12<10:28,  2.42it/s]

 75%|███████▍  | 4495/6015 [31:12<10:29,  2.42it/s]

 75%|███████▍  | 4496/6015 [31:12<10:27,  2.42it/s]

 75%|███████▍  | 4497/6015 [31:13<10:26,  2.42it/s]

 75%|███████▍  | 4498/6015 [31:13<10:26,  2.42it/s]

 75%|███████▍  | 4499/6015 [31:14<10:26,  2.42it/s]

 75%|███████▍  | 4500/6015 [31:14<10:26,  2.42it/s]

 75%|███████▍  | 4501/6015 [31:15<10:26,  2.42it/s]

 75%|███████▍  | 4502/6015 [31:15<10:26,  2.42it/s]

 75%|███████▍  | 4503/6015 [31:15<10:25,  2.42it/s]

 75%|███████▍  | 4504/6015 [31:16<10:25,  2.42it/s]

 75%|███████▍  | 4505/6015 [31:16<10:25,  2.42it/s]

 75%|███████▍  | 4506/6015 [31:17<10:24,  2.42it/s]

 75%|███████▍  | 4507/6015 [31:17<10:23,  2.42it/s]

 75%|███████▍  | 4508/6015 [31:17<10:23,  2.42it/s]

 75%|███████▍  | 4509/6015 [31:18<10:25,  2.41it/s]

 75%|███████▍  | 4510/6015 [31:18<10:24,  2.41it/s]

 75%|███████▍  | 4511/6015 [31:19<10:23,  2.41it/s]

 75%|███████▌  | 4512/6015 [31:19<10:22,  2.42it/s]

 75%|███████▌  | 4513/6015 [31:20<10:21,  2.42it/s]

 75%|███████▌  | 4514/6015 [31:20<10:21,  2.41it/s]

 75%|███████▌  | 4515/6015 [31:20<10:22,  2.41it/s]

 75%|███████▌  | 4516/6015 [31:21<10:20,  2.41it/s]

 75%|███████▌  | 4517/6015 [31:21<10:20,  2.41it/s]

 75%|███████▌  | 4518/6015 [31:22<10:19,  2.42it/s]

 75%|███████▌  | 4519/6015 [31:22<10:18,  2.42it/s]

 75%|███████▌  | 4520/6015 [31:22<10:17,  2.42it/s]

 75%|███████▌  | 4521/6015 [31:23<10:17,  2.42it/s]

 75%|███████▌  | 4522/6015 [31:23<10:16,  2.42it/s]

 75%|███████▌  | 4523/6015 [31:24<10:16,  2.42it/s]

 75%|███████▌  | 4524/6015 [31:24<10:16,  2.42it/s]

 75%|███████▌  | 4525/6015 [31:24<10:16,  2.42it/s]

 75%|███████▌  | 4526/6015 [31:25<10:15,  2.42it/s]

 75%|███████▌  | 4527/6015 [31:25<10:14,  2.42it/s]

 75%|███████▌  | 4528/6015 [31:26<10:15,  2.42it/s]

 75%|███████▌  | 4529/6015 [31:26<10:14,  2.42it/s]

 75%|███████▌  | 4530/6015 [31:27<10:14,  2.42it/s]

 75%|███████▌  | 4531/6015 [31:27<10:13,  2.42it/s]

 75%|███████▌  | 4532/6015 [31:27<10:12,  2.42it/s]

 75%|███████▌  | 4533/6015 [31:28<10:11,  2.42it/s]

 75%|███████▌  | 4534/6015 [31:28<10:11,  2.42it/s]

 75%|███████▌  | 4535/6015 [31:29<10:10,  2.42it/s]

 75%|███████▌  | 4536/6015 [31:29<10:10,  2.42it/s]

 75%|███████▌  | 4537/6015 [31:29<10:09,  2.42it/s]

 75%|███████▌  | 4538/6015 [31:30<10:09,  2.42it/s]

 75%|███████▌  | 4539/6015 [31:30<10:09,  2.42it/s]

 75%|███████▌  | 4540/6015 [31:31<10:09,  2.42it/s]

 75%|███████▌  | 4541/6015 [31:31<10:08,  2.42it/s]

 76%|███████▌  | 4542/6015 [31:32<10:08,  2.42it/s]

 76%|███████▌  | 4543/6015 [31:32<10:08,  2.42it/s]

 76%|███████▌  | 4544/6015 [31:32<10:07,  2.42it/s]

 76%|███████▌  | 4545/6015 [31:33<10:07,  2.42it/s]

 76%|███████▌  | 4546/6015 [31:33<10:07,  2.42it/s]

 76%|███████▌  | 4547/6015 [31:34<10:07,  2.42it/s]

 76%|███████▌  | 4548/6015 [31:34<10:06,  2.42it/s]

 76%|███████▌  | 4549/6015 [31:34<10:06,  2.42it/s]

 76%|███████▌  | 4550/6015 [31:35<10:09,  2.40it/s]

 76%|███████▌  | 4551/6015 [31:35<10:08,  2.41it/s]

 76%|███████▌  | 4552/6015 [31:36<10:07,  2.41it/s]

 76%|███████▌  | 4553/6015 [31:36<10:05,  2.41it/s]

 76%|███████▌  | 4554/6015 [31:36<10:05,  2.41it/s]

 76%|███████▌  | 4555/6015 [31:37<10:05,  2.41it/s]

 76%|███████▌  | 4556/6015 [31:37<10:04,  2.41it/s]

 76%|███████▌  | 4557/6015 [31:38<10:03,  2.42it/s]

 76%|███████▌  | 4558/6015 [31:38<10:02,  2.42it/s]

 76%|███████▌  | 4559/6015 [31:39<10:01,  2.42it/s]

 76%|███████▌  | 4560/6015 [31:39<10:00,  2.42it/s]

 76%|███████▌  | 4561/6015 [31:39<10:00,  2.42it/s]

 76%|███████▌  | 4562/6015 [31:40<10:00,  2.42it/s]

 76%|███████▌  | 4563/6015 [31:40<10:00,  2.42it/s]

 76%|███████▌  | 4564/6015 [31:41<10:00,  2.41it/s]

 76%|███████▌  | 4565/6015 [31:41<10:00,  2.42it/s]

 76%|███████▌  | 4566/6015 [31:41<09:59,  2.42it/s]

 76%|███████▌  | 4567/6015 [31:42<09:58,  2.42it/s]

 76%|███████▌  | 4568/6015 [31:42<09:58,  2.42it/s]

 76%|███████▌  | 4569/6015 [31:43<09:57,  2.42it/s]

 76%|███████▌  | 4570/6015 [31:43<09:57,  2.42it/s]

 76%|███████▌  | 4571/6015 [31:44<09:57,  2.42it/s]

 76%|███████▌  | 4572/6015 [31:44<09:57,  2.42it/s]

 76%|███████▌  | 4573/6015 [31:44<09:56,  2.42it/s]

 76%|███████▌  | 4574/6015 [31:45<09:56,  2.42it/s]

 76%|███████▌  | 4575/6015 [31:45<09:55,  2.42it/s]

 76%|███████▌  | 4576/6015 [31:46<09:55,  2.42it/s]

 76%|███████▌  | 4577/6015 [31:46<09:54,  2.42it/s]

 76%|███████▌  | 4578/6015 [31:46<09:55,  2.41it/s]

 76%|███████▌  | 4579/6015 [31:47<09:54,  2.41it/s]

 76%|███████▌  | 4580/6015 [31:47<09:54,  2.41it/s]

 76%|███████▌  | 4581/6015 [31:48<09:53,  2.41it/s]

 76%|███████▌  | 4582/6015 [31:48<09:53,  2.41it/s]

 76%|███████▌  | 4583/6015 [31:48<09:52,  2.42it/s]

 76%|███████▌  | 4584/6015 [31:49<09:52,  2.42it/s]

 76%|███████▌  | 4585/6015 [31:49<09:51,  2.42it/s]

 76%|███████▌  | 4586/6015 [31:50<09:51,  2.42it/s]

 76%|███████▋  | 4587/6015 [31:50<09:50,  2.42it/s]

 76%|███████▋  | 4588/6015 [31:51<09:50,  2.42it/s]

 76%|███████▋  | 4589/6015 [31:51<09:49,  2.42it/s]

 76%|███████▋  | 4590/6015 [31:51<09:49,  2.42it/s]

 76%|███████▋  | 4591/6015 [31:52<09:49,  2.42it/s]

 76%|███████▋  | 4592/6015 [31:52<09:49,  2.41it/s]

 76%|███████▋  | 4593/6015 [31:53<09:48,  2.41it/s]

 76%|███████▋  | 4594/6015 [31:53<09:48,  2.42it/s]

 76%|███████▋  | 4595/6015 [31:53<09:47,  2.42it/s]

 76%|███████▋  | 4596/6015 [31:54<09:47,  2.42it/s]

 76%|███████▋  | 4597/6015 [31:54<09:47,  2.41it/s]

 76%|███████▋  | 4598/6015 [31:55<09:47,  2.41it/s]

 76%|███████▋  | 4599/6015 [31:55<09:46,  2.41it/s]

 76%|███████▋  | 4600/6015 [31:56<09:45,  2.42it/s]

 76%|███████▋  | 4601/6015 [31:56<09:45,  2.41it/s]

 77%|███████▋  | 4602/6015 [31:56<09:45,  2.41it/s]

 77%|███████▋  | 4603/6015 [31:57<09:44,  2.41it/s]

 77%|███████▋  | 4604/6015 [31:57<09:44,  2.41it/s]

 77%|███████▋  | 4605/6015 [31:58<09:43,  2.41it/s]

 77%|███████▋  | 4606/6015 [31:58<09:43,  2.42it/s]

 77%|███████▋  | 4607/6015 [31:58<09:42,  2.42it/s]

 77%|███████▋  | 4608/6015 [31:59<09:42,  2.42it/s]

 77%|███████▋  | 4609/6015 [31:59<09:42,  2.41it/s]

 77%|███████▋  | 4610/6015 [32:00<09:41,  2.42it/s]

 77%|███████▋  | 4611/6015 [32:00<09:41,  2.41it/s]

 77%|███████▋  | 4612/6015 [32:00<09:41,  2.41it/s]

 77%|███████▋  | 4613/6015 [32:01<09:41,  2.41it/s]

 77%|███████▋  | 4614/6015 [32:01<09:41,  2.41it/s]

 77%|███████▋  | 4615/6015 [32:02<09:40,  2.41it/s]

 77%|███████▋  | 4616/6015 [32:02<09:40,  2.41it/s]

 77%|███████▋  | 4617/6015 [32:03<09:39,  2.41it/s]

 77%|███████▋  | 4618/6015 [32:03<09:38,  2.41it/s]

 77%|███████▋  | 4619/6015 [32:03<09:38,  2.41it/s]

 77%|███████▋  | 4620/6015 [32:04<09:38,  2.41it/s]

 77%|███████▋  | 4621/6015 [32:04<09:38,  2.41it/s]

 77%|███████▋  | 4622/6015 [32:05<09:38,  2.41it/s]

 77%|███████▋  | 4623/6015 [32:05<09:37,  2.41it/s]

 77%|███████▋  | 4624/6015 [32:05<09:36,  2.41it/s]

 77%|███████▋  | 4625/6015 [32:06<09:36,  2.41it/s]

 77%|███████▋  | 4626/6015 [32:06<09:35,  2.41it/s]

 77%|███████▋  | 4627/6015 [32:07<09:35,  2.41it/s]

 77%|███████▋  | 4628/6015 [32:07<09:35,  2.41it/s]

 77%|███████▋  | 4629/6015 [32:08<09:35,  2.41it/s]

 77%|███████▋  | 4630/6015 [32:08<09:34,  2.41it/s]

 77%|███████▋  | 4631/6015 [32:08<09:34,  2.41it/s]

 77%|███████▋  | 4632/6015 [32:09<09:34,  2.41it/s]

 77%|███████▋  | 4633/6015 [32:09<09:33,  2.41it/s]

 77%|███████▋  | 4634/6015 [32:10<09:32,  2.41it/s]

 77%|███████▋  | 4635/6015 [32:10<09:32,  2.41it/s]

 77%|███████▋  | 4636/6015 [32:10<09:31,  2.41it/s]

 77%|███████▋  | 4637/6015 [32:11<09:30,  2.41it/s]

 77%|███████▋  | 4638/6015 [32:11<09:30,  2.42it/s]

 77%|███████▋  | 4639/6015 [32:12<09:29,  2.41it/s]

 77%|███████▋  | 4640/6015 [32:12<09:29,  2.41it/s]

 77%|███████▋  | 4641/6015 [32:13<09:29,  2.41it/s]

 77%|███████▋  | 4642/6015 [32:13<09:29,  2.41it/s]

 77%|███████▋  | 4643/6015 [32:13<09:28,  2.41it/s]

 77%|███████▋  | 4644/6015 [32:14<09:28,  2.41it/s]

 77%|███████▋  | 4645/6015 [32:14<09:27,  2.41it/s]

 77%|███████▋  | 4646/6015 [32:15<09:32,  2.39it/s]

 77%|███████▋  | 4647/6015 [32:15<09:29,  2.40it/s]

 77%|███████▋  | 4648/6015 [32:15<09:28,  2.40it/s]

 77%|███████▋  | 4649/6015 [32:16<09:28,  2.40it/s]

 77%|███████▋  | 4650/6015 [32:16<09:26,  2.41it/s]

 77%|███████▋  | 4651/6015 [32:17<09:25,  2.41it/s]

 77%|███████▋  | 4652/6015 [32:17<09:24,  2.41it/s]

 77%|███████▋  | 4653/6015 [32:18<09:24,  2.41it/s]

 77%|███████▋  | 4654/6015 [32:18<09:24,  2.41it/s]

 77%|███████▋  | 4655/6015 [32:18<09:24,  2.41it/s]

 77%|███████▋  | 4656/6015 [32:19<09:23,  2.41it/s]

 77%|███████▋  | 4657/6015 [32:19<09:23,  2.41it/s]

 77%|███████▋  | 4658/6015 [32:20<09:22,  2.41it/s]

 77%|███████▋  | 4659/6015 [32:20<09:23,  2.41it/s]

 77%|███████▋  | 4660/6015 [32:20<09:23,  2.41it/s]

 77%|███████▋  | 4661/6015 [32:21<09:22,  2.41it/s]

 78%|███████▊  | 4662/6015 [32:21<09:21,  2.41it/s]

 78%|███████▊  | 4663/6015 [32:22<09:20,  2.41it/s]

 78%|███████▊  | 4664/6015 [32:22<09:20,  2.41it/s]

 78%|███████▊  | 4665/6015 [32:22<09:20,  2.41it/s]

 78%|███████▊  | 4666/6015 [32:23<09:19,  2.41it/s]

 78%|███████▊  | 4667/6015 [32:23<09:19,  2.41it/s]

 78%|███████▊  | 4668/6015 [32:24<09:19,  2.41it/s]

 78%|███████▊  | 4669/6015 [32:24<09:18,  2.41it/s]

 78%|███████▊  | 4670/6015 [32:25<09:18,  2.41it/s]

 78%|███████▊  | 4671/6015 [32:25<09:17,  2.41it/s]

 78%|███████▊  | 4672/6015 [32:25<09:17,  2.41it/s]

 78%|███████▊  | 4673/6015 [32:26<09:16,  2.41it/s]

 78%|███████▊  | 4674/6015 [32:26<09:16,  2.41it/s]

 78%|███████▊  | 4675/6015 [32:27<09:16,  2.41it/s]

 78%|███████▊  | 4676/6015 [32:27<09:16,  2.41it/s]

 78%|███████▊  | 4677/6015 [32:27<09:15,  2.41it/s]

 78%|███████▊  | 4678/6015 [32:28<09:15,  2.41it/s]

 78%|███████▊  | 4679/6015 [32:28<09:15,  2.41it/s]

 78%|███████▊  | 4680/6015 [32:29<09:15,  2.40it/s]

 78%|███████▊  | 4681/6015 [32:29<09:15,  2.40it/s]

 78%|███████▊  | 4682/6015 [32:30<09:14,  2.40it/s]

 78%|███████▊  | 4683/6015 [32:30<09:13,  2.41it/s]

 78%|███████▊  | 4684/6015 [32:30<09:12,  2.41it/s]

 78%|███████▊  | 4685/6015 [32:31<09:12,  2.41it/s]

 78%|███████▊  | 4686/6015 [32:31<09:11,  2.41it/s]

 78%|███████▊  | 4687/6015 [32:32<09:11,  2.41it/s]

 78%|███████▊  | 4688/6015 [32:32<09:11,  2.41it/s]

 78%|███████▊  | 4689/6015 [32:32<09:11,  2.41it/s]

 78%|███████▊  | 4690/6015 [32:33<09:10,  2.41it/s]

 78%|███████▊  | 4691/6015 [32:33<09:09,  2.41it/s]

 78%|███████▊  | 4692/6015 [32:34<09:09,  2.41it/s]

 78%|███████▊  | 4693/6015 [32:34<09:08,  2.41it/s]

 78%|███████▊  | 4694/6015 [32:35<09:08,  2.41it/s]

 78%|███████▊  | 4695/6015 [32:35<09:08,  2.41it/s]

 78%|███████▊  | 4696/6015 [32:35<09:07,  2.41it/s]

 78%|███████▊  | 4697/6015 [32:36<09:07,  2.41it/s]

 78%|███████▊  | 4698/6015 [32:36<09:06,  2.41it/s]

 78%|███████▊  | 4699/6015 [32:37<09:06,  2.41it/s]

 78%|███████▊  | 4700/6015 [32:37<09:06,  2.40it/s]

 78%|███████▊  | 4701/6015 [32:37<09:06,  2.40it/s]

 78%|███████▊  | 4702/6015 [32:38<09:07,  2.40it/s]

 78%|███████▊  | 4703/6015 [32:38<09:06,  2.40it/s]

 78%|███████▊  | 4704/6015 [32:39<09:05,  2.40it/s]

 78%|███████▊  | 4705/6015 [32:39<09:04,  2.40it/s]

 78%|███████▊  | 4706/6015 [32:40<09:04,  2.40it/s]

 78%|███████▊  | 4707/6015 [32:40<09:05,  2.40it/s]

 78%|███████▊  | 4708/6015 [32:40<09:04,  2.40it/s]

 78%|███████▊  | 4709/6015 [32:41<09:03,  2.40it/s]

 78%|███████▊  | 4710/6015 [32:41<09:03,  2.40it/s]

 78%|███████▊  | 4711/6015 [32:42<09:02,  2.40it/s]

 78%|███████▊  | 4712/6015 [32:42<09:01,  2.40it/s]

 78%|███████▊  | 4713/6015 [32:42<09:00,  2.41it/s]

 78%|███████▊  | 4714/6015 [32:43<09:01,  2.40it/s]

 78%|███████▊  | 4715/6015 [32:43<09:00,  2.40it/s]

 78%|███████▊  | 4716/6015 [32:44<09:00,  2.40it/s]

 78%|███████▊  | 4717/6015 [32:44<08:59,  2.41it/s]

 78%|███████▊  | 4718/6015 [32:45<08:59,  2.41it/s]

 78%|███████▊  | 4719/6015 [32:45<08:58,  2.41it/s]

 78%|███████▊  | 4720/6015 [32:45<08:58,  2.41it/s]

 78%|███████▊  | 4721/6015 [32:46<08:58,  2.40it/s]

 79%|███████▊  | 4722/6015 [32:46<08:58,  2.40it/s]

 79%|███████▊  | 4723/6015 [32:47<08:57,  2.40it/s]

 79%|███████▊  | 4724/6015 [32:47<08:56,  2.40it/s]

 79%|███████▊  | 4725/6015 [32:47<08:56,  2.41it/s]

 79%|███████▊  | 4726/6015 [32:48<08:55,  2.41it/s]

 79%|███████▊  | 4727/6015 [32:48<08:55,  2.41it/s]

 79%|███████▊  | 4728/6015 [32:49<08:55,  2.40it/s]

 79%|███████▊  | 4729/6015 [32:49<08:55,  2.40it/s]

 79%|███████▊  | 4730/6015 [32:50<08:55,  2.40it/s]

 79%|███████▊  | 4731/6015 [32:50<08:54,  2.40it/s]

 79%|███████▊  | 4732/6015 [32:50<08:53,  2.40it/s]

 79%|███████▊  | 4733/6015 [32:51<08:54,  2.40it/s]

 79%|███████▊  | 4734/6015 [32:51<08:53,  2.40it/s]

 79%|███████▊  | 4735/6015 [32:52<08:54,  2.39it/s]

 79%|███████▊  | 4736/6015 [32:52<08:53,  2.40it/s]

 79%|███████▉  | 4737/6015 [32:52<08:53,  2.39it/s]

 79%|███████▉  | 4738/6015 [32:53<08:52,  2.40it/s]

 79%|███████▉  | 4739/6015 [32:53<08:53,  2.39it/s]

 79%|███████▉  | 4740/6015 [32:54<08:51,  2.40it/s]

 79%|███████▉  | 4741/6015 [32:54<08:50,  2.40it/s]

 79%|███████▉  | 4742/6015 [32:55<08:49,  2.40it/s]

 79%|███████▉  | 4743/6015 [32:55<08:50,  2.40it/s]

 79%|███████▉  | 4744/6015 [32:55<08:49,  2.40it/s]

 79%|███████▉  | 4745/6015 [32:56<08:48,  2.40it/s]

 79%|███████▉  | 4746/6015 [32:56<08:47,  2.40it/s]

 79%|███████▉  | 4747/6015 [32:57<08:48,  2.40it/s]

 79%|███████▉  | 4748/6015 [32:57<08:47,  2.40it/s]

 79%|███████▉  | 4749/6015 [32:57<08:46,  2.40it/s]

 79%|███████▉  | 4750/6015 [32:58<08:47,  2.40it/s]

 79%|███████▉  | 4751/6015 [32:58<08:46,  2.40it/s]

 79%|███████▉  | 4752/6015 [32:59<08:45,  2.40it/s]

 79%|███████▉  | 4753/6015 [32:59<08:44,  2.40it/s]

 79%|███████▉  | 4754/6015 [33:00<08:44,  2.40it/s]

 79%|███████▉  | 4755/6015 [33:00<08:44,  2.40it/s]

 79%|███████▉  | 4756/6015 [33:00<08:43,  2.40it/s]

 79%|███████▉  | 4757/6015 [33:01<08:43,  2.40it/s]

 79%|███████▉  | 4758/6015 [33:01<08:46,  2.39it/s]

 79%|███████▉  | 4759/6015 [33:02<08:44,  2.39it/s]

 79%|███████▉  | 4760/6015 [33:02<08:43,  2.40it/s]

 79%|███████▉  | 4761/6015 [33:02<08:42,  2.40it/s]

 79%|███████▉  | 4762/6015 [33:03<08:42,  2.40it/s]

 79%|███████▉  | 4763/6015 [33:03<08:41,  2.40it/s]

 79%|███████▉  | 4764/6015 [33:04<08:41,  2.40it/s]

 79%|███████▉  | 4765/6015 [33:04<08:39,  2.40it/s]

 79%|███████▉  | 4766/6015 [33:05<08:39,  2.41it/s]

 79%|███████▉  | 4767/6015 [33:05<08:39,  2.40it/s]

 79%|███████▉  | 4768/6015 [33:05<08:39,  2.40it/s]

 79%|███████▉  | 4769/6015 [33:06<08:38,  2.40it/s]

 79%|███████▉  | 4770/6015 [33:06<08:38,  2.40it/s]

 79%|███████▉  | 4771/6015 [33:07<08:37,  2.40it/s]

 79%|███████▉  | 4772/6015 [33:07<08:37,  2.40it/s]

 79%|███████▉  | 4773/6015 [33:07<08:37,  2.40it/s]

 79%|███████▉  | 4774/6015 [33:08<08:36,  2.40it/s]

 79%|███████▉  | 4775/6015 [33:08<08:35,  2.41it/s]

 79%|███████▉  | 4776/6015 [33:09<08:35,  2.40it/s]

 79%|███████▉  | 4777/6015 [33:09<08:34,  2.40it/s]

 79%|███████▉  | 4778/6015 [33:09<08:34,  2.40it/s]

 79%|███████▉  | 4779/6015 [33:10<08:34,  2.40it/s]

 79%|███████▉  | 4780/6015 [33:10<08:33,  2.40it/s]

 79%|███████▉  | 4781/6015 [33:11<08:33,  2.40it/s]

 80%|███████▉  | 4782/6015 [33:11<08:33,  2.40it/s]

 80%|███████▉  | 4783/6015 [33:12<08:32,  2.40it/s]

 80%|███████▉  | 4784/6015 [33:12<08:32,  2.40it/s]

 80%|███████▉  | 4785/6015 [33:12<08:31,  2.41it/s]

 80%|███████▉  | 4786/6015 [33:13<08:31,  2.40it/s]

 80%|███████▉  | 4787/6015 [33:13<08:32,  2.40it/s]

 80%|███████▉  | 4788/6015 [33:14<08:31,  2.40it/s]

 80%|███████▉  | 4789/6015 [33:14<08:30,  2.40it/s]

 80%|███████▉  | 4790/6015 [33:14<08:29,  2.40it/s]

 80%|███████▉  | 4791/6015 [33:15<08:29,  2.40it/s]

 80%|███████▉  | 4792/6015 [33:15<08:29,  2.40it/s]

 80%|███████▉  | 4793/6015 [33:16<08:28,  2.40it/s]

 80%|███████▉  | 4794/6015 [33:16<08:28,  2.40it/s]

 80%|███████▉  | 4795/6015 [33:17<08:28,  2.40it/s]

 80%|███████▉  | 4796/6015 [33:17<08:27,  2.40it/s]

 80%|███████▉  | 4797/6015 [33:17<08:26,  2.40it/s]

 80%|███████▉  | 4798/6015 [33:18<08:26,  2.40it/s]

 80%|███████▉  | 4799/6015 [33:18<08:25,  2.40it/s]

 80%|███████▉  | 4800/6015 [33:19<08:25,  2.40it/s]

 80%|███████▉  | 4801/6015 [33:19<08:26,  2.40it/s]

 80%|███████▉  | 4802/6015 [33:19<08:25,  2.40it/s]

 80%|███████▉  | 4803/6015 [33:20<08:24,  2.40it/s]

 80%|███████▉  | 4804/6015 [33:20<08:24,  2.40it/s]

 80%|███████▉  | 4805/6015 [33:21<08:23,  2.40it/s]

 80%|███████▉  | 4806/6015 [33:21<08:23,  2.40it/s]

 80%|███████▉  | 4807/6015 [33:22<08:22,  2.40it/s]

 80%|███████▉  | 4808/6015 [33:22<08:22,  2.40it/s]

 80%|███████▉  | 4809/6015 [33:22<08:22,  2.40it/s]

 80%|███████▉  | 4810/6015 [33:23<08:21,  2.40it/s]

 80%|███████▉  | 4811/6015 [33:23<08:21,  2.40it/s]

 80%|████████  | 4812/6015 [33:24<08:20,  2.40it/s]

 80%|████████  | 4813/6015 [33:24<08:20,  2.40it/s]

 80%|████████  | 4814/6015 [33:24<08:19,  2.40it/s]

 80%|████████  | 4815/6015 [33:25<08:19,  2.40it/s]

 80%|████████  | 4816/6015 [33:25<08:19,  2.40it/s]

 80%|████████  | 4817/6015 [33:26<08:19,  2.40it/s]

 80%|████████  | 4818/6015 [33:26<08:18,  2.40it/s]

 80%|████████  | 4819/6015 [33:27<08:18,  2.40it/s]

 80%|████████  | 4820/6015 [33:27<08:17,  2.40it/s]

 80%|████████  | 4821/6015 [33:27<08:17,  2.40it/s]

 80%|████████  | 4822/6015 [33:28<08:16,  2.40it/s]

 80%|████████  | 4823/6015 [33:28<08:16,  2.40it/s]

 80%|████████  | 4824/6015 [33:29<08:15,  2.40it/s]

 80%|████████  | 4825/6015 [33:29<08:16,  2.40it/s]

 80%|████████  | 4826/6015 [33:29<08:16,  2.40it/s]

 80%|████████  | 4827/6015 [33:30<08:15,  2.40it/s]

 80%|████████  | 4828/6015 [33:30<08:14,  2.40it/s]

 80%|████████  | 4829/6015 [33:31<08:14,  2.40it/s]

 80%|████████  | 4830/6015 [33:31<08:13,  2.40it/s]

 80%|████████  | 4831/6015 [33:32<08:13,  2.40it/s]

 80%|████████  | 4832/6015 [33:32<08:12,  2.40it/s]

 80%|████████  | 4833/6015 [33:32<08:12,  2.40it/s]

 80%|████████  | 4834/6015 [33:33<08:11,  2.40it/s]

 80%|████████  | 4835/6015 [33:33<08:11,  2.40it/s]

 80%|████████  | 4836/6015 [33:34<08:11,  2.40it/s]

 80%|████████  | 4837/6015 [33:34<08:11,  2.40it/s]

 80%|████████  | 4838/6015 [33:34<08:10,  2.40it/s]

 80%|████████  | 4839/6015 [33:35<08:10,  2.40it/s]

 80%|████████  | 4840/6015 [33:35<08:09,  2.40it/s]

 80%|████████  | 4841/6015 [33:36<08:09,  2.40it/s]

 80%|████████  | 4842/6015 [33:36<08:12,  2.38it/s]

 81%|████████  | 4843/6015 [33:37<08:10,  2.39it/s]

 81%|████████  | 4844/6015 [33:37<08:10,  2.39it/s]

 81%|████████  | 4845/6015 [33:37<08:09,  2.39it/s]

 81%|████████  | 4846/6015 [33:38<08:08,  2.39it/s]

 81%|████████  | 4847/6015 [33:38<08:07,  2.40it/s]

 81%|████████  | 4848/6015 [33:39<08:06,  2.40it/s]

 81%|████████  | 4849/6015 [33:39<08:06,  2.40it/s]

 81%|████████  | 4850/6015 [33:39<08:06,  2.40it/s]

 81%|████████  | 4851/6015 [33:40<08:05,  2.40it/s]

 81%|████████  | 4852/6015 [33:40<08:05,  2.40it/s]

 81%|████████  | 4853/6015 [33:41<08:04,  2.40it/s]

 81%|████████  | 4854/6015 [33:41<08:03,  2.40it/s]

 81%|████████  | 4855/6015 [33:42<08:02,  2.40it/s]

 81%|████████  | 4856/6015 [33:42<08:02,  2.40it/s]

 81%|████████  | 4857/6015 [33:42<08:02,  2.40it/s]

 81%|████████  | 4858/6015 [33:43<08:02,  2.40it/s]

 81%|████████  | 4859/6015 [33:43<08:01,  2.40it/s]

 81%|████████  | 4860/6015 [33:44<08:01,  2.40it/s]

 81%|████████  | 4861/6015 [33:44<08:01,  2.40it/s]

 81%|████████  | 4862/6015 [33:44<08:01,  2.40it/s]

 81%|████████  | 4863/6015 [33:45<08:00,  2.40it/s]

 81%|████████  | 4864/6015 [33:45<08:00,  2.40it/s]

 81%|████████  | 4865/6015 [33:46<07:59,  2.40it/s]

 81%|████████  | 4866/6015 [33:46<07:58,  2.40it/s]

 81%|████████  | 4867/6015 [33:47<07:58,  2.40it/s]

 81%|████████  | 4868/6015 [33:47<07:57,  2.40it/s]

 81%|████████  | 4869/6015 [33:47<07:57,  2.40it/s]

 81%|████████  | 4870/6015 [33:48<07:57,  2.40it/s]

 81%|████████  | 4871/6015 [33:48<07:56,  2.40it/s]

 81%|████████  | 4872/6015 [33:49<07:57,  2.40it/s]

 81%|████████  | 4873/6015 [33:49<07:56,  2.40it/s]

 81%|████████  | 4874/6015 [33:50<07:57,  2.39it/s]

 81%|████████  | 4875/6015 [33:50<07:56,  2.39it/s]

 81%|████████  | 4876/6015 [33:50<07:55,  2.40it/s]

 81%|████████  | 4877/6015 [33:51<07:55,  2.39it/s]

 81%|████████  | 4878/6015 [33:51<07:54,  2.39it/s]

 81%|████████  | 4879/6015 [33:52<07:53,  2.40it/s]

 81%|████████  | 4880/6015 [33:52<07:53,  2.40it/s]

 81%|████████  | 4881/6015 [33:52<07:52,  2.40it/s]

 81%|████████  | 4882/6015 [33:53<07:52,  2.40it/s]

 81%|████████  | 4883/6015 [33:53<07:53,  2.39it/s]

 81%|████████  | 4884/6015 [33:54<07:52,  2.39it/s]

 81%|████████  | 4885/6015 [33:54<07:52,  2.39it/s]

 81%|████████  | 4886/6015 [33:55<07:52,  2.39it/s]

 81%|████████  | 4887/6015 [33:55<07:52,  2.39it/s]

 81%|████████▏ | 4888/6015 [33:55<07:51,  2.39it/s]

 81%|████████▏ | 4889/6015 [33:56<07:51,  2.39it/s]

 81%|████████▏ | 4890/6015 [33:56<07:50,  2.39it/s]

 81%|████████▏ | 4891/6015 [33:57<07:50,  2.39it/s]

 81%|████████▏ | 4892/6015 [33:57<07:49,  2.39it/s]

 81%|████████▏ | 4893/6015 [33:57<07:51,  2.38it/s]

 81%|████████▏ | 4894/6015 [33:58<07:50,  2.38it/s]

 81%|████████▏ | 4895/6015 [33:58<07:50,  2.38it/s]

 81%|████████▏ | 4896/6015 [33:59<07:49,  2.39it/s]

 81%|████████▏ | 4897/6015 [33:59<07:48,  2.38it/s]

 81%|████████▏ | 4898/6015 [34:00<07:47,  2.39it/s]

 81%|████████▏ | 4899/6015 [34:00<07:47,  2.39it/s]

 81%|████████▏ | 4900/6015 [34:00<07:46,  2.39it/s]

 81%|████████▏ | 4901/6015 [34:01<07:47,  2.38it/s]

 81%|████████▏ | 4902/6015 [34:01<07:46,  2.39it/s]

 82%|████████▏ | 4903/6015 [34:02<07:44,  2.39it/s]

 82%|████████▏ | 4904/6015 [34:02<07:43,  2.40it/s]

 82%|████████▏ | 4905/6015 [34:02<07:44,  2.39it/s]

 82%|████████▏ | 4906/6015 [34:03<07:43,  2.39it/s]

 82%|████████▏ | 4907/6015 [34:03<07:42,  2.39it/s]

 82%|████████▏ | 4908/6015 [34:04<07:42,  2.39it/s]

 82%|████████▏ | 4909/6015 [34:04<07:42,  2.39it/s]

 82%|████████▏ | 4910/6015 [34:05<07:41,  2.39it/s]

 82%|████████▏ | 4911/6015 [34:05<07:41,  2.39it/s]

 82%|████████▏ | 4912/6015 [34:05<07:40,  2.39it/s]

 82%|████████▏ | 4913/6015 [34:06<07:40,  2.39it/s]

 82%|████████▏ | 4914/6015 [34:06<07:40,  2.39it/s]

 82%|████████▏ | 4915/6015 [34:07<07:40,  2.39it/s]

 82%|████████▏ | 4916/6015 [34:07<07:39,  2.39it/s]

 82%|████████▏ | 4917/6015 [34:07<07:39,  2.39it/s]

 82%|████████▏ | 4918/6015 [34:08<07:38,  2.39it/s]

 82%|████████▏ | 4919/6015 [34:08<07:38,  2.39it/s]

 82%|████████▏ | 4920/6015 [34:09<07:37,  2.39it/s]

 82%|████████▏ | 4921/6015 [34:09<07:37,  2.39it/s]

 82%|████████▏ | 4922/6015 [34:10<07:37,  2.39it/s]

 82%|████████▏ | 4923/6015 [34:10<07:37,  2.39it/s]

 82%|████████▏ | 4924/6015 [34:10<07:35,  2.39it/s]

 82%|████████▏ | 4925/6015 [34:11<07:36,  2.39it/s]

 82%|████████▏ | 4926/6015 [34:11<07:35,  2.39it/s]

 82%|████████▏ | 4927/6015 [34:12<07:35,  2.39it/s]

 82%|████████▏ | 4928/6015 [34:12<07:34,  2.39it/s]

 82%|████████▏ | 4929/6015 [34:13<07:34,  2.39it/s]

 82%|████████▏ | 4930/6015 [34:13<07:33,  2.39it/s]

 82%|████████▏ | 4931/6015 [34:13<07:33,  2.39it/s]

 82%|████████▏ | 4932/6015 [34:14<07:32,  2.39it/s]

 82%|████████▏ | 4933/6015 [34:14<07:32,  2.39it/s]

 82%|████████▏ | 4934/6015 [34:15<07:32,  2.39it/s]

 82%|████████▏ | 4935/6015 [34:15<07:31,  2.39it/s]

 82%|████████▏ | 4936/6015 [34:15<07:30,  2.39it/s]

 82%|████████▏ | 4937/6015 [34:16<07:30,  2.39it/s]

 82%|████████▏ | 4938/6015 [34:16<07:30,  2.39it/s]

 82%|████████▏ | 4939/6015 [34:17<07:30,  2.39it/s]

 82%|████████▏ | 4940/6015 [34:17<07:29,  2.39it/s]

 82%|████████▏ | 4941/6015 [34:18<07:30,  2.38it/s]

 82%|████████▏ | 4942/6015 [34:18<07:29,  2.39it/s]

 82%|████████▏ | 4943/6015 [34:18<07:28,  2.39it/s]

 82%|████████▏ | 4944/6015 [34:19<07:28,  2.39it/s]

 82%|████████▏ | 4945/6015 [34:19<07:28,  2.39it/s]

 82%|████████▏ | 4946/6015 [34:20<07:27,  2.39it/s]

 82%|████████▏ | 4947/6015 [34:20<07:27,  2.39it/s]

 82%|████████▏ | 4948/6015 [34:20<07:26,  2.39it/s]

 82%|████████▏ | 4949/6015 [34:21<07:27,  2.38it/s]

 82%|████████▏ | 4950/6015 [34:21<07:26,  2.39it/s]

 82%|████████▏ | 4951/6015 [34:22<07:25,  2.39it/s]

 82%|████████▏ | 4952/6015 [34:22<07:24,  2.39it/s]

 82%|████████▏ | 4953/6015 [34:23<07:24,  2.39it/s]

 82%|████████▏ | 4954/6015 [34:23<07:23,  2.39it/s]

 82%|████████▏ | 4955/6015 [34:23<07:23,  2.39it/s]

 82%|████████▏ | 4956/6015 [34:24<07:22,  2.39it/s]

 82%|████████▏ | 4957/6015 [34:24<07:23,  2.39it/s]

 82%|████████▏ | 4958/6015 [34:25<07:23,  2.39it/s]

 82%|████████▏ | 4959/6015 [34:25<07:23,  2.38it/s]

 82%|████████▏ | 4960/6015 [34:25<07:22,  2.38it/s]

 82%|████████▏ | 4961/6015 [34:26<07:22,  2.38it/s]

 82%|████████▏ | 4962/6015 [34:26<07:22,  2.38it/s]

 83%|████████▎ | 4963/6015 [34:27<07:21,  2.38it/s]

 83%|████████▎ | 4964/6015 [34:27<07:20,  2.39it/s]

 83%|████████▎ | 4965/6015 [34:28<07:19,  2.39it/s]

 83%|████████▎ | 4966/6015 [34:28<07:19,  2.39it/s]

 83%|████████▎ | 4967/6015 [34:28<07:17,  2.39it/s]

 83%|████████▎ | 4968/6015 [34:29<07:18,  2.39it/s]

 83%|████████▎ | 4969/6015 [34:29<07:17,  2.39it/s]

 83%|████████▎ | 4970/6015 [34:30<07:16,  2.39it/s]

 83%|████████▎ | 4971/6015 [34:30<07:16,  2.39it/s]

 83%|████████▎ | 4972/6015 [34:31<07:16,  2.39it/s]

 83%|████████▎ | 4973/6015 [34:31<07:16,  2.39it/s]

 83%|████████▎ | 4974/6015 [34:31<07:15,  2.39it/s]

 83%|████████▎ | 4975/6015 [34:32<07:15,  2.39it/s]

 83%|████████▎ | 4976/6015 [34:32<07:14,  2.39it/s]

 83%|████████▎ | 4977/6015 [34:33<07:13,  2.39it/s]

 83%|████████▎ | 4978/6015 [34:33<07:13,  2.39it/s]

 83%|████████▎ | 4979/6015 [34:33<07:13,  2.39it/s]

 83%|████████▎ | 4980/6015 [34:34<07:12,  2.39it/s]

 83%|████████▎ | 4981/6015 [34:34<07:11,  2.40it/s]

 83%|████████▎ | 4982/6015 [34:35<07:11,  2.39it/s]

 83%|████████▎ | 4983/6015 [34:35<07:11,  2.39it/s]

 83%|████████▎ | 4984/6015 [34:36<07:11,  2.39it/s]

 83%|████████▎ | 4985/6015 [34:36<07:11,  2.39it/s]

 83%|████████▎ | 4986/6015 [34:36<07:11,  2.39it/s]

 83%|████████▎ | 4987/6015 [34:37<07:10,  2.39it/s]

 83%|████████▎ | 4988/6015 [34:37<07:10,  2.39it/s]

 83%|████████▎ | 4989/6015 [34:38<07:09,  2.39it/s]

 83%|████████▎ | 4990/6015 [34:38<07:09,  2.39it/s]

 83%|████████▎ | 4991/6015 [34:38<07:08,  2.39it/s]

 83%|████████▎ | 4992/6015 [34:39<07:08,  2.39it/s]

 83%|████████▎ | 4993/6015 [34:39<07:07,  2.39it/s]

 83%|████████▎ | 4994/6015 [34:40<07:06,  2.39it/s]

 83%|████████▎ | 4995/6015 [34:40<07:07,  2.39it/s]

 83%|████████▎ | 4996/6015 [34:41<07:07,  2.39it/s]

 83%|████████▎ | 4997/6015 [34:41<07:06,  2.39it/s]

 83%|████████▎ | 4998/6015 [34:41<07:05,  2.39it/s]

 83%|████████▎ | 4999/6015 [34:42<07:05,  2.39it/s]

 83%|████████▎ | 5000/6015 [34:42<07:05,  2.39it/s]

 83%|████████▎ | 5001/6015 [34:43<07:05,  2.39it/s]

 83%|████████▎ | 5002/6015 [34:43<07:04,  2.38it/s]

 83%|████████▎ | 5003/6015 [34:43<07:04,  2.39it/s]

 83%|████████▎ | 5004/6015 [34:44<07:04,  2.38it/s]

 83%|████████▎ | 5005/6015 [34:44<07:03,  2.38it/s]

 83%|████████▎ | 5006/6015 [34:45<07:02,  2.39it/s]

 83%|████████▎ | 5007/6015 [34:45<07:01,  2.39it/s]

logging
logging the anndata

 83%|████████▎ | 5008/6015 [34:46<07:13,  2.32it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 83%|████████▎ | 5009/6015 [34:46<07:08,  2.35it/s]

 83%|████████▎ | 5010/6015 [34:46<07:04,  2.37it/s]

 83%|████████▎ | 5011/6015 [34:47<07:00,  2.39it/s]

 83%|████████▎ | 5012/6015 [34:47<06:57,  2.40it/s]

 83%|████████▎ | 5013/6015 [34:48<06:55,  2.41it/s]

 83%|████████▎ | 5014/6015 [34:48<06:54,  2.42it/s]

 83%|████████▎ | 5015/6015 [34:49<06:53,  2.42it/s]

 83%|████████▎ | 5016/6015 [34:49<06:52,  2.42it/s]

 83%|████████▎ | 5017/6015 [34:49<06:51,  2.42it/s]

 83%|████████▎ | 5018/6015 [34:50<06:50,  2.43it/s]

 83%|████████▎ | 5019/6015 [34:50<06:50,  2.43it/s]

 83%|████████▎ | 5020/6015 [34:51<06:50,  2.43it/s]

 83%|████████▎ | 5021/6015 [34:51<06:49,  2.42it/s]

 83%|████████▎ | 5022/6015 [34:51<06:49,  2.43it/s]

 84%|████████▎ | 5023/6015 [34:52<06:48,  2.43it/s]

 84%|████████▎ | 5024/6015 [34:52<06:48,  2.43it/s]

 84%|████████▎ | 5025/6015 [34:53<06:48,  2.43it/s]

 84%|████████▎ | 5026/6015 [34:53<06:47,  2.43it/s]

 84%|████████▎ | 5027/6015 [34:53<06:47,  2.42it/s]

 84%|████████▎ | 5028/6015 [34:54<06:48,  2.42it/s]

 84%|████████▎ | 5029/6015 [34:54<06:47,  2.42it/s]

 84%|████████▎ | 5030/6015 [34:55<06:46,  2.42it/s]

 84%|████████▎ | 5031/6015 [34:55<06:45,  2.42it/s]

 84%|████████▎ | 5032/6015 [34:56<06:45,  2.42it/s]

 84%|████████▎ | 5033/6015 [34:56<06:45,  2.42it/s]

 84%|████████▎ | 5034/6015 [34:56<06:44,  2.43it/s]

 84%|████████▎ | 5035/6015 [34:57<06:44,  2.42it/s]

 84%|████████▎ | 5036/6015 [34:57<06:44,  2.42it/s]

 84%|████████▎ | 5037/6015 [34:58<06:43,  2.42it/s]

 84%|████████▍ | 5038/6015 [34:58<06:42,  2.42it/s]

 84%|████████▍ | 5039/6015 [34:58<06:42,  2.43it/s]

 84%|████████▍ | 5040/6015 [34:59<06:41,  2.43it/s]

 84%|████████▍ | 5041/6015 [34:59<06:41,  2.43it/s]

 84%|████████▍ | 5042/6015 [35:00<06:40,  2.43it/s]

 84%|████████▍ | 5043/6015 [35:00<06:40,  2.43it/s]

 84%|████████▍ | 5044/6015 [35:00<06:39,  2.43it/s]

 84%|████████▍ | 5045/6015 [35:01<06:39,  2.43it/s]

 84%|████████▍ | 5046/6015 [35:01<06:39,  2.43it/s]

 84%|████████▍ | 5047/6015 [35:02<06:38,  2.43it/s]

 84%|████████▍ | 5048/6015 [35:02<06:38,  2.43it/s]

 84%|████████▍ | 5049/6015 [35:03<06:38,  2.43it/s]

 84%|████████▍ | 5050/6015 [35:03<06:37,  2.43it/s]

 84%|████████▍ | 5051/6015 [35:03<06:37,  2.43it/s]

 84%|████████▍ | 5052/6015 [35:04<06:37,  2.43it/s]

 84%|████████▍ | 5053/6015 [35:04<06:36,  2.43it/s]

 84%|████████▍ | 5054/6015 [35:05<06:36,  2.43it/s]

 84%|████████▍ | 5055/6015 [35:05<06:35,  2.43it/s]

 84%|████████▍ | 5056/6015 [35:05<06:35,  2.43it/s]

 84%|████████▍ | 5057/6015 [35:06<06:34,  2.43it/s]

 84%|████████▍ | 5058/6015 [35:06<06:34,  2.42it/s]

 84%|████████▍ | 5059/6015 [35:07<06:33,  2.43it/s]

 84%|████████▍ | 5060/6015 [35:07<06:33,  2.43it/s]

 84%|████████▍ | 5061/6015 [35:07<06:33,  2.42it/s]

 84%|████████▍ | 5062/6015 [35:08<06:33,  2.42it/s]

 84%|████████▍ | 5063/6015 [35:08<06:32,  2.42it/s]

 84%|████████▍ | 5064/6015 [35:09<06:32,  2.43it/s]

 84%|████████▍ | 5065/6015 [35:09<06:31,  2.42it/s]

 84%|████████▍ | 5066/6015 [35:10<06:31,  2.43it/s]

 84%|████████▍ | 5067/6015 [35:10<06:30,  2.43it/s]

 84%|████████▍ | 5068/6015 [35:10<06:30,  2.43it/s]

 84%|████████▍ | 5069/6015 [35:11<06:30,  2.42it/s]

 84%|████████▍ | 5070/6015 [35:11<06:29,  2.42it/s]

 84%|████████▍ | 5071/6015 [35:12<06:29,  2.43it/s]

 84%|████████▍ | 5072/6015 [35:12<06:28,  2.42it/s]

 84%|████████▍ | 5073/6015 [35:12<06:28,  2.42it/s]

 84%|████████▍ | 5074/6015 [35:13<06:29,  2.42it/s]

 84%|████████▍ | 5075/6015 [35:13<06:28,  2.42it/s]

 84%|████████▍ | 5076/6015 [35:14<06:28,  2.42it/s]

 84%|████████▍ | 5077/6015 [35:14<06:27,  2.42it/s]

 84%|████████▍ | 5078/6015 [35:14<06:27,  2.42it/s]

 84%|████████▍ | 5079/6015 [35:15<06:26,  2.42it/s]

 84%|████████▍ | 5080/6015 [35:15<06:26,  2.42it/s]

 84%|████████▍ | 5081/6015 [35:16<06:25,  2.42it/s]

 84%|████████▍ | 5082/6015 [35:16<06:25,  2.42it/s]

 85%|████████▍ | 5083/6015 [35:17<06:24,  2.42it/s]

 85%|████████▍ | 5084/6015 [35:17<06:24,  2.42it/s]

 85%|████████▍ | 5085/6015 [35:17<06:24,  2.42it/s]

 85%|████████▍ | 5086/6015 [35:18<06:23,  2.42it/s]

 85%|████████▍ | 5087/6015 [35:18<06:23,  2.42it/s]

 85%|████████▍ | 5088/6015 [35:19<06:22,  2.42it/s]

 85%|████████▍ | 5089/6015 [35:19<06:22,  2.42it/s]

 85%|████████▍ | 5090/6015 [35:19<06:21,  2.42it/s]

 85%|████████▍ | 5091/6015 [35:20<06:21,  2.42it/s]

 85%|████████▍ | 5092/6015 [35:20<06:20,  2.42it/s]

 85%|████████▍ | 5093/6015 [35:21<06:21,  2.42it/s]

 85%|████████▍ | 5094/6015 [35:21<06:21,  2.42it/s]

 85%|████████▍ | 5095/6015 [35:22<06:20,  2.41it/s]

 85%|████████▍ | 5096/6015 [35:22<06:20,  2.42it/s]

 85%|████████▍ | 5097/6015 [35:22<06:19,  2.42it/s]

 85%|████████▍ | 5098/6015 [35:23<06:18,  2.42it/s]

 85%|████████▍ | 5099/6015 [35:23<06:18,  2.42it/s]

 85%|████████▍ | 5100/6015 [35:24<06:18,  2.42it/s]

 85%|████████▍ | 5101/6015 [35:24<06:17,  2.42it/s]

 85%|████████▍ | 5102/6015 [35:24<06:17,  2.42it/s]

 85%|████████▍ | 5103/6015 [35:25<06:17,  2.42it/s]

 85%|████████▍ | 5104/6015 [35:25<06:16,  2.42it/s]

 85%|████████▍ | 5105/6015 [35:26<06:16,  2.42it/s]

 85%|████████▍ | 5106/6015 [35:26<06:15,  2.42it/s]

 85%|████████▍ | 5107/6015 [35:26<06:15,  2.42it/s]

 85%|████████▍ | 5108/6015 [35:27<06:15,  2.41it/s]

 85%|████████▍ | 5109/6015 [35:27<06:14,  2.42it/s]

 85%|████████▍ | 5110/6015 [35:28<06:14,  2.42it/s]

 85%|████████▍ | 5111/6015 [35:28<06:13,  2.42it/s]

 85%|████████▍ | 5112/6015 [35:29<06:12,  2.42it/s]

 85%|████████▌ | 5113/6015 [35:29<06:12,  2.42it/s]

 85%|████████▌ | 5114/6015 [35:29<06:12,  2.42it/s]

 85%|████████▌ | 5115/6015 [35:30<06:12,  2.42it/s]

 85%|████████▌ | 5116/6015 [35:30<06:11,  2.42it/s]

 85%|████████▌ | 5117/6015 [35:31<06:11,  2.42it/s]

 85%|████████▌ | 5118/6015 [35:31<06:11,  2.42it/s]

 85%|████████▌ | 5119/6015 [35:31<06:10,  2.42it/s]

 85%|████████▌ | 5120/6015 [35:32<06:10,  2.41it/s]

 85%|████████▌ | 5121/6015 [35:32<06:10,  2.41it/s]

 85%|████████▌ | 5122/6015 [35:33<06:09,  2.42it/s]

 85%|████████▌ | 5123/6015 [35:33<06:09,  2.41it/s]

 85%|████████▌ | 5124/6015 [35:34<06:08,  2.41it/s]

 85%|████████▌ | 5125/6015 [35:34<06:09,  2.41it/s]

 85%|████████▌ | 5126/6015 [35:34<06:08,  2.41it/s]

 85%|████████▌ | 5127/6015 [35:35<06:07,  2.42it/s]

 85%|████████▌ | 5128/6015 [35:35<06:06,  2.42it/s]

 85%|████████▌ | 5129/6015 [35:36<06:06,  2.42it/s]

 85%|████████▌ | 5130/6015 [35:36<06:06,  2.42it/s]

 85%|████████▌ | 5131/6015 [35:36<06:05,  2.42it/s]

 85%|████████▌ | 5132/6015 [35:37<06:05,  2.42it/s]

 85%|████████▌ | 5133/6015 [35:37<06:04,  2.42it/s]

 85%|████████▌ | 5134/6015 [35:38<06:04,  2.42it/s]

 85%|████████▌ | 5135/6015 [35:38<06:03,  2.42it/s]

 85%|████████▌ | 5136/6015 [35:38<06:03,  2.42it/s]

 85%|████████▌ | 5137/6015 [35:39<06:02,  2.42it/s]

 85%|████████▌ | 5138/6015 [35:39<06:02,  2.42it/s]

 85%|████████▌ | 5139/6015 [35:40<06:01,  2.42it/s]

 85%|████████▌ | 5140/6015 [35:40<06:01,  2.42it/s]

 85%|████████▌ | 5141/6015 [35:41<06:01,  2.42it/s]

 85%|████████▌ | 5142/6015 [35:41<06:00,  2.42it/s]

 86%|████████▌ | 5143/6015 [35:41<06:00,  2.42it/s]

 86%|████████▌ | 5144/6015 [35:42<05:59,  2.42it/s]

 86%|████████▌ | 5145/6015 [35:42<05:59,  2.42it/s]

 86%|████████▌ | 5146/6015 [35:43<05:58,  2.42it/s]

 86%|████████▌ | 5147/6015 [35:43<05:58,  2.42it/s]

 86%|████████▌ | 5148/6015 [35:43<05:58,  2.42it/s]

 86%|████████▌ | 5149/6015 [35:44<05:57,  2.42it/s]

 86%|████████▌ | 5150/6015 [35:44<05:57,  2.42it/s]

 86%|████████▌ | 5151/6015 [35:45<05:56,  2.42it/s]

 86%|████████▌ | 5152/6015 [35:45<05:56,  2.42it/s]

 86%|████████▌ | 5153/6015 [35:45<05:55,  2.42it/s]

 86%|████████▌ | 5154/6015 [35:46<05:55,  2.42it/s]

 86%|████████▌ | 5155/6015 [35:46<05:55,  2.42it/s]

 86%|████████▌ | 5156/6015 [35:47<05:55,  2.42it/s]

 86%|████████▌ | 5157/6015 [35:47<05:54,  2.42it/s]

 86%|████████▌ | 5158/6015 [35:48<05:53,  2.42it/s]

 86%|████████▌ | 5159/6015 [35:48<05:53,  2.42it/s]

 86%|████████▌ | 5160/6015 [35:48<05:53,  2.42it/s]

 86%|████████▌ | 5161/6015 [35:49<05:53,  2.42it/s]

 86%|████████▌ | 5162/6015 [35:49<05:52,  2.42it/s]

 86%|████████▌ | 5163/6015 [35:50<05:52,  2.42it/s]

 86%|████████▌ | 5164/6015 [35:50<05:51,  2.42it/s]

 86%|████████▌ | 5165/6015 [35:50<05:51,  2.42it/s]

 86%|████████▌ | 5166/6015 [35:51<05:51,  2.42it/s]

 86%|████████▌ | 5167/6015 [35:51<05:50,  2.42it/s]

 86%|████████▌ | 5168/6015 [35:52<05:50,  2.42it/s]

 86%|████████▌ | 5169/6015 [35:52<05:49,  2.42it/s]

 86%|████████▌ | 5170/6015 [35:53<05:49,  2.42it/s]

 86%|████████▌ | 5171/6015 [35:53<05:48,  2.42it/s]

 86%|████████▌ | 5172/6015 [35:53<05:48,  2.42it/s]

 86%|████████▌ | 5173/6015 [35:54<05:48,  2.42it/s]

 86%|████████▌ | 5174/6015 [35:54<05:47,  2.42it/s]

 86%|████████▌ | 5175/6015 [35:55<05:47,  2.42it/s]

 86%|████████▌ | 5176/6015 [35:55<05:46,  2.42it/s]

 86%|████████▌ | 5177/6015 [35:55<05:46,  2.42it/s]

 86%|████████▌ | 5178/6015 [35:56<05:47,  2.41it/s]

 86%|████████▌ | 5179/6015 [35:56<05:46,  2.41it/s]

 86%|████████▌ | 5180/6015 [35:57<05:45,  2.41it/s]

 86%|████████▌ | 5181/6015 [35:57<05:45,  2.42it/s]

 86%|████████▌ | 5182/6015 [35:57<05:45,  2.41it/s]

 86%|████████▌ | 5183/6015 [35:58<05:44,  2.41it/s]

 86%|████████▌ | 5184/6015 [35:58<05:44,  2.42it/s]

 86%|████████▌ | 5185/6015 [35:59<05:43,  2.42it/s]

 86%|████████▌ | 5186/6015 [35:59<05:42,  2.42it/s]

 86%|████████▌ | 5187/6015 [36:00<05:42,  2.42it/s]

 86%|████████▋ | 5188/6015 [36:00<05:42,  2.42it/s]

 86%|████████▋ | 5189/6015 [36:00<05:42,  2.41it/s]

 86%|████████▋ | 5190/6015 [36:01<05:41,  2.41it/s]

 86%|████████▋ | 5191/6015 [36:01<05:41,  2.42it/s]

 86%|████████▋ | 5192/6015 [36:02<05:40,  2.42it/s]

 86%|████████▋ | 5193/6015 [36:02<05:40,  2.41it/s]

 86%|████████▋ | 5194/6015 [36:02<05:39,  2.41it/s]

 86%|████████▋ | 5195/6015 [36:03<05:39,  2.41it/s]

 86%|████████▋ | 5196/6015 [36:03<05:39,  2.41it/s]

 86%|████████▋ | 5197/6015 [36:04<05:39,  2.41it/s]

 86%|████████▋ | 5198/6015 [36:04<05:38,  2.41it/s]

 86%|████████▋ | 5199/6015 [36:05<05:38,  2.41it/s]

 86%|████████▋ | 5200/6015 [36:05<05:37,  2.41it/s]

 86%|████████▋ | 5201/6015 [36:05<05:37,  2.41it/s]

 86%|████████▋ | 5202/6015 [36:06<05:36,  2.41it/s]

 87%|████████▋ | 5203/6015 [36:06<05:36,  2.41it/s]

 87%|████████▋ | 5204/6015 [36:07<05:36,  2.41it/s]

 87%|████████▋ | 5205/6015 [36:07<05:35,  2.41it/s]

 87%|████████▋ | 5206/6015 [36:07<05:36,  2.41it/s]

 87%|████████▋ | 5207/6015 [36:08<05:35,  2.41it/s]

 87%|████████▋ | 5208/6015 [36:08<05:35,  2.41it/s]

 87%|████████▋ | 5209/6015 [36:09<05:34,  2.41it/s]

 87%|████████▋ | 5210/6015 [36:09<05:33,  2.41it/s]

 87%|████████▋ | 5211/6015 [36:10<05:33,  2.41it/s]

 87%|████████▋ | 5212/6015 [36:10<05:32,  2.41it/s]

 87%|████████▋ | 5213/6015 [36:10<05:32,  2.41it/s]

 87%|████████▋ | 5214/6015 [36:11<05:31,  2.41it/s]

 87%|████████▋ | 5215/6015 [36:11<05:31,  2.42it/s]

 87%|████████▋ | 5216/6015 [36:12<05:31,  2.41it/s]

 87%|████████▋ | 5217/6015 [36:12<05:30,  2.42it/s]

 87%|████████▋ | 5218/6015 [36:12<05:29,  2.42it/s]

 87%|████████▋ | 5219/6015 [36:13<05:29,  2.42it/s]

 87%|████████▋ | 5220/6015 [36:13<05:28,  2.42it/s]

 87%|████████▋ | 5221/6015 [36:14<05:28,  2.42it/s]

 87%|████████▋ | 5222/6015 [36:14<05:28,  2.41it/s]

 87%|████████▋ | 5223/6015 [36:14<05:28,  2.41it/s]

 87%|████████▋ | 5224/6015 [36:15<05:27,  2.41it/s]

 87%|████████▋ | 5225/6015 [36:15<05:27,  2.41it/s]

 87%|████████▋ | 5226/6015 [36:16<05:26,  2.41it/s]

 87%|████████▋ | 5227/6015 [36:16<05:26,  2.41it/s]

 87%|████████▋ | 5228/6015 [36:17<05:25,  2.42it/s]

 87%|████████▋ | 5229/6015 [36:17<05:25,  2.41it/s]

 87%|████████▋ | 5230/6015 [36:17<05:24,  2.42it/s]

 87%|████████▋ | 5231/6015 [36:18<05:24,  2.42it/s]

 87%|████████▋ | 5232/6015 [36:18<05:24,  2.41it/s]

 87%|████████▋ | 5233/6015 [36:19<05:23,  2.41it/s]

 87%|████████▋ | 5234/6015 [36:19<05:23,  2.42it/s]

 87%|████████▋ | 5235/6015 [36:19<05:23,  2.41it/s]

 87%|████████▋ | 5236/6015 [36:20<05:23,  2.41it/s]

 87%|████████▋ | 5237/6015 [36:20<05:22,  2.41it/s]

 87%|████████▋ | 5238/6015 [36:21<05:22,  2.41it/s]

 87%|████████▋ | 5239/6015 [36:21<05:21,  2.41it/s]

 87%|████████▋ | 5240/6015 [36:22<05:20,  2.41it/s]

 87%|████████▋ | 5241/6015 [36:22<05:20,  2.41it/s]

 87%|████████▋ | 5242/6015 [36:22<05:20,  2.41it/s]

 87%|████████▋ | 5243/6015 [36:23<05:19,  2.41it/s]

 87%|████████▋ | 5244/6015 [36:23<05:19,  2.41it/s]

 87%|████████▋ | 5245/6015 [36:24<05:19,  2.41it/s]

 87%|████████▋ | 5246/6015 [36:24<05:19,  2.41it/s]

 87%|████████▋ | 5247/6015 [36:24<05:18,  2.41it/s]

 87%|████████▋ | 5248/6015 [36:25<05:18,  2.41it/s]

 87%|████████▋ | 5249/6015 [36:25<05:17,  2.41it/s]

 87%|████████▋ | 5250/6015 [36:26<05:16,  2.41it/s]

 87%|████████▋ | 5251/6015 [36:26<05:16,  2.41it/s]

 87%|████████▋ | 5252/6015 [36:26<05:16,  2.41it/s]

 87%|████████▋ | 5253/6015 [36:27<05:15,  2.41it/s]

 87%|████████▋ | 5254/6015 [36:27<05:15,  2.42it/s]

 87%|████████▋ | 5255/6015 [36:28<05:14,  2.41it/s]

 87%|████████▋ | 5256/6015 [36:28<05:14,  2.41it/s]

 87%|████████▋ | 5257/6015 [36:29<05:13,  2.41it/s]

 87%|████████▋ | 5258/6015 [36:29<05:13,  2.41it/s]

 87%|████████▋ | 5259/6015 [36:29<05:13,  2.41it/s]

 87%|████████▋ | 5260/6015 [36:30<05:12,  2.41it/s]

 87%|████████▋ | 5261/6015 [36:30<05:12,  2.41it/s]

 87%|████████▋ | 5262/6015 [36:31<05:12,  2.41it/s]

 87%|████████▋ | 5263/6015 [36:31<05:12,  2.41it/s]

 88%|████████▊ | 5264/6015 [36:31<05:11,  2.41it/s]

 88%|████████▊ | 5265/6015 [36:32<05:11,  2.41it/s]

 88%|████████▊ | 5266/6015 [36:32<05:10,  2.41it/s]

 88%|████████▊ | 5267/6015 [36:33<05:10,  2.41it/s]

 88%|████████▊ | 5268/6015 [36:33<05:10,  2.41it/s]

 88%|████████▊ | 5269/6015 [36:34<05:09,  2.41it/s]

 88%|████████▊ | 5270/6015 [36:34<05:09,  2.41it/s]

 88%|████████▊ | 5271/6015 [36:34<05:08,  2.41it/s]

 88%|████████▊ | 5272/6015 [36:35<05:08,  2.41it/s]

 88%|████████▊ | 5273/6015 [36:35<05:08,  2.41it/s]

 88%|████████▊ | 5274/6015 [36:36<05:07,  2.41it/s]

 88%|████████▊ | 5275/6015 [36:36<05:06,  2.41it/s]

 88%|████████▊ | 5276/6015 [36:36<05:08,  2.40it/s]

 88%|████████▊ | 5277/6015 [36:37<05:06,  2.40it/s]

 88%|████████▊ | 5278/6015 [36:37<05:06,  2.40it/s]

 88%|████████▊ | 5279/6015 [36:38<05:05,  2.41it/s]

 88%|████████▊ | 5280/6015 [36:38<05:05,  2.41it/s]

 88%|████████▊ | 5281/6015 [36:39<05:04,  2.41it/s]

 88%|████████▊ | 5282/6015 [36:39<05:04,  2.41it/s]

 88%|████████▊ | 5283/6015 [36:39<05:04,  2.41it/s]

 88%|████████▊ | 5284/6015 [36:40<05:03,  2.41it/s]

 88%|████████▊ | 5285/6015 [36:40<05:03,  2.40it/s]

 88%|████████▊ | 5286/6015 [36:41<05:03,  2.40it/s]

 88%|████████▊ | 5287/6015 [36:41<05:02,  2.41it/s]

 88%|████████▊ | 5288/6015 [36:41<05:01,  2.41it/s]

 88%|████████▊ | 5289/6015 [36:42<05:01,  2.41it/s]

 88%|████████▊ | 5290/6015 [36:42<05:00,  2.41it/s]

 88%|████████▊ | 5291/6015 [36:43<05:00,  2.41it/s]

 88%|████████▊ | 5292/6015 [36:43<05:00,  2.41it/s]

 88%|████████▊ | 5293/6015 [36:44<04:59,  2.41it/s]

 88%|████████▊ | 5294/6015 [36:44<04:59,  2.41it/s]

 88%|████████▊ | 5295/6015 [36:44<04:58,  2.41it/s]

 88%|████████▊ | 5296/6015 [36:45<04:58,  2.41it/s]

 88%|████████▊ | 5297/6015 [36:45<04:57,  2.41it/s]

 88%|████████▊ | 5298/6015 [36:46<04:57,  2.41it/s]

 88%|████████▊ | 5299/6015 [36:46<04:57,  2.41it/s]

 88%|████████▊ | 5300/6015 [36:46<04:56,  2.41it/s]

 88%|████████▊ | 5301/6015 [36:47<04:56,  2.41it/s]

 88%|████████▊ | 5302/6015 [36:47<04:56,  2.41it/s]

 88%|████████▊ | 5303/6015 [36:48<04:55,  2.41it/s]

 88%|████████▊ | 5304/6015 [36:48<04:55,  2.41it/s]

 88%|████████▊ | 5305/6015 [36:48<04:54,  2.41it/s]

 88%|████████▊ | 5306/6015 [36:49<04:54,  2.41it/s]

 88%|████████▊ | 5307/6015 [36:49<04:54,  2.41it/s]

 88%|████████▊ | 5308/6015 [36:50<04:53,  2.41it/s]

 88%|████████▊ | 5309/6015 [36:50<04:53,  2.41it/s]

 88%|████████▊ | 5310/6015 [36:51<04:52,  2.41it/s]

 88%|████████▊ | 5311/6015 [36:51<04:52,  2.41it/s]

 88%|████████▊ | 5312/6015 [36:51<04:52,  2.41it/s]

 88%|████████▊ | 5313/6015 [36:52<04:51,  2.41it/s]

 88%|████████▊ | 5314/6015 [36:52<04:51,  2.41it/s]

 88%|████████▊ | 5315/6015 [36:53<04:50,  2.41it/s]

 88%|████████▊ | 5316/6015 [36:53<04:50,  2.41it/s]

 88%|████████▊ | 5317/6015 [36:53<04:50,  2.40it/s]

 88%|████████▊ | 5318/6015 [36:54<04:50,  2.40it/s]

 88%|████████▊ | 5319/6015 [36:54<04:49,  2.40it/s]

 88%|████████▊ | 5320/6015 [36:55<04:49,  2.40it/s]

 88%|████████▊ | 5321/6015 [36:55<04:48,  2.40it/s]

 88%|████████▊ | 5322/6015 [36:56<04:48,  2.40it/s]

 88%|████████▊ | 5323/6015 [36:56<04:47,  2.41it/s]

 89%|████████▊ | 5324/6015 [36:56<04:47,  2.41it/s]

 89%|████████▊ | 5325/6015 [36:57<04:46,  2.41it/s]

 89%|████████▊ | 5326/6015 [36:57<04:46,  2.41it/s]

 89%|████████▊ | 5327/6015 [36:58<04:45,  2.41it/s]

 89%|████████▊ | 5328/6015 [36:58<04:45,  2.41it/s]

 89%|████████▊ | 5329/6015 [36:58<04:45,  2.41it/s]

 89%|████████▊ | 5330/6015 [36:59<04:44,  2.40it/s]

 89%|████████▊ | 5331/6015 [36:59<04:44,  2.41it/s]

 89%|████████▊ | 5332/6015 [37:00<04:43,  2.41it/s]

 89%|████████▊ | 5333/6015 [37:00<04:43,  2.41it/s]

 89%|████████▊ | 5334/6015 [37:01<04:43,  2.41it/s]

 89%|████████▊ | 5335/6015 [37:01<04:42,  2.41it/s]

 89%|████████▊ | 5336/6015 [37:01<04:42,  2.41it/s]

 89%|████████▊ | 5337/6015 [37:02<04:41,  2.41it/s]

 89%|████████▊ | 5338/6015 [37:02<04:41,  2.41it/s]

 89%|████████▉ | 5339/6015 [37:03<04:40,  2.41it/s]

 89%|████████▉ | 5340/6015 [37:03<04:40,  2.40it/s]

 89%|████████▉ | 5341/6015 [37:03<04:40,  2.40it/s]

 89%|████████▉ | 5342/6015 [37:04<04:40,  2.40it/s]

 89%|████████▉ | 5343/6015 [37:04<04:39,  2.40it/s]

 89%|████████▉ | 5344/6015 [37:05<04:39,  2.40it/s]

 89%|████████▉ | 5345/6015 [37:05<04:39,  2.40it/s]

 89%|████████▉ | 5346/6015 [37:06<04:38,  2.40it/s]

 89%|████████▉ | 5347/6015 [37:06<04:38,  2.40it/s]

 89%|████████▉ | 5348/6015 [37:06<04:37,  2.40it/s]

 89%|████████▉ | 5349/6015 [37:07<04:36,  2.41it/s]

 89%|████████▉ | 5350/6015 [37:07<04:36,  2.41it/s]

 89%|████████▉ | 5351/6015 [37:08<04:36,  2.41it/s]

 89%|████████▉ | 5352/6015 [37:08<04:35,  2.40it/s]

 89%|████████▉ | 5353/6015 [37:08<04:35,  2.40it/s]

 89%|████████▉ | 5354/6015 [37:09<04:34,  2.40it/s]

 89%|████████▉ | 5355/6015 [37:09<04:34,  2.40it/s]

 89%|████████▉ | 5356/6015 [37:10<04:34,  2.40it/s]

 89%|████████▉ | 5357/6015 [37:10<04:33,  2.40it/s]

 89%|████████▉ | 5358/6015 [37:11<04:33,  2.41it/s]

 89%|████████▉ | 5359/6015 [37:11<04:34,  2.39it/s]

 89%|████████▉ | 5360/6015 [37:11<04:33,  2.39it/s]

 89%|████████▉ | 5361/6015 [37:12<04:32,  2.40it/s]

 89%|████████▉ | 5362/6015 [37:12<04:32,  2.40it/s]

 89%|████████▉ | 5363/6015 [37:13<04:31,  2.40it/s]

 89%|████████▉ | 5364/6015 [37:13<04:30,  2.40it/s]

 89%|████████▉ | 5365/6015 [37:13<04:30,  2.40it/s]

 89%|████████▉ | 5366/6015 [37:14<04:30,  2.40it/s]

 89%|████████▉ | 5367/6015 [37:14<04:29,  2.40it/s]

 89%|████████▉ | 5368/6015 [37:15<04:29,  2.41it/s]

 89%|████████▉ | 5369/6015 [37:15<04:28,  2.40it/s]

 89%|████████▉ | 5370/6015 [37:16<04:28,  2.40it/s]

 89%|████████▉ | 5371/6015 [37:16<04:28,  2.40it/s]

 89%|████████▉ | 5372/6015 [37:16<04:28,  2.40it/s]

 89%|████████▉ | 5373/6015 [37:17<04:27,  2.40it/s]

 89%|████████▉ | 5374/6015 [37:17<04:27,  2.40it/s]

 89%|████████▉ | 5375/6015 [37:18<04:27,  2.40it/s]

 89%|████████▉ | 5376/6015 [37:18<04:26,  2.40it/s]

 89%|████████▉ | 5377/6015 [37:18<04:25,  2.40it/s]

 89%|████████▉ | 5378/6015 [37:19<04:25,  2.40it/s]

 89%|████████▉ | 5379/6015 [37:19<04:24,  2.40it/s]

 89%|████████▉ | 5380/6015 [37:20<04:24,  2.40it/s]

 89%|████████▉ | 5381/6015 [37:20<04:23,  2.40it/s]

 89%|████████▉ | 5382/6015 [37:21<04:23,  2.40it/s]

 89%|████████▉ | 5383/6015 [37:21<04:22,  2.40it/s]

 90%|████████▉ | 5384/6015 [37:21<04:22,  2.40it/s]

 90%|████████▉ | 5385/6015 [37:22<04:22,  2.40it/s]

 90%|████████▉ | 5386/6015 [37:22<04:21,  2.40it/s]

 90%|████████▉ | 5387/6015 [37:23<04:21,  2.40it/s]

 90%|████████▉ | 5388/6015 [37:23<04:20,  2.40it/s]

 90%|████████▉ | 5389/6015 [37:23<04:20,  2.40it/s]

 90%|████████▉ | 5390/6015 [37:24<04:20,  2.40it/s]

 90%|████████▉ | 5391/6015 [37:24<04:19,  2.40it/s]

 90%|████████▉ | 5392/6015 [37:25<04:19,  2.40it/s]

 90%|████████▉ | 5393/6015 [37:25<04:18,  2.40it/s]

 90%|████████▉ | 5394/6015 [37:26<04:18,  2.40it/s]

 90%|████████▉ | 5395/6015 [37:26<04:17,  2.40it/s]

 90%|████████▉ | 5396/6015 [37:26<04:17,  2.41it/s]

 90%|████████▉ | 5397/6015 [37:27<04:16,  2.41it/s]

 90%|████████▉ | 5398/6015 [37:27<04:16,  2.40it/s]

 90%|████████▉ | 5399/6015 [37:28<04:16,  2.40it/s]

 90%|████████▉ | 5400/6015 [37:28<04:16,  2.40it/s]

 90%|████████▉ | 5401/6015 [37:28<04:15,  2.40it/s]

 90%|████████▉ | 5402/6015 [37:29<04:15,  2.40it/s]

 90%|████████▉ | 5403/6015 [37:29<04:14,  2.40it/s]

 90%|████████▉ | 5404/6015 [37:30<04:14,  2.40it/s]

 90%|████████▉ | 5405/6015 [37:30<04:13,  2.41it/s]

 90%|████████▉ | 5406/6015 [37:31<04:13,  2.41it/s]

 90%|████████▉ | 5407/6015 [37:31<04:13,  2.40it/s]

 90%|████████▉ | 5408/6015 [37:31<04:12,  2.40it/s]

 90%|████████▉ | 5409/6015 [37:32<04:12,  2.40it/s]

 90%|████████▉ | 5410/6015 [37:32<04:11,  2.41it/s]

 90%|████████▉ | 5411/6015 [37:33<04:11,  2.41it/s]

 90%|████████▉ | 5412/6015 [37:33<04:10,  2.41it/s]

 90%|████████▉ | 5413/6015 [37:33<04:10,  2.41it/s]

 90%|█████████ | 5414/6015 [37:34<04:10,  2.40it/s]

 90%|█████████ | 5415/6015 [37:34<04:09,  2.40it/s]

 90%|█████████ | 5416/6015 [37:35<04:09,  2.41it/s]

 90%|█████████ | 5417/6015 [37:35<04:08,  2.40it/s]

 90%|█████████ | 5418/6015 [37:36<04:08,  2.40it/s]

 90%|█████████ | 5419/6015 [37:36<04:07,  2.40it/s]

 90%|█████████ | 5420/6015 [37:36<04:07,  2.40it/s]

 90%|█████████ | 5421/6015 [37:37<04:07,  2.40it/s]

 90%|█████████ | 5422/6015 [37:37<04:07,  2.40it/s]

 90%|█████████ | 5423/6015 [37:38<04:06,  2.40it/s]

 90%|█████████ | 5424/6015 [37:38<04:06,  2.40it/s]

 90%|█████████ | 5425/6015 [37:38<04:06,  2.39it/s]

 90%|█████████ | 5426/6015 [37:39<04:05,  2.40it/s]

 90%|█████████ | 5427/6015 [37:39<04:05,  2.39it/s]

 90%|█████████ | 5428/6015 [37:40<04:04,  2.40it/s]

 90%|█████████ | 5429/6015 [37:40<04:04,  2.40it/s]

 90%|█████████ | 5430/6015 [37:41<04:03,  2.40it/s]

 90%|█████████ | 5431/6015 [37:41<04:03,  2.40it/s]

 90%|█████████ | 5432/6015 [37:41<04:02,  2.40it/s]

 90%|█████████ | 5433/6015 [37:42<04:02,  2.40it/s]

 90%|█████████ | 5434/6015 [37:42<04:01,  2.40it/s]

 90%|█████████ | 5435/6015 [37:43<04:01,  2.40it/s]

 90%|█████████ | 5436/6015 [37:43<04:00,  2.40it/s]

 90%|█████████ | 5437/6015 [37:43<04:00,  2.40it/s]

 90%|█████████ | 5438/6015 [37:44<04:00,  2.40it/s]

 90%|█████████ | 5439/6015 [37:44<03:59,  2.40it/s]

 90%|█████████ | 5440/6015 [37:45<03:59,  2.40it/s]

 90%|█████████ | 5441/6015 [37:45<03:58,  2.40it/s]

 90%|█████████ | 5442/6015 [37:46<03:59,  2.40it/s]

 90%|█████████ | 5443/6015 [37:46<03:58,  2.40it/s]

 91%|█████████ | 5444/6015 [37:46<03:58,  2.40it/s]

 91%|█████████ | 5445/6015 [37:47<03:57,  2.40it/s]

 91%|█████████ | 5446/6015 [37:47<03:56,  2.40it/s]

 91%|█████████ | 5447/6015 [37:48<03:56,  2.40it/s]

 91%|█████████ | 5448/6015 [37:48<03:56,  2.40it/s]

 91%|█████████ | 5449/6015 [37:48<03:56,  2.40it/s]

 91%|█████████ | 5450/6015 [37:49<03:55,  2.40it/s]

 91%|█████████ | 5451/6015 [37:49<03:54,  2.40it/s]

 91%|█████████ | 5452/6015 [37:50<03:54,  2.40it/s]

 91%|█████████ | 5453/6015 [37:50<03:53,  2.40it/s]

 91%|█████████ | 5454/6015 [37:51<03:53,  2.40it/s]

 91%|█████████ | 5455/6015 [37:51<03:53,  2.40it/s]

 91%|█████████ | 5456/6015 [37:51<03:52,  2.40it/s]

 91%|█████████ | 5457/6015 [37:52<03:52,  2.40it/s]

 91%|█████████ | 5458/6015 [37:52<03:52,  2.40it/s]

 91%|█████████ | 5459/6015 [37:53<03:51,  2.40it/s]

 91%|█████████ | 5460/6015 [37:53<03:51,  2.40it/s]

 91%|█████████ | 5461/6015 [37:53<03:51,  2.40it/s]

 91%|█████████ | 5462/6015 [37:54<03:50,  2.40it/s]

 91%|█████████ | 5463/6015 [37:54<03:50,  2.40it/s]

 91%|█████████ | 5464/6015 [37:55<03:49,  2.40it/s]

 91%|█████████ | 5465/6015 [37:55<03:49,  2.40it/s]

 91%|█████████ | 5466/6015 [37:56<03:49,  2.39it/s]

 91%|█████████ | 5467/6015 [37:56<03:48,  2.39it/s]

 91%|█████████ | 5468/6015 [37:56<03:48,  2.39it/s]

 91%|█████████ | 5469/6015 [37:57<03:48,  2.39it/s]

 91%|█████████ | 5470/6015 [37:57<03:47,  2.40it/s]

 91%|█████████ | 5471/6015 [37:58<03:46,  2.40it/s]

 91%|█████████ | 5472/6015 [37:58<03:46,  2.40it/s]

 91%|█████████ | 5473/6015 [37:58<03:46,  2.40it/s]

 91%|█████████ | 5474/6015 [37:59<03:45,  2.39it/s]

 91%|█████████ | 5475/6015 [37:59<03:45,  2.39it/s]

 91%|█████████ | 5476/6015 [38:00<03:45,  2.39it/s]

 91%|█████████ | 5477/6015 [38:00<03:44,  2.39it/s]

 91%|█████████ | 5478/6015 [38:01<03:44,  2.39it/s]

 91%|█████████ | 5479/6015 [38:01<03:43,  2.40it/s]

 91%|█████████ | 5480/6015 [38:01<03:43,  2.39it/s]

 91%|█████████ | 5481/6015 [38:02<03:42,  2.40it/s]

 91%|█████████ | 5482/6015 [38:02<03:42,  2.39it/s]

 91%|█████████ | 5483/6015 [38:03<03:42,  2.39it/s]

 91%|█████████ | 5484/6015 [38:03<03:41,  2.40it/s]

 91%|█████████ | 5485/6015 [38:03<03:41,  2.40it/s]

 91%|█████████ | 5486/6015 [38:04<03:40,  2.40it/s]

 91%|█████████ | 5487/6015 [38:04<03:40,  2.40it/s]

 91%|█████████ | 5488/6015 [38:05<03:39,  2.40it/s]

 91%|█████████▏| 5489/6015 [38:05<03:39,  2.40it/s]

 91%|█████████▏| 5490/6015 [38:06<03:38,  2.40it/s]

 91%|█████████▏| 5491/6015 [38:06<03:38,  2.40it/s]

 91%|█████████▏| 5492/6015 [38:06<03:38,  2.40it/s]

 91%|█████████▏| 5493/6015 [38:07<03:37,  2.40it/s]

 91%|█████████▏| 5494/6015 [38:07<03:37,  2.40it/s]

 91%|█████████▏| 5495/6015 [38:08<03:37,  2.40it/s]

 91%|█████████▏| 5496/6015 [38:08<03:36,  2.40it/s]

 91%|█████████▏| 5497/6015 [38:08<03:36,  2.40it/s]

 91%|█████████▏| 5498/6015 [38:09<03:35,  2.40it/s]

 91%|█████████▏| 5499/6015 [38:09<03:35,  2.40it/s]

 91%|█████████▏| 5500/6015 [38:10<03:34,  2.40it/s]

 91%|█████████▏| 5501/6015 [38:10<03:34,  2.40it/s]

 91%|█████████▏| 5502/6015 [38:11<03:33,  2.40it/s]

 91%|█████████▏| 5503/6015 [38:11<03:33,  2.40it/s]

 92%|█████████▏| 5504/6015 [38:11<03:33,  2.40it/s]

 92%|█████████▏| 5505/6015 [38:12<03:32,  2.40it/s]

 92%|█████████▏| 5506/6015 [38:12<03:32,  2.40it/s]

 92%|█████████▏| 5507/6015 [38:13<03:31,  2.40it/s]

 92%|█████████▏| 5508/6015 [38:13<03:31,  2.40it/s]

 92%|█████████▏| 5509/6015 [38:13<03:31,  2.39it/s]

 92%|█████████▏| 5510/6015 [38:14<03:30,  2.40it/s]

 92%|█████████▏| 5511/6015 [38:14<03:30,  2.40it/s]

 92%|█████████▏| 5512/6015 [38:15<03:29,  2.40it/s]

 92%|█████████▏| 5513/6015 [38:15<03:29,  2.39it/s]

 92%|█████████▏| 5514/6015 [38:16<03:29,  2.39it/s]

 92%|█████████▏| 5515/6015 [38:16<03:28,  2.40it/s]

 92%|█████████▏| 5516/6015 [38:16<03:28,  2.40it/s]

 92%|█████████▏| 5517/6015 [38:17<03:27,  2.40it/s]

 92%|█████████▏| 5518/6015 [38:17<03:27,  2.40it/s]

 92%|█████████▏| 5519/6015 [38:18<03:26,  2.40it/s]

 92%|█████████▏| 5520/6015 [38:18<03:26,  2.40it/s]

 92%|█████████▏| 5521/6015 [38:18<03:26,  2.40it/s]

 92%|█████████▏| 5522/6015 [38:19<03:25,  2.39it/s]

 92%|█████████▏| 5523/6015 [38:19<03:25,  2.39it/s]

 92%|█████████▏| 5524/6015 [38:20<03:25,  2.39it/s]

 92%|█████████▏| 5525/6015 [38:20<03:24,  2.39it/s]

 92%|█████████▏| 5526/6015 [38:21<03:24,  2.39it/s]

 92%|█████████▏| 5527/6015 [38:21<03:23,  2.40it/s]

 92%|█████████▏| 5528/6015 [38:21<03:23,  2.40it/s]

 92%|█████████▏| 5529/6015 [38:22<03:22,  2.40it/s]

 92%|█████████▏| 5530/6015 [38:22<03:22,  2.39it/s]

 92%|█████████▏| 5531/6015 [38:23<03:22,  2.39it/s]

 92%|█████████▏| 5532/6015 [38:23<03:22,  2.39it/s]

 92%|█████████▏| 5533/6015 [38:23<03:21,  2.39it/s]

 92%|█████████▏| 5534/6015 [38:24<03:21,  2.39it/s]

 92%|█████████▏| 5535/6015 [38:24<03:21,  2.39it/s]

 92%|█████████▏| 5536/6015 [38:25<03:20,  2.39it/s]

 92%|█████████▏| 5537/6015 [38:25<03:20,  2.39it/s]

 92%|█████████▏| 5538/6015 [38:26<03:19,  2.39it/s]

 92%|█████████▏| 5539/6015 [38:26<03:19,  2.39it/s]

 92%|█████████▏| 5540/6015 [38:26<03:18,  2.39it/s]

 92%|█████████▏| 5541/6015 [38:27<03:18,  2.39it/s]

 92%|█████████▏| 5542/6015 [38:27<03:17,  2.39it/s]

 92%|█████████▏| 5543/6015 [38:28<03:17,  2.39it/s]

 92%|█████████▏| 5544/6015 [38:28<03:17,  2.39it/s]

 92%|█████████▏| 5545/6015 [38:29<03:16,  2.39it/s]

 92%|█████████▏| 5546/6015 [38:29<03:16,  2.39it/s]

 92%|█████████▏| 5547/6015 [38:29<03:15,  2.39it/s]

 92%|█████████▏| 5548/6015 [38:30<03:15,  2.39it/s]

 92%|█████████▏| 5549/6015 [38:30<03:14,  2.39it/s]

 92%|█████████▏| 5550/6015 [38:31<03:14,  2.39it/s]

 92%|█████████▏| 5551/6015 [38:31<03:14,  2.39it/s]

 92%|█████████▏| 5552/6015 [38:31<03:13,  2.39it/s]

 92%|█████████▏| 5553/6015 [38:32<03:13,  2.39it/s]

 92%|█████████▏| 5554/6015 [38:32<03:12,  2.39it/s]

 92%|█████████▏| 5555/6015 [38:33<03:12,  2.39it/s]

 92%|█████████▏| 5556/6015 [38:33<03:12,  2.39it/s]

 92%|█████████▏| 5557/6015 [38:34<03:12,  2.38it/s]

 92%|█████████▏| 5558/6015 [38:34<03:11,  2.39it/s]

 92%|█████████▏| 5559/6015 [38:34<03:10,  2.39it/s]

 92%|█████████▏| 5560/6015 [38:35<03:10,  2.39it/s]

 92%|█████████▏| 5561/6015 [38:35<03:09,  2.39it/s]

 92%|█████████▏| 5562/6015 [38:36<03:09,  2.39it/s]

 92%|█████████▏| 5563/6015 [38:36<03:09,  2.39it/s]

 93%|█████████▎| 5564/6015 [38:36<03:08,  2.39it/s]

 93%|█████████▎| 5565/6015 [38:37<03:08,  2.39it/s]

 93%|█████████▎| 5566/6015 [38:37<03:07,  2.39it/s]

 93%|█████████▎| 5567/6015 [38:38<03:07,  2.39it/s]

 93%|█████████▎| 5568/6015 [38:38<03:06,  2.39it/s]

 93%|█████████▎| 5569/6015 [38:39<03:06,  2.39it/s]

 93%|█████████▎| 5570/6015 [38:39<03:06,  2.39it/s]

 93%|█████████▎| 5571/6015 [38:39<03:05,  2.39it/s]

 93%|█████████▎| 5572/6015 [38:40<03:05,  2.39it/s]

 93%|█████████▎| 5573/6015 [38:40<03:04,  2.39it/s]

 93%|█████████▎| 5574/6015 [38:41<03:04,  2.39it/s]

 93%|█████████▎| 5575/6015 [38:41<03:04,  2.39it/s]

 93%|█████████▎| 5576/6015 [38:41<03:03,  2.39it/s]

 93%|█████████▎| 5577/6015 [38:42<03:03,  2.39it/s]

 93%|█████████▎| 5578/6015 [38:42<03:02,  2.39it/s]

 93%|█████████▎| 5579/6015 [38:43<03:02,  2.39it/s]

 93%|█████████▎| 5580/6015 [38:43<03:02,  2.39it/s]

 93%|█████████▎| 5581/6015 [38:44<03:01,  2.39it/s]

 93%|█████████▎| 5582/6015 [38:44<03:01,  2.39it/s]

 93%|█████████▎| 5583/6015 [38:44<03:00,  2.39it/s]

 93%|█████████▎| 5584/6015 [38:45<03:00,  2.39it/s]

 93%|█████████▎| 5585/6015 [38:45<02:59,  2.39it/s]

 93%|█████████▎| 5586/6015 [38:46<02:59,  2.39it/s]

 93%|█████████▎| 5587/6015 [38:46<02:58,  2.39it/s]

 93%|█████████▎| 5588/6015 [38:46<02:58,  2.39it/s]

 93%|█████████▎| 5589/6015 [38:47<02:58,  2.39it/s]

 93%|█████████▎| 5590/6015 [38:47<02:57,  2.39it/s]

 93%|█████████▎| 5591/6015 [38:48<02:57,  2.39it/s]

 93%|█████████▎| 5592/6015 [38:48<02:57,  2.39it/s]

 93%|█████████▎| 5593/6015 [38:49<02:56,  2.39it/s]

 93%|█████████▎| 5594/6015 [38:49<02:56,  2.39it/s]

 93%|█████████▎| 5595/6015 [38:49<02:55,  2.39it/s]

 93%|█████████▎| 5596/6015 [38:50<02:55,  2.39it/s]

 93%|█████████▎| 5597/6015 [38:50<02:55,  2.39it/s]

 93%|█████████▎| 5598/6015 [38:51<02:54,  2.39it/s]

 93%|█████████▎| 5599/6015 [38:51<02:53,  2.39it/s]

 93%|█████████▎| 5600/6015 [38:52<02:53,  2.39it/s]

 93%|█████████▎| 5601/6015 [38:52<02:53,  2.39it/s]

 93%|█████████▎| 5602/6015 [38:52<02:52,  2.39it/s]

 93%|█████████▎| 5603/6015 [38:53<02:52,  2.39it/s]

 93%|█████████▎| 5604/6015 [38:53<02:52,  2.39it/s]

 93%|█████████▎| 5605/6015 [38:54<02:51,  2.39it/s]

 93%|█████████▎| 5606/6015 [38:54<02:51,  2.39it/s]

 93%|█████████▎| 5607/6015 [38:54<02:50,  2.39it/s]

 93%|█████████▎| 5608/6015 [38:55<02:50,  2.39it/s]

 93%|█████████▎| 5609/6015 [38:55<02:50,  2.39it/s]

 93%|█████████▎| 5610/6015 [38:56<02:49,  2.39it/s]

 93%|█████████▎| 5611/6015 [38:56<02:49,  2.39it/s]

 93%|█████████▎| 5612/6015 [38:57<02:48,  2.39it/s]

 93%|█████████▎| 5613/6015 [38:57<02:48,  2.39it/s]

 93%|█████████▎| 5614/6015 [38:57<02:47,  2.39it/s]

 93%|█████████▎| 5615/6015 [38:58<02:47,  2.39it/s]

 93%|█████████▎| 5616/6015 [38:58<02:46,  2.39it/s]

 93%|█████████▎| 5617/6015 [38:59<02:46,  2.39it/s]

 93%|█████████▎| 5618/6015 [38:59<02:46,  2.39it/s]

 93%|█████████▎| 5619/6015 [38:59<02:45,  2.39it/s]

 93%|█████████▎| 5620/6015 [39:00<02:45,  2.39it/s]

 93%|█████████▎| 5621/6015 [39:00<02:45,  2.39it/s]

 93%|█████████▎| 5622/6015 [39:01<02:44,  2.38it/s]

 93%|█████████▎| 5623/6015 [39:01<02:44,  2.38it/s]

 93%|█████████▎| 5624/6015 [39:02<02:43,  2.39it/s]

 94%|█████████▎| 5625/6015 [39:02<02:43,  2.39it/s]

 94%|█████████▎| 5626/6015 [39:02<02:42,  2.39it/s]

 94%|█████████▎| 5627/6015 [39:03<02:42,  2.39it/s]

 94%|█████████▎| 5628/6015 [39:03<02:41,  2.39it/s]

 94%|█████████▎| 5629/6015 [39:04<02:41,  2.39it/s]

 94%|█████████▎| 5630/6015 [39:04<02:41,  2.39it/s]

 94%|█████████▎| 5631/6015 [39:04<02:40,  2.39it/s]

 94%|█████████▎| 5632/6015 [39:05<02:40,  2.39it/s]

 94%|█████████▎| 5633/6015 [39:05<02:39,  2.39it/s]

logging
logging the anndata

 94%|█████████▎| 5634/6015 [39:06<02:45,  2.30it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 94%|█████████▎| 5635/6015 [39:06<02:42,  2.33it/s]

 94%|█████████▎| 5636/6015 [39:07<02:40,  2.36it/s]

 94%|█████████▎| 5637/6015 [39:07<02:38,  2.38it/s]

 94%|█████████▎| 5638/6015 [39:07<02:37,  2.40it/s]

 94%|█████████▎| 5639/6015 [39:08<02:36,  2.41it/s]

 94%|█████████▍| 5640/6015 [39:08<02:35,  2.41it/s]

 94%|█████████▍| 5641/6015 [39:09<02:34,  2.42it/s]

 94%|█████████▍| 5642/6015 [39:09<02:34,  2.42it/s]

 94%|█████████▍| 5643/6015 [39:10<02:33,  2.42it/s]

 94%|█████████▍| 5644/6015 [39:10<02:32,  2.43it/s]

 94%|█████████▍| 5645/6015 [39:10<02:32,  2.43it/s]

 94%|█████████▍| 5646/6015 [39:11<02:31,  2.43it/s]

 94%|█████████▍| 5647/6015 [39:11<02:31,  2.43it/s]

 94%|█████████▍| 5648/6015 [39:12<02:31,  2.43it/s]

 94%|█████████▍| 5649/6015 [39:12<02:30,  2.43it/s]

 94%|█████████▍| 5650/6015 [39:12<02:30,  2.43it/s]

 94%|█████████▍| 5651/6015 [39:13<02:29,  2.43it/s]

 94%|█████████▍| 5652/6015 [39:13<02:29,  2.43it/s]

 94%|█████████▍| 5653/6015 [39:14<02:29,  2.43it/s]

 94%|█████████▍| 5654/6015 [39:14<02:28,  2.43it/s]

 94%|█████████▍| 5655/6015 [39:14<02:28,  2.43it/s]

 94%|█████████▍| 5656/6015 [39:15<02:27,  2.43it/s]

 94%|█████████▍| 5657/6015 [39:15<02:27,  2.43it/s]

 94%|█████████▍| 5658/6015 [39:16<02:27,  2.43it/s]

 94%|█████████▍| 5659/6015 [39:16<02:26,  2.43it/s]

 94%|█████████▍| 5660/6015 [39:17<02:26,  2.43it/s]

 94%|█████████▍| 5661/6015 [39:17<02:25,  2.43it/s]

 94%|█████████▍| 5662/6015 [39:17<02:25,  2.43it/s]

 94%|█████████▍| 5663/6015 [39:18<02:24,  2.43it/s]

 94%|█████████▍| 5664/6015 [39:18<02:24,  2.43it/s]

 94%|█████████▍| 5665/6015 [39:19<02:24,  2.43it/s]

 94%|█████████▍| 5666/6015 [39:19<02:23,  2.43it/s]

 94%|█████████▍| 5667/6015 [39:19<02:23,  2.43it/s]

 94%|█████████▍| 5668/6015 [39:20<02:23,  2.43it/s]

 94%|█████████▍| 5669/6015 [39:20<02:22,  2.43it/s]

 94%|█████████▍| 5670/6015 [39:21<02:22,  2.43it/s]

 94%|█████████▍| 5671/6015 [39:21<02:21,  2.43it/s]

 94%|█████████▍| 5672/6015 [39:21<02:21,  2.43it/s]

 94%|█████████▍| 5673/6015 [39:22<02:20,  2.43it/s]

 94%|█████████▍| 5674/6015 [39:22<02:20,  2.43it/s]

 94%|█████████▍| 5675/6015 [39:23<02:19,  2.43it/s]

 94%|█████████▍| 5676/6015 [39:23<02:19,  2.43it/s]

 94%|█████████▍| 5677/6015 [39:24<02:19,  2.43it/s]

 94%|█████████▍| 5678/6015 [39:24<02:18,  2.43it/s]

 94%|█████████▍| 5679/6015 [39:24<02:18,  2.43it/s]

 94%|█████████▍| 5680/6015 [39:25<02:18,  2.43it/s]

 94%|█████████▍| 5681/6015 [39:25<02:17,  2.43it/s]

 94%|█████████▍| 5682/6015 [39:26<02:17,  2.43it/s]

 94%|█████████▍| 5683/6015 [39:26<02:16,  2.43it/s]

 94%|█████████▍| 5684/6015 [39:26<02:16,  2.42it/s]

 95%|█████████▍| 5685/6015 [39:27<02:16,  2.42it/s]

 95%|█████████▍| 5686/6015 [39:27<02:15,  2.43it/s]

 95%|█████████▍| 5687/6015 [39:28<02:15,  2.43it/s]

 95%|█████████▍| 5688/6015 [39:28<02:14,  2.43it/s]

 95%|█████████▍| 5689/6015 [39:28<02:14,  2.42it/s]

 95%|█████████▍| 5690/6015 [39:29<02:13,  2.43it/s]

 95%|█████████▍| 5691/6015 [39:29<02:13,  2.43it/s]

 95%|█████████▍| 5692/6015 [39:30<02:13,  2.43it/s]

 95%|█████████▍| 5693/6015 [39:30<02:12,  2.43it/s]

 95%|█████████▍| 5694/6015 [39:31<02:12,  2.43it/s]

 95%|█████████▍| 5695/6015 [39:31<02:12,  2.42it/s]

 95%|█████████▍| 5696/6015 [39:31<02:11,  2.42it/s]

 95%|█████████▍| 5697/6015 [39:32<02:11,  2.42it/s]

 95%|█████████▍| 5698/6015 [39:32<02:10,  2.42it/s]

 95%|█████████▍| 5699/6015 [39:33<02:10,  2.42it/s]

 95%|█████████▍| 5700/6015 [39:33<02:10,  2.42it/s]

 95%|█████████▍| 5701/6015 [39:33<02:09,  2.42it/s]

 95%|█████████▍| 5702/6015 [39:34<02:09,  2.42it/s]

 95%|█████████▍| 5703/6015 [39:34<02:08,  2.42it/s]

 95%|█████████▍| 5704/6015 [39:35<02:08,  2.42it/s]

 95%|█████████▍| 5705/6015 [39:35<02:07,  2.43it/s]

 95%|█████████▍| 5706/6015 [39:35<02:07,  2.42it/s]

 95%|█████████▍| 5707/6015 [39:36<02:07,  2.42it/s]

 95%|█████████▍| 5708/6015 [39:36<02:06,  2.42it/s]

 95%|█████████▍| 5709/6015 [39:37<02:06,  2.42it/s]

 95%|█████████▍| 5710/6015 [39:37<02:06,  2.42it/s]

 95%|█████████▍| 5711/6015 [39:38<02:05,  2.42it/s]

 95%|█████████▍| 5712/6015 [39:38<02:04,  2.42it/s]

 95%|█████████▍| 5713/6015 [39:38<02:04,  2.42it/s]

 95%|█████████▍| 5714/6015 [39:39<02:04,  2.42it/s]

 95%|█████████▌| 5715/6015 [39:39<02:03,  2.42it/s]

 95%|█████████▌| 5716/6015 [39:40<02:03,  2.42it/s]

 95%|█████████▌| 5717/6015 [39:40<02:03,  2.42it/s]

 95%|█████████▌| 5718/6015 [39:40<02:02,  2.42it/s]

 95%|█████████▌| 5719/6015 [39:41<02:02,  2.42it/s]

 95%|█████████▌| 5720/6015 [39:41<02:01,  2.42it/s]

 95%|█████████▌| 5721/6015 [39:42<02:01,  2.42it/s]

 95%|█████████▌| 5722/6015 [39:42<02:01,  2.42it/s]

 95%|█████████▌| 5723/6015 [39:42<02:00,  2.42it/s]

 95%|█████████▌| 5724/6015 [39:43<02:00,  2.42it/s]

 95%|█████████▌| 5725/6015 [39:43<01:59,  2.42it/s]

 95%|█████████▌| 5726/6015 [39:44<01:59,  2.42it/s]

 95%|█████████▌| 5727/6015 [39:44<01:59,  2.41it/s]

 95%|█████████▌| 5728/6015 [39:45<01:58,  2.42it/s]

 95%|█████████▌| 5729/6015 [39:45<01:58,  2.42it/s]

 95%|█████████▌| 5730/6015 [39:45<01:57,  2.42it/s]

 95%|█████████▌| 5731/6015 [39:46<01:57,  2.42it/s]

 95%|█████████▌| 5732/6015 [39:46<01:56,  2.42it/s]

 95%|█████████▌| 5733/6015 [39:47<01:56,  2.42it/s]

 95%|█████████▌| 5734/6015 [39:47<01:56,  2.42it/s]

 95%|█████████▌| 5735/6015 [39:47<01:55,  2.42it/s]

 95%|█████████▌| 5736/6015 [39:48<01:55,  2.42it/s]

 95%|█████████▌| 5737/6015 [39:48<01:55,  2.41it/s]

 95%|█████████▌| 5738/6015 [39:49<01:54,  2.42it/s]

 95%|█████████▌| 5739/6015 [39:49<01:54,  2.42it/s]

 95%|█████████▌| 5740/6015 [39:50<01:53,  2.42it/s]

 95%|█████████▌| 5741/6015 [39:50<01:53,  2.42it/s]

 95%|█████████▌| 5742/6015 [39:50<01:52,  2.42it/s]

 95%|█████████▌| 5743/6015 [39:51<01:52,  2.42it/s]

 95%|█████████▌| 5744/6015 [39:51<01:51,  2.42it/s]

 96%|█████████▌| 5745/6015 [39:52<01:51,  2.42it/s]

 96%|█████████▌| 5746/6015 [39:52<01:51,  2.42it/s]

 96%|█████████▌| 5747/6015 [39:52<01:50,  2.42it/s]

 96%|█████████▌| 5748/6015 [39:53<01:50,  2.42it/s]

 96%|█████████▌| 5749/6015 [39:53<01:49,  2.42it/s]

 96%|█████████▌| 5750/6015 [39:54<01:49,  2.42it/s]

 96%|█████████▌| 5751/6015 [39:54<01:49,  2.42it/s]

 96%|█████████▌| 5752/6015 [39:54<01:48,  2.42it/s]

 96%|█████████▌| 5753/6015 [39:55<01:48,  2.42it/s]

 96%|█████████▌| 5754/6015 [39:55<01:47,  2.42it/s]

 96%|█████████▌| 5755/6015 [39:56<01:47,  2.42it/s]

 96%|█████████▌| 5756/6015 [39:56<01:47,  2.42it/s]

 96%|█████████▌| 5757/6015 [39:57<01:46,  2.42it/s]

 96%|█████████▌| 5758/6015 [39:57<01:46,  2.42it/s]

 96%|█████████▌| 5759/6015 [39:57<01:45,  2.42it/s]

 96%|█████████▌| 5760/6015 [39:58<01:45,  2.42it/s]

 96%|█████████▌| 5761/6015 [39:58<01:44,  2.42it/s]

 96%|█████████▌| 5762/6015 [39:59<01:44,  2.42it/s]

 96%|█████████▌| 5763/6015 [39:59<01:44,  2.42it/s]

 96%|█████████▌| 5764/6015 [39:59<01:43,  2.42it/s]

 96%|█████████▌| 5765/6015 [40:00<01:43,  2.42it/s]

 96%|█████████▌| 5766/6015 [40:00<01:42,  2.42it/s]

 96%|█████████▌| 5767/6015 [40:01<01:42,  2.42it/s]

 96%|█████████▌| 5768/6015 [40:01<01:42,  2.42it/s]

 96%|█████████▌| 5769/6015 [40:02<01:41,  2.42it/s]

 96%|█████████▌| 5770/6015 [40:02<01:41,  2.42it/s]

 96%|█████████▌| 5771/6015 [40:02<01:40,  2.42it/s]

 96%|█████████▌| 5772/6015 [40:03<01:40,  2.42it/s]

 96%|█████████▌| 5773/6015 [40:03<01:40,  2.42it/s]

 96%|█████████▌| 5774/6015 [40:04<01:39,  2.42it/s]

 96%|█████████▌| 5775/6015 [40:04<01:39,  2.42it/s]

 96%|█████████▌| 5776/6015 [40:04<01:38,  2.42it/s]

 96%|█████████▌| 5777/6015 [40:05<01:38,  2.42it/s]

 96%|█████████▌| 5778/6015 [40:05<01:37,  2.42it/s]

 96%|█████████▌| 5779/6015 [40:06<01:37,  2.42it/s]

 96%|█████████▌| 5780/6015 [40:06<01:37,  2.42it/s]

 96%|█████████▌| 5781/6015 [40:06<01:36,  2.42it/s]

 96%|█████████▌| 5782/6015 [40:07<01:36,  2.42it/s]

 96%|█████████▌| 5783/6015 [40:07<01:35,  2.42it/s]

 96%|█████████▌| 5784/6015 [40:08<01:35,  2.42it/s]

 96%|█████████▌| 5785/6015 [40:08<01:35,  2.41it/s]

 96%|█████████▌| 5786/6015 [40:09<01:34,  2.42it/s]

 96%|█████████▌| 5787/6015 [40:09<01:34,  2.42it/s]

 96%|█████████▌| 5788/6015 [40:09<01:33,  2.42it/s]

 96%|█████████▌| 5789/6015 [40:10<01:33,  2.42it/s]

 96%|█████████▋| 5790/6015 [40:10<01:32,  2.42it/s]

 96%|█████████▋| 5791/6015 [40:11<01:32,  2.42it/s]

 96%|█████████▋| 5792/6015 [40:11<01:32,  2.42it/s]

 96%|█████████▋| 5793/6015 [40:11<01:31,  2.42it/s]

 96%|█████████▋| 5794/6015 [40:12<01:31,  2.42it/s]

 96%|█████████▋| 5795/6015 [40:12<01:30,  2.42it/s]

 96%|█████████▋| 5796/6015 [40:13<01:30,  2.42it/s]

 96%|█████████▋| 5797/6015 [40:13<01:29,  2.42it/s]

 96%|█████████▋| 5798/6015 [40:13<01:29,  2.42it/s]

 96%|█████████▋| 5799/6015 [40:14<01:29,  2.42it/s]

 96%|█████████▋| 5800/6015 [40:14<01:29,  2.41it/s]

 96%|█████████▋| 5801/6015 [40:15<01:28,  2.42it/s]

 96%|█████████▋| 5802/6015 [40:15<01:28,  2.41it/s]

 96%|█████████▋| 5803/6015 [40:16<01:27,  2.42it/s]

 96%|█████████▋| 5804/6015 [40:16<01:27,  2.42it/s]

 97%|█████████▋| 5805/6015 [40:16<01:26,  2.42it/s]

 97%|█████████▋| 5806/6015 [40:17<01:26,  2.42it/s]

 97%|█████████▋| 5807/6015 [40:17<01:26,  2.41it/s]

 97%|█████████▋| 5808/6015 [40:18<01:25,  2.41it/s]

 97%|█████████▋| 5809/6015 [40:18<01:25,  2.42it/s]

 97%|█████████▋| 5810/6015 [40:18<01:24,  2.42it/s]

 97%|█████████▋| 5811/6015 [40:19<01:24,  2.42it/s]

 97%|█████████▋| 5812/6015 [40:19<01:23,  2.42it/s]

 97%|█████████▋| 5813/6015 [40:20<01:23,  2.42it/s]

 97%|█████████▋| 5814/6015 [40:20<01:23,  2.42it/s]

 97%|█████████▋| 5815/6015 [40:21<01:22,  2.42it/s]

 97%|█████████▋| 5816/6015 [40:21<01:22,  2.42it/s]

 97%|█████████▋| 5817/6015 [40:21<01:21,  2.42it/s]

 97%|█████████▋| 5818/6015 [40:22<01:21,  2.42it/s]

 97%|█████████▋| 5819/6015 [40:22<01:21,  2.42it/s]

 97%|█████████▋| 5820/6015 [40:23<01:20,  2.42it/s]

 97%|█████████▋| 5821/6015 [40:23<01:20,  2.42it/s]

 97%|█████████▋| 5822/6015 [40:23<01:19,  2.42it/s]

 97%|█████████▋| 5823/6015 [40:24<01:19,  2.42it/s]

 97%|█████████▋| 5824/6015 [40:24<01:19,  2.41it/s]

 97%|█████████▋| 5825/6015 [40:25<01:18,  2.42it/s]

 97%|█████████▋| 5826/6015 [40:25<01:18,  2.42it/s]

 97%|█████████▋| 5827/6015 [40:25<01:17,  2.42it/s]

 97%|█████████▋| 5828/6015 [40:26<01:17,  2.42it/s]

 97%|█████████▋| 5829/6015 [40:26<01:16,  2.42it/s]

 97%|█████████▋| 5830/6015 [40:27<01:16,  2.42it/s]

 97%|█████████▋| 5831/6015 [40:27<01:16,  2.42it/s]

 97%|█████████▋| 5832/6015 [40:28<01:15,  2.42it/s]

 97%|█████████▋| 5833/6015 [40:28<01:15,  2.42it/s]

 97%|█████████▋| 5834/6015 [40:28<01:14,  2.42it/s]

 97%|█████████▋| 5835/6015 [40:29<01:14,  2.42it/s]

 97%|█████████▋| 5836/6015 [40:29<01:14,  2.41it/s]

 97%|█████████▋| 5837/6015 [40:30<01:13,  2.41it/s]

 97%|█████████▋| 5838/6015 [40:30<01:13,  2.41it/s]

 97%|█████████▋| 5839/6015 [40:30<01:12,  2.41it/s]

 97%|█████████▋| 5840/6015 [40:31<01:12,  2.42it/s]

 97%|█████████▋| 5841/6015 [40:31<01:12,  2.42it/s]

 97%|█████████▋| 5842/6015 [40:32<01:11,  2.42it/s]

 97%|█████████▋| 5843/6015 [40:32<01:11,  2.42it/s]

 97%|█████████▋| 5844/6015 [40:33<01:10,  2.42it/s]

 97%|█████████▋| 5845/6015 [40:33<01:10,  2.42it/s]

 97%|█████████▋| 5846/6015 [40:33<01:09,  2.42it/s]

 97%|█████████▋| 5847/6015 [40:34<01:09,  2.42it/s]

 97%|█████████▋| 5848/6015 [40:34<01:09,  2.42it/s]

 97%|█████████▋| 5849/6015 [40:35<01:08,  2.41it/s]

 97%|█████████▋| 5850/6015 [40:35<01:08,  2.42it/s]

 97%|█████████▋| 5851/6015 [40:35<01:07,  2.41it/s]

 97%|█████████▋| 5852/6015 [40:36<01:07,  2.42it/s]

 97%|█████████▋| 5853/6015 [40:36<01:07,  2.42it/s]

 97%|█████████▋| 5854/6015 [40:37<01:06,  2.42it/s]

 97%|█████████▋| 5855/6015 [40:37<01:06,  2.42it/s]

 97%|█████████▋| 5856/6015 [40:37<01:05,  2.42it/s]

 97%|█████████▋| 5857/6015 [40:38<01:05,  2.42it/s]

 97%|█████████▋| 5858/6015 [40:38<01:04,  2.42it/s]

 97%|█████████▋| 5859/6015 [40:39<01:04,  2.41it/s]

 97%|█████████▋| 5860/6015 [40:39<01:04,  2.41it/s]

 97%|█████████▋| 5861/6015 [40:40<01:03,  2.42it/s]

 97%|█████████▋| 5862/6015 [40:40<01:03,  2.41it/s]

 97%|█████████▋| 5863/6015 [40:40<01:02,  2.42it/s]

 97%|█████████▋| 5864/6015 [40:41<01:02,  2.41it/s]

 98%|█████████▊| 5865/6015 [40:41<01:02,  2.41it/s]

 98%|█████████▊| 5866/6015 [40:42<01:01,  2.41it/s]

 98%|█████████▊| 5867/6015 [40:42<01:01,  2.41it/s]

 98%|█████████▊| 5868/6015 [40:42<01:00,  2.42it/s]

 98%|█████████▊| 5869/6015 [40:43<01:00,  2.42it/s]

 98%|█████████▊| 5870/6015 [40:43<01:00,  2.41it/s]

 98%|█████████▊| 5871/6015 [40:44<00:59,  2.42it/s]

 98%|█████████▊| 5872/6015 [40:44<00:59,  2.42it/s]

 98%|█████████▊| 5873/6015 [40:45<00:58,  2.42it/s]

 98%|█████████▊| 5874/6015 [40:45<00:58,  2.42it/s]

 98%|█████████▊| 5875/6015 [40:45<00:57,  2.42it/s]

 98%|█████████▊| 5876/6015 [40:46<00:57,  2.42it/s]

 98%|█████████▊| 5877/6015 [40:46<00:57,  2.42it/s]

 98%|█████████▊| 5878/6015 [40:47<00:56,  2.42it/s]

 98%|█████████▊| 5879/6015 [40:47<00:56,  2.41it/s]

 98%|█████████▊| 5880/6015 [40:47<00:55,  2.42it/s]

 98%|█████████▊| 5881/6015 [40:48<00:55,  2.41it/s]

 98%|█████████▊| 5882/6015 [40:48<00:55,  2.41it/s]

 98%|█████████▊| 5883/6015 [40:49<00:54,  2.42it/s]

 98%|█████████▊| 5884/6015 [40:49<00:54,  2.41it/s]

 98%|█████████▊| 5885/6015 [40:50<00:53,  2.41it/s]

 98%|█████████▊| 5886/6015 [40:50<00:53,  2.41it/s]

 98%|█████████▊| 5887/6015 [40:50<00:53,  2.41it/s]

 98%|█████████▊| 5888/6015 [40:51<00:52,  2.41it/s]

 98%|█████████▊| 5889/6015 [40:51<00:52,  2.41it/s]

 98%|█████████▊| 5890/6015 [40:52<00:51,  2.41it/s]

 98%|█████████▊| 5891/6015 [40:52<00:51,  2.42it/s]

 98%|█████████▊| 5892/6015 [40:52<00:50,  2.41it/s]

 98%|█████████▊| 5893/6015 [40:53<00:50,  2.41it/s]

 98%|█████████▊| 5894/6015 [40:53<00:50,  2.41it/s]

 98%|█████████▊| 5895/6015 [40:54<00:49,  2.41it/s]

 98%|█████████▊| 5896/6015 [40:54<00:49,  2.41it/s]

 98%|█████████▊| 5897/6015 [40:54<00:48,  2.41it/s]

 98%|█████████▊| 5898/6015 [40:55<00:48,  2.41it/s]

 98%|█████████▊| 5899/6015 [40:55<00:48,  2.41it/s]

 98%|█████████▊| 5900/6015 [40:56<00:47,  2.41it/s]

 98%|█████████▊| 5901/6015 [40:56<00:47,  2.42it/s]

 98%|█████████▊| 5902/6015 [40:57<00:46,  2.42it/s]

 98%|█████████▊| 5903/6015 [40:57<00:46,  2.42it/s]

 98%|█████████▊| 5904/6015 [40:57<00:45,  2.41it/s]

 98%|█████████▊| 5905/6015 [40:58<00:45,  2.41it/s]

 98%|█████████▊| 5906/6015 [40:58<00:45,  2.41it/s]

 98%|█████████▊| 5907/6015 [40:59<00:44,  2.41it/s]

 98%|█████████▊| 5908/6015 [40:59<00:44,  2.42it/s]

 98%|█████████▊| 5909/6015 [40:59<00:43,  2.41it/s]

 98%|█████████▊| 5910/6015 [41:00<00:43,  2.41it/s]

 98%|█████████▊| 5911/6015 [41:00<00:43,  2.41it/s]

 98%|█████████▊| 5912/6015 [41:01<00:42,  2.42it/s]

 98%|█████████▊| 5913/6015 [41:01<00:42,  2.41it/s]

 98%|█████████▊| 5914/6015 [41:02<00:41,  2.41it/s]

 98%|█████████▊| 5915/6015 [41:02<00:41,  2.41it/s]

 98%|█████████▊| 5916/6015 [41:02<00:41,  2.41it/s]

 98%|█████████▊| 5917/6015 [41:03<00:40,  2.41it/s]

 98%|█████████▊| 5918/6015 [41:03<00:40,  2.41it/s]

 98%|█████████▊| 5919/6015 [41:04<00:39,  2.41it/s]

 98%|█████████▊| 5920/6015 [41:04<00:39,  2.41it/s]

 98%|█████████▊| 5921/6015 [41:04<00:38,  2.41it/s]

 98%|█████████▊| 5922/6015 [41:05<00:38,  2.41it/s]

 98%|█████████▊| 5923/6015 [41:05<00:38,  2.41it/s]

 98%|█████████▊| 5924/6015 [41:06<00:37,  2.41it/s]

 99%|█████████▊| 5925/6015 [41:06<00:37,  2.41it/s]

 99%|█████████▊| 5926/6015 [41:06<00:36,  2.41it/s]

 99%|█████████▊| 5927/6015 [41:07<00:36,  2.41it/s]

 99%|█████████▊| 5928/6015 [41:07<00:36,  2.41it/s]

 99%|█████████▊| 5929/6015 [41:08<00:35,  2.41it/s]

 99%|█████████▊| 5930/6015 [41:08<00:35,  2.41it/s]

 99%|█████████▊| 5931/6015 [41:09<00:34,  2.41it/s]

 99%|█████████▊| 5932/6015 [41:09<00:34,  2.41it/s]

 99%|█████████▊| 5933/6015 [41:09<00:34,  2.41it/s]

 99%|█████████▊| 5934/6015 [41:10<00:33,  2.40it/s]

 99%|█████████▊| 5935/6015 [41:10<00:33,  2.41it/s]

 99%|█████████▊| 5936/6015 [41:11<00:32,  2.41it/s]

 99%|█████████▊| 5937/6015 [41:11<00:32,  2.41it/s]

 99%|█████████▊| 5938/6015 [41:11<00:31,  2.41it/s]

 99%|█████████▊| 5939/6015 [41:12<00:31,  2.41it/s]

 99%|█████████▉| 5940/6015 [41:12<00:31,  2.41it/s]

 99%|█████████▉| 5941/6015 [41:13<00:30,  2.41it/s]

 99%|█████████▉| 5942/6015 [41:13<00:30,  2.41it/s]

 99%|█████████▉| 5943/6015 [41:14<00:29,  2.41it/s]

 99%|█████████▉| 5944/6015 [41:14<00:29,  2.41it/s]

 99%|█████████▉| 5945/6015 [41:14<00:29,  2.41it/s]

 99%|█████████▉| 5946/6015 [41:15<00:28,  2.41it/s]

 99%|█████████▉| 5947/6015 [41:15<00:28,  2.41it/s]

 99%|█████████▉| 5948/6015 [41:16<00:27,  2.41it/s]

 99%|█████████▉| 5949/6015 [41:16<00:27,  2.41it/s]

 99%|█████████▉| 5950/6015 [41:16<00:26,  2.41it/s]

 99%|█████████▉| 5951/6015 [41:17<00:26,  2.41it/s]

 99%|█████████▉| 5952/6015 [41:17<00:26,  2.41it/s]

 99%|█████████▉| 5953/6015 [41:18<00:25,  2.41it/s]

 99%|█████████▉| 5954/6015 [41:18<00:25,  2.41it/s]

 99%|█████████▉| 5955/6015 [41:19<00:24,  2.40it/s]

 99%|█████████▉| 5956/6015 [41:19<00:24,  2.41it/s]

 99%|█████████▉| 5957/6015 [41:19<00:24,  2.41it/s]

 99%|█████████▉| 5958/6015 [41:20<00:23,  2.41it/s]

 99%|█████████▉| 5959/6015 [41:20<00:23,  2.41it/s]

 99%|█████████▉| 5960/6015 [41:21<00:22,  2.40it/s]

 99%|█████████▉| 5961/6015 [41:21<00:22,  2.40it/s]

 99%|█████████▉| 5962/6015 [41:21<00:22,  2.40it/s]

 99%|█████████▉| 5963/6015 [41:22<00:21,  2.40it/s]

 99%|█████████▉| 5964/6015 [41:22<00:21,  2.40it/s]

 99%|█████████▉| 5965/6015 [41:23<00:20,  2.40it/s]

 99%|█████████▉| 5966/6015 [41:23<00:20,  2.41it/s]

 99%|█████████▉| 5967/6015 [41:24<00:19,  2.40it/s]

 99%|█████████▉| 5968/6015 [41:24<00:19,  2.41it/s]

 99%|█████████▉| 5969/6015 [41:24<00:19,  2.41it/s]

 99%|█████████▉| 5970/6015 [41:25<00:18,  2.41it/s]

 99%|█████████▉| 5971/6015 [41:25<00:18,  2.41it/s]

 99%|█████████▉| 5972/6015 [41:26<00:17,  2.41it/s]

 99%|█████████▉| 5973/6015 [41:26<00:17,  2.41it/s]

 99%|█████████▉| 5974/6015 [41:26<00:17,  2.41it/s]

 99%|█████████▉| 5975/6015 [41:27<00:16,  2.40it/s]

 99%|█████████▉| 5976/6015 [41:27<00:16,  2.41it/s]

 99%|█████████▉| 5977/6015 [41:28<00:15,  2.41it/s]

 99%|█████████▉| 5978/6015 [41:28<00:15,  2.40it/s]

 99%|█████████▉| 5979/6015 [41:29<00:14,  2.40it/s]

 99%|█████████▉| 5980/6015 [41:29<00:14,  2.41it/s]

 99%|█████████▉| 5981/6015 [41:29<00:14,  2.41it/s]

 99%|█████████▉| 5982/6015 [41:30<00:13,  2.41it/s]

 99%|█████████▉| 5983/6015 [41:30<00:13,  2.41it/s]

 99%|█████████▉| 5984/6015 [41:31<00:12,  2.41it/s]

100%|█████████▉| 5985/6015 [41:31<00:12,  2.41it/s]

100%|█████████▉| 5986/6015 [41:31<00:12,  2.41it/s]

100%|█████████▉| 5987/6015 [41:32<00:11,  2.41it/s]

100%|█████████▉| 5988/6015 [41:32<00:11,  2.41it/s]

100%|█████████▉| 5989/6015 [41:33<00:10,  2.41it/s]

100%|█████████▉| 5990/6015 [41:33<00:10,  2.40it/s]

100%|█████████▉| 5991/6015 [41:34<00:09,  2.40it/s]

100%|█████████▉| 5992/6015 [41:34<00:09,  2.40it/s]

100%|█████████▉| 5993/6015 [41:34<00:09,  2.41it/s]

100%|█████████▉| 5994/6015 [41:35<00:08,  2.40it/s]

100%|█████████▉| 5995/6015 [41:35<00:08,  2.40it/s]

100%|█████████▉| 5996/6015 [41:36<00:07,  2.40it/s]

100%|█████████▉| 5997/6015 [41:36<00:07,  2.40it/s]

100%|█████████▉| 5998/6015 [41:36<00:07,  2.40it/s]

100%|█████████▉| 5999/6015 [41:37<00:06,  2.40it/s]

100%|█████████▉| 6000/6015 [41:37<00:06,  2.40it/s]

100%|█████████▉| 6001/6015 [41:38<00:05,  2.40it/s]

100%|█████████▉| 6002/6015 [41:38<00:05,  2.40it/s]

100%|█████████▉| 6003/6015 [41:38<00:04,  2.41it/s]

100%|█████████▉| 6004/6015 [41:39<00:04,  2.41it/s]

100%|█████████▉| 6005/6015 [41:39<00:04,  2.41it/s]

100%|█████████▉| 6006/6015 [41:40<00:03,  2.40it/s]

100%|█████████▉| 6007/6015 [41:40<00:03,  2.41it/s]

100%|█████████▉| 6008/6015 [41:41<00:02,  2.41it/s]

100%|█████████▉| 6009/6015 [41:41<00:02,  2.40it/s]

100%|█████████▉| 6010/6015 [41:41<00:02,  2.40it/s]

100%|█████████▉| 6011/6015 [41:42<00:01,  2.41it/s]

100%|█████████▉| 6012/6015 [41:42<00:01,  2.41it/s]

100%|█████████▉| 6013/6015 [41:43<00:00,  2.41it/s]

100%|█████████▉| 6014/6015 [41:43<00:00,  2.41it/s]

100%|██████████| 6015/6015 [41:43<00:00,  2.83it/s]

100%|██████████| 6015/6015 [41:44<00:00,  2.40it/s]

logging the anndata
AnnData object with n_obs × n_vars = 24349 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

too few cells to embed into a umap
too few cells to compute a clustering

PairwiseArrays with keys: connectivities, distances

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.936544 -12.723997 -17.082058 ... -16.638536 -14.678699 -15.849062]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.814676  -13.414804  -13.6221485 ... -13.3795    -13.57051
 -13.728125 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.11241  -14.477257 -16.828802 ... -18.517233 -17.298765 -17.752962]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.968805 -11.981436 -14.636043 ... -14.348235 -13.175865 -13.971296]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.288264 -14.397164 -15.631826 ... -17.581015 -17.189272 -17.036139]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.594173 -13.281123 -13.453631 ... -13.209101 -13.373909 -13.502324]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.920115 -12.383987 -12.880531 ... -13.032032 -12.88476  -13.139544]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.64954  -17.70145  -16.876919 ... -18.229143 -18.598305 -18.952177]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.493206 -16.94889  -15.628522 ... -17.498947 -18.179478 -17.859762]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.736188 -16.774488 -15.782232 ... -17.3697   -17.61246  -17.426752]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.265089 -20.262619 -24.45929  ... -27.124426 -24.494125 -25.551224]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-28.987862 -26.159197 -29.517937 ... -27.253286 -25.662489 -27.87846 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.555761 -13.997547 -15.8786   ... -18.36659  -17.18512  -17.913944]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.079774 -13.377934 -14.729911 ... -12.431318 -12.043623 -13.460995]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.731758 -15.204903 -17.065613 ... -18.073156 -17.435823 -17.948744]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.6761756 2.9681447 3.6475143 ... 5.050996  4.5182476 4.8572307]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.488496   -7.7719245 -10.715005  ... -11.860871  -11.631931
 -11.520898 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.448072 -11.686531 -16.64716  ... -16.43634  -15.009713 -15.932243]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.21318    -3.8821344 -10.161862  ...  -8.786695   -6.170044
  -7.604664 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.017447 -14.689603 -14.798006 ... -17.859884 -17.459517 -17.437534]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.046488 -18.059    -19.901648 ... -19.864445 -19.377537 -20.856407]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.500931 -11.425809 -14.231429 ... -13.44596  -12.226186 -13.053683]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.947791 -9.938894 -9.634234 ... -8.854282 -8.882388 -9.855611]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.370932 -18.492212 -20.33529  ... -22.164986 -20.816187 -22.113773]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.775369  -13.857392  -14.873293  ... -11.4450445 -12.352082
 -13.075597 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.024378 -12.518906 -13.281144 ... -13.528808 -13.033866 -13.474256]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.610627  -7.8133197 -9.010269  ... -7.11458   -6.944924  -7.2556896]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.537471 -8.448647 -9.543247 ... -8.155886 -8.022179 -8.604139]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.968221  -7.784039  -8.754944  ... -6.740062  -7.0806546 -7.647237 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.604646  -9.661902 -10.350097 ...  -9.038558  -9.117466 -10.028059]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.252449  -15.050173  -13.8521595 ... -15.171235  -14.3129425
 -13.794124 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.483685 -18.480133 -18.630486 ... -23.772655 -22.495012 -22.376858]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.635206 -13.965159 -17.70209  ... -21.394567 -18.619644 -19.228249]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.611253 -16.809364 -15.829407 ... -18.953506 -19.299421 -18.218922]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.712352 -13.857354 -16.228127 ... -16.891558 -17.076136 -17.293682]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.462443  -13.459199  -13.000613  ... -14.1123295 -13.96628
 -13.579577 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.6295395  -9.255174   -9.233294  ...  -9.859871  -10.015299
 -10.623355 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.690399   -4.5251603  -7.9753904 ... -10.624789   -8.588683
 -10.072431 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.977062 -16.352627 -16.302948 ... -14.339013 -14.549397 -15.55476 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.033675  -4.40124   -8.569975 ... -12.05037   -9.537395 -11.149873]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.573534 -15.767016 -18.778164 ... -19.099619 -18.111591 -18.87855 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.071754  -9.918662 -10.64132  ...  -9.084727  -9.041492 -10.056355]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.803816 -15.408104 -17.919456 ... -19.438269 -18.285606 -19.323   ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.692249 -13.58642  -14.925502 ... -16.601393 -15.277733 -16.467613]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.441546 -11.741732 -14.293032 ... -13.835749 -12.551466 -13.179878]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.133558  -8.518778 -10.946448 ... -11.287366 -10.447039 -10.448987]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.096974 -13.02494  -12.955858 ... -12.806622 -12.968203 -13.131756]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.85652  -13.501425 -13.701636 ... -13.587351 -13.608512 -13.942522]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.84755   -11.716504  -13.102296  ... -12.939661  -12.186232
 -12.7930355]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.714678 -16.776098 -20.241627 ... -18.751793 -17.718002 -18.115828]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.761478  -11.308815  -11.617667  ... -12.613655  -12.654922
 -12.8386345]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.555034  -9.617104 -10.717107 ...  -9.106125  -9.412452  -9.935191]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.836931 -10.83466  -10.34868  ...  -9.457273  -9.452445 -10.211922]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.6206665 -7.162758  -8.601039  ... -8.245591  -8.023795  -8.608586 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.114897 -14.249556 -16.89117  ... -17.762741 -16.069096 -16.632246]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.931137 -17.220625 -17.442188 ... -18.86861  -18.385658 -19.070318]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.836895 -19.563608 -22.550945 ... -21.70467  -20.070137 -21.594427]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.973562 -20.920448 -24.168911 ... -26.315128 -24.646748 -25.109835]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.830171  3.0770676 3.8313498 ... 5.2782445 4.640337  5.1023836]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.542315 -16.06117  -17.501232 ... -18.054842 -17.127039 -18.025354]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.833969 -12.769011 -13.711964 ... -12.281478 -11.600422 -12.426803]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.049498  -13.798788  -14.0876045 ... -16.43742   -16.329641
 -16.748463 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.099536  -13.3275585 -12.818112  ... -13.085853  -13.495558
 -13.490154 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.951107 -12.135004 -17.800793 ... -19.111559 -16.53293  -17.241312]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.567934 -12.068999 -11.58522  ... -13.06581  -13.633343 -12.969959]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.9015465 -10.504625  -11.080408  ... -12.802419  -11.703841
 -13.101584 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.007058  -12.844188  -12.923927  ... -14.731376  -13.734697
 -15.4143505]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.216289 -11.625102 -12.505637 ... -14.698048 -13.571039 -14.935136]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.288462 -20.855042 -21.253666 ... -25.410471 -24.485733 -25.863836]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[5.5709853 4.681005  5.4521737 ... 6.826003  6.156515  6.6794405]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.4859357 -6.5879097 -5.391558  ... -5.7673573 -5.9085803 -6.4822288]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.047855 -13.843609 -21.033583 ... -24.232832 -20.769321 -20.76483 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.896467 -15.513425 -17.509125 ... -18.920937 -16.712536 -17.79625 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.94102   -7.309123 -10.548554 ... -11.389042  -9.176182 -11.299436]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.083784  -8.391252 -15.553548 ... -14.975218 -11.96797  -12.964242]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.908868 -11.828691 -11.150862 ... -10.40115  -10.75947  -11.726977]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.751213 -20.815277 -18.95288  ... -25.678633 -25.31935  -25.397573]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.50609  -18.88071  -23.145441 ... -23.539513 -21.82116  -23.041224]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.129534 -18.212713 -17.302538 ... -18.437094 -18.67227  -19.936756]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.234227 -12.150783 -13.630093 ... -14.735483 -14.129112 -14.566112]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.0769005 -8.322892  -8.901714  ... -8.291932  -8.365131  -8.846435 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.108158 -13.780124 -15.673841 ... -17.81537  -17.043583 -17.349459]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.863812 -11.905087 -14.063743 ... -13.994828 -13.372754 -13.981646]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.9622006 -5.569387  -4.2707224 ... -8.151775  -7.791893  -7.507862 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.195093 -18.919523 -18.48482  ... -18.929771 -18.728632 -18.595276]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.5104427  -4.036179   -8.208144  ... -10.503204   -8.14172
  -9.987954 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.093966  -6.519131  -9.109803 ... -12.394685 -10.5313   -12.153956]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.399544  2.3503375 3.4722257 ... 4.291203  3.7059367 4.0263276]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.448305   -6.2402935 -10.099053  ...  -9.791115   -8.640498
  -8.746733 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.4793    -6.0615506 -7.4543047 ... -6.1864915 -5.7735667 -5.664791 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.936211  -7.272975  -8.701162  ... -7.8853717 -7.6084547 -7.5641365]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.0658655  -8.687847  -10.192118  ...  -9.006061   -8.301263
  -8.281377 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.906015 -11.823204 -14.78234  ... -15.199548 -14.162218 -14.661068]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.372813 -11.632022 -14.081419 ... -14.026082 -13.418111 -13.632114]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.599459 -10.441069 -12.197908 ... -12.525374 -12.068093 -12.072873]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.313858 -16.671038 -16.882257 ... -19.242752 -18.972202 -19.353884]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.737854 -17.174706 -18.552053 ... -19.978796 -19.176252 -20.481562]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.783994 -14.108418 -14.13139  ... -15.415    -15.428096 -16.151258]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.446135 -14.395244 -16.433836 ... -17.312445 -15.867838 -17.152937]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.639545 -22.024588 -17.440525 ... -15.66243  -18.43674  -18.778673]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.509352 -17.121174 -16.907969 ... -14.486801 -15.431786 -16.373596]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.01723  -13.164396 -15.37809  ... -15.539079 -13.993916 -15.147969]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.863345 -10.948465 -12.94096  ... -10.841671 -10.307574 -11.461112]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.280142 -18.76611  -19.106125 ... -21.72792  -21.274633 -21.75159 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.051664 -13.944313 -16.904066 ... -17.087103 -15.403958 -16.382454]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.488825 -20.01163  -21.215128 ... -24.805138 -24.768593 -24.595835]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.849951 -13.202506 -15.588977 ... -14.508949 -13.444735 -14.258711]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.208418 -15.507074 -19.089983 ... -18.899853 -17.10013  -18.258692]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.792845  -15.357911  -13.788301  ... -12.474505  -14.0145035
 -13.78555  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.196827 -15.801747 -15.836928 ... -14.560636 -15.558582 -15.830973]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.784126 -21.826256 -22.067268 ... -25.095577 -24.1189   -24.052485]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.87616  -16.359596 -17.400246 ... -14.533267 -15.015267 -16.401234]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.763416 -12.470567 -12.471085 ... -12.68364  -12.774753 -13.076558]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.1616745 -12.884407  -13.018715  ... -12.886898  -13.074579
 -13.188592 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.439032 -15.179998 -15.972676 ... -13.620148 -13.706311 -14.005758]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.034035 -20.357367 -23.677917 ... -22.98817  -20.971745 -22.628036]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.042115   -5.3285165  -8.314763  ... -11.037708   -9.321319
 -10.4553   ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-25.328016 -21.621487 -25.909208 ... -24.233965 -23.839153 -25.15864 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.734594 -17.864063 -19.968603 ... -21.741703 -20.483736 -21.577885]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.724254 -15.744234 -15.025035 ... -14.330377 -14.7316   -15.723739]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.852295 -18.795584 -22.66578  ... -23.619009 -21.46145  -22.877058]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.850523 -16.673056 -14.409148 ... -14.182818 -15.580024 -15.968783]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.893705 -14.221709 -16.426062 ... -17.73262  -15.963014 -16.9414  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.269048 -13.882718 -15.30112  ... -12.505809 -11.992164 -13.343924]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.872155  -14.821955  -15.278095  ... -13.7944565 -13.567437
 -14.855845 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.58687   -14.112195  -14.0007105 ... -11.490876  -12.182026
 -12.893127 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.681976 -13.180751 -16.93331  ... -15.635832 -13.681314 -14.755976]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.515945 -19.455011 -20.909784 ... -23.46081  -21.723614 -23.06725 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.013015 -13.116754 -14.959376 ... -11.539025 -11.638971 -12.626209]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.517256 -19.370415 -23.626686 ... -22.503706 -20.474865 -22.378782]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.331126 -12.937478 -14.685727 ... -12.824096 -12.131284 -12.80475 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.695178 -11.905935 -13.828655 ... -11.988173 -11.341107 -12.058677]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.313797 -12.240018 -13.766425 ... -11.154006 -10.62215  -11.490237]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.846199 -12.766502 -14.263759 ... -11.674481 -11.231194 -12.066328]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.358807 -15.697002 -17.250116 ... -13.825112 -14.209466 -15.385293]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.144316 -11.318908 -11.354643 ... -12.463073 -11.751323 -12.758585]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.350355 -13.089896 -13.210569 ... -13.021934 -13.190102 -13.36482 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.865684 -14.046652 -14.420745 ... -11.20967  -12.544427 -13.517208]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.13046  -18.166515 -21.38121  ... -16.409956 -16.943102 -18.665354]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.745195 -14.636644 -16.380522 ... -15.297153 -14.939439 -16.451124]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.686954 -13.594362 -15.530974 ... -14.628369 -13.60936  -14.271735]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.483328 -18.075571 -15.883178 ... -14.479988 -16.308374 -16.586166]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.282693 -16.85878  -15.362053 ... -14.614324 -15.344185 -15.233147]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.581009 -13.653472 -15.328894 ... -14.04578  -13.357147 -13.8878  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.547255 -18.437904 -16.304083 ... -13.673435 -15.409335 -15.446361]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.671975 -13.726373 -16.464043 ... -15.658026 -14.347309 -15.321709]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.800896 -18.743967 -16.881828 ... -16.521957 -17.481846 -18.07741 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.399363 -13.371695 -14.840854 ... -13.992933 -13.32841  -14.026779]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.459797 -21.870537 -19.516613 ... -18.459032 -18.915644 -19.48335 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.543028 -18.820644 -16.248486 ... -17.787056 -18.898981 -19.260624]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.221176  -15.2408905 -15.064628  ... -15.651278  -15.924186
 -15.986871 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[5.0371714 4.2923265 5.0821166 ... 5.6997395 5.159008  5.464633 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.604946 -17.353605 -14.974284 ... -15.012264 -16.074886 -16.32676 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.429639 -12.995273 -14.550492 ... -12.961243 -12.129998 -12.936414]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.262028 -16.794682 -18.460133 ... -18.595387 -17.591465 -18.552477]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.826742 -11.984824 -13.928173 ... -12.156397 -11.465776 -12.190425]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.92348  -12.820575 -13.699865 ... -11.085789 -11.308982 -12.027385]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.801354 -14.761608 -15.079266 ... -15.744571 -15.068467 -15.851797]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.3572   -19.688854 -20.4902   ... -17.002102 -17.846699 -19.228964]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.775679 -12.181096 -13.915537 ... -11.905967 -11.382218 -12.148356]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.468062  -7.5533376 -8.361289  ... -9.250508  -8.972377  -9.274783 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.228036  -8.341506  -7.9557414 ... -9.064997  -8.537764  -8.885505 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.693944 -11.164544 -13.29072  ... -13.573864 -12.307693 -13.04138 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.214688 -13.364773 -16.02084  ... -14.788872 -13.920578 -14.891068]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.004025 -16.984253 -18.824844 ... -20.697876 -19.639933 -21.06664 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.9909935 -14.274334  -17.001778  ... -15.780917  -14.796847
 -15.535578 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.978689 -14.198233 -16.806396 ... -15.886838 -14.919461 -15.843045]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.410776 -13.787923 -14.242134 ... -14.376101 -14.397736 -14.724439]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.927181  -13.7503605 -13.772079  ... -13.684912  -13.927563
 -14.016626 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.373933 -11.575328 -12.345768 ... -12.63148  -12.307611 -12.633454]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.256594 -17.407816 -15.32801  ... -16.181828 -16.858015 -17.479982]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.231062 -21.047554 -20.300747 ... -23.202835 -23.120783 -23.70733 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.743449  -11.996312  -11.238641  ... -11.4389515 -11.25182
 -11.800626 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.524944 -16.11232  -16.639227 ... -19.331364 -18.818922 -19.134615]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.228819 -21.383215 -19.996449 ... -15.827146 -17.576519 -19.155035]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-26.14424  -23.580324 -26.28584  ... -26.63532  -25.562437 -27.34531 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.661956 -10.025067  -9.525273 ...  -8.434747  -9.475652  -9.735328]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.533713 -8.097079 -9.688423 ... -8.739458 -8.496006 -8.617679]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.654366 -14.679854 -20.361174 ... -19.667915 -17.114296 -18.351528]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.385668  -3.2869105 -6.9447293 ... -8.272808  -5.8620176 -7.5306897]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.975245 -16.136185 -19.036829 ... -19.95204  -18.373672 -18.954134]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.405827 -19.497778 -21.070599 ... -21.859093 -21.354532 -22.609331]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.183669  -6.7782035 -8.477336  ... -7.581862  -7.395292  -7.4946804]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.477325 -19.476927 -18.757963 ... -15.498549 -16.980818 -17.279486]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.784132  -11.478633  -17.863598  ... -19.346857  -15.8560295
 -17.2975   ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.609757  -9.001516 -10.881748 ... -12.47472  -10.421533 -10.690703]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.784103 -13.118704 -13.644797 ... -13.942305 -13.768488 -14.169691]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.96578  -13.124602 -15.068429 ... -15.806394 -14.417407 -15.494462]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.216219 -12.873655 -12.218607 ... -13.956036 -13.453355 -14.373599]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.750465 -10.429065 -13.137042 ... -13.425244 -12.478704 -13.106506]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.654163 -13.931142 -16.928646 ... -19.346031 -18.139206 -18.798326]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.658428 -23.488556 -23.716959 ... -24.608772 -23.794947 -25.284534]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.753846 -12.375522 -13.343726 ... -16.26263  -15.220046 -16.270489]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.368363 -13.554384 -12.777704 ... -13.775173 -13.89608  -13.945293]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.676872 -17.91784  -18.188429 ... -21.154228 -20.5786   -21.536913]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.948723  -9.15725  -13.44031  ... -10.578652  -9.026231  -9.878304]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.643508 -11.173788 -13.772239 ... -16.228266 -14.808813 -15.664272]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.85113  -13.254859 -16.376549 ... -16.4158   -15.819304 -16.717995]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.5599375 -10.978111  -10.930229  ... -12.232849  -11.389458
 -12.06893  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.069193 -12.237502 -16.01204  ... -17.183035 -15.513856 -16.610306]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.582525 -10.797349 -14.444701 ... -15.881445 -14.119959 -15.043626]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.878277  -9.153077 -13.041782 ... -15.38383  -13.110154 -14.342944]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.922882 -15.441784 -18.79777  ... -20.269787 -18.365438 -19.517754]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.861847 -14.530145 -14.782556 ... -14.88514  -14.776969 -15.254204]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.895642 -8.387288 -9.677829 ... -8.791424 -8.82173  -9.443016]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.842753  -13.261176  -13.734878  ... -14.3187895 -14.054338
 -14.431814 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.957848 -8.404338 -9.713711 ... -8.910712 -8.904029 -9.601958]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.390285 -8.453814 -9.270221 ... -8.585078 -8.765235 -9.097039]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.091978  -8.096175  -9.0017605 ... -7.6161885 -7.830366  -8.203306 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.28974  -13.049135 -13.077976 ... -13.167027 -13.224807 -13.438834]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.694626  -7.4620214 -8.392002  ... -8.765376  -8.700252  -9.136825 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.248984 -12.927779 -13.001611 ... -13.136188 -13.205994 -13.457121]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.5661955 -13.213713  -13.426982  ... -13.14717   -13.331829
 -13.477032 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.725004 -12.30139  -16.6107   ... -17.52333  -16.101212 -17.467176]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.902025 -16.204014 -19.569105 ... -18.29307  -17.538292 -19.22859 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.547275  -12.70614   -14.902527  ... -15.760642  -14.8811
 -15.2280855]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.602534 -13.155251 -15.853504 ... -15.730006 -14.791116 -15.997802]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.084826  -7.893203  -8.826398  ... -7.8340077 -8.033599  -8.592112 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.053386 -10.737953 -13.272859 ... -12.605965 -12.260918 -13.394314]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.942529  -11.240194  -12.7830515 ... -14.088929  -12.373134
 -12.99809  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.601196 -20.293428 -21.613672 ... -26.352251 -24.705471 -25.938793]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.906526  -11.9305935 -12.689086  ... -14.539413  -13.519406
 -14.508104 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.748991 -16.179398 -19.685719 ... -18.830162 -17.434418 -18.673422]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.875065 -22.58935  -24.32426  ... -25.837084 -24.907679 -25.433046]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.510308 -13.190154 -13.246836 ... -13.278437 -13.443662 -13.610616]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.772379 -14.401292 -13.12991  ... -14.961133 -15.256574 -15.116055]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.272679  -8.354211 -10.718759 ... -10.680055  -9.434686  -9.329351]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.8126335  -4.828674   -9.630169  ... -12.021978  -10.033914
 -11.483273 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.058382 -13.854398 -15.777414 ... -17.427631 -15.503031 -16.688557]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.018297 -11.870536 -14.197558 ... -16.34345  -15.069463 -16.213   ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.915806 -22.069115 -19.38247  ... -24.823202 -24.672453 -25.681345]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.124006 -15.88507  -18.79947  ... -20.340443 -18.685665 -19.640762]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.814801  -13.492713  -13.669233  ... -13.3595915 -13.5603695
 -13.718234 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.219726  -9.507994 -10.999665 ... -11.269163 -10.374054 -11.170095]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.019221  -12.3792925 -12.875366  ... -12.89916   -12.778561
 -13.255972 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.048258 -19.93538  -20.703684 ... -21.164913 -20.67664  -21.77719 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.567276 -14.617176 -15.184219 ... -14.334548 -13.914913 -14.986186]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.115904 -13.08574  -12.969023 ... -12.459178 -11.890767 -13.643388]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.764946 -18.921328 -20.485079 ... -18.27199  -18.064049 -19.465546]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.051743 -20.506523 -20.443699 ... -17.853773 -19.53024  -20.771976]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-26.71256  -23.450598 -27.906311 ... -28.247534 -25.353296 -27.229397]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.781287 -11.005187 -13.354591 ... -12.734093 -11.726994 -12.481862]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.806497 -11.684205 -13.272466 ... -13.957236 -12.710077 -13.281018]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.908923 -10.815298 -11.334097 ... -11.951481 -11.225202 -12.161103]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.6003895  -5.6139655 -10.17383   ...  -9.610147   -7.0691733
  -7.827628 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.734582 -14.539618 -15.407135 ... -14.208683 -13.875283 -15.117638]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.12806  -12.740141 -12.035329 ... -12.249651 -12.017105 -13.021536]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.146654 -18.850311 -21.704622 ... -22.34717  -21.628263 -22.899742]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.460926  -13.8338175 -16.162357  ... -12.898997  -12.278407
 -13.75102  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.149778 -13.559981 -16.686184 ... -16.93192  -15.346532 -16.566471]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.488198 -12.243733 -14.530991 ... -16.330143 -15.312429 -16.241898]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.389263 -16.125854 -16.35797  ... -20.548998 -20.079092 -19.758404]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.703865 -19.77624  -22.861814 ... -22.513382 -20.707804 -22.611063]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.061673  -12.3664875 -13.076762  ... -13.0810585 -12.659581
 -13.057811 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.355682 -21.09399  -23.68346  ... -25.203981 -24.387506 -24.890554]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.843386 -12.83774  -14.962784 ... -15.364084 -14.128875 -15.238445]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.402252 -15.48495  -16.840187 ... -17.071072 -16.177393 -16.664694]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.16624  -15.07558  -16.186472 ... -17.029871 -16.385723 -16.94942 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.391556 -17.836473 -18.781425 ... -21.183952 -20.978563 -20.973108]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.520172 -20.454754 -21.867039 ... -23.66676  -21.848589 -23.361328]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.102475 -14.399423 -15.03596  ... -15.751654 -15.399807 -15.821101]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.742018 -20.244905 -21.35064  ... -22.34725  -21.783949 -22.852867]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.916595  -11.2173395 -14.380495  ... -15.822983  -14.380707
 -15.241848 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-25.673634 -23.236135 -25.7434   ... -27.887468 -25.514822 -27.179834]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.054064   -6.3834834  -9.47389   ... -12.80038   -10.862923
 -12.3970995]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.215607  -5.05611   -8.57576  ... -10.949066  -8.936535 -10.676224]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.384157 -14.162878 -17.173855 ... -18.120483 -16.241835 -17.37832 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.394754 -18.461626 -21.433266 ... -23.330862 -22.067017 -23.144962]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.494152 -12.38009  -15.202754 ... -15.525217 -13.83875  -14.775866]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.785055 -14.389851 -19.177776 ... -15.929888 -14.658732 -15.703752]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.994919  -2.80392   -6.765769  ... -8.271946  -5.766019  -7.4747233]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.042658 -12.909322 -14.251605 ... -14.931162 -14.359574 -14.788417]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.714463 -10.933107 -12.849504 ... -14.017626 -12.960438 -12.683363]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-27.588112 -25.450874 -27.382488 ... -29.142708 -27.774082 -29.618584]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.118188 -12.843349 -12.955918 ... -12.885942 -13.017462 -13.118977]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-24.941977 -24.108204 -25.217163 ... -27.44856  -25.29086  -27.31175 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.039248 -13.753719 -16.187128 ... -15.551059 -14.96943  -15.943336]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.600193 -13.187992 -13.496236 ... -13.570929 -13.431192 -13.747908]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.848225 -8.477332 -9.841471 ... -8.492054 -8.324291 -8.895363]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.168396 -10.405453 -15.13084  ... -14.618738 -13.114293 -14.322481]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.28301  -15.874379 -20.386255 ... -21.608593 -19.756172 -20.97691 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.473379   -5.6536636  -8.973918  ... -11.664431   -9.822868
 -10.98248  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.37147   -9.246397 -10.385848 ... -10.016381  -9.914348 -10.444016]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.649355 -16.89769  -22.05763  ... -19.828135 -19.038578 -19.80631 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.430147 -10.690609 -15.980512 ... -18.888412 -16.800072 -17.818079]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.6824875 -10.5387535 -12.017671  ... -11.81988   -11.094916
 -11.673197 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.048941 -13.472271 -15.185656 ... -12.900084 -12.137086 -13.289884]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.213456 -13.070686 -14.42234  ... -14.712373 -13.754517 -14.406371]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.953396  4.013128  4.921878  ... 5.8838243 5.3491416 5.791666 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.4895918 2.5986853 3.6983573 ... 4.686091  3.9949358 4.292168 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.9288535 -2.5901093 -2.5851698 ... -2.1366465 -2.572322  -2.7830453]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.443732  -9.08912  -12.864921 ... -14.649933 -12.609353 -13.327109]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.4829252 2.5674744 3.6997216 ... 4.8037953 4.0640855 4.3461   ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.4192398 2.7924693 3.2521205 ... 4.7581506 4.1490655 4.5476737]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.36334   -11.7898855 -15.380767  ... -14.638284  -14.438078
 -14.727036 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.3316464 3.699429  4.4906273 ... 6.064112  5.4153185 5.660538 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.660468 -12.359341 -12.499479 ... -12.08637  -12.275848 -12.401793]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.5909815 -11.169349  -13.511789  ... -12.088068  -11.246784
 -11.886423 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.032494  -8.047045  -8.988046  ... -7.6239686 -7.8703756 -8.19694  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.47004  -15.9547   -18.618166 ... -18.592817 -17.132154 -18.466381]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.819239 -18.725012 -19.717258 ... -21.249964 -20.620903 -21.80857 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.626175  -7.5288754 -9.489098  ... -9.715015  -8.816859  -8.874137 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-24.75728  -20.040956 -26.408897 ... -23.352646 -20.95792  -22.506166]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.443856 -13.020984 -13.336755 ... -13.138817 -13.207654 -13.409801]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.874731 -14.162182 -15.845071 ... -17.136728 -16.654474 -17.235613]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.724084 -13.632948 -14.669557 ... -15.859786 -14.89219  -15.270806]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.810271  3.0982416 3.8955052 ... 5.268039  4.664195  5.0868783]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.971945 -13.183678 -14.93981  ... -17.560877 -15.953767 -16.245468]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.387861 -10.643051 -11.233053 ... -13.158376 -12.676811 -13.01834 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.014492 -21.090082 -22.77309  ... -24.464075 -23.648258 -24.361547]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.161844 -12.623073 -13.176112 ... -13.044866 -13.019212 -13.157845]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.803165 -13.412112 -13.651545 ... -13.570959 -13.633628 -13.845818]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.285073  -8.041465  -8.867057  ... -9.368585  -9.19636   -9.7963295]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.026095 -13.541904 -12.530811 ... -14.137257 -14.353291 -14.192604]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.015194 -12.69705  -18.249174 ... -20.102402 -17.064137 -18.18516 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.824891  -14.124437  -14.7476845 ... -15.752308  -15.301583
 -15.749948 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.593708 -14.037153 -14.518145 ... -15.319762 -14.961366 -15.358083]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.931142 -14.263425 -14.80377  ... -14.284011 -14.130953 -14.596274]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.270908  -7.2854795 -8.1588335 ... -7.3219776 -7.723289  -8.118351 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.388874 -12.963234 -13.337489 ... -13.920787 -13.626657 -14.066247]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.556459 -10.250028 -11.223024 ... -14.357626 -13.423839 -13.723345]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.408752 -21.01656  -22.657658 ... -23.822672 -22.823206 -24.471073]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.298524  -9.30372  -12.24524  ... -13.236693 -11.678364 -12.555427]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.895048 -21.719372 -24.475168 ... -25.928658 -24.681803 -25.737743]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.286222 -24.216028 -22.980095 ... -25.214466 -25.246845 -25.722202]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.30282  -15.479137 -16.83601  ... -17.400036 -16.186712 -17.04288 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.573283 -13.920531 -15.42333  ... -13.472704 -13.237554 -13.51875 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.444116 -15.107615 -15.333167 ... -15.548369 -15.629209 -15.665001]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.191895 -20.48498  -19.096214 ... -20.293972 -20.348228 -21.346785]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.074839 -11.623437 -14.843685 ... -14.31958  -12.889937 -13.849968]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.193754 -11.206087 -11.974483 ... -13.162646 -12.417915 -13.652847]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.961169  2.03036   2.957985  ... 4.550528  3.8363023 4.2498813]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.331457 -12.844196 -13.283747 ... -12.873976 -12.910644 -13.10784 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.446276 -15.835146 -16.769352 ... -18.511307 -18.218466 -18.485249]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.703695 -16.541283 -17.344294 ... -20.452337 -19.493727 -20.405592]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.246557 -10.678253 -13.481271 ... -17.577074 -15.871089 -15.933658]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.634867 -19.462341 -19.09817  ... -20.040035 -20.243866 -21.065552]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.675013 -13.996584 -14.688781 ... -15.046793 -14.53866  -15.263631]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.957989 -11.218598 -13.055415 ... -14.869559 -13.071585 -13.380856]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.2901   -15.382239 -17.991758 ... -19.394178 -17.918798 -18.85368 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.978008 -22.046574 -22.854038 ... -22.352406 -21.872263 -23.185081]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.560939 -12.581597 -13.801373 ... -13.714625 -13.3462   -13.706902]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.771821 -14.824977 -13.557653 ... -19.04953  -18.920944 -18.579071]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.082994 -11.206914 -13.156214 ... -13.380657 -12.988033 -13.126733]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.145922 -15.49339  -15.327617 ... -19.144672 -19.039038 -18.931406]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.7328005  -5.929262   -8.989977  ... -11.168024   -9.173094
 -10.170543 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.391569 -13.222901 -12.451933 ... -17.35242  -17.09365  -16.775087]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.006179 -12.650151 -14.207447 ... -13.948629 -13.762891 -14.334627]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.351639 -13.994016 -16.352669 ... -21.062283 -19.039404 -19.663198]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.552237 -18.707949 -19.76418  ... -19.5493   -18.332603 -19.797413]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.716085  -9.751456 -12.689137 ... -13.588807 -12.014762 -12.922383]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.925257 -19.133814 -23.421152 ... -23.328972 -19.925365 -22.4843  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.669035 -12.046254 -15.337579 ... -16.468658 -14.6312   -15.537487]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.25235  -18.533134 -22.454126 ... -20.76032  -18.25385  -20.482038]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.771001  -9.360186 -10.971499 ... -15.496052 -13.516722 -14.859012]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.693051 -14.597305 -14.673813 ... -12.703227 -13.788989 -14.204216]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.4353127 3.66461   4.394993  ... 6.1023555 5.0846887 5.6778083]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.960775 -22.173664 -24.944994 ... -26.198074 -24.720291 -26.36047 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.475193 -16.494747 -18.445263 ... -22.129316 -20.206797 -21.363483]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.639375  -12.895873  -12.4888935 ... -12.466599  -12.645998
 -12.87538  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.036545 -15.859795 -16.958132 ... -18.156555 -16.717073 -18.215347]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.7675495 -14.522244  -15.604884  ... -16.439331  -15.316679
 -16.378523 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.119003 -19.747631 -24.248863 ... -25.094957 -22.534765 -24.232605]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.743385 -19.923353 -20.062202 ... -19.753756 -19.904898 -20.266891]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.533679  -7.3559146 -8.500704  ... -7.3847547 -7.8232646 -8.117191 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.783676  -8.828037  -8.298266  ... -6.678509  -7.995126  -7.9466977]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.626319 -12.126472 -12.640508 ... -12.343786 -12.090242 -12.54307 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.819936 -11.212357 -13.182449 ... -13.269748 -11.968633 -12.903096]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.83088  -10.056432 -13.10841  ... -15.787821 -13.899189 -15.239394]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.40335  -12.811286 -13.252877 ... -14.905794 -14.131222 -14.760384]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.452215 -11.536569 -14.537472 ... -18.164309 -15.843687 -17.641651]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.802946 -16.918507 -14.799471 ... -15.779755 -17.075474 -17.968298]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.613322 -10.871993 -12.738976 ... -12.155153 -12.396622 -12.983691]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.112503 -17.357588 -18.219423 ... -17.745604 -17.482306 -17.89732 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.367867  -10.886101  -13.733083  ... -14.334606  -13.1833105
 -13.978797 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.265886 -19.51633  -21.954605 ... -25.11383  -24.952267 -25.453844]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.268408 -15.490125 -16.717482 ... -18.813274 -18.034029 -18.899597]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.91067  -12.075159 -15.443086 ... -16.916245 -15.378082 -16.275835]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-25.109966 -23.356548 -25.647318 ... -27.934553 -26.36058  -28.22281 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.667799 -15.194538 -19.200184 ... -22.15054  -19.814522 -21.095158]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.16565    -9.027105  -12.119725  ... -13.910653  -11.546906
 -12.1449795]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.911628 -14.439591 -15.848934 ... -17.88077  -16.592556 -17.636597]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.597595  -12.770959  -13.543669  ... -14.6662655 -14.580298
 -14.971704 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.619409  -10.229183  -13.091298  ... -14.205052  -12.817966
 -13.6362295]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.232723 -14.960286 -16.26008  ... -17.047152 -16.484518 -17.343407]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.990786 -19.68204  -22.568762 ... -26.245241 -23.483568 -25.225693]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.710449 -12.2859   -15.026364 ... -16.003185 -14.788691 -15.403714]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.347215  -5.1465154 -7.00455   ... -6.994813  -6.2065825 -6.6128836]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.463124  -11.685781  -15.2373085 ... -16.78095   -14.957156
 -15.870692 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-24.255096 -21.988085 -26.050476 ... -27.378813 -24.756918 -26.026186]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.52033  -13.029886 -16.637104 ... -18.255497 -15.9085   -17.834846]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.06664  -14.713224 -19.109953 ... -15.396986 -14.015521 -14.697147]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.93975  -12.179164 -15.63478  ... -17.73981  -15.916937 -16.683624]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.605192   -8.464627  -11.393437  ... -11.7407465 -10.459768
 -11.493392 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.760223  -13.920143  -14.774219  ... -15.095384  -14.8754425
 -15.255572 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.665287  -8.591136 -11.52068  ... -12.137795 -10.751607 -11.779456]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.775172  -8.530732 -11.762267 ... -12.704093 -11.034045 -12.044793]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.484616 -13.910728 -16.663929 ... -16.705591 -14.745182 -15.52995 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.491931 -11.980909 -16.240849 ... -16.867304 -15.115216 -16.536636]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.953781 -12.417235 -14.381117 ... -13.763985 -12.740938 -13.267184]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.01594  -11.266186 -14.680152 ... -17.10593  -15.093561 -16.04355 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.386664  -9.407994 -12.32457  ... -11.990171 -11.034704 -11.853145]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.851484  -10.110149  -12.6835785 ... -14.332457  -12.728636
 -13.653938 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.958494 -14.261394 -15.848995 ... -17.612545 -16.43133  -17.23961 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.213772 -12.504876 -15.492258 ... -17.797405 -16.039328 -17.204645]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.155545  -9.95253  -13.417535 ... -16.036804 -13.840486 -14.76867 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.684026 -11.546797 -15.429412 ... -14.651401 -13.141988 -14.109268]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.047357 -12.166294 -14.945875 ... -15.853251 -14.358803 -15.146224]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.6683447 2.895581  3.5370028 ... 5.284055  4.6284695 5.0587373]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.178474 -20.845934 -22.392155 ... -21.298626 -21.329327 -22.200855]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.302016 -13.11191  -13.122104 ... -12.971862 -13.119727 -13.34021 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.589469 -13.186914 -13.398558 ... -13.155052 -13.328251 -13.49339 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.841011 -18.457996 -22.487307 ... -25.133238 -23.06043  -23.937979]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.86921  -13.495199 -13.746373 ... -13.262689 -13.439951 -13.750359]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.61503  -16.473392 -16.463068 ... -16.188194 -15.846624 -17.048548]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.771294   -8.5978775  -8.833529  ...  -9.909015   -9.507476
 -10.070869 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.391006 -17.21327  -16.370426 ... -13.683082 -15.302989 -15.3532  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.708439  -10.430076  -12.362296  ... -12.5841675 -11.8421135
 -12.552817 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.281697  -9.196405 -11.964675 ... -12.852359 -11.516667 -12.570594]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.626434  -12.4857025 -16.419619  ... -16.76663   -16.014578
 -17.586586 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.679153  -9.692075 -12.329563 ... -12.851126 -11.662452 -12.446765]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.715065 -18.678585 -20.74753  ... -22.80773  -21.839329 -22.66566 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.241646 -4.884206 -7.688413 ... -9.987177 -8.428246 -9.887551]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.7663765 -11.168151  -12.2604265 ... -13.940596  -12.940649
 -12.815425 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.229134   -9.043779  -12.0940895 ... -13.021565  -12.576407
 -12.634439 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.81837  -18.502817 -22.532137 ... -22.189342 -20.487823 -22.249962]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.298805 -12.968418 -13.115226 ... -12.902165 -13.054543 -13.232772]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.185326  -13.945901  -13.786638  ... -14.618999  -14.376356
 -14.5581255]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-24.62002  -22.570892 -25.085049 ... -27.375446 -26.255087 -27.178701]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.30658  -20.353914 -21.020895 ... -24.198496 -23.668123 -24.388819]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.305345 -11.774644 -15.192937 ... -14.468393 -12.987251 -13.970131]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.265273  -8.321935  -9.452715  ... -7.2946777 -8.062557  -7.9362392]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.924796 -13.035912 -16.360918 ... -19.02043  -17.034472 -18.094694]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.274954 -20.609627 -22.399487 ... -22.268541 -21.316498 -22.79552 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.720341  -9.663707 -10.130163 ... -10.984295 -10.503343 -11.18597 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.6749334 3.9483464 4.627332  ... 6.1172476 5.4907913 5.9735413]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-28.315594 -25.49113  -28.990553 ... -30.523375 -28.616442 -30.113562]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.005142 -20.202301 -20.632936 ... -22.36709  -20.762674 -22.21857 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.6801767 -4.9537334 -4.5247097 ... -4.369752  -4.5302315 -4.9041343]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.722299  -6.6499414 -5.5328207 ... -5.0472374 -5.3394175 -5.2737985]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.762586  -6.515747  -5.4117064 ... -3.609875  -3.7400606 -3.998302 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.131026  -7.7694373 -7.1687646 ... -7.865546  -7.8889484 -7.672862 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.3913174 2.6847346 3.35982   ... 4.590103  4.0942345 4.5508986]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.342317  3.8880377 4.3476663 ... 5.6891184 5.132324  5.545051 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.705741  -6.446894  -6.3846726 ... -8.540124  -8.218926  -7.537446 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.7161891 2.7280102 3.8094907 ... 5.0096903 4.272336  4.601143 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.6377504 2.794331  3.642233  ... 4.959669  4.121505  4.49856  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.410701  3.6911988 4.460387  ... 6.096648  5.3112197 5.6238456]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.8088043 2.8201582 3.86874   ... 5.2069464 4.533453  4.868654 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.8586173 3.0128934 3.9775271 ... 5.1892705 4.4340925 4.8092356]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.9335413 3.8433251 5.0279083 ... 5.923682  5.3156967 5.6780596]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.7697263 -4.1772656 -7.3226476 ... -9.733028  -7.82536   -9.244805 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.611027  -11.632867  -14.985791  ... -14.810191  -12.778755
 -13.6495075]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.584791 -12.293421 -12.419614 ... -11.976232 -12.176835 -12.309561]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.30296   -11.1114025 -11.463235  ... -11.132596  -11.0879345
 -11.042794 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.4732585  -8.240706   -7.943943  ... -11.62438   -11.389545
 -10.71281  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.399902  2.7763839 3.4037879 ... 4.6988587 4.1068687 4.4025044]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.488216 -16.102217 -18.026514 ... -20.994032 -19.663376 -20.328373]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[5.193619  4.4550023 5.2133145 ... 6.564181  5.975591  6.4562774]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.5778766 2.852859  4.026222  ... 4.9504757 4.2163777 4.4998045]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.314903 -10.122619 -13.601503 ... -17.206059 -15.479864 -16.213993]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.320861  -10.934715  -14.441305  ... -14.990234  -14.1784525
 -14.805045 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.374771  -13.312198  -13.130189  ... -12.2441635 -12.9258585
 -12.541646 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.421535 -10.652305 -10.714179 ... -11.014212 -11.390232 -11.036063]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.038776 -19.559828 -22.334219 ... -20.610283 -20.069912 -21.346718]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.182491 -15.118347 -16.87148  ... -17.519165 -16.272257 -17.310131]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.517132  -12.69567   -13.48468   ... -14.012649  -13.7612095
 -14.158861 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.987664 -14.827403 -15.328435 ... -18.132076 -17.680696 -18.230764]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.009652 -10.998805 -14.721112 ... -15.755669 -14.133033 -15.125775]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.375908 -12.220648 -16.057215 ... -17.195768 -15.572504 -16.542871]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.5742753 3.2316206 3.6315672 ... 5.3863916 4.6319346 4.95294  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.761751 -14.381578 -17.49881  ... -18.291851 -16.998964 -18.109165]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.12524  -7.955782 -9.349229 ... -9.408491 -8.818796 -9.414284]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.962435 -8.981323 -7.616671 ... -9.387953 -9.595693 -9.037783]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.593376 -15.945516 -17.991125 ... -17.793499 -17.571926 -17.901709]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.488848 -10.609298 -11.20989  ...  -9.73939  -10.186061 -11.217508]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.16341  -16.589037 -19.96067  ... -20.573503 -19.28881  -19.919113]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.683125  -9.385587 -14.227221 ... -13.10593  -11.137957 -12.109534]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.602448  -6.3564897 -4.9657593 ... -4.572664  -5.4927926 -5.6612344]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.833271 -16.224277 -15.952584 ... -17.900463 -17.769894 -18.69528 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.012541 -13.867559 -15.717203 ... -17.178684 -15.440232 -16.579794]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.621052 -12.666777 -15.060714 ... -15.169996 -14.742865 -15.732829]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.887195 -13.448151 -10.519734 ... -13.54638  -14.668152 -13.784329]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.2552042 -3.1736786 -2.833939  ... -3.3142939 -3.8042555 -3.6313858]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.184124 -15.595278 -13.157262 ... -16.625326 -16.868603 -16.296722]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.203068 -23.026655 -22.569023 ... -27.042309 -26.127644 -26.284767]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.529761 -13.967292 -15.229129 ... -16.00956  -16.103668 -16.722824]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.1367366 1.8228328 3.4889543 ... 4.469567  3.4154766 3.7526298]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.048344 -20.719477 -22.497145 ... -24.494364 -24.166792 -24.05053 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.172586 -19.7672   -21.105656 ... -24.371025 -23.655254 -24.478779]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.814641  -9.1896925 -9.324599  ... -8.685533  -9.080477  -9.254826 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.616665 -14.931669 -16.994404 ... -17.180662 -15.814452 -16.93983 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.261698 -16.287241 -18.618305 ... -19.211958 -17.884178 -18.943523]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.936532 -13.477904 -16.348305 ... -16.615421 -15.308867 -15.985443]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.644918 -14.898339 -16.28039  ... -16.503529 -15.934135 -16.66728 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.47538  -12.758116 -13.41448  ... -13.064746 -12.968964 -13.277627]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.351181 -16.77874  -16.146372 ... -18.640009 -18.802017 -19.24885 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.7677584 3.7998714 4.546326  ... 6.657071  5.923264  6.3753343]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.75331  -21.048967 -20.087135 ... -19.308098 -19.734539 -19.89018 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.804266 -8.128592 -7.853531 ... -7.090362 -7.581439 -8.291977]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

PairwiseArrays with keys: connectivities, distances

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:66: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  sc.tl.leiden(n_adata, resolution=4.0)

{'cellxgene_census/dkd_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.6050132734327139, 'macro': 0.45858384601691754, 'micro': 0.6050132734327139, 'weighted': 0.5752358078815335}}, 'cellxgene_census/dkd_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5608184918529746, 'macro': 0.49302410982269285, 'micro': 0.5608184918529746, 'weighted': 0.5370188034467204}}, 'cellxgene_census/dkd_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5941644562334217, 'macro': 0.5355514243377841, 'micro': 0.5941644562334217, 'weighted': 0.5827613925424003}}, 'cellxgene_census/dkd_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5985221674876847, 'macro': 0.5, 'micro': 0.5985221674876847, 'weighted': 0.5985221674876847}}, 'cellxgene_census/gtex_v9_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5690731903254497, 'macro': 0.3561412506114705, 'micro': 0.5690731903254497, 'weighted': 0.5111263506144524}}, 'cellxgene_census/gtex_v9_cls': {'cell_type_ontology_term_id': {'accuracy': 0.47340980187695514, 'macro': 0.4771516389245344, 'micro': 0.47340980187695514, 'weighted': 0.4105919407683359}}, 'cellxgene_census/gtex_v9_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.49930483142161974, 'macro': 0.45026649672378827, 'micro': 0.49930483142161974, 'weighted': 0.46767738060420655}}, 'cellxgene_census/gtex_v9_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.49930483142161974, 'macro': 0.45026649672378827, 'micro': 0.49930483142161974, 'weighted': 0.46767738060420655}}, 'cellxgene_census/hypomap_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9331843865688121, 'macro': 0.5582565920511067, 'micro': 0.9331843865688121, 'weighted': 0.9095025274318423}}, 'cellxgene_census/hypomap_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9817518248175182, 'macro': 0.8017862483599127, 'micro': 0.9817518248175182, 'weighted': 0.9743770548339135}}, 'cellxgene_census/hypomap_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9908759124087592, 'macro': 0.8529747502946833, 'micro': 0.9908759124087592, 'weighted': 0.986699566363855}}, 'cellxgene_census/hypomap_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9963503649635036, 'macro': 0.8811979101634128, 'micro': 0.9963503649635036, 'weighted': 0.9945824700566079}}}
doing  cellxgene_census/mouse_pancreas_atlas

/lustre/fswork/projects/rech/xeg/uat95fg/scdataloader/scdataloader/utils.py:427: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  organismdf = pd.concat(organismdf)

predict epoch start

  0%|          | 0/4716 [00:00<?, ?it/s]

  0%|          | 1/4716 [00:04<6:13:33,  4.75s/it]

  0%|          | 2/4716 [00:05<2:52:41,  2.20s/it]

  0%|          | 3/4716 [00:05<1:48:21,  1.38s/it]

  0%|          | 4/4716 [00:05<1:18:03,  1.01it/s]

  0%|          | 5/4716 [00:06<1:01:18,  1.28it/s]

  0%|          | 6/4716 [00:06<51:14,  1.53it/s]

  0%|          | 7/4716 [00:07<44:50,  1.75it/s]

  0%|          | 8/4716 [00:07<40:38,  1.93it/s]

  0%|          | 9/4716 [00:07<38:03,  2.06it/s]

  0%|          | 10/4716 [00:08<36:04,  2.17it/s]

  0%|          | 11/4716 [00:08<34:43,  2.26it/s]

  0%|          | 12/4716 [00:09<33:47,  2.32it/s]

  0%|          | 13/4716 [00:09<33:12,  2.36it/s]

  0%|          | 14/4716 [00:10<32:46,  2.39it/s]

  0%|          | 15/4716 [00:10<32:24,  2.42it/s]

  0%|          | 16/4716 [00:10<32:11,  2.43it/s]

  0%|          | 17/4716 [00:11<32:04,  2.44it/s]

  0%|          | 18/4716 [00:11<31:57,  2.45it/s]

  0%|          | 19/4716 [00:12<32:00,  2.45it/s]

  0%|          | 20/4716 [00:12<31:55,  2.45it/s]

  0%|          | 21/4716 [00:12<31:50,  2.46it/s]

  0%|          | 22/4716 [00:13<31:48,  2.46it/s]

  0%|          | 23/4716 [00:13<31:46,  2.46it/s]

  1%|          | 24/4716 [00:14<31:46,  2.46it/s]

  1%|          | 25/4716 [00:14<31:48,  2.46it/s]

  1%|          | 26/4716 [00:14<31:45,  2.46it/s]

  1%|          | 27/4716 [00:15<31:43,  2.46it/s]

  1%|          | 28/4716 [00:15<31:44,  2.46it/s]

  1%|          | 29/4716 [00:16<31:43,  2.46it/s]

  1%|          | 30/4716 [00:16<31:44,  2.46it/s]

  1%|          | 31/4716 [00:16<31:43,  2.46it/s]

  1%|          | 32/4716 [00:17<31:39,  2.47it/s]

  1%|          | 33/4716 [00:17<31:42,  2.46it/s]

  1%|          | 34/4716 [00:18<31:44,  2.46it/s]

  1%|          | 35/4716 [00:18<31:43,  2.46it/s]

  1%|          | 36/4716 [00:18<31:42,  2.46it/s]

  1%|          | 37/4716 [00:19<31:41,  2.46it/s]

  1%|          | 38/4716 [00:19<31:41,  2.46it/s]

  1%|          | 39/4716 [00:20<31:40,  2.46it/s]

  1%|          | 40/4716 [00:20<31:40,  2.46it/s]

  1%|          | 41/4716 [00:20<31:38,  2.46it/s]

  1%|          | 42/4716 [00:21<31:37,  2.46it/s]

  1%|          | 43/4716 [00:21<31:37,  2.46it/s]

  1%|          | 44/4716 [00:22<31:36,  2.46it/s]

  1%|          | 45/4716 [00:22<31:37,  2.46it/s]

  1%|          | 46/4716 [00:23<31:40,  2.46it/s]

  1%|          | 47/4716 [00:23<31:37,  2.46it/s]

  1%|          | 48/4716 [00:23<31:37,  2.46it/s]

  1%|          | 49/4716 [00:24<31:37,  2.46it/s]

  1%|          | 50/4716 [00:24<31:38,  2.46it/s]

  1%|          | 51/4716 [00:25<31:41,  2.45it/s]

  1%|          | 52/4716 [00:25<31:41,  2.45it/s]

  1%|          | 53/4716 [00:25<31:40,  2.45it/s]

  1%|          | 54/4716 [00:26<31:39,  2.45it/s]

  1%|          | 55/4716 [00:26<31:37,  2.46it/s]

  1%|          | 56/4716 [00:27<31:37,  2.46it/s]

  1%|          | 57/4716 [00:27<31:36,  2.46it/s]

  1%|          | 58/4716 [00:27<31:34,  2.46it/s]

  1%|▏         | 59/4716 [00:28<31:34,  2.46it/s]

  1%|▏         | 60/4716 [00:28<31:37,  2.45it/s]

  1%|▏         | 61/4716 [00:29<31:36,  2.45it/s]

  1%|▏         | 62/4716 [00:29<31:35,  2.46it/s]

  1%|▏         | 63/4716 [00:29<31:33,  2.46it/s]

  1%|▏         | 64/4716 [00:30<31:33,  2.46it/s]

  1%|▏         | 65/4716 [00:30<31:37,  2.45it/s]

  1%|▏         | 66/4716 [00:31<31:35,  2.45it/s]

  1%|▏         | 67/4716 [00:31<31:37,  2.45it/s]

  1%|▏         | 68/4716 [00:31<31:35,  2.45it/s]

  1%|▏         | 69/4716 [00:32<31:36,  2.45it/s]

  1%|▏         | 70/4716 [00:32<31:34,  2.45it/s]

  2%|▏         | 71/4716 [00:33<31:34,  2.45it/s]

  2%|▏         | 72/4716 [00:33<31:37,  2.45it/s]

  2%|▏         | 73/4716 [00:34<31:33,  2.45it/s]

  2%|▏         | 74/4716 [00:34<31:33,  2.45it/s]

  2%|▏         | 75/4716 [00:34<31:35,  2.45it/s]

  2%|▏         | 76/4716 [00:35<31:33,  2.45it/s]

  2%|▏         | 77/4716 [00:35<31:32,  2.45it/s]

  2%|▏         | 78/4716 [00:36<31:30,  2.45it/s]

  2%|▏         | 79/4716 [00:36<31:29,  2.45it/s]

  2%|▏         | 80/4716 [00:36<31:29,  2.45it/s]

  2%|▏         | 81/4716 [00:37<31:30,  2.45it/s]

  2%|▏         | 82/4716 [00:37<31:30,  2.45it/s]

  2%|▏         | 83/4716 [00:38<31:32,  2.45it/s]

  2%|▏         | 84/4716 [00:38<31:30,  2.45it/s]

  2%|▏         | 85/4716 [00:38<31:34,  2.44it/s]

  2%|▏         | 86/4716 [00:39<31:32,  2.45it/s]

  2%|▏         | 87/4716 [00:39<31:31,  2.45it/s]

  2%|▏         | 88/4716 [00:40<31:30,  2.45it/s]

  2%|▏         | 89/4716 [00:40<31:28,  2.45it/s]

  2%|▏         | 90/4716 [00:40<31:27,  2.45it/s]

  2%|▏         | 91/4716 [00:41<31:27,  2.45it/s]

  2%|▏         | 92/4716 [00:41<31:26,  2.45it/s]

  2%|▏         | 93/4716 [00:42<31:23,  2.45it/s]

  2%|▏         | 94/4716 [00:42<31:25,  2.45it/s]

  2%|▏         | 95/4716 [00:43<31:25,  2.45it/s]

  2%|▏         | 96/4716 [00:43<31:25,  2.45it/s]

  2%|▏         | 97/4716 [00:43<31:31,  2.44it/s]

  2%|▏         | 98/4716 [00:44<31:29,  2.44it/s]

  2%|▏         | 99/4716 [00:44<31:29,  2.44it/s]

  2%|▏         | 100/4716 [00:45<31:26,  2.45it/s]

  2%|▏         | 101/4716 [00:45<31:26,  2.45it/s]

  2%|▏         | 102/4716 [00:45<31:24,  2.45it/s]

  2%|▏         | 103/4716 [00:46<31:25,  2.45it/s]

  2%|▏         | 104/4716 [00:46<31:28,  2.44it/s]

  2%|▏         | 105/4716 [00:47<31:26,  2.44it/s]

  2%|▏         | 106/4716 [00:47<31:24,  2.45it/s]

  2%|▏         | 107/4716 [00:47<31:22,  2.45it/s]

  2%|▏         | 108/4716 [00:48<31:25,  2.44it/s]

  2%|▏         | 109/4716 [00:48<31:24,  2.44it/s]

  2%|▏         | 110/4716 [00:49<31:22,  2.45it/s]

  2%|▏         | 111/4716 [00:49<31:27,  2.44it/s]

  2%|▏         | 112/4716 [00:49<31:25,  2.44it/s]

  2%|▏         | 113/4716 [00:50<31:23,  2.44it/s]

  2%|▏         | 114/4716 [00:50<31:20,  2.45it/s]

  2%|▏         | 115/4716 [00:51<31:22,  2.44it/s]

  2%|▏         | 116/4716 [00:51<31:22,  2.44it/s]

  2%|▏         | 117/4716 [00:52<31:24,  2.44it/s]

  3%|▎         | 118/4716 [00:52<31:24,  2.44it/s]

  3%|▎         | 119/4716 [00:52<31:23,  2.44it/s]

  3%|▎         | 120/4716 [00:53<31:23,  2.44it/s]

  3%|▎         | 121/4716 [00:53<31:22,  2.44it/s]

  3%|▎         | 122/4716 [00:54<31:24,  2.44it/s]

  3%|▎         | 123/4716 [00:54<31:21,  2.44it/s]

  3%|▎         | 124/4716 [00:54<31:20,  2.44it/s]

  3%|▎         | 125/4716 [00:55<31:20,  2.44it/s]

  3%|▎         | 126/4716 [00:55<31:20,  2.44it/s]

  3%|▎         | 127/4716 [00:56<31:20,  2.44it/s]

  3%|▎         | 128/4716 [00:56<31:17,  2.44it/s]

  3%|▎         | 129/4716 [00:56<31:18,  2.44it/s]

  3%|▎         | 130/4716 [00:57<31:16,  2.44it/s]

  3%|▎         | 131/4716 [00:57<31:16,  2.44it/s]

  3%|▎         | 132/4716 [00:58<31:19,  2.44it/s]

  3%|▎         | 133/4716 [00:58<31:15,  2.44it/s]

  3%|▎         | 134/4716 [00:58<31:16,  2.44it/s]

  3%|▎         | 135/4716 [00:59<31:14,  2.44it/s]

  3%|▎         | 136/4716 [00:59<31:16,  2.44it/s]

  3%|▎         | 137/4716 [01:00<31:13,  2.44it/s]

  3%|▎         | 138/4716 [01:00<31:16,  2.44it/s]

  3%|▎         | 139/4716 [01:01<31:15,  2.44it/s]

  3%|▎         | 140/4716 [01:01<31:15,  2.44it/s]

  3%|▎         | 141/4716 [01:01<31:16,  2.44it/s]

  3%|▎         | 142/4716 [01:02<31:16,  2.44it/s]

  3%|▎         | 143/4716 [01:02<31:16,  2.44it/s]

  3%|▎         | 144/4716 [01:03<31:15,  2.44it/s]

  3%|▎         | 145/4716 [01:03<31:17,  2.43it/s]

  3%|▎         | 146/4716 [01:03<31:18,  2.43it/s]

  3%|▎         | 147/4716 [01:04<31:15,  2.44it/s]

  3%|▎         | 148/4716 [01:04<31:13,  2.44it/s]

  3%|▎         | 149/4716 [01:05<31:12,  2.44it/s]

  3%|▎         | 150/4716 [01:05<31:10,  2.44it/s]

  3%|▎         | 151/4716 [01:05<31:08,  2.44it/s]

  3%|▎         | 152/4716 [01:06<31:07,  2.44it/s]

  3%|▎         | 153/4716 [01:06<31:06,  2.45it/s]

  3%|▎         | 154/4716 [01:07<31:04,  2.45it/s]

  3%|▎         | 155/4716 [01:07<31:04,  2.45it/s]

  3%|▎         | 156/4716 [01:07<31:04,  2.45it/s]

  3%|▎         | 157/4716 [01:08<31:05,  2.44it/s]

  3%|▎         | 158/4716 [01:08<31:03,  2.45it/s]

  3%|▎         | 159/4716 [01:09<31:03,  2.45it/s]

  3%|▎         | 160/4716 [01:09<31:02,  2.45it/s]

  3%|▎         | 161/4716 [01:10<31:03,  2.44it/s]

  3%|▎         | 162/4716 [01:10<31:05,  2.44it/s]

  3%|▎         | 163/4716 [01:10<31:04,  2.44it/s]

  3%|▎         | 164/4716 [01:11<31:05,  2.44it/s]

  3%|▎         | 165/4716 [01:11<31:04,  2.44it/s]

  4%|▎         | 166/4716 [01:12<31:05,  2.44it/s]

  4%|▎         | 167/4716 [01:12<31:04,  2.44it/s]

  4%|▎         | 168/4716 [01:12<31:03,  2.44it/s]

  4%|▎         | 169/4716 [01:13<31:02,  2.44it/s]

  4%|▎         | 170/4716 [01:13<31:03,  2.44it/s]

  4%|▎         | 171/4716 [01:14<31:01,  2.44it/s]

  4%|▎         | 172/4716 [01:14<31:02,  2.44it/s]

  4%|▎         | 173/4716 [01:14<31:04,  2.44it/s]

  4%|▎         | 174/4716 [01:15<31:01,  2.44it/s]

  4%|▎         | 175/4716 [01:15<30:59,  2.44it/s]

  4%|▎         | 176/4716 [01:16<30:58,  2.44it/s]

  4%|▍         | 177/4716 [01:16<30:57,  2.44it/s]

  4%|▍         | 178/4716 [01:16<30:57,  2.44it/s]

  4%|▍         | 179/4716 [01:17<30:56,  2.44it/s]

  4%|▍         | 180/4716 [01:17<30:57,  2.44it/s]

  4%|▍         | 181/4716 [01:18<30:58,  2.44it/s]

  4%|▍         | 182/4716 [01:18<30:58,  2.44it/s]

  4%|▍         | 183/4716 [01:19<30:56,  2.44it/s]

  4%|▍         | 184/4716 [01:19<30:57,  2.44it/s]

  4%|▍         | 185/4716 [01:19<30:56,  2.44it/s]

  4%|▍         | 186/4716 [01:20<30:56,  2.44it/s]

  4%|▍         | 187/4716 [01:20<30:57,  2.44it/s]

  4%|▍         | 188/4716 [01:21<31:04,  2.43it/s]

  4%|▍         | 189/4716 [01:21<31:04,  2.43it/s]

  4%|▍         | 190/4716 [01:21<31:01,  2.43it/s]

  4%|▍         | 191/4716 [01:22<31:02,  2.43it/s]

  4%|▍         | 192/4716 [01:22<31:00,  2.43it/s]

  4%|▍         | 193/4716 [01:23<30:59,  2.43it/s]

  4%|▍         | 194/4716 [01:23<30:57,  2.43it/s]

  4%|▍         | 195/4716 [01:23<30:56,  2.44it/s]

  4%|▍         | 196/4716 [01:24<30:55,  2.44it/s]

  4%|▍         | 197/4716 [01:24<30:55,  2.44it/s]

  4%|▍         | 198/4716 [01:25<30:53,  2.44it/s]

  4%|▍         | 199/4716 [01:25<30:52,  2.44it/s]

  4%|▍         | 200/4716 [01:26<30:55,  2.43it/s]

  4%|▍         | 201/4716 [01:26<30:53,  2.44it/s]

  4%|▍         | 202/4716 [01:26<30:53,  2.44it/s]

  4%|▍         | 203/4716 [01:27<30:51,  2.44it/s]

  4%|▍         | 204/4716 [01:27<30:51,  2.44it/s]

  4%|▍         | 205/4716 [01:28<30:52,  2.44it/s]

  4%|▍         | 206/4716 [01:28<30:52,  2.44it/s]

  4%|▍         | 207/4716 [01:28<30:52,  2.43it/s]

  4%|▍         | 208/4716 [01:29<30:52,  2.43it/s]

  4%|▍         | 209/4716 [01:29<30:51,  2.43it/s]

  4%|▍         | 210/4716 [01:30<30:50,  2.44it/s]

  4%|▍         | 211/4716 [01:30<30:52,  2.43it/s]

  4%|▍         | 212/4716 [01:30<30:51,  2.43it/s]

  5%|▍         | 213/4716 [01:31<30:50,  2.43it/s]

  5%|▍         | 214/4716 [01:31<30:48,  2.44it/s]

  5%|▍         | 215/4716 [01:32<30:49,  2.43it/s]

  5%|▍         | 216/4716 [01:32<30:49,  2.43it/s]

  5%|▍         | 217/4716 [01:33<30:49,  2.43it/s]

  5%|▍         | 218/4716 [01:33<30:48,  2.43it/s]

  5%|▍         | 219/4716 [01:33<30:47,  2.43it/s]

  5%|▍         | 220/4716 [01:34<30:50,  2.43it/s]

  5%|▍         | 221/4716 [01:34<30:48,  2.43it/s]

  5%|▍         | 222/4716 [01:35<30:46,  2.43it/s]

  5%|▍         | 223/4716 [01:35<30:44,  2.44it/s]

  5%|▍         | 224/4716 [01:35<30:44,  2.44it/s]

  5%|▍         | 225/4716 [01:36<30:42,  2.44it/s]

  5%|▍         | 226/4716 [01:36<30:44,  2.43it/s]

  5%|▍         | 227/4716 [01:37<30:44,  2.43it/s]

  5%|▍         | 228/4716 [01:37<30:44,  2.43it/s]

  5%|▍         | 229/4716 [01:37<30:44,  2.43it/s]

  5%|▍         | 230/4716 [01:38<30:44,  2.43it/s]

  5%|▍         | 231/4716 [01:38<30:48,  2.43it/s]

  5%|▍         | 232/4716 [01:39<30:47,  2.43it/s]

  5%|▍         | 233/4716 [01:39<30:46,  2.43it/s]

  5%|▍         | 234/4716 [01:39<30:44,  2.43it/s]

  5%|▍         | 235/4716 [01:40<30:43,  2.43it/s]

  5%|▌         | 236/4716 [01:40<30:41,  2.43it/s]

  5%|▌         | 237/4716 [01:41<30:40,  2.43it/s]

  5%|▌         | 238/4716 [01:41<30:41,  2.43it/s]

  5%|▌         | 239/4716 [01:42<30:40,  2.43it/s]

  5%|▌         | 240/4716 [01:42<30:39,  2.43it/s]

  5%|▌         | 241/4716 [01:42<30:36,  2.44it/s]

  5%|▌         | 242/4716 [01:43<30:38,  2.43it/s]

  5%|▌         | 243/4716 [01:43<30:37,  2.43it/s]

  5%|▌         | 244/4716 [01:44<30:37,  2.43it/s]

  5%|▌         | 245/4716 [01:44<30:37,  2.43it/s]

  5%|▌         | 246/4716 [01:44<30:38,  2.43it/s]

  5%|▌         | 247/4716 [01:45<30:38,  2.43it/s]

  5%|▌         | 248/4716 [01:45<30:38,  2.43it/s]

  5%|▌         | 249/4716 [01:46<30:39,  2.43it/s]

  5%|▌         | 250/4716 [01:46<30:39,  2.43it/s]

  5%|▌         | 251/4716 [01:46<30:38,  2.43it/s]

  5%|▌         | 252/4716 [01:47<30:36,  2.43it/s]

  5%|▌         | 253/4716 [01:47<30:37,  2.43it/s]

  5%|▌         | 254/4716 [01:48<30:37,  2.43it/s]

  5%|▌         | 255/4716 [01:48<30:36,  2.43it/s]

  5%|▌         | 256/4716 [01:49<30:35,  2.43it/s]

  5%|▌         | 257/4716 [01:49<30:34,  2.43it/s]

  5%|▌         | 258/4716 [01:49<30:35,  2.43it/s]

  5%|▌         | 259/4716 [01:50<30:37,  2.43it/s]

  6%|▌         | 260/4716 [01:50<30:36,  2.43it/s]

  6%|▌         | 261/4716 [01:51<30:39,  2.42it/s]

  6%|▌         | 262/4716 [01:51<30:38,  2.42it/s]

  6%|▌         | 263/4716 [01:51<30:37,  2.42it/s]

  6%|▌         | 264/4716 [01:52<30:39,  2.42it/s]

  6%|▌         | 265/4716 [01:52<30:35,  2.42it/s]

  6%|▌         | 266/4716 [01:53<30:34,  2.43it/s]

  6%|▌         | 267/4716 [01:53<30:30,  2.43it/s]

  6%|▌         | 268/4716 [01:53<30:31,  2.43it/s]

  6%|▌         | 269/4716 [01:54<30:32,  2.43it/s]

  6%|▌         | 270/4716 [01:54<30:32,  2.43it/s]

  6%|▌         | 271/4716 [01:55<30:30,  2.43it/s]

  6%|▌         | 272/4716 [01:55<30:28,  2.43it/s]

  6%|▌         | 273/4716 [01:56<30:31,  2.43it/s]

  6%|▌         | 274/4716 [01:56<30:30,  2.43it/s]

  6%|▌         | 275/4716 [01:56<30:29,  2.43it/s]

  6%|▌         | 276/4716 [01:57<30:28,  2.43it/s]

  6%|▌         | 277/4716 [01:57<30:28,  2.43it/s]

  6%|▌         | 278/4716 [01:58<30:27,  2.43it/s]

  6%|▌         | 279/4716 [01:58<30:25,  2.43it/s]

  6%|▌         | 280/4716 [01:58<30:28,  2.43it/s]

  6%|▌         | 281/4716 [01:59<30:26,  2.43it/s]

  6%|▌         | 282/4716 [01:59<30:25,  2.43it/s]

  6%|▌         | 283/4716 [02:00<30:24,  2.43it/s]

  6%|▌         | 284/4716 [02:00<30:24,  2.43it/s]

  6%|▌         | 285/4716 [02:00<30:23,  2.43it/s]

  6%|▌         | 286/4716 [02:01<30:25,  2.43it/s]

  6%|▌         | 287/4716 [02:01<30:26,  2.42it/s]

  6%|▌         | 288/4716 [02:02<30:28,  2.42it/s]

  6%|▌         | 289/4716 [02:02<30:25,  2.43it/s]

  6%|▌         | 290/4716 [02:03<30:25,  2.42it/s]

  6%|▌         | 291/4716 [02:03<30:25,  2.42it/s]

  6%|▌         | 292/4716 [02:03<30:25,  2.42it/s]

  6%|▌         | 293/4716 [02:04<30:26,  2.42it/s]

  6%|▌         | 294/4716 [02:04<30:25,  2.42it/s]

  6%|▋         | 295/4716 [02:05<30:24,  2.42it/s]

  6%|▋         | 296/4716 [02:05<30:23,  2.42it/s]

  6%|▋         | 297/4716 [02:05<30:22,  2.42it/s]

  6%|▋         | 298/4716 [02:06<30:22,  2.42it/s]

  6%|▋         | 299/4716 [02:06<30:22,  2.42it/s]

  6%|▋         | 300/4716 [02:07<30:21,  2.42it/s]

  6%|▋         | 301/4716 [02:07<30:21,  2.42it/s]

  6%|▋         | 302/4716 [02:08<30:20,  2.42it/s]

  6%|▋         | 303/4716 [02:08<30:19,  2.42it/s]

  6%|▋         | 304/4716 [02:08<30:21,  2.42it/s]

  6%|▋         | 305/4716 [02:09<30:20,  2.42it/s]

  6%|▋         | 306/4716 [02:09<30:20,  2.42it/s]

  7%|▋         | 307/4716 [02:10<30:21,  2.42it/s]

  7%|▋         | 308/4716 [02:10<30:20,  2.42it/s]

  7%|▋         | 309/4716 [02:10<30:20,  2.42it/s]

  7%|▋         | 310/4716 [02:11<30:18,  2.42it/s]

  7%|▋         | 311/4716 [02:11<30:18,  2.42it/s]

  7%|▋         | 312/4716 [02:12<30:16,  2.42it/s]

  7%|▋         | 313/4716 [02:12<30:19,  2.42it/s]

  7%|▋         | 314/4716 [02:12<30:16,  2.42it/s]

  7%|▋         | 315/4716 [02:13<30:14,  2.43it/s]

  7%|▋         | 316/4716 [02:13<30:14,  2.42it/s]

  7%|▋         | 317/4716 [02:14<30:18,  2.42it/s]

  7%|▋         | 318/4716 [02:14<30:18,  2.42it/s]

  7%|▋         | 319/4716 [02:15<30:16,  2.42it/s]

  7%|▋         | 320/4716 [02:15<30:16,  2.42it/s]

  7%|▋         | 321/4716 [02:15<30:15,  2.42it/s]

  7%|▋         | 322/4716 [02:16<30:14,  2.42it/s]

  7%|▋         | 323/4716 [02:16<30:12,  2.42it/s]

  7%|▋         | 324/4716 [02:17<30:15,  2.42it/s]

  7%|▋         | 325/4716 [02:17<30:14,  2.42it/s]

  7%|▋         | 326/4716 [02:17<30:14,  2.42it/s]

  7%|▋         | 327/4716 [02:18<30:13,  2.42it/s]

  7%|▋         | 328/4716 [02:18<30:16,  2.42it/s]

  7%|▋         | 329/4716 [02:19<30:16,  2.42it/s]

  7%|▋         | 330/4716 [02:19<30:14,  2.42it/s]

  7%|▋         | 331/4716 [02:19<30:14,  2.42it/s]

  7%|▋         | 332/4716 [02:20<30:17,  2.41it/s]

  7%|▋         | 333/4716 [02:20<30:21,  2.41it/s]

  7%|▋         | 334/4716 [02:21<30:17,  2.41it/s]

  7%|▋         | 335/4716 [02:21<30:15,  2.41it/s]

  7%|▋         | 336/4716 [02:22<30:15,  2.41it/s]

  7%|▋         | 337/4716 [02:22<30:19,  2.41it/s]

  7%|▋         | 338/4716 [02:22<30:14,  2.41it/s]

  7%|▋         | 339/4716 [02:23<30:14,  2.41it/s]

  7%|▋         | 340/4716 [02:23<30:12,  2.41it/s]

  7%|▋         | 341/4716 [02:24<30:12,  2.41it/s]

  7%|▋         | 342/4716 [02:24<30:09,  2.42it/s]

  7%|▋         | 343/4716 [02:24<30:09,  2.42it/s]

  7%|▋         | 344/4716 [02:25<30:09,  2.42it/s]

  7%|▋         | 345/4716 [02:25<30:11,  2.41it/s]

  7%|▋         | 346/4716 [02:26<30:07,  2.42it/s]

  7%|▋         | 347/4716 [02:26<30:07,  2.42it/s]

  7%|▋         | 348/4716 [02:27<30:06,  2.42it/s]

  7%|▋         | 349/4716 [02:27<30:06,  2.42it/s]

  7%|▋         | 350/4716 [02:27<30:04,  2.42it/s]

  7%|▋         | 351/4716 [02:28<30:05,  2.42it/s]

  7%|▋         | 352/4716 [02:28<30:08,  2.41it/s]

  7%|▋         | 353/4716 [02:29<30:06,  2.42it/s]

  8%|▊         | 354/4716 [02:29<30:04,  2.42it/s]

  8%|▊         | 355/4716 [02:29<30:04,  2.42it/s]

  8%|▊         | 356/4716 [02:30<30:05,  2.41it/s]

  8%|▊         | 357/4716 [02:30<30:05,  2.41it/s]

  8%|▊         | 358/4716 [02:31<30:08,  2.41it/s]

  8%|▊         | 359/4716 [02:31<30:05,  2.41it/s]

  8%|▊         | 360/4716 [02:32<30:04,  2.41it/s]

  8%|▊         | 361/4716 [02:32<30:04,  2.41it/s]

  8%|▊         | 362/4716 [02:32<30:04,  2.41it/s]

  8%|▊         | 363/4716 [02:33<30:02,  2.41it/s]

  8%|▊         | 364/4716 [02:33<30:03,  2.41it/s]

  8%|▊         | 365/4716 [02:34<30:04,  2.41it/s]

  8%|▊         | 366/4716 [02:34<30:04,  2.41it/s]

  8%|▊         | 367/4716 [02:34<30:03,  2.41it/s]

  8%|▊         | 368/4716 [02:35<30:02,  2.41it/s]

  8%|▊         | 369/4716 [02:35<30:02,  2.41it/s]

  8%|▊         | 370/4716 [02:36<30:01,  2.41it/s]

  8%|▊         | 371/4716 [02:36<30:01,  2.41it/s]

  8%|▊         | 372/4716 [02:36<30:01,  2.41it/s]

  8%|▊         | 373/4716 [02:37<30:02,  2.41it/s]

  8%|▊         | 374/4716 [02:37<30:00,  2.41it/s]

  8%|▊         | 375/4716 [02:38<30:01,  2.41it/s]

  8%|▊         | 376/4716 [02:38<30:00,  2.41it/s]

  8%|▊         | 377/4716 [02:39<29:59,  2.41it/s]

  8%|▊         | 378/4716 [02:39<29:56,  2.41it/s]

  8%|▊         | 379/4716 [02:39<29:57,  2.41it/s]

  8%|▊         | 380/4716 [02:40<29:57,  2.41it/s]

  8%|▊         | 381/4716 [02:40<29:56,  2.41it/s]

  8%|▊         | 382/4716 [02:41<29:55,  2.41it/s]

  8%|▊         | 383/4716 [02:41<29:55,  2.41it/s]

  8%|▊         | 384/4716 [02:41<29:53,  2.41it/s]

  8%|▊         | 385/4716 [02:42<29:53,  2.41it/s]

  8%|▊         | 386/4716 [02:42<29:53,  2.41it/s]

  8%|▊         | 387/4716 [02:43<29:54,  2.41it/s]

  8%|▊         | 388/4716 [02:43<29:57,  2.41it/s]

  8%|▊         | 389/4716 [02:44<29:53,  2.41it/s]

  8%|▊         | 390/4716 [02:44<29:55,  2.41it/s]

  8%|▊         | 391/4716 [02:44<29:52,  2.41it/s]

  8%|▊         | 392/4716 [02:45<29:51,  2.41it/s]

  8%|▊         | 393/4716 [02:45<29:52,  2.41it/s]

  8%|▊         | 394/4716 [02:46<29:53,  2.41it/s]

  8%|▊         | 395/4716 [02:46<29:50,  2.41it/s]

  8%|▊         | 396/4716 [02:46<29:51,  2.41it/s]

  8%|▊         | 397/4716 [02:47<29:48,  2.41it/s]

  8%|▊         | 398/4716 [02:47<29:49,  2.41it/s]

  8%|▊         | 399/4716 [02:48<29:50,  2.41it/s]

  8%|▊         | 400/4716 [02:48<29:52,  2.41it/s]

  9%|▊         | 401/4716 [02:49<29:50,  2.41it/s]

  9%|▊         | 402/4716 [02:49<29:50,  2.41it/s]

  9%|▊         | 403/4716 [02:49<29:50,  2.41it/s]

  9%|▊         | 404/4716 [02:50<29:48,  2.41it/s]

  9%|▊         | 405/4716 [02:50<29:47,  2.41it/s]

  9%|▊         | 406/4716 [02:51<29:46,  2.41it/s]

  9%|▊         | 407/4716 [02:51<29:45,  2.41it/s]

  9%|▊         | 408/4716 [02:51<29:45,  2.41it/s]

  9%|▊         | 409/4716 [02:52<29:46,  2.41it/s]

  9%|▊         | 410/4716 [02:52<29:41,  2.42it/s]

  9%|▊         | 411/4716 [02:53<29:43,  2.41it/s]

  9%|▊         | 412/4716 [02:53<29:44,  2.41it/s]

  9%|▉         | 413/4716 [02:53<29:43,  2.41it/s]

  9%|▉         | 414/4716 [02:54<29:42,  2.41it/s]

  9%|▉         | 415/4716 [02:54<29:42,  2.41it/s]

  9%|▉         | 416/4716 [02:55<29:47,  2.41it/s]

  9%|▉         | 417/4716 [02:55<29:45,  2.41it/s]

  9%|▉         | 418/4716 [02:56<29:43,  2.41it/s]

  9%|▉         | 419/4716 [02:56<29:44,  2.41it/s]

  9%|▉         | 420/4716 [02:56<29:41,  2.41it/s]

  9%|▉         | 421/4716 [02:57<29:40,  2.41it/s]

  9%|▉         | 422/4716 [02:57<29:43,  2.41it/s]

  9%|▉         | 423/4716 [02:58<29:40,  2.41it/s]

  9%|▉         | 424/4716 [02:58<29:39,  2.41it/s]

  9%|▉         | 425/4716 [02:58<29:40,  2.41it/s]

  9%|▉         | 426/4716 [02:59<29:41,  2.41it/s]

  9%|▉         | 427/4716 [02:59<29:39,  2.41it/s]

  9%|▉         | 428/4716 [03:00<29:40,  2.41it/s]

  9%|▉         | 429/4716 [03:00<29:38,  2.41it/s]

  9%|▉         | 430/4716 [03:01<29:40,  2.41it/s]

  9%|▉         | 431/4716 [03:01<29:38,  2.41it/s]

  9%|▉         | 432/4716 [03:01<29:38,  2.41it/s]

  9%|▉         | 433/4716 [03:02<29:36,  2.41it/s]

  9%|▉         | 434/4716 [03:02<29:35,  2.41it/s]

  9%|▉         | 435/4716 [03:03<29:34,  2.41it/s]

  9%|▉         | 436/4716 [03:03<29:34,  2.41it/s]

  9%|▉         | 437/4716 [03:03<29:34,  2.41it/s]

  9%|▉         | 438/4716 [03:04<29:30,  2.42it/s]

  9%|▉         | 439/4716 [03:04<29:32,  2.41it/s]

  9%|▉         | 440/4716 [03:05<29:33,  2.41it/s]

  9%|▉         | 441/4716 [03:05<29:34,  2.41it/s]

  9%|▉         | 442/4716 [03:06<29:32,  2.41it/s]

  9%|▉         | 443/4716 [03:06<29:35,  2.41it/s]

  9%|▉         | 444/4716 [03:06<29:33,  2.41it/s]

  9%|▉         | 445/4716 [03:07<29:34,  2.41it/s]

  9%|▉         | 446/4716 [03:07<29:32,  2.41it/s]

  9%|▉         | 447/4716 [03:08<29:33,  2.41it/s]

  9%|▉         | 448/4716 [03:08<29:33,  2.41it/s]

 10%|▉         | 449/4716 [03:08<29:31,  2.41it/s]

 10%|▉         | 450/4716 [03:09<29:29,  2.41it/s]

 10%|▉         | 451/4716 [03:09<29:29,  2.41it/s]

 10%|▉         | 452/4716 [03:10<29:28,  2.41it/s]

 10%|▉         | 453/4716 [03:10<29:30,  2.41it/s]

 10%|▉         | 454/4716 [03:10<29:30,  2.41it/s]

 10%|▉         | 455/4716 [03:11<29:30,  2.41it/s]

 10%|▉         | 456/4716 [03:11<29:31,  2.41it/s]

 10%|▉         | 457/4716 [03:12<29:29,  2.41it/s]

 10%|▉         | 458/4716 [03:12<29:29,  2.41it/s]

 10%|▉         | 459/4716 [03:13<29:28,  2.41it/s]

 10%|▉         | 460/4716 [03:13<29:31,  2.40it/s]

 10%|▉         | 461/4716 [03:13<29:29,  2.40it/s]

 10%|▉         | 462/4716 [03:14<29:27,  2.41it/s]

 10%|▉         | 463/4716 [03:14<29:25,  2.41it/s]

 10%|▉         | 464/4716 [03:15<29:27,  2.41it/s]

 10%|▉         | 465/4716 [03:15<29:26,  2.41it/s]

 10%|▉         | 466/4716 [03:15<29:25,  2.41it/s]

 10%|▉         | 467/4716 [03:16<29:22,  2.41it/s]

 10%|▉         | 468/4716 [03:16<29:24,  2.41it/s]

 10%|▉         | 469/4716 [03:17<29:24,  2.41it/s]

 10%|▉         | 470/4716 [03:17<29:22,  2.41it/s]

 10%|▉         | 471/4716 [03:18<29:26,  2.40it/s]

 10%|█         | 472/4716 [03:18<29:23,  2.41it/s]

 10%|█         | 473/4716 [03:18<29:25,  2.40it/s]

 10%|█         | 474/4716 [03:19<29:23,  2.41it/s]

 10%|█         | 475/4716 [03:19<29:21,  2.41it/s]

 10%|█         | 476/4716 [03:20<29:22,  2.41it/s]

 10%|█         | 477/4716 [03:20<29:22,  2.41it/s]

 10%|█         | 478/4716 [03:20<29:20,  2.41it/s]

 10%|█         | 479/4716 [03:21<29:20,  2.41it/s]

 10%|█         | 480/4716 [03:21<29:19,  2.41it/s]

 10%|█         | 481/4716 [03:22<29:20,  2.41it/s]

 10%|█         | 482/4716 [03:22<29:23,  2.40it/s]

 10%|█         | 483/4716 [03:23<29:22,  2.40it/s]

 10%|█         | 484/4716 [03:23<29:21,  2.40it/s]

 10%|█         | 485/4716 [03:23<29:19,  2.40it/s]

 10%|█         | 486/4716 [03:24<29:20,  2.40it/s]

 10%|█         | 487/4716 [03:24<29:18,  2.40it/s]

 10%|█         | 488/4716 [03:25<29:18,  2.40it/s]

 10%|█         | 489/4716 [03:25<29:18,  2.40it/s]

 10%|█         | 490/4716 [03:25<29:17,  2.41it/s]

 10%|█         | 491/4716 [03:26<29:17,  2.40it/s]

 10%|█         | 492/4716 [03:26<29:17,  2.40it/s]

 10%|█         | 493/4716 [03:27<29:15,  2.40it/s]

 10%|█         | 494/4716 [03:27<29:16,  2.40it/s]

 10%|█         | 495/4716 [03:28<29:15,  2.40it/s]

 11%|█         | 496/4716 [03:28<29:14,  2.41it/s]

 11%|█         | 497/4716 [03:28<29:13,  2.41it/s]

 11%|█         | 498/4716 [03:29<29:12,  2.41it/s]

 11%|█         | 499/4716 [03:29<29:12,  2.41it/s]

 11%|█         | 500/4716 [03:30<29:11,  2.41it/s]

 11%|█         | 501/4716 [03:30<29:13,  2.40it/s]

 11%|█         | 502/4716 [03:30<29:13,  2.40it/s]

 11%|█         | 503/4716 [03:31<29:13,  2.40it/s]

 11%|█         | 504/4716 [03:31<29:12,  2.40it/s]

 11%|█         | 505/4716 [03:32<29:13,  2.40it/s]

 11%|█         | 506/4716 [03:32<29:10,  2.40it/s]

 11%|█         | 507/4716 [03:33<29:11,  2.40it/s]

 11%|█         | 508/4716 [03:33<29:11,  2.40it/s]

 11%|█         | 509/4716 [03:33<29:11,  2.40it/s]

 11%|█         | 510/4716 [03:34<29:08,  2.41it/s]

 11%|█         | 511/4716 [03:34<29:07,  2.41it/s]

 11%|█         | 512/4716 [03:35<29:07,  2.41it/s]

 11%|█         | 513/4716 [03:35<29:08,  2.40it/s]

 11%|█         | 514/4716 [03:35<29:09,  2.40it/s]

 11%|█         | 515/4716 [03:36<29:12,  2.40it/s]

 11%|█         | 516/4716 [03:36<29:10,  2.40it/s]

 11%|█         | 517/4716 [03:37<29:07,  2.40it/s]

 11%|█         | 518/4716 [03:37<29:07,  2.40it/s]

 11%|█         | 519/4716 [03:38<29:06,  2.40it/s]

 11%|█         | 520/4716 [03:38<29:06,  2.40it/s]

 11%|█         | 521/4716 [03:38<29:05,  2.40it/s]

 11%|█         | 522/4716 [03:39<29:06,  2.40it/s]

 11%|█         | 523/4716 [03:39<29:05,  2.40it/s]

 11%|█         | 524/4716 [03:40<29:07,  2.40it/s]

 11%|█         | 525/4716 [03:40<29:04,  2.40it/s]

 11%|█         | 526/4716 [03:40<29:07,  2.40it/s]

 11%|█         | 527/4716 [03:41<29:04,  2.40it/s]

 11%|█         | 528/4716 [03:41<29:05,  2.40it/s]

 11%|█         | 529/4716 [03:42<29:04,  2.40it/s]

 11%|█         | 530/4716 [03:42<29:04,  2.40it/s]

 11%|█▏        | 531/4716 [03:43<29:02,  2.40it/s]

 11%|█▏        | 532/4716 [03:43<29:04,  2.40it/s]

 11%|█▏        | 533/4716 [03:43<29:04,  2.40it/s]

 11%|█▏        | 534/4716 [03:44<29:04,  2.40it/s]

 11%|█▏        | 535/4716 [03:44<29:02,  2.40it/s]

 11%|█▏        | 536/4716 [03:45<28:59,  2.40it/s]

 11%|█▏        | 537/4716 [03:45<29:01,  2.40it/s]

 11%|█▏        | 538/4716 [03:45<29:00,  2.40it/s]

 11%|█▏        | 539/4716 [03:46<28:59,  2.40it/s]

 11%|█▏        | 540/4716 [03:46<28:59,  2.40it/s]

 11%|█▏        | 541/4716 [03:47<28:58,  2.40it/s]

 11%|█▏        | 542/4716 [03:47<28:59,  2.40it/s]

 12%|█▏        | 543/4716 [03:48<28:58,  2.40it/s]

 12%|█▏        | 544/4716 [03:48<28:59,  2.40it/s]

 12%|█▏        | 545/4716 [03:48<29:00,  2.40it/s]

 12%|█▏        | 546/4716 [03:49<29:00,  2.40it/s]

 12%|█▏        | 547/4716 [03:49<28:57,  2.40it/s]

 12%|█▏        | 548/4716 [03:50<28:57,  2.40it/s]

 12%|█▏        | 549/4716 [03:50<28:55,  2.40it/s]

 12%|█▏        | 550/4716 [03:50<28:54,  2.40it/s]

 12%|█▏        | 551/4716 [03:51<28:53,  2.40it/s]

 12%|█▏        | 552/4716 [03:51<28:54,  2.40it/s]

 12%|█▏        | 553/4716 [03:52<28:54,  2.40it/s]

 12%|█▏        | 554/4716 [03:52<28:54,  2.40it/s]

 12%|█▏        | 555/4716 [03:53<28:53,  2.40it/s]

 12%|█▏        | 556/4716 [03:53<28:53,  2.40it/s]

 12%|█▏        | 557/4716 [03:53<28:56,  2.40it/s]

 12%|█▏        | 558/4716 [03:54<28:55,  2.40it/s]

 12%|█▏        | 559/4716 [03:54<28:55,  2.40it/s]

 12%|█▏        | 560/4716 [03:55<28:55,  2.39it/s]

 12%|█▏        | 561/4716 [03:55<28:52,  2.40it/s]

 12%|█▏        | 562/4716 [03:55<28:53,  2.40it/s]

 12%|█▏        | 563/4716 [03:56<28:52,  2.40it/s]

 12%|█▏        | 564/4716 [03:56<28:50,  2.40it/s]

 12%|█▏        | 565/4716 [03:57<28:49,  2.40it/s]

 12%|█▏        | 566/4716 [03:57<28:48,  2.40it/s]

 12%|█▏        | 567/4716 [03:58<28:48,  2.40it/s]

 12%|█▏        | 568/4716 [03:58<28:47,  2.40it/s]

 12%|█▏        | 569/4716 [03:58<28:46,  2.40it/s]

 12%|█▏        | 570/4716 [03:59<28:46,  2.40it/s]

 12%|█▏        | 571/4716 [03:59<28:46,  2.40it/s]

 12%|█▏        | 572/4716 [04:00<28:46,  2.40it/s]

 12%|█▏        | 573/4716 [04:00<28:45,  2.40it/s]

 12%|█▏        | 574/4716 [04:00<28:45,  2.40it/s]

 12%|█▏        | 575/4716 [04:01<28:47,  2.40it/s]

 12%|█▏        | 576/4716 [04:01<28:46,  2.40it/s]

 12%|█▏        | 577/4716 [04:02<28:47,  2.40it/s]

 12%|█▏        | 578/4716 [04:02<28:45,  2.40it/s]

 12%|█▏        | 579/4716 [04:03<28:45,  2.40it/s]

 12%|█▏        | 580/4716 [04:03<28:43,  2.40it/s]

 12%|█▏        | 581/4716 [04:03<28:45,  2.40it/s]

 12%|█▏        | 582/4716 [04:04<28:45,  2.40it/s]

 12%|█▏        | 583/4716 [04:04<28:44,  2.40it/s]

 12%|█▏        | 584/4716 [04:05<28:43,  2.40it/s]

 12%|█▏        | 585/4716 [04:05<28:41,  2.40it/s]

 12%|█▏        | 586/4716 [04:05<28:42,  2.40it/s]

 12%|█▏        | 587/4716 [04:06<28:42,  2.40it/s]

 12%|█▏        | 588/4716 [04:06<28:41,  2.40it/s]

 12%|█▏        | 589/4716 [04:07<28:43,  2.39it/s]

 13%|█▎        | 590/4716 [04:07<28:42,  2.39it/s]

 13%|█▎        | 591/4716 [04:08<28:40,  2.40it/s]

 13%|█▎        | 592/4716 [04:08<28:42,  2.39it/s]

 13%|█▎        | 593/4716 [04:08<28:43,  2.39it/s]

 13%|█▎        | 594/4716 [04:09<28:43,  2.39it/s]

 13%|█▎        | 595/4716 [04:09<28:39,  2.40it/s]

 13%|█▎        | 596/4716 [04:10<28:38,  2.40it/s]

 13%|█▎        | 597/4716 [04:10<28:39,  2.40it/s]

 13%|█▎        | 598/4716 [04:10<28:38,  2.40it/s]

 13%|█▎        | 599/4716 [04:11<28:35,  2.40it/s]

 13%|█▎        | 600/4716 [04:11<28:37,  2.40it/s]

 13%|█▎        | 601/4716 [04:12<28:36,  2.40it/s]

 13%|█▎        | 602/4716 [04:12<28:35,  2.40it/s]

 13%|█▎        | 603/4716 [04:13<28:35,  2.40it/s]

 13%|█▎        | 604/4716 [04:13<28:36,  2.40it/s]

 13%|█▎        | 605/4716 [04:13<28:35,  2.40it/s]

 13%|█▎        | 606/4716 [04:14<28:36,  2.39it/s]

 13%|█▎        | 607/4716 [04:14<28:35,  2.40it/s]

 13%|█▎        | 608/4716 [04:15<28:38,  2.39it/s]

 13%|█▎        | 609/4716 [04:15<28:37,  2.39it/s]

 13%|█▎        | 610/4716 [04:15<28:37,  2.39it/s]

 13%|█▎        | 611/4716 [04:16<28:36,  2.39it/s]

 13%|█▎        | 612/4716 [04:16<28:34,  2.39it/s]

 13%|█▎        | 613/4716 [04:17<28:34,  2.39it/s]

 13%|█▎        | 614/4716 [04:17<28:37,  2.39it/s]

 13%|█▎        | 615/4716 [04:18<28:34,  2.39it/s]

 13%|█▎        | 616/4716 [04:18<28:32,  2.39it/s]

 13%|█▎        | 617/4716 [04:18<28:29,  2.40it/s]

 13%|█▎        | 618/4716 [04:19<28:32,  2.39it/s]

 13%|█▎        | 619/4716 [04:19<28:33,  2.39it/s]

 13%|█▎        | 620/4716 [04:20<28:35,  2.39it/s]

 13%|█▎        | 621/4716 [04:20<28:34,  2.39it/s]

 13%|█▎        | 622/4716 [04:20<28:34,  2.39it/s]

 13%|█▎        | 623/4716 [04:21<28:31,  2.39it/s]

 13%|█▎        | 624/4716 [04:21<28:31,  2.39it/s]

 13%|█▎        | 625/4716 [04:22<28:29,  2.39it/s]

logging
logging the anndata

 13%|█▎        | 626/4716 [04:22<30:21,  2.25it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 13%|█▎        | 627/4716 [04:23<29:40,  2.30it/s]

 13%|█▎        | 628/4716 [04:23<29:08,  2.34it/s]

 13%|█▎        | 629/4716 [04:23<28:45,  2.37it/s]

 13%|█▎        | 630/4716 [04:24<28:31,  2.39it/s]

 13%|█▎        | 631/4716 [04:24<28:19,  2.40it/s]

 13%|█▎        | 632/4716 [04:25<28:10,  2.42it/s]

 13%|█▎        | 633/4716 [04:25<28:05,  2.42it/s]

 13%|█▎        | 634/4716 [04:26<28:01,  2.43it/s]

 13%|█▎        | 635/4716 [04:26<27:58,  2.43it/s]

 13%|█▎        | 636/4716 [04:26<27:54,  2.44it/s]

 14%|█▎        | 637/4716 [04:27<27:53,  2.44it/s]

 14%|█▎        | 638/4716 [04:27<27:52,  2.44it/s]

 14%|█▎        | 639/4716 [04:28<27:53,  2.44it/s]

 14%|█▎        | 640/4716 [04:28<27:51,  2.44it/s]

 14%|█▎        | 641/4716 [04:28<27:49,  2.44it/s]

 14%|█▎        | 642/4716 [04:29<27:50,  2.44it/s]

 14%|█▎        | 643/4716 [04:29<27:50,  2.44it/s]

 14%|█▎        | 644/4716 [04:30<27:51,  2.44it/s]

 14%|█▎        | 645/4716 [04:30<27:50,  2.44it/s]

 14%|█▎        | 646/4716 [04:30<27:49,  2.44it/s]

 14%|█▎        | 647/4716 [04:31<27:48,  2.44it/s]

 14%|█▎        | 648/4716 [04:31<27:48,  2.44it/s]

 14%|█▍        | 649/4716 [04:32<27:48,  2.44it/s]

 14%|█▍        | 650/4716 [04:32<27:48,  2.44it/s]

 14%|█▍        | 651/4716 [04:33<27:48,  2.44it/s]

 14%|█▍        | 652/4716 [04:33<27:47,  2.44it/s]

 14%|█▍        | 653/4716 [04:33<27:50,  2.43it/s]

 14%|█▍        | 654/4716 [04:34<27:50,  2.43it/s]

 14%|█▍        | 655/4716 [04:34<27:49,  2.43it/s]

 14%|█▍        | 656/4716 [04:35<27:47,  2.43it/s]

 14%|█▍        | 657/4716 [04:35<27:47,  2.43it/s]

 14%|█▍        | 658/4716 [04:35<27:45,  2.44it/s]

 14%|█▍        | 659/4716 [04:36<27:45,  2.44it/s]

 14%|█▍        | 660/4716 [04:36<27:45,  2.44it/s]

 14%|█▍        | 661/4716 [04:37<27:45,  2.44it/s]

 14%|█▍        | 662/4716 [04:37<27:45,  2.43it/s]

 14%|█▍        | 663/4716 [04:37<27:42,  2.44it/s]

 14%|█▍        | 664/4716 [04:38<27:43,  2.44it/s]

 14%|█▍        | 665/4716 [04:38<27:42,  2.44it/s]

 14%|█▍        | 666/4716 [04:39<27:41,  2.44it/s]

 14%|█▍        | 667/4716 [04:39<27:41,  2.44it/s]

 14%|█▍        | 668/4716 [04:39<27:41,  2.44it/s]

 14%|█▍        | 669/4716 [04:40<27:40,  2.44it/s]

 14%|█▍        | 670/4716 [04:40<27:41,  2.44it/s]

 14%|█▍        | 671/4716 [04:41<27:41,  2.43it/s]

 14%|█▍        | 672/4716 [04:41<27:41,  2.43it/s]

 14%|█▍        | 673/4716 [04:42<27:43,  2.43it/s]

 14%|█▍        | 674/4716 [04:42<27:42,  2.43it/s]

 14%|█▍        | 675/4716 [04:42<27:41,  2.43it/s]

 14%|█▍        | 676/4716 [04:43<27:39,  2.44it/s]

 14%|█▍        | 677/4716 [04:43<27:37,  2.44it/s]

 14%|█▍        | 678/4716 [04:44<27:37,  2.44it/s]

 14%|█▍        | 679/4716 [04:44<27:37,  2.44it/s]

 14%|█▍        | 680/4716 [04:44<27:37,  2.43it/s]

 14%|█▍        | 681/4716 [04:45<27:38,  2.43it/s]

 14%|█▍        | 682/4716 [04:45<27:39,  2.43it/s]

 14%|█▍        | 683/4716 [04:46<27:38,  2.43it/s]

 15%|█▍        | 684/4716 [04:46<27:38,  2.43it/s]

 15%|█▍        | 685/4716 [04:46<27:35,  2.43it/s]

 15%|█▍        | 686/4716 [04:47<27:35,  2.43it/s]

 15%|█▍        | 687/4716 [04:47<27:35,  2.43it/s]

 15%|█▍        | 688/4716 [04:48<27:35,  2.43it/s]

 15%|█▍        | 689/4716 [04:48<27:35,  2.43it/s]

 15%|█▍        | 690/4716 [04:49<27:35,  2.43it/s]

 15%|█▍        | 691/4716 [04:49<27:34,  2.43it/s]

 15%|█▍        | 692/4716 [04:49<27:33,  2.43it/s]

 15%|█▍        | 693/4716 [04:50<27:34,  2.43it/s]

 15%|█▍        | 694/4716 [04:50<27:33,  2.43it/s]

 15%|█▍        | 695/4716 [04:51<27:37,  2.43it/s]

 15%|█▍        | 696/4716 [04:51<27:34,  2.43it/s]

 15%|█▍        | 697/4716 [04:51<27:34,  2.43it/s]

 15%|█▍        | 698/4716 [04:52<27:32,  2.43it/s]

 15%|█▍        | 699/4716 [04:52<27:30,  2.43it/s]

 15%|█▍        | 700/4716 [04:53<27:30,  2.43it/s]

 15%|█▍        | 701/4716 [04:53<27:29,  2.43it/s]

 15%|█▍        | 702/4716 [04:53<27:30,  2.43it/s]

 15%|█▍        | 703/4716 [04:54<27:28,  2.43it/s]

 15%|█▍        | 704/4716 [04:54<27:30,  2.43it/s]

 15%|█▍        | 705/4716 [04:55<27:31,  2.43it/s]

 15%|█▍        | 706/4716 [04:55<27:30,  2.43it/s]

 15%|█▍        | 707/4716 [04:56<27:28,  2.43it/s]

 15%|█▌        | 708/4716 [04:56<27:27,  2.43it/s]

 15%|█▌        | 709/4716 [04:56<27:27,  2.43it/s]

 15%|█▌        | 710/4716 [04:57<27:27,  2.43it/s]

 15%|█▌        | 711/4716 [04:57<27:27,  2.43it/s]

 15%|█▌        | 712/4716 [04:58<27:25,  2.43it/s]

 15%|█▌        | 713/4716 [04:58<27:26,  2.43it/s]

 15%|█▌        | 714/4716 [04:58<27:25,  2.43it/s]

 15%|█▌        | 715/4716 [04:59<27:26,  2.43it/s]

 15%|█▌        | 716/4716 [04:59<27:27,  2.43it/s]

 15%|█▌        | 717/4716 [05:00<27:26,  2.43it/s]

 15%|█▌        | 718/4716 [05:00<27:26,  2.43it/s]

 15%|█▌        | 719/4716 [05:00<27:26,  2.43it/s]

 15%|█▌        | 720/4716 [05:01<27:26,  2.43it/s]

 15%|█▌        | 721/4716 [05:01<27:24,  2.43it/s]

 15%|█▌        | 722/4716 [05:02<27:23,  2.43it/s]

 15%|█▌        | 723/4716 [05:02<27:21,  2.43it/s]

 15%|█▌        | 724/4716 [05:03<27:22,  2.43it/s]

 15%|█▌        | 725/4716 [05:03<27:21,  2.43it/s]

 15%|█▌        | 726/4716 [05:03<27:21,  2.43it/s]

 15%|█▌        | 727/4716 [05:04<27:19,  2.43it/s]

 15%|█▌        | 728/4716 [05:04<27:19,  2.43it/s]

 15%|█▌        | 729/4716 [05:05<27:21,  2.43it/s]

 15%|█▌        | 730/4716 [05:05<27:20,  2.43it/s]

 16%|█▌        | 731/4716 [05:05<27:19,  2.43it/s]

 16%|█▌        | 732/4716 [05:06<27:17,  2.43it/s]

 16%|█▌        | 733/4716 [05:06<27:17,  2.43it/s]

 16%|█▌        | 734/4716 [05:07<27:17,  2.43it/s]

 16%|█▌        | 735/4716 [05:07<27:20,  2.43it/s]

 16%|█▌        | 736/4716 [05:07<27:18,  2.43it/s]

 16%|█▌        | 737/4716 [05:08<27:17,  2.43it/s]

 16%|█▌        | 738/4716 [05:08<27:16,  2.43it/s]

 16%|█▌        | 739/4716 [05:09<27:17,  2.43it/s]

 16%|█▌        | 740/4716 [05:09<27:15,  2.43it/s]

 16%|█▌        | 741/4716 [05:10<27:16,  2.43it/s]

 16%|█▌        | 742/4716 [05:10<27:16,  2.43it/s]

 16%|█▌        | 743/4716 [05:10<27:16,  2.43it/s]

 16%|█▌        | 744/4716 [05:11<27:15,  2.43it/s]

 16%|█▌        | 745/4716 [05:11<27:14,  2.43it/s]

 16%|█▌        | 746/4716 [05:12<27:15,  2.43it/s]

 16%|█▌        | 747/4716 [05:12<27:17,  2.42it/s]

 16%|█▌        | 748/4716 [05:12<27:16,  2.42it/s]

 16%|█▌        | 749/4716 [05:13<27:15,  2.43it/s]

 16%|█▌        | 750/4716 [05:13<27:16,  2.42it/s]

 16%|█▌        | 751/4716 [05:14<27:14,  2.43it/s]

 16%|█▌        | 752/4716 [05:14<27:12,  2.43it/s]

 16%|█▌        | 753/4716 [05:14<27:12,  2.43it/s]

 16%|█▌        | 754/4716 [05:15<27:11,  2.43it/s]

 16%|█▌        | 755/4716 [05:15<27:12,  2.43it/s]

 16%|█▌        | 756/4716 [05:16<27:11,  2.43it/s]

 16%|█▌        | 757/4716 [05:16<27:12,  2.43it/s]

 16%|█▌        | 758/4716 [05:17<27:11,  2.43it/s]

 16%|█▌        | 759/4716 [05:17<27:12,  2.42it/s]

 16%|█▌        | 760/4716 [05:17<27:12,  2.42it/s]

 16%|█▌        | 761/4716 [05:18<27:11,  2.42it/s]

 16%|█▌        | 762/4716 [05:18<27:09,  2.43it/s]

 16%|█▌        | 763/4716 [05:19<27:09,  2.43it/s]

 16%|█▌        | 764/4716 [05:19<27:09,  2.43it/s]

 16%|█▌        | 765/4716 [05:19<27:08,  2.43it/s]

 16%|█▌        | 766/4716 [05:20<27:08,  2.43it/s]

 16%|█▋        | 767/4716 [05:20<27:06,  2.43it/s]

 16%|█▋        | 768/4716 [05:21<27:08,  2.42it/s]

 16%|█▋        | 769/4716 [05:21<27:06,  2.43it/s]

 16%|█▋        | 770/4716 [05:21<27:06,  2.43it/s]

 16%|█▋        | 771/4716 [05:22<27:05,  2.43it/s]

 16%|█▋        | 772/4716 [05:22<27:05,  2.43it/s]

 16%|█▋        | 773/4716 [05:23<27:05,  2.43it/s]

 16%|█▋        | 774/4716 [05:23<27:07,  2.42it/s]

 16%|█▋        | 775/4716 [05:24<27:05,  2.42it/s]

 16%|█▋        | 776/4716 [05:24<27:05,  2.42it/s]

 16%|█▋        | 777/4716 [05:24<27:07,  2.42it/s]

 16%|█▋        | 778/4716 [05:25<27:04,  2.42it/s]

 17%|█▋        | 779/4716 [05:25<27:03,  2.42it/s]

 17%|█▋        | 780/4716 [05:26<27:02,  2.43it/s]

 17%|█▋        | 781/4716 [05:26<27:04,  2.42it/s]

 17%|█▋        | 782/4716 [05:26<27:03,  2.42it/s]

 17%|█▋        | 783/4716 [05:27<27:04,  2.42it/s]

 17%|█▋        | 784/4716 [05:27<27:02,  2.42it/s]

 17%|█▋        | 785/4716 [05:28<27:03,  2.42it/s]

 17%|█▋        | 786/4716 [05:28<27:01,  2.42it/s]

 17%|█▋        | 787/4716 [05:28<27:00,  2.42it/s]

 17%|█▋        | 788/4716 [05:29<27:01,  2.42it/s]

 17%|█▋        | 789/4716 [05:29<26:59,  2.42it/s]

 17%|█▋        | 790/4716 [05:30<26:59,  2.42it/s]

 17%|█▋        | 791/4716 [05:30<26:58,  2.43it/s]

 17%|█▋        | 792/4716 [05:31<26:59,  2.42it/s]

 17%|█▋        | 793/4716 [05:31<26:58,  2.42it/s]

 17%|█▋        | 794/4716 [05:31<26:58,  2.42it/s]

 17%|█▋        | 795/4716 [05:32<26:59,  2.42it/s]

 17%|█▋        | 796/4716 [05:32<26:57,  2.42it/s]

 17%|█▋        | 797/4716 [05:33<26:55,  2.43it/s]

 17%|█▋        | 798/4716 [05:33<26:54,  2.43it/s]

 17%|█▋        | 799/4716 [05:33<26:53,  2.43it/s]

 17%|█▋        | 800/4716 [05:34<27:05,  2.41it/s]

 17%|█▋        | 801/4716 [05:34<27:02,  2.41it/s]

 17%|█▋        | 802/4716 [05:35<26:59,  2.42it/s]

 17%|█▋        | 803/4716 [05:35<27:00,  2.42it/s]

 17%|█▋        | 804/4716 [05:36<26:59,  2.42it/s]

 17%|█▋        | 805/4716 [05:36<26:58,  2.42it/s]

 17%|█▋        | 806/4716 [05:36<26:57,  2.42it/s]

 17%|█▋        | 807/4716 [05:37<26:55,  2.42it/s]

 17%|█▋        | 808/4716 [05:37<26:56,  2.42it/s]

 17%|█▋        | 809/4716 [05:38<26:52,  2.42it/s]

 17%|█▋        | 810/4716 [05:38<26:52,  2.42it/s]

 17%|█▋        | 811/4716 [05:38<26:52,  2.42it/s]

 17%|█▋        | 812/4716 [05:39<26:51,  2.42it/s]

 17%|█▋        | 813/4716 [05:39<26:53,  2.42it/s]

 17%|█▋        | 814/4716 [05:40<26:53,  2.42it/s]

 17%|█▋        | 815/4716 [05:40<26:53,  2.42it/s]

 17%|█▋        | 816/4716 [05:40<26:51,  2.42it/s]

 17%|█▋        | 817/4716 [05:41<26:50,  2.42it/s]

 17%|█▋        | 818/4716 [05:41<26:50,  2.42it/s]

 17%|█▋        | 819/4716 [05:42<26:49,  2.42it/s]

 17%|█▋        | 820/4716 [05:42<26:48,  2.42it/s]

 17%|█▋        | 821/4716 [05:43<26:48,  2.42it/s]

 17%|█▋        | 822/4716 [05:43<26:47,  2.42it/s]

 17%|█▋        | 823/4716 [05:43<26:47,  2.42it/s]

 17%|█▋        | 824/4716 [05:44<26:44,  2.43it/s]

 17%|█▋        | 825/4716 [05:44<26:46,  2.42it/s]

 18%|█▊        | 826/4716 [05:45<26:47,  2.42it/s]

 18%|█▊        | 827/4716 [05:45<26:45,  2.42it/s]

 18%|█▊        | 828/4716 [05:45<26:45,  2.42it/s]

 18%|█▊        | 829/4716 [05:46<26:44,  2.42it/s]

 18%|█▊        | 830/4716 [05:46<26:43,  2.42it/s]

 18%|█▊        | 831/4716 [05:47<26:43,  2.42it/s]

 18%|█▊        | 832/4716 [05:47<26:43,  2.42it/s]

 18%|█▊        | 833/4716 [05:47<26:42,  2.42it/s]

 18%|█▊        | 834/4716 [05:48<26:42,  2.42it/s]

 18%|█▊        | 835/4716 [05:48<26:42,  2.42it/s]

 18%|█▊        | 836/4716 [05:49<26:42,  2.42it/s]

 18%|█▊        | 837/4716 [05:49<26:40,  2.42it/s]

 18%|█▊        | 838/4716 [05:50<26:42,  2.42it/s]

 18%|█▊        | 839/4716 [05:50<26:40,  2.42it/s]

 18%|█▊        | 840/4716 [05:50<26:41,  2.42it/s]

 18%|█▊        | 841/4716 [05:51<26:39,  2.42it/s]

 18%|█▊        | 842/4716 [05:51<26:43,  2.42it/s]

 18%|█▊        | 843/4716 [05:52<26:42,  2.42it/s]

 18%|█▊        | 844/4716 [05:52<26:42,  2.42it/s]

 18%|█▊        | 845/4716 [05:52<26:42,  2.42it/s]

 18%|█▊        | 846/4716 [05:53<26:40,  2.42it/s]

 18%|█▊        | 847/4716 [05:53<26:40,  2.42it/s]

 18%|█▊        | 848/4716 [05:54<26:39,  2.42it/s]

 18%|█▊        | 849/4716 [05:54<26:38,  2.42it/s]

 18%|█▊        | 850/4716 [05:55<26:38,  2.42it/s]

 18%|█▊        | 851/4716 [05:55<26:37,  2.42it/s]

 18%|█▊        | 852/4716 [05:55<26:36,  2.42it/s]

 18%|█▊        | 853/4716 [05:56<26:35,  2.42it/s]

 18%|█▊        | 854/4716 [05:56<26:38,  2.42it/s]

 18%|█▊        | 855/4716 [05:57<26:38,  2.41it/s]

 18%|█▊        | 856/4716 [05:57<26:37,  2.42it/s]

 18%|█▊        | 857/4716 [05:57<26:37,  2.42it/s]

 18%|█▊        | 858/4716 [05:58<26:35,  2.42it/s]

 18%|█▊        | 859/4716 [05:58<26:34,  2.42it/s]

 18%|█▊        | 860/4716 [05:59<26:33,  2.42it/s]

 18%|█▊        | 861/4716 [05:59<26:32,  2.42it/s]

 18%|█▊        | 862/4716 [05:59<26:35,  2.41it/s]

 18%|█▊        | 863/4716 [06:00<26:33,  2.42it/s]

 18%|█▊        | 864/4716 [06:00<26:32,  2.42it/s]

 18%|█▊        | 865/4716 [06:01<26:30,  2.42it/s]

 18%|█▊        | 866/4716 [06:01<26:31,  2.42it/s]

 18%|█▊        | 867/4716 [06:02<26:29,  2.42it/s]

 18%|█▊        | 868/4716 [06:02<26:30,  2.42it/s]

 18%|█▊        | 869/4716 [06:02<26:29,  2.42it/s]

 18%|█▊        | 870/4716 [06:03<26:27,  2.42it/s]

 18%|█▊        | 871/4716 [06:03<26:27,  2.42it/s]

 18%|█▊        | 872/4716 [06:04<26:26,  2.42it/s]

 19%|█▊        | 873/4716 [06:04<26:27,  2.42it/s]

 19%|█▊        | 874/4716 [06:04<26:26,  2.42it/s]

 19%|█▊        | 875/4716 [06:05<26:28,  2.42it/s]

 19%|█▊        | 876/4716 [06:05<26:28,  2.42it/s]

 19%|█▊        | 877/4716 [06:06<26:29,  2.42it/s]

 19%|█▊        | 878/4716 [06:06<26:28,  2.42it/s]

 19%|█▊        | 879/4716 [06:06<26:26,  2.42it/s]

 19%|█▊        | 880/4716 [06:07<26:26,  2.42it/s]

 19%|█▊        | 881/4716 [06:07<26:26,  2.42it/s]

 19%|█▊        | 882/4716 [06:08<26:31,  2.41it/s]

 19%|█▊        | 883/4716 [06:08<26:29,  2.41it/s]

 19%|█▊        | 884/4716 [06:09<26:27,  2.41it/s]

 19%|█▉        | 885/4716 [06:09<26:26,  2.41it/s]

 19%|█▉        | 886/4716 [06:09<26:25,  2.42it/s]

 19%|█▉        | 887/4716 [06:10<26:25,  2.41it/s]

 19%|█▉        | 888/4716 [06:10<26:25,  2.41it/s]

 19%|█▉        | 889/4716 [06:11<26:25,  2.41it/s]

 19%|█▉        | 890/4716 [06:11<26:25,  2.41it/s]

 19%|█▉        | 891/4716 [06:11<26:25,  2.41it/s]

 19%|█▉        | 892/4716 [06:12<26:23,  2.42it/s]

 19%|█▉        | 893/4716 [06:12<26:22,  2.42it/s]

 19%|█▉        | 894/4716 [06:13<26:22,  2.41it/s]

 19%|█▉        | 895/4716 [06:13<26:21,  2.42it/s]

 19%|█▉        | 896/4716 [06:14<26:20,  2.42it/s]

 19%|█▉        | 897/4716 [06:14<26:22,  2.41it/s]

 19%|█▉        | 898/4716 [06:14<26:20,  2.42it/s]

 19%|█▉        | 899/4716 [06:15<26:18,  2.42it/s]

 19%|█▉        | 900/4716 [06:15<26:17,  2.42it/s]

 19%|█▉        | 901/4716 [06:16<26:18,  2.42it/s]

 19%|█▉        | 902/4716 [06:16<26:20,  2.41it/s]

 19%|█▉        | 903/4716 [06:16<26:18,  2.41it/s]

 19%|█▉        | 904/4716 [06:17<26:18,  2.41it/s]

 19%|█▉        | 905/4716 [06:17<26:19,  2.41it/s]

 19%|█▉        | 906/4716 [06:18<26:17,  2.41it/s]

 19%|█▉        | 907/4716 [06:18<26:18,  2.41it/s]

 19%|█▉        | 908/4716 [06:19<26:17,  2.41it/s]

 19%|█▉        | 909/4716 [06:19<26:17,  2.41it/s]

 19%|█▉        | 910/4716 [06:19<26:16,  2.41it/s]

 19%|█▉        | 911/4716 [06:20<26:15,  2.41it/s]

 19%|█▉        | 912/4716 [06:20<26:14,  2.42it/s]

 19%|█▉        | 913/4716 [06:21<26:14,  2.42it/s]

 19%|█▉        | 914/4716 [06:21<26:13,  2.42it/s]

 19%|█▉        | 915/4716 [06:21<26:12,  2.42it/s]

 19%|█▉        | 916/4716 [06:22<26:13,  2.42it/s]

 19%|█▉        | 917/4716 [06:22<26:14,  2.41it/s]

 19%|█▉        | 918/4716 [06:23<26:13,  2.41it/s]

 19%|█▉        | 919/4716 [06:23<26:13,  2.41it/s]

 20%|█▉        | 920/4716 [06:23<26:12,  2.41it/s]

 20%|█▉        | 921/4716 [06:24<26:12,  2.41it/s]

 20%|█▉        | 922/4716 [06:24<26:13,  2.41it/s]

 20%|█▉        | 923/4716 [06:25<26:11,  2.41it/s]

 20%|█▉        | 924/4716 [06:25<26:11,  2.41it/s]

 20%|█▉        | 925/4716 [06:26<26:11,  2.41it/s]

 20%|█▉        | 926/4716 [06:26<26:10,  2.41it/s]

 20%|█▉        | 927/4716 [06:26<26:09,  2.41it/s]

 20%|█▉        | 928/4716 [06:27<26:10,  2.41it/s]

 20%|█▉        | 929/4716 [06:27<26:09,  2.41it/s]

 20%|█▉        | 930/4716 [06:28<26:10,  2.41it/s]

 20%|█▉        | 931/4716 [06:28<26:13,  2.41it/s]

 20%|█▉        | 932/4716 [06:28<26:10,  2.41it/s]

 20%|█▉        | 933/4716 [06:29<26:08,  2.41it/s]

 20%|█▉        | 934/4716 [06:29<26:06,  2.41it/s]

 20%|█▉        | 935/4716 [06:30<26:06,  2.41it/s]

 20%|█▉        | 936/4716 [06:30<26:04,  2.42it/s]

 20%|█▉        | 937/4716 [06:31<26:06,  2.41it/s]

 20%|█▉        | 938/4716 [06:31<26:06,  2.41it/s]

 20%|█▉        | 939/4716 [06:31<26:05,  2.41it/s]

 20%|█▉        | 940/4716 [06:32<26:05,  2.41it/s]

 20%|█▉        | 941/4716 [06:32<26:06,  2.41it/s]

 20%|█▉        | 942/4716 [06:33<26:08,  2.41it/s]

 20%|█▉        | 943/4716 [06:33<26:07,  2.41it/s]

 20%|██        | 944/4716 [06:33<26:06,  2.41it/s]

 20%|██        | 945/4716 [06:34<26:05,  2.41it/s]

 20%|██        | 946/4716 [06:34<26:03,  2.41it/s]

 20%|██        | 947/4716 [06:35<26:04,  2.41it/s]

 20%|██        | 948/4716 [06:35<26:04,  2.41it/s]

 20%|██        | 949/4716 [06:36<26:02,  2.41it/s]

 20%|██        | 950/4716 [06:36<26:03,  2.41it/s]

 20%|██        | 951/4716 [06:36<26:02,  2.41it/s]

 20%|██        | 952/4716 [06:37<26:03,  2.41it/s]

 20%|██        | 953/4716 [06:37<26:01,  2.41it/s]

 20%|██        | 954/4716 [06:38<26:00,  2.41it/s]

 20%|██        | 955/4716 [06:38<25:59,  2.41it/s]

 20%|██        | 956/4716 [06:38<26:00,  2.41it/s]

 20%|██        | 957/4716 [06:39<26:00,  2.41it/s]

 20%|██        | 958/4716 [06:39<26:00,  2.41it/s]

 20%|██        | 959/4716 [06:40<25:59,  2.41it/s]

 20%|██        | 960/4716 [06:40<25:57,  2.41it/s]

 20%|██        | 961/4716 [06:40<25:58,  2.41it/s]

 20%|██        | 962/4716 [06:41<25:57,  2.41it/s]

 20%|██        | 963/4716 [06:41<25:57,  2.41it/s]

 20%|██        | 964/4716 [06:42<25:55,  2.41it/s]

 20%|██        | 965/4716 [06:42<25:55,  2.41it/s]

 20%|██        | 966/4716 [06:43<25:53,  2.41it/s]

 21%|██        | 967/4716 [06:43<25:54,  2.41it/s]

 21%|██        | 968/4716 [06:43<25:56,  2.41it/s]

 21%|██        | 969/4716 [06:44<25:55,  2.41it/s]

 21%|██        | 970/4716 [06:44<25:56,  2.41it/s]

 21%|██        | 971/4716 [06:45<25:54,  2.41it/s]

 21%|██        | 972/4716 [06:45<25:53,  2.41it/s]

 21%|██        | 973/4716 [06:45<25:52,  2.41it/s]

 21%|██        | 974/4716 [06:46<25:52,  2.41it/s]

 21%|██        | 975/4716 [06:46<25:50,  2.41it/s]

 21%|██        | 976/4716 [06:47<25:52,  2.41it/s]

 21%|██        | 977/4716 [06:47<25:51,  2.41it/s]

 21%|██        | 978/4716 [06:48<25:53,  2.41it/s]

 21%|██        | 979/4716 [06:48<25:52,  2.41it/s]

 21%|██        | 980/4716 [06:48<25:51,  2.41it/s]

 21%|██        | 981/4716 [06:49<25:51,  2.41it/s]

 21%|██        | 982/4716 [06:49<25:52,  2.41it/s]

 21%|██        | 983/4716 [06:50<25:52,  2.40it/s]

 21%|██        | 984/4716 [06:50<25:50,  2.41it/s]

 21%|██        | 985/4716 [06:50<25:52,  2.40it/s]

 21%|██        | 986/4716 [06:51<25:51,  2.40it/s]

 21%|██        | 987/4716 [06:51<25:49,  2.41it/s]

 21%|██        | 988/4716 [06:52<25:50,  2.40it/s]

 21%|██        | 989/4716 [06:52<25:50,  2.40it/s]

 21%|██        | 990/4716 [06:53<25:48,  2.41it/s]

 21%|██        | 991/4716 [06:53<25:49,  2.40it/s]

 21%|██        | 992/4716 [06:53<25:47,  2.41it/s]

 21%|██        | 993/4716 [06:54<25:46,  2.41it/s]

 21%|██        | 994/4716 [06:54<25:44,  2.41it/s]

 21%|██        | 995/4716 [06:55<25:45,  2.41it/s]

 21%|██        | 996/4716 [06:55<25:44,  2.41it/s]

 21%|██        | 997/4716 [06:55<25:43,  2.41it/s]

 21%|██        | 998/4716 [06:56<25:43,  2.41it/s]

 21%|██        | 999/4716 [06:56<25:45,  2.40it/s]

 21%|██        | 1000/4716 [06:57<25:44,  2.41it/s]

 21%|██        | 1001/4716 [06:57<25:44,  2.41it/s]

 21%|██        | 1002/4716 [06:58<25:43,  2.41it/s]

 21%|██▏       | 1003/4716 [06:58<25:44,  2.40it/s]

 21%|██▏       | 1004/4716 [06:58<25:42,  2.41it/s]

 21%|██▏       | 1005/4716 [06:59<25:41,  2.41it/s]

 21%|██▏       | 1006/4716 [06:59<25:42,  2.41it/s]

 21%|██▏       | 1007/4716 [07:00<25:41,  2.41it/s]

 21%|██▏       | 1008/4716 [07:00<25:41,  2.41it/s]

 21%|██▏       | 1009/4716 [07:00<25:40,  2.41it/s]

 21%|██▏       | 1010/4716 [07:01<25:38,  2.41it/s]

 21%|██▏       | 1011/4716 [07:01<25:38,  2.41it/s]

 21%|██▏       | 1012/4716 [07:02<25:39,  2.41it/s]

 21%|██▏       | 1013/4716 [07:02<25:38,  2.41it/s]

 22%|██▏       | 1014/4716 [07:03<25:38,  2.41it/s]

 22%|██▏       | 1015/4716 [07:03<25:37,  2.41it/s]

 22%|██▏       | 1016/4716 [07:03<25:38,  2.40it/s]

 22%|██▏       | 1017/4716 [07:04<25:37,  2.41it/s]

 22%|██▏       | 1018/4716 [07:04<25:35,  2.41it/s]

 22%|██▏       | 1019/4716 [07:05<25:34,  2.41it/s]

 22%|██▏       | 1020/4716 [07:05<25:33,  2.41it/s]

 22%|██▏       | 1021/4716 [07:05<25:32,  2.41it/s]

 22%|██▏       | 1022/4716 [07:06<25:35,  2.41it/s]

 22%|██▏       | 1023/4716 [07:06<25:36,  2.40it/s]

 22%|██▏       | 1024/4716 [07:07<25:34,  2.41it/s]

 22%|██▏       | 1025/4716 [07:07<25:34,  2.41it/s]

 22%|██▏       | 1026/4716 [07:07<25:33,  2.41it/s]

 22%|██▏       | 1027/4716 [07:08<25:35,  2.40it/s]

 22%|██▏       | 1028/4716 [07:08<25:31,  2.41it/s]

 22%|██▏       | 1029/4716 [07:09<25:32,  2.41it/s]

 22%|██▏       | 1030/4716 [07:09<25:30,  2.41it/s]

 22%|██▏       | 1031/4716 [07:10<25:31,  2.41it/s]

 22%|██▏       | 1032/4716 [07:10<25:30,  2.41it/s]

 22%|██▏       | 1033/4716 [07:10<25:31,  2.40it/s]

 22%|██▏       | 1034/4716 [07:11<25:30,  2.41it/s]

 22%|██▏       | 1035/4716 [07:11<25:31,  2.40it/s]

 22%|██▏       | 1036/4716 [07:12<25:29,  2.41it/s]

 22%|██▏       | 1037/4716 [07:12<25:30,  2.40it/s]

 22%|██▏       | 1038/4716 [07:12<25:28,  2.41it/s]

 22%|██▏       | 1039/4716 [07:13<25:28,  2.41it/s]

 22%|██▏       | 1040/4716 [07:13<25:27,  2.41it/s]

 22%|██▏       | 1041/4716 [07:14<25:26,  2.41it/s]

 22%|██▏       | 1042/4716 [07:14<25:26,  2.41it/s]

 22%|██▏       | 1043/4716 [07:15<25:25,  2.41it/s]

 22%|██▏       | 1044/4716 [07:15<25:24,  2.41it/s]

 22%|██▏       | 1045/4716 [07:15<25:24,  2.41it/s]

 22%|██▏       | 1046/4716 [07:16<25:26,  2.40it/s]

 22%|██▏       | 1047/4716 [07:16<25:24,  2.41it/s]

 22%|██▏       | 1048/4716 [07:17<25:24,  2.41it/s]

 22%|██▏       | 1049/4716 [07:17<25:27,  2.40it/s]

 22%|██▏       | 1050/4716 [07:17<25:26,  2.40it/s]

 22%|██▏       | 1051/4716 [07:18<25:24,  2.40it/s]

 22%|██▏       | 1052/4716 [07:18<25:21,  2.41it/s]

 22%|██▏       | 1053/4716 [07:19<25:20,  2.41it/s]

 22%|██▏       | 1054/4716 [07:19<25:20,  2.41it/s]

 22%|██▏       | 1055/4716 [07:20<25:22,  2.40it/s]

 22%|██▏       | 1056/4716 [07:20<25:23,  2.40it/s]

 22%|██▏       | 1057/4716 [07:20<25:21,  2.40it/s]

 22%|██▏       | 1058/4716 [07:21<25:25,  2.40it/s]

 22%|██▏       | 1059/4716 [07:21<25:23,  2.40it/s]

 22%|██▏       | 1060/4716 [07:22<25:22,  2.40it/s]

 22%|██▏       | 1061/4716 [07:22<25:20,  2.40it/s]

 23%|██▎       | 1062/4716 [07:22<25:20,  2.40it/s]

 23%|██▎       | 1063/4716 [07:23<25:17,  2.41it/s]

 23%|██▎       | 1064/4716 [07:23<25:18,  2.40it/s]

 23%|██▎       | 1065/4716 [07:24<25:16,  2.41it/s]

 23%|██▎       | 1066/4716 [07:24<25:16,  2.41it/s]

 23%|██▎       | 1067/4716 [07:25<25:16,  2.41it/s]

 23%|██▎       | 1068/4716 [07:25<25:15,  2.41it/s]

 23%|██▎       | 1069/4716 [07:25<25:14,  2.41it/s]

 23%|██▎       | 1070/4716 [07:26<25:16,  2.40it/s]

 23%|██▎       | 1071/4716 [07:26<25:14,  2.41it/s]

 23%|██▎       | 1072/4716 [07:27<25:16,  2.40it/s]

 23%|██▎       | 1073/4716 [07:27<25:16,  2.40it/s]

 23%|██▎       | 1074/4716 [07:27<25:15,  2.40it/s]

 23%|██▎       | 1075/4716 [07:28<25:13,  2.41it/s]

 23%|██▎       | 1076/4716 [07:28<25:13,  2.41it/s]

 23%|██▎       | 1077/4716 [07:29<25:15,  2.40it/s]

 23%|██▎       | 1078/4716 [07:29<25:14,  2.40it/s]

 23%|██▎       | 1079/4716 [07:30<25:13,  2.40it/s]

 23%|██▎       | 1080/4716 [07:30<25:12,  2.40it/s]

 23%|██▎       | 1081/4716 [07:30<25:12,  2.40it/s]

 23%|██▎       | 1082/4716 [07:31<25:11,  2.40it/s]

 23%|██▎       | 1083/4716 [07:31<25:14,  2.40it/s]

 23%|██▎       | 1084/4716 [07:32<25:13,  2.40it/s]

 23%|██▎       | 1085/4716 [07:32<25:12,  2.40it/s]

 23%|██▎       | 1086/4716 [07:32<25:11,  2.40it/s]

 23%|██▎       | 1087/4716 [07:33<25:14,  2.40it/s]

 23%|██▎       | 1088/4716 [07:33<25:12,  2.40it/s]

 23%|██▎       | 1089/4716 [07:34<25:10,  2.40it/s]

 23%|██▎       | 1090/4716 [07:34<25:10,  2.40it/s]

 23%|██▎       | 1091/4716 [07:35<25:09,  2.40it/s]

 23%|██▎       | 1092/4716 [07:35<25:07,  2.40it/s]

 23%|██▎       | 1093/4716 [07:35<25:07,  2.40it/s]

 23%|██▎       | 1094/4716 [07:36<25:07,  2.40it/s]

 23%|██▎       | 1095/4716 [07:36<25:08,  2.40it/s]

 23%|██▎       | 1096/4716 [07:37<25:06,  2.40it/s]

 23%|██▎       | 1097/4716 [07:37<25:06,  2.40it/s]

 23%|██▎       | 1098/4716 [07:37<25:06,  2.40it/s]

 23%|██▎       | 1099/4716 [07:38<25:07,  2.40it/s]

 23%|██▎       | 1100/4716 [07:38<25:06,  2.40it/s]

 23%|██▎       | 1101/4716 [07:39<25:08,  2.40it/s]

 23%|██▎       | 1102/4716 [07:39<25:06,  2.40it/s]

 23%|██▎       | 1103/4716 [07:40<25:05,  2.40it/s]

 23%|██▎       | 1104/4716 [07:40<25:04,  2.40it/s]

 23%|██▎       | 1105/4716 [07:40<25:05,  2.40it/s]

 23%|██▎       | 1106/4716 [07:41<25:05,  2.40it/s]

 23%|██▎       | 1107/4716 [07:41<25:05,  2.40it/s]

 23%|██▎       | 1108/4716 [07:42<25:05,  2.40it/s]

 24%|██▎       | 1109/4716 [07:42<25:03,  2.40it/s]

 24%|██▎       | 1110/4716 [07:42<25:03,  2.40it/s]

 24%|██▎       | 1111/4716 [07:43<25:02,  2.40it/s]

 24%|██▎       | 1112/4716 [07:43<25:02,  2.40it/s]

 24%|██▎       | 1113/4716 [07:44<25:00,  2.40it/s]

 24%|██▎       | 1114/4716 [07:44<24:59,  2.40it/s]

 24%|██▎       | 1115/4716 [07:45<25:00,  2.40it/s]

 24%|██▎       | 1116/4716 [07:45<25:00,  2.40it/s]

 24%|██▎       | 1117/4716 [07:45<24:58,  2.40it/s]

 24%|██▎       | 1118/4716 [07:46<24:59,  2.40it/s]

 24%|██▎       | 1119/4716 [07:46<24:59,  2.40it/s]

 24%|██▎       | 1120/4716 [07:47<24:58,  2.40it/s]

 24%|██▍       | 1121/4716 [07:47<24:59,  2.40it/s]

 24%|██▍       | 1122/4716 [07:47<24:58,  2.40it/s]

 24%|██▍       | 1123/4716 [07:48<24:58,  2.40it/s]

 24%|██▍       | 1124/4716 [07:48<24:57,  2.40it/s]

 24%|██▍       | 1125/4716 [07:49<24:59,  2.40it/s]

 24%|██▍       | 1126/4716 [07:49<24:58,  2.40it/s]

 24%|██▍       | 1127/4716 [07:50<24:58,  2.39it/s]

 24%|██▍       | 1128/4716 [07:50<24:56,  2.40it/s]

 24%|██▍       | 1129/4716 [07:50<24:57,  2.40it/s]

 24%|██▍       | 1130/4716 [07:51<24:55,  2.40it/s]

 24%|██▍       | 1131/4716 [07:51<24:55,  2.40it/s]

 24%|██▍       | 1132/4716 [07:52<24:54,  2.40it/s]

 24%|██▍       | 1133/4716 [07:52<24:52,  2.40it/s]

 24%|██▍       | 1134/4716 [07:52<24:52,  2.40it/s]

 24%|██▍       | 1135/4716 [07:53<24:52,  2.40it/s]

 24%|██▍       | 1136/4716 [07:53<24:51,  2.40it/s]

 24%|██▍       | 1137/4716 [07:54<24:52,  2.40it/s]

 24%|██▍       | 1138/4716 [07:54<24:49,  2.40it/s]

 24%|██▍       | 1139/4716 [07:55<24:48,  2.40it/s]

 24%|██▍       | 1140/4716 [07:55<24:48,  2.40it/s]

 24%|██▍       | 1141/4716 [07:55<24:49,  2.40it/s]

 24%|██▍       | 1142/4716 [07:56<24:48,  2.40it/s]

 24%|██▍       | 1143/4716 [07:56<24:48,  2.40it/s]

 24%|██▍       | 1144/4716 [07:57<24:52,  2.39it/s]

 24%|██▍       | 1145/4716 [07:57<24:50,  2.40it/s]

 24%|██▍       | 1146/4716 [07:57<24:48,  2.40it/s]

 24%|██▍       | 1147/4716 [07:58<24:47,  2.40it/s]

 24%|██▍       | 1148/4716 [07:58<24:47,  2.40it/s]

 24%|██▍       | 1149/4716 [07:59<24:47,  2.40it/s]

 24%|██▍       | 1150/4716 [07:59<24:47,  2.40it/s]

 24%|██▍       | 1151/4716 [08:00<24:45,  2.40it/s]

 24%|██▍       | 1152/4716 [08:00<24:45,  2.40it/s]

 24%|██▍       | 1153/4716 [08:00<24:43,  2.40it/s]

 24%|██▍       | 1154/4716 [08:01<24:44,  2.40it/s]

 24%|██▍       | 1155/4716 [08:01<24:43,  2.40it/s]

 25%|██▍       | 1156/4716 [08:02<24:44,  2.40it/s]

 25%|██▍       | 1157/4716 [08:02<24:43,  2.40it/s]

 25%|██▍       | 1158/4716 [08:02<24:45,  2.40it/s]

 25%|██▍       | 1159/4716 [08:03<24:44,  2.40it/s]

 25%|██▍       | 1160/4716 [08:03<24:43,  2.40it/s]

 25%|██▍       | 1161/4716 [08:04<24:41,  2.40it/s]

 25%|██▍       | 1162/4716 [08:04<24:43,  2.40it/s]

 25%|██▍       | 1163/4716 [08:05<24:40,  2.40it/s]

 25%|██▍       | 1164/4716 [08:05<24:41,  2.40it/s]

 25%|██▍       | 1165/4716 [08:05<24:43,  2.39it/s]

 25%|██▍       | 1166/4716 [08:06<24:42,  2.39it/s]

 25%|██▍       | 1167/4716 [08:06<24:41,  2.40it/s]

 25%|██▍       | 1168/4716 [08:07<24:43,  2.39it/s]

 25%|██▍       | 1169/4716 [08:07<24:41,  2.39it/s]

 25%|██▍       | 1170/4716 [08:07<24:41,  2.39it/s]

 25%|██▍       | 1171/4716 [08:08<24:37,  2.40it/s]

 25%|██▍       | 1172/4716 [08:08<24:37,  2.40it/s]

 25%|██▍       | 1173/4716 [08:09<24:36,  2.40it/s]

 25%|██▍       | 1174/4716 [08:09<24:35,  2.40it/s]

 25%|██▍       | 1175/4716 [08:10<24:37,  2.40it/s]

 25%|██▍       | 1176/4716 [08:10<24:40,  2.39it/s]

 25%|██▍       | 1177/4716 [08:10<24:39,  2.39it/s]

 25%|██▍       | 1178/4716 [08:11<24:36,  2.40it/s]

 25%|██▌       | 1179/4716 [08:11<24:36,  2.40it/s]

 25%|██▌       | 1180/4716 [08:12<24:37,  2.39it/s]

 25%|██▌       | 1181/4716 [08:12<24:37,  2.39it/s]

 25%|██▌       | 1182/4716 [08:12<24:36,  2.39it/s]

 25%|██▌       | 1183/4716 [08:13<24:35,  2.40it/s]

 25%|██▌       | 1184/4716 [08:13<24:33,  2.40it/s]

 25%|██▌       | 1185/4716 [08:14<24:33,  2.40it/s]

 25%|██▌       | 1186/4716 [08:14<24:32,  2.40it/s]

 25%|██▌       | 1187/4716 [08:15<24:33,  2.39it/s]

 25%|██▌       | 1188/4716 [08:15<24:33,  2.39it/s]

 25%|██▌       | 1189/4716 [08:15<24:35,  2.39it/s]

 25%|██▌       | 1190/4716 [08:16<24:33,  2.39it/s]

 25%|██▌       | 1191/4716 [08:16<24:35,  2.39it/s]

 25%|██▌       | 1192/4716 [08:17<24:32,  2.39it/s]

 25%|██▌       | 1193/4716 [08:17<24:30,  2.40it/s]

 25%|██▌       | 1194/4716 [08:17<24:29,  2.40it/s]

 25%|██▌       | 1195/4716 [08:18<24:30,  2.40it/s]

 25%|██▌       | 1196/4716 [08:18<24:26,  2.40it/s]

 25%|██▌       | 1197/4716 [08:19<24:29,  2.40it/s]

 25%|██▌       | 1198/4716 [08:19<24:28,  2.40it/s]

 25%|██▌       | 1199/4716 [08:20<24:27,  2.40it/s]

 25%|██▌       | 1200/4716 [08:20<24:27,  2.40it/s]

 25%|██▌       | 1201/4716 [08:20<24:28,  2.39it/s]

 25%|██▌       | 1202/4716 [08:21<24:28,  2.39it/s]

 26%|██▌       | 1203/4716 [08:21<24:30,  2.39it/s]

 26%|██▌       | 1204/4716 [08:22<24:28,  2.39it/s]

 26%|██▌       | 1205/4716 [08:22<24:29,  2.39it/s]

 26%|██▌       | 1206/4716 [08:23<24:29,  2.39it/s]

 26%|██▌       | 1207/4716 [08:23<24:27,  2.39it/s]

 26%|██▌       | 1208/4716 [08:23<24:26,  2.39it/s]

 26%|██▌       | 1209/4716 [08:24<24:28,  2.39it/s]

 26%|██▌       | 1210/4716 [08:24<24:30,  2.38it/s]

 26%|██▌       | 1211/4716 [08:25<24:28,  2.39it/s]

 26%|██▌       | 1212/4716 [08:25<24:27,  2.39it/s]

 26%|██▌       | 1213/4716 [08:25<24:25,  2.39it/s]

 26%|██▌       | 1214/4716 [08:26<24:23,  2.39it/s]

 26%|██▌       | 1215/4716 [08:26<24:24,  2.39it/s]

 26%|██▌       | 1216/4716 [08:27<24:25,  2.39it/s]

 26%|██▌       | 1217/4716 [08:27<24:24,  2.39it/s]

 26%|██▌       | 1218/4716 [08:28<24:20,  2.39it/s]

 26%|██▌       | 1219/4716 [08:28<24:22,  2.39it/s]

 26%|██▌       | 1220/4716 [08:28<24:23,  2.39it/s]

 26%|██▌       | 1221/4716 [08:29<24:22,  2.39it/s]

 26%|██▌       | 1222/4716 [08:29<24:20,  2.39it/s]

 26%|██▌       | 1223/4716 [08:30<24:21,  2.39it/s]

 26%|██▌       | 1224/4716 [08:30<24:22,  2.39it/s]

 26%|██▌       | 1225/4716 [08:30<24:21,  2.39it/s]

 26%|██▌       | 1226/4716 [08:31<24:18,  2.39it/s]

 26%|██▌       | 1227/4716 [08:31<24:19,  2.39it/s]

 26%|██▌       | 1228/4716 [08:32<24:19,  2.39it/s]

 26%|██▌       | 1229/4716 [08:32<24:19,  2.39it/s]

 26%|██▌       | 1230/4716 [08:33<24:18,  2.39it/s]

 26%|██▌       | 1231/4716 [08:33<24:18,  2.39it/s]

 26%|██▌       | 1232/4716 [08:33<24:17,  2.39it/s]

 26%|██▌       | 1233/4716 [08:34<24:15,  2.39it/s]

 26%|██▌       | 1234/4716 [08:34<24:15,  2.39it/s]

 26%|██▌       | 1235/4716 [08:35<24:16,  2.39it/s]

 26%|██▌       | 1236/4716 [08:35<24:15,  2.39it/s]

 26%|██▌       | 1237/4716 [08:35<24:15,  2.39it/s]

 26%|██▋       | 1238/4716 [08:36<24:14,  2.39it/s]

 26%|██▋       | 1239/4716 [08:36<24:13,  2.39it/s]

 26%|██▋       | 1240/4716 [08:37<24:11,  2.39it/s]

 26%|██▋       | 1241/4716 [08:37<24:12,  2.39it/s]

 26%|██▋       | 1242/4716 [08:38<24:12,  2.39it/s]

 26%|██▋       | 1243/4716 [08:38<24:12,  2.39it/s]

 26%|██▋       | 1244/4716 [08:38<24:10,  2.39it/s]

 26%|██▋       | 1245/4716 [08:39<24:10,  2.39it/s]

 26%|██▋       | 1246/4716 [08:39<24:09,  2.39it/s]

 26%|██▋       | 1247/4716 [08:40<24:10,  2.39it/s]

 26%|██▋       | 1248/4716 [08:40<24:11,  2.39it/s]

 26%|██▋       | 1249/4716 [08:40<24:11,  2.39it/s]

 27%|██▋       | 1250/4716 [08:41<24:10,  2.39it/s]

 27%|██▋       | 1251/4716 [08:41<24:10,  2.39it/s]

logging
logging the anndata

 27%|██▋       | 1252/4716 [08:42<24:50,  2.32it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 27%|██▋       | 1253/4716 [08:42<24:33,  2.35it/s]

 27%|██▋       | 1254/4716 [08:43<24:20,  2.37it/s]

 27%|██▋       | 1255/4716 [08:43<24:11,  2.39it/s]

 27%|██▋       | 1256/4716 [08:43<24:02,  2.40it/s]

 27%|██▋       | 1257/4716 [08:44<23:56,  2.41it/s]

 27%|██▋       | 1258/4716 [08:44<23:51,  2.42it/s]

 27%|██▋       | 1259/4716 [08:45<23:49,  2.42it/s]

 27%|██▋       | 1260/4716 [08:45<23:46,  2.42it/s]

 27%|██▋       | 1261/4716 [08:45<23:44,  2.42it/s]

 27%|██▋       | 1262/4716 [08:46<23:44,  2.42it/s]

 27%|██▋       | 1263/4716 [08:46<23:44,  2.42it/s]

 27%|██▋       | 1264/4716 [08:47<23:43,  2.42it/s]

 27%|██▋       | 1265/4716 [08:47<23:43,  2.42it/s]

 27%|██▋       | 1266/4716 [08:48<23:43,  2.42it/s]

 27%|██▋       | 1267/4716 [08:48<23:41,  2.43it/s]

 27%|██▋       | 1268/4716 [08:48<23:40,  2.43it/s]

 27%|██▋       | 1269/4716 [08:49<23:40,  2.43it/s]

 27%|██▋       | 1270/4716 [08:49<23:40,  2.43it/s]

 27%|██▋       | 1271/4716 [08:50<23:40,  2.43it/s]

 27%|██▋       | 1272/4716 [08:50<23:39,  2.43it/s]

 27%|██▋       | 1273/4716 [08:50<23:41,  2.42it/s]

 27%|██▋       | 1274/4716 [08:51<23:39,  2.43it/s]

 27%|██▋       | 1275/4716 [08:51<23:39,  2.42it/s]

 27%|██▋       | 1276/4716 [08:52<23:49,  2.41it/s]

 27%|██▋       | 1277/4716 [08:52<23:44,  2.41it/s]

 27%|██▋       | 1278/4716 [08:53<23:41,  2.42it/s]

 27%|██▋       | 1279/4716 [08:53<23:39,  2.42it/s]

 27%|██▋       | 1280/4716 [08:53<23:39,  2.42it/s]

 27%|██▋       | 1281/4716 [08:54<23:38,  2.42it/s]

 27%|██▋       | 1282/4716 [08:54<23:37,  2.42it/s]

 27%|██▋       | 1283/4716 [08:55<23:34,  2.43it/s]

 27%|██▋       | 1284/4716 [08:55<23:34,  2.43it/s]

 27%|██▋       | 1285/4716 [08:55<23:33,  2.43it/s]

 27%|██▋       | 1286/4716 [08:56<23:32,  2.43it/s]

 27%|██▋       | 1287/4716 [08:56<23:33,  2.43it/s]

 27%|██▋       | 1288/4716 [08:57<23:32,  2.43it/s]

 27%|██▋       | 1289/4716 [08:57<23:32,  2.43it/s]

 27%|██▋       | 1290/4716 [08:57<23:30,  2.43it/s]

 27%|██▋       | 1291/4716 [08:58<23:31,  2.43it/s]

 27%|██▋       | 1292/4716 [08:58<23:30,  2.43it/s]

 27%|██▋       | 1293/4716 [08:59<23:29,  2.43it/s]

 27%|██▋       | 1294/4716 [08:59<23:30,  2.43it/s]

 27%|██▋       | 1295/4716 [09:00<23:31,  2.42it/s]

 27%|██▋       | 1296/4716 [09:00<23:29,  2.43it/s]

 28%|██▊       | 1297/4716 [09:00<23:29,  2.43it/s]

 28%|██▊       | 1298/4716 [09:01<23:29,  2.43it/s]

 28%|██▊       | 1299/4716 [09:01<23:29,  2.42it/s]

 28%|██▊       | 1300/4716 [09:02<23:31,  2.42it/s]

 28%|██▊       | 1301/4716 [09:02<23:29,  2.42it/s]

 28%|██▊       | 1302/4716 [09:02<23:30,  2.42it/s]

 28%|██▊       | 1303/4716 [09:03<23:28,  2.42it/s]

 28%|██▊       | 1304/4716 [09:03<23:28,  2.42it/s]

 28%|██▊       | 1305/4716 [09:04<23:30,  2.42it/s]

 28%|██▊       | 1306/4716 [09:04<23:30,  2.42it/s]

 28%|██▊       | 1307/4716 [09:04<23:28,  2.42it/s]

 28%|██▊       | 1308/4716 [09:05<23:26,  2.42it/s]

 28%|██▊       | 1309/4716 [09:05<23:26,  2.42it/s]

 28%|██▊       | 1310/4716 [09:06<23:25,  2.42it/s]

 28%|██▊       | 1311/4716 [09:06<23:25,  2.42it/s]

 28%|██▊       | 1312/4716 [09:07<23:25,  2.42it/s]

 28%|██▊       | 1313/4716 [09:07<23:23,  2.43it/s]

 28%|██▊       | 1314/4716 [09:07<23:22,  2.43it/s]

 28%|██▊       | 1315/4716 [09:08<23:23,  2.42it/s]

 28%|██▊       | 1316/4716 [09:08<23:22,  2.42it/s]

 28%|██▊       | 1317/4716 [09:09<23:23,  2.42it/s]

 28%|██▊       | 1318/4716 [09:09<23:22,  2.42it/s]

 28%|██▊       | 1319/4716 [09:09<23:22,  2.42it/s]

 28%|██▊       | 1320/4716 [09:10<23:22,  2.42it/s]

 28%|██▊       | 1321/4716 [09:10<23:21,  2.42it/s]

 28%|██▊       | 1322/4716 [09:11<23:21,  2.42it/s]

 28%|██▊       | 1323/4716 [09:11<23:20,  2.42it/s]

 28%|██▊       | 1324/4716 [09:11<23:19,  2.42it/s]

 28%|██▊       | 1325/4716 [09:12<23:19,  2.42it/s]

 28%|██▊       | 1326/4716 [09:12<23:20,  2.42it/s]

 28%|██▊       | 1327/4716 [09:13<23:18,  2.42it/s]

 28%|██▊       | 1328/4716 [09:13<23:20,  2.42it/s]

 28%|██▊       | 1329/4716 [09:14<23:20,  2.42it/s]

 28%|██▊       | 1330/4716 [09:14<23:19,  2.42it/s]

 28%|██▊       | 1331/4716 [09:14<23:18,  2.42it/s]

 28%|██▊       | 1332/4716 [09:15<23:17,  2.42it/s]

 28%|██▊       | 1333/4716 [09:15<23:16,  2.42it/s]

 28%|██▊       | 1334/4716 [09:16<23:15,  2.42it/s]

 28%|██▊       | 1335/4716 [09:16<23:19,  2.42it/s]

 28%|██▊       | 1336/4716 [09:16<23:17,  2.42it/s]

 28%|██▊       | 1337/4716 [09:17<23:17,  2.42it/s]

 28%|██▊       | 1338/4716 [09:17<23:16,  2.42it/s]

 28%|██▊       | 1339/4716 [09:18<23:14,  2.42it/s]

 28%|██▊       | 1340/4716 [09:18<23:14,  2.42it/s]

 28%|██▊       | 1341/4716 [09:19<23:14,  2.42it/s]

 28%|██▊       | 1342/4716 [09:19<23:15,  2.42it/s]

 28%|██▊       | 1343/4716 [09:19<23:14,  2.42it/s]

 28%|██▊       | 1344/4716 [09:20<23:13,  2.42it/s]

 29%|██▊       | 1345/4716 [09:20<23:14,  2.42it/s]

 29%|██▊       | 1346/4716 [09:21<23:13,  2.42it/s]

 29%|██▊       | 1347/4716 [09:21<23:12,  2.42it/s]

 29%|██▊       | 1348/4716 [09:21<23:12,  2.42it/s]

 29%|██▊       | 1349/4716 [09:22<23:11,  2.42it/s]

 29%|██▊       | 1350/4716 [09:22<23:20,  2.40it/s]

 29%|██▊       | 1351/4716 [09:23<23:15,  2.41it/s]

 29%|██▊       | 1352/4716 [09:23<23:13,  2.41it/s]

 29%|██▊       | 1353/4716 [09:23<23:12,  2.42it/s]

 29%|██▊       | 1354/4716 [09:24<23:11,  2.42it/s]

 29%|██▊       | 1355/4716 [09:24<23:10,  2.42it/s]

 29%|██▉       | 1356/4716 [09:25<23:09,  2.42it/s]

 29%|██▉       | 1357/4716 [09:25<23:07,  2.42it/s]

 29%|██▉       | 1358/4716 [09:26<23:08,  2.42it/s]

 29%|██▉       | 1359/4716 [09:26<23:06,  2.42it/s]

 29%|██▉       | 1360/4716 [09:26<23:07,  2.42it/s]

 29%|██▉       | 1361/4716 [09:27<23:06,  2.42it/s]

 29%|██▉       | 1362/4716 [09:27<23:07,  2.42it/s]

 29%|██▉       | 1363/4716 [09:28<23:06,  2.42it/s]

 29%|██▉       | 1364/4716 [09:28<23:05,  2.42it/s]

 29%|██▉       | 1365/4716 [09:28<23:06,  2.42it/s]

 29%|██▉       | 1366/4716 [09:29<23:05,  2.42it/s]

 29%|██▉       | 1367/4716 [09:29<23:03,  2.42it/s]

 29%|██▉       | 1368/4716 [09:30<23:02,  2.42it/s]

 29%|██▉       | 1369/4716 [09:30<23:03,  2.42it/s]

 29%|██▉       | 1370/4716 [09:31<23:01,  2.42it/s]

 29%|██▉       | 1371/4716 [09:31<23:02,  2.42it/s]

 29%|██▉       | 1372/4716 [09:31<23:01,  2.42it/s]

 29%|██▉       | 1373/4716 [09:32<23:00,  2.42it/s]

 29%|██▉       | 1374/4716 [09:32<22:59,  2.42it/s]

 29%|██▉       | 1375/4716 [09:33<23:00,  2.42it/s]

 29%|██▉       | 1376/4716 [09:33<22:59,  2.42it/s]

 29%|██▉       | 1377/4716 [09:33<23:00,  2.42it/s]

 29%|██▉       | 1378/4716 [09:34<22:59,  2.42it/s]

 29%|██▉       | 1379/4716 [09:34<22:58,  2.42it/s]

 29%|██▉       | 1380/4716 [09:35<22:58,  2.42it/s]

 29%|██▉       | 1381/4716 [09:35<22:57,  2.42it/s]

 29%|██▉       | 1382/4716 [09:35<22:56,  2.42it/s]

 29%|██▉       | 1383/4716 [09:36<22:55,  2.42it/s]

 29%|██▉       | 1384/4716 [09:36<22:55,  2.42it/s]

 29%|██▉       | 1385/4716 [09:37<22:55,  2.42it/s]

 29%|██▉       | 1386/4716 [09:37<22:54,  2.42it/s]

 29%|██▉       | 1387/4716 [09:38<22:54,  2.42it/s]

 29%|██▉       | 1388/4716 [09:38<22:53,  2.42it/s]

 29%|██▉       | 1389/4716 [09:38<22:54,  2.42it/s]

 29%|██▉       | 1390/4716 [09:39<22:51,  2.42it/s]

 29%|██▉       | 1391/4716 [09:39<22:52,  2.42it/s]

 30%|██▉       | 1392/4716 [09:40<22:51,  2.42it/s]

 30%|██▉       | 1393/4716 [09:40<22:50,  2.42it/s]

 30%|██▉       | 1394/4716 [09:40<22:51,  2.42it/s]

 30%|██▉       | 1395/4716 [09:41<22:52,  2.42it/s]

 30%|██▉       | 1396/4716 [09:41<22:50,  2.42it/s]

 30%|██▉       | 1397/4716 [09:42<22:50,  2.42it/s]

 30%|██▉       | 1398/4716 [09:42<22:48,  2.42it/s]

 30%|██▉       | 1399/4716 [09:42<22:48,  2.42it/s]

 30%|██▉       | 1400/4716 [09:43<22:47,  2.42it/s]

 30%|██▉       | 1401/4716 [09:43<22:49,  2.42it/s]

 30%|██▉       | 1402/4716 [09:44<22:50,  2.42it/s]

 30%|██▉       | 1403/4716 [09:44<22:50,  2.42it/s]

 30%|██▉       | 1404/4716 [09:45<22:55,  2.41it/s]

 30%|██▉       | 1405/4716 [09:45<22:54,  2.41it/s]

 30%|██▉       | 1406/4716 [09:45<22:50,  2.42it/s]

 30%|██▉       | 1407/4716 [09:46<22:49,  2.42it/s]

 30%|██▉       | 1408/4716 [09:46<22:47,  2.42it/s]

 30%|██▉       | 1409/4716 [09:47<22:45,  2.42it/s]

 30%|██▉       | 1410/4716 [09:47<22:45,  2.42it/s]

 30%|██▉       | 1411/4716 [09:47<22:44,  2.42it/s]

 30%|██▉       | 1412/4716 [09:48<22:47,  2.42it/s]

 30%|██▉       | 1413/4716 [09:48<22:44,  2.42it/s]

 30%|██▉       | 1414/4716 [09:49<22:43,  2.42it/s]

 30%|███       | 1415/4716 [09:49<22:44,  2.42it/s]

 30%|███       | 1416/4716 [09:50<22:43,  2.42it/s]

 30%|███       | 1417/4716 [09:50<22:43,  2.42it/s]

 30%|███       | 1418/4716 [09:50<22:42,  2.42it/s]

 30%|███       | 1419/4716 [09:51<22:41,  2.42it/s]

 30%|███       | 1420/4716 [09:51<22:40,  2.42it/s]

 30%|███       | 1421/4716 [09:52<22:41,  2.42it/s]

 30%|███       | 1422/4716 [09:52<22:40,  2.42it/s]

 30%|███       | 1423/4716 [09:52<22:40,  2.42it/s]

 30%|███       | 1424/4716 [09:53<22:39,  2.42it/s]

 30%|███       | 1425/4716 [09:53<22:40,  2.42it/s]

 30%|███       | 1426/4716 [09:54<22:38,  2.42it/s]

 30%|███       | 1427/4716 [09:54<22:39,  2.42it/s]

 30%|███       | 1428/4716 [09:54<22:37,  2.42it/s]

 30%|███       | 1429/4716 [09:55<22:37,  2.42it/s]

 30%|███       | 1430/4716 [09:55<22:38,  2.42it/s]

 30%|███       | 1431/4716 [09:56<22:36,  2.42it/s]

 30%|███       | 1432/4716 [09:56<22:37,  2.42it/s]

 30%|███       | 1433/4716 [09:57<22:38,  2.42it/s]

 30%|███       | 1434/4716 [09:57<22:39,  2.41it/s]

 30%|███       | 1435/4716 [09:57<22:37,  2.42it/s]

 30%|███       | 1436/4716 [09:58<22:36,  2.42it/s]

 30%|███       | 1437/4716 [09:58<22:35,  2.42it/s]

 30%|███       | 1438/4716 [09:59<22:35,  2.42it/s]

 31%|███       | 1439/4716 [09:59<22:35,  2.42it/s]

 31%|███       | 1440/4716 [09:59<22:34,  2.42it/s]

 31%|███       | 1441/4716 [10:00<22:34,  2.42it/s]

 31%|███       | 1442/4716 [10:00<22:33,  2.42it/s]

 31%|███       | 1443/4716 [10:01<22:33,  2.42it/s]

 31%|███       | 1444/4716 [10:01<22:41,  2.40it/s]

 31%|███       | 1445/4716 [10:02<22:36,  2.41it/s]

 31%|███       | 1446/4716 [10:02<22:35,  2.41it/s]

 31%|███       | 1447/4716 [10:02<22:33,  2.41it/s]

 31%|███       | 1448/4716 [10:03<22:33,  2.41it/s]

 31%|███       | 1449/4716 [10:03<22:31,  2.42it/s]

 31%|███       | 1450/4716 [10:04<22:31,  2.42it/s]

 31%|███       | 1451/4716 [10:04<22:30,  2.42it/s]

 31%|███       | 1452/4716 [10:04<22:29,  2.42it/s]

 31%|███       | 1453/4716 [10:05<22:28,  2.42it/s]

 31%|███       | 1454/4716 [10:05<22:27,  2.42it/s]

 31%|███       | 1455/4716 [10:06<22:25,  2.42it/s]

 31%|███       | 1456/4716 [10:06<22:26,  2.42it/s]

 31%|███       | 1457/4716 [10:06<22:26,  2.42it/s]

 31%|███       | 1458/4716 [10:07<22:25,  2.42it/s]

 31%|███       | 1459/4716 [10:07<22:25,  2.42it/s]

 31%|███       | 1460/4716 [10:08<22:23,  2.42it/s]

 31%|███       | 1461/4716 [10:08<22:23,  2.42it/s]

 31%|███       | 1462/4716 [10:09<22:25,  2.42it/s]

 31%|███       | 1463/4716 [10:09<22:24,  2.42it/s]

 31%|███       | 1464/4716 [10:09<22:23,  2.42it/s]

 31%|███       | 1465/4716 [10:10<22:24,  2.42it/s]

 31%|███       | 1466/4716 [10:10<22:22,  2.42it/s]

 31%|███       | 1467/4716 [10:11<22:23,  2.42it/s]

 31%|███       | 1468/4716 [10:11<22:23,  2.42it/s]

 31%|███       | 1469/4716 [10:11<22:24,  2.41it/s]

 31%|███       | 1470/4716 [10:12<22:22,  2.42it/s]

 31%|███       | 1471/4716 [10:12<22:21,  2.42it/s]

 31%|███       | 1472/4716 [10:13<22:23,  2.42it/s]

 31%|███       | 1473/4716 [10:13<22:21,  2.42it/s]

 31%|███▏      | 1474/4716 [10:13<22:22,  2.42it/s]

 31%|███▏      | 1475/4716 [10:14<22:20,  2.42it/s]

 31%|███▏      | 1476/4716 [10:14<22:21,  2.42it/s]

 31%|███▏      | 1477/4716 [10:15<22:18,  2.42it/s]

 31%|███▏      | 1478/4716 [10:15<22:18,  2.42it/s]

 31%|███▏      | 1479/4716 [10:16<22:18,  2.42it/s]

 31%|███▏      | 1480/4716 [10:16<22:18,  2.42it/s]

 31%|███▏      | 1481/4716 [10:16<22:19,  2.42it/s]

 31%|███▏      | 1482/4716 [10:17<22:18,  2.42it/s]

 31%|███▏      | 1483/4716 [10:17<22:16,  2.42it/s]

 31%|███▏      | 1484/4716 [10:18<22:15,  2.42it/s]

 31%|███▏      | 1485/4716 [10:18<22:14,  2.42it/s]

 32%|███▏      | 1486/4716 [10:18<22:17,  2.41it/s]

 32%|███▏      | 1487/4716 [10:19<22:16,  2.42it/s]

 32%|███▏      | 1488/4716 [10:19<22:15,  2.42it/s]

 32%|███▏      | 1489/4716 [10:20<22:14,  2.42it/s]

 32%|███▏      | 1490/4716 [10:20<22:14,  2.42it/s]

 32%|███▏      | 1491/4716 [10:21<22:14,  2.42it/s]

 32%|███▏      | 1492/4716 [10:21<22:12,  2.42it/s]

 32%|███▏      | 1493/4716 [10:21<22:12,  2.42it/s]

 32%|███▏      | 1494/4716 [10:22<22:11,  2.42it/s]

 32%|███▏      | 1495/4716 [10:22<22:11,  2.42it/s]

 32%|███▏      | 1496/4716 [10:23<22:12,  2.42it/s]

 32%|███▏      | 1497/4716 [10:23<22:13,  2.41it/s]

 32%|███▏      | 1498/4716 [10:23<22:11,  2.42it/s]

 32%|███▏      | 1499/4716 [10:24<22:10,  2.42it/s]

 32%|███▏      | 1500/4716 [10:24<22:09,  2.42it/s]

 32%|███▏      | 1501/4716 [10:25<22:08,  2.42it/s]

 32%|███▏      | 1502/4716 [10:25<22:09,  2.42it/s]

 32%|███▏      | 1503/4716 [10:25<22:09,  2.42it/s]

 32%|███▏      | 1504/4716 [10:26<22:08,  2.42it/s]

 32%|███▏      | 1505/4716 [10:26<22:08,  2.42it/s]

 32%|███▏      | 1506/4716 [10:27<22:10,  2.41it/s]

 32%|███▏      | 1507/4716 [10:27<22:08,  2.41it/s]

 32%|███▏      | 1508/4716 [10:28<22:10,  2.41it/s]

 32%|███▏      | 1509/4716 [10:28<22:08,  2.41it/s]

 32%|███▏      | 1510/4716 [10:28<22:07,  2.42it/s]

 32%|███▏      | 1511/4716 [10:29<22:07,  2.41it/s]

 32%|███▏      | 1512/4716 [10:29<22:05,  2.42it/s]

 32%|███▏      | 1513/4716 [10:30<22:05,  2.42it/s]

 32%|███▏      | 1514/4716 [10:30<22:06,  2.41it/s]

 32%|███▏      | 1515/4716 [10:30<22:05,  2.41it/s]

 32%|███▏      | 1516/4716 [10:31<22:06,  2.41it/s]

 32%|███▏      | 1517/4716 [10:31<22:04,  2.41it/s]

 32%|███▏      | 1518/4716 [10:32<22:04,  2.41it/s]

 32%|███▏      | 1519/4716 [10:32<22:03,  2.42it/s]

 32%|███▏      | 1520/4716 [10:33<22:02,  2.42it/s]

 32%|███▏      | 1521/4716 [10:33<22:03,  2.41it/s]

 32%|███▏      | 1522/4716 [10:33<22:03,  2.41it/s]

 32%|███▏      | 1523/4716 [10:34<22:02,  2.41it/s]

 32%|███▏      | 1524/4716 [10:34<22:02,  2.41it/s]

 32%|███▏      | 1525/4716 [10:35<22:02,  2.41it/s]

 32%|███▏      | 1526/4716 [10:35<22:01,  2.41it/s]

 32%|███▏      | 1527/4716 [10:35<22:00,  2.41it/s]

 32%|███▏      | 1528/4716 [10:36<21:59,  2.42it/s]

 32%|███▏      | 1529/4716 [10:36<21:59,  2.42it/s]

 32%|███▏      | 1530/4716 [10:37<21:58,  2.42it/s]

 32%|███▏      | 1531/4716 [10:37<22:00,  2.41it/s]

 32%|███▏      | 1532/4716 [10:37<21:58,  2.41it/s]

 33%|███▎      | 1533/4716 [10:38<21:58,  2.41it/s]

 33%|███▎      | 1534/4716 [10:38<21:57,  2.42it/s]

 33%|███▎      | 1535/4716 [10:39<21:56,  2.42it/s]

 33%|███▎      | 1536/4716 [10:39<21:55,  2.42it/s]

 33%|███▎      | 1537/4716 [10:40<21:54,  2.42it/s]

 33%|███▎      | 1538/4716 [10:40<21:55,  2.42it/s]

 33%|███▎      | 1539/4716 [10:40<21:54,  2.42it/s]

 33%|███▎      | 1540/4716 [10:41<22:01,  2.40it/s]

 33%|███▎      | 1541/4716 [10:41<21:59,  2.41it/s]

 33%|███▎      | 1542/4716 [10:42<21:59,  2.41it/s]

 33%|███▎      | 1543/4716 [10:42<21:56,  2.41it/s]

 33%|███▎      | 1544/4716 [10:42<21:56,  2.41it/s]

 33%|███▎      | 1545/4716 [10:43<21:53,  2.41it/s]

 33%|███▎      | 1546/4716 [10:43<21:54,  2.41it/s]

 33%|███▎      | 1547/4716 [10:44<21:53,  2.41it/s]

 33%|███▎      | 1548/4716 [10:44<21:53,  2.41it/s]

 33%|███▎      | 1549/4716 [10:45<21:53,  2.41it/s]

 33%|███▎      | 1550/4716 [10:45<21:52,  2.41it/s]

 33%|███▎      | 1551/4716 [10:45<21:54,  2.41it/s]

 33%|███▎      | 1552/4716 [10:46<21:52,  2.41it/s]

 33%|███▎      | 1553/4716 [10:46<21:51,  2.41it/s]

 33%|███▎      | 1554/4716 [10:47<21:50,  2.41it/s]

 33%|███▎      | 1555/4716 [10:47<21:51,  2.41it/s]

 33%|███▎      | 1556/4716 [10:47<21:51,  2.41it/s]

 33%|███▎      | 1557/4716 [10:48<21:50,  2.41it/s]

 33%|███▎      | 1558/4716 [10:48<21:49,  2.41it/s]

 33%|███▎      | 1559/4716 [10:49<21:50,  2.41it/s]

 33%|███▎      | 1560/4716 [10:49<21:47,  2.41it/s]

 33%|███▎      | 1561/4716 [10:50<21:47,  2.41it/s]

 33%|███▎      | 1562/4716 [10:50<21:48,  2.41it/s]

 33%|███▎      | 1563/4716 [10:50<21:48,  2.41it/s]

 33%|███▎      | 1564/4716 [10:51<21:47,  2.41it/s]

 33%|███▎      | 1565/4716 [10:51<21:47,  2.41it/s]

 33%|███▎      | 1566/4716 [10:52<21:46,  2.41it/s]

 33%|███▎      | 1567/4716 [10:52<21:47,  2.41it/s]

 33%|███▎      | 1568/4716 [10:52<21:44,  2.41it/s]

 33%|███▎      | 1569/4716 [10:53<21:44,  2.41it/s]

 33%|███▎      | 1570/4716 [10:53<21:47,  2.41it/s]

 33%|███▎      | 1571/4716 [10:54<21:43,  2.41it/s]

 33%|███▎      | 1572/4716 [10:54<21:42,  2.41it/s]

 33%|███▎      | 1573/4716 [10:54<21:42,  2.41it/s]

 33%|███▎      | 1574/4716 [10:55<21:41,  2.41it/s]

 33%|███▎      | 1575/4716 [10:55<21:41,  2.41it/s]

 33%|███▎      | 1576/4716 [10:56<21:41,  2.41it/s]

 33%|███▎      | 1577/4716 [10:56<21:40,  2.41it/s]

 33%|███▎      | 1578/4716 [10:57<21:41,  2.41it/s]

 33%|███▎      | 1579/4716 [10:57<21:40,  2.41it/s]

 34%|███▎      | 1580/4716 [10:57<21:40,  2.41it/s]

 34%|███▎      | 1581/4716 [10:58<21:38,  2.41it/s]

 34%|███▎      | 1582/4716 [10:58<21:38,  2.41it/s]

 34%|███▎      | 1583/4716 [10:59<21:38,  2.41it/s]

 34%|███▎      | 1584/4716 [10:59<21:38,  2.41it/s]

 34%|███▎      | 1585/4716 [10:59<21:38,  2.41it/s]

 34%|███▎      | 1586/4716 [11:00<21:37,  2.41it/s]

 34%|███▎      | 1587/4716 [11:00<21:36,  2.41it/s]

 34%|███▎      | 1588/4716 [11:01<21:36,  2.41it/s]

 34%|███▎      | 1589/4716 [11:01<21:35,  2.41it/s]

 34%|███▎      | 1590/4716 [11:02<21:36,  2.41it/s]

 34%|███▎      | 1591/4716 [11:02<21:37,  2.41it/s]

 34%|███▍      | 1592/4716 [11:02<21:35,  2.41it/s]

 34%|███▍      | 1593/4716 [11:03<21:35,  2.41it/s]

 34%|███▍      | 1594/4716 [11:03<21:35,  2.41it/s]

 34%|███▍      | 1595/4716 [11:04<21:37,  2.40it/s]

 34%|███▍      | 1596/4716 [11:04<21:36,  2.41it/s]

 34%|███▍      | 1597/4716 [11:04<21:34,  2.41it/s]

 34%|███▍      | 1598/4716 [11:05<21:33,  2.41it/s]

 34%|███▍      | 1599/4716 [11:05<21:33,  2.41it/s]

 34%|███▍      | 1600/4716 [11:06<21:33,  2.41it/s]

 34%|███▍      | 1601/4716 [11:06<21:32,  2.41it/s]

 34%|███▍      | 1602/4716 [11:07<21:33,  2.41it/s]

 34%|███▍      | 1603/4716 [11:07<21:32,  2.41it/s]

 34%|███▍      | 1604/4716 [11:07<21:32,  2.41it/s]

 34%|███▍      | 1605/4716 [11:08<21:31,  2.41it/s]

 34%|███▍      | 1606/4716 [11:08<21:30,  2.41it/s]

 34%|███▍      | 1607/4716 [11:09<21:29,  2.41it/s]

 34%|███▍      | 1608/4716 [11:09<21:30,  2.41it/s]

 34%|███▍      | 1609/4716 [11:09<21:30,  2.41it/s]

 34%|███▍      | 1610/4716 [11:10<21:28,  2.41it/s]

 34%|███▍      | 1611/4716 [11:10<21:30,  2.41it/s]

 34%|███▍      | 1612/4716 [11:11<21:28,  2.41it/s]

 34%|███▍      | 1613/4716 [11:11<21:31,  2.40it/s]

 34%|███▍      | 1614/4716 [11:12<21:29,  2.40it/s]

 34%|███▍      | 1615/4716 [11:12<21:30,  2.40it/s]

 34%|███▍      | 1616/4716 [11:12<21:28,  2.41it/s]

 34%|███▍      | 1617/4716 [11:13<21:27,  2.41it/s]

 34%|███▍      | 1618/4716 [11:13<21:26,  2.41it/s]

 34%|███▍      | 1619/4716 [11:14<21:26,  2.41it/s]

 34%|███▍      | 1620/4716 [11:14<21:25,  2.41it/s]

 34%|███▍      | 1621/4716 [11:14<21:25,  2.41it/s]

 34%|███▍      | 1622/4716 [11:15<21:26,  2.41it/s]

 34%|███▍      | 1623/4716 [11:15<21:25,  2.41it/s]

 34%|███▍      | 1624/4716 [11:16<21:24,  2.41it/s]

 34%|███▍      | 1625/4716 [11:16<21:25,  2.40it/s]

 34%|███▍      | 1626/4716 [11:17<21:25,  2.40it/s]

 34%|███▍      | 1627/4716 [11:17<21:23,  2.41it/s]

 35%|███▍      | 1628/4716 [11:17<21:24,  2.40it/s]

 35%|███▍      | 1629/4716 [11:18<21:22,  2.41it/s]

 35%|███▍      | 1630/4716 [11:18<21:22,  2.41it/s]

 35%|███▍      | 1631/4716 [11:19<21:25,  2.40it/s]

 35%|███▍      | 1632/4716 [11:19<21:24,  2.40it/s]

 35%|███▍      | 1633/4716 [11:19<21:23,  2.40it/s]

 35%|███▍      | 1634/4716 [11:20<21:26,  2.40it/s]

 35%|███▍      | 1635/4716 [11:20<21:24,  2.40it/s]

 35%|███▍      | 1636/4716 [11:21<21:24,  2.40it/s]

 35%|███▍      | 1637/4716 [11:21<21:22,  2.40it/s]

 35%|███▍      | 1638/4716 [11:21<21:21,  2.40it/s]

 35%|███▍      | 1639/4716 [11:22<21:19,  2.40it/s]

 35%|███▍      | 1640/4716 [11:22<21:18,  2.41it/s]

 35%|███▍      | 1641/4716 [11:23<21:16,  2.41it/s]

 35%|███▍      | 1642/4716 [11:23<21:15,  2.41it/s]

 35%|███▍      | 1643/4716 [11:24<21:13,  2.41it/s]

 35%|███▍      | 1644/4716 [11:24<21:13,  2.41it/s]

 35%|███▍      | 1645/4716 [11:24<21:11,  2.42it/s]

 35%|███▍      | 1646/4716 [11:25<21:13,  2.41it/s]

 35%|███▍      | 1647/4716 [11:25<21:12,  2.41it/s]

 35%|███▍      | 1648/4716 [11:26<21:11,  2.41it/s]

 35%|███▍      | 1649/4716 [11:26<21:13,  2.41it/s]

 35%|███▍      | 1650/4716 [11:26<21:13,  2.41it/s]

 35%|███▌      | 1651/4716 [11:27<21:12,  2.41it/s]

 35%|███▌      | 1652/4716 [11:27<21:12,  2.41it/s]

 35%|███▌      | 1653/4716 [11:28<21:11,  2.41it/s]

 35%|███▌      | 1654/4716 [11:28<21:10,  2.41it/s]

 35%|███▌      | 1655/4716 [11:29<21:13,  2.40it/s]

 35%|███▌      | 1656/4716 [11:29<21:13,  2.40it/s]

 35%|███▌      | 1657/4716 [11:29<21:12,  2.40it/s]

 35%|███▌      | 1658/4716 [11:30<21:10,  2.41it/s]

 35%|███▌      | 1659/4716 [11:30<21:10,  2.41it/s]

 35%|███▌      | 1660/4716 [11:31<21:09,  2.41it/s]

 35%|███▌      | 1661/4716 [11:31<21:08,  2.41it/s]

 35%|███▌      | 1662/4716 [11:31<21:07,  2.41it/s]

 35%|███▌      | 1663/4716 [11:32<21:07,  2.41it/s]

 35%|███▌      | 1664/4716 [11:32<21:06,  2.41it/s]

 35%|███▌      | 1665/4716 [11:33<21:07,  2.41it/s]

 35%|███▌      | 1666/4716 [11:33<21:07,  2.41it/s]

 35%|███▌      | 1667/4716 [11:34<21:08,  2.40it/s]

 35%|███▌      | 1668/4716 [11:34<21:06,  2.41it/s]

 35%|███▌      | 1669/4716 [11:34<21:06,  2.41it/s]

 35%|███▌      | 1670/4716 [11:35<21:06,  2.41it/s]

 35%|███▌      | 1671/4716 [11:35<21:05,  2.41it/s]

 35%|███▌      | 1672/4716 [11:36<21:04,  2.41it/s]

 35%|███▌      | 1673/4716 [11:36<21:07,  2.40it/s]

 35%|███▌      | 1674/4716 [11:36<21:05,  2.40it/s]

 36%|███▌      | 1675/4716 [11:37<21:03,  2.41it/s]

 36%|███▌      | 1676/4716 [11:37<21:05,  2.40it/s]

 36%|███▌      | 1677/4716 [11:38<21:05,  2.40it/s]

 36%|███▌      | 1678/4716 [11:38<21:04,  2.40it/s]

 36%|███▌      | 1679/4716 [11:39<21:02,  2.41it/s]

 36%|███▌      | 1680/4716 [11:39<21:02,  2.40it/s]

 36%|███▌      | 1681/4716 [11:39<21:01,  2.41it/s]

 36%|███▌      | 1682/4716 [11:40<21:01,  2.41it/s]

 36%|███▌      | 1683/4716 [11:40<20:59,  2.41it/s]

 36%|███▌      | 1684/4716 [11:41<20:59,  2.41it/s]

 36%|███▌      | 1685/4716 [11:41<20:59,  2.41it/s]

 36%|███▌      | 1686/4716 [11:41<21:00,  2.40it/s]

 36%|███▌      | 1687/4716 [11:42<20:58,  2.41it/s]

 36%|███▌      | 1688/4716 [11:42<20:59,  2.40it/s]

 36%|███▌      | 1689/4716 [11:43<20:58,  2.40it/s]

 36%|███▌      | 1690/4716 [11:43<20:57,  2.41it/s]

 36%|███▌      | 1691/4716 [11:44<20:56,  2.41it/s]

 36%|███▌      | 1692/4716 [11:44<20:58,  2.40it/s]

 36%|███▌      | 1693/4716 [11:44<20:57,  2.40it/s]

 36%|███▌      | 1694/4716 [11:45<20:57,  2.40it/s]

 36%|███▌      | 1695/4716 [11:45<20:57,  2.40it/s]

 36%|███▌      | 1696/4716 [11:46<20:56,  2.40it/s]

 36%|███▌      | 1697/4716 [11:46<20:56,  2.40it/s]

 36%|███▌      | 1698/4716 [11:46<20:57,  2.40it/s]

 36%|███▌      | 1699/4716 [11:47<20:56,  2.40it/s]

 36%|███▌      | 1700/4716 [11:47<20:54,  2.40it/s]

 36%|███▌      | 1701/4716 [11:48<20:54,  2.40it/s]

 36%|███▌      | 1702/4716 [11:48<20:55,  2.40it/s]

 36%|███▌      | 1703/4716 [11:49<20:55,  2.40it/s]

 36%|███▌      | 1704/4716 [11:49<20:53,  2.40it/s]

 36%|███▌      | 1705/4716 [11:49<20:53,  2.40it/s]

 36%|███▌      | 1706/4716 [11:50<20:52,  2.40it/s]

 36%|███▌      | 1707/4716 [11:50<20:51,  2.40it/s]

 36%|███▌      | 1708/4716 [11:51<20:50,  2.41it/s]

 36%|███▌      | 1709/4716 [11:51<20:50,  2.40it/s]

 36%|███▋      | 1710/4716 [11:51<20:50,  2.40it/s]

 36%|███▋      | 1711/4716 [11:52<20:50,  2.40it/s]

 36%|███▋      | 1712/4716 [11:52<20:49,  2.40it/s]

 36%|███▋      | 1713/4716 [11:53<20:50,  2.40it/s]

 36%|███▋      | 1714/4716 [11:53<20:49,  2.40it/s]

 36%|███▋      | 1715/4716 [11:54<20:48,  2.40it/s]

 36%|███▋      | 1716/4716 [11:54<20:49,  2.40it/s]

 36%|███▋      | 1717/4716 [11:54<20:47,  2.40it/s]

 36%|███▋      | 1718/4716 [11:55<20:47,  2.40it/s]

 36%|███▋      | 1719/4716 [11:55<20:47,  2.40it/s]

 36%|███▋      | 1720/4716 [11:56<20:45,  2.40it/s]

 36%|███▋      | 1721/4716 [11:56<20:45,  2.40it/s]

 37%|███▋      | 1722/4716 [11:56<20:47,  2.40it/s]

 37%|███▋      | 1723/4716 [11:57<20:47,  2.40it/s]

 37%|███▋      | 1724/4716 [11:57<20:45,  2.40it/s]

 37%|███▋      | 1725/4716 [11:58<20:45,  2.40it/s]

 37%|███▋      | 1726/4716 [11:58<20:48,  2.39it/s]

 37%|███▋      | 1727/4716 [11:59<20:47,  2.40it/s]

 37%|███▋      | 1728/4716 [11:59<20:48,  2.39it/s]

 37%|███▋      | 1729/4716 [11:59<20:46,  2.40it/s]

 37%|███▋      | 1730/4716 [12:00<20:47,  2.39it/s]

 37%|███▋      | 1731/4716 [12:00<20:45,  2.40it/s]

 37%|███▋      | 1732/4716 [12:01<20:44,  2.40it/s]

 37%|███▋      | 1733/4716 [12:01<20:41,  2.40it/s]

 37%|███▋      | 1734/4716 [12:01<20:44,  2.40it/s]

 37%|███▋      | 1735/4716 [12:02<20:44,  2.39it/s]

 37%|███▋      | 1736/4716 [12:02<20:44,  2.39it/s]

 37%|███▋      | 1737/4716 [12:03<20:42,  2.40it/s]

 37%|███▋      | 1738/4716 [12:03<20:43,  2.40it/s]

 37%|███▋      | 1739/4716 [12:04<20:42,  2.40it/s]

 37%|███▋      | 1740/4716 [12:04<20:41,  2.40it/s]

 37%|███▋      | 1741/4716 [12:04<20:41,  2.40it/s]

 37%|███▋      | 1742/4716 [12:05<20:40,  2.40it/s]

 37%|███▋      | 1743/4716 [12:05<20:38,  2.40it/s]

 37%|███▋      | 1744/4716 [12:06<20:38,  2.40it/s]

 37%|███▋      | 1745/4716 [12:06<20:37,  2.40it/s]

 37%|███▋      | 1746/4716 [12:06<20:37,  2.40it/s]

 37%|███▋      | 1747/4716 [12:07<20:37,  2.40it/s]

 37%|███▋      | 1748/4716 [12:07<20:37,  2.40it/s]

 37%|███▋      | 1749/4716 [12:08<20:36,  2.40it/s]

 37%|███▋      | 1750/4716 [12:08<20:35,  2.40it/s]

 37%|███▋      | 1751/4716 [12:09<20:36,  2.40it/s]

 37%|███▋      | 1752/4716 [12:09<20:35,  2.40it/s]

 37%|███▋      | 1753/4716 [12:09<20:33,  2.40it/s]

 37%|███▋      | 1754/4716 [12:10<20:33,  2.40it/s]

 37%|███▋      | 1755/4716 [12:10<20:34,  2.40it/s]

 37%|███▋      | 1756/4716 [12:11<20:33,  2.40it/s]

 37%|███▋      | 1757/4716 [12:11<20:33,  2.40it/s]

 37%|███▋      | 1758/4716 [12:11<20:33,  2.40it/s]

 37%|███▋      | 1759/4716 [12:12<20:34,  2.40it/s]

 37%|███▋      | 1760/4716 [12:12<20:33,  2.40it/s]

 37%|███▋      | 1761/4716 [12:13<20:33,  2.39it/s]

 37%|███▋      | 1762/4716 [12:13<20:33,  2.40it/s]

 37%|███▋      | 1763/4716 [12:14<20:32,  2.40it/s]

 37%|███▋      | 1764/4716 [12:14<20:32,  2.39it/s]

 37%|███▋      | 1765/4716 [12:14<20:31,  2.40it/s]

 37%|███▋      | 1766/4716 [12:15<20:30,  2.40it/s]

 37%|███▋      | 1767/4716 [12:15<20:28,  2.40it/s]

 37%|███▋      | 1768/4716 [12:16<20:28,  2.40it/s]

 38%|███▊      | 1769/4716 [12:16<20:25,  2.40it/s]

 38%|███▊      | 1770/4716 [12:16<20:26,  2.40it/s]

 38%|███▊      | 1771/4716 [12:17<20:25,  2.40it/s]

 38%|███▊      | 1772/4716 [12:17<20:28,  2.40it/s]

 38%|███▊      | 1773/4716 [12:18<20:27,  2.40it/s]

 38%|███▊      | 1774/4716 [12:18<20:28,  2.40it/s]

 38%|███▊      | 1775/4716 [12:19<20:25,  2.40it/s]

 38%|███▊      | 1776/4716 [12:19<20:26,  2.40it/s]

 38%|███▊      | 1777/4716 [12:19<20:25,  2.40it/s]

 38%|███▊      | 1778/4716 [12:20<20:25,  2.40it/s]

 38%|███▊      | 1779/4716 [12:20<20:24,  2.40it/s]

 38%|███▊      | 1780/4716 [12:21<20:25,  2.40it/s]

 38%|███▊      | 1781/4716 [12:21<20:24,  2.40it/s]

 38%|███▊      | 1782/4716 [12:21<20:25,  2.39it/s]

 38%|███▊      | 1783/4716 [12:22<20:22,  2.40it/s]

 38%|███▊      | 1784/4716 [12:22<20:22,  2.40it/s]

 38%|███▊      | 1785/4716 [12:23<20:24,  2.39it/s]

 38%|███▊      | 1786/4716 [12:23<20:21,  2.40it/s]

 38%|███▊      | 1787/4716 [12:24<20:21,  2.40it/s]

 38%|███▊      | 1788/4716 [12:24<20:20,  2.40it/s]

 38%|███▊      | 1789/4716 [12:24<20:19,  2.40it/s]

 38%|███▊      | 1790/4716 [12:25<20:18,  2.40it/s]

 38%|███▊      | 1791/4716 [12:25<20:16,  2.40it/s]

 38%|███▊      | 1792/4716 [12:26<20:17,  2.40it/s]

 38%|███▊      | 1793/4716 [12:26<20:18,  2.40it/s]

 38%|███▊      | 1794/4716 [12:26<20:17,  2.40it/s]

 38%|███▊      | 1795/4716 [12:27<20:17,  2.40it/s]

 38%|███▊      | 1796/4716 [12:27<20:18,  2.40it/s]

 38%|███▊      | 1797/4716 [12:28<20:19,  2.39it/s]

 38%|███▊      | 1798/4716 [12:28<20:17,  2.40it/s]

 38%|███▊      | 1799/4716 [12:29<20:18,  2.39it/s]

 38%|███▊      | 1800/4716 [12:29<20:16,  2.40it/s]

 38%|███▊      | 1801/4716 [12:29<20:18,  2.39it/s]

 38%|███▊      | 1802/4716 [12:30<20:17,  2.39it/s]

 38%|███▊      | 1803/4716 [12:30<20:17,  2.39it/s]

 38%|███▊      | 1804/4716 [12:31<20:15,  2.40it/s]

 38%|███▊      | 1805/4716 [12:31<20:14,  2.40it/s]

 38%|███▊      | 1806/4716 [12:31<20:13,  2.40it/s]

 38%|███▊      | 1807/4716 [12:32<20:15,  2.39it/s]

 38%|███▊      | 1808/4716 [12:32<20:13,  2.40it/s]

 38%|███▊      | 1809/4716 [12:33<20:12,  2.40it/s]

 38%|███▊      | 1810/4716 [12:33<20:11,  2.40it/s]

 38%|███▊      | 1811/4716 [12:34<20:11,  2.40it/s]

 38%|███▊      | 1812/4716 [12:34<20:09,  2.40it/s]

 38%|███▊      | 1813/4716 [12:34<20:11,  2.40it/s]

 38%|███▊      | 1814/4716 [12:35<20:12,  2.39it/s]

 38%|███▊      | 1815/4716 [12:35<20:12,  2.39it/s]

 39%|███▊      | 1816/4716 [12:36<20:11,  2.39it/s]

 39%|███▊      | 1817/4716 [12:36<20:10,  2.39it/s]

 39%|███▊      | 1818/4716 [12:36<20:09,  2.40it/s]

 39%|███▊      | 1819/4716 [12:37<20:09,  2.40it/s]

 39%|███▊      | 1820/4716 [12:37<20:08,  2.40it/s]

 39%|███▊      | 1821/4716 [12:38<20:08,  2.40it/s]

 39%|███▊      | 1822/4716 [12:38<20:08,  2.40it/s]

 39%|███▊      | 1823/4716 [12:39<20:08,  2.39it/s]

 39%|███▊      | 1824/4716 [12:39<20:08,  2.39it/s]

 39%|███▊      | 1825/4716 [12:39<20:07,  2.39it/s]

 39%|███▊      | 1826/4716 [12:40<20:06,  2.40it/s]

 39%|███▊      | 1827/4716 [12:40<20:06,  2.40it/s]

 39%|███▉      | 1828/4716 [12:41<20:14,  2.38it/s]

 39%|███▉      | 1829/4716 [12:41<20:12,  2.38it/s]

 39%|███▉      | 1830/4716 [12:41<20:10,  2.38it/s]

 39%|███▉      | 1831/4716 [12:42<20:07,  2.39it/s]

 39%|███▉      | 1832/4716 [12:42<20:05,  2.39it/s]

 39%|███▉      | 1833/4716 [12:43<20:04,  2.39it/s]

 39%|███▉      | 1834/4716 [12:43<20:04,  2.39it/s]

 39%|███▉      | 1835/4716 [12:44<20:03,  2.39it/s]

 39%|███▉      | 1836/4716 [12:44<20:01,  2.40it/s]

 39%|███▉      | 1837/4716 [12:44<20:03,  2.39it/s]

 39%|███▉      | 1838/4716 [12:45<20:02,  2.39it/s]

 39%|███▉      | 1839/4716 [12:45<20:01,  2.40it/s]

 39%|███▉      | 1840/4716 [12:46<20:03,  2.39it/s]

 39%|███▉      | 1841/4716 [12:46<20:02,  2.39it/s]

 39%|███▉      | 1842/4716 [12:46<20:02,  2.39it/s]

 39%|███▉      | 1843/4716 [12:47<20:03,  2.39it/s]

 39%|███▉      | 1844/4716 [12:47<20:03,  2.39it/s]

 39%|███▉      | 1845/4716 [12:48<19:59,  2.39it/s]

 39%|███▉      | 1846/4716 [12:48<19:58,  2.39it/s]

 39%|███▉      | 1847/4716 [12:49<19:58,  2.39it/s]

 39%|███▉      | 1848/4716 [12:49<19:59,  2.39it/s]

 39%|███▉      | 1849/4716 [12:49<19:57,  2.39it/s]

 39%|███▉      | 1850/4716 [12:50<19:58,  2.39it/s]

 39%|███▉      | 1851/4716 [12:50<19:56,  2.39it/s]

 39%|███▉      | 1852/4716 [12:51<19:57,  2.39it/s]

 39%|███▉      | 1853/4716 [12:51<19:57,  2.39it/s]

 39%|███▉      | 1854/4716 [12:52<19:58,  2.39it/s]

 39%|███▉      | 1855/4716 [12:52<19:56,  2.39it/s]

 39%|███▉      | 1856/4716 [12:52<19:57,  2.39it/s]

 39%|███▉      | 1857/4716 [12:53<19:56,  2.39it/s]

 39%|███▉      | 1858/4716 [12:53<19:54,  2.39it/s]

 39%|███▉      | 1859/4716 [12:54<19:53,  2.39it/s]

 39%|███▉      | 1860/4716 [12:54<19:54,  2.39it/s]

 39%|███▉      | 1861/4716 [12:54<19:51,  2.40it/s]

 39%|███▉      | 1862/4716 [12:55<19:52,  2.39it/s]

 40%|███▉      | 1863/4716 [12:55<19:50,  2.40it/s]

 40%|███▉      | 1864/4716 [12:56<19:51,  2.39it/s]

 40%|███▉      | 1865/4716 [12:56<19:49,  2.40it/s]

 40%|███▉      | 1866/4716 [12:57<19:50,  2.39it/s]

 40%|███▉      | 1867/4716 [12:57<19:48,  2.40it/s]

 40%|███▉      | 1868/4716 [12:57<19:51,  2.39it/s]

 40%|███▉      | 1869/4716 [12:58<19:49,  2.39it/s]

 40%|███▉      | 1870/4716 [12:58<19:49,  2.39it/s]

 40%|███▉      | 1871/4716 [12:59<19:49,  2.39it/s]

 40%|███▉      | 1872/4716 [12:59<19:49,  2.39it/s]

 40%|███▉      | 1873/4716 [12:59<19:49,  2.39it/s]

 40%|███▉      | 1874/4716 [13:00<19:48,  2.39it/s]

 40%|███▉      | 1875/4716 [13:00<19:47,  2.39it/s]

 40%|███▉      | 1876/4716 [13:01<19:46,  2.39it/s]

 40%|███▉      | 1877/4716 [13:01<19:45,  2.39it/s]

logging
logging the anndata

 40%|███▉      | 1878/4716 [13:02<20:20,  2.33it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 40%|███▉      | 1879/4716 [13:02<20:06,  2.35it/s]

 40%|███▉      | 1880/4716 [13:02<19:53,  2.38it/s]

 40%|███▉      | 1881/4716 [13:03<19:45,  2.39it/s]

 40%|███▉      | 1882/4716 [13:03<19:39,  2.40it/s]

 40%|███▉      | 1883/4716 [13:04<19:34,  2.41it/s]

 40%|███▉      | 1884/4716 [13:04<19:31,  2.42it/s]

 40%|███▉      | 1885/4716 [13:04<19:28,  2.42it/s]

 40%|███▉      | 1886/4716 [13:05<19:27,  2.42it/s]

 40%|████      | 1887/4716 [13:05<19:24,  2.43it/s]

 40%|████      | 1888/4716 [13:06<19:23,  2.43it/s]

 40%|████      | 1889/4716 [13:06<19:21,  2.43it/s]

 40%|████      | 1890/4716 [13:07<19:21,  2.43it/s]

 40%|████      | 1891/4716 [13:07<19:20,  2.43it/s]

 40%|████      | 1892/4716 [13:07<19:20,  2.43it/s]

 40%|████      | 1893/4716 [13:08<19:19,  2.43it/s]

 40%|████      | 1894/4716 [13:08<19:18,  2.43it/s]

 40%|████      | 1895/4716 [13:09<19:19,  2.43it/s]

 40%|████      | 1896/4716 [13:09<19:19,  2.43it/s]

 40%|████      | 1897/4716 [13:09<19:19,  2.43it/s]

 40%|████      | 1898/4716 [13:10<19:18,  2.43it/s]

 40%|████      | 1899/4716 [13:10<19:17,  2.43it/s]

 40%|████      | 1900/4716 [13:11<19:17,  2.43it/s]

 40%|████      | 1901/4716 [13:11<19:16,  2.43it/s]

 40%|████      | 1902/4716 [13:11<19:17,  2.43it/s]

 40%|████      | 1903/4716 [13:12<19:16,  2.43it/s]

 40%|████      | 1904/4716 [13:12<19:16,  2.43it/s]

 40%|████      | 1905/4716 [13:13<19:21,  2.42it/s]

 40%|████      | 1906/4716 [13:13<19:18,  2.43it/s]

 40%|████      | 1907/4716 [13:14<19:17,  2.43it/s]

 40%|████      | 1908/4716 [13:14<19:16,  2.43it/s]

 40%|████      | 1909/4716 [13:14<19:15,  2.43it/s]

 41%|████      | 1910/4716 [13:15<19:14,  2.43it/s]

 41%|████      | 1911/4716 [13:15<19:14,  2.43it/s]

 41%|████      | 1912/4716 [13:16<19:13,  2.43it/s]

 41%|████      | 1913/4716 [13:16<19:13,  2.43it/s]

 41%|████      | 1914/4716 [13:16<19:13,  2.43it/s]

 41%|████      | 1915/4716 [13:17<19:13,  2.43it/s]

 41%|████      | 1916/4716 [13:17<19:11,  2.43it/s]

 41%|████      | 1917/4716 [13:18<19:12,  2.43it/s]

 41%|████      | 1918/4716 [13:18<19:11,  2.43it/s]

 41%|████      | 1919/4716 [13:18<19:10,  2.43it/s]

 41%|████      | 1920/4716 [13:19<19:11,  2.43it/s]

 41%|████      | 1921/4716 [13:19<19:12,  2.43it/s]

 41%|████      | 1922/4716 [13:20<19:12,  2.43it/s]

 41%|████      | 1923/4716 [13:20<19:10,  2.43it/s]

 41%|████      | 1924/4716 [13:21<19:10,  2.43it/s]

 41%|████      | 1925/4716 [13:21<19:09,  2.43it/s]

 41%|████      | 1926/4716 [13:21<19:08,  2.43it/s]

 41%|████      | 1927/4716 [13:22<19:08,  2.43it/s]

 41%|████      | 1928/4716 [13:22<19:09,  2.43it/s]

 41%|████      | 1929/4716 [13:23<19:07,  2.43it/s]

 41%|████      | 1930/4716 [13:23<19:06,  2.43it/s]

 41%|████      | 1931/4716 [13:23<19:07,  2.43it/s]

 41%|████      | 1932/4716 [13:24<19:07,  2.43it/s]

 41%|████      | 1933/4716 [13:24<19:08,  2.42it/s]

 41%|████      | 1934/4716 [13:25<19:10,  2.42it/s]

 41%|████      | 1935/4716 [13:25<19:07,  2.42it/s]

 41%|████      | 1936/4716 [13:25<19:05,  2.43it/s]

 41%|████      | 1937/4716 [13:26<19:03,  2.43it/s]

 41%|████      | 1938/4716 [13:26<19:03,  2.43it/s]

 41%|████      | 1939/4716 [13:27<19:03,  2.43it/s]

 41%|████      | 1940/4716 [13:27<19:02,  2.43it/s]

 41%|████      | 1941/4716 [13:28<19:03,  2.43it/s]

 41%|████      | 1942/4716 [13:28<19:02,  2.43it/s]

 41%|████      | 1943/4716 [13:28<19:02,  2.43it/s]

 41%|████      | 1944/4716 [13:29<19:01,  2.43it/s]

 41%|████      | 1945/4716 [13:29<19:00,  2.43it/s]

 41%|████▏     | 1946/4716 [13:30<19:00,  2.43it/s]

 41%|████▏     | 1947/4716 [13:30<18:59,  2.43it/s]

 41%|████▏     | 1948/4716 [13:30<18:58,  2.43it/s]

 41%|████▏     | 1949/4716 [13:31<19:00,  2.43it/s]

 41%|████▏     | 1950/4716 [13:31<18:59,  2.43it/s]

 41%|████▏     | 1951/4716 [13:32<19:01,  2.42it/s]

 41%|████▏     | 1952/4716 [13:32<19:00,  2.42it/s]

 41%|████▏     | 1953/4716 [13:32<19:03,  2.42it/s]

 41%|████▏     | 1954/4716 [13:33<19:00,  2.42it/s]

 41%|████▏     | 1955/4716 [13:33<18:59,  2.42it/s]

 41%|████▏     | 1956/4716 [13:34<18:59,  2.42it/s]

 41%|████▏     | 1957/4716 [13:34<18:57,  2.42it/s]

 42%|████▏     | 1958/4716 [13:35<18:57,  2.42it/s]

 42%|████▏     | 1959/4716 [13:35<18:56,  2.43it/s]

 42%|████▏     | 1960/4716 [13:35<18:57,  2.42it/s]

 42%|████▏     | 1961/4716 [13:36<18:56,  2.42it/s]

 42%|████▏     | 1962/4716 [13:36<18:57,  2.42it/s]

 42%|████▏     | 1963/4716 [13:37<18:56,  2.42it/s]

 42%|████▏     | 1964/4716 [13:37<18:56,  2.42it/s]

 42%|████▏     | 1965/4716 [13:37<18:55,  2.42it/s]

 42%|████▏     | 1966/4716 [13:38<18:55,  2.42it/s]

 42%|████▏     | 1967/4716 [13:38<18:54,  2.42it/s]

 42%|████▏     | 1968/4716 [13:39<18:53,  2.42it/s]

 42%|████▏     | 1969/4716 [13:39<18:55,  2.42it/s]

 42%|████▏     | 1970/4716 [13:39<18:53,  2.42it/s]

 42%|████▏     | 1971/4716 [13:40<18:54,  2.42it/s]

 42%|████▏     | 1972/4716 [13:40<18:53,  2.42it/s]

 42%|████▏     | 1973/4716 [13:41<18:53,  2.42it/s]

 42%|████▏     | 1974/4716 [13:41<18:51,  2.42it/s]

 42%|████▏     | 1975/4716 [13:42<18:54,  2.42it/s]

 42%|████▏     | 1976/4716 [13:42<18:53,  2.42it/s]

 42%|████▏     | 1977/4716 [13:42<18:52,  2.42it/s]

 42%|████▏     | 1978/4716 [13:43<18:50,  2.42it/s]

 42%|████▏     | 1979/4716 [13:43<18:49,  2.42it/s]

 42%|████▏     | 1980/4716 [13:44<18:49,  2.42it/s]

 42%|████▏     | 1981/4716 [13:44<18:50,  2.42it/s]

 42%|████▏     | 1982/4716 [13:44<18:50,  2.42it/s]

 42%|████▏     | 1983/4716 [13:45<18:49,  2.42it/s]

 42%|████▏     | 1984/4716 [13:45<18:48,  2.42it/s]

 42%|████▏     | 1985/4716 [13:46<18:46,  2.42it/s]

 42%|████▏     | 1986/4716 [13:46<18:45,  2.43it/s]

 42%|████▏     | 1987/4716 [13:47<18:44,  2.43it/s]

 42%|████▏     | 1988/4716 [13:47<18:45,  2.42it/s]

 42%|████▏     | 1989/4716 [13:47<18:45,  2.42it/s]

 42%|████▏     | 1990/4716 [13:48<18:47,  2.42it/s]

 42%|████▏     | 1991/4716 [13:48<18:48,  2.42it/s]

 42%|████▏     | 1992/4716 [13:49<18:45,  2.42it/s]

 42%|████▏     | 1993/4716 [13:49<18:43,  2.42it/s]

 42%|████▏     | 1994/4716 [13:49<18:44,  2.42it/s]

 42%|████▏     | 1995/4716 [13:50<18:42,  2.42it/s]

 42%|████▏     | 1996/4716 [13:50<18:42,  2.42it/s]

 42%|████▏     | 1997/4716 [13:51<18:43,  2.42it/s]

 42%|████▏     | 1998/4716 [13:51<18:44,  2.42it/s]

 42%|████▏     | 1999/4716 [13:51<18:43,  2.42it/s]

 42%|████▏     | 2000/4716 [13:52<18:42,  2.42it/s]

 42%|████▏     | 2001/4716 [13:52<18:42,  2.42it/s]

 42%|████▏     | 2002/4716 [13:53<18:41,  2.42it/s]

 42%|████▏     | 2003/4716 [13:53<18:39,  2.42it/s]

 42%|████▏     | 2004/4716 [13:54<18:39,  2.42it/s]

 43%|████▎     | 2005/4716 [13:54<18:38,  2.42it/s]

 43%|████▎     | 2006/4716 [13:54<18:36,  2.43it/s]

 43%|████▎     | 2007/4716 [13:55<18:40,  2.42it/s]

 43%|████▎     | 2008/4716 [13:55<18:40,  2.42it/s]

 43%|████▎     | 2009/4716 [13:56<18:38,  2.42it/s]

 43%|████▎     | 2010/4716 [13:56<18:38,  2.42it/s]

 43%|████▎     | 2011/4716 [13:56<18:37,  2.42it/s]

 43%|████▎     | 2012/4716 [13:57<18:36,  2.42it/s]

 43%|████▎     | 2013/4716 [13:57<18:34,  2.43it/s]

 43%|████▎     | 2014/4716 [13:58<18:34,  2.43it/s]

 43%|████▎     | 2015/4716 [13:58<18:32,  2.43it/s]

 43%|████▎     | 2016/4716 [13:58<18:34,  2.42it/s]

 43%|████▎     | 2017/4716 [13:59<18:35,  2.42it/s]

 43%|████▎     | 2018/4716 [13:59<18:34,  2.42it/s]

 43%|████▎     | 2019/4716 [14:00<18:33,  2.42it/s]

 43%|████▎     | 2020/4716 [14:00<18:32,  2.42it/s]

 43%|████▎     | 2021/4716 [14:01<18:35,  2.42it/s]

 43%|████▎     | 2022/4716 [14:01<18:33,  2.42it/s]

 43%|████▎     | 2023/4716 [14:01<18:31,  2.42it/s]

 43%|████▎     | 2024/4716 [14:02<18:31,  2.42it/s]

 43%|████▎     | 2025/4716 [14:02<18:31,  2.42it/s]

 43%|████▎     | 2026/4716 [14:03<18:29,  2.42it/s]

 43%|████▎     | 2027/4716 [14:03<18:29,  2.42it/s]

 43%|████▎     | 2028/4716 [14:03<18:28,  2.42it/s]

 43%|████▎     | 2029/4716 [14:04<18:28,  2.43it/s]

 43%|████▎     | 2030/4716 [14:04<18:28,  2.42it/s]

 43%|████▎     | 2031/4716 [14:05<18:26,  2.43it/s]

 43%|████▎     | 2032/4716 [14:05<18:26,  2.43it/s]

 43%|████▎     | 2033/4716 [14:05<18:25,  2.43it/s]

 43%|████▎     | 2034/4716 [14:06<18:28,  2.42it/s]

 43%|████▎     | 2035/4716 [14:06<18:26,  2.42it/s]

 43%|████▎     | 2036/4716 [14:07<18:25,  2.42it/s]

 43%|████▎     | 2037/4716 [14:07<18:24,  2.43it/s]

 43%|████▎     | 2038/4716 [14:08<18:23,  2.43it/s]

 43%|████▎     | 2039/4716 [14:08<18:22,  2.43it/s]

 43%|████▎     | 2040/4716 [14:08<18:22,  2.43it/s]

 43%|████▎     | 2041/4716 [14:09<18:23,  2.42it/s]

 43%|████▎     | 2042/4716 [14:09<18:22,  2.42it/s]

 43%|████▎     | 2043/4716 [14:10<18:22,  2.43it/s]

 43%|████▎     | 2044/4716 [14:10<18:21,  2.43it/s]

 43%|████▎     | 2045/4716 [14:10<18:22,  2.42it/s]

 43%|████▎     | 2046/4716 [14:11<18:20,  2.43it/s]

 43%|████▎     | 2047/4716 [14:11<18:19,  2.43it/s]

 43%|████▎     | 2048/4716 [14:12<18:19,  2.43it/s]

 43%|████▎     | 2049/4716 [14:12<18:19,  2.43it/s]

 43%|████▎     | 2050/4716 [14:13<18:18,  2.43it/s]

 43%|████▎     | 2051/4716 [14:13<18:19,  2.42it/s]

 44%|████▎     | 2052/4716 [14:13<18:19,  2.42it/s]

 44%|████▎     | 2053/4716 [14:14<18:18,  2.42it/s]

 44%|████▎     | 2054/4716 [14:14<18:17,  2.43it/s]

 44%|████▎     | 2055/4716 [14:15<18:16,  2.43it/s]

 44%|████▎     | 2056/4716 [14:15<18:16,  2.43it/s]

 44%|████▎     | 2057/4716 [14:15<18:15,  2.43it/s]

 44%|████▎     | 2058/4716 [14:16<18:15,  2.43it/s]

 44%|████▎     | 2059/4716 [14:16<18:14,  2.43it/s]

 44%|████▎     | 2060/4716 [14:17<18:15,  2.42it/s]

 44%|████▎     | 2061/4716 [14:17<18:14,  2.43it/s]

 44%|████▎     | 2062/4716 [14:17<18:13,  2.43it/s]

 44%|████▎     | 2063/4716 [14:18<18:13,  2.43it/s]

 44%|████▍     | 2064/4716 [14:18<18:13,  2.42it/s]

 44%|████▍     | 2065/4716 [14:19<18:13,  2.42it/s]

 44%|████▍     | 2066/4716 [14:19<18:13,  2.42it/s]

 44%|████▍     | 2067/4716 [14:20<18:13,  2.42it/s]

 44%|████▍     | 2068/4716 [14:20<18:14,  2.42it/s]

 44%|████▍     | 2069/4716 [14:20<18:13,  2.42it/s]

 44%|████▍     | 2070/4716 [14:21<18:14,  2.42it/s]

 44%|████▍     | 2071/4716 [14:21<18:16,  2.41it/s]

 44%|████▍     | 2072/4716 [14:22<18:14,  2.42it/s]

 44%|████▍     | 2073/4716 [14:22<18:14,  2.42it/s]

 44%|████▍     | 2074/4716 [14:22<18:13,  2.42it/s]

 44%|████▍     | 2075/4716 [14:23<18:13,  2.42it/s]

 44%|████▍     | 2076/4716 [14:23<18:11,  2.42it/s]

 44%|████▍     | 2077/4716 [14:24<18:11,  2.42it/s]

 44%|████▍     | 2078/4716 [14:24<18:11,  2.42it/s]

 44%|████▍     | 2079/4716 [14:24<18:10,  2.42it/s]

 44%|████▍     | 2080/4716 [14:25<18:10,  2.42it/s]

 44%|████▍     | 2081/4716 [14:25<18:09,  2.42it/s]

 44%|████▍     | 2082/4716 [14:26<18:10,  2.42it/s]

 44%|████▍     | 2083/4716 [14:26<18:10,  2.42it/s]

 44%|████▍     | 2084/4716 [14:27<18:09,  2.42it/s]

 44%|████▍     | 2085/4716 [14:27<18:08,  2.42it/s]

 44%|████▍     | 2086/4716 [14:27<18:07,  2.42it/s]

 44%|████▍     | 2087/4716 [14:28<18:06,  2.42it/s]

 44%|████▍     | 2088/4716 [14:28<18:06,  2.42it/s]

 44%|████▍     | 2089/4716 [14:29<18:05,  2.42it/s]

 44%|████▍     | 2090/4716 [14:29<18:05,  2.42it/s]

 44%|████▍     | 2091/4716 [14:29<18:05,  2.42it/s]

 44%|████▍     | 2092/4716 [14:30<18:06,  2.41it/s]

 44%|████▍     | 2093/4716 [14:30<18:05,  2.42it/s]

 44%|████▍     | 2094/4716 [14:31<18:04,  2.42it/s]

 44%|████▍     | 2095/4716 [14:31<18:04,  2.42it/s]

 44%|████▍     | 2096/4716 [14:32<18:03,  2.42it/s]

 44%|████▍     | 2097/4716 [14:32<18:02,  2.42it/s]

 44%|████▍     | 2098/4716 [14:32<18:03,  2.42it/s]

 45%|████▍     | 2099/4716 [14:33<18:01,  2.42it/s]

 45%|████▍     | 2100/4716 [14:33<18:01,  2.42it/s]

 45%|████▍     | 2101/4716 [14:34<17:59,  2.42it/s]

 45%|████▍     | 2102/4716 [14:34<17:59,  2.42it/s]

 45%|████▍     | 2103/4716 [14:34<17:58,  2.42it/s]

 45%|████▍     | 2104/4716 [14:35<17:58,  2.42it/s]

 45%|████▍     | 2105/4716 [14:35<17:57,  2.42it/s]

 45%|████▍     | 2106/4716 [14:36<17:56,  2.42it/s]

 45%|████▍     | 2107/4716 [14:36<17:57,  2.42it/s]

 45%|████▍     | 2108/4716 [14:36<17:57,  2.42it/s]

 45%|████▍     | 2109/4716 [14:37<17:57,  2.42it/s]

 45%|████▍     | 2110/4716 [14:37<17:56,  2.42it/s]

 45%|████▍     | 2111/4716 [14:38<17:56,  2.42it/s]

 45%|████▍     | 2112/4716 [14:38<17:54,  2.42it/s]

 45%|████▍     | 2113/4716 [14:39<17:55,  2.42it/s]

 45%|████▍     | 2114/4716 [14:39<17:54,  2.42it/s]

 45%|████▍     | 2115/4716 [14:39<17:54,  2.42it/s]

 45%|████▍     | 2116/4716 [14:40<17:54,  2.42it/s]

 45%|████▍     | 2117/4716 [14:40<17:54,  2.42it/s]

 45%|████▍     | 2118/4716 [14:41<17:53,  2.42it/s]

 45%|████▍     | 2119/4716 [14:41<17:52,  2.42it/s]

 45%|████▍     | 2120/4716 [14:41<17:58,  2.41it/s]

 45%|████▍     | 2121/4716 [14:42<17:55,  2.41it/s]

 45%|████▍     | 2122/4716 [14:42<17:54,  2.41it/s]

 45%|████▌     | 2123/4716 [14:43<17:52,  2.42it/s]

 45%|████▌     | 2124/4716 [14:43<17:52,  2.42it/s]

 45%|████▌     | 2125/4716 [14:44<17:53,  2.41it/s]

 45%|████▌     | 2126/4716 [14:44<17:53,  2.41it/s]

 45%|████▌     | 2127/4716 [14:44<17:52,  2.41it/s]

 45%|████▌     | 2128/4716 [14:45<17:54,  2.41it/s]

 45%|████▌     | 2129/4716 [14:45<17:52,  2.41it/s]

 45%|████▌     | 2130/4716 [14:46<17:50,  2.42it/s]

 45%|████▌     | 2131/4716 [14:46<17:49,  2.42it/s]

 45%|████▌     | 2132/4716 [14:46<17:48,  2.42it/s]

 45%|████▌     | 2133/4716 [14:47<17:48,  2.42it/s]

 45%|████▌     | 2134/4716 [14:47<17:48,  2.42it/s]

 45%|████▌     | 2135/4716 [14:48<17:48,  2.42it/s]

 45%|████▌     | 2136/4716 [14:48<17:47,  2.42it/s]

 45%|████▌     | 2137/4716 [14:48<17:47,  2.42it/s]

 45%|████▌     | 2138/4716 [14:49<17:47,  2.42it/s]

 45%|████▌     | 2139/4716 [14:49<17:46,  2.42it/s]

 45%|████▌     | 2140/4716 [14:50<17:46,  2.41it/s]

 45%|████▌     | 2141/4716 [14:50<17:47,  2.41it/s]

 45%|████▌     | 2142/4716 [14:51<17:46,  2.41it/s]

 45%|████▌     | 2143/4716 [14:51<17:45,  2.41it/s]

 45%|████▌     | 2144/4716 [14:51<17:43,  2.42it/s]

 45%|████▌     | 2145/4716 [14:52<17:44,  2.41it/s]

 46%|████▌     | 2146/4716 [14:52<17:42,  2.42it/s]

 46%|████▌     | 2147/4716 [14:53<17:43,  2.42it/s]

 46%|████▌     | 2148/4716 [14:53<17:42,  2.42it/s]

 46%|████▌     | 2149/4716 [14:53<17:41,  2.42it/s]

 46%|████▌     | 2150/4716 [14:54<17:42,  2.42it/s]

 46%|████▌     | 2151/4716 [14:54<17:41,  2.42it/s]

 46%|████▌     | 2152/4716 [14:55<17:39,  2.42it/s]

 46%|████▌     | 2153/4716 [14:55<17:39,  2.42it/s]

 46%|████▌     | 2154/4716 [14:56<17:38,  2.42it/s]

 46%|████▌     | 2155/4716 [14:56<17:38,  2.42it/s]

 46%|████▌     | 2156/4716 [14:56<17:39,  2.42it/s]

 46%|████▌     | 2157/4716 [14:57<17:38,  2.42it/s]

 46%|████▌     | 2158/4716 [14:57<17:39,  2.41it/s]

 46%|████▌     | 2159/4716 [14:58<17:38,  2.41it/s]

 46%|████▌     | 2160/4716 [14:58<17:38,  2.42it/s]

 46%|████▌     | 2161/4716 [14:58<17:37,  2.42it/s]

 46%|████▌     | 2162/4716 [14:59<17:37,  2.41it/s]

 46%|████▌     | 2163/4716 [14:59<17:36,  2.42it/s]

 46%|████▌     | 2164/4716 [15:00<17:36,  2.42it/s]

 46%|████▌     | 2165/4716 [15:00<17:36,  2.41it/s]

 46%|████▌     | 2166/4716 [15:00<17:35,  2.42it/s]

 46%|████▌     | 2167/4716 [15:01<17:35,  2.41it/s]

 46%|████▌     | 2168/4716 [15:01<17:36,  2.41it/s]

 46%|████▌     | 2169/4716 [15:02<17:35,  2.41it/s]

 46%|████▌     | 2170/4716 [15:02<17:34,  2.41it/s]

 46%|████▌     | 2171/4716 [15:03<17:33,  2.42it/s]

 46%|████▌     | 2172/4716 [15:03<17:33,  2.41it/s]

 46%|████▌     | 2173/4716 [15:03<17:34,  2.41it/s]

 46%|████▌     | 2174/4716 [15:04<17:33,  2.41it/s]

 46%|████▌     | 2175/4716 [15:04<17:33,  2.41it/s]

 46%|████▌     | 2176/4716 [15:05<17:31,  2.41it/s]

 46%|████▌     | 2177/4716 [15:05<17:32,  2.41it/s]

 46%|████▌     | 2178/4716 [15:05<17:31,  2.41it/s]

 46%|████▌     | 2179/4716 [15:06<17:30,  2.42it/s]

 46%|████▌     | 2180/4716 [15:06<17:28,  2.42it/s]

 46%|████▌     | 2181/4716 [15:07<17:29,  2.42it/s]

 46%|████▋     | 2182/4716 [15:07<17:30,  2.41it/s]

 46%|████▋     | 2183/4716 [15:08<17:30,  2.41it/s]

 46%|████▋     | 2184/4716 [15:08<17:31,  2.41it/s]

 46%|████▋     | 2185/4716 [15:08<17:30,  2.41it/s]

 46%|████▋     | 2186/4716 [15:09<17:28,  2.41it/s]

 46%|████▋     | 2187/4716 [15:09<17:26,  2.42it/s]

 46%|████▋     | 2188/4716 [15:10<17:26,  2.42it/s]

 46%|████▋     | 2189/4716 [15:10<17:25,  2.42it/s]

 46%|████▋     | 2190/4716 [15:10<17:25,  2.42it/s]

 46%|████▋     | 2191/4716 [15:11<17:26,  2.41it/s]

 46%|████▋     | 2192/4716 [15:11<17:26,  2.41it/s]

 47%|████▋     | 2193/4716 [15:12<17:25,  2.41it/s]

 47%|████▋     | 2194/4716 [15:12<17:26,  2.41it/s]

 47%|████▋     | 2195/4716 [15:12<17:25,  2.41it/s]

 47%|████▋     | 2196/4716 [15:13<17:25,  2.41it/s]

 47%|████▋     | 2197/4716 [15:13<17:23,  2.41it/s]

 47%|████▋     | 2198/4716 [15:14<17:24,  2.41it/s]

 47%|████▋     | 2199/4716 [15:14<17:23,  2.41it/s]

 47%|████▋     | 2200/4716 [15:15<17:23,  2.41it/s]

 47%|████▋     | 2201/4716 [15:15<17:22,  2.41it/s]

 47%|████▋     | 2202/4716 [15:15<17:22,  2.41it/s]

 47%|████▋     | 2203/4716 [15:16<17:28,  2.40it/s]

 47%|████▋     | 2204/4716 [15:16<17:25,  2.40it/s]

 47%|████▋     | 2205/4716 [15:17<17:23,  2.41it/s]

 47%|████▋     | 2206/4716 [15:17<17:23,  2.41it/s]

 47%|████▋     | 2207/4716 [15:17<17:21,  2.41it/s]

 47%|████▋     | 2208/4716 [15:18<17:19,  2.41it/s]

 47%|████▋     | 2209/4716 [15:18<17:19,  2.41it/s]

 47%|████▋     | 2210/4716 [15:19<17:19,  2.41it/s]

 47%|████▋     | 2211/4716 [15:19<17:19,  2.41it/s]

 47%|████▋     | 2212/4716 [15:20<17:18,  2.41it/s]

 47%|████▋     | 2213/4716 [15:20<17:19,  2.41it/s]

 47%|████▋     | 2214/4716 [15:20<17:17,  2.41it/s]

 47%|████▋     | 2215/4716 [15:21<17:18,  2.41it/s]

 47%|████▋     | 2216/4716 [15:21<17:16,  2.41it/s]

 47%|████▋     | 2217/4716 [15:22<17:16,  2.41it/s]

 47%|████▋     | 2218/4716 [15:22<17:15,  2.41it/s]

 47%|████▋     | 2219/4716 [15:22<17:15,  2.41it/s]

 47%|████▋     | 2220/4716 [15:23<17:14,  2.41it/s]

 47%|████▋     | 2221/4716 [15:23<17:14,  2.41it/s]

 47%|████▋     | 2222/4716 [15:24<17:13,  2.41it/s]

 47%|████▋     | 2223/4716 [15:24<17:12,  2.41it/s]

 47%|████▋     | 2224/4716 [15:25<17:12,  2.41it/s]

 47%|████▋     | 2225/4716 [15:25<17:12,  2.41it/s]

 47%|████▋     | 2226/4716 [15:25<17:12,  2.41it/s]

 47%|████▋     | 2227/4716 [15:26<17:11,  2.41it/s]

 47%|████▋     | 2228/4716 [15:26<17:11,  2.41it/s]

 47%|████▋     | 2229/4716 [15:27<17:10,  2.41it/s]

 47%|████▋     | 2230/4716 [15:27<17:10,  2.41it/s]

 47%|████▋     | 2231/4716 [15:27<17:09,  2.41it/s]

 47%|████▋     | 2232/4716 [15:28<17:10,  2.41it/s]

 47%|████▋     | 2233/4716 [15:28<17:10,  2.41it/s]

 47%|████▋     | 2234/4716 [15:29<17:10,  2.41it/s]

 47%|████▋     | 2235/4716 [15:29<17:10,  2.41it/s]

 47%|████▋     | 2236/4716 [15:30<17:09,  2.41it/s]

 47%|████▋     | 2237/4716 [15:30<17:08,  2.41it/s]

 47%|████▋     | 2238/4716 [15:30<17:09,  2.41it/s]

 47%|████▋     | 2239/4716 [15:31<17:08,  2.41it/s]

 47%|████▋     | 2240/4716 [15:31<17:09,  2.40it/s]

 48%|████▊     | 2241/4716 [15:32<17:07,  2.41it/s]

 48%|████▊     | 2242/4716 [15:32<17:07,  2.41it/s]

 48%|████▊     | 2243/4716 [15:32<17:07,  2.41it/s]

 48%|████▊     | 2244/4716 [15:33<17:08,  2.40it/s]

 48%|████▊     | 2245/4716 [15:33<17:07,  2.40it/s]

 48%|████▊     | 2246/4716 [15:34<17:07,  2.40it/s]

 48%|████▊     | 2247/4716 [15:34<17:07,  2.40it/s]

 48%|████▊     | 2248/4716 [15:34<17:06,  2.40it/s]

 48%|████▊     | 2249/4716 [15:35<17:05,  2.41it/s]

 48%|████▊     | 2250/4716 [15:35<17:04,  2.41it/s]

 48%|████▊     | 2251/4716 [15:36<17:02,  2.41it/s]

 48%|████▊     | 2252/4716 [15:36<17:02,  2.41it/s]

 48%|████▊     | 2253/4716 [15:37<17:03,  2.41it/s]

 48%|████▊     | 2254/4716 [15:37<17:02,  2.41it/s]

 48%|████▊     | 2255/4716 [15:37<17:01,  2.41it/s]

 48%|████▊     | 2256/4716 [15:38<17:01,  2.41it/s]

 48%|████▊     | 2257/4716 [15:38<17:00,  2.41it/s]

 48%|████▊     | 2258/4716 [15:39<17:01,  2.41it/s]

 48%|████▊     | 2259/4716 [15:39<17:03,  2.40it/s]

 48%|████▊     | 2260/4716 [15:39<17:02,  2.40it/s]

 48%|████▊     | 2261/4716 [15:40<17:00,  2.41it/s]

 48%|████▊     | 2262/4716 [15:40<16:58,  2.41it/s]

 48%|████▊     | 2263/4716 [15:41<16:58,  2.41it/s]

 48%|████▊     | 2264/4716 [15:41<16:58,  2.41it/s]

 48%|████▊     | 2265/4716 [15:42<16:57,  2.41it/s]

 48%|████▊     | 2266/4716 [15:42<16:56,  2.41it/s]

 48%|████▊     | 2267/4716 [15:42<16:57,  2.41it/s]

 48%|████▊     | 2268/4716 [15:43<16:56,  2.41it/s]

 48%|████▊     | 2269/4716 [15:43<16:56,  2.41it/s]

 48%|████▊     | 2270/4716 [15:44<16:56,  2.41it/s]

 48%|████▊     | 2271/4716 [15:44<16:54,  2.41it/s]

 48%|████▊     | 2272/4716 [15:44<16:54,  2.41it/s]

 48%|████▊     | 2273/4716 [15:45<16:55,  2.41it/s]

 48%|████▊     | 2274/4716 [15:45<16:54,  2.41it/s]

 48%|████▊     | 2275/4716 [15:46<16:53,  2.41it/s]

 48%|████▊     | 2276/4716 [15:46<16:53,  2.41it/s]

 48%|████▊     | 2277/4716 [15:47<16:52,  2.41it/s]

 48%|████▊     | 2278/4716 [15:47<16:52,  2.41it/s]

 48%|████▊     | 2279/4716 [15:47<16:53,  2.41it/s]

 48%|████▊     | 2280/4716 [15:48<16:53,  2.40it/s]

 48%|████▊     | 2281/4716 [15:48<16:52,  2.41it/s]

 48%|████▊     | 2282/4716 [15:49<16:51,  2.41it/s]

 48%|████▊     | 2283/4716 [15:49<16:50,  2.41it/s]

 48%|████▊     | 2284/4716 [15:49<16:50,  2.41it/s]

 48%|████▊     | 2285/4716 [15:50<16:48,  2.41it/s]

 48%|████▊     | 2286/4716 [15:50<16:49,  2.41it/s]

 48%|████▊     | 2287/4716 [15:51<16:48,  2.41it/s]

 49%|████▊     | 2288/4716 [15:51<16:48,  2.41it/s]

 49%|████▊     | 2289/4716 [15:52<16:47,  2.41it/s]

 49%|████▊     | 2290/4716 [15:52<16:48,  2.41it/s]

 49%|████▊     | 2291/4716 [15:52<16:47,  2.41it/s]

 49%|████▊     | 2292/4716 [15:53<16:47,  2.41it/s]

 49%|████▊     | 2293/4716 [15:53<16:45,  2.41it/s]

 49%|████▊     | 2294/4716 [15:54<16:46,  2.41it/s]

 49%|████▊     | 2295/4716 [15:54<16:46,  2.41it/s]

 49%|████▊     | 2296/4716 [15:54<16:45,  2.41it/s]

 49%|████▊     | 2297/4716 [15:55<16:45,  2.41it/s]

 49%|████▊     | 2298/4716 [15:55<16:45,  2.41it/s]

 49%|████▊     | 2299/4716 [15:56<16:43,  2.41it/s]

 49%|████▉     | 2300/4716 [15:56<16:44,  2.41it/s]

 49%|████▉     | 2301/4716 [15:57<16:44,  2.40it/s]

 49%|████▉     | 2302/4716 [15:57<16:43,  2.40it/s]

 49%|████▉     | 2303/4716 [15:57<16:42,  2.41it/s]

 49%|████▉     | 2304/4716 [15:58<16:43,  2.40it/s]

 49%|████▉     | 2305/4716 [15:58<16:42,  2.40it/s]

 49%|████▉     | 2306/4716 [15:59<16:41,  2.41it/s]

 49%|████▉     | 2307/4716 [15:59<16:43,  2.40it/s]

 49%|████▉     | 2308/4716 [15:59<16:42,  2.40it/s]

 49%|████▉     | 2309/4716 [16:00<16:40,  2.41it/s]

 49%|████▉     | 2310/4716 [16:00<16:40,  2.41it/s]

 49%|████▉     | 2311/4716 [16:01<16:40,  2.40it/s]

 49%|████▉     | 2312/4716 [16:01<16:38,  2.41it/s]

 49%|████▉     | 2313/4716 [16:01<16:39,  2.40it/s]

 49%|████▉     | 2314/4716 [16:02<16:38,  2.41it/s]

 49%|████▉     | 2315/4716 [16:02<16:38,  2.41it/s]

 49%|████▉     | 2316/4716 [16:03<16:36,  2.41it/s]

 49%|████▉     | 2317/4716 [16:03<16:36,  2.41it/s]

 49%|████▉     | 2318/4716 [16:04<16:35,  2.41it/s]

 49%|████▉     | 2319/4716 [16:04<16:36,  2.41it/s]

 49%|████▉     | 2320/4716 [16:04<16:36,  2.40it/s]

 49%|████▉     | 2321/4716 [16:05<16:36,  2.40it/s]

 49%|████▉     | 2322/4716 [16:05<16:37,  2.40it/s]

 49%|████▉     | 2323/4716 [16:06<16:37,  2.40it/s]

 49%|████▉     | 2324/4716 [16:06<16:35,  2.40it/s]

 49%|████▉     | 2325/4716 [16:06<16:34,  2.40it/s]

 49%|████▉     | 2326/4716 [16:07<16:34,  2.40it/s]

 49%|████▉     | 2327/4716 [16:07<16:33,  2.40it/s]

 49%|████▉     | 2328/4716 [16:08<16:33,  2.40it/s]

 49%|████▉     | 2329/4716 [16:08<16:32,  2.40it/s]

 49%|████▉     | 2330/4716 [16:09<16:33,  2.40it/s]

 49%|████▉     | 2331/4716 [16:09<16:32,  2.40it/s]

 49%|████▉     | 2332/4716 [16:09<16:31,  2.40it/s]

 49%|████▉     | 2333/4716 [16:10<16:31,  2.40it/s]

 49%|████▉     | 2334/4716 [16:10<16:31,  2.40it/s]

 50%|████▉     | 2335/4716 [16:11<16:30,  2.40it/s]

 50%|████▉     | 2336/4716 [16:11<16:28,  2.41it/s]

 50%|████▉     | 2337/4716 [16:11<16:28,  2.41it/s]

 50%|████▉     | 2338/4716 [16:12<16:29,  2.40it/s]

 50%|████▉     | 2339/4716 [16:12<16:28,  2.41it/s]

 50%|████▉     | 2340/4716 [16:13<16:27,  2.40it/s]

 50%|████▉     | 2341/4716 [16:13<16:27,  2.40it/s]

 50%|████▉     | 2342/4716 [16:14<16:28,  2.40it/s]

 50%|████▉     | 2343/4716 [16:14<16:27,  2.40it/s]

 50%|████▉     | 2344/4716 [16:14<16:26,  2.40it/s]

 50%|████▉     | 2345/4716 [16:15<16:26,  2.40it/s]

 50%|████▉     | 2346/4716 [16:15<16:25,  2.40it/s]

 50%|████▉     | 2347/4716 [16:16<16:24,  2.41it/s]

 50%|████▉     | 2348/4716 [16:16<16:24,  2.41it/s]

 50%|████▉     | 2349/4716 [16:16<16:24,  2.40it/s]

 50%|████▉     | 2350/4716 [16:17<16:23,  2.41it/s]

 50%|████▉     | 2351/4716 [16:17<16:22,  2.41it/s]

 50%|████▉     | 2352/4716 [16:18<16:22,  2.40it/s]

 50%|████▉     | 2353/4716 [16:18<16:22,  2.40it/s]

 50%|████▉     | 2354/4716 [16:19<16:21,  2.41it/s]

 50%|████▉     | 2355/4716 [16:19<16:20,  2.41it/s]

 50%|████▉     | 2356/4716 [16:19<16:20,  2.41it/s]

 50%|████▉     | 2357/4716 [16:20<16:21,  2.40it/s]

 50%|█████     | 2358/4716 [16:20<16:21,  2.40it/s]

 50%|█████     | 2359/4716 [16:21<16:20,  2.40it/s]

 50%|█████     | 2360/4716 [16:21<16:19,  2.40it/s]

 50%|█████     | 2361/4716 [16:21<16:19,  2.40it/s]

 50%|█████     | 2362/4716 [16:22<16:17,  2.41it/s]

 50%|█████     | 2363/4716 [16:22<16:18,  2.40it/s]

 50%|█████     | 2364/4716 [16:23<16:18,  2.40it/s]

 50%|█████     | 2365/4716 [16:23<16:17,  2.40it/s]

 50%|█████     | 2366/4716 [16:24<16:17,  2.40it/s]

 50%|█████     | 2367/4716 [16:24<16:17,  2.40it/s]

 50%|█████     | 2368/4716 [16:24<16:17,  2.40it/s]

 50%|█████     | 2369/4716 [16:25<16:16,  2.40it/s]

 50%|█████     | 2370/4716 [16:25<16:17,  2.40it/s]

 50%|█████     | 2371/4716 [16:26<16:16,  2.40it/s]

 50%|█████     | 2372/4716 [16:26<16:16,  2.40it/s]

 50%|█████     | 2373/4716 [16:26<16:17,  2.40it/s]

 50%|█████     | 2374/4716 [16:27<16:16,  2.40it/s]

 50%|█████     | 2375/4716 [16:27<16:15,  2.40it/s]

 50%|█████     | 2376/4716 [16:28<16:16,  2.40it/s]

 50%|█████     | 2377/4716 [16:28<16:14,  2.40it/s]

 50%|█████     | 2378/4716 [16:29<16:18,  2.39it/s]

 50%|█████     | 2379/4716 [16:29<16:17,  2.39it/s]

 50%|█████     | 2380/4716 [16:29<16:18,  2.39it/s]

 50%|█████     | 2381/4716 [16:30<16:15,  2.39it/s]

 51%|█████     | 2382/4716 [16:30<16:14,  2.39it/s]

 51%|█████     | 2383/4716 [16:31<16:13,  2.40it/s]

 51%|█████     | 2384/4716 [16:31<16:12,  2.40it/s]

 51%|█████     | 2385/4716 [16:31<16:10,  2.40it/s]

 51%|█████     | 2386/4716 [16:32<16:10,  2.40it/s]

 51%|█████     | 2387/4716 [16:32<16:11,  2.40it/s]

 51%|█████     | 2388/4716 [16:33<16:10,  2.40it/s]

 51%|█████     | 2389/4716 [16:33<16:09,  2.40it/s]

 51%|█████     | 2390/4716 [16:34<16:10,  2.40it/s]

 51%|█████     | 2391/4716 [16:34<16:09,  2.40it/s]

 51%|█████     | 2392/4716 [16:34<16:10,  2.39it/s]

 51%|█████     | 2393/4716 [16:35<16:08,  2.40it/s]

 51%|█████     | 2394/4716 [16:35<16:09,  2.40it/s]

 51%|█████     | 2395/4716 [16:36<16:06,  2.40it/s]

 51%|█████     | 2396/4716 [16:36<16:06,  2.40it/s]

 51%|█████     | 2397/4716 [16:36<16:07,  2.40it/s]

 51%|█████     | 2398/4716 [16:37<16:08,  2.39it/s]

 51%|█████     | 2399/4716 [16:37<16:06,  2.40it/s]

 51%|█████     | 2400/4716 [16:38<16:07,  2.39it/s]

 51%|█████     | 2401/4716 [16:38<16:05,  2.40it/s]

 51%|█████     | 2402/4716 [16:39<16:06,  2.39it/s]

 51%|█████     | 2403/4716 [16:39<16:05,  2.40it/s]

 51%|█████     | 2404/4716 [16:39<16:04,  2.40it/s]

 51%|█████     | 2405/4716 [16:40<16:04,  2.40it/s]

 51%|█████     | 2406/4716 [16:40<16:02,  2.40it/s]

 51%|█████     | 2407/4716 [16:41<16:03,  2.40it/s]

 51%|█████     | 2408/4716 [16:41<16:02,  2.40it/s]

 51%|█████     | 2409/4716 [16:41<16:03,  2.39it/s]

 51%|█████     | 2410/4716 [16:42<16:02,  2.40it/s]

 51%|█████     | 2411/4716 [16:42<16:01,  2.40it/s]

 51%|█████     | 2412/4716 [16:43<16:00,  2.40it/s]

 51%|█████     | 2413/4716 [16:43<16:00,  2.40it/s]

 51%|█████     | 2414/4716 [16:44<15:59,  2.40it/s]

 51%|█████     | 2415/4716 [16:44<15:57,  2.40it/s]

 51%|█████     | 2416/4716 [16:44<15:57,  2.40it/s]

 51%|█████▏    | 2417/4716 [16:45<15:57,  2.40it/s]

 51%|█████▏    | 2418/4716 [16:45<15:57,  2.40it/s]

 51%|█████▏    | 2419/4716 [16:46<15:56,  2.40it/s]

 51%|█████▏    | 2420/4716 [16:46<15:56,  2.40it/s]

 51%|█████▏    | 2421/4716 [16:46<15:56,  2.40it/s]

 51%|█████▏    | 2422/4716 [16:47<15:55,  2.40it/s]

 51%|█████▏    | 2423/4716 [16:47<15:55,  2.40it/s]

 51%|█████▏    | 2424/4716 [16:48<15:54,  2.40it/s]

 51%|█████▏    | 2425/4716 [16:48<15:54,  2.40it/s]

 51%|█████▏    | 2426/4716 [16:49<15:53,  2.40it/s]

 51%|█████▏    | 2427/4716 [16:49<15:53,  2.40it/s]

 51%|█████▏    | 2428/4716 [16:49<15:51,  2.40it/s]

 52%|█████▏    | 2429/4716 [16:50<15:51,  2.40it/s]

 52%|█████▏    | 2430/4716 [16:50<15:52,  2.40it/s]

 52%|█████▏    | 2431/4716 [16:51<15:51,  2.40it/s]

 52%|█████▏    | 2432/4716 [16:51<15:51,  2.40it/s]

 52%|█████▏    | 2433/4716 [16:51<15:49,  2.40it/s]

 52%|█████▏    | 2434/4716 [16:52<15:51,  2.40it/s]

 52%|█████▏    | 2435/4716 [16:52<15:51,  2.40it/s]

 52%|█████▏    | 2436/4716 [16:53<15:52,  2.39it/s]

 52%|█████▏    | 2437/4716 [16:53<15:51,  2.40it/s]

 52%|█████▏    | 2438/4716 [16:54<15:49,  2.40it/s]

 52%|█████▏    | 2439/4716 [16:54<15:48,  2.40it/s]

 52%|█████▏    | 2440/4716 [16:54<15:49,  2.40it/s]

 52%|█████▏    | 2441/4716 [16:55<15:48,  2.40it/s]

 52%|█████▏    | 2442/4716 [16:55<15:48,  2.40it/s]

 52%|█████▏    | 2443/4716 [16:56<15:48,  2.40it/s]

 52%|█████▏    | 2444/4716 [16:56<15:47,  2.40it/s]

 52%|█████▏    | 2445/4716 [16:56<15:48,  2.39it/s]

 52%|█████▏    | 2446/4716 [16:57<15:47,  2.40it/s]

 52%|█████▏    | 2447/4716 [16:57<15:49,  2.39it/s]

 52%|█████▏    | 2448/4716 [16:58<15:47,  2.39it/s]

 52%|█████▏    | 2449/4716 [16:58<15:46,  2.40it/s]

 52%|█████▏    | 2450/4716 [16:59<15:44,  2.40it/s]

 52%|█████▏    | 2451/4716 [16:59<15:44,  2.40it/s]

 52%|█████▏    | 2452/4716 [16:59<15:43,  2.40it/s]

 52%|█████▏    | 2453/4716 [17:00<15:43,  2.40it/s]

 52%|█████▏    | 2454/4716 [17:00<15:43,  2.40it/s]

 52%|█████▏    | 2455/4716 [17:01<15:43,  2.40it/s]

 52%|█████▏    | 2456/4716 [17:01<15:42,  2.40it/s]

 52%|█████▏    | 2457/4716 [17:01<15:42,  2.40it/s]

 52%|█████▏    | 2458/4716 [17:02<15:41,  2.40it/s]

 52%|█████▏    | 2459/4716 [17:02<15:42,  2.39it/s]

 52%|█████▏    | 2460/4716 [17:03<15:42,  2.39it/s]

 52%|█████▏    | 2461/4716 [17:03<15:42,  2.39it/s]

 52%|█████▏    | 2462/4716 [17:04<15:41,  2.39it/s]

 52%|█████▏    | 2463/4716 [17:04<15:40,  2.40it/s]

 52%|█████▏    | 2464/4716 [17:04<15:41,  2.39it/s]

 52%|█████▏    | 2465/4716 [17:05<15:41,  2.39it/s]

 52%|█████▏    | 2466/4716 [17:05<15:39,  2.40it/s]

 52%|█████▏    | 2467/4716 [17:06<15:39,  2.39it/s]

 52%|█████▏    | 2468/4716 [17:06<15:38,  2.39it/s]

 52%|█████▏    | 2469/4716 [17:07<15:38,  2.39it/s]

 52%|█████▏    | 2470/4716 [17:07<15:36,  2.40it/s]

 52%|█████▏    | 2471/4716 [17:07<15:37,  2.40it/s]

 52%|█████▏    | 2472/4716 [17:08<15:36,  2.40it/s]

 52%|█████▏    | 2473/4716 [17:08<15:35,  2.40it/s]

 52%|█████▏    | 2474/4716 [17:09<15:35,  2.40it/s]

 52%|█████▏    | 2475/4716 [17:09<15:35,  2.39it/s]

 53%|█████▎    | 2476/4716 [17:09<15:34,  2.40it/s]

 53%|█████▎    | 2477/4716 [17:10<15:33,  2.40it/s]

 53%|█████▎    | 2478/4716 [17:10<15:34,  2.40it/s]

 53%|█████▎    | 2479/4716 [17:11<15:34,  2.39it/s]

 53%|█████▎    | 2480/4716 [17:11<15:32,  2.40it/s]

 53%|█████▎    | 2481/4716 [17:12<15:34,  2.39it/s]

 53%|█████▎    | 2482/4716 [17:12<15:33,  2.39it/s]

 53%|█████▎    | 2483/4716 [17:12<15:33,  2.39it/s]

 53%|█████▎    | 2484/4716 [17:13<15:32,  2.39it/s]

 53%|█████▎    | 2485/4716 [17:13<15:33,  2.39it/s]

 53%|█████▎    | 2486/4716 [17:14<15:32,  2.39it/s]

 53%|█████▎    | 2487/4716 [17:14<15:32,  2.39it/s]

 53%|█████▎    | 2488/4716 [17:14<15:31,  2.39it/s]

 53%|█████▎    | 2489/4716 [17:15<15:29,  2.40it/s]

 53%|█████▎    | 2490/4716 [17:15<15:27,  2.40it/s]

 53%|█████▎    | 2491/4716 [17:16<15:28,  2.40it/s]

 53%|█████▎    | 2492/4716 [17:16<15:34,  2.38it/s]

 53%|█████▎    | 2493/4716 [17:17<15:32,  2.38it/s]

 53%|█████▎    | 2494/4716 [17:17<15:31,  2.39it/s]

 53%|█████▎    | 2495/4716 [17:17<15:28,  2.39it/s]

 53%|█████▎    | 2496/4716 [17:18<15:28,  2.39it/s]

 53%|█████▎    | 2497/4716 [17:18<15:28,  2.39it/s]

 53%|█████▎    | 2498/4716 [17:19<15:27,  2.39it/s]

 53%|█████▎    | 2499/4716 [17:19<15:25,  2.40it/s]

 53%|█████▎    | 2500/4716 [17:19<15:26,  2.39it/s]

 53%|█████▎    | 2501/4716 [17:20<15:25,  2.39it/s]

 53%|█████▎    | 2502/4716 [17:20<15:25,  2.39it/s]

 53%|█████▎    | 2503/4716 [17:21<15:24,  2.39it/s]

logging
logging the anndata

 53%|█████▎    | 2504/4716 [17:21<16:00,  2.30it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 53%|█████▎    | 2505/4716 [17:22<15:45,  2.34it/s]

 53%|█████▎    | 2506/4716 [17:22<15:33,  2.37it/s]

 53%|█████▎    | 2507/4716 [17:22<15:25,  2.39it/s]

 53%|█████▎    | 2508/4716 [17:23<15:18,  2.40it/s]

 53%|█████▎    | 2509/4716 [17:23<15:14,  2.41it/s]

 53%|█████▎    | 2510/4716 [17:24<15:12,  2.42it/s]

 53%|█████▎    | 2511/4716 [17:24<15:09,  2.42it/s]

 53%|█████▎    | 2512/4716 [17:24<15:07,  2.43it/s]

 53%|█████▎    | 2513/4716 [17:25<15:06,  2.43it/s]

 53%|█████▎    | 2514/4716 [17:25<15:05,  2.43it/s]

 53%|█████▎    | 2515/4716 [17:26<15:03,  2.44it/s]

 53%|█████▎    | 2516/4716 [17:26<15:02,  2.44it/s]

 53%|█████▎    | 2517/4716 [17:27<15:01,  2.44it/s]

 53%|█████▎    | 2518/4716 [17:27<15:00,  2.44it/s]

 53%|█████▎    | 2519/4716 [17:27<15:00,  2.44it/s]

 53%|█████▎    | 2520/4716 [17:28<14:59,  2.44it/s]

 53%|█████▎    | 2521/4716 [17:28<14:59,  2.44it/s]

 53%|█████▎    | 2522/4716 [17:29<14:58,  2.44it/s]

 53%|█████▎    | 2523/4716 [17:29<14:58,  2.44it/s]

 54%|█████▎    | 2524/4716 [17:29<14:57,  2.44it/s]

 54%|█████▎    | 2525/4716 [17:30<14:58,  2.44it/s]

 54%|█████▎    | 2526/4716 [17:30<14:57,  2.44it/s]

 54%|█████▎    | 2527/4716 [17:31<14:57,  2.44it/s]

 54%|█████▎    | 2528/4716 [17:31<14:57,  2.44it/s]

 54%|█████▎    | 2529/4716 [17:31<14:56,  2.44it/s]

 54%|█████▎    | 2530/4716 [17:32<14:56,  2.44it/s]

 54%|█████▎    | 2531/4716 [17:32<14:55,  2.44it/s]

 54%|█████▎    | 2532/4716 [17:33<14:54,  2.44it/s]

 54%|█████▎    | 2533/4716 [17:33<14:55,  2.44it/s]

 54%|█████▎    | 2534/4716 [17:33<14:55,  2.44it/s]

 54%|█████▍    | 2535/4716 [17:34<14:54,  2.44it/s]

 54%|█████▍    | 2536/4716 [17:34<14:54,  2.44it/s]

 54%|█████▍    | 2537/4716 [17:35<14:54,  2.44it/s]

 54%|█████▍    | 2538/4716 [17:35<14:54,  2.44it/s]

 54%|█████▍    | 2539/4716 [17:36<14:53,  2.44it/s]

 54%|█████▍    | 2540/4716 [17:36<14:53,  2.44it/s]

 54%|█████▍    | 2541/4716 [17:36<14:52,  2.44it/s]

 54%|█████▍    | 2542/4716 [17:37<14:51,  2.44it/s]

 54%|█████▍    | 2543/4716 [17:37<14:51,  2.44it/s]

 54%|█████▍    | 2544/4716 [17:38<14:50,  2.44it/s]

 54%|█████▍    | 2545/4716 [17:38<14:49,  2.44it/s]

 54%|█████▍    | 2546/4716 [17:38<14:50,  2.44it/s]

 54%|█████▍    | 2547/4716 [17:39<14:51,  2.43it/s]

 54%|█████▍    | 2548/4716 [17:39<14:50,  2.43it/s]

 54%|█████▍    | 2549/4716 [17:40<14:49,  2.44it/s]

 54%|█████▍    | 2550/4716 [17:40<14:49,  2.44it/s]

 54%|█████▍    | 2551/4716 [17:40<14:48,  2.44it/s]

 54%|█████▍    | 2552/4716 [17:41<14:48,  2.44it/s]

 54%|█████▍    | 2553/4716 [17:41<14:48,  2.44it/s]

 54%|█████▍    | 2554/4716 [17:42<14:47,  2.44it/s]

 54%|█████▍    | 2555/4716 [17:42<14:46,  2.44it/s]

 54%|█████▍    | 2556/4716 [17:43<14:46,  2.44it/s]

 54%|█████▍    | 2557/4716 [17:43<14:47,  2.43it/s]

 54%|█████▍    | 2558/4716 [17:43<14:46,  2.43it/s]

 54%|█████▍    | 2559/4716 [17:44<14:46,  2.43it/s]

 54%|█████▍    | 2560/4716 [17:44<14:45,  2.43it/s]

 54%|█████▍    | 2561/4716 [17:45<14:46,  2.43it/s]

 54%|█████▍    | 2562/4716 [17:45<14:45,  2.43it/s]

 54%|█████▍    | 2563/4716 [17:45<14:44,  2.43it/s]

 54%|█████▍    | 2564/4716 [17:46<14:44,  2.43it/s]

 54%|█████▍    | 2565/4716 [17:46<14:44,  2.43it/s]

 54%|█████▍    | 2566/4716 [17:47<14:43,  2.43it/s]

 54%|█████▍    | 2567/4716 [17:47<14:42,  2.44it/s]

 54%|█████▍    | 2568/4716 [17:47<14:42,  2.44it/s]

 54%|█████▍    | 2569/4716 [17:48<14:41,  2.43it/s]

 54%|█████▍    | 2570/4716 [17:48<14:41,  2.44it/s]

 55%|█████▍    | 2571/4716 [17:49<14:41,  2.43it/s]

 55%|█████▍    | 2572/4716 [17:49<14:40,  2.44it/s]

 55%|█████▍    | 2573/4716 [17:50<14:40,  2.43it/s]

 55%|█████▍    | 2574/4716 [17:50<14:40,  2.43it/s]

 55%|█████▍    | 2575/4716 [17:50<14:39,  2.43it/s]

 55%|█████▍    | 2576/4716 [17:51<14:38,  2.44it/s]

 55%|█████▍    | 2577/4716 [17:51<14:37,  2.44it/s]

 55%|█████▍    | 2578/4716 [17:52<14:38,  2.43it/s]

 55%|█████▍    | 2579/4716 [17:52<14:37,  2.43it/s]

 55%|█████▍    | 2580/4716 [17:52<14:37,  2.43it/s]

 55%|█████▍    | 2581/4716 [17:53<14:37,  2.43it/s]

 55%|█████▍    | 2582/4716 [17:53<14:38,  2.43it/s]

 55%|█████▍    | 2583/4716 [17:54<14:38,  2.43it/s]

 55%|█████▍    | 2584/4716 [17:54<14:37,  2.43it/s]

 55%|█████▍    | 2585/4716 [17:54<14:37,  2.43it/s]

 55%|█████▍    | 2586/4716 [17:55<14:39,  2.42it/s]

 55%|█████▍    | 2587/4716 [17:55<14:37,  2.42it/s]

 55%|█████▍    | 2588/4716 [17:56<14:37,  2.43it/s]

 55%|█████▍    | 2589/4716 [17:56<14:36,  2.43it/s]

 55%|█████▍    | 2590/4716 [17:56<14:35,  2.43it/s]

 55%|█████▍    | 2591/4716 [17:57<14:35,  2.43it/s]

 55%|█████▍    | 2592/4716 [17:57<14:34,  2.43it/s]

 55%|█████▍    | 2593/4716 [17:58<14:34,  2.43it/s]

 55%|█████▌    | 2594/4716 [17:58<14:33,  2.43it/s]

 55%|█████▌    | 2595/4716 [17:59<14:32,  2.43it/s]

 55%|█████▌    | 2596/4716 [17:59<14:32,  2.43it/s]

 55%|█████▌    | 2597/4716 [17:59<14:32,  2.43it/s]

 55%|█████▌    | 2598/4716 [18:00<14:31,  2.43it/s]

 55%|█████▌    | 2599/4716 [18:00<14:31,  2.43it/s]

 55%|█████▌    | 2600/4716 [18:01<14:31,  2.43it/s]

 55%|█████▌    | 2601/4716 [18:01<14:30,  2.43it/s]

 55%|█████▌    | 2602/4716 [18:01<14:31,  2.43it/s]

 55%|█████▌    | 2603/4716 [18:02<14:29,  2.43it/s]

 55%|█████▌    | 2604/4716 [18:02<14:30,  2.43it/s]

 55%|█████▌    | 2605/4716 [18:03<14:29,  2.43it/s]

 55%|█████▌    | 2606/4716 [18:03<14:29,  2.43it/s]

 55%|█████▌    | 2607/4716 [18:03<14:28,  2.43it/s]

 55%|█████▌    | 2608/4716 [18:04<14:27,  2.43it/s]

 55%|█████▌    | 2609/4716 [18:04<14:28,  2.43it/s]

 55%|█████▌    | 2610/4716 [18:05<14:27,  2.43it/s]

 55%|█████▌    | 2611/4716 [18:05<14:26,  2.43it/s]

 55%|█████▌    | 2612/4716 [18:06<14:25,  2.43it/s]

 55%|█████▌    | 2613/4716 [18:06<14:26,  2.43it/s]

 55%|█████▌    | 2614/4716 [18:06<14:25,  2.43it/s]

 55%|█████▌    | 2615/4716 [18:07<14:26,  2.42it/s]

 55%|█████▌    | 2616/4716 [18:07<14:25,  2.43it/s]

 55%|█████▌    | 2617/4716 [18:08<14:25,  2.43it/s]

 56%|█████▌    | 2618/4716 [18:08<14:24,  2.43it/s]

 56%|█████▌    | 2619/4716 [18:08<14:26,  2.42it/s]

 56%|█████▌    | 2620/4716 [18:09<14:25,  2.42it/s]

 56%|█████▌    | 2621/4716 [18:09<14:25,  2.42it/s]

 56%|█████▌    | 2622/4716 [18:10<14:24,  2.42it/s]

 56%|█████▌    | 2623/4716 [18:10<14:23,  2.42it/s]

 56%|█████▌    | 2624/4716 [18:11<14:24,  2.42it/s]

 56%|█████▌    | 2625/4716 [18:11<14:22,  2.42it/s]

 56%|█████▌    | 2626/4716 [18:11<14:22,  2.42it/s]

 56%|█████▌    | 2627/4716 [18:12<14:20,  2.43it/s]

 56%|█████▌    | 2628/4716 [18:12<14:19,  2.43it/s]

 56%|█████▌    | 2629/4716 [18:13<14:20,  2.42it/s]

 56%|█████▌    | 2630/4716 [18:13<14:20,  2.43it/s]

 56%|█████▌    | 2631/4716 [18:13<14:19,  2.43it/s]

 56%|█████▌    | 2632/4716 [18:14<14:18,  2.43it/s]

 56%|█████▌    | 2633/4716 [18:14<14:19,  2.42it/s]

 56%|█████▌    | 2634/4716 [18:15<14:18,  2.43it/s]

 56%|█████▌    | 2635/4716 [18:15<14:18,  2.42it/s]

 56%|█████▌    | 2636/4716 [18:15<14:18,  2.42it/s]

 56%|█████▌    | 2637/4716 [18:16<14:18,  2.42it/s]

 56%|█████▌    | 2638/4716 [18:16<14:17,  2.42it/s]

 56%|█████▌    | 2639/4716 [18:17<14:18,  2.42it/s]

 56%|█████▌    | 2640/4716 [18:17<14:17,  2.42it/s]

 56%|█████▌    | 2641/4716 [18:18<14:18,  2.42it/s]

 56%|█████▌    | 2642/4716 [18:18<14:17,  2.42it/s]

 56%|█████▌    | 2643/4716 [18:18<14:15,  2.42it/s]

 56%|█████▌    | 2644/4716 [18:19<14:15,  2.42it/s]

 56%|█████▌    | 2645/4716 [18:19<14:14,  2.42it/s]

 56%|█████▌    | 2646/4716 [18:20<14:13,  2.42it/s]

 56%|█████▌    | 2647/4716 [18:20<14:12,  2.43it/s]

 56%|█████▌    | 2648/4716 [18:20<14:14,  2.42it/s]

 56%|█████▌    | 2649/4716 [18:21<14:13,  2.42it/s]

 56%|█████▌    | 2650/4716 [18:21<14:13,  2.42it/s]

 56%|█████▌    | 2651/4716 [18:22<14:12,  2.42it/s]

 56%|█████▌    | 2652/4716 [18:22<14:11,  2.42it/s]

 56%|█████▋    | 2653/4716 [18:22<14:10,  2.43it/s]

 56%|█████▋    | 2654/4716 [18:23<14:10,  2.42it/s]

 56%|█████▋    | 2655/4716 [18:23<14:10,  2.42it/s]

 56%|█████▋    | 2656/4716 [18:24<14:09,  2.43it/s]

 56%|█████▋    | 2657/4716 [18:24<14:08,  2.43it/s]

 56%|█████▋    | 2658/4716 [18:25<14:07,  2.43it/s]

 56%|█████▋    | 2659/4716 [18:25<14:08,  2.42it/s]

 56%|█████▋    | 2660/4716 [18:25<14:08,  2.42it/s]

 56%|█████▋    | 2661/4716 [18:26<14:08,  2.42it/s]

 56%|█████▋    | 2662/4716 [18:26<14:06,  2.43it/s]

 56%|█████▋    | 2663/4716 [18:27<14:05,  2.43it/s]

 56%|█████▋    | 2664/4716 [18:27<14:04,  2.43it/s]

 57%|█████▋    | 2665/4716 [18:27<14:04,  2.43it/s]

 57%|█████▋    | 2666/4716 [18:28<14:04,  2.43it/s]

 57%|█████▋    | 2667/4716 [18:28<14:03,  2.43it/s]

 57%|█████▋    | 2668/4716 [18:29<14:03,  2.43it/s]

 57%|█████▋    | 2669/4716 [18:29<14:03,  2.43it/s]

 57%|█████▋    | 2670/4716 [18:29<14:03,  2.43it/s]

 57%|█████▋    | 2671/4716 [18:30<14:03,  2.42it/s]

 57%|█████▋    | 2672/4716 [18:30<14:02,  2.43it/s]

 57%|█████▋    | 2673/4716 [18:31<14:02,  2.43it/s]

 57%|█████▋    | 2674/4716 [18:31<14:03,  2.42it/s]

 57%|█████▋    | 2675/4716 [18:32<14:02,  2.42it/s]

 57%|█████▋    | 2676/4716 [18:32<14:02,  2.42it/s]

 57%|█████▋    | 2677/4716 [18:32<14:00,  2.42it/s]

 57%|█████▋    | 2678/4716 [18:33<13:59,  2.43it/s]

 57%|█████▋    | 2679/4716 [18:33<13:59,  2.43it/s]

 57%|█████▋    | 2680/4716 [18:34<13:59,  2.43it/s]

 57%|█████▋    | 2681/4716 [18:34<13:59,  2.42it/s]

 57%|█████▋    | 2682/4716 [18:34<13:59,  2.42it/s]

 57%|█████▋    | 2683/4716 [18:35<13:59,  2.42it/s]

 57%|█████▋    | 2684/4716 [18:35<13:58,  2.42it/s]

 57%|█████▋    | 2685/4716 [18:36<13:57,  2.42it/s]

 57%|█████▋    | 2686/4716 [18:36<13:56,  2.43it/s]

 57%|█████▋    | 2687/4716 [18:36<13:56,  2.42it/s]

 57%|█████▋    | 2688/4716 [18:37<13:55,  2.43it/s]

 57%|█████▋    | 2689/4716 [18:37<13:55,  2.43it/s]

 57%|█████▋    | 2690/4716 [18:38<13:55,  2.43it/s]

 57%|█████▋    | 2691/4716 [18:38<13:56,  2.42it/s]

 57%|█████▋    | 2692/4716 [18:39<13:56,  2.42it/s]

 57%|█████▋    | 2693/4716 [18:39<13:56,  2.42it/s]

 57%|█████▋    | 2694/4716 [18:39<13:55,  2.42it/s]

 57%|█████▋    | 2695/4716 [18:40<13:54,  2.42it/s]

 57%|█████▋    | 2696/4716 [18:40<13:54,  2.42it/s]

 57%|█████▋    | 2697/4716 [18:41<13:53,  2.42it/s]

 57%|█████▋    | 2698/4716 [18:41<13:53,  2.42it/s]

 57%|█████▋    | 2699/4716 [18:41<13:51,  2.42it/s]

 57%|█████▋    | 2700/4716 [18:42<13:52,  2.42it/s]

 57%|█████▋    | 2701/4716 [18:42<13:52,  2.42it/s]

 57%|█████▋    | 2702/4716 [18:43<13:51,  2.42it/s]

 57%|█████▋    | 2703/4716 [18:43<13:50,  2.42it/s]

 57%|█████▋    | 2704/4716 [18:44<13:50,  2.42it/s]

 57%|█████▋    | 2705/4716 [18:44<13:49,  2.42it/s]

 57%|█████▋    | 2706/4716 [18:44<13:49,  2.42it/s]

 57%|█████▋    | 2707/4716 [18:45<13:49,  2.42it/s]

 57%|█████▋    | 2708/4716 [18:45<13:49,  2.42it/s]

 57%|█████▋    | 2709/4716 [18:46<13:49,  2.42it/s]

 57%|█████▋    | 2710/4716 [18:46<13:47,  2.42it/s]

 57%|█████▋    | 2711/4716 [18:46<13:48,  2.42it/s]

 58%|█████▊    | 2712/4716 [18:47<13:47,  2.42it/s]

 58%|█████▊    | 2713/4716 [18:47<13:47,  2.42it/s]

 58%|█████▊    | 2714/4716 [18:48<13:46,  2.42it/s]

 58%|█████▊    | 2715/4716 [18:48<13:45,  2.42it/s]

 58%|█████▊    | 2716/4716 [18:48<13:45,  2.42it/s]

 58%|█████▊    | 2717/4716 [18:49<13:44,  2.42it/s]

 58%|█████▊    | 2718/4716 [18:49<13:44,  2.42it/s]

 58%|█████▊    | 2719/4716 [18:50<13:43,  2.42it/s]

 58%|█████▊    | 2720/4716 [18:50<13:44,  2.42it/s]

 58%|█████▊    | 2721/4716 [18:51<13:43,  2.42it/s]

 58%|█████▊    | 2722/4716 [18:51<13:43,  2.42it/s]

 58%|█████▊    | 2723/4716 [18:51<13:42,  2.42it/s]

 58%|█████▊    | 2724/4716 [18:52<13:43,  2.42it/s]

 58%|█████▊    | 2725/4716 [18:52<13:42,  2.42it/s]

 58%|█████▊    | 2726/4716 [18:53<13:42,  2.42it/s]

 58%|█████▊    | 2727/4716 [18:53<13:41,  2.42it/s]

 58%|█████▊    | 2728/4716 [18:53<13:41,  2.42it/s]

 58%|█████▊    | 2729/4716 [18:54<13:42,  2.42it/s]

 58%|█████▊    | 2730/4716 [18:54<13:41,  2.42it/s]

 58%|█████▊    | 2731/4716 [18:55<13:41,  2.42it/s]

 58%|█████▊    | 2732/4716 [18:55<13:40,  2.42it/s]

 58%|█████▊    | 2733/4716 [18:55<13:39,  2.42it/s]

 58%|█████▊    | 2734/4716 [18:56<13:39,  2.42it/s]

 58%|█████▊    | 2735/4716 [18:56<13:40,  2.41it/s]

 58%|█████▊    | 2736/4716 [18:57<13:39,  2.42it/s]

 58%|█████▊    | 2737/4716 [18:57<13:39,  2.42it/s]

 58%|█████▊    | 2738/4716 [18:58<13:38,  2.42it/s]

 58%|█████▊    | 2739/4716 [18:58<13:36,  2.42it/s]

 58%|█████▊    | 2740/4716 [18:58<13:37,  2.42it/s]

 58%|█████▊    | 2741/4716 [18:59<13:36,  2.42it/s]

 58%|█████▊    | 2742/4716 [18:59<13:36,  2.42it/s]

 58%|█████▊    | 2743/4716 [19:00<13:38,  2.41it/s]

 58%|█████▊    | 2744/4716 [19:00<13:36,  2.41it/s]

 58%|█████▊    | 2745/4716 [19:00<13:35,  2.42it/s]

 58%|█████▊    | 2746/4716 [19:01<13:34,  2.42it/s]

 58%|█████▊    | 2747/4716 [19:01<13:34,  2.42it/s]

 58%|█████▊    | 2748/4716 [19:02<13:34,  2.42it/s]

 58%|█████▊    | 2749/4716 [19:02<13:34,  2.41it/s]

 58%|█████▊    | 2750/4716 [19:03<13:33,  2.42it/s]

 58%|█████▊    | 2751/4716 [19:03<13:33,  2.42it/s]

 58%|█████▊    | 2752/4716 [19:03<13:32,  2.42it/s]

 58%|█████▊    | 2753/4716 [19:04<13:32,  2.42it/s]

 58%|█████▊    | 2754/4716 [19:04<13:31,  2.42it/s]

 58%|█████▊    | 2755/4716 [19:05<13:31,  2.42it/s]

 58%|█████▊    | 2756/4716 [19:05<13:31,  2.42it/s]

 58%|█████▊    | 2757/4716 [19:05<13:30,  2.42it/s]

 58%|█████▊    | 2758/4716 [19:06<13:31,  2.41it/s]

 59%|█████▊    | 2759/4716 [19:06<13:30,  2.41it/s]

 59%|█████▊    | 2760/4716 [19:07<13:29,  2.42it/s]

 59%|█████▊    | 2761/4716 [19:07<13:28,  2.42it/s]

 59%|█████▊    | 2762/4716 [19:07<13:28,  2.42it/s]

 59%|█████▊    | 2763/4716 [19:08<13:27,  2.42it/s]

 59%|█████▊    | 2764/4716 [19:08<13:27,  2.42it/s]

 59%|█████▊    | 2765/4716 [19:09<13:26,  2.42it/s]

 59%|█████▊    | 2766/4716 [19:09<13:27,  2.41it/s]

 59%|█████▊    | 2767/4716 [19:10<13:26,  2.42it/s]

 59%|█████▊    | 2768/4716 [19:10<13:25,  2.42it/s]

 59%|█████▊    | 2769/4716 [19:10<13:24,  2.42it/s]

 59%|█████▊    | 2770/4716 [19:11<13:24,  2.42it/s]

 59%|█████▉    | 2771/4716 [19:11<13:23,  2.42it/s]

 59%|█████▉    | 2772/4716 [19:12<13:23,  2.42it/s]

 59%|█████▉    | 2773/4716 [19:12<13:24,  2.42it/s]

 59%|█████▉    | 2774/4716 [19:12<13:24,  2.41it/s]

 59%|█████▉    | 2775/4716 [19:13<13:23,  2.42it/s]

 59%|█████▉    | 2776/4716 [19:13<13:23,  2.41it/s]

 59%|█████▉    | 2777/4716 [19:14<13:23,  2.41it/s]

 59%|█████▉    | 2778/4716 [19:14<13:22,  2.41it/s]

 59%|█████▉    | 2779/4716 [19:15<13:24,  2.41it/s]

 59%|█████▉    | 2780/4716 [19:15<13:22,  2.41it/s]

 59%|█████▉    | 2781/4716 [19:15<13:22,  2.41it/s]

 59%|█████▉    | 2782/4716 [19:16<13:21,  2.41it/s]

 59%|█████▉    | 2783/4716 [19:16<13:20,  2.42it/s]

 59%|█████▉    | 2784/4716 [19:17<13:19,  2.42it/s]

 59%|█████▉    | 2785/4716 [19:17<13:18,  2.42it/s]

 59%|█████▉    | 2786/4716 [19:17<13:17,  2.42it/s]

 59%|█████▉    | 2787/4716 [19:18<13:18,  2.42it/s]

 59%|█████▉    | 2788/4716 [19:18<13:18,  2.41it/s]

 59%|█████▉    | 2789/4716 [19:19<13:18,  2.41it/s]

 59%|█████▉    | 2790/4716 [19:19<13:17,  2.41it/s]

 59%|█████▉    | 2791/4716 [19:20<13:16,  2.42it/s]

 59%|█████▉    | 2792/4716 [19:20<13:16,  2.42it/s]

 59%|█████▉    | 2793/4716 [19:20<13:16,  2.42it/s]

 59%|█████▉    | 2794/4716 [19:21<13:15,  2.42it/s]

 59%|█████▉    | 2795/4716 [19:21<13:15,  2.42it/s]

 59%|█████▉    | 2796/4716 [19:22<13:15,  2.41it/s]

 59%|█████▉    | 2797/4716 [19:22<13:14,  2.42it/s]

 59%|█████▉    | 2798/4716 [19:22<13:14,  2.41it/s]

 59%|█████▉    | 2799/4716 [19:23<13:13,  2.41it/s]

 59%|█████▉    | 2800/4716 [19:23<13:13,  2.42it/s]

 59%|█████▉    | 2801/4716 [19:24<13:12,  2.42it/s]

 59%|█████▉    | 2802/4716 [19:24<13:13,  2.41it/s]

 59%|█████▉    | 2803/4716 [19:24<13:13,  2.41it/s]

 59%|█████▉    | 2804/4716 [19:25<13:13,  2.41it/s]

 59%|█████▉    | 2805/4716 [19:25<13:12,  2.41it/s]

 59%|█████▉    | 2806/4716 [19:26<13:10,  2.42it/s]

 60%|█████▉    | 2807/4716 [19:26<13:14,  2.40it/s]

 60%|█████▉    | 2808/4716 [19:27<13:13,  2.40it/s]

 60%|█████▉    | 2809/4716 [19:27<13:11,  2.41it/s]

 60%|█████▉    | 2810/4716 [19:27<13:10,  2.41it/s]

 60%|█████▉    | 2811/4716 [19:28<13:09,  2.41it/s]

 60%|█████▉    | 2812/4716 [19:28<13:08,  2.41it/s]

 60%|█████▉    | 2813/4716 [19:29<13:09,  2.41it/s]

 60%|█████▉    | 2814/4716 [19:29<13:08,  2.41it/s]

 60%|█████▉    | 2815/4716 [19:29<13:07,  2.41it/s]

 60%|█████▉    | 2816/4716 [19:30<13:06,  2.41it/s]

 60%|█████▉    | 2817/4716 [19:30<13:07,  2.41it/s]

 60%|█████▉    | 2818/4716 [19:31<13:06,  2.41it/s]

 60%|█████▉    | 2819/4716 [19:31<13:06,  2.41it/s]

 60%|█████▉    | 2820/4716 [19:32<13:05,  2.42it/s]

 60%|█████▉    | 2821/4716 [19:32<13:04,  2.41it/s]

 60%|█████▉    | 2822/4716 [19:32<13:04,  2.42it/s]

 60%|█████▉    | 2823/4716 [19:33<13:05,  2.41it/s]

 60%|█████▉    | 2824/4716 [19:33<13:05,  2.41it/s]

 60%|█████▉    | 2825/4716 [19:34<13:03,  2.41it/s]

 60%|█████▉    | 2826/4716 [19:34<13:02,  2.41it/s]

 60%|█████▉    | 2827/4716 [19:34<13:03,  2.41it/s]

 60%|█████▉    | 2828/4716 [19:35<13:02,  2.41it/s]

 60%|█████▉    | 2829/4716 [19:35<13:03,  2.41it/s]

 60%|██████    | 2830/4716 [19:36<13:02,  2.41it/s]

 60%|██████    | 2831/4716 [19:36<13:02,  2.41it/s]

 60%|██████    | 2832/4716 [19:36<13:01,  2.41it/s]

 60%|██████    | 2833/4716 [19:37<13:00,  2.41it/s]

 60%|██████    | 2834/4716 [19:37<12:59,  2.41it/s]

 60%|██████    | 2835/4716 [19:38<12:59,  2.41it/s]

 60%|██████    | 2836/4716 [19:38<12:59,  2.41it/s]

 60%|██████    | 2837/4716 [19:39<12:58,  2.41it/s]

 60%|██████    | 2838/4716 [19:39<12:58,  2.41it/s]

 60%|██████    | 2839/4716 [19:39<12:57,  2.41it/s]

 60%|██████    | 2840/4716 [19:40<12:57,  2.41it/s]

 60%|██████    | 2841/4716 [19:40<12:56,  2.41it/s]

 60%|██████    | 2842/4716 [19:41<12:57,  2.41it/s]

 60%|██████    | 2843/4716 [19:41<12:56,  2.41it/s]

 60%|██████    | 2844/4716 [19:41<12:55,  2.41it/s]

 60%|██████    | 2845/4716 [19:42<12:55,  2.41it/s]

 60%|██████    | 2846/4716 [19:42<12:55,  2.41it/s]

 60%|██████    | 2847/4716 [19:43<12:55,  2.41it/s]

 60%|██████    | 2848/4716 [19:43<12:54,  2.41it/s]

 60%|██████    | 2849/4716 [19:44<12:54,  2.41it/s]

 60%|██████    | 2850/4716 [19:44<12:53,  2.41it/s]

 60%|██████    | 2851/4716 [19:44<12:53,  2.41it/s]

 60%|██████    | 2852/4716 [19:45<12:52,  2.41it/s]

 60%|██████    | 2853/4716 [19:45<12:52,  2.41it/s]

 61%|██████    | 2854/4716 [19:46<12:52,  2.41it/s]

 61%|██████    | 2855/4716 [19:46<12:51,  2.41it/s]

 61%|██████    | 2856/4716 [19:46<12:51,  2.41it/s]

 61%|██████    | 2857/4716 [19:47<12:51,  2.41it/s]

 61%|██████    | 2858/4716 [19:47<12:51,  2.41it/s]

 61%|██████    | 2859/4716 [19:48<12:51,  2.41it/s]

 61%|██████    | 2860/4716 [19:48<12:50,  2.41it/s]

 61%|██████    | 2861/4716 [19:49<12:49,  2.41it/s]

 61%|██████    | 2862/4716 [19:49<12:49,  2.41it/s]

 61%|██████    | 2863/4716 [19:49<12:48,  2.41it/s]

 61%|██████    | 2864/4716 [19:50<12:48,  2.41it/s]

 61%|██████    | 2865/4716 [19:50<12:47,  2.41it/s]

 61%|██████    | 2866/4716 [19:51<12:47,  2.41it/s]

 61%|██████    | 2867/4716 [19:51<12:47,  2.41it/s]

 61%|██████    | 2868/4716 [19:51<12:47,  2.41it/s]

 61%|██████    | 2869/4716 [19:52<12:46,  2.41it/s]

 61%|██████    | 2870/4716 [19:52<12:47,  2.41it/s]

 61%|██████    | 2871/4716 [19:53<12:46,  2.41it/s]

 61%|██████    | 2872/4716 [19:53<12:46,  2.41it/s]

 61%|██████    | 2873/4716 [19:54<12:45,  2.41it/s]

 61%|██████    | 2874/4716 [19:54<12:45,  2.41it/s]

 61%|██████    | 2875/4716 [19:54<12:43,  2.41it/s]

 61%|██████    | 2876/4716 [19:55<12:43,  2.41it/s]

 61%|██████    | 2877/4716 [19:55<12:43,  2.41it/s]

 61%|██████    | 2878/4716 [19:56<12:44,  2.41it/s]

 61%|██████    | 2879/4716 [19:56<12:43,  2.40it/s]

 61%|██████    | 2880/4716 [19:56<12:42,  2.41it/s]

 61%|██████    | 2881/4716 [19:57<12:42,  2.41it/s]

 61%|██████    | 2882/4716 [19:57<12:42,  2.41it/s]

 61%|██████    | 2883/4716 [19:58<12:42,  2.40it/s]

 61%|██████    | 2884/4716 [19:58<12:41,  2.41it/s]

 61%|██████    | 2885/4716 [19:58<12:41,  2.41it/s]

 61%|██████    | 2886/4716 [19:59<12:39,  2.41it/s]

 61%|██████    | 2887/4716 [19:59<12:40,  2.41it/s]

 61%|██████    | 2888/4716 [20:00<12:39,  2.41it/s]

 61%|██████▏   | 2889/4716 [20:00<12:39,  2.41it/s]

 61%|██████▏   | 2890/4716 [20:01<12:39,  2.40it/s]

 61%|██████▏   | 2891/4716 [20:01<12:38,  2.41it/s]

 61%|██████▏   | 2892/4716 [20:01<12:38,  2.40it/s]

 61%|██████▏   | 2893/4716 [20:02<12:37,  2.41it/s]

 61%|██████▏   | 2894/4716 [20:02<12:36,  2.41it/s]

 61%|██████▏   | 2895/4716 [20:03<12:36,  2.41it/s]

 61%|██████▏   | 2896/4716 [20:03<12:36,  2.41it/s]

 61%|██████▏   | 2897/4716 [20:03<12:34,  2.41it/s]

 61%|██████▏   | 2898/4716 [20:04<12:34,  2.41it/s]

 61%|██████▏   | 2899/4716 [20:04<12:33,  2.41it/s]

 61%|██████▏   | 2900/4716 [20:05<12:33,  2.41it/s]

 62%|██████▏   | 2901/4716 [20:05<12:32,  2.41it/s]

 62%|██████▏   | 2902/4716 [20:06<12:31,  2.41it/s]

 62%|██████▏   | 2903/4716 [20:06<12:32,  2.41it/s]

 62%|██████▏   | 2904/4716 [20:06<12:31,  2.41it/s]

 62%|██████▏   | 2905/4716 [20:07<12:31,  2.41it/s]

 62%|██████▏   | 2906/4716 [20:07<12:30,  2.41it/s]

 62%|██████▏   | 2907/4716 [20:08<12:30,  2.41it/s]

 62%|██████▏   | 2908/4716 [20:08<12:30,  2.41it/s]

 62%|██████▏   | 2909/4716 [20:08<12:29,  2.41it/s]

 62%|██████▏   | 2910/4716 [20:09<12:30,  2.41it/s]

 62%|██████▏   | 2911/4716 [20:09<12:30,  2.41it/s]

 62%|██████▏   | 2912/4716 [20:10<12:28,  2.41it/s]

 62%|██████▏   | 2913/4716 [20:10<12:27,  2.41it/s]

 62%|██████▏   | 2914/4716 [20:11<12:27,  2.41it/s]

 62%|██████▏   | 2915/4716 [20:11<12:27,  2.41it/s]

 62%|██████▏   | 2916/4716 [20:11<12:27,  2.41it/s]

 62%|██████▏   | 2917/4716 [20:12<12:27,  2.41it/s]

 62%|██████▏   | 2918/4716 [20:12<12:29,  2.40it/s]

 62%|██████▏   | 2919/4716 [20:13<12:27,  2.40it/s]

 62%|██████▏   | 2920/4716 [20:13<12:26,  2.41it/s]

 62%|██████▏   | 2921/4716 [20:13<12:26,  2.41it/s]

 62%|██████▏   | 2922/4716 [20:14<12:25,  2.41it/s]

 62%|██████▏   | 2923/4716 [20:14<12:24,  2.41it/s]

 62%|██████▏   | 2924/4716 [20:15<12:24,  2.41it/s]

 62%|██████▏   | 2925/4716 [20:15<12:24,  2.41it/s]

 62%|██████▏   | 2926/4716 [20:16<12:24,  2.41it/s]

 62%|██████▏   | 2927/4716 [20:16<12:22,  2.41it/s]

 62%|██████▏   | 2928/4716 [20:16<12:23,  2.40it/s]

 62%|██████▏   | 2929/4716 [20:17<12:23,  2.40it/s]

 62%|██████▏   | 2930/4716 [20:17<12:22,  2.41it/s]

 62%|██████▏   | 2931/4716 [20:18<12:21,  2.41it/s]

 62%|██████▏   | 2932/4716 [20:18<12:21,  2.40it/s]

 62%|██████▏   | 2933/4716 [20:18<12:20,  2.41it/s]

 62%|██████▏   | 2934/4716 [20:19<12:21,  2.40it/s]

 62%|██████▏   | 2935/4716 [20:19<12:21,  2.40it/s]

 62%|██████▏   | 2936/4716 [20:20<12:20,  2.40it/s]

 62%|██████▏   | 2937/4716 [20:20<12:19,  2.41it/s]

 62%|██████▏   | 2938/4716 [20:21<12:19,  2.40it/s]

 62%|██████▏   | 2939/4716 [20:21<12:20,  2.40it/s]

 62%|██████▏   | 2940/4716 [20:21<12:20,  2.40it/s]

 62%|██████▏   | 2941/4716 [20:22<12:18,  2.40it/s]

 62%|██████▏   | 2942/4716 [20:22<12:18,  2.40it/s]

 62%|██████▏   | 2943/4716 [20:23<12:17,  2.41it/s]

 62%|██████▏   | 2944/4716 [20:23<12:16,  2.41it/s]

 62%|██████▏   | 2945/4716 [20:23<12:16,  2.40it/s]

 62%|██████▏   | 2946/4716 [20:24<12:15,  2.41it/s]

 62%|██████▏   | 2947/4716 [20:24<12:15,  2.41it/s]

 63%|██████▎   | 2948/4716 [20:25<12:14,  2.41it/s]

 63%|██████▎   | 2949/4716 [20:25<12:14,  2.41it/s]

 63%|██████▎   | 2950/4716 [20:26<12:13,  2.41it/s]

 63%|██████▎   | 2951/4716 [20:26<12:13,  2.41it/s]

 63%|██████▎   | 2952/4716 [20:26<12:13,  2.40it/s]

 63%|██████▎   | 2953/4716 [20:27<12:12,  2.41it/s]

 63%|██████▎   | 2954/4716 [20:27<12:11,  2.41it/s]

 63%|██████▎   | 2955/4716 [20:28<12:11,  2.41it/s]

 63%|██████▎   | 2956/4716 [20:28<12:10,  2.41it/s]

 63%|██████▎   | 2957/4716 [20:28<12:11,  2.40it/s]

 63%|██████▎   | 2958/4716 [20:29<12:11,  2.40it/s]

 63%|██████▎   | 2959/4716 [20:29<12:10,  2.41it/s]

 63%|██████▎   | 2960/4716 [20:30<12:10,  2.40it/s]

 63%|██████▎   | 2961/4716 [20:30<12:10,  2.40it/s]

 63%|██████▎   | 2962/4716 [20:30<12:09,  2.40it/s]

 63%|██████▎   | 2963/4716 [20:31<12:09,  2.40it/s]

 63%|██████▎   | 2964/4716 [20:31<12:08,  2.40it/s]

 63%|██████▎   | 2965/4716 [20:32<12:07,  2.41it/s]

 63%|██████▎   | 2966/4716 [20:32<12:07,  2.40it/s]

 63%|██████▎   | 2967/4716 [20:33<12:07,  2.40it/s]

 63%|██████▎   | 2968/4716 [20:33<12:07,  2.40it/s]

 63%|██████▎   | 2969/4716 [20:33<12:06,  2.41it/s]

 63%|██████▎   | 2970/4716 [20:34<12:06,  2.40it/s]

 63%|██████▎   | 2971/4716 [20:34<12:05,  2.40it/s]

 63%|██████▎   | 2972/4716 [20:35<12:06,  2.40it/s]

 63%|██████▎   | 2973/4716 [20:35<12:04,  2.40it/s]

 63%|██████▎   | 2974/4716 [20:35<12:04,  2.40it/s]

 63%|██████▎   | 2975/4716 [20:36<12:04,  2.40it/s]

 63%|██████▎   | 2976/4716 [20:36<12:03,  2.41it/s]

 63%|██████▎   | 2977/4716 [20:37<12:02,  2.41it/s]

 63%|██████▎   | 2978/4716 [20:37<12:02,  2.41it/s]

 63%|██████▎   | 2979/4716 [20:38<12:01,  2.41it/s]

 63%|██████▎   | 2980/4716 [20:38<12:01,  2.41it/s]

 63%|██████▎   | 2981/4716 [20:38<12:01,  2.40it/s]

 63%|██████▎   | 2982/4716 [20:39<12:01,  2.40it/s]

 63%|██████▎   | 2983/4716 [20:39<12:00,  2.40it/s]

 63%|██████▎   | 2984/4716 [20:40<12:00,  2.40it/s]

 63%|██████▎   | 2985/4716 [20:40<12:00,  2.40it/s]

 63%|██████▎   | 2986/4716 [20:40<11:59,  2.40it/s]

 63%|██████▎   | 2987/4716 [20:41<11:58,  2.41it/s]

 63%|██████▎   | 2988/4716 [20:41<11:58,  2.40it/s]

 63%|██████▎   | 2989/4716 [20:42<11:58,  2.40it/s]

 63%|██████▎   | 2990/4716 [20:42<11:57,  2.40it/s]

 63%|██████▎   | 2991/4716 [20:43<11:57,  2.40it/s]

 63%|██████▎   | 2992/4716 [20:43<11:56,  2.40it/s]

 63%|██████▎   | 2993/4716 [20:43<11:57,  2.40it/s]

 63%|██████▎   | 2994/4716 [20:44<11:56,  2.40it/s]

 64%|██████▎   | 2995/4716 [20:44<11:56,  2.40it/s]

 64%|██████▎   | 2996/4716 [20:45<11:56,  2.40it/s]

 64%|██████▎   | 2997/4716 [20:45<11:55,  2.40it/s]

 64%|██████▎   | 2998/4716 [20:45<11:55,  2.40it/s]

 64%|██████▎   | 2999/4716 [20:46<11:56,  2.40it/s]

 64%|██████▎   | 3000/4716 [20:46<11:54,  2.40it/s]

 64%|██████▎   | 3001/4716 [20:47<11:54,  2.40it/s]

 64%|██████▎   | 3002/4716 [20:47<11:54,  2.40it/s]

 64%|██████▎   | 3003/4716 [20:48<11:54,  2.40it/s]

 64%|██████▎   | 3004/4716 [20:48<11:53,  2.40it/s]

 64%|██████▎   | 3005/4716 [20:48<11:52,  2.40it/s]

 64%|██████▎   | 3006/4716 [20:49<11:52,  2.40it/s]

 64%|██████▍   | 3007/4716 [20:49<11:52,  2.40it/s]

 64%|██████▍   | 3008/4716 [20:50<11:51,  2.40it/s]

 64%|██████▍   | 3009/4716 [20:50<11:51,  2.40it/s]

 64%|██████▍   | 3010/4716 [20:50<11:51,  2.40it/s]

 64%|██████▍   | 3011/4716 [20:51<11:50,  2.40it/s]

 64%|██████▍   | 3012/4716 [20:51<11:49,  2.40it/s]

 64%|██████▍   | 3013/4716 [20:52<11:48,  2.40it/s]

 64%|██████▍   | 3014/4716 [20:52<11:49,  2.40it/s]

 64%|██████▍   | 3015/4716 [20:53<11:48,  2.40it/s]

 64%|██████▍   | 3016/4716 [20:53<11:50,  2.39it/s]

 64%|██████▍   | 3017/4716 [20:53<11:50,  2.39it/s]

 64%|██████▍   | 3018/4716 [20:54<11:48,  2.40it/s]

 64%|██████▍   | 3019/4716 [20:54<11:46,  2.40it/s]

 64%|██████▍   | 3020/4716 [20:55<11:46,  2.40it/s]

 64%|██████▍   | 3021/4716 [20:55<11:45,  2.40it/s]

 64%|██████▍   | 3022/4716 [20:55<11:45,  2.40it/s]

 64%|██████▍   | 3023/4716 [20:56<11:43,  2.41it/s]

 64%|██████▍   | 3024/4716 [20:56<11:43,  2.40it/s]

 64%|██████▍   | 3025/4716 [20:57<11:43,  2.40it/s]

 64%|██████▍   | 3026/4716 [20:57<11:43,  2.40it/s]

 64%|██████▍   | 3027/4716 [20:58<11:43,  2.40it/s]

 64%|██████▍   | 3028/4716 [20:58<11:42,  2.40it/s]

 64%|██████▍   | 3029/4716 [20:58<11:42,  2.40it/s]

 64%|██████▍   | 3030/4716 [20:59<11:42,  2.40it/s]

 64%|██████▍   | 3031/4716 [20:59<11:41,  2.40it/s]

 64%|██████▍   | 3032/4716 [21:00<11:41,  2.40it/s]

 64%|██████▍   | 3033/4716 [21:00<11:40,  2.40it/s]

 64%|██████▍   | 3034/4716 [21:00<11:40,  2.40it/s]

 64%|██████▍   | 3035/4716 [21:01<11:38,  2.41it/s]

 64%|██████▍   | 3036/4716 [21:01<11:39,  2.40it/s]

 64%|██████▍   | 3037/4716 [21:02<11:38,  2.40it/s]

 64%|██████▍   | 3038/4716 [21:02<11:38,  2.40it/s]

 64%|██████▍   | 3039/4716 [21:03<11:38,  2.40it/s]

 64%|██████▍   | 3040/4716 [21:03<11:38,  2.40it/s]

 64%|██████▍   | 3041/4716 [21:03<11:37,  2.40it/s]

 65%|██████▍   | 3042/4716 [21:04<11:37,  2.40it/s]

 65%|██████▍   | 3043/4716 [21:04<11:38,  2.40it/s]

 65%|██████▍   | 3044/4716 [21:05<11:37,  2.40it/s]

 65%|██████▍   | 3045/4716 [21:05<11:37,  2.40it/s]

 65%|██████▍   | 3046/4716 [21:05<11:37,  2.40it/s]

 65%|██████▍   | 3047/4716 [21:06<11:36,  2.40it/s]

 65%|██████▍   | 3048/4716 [21:06<11:35,  2.40it/s]

 65%|██████▍   | 3049/4716 [21:07<11:35,  2.40it/s]

 65%|██████▍   | 3050/4716 [21:07<11:35,  2.40it/s]

 65%|██████▍   | 3051/4716 [21:08<11:34,  2.40it/s]

 65%|██████▍   | 3052/4716 [21:08<11:34,  2.40it/s]

 65%|██████▍   | 3053/4716 [21:08<11:34,  2.39it/s]

 65%|██████▍   | 3054/4716 [21:09<11:34,  2.39it/s]

 65%|██████▍   | 3055/4716 [21:09<11:33,  2.39it/s]

 65%|██████▍   | 3056/4716 [21:10<11:33,  2.39it/s]

 65%|██████▍   | 3057/4716 [21:10<11:33,  2.39it/s]

 65%|██████▍   | 3058/4716 [21:10<11:33,  2.39it/s]

 65%|██████▍   | 3059/4716 [21:11<11:32,  2.39it/s]

 65%|██████▍   | 3060/4716 [21:11<11:31,  2.39it/s]

 65%|██████▍   | 3061/4716 [21:12<11:30,  2.40it/s]

 65%|██████▍   | 3062/4716 [21:12<11:30,  2.39it/s]

 65%|██████▍   | 3063/4716 [21:13<11:29,  2.40it/s]

 65%|██████▍   | 3064/4716 [21:13<11:29,  2.40it/s]

 65%|██████▍   | 3065/4716 [21:13<11:28,  2.40it/s]

 65%|██████▌   | 3066/4716 [21:14<11:28,  2.40it/s]

 65%|██████▌   | 3067/4716 [21:14<11:27,  2.40it/s]

 65%|██████▌   | 3068/4716 [21:15<11:28,  2.39it/s]

 65%|██████▌   | 3069/4716 [21:15<11:27,  2.40it/s]

 65%|██████▌   | 3070/4716 [21:15<11:27,  2.39it/s]

 65%|██████▌   | 3071/4716 [21:16<11:26,  2.40it/s]

 65%|██████▌   | 3072/4716 [21:16<11:24,  2.40it/s]

 65%|██████▌   | 3073/4716 [21:17<11:24,  2.40it/s]

 65%|██████▌   | 3074/4716 [21:17<11:24,  2.40it/s]

 65%|██████▌   | 3075/4716 [21:18<11:23,  2.40it/s]

 65%|██████▌   | 3076/4716 [21:18<11:22,  2.40it/s]

 65%|██████▌   | 3077/4716 [21:18<11:22,  2.40it/s]

 65%|██████▌   | 3078/4716 [21:19<11:21,  2.40it/s]

 65%|██████▌   | 3079/4716 [21:19<11:21,  2.40it/s]

 65%|██████▌   | 3080/4716 [21:20<11:21,  2.40it/s]

 65%|██████▌   | 3081/4716 [21:20<11:21,  2.40it/s]

 65%|██████▌   | 3082/4716 [21:20<11:21,  2.40it/s]

 65%|██████▌   | 3083/4716 [21:21<11:21,  2.40it/s]

 65%|██████▌   | 3084/4716 [21:21<11:20,  2.40it/s]

 65%|██████▌   | 3085/4716 [21:22<11:20,  2.40it/s]

 65%|██████▌   | 3086/4716 [21:22<11:20,  2.39it/s]

 65%|██████▌   | 3087/4716 [21:23<11:20,  2.39it/s]

 65%|██████▌   | 3088/4716 [21:23<11:19,  2.40it/s]

 66%|██████▌   | 3089/4716 [21:23<11:18,  2.40it/s]

 66%|██████▌   | 3090/4716 [21:24<11:18,  2.40it/s]

 66%|██████▌   | 3091/4716 [21:24<11:18,  2.39it/s]

 66%|██████▌   | 3092/4716 [21:25<11:17,  2.40it/s]

 66%|██████▌   | 3093/4716 [21:25<11:16,  2.40it/s]

 66%|██████▌   | 3094/4716 [21:25<11:16,  2.40it/s]

 66%|██████▌   | 3095/4716 [21:26<11:16,  2.40it/s]

 66%|██████▌   | 3096/4716 [21:26<11:15,  2.40it/s]

 66%|██████▌   | 3097/4716 [21:27<11:15,  2.40it/s]

 66%|██████▌   | 3098/4716 [21:27<11:14,  2.40it/s]

 66%|██████▌   | 3099/4716 [21:28<11:15,  2.39it/s]

 66%|██████▌   | 3100/4716 [21:28<11:15,  2.39it/s]

 66%|██████▌   | 3101/4716 [21:28<11:14,  2.40it/s]

 66%|██████▌   | 3102/4716 [21:29<11:13,  2.40it/s]

 66%|██████▌   | 3103/4716 [21:29<11:13,  2.40it/s]

 66%|██████▌   | 3104/4716 [21:30<11:12,  2.40it/s]

 66%|██████▌   | 3105/4716 [21:30<11:13,  2.39it/s]

 66%|██████▌   | 3106/4716 [21:31<11:12,  2.39it/s]

 66%|██████▌   | 3107/4716 [21:31<11:12,  2.39it/s]

 66%|██████▌   | 3108/4716 [21:31<11:11,  2.39it/s]

 66%|██████▌   | 3109/4716 [21:32<11:11,  2.39it/s]

 66%|██████▌   | 3110/4716 [21:32<11:10,  2.39it/s]

 66%|██████▌   | 3111/4716 [21:33<11:10,  2.39it/s]

 66%|██████▌   | 3112/4716 [21:33<11:09,  2.40it/s]

 66%|██████▌   | 3113/4716 [21:33<11:09,  2.39it/s]

 66%|██████▌   | 3114/4716 [21:34<11:09,  2.39it/s]

 66%|██████▌   | 3115/4716 [21:34<11:08,  2.39it/s]

 66%|██████▌   | 3116/4716 [21:35<11:12,  2.38it/s]

 66%|██████▌   | 3117/4716 [21:35<11:11,  2.38it/s]

 66%|██████▌   | 3118/4716 [21:36<11:10,  2.38it/s]

 66%|██████▌   | 3119/4716 [21:36<11:09,  2.39it/s]

 66%|██████▌   | 3120/4716 [21:36<11:08,  2.39it/s]

 66%|██████▌   | 3121/4716 [21:37<11:07,  2.39it/s]

 66%|██████▌   | 3122/4716 [21:37<11:07,  2.39it/s]

 66%|██████▌   | 3123/4716 [21:38<11:07,  2.39it/s]

 66%|██████▌   | 3124/4716 [21:38<11:07,  2.39it/s]

 66%|██████▋   | 3125/4716 [21:38<11:05,  2.39it/s]

 66%|██████▋   | 3126/4716 [21:39<11:04,  2.39it/s]

 66%|██████▋   | 3127/4716 [21:39<11:03,  2.39it/s]

 66%|██████▋   | 3128/4716 [21:40<11:03,  2.39it/s]

 66%|██████▋   | 3129/4716 [21:40<11:02,  2.39it/s]

logging
logging the anndata

 66%|██████▋   | 3130/4716 [21:41<11:22,  2.32it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 66%|██████▋   | 3131/4716 [21:41<11:12,  2.36it/s]

 66%|██████▋   | 3132/4716 [21:41<11:05,  2.38it/s]

 66%|██████▋   | 3133/4716 [21:42<10:59,  2.40it/s]

 66%|██████▋   | 3134/4716 [21:42<10:55,  2.41it/s]

 66%|██████▋   | 3135/4716 [21:43<10:53,  2.42it/s]

 66%|██████▋   | 3136/4716 [21:43<10:51,  2.43it/s]

 67%|██████▋   | 3137/4716 [21:43<10:49,  2.43it/s]

 67%|██████▋   | 3138/4716 [21:44<10:48,  2.43it/s]

 67%|██████▋   | 3139/4716 [21:44<10:46,  2.44it/s]

 67%|██████▋   | 3140/4716 [21:45<10:46,  2.44it/s]

 67%|██████▋   | 3141/4716 [21:45<10:45,  2.44it/s]

 67%|██████▋   | 3142/4716 [21:45<10:45,  2.44it/s]

 67%|██████▋   | 3143/4716 [21:46<10:45,  2.44it/s]

 67%|██████▋   | 3144/4716 [21:46<10:46,  2.43it/s]

 67%|██████▋   | 3145/4716 [21:47<10:46,  2.43it/s]

 67%|██████▋   | 3146/4716 [21:47<10:45,  2.43it/s]

 67%|██████▋   | 3147/4716 [21:48<10:45,  2.43it/s]

 67%|██████▋   | 3148/4716 [21:48<10:43,  2.44it/s]

 67%|██████▋   | 3149/4716 [21:48<10:43,  2.44it/s]

 67%|██████▋   | 3150/4716 [21:49<10:42,  2.44it/s]

 67%|██████▋   | 3151/4716 [21:49<10:42,  2.43it/s]

 67%|██████▋   | 3152/4716 [21:50<10:41,  2.44it/s]

 67%|██████▋   | 3153/4716 [21:50<10:41,  2.44it/s]

 67%|██████▋   | 3154/4716 [21:50<10:41,  2.44it/s]

 67%|██████▋   | 3155/4716 [21:51<10:41,  2.43it/s]

 67%|██████▋   | 3156/4716 [21:51<10:42,  2.43it/s]

 67%|██████▋   | 3157/4716 [21:52<10:41,  2.43it/s]

 67%|██████▋   | 3158/4716 [21:52<10:41,  2.43it/s]

 67%|██████▋   | 3159/4716 [21:52<10:40,  2.43it/s]

 67%|██████▋   | 3160/4716 [21:53<10:41,  2.42it/s]

 67%|██████▋   | 3161/4716 [21:53<10:40,  2.43it/s]

 67%|██████▋   | 3162/4716 [21:54<10:40,  2.43it/s]

 67%|██████▋   | 3163/4716 [21:54<10:40,  2.43it/s]

 67%|██████▋   | 3164/4716 [21:55<10:38,  2.43it/s]

 67%|██████▋   | 3165/4716 [21:55<10:38,  2.43it/s]

 67%|██████▋   | 3166/4716 [21:55<10:37,  2.43it/s]

 67%|██████▋   | 3167/4716 [21:56<10:38,  2.43it/s]

 67%|██████▋   | 3168/4716 [21:56<10:36,  2.43it/s]

 67%|██████▋   | 3169/4716 [21:57<10:36,  2.43it/s]

 67%|██████▋   | 3170/4716 [21:57<10:35,  2.43it/s]

 67%|██████▋   | 3171/4716 [21:57<10:35,  2.43it/s]

 67%|██████▋   | 3172/4716 [21:58<10:34,  2.43it/s]

 67%|██████▋   | 3173/4716 [21:58<10:33,  2.43it/s]

 67%|██████▋   | 3174/4716 [21:59<10:32,  2.44it/s]

 67%|██████▋   | 3175/4716 [21:59<10:32,  2.44it/s]

 67%|██████▋   | 3176/4716 [21:59<10:31,  2.44it/s]

 67%|██████▋   | 3177/4716 [22:00<10:31,  2.44it/s]

 67%|██████▋   | 3178/4716 [22:00<10:31,  2.43it/s]

 67%|██████▋   | 3179/4716 [22:01<10:31,  2.43it/s]

 67%|██████▋   | 3180/4716 [22:01<10:31,  2.43it/s]

 67%|██████▋   | 3181/4716 [22:02<10:30,  2.43it/s]

 67%|██████▋   | 3182/4716 [22:02<10:30,  2.43it/s]

 67%|██████▋   | 3183/4716 [22:02<10:29,  2.44it/s]

 68%|██████▊   | 3184/4716 [22:03<10:28,  2.44it/s]

 68%|██████▊   | 3185/4716 [22:03<10:28,  2.44it/s]

 68%|██████▊   | 3186/4716 [22:04<10:28,  2.44it/s]

 68%|██████▊   | 3187/4716 [22:04<10:29,  2.43it/s]

 68%|██████▊   | 3188/4716 [22:04<10:27,  2.43it/s]

 68%|██████▊   | 3189/4716 [22:05<10:27,  2.44it/s]

 68%|██████▊   | 3190/4716 [22:05<10:26,  2.44it/s]

 68%|██████▊   | 3191/4716 [22:06<10:26,  2.44it/s]

 68%|██████▊   | 3192/4716 [22:06<10:26,  2.43it/s]

 68%|██████▊   | 3193/4716 [22:06<10:26,  2.43it/s]

 68%|██████▊   | 3194/4716 [22:07<10:26,  2.43it/s]

 68%|██████▊   | 3195/4716 [22:07<10:25,  2.43it/s]

 68%|██████▊   | 3196/4716 [22:08<10:25,  2.43it/s]

 68%|██████▊   | 3197/4716 [22:08<10:24,  2.43it/s]

 68%|██████▊   | 3198/4716 [22:09<10:25,  2.43it/s]

 68%|██████▊   | 3199/4716 [22:09<10:24,  2.43it/s]

 68%|██████▊   | 3200/4716 [22:09<10:24,  2.43it/s]

 68%|██████▊   | 3201/4716 [22:10<10:22,  2.43it/s]

 68%|██████▊   | 3202/4716 [22:10<10:22,  2.43it/s]

 68%|██████▊   | 3203/4716 [22:11<10:22,  2.43it/s]

 68%|██████▊   | 3204/4716 [22:11<10:21,  2.43it/s]

 68%|██████▊   | 3205/4716 [22:11<10:21,  2.43it/s]

 68%|██████▊   | 3206/4716 [22:12<10:21,  2.43it/s]

 68%|██████▊   | 3207/4716 [22:12<10:21,  2.43it/s]

 68%|██████▊   | 3208/4716 [22:13<10:19,  2.43it/s]

 68%|██████▊   | 3209/4716 [22:13<10:19,  2.43it/s]

 68%|██████▊   | 3210/4716 [22:13<10:19,  2.43it/s]

 68%|██████▊   | 3211/4716 [22:14<10:19,  2.43it/s]

 68%|██████▊   | 3212/4716 [22:14<10:19,  2.43it/s]

 68%|██████▊   | 3213/4716 [22:15<10:18,  2.43it/s]

 68%|██████▊   | 3214/4716 [22:15<10:18,  2.43it/s]

 68%|██████▊   | 3215/4716 [22:16<10:17,  2.43it/s]

 68%|██████▊   | 3216/4716 [22:16<10:17,  2.43it/s]

 68%|██████▊   | 3217/4716 [22:16<10:18,  2.42it/s]

 68%|██████▊   | 3218/4716 [22:17<10:17,  2.43it/s]

 68%|██████▊   | 3219/4716 [22:17<10:16,  2.43it/s]

 68%|██████▊   | 3220/4716 [22:18<10:15,  2.43it/s]

 68%|██████▊   | 3221/4716 [22:18<10:15,  2.43it/s]

 68%|██████▊   | 3222/4716 [22:18<10:16,  2.42it/s]

 68%|██████▊   | 3223/4716 [22:19<10:16,  2.42it/s]

 68%|██████▊   | 3224/4716 [22:19<10:16,  2.42it/s]

 68%|██████▊   | 3225/4716 [22:20<10:15,  2.42it/s]

 68%|██████▊   | 3226/4716 [22:20<10:14,  2.42it/s]

 68%|██████▊   | 3227/4716 [22:20<10:14,  2.42it/s]

 68%|██████▊   | 3228/4716 [22:21<10:14,  2.42it/s]

 68%|██████▊   | 3229/4716 [22:21<10:13,  2.42it/s]

 68%|██████▊   | 3230/4716 [22:22<10:13,  2.42it/s]

 69%|██████▊   | 3231/4716 [22:22<10:12,  2.43it/s]

 69%|██████▊   | 3232/4716 [22:23<10:11,  2.43it/s]

 69%|██████▊   | 3233/4716 [22:23<10:10,  2.43it/s]

 69%|██████▊   | 3234/4716 [22:23<10:10,  2.43it/s]

 69%|██████▊   | 3235/4716 [22:24<10:10,  2.43it/s]

 69%|██████▊   | 3236/4716 [22:24<10:09,  2.43it/s]

 69%|██████▊   | 3237/4716 [22:25<10:09,  2.43it/s]

 69%|██████▊   | 3238/4716 [22:25<10:08,  2.43it/s]

 69%|██████▊   | 3239/4716 [22:25<10:08,  2.43it/s]

 69%|██████▊   | 3240/4716 [22:26<10:08,  2.43it/s]

 69%|██████▊   | 3241/4716 [22:26<10:07,  2.43it/s]

 69%|██████▊   | 3242/4716 [22:27<10:06,  2.43it/s]

 69%|██████▉   | 3243/4716 [22:27<10:06,  2.43it/s]

 69%|██████▉   | 3244/4716 [22:27<10:06,  2.43it/s]

 69%|██████▉   | 3245/4716 [22:28<10:06,  2.42it/s]

 69%|██████▉   | 3246/4716 [22:28<10:06,  2.43it/s]

 69%|██████▉   | 3247/4716 [22:29<10:06,  2.42it/s]

 69%|██████▉   | 3248/4716 [22:29<10:04,  2.43it/s]

 69%|██████▉   | 3249/4716 [22:30<10:03,  2.43it/s]

 69%|██████▉   | 3250/4716 [22:30<10:03,  2.43it/s]

 69%|██████▉   | 3251/4716 [22:30<10:03,  2.43it/s]

 69%|██████▉   | 3252/4716 [22:31<10:03,  2.43it/s]

 69%|██████▉   | 3253/4716 [22:31<10:02,  2.43it/s]

 69%|██████▉   | 3254/4716 [22:32<10:02,  2.43it/s]

 69%|██████▉   | 3255/4716 [22:32<10:01,  2.43it/s]

 69%|██████▉   | 3256/4716 [22:32<10:01,  2.43it/s]

 69%|██████▉   | 3257/4716 [22:33<10:02,  2.42it/s]

 69%|██████▉   | 3258/4716 [22:33<10:01,  2.42it/s]

 69%|██████▉   | 3259/4716 [22:34<10:01,  2.42it/s]

 69%|██████▉   | 3260/4716 [22:34<10:00,  2.42it/s]

 69%|██████▉   | 3261/4716 [22:34<09:59,  2.43it/s]

 69%|██████▉   | 3262/4716 [22:35<09:59,  2.43it/s]

 69%|██████▉   | 3263/4716 [22:35<09:58,  2.43it/s]

 69%|██████▉   | 3264/4716 [22:36<09:58,  2.42it/s]

 69%|██████▉   | 3265/4716 [22:36<09:58,  2.42it/s]

 69%|██████▉   | 3266/4716 [22:37<09:57,  2.43it/s]

 69%|██████▉   | 3267/4716 [22:37<09:57,  2.42it/s]

 69%|██████▉   | 3268/4716 [22:37<09:56,  2.43it/s]

 69%|██████▉   | 3269/4716 [22:38<09:56,  2.43it/s]

 69%|██████▉   | 3270/4716 [22:38<09:55,  2.43it/s]

 69%|██████▉   | 3271/4716 [22:39<09:55,  2.43it/s]

 69%|██████▉   | 3272/4716 [22:39<09:54,  2.43it/s]

 69%|██████▉   | 3273/4716 [22:39<09:53,  2.43it/s]

 69%|██████▉   | 3274/4716 [22:40<09:53,  2.43it/s]

 69%|██████▉   | 3275/4716 [22:40<09:53,  2.43it/s]

 69%|██████▉   | 3276/4716 [22:41<09:52,  2.43it/s]

 69%|██████▉   | 3277/4716 [22:41<09:52,  2.43it/s]

 70%|██████▉   | 3278/4716 [22:41<09:52,  2.43it/s]

 70%|██████▉   | 3279/4716 [22:42<09:51,  2.43it/s]

 70%|██████▉   | 3280/4716 [22:42<09:51,  2.43it/s]

 70%|██████▉   | 3281/4716 [22:43<09:52,  2.42it/s]

 70%|██████▉   | 3282/4716 [22:43<09:51,  2.42it/s]

 70%|██████▉   | 3283/4716 [22:44<09:52,  2.42it/s]

 70%|██████▉   | 3284/4716 [22:44<09:54,  2.41it/s]

 70%|██████▉   | 3285/4716 [22:44<09:53,  2.41it/s]

 70%|██████▉   | 3286/4716 [22:45<09:51,  2.42it/s]

 70%|██████▉   | 3287/4716 [22:45<09:51,  2.42it/s]

 70%|██████▉   | 3288/4716 [22:46<09:49,  2.42it/s]

 70%|██████▉   | 3289/4716 [22:46<09:49,  2.42it/s]

 70%|██████▉   | 3290/4716 [22:46<09:47,  2.43it/s]

 70%|██████▉   | 3291/4716 [22:47<09:47,  2.43it/s]

 70%|██████▉   | 3292/4716 [22:47<09:46,  2.43it/s]

 70%|██████▉   | 3293/4716 [22:48<09:46,  2.42it/s]

 70%|██████▉   | 3294/4716 [22:48<09:46,  2.43it/s]

 70%|██████▉   | 3295/4716 [22:49<09:45,  2.43it/s]

 70%|██████▉   | 3296/4716 [22:49<09:45,  2.43it/s]

 70%|██████▉   | 3297/4716 [22:49<09:46,  2.42it/s]

 70%|██████▉   | 3298/4716 [22:50<09:46,  2.42it/s]

 70%|██████▉   | 3299/4716 [22:50<09:45,  2.42it/s]

 70%|██████▉   | 3300/4716 [22:51<09:44,  2.42it/s]

 70%|██████▉   | 3301/4716 [22:51<09:44,  2.42it/s]

 70%|███████   | 3302/4716 [22:51<09:44,  2.42it/s]

 70%|███████   | 3303/4716 [22:52<09:43,  2.42it/s]

 70%|███████   | 3304/4716 [22:52<09:43,  2.42it/s]

 70%|███████   | 3305/4716 [22:53<09:42,  2.42it/s]

 70%|███████   | 3306/4716 [22:53<09:41,  2.43it/s]

 70%|███████   | 3307/4716 [22:53<09:41,  2.42it/s]

 70%|███████   | 3308/4716 [22:54<09:40,  2.43it/s]

 70%|███████   | 3309/4716 [22:54<09:40,  2.42it/s]

 70%|███████   | 3310/4716 [22:55<09:39,  2.43it/s]

 70%|███████   | 3311/4716 [22:55<09:39,  2.42it/s]

 70%|███████   | 3312/4716 [22:56<09:38,  2.43it/s]

 70%|███████   | 3313/4716 [22:56<09:38,  2.42it/s]

 70%|███████   | 3314/4716 [22:56<09:37,  2.43it/s]

 70%|███████   | 3315/4716 [22:57<09:37,  2.42it/s]

 70%|███████   | 3316/4716 [22:57<09:37,  2.42it/s]

 70%|███████   | 3317/4716 [22:58<09:36,  2.42it/s]

 70%|███████   | 3318/4716 [22:58<09:36,  2.43it/s]

 70%|███████   | 3319/4716 [22:58<09:36,  2.43it/s]

 70%|███████   | 3320/4716 [22:59<09:35,  2.43it/s]

 70%|███████   | 3321/4716 [22:59<09:34,  2.43it/s]

 70%|███████   | 3322/4716 [23:00<09:35,  2.42it/s]

 70%|███████   | 3323/4716 [23:00<09:35,  2.42it/s]

 70%|███████   | 3324/4716 [23:00<09:34,  2.42it/s]

 71%|███████   | 3325/4716 [23:01<09:33,  2.42it/s]

 71%|███████   | 3326/4716 [23:01<09:34,  2.42it/s]

 71%|███████   | 3327/4716 [23:02<09:33,  2.42it/s]

 71%|███████   | 3328/4716 [23:02<09:33,  2.42it/s]

 71%|███████   | 3329/4716 [23:03<09:32,  2.42it/s]

 71%|███████   | 3330/4716 [23:03<09:32,  2.42it/s]

 71%|███████   | 3331/4716 [23:03<09:31,  2.42it/s]

 71%|███████   | 3332/4716 [23:04<09:31,  2.42it/s]

 71%|███████   | 3333/4716 [23:04<09:31,  2.42it/s]

 71%|███████   | 3334/4716 [23:05<09:31,  2.42it/s]

 71%|███████   | 3335/4716 [23:05<09:31,  2.42it/s]

 71%|███████   | 3336/4716 [23:05<09:29,  2.42it/s]

 71%|███████   | 3337/4716 [23:06<09:29,  2.42it/s]

 71%|███████   | 3338/4716 [23:06<09:29,  2.42it/s]

 71%|███████   | 3339/4716 [23:07<09:29,  2.42it/s]

 71%|███████   | 3340/4716 [23:07<09:28,  2.42it/s]

 71%|███████   | 3341/4716 [23:07<09:29,  2.42it/s]

 71%|███████   | 3342/4716 [23:08<09:28,  2.42it/s]

 71%|███████   | 3343/4716 [23:08<09:28,  2.42it/s]

 71%|███████   | 3344/4716 [23:09<09:29,  2.41it/s]

 71%|███████   | 3345/4716 [23:09<09:28,  2.41it/s]

 71%|███████   | 3346/4716 [23:10<09:27,  2.41it/s]

 71%|███████   | 3347/4716 [23:10<09:27,  2.41it/s]

 71%|███████   | 3348/4716 [23:10<09:26,  2.41it/s]

 71%|███████   | 3349/4716 [23:11<09:25,  2.42it/s]

 71%|███████   | 3350/4716 [23:11<09:25,  2.42it/s]

 71%|███████   | 3351/4716 [23:12<09:24,  2.42it/s]

 71%|███████   | 3352/4716 [23:12<09:24,  2.42it/s]

 71%|███████   | 3353/4716 [23:12<09:23,  2.42it/s]

 71%|███████   | 3354/4716 [23:13<09:23,  2.42it/s]

 71%|███████   | 3355/4716 [23:13<09:22,  2.42it/s]

 71%|███████   | 3356/4716 [23:14<09:23,  2.42it/s]

 71%|███████   | 3357/4716 [23:14<09:21,  2.42it/s]

 71%|███████   | 3358/4716 [23:15<09:21,  2.42it/s]

 71%|███████   | 3359/4716 [23:15<09:20,  2.42it/s]

 71%|███████   | 3360/4716 [23:15<09:20,  2.42it/s]

 71%|███████▏  | 3361/4716 [23:16<09:19,  2.42it/s]

 71%|███████▏  | 3362/4716 [23:16<09:19,  2.42it/s]

 71%|███████▏  | 3363/4716 [23:17<09:19,  2.42it/s]

 71%|███████▏  | 3364/4716 [23:17<09:18,  2.42it/s]

 71%|███████▏  | 3365/4716 [23:17<09:17,  2.42it/s]

 71%|███████▏  | 3366/4716 [23:18<09:17,  2.42it/s]

 71%|███████▏  | 3367/4716 [23:18<09:16,  2.42it/s]

 71%|███████▏  | 3368/4716 [23:19<09:15,  2.42it/s]

 71%|███████▏  | 3369/4716 [23:19<09:15,  2.42it/s]

 71%|███████▏  | 3370/4716 [23:19<09:15,  2.43it/s]

 71%|███████▏  | 3371/4716 [23:20<09:15,  2.42it/s]

 72%|███████▏  | 3372/4716 [23:20<09:15,  2.42it/s]

 72%|███████▏  | 3373/4716 [23:21<09:14,  2.42it/s]

 72%|███████▏  | 3374/4716 [23:21<09:14,  2.42it/s]

 72%|███████▏  | 3375/4716 [23:22<09:13,  2.42it/s]

 72%|███████▏  | 3376/4716 [23:22<09:13,  2.42it/s]

 72%|███████▏  | 3377/4716 [23:22<09:12,  2.42it/s]

 72%|███████▏  | 3378/4716 [23:23<09:13,  2.42it/s]

 72%|███████▏  | 3379/4716 [23:23<09:12,  2.42it/s]

 72%|███████▏  | 3380/4716 [23:24<09:12,  2.42it/s]

 72%|███████▏  | 3381/4716 [23:24<09:12,  2.42it/s]

 72%|███████▏  | 3382/4716 [23:24<09:11,  2.42it/s]

 72%|███████▏  | 3383/4716 [23:25<09:12,  2.41it/s]

 72%|███████▏  | 3384/4716 [23:25<09:11,  2.42it/s]

 72%|███████▏  | 3385/4716 [23:26<09:11,  2.42it/s]

 72%|███████▏  | 3386/4716 [23:26<09:10,  2.42it/s]

 72%|███████▏  | 3387/4716 [23:27<09:10,  2.42it/s]

 72%|███████▏  | 3388/4716 [23:27<09:10,  2.41it/s]

 72%|███████▏  | 3389/4716 [23:27<09:09,  2.42it/s]

 72%|███████▏  | 3390/4716 [23:28<09:09,  2.41it/s]

 72%|███████▏  | 3391/4716 [23:28<09:08,  2.42it/s]

 72%|███████▏  | 3392/4716 [23:29<09:08,  2.42it/s]

 72%|███████▏  | 3393/4716 [23:29<09:07,  2.42it/s]

 72%|███████▏  | 3394/4716 [23:29<09:08,  2.41it/s]

 72%|███████▏  | 3395/4716 [23:30<09:06,  2.42it/s]

 72%|███████▏  | 3396/4716 [23:30<09:07,  2.41it/s]

 72%|███████▏  | 3397/4716 [23:31<09:05,  2.42it/s]

 72%|███████▏  | 3398/4716 [23:31<09:06,  2.41it/s]

 72%|███████▏  | 3399/4716 [23:31<09:05,  2.42it/s]

 72%|███████▏  | 3400/4716 [23:32<09:04,  2.42it/s]

 72%|███████▏  | 3401/4716 [23:32<09:02,  2.42it/s]

 72%|███████▏  | 3402/4716 [23:33<09:04,  2.42it/s]

 72%|███████▏  | 3403/4716 [23:33<09:03,  2.42it/s]

 72%|███████▏  | 3404/4716 [23:34<09:02,  2.42it/s]

 72%|███████▏  | 3405/4716 [23:34<09:02,  2.42it/s]

 72%|███████▏  | 3406/4716 [23:34<09:01,  2.42it/s]

 72%|███████▏  | 3407/4716 [23:35<09:00,  2.42it/s]

 72%|███████▏  | 3408/4716 [23:35<09:00,  2.42it/s]

 72%|███████▏  | 3409/4716 [23:36<09:01,  2.41it/s]

 72%|███████▏  | 3410/4716 [23:36<09:00,  2.42it/s]

 72%|███████▏  | 3411/4716 [23:36<09:00,  2.42it/s]

 72%|███████▏  | 3412/4716 [23:37<08:59,  2.42it/s]

 72%|███████▏  | 3413/4716 [23:37<08:59,  2.41it/s]

 72%|███████▏  | 3414/4716 [23:38<08:59,  2.42it/s]

 72%|███████▏  | 3415/4716 [23:38<08:58,  2.41it/s]

 72%|███████▏  | 3416/4716 [23:39<08:57,  2.42it/s]

 72%|███████▏  | 3417/4716 [23:39<08:57,  2.42it/s]

 72%|███████▏  | 3418/4716 [23:39<08:57,  2.42it/s]

 72%|███████▏  | 3419/4716 [23:40<08:56,  2.42it/s]

 73%|███████▎  | 3420/4716 [23:40<08:55,  2.42it/s]

 73%|███████▎  | 3421/4716 [23:41<08:55,  2.42it/s]

 73%|███████▎  | 3422/4716 [23:41<08:56,  2.41it/s]

 73%|███████▎  | 3423/4716 [23:41<08:56,  2.41it/s]

 73%|███████▎  | 3424/4716 [23:42<08:56,  2.41it/s]

 73%|███████▎  | 3425/4716 [23:42<08:55,  2.41it/s]

 73%|███████▎  | 3426/4716 [23:43<08:54,  2.41it/s]

 73%|███████▎  | 3427/4716 [23:43<08:53,  2.41it/s]

 73%|███████▎  | 3428/4716 [23:43<08:53,  2.41it/s]

 73%|███████▎  | 3429/4716 [23:44<08:52,  2.42it/s]

 73%|███████▎  | 3430/4716 [23:44<08:53,  2.41it/s]

 73%|███████▎  | 3431/4716 [23:45<08:52,  2.41it/s]

 73%|███████▎  | 3432/4716 [23:45<08:51,  2.41it/s]

 73%|███████▎  | 3433/4716 [23:46<08:51,  2.41it/s]

 73%|███████▎  | 3434/4716 [23:46<08:51,  2.41it/s]

 73%|███████▎  | 3435/4716 [23:46<08:51,  2.41it/s]

 73%|███████▎  | 3436/4716 [23:47<08:50,  2.41it/s]

 73%|███████▎  | 3437/4716 [23:47<08:50,  2.41it/s]

 73%|███████▎  | 3438/4716 [23:48<08:49,  2.42it/s]

 73%|███████▎  | 3439/4716 [23:48<08:49,  2.41it/s]

 73%|███████▎  | 3440/4716 [23:48<08:48,  2.41it/s]

 73%|███████▎  | 3441/4716 [23:49<08:49,  2.41it/s]

 73%|███████▎  | 3442/4716 [23:49<08:48,  2.41it/s]

 73%|███████▎  | 3443/4716 [23:50<08:48,  2.41it/s]

 73%|███████▎  | 3444/4716 [23:50<08:47,  2.41it/s]

 73%|███████▎  | 3445/4716 [23:51<08:47,  2.41it/s]

 73%|███████▎  | 3446/4716 [23:51<08:46,  2.41it/s]

 73%|███████▎  | 3447/4716 [23:51<08:46,  2.41it/s]

 73%|███████▎  | 3448/4716 [23:52<08:45,  2.41it/s]

 73%|███████▎  | 3449/4716 [23:52<08:45,  2.41it/s]

 73%|███████▎  | 3450/4716 [23:53<08:44,  2.42it/s]

 73%|███████▎  | 3451/4716 [23:53<08:44,  2.41it/s]

 73%|███████▎  | 3452/4716 [23:53<08:44,  2.41it/s]

 73%|███████▎  | 3453/4716 [23:54<08:43,  2.41it/s]

 73%|███████▎  | 3454/4716 [23:54<08:42,  2.41it/s]

 73%|███████▎  | 3455/4716 [23:55<08:41,  2.42it/s]

 73%|███████▎  | 3456/4716 [23:55<08:41,  2.41it/s]

 73%|███████▎  | 3457/4716 [23:56<08:41,  2.42it/s]

 73%|███████▎  | 3458/4716 [23:56<08:41,  2.41it/s]

 73%|███████▎  | 3459/4716 [23:56<08:40,  2.41it/s]

 73%|███████▎  | 3460/4716 [23:57<08:40,  2.41it/s]

 73%|███████▎  | 3461/4716 [23:57<08:39,  2.41it/s]

 73%|███████▎  | 3462/4716 [23:58<08:39,  2.41it/s]

 73%|███████▎  | 3463/4716 [23:58<08:39,  2.41it/s]

 73%|███████▎  | 3464/4716 [23:58<08:39,  2.41it/s]

 73%|███████▎  | 3465/4716 [23:59<08:38,  2.41it/s]

 73%|███████▎  | 3466/4716 [23:59<08:38,  2.41it/s]

 74%|███████▎  | 3467/4716 [24:00<08:37,  2.42it/s]

 74%|███████▎  | 3468/4716 [24:00<08:36,  2.41it/s]

 74%|███████▎  | 3469/4716 [24:00<08:36,  2.41it/s]

 74%|███████▎  | 3470/4716 [24:01<08:36,  2.41it/s]

 74%|███████▎  | 3471/4716 [24:01<08:35,  2.41it/s]

 74%|███████▎  | 3472/4716 [24:02<08:35,  2.41it/s]

 74%|███████▎  | 3473/4716 [24:02<08:36,  2.41it/s]

 74%|███████▎  | 3474/4716 [24:03<08:36,  2.41it/s]

 74%|███████▎  | 3475/4716 [24:03<08:35,  2.41it/s]

 74%|███████▎  | 3476/4716 [24:03<08:34,  2.41it/s]

 74%|███████▎  | 3477/4716 [24:04<08:34,  2.41it/s]

 74%|███████▎  | 3478/4716 [24:04<08:33,  2.41it/s]

 74%|███████▍  | 3479/4716 [24:05<08:33,  2.41it/s]

 74%|███████▍  | 3480/4716 [24:05<08:33,  2.41it/s]

 74%|███████▍  | 3481/4716 [24:05<08:33,  2.41it/s]

 74%|███████▍  | 3482/4716 [24:06<08:32,  2.41it/s]

 74%|███████▍  | 3483/4716 [24:06<08:32,  2.40it/s]

 74%|███████▍  | 3484/4716 [24:07<08:32,  2.41it/s]

 74%|███████▍  | 3485/4716 [24:07<08:31,  2.41it/s]

 74%|███████▍  | 3486/4716 [24:08<08:30,  2.41it/s]

 74%|███████▍  | 3487/4716 [24:08<08:30,  2.41it/s]

 74%|███████▍  | 3488/4716 [24:08<08:29,  2.41it/s]

 74%|███████▍  | 3489/4716 [24:09<08:29,  2.41it/s]

 74%|███████▍  | 3490/4716 [24:09<08:29,  2.41it/s]

 74%|███████▍  | 3491/4716 [24:10<08:28,  2.41it/s]

 74%|███████▍  | 3492/4716 [24:10<08:27,  2.41it/s]

 74%|███████▍  | 3493/4716 [24:10<08:27,  2.41it/s]

 74%|███████▍  | 3494/4716 [24:11<08:27,  2.41it/s]

 74%|███████▍  | 3495/4716 [24:11<08:26,  2.41it/s]

 74%|███████▍  | 3496/4716 [24:12<08:26,  2.41it/s]

 74%|███████▍  | 3497/4716 [24:12<08:26,  2.41it/s]

 74%|███████▍  | 3498/4716 [24:13<08:26,  2.40it/s]

 74%|███████▍  | 3499/4716 [24:13<08:25,  2.41it/s]

 74%|███████▍  | 3500/4716 [24:13<08:25,  2.41it/s]

 74%|███████▍  | 3501/4716 [24:14<08:24,  2.41it/s]

 74%|███████▍  | 3502/4716 [24:14<08:24,  2.41it/s]

 74%|███████▍  | 3503/4716 [24:15<08:23,  2.41it/s]

 74%|███████▍  | 3504/4716 [24:15<08:22,  2.41it/s]

 74%|███████▍  | 3505/4716 [24:15<08:21,  2.41it/s]

 74%|███████▍  | 3506/4716 [24:16<08:22,  2.41it/s]

 74%|███████▍  | 3507/4716 [24:16<08:22,  2.41it/s]

 74%|███████▍  | 3508/4716 [24:17<08:21,  2.41it/s]

 74%|███████▍  | 3509/4716 [24:17<08:21,  2.41it/s]

 74%|███████▍  | 3510/4716 [24:18<08:21,  2.41it/s]

 74%|███████▍  | 3511/4716 [24:18<08:20,  2.41it/s]

 74%|███████▍  | 3512/4716 [24:18<08:19,  2.41it/s]

 74%|███████▍  | 3513/4716 [24:19<08:19,  2.41it/s]

 75%|███████▍  | 3514/4716 [24:19<08:18,  2.41it/s]

 75%|███████▍  | 3515/4716 [24:20<08:18,  2.41it/s]

 75%|███████▍  | 3516/4716 [24:20<08:18,  2.41it/s]

 75%|███████▍  | 3517/4716 [24:20<08:18,  2.40it/s]

 75%|███████▍  | 3518/4716 [24:21<08:18,  2.41it/s]

 75%|███████▍  | 3519/4716 [24:21<08:17,  2.40it/s]

 75%|███████▍  | 3520/4716 [24:22<08:16,  2.41it/s]

 75%|███████▍  | 3521/4716 [24:22<08:16,  2.41it/s]

 75%|███████▍  | 3522/4716 [24:22<08:15,  2.41it/s]

 75%|███████▍  | 3523/4716 [24:23<08:15,  2.41it/s]

 75%|███████▍  | 3524/4716 [24:23<08:14,  2.41it/s]

 75%|███████▍  | 3525/4716 [24:24<08:14,  2.41it/s]

 75%|███████▍  | 3526/4716 [24:24<08:13,  2.41it/s]

 75%|███████▍  | 3527/4716 [24:25<08:13,  2.41it/s]

 75%|███████▍  | 3528/4716 [24:25<08:12,  2.41it/s]

 75%|███████▍  | 3529/4716 [24:25<08:12,  2.41it/s]

 75%|███████▍  | 3530/4716 [24:26<08:11,  2.41it/s]

 75%|███████▍  | 3531/4716 [24:26<08:11,  2.41it/s]

 75%|███████▍  | 3532/4716 [24:27<08:11,  2.41it/s]

 75%|███████▍  | 3533/4716 [24:27<08:10,  2.41it/s]

 75%|███████▍  | 3534/4716 [24:27<08:10,  2.41it/s]

 75%|███████▍  | 3535/4716 [24:28<08:10,  2.41it/s]

 75%|███████▍  | 3536/4716 [24:28<08:10,  2.41it/s]

 75%|███████▌  | 3537/4716 [24:29<08:09,  2.41it/s]

 75%|███████▌  | 3538/4716 [24:29<08:09,  2.41it/s]

 75%|███████▌  | 3539/4716 [24:30<08:08,  2.41it/s]

 75%|███████▌  | 3540/4716 [24:30<08:08,  2.41it/s]

 75%|███████▌  | 3541/4716 [24:30<08:08,  2.41it/s]

 75%|███████▌  | 3542/4716 [24:31<08:07,  2.41it/s]

 75%|███████▌  | 3543/4716 [24:31<08:07,  2.41it/s]

 75%|███████▌  | 3544/4716 [24:32<08:06,  2.41it/s]

 75%|███████▌  | 3545/4716 [24:32<08:06,  2.41it/s]

 75%|███████▌  | 3546/4716 [24:32<08:05,  2.41it/s]

 75%|███████▌  | 3547/4716 [24:33<08:04,  2.41it/s]

 75%|███████▌  | 3548/4716 [24:33<08:04,  2.41it/s]

 75%|███████▌  | 3549/4716 [24:34<08:03,  2.41it/s]

 75%|███████▌  | 3550/4716 [24:34<08:03,  2.41it/s]

 75%|███████▌  | 3551/4716 [24:35<08:03,  2.41it/s]

 75%|███████▌  | 3552/4716 [24:35<08:03,  2.41it/s]

 75%|███████▌  | 3553/4716 [24:35<08:02,  2.41it/s]

 75%|███████▌  | 3554/4716 [24:36<08:02,  2.41it/s]

 75%|███████▌  | 3555/4716 [24:36<08:01,  2.41it/s]

 75%|███████▌  | 3556/4716 [24:37<08:01,  2.41it/s]

 75%|███████▌  | 3557/4716 [24:37<08:00,  2.41it/s]

 75%|███████▌  | 3558/4716 [24:37<08:00,  2.41it/s]

 75%|███████▌  | 3559/4716 [24:38<08:00,  2.41it/s]

 75%|███████▌  | 3560/4716 [24:38<07:59,  2.41it/s]

 76%|███████▌  | 3561/4716 [24:39<07:59,  2.41it/s]

 76%|███████▌  | 3562/4716 [24:39<07:58,  2.41it/s]

 76%|███████▌  | 3563/4716 [24:40<07:58,  2.41it/s]

 76%|███████▌  | 3564/4716 [24:40<07:58,  2.41it/s]

 76%|███████▌  | 3565/4716 [24:40<07:58,  2.41it/s]

 76%|███████▌  | 3566/4716 [24:41<07:57,  2.41it/s]

 76%|███████▌  | 3567/4716 [24:41<07:57,  2.41it/s]

 76%|███████▌  | 3568/4716 [24:42<07:56,  2.41it/s]

 76%|███████▌  | 3569/4716 [24:42<07:55,  2.41it/s]

 76%|███████▌  | 3570/4716 [24:42<07:55,  2.41it/s]

 76%|███████▌  | 3571/4716 [24:43<07:55,  2.41it/s]

 76%|███████▌  | 3572/4716 [24:43<07:55,  2.41it/s]

 76%|███████▌  | 3573/4716 [24:44<07:55,  2.41it/s]

 76%|███████▌  | 3574/4716 [24:44<07:54,  2.41it/s]

 76%|███████▌  | 3575/4716 [24:44<07:53,  2.41it/s]

 76%|███████▌  | 3576/4716 [24:45<07:53,  2.41it/s]

 76%|███████▌  | 3577/4716 [24:45<07:54,  2.40it/s]

 76%|███████▌  | 3578/4716 [24:46<07:53,  2.41it/s]

 76%|███████▌  | 3579/4716 [24:46<07:53,  2.40it/s]

 76%|███████▌  | 3580/4716 [24:47<07:53,  2.40it/s]

 76%|███████▌  | 3581/4716 [24:47<07:51,  2.41it/s]

 76%|███████▌  | 3582/4716 [24:47<07:50,  2.41it/s]

 76%|███████▌  | 3583/4716 [24:48<07:51,  2.40it/s]

 76%|███████▌  | 3584/4716 [24:48<07:51,  2.40it/s]

 76%|███████▌  | 3585/4716 [24:49<07:50,  2.41it/s]

 76%|███████▌  | 3586/4716 [24:49<07:50,  2.40it/s]

 76%|███████▌  | 3587/4716 [24:49<07:49,  2.40it/s]

 76%|███████▌  | 3588/4716 [24:50<07:48,  2.41it/s]

 76%|███████▌  | 3589/4716 [24:50<07:47,  2.41it/s]

 76%|███████▌  | 3590/4716 [24:51<07:47,  2.41it/s]

 76%|███████▌  | 3591/4716 [24:51<07:47,  2.41it/s]

 76%|███████▌  | 3592/4716 [24:52<07:47,  2.40it/s]

 76%|███████▌  | 3593/4716 [24:52<07:47,  2.40it/s]

 76%|███████▌  | 3594/4716 [24:52<07:46,  2.40it/s]

 76%|███████▌  | 3595/4716 [24:53<07:46,  2.40it/s]

 76%|███████▋  | 3596/4716 [24:53<07:46,  2.40it/s]

 76%|███████▋  | 3597/4716 [24:54<07:45,  2.40it/s]

 76%|███████▋  | 3598/4716 [24:54<07:45,  2.40it/s]

 76%|███████▋  | 3599/4716 [24:54<07:44,  2.40it/s]

 76%|███████▋  | 3600/4716 [24:55<07:45,  2.40it/s]

 76%|███████▋  | 3601/4716 [24:55<07:43,  2.40it/s]

 76%|███████▋  | 3602/4716 [24:56<07:44,  2.40it/s]

 76%|███████▋  | 3603/4716 [24:56<07:43,  2.40it/s]

 76%|███████▋  | 3604/4716 [24:57<07:42,  2.40it/s]

 76%|███████▋  | 3605/4716 [24:57<07:41,  2.41it/s]

 76%|███████▋  | 3606/4716 [24:57<07:41,  2.41it/s]

 76%|███████▋  | 3607/4716 [24:58<07:41,  2.41it/s]

 77%|███████▋  | 3608/4716 [24:58<07:40,  2.41it/s]

 77%|███████▋  | 3609/4716 [24:59<07:39,  2.41it/s]

 77%|███████▋  | 3610/4716 [24:59<07:39,  2.40it/s]

 77%|███████▋  | 3611/4716 [24:59<07:39,  2.41it/s]

 77%|███████▋  | 3612/4716 [25:00<07:38,  2.41it/s]

 77%|███████▋  | 3613/4716 [25:00<07:38,  2.41it/s]

 77%|███████▋  | 3614/4716 [25:01<07:37,  2.41it/s]

 77%|███████▋  | 3615/4716 [25:01<07:37,  2.41it/s]

 77%|███████▋  | 3616/4716 [25:02<07:37,  2.40it/s]

 77%|███████▋  | 3617/4716 [25:02<07:37,  2.40it/s]

 77%|███████▋  | 3618/4716 [25:02<07:37,  2.40it/s]

 77%|███████▋  | 3619/4716 [25:03<07:36,  2.40it/s]

 77%|███████▋  | 3620/4716 [25:03<07:35,  2.40it/s]

 77%|███████▋  | 3621/4716 [25:04<07:34,  2.41it/s]

 77%|███████▋  | 3622/4716 [25:04<07:34,  2.40it/s]

 77%|███████▋  | 3623/4716 [25:04<07:35,  2.40it/s]

 77%|███████▋  | 3624/4716 [25:05<07:34,  2.40it/s]

 77%|███████▋  | 3625/4716 [25:05<07:33,  2.40it/s]

 77%|███████▋  | 3626/4716 [25:06<07:33,  2.40it/s]

 77%|███████▋  | 3627/4716 [25:06<07:33,  2.40it/s]

 77%|███████▋  | 3628/4716 [25:07<07:32,  2.40it/s]

 77%|███████▋  | 3629/4716 [25:07<07:32,  2.40it/s]

 77%|███████▋  | 3630/4716 [25:07<07:31,  2.41it/s]

 77%|███████▋  | 3631/4716 [25:08<07:32,  2.40it/s]

 77%|███████▋  | 3632/4716 [25:08<07:31,  2.40it/s]

 77%|███████▋  | 3633/4716 [25:09<07:31,  2.40it/s]

 77%|███████▋  | 3634/4716 [25:09<07:30,  2.40it/s]

 77%|███████▋  | 3635/4716 [25:09<07:30,  2.40it/s]

 77%|███████▋  | 3636/4716 [25:10<07:30,  2.40it/s]

 77%|███████▋  | 3637/4716 [25:10<07:29,  2.40it/s]

 77%|███████▋  | 3638/4716 [25:11<07:28,  2.40it/s]

 77%|███████▋  | 3639/4716 [25:11<07:28,  2.40it/s]

 77%|███████▋  | 3640/4716 [25:12<07:28,  2.40it/s]

 77%|███████▋  | 3641/4716 [25:12<07:28,  2.40it/s]

 77%|███████▋  | 3642/4716 [25:12<07:28,  2.39it/s]

 77%|███████▋  | 3643/4716 [25:13<07:27,  2.40it/s]

 77%|███████▋  | 3644/4716 [25:13<07:26,  2.40it/s]

 77%|███████▋  | 3645/4716 [25:14<07:25,  2.40it/s]

 77%|███████▋  | 3646/4716 [25:14<07:25,  2.40it/s]

 77%|███████▋  | 3647/4716 [25:14<07:24,  2.41it/s]

 77%|███████▋  | 3648/4716 [25:15<07:24,  2.40it/s]

 77%|███████▋  | 3649/4716 [25:15<07:24,  2.40it/s]

 77%|███████▋  | 3650/4716 [25:16<07:25,  2.39it/s]

 77%|███████▋  | 3651/4716 [25:16<07:24,  2.40it/s]

 77%|███████▋  | 3652/4716 [25:17<07:24,  2.39it/s]

 77%|███████▋  | 3653/4716 [25:17<07:23,  2.39it/s]

 77%|███████▋  | 3654/4716 [25:17<07:22,  2.40it/s]

 78%|███████▊  | 3655/4716 [25:18<07:22,  2.40it/s]

 78%|███████▊  | 3656/4716 [25:18<07:21,  2.40it/s]

 78%|███████▊  | 3657/4716 [25:19<07:21,  2.40it/s]

 78%|███████▊  | 3658/4716 [25:19<07:20,  2.40it/s]

 78%|███████▊  | 3659/4716 [25:19<07:19,  2.41it/s]

 78%|███████▊  | 3660/4716 [25:20<07:19,  2.40it/s]

 78%|███████▊  | 3661/4716 [25:20<07:18,  2.40it/s]

 78%|███████▊  | 3662/4716 [25:21<07:18,  2.40it/s]

 78%|███████▊  | 3663/4716 [25:21<07:18,  2.40it/s]

 78%|███████▊  | 3664/4716 [25:22<07:17,  2.40it/s]

 78%|███████▊  | 3665/4716 [25:22<07:17,  2.40it/s]

 78%|███████▊  | 3666/4716 [25:22<07:17,  2.40it/s]

 78%|███████▊  | 3667/4716 [25:23<07:17,  2.40it/s]

 78%|███████▊  | 3668/4716 [25:23<07:16,  2.40it/s]

 78%|███████▊  | 3669/4716 [25:24<07:16,  2.40it/s]

 78%|███████▊  | 3670/4716 [25:24<07:16,  2.40it/s]

 78%|███████▊  | 3671/4716 [25:24<07:15,  2.40it/s]

 78%|███████▊  | 3672/4716 [25:25<07:14,  2.40it/s]

 78%|███████▊  | 3673/4716 [25:25<07:14,  2.40it/s]

 78%|███████▊  | 3674/4716 [25:26<07:13,  2.40it/s]

 78%|███████▊  | 3675/4716 [25:26<07:13,  2.40it/s]

 78%|███████▊  | 3676/4716 [25:27<07:12,  2.40it/s]

 78%|███████▊  | 3677/4716 [25:27<07:12,  2.40it/s]

 78%|███████▊  | 3678/4716 [25:27<07:12,  2.40it/s]

 78%|███████▊  | 3679/4716 [25:28<07:12,  2.40it/s]

 78%|███████▊  | 3680/4716 [25:28<07:11,  2.40it/s]

 78%|███████▊  | 3681/4716 [25:29<07:11,  2.40it/s]

 78%|███████▊  | 3682/4716 [25:29<07:11,  2.40it/s]

 78%|███████▊  | 3683/4716 [25:29<07:11,  2.39it/s]

 78%|███████▊  | 3684/4716 [25:30<07:10,  2.39it/s]

 78%|███████▊  | 3685/4716 [25:30<07:10,  2.39it/s]

 78%|███████▊  | 3686/4716 [25:31<07:10,  2.40it/s]

 78%|███████▊  | 3687/4716 [25:31<07:09,  2.39it/s]

 78%|███████▊  | 3688/4716 [25:32<07:09,  2.40it/s]

 78%|███████▊  | 3689/4716 [25:32<07:09,  2.39it/s]

 78%|███████▊  | 3690/4716 [25:32<07:08,  2.39it/s]

 78%|███████▊  | 3691/4716 [25:33<07:08,  2.39it/s]

 78%|███████▊  | 3692/4716 [25:33<07:07,  2.40it/s]

 78%|███████▊  | 3693/4716 [25:34<07:06,  2.40it/s]

 78%|███████▊  | 3694/4716 [25:34<07:06,  2.40it/s]

 78%|███████▊  | 3695/4716 [25:34<07:06,  2.39it/s]

 78%|███████▊  | 3696/4716 [25:35<07:05,  2.39it/s]

 78%|███████▊  | 3697/4716 [25:35<07:05,  2.39it/s]

 78%|███████▊  | 3698/4716 [25:36<07:05,  2.39it/s]

 78%|███████▊  | 3699/4716 [25:36<07:04,  2.40it/s]

 78%|███████▊  | 3700/4716 [25:37<07:03,  2.40it/s]

 78%|███████▊  | 3701/4716 [25:37<07:03,  2.40it/s]

 78%|███████▊  | 3702/4716 [25:37<07:03,  2.40it/s]

 79%|███████▊  | 3703/4716 [25:38<07:02,  2.40it/s]

 79%|███████▊  | 3704/4716 [25:38<07:02,  2.40it/s]

 79%|███████▊  | 3705/4716 [25:39<07:01,  2.40it/s]

 79%|███████▊  | 3706/4716 [25:39<07:01,  2.40it/s]

 79%|███████▊  | 3707/4716 [25:39<07:01,  2.39it/s]

 79%|███████▊  | 3708/4716 [25:40<07:00,  2.40it/s]

 79%|███████▊  | 3709/4716 [25:40<06:59,  2.40it/s]

 79%|███████▊  | 3710/4716 [25:41<06:59,  2.40it/s]

 79%|███████▊  | 3711/4716 [25:41<06:58,  2.40it/s]

 79%|███████▊  | 3712/4716 [25:42<06:58,  2.40it/s]

 79%|███████▊  | 3713/4716 [25:42<06:57,  2.40it/s]

 79%|███████▉  | 3714/4716 [25:42<06:57,  2.40it/s]

 79%|███████▉  | 3715/4716 [25:43<06:58,  2.39it/s]

 79%|███████▉  | 3716/4716 [25:43<06:58,  2.39it/s]

 79%|███████▉  | 3717/4716 [25:44<06:59,  2.38it/s]

 79%|███████▉  | 3718/4716 [25:44<06:57,  2.39it/s]

 79%|███████▉  | 3719/4716 [25:44<06:57,  2.39it/s]

 79%|███████▉  | 3720/4716 [25:45<06:55,  2.40it/s]

 79%|███████▉  | 3721/4716 [25:45<06:55,  2.39it/s]

 79%|███████▉  | 3722/4716 [25:46<06:55,  2.39it/s]

 79%|███████▉  | 3723/4716 [25:46<06:55,  2.39it/s]

 79%|███████▉  | 3724/4716 [25:47<06:54,  2.39it/s]

 79%|███████▉  | 3725/4716 [25:47<06:54,  2.39it/s]

 79%|███████▉  | 3726/4716 [25:47<06:53,  2.40it/s]

 79%|███████▉  | 3727/4716 [25:48<06:53,  2.39it/s]

 79%|███████▉  | 3728/4716 [25:48<06:52,  2.39it/s]

 79%|███████▉  | 3729/4716 [25:49<06:52,  2.39it/s]

 79%|███████▉  | 3730/4716 [25:49<06:51,  2.40it/s]

 79%|███████▉  | 3731/4716 [25:49<06:51,  2.39it/s]

 79%|███████▉  | 3732/4716 [25:50<06:50,  2.40it/s]

 79%|███████▉  | 3733/4716 [25:50<06:50,  2.40it/s]

 79%|███████▉  | 3734/4716 [25:51<06:49,  2.40it/s]

 79%|███████▉  | 3735/4716 [25:51<06:49,  2.39it/s]

 79%|███████▉  | 3736/4716 [25:52<06:48,  2.40it/s]

 79%|███████▉  | 3737/4716 [25:52<06:48,  2.39it/s]

 79%|███████▉  | 3738/4716 [25:52<06:48,  2.39it/s]

 79%|███████▉  | 3739/4716 [25:53<06:47,  2.40it/s]

 79%|███████▉  | 3740/4716 [25:53<06:47,  2.39it/s]

 79%|███████▉  | 3741/4716 [25:54<06:47,  2.40it/s]

 79%|███████▉  | 3742/4716 [25:54<06:46,  2.39it/s]

 79%|███████▉  | 3743/4716 [25:55<06:46,  2.40it/s]

 79%|███████▉  | 3744/4716 [25:55<06:45,  2.39it/s]

 79%|███████▉  | 3745/4716 [25:55<06:45,  2.39it/s]

 79%|███████▉  | 3746/4716 [25:56<06:45,  2.39it/s]

 79%|███████▉  | 3747/4716 [25:56<06:45,  2.39it/s]

 79%|███████▉  | 3748/4716 [25:57<06:45,  2.39it/s]

 79%|███████▉  | 3749/4716 [25:57<06:44,  2.39it/s]

 80%|███████▉  | 3750/4716 [25:57<06:43,  2.39it/s]

 80%|███████▉  | 3751/4716 [25:58<06:43,  2.39it/s]

 80%|███████▉  | 3752/4716 [25:58<06:43,  2.39it/s]

 80%|███████▉  | 3753/4716 [25:59<06:42,  2.39it/s]

 80%|███████▉  | 3754/4716 [25:59<06:41,  2.39it/s]

 80%|███████▉  | 3755/4716 [26:00<06:41,  2.40it/s]

logging
logging the anndata

 80%|███████▉  | 3756/4716 [26:00<06:53,  2.32it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 80%|███████▉  | 3757/4716 [26:00<06:47,  2.35it/s]

 80%|███████▉  | 3758/4716 [26:01<06:42,  2.38it/s]

 80%|███████▉  | 3759/4716 [26:01<06:39,  2.40it/s]

 80%|███████▉  | 3760/4716 [26:02<06:36,  2.41it/s]

 80%|███████▉  | 3761/4716 [26:02<06:34,  2.42it/s]

 80%|███████▉  | 3762/4716 [26:02<06:32,  2.43it/s]

 80%|███████▉  | 3763/4716 [26:03<06:32,  2.43it/s]

 80%|███████▉  | 3764/4716 [26:03<06:31,  2.43it/s]

 80%|███████▉  | 3765/4716 [26:04<06:30,  2.43it/s]

 80%|███████▉  | 3766/4716 [26:04<06:30,  2.44it/s]

 80%|███████▉  | 3767/4716 [26:04<06:29,  2.44it/s]

 80%|███████▉  | 3768/4716 [26:05<06:29,  2.44it/s]

 80%|███████▉  | 3769/4716 [26:05<06:29,  2.43it/s]

 80%|███████▉  | 3770/4716 [26:06<06:28,  2.43it/s]

 80%|███████▉  | 3771/4716 [26:06<06:28,  2.43it/s]

 80%|███████▉  | 3772/4716 [26:07<06:27,  2.43it/s]

 80%|████████  | 3773/4716 [26:07<06:27,  2.43it/s]

 80%|████████  | 3774/4716 [26:07<06:27,  2.43it/s]

 80%|████████  | 3775/4716 [26:08<06:27,  2.43it/s]

 80%|████████  | 3776/4716 [26:08<06:26,  2.43it/s]

 80%|████████  | 3777/4716 [26:09<06:25,  2.43it/s]

 80%|████████  | 3778/4716 [26:09<06:25,  2.43it/s]

 80%|████████  | 3779/4716 [26:09<06:25,  2.43it/s]

 80%|████████  | 3780/4716 [26:10<06:24,  2.43it/s]

 80%|████████  | 3781/4716 [26:10<06:23,  2.44it/s]

 80%|████████  | 3782/4716 [26:11<06:23,  2.44it/s]

 80%|████████  | 3783/4716 [26:11<06:24,  2.42it/s]

 80%|████████  | 3784/4716 [26:11<06:24,  2.43it/s]

 80%|████████  | 3785/4716 [26:12<06:23,  2.43it/s]

 80%|████████  | 3786/4716 [26:12<06:22,  2.43it/s]

 80%|████████  | 3787/4716 [26:13<06:21,  2.43it/s]

 80%|████████  | 3788/4716 [26:13<06:21,  2.43it/s]

 80%|████████  | 3789/4716 [26:14<06:21,  2.43it/s]

 80%|████████  | 3790/4716 [26:14<06:20,  2.43it/s]

 80%|████████  | 3791/4716 [26:14<06:20,  2.43it/s]

 80%|████████  | 3792/4716 [26:15<06:19,  2.43it/s]

 80%|████████  | 3793/4716 [26:15<06:19,  2.43it/s]

 80%|████████  | 3794/4716 [26:16<06:18,  2.43it/s]

 80%|████████  | 3795/4716 [26:16<06:18,  2.43it/s]

 80%|████████  | 3796/4716 [26:16<06:18,  2.43it/s]

 81%|████████  | 3797/4716 [26:17<06:17,  2.43it/s]

 81%|████████  | 3798/4716 [26:17<06:16,  2.44it/s]

 81%|████████  | 3799/4716 [26:18<06:16,  2.43it/s]

 81%|████████  | 3800/4716 [26:18<06:16,  2.44it/s]

 81%|████████  | 3801/4716 [26:18<06:15,  2.43it/s]

 81%|████████  | 3802/4716 [26:19<06:15,  2.44it/s]

 81%|████████  | 3803/4716 [26:19<06:16,  2.43it/s]

 81%|████████  | 3804/4716 [26:20<06:15,  2.43it/s]

 81%|████████  | 3805/4716 [26:20<06:14,  2.43it/s]

 81%|████████  | 3806/4716 [26:21<06:13,  2.43it/s]

 81%|████████  | 3807/4716 [26:21<06:13,  2.43it/s]

 81%|████████  | 3808/4716 [26:21<06:13,  2.43it/s]

 81%|████████  | 3809/4716 [26:22<06:12,  2.43it/s]

 81%|████████  | 3810/4716 [26:22<06:12,  2.43it/s]

 81%|████████  | 3811/4716 [26:23<06:12,  2.43it/s]

 81%|████████  | 3812/4716 [26:23<06:11,  2.43it/s]

 81%|████████  | 3813/4716 [26:23<06:11,  2.43it/s]

 81%|████████  | 3814/4716 [26:24<06:10,  2.43it/s]

 81%|████████  | 3815/4716 [26:24<06:10,  2.43it/s]

 81%|████████  | 3816/4716 [26:25<06:09,  2.43it/s]

 81%|████████  | 3817/4716 [26:25<06:09,  2.43it/s]

 81%|████████  | 3818/4716 [26:25<06:09,  2.43it/s]

 81%|████████  | 3819/4716 [26:26<06:08,  2.43it/s]

 81%|████████  | 3820/4716 [26:26<06:08,  2.43it/s]

 81%|████████  | 3821/4716 [26:27<06:08,  2.43it/s]

 81%|████████  | 3822/4716 [26:27<06:07,  2.43it/s]

 81%|████████  | 3823/4716 [26:28<06:07,  2.43it/s]

 81%|████████  | 3824/4716 [26:28<06:07,  2.43it/s]

 81%|████████  | 3825/4716 [26:28<06:06,  2.43it/s]

 81%|████████  | 3826/4716 [26:29<06:06,  2.43it/s]

 81%|████████  | 3827/4716 [26:29<06:05,  2.43it/s]

 81%|████████  | 3828/4716 [26:30<06:05,  2.43it/s]

 81%|████████  | 3829/4716 [26:30<06:04,  2.43it/s]

 81%|████████  | 3830/4716 [26:30<06:04,  2.43it/s]

 81%|████████  | 3831/4716 [26:31<06:03,  2.43it/s]

 81%|████████▏ | 3832/4716 [26:31<06:03,  2.43it/s]

 81%|████████▏ | 3833/4716 [26:32<06:03,  2.43it/s]

 81%|████████▏ | 3834/4716 [26:32<06:02,  2.43it/s]

 81%|████████▏ | 3835/4716 [26:32<06:02,  2.43it/s]

 81%|████████▏ | 3836/4716 [26:33<06:01,  2.43it/s]

 81%|████████▏ | 3837/4716 [26:33<06:01,  2.43it/s]

 81%|████████▏ | 3838/4716 [26:34<06:01,  2.43it/s]

 81%|████████▏ | 3839/4716 [26:34<06:01,  2.43it/s]

 81%|████████▏ | 3840/4716 [26:35<06:00,  2.43it/s]

 81%|████████▏ | 3841/4716 [26:35<06:00,  2.43it/s]

 81%|████████▏ | 3842/4716 [26:35<06:00,  2.43it/s]

 81%|████████▏ | 3843/4716 [26:36<06:00,  2.42it/s]

 82%|████████▏ | 3844/4716 [26:36<06:00,  2.42it/s]

 82%|████████▏ | 3845/4716 [26:37<05:59,  2.42it/s]

 82%|████████▏ | 3846/4716 [26:37<05:58,  2.43it/s]

 82%|████████▏ | 3847/4716 [26:37<05:58,  2.42it/s]

 82%|████████▏ | 3848/4716 [26:38<05:58,  2.42it/s]

 82%|████████▏ | 3849/4716 [26:38<05:58,  2.42it/s]

 82%|████████▏ | 3850/4716 [26:39<05:57,  2.42it/s]

 82%|████████▏ | 3851/4716 [26:39<05:56,  2.43it/s]

 82%|████████▏ | 3852/4716 [26:39<05:56,  2.43it/s]

 82%|████████▏ | 3853/4716 [26:40<05:55,  2.43it/s]

 82%|████████▏ | 3854/4716 [26:40<05:55,  2.43it/s]

 82%|████████▏ | 3855/4716 [26:41<05:56,  2.42it/s]

 82%|████████▏ | 3856/4716 [26:41<05:56,  2.42it/s]

 82%|████████▏ | 3857/4716 [26:42<05:55,  2.42it/s]

 82%|████████▏ | 3858/4716 [26:42<05:54,  2.42it/s]

 82%|████████▏ | 3859/4716 [26:42<05:53,  2.42it/s]

 82%|████████▏ | 3860/4716 [26:43<05:53,  2.42it/s]

 82%|████████▏ | 3861/4716 [26:43<05:52,  2.42it/s]

 82%|████████▏ | 3862/4716 [26:44<05:52,  2.43it/s]

 82%|████████▏ | 3863/4716 [26:44<05:52,  2.42it/s]

 82%|████████▏ | 3864/4716 [26:44<05:51,  2.42it/s]

 82%|████████▏ | 3865/4716 [26:45<05:51,  2.42it/s]

 82%|████████▏ | 3866/4716 [26:45<05:50,  2.42it/s]

 82%|████████▏ | 3867/4716 [26:46<05:50,  2.42it/s]

 82%|████████▏ | 3868/4716 [26:46<05:49,  2.42it/s]

 82%|████████▏ | 3869/4716 [26:46<05:49,  2.42it/s]

 82%|████████▏ | 3870/4716 [26:47<05:48,  2.43it/s]

 82%|████████▏ | 3871/4716 [26:47<05:48,  2.43it/s]

 82%|████████▏ | 3872/4716 [26:48<05:47,  2.43it/s]

 82%|████████▏ | 3873/4716 [26:48<05:47,  2.42it/s]

 82%|████████▏ | 3874/4716 [26:49<05:47,  2.43it/s]

 82%|████████▏ | 3875/4716 [26:49<05:46,  2.43it/s]

 82%|████████▏ | 3876/4716 [26:49<05:45,  2.43it/s]

 82%|████████▏ | 3877/4716 [26:50<05:46,  2.42it/s]

 82%|████████▏ | 3878/4716 [26:50<05:45,  2.43it/s]

 82%|████████▏ | 3879/4716 [26:51<05:44,  2.43it/s]

 82%|████████▏ | 3880/4716 [26:51<05:44,  2.43it/s]

 82%|████████▏ | 3881/4716 [26:51<05:43,  2.43it/s]

 82%|████████▏ | 3882/4716 [26:52<05:43,  2.43it/s]

 82%|████████▏ | 3883/4716 [26:52<05:43,  2.43it/s]

 82%|████████▏ | 3884/4716 [26:53<05:43,  2.42it/s]

 82%|████████▏ | 3885/4716 [26:53<05:42,  2.43it/s]

 82%|████████▏ | 3886/4716 [26:53<05:42,  2.43it/s]

 82%|████████▏ | 3887/4716 [26:54<05:41,  2.43it/s]

 82%|████████▏ | 3888/4716 [26:54<05:40,  2.43it/s]

 82%|████████▏ | 3889/4716 [26:55<05:40,  2.43it/s]

 82%|████████▏ | 3890/4716 [26:55<05:40,  2.43it/s]

 83%|████████▎ | 3891/4716 [26:56<05:39,  2.43it/s]

 83%|████████▎ | 3892/4716 [26:56<05:39,  2.43it/s]

 83%|████████▎ | 3893/4716 [26:56<05:38,  2.43it/s]

 83%|████████▎ | 3894/4716 [26:57<05:38,  2.43it/s]

 83%|████████▎ | 3895/4716 [26:57<05:38,  2.43it/s]

 83%|████████▎ | 3896/4716 [26:58<05:37,  2.43it/s]

 83%|████████▎ | 3897/4716 [26:58<05:37,  2.43it/s]

 83%|████████▎ | 3898/4716 [26:58<05:37,  2.43it/s]

 83%|████████▎ | 3899/4716 [26:59<05:36,  2.43it/s]

 83%|████████▎ | 3900/4716 [26:59<05:36,  2.43it/s]

 83%|████████▎ | 3901/4716 [27:00<05:35,  2.43it/s]

 83%|████████▎ | 3902/4716 [27:00<05:35,  2.42it/s]

 83%|████████▎ | 3903/4716 [27:00<05:35,  2.43it/s]

 83%|████████▎ | 3904/4716 [27:01<05:34,  2.43it/s]

 83%|████████▎ | 3905/4716 [27:01<05:34,  2.42it/s]

 83%|████████▎ | 3906/4716 [27:02<05:34,  2.42it/s]

 83%|████████▎ | 3907/4716 [27:02<05:33,  2.43it/s]

 83%|████████▎ | 3908/4716 [27:03<05:32,  2.43it/s]

 83%|████████▎ | 3909/4716 [27:03<05:32,  2.43it/s]

 83%|████████▎ | 3910/4716 [27:03<05:32,  2.43it/s]

 83%|████████▎ | 3911/4716 [27:04<05:31,  2.43it/s]

 83%|████████▎ | 3912/4716 [27:04<05:31,  2.43it/s]

 83%|████████▎ | 3913/4716 [27:05<05:30,  2.43it/s]

 83%|████████▎ | 3914/4716 [27:05<05:30,  2.43it/s]

 83%|████████▎ | 3915/4716 [27:05<05:29,  2.43it/s]

 83%|████████▎ | 3916/4716 [27:06<05:29,  2.43it/s]

 83%|████████▎ | 3917/4716 [27:06<05:29,  2.43it/s]

 83%|████████▎ | 3918/4716 [27:07<05:28,  2.43it/s]

 83%|████████▎ | 3919/4716 [27:07<05:28,  2.43it/s]

 83%|████████▎ | 3920/4716 [27:07<05:27,  2.43it/s]

 83%|████████▎ | 3921/4716 [27:08<05:27,  2.43it/s]

 83%|████████▎ | 3922/4716 [27:08<05:27,  2.43it/s]

 83%|████████▎ | 3923/4716 [27:09<05:26,  2.43it/s]

 83%|████████▎ | 3924/4716 [27:09<05:26,  2.42it/s]

 83%|████████▎ | 3925/4716 [27:10<05:26,  2.42it/s]

 83%|████████▎ | 3926/4716 [27:10<05:25,  2.43it/s]

 83%|████████▎ | 3927/4716 [27:10<05:25,  2.43it/s]

 83%|████████▎ | 3928/4716 [27:11<05:24,  2.43it/s]

 83%|████████▎ | 3929/4716 [27:11<05:24,  2.43it/s]

 83%|████████▎ | 3930/4716 [27:12<05:24,  2.42it/s]

 83%|████████▎ | 3931/4716 [27:12<05:23,  2.43it/s]

 83%|████████▎ | 3932/4716 [27:12<05:23,  2.43it/s]

 83%|████████▎ | 3933/4716 [27:13<05:22,  2.42it/s]

 83%|████████▎ | 3934/4716 [27:13<05:22,  2.42it/s]

 83%|████████▎ | 3935/4716 [27:14<05:21,  2.43it/s]

 83%|████████▎ | 3936/4716 [27:14<05:21,  2.43it/s]

 83%|████████▎ | 3937/4716 [27:15<05:21,  2.43it/s]

 84%|████████▎ | 3938/4716 [27:15<05:20,  2.42it/s]

 84%|████████▎ | 3939/4716 [27:15<05:20,  2.42it/s]

 84%|████████▎ | 3940/4716 [27:16<05:20,  2.42it/s]

 84%|████████▎ | 3941/4716 [27:16<05:20,  2.42it/s]

 84%|████████▎ | 3942/4716 [27:17<05:19,  2.42it/s]

 84%|████████▎ | 3943/4716 [27:17<05:19,  2.42it/s]

 84%|████████▎ | 3944/4716 [27:17<05:18,  2.42it/s]

 84%|████████▎ | 3945/4716 [27:18<05:18,  2.42it/s]

 84%|████████▎ | 3946/4716 [27:18<05:17,  2.42it/s]

 84%|████████▎ | 3947/4716 [27:19<05:17,  2.42it/s]

 84%|████████▎ | 3948/4716 [27:19<05:17,  2.42it/s]

 84%|████████▎ | 3949/4716 [27:19<05:16,  2.42it/s]

 84%|████████▍ | 3950/4716 [27:20<05:15,  2.42it/s]

 84%|████████▍ | 3951/4716 [27:20<05:15,  2.42it/s]

 84%|████████▍ | 3952/4716 [27:21<05:15,  2.42it/s]

 84%|████████▍ | 3953/4716 [27:21<05:14,  2.43it/s]

 84%|████████▍ | 3954/4716 [27:22<05:14,  2.42it/s]

 84%|████████▍ | 3955/4716 [27:22<05:13,  2.42it/s]

 84%|████████▍ | 3956/4716 [27:22<05:13,  2.42it/s]

 84%|████████▍ | 3957/4716 [27:23<05:13,  2.42it/s]

 84%|████████▍ | 3958/4716 [27:23<05:13,  2.42it/s]

 84%|████████▍ | 3959/4716 [27:24<05:12,  2.42it/s]

 84%|████████▍ | 3960/4716 [27:24<05:12,  2.42it/s]

 84%|████████▍ | 3961/4716 [27:24<05:11,  2.42it/s]

 84%|████████▍ | 3962/4716 [27:25<05:11,  2.42it/s]

 84%|████████▍ | 3963/4716 [27:25<05:10,  2.42it/s]

 84%|████████▍ | 3964/4716 [27:26<05:10,  2.42it/s]

 84%|████████▍ | 3965/4716 [27:26<05:10,  2.42it/s]

 84%|████████▍ | 3966/4716 [27:26<05:09,  2.42it/s]

 84%|████████▍ | 3967/4716 [27:27<05:08,  2.43it/s]

 84%|████████▍ | 3968/4716 [27:27<05:08,  2.42it/s]

 84%|████████▍ | 3969/4716 [27:28<05:08,  2.42it/s]

 84%|████████▍ | 3970/4716 [27:28<05:07,  2.42it/s]

 84%|████████▍ | 3971/4716 [27:29<05:07,  2.42it/s]

 84%|████████▍ | 3972/4716 [27:29<05:06,  2.42it/s]

 84%|████████▍ | 3973/4716 [27:29<05:06,  2.42it/s]

 84%|████████▍ | 3974/4716 [27:30<05:05,  2.43it/s]

 84%|████████▍ | 3975/4716 [27:30<05:06,  2.42it/s]

 84%|████████▍ | 3976/4716 [27:31<05:05,  2.42it/s]

 84%|████████▍ | 3977/4716 [27:31<05:05,  2.42it/s]

 84%|████████▍ | 3978/4716 [27:31<05:04,  2.42it/s]

 84%|████████▍ | 3979/4716 [27:32<05:04,  2.42it/s]

 84%|████████▍ | 3980/4716 [27:32<05:03,  2.42it/s]

 84%|████████▍ | 3981/4716 [27:33<05:03,  2.42it/s]

 84%|████████▍ | 3982/4716 [27:33<05:03,  2.42it/s]

 84%|████████▍ | 3983/4716 [27:33<05:02,  2.42it/s]

 84%|████████▍ | 3984/4716 [27:34<05:02,  2.42it/s]

 84%|████████▍ | 3985/4716 [27:34<05:01,  2.42it/s]

 85%|████████▍ | 3986/4716 [27:35<05:01,  2.42it/s]

 85%|████████▍ | 3987/4716 [27:35<05:00,  2.43it/s]

 85%|████████▍ | 3988/4716 [27:36<05:00,  2.42it/s]

 85%|████████▍ | 3989/4716 [27:36<04:59,  2.42it/s]

 85%|████████▍ | 3990/4716 [27:36<04:59,  2.42it/s]

 85%|████████▍ | 3991/4716 [27:37<04:59,  2.42it/s]

 85%|████████▍ | 3992/4716 [27:37<04:58,  2.42it/s]

 85%|████████▍ | 3993/4716 [27:38<04:58,  2.42it/s]

 85%|████████▍ | 3994/4716 [27:38<04:57,  2.42it/s]

 85%|████████▍ | 3995/4716 [27:38<04:57,  2.42it/s]

 85%|████████▍ | 3996/4716 [27:39<04:56,  2.42it/s]

 85%|████████▍ | 3997/4716 [27:39<04:56,  2.42it/s]

 85%|████████▍ | 3998/4716 [27:40<04:56,  2.43it/s]

 85%|████████▍ | 3999/4716 [27:40<04:55,  2.43it/s]

 85%|████████▍ | 4000/4716 [27:41<04:55,  2.43it/s]

 85%|████████▍ | 4001/4716 [27:41<04:55,  2.42it/s]

 85%|████████▍ | 4002/4716 [27:41<04:56,  2.41it/s]

 85%|████████▍ | 4003/4716 [27:42<04:55,  2.41it/s]

 85%|████████▍ | 4004/4716 [27:42<04:54,  2.41it/s]

 85%|████████▍ | 4005/4716 [27:43<04:54,  2.42it/s]

 85%|████████▍ | 4006/4716 [27:43<04:53,  2.42it/s]

 85%|████████▍ | 4007/4716 [27:43<04:52,  2.42it/s]

 85%|████████▍ | 4008/4716 [27:44<04:52,  2.42it/s]

 85%|████████▌ | 4009/4716 [27:44<04:51,  2.42it/s]

 85%|████████▌ | 4010/4716 [27:45<04:52,  2.42it/s]

 85%|████████▌ | 4011/4716 [27:45<04:51,  2.42it/s]

 85%|████████▌ | 4012/4716 [27:45<04:50,  2.42it/s]

 85%|████████▌ | 4013/4716 [27:46<04:50,  2.42it/s]

 85%|████████▌ | 4014/4716 [27:46<04:50,  2.42it/s]

 85%|████████▌ | 4015/4716 [27:47<04:49,  2.42it/s]

 85%|████████▌ | 4016/4716 [27:47<04:49,  2.42it/s]

 85%|████████▌ | 4017/4716 [27:48<04:49,  2.42it/s]

 85%|████████▌ | 4018/4716 [27:48<04:48,  2.42it/s]

 85%|████████▌ | 4019/4716 [27:48<04:48,  2.42it/s]

 85%|████████▌ | 4020/4716 [27:49<04:47,  2.42it/s]

 85%|████████▌ | 4021/4716 [27:49<04:48,  2.41it/s]

 85%|████████▌ | 4022/4716 [27:50<04:47,  2.42it/s]

 85%|████████▌ | 4023/4716 [27:50<04:47,  2.41it/s]

 85%|████████▌ | 4024/4716 [27:50<04:46,  2.42it/s]

 85%|████████▌ | 4025/4716 [27:51<04:46,  2.41it/s]

 85%|████████▌ | 4026/4716 [27:51<04:45,  2.42it/s]

 85%|████████▌ | 4027/4716 [27:52<04:44,  2.42it/s]

 85%|████████▌ | 4028/4716 [27:52<04:44,  2.41it/s]

 85%|████████▌ | 4029/4716 [27:53<04:44,  2.41it/s]

 85%|████████▌ | 4030/4716 [27:53<04:44,  2.42it/s]

 85%|████████▌ | 4031/4716 [27:53<04:43,  2.42it/s]

 85%|████████▌ | 4032/4716 [27:54<04:43,  2.41it/s]

 86%|████████▌ | 4033/4716 [27:54<04:42,  2.42it/s]

 86%|████████▌ | 4034/4716 [27:55<04:42,  2.42it/s]

 86%|████████▌ | 4035/4716 [27:55<04:41,  2.42it/s]

 86%|████████▌ | 4036/4716 [27:55<04:41,  2.42it/s]

 86%|████████▌ | 4037/4716 [27:56<04:40,  2.42it/s]

 86%|████████▌ | 4038/4716 [27:56<04:40,  2.42it/s]

 86%|████████▌ | 4039/4716 [27:57<04:40,  2.42it/s]

 86%|████████▌ | 4040/4716 [27:57<04:39,  2.42it/s]

 86%|████████▌ | 4041/4716 [27:57<04:38,  2.42it/s]

 86%|████████▌ | 4042/4716 [27:58<04:38,  2.42it/s]

 86%|████████▌ | 4043/4716 [27:58<04:38,  2.42it/s]

 86%|████████▌ | 4044/4716 [27:59<04:38,  2.42it/s]

 86%|████████▌ | 4045/4716 [27:59<04:37,  2.42it/s]

 86%|████████▌ | 4046/4716 [28:00<04:37,  2.42it/s]

 86%|████████▌ | 4047/4716 [28:00<04:36,  2.42it/s]

 86%|████████▌ | 4048/4716 [28:00<04:36,  2.42it/s]

 86%|████████▌ | 4049/4716 [28:01<04:36,  2.41it/s]

 86%|████████▌ | 4050/4716 [28:01<04:36,  2.41it/s]

 86%|████████▌ | 4051/4716 [28:02<04:35,  2.42it/s]

 86%|████████▌ | 4052/4716 [28:02<04:34,  2.42it/s]

 86%|████████▌ | 4053/4716 [28:02<04:34,  2.42it/s]

 86%|████████▌ | 4054/4716 [28:03<04:33,  2.42it/s]

 86%|████████▌ | 4055/4716 [28:03<04:33,  2.42it/s]

 86%|████████▌ | 4056/4716 [28:04<04:33,  2.42it/s]

 86%|████████▌ | 4057/4716 [28:04<04:32,  2.41it/s]

 86%|████████▌ | 4058/4716 [28:05<04:32,  2.41it/s]

 86%|████████▌ | 4059/4716 [28:05<04:31,  2.42it/s]

 86%|████████▌ | 4060/4716 [28:05<04:31,  2.41it/s]

 86%|████████▌ | 4061/4716 [28:06<04:31,  2.42it/s]

 86%|████████▌ | 4062/4716 [28:06<04:30,  2.42it/s]

 86%|████████▌ | 4063/4716 [28:07<04:30,  2.42it/s]

 86%|████████▌ | 4064/4716 [28:07<04:30,  2.41it/s]

 86%|████████▌ | 4065/4716 [28:07<04:29,  2.41it/s]

 86%|████████▌ | 4066/4716 [28:08<04:29,  2.42it/s]

 86%|████████▌ | 4067/4716 [28:08<04:28,  2.41it/s]

 86%|████████▋ | 4068/4716 [28:09<04:28,  2.42it/s]

 86%|████████▋ | 4069/4716 [28:09<04:28,  2.41it/s]

 86%|████████▋ | 4070/4716 [28:09<04:27,  2.42it/s]

 86%|████████▋ | 4071/4716 [28:10<04:27,  2.41it/s]

 86%|████████▋ | 4072/4716 [28:10<04:26,  2.41it/s]

 86%|████████▋ | 4073/4716 [28:11<04:26,  2.41it/s]

 86%|████████▋ | 4074/4716 [28:11<04:25,  2.42it/s]

 86%|████████▋ | 4075/4716 [28:12<04:25,  2.41it/s]

 86%|████████▋ | 4076/4716 [28:12<04:25,  2.41it/s]

 86%|████████▋ | 4077/4716 [28:12<04:24,  2.41it/s]

 86%|████████▋ | 4078/4716 [28:13<04:24,  2.41it/s]

 86%|████████▋ | 4079/4716 [28:13<04:24,  2.41it/s]

 87%|████████▋ | 4080/4716 [28:14<04:23,  2.41it/s]

 87%|████████▋ | 4081/4716 [28:14<04:23,  2.41it/s]

 87%|████████▋ | 4082/4716 [28:14<04:22,  2.41it/s]

 87%|████████▋ | 4083/4716 [28:15<04:22,  2.41it/s]

 87%|████████▋ | 4084/4716 [28:15<04:21,  2.41it/s]

 87%|████████▋ | 4085/4716 [28:16<04:21,  2.41it/s]

 87%|████████▋ | 4086/4716 [28:16<04:20,  2.42it/s]

 87%|████████▋ | 4087/4716 [28:17<04:20,  2.42it/s]

 87%|████████▋ | 4088/4716 [28:17<04:20,  2.41it/s]

 87%|████████▋ | 4089/4716 [28:17<04:19,  2.41it/s]

 87%|████████▋ | 4090/4716 [28:18<04:19,  2.41it/s]

 87%|████████▋ | 4091/4716 [28:18<04:19,  2.41it/s]

 87%|████████▋ | 4092/4716 [28:19<04:18,  2.41it/s]

 87%|████████▋ | 4093/4716 [28:19<04:18,  2.41it/s]

 87%|████████▋ | 4094/4716 [28:19<04:17,  2.42it/s]

 87%|████████▋ | 4095/4716 [28:20<04:17,  2.41it/s]

 87%|████████▋ | 4096/4716 [28:20<04:16,  2.42it/s]

 87%|████████▋ | 4097/4716 [28:21<04:16,  2.41it/s]

 87%|████████▋ | 4098/4716 [28:21<04:16,  2.41it/s]

 87%|████████▋ | 4099/4716 [28:21<04:16,  2.41it/s]

 87%|████████▋ | 4100/4716 [28:22<04:15,  2.41it/s]

 87%|████████▋ | 4101/4716 [28:22<04:14,  2.41it/s]

 87%|████████▋ | 4102/4716 [28:23<04:14,  2.41it/s]

 87%|████████▋ | 4103/4716 [28:23<04:13,  2.41it/s]

 87%|████████▋ | 4104/4716 [28:24<04:13,  2.42it/s]

 87%|████████▋ | 4105/4716 [28:24<04:12,  2.42it/s]

 87%|████████▋ | 4106/4716 [28:24<04:12,  2.42it/s]

 87%|████████▋ | 4107/4716 [28:25<04:12,  2.41it/s]

 87%|████████▋ | 4108/4716 [28:25<04:11,  2.41it/s]

 87%|████████▋ | 4109/4716 [28:26<04:11,  2.41it/s]

 87%|████████▋ | 4110/4716 [28:26<04:11,  2.41it/s]

 87%|████████▋ | 4111/4716 [28:26<04:10,  2.41it/s]

 87%|████████▋ | 4112/4716 [28:27<04:10,  2.41it/s]

 87%|████████▋ | 4113/4716 [28:27<04:10,  2.41it/s]

 87%|████████▋ | 4114/4716 [28:28<04:09,  2.41it/s]

 87%|████████▋ | 4115/4716 [28:28<04:09,  2.41it/s]

 87%|████████▋ | 4116/4716 [28:29<04:09,  2.41it/s]

 87%|████████▋ | 4117/4716 [28:29<04:08,  2.41it/s]

 87%|████████▋ | 4118/4716 [28:29<04:08,  2.41it/s]

 87%|████████▋ | 4119/4716 [28:30<04:07,  2.41it/s]

 87%|████████▋ | 4120/4716 [28:30<04:07,  2.41it/s]

 87%|████████▋ | 4121/4716 [28:31<04:06,  2.41it/s]

 87%|████████▋ | 4122/4716 [28:31<04:06,  2.41it/s]

 87%|████████▋ | 4123/4716 [28:31<04:05,  2.41it/s]

 87%|████████▋ | 4124/4716 [28:32<04:05,  2.41it/s]

 87%|████████▋ | 4125/4716 [28:32<04:04,  2.41it/s]

 87%|████████▋ | 4126/4716 [28:33<04:04,  2.41it/s]

 88%|████████▊ | 4127/4716 [28:33<04:04,  2.41it/s]

 88%|████████▊ | 4128/4716 [28:34<04:03,  2.41it/s]

 88%|████████▊ | 4129/4716 [28:34<04:03,  2.41it/s]

 88%|████████▊ | 4130/4716 [28:34<04:03,  2.41it/s]

 88%|████████▊ | 4131/4716 [28:35<04:04,  2.40it/s]

 88%|████████▊ | 4132/4716 [28:35<04:03,  2.40it/s]

 88%|████████▊ | 4133/4716 [28:36<04:02,  2.40it/s]

 88%|████████▊ | 4134/4716 [28:36<04:01,  2.41it/s]

 88%|████████▊ | 4135/4716 [28:36<04:01,  2.41it/s]

 88%|████████▊ | 4136/4716 [28:37<04:00,  2.41it/s]

 88%|████████▊ | 4137/4716 [28:37<04:00,  2.41it/s]

 88%|████████▊ | 4138/4716 [28:38<03:59,  2.41it/s]

 88%|████████▊ | 4139/4716 [28:38<03:59,  2.41it/s]

 88%|████████▊ | 4140/4716 [28:39<03:59,  2.41it/s]

 88%|████████▊ | 4141/4716 [28:39<03:58,  2.41it/s]

 88%|████████▊ | 4142/4716 [28:39<03:58,  2.41it/s]

 88%|████████▊ | 4143/4716 [28:40<03:57,  2.41it/s]

 88%|████████▊ | 4144/4716 [28:40<03:57,  2.41it/s]

 88%|████████▊ | 4145/4716 [28:41<03:56,  2.41it/s]

 88%|████████▊ | 4146/4716 [28:41<03:56,  2.41it/s]

 88%|████████▊ | 4147/4716 [28:41<03:55,  2.41it/s]

 88%|████████▊ | 4148/4716 [28:42<03:55,  2.41it/s]

 88%|████████▊ | 4149/4716 [28:42<03:54,  2.41it/s]

 88%|████████▊ | 4150/4716 [28:43<03:54,  2.41it/s]

 88%|████████▊ | 4151/4716 [28:43<03:53,  2.41it/s]

 88%|████████▊ | 4152/4716 [28:43<03:53,  2.41it/s]

 88%|████████▊ | 4153/4716 [28:44<03:53,  2.41it/s]

 88%|████████▊ | 4154/4716 [28:44<03:52,  2.41it/s]

 88%|████████▊ | 4155/4716 [28:45<03:52,  2.41it/s]

 88%|████████▊ | 4156/4716 [28:45<03:52,  2.41it/s]

 88%|████████▊ | 4157/4716 [28:46<03:51,  2.41it/s]

 88%|████████▊ | 4158/4716 [28:46<03:51,  2.41it/s]

 88%|████████▊ | 4159/4716 [28:46<03:50,  2.41it/s]

 88%|████████▊ | 4160/4716 [28:47<03:50,  2.41it/s]

 88%|████████▊ | 4161/4716 [28:47<03:49,  2.41it/s]

 88%|████████▊ | 4162/4716 [28:48<03:49,  2.41it/s]

 88%|████████▊ | 4163/4716 [28:48<03:48,  2.41it/s]

 88%|████████▊ | 4164/4716 [28:48<03:48,  2.41it/s]

 88%|████████▊ | 4165/4716 [28:49<03:48,  2.41it/s]

 88%|████████▊ | 4166/4716 [28:49<03:48,  2.41it/s]

 88%|████████▊ | 4167/4716 [28:50<03:48,  2.41it/s]

 88%|████████▊ | 4168/4716 [28:50<03:47,  2.41it/s]

 88%|████████▊ | 4169/4716 [28:51<03:46,  2.41it/s]

 88%|████████▊ | 4170/4716 [28:51<03:46,  2.41it/s]

 88%|████████▊ | 4171/4716 [28:51<03:46,  2.41it/s]

 88%|████████▊ | 4172/4716 [28:52<03:45,  2.41it/s]

 88%|████████▊ | 4173/4716 [28:52<03:45,  2.41it/s]

 89%|████████▊ | 4174/4716 [28:53<03:44,  2.41it/s]

 89%|████████▊ | 4175/4716 [28:53<03:44,  2.41it/s]

 89%|████████▊ | 4176/4716 [28:53<03:44,  2.41it/s]

 89%|████████▊ | 4177/4716 [28:54<03:43,  2.41it/s]

 89%|████████▊ | 4178/4716 [28:54<03:43,  2.41it/s]

 89%|████████▊ | 4179/4716 [28:55<03:42,  2.41it/s]

 89%|████████▊ | 4180/4716 [28:55<03:42,  2.41it/s]

 89%|████████▊ | 4181/4716 [28:56<03:42,  2.41it/s]

 89%|████████▊ | 4182/4716 [28:56<03:41,  2.41it/s]

 89%|████████▊ | 4183/4716 [28:56<03:41,  2.41it/s]

 89%|████████▊ | 4184/4716 [28:57<03:40,  2.41it/s]

 89%|████████▊ | 4185/4716 [28:57<03:40,  2.41it/s]

 89%|████████▉ | 4186/4716 [28:58<03:40,  2.40it/s]

 89%|████████▉ | 4187/4716 [28:58<03:39,  2.41it/s]

 89%|████████▉ | 4188/4716 [28:58<03:39,  2.40it/s]

 89%|████████▉ | 4189/4716 [28:59<03:38,  2.41it/s]

 89%|████████▉ | 4190/4716 [28:59<03:38,  2.41it/s]

 89%|████████▉ | 4191/4716 [29:00<03:38,  2.41it/s]

 89%|████████▉ | 4192/4716 [29:00<03:37,  2.41it/s]

 89%|████████▉ | 4193/4716 [29:00<03:37,  2.41it/s]

 89%|████████▉ | 4194/4716 [29:01<03:36,  2.41it/s]

 89%|████████▉ | 4195/4716 [29:01<03:36,  2.41it/s]

 89%|████████▉ | 4196/4716 [29:02<03:35,  2.41it/s]

 89%|████████▉ | 4197/4716 [29:02<03:35,  2.41it/s]

 89%|████████▉ | 4198/4716 [29:03<03:35,  2.41it/s]

 89%|████████▉ | 4199/4716 [29:03<03:34,  2.41it/s]

 89%|████████▉ | 4200/4716 [29:03<03:34,  2.40it/s]

 89%|████████▉ | 4201/4716 [29:04<03:34,  2.40it/s]

 89%|████████▉ | 4202/4716 [29:04<03:33,  2.41it/s]

 89%|████████▉ | 4203/4716 [29:05<03:33,  2.41it/s]

 89%|████████▉ | 4204/4716 [29:05<03:32,  2.41it/s]

 89%|████████▉ | 4205/4716 [29:05<03:32,  2.41it/s]

 89%|████████▉ | 4206/4716 [29:06<03:32,  2.41it/s]

 89%|████████▉ | 4207/4716 [29:06<03:31,  2.41it/s]

 89%|████████▉ | 4208/4716 [29:07<03:31,  2.40it/s]

 89%|████████▉ | 4209/4716 [29:07<03:30,  2.41it/s]

 89%|████████▉ | 4210/4716 [29:08<03:30,  2.40it/s]

 89%|████████▉ | 4211/4716 [29:08<03:30,  2.40it/s]

 89%|████████▉ | 4212/4716 [29:08<03:29,  2.40it/s]

 89%|████████▉ | 4213/4716 [29:09<03:29,  2.41it/s]

 89%|████████▉ | 4214/4716 [29:09<03:28,  2.41it/s]

 89%|████████▉ | 4215/4716 [29:10<03:28,  2.41it/s]

 89%|████████▉ | 4216/4716 [29:10<03:27,  2.41it/s]

 89%|████████▉ | 4217/4716 [29:10<03:27,  2.41it/s]

 89%|████████▉ | 4218/4716 [29:11<03:26,  2.41it/s]

 89%|████████▉ | 4219/4716 [29:11<03:26,  2.41it/s]

 89%|████████▉ | 4220/4716 [29:12<03:25,  2.41it/s]

 90%|████████▉ | 4221/4716 [29:12<03:25,  2.41it/s]

 90%|████████▉ | 4222/4716 [29:13<03:25,  2.41it/s]

 90%|████████▉ | 4223/4716 [29:13<03:24,  2.41it/s]

 90%|████████▉ | 4224/4716 [29:13<03:24,  2.41it/s]

 90%|████████▉ | 4225/4716 [29:14<03:23,  2.41it/s]

 90%|████████▉ | 4226/4716 [29:14<03:23,  2.40it/s]

 90%|████████▉ | 4227/4716 [29:15<03:23,  2.41it/s]

 90%|████████▉ | 4228/4716 [29:15<03:22,  2.41it/s]

 90%|████████▉ | 4229/4716 [29:15<03:22,  2.41it/s]

 90%|████████▉ | 4230/4716 [29:16<03:21,  2.41it/s]

 90%|████████▉ | 4231/4716 [29:16<03:21,  2.41it/s]

 90%|████████▉ | 4232/4716 [29:17<03:21,  2.41it/s]

 90%|████████▉ | 4233/4716 [29:17<03:20,  2.40it/s]

 90%|████████▉ | 4234/4716 [29:18<03:20,  2.40it/s]

 90%|████████▉ | 4235/4716 [29:18<03:20,  2.40it/s]

 90%|████████▉ | 4236/4716 [29:18<03:19,  2.41it/s]

 90%|████████▉ | 4237/4716 [29:19<03:19,  2.40it/s]

 90%|████████▉ | 4238/4716 [29:19<03:18,  2.41it/s]

 90%|████████▉ | 4239/4716 [29:20<03:18,  2.41it/s]

 90%|████████▉ | 4240/4716 [29:20<03:17,  2.41it/s]

 90%|████████▉ | 4241/4716 [29:20<03:17,  2.41it/s]

 90%|████████▉ | 4242/4716 [29:21<03:17,  2.41it/s]

 90%|████████▉ | 4243/4716 [29:21<03:17,  2.40it/s]

 90%|████████▉ | 4244/4716 [29:22<03:16,  2.40it/s]

 90%|█████████ | 4245/4716 [29:22<03:16,  2.40it/s]

 90%|█████████ | 4246/4716 [29:23<03:15,  2.40it/s]

 90%|█████████ | 4247/4716 [29:23<03:15,  2.40it/s]

 90%|█████████ | 4248/4716 [29:23<03:14,  2.40it/s]

 90%|█████████ | 4249/4716 [29:24<03:14,  2.40it/s]

 90%|█████████ | 4250/4716 [29:24<03:14,  2.39it/s]

 90%|█████████ | 4251/4716 [29:25<03:14,  2.40it/s]

 90%|█████████ | 4252/4716 [29:25<03:13,  2.40it/s]

 90%|█████████ | 4253/4716 [29:25<03:12,  2.40it/s]

 90%|█████████ | 4254/4716 [29:26<03:12,  2.40it/s]

 90%|█████████ | 4255/4716 [29:26<03:11,  2.40it/s]

 90%|█████████ | 4256/4716 [29:27<03:11,  2.40it/s]

 90%|█████████ | 4257/4716 [29:27<03:11,  2.40it/s]

 90%|█████████ | 4258/4716 [29:28<03:10,  2.40it/s]

 90%|█████████ | 4259/4716 [29:28<03:10,  2.40it/s]

 90%|█████████ | 4260/4716 [29:28<03:10,  2.40it/s]

 90%|█████████ | 4261/4716 [29:29<03:09,  2.40it/s]

 90%|█████████ | 4262/4716 [29:29<03:09,  2.40it/s]

 90%|█████████ | 4263/4716 [29:30<03:08,  2.40it/s]

 90%|█████████ | 4264/4716 [29:30<03:08,  2.40it/s]

 90%|█████████ | 4265/4716 [29:30<03:07,  2.41it/s]

 90%|█████████ | 4266/4716 [29:31<03:07,  2.40it/s]

 90%|█████████ | 4267/4716 [29:31<03:06,  2.40it/s]

 91%|█████████ | 4268/4716 [29:32<03:06,  2.40it/s]

 91%|█████████ | 4269/4716 [29:32<03:05,  2.40it/s]

 91%|█████████ | 4270/4716 [29:33<03:05,  2.41it/s]

 91%|█████████ | 4271/4716 [29:33<03:05,  2.40it/s]

 91%|█████████ | 4272/4716 [29:33<03:04,  2.40it/s]

 91%|█████████ | 4273/4716 [29:34<03:04,  2.40it/s]

 91%|█████████ | 4274/4716 [29:34<03:04,  2.40it/s]

 91%|█████████ | 4275/4716 [29:35<03:03,  2.40it/s]

 91%|█████████ | 4276/4716 [29:35<03:03,  2.40it/s]

 91%|█████████ | 4277/4716 [29:35<03:02,  2.40it/s]

 91%|█████████ | 4278/4716 [29:36<03:02,  2.40it/s]

 91%|█████████ | 4279/4716 [29:36<03:02,  2.40it/s]

 91%|█████████ | 4280/4716 [29:37<03:01,  2.40it/s]

 91%|█████████ | 4281/4716 [29:37<03:01,  2.40it/s]

 91%|█████████ | 4282/4716 [29:38<03:00,  2.40it/s]

 91%|█████████ | 4283/4716 [29:38<03:01,  2.39it/s]

 91%|█████████ | 4284/4716 [29:38<03:00,  2.40it/s]

 91%|█████████ | 4285/4716 [29:39<02:59,  2.40it/s]

 91%|█████████ | 4286/4716 [29:39<02:59,  2.40it/s]

 91%|█████████ | 4287/4716 [29:40<02:58,  2.40it/s]

 91%|█████████ | 4288/4716 [29:40<02:58,  2.40it/s]

 91%|█████████ | 4289/4716 [29:40<02:58,  2.40it/s]

 91%|█████████ | 4290/4716 [29:41<02:57,  2.40it/s]

 91%|█████████ | 4291/4716 [29:41<02:57,  2.40it/s]

 91%|█████████ | 4292/4716 [29:42<02:56,  2.40it/s]

 91%|█████████ | 4293/4716 [29:42<02:56,  2.39it/s]

 91%|█████████ | 4294/4716 [29:43<02:55,  2.40it/s]

 91%|█████████ | 4295/4716 [29:43<02:55,  2.40it/s]

 91%|█████████ | 4296/4716 [29:43<02:55,  2.40it/s]

 91%|█████████ | 4297/4716 [29:44<02:54,  2.40it/s]

 91%|█████████ | 4298/4716 [29:44<02:54,  2.40it/s]

 91%|█████████ | 4299/4716 [29:45<02:53,  2.40it/s]

 91%|█████████ | 4300/4716 [29:45<02:53,  2.40it/s]

 91%|█████████ | 4301/4716 [29:45<02:53,  2.40it/s]

 91%|█████████ | 4302/4716 [29:46<02:52,  2.40it/s]

 91%|█████████ | 4303/4716 [29:46<02:52,  2.40it/s]

 91%|█████████▏| 4304/4716 [29:47<02:51,  2.40it/s]

 91%|█████████▏| 4305/4716 [29:47<02:51,  2.40it/s]

 91%|█████████▏| 4306/4716 [29:48<02:50,  2.40it/s]

 91%|█████████▏| 4307/4716 [29:48<02:50,  2.40it/s]

 91%|█████████▏| 4308/4716 [29:48<02:50,  2.40it/s]

 91%|█████████▏| 4309/4716 [29:49<02:49,  2.40it/s]

 91%|█████████▏| 4310/4716 [29:49<02:49,  2.40it/s]

 91%|█████████▏| 4311/4716 [29:50<02:49,  2.40it/s]

 91%|█████████▏| 4312/4716 [29:50<02:48,  2.40it/s]

 91%|█████████▏| 4313/4716 [29:50<02:47,  2.40it/s]

 91%|█████████▏| 4314/4716 [29:51<02:47,  2.40it/s]

 91%|█████████▏| 4315/4716 [29:51<02:47,  2.40it/s]

 92%|█████████▏| 4316/4716 [29:52<02:46,  2.40it/s]

 92%|█████████▏| 4317/4716 [29:52<02:46,  2.40it/s]

 92%|█████████▏| 4318/4716 [29:53<02:46,  2.39it/s]

 92%|█████████▏| 4319/4716 [29:53<02:45,  2.40it/s]

 92%|█████████▏| 4320/4716 [29:53<02:45,  2.40it/s]

 92%|█████████▏| 4321/4716 [29:54<02:44,  2.40it/s]

 92%|█████████▏| 4322/4716 [29:54<02:44,  2.40it/s]

 92%|█████████▏| 4323/4716 [29:55<02:43,  2.40it/s]

 92%|█████████▏| 4324/4716 [29:55<02:43,  2.40it/s]

 92%|█████████▏| 4325/4716 [29:55<02:42,  2.40it/s]

 92%|█████████▏| 4326/4716 [29:56<02:42,  2.40it/s]

 92%|█████████▏| 4327/4716 [29:56<02:42,  2.40it/s]

 92%|█████████▏| 4328/4716 [29:57<02:42,  2.39it/s]

 92%|█████████▏| 4329/4716 [29:57<02:41,  2.40it/s]

 92%|█████████▏| 4330/4716 [29:58<02:41,  2.40it/s]

 92%|█████████▏| 4331/4716 [29:58<02:40,  2.40it/s]

 92%|█████████▏| 4332/4716 [29:58<02:40,  2.40it/s]

 92%|█████████▏| 4333/4716 [29:59<02:39,  2.40it/s]

 92%|█████████▏| 4334/4716 [29:59<02:39,  2.40it/s]

 92%|█████████▏| 4335/4716 [30:00<02:38,  2.40it/s]

 92%|█████████▏| 4336/4716 [30:00<02:38,  2.40it/s]

 92%|█████████▏| 4337/4716 [30:00<02:37,  2.40it/s]

 92%|█████████▏| 4338/4716 [30:01<02:37,  2.40it/s]

 92%|█████████▏| 4339/4716 [30:01<02:37,  2.40it/s]

 92%|█████████▏| 4340/4716 [30:02<02:36,  2.40it/s]

 92%|█████████▏| 4341/4716 [30:02<02:36,  2.40it/s]

 92%|█████████▏| 4342/4716 [30:03<02:36,  2.39it/s]

 92%|█████████▏| 4343/4716 [30:03<02:35,  2.39it/s]

 92%|█████████▏| 4344/4716 [30:03<02:35,  2.40it/s]

 92%|█████████▏| 4345/4716 [30:04<02:34,  2.40it/s]

 92%|█████████▏| 4346/4716 [30:04<02:34,  2.40it/s]

 92%|█████████▏| 4347/4716 [30:05<02:33,  2.40it/s]

 92%|█████████▏| 4348/4716 [30:05<02:33,  2.40it/s]

 92%|█████████▏| 4349/4716 [30:05<02:33,  2.40it/s]

 92%|█████████▏| 4350/4716 [30:06<02:32,  2.40it/s]

 92%|█████████▏| 4351/4716 [30:06<02:32,  2.39it/s]

 92%|█████████▏| 4352/4716 [30:07<02:32,  2.39it/s]

 92%|█████████▏| 4353/4716 [30:07<02:31,  2.39it/s]

 92%|█████████▏| 4354/4716 [30:08<02:31,  2.39it/s]

 92%|█████████▏| 4355/4716 [30:08<02:30,  2.40it/s]

 92%|█████████▏| 4356/4716 [30:08<02:30,  2.39it/s]

 92%|█████████▏| 4357/4716 [30:09<02:30,  2.39it/s]

 92%|█████████▏| 4358/4716 [30:09<02:29,  2.39it/s]

 92%|█████████▏| 4359/4716 [30:10<02:29,  2.40it/s]

 92%|█████████▏| 4360/4716 [30:10<02:28,  2.39it/s]

 92%|█████████▏| 4361/4716 [30:10<02:28,  2.40it/s]

 92%|█████████▏| 4362/4716 [30:11<02:27,  2.40it/s]

 93%|█████████▎| 4363/4716 [30:11<02:27,  2.40it/s]

 93%|█████████▎| 4364/4716 [30:12<02:26,  2.40it/s]

 93%|█████████▎| 4365/4716 [30:12<02:27,  2.39it/s]

 93%|█████████▎| 4366/4716 [30:13<02:26,  2.39it/s]

 93%|█████████▎| 4367/4716 [30:13<02:25,  2.39it/s]

 93%|█████████▎| 4368/4716 [30:13<02:25,  2.40it/s]

 93%|█████████▎| 4369/4716 [30:14<02:24,  2.40it/s]

 93%|█████████▎| 4370/4716 [30:14<02:24,  2.39it/s]

 93%|█████████▎| 4371/4716 [30:15<02:24,  2.39it/s]

 93%|█████████▎| 4372/4716 [30:15<02:23,  2.39it/s]

 93%|█████████▎| 4373/4716 [30:15<02:23,  2.40it/s]

 93%|█████████▎| 4374/4716 [30:16<02:22,  2.39it/s]

 93%|█████████▎| 4375/4716 [30:16<02:22,  2.39it/s]

 93%|█████████▎| 4376/4716 [30:17<02:22,  2.39it/s]

 93%|█████████▎| 4377/4716 [30:17<02:21,  2.39it/s]

 93%|█████████▎| 4378/4716 [30:18<02:21,  2.38it/s]

 93%|█████████▎| 4379/4716 [30:18<02:21,  2.39it/s]

 93%|█████████▎| 4380/4716 [30:18<02:20,  2.39it/s]

 93%|█████████▎| 4381/4716 [30:19<02:20,  2.39it/s]

logging
logging the anndata

 93%|█████████▎| 4382/4716 [30:19<02:24,  2.32it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 93%|█████████▎| 4383/4716 [30:20<02:21,  2.35it/s]

 93%|█████████▎| 4384/4716 [30:20<02:19,  2.37it/s]

 93%|█████████▎| 4385/4716 [30:21<02:18,  2.39it/s]

 93%|█████████▎| 4386/4716 [30:21<02:17,  2.41it/s]

 93%|█████████▎| 4387/4716 [30:21<02:16,  2.41it/s]

 93%|█████████▎| 4388/4716 [30:22<02:15,  2.42it/s]

 93%|█████████▎| 4389/4716 [30:22<02:14,  2.42it/s]

 93%|█████████▎| 4390/4716 [30:23<02:14,  2.43it/s]

 93%|█████████▎| 4391/4716 [30:23<02:13,  2.43it/s]

 93%|█████████▎| 4392/4716 [30:23<02:13,  2.43it/s]

 93%|█████████▎| 4393/4716 [30:24<02:12,  2.43it/s]

 93%|█████████▎| 4394/4716 [30:24<02:12,  2.43it/s]

 93%|█████████▎| 4395/4716 [30:25<02:12,  2.42it/s]

 93%|█████████▎| 4396/4716 [30:25<02:11,  2.43it/s]

 93%|█████████▎| 4397/4716 [30:25<02:11,  2.43it/s]

 93%|█████████▎| 4398/4716 [30:26<02:10,  2.44it/s]

 93%|█████████▎| 4399/4716 [30:26<02:10,  2.43it/s]

 93%|█████████▎| 4400/4716 [30:27<02:09,  2.43it/s]

 93%|█████████▎| 4401/4716 [30:27<02:09,  2.43it/s]

 93%|█████████▎| 4402/4716 [30:28<02:08,  2.44it/s]

 93%|█████████▎| 4403/4716 [30:28<02:08,  2.44it/s]

 93%|█████████▎| 4404/4716 [30:28<02:07,  2.44it/s]

 93%|█████████▎| 4405/4716 [30:29<02:07,  2.44it/s]

 93%|█████████▎| 4406/4716 [30:29<02:07,  2.44it/s]

 93%|█████████▎| 4407/4716 [30:30<02:07,  2.42it/s]

 93%|█████████▎| 4408/4716 [30:30<02:06,  2.43it/s]

 93%|█████████▎| 4409/4716 [30:30<02:06,  2.43it/s]

 94%|█████████▎| 4410/4716 [30:31<02:05,  2.43it/s]

 94%|█████████▎| 4411/4716 [30:31<02:05,  2.43it/s]

 94%|█████████▎| 4412/4716 [30:32<02:05,  2.43it/s]

 94%|█████████▎| 4413/4716 [30:32<02:04,  2.43it/s]

 94%|█████████▎| 4414/4716 [30:32<02:04,  2.43it/s]

 94%|█████████▎| 4415/4716 [30:33<02:03,  2.43it/s]

 94%|█████████▎| 4416/4716 [30:33<02:03,  2.43it/s]

 94%|█████████▎| 4417/4716 [30:34<02:02,  2.43it/s]

 94%|█████████▎| 4418/4716 [30:34<02:02,  2.44it/s]

 94%|█████████▎| 4419/4716 [30:35<02:02,  2.43it/s]

 94%|█████████▎| 4420/4716 [30:35<02:01,  2.43it/s]

 94%|█████████▎| 4421/4716 [30:35<02:01,  2.43it/s]

 94%|█████████▍| 4422/4716 [30:36<02:00,  2.43it/s]

 94%|█████████▍| 4423/4716 [30:36<02:00,  2.43it/s]

 94%|█████████▍| 4424/4716 [30:37<02:00,  2.43it/s]

 94%|█████████▍| 4425/4716 [30:37<01:59,  2.43it/s]

 94%|█████████▍| 4426/4716 [30:37<01:59,  2.43it/s]

 94%|█████████▍| 4427/4716 [30:38<01:58,  2.43it/s]

 94%|█████████▍| 4428/4716 [30:38<01:58,  2.43it/s]

 94%|█████████▍| 4429/4716 [30:39<01:57,  2.43it/s]

 94%|█████████▍| 4430/4716 [30:39<01:57,  2.43it/s]

 94%|█████████▍| 4431/4716 [30:39<01:57,  2.44it/s]

 94%|█████████▍| 4432/4716 [30:40<01:56,  2.43it/s]

 94%|█████████▍| 4433/4716 [30:40<01:56,  2.43it/s]

 94%|█████████▍| 4434/4716 [30:41<01:55,  2.43it/s]

 94%|█████████▍| 4435/4716 [30:41<01:55,  2.43it/s]

 94%|█████████▍| 4436/4716 [30:41<01:55,  2.43it/s]

 94%|█████████▍| 4437/4716 [30:42<01:54,  2.43it/s]

 94%|█████████▍| 4438/4716 [30:42<01:54,  2.43it/s]

 94%|█████████▍| 4439/4716 [30:43<01:53,  2.43it/s]

 94%|█████████▍| 4440/4716 [30:43<01:53,  2.44it/s]

 94%|█████████▍| 4441/4716 [30:44<01:53,  2.43it/s]

 94%|█████████▍| 4442/4716 [30:44<01:52,  2.43it/s]

 94%|█████████▍| 4443/4716 [30:44<01:52,  2.43it/s]

 94%|█████████▍| 4444/4716 [30:45<01:51,  2.44it/s]

 94%|█████████▍| 4445/4716 [30:45<01:51,  2.43it/s]

 94%|█████████▍| 4446/4716 [30:46<01:50,  2.43it/s]

 94%|█████████▍| 4447/4716 [30:46<01:50,  2.43it/s]

 94%|█████████▍| 4448/4716 [30:46<01:50,  2.43it/s]

 94%|█████████▍| 4449/4716 [30:47<01:49,  2.43it/s]

 94%|█████████▍| 4450/4716 [30:47<01:49,  2.43it/s]

 94%|█████████▍| 4451/4716 [30:48<01:49,  2.43it/s]

 94%|█████████▍| 4452/4716 [30:48<01:48,  2.43it/s]

 94%|█████████▍| 4453/4716 [30:48<01:48,  2.43it/s]

 94%|█████████▍| 4454/4716 [30:49<01:47,  2.43it/s]

 94%|█████████▍| 4455/4716 [30:49<01:47,  2.43it/s]

 94%|█████████▍| 4456/4716 [30:50<01:47,  2.43it/s]

 95%|█████████▍| 4457/4716 [30:50<01:46,  2.43it/s]

 95%|█████████▍| 4458/4716 [30:51<01:46,  2.43it/s]

 95%|█████████▍| 4459/4716 [30:51<01:45,  2.43it/s]

 95%|█████████▍| 4460/4716 [30:51<01:45,  2.43it/s]

 95%|█████████▍| 4461/4716 [30:52<01:45,  2.43it/s]

 95%|█████████▍| 4462/4716 [30:52<01:44,  2.43it/s]

 95%|█████████▍| 4463/4716 [30:53<01:44,  2.43it/s]

 95%|█████████▍| 4464/4716 [30:53<01:43,  2.43it/s]

 95%|█████████▍| 4465/4716 [30:53<01:43,  2.43it/s]

 95%|█████████▍| 4466/4716 [30:54<01:43,  2.43it/s]

 95%|█████████▍| 4467/4716 [30:54<01:42,  2.43it/s]

 95%|█████████▍| 4468/4716 [30:55<01:42,  2.43it/s]

 95%|█████████▍| 4469/4716 [30:55<01:41,  2.43it/s]

 95%|█████████▍| 4470/4716 [30:55<01:41,  2.43it/s]

 95%|█████████▍| 4471/4716 [30:56<01:40,  2.43it/s]

 95%|█████████▍| 4472/4716 [30:56<01:40,  2.43it/s]

 95%|█████████▍| 4473/4716 [30:57<01:40,  2.43it/s]

 95%|█████████▍| 4474/4716 [30:57<01:39,  2.43it/s]

 95%|█████████▍| 4475/4716 [30:58<01:39,  2.43it/s]

 95%|█████████▍| 4476/4716 [30:58<01:38,  2.43it/s]

 95%|█████████▍| 4477/4716 [30:58<01:38,  2.42it/s]

 95%|█████████▍| 4478/4716 [30:59<01:38,  2.43it/s]

 95%|█████████▍| 4479/4716 [30:59<01:38,  2.41it/s]

 95%|█████████▍| 4480/4716 [31:00<01:37,  2.42it/s]

 95%|█████████▌| 4481/4716 [31:00<01:37,  2.42it/s]

 95%|█████████▌| 4482/4716 [31:00<01:36,  2.42it/s]

 95%|█████████▌| 4483/4716 [31:01<01:36,  2.42it/s]

 95%|█████████▌| 4484/4716 [31:01<01:35,  2.42it/s]

 95%|█████████▌| 4485/4716 [31:02<01:35,  2.42it/s]

 95%|█████████▌| 4486/4716 [31:02<01:34,  2.42it/s]

 95%|█████████▌| 4487/4716 [31:03<01:34,  2.42it/s]

 95%|█████████▌| 4488/4716 [31:03<01:33,  2.43it/s]

 95%|█████████▌| 4489/4716 [31:03<01:33,  2.43it/s]

 95%|█████████▌| 4490/4716 [31:04<01:33,  2.43it/s]

 95%|█████████▌| 4491/4716 [31:04<01:32,  2.43it/s]

 95%|█████████▌| 4492/4716 [31:05<01:32,  2.43it/s]

 95%|█████████▌| 4493/4716 [31:05<01:31,  2.43it/s]

 95%|█████████▌| 4494/4716 [31:05<01:31,  2.42it/s]

 95%|█████████▌| 4495/4716 [31:06<01:31,  2.42it/s]

 95%|█████████▌| 4496/4716 [31:06<01:30,  2.43it/s]

 95%|█████████▌| 4497/4716 [31:07<01:30,  2.43it/s]

 95%|█████████▌| 4498/4716 [31:07<01:29,  2.43it/s]

 95%|█████████▌| 4499/4716 [31:07<01:29,  2.43it/s]

 95%|█████████▌| 4500/4716 [31:08<01:28,  2.43it/s]

 95%|█████████▌| 4501/4716 [31:08<01:28,  2.43it/s]

 95%|█████████▌| 4502/4716 [31:09<01:28,  2.42it/s]

 95%|█████████▌| 4503/4716 [31:09<01:27,  2.43it/s]

 96%|█████████▌| 4504/4716 [31:10<01:27,  2.43it/s]

 96%|█████████▌| 4505/4716 [31:10<01:27,  2.42it/s]

 96%|█████████▌| 4506/4716 [31:10<01:26,  2.42it/s]

 96%|█████████▌| 4507/4716 [31:11<01:26,  2.42it/s]

 96%|█████████▌| 4508/4716 [31:11<01:25,  2.43it/s]

 96%|█████████▌| 4509/4716 [31:12<01:25,  2.43it/s]

 96%|█████████▌| 4510/4716 [31:12<01:24,  2.43it/s]

 96%|█████████▌| 4511/4716 [31:12<01:24,  2.43it/s]

 96%|█████████▌| 4512/4716 [31:13<01:24,  2.43it/s]

 96%|█████████▌| 4513/4716 [31:13<01:23,  2.43it/s]

 96%|█████████▌| 4514/4716 [31:14<01:23,  2.43it/s]

 96%|█████████▌| 4515/4716 [31:14<01:22,  2.43it/s]

 96%|█████████▌| 4516/4716 [31:14<01:22,  2.43it/s]

 96%|█████████▌| 4517/4716 [31:15<01:21,  2.43it/s]

 96%|█████████▌| 4518/4716 [31:15<01:21,  2.43it/s]

 96%|█████████▌| 4519/4716 [31:16<01:21,  2.43it/s]

 96%|█████████▌| 4520/4716 [31:16<01:20,  2.43it/s]

 96%|█████████▌| 4521/4716 [31:17<01:20,  2.43it/s]

 96%|█████████▌| 4522/4716 [31:17<01:19,  2.43it/s]

 96%|█████████▌| 4523/4716 [31:17<01:19,  2.43it/s]

 96%|█████████▌| 4524/4716 [31:18<01:19,  2.43it/s]

 96%|█████████▌| 4525/4716 [31:18<01:18,  2.43it/s]

 96%|█████████▌| 4526/4716 [31:19<01:18,  2.43it/s]

 96%|█████████▌| 4527/4716 [31:19<01:17,  2.42it/s]

 96%|█████████▌| 4528/4716 [31:19<01:17,  2.42it/s]

 96%|█████████▌| 4529/4716 [31:20<01:17,  2.42it/s]

 96%|█████████▌| 4530/4716 [31:20<01:16,  2.42it/s]

 96%|█████████▌| 4531/4716 [31:21<01:16,  2.42it/s]

 96%|█████████▌| 4532/4716 [31:21<01:15,  2.42it/s]

 96%|█████████▌| 4533/4716 [31:21<01:15,  2.43it/s]

 96%|█████████▌| 4534/4716 [31:22<01:15,  2.43it/s]

 96%|█████████▌| 4535/4716 [31:22<01:14,  2.43it/s]

 96%|█████████▌| 4536/4716 [31:23<01:14,  2.43it/s]

 96%|█████████▌| 4537/4716 [31:23<01:13,  2.43it/s]

 96%|█████████▌| 4538/4716 [31:24<01:13,  2.43it/s]

 96%|█████████▌| 4539/4716 [31:24<01:12,  2.43it/s]

 96%|█████████▋| 4540/4716 [31:24<01:12,  2.43it/s]

 96%|█████████▋| 4541/4716 [31:25<01:12,  2.43it/s]

 96%|█████████▋| 4542/4716 [31:25<01:11,  2.43it/s]

 96%|█████████▋| 4543/4716 [31:26<01:11,  2.43it/s]

 96%|█████████▋| 4544/4716 [31:26<01:10,  2.43it/s]

 96%|█████████▋| 4545/4716 [31:26<01:10,  2.43it/s]

 96%|█████████▋| 4546/4716 [31:27<01:10,  2.43it/s]

 96%|█████████▋| 4547/4716 [31:27<01:09,  2.43it/s]

 96%|█████████▋| 4548/4716 [31:28<01:09,  2.43it/s]

 96%|█████████▋| 4549/4716 [31:28<01:08,  2.43it/s]

 96%|█████████▋| 4550/4716 [31:28<01:08,  2.43it/s]

 97%|█████████▋| 4551/4716 [31:29<01:07,  2.43it/s]

 97%|█████████▋| 4552/4716 [31:29<01:07,  2.43it/s]

 97%|█████████▋| 4553/4716 [31:30<01:07,  2.43it/s]

 97%|█████████▋| 4554/4716 [31:30<01:06,  2.43it/s]

 97%|█████████▋| 4555/4716 [31:31<01:06,  2.42it/s]

 97%|█████████▋| 4556/4716 [31:31<01:05,  2.43it/s]

 97%|█████████▋| 4557/4716 [31:31<01:05,  2.43it/s]

 97%|█████████▋| 4558/4716 [31:32<01:05,  2.43it/s]

 97%|█████████▋| 4559/4716 [31:32<01:04,  2.43it/s]

 97%|█████████▋| 4560/4716 [31:33<01:04,  2.43it/s]

 97%|█████████▋| 4561/4716 [31:33<01:03,  2.43it/s]

 97%|█████████▋| 4562/4716 [31:33<01:03,  2.42it/s]

 97%|█████████▋| 4563/4716 [31:34<01:03,  2.43it/s]

 97%|█████████▋| 4564/4716 [31:34<01:02,  2.43it/s]

 97%|█████████▋| 4565/4716 [31:35<01:02,  2.43it/s]

 97%|█████████▋| 4566/4716 [31:35<01:01,  2.43it/s]

 97%|█████████▋| 4567/4716 [31:35<01:01,  2.42it/s]

 97%|█████████▋| 4568/4716 [31:36<01:01,  2.43it/s]

 97%|█████████▋| 4569/4716 [31:36<01:00,  2.42it/s]

 97%|█████████▋| 4570/4716 [31:37<01:00,  2.43it/s]

 97%|█████████▋| 4571/4716 [31:37<00:59,  2.43it/s]

 97%|█████████▋| 4572/4716 [31:38<00:59,  2.42it/s]

 97%|█████████▋| 4573/4716 [31:38<00:58,  2.43it/s]

 97%|█████████▋| 4574/4716 [31:38<00:58,  2.43it/s]

 97%|█████████▋| 4575/4716 [31:39<00:58,  2.43it/s]

 97%|█████████▋| 4576/4716 [31:39<00:57,  2.42it/s]

 97%|█████████▋| 4577/4716 [31:40<00:57,  2.42it/s]

 97%|█████████▋| 4578/4716 [31:40<00:57,  2.42it/s]

 97%|█████████▋| 4579/4716 [31:40<00:56,  2.42it/s]

 97%|█████████▋| 4580/4716 [31:41<00:56,  2.42it/s]

 97%|█████████▋| 4581/4716 [31:41<00:55,  2.42it/s]

 97%|█████████▋| 4582/4716 [31:42<00:55,  2.42it/s]

 97%|█████████▋| 4583/4716 [31:42<00:54,  2.42it/s]

 97%|█████████▋| 4584/4716 [31:42<00:54,  2.42it/s]

 97%|█████████▋| 4585/4716 [31:43<00:53,  2.43it/s]

 97%|█████████▋| 4586/4716 [31:43<00:53,  2.42it/s]

 97%|█████████▋| 4587/4716 [31:44<00:53,  2.42it/s]

 97%|█████████▋| 4588/4716 [31:44<00:52,  2.42it/s]

 97%|█████████▋| 4589/4716 [31:45<00:52,  2.42it/s]

 97%|█████████▋| 4590/4716 [31:45<00:52,  2.42it/s]

 97%|█████████▋| 4591/4716 [31:45<00:51,  2.42it/s]

 97%|█████████▋| 4592/4716 [31:46<00:51,  2.42it/s]

 97%|█████████▋| 4593/4716 [31:46<00:50,  2.42it/s]

 97%|█████████▋| 4594/4716 [31:47<00:50,  2.42it/s]

 97%|█████████▋| 4595/4716 [31:47<00:50,  2.42it/s]

 97%|█████████▋| 4596/4716 [31:47<00:49,  2.42it/s]

 97%|█████████▋| 4597/4716 [31:48<00:49,  2.42it/s]

 97%|█████████▋| 4598/4716 [31:48<00:48,  2.42it/s]

 98%|█████████▊| 4599/4716 [31:49<00:48,  2.42it/s]

 98%|█████████▊| 4600/4716 [31:49<00:48,  2.42it/s]

 98%|█████████▊| 4601/4716 [31:50<00:47,  2.42it/s]

 98%|█████████▊| 4602/4716 [31:50<00:47,  2.42it/s]

 98%|█████████▊| 4603/4716 [31:50<00:46,  2.42it/s]

 98%|█████████▊| 4604/4716 [31:51<00:46,  2.42it/s]

 98%|█████████▊| 4605/4716 [31:51<00:45,  2.42it/s]

 98%|█████████▊| 4606/4716 [31:52<00:45,  2.42it/s]

 98%|█████████▊| 4607/4716 [31:52<00:45,  2.42it/s]

 98%|█████████▊| 4608/4716 [31:52<00:44,  2.42it/s]

 98%|█████████▊| 4609/4716 [31:53<00:44,  2.42it/s]

 98%|█████████▊| 4610/4716 [31:53<00:43,  2.42it/s]

 98%|█████████▊| 4611/4716 [31:54<00:43,  2.42it/s]

 98%|█████████▊| 4612/4716 [31:54<00:42,  2.42it/s]

 98%|█████████▊| 4613/4716 [31:54<00:42,  2.42it/s]

 98%|█████████▊| 4614/4716 [31:55<00:42,  2.42it/s]

 98%|█████████▊| 4615/4716 [31:55<00:41,  2.42it/s]

 98%|█████████▊| 4616/4716 [31:56<00:41,  2.42it/s]

 98%|█████████▊| 4617/4716 [31:56<00:40,  2.42it/s]

 98%|█████████▊| 4618/4716 [31:57<00:40,  2.42it/s]

 98%|█████████▊| 4619/4716 [31:57<00:40,  2.42it/s]

 98%|█████████▊| 4620/4716 [31:57<00:39,  2.42it/s]

 98%|█████████▊| 4621/4716 [31:58<00:39,  2.42it/s]

 98%|█████████▊| 4622/4716 [31:58<00:38,  2.42it/s]

 98%|█████████▊| 4623/4716 [31:59<00:38,  2.42it/s]

 98%|█████████▊| 4624/4716 [31:59<00:37,  2.42it/s]

 98%|█████████▊| 4625/4716 [31:59<00:37,  2.42it/s]

 98%|█████████▊| 4626/4716 [32:00<00:37,  2.41it/s]

 98%|█████████▊| 4627/4716 [32:00<00:36,  2.41it/s]

 98%|█████████▊| 4628/4716 [32:01<00:36,  2.41it/s]

 98%|█████████▊| 4629/4716 [32:01<00:36,  2.42it/s]

 98%|█████████▊| 4630/4716 [32:01<00:35,  2.42it/s]

 98%|█████████▊| 4631/4716 [32:02<00:35,  2.42it/s]

 98%|█████████▊| 4632/4716 [32:02<00:34,  2.42it/s]

 98%|█████████▊| 4633/4716 [32:03<00:34,  2.42it/s]

 98%|█████████▊| 4634/4716 [32:03<00:33,  2.41it/s]

 98%|█████████▊| 4635/4716 [32:04<00:33,  2.42it/s]

 98%|█████████▊| 4636/4716 [32:04<00:33,  2.42it/s]

 98%|█████████▊| 4637/4716 [32:04<00:32,  2.42it/s]

 98%|█████████▊| 4638/4716 [32:05<00:32,  2.42it/s]

 98%|█████████▊| 4639/4716 [32:05<00:31,  2.42it/s]

 98%|█████████▊| 4640/4716 [32:06<00:31,  2.42it/s]

 98%|█████████▊| 4641/4716 [32:06<00:31,  2.42it/s]

 98%|█████████▊| 4642/4716 [32:06<00:30,  2.42it/s]

 98%|█████████▊| 4643/4716 [32:07<00:30,  2.42it/s]

 98%|█████████▊| 4644/4716 [32:07<00:29,  2.42it/s]

 98%|█████████▊| 4645/4716 [32:08<00:29,  2.42it/s]

 99%|█████████▊| 4646/4716 [32:08<00:28,  2.42it/s]

 99%|█████████▊| 4647/4716 [32:09<00:28,  2.41it/s]

 99%|█████████▊| 4648/4716 [32:09<00:28,  2.42it/s]

 99%|█████████▊| 4649/4716 [32:09<00:27,  2.42it/s]

 99%|█████████▊| 4650/4716 [32:10<00:27,  2.42it/s]

 99%|█████████▊| 4651/4716 [32:10<00:26,  2.42it/s]

 99%|█████████▊| 4652/4716 [32:11<00:26,  2.42it/s]

 99%|█████████▊| 4653/4716 [32:11<00:26,  2.42it/s]

 99%|█████████▊| 4654/4716 [32:11<00:25,  2.42it/s]

 99%|█████████▊| 4655/4716 [32:12<00:25,  2.42it/s]

 99%|█████████▊| 4656/4716 [32:12<00:24,  2.42it/s]

 99%|█████████▊| 4657/4716 [32:13<00:24,  2.42it/s]

 99%|█████████▉| 4658/4716 [32:13<00:23,  2.42it/s]

 99%|█████████▉| 4659/4716 [32:13<00:23,  2.42it/s]

 99%|█████████▉| 4660/4716 [32:14<00:23,  2.42it/s]

 99%|█████████▉| 4661/4716 [32:14<00:22,  2.42it/s]

 99%|█████████▉| 4662/4716 [32:15<00:22,  2.42it/s]

 99%|█████████▉| 4663/4716 [32:15<00:21,  2.42it/s]

 99%|█████████▉| 4664/4716 [32:16<00:21,  2.42it/s]

 99%|█████████▉| 4665/4716 [32:16<00:21,  2.42it/s]

 99%|█████████▉| 4666/4716 [32:16<00:20,  2.42it/s]

 99%|█████████▉| 4667/4716 [32:17<00:20,  2.41it/s]

 99%|█████████▉| 4668/4716 [32:17<00:19,  2.41it/s]

 99%|█████████▉| 4669/4716 [32:18<00:19,  2.41it/s]

 99%|█████████▉| 4670/4716 [32:18<00:19,  2.41it/s]

 99%|█████████▉| 4671/4716 [32:18<00:18,  2.41it/s]

 99%|█████████▉| 4672/4716 [32:19<00:18,  2.41it/s]

 99%|█████████▉| 4673/4716 [32:19<00:17,  2.41it/s]

 99%|█████████▉| 4674/4716 [32:20<00:17,  2.42it/s]

 99%|█████████▉| 4675/4716 [32:20<00:16,  2.42it/s]

 99%|█████████▉| 4676/4716 [32:21<00:16,  2.41it/s]

 99%|█████████▉| 4677/4716 [32:21<00:16,  2.42it/s]

 99%|█████████▉| 4678/4716 [32:21<00:15,  2.41it/s]

 99%|█████████▉| 4679/4716 [32:22<00:15,  2.41it/s]

 99%|█████████▉| 4680/4716 [32:22<00:14,  2.41it/s]

 99%|█████████▉| 4681/4716 [32:23<00:14,  2.41it/s]

 99%|█████████▉| 4682/4716 [32:23<00:14,  2.41it/s]

 99%|█████████▉| 4683/4716 [32:23<00:13,  2.41it/s]

 99%|█████████▉| 4684/4716 [32:24<00:13,  2.41it/s]

 99%|█████████▉| 4685/4716 [32:24<00:12,  2.41it/s]

 99%|█████████▉| 4686/4716 [32:25<00:12,  2.41it/s]

 99%|█████████▉| 4687/4716 [32:25<00:12,  2.41it/s]

 99%|█████████▉| 4688/4716 [32:26<00:11,  2.41it/s]

 99%|█████████▉| 4689/4716 [32:26<00:11,  2.41it/s]

 99%|█████████▉| 4690/4716 [32:26<00:10,  2.42it/s]

 99%|█████████▉| 4691/4716 [32:27<00:10,  2.41it/s]

 99%|█████████▉| 4692/4716 [32:27<00:09,  2.42it/s]

100%|█████████▉| 4693/4716 [32:28<00:09,  2.41it/s]

100%|█████████▉| 4694/4716 [32:28<00:09,  2.41it/s]

100%|█████████▉| 4695/4716 [32:28<00:08,  2.41it/s]

100%|█████████▉| 4696/4716 [32:29<00:08,  2.41it/s]

100%|█████████▉| 4697/4716 [32:29<00:07,  2.41it/s]

100%|█████████▉| 4698/4716 [32:30<00:07,  2.41it/s]

100%|█████████▉| 4699/4716 [32:30<00:07,  2.41it/s]

100%|█████████▉| 4700/4716 [32:30<00:06,  2.41it/s]

100%|█████████▉| 4701/4716 [32:31<00:06,  2.41it/s]

100%|█████████▉| 4702/4716 [32:31<00:05,  2.41it/s]

100%|█████████▉| 4703/4716 [32:32<00:05,  2.41it/s]

100%|█████████▉| 4704/4716 [32:32<00:04,  2.41it/s]

100%|█████████▉| 4705/4716 [32:33<00:04,  2.41it/s]

100%|█████████▉| 4706/4716 [32:33<00:04,  2.41it/s]

100%|█████████▉| 4707/4716 [32:33<00:03,  2.41it/s]

100%|█████████▉| 4708/4716 [32:34<00:03,  2.41it/s]

100%|█████████▉| 4709/4716 [32:34<00:02,  2.42it/s]

100%|█████████▉| 4710/4716 [32:35<00:02,  2.41it/s]

100%|█████████▉| 4711/4716 [32:35<00:02,  2.42it/s]

100%|█████████▉| 4712/4716 [32:35<00:01,  2.42it/s]

100%|█████████▉| 4713/4716 [32:36<00:01,  2.42it/s]

100%|█████████▉| 4714/4716 [32:36<00:00,  2.42it/s]

100%|█████████▉| 4715/4716 [32:37<00:00,  2.41it/s]

100%|██████████| 4716/4716 [32:37<00:00,  2.65it/s]

100%|██████████| 4716/4716 [32:38<00:00,  2.41it/s]

logging the anndata
AnnData object with n_obs × n_vars = 21348 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

too few cells to embed into a umap
too few cells to compute a clustering

PairwiseArrays with keys: connectivities, distances

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.563617 -10.893947 -18.881716 ... -12.81886   -9.948925  -9.411334]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.244153 -13.754114 -13.45663  ... -14.603881 -13.968375 -14.244924]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.041462 -11.282833 -20.877981 ... -11.50654   -8.453768  -8.710994]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.590944  -9.772922 -15.182728 ... -11.472412  -9.14322   -8.803176]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.4294   -14.931754 -23.57626  ... -14.069737 -11.800607 -12.100268]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.249495 -13.648692 -13.442072 ... -14.480756 -13.858893 -14.132957]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.146185  -13.1955805 -12.953807  ... -14.084785  -13.31437
 -13.576982 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.405237  -16.267332  -20.888678  ... -15.3099575 -14.117388
 -15.69593  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.269842 -19.847954 -23.599915 ... -18.907022 -16.393806 -17.422058]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.316563 -20.995937 -17.73009  ... -21.926489 -19.640234 -19.741583]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.275913 -17.370508 -21.33396  ... -18.784964 -17.387815 -16.571781]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.699385 -17.9748   -13.800481 ... -21.67007  -19.128399 -21.487936]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.608417  -13.383167  -13.414845  ... -13.943566  -13.2778015
 -11.941015 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.854958   -8.273032  -10.266169  ...  -9.676504   -7.6810937
  -8.194425 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.029919 -14.421223 -17.952038 ... -15.52542  -15.100529 -14.98164 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.923673   -6.8646975  -7.6844535 ... -10.628564   -7.532937
  -8.778167 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.615993 -17.201218 -19.454472 ... -18.224407 -17.97483  -14.186622]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.773506 -16.283127 -16.8999   ... -19.371723 -18.025105 -16.689121]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.675005 -12.711767  -8.673459 ... -18.965551 -14.703952 -17.099426]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.028374 -20.694187 -10.025389 ... -25.466211 -22.372145 -24.563398]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.28734  -15.324583 -21.346777 ... -19.0084   -18.411776 -18.50235 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.059574 -10.192696 -15.959258 ... -11.771328  -9.385105  -8.907169]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.8220057 -3.1293058 -6.5999475 ... -6.314463  -6.0306177 -4.2122693]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.726187 -16.395912 -25.543007 ... -12.152295 -12.397356 -11.741819]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -5.7821393  -7.175834  -11.587203  ...  -6.4359775  -6.82577
  -6.8540096]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.036929 -11.740299 -14.004059 ... -10.32568  -10.230126 -10.08236 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -2.354169   -1.3811063 -13.349866  ...   2.5310652   2.5580711
   2.885887 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.06129032  1.2427514  -8.232992   ... -0.37925956  0.6455329
 -1.1950196 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.12100981  0.8072106  -8.977398   ... -0.3328696  -0.32413432
  0.60302603]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.851481   -7.6091166 -10.133962  ...  -9.53026    -7.69368
  -7.757185 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.18854   -9.661539 -12.80232  ...  -8.815257  -9.265247  -7.809402]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.689116 -14.67373  -19.983234 ... -16.268822 -13.356357 -15.200313]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.906981   -8.485065  -13.761965  ... -10.025829   -7.5274324
  -6.686966 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-27.47425  -24.878363 -27.961458 ... -21.981937 -22.429762 -17.74289 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.208174 -18.706041 -15.740378 ... -17.540415 -16.369196 -18.597021]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.865246 -20.2462   -15.249202 ... -18.692867 -16.928108 -18.307035]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.8379426 -7.108069  -8.41821   ... -7.9370265 -7.026356  -6.1858125]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.128885   -6.376553  -10.934783  ...  -7.739715   -7.3306
  -6.2231016]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.616006 -12.434084 -11.992308 ... -12.639364 -10.576291 -10.093325]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.813306 -8.294596 -9.618964 ... -9.691788 -9.016302 -8.589861]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.39865  -18.914106 -17.21103  ... -20.737135 -18.956211 -19.471518]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.445352  -8.865429 -14.807003 ... -10.021618  -8.023054  -8.150906]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-27.636925 -24.887012 -24.457659 ... -25.632107 -24.134722 -21.443596]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.09097   -3.8905163 -6.246029  ... -7.4261465 -6.8737874 -5.1184525]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.435644  -6.9273367 -9.017894  ... -7.8597665 -5.5553284 -5.5623484]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.360054 -15.600711 -16.763754 ... -16.287674 -14.849143 -13.560931]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.294579 -12.761096 -13.085328 ... -13.273251 -12.743117 -13.050554]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.961507 -13.317583 -13.590684 ... -14.163287 -13.49146  -13.783104]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.237944  -9.671008 -13.710723 ... -11.030603  -9.41897   -9.392008]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-25.235611 -21.324566 -23.842113 ... -20.387653 -19.819305 -16.013845]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.49016  -14.384353 -14.19686  ... -15.277066 -14.530087 -14.739825]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.4190755 -5.4326277 -8.713315  ... -6.8547873 -6.269933  -5.8709645]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.0013204 -4.4583125 -7.2621617 ... -7.380718  -6.682748  -5.0648384]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.423407   -5.6402445 -10.38183   ...  -6.021462   -5.236837
  -4.4506354]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.111063 -10.308022 -18.248184 ... -11.564386  -9.871341  -7.608319]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.730711 -18.856049 -16.464973 ... -21.145786 -20.319801 -19.40263 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-24.665695 -21.378616 -21.898867 ... -24.338547 -21.916246 -21.047646]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.750133  -15.028216   -8.001747  ... -15.859293  -13.881152
 -14.6556425]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.295599  -9.407997  -8.239512 ... -12.312394  -9.189037  -9.280492]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.751675 -19.78224  -19.937906 ... -22.689198 -22.01502  -21.059357]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.492026   -7.8329854 -11.559641  ...  -9.084551   -6.852989
  -7.9206285]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.171616 -17.602747 -21.365528 ... -17.16969  -15.013758 -15.503115]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.790196 -13.322506 -13.373483 ... -13.792337 -12.895014 -13.624701]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-25.203691 -17.81339  -19.354025 ... -20.565807 -18.048218 -16.368372]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-25.26256  -23.951603 -11.925164 ... -23.935389 -19.808674 -21.924196]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.7284656 -5.5973334 -7.898248  ... -6.940945  -5.051376  -7.310924 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.2546854 -7.0733957 -8.99819   ... -8.318959  -6.5324683 -8.875728 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.3014765 -5.5548983 -8.583567  ... -6.5369825 -5.9477406 -6.594502 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.091745 -22.755596 -22.397085 ... -22.03817  -21.22265  -22.986757]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.2506137 -5.002115  -3.578765  ... -5.8169374 -4.4834995 -3.9928052]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.8563647 -5.858347  -7.503812  ... -6.5910673 -4.719919  -5.37993  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-27.33199  -19.181906 -27.458382 ... -17.700245 -15.549355 -12.89071 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.528745  -8.748282  -8.98489  ... -12.376036 -10.29819   -9.847621]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.096293   -7.030255  -10.323231  ...  -9.887967   -9.597826
  -7.0884633]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.891182 -16.11653  -21.019161 ... -18.649899 -18.364998 -12.089724]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.422228   -9.6106825  -8.741357  ... -11.159349  -10.117344
  -7.7856183]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.77492  -22.278805 -28.563646 ... -23.098377 -22.07071  -24.230555]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.166316   -7.705537   -6.7425995 ... -10.483629   -9.947874
  -8.572998 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.675898 -19.784525 -22.630123 ... -17.039877 -17.846806 -19.221436]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.5387   -14.024592 -16.111376 ... -15.840518 -14.903788 -13.959535]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.410769  -7.591528  -8.9571705 ... -8.178503  -6.684222  -5.761447 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.882881 -18.166471 -21.638601 ... -17.064405 -16.520119 -13.14289 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.937834 -10.406    -11.24329  ... -11.172174 -10.648322 -10.932996]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.378984 -19.373886 -21.658352 ... -20.913134 -18.969109 -18.971066]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.765597 -12.652566  -9.435274 ... -10.600817 -10.502161 -11.367066]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.332183  -7.2867455 -7.9282465 ... -9.649291  -8.686021  -7.093346 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.37918  -10.821511 -11.547563 ... -14.623321 -13.41504  -12.057025]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.3597145  -9.116464  -10.291694  ... -10.617921   -8.8567
  -9.310169 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.396202 -12.994862 -18.089174 ... -13.562738 -12.894622 -10.131291]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.701381 -10.36227  -13.591047 ... -10.705343 -10.327727  -8.998968]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.499942 -10.187669 -14.058938 ... -10.604701 -10.28635   -9.006895]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.343899  -14.494786  -18.714453  ... -13.17304   -11.2477045
 -11.9973755]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.387615 -18.317968 -15.806898 ... -19.594746 -18.411371 -18.932728]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.913866 -16.490236 -15.428967 ... -17.442554 -16.320742 -16.769102]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.986265   -8.5277    -11.150975  ...  -9.050884   -7.1608315
  -7.6727896]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.667615 -14.54463  -17.365196 ... -14.801909 -15.459161 -11.831853]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.680307 -21.819689 -20.95291  ... -22.527147 -20.63179  -21.197239]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.165525 -12.596842 -13.759486 ... -13.024165 -12.015546 -11.255883]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.270638   -7.0348988 -10.647127  ...  -8.071659   -6.1914306
  -6.673606 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-24.430418 -23.352663 -19.097954 ... -24.37038  -22.052628 -24.071482]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.474333   -8.55866   -12.187238  ...  -9.364819   -7.3349743
  -7.9827285]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.108866 -22.513784 -16.938398 ... -23.474358 -21.127443 -22.293451]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.160411   -8.600015  -11.431344  ...  -9.239604   -7.125636
  -7.7623787]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.00761  -15.653404 -16.39461  ... -17.793013 -15.497914 -14.076731]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.285286 -15.057308 -15.014372 ... -15.523595 -14.576579 -12.444296]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.763181 -15.691015 -20.915775 ... -15.351595 -16.71031  -13.085132]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.032497 -21.89575  -20.782127 ... -23.190672 -22.241756 -21.366343]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.527632 -10.010669 -11.632023 ... -11.487599  -9.449836  -9.594324]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.237493 -11.595106 -12.913553 ... -12.036794 -11.252109 -12.001412]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.808584  -13.361726  -12.751381  ... -14.1080475 -13.511388
 -13.825465 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.156397  -8.568856 -10.70558  ...  -9.037299  -7.248451  -6.820678]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.766462 -18.890596 -19.914902 ... -19.078732 -17.951511 -16.116655]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.81661  -7.210384 -9.717111 ... -9.844485 -7.945693 -8.027005]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-26.244318 -24.265823 -30.422487 ... -23.897833 -25.009413 -20.618979]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.405596 -22.190783 -18.342464 ... -25.402914 -23.750437 -22.842173]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.791477  -13.1407175 -11.788359  ... -15.869997  -14.438564
 -17.749271 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.464619 -20.49332  -20.3545   ... -23.949345 -23.142244 -21.504025]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.34664  -25.19335  -22.482073 ... -25.021639 -24.078724 -23.855465]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.903389 -18.768305 -18.122076 ... -20.73284  -19.366152 -18.025028]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.23232    -7.3044143 -13.056377  ...  -8.5975895  -6.878409
  -7.2506604]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.109737 -12.501655 -14.177367 ... -14.264845 -12.95103  -13.190548]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.588748   -6.261638  -12.317427  ...  -7.2509875  -6.41813
  -6.525953 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.821314 -10.653514 -14.498375 ... -12.467942  -9.740428  -9.247944]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-25.377773 -22.225883 -23.484262 ... -23.22014  -21.263264 -20.230299]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.031646  -9.196573 -12.738805 ... -10.40747   -8.57431   -9.203149]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.742908 -15.493506 -14.969007 ... -18.438288 -16.725924 -16.11779 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.6222105  -9.157094  -12.078049  ... -10.455844   -7.8037705
  -8.724251 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.1050205  -8.783258  -11.826741  ...  -9.41424    -7.1158643
  -8.07895  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.270527   -6.334209  -10.133812  ...  -7.540067   -5.2128887
  -6.4385915]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.060907   -7.0700703 -10.894337  ...  -8.187886   -5.8467407
  -7.0654955]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.75989  -18.961252 -18.42801  ... -19.924564 -18.754038 -17.78278 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.7657785 -6.834066  -9.127596  ... -8.583568  -6.2710295 -8.518429 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.376495  -12.957859  -13.0144005 ... -13.636569  -13.051792
 -13.337132 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.902431 -15.23538  -15.558015 ... -16.76771  -15.578642 -16.450748]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.48602  -21.634054 -18.458584 ... -22.001738 -21.14948  -19.793589]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.50981  -19.148182 -19.43     ... -23.721395 -22.071241 -21.470795]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.76317   -6.7457943 -9.879933  ... -6.78232   -5.348069  -5.110855 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.096409 -18.63431  -17.399878 ... -18.16093  -16.684828 -14.319489]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.681416 -17.993893 -20.198133 ... -15.282487 -14.016634 -12.389478]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.690638   -7.4905577 -10.212924  ...  -8.244707   -6.5036306
  -6.7828383]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.034649  -15.654954  -14.508083  ... -14.338964  -13.8534355
 -12.237338 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.938472  -6.860632  -9.741523  ... -7.1535926 -5.4982724 -5.5951586]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.657927 -17.257906 -19.148048 ... -12.475009 -13.168717  -8.389419]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.518665 -22.577412 -20.467598 ... -23.445372 -22.346756 -24.658323]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.17471  -18.061632 -16.940687 ... -18.123995 -16.845692 -16.307066]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.859617  -9.625707  -8.960757 ... -11.141868  -8.28905  -10.218385]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.240625 -23.132504 -20.208988 ... -25.672989 -24.909357 -26.261395]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.20588    -8.435887  -12.413948  ...  -9.45084    -7.1699324
  -8.245751 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.915355 -12.358341 -15.128774 ... -13.11902  -11.340467 -12.129455]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.840277   -9.258421  -12.522482  ... -10.020205   -7.5912685
  -8.543289 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.812417 -14.522778 -14.081139 ... -14.917713 -12.950799 -14.192284]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.435129   -8.67216    -9.647025  ... -10.330828   -7.7569923
  -9.518233 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.957779 -19.514006 -16.821531 ... -18.707556 -18.91206  -15.828408]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.83368    -8.497532  -11.84364   ...  -9.321377   -7.143697
  -8.0118475]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.630532 -10.654454 -11.821503 ... -10.531157  -8.639492 -10.506227]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.894005  -7.2249007 -8.823607  ... -8.595609  -6.1680136 -8.315103 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.76602    -7.9847746 -11.115979  ...  -9.604524   -7.4478393
  -7.651474 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.792049   -7.7668085 -10.097742  ...  -8.881496   -6.8017945
  -7.301314 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.658229 -14.494313 -13.557377 ... -18.15441  -16.27328  -16.255936]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.31475    -8.030526  -10.719876  ...  -8.50919    -6.3328104
  -6.8804717]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.402385   -8.259152  -10.557931  ...  -9.479699   -7.1973963
  -7.8200974]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.1471615 -14.127243  -14.529161  ... -14.837744  -13.9991045
 -14.138118 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.927031 -13.53772  -13.282766 ... -14.009534 -13.281382 -13.635984]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.352965 -11.104553 -10.929123 ... -12.333891 -10.883864 -12.065646]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.151054 -19.512167 -21.666864 ... -22.28711  -20.6828   -21.544193]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.713398 -20.52421  -15.856857 ... -23.034986 -21.092875 -20.724033]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.269693  -7.634807  -7.933695  ... -8.8085985 -6.3283577 -8.248302 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.573833 -15.736011 -15.735157 ... -16.803038 -15.508136 -14.633333]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-27.714323 -25.25675  -28.898249 ... -21.19343  -20.105995 -20.312006]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -5.417577   -9.202038   -5.8575726 ... -12.639973  -12.605834
 -14.967677 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.2535305 -4.375564  -8.699234  ... -3.8572161 -4.334868  -4.2796183]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -3.461619   -4.5388103 -10.000662  ...  -4.385562   -4.440436
  -2.393165 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.9052018 -4.3551464 -6.9625173 ... -6.2549133 -4.8229012 -7.8878145]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.373639   -6.520635  -11.708442  ...  -7.909904   -7.3906827
  -5.0726314]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.613095  -10.143144   -0.989107  ... -14.769084  -13.4705715
 -13.748512 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.986118   -9.937758  -14.364299  ... -15.1960335 -14.936547
 -13.84407  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.941258  -5.6406784 -9.199924  ... -6.3898726 -5.0274205 -4.067605 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.419546 -18.9119   -21.046339 ... -17.204288 -16.329521 -12.629333]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.056662  -10.667855  -17.859362  ... -11.707044  -11.273374
  -6.2749696]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.994913  -13.430281  -13.3024435 ... -13.474168  -11.915753
  -8.337516 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.855205 -13.462168 -12.959195 ... -14.524291 -13.495527 -14.272037]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.282044   -7.6361175  -9.354689  ...  -8.89356    -6.750637
  -7.5183034]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.4099827  -7.840365  -13.524623  ...  -8.946259   -7.7924476
 -10.49319  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.105053  -9.62322  -10.233642 ... -10.948424  -9.767942  -9.73763 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.059067 -17.662518 -24.587679 ... -17.835453 -17.142511 -14.956619]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.271914  -13.0749855 -14.510088  ... -13.518401  -12.960864
 -13.769829 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.309662 -18.028893 -22.48233  ... -16.974358 -15.900579 -17.128902]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.533092  -11.561693  -13.790649  ... -11.6189785 -10.658417
  -9.14767  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.922364   -8.172151  -10.444047  ...  -9.125909   -7.6973543
  -7.95164  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.977055  -6.696629  -9.615291  ... -7.4856353 -7.8076797 -6.1137624]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.489213  -8.821013 -13.111481 ... -10.05668   -8.619435 -11.581621]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.760145   -7.711568  -10.585248  ...  -8.97912    -8.21297
  -6.9493656]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.689118  -7.541032  -9.8222885 ... -8.6677    -7.6069903 -6.8127484]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.9457655  -8.2603655 -10.284619  ...  -9.777161   -9.271631
  -7.3511615]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.971377   -8.451122   -9.002714  ...  -9.995571   -9.425957
  -6.1827316]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.03517  -15.911548 -14.374976 ... -17.326237 -16.410141 -16.133965]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.270854   -7.1144676 -10.389417  ...  -8.274083   -7.6418643
  -6.268689 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.968352 -12.308625 -13.15138  ... -13.281025 -12.679302 -12.852763]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.5009284  -7.3431787 -10.639022  ...  -8.907736   -8.045087
  -6.895103 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.3607097  -6.424198  -11.353892  ...  -6.7102003  -5.8263507
  -5.2076087]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -1.7960161  -1.0633813 -10.641346  ...  -1.2387073  -0.8724029
  -1.5235382]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.616131 -12.291136 -13.03811  ... -12.87109  -12.333653 -12.816856]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.3489957  -6.233321  -10.82587   ...  -6.710247   -5.4199853
  -5.4101114]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.89846  -12.578407 -13.18497  ... -13.085143 -12.496886 -12.967097]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.154448 -13.6616   -13.329372 ... -14.464928 -13.833859 -14.188595]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.799276  -7.9379673 -8.734022  ... -9.31057   -8.926746  -7.674614 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.091784 -16.195906 -15.324623 ... -19.324259 -19.265884 -16.217604]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.573427 -17.970003 -17.096277 ... -17.673618 -15.681138 -15.413153]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.146072   -8.4074545 -13.369398  ...  -8.588362   -7.547513
  -8.081429 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.486515   -6.9362645 -10.383108  ...  -8.080279   -6.679013
  -6.9120812]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.8387165 -5.849527  -9.244264  ... -6.6716814 -6.9522243 -4.7347746]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.321441   -7.1918845  -9.249987  ...  -9.226203   -8.666962
  -6.4073987]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.48971  -16.683537 -22.197512 ... -17.939734 -16.137856 -18.728064]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.53149  -16.453197 -12.809212 ... -16.39236  -15.171658 -15.980238]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.305639  -9.213265 -10.984681 ... -10.136237  -7.751581  -8.29055 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.076376  -17.588902   -5.9823318 ... -20.35272   -18.682192
 -18.700827 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.325455 -13.045378 -13.169986 ... -13.841163 -13.213608 -13.842677]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.363998  -16.849491  -21.868227  ... -16.064943  -14.081786
 -14.5446005]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.1843405  -8.7156315 -10.899189  ...  -9.25846    -6.7293634
  -6.2727757]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.171838 -11.481116 -15.699316 ... -12.687246 -11.876958 -10.835234]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.744147  -6.646283  -8.523744  ... -9.44883   -8.781953  -7.2257023]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.29003    -8.909887  -10.788812  ... -10.379317   -9.046182
  -9.6956625]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.602243 -22.977686 -22.026188 ... -25.214558 -24.284142 -26.683636]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.108118  -8.799102  -9.307085 ... -10.032107  -9.47806   -6.25833 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.349274  -13.805832  -13.408309  ... -14.6959715 -14.074657
 -14.264751 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.214536  -6.349583  -9.203555  ... -8.325493  -6.7623763 -8.703026 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.568674 -12.886694 -11.941303 ... -14.291    -13.675074 -13.752476]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.705303 -21.376389 -21.183653 ... -21.357437 -20.370638 -20.474964]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.014429  -7.62219   -9.106488 ...  -9.144787  -7.151865  -7.853701]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.434696  -7.318936  -9.773684  ... -7.841555  -5.5169387 -8.423553 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-29.910402 -27.491997 -25.803219 ... -27.137796 -24.912142 -24.036966]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-28.737598 -28.415234 -22.732553 ... -26.271046 -26.282145 -23.41677 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.702848   -9.747161   -9.6434145 ... -15.809273  -13.161985
 -17.509375 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.509376  -7.972473  -8.453477 ...  -9.403481  -7.279944  -7.795107]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.296867  -5.7710423 -8.200773  ... -6.992304  -4.7633314 -7.769311 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.879766 -23.417051 -23.641886 ... -24.98098  -23.815363 -23.81261 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.197708 -18.087934 -20.024895 ... -17.172432 -17.654436 -17.57157 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.167095   -8.916707  -11.721359  ... -10.4879     -8.1796465
  -8.913347 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.216282  -16.448122  -21.559599  ... -17.761322  -16.961487
 -14.7681675]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.410208 -18.961401 -21.707766 ... -17.271074 -17.57994  -15.40611 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.265793 -16.543158 -15.6032   ... -20.26036  -20.971436 -18.093344]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.963762 -10.298042 -13.028585 ... -11.422169 -10.357863 -10.451747]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.23328  -22.714867 -16.630713 ... -24.2535   -22.617155 -23.095047]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.3734   -7.774869 -9.721654 ... -9.926264 -9.029804 -7.93542 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.5826716 -4.687425  -7.44913   ... -5.9724298 -5.654953  -5.0833626]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.746536 -13.356836  -8.378916 ... -15.770638 -14.640729 -15.347653]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.555016 -23.069382 -14.312174 ... -24.557734 -22.84876  -23.378798]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.602076   -8.304523  -11.410194  ... -12.13712   -12.087158
 -10.0940075]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.146129  -13.928312  -10.2079935 ... -15.317974  -14.414902
 -14.872121 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.301506  -10.77729   -11.895373  ... -14.486636  -13.683608
 -14.3677635]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.706631   -8.049463  -11.312322  ...  -9.183702   -8.239477
  -7.5082808]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.4021435 -12.951668  -13.259145  ... -15.708992  -15.781301
 -15.792281 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.3676996e+01 -1.0617282e+01  7.9244580e-03 ... -1.7323227e+01
 -1.5022824e+01 -1.4587734e+01]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.5765276 -6.4095483 -5.3357453 ... -8.315766  -8.15122   -6.1605926]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.573671 -11.909172  -9.767902 ... -13.656768 -12.399786  -8.648593]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.401356  -13.673877   -7.5425043 ... -15.205738  -15.266259
 -10.835972 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.927672   -8.331357  -10.003435  ... -10.5221815  -8.560822
  -7.484833 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.410645  -9.868731 -17.365871 ... -13.229989 -13.312679  -9.667755]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.04307    -6.1805763 -11.149137  ...  -7.0224385  -6.6671953
  -4.6228423]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.372059 -15.976681 -12.606409 ... -16.637877 -15.37159  -15.3614  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.989266 -12.915157  -7.27243  ... -14.462253 -13.8245   -13.1247  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-28.096294 -26.936306 -20.344109 ... -29.287489 -26.790258 -27.194891]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.97448  -13.482153 -13.296789 ... -14.190437 -13.523646 -13.9802  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.667429 -13.396471 -10.135273 ... -15.014292 -17.021152 -16.04504 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.432968 -16.409101 -21.521217 ... -16.756517 -15.442838 -15.749058]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.819741 -13.198982 -12.721752 ... -14.286592 -13.732    -13.874422]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -3.9528177  -4.8057055 -10.2115135 ...  -4.475551   -4.6470966
  -2.6637826]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.291656 -14.323986 -15.672445 ... -16.469437 -15.342019 -14.361923]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-25.350864 -21.901814 -19.713308 ... -23.82369  -22.335499 -21.235254]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.908562   -7.377988  -10.525621  ...  -8.520162   -6.6816173
  -7.3583884]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.19817    -7.413586  -10.413043  ...  -8.392022   -7.4049935
  -6.751872 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.887217  -17.999517   -2.2090056 ... -23.286272  -21.599335
 -21.032722 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-24.005367 -18.587347 -27.257816 ... -20.030718 -19.714895 -14.532737]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.242449 -10.693028 -10.835923 ... -11.996894 -11.174569 -10.638696]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.99795    -7.272332  -12.623096  ...  -8.56032    -6.7707477
  -7.5509205]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.77947   -8.966364 -11.470159 ...  -9.851691  -7.918529  -8.604934]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.624541   -6.7052503  -7.6589093 ...  -9.084124   -6.0981536
  -6.376327 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.636326   -7.545844   -8.926879  ...  -8.635156   -6.7104425
  -7.124735 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.675929   -6.1379657 -13.905599  ...  -7.438791   -7.2795725
  -6.0310535]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.478394 -19.559462 -22.708467 ... -19.722837 -19.424225 -18.895996]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.08012    -6.1844177  -7.5797067 ...  -8.899723   -7.1156416
  -6.547667 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.300047  -13.680742  -13.561143  ... -14.505782  -13.825518
 -14.1775465]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.032679 -12.593768 -13.21192  ... -12.004582 -11.196518 -10.135516]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -3.1374288  -2.4809659 -10.801923  ...  -2.3212693  -1.9390823
  -1.895071 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.4911118 -5.484219  -6.496003  ... -6.5195694 -5.861589  -6.765847 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.15365  -20.636616 -12.32924  ... -22.334051 -23.57309  -20.636663]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.117307 -11.91623  -11.574629 ... -12.806801 -11.054223 -10.575443]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.494738 -11.047365 -12.423479 ... -10.54725   -9.383168  -9.230383]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.9842825 -13.311737  -13.147745  ... -14.214004  -13.563066
 -13.890681 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.023401 -15.325412 -18.661673 ... -17.62244  -16.253912 -16.763979]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.169724  -11.0859585 -11.883982  ... -13.226456  -11.691072
 -13.178021 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.647327  -9.641945  -8.341427 ... -12.078246  -9.178223  -8.988528]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.482627   -9.136892  -12.739167  ...  -9.270623   -7.3747025
  -7.6549554]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.184372 -15.062696 -14.351262 ... -15.910996 -14.461284 -14.65746 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.732542 -14.934245  -7.672718 ... -16.290678 -14.467327 -16.811222]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.724458 -13.864366 -13.668483 ... -14.000493 -13.392885 -13.055648]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.13109  -13.730344 -13.586235 ... -14.446729 -13.777727 -14.274121]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.2651505  -6.508862  -10.528107  ...  -7.383544   -6.1058497
  -5.963063 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.717622 -15.220079 -17.36842  ... -12.916567 -11.999879 -11.729018]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.323682  -11.153628  -17.193325  ... -13.042131  -11.247012
 -10.4782505]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.403858 -15.003121 -12.515173 ... -15.279504 -14.223083 -14.433712]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.19404  -14.713158 -12.18369  ... -14.966512 -13.925804 -14.089726]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.646222  -14.016882  -15.5502825 ... -14.458359  -14.031201
 -13.526064 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.0618796 -6.2246747 -9.012383  ... -6.443225  -5.9368753 -5.068827 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.128922  -11.624877  -13.114851  ... -12.085204  -11.393467
 -11.7076235]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.731217  -9.267344 -11.589116 ...  -9.959399  -8.479018  -9.017698]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.662209 -19.924189 -12.673326 ... -22.46824  -23.497395 -19.29439 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.572647  -6.8714294  2.1740665 ... -9.537969  -8.383158  -8.10976  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.554407 -22.698338  -7.403337 ... -27.124344 -25.238035 -24.48776 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-32.24917  -30.190952 -23.66035  ... -35.5346   -34.352394 -32.164   ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.854072 -13.640748 -13.306712 ... -12.990237 -12.679286 -10.678725]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.292437   -7.9433722 -11.080908  ...  -8.236965   -6.600866
  -6.26053  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.415491 -16.745228 -13.759625 ... -17.919466 -17.483309 -17.232143]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.936231 -20.350414 -15.698887 ... -22.163546 -20.813152 -24.722816]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.591095 -10.559536 -17.082525 ... -12.026706  -9.572512  -8.993792]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.029661 -20.014046 -13.834395 ... -23.902067 -23.015034 -21.412918]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.338389 -10.623382  -9.347792 ... -13.155788 -10.284158 -10.113691]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.164476 -12.212487 -13.251059 ... -12.919946 -12.211954 -12.384116]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.311428 -18.744648 -17.705738 ... -19.191317 -18.915915 -17.800442]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.993054 -16.24579  -12.861322 ... -18.704615 -17.98133  -17.561472]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.330965 -14.087553 -14.128092 ... -16.813728 -14.696654 -14.119934]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.741022 -18.819149 -13.746691 ... -20.199574 -19.896173 -20.648176]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.93911  -11.608551 -10.78097  ... -12.003328 -11.428534 -11.116673]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.852614  -5.7591724 -8.613098  ... -7.261063  -6.3186293 -5.323341 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.619228 -15.989118 -21.93566  ... -18.788103 -16.570644 -16.16548 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-28.336319 -25.532475 -24.219913 ... -26.650429 -25.186802 -24.039076]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.459018  -11.594309  -11.791948  ... -12.359188  -11.4910965

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.391982  -8.963516 -18.430834 ...  -9.745694  -8.963761  -5.854913]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.116453 -20.287518 -24.289022 ... -20.122303 -20.65381  -18.048965]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.729701 -10.183068 -16.23522  ...  -9.785022  -9.7312   -10.138961]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.331633 -18.861378 -19.462273 ... -20.065765 -19.522232 -18.280766]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.439131  -8.077228  -9.848678  ... -8.900163  -8.338853  -7.9101105]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.006576 -10.922204 -18.08603  ... -12.461894 -11.434029 -11.271592]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.401076 -16.370285  -5.899189 ... -18.730257 -17.894075 -17.892576]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.956131  -6.572112   2.0871437 ... -9.495625  -8.32589   -8.379563 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.872451 -15.38177  -19.45515  ... -15.487045 -14.222979 -14.378446]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.7331357 -7.3228736 -8.7739725 ... -7.675423  -6.7321916 -6.533851 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.7395115 -12.475188  -15.451933  ... -13.775704  -12.569649
 -14.274789 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.723259 -15.49283  -13.736718 ... -19.059057 -17.432295 -18.744717]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.663588 -18.673914 -16.64211  ... -17.333956 -17.143877 -17.495926]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.058505  -6.42133   -5.241682  ... -6.5104737 -5.777529  -5.0033336]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.872337 -22.002302 -18.600624 ... -22.070606 -21.866623 -20.625092]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.736836  -8.40722   -8.833279 ...  -9.702537  -9.171157  -6.30002 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.528539 -11.821261 -12.888313 ... -12.093343 -11.675176 -11.802737]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-24.430586 -21.341768 -16.883392 ... -25.360762 -24.539047 -22.030361]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.110876 -19.789106 -16.397577 ... -23.379776 -22.662893 -20.803347]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.436196   -8.730591  -13.666565  ...  -9.038515   -8.490924
  -6.3974705]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.227135 -15.239499 -17.082325 ... -13.086662 -16.012754 -13.89666 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.9539824 -6.7517805 -8.604148  ... -6.956585  -6.282573  -5.419799 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.855296  -6.510505  -8.8292    ... -6.497681  -6.8071733 -5.137188 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.37415   -11.7807255 -14.571607  ... -12.377969  -11.503683
 -11.134588 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.692515 -10.134841 -15.980132 ... -11.627578  -9.221198  -9.111019]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.291536   -7.3289084 -10.121413  ...  -8.756669   -7.307139
  -7.188007 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.52852  -11.970997 -12.955664 ... -12.127201 -11.712649 -11.949591]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.190781  -8.016714 -11.228663 ...  -9.941647  -8.393776  -8.499788]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.988311 -16.468348 -16.268387 ... -15.950018 -16.894148 -17.52001 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.8620074 -5.44227   -7.2703924 ... -6.0379615 -6.4533906 -5.4314785]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.015814 -23.909126  -9.24997  ... -26.902351 -25.565464 -23.49592 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.4752274  -6.9784546 -10.0201645 ...  -8.265637   -7.421509
  -6.6027946]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-29.106525 -27.177065 -24.219572 ... -29.72367  -28.797733 -26.693361]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.403362 -17.316967 -15.757665 ... -18.830313 -17.841736 -18.559753]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.022028   -7.7600927 -11.089625  ...  -8.879243   -7.8587656
  -7.8042097]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.033237 -20.90827  -18.15548  ... -22.835606 -22.048555 -20.462223]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.1174755 -11.600363  -14.052281  ... -13.66064   -11.365094
 -12.678678 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.208448  -8.940904 -11.488379 ...  -8.83941   -6.657344  -4.541788]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.407036 -21.334877 -16.700611 ... -23.46164  -22.64658  -20.353582]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.0781555 -8.434839  -9.014049  ... -8.773061  -8.2641115 -7.9916472]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.276027 -7.456367 -9.549252 ... -8.044648 -6.841265 -6.269443]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.056992  -13.0019865 -13.082173  ... -13.913156  -13.548222
 -13.740829 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.627641  -9.92645  -11.17525  ... -13.965259 -13.814365 -11.666199]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.189656  -8.381032  -9.083532 ...  -8.971294  -6.664228  -7.176891]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.100125 -10.815828  -8.446908 ... -12.372089 -11.604122 -11.057395]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.42177    -9.431796  -10.916548  ... -10.014828   -8.355351
  -8.3593235]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.458055 -14.094235 -19.788649 ... -12.508919 -13.556449  -8.843289]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.507083   -9.609664  -12.412007  ... -10.516639   -8.7119465

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.993908 -13.799475 -14.894271 ... -12.716718 -12.134762 -10.372063]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.37524   -9.449196 -10.592766 ... -10.094669  -8.549489  -8.458225]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.8370943 -4.869893   4.4092116 ... -7.097723  -5.8849263 -6.4023213]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.473757 -14.430679  -7.897357 ... -16.500416 -15.536092 -15.75302 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.049144  -5.850104   3.1361654 ... -7.9441366 -6.729376  -6.859677 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.872354  -6.2695765  2.2925205 ... -8.631094  -7.216871  -7.4403677]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.530008  -14.268015  -15.202342  ... -13.045199  -12.295893
 -12.1398735]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.148353  -6.1866064 -9.206545  ... -6.03205   -6.0417223 -4.5153556]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.284497 -14.74519  -13.702644 ... -15.805227 -14.531166 -12.764202]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.171803   -8.80467   -10.513459  ...  -9.453599   -8.351613
  -7.9862175]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.2671485 -6.0895443  2.765818  ... -8.118114  -6.862755  -6.700361 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.16057  -13.212313  -7.684155 ... -15.617618 -14.493571 -13.176861]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.423063  -7.1582146 -8.540097  ... -8.075427  -7.8846545 -7.768901 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.6350594 -6.1310205 -9.64615   ... -7.615315  -6.844585  -7.6926665]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.279269   -8.23937   -10.943468  ...  -9.722933   -8.533849
  -7.4519253]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.882446 -12.015164 -11.836296 ... -11.89566  -10.393743 -11.696634]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.481203  -8.789991  -8.234266  ... -9.150385  -7.8726935 -7.930073 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.423051  -9.658508  -8.383974 ... -12.100934  -9.226006  -8.982004]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.862589 -20.977364  -5.302709 ... -23.324463 -23.815945 -22.630865]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.152705 -12.890071 -13.118052 ... -13.283176 -12.81411  -13.230368]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.033849 -13.456396 -13.207655 ... -14.400693 -13.695904 -14.10573 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.890081  -22.132662   -5.9588423 ... -26.184488  -24.038452
 -24.162672 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.233545 -13.747165 -13.145028 ... -14.088254 -13.61855  -13.747639]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.85115    -6.4297414 -11.403876  ...  -9.636152   -9.854286
  -7.1554246]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.447671  -11.869772  -20.162321  ... -13.5594635 -12.643078
 -11.112947 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.578138 -20.38366  -19.726202 ... -19.852423 -18.378922 -14.893982]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.684432  -6.6964192  2.6317837 ... -8.568675  -7.527455  -8.426501 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.548553  -6.275696   3.4677176 ... -8.926052  -7.61242   -8.007847 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.370735 -17.59097  -23.420113 ... -22.35192  -21.512014 -19.505009]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.558865  -7.3634853  2.1894436 ... -9.825823  -8.225274  -8.704741 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.355097 -16.66624  -16.021368 ... -18.270044 -18.414438 -17.53568 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.4199743 -5.42168   -6.5718713 ... -7.4088907 -7.342212  -6.6366796]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.442545 -13.334701 -18.57105  ... -12.400534 -11.894344  -8.244365]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.584057 -19.312449 -14.957593 ... -20.695446 -19.743036 -18.780237]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-24.392832  -23.01455   -15.6107025 ... -25.583242  -23.699797
 -23.09362  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.786319 -13.272954 -13.137828 ... -14.054561 -13.497984 -13.754564]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.215923 -23.275667 -11.027814 ... -26.606129 -24.854582 -24.793575]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.967992 -17.02238  -13.993642 ... -17.12081  -16.12234  -18.19337 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.104538 -13.091142 -15.815352 ... -15.64476  -14.612483 -16.351793]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.757041 -10.602183 -17.33466  ... -12.147315  -9.618298  -9.077337]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.7285666 -7.7584624 -9.403367  ... -7.401226  -7.188882  -5.4462385]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.260096   -8.197759  -11.093968  ...  -8.630278   -7.479709
  -8.1232815]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.913725 -19.167812 -17.813595 ... -19.313473 -20.726196 -18.240452]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.237814  -5.3764844 -7.011126  ... -6.0709724 -4.0183086 -6.3531246]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.333095  -9.260206  -8.206247 ... -11.258711  -8.809971  -8.386367]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.616432 -19.32121  -17.936697 ... -22.901264 -20.213465 -20.9413  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.999098 -16.359484 -17.370054 ... -20.271784 -19.638521 -18.877737]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.334322  -8.539004 -14.038041 ...  -9.535663  -8.977063 -10.177794]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.782862   -5.745803  -13.4547205 ...  -9.761694   -8.020674
 -10.709776 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.264877 -18.644312 -12.911246 ... -20.272049 -18.418825 -19.398382]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.555889  -8.450805  -8.387822 ... -11.525746  -8.202194  -9.859204]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.033822   -6.2174034  -7.849732  ...  -9.868994   -6.9925056
  -9.430821 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.205301 -18.550592 -14.050339 ... -19.48839  -18.148754 -19.286352]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.454113   -9.123696   -7.7445045 ... -10.088093   -7.8662443
  -9.201346 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.405682  -9.438007  -9.396367 ...  -9.946303  -8.048076  -9.213405]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.466581  -9.229721  -8.488693 ... -10.479114  -8.189578  -9.237447]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.192031  -9.404667  -8.890061 ... -10.725658  -8.301825  -9.795434]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.517634 -10.443811  -9.247433 ... -12.079425  -9.358012 -11.091756]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.766522 -8.17286  -7.490293 ... -9.186919 -6.852353 -8.530994]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.779566  -4.88229   -5.461589  ... -8.517185  -8.034883  -6.2266464]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.583601 -11.776727 -15.498699 ... -16.055866 -14.060518 -15.812797]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.536129 -13.816055 -13.579497 ... -14.603432 -13.900721 -14.144683]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.1195545 -11.776254  -13.172422  ... -12.369242  -11.951187
 -11.675116 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-25.148035 -21.41331  -18.611486 ... -23.501999 -21.627764 -20.367785]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.410557   -7.3955917  -8.119737  ... -10.363365   -7.198523
  -9.653388 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.167364 -20.039202  -7.900456 ... -23.679296 -22.61529  -23.343737]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.304604   -8.183244   -7.1142645 ... -11.090678   -7.9032555
  -7.835529 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.655409  -5.2995863 -7.192202  ... -8.149386  -5.6056924 -7.913284 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-26.467804 -22.265785 -22.51077  ... -22.400824 -21.12066  -19.260738]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.094385 -13.931942 -12.249172 ... -16.422297 -14.911688 -15.263745]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-29.235605 -25.277504 -24.63525  ... -24.820868 -24.024122 -21.428215]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.318054 -18.430515 -16.0701   ... -18.357182 -17.797153 -17.726835]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.345118 -14.044144 -10.994561 ... -16.29698  -17.94358  -14.955775]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.474216  -6.394367  -7.962561  ... -8.889104  -8.673668  -7.2545595]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.537925 -12.413262 -12.267204 ... -13.945671 -12.961565 -12.941544]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.865652 -14.118339 -12.292529 ... -15.184835 -13.939687 -15.019417]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.6596017 -7.369361  -9.043421  ... -7.81521   -6.9435015 -6.5211525]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.867903  -9.335767 -11.947435 ... -10.486796  -9.452067  -8.770412]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.007137   -7.361412   -7.8759747 ...  -9.164555   -8.205356
  -6.342087 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.452591  -11.1704855 -10.533828  ... -14.132089  -14.328724
 -11.187844 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.930511  -7.026786   1.1538826 ... -9.9813175 -8.478439  -8.352513 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.3797   -22.27737  -14.710447 ... -23.259066 -21.671633 -21.86154 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-21.199728 -21.563192 -19.371834 ... -22.644987 -21.672922 -21.16195 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.445036 -17.211048 -19.59818  ... -14.023374 -14.794629 -12.801646]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.27055  -17.564705 -12.008827 ... -19.638128 -18.12459  -17.042513]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.621469  -8.409126  -8.068125 ...  -9.46198   -8.964537  -7.892625]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.427217  -12.024067  -11.379746  ... -13.540675  -12.573406
 -11.3417015]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.896025 -16.50279  -16.134008 ... -17.575584 -17.360622 -18.263964]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.581478 -6.129613 -7.688015 ... -8.67206  -8.231035 -6.751576]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.033997 -15.791758 -26.692638 ... -17.25168  -17.39847  -15.437232]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.223967 -19.365438 -26.047058 ... -16.694942 -17.089437 -14.509071]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.150991 -13.438086 -20.709154 ... -12.827957 -12.615318 -10.612162]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.605478 -16.314548 -23.283892 ... -15.242865 -15.802871 -13.671236]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.583578 -14.578029 -22.81214  ... -17.334608 -16.940943 -17.722069]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.517195 -16.124737 -22.450487 ... -18.661394 -18.12023  -19.077303]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.614883  -8.361591  -9.609489 ...  -9.973503  -8.120666  -8.856742]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.428082 -17.286028 -23.285484 ... -18.2677   -18.038633 -17.05011 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-20.014591 -16.659193 -21.233759 ... -19.238918 -19.238565 -16.64777 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-23.164286 -19.761786 -21.206854 ... -20.20693  -20.170897 -15.623241]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-22.452463 -20.478464 -18.130966 ... -22.072487 -21.135077 -19.39768 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-26.069828 -24.18055  -21.740107 ... -25.939486 -24.585735 -22.537321]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.8731165  -8.3775625  -9.372747  ...  -8.277297   -6.4855285
  -6.4457746]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.291756 -11.600978 -14.468171 ... -12.050084  -9.517993 -11.970148]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.261744  -12.683388  -12.705997  ... -13.610099  -12.935065
 -13.2908945]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.346622 -19.260906 -16.408825 ... -20.233294 -19.47622  -20.73148 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.381258   -8.0327215  -9.043615  ...  -8.521394   -7.1810293
  -5.236632 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.593066 -13.752982 -10.615163 ... -16.144566 -14.326055 -18.228489]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_1372178/542231449.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.267086  -5.212122  -8.660872  ... -6.0313425 -4.4175644 -6.2709866]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

PairwiseArrays with keys: connectivities, distances

{'cellxgene_census/dkd_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.6050132734327139, 'macro': 0.45858384601691754, 'micro': 0.6050132734327139, 'weighted': 0.5752358078815335}}, 'cellxgene_census/dkd_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5608184918529746, 'macro': 0.49302410982269285, 'micro': 0.5608184918529746, 'weighted': 0.5370188034467204}}, 'cellxgene_census/dkd_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5941644562334217, 'macro': 0.5355514243377841, 'micro': 0.5941644562334217, 'weighted': 0.5827613925424003}}, 'cellxgene_census/dkd_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5985221674876847, 'macro': 0.5, 'micro': 0.5985221674876847, 'weighted': 0.5985221674876847}}, 'cellxgene_census/gtex_v9_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5690731903254497, 'macro': 0.3561412506114705, 'micro': 0.5690731903254497, 'weighted': 0.5111263506144524}}, 'cellxgene_census/gtex_v9_cls': {'cell_type_ontology_term_id': {'accuracy': 0.47340980187695514, 'macro': 0.4771516389245344, 'micro': 0.47340980187695514, 'weighted': 0.4105919407683359}}, 'cellxgene_census/gtex_v9_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.49930483142161974, 'macro': 0.45026649672378827, 'micro': 0.49930483142161974, 'weighted': 0.46767738060420655}}, 'cellxgene_census/gtex_v9_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.49930483142161974, 'macro': 0.45026649672378827, 'micro': 0.49930483142161974, 'weighted': 0.46767738060420655}}, 'cellxgene_census/hypomap_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9331843865688121, 'macro': 0.5582565920511067, 'micro': 0.9331843865688121, 'weighted': 0.9095025274318423}}, 'cellxgene_census/hypomap_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9817518248175182, 'macro': 0.8017862483599127, 'micro': 0.9817518248175182, 'weighted': 0.9743770548339135}}, 'cellxgene_census/hypomap_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9908759124087592, 'macro': 0.8529747502946833, 'micro': 0.9908759124087592, 'weighted': 0.986699566363855}}, 'cellxgene_census/hypomap_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9963503649635036, 'macro': 0.8811979101634128, 'micro': 0.9963503649635036, 'weighted': 0.9945824700566079}}, 'cellxgene_census/mouse_pancreas_atlas_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9168991697845367, 'macro': 0.736673219519387, 'micro': 0.9168991697845367, 'weighted': 0.8911321328642097}}, 'cellxgene_census/mouse_pancreas_atlas_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9222539985171062, 'macro': 0.7317299769023702, 'micro': 0.9222539985171062, 'weighted': 0.8935278968505191}}, 'cellxgene_census/mouse_pancreas_atlas_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9653638385764219, 'macro': 0.7529330761341159, 'micro': 0.9653638385764219, 'weighted': 0.9564964495219883}}, 'cellxgene_census/mouse_pancreas_atlas_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9721427814850122, 'macro': 0.7654463915196114, 'micro': 0.9721427814850122, 'weighted': 0.9663853668888627}}}

In [14]:
metrics

{'cellxgene_census/dkd_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.6050132734327139,
   'macro': 0.45858384601691754,
   'micro': 0.6050132734327139,
   'weighted': 0.5752358078815335}},
 'cellxgene_census/dkd_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5608184918529746,
   'macro': 0.49302410982269285,
   'micro': 0.5608184918529746,
   'weighted': 0.5370188034467204}},
 'cellxgene_census/dkd_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5941644562334217,
   'macro': 0.5355514243377841,
   'micro': 0.5941644562334217,
   'weighted': 0.5827613925424003}},
 'cellxgene_census/dkd_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5985221674876847,
   'macro': 0.5,
   'micro': 0.5985221674876847,
   'weighted': 0.5985221674876847}},
 'cellxgene_census/gtex_v9_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5690731903254497,
   'macro': 0.3561412506114705,
   'micro': 0.5690731903254497,
   'weighted': 0.5111263506144524}},
 'cellxgene_census/gtex_v9_cls': {'cell_type_ontology_term_id': {'accuracy': 0.47340980187695514,
   'macro': 0.4771516389245344,
   'micro': 0.47340980187695514,
   'weighted': 0.4105919407683359}},
 'cellxgene_census/gtex_v9_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.49930483142161974,
   'macro': 0.45026649672378827,
   'micro': 0.49930483142161974,
   'weighted': 0.46767738060420655}},
 'cellxgene_census/gtex_v9_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.49930483142161974,
   'macro': 0.45026649672378827,
   'micro': 0.49930483142161974,
   'weighted': 0.46767738060420655}},
 'cellxgene_census/hypomap_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9331843865688121,
   'macro': 0.5582565920511067,
   'micro': 0.9331843865688121,
   'weighted': 0.9095025274318423}},
 'cellxgene_census/hypomap_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9817518248175182,
   'macro': 0.8017862483599127,
   'micro': 0.9817518248175182,
   'weighted': 0.9743770548339135}},
 'cellxgene_census/hypomap_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9908759124087592,
   'macro': 0.8529747502946833,
   'micro': 0.9908759124087592,
   'weighted': 0.986699566363855}},
 'cellxgene_census/hypomap_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9963503649635036,
   'macro': 0.8811979101634128,
   'micro': 0.9963503649635036,
   'weighted': 0.9945824700566079}},
 'cellxgene_census/mouse_pancreas_atlas_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9168991697845367,
   'macro': 0.736673219519387,
   'micro': 0.9168991697845367,
   'weighted': 0.8911321328642097}},
 'cellxgene_census/mouse_pancreas_atlas_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9222539985171062,
   'macro': 0.7317299769023702,
   'micro': 0.9222539985171062,
   'weighted': 0.8935278968505191}},
 'cellxgene_census/mouse_pancreas_atlas_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9653638385764219,
   'macro': 0.7529330761341159,
   'micro': 0.9653638385764219,
   'weighted': 0.9564964495219883}},
 'cellxgene_census/mouse_pancreas_atlas_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9721427814850122,
   'macro': 0.7654463915196114,
   'micro': 0.9721427814850122,
   'weighted': 0.9663853668888627}}}

# same with scPRINT-V1

In [15]:
metrics = {
    "mouse_pancreas_atlas_ref_cls": {
        "accuracy": 0.91554001759347,
        "macro": 0.7358365399587412,
        "micro": 0.91554001759347,
        "weighted": 0.8892443110748087,
    },
    "mouse_pancreas_atlas_cls": {
        "accuracy": 0.9174917491749175,
        "macro": 0.6682410013202696,
        "micro": 0.9174917491749175,
        "weighted": 0.8986229074231167,
    },
    "mouse_pancreas_atlas_smooth_cls": {
        "accuracy": 0.9504950495049505,
        "macro": 0.7151672322851542,
        "micro": 0.9504950495049505,
        "weighted": 0.9452647264778836,
    },
    "mouse_pancreas_atlas_clust_cls": {
        "accuracy": 0.8943894389438944,
        "macro": 0.5808108982132751,
        "micro": 0.8943894389438944,
        "weighted": 0.8906195009508227,
    },
    "hypomap_ref_cls": {
        "accuracy": 0.9337637202052348,
        "macro": 0.5608821020187095,
        "micro": 0.9337637202052348,
        "weighted": 0.910030386475484,
    },
    "hypomap_cls": {
        "accuracy": 0.9556962025316456,
        "macro": 0.6988727858293076,
        "micro": 0.9556962025316456,
        "weighted": 0.9484498257200514,
    },
    "hypomap_smooth_cls": {
        "accuracy": 0.9810126582278481,
        "macro": 0.8412698412698413,
        "micro": 0.9810126582278481,
        "weighted": 0.9755877034358047,
    },
    "hypomap_clust_cls": {
        "accuracy": 0.9936708860759493,
        "macro": 0.8840579710144927,
        "micro": 0.9936708860759493,
        "weighted": 0.9906439185470556,
    },
    "gtex_v9_ref_cls": {
        "accuracy": 0.5696326616489581,
        "macro": 0.3572722554532954,
        "micro": 0.5696326616489581,
        "weighted": 0.5124042722647043,
    },
    "gtex_v9_cls": {
        "accuracy": 0.19325153374233128,
        "macro": 0.3269064269064269,
        "micro": 0.19325153374233128,
        "weighted": 0.1457639497516798,
    },
    "gtex_v9_smooth_cls": {
        "accuracy": 0.2331288343558282,
        "macro": 0.3494002998500749,
        "micro": 0.2331288343558282,
        "weighted": 0.19835703313987174,
    },
    "gtex_v9_clust_cls": {
        "accuracy": 0.2331288343558282,
        "macro": 0.3494002998500749,
        "micro": 0.2331288343558282,
        "weighted": 0.19835703313987174,
    },
    "dkd_ref_cls": {
        "accuracy": 0.6029201551970594,
        "macro": 0.45667225888053287,
        "micro": 0.6029201551970594,
        "weighted": 0.5725978164390636,
    },
    "dkd_cls": {
        "accuracy": 0.6589708247185849,
        "macro": 0.34036269065023983,
        "micro": 0.6589708247185849,
        "weighted": 0.6329558903937222,
    },
    "dkd_smooth_cls": {
        "accuracy": 0.6890650126349644,
        "macro": 0.3721906019756931,
        "micro": 0.6890650126349644,
        "weighted": 0.672958398433104,
    },
    "dkd_clust_cls": {
        "accuracy": 0.7259361359981622,
        "macro": 0.5,
        "micro": 0.7259361359981622,
        "weighted": 0.7259361359981622,
    },
}

In [16]:
for k, v in metrics.items():
    print(f"{k}: {v['accuracy']}")

mouse_pancreas_atlas_ref_cls: 0.91554001759347
mouse_pancreas_atlas_cls: 0.9174917491749175
mouse_pancreas_atlas_smooth_cls: 0.9504950495049505
mouse_pancreas_atlas_clust_cls: 0.8943894389438944
hypomap_ref_cls: 0.9337637202052348
hypomap_cls: 0.9556962025316456
hypomap_smooth_cls: 0.9810126582278481
hypomap_clust_cls: 0.9936708860759493
gtex_v9_ref_cls: 0.5696326616489581
gtex_v9_cls: 0.19325153374233128
gtex_v9_smooth_cls: 0.2331288343558282
gtex_v9_clust_cls: 0.2331288343558282
dkd_ref_cls: 0.6029201551970594
dkd_cls: 0.6589708247185849
dkd_smooth_cls: 0.6890650126349644
dkd_clust_cls: 0.7259361359981622

In [17]:
for k, v in res_label.items():
    if k is None:
        continue
    print(f"{k.split('/')[1]}: ")
    for l, w in v.items():
        if w is None:
            continue
        print(f"    {l}: {w['accuracy']}")
    m = 0
    for l, w in metrics.items():
        if l.startswith(k.split("/")[1]):
            if w["accuracy"] > m:
                m = w["accuracy"]
    print(f"    scPRINT-2 (zero-shot): {m:.3f}")

dkd:
    knn: 0.949
    logistic_regression: 0.9572
    majority_vote: 0.2954
    mlp: 0.954
    naive_bayes: 0.9269
    random_labels: 0.1808
    scanvi: 0.957
    scanvi_scarches: 0.957
    scgpt_zeroshot: 0.8486
    scimilarity: 0.8869
    scimilarity_knn: 0.9553
    seurat_transferdata: 0.9541
    singler: 0.9147
    true_labels: 1
    uce: 0.1813
    xgboost: 0.9644
    geneformer: NA
    scgpt_finetuned: NA
    scprint: NA
    scPRINT-2 (zero-shot): 0.726
gtex_v9:
    knn: 0.8523
    logistic_regression: 0.8829
    majority_vote: 0.0799
    mlp: 0.7784
    naive_bayes: 0.7599
    random_labels: 0.0324
    scanvi: 0.8899
    scanvi_scarches: 0.8797
    scgpt_zeroshot: 0.6234
    scimilarity: 0.6665
    scimilarity_knn: 0.8253
    seurat_transferdata: 0.841
    singler: 0.7903
    true_labels: 1
    uce: 0.0054
    xgboost: 0.8328
    geneformer: NA
    scgpt_finetuned: NA
    scprint: NA
    scPRINT-2 (zero-shot): 0.570
hypomap:
    knn: 0.9954
    logistic_regression: 0.9964
    majority_vote: 0.4516
    mlp: 0.9973
    naive_bayes: 0.9945
    random_labels: 0.3157
    scanvi: 0.9973
    scanvi_scarches: 0.9964
    scgpt_zeroshot: NA
    scimilarity: NA
    scimilarity_knn: NA
    seurat_transferdata: 0.9964
    singler: 0.9927
    true_labels: 1
    uce: 0.3841
    xgboost: 0.9973
    geneformer: NA
    scgpt_finetuned: NA
    scprint: NA
    scPRINT-2 (zero-shot): 0.994
immune_cell_atlas:
    knn: 0.8144
    logistic_regression: 0.885
    majority_vote: 0.0058
    mlp: 0.8676
    naive_bayes: 0.6389
    random_labels: 0.0481
    scanvi: 0.8926
    scanvi_scarches: 0.9035
    scgpt_zeroshot: 0.6787
    scimilarity: 0.8354
    scimilarity_knn: 0.8752
    seurat_transferdata: 0.8269
    singler: NA
    true_labels: 1
    uce: 0.0366
    xgboost: 0.8192
    geneformer: NA
    scgpt_finetuned: NA
    scprint: NA
    scPRINT-2 (zero-shot): 0.000
mouse_pancreas_atlas:
    knn: 0.9756
    logistic_regression: 0.978
    majority_vote: 0.3239
    mlp: 0.9703
    naive_bayes: 0.9502
    random_labels: 0.172
    scanvi: 0.9768
    scanvi_scarches: 0.9781
    scgpt_zeroshot: NA
    scimilarity: NA
    scimilarity_knn: NA
    seurat_transferdata: 0.9659
    singler: NA
    true_labels: 1
    uce: 0.1666
    xgboost: 0.9752
    geneformer: NA
    scgpt_finetuned: NA
    scprint: NA
    scPRINT-2 (zero-shot): 0.950
tabula_sapiens:
    knn: 0.1725
    logistic_regression: 0.1831
    majority_vote: 0.0211
    mlp: 0.2887
    naive_bayes: 0.1585
    random_labels: 0.0176
    scanvi: 0.1725
    scanvi_scarches: 0.2711
    scgpt_zeroshot: 0.162
    scimilarity: 0.2007
    scimilarity_knn: 0.1866
    seurat_transferdata: 0.3768
    singler: 0.1725
    true_labels: 1
    uce: 0.0106
    xgboost: 0.243
    geneformer: NA
    scgpt_finetuned: NA
    scprint: NA
    scPRINT-2 (zero-shot): 0.000

In [18]:
import pandas as pd

In [19]:
emb = pd.DataFrame(
    data={
        "Isolated labels": [
            0.621361,
            0.387139,
            0.520031,
            0.544676,
        ],
        "KMeans NMI": [
            0.655657,
            0.570249,
            0.61668,
            0.516657,
        ],
        "KMeans ARI": [
            0.439839,
            0.225424,
            0.280595,
            0.35364,
        ],
        "Silhouette label": [
            0.562681,
            0.61172,
            0.503856,
            0.547946,
        ],
        "cLISI": [
            0.99952,
            1.0,
            0.996694,
            0.992218,
        ],
        "BRAS": [
            0.739654,
            0.786443,
            0.803204,
            0.761943,
        ],
        "iLISI": [
            0.043682,
            0.0,
            0.077398,
            0.19466,
        ],
        "KBET": [
            0.239296,
            0.844529,
            0.353033,
            0.4047,
        ],
        "Graph connectivity": [
            0.854861,
            0.826488,
            0.704139,
            0.857564,
        ],
        "PCR comparison": [
            0,
            0.41701,
            0.096562,
            0.736278,
        ],
        "Batch correction": [
            0.375498,
            0.574894,
            0.406867,
            0.552538,
        ],
        "Bio conservation": [
            0.655811,
            0.558906,
            0.583571,
            0.591027,
        ],
        "Total": [
            0.543686,
            0.565301,
            0.51289,
            0.575631,
        ],
    },
    index=["mouse_pancreas_atlas", "hypomap", "gtex_v9", "dkd"],
)

In [20]:
FACT = 1.5
emb.iloc[:, -1] * (1 + FACT) - (emb.iloc[:, -2] * FACT + emb.iloc[:, -3])

mouse_pancreas_atlas    5.000000e-07
hypomap                -5.000000e-07
gtex_v9                 1.500000e-06
dkd                    -1.000000e-06
dtype: float64

In [21]:
for k, v in res.items():
    if k is None:
        continue
    print(f"{k.split('/')[1]}: ")
    for l, w in v.items():
        cell = 0

        for c in [
            "ari",
            "nmi",
            "isolated_label_asw",
            "clisi",
            "asw_label",
        ]:
            if w[c] == "NA":
                continue
            cell += w[c]
        cell /= 5
        batch = 0

        for b in [
            "pcr",
            "graph_connectivity",
            "asw_batch",
            "ilisi",
            "kbet",
        ]:
            if w[b] == "NA":
                continue
            batch += w[b]
        batch /= 5
        total = cell * 0.4 + batch * 0.6
        print(f"    {l}: {total:.3f}")
    # print(f"         Bio: {cell:.3f}")
    # print(f"         Batch: {batch:.3f}")
    if k.split("/")[1] not in emb.index:
        continue
    print(f"   scPRINT-2 (zero-shot): {emb.loc[k.split('/')[1], 'Total']:.3f}")
    # print(f"         Bio: {emb.loc[k.split('/')[1], 'Bio conservation']:.3f}")
# print(f"         Batch: {emb.loc[k.split('/')[1], 'Batch correction']:.3f}")

# cell_cycle_conservation
# hvg_overlap
# isolated_label_asw

dkd:
    batchelor_fastmnn: 0.627
    batchelor_mnn_correct: 0.601
    bbknn: 0.365
    combat: 0.643
    embed_cell_types: 0.791
    embed_cell_types_jittered: 0.790
    geneformer: 0.150
    harmony: 0.660
    harmonypy: 0.657
    liger: 0.713
    mnnpy: 0.414
    no_integration: 0.491
    no_integration_batch: 0.466
    pyliger: 0.705
    scalex: 0.642
    scanorama: 0.420
    scanvi: 0.634
    scgpt_zeroshot: 0.555
    scimilarity: 0.548
    scvi: 0.635
    shuffle_integration: 0.467
    shuffle_integration_by_batch: 0.250
    shuffle_integration_by_cell_type: 0.724
    uce: 0.505
    scgpt_finetuned: 0.000
    scprint: 0.000
   scPRINT-2 (zero-shot): 0.576
gtex_v9:
    batchelor_fastmnn: 0.538
    batchelor_mnn_correct: 0.000
    bbknn: 0.335
    combat: 0.642
    embed_cell_types: 0.762
    embed_cell_types_jittered: 0.762
    geneformer: 0.231
    harmony: 0.617
    harmonypy: 0.618
    liger: 0.555
    mnnpy: 0.000
    no_integration: 0.545
    no_integration_batch: 0.553
    pyliger: 0.569
    scalex: 0.593
    scanorama: 0.323
    scanvi: 0.604
    scgpt_zeroshot: 0.556
    scimilarity: 0.552
    scvi: 0.617
    shuffle_integration: 0.438
    shuffle_integration_by_batch: 0.298
    shuffle_integration_by_cell_type: 0.674
    uce: 0.559
    scgpt_finetuned: 0.000
    scprint: 0.000
   scPRINT-2 (zero-shot): 0.513
hypomap:
    batchelor_fastmnn: 0.477
    batchelor_mnn_correct: 0.000
    bbknn: 0.338
    combat: 0.554
    embed_cell_types: 0.682
    embed_cell_types_jittered: 0.682
    geneformer: 0.000
    harmony: 0.521
    harmonypy: 0.522
    liger: 0.522
    mnnpy: 0.000
    no_integration: 0.435
    no_integration_batch: 0.527
    pyliger: 0.519
    scalex: 0.554
    scanorama: 0.294
    scanvi: 0.464
    scgpt_zeroshot: 0.000
    scimilarity: 0.000
    scvi: 0.469
    shuffle_integration: 0.383
    shuffle_integration_by_batch: 0.262
    shuffle_integration_by_cell_type: 0.505
    uce: 0.460
    scgpt_finetuned: 0.000
    scprint: 0.000
   scPRINT-2 (zero-shot): 0.565
immune_cell_atlas:
    batchelor_fastmnn: 0.608
    batchelor_mnn_correct: 0.000
    bbknn: 0.341
    combat: 0.620
    embed_cell_types: 0.862
    embed_cell_types_jittered: 0.861
    geneformer: 0.190
    harmony: 0.627
    harmonypy: 0.627
    liger: 0.622
    mnnpy: 0.000
    no_integration: 0.501
    no_integration_batch: 0.514
    pyliger: 0.625
    scalex: 0.607
    scanorama: 0.355
    scanvi: 0.649
    scgpt_zeroshot: 0.520
    scimilarity: 0.593
    scvi: 0.628
    shuffle_integration: 0.460
    shuffle_integration_by_batch: 0.279
    shuffle_integration_by_cell_type: 0.702
    uce: 0.548
    scgpt_finetuned: 0.000
    scprint: 0.000
mouse_pancreas_atlas:
    batchelor_fastmnn: 0.561
    batchelor_mnn_correct: 0.000
    bbknn: 0.330
    combat: 0.631
    embed_cell_types: 0.749
    embed_cell_types_jittered: 0.749
    geneformer: 0.000
    harmony: 0.592
    harmonypy: 0.589
    liger: 0.569
    mnnpy: 0.000
    no_integration: 0.576
    no_integration_batch: 0.571
    pyliger: 0.570
    scalex: 0.577
    scanorama: 0.465
    scanvi: 0.612
    scgpt_zeroshot: 0.000
    scimilarity: 0.000
    scvi: 0.607
    shuffle_integration: 0.459
    shuffle_integration_by_batch: 0.315
    shuffle_integration_by_cell_type: 0.642
    uce: 0.516
    scgpt_finetuned: 0.000
    scprint: 0.000
   scPRINT-2 (zero-shot): 0.544
tabula_sapiens:
    batchelor_fastmnn: 0.535
    batchelor_mnn_correct: 0.000
    bbknn: 0.290
    combat: 0.607
    embed_cell_types: 0.794
    embed_cell_types_jittered: 0.795
    geneformer: 0.232
    harmony: 0.556
    harmonypy: 0.555
    liger: 0.471
    mnnpy: 0.000
    no_integration: 0.499
    no_integration_batch: 0.530
    pyliger: 0.472
    scalex: 0.572
    scanorama: 0.314
    scanvi: 0.569
    scgpt_zeroshot: 0.522
    scimilarity: 0.505
    scvi: 0.564
    shuffle_integration: 0.394
    shuffle_integration_by_batch: 0.275
    shuffle_integration_by_cell_type: 0.624
    uce: 0.486
    scgpt_finetuned: 0.000
    scprint: 0.000

# same with finetuning batch

In [22]:
## ISSUE: many batches to correct, mmd might not be the right tool

## same with fine tuning class

<span id="papermill-error-cell" style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">Execution using papermill encountered an exception here and stopped:</span>

In [23]:
finetuner = FinetuneBatchClass(
    batch_key="donor_id",
    max_len=3000,
)

model, metrics[name + "_fine_tuning"] = finetuner(model=model, train_adata=adata)

TypeError: FinetuneBatchClass.__call__() got an unexpected keyword argument 'train_adata'

In [ ]:
metrics