<span style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">An Exception was encountered at '<a href="#papermill-error-cell">In [23]</a>'.</span>

# open problems (task batch correction / label proj)

In [1]:
import pandas as pd
import requests
import json
from scib_metrics.benchmark import Benchmarker, BioConservation, BatchCorrection
import scanpy as sc
from scprint import scPrint
from scdataloader import Preprocessor
from scprint.tasks import Embedder, FinetuneBatchClass
from scprint.tasks.cell_emb import compute_classification
from scprint.utils import zero_shot_annotation_with_refinement
import numpy as np
import os

%load_ext autoreload
%autoreload 2

/lustre/fswork/projects/rech/xeg/uat95fg/scPRINT/.venv/lib/python3.12/site-packages/transformers/utils/hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(

→ connected lamindb: jkobject/scprint2

/lustre/fswork/projects/rech/xeg/uat95fg/simpler_flash/src/simpler_flash/layer_norm.py:1044: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd
/lustre/fswork/projects/rech/xeg/uat95fg/simpler_flash/src/simpler_flash/layer_norm.py:1107: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd

In [2]:
! uv pip list | grep scib #same version as OP

scib                       1.1.7
scib-metrics               0.5.6

In [3]:
LOC = "./data/" #"/pasteur/appa/scratch/jkalfon/data/spcrint_data/"

In [4]:
if not os.path.exists("data/results_batch.json"):
    url = "https://raw.githubusercontent.com/openproblems-bio/website/main/results/batch_integration/data/results.json"
    response = requests.get(url)

    with open("data/results_batch.json", "w") as f:
        f.write(response.text)

if not os.path.exists("data/results_label.json"):
    url = "https://raw.githubusercontent.com/openproblems-bio/website/main/results/label_projection/data/results.json"
    response = requests.get(url)

    with open("data/results_label.json", "w") as f:
        f.write(response.text)

print("File downloaded successfully!")

File downloaded successfully!

In [5]:
res = {}
with open("data/results_batch.json", "r") as f:
    data_batch = json.load(f)
for dataset in data_batch:
    dataset_id = dataset["dataset_id"]
    if dataset_id not in res:
        res[dataset_id] = {}
    res[dataset_id].update({dataset["method_id"]: dataset["metric_values"]})

In [6]:
res_label = {}
with open("data/results_label.json", "r") as f:
    data_label = json.load(f)
for dataset in data_label:
    dataset_id = dataset["dataset_id"]
    if dataset_id not in res_label:
        res_label[dataset_id] = {}
    res_label[dataset_id].update({dataset["method_id"]: dataset["metric_values"]})

res_label.keys()

dict_keys(['cellxgene_census/dkd', 'cellxgene_census/gtex_v9', 'cellxgene_census/hypomap', 'cellxgene_census/immune_cell_atlas', 'cellxgene_census/mouse_pancreas_atlas', 'cellxgene_census/tabula_sapiens', None])

In [7]:
pd.DataFrame(res_label["cellxgene_census/dkd"])

,knn,logistic_regression,majority_vote,mlp,naive_bayes,random_labels,scanvi,scanvi_scarches,scgpt_zeroshot,scimilarity,scimilarity_knn,seurat_transferdata,singler,true_labels,uce,xgboost,geneformer,scgpt_finetuned,scprint
accuracy,0.9490,0.9572,0.2954,0.9540,0.9269,0.1808,0.9570,0.9570,0.8486,0.8869,0.9553,0.9541,0.9147,1,0.1813,0.9644,NA,NA,NA
f1_macro,0.9286,0.9413,0.0351,0.9245,0.9181,0.0774,0.9360,0.9366,0.5239,0.6233,0.9292,0.9344,0.9027,1,0.0743,0.9225,NA,NA,NA
f1_micro,0.9490,0.9572,0.2954,0.9540,0.9269,0.1808,0.9570,0.9570,0.8486,0.8869,0.9553,0.9541,0.9147,1,0.1813,0.9644,NA,NA,NA
f1_weighted,0.9487,0.9567,0.1347,0.9529,0.9296,0.1801,0.9579,0.9567,0.8339,0.8655,0.9556,0.9544,0.9192,1,0.1790,0.9634,NA,NA,NA

In [8]:
pd.DataFrame(res["cellxgene_census/dkd"])

,batchelor_fastmnn,batchelor_mnn_correct,bbknn,combat,embed_cell_types,embed_cell_types_jittered,geneformer,harmony,harmonypy,liger,mnnpy,no_integration,no_integration_batch,pyliger,scalex,scanorama,scanvi,scgpt_zeroshot,scimilarity,scvi,shuffle_integration,shuffle_integration_by_batch,shuffle_integration_by_cell_type,uce,scgpt_finetuned,scprint
ari,0.7599,0.757,0.7666,0.7673,1,1,0.0024,0.7867,0.7655,0.7463,0.1674,0.5999,0.2884,0.6633,0.6177,0.2302,0.7806,0.7597,0.7103,0.8284,-0.0001,0.0069,0.5604,0.508,NA,NA
asw_batch,0.894,0.799,NA,0.9123,0.9593,0.9573,0.4736,0.9066,0.905,0.8743,0.8846,0.8913,0.7086,0.8876,0.8582,0.9048,0.9099,0.8888,0.8264,0.9166,0.9426,0.9005,0.9328,0.9286,NA,NA
asw_label,0.6657,0.6657,NA,0.613,0.9897,0.9897,0.364,0.6466,0.6463,0.6295,0.5027,0.6276,0.5116,0.6284,0.5917,0.5009,0.6334,0.6318,0.7111,0.5754,0.4945,0.4895,0.6276,0.587,NA,NA
cell_cycle_conservation,0.8574,0.8692,NA,0.7925,0.8104,0.8099,0.0527,0.8495,0.8466,0.6013,0.3797,0.8248,0.8609,0.4286,0.3481,0.3818,0.6302,0.7563,0.6936,0.5349,0.0667,0.0726,0.7069,0.8451,NA,NA
clisi,1,1,0.9622,0.9997,1,1,0.7461,1,1,0.9991,0.8921,0.9998,0.9968,0.9995,0.9939,0.8857,1,0.9994,0.9997,0.9992,0.7301,0.7424,0.9998,0.999,NA,NA
graph_connectivity,0.9745,0.9696,0.984,0.9728,1,1,0.0109,0.977,0.9765,0.9628,0.5458,0.9701,0.5229,0.968,0.9278,0.5459,0.9962,0.9631,0.971,0.9812,0.2488,0.2596,0.9703,0.9568,NA,NA
hvg_overlap,NA,0.4293,NA,0.6649,NA,NA,NA,NA,NA,NA,0.4056,NA,NA,NA,0.2665,0.2484,NA,NA,NA,NA,0.6462,1,0.668,NA,NA,NA
ilisi,0.272,0.2893,0.3526,0.1644,0.4348,0.4305,0,0.333,0.3319,0.4223,0.1732,0.0754,0.0076,0.4235,0.3097,0.2657,0.3153,0.2272,0.2297,0.303,0.4782,0.0755,0.4322,0.2298,NA,NA
isolated_label_asw,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
isolated_label_f1,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
kbet,0.3806,0.2482,NA,0.1687,0.949,0.9433,0,0.4251,0.4187,0.7526,0,0.1529,0.0946,0.7672,0.3209,0.0001,0.2521,0.235,0.2235,0.2538,0.4093,0.0113,0.9511,0.2174,NA,NA
nmi,0.829,0.8248,0.8228,0.8306,1,1,0.0315,0.8322,0.8233,0.8002,0.2288,0.7735,0.5322,0.7619,0.6992,0.2268,0.8646,0.7909,0.7877,0.8495,0.0013,0.015,0.761,0.7228,NA,NA
pcr,0.5339,0.5344,NA,0.9998,0.5898,0.5896,0,0.6805,0.6897,0.8142,0.6494,0,1,0.7925,0.9998,0.5585,0.6277,0.19,0.1773,0.6671,0.9975,0,0.7788,0,NA,NA

In [9]:
model_checkpoint_file = "../models/ji9krimq.ckpt"

In [10]:
model = scPrint.load_from_checkpoint(
    model_checkpoint_file, precpt_gene_emb=None, gene_pos_file=None
)
model = model.to("cuda")

FYI: scPrint is not attached to a `Trainer`.

In [11]:
datasets = {
    "cellxgene_census/dkd": "https://datasets.cellxgene.cziscience.com/46d8d92b-32e0-4ca5-9907-4dbf519c7fc3.h5ad",  # 0.3  ['control_3']
    "cellxgene_census/gtex_v9": "https://datasets.cellxgene.cziscience.com/002308e1-0121-4aa1-b8f2-9d034cf44b0f.h5ad",  # 1gb ['GTEX-16BQI']
    "cellxgene_census/hypomap": "https://datasets.cellxgene.cziscience.com/d3be7423-d664-4913-89a9-a506cae4c28f.h5ad",  # 4gb ['SRR9000488']
    "cellxgene_census/mouse_pancreas_atlas": "https://datasets.cellxgene.cziscience.com/49243c50-bf0c-4b10-87f8-55ec9f455399.h5ad",  # 4gb ['mouse_pancreatic_islet_atlas_Hrovatin__VSG__MUC13639']
    # "cellxgene_census/immune_cell_atlas": "https://datasets.cellxgene.cziscience.com/78819b62-0699-4672-8dc8-d9317b04d255.h5ad",  # 3gb --> issue with scib (too large?)
    # 'cellxgene_census/tabula_sapiens': 'https://datasets.cellxgene.cziscience.com/5a495302-b7cd-4bf9-853e-95627b00bb03.h5ad' # 42gb --> too large for scib
}

test = {
    "cellxgene_census/dkd": ["control_3"],
    "cellxgene_census/gtex_v9": ["GTEX-16BQI"],
    "cellxgene_census/hypomap": ["SRR9000488"],
    "cellxgene_census/mouse_pancreas_atlas": [
        "mouse_pancreatic_islet_atlas_Hrovatin__VSG__MUC13639"
    ],
}

In [12]:
metrics = {}
metacell = model.expr_emb_style == "metacell"
model.mask_zeros = False

In [13]:
for name, url in list(datasets.items())[:]:
    print("doing ", name)
    if not os.path.exists(LOC + "temp/" + name + "_proc.h5ad"):
        adata = sc.read(LOC + name + ".h5ad", backup_url=url)
        preprocessor = Preprocessor(
            force_preprocess=True,
            skip_validate=True,
            # drop_non_primary=False,
            is_symbol=False,
            do_postp=metacell,
        )
        print("")
        adata = preprocessor(adata)
        if metacell:
            sc.pp.neighbors(adata, use_rep="X_pca")
        adata.write_h5ad(LOC + "temp/" + name + "_proc.h5ad")
    else:
        adata = sc.read(LOC + "temp/" + name + "_proc.h5ad")

    embed = Embedder(
        how="random expr",
        max_len=2600,
        num_workers=8,
        pred_embedding=["cell_type_ontology_term_id"],
        keep_all_labels_pred=True,
        doplot=False,
    )
    n_adata, _ = embed(model, adata)
    # cls regular
    loc = n_adata.obs.columns[n_adata.obs.columns.str.startswith("CL:")]
    pred = n_adata.obs.loc[:, loc]
    n_adata.obs["pred_cell_type_ontology_term_id"] = loc[pred.values.argmax(1)].values
    n_adata.obs["_ref_cls"] = loc[pred.values.argmax(1)].values
    metrics[name + "_ref_cls"] = compute_classification(
        n_adata,
        ["cell_type_ontology_term_id"],
        label_decoders=model.label_decoders,
        labels_hierarchy=model.labels_hierarchy,
    )
    n_adata_last = n_adata[n_adata.obs["donor_id"].isin(test[name])]
    metrics[name + "_cls"] = compute_classification(
        n_adata_last,
        ["cell_type_ontology_term_id"],
        label_decoders=model.label_decoders,
        labels_hierarchy=model.labels_hierarchy,
    )
    # cls ref
    for i in range(1):
        pred.iloc[:, :] = zero_shot_annotation_with_refinement(
            pred.values, n_adata, return_raw=True
        ).astype(np.float32)
    n_adata.obs["pred_cell_type_ontology_term_id"] = loc[
        zero_shot_annotation_with_refinement(pred.values, n_adata)
    ].values
    n_adata_last = n_adata[n_adata.obs["donor_id"].isin(test[name])]
    metrics[name + "_smooth_cls"] = compute_classification(
        n_adata_last,
        ["cell_type_ontology_term_id"],
        label_decoders=model.label_decoders,
        labels_hierarchy=model.labels_hierarchy,
    )
    # cls cluster
    if "seurat_clusters" in n_adata.obs:
        n_adata.obs["leiden"] = n_adata.obs["seurat_clusters"]
    if "leiden" not in n_adata.obs:
        sc.tl.leiden(n_adata, resolution=4.0)
    for i in n_adata.obs["leiden"].unique():
        n_adata.obs.loc[
            n_adata.obs["leiden"] == str(i), "pred_cell_type_ontology_term_id"
        ] = loc[pred[n_adata.obs["leiden"] == str(i)].values.sum(0).argsort()[::-1][0]]
    n_adata_last = n_adata[n_adata.obs["donor_id"].isin(test[name])]
    metrics[name + "_clust_cls"] = compute_classification(
        n_adata_last,
        ["cell_type_ontology_term_id"],
        label_decoders=model.label_decoders,
        labels_hierarchy=model.labels_hierarchy,
    )
    print(metrics)
    # batch correction
    # bm = Benchmarker(
    #    n_adata,
    #    batch_key="donor_id",  # "batch",  # batch, tech, assay_ontology_term_id, donor_id
    #    label_key="cell_type",  # celltype
    #    embedding_obsm_keys=["scprint_emb"],
    #    bio_conservation_metrics=BioConservation(),
    #    batch_correction_metrics=BatchCorrection(),
    #    n_jobs=10,
    # )
    # del n_adata, adata
    # bm.benchmark()
    # metrics[name + "_batch_corr"] = bm.get_results()
    # bm.plot_results_table(min_max_scale=False)
    # print(metrics[name + "_batch_corr"])

doing  cellxgene_census/dkd

/lustre/fswork/projects/rech/xeg/uat95fg/scdataloader/scdataloader/utils.py:427: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  organismdf = pd.concat(organismdf)

predict epoch start

  0%|          | 0/613 [00:00<?, ?it/s]

  0%|          | 1/613 [00:02<24:49,  2.43s/it]

  0%|          | 2/613 [00:03<16:57,  1.66s/it]

  0%|          | 3/613 [00:04<14:27,  1.42s/it]

  1%|          | 4/613 [00:05<13:16,  1.31s/it]

  1%|          | 5/613 [00:06<12:35,  1.24s/it]

  1%|          | 6/613 [00:08<12:10,  1.20s/it]

  1%|          | 7/613 [00:09<11:54,  1.18s/it]

  1%|▏         | 8/613 [00:10<11:43,  1.16s/it]

  1%|▏         | 9/613 [00:11<11:37,  1.16s/it]

  2%|▏         | 10/613 [00:12<11:32,  1.15s/it]

  2%|▏         | 11/613 [00:13<11:28,  1.14s/it]

  2%|▏         | 12/613 [00:14<11:24,  1.14s/it]

  2%|▏         | 13/613 [00:16<11:22,  1.14s/it]

  2%|▏         | 14/613 [00:17<11:20,  1.14s/it]

  2%|▏         | 15/613 [00:18<11:19,  1.14s/it]

  3%|▎         | 16/613 [00:19<11:17,  1.14s/it]

  3%|▎         | 17/613 [00:20<11:16,  1.14s/it]

  3%|▎         | 18/613 [00:21<11:15,  1.13s/it]

  3%|▎         | 19/613 [00:22<11:13,  1.13s/it]

  3%|▎         | 20/613 [00:23<11:12,  1.13s/it]

  3%|▎         | 21/613 [00:25<11:11,  1.13s/it]

  4%|▎         | 22/613 [00:26<11:10,  1.13s/it]

  4%|▍         | 23/613 [00:27<11:09,  1.13s/it]

  4%|▍         | 24/613 [00:28<11:09,  1.14s/it]

  4%|▍         | 25/613 [00:29<11:07,  1.14s/it]

  4%|▍         | 26/613 [00:30<11:06,  1.14s/it]

  4%|▍         | 27/613 [00:31<11:05,  1.14s/it]

  5%|▍         | 28/613 [00:33<11:04,  1.14s/it]

  5%|▍         | 29/613 [00:34<11:03,  1.14s/it]

  5%|▍         | 30/613 [00:35<11:02,  1.14s/it]

  5%|▌         | 31/613 [00:36<11:01,  1.14s/it]

  5%|▌         | 32/613 [00:37<11:00,  1.14s/it]

  5%|▌         | 33/613 [00:38<10:59,  1.14s/it]

  6%|▌         | 34/613 [00:39<10:58,  1.14s/it]

  6%|▌         | 35/613 [00:40<10:57,  1.14s/it]

  6%|▌         | 36/613 [00:42<10:56,  1.14s/it]

  6%|▌         | 37/613 [00:43<10:55,  1.14s/it]

  6%|▌         | 38/613 [00:44<10:54,  1.14s/it]

  6%|▋         | 39/613 [00:45<10:53,  1.14s/it]

  7%|▋         | 40/613 [00:46<10:52,  1.14s/it]

  7%|▋         | 41/613 [00:47<10:51,  1.14s/it]

  7%|▋         | 42/613 [00:48<10:49,  1.14s/it]

  7%|▋         | 43/613 [00:50<10:49,  1.14s/it]

  7%|▋         | 44/613 [00:51<10:47,  1.14s/it]

  7%|▋         | 45/613 [00:52<10:45,  1.14s/it]

  8%|▊         | 46/613 [00:53<10:44,  1.14s/it]

  8%|▊         | 47/613 [00:54<10:43,  1.14s/it]

  8%|▊         | 48/613 [00:55<10:42,  1.14s/it]

  8%|▊         | 49/613 [00:56<10:42,  1.14s/it]

  8%|▊         | 50/613 [00:58<10:41,  1.14s/it]

  8%|▊         | 51/613 [00:59<10:39,  1.14s/it]

  8%|▊         | 52/613 [01:00<10:38,  1.14s/it]

  9%|▊         | 53/613 [01:01<10:37,  1.14s/it]

  9%|▉         | 54/613 [01:02<10:36,  1.14s/it]

  9%|▉         | 55/613 [01:03<10:35,  1.14s/it]

  9%|▉         | 56/613 [01:04<10:34,  1.14s/it]

  9%|▉         | 57/613 [01:06<10:33,  1.14s/it]

  9%|▉         | 58/613 [01:07<10:32,  1.14s/it]

 10%|▉         | 59/613 [01:08<10:31,  1.14s/it]

 10%|▉         | 60/613 [01:09<10:30,  1.14s/it]

 10%|▉         | 61/613 [01:10<10:28,  1.14s/it]

 10%|█         | 62/613 [01:11<10:27,  1.14s/it]

 10%|█         | 63/613 [01:12<10:26,  1.14s/it]

 10%|█         | 64/613 [01:14<10:26,  1.14s/it]

 11%|█         | 65/613 [01:15<10:24,  1.14s/it]

 11%|█         | 66/613 [01:16<10:23,  1.14s/it]

 11%|█         | 67/613 [01:17<10:22,  1.14s/it]

 11%|█         | 68/613 [01:18<10:21,  1.14s/it]

 11%|█▏        | 69/613 [01:19<10:19,  1.14s/it]

 11%|█▏        | 70/613 [01:20<10:18,  1.14s/it]

 12%|█▏        | 71/613 [01:21<10:17,  1.14s/it]

 12%|█▏        | 72/613 [01:23<10:16,  1.14s/it]

 12%|█▏        | 73/613 [01:24<10:16,  1.14s/it]

 12%|█▏        | 74/613 [01:25<10:15,  1.14s/it]

 12%|█▏        | 75/613 [01:26<10:14,  1.14s/it]

 12%|█▏        | 76/613 [01:27<10:12,  1.14s/it]

 13%|█▎        | 77/613 [01:28<10:12,  1.14s/it]

 13%|█▎        | 78/613 [01:29<10:11,  1.14s/it]

 13%|█▎        | 79/613 [01:31<10:10,  1.14s/it]

 13%|█▎        | 80/613 [01:32<10:09,  1.14s/it]

 13%|█▎        | 81/613 [01:33<10:08,  1.14s/it]

 13%|█▎        | 82/613 [01:34<10:07,  1.14s/it]

 14%|█▎        | 83/613 [01:35<10:05,  1.14s/it]

 14%|█▎        | 84/613 [01:36<10:04,  1.14s/it]

 14%|█▍        | 85/613 [01:37<10:03,  1.14s/it]

 14%|█▍        | 86/613 [01:39<10:01,  1.14s/it]

 14%|█▍        | 87/613 [01:40<10:00,  1.14s/it]

 14%|█▍        | 88/613 [01:41<09:59,  1.14s/it]

 15%|█▍        | 89/613 [01:42<09:58,  1.14s/it]

 15%|█▍        | 90/613 [01:43<09:57,  1.14s/it]

 15%|█▍        | 91/613 [01:44<09:56,  1.14s/it]

 15%|█▌        | 92/613 [01:45<09:54,  1.14s/it]

 15%|█▌        | 93/613 [01:47<09:53,  1.14s/it]

 15%|█▌        | 94/613 [01:48<09:53,  1.14s/it]

 15%|█▌        | 95/613 [01:49<09:52,  1.14s/it]

 16%|█▌        | 96/613 [01:50<09:51,  1.14s/it]

 16%|█▌        | 97/613 [01:51<09:50,  1.14s/it]

 16%|█▌        | 98/613 [01:52<09:49,  1.14s/it]

 16%|█▌        | 99/613 [01:53<09:47,  1.14s/it]

 16%|█▋        | 100/613 [01:55<09:46,  1.14s/it]

 16%|█▋        | 101/613 [01:56<09:45,  1.14s/it]

 17%|█▋        | 102/613 [01:57<09:44,  1.14s/it]

 17%|█▋        | 103/613 [01:58<09:43,  1.14s/it]

 17%|█▋        | 104/613 [01:59<09:41,  1.14s/it]

 17%|█▋        | 105/613 [02:00<09:40,  1.14s/it]

 17%|█▋        | 106/613 [02:01<09:39,  1.14s/it]

 17%|█▋        | 107/613 [02:03<09:38,  1.14s/it]

 18%|█▊        | 108/613 [02:04<09:37,  1.14s/it]

 18%|█▊        | 109/613 [02:05<09:36,  1.14s/it]

 18%|█▊        | 110/613 [02:06<09:35,  1.14s/it]

 18%|█▊        | 111/613 [02:07<09:33,  1.14s/it]

 18%|█▊        | 112/613 [02:08<09:32,  1.14s/it]

 18%|█▊        | 113/613 [02:10<09:32,  1.14s/it]

 19%|█▊        | 114/613 [02:11<09:30,  1.14s/it]

 19%|█▉        | 115/613 [02:12<09:30,  1.14s/it]

 19%|█▉        | 116/613 [02:13<09:29,  1.15s/it]

 19%|█▉        | 117/613 [02:14<09:28,  1.15s/it]

 19%|█▉        | 118/613 [02:15<09:27,  1.15s/it]

 19%|█▉        | 119/613 [02:16<09:25,  1.15s/it]

 20%|█▉        | 120/613 [02:18<09:24,  1.15s/it]

 20%|█▉        | 121/613 [02:19<09:23,  1.15s/it]

 20%|█▉        | 122/613 [02:20<09:22,  1.15s/it]

 20%|██        | 123/613 [02:21<09:22,  1.15s/it]

 20%|██        | 124/613 [02:22<09:20,  1.15s/it]

 20%|██        | 125/613 [02:23<09:19,  1.15s/it]

 21%|██        | 126/613 [02:24<09:17,  1.15s/it]

 21%|██        | 127/613 [02:26<09:16,  1.14s/it]

 21%|██        | 128/613 [02:27<09:15,  1.15s/it]

 21%|██        | 129/613 [02:28<09:15,  1.15s/it]

 21%|██        | 130/613 [02:29<09:14,  1.15s/it]

 21%|██▏       | 131/613 [02:30<09:13,  1.15s/it]

 22%|██▏       | 132/613 [02:31<09:11,  1.15s/it]

 22%|██▏       | 133/613 [02:32<09:11,  1.15s/it]

 22%|██▏       | 134/613 [02:34<09:09,  1.15s/it]

 22%|██▏       | 135/613 [02:35<09:08,  1.15s/it]

 22%|██▏       | 136/613 [02:36<09:07,  1.15s/it]

 22%|██▏       | 137/613 [02:37<09:06,  1.15s/it]

 23%|██▎       | 138/613 [02:38<09:05,  1.15s/it]

 23%|██▎       | 139/613 [02:39<09:03,  1.15s/it]

 23%|██▎       | 140/613 [02:40<09:02,  1.15s/it]

 23%|██▎       | 141/613 [02:42<09:01,  1.15s/it]

 23%|██▎       | 142/613 [02:43<09:01,  1.15s/it]

 23%|██▎       | 143/613 [02:44<09:00,  1.15s/it]

 23%|██▎       | 144/613 [02:45<08:59,  1.15s/it]

 24%|██▎       | 145/613 [02:46<08:57,  1.15s/it]

 24%|██▍       | 146/613 [02:47<08:55,  1.15s/it]

 24%|██▍       | 147/613 [02:49<08:55,  1.15s/it]

 24%|██▍       | 148/613 [02:50<08:55,  1.15s/it]

 24%|██▍       | 149/613 [02:51<08:53,  1.15s/it]

 24%|██▍       | 150/613 [02:52<08:52,  1.15s/it]

 25%|██▍       | 151/613 [02:53<08:51,  1.15s/it]

 25%|██▍       | 152/613 [02:54<08:50,  1.15s/it]

 25%|██▍       | 153/613 [02:55<08:49,  1.15s/it]

 25%|██▌       | 154/613 [02:57<08:49,  1.15s/it]

 25%|██▌       | 155/613 [02:58<08:47,  1.15s/it]

 25%|██▌       | 156/613 [02:59<08:46,  1.15s/it]

 26%|██▌       | 157/613 [03:00<08:45,  1.15s/it]

 26%|██▌       | 158/613 [03:01<08:43,  1.15s/it]

 26%|██▌       | 159/613 [03:02<08:42,  1.15s/it]

 26%|██▌       | 160/613 [03:03<08:41,  1.15s/it]

 26%|██▋       | 161/613 [03:05<08:39,  1.15s/it]

 26%|██▋       | 162/613 [03:06<08:38,  1.15s/it]

 27%|██▋       | 163/613 [03:07<08:37,  1.15s/it]

 27%|██▋       | 164/613 [03:08<08:36,  1.15s/it]

 27%|██▋       | 165/613 [03:09<08:34,  1.15s/it]

 27%|██▋       | 166/613 [03:10<08:34,  1.15s/it]

 27%|██▋       | 167/613 [03:12<08:33,  1.15s/it]

 27%|██▋       | 168/613 [03:13<08:31,  1.15s/it]

 28%|██▊       | 169/613 [03:14<08:30,  1.15s/it]

 28%|██▊       | 170/613 [03:15<08:29,  1.15s/it]

 28%|██▊       | 171/613 [03:16<08:28,  1.15s/it]

 28%|██▊       | 172/613 [03:17<08:26,  1.15s/it]

 28%|██▊       | 173/613 [03:18<08:25,  1.15s/it]

 28%|██▊       | 174/613 [03:20<08:24,  1.15s/it]

 29%|██▊       | 175/613 [03:21<08:23,  1.15s/it]

 29%|██▊       | 176/613 [03:22<08:22,  1.15s/it]

 29%|██▉       | 177/613 [03:23<08:21,  1.15s/it]

 29%|██▉       | 178/613 [03:24<08:20,  1.15s/it]

 29%|██▉       | 179/613 [03:25<08:19,  1.15s/it]

 29%|██▉       | 180/613 [03:26<08:18,  1.15s/it]

 30%|██▉       | 181/613 [03:28<08:17,  1.15s/it]

 30%|██▉       | 182/613 [03:29<08:16,  1.15s/it]

 30%|██▉       | 183/613 [03:30<08:15,  1.15s/it]

 30%|███       | 184/613 [03:31<08:14,  1.15s/it]

 30%|███       | 185/613 [03:32<08:13,  1.15s/it]

 30%|███       | 186/613 [03:33<08:11,  1.15s/it]

 31%|███       | 187/613 [03:35<08:11,  1.15s/it]

 31%|███       | 188/613 [03:36<08:09,  1.15s/it]

 31%|███       | 189/613 [03:37<08:08,  1.15s/it]

 31%|███       | 190/613 [03:38<08:06,  1.15s/it]

 31%|███       | 191/613 [03:39<08:06,  1.15s/it]

 31%|███▏      | 192/613 [03:40<08:05,  1.15s/it]

 31%|███▏      | 193/613 [03:41<08:04,  1.15s/it]

 32%|███▏      | 194/613 [03:43<08:03,  1.15s/it]

 32%|███▏      | 195/613 [03:44<08:02,  1.15s/it]

 32%|███▏      | 196/613 [03:45<08:00,  1.15s/it]

 32%|███▏      | 197/613 [03:46<07:59,  1.15s/it]

 32%|███▏      | 198/613 [03:47<07:58,  1.15s/it]

 32%|███▏      | 199/613 [03:48<07:57,  1.15s/it]

 33%|███▎      | 200/613 [03:50<07:56,  1.15s/it]

 33%|███▎      | 201/613 [03:51<07:55,  1.15s/it]

 33%|███▎      | 202/613 [03:52<07:53,  1.15s/it]

 33%|███▎      | 203/613 [03:53<07:53,  1.15s/it]

 33%|███▎      | 204/613 [03:54<07:51,  1.15s/it]

 33%|███▎      | 205/613 [03:55<07:50,  1.15s/it]

 34%|███▎      | 206/613 [03:56<07:48,  1.15s/it]

 34%|███▍      | 207/613 [03:58<07:47,  1.15s/it]

 34%|███▍      | 208/613 [03:59<07:46,  1.15s/it]

 34%|███▍      | 209/613 [04:00<07:46,  1.15s/it]

 34%|███▍      | 210/613 [04:01<07:44,  1.15s/it]

 34%|███▍      | 211/613 [04:02<07:43,  1.15s/it]

 35%|███▍      | 212/613 [04:03<07:42,  1.15s/it]

 35%|███▍      | 213/613 [04:05<07:41,  1.15s/it]

 35%|███▍      | 214/613 [04:06<07:40,  1.15s/it]

 35%|███▌      | 215/613 [04:07<07:38,  1.15s/it]

 35%|███▌      | 216/613 [04:08<07:37,  1.15s/it]

 35%|███▌      | 217/613 [04:09<07:36,  1.15s/it]

 36%|███▌      | 218/613 [04:10<07:35,  1.15s/it]

 36%|███▌      | 219/613 [04:11<07:34,  1.15s/it]

 36%|███▌      | 220/613 [04:13<07:33,  1.15s/it]

 36%|███▌      | 221/613 [04:14<07:32,  1.15s/it]

 36%|███▌      | 222/613 [04:15<07:30,  1.15s/it]

 36%|███▋      | 223/613 [04:16<07:29,  1.15s/it]

 37%|███▋      | 224/613 [04:17<07:28,  1.15s/it]

 37%|███▋      | 225/613 [04:18<07:27,  1.15s/it]

 37%|███▋      | 226/613 [04:20<07:26,  1.15s/it]

 37%|███▋      | 227/613 [04:21<07:25,  1.15s/it]

 37%|███▋      | 228/613 [04:22<07:24,  1.15s/it]

 37%|███▋      | 229/613 [04:23<07:22,  1.15s/it]

 38%|███▊      | 230/613 [04:24<07:21,  1.15s/it]

 38%|███▊      | 231/613 [04:25<07:20,  1.15s/it]

 38%|███▊      | 232/613 [04:26<07:19,  1.15s/it]

 38%|███▊      | 233/613 [04:28<07:18,  1.15s/it]

 38%|███▊      | 234/613 [04:29<07:17,  1.15s/it]

 38%|███▊      | 235/613 [04:30<07:16,  1.15s/it]

 38%|███▊      | 236/613 [04:31<07:15,  1.15s/it]

 39%|███▊      | 237/613 [04:32<07:14,  1.15s/it]

 39%|███▉      | 238/613 [04:33<07:12,  1.15s/it]

 39%|███▉      | 239/613 [04:35<07:11,  1.15s/it]

 39%|███▉      | 240/613 [04:36<07:10,  1.15s/it]

 39%|███▉      | 241/613 [04:37<07:09,  1.15s/it]

 39%|███▉      | 242/613 [04:38<07:08,  1.15s/it]

 40%|███▉      | 243/613 [04:39<07:07,  1.15s/it]

 40%|███▉      | 244/613 [04:40<07:05,  1.15s/it]

 40%|███▉      | 245/613 [04:41<07:04,  1.15s/it]

 40%|████      | 246/613 [04:43<07:03,  1.15s/it]

 40%|████      | 247/613 [04:44<07:01,  1.15s/it]

 40%|████      | 248/613 [04:45<07:01,  1.15s/it]

 41%|████      | 249/613 [04:46<06:59,  1.15s/it]

 41%|████      | 250/613 [04:47<06:58,  1.15s/it]

 41%|████      | 251/613 [04:48<06:57,  1.15s/it]

 41%|████      | 252/613 [04:50<06:56,  1.15s/it]

 41%|████▏     | 253/613 [04:51<06:55,  1.15s/it]

 41%|████▏     | 254/613 [04:52<06:53,  1.15s/it]

 42%|████▏     | 255/613 [04:53<06:52,  1.15s/it]

 42%|████▏     | 256/613 [04:54<06:52,  1.16s/it]

 42%|████▏     | 257/613 [04:55<06:51,  1.16s/it]

 42%|████▏     | 258/613 [04:56<06:50,  1.16s/it]

 42%|████▏     | 259/613 [04:58<06:48,  1.15s/it]

 42%|████▏     | 260/613 [04:59<06:47,  1.16s/it]

 43%|████▎     | 261/613 [05:00<06:46,  1.16s/it]

 43%|████▎     | 262/613 [05:01<06:45,  1.15s/it]

 43%|████▎     | 263/613 [05:02<06:44,  1.15s/it]

 43%|████▎     | 264/613 [05:03<06:43,  1.16s/it]

 43%|████▎     | 265/613 [05:05<06:42,  1.16s/it]

 43%|████▎     | 266/613 [05:06<06:41,  1.16s/it]

 44%|████▎     | 267/613 [05:07<06:40,  1.16s/it]

 44%|████▎     | 268/613 [05:08<06:39,  1.16s/it]

 44%|████▍     | 269/613 [05:09<06:38,  1.16s/it]

 44%|████▍     | 270/613 [05:10<06:36,  1.16s/it]

 44%|████▍     | 271/613 [05:11<06:35,  1.16s/it]

 44%|████▍     | 272/613 [05:13<06:34,  1.16s/it]

 45%|████▍     | 273/613 [05:14<06:32,  1.16s/it]

 45%|████▍     | 274/613 [05:15<06:31,  1.16s/it]

 45%|████▍     | 275/613 [05:16<06:30,  1.16s/it]

 45%|████▌     | 276/613 [05:17<06:29,  1.15s/it]

 45%|████▌     | 277/613 [05:18<06:28,  1.16s/it]

 45%|████▌     | 278/613 [05:20<06:27,  1.16s/it]

 46%|████▌     | 279/613 [05:21<06:26,  1.16s/it]

 46%|████▌     | 280/613 [05:22<06:24,  1.16s/it]

 46%|████▌     | 281/613 [05:23<06:23,  1.16s/it]

 46%|████▌     | 282/613 [05:24<06:22,  1.15s/it]

 46%|████▌     | 283/613 [05:25<06:21,  1.15s/it]

 46%|████▋     | 284/613 [05:26<06:19,  1.15s/it]

 46%|████▋     | 285/613 [05:28<06:19,  1.16s/it]

 47%|████▋     | 286/613 [05:29<06:18,  1.16s/it]

 47%|████▋     | 287/613 [05:30<06:17,  1.16s/it]

 47%|████▋     | 288/613 [05:31<06:15,  1.16s/it]

 47%|████▋     | 289/613 [05:32<06:14,  1.16s/it]

 47%|████▋     | 290/613 [05:33<06:13,  1.16s/it]

 47%|████▋     | 291/613 [05:35<06:12,  1.16s/it]

 48%|████▊     | 292/613 [05:36<06:10,  1.16s/it]

 48%|████▊     | 293/613 [05:37<06:09,  1.16s/it]

 48%|████▊     | 294/613 [05:38<06:08,  1.16s/it]

 48%|████▊     | 295/613 [05:39<06:07,  1.16s/it]

 48%|████▊     | 296/613 [05:40<06:06,  1.16s/it]

 48%|████▊     | 297/613 [05:42<06:05,  1.16s/it]

 49%|████▊     | 298/613 [05:43<06:04,  1.16s/it]

 49%|████▉     | 299/613 [05:44<06:03,  1.16s/it]

 49%|████▉     | 300/613 [05:45<06:02,  1.16s/it]

 49%|████▉     | 301/613 [05:46<06:00,  1.16s/it]

 49%|████▉     | 302/613 [05:47<05:59,  1.16s/it]

 49%|████▉     | 303/613 [05:48<05:58,  1.16s/it]

 50%|████▉     | 304/613 [05:50<05:57,  1.16s/it]

 50%|████▉     | 305/613 [05:51<05:56,  1.16s/it]

 50%|████▉     | 306/613 [05:52<05:55,  1.16s/it]

 50%|█████     | 307/613 [05:53<05:54,  1.16s/it]

 50%|█████     | 308/613 [05:54<05:52,  1.16s/it]

 50%|█████     | 309/613 [05:55<05:52,  1.16s/it]

 51%|█████     | 310/613 [05:57<05:50,  1.16s/it]

 51%|█████     | 311/613 [05:58<05:49,  1.16s/it]

 51%|█████     | 312/613 [05:59<05:48,  1.16s/it]

 51%|█████     | 313/613 [06:00<05:46,  1.16s/it]

 51%|█████     | 314/613 [06:01<05:46,  1.16s/it]

 51%|█████▏    | 315/613 [06:02<05:45,  1.16s/it]

 52%|█████▏    | 316/613 [06:04<05:43,  1.16s/it]

 52%|█████▏    | 317/613 [06:05<05:42,  1.16s/it]

 52%|█████▏    | 318/613 [06:06<05:41,  1.16s/it]

 52%|█████▏    | 319/613 [06:07<05:39,  1.16s/it]

 52%|█████▏    | 320/613 [06:08<05:38,  1.16s/it]

 52%|█████▏    | 321/613 [06:09<05:37,  1.16s/it]

 53%|█████▎    | 322/613 [06:10<05:36,  1.16s/it]

 53%|█████▎    | 323/613 [06:12<05:35,  1.16s/it]

 53%|█████▎    | 324/613 [06:13<05:34,  1.16s/it]

 53%|█████▎    | 325/613 [06:14<05:33,  1.16s/it]

 53%|█████▎    | 326/613 [06:15<05:32,  1.16s/it]

 53%|█████▎    | 327/613 [06:16<05:31,  1.16s/it]

 54%|█████▎    | 328/613 [06:17<05:29,  1.16s/it]

 54%|█████▎    | 329/613 [06:19<05:28,  1.16s/it]

 54%|█████▍    | 330/613 [06:20<05:27,  1.16s/it]

 54%|█████▍    | 331/613 [06:21<05:26,  1.16s/it]

 54%|█████▍    | 332/613 [06:22<05:24,  1.16s/it]

 54%|█████▍    | 333/613 [06:23<05:23,  1.16s/it]

 54%|█████▍    | 334/613 [06:24<05:22,  1.16s/it]

 55%|█████▍    | 335/613 [06:26<05:21,  1.16s/it]

 55%|█████▍    | 336/613 [06:27<05:20,  1.16s/it]

 55%|█████▍    | 337/613 [06:28<05:19,  1.16s/it]

 55%|█████▌    | 338/613 [06:29<05:18,  1.16s/it]

 55%|█████▌    | 339/613 [06:30<05:17,  1.16s/it]

 55%|█████▌    | 340/613 [06:31<05:16,  1.16s/it]

 56%|█████▌    | 341/613 [06:32<05:15,  1.16s/it]

 56%|█████▌    | 342/613 [06:34<05:13,  1.16s/it]

 56%|█████▌    | 343/613 [06:35<05:12,  1.16s/it]

 56%|█████▌    | 344/613 [06:36<05:11,  1.16s/it]

 56%|█████▋    | 345/613 [06:37<05:10,  1.16s/it]

 56%|█████▋    | 346/613 [06:38<05:09,  1.16s/it]

 57%|█████▋    | 347/613 [06:39<05:08,  1.16s/it]

 57%|█████▋    | 348/613 [06:41<05:06,  1.16s/it]

 57%|█████▋    | 349/613 [06:42<05:05,  1.16s/it]

 57%|█████▋    | 350/613 [06:43<05:04,  1.16s/it]

 57%|█████▋    | 351/613 [06:44<05:03,  1.16s/it]

 57%|█████▋    | 352/613 [06:45<05:01,  1.16s/it]

 58%|█████▊    | 353/613 [06:46<05:00,  1.16s/it]

 58%|█████▊    | 354/613 [06:48<04:59,  1.16s/it]

 58%|█████▊    | 355/613 [06:49<04:58,  1.16s/it]

 58%|█████▊    | 356/613 [06:50<04:57,  1.16s/it]

 58%|█████▊    | 357/613 [06:51<04:56,  1.16s/it]

 58%|█████▊    | 358/613 [06:52<04:55,  1.16s/it]

 59%|█████▊    | 359/613 [06:53<04:54,  1.16s/it]

 59%|█████▊    | 360/613 [06:54<04:52,  1.16s/it]

 59%|█████▉    | 361/613 [06:56<04:51,  1.16s/it]

 59%|█████▉    | 362/613 [06:57<04:50,  1.16s/it]

 59%|█████▉    | 363/613 [06:58<04:49,  1.16s/it]

 59%|█████▉    | 364/613 [06:59<04:48,  1.16s/it]

 60%|█████▉    | 365/613 [07:00<04:47,  1.16s/it]

 60%|█████▉    | 366/613 [07:01<04:45,  1.16s/it]

 60%|█████▉    | 367/613 [07:03<04:45,  1.16s/it]

 60%|██████    | 368/613 [07:04<04:43,  1.16s/it]

 60%|██████    | 369/613 [07:05<04:42,  1.16s/it]

 60%|██████    | 370/613 [07:06<04:41,  1.16s/it]

 61%|██████    | 371/613 [07:07<04:39,  1.16s/it]

 61%|██████    | 372/613 [07:08<04:38,  1.16s/it]

 61%|██████    | 373/613 [07:10<04:38,  1.16s/it]

 61%|██████    | 374/613 [07:11<04:36,  1.16s/it]

 61%|██████    | 375/613 [07:12<04:35,  1.16s/it]

 61%|██████▏   | 376/613 [07:13<04:34,  1.16s/it]

 62%|██████▏   | 377/613 [07:14<04:33,  1.16s/it]

 62%|██████▏   | 378/613 [07:15<04:32,  1.16s/it]

 62%|██████▏   | 379/613 [07:16<04:31,  1.16s/it]

 62%|██████▏   | 380/613 [07:18<04:30,  1.16s/it]

 62%|██████▏   | 381/613 [07:19<04:28,  1.16s/it]

 62%|██████▏   | 382/613 [07:20<04:27,  1.16s/it]

 62%|██████▏   | 383/613 [07:21<04:26,  1.16s/it]

 63%|██████▎   | 384/613 [07:22<04:25,  1.16s/it]

 63%|██████▎   | 385/613 [07:23<04:24,  1.16s/it]

 63%|██████▎   | 386/613 [07:25<04:23,  1.16s/it]

 63%|██████▎   | 387/613 [07:26<04:21,  1.16s/it]

 63%|██████▎   | 388/613 [07:27<04:20,  1.16s/it]

 63%|██████▎   | 389/613 [07:28<04:19,  1.16s/it]

 64%|██████▎   | 390/613 [07:29<04:18,  1.16s/it]

 64%|██████▍   | 391/613 [07:30<04:17,  1.16s/it]

 64%|██████▍   | 392/613 [07:32<04:15,  1.16s/it]

 64%|██████▍   | 393/613 [07:33<04:14,  1.16s/it]

 64%|██████▍   | 394/613 [07:34<04:13,  1.16s/it]

 64%|██████▍   | 395/613 [07:35<04:12,  1.16s/it]

 65%|██████▍   | 396/613 [07:36<04:11,  1.16s/it]

 65%|██████▍   | 397/613 [07:37<04:09,  1.16s/it]

 65%|██████▍   | 398/613 [07:38<04:08,  1.16s/it]

 65%|██████▌   | 399/613 [07:40<04:07,  1.16s/it]

 65%|██████▌   | 400/613 [07:41<04:06,  1.16s/it]

 65%|██████▌   | 401/613 [07:42<04:05,  1.16s/it]

 66%|██████▌   | 402/613 [07:43<04:04,  1.16s/it]

 66%|██████▌   | 403/613 [07:44<04:03,  1.16s/it]

 66%|██████▌   | 404/613 [07:45<04:02,  1.16s/it]

 66%|██████▌   | 405/613 [07:47<04:00,  1.16s/it]

 66%|██████▌   | 406/613 [07:48<03:59,  1.16s/it]

 66%|██████▋   | 407/613 [07:49<03:58,  1.16s/it]

 67%|██████▋   | 408/613 [07:50<03:57,  1.16s/it]

 67%|██████▋   | 409/613 [07:51<03:56,  1.16s/it]

 67%|██████▋   | 410/613 [07:52<03:55,  1.16s/it]

 67%|██████▋   | 411/613 [07:54<03:53,  1.16s/it]

 67%|██████▋   | 412/613 [07:55<03:52,  1.16s/it]

 67%|██████▋   | 413/613 [07:56<03:51,  1.16s/it]

 68%|██████▊   | 414/613 [07:57<03:50,  1.16s/it]

 68%|██████▊   | 415/613 [07:58<03:49,  1.16s/it]

 68%|██████▊   | 416/613 [07:59<03:48,  1.16s/it]

 68%|██████▊   | 417/613 [08:00<03:47,  1.16s/it]

 68%|██████▊   | 418/613 [08:02<03:45,  1.16s/it]

 68%|██████▊   | 419/613 [08:03<03:44,  1.16s/it]

 69%|██████▊   | 420/613 [08:04<03:43,  1.16s/it]

 69%|██████▊   | 421/613 [08:05<03:42,  1.16s/it]

 69%|██████▉   | 422/613 [08:06<03:41,  1.16s/it]

 69%|██████▉   | 423/613 [08:07<03:40,  1.16s/it]

 69%|██████▉   | 424/613 [08:09<03:38,  1.16s/it]

 69%|██████▉   | 425/613 [08:10<03:37,  1.16s/it]

 69%|██████▉   | 426/613 [08:11<03:36,  1.16s/it]

 70%|██████▉   | 427/613 [08:12<03:35,  1.16s/it]

 70%|██████▉   | 428/613 [08:13<03:34,  1.16s/it]

 70%|██████▉   | 429/613 [08:14<03:33,  1.16s/it]

 70%|███████   | 430/613 [08:16<03:32,  1.16s/it]

 70%|███████   | 431/613 [08:17<03:31,  1.16s/it]

 70%|███████   | 432/613 [08:18<03:29,  1.16s/it]

 71%|███████   | 433/613 [08:19<03:28,  1.16s/it]

 71%|███████   | 434/613 [08:20<03:27,  1.16s/it]

 71%|███████   | 435/613 [08:21<03:26,  1.16s/it]

 71%|███████   | 436/613 [08:22<03:25,  1.16s/it]

 71%|███████▏  | 437/613 [08:24<03:23,  1.16s/it]

 71%|███████▏  | 438/613 [08:25<03:22,  1.16s/it]

 72%|███████▏  | 439/613 [08:26<03:21,  1.16s/it]

 72%|███████▏  | 440/613 [08:27<03:20,  1.16s/it]

 72%|███████▏  | 441/613 [08:28<03:19,  1.16s/it]

 72%|███████▏  | 442/613 [08:29<03:18,  1.16s/it]

 72%|███████▏  | 443/613 [08:31<03:17,  1.16s/it]

 72%|███████▏  | 444/613 [08:32<03:16,  1.16s/it]

 73%|███████▎  | 445/613 [08:33<03:14,  1.16s/it]

 73%|███████▎  | 446/613 [08:34<03:13,  1.16s/it]

 73%|███████▎  | 447/613 [08:35<03:12,  1.16s/it]

 73%|███████▎  | 448/613 [08:36<03:11,  1.16s/it]

 73%|███████▎  | 449/613 [08:38<03:09,  1.16s/it]

 73%|███████▎  | 450/613 [08:39<03:08,  1.16s/it]

 74%|███████▎  | 451/613 [08:40<03:07,  1.16s/it]

 74%|███████▎  | 452/613 [08:41<03:06,  1.16s/it]

 74%|███████▍  | 453/613 [08:42<03:05,  1.16s/it]

 74%|███████▍  | 454/613 [08:43<03:04,  1.16s/it]

 74%|███████▍  | 455/613 [08:45<03:03,  1.16s/it]

 74%|███████▍  | 456/613 [08:46<03:02,  1.16s/it]

 75%|███████▍  | 457/613 [08:47<03:01,  1.16s/it]

 75%|███████▍  | 458/613 [08:48<02:59,  1.16s/it]

 75%|███████▍  | 459/613 [08:49<02:58,  1.16s/it]

 75%|███████▌  | 460/613 [08:50<02:57,  1.16s/it]

 75%|███████▌  | 461/613 [08:51<02:56,  1.16s/it]

 75%|███████▌  | 462/613 [08:53<02:55,  1.16s/it]

 76%|███████▌  | 463/613 [08:54<02:54,  1.16s/it]

 76%|███████▌  | 464/613 [08:55<02:52,  1.16s/it]

 76%|███████▌  | 465/613 [08:56<02:51,  1.16s/it]

 76%|███████▌  | 466/613 [08:57<02:50,  1.16s/it]

 76%|███████▌  | 467/613 [08:58<02:49,  1.16s/it]

 76%|███████▋  | 468/613 [09:00<02:48,  1.16s/it]

 77%|███████▋  | 469/613 [09:01<02:47,  1.16s/it]

 77%|███████▋  | 470/613 [09:02<02:45,  1.16s/it]

 77%|███████▋  | 471/613 [09:03<02:44,  1.16s/it]

 77%|███████▋  | 472/613 [09:04<02:43,  1.16s/it]

 77%|███████▋  | 473/613 [09:05<02:42,  1.16s/it]

 77%|███████▋  | 474/613 [09:07<02:41,  1.16s/it]

 77%|███████▋  | 475/613 [09:08<02:40,  1.16s/it]

 78%|███████▊  | 476/613 [09:09<02:38,  1.16s/it]

 78%|███████▊  | 477/613 [09:10<02:37,  1.16s/it]

 78%|███████▊  | 478/613 [09:11<02:36,  1.16s/it]

 78%|███████▊  | 479/613 [09:12<02:35,  1.16s/it]

 78%|███████▊  | 480/613 [09:14<02:34,  1.16s/it]

 78%|███████▊  | 481/613 [09:15<02:33,  1.16s/it]

 79%|███████▊  | 482/613 [09:16<02:31,  1.16s/it]

 79%|███████▉  | 483/613 [09:17<02:30,  1.16s/it]

 79%|███████▉  | 484/613 [09:18<02:29,  1.16s/it]

 79%|███████▉  | 485/613 [09:19<02:28,  1.16s/it]

 79%|███████▉  | 486/613 [09:20<02:27,  1.16s/it]

 79%|███████▉  | 487/613 [09:22<02:26,  1.16s/it]

 80%|███████▉  | 488/613 [09:23<02:25,  1.16s/it]

 80%|███████▉  | 489/613 [09:24<02:24,  1.16s/it]

 80%|███████▉  | 490/613 [09:25<02:22,  1.16s/it]

 80%|████████  | 491/613 [09:26<02:21,  1.16s/it]

 80%|████████  | 492/613 [09:27<02:20,  1.16s/it]

 80%|████████  | 493/613 [09:29<02:19,  1.16s/it]

 81%|████████  | 494/613 [09:30<02:18,  1.16s/it]

 81%|████████  | 495/613 [09:31<02:16,  1.16s/it]

 81%|████████  | 496/613 [09:32<02:15,  1.16s/it]

 81%|████████  | 497/613 [09:33<02:14,  1.16s/it]

 81%|████████  | 498/613 [09:34<02:13,  1.16s/it]

 81%|████████▏ | 499/613 [09:36<02:12,  1.16s/it]

 82%|████████▏ | 500/613 [09:37<02:11,  1.16s/it]

 82%|████████▏ | 501/613 [09:38<02:10,  1.16s/it]

 82%|████████▏ | 502/613 [09:39<02:08,  1.16s/it]

 82%|████████▏ | 503/613 [09:40<02:07,  1.16s/it]

 82%|████████▏ | 504/613 [09:41<02:06,  1.16s/it]

 82%|████████▏ | 505/613 [09:43<02:05,  1.16s/it]

 83%|████████▎ | 506/613 [09:44<02:04,  1.16s/it]

 83%|████████▎ | 507/613 [09:45<02:03,  1.16s/it]

 83%|████████▎ | 508/613 [09:46<02:02,  1.16s/it]

 83%|████████▎ | 509/613 [09:47<02:00,  1.16s/it]

 83%|████████▎ | 510/613 [09:48<01:59,  1.16s/it]

 83%|████████▎ | 511/613 [09:49<01:58,  1.16s/it]

 84%|████████▎ | 512/613 [09:51<01:57,  1.16s/it]

 84%|████████▎ | 513/613 [09:52<01:55,  1.16s/it]

 84%|████████▍ | 514/613 [09:53<01:54,  1.16s/it]

 84%|████████▍ | 515/613 [09:54<01:53,  1.16s/it]

 84%|████████▍ | 516/613 [09:55<01:52,  1.16s/it]

 84%|████████▍ | 517/613 [09:56<01:51,  1.16s/it]

 85%|████████▍ | 518/613 [09:58<01:50,  1.16s/it]

 85%|████████▍ | 519/613 [09:59<01:49,  1.16s/it]

 85%|████████▍ | 520/613 [10:00<01:47,  1.16s/it]

 85%|████████▍ | 521/613 [10:01<01:46,  1.16s/it]

 85%|████████▌ | 522/613 [10:02<01:45,  1.16s/it]

 85%|████████▌ | 523/613 [10:03<01:44,  1.16s/it]

 85%|████████▌ | 524/613 [10:05<01:43,  1.16s/it]

 86%|████████▌ | 525/613 [10:06<01:41,  1.16s/it]

 86%|████████▌ | 526/613 [10:07<01:40,  1.16s/it]

 86%|████████▌ | 527/613 [10:08<01:39,  1.16s/it]

 86%|████████▌ | 528/613 [10:09<01:38,  1.16s/it]

 86%|████████▋ | 529/613 [10:10<01:37,  1.16s/it]

 86%|████████▋ | 530/613 [10:12<01:36,  1.16s/it]

 87%|████████▋ | 531/613 [10:13<01:35,  1.16s/it]

 87%|████████▋ | 532/613 [10:14<01:33,  1.16s/it]

 87%|████████▋ | 533/613 [10:15<01:32,  1.16s/it]

 87%|████████▋ | 534/613 [10:16<01:31,  1.16s/it]

 87%|████████▋ | 535/613 [10:17<01:30,  1.16s/it]

 87%|████████▋ | 536/613 [10:18<01:29,  1.16s/it]

 88%|████████▊ | 537/613 [10:20<01:28,  1.16s/it]

 88%|████████▊ | 538/613 [10:21<01:26,  1.16s/it]

 88%|████████▊ | 539/613 [10:22<01:25,  1.16s/it]

 88%|████████▊ | 540/613 [10:23<01:24,  1.16s/it]

 88%|████████▊ | 541/613 [10:24<01:23,  1.16s/it]

 88%|████████▊ | 542/613 [10:25<01:22,  1.16s/it]

 89%|████████▊ | 543/613 [10:27<01:21,  1.16s/it]

 89%|████████▊ | 544/613 [10:28<01:19,  1.16s/it]

 89%|████████▉ | 545/613 [10:29<01:18,  1.16s/it]

 89%|████████▉ | 546/613 [10:30<01:17,  1.16s/it]

 89%|████████▉ | 547/613 [10:31<01:16,  1.16s/it]

 89%|████████▉ | 548/613 [10:32<01:15,  1.16s/it]

 90%|████████▉ | 549/613 [10:34<01:14,  1.16s/it]

 90%|████████▉ | 550/613 [10:35<01:13,  1.16s/it]

 90%|████████▉ | 551/613 [10:36<01:11,  1.16s/it]

 90%|█████████ | 552/613 [10:37<01:10,  1.16s/it]

 90%|█████████ | 553/613 [10:38<01:09,  1.16s/it]

 90%|█████████ | 554/613 [10:39<01:08,  1.16s/it]

 91%|█████████ | 555/613 [10:41<01:07,  1.16s/it]

 91%|█████████ | 556/613 [10:42<01:06,  1.16s/it]

 91%|█████████ | 557/613 [10:43<01:04,  1.16s/it]

 91%|█████████ | 558/613 [10:44<01:03,  1.16s/it]

 91%|█████████ | 559/613 [10:45<01:02,  1.16s/it]

 91%|█████████▏| 560/613 [10:46<01:01,  1.16s/it]

 92%|█████████▏| 561/613 [10:47<01:00,  1.16s/it]

 92%|█████████▏| 562/613 [10:49<00:59,  1.16s/it]

 92%|█████████▏| 563/613 [10:50<00:58,  1.16s/it]

 92%|█████████▏| 564/613 [10:51<00:56,  1.16s/it]

 92%|█████████▏| 565/613 [10:52<00:55,  1.16s/it]

 92%|█████████▏| 566/613 [10:53<00:54,  1.16s/it]

 92%|█████████▏| 567/613 [10:54<00:53,  1.16s/it]

 93%|█████████▎| 568/613 [10:56<00:52,  1.16s/it]

 93%|█████████▎| 569/613 [10:57<00:51,  1.16s/it]

 93%|█████████▎| 570/613 [10:58<00:49,  1.16s/it]

 93%|█████████▎| 571/613 [10:59<00:48,  1.16s/it]

 93%|█████████▎| 572/613 [11:00<00:47,  1.16s/it]

 93%|█████████▎| 573/613 [11:01<00:46,  1.16s/it]

 94%|█████████▎| 574/613 [11:03<00:45,  1.16s/it]

 94%|█████████▍| 575/613 [11:04<00:44,  1.16s/it]

 94%|█████████▍| 576/613 [11:05<00:43,  1.16s/it]

 94%|█████████▍| 577/613 [11:06<00:41,  1.16s/it]

 94%|█████████▍| 578/613 [11:07<00:40,  1.16s/it]

 94%|█████████▍| 579/613 [11:08<00:39,  1.16s/it]

 95%|█████████▍| 580/613 [11:10<00:38,  1.16s/it]

 95%|█████████▍| 581/613 [11:11<00:37,  1.16s/it]

 95%|█████████▍| 582/613 [11:12<00:36,  1.16s/it]

 95%|█████████▌| 583/613 [11:13<00:34,  1.16s/it]

 95%|█████████▌| 584/613 [11:14<00:33,  1.16s/it]

 95%|█████████▌| 585/613 [11:15<00:32,  1.16s/it]

 96%|█████████▌| 586/613 [11:17<00:31,  1.16s/it]

 96%|█████████▌| 587/613 [11:18<00:30,  1.16s/it]

 96%|█████████▌| 588/613 [11:19<00:29,  1.16s/it]

 96%|█████████▌| 589/613 [11:20<00:27,  1.16s/it]

 96%|█████████▌| 590/613 [11:21<00:26,  1.16s/it]

 96%|█████████▋| 591/613 [11:22<00:25,  1.16s/it]

 97%|█████████▋| 592/613 [11:23<00:24,  1.16s/it]

 97%|█████████▋| 593/613 [11:25<00:23,  1.16s/it]

 97%|█████████▋| 594/613 [11:26<00:22,  1.16s/it]

 97%|█████████▋| 595/613 [11:27<00:20,  1.16s/it]

 97%|█████████▋| 596/613 [11:28<00:19,  1.16s/it]

 97%|█████████▋| 597/613 [11:29<00:18,  1.16s/it]

 98%|█████████▊| 598/613 [11:30<00:17,  1.16s/it]

 98%|█████████▊| 599/613 [11:32<00:16,  1.16s/it]

 98%|█████████▊| 600/613 [11:33<00:15,  1.16s/it]

 98%|█████████▊| 601/613 [11:34<00:13,  1.16s/it]

 98%|█████████▊| 602/613 [11:35<00:12,  1.16s/it]

 98%|█████████▊| 603/613 [11:36<00:11,  1.16s/it]

 99%|█████████▊| 604/613 [11:37<00:10,  1.16s/it]

 99%|█████████▊| 605/613 [11:39<00:09,  1.16s/it]

 99%|█████████▉| 606/613 [11:40<00:08,  1.16s/it]

 99%|█████████▉| 607/613 [11:41<00:06,  1.16s/it]

 99%|█████████▉| 608/613 [11:42<00:05,  1.16s/it]

 99%|█████████▉| 609/613 [11:43<00:04,  1.16s/it]

100%|█████████▉| 610/613 [11:44<00:03,  1.16s/it]

100%|█████████▉| 611/613 [11:46<00:02,  1.16s/it]

100%|█████████▉| 612/613 [11:47<00:01,  1.16s/it]

100%|██████████| 613/613 [11:47<00:00,  1.14it/s]

100%|██████████| 613/613 [11:47<00:00,  1.15s/it]

logging the anndata
AnnData object with n_obs × n_vars = 39176 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

too few cells to embed into a umap
too few cells to compute a clustering

PairwiseArrays with keys: connectivities, distances

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.919583  -13.540295  -13.518924  ... -13.595631  -13.912533
 -13.6789465]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.635503 -14.214784 -14.216818 ... -14.194136 -14.580806 -14.255302]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.034133 -12.728455 -12.419679 ... -12.607303 -12.621627 -12.901445]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.972907  -13.662628  -13.640425  ... -13.592228  -13.789477
 -13.7406025]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.305216  -12.976042  -12.772959  ... -12.865369  -12.8902645
 -13.149022 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.583794 -14.166039 -14.159821 ... -14.142267 -14.533628 -14.211736]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.8427105 -14.503536  -14.4822445 ... -14.52371   -14.830965
 -14.550227 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.139357 -16.106964 -16.336588 ... -15.930022 -15.875849 -15.864525]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.408361 -17.571665 -17.839312 ... -17.2725   -17.058626 -17.173191]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.692895 -15.13227  -15.421338 ... -14.730698 -15.147544 -14.956182]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.707977 -12.453294 -11.966597 ... -12.551676 -11.837022 -12.814546]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.160029 -11.675887 -11.700757 ... -12.165213 -11.486928 -12.100153]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.305541  -8.04607   -7.6640844 ... -7.8317537 -8.019724  -7.9901466]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.205995  -7.8121586 -7.7843823 ... -7.6147857 -7.9373326 -7.6005073]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.0493765 -13.644092  -13.623694  ... -13.6666155 -14.015474
 -13.747146 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.9103827 -6.8107967 -6.8859773 ... -6.719709  -6.786995  -6.882451 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.885571 -10.410029 -10.255995 ... -10.877157 -10.836493 -11.618417]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.662681 -12.31206  -12.430369 ... -12.836156 -12.608841 -13.218209]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.9345376 -4.7442327 -5.590227  ... -5.2098956 -4.351493  -4.822701 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.377447 -13.88257  -13.767546 ... -13.901062 -14.343498 -13.963571]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.3080187 -6.4281316 -5.8976774 ... -6.561456  -7.2308626 -6.816121 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.011332 -13.611204 -13.587202 ... -13.637689 -13.984268 -13.720446]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.9736304 -5.9080753 -5.436384  ... -5.8272324 -6.0417657 -5.8094816]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.745066 -11.070003 -10.788039 ... -10.920352 -11.510928 -10.75648 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.695064  -6.740504  -6.258753  ... -6.3823094 -7.3873224 -6.3633537]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.95344  -13.544895 -13.491926 ... -13.512881 -13.884569 -13.549025]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.7400894 -4.354454  -4.3090067 ... -4.3857155 -4.659718  -4.4497576]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.8773837 -4.3757796 -4.174076  ... -4.3346796 -4.709349  -4.495114 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.2224917 -4.685657  -4.437651  ... -4.590866  -5.0137706 -4.734278 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.452261  -8.287117  -7.8506002 ... -7.939783  -9.009653  -8.171405 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.694525  -9.754603  -9.445967  ... -9.718983  -9.625735  -9.7448845]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.598768 -9.638205 -9.536411 ... -9.673109 -9.461165 -9.761586]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.397115 -9.392111 -9.282448 ... -9.409902 -9.231549 -9.528902]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.291404 -13.910576 -13.888615 ... -13.932684 -14.238485 -14.051657]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.014286  -7.9204454 -7.575684  ... -7.6077895 -8.469435  -7.909361 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.4491587 -5.276096  -5.2369    ... -4.6468806 -5.6576242 -4.5198245]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.233922  -4.712362  -4.2128325 ... -4.48032   -4.969888  -4.7667317]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.7582664 -7.7233157 -7.492503  ... -7.9466157 -7.7977743 -8.07222  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.511666 -10.8259   -11.078482 ... -10.754593 -10.4714   -10.213257]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.052636  -6.878938  -6.3626637 ... -6.9073873 -6.9049616 -7.0506587]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.677391  -14.4079895 -14.444743  ... -14.419384  -14.6773815
 -14.447021 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.859512  -8.6291275 -8.200068  ... -8.293114  -9.422911  -8.48662  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.504347  -13.4255705 -12.998536  ... -13.428329  -13.455265
 -13.82484  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.897065 -8.788582 -8.376957 ... -8.870974 -8.996687 -8.844286]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.591175 -10.108804 -10.225462 ... -10.148075 -10.478293 -10.348489]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.846039 -13.535819 -13.591576 ... -13.691321 -13.835604 -13.851129]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.545568  -14.148888  -14.154837  ... -14.136428  -14.4990635
 -14.195863 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.752313  -6.3441787 -5.91462   ... -6.1457477 -6.5265985 -6.2166204]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.3408613 -5.999253  -5.573597  ... -5.6958017 -6.101958  -5.748249 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.261278  -9.771651  -9.264643 ...  -9.907218 -10.311237 -10.006995]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.298739  -13.9221945 -13.921922  ... -13.926016  -14.266611
 -13.99499  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.9781213 -6.5510006 -6.126908  ... -6.2234254 -6.710857  -6.2902994]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.559172 -14.154563 -14.156708 ... -14.141148 -14.509891 -14.196641]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.976155  -6.5527005 -6.13363   ... -6.2211437 -6.7064652 -6.2896376]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.9040694 -6.2993155 -5.919592  ... -6.077529  -6.6330705 -6.1854672]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.1318016 -5.595764  -5.330617  ... -5.4817195 -5.9138527 -5.5898952]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.513635 -14.095731 -14.054366 ... -14.054641 -14.447202 -14.102882]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.576918  -5.1598425 -4.817669  ... -4.849992  -5.2706738 -4.909083 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.529867 -14.113211 -14.074123 ... -14.073547 -14.468912 -14.128833]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.548405 -14.137708 -14.098484 ... -14.101183 -14.492006 -14.151373]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.241567 -5.81952  -5.409891 ... -5.663344 -6.000168 -5.791406]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.973087  -10.577561  -10.334683  ... -10.77855   -10.9384985
 -10.96441  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.213447  -13.8037195 -13.682579  ... -13.721936  -14.12392
 -13.758841 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.4569783 -6.751996  -6.2396145 ... -6.480886  -7.218456  -6.5168014]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.427925  -5.763238  -5.3120403 ... -5.4724627 -6.165427  -5.5766034]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.9341702 -3.1135204 -2.8001587 ... -2.7163534 -3.4605057 -2.721135 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.58035  -7.926686 -7.695902 ... -8.106747 -7.787703 -8.105574]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.861652  -11.6634245 -11.488428  ... -11.744356  -11.819306
 -11.716735 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.590352  -9.716665  -9.377361 ...  -9.491758 -10.311584  -9.568014]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.549007  -8.11656   -8.266916  ... -8.18764   -8.3151655 -8.175324 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.552464  -12.948497  -12.033217  ... -13.2017975 -13.612456
 -13.709435 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.631875 -14.201025 -14.197123 ... -14.175558 -14.579836 -14.242444]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.195506 -10.594174 -10.85314  ... -10.480391 -10.15509  -10.261298]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.1966095 -9.308226  -9.415082  ... -9.434401  -9.314309  -9.334251 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.682012 -9.500611 -9.292059 ... -9.658443 -9.717841 -9.859273]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.8717732 -8.110406  -7.868744  ... -8.319516  -8.066135  -8.327909 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.547548  -12.093125  -11.74503   ... -11.967997  -12.3839655
 -12.102441 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.42942   -7.1464934 -6.7342405 ... -6.839354  -7.1823044 -6.888919 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.393491  -9.885495  -9.313056 ...  -9.9657   -10.408443 -10.095404]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.652048 -14.22859  -14.221841 ... -14.202351 -14.596293 -14.268215]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.692981 -8.472084 -8.38918  ... -8.384651 -8.682119 -8.485593]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.095633 -13.741636 -13.703672 ... -13.764484 -14.083051 -13.799552]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.14034  -12.117187 -12.221011 ... -12.552964 -12.354551 -12.459997]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.347363 -8.030941 -8.224799 ... -7.981851 -8.237126 -7.91218 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.3945403 -7.039838  -7.120591  ... -6.95829   -7.3600082 -6.905809 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.549582 -12.35555  -12.480024 ... -12.509157 -12.574136 -12.374583]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.451251 -10.232009 -10.506489 ... -10.335265 -10.481667 -10.204933]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.009781 -12.817503 -12.386492 ... -13.191179 -13.36865  -13.259768]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.43351  -14.008395 -14.005257 ... -14.014115 -14.38641  -14.090154]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.027405 -8.118089 -8.218327 ... -8.126963 -8.061204 -8.013101]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.038362 -10.425959 -10.419348 ... -10.167952 -10.813133 -10.374026]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.235149  -9.167427  -9.370223 ...  -9.638867  -9.611793 -10.035191]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.382318  -7.0427217 -7.182862  ... -7.046961  -7.298401  -6.9949203]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.353205  -6.0577254 -6.183857  ... -6.035683  -6.3274255 -5.9413676]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.893826 -14.863061 -14.601535 ... -15.083905 -15.13733  -14.914435]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.220595 -13.998497 -13.849591 ... -14.116555 -14.328834 -14.089781]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.8085837 -6.2745337 -5.833122  ... -6.639847  -6.0034204 -6.7197886]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.511416  -11.888741  -11.798798  ... -11.712046  -12.3067665
 -11.835357 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.149432  -4.6806097 -4.3116026 ... -4.3045588 -4.811465  -4.324394 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.4669075 -4.6830077 -4.2683687 ... -4.2625384 -5.094543  -4.3441567]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.41516  -10.414867 -10.103202 ... -10.159332 -11.090595 -10.301077]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.116147 -10.076949  -9.742716 ...  -9.810225 -10.771542  -9.952759]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.5240006 -4.083171  -3.77279   ... -3.7244115 -4.152952  -3.594827 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.768511 -12.263613 -12.119157 ... -12.150351 -12.618348 -12.161568]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.86009   -4.4501963 -4.182398  ... -4.0868597 -4.4885597 -3.8848426]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.503499  -7.269944  -6.7280965 ... -6.8372016 -8.063189  -7.1581335]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.3411913 -4.509548  -3.9868376 ... -4.1239905 -4.9835334 -4.292257 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.873085 -12.880657 -12.404491 ... -13.112195 -13.879818 -13.326194]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.5995946 -6.183675  -5.7522016 ... -5.979505  -6.3746047 -6.040997 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.812293  -9.937406  -9.523383 ... -10.005222 -10.480921 -10.678672]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.174869  -13.817715  -13.840793  ... -13.8464365 -14.140536
 -13.870665 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.3089166 -6.89764   -6.4743314 ... -6.7011185 -7.093863  -6.7497396]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.552214  -5.5876756 -5.359049  ... -5.5127683 -6.2442117 -5.7911196]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.6549582 -6.3080773 -6.010126  ... -6.445995  -6.4353204 -6.7240524]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.3356466 -5.9708796 -6.1266603 ... -6.044147  -5.488818  -5.7908816]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.434661  -14.12322   -13.899364  ... -14.2752695 -14.553448
 -14.226067 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.092722  -5.5908375 -5.054181  ... -5.3707905 -5.8879952 -5.6030173]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.300764  -5.886008  -5.455254  ... -5.6852765 -6.0762544 -5.759641 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.398635 -12.946765 -12.879442 ... -12.928345 -13.293906 -12.996508]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.9918823 -7.645891  -7.1014023 ... -7.686259  -8.10592   -7.9578986]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.3764195 -6.6231074 -6.7252026 ... -6.885977  -6.5551596 -6.6903305]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.733007 -12.292886 -12.098069 ... -12.264239 -12.621237 -12.433333]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.4751453 -7.0642056 -6.644172  ... -6.860317  -7.2603893 -6.9149404]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.050997  -6.064922  -6.136941  ... -6.1906357 -6.133413  -5.904273 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.3456756 1.6110475 1.5898155 ... 1.5069616 1.4202374 1.7653533]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.7384582 -1.7903141 -1.7567986 ... -1.7553117 -2.3507042 -1.9231249]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.62491  -8.247897 -7.817999 ... -8.031718 -8.398186 -8.097349]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.6354156 -4.0994396 -3.5736103 ... -4.0242834 -4.5683703 -4.0995927]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.244907 -13.815354 -13.762592 ... -13.797135 -14.18935  -13.868459]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.624233  -5.116936  -4.6108694 ... -5.0378165 -5.5456295 -5.1195745]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.842372  -5.3505244 -4.8607063 ... -5.2639146 -5.7525826 -5.3319254]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.882266  -4.968717  -4.7969284 ... -4.8739295 -5.5950603 -4.994184 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.6508217  -0.8594111  -0.6340947  ... -0.77366686 -1.3761687
 -0.9783805 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.866664 -9.401119 -9.314699 ... -9.391556 -9.72221  -9.37513 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.2157993 -4.62156   -4.250086  ... -4.4498596 -4.9621167 -4.5924225]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.651123 -11.352095 -11.227298 ... -11.367167 -11.577204 -11.421037]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.6582403 -5.157629  -4.639289  ... -5.08346   -5.5828753 -5.158354 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.7815933 -7.443865  -6.9949317 ... -7.654868  -7.9998665 -7.855288 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.008306  -6.6501737 -6.219413  ... -6.4466867 -6.8158636 -6.4862213]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.331254  -5.9092875 -5.470458  ... -5.695899  -6.1023903 -5.757393 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.8792757  -0.49774384 -0.3234509  ... -0.35822335 -1.3972577
 -0.6786624 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.992155  -4.903601  -4.4529777 ... -4.469027  -5.6108837 -4.7547174]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

PairwiseArrays with keys: connectivities, distances

{'cellxgene_census/dkd_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3432203389830508, 'macro': 0.25917444685094343, 'micro': 0.3432203389830508, 'weighted': 0.34017252137470233}}, 'cellxgene_census/dkd_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3550587343690792, 'macro': 0.27207633588309094, 'micro': 0.3550587343690792, 'weighted': 0.3524031871669568}}, 'cellxgene_census/dkd_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3561955286093217, 'macro': 0.2740563641826558, 'micro': 0.3561955286093217, 'weighted': 0.3538971563453317}}, 'cellxgene_census/dkd_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.361121636983706, 'macro': 0.2857142857142857, 'micro': 0.361121636983706, 'weighted': 0.361121636983706}}}
doing  cellxgene_census/gtex_v9

/lustre/fswork/projects/rech/xeg/uat95fg/scdataloader/scdataloader/utils.py:427: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  organismdf = pd.concat(organismdf)

predict epoch start

  0%|          | 0/3268 [00:00<?, ?it/s]

  0%|          | 1/3268 [00:04<4:27:51,  4.92s/it]

  0%|          | 2/3268 [00:06<2:26:35,  2.69s/it]

  0%|          | 3/3268 [00:07<1:47:35,  1.98s/it]

  0%|          | 4/3268 [00:08<1:29:17,  1.64s/it]

  0%|          | 5/3268 [00:09<1:19:10,  1.46s/it]

  0%|          | 6/3268 [00:10<1:13:05,  1.34s/it]

  0%|          | 7/3268 [00:11<1:09:12,  1.27s/it]

  0%|          | 8/3268 [00:12<1:06:45,  1.23s/it]

  0%|          | 9/3268 [00:13<1:05:10,  1.20s/it]

  0%|          | 10/3268 [00:15<1:04:03,  1.18s/it]

  0%|          | 11/3268 [00:16<1:03:17,  1.17s/it]

  0%|          | 12/3268 [00:17<1:02:41,  1.16s/it]

  0%|          | 13/3268 [00:18<1:02:13,  1.15s/it]

  0%|          | 14/3268 [00:19<1:01:56,  1.14s/it]

  0%|          | 15/3268 [00:20<1:01:44,  1.14s/it]

  0%|          | 16/3268 [00:21<1:01:35,  1.14s/it]

  1%|          | 17/3268 [00:23<1:01:30,  1.14s/it]

  1%|          | 18/3268 [00:24<1:01:24,  1.13s/it]

  1%|          | 19/3268 [00:25<1:01:21,  1.13s/it]

  1%|          | 20/3268 [00:26<1:01:20,  1.13s/it]

  1%|          | 21/3268 [00:27<1:01:20,  1.13s/it]

  1%|          | 22/3268 [00:28<1:01:20,  1.13s/it]

  1%|          | 23/3268 [00:29<1:01:18,  1.13s/it]

  1%|          | 24/3268 [00:30<1:01:15,  1.13s/it]

  1%|          | 25/3268 [00:32<1:01:16,  1.13s/it]

  1%|          | 26/3268 [00:33<1:01:19,  1.13s/it]

  1%|          | 27/3268 [00:34<1:01:14,  1.13s/it]

  1%|          | 28/3268 [00:35<1:01:12,  1.13s/it]

  1%|          | 29/3268 [00:36<1:01:10,  1.13s/it]

  1%|          | 30/3268 [00:37<1:01:10,  1.13s/it]

  1%|          | 31/3268 [00:38<1:01:12,  1.13s/it]

  1%|          | 32/3268 [00:40<1:01:10,  1.13s/it]

  1%|          | 33/3268 [00:41<1:01:10,  1.13s/it]

  1%|          | 34/3268 [00:42<1:01:08,  1.13s/it]

  1%|          | 35/3268 [00:43<1:01:09,  1.14s/it]

  1%|          | 36/3268 [00:44<1:01:09,  1.14s/it]

  1%|          | 37/3268 [00:45<1:01:09,  1.14s/it]

  1%|          | 38/3268 [00:46<1:01:09,  1.14s/it]

  1%|          | 39/3268 [00:47<1:01:09,  1.14s/it]

  1%|          | 40/3268 [00:49<1:01:06,  1.14s/it]

  1%|▏         | 41/3268 [00:50<1:01:03,  1.14s/it]

  1%|▏         | 42/3268 [00:51<1:01:01,  1.13s/it]

  1%|▏         | 43/3268 [00:52<1:01:04,  1.14s/it]

  1%|▏         | 44/3268 [00:53<1:01:04,  1.14s/it]

  1%|▏         | 45/3268 [00:54<1:01:03,  1.14s/it]

  1%|▏         | 46/3268 [00:55<1:01:02,  1.14s/it]

  1%|▏         | 47/3268 [00:57<1:01:04,  1.14s/it]

  1%|▏         | 48/3268 [00:58<1:01:03,  1.14s/it]

  1%|▏         | 49/3268 [00:59<1:00:59,  1.14s/it]

  2%|▏         | 50/3268 [01:00<1:00:58,  1.14s/it]

  2%|▏         | 51/3268 [01:01<1:00:58,  1.14s/it]

  2%|▏         | 52/3268 [01:02<1:01:01,  1.14s/it]

  2%|▏         | 53/3268 [01:03<1:00:58,  1.14s/it]

  2%|▏         | 54/3268 [01:05<1:00:57,  1.14s/it]

  2%|▏         | 55/3268 [01:06<1:00:58,  1.14s/it]

  2%|▏         | 56/3268 [01:07<1:00:58,  1.14s/it]

  2%|▏         | 57/3268 [01:08<1:01:00,  1.14s/it]

  2%|▏         | 58/3268 [01:09<1:01:00,  1.14s/it]

  2%|▏         | 59/3268 [01:10<1:00:59,  1.14s/it]

  2%|▏         | 60/3268 [01:11<1:00:55,  1.14s/it]

  2%|▏         | 61/3268 [01:13<1:00:53,  1.14s/it]

  2%|▏         | 62/3268 [01:14<1:00:53,  1.14s/it]

  2%|▏         | 63/3268 [01:15<1:00:52,  1.14s/it]

  2%|▏         | 64/3268 [01:16<1:00:50,  1.14s/it]

  2%|▏         | 65/3268 [01:17<1:00:49,  1.14s/it]

  2%|▏         | 66/3268 [01:18<1:00:47,  1.14s/it]

  2%|▏         | 67/3268 [01:19<1:00:48,  1.14s/it]

  2%|▏         | 68/3268 [01:20<1:00:53,  1.14s/it]

  2%|▏         | 69/3268 [01:22<1:00:49,  1.14s/it]

  2%|▏         | 70/3268 [01:23<1:00:52,  1.14s/it]

  2%|▏         | 71/3268 [01:24<1:00:48,  1.14s/it]

  2%|▏         | 72/3268 [01:25<1:00:44,  1.14s/it]

  2%|▏         | 73/3268 [01:26<1:00:41,  1.14s/it]

  2%|▏         | 74/3268 [01:27<1:00:42,  1.14s/it]

  2%|▏         | 75/3268 [01:28<1:00:41,  1.14s/it]

  2%|▏         | 76/3268 [01:30<1:00:38,  1.14s/it]

  2%|▏         | 77/3268 [01:31<1:00:39,  1.14s/it]

  2%|▏         | 78/3268 [01:32<1:00:38,  1.14s/it]

  2%|▏         | 79/3268 [01:33<1:00:36,  1.14s/it]

  2%|▏         | 80/3268 [01:34<1:00:32,  1.14s/it]

  2%|▏         | 81/3268 [01:35<1:00:33,  1.14s/it]

  3%|▎         | 82/3268 [01:36<1:00:34,  1.14s/it]

  3%|▎         | 83/3268 [01:38<1:00:36,  1.14s/it]

  3%|▎         | 84/3268 [01:39<1:00:38,  1.14s/it]

  3%|▎         | 85/3268 [01:40<1:00:38,  1.14s/it]

  3%|▎         | 86/3268 [01:41<1:00:36,  1.14s/it]

  3%|▎         | 87/3268 [01:42<1:00:33,  1.14s/it]

  3%|▎         | 88/3268 [01:43<1:00:31,  1.14s/it]

  3%|▎         | 89/3268 [01:44<1:00:33,  1.14s/it]

  3%|▎         | 90/3268 [01:46<1:00:31,  1.14s/it]

  3%|▎         | 91/3268 [01:47<1:00:31,  1.14s/it]

  3%|▎         | 92/3268 [01:48<1:00:29,  1.14s/it]

  3%|▎         | 93/3268 [01:49<1:00:30,  1.14s/it]

  3%|▎         | 94/3268 [01:50<1:00:27,  1.14s/it]

  3%|▎         | 95/3268 [01:51<1:00:24,  1.14s/it]

  3%|▎         | 96/3268 [01:52<1:00:23,  1.14s/it]

  3%|▎         | 97/3268 [01:54<1:00:25,  1.14s/it]

  3%|▎         | 98/3268 [01:55<1:00:24,  1.14s/it]

  3%|▎         | 99/3268 [01:56<1:00:25,  1.14s/it]

  3%|▎         | 100/3268 [01:57<1:00:23,  1.14s/it]

  3%|▎         | 101/3268 [01:58<1:00:21,  1.14s/it]

  3%|▎         | 102/3268 [01:59<1:00:18,  1.14s/it]

  3%|▎         | 103/3268 [02:00<1:00:17,  1.14s/it]

  3%|▎         | 104/3268 [02:02<1:00:16,  1.14s/it]

  3%|▎         | 105/3268 [02:03<1:00:20,  1.14s/it]

  3%|▎         | 106/3268 [02:04<1:00:18,  1.14s/it]

  3%|▎         | 107/3268 [02:05<1:00:15,  1.14s/it]

  3%|▎         | 108/3268 [02:06<1:00:15,  1.14s/it]

  3%|▎         | 109/3268 [02:07<1:00:14,  1.14s/it]

  3%|▎         | 110/3268 [02:08<1:00:11,  1.14s/it]

  3%|▎         | 111/3268 [02:10<1:00:09,  1.14s/it]

  3%|▎         | 112/3268 [02:11<1:00:09,  1.14s/it]

  3%|▎         | 113/3268 [02:12<1:00:07,  1.14s/it]

  3%|▎         | 114/3268 [02:13<1:00:06,  1.14s/it]

  4%|▎         | 115/3268 [02:14<1:00:08,  1.14s/it]

  4%|▎         | 116/3268 [02:15<1:00:10,  1.15s/it]

  4%|▎         | 117/3268 [02:16<1:00:10,  1.15s/it]

  4%|▎         | 118/3268 [02:18<1:00:07,  1.15s/it]

  4%|▎         | 119/3268 [02:19<1:00:08,  1.15s/it]

  4%|▎         | 120/3268 [02:20<1:00:07,  1.15s/it]

  4%|▎         | 121/3268 [02:21<1:00:03,  1.14s/it]

  4%|▎         | 122/3268 [02:22<1:00:03,  1.15s/it]

  4%|▍         | 123/3268 [02:23<1:00:08,  1.15s/it]

  4%|▍         | 124/3268 [02:25<1:00:04,  1.15s/it]

  4%|▍         | 125/3268 [02:26<1:00:02,  1.15s/it]

  4%|▍         | 126/3268 [02:27<1:00:04,  1.15s/it]

  4%|▍         | 127/3268 [02:28<1:00:04,  1.15s/it]

  4%|▍         | 128/3268 [02:29<59:59,  1.15s/it]

  4%|▍         | 129/3268 [02:30<1:00:01,  1.15s/it]

  4%|▍         | 130/3268 [02:31<59:59,  1.15s/it]

  4%|▍         | 131/3268 [02:33<1:00:00,  1.15s/it]

  4%|▍         | 132/3268 [02:34<59:55,  1.15s/it]

  4%|▍         | 133/3268 [02:35<59:53,  1.15s/it]

  4%|▍         | 134/3268 [02:36<59:52,  1.15s/it]

  4%|▍         | 135/3268 [02:37<59:56,  1.15s/it]

  4%|▍         | 136/3268 [02:38<59:52,  1.15s/it]

  4%|▍         | 137/3268 [02:39<59:50,  1.15s/it]

  4%|▍         | 138/3268 [02:41<59:49,  1.15s/it]

  4%|▍         | 139/3268 [02:42<59:48,  1.15s/it]

  4%|▍         | 140/3268 [02:43<59:51,  1.15s/it]

  4%|▍         | 141/3268 [02:44<59:48,  1.15s/it]

  4%|▍         | 142/3268 [02:45<59:46,  1.15s/it]

  4%|▍         | 143/3268 [02:46<59:45,  1.15s/it]

  4%|▍         | 144/3268 [02:47<59:48,  1.15s/it]

  4%|▍         | 145/3268 [02:49<59:48,  1.15s/it]

  4%|▍         | 146/3268 [02:50<59:45,  1.15s/it]

  4%|▍         | 147/3268 [02:51<59:44,  1.15s/it]

  5%|▍         | 148/3268 [02:52<59:42,  1.15s/it]

  5%|▍         | 149/3268 [02:53<59:41,  1.15s/it]

  5%|▍         | 150/3268 [02:54<59:41,  1.15s/it]

  5%|▍         | 151/3268 [02:55<59:35,  1.15s/it]

  5%|▍         | 152/3268 [02:57<59:32,  1.15s/it]

  5%|▍         | 153/3268 [02:58<59:33,  1.15s/it]

  5%|▍         | 154/3268 [02:59<59:33,  1.15s/it]

  5%|▍         | 155/3268 [03:00<59:33,  1.15s/it]

  5%|▍         | 156/3268 [03:01<59:32,  1.15s/it]

  5%|▍         | 157/3268 [03:02<59:30,  1.15s/it]

  5%|▍         | 158/3268 [03:04<59:30,  1.15s/it]

  5%|▍         | 159/3268 [03:05<59:29,  1.15s/it]

  5%|▍         | 160/3268 [03:06<59:31,  1.15s/it]

  5%|▍         | 161/3268 [03:07<59:34,  1.15s/it]

  5%|▍         | 162/3268 [03:08<59:31,  1.15s/it]

  5%|▍         | 163/3268 [03:09<59:34,  1.15s/it]

  5%|▌         | 164/3268 [03:10<59:31,  1.15s/it]

  5%|▌         | 165/3268 [03:12<59:29,  1.15s/it]

  5%|▌         | 166/3268 [03:13<59:27,  1.15s/it]

  5%|▌         | 167/3268 [03:14<59:25,  1.15s/it]

  5%|▌         | 168/3268 [03:15<59:26,  1.15s/it]

  5%|▌         | 169/3268 [03:16<59:24,  1.15s/it]

  5%|▌         | 170/3268 [03:17<59:21,  1.15s/it]

  5%|▌         | 171/3268 [03:18<59:21,  1.15s/it]

  5%|▌         | 172/3268 [03:20<59:21,  1.15s/it]

  5%|▌         | 173/3268 [03:21<59:21,  1.15s/it]

  5%|▌         | 174/3268 [03:22<59:20,  1.15s/it]

  5%|▌         | 175/3268 [03:23<59:19,  1.15s/it]

  5%|▌         | 176/3268 [03:24<59:20,  1.15s/it]

  5%|▌         | 177/3268 [03:25<59:14,  1.15s/it]

  5%|▌         | 178/3268 [03:27<59:13,  1.15s/it]

  5%|▌         | 179/3268 [03:28<59:16,  1.15s/it]

  6%|▌         | 180/3268 [03:29<59:16,  1.15s/it]

  6%|▌         | 181/3268 [03:30<59:16,  1.15s/it]

  6%|▌         | 182/3268 [03:31<59:20,  1.15s/it]

  6%|▌         | 183/3268 [03:32<59:19,  1.15s/it]

  6%|▌         | 184/3268 [03:33<59:13,  1.15s/it]

  6%|▌         | 185/3268 [03:35<59:10,  1.15s/it]

  6%|▌         | 186/3268 [03:36<59:14,  1.15s/it]

  6%|▌         | 187/3268 [03:37<59:14,  1.15s/it]

  6%|▌         | 188/3268 [03:38<59:13,  1.15s/it]

  6%|▌         | 189/3268 [03:39<59:09,  1.15s/it]

  6%|▌         | 190/3268 [03:40<59:07,  1.15s/it]

  6%|▌         | 191/3268 [03:42<59:07,  1.15s/it]

  6%|▌         | 192/3268 [03:43<59:07,  1.15s/it]

  6%|▌         | 193/3268 [03:44<59:03,  1.15s/it]

  6%|▌         | 194/3268 [03:45<59:00,  1.15s/it]

  6%|▌         | 195/3268 [03:46<58:56,  1.15s/it]

  6%|▌         | 196/3268 [03:47<58:56,  1.15s/it]

  6%|▌         | 197/3268 [03:48<58:54,  1.15s/it]

  6%|▌         | 198/3268 [03:50<58:54,  1.15s/it]

  6%|▌         | 199/3268 [03:51<58:54,  1.15s/it]

  6%|▌         | 200/3268 [03:52<58:53,  1.15s/it]

  6%|▌         | 201/3268 [03:53<58:55,  1.15s/it]

  6%|▌         | 202/3268 [03:54<58:51,  1.15s/it]

  6%|▌         | 203/3268 [03:55<58:48,  1.15s/it]

  6%|▌         | 204/3268 [03:56<58:47,  1.15s/it]

  6%|▋         | 205/3268 [03:58<58:48,  1.15s/it]

  6%|▋         | 206/3268 [03:59<58:48,  1.15s/it]

  6%|▋         | 207/3268 [04:00<58:44,  1.15s/it]

  6%|▋         | 208/3268 [04:01<58:48,  1.15s/it]

  6%|▋         | 209/3268 [04:02<58:47,  1.15s/it]

  6%|▋         | 210/3268 [04:03<58:46,  1.15s/it]

  6%|▋         | 211/3268 [04:05<58:43,  1.15s/it]

  6%|▋         | 212/3268 [04:06<58:42,  1.15s/it]

  7%|▋         | 213/3268 [04:07<58:38,  1.15s/it]

  7%|▋         | 214/3268 [04:08<58:39,  1.15s/it]

  7%|▋         | 215/3268 [04:09<58:39,  1.15s/it]

  7%|▋         | 216/3268 [04:10<58:36,  1.15s/it]

  7%|▋         | 217/3268 [04:11<58:36,  1.15s/it]

  7%|▋         | 218/3268 [04:13<58:35,  1.15s/it]

  7%|▋         | 219/3268 [04:14<58:35,  1.15s/it]

  7%|▋         | 220/3268 [04:15<58:38,  1.15s/it]

  7%|▋         | 221/3268 [04:16<58:39,  1.15s/it]

  7%|▋         | 222/3268 [04:17<58:41,  1.16s/it]

  7%|▋         | 223/3268 [04:18<58:36,  1.15s/it]

  7%|▋         | 224/3268 [04:20<58:30,  1.15s/it]

  7%|▋         | 225/3268 [04:21<58:31,  1.15s/it]

  7%|▋         | 226/3268 [04:22<58:29,  1.15s/it]

  7%|▋         | 227/3268 [04:23<58:29,  1.15s/it]

  7%|▋         | 228/3268 [04:24<58:30,  1.15s/it]

  7%|▋         | 229/3268 [04:25<58:26,  1.15s/it]

  7%|▋         | 230/3268 [04:26<58:28,  1.15s/it]

  7%|▋         | 231/3268 [04:28<58:25,  1.15s/it]

  7%|▋         | 232/3268 [04:29<58:26,  1.15s/it]

  7%|▋         | 233/3268 [04:30<58:20,  1.15s/it]

  7%|▋         | 234/3268 [04:31<58:19,  1.15s/it]

  7%|▋         | 235/3268 [04:32<58:19,  1.15s/it]

  7%|▋         | 236/3268 [04:33<58:21,  1.15s/it]

  7%|▋         | 237/3268 [04:35<58:19,  1.15s/it]

  7%|▋         | 238/3268 [04:36<58:21,  1.16s/it]

  7%|▋         | 239/3268 [04:37<58:15,  1.15s/it]

  7%|▋         | 240/3268 [04:38<58:10,  1.15s/it]

  7%|▋         | 241/3268 [04:39<58:12,  1.15s/it]

  7%|▋         | 242/3268 [04:40<58:13,  1.15s/it]

  7%|▋         | 243/3268 [04:41<58:17,  1.16s/it]

  7%|▋         | 244/3268 [04:43<58:18,  1.16s/it]

  7%|▋         | 245/3268 [04:44<58:14,  1.16s/it]

  8%|▊         | 246/3268 [04:45<58:11,  1.16s/it]

  8%|▊         | 247/3268 [04:46<58:10,  1.16s/it]

  8%|▊         | 248/3268 [04:47<58:05,  1.15s/it]

  8%|▊         | 249/3268 [04:48<58:05,  1.15s/it]

  8%|▊         | 250/3268 [04:50<58:05,  1.15s/it]

  8%|▊         | 251/3268 [04:51<58:05,  1.16s/it]

  8%|▊         | 252/3268 [04:52<58:00,  1.15s/it]

  8%|▊         | 253/3268 [04:53<57:59,  1.15s/it]

  8%|▊         | 254/3268 [04:54<57:55,  1.15s/it]

  8%|▊         | 255/3268 [04:55<57:55,  1.15s/it]

  8%|▊         | 256/3268 [04:57<57:54,  1.15s/it]

  8%|▊         | 257/3268 [04:58<57:53,  1.15s/it]

  8%|▊         | 258/3268 [04:59<57:58,  1.16s/it]

  8%|▊         | 259/3268 [05:00<57:55,  1.16s/it]

  8%|▊         | 260/3268 [05:01<57:53,  1.15s/it]

  8%|▊         | 261/3268 [05:02<57:51,  1.15s/it]

  8%|▊         | 262/3268 [05:03<57:46,  1.15s/it]

  8%|▊         | 263/3268 [05:05<57:45,  1.15s/it]

  8%|▊         | 264/3268 [05:06<57:43,  1.15s/it]

  8%|▊         | 265/3268 [05:07<57:46,  1.15s/it]

  8%|▊         | 266/3268 [05:08<57:45,  1.15s/it]

  8%|▊         | 267/3268 [05:09<57:42,  1.15s/it]

  8%|▊         | 268/3268 [05:10<57:39,  1.15s/it]

  8%|▊         | 269/3268 [05:12<57:41,  1.15s/it]

  8%|▊         | 270/3268 [05:13<57:42,  1.15s/it]

  8%|▊         | 271/3268 [05:14<57:41,  1.15s/it]

  8%|▊         | 272/3268 [05:15<57:41,  1.16s/it]

  8%|▊         | 273/3268 [05:16<57:38,  1.15s/it]

  8%|▊         | 274/3268 [05:17<57:41,  1.16s/it]

  8%|▊         | 275/3268 [05:18<57:38,  1.16s/it]

  8%|▊         | 276/3268 [05:20<57:36,  1.16s/it]

  8%|▊         | 277/3268 [05:21<57:34,  1.15s/it]

  9%|▊         | 278/3268 [05:22<57:32,  1.15s/it]

  9%|▊         | 279/3268 [05:23<57:34,  1.16s/it]

  9%|▊         | 280/3268 [05:24<57:32,  1.16s/it]

  9%|▊         | 281/3268 [05:25<57:32,  1.16s/it]

  9%|▊         | 282/3268 [05:27<57:31,  1.16s/it]

  9%|▊         | 283/3268 [05:28<57:30,  1.16s/it]

  9%|▊         | 284/3268 [05:29<57:31,  1.16s/it]

  9%|▊         | 285/3268 [05:30<57:26,  1.16s/it]

  9%|▉         | 286/3268 [05:31<57:23,  1.15s/it]

  9%|▉         | 287/3268 [05:32<57:24,  1.16s/it]

  9%|▉         | 288/3268 [05:33<57:25,  1.16s/it]

  9%|▉         | 289/3268 [05:35<57:25,  1.16s/it]

  9%|▉         | 290/3268 [05:36<57:23,  1.16s/it]

  9%|▉         | 291/3268 [05:37<57:20,  1.16s/it]

  9%|▉         | 292/3268 [05:38<57:18,  1.16s/it]

  9%|▉         | 293/3268 [05:39<57:20,  1.16s/it]

  9%|▉         | 294/3268 [05:40<57:15,  1.16s/it]

  9%|▉         | 295/3268 [05:42<57:13,  1.15s/it]

  9%|▉         | 296/3268 [05:43<57:10,  1.15s/it]

  9%|▉         | 297/3268 [05:44<57:10,  1.15s/it]

  9%|▉         | 298/3268 [05:45<57:10,  1.16s/it]

  9%|▉         | 299/3268 [05:46<57:12,  1.16s/it]

  9%|▉         | 300/3268 [05:47<57:12,  1.16s/it]

  9%|▉         | 301/3268 [05:48<57:10,  1.16s/it]

  9%|▉         | 302/3268 [05:50<57:08,  1.16s/it]

  9%|▉         | 303/3268 [05:51<57:08,  1.16s/it]

  9%|▉         | 304/3268 [05:52<57:10,  1.16s/it]

  9%|▉         | 305/3268 [05:53<57:07,  1.16s/it]

  9%|▉         | 306/3268 [05:54<57:03,  1.16s/it]

  9%|▉         | 307/3268 [05:55<57:01,  1.16s/it]

  9%|▉         | 308/3268 [05:57<57:00,  1.16s/it]

  9%|▉         | 309/3268 [05:58<57:03,  1.16s/it]

  9%|▉         | 310/3268 [05:59<57:01,  1.16s/it]

 10%|▉         | 311/3268 [06:00<57:00,  1.16s/it]

 10%|▉         | 312/3268 [06:01<57:02,  1.16s/it]

 10%|▉         | 313/3268 [06:02<56:58,  1.16s/it]

 10%|▉         | 314/3268 [06:04<56:58,  1.16s/it]

 10%|▉         | 315/3268 [06:05<56:52,  1.16s/it]

 10%|▉         | 316/3268 [06:06<56:53,  1.16s/it]

 10%|▉         | 317/3268 [06:07<56:51,  1.16s/it]

 10%|▉         | 318/3268 [06:08<56:54,  1.16s/it]

 10%|▉         | 319/3268 [06:09<56:53,  1.16s/it]

 10%|▉         | 320/3268 [06:10<56:52,  1.16s/it]

 10%|▉         | 321/3268 [06:12<56:50,  1.16s/it]

 10%|▉         | 322/3268 [06:13<56:47,  1.16s/it]

 10%|▉         | 323/3268 [06:14<56:44,  1.16s/it]

 10%|▉         | 324/3268 [06:15<56:38,  1.15s/it]

 10%|▉         | 325/3268 [06:16<56:36,  1.15s/it]

 10%|▉         | 326/3268 [06:17<56:36,  1.15s/it]

 10%|█         | 327/3268 [06:19<56:39,  1.16s/it]

 10%|█         | 328/3268 [06:20<56:41,  1.16s/it]

 10%|█         | 329/3268 [06:21<56:43,  1.16s/it]

 10%|█         | 330/3268 [06:22<56:40,  1.16s/it]

 10%|█         | 331/3268 [06:23<56:39,  1.16s/it]

 10%|█         | 332/3268 [06:24<56:38,  1.16s/it]

 10%|█         | 333/3268 [06:26<56:35,  1.16s/it]

 10%|█         | 334/3268 [06:27<56:33,  1.16s/it]

 10%|█         | 335/3268 [06:28<56:28,  1.16s/it]

 10%|█         | 336/3268 [06:29<56:31,  1.16s/it]

 10%|█         | 337/3268 [06:30<56:33,  1.16s/it]

 10%|█         | 338/3268 [06:31<56:36,  1.16s/it]

 10%|█         | 339/3268 [06:32<56:31,  1.16s/it]

 10%|█         | 340/3268 [06:34<56:33,  1.16s/it]

 10%|█         | 341/3268 [06:35<56:29,  1.16s/it]

 10%|█         | 342/3268 [06:36<56:22,  1.16s/it]

 10%|█         | 343/3268 [06:37<56:21,  1.16s/it]

 11%|█         | 344/3268 [06:38<56:21,  1.16s/it]

 11%|█         | 345/3268 [06:39<56:23,  1.16s/it]

 11%|█         | 346/3268 [06:41<56:20,  1.16s/it]

 11%|█         | 347/3268 [06:42<56:21,  1.16s/it]

 11%|█         | 348/3268 [06:43<56:20,  1.16s/it]

 11%|█         | 349/3268 [06:44<56:20,  1.16s/it]

 11%|█         | 350/3268 [06:45<56:15,  1.16s/it]

 11%|█         | 351/3268 [06:46<56:17,  1.16s/it]

 11%|█         | 352/3268 [06:47<56:13,  1.16s/it]

 11%|█         | 353/3268 [06:49<56:09,  1.16s/it]

 11%|█         | 354/3268 [06:50<56:09,  1.16s/it]

 11%|█         | 355/3268 [06:51<56:10,  1.16s/it]

 11%|█         | 356/3268 [06:52<56:06,  1.16s/it]

 11%|█         | 357/3268 [06:53<56:06,  1.16s/it]

 11%|█         | 358/3268 [06:54<56:14,  1.16s/it]

 11%|█         | 359/3268 [06:56<56:12,  1.16s/it]

 11%|█         | 360/3268 [06:57<56:07,  1.16s/it]

 11%|█         | 361/3268 [06:58<56:07,  1.16s/it]

 11%|█         | 362/3268 [06:59<56:07,  1.16s/it]

 11%|█         | 363/3268 [07:00<56:05,  1.16s/it]

 11%|█         | 364/3268 [07:01<56:02,  1.16s/it]

 11%|█         | 365/3268 [07:03<55:58,  1.16s/it]

 11%|█         | 366/3268 [07:04<55:57,  1.16s/it]

 11%|█         | 367/3268 [07:05<55:53,  1.16s/it]

 11%|█▏        | 368/3268 [07:06<55:55,  1.16s/it]

 11%|█▏        | 369/3268 [07:07<55:53,  1.16s/it]

 11%|█▏        | 370/3268 [07:08<55:54,  1.16s/it]

 11%|█▏        | 371/3268 [07:09<55:51,  1.16s/it]

 11%|█▏        | 372/3268 [07:11<55:50,  1.16s/it]

 11%|█▏        | 373/3268 [07:12<55:53,  1.16s/it]

 11%|█▏        | 374/3268 [07:13<55:49,  1.16s/it]

 11%|█▏        | 375/3268 [07:14<55:47,  1.16s/it]

 12%|█▏        | 376/3268 [07:15<55:45,  1.16s/it]

 12%|█▏        | 377/3268 [07:16<55:43,  1.16s/it]

 12%|█▏        | 378/3268 [07:18<55:44,  1.16s/it]

 12%|█▏        | 379/3268 [07:19<55:45,  1.16s/it]

 12%|█▏        | 380/3268 [07:20<55:44,  1.16s/it]

 12%|█▏        | 381/3268 [07:21<55:44,  1.16s/it]

 12%|█▏        | 382/3268 [07:22<55:43,  1.16s/it]

 12%|█▏        | 383/3268 [07:23<55:43,  1.16s/it]

 12%|█▏        | 384/3268 [07:25<55:41,  1.16s/it]

 12%|█▏        | 385/3268 [07:26<55:39,  1.16s/it]

 12%|█▏        | 386/3268 [07:27<55:39,  1.16s/it]

 12%|█▏        | 387/3268 [07:28<55:33,  1.16s/it]

 12%|█▏        | 388/3268 [07:29<55:33,  1.16s/it]

 12%|█▏        | 389/3268 [07:30<55:35,  1.16s/it]

 12%|█▏        | 390/3268 [07:31<55:36,  1.16s/it]

 12%|█▏        | 391/3268 [07:33<55:34,  1.16s/it]

 12%|█▏        | 392/3268 [07:34<55:33,  1.16s/it]

 12%|█▏        | 393/3268 [07:35<55:31,  1.16s/it]

 12%|█▏        | 394/3268 [07:36<55:29,  1.16s/it]

 12%|█▏        | 395/3268 [07:37<55:27,  1.16s/it]

 12%|█▏        | 396/3268 [07:38<55:27,  1.16s/it]

 12%|█▏        | 397/3268 [07:40<55:24,  1.16s/it]

 12%|█▏        | 398/3268 [07:41<55:24,  1.16s/it]

 12%|█▏        | 399/3268 [07:42<55:24,  1.16s/it]

 12%|█▏        | 400/3268 [07:43<55:22,  1.16s/it]

 12%|█▏        | 401/3268 [07:44<55:20,  1.16s/it]

 12%|█▏        | 402/3268 [07:45<55:23,  1.16s/it]

 12%|█▏        | 403/3268 [07:47<55:20,  1.16s/it]

 12%|█▏        | 404/3268 [07:48<55:17,  1.16s/it]

 12%|█▏        | 405/3268 [07:49<55:15,  1.16s/it]

 12%|█▏        | 406/3268 [07:50<55:13,  1.16s/it]

 12%|█▏        | 407/3268 [07:51<55:12,  1.16s/it]

 12%|█▏        | 408/3268 [07:52<55:13,  1.16s/it]

 13%|█▎        | 409/3268 [07:53<55:14,  1.16s/it]

 13%|█▎        | 410/3268 [07:55<55:15,  1.16s/it]

 13%|█▎        | 411/3268 [07:56<55:11,  1.16s/it]

 13%|█▎        | 412/3268 [07:57<55:09,  1.16s/it]

 13%|█▎        | 413/3268 [07:58<55:08,  1.16s/it]

 13%|█▎        | 414/3268 [07:59<55:16,  1.16s/it]

 13%|█▎        | 415/3268 [08:00<55:11,  1.16s/it]

 13%|█▎        | 416/3268 [08:02<55:11,  1.16s/it]

 13%|█▎        | 417/3268 [08:03<55:08,  1.16s/it]

 13%|█▎        | 418/3268 [08:04<55:07,  1.16s/it]

 13%|█▎        | 419/3268 [08:05<55:03,  1.16s/it]

 13%|█▎        | 420/3268 [08:06<54:58,  1.16s/it]

 13%|█▎        | 421/3268 [08:07<54:56,  1.16s/it]

 13%|█▎        | 422/3268 [08:09<54:51,  1.16s/it]

 13%|█▎        | 423/3268 [08:10<54:54,  1.16s/it]

 13%|█▎        | 424/3268 [08:11<54:51,  1.16s/it]

 13%|█▎        | 425/3268 [08:12<54:53,  1.16s/it]

 13%|█▎        | 426/3268 [08:13<54:51,  1.16s/it]

 13%|█▎        | 427/3268 [08:14<54:55,  1.16s/it]

 13%|█▎        | 428/3268 [08:16<54:54,  1.16s/it]

 13%|█▎        | 429/3268 [08:17<54:49,  1.16s/it]

 13%|█▎        | 430/3268 [08:18<54:45,  1.16s/it]

 13%|█▎        | 431/3268 [08:19<54:46,  1.16s/it]

 13%|█▎        | 432/3268 [08:20<54:43,  1.16s/it]

 13%|█▎        | 433/3268 [08:21<54:46,  1.16s/it]

 13%|█▎        | 434/3268 [08:22<54:47,  1.16s/it]

 13%|█▎        | 435/3268 [08:24<54:49,  1.16s/it]

 13%|█▎        | 436/3268 [08:25<54:47,  1.16s/it]

 13%|█▎        | 437/3268 [08:26<54:44,  1.16s/it]

 13%|█▎        | 438/3268 [08:27<54:43,  1.16s/it]

 13%|█▎        | 439/3268 [08:28<54:52,  1.16s/it]

 13%|█▎        | 440/3268 [08:29<54:47,  1.16s/it]

 13%|█▎        | 441/3268 [08:31<54:45,  1.16s/it]

 14%|█▎        | 442/3268 [08:32<54:39,  1.16s/it]

 14%|█▎        | 443/3268 [08:33<54:34,  1.16s/it]

 14%|█▎        | 444/3268 [08:34<54:33,  1.16s/it]

 14%|█▎        | 445/3268 [08:35<54:33,  1.16s/it]

 14%|█▎        | 446/3268 [08:36<54:31,  1.16s/it]

 14%|█▎        | 447/3268 [08:38<54:30,  1.16s/it]

 14%|█▎        | 448/3268 [08:39<54:28,  1.16s/it]

 14%|█▎        | 449/3268 [08:40<54:31,  1.16s/it]

 14%|█▍        | 450/3268 [08:41<54:31,  1.16s/it]

 14%|█▍        | 451/3268 [08:42<54:27,  1.16s/it]

 14%|█▍        | 452/3268 [08:43<54:26,  1.16s/it]

 14%|█▍        | 453/3268 [08:45<54:23,  1.16s/it]

 14%|█▍        | 454/3268 [08:46<54:21,  1.16s/it]

 14%|█▍        | 455/3268 [08:47<54:19,  1.16s/it]

 14%|█▍        | 456/3268 [08:48<54:21,  1.16s/it]

 14%|█▍        | 457/3268 [08:49<54:19,  1.16s/it]

 14%|█▍        | 458/3268 [08:50<54:20,  1.16s/it]

 14%|█▍        | 459/3268 [08:51<54:16,  1.16s/it]

 14%|█▍        | 460/3268 [08:53<54:16,  1.16s/it]

 14%|█▍        | 461/3268 [08:54<54:17,  1.16s/it]

 14%|█▍        | 462/3268 [08:55<54:12,  1.16s/it]

 14%|█▍        | 463/3268 [08:56<54:10,  1.16s/it]

 14%|█▍        | 464/3268 [08:57<54:07,  1.16s/it]

 14%|█▍        | 465/3268 [08:58<54:02,  1.16s/it]

 14%|█▍        | 466/3268 [09:00<54:06,  1.16s/it]

 14%|█▍        | 467/3268 [09:01<54:09,  1.16s/it]

 14%|█▍        | 468/3268 [09:02<54:07,  1.16s/it]

 14%|█▍        | 469/3268 [09:03<54:04,  1.16s/it]

 14%|█▍        | 470/3268 [09:04<54:05,  1.16s/it]

 14%|█▍        | 471/3268 [09:05<54:03,  1.16s/it]

 14%|█▍        | 472/3268 [09:07<54:01,  1.16s/it]

 14%|█▍        | 473/3268 [09:08<54:02,  1.16s/it]

 15%|█▍        | 474/3268 [09:09<54:01,  1.16s/it]

 15%|█▍        | 475/3268 [09:10<54:02,  1.16s/it]

 15%|█▍        | 476/3268 [09:11<54:04,  1.16s/it]

 15%|█▍        | 477/3268 [09:12<54:06,  1.16s/it]

 15%|█▍        | 478/3268 [09:14<54:04,  1.16s/it]

 15%|█▍        | 479/3268 [09:15<54:01,  1.16s/it]

 15%|█▍        | 480/3268 [09:16<53:58,  1.16s/it]

 15%|█▍        | 481/3268 [09:17<53:53,  1.16s/it]

 15%|█▍        | 482/3268 [09:18<53:51,  1.16s/it]

 15%|█▍        | 483/3268 [09:19<53:50,  1.16s/it]

 15%|█▍        | 484/3268 [09:20<53:52,  1.16s/it]

 15%|█▍        | 485/3268 [09:22<53:52,  1.16s/it]

 15%|█▍        | 486/3268 [09:23<53:52,  1.16s/it]

 15%|█▍        | 487/3268 [09:24<53:49,  1.16s/it]

 15%|█▍        | 488/3268 [09:25<53:46,  1.16s/it]

 15%|█▍        | 489/3268 [09:26<53:42,  1.16s/it]

 15%|█▍        | 490/3268 [09:27<53:39,  1.16s/it]

 15%|█▌        | 491/3268 [09:29<53:35,  1.16s/it]

 15%|█▌        | 492/3268 [09:30<53:35,  1.16s/it]

 15%|█▌        | 493/3268 [09:31<53:35,  1.16s/it]

 15%|█▌        | 494/3268 [09:32<53:34,  1.16s/it]

 15%|█▌        | 495/3268 [09:33<53:32,  1.16s/it]

 15%|█▌        | 496/3268 [09:34<53:33,  1.16s/it]

 15%|█▌        | 497/3268 [09:36<53:31,  1.16s/it]

 15%|█▌        | 498/3268 [09:37<53:31,  1.16s/it]

 15%|█▌        | 499/3268 [09:38<53:32,  1.16s/it]

 15%|█▌        | 500/3268 [09:39<53:26,  1.16s/it]

 15%|█▌        | 501/3268 [09:40<53:24,  1.16s/it]

 15%|█▌        | 502/3268 [09:41<53:28,  1.16s/it]

 15%|█▌        | 503/3268 [09:43<53:26,  1.16s/it]

 15%|█▌        | 504/3268 [09:44<53:26,  1.16s/it]

 15%|█▌        | 505/3268 [09:45<53:24,  1.16s/it]

 15%|█▌        | 506/3268 [09:46<53:23,  1.16s/it]

 16%|█▌        | 507/3268 [09:47<53:26,  1.16s/it]

 16%|█▌        | 508/3268 [09:48<53:23,  1.16s/it]

 16%|█▌        | 509/3268 [09:49<53:20,  1.16s/it]

 16%|█▌        | 510/3268 [09:51<53:17,  1.16s/it]

 16%|█▌        | 511/3268 [09:52<53:17,  1.16s/it]

 16%|█▌        | 512/3268 [09:53<53:14,  1.16s/it]

 16%|█▌        | 513/3268 [09:54<53:13,  1.16s/it]

 16%|█▌        | 514/3268 [09:55<53:15,  1.16s/it]

 16%|█▌        | 515/3268 [09:56<53:16,  1.16s/it]

 16%|█▌        | 516/3268 [09:58<53:16,  1.16s/it]

 16%|█▌        | 517/3268 [09:59<53:14,  1.16s/it]

 16%|█▌        | 518/3268 [10:00<53:12,  1.16s/it]

 16%|█▌        | 519/3268 [10:01<53:12,  1.16s/it]

 16%|█▌        | 520/3268 [10:02<53:13,  1.16s/it]

 16%|█▌        | 521/3268 [10:03<53:11,  1.16s/it]

 16%|█▌        | 522/3268 [10:05<53:06,  1.16s/it]

 16%|█▌        | 523/3268 [10:06<53:02,  1.16s/it]

 16%|█▌        | 524/3268 [10:07<52:59,  1.16s/it]

 16%|█▌        | 525/3268 [10:08<53:03,  1.16s/it]

 16%|█▌        | 526/3268 [10:09<53:03,  1.16s/it]

 16%|█▌        | 527/3268 [10:10<53:01,  1.16s/it]

 16%|█▌        | 528/3268 [10:12<52:58,  1.16s/it]

 16%|█▌        | 529/3268 [10:13<52:56,  1.16s/it]

 16%|█▌        | 530/3268 [10:14<53:03,  1.16s/it]

 16%|█▌        | 531/3268 [10:15<53:02,  1.16s/it]

 16%|█▋        | 532/3268 [10:16<53:00,  1.16s/it]

 16%|█▋        | 533/3268 [10:17<52:55,  1.16s/it]

 16%|█▋        | 534/3268 [10:18<52:55,  1.16s/it]

 16%|█▋        | 535/3268 [10:20<52:55,  1.16s/it]

 16%|█▋        | 536/3268 [10:21<52:55,  1.16s/it]

 16%|█▋        | 537/3268 [10:22<52:53,  1.16s/it]

 16%|█▋        | 538/3268 [10:23<52:47,  1.16s/it]

 16%|█▋        | 539/3268 [10:24<52:43,  1.16s/it]

 17%|█▋        | 540/3268 [10:25<52:42,  1.16s/it]

 17%|█▋        | 541/3268 [10:27<52:44,  1.16s/it]

 17%|█▋        | 542/3268 [10:28<52:43,  1.16s/it]

 17%|█▋        | 543/3268 [10:29<52:43,  1.16s/it]

 17%|█▋        | 544/3268 [10:30<52:41,  1.16s/it]

 17%|█▋        | 545/3268 [10:31<52:39,  1.16s/it]

 17%|█▋        | 546/3268 [10:32<52:37,  1.16s/it]

 17%|█▋        | 547/3268 [10:34<52:36,  1.16s/it]

 17%|█▋        | 548/3268 [10:35<52:34,  1.16s/it]

 17%|█▋        | 549/3268 [10:36<52:29,  1.16s/it]

 17%|█▋        | 550/3268 [10:37<52:30,  1.16s/it]

 17%|█▋        | 551/3268 [10:38<52:29,  1.16s/it]

 17%|█▋        | 552/3268 [10:39<52:27,  1.16s/it]

 17%|█▋        | 553/3268 [10:41<52:25,  1.16s/it]

 17%|█▋        | 554/3268 [10:42<52:24,  1.16s/it]

 17%|█▋        | 555/3268 [10:43<52:26,  1.16s/it]

 17%|█▋        | 556/3268 [10:44<52:24,  1.16s/it]

 17%|█▋        | 557/3268 [10:45<52:24,  1.16s/it]

 17%|█▋        | 558/3268 [10:46<52:20,  1.16s/it]

 17%|█▋        | 559/3268 [10:47<52:19,  1.16s/it]

 17%|█▋        | 560/3268 [10:49<52:18,  1.16s/it]

 17%|█▋        | 561/3268 [10:50<52:16,  1.16s/it]

 17%|█▋        | 562/3268 [10:51<52:17,  1.16s/it]

 17%|█▋        | 563/3268 [10:52<52:18,  1.16s/it]

 17%|█▋        | 564/3268 [10:53<52:18,  1.16s/it]

 17%|█▋        | 565/3268 [10:54<52:16,  1.16s/it]

 17%|█▋        | 566/3268 [10:56<52:16,  1.16s/it]

 17%|█▋        | 567/3268 [10:57<52:15,  1.16s/it]

 17%|█▋        | 568/3268 [10:58<52:15,  1.16s/it]

 17%|█▋        | 569/3268 [10:59<52:13,  1.16s/it]

 17%|█▋        | 570/3268 [11:00<52:09,  1.16s/it]

 17%|█▋        | 571/3268 [11:01<52:08,  1.16s/it]

 18%|█▊        | 572/3268 [11:03<52:04,  1.16s/it]

 18%|█▊        | 573/3268 [11:04<52:02,  1.16s/it]

 18%|█▊        | 574/3268 [11:05<52:03,  1.16s/it]

 18%|█▊        | 575/3268 [11:06<52:05,  1.16s/it]

 18%|█▊        | 576/3268 [11:07<52:05,  1.16s/it]

 18%|█▊        | 577/3268 [11:08<52:05,  1.16s/it]

 18%|█▊        | 578/3268 [11:10<52:02,  1.16s/it]

 18%|█▊        | 579/3268 [11:11<52:01,  1.16s/it]

 18%|█▊        | 580/3268 [11:12<52:06,  1.16s/it]

 18%|█▊        | 581/3268 [11:13<52:02,  1.16s/it]

 18%|█▊        | 582/3268 [11:14<52:00,  1.16s/it]

 18%|█▊        | 583/3268 [11:15<51:56,  1.16s/it]

 18%|█▊        | 584/3268 [11:17<51:50,  1.16s/it]

 18%|█▊        | 585/3268 [11:18<51:46,  1.16s/it]

 18%|█▊        | 586/3268 [11:19<51:49,  1.16s/it]

 18%|█▊        | 587/3268 [11:20<51:51,  1.16s/it]

 18%|█▊        | 588/3268 [11:21<51:52,  1.16s/it]

 18%|█▊        | 589/3268 [11:22<51:54,  1.16s/it]

 18%|█▊        | 590/3268 [11:23<51:54,  1.16s/it]

 18%|█▊        | 591/3268 [11:25<51:52,  1.16s/it]

 18%|█▊        | 592/3268 [11:26<51:47,  1.16s/it]

 18%|█▊        | 593/3268 [11:27<51:47,  1.16s/it]

 18%|█▊        | 594/3268 [11:28<51:50,  1.16s/it]

 18%|█▊        | 595/3268 [11:29<51:48,  1.16s/it]

 18%|█▊        | 596/3268 [11:30<51:43,  1.16s/it]

 18%|█▊        | 597/3268 [11:32<51:43,  1.16s/it]

 18%|█▊        | 598/3268 [11:33<51:42,  1.16s/it]

 18%|█▊        | 599/3268 [11:34<51:40,  1.16s/it]

 18%|█▊        | 600/3268 [11:35<51:37,  1.16s/it]

 18%|█▊        | 601/3268 [11:36<51:36,  1.16s/it]

 18%|█▊        | 602/3268 [11:37<51:37,  1.16s/it]

 18%|█▊        | 603/3268 [11:39<51:38,  1.16s/it]

 18%|█▊        | 604/3268 [11:40<51:35,  1.16s/it]

 19%|█▊        | 605/3268 [11:41<51:36,  1.16s/it]

 19%|█▊        | 606/3268 [11:42<51:37,  1.16s/it]

 19%|█▊        | 607/3268 [11:43<51:36,  1.16s/it]

 19%|█▊        | 608/3268 [11:44<51:33,  1.16s/it]

 19%|█▊        | 609/3268 [11:46<51:31,  1.16s/it]

 19%|█▊        | 610/3268 [11:47<51:26,  1.16s/it]

 19%|█▊        | 611/3268 [11:48<51:23,  1.16s/it]

 19%|█▊        | 612/3268 [11:49<51:21,  1.16s/it]

 19%|█▉        | 613/3268 [11:50<51:18,  1.16s/it]

 19%|█▉        | 614/3268 [11:51<51:17,  1.16s/it]

 19%|█▉        | 615/3268 [11:53<51:18,  1.16s/it]

 19%|█▉        | 616/3268 [11:54<51:16,  1.16s/it]

 19%|█▉        | 617/3268 [11:55<51:14,  1.16s/it]

 19%|█▉        | 618/3268 [11:56<51:14,  1.16s/it]

 19%|█▉        | 619/3268 [11:57<51:19,  1.16s/it]

 19%|█▉        | 620/3268 [11:58<51:21,  1.16s/it]

 19%|█▉        | 621/3268 [11:59<51:17,  1.16s/it]

 19%|█▉        | 622/3268 [12:01<51:16,  1.16s/it]

 19%|█▉        | 623/3268 [12:02<51:15,  1.16s/it]

 19%|█▉        | 624/3268 [12:03<51:13,  1.16s/it]

 19%|█▉        | 625/3268 [12:04<51:07,  1.16s/it]

logging
logging the anndata

 19%|█▉        | 626/3268 [12:05<53:11,  1.21s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 19%|█▉        | 627/3268 [12:07<52:27,  1.19s/it]

 19%|█▉        | 628/3268 [12:08<51:57,  1.18s/it]

 19%|█▉        | 629/3268 [12:09<51:35,  1.17s/it]

 19%|█▉        | 630/3268 [12:10<51:22,  1.17s/it]

 19%|█▉        | 631/3268 [12:11<51:09,  1.16s/it]

 19%|█▉        | 632/3268 [12:12<51:01,  1.16s/it]

 19%|█▉        | 633/3268 [12:14<50:52,  1.16s/it]

 19%|█▉        | 634/3268 [12:15<50:48,  1.16s/it]

 19%|█▉        | 635/3268 [12:16<50:44,  1.16s/it]

 19%|█▉        | 636/3268 [12:17<50:43,  1.16s/it]

 19%|█▉        | 637/3268 [12:18<50:40,  1.16s/it]

 20%|█▉        | 638/3268 [12:19<50:39,  1.16s/it]

 20%|█▉        | 639/3268 [12:20<50:38,  1.16s/it]

 20%|█▉        | 640/3268 [12:22<50:39,  1.16s/it]

 20%|█▉        | 641/3268 [12:23<50:38,  1.16s/it]

 20%|█▉        | 642/3268 [12:24<50:33,  1.16s/it]

 20%|█▉        | 643/3268 [12:25<50:31,  1.15s/it]

 20%|█▉        | 644/3268 [12:26<50:31,  1.16s/it]

 20%|█▉        | 645/3268 [12:27<50:30,  1.16s/it]

 20%|█▉        | 646/3268 [12:29<50:28,  1.16s/it]

 20%|█▉        | 647/3268 [12:30<50:29,  1.16s/it]

 20%|█▉        | 648/3268 [12:31<50:28,  1.16s/it]

 20%|█▉        | 649/3268 [12:32<50:28,  1.16s/it]

 20%|█▉        | 650/3268 [12:33<50:28,  1.16s/it]

 20%|█▉        | 651/3268 [12:34<50:28,  1.16s/it]

 20%|█▉        | 652/3268 [12:35<50:27,  1.16s/it]

 20%|█▉        | 653/3268 [12:37<50:22,  1.16s/it]

 20%|██        | 654/3268 [12:38<50:18,  1.15s/it]

 20%|██        | 655/3268 [12:39<50:17,  1.15s/it]

 20%|██        | 656/3268 [12:40<50:17,  1.16s/it]

 20%|██        | 657/3268 [12:41<50:15,  1.15s/it]

 20%|██        | 658/3268 [12:42<50:15,  1.16s/it]

 20%|██        | 659/3268 [12:44<50:15,  1.16s/it]

 20%|██        | 660/3268 [12:45<50:12,  1.16s/it]

 20%|██        | 661/3268 [12:46<50:09,  1.15s/it]

 20%|██        | 662/3268 [12:47<50:06,  1.15s/it]

 20%|██        | 663/3268 [12:48<50:06,  1.15s/it]

 20%|██        | 664/3268 [12:49<50:06,  1.15s/it]

 20%|██        | 665/3268 [12:51<50:07,  1.16s/it]

 20%|██        | 666/3268 [12:52<50:04,  1.15s/it]

 20%|██        | 667/3268 [12:53<50:06,  1.16s/it]

 20%|██        | 668/3268 [12:54<50:03,  1.16s/it]

 20%|██        | 669/3268 [12:55<50:00,  1.15s/it]

 21%|██        | 670/3268 [12:56<49:57,  1.15s/it]

 21%|██        | 671/3268 [12:57<49:58,  1.15s/it]

 21%|██        | 672/3268 [12:59<49:59,  1.16s/it]

 21%|██        | 673/3268 [13:00<49:58,  1.16s/it]

 21%|██        | 674/3268 [13:01<49:55,  1.15s/it]

 21%|██        | 675/3268 [13:02<49:53,  1.15s/it]

 21%|██        | 676/3268 [13:03<49:52,  1.15s/it]

 21%|██        | 677/3268 [13:04<49:51,  1.15s/it]

 21%|██        | 678/3268 [13:06<49:48,  1.15s/it]

 21%|██        | 679/3268 [13:07<49:49,  1.15s/it]

 21%|██        | 680/3268 [13:08<49:52,  1.16s/it]

 21%|██        | 681/3268 [13:09<49:52,  1.16s/it]

 21%|██        | 682/3268 [13:10<49:51,  1.16s/it]

 21%|██        | 683/3268 [13:11<49:52,  1.16s/it]

 21%|██        | 684/3268 [13:12<49:51,  1.16s/it]

 21%|██        | 685/3268 [13:14<49:47,  1.16s/it]

 21%|██        | 686/3268 [13:15<49:46,  1.16s/it]

 21%|██        | 687/3268 [13:16<49:42,  1.16s/it]

 21%|██        | 688/3268 [13:17<49:41,  1.16s/it]

 21%|██        | 689/3268 [13:18<49:40,  1.16s/it]

 21%|██        | 690/3268 [13:19<49:44,  1.16s/it]

 21%|██        | 691/3268 [13:21<49:43,  1.16s/it]

 21%|██        | 692/3268 [13:22<49:39,  1.16s/it]

 21%|██        | 693/3268 [13:23<49:40,  1.16s/it]

 21%|██        | 694/3268 [13:24<49:36,  1.16s/it]

 21%|██▏       | 695/3268 [13:25<49:32,  1.16s/it]

 21%|██▏       | 696/3268 [13:26<49:29,  1.15s/it]

 21%|██▏       | 697/3268 [13:27<49:30,  1.16s/it]

 21%|██▏       | 698/3268 [13:29<49:27,  1.15s/it]

 21%|██▏       | 699/3268 [13:30<49:27,  1.16s/it]

 21%|██▏       | 700/3268 [13:31<49:26,  1.16s/it]

 21%|██▏       | 701/3268 [13:32<49:25,  1.16s/it]

 21%|██▏       | 702/3268 [13:33<49:26,  1.16s/it]

 22%|██▏       | 703/3268 [13:34<49:23,  1.16s/it]

 22%|██▏       | 704/3268 [13:36<49:22,  1.16s/it]

 22%|██▏       | 705/3268 [13:37<49:25,  1.16s/it]

 22%|██▏       | 706/3268 [13:38<49:23,  1.16s/it]

 22%|██▏       | 707/3268 [13:39<49:24,  1.16s/it]

 22%|██▏       | 708/3268 [13:40<49:19,  1.16s/it]

 22%|██▏       | 709/3268 [13:41<49:17,  1.16s/it]

 22%|██▏       | 710/3268 [13:43<49:15,  1.16s/it]

 22%|██▏       | 711/3268 [13:44<49:13,  1.16s/it]

 22%|██▏       | 712/3268 [13:45<49:14,  1.16s/it]

 22%|██▏       | 713/3268 [13:46<49:12,  1.16s/it]

 22%|██▏       | 714/3268 [13:47<49:12,  1.16s/it]

 22%|██▏       | 715/3268 [13:48<49:12,  1.16s/it]

 22%|██▏       | 716/3268 [13:49<49:08,  1.16s/it]

 22%|██▏       | 717/3268 [13:51<49:08,  1.16s/it]

 22%|██▏       | 718/3268 [13:52<49:05,  1.16s/it]

 22%|██▏       | 719/3268 [13:53<49:06,  1.16s/it]

 22%|██▏       | 720/3268 [13:54<49:07,  1.16s/it]

 22%|██▏       | 721/3268 [13:55<49:03,  1.16s/it]

 22%|██▏       | 722/3268 [13:56<49:04,  1.16s/it]

 22%|██▏       | 723/3268 [13:58<49:01,  1.16s/it]

 22%|██▏       | 724/3268 [13:59<48:58,  1.16s/it]

 22%|██▏       | 725/3268 [14:00<48:56,  1.15s/it]

 22%|██▏       | 726/3268 [14:01<48:56,  1.16s/it]

 22%|██▏       | 727/3268 [14:02<48:57,  1.16s/it]

 22%|██▏       | 728/3268 [14:03<48:55,  1.16s/it]

 22%|██▏       | 729/3268 [14:04<48:57,  1.16s/it]

 22%|██▏       | 730/3268 [14:06<48:55,  1.16s/it]

 22%|██▏       | 731/3268 [14:07<48:53,  1.16s/it]

 22%|██▏       | 732/3268 [14:08<48:49,  1.16s/it]

 22%|██▏       | 733/3268 [14:09<48:47,  1.15s/it]

 22%|██▏       | 734/3268 [14:10<48:46,  1.16s/it]

 22%|██▏       | 735/3268 [14:11<48:48,  1.16s/it]

 23%|██▎       | 736/3268 [14:13<48:48,  1.16s/it]

 23%|██▎       | 737/3268 [14:14<48:47,  1.16s/it]

 23%|██▎       | 738/3268 [14:15<48:44,  1.16s/it]

 23%|██▎       | 739/3268 [14:16<48:47,  1.16s/it]

 23%|██▎       | 740/3268 [14:17<48:42,  1.16s/it]

 23%|██▎       | 741/3268 [14:18<48:42,  1.16s/it]

 23%|██▎       | 742/3268 [14:20<48:37,  1.15s/it]

 23%|██▎       | 743/3268 [14:21<48:35,  1.15s/it]

 23%|██▎       | 744/3268 [14:22<48:34,  1.15s/it]

 23%|██▎       | 745/3268 [14:23<48:34,  1.16s/it]

 23%|██▎       | 746/3268 [14:24<48:35,  1.16s/it]

 23%|██▎       | 747/3268 [14:25<48:34,  1.16s/it]

 23%|██▎       | 748/3268 [14:26<48:33,  1.16s/it]

 23%|██▎       | 749/3268 [14:28<48:30,  1.16s/it]

 23%|██▎       | 750/3268 [14:29<48:28,  1.15s/it]

 23%|██▎       | 751/3268 [14:30<48:24,  1.15s/it]

 23%|██▎       | 752/3268 [14:31<48:24,  1.15s/it]

 23%|██▎       | 753/3268 [14:32<48:24,  1.16s/it]

 23%|██▎       | 754/3268 [14:33<48:26,  1.16s/it]

 23%|██▎       | 755/3268 [14:35<48:25,  1.16s/it]

 23%|██▎       | 756/3268 [14:36<48:26,  1.16s/it]

 23%|██▎       | 757/3268 [14:37<48:23,  1.16s/it]

 23%|██▎       | 758/3268 [14:38<48:19,  1.16s/it]

 23%|██▎       | 759/3268 [14:39<48:19,  1.16s/it]

 23%|██▎       | 760/3268 [14:40<48:18,  1.16s/it]

 23%|██▎       | 761/3268 [14:41<48:19,  1.16s/it]

 23%|██▎       | 762/3268 [14:43<48:16,  1.16s/it]

 23%|██▎       | 763/3268 [14:44<48:18,  1.16s/it]

 23%|██▎       | 764/3268 [14:45<48:18,  1.16s/it]

 23%|██▎       | 765/3268 [14:46<48:16,  1.16s/it]

 23%|██▎       | 766/3268 [14:47<48:13,  1.16s/it]

 23%|██▎       | 767/3268 [14:48<48:14,  1.16s/it]

 24%|██▎       | 768/3268 [14:50<48:12,  1.16s/it]

 24%|██▎       | 769/3268 [14:51<48:11,  1.16s/it]

 24%|██▎       | 770/3268 [14:52<48:09,  1.16s/it]

 24%|██▎       | 771/3268 [14:53<48:08,  1.16s/it]

 24%|██▎       | 772/3268 [14:54<48:04,  1.16s/it]

 24%|██▎       | 773/3268 [14:55<48:03,  1.16s/it]

 24%|██▎       | 774/3268 [14:57<48:07,  1.16s/it]

 24%|██▎       | 775/3268 [14:58<48:06,  1.16s/it]

 24%|██▎       | 776/3268 [14:59<48:05,  1.16s/it]

 24%|██▍       | 777/3268 [15:00<48:03,  1.16s/it]

 24%|██▍       | 778/3268 [15:01<47:59,  1.16s/it]

 24%|██▍       | 779/3268 [15:02<48:04,  1.16s/it]

 24%|██▍       | 780/3268 [15:03<48:03,  1.16s/it]

 24%|██▍       | 781/3268 [15:05<47:59,  1.16s/it]

 24%|██▍       | 782/3268 [15:06<47:58,  1.16s/it]

 24%|██▍       | 783/3268 [15:07<47:55,  1.16s/it]

 24%|██▍       | 784/3268 [15:08<47:52,  1.16s/it]

 24%|██▍       | 785/3268 [15:09<47:53,  1.16s/it]

 24%|██▍       | 786/3268 [15:10<47:53,  1.16s/it]

 24%|██▍       | 787/3268 [15:12<47:50,  1.16s/it]

 24%|██▍       | 788/3268 [15:13<47:50,  1.16s/it]

 24%|██▍       | 789/3268 [15:14<47:50,  1.16s/it]

 24%|██▍       | 790/3268 [15:15<47:47,  1.16s/it]

 24%|██▍       | 791/3268 [15:16<47:44,  1.16s/it]

 24%|██▍       | 792/3268 [15:17<47:44,  1.16s/it]

 24%|██▍       | 793/3268 [15:18<47:43,  1.16s/it]

 24%|██▍       | 794/3268 [15:20<47:42,  1.16s/it]

 24%|██▍       | 795/3268 [15:21<47:41,  1.16s/it]

 24%|██▍       | 796/3268 [15:22<47:39,  1.16s/it]

 24%|██▍       | 797/3268 [15:23<47:39,  1.16s/it]

 24%|██▍       | 798/3268 [15:24<47:37,  1.16s/it]

 24%|██▍       | 799/3268 [15:25<47:34,  1.16s/it]

 24%|██▍       | 800/3268 [15:27<47:30,  1.16s/it]

 25%|██▍       | 801/3268 [15:28<47:31,  1.16s/it]

 25%|██▍       | 802/3268 [15:29<47:31,  1.16s/it]

 25%|██▍       | 803/3268 [15:30<47:30,  1.16s/it]

 25%|██▍       | 804/3268 [15:31<47:32,  1.16s/it]

 25%|██▍       | 805/3268 [15:32<47:31,  1.16s/it]

 25%|██▍       | 806/3268 [15:34<47:30,  1.16s/it]

 25%|██▍       | 807/3268 [15:35<47:27,  1.16s/it]

 25%|██▍       | 808/3268 [15:36<47:25,  1.16s/it]

 25%|██▍       | 809/3268 [15:37<47:25,  1.16s/it]

 25%|██▍       | 810/3268 [15:38<47:22,  1.16s/it]

 25%|██▍       | 811/3268 [15:39<47:20,  1.16s/it]

 25%|██▍       | 812/3268 [15:40<47:19,  1.16s/it]

 25%|██▍       | 813/3268 [15:42<47:21,  1.16s/it]

 25%|██▍       | 814/3268 [15:43<47:18,  1.16s/it]

 25%|██▍       | 815/3268 [15:44<47:21,  1.16s/it]

 25%|██▍       | 816/3268 [15:45<47:17,  1.16s/it]

 25%|██▌       | 817/3268 [15:46<47:15,  1.16s/it]

 25%|██▌       | 818/3268 [15:47<47:12,  1.16s/it]

 25%|██▌       | 819/3268 [15:49<47:09,  1.16s/it]

 25%|██▌       | 820/3268 [15:50<47:14,  1.16s/it]

 25%|██▌       | 821/3268 [15:51<47:15,  1.16s/it]

 25%|██▌       | 822/3268 [15:52<47:17,  1.16s/it]

 25%|██▌       | 823/3268 [15:53<47:17,  1.16s/it]

 25%|██▌       | 824/3268 [15:54<47:15,  1.16s/it]

 25%|██▌       | 825/3268 [15:56<47:14,  1.16s/it]

 25%|██▌       | 826/3268 [15:57<47:14,  1.16s/it]

 25%|██▌       | 827/3268 [15:58<47:10,  1.16s/it]

 25%|██▌       | 828/3268 [15:59<47:10,  1.16s/it]

 25%|██▌       | 829/3268 [16:00<47:06,  1.16s/it]

 25%|██▌       | 830/3268 [16:01<47:01,  1.16s/it]

 25%|██▌       | 831/3268 [16:02<47:00,  1.16s/it]

 25%|██▌       | 832/3268 [16:04<46:56,  1.16s/it]

 25%|██▌       | 833/3268 [16:05<46:55,  1.16s/it]

 26%|██▌       | 834/3268 [16:06<46:57,  1.16s/it]

 26%|██▌       | 835/3268 [16:07<46:55,  1.16s/it]

 26%|██▌       | 836/3268 [16:08<46:55,  1.16s/it]

 26%|██▌       | 837/3268 [16:09<46:55,  1.16s/it]

 26%|██▌       | 838/3268 [16:11<46:58,  1.16s/it]

 26%|██▌       | 839/3268 [16:12<46:55,  1.16s/it]

 26%|██▌       | 840/3268 [16:13<46:53,  1.16s/it]

 26%|██▌       | 841/3268 [16:14<46:53,  1.16s/it]

 26%|██▌       | 842/3268 [16:15<46:51,  1.16s/it]

 26%|██▌       | 843/3268 [16:16<46:50,  1.16s/it]

 26%|██▌       | 844/3268 [16:18<46:51,  1.16s/it]

 26%|██▌       | 845/3268 [16:19<46:47,  1.16s/it]

 26%|██▌       | 846/3268 [16:20<46:46,  1.16s/it]

 26%|██▌       | 847/3268 [16:21<46:44,  1.16s/it]

 26%|██▌       | 848/3268 [16:22<46:46,  1.16s/it]

 26%|██▌       | 849/3268 [16:23<46:43,  1.16s/it]

 26%|██▌       | 850/3268 [16:24<46:43,  1.16s/it]

 26%|██▌       | 851/3268 [16:26<46:37,  1.16s/it]

 26%|██▌       | 852/3268 [16:27<46:37,  1.16s/it]

 26%|██▌       | 853/3268 [16:28<46:33,  1.16s/it]

 26%|██▌       | 854/3268 [16:29<46:34,  1.16s/it]

 26%|██▌       | 855/3268 [16:30<46:36,  1.16s/it]

 26%|██▌       | 856/3268 [16:31<46:36,  1.16s/it]

 26%|██▌       | 857/3268 [16:33<46:33,  1.16s/it]

 26%|██▋       | 858/3268 [16:34<46:32,  1.16s/it]

 26%|██▋       | 859/3268 [16:35<46:30,  1.16s/it]

 26%|██▋       | 860/3268 [16:36<46:26,  1.16s/it]

 26%|██▋       | 861/3268 [16:37<46:23,  1.16s/it]

 26%|██▋       | 862/3268 [16:38<46:23,  1.16s/it]

 26%|██▋       | 863/3268 [16:40<46:25,  1.16s/it]

 26%|██▋       | 864/3268 [16:41<46:24,  1.16s/it]

 26%|██▋       | 865/3268 [16:42<46:24,  1.16s/it]

 26%|██▋       | 866/3268 [16:43<46:19,  1.16s/it]

 27%|██▋       | 867/3268 [16:44<46:20,  1.16s/it]

 27%|██▋       | 868/3268 [16:45<46:17,  1.16s/it]

 27%|██▋       | 869/3268 [16:46<46:17,  1.16s/it]

 27%|██▋       | 870/3268 [16:48<46:15,  1.16s/it]

 27%|██▋       | 871/3268 [16:49<46:12,  1.16s/it]

 27%|██▋       | 872/3268 [16:50<46:12,  1.16s/it]

 27%|██▋       | 873/3268 [16:51<46:12,  1.16s/it]

 27%|██▋       | 874/3268 [16:52<46:09,  1.16s/it]

 27%|██▋       | 875/3268 [16:53<46:07,  1.16s/it]

 27%|██▋       | 876/3268 [16:55<46:08,  1.16s/it]

 27%|██▋       | 877/3268 [16:56<46:05,  1.16s/it]

 27%|██▋       | 878/3268 [16:57<46:07,  1.16s/it]

 27%|██▋       | 879/3268 [16:58<46:07,  1.16s/it]

 27%|██▋       | 880/3268 [16:59<46:04,  1.16s/it]

 27%|██▋       | 881/3268 [17:00<46:06,  1.16s/it]

 27%|██▋       | 882/3268 [17:02<46:09,  1.16s/it]

 27%|██▋       | 883/3268 [17:03<46:10,  1.16s/it]

 27%|██▋       | 884/3268 [17:04<46:05,  1.16s/it]

 27%|██▋       | 885/3268 [17:05<46:00,  1.16s/it]

 27%|██▋       | 886/3268 [17:06<45:59,  1.16s/it]

 27%|██▋       | 887/3268 [17:07<45:58,  1.16s/it]

 27%|██▋       | 888/3268 [17:08<45:55,  1.16s/it]

 27%|██▋       | 889/3268 [17:10<45:54,  1.16s/it]

 27%|██▋       | 890/3268 [17:11<45:57,  1.16s/it]

 27%|██▋       | 891/3268 [17:12<45:52,  1.16s/it]

 27%|██▋       | 892/3268 [17:13<45:52,  1.16s/it]

 27%|██▋       | 893/3268 [17:14<45:50,  1.16s/it]

 27%|██▋       | 894/3268 [17:15<45:48,  1.16s/it]

 27%|██▋       | 895/3268 [17:17<45:48,  1.16s/it]

 27%|██▋       | 896/3268 [17:18<45:48,  1.16s/it]

 27%|██▋       | 897/3268 [17:19<45:45,  1.16s/it]

 27%|██▋       | 898/3268 [17:20<45:46,  1.16s/it]

 28%|██▊       | 899/3268 [17:21<45:45,  1.16s/it]

 28%|██▊       | 900/3268 [17:22<45:43,  1.16s/it]

 28%|██▊       | 901/3268 [17:24<45:42,  1.16s/it]

 28%|██▊       | 902/3268 [17:25<45:41,  1.16s/it]

 28%|██▊       | 903/3268 [17:26<45:38,  1.16s/it]

 28%|██▊       | 904/3268 [17:27<45:36,  1.16s/it]

 28%|██▊       | 905/3268 [17:28<45:34,  1.16s/it]

 28%|██▊       | 906/3268 [17:29<45:33,  1.16s/it]

 28%|██▊       | 907/3268 [17:31<45:34,  1.16s/it]

 28%|██▊       | 908/3268 [17:32<45:34,  1.16s/it]

 28%|██▊       | 909/3268 [17:33<45:33,  1.16s/it]

 28%|██▊       | 910/3268 [17:34<45:32,  1.16s/it]

 28%|██▊       | 911/3268 [17:35<45:32,  1.16s/it]

 28%|██▊       | 912/3268 [17:36<45:31,  1.16s/it]

 28%|██▊       | 913/3268 [17:37<45:27,  1.16s/it]

 28%|██▊       | 914/3268 [17:39<45:26,  1.16s/it]

 28%|██▊       | 915/3268 [17:40<45:23,  1.16s/it]

 28%|██▊       | 916/3268 [17:41<45:23,  1.16s/it]

 28%|██▊       | 917/3268 [17:42<45:22,  1.16s/it]

 28%|██▊       | 918/3268 [17:43<45:23,  1.16s/it]

 28%|██▊       | 919/3268 [17:44<45:23,  1.16s/it]

 28%|██▊       | 920/3268 [17:46<45:23,  1.16s/it]

 28%|██▊       | 921/3268 [17:47<45:22,  1.16s/it]

 28%|██▊       | 922/3268 [17:48<45:19,  1.16s/it]

 28%|██▊       | 923/3268 [17:49<45:16,  1.16s/it]

 28%|██▊       | 924/3268 [17:50<45:16,  1.16s/it]

 28%|██▊       | 925/3268 [17:51<45:14,  1.16s/it]

 28%|██▊       | 926/3268 [17:53<45:12,  1.16s/it]

 28%|██▊       | 927/3268 [17:54<45:14,  1.16s/it]

 28%|██▊       | 928/3268 [17:55<45:13,  1.16s/it]

 28%|██▊       | 929/3268 [17:56<45:12,  1.16s/it]

 28%|██▊       | 930/3268 [17:57<45:10,  1.16s/it]

 28%|██▊       | 931/3268 [17:58<45:08,  1.16s/it]

 29%|██▊       | 932/3268 [17:59<45:07,  1.16s/it]

 29%|██▊       | 933/3268 [18:01<45:04,  1.16s/it]

 29%|██▊       | 934/3268 [18:02<45:03,  1.16s/it]

 29%|██▊       | 935/3268 [18:03<45:00,  1.16s/it]

 29%|██▊       | 936/3268 [18:04<45:02,  1.16s/it]

 29%|██▊       | 937/3268 [18:05<45:01,  1.16s/it]

 29%|██▊       | 938/3268 [18:06<45:00,  1.16s/it]

 29%|██▊       | 939/3268 [18:08<45:00,  1.16s/it]

 29%|██▉       | 940/3268 [18:09<45:01,  1.16s/it]

 29%|██▉       | 941/3268 [18:10<44:58,  1.16s/it]

 29%|██▉       | 942/3268 [18:11<44:55,  1.16s/it]

 29%|██▉       | 943/3268 [18:12<44:54,  1.16s/it]

 29%|██▉       | 944/3268 [18:13<44:50,  1.16s/it]

 29%|██▉       | 945/3268 [18:15<44:49,  1.16s/it]

 29%|██▉       | 946/3268 [18:16<44:47,  1.16s/it]

 29%|██▉       | 947/3268 [18:17<44:46,  1.16s/it]

 29%|██▉       | 948/3268 [18:18<44:44,  1.16s/it]

 29%|██▉       | 949/3268 [18:19<44:44,  1.16s/it]

 29%|██▉       | 950/3268 [18:20<44:43,  1.16s/it]

 29%|██▉       | 951/3268 [18:21<44:44,  1.16s/it]

 29%|██▉       | 952/3268 [18:23<44:43,  1.16s/it]

 29%|██▉       | 953/3268 [18:24<44:42,  1.16s/it]

 29%|██▉       | 954/3268 [18:25<44:39,  1.16s/it]

 29%|██▉       | 955/3268 [18:26<44:38,  1.16s/it]

 29%|██▉       | 956/3268 [18:27<44:37,  1.16s/it]

 29%|██▉       | 957/3268 [18:28<44:34,  1.16s/it]

 29%|██▉       | 958/3268 [18:30<44:33,  1.16s/it]

 29%|██▉       | 959/3268 [18:31<44:30,  1.16s/it]

 29%|██▉       | 960/3268 [18:32<44:28,  1.16s/it]

 29%|██▉       | 961/3268 [18:33<44:28,  1.16s/it]

 29%|██▉       | 962/3268 [18:34<44:30,  1.16s/it]

 29%|██▉       | 963/3268 [18:35<44:31,  1.16s/it]

 29%|██▉       | 964/3268 [18:37<44:31,  1.16s/it]

 30%|██▉       | 965/3268 [18:38<44:27,  1.16s/it]

 30%|██▉       | 966/3268 [18:39<44:26,  1.16s/it]

 30%|██▉       | 967/3268 [18:40<44:25,  1.16s/it]

 30%|██▉       | 968/3268 [18:41<44:21,  1.16s/it]

 30%|██▉       | 969/3268 [18:42<44:24,  1.16s/it]

 30%|██▉       | 970/3268 [18:43<44:23,  1.16s/it]

 30%|██▉       | 971/3268 [18:45<44:21,  1.16s/it]

 30%|██▉       | 972/3268 [18:46<44:17,  1.16s/it]

 30%|██▉       | 973/3268 [18:47<44:18,  1.16s/it]

 30%|██▉       | 974/3268 [18:48<44:15,  1.16s/it]

 30%|██▉       | 975/3268 [18:49<44:16,  1.16s/it]

 30%|██▉       | 976/3268 [18:50<44:17,  1.16s/it]

 30%|██▉       | 977/3268 [18:52<44:12,  1.16s/it]

 30%|██▉       | 978/3268 [18:53<44:11,  1.16s/it]

 30%|██▉       | 979/3268 [18:54<44:11,  1.16s/it]

 30%|██▉       | 980/3268 [18:55<44:10,  1.16s/it]

 30%|███       | 981/3268 [18:56<44:11,  1.16s/it]

 30%|███       | 982/3268 [18:57<44:11,  1.16s/it]

 30%|███       | 983/3268 [18:59<44:11,  1.16s/it]

 30%|███       | 984/3268 [19:00<44:07,  1.16s/it]

 30%|███       | 985/3268 [19:01<44:08,  1.16s/it]

 30%|███       | 986/3268 [19:02<44:07,  1.16s/it]

 30%|███       | 987/3268 [19:03<44:02,  1.16s/it]

 30%|███       | 988/3268 [19:04<44:01,  1.16s/it]

 30%|███       | 989/3268 [19:06<44:01,  1.16s/it]

 30%|███       | 990/3268 [19:07<44:02,  1.16s/it]

 30%|███       | 991/3268 [19:08<44:00,  1.16s/it]

 30%|███       | 992/3268 [19:09<43:56,  1.16s/it]

 30%|███       | 993/3268 [19:10<43:58,  1.16s/it]

 30%|███       | 994/3268 [19:11<43:56,  1.16s/it]

 30%|███       | 995/3268 [19:12<43:58,  1.16s/it]

 30%|███       | 996/3268 [19:14<43:56,  1.16s/it]

 31%|███       | 997/3268 [19:15<43:53,  1.16s/it]

 31%|███       | 998/3268 [19:16<43:50,  1.16s/it]

 31%|███       | 999/3268 [19:17<43:50,  1.16s/it]

 31%|███       | 1000/3268 [19:18<43:47,  1.16s/it]

 31%|███       | 1001/3268 [19:19<43:45,  1.16s/it]

 31%|███       | 1002/3268 [19:21<43:44,  1.16s/it]

 31%|███       | 1003/3268 [19:22<43:42,  1.16s/it]

 31%|███       | 1004/3268 [19:23<43:39,  1.16s/it]

 31%|███       | 1005/3268 [19:24<43:40,  1.16s/it]

 31%|███       | 1006/3268 [19:25<43:40,  1.16s/it]

 31%|███       | 1007/3268 [19:26<43:38,  1.16s/it]

 31%|███       | 1008/3268 [19:28<43:36,  1.16s/it]

 31%|███       | 1009/3268 [19:29<43:37,  1.16s/it]

 31%|███       | 1010/3268 [19:30<43:33,  1.16s/it]

 31%|███       | 1011/3268 [19:31<43:31,  1.16s/it]

 31%|███       | 1012/3268 [19:32<43:31,  1.16s/it]

 31%|███       | 1013/3268 [19:33<43:31,  1.16s/it]

 31%|███       | 1014/3268 [19:34<43:32,  1.16s/it]

 31%|███       | 1015/3268 [19:36<43:33,  1.16s/it]

 31%|███       | 1016/3268 [19:37<43:33,  1.16s/it]

 31%|███       | 1017/3268 [19:38<43:31,  1.16s/it]

 31%|███       | 1018/3268 [19:39<43:29,  1.16s/it]

 31%|███       | 1019/3268 [19:40<43:29,  1.16s/it]

 31%|███       | 1020/3268 [19:41<43:29,  1.16s/it]

 31%|███       | 1021/3268 [19:43<43:26,  1.16s/it]

 31%|███▏      | 1022/3268 [19:44<43:24,  1.16s/it]

 31%|███▏      | 1023/3268 [19:45<43:23,  1.16s/it]

 31%|███▏      | 1024/3268 [19:46<43:19,  1.16s/it]

 31%|███▏      | 1025/3268 [19:47<43:19,  1.16s/it]

 31%|███▏      | 1026/3268 [19:48<43:19,  1.16s/it]

 31%|███▏      | 1027/3268 [19:50<43:22,  1.16s/it]

 31%|███▏      | 1028/3268 [19:51<43:20,  1.16s/it]

 31%|███▏      | 1029/3268 [19:52<43:18,  1.16s/it]

 32%|███▏      | 1030/3268 [19:53<43:16,  1.16s/it]

 32%|███▏      | 1031/3268 [19:54<43:16,  1.16s/it]

 32%|███▏      | 1032/3268 [19:55<43:16,  1.16s/it]

 32%|███▏      | 1033/3268 [19:57<43:13,  1.16s/it]

 32%|███▏      | 1034/3268 [19:58<43:09,  1.16s/it]

 32%|███▏      | 1035/3268 [19:59<43:08,  1.16s/it]

 32%|███▏      | 1036/3268 [20:00<43:09,  1.16s/it]

 32%|███▏      | 1037/3268 [20:01<43:04,  1.16s/it]

 32%|███▏      | 1038/3268 [20:02<43:04,  1.16s/it]

 32%|███▏      | 1039/3268 [20:03<43:04,  1.16s/it]

 32%|███▏      | 1040/3268 [20:05<43:04,  1.16s/it]

 32%|███▏      | 1041/3268 [20:06<42:59,  1.16s/it]

 32%|███▏      | 1042/3268 [20:07<42:59,  1.16s/it]

 32%|███▏      | 1043/3268 [20:08<42:57,  1.16s/it]

 32%|███▏      | 1044/3268 [20:09<42:56,  1.16s/it]

 32%|███▏      | 1045/3268 [20:10<42:54,  1.16s/it]

 32%|███▏      | 1046/3268 [20:12<42:57,  1.16s/it]

 32%|███▏      | 1047/3268 [20:13<42:55,  1.16s/it]

 32%|███▏      | 1048/3268 [20:14<42:55,  1.16s/it]

 32%|███▏      | 1049/3268 [20:15<42:50,  1.16s/it]

 32%|███▏      | 1050/3268 [20:16<42:57,  1.16s/it]

 32%|███▏      | 1051/3268 [20:17<42:52,  1.16s/it]

 32%|███▏      | 1052/3268 [20:19<42:52,  1.16s/it]

 32%|███▏      | 1053/3268 [20:20<42:48,  1.16s/it]

 32%|███▏      | 1054/3268 [20:21<42:50,  1.16s/it]

 32%|███▏      | 1055/3268 [20:22<42:52,  1.16s/it]

 32%|███▏      | 1056/3268 [20:23<42:49,  1.16s/it]

 32%|███▏      | 1057/3268 [20:24<42:45,  1.16s/it]

 32%|███▏      | 1058/3268 [20:26<42:47,  1.16s/it]

 32%|███▏      | 1059/3268 [20:27<42:43,  1.16s/it]

 32%|███▏      | 1060/3268 [20:28<42:38,  1.16s/it]

 32%|███▏      | 1061/3268 [20:29<42:38,  1.16s/it]

 32%|███▏      | 1062/3268 [20:30<42:37,  1.16s/it]

 33%|███▎      | 1063/3268 [20:31<42:36,  1.16s/it]

 33%|███▎      | 1064/3268 [20:32<42:36,  1.16s/it]

 33%|███▎      | 1065/3268 [20:34<42:36,  1.16s/it]

 33%|███▎      | 1066/3268 [20:35<42:35,  1.16s/it]

 33%|███▎      | 1067/3268 [20:36<42:32,  1.16s/it]

 33%|███▎      | 1068/3268 [20:37<42:32,  1.16s/it]

 33%|███▎      | 1069/3268 [20:38<42:30,  1.16s/it]

 33%|███▎      | 1070/3268 [20:39<42:26,  1.16s/it]

 33%|███▎      | 1071/3268 [20:41<42:25,  1.16s/it]

 33%|███▎      | 1072/3268 [20:42<42:27,  1.16s/it]

 33%|███▎      | 1073/3268 [20:43<42:29,  1.16s/it]

 33%|███▎      | 1074/3268 [20:44<42:26,  1.16s/it]

 33%|███▎      | 1075/3268 [20:45<42:23,  1.16s/it]

 33%|███▎      | 1076/3268 [20:46<42:24,  1.16s/it]

 33%|███▎      | 1077/3268 [20:48<42:26,  1.16s/it]

 33%|███▎      | 1078/3268 [20:49<42:23,  1.16s/it]

 33%|███▎      | 1079/3268 [20:50<42:19,  1.16s/it]

 33%|███▎      | 1080/3268 [20:51<42:17,  1.16s/it]

 33%|███▎      | 1081/3268 [20:52<42:14,  1.16s/it]

 33%|███▎      | 1082/3268 [20:53<42:12,  1.16s/it]

 33%|███▎      | 1083/3268 [20:55<42:14,  1.16s/it]

 33%|███▎      | 1084/3268 [20:56<42:16,  1.16s/it]

 33%|███▎      | 1085/3268 [20:57<42:15,  1.16s/it]

 33%|███▎      | 1086/3268 [20:58<42:16,  1.16s/it]

 33%|███▎      | 1087/3268 [20:59<42:15,  1.16s/it]

 33%|███▎      | 1088/3268 [21:00<42:11,  1.16s/it]

 33%|███▎      | 1089/3268 [21:01<42:07,  1.16s/it]

 33%|███▎      | 1090/3268 [21:03<42:07,  1.16s/it]

 33%|███▎      | 1091/3268 [21:04<42:06,  1.16s/it]

 33%|███▎      | 1092/3268 [21:05<42:01,  1.16s/it]

 33%|███▎      | 1093/3268 [21:06<42:01,  1.16s/it]

 33%|███▎      | 1094/3268 [21:07<41:59,  1.16s/it]

 34%|███▎      | 1095/3268 [21:08<42:00,  1.16s/it]

 34%|███▎      | 1096/3268 [21:10<42:00,  1.16s/it]

 34%|███▎      | 1097/3268 [21:11<41:59,  1.16s/it]

 34%|███▎      | 1098/3268 [21:12<41:58,  1.16s/it]

 34%|███▎      | 1099/3268 [21:13<41:57,  1.16s/it]

 34%|███▎      | 1100/3268 [21:14<41:57,  1.16s/it]

 34%|███▎      | 1101/3268 [21:15<41:56,  1.16s/it]

 34%|███▎      | 1102/3268 [21:17<41:56,  1.16s/it]

 34%|███▍      | 1103/3268 [21:18<41:53,  1.16s/it]

 34%|███▍      | 1104/3268 [21:19<41:51,  1.16s/it]

 34%|███▍      | 1105/3268 [21:20<41:50,  1.16s/it]

 34%|███▍      | 1106/3268 [21:21<41:51,  1.16s/it]

 34%|███▍      | 1107/3268 [21:22<41:51,  1.16s/it]

 34%|███▍      | 1108/3268 [21:24<41:46,  1.16s/it]

 34%|███▍      | 1109/3268 [21:25<41:47,  1.16s/it]

 34%|███▍      | 1110/3268 [21:26<41:48,  1.16s/it]

 34%|███▍      | 1111/3268 [21:27<41:47,  1.16s/it]

 34%|███▍      | 1112/3268 [21:28<41:47,  1.16s/it]

 34%|███▍      | 1113/3268 [21:29<41:44,  1.16s/it]

 34%|███▍      | 1114/3268 [21:31<41:42,  1.16s/it]

 34%|███▍      | 1115/3268 [21:32<41:42,  1.16s/it]

 34%|███▍      | 1116/3268 [21:33<41:40,  1.16s/it]

 34%|███▍      | 1117/3268 [21:34<41:36,  1.16s/it]

 34%|███▍      | 1118/3268 [21:35<41:37,  1.16s/it]

 34%|███▍      | 1119/3268 [21:36<41:35,  1.16s/it]

 34%|███▍      | 1120/3268 [21:37<41:34,  1.16s/it]

 34%|███▍      | 1121/3268 [21:39<41:31,  1.16s/it]

 34%|███▍      | 1122/3268 [21:40<41:29,  1.16s/it]

 34%|███▍      | 1123/3268 [21:41<41:31,  1.16s/it]

 34%|███▍      | 1124/3268 [21:42<41:29,  1.16s/it]

 34%|███▍      | 1125/3268 [21:43<41:27,  1.16s/it]

 34%|███▍      | 1126/3268 [21:44<41:26,  1.16s/it]

 34%|███▍      | 1127/3268 [21:46<41:23,  1.16s/it]

 35%|███▍      | 1128/3268 [21:47<41:25,  1.16s/it]

 35%|███▍      | 1129/3268 [21:48<41:23,  1.16s/it]

 35%|███▍      | 1130/3268 [21:49<41:20,  1.16s/it]

 35%|███▍      | 1131/3268 [21:50<41:16,  1.16s/it]

 35%|███▍      | 1132/3268 [21:51<41:15,  1.16s/it]

 35%|███▍      | 1133/3268 [21:53<41:12,  1.16s/it]

 35%|███▍      | 1134/3268 [21:54<41:12,  1.16s/it]

 35%|███▍      | 1135/3268 [21:55<41:12,  1.16s/it]

 35%|███▍      | 1136/3268 [21:56<41:12,  1.16s/it]

 35%|███▍      | 1137/3268 [21:57<41:12,  1.16s/it]

 35%|███▍      | 1138/3268 [21:58<41:11,  1.16s/it]

 35%|███▍      | 1139/3268 [22:00<41:10,  1.16s/it]

 35%|███▍      | 1140/3268 [22:01<41:10,  1.16s/it]

 35%|███▍      | 1141/3268 [22:02<41:08,  1.16s/it]

 35%|███▍      | 1142/3268 [22:03<41:06,  1.16s/it]

 35%|███▍      | 1143/3268 [22:04<41:04,  1.16s/it]

 35%|███▌      | 1144/3268 [22:05<41:04,  1.16s/it]

 35%|███▌      | 1145/3268 [22:06<41:02,  1.16s/it]

 35%|███▌      | 1146/3268 [22:08<41:04,  1.16s/it]

 35%|███▌      | 1147/3268 [22:09<41:05,  1.16s/it]

 35%|███▌      | 1148/3268 [22:10<41:06,  1.16s/it]

 35%|███▌      | 1149/3268 [22:11<41:05,  1.16s/it]

 35%|███▌      | 1150/3268 [22:12<41:05,  1.16s/it]

 35%|███▌      | 1151/3268 [22:13<41:01,  1.16s/it]

 35%|███▌      | 1152/3268 [22:15<40:59,  1.16s/it]

 35%|███▌      | 1153/3268 [22:16<40:58,  1.16s/it]

 35%|███▌      | 1154/3268 [22:17<40:57,  1.16s/it]

 35%|███▌      | 1155/3268 [22:18<40:56,  1.16s/it]

 35%|███▌      | 1156/3268 [22:19<40:53,  1.16s/it]

 35%|███▌      | 1157/3268 [22:20<40:50,  1.16s/it]

 35%|███▌      | 1158/3268 [22:22<40:49,  1.16s/it]

 35%|███▌      | 1159/3268 [22:23<40:49,  1.16s/it]

 35%|███▌      | 1160/3268 [22:24<40:47,  1.16s/it]

 36%|███▌      | 1161/3268 [22:25<40:47,  1.16s/it]

 36%|███▌      | 1162/3268 [22:26<40:46,  1.16s/it]

 36%|███▌      | 1163/3268 [22:27<40:43,  1.16s/it]

 36%|███▌      | 1164/3268 [22:29<40:41,  1.16s/it]

 36%|███▌      | 1165/3268 [22:30<40:40,  1.16s/it]

 36%|███▌      | 1166/3268 [22:31<40:38,  1.16s/it]

 36%|███▌      | 1167/3268 [22:32<40:37,  1.16s/it]

 36%|███▌      | 1168/3268 [22:33<40:35,  1.16s/it]

 36%|███▌      | 1169/3268 [22:34<40:36,  1.16s/it]

 36%|███▌      | 1170/3268 [22:36<40:36,  1.16s/it]

 36%|███▌      | 1171/3268 [22:37<40:35,  1.16s/it]

 36%|███▌      | 1172/3268 [22:38<40:34,  1.16s/it]

 36%|███▌      | 1173/3268 [22:39<40:30,  1.16s/it]

 36%|███▌      | 1174/3268 [22:40<40:26,  1.16s/it]

 36%|███▌      | 1175/3268 [22:41<40:27,  1.16s/it]

 36%|███▌      | 1176/3268 [22:42<40:24,  1.16s/it]

 36%|███▌      | 1177/3268 [22:44<40:24,  1.16s/it]

 36%|███▌      | 1178/3268 [22:45<40:22,  1.16s/it]

 36%|███▌      | 1179/3268 [22:46<40:20,  1.16s/it]

 36%|███▌      | 1180/3268 [22:47<40:19,  1.16s/it]

 36%|███▌      | 1181/3268 [22:48<40:20,  1.16s/it]

 36%|███▌      | 1182/3268 [22:49<40:15,  1.16s/it]

 36%|███▌      | 1183/3268 [22:51<40:13,  1.16s/it]

 36%|███▌      | 1184/3268 [22:52<40:15,  1.16s/it]

 36%|███▋      | 1185/3268 [22:53<40:16,  1.16s/it]

 36%|███▋      | 1186/3268 [22:54<40:14,  1.16s/it]

 36%|███▋      | 1187/3268 [22:55<40:13,  1.16s/it]

 36%|███▋      | 1188/3268 [22:56<40:12,  1.16s/it]

 36%|███▋      | 1189/3268 [22:58<40:12,  1.16s/it]

 36%|███▋      | 1190/3268 [22:59<40:11,  1.16s/it]

 36%|███▋      | 1191/3268 [23:00<40:08,  1.16s/it]

 36%|███▋      | 1192/3268 [23:01<40:06,  1.16s/it]

 37%|███▋      | 1193/3268 [23:02<40:05,  1.16s/it]

 37%|███▋      | 1194/3268 [23:03<40:04,  1.16s/it]

 37%|███▋      | 1195/3268 [23:05<40:02,  1.16s/it]

 37%|███▋      | 1196/3268 [23:06<40:03,  1.16s/it]

 37%|███▋      | 1197/3268 [23:07<40:04,  1.16s/it]

 37%|███▋      | 1198/3268 [23:08<40:02,  1.16s/it]

 37%|███▋      | 1199/3268 [23:09<40:02,  1.16s/it]

 37%|███▋      | 1200/3268 [23:10<40:01,  1.16s/it]

 37%|███▋      | 1201/3268 [23:11<40:00,  1.16s/it]

 37%|███▋      | 1202/3268 [23:13<40:00,  1.16s/it]

 37%|███▋      | 1203/3268 [23:14<39:59,  1.16s/it]

 37%|███▋      | 1204/3268 [23:15<39:58,  1.16s/it]

 37%|███▋      | 1205/3268 [23:16<39:57,  1.16s/it]

 37%|███▋      | 1206/3268 [23:17<39:52,  1.16s/it]

 37%|███▋      | 1207/3268 [23:18<39:51,  1.16s/it]

 37%|███▋      | 1208/3268 [23:20<39:54,  1.16s/it]

 37%|███▋      | 1209/3268 [23:21<39:52,  1.16s/it]

 37%|███▋      | 1210/3268 [23:22<39:51,  1.16s/it]

 37%|███▋      | 1211/3268 [23:23<39:53,  1.16s/it]

 37%|███▋      | 1212/3268 [23:24<39:50,  1.16s/it]

 37%|███▋      | 1213/3268 [23:25<39:46,  1.16s/it]

 37%|███▋      | 1214/3268 [23:27<39:45,  1.16s/it]

 37%|███▋      | 1215/3268 [23:28<39:46,  1.16s/it]

 37%|███▋      | 1216/3268 [23:29<39:45,  1.16s/it]

 37%|███▋      | 1217/3268 [23:30<39:42,  1.16s/it]

 37%|███▋      | 1218/3268 [23:31<39:39,  1.16s/it]

 37%|███▋      | 1219/3268 [23:32<39:37,  1.16s/it]

 37%|███▋      | 1220/3268 [23:34<39:35,  1.16s/it]

 37%|███▋      | 1221/3268 [23:35<39:35,  1.16s/it]

 37%|███▋      | 1222/3268 [23:36<39:35,  1.16s/it]

 37%|███▋      | 1223/3268 [23:37<39:35,  1.16s/it]

 37%|███▋      | 1224/3268 [23:38<39:34,  1.16s/it]

 37%|███▋      | 1225/3268 [23:39<39:34,  1.16s/it]

 38%|███▊      | 1226/3268 [23:41<39:33,  1.16s/it]

 38%|███▊      | 1227/3268 [23:42<39:30,  1.16s/it]

 38%|███▊      | 1228/3268 [23:43<39:28,  1.16s/it]

 38%|███▊      | 1229/3268 [23:44<39:30,  1.16s/it]

 38%|███▊      | 1230/3268 [23:45<39:30,  1.16s/it]

 38%|███▊      | 1231/3268 [23:46<39:29,  1.16s/it]

 38%|███▊      | 1232/3268 [23:48<39:28,  1.16s/it]

 38%|███▊      | 1233/3268 [23:49<39:27,  1.16s/it]

 38%|███▊      | 1234/3268 [23:50<39:26,  1.16s/it]

 38%|███▊      | 1235/3268 [23:51<39:22,  1.16s/it]

 38%|███▊      | 1236/3268 [23:52<39:19,  1.16s/it]

 38%|███▊      | 1237/3268 [23:53<39:17,  1.16s/it]

 38%|███▊      | 1238/3268 [23:54<39:19,  1.16s/it]

 38%|███▊      | 1239/3268 [23:56<39:18,  1.16s/it]

 38%|███▊      | 1240/3268 [23:57<39:17,  1.16s/it]

 38%|███▊      | 1241/3268 [23:58<39:15,  1.16s/it]

 38%|███▊      | 1242/3268 [23:59<39:12,  1.16s/it]

 38%|███▊      | 1243/3268 [24:00<39:11,  1.16s/it]

 38%|███▊      | 1244/3268 [24:01<39:09,  1.16s/it]

 38%|███▊      | 1245/3268 [24:03<39:05,  1.16s/it]

 38%|███▊      | 1246/3268 [24:04<39:02,  1.16s/it]

 38%|███▊      | 1247/3268 [24:05<39:01,  1.16s/it]

 38%|███▊      | 1248/3268 [24:06<39:01,  1.16s/it]

 38%|███▊      | 1249/3268 [24:07<39:01,  1.16s/it]

 38%|███▊      | 1250/3268 [24:08<39:00,  1.16s/it]

 38%|███▊      | 1251/3268 [24:10<38:59,  1.16s/it]

logging
logging the anndata

 38%|███▊      | 1252/3268 [24:11<39:57,  1.19s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 38%|███▊      | 1253/3268 [24:12<39:35,  1.18s/it]

 38%|███▊      | 1254/3268 [24:13<39:18,  1.17s/it]

 38%|███▊      | 1255/3268 [24:14<39:07,  1.17s/it]

 38%|███▊      | 1256/3268 [24:15<39:00,  1.16s/it]

 38%|███▊      | 1257/3268 [24:17<38:56,  1.16s/it]

 38%|███▊      | 1258/3268 [24:18<38:51,  1.16s/it]

 39%|███▊      | 1259/3268 [24:19<38:49,  1.16s/it]

 39%|███▊      | 1260/3268 [24:20<38:44,  1.16s/it]

 39%|███▊      | 1261/3268 [24:21<38:40,  1.16s/it]

 39%|███▊      | 1262/3268 [24:22<38:37,  1.16s/it]

 39%|███▊      | 1263/3268 [24:24<38:35,  1.15s/it]

 39%|███▊      | 1264/3268 [24:25<38:37,  1.16s/it]

 39%|███▊      | 1265/3268 [24:26<38:34,  1.16s/it]

 39%|███▊      | 1266/3268 [24:27<38:34,  1.16s/it]

 39%|███▉      | 1267/3268 [24:28<38:34,  1.16s/it]

 39%|███▉      | 1268/3268 [24:29<38:31,  1.16s/it]

 39%|███▉      | 1269/3268 [24:30<38:31,  1.16s/it]

 39%|███▉      | 1270/3268 [24:32<38:29,  1.16s/it]

 39%|███▉      | 1271/3268 [24:33<38:29,  1.16s/it]

 39%|███▉      | 1272/3268 [24:34<38:25,  1.16s/it]

 39%|███▉      | 1273/3268 [24:35<38:24,  1.16s/it]

 39%|███▉      | 1274/3268 [24:36<38:24,  1.16s/it]

 39%|███▉      | 1275/3268 [24:37<38:21,  1.15s/it]

 39%|███▉      | 1276/3268 [24:39<38:22,  1.16s/it]

 39%|███▉      | 1277/3268 [24:40<38:21,  1.16s/it]

 39%|███▉      | 1278/3268 [24:41<38:17,  1.15s/it]

 39%|███▉      | 1279/3268 [24:42<38:16,  1.15s/it]

 39%|███▉      | 1280/3268 [24:43<38:13,  1.15s/it]

 39%|███▉      | 1281/3268 [24:44<38:11,  1.15s/it]

 39%|███▉      | 1282/3268 [24:45<38:11,  1.15s/it]

 39%|███▉      | 1283/3268 [24:47<38:13,  1.16s/it]

 39%|███▉      | 1284/3268 [24:48<38:12,  1.16s/it]

 39%|███▉      | 1285/3268 [24:49<38:08,  1.15s/it]

 39%|███▉      | 1286/3268 [24:50<38:07,  1.15s/it]

 39%|███▉      | 1287/3268 [24:51<38:11,  1.16s/it]

 39%|███▉      | 1288/3268 [24:52<38:11,  1.16s/it]

 39%|███▉      | 1289/3268 [24:54<38:10,  1.16s/it]

 39%|███▉      | 1290/3268 [24:55<38:05,  1.16s/it]

 40%|███▉      | 1291/3268 [24:56<38:03,  1.16s/it]

 40%|███▉      | 1292/3268 [24:57<38:02,  1.16s/it]

 40%|███▉      | 1293/3268 [24:58<38:03,  1.16s/it]

 40%|███▉      | 1294/3268 [24:59<38:02,  1.16s/it]

 40%|███▉      | 1295/3268 [25:00<38:00,  1.16s/it]

 40%|███▉      | 1296/3268 [25:02<37:58,  1.16s/it]

 40%|███▉      | 1297/3268 [25:03<37:57,  1.16s/it]

 40%|███▉      | 1298/3268 [25:04<37:56,  1.16s/it]

 40%|███▉      | 1299/3268 [25:05<37:52,  1.15s/it]

 40%|███▉      | 1300/3268 [25:06<37:52,  1.15s/it]

 40%|███▉      | 1301/3268 [25:07<37:52,  1.16s/it]

 40%|███▉      | 1302/3268 [25:09<37:53,  1.16s/it]

 40%|███▉      | 1303/3268 [25:10<37:53,  1.16s/it]

 40%|███▉      | 1304/3268 [25:11<37:53,  1.16s/it]

 40%|███▉      | 1305/3268 [25:12<37:50,  1.16s/it]

 40%|███▉      | 1306/3268 [25:13<37:48,  1.16s/it]

 40%|███▉      | 1307/3268 [25:14<37:47,  1.16s/it]

 40%|████      | 1308/3268 [25:16<37:46,  1.16s/it]

 40%|████      | 1309/3268 [25:17<37:43,  1.16s/it]

 40%|████      | 1310/3268 [25:18<37:41,  1.15s/it]

 40%|████      | 1311/3268 [25:19<37:39,  1.15s/it]

 40%|████      | 1312/3268 [25:20<37:39,  1.16s/it]

 40%|████      | 1313/3268 [25:21<37:40,  1.16s/it]

 40%|████      | 1314/3268 [25:22<37:39,  1.16s/it]

 40%|████      | 1315/3268 [25:24<37:37,  1.16s/it]

 40%|████      | 1316/3268 [25:25<37:34,  1.16s/it]

 40%|████      | 1317/3268 [25:26<37:34,  1.16s/it]

 40%|████      | 1318/3268 [25:27<37:33,  1.16s/it]

 40%|████      | 1319/3268 [25:28<37:32,  1.16s/it]

 40%|████      | 1320/3268 [25:29<37:31,  1.16s/it]

 40%|████      | 1321/3268 [25:31<37:29,  1.16s/it]

 40%|████      | 1322/3268 [25:32<37:26,  1.15s/it]

 40%|████      | 1323/3268 [25:33<37:25,  1.15s/it]

 41%|████      | 1324/3268 [25:34<37:22,  1.15s/it]

 41%|████      | 1325/3268 [25:35<37:20,  1.15s/it]

 41%|████      | 1326/3268 [25:36<37:19,  1.15s/it]

 41%|████      | 1327/3268 [25:37<37:21,  1.15s/it]

 41%|████      | 1328/3268 [25:39<37:22,  1.16s/it]

 41%|████      | 1329/3268 [25:40<37:21,  1.16s/it]

 41%|████      | 1330/3268 [25:41<37:21,  1.16s/it]

 41%|████      | 1331/3268 [25:42<37:19,  1.16s/it]

 41%|████      | 1332/3268 [25:43<37:16,  1.16s/it]

 41%|████      | 1333/3268 [25:44<37:14,  1.15s/it]

 41%|████      | 1334/3268 [25:46<37:14,  1.16s/it]

 41%|████      | 1335/3268 [25:47<37:16,  1.16s/it]

 41%|████      | 1336/3268 [25:48<37:14,  1.16s/it]

 41%|████      | 1337/3268 [25:49<37:13,  1.16s/it]

 41%|████      | 1338/3268 [25:50<37:12,  1.16s/it]

 41%|████      | 1339/3268 [25:51<37:10,  1.16s/it]

 41%|████      | 1340/3268 [25:52<37:07,  1.16s/it]

 41%|████      | 1341/3268 [25:54<37:07,  1.16s/it]

 41%|████      | 1342/3268 [25:55<37:06,  1.16s/it]

 41%|████      | 1343/3268 [25:56<37:07,  1.16s/it]

 41%|████      | 1344/3268 [25:57<37:07,  1.16s/it]

 41%|████      | 1345/3268 [25:58<37:09,  1.16s/it]

 41%|████      | 1346/3268 [25:59<37:08,  1.16s/it]

 41%|████      | 1347/3268 [26:01<37:06,  1.16s/it]

 41%|████      | 1348/3268 [26:02<37:04,  1.16s/it]

 41%|████▏     | 1349/3268 [26:03<37:03,  1.16s/it]

 41%|████▏     | 1350/3268 [26:04<37:02,  1.16s/it]

 41%|████▏     | 1351/3268 [26:05<37:00,  1.16s/it]

 41%|████▏     | 1352/3268 [26:06<36:57,  1.16s/it]

 41%|████▏     | 1353/3268 [26:08<36:53,  1.16s/it]

 41%|████▏     | 1354/3268 [26:09<36:51,  1.16s/it]

 41%|████▏     | 1355/3268 [26:10<36:50,  1.16s/it]

 41%|████▏     | 1356/3268 [26:11<36:50,  1.16s/it]

 42%|████▏     | 1357/3268 [26:12<36:48,  1.16s/it]

 42%|████▏     | 1358/3268 [26:13<36:48,  1.16s/it]

 42%|████▏     | 1359/3268 [26:14<36:45,  1.16s/it]

 42%|████▏     | 1360/3268 [26:16<36:44,  1.16s/it]

 42%|████▏     | 1361/3268 [26:17<36:41,  1.15s/it]

 42%|████▏     | 1362/3268 [26:18<36:41,  1.16s/it]

 42%|████▏     | 1363/3268 [26:19<36:39,  1.15s/it]

 42%|████▏     | 1364/3268 [26:20<36:40,  1.16s/it]

 42%|████▏     | 1365/3268 [26:21<36:40,  1.16s/it]

 42%|████▏     | 1366/3268 [26:23<36:39,  1.16s/it]

 42%|████▏     | 1367/3268 [26:24<36:37,  1.16s/it]

 42%|████▏     | 1368/3268 [26:25<36:37,  1.16s/it]

 42%|████▏     | 1369/3268 [26:26<36:35,  1.16s/it]

 42%|████▏     | 1370/3268 [26:27<36:35,  1.16s/it]

 42%|████▏     | 1371/3268 [26:28<36:32,  1.16s/it]

 42%|████▏     | 1372/3268 [26:30<36:31,  1.16s/it]

 42%|████▏     | 1373/3268 [26:31<36:30,  1.16s/it]

 42%|████▏     | 1374/3268 [26:32<36:29,  1.16s/it]

 42%|████▏     | 1375/3268 [26:33<36:30,  1.16s/it]

 42%|████▏     | 1376/3268 [26:34<36:29,  1.16s/it]

 42%|████▏     | 1377/3268 [26:35<36:29,  1.16s/it]

 42%|████▏     | 1378/3268 [26:36<36:27,  1.16s/it]

 42%|████▏     | 1379/3268 [26:38<36:24,  1.16s/it]

 42%|████▏     | 1380/3268 [26:39<36:22,  1.16s/it]

 42%|████▏     | 1381/3268 [26:40<36:19,  1.16s/it]

 42%|████▏     | 1382/3268 [26:41<36:18,  1.16s/it]

 42%|████▏     | 1383/3268 [26:42<36:17,  1.16s/it]

 42%|████▏     | 1384/3268 [26:43<36:17,  1.16s/it]

 42%|████▏     | 1385/3268 [26:45<36:14,  1.15s/it]

 42%|████▏     | 1386/3268 [26:46<36:14,  1.16s/it]

 42%|████▏     | 1387/3268 [26:47<36:13,  1.16s/it]

 42%|████▏     | 1388/3268 [26:48<36:10,  1.15s/it]

 43%|████▎     | 1389/3268 [26:49<36:08,  1.15s/it]

 43%|████▎     | 1390/3268 [26:50<36:10,  1.16s/it]

 43%|████▎     | 1391/3268 [26:51<36:10,  1.16s/it]

 43%|████▎     | 1392/3268 [26:53<36:11,  1.16s/it]

 43%|████▎     | 1393/3268 [26:54<36:08,  1.16s/it]

 43%|████▎     | 1394/3268 [26:55<36:09,  1.16s/it]

 43%|████▎     | 1395/3268 [26:56<36:08,  1.16s/it]

 43%|████▎     | 1396/3268 [26:57<36:05,  1.16s/it]

 43%|████▎     | 1397/3268 [26:58<36:03,  1.16s/it]

 43%|████▎     | 1398/3268 [27:00<36:01,  1.16s/it]

 43%|████▎     | 1399/3268 [27:01<35:58,  1.15s/it]

 43%|████▎     | 1400/3268 [27:02<35:59,  1.16s/it]

 43%|████▎     | 1401/3268 [27:03<35:59,  1.16s/it]

 43%|████▎     | 1402/3268 [27:04<36:01,  1.16s/it]

 43%|████▎     | 1403/3268 [27:05<35:58,  1.16s/it]

 43%|████▎     | 1404/3268 [27:07<35:56,  1.16s/it]

 43%|████▎     | 1405/3268 [27:08<35:56,  1.16s/it]

 43%|████▎     | 1406/3268 [27:09<35:55,  1.16s/it]

 43%|████▎     | 1407/3268 [27:10<35:53,  1.16s/it]

 43%|████▎     | 1408/3268 [27:11<35:52,  1.16s/it]

 43%|████▎     | 1409/3268 [27:12<35:50,  1.16s/it]

 43%|████▎     | 1410/3268 [27:13<35:48,  1.16s/it]

 43%|████▎     | 1411/3268 [27:15<35:46,  1.16s/it]

 43%|████▎     | 1412/3268 [27:16<35:46,  1.16s/it]

 43%|████▎     | 1413/3268 [27:17<35:47,  1.16s/it]

 43%|████▎     | 1414/3268 [27:18<35:45,  1.16s/it]

 43%|████▎     | 1415/3268 [27:19<35:42,  1.16s/it]

 43%|████▎     | 1416/3268 [27:20<35:43,  1.16s/it]

 43%|████▎     | 1417/3268 [27:22<35:40,  1.16s/it]

 43%|████▎     | 1418/3268 [27:23<35:39,  1.16s/it]

 43%|████▎     | 1419/3268 [27:24<35:37,  1.16s/it]

 43%|████▎     | 1420/3268 [27:25<35:37,  1.16s/it]

 43%|████▎     | 1421/3268 [27:26<35:36,  1.16s/it]

 44%|████▎     | 1422/3268 [27:27<35:34,  1.16s/it]

 44%|████▎     | 1423/3268 [27:28<35:36,  1.16s/it]

 44%|████▎     | 1424/3268 [27:30<35:35,  1.16s/it]

 44%|████▎     | 1425/3268 [27:31<35:35,  1.16s/it]

 44%|████▎     | 1426/3268 [27:32<35:31,  1.16s/it]

 44%|████▎     | 1427/3268 [27:33<35:29,  1.16s/it]

 44%|████▎     | 1428/3268 [27:34<35:27,  1.16s/it]

 44%|████▎     | 1429/3268 [27:35<35:25,  1.16s/it]

 44%|████▍     | 1430/3268 [27:37<35:25,  1.16s/it]

 44%|████▍     | 1431/3268 [27:38<35:25,  1.16s/it]

 44%|████▍     | 1432/3268 [27:39<35:22,  1.16s/it]

 44%|████▍     | 1433/3268 [27:40<35:19,  1.16s/it]

 44%|████▍     | 1434/3268 [27:41<35:21,  1.16s/it]

 44%|████▍     | 1435/3268 [27:42<35:19,  1.16s/it]

 44%|████▍     | 1436/3268 [27:44<35:19,  1.16s/it]

 44%|████▍     | 1437/3268 [27:45<35:16,  1.16s/it]

 44%|████▍     | 1438/3268 [27:46<35:15,  1.16s/it]

 44%|████▍     | 1439/3268 [27:47<35:14,  1.16s/it]

 44%|████▍     | 1440/3268 [27:48<35:13,  1.16s/it]

 44%|████▍     | 1441/3268 [27:49<35:12,  1.16s/it]

 44%|████▍     | 1442/3268 [27:50<35:12,  1.16s/it]

 44%|████▍     | 1443/3268 [27:52<35:12,  1.16s/it]

 44%|████▍     | 1444/3268 [27:53<35:10,  1.16s/it]

 44%|████▍     | 1445/3268 [27:54<35:09,  1.16s/it]

 44%|████▍     | 1446/3268 [27:55<35:06,  1.16s/it]

 44%|████▍     | 1447/3268 [27:56<35:04,  1.16s/it]

 44%|████▍     | 1448/3268 [27:57<35:02,  1.16s/it]

 44%|████▍     | 1449/3268 [27:59<35:02,  1.16s/it]

 44%|████▍     | 1450/3268 [28:00<35:03,  1.16s/it]

 44%|████▍     | 1451/3268 [28:01<35:02,  1.16s/it]

 44%|████▍     | 1452/3268 [28:02<35:01,  1.16s/it]

 44%|████▍     | 1453/3268 [28:03<35:01,  1.16s/it]

 44%|████▍     | 1454/3268 [28:04<34:59,  1.16s/it]

 45%|████▍     | 1455/3268 [28:05<34:55,  1.16s/it]

 45%|████▍     | 1456/3268 [28:07<34:54,  1.16s/it]

 45%|████▍     | 1457/3268 [28:08<34:55,  1.16s/it]

 45%|████▍     | 1458/3268 [28:09<34:53,  1.16s/it]

 45%|████▍     | 1459/3268 [28:10<34:56,  1.16s/it]

 45%|████▍     | 1460/3268 [28:11<34:57,  1.16s/it]

 45%|████▍     | 1461/3268 [28:12<34:53,  1.16s/it]

 45%|████▍     | 1462/3268 [28:14<34:53,  1.16s/it]

 45%|████▍     | 1463/3268 [28:15<34:51,  1.16s/it]

 45%|████▍     | 1464/3268 [28:16<34:52,  1.16s/it]

 45%|████▍     | 1465/3268 [28:17<34:49,  1.16s/it]

 45%|████▍     | 1466/3268 [28:18<34:48,  1.16s/it]

 45%|████▍     | 1467/3268 [28:19<34:48,  1.16s/it]

 45%|████▍     | 1468/3268 [28:21<34:46,  1.16s/it]

 45%|████▍     | 1469/3268 [28:22<34:43,  1.16s/it]

 45%|████▍     | 1470/3268 [28:23<34:41,  1.16s/it]

 45%|████▌     | 1471/3268 [28:24<34:41,  1.16s/it]

 45%|████▌     | 1472/3268 [28:25<34:41,  1.16s/it]

 45%|████▌     | 1473/3268 [28:26<34:40,  1.16s/it]

 45%|████▌     | 1474/3268 [28:28<34:37,  1.16s/it]

 45%|████▌     | 1475/3268 [28:29<34:35,  1.16s/it]

 45%|████▌     | 1476/3268 [28:30<34:34,  1.16s/it]

 45%|████▌     | 1477/3268 [28:31<34:31,  1.16s/it]

 45%|████▌     | 1478/3268 [28:32<34:29,  1.16s/it]

 45%|████▌     | 1479/3268 [28:33<34:28,  1.16s/it]

 45%|████▌     | 1480/3268 [28:34<34:28,  1.16s/it]

 45%|████▌     | 1481/3268 [28:36<34:28,  1.16s/it]

 45%|████▌     | 1482/3268 [28:37<34:27,  1.16s/it]

 45%|████▌     | 1483/3268 [28:38<34:27,  1.16s/it]

 45%|████▌     | 1484/3268 [28:39<34:26,  1.16s/it]

 45%|████▌     | 1485/3268 [28:40<34:26,  1.16s/it]

 45%|████▌     | 1486/3268 [28:41<34:25,  1.16s/it]

 46%|████▌     | 1487/3268 [28:43<34:23,  1.16s/it]

 46%|████▌     | 1488/3268 [28:44<34:21,  1.16s/it]

 46%|████▌     | 1489/3268 [28:45<34:19,  1.16s/it]

 46%|████▌     | 1490/3268 [28:46<34:16,  1.16s/it]

 46%|████▌     | 1491/3268 [28:47<34:16,  1.16s/it]

 46%|████▌     | 1492/3268 [28:48<34:16,  1.16s/it]

 46%|████▌     | 1493/3268 [28:50<34:14,  1.16s/it]

 46%|████▌     | 1494/3268 [28:51<34:14,  1.16s/it]

 46%|████▌     | 1495/3268 [28:52<34:13,  1.16s/it]

 46%|████▌     | 1496/3268 [28:53<34:10,  1.16s/it]

 46%|████▌     | 1497/3268 [28:54<34:09,  1.16s/it]

 46%|████▌     | 1498/3268 [28:55<34:06,  1.16s/it]

 46%|████▌     | 1499/3268 [28:56<34:05,  1.16s/it]

 46%|████▌     | 1500/3268 [28:58<34:04,  1.16s/it]

 46%|████▌     | 1501/3268 [28:59<34:04,  1.16s/it]

 46%|████▌     | 1502/3268 [29:00<34:04,  1.16s/it]

 46%|████▌     | 1503/3268 [29:01<34:05,  1.16s/it]

 46%|████▌     | 1504/3268 [29:02<34:03,  1.16s/it]

 46%|████▌     | 1505/3268 [29:03<34:02,  1.16s/it]

 46%|████▌     | 1506/3268 [29:05<34:02,  1.16s/it]

 46%|████▌     | 1507/3268 [29:06<33:59,  1.16s/it]

 46%|████▌     | 1508/3268 [29:07<33:57,  1.16s/it]

 46%|████▌     | 1509/3268 [29:08<33:55,  1.16s/it]

 46%|████▌     | 1510/3268 [29:09<33:54,  1.16s/it]

 46%|████▌     | 1511/3268 [29:10<33:52,  1.16s/it]

 46%|████▋     | 1512/3268 [29:12<33:51,  1.16s/it]

 46%|████▋     | 1513/3268 [29:13<33:51,  1.16s/it]

 46%|████▋     | 1514/3268 [29:14<33:50,  1.16s/it]

 46%|████▋     | 1515/3268 [29:15<33:50,  1.16s/it]

 46%|████▋     | 1516/3268 [29:16<33:49,  1.16s/it]

 46%|████▋     | 1517/3268 [29:17<33:48,  1.16s/it]

 46%|████▋     | 1518/3268 [29:18<33:47,  1.16s/it]

 46%|████▋     | 1519/3268 [29:20<33:47,  1.16s/it]

 47%|████▋     | 1520/3268 [29:21<33:46,  1.16s/it]

 47%|████▋     | 1521/3268 [29:22<33:44,  1.16s/it]

 47%|████▋     | 1522/3268 [29:23<33:42,  1.16s/it]

 47%|████▋     | 1523/3268 [29:24<33:39,  1.16s/it]

 47%|████▋     | 1524/3268 [29:25<33:39,  1.16s/it]

 47%|████▋     | 1525/3268 [29:27<33:39,  1.16s/it]

 47%|████▋     | 1526/3268 [29:28<33:37,  1.16s/it]

 47%|████▋     | 1527/3268 [29:29<33:35,  1.16s/it]

 47%|████▋     | 1528/3268 [29:30<33:36,  1.16s/it]

 47%|████▋     | 1529/3268 [29:31<33:35,  1.16s/it]

 47%|████▋     | 1530/3268 [29:32<33:31,  1.16s/it]

 47%|████▋     | 1531/3268 [29:34<33:29,  1.16s/it]

 47%|████▋     | 1532/3268 [29:35<33:29,  1.16s/it]

 47%|████▋     | 1533/3268 [29:36<33:27,  1.16s/it]

 47%|████▋     | 1534/3268 [29:37<33:28,  1.16s/it]

 47%|████▋     | 1535/3268 [29:38<33:28,  1.16s/it]

 47%|████▋     | 1536/3268 [29:39<33:26,  1.16s/it]

 47%|████▋     | 1537/3268 [29:40<33:24,  1.16s/it]

 47%|████▋     | 1538/3268 [29:42<33:25,  1.16s/it]

 47%|████▋     | 1539/3268 [29:43<33:23,  1.16s/it]

 47%|████▋     | 1540/3268 [29:44<33:21,  1.16s/it]

 47%|████▋     | 1541/3268 [29:45<33:20,  1.16s/it]

 47%|████▋     | 1542/3268 [29:46<33:17,  1.16s/it]

 47%|████▋     | 1543/3268 [29:47<33:16,  1.16s/it]

 47%|████▋     | 1544/3268 [29:49<33:17,  1.16s/it]

 47%|████▋     | 1545/3268 [29:50<33:16,  1.16s/it]

 47%|████▋     | 1546/3268 [29:51<33:15,  1.16s/it]

 47%|████▋     | 1547/3268 [29:52<33:12,  1.16s/it]

 47%|████▋     | 1548/3268 [29:53<33:12,  1.16s/it]

 47%|████▋     | 1549/3268 [29:54<33:12,  1.16s/it]

 47%|████▋     | 1550/3268 [29:56<33:10,  1.16s/it]

 47%|████▋     | 1551/3268 [29:57<33:06,  1.16s/it]

 47%|████▋     | 1552/3268 [29:58<33:05,  1.16s/it]

 48%|████▊     | 1553/3268 [29:59<33:05,  1.16s/it]

 48%|████▊     | 1554/3268 [30:00<33:06,  1.16s/it]

 48%|████▊     | 1555/3268 [30:01<33:06,  1.16s/it]

 48%|████▊     | 1556/3268 [30:02<33:04,  1.16s/it]

 48%|████▊     | 1557/3268 [30:04<33:03,  1.16s/it]

 48%|████▊     | 1558/3268 [30:05<33:04,  1.16s/it]

 48%|████▊     | 1559/3268 [30:06<33:01,  1.16s/it]

 48%|████▊     | 1560/3268 [30:07<32:58,  1.16s/it]

 48%|████▊     | 1561/3268 [30:08<32:57,  1.16s/it]

 48%|████▊     | 1562/3268 [30:09<32:56,  1.16s/it]

 48%|████▊     | 1563/3268 [30:11<32:54,  1.16s/it]

 48%|████▊     | 1564/3268 [30:12<32:54,  1.16s/it]

 48%|████▊     | 1565/3268 [30:13<32:55,  1.16s/it]

 48%|████▊     | 1566/3268 [30:14<32:54,  1.16s/it]

 48%|████▊     | 1567/3268 [30:15<32:52,  1.16s/it]

 48%|████▊     | 1568/3268 [30:16<32:50,  1.16s/it]

 48%|████▊     | 1569/3268 [30:18<32:51,  1.16s/it]

 48%|████▊     | 1570/3268 [30:19<32:49,  1.16s/it]

 48%|████▊     | 1571/3268 [30:20<32:47,  1.16s/it]

 48%|████▊     | 1572/3268 [30:21<32:44,  1.16s/it]

 48%|████▊     | 1573/3268 [30:22<32:40,  1.16s/it]

 48%|████▊     | 1574/3268 [30:23<32:40,  1.16s/it]

 48%|████▊     | 1575/3268 [30:24<32:41,  1.16s/it]

 48%|████▊     | 1576/3268 [30:26<32:42,  1.16s/it]

 48%|████▊     | 1577/3268 [30:27<32:43,  1.16s/it]

 48%|████▊     | 1578/3268 [30:28<32:43,  1.16s/it]

 48%|████▊     | 1579/3268 [30:29<32:41,  1.16s/it]

 48%|████▊     | 1580/3268 [30:30<32:40,  1.16s/it]

 48%|████▊     | 1581/3268 [30:31<32:37,  1.16s/it]

 48%|████▊     | 1582/3268 [30:33<32:35,  1.16s/it]

 48%|████▊     | 1583/3268 [30:34<32:33,  1.16s/it]

 48%|████▊     | 1584/3268 [30:35<32:31,  1.16s/it]

 49%|████▊     | 1585/3268 [30:36<32:31,  1.16s/it]

 49%|████▊     | 1586/3268 [30:37<32:31,  1.16s/it]

 49%|████▊     | 1587/3268 [30:38<32:29,  1.16s/it]

 49%|████▊     | 1588/3268 [30:40<32:26,  1.16s/it]

 49%|████▊     | 1589/3268 [30:41<32:23,  1.16s/it]

 49%|████▊     | 1590/3268 [30:42<32:22,  1.16s/it]

 49%|████▊     | 1591/3268 [30:43<32:22,  1.16s/it]

 49%|████▊     | 1592/3268 [30:44<32:22,  1.16s/it]

 49%|████▊     | 1593/3268 [30:45<32:21,  1.16s/it]

 49%|████▉     | 1594/3268 [30:47<32:19,  1.16s/it]

 49%|████▉     | 1595/3268 [30:48<32:18,  1.16s/it]

 49%|████▉     | 1596/3268 [30:49<32:16,  1.16s/it]

 49%|████▉     | 1597/3268 [30:50<32:18,  1.16s/it]

 49%|████▉     | 1598/3268 [30:51<32:15,  1.16s/it]

 49%|████▉     | 1599/3268 [30:52<32:13,  1.16s/it]

 49%|████▉     | 1600/3268 [30:53<32:12,  1.16s/it]

 49%|████▉     | 1601/3268 [30:55<32:10,  1.16s/it]

 49%|████▉     | 1602/3268 [30:56<32:09,  1.16s/it]

 49%|████▉     | 1603/3268 [30:57<32:09,  1.16s/it]

 49%|████▉     | 1604/3268 [30:58<32:09,  1.16s/it]

 49%|████▉     | 1605/3268 [30:59<32:07,  1.16s/it]

 49%|████▉     | 1606/3268 [31:00<32:06,  1.16s/it]

 49%|████▉     | 1607/3268 [31:02<32:03,  1.16s/it]

 49%|████▉     | 1608/3268 [31:03<32:01,  1.16s/it]

 49%|████▉     | 1609/3268 [31:04<32:00,  1.16s/it]

 49%|████▉     | 1610/3268 [31:05<31:59,  1.16s/it]

 49%|████▉     | 1611/3268 [31:06<31:59,  1.16s/it]

 49%|████▉     | 1612/3268 [31:07<31:57,  1.16s/it]

 49%|████▉     | 1613/3268 [31:09<31:56,  1.16s/it]

 49%|████▉     | 1614/3268 [31:10<31:55,  1.16s/it]

 49%|████▉     | 1615/3268 [31:11<31:56,  1.16s/it]

 49%|████▉     | 1616/3268 [31:12<31:55,  1.16s/it]

 49%|████▉     | 1617/3268 [31:13<31:53,  1.16s/it]

 50%|████▉     | 1618/3268 [31:14<31:50,  1.16s/it]

 50%|████▉     | 1619/3268 [31:15<31:49,  1.16s/it]

 50%|████▉     | 1620/3268 [31:17<31:48,  1.16s/it]

 50%|████▉     | 1621/3268 [31:18<31:50,  1.16s/it]

 50%|████▉     | 1622/3268 [31:19<31:50,  1.16s/it]

 50%|████▉     | 1623/3268 [31:20<31:49,  1.16s/it]

 50%|████▉     | 1624/3268 [31:21<31:49,  1.16s/it]

 50%|████▉     | 1625/3268 [31:22<31:46,  1.16s/it]

 50%|████▉     | 1626/3268 [31:24<31:44,  1.16s/it]

 50%|████▉     | 1627/3268 [31:25<31:42,  1.16s/it]

 50%|████▉     | 1628/3268 [31:26<31:40,  1.16s/it]

 50%|████▉     | 1629/3268 [31:27<31:37,  1.16s/it]

 50%|████▉     | 1630/3268 [31:28<31:38,  1.16s/it]

 50%|████▉     | 1631/3268 [31:29<31:35,  1.16s/it]

 50%|████▉     | 1632/3268 [31:31<31:37,  1.16s/it]

 50%|████▉     | 1633/3268 [31:32<31:36,  1.16s/it]

 50%|█████     | 1634/3268 [31:33<31:34,  1.16s/it]

 50%|█████     | 1635/3268 [31:34<31:35,  1.16s/it]

 50%|█████     | 1636/3268 [31:35<31:34,  1.16s/it]

 50%|█████     | 1637/3268 [31:36<31:32,  1.16s/it]

 50%|█████     | 1638/3268 [31:38<31:30,  1.16s/it]

 50%|█████     | 1639/3268 [31:39<31:29,  1.16s/it]

 50%|█████     | 1640/3268 [31:40<31:28,  1.16s/it]

 50%|█████     | 1641/3268 [31:41<31:29,  1.16s/it]

 50%|█████     | 1642/3268 [31:42<31:28,  1.16s/it]

 50%|█████     | 1643/3268 [31:43<31:24,  1.16s/it]

 50%|█████     | 1644/3268 [31:44<31:22,  1.16s/it]

 50%|█████     | 1645/3268 [31:46<31:19,  1.16s/it]

 50%|█████     | 1646/3268 [31:47<31:17,  1.16s/it]

 50%|█████     | 1647/3268 [31:48<31:17,  1.16s/it]

 50%|█████     | 1648/3268 [31:49<31:16,  1.16s/it]

 50%|█████     | 1649/3268 [31:50<31:16,  1.16s/it]

 50%|█████     | 1650/3268 [31:51<31:13,  1.16s/it]

 51%|█████     | 1651/3268 [31:53<31:15,  1.16s/it]

 51%|█████     | 1652/3268 [31:54<31:16,  1.16s/it]

 51%|█████     | 1653/3268 [31:55<31:15,  1.16s/it]

 51%|█████     | 1654/3268 [31:56<31:11,  1.16s/it]

 51%|█████     | 1655/3268 [31:57<31:08,  1.16s/it]

 51%|█████     | 1656/3268 [31:58<31:08,  1.16s/it]

 51%|█████     | 1657/3268 [32:00<31:05,  1.16s/it]

 51%|█████     | 1658/3268 [32:01<31:05,  1.16s/it]

 51%|█████     | 1659/3268 [32:02<31:05,  1.16s/it]

 51%|█████     | 1660/3268 [32:03<31:05,  1.16s/it]

 51%|█████     | 1661/3268 [32:04<31:05,  1.16s/it]

 51%|█████     | 1662/3268 [32:05<31:02,  1.16s/it]

 51%|█████     | 1663/3268 [32:07<31:04,  1.16s/it]

 51%|█████     | 1664/3268 [32:08<31:02,  1.16s/it]

 51%|█████     | 1665/3268 [32:09<31:01,  1.16s/it]

 51%|█████     | 1666/3268 [32:10<30:59,  1.16s/it]

 51%|█████     | 1667/3268 [32:11<30:55,  1.16s/it]

 51%|█████     | 1668/3268 [32:12<30:55,  1.16s/it]

 51%|█████     | 1669/3268 [32:13<30:53,  1.16s/it]

 51%|█████     | 1670/3268 [32:15<30:54,  1.16s/it]

 51%|█████     | 1671/3268 [32:16<30:52,  1.16s/it]

 51%|█████     | 1672/3268 [32:17<30:51,  1.16s/it]

 51%|█████     | 1673/3268 [32:18<30:51,  1.16s/it]

 51%|█████     | 1674/3268 [32:19<30:50,  1.16s/it]

 51%|█████▏    | 1675/3268 [32:20<30:50,  1.16s/it]

 51%|█████▏    | 1676/3268 [32:22<30:46,  1.16s/it]

 51%|█████▏    | 1677/3268 [32:23<30:44,  1.16s/it]

 51%|█████▏    | 1678/3268 [32:24<30:43,  1.16s/it]

 51%|█████▏    | 1679/3268 [32:25<30:40,  1.16s/it]

 51%|█████▏    | 1680/3268 [32:26<30:41,  1.16s/it]

 51%|█████▏    | 1681/3268 [32:27<30:42,  1.16s/it]

 51%|█████▏    | 1682/3268 [32:29<30:41,  1.16s/it]

 51%|█████▏    | 1683/3268 [32:30<30:39,  1.16s/it]

 52%|█████▏    | 1684/3268 [32:31<30:37,  1.16s/it]

 52%|█████▏    | 1685/3268 [32:32<30:37,  1.16s/it]

 52%|█████▏    | 1686/3268 [32:33<30:35,  1.16s/it]

 52%|█████▏    | 1687/3268 [32:34<30:36,  1.16s/it]

 52%|█████▏    | 1688/3268 [32:36<30:35,  1.16s/it]

 52%|█████▏    | 1689/3268 [32:37<30:32,  1.16s/it]

 52%|█████▏    | 1690/3268 [32:38<30:29,  1.16s/it]

 52%|█████▏    | 1691/3268 [32:39<30:30,  1.16s/it]

 52%|█████▏    | 1692/3268 [32:40<30:30,  1.16s/it]

 52%|█████▏    | 1693/3268 [32:41<30:28,  1.16s/it]

 52%|█████▏    | 1694/3268 [32:42<30:26,  1.16s/it]

 52%|█████▏    | 1695/3268 [32:44<30:26,  1.16s/it]

 52%|█████▏    | 1696/3268 [32:45<30:24,  1.16s/it]

 52%|█████▏    | 1697/3268 [32:46<30:21,  1.16s/it]

 52%|█████▏    | 1698/3268 [32:47<30:21,  1.16s/it]

 52%|█████▏    | 1699/3268 [32:48<30:21,  1.16s/it]

 52%|█████▏    | 1700/3268 [32:49<30:20,  1.16s/it]

 52%|█████▏    | 1701/3268 [32:51<30:17,  1.16s/it]

 52%|█████▏    | 1702/3268 [32:52<30:16,  1.16s/it]

 52%|█████▏    | 1703/3268 [32:53<30:16,  1.16s/it]

 52%|█████▏    | 1704/3268 [32:54<30:15,  1.16s/it]

 52%|█████▏    | 1705/3268 [32:55<30:11,  1.16s/it]

 52%|█████▏    | 1706/3268 [32:56<30:09,  1.16s/it]

 52%|█████▏    | 1707/3268 [32:58<30:10,  1.16s/it]

 52%|█████▏    | 1708/3268 [32:59<30:10,  1.16s/it]

 52%|█████▏    | 1709/3268 [33:00<30:08,  1.16s/it]

 52%|█████▏    | 1710/3268 [33:01<30:09,  1.16s/it]

 52%|█████▏    | 1711/3268 [33:02<30:08,  1.16s/it]

 52%|█████▏    | 1712/3268 [33:03<30:06,  1.16s/it]

 52%|█████▏    | 1713/3268 [33:05<30:06,  1.16s/it]

 52%|█████▏    | 1714/3268 [33:06<30:05,  1.16s/it]

 52%|█████▏    | 1715/3268 [33:07<30:03,  1.16s/it]

 53%|█████▎    | 1716/3268 [33:08<30:00,  1.16s/it]

 53%|█████▎    | 1717/3268 [33:09<29:59,  1.16s/it]

 53%|█████▎    | 1718/3268 [33:10<29:57,  1.16s/it]

 53%|█████▎    | 1719/3268 [33:11<29:55,  1.16s/it]

 53%|█████▎    | 1720/3268 [33:13<29:54,  1.16s/it]

 53%|█████▎    | 1721/3268 [33:14<29:54,  1.16s/it]

 53%|█████▎    | 1722/3268 [33:15<29:56,  1.16s/it]

 53%|█████▎    | 1723/3268 [33:16<29:54,  1.16s/it]

 53%|█████▎    | 1724/3268 [33:17<29:52,  1.16s/it]

 53%|█████▎    | 1725/3268 [33:18<29:50,  1.16s/it]

 53%|█████▎    | 1726/3268 [33:20<29:49,  1.16s/it]

 53%|█████▎    | 1727/3268 [33:21<29:48,  1.16s/it]

 53%|█████▎    | 1728/3268 [33:22<29:46,  1.16s/it]

 53%|█████▎    | 1729/3268 [33:23<29:45,  1.16s/it]

 53%|█████▎    | 1730/3268 [33:24<29:44,  1.16s/it]

 53%|█████▎    | 1731/3268 [33:25<29:44,  1.16s/it]

 53%|█████▎    | 1732/3268 [33:27<29:42,  1.16s/it]

 53%|█████▎    | 1733/3268 [33:28<29:41,  1.16s/it]

 53%|█████▎    | 1734/3268 [33:29<29:40,  1.16s/it]

 53%|█████▎    | 1735/3268 [33:30<29:39,  1.16s/it]

 53%|█████▎    | 1736/3268 [33:31<29:37,  1.16s/it]

 53%|█████▎    | 1737/3268 [33:32<29:36,  1.16s/it]

 53%|█████▎    | 1738/3268 [33:34<29:35,  1.16s/it]

 53%|█████▎    | 1739/3268 [33:35<29:33,  1.16s/it]

 53%|█████▎    | 1740/3268 [33:36<29:31,  1.16s/it]

 53%|█████▎    | 1741/3268 [33:37<29:29,  1.16s/it]

 53%|█████▎    | 1742/3268 [33:38<29:29,  1.16s/it]

 53%|█████▎    | 1743/3268 [33:39<29:31,  1.16s/it]

 53%|█████▎    | 1744/3268 [33:41<29:32,  1.16s/it]

 53%|█████▎    | 1745/3268 [33:42<29:30,  1.16s/it]

 53%|█████▎    | 1746/3268 [33:43<29:28,  1.16s/it]

 53%|█████▎    | 1747/3268 [33:44<29:25,  1.16s/it]

 53%|█████▎    | 1748/3268 [33:45<29:26,  1.16s/it]

 54%|█████▎    | 1749/3268 [33:46<29:22,  1.16s/it]

 54%|█████▎    | 1750/3268 [33:47<29:21,  1.16s/it]

 54%|█████▎    | 1751/3268 [33:49<29:20,  1.16s/it]

 54%|█████▎    | 1752/3268 [33:50<29:22,  1.16s/it]

 54%|█████▎    | 1753/3268 [33:51<29:22,  1.16s/it]

 54%|█████▎    | 1754/3268 [33:52<29:19,  1.16s/it]

 54%|█████▎    | 1755/3268 [33:53<29:18,  1.16s/it]

 54%|█████▎    | 1756/3268 [33:54<29:16,  1.16s/it]

 54%|█████▍    | 1757/3268 [33:56<29:12,  1.16s/it]

 54%|█████▍    | 1758/3268 [33:57<29:10,  1.16s/it]

 54%|█████▍    | 1759/3268 [33:58<29:08,  1.16s/it]

 54%|█████▍    | 1760/3268 [33:59<29:08,  1.16s/it]

 54%|█████▍    | 1761/3268 [34:00<29:09,  1.16s/it]

 54%|█████▍    | 1762/3268 [34:01<29:08,  1.16s/it]

 54%|█████▍    | 1763/3268 [34:03<29:08,  1.16s/it]

 54%|█████▍    | 1764/3268 [34:04<29:08,  1.16s/it]

 54%|█████▍    | 1765/3268 [34:05<29:07,  1.16s/it]

 54%|█████▍    | 1766/3268 [34:06<29:04,  1.16s/it]

 54%|█████▍    | 1767/3268 [34:07<29:02,  1.16s/it]

 54%|█████▍    | 1768/3268 [34:08<29:00,  1.16s/it]

 54%|█████▍    | 1769/3268 [34:10<28:59,  1.16s/it]

 54%|█████▍    | 1770/3268 [34:11<28:57,  1.16s/it]

 54%|█████▍    | 1771/3268 [34:12<28:56,  1.16s/it]

 54%|█████▍    | 1772/3268 [34:13<28:57,  1.16s/it]

 54%|█████▍    | 1773/3268 [34:14<28:57,  1.16s/it]

 54%|█████▍    | 1774/3268 [34:15<28:57,  1.16s/it]

 54%|█████▍    | 1775/3268 [34:17<28:54,  1.16s/it]

 54%|█████▍    | 1776/3268 [34:18<28:54,  1.16s/it]

 54%|█████▍    | 1777/3268 [34:19<28:51,  1.16s/it]

 54%|█████▍    | 1778/3268 [34:20<28:50,  1.16s/it]

 54%|█████▍    | 1779/3268 [34:21<28:48,  1.16s/it]

 54%|█████▍    | 1780/3268 [34:22<28:47,  1.16s/it]

 54%|█████▍    | 1781/3268 [34:23<28:44,  1.16s/it]

 55%|█████▍    | 1782/3268 [34:25<28:43,  1.16s/it]

 55%|█████▍    | 1783/3268 [34:26<28:43,  1.16s/it]

 55%|█████▍    | 1784/3268 [34:27<28:42,  1.16s/it]

 55%|█████▍    | 1785/3268 [34:28<28:42,  1.16s/it]

 55%|█████▍    | 1786/3268 [34:29<28:42,  1.16s/it]

 55%|█████▍    | 1787/3268 [34:30<28:40,  1.16s/it]

 55%|█████▍    | 1788/3268 [34:32<28:38,  1.16s/it]

 55%|█████▍    | 1789/3268 [34:33<28:36,  1.16s/it]

 55%|█████▍    | 1790/3268 [34:34<28:35,  1.16s/it]

 55%|█████▍    | 1791/3268 [34:35<28:34,  1.16s/it]

 55%|█████▍    | 1792/3268 [34:36<28:33,  1.16s/it]

 55%|█████▍    | 1793/3268 [34:37<28:31,  1.16s/it]

 55%|█████▍    | 1794/3268 [34:39<28:30,  1.16s/it]

 55%|█████▍    | 1795/3268 [34:40<28:29,  1.16s/it]

 55%|█████▍    | 1796/3268 [34:41<28:29,  1.16s/it]

 55%|█████▍    | 1797/3268 [34:42<28:29,  1.16s/it]

 55%|█████▌    | 1798/3268 [34:43<28:28,  1.16s/it]

 55%|█████▌    | 1799/3268 [34:44<28:28,  1.16s/it]

 55%|█████▌    | 1800/3268 [34:46<28:27,  1.16s/it]

 55%|█████▌    | 1801/3268 [34:47<28:26,  1.16s/it]

 55%|█████▌    | 1802/3268 [34:48<28:23,  1.16s/it]

 55%|█████▌    | 1803/3268 [34:49<28:23,  1.16s/it]

 55%|█████▌    | 1804/3268 [34:50<28:21,  1.16s/it]

 55%|█████▌    | 1805/3268 [34:51<28:19,  1.16s/it]

 55%|█████▌    | 1806/3268 [34:53<28:18,  1.16s/it]

 55%|█████▌    | 1807/3268 [34:54<28:17,  1.16s/it]

 55%|█████▌    | 1808/3268 [34:55<28:17,  1.16s/it]

 55%|█████▌    | 1809/3268 [34:56<28:16,  1.16s/it]

 55%|█████▌    | 1810/3268 [34:57<28:17,  1.16s/it]

 55%|█████▌    | 1811/3268 [34:58<28:15,  1.16s/it]

 55%|█████▌    | 1812/3268 [34:59<28:11,  1.16s/it]

 55%|█████▌    | 1813/3268 [35:01<28:10,  1.16s/it]

 56%|█████▌    | 1814/3268 [35:02<28:10,  1.16s/it]

 56%|█████▌    | 1815/3268 [35:03<28:10,  1.16s/it]

 56%|█████▌    | 1816/3268 [35:04<28:07,  1.16s/it]

 56%|█████▌    | 1817/3268 [35:05<28:07,  1.16s/it]

 56%|█████▌    | 1818/3268 [35:06<28:05,  1.16s/it]

 56%|█████▌    | 1819/3268 [35:08<28:04,  1.16s/it]

 56%|█████▌    | 1820/3268 [35:09<28:02,  1.16s/it]

 56%|█████▌    | 1821/3268 [35:10<28:01,  1.16s/it]

 56%|█████▌    | 1822/3268 [35:11<28:00,  1.16s/it]

 56%|█████▌    | 1823/3268 [35:12<27:59,  1.16s/it]

 56%|█████▌    | 1824/3268 [35:13<27:56,  1.16s/it]

 56%|█████▌    | 1825/3268 [35:15<27:55,  1.16s/it]

 56%|█████▌    | 1826/3268 [35:16<27:55,  1.16s/it]

 56%|█████▌    | 1827/3268 [35:17<27:53,  1.16s/it]

 56%|█████▌    | 1828/3268 [35:18<27:52,  1.16s/it]

 56%|█████▌    | 1829/3268 [35:19<27:51,  1.16s/it]

 56%|█████▌    | 1830/3268 [35:20<27:49,  1.16s/it]

 56%|█████▌    | 1831/3268 [35:22<27:48,  1.16s/it]

 56%|█████▌    | 1832/3268 [35:23<27:47,  1.16s/it]

 56%|█████▌    | 1833/3268 [35:24<27:47,  1.16s/it]

 56%|█████▌    | 1834/3268 [35:25<27:46,  1.16s/it]

 56%|█████▌    | 1835/3268 [35:26<27:43,  1.16s/it]

 56%|█████▌    | 1836/3268 [35:27<27:42,  1.16s/it]

 56%|█████▌    | 1837/3268 [35:29<27:40,  1.16s/it]

 56%|█████▌    | 1838/3268 [35:30<27:40,  1.16s/it]

 56%|█████▋    | 1839/3268 [35:31<27:41,  1.16s/it]

 56%|█████▋    | 1840/3268 [35:32<27:39,  1.16s/it]

 56%|█████▋    | 1841/3268 [35:33<27:38,  1.16s/it]

 56%|█████▋    | 1842/3268 [35:34<27:37,  1.16s/it]

 56%|█████▋    | 1843/3268 [35:36<27:34,  1.16s/it]

 56%|█████▋    | 1844/3268 [35:37<27:35,  1.16s/it]

 56%|█████▋    | 1845/3268 [35:38<27:33,  1.16s/it]

 56%|█████▋    | 1846/3268 [35:39<27:32,  1.16s/it]

 57%|█████▋    | 1847/3268 [35:40<27:31,  1.16s/it]

 57%|█████▋    | 1848/3268 [35:41<27:27,  1.16s/it]

 57%|█████▋    | 1849/3268 [35:42<27:26,  1.16s/it]

 57%|█████▋    | 1850/3268 [35:44<27:24,  1.16s/it]

 57%|█████▋    | 1851/3268 [35:45<27:24,  1.16s/it]

 57%|█████▋    | 1852/3268 [35:46<27:23,  1.16s/it]

 57%|█████▋    | 1853/3268 [35:47<27:22,  1.16s/it]

 57%|█████▋    | 1854/3268 [35:48<27:21,  1.16s/it]

 57%|█████▋    | 1855/3268 [35:49<27:23,  1.16s/it]

 57%|█████▋    | 1856/3268 [35:51<27:22,  1.16s/it]

 57%|█████▋    | 1857/3268 [35:52<27:21,  1.16s/it]

 57%|█████▋    | 1858/3268 [35:53<27:23,  1.17s/it]

 57%|█████▋    | 1859/3268 [35:54<27:19,  1.16s/it]

 57%|█████▋    | 1860/3268 [35:55<27:15,  1.16s/it]

 57%|█████▋    | 1861/3268 [35:56<27:14,  1.16s/it]

 57%|█████▋    | 1862/3268 [35:58<27:12,  1.16s/it]

 57%|█████▋    | 1863/3268 [35:59<27:12,  1.16s/it]

 57%|█████▋    | 1864/3268 [36:00<27:11,  1.16s/it]

 57%|█████▋    | 1865/3268 [36:01<27:11,  1.16s/it]

 57%|█████▋    | 1866/3268 [36:02<27:10,  1.16s/it]

 57%|█████▋    | 1867/3268 [36:03<27:07,  1.16s/it]

 57%|█████▋    | 1868/3268 [36:05<27:05,  1.16s/it]

 57%|█████▋    | 1869/3268 [36:06<27:05,  1.16s/it]

 57%|█████▋    | 1870/3268 [36:07<27:04,  1.16s/it]

 57%|█████▋    | 1871/3268 [36:08<27:03,  1.16s/it]

 57%|█████▋    | 1872/3268 [36:09<27:01,  1.16s/it]

 57%|█████▋    | 1873/3268 [36:10<27:00,  1.16s/it]

 57%|█████▋    | 1874/3268 [36:12<26:57,  1.16s/it]

 57%|█████▋    | 1875/3268 [36:13<26:57,  1.16s/it]

 57%|█████▋    | 1876/3268 [36:14<26:55,  1.16s/it]

 57%|█████▋    | 1877/3268 [36:15<26:53,  1.16s/it]

logging
logging the anndata

 57%|█████▋    | 1878/3268 [36:16<27:31,  1.19s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 57%|█████▋    | 1879/3268 [36:17<27:17,  1.18s/it]

 58%|█████▊    | 1880/3268 [36:19<27:05,  1.17s/it]

 58%|█████▊    | 1881/3268 [36:20<26:57,  1.17s/it]

 58%|█████▊    | 1882/3268 [36:21<26:50,  1.16s/it]

 58%|█████▊    | 1883/3268 [36:22<26:45,  1.16s/it]

 58%|█████▊    | 1884/3268 [36:23<26:43,  1.16s/it]

 58%|█████▊    | 1885/3268 [36:24<26:41,  1.16s/it]

 58%|█████▊    | 1886/3268 [36:25<26:40,  1.16s/it]

 58%|█████▊    | 1887/3268 [36:27<26:37,  1.16s/it]

 58%|█████▊    | 1888/3268 [36:28<26:36,  1.16s/it]

 58%|█████▊    | 1889/3268 [36:29<26:35,  1.16s/it]

 58%|█████▊    | 1890/3268 [36:30<26:32,  1.16s/it]

 58%|█████▊    | 1891/3268 [36:31<26:31,  1.16s/it]

 58%|█████▊    | 1892/3268 [36:32<26:30,  1.16s/it]

 58%|█████▊    | 1893/3268 [36:34<26:28,  1.16s/it]

 58%|█████▊    | 1894/3268 [36:35<26:27,  1.16s/it]

 58%|█████▊    | 1895/3268 [36:36<26:26,  1.16s/it]

 58%|█████▊    | 1896/3268 [36:37<26:28,  1.16s/it]

 58%|█████▊    | 1897/3268 [36:38<26:24,  1.16s/it]

 58%|█████▊    | 1898/3268 [36:39<26:24,  1.16s/it]

 58%|█████▊    | 1899/3268 [36:41<26:22,  1.16s/it]

 58%|█████▊    | 1900/3268 [36:42<26:19,  1.15s/it]

 58%|█████▊    | 1901/3268 [36:43<26:18,  1.15s/it]

 58%|█████▊    | 1902/3268 [36:44<26:19,  1.16s/it]

 58%|█████▊    | 1903/3268 [36:45<26:19,  1.16s/it]

 58%|█████▊    | 1904/3268 [36:46<26:18,  1.16s/it]

 58%|█████▊    | 1905/3268 [36:47<26:16,  1.16s/it]

 58%|█████▊    | 1906/3268 [36:49<26:15,  1.16s/it]

 58%|█████▊    | 1907/3268 [36:50<26:13,  1.16s/it]

 58%|█████▊    | 1908/3268 [36:51<26:10,  1.16s/it]

 58%|█████▊    | 1909/3268 [36:52<26:09,  1.16s/it]

 58%|█████▊    | 1910/3268 [36:53<26:09,  1.16s/it]

 58%|█████▊    | 1911/3268 [36:54<26:08,  1.16s/it]

 59%|█████▊    | 1912/3268 [36:56<26:07,  1.16s/it]

 59%|█████▊    | 1913/3268 [36:57<26:06,  1.16s/it]

 59%|█████▊    | 1914/3268 [36:58<26:05,  1.16s/it]

 59%|█████▊    | 1915/3268 [36:59<26:04,  1.16s/it]

 59%|█████▊    | 1916/3268 [37:00<26:02,  1.16s/it]

 59%|█████▊    | 1917/3268 [37:01<26:01,  1.16s/it]

 59%|█████▊    | 1918/3268 [37:02<26:00,  1.16s/it]

 59%|█████▊    | 1919/3268 [37:04<25:59,  1.16s/it]

 59%|█████▉    | 1920/3268 [37:05<25:59,  1.16s/it]

 59%|█████▉    | 1921/3268 [37:06<25:58,  1.16s/it]

 59%|█████▉    | 1922/3268 [37:07<25:57,  1.16s/it]

 59%|█████▉    | 1923/3268 [37:08<25:56,  1.16s/it]

 59%|█████▉    | 1924/3268 [37:09<25:55,  1.16s/it]

 59%|█████▉    | 1925/3268 [37:11<25:54,  1.16s/it]

 59%|█████▉    | 1926/3268 [37:12<25:53,  1.16s/it]

 59%|█████▉    | 1927/3268 [37:13<25:52,  1.16s/it]

 59%|█████▉    | 1928/3268 [37:14<25:51,  1.16s/it]

 59%|█████▉    | 1929/3268 [37:15<25:47,  1.16s/it]

 59%|█████▉    | 1930/3268 [37:16<25:46,  1.16s/it]

 59%|█████▉    | 1931/3268 [37:18<25:45,  1.16s/it]

 59%|█████▉    | 1932/3268 [37:19<25:43,  1.16s/it]

 59%|█████▉    | 1933/3268 [37:20<25:43,  1.16s/it]

 59%|█████▉    | 1934/3268 [37:21<25:42,  1.16s/it]

 59%|█████▉    | 1935/3268 [37:22<25:41,  1.16s/it]

 59%|█████▉    | 1936/3268 [37:23<25:43,  1.16s/it]

 59%|█████▉    | 1937/3268 [37:24<25:41,  1.16s/it]

 59%|█████▉    | 1938/3268 [37:26<25:39,  1.16s/it]

 59%|█████▉    | 1939/3268 [37:27<25:38,  1.16s/it]

 59%|█████▉    | 1940/3268 [37:28<25:36,  1.16s/it]

 59%|█████▉    | 1941/3268 [37:29<25:35,  1.16s/it]

 59%|█████▉    | 1942/3268 [37:30<25:35,  1.16s/it]

 59%|█████▉    | 1943/3268 [37:31<25:34,  1.16s/it]

 59%|█████▉    | 1944/3268 [37:33<25:32,  1.16s/it]

 60%|█████▉    | 1945/3268 [37:34<25:30,  1.16s/it]

 60%|█████▉    | 1946/3268 [37:35<25:27,  1.16s/it]

 60%|█████▉    | 1947/3268 [37:36<25:25,  1.15s/it]

 60%|█████▉    | 1948/3268 [37:37<25:24,  1.15s/it]

 60%|█████▉    | 1949/3268 [37:38<25:23,  1.16s/it]

 60%|█████▉    | 1950/3268 [37:40<25:22,  1.16s/it]

 60%|█████▉    | 1951/3268 [37:41<25:22,  1.16s/it]

 60%|█████▉    | 1952/3268 [37:42<25:20,  1.16s/it]

 60%|█████▉    | 1953/3268 [37:43<25:19,  1.16s/it]

 60%|█████▉    | 1954/3268 [37:44<25:17,  1.15s/it]

 60%|█████▉    | 1955/3268 [37:45<25:15,  1.15s/it]

 60%|█████▉    | 1956/3268 [37:46<25:14,  1.15s/it]

 60%|█████▉    | 1957/3268 [37:48<25:14,  1.16s/it]

 60%|█████▉    | 1958/3268 [37:49<25:14,  1.16s/it]

 60%|█████▉    | 1959/3268 [37:50<25:12,  1.16s/it]

 60%|█████▉    | 1960/3268 [37:51<25:12,  1.16s/it]

 60%|██████    | 1961/3268 [37:52<25:12,  1.16s/it]

 60%|██████    | 1962/3268 [37:53<25:11,  1.16s/it]

 60%|██████    | 1963/3268 [37:55<25:11,  1.16s/it]

 60%|██████    | 1964/3268 [37:56<25:09,  1.16s/it]

 60%|██████    | 1965/3268 [37:57<25:08,  1.16s/it]

 60%|██████    | 1966/3268 [37:58<25:05,  1.16s/it]

 60%|██████    | 1967/3268 [37:59<25:04,  1.16s/it]

 60%|██████    | 1968/3268 [38:00<25:03,  1.16s/it]

 60%|██████    | 1969/3268 [38:01<25:02,  1.16s/it]

 60%|██████    | 1970/3268 [38:03<25:02,  1.16s/it]

 60%|██████    | 1971/3268 [38:04<25:01,  1.16s/it]

 60%|██████    | 1972/3268 [38:05<24:59,  1.16s/it]

 60%|██████    | 1973/3268 [38:06<24:57,  1.16s/it]

 60%|██████    | 1974/3268 [38:07<24:54,  1.15s/it]

 60%|██████    | 1975/3268 [38:08<24:54,  1.16s/it]

 60%|██████    | 1976/3268 [38:10<24:54,  1.16s/it]

 60%|██████    | 1977/3268 [38:11<24:53,  1.16s/it]

 61%|██████    | 1978/3268 [38:12<24:51,  1.16s/it]

 61%|██████    | 1979/3268 [38:13<24:50,  1.16s/it]

 61%|██████    | 1980/3268 [38:14<24:49,  1.16s/it]

 61%|██████    | 1981/3268 [38:15<24:48,  1.16s/it]

 61%|██████    | 1982/3268 [38:17<24:48,  1.16s/it]

 61%|██████    | 1983/3268 [38:18<24:48,  1.16s/it]

 61%|██████    | 1984/3268 [38:19<24:46,  1.16s/it]

 61%|██████    | 1985/3268 [38:20<24:46,  1.16s/it]

 61%|██████    | 1986/3268 [38:21<24:44,  1.16s/it]

 61%|██████    | 1987/3268 [38:22<24:42,  1.16s/it]

 61%|██████    | 1988/3268 [38:23<24:40,  1.16s/it]

 61%|██████    | 1989/3268 [38:25<24:39,  1.16s/it]

 61%|██████    | 1990/3268 [38:26<24:39,  1.16s/it]

 61%|██████    | 1991/3268 [38:27<24:38,  1.16s/it]

 61%|██████    | 1992/3268 [38:28<24:37,  1.16s/it]

 61%|██████    | 1993/3268 [38:29<24:37,  1.16s/it]

 61%|██████    | 1994/3268 [38:30<24:35,  1.16s/it]

 61%|██████    | 1995/3268 [38:32<24:32,  1.16s/it]

 61%|██████    | 1996/3268 [38:33<24:30,  1.16s/it]

 61%|██████    | 1997/3268 [38:34<24:29,  1.16s/it]

 61%|██████    | 1998/3268 [38:35<24:28,  1.16s/it]

 61%|██████    | 1999/3268 [38:36<24:27,  1.16s/it]

 61%|██████    | 2000/3268 [38:37<24:26,  1.16s/it]

 61%|██████    | 2001/3268 [38:39<24:26,  1.16s/it]

 61%|██████▏   | 2002/3268 [38:40<24:24,  1.16s/it]

 61%|██████▏   | 2003/3268 [38:41<24:24,  1.16s/it]

 61%|██████▏   | 2004/3268 [38:42<24:23,  1.16s/it]

 61%|██████▏   | 2005/3268 [38:43<24:21,  1.16s/it]

 61%|██████▏   | 2006/3268 [38:44<24:19,  1.16s/it]

 61%|██████▏   | 2007/3268 [38:45<24:19,  1.16s/it]

 61%|██████▏   | 2008/3268 [38:47<24:18,  1.16s/it]

 61%|██████▏   | 2009/3268 [38:48<24:16,  1.16s/it]

 62%|██████▏   | 2010/3268 [38:49<24:14,  1.16s/it]

 62%|██████▏   | 2011/3268 [38:50<24:13,  1.16s/it]

 62%|██████▏   | 2012/3268 [38:51<24:11,  1.16s/it]

 62%|██████▏   | 2013/3268 [38:52<24:10,  1.16s/it]

 62%|██████▏   | 2014/3268 [38:54<24:09,  1.16s/it]

 62%|██████▏   | 2015/3268 [38:55<24:07,  1.16s/it]

 62%|██████▏   | 2016/3268 [38:56<24:08,  1.16s/it]

 62%|██████▏   | 2017/3268 [38:57<24:08,  1.16s/it]

 62%|██████▏   | 2018/3268 [38:58<24:08,  1.16s/it]

 62%|██████▏   | 2019/3268 [38:59<24:05,  1.16s/it]

 62%|██████▏   | 2020/3268 [39:00<24:05,  1.16s/it]

 62%|██████▏   | 2021/3268 [39:02<24:04,  1.16s/it]

 62%|██████▏   | 2022/3268 [39:03<24:01,  1.16s/it]

 62%|██████▏   | 2023/3268 [39:04<24:00,  1.16s/it]

 62%|██████▏   | 2024/3268 [39:05<23:59,  1.16s/it]

 62%|██████▏   | 2025/3268 [39:06<23:58,  1.16s/it]

 62%|██████▏   | 2026/3268 [39:07<23:56,  1.16s/it]

 62%|██████▏   | 2027/3268 [39:09<23:55,  1.16s/it]

 62%|██████▏   | 2028/3268 [39:10<23:53,  1.16s/it]

 62%|██████▏   | 2029/3268 [39:11<23:55,  1.16s/it]

 62%|██████▏   | 2030/3268 [39:12<23:54,  1.16s/it]

 62%|██████▏   | 2031/3268 [39:13<23:53,  1.16s/it]

 62%|██████▏   | 2032/3268 [39:14<23:51,  1.16s/it]

 62%|██████▏   | 2033/3268 [39:16<23:50,  1.16s/it]

 62%|██████▏   | 2034/3268 [39:17<23:48,  1.16s/it]

 62%|██████▏   | 2035/3268 [39:18<23:47,  1.16s/it]

 62%|██████▏   | 2036/3268 [39:19<23:46,  1.16s/it]

 62%|██████▏   | 2037/3268 [39:20<23:47,  1.16s/it]

 62%|██████▏   | 2038/3268 [39:21<23:46,  1.16s/it]

 62%|██████▏   | 2039/3268 [39:22<23:43,  1.16s/it]

 62%|██████▏   | 2040/3268 [39:24<23:45,  1.16s/it]

 62%|██████▏   | 2041/3268 [39:25<23:58,  1.17s/it]

 62%|██████▏   | 2042/3268 [39:26<23:55,  1.17s/it]

 63%|██████▎   | 2043/3268 [39:27<23:49,  1.17s/it]

 63%|██████▎   | 2044/3268 [39:28<23:44,  1.16s/it]

 63%|██████▎   | 2045/3268 [39:29<23:40,  1.16s/it]

 63%|██████▎   | 2046/3268 [39:31<23:38,  1.16s/it]

 63%|██████▎   | 2047/3268 [39:32<23:39,  1.16s/it]

 63%|██████▎   | 2048/3268 [39:33<23:35,  1.16s/it]

 63%|██████▎   | 2049/3268 [39:34<23:32,  1.16s/it]

 63%|██████▎   | 2050/3268 [39:35<23:30,  1.16s/it]

 63%|██████▎   | 2051/3268 [39:36<23:28,  1.16s/it]

 63%|██████▎   | 2052/3268 [39:38<23:26,  1.16s/it]

 63%|██████▎   | 2053/3268 [39:39<23:25,  1.16s/it]

 63%|██████▎   | 2054/3268 [39:40<23:24,  1.16s/it]

 63%|██████▎   | 2055/3268 [39:41<23:26,  1.16s/it]

 63%|██████▎   | 2056/3268 [39:42<23:23,  1.16s/it]

 63%|██████▎   | 2057/3268 [39:43<23:22,  1.16s/it]

 63%|██████▎   | 2058/3268 [39:45<23:21,  1.16s/it]

 63%|██████▎   | 2059/3268 [39:46<23:19,  1.16s/it]

 63%|██████▎   | 2060/3268 [39:47<23:17,  1.16s/it]

 63%|██████▎   | 2061/3268 [39:48<23:16,  1.16s/it]

 63%|██████▎   | 2062/3268 [39:49<23:15,  1.16s/it]

 63%|██████▎   | 2063/3268 [39:50<23:13,  1.16s/it]

 63%|██████▎   | 2064/3268 [39:51<23:13,  1.16s/it]

 63%|██████▎   | 2065/3268 [39:53<23:12,  1.16s/it]

 63%|██████▎   | 2066/3268 [39:54<23:12,  1.16s/it]

 63%|██████▎   | 2067/3268 [39:55<23:10,  1.16s/it]

 63%|██████▎   | 2068/3268 [39:56<23:08,  1.16s/it]

 63%|██████▎   | 2069/3268 [39:57<23:07,  1.16s/it]

 63%|██████▎   | 2070/3268 [39:58<23:06,  1.16s/it]

 63%|██████▎   | 2071/3268 [40:00<23:05,  1.16s/it]

 63%|██████▎   | 2072/3268 [40:01<23:05,  1.16s/it]

 63%|██████▎   | 2073/3268 [40:02<23:03,  1.16s/it]

 63%|██████▎   | 2074/3268 [40:03<23:02,  1.16s/it]

 63%|██████▎   | 2075/3268 [40:04<23:00,  1.16s/it]

 64%|██████▎   | 2076/3268 [40:05<22:59,  1.16s/it]

 64%|██████▎   | 2077/3268 [40:07<22:56,  1.16s/it]

 64%|██████▎   | 2078/3268 [40:08<22:56,  1.16s/it]

 64%|██████▎   | 2079/3268 [40:09<22:56,  1.16s/it]

 64%|██████▎   | 2080/3268 [40:10<22:54,  1.16s/it]

 64%|██████▎   | 2081/3268 [40:11<22:53,  1.16s/it]

 64%|██████▎   | 2082/3268 [40:12<22:52,  1.16s/it]

 64%|██████▎   | 2083/3268 [40:13<22:51,  1.16s/it]

 64%|██████▍   | 2084/3268 [40:15<22:50,  1.16s/it]

 64%|██████▍   | 2085/3268 [40:16<22:49,  1.16s/it]

 64%|██████▍   | 2086/3268 [40:17<22:47,  1.16s/it]

 64%|██████▍   | 2087/3268 [40:18<22:45,  1.16s/it]

 64%|██████▍   | 2088/3268 [40:19<22:44,  1.16s/it]

 64%|██████▍   | 2089/3268 [40:20<22:44,  1.16s/it]

 64%|██████▍   | 2090/3268 [40:22<22:45,  1.16s/it]

 64%|██████▍   | 2091/3268 [40:23<22:45,  1.16s/it]

 64%|██████▍   | 2092/3268 [40:24<22:44,  1.16s/it]

 64%|██████▍   | 2093/3268 [40:25<22:42,  1.16s/it]

 64%|██████▍   | 2094/3268 [40:26<22:40,  1.16s/it]

 64%|██████▍   | 2095/3268 [40:27<22:39,  1.16s/it]

 64%|██████▍   | 2096/3268 [40:29<22:39,  1.16s/it]

 64%|██████▍   | 2097/3268 [40:30<22:36,  1.16s/it]

 64%|██████▍   | 2098/3268 [40:31<22:36,  1.16s/it]

 64%|██████▍   | 2099/3268 [40:32<22:37,  1.16s/it]

 64%|██████▍   | 2100/3268 [40:33<22:36,  1.16s/it]

 64%|██████▍   | 2101/3268 [40:34<22:35,  1.16s/it]

 64%|██████▍   | 2102/3268 [40:35<22:32,  1.16s/it]

 64%|██████▍   | 2103/3268 [40:37<22:30,  1.16s/it]

 64%|██████▍   | 2104/3268 [40:38<22:29,  1.16s/it]

 64%|██████▍   | 2105/3268 [40:39<22:28,  1.16s/it]

 64%|██████▍   | 2106/3268 [40:40<22:25,  1.16s/it]

 64%|██████▍   | 2107/3268 [40:41<22:25,  1.16s/it]

 65%|██████▍   | 2108/3268 [40:42<22:23,  1.16s/it]

 65%|██████▍   | 2109/3268 [40:44<22:22,  1.16s/it]

 65%|██████▍   | 2110/3268 [40:45<22:20,  1.16s/it]

 65%|██████▍   | 2111/3268 [40:46<22:18,  1.16s/it]

 65%|██████▍   | 2112/3268 [40:47<22:17,  1.16s/it]

 65%|██████▍   | 2113/3268 [40:48<22:16,  1.16s/it]

 65%|██████▍   | 2114/3268 [40:49<22:15,  1.16s/it]

 65%|██████▍   | 2115/3268 [40:51<22:15,  1.16s/it]

 65%|██████▍   | 2116/3268 [40:52<22:14,  1.16s/it]

 65%|██████▍   | 2117/3268 [40:53<22:16,  1.16s/it]

 65%|██████▍   | 2118/3268 [40:54<22:13,  1.16s/it]

 65%|██████▍   | 2119/3268 [40:55<22:12,  1.16s/it]

 65%|██████▍   | 2120/3268 [40:56<22:09,  1.16s/it]

 65%|██████▍   | 2121/3268 [40:58<22:08,  1.16s/it]

 65%|██████▍   | 2122/3268 [40:59<22:07,  1.16s/it]

 65%|██████▍   | 2123/3268 [41:00<22:06,  1.16s/it]

 65%|██████▍   | 2124/3268 [41:01<22:05,  1.16s/it]

 65%|██████▌   | 2125/3268 [41:02<22:04,  1.16s/it]

 65%|██████▌   | 2126/3268 [41:03<22:03,  1.16s/it]

 65%|██████▌   | 2127/3268 [41:04<22:02,  1.16s/it]

 65%|██████▌   | 2128/3268 [41:06<22:01,  1.16s/it]

 65%|██████▌   | 2129/3268 [41:07<22:01,  1.16s/it]

 65%|██████▌   | 2130/3268 [41:08<21:58,  1.16s/it]

 65%|██████▌   | 2131/3268 [41:09<21:56,  1.16s/it]

 65%|██████▌   | 2132/3268 [41:10<21:54,  1.16s/it]

 65%|██████▌   | 2133/3268 [41:11<21:52,  1.16s/it]

 65%|██████▌   | 2134/3268 [41:13<21:53,  1.16s/it]

 65%|██████▌   | 2135/3268 [41:14<21:53,  1.16s/it]

 65%|██████▌   | 2136/3268 [41:15<21:52,  1.16s/it]

 65%|██████▌   | 2137/3268 [41:16<21:50,  1.16s/it]

 65%|██████▌   | 2138/3268 [41:17<21:48,  1.16s/it]

 65%|██████▌   | 2139/3268 [41:18<21:47,  1.16s/it]

 65%|██████▌   | 2140/3268 [41:20<21:45,  1.16s/it]

 66%|██████▌   | 2141/3268 [41:21<21:45,  1.16s/it]

 66%|██████▌   | 2142/3268 [41:22<21:44,  1.16s/it]

 66%|██████▌   | 2143/3268 [41:23<21:42,  1.16s/it]

 66%|██████▌   | 2144/3268 [41:24<21:42,  1.16s/it]

 66%|██████▌   | 2145/3268 [41:25<21:41,  1.16s/it]

 66%|██████▌   | 2146/3268 [41:26<21:39,  1.16s/it]

 66%|██████▌   | 2147/3268 [41:28<21:38,  1.16s/it]

 66%|██████▌   | 2148/3268 [41:29<21:38,  1.16s/it]

 66%|██████▌   | 2149/3268 [41:30<21:37,  1.16s/it]

 66%|██████▌   | 2150/3268 [41:31<21:34,  1.16s/it]

 66%|██████▌   | 2151/3268 [41:32<21:32,  1.16s/it]

 66%|██████▌   | 2152/3268 [41:33<21:31,  1.16s/it]

 66%|██████▌   | 2153/3268 [41:35<21:32,  1.16s/it]

 66%|██████▌   | 2154/3268 [41:36<21:32,  1.16s/it]

 66%|██████▌   | 2155/3268 [41:37<21:31,  1.16s/it]

 66%|██████▌   | 2156/3268 [41:38<21:30,  1.16s/it]

 66%|██████▌   | 2157/3268 [41:39<21:29,  1.16s/it]

 66%|██████▌   | 2158/3268 [41:40<21:28,  1.16s/it]

 66%|██████▌   | 2159/3268 [41:42<21:27,  1.16s/it]

 66%|██████▌   | 2160/3268 [41:43<21:26,  1.16s/it]

 66%|██████▌   | 2161/3268 [41:44<21:25,  1.16s/it]

 66%|██████▌   | 2162/3268 [41:45<21:23,  1.16s/it]

 66%|██████▌   | 2163/3268 [41:46<21:21,  1.16s/it]

 66%|██████▌   | 2164/3268 [41:47<21:20,  1.16s/it]

 66%|██████▌   | 2165/3268 [41:49<21:18,  1.16s/it]

 66%|██████▋   | 2166/3268 [41:50<21:16,  1.16s/it]

 66%|██████▋   | 2167/3268 [41:51<21:15,  1.16s/it]

 66%|██████▋   | 2168/3268 [41:52<21:14,  1.16s/it]

 66%|██████▋   | 2169/3268 [41:53<21:12,  1.16s/it]

 66%|██████▋   | 2170/3268 [41:54<21:12,  1.16s/it]

 66%|██████▋   | 2171/3268 [41:55<21:11,  1.16s/it]

 66%|██████▋   | 2172/3268 [41:57<21:10,  1.16s/it]

 66%|██████▋   | 2173/3268 [41:58<21:08,  1.16s/it]

 67%|██████▋   | 2174/3268 [41:59<21:07,  1.16s/it]

 67%|██████▋   | 2175/3268 [42:00<21:07,  1.16s/it]

 67%|██████▋   | 2176/3268 [42:01<21:04,  1.16s/it]

 67%|██████▋   | 2177/3268 [42:02<21:03,  1.16s/it]

 67%|██████▋   | 2178/3268 [42:04<21:01,  1.16s/it]

 67%|██████▋   | 2179/3268 [42:05<21:01,  1.16s/it]

 67%|██████▋   | 2180/3268 [42:06<21:01,  1.16s/it]

 67%|██████▋   | 2181/3268 [42:07<20:59,  1.16s/it]

 67%|██████▋   | 2182/3268 [42:08<20:58,  1.16s/it]

 67%|██████▋   | 2183/3268 [42:09<20:57,  1.16s/it]

 67%|██████▋   | 2184/3268 [42:11<20:55,  1.16s/it]

 67%|██████▋   | 2185/3268 [42:12<20:54,  1.16s/it]

 67%|██████▋   | 2186/3268 [42:13<20:52,  1.16s/it]

 67%|██████▋   | 2187/3268 [42:14<20:51,  1.16s/it]

 67%|██████▋   | 2188/3268 [42:15<20:51,  1.16s/it]

 67%|██████▋   | 2189/3268 [42:16<20:50,  1.16s/it]

 67%|██████▋   | 2190/3268 [42:17<20:49,  1.16s/it]

 67%|██████▋   | 2191/3268 [42:19<20:48,  1.16s/it]

 67%|██████▋   | 2192/3268 [42:20<20:47,  1.16s/it]

 67%|██████▋   | 2193/3268 [42:21<20:46,  1.16s/it]

 67%|██████▋   | 2194/3268 [42:22<20:45,  1.16s/it]

 67%|██████▋   | 2195/3268 [42:23<20:43,  1.16s/it]

 67%|██████▋   | 2196/3268 [42:24<20:40,  1.16s/it]

 67%|██████▋   | 2197/3268 [42:26<20:39,  1.16s/it]

 67%|██████▋   | 2198/3268 [42:27<20:38,  1.16s/it]

 67%|██████▋   | 2199/3268 [42:28<20:38,  1.16s/it]

 67%|██████▋   | 2200/3268 [42:29<20:37,  1.16s/it]

 67%|██████▋   | 2201/3268 [42:30<20:35,  1.16s/it]

 67%|██████▋   | 2202/3268 [42:31<20:34,  1.16s/it]

 67%|██████▋   | 2203/3268 [42:33<20:34,  1.16s/it]

 67%|██████▋   | 2204/3268 [42:34<20:33,  1.16s/it]

 67%|██████▋   | 2205/3268 [42:35<20:31,  1.16s/it]

 68%|██████▊   | 2206/3268 [42:36<20:29,  1.16s/it]

 68%|██████▊   | 2207/3268 [42:37<20:29,  1.16s/it]

 68%|██████▊   | 2208/3268 [42:38<20:27,  1.16s/it]

 68%|██████▊   | 2209/3268 [42:39<20:27,  1.16s/it]

 68%|██████▊   | 2210/3268 [42:41<20:26,  1.16s/it]

 68%|██████▊   | 2211/3268 [42:42<20:26,  1.16s/it]

 68%|██████▊   | 2212/3268 [42:43<20:24,  1.16s/it]

 68%|██████▊   | 2213/3268 [42:44<20:23,  1.16s/it]

 68%|██████▊   | 2214/3268 [42:45<20:22,  1.16s/it]

 68%|██████▊   | 2215/3268 [42:46<20:21,  1.16s/it]

 68%|██████▊   | 2216/3268 [42:48<20:21,  1.16s/it]

 68%|██████▊   | 2217/3268 [42:49<20:19,  1.16s/it]

 68%|██████▊   | 2218/3268 [42:50<20:21,  1.16s/it]

 68%|██████▊   | 2219/3268 [42:51<20:17,  1.16s/it]

 68%|██████▊   | 2220/3268 [42:52<20:16,  1.16s/it]

 68%|██████▊   | 2221/3268 [42:53<20:13,  1.16s/it]

 68%|██████▊   | 2222/3268 [42:55<20:12,  1.16s/it]

 68%|██████▊   | 2223/3268 [42:56<20:11,  1.16s/it]

 68%|██████▊   | 2224/3268 [42:57<20:09,  1.16s/it]

 68%|██████▊   | 2225/3268 [42:58<20:08,  1.16s/it]

 68%|██████▊   | 2226/3268 [42:59<20:07,  1.16s/it]

 68%|██████▊   | 2227/3268 [43:00<20:06,  1.16s/it]

 68%|██████▊   | 2228/3268 [43:02<20:05,  1.16s/it]

 68%|██████▊   | 2229/3268 [43:03<20:03,  1.16s/it]

 68%|██████▊   | 2230/3268 [43:04<20:02,  1.16s/it]

 68%|██████▊   | 2231/3268 [43:05<20:01,  1.16s/it]

 68%|██████▊   | 2232/3268 [43:06<20:00,  1.16s/it]

 68%|██████▊   | 2233/3268 [43:07<19:58,  1.16s/it]

 68%|██████▊   | 2234/3268 [43:08<19:57,  1.16s/it]

 68%|██████▊   | 2235/3268 [43:10<19:58,  1.16s/it]

 68%|██████▊   | 2236/3268 [43:11<19:57,  1.16s/it]

 68%|██████▊   | 2237/3268 [43:12<19:55,  1.16s/it]

 68%|██████▊   | 2238/3268 [43:13<19:54,  1.16s/it]

 69%|██████▊   | 2239/3268 [43:14<19:53,  1.16s/it]

 69%|██████▊   | 2240/3268 [43:15<19:52,  1.16s/it]

 69%|██████▊   | 2241/3268 [43:17<19:51,  1.16s/it]

 69%|██████▊   | 2242/3268 [43:18<19:49,  1.16s/it]

 69%|██████▊   | 2243/3268 [43:19<19:48,  1.16s/it]

 69%|██████▊   | 2244/3268 [43:20<19:47,  1.16s/it]

 69%|██████▊   | 2245/3268 [43:21<19:46,  1.16s/it]

 69%|██████▊   | 2246/3268 [43:22<19:45,  1.16s/it]

 69%|██████▉   | 2247/3268 [43:24<19:45,  1.16s/it]

 69%|██████▉   | 2248/3268 [43:25<19:43,  1.16s/it]

 69%|██████▉   | 2249/3268 [43:26<19:42,  1.16s/it]

 69%|██████▉   | 2250/3268 [43:27<19:41,  1.16s/it]

 69%|██████▉   | 2251/3268 [43:28<19:38,  1.16s/it]

 69%|██████▉   | 2252/3268 [43:29<19:37,  1.16s/it]

 69%|██████▉   | 2253/3268 [43:30<19:35,  1.16s/it]

 69%|██████▉   | 2254/3268 [43:32<19:34,  1.16s/it]

 69%|██████▉   | 2255/3268 [43:33<19:34,  1.16s/it]

 69%|██████▉   | 2256/3268 [43:34<19:33,  1.16s/it]

 69%|██████▉   | 2257/3268 [43:35<19:31,  1.16s/it]

 69%|██████▉   | 2258/3268 [43:36<19:29,  1.16s/it]

 69%|██████▉   | 2259/3268 [43:37<19:30,  1.16s/it]

 69%|██████▉   | 2260/3268 [43:39<19:30,  1.16s/it]

 69%|██████▉   | 2261/3268 [43:40<19:29,  1.16s/it]

 69%|██████▉   | 2262/3268 [43:41<19:27,  1.16s/it]

 69%|██████▉   | 2263/3268 [43:42<19:25,  1.16s/it]

 69%|██████▉   | 2264/3268 [43:43<19:24,  1.16s/it]

 69%|██████▉   | 2265/3268 [43:44<19:23,  1.16s/it]

 69%|██████▉   | 2266/3268 [43:46<19:21,  1.16s/it]

 69%|██████▉   | 2267/3268 [43:47<19:20,  1.16s/it]

 69%|██████▉   | 2268/3268 [43:48<19:20,  1.16s/it]

 69%|██████▉   | 2269/3268 [43:49<19:19,  1.16s/it]

 69%|██████▉   | 2270/3268 [43:50<19:18,  1.16s/it]

 69%|██████▉   | 2271/3268 [43:51<19:16,  1.16s/it]

 70%|██████▉   | 2272/3268 [43:53<19:17,  1.16s/it]

 70%|██████▉   | 2273/3268 [43:54<19:17,  1.16s/it]

 70%|██████▉   | 2274/3268 [43:55<19:16,  1.16s/it]

 70%|██████▉   | 2275/3268 [43:56<19:14,  1.16s/it]

 70%|██████▉   | 2276/3268 [43:57<19:12,  1.16s/it]

 70%|██████▉   | 2277/3268 [43:58<19:10,  1.16s/it]

 70%|██████▉   | 2278/3268 [44:00<19:07,  1.16s/it]

 70%|██████▉   | 2279/3268 [44:01<19:05,  1.16s/it]

 70%|██████▉   | 2280/3268 [44:02<19:05,  1.16s/it]

 70%|██████▉   | 2281/3268 [44:03<19:03,  1.16s/it]

 70%|██████▉   | 2282/3268 [44:04<19:02,  1.16s/it]

 70%|██████▉   | 2283/3268 [44:05<19:01,  1.16s/it]

 70%|██████▉   | 2284/3268 [44:06<19:00,  1.16s/it]

 70%|██████▉   | 2285/3268 [44:08<19:01,  1.16s/it]

 70%|██████▉   | 2286/3268 [44:09<18:58,  1.16s/it]

 70%|██████▉   | 2287/3268 [44:10<18:58,  1.16s/it]

 70%|███████   | 2288/3268 [44:11<18:57,  1.16s/it]

 70%|███████   | 2289/3268 [44:12<18:56,  1.16s/it]

 70%|███████   | 2290/3268 [44:13<18:55,  1.16s/it]

 70%|███████   | 2291/3268 [44:15<18:52,  1.16s/it]

 70%|███████   | 2292/3268 [44:16<18:50,  1.16s/it]

 70%|███████   | 2293/3268 [44:17<18:50,  1.16s/it]

 70%|███████   | 2294/3268 [44:18<18:48,  1.16s/it]

 70%|███████   | 2295/3268 [44:19<18:48,  1.16s/it]

 70%|███████   | 2296/3268 [44:20<18:47,  1.16s/it]

 70%|███████   | 2297/3268 [44:22<18:46,  1.16s/it]

 70%|███████   | 2298/3268 [44:23<18:45,  1.16s/it]

 70%|███████   | 2299/3268 [44:24<18:43,  1.16s/it]

 70%|███████   | 2300/3268 [44:25<18:42,  1.16s/it]

 70%|███████   | 2301/3268 [44:26<18:41,  1.16s/it]

 70%|███████   | 2302/3268 [44:27<18:39,  1.16s/it]

 70%|███████   | 2303/3268 [44:28<18:38,  1.16s/it]

 71%|███████   | 2304/3268 [44:30<18:38,  1.16s/it]

 71%|███████   | 2305/3268 [44:31<18:38,  1.16s/it]

 71%|███████   | 2306/3268 [44:32<18:38,  1.16s/it]

 71%|███████   | 2307/3268 [44:33<18:38,  1.16s/it]

 71%|███████   | 2308/3268 [44:34<18:36,  1.16s/it]

 71%|███████   | 2309/3268 [44:35<18:34,  1.16s/it]

 71%|███████   | 2310/3268 [44:37<18:32,  1.16s/it]

 71%|███████   | 2311/3268 [44:38<18:30,  1.16s/it]

 71%|███████   | 2312/3268 [44:39<18:30,  1.16s/it]

 71%|███████   | 2313/3268 [44:40<18:29,  1.16s/it]

 71%|███████   | 2314/3268 [44:41<18:26,  1.16s/it]

 71%|███████   | 2315/3268 [44:42<18:25,  1.16s/it]

 71%|███████   | 2316/3268 [44:44<18:24,  1.16s/it]

 71%|███████   | 2317/3268 [44:45<18:25,  1.16s/it]

 71%|███████   | 2318/3268 [44:46<18:23,  1.16s/it]

 71%|███████   | 2319/3268 [44:47<18:22,  1.16s/it]

 71%|███████   | 2320/3268 [44:48<18:22,  1.16s/it]

 71%|███████   | 2321/3268 [44:49<18:21,  1.16s/it]

 71%|███████   | 2322/3268 [44:51<18:19,  1.16s/it]

 71%|███████   | 2323/3268 [44:52<18:17,  1.16s/it]

 71%|███████   | 2324/3268 [44:53<18:16,  1.16s/it]

 71%|███████   | 2325/3268 [44:54<18:15,  1.16s/it]

 71%|███████   | 2326/3268 [44:55<18:12,  1.16s/it]

 71%|███████   | 2327/3268 [44:56<18:11,  1.16s/it]

 71%|███████   | 2328/3268 [44:58<18:10,  1.16s/it]

 71%|███████▏  | 2329/3268 [44:59<18:10,  1.16s/it]

 71%|███████▏  | 2330/3268 [45:00<18:10,  1.16s/it]

 71%|███████▏  | 2331/3268 [45:01<18:09,  1.16s/it]

 71%|███████▏  | 2332/3268 [45:02<18:09,  1.16s/it]

 71%|███████▏  | 2333/3268 [45:03<18:07,  1.16s/it]

 71%|███████▏  | 2334/3268 [45:05<18:04,  1.16s/it]

 71%|███████▏  | 2335/3268 [45:06<18:03,  1.16s/it]

 71%|███████▏  | 2336/3268 [45:07<18:02,  1.16s/it]

 72%|███████▏  | 2337/3268 [45:08<18:00,  1.16s/it]

 72%|███████▏  | 2338/3268 [45:09<17:59,  1.16s/it]

 72%|███████▏  | 2339/3268 [45:10<17:58,  1.16s/it]

 72%|███████▏  | 2340/3268 [45:11<17:57,  1.16s/it]

 72%|███████▏  | 2341/3268 [45:13<17:56,  1.16s/it]

 72%|███████▏  | 2342/3268 [45:14<17:54,  1.16s/it]

 72%|███████▏  | 2343/3268 [45:15<17:54,  1.16s/it]

 72%|███████▏  | 2344/3268 [45:16<17:53,  1.16s/it]

 72%|███████▏  | 2345/3268 [45:17<17:51,  1.16s/it]

 72%|███████▏  | 2346/3268 [45:18<17:50,  1.16s/it]

 72%|███████▏  | 2347/3268 [45:20<17:50,  1.16s/it]

 72%|███████▏  | 2348/3268 [45:21<17:48,  1.16s/it]

 72%|███████▏  | 2349/3268 [45:22<17:48,  1.16s/it]

 72%|███████▏  | 2350/3268 [45:23<17:46,  1.16s/it]

 72%|███████▏  | 2351/3268 [45:24<17:45,  1.16s/it]

 72%|███████▏  | 2352/3268 [45:25<17:45,  1.16s/it]

 72%|███████▏  | 2353/3268 [45:27<17:42,  1.16s/it]

 72%|███████▏  | 2354/3268 [45:28<17:41,  1.16s/it]

 72%|███████▏  | 2355/3268 [45:29<17:39,  1.16s/it]

 72%|███████▏  | 2356/3268 [45:30<17:38,  1.16s/it]

 72%|███████▏  | 2357/3268 [45:31<17:36,  1.16s/it]

 72%|███████▏  | 2358/3268 [45:32<17:36,  1.16s/it]

 72%|███████▏  | 2359/3268 [45:34<17:34,  1.16s/it]

 72%|███████▏  | 2360/3268 [45:35<17:34,  1.16s/it]

 72%|███████▏  | 2361/3268 [45:36<17:35,  1.16s/it]

 72%|███████▏  | 2362/3268 [45:37<17:33,  1.16s/it]

 72%|███████▏  | 2363/3268 [45:38<17:32,  1.16s/it]

 72%|███████▏  | 2364/3268 [45:39<17:31,  1.16s/it]

 72%|███████▏  | 2365/3268 [45:41<17:29,  1.16s/it]

 72%|███████▏  | 2366/3268 [45:42<17:27,  1.16s/it]

 72%|███████▏  | 2367/3268 [45:43<17:25,  1.16s/it]

 72%|███████▏  | 2368/3268 [45:44<17:24,  1.16s/it]

 72%|███████▏  | 2369/3268 [45:45<17:23,  1.16s/it]

 73%|███████▎  | 2370/3268 [45:46<17:23,  1.16s/it]

 73%|███████▎  | 2371/3268 [45:47<17:20,  1.16s/it]

 73%|███████▎  | 2372/3268 [45:49<17:19,  1.16s/it]

 73%|███████▎  | 2373/3268 [45:50<17:19,  1.16s/it]

 73%|███████▎  | 2374/3268 [45:51<17:18,  1.16s/it]

 73%|███████▎  | 2375/3268 [45:52<17:18,  1.16s/it]

 73%|███████▎  | 2376/3268 [45:53<17:17,  1.16s/it]

 73%|███████▎  | 2377/3268 [45:54<17:16,  1.16s/it]

 73%|███████▎  | 2378/3268 [45:56<17:14,  1.16s/it]

 73%|███████▎  | 2379/3268 [45:57<17:12,  1.16s/it]

 73%|███████▎  | 2380/3268 [45:58<17:11,  1.16s/it]

 73%|███████▎  | 2381/3268 [45:59<17:09,  1.16s/it]

 73%|███████▎  | 2382/3268 [46:00<17:08,  1.16s/it]

 73%|███████▎  | 2383/3268 [46:01<17:07,  1.16s/it]

 73%|███████▎  | 2384/3268 [46:03<17:06,  1.16s/it]

 73%|███████▎  | 2385/3268 [46:04<17:06,  1.16s/it]

 73%|███████▎  | 2386/3268 [46:05<17:06,  1.16s/it]

 73%|███████▎  | 2387/3268 [46:06<17:05,  1.16s/it]

 73%|███████▎  | 2388/3268 [46:07<17:04,  1.16s/it]

 73%|███████▎  | 2389/3268 [46:08<17:03,  1.16s/it]

 73%|███████▎  | 2390/3268 [46:10<17:01,  1.16s/it]

 73%|███████▎  | 2391/3268 [46:11<16:59,  1.16s/it]

 73%|███████▎  | 2392/3268 [46:12<16:56,  1.16s/it]

 73%|███████▎  | 2393/3268 [46:13<16:55,  1.16s/it]

 73%|███████▎  | 2394/3268 [46:14<16:55,  1.16s/it]

 73%|███████▎  | 2395/3268 [46:15<16:51,  1.16s/it]

 73%|███████▎  | 2396/3268 [46:17<16:50,  1.16s/it]

 73%|███████▎  | 2397/3268 [46:18<16:48,  1.16s/it]

 73%|███████▎  | 2398/3268 [46:19<16:47,  1.16s/it]

 73%|███████▎  | 2399/3268 [46:20<16:47,  1.16s/it]

 73%|███████▎  | 2400/3268 [46:21<16:45,  1.16s/it]

 73%|███████▎  | 2401/3268 [46:22<16:45,  1.16s/it]

 74%|███████▎  | 2402/3268 [46:23<16:43,  1.16s/it]

 74%|███████▎  | 2403/3268 [46:25<16:43,  1.16s/it]

 74%|███████▎  | 2404/3268 [46:26<16:42,  1.16s/it]

 74%|███████▎  | 2405/3268 [46:27<16:43,  1.16s/it]

 74%|███████▎  | 2406/3268 [46:28<16:42,  1.16s/it]

 74%|███████▎  | 2407/3268 [46:29<16:41,  1.16s/it]

 74%|███████▎  | 2408/3268 [46:30<16:39,  1.16s/it]

 74%|███████▎  | 2409/3268 [46:32<16:37,  1.16s/it]

 74%|███████▎  | 2410/3268 [46:33<16:35,  1.16s/it]

 74%|███████▍  | 2411/3268 [46:34<16:34,  1.16s/it]

 74%|███████▍  | 2412/3268 [46:35<16:34,  1.16s/it]

 74%|███████▍  | 2413/3268 [46:36<16:33,  1.16s/it]

 74%|███████▍  | 2414/3268 [46:37<16:33,  1.16s/it]

 74%|███████▍  | 2415/3268 [46:39<16:32,  1.16s/it]

 74%|███████▍  | 2416/3268 [46:40<16:30,  1.16s/it]

 74%|███████▍  | 2417/3268 [46:41<16:29,  1.16s/it]

 74%|███████▍  | 2418/3268 [46:42<16:28,  1.16s/it]

 74%|███████▍  | 2419/3268 [46:43<16:25,  1.16s/it]

 74%|███████▍  | 2420/3268 [46:44<16:24,  1.16s/it]

 74%|███████▍  | 2421/3268 [46:46<16:23,  1.16s/it]

 74%|███████▍  | 2422/3268 [46:47<16:22,  1.16s/it]

 74%|███████▍  | 2423/3268 [46:48<16:20,  1.16s/it]

 74%|███████▍  | 2424/3268 [46:49<16:20,  1.16s/it]

 74%|███████▍  | 2425/3268 [46:50<16:19,  1.16s/it]

 74%|███████▍  | 2426/3268 [46:51<16:17,  1.16s/it]

 74%|███████▍  | 2427/3268 [46:53<16:17,  1.16s/it]

 74%|███████▍  | 2428/3268 [46:54<16:15,  1.16s/it]

 74%|███████▍  | 2429/3268 [46:55<16:14,  1.16s/it]

 74%|███████▍  | 2430/3268 [46:56<16:15,  1.16s/it]

 74%|███████▍  | 2431/3268 [46:57<16:13,  1.16s/it]

 74%|███████▍  | 2432/3268 [46:58<16:12,  1.16s/it]

 74%|███████▍  | 2433/3268 [47:00<16:10,  1.16s/it]

 74%|███████▍  | 2434/3268 [47:01<16:08,  1.16s/it]

 75%|███████▍  | 2435/3268 [47:02<16:07,  1.16s/it]

 75%|███████▍  | 2436/3268 [47:03<16:06,  1.16s/it]

 75%|███████▍  | 2437/3268 [47:04<16:05,  1.16s/it]

 75%|███████▍  | 2438/3268 [47:05<16:04,  1.16s/it]

 75%|███████▍  | 2439/3268 [47:06<16:03,  1.16s/it]

 75%|███████▍  | 2440/3268 [47:08<16:03,  1.16s/it]

 75%|███████▍  | 2441/3268 [47:09<16:01,  1.16s/it]

 75%|███████▍  | 2442/3268 [47:10<16:00,  1.16s/it]

 75%|███████▍  | 2443/3268 [47:11<15:58,  1.16s/it]

 75%|███████▍  | 2444/3268 [47:12<15:57,  1.16s/it]

 75%|███████▍  | 2445/3268 [47:13<15:55,  1.16s/it]

 75%|███████▍  | 2446/3268 [47:15<15:54,  1.16s/it]

 75%|███████▍  | 2447/3268 [47:16<15:54,  1.16s/it]

 75%|███████▍  | 2448/3268 [47:17<15:53,  1.16s/it]

 75%|███████▍  | 2449/3268 [47:18<15:53,  1.16s/it]

 75%|███████▍  | 2450/3268 [47:19<15:51,  1.16s/it]

 75%|███████▌  | 2451/3268 [47:20<15:49,  1.16s/it]

 75%|███████▌  | 2452/3268 [47:22<15:47,  1.16s/it]

 75%|███████▌  | 2453/3268 [47:23<15:46,  1.16s/it]

 75%|███████▌  | 2454/3268 [47:24<15:44,  1.16s/it]

 75%|███████▌  | 2455/3268 [47:25<15:44,  1.16s/it]

 75%|███████▌  | 2456/3268 [47:26<15:43,  1.16s/it]

 75%|███████▌  | 2457/3268 [47:27<15:42,  1.16s/it]

 75%|███████▌  | 2458/3268 [47:29<15:42,  1.16s/it]

 75%|███████▌  | 2459/3268 [47:30<15:41,  1.16s/it]

 75%|███████▌  | 2460/3268 [47:31<15:39,  1.16s/it]

 75%|███████▌  | 2461/3268 [47:32<15:38,  1.16s/it]

 75%|███████▌  | 2462/3268 [47:33<15:36,  1.16s/it]

 75%|███████▌  | 2463/3268 [47:34<15:34,  1.16s/it]

 75%|███████▌  | 2464/3268 [47:36<15:32,  1.16s/it]

 75%|███████▌  | 2465/3268 [47:37<15:30,  1.16s/it]

 75%|███████▌  | 2466/3268 [47:38<15:30,  1.16s/it]

 75%|███████▌  | 2467/3268 [47:39<15:29,  1.16s/it]

 76%|███████▌  | 2468/3268 [47:40<15:28,  1.16s/it]

 76%|███████▌  | 2469/3268 [47:41<15:27,  1.16s/it]

 76%|███████▌  | 2470/3268 [47:42<15:26,  1.16s/it]

 76%|███████▌  | 2471/3268 [47:44<15:24,  1.16s/it]

 76%|███████▌  | 2472/3268 [47:45<15:23,  1.16s/it]

 76%|███████▌  | 2473/3268 [47:46<15:22,  1.16s/it]

 76%|███████▌  | 2474/3268 [47:47<15:21,  1.16s/it]

 76%|███████▌  | 2475/3268 [47:48<15:19,  1.16s/it]

 76%|███████▌  | 2476/3268 [47:49<15:19,  1.16s/it]

 76%|███████▌  | 2477/3268 [47:51<15:18,  1.16s/it]

 76%|███████▌  | 2478/3268 [47:52<15:16,  1.16s/it]

 76%|███████▌  | 2479/3268 [47:53<15:15,  1.16s/it]

 76%|███████▌  | 2480/3268 [47:54<15:15,  1.16s/it]

 76%|███████▌  | 2481/3268 [47:55<15:15,  1.16s/it]

 76%|███████▌  | 2482/3268 [47:56<15:13,  1.16s/it]

 76%|███████▌  | 2483/3268 [47:58<15:13,  1.16s/it]

 76%|███████▌  | 2484/3268 [47:59<15:11,  1.16s/it]

 76%|███████▌  | 2485/3268 [48:00<15:10,  1.16s/it]

 76%|███████▌  | 2486/3268 [48:01<15:09,  1.16s/it]

 76%|███████▌  | 2487/3268 [48:02<15:07,  1.16s/it]

 76%|███████▌  | 2488/3268 [48:03<15:05,  1.16s/it]

 76%|███████▌  | 2489/3268 [48:05<15:04,  1.16s/it]

 76%|███████▌  | 2490/3268 [48:06<15:03,  1.16s/it]

 76%|███████▌  | 2491/3268 [48:07<15:03,  1.16s/it]

 76%|███████▋  | 2492/3268 [48:08<15:02,  1.16s/it]

 76%|███████▋  | 2493/3268 [48:09<15:00,  1.16s/it]

 76%|███████▋  | 2494/3268 [48:10<14:59,  1.16s/it]

 76%|███████▋  | 2495/3268 [48:12<14:57,  1.16s/it]

 76%|███████▋  | 2496/3268 [48:13<14:56,  1.16s/it]

 76%|███████▋  | 2497/3268 [48:14<14:56,  1.16s/it]

 76%|███████▋  | 2498/3268 [48:15<14:55,  1.16s/it]

 76%|███████▋  | 2499/3268 [48:16<14:53,  1.16s/it]

 76%|███████▋  | 2500/3268 [48:17<14:51,  1.16s/it]

 77%|███████▋  | 2501/3268 [48:19<14:50,  1.16s/it]

 77%|███████▋  | 2502/3268 [48:20<14:50,  1.16s/it]

 77%|███████▋  | 2503/3268 [48:21<14:48,  1.16s/it]

logging
logging the anndata

 77%|███████▋  | 2504/3268 [48:22<15:23,  1.21s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 77%|███████▋  | 2505/3268 [48:23<15:10,  1.19s/it]

 77%|███████▋  | 2506/3268 [48:24<15:01,  1.18s/it]

 77%|███████▋  | 2507/3268 [48:26<14:54,  1.18s/it]

 77%|███████▋  | 2508/3268 [48:27<14:48,  1.17s/it]

 77%|███████▋  | 2509/3268 [48:28<14:44,  1.17s/it]

 77%|███████▋  | 2510/3268 [48:29<14:40,  1.16s/it]

 77%|███████▋  | 2511/3268 [48:30<14:37,  1.16s/it]

 77%|███████▋  | 2512/3268 [48:31<14:34,  1.16s/it]

 77%|███████▋  | 2513/3268 [48:33<14:31,  1.15s/it]

 77%|███████▋  | 2514/3268 [48:34<14:30,  1.15s/it]

 77%|███████▋  | 2515/3268 [48:35<14:28,  1.15s/it]

 77%|███████▋  | 2516/3268 [48:36<14:27,  1.15s/it]

 77%|███████▋  | 2517/3268 [48:37<14:25,  1.15s/it]

 77%|███████▋  | 2518/3268 [48:38<14:25,  1.15s/it]

 77%|███████▋  | 2519/3268 [48:39<14:24,  1.15s/it]

 77%|███████▋  | 2520/3268 [48:41<14:22,  1.15s/it]

 77%|███████▋  | 2521/3268 [48:42<14:22,  1.15s/it]

 77%|███████▋  | 2522/3268 [48:43<14:20,  1.15s/it]

 77%|███████▋  | 2523/3268 [48:44<14:19,  1.15s/it]

 77%|███████▋  | 2524/3268 [48:45<14:18,  1.15s/it]

 77%|███████▋  | 2525/3268 [48:46<14:17,  1.15s/it]

 77%|███████▋  | 2526/3268 [48:48<14:16,  1.15s/it]

 77%|███████▋  | 2527/3268 [48:49<14:15,  1.15s/it]

 77%|███████▋  | 2528/3268 [48:50<14:14,  1.16s/it]

 77%|███████▋  | 2529/3268 [48:51<14:13,  1.15s/it]

 77%|███████▋  | 2530/3268 [48:52<14:11,  1.15s/it]

 77%|███████▋  | 2531/3268 [48:53<14:10,  1.15s/it]

 77%|███████▋  | 2532/3268 [48:54<14:10,  1.16s/it]

 78%|███████▊  | 2533/3268 [48:56<14:08,  1.15s/it]

 78%|███████▊  | 2534/3268 [48:57<14:07,  1.16s/it]

 78%|███████▊  | 2535/3268 [48:58<14:06,  1.15s/it]

 78%|███████▊  | 2536/3268 [48:59<14:04,  1.15s/it]

 78%|███████▊  | 2537/3268 [49:00<14:03,  1.15s/it]

 78%|███████▊  | 2538/3268 [49:01<14:02,  1.15s/it]

 78%|███████▊  | 2539/3268 [49:03<14:01,  1.15s/it]

 78%|███████▊  | 2540/3268 [49:04<14:01,  1.16s/it]

 78%|███████▊  | 2541/3268 [49:05<13:59,  1.16s/it]

 78%|███████▊  | 2542/3268 [49:06<13:59,  1.16s/it]

 78%|███████▊  | 2543/3268 [49:07<13:57,  1.16s/it]

 78%|███████▊  | 2544/3268 [49:08<13:55,  1.15s/it]

 78%|███████▊  | 2545/3268 [49:09<13:54,  1.15s/it]

 78%|███████▊  | 2546/3268 [49:11<13:53,  1.15s/it]

 78%|███████▊  | 2547/3268 [49:12<13:52,  1.15s/it]

 78%|███████▊  | 2548/3268 [49:13<13:51,  1.15s/it]

 78%|███████▊  | 2549/3268 [49:14<13:50,  1.15s/it]

 78%|███████▊  | 2550/3268 [49:15<13:49,  1.16s/it]

 78%|███████▊  | 2551/3268 [49:16<13:48,  1.16s/it]

 78%|███████▊  | 2552/3268 [49:18<13:47,  1.16s/it]

 78%|███████▊  | 2553/3268 [49:19<13:45,  1.15s/it]

 78%|███████▊  | 2554/3268 [49:20<13:44,  1.15s/it]

 78%|███████▊  | 2555/3268 [49:21<13:42,  1.15s/it]

 78%|███████▊  | 2556/3268 [49:22<13:41,  1.15s/it]

 78%|███████▊  | 2557/3268 [49:23<13:40,  1.15s/it]

 78%|███████▊  | 2558/3268 [49:24<13:39,  1.15s/it]

 78%|███████▊  | 2559/3268 [49:26<13:39,  1.16s/it]

 78%|███████▊  | 2560/3268 [49:27<13:38,  1.16s/it]

 78%|███████▊  | 2561/3268 [49:28<13:37,  1.16s/it]

 78%|███████▊  | 2562/3268 [49:29<13:36,  1.16s/it]

 78%|███████▊  | 2563/3268 [49:30<13:34,  1.16s/it]

 78%|███████▊  | 2564/3268 [49:31<13:33,  1.16s/it]

 78%|███████▊  | 2565/3268 [49:33<13:32,  1.16s/it]

 79%|███████▊  | 2566/3268 [49:34<13:30,  1.15s/it]

 79%|███████▊  | 2567/3268 [49:35<13:28,  1.15s/it]

 79%|███████▊  | 2568/3268 [49:36<13:27,  1.15s/it]

 79%|███████▊  | 2569/3268 [49:37<13:26,  1.15s/it]

 79%|███████▊  | 2570/3268 [49:38<13:26,  1.16s/it]

 79%|███████▊  | 2571/3268 [49:40<13:24,  1.15s/it]

 79%|███████▊  | 2572/3268 [49:41<13:24,  1.16s/it]

 79%|███████▊  | 2573/3268 [49:42<13:22,  1.15s/it]

 79%|███████▉  | 2574/3268 [49:43<13:21,  1.15s/it]

 79%|███████▉  | 2575/3268 [49:44<13:20,  1.15s/it]

 79%|███████▉  | 2576/3268 [49:45<13:19,  1.16s/it]

 79%|███████▉  | 2577/3268 [49:46<13:19,  1.16s/it]

 79%|███████▉  | 2578/3268 [49:48<13:18,  1.16s/it]

 79%|███████▉  | 2579/3268 [49:49<13:17,  1.16s/it]

 79%|███████▉  | 2580/3268 [49:50<13:15,  1.16s/it]

 79%|███████▉  | 2581/3268 [49:51<13:13,  1.16s/it]

 79%|███████▉  | 2582/3268 [49:52<13:12,  1.15s/it]

 79%|███████▉  | 2583/3268 [49:53<13:10,  1.15s/it]

 79%|███████▉  | 2584/3268 [49:55<13:11,  1.16s/it]

 79%|███████▉  | 2585/3268 [49:56<13:09,  1.16s/it]

 79%|███████▉  | 2586/3268 [49:57<13:07,  1.16s/it]

 79%|███████▉  | 2587/3268 [49:58<13:06,  1.16s/it]

 79%|███████▉  | 2588/3268 [49:59<13:05,  1.16s/it]

 79%|███████▉  | 2589/3268 [50:00<13:04,  1.16s/it]

 79%|███████▉  | 2590/3268 [50:01<13:03,  1.16s/it]

 79%|███████▉  | 2591/3268 [50:03<13:01,  1.15s/it]

 79%|███████▉  | 2592/3268 [50:04<13:01,  1.16s/it]

 79%|███████▉  | 2593/3268 [50:05<13:00,  1.16s/it]

 79%|███████▉  | 2594/3268 [50:06<12:58,  1.16s/it]

 79%|███████▉  | 2595/3268 [50:07<12:57,  1.16s/it]

 79%|███████▉  | 2596/3268 [50:08<12:57,  1.16s/it]

 79%|███████▉  | 2597/3268 [50:10<12:55,  1.16s/it]

 79%|███████▉  | 2598/3268 [50:11<12:54,  1.16s/it]

 80%|███████▉  | 2599/3268 [50:12<12:53,  1.16s/it]

 80%|███████▉  | 2600/3268 [50:13<12:51,  1.16s/it]

 80%|███████▉  | 2601/3268 [50:14<12:50,  1.16s/it]

 80%|███████▉  | 2602/3268 [50:15<12:49,  1.16s/it]

 80%|███████▉  | 2603/3268 [50:16<12:49,  1.16s/it]

 80%|███████▉  | 2604/3268 [50:18<12:47,  1.16s/it]

 80%|███████▉  | 2605/3268 [50:19<12:47,  1.16s/it]

 80%|███████▉  | 2606/3268 [50:20<12:45,  1.16s/it]

 80%|███████▉  | 2607/3268 [50:21<12:43,  1.16s/it]

 80%|███████▉  | 2608/3268 [50:22<12:42,  1.15s/it]

 80%|███████▉  | 2609/3268 [50:23<12:40,  1.15s/it]

 80%|███████▉  | 2610/3268 [50:25<12:40,  1.16s/it]

 80%|███████▉  | 2611/3268 [50:26<12:39,  1.16s/it]

 80%|███████▉  | 2612/3268 [50:27<12:38,  1.16s/it]

 80%|███████▉  | 2613/3268 [50:28<12:37,  1.16s/it]

 80%|███████▉  | 2614/3268 [50:29<12:35,  1.16s/it]

 80%|████████  | 2615/3268 [50:30<12:34,  1.16s/it]

 80%|████████  | 2616/3268 [50:32<12:33,  1.16s/it]

 80%|████████  | 2617/3268 [50:33<12:31,  1.15s/it]

 80%|████████  | 2618/3268 [50:34<12:31,  1.16s/it]

 80%|████████  | 2619/3268 [50:35<12:30,  1.16s/it]

 80%|████████  | 2620/3268 [50:36<12:29,  1.16s/it]

 80%|████████  | 2621/3268 [50:37<12:28,  1.16s/it]

 80%|████████  | 2622/3268 [50:38<12:27,  1.16s/it]

 80%|████████  | 2623/3268 [50:40<12:26,  1.16s/it]

 80%|████████  | 2624/3268 [50:41<12:24,  1.16s/it]

 80%|████████  | 2625/3268 [50:42<12:23,  1.16s/it]

 80%|████████  | 2626/3268 [50:43<12:21,  1.16s/it]

 80%|████████  | 2627/3268 [50:44<12:20,  1.16s/it]

 80%|████████  | 2628/3268 [50:45<12:19,  1.15s/it]

 80%|████████  | 2629/3268 [50:47<12:18,  1.16s/it]

 80%|████████  | 2630/3268 [50:48<12:17,  1.16s/it]

 81%|████████  | 2631/3268 [50:49<12:15,  1.16s/it]

 81%|████████  | 2632/3268 [50:50<12:15,  1.16s/it]

 81%|████████  | 2633/3268 [50:51<12:13,  1.16s/it]

 81%|████████  | 2634/3268 [50:52<12:13,  1.16s/it]

 81%|████████  | 2635/3268 [50:53<12:11,  1.16s/it]

 81%|████████  | 2636/3268 [50:55<12:10,  1.16s/it]

 81%|████████  | 2637/3268 [50:56<12:09,  1.16s/it]

 81%|████████  | 2638/3268 [50:57<12:07,  1.16s/it]

 81%|████████  | 2639/3268 [50:58<12:07,  1.16s/it]

 81%|████████  | 2640/3268 [50:59<12:06,  1.16s/it]

 81%|████████  | 2641/3268 [51:00<12:05,  1.16s/it]

 81%|████████  | 2642/3268 [51:02<12:03,  1.16s/it]

 81%|████████  | 2643/3268 [51:03<12:02,  1.16s/it]

 81%|████████  | 2644/3268 [51:04<12:01,  1.16s/it]

 81%|████████  | 2645/3268 [51:05<12:00,  1.16s/it]

 81%|████████  | 2646/3268 [51:06<11:58,  1.16s/it]

 81%|████████  | 2647/3268 [51:07<11:57,  1.16s/it]

 81%|████████  | 2648/3268 [51:09<11:56,  1.16s/it]

 81%|████████  | 2649/3268 [51:10<11:56,  1.16s/it]

 81%|████████  | 2650/3268 [51:11<11:55,  1.16s/it]

 81%|████████  | 2651/3268 [51:12<11:54,  1.16s/it]

 81%|████████  | 2652/3268 [51:13<11:53,  1.16s/it]

 81%|████████  | 2653/3268 [51:14<11:51,  1.16s/it]

 81%|████████  | 2654/3268 [51:15<11:50,  1.16s/it]

 81%|████████  | 2655/3268 [51:17<11:48,  1.16s/it]

 81%|████████▏ | 2656/3268 [51:18<11:47,  1.16s/it]

 81%|████████▏ | 2657/3268 [51:19<11:46,  1.16s/it]

 81%|████████▏ | 2658/3268 [51:20<11:45,  1.16s/it]

 81%|████████▏ | 2659/3268 [51:21<11:44,  1.16s/it]

 81%|████████▏ | 2660/3268 [51:22<11:43,  1.16s/it]

 81%|████████▏ | 2661/3268 [51:24<11:41,  1.16s/it]

 81%|████████▏ | 2662/3268 [51:25<11:41,  1.16s/it]

 81%|████████▏ | 2663/3268 [51:26<11:39,  1.16s/it]

 82%|████████▏ | 2664/3268 [51:27<11:38,  1.16s/it]

 82%|████████▏ | 2665/3268 [51:28<11:37,  1.16s/it]

 82%|████████▏ | 2666/3268 [51:29<11:36,  1.16s/it]

 82%|████████▏ | 2667/3268 [51:30<11:35,  1.16s/it]

 82%|████████▏ | 2668/3268 [51:32<11:34,  1.16s/it]

 82%|████████▏ | 2669/3268 [51:33<11:32,  1.16s/it]

 82%|████████▏ | 2670/3268 [51:34<11:33,  1.16s/it]

 82%|████████▏ | 2671/3268 [51:35<11:31,  1.16s/it]

 82%|████████▏ | 2672/3268 [51:36<11:29,  1.16s/it]

 82%|████████▏ | 2673/3268 [51:37<11:27,  1.16s/it]

 82%|████████▏ | 2674/3268 [51:39<11:26,  1.16s/it]

 82%|████████▏ | 2675/3268 [51:40<11:25,  1.16s/it]

 82%|████████▏ | 2676/3268 [51:41<11:25,  1.16s/it]

 82%|████████▏ | 2677/3268 [51:42<11:24,  1.16s/it]

 82%|████████▏ | 2678/3268 [51:43<11:22,  1.16s/it]

 82%|████████▏ | 2679/3268 [51:44<11:21,  1.16s/it]

 82%|████████▏ | 2680/3268 [51:46<11:20,  1.16s/it]

 82%|████████▏ | 2681/3268 [51:47<11:19,  1.16s/it]

 82%|████████▏ | 2682/3268 [51:48<11:17,  1.16s/it]

 82%|████████▏ | 2683/3268 [51:49<11:16,  1.16s/it]

 82%|████████▏ | 2684/3268 [51:50<11:15,  1.16s/it]

 82%|████████▏ | 2685/3268 [51:51<11:13,  1.16s/it]

 82%|████████▏ | 2686/3268 [51:52<11:12,  1.16s/it]

 82%|████████▏ | 2687/3268 [51:54<11:11,  1.16s/it]

 82%|████████▏ | 2688/3268 [51:55<11:10,  1.16s/it]

 82%|████████▏ | 2689/3268 [51:56<11:09,  1.16s/it]

 82%|████████▏ | 2690/3268 [51:57<11:07,  1.16s/it]

 82%|████████▏ | 2691/3268 [51:58<11:07,  1.16s/it]

 82%|████████▏ | 2692/3268 [51:59<11:06,  1.16s/it]

 82%|████████▏ | 2693/3268 [52:01<11:05,  1.16s/it]

 82%|████████▏ | 2694/3268 [52:02<11:03,  1.16s/it]

 82%|████████▏ | 2695/3268 [52:03<11:01,  1.15s/it]

 82%|████████▏ | 2696/3268 [52:04<11:00,  1.16s/it]

 83%|████████▎ | 2697/3268 [52:05<11:00,  1.16s/it]

 83%|████████▎ | 2698/3268 [52:06<10:59,  1.16s/it]

 83%|████████▎ | 2699/3268 [52:08<10:58,  1.16s/it]

 83%|████████▎ | 2700/3268 [52:09<10:57,  1.16s/it]

 83%|████████▎ | 2701/3268 [52:10<10:55,  1.16s/it]

 83%|████████▎ | 2702/3268 [52:11<10:53,  1.16s/it]

 83%|████████▎ | 2703/3268 [52:12<10:52,  1.15s/it]

 83%|████████▎ | 2704/3268 [52:13<10:52,  1.16s/it]

 83%|████████▎ | 2705/3268 [52:14<10:51,  1.16s/it]

 83%|████████▎ | 2706/3268 [52:16<10:50,  1.16s/it]

 83%|████████▎ | 2707/3268 [52:17<10:49,  1.16s/it]

 83%|████████▎ | 2708/3268 [52:18<10:48,  1.16s/it]

 83%|████████▎ | 2709/3268 [52:19<10:47,  1.16s/it]

 83%|████████▎ | 2710/3268 [52:20<10:45,  1.16s/it]

 83%|████████▎ | 2711/3268 [52:21<10:44,  1.16s/it]

 83%|████████▎ | 2712/3268 [52:23<10:43,  1.16s/it]

 83%|████████▎ | 2713/3268 [52:24<10:41,  1.16s/it]

 83%|████████▎ | 2714/3268 [52:25<10:40,  1.16s/it]

 83%|████████▎ | 2715/3268 [52:26<10:41,  1.16s/it]

 83%|████████▎ | 2716/3268 [52:27<10:39,  1.16s/it]

 83%|████████▎ | 2717/3268 [52:28<10:37,  1.16s/it]

 83%|████████▎ | 2718/3268 [52:30<10:36,  1.16s/it]

 83%|████████▎ | 2719/3268 [52:31<10:36,  1.16s/it]

 83%|████████▎ | 2720/3268 [52:32<10:34,  1.16s/it]

 83%|████████▎ | 2721/3268 [52:33<10:33,  1.16s/it]

 83%|████████▎ | 2722/3268 [52:34<10:31,  1.16s/it]

 83%|████████▎ | 2723/3268 [52:35<10:29,  1.16s/it]

 83%|████████▎ | 2724/3268 [52:36<10:29,  1.16s/it]

 83%|████████▎ | 2725/3268 [52:38<10:28,  1.16s/it]

 83%|████████▎ | 2726/3268 [52:39<10:27,  1.16s/it]

 83%|████████▎ | 2727/3268 [52:40<10:26,  1.16s/it]

 83%|████████▎ | 2728/3268 [52:41<10:25,  1.16s/it]

 84%|████████▎ | 2729/3268 [52:42<10:24,  1.16s/it]

 84%|████████▎ | 2730/3268 [52:43<10:23,  1.16s/it]

 84%|████████▎ | 2731/3268 [52:45<10:20,  1.16s/it]

 84%|████████▎ | 2732/3268 [52:46<10:20,  1.16s/it]

 84%|████████▎ | 2733/3268 [52:47<10:19,  1.16s/it]

 84%|████████▎ | 2734/3268 [52:48<10:18,  1.16s/it]

 84%|████████▎ | 2735/3268 [52:49<10:17,  1.16s/it]

 84%|████████▎ | 2736/3268 [52:50<10:16,  1.16s/it]

 84%|████████▍ | 2737/3268 [52:51<10:15,  1.16s/it]

 84%|████████▍ | 2738/3268 [52:53<10:14,  1.16s/it]

 84%|████████▍ | 2739/3268 [52:54<10:12,  1.16s/it]

 84%|████████▍ | 2740/3268 [52:55<10:11,  1.16s/it]

 84%|████████▍ | 2741/3268 [52:56<10:10,  1.16s/it]

 84%|████████▍ | 2742/3268 [52:57<10:08,  1.16s/it]

 84%|████████▍ | 2743/3268 [52:58<10:08,  1.16s/it]

 84%|████████▍ | 2744/3268 [53:00<10:06,  1.16s/it]

 84%|████████▍ | 2745/3268 [53:01<10:05,  1.16s/it]

 84%|████████▍ | 2746/3268 [53:02<10:03,  1.16s/it]

 84%|████████▍ | 2747/3268 [53:03<10:02,  1.16s/it]

 84%|████████▍ | 2748/3268 [53:04<10:01,  1.16s/it]

 84%|████████▍ | 2749/3268 [53:05<10:00,  1.16s/it]

 84%|████████▍ | 2750/3268 [53:07<09:59,  1.16s/it]

 84%|████████▍ | 2751/3268 [53:08<09:58,  1.16s/it]

 84%|████████▍ | 2752/3268 [53:09<09:57,  1.16s/it]

 84%|████████▍ | 2753/3268 [53:10<09:55,  1.16s/it]

 84%|████████▍ | 2754/3268 [53:11<09:54,  1.16s/it]

 84%|████████▍ | 2755/3268 [53:12<09:53,  1.16s/it]

 84%|████████▍ | 2756/3268 [53:13<09:52,  1.16s/it]

 84%|████████▍ | 2757/3268 [53:15<09:50,  1.16s/it]

 84%|████████▍ | 2758/3268 [53:16<09:50,  1.16s/it]

 84%|████████▍ | 2759/3268 [53:17<09:49,  1.16s/it]

 84%|████████▍ | 2760/3268 [53:18<09:47,  1.16s/it]

 84%|████████▍ | 2761/3268 [53:19<09:46,  1.16s/it]

 85%|████████▍ | 2762/3268 [53:20<09:45,  1.16s/it]

 85%|████████▍ | 2763/3268 [53:22<09:44,  1.16s/it]

 85%|████████▍ | 2764/3268 [53:23<09:43,  1.16s/it]

 85%|████████▍ | 2765/3268 [53:24<09:41,  1.16s/it]

 85%|████████▍ | 2766/3268 [53:25<09:39,  1.16s/it]

 85%|████████▍ | 2767/3268 [53:26<09:38,  1.16s/it]

 85%|████████▍ | 2768/3268 [53:27<09:38,  1.16s/it]

 85%|████████▍ | 2769/3268 [53:29<09:37,  1.16s/it]

 85%|████████▍ | 2770/3268 [53:30<09:36,  1.16s/it]

 85%|████████▍ | 2771/3268 [53:31<09:35,  1.16s/it]

 85%|████████▍ | 2772/3268 [53:32<09:34,  1.16s/it]

 85%|████████▍ | 2773/3268 [53:33<09:32,  1.16s/it]

 85%|████████▍ | 2774/3268 [53:34<09:31,  1.16s/it]

 85%|████████▍ | 2775/3268 [53:35<09:30,  1.16s/it]

 85%|████████▍ | 2776/3268 [53:37<09:29,  1.16s/it]

 85%|████████▍ | 2777/3268 [53:38<09:28,  1.16s/it]

 85%|████████▌ | 2778/3268 [53:39<09:27,  1.16s/it]

 85%|████████▌ | 2779/3268 [53:40<09:26,  1.16s/it]

 85%|████████▌ | 2780/3268 [53:41<09:25,  1.16s/it]

 85%|████████▌ | 2781/3268 [53:42<09:23,  1.16s/it]

 85%|████████▌ | 2782/3268 [53:44<09:22,  1.16s/it]

 85%|████████▌ | 2783/3268 [53:45<09:21,  1.16s/it]

 85%|████████▌ | 2784/3268 [53:46<09:21,  1.16s/it]

 85%|████████▌ | 2785/3268 [53:47<09:19,  1.16s/it]

 85%|████████▌ | 2786/3268 [53:48<09:18,  1.16s/it]

 85%|████████▌ | 2787/3268 [53:49<09:17,  1.16s/it]

 85%|████████▌ | 2788/3268 [53:51<09:15,  1.16s/it]

 85%|████████▌ | 2789/3268 [53:52<09:15,  1.16s/it]

 85%|████████▌ | 2790/3268 [53:53<09:13,  1.16s/it]

 85%|████████▌ | 2791/3268 [53:54<09:12,  1.16s/it]

 85%|████████▌ | 2792/3268 [53:55<09:11,  1.16s/it]

 85%|████████▌ | 2793/3268 [53:56<09:10,  1.16s/it]

 85%|████████▌ | 2794/3268 [53:57<09:09,  1.16s/it]

 86%|████████▌ | 2795/3268 [53:59<09:08,  1.16s/it]

 86%|████████▌ | 2796/3268 [54:00<09:07,  1.16s/it]

 86%|████████▌ | 2797/3268 [54:01<09:05,  1.16s/it]

 86%|████████▌ | 2798/3268 [54:02<09:04,  1.16s/it]

 86%|████████▌ | 2799/3268 [54:03<09:03,  1.16s/it]

 86%|████████▌ | 2800/3268 [54:04<09:01,  1.16s/it]

 86%|████████▌ | 2801/3268 [54:06<09:00,  1.16s/it]

 86%|████████▌ | 2802/3268 [54:07<08:59,  1.16s/it]

 86%|████████▌ | 2803/3268 [54:08<08:58,  1.16s/it]

 86%|████████▌ | 2804/3268 [54:09<08:57,  1.16s/it]

 86%|████████▌ | 2805/3268 [54:10<08:56,  1.16s/it]

 86%|████████▌ | 2806/3268 [54:11<08:54,  1.16s/it]

 86%|████████▌ | 2807/3268 [54:13<08:53,  1.16s/it]

 86%|████████▌ | 2808/3268 [54:14<08:52,  1.16s/it]

 86%|████████▌ | 2809/3268 [54:15<08:51,  1.16s/it]

 86%|████████▌ | 2810/3268 [54:16<08:50,  1.16s/it]

 86%|████████▌ | 2811/3268 [54:17<08:48,  1.16s/it]

 86%|████████▌ | 2812/3268 [54:18<08:47,  1.16s/it]

 86%|████████▌ | 2813/3268 [54:19<08:46,  1.16s/it]

 86%|████████▌ | 2814/3268 [54:21<08:45,  1.16s/it]

 86%|████████▌ | 2815/3268 [54:22<08:44,  1.16s/it]

 86%|████████▌ | 2816/3268 [54:23<08:43,  1.16s/it]

 86%|████████▌ | 2817/3268 [54:24<08:42,  1.16s/it]

 86%|████████▌ | 2818/3268 [54:25<08:41,  1.16s/it]

 86%|████████▋ | 2819/3268 [54:26<08:40,  1.16s/it]

 86%|████████▋ | 2820/3268 [54:28<08:39,  1.16s/it]

 86%|████████▋ | 2821/3268 [54:29<08:38,  1.16s/it]

 86%|████████▋ | 2822/3268 [54:30<08:37,  1.16s/it]

 86%|████████▋ | 2823/3268 [54:31<08:35,  1.16s/it]

 86%|████████▋ | 2824/3268 [54:32<08:34,  1.16s/it]

 86%|████████▋ | 2825/3268 [54:33<08:32,  1.16s/it]

 86%|████████▋ | 2826/3268 [54:35<08:31,  1.16s/it]

 87%|████████▋ | 2827/3268 [54:36<08:30,  1.16s/it]

 87%|████████▋ | 2828/3268 [54:37<08:29,  1.16s/it]

 87%|████████▋ | 2829/3268 [54:38<08:29,  1.16s/it]

 87%|████████▋ | 2830/3268 [54:39<08:28,  1.16s/it]

 87%|████████▋ | 2831/3268 [54:40<08:27,  1.16s/it]

 87%|████████▋ | 2832/3268 [54:41<08:25,  1.16s/it]

 87%|████████▋ | 2833/3268 [54:43<08:24,  1.16s/it]

 87%|████████▋ | 2834/3268 [54:44<08:23,  1.16s/it]

 87%|████████▋ | 2835/3268 [54:45<08:22,  1.16s/it]

 87%|████████▋ | 2836/3268 [54:46<08:20,  1.16s/it]

 87%|████████▋ | 2837/3268 [54:47<08:19,  1.16s/it]

 87%|████████▋ | 2838/3268 [54:48<08:17,  1.16s/it]

 87%|████████▋ | 2839/3268 [54:50<08:16,  1.16s/it]

 87%|████████▋ | 2840/3268 [54:51<08:15,  1.16s/it]

 87%|████████▋ | 2841/3268 [54:52<08:14,  1.16s/it]

 87%|████████▋ | 2842/3268 [54:53<08:13,  1.16s/it]

 87%|████████▋ | 2843/3268 [54:54<08:12,  1.16s/it]

 87%|████████▋ | 2844/3268 [54:55<08:11,  1.16s/it]

 87%|████████▋ | 2845/3268 [54:57<08:10,  1.16s/it]

 87%|████████▋ | 2846/3268 [54:58<08:08,  1.16s/it]

 87%|████████▋ | 2847/3268 [54:59<08:07,  1.16s/it]

 87%|████████▋ | 2848/3268 [55:00<08:06,  1.16s/it]

 87%|████████▋ | 2849/3268 [55:01<08:05,  1.16s/it]

 87%|████████▋ | 2850/3268 [55:02<08:03,  1.16s/it]

 87%|████████▋ | 2851/3268 [55:04<08:03,  1.16s/it]

 87%|████████▋ | 2852/3268 [55:05<08:03,  1.16s/it]

 87%|████████▋ | 2853/3268 [55:06<08:02,  1.16s/it]

 87%|████████▋ | 2854/3268 [55:07<08:00,  1.16s/it]

 87%|████████▋ | 2855/3268 [55:08<07:59,  1.16s/it]

 87%|████████▋ | 2856/3268 [55:09<07:57,  1.16s/it]

 87%|████████▋ | 2857/3268 [55:10<07:56,  1.16s/it]

 87%|████████▋ | 2858/3268 [55:12<07:54,  1.16s/it]

 87%|████████▋ | 2859/3268 [55:13<07:53,  1.16s/it]

 88%|████████▊ | 2860/3268 [55:14<07:52,  1.16s/it]

 88%|████████▊ | 2861/3268 [55:15<07:51,  1.16s/it]

 88%|████████▊ | 2862/3268 [55:16<07:56,  1.17s/it]

 88%|████████▊ | 2863/3268 [55:17<07:52,  1.17s/it]

 88%|████████▊ | 2864/3268 [55:19<07:50,  1.16s/it]

 88%|████████▊ | 2865/3268 [55:20<07:48,  1.16s/it]

 88%|████████▊ | 2866/3268 [55:21<07:47,  1.16s/it]

 88%|████████▊ | 2867/3268 [55:22<07:45,  1.16s/it]

 88%|████████▊ | 2868/3268 [55:23<07:44,  1.16s/it]

 88%|████████▊ | 2869/3268 [55:24<07:42,  1.16s/it]

 88%|████████▊ | 2870/3268 [55:26<07:42,  1.16s/it]

 88%|████████▊ | 2871/3268 [55:27<07:40,  1.16s/it]

 88%|████████▊ | 2872/3268 [55:28<07:39,  1.16s/it]

 88%|████████▊ | 2873/3268 [55:29<07:37,  1.16s/it]

 88%|████████▊ | 2874/3268 [55:30<07:36,  1.16s/it]

 88%|████████▊ | 2875/3268 [55:31<07:35,  1.16s/it]

 88%|████████▊ | 2876/3268 [55:33<07:34,  1.16s/it]

 88%|████████▊ | 2877/3268 [55:34<07:33,  1.16s/it]

 88%|████████▊ | 2878/3268 [55:35<07:32,  1.16s/it]

 88%|████████▊ | 2879/3268 [55:36<07:31,  1.16s/it]

 88%|████████▊ | 2880/3268 [55:37<07:30,  1.16s/it]

 88%|████████▊ | 2881/3268 [55:38<07:29,  1.16s/it]

 88%|████████▊ | 2882/3268 [55:39<07:27,  1.16s/it]

 88%|████████▊ | 2883/3268 [55:41<07:26,  1.16s/it]

 88%|████████▊ | 2884/3268 [55:42<07:24,  1.16s/it]

 88%|████████▊ | 2885/3268 [55:43<07:23,  1.16s/it]

 88%|████████▊ | 2886/3268 [55:44<07:23,  1.16s/it]

 88%|████████▊ | 2887/3268 [55:45<07:22,  1.16s/it]

 88%|████████▊ | 2888/3268 [55:46<07:21,  1.16s/it]

 88%|████████▊ | 2889/3268 [55:48<07:20,  1.16s/it]

 88%|████████▊ | 2890/3268 [55:49<07:18,  1.16s/it]

 88%|████████▊ | 2891/3268 [55:50<07:17,  1.16s/it]

 88%|████████▊ | 2892/3268 [55:51<07:16,  1.16s/it]

 89%|████████▊ | 2893/3268 [55:52<07:14,  1.16s/it]

 89%|████████▊ | 2894/3268 [55:53<07:13,  1.16s/it]

 89%|████████▊ | 2895/3268 [55:55<07:12,  1.16s/it]

 89%|████████▊ | 2896/3268 [55:56<07:11,  1.16s/it]

 89%|████████▊ | 2897/3268 [55:57<07:10,  1.16s/it]

 89%|████████▊ | 2898/3268 [55:58<07:09,  1.16s/it]

 89%|████████▊ | 2899/3268 [55:59<07:08,  1.16s/it]

 89%|████████▊ | 2900/3268 [56:00<07:07,  1.16s/it]

 89%|████████▉ | 2901/3268 [56:02<07:05,  1.16s/it]

 89%|████████▉ | 2902/3268 [56:03<07:04,  1.16s/it]

 89%|████████▉ | 2903/3268 [56:04<07:03,  1.16s/it]

 89%|████████▉ | 2904/3268 [56:05<07:02,  1.16s/it]

 89%|████████▉ | 2905/3268 [56:06<07:00,  1.16s/it]

 89%|████████▉ | 2906/3268 [56:07<06:59,  1.16s/it]

 89%|████████▉ | 2907/3268 [56:08<06:58,  1.16s/it]

 89%|████████▉ | 2908/3268 [56:10<06:57,  1.16s/it]

 89%|████████▉ | 2909/3268 [56:11<06:57,  1.16s/it]

 89%|████████▉ | 2910/3268 [56:12<06:55,  1.16s/it]

 89%|████████▉ | 2911/3268 [56:13<06:54,  1.16s/it]

 89%|████████▉ | 2912/3268 [56:14<06:52,  1.16s/it]

 89%|████████▉ | 2913/3268 [56:15<06:51,  1.16s/it]

 89%|████████▉ | 2914/3268 [56:17<06:50,  1.16s/it]

 89%|████████▉ | 2915/3268 [56:18<06:49,  1.16s/it]

 89%|████████▉ | 2916/3268 [56:19<06:48,  1.16s/it]

 89%|████████▉ | 2917/3268 [56:20<06:47,  1.16s/it]

 89%|████████▉ | 2918/3268 [56:21<06:46,  1.16s/it]

 89%|████████▉ | 2919/3268 [56:22<06:44,  1.16s/it]

 89%|████████▉ | 2920/3268 [56:24<06:43,  1.16s/it]

 89%|████████▉ | 2921/3268 [56:25<06:42,  1.16s/it]

 89%|████████▉ | 2922/3268 [56:26<06:40,  1.16s/it]

 89%|████████▉ | 2923/3268 [56:27<06:39,  1.16s/it]

 89%|████████▉ | 2924/3268 [56:28<06:38,  1.16s/it]

 90%|████████▉ | 2925/3268 [56:29<06:37,  1.16s/it]

 90%|████████▉ | 2926/3268 [56:31<06:36,  1.16s/it]

 90%|████████▉ | 2927/3268 [56:32<06:35,  1.16s/it]

 90%|████████▉ | 2928/3268 [56:33<06:34,  1.16s/it]

 90%|████████▉ | 2929/3268 [56:34<06:33,  1.16s/it]

 90%|████████▉ | 2930/3268 [56:35<06:32,  1.16s/it]

 90%|████████▉ | 2931/3268 [56:36<06:30,  1.16s/it]

 90%|████████▉ | 2932/3268 [56:37<06:29,  1.16s/it]

 90%|████████▉ | 2933/3268 [56:39<06:27,  1.16s/it]

 90%|████████▉ | 2934/3268 [56:40<06:26,  1.16s/it]

 90%|████████▉ | 2935/3268 [56:41<06:25,  1.16s/it]

 90%|████████▉ | 2936/3268 [56:42<06:24,  1.16s/it]

 90%|████████▉ | 2937/3268 [56:43<06:23,  1.16s/it]

 90%|████████▉ | 2938/3268 [56:44<06:22,  1.16s/it]

 90%|████████▉ | 2939/3268 [56:46<06:21,  1.16s/it]

 90%|████████▉ | 2940/3268 [56:47<06:20,  1.16s/it]

 90%|████████▉ | 2941/3268 [56:48<06:19,  1.16s/it]

 90%|█████████ | 2942/3268 [56:49<06:17,  1.16s/it]

 90%|█████████ | 2943/3268 [56:50<06:16,  1.16s/it]

 90%|█████████ | 2944/3268 [56:51<06:15,  1.16s/it]

 90%|█████████ | 2945/3268 [56:53<06:14,  1.16s/it]

 90%|█████████ | 2946/3268 [56:54<06:13,  1.16s/it]

 90%|█████████ | 2947/3268 [56:55<06:12,  1.16s/it]

 90%|█████████ | 2948/3268 [56:56<06:11,  1.16s/it]

 90%|█████████ | 2949/3268 [56:57<06:09,  1.16s/it]

 90%|█████████ | 2950/3268 [56:58<06:08,  1.16s/it]

 90%|█████████ | 2951/3268 [57:00<06:07,  1.16s/it]

 90%|█████████ | 2952/3268 [57:01<06:06,  1.16s/it]

 90%|█████████ | 2953/3268 [57:02<06:05,  1.16s/it]

 90%|█████████ | 2954/3268 [57:03<06:04,  1.16s/it]

 90%|█████████ | 2955/3268 [57:04<06:03,  1.16s/it]

 90%|█████████ | 2956/3268 [57:05<06:01,  1.16s/it]

 90%|█████████ | 2957/3268 [57:06<06:00,  1.16s/it]

 91%|█████████ | 2958/3268 [57:08<05:59,  1.16s/it]

 91%|█████████ | 2959/3268 [57:09<05:58,  1.16s/it]

 91%|█████████ | 2960/3268 [57:10<05:57,  1.16s/it]

 91%|█████████ | 2961/3268 [57:11<05:56,  1.16s/it]

 91%|█████████ | 2962/3268 [57:12<05:54,  1.16s/it]

 91%|█████████ | 2963/3268 [57:13<05:53,  1.16s/it]

 91%|█████████ | 2964/3268 [57:15<05:52,  1.16s/it]

 91%|█████████ | 2965/3268 [57:16<05:51,  1.16s/it]

 91%|█████████ | 2966/3268 [57:17<05:49,  1.16s/it]

 91%|█████████ | 2967/3268 [57:18<05:49,  1.16s/it]

 91%|█████████ | 2968/3268 [57:19<05:48,  1.16s/it]

 91%|█████████ | 2969/3268 [57:20<05:46,  1.16s/it]

 91%|█████████ | 2970/3268 [57:22<05:45,  1.16s/it]

 91%|█████████ | 2971/3268 [57:23<05:44,  1.16s/it]

 91%|█████████ | 2972/3268 [57:24<05:43,  1.16s/it]

 91%|█████████ | 2973/3268 [57:25<05:42,  1.16s/it]

 91%|█████████ | 2974/3268 [57:26<05:41,  1.16s/it]

 91%|█████████ | 2975/3268 [57:27<05:40,  1.16s/it]

 91%|█████████ | 2976/3268 [57:29<05:38,  1.16s/it]

 91%|█████████ | 2977/3268 [57:30<05:38,  1.16s/it]

 91%|█████████ | 2978/3268 [57:31<05:36,  1.16s/it]

 91%|█████████ | 2979/3268 [57:32<05:35,  1.16s/it]

 91%|█████████ | 2980/3268 [57:33<05:34,  1.16s/it]

 91%|█████████ | 2981/3268 [57:34<05:33,  1.16s/it]

 91%|█████████ | 2982/3268 [57:35<05:31,  1.16s/it]

 91%|█████████▏| 2983/3268 [57:37<05:30,  1.16s/it]

 91%|█████████▏| 2984/3268 [57:38<05:29,  1.16s/it]

 91%|█████████▏| 2985/3268 [57:39<05:28,  1.16s/it]

 91%|█████████▏| 2986/3268 [57:40<05:27,  1.16s/it]

 91%|█████████▏| 2987/3268 [57:41<05:26,  1.16s/it]

 91%|█████████▏| 2988/3268 [57:42<05:24,  1.16s/it]

 91%|█████████▏| 2989/3268 [57:44<05:23,  1.16s/it]

 91%|█████████▏| 2990/3268 [57:45<05:22,  1.16s/it]

 92%|█████████▏| 2991/3268 [57:46<05:21,  1.16s/it]

 92%|█████████▏| 2992/3268 [57:47<05:20,  1.16s/it]

 92%|█████████▏| 2993/3268 [57:48<05:19,  1.16s/it]

 92%|█████████▏| 2994/3268 [57:49<05:17,  1.16s/it]

 92%|█████████▏| 2995/3268 [57:51<05:16,  1.16s/it]

 92%|█████████▏| 2996/3268 [57:52<05:15,  1.16s/it]

 92%|█████████▏| 2997/3268 [57:53<05:14,  1.16s/it]

 92%|█████████▏| 2998/3268 [57:54<05:13,  1.16s/it]

 92%|█████████▏| 2999/3268 [57:55<05:12,  1.16s/it]

 92%|█████████▏| 3000/3268 [57:56<05:11,  1.16s/it]

 92%|█████████▏| 3001/3268 [57:58<05:10,  1.16s/it]

 92%|█████████▏| 3002/3268 [57:59<05:09,  1.16s/it]

 92%|█████████▏| 3003/3268 [58:00<05:07,  1.16s/it]

 92%|█████████▏| 3004/3268 [58:01<05:06,  1.16s/it]

 92%|█████████▏| 3005/3268 [58:02<05:05,  1.16s/it]

 92%|█████████▏| 3006/3268 [58:03<05:04,  1.16s/it]

 92%|█████████▏| 3007/3268 [58:05<05:02,  1.16s/it]

 92%|█████████▏| 3008/3268 [58:06<05:01,  1.16s/it]

 92%|█████████▏| 3009/3268 [58:07<05:00,  1.16s/it]

 92%|█████████▏| 3010/3268 [58:08<04:59,  1.16s/it]

 92%|█████████▏| 3011/3268 [58:09<04:58,  1.16s/it]

 92%|█████████▏| 3012/3268 [58:10<04:57,  1.16s/it]

 92%|█████████▏| 3013/3268 [58:11<04:56,  1.16s/it]

 92%|█████████▏| 3014/3268 [58:13<04:55,  1.16s/it]

 92%|█████████▏| 3015/3268 [58:14<04:53,  1.16s/it]

 92%|█████████▏| 3016/3268 [58:15<04:52,  1.16s/it]

 92%|█████████▏| 3017/3268 [58:16<04:51,  1.16s/it]

 92%|█████████▏| 3018/3268 [58:17<04:49,  1.16s/it]

 92%|█████████▏| 3019/3268 [58:18<04:48,  1.16s/it]

 92%|█████████▏| 3020/3268 [58:20<04:47,  1.16s/it]

 92%|█████████▏| 3021/3268 [58:21<04:46,  1.16s/it]

 92%|█████████▏| 3022/3268 [58:22<04:45,  1.16s/it]

 93%|█████████▎| 3023/3268 [58:23<04:44,  1.16s/it]

 93%|█████████▎| 3024/3268 [58:24<04:43,  1.16s/it]

 93%|█████████▎| 3025/3268 [58:25<04:42,  1.16s/it]

 93%|█████████▎| 3026/3268 [58:27<04:41,  1.16s/it]

 93%|█████████▎| 3027/3268 [58:28<04:39,  1.16s/it]

 93%|█████████▎| 3028/3268 [58:29<04:38,  1.16s/it]

 93%|█████████▎| 3029/3268 [58:30<04:37,  1.16s/it]

 93%|█████████▎| 3030/3268 [58:31<04:36,  1.16s/it]

 93%|█████████▎| 3031/3268 [58:32<04:35,  1.16s/it]

 93%|█████████▎| 3032/3268 [58:34<04:33,  1.16s/it]

 93%|█████████▎| 3033/3268 [58:35<04:32,  1.16s/it]

 93%|█████████▎| 3034/3268 [58:36<04:31,  1.16s/it]

 93%|█████████▎| 3035/3268 [58:37<04:30,  1.16s/it]

 93%|█████████▎| 3036/3268 [58:38<04:29,  1.16s/it]

 93%|█████████▎| 3037/3268 [58:39<04:28,  1.16s/it]

 93%|█████████▎| 3038/3268 [58:41<04:27,  1.16s/it]

 93%|█████████▎| 3039/3268 [58:42<04:25,  1.16s/it]

 93%|█████████▎| 3040/3268 [58:43<04:24,  1.16s/it]

 93%|█████████▎| 3041/3268 [58:44<04:23,  1.16s/it]

 93%|█████████▎| 3042/3268 [58:45<04:22,  1.16s/it]

 93%|█████████▎| 3043/3268 [58:46<04:21,  1.16s/it]

 93%|█████████▎| 3044/3268 [58:47<04:20,  1.16s/it]

 93%|█████████▎| 3045/3268 [58:49<04:18,  1.16s/it]

 93%|█████████▎| 3046/3268 [58:50<04:17,  1.16s/it]

 93%|█████████▎| 3047/3268 [58:51<04:16,  1.16s/it]

 93%|█████████▎| 3048/3268 [58:52<04:15,  1.16s/it]

 93%|█████████▎| 3049/3268 [58:53<04:14,  1.16s/it]

 93%|█████████▎| 3050/3268 [58:54<04:13,  1.16s/it]

 93%|█████████▎| 3051/3268 [58:56<04:11,  1.16s/it]

 93%|█████████▎| 3052/3268 [58:57<04:10,  1.16s/it]

 93%|█████████▎| 3053/3268 [58:58<04:09,  1.16s/it]

 93%|█████████▎| 3054/3268 [58:59<04:08,  1.16s/it]

 93%|█████████▎| 3055/3268 [59:00<04:06,  1.16s/it]

 94%|█████████▎| 3056/3268 [59:01<04:05,  1.16s/it]

 94%|█████████▎| 3057/3268 [59:03<04:04,  1.16s/it]

 94%|█████████▎| 3058/3268 [59:04<04:03,  1.16s/it]

 94%|█████████▎| 3059/3268 [59:05<04:02,  1.16s/it]

 94%|█████████▎| 3060/3268 [59:06<04:01,  1.16s/it]

 94%|█████████▎| 3061/3268 [59:07<04:00,  1.16s/it]

 94%|█████████▎| 3062/3268 [59:08<03:59,  1.16s/it]

 94%|█████████▎| 3063/3268 [59:10<03:57,  1.16s/it]

 94%|█████████▍| 3064/3268 [59:11<03:56,  1.16s/it]

 94%|█████████▍| 3065/3268 [59:12<03:55,  1.16s/it]

 94%|█████████▍| 3066/3268 [59:13<03:54,  1.16s/it]

 94%|█████████▍| 3067/3268 [59:14<03:53,  1.16s/it]

 94%|█████████▍| 3068/3268 [59:15<03:52,  1.16s/it]

 94%|█████████▍| 3069/3268 [59:16<03:50,  1.16s/it]

 94%|█████████▍| 3070/3268 [59:18<03:49,  1.16s/it]

 94%|█████████▍| 3071/3268 [59:19<03:48,  1.16s/it]

 94%|█████████▍| 3072/3268 [59:20<03:47,  1.16s/it]

 94%|█████████▍| 3073/3268 [59:21<03:46,  1.16s/it]

 94%|█████████▍| 3074/3268 [59:22<03:45,  1.16s/it]

 94%|█████████▍| 3075/3268 [59:23<03:44,  1.16s/it]

 94%|█████████▍| 3076/3268 [59:25<03:43,  1.16s/it]

 94%|█████████▍| 3077/3268 [59:26<03:41,  1.16s/it]

 94%|█████████▍| 3078/3268 [59:27<03:40,  1.16s/it]

 94%|█████████▍| 3079/3268 [59:28<03:39,  1.16s/it]

 94%|█████████▍| 3080/3268 [59:29<03:38,  1.16s/it]

 94%|█████████▍| 3081/3268 [59:30<03:37,  1.16s/it]

 94%|█████████▍| 3082/3268 [59:32<03:36,  1.16s/it]

 94%|█████████▍| 3083/3268 [59:33<03:35,  1.16s/it]

 94%|█████████▍| 3084/3268 [59:34<03:34,  1.17s/it]

 94%|█████████▍| 3085/3268 [59:35<03:32,  1.16s/it]

 94%|█████████▍| 3086/3268 [59:36<03:31,  1.16s/it]

 94%|█████████▍| 3087/3268 [59:37<03:30,  1.16s/it]

 94%|█████████▍| 3088/3268 [59:39<03:29,  1.16s/it]

 95%|█████████▍| 3089/3268 [59:40<03:28,  1.16s/it]

 95%|█████████▍| 3090/3268 [59:41<03:27,  1.16s/it]

 95%|█████████▍| 3091/3268 [59:42<03:26,  1.16s/it]

 95%|█████████▍| 3092/3268 [59:43<03:24,  1.16s/it]

 95%|█████████▍| 3093/3268 [59:44<03:23,  1.16s/it]

 95%|█████████▍| 3094/3268 [59:46<03:22,  1.16s/it]

 95%|█████████▍| 3095/3268 [59:47<03:20,  1.16s/it]

 95%|█████████▍| 3096/3268 [59:48<03:19,  1.16s/it]

 95%|█████████▍| 3097/3268 [59:49<03:18,  1.16s/it]

 95%|█████████▍| 3098/3268 [59:50<03:17,  1.16s/it]

 95%|█████████▍| 3099/3268 [59:51<03:16,  1.16s/it]

 95%|█████████▍| 3100/3268 [59:53<03:15,  1.16s/it]

 95%|█████████▍| 3101/3268 [59:54<03:13,  1.16s/it]

 95%|█████████▍| 3102/3268 [59:55<03:12,  1.16s/it]

 95%|█████████▍| 3103/3268 [59:56<03:11,  1.16s/it]

 95%|█████████▍| 3104/3268 [59:57<03:10,  1.16s/it]

 95%|█████████▌| 3105/3268 [59:58<03:09,  1.16s/it]

 95%|█████████▌| 3106/3268 [59:59<03:08,  1.16s/it]

 95%|█████████▌| 3107/3268 [1:00:01<03:07,  1.16s/it]

 95%|█████████▌| 3108/3268 [1:00:02<03:05,  1.16s/it]

 95%|█████████▌| 3109/3268 [1:00:03<03:04,  1.16s/it]

 95%|█████████▌| 3110/3268 [1:00:04<03:03,  1.16s/it]

 95%|█████████▌| 3111/3268 [1:00:05<03:02,  1.16s/it]

 95%|█████████▌| 3112/3268 [1:00:06<03:01,  1.16s/it]

 95%|█████████▌| 3113/3268 [1:00:08<03:00,  1.16s/it]

 95%|█████████▌| 3114/3268 [1:00:09<02:59,  1.16s/it]

 95%|█████████▌| 3115/3268 [1:00:10<02:57,  1.16s/it]

 95%|█████████▌| 3116/3268 [1:00:11<02:56,  1.16s/it]

 95%|█████████▌| 3117/3268 [1:00:12<02:55,  1.16s/it]

 95%|█████████▌| 3118/3268 [1:00:13<02:54,  1.16s/it]

 95%|█████████▌| 3119/3268 [1:00:15<02:53,  1.16s/it]

 95%|█████████▌| 3120/3268 [1:00:16<02:52,  1.16s/it]

 96%|█████████▌| 3121/3268 [1:00:17<02:50,  1.16s/it]

 96%|█████████▌| 3122/3268 [1:00:18<02:49,  1.16s/it]

 96%|█████████▌| 3123/3268 [1:00:19<02:48,  1.16s/it]

 96%|█████████▌| 3124/3268 [1:00:20<02:47,  1.16s/it]

 96%|█████████▌| 3125/3268 [1:00:22<02:45,  1.16s/it]

 96%|█████████▌| 3126/3268 [1:00:23<02:44,  1.16s/it]

 96%|█████████▌| 3127/3268 [1:00:24<02:43,  1.16s/it]

 96%|█████████▌| 3128/3268 [1:00:25<02:42,  1.16s/it]

 96%|█████████▌| 3129/3268 [1:00:26<02:41,  1.16s/it]

logging
logging the anndata

 96%|█████████▌| 3130/3268 [1:00:27<02:45,  1.20s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 96%|█████████▌| 3131/3268 [1:00:29<02:42,  1.18s/it]

 96%|█████████▌| 3132/3268 [1:00:30<02:39,  1.17s/it]

 96%|█████████▌| 3133/3268 [1:00:31<02:37,  1.17s/it]

 96%|█████████▌| 3134/3268 [1:00:32<02:35,  1.16s/it]

 96%|█████████▌| 3135/3268 [1:00:33<02:34,  1.16s/it]

 96%|█████████▌| 3136/3268 [1:00:34<02:32,  1.16s/it]

 96%|█████████▌| 3137/3268 [1:00:36<02:31,  1.16s/it]

 96%|█████████▌| 3138/3268 [1:00:37<02:30,  1.16s/it]

 96%|█████████▌| 3139/3268 [1:00:38<02:29,  1.16s/it]

 96%|█████████▌| 3140/3268 [1:00:39<02:27,  1.16s/it]

 96%|█████████▌| 3141/3268 [1:00:40<02:26,  1.16s/it]

 96%|█████████▌| 3142/3268 [1:00:41<02:25,  1.16s/it]

 96%|█████████▌| 3143/3268 [1:00:43<02:24,  1.16s/it]

 96%|█████████▌| 3144/3268 [1:00:44<02:23,  1.16s/it]

 96%|█████████▌| 3145/3268 [1:00:45<02:22,  1.16s/it]

 96%|█████████▋| 3146/3268 [1:00:46<02:20,  1.16s/it]

 96%|█████████▋| 3147/3268 [1:00:47<02:19,  1.16s/it]

 96%|█████████▋| 3148/3268 [1:00:48<02:18,  1.16s/it]

 96%|█████████▋| 3149/3268 [1:00:49<02:17,  1.16s/it]

 96%|█████████▋| 3150/3268 [1:00:51<02:16,  1.16s/it]

 96%|█████████▋| 3151/3268 [1:00:52<02:15,  1.15s/it]

 96%|█████████▋| 3152/3268 [1:00:53<02:13,  1.15s/it]

 96%|█████████▋| 3153/3268 [1:00:54<02:12,  1.15s/it]

 97%|█████████▋| 3154/3268 [1:00:55<02:11,  1.16s/it]

 97%|█████████▋| 3155/3268 [1:00:56<02:10,  1.15s/it]

 97%|█████████▋| 3156/3268 [1:00:58<02:09,  1.16s/it]

 97%|█████████▋| 3157/3268 [1:00:59<02:08,  1.16s/it]

 97%|█████████▋| 3158/3268 [1:01:00<02:07,  1.16s/it]

 97%|█████████▋| 3159/3268 [1:01:01<02:05,  1.15s/it]

 97%|█████████▋| 3160/3268 [1:01:02<02:04,  1.15s/it]

 97%|█████████▋| 3161/3268 [1:01:03<02:03,  1.15s/it]

 97%|█████████▋| 3162/3268 [1:01:04<02:02,  1.15s/it]

 97%|█████████▋| 3163/3268 [1:01:06<02:01,  1.15s/it]

 97%|█████████▋| 3164/3268 [1:01:07<02:00,  1.15s/it]

 97%|█████████▋| 3165/3268 [1:01:08<01:59,  1.16s/it]

 97%|█████████▋| 3166/3268 [1:01:09<01:57,  1.16s/it]

 97%|█████████▋| 3167/3268 [1:01:10<01:56,  1.16s/it]

 97%|█████████▋| 3168/3268 [1:01:11<01:55,  1.15s/it]

 97%|█████████▋| 3169/3268 [1:01:13<01:54,  1.15s/it]

 97%|█████████▋| 3170/3268 [1:01:14<01:53,  1.15s/it]

 97%|█████████▋| 3171/3268 [1:01:15<01:52,  1.16s/it]

 97%|█████████▋| 3172/3268 [1:01:16<01:50,  1.16s/it]

 97%|█████████▋| 3173/3268 [1:01:17<01:49,  1.16s/it]

 97%|█████████▋| 3174/3268 [1:01:18<01:48,  1.16s/it]

 97%|█████████▋| 3175/3268 [1:01:19<01:47,  1.16s/it]

 97%|█████████▋| 3176/3268 [1:01:21<01:46,  1.15s/it]

 97%|█████████▋| 3177/3268 [1:01:22<01:45,  1.15s/it]

 97%|█████████▋| 3178/3268 [1:01:23<01:43,  1.15s/it]

 97%|█████████▋| 3179/3268 [1:01:24<01:42,  1.16s/it]

 97%|█████████▋| 3180/3268 [1:01:25<01:41,  1.16s/it]

 97%|█████████▋| 3181/3268 [1:01:26<01:40,  1.16s/it]

 97%|█████████▋| 3182/3268 [1:01:28<01:39,  1.16s/it]

 97%|█████████▋| 3183/3268 [1:01:29<01:38,  1.15s/it]

 97%|█████████▋| 3184/3268 [1:01:30<01:36,  1.15s/it]

 97%|█████████▋| 3185/3268 [1:01:31<01:35,  1.15s/it]

 97%|█████████▋| 3186/3268 [1:01:32<01:34,  1.16s/it]

 98%|█████████▊| 3187/3268 [1:01:33<01:33,  1.16s/it]

 98%|█████████▊| 3188/3268 [1:01:34<01:32,  1.16s/it]

 98%|█████████▊| 3189/3268 [1:01:36<01:31,  1.16s/it]

 98%|█████████▊| 3190/3268 [1:01:37<01:30,  1.16s/it]

 98%|█████████▊| 3191/3268 [1:01:38<01:29,  1.16s/it]

 98%|█████████▊| 3192/3268 [1:01:39<01:27,  1.16s/it]

 98%|█████████▊| 3193/3268 [1:01:40<01:26,  1.16s/it]

 98%|█████████▊| 3194/3268 [1:01:41<01:25,  1.16s/it]

 98%|█████████▊| 3195/3268 [1:01:43<01:24,  1.16s/it]

 98%|█████████▊| 3196/3268 [1:01:44<01:23,  1.16s/it]

 98%|█████████▊| 3197/3268 [1:01:45<01:22,  1.16s/it]

 98%|█████████▊| 3198/3268 [1:01:46<01:20,  1.16s/it]

 98%|█████████▊| 3199/3268 [1:01:47<01:19,  1.16s/it]

 98%|█████████▊| 3200/3268 [1:01:48<01:18,  1.16s/it]

 98%|█████████▊| 3201/3268 [1:01:50<01:17,  1.16s/it]

 98%|█████████▊| 3202/3268 [1:01:51<01:16,  1.16s/it]

 98%|█████████▊| 3203/3268 [1:01:52<01:15,  1.16s/it]

 98%|█████████▊| 3204/3268 [1:01:53<01:13,  1.16s/it]

 98%|█████████▊| 3205/3268 [1:01:54<01:12,  1.15s/it]

 98%|█████████▊| 3206/3268 [1:01:55<01:11,  1.15s/it]

 98%|█████████▊| 3207/3268 [1:01:56<01:10,  1.15s/it]

 98%|█████████▊| 3208/3268 [1:01:58<01:09,  1.16s/it]

 98%|█████████▊| 3209/3268 [1:01:59<01:08,  1.16s/it]

 98%|█████████▊| 3210/3268 [1:02:00<01:07,  1.16s/it]

 98%|█████████▊| 3211/3268 [1:02:01<01:05,  1.16s/it]

 98%|█████████▊| 3212/3268 [1:02:02<01:04,  1.16s/it]

 98%|█████████▊| 3213/3268 [1:02:03<01:03,  1.16s/it]

 98%|█████████▊| 3214/3268 [1:02:05<01:02,  1.15s/it]

 98%|█████████▊| 3215/3268 [1:02:06<01:01,  1.15s/it]

 98%|█████████▊| 3216/3268 [1:02:07<01:00,  1.15s/it]

 98%|█████████▊| 3217/3268 [1:02:08<00:58,  1.15s/it]

 98%|█████████▊| 3218/3268 [1:02:09<00:57,  1.15s/it]

 99%|█████████▊| 3219/3268 [1:02:10<00:56,  1.15s/it]

 99%|█████████▊| 3220/3268 [1:02:11<00:55,  1.15s/it]

 99%|█████████▊| 3221/3268 [1:02:13<00:54,  1.15s/it]

 99%|█████████▊| 3222/3268 [1:02:14<00:53,  1.15s/it]

 99%|█████████▊| 3223/3268 [1:02:15<00:51,  1.16s/it]

 99%|█████████▊| 3224/3268 [1:02:16<00:50,  1.16s/it]

 99%|█████████▊| 3225/3268 [1:02:17<00:49,  1.16s/it]

 99%|█████████▊| 3226/3268 [1:02:18<00:48,  1.16s/it]

 99%|█████████▊| 3227/3268 [1:02:20<00:47,  1.16s/it]

 99%|█████████▉| 3228/3268 [1:02:21<00:46,  1.16s/it]

 99%|█████████▉| 3229/3268 [1:02:22<00:45,  1.16s/it]

 99%|█████████▉| 3230/3268 [1:02:23<00:43,  1.16s/it]

 99%|█████████▉| 3231/3268 [1:02:24<00:42,  1.16s/it]

 99%|█████████▉| 3232/3268 [1:02:25<00:41,  1.16s/it]

 99%|█████████▉| 3233/3268 [1:02:26<00:40,  1.16s/it]

 99%|█████████▉| 3234/3268 [1:02:28<00:39,  1.16s/it]

 99%|█████████▉| 3235/3268 [1:02:29<00:38,  1.16s/it]

 99%|█████████▉| 3236/3268 [1:02:30<00:37,  1.16s/it]

 99%|█████████▉| 3237/3268 [1:02:31<00:35,  1.16s/it]

 99%|█████████▉| 3238/3268 [1:02:32<00:34,  1.16s/it]

 99%|█████████▉| 3239/3268 [1:02:33<00:33,  1.16s/it]

 99%|█████████▉| 3240/3268 [1:02:35<00:32,  1.16s/it]

 99%|█████████▉| 3241/3268 [1:02:36<00:31,  1.16s/it]

 99%|█████████▉| 3242/3268 [1:02:37<00:30,  1.16s/it]

 99%|█████████▉| 3243/3268 [1:02:38<00:28,  1.16s/it]

 99%|█████████▉| 3244/3268 [1:02:39<00:27,  1.16s/it]

 99%|█████████▉| 3245/3268 [1:02:40<00:26,  1.16s/it]

 99%|█████████▉| 3246/3268 [1:02:42<00:25,  1.16s/it]

 99%|█████████▉| 3247/3268 [1:02:43<00:24,  1.16s/it]

 99%|█████████▉| 3248/3268 [1:02:44<00:23,  1.15s/it]

 99%|█████████▉| 3249/3268 [1:02:45<00:21,  1.16s/it]

 99%|█████████▉| 3250/3268 [1:02:46<00:20,  1.16s/it]

 99%|█████████▉| 3251/3268 [1:02:47<00:19,  1.16s/it]

100%|█████████▉| 3252/3268 [1:02:48<00:18,  1.16s/it]

100%|█████████▉| 3253/3268 [1:02:50<00:17,  1.16s/it]

100%|█████████▉| 3254/3268 [1:02:51<00:16,  1.16s/it]

100%|█████████▉| 3255/3268 [1:02:52<00:15,  1.16s/it]

100%|█████████▉| 3256/3268 [1:02:53<00:13,  1.15s/it]

100%|█████████▉| 3257/3268 [1:02:54<00:12,  1.16s/it]

100%|█████████▉| 3258/3268 [1:02:55<00:11,  1.16s/it]

100%|█████████▉| 3259/3268 [1:02:57<00:10,  1.16s/it]

100%|█████████▉| 3260/3268 [1:02:58<00:09,  1.16s/it]

100%|█████████▉| 3261/3268 [1:02:59<00:08,  1.16s/it]

100%|█████████▉| 3262/3268 [1:03:00<00:06,  1.16s/it]

100%|█████████▉| 3263/3268 [1:03:01<00:05,  1.16s/it]

100%|█████████▉| 3264/3268 [1:03:02<00:04,  1.16s/it]

100%|█████████▉| 3265/3268 [1:03:03<00:03,  1.16s/it]

100%|█████████▉| 3266/3268 [1:03:05<00:02,  1.16s/it]

100%|█████████▉| 3267/3268 [1:03:06<00:01,  1.16s/it]

100%|██████████| 3268/3268 [1:03:07<00:00,  1.02s/it]

100%|██████████| 3268/3268 [1:03:07<00:00,  1.16s/it]

logging the anndata
AnnData object with n_obs × n_vars = 8806 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

too few cells to embed into a umap
too few cells to compute a clustering

PairwiseArrays with keys: connectivities, distances

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.886151 -13.372179 -12.94814  ... -12.879449 -12.828099 -13.27167 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.77336   -13.1897135 -12.817028  ... -12.915905  -12.763533
 -13.181608 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.234969 -10.527688 -10.488899 ...  -6.619437 -11.138645 -12.68215 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.258423 -12.408105 -12.29144  ... -11.226741 -12.497975 -13.326268]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.282739  -10.7417755 -10.797053  ...  -7.802258  -11.655841
 -13.166108 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.755366 -13.17731  -12.79382  ... -12.842693 -12.728837 -13.151604]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.866629 -13.330537 -12.897593 ... -12.96828  -12.701866 -13.143369]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.435931 -12.084807 -12.408446 ... -12.603768 -12.718252 -12.010803]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.608605 -12.884585 -13.525776 ... -12.505763 -14.278515 -13.462977]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.971289 -12.461773 -12.710317 ... -12.615749 -13.935447 -13.612761]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.712511  -7.007792  -6.4250417 ... -7.404951  -6.1715837 -4.2627325]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.977942 -14.878302 -13.173927 ... -12.723566 -11.418476  -8.562086]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.064979  -8.754723  -8.474873  ... -3.8416932 -8.610553  -8.557    ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.305842  -7.414974  -6.9995112 ... -5.3996224 -6.8543215 -5.842896 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.712021 -13.149658 -12.749734 ... -12.565855 -12.684727 -13.151692]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.5326595 -6.747631  -6.530906  ... -6.154668  -6.5800056 -6.5892334]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.821851 -10.851961  -9.041305 ... -11.630738  -8.353827  -8.142466]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.998601 -13.059753 -12.137312 ... -14.68408  -12.466533 -12.884588]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.917084 -11.550236 -11.138832 ... -15.4423   -13.406121 -13.618291]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.527774 -13.231729 -12.718022 ... -12.043683 -12.011909 -12.652447]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.860951  -8.951851  -7.374112  ... -7.334375  -7.0938993 -8.367974 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.712359 -13.150635 -12.750899 ... -12.571125 -12.675675 -13.14498 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.9925554  -3.9830348  -3.2025468  ... -3.3240504  -0.99052554
 -0.42545235]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.656143 -13.760594 -13.469014 ...  -8.869258 -12.654616 -12.983944]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.566082  -12.476106  -11.945224  ...  -5.3813567 -12.047682
 -12.261651 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.600442  -13.0060835 -12.639525  ... -11.940288  -12.4981785
 -12.956567 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.750702  -8.639941  -8.69048   ... -3.1643975 -7.6083374 -8.13916  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.3529205 -7.2793446 -7.1542277 ... -2.321969  -6.522383  -7.1256247]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.1998515 -7.148268  -6.956775  ... -2.2761087 -6.3903728 -6.9507113]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.173837  -11.243133  -10.565178  ...  -6.1079273 -10.064981
 -10.77222  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.558425  -3.6385942 -3.8508906 ... -5.529532  -3.9525278 -5.114144 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.2000525 -2.6735919 -3.0637043 ... -7.0208445 -5.9841485 -7.6703916]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.0522597 -2.491963  -2.8755991 ... -6.7987165 -5.8730087 -7.5488377]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.453157 -12.874738 -12.468203 ... -12.401416 -12.363303 -12.841044]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.781408  -10.362744   -9.767243  ...  -7.1196694 -11.840872
 -13.086447 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.637744  -9.892544 -10.636022 ...  -6.731933 -14.826303 -16.020466]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.307534  -4.357285  -3.4975483 ... -1.471668  -3.2287102 -3.5289252]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.91679   -6.280486  -5.4567914 ... -5.564007  -5.165594  -5.7080064]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.8596907 -6.141853  -6.5084977 ... -8.491166  -7.3056    -6.2957034]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.7251463  -4.790659   -4.5623155  ... -0.66208214 -4.5132623
 -5.7458086 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.899779 -13.368482 -13.002479 ... -13.094887 -12.73959  -12.923224]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.232563  -12.299819  -11.723227  ...  -6.4231153 -11.175233
 -11.943168 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.047563 -8.871902 -8.572226 ... -8.011665 -8.032901 -8.568806]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.7758136 -5.1737595 -4.2687244 ... -5.7872605 -1.9897592 -1.9976387]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.890409  -10.2792425  -9.872496  ...  -8.810447   -8.460536
  -7.9395757]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.480414  -12.733981  -12.2369995 ... -13.188632  -12.32849
 -12.802546 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.733815 -13.140746 -12.762384 ... -12.846889 -12.693906 -13.052605]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.4788885 -12.917155  -12.499768  ... -12.6513195 -12.356453

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.5591173 -4.743975  -4.447083  ... -1.7742985 -4.162848  -4.5183663]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.8331385 -4.889524  -5.3655357 ... -5.7900705 -6.0104494 -5.1944366]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -4.747919   -4.5011053  -6.5250936 ... -10.128221  -12.148537
 -16.046238 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.661396 -5.93831  -5.299371 ... -9.123192 -5.745502 -5.518344]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.785897  -5.4168096 -4.6736    ... -6.1018434 -5.709757  -7.3206296]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.726462 -13.285721 -11.306918 ... -15.082284 -11.070934 -10.670631]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.1067104 -4.497424  -4.1185303 ... -4.0555377 -3.6023057 -5.04476  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.917823   -9.382169  -10.1200285 ...  -6.2881284 -10.382147
 -11.954821 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.244051  -6.211019  -5.6981616 ... -7.5596027 -5.0965824 -6.594048 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.708707  -14.9731045 -14.708716  ...  -9.047531  -13.440652
 -13.519185 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.634439 -13.11847  -12.692137 ... -12.357434 -12.420696 -12.916452]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.8657327 -5.7998815 -5.3533435 ... -1.6940042 -5.467763  -6.0807714]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.7262535 -11.61051   -11.562974  ...  -8.448339  -11.697513
 -13.033952 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.967253  -11.991796  -11.768124  ...  -6.5682836 -11.16464
 -11.501352 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.950165 -15.924134 -15.341258 ... -14.063641 -13.901703 -12.981601]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.066166  -11.159505  -10.4290695 ...  -7.975698   -9.438665
 -10.797468 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.6327524 -5.868446  -5.306447  ... -2.085633  -5.103016  -6.0687065]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.629776  -9.254122  -8.588141  ... -8.056055  -8.0378475 -8.8631735]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.151749  -6.550139  -6.891382  ... -7.1183753 -7.577485  -8.337978 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.133487 -11.565676 -11.392882 ... -12.685297 -11.847224 -12.627428]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.693841 -12.196071 -11.896047 ... -12.61228  -11.883925 -12.424707]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.744045  -12.145803  -11.882604  ... -12.5127535 -11.944798
 -12.46072  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.524906 -11.050103 -10.952405 ... -12.951523 -11.863748 -13.085905]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.0030365 -10.58704   -10.468547  ... -13.012971  -11.396047
 -12.581801 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.9973345 -12.495679  -12.188432  ... -12.695819  -12.131198
 -12.679559 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.079426  -12.608256  -12.309161  ... -12.7633915 -12.196761
 -12.716847 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.63099    -7.7812614  -8.661011  ...  -9.599743  -12.042212
 -12.781865 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.153815 -12.555066 -12.09285  ... -11.397473 -11.743269 -11.939952]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.023653 -12.349987 -11.919659 ... -10.977082 -11.665577 -11.926588]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.6969323 -6.8950534 -6.88106   ... -6.7808137 -6.8426776 -5.401989 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.227743  -9.967365 -10.865879 ... -15.681442 -13.573999 -13.450913]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.90105   -13.3769045 -12.832949  ... -16.724838  -10.632603
 -10.793181 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.847015  -12.320185  -11.8651085 ... -11.762058  -11.135264
 -10.880803 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.079783  -6.665051  -6.4642043 ... -6.108918  -5.0582323 -5.2032433]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.895025 -11.466363 -11.137869 ... -10.711885 -10.227675 -10.84282 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.9421053 -8.379901  -8.457269  ... -7.6606636 -7.37767   -7.660841 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.579789  -9.826024 -10.293073 ...  -9.253896  -9.374608  -9.952494]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.164103  -8.794877  -8.714089  ... -7.909997  -7.5886264 -8.622782 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.024117  -9.929287  -9.127552  ... -9.278201  -7.2767115 -7.2232533]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.196592  -12.050597  -12.7898855 ... -13.985549  -14.808677
 -14.714275 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.430105 -11.339435 -12.451359 ... -15.887077 -14.394038 -14.432792]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.901824  -12.945773  -13.123017  ... -13.3971405 -14.050799
 -14.236725 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.3868694 -6.787781  -6.658115  ... -9.888135  -7.0377755 -6.191651 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.483408 -12.914139 -12.501394 ... -12.465729 -12.279952 -12.690295]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.22887  -12.630152 -12.25358  ... -12.340132 -12.254102 -12.76433 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.645451  -8.534446  -8.58387   ... -9.081934  -8.983555  -8.3836355]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.348863 -14.093527 -13.345399 ... -13.760888 -12.564181 -10.789381]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.669798  -9.23043   -9.087912 ... -11.515095  -8.738202  -8.446941]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.139982 -10.912274 -10.9305   ... -17.31385  -10.819251  -9.27453 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.250806 -11.287145 -11.025365 ... -14.134669 -10.732824 -12.294118]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.448887  -8.980699  -8.447244  ... -8.500428  -7.472446  -7.2344913]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.589836   -9.414716   -9.633108  ...  -9.869302  -10.2128935
  -9.632849 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.260645 -11.300423 -11.444625 ... -11.936715 -12.112679 -12.165059]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.095515  -8.812948  -8.259416  ... -8.122486  -6.9294324 -6.8148274]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.6486435 -9.395428  -8.774124  ... -8.803804  -7.480822  -7.3894587]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.443139  -9.367877  -9.734524 ...  -9.717998 -10.265967  -9.602922]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.8128114 -8.227124  -7.928876  ... -8.13504   -7.224498  -7.2179346]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.710615  -9.1209135 -8.83927   ... -8.948949  -8.05757   -7.8874927]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.55895  -10.781609 -11.901245 ...  -8.936159 -11.418853 -11.510243]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.417507 -11.57828  -11.581344 ... -11.888063 -11.691221 -11.881362]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.951575 -12.112679 -11.918056 ... -12.337821 -12.253109 -12.240892]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.420715  -7.0348883 -6.810799  ... -6.46021   -6.1897144 -6.3413568]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.692246 -11.336438 -11.734408 ... -11.361415 -10.903138 -13.252409]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.066069  -7.587775  -7.78654   ... -5.9789357 -6.318807  -6.8904257]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.462374 -11.102678 -11.633716 ...  -7.973105 -10.099954 -12.441795]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.5170345 -8.160679  -7.9977603 ... -7.2341647 -5.904142  -6.105547 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.510452  -10.527389  -10.262252  ... -10.455501   -7.5881853
  -7.6337357]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.113887  -8.539376  -8.170862  ... -8.424569  -7.773561  -6.4865255]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.958527  -8.317802  -8.1443815 ... -8.024075  -7.682332  -6.5346007]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.0205207 -7.7097116 -7.5409536 ... -6.9580526 -5.406247  -5.6841774]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.0380745 -7.2014246 -6.3632755 ... -3.512388  -5.5619035 -5.8477645]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.498789  -7.8387575 -8.715789  ... -7.388755  -8.778543  -6.818711 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.260385  -9.743313  -9.438174 ... -10.390285  -9.977388 -10.709408]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.319943  -7.74026   -7.5110354 ... -7.9707174 -7.134911  -7.1947894]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.6775293 -8.103622  -7.8664804 ... -8.298376  -7.4269533 -7.5141335]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.848859  -8.290539  -8.057838  ... -8.47149   -7.6322646 -7.7407055]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.47593   -7.9061623 -7.683995  ... -8.159624  -7.2799234 -7.355703 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.758019 -13.154856 -12.790878 ... -12.817517 -12.707864 -13.058779]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.762451 -13.115781 -12.797656 ... -12.93307  -12.795107 -13.032948]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.101602 -12.418206 -12.118716 ... -12.143129 -12.028225 -12.281354]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.27231  -12.149695 -12.347484 ... -11.249197 -11.421371 -14.159839]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.790087 -9.733031 -9.66041  ... -7.838092 -8.659294 -8.704687]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.987563  -8.690699  -8.4427805 ... -7.799599  -8.346504  -8.22881  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.0105095 -12.355329  -12.008846  ... -12.04963   -11.769001
 -12.028708 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.905771   -8.810452   -9.435292  ... -11.944951  -10.272048
  -7.4191537]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.53634   -11.553089  -10.657245  ...  -6.1145186 -10.966827
 -11.548927 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.79688   -7.813466  -7.061832  ... -2.235898  -6.154411  -6.1561728]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.7004747 -6.4932203 -6.259444  ... -2.0669682 -5.955557  -6.283972 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.057143  -10.874743  -10.252391  ...  -6.150418  -10.6803055
 -11.272903 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.5978513 -7.4965215 -6.563712  ... -7.368383  -6.2881613 -6.7537546]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.09859  -11.653476 -11.040308 ... -11.38311   -9.850603 -10.343272]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.390749  -9.694781  -8.866429  ... -9.373471  -6.1145077 -6.1744494]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.681178  -4.0370603 -3.9075055 ... -1.8901546 -5.953934  -6.717918 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.751761  -9.641611  -9.98576  ... -10.23681  -10.494886  -9.808246]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.0852895 -7.029364  -6.729826  ... -2.4722147 -6.4173627 -7.0683136]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.1568756 -6.9336157 -6.7086596 ... -1.5105867 -6.0639    -6.52843  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.9223921 -4.6530476 -4.1210513 ... -7.1686215 -3.8027663 -5.5985646]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.344957 -12.736435 -12.321976 ... -12.697296 -12.255975 -12.539747]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.232744  -8.091773  -7.7290874 ... -2.6108565 -7.1418743 -7.46631  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.704716 -13.117626 -12.743066 ... -12.861948 -12.686713 -13.098309]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.232506  -8.0867    -7.732644  ... -2.6154826 -7.142251  -7.4532094]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.736698  -7.7197623 -7.404883  ... -2.9520202 -6.975904  -7.578929 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.776135  -7.7434783 -7.5427146 ... -2.939249  -7.0272512 -7.5874887]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.809864 -13.244031 -12.840221 ... -12.448553 -12.695869 -13.101043]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.3015065 -7.0352592 -6.7756915 ... -1.8838328 -6.581711  -6.909677 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.742393  -13.174575  -12.790829  ... -12.501686  -12.6720085
 -13.106371 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.75643  -13.191402 -12.803895 ... -12.501158 -12.664101 -13.089466]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.567815  -5.4627156 -5.1182756 ... -2.5935495 -5.8270397 -6.837356 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.946685 -10.399996  -9.340086 ... -11.004047 -10.293729 -10.909521]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.412509 -12.844412 -12.530367 ... -11.43102  -12.169423 -12.799217]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.025699  -5.585455  -5.8828444 ... -1.2761778 -5.1817193 -6.893439 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.806416  -6.5915794 -6.312944  ... -1.509541  -5.644173  -6.316918 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.5942273 -6.44298   -6.1414404 ... -1.3729285 -5.943523  -6.442227 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.2306604 -4.4864597 -3.6456587 ... -5.7936964 -1.9504193 -0.8384847]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.018047 -9.326352 -9.038467 ... -8.572354 -8.658888 -9.180549]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.982355 -12.02442  -11.632288 ...  -8.052631 -11.422408 -12.166329]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.702758  -7.087073  -6.9160957 ... -7.6311364 -7.226855  -7.523506 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.116714 -11.359562  -9.529788 ...  -8.487163  -6.878236  -7.826107]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.752787 -13.170351 -12.795911 ... -12.843422 -12.728749 -13.150303]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.5768795 -8.509889  -8.834862  ... -8.782353  -9.2170515 -8.365022 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.427658  -8.733391  -8.19375   ... -9.578991  -8.3851795 -6.949406 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.686741  -8.2428465 -7.458886  ... -7.271867  -7.1355357 -7.9522324]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.48536   -4.8098464 -3.9629843 ... -5.9667287 -2.0120013 -1.0137819]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.047585 -11.264615 -10.705507 ...  -8.323076  -9.830076 -10.322004]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.477247  -8.311608  -7.9893146 ... -2.9053566 -7.4405046 -7.7459235]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.5653734 -4.151036  -3.5738103 ... -6.714144  -3.5157537 -5.3514137]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.778856  -13.194205  -12.815779  ... -12.9009285 -12.755903
 -13.178219 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.816174  -9.044453  -8.719331  ... -5.949572  -6.9622035 -6.825743 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.360134 -12.797219 -12.333587 ... -12.396273 -12.092314 -12.443316]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.598268  -13.333386  -12.7618685 ... -13.053127  -11.863379
 -10.164746 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.116346  -8.4838705 -8.198017  ... -8.38893   -7.893093  -6.6047006]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.9776545 -7.300997  -6.973427  ... -6.1658    -6.2343793 -4.5989184]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.374292 -12.784566 -12.395976 ... -12.407338 -11.528998  -9.716324]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.694888 -11.358227 -11.128424 ... -11.575247 -10.129756  -8.462699]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.7933    -11.304734   -9.819521  ... -11.292302   -6.180168
  -5.5829353]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.874964 -13.308757 -12.92221  ... -12.821836 -12.783343 -13.211171]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.421377  -7.607815  -7.270277  ... -7.5808735 -7.4078574 -6.143339 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.362956 -9.485455 -9.33226  ... -7.102524 -7.767704 -7.676238]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.756072  -14.20377   -12.052748  ... -14.227303  -10.75747
  -9.8873415]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.8507314 -7.253331  -6.931588  ... -6.908372  -6.4658575 -5.1860194]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.0189404 -6.255022  -6.155974  ... -4.965161  -5.4419603 -3.6636739]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.089479  -12.4907255 -12.1162    ... -12.410284  -12.1453085

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.3687973 -7.3081183 -7.0471334 ... -2.6662786 -6.698884  -7.3691044]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.602663 -11.19301  -10.489031 ... -11.367981  -9.154269  -9.058272]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.517636  -9.184413  -8.5173435 ... -8.534308  -7.9214506 -8.786465 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.114429  -6.4162745 -5.8500533 ... -2.6252856 -5.2985973 -6.303539 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.903406  -3.85074   -3.411383  ... -5.805093  -2.2653928 -4.548911 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.4948826 -5.3512254 -4.8360496 ... -7.617001  -4.2381325 -6.0261126]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.1122074 -6.9378867 -6.408247  ... -9.292034  -5.9254    -7.6576643]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.3484535 -12.793668  -11.215175  ... -14.828295  -11.423078
 -11.128944 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.3839793 -6.2812567 -5.31275   ... -6.4728613 -5.4790053 -6.07673  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.446924 -12.926652 -12.484741 ... -12.108221 -12.03932  -12.437768]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.635117 -11.860803 -11.60215  ... -15.84516  -11.664573 -12.454479]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.2085676 -6.3255653 -4.9083595 ... -8.322527  -6.359714  -6.882068 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.391524 -12.825388 -12.427005 ... -12.257998 -12.352978 -12.835385]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.9868717  -9.547919   -8.467334  ... -12.036774   -4.5432405
  -3.1090608]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.675338 -12.952807 -12.589188 ... -11.011107 -12.524209 -12.947891]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.662188 -13.064198 -12.695536 ... -12.772133 -12.606702 -12.970956]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.8148756 -7.579147  -7.2503757 ... -2.251713  -6.7966967 -7.045936 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.276415  -13.10137   -12.0715685 ... -12.393197  -11.612436
 -11.9397335]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.917999 -13.272487 -11.87025  ... -13.82688  -11.61229  -12.010721]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.8929553 -7.2656403 -6.3874555 ... -6.12359   -5.4479356 -4.188898 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.089832  -7.9407396 -7.627713  ... -2.4516575 -7.061044  -7.400364 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.95289  -14.03414  -13.095418 ... -12.151752 -12.010601 -12.952127]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.858776  -9.515108  -9.03879  ...  -9.019746 -10.31485  -10.814653]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.449509 -11.835212 -11.404914 ... -11.283701 -11.022593 -11.682236]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.3000846 -6.871119  -7.0873165 ... -5.2773623 -5.895348  -6.5568104]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.249971  -7.5971565 -7.282717  ... -8.569049  -7.62343   -7.5160823]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.222228  -5.598303  -5.2835608 ... -5.9905257 -5.317103  -5.765681 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.081498 -9.045409 -8.139035 ... -7.337937 -7.057868 -8.158098]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.6126003 -7.0956655 -7.0528316 ... -6.81468   -6.7074127 -7.054625 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.569926  -6.7861    -6.6169214 ... -8.479071  -8.193937  -9.216198 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.260662  -7.8960977 -7.667347  ... -7.0110426 -6.5939393 -6.809569 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.076947  -7.442341  -7.2569304 ... -7.8735204 -7.360886  -7.729492 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.045594  -8.779554  -7.8245883 ... -9.440474  -7.755435  -8.694491 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.0499783 -5.083853  -4.9551187 ... -5.0736485 -5.717178  -5.9803114]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.776194 -13.230372 -12.899943 ... -13.048254 -12.694816 -13.075182]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.965793  -11.185008  -10.759566  ...  -9.421448  -11.512494
 -12.1147585]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.645606  -7.616781  -7.3667636 ... -2.9077845 -6.93573   -7.5210176]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.298413  -4.84976   -4.6376677 ... -3.9774458 -2.7665198 -3.7016351]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.842239 -11.020488 -10.42418  ...  -9.563112  -8.225784  -9.999   ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.274347 -11.938291 -11.240367 ... -11.948345 -10.826775 -11.5402  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.81084    -9.754552   -9.7223425 ... -10.221034  -13.180575
 -12.397262 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.591499 -13.025285 -12.638022 ... -12.546022 -12.459983 -12.880203]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.524527 -11.418565 -10.9403   ...  -8.865182 -10.907659 -11.458201]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.316849  -12.683905  -12.29266   ... -11.8977165 -11.94741
 -12.288225 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.130464  -7.5165377 -7.2039657 ... -7.6260457 -6.8533916 -7.1218195]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.9936113 -3.6547873 -4.0143867 ... -3.949319  -4.82911   -5.537616 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.973409 -11.737218 -10.980071 ... -11.640708 -10.376244 -11.195111]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.04813  -13.81422  -12.211404 ...  -9.624408  -9.369216 -11.176233]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.091016   -9.71776    -8.210536  ... -12.319679   -7.424556
  -6.9966173]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.861908 -10.663919  -9.956987 ...  -9.87014   -8.523548  -8.378878]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.921935 -10.668505 -10.015906 ...  -9.963982  -8.69493   -8.572208]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.418606 -12.863443 -12.496597 ... -12.528555 -12.404454 -12.910336]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.259312 -13.98327  -13.646377 ...  -7.332115 -12.524945 -13.492187]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.703351 -13.156238 -12.748713 ... -12.790141 -12.669789 -13.089755]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.041426   -7.6326904  -6.2002454 ... -12.683163   -7.9652324
  -8.457561 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.094848  -8.4428835 -8.187722  ... -8.602565  -7.8832793 -8.043671 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.876584 -13.30808  -12.921182 ... -12.811779 -12.759003 -13.175882]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.175956 -12.465265 -12.125758 ... -11.701265 -12.058411 -12.53549 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.65384  -12.038967 -11.358933 ... -10.946417 -10.303291 -10.549717]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.799202 -10.34719   -9.792461 ...  -8.357179  -8.470923  -8.657636]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.265098 -11.384355 -10.194341 ... -10.522995  -8.114131  -8.090595]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.2884655 -12.696583  -12.214718  ... -12.206195  -12.009807
 -12.205221 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.786515  -4.041757  -3.3196886 ... -5.5351377 -1.614131  -0.6657377]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.519836 -11.928582 -11.14724  ... -11.774099 -10.777853 -10.750156]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.977777 -10.809863 -10.162604 ...  -9.932506  -9.934705  -9.853962]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.466804 -12.879241 -12.479987 ... -12.479682 -12.447494 -12.92791 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.750952 -11.486145 -10.720324 ... -11.473208 -10.147787 -10.920429]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.525269  -8.677775  -8.008539  ... -7.9300957 -7.8904037 -8.570295 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.082077  -12.350908  -12.011375  ... -12.135868  -12.034552
 -12.3375025]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.696804 -11.610062 -11.033879 ...  -8.935717  -7.895559  -8.600756]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.061038  -9.857937  -8.823748 ... -10.092259  -8.362784  -8.96627 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.110367  -8.195319  -7.7679877 ... -3.08106   -6.9702835 -7.455834 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.8348374 -4.4678435 -4.595785  ... -3.5245492 -3.7190762 -4.010678 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.296119 -11.053915 -10.413316 ...  -8.677519  -9.316181 -10.188991]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.006101  -6.8923535 -5.930734  ... -2.751333  -4.8914137 -5.771967 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.68777   -8.525211  -8.699154 ...  -4.649152 -10.526807  -8.399113]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.69271   -6.628924  -6.3913693 ... -2.601778  -6.322917  -6.4027452]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.07104    -8.20169    -8.128264  ...  -6.8097878 -10.479593
  -9.209926 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.987376 -11.598407 -10.444134 ... -10.902958 -10.207736 -10.928784]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.676788 -11.768    -11.36783  ...  -9.4169   -11.970866 -12.526873]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.115098  -5.3263316 -5.026558  ... -2.146896  -4.595306  -4.910762 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.004191  -11.9594555 -11.567937  ...  -8.029801  -13.282358
 -14.398188 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.1849854 -3.9029431 -3.4356463 ... -6.1586304 -3.0588732 -5.006715 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.748831  -13.154216  -12.7727375 ... -12.852065  -12.68934
 -13.051542 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.361237  -11.027693  -10.171952  ... -11.9444685  -7.6594987
  -7.3933134]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.104112 -11.647108 -11.060915 ... -12.13465   -9.92599  -10.005647]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.4661698 -3.4200857 -2.1456082 ... -7.09072   -4.7285004 -4.5039897]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.128832 -11.422478 -11.094921 ...  -8.407037  -9.591127  -9.522292]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.956808  -6.6873264 -6.4385586 ... -1.427208  -6.1942964 -6.505236 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.3351293 -7.2019377 -6.7660933 ... -1.8933738 -6.4545765 -6.788797 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.70785  -12.889734 -12.314219 ...  -8.557566 -11.702112 -12.234456]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.758558 -12.903897 -12.33074  ...  -8.209309 -11.755995 -12.304949]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.6647296 -6.5187354 -6.419995  ... -1.2024586 -5.9953723 -6.4216332]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.968906 -12.289146 -11.943694 ...  -9.989822 -11.59604  -12.055778]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.628733 -10.294261  -9.911552 ... -11.261879  -8.808672  -9.748595]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.9976892 -6.033669  -5.1182637 ... -2.5462544 -4.6053667 -4.531142 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.741534  -6.69092   -6.3962364 ... -1.9769335 -5.910036  -6.5089836]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.998173 -12.336281 -11.92391  ... -11.336692 -11.722565 -12.114081]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.102188  -6.4005294 -4.915205  ... -6.6194468 -3.039602  -1.9877566]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.3218927 -6.9537587 -6.420358  ... -6.3189178 -5.18319   -3.4262629]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.259309  -10.597903  -10.052585  ...  -9.808226   -9.8172865
 -10.645747 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.7429767 -7.719219  -7.436959  ... -3.1265671 -6.9638033 -7.584559 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.734143 -10.991084 -10.849252 ...  -9.93698  -11.594394 -12.016219]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.6009145 -6.691339  -6.368015  ... -3.6140563 -8.592626  -9.7669525]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.392346  -8.375422  -8.069116 ...  -7.525466 -11.36133  -12.878048]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.41996   -8.416546  -8.162361  ... -3.3602366 -7.388023  -7.997549 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.6072454 -5.570711  -4.661988  ... -1.3932809 -3.2736914 -4.5370684]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.5510025 -12.996087  -12.574356  ... -12.217133  -12.346805
 -12.812981 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.402965  -6.2745314 -5.4280133 ... -2.1915307 -4.143538  -5.3617487]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.556832 -6.373764 -5.55245  ... -2.413295 -4.368742 -5.578277]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.473159 -10.674543 -10.047785 ...  -8.187911 -11.130645 -11.930404]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.8544674 -5.751884  -5.3118196 ... -2.2603836 -6.556394  -7.3565855]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.469075  -10.7269945 -10.461346  ...  -9.212215  -10.6616335
 -11.280029 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.546794  -6.500177  -6.154568  ... -2.262561  -6.0999866 -6.7625766]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.313343 -10.652801 -10.265667 ...  -9.788727 -10.261262 -10.799883]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.4533153 -6.339328  -5.4895864 ... -2.0574    -4.0852485 -5.3176165]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.701828  -2.827392  -1.9613883 ... -6.2795234 -1.5507075 -3.388127 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.142396  -7.1398344 -6.828516  ... -2.5283704 -6.033555  -6.47844  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.641145  -6.590152  -6.316067  ... -1.7402669 -5.7200513 -6.31582  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.999315   -9.107435   -8.265204  ...  -5.8111634 -10.508988
 -11.9626465]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.7443504 -6.757117  -6.2875075 ... -3.1935728 -7.0243716 -7.762896 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.944693  -7.3748627 -6.984722  ... -7.5865664 -6.6043124 -6.88093  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.880922  -14.7696495 -13.430327  ... -10.96355   -11.196262
 -12.92911  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.7263975 -13.148748  -12.767663  ... -12.370549  -12.598665
 -13.03394  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.78194  -13.205771 -12.821064 ... -12.487604 -12.678811 -13.106275]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.977003 -14.487705 -12.595517 ...  -9.604583 -10.368512 -11.635963]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.538869 -12.972429 -12.580981 ... -12.682258 -12.412917 -12.837549]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.3423553 -7.880589  -6.811676  ... -9.944704  -4.244701  -4.0242715]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.498407 -12.711613 -12.159    ... -10.542001 -11.86986  -12.470653]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.354353 -10.249963 -10.512265 ... -10.600104 -10.945609 -10.267479]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.2102833 -7.150752  -6.1638584 ... -2.842827  -4.754366  -5.880444 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.4524302 -6.3716927 -5.469669  ... -2.359181  -4.2226105 -5.5036764]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.31398  -12.656397 -12.093118 ... -11.758665 -11.475041 -12.131361]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.522749  -6.42134   -5.426892  ... -2.3478444 -4.259288  -5.393849 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.325942  -9.830975  -8.816944 ... -11.82029   -6.945949  -6.598765]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.9788901 -2.985229  -2.3220048 ... -4.8906364 -1.9922528 -4.106203 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.8604736  -6.9120336  -7.1702604 ...  -9.959809   -8.788024
 -10.539071 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.969735 -10.774133  -9.802497 ... -11.063265  -9.435122 -10.238271]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.22902  -13.193231 -12.388807 ... -14.148202 -11.446955 -11.196962]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.513412 -12.919955 -12.512535 ... -12.570144 -12.410641 -12.774271]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.510454 -14.189446 -12.717789 ...  -9.922553  -9.980345 -11.509599]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.715282 -10.507405  -9.491192 ... -14.518347 -11.023847 -11.618611]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.14036   -8.973839  -7.869581 ... -13.649538  -9.616956 -10.191792]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.809104  -9.208071  -8.523578  ... -6.9163885 -8.231126  -8.829803 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.357314  -7.577002  -7.4760456 ... -7.4247    -7.444889  -7.4429336]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.1270514 -5.39127   -5.090504  ... -5.5532346 -5.680233  -5.8505015]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.666335  -9.561926  -9.436716 ... -15.296676 -11.367806 -12.646869]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.6111407 -7.2227135 -6.984767  ... -6.5217752 -6.007471  -6.206184 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.6702137 -7.3997626 -7.2040334 ... -7.181632  -6.3574023 -6.702964 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.3583937 -6.9496646 -6.697403  ... -6.3341866 -5.82243   -6.029136 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.3896227 -6.870578  -6.7754793 ... -6.634298  -6.7116523 -7.197978 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.1267376 -6.8152213 -6.742054  ... -6.920949  -6.5620956 -7.1206965]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.0374002 -5.5945406 -5.4944296 ... -5.492433  -5.4602904 -6.0096154]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.8471363  -4.2091117  -3.1292775  ... -4.788322   -0.76272607
  0.15069206]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.885679 -12.475628 -11.465638 ... -12.70885  -11.408223 -11.274616]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.83197  -13.267221 -12.93209  ... -13.078185 -12.753967 -13.128611]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.814883 -13.247921 -12.92052  ... -13.136863 -12.78564  -13.16166 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.17527   -14.241719  -13.9306755 ... -14.098518  -12.962424
 -12.368148 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.4212513 -6.644529  -6.4290414 ... -6.1519203 -6.513094  -6.512338 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.422593 -14.112828 -12.170812 ... -12.114538 -10.370641 -11.748955]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.5522556 -5.950749  -5.4971457 ... -6.173372  -5.206858  -5.4821362]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.926419  -6.241301  -5.9614344 ... -6.3492813 -6.3424006 -6.452393 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.591367 -13.091493 -12.032251 ... -13.066058 -11.923177 -12.407629]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.87732  -13.482237 -12.936196 ... -12.459036 -12.27046  -12.811946]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.7238464  -8.038147   -7.676654  ... -11.145044  -10.738686
 -12.712924 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.582561 -13.035093 -12.67021  ... -12.871905 -12.450836 -12.809801]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.9203963  -5.284574   -4.2116323  ... -5.8573527  -2.0075321
 -0.98390156]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.659273  -6.173362  -5.514534  ... -8.801982  -5.0243263 -4.7967005]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.537406  -10.632182  -10.154242  ...  -7.6909037  -8.789138
  -9.26443  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.492866  -10.57834   -10.08622   ...  -7.6537614  -8.732686
  -9.205109 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.470466  -6.414864  -6.136627  ... -2.2507617 -6.224209  -6.916524 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.146851  -7.9636827 -7.664553  ... -2.5289214 -7.1260915 -7.420636 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.149409  -6.505265  -6.200122  ... -6.0665665 -6.1688557 -6.531071 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.563801  -8.868739  -8.299238  ... -8.703184  -7.2031984 -7.540968 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.081387  -6.9106936 -5.9954567 ... -3.0271592 -5.0542035 -6.118478 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.565001 -12.127398 -11.804574 ... -13.504533 -12.252103 -12.951318]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.692305 -12.89334  -12.489742 ... -10.140847 -12.292972 -12.751394]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.382625 -12.39862  -11.855409 ...  -6.438915 -11.459437 -12.138059]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.633078 -11.010884 -10.75592  ... -11.924348 -11.332002 -11.637538]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.985755 -12.539275 -12.041869 ... -12.158417 -11.713988 -12.345158]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.319488 -9.918273 -9.215799 ... -8.474188 -8.746466 -9.658248]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.24499  -12.498068 -12.069807 ... -10.944427 -12.154999 -12.59657 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.267514  -4.5995793 -3.7332077 ... -5.6758585 -1.7820791 -0.8085213]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.773622  -8.800655  -8.456462 ...  -9.933625 -10.576438 -11.603184]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.309628  -8.324121  -8.16213  ... -10.105171 -10.698879 -11.994638]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.135109  -9.45369   -9.102144 ...  -9.096802  -9.600821 -10.584005]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.61318   -8.998121  -8.647894 ...  -8.921999  -9.244689 -10.478266]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.852117   -9.265361   -8.863036  ...  -9.937634   -9.6995325
 -10.909622 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.403946 -12.653648 -12.293222 ... -10.150034 -12.163451 -12.617141]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.252462  -5.7437654 -5.497157  ... -6.7680306 -5.5769963 -6.1177115]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.802962  -10.020221  -10.0553875 ...  -5.595279   -9.716588
 -10.5352745]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.856149  -6.3129025 -5.916776  ... -1.1659608 -5.788182  -6.245003 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

PairwiseArrays with keys: connectivities, distances

{'cellxgene_census/dkd_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3432203389830508, 'macro': 0.25917444685094343, 'micro': 0.3432203389830508, 'weighted': 0.34017252137470233}}, 'cellxgene_census/dkd_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3550587343690792, 'macro': 0.27207633588309094, 'micro': 0.3550587343690792, 'weighted': 0.3524031871669568}}, 'cellxgene_census/dkd_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3561955286093217, 'macro': 0.2740563641826558, 'micro': 0.3561955286093217, 'weighted': 0.3538971563453317}}, 'cellxgene_census/dkd_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.361121636983706, 'macro': 0.2857142857142857, 'micro': 0.361121636983706, 'weighted': 0.361121636983706}}, 'cellxgene_census/gtex_v9_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4940849057506001, 'macro': 0.32408851632492214, 'micro': 0.4940849057506001, 'weighted': 0.46206164048799947}}, 'cellxgene_census/gtex_v9_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5688216892596455, 'macro': 0.5135325396389532, 'micro': 0.5688216892596455, 'weighted': 0.4995750709500925}}, 'cellxgene_census/gtex_v9_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5477059436913452, 'macro': 0.5371100686494984, 'micro': 0.5477059436913452, 'weighted': 0.5004916521764624}}, 'cellxgene_census/gtex_v9_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5477059436913452, 'macro': 0.5371100686494984, 'micro': 0.5477059436913452, 'weighted': 0.5004916521764624}}}
doing  cellxgene_census/hypomap

/lustre/fswork/projects/rech/xeg/uat95fg/scdataloader/scdataloader/utils.py:427: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  organismdf = pd.concat(organismdf)

predict epoch start

  0%|          | 0/6015 [00:00<?, ?it/s]

  0%|          | 1/6015 [00:07<12:39:12,  7.57s/it]

  0%|          | 2/6015 [00:08<6:19:17,  3.78s/it]

  0%|          | 3/6015 [00:09<4:17:35,  2.57s/it]

  0%|          | 4/6015 [00:10<3:20:22,  2.00s/it]

  0%|          | 5/6015 [00:12<2:48:40,  1.68s/it]

  0%|          | 6/6015 [00:13<2:29:41,  1.49s/it]

  0%|          | 7/6015 [00:14<2:17:43,  1.38s/it]

  0%|          | 8/6015 [00:15<2:09:47,  1.30s/it]

  0%|          | 9/6015 [00:16<2:04:43,  1.25s/it]

  0%|          | 10/6015 [00:17<2:01:05,  1.21s/it]

  0%|          | 11/6015 [00:18<1:58:38,  1.19s/it]

  0%|          | 12/6015 [00:19<1:56:57,  1.17s/it]

  0%|          | 13/6015 [00:21<1:55:39,  1.16s/it]

  0%|          | 14/6015 [00:22<1:54:52,  1.15s/it]

  0%|          | 15/6015 [00:23<1:54:24,  1.14s/it]

  0%|          | 16/6015 [00:24<1:53:57,  1.14s/it]

  0%|          | 17/6015 [00:25<1:53:50,  1.14s/it]

  0%|          | 18/6015 [00:26<1:53:37,  1.14s/it]

  0%|          | 19/6015 [00:27<1:53:29,  1.14s/it]

  0%|          | 20/6015 [00:29<1:53:21,  1.13s/it]

  0%|          | 21/6015 [00:30<1:53:11,  1.13s/it]

  0%|          | 22/6015 [00:31<1:53:15,  1.13s/it]

  0%|          | 23/6015 [00:32<1:53:15,  1.13s/it]

  0%|          | 24/6015 [00:33<1:53:14,  1.13s/it]

  0%|          | 25/6015 [00:34<1:53:09,  1.13s/it]

  0%|          | 26/6015 [00:35<1:53:13,  1.13s/it]

  0%|          | 27/6015 [00:36<1:53:12,  1.13s/it]

  0%|          | 28/6015 [00:38<1:53:24,  1.14s/it]

  0%|          | 29/6015 [00:39<1:53:26,  1.14s/it]

  0%|          | 30/6015 [00:40<1:53:30,  1.14s/it]

  1%|          | 31/6015 [00:41<1:53:27,  1.14s/it]

  1%|          | 32/6015 [00:42<1:53:27,  1.14s/it]

  1%|          | 33/6015 [00:43<1:53:20,  1.14s/it]

  1%|          | 34/6015 [00:44<1:53:18,  1.14s/it]

  1%|          | 35/6015 [00:46<1:53:18,  1.14s/it]

  1%|          | 36/6015 [00:47<1:53:16,  1.14s/it]

  1%|          | 37/6015 [00:48<1:53:18,  1.14s/it]

  1%|          | 38/6015 [00:49<1:53:15,  1.14s/it]

  1%|          | 39/6015 [00:50<1:53:11,  1.14s/it]

  1%|          | 40/6015 [00:51<1:53:06,  1.14s/it]

  1%|          | 41/6015 [00:52<1:53:05,  1.14s/it]

  1%|          | 42/6015 [00:54<1:53:09,  1.14s/it]

  1%|          | 43/6015 [00:55<1:53:06,  1.14s/it]

  1%|          | 44/6015 [00:56<1:53:06,  1.14s/it]

  1%|          | 45/6015 [00:57<1:53:16,  1.14s/it]

  1%|          | 46/6015 [00:58<1:53:15,  1.14s/it]

  1%|          | 47/6015 [00:59<1:53:14,  1.14s/it]

  1%|          | 48/6015 [01:00<1:53:14,  1.14s/it]

  1%|          | 49/6015 [01:02<1:53:11,  1.14s/it]

  1%|          | 50/6015 [01:03<1:53:10,  1.14s/it]

  1%|          | 51/6015 [01:04<1:53:08,  1.14s/it]

  1%|          | 52/6015 [01:05<1:53:15,  1.14s/it]

  1%|          | 53/6015 [01:06<1:53:08,  1.14s/it]

  1%|          | 54/6015 [01:07<1:53:06,  1.14s/it]

  1%|          | 55/6015 [01:08<1:53:07,  1.14s/it]

  1%|          | 56/6015 [01:09<1:53:09,  1.14s/it]

  1%|          | 57/6015 [01:11<1:53:03,  1.14s/it]

  1%|          | 58/6015 [01:12<1:52:59,  1.14s/it]

  1%|          | 59/6015 [01:13<1:53:03,  1.14s/it]

  1%|          | 60/6015 [01:14<1:53:00,  1.14s/it]

  1%|          | 61/6015 [01:15<1:53:04,  1.14s/it]

  1%|          | 62/6015 [01:16<1:53:07,  1.14s/it]

  1%|          | 63/6015 [01:17<1:53:12,  1.14s/it]

  1%|          | 64/6015 [01:19<1:53:09,  1.14s/it]

  1%|          | 65/6015 [01:20<1:53:14,  1.14s/it]

  1%|          | 66/6015 [01:21<1:53:12,  1.14s/it]

  1%|          | 67/6015 [01:22<1:53:07,  1.14s/it]

  1%|          | 68/6015 [01:23<1:53:03,  1.14s/it]

  1%|          | 69/6015 [01:24<1:53:02,  1.14s/it]

  1%|          | 70/6015 [01:25<1:53:02,  1.14s/it]

  1%|          | 71/6015 [01:27<1:53:05,  1.14s/it]

  1%|          | 72/6015 [01:28<1:53:19,  1.14s/it]

  1%|          | 73/6015 [01:29<1:53:09,  1.14s/it]

  1%|          | 74/6015 [01:30<1:53:04,  1.14s/it]

  1%|          | 75/6015 [01:31<1:52:58,  1.14s/it]

  1%|▏         | 76/6015 [01:32<1:53:00,  1.14s/it]

  1%|▏         | 77/6015 [01:33<1:52:57,  1.14s/it]

  1%|▏         | 78/6015 [01:35<1:52:55,  1.14s/it]

  1%|▏         | 79/6015 [01:36<1:52:53,  1.14s/it]

  1%|▏         | 80/6015 [01:37<1:52:58,  1.14s/it]

  1%|▏         | 81/6015 [01:38<1:53:05,  1.14s/it]

  1%|▏         | 82/6015 [01:39<1:53:01,  1.14s/it]

  1%|▏         | 83/6015 [01:40<1:52:59,  1.14s/it]

  1%|▏         | 84/6015 [01:41<1:52:58,  1.14s/it]

  1%|▏         | 85/6015 [01:43<1:53:01,  1.14s/it]

  1%|▏         | 86/6015 [01:44<1:53:02,  1.14s/it]

  1%|▏         | 87/6015 [01:45<1:53:05,  1.14s/it]

  1%|▏         | 88/6015 [01:46<1:53:04,  1.14s/it]

  1%|▏         | 89/6015 [01:47<1:53:03,  1.14s/it]

  1%|▏         | 90/6015 [01:48<1:53:03,  1.14s/it]

  2%|▏         | 91/6015 [01:49<1:52:56,  1.14s/it]

  2%|▏         | 92/6015 [01:51<1:52:50,  1.14s/it]

  2%|▏         | 93/6015 [01:52<1:52:47,  1.14s/it]

  2%|▏         | 94/6015 [01:53<1:52:46,  1.14s/it]

  2%|▏         | 95/6015 [01:54<1:52:48,  1.14s/it]

  2%|▏         | 96/6015 [01:55<1:52:44,  1.14s/it]

  2%|▏         | 97/6015 [01:56<1:52:42,  1.14s/it]

  2%|▏         | 98/6015 [01:57<1:52:48,  1.14s/it]

  2%|▏         | 99/6015 [01:59<1:52:51,  1.14s/it]

  2%|▏         | 100/6015 [02:00<1:52:47,  1.14s/it]

  2%|▏         | 101/6015 [02:01<1:52:44,  1.14s/it]

  2%|▏         | 102/6015 [02:02<1:52:40,  1.14s/it]

  2%|▏         | 103/6015 [02:03<1:52:44,  1.14s/it]

  2%|▏         | 104/6015 [02:04<1:52:47,  1.14s/it]

  2%|▏         | 105/6015 [02:05<1:52:48,  1.15s/it]

  2%|▏         | 106/6015 [02:07<1:52:48,  1.15s/it]

  2%|▏         | 107/6015 [02:08<1:52:46,  1.15s/it]

  2%|▏         | 108/6015 [02:09<1:52:41,  1.14s/it]

  2%|▏         | 109/6015 [02:10<1:52:39,  1.14s/it]

  2%|▏         | 110/6015 [02:11<1:52:36,  1.14s/it]

  2%|▏         | 111/6015 [02:12<1:52:45,  1.15s/it]

  2%|▏         | 112/6015 [02:13<1:52:42,  1.15s/it]

  2%|▏         | 113/6015 [02:15<1:52:42,  1.15s/it]

  2%|▏         | 114/6015 [02:16<1:52:40,  1.15s/it]

  2%|▏         | 115/6015 [02:17<1:52:36,  1.15s/it]

  2%|▏         | 116/6015 [02:18<1:52:51,  1.15s/it]

  2%|▏         | 117/6015 [02:19<1:52:45,  1.15s/it]

  2%|▏         | 118/6015 [02:20<1:52:41,  1.15s/it]

  2%|▏         | 119/6015 [02:22<1:52:36,  1.15s/it]

  2%|▏         | 120/6015 [02:23<1:52:41,  1.15s/it]

  2%|▏         | 121/6015 [02:24<1:52:42,  1.15s/it]

  2%|▏         | 122/6015 [02:25<1:52:41,  1.15s/it]

  2%|▏         | 123/6015 [02:26<1:52:40,  1.15s/it]

  2%|▏         | 124/6015 [02:27<1:52:34,  1.15s/it]

  2%|▏         | 125/6015 [02:28<1:52:34,  1.15s/it]

  2%|▏         | 126/6015 [02:30<1:52:36,  1.15s/it]

  2%|▏         | 127/6015 [02:31<1:52:44,  1.15s/it]

  2%|▏         | 128/6015 [02:32<1:52:38,  1.15s/it]

  2%|▏         | 129/6015 [02:33<1:52:34,  1.15s/it]

  2%|▏         | 130/6015 [02:34<1:52:30,  1.15s/it]

  2%|▏         | 131/6015 [02:35<1:52:32,  1.15s/it]

  2%|▏         | 132/6015 [02:36<1:52:36,  1.15s/it]

  2%|▏         | 133/6015 [02:38<1:52:36,  1.15s/it]

  2%|▏         | 134/6015 [02:39<1:52:33,  1.15s/it]

  2%|▏         | 135/6015 [02:40<1:52:34,  1.15s/it]

  2%|▏         | 136/6015 [02:41<1:52:34,  1.15s/it]

  2%|▏         | 137/6015 [02:42<1:52:26,  1.15s/it]

  2%|▏         | 138/6015 [02:43<1:52:28,  1.15s/it]

  2%|▏         | 139/6015 [02:44<1:52:22,  1.15s/it]

  2%|▏         | 140/6015 [02:46<1:52:24,  1.15s/it]

  2%|▏         | 141/6015 [02:47<1:52:37,  1.15s/it]

  2%|▏         | 142/6015 [02:48<1:52:31,  1.15s/it]

  2%|▏         | 143/6015 [02:49<1:52:32,  1.15s/it]

  2%|▏         | 144/6015 [02:50<1:52:38,  1.15s/it]

  2%|▏         | 145/6015 [02:51<1:52:45,  1.15s/it]

  2%|▏         | 146/6015 [02:53<1:52:38,  1.15s/it]

  2%|▏         | 147/6015 [02:54<1:52:43,  1.15s/it]

  2%|▏         | 148/6015 [02:55<1:52:39,  1.15s/it]

  2%|▏         | 149/6015 [02:56<1:52:35,  1.15s/it]

  2%|▏         | 150/6015 [02:57<1:52:31,  1.15s/it]

  3%|▎         | 151/6015 [02:58<1:52:30,  1.15s/it]

  3%|▎         | 152/6015 [02:59<1:52:25,  1.15s/it]

  3%|▎         | 153/6015 [03:01<1:52:20,  1.15s/it]

  3%|▎         | 154/6015 [03:02<1:52:15,  1.15s/it]

  3%|▎         | 155/6015 [03:03<1:52:16,  1.15s/it]

  3%|▎         | 156/6015 [03:04<1:52:21,  1.15s/it]

  3%|▎         | 157/6015 [03:05<1:52:15,  1.15s/it]

  3%|▎         | 158/6015 [03:06<1:52:12,  1.15s/it]

  3%|▎         | 159/6015 [03:07<1:52:11,  1.15s/it]

  3%|▎         | 160/6015 [03:09<1:52:10,  1.15s/it]

  3%|▎         | 161/6015 [03:10<1:52:12,  1.15s/it]

  3%|▎         | 162/6015 [03:11<1:52:12,  1.15s/it]

  3%|▎         | 163/6015 [03:12<1:52:18,  1.15s/it]

  3%|▎         | 164/6015 [03:13<1:52:19,  1.15s/it]

  3%|▎         | 165/6015 [03:14<1:52:16,  1.15s/it]

  3%|▎         | 166/6015 [03:16<1:52:20,  1.15s/it]

  3%|▎         | 167/6015 [03:17<1:52:23,  1.15s/it]

  3%|▎         | 168/6015 [03:18<1:52:18,  1.15s/it]

  3%|▎         | 169/6015 [03:19<1:52:14,  1.15s/it]

  3%|▎         | 170/6015 [03:20<1:52:17,  1.15s/it]

  3%|▎         | 171/6015 [03:21<1:52:17,  1.15s/it]

  3%|▎         | 172/6015 [03:22<1:52:17,  1.15s/it]

  3%|▎         | 173/6015 [03:24<1:52:11,  1.15s/it]

  3%|▎         | 174/6015 [03:25<1:52:01,  1.15s/it]

  3%|▎         | 175/6015 [03:26<1:52:06,  1.15s/it]

  3%|▎         | 176/6015 [03:27<1:52:00,  1.15s/it]

  3%|▎         | 177/6015 [03:28<1:52:05,  1.15s/it]

  3%|▎         | 178/6015 [03:29<1:52:08,  1.15s/it]

  3%|▎         | 179/6015 [03:31<1:52:07,  1.15s/it]

  3%|▎         | 180/6015 [03:32<1:52:13,  1.15s/it]

  3%|▎         | 181/6015 [03:33<1:52:15,  1.15s/it]

  3%|▎         | 182/6015 [03:34<1:52:15,  1.15s/it]

  3%|▎         | 183/6015 [03:35<1:52:06,  1.15s/it]

  3%|▎         | 184/6015 [03:36<1:52:01,  1.15s/it]

  3%|▎         | 185/6015 [03:37<1:52:01,  1.15s/it]

  3%|▎         | 186/6015 [03:39<1:52:02,  1.15s/it]

  3%|▎         | 187/6015 [03:40<1:51:55,  1.15s/it]

  3%|▎         | 188/6015 [03:41<1:51:50,  1.15s/it]

  3%|▎         | 189/6015 [03:42<1:51:54,  1.15s/it]

  3%|▎         | 190/6015 [03:43<1:51:47,  1.15s/it]

  3%|▎         | 191/6015 [03:44<1:51:47,  1.15s/it]

  3%|▎         | 192/6015 [03:46<1:51:47,  1.15s/it]

  3%|▎         | 193/6015 [03:47<1:51:47,  1.15s/it]

  3%|▎         | 194/6015 [03:48<1:51:48,  1.15s/it]

  3%|▎         | 195/6015 [03:49<1:51:53,  1.15s/it]

  3%|▎         | 196/6015 [03:50<1:51:57,  1.15s/it]

  3%|▎         | 197/6015 [03:51<1:51:47,  1.15s/it]

  3%|▎         | 198/6015 [03:52<1:51:50,  1.15s/it]

  3%|▎         | 199/6015 [03:54<1:51:47,  1.15s/it]

  3%|▎         | 200/6015 [03:55<1:51:51,  1.15s/it]

  3%|▎         | 201/6015 [03:56<1:51:47,  1.15s/it]

  3%|▎         | 202/6015 [03:57<1:52:02,  1.16s/it]

  3%|▎         | 203/6015 [03:58<1:51:55,  1.16s/it]

  3%|▎         | 204/6015 [03:59<1:51:47,  1.15s/it]

  3%|▎         | 205/6015 [04:01<1:51:46,  1.15s/it]

  3%|▎         | 206/6015 [04:02<1:51:47,  1.15s/it]

  3%|▎         | 207/6015 [04:03<1:51:46,  1.15s/it]

  3%|▎         | 208/6015 [04:04<1:51:48,  1.16s/it]

  3%|▎         | 209/6015 [04:05<1:51:35,  1.15s/it]

  3%|▎         | 210/6015 [04:06<1:51:30,  1.15s/it]

  4%|▎         | 211/6015 [04:07<1:51:34,  1.15s/it]

  4%|▎         | 212/6015 [04:09<1:51:32,  1.15s/it]

  4%|▎         | 213/6015 [04:10<1:51:30,  1.15s/it]

  4%|▎         | 214/6015 [04:11<1:51:32,  1.15s/it]

  4%|▎         | 215/6015 [04:12<1:51:32,  1.15s/it]

  4%|▎         | 216/6015 [04:13<1:51:32,  1.15s/it]

  4%|▎         | 217/6015 [04:14<1:51:26,  1.15s/it]

  4%|▎         | 218/6015 [04:16<1:51:28,  1.15s/it]

  4%|▎         | 219/6015 [04:17<1:51:27,  1.15s/it]

  4%|▎         | 220/6015 [04:18<1:51:20,  1.15s/it]

  4%|▎         | 221/6015 [04:19<1:51:16,  1.15s/it]

  4%|▎         | 222/6015 [04:20<1:51:12,  1.15s/it]

  4%|▎         | 223/6015 [04:21<1:51:16,  1.15s/it]

  4%|▎         | 224/6015 [04:22<1:51:13,  1.15s/it]

  4%|▎         | 225/6015 [04:24<1:51:22,  1.15s/it]

  4%|▍         | 226/6015 [04:25<1:51:16,  1.15s/it]

  4%|▍         | 227/6015 [04:26<1:51:19,  1.15s/it]

  4%|▍         | 228/6015 [04:27<1:51:19,  1.15s/it]

  4%|▍         | 229/6015 [04:28<1:51:11,  1.15s/it]

  4%|▍         | 230/6015 [04:29<1:51:12,  1.15s/it]

  4%|▍         | 231/6015 [04:31<1:51:13,  1.15s/it]

  4%|▍         | 232/6015 [04:32<1:51:09,  1.15s/it]

  4%|▍         | 233/6015 [04:33<1:51:17,  1.15s/it]

  4%|▍         | 234/6015 [04:34<1:51:16,  1.15s/it]

  4%|▍         | 235/6015 [04:35<1:51:13,  1.15s/it]

  4%|▍         | 236/6015 [04:36<1:51:13,  1.15s/it]

  4%|▍         | 237/6015 [04:37<1:51:09,  1.15s/it]

  4%|▍         | 238/6015 [04:39<1:51:12,  1.15s/it]

  4%|▍         | 239/6015 [04:40<1:51:03,  1.15s/it]

  4%|▍         | 240/6015 [04:41<1:51:06,  1.15s/it]

  4%|▍         | 241/6015 [04:42<1:51:06,  1.15s/it]

  4%|▍         | 242/6015 [04:43<1:51:12,  1.16s/it]

  4%|▍         | 243/6015 [04:44<1:51:11,  1.16s/it]

  4%|▍         | 244/6015 [04:46<1:51:06,  1.16s/it]

  4%|▍         | 245/6015 [04:47<1:51:04,  1.16s/it]

  4%|▍         | 246/6015 [04:48<1:51:03,  1.16s/it]

  4%|▍         | 247/6015 [04:49<1:51:02,  1.16s/it]

  4%|▍         | 248/6015 [04:50<1:50:59,  1.15s/it]

  4%|▍         | 249/6015 [04:51<1:50:55,  1.15s/it]

  4%|▍         | 250/6015 [04:52<1:50:56,  1.15s/it]

  4%|▍         | 251/6015 [04:54<1:50:59,  1.16s/it]

  4%|▍         | 252/6015 [04:55<1:50:55,  1.15s/it]

  4%|▍         | 253/6015 [04:56<1:51:06,  1.16s/it]

  4%|▍         | 254/6015 [04:57<1:51:02,  1.16s/it]

  4%|▍         | 255/6015 [04:58<1:50:58,  1.16s/it]

  4%|▍         | 256/6015 [04:59<1:50:50,  1.15s/it]

  4%|▍         | 257/6015 [05:01<1:50:50,  1.16s/it]

  4%|▍         | 258/6015 [05:02<1:50:45,  1.15s/it]

  4%|▍         | 259/6015 [05:03<1:50:44,  1.15s/it]

  4%|▍         | 260/6015 [05:04<1:50:47,  1.16s/it]

  4%|▍         | 261/6015 [05:05<1:50:57,  1.16s/it]

  4%|▍         | 262/6015 [05:06<1:50:59,  1.16s/it]

  4%|▍         | 263/6015 [05:07<1:50:56,  1.16s/it]

  4%|▍         | 264/6015 [05:09<1:50:49,  1.16s/it]

  4%|▍         | 265/6015 [05:10<1:50:50,  1.16s/it]

  4%|▍         | 266/6015 [05:11<1:50:46,  1.16s/it]

  4%|▍         | 267/6015 [05:12<1:50:39,  1.16s/it]

  4%|▍         | 268/6015 [05:13<1:50:36,  1.15s/it]

  4%|▍         | 269/6015 [05:14<1:50:31,  1.15s/it]

  4%|▍         | 270/6015 [05:16<1:50:33,  1.15s/it]

  5%|▍         | 271/6015 [05:17<1:50:37,  1.16s/it]

  5%|▍         | 272/6015 [05:18<1:50:36,  1.16s/it]

  5%|▍         | 273/6015 [05:19<1:50:32,  1.16s/it]

  5%|▍         | 274/6015 [05:20<1:50:30,  1.16s/it]

  5%|▍         | 275/6015 [05:21<1:50:31,  1.16s/it]

  5%|▍         | 276/6015 [05:23<1:50:26,  1.15s/it]

  5%|▍         | 277/6015 [05:24<1:50:27,  1.15s/it]

  5%|▍         | 278/6015 [05:25<1:50:28,  1.16s/it]

  5%|▍         | 279/6015 [05:26<1:50:33,  1.16s/it]

  5%|▍         | 280/6015 [05:27<1:50:31,  1.16s/it]

  5%|▍         | 281/6015 [05:28<1:50:25,  1.16s/it]

  5%|▍         | 282/6015 [05:29<1:50:22,  1.16s/it]

  5%|▍         | 283/6015 [05:31<1:50:19,  1.15s/it]

  5%|▍         | 284/6015 [05:32<1:50:17,  1.15s/it]

  5%|▍         | 285/6015 [05:33<1:50:13,  1.15s/it]

  5%|▍         | 286/6015 [05:34<1:50:17,  1.16s/it]

  5%|▍         | 287/6015 [05:35<1:50:18,  1.16s/it]

  5%|▍         | 288/6015 [05:36<1:50:19,  1.16s/it]

  5%|▍         | 289/6015 [05:38<1:50:22,  1.16s/it]

  5%|▍         | 290/6015 [05:39<1:50:15,  1.16s/it]

  5%|▍         | 291/6015 [05:40<1:50:15,  1.16s/it]

  5%|▍         | 292/6015 [05:41<1:50:19,  1.16s/it]

  5%|▍         | 293/6015 [05:42<1:50:17,  1.16s/it]

  5%|▍         | 294/6015 [05:43<1:50:20,  1.16s/it]

  5%|▍         | 295/6015 [05:44<1:50:16,  1.16s/it]

  5%|▍         | 296/6015 [05:46<1:50:14,  1.16s/it]

  5%|▍         | 297/6015 [05:47<1:50:22,  1.16s/it]

  5%|▍         | 298/6015 [05:48<1:50:22,  1.16s/it]

  5%|▍         | 299/6015 [05:49<1:50:20,  1.16s/it]

  5%|▍         | 300/6015 [05:50<1:50:15,  1.16s/it]

  5%|▌         | 301/6015 [05:51<1:50:16,  1.16s/it]

  5%|▌         | 302/6015 [05:53<1:50:09,  1.16s/it]

  5%|▌         | 303/6015 [05:54<1:50:06,  1.16s/it]

  5%|▌         | 304/6015 [05:55<1:49:58,  1.16s/it]

  5%|▌         | 305/6015 [05:56<1:50:02,  1.16s/it]

  5%|▌         | 306/6015 [05:57<1:50:12,  1.16s/it]

  5%|▌         | 307/6015 [05:58<1:50:13,  1.16s/it]

  5%|▌         | 308/6015 [06:00<1:50:06,  1.16s/it]

  5%|▌         | 309/6015 [06:01<1:50:10,  1.16s/it]

  5%|▌         | 310/6015 [06:02<1:50:08,  1.16s/it]

  5%|▌         | 311/6015 [06:03<1:50:04,  1.16s/it]

  5%|▌         | 312/6015 [06:04<1:50:00,  1.16s/it]

  5%|▌         | 313/6015 [06:05<1:49:55,  1.16s/it]

  5%|▌         | 314/6015 [06:06<1:49:50,  1.16s/it]

  5%|▌         | 315/6015 [06:08<1:49:52,  1.16s/it]

  5%|▌         | 316/6015 [06:09<1:49:54,  1.16s/it]

  5%|▌         | 317/6015 [06:10<1:49:50,  1.16s/it]

  5%|▌         | 318/6015 [06:11<1:50:04,  1.16s/it]

  5%|▌         | 319/6015 [06:12<1:50:00,  1.16s/it]

  5%|▌         | 320/6015 [06:13<1:50:00,  1.16s/it]

  5%|▌         | 321/6015 [06:15<1:49:56,  1.16s/it]

  5%|▌         | 322/6015 [06:16<1:49:56,  1.16s/it]

  5%|▌         | 323/6015 [06:17<1:50:01,  1.16s/it]

  5%|▌         | 324/6015 [06:18<1:49:54,  1.16s/it]

  5%|▌         | 325/6015 [06:19<1:49:44,  1.16s/it]

  5%|▌         | 326/6015 [06:20<1:49:42,  1.16s/it]

  5%|▌         | 327/6015 [06:22<1:49:42,  1.16s/it]

  5%|▌         | 328/6015 [06:23<1:49:37,  1.16s/it]

  5%|▌         | 329/6015 [06:24<1:49:40,  1.16s/it]

  5%|▌         | 330/6015 [06:25<1:49:43,  1.16s/it]

  6%|▌         | 331/6015 [06:26<1:49:38,  1.16s/it]

  6%|▌         | 332/6015 [06:27<1:49:39,  1.16s/it]

  6%|▌         | 333/6015 [06:28<1:49:35,  1.16s/it]

  6%|▌         | 334/6015 [06:30<1:49:36,  1.16s/it]

  6%|▌         | 335/6015 [06:31<1:49:40,  1.16s/it]

  6%|▌         | 336/6015 [06:32<1:49:36,  1.16s/it]

  6%|▌         | 337/6015 [06:33<1:49:36,  1.16s/it]

  6%|▌         | 338/6015 [06:34<1:49:35,  1.16s/it]

  6%|▌         | 339/6015 [06:35<1:49:32,  1.16s/it]

  6%|▌         | 340/6015 [06:37<1:49:30,  1.16s/it]

  6%|▌         | 341/6015 [06:38<1:49:36,  1.16s/it]

  6%|▌         | 342/6015 [06:39<1:49:36,  1.16s/it]

  6%|▌         | 343/6015 [06:40<1:49:32,  1.16s/it]

  6%|▌         | 344/6015 [06:41<1:49:22,  1.16s/it]

  6%|▌         | 345/6015 [06:42<1:49:16,  1.16s/it]

  6%|▌         | 346/6015 [06:44<1:49:19,  1.16s/it]

  6%|▌         | 347/6015 [06:45<1:49:23,  1.16s/it]

  6%|▌         | 348/6015 [06:46<1:49:20,  1.16s/it]

  6%|▌         | 349/6015 [06:47<1:49:20,  1.16s/it]

  6%|▌         | 350/6015 [06:48<1:49:23,  1.16s/it]

  6%|▌         | 351/6015 [06:49<1:49:32,  1.16s/it]

  6%|▌         | 352/6015 [06:50<1:49:31,  1.16s/it]

  6%|▌         | 353/6015 [06:52<1:49:26,  1.16s/it]

  6%|▌         | 354/6015 [06:53<1:49:18,  1.16s/it]

  6%|▌         | 355/6015 [06:54<1:49:13,  1.16s/it]

  6%|▌         | 356/6015 [06:55<1:49:08,  1.16s/it]

  6%|▌         | 357/6015 [06:56<1:49:17,  1.16s/it]

  6%|▌         | 358/6015 [06:57<1:49:17,  1.16s/it]

  6%|▌         | 359/6015 [06:59<1:49:18,  1.16s/it]

  6%|▌         | 360/6015 [07:00<1:49:18,  1.16s/it]

  6%|▌         | 361/6015 [07:01<1:49:14,  1.16s/it]

  6%|▌         | 362/6015 [07:02<1:49:36,  1.16s/it]

  6%|▌         | 363/6015 [07:03<1:49:24,  1.16s/it]

  6%|▌         | 364/6015 [07:04<1:49:21,  1.16s/it]

  6%|▌         | 365/6015 [07:06<1:49:12,  1.16s/it]

  6%|▌         | 366/6015 [07:07<1:49:07,  1.16s/it]

  6%|▌         | 367/6015 [07:08<1:49:10,  1.16s/it]

  6%|▌         | 368/6015 [07:09<1:49:08,  1.16s/it]

  6%|▌         | 369/6015 [07:10<1:49:06,  1.16s/it]

  6%|▌         | 370/6015 [07:11<1:49:07,  1.16s/it]

  6%|▌         | 371/6015 [07:13<1:49:03,  1.16s/it]

  6%|▌         | 372/6015 [07:14<1:48:58,  1.16s/it]

  6%|▌         | 373/6015 [07:15<1:48:57,  1.16s/it]

  6%|▌         | 374/6015 [07:16<1:49:03,  1.16s/it]

  6%|▌         | 375/6015 [07:17<1:48:55,  1.16s/it]

  6%|▋         | 376/6015 [07:18<1:49:00,  1.16s/it]

  6%|▋         | 377/6015 [07:19<1:48:55,  1.16s/it]

  6%|▋         | 378/6015 [07:21<1:48:55,  1.16s/it]

  6%|▋         | 379/6015 [07:22<1:49:01,  1.16s/it]

  6%|▋         | 380/6015 [07:23<1:49:01,  1.16s/it]

  6%|▋         | 381/6015 [07:24<1:49:03,  1.16s/it]

  6%|▋         | 382/6015 [07:25<1:48:53,  1.16s/it]

  6%|▋         | 383/6015 [07:26<1:48:48,  1.16s/it]

  6%|▋         | 384/6015 [07:28<1:48:49,  1.16s/it]

  6%|▋         | 385/6015 [07:29<1:48:52,  1.16s/it]

  6%|▋         | 386/6015 [07:30<1:48:53,  1.16s/it]

  6%|▋         | 387/6015 [07:31<1:48:45,  1.16s/it]

  6%|▋         | 388/6015 [07:32<1:48:49,  1.16s/it]

  6%|▋         | 389/6015 [07:33<1:48:43,  1.16s/it]

  6%|▋         | 390/6015 [07:35<1:48:43,  1.16s/it]

  7%|▋         | 391/6015 [07:36<1:48:33,  1.16s/it]

  7%|▋         | 392/6015 [07:37<1:48:30,  1.16s/it]

  7%|▋         | 393/6015 [07:38<1:48:27,  1.16s/it]

  7%|▋         | 394/6015 [07:39<1:48:28,  1.16s/it]

  7%|▋         | 395/6015 [07:40<1:48:36,  1.16s/it]

  7%|▋         | 396/6015 [07:41<1:48:39,  1.16s/it]

  7%|▋         | 397/6015 [07:43<1:48:38,  1.16s/it]

  7%|▋         | 398/6015 [07:44<1:48:40,  1.16s/it]

  7%|▋         | 399/6015 [07:45<1:48:40,  1.16s/it]

  7%|▋         | 400/6015 [07:46<1:48:33,  1.16s/it]

  7%|▋         | 401/6015 [07:47<1:48:36,  1.16s/it]

  7%|▋         | 402/6015 [07:48<1:48:34,  1.16s/it]

  7%|▋         | 403/6015 [07:50<1:48:30,  1.16s/it]

  7%|▋         | 404/6015 [07:51<1:48:21,  1.16s/it]

  7%|▋         | 405/6015 [07:52<1:48:22,  1.16s/it]

  7%|▋         | 406/6015 [07:53<1:48:18,  1.16s/it]

  7%|▋         | 407/6015 [07:54<1:48:16,  1.16s/it]

  7%|▋         | 408/6015 [07:55<1:48:14,  1.16s/it]

  7%|▋         | 409/6015 [07:57<1:48:19,  1.16s/it]

  7%|▋         | 410/6015 [07:58<1:48:23,  1.16s/it]

  7%|▋         | 411/6015 [07:59<1:48:15,  1.16s/it]

  7%|▋         | 412/6015 [08:00<1:48:15,  1.16s/it]

  7%|▋         | 413/6015 [08:01<1:48:07,  1.16s/it]

  7%|▋         | 414/6015 [08:02<1:48:05,  1.16s/it]

  7%|▋         | 415/6015 [08:04<1:48:12,  1.16s/it]

  7%|▋         | 416/6015 [08:05<1:48:17,  1.16s/it]

  7%|▋         | 417/6015 [08:06<1:48:19,  1.16s/it]

  7%|▋         | 418/6015 [08:07<1:48:12,  1.16s/it]

  7%|▋         | 419/6015 [08:08<1:48:07,  1.16s/it]

  7%|▋         | 420/6015 [08:09<1:48:15,  1.16s/it]

  7%|▋         | 421/6015 [08:10<1:48:12,  1.16s/it]

  7%|▋         | 422/6015 [08:12<1:48:04,  1.16s/it]

  7%|▋         | 423/6015 [08:13<1:48:02,  1.16s/it]

  7%|▋         | 424/6015 [08:14<1:48:02,  1.16s/it]

  7%|▋         | 425/6015 [08:15<1:47:56,  1.16s/it]

  7%|▋         | 426/6015 [08:16<1:47:56,  1.16s/it]

  7%|▋         | 427/6015 [08:17<1:47:58,  1.16s/it]

  7%|▋         | 428/6015 [08:19<1:48:04,  1.16s/it]

  7%|▋         | 429/6015 [08:20<1:48:06,  1.16s/it]

  7%|▋         | 430/6015 [08:21<1:47:57,  1.16s/it]

  7%|▋         | 431/6015 [08:22<1:47:54,  1.16s/it]

  7%|▋         | 432/6015 [08:23<1:47:55,  1.16s/it]

  7%|▋         | 433/6015 [08:24<1:47:46,  1.16s/it]

  7%|▋         | 434/6015 [08:26<1:47:47,  1.16s/it]

  7%|▋         | 435/6015 [08:27<1:47:52,  1.16s/it]

  7%|▋         | 436/6015 [08:28<1:47:48,  1.16s/it]

  7%|▋         | 437/6015 [08:29<1:47:56,  1.16s/it]

  7%|▋         | 438/6015 [08:30<1:48:02,  1.16s/it]

  7%|▋         | 439/6015 [08:31<1:47:51,  1.16s/it]

  7%|▋         | 440/6015 [08:33<1:47:45,  1.16s/it]

  7%|▋         | 441/6015 [08:34<1:47:41,  1.16s/it]

  7%|▋         | 442/6015 [08:35<1:47:45,  1.16s/it]

  7%|▋         | 443/6015 [08:36<1:47:45,  1.16s/it]

  7%|▋         | 444/6015 [08:37<1:47:43,  1.16s/it]

  7%|▋         | 445/6015 [08:38<1:47:50,  1.16s/it]

  7%|▋         | 446/6015 [08:39<1:47:39,  1.16s/it]

  7%|▋         | 447/6015 [08:41<1:47:37,  1.16s/it]

  7%|▋         | 448/6015 [08:42<1:47:34,  1.16s/it]

  7%|▋         | 449/6015 [08:43<1:47:30,  1.16s/it]

  7%|▋         | 450/6015 [08:44<1:47:29,  1.16s/it]

  7%|▋         | 451/6015 [08:45<1:47:32,  1.16s/it]

  8%|▊         | 452/6015 [08:46<1:47:35,  1.16s/it]

  8%|▊         | 453/6015 [08:48<1:47:32,  1.16s/it]

  8%|▊         | 454/6015 [08:49<1:47:36,  1.16s/it]

  8%|▊         | 455/6015 [08:50<1:47:31,  1.16s/it]

  8%|▊         | 456/6015 [08:51<1:47:33,  1.16s/it]

  8%|▊         | 457/6015 [08:52<1:47:25,  1.16s/it]

  8%|▊         | 458/6015 [08:53<1:47:25,  1.16s/it]

  8%|▊         | 459/6015 [08:55<1:47:22,  1.16s/it]

  8%|▊         | 460/6015 [08:56<1:47:18,  1.16s/it]

  8%|▊         | 461/6015 [08:57<1:47:17,  1.16s/it]

  8%|▊         | 462/6015 [08:58<1:47:22,  1.16s/it]

  8%|▊         | 463/6015 [08:59<1:47:19,  1.16s/it]

  8%|▊         | 464/6015 [09:00<1:47:25,  1.16s/it]

  8%|▊         | 465/6015 [09:02<1:47:22,  1.16s/it]

  8%|▊         | 466/6015 [09:03<1:47:17,  1.16s/it]

  8%|▊         | 467/6015 [09:04<1:47:16,  1.16s/it]

  8%|▊         | 468/6015 [09:05<1:47:15,  1.16s/it]

  8%|▊         | 469/6015 [09:06<1:47:19,  1.16s/it]

  8%|▊         | 470/6015 [09:07<1:47:14,  1.16s/it]

  8%|▊         | 471/6015 [09:08<1:47:10,  1.16s/it]

  8%|▊         | 472/6015 [09:10<1:47:11,  1.16s/it]

  8%|▊         | 473/6015 [09:11<1:47:15,  1.16s/it]

  8%|▊         | 474/6015 [09:12<1:47:14,  1.16s/it]

  8%|▊         | 475/6015 [09:13<1:47:11,  1.16s/it]

  8%|▊         | 476/6015 [09:14<1:47:13,  1.16s/it]

  8%|▊         | 477/6015 [09:15<1:47:15,  1.16s/it]

  8%|▊         | 478/6015 [09:17<1:47:13,  1.16s/it]

  8%|▊         | 479/6015 [09:18<1:47:12,  1.16s/it]

  8%|▊         | 480/6015 [09:19<1:47:12,  1.16s/it]

  8%|▊         | 481/6015 [09:20<1:47:11,  1.16s/it]

  8%|▊         | 482/6015 [09:21<1:47:01,  1.16s/it]

  8%|▊         | 483/6015 [09:22<1:46:57,  1.16s/it]

  8%|▊         | 484/6015 [09:24<1:46:55,  1.16s/it]

  8%|▊         | 485/6015 [09:25<1:46:53,  1.16s/it]

  8%|▊         | 486/6015 [09:26<1:46:50,  1.16s/it]

  8%|▊         | 487/6015 [09:27<1:46:53,  1.16s/it]

  8%|▊         | 488/6015 [09:28<1:46:58,  1.16s/it]

  8%|▊         | 489/6015 [09:29<1:46:56,  1.16s/it]

  8%|▊         | 490/6015 [09:31<1:46:58,  1.16s/it]

  8%|▊         | 491/6015 [09:32<1:46:56,  1.16s/it]

  8%|▊         | 492/6015 [09:33<1:46:55,  1.16s/it]

  8%|▊         | 493/6015 [09:34<1:46:52,  1.16s/it]

  8%|▊         | 494/6015 [09:35<1:46:52,  1.16s/it]

  8%|▊         | 495/6015 [09:36<1:46:55,  1.16s/it]

  8%|▊         | 496/6015 [09:38<1:47:01,  1.16s/it]

  8%|▊         | 497/6015 [09:39<1:47:03,  1.16s/it]

  8%|▊         | 498/6015 [09:40<1:46:55,  1.16s/it]

  8%|▊         | 499/6015 [09:41<1:46:49,  1.16s/it]

  8%|▊         | 500/6015 [09:42<1:46:39,  1.16s/it]

  8%|▊         | 501/6015 [09:43<1:46:34,  1.16s/it]

  8%|▊         | 502/6015 [09:44<1:46:33,  1.16s/it]

  8%|▊         | 503/6015 [09:46<1:46:40,  1.16s/it]

  8%|▊         | 504/6015 [09:47<1:46:39,  1.16s/it]

  8%|▊         | 505/6015 [09:48<1:46:37,  1.16s/it]

  8%|▊         | 506/6015 [09:49<1:46:34,  1.16s/it]

  8%|▊         | 507/6015 [09:50<1:46:35,  1.16s/it]

  8%|▊         | 508/6015 [09:51<1:46:35,  1.16s/it]

  8%|▊         | 509/6015 [09:53<1:46:35,  1.16s/it]

  8%|▊         | 510/6015 [09:54<1:46:28,  1.16s/it]

  8%|▊         | 511/6015 [09:55<1:46:22,  1.16s/it]

  9%|▊         | 512/6015 [09:56<1:46:18,  1.16s/it]

  9%|▊         | 513/6015 [09:57<1:46:19,  1.16s/it]

  9%|▊         | 514/6015 [09:58<1:46:22,  1.16s/it]

  9%|▊         | 515/6015 [10:00<1:46:25,  1.16s/it]

  9%|▊         | 516/6015 [10:01<1:46:24,  1.16s/it]

  9%|▊         | 517/6015 [10:02<1:46:21,  1.16s/it]

  9%|▊         | 518/6015 [10:03<1:46:20,  1.16s/it]

  9%|▊         | 519/6015 [10:04<1:46:31,  1.16s/it]

  9%|▊         | 520/6015 [10:05<1:46:24,  1.16s/it]

  9%|▊         | 521/6015 [10:07<1:46:25,  1.16s/it]

  9%|▊         | 522/6015 [10:08<1:46:21,  1.16s/it]

  9%|▊         | 523/6015 [10:09<1:46:13,  1.16s/it]

  9%|▊         | 524/6015 [10:10<1:46:07,  1.16s/it]

  9%|▊         | 525/6015 [10:11<1:46:10,  1.16s/it]

  9%|▊         | 526/6015 [10:12<1:46:15,  1.16s/it]

  9%|▉         | 527/6015 [10:14<1:46:11,  1.16s/it]

  9%|▉         | 528/6015 [10:15<1:46:11,  1.16s/it]

  9%|▉         | 529/6015 [10:16<1:46:07,  1.16s/it]

  9%|▉         | 530/6015 [10:17<1:46:00,  1.16s/it]

  9%|▉         | 531/6015 [10:18<1:46:07,  1.16s/it]

  9%|▉         | 532/6015 [10:19<1:46:08,  1.16s/it]

  9%|▉         | 533/6015 [10:20<1:46:07,  1.16s/it]

  9%|▉         | 534/6015 [10:22<1:46:07,  1.16s/it]

  9%|▉         | 535/6015 [10:23<1:45:58,  1.16s/it]

  9%|▉         | 536/6015 [10:24<1:45:57,  1.16s/it]

  9%|▉         | 537/6015 [10:25<1:45:53,  1.16s/it]

  9%|▉         | 538/6015 [10:26<1:46:03,  1.16s/it]

  9%|▉         | 539/6015 [10:27<1:46:05,  1.16s/it]

  9%|▉         | 540/6015 [10:29<1:45:58,  1.16s/it]

  9%|▉         | 541/6015 [10:30<1:45:51,  1.16s/it]

  9%|▉         | 542/6015 [10:31<1:45:59,  1.16s/it]

  9%|▉         | 543/6015 [10:32<1:45:58,  1.16s/it]

  9%|▉         | 544/6015 [10:33<1:45:54,  1.16s/it]

  9%|▉         | 545/6015 [10:34<1:45:43,  1.16s/it]

  9%|▉         | 546/6015 [10:36<1:45:42,  1.16s/it]

  9%|▉         | 547/6015 [10:37<1:45:44,  1.16s/it]

  9%|▉         | 548/6015 [10:38<1:45:43,  1.16s/it]

  9%|▉         | 549/6015 [10:39<1:45:45,  1.16s/it]

  9%|▉         | 550/6015 [10:40<1:45:50,  1.16s/it]

  9%|▉         | 551/6015 [10:41<1:45:51,  1.16s/it]

  9%|▉         | 552/6015 [10:43<1:45:44,  1.16s/it]

  9%|▉         | 553/6015 [10:44<1:45:48,  1.16s/it]

  9%|▉         | 554/6015 [10:45<1:45:44,  1.16s/it]

  9%|▉         | 555/6015 [10:46<1:45:38,  1.16s/it]

  9%|▉         | 556/6015 [10:47<1:45:39,  1.16s/it]

  9%|▉         | 557/6015 [10:48<1:45:35,  1.16s/it]

  9%|▉         | 558/6015 [10:50<1:45:36,  1.16s/it]

  9%|▉         | 559/6015 [10:51<1:45:39,  1.16s/it]

  9%|▉         | 560/6015 [10:52<1:45:28,  1.16s/it]

  9%|▉         | 561/6015 [10:53<1:45:24,  1.16s/it]

  9%|▉         | 562/6015 [10:54<1:45:19,  1.16s/it]

  9%|▉         | 563/6015 [10:55<1:45:21,  1.16s/it]

  9%|▉         | 564/6015 [10:56<1:45:14,  1.16s/it]

  9%|▉         | 565/6015 [10:58<1:45:15,  1.16s/it]

  9%|▉         | 566/6015 [10:59<1:45:21,  1.16s/it]

  9%|▉         | 567/6015 [11:00<1:45:18,  1.16s/it]

  9%|▉         | 568/6015 [11:01<1:45:16,  1.16s/it]

  9%|▉         | 569/6015 [11:02<1:45:20,  1.16s/it]

  9%|▉         | 570/6015 [11:03<1:45:23,  1.16s/it]

  9%|▉         | 571/6015 [11:05<1:45:23,  1.16s/it]

 10%|▉         | 572/6015 [11:06<1:45:19,  1.16s/it]

 10%|▉         | 573/6015 [11:07<1:45:14,  1.16s/it]

 10%|▉         | 574/6015 [11:08<1:45:12,  1.16s/it]

 10%|▉         | 575/6015 [11:09<1:45:14,  1.16s/it]

 10%|▉         | 576/6015 [11:10<1:45:16,  1.16s/it]

 10%|▉         | 577/6015 [11:12<1:45:26,  1.16s/it]

 10%|▉         | 578/6015 [11:13<1:45:24,  1.16s/it]

 10%|▉         | 579/6015 [11:14<1:45:24,  1.16s/it]

 10%|▉         | 580/6015 [11:15<1:45:29,  1.16s/it]

 10%|▉         | 581/6015 [11:16<1:45:23,  1.16s/it]

 10%|▉         | 582/6015 [11:17<1:45:12,  1.16s/it]

 10%|▉         | 583/6015 [11:19<1:45:20,  1.16s/it]

 10%|▉         | 584/6015 [11:20<1:45:13,  1.16s/it]

 10%|▉         | 585/6015 [11:21<1:45:14,  1.16s/it]

 10%|▉         | 586/6015 [11:22<1:45:09,  1.16s/it]

 10%|▉         | 587/6015 [11:23<1:45:07,  1.16s/it]

 10%|▉         | 588/6015 [11:24<1:45:03,  1.16s/it]

 10%|▉         | 589/6015 [11:26<1:45:05,  1.16s/it]

 10%|▉         | 590/6015 [11:27<1:44:59,  1.16s/it]

 10%|▉         | 591/6015 [11:28<1:45:02,  1.16s/it]

 10%|▉         | 592/6015 [11:29<1:45:00,  1.16s/it]

 10%|▉         | 593/6015 [11:30<1:44:59,  1.16s/it]

 10%|▉         | 594/6015 [11:31<1:44:58,  1.16s/it]

 10%|▉         | 595/6015 [11:32<1:45:01,  1.16s/it]

 10%|▉         | 596/6015 [11:34<1:45:02,  1.16s/it]

 10%|▉         | 597/6015 [11:35<1:45:04,  1.16s/it]

 10%|▉         | 598/6015 [11:36<1:44:59,  1.16s/it]

 10%|▉         | 599/6015 [11:37<1:44:51,  1.16s/it]

 10%|▉         | 600/6015 [11:38<1:44:47,  1.16s/it]

 10%|▉         | 601/6015 [11:39<1:44:44,  1.16s/it]

 10%|█         | 602/6015 [11:41<1:44:46,  1.16s/it]

 10%|█         | 603/6015 [11:42<1:44:44,  1.16s/it]

 10%|█         | 604/6015 [11:43<1:44:44,  1.16s/it]

 10%|█         | 605/6015 [11:44<1:44:52,  1.16s/it]

 10%|█         | 606/6015 [11:45<1:44:52,  1.16s/it]

 10%|█         | 607/6015 [11:46<1:44:55,  1.16s/it]

 10%|█         | 608/6015 [11:48<1:45:07,  1.17s/it]

 10%|█         | 609/6015 [11:49<1:44:57,  1.16s/it]

 10%|█         | 610/6015 [11:50<1:44:49,  1.16s/it]

 10%|█         | 611/6015 [11:51<1:44:50,  1.16s/it]

 10%|█         | 612/6015 [11:52<1:44:54,  1.16s/it]

 10%|█         | 613/6015 [11:53<1:44:52,  1.16s/it]

 10%|█         | 614/6015 [11:55<1:44:50,  1.16s/it]

 10%|█         | 615/6015 [11:56<1:44:45,  1.16s/it]

 10%|█         | 616/6015 [11:57<1:44:39,  1.16s/it]

 10%|█         | 617/6015 [11:58<1:44:29,  1.16s/it]

 10%|█         | 618/6015 [11:59<1:44:24,  1.16s/it]

 10%|█         | 619/6015 [12:00<1:44:30,  1.16s/it]

 10%|█         | 620/6015 [12:02<1:44:26,  1.16s/it]

 10%|█         | 621/6015 [12:03<1:44:28,  1.16s/it]

 10%|█         | 622/6015 [12:04<1:44:25,  1.16s/it]

 10%|█         | 623/6015 [12:05<1:44:25,  1.16s/it]

 10%|█         | 624/6015 [12:06<1:44:23,  1.16s/it]

 10%|█         | 625/6015 [12:07<1:44:23,  1.16s/it]

logging
logging the anndata

 10%|█         | 626/6015 [12:09<1:50:17,  1.23s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 10%|█         | 627/6015 [12:10<1:48:22,  1.21s/it]

 10%|█         | 628/6015 [12:11<1:46:59,  1.19s/it]

 10%|█         | 629/6015 [12:12<1:46:03,  1.18s/it]

 10%|█         | 630/6015 [12:13<1:45:29,  1.18s/it]

 10%|█         | 631/6015 [12:15<1:44:55,  1.17s/it]

 11%|█         | 632/6015 [12:16<1:44:28,  1.16s/it]

 11%|█         | 633/6015 [12:17<1:44:11,  1.16s/it]

 11%|█         | 634/6015 [12:18<1:43:58,  1.16s/it]

 11%|█         | 635/6015 [12:19<1:43:54,  1.16s/it]

 11%|█         | 636/6015 [12:20<1:43:50,  1.16s/it]

 11%|█         | 637/6015 [12:21<1:43:43,  1.16s/it]

 11%|█         | 638/6015 [12:23<1:43:40,  1.16s/it]

 11%|█         | 639/6015 [12:24<1:43:43,  1.16s/it]

 11%|█         | 640/6015 [12:25<1:43:37,  1.16s/it]

 11%|█         | 641/6015 [12:26<1:43:31,  1.16s/it]

 11%|█         | 642/6015 [12:27<1:43:25,  1.15s/it]

 11%|█         | 643/6015 [12:28<1:43:27,  1.16s/it]

 11%|█         | 644/6015 [12:30<1:43:24,  1.16s/it]

 11%|█         | 645/6015 [12:31<1:43:26,  1.16s/it]

 11%|█         | 646/6015 [12:32<1:43:30,  1.16s/it]

 11%|█         | 647/6015 [12:33<1:43:28,  1.16s/it]

 11%|█         | 648/6015 [12:34<1:43:25,  1.16s/it]

 11%|█         | 649/6015 [12:35<1:43:26,  1.16s/it]

 11%|█         | 650/6015 [12:36<1:43:19,  1.16s/it]

 11%|█         | 651/6015 [12:38<1:43:19,  1.16s/it]

 11%|█         | 652/6015 [12:39<1:43:20,  1.16s/it]

 11%|█         | 653/6015 [12:40<1:43:24,  1.16s/it]

 11%|█         | 654/6015 [12:41<1:43:21,  1.16s/it]

 11%|█         | 655/6015 [12:42<1:43:23,  1.16s/it]

 11%|█         | 656/6015 [12:43<1:43:18,  1.16s/it]

 11%|█         | 657/6015 [12:45<1:43:19,  1.16s/it]

 11%|█         | 658/6015 [12:46<1:43:15,  1.16s/it]

 11%|█         | 659/6015 [12:47<1:43:14,  1.16s/it]

 11%|█         | 660/6015 [12:48<1:43:05,  1.16s/it]

 11%|█         | 661/6015 [12:49<1:43:04,  1.16s/it]

 11%|█         | 662/6015 [12:50<1:43:03,  1.16s/it]

 11%|█         | 663/6015 [12:52<1:43:07,  1.16s/it]

 11%|█         | 664/6015 [12:53<1:43:08,  1.16s/it]

 11%|█         | 665/6015 [12:54<1:43:03,  1.16s/it]

 11%|█         | 666/6015 [12:55<1:43:06,  1.16s/it]

 11%|█         | 667/6015 [12:56<1:43:04,  1.16s/it]

 11%|█         | 668/6015 [12:57<1:43:04,  1.16s/it]

 11%|█         | 669/6015 [12:58<1:43:09,  1.16s/it]

 11%|█         | 670/6015 [13:00<1:43:09,  1.16s/it]

 11%|█         | 671/6015 [13:01<1:43:08,  1.16s/it]

 11%|█         | 672/6015 [13:02<1:43:05,  1.16s/it]

 11%|█         | 673/6015 [13:03<1:43:00,  1.16s/it]

 11%|█         | 674/6015 [13:04<1:42:56,  1.16s/it]

 11%|█         | 675/6015 [13:05<1:42:51,  1.16s/it]

 11%|█         | 676/6015 [13:07<1:42:53,  1.16s/it]

 11%|█▏        | 677/6015 [13:08<1:42:51,  1.16s/it]

 11%|█▏        | 678/6015 [13:09<1:42:52,  1.16s/it]

 11%|█▏        | 679/6015 [13:10<1:42:51,  1.16s/it]

 11%|█▏        | 680/6015 [13:11<1:42:49,  1.16s/it]

 11%|█▏        | 681/6015 [13:12<1:42:48,  1.16s/it]

 11%|█▏        | 682/6015 [13:13<1:42:44,  1.16s/it]

 11%|█▏        | 683/6015 [13:15<1:42:44,  1.16s/it]

 11%|█▏        | 684/6015 [13:16<1:42:50,  1.16s/it]

 11%|█▏        | 685/6015 [13:17<1:42:46,  1.16s/it]

 11%|█▏        | 686/6015 [13:18<1:42:45,  1.16s/it]

 11%|█▏        | 687/6015 [13:19<1:42:40,  1.16s/it]

 11%|█▏        | 688/6015 [13:20<1:42:41,  1.16s/it]

 11%|█▏        | 689/6015 [13:22<1:42:39,  1.16s/it]

 11%|█▏        | 690/6015 [13:23<1:42:32,  1.16s/it]

 11%|█▏        | 691/6015 [13:24<1:42:31,  1.16s/it]

 12%|█▏        | 692/6015 [13:25<1:42:31,  1.16s/it]

 12%|█▏        | 693/6015 [13:26<1:42:33,  1.16s/it]

 12%|█▏        | 694/6015 [13:27<1:42:30,  1.16s/it]

 12%|█▏        | 695/6015 [13:29<1:42:35,  1.16s/it]

 12%|█▏        | 696/6015 [13:30<1:42:39,  1.16s/it]

 12%|█▏        | 697/6015 [13:31<1:42:32,  1.16s/it]

 12%|█▏        | 698/6015 [13:32<1:42:30,  1.16s/it]

 12%|█▏        | 699/6015 [13:33<1:42:25,  1.16s/it]

 12%|█▏        | 700/6015 [13:34<1:42:24,  1.16s/it]

 12%|█▏        | 701/6015 [13:35<1:42:25,  1.16s/it]

 12%|█▏        | 702/6015 [13:37<1:42:21,  1.16s/it]

 12%|█▏        | 703/6015 [13:38<1:42:25,  1.16s/it]

 12%|█▏        | 704/6015 [13:39<1:42:29,  1.16s/it]

 12%|█▏        | 705/6015 [13:40<1:42:27,  1.16s/it]

 12%|█▏        | 706/6015 [13:41<1:42:23,  1.16s/it]

 12%|█▏        | 707/6015 [13:42<1:42:19,  1.16s/it]

 12%|█▏        | 708/6015 [13:44<1:42:14,  1.16s/it]

 12%|█▏        | 709/6015 [13:45<1:42:15,  1.16s/it]

 12%|█▏        | 710/6015 [13:46<1:42:14,  1.16s/it]

 12%|█▏        | 711/6015 [13:47<1:42:17,  1.16s/it]

 12%|█▏        | 712/6015 [13:48<1:42:19,  1.16s/it]

 12%|█▏        | 713/6015 [13:49<1:42:20,  1.16s/it]

 12%|█▏        | 714/6015 [13:51<1:42:20,  1.16s/it]

 12%|█▏        | 715/6015 [13:52<1:42:26,  1.16s/it]

 12%|█▏        | 716/6015 [13:53<1:42:22,  1.16s/it]

 12%|█▏        | 717/6015 [13:54<1:42:17,  1.16s/it]

 12%|█▏        | 718/6015 [13:55<1:42:10,  1.16s/it]

 12%|█▏        | 719/6015 [13:56<1:42:03,  1.16s/it]

 12%|█▏        | 720/6015 [13:57<1:42:06,  1.16s/it]

 12%|█▏        | 721/6015 [13:59<1:42:05,  1.16s/it]

 12%|█▏        | 722/6015 [14:00<1:42:08,  1.16s/it]

 12%|█▏        | 723/6015 [14:01<1:42:09,  1.16s/it]

 12%|█▏        | 724/6015 [14:02<1:42:11,  1.16s/it]

 12%|█▏        | 725/6015 [14:03<1:42:08,  1.16s/it]

 12%|█▏        | 726/6015 [14:04<1:42:01,  1.16s/it]

 12%|█▏        | 727/6015 [14:06<1:41:59,  1.16s/it]

 12%|█▏        | 728/6015 [14:07<1:42:05,  1.16s/it]

 12%|█▏        | 729/6015 [14:08<1:42:03,  1.16s/it]

 12%|█▏        | 730/6015 [14:09<1:42:00,  1.16s/it]

 12%|█▏        | 731/6015 [14:10<1:41:55,  1.16s/it]

 12%|█▏        | 732/6015 [14:11<1:41:45,  1.16s/it]

 12%|█▏        | 733/6015 [14:13<1:41:48,  1.16s/it]

 12%|█▏        | 734/6015 [14:14<1:41:47,  1.16s/it]

 12%|█▏        | 735/6015 [14:15<1:41:46,  1.16s/it]

 12%|█▏        | 736/6015 [14:16<1:41:50,  1.16s/it]

 12%|█▏        | 737/6015 [14:17<1:41:44,  1.16s/it]

 12%|█▏        | 738/6015 [14:18<1:41:38,  1.16s/it]

 12%|█▏        | 739/6015 [14:19<1:41:35,  1.16s/it]

 12%|█▏        | 740/6015 [14:21<1:41:40,  1.16s/it]

 12%|█▏        | 741/6015 [14:22<1:41:41,  1.16s/it]

 12%|█▏        | 742/6015 [14:23<1:41:40,  1.16s/it]

 12%|█▏        | 743/6015 [14:24<1:41:41,  1.16s/it]

 12%|█▏        | 744/6015 [14:25<1:41:42,  1.16s/it]

 12%|█▏        | 745/6015 [14:26<1:41:36,  1.16s/it]

 12%|█▏        | 746/6015 [14:28<1:41:37,  1.16s/it]

 12%|█▏        | 747/6015 [14:29<1:41:28,  1.16s/it]

 12%|█▏        | 748/6015 [14:30<1:41:31,  1.16s/it]

 12%|█▏        | 749/6015 [14:31<1:41:23,  1.16s/it]

 12%|█▏        | 750/6015 [14:32<1:41:27,  1.16s/it]

 12%|█▏        | 751/6015 [14:33<1:41:27,  1.16s/it]

 13%|█▎        | 752/6015 [14:34<1:41:27,  1.16s/it]

 13%|█▎        | 753/6015 [14:36<1:41:26,  1.16s/it]

 13%|█▎        | 754/6015 [14:37<1:41:27,  1.16s/it]

 13%|█▎        | 755/6015 [14:38<1:41:28,  1.16s/it]

 13%|█▎        | 756/6015 [14:39<1:41:28,  1.16s/it]

 13%|█▎        | 757/6015 [14:40<1:41:26,  1.16s/it]

 13%|█▎        | 758/6015 [14:41<1:41:22,  1.16s/it]

 13%|█▎        | 759/6015 [14:43<1:41:17,  1.16s/it]

 13%|█▎        | 760/6015 [14:44<1:41:20,  1.16s/it]

 13%|█▎        | 761/6015 [14:45<1:41:22,  1.16s/it]

 13%|█▎        | 762/6015 [14:46<1:41:22,  1.16s/it]

 13%|█▎        | 763/6015 [14:47<1:41:18,  1.16s/it]

 13%|█▎        | 764/6015 [14:48<1:41:20,  1.16s/it]

 13%|█▎        | 765/6015 [14:50<1:41:20,  1.16s/it]

 13%|█▎        | 766/6015 [14:51<1:41:16,  1.16s/it]

 13%|█▎        | 767/6015 [14:52<1:41:11,  1.16s/it]

 13%|█▎        | 768/6015 [14:53<1:41:11,  1.16s/it]

 13%|█▎        | 769/6015 [14:54<1:41:08,  1.16s/it]

 13%|█▎        | 770/6015 [14:55<1:41:13,  1.16s/it]

 13%|█▎        | 771/6015 [14:56<1:41:17,  1.16s/it]

 13%|█▎        | 772/6015 [14:58<1:41:20,  1.16s/it]

 13%|█▎        | 773/6015 [14:59<1:41:20,  1.16s/it]

 13%|█▎        | 774/6015 [15:00<1:41:19,  1.16s/it]

 13%|█▎        | 775/6015 [15:01<1:41:13,  1.16s/it]

 13%|█▎        | 776/6015 [15:02<1:41:05,  1.16s/it]

 13%|█▎        | 777/6015 [15:03<1:41:03,  1.16s/it]

 13%|█▎        | 778/6015 [15:05<1:41:01,  1.16s/it]

 13%|█▎        | 779/6015 [15:06<1:40:59,  1.16s/it]

 13%|█▎        | 780/6015 [15:07<1:41:00,  1.16s/it]

 13%|█▎        | 781/6015 [15:08<1:41:01,  1.16s/it]

 13%|█▎        | 782/6015 [15:09<1:40:59,  1.16s/it]

 13%|█▎        | 783/6015 [15:10<1:40:59,  1.16s/it]

 13%|█▎        | 784/6015 [15:12<1:41:02,  1.16s/it]

 13%|█▎        | 785/6015 [15:13<1:41:02,  1.16s/it]

 13%|█▎        | 786/6015 [15:14<1:40:58,  1.16s/it]

 13%|█▎        | 787/6015 [15:15<1:41:00,  1.16s/it]

 13%|█▎        | 788/6015 [15:16<1:40:57,  1.16s/it]

 13%|█▎        | 789/6015 [15:17<1:40:54,  1.16s/it]

 13%|█▎        | 790/6015 [15:18<1:40:50,  1.16s/it]

 13%|█▎        | 791/6015 [15:20<1:40:45,  1.16s/it]

 13%|█▎        | 792/6015 [15:21<1:40:48,  1.16s/it]

 13%|█▎        | 793/6015 [15:22<1:40:51,  1.16s/it]

 13%|█▎        | 794/6015 [15:23<1:40:45,  1.16s/it]

 13%|█▎        | 795/6015 [15:24<1:40:42,  1.16s/it]

 13%|█▎        | 796/6015 [15:25<1:40:40,  1.16s/it]

 13%|█▎        | 797/6015 [15:27<1:40:42,  1.16s/it]

 13%|█▎        | 798/6015 [15:28<1:40:43,  1.16s/it]

 13%|█▎        | 799/6015 [15:29<1:40:33,  1.16s/it]

 13%|█▎        | 800/6015 [15:30<1:40:30,  1.16s/it]

 13%|█▎        | 801/6015 [15:31<1:40:29,  1.16s/it]

 13%|█▎        | 802/6015 [15:32<1:40:28,  1.16s/it]

 13%|█▎        | 803/6015 [15:34<1:40:34,  1.16s/it]

 13%|█▎        | 804/6015 [15:35<1:40:34,  1.16s/it]

 13%|█▎        | 805/6015 [15:36<1:40:32,  1.16s/it]

 13%|█▎        | 806/6015 [15:37<1:40:30,  1.16s/it]

 13%|█▎        | 807/6015 [15:38<1:40:25,  1.16s/it]

 13%|█▎        | 808/6015 [15:39<1:40:27,  1.16s/it]

 13%|█▎        | 809/6015 [15:40<1:40:29,  1.16s/it]

 13%|█▎        | 810/6015 [15:42<1:40:26,  1.16s/it]

 13%|█▎        | 811/6015 [15:43<1:40:24,  1.16s/it]

 13%|█▎        | 812/6015 [15:44<1:40:24,  1.16s/it]

 14%|█▎        | 813/6015 [15:45<1:40:28,  1.16s/it]

 14%|█▎        | 814/6015 [15:46<1:40:23,  1.16s/it]

 14%|█▎        | 815/6015 [15:47<1:40:23,  1.16s/it]

 14%|█▎        | 816/6015 [15:49<1:40:23,  1.16s/it]

 14%|█▎        | 817/6015 [15:50<1:40:18,  1.16s/it]

 14%|█▎        | 818/6015 [15:51<1:40:15,  1.16s/it]

 14%|█▎        | 819/6015 [15:52<1:40:14,  1.16s/it]

 14%|█▎        | 820/6015 [15:53<1:40:15,  1.16s/it]

 14%|█▎        | 821/6015 [15:54<1:40:18,  1.16s/it]

 14%|█▎        | 822/6015 [15:56<1:40:13,  1.16s/it]

 14%|█▎        | 823/6015 [15:57<1:40:09,  1.16s/it]

 14%|█▎        | 824/6015 [15:58<1:40:13,  1.16s/it]

 14%|█▎        | 825/6015 [15:59<1:40:07,  1.16s/it]

 14%|█▎        | 826/6015 [16:00<1:40:11,  1.16s/it]

 14%|█▎        | 827/6015 [16:01<1:40:07,  1.16s/it]

 14%|█▍        | 828/6015 [16:02<1:40:02,  1.16s/it]

 14%|█▍        | 829/6015 [16:04<1:40:05,  1.16s/it]

 14%|█▍        | 830/6015 [16:05<1:40:09,  1.16s/it]

 14%|█▍        | 831/6015 [16:06<1:40:08,  1.16s/it]

 14%|█▍        | 832/6015 [16:07<1:40:03,  1.16s/it]

 14%|█▍        | 833/6015 [16:08<1:39:58,  1.16s/it]

 14%|█▍        | 834/6015 [16:09<1:40:03,  1.16s/it]

 14%|█▍        | 835/6015 [16:11<1:40:02,  1.16s/it]

 14%|█▍        | 836/6015 [16:12<1:40:01,  1.16s/it]

 14%|█▍        | 837/6015 [16:13<1:39:59,  1.16s/it]

 14%|█▍        | 838/6015 [16:14<1:39:50,  1.16s/it]

 14%|█▍        | 839/6015 [16:15<1:39:44,  1.16s/it]

 14%|█▍        | 840/6015 [16:16<1:39:48,  1.16s/it]

 14%|█▍        | 841/6015 [16:18<1:39:52,  1.16s/it]

 14%|█▍        | 842/6015 [16:19<1:40:03,  1.16s/it]

 14%|█▍        | 843/6015 [16:20<1:40:08,  1.16s/it]

 14%|█▍        | 844/6015 [16:21<1:40:08,  1.16s/it]

 14%|█▍        | 845/6015 [16:22<1:40:03,  1.16s/it]

 14%|█▍        | 846/6015 [16:23<1:39:58,  1.16s/it]

 14%|█▍        | 847/6015 [16:25<1:39:57,  1.16s/it]

 14%|█▍        | 848/6015 [16:26<1:39:52,  1.16s/it]

 14%|█▍        | 849/6015 [16:27<1:39:53,  1.16s/it]

 14%|█▍        | 850/6015 [16:28<1:39:49,  1.16s/it]

 14%|█▍        | 851/6015 [16:29<1:39:37,  1.16s/it]

 14%|█▍        | 852/6015 [16:30<1:39:40,  1.16s/it]

 14%|█▍        | 853/6015 [16:31<1:39:42,  1.16s/it]

 14%|█▍        | 854/6015 [16:33<1:39:36,  1.16s/it]

 14%|█▍        | 855/6015 [16:34<1:39:35,  1.16s/it]

 14%|█▍        | 856/6015 [16:35<1:39:36,  1.16s/it]

 14%|█▍        | 857/6015 [16:36<1:39:34,  1.16s/it]

 14%|█▍        | 858/6015 [16:37<1:39:32,  1.16s/it]

 14%|█▍        | 859/6015 [16:38<1:39:33,  1.16s/it]

 14%|█▍        | 860/6015 [16:40<1:39:30,  1.16s/it]

 14%|█▍        | 861/6015 [16:41<1:39:27,  1.16s/it]

 14%|█▍        | 862/6015 [16:42<1:39:19,  1.16s/it]

 14%|█▍        | 863/6015 [16:43<1:39:15,  1.16s/it]

 14%|█▍        | 864/6015 [16:44<1:39:15,  1.16s/it]

 14%|█▍        | 865/6015 [16:45<1:39:19,  1.16s/it]

 14%|█▍        | 866/6015 [16:47<1:39:25,  1.16s/it]

 14%|█▍        | 867/6015 [16:48<1:39:28,  1.16s/it]

 14%|█▍        | 868/6015 [16:49<1:39:25,  1.16s/it]

 14%|█▍        | 869/6015 [16:50<1:39:19,  1.16s/it]

 14%|█▍        | 870/6015 [16:51<1:39:20,  1.16s/it]

 14%|█▍        | 871/6015 [16:52<1:39:15,  1.16s/it]

 14%|█▍        | 872/6015 [16:53<1:39:12,  1.16s/it]

 15%|█▍        | 873/6015 [16:55<1:39:11,  1.16s/it]

 15%|█▍        | 874/6015 [16:56<1:39:10,  1.16s/it]

 15%|█▍        | 875/6015 [16:57<1:39:14,  1.16s/it]

 15%|█▍        | 876/6015 [16:58<1:39:11,  1.16s/it]

 15%|█▍        | 877/6015 [16:59<1:39:12,  1.16s/it]

 15%|█▍        | 878/6015 [17:00<1:39:14,  1.16s/it]

 15%|█▍        | 879/6015 [17:02<1:39:18,  1.16s/it]

 15%|█▍        | 880/6015 [17:03<1:39:12,  1.16s/it]

 15%|█▍        | 881/6015 [17:04<1:39:09,  1.16s/it]

 15%|█▍        | 882/6015 [17:05<1:39:05,  1.16s/it]

 15%|█▍        | 883/6015 [17:06<1:39:04,  1.16s/it]

 15%|█▍        | 884/6015 [17:07<1:39:02,  1.16s/it]

 15%|█▍        | 885/6015 [17:09<1:39:06,  1.16s/it]

 15%|█▍        | 886/6015 [17:10<1:39:03,  1.16s/it]

 15%|█▍        | 887/6015 [17:11<1:39:01,  1.16s/it]

 15%|█▍        | 888/6015 [17:12<1:38:59,  1.16s/it]

 15%|█▍        | 889/6015 [17:13<1:39:03,  1.16s/it]

 15%|█▍        | 890/6015 [17:14<1:39:05,  1.16s/it]

 15%|█▍        | 891/6015 [17:15<1:39:04,  1.16s/it]

 15%|█▍        | 892/6015 [17:17<1:38:56,  1.16s/it]

 15%|█▍        | 893/6015 [17:18<1:38:57,  1.16s/it]

 15%|█▍        | 894/6015 [17:19<1:38:55,  1.16s/it]

 15%|█▍        | 895/6015 [17:20<1:38:51,  1.16s/it]

 15%|█▍        | 896/6015 [17:21<1:38:57,  1.16s/it]

 15%|█▍        | 897/6015 [17:22<1:38:55,  1.16s/it]

 15%|█▍        | 898/6015 [17:24<1:38:51,  1.16s/it]

 15%|█▍        | 899/6015 [17:25<1:38:49,  1.16s/it]

 15%|█▍        | 900/6015 [17:26<1:38:44,  1.16s/it]

 15%|█▍        | 901/6015 [17:27<1:38:48,  1.16s/it]

 15%|█▍        | 902/6015 [17:28<1:38:49,  1.16s/it]

 15%|█▌        | 903/6015 [17:29<1:38:50,  1.16s/it]

 15%|█▌        | 904/6015 [17:31<1:38:45,  1.16s/it]

 15%|█▌        | 905/6015 [17:32<1:38:40,  1.16s/it]

 15%|█▌        | 906/6015 [17:33<1:38:34,  1.16s/it]

 15%|█▌        | 907/6015 [17:34<1:38:33,  1.16s/it]

 15%|█▌        | 908/6015 [17:35<1:38:35,  1.16s/it]

 15%|█▌        | 909/6015 [17:36<1:38:35,  1.16s/it]

 15%|█▌        | 910/6015 [17:38<1:38:35,  1.16s/it]

 15%|█▌        | 911/6015 [17:39<1:38:37,  1.16s/it]

 15%|█▌        | 912/6015 [17:40<1:38:38,  1.16s/it]

 15%|█▌        | 913/6015 [17:41<1:38:39,  1.16s/it]

 15%|█▌        | 914/6015 [17:42<1:38:35,  1.16s/it]

 15%|█▌        | 915/6015 [17:43<1:38:32,  1.16s/it]

 15%|█▌        | 916/6015 [17:44<1:38:27,  1.16s/it]

 15%|█▌        | 917/6015 [17:46<1:38:21,  1.16s/it]

 15%|█▌        | 918/6015 [17:47<1:38:23,  1.16s/it]

 15%|█▌        | 919/6015 [17:48<1:38:28,  1.16s/it]

 15%|█▌        | 920/6015 [17:49<1:38:30,  1.16s/it]

 15%|█▌        | 921/6015 [17:50<1:38:33,  1.16s/it]

 15%|█▌        | 922/6015 [17:51<1:38:27,  1.16s/it]

 15%|█▌        | 923/6015 [17:53<1:38:26,  1.16s/it]

 15%|█▌        | 924/6015 [17:54<1:38:26,  1.16s/it]

 15%|█▌        | 925/6015 [17:55<1:38:22,  1.16s/it]

 15%|█▌        | 926/6015 [17:56<1:38:18,  1.16s/it]

 15%|█▌        | 927/6015 [17:57<1:38:14,  1.16s/it]

 15%|█▌        | 928/6015 [17:58<1:38:14,  1.16s/it]

 15%|█▌        | 929/6015 [18:00<1:38:10,  1.16s/it]

 15%|█▌        | 930/6015 [18:01<1:38:13,  1.16s/it]

 15%|█▌        | 931/6015 [18:02<1:38:16,  1.16s/it]

 15%|█▌        | 932/6015 [18:03<1:38:20,  1.16s/it]

 16%|█▌        | 933/6015 [18:04<1:38:21,  1.16s/it]

 16%|█▌        | 934/6015 [18:05<1:38:13,  1.16s/it]

 16%|█▌        | 935/6015 [18:06<1:38:06,  1.16s/it]

 16%|█▌        | 936/6015 [18:08<1:38:06,  1.16s/it]

 16%|█▌        | 937/6015 [18:09<1:38:02,  1.16s/it]

 16%|█▌        | 938/6015 [18:10<1:38:01,  1.16s/it]

 16%|█▌        | 939/6015 [18:11<1:37:56,  1.16s/it]

 16%|█▌        | 940/6015 [18:12<1:37:57,  1.16s/it]

 16%|█▌        | 941/6015 [18:13<1:38:01,  1.16s/it]

 16%|█▌        | 942/6015 [18:15<1:38:05,  1.16s/it]

 16%|█▌        | 943/6015 [18:16<1:38:07,  1.16s/it]

 16%|█▌        | 944/6015 [18:17<1:38:01,  1.16s/it]

 16%|█▌        | 945/6015 [18:18<1:37:56,  1.16s/it]

 16%|█▌        | 946/6015 [18:19<1:37:56,  1.16s/it]

 16%|█▌        | 947/6015 [18:20<1:37:49,  1.16s/it]

 16%|█▌        | 948/6015 [18:22<1:37:54,  1.16s/it]

 16%|█▌        | 949/6015 [18:23<1:37:58,  1.16s/it]

 16%|█▌        | 950/6015 [18:24<1:37:55,  1.16s/it]

 16%|█▌        | 951/6015 [18:25<1:37:49,  1.16s/it]

 16%|█▌        | 952/6015 [18:26<1:37:49,  1.16s/it]

 16%|█▌        | 953/6015 [18:27<1:37:46,  1.16s/it]

 16%|█▌        | 954/6015 [18:29<1:37:47,  1.16s/it]

 16%|█▌        | 955/6015 [18:30<1:37:47,  1.16s/it]

 16%|█▌        | 956/6015 [18:31<1:37:47,  1.16s/it]

 16%|█▌        | 957/6015 [18:32<1:37:41,  1.16s/it]

 16%|█▌        | 958/6015 [18:33<1:37:42,  1.16s/it]

 16%|█▌        | 959/6015 [18:34<1:37:43,  1.16s/it]

 16%|█▌        | 960/6015 [18:35<1:37:47,  1.16s/it]

 16%|█▌        | 961/6015 [18:37<1:37:43,  1.16s/it]

 16%|█▌        | 962/6015 [18:38<1:37:32,  1.16s/it]

 16%|█▌        | 963/6015 [18:39<1:37:32,  1.16s/it]

 16%|█▌        | 964/6015 [18:40<1:37:28,  1.16s/it]

 16%|█▌        | 965/6015 [18:41<1:37:27,  1.16s/it]

 16%|█▌        | 966/6015 [18:42<1:37:26,  1.16s/it]

 16%|█▌        | 967/6015 [18:44<1:37:25,  1.16s/it]

 16%|█▌        | 968/6015 [18:45<1:37:23,  1.16s/it]

 16%|█▌        | 969/6015 [18:46<1:37:31,  1.16s/it]

 16%|█▌        | 970/6015 [18:47<1:37:31,  1.16s/it]

 16%|█▌        | 971/6015 [18:48<1:37:24,  1.16s/it]

 16%|█▌        | 972/6015 [18:49<1:37:23,  1.16s/it]

 16%|█▌        | 973/6015 [18:51<1:37:24,  1.16s/it]

 16%|█▌        | 974/6015 [18:52<1:37:17,  1.16s/it]

 16%|█▌        | 975/6015 [18:53<1:37:22,  1.16s/it]

 16%|█▌        | 976/6015 [18:54<1:37:21,  1.16s/it]

 16%|█▌        | 977/6015 [18:55<1:37:22,  1.16s/it]

 16%|█▋        | 978/6015 [18:56<1:37:18,  1.16s/it]

 16%|█▋        | 979/6015 [18:57<1:37:18,  1.16s/it]

 16%|█▋        | 980/6015 [18:59<1:37:20,  1.16s/it]

 16%|█▋        | 981/6015 [19:00<1:37:19,  1.16s/it]

 16%|█▋        | 982/6015 [19:01<1:37:14,  1.16s/it]

 16%|█▋        | 983/6015 [19:02<1:37:14,  1.16s/it]

 16%|█▋        | 984/6015 [19:03<1:37:12,  1.16s/it]

 16%|█▋        | 985/6015 [19:04<1:37:09,  1.16s/it]

 16%|█▋        | 986/6015 [19:06<1:37:08,  1.16s/it]

 16%|█▋        | 987/6015 [19:07<1:37:11,  1.16s/it]

 16%|█▋        | 988/6015 [19:08<1:37:10,  1.16s/it]

 16%|█▋        | 989/6015 [19:09<1:37:16,  1.16s/it]

 16%|█▋        | 990/6015 [19:10<1:37:12,  1.16s/it]

 16%|█▋        | 991/6015 [19:11<1:37:09,  1.16s/it]

 16%|█▋        | 992/6015 [19:13<1:37:04,  1.16s/it]

 17%|█▋        | 993/6015 [19:14<1:37:08,  1.16s/it]

 17%|█▋        | 994/6015 [19:15<1:37:06,  1.16s/it]

 17%|█▋        | 995/6015 [19:16<1:37:00,  1.16s/it]

 17%|█▋        | 996/6015 [19:17<1:36:58,  1.16s/it]

 17%|█▋        | 997/6015 [19:18<1:36:56,  1.16s/it]

 17%|█▋        | 998/6015 [19:20<1:37:02,  1.16s/it]

 17%|█▋        | 999/6015 [19:21<1:36:58,  1.16s/it]

 17%|█▋        | 1000/6015 [19:22<1:36:57,  1.16s/it]

 17%|█▋        | 1001/6015 [19:23<1:37:01,  1.16s/it]

 17%|█▋        | 1002/6015 [19:24<1:37:02,  1.16s/it]

 17%|█▋        | 1003/6015 [19:25<1:37:00,  1.16s/it]

 17%|█▋        | 1004/6015 [19:26<1:36:54,  1.16s/it]

 17%|█▋        | 1005/6015 [19:28<1:36:49,  1.16s/it]

 17%|█▋        | 1006/6015 [19:29<1:36:45,  1.16s/it]

 17%|█▋        | 1007/6015 [19:30<1:36:44,  1.16s/it]

 17%|█▋        | 1008/6015 [19:31<1:36:46,  1.16s/it]

 17%|█▋        | 1009/6015 [19:32<1:36:44,  1.16s/it]

 17%|█▋        | 1010/6015 [19:33<1:36:46,  1.16s/it]

 17%|█▋        | 1011/6015 [19:35<1:36:40,  1.16s/it]

 17%|█▋        | 1012/6015 [19:36<1:36:47,  1.16s/it]

 17%|█▋        | 1013/6015 [19:37<1:36:42,  1.16s/it]

 17%|█▋        | 1014/6015 [19:38<1:36:45,  1.16s/it]

 17%|█▋        | 1015/6015 [19:39<1:36:48,  1.16s/it]

 17%|█▋        | 1016/6015 [19:40<1:36:44,  1.16s/it]

 17%|█▋        | 1017/6015 [19:42<1:36:37,  1.16s/it]

 17%|█▋        | 1018/6015 [19:43<1:36:35,  1.16s/it]

 17%|█▋        | 1019/6015 [19:44<1:36:42,  1.16s/it]

 17%|█▋        | 1020/6015 [19:45<1:36:34,  1.16s/it]

 17%|█▋        | 1021/6015 [19:46<1:36:28,  1.16s/it]

 17%|█▋        | 1022/6015 [19:47<1:36:27,  1.16s/it]

 17%|█▋        | 1023/6015 [19:49<1:36:26,  1.16s/it]

 17%|█▋        | 1024/6015 [19:50<1:36:31,  1.16s/it]

 17%|█▋        | 1025/6015 [19:51<1:36:32,  1.16s/it]

 17%|█▋        | 1026/6015 [19:52<1:36:27,  1.16s/it]

 17%|█▋        | 1027/6015 [19:53<1:36:30,  1.16s/it]

 17%|█▋        | 1028/6015 [19:54<1:36:29,  1.16s/it]

 17%|█▋        | 1029/6015 [19:55<1:36:19,  1.16s/it]

 17%|█▋        | 1030/6015 [19:57<1:36:26,  1.16s/it]

 17%|█▋        | 1031/6015 [19:58<1:36:22,  1.16s/it]

 17%|█▋        | 1032/6015 [19:59<1:36:17,  1.16s/it]

 17%|█▋        | 1033/6015 [20:00<1:36:14,  1.16s/it]

 17%|█▋        | 1034/6015 [20:01<1:36:20,  1.16s/it]

 17%|█▋        | 1035/6015 [20:02<1:36:17,  1.16s/it]

 17%|█▋        | 1036/6015 [20:04<1:36:21,  1.16s/it]

 17%|█▋        | 1037/6015 [20:05<1:36:21,  1.16s/it]

 17%|█▋        | 1038/6015 [20:06<1:36:18,  1.16s/it]

 17%|█▋        | 1039/6015 [20:07<1:36:20,  1.16s/it]

 17%|█▋        | 1040/6015 [20:08<1:36:13,  1.16s/it]

 17%|█▋        | 1041/6015 [20:09<1:36:18,  1.16s/it]

 17%|█▋        | 1042/6015 [20:11<1:36:12,  1.16s/it]

 17%|█▋        | 1043/6015 [20:12<1:36:05,  1.16s/it]

 17%|█▋        | 1044/6015 [20:13<1:36:04,  1.16s/it]

 17%|█▋        | 1045/6015 [20:14<1:36:02,  1.16s/it]

 17%|█▋        | 1046/6015 [20:15<1:36:03,  1.16s/it]

 17%|█▋        | 1047/6015 [20:16<1:36:00,  1.16s/it]

 17%|█▋        | 1048/6015 [20:18<1:36:01,  1.16s/it]

 17%|█▋        | 1049/6015 [20:19<1:36:01,  1.16s/it]

 17%|█▋        | 1050/6015 [20:20<1:36:04,  1.16s/it]

 17%|█▋        | 1051/6015 [20:21<1:36:03,  1.16s/it]

 17%|█▋        | 1052/6015 [20:22<1:36:00,  1.16s/it]

 18%|█▊        | 1053/6015 [20:23<1:35:59,  1.16s/it]

 18%|█▊        | 1054/6015 [20:25<1:35:52,  1.16s/it]

 18%|█▊        | 1055/6015 [20:26<1:35:48,  1.16s/it]

 18%|█▊        | 1056/6015 [20:27<1:35:48,  1.16s/it]

 18%|█▊        | 1057/6015 [20:28<1:35:53,  1.16s/it]

 18%|█▊        | 1058/6015 [20:29<1:35:52,  1.16s/it]

 18%|█▊        | 1059/6015 [20:30<1:35:55,  1.16s/it]

 18%|█▊        | 1060/6015 [20:31<1:35:53,  1.16s/it]

 18%|█▊        | 1061/6015 [20:33<1:35:49,  1.16s/it]

 18%|█▊        | 1062/6015 [20:34<1:35:50,  1.16s/it]

 18%|█▊        | 1063/6015 [20:35<1:35:51,  1.16s/it]

 18%|█▊        | 1064/6015 [20:36<1:35:52,  1.16s/it]

 18%|█▊        | 1065/6015 [20:37<1:35:49,  1.16s/it]

 18%|█▊        | 1066/6015 [20:38<1:35:45,  1.16s/it]

 18%|█▊        | 1067/6015 [20:40<1:35:42,  1.16s/it]

 18%|█▊        | 1068/6015 [20:41<1:35:39,  1.16s/it]

 18%|█▊        | 1069/6015 [20:42<1:35:42,  1.16s/it]

 18%|█▊        | 1070/6015 [20:43<1:35:47,  1.16s/it]

 18%|█▊        | 1071/6015 [20:44<1:35:47,  1.16s/it]

 18%|█▊        | 1072/6015 [20:45<1:35:46,  1.16s/it]

 18%|█▊        | 1073/6015 [20:47<1:36:00,  1.17s/it]

 18%|█▊        | 1074/6015 [20:48<1:35:50,  1.16s/it]

 18%|█▊        | 1075/6015 [20:49<1:35:46,  1.16s/it]

 18%|█▊        | 1076/6015 [20:50<1:35:37,  1.16s/it]

 18%|█▊        | 1077/6015 [20:51<1:35:40,  1.16s/it]

 18%|█▊        | 1078/6015 [20:52<1:35:29,  1.16s/it]

 18%|█▊        | 1079/6015 [20:54<1:35:30,  1.16s/it]

 18%|█▊        | 1080/6015 [20:55<1:35:34,  1.16s/it]

 18%|█▊        | 1081/6015 [20:56<1:35:31,  1.16s/it]

 18%|█▊        | 1082/6015 [20:57<1:35:25,  1.16s/it]

 18%|█▊        | 1083/6015 [20:58<1:35:26,  1.16s/it]

 18%|█▊        | 1084/6015 [20:59<1:35:21,  1.16s/it]

 18%|█▊        | 1085/6015 [21:01<1:35:24,  1.16s/it]

 18%|█▊        | 1086/6015 [21:02<1:35:20,  1.16s/it]

 18%|█▊        | 1087/6015 [21:03<1:35:25,  1.16s/it]

 18%|█▊        | 1088/6015 [21:04<1:35:24,  1.16s/it]

 18%|█▊        | 1089/6015 [21:05<1:35:23,  1.16s/it]

 18%|█▊        | 1090/6015 [21:06<1:35:23,  1.16s/it]

 18%|█▊        | 1091/6015 [21:07<1:35:25,  1.16s/it]

 18%|█▊        | 1092/6015 [21:09<1:35:28,  1.16s/it]

 18%|█▊        | 1093/6015 [21:10<1:35:26,  1.16s/it]

 18%|█▊        | 1094/6015 [21:11<1:35:19,  1.16s/it]

 18%|█▊        | 1095/6015 [21:12<1:35:14,  1.16s/it]

 18%|█▊        | 1096/6015 [21:13<1:35:10,  1.16s/it]

 18%|█▊        | 1097/6015 [21:14<1:35:13,  1.16s/it]

 18%|█▊        | 1098/6015 [21:16<1:35:11,  1.16s/it]

 18%|█▊        | 1099/6015 [21:17<1:35:10,  1.16s/it]

 18%|█▊        | 1100/6015 [21:18<1:35:06,  1.16s/it]

 18%|█▊        | 1101/6015 [21:19<1:35:08,  1.16s/it]

 18%|█▊        | 1102/6015 [21:20<1:35:07,  1.16s/it]

 18%|█▊        | 1103/6015 [21:21<1:35:07,  1.16s/it]

 18%|█▊        | 1104/6015 [21:23<1:35:11,  1.16s/it]

 18%|█▊        | 1105/6015 [21:24<1:35:07,  1.16s/it]

 18%|█▊        | 1106/6015 [21:25<1:34:59,  1.16s/it]

 18%|█▊        | 1107/6015 [21:26<1:34:58,  1.16s/it]

 18%|█▊        | 1108/6015 [21:27<1:34:56,  1.16s/it]

 18%|█▊        | 1109/6015 [21:28<1:34:57,  1.16s/it]

 18%|█▊        | 1110/6015 [21:30<1:34:56,  1.16s/it]

 18%|█▊        | 1111/6015 [21:31<1:34:54,  1.16s/it]

 18%|█▊        | 1112/6015 [21:32<1:34:53,  1.16s/it]

 19%|█▊        | 1113/6015 [21:33<1:34:56,  1.16s/it]

 19%|█▊        | 1114/6015 [21:34<1:35:00,  1.16s/it]

 19%|█▊        | 1115/6015 [21:35<1:34:58,  1.16s/it]

 19%|█▊        | 1116/6015 [21:37<1:35:00,  1.16s/it]

 19%|█▊        | 1117/6015 [21:38<1:34:58,  1.16s/it]

 19%|█▊        | 1118/6015 [21:39<1:34:59,  1.16s/it]

 19%|█▊        | 1119/6015 [21:40<1:34:59,  1.16s/it]

 19%|█▊        | 1120/6015 [21:41<1:34:52,  1.16s/it]

 19%|█▊        | 1121/6015 [21:42<1:34:45,  1.16s/it]

 19%|█▊        | 1122/6015 [21:44<1:34:40,  1.16s/it]

 19%|█▊        | 1123/6015 [21:45<1:34:41,  1.16s/it]

 19%|█▊        | 1124/6015 [21:46<1:34:41,  1.16s/it]

 19%|█▊        | 1125/6015 [21:47<1:34:43,  1.16s/it]

 19%|█▊        | 1126/6015 [21:48<1:34:41,  1.16s/it]

 19%|█▊        | 1127/6015 [21:49<1:34:40,  1.16s/it]

 19%|█▉        | 1128/6015 [21:50<1:34:41,  1.16s/it]

 19%|█▉        | 1129/6015 [21:52<1:34:44,  1.16s/it]

 19%|█▉        | 1130/6015 [21:53<1:34:47,  1.16s/it]

 19%|█▉        | 1131/6015 [21:54<1:34:48,  1.16s/it]

 19%|█▉        | 1132/6015 [21:55<1:34:46,  1.16s/it]

 19%|█▉        | 1133/6015 [21:56<1:34:40,  1.16s/it]

 19%|█▉        | 1134/6015 [21:57<1:34:39,  1.16s/it]

 19%|█▉        | 1135/6015 [21:59<1:34:39,  1.16s/it]

 19%|█▉        | 1136/6015 [22:00<1:34:36,  1.16s/it]

 19%|█▉        | 1137/6015 [22:01<1:34:30,  1.16s/it]

 19%|█▉        | 1138/6015 [22:02<1:34:34,  1.16s/it]

 19%|█▉        | 1139/6015 [22:03<1:34:31,  1.16s/it]

 19%|█▉        | 1140/6015 [22:04<1:34:23,  1.16s/it]

 19%|█▉        | 1141/6015 [22:06<1:34:15,  1.16s/it]

 19%|█▉        | 1142/6015 [22:07<1:34:13,  1.16s/it]

 19%|█▉        | 1143/6015 [22:08<1:34:14,  1.16s/it]

 19%|█▉        | 1144/6015 [22:09<1:34:19,  1.16s/it]

 19%|█▉        | 1145/6015 [22:10<1:34:23,  1.16s/it]

 19%|█▉        | 1146/6015 [22:11<1:34:16,  1.16s/it]

 19%|█▉        | 1147/6015 [22:13<1:34:11,  1.16s/it]

 19%|█▉        | 1148/6015 [22:14<1:34:13,  1.16s/it]

 19%|█▉        | 1149/6015 [22:15<1:34:10,  1.16s/it]

 19%|█▉        | 1150/6015 [22:16<1:34:06,  1.16s/it]

 19%|█▉        | 1151/6015 [22:17<1:34:01,  1.16s/it]

 19%|█▉        | 1152/6015 [22:18<1:34:01,  1.16s/it]

 19%|█▉        | 1153/6015 [22:20<1:34:02,  1.16s/it]

 19%|█▉        | 1154/6015 [22:21<1:33:56,  1.16s/it]

 19%|█▉        | 1155/6015 [22:22<1:33:56,  1.16s/it]

 19%|█▉        | 1156/6015 [22:23<1:33:58,  1.16s/it]

 19%|█▉        | 1157/6015 [22:24<1:34:04,  1.16s/it]

 19%|█▉        | 1158/6015 [22:25<1:34:03,  1.16s/it]

 19%|█▉        | 1159/6015 [22:27<1:34:06,  1.16s/it]

 19%|█▉        | 1160/6015 [22:28<1:34:02,  1.16s/it]

 19%|█▉        | 1161/6015 [22:29<1:34:00,  1.16s/it]

 19%|█▉        | 1162/6015 [22:30<1:33:57,  1.16s/it]

 19%|█▉        | 1163/6015 [22:31<1:33:56,  1.16s/it]

 19%|█▉        | 1164/6015 [22:32<1:33:54,  1.16s/it]

 19%|█▉        | 1165/6015 [22:33<1:33:55,  1.16s/it]

 19%|█▉        | 1166/6015 [22:35<1:33:52,  1.16s/it]

 19%|█▉        | 1167/6015 [22:36<1:33:46,  1.16s/it]

 19%|█▉        | 1168/6015 [22:37<1:33:48,  1.16s/it]

 19%|█▉        | 1169/6015 [22:38<1:33:48,  1.16s/it]

 19%|█▉        | 1170/6015 [22:39<1:33:54,  1.16s/it]

 19%|█▉        | 1171/6015 [22:40<1:33:56,  1.16s/it]

 19%|█▉        | 1172/6015 [22:42<1:33:54,  1.16s/it]

 20%|█▉        | 1173/6015 [22:43<1:33:52,  1.16s/it]

 20%|█▉        | 1174/6015 [22:44<1:33:40,  1.16s/it]

 20%|█▉        | 1175/6015 [22:45<1:33:39,  1.16s/it]

 20%|█▉        | 1176/6015 [22:46<1:33:33,  1.16s/it]

 20%|█▉        | 1177/6015 [22:47<1:33:30,  1.16s/it]

 20%|█▉        | 1178/6015 [22:49<1:33:26,  1.16s/it]

 20%|█▉        | 1179/6015 [22:50<1:33:33,  1.16s/it]

 20%|█▉        | 1180/6015 [22:51<1:33:36,  1.16s/it]

 20%|█▉        | 1181/6015 [22:52<1:33:37,  1.16s/it]

 20%|█▉        | 1182/6015 [22:53<1:33:35,  1.16s/it]

 20%|█▉        | 1183/6015 [22:54<1:33:31,  1.16s/it]

 20%|█▉        | 1184/6015 [22:56<1:33:33,  1.16s/it]

 20%|█▉        | 1185/6015 [22:57<1:33:29,  1.16s/it]

 20%|█▉        | 1186/6015 [22:58<1:33:24,  1.16s/it]

 20%|█▉        | 1187/6015 [22:59<1:33:22,  1.16s/it]

 20%|█▉        | 1188/6015 [23:00<1:33:22,  1.16s/it]

 20%|█▉        | 1189/6015 [23:01<1:33:32,  1.16s/it]

 20%|█▉        | 1190/6015 [23:03<1:33:30,  1.16s/it]

 20%|█▉        | 1191/6015 [23:04<1:33:29,  1.16s/it]

 20%|█▉        | 1192/6015 [23:05<1:33:24,  1.16s/it]

 20%|█▉        | 1193/6015 [23:06<1:33:15,  1.16s/it]

 20%|█▉        | 1194/6015 [23:07<1:33:13,  1.16s/it]

 20%|█▉        | 1195/6015 [23:08<1:33:12,  1.16s/it]

 20%|█▉        | 1196/6015 [23:09<1:33:14,  1.16s/it]

 20%|█▉        | 1197/6015 [23:11<1:33:16,  1.16s/it]

 20%|█▉        | 1198/6015 [23:12<1:33:12,  1.16s/it]

 20%|█▉        | 1199/6015 [23:13<1:33:12,  1.16s/it]

 20%|█▉        | 1200/6015 [23:14<1:33:13,  1.16s/it]

 20%|█▉        | 1201/6015 [23:15<1:33:08,  1.16s/it]

 20%|█▉        | 1202/6015 [23:16<1:33:09,  1.16s/it]

 20%|██        | 1203/6015 [23:18<1:33:12,  1.16s/it]

 20%|██        | 1204/6015 [23:19<1:33:03,  1.16s/it]

 20%|██        | 1205/6015 [23:20<1:33:03,  1.16s/it]

 20%|██        | 1206/6015 [23:21<1:33:02,  1.16s/it]

 20%|██        | 1207/6015 [23:22<1:33:06,  1.16s/it]

 20%|██        | 1208/6015 [23:23<1:33:09,  1.16s/it]

 20%|██        | 1209/6015 [23:25<1:33:11,  1.16s/it]

 20%|██        | 1210/6015 [23:26<1:33:10,  1.16s/it]

 20%|██        | 1211/6015 [23:27<1:33:12,  1.16s/it]

 20%|██        | 1212/6015 [23:28<1:33:02,  1.16s/it]

 20%|██        | 1213/6015 [23:29<1:33:00,  1.16s/it]

 20%|██        | 1214/6015 [23:30<1:32:59,  1.16s/it]

 20%|██        | 1215/6015 [23:32<1:33:01,  1.16s/it]

 20%|██        | 1216/6015 [23:33<1:32:57,  1.16s/it]

 20%|██        | 1217/6015 [23:34<1:32:52,  1.16s/it]

 20%|██        | 1218/6015 [23:35<1:32:47,  1.16s/it]

 20%|██        | 1219/6015 [23:36<1:32:45,  1.16s/it]

 20%|██        | 1220/6015 [23:37<1:32:53,  1.16s/it]

 20%|██        | 1221/6015 [23:39<1:32:52,  1.16s/it]

 20%|██        | 1222/6015 [23:40<1:32:53,  1.16s/it]

 20%|██        | 1223/6015 [23:41<1:32:56,  1.16s/it]

 20%|██        | 1224/6015 [23:42<1:32:56,  1.16s/it]

 20%|██        | 1225/6015 [23:43<1:32:53,  1.16s/it]

 20%|██        | 1226/6015 [23:44<1:32:56,  1.16s/it]

 20%|██        | 1227/6015 [23:46<1:32:57,  1.16s/it]

 20%|██        | 1228/6015 [23:47<1:32:51,  1.16s/it]

 20%|██        | 1229/6015 [23:48<1:32:49,  1.16s/it]

 20%|██        | 1230/6015 [23:49<1:32:44,  1.16s/it]

 20%|██        | 1231/6015 [23:50<1:32:39,  1.16s/it]

 20%|██        | 1232/6015 [23:51<1:32:41,  1.16s/it]

 20%|██        | 1233/6015 [23:52<1:32:37,  1.16s/it]

 21%|██        | 1234/6015 [23:54<1:32:34,  1.16s/it]

 21%|██        | 1235/6015 [23:55<1:32:37,  1.16s/it]

 21%|██        | 1236/6015 [23:56<1:32:42,  1.16s/it]

 21%|██        | 1237/6015 [23:57<1:32:40,  1.16s/it]

 21%|██        | 1238/6015 [23:58<1:32:37,  1.16s/it]

 21%|██        | 1239/6015 [23:59<1:32:32,  1.16s/it]

 21%|██        | 1240/6015 [24:01<1:32:28,  1.16s/it]

 21%|██        | 1241/6015 [24:02<1:32:20,  1.16s/it]

 21%|██        | 1242/6015 [24:03<1:32:20,  1.16s/it]

 21%|██        | 1243/6015 [24:04<1:32:17,  1.16s/it]

 21%|██        | 1244/6015 [24:05<1:32:20,  1.16s/it]

 21%|██        | 1245/6015 [24:06<1:32:22,  1.16s/it]

 21%|██        | 1246/6015 [24:08<1:32:24,  1.16s/it]

 21%|██        | 1247/6015 [24:09<1:32:23,  1.16s/it]

 21%|██        | 1248/6015 [24:10<1:32:22,  1.16s/it]

 21%|██        | 1249/6015 [24:11<1:32:22,  1.16s/it]

 21%|██        | 1250/6015 [24:12<1:32:21,  1.16s/it]

 21%|██        | 1251/6015 [24:13<1:32:14,  1.16s/it]

logging
logging the anndata

 21%|██        | 1252/6015 [24:15<1:35:39,  1.21s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 21%|██        | 1253/6015 [24:16<1:34:30,  1.19s/it]

 21%|██        | 1254/6015 [24:17<1:33:38,  1.18s/it]

 21%|██        | 1255/6015 [24:18<1:33:02,  1.17s/it]

 21%|██        | 1256/6015 [24:19<1:32:34,  1.17s/it]

 21%|██        | 1257/6015 [24:20<1:32:19,  1.16s/it]

 21%|██        | 1258/6015 [24:22<1:32:04,  1.16s/it]

 21%|██        | 1259/6015 [24:23<1:31:58,  1.16s/it]

 21%|██        | 1260/6015 [24:24<1:31:44,  1.16s/it]

 21%|██        | 1261/6015 [24:25<1:31:41,  1.16s/it]

 21%|██        | 1262/6015 [24:26<1:31:35,  1.16s/it]

 21%|██        | 1263/6015 [24:27<1:31:31,  1.16s/it]

 21%|██        | 1264/6015 [24:29<1:31:34,  1.16s/it]

 21%|██        | 1265/6015 [24:30<1:31:30,  1.16s/it]

 21%|██        | 1266/6015 [24:31<1:31:27,  1.16s/it]

 21%|██        | 1267/6015 [24:32<1:31:21,  1.15s/it]

 21%|██        | 1268/6015 [24:33<1:31:17,  1.15s/it]

 21%|██        | 1269/6015 [24:34<1:31:22,  1.16s/it]

 21%|██        | 1270/6015 [24:36<1:31:26,  1.16s/it]

 21%|██        | 1271/6015 [24:37<1:31:26,  1.16s/it]

 21%|██        | 1272/6015 [24:38<1:31:25,  1.16s/it]

 21%|██        | 1273/6015 [24:39<1:31:23,  1.16s/it]

 21%|██        | 1274/6015 [24:40<1:31:19,  1.16s/it]

 21%|██        | 1275/6015 [24:41<1:31:14,  1.15s/it]

 21%|██        | 1276/6015 [24:42<1:31:13,  1.16s/it]

 21%|██        | 1277/6015 [24:44<1:31:12,  1.16s/it]

 21%|██        | 1278/6015 [24:45<1:31:12,  1.16s/it]

 21%|██▏       | 1279/6015 [24:46<1:31:10,  1.16s/it]

 21%|██▏       | 1280/6015 [24:47<1:31:09,  1.16s/it]

 21%|██▏       | 1281/6015 [24:48<1:31:15,  1.16s/it]

 21%|██▏       | 1282/6015 [24:49<1:31:11,  1.16s/it]

 21%|██▏       | 1283/6015 [24:51<1:31:10,  1.16s/it]

 21%|██▏       | 1284/6015 [24:52<1:31:07,  1.16s/it]

 21%|██▏       | 1285/6015 [24:53<1:31:05,  1.16s/it]

 21%|██▏       | 1286/6015 [24:54<1:31:10,  1.16s/it]

 21%|██▏       | 1287/6015 [24:55<1:31:08,  1.16s/it]

 21%|██▏       | 1288/6015 [24:56<1:31:08,  1.16s/it]

 21%|██▏       | 1289/6015 [24:57<1:31:08,  1.16s/it]

 21%|██▏       | 1290/6015 [24:59<1:31:06,  1.16s/it]

 21%|██▏       | 1291/6015 [25:00<1:31:05,  1.16s/it]

 21%|██▏       | 1292/6015 [25:01<1:31:05,  1.16s/it]

 21%|██▏       | 1293/6015 [25:02<1:30:58,  1.16s/it]

 22%|██▏       | 1294/6015 [25:03<1:30:55,  1.16s/it]

 22%|██▏       | 1295/6015 [25:04<1:30:55,  1.16s/it]

 22%|██▏       | 1296/6015 [25:06<1:30:57,  1.16s/it]

 22%|██▏       | 1297/6015 [25:07<1:30:58,  1.16s/it]

 22%|██▏       | 1298/6015 [25:08<1:30:53,  1.16s/it]

 22%|██▏       | 1299/6015 [25:09<1:30:53,  1.16s/it]

 22%|██▏       | 1300/6015 [25:10<1:30:49,  1.16s/it]

 22%|██▏       | 1301/6015 [25:11<1:30:53,  1.16s/it]

 22%|██▏       | 1302/6015 [25:13<1:30:48,  1.16s/it]

 22%|██▏       | 1303/6015 [25:14<1:30:46,  1.16s/it]

 22%|██▏       | 1304/6015 [25:15<1:30:53,  1.16s/it]

 22%|██▏       | 1305/6015 [25:16<1:30:51,  1.16s/it]

 22%|██▏       | 1306/6015 [25:17<1:30:52,  1.16s/it]

 22%|██▏       | 1307/6015 [25:18<1:30:46,  1.16s/it]

 22%|██▏       | 1308/6015 [25:19<1:30:48,  1.16s/it]

 22%|██▏       | 1309/6015 [25:21<1:30:42,  1.16s/it]

 22%|██▏       | 1310/6015 [25:22<1:30:44,  1.16s/it]

 22%|██▏       | 1311/6015 [25:23<1:30:43,  1.16s/it]

 22%|██▏       | 1312/6015 [25:24<1:30:42,  1.16s/it]

 22%|██▏       | 1313/6015 [25:25<1:30:44,  1.16s/it]

 22%|██▏       | 1314/6015 [25:26<1:30:42,  1.16s/it]

 22%|██▏       | 1315/6015 [25:28<1:30:33,  1.16s/it]

 22%|██▏       | 1316/6015 [25:29<1:30:34,  1.16s/it]

 22%|██▏       | 1317/6015 [25:30<1:30:32,  1.16s/it]

 22%|██▏       | 1318/6015 [25:31<1:30:36,  1.16s/it]

 22%|██▏       | 1319/6015 [25:32<1:30:37,  1.16s/it]

 22%|██▏       | 1320/6015 [25:33<1:30:33,  1.16s/it]

 22%|██▏       | 1321/6015 [25:34<1:30:31,  1.16s/it]

 22%|██▏       | 1322/6015 [25:36<1:30:29,  1.16s/it]

 22%|██▏       | 1323/6015 [25:37<1:30:22,  1.16s/it]

 22%|██▏       | 1324/6015 [25:38<1:30:22,  1.16s/it]

 22%|██▏       | 1325/6015 [25:39<1:30:18,  1.16s/it]

 22%|██▏       | 1326/6015 [25:40<1:30:21,  1.16s/it]

 22%|██▏       | 1327/6015 [25:41<1:30:16,  1.16s/it]

 22%|██▏       | 1328/6015 [25:43<1:30:18,  1.16s/it]

 22%|██▏       | 1329/6015 [25:44<1:30:19,  1.16s/it]

 22%|██▏       | 1330/6015 [25:45<1:30:18,  1.16s/it]

 22%|██▏       | 1331/6015 [25:46<1:30:15,  1.16s/it]

 22%|██▏       | 1332/6015 [25:47<1:30:12,  1.16s/it]

 22%|██▏       | 1333/6015 [25:48<1:30:13,  1.16s/it]

 22%|██▏       | 1334/6015 [25:50<1:30:13,  1.16s/it]

 22%|██▏       | 1335/6015 [25:51<1:30:12,  1.16s/it]

 22%|██▏       | 1336/6015 [25:52<1:30:13,  1.16s/it]

 22%|██▏       | 1337/6015 [25:53<1:30:12,  1.16s/it]

 22%|██▏       | 1338/6015 [25:54<1:30:11,  1.16s/it]

 22%|██▏       | 1339/6015 [25:55<1:30:12,  1.16s/it]

 22%|██▏       | 1340/6015 [25:56<1:30:05,  1.16s/it]

 22%|██▏       | 1341/6015 [25:58<1:30:01,  1.16s/it]

 22%|██▏       | 1342/6015 [25:59<1:29:57,  1.16s/it]

 22%|██▏       | 1343/6015 [26:00<1:30:00,  1.16s/it]

 22%|██▏       | 1344/6015 [26:01<1:29:57,  1.16s/it]

 22%|██▏       | 1345/6015 [26:02<1:30:00,  1.16s/it]

 22%|██▏       | 1346/6015 [26:03<1:30:03,  1.16s/it]

 22%|██▏       | 1347/6015 [26:05<1:30:03,  1.16s/it]

 22%|██▏       | 1348/6015 [26:06<1:30:04,  1.16s/it]

 22%|██▏       | 1349/6015 [26:07<1:30:05,  1.16s/it]

 22%|██▏       | 1350/6015 [26:08<1:29:57,  1.16s/it]

 22%|██▏       | 1351/6015 [26:09<1:29:57,  1.16s/it]

 22%|██▏       | 1352/6015 [26:10<1:29:59,  1.16s/it]

 22%|██▏       | 1353/6015 [26:12<1:29:56,  1.16s/it]

 23%|██▎       | 1354/6015 [26:13<1:29:55,  1.16s/it]

 23%|██▎       | 1355/6015 [26:14<1:29:51,  1.16s/it]

 23%|██▎       | 1356/6015 [26:15<1:29:54,  1.16s/it]

 23%|██▎       | 1357/6015 [26:16<1:29:46,  1.16s/it]

 23%|██▎       | 1358/6015 [26:17<1:29:51,  1.16s/it]

 23%|██▎       | 1359/6015 [26:18<1:29:49,  1.16s/it]

 23%|██▎       | 1360/6015 [26:20<1:29:46,  1.16s/it]

 23%|██▎       | 1361/6015 [26:21<1:29:47,  1.16s/it]

 23%|██▎       | 1362/6015 [26:22<1:29:48,  1.16s/it]

 23%|██▎       | 1363/6015 [26:23<1:29:45,  1.16s/it]

 23%|██▎       | 1364/6015 [26:24<1:29:49,  1.16s/it]

 23%|██▎       | 1365/6015 [26:25<1:29:49,  1.16s/it]

 23%|██▎       | 1366/6015 [26:27<1:29:46,  1.16s/it]

 23%|██▎       | 1367/6015 [26:28<1:29:43,  1.16s/it]

 23%|██▎       | 1368/6015 [26:29<1:29:42,  1.16s/it]

 23%|██▎       | 1369/6015 [26:30<1:29:35,  1.16s/it]

 23%|██▎       | 1370/6015 [26:31<1:29:43,  1.16s/it]

 23%|██▎       | 1371/6015 [26:32<1:29:38,  1.16s/it]

 23%|██▎       | 1372/6015 [26:34<1:29:33,  1.16s/it]

 23%|██▎       | 1373/6015 [26:35<1:29:26,  1.16s/it]

 23%|██▎       | 1374/6015 [26:36<1:29:23,  1.16s/it]

 23%|██▎       | 1375/6015 [26:37<1:29:25,  1.16s/it]

 23%|██▎       | 1376/6015 [26:38<1:29:26,  1.16s/it]

 23%|██▎       | 1377/6015 [26:39<1:29:23,  1.16s/it]

 23%|██▎       | 1378/6015 [26:40<1:29:23,  1.16s/it]

 23%|██▎       | 1379/6015 [26:42<1:29:20,  1.16s/it]

 23%|██▎       | 1380/6015 [26:43<1:29:34,  1.16s/it]

 23%|██▎       | 1381/6015 [26:44<1:29:31,  1.16s/it]

 23%|██▎       | 1382/6015 [26:45<1:29:20,  1.16s/it]

 23%|██▎       | 1383/6015 [26:46<1:29:20,  1.16s/it]

 23%|██▎       | 1384/6015 [26:47<1:29:20,  1.16s/it]

 23%|██▎       | 1385/6015 [26:49<1:29:18,  1.16s/it]

 23%|██▎       | 1386/6015 [26:50<1:29:22,  1.16s/it]

 23%|██▎       | 1387/6015 [26:51<1:29:20,  1.16s/it]

 23%|██▎       | 1388/6015 [26:52<1:29:17,  1.16s/it]

 23%|██▎       | 1389/6015 [26:53<1:29:16,  1.16s/it]

 23%|██▎       | 1390/6015 [26:54<1:29:14,  1.16s/it]

 23%|██▎       | 1391/6015 [26:55<1:29:09,  1.16s/it]

 23%|██▎       | 1392/6015 [26:57<1:29:07,  1.16s/it]

 23%|██▎       | 1393/6015 [26:58<1:29:04,  1.16s/it]

 23%|██▎       | 1394/6015 [26:59<1:29:06,  1.16s/it]

 23%|██▎       | 1395/6015 [27:00<1:29:06,  1.16s/it]

 23%|██▎       | 1396/6015 [27:01<1:29:09,  1.16s/it]

 23%|██▎       | 1397/6015 [27:02<1:29:06,  1.16s/it]

 23%|██▎       | 1398/6015 [27:04<1:29:13,  1.16s/it]

 23%|██▎       | 1399/6015 [27:05<1:29:09,  1.16s/it]

 23%|██▎       | 1400/6015 [27:06<1:29:04,  1.16s/it]

 23%|██▎       | 1401/6015 [27:07<1:28:59,  1.16s/it]

 23%|██▎       | 1402/6015 [27:08<1:28:55,  1.16s/it]

 23%|██▎       | 1403/6015 [27:09<1:28:56,  1.16s/it]

 23%|██▎       | 1404/6015 [27:11<1:28:54,  1.16s/it]

 23%|██▎       | 1405/6015 [27:12<1:28:57,  1.16s/it]

 23%|██▎       | 1406/6015 [27:13<1:29:01,  1.16s/it]

 23%|██▎       | 1407/6015 [27:14<1:29:21,  1.16s/it]

 23%|██▎       | 1408/6015 [27:15<1:29:13,  1.16s/it]

 23%|██▎       | 1409/6015 [27:16<1:29:04,  1.16s/it]

 23%|██▎       | 1410/6015 [27:18<1:28:56,  1.16s/it]

 23%|██▎       | 1411/6015 [27:19<1:28:47,  1.16s/it]

 23%|██▎       | 1412/6015 [27:20<1:28:44,  1.16s/it]

 23%|██▎       | 1413/6015 [27:21<1:28:40,  1.16s/it]

 24%|██▎       | 1414/6015 [27:22<1:28:45,  1.16s/it]

 24%|██▎       | 1415/6015 [27:23<1:28:41,  1.16s/it]

 24%|██▎       | 1416/6015 [27:24<1:28:42,  1.16s/it]

 24%|██▎       | 1417/6015 [27:26<1:28:49,  1.16s/it]

 24%|██▎       | 1418/6015 [27:27<1:28:46,  1.16s/it]

 24%|██▎       | 1419/6015 [27:28<1:28:49,  1.16s/it]

 24%|██▎       | 1420/6015 [27:29<1:28:44,  1.16s/it]

 24%|██▎       | 1421/6015 [27:30<1:28:40,  1.16s/it]

 24%|██▎       | 1422/6015 [27:31<1:28:43,  1.16s/it]

 24%|██▎       | 1423/6015 [27:33<1:28:50,  1.16s/it]

 24%|██▎       | 1424/6015 [27:34<1:28:46,  1.16s/it]

 24%|██▎       | 1425/6015 [27:35<1:28:36,  1.16s/it]

 24%|██▎       | 1426/6015 [27:36<1:28:30,  1.16s/it]

 24%|██▎       | 1427/6015 [27:37<1:28:29,  1.16s/it]

 24%|██▎       | 1428/6015 [27:38<1:28:32,  1.16s/it]

 24%|██▍       | 1429/6015 [27:40<1:28:30,  1.16s/it]

 24%|██▍       | 1430/6015 [27:41<1:28:30,  1.16s/it]

 24%|██▍       | 1431/6015 [27:42<1:28:28,  1.16s/it]

 24%|██▍       | 1432/6015 [27:43<1:28:32,  1.16s/it]

 24%|██▍       | 1433/6015 [27:44<1:28:30,  1.16s/it]

 24%|██▍       | 1434/6015 [27:45<1:28:21,  1.16s/it]

 24%|██▍       | 1435/6015 [27:46<1:28:21,  1.16s/it]

 24%|██▍       | 1436/6015 [27:48<1:28:17,  1.16s/it]

 24%|██▍       | 1437/6015 [27:49<1:28:18,  1.16s/it]

 24%|██▍       | 1438/6015 [27:50<1:28:20,  1.16s/it]

 24%|██▍       | 1439/6015 [27:51<1:28:22,  1.16s/it]

 24%|██▍       | 1440/6015 [27:52<1:28:17,  1.16s/it]

 24%|██▍       | 1441/6015 [27:53<1:28:16,  1.16s/it]

 24%|██▍       | 1442/6015 [27:55<1:28:12,  1.16s/it]

 24%|██▍       | 1443/6015 [27:56<1:28:12,  1.16s/it]

 24%|██▍       | 1444/6015 [27:57<1:28:10,  1.16s/it]

 24%|██▍       | 1445/6015 [27:58<1:28:09,  1.16s/it]

 24%|██▍       | 1446/6015 [27:59<1:28:09,  1.16s/it]

 24%|██▍       | 1447/6015 [28:00<1:28:10,  1.16s/it]

 24%|██▍       | 1448/6015 [28:02<1:28:13,  1.16s/it]

 24%|██▍       | 1449/6015 [28:03<1:28:10,  1.16s/it]

 24%|██▍       | 1450/6015 [28:04<1:28:07,  1.16s/it]

 24%|██▍       | 1451/6015 [28:05<1:28:09,  1.16s/it]

 24%|██▍       | 1452/6015 [28:06<1:28:02,  1.16s/it]

 24%|██▍       | 1453/6015 [28:07<1:27:59,  1.16s/it]

 24%|██▍       | 1454/6015 [28:08<1:27:55,  1.16s/it]

 24%|██▍       | 1455/6015 [28:10<1:27:54,  1.16s/it]

 24%|██▍       | 1456/6015 [28:11<1:28:00,  1.16s/it]

 24%|██▍       | 1457/6015 [28:12<1:27:59,  1.16s/it]

 24%|██▍       | 1458/6015 [28:13<1:27:56,  1.16s/it]

 24%|██▍       | 1459/6015 [28:14<1:27:55,  1.16s/it]

 24%|██▍       | 1460/6015 [28:15<1:28:01,  1.16s/it]

 24%|██▍       | 1461/6015 [28:17<1:27:59,  1.16s/it]

 24%|██▍       | 1462/6015 [28:18<1:27:59,  1.16s/it]

 24%|██▍       | 1463/6015 [28:19<1:27:53,  1.16s/it]

 24%|██▍       | 1464/6015 [28:20<1:27:49,  1.16s/it]

 24%|██▍       | 1465/6015 [28:21<1:27:44,  1.16s/it]

 24%|██▍       | 1466/6015 [28:22<1:27:43,  1.16s/it]

 24%|██▍       | 1467/6015 [28:24<1:27:44,  1.16s/it]

 24%|██▍       | 1468/6015 [28:25<1:27:43,  1.16s/it]

 24%|██▍       | 1469/6015 [28:26<1:27:43,  1.16s/it]

 24%|██▍       | 1470/6015 [28:27<1:27:47,  1.16s/it]

 24%|██▍       | 1471/6015 [28:28<1:27:37,  1.16s/it]

 24%|██▍       | 1472/6015 [28:29<1:27:43,  1.16s/it]

 24%|██▍       | 1473/6015 [28:30<1:27:39,  1.16s/it]

 25%|██▍       | 1474/6015 [28:32<1:27:31,  1.16s/it]

 25%|██▍       | 1475/6015 [28:33<1:27:32,  1.16s/it]

 25%|██▍       | 1476/6015 [28:34<1:27:37,  1.16s/it]

 25%|██▍       | 1477/6015 [28:35<1:27:44,  1.16s/it]

 25%|██▍       | 1478/6015 [28:36<1:27:46,  1.16s/it]

 25%|██▍       | 1479/6015 [28:37<1:27:42,  1.16s/it]

 25%|██▍       | 1480/6015 [28:39<1:27:38,  1.16s/it]

 25%|██▍       | 1481/6015 [28:40<1:27:34,  1.16s/it]

 25%|██▍       | 1482/6015 [28:41<1:27:31,  1.16s/it]

 25%|██▍       | 1483/6015 [28:42<1:27:27,  1.16s/it]

 25%|██▍       | 1484/6015 [28:43<1:27:38,  1.16s/it]

 25%|██▍       | 1485/6015 [28:44<1:27:33,  1.16s/it]

 25%|██▍       | 1486/6015 [28:46<1:27:26,  1.16s/it]

 25%|██▍       | 1487/6015 [28:47<1:27:24,  1.16s/it]

 25%|██▍       | 1488/6015 [28:48<1:27:20,  1.16s/it]

 25%|██▍       | 1489/6015 [28:49<1:27:20,  1.16s/it]

 25%|██▍       | 1490/6015 [28:50<1:27:21,  1.16s/it]

 25%|██▍       | 1491/6015 [28:51<1:27:17,  1.16s/it]

 25%|██▍       | 1492/6015 [28:52<1:27:14,  1.16s/it]

 25%|██▍       | 1493/6015 [28:54<1:27:17,  1.16s/it]

 25%|██▍       | 1494/6015 [28:55<1:27:27,  1.16s/it]

 25%|██▍       | 1495/6015 [28:56<1:27:20,  1.16s/it]

 25%|██▍       | 1496/6015 [28:57<1:27:18,  1.16s/it]

 25%|██▍       | 1497/6015 [28:58<1:27:12,  1.16s/it]

 25%|██▍       | 1498/6015 [28:59<1:27:09,  1.16s/it]

 25%|██▍       | 1499/6015 [29:01<1:27:05,  1.16s/it]

 25%|██▍       | 1500/6015 [29:02<1:27:07,  1.16s/it]

 25%|██▍       | 1501/6015 [29:03<1:27:06,  1.16s/it]

 25%|██▍       | 1502/6015 [29:04<1:27:08,  1.16s/it]

 25%|██▍       | 1503/6015 [29:05<1:27:09,  1.16s/it]

 25%|██▌       | 1504/6015 [29:06<1:27:12,  1.16s/it]

 25%|██▌       | 1505/6015 [29:08<1:27:12,  1.16s/it]

 25%|██▌       | 1506/6015 [29:09<1:27:09,  1.16s/it]

 25%|██▌       | 1507/6015 [29:10<1:27:05,  1.16s/it]

 25%|██▌       | 1508/6015 [29:11<1:26:52,  1.16s/it]

 25%|██▌       | 1509/6015 [29:12<1:26:52,  1.16s/it]

 25%|██▌       | 1510/6015 [29:13<1:26:56,  1.16s/it]

 25%|██▌       | 1511/6015 [29:14<1:26:54,  1.16s/it]

 25%|██▌       | 1512/6015 [29:16<1:26:52,  1.16s/it]

 25%|██▌       | 1513/6015 [29:17<1:26:55,  1.16s/it]

 25%|██▌       | 1514/6015 [29:18<1:26:59,  1.16s/it]

 25%|██▌       | 1515/6015 [29:19<1:26:58,  1.16s/it]

 25%|██▌       | 1516/6015 [29:20<1:26:53,  1.16s/it]

 25%|██▌       | 1517/6015 [29:21<1:26:52,  1.16s/it]

 25%|██▌       | 1518/6015 [29:23<1:26:49,  1.16s/it]

 25%|██▌       | 1519/6015 [29:24<1:26:48,  1.16s/it]

 25%|██▌       | 1520/6015 [29:25<1:26:51,  1.16s/it]

 25%|██▌       | 1521/6015 [29:26<1:26:50,  1.16s/it]

 25%|██▌       | 1522/6015 [29:27<1:26:50,  1.16s/it]

 25%|██▌       | 1523/6015 [29:28<1:26:43,  1.16s/it]

 25%|██▌       | 1524/6015 [29:30<1:26:49,  1.16s/it]

 25%|██▌       | 1525/6015 [29:31<1:26:47,  1.16s/it]

 25%|██▌       | 1526/6015 [29:32<1:26:48,  1.16s/it]

 25%|██▌       | 1527/6015 [29:33<1:26:45,  1.16s/it]

 25%|██▌       | 1528/6015 [29:34<1:26:37,  1.16s/it]

 25%|██▌       | 1529/6015 [29:35<1:26:33,  1.16s/it]

 25%|██▌       | 1530/6015 [29:37<1:26:35,  1.16s/it]

 25%|██▌       | 1531/6015 [29:38<1:26:40,  1.16s/it]

 25%|██▌       | 1532/6015 [29:39<1:26:39,  1.16s/it]

 25%|██▌       | 1533/6015 [29:40<1:26:41,  1.16s/it]

 26%|██▌       | 1534/6015 [29:41<1:26:43,  1.16s/it]

 26%|██▌       | 1535/6015 [29:42<1:26:43,  1.16s/it]

 26%|██▌       | 1536/6015 [29:43<1:26:38,  1.16s/it]

 26%|██▌       | 1537/6015 [29:45<1:26:37,  1.16s/it]

 26%|██▌       | 1538/6015 [29:46<1:26:35,  1.16s/it]

 26%|██▌       | 1539/6015 [29:47<1:26:39,  1.16s/it]

 26%|██▌       | 1540/6015 [29:48<1:26:34,  1.16s/it]

 26%|██▌       | 1541/6015 [29:49<1:26:30,  1.16s/it]

 26%|██▌       | 1542/6015 [29:50<1:26:20,  1.16s/it]

 26%|██▌       | 1543/6015 [29:52<1:26:15,  1.16s/it]

 26%|██▌       | 1544/6015 [29:53<1:26:19,  1.16s/it]

 26%|██▌       | 1545/6015 [29:54<1:26:22,  1.16s/it]

 26%|██▌       | 1546/6015 [29:55<1:26:21,  1.16s/it]

 26%|██▌       | 1547/6015 [29:56<1:26:18,  1.16s/it]

 26%|██▌       | 1548/6015 [29:57<1:26:15,  1.16s/it]

 26%|██▌       | 1549/6015 [29:59<1:26:17,  1.16s/it]

 26%|██▌       | 1550/6015 [30:00<1:26:12,  1.16s/it]

 26%|██▌       | 1551/6015 [30:01<1:26:10,  1.16s/it]

 26%|██▌       | 1552/6015 [30:02<1:26:08,  1.16s/it]

 26%|██▌       | 1553/6015 [30:03<1:26:07,  1.16s/it]

 26%|██▌       | 1554/6015 [30:04<1:26:04,  1.16s/it]

 26%|██▌       | 1555/6015 [30:05<1:26:08,  1.16s/it]

 26%|██▌       | 1556/6015 [30:07<1:26:12,  1.16s/it]

 26%|██▌       | 1557/6015 [30:08<1:26:10,  1.16s/it]

 26%|██▌       | 1558/6015 [30:09<1:26:05,  1.16s/it]

 26%|██▌       | 1559/6015 [30:10<1:26:09,  1.16s/it]

 26%|██▌       | 1560/6015 [30:11<1:26:07,  1.16s/it]

 26%|██▌       | 1561/6015 [30:12<1:26:07,  1.16s/it]

 26%|██▌       | 1562/6015 [30:14<1:26:00,  1.16s/it]

 26%|██▌       | 1563/6015 [30:15<1:26:01,  1.16s/it]

 26%|██▌       | 1564/6015 [30:16<1:26:02,  1.16s/it]

 26%|██▌       | 1565/6015 [30:17<1:26:01,  1.16s/it]

 26%|██▌       | 1566/6015 [30:18<1:25:59,  1.16s/it]

 26%|██▌       | 1567/6015 [30:19<1:26:03,  1.16s/it]

 26%|██▌       | 1568/6015 [30:21<1:26:01,  1.16s/it]

 26%|██▌       | 1569/6015 [30:22<1:25:59,  1.16s/it]

 26%|██▌       | 1570/6015 [30:23<1:26:00,  1.16s/it]

 26%|██▌       | 1571/6015 [30:24<1:25:55,  1.16s/it]

 26%|██▌       | 1572/6015 [30:25<1:25:54,  1.16s/it]

 26%|██▌       | 1573/6015 [30:26<1:25:53,  1.16s/it]

 26%|██▌       | 1574/6015 [30:28<1:25:51,  1.16s/it]

 26%|██▌       | 1575/6015 [30:29<1:25:43,  1.16s/it]

 26%|██▌       | 1576/6015 [30:30<1:25:40,  1.16s/it]

 26%|██▌       | 1577/6015 [30:31<1:25:44,  1.16s/it]

 26%|██▌       | 1578/6015 [30:32<1:25:45,  1.16s/it]

 26%|██▋       | 1579/6015 [30:33<1:25:42,  1.16s/it]

 26%|██▋       | 1580/6015 [30:34<1:25:39,  1.16s/it]

 26%|██▋       | 1581/6015 [30:36<1:25:41,  1.16s/it]

 26%|██▋       | 1582/6015 [30:37<1:25:43,  1.16s/it]

 26%|██▋       | 1583/6015 [30:38<1:25:37,  1.16s/it]

 26%|██▋       | 1584/6015 [30:39<1:25:35,  1.16s/it]

 26%|██▋       | 1585/6015 [30:40<1:25:31,  1.16s/it]

 26%|██▋       | 1586/6015 [30:41<1:25:27,  1.16s/it]

 26%|██▋       | 1587/6015 [30:43<1:25:34,  1.16s/it]

 26%|██▋       | 1588/6015 [30:44<1:25:33,  1.16s/it]

 26%|██▋       | 1589/6015 [30:45<1:25:35,  1.16s/it]

 26%|██▋       | 1590/6015 [30:46<1:25:34,  1.16s/it]

 26%|██▋       | 1591/6015 [30:47<1:25:40,  1.16s/it]

 26%|██▋       | 1592/6015 [30:48<1:25:37,  1.16s/it]

 26%|██▋       | 1593/6015 [30:50<1:25:39,  1.16s/it]

 27%|██▋       | 1594/6015 [30:51<1:25:31,  1.16s/it]

 27%|██▋       | 1595/6015 [30:52<1:25:33,  1.16s/it]

 27%|██▋       | 1596/6015 [30:53<1:25:40,  1.16s/it]

 27%|██▋       | 1597/6015 [30:54<1:25:36,  1.16s/it]

 27%|██▋       | 1598/6015 [30:55<1:25:36,  1.16s/it]

 27%|██▋       | 1599/6015 [30:57<1:25:31,  1.16s/it]

 27%|██▋       | 1600/6015 [30:58<1:25:23,  1.16s/it]

 27%|██▋       | 1601/6015 [30:59<1:25:22,  1.16s/it]

 27%|██▋       | 1602/6015 [31:00<1:25:15,  1.16s/it]

 27%|██▋       | 1603/6015 [31:01<1:25:18,  1.16s/it]

 27%|██▋       | 1604/6015 [31:02<1:25:22,  1.16s/it]

 27%|██▋       | 1605/6015 [31:04<1:25:19,  1.16s/it]

 27%|██▋       | 1606/6015 [31:05<1:25:17,  1.16s/it]

 27%|██▋       | 1607/6015 [31:06<1:25:14,  1.16s/it]

 27%|██▋       | 1608/6015 [31:07<1:25:17,  1.16s/it]

 27%|██▋       | 1609/6015 [31:08<1:25:12,  1.16s/it]

 27%|██▋       | 1610/6015 [31:09<1:25:17,  1.16s/it]

 27%|██▋       | 1611/6015 [31:10<1:25:11,  1.16s/it]

 27%|██▋       | 1612/6015 [31:12<1:25:05,  1.16s/it]

 27%|██▋       | 1613/6015 [31:13<1:25:04,  1.16s/it]

 27%|██▋       | 1614/6015 [31:14<1:25:01,  1.16s/it]

 27%|██▋       | 1615/6015 [31:15<1:25:00,  1.16s/it]

 27%|██▋       | 1616/6015 [31:16<1:25:01,  1.16s/it]

 27%|██▋       | 1617/6015 [31:17<1:25:06,  1.16s/it]

 27%|██▋       | 1618/6015 [31:19<1:25:06,  1.16s/it]

 27%|██▋       | 1619/6015 [31:20<1:25:05,  1.16s/it]

 27%|██▋       | 1620/6015 [31:21<1:25:05,  1.16s/it]

 27%|██▋       | 1621/6015 [31:22<1:24:58,  1.16s/it]

 27%|██▋       | 1622/6015 [31:23<1:24:54,  1.16s/it]

 27%|██▋       | 1623/6015 [31:24<1:24:50,  1.16s/it]

 27%|██▋       | 1624/6015 [31:26<1:24:50,  1.16s/it]

 27%|██▋       | 1625/6015 [31:27<1:24:45,  1.16s/it]

 27%|██▋       | 1626/6015 [31:28<1:24:51,  1.16s/it]

 27%|██▋       | 1627/6015 [31:29<1:24:55,  1.16s/it]

 27%|██▋       | 1628/6015 [31:30<1:24:54,  1.16s/it]

 27%|██▋       | 1629/6015 [31:31<1:24:54,  1.16s/it]

 27%|██▋       | 1630/6015 [31:33<1:24:48,  1.16s/it]

 27%|██▋       | 1631/6015 [31:34<1:24:46,  1.16s/it]

 27%|██▋       | 1632/6015 [31:35<1:24:46,  1.16s/it]

 27%|██▋       | 1633/6015 [31:36<1:24:52,  1.16s/it]

 27%|██▋       | 1634/6015 [31:37<1:24:50,  1.16s/it]

 27%|██▋       | 1635/6015 [31:38<1:24:47,  1.16s/it]

 27%|██▋       | 1636/6015 [31:39<1:24:41,  1.16s/it]

 27%|██▋       | 1637/6015 [31:41<1:24:39,  1.16s/it]

 27%|██▋       | 1638/6015 [31:42<1:24:37,  1.16s/it]

 27%|██▋       | 1639/6015 [31:43<1:24:43,  1.16s/it]

 27%|██▋       | 1640/6015 [31:44<1:24:41,  1.16s/it]

 27%|██▋       | 1641/6015 [31:45<1:24:35,  1.16s/it]

 27%|██▋       | 1642/6015 [31:46<1:24:35,  1.16s/it]

 27%|██▋       | 1643/6015 [31:48<1:24:36,  1.16s/it]

 27%|██▋       | 1644/6015 [31:49<1:24:27,  1.16s/it]

 27%|██▋       | 1645/6015 [31:50<1:24:27,  1.16s/it]

 27%|██▋       | 1646/6015 [31:51<1:24:21,  1.16s/it]

 27%|██▋       | 1647/6015 [31:52<1:24:19,  1.16s/it]

 27%|██▋       | 1648/6015 [31:53<1:24:21,  1.16s/it]

 27%|██▋       | 1649/6015 [31:55<1:24:20,  1.16s/it]

 27%|██▋       | 1650/6015 [31:56<1:24:22,  1.16s/it]

 27%|██▋       | 1651/6015 [31:57<1:24:24,  1.16s/it]

 27%|██▋       | 1652/6015 [31:58<1:24:23,  1.16s/it]

 27%|██▋       | 1653/6015 [31:59<1:24:26,  1.16s/it]

 27%|██▋       | 1654/6015 [32:00<1:24:24,  1.16s/it]

 28%|██▊       | 1655/6015 [32:02<1:24:28,  1.16s/it]

 28%|██▊       | 1656/6015 [32:03<1:24:31,  1.16s/it]

 28%|██▊       | 1657/6015 [32:04<1:24:26,  1.16s/it]

 28%|██▊       | 1658/6015 [32:05<1:24:25,  1.16s/it]

 28%|██▊       | 1659/6015 [32:06<1:24:20,  1.16s/it]

 28%|██▊       | 1660/6015 [32:07<1:24:17,  1.16s/it]

 28%|██▊       | 1661/6015 [32:08<1:24:13,  1.16s/it]

 28%|██▊       | 1662/6015 [32:10<1:24:06,  1.16s/it]

 28%|██▊       | 1663/6015 [32:11<1:24:06,  1.16s/it]

 28%|██▊       | 1664/6015 [32:12<1:24:08,  1.16s/it]

 28%|██▊       | 1665/6015 [32:13<1:24:12,  1.16s/it]

 28%|██▊       | 1666/6015 [32:14<1:24:13,  1.16s/it]

 28%|██▊       | 1667/6015 [32:15<1:24:08,  1.16s/it]

 28%|██▊       | 1668/6015 [32:17<1:24:04,  1.16s/it]

 28%|██▊       | 1669/6015 [32:18<1:24:05,  1.16s/it]

 28%|██▊       | 1670/6015 [32:19<1:24:03,  1.16s/it]

 28%|██▊       | 1671/6015 [32:20<1:24:03,  1.16s/it]

 28%|██▊       | 1672/6015 [32:21<1:23:59,  1.16s/it]

 28%|██▊       | 1673/6015 [32:22<1:24:01,  1.16s/it]

 28%|██▊       | 1674/6015 [32:24<1:23:59,  1.16s/it]

 28%|██▊       | 1675/6015 [32:25<1:23:54,  1.16s/it]

 28%|██▊       | 1676/6015 [32:26<1:23:53,  1.16s/it]

 28%|██▊       | 1677/6015 [32:27<1:24:02,  1.16s/it]

 28%|██▊       | 1678/6015 [32:28<1:24:03,  1.16s/it]

 28%|██▊       | 1679/6015 [32:29<1:24:01,  1.16s/it]

 28%|██▊       | 1680/6015 [32:31<1:23:58,  1.16s/it]

 28%|██▊       | 1681/6015 [32:32<1:23:57,  1.16s/it]

 28%|██▊       | 1682/6015 [32:33<1:24:00,  1.16s/it]

 28%|██▊       | 1683/6015 [32:34<1:23:56,  1.16s/it]

 28%|██▊       | 1684/6015 [32:35<1:23:49,  1.16s/it]

 28%|██▊       | 1685/6015 [32:36<1:23:43,  1.16s/it]

 28%|██▊       | 1686/6015 [32:38<1:23:43,  1.16s/it]

 28%|██▊       | 1687/6015 [32:39<1:23:37,  1.16s/it]

 28%|██▊       | 1688/6015 [32:40<1:23:39,  1.16s/it]

 28%|██▊       | 1689/6015 [32:41<1:23:40,  1.16s/it]

 28%|██▊       | 1690/6015 [32:42<1:23:40,  1.16s/it]

 28%|██▊       | 1691/6015 [32:43<1:23:43,  1.16s/it]

 28%|██▊       | 1692/6015 [32:44<1:23:38,  1.16s/it]

 28%|██▊       | 1693/6015 [32:46<1:23:37,  1.16s/it]

 28%|██▊       | 1694/6015 [32:47<1:23:38,  1.16s/it]

 28%|██▊       | 1695/6015 [32:48<1:23:44,  1.16s/it]

 28%|██▊       | 1696/6015 [32:49<1:23:38,  1.16s/it]

 28%|██▊       | 1697/6015 [32:50<1:23:36,  1.16s/it]

 28%|██▊       | 1698/6015 [32:51<1:23:33,  1.16s/it]

 28%|██▊       | 1699/6015 [32:53<1:23:27,  1.16s/it]

 28%|██▊       | 1700/6015 [32:54<1:23:29,  1.16s/it]

 28%|██▊       | 1701/6015 [32:55<1:23:30,  1.16s/it]

 28%|██▊       | 1702/6015 [32:56<1:23:29,  1.16s/it]

 28%|██▊       | 1703/6015 [32:57<1:23:32,  1.16s/it]

 28%|██▊       | 1704/6015 [32:58<1:23:31,  1.16s/it]

 28%|██▊       | 1705/6015 [33:00<1:23:30,  1.16s/it]

 28%|██▊       | 1706/6015 [33:01<1:23:34,  1.16s/it]

 28%|██▊       | 1707/6015 [33:02<1:23:30,  1.16s/it]

 28%|██▊       | 1708/6015 [33:03<1:23:27,  1.16s/it]

 28%|██▊       | 1709/6015 [33:04<1:23:22,  1.16s/it]

 28%|██▊       | 1710/6015 [33:05<1:23:24,  1.16s/it]

 28%|██▊       | 1711/6015 [33:07<1:23:23,  1.16s/it]

 28%|██▊       | 1712/6015 [33:08<1:23:24,  1.16s/it]

 28%|██▊       | 1713/6015 [33:09<1:23:25,  1.16s/it]

 28%|██▊       | 1714/6015 [33:10<1:23:22,  1.16s/it]

 29%|██▊       | 1715/6015 [33:11<1:23:12,  1.16s/it]

 29%|██▊       | 1716/6015 [33:12<1:23:08,  1.16s/it]

 29%|██▊       | 1717/6015 [33:14<1:23:04,  1.16s/it]

 29%|██▊       | 1718/6015 [33:15<1:23:09,  1.16s/it]

 29%|██▊       | 1719/6015 [33:16<1:23:04,  1.16s/it]

 29%|██▊       | 1720/6015 [33:17<1:23:06,  1.16s/it]

 29%|██▊       | 1721/6015 [33:18<1:23:04,  1.16s/it]

 29%|██▊       | 1722/6015 [33:19<1:23:07,  1.16s/it]

 29%|██▊       | 1723/6015 [33:21<1:23:09,  1.16s/it]

 29%|██▊       | 1724/6015 [33:22<1:23:08,  1.16s/it]

 29%|██▊       | 1725/6015 [33:23<1:23:14,  1.16s/it]

 29%|██▊       | 1726/6015 [33:24<1:23:11,  1.16s/it]

 29%|██▊       | 1727/6015 [33:25<1:23:01,  1.16s/it]

 29%|██▊       | 1728/6015 [33:26<1:23:01,  1.16s/it]

 29%|██▊       | 1729/6015 [33:27<1:22:57,  1.16s/it]

 29%|██▉       | 1730/6015 [33:29<1:23:03,  1.16s/it]

 29%|██▉       | 1731/6015 [33:30<1:23:03,  1.16s/it]

 29%|██▉       | 1732/6015 [33:31<1:22:59,  1.16s/it]

 29%|██▉       | 1733/6015 [33:32<1:22:57,  1.16s/it]

 29%|██▉       | 1734/6015 [33:33<1:22:53,  1.16s/it]

 29%|██▉       | 1735/6015 [33:34<1:22:53,  1.16s/it]

 29%|██▉       | 1736/6015 [33:36<1:22:50,  1.16s/it]

 29%|██▉       | 1737/6015 [33:37<1:22:47,  1.16s/it]

 29%|██▉       | 1738/6015 [33:38<1:22:42,  1.16s/it]

 29%|██▉       | 1739/6015 [33:39<1:22:40,  1.16s/it]

 29%|██▉       | 1740/6015 [33:40<1:22:42,  1.16s/it]

 29%|██▉       | 1741/6015 [33:41<1:22:42,  1.16s/it]

 29%|██▉       | 1742/6015 [33:43<1:22:41,  1.16s/it]

 29%|██▉       | 1743/6015 [33:44<1:22:44,  1.16s/it]

 29%|██▉       | 1744/6015 [33:45<1:22:40,  1.16s/it]

 29%|██▉       | 1745/6015 [33:46<1:22:38,  1.16s/it]

 29%|██▉       | 1746/6015 [33:47<1:22:36,  1.16s/it]

 29%|██▉       | 1747/6015 [33:48<1:22:34,  1.16s/it]

 29%|██▉       | 1748/6015 [33:50<1:22:33,  1.16s/it]

 29%|██▉       | 1749/6015 [33:51<1:22:29,  1.16s/it]

 29%|██▉       | 1750/6015 [33:52<1:22:31,  1.16s/it]

 29%|██▉       | 1751/6015 [33:53<1:22:28,  1.16s/it]

 29%|██▉       | 1752/6015 [33:54<1:22:28,  1.16s/it]

 29%|██▉       | 1753/6015 [33:55<1:22:25,  1.16s/it]

 29%|██▉       | 1754/6015 [33:57<1:22:25,  1.16s/it]

 29%|██▉       | 1755/6015 [33:58<1:22:26,  1.16s/it]

 29%|██▉       | 1756/6015 [33:59<1:22:31,  1.16s/it]

 29%|██▉       | 1757/6015 [34:00<1:22:32,  1.16s/it]

 29%|██▉       | 1758/6015 [34:01<1:22:29,  1.16s/it]

 29%|██▉       | 1759/6015 [34:02<1:22:38,  1.16s/it]

 29%|██▉       | 1760/6015 [34:04<1:22:34,  1.16s/it]

 29%|██▉       | 1761/6015 [34:05<1:22:32,  1.16s/it]

 29%|██▉       | 1762/6015 [34:06<1:22:27,  1.16s/it]

 29%|██▉       | 1763/6015 [34:07<1:22:22,  1.16s/it]

 29%|██▉       | 1764/6015 [34:08<1:22:18,  1.16s/it]

 29%|██▉       | 1765/6015 [34:09<1:22:17,  1.16s/it]

 29%|██▉       | 1766/6015 [34:10<1:22:20,  1.16s/it]

 29%|██▉       | 1767/6015 [34:12<1:22:21,  1.16s/it]

 29%|██▉       | 1768/6015 [34:13<1:22:24,  1.16s/it]

 29%|██▉       | 1769/6015 [34:14<1:22:24,  1.16s/it]

 29%|██▉       | 1770/6015 [34:15<1:22:22,  1.16s/it]

 29%|██▉       | 1771/6015 [34:16<1:22:20,  1.16s/it]

 29%|██▉       | 1772/6015 [34:17<1:22:10,  1.16s/it]

 29%|██▉       | 1773/6015 [34:19<1:22:05,  1.16s/it]

 29%|██▉       | 1774/6015 [34:20<1:22:11,  1.16s/it]

 30%|██▉       | 1775/6015 [34:21<1:22:07,  1.16s/it]

 30%|██▉       | 1776/6015 [34:22<1:22:06,  1.16s/it]

 30%|██▉       | 1777/6015 [34:23<1:22:03,  1.16s/it]

 30%|██▉       | 1778/6015 [34:24<1:22:03,  1.16s/it]

 30%|██▉       | 1779/6015 [34:26<1:22:06,  1.16s/it]

 30%|██▉       | 1780/6015 [34:27<1:21:59,  1.16s/it]

 30%|██▉       | 1781/6015 [34:28<1:21:53,  1.16s/it]

 30%|██▉       | 1782/6015 [34:29<1:21:55,  1.16s/it]

 30%|██▉       | 1783/6015 [34:30<1:21:55,  1.16s/it]

 30%|██▉       | 1784/6015 [34:31<1:21:53,  1.16s/it]

 30%|██▉       | 1785/6015 [34:33<1:21:51,  1.16s/it]

 30%|██▉       | 1786/6015 [34:34<1:21:50,  1.16s/it]

 30%|██▉       | 1787/6015 [34:35<1:21:50,  1.16s/it]

 30%|██▉       | 1788/6015 [34:36<1:21:50,  1.16s/it]

 30%|██▉       | 1789/6015 [34:37<1:21:51,  1.16s/it]

 30%|██▉       | 1790/6015 [34:38<1:21:54,  1.16s/it]

 30%|██▉       | 1791/6015 [34:40<1:21:55,  1.16s/it]

 30%|██▉       | 1792/6015 [34:41<1:21:51,  1.16s/it]

 30%|██▉       | 1793/6015 [34:42<1:21:44,  1.16s/it]

 30%|██▉       | 1794/6015 [34:43<1:21:38,  1.16s/it]

 30%|██▉       | 1795/6015 [34:44<1:21:39,  1.16s/it]

 30%|██▉       | 1796/6015 [34:45<1:21:39,  1.16s/it]

 30%|██▉       | 1797/6015 [34:46<1:21:35,  1.16s/it]

 30%|██▉       | 1798/6015 [34:48<1:21:33,  1.16s/it]

 30%|██▉       | 1799/6015 [34:49<1:21:34,  1.16s/it]

 30%|██▉       | 1800/6015 [34:50<1:21:35,  1.16s/it]

 30%|██▉       | 1801/6015 [34:51<1:21:34,  1.16s/it]

 30%|██▉       | 1802/6015 [34:52<1:21:34,  1.16s/it]

 30%|██▉       | 1803/6015 [34:53<1:21:37,  1.16s/it]

 30%|██▉       | 1804/6015 [34:55<1:21:31,  1.16s/it]

 30%|███       | 1805/6015 [34:56<1:21:32,  1.16s/it]

 30%|███       | 1806/6015 [34:57<1:21:30,  1.16s/it]

 30%|███       | 1807/6015 [34:58<1:21:25,  1.16s/it]

 30%|███       | 1808/6015 [34:59<1:21:22,  1.16s/it]

 30%|███       | 1809/6015 [35:00<1:21:24,  1.16s/it]

 30%|███       | 1810/6015 [35:02<1:21:20,  1.16s/it]

 30%|███       | 1811/6015 [35:03<1:21:21,  1.16s/it]

 30%|███       | 1812/6015 [35:04<1:21:27,  1.16s/it]

 30%|███       | 1813/6015 [35:05<1:21:26,  1.16s/it]

 30%|███       | 1814/6015 [35:06<1:21:25,  1.16s/it]

 30%|███       | 1815/6015 [35:07<1:21:25,  1.16s/it]

 30%|███       | 1816/6015 [35:09<1:21:22,  1.16s/it]

 30%|███       | 1817/6015 [35:10<1:21:18,  1.16s/it]

 30%|███       | 1818/6015 [35:11<1:21:13,  1.16s/it]

 30%|███       | 1819/6015 [35:12<1:21:10,  1.16s/it]

 30%|███       | 1820/6015 [35:13<1:21:06,  1.16s/it]

 30%|███       | 1821/6015 [35:14<1:21:13,  1.16s/it]

 30%|███       | 1822/6015 [35:16<1:21:06,  1.16s/it]

 30%|███       | 1823/6015 [35:17<1:21:09,  1.16s/it]

 30%|███       | 1824/6015 [35:18<1:21:38,  1.17s/it]

 30%|███       | 1825/6015 [35:19<1:22:04,  1.18s/it]

 30%|███       | 1826/6015 [35:20<1:21:48,  1.17s/it]

 30%|███       | 1827/6015 [35:21<1:21:37,  1.17s/it]

 30%|███       | 1828/6015 [35:23<1:21:34,  1.17s/it]

 30%|███       | 1829/6015 [35:24<1:21:34,  1.17s/it]

 30%|███       | 1830/6015 [35:25<1:21:23,  1.17s/it]

 30%|███       | 1831/6015 [35:26<1:21:13,  1.16s/it]

 30%|███       | 1832/6015 [35:27<1:21:04,  1.16s/it]

 30%|███       | 1833/6015 [35:28<1:21:01,  1.16s/it]

 30%|███       | 1834/6015 [35:30<1:21:02,  1.16s/it]

 31%|███       | 1835/6015 [35:31<1:21:00,  1.16s/it]

 31%|███       | 1836/6015 [35:32<1:21:02,  1.16s/it]

 31%|███       | 1837/6015 [35:33<1:20:57,  1.16s/it]

 31%|███       | 1838/6015 [35:34<1:20:50,  1.16s/it]

 31%|███       | 1839/6015 [35:35<1:20:47,  1.16s/it]

 31%|███       | 1840/6015 [35:37<1:20:49,  1.16s/it]

 31%|███       | 1841/6015 [35:38<1:20:48,  1.16s/it]

 31%|███       | 1842/6015 [35:39<1:20:38,  1.16s/it]

 31%|███       | 1843/6015 [35:40<1:20:35,  1.16s/it]

 31%|███       | 1844/6015 [35:41<1:20:36,  1.16s/it]

 31%|███       | 1845/6015 [35:42<1:20:41,  1.16s/it]

 31%|███       | 1846/6015 [35:43<1:20:36,  1.16s/it]

 31%|███       | 1847/6015 [35:45<1:20:37,  1.16s/it]

 31%|███       | 1848/6015 [35:46<1:20:37,  1.16s/it]

 31%|███       | 1849/6015 [35:47<1:20:42,  1.16s/it]

 31%|███       | 1850/6015 [35:48<1:20:43,  1.16s/it]

 31%|███       | 1851/6015 [35:49<1:20:42,  1.16s/it]

 31%|███       | 1852/6015 [35:50<1:20:39,  1.16s/it]

 31%|███       | 1853/6015 [35:52<1:20:39,  1.16s/it]

 31%|███       | 1854/6015 [35:53<1:20:33,  1.16s/it]

 31%|███       | 1855/6015 [35:54<1:20:31,  1.16s/it]

 31%|███       | 1856/6015 [35:55<1:20:29,  1.16s/it]

 31%|███       | 1857/6015 [35:56<1:20:31,  1.16s/it]

 31%|███       | 1858/6015 [35:57<1:20:37,  1.16s/it]

 31%|███       | 1859/6015 [35:59<1:20:36,  1.16s/it]

 31%|███       | 1860/6015 [36:00<1:20:38,  1.16s/it]

 31%|███       | 1861/6015 [36:01<1:20:33,  1.16s/it]

 31%|███       | 1862/6015 [36:02<1:20:25,  1.16s/it]

 31%|███       | 1863/6015 [36:03<1:20:25,  1.16s/it]

 31%|███       | 1864/6015 [36:04<1:20:19,  1.16s/it]

 31%|███       | 1865/6015 [36:06<1:20:14,  1.16s/it]

 31%|███       | 1866/6015 [36:07<1:20:12,  1.16s/it]

 31%|███       | 1867/6015 [36:08<1:20:13,  1.16s/it]

 31%|███       | 1868/6015 [36:09<1:20:09,  1.16s/it]

 31%|███       | 1869/6015 [36:10<1:20:11,  1.16s/it]

 31%|███       | 1870/6015 [36:11<1:20:13,  1.16s/it]

 31%|███       | 1871/6015 [36:13<1:20:13,  1.16s/it]

 31%|███       | 1872/6015 [36:14<1:20:12,  1.16s/it]

 31%|███       | 1873/6015 [36:15<1:20:12,  1.16s/it]

 31%|███       | 1874/6015 [36:16<1:20:09,  1.16s/it]

 31%|███       | 1875/6015 [36:17<1:20:05,  1.16s/it]

 31%|███       | 1876/6015 [36:18<1:20:08,  1.16s/it]

 31%|███       | 1877/6015 [36:19<1:20:06,  1.16s/it]

logging
logging the anndata

 31%|███       | 1878/6015 [36:21<1:23:42,  1.21s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 31%|███       | 1879/6015 [36:22<1:22:27,  1.20s/it]

 31%|███▏      | 1880/6015 [36:23<1:21:35,  1.18s/it]

 31%|███▏      | 1881/6015 [36:24<1:20:58,  1.18s/it]

 31%|███▏      | 1882/6015 [36:25<1:20:36,  1.17s/it]

 31%|███▏      | 1883/6015 [36:27<1:20:23,  1.17s/it]

 31%|███▏      | 1884/6015 [36:28<1:20:08,  1.16s/it]

 31%|███▏      | 1885/6015 [36:29<1:19:56,  1.16s/it]

 31%|███▏      | 1886/6015 [36:30<1:19:51,  1.16s/it]

 31%|███▏      | 1887/6015 [36:31<1:19:47,  1.16s/it]

 31%|███▏      | 1888/6015 [36:32<1:19:46,  1.16s/it]

 31%|███▏      | 1889/6015 [36:34<1:19:43,  1.16s/it]

 31%|███▏      | 1890/6015 [36:35<1:19:33,  1.16s/it]

 31%|███▏      | 1891/6015 [36:36<1:19:28,  1.16s/it]

 31%|███▏      | 1892/6015 [36:37<1:19:25,  1.16s/it]

 31%|███▏      | 1893/6015 [36:38<1:19:27,  1.16s/it]

 31%|███▏      | 1894/6015 [36:39<1:19:29,  1.16s/it]

 32%|███▏      | 1895/6015 [36:40<1:19:25,  1.16s/it]

 32%|███▏      | 1896/6015 [36:42<1:19:24,  1.16s/it]

 32%|███▏      | 1897/6015 [36:43<1:19:18,  1.16s/it]

 32%|███▏      | 1898/6015 [36:44<1:19:19,  1.16s/it]

 32%|███▏      | 1899/6015 [36:45<1:19:15,  1.16s/it]

 32%|███▏      | 1900/6015 [36:46<1:19:16,  1.16s/it]

 32%|███▏      | 1901/6015 [36:47<1:19:14,  1.16s/it]

 32%|███▏      | 1902/6015 [36:49<1:19:13,  1.16s/it]

 32%|███▏      | 1903/6015 [36:50<1:19:12,  1.16s/it]

 32%|███▏      | 1904/6015 [36:51<1:19:08,  1.16s/it]

 32%|███▏      | 1905/6015 [36:52<1:19:08,  1.16s/it]

 32%|███▏      | 1906/6015 [36:53<1:19:07,  1.16s/it]

 32%|███▏      | 1907/6015 [36:54<1:19:05,  1.16s/it]

 32%|███▏      | 1908/6015 [36:56<1:19:07,  1.16s/it]

 32%|███▏      | 1909/6015 [36:57<1:19:07,  1.16s/it]

 32%|███▏      | 1910/6015 [36:58<1:19:05,  1.16s/it]

 32%|███▏      | 1911/6015 [36:59<1:19:10,  1.16s/it]

 32%|███▏      | 1912/6015 [37:00<1:19:11,  1.16s/it]

 32%|███▏      | 1913/6015 [37:01<1:19:07,  1.16s/it]

 32%|███▏      | 1914/6015 [37:02<1:19:05,  1.16s/it]

 32%|███▏      | 1915/6015 [37:04<1:19:02,  1.16s/it]

 32%|███▏      | 1916/6015 [37:05<1:19:00,  1.16s/it]

 32%|███▏      | 1917/6015 [37:06<1:18:59,  1.16s/it]

 32%|███▏      | 1918/6015 [37:07<1:18:55,  1.16s/it]

 32%|███▏      | 1919/6015 [37:08<1:19:00,  1.16s/it]

 32%|███▏      | 1920/6015 [37:09<1:19:03,  1.16s/it]

 32%|███▏      | 1921/6015 [37:11<1:18:59,  1.16s/it]

 32%|███▏      | 1922/6015 [37:12<1:18:57,  1.16s/it]

 32%|███▏      | 1923/6015 [37:13<1:19:03,  1.16s/it]

 32%|███▏      | 1924/6015 [37:14<1:18:54,  1.16s/it]

 32%|███▏      | 1925/6015 [37:15<1:18:56,  1.16s/it]

 32%|███▏      | 1926/6015 [37:16<1:18:49,  1.16s/it]

 32%|███▏      | 1927/6015 [37:18<1:18:47,  1.16s/it]

 32%|███▏      | 1928/6015 [37:19<1:18:45,  1.16s/it]

 32%|███▏      | 1929/6015 [37:20<1:18:43,  1.16s/it]

 32%|███▏      | 1930/6015 [37:21<1:18:45,  1.16s/it]

 32%|███▏      | 1931/6015 [37:22<1:18:48,  1.16s/it]

 32%|███▏      | 1932/6015 [37:23<1:18:45,  1.16s/it]

 32%|███▏      | 1933/6015 [37:24<1:18:42,  1.16s/it]

 32%|███▏      | 1934/6015 [37:26<1:18:44,  1.16s/it]

 32%|███▏      | 1935/6015 [37:27<1:18:38,  1.16s/it]

 32%|███▏      | 1936/6015 [37:28<1:18:37,  1.16s/it]

 32%|███▏      | 1937/6015 [37:29<1:18:34,  1.16s/it]

 32%|███▏      | 1938/6015 [37:30<1:18:39,  1.16s/it]

 32%|███▏      | 1939/6015 [37:31<1:18:43,  1.16s/it]

 32%|███▏      | 1940/6015 [37:33<1:18:44,  1.16s/it]

 32%|███▏      | 1941/6015 [37:34<1:18:42,  1.16s/it]

 32%|███▏      | 1942/6015 [37:35<1:18:41,  1.16s/it]

 32%|███▏      | 1943/6015 [37:36<1:18:38,  1.16s/it]

 32%|███▏      | 1944/6015 [37:37<1:18:36,  1.16s/it]

 32%|███▏      | 1945/6015 [37:38<1:18:40,  1.16s/it]

 32%|███▏      | 1946/6015 [37:40<1:18:46,  1.16s/it]

 32%|███▏      | 1947/6015 [37:41<1:18:36,  1.16s/it]

 32%|███▏      | 1948/6015 [37:42<1:18:30,  1.16s/it]

 32%|███▏      | 1949/6015 [37:43<1:18:24,  1.16s/it]

 32%|███▏      | 1950/6015 [37:44<1:18:21,  1.16s/it]

 32%|███▏      | 1951/6015 [37:45<1:18:19,  1.16s/it]

 32%|███▏      | 1952/6015 [37:46<1:18:22,  1.16s/it]

 32%|███▏      | 1953/6015 [37:48<1:18:21,  1.16s/it]

 32%|███▏      | 1954/6015 [37:49<1:18:19,  1.16s/it]

 33%|███▎      | 1955/6015 [37:50<1:18:23,  1.16s/it]

 33%|███▎      | 1956/6015 [37:51<1:18:18,  1.16s/it]

 33%|███▎      | 1957/6015 [37:52<1:18:16,  1.16s/it]

 33%|███▎      | 1958/6015 [37:53<1:18:12,  1.16s/it]

 33%|███▎      | 1959/6015 [37:55<1:18:07,  1.16s/it]

 33%|███▎      | 1960/6015 [37:56<1:18:09,  1.16s/it]

 33%|███▎      | 1961/6015 [37:57<1:18:07,  1.16s/it]

 33%|███▎      | 1962/6015 [37:58<1:18:09,  1.16s/it]

 33%|███▎      | 1963/6015 [37:59<1:18:09,  1.16s/it]

 33%|███▎      | 1964/6015 [38:00<1:18:08,  1.16s/it]

 33%|███▎      | 1965/6015 [38:01<1:18:03,  1.16s/it]

 33%|███▎      | 1966/6015 [38:03<1:18:05,  1.16s/it]

 33%|███▎      | 1967/6015 [38:04<1:18:03,  1.16s/it]

 33%|███▎      | 1968/6015 [38:05<1:18:05,  1.16s/it]

 33%|███▎      | 1969/6015 [38:06<1:18:02,  1.16s/it]

 33%|███▎      | 1970/6015 [38:07<1:17:59,  1.16s/it]

 33%|███▎      | 1971/6015 [38:08<1:18:01,  1.16s/it]

 33%|███▎      | 1972/6015 [38:10<1:18:03,  1.16s/it]

 33%|███▎      | 1973/6015 [38:11<1:18:01,  1.16s/it]

 33%|███▎      | 1974/6015 [38:12<1:18:04,  1.16s/it]

 33%|███▎      | 1975/6015 [38:13<1:18:02,  1.16s/it]

 33%|███▎      | 1976/6015 [38:14<1:18:00,  1.16s/it]

 33%|███▎      | 1977/6015 [38:15<1:17:54,  1.16s/it]

 33%|███▎      | 1978/6015 [38:17<1:17:49,  1.16s/it]

 33%|███▎      | 1979/6015 [38:18<1:17:48,  1.16s/it]

 33%|███▎      | 1980/6015 [38:19<1:17:47,  1.16s/it]

 33%|███▎      | 1981/6015 [38:20<1:17:51,  1.16s/it]

 33%|███▎      | 1982/6015 [38:21<1:17:51,  1.16s/it]

 33%|███▎      | 1983/6015 [38:22<1:17:46,  1.16s/it]

 33%|███▎      | 1984/6015 [38:23<1:17:53,  1.16s/it]

 33%|███▎      | 1985/6015 [38:25<1:17:51,  1.16s/it]

 33%|███▎      | 1986/6015 [38:26<1:17:47,  1.16s/it]

 33%|███▎      | 1987/6015 [38:27<1:17:44,  1.16s/it]

 33%|███▎      | 1988/6015 [38:28<1:17:40,  1.16s/it]

 33%|███▎      | 1989/6015 [38:29<1:17:40,  1.16s/it]

 33%|███▎      | 1990/6015 [38:30<1:17:40,  1.16s/it]

 33%|███▎      | 1991/6015 [38:32<1:17:43,  1.16s/it]

 33%|███▎      | 1992/6015 [38:33<1:17:43,  1.16s/it]

 33%|███▎      | 1993/6015 [38:34<1:17:40,  1.16s/it]

 33%|███▎      | 1994/6015 [38:35<1:17:40,  1.16s/it]

 33%|███▎      | 1995/6015 [38:36<1:17:33,  1.16s/it]

 33%|███▎      | 1996/6015 [38:37<1:17:34,  1.16s/it]

 33%|███▎      | 1997/6015 [38:39<1:17:32,  1.16s/it]

 33%|███▎      | 1998/6015 [38:40<1:17:26,  1.16s/it]

 33%|███▎      | 1999/6015 [38:41<1:17:31,  1.16s/it]

 33%|███▎      | 2000/6015 [38:42<1:17:32,  1.16s/it]

 33%|███▎      | 2001/6015 [38:43<1:17:38,  1.16s/it]

 33%|███▎      | 2002/6015 [38:44<1:17:36,  1.16s/it]

 33%|███▎      | 2003/6015 [38:46<1:17:33,  1.16s/it]

 33%|███▎      | 2004/6015 [38:47<1:17:29,  1.16s/it]

 33%|███▎      | 2005/6015 [38:48<1:17:31,  1.16s/it]

 33%|███▎      | 2006/6015 [38:49<1:17:29,  1.16s/it]

 33%|███▎      | 2007/6015 [38:50<1:17:27,  1.16s/it]

 33%|███▎      | 2008/6015 [38:51<1:17:27,  1.16s/it]

 33%|███▎      | 2009/6015 [38:52<1:17:24,  1.16s/it]

 33%|███▎      | 2010/6015 [38:54<1:17:21,  1.16s/it]

 33%|███▎      | 2011/6015 [38:55<1:17:18,  1.16s/it]

 33%|███▎      | 2012/6015 [38:56<1:17:16,  1.16s/it]

 33%|███▎      | 2013/6015 [38:57<1:17:10,  1.16s/it]

 33%|███▎      | 2014/6015 [38:58<1:17:13,  1.16s/it]

 33%|███▎      | 2015/6015 [38:59<1:17:14,  1.16s/it]

 34%|███▎      | 2016/6015 [39:01<1:17:17,  1.16s/it]

 34%|███▎      | 2017/6015 [39:02<1:17:09,  1.16s/it]

 34%|███▎      | 2018/6015 [39:03<1:17:10,  1.16s/it]

 34%|███▎      | 2019/6015 [39:04<1:17:06,  1.16s/it]

 34%|███▎      | 2020/6015 [39:05<1:17:04,  1.16s/it]

 34%|███▎      | 2021/6015 [39:06<1:17:01,  1.16s/it]

 34%|███▎      | 2022/6015 [39:08<1:16:59,  1.16s/it]

 34%|███▎      | 2023/6015 [39:09<1:17:00,  1.16s/it]

 34%|███▎      | 2024/6015 [39:10<1:16:56,  1.16s/it]

 34%|███▎      | 2025/6015 [39:11<1:16:56,  1.16s/it]

 34%|███▎      | 2026/6015 [39:12<1:16:56,  1.16s/it]

 34%|███▎      | 2027/6015 [39:13<1:16:55,  1.16s/it]

 34%|███▎      | 2028/6015 [39:14<1:16:55,  1.16s/it]

 34%|███▎      | 2029/6015 [39:16<1:16:56,  1.16s/it]

 34%|███▎      | 2030/6015 [39:17<1:16:52,  1.16s/it]

 34%|███▍      | 2031/6015 [39:18<1:16:51,  1.16s/it]

 34%|███▍      | 2032/6015 [39:19<1:16:51,  1.16s/it]

 34%|███▍      | 2033/6015 [39:20<1:16:50,  1.16s/it]

 34%|███▍      | 2034/6015 [39:21<1:16:50,  1.16s/it]

 34%|███▍      | 2035/6015 [39:23<1:16:52,  1.16s/it]

 34%|███▍      | 2036/6015 [39:24<1:16:51,  1.16s/it]

 34%|███▍      | 2037/6015 [39:25<1:17:00,  1.16s/it]

 34%|███▍      | 2038/6015 [39:26<1:16:53,  1.16s/it]

 34%|███▍      | 2039/6015 [39:27<1:16:50,  1.16s/it]

 34%|███▍      | 2040/6015 [39:28<1:16:47,  1.16s/it]

 34%|███▍      | 2041/6015 [39:30<1:16:41,  1.16s/it]

 34%|███▍      | 2042/6015 [39:31<1:16:40,  1.16s/it]

 34%|███▍      | 2043/6015 [39:32<1:16:42,  1.16s/it]

 34%|███▍      | 2044/6015 [39:33<1:16:43,  1.16s/it]

 34%|███▍      | 2045/6015 [39:34<1:16:40,  1.16s/it]

 34%|███▍      | 2046/6015 [39:35<1:16:36,  1.16s/it]

 34%|███▍      | 2047/6015 [39:36<1:16:35,  1.16s/it]

 34%|███▍      | 2048/6015 [39:38<1:16:31,  1.16s/it]

 34%|███▍      | 2049/6015 [39:39<1:16:32,  1.16s/it]

 34%|███▍      | 2050/6015 [39:40<1:16:26,  1.16s/it]

 34%|███▍      | 2051/6015 [39:41<1:16:26,  1.16s/it]

 34%|███▍      | 2052/6015 [39:42<1:16:22,  1.16s/it]

 34%|███▍      | 2053/6015 [39:43<1:16:25,  1.16s/it]

 34%|███▍      | 2054/6015 [39:45<1:16:31,  1.16s/it]

 34%|███▍      | 2055/6015 [39:46<1:16:34,  1.16s/it]

 34%|███▍      | 2056/6015 [39:47<1:16:39,  1.16s/it]

 34%|███▍      | 2057/6015 [39:48<1:16:35,  1.16s/it]

 34%|███▍      | 2058/6015 [39:49<1:16:37,  1.16s/it]

 34%|███▍      | 2059/6015 [39:50<1:16:38,  1.16s/it]

 34%|███▍      | 2060/6015 [39:52<1:16:44,  1.16s/it]

 34%|███▍      | 2061/6015 [39:53<1:16:38,  1.16s/it]

 34%|███▍      | 2062/6015 [39:54<1:16:31,  1.16s/it]

 34%|███▍      | 2063/6015 [39:55<1:16:30,  1.16s/it]

 34%|███▍      | 2064/6015 [39:56<1:16:23,  1.16s/it]

 34%|███▍      | 2065/6015 [39:57<1:16:19,  1.16s/it]

 34%|███▍      | 2066/6015 [39:59<1:16:20,  1.16s/it]

 34%|███▍      | 2067/6015 [40:00<1:16:17,  1.16s/it]

 34%|███▍      | 2068/6015 [40:01<1:16:17,  1.16s/it]

 34%|███▍      | 2069/6015 [40:02<1:16:17,  1.16s/it]

 34%|███▍      | 2070/6015 [40:03<1:16:09,  1.16s/it]

 34%|███▍      | 2071/6015 [40:04<1:16:08,  1.16s/it]

 34%|███▍      | 2072/6015 [40:05<1:16:11,  1.16s/it]

 34%|███▍      | 2073/6015 [40:07<1:16:09,  1.16s/it]

 34%|███▍      | 2074/6015 [40:08<1:16:03,  1.16s/it]

 34%|███▍      | 2075/6015 [40:09<1:16:03,  1.16s/it]

 35%|███▍      | 2076/6015 [40:10<1:16:03,  1.16s/it]

 35%|███▍      | 2077/6015 [40:11<1:15:59,  1.16s/it]

 35%|███▍      | 2078/6015 [40:12<1:15:58,  1.16s/it]

 35%|███▍      | 2079/6015 [40:14<1:15:59,  1.16s/it]

 35%|███▍      | 2080/6015 [40:15<1:15:57,  1.16s/it]

 35%|███▍      | 2081/6015 [40:16<1:15:55,  1.16s/it]

 35%|███▍      | 2082/6015 [40:17<1:15:54,  1.16s/it]

 35%|███▍      | 2083/6015 [40:18<1:15:50,  1.16s/it]

 35%|███▍      | 2084/6015 [40:19<1:15:52,  1.16s/it]

 35%|███▍      | 2085/6015 [40:21<1:15:53,  1.16s/it]

 35%|███▍      | 2086/6015 [40:22<1:15:51,  1.16s/it]

 35%|███▍      | 2087/6015 [40:23<1:15:51,  1.16s/it]

 35%|███▍      | 2088/6015 [40:24<1:15:53,  1.16s/it]

 35%|███▍      | 2089/6015 [40:25<1:15:51,  1.16s/it]

 35%|███▍      | 2090/6015 [40:26<1:15:50,  1.16s/it]

 35%|███▍      | 2091/6015 [40:27<1:15:51,  1.16s/it]

 35%|███▍      | 2092/6015 [40:29<1:15:49,  1.16s/it]

 35%|███▍      | 2093/6015 [40:30<1:15:43,  1.16s/it]

 35%|███▍      | 2094/6015 [40:31<1:15:41,  1.16s/it]

 35%|███▍      | 2095/6015 [40:32<1:15:40,  1.16s/it]

 35%|███▍      | 2096/6015 [40:33<1:15:39,  1.16s/it]

 35%|███▍      | 2097/6015 [40:34<1:15:40,  1.16s/it]

 35%|███▍      | 2098/6015 [40:36<1:15:43,  1.16s/it]

 35%|███▍      | 2099/6015 [40:37<1:15:40,  1.16s/it]

 35%|███▍      | 2100/6015 [40:38<1:15:35,  1.16s/it]

 35%|███▍      | 2101/6015 [40:39<1:15:35,  1.16s/it]

 35%|███▍      | 2102/6015 [40:40<1:15:31,  1.16s/it]

 35%|███▍      | 2103/6015 [40:41<1:15:27,  1.16s/it]

 35%|███▍      | 2104/6015 [40:43<1:15:23,  1.16s/it]

 35%|███▍      | 2105/6015 [40:44<1:15:23,  1.16s/it]

 35%|███▌      | 2106/6015 [40:45<1:15:29,  1.16s/it]

 35%|███▌      | 2107/6015 [40:46<1:15:28,  1.16s/it]

 35%|███▌      | 2108/6015 [40:47<1:15:31,  1.16s/it]

 35%|███▌      | 2109/6015 [40:48<1:15:28,  1.16s/it]

 35%|███▌      | 2110/6015 [40:49<1:15:28,  1.16s/it]

 35%|███▌      | 2111/6015 [40:51<1:15:28,  1.16s/it]

 35%|███▌      | 2112/6015 [40:52<1:15:30,  1.16s/it]

 35%|███▌      | 2113/6015 [40:53<1:15:30,  1.16s/it]

 35%|███▌      | 2114/6015 [40:54<1:15:22,  1.16s/it]

 35%|███▌      | 2115/6015 [40:55<1:15:27,  1.16s/it]

 35%|███▌      | 2116/6015 [40:56<1:15:27,  1.16s/it]

 35%|███▌      | 2117/6015 [40:58<1:15:22,  1.16s/it]

 35%|███▌      | 2118/6015 [40:59<1:15:20,  1.16s/it]

 35%|███▌      | 2119/6015 [41:00<1:15:21,  1.16s/it]

 35%|███▌      | 2120/6015 [41:01<1:15:13,  1.16s/it]

 35%|███▌      | 2121/6015 [41:02<1:15:15,  1.16s/it]

 35%|███▌      | 2122/6015 [41:03<1:15:18,  1.16s/it]

 35%|███▌      | 2123/6015 [41:05<1:15:14,  1.16s/it]

 35%|███▌      | 2124/6015 [41:06<1:15:11,  1.16s/it]

 35%|███▌      | 2125/6015 [41:07<1:15:11,  1.16s/it]

 35%|███▌      | 2126/6015 [41:08<1:15:14,  1.16s/it]

 35%|███▌      | 2127/6015 [41:09<1:15:09,  1.16s/it]

 35%|███▌      | 2128/6015 [41:10<1:15:07,  1.16s/it]

 35%|███▌      | 2129/6015 [41:12<1:15:02,  1.16s/it]

 35%|███▌      | 2130/6015 [41:13<1:14:56,  1.16s/it]

 35%|███▌      | 2131/6015 [41:14<1:14:58,  1.16s/it]

 35%|███▌      | 2132/6015 [41:15<1:15:02,  1.16s/it]

 35%|███▌      | 2133/6015 [41:16<1:15:01,  1.16s/it]

 35%|███▌      | 2134/6015 [41:17<1:15:02,  1.16s/it]

 35%|███▌      | 2135/6015 [41:18<1:14:57,  1.16s/it]

 36%|███▌      | 2136/6015 [41:20<1:14:58,  1.16s/it]

 36%|███▌      | 2137/6015 [41:21<1:14:57,  1.16s/it]

 36%|███▌      | 2138/6015 [41:22<1:14:53,  1.16s/it]

 36%|███▌      | 2139/6015 [41:23<1:14:49,  1.16s/it]

 36%|███▌      | 2140/6015 [41:24<1:14:48,  1.16s/it]

 36%|███▌      | 2141/6015 [41:25<1:14:48,  1.16s/it]

 36%|███▌      | 2142/6015 [41:27<1:14:48,  1.16s/it]

 36%|███▌      | 2143/6015 [41:28<1:14:47,  1.16s/it]

 36%|███▌      | 2144/6015 [41:29<1:14:44,  1.16s/it]

 36%|███▌      | 2145/6015 [41:30<1:14:43,  1.16s/it]

 36%|███▌      | 2146/6015 [41:31<1:14:44,  1.16s/it]

 36%|███▌      | 2147/6015 [41:32<1:14:45,  1.16s/it]

 36%|███▌      | 2148/6015 [41:34<1:14:39,  1.16s/it]

 36%|███▌      | 2149/6015 [41:35<1:14:37,  1.16s/it]

 36%|███▌      | 2150/6015 [41:36<1:14:32,  1.16s/it]

 36%|███▌      | 2151/6015 [41:37<1:14:31,  1.16s/it]

 36%|███▌      | 2152/6015 [41:38<1:14:36,  1.16s/it]

 36%|███▌      | 2153/6015 [41:39<1:14:43,  1.16s/it]

 36%|███▌      | 2154/6015 [41:41<1:14:41,  1.16s/it]

 36%|███▌      | 2155/6015 [41:42<1:14:40,  1.16s/it]

 36%|███▌      | 2156/6015 [41:43<1:14:41,  1.16s/it]

 36%|███▌      | 2157/6015 [41:44<1:14:38,  1.16s/it]

 36%|███▌      | 2158/6015 [41:45<1:14:34,  1.16s/it]

 36%|███▌      | 2159/6015 [41:46<1:14:33,  1.16s/it]

 36%|███▌      | 2160/6015 [41:47<1:14:28,  1.16s/it]

 36%|███▌      | 2161/6015 [41:49<1:14:27,  1.16s/it]

 36%|███▌      | 2162/6015 [41:50<1:14:24,  1.16s/it]

 36%|███▌      | 2163/6015 [41:51<1:14:22,  1.16s/it]

 36%|███▌      | 2164/6015 [41:52<1:14:21,  1.16s/it]

 36%|███▌      | 2165/6015 [41:53<1:14:22,  1.16s/it]

 36%|███▌      | 2166/6015 [41:54<1:14:22,  1.16s/it]

 36%|███▌      | 2167/6015 [41:56<1:14:20,  1.16s/it]

 36%|███▌      | 2168/6015 [41:57<1:14:21,  1.16s/it]

 36%|███▌      | 2169/6015 [41:58<1:14:17,  1.16s/it]

 36%|███▌      | 2170/6015 [41:59<1:14:14,  1.16s/it]

 36%|███▌      | 2171/6015 [42:00<1:14:12,  1.16s/it]

 36%|███▌      | 2172/6015 [42:01<1:14:16,  1.16s/it]

 36%|███▌      | 2173/6015 [42:03<1:14:15,  1.16s/it]

 36%|███▌      | 2174/6015 [42:04<1:14:19,  1.16s/it]

 36%|███▌      | 2175/6015 [42:05<1:14:17,  1.16s/it]

 36%|███▌      | 2176/6015 [42:06<1:14:15,  1.16s/it]

 36%|███▌      | 2177/6015 [42:07<1:14:10,  1.16s/it]

 36%|███▌      | 2178/6015 [42:08<1:14:07,  1.16s/it]

 36%|███▌      | 2179/6015 [42:10<1:14:06,  1.16s/it]

 36%|███▌      | 2180/6015 [42:11<1:14:08,  1.16s/it]

 36%|███▋      | 2181/6015 [42:12<1:14:02,  1.16s/it]

 36%|███▋      | 2182/6015 [42:13<1:14:01,  1.16s/it]

 36%|███▋      | 2183/6015 [42:14<1:14:09,  1.16s/it]

 36%|███▋      | 2184/6015 [42:15<1:14:06,  1.16s/it]

 36%|███▋      | 2185/6015 [42:16<1:14:03,  1.16s/it]

 36%|███▋      | 2186/6015 [42:18<1:13:58,  1.16s/it]

 36%|███▋      | 2187/6015 [42:19<1:13:59,  1.16s/it]

 36%|███▋      | 2188/6015 [42:20<1:13:57,  1.16s/it]

 36%|███▋      | 2189/6015 [42:21<1:13:55,  1.16s/it]

 36%|███▋      | 2190/6015 [42:22<1:13:54,  1.16s/it]

 36%|███▋      | 2191/6015 [42:23<1:13:53,  1.16s/it]

 36%|███▋      | 2192/6015 [42:25<1:13:52,  1.16s/it]

 36%|███▋      | 2193/6015 [42:26<1:13:57,  1.16s/it]

 36%|███▋      | 2194/6015 [42:27<1:13:50,  1.16s/it]

 36%|███▋      | 2195/6015 [42:28<1:13:48,  1.16s/it]

 37%|███▋      | 2196/6015 [42:29<1:13:44,  1.16s/it]

 37%|███▋      | 2197/6015 [42:30<1:13:42,  1.16s/it]

 37%|███▋      | 2198/6015 [42:32<1:13:42,  1.16s/it]

 37%|███▋      | 2199/6015 [42:33<1:13:44,  1.16s/it]

 37%|███▋      | 2200/6015 [42:34<1:13:45,  1.16s/it]

 37%|███▋      | 2201/6015 [42:35<1:13:44,  1.16s/it]

 37%|███▋      | 2202/6015 [42:36<1:13:40,  1.16s/it]

 37%|███▋      | 2203/6015 [42:37<1:13:42,  1.16s/it]

 37%|███▋      | 2204/6015 [42:38<1:13:38,  1.16s/it]

 37%|███▋      | 2205/6015 [42:40<1:13:37,  1.16s/it]

 37%|███▋      | 2206/6015 [42:41<1:13:36,  1.16s/it]

 37%|███▋      | 2207/6015 [42:42<1:13:33,  1.16s/it]

 37%|███▋      | 2208/6015 [42:43<1:13:31,  1.16s/it]

 37%|███▋      | 2209/6015 [42:44<1:13:30,  1.16s/it]

 37%|███▋      | 2210/6015 [42:45<1:13:31,  1.16s/it]

 37%|███▋      | 2211/6015 [42:47<1:13:34,  1.16s/it]

 37%|███▋      | 2212/6015 [42:48<1:13:36,  1.16s/it]

 37%|███▋      | 2213/6015 [42:49<1:13:33,  1.16s/it]

 37%|███▋      | 2214/6015 [42:50<1:13:32,  1.16s/it]

 37%|███▋      | 2215/6015 [42:51<1:13:28,  1.16s/it]

 37%|███▋      | 2216/6015 [42:52<1:13:38,  1.16s/it]

 37%|███▋      | 2217/6015 [42:54<1:13:34,  1.16s/it]

 37%|███▋      | 2218/6015 [42:55<1:13:25,  1.16s/it]

 37%|███▋      | 2219/6015 [42:56<1:13:20,  1.16s/it]

 37%|███▋      | 2220/6015 [42:57<1:13:15,  1.16s/it]

 37%|███▋      | 2221/6015 [42:58<1:13:17,  1.16s/it]

 37%|███▋      | 2222/6015 [42:59<1:13:20,  1.16s/it]

 37%|███▋      | 2223/6015 [43:01<1:13:22,  1.16s/it]

 37%|███▋      | 2224/6015 [43:02<1:13:24,  1.16s/it]

 37%|███▋      | 2225/6015 [43:03<1:13:20,  1.16s/it]

 37%|███▋      | 2226/6015 [43:04<1:13:17,  1.16s/it]

 37%|███▋      | 2227/6015 [43:05<1:13:20,  1.16s/it]

 37%|███▋      | 2228/6015 [43:06<1:13:13,  1.16s/it]

 37%|███▋      | 2229/6015 [43:08<1:13:13,  1.16s/it]

 37%|███▋      | 2230/6015 [43:09<1:13:11,  1.16s/it]

 37%|███▋      | 2231/6015 [43:10<1:13:10,  1.16s/it]

 37%|███▋      | 2232/6015 [43:11<1:13:13,  1.16s/it]

 37%|███▋      | 2233/6015 [43:12<1:13:19,  1.16s/it]

 37%|███▋      | 2234/6015 [43:13<1:13:13,  1.16s/it]

 37%|███▋      | 2235/6015 [43:14<1:13:14,  1.16s/it]

 37%|███▋      | 2236/6015 [43:16<1:13:08,  1.16s/it]

 37%|███▋      | 2237/6015 [43:17<1:13:05,  1.16s/it]

 37%|███▋      | 2238/6015 [43:18<1:13:05,  1.16s/it]

 37%|███▋      | 2239/6015 [43:19<1:13:06,  1.16s/it]

 37%|███▋      | 2240/6015 [43:20<1:13:06,  1.16s/it]

 37%|███▋      | 2241/6015 [43:21<1:13:05,  1.16s/it]

 37%|███▋      | 2242/6015 [43:23<1:13:03,  1.16s/it]

 37%|███▋      | 2243/6015 [43:24<1:13:01,  1.16s/it]

 37%|███▋      | 2244/6015 [43:25<1:12:57,  1.16s/it]

 37%|███▋      | 2245/6015 [43:26<1:12:52,  1.16s/it]

 37%|███▋      | 2246/6015 [43:27<1:12:47,  1.16s/it]

 37%|███▋      | 2247/6015 [43:28<1:12:50,  1.16s/it]

 37%|███▋      | 2248/6015 [43:30<1:12:54,  1.16s/it]

 37%|███▋      | 2249/6015 [43:31<1:12:55,  1.16s/it]

 37%|███▋      | 2250/6015 [43:32<1:12:53,  1.16s/it]

 37%|███▋      | 2251/6015 [43:33<1:12:52,  1.16s/it]

 37%|███▋      | 2252/6015 [43:34<1:12:45,  1.16s/it]

 37%|███▋      | 2253/6015 [43:35<1:12:50,  1.16s/it]

 37%|███▋      | 2254/6015 [43:37<1:12:47,  1.16s/it]

 37%|███▋      | 2255/6015 [43:38<1:12:43,  1.16s/it]

 38%|███▊      | 2256/6015 [43:39<1:12:38,  1.16s/it]

 38%|███▊      | 2257/6015 [43:40<1:12:38,  1.16s/it]

 38%|███▊      | 2258/6015 [43:41<1:12:38,  1.16s/it]

 38%|███▊      | 2259/6015 [43:42<1:12:40,  1.16s/it]

 38%|███▊      | 2260/6015 [43:43<1:12:41,  1.16s/it]

 38%|███▊      | 2261/6015 [43:45<1:12:41,  1.16s/it]

 38%|███▊      | 2262/6015 [43:46<1:12:37,  1.16s/it]

 38%|███▊      | 2263/6015 [43:47<1:12:35,  1.16s/it]

 38%|███▊      | 2264/6015 [43:48<1:12:35,  1.16s/it]

 38%|███▊      | 2265/6015 [43:49<1:12:39,  1.16s/it]

 38%|███▊      | 2266/6015 [43:50<1:12:42,  1.16s/it]

 38%|███▊      | 2267/6015 [43:52<1:12:39,  1.16s/it]

 38%|███▊      | 2268/6015 [43:53<1:12:35,  1.16s/it]

 38%|███▊      | 2269/6015 [43:54<1:12:28,  1.16s/it]

 38%|███▊      | 2270/6015 [43:55<1:12:27,  1.16s/it]

 38%|███▊      | 2271/6015 [43:56<1:12:26,  1.16s/it]

 38%|███▊      | 2272/6015 [43:57<1:12:24,  1.16s/it]

 38%|███▊      | 2273/6015 [43:59<1:12:23,  1.16s/it]

 38%|███▊      | 2274/6015 [44:00<1:12:22,  1.16s/it]

 38%|███▊      | 2275/6015 [44:01<1:12:23,  1.16s/it]

 38%|███▊      | 2276/6015 [44:02<1:12:23,  1.16s/it]

 38%|███▊      | 2277/6015 [44:03<1:12:26,  1.16s/it]

 38%|███▊      | 2278/6015 [44:04<1:12:24,  1.16s/it]

 38%|███▊      | 2279/6015 [44:06<1:12:22,  1.16s/it]

 38%|███▊      | 2280/6015 [44:07<1:12:16,  1.16s/it]

 38%|███▊      | 2281/6015 [44:08<1:12:11,  1.16s/it]

 38%|███▊      | 2282/6015 [44:09<1:12:11,  1.16s/it]

 38%|███▊      | 2283/6015 [44:10<1:12:10,  1.16s/it]

 38%|███▊      | 2284/6015 [44:11<1:12:05,  1.16s/it]

 38%|███▊      | 2285/6015 [44:13<1:12:07,  1.16s/it]

 38%|███▊      | 2286/6015 [44:14<1:12:10,  1.16s/it]

 38%|███▊      | 2287/6015 [44:15<1:12:11,  1.16s/it]

 38%|███▊      | 2288/6015 [44:16<1:12:10,  1.16s/it]

 38%|███▊      | 2289/6015 [44:17<1:12:11,  1.16s/it]

 38%|███▊      | 2290/6015 [44:18<1:12:07,  1.16s/it]

 38%|███▊      | 2291/6015 [44:19<1:12:01,  1.16s/it]

 38%|███▊      | 2292/6015 [44:21<1:12:01,  1.16s/it]

 38%|███▊      | 2293/6015 [44:22<1:12:01,  1.16s/it]

 38%|███▊      | 2294/6015 [44:23<1:11:58,  1.16s/it]

 38%|███▊      | 2295/6015 [44:24<1:11:59,  1.16s/it]

 38%|███▊      | 2296/6015 [44:25<1:11:57,  1.16s/it]

 38%|███▊      | 2297/6015 [44:26<1:11:56,  1.16s/it]

 38%|███▊      | 2298/6015 [44:28<1:11:51,  1.16s/it]

 38%|███▊      | 2299/6015 [44:29<1:11:50,  1.16s/it]

 38%|███▊      | 2300/6015 [44:30<1:11:50,  1.16s/it]

 38%|███▊      | 2301/6015 [44:31<1:11:51,  1.16s/it]

 38%|███▊      | 2302/6015 [44:32<1:11:49,  1.16s/it]

 38%|███▊      | 2303/6015 [44:33<1:11:49,  1.16s/it]

 38%|███▊      | 2304/6015 [44:35<1:11:45,  1.16s/it]

 38%|███▊      | 2305/6015 [44:36<1:11:47,  1.16s/it]

 38%|███▊      | 2306/6015 [44:37<1:11:55,  1.16s/it]

 38%|███▊      | 2307/6015 [44:38<1:11:48,  1.16s/it]

 38%|███▊      | 2308/6015 [44:39<1:11:44,  1.16s/it]

 38%|███▊      | 2309/6015 [44:40<1:11:42,  1.16s/it]

 38%|███▊      | 2310/6015 [44:42<1:11:40,  1.16s/it]

 38%|███▊      | 2311/6015 [44:43<1:11:42,  1.16s/it]

 38%|███▊      | 2312/6015 [44:44<1:11:40,  1.16s/it]

 38%|███▊      | 2313/6015 [44:45<1:11:38,  1.16s/it]

 38%|███▊      | 2314/6015 [44:46<1:11:38,  1.16s/it]

 38%|███▊      | 2315/6015 [44:47<1:11:35,  1.16s/it]

 39%|███▊      | 2316/6015 [44:49<1:11:37,  1.16s/it]

 39%|███▊      | 2317/6015 [44:50<1:11:39,  1.16s/it]

 39%|███▊      | 2318/6015 [44:51<1:11:39,  1.16s/it]

 39%|███▊      | 2319/6015 [44:52<1:11:38,  1.16s/it]

 39%|███▊      | 2320/6015 [44:53<1:11:32,  1.16s/it]

 39%|███▊      | 2321/6015 [44:54<1:11:30,  1.16s/it]

 39%|███▊      | 2322/6015 [44:55<1:11:27,  1.16s/it]

 39%|███▊      | 2323/6015 [44:57<1:11:28,  1.16s/it]

 39%|███▊      | 2324/6015 [44:58<1:11:27,  1.16s/it]

 39%|███▊      | 2325/6015 [44:59<1:11:28,  1.16s/it]

 39%|███▊      | 2326/6015 [45:00<1:11:24,  1.16s/it]

 39%|███▊      | 2327/6015 [45:01<1:11:22,  1.16s/it]

 39%|███▊      | 2328/6015 [45:02<1:11:22,  1.16s/it]

 39%|███▊      | 2329/6015 [45:04<1:11:24,  1.16s/it]

 39%|███▊      | 2330/6015 [45:05<1:11:24,  1.16s/it]

 39%|███▉      | 2331/6015 [45:06<1:11:26,  1.16s/it]

 39%|███▉      | 2332/6015 [45:07<1:11:20,  1.16s/it]

 39%|███▉      | 2333/6015 [45:08<1:11:17,  1.16s/it]

 39%|███▉      | 2334/6015 [45:09<1:11:11,  1.16s/it]

 39%|███▉      | 2335/6015 [45:11<1:11:10,  1.16s/it]

 39%|███▉      | 2336/6015 [45:12<1:11:14,  1.16s/it]

 39%|███▉      | 2337/6015 [45:13<1:11:12,  1.16s/it]

 39%|███▉      | 2338/6015 [45:14<1:11:07,  1.16s/it]

 39%|███▉      | 2339/6015 [45:15<1:11:07,  1.16s/it]

 39%|███▉      | 2340/6015 [45:16<1:11:08,  1.16s/it]

 39%|███▉      | 2341/6015 [45:18<1:11:08,  1.16s/it]

 39%|███▉      | 2342/6015 [45:19<1:11:06,  1.16s/it]

 39%|███▉      | 2343/6015 [45:20<1:11:07,  1.16s/it]

 39%|███▉      | 2344/6015 [45:21<1:10:59,  1.16s/it]

 39%|███▉      | 2345/6015 [45:22<1:11:04,  1.16s/it]

 39%|███▉      | 2346/6015 [45:23<1:11:02,  1.16s/it]

 39%|███▉      | 2347/6015 [45:25<1:11:03,  1.16s/it]

 39%|███▉      | 2348/6015 [45:26<1:11:00,  1.16s/it]

 39%|███▉      | 2349/6015 [45:27<1:11:03,  1.16s/it]

 39%|███▉      | 2350/6015 [45:28<1:11:03,  1.16s/it]

 39%|███▉      | 2351/6015 [45:29<1:11:00,  1.16s/it]

 39%|███▉      | 2352/6015 [45:30<1:10:54,  1.16s/it]

 39%|███▉      | 2353/6015 [45:32<1:10:50,  1.16s/it]

 39%|███▉      | 2354/6015 [45:33<1:10:47,  1.16s/it]

 39%|███▉      | 2355/6015 [45:34<1:10:51,  1.16s/it]

 39%|███▉      | 2356/6015 [45:35<1:10:54,  1.16s/it]

 39%|███▉      | 2357/6015 [45:36<1:10:55,  1.16s/it]

 39%|███▉      | 2358/6015 [45:37<1:10:53,  1.16s/it]

 39%|███▉      | 2359/6015 [45:38<1:10:50,  1.16s/it]

 39%|███▉      | 2360/6015 [45:40<1:10:45,  1.16s/it]

 39%|███▉      | 2361/6015 [45:41<1:10:41,  1.16s/it]

 39%|███▉      | 2362/6015 [45:42<1:10:46,  1.16s/it]

 39%|███▉      | 2363/6015 [45:43<1:10:42,  1.16s/it]

 39%|███▉      | 2364/6015 [45:44<1:10:40,  1.16s/it]

 39%|███▉      | 2365/6015 [45:45<1:10:36,  1.16s/it]

 39%|███▉      | 2366/6015 [45:47<1:10:37,  1.16s/it]

 39%|███▉      | 2367/6015 [45:48<1:10:35,  1.16s/it]

 39%|███▉      | 2368/6015 [45:49<1:10:35,  1.16s/it]

 39%|███▉      | 2369/6015 [45:50<1:10:32,  1.16s/it]

 39%|███▉      | 2370/6015 [45:51<1:10:30,  1.16s/it]

 39%|███▉      | 2371/6015 [45:52<1:10:29,  1.16s/it]

 39%|███▉      | 2372/6015 [45:54<1:10:33,  1.16s/it]

 39%|███▉      | 2373/6015 [45:55<1:10:33,  1.16s/it]

 39%|███▉      | 2374/6015 [45:56<1:10:34,  1.16s/it]

 39%|███▉      | 2375/6015 [45:57<1:10:36,  1.16s/it]

 40%|███▉      | 2376/6015 [45:58<1:10:35,  1.16s/it]

 40%|███▉      | 2377/6015 [45:59<1:10:30,  1.16s/it]

 40%|███▉      | 2378/6015 [46:01<1:10:27,  1.16s/it]

 40%|███▉      | 2379/6015 [46:02<1:10:25,  1.16s/it]

 40%|███▉      | 2380/6015 [46:03<1:10:24,  1.16s/it]

 40%|███▉      | 2381/6015 [46:04<1:10:22,  1.16s/it]

 40%|███▉      | 2382/6015 [46:05<1:10:24,  1.16s/it]

 40%|███▉      | 2383/6015 [46:06<1:10:23,  1.16s/it]

 40%|███▉      | 2384/6015 [46:08<1:10:25,  1.16s/it]

 40%|███▉      | 2385/6015 [46:09<1:10:25,  1.16s/it]

 40%|███▉      | 2386/6015 [46:10<1:10:23,  1.16s/it]

 40%|███▉      | 2387/6015 [46:11<1:10:24,  1.16s/it]

 40%|███▉      | 2388/6015 [46:12<1:10:20,  1.16s/it]

 40%|███▉      | 2389/6015 [46:13<1:10:16,  1.16s/it]

 40%|███▉      | 2390/6015 [46:15<1:10:12,  1.16s/it]

 40%|███▉      | 2391/6015 [46:16<1:10:08,  1.16s/it]

 40%|███▉      | 2392/6015 [46:17<1:10:07,  1.16s/it]

 40%|███▉      | 2393/6015 [46:18<1:10:04,  1.16s/it]

 40%|███▉      | 2394/6015 [46:19<1:10:01,  1.16s/it]

 40%|███▉      | 2395/6015 [46:20<1:10:03,  1.16s/it]

 40%|███▉      | 2396/6015 [46:21<1:10:04,  1.16s/it]

 40%|███▉      | 2397/6015 [46:23<1:10:03,  1.16s/it]

 40%|███▉      | 2398/6015 [46:24<1:10:03,  1.16s/it]

 40%|███▉      | 2399/6015 [46:25<1:10:05,  1.16s/it]

 40%|███▉      | 2400/6015 [46:26<1:10:01,  1.16s/it]

 40%|███▉      | 2401/6015 [46:27<1:09:58,  1.16s/it]

 40%|███▉      | 2402/6015 [46:28<1:09:55,  1.16s/it]

 40%|███▉      | 2403/6015 [46:30<1:09:50,  1.16s/it]

 40%|███▉      | 2404/6015 [46:31<1:09:50,  1.16s/it]

 40%|███▉      | 2405/6015 [46:32<1:09:56,  1.16s/it]

 40%|████      | 2406/6015 [46:33<1:09:55,  1.16s/it]

 40%|████      | 2407/6015 [46:34<1:09:57,  1.16s/it]

 40%|████      | 2408/6015 [46:35<1:09:53,  1.16s/it]

 40%|████      | 2409/6015 [46:37<1:09:48,  1.16s/it]

 40%|████      | 2410/6015 [46:38<1:09:45,  1.16s/it]

 40%|████      | 2411/6015 [46:39<1:09:43,  1.16s/it]

 40%|████      | 2412/6015 [46:40<1:09:41,  1.16s/it]

 40%|████      | 2413/6015 [46:41<1:09:45,  1.16s/it]

 40%|████      | 2414/6015 [46:42<1:09:47,  1.16s/it]

 40%|████      | 2415/6015 [46:44<1:09:46,  1.16s/it]

 40%|████      | 2416/6015 [46:45<1:09:45,  1.16s/it]

 40%|████      | 2417/6015 [46:46<1:09:47,  1.16s/it]

 40%|████      | 2418/6015 [46:47<1:09:48,  1.16s/it]

 40%|████      | 2419/6015 [46:48<1:09:44,  1.16s/it]

 40%|████      | 2420/6015 [46:49<1:09:41,  1.16s/it]

 40%|████      | 2421/6015 [46:51<1:09:38,  1.16s/it]

 40%|████      | 2422/6015 [46:52<1:09:36,  1.16s/it]

 40%|████      | 2423/6015 [46:53<1:09:32,  1.16s/it]

 40%|████      | 2424/6015 [46:54<1:09:29,  1.16s/it]

 40%|████      | 2425/6015 [46:55<1:09:29,  1.16s/it]

 40%|████      | 2426/6015 [46:56<1:09:27,  1.16s/it]

 40%|████      | 2427/6015 [46:58<1:09:27,  1.16s/it]

 40%|████      | 2428/6015 [46:59<1:09:26,  1.16s/it]

 40%|████      | 2429/6015 [47:00<1:09:28,  1.16s/it]

 40%|████      | 2430/6015 [47:01<1:09:33,  1.16s/it]

 40%|████      | 2431/6015 [47:02<1:09:30,  1.16s/it]

 40%|████      | 2432/6015 [47:03<1:09:27,  1.16s/it]

 40%|████      | 2433/6015 [47:04<1:09:27,  1.16s/it]

 40%|████      | 2434/6015 [47:06<1:09:26,  1.16s/it]

 40%|████      | 2435/6015 [47:07<1:09:26,  1.16s/it]

 40%|████      | 2436/6015 [47:08<1:09:17,  1.16s/it]

 41%|████      | 2437/6015 [47:09<1:09:16,  1.16s/it]

 41%|████      | 2438/6015 [47:10<1:09:14,  1.16s/it]

 41%|████      | 2439/6015 [47:11<1:09:18,  1.16s/it]

 41%|████      | 2440/6015 [47:13<1:09:20,  1.16s/it]

 41%|████      | 2441/6015 [47:14<1:09:16,  1.16s/it]

 41%|████      | 2442/6015 [47:15<1:09:17,  1.16s/it]

 41%|████      | 2443/6015 [47:16<1:09:17,  1.16s/it]

 41%|████      | 2444/6015 [47:17<1:09:15,  1.16s/it]

 41%|████      | 2445/6015 [47:18<1:09:14,  1.16s/it]

 41%|████      | 2446/6015 [47:20<1:09:10,  1.16s/it]

 41%|████      | 2447/6015 [47:21<1:09:09,  1.16s/it]

 41%|████      | 2448/6015 [47:22<1:09:02,  1.16s/it]

 41%|████      | 2449/6015 [47:23<1:08:58,  1.16s/it]

 41%|████      | 2450/6015 [47:24<1:08:56,  1.16s/it]

 41%|████      | 2451/6015 [47:25<1:08:55,  1.16s/it]

 41%|████      | 2452/6015 [47:27<1:08:57,  1.16s/it]

 41%|████      | 2453/6015 [47:28<1:08:58,  1.16s/it]

 41%|████      | 2454/6015 [47:29<1:08:59,  1.16s/it]

 41%|████      | 2455/6015 [47:30<1:08:56,  1.16s/it]

 41%|████      | 2456/6015 [47:31<1:08:52,  1.16s/it]

 41%|████      | 2457/6015 [47:32<1:08:57,  1.16s/it]

 41%|████      | 2458/6015 [47:34<1:08:56,  1.16s/it]

 41%|████      | 2459/6015 [47:35<1:08:56,  1.16s/it]

 41%|████      | 2460/6015 [47:36<1:08:53,  1.16s/it]

 41%|████      | 2461/6015 [47:37<1:08:50,  1.16s/it]

 41%|████      | 2462/6015 [47:38<1:08:49,  1.16s/it]

 41%|████      | 2463/6015 [47:39<1:08:51,  1.16s/it]

 41%|████      | 2464/6015 [47:41<1:08:56,  1.16s/it]

 41%|████      | 2465/6015 [47:42<1:09:02,  1.17s/it]

 41%|████      | 2466/6015 [47:43<1:08:59,  1.17s/it]

 41%|████      | 2467/6015 [47:44<1:08:50,  1.16s/it]

 41%|████      | 2468/6015 [47:45<1:08:47,  1.16s/it]

 41%|████      | 2469/6015 [47:46<1:08:47,  1.16s/it]

 41%|████      | 2470/6015 [47:48<1:08:46,  1.16s/it]

 41%|████      | 2471/6015 [47:49<1:08:43,  1.16s/it]

 41%|████      | 2472/6015 [47:50<1:08:42,  1.16s/it]

 41%|████      | 2473/6015 [47:51<1:08:39,  1.16s/it]

 41%|████      | 2474/6015 [47:52<1:08:34,  1.16s/it]

 41%|████      | 2475/6015 [47:53<1:08:34,  1.16s/it]

 41%|████      | 2476/6015 [47:54<1:08:35,  1.16s/it]

 41%|████      | 2477/6015 [47:56<1:08:36,  1.16s/it]

 41%|████      | 2478/6015 [47:57<1:08:34,  1.16s/it]

 41%|████      | 2479/6015 [47:58<1:08:34,  1.16s/it]

 41%|████      | 2480/6015 [47:59<1:08:31,  1.16s/it]

 41%|████      | 2481/6015 [48:00<1:08:22,  1.16s/it]

 41%|████▏     | 2482/6015 [48:01<1:08:19,  1.16s/it]

 41%|████▏     | 2483/6015 [48:03<1:08:19,  1.16s/it]

 41%|████▏     | 2484/6015 [48:04<1:08:21,  1.16s/it]

 41%|████▏     | 2485/6015 [48:05<1:08:21,  1.16s/it]

 41%|████▏     | 2486/6015 [48:06<1:08:23,  1.16s/it]

 41%|████▏     | 2487/6015 [48:07<1:08:22,  1.16s/it]

 41%|████▏     | 2488/6015 [48:08<1:08:19,  1.16s/it]

 41%|████▏     | 2489/6015 [48:10<1:08:16,  1.16s/it]

 41%|████▏     | 2490/6015 [48:11<1:08:23,  1.16s/it]

 41%|████▏     | 2491/6015 [48:12<1:08:21,  1.16s/it]

 41%|████▏     | 2492/6015 [48:13<1:08:18,  1.16s/it]

 41%|████▏     | 2493/6015 [48:14<1:08:15,  1.16s/it]

 41%|████▏     | 2494/6015 [48:15<1:08:11,  1.16s/it]

 41%|████▏     | 2495/6015 [48:17<1:08:06,  1.16s/it]

 41%|████▏     | 2496/6015 [48:18<1:08:06,  1.16s/it]

 42%|████▏     | 2497/6015 [48:19<1:08:06,  1.16s/it]

 42%|████▏     | 2498/6015 [48:20<1:08:06,  1.16s/it]

 42%|████▏     | 2499/6015 [48:21<1:08:07,  1.16s/it]

 42%|████▏     | 2500/6015 [48:22<1:08:05,  1.16s/it]

 42%|████▏     | 2501/6015 [48:24<1:08:04,  1.16s/it]

 42%|████▏     | 2502/6015 [48:25<1:08:02,  1.16s/it]

 42%|████▏     | 2503/6015 [48:26<1:08:01,  1.16s/it]

logging
logging the anndata

 42%|████▏     | 2504/6015 [48:27<1:09:56,  1.20s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 42%|████▏     | 2505/6015 [48:28<1:09:15,  1.18s/it]

 42%|████▏     | 2506/6015 [48:29<1:08:49,  1.18s/it]

 42%|████▏     | 2507/6015 [48:31<1:08:28,  1.17s/it]

 42%|████▏     | 2508/6015 [48:32<1:08:12,  1.17s/it]

 42%|████▏     | 2509/6015 [48:33<1:07:57,  1.16s/it]

 42%|████▏     | 2510/6015 [48:34<1:07:47,  1.16s/it]

 42%|████▏     | 2511/6015 [48:35<1:07:43,  1.16s/it]

 42%|████▏     | 2512/6015 [48:36<1:07:37,  1.16s/it]

 42%|████▏     | 2513/6015 [48:38<1:07:35,  1.16s/it]

 42%|████▏     | 2514/6015 [48:39<1:07:29,  1.16s/it]

 42%|████▏     | 2515/6015 [48:40<1:07:29,  1.16s/it]

 42%|████▏     | 2516/6015 [48:41<1:07:30,  1.16s/it]

 42%|████▏     | 2517/6015 [48:42<1:07:30,  1.16s/it]

 42%|████▏     | 2518/6015 [48:43<1:07:29,  1.16s/it]

 42%|████▏     | 2519/6015 [48:45<1:07:27,  1.16s/it]

 42%|████▏     | 2520/6015 [48:46<1:07:24,  1.16s/it]

 42%|████▏     | 2521/6015 [48:47<1:07:22,  1.16s/it]

 42%|████▏     | 2522/6015 [48:48<1:07:19,  1.16s/it]

 42%|████▏     | 2523/6015 [48:49<1:07:19,  1.16s/it]

 42%|████▏     | 2524/6015 [48:50<1:07:22,  1.16s/it]

 42%|████▏     | 2525/6015 [48:51<1:07:15,  1.16s/it]

 42%|████▏     | 2526/6015 [48:53<1:07:11,  1.16s/it]

 42%|████▏     | 2527/6015 [48:54<1:07:09,  1.16s/it]

 42%|████▏     | 2528/6015 [48:55<1:07:07,  1.15s/it]

 42%|████▏     | 2529/6015 [48:56<1:07:04,  1.15s/it]

 42%|████▏     | 2530/6015 [48:57<1:07:11,  1.16s/it]

 42%|████▏     | 2531/6015 [48:58<1:07:09,  1.16s/it]

 42%|████▏     | 2532/6015 [49:00<1:07:05,  1.16s/it]

 42%|████▏     | 2533/6015 [49:01<1:07:03,  1.16s/it]

 42%|████▏     | 2534/6015 [49:02<1:07:00,  1.15s/it]

 42%|████▏     | 2535/6015 [49:03<1:07:02,  1.16s/it]

 42%|████▏     | 2536/6015 [49:04<1:07:02,  1.16s/it]

 42%|████▏     | 2537/6015 [49:05<1:07:01,  1.16s/it]

 42%|████▏     | 2538/6015 [49:06<1:06:57,  1.16s/it]

 42%|████▏     | 2539/6015 [49:08<1:06:57,  1.16s/it]

 42%|████▏     | 2540/6015 [49:09<1:07:04,  1.16s/it]

 42%|████▏     | 2541/6015 [49:10<1:07:00,  1.16s/it]

 42%|████▏     | 2542/6015 [49:11<1:06:54,  1.16s/it]

 42%|████▏     | 2543/6015 [49:12<1:06:51,  1.16s/it]

 42%|████▏     | 2544/6015 [49:13<1:06:51,  1.16s/it]

 42%|████▏     | 2545/6015 [49:15<1:06:53,  1.16s/it]

 42%|████▏     | 2546/6015 [49:16<1:06:50,  1.16s/it]

 42%|████▏     | 2547/6015 [49:17<1:06:48,  1.16s/it]

 42%|████▏     | 2548/6015 [49:18<1:06:56,  1.16s/it]

 42%|████▏     | 2549/6015 [49:19<1:06:50,  1.16s/it]

 42%|████▏     | 2550/6015 [49:20<1:06:47,  1.16s/it]

 42%|████▏     | 2551/6015 [49:22<1:06:43,  1.16s/it]

 42%|████▏     | 2552/6015 [49:23<1:06:40,  1.16s/it]

 42%|████▏     | 2553/6015 [49:24<1:06:39,  1.16s/it]

 42%|████▏     | 2554/6015 [49:25<1:06:41,  1.16s/it]

 42%|████▏     | 2555/6015 [49:26<1:06:42,  1.16s/it]

 42%|████▏     | 2556/6015 [49:27<1:06:41,  1.16s/it]

 43%|████▎     | 2557/6015 [49:28<1:06:37,  1.16s/it]

 43%|████▎     | 2558/6015 [49:30<1:06:41,  1.16s/it]

 43%|████▎     | 2559/6015 [49:31<1:06:37,  1.16s/it]

 43%|████▎     | 2560/6015 [49:32<1:06:34,  1.16s/it]

 43%|████▎     | 2561/6015 [49:33<1:06:33,  1.16s/it]

 43%|████▎     | 2562/6015 [49:34<1:06:33,  1.16s/it]

 43%|████▎     | 2563/6015 [49:35<1:06:35,  1.16s/it]

 43%|████▎     | 2564/6015 [49:37<1:06:33,  1.16s/it]

 43%|████▎     | 2565/6015 [49:38<1:06:30,  1.16s/it]

 43%|████▎     | 2566/6015 [49:39<1:06:33,  1.16s/it]

 43%|████▎     | 2567/6015 [49:40<1:06:28,  1.16s/it]

 43%|████▎     | 2568/6015 [49:41<1:06:25,  1.16s/it]

 43%|████▎     | 2569/6015 [49:42<1:06:23,  1.16s/it]

 43%|████▎     | 2570/6015 [49:43<1:06:16,  1.15s/it]

 43%|████▎     | 2571/6015 [49:45<1:06:19,  1.16s/it]

 43%|████▎     | 2572/6015 [49:46<1:06:20,  1.16s/it]

 43%|████▎     | 2573/6015 [49:47<1:06:17,  1.16s/it]

 43%|████▎     | 2574/6015 [49:48<1:06:20,  1.16s/it]

 43%|████▎     | 2575/6015 [49:49<1:06:22,  1.16s/it]

 43%|████▎     | 2576/6015 [49:50<1:06:21,  1.16s/it]

 43%|████▎     | 2577/6015 [49:52<1:06:16,  1.16s/it]

 43%|████▎     | 2578/6015 [49:53<1:06:13,  1.16s/it]

 43%|████▎     | 2579/6015 [49:54<1:06:16,  1.16s/it]

 43%|████▎     | 2580/6015 [49:55<1:06:17,  1.16s/it]

 43%|████▎     | 2581/6015 [49:56<1:06:16,  1.16s/it]

 43%|████▎     | 2582/6015 [49:57<1:06:10,  1.16s/it]

 43%|████▎     | 2583/6015 [49:59<1:06:05,  1.16s/it]

 43%|████▎     | 2584/6015 [50:00<1:06:03,  1.16s/it]

 43%|████▎     | 2585/6015 [50:01<1:06:04,  1.16s/it]

 43%|████▎     | 2586/6015 [50:02<1:06:03,  1.16s/it]

 43%|████▎     | 2587/6015 [50:03<1:06:06,  1.16s/it]

 43%|████▎     | 2588/6015 [50:04<1:06:03,  1.16s/it]

 43%|████▎     | 2589/6015 [50:05<1:06:02,  1.16s/it]

 43%|████▎     | 2590/6015 [50:07<1:05:55,  1.16s/it]

 43%|████▎     | 2591/6015 [50:08<1:05:56,  1.16s/it]

 43%|████▎     | 2592/6015 [50:09<1:05:53,  1.16s/it]

 43%|████▎     | 2593/6015 [50:10<1:05:55,  1.16s/it]

 43%|████▎     | 2594/6015 [50:11<1:05:55,  1.16s/it]

 43%|████▎     | 2595/6015 [50:12<1:05:57,  1.16s/it]

 43%|████▎     | 2596/6015 [50:14<1:05:54,  1.16s/it]

 43%|████▎     | 2597/6015 [50:15<1:05:50,  1.16s/it]

 43%|████▎     | 2598/6015 [50:16<1:05:47,  1.16s/it]

 43%|████▎     | 2599/6015 [50:17<1:05:45,  1.16s/it]

 43%|████▎     | 2600/6015 [50:18<1:05:46,  1.16s/it]

 43%|████▎     | 2601/6015 [50:19<1:05:45,  1.16s/it]

 43%|████▎     | 2602/6015 [50:20<1:05:47,  1.16s/it]

 43%|████▎     | 2603/6015 [50:22<1:05:45,  1.16s/it]

 43%|████▎     | 2604/6015 [50:23<1:05:42,  1.16s/it]

 43%|████▎     | 2605/6015 [50:24<1:05:41,  1.16s/it]

 43%|████▎     | 2606/6015 [50:25<1:05:37,  1.16s/it]

 43%|████▎     | 2607/6015 [50:26<1:05:37,  1.16s/it]

 43%|████▎     | 2608/6015 [50:27<1:05:35,  1.16s/it]

 43%|████▎     | 2609/6015 [50:29<1:05:39,  1.16s/it]

 43%|████▎     | 2610/6015 [50:30<1:05:36,  1.16s/it]

 43%|████▎     | 2611/6015 [50:31<1:05:33,  1.16s/it]

 43%|████▎     | 2612/6015 [50:32<1:05:34,  1.16s/it]

 43%|████▎     | 2613/6015 [50:33<1:05:34,  1.16s/it]

 43%|████▎     | 2614/6015 [50:34<1:05:32,  1.16s/it]

 43%|████▎     | 2615/6015 [50:36<1:05:30,  1.16s/it]

 43%|████▎     | 2616/6015 [50:37<1:05:29,  1.16s/it]

 44%|████▎     | 2617/6015 [50:38<1:05:30,  1.16s/it]

 44%|████▎     | 2618/6015 [50:39<1:05:30,  1.16s/it]

 44%|████▎     | 2619/6015 [50:40<1:05:27,  1.16s/it]

 44%|████▎     | 2620/6015 [50:41<1:05:26,  1.16s/it]

 44%|████▎     | 2621/6015 [50:42<1:05:27,  1.16s/it]

 44%|████▎     | 2622/6015 [50:44<1:05:28,  1.16s/it]

 44%|████▎     | 2623/6015 [50:45<1:05:25,  1.16s/it]

 44%|████▎     | 2624/6015 [50:46<1:05:24,  1.16s/it]

 44%|████▎     | 2625/6015 [50:47<1:05:18,  1.16s/it]

 44%|████▎     | 2626/6015 [50:48<1:05:16,  1.16s/it]

 44%|████▎     | 2627/6015 [50:49<1:05:16,  1.16s/it]

 44%|████▎     | 2628/6015 [50:51<1:05:14,  1.16s/it]

 44%|████▎     | 2629/6015 [50:52<1:05:15,  1.16s/it]

 44%|████▎     | 2630/6015 [50:53<1:05:16,  1.16s/it]

 44%|████▎     | 2631/6015 [50:54<1:05:16,  1.16s/it]

 44%|████▍     | 2632/6015 [50:55<1:05:17,  1.16s/it]

 44%|████▍     | 2633/6015 [50:56<1:05:15,  1.16s/it]

 44%|████▍     | 2634/6015 [50:57<1:05:12,  1.16s/it]

 44%|████▍     | 2635/6015 [50:59<1:05:11,  1.16s/it]

 44%|████▍     | 2636/6015 [51:00<1:05:12,  1.16s/it]

 44%|████▍     | 2637/6015 [51:01<1:05:11,  1.16s/it]

 44%|████▍     | 2638/6015 [51:02<1:05:17,  1.16s/it]

 44%|████▍     | 2639/6015 [51:03<1:05:16,  1.16s/it]

 44%|████▍     | 2640/6015 [51:04<1:05:15,  1.16s/it]

 44%|████▍     | 2641/6015 [51:06<1:05:12,  1.16s/it]

 44%|████▍     | 2642/6015 [51:07<1:05:09,  1.16s/it]

 44%|████▍     | 2643/6015 [51:08<1:05:05,  1.16s/it]

 44%|████▍     | 2644/6015 [51:09<1:05:00,  1.16s/it]

 44%|████▍     | 2645/6015 [51:10<1:05:04,  1.16s/it]

 44%|████▍     | 2646/6015 [51:11<1:04:54,  1.16s/it]

 44%|████▍     | 2647/6015 [51:13<1:04:50,  1.16s/it]

 44%|████▍     | 2648/6015 [51:14<1:04:49,  1.16s/it]

 44%|████▍     | 2649/6015 [51:15<1:04:46,  1.15s/it]

 44%|████▍     | 2650/6015 [51:16<1:04:47,  1.16s/it]

 44%|████▍     | 2651/6015 [51:17<1:04:48,  1.16s/it]

 44%|████▍     | 2652/6015 [51:18<1:04:48,  1.16s/it]

 44%|████▍     | 2653/6015 [51:19<1:04:46,  1.16s/it]

 44%|████▍     | 2654/6015 [51:21<1:04:47,  1.16s/it]

 44%|████▍     | 2655/6015 [51:22<1:04:44,  1.16s/it]

 44%|████▍     | 2656/6015 [51:23<1:04:41,  1.16s/it]

 44%|████▍     | 2657/6015 [51:24<1:04:37,  1.15s/it]

 44%|████▍     | 2658/6015 [51:25<1:04:41,  1.16s/it]

 44%|████▍     | 2659/6015 [51:26<1:04:38,  1.16s/it]

 44%|████▍     | 2660/6015 [51:28<1:04:41,  1.16s/it]

 44%|████▍     | 2661/6015 [51:29<1:04:38,  1.16s/it]

 44%|████▍     | 2662/6015 [51:30<1:04:36,  1.16s/it]

 44%|████▍     | 2663/6015 [51:31<1:04:35,  1.16s/it]

 44%|████▍     | 2664/6015 [51:32<1:04:35,  1.16s/it]

 44%|████▍     | 2665/6015 [51:33<1:04:29,  1.16s/it]

 44%|████▍     | 2666/6015 [51:34<1:04:30,  1.16s/it]

 44%|████▍     | 2667/6015 [51:36<1:04:29,  1.16s/it]

 44%|████▍     | 2668/6015 [51:37<1:04:27,  1.16s/it]

 44%|████▍     | 2669/6015 [51:38<1:04:26,  1.16s/it]

 44%|████▍     | 2670/6015 [51:39<1:04:25,  1.16s/it]

 44%|████▍     | 2671/6015 [51:40<1:04:26,  1.16s/it]

 44%|████▍     | 2672/6015 [51:41<1:04:23,  1.16s/it]

 44%|████▍     | 2673/6015 [51:43<1:04:23,  1.16s/it]

 44%|████▍     | 2674/6015 [51:44<1:04:18,  1.16s/it]

 44%|████▍     | 2675/6015 [51:45<1:04:19,  1.16s/it]

 44%|████▍     | 2676/6015 [51:46<1:04:20,  1.16s/it]

 45%|████▍     | 2677/6015 [51:47<1:04:20,  1.16s/it]

 45%|████▍     | 2678/6015 [51:48<1:04:20,  1.16s/it]

 45%|████▍     | 2679/6015 [51:50<1:04:18,  1.16s/it]

 45%|████▍     | 2680/6015 [51:51<1:04:17,  1.16s/it]

 45%|████▍     | 2681/6015 [51:52<1:04:14,  1.16s/it]

 45%|████▍     | 2682/6015 [51:53<1:04:12,  1.16s/it]

 45%|████▍     | 2683/6015 [51:54<1:04:11,  1.16s/it]

 45%|████▍     | 2684/6015 [51:55<1:04:10,  1.16s/it]

 45%|████▍     | 2685/6015 [51:56<1:04:13,  1.16s/it]

 45%|████▍     | 2686/6015 [51:58<1:04:15,  1.16s/it]

 45%|████▍     | 2687/6015 [51:59<1:04:11,  1.16s/it]

 45%|████▍     | 2688/6015 [52:00<1:04:09,  1.16s/it]

 45%|████▍     | 2689/6015 [52:01<1:04:10,  1.16s/it]

 45%|████▍     | 2690/6015 [52:02<1:04:07,  1.16s/it]

 45%|████▍     | 2691/6015 [52:03<1:04:04,  1.16s/it]

 45%|████▍     | 2692/6015 [52:05<1:04:01,  1.16s/it]

 45%|████▍     | 2693/6015 [52:06<1:04:00,  1.16s/it]

 45%|████▍     | 2694/6015 [52:07<1:04:04,  1.16s/it]

 45%|████▍     | 2695/6015 [52:08<1:04:05,  1.16s/it]

 45%|████▍     | 2696/6015 [52:09<1:04:03,  1.16s/it]

 45%|████▍     | 2697/6015 [52:10<1:04:01,  1.16s/it]

 45%|████▍     | 2698/6015 [52:12<1:03:59,  1.16s/it]

 45%|████▍     | 2699/6015 [52:13<1:03:55,  1.16s/it]

 45%|████▍     | 2700/6015 [52:14<1:03:55,  1.16s/it]

 45%|████▍     | 2701/6015 [52:15<1:03:54,  1.16s/it]

 45%|████▍     | 2702/6015 [52:16<1:03:53,  1.16s/it]

 45%|████▍     | 2703/6015 [52:17<1:03:50,  1.16s/it]

 45%|████▍     | 2704/6015 [52:18<1:03:51,  1.16s/it]

 45%|████▍     | 2705/6015 [52:20<1:03:50,  1.16s/it]

 45%|████▍     | 2706/6015 [52:21<1:03:49,  1.16s/it]

 45%|████▌     | 2707/6015 [52:22<1:03:49,  1.16s/it]

 45%|████▌     | 2708/6015 [52:23<1:03:49,  1.16s/it]

 45%|████▌     | 2709/6015 [52:24<1:03:45,  1.16s/it]

 45%|████▌     | 2710/6015 [52:25<1:03:45,  1.16s/it]

 45%|████▌     | 2711/6015 [52:27<1:03:43,  1.16s/it]

 45%|████▌     | 2712/6015 [52:28<1:03:39,  1.16s/it]

 45%|████▌     | 2713/6015 [52:29<1:03:36,  1.16s/it]

 45%|████▌     | 2714/6015 [52:30<1:03:33,  1.16s/it]

 45%|████▌     | 2715/6015 [52:31<1:03:33,  1.16s/it]

 45%|████▌     | 2716/6015 [52:32<1:03:34,  1.16s/it]

 45%|████▌     | 2717/6015 [52:33<1:03:35,  1.16s/it]

 45%|████▌     | 2718/6015 [52:35<1:03:34,  1.16s/it]

 45%|████▌     | 2719/6015 [52:36<1:03:35,  1.16s/it]

 45%|████▌     | 2720/6015 [52:37<1:03:36,  1.16s/it]

 45%|████▌     | 2721/6015 [52:38<1:03:34,  1.16s/it]

 45%|████▌     | 2722/6015 [52:39<1:03:30,  1.16s/it]

 45%|████▌     | 2723/6015 [52:40<1:03:29,  1.16s/it]

 45%|████▌     | 2724/6015 [52:42<1:03:26,  1.16s/it]

 45%|████▌     | 2725/6015 [52:43<1:03:26,  1.16s/it]

 45%|████▌     | 2726/6015 [52:44<1:03:28,  1.16s/it]

 45%|████▌     | 2727/6015 [52:45<1:03:29,  1.16s/it]

 45%|████▌     | 2728/6015 [52:46<1:03:26,  1.16s/it]

 45%|████▌     | 2729/6015 [52:47<1:03:27,  1.16s/it]

 45%|████▌     | 2730/6015 [52:49<1:03:26,  1.16s/it]

 45%|████▌     | 2731/6015 [52:50<1:03:24,  1.16s/it]

 45%|████▌     | 2732/6015 [52:51<1:03:21,  1.16s/it]

 45%|████▌     | 2733/6015 [52:52<1:03:19,  1.16s/it]

 45%|████▌     | 2734/6015 [52:53<1:03:17,  1.16s/it]

 45%|████▌     | 2735/6015 [52:54<1:03:18,  1.16s/it]

 45%|████▌     | 2736/6015 [52:55<1:03:19,  1.16s/it]

 46%|████▌     | 2737/6015 [52:57<1:03:18,  1.16s/it]

 46%|████▌     | 2738/6015 [52:58<1:03:14,  1.16s/it]

 46%|████▌     | 2739/6015 [52:59<1:03:13,  1.16s/it]

 46%|████▌     | 2740/6015 [53:00<1:03:12,  1.16s/it]

 46%|████▌     | 2741/6015 [53:01<1:03:08,  1.16s/it]

 46%|████▌     | 2742/6015 [53:02<1:03:06,  1.16s/it]

 46%|████▌     | 2743/6015 [53:04<1:03:07,  1.16s/it]

 46%|████▌     | 2744/6015 [53:05<1:03:03,  1.16s/it]

 46%|████▌     | 2745/6015 [53:06<1:03:02,  1.16s/it]

 46%|████▌     | 2746/6015 [53:07<1:03:04,  1.16s/it]

 46%|████▌     | 2747/6015 [53:08<1:02:59,  1.16s/it]

 46%|████▌     | 2748/6015 [53:09<1:02:59,  1.16s/it]

 46%|████▌     | 2749/6015 [53:11<1:02:57,  1.16s/it]

 46%|████▌     | 2750/6015 [53:12<1:02:59,  1.16s/it]

 46%|████▌     | 2751/6015 [53:13<1:02:57,  1.16s/it]

 46%|████▌     | 2752/6015 [53:14<1:02:55,  1.16s/it]

 46%|████▌     | 2753/6015 [53:15<1:02:58,  1.16s/it]

 46%|████▌     | 2754/6015 [53:16<1:02:59,  1.16s/it]

 46%|████▌     | 2755/6015 [53:17<1:02:58,  1.16s/it]

 46%|████▌     | 2756/6015 [53:19<1:02:58,  1.16s/it]

 46%|████▌     | 2757/6015 [53:20<1:02:52,  1.16s/it]

 46%|████▌     | 2758/6015 [53:21<1:02:54,  1.16s/it]

 46%|████▌     | 2759/6015 [53:22<1:02:48,  1.16s/it]

 46%|████▌     | 2760/6015 [53:23<1:02:46,  1.16s/it]

 46%|████▌     | 2761/6015 [53:24<1:02:45,  1.16s/it]

 46%|████▌     | 2762/6015 [53:26<1:02:44,  1.16s/it]

 46%|████▌     | 2763/6015 [53:27<1:02:42,  1.16s/it]

 46%|████▌     | 2764/6015 [53:28<1:02:40,  1.16s/it]

 46%|████▌     | 2765/6015 [53:29<1:02:39,  1.16s/it]

 46%|████▌     | 2766/6015 [53:30<1:02:37,  1.16s/it]

 46%|████▌     | 2767/6015 [53:31<1:02:36,  1.16s/it]

 46%|████▌     | 2768/6015 [53:33<1:02:40,  1.16s/it]

 46%|████▌     | 2769/6015 [53:34<1:02:41,  1.16s/it]

 46%|████▌     | 2770/6015 [53:35<1:02:40,  1.16s/it]

 46%|████▌     | 2771/6015 [53:36<1:02:38,  1.16s/it]

 46%|████▌     | 2772/6015 [53:37<1:02:36,  1.16s/it]

 46%|████▌     | 2773/6015 [53:38<1:02:33,  1.16s/it]

 46%|████▌     | 2774/6015 [53:39<1:02:29,  1.16s/it]

 46%|████▌     | 2775/6015 [53:41<1:02:25,  1.16s/it]

 46%|████▌     | 2776/6015 [53:42<1:02:26,  1.16s/it]

 46%|████▌     | 2777/6015 [53:43<1:02:25,  1.16s/it]

 46%|████▌     | 2778/6015 [53:44<1:02:25,  1.16s/it]

 46%|████▌     | 2779/6015 [53:45<1:02:23,  1.16s/it]

 46%|████▌     | 2780/6015 [53:46<1:02:24,  1.16s/it]

 46%|████▌     | 2781/6015 [53:48<1:02:20,  1.16s/it]

 46%|████▋     | 2782/6015 [53:49<1:02:22,  1.16s/it]

 46%|████▋     | 2783/6015 [53:50<1:02:16,  1.16s/it]

 46%|████▋     | 2784/6015 [53:51<1:02:16,  1.16s/it]

 46%|████▋     | 2785/6015 [53:52<1:02:12,  1.16s/it]

 46%|████▋     | 2786/6015 [53:53<1:02:15,  1.16s/it]

 46%|████▋     | 2787/6015 [53:55<1:02:17,  1.16s/it]

 46%|████▋     | 2788/6015 [53:56<1:02:17,  1.16s/it]

 46%|████▋     | 2789/6015 [53:57<1:02:19,  1.16s/it]

 46%|████▋     | 2790/6015 [53:58<1:02:15,  1.16s/it]

 46%|████▋     | 2791/6015 [53:59<1:02:17,  1.16s/it]

 46%|████▋     | 2792/6015 [54:00<1:02:17,  1.16s/it]

 46%|████▋     | 2793/6015 [54:01<1:02:13,  1.16s/it]

 46%|████▋     | 2794/6015 [54:03<1:02:12,  1.16s/it]

 46%|████▋     | 2795/6015 [54:04<1:02:08,  1.16s/it]

 46%|████▋     | 2796/6015 [54:05<1:02:10,  1.16s/it]

 47%|████▋     | 2797/6015 [54:06<1:02:10,  1.16s/it]

 47%|████▋     | 2798/6015 [54:07<1:02:11,  1.16s/it]

 47%|████▋     | 2799/6015 [54:08<1:02:10,  1.16s/it]

 47%|████▋     | 2800/6015 [54:10<1:02:14,  1.16s/it]

 47%|████▋     | 2801/6015 [54:11<1:02:09,  1.16s/it]

 47%|████▋     | 2802/6015 [54:12<1:02:09,  1.16s/it]

 47%|████▋     | 2803/6015 [54:13<1:02:08,  1.16s/it]

 47%|████▋     | 2804/6015 [54:14<1:02:02,  1.16s/it]

 47%|████▋     | 2805/6015 [54:15<1:01:59,  1.16s/it]

 47%|████▋     | 2806/6015 [54:17<1:01:58,  1.16s/it]

 47%|████▋     | 2807/6015 [54:18<1:01:55,  1.16s/it]

 47%|████▋     | 2808/6015 [54:19<1:02:02,  1.16s/it]

 47%|████▋     | 2809/6015 [54:20<1:02:02,  1.16s/it]

 47%|████▋     | 2810/6015 [54:21<1:02:00,  1.16s/it]

 47%|████▋     | 2811/6015 [54:22<1:01:59,  1.16s/it]

 47%|████▋     | 2812/6015 [54:24<1:01:57,  1.16s/it]

 47%|████▋     | 2813/6015 [54:25<1:01:56,  1.16s/it]

 47%|████▋     | 2814/6015 [54:26<1:01:56,  1.16s/it]

 47%|████▋     | 2815/6015 [54:27<1:01:55,  1.16s/it]

 47%|████▋     | 2816/6015 [54:28<1:01:52,  1.16s/it]

 47%|████▋     | 2817/6015 [54:29<1:01:48,  1.16s/it]

 47%|████▋     | 2818/6015 [54:30<1:01:44,  1.16s/it]

 47%|████▋     | 2819/6015 [54:32<1:01:43,  1.16s/it]

 47%|████▋     | 2820/6015 [54:33<1:01:40,  1.16s/it]

 47%|████▋     | 2821/6015 [54:34<1:01:38,  1.16s/it]

 47%|████▋     | 2822/6015 [54:35<1:01:38,  1.16s/it]

 47%|████▋     | 2823/6015 [54:36<1:01:37,  1.16s/it]

 47%|████▋     | 2824/6015 [54:37<1:01:35,  1.16s/it]

 47%|████▋     | 2825/6015 [54:39<1:01:37,  1.16s/it]

 47%|████▋     | 2826/6015 [54:40<1:01:37,  1.16s/it]

 47%|████▋     | 2827/6015 [54:41<1:01:35,  1.16s/it]

 47%|████▋     | 2828/6015 [54:42<1:01:31,  1.16s/it]

 47%|████▋     | 2829/6015 [54:43<1:01:33,  1.16s/it]

 47%|████▋     | 2830/6015 [54:44<1:01:30,  1.16s/it]

 47%|████▋     | 2831/6015 [54:46<1:01:30,  1.16s/it]

 47%|████▋     | 2832/6015 [54:47<1:01:28,  1.16s/it]

 47%|████▋     | 2833/6015 [54:48<1:01:30,  1.16s/it]

 47%|████▋     | 2834/6015 [54:49<1:01:28,  1.16s/it]

 47%|████▋     | 2835/6015 [54:50<1:01:26,  1.16s/it]

 47%|████▋     | 2836/6015 [54:51<1:01:24,  1.16s/it]

 47%|████▋     | 2837/6015 [54:53<1:01:27,  1.16s/it]

 47%|████▋     | 2838/6015 [54:54<1:01:24,  1.16s/it]

 47%|████▋     | 2839/6015 [54:55<1:01:21,  1.16s/it]

 47%|████▋     | 2840/6015 [54:56<1:01:21,  1.16s/it]

 47%|████▋     | 2841/6015 [54:57<1:01:16,  1.16s/it]

 47%|████▋     | 2842/6015 [54:58<1:01:15,  1.16s/it]

 47%|████▋     | 2843/6015 [54:59<1:01:16,  1.16s/it]

 47%|████▋     | 2844/6015 [55:01<1:01:16,  1.16s/it]

 47%|████▋     | 2845/6015 [55:02<1:01:13,  1.16s/it]

 47%|████▋     | 2846/6015 [55:03<1:01:15,  1.16s/it]

 47%|████▋     | 2847/6015 [55:04<1:01:15,  1.16s/it]

 47%|████▋     | 2848/6015 [55:05<1:01:13,  1.16s/it]

 47%|████▋     | 2849/6015 [55:06<1:01:08,  1.16s/it]

 47%|████▋     | 2850/6015 [55:08<1:01:08,  1.16s/it]

 47%|████▋     | 2851/6015 [55:09<1:01:06,  1.16s/it]

 47%|████▋     | 2852/6015 [55:10<1:01:03,  1.16s/it]

 47%|████▋     | 2853/6015 [55:11<1:01:04,  1.16s/it]

 47%|████▋     | 2854/6015 [55:12<1:01:05,  1.16s/it]

 47%|████▋     | 2855/6015 [55:13<1:01:04,  1.16s/it]

 47%|████▋     | 2856/6015 [55:15<1:01:01,  1.16s/it]

 47%|████▋     | 2857/6015 [55:16<1:00:59,  1.16s/it]

 48%|████▊     | 2858/6015 [55:17<1:00:58,  1.16s/it]

 48%|████▊     | 2859/6015 [55:18<1:00:57,  1.16s/it]

 48%|████▊     | 2860/6015 [55:19<1:00:56,  1.16s/it]

 48%|████▊     | 2861/6015 [55:20<1:00:54,  1.16s/it]

 48%|████▊     | 2862/6015 [55:21<1:00:56,  1.16s/it]

 48%|████▊     | 2863/6015 [55:23<1:00:56,  1.16s/it]

 48%|████▊     | 2864/6015 [55:24<1:00:57,  1.16s/it]

 48%|████▊     | 2865/6015 [55:25<1:00:56,  1.16s/it]

 48%|████▊     | 2866/6015 [55:26<1:00:57,  1.16s/it]

 48%|████▊     | 2867/6015 [55:27<1:00:57,  1.16s/it]

 48%|████▊     | 2868/6015 [55:28<1:01:01,  1.16s/it]

 48%|████▊     | 2869/6015 [55:30<1:00:53,  1.16s/it]

 48%|████▊     | 2870/6015 [55:31<1:00:48,  1.16s/it]

 48%|████▊     | 2871/6015 [55:32<1:00:45,  1.16s/it]

 48%|████▊     | 2872/6015 [55:33<1:00:44,  1.16s/it]

 48%|████▊     | 2873/6015 [55:34<1:00:42,  1.16s/it]

 48%|████▊     | 2874/6015 [55:35<1:00:40,  1.16s/it]

 48%|████▊     | 2875/6015 [55:37<1:00:38,  1.16s/it]

 48%|████▊     | 2876/6015 [55:38<1:00:39,  1.16s/it]

 48%|████▊     | 2877/6015 [55:39<1:00:36,  1.16s/it]

 48%|████▊     | 2878/6015 [55:40<1:00:35,  1.16s/it]

 48%|████▊     | 2879/6015 [55:41<1:00:36,  1.16s/it]

 48%|████▊     | 2880/6015 [55:42<1:00:38,  1.16s/it]

 48%|████▊     | 2881/6015 [55:44<1:00:35,  1.16s/it]

 48%|████▊     | 2882/6015 [55:45<1:00:33,  1.16s/it]

 48%|████▊     | 2883/6015 [55:46<1:00:33,  1.16s/it]

 48%|████▊     | 2884/6015 [55:47<1:00:32,  1.16s/it]

 48%|████▊     | 2885/6015 [55:48<1:00:31,  1.16s/it]

 48%|████▊     | 2886/6015 [55:49<1:00:26,  1.16s/it]

 48%|████▊     | 2887/6015 [55:50<1:00:25,  1.16s/it]

 48%|████▊     | 2888/6015 [55:52<1:00:24,  1.16s/it]

 48%|████▊     | 2889/6015 [55:53<1:00:25,  1.16s/it]

 48%|████▊     | 2890/6015 [55:54<1:00:24,  1.16s/it]

 48%|████▊     | 2891/6015 [55:55<1:00:22,  1.16s/it]

 48%|████▊     | 2892/6015 [55:56<1:00:22,  1.16s/it]

 48%|████▊     | 2893/6015 [55:57<1:00:26,  1.16s/it]

 48%|████▊     | 2894/6015 [55:59<1:00:23,  1.16s/it]

 48%|████▊     | 2895/6015 [56:00<1:00:20,  1.16s/it]

 48%|████▊     | 2896/6015 [56:01<1:00:19,  1.16s/it]

 48%|████▊     | 2897/6015 [56:02<1:00:15,  1.16s/it]

 48%|████▊     | 2898/6015 [56:03<1:00:13,  1.16s/it]

 48%|████▊     | 2899/6015 [56:04<1:00:14,  1.16s/it]

 48%|████▊     | 2900/6015 [56:06<1:00:12,  1.16s/it]

 48%|████▊     | 2901/6015 [56:07<1:00:11,  1.16s/it]

 48%|████▊     | 2902/6015 [56:08<1:00:11,  1.16s/it]

 48%|████▊     | 2903/6015 [56:09<1:00:07,  1.16s/it]

 48%|████▊     | 2904/6015 [56:10<1:00:08,  1.16s/it]

 48%|████▊     | 2905/6015 [56:11<1:00:03,  1.16s/it]

 48%|████▊     | 2906/6015 [56:13<1:00:05,  1.16s/it]

 48%|████▊     | 2907/6015 [56:14<1:00:01,  1.16s/it]

 48%|████▊     | 2908/6015 [56:15<1:00:00,  1.16s/it]

 48%|████▊     | 2909/6015 [56:16<59:59,  1.16s/it]

 48%|████▊     | 2910/6015 [56:17<1:00:01,  1.16s/it]

 48%|████▊     | 2911/6015 [56:18<1:00:01,  1.16s/it]

 48%|████▊     | 2912/6015 [56:19<1:00:04,  1.16s/it]

 48%|████▊     | 2913/6015 [56:21<1:00:03,  1.16s/it]

 48%|████▊     | 2914/6015 [56:22<1:00:01,  1.16s/it]

 48%|████▊     | 2915/6015 [56:23<59:55,  1.16s/it]

 48%|████▊     | 2916/6015 [56:24<59:55,  1.16s/it]

 48%|████▊     | 2917/6015 [56:25<59:53,  1.16s/it]

 49%|████▊     | 2918/6015 [56:26<59:52,  1.16s/it]

 49%|████▊     | 2919/6015 [56:28<59:50,  1.16s/it]

 49%|████▊     | 2920/6015 [56:29<59:48,  1.16s/it]

 49%|████▊     | 2921/6015 [56:30<59:46,  1.16s/it]

 49%|████▊     | 2922/6015 [56:31<59:45,  1.16s/it]

 49%|████▊     | 2923/6015 [56:32<59:44,  1.16s/it]

 49%|████▊     | 2924/6015 [56:33<59:44,  1.16s/it]

 49%|████▊     | 2925/6015 [56:35<59:48,  1.16s/it]

 49%|████▊     | 2926/6015 [56:36<59:52,  1.16s/it]

 49%|████▊     | 2927/6015 [56:37<59:50,  1.16s/it]

 49%|████▊     | 2928/6015 [56:38<59:46,  1.16s/it]

 49%|████▊     | 2929/6015 [56:39<59:45,  1.16s/it]

 49%|████▊     | 2930/6015 [56:40<59:43,  1.16s/it]

 49%|████▊     | 2931/6015 [56:42<59:44,  1.16s/it]

 49%|████▊     | 2932/6015 [56:43<59:42,  1.16s/it]

 49%|████▉     | 2933/6015 [56:44<59:38,  1.16s/it]

 49%|████▉     | 2934/6015 [56:45<59:37,  1.16s/it]

 49%|████▉     | 2935/6015 [56:46<59:32,  1.16s/it]

 49%|████▉     | 2936/6015 [56:47<59:28,  1.16s/it]

 49%|████▉     | 2937/6015 [56:48<59:27,  1.16s/it]

 49%|████▉     | 2938/6015 [56:50<59:28,  1.16s/it]

 49%|████▉     | 2939/6015 [56:51<59:26,  1.16s/it]

 49%|████▉     | 2940/6015 [56:52<59:26,  1.16s/it]

 49%|████▉     | 2941/6015 [56:53<59:26,  1.16s/it]

 49%|████▉     | 2942/6015 [56:54<59:25,  1.16s/it]

 49%|████▉     | 2943/6015 [56:55<59:24,  1.16s/it]

 49%|████▉     | 2944/6015 [56:57<59:20,  1.16s/it]

 49%|████▉     | 2945/6015 [56:58<59:19,  1.16s/it]

 49%|████▉     | 2946/6015 [56:59<59:20,  1.16s/it]

 49%|████▉     | 2947/6015 [57:00<59:18,  1.16s/it]

 49%|████▉     | 2948/6015 [57:01<59:15,  1.16s/it]

 49%|████▉     | 2949/6015 [57:02<59:18,  1.16s/it]

 49%|████▉     | 2950/6015 [57:04<59:19,  1.16s/it]

 49%|████▉     | 2951/6015 [57:05<59:16,  1.16s/it]

 49%|████▉     | 2952/6015 [57:06<59:19,  1.16s/it]

 49%|████▉     | 2953/6015 [57:07<59:16,  1.16s/it]

 49%|████▉     | 2954/6015 [57:08<59:17,  1.16s/it]

 49%|████▉     | 2955/6015 [57:09<59:13,  1.16s/it]

 49%|████▉     | 2956/6015 [57:11<59:14,  1.16s/it]

 49%|████▉     | 2957/6015 [57:12<59:12,  1.16s/it]

 49%|████▉     | 2958/6015 [57:13<59:08,  1.16s/it]

 49%|████▉     | 2959/6015 [57:14<59:03,  1.16s/it]

 49%|████▉     | 2960/6015 [57:15<59:04,  1.16s/it]

 49%|████▉     | 2961/6015 [57:16<59:07,  1.16s/it]

 49%|████▉     | 2962/6015 [57:18<59:05,  1.16s/it]

 49%|████▉     | 2963/6015 [57:19<59:01,  1.16s/it]

 49%|████▉     | 2964/6015 [57:20<58:57,  1.16s/it]

 49%|████▉     | 2965/6015 [57:21<59:00,  1.16s/it]

 49%|████▉     | 2966/6015 [57:22<59:01,  1.16s/it]

 49%|████▉     | 2967/6015 [57:23<58:59,  1.16s/it]

 49%|████▉     | 2968/6015 [57:24<58:55,  1.16s/it]

 49%|████▉     | 2969/6015 [57:26<58:53,  1.16s/it]

 49%|████▉     | 2970/6015 [57:27<58:54,  1.16s/it]

 49%|████▉     | 2971/6015 [57:28<58:53,  1.16s/it]

 49%|████▉     | 2972/6015 [57:29<58:52,  1.16s/it]

 49%|████▉     | 2973/6015 [57:30<58:52,  1.16s/it]

 49%|████▉     | 2974/6015 [57:31<58:54,  1.16s/it]

 49%|████▉     | 2975/6015 [57:33<58:52,  1.16s/it]

 49%|████▉     | 2976/6015 [57:34<58:48,  1.16s/it]

 49%|████▉     | 2977/6015 [57:35<58:45,  1.16s/it]

 50%|████▉     | 2978/6015 [57:36<58:48,  1.16s/it]

 50%|████▉     | 2979/6015 [57:37<58:47,  1.16s/it]

 50%|████▉     | 2980/6015 [57:38<58:44,  1.16s/it]

 50%|████▉     | 2981/6015 [57:40<58:40,  1.16s/it]

 50%|████▉     | 2982/6015 [57:41<58:37,  1.16s/it]

 50%|████▉     | 2983/6015 [57:42<58:36,  1.16s/it]

 50%|████▉     | 2984/6015 [57:43<58:38,  1.16s/it]

 50%|████▉     | 2985/6015 [57:44<58:37,  1.16s/it]

 50%|████▉     | 2986/6015 [57:45<58:40,  1.16s/it]

 50%|████▉     | 2987/6015 [57:47<58:41,  1.16s/it]

 50%|████▉     | 2988/6015 [57:48<58:41,  1.16s/it]

 50%|████▉     | 2989/6015 [57:49<58:34,  1.16s/it]

 50%|████▉     | 2990/6015 [57:50<58:32,  1.16s/it]

 50%|████▉     | 2991/6015 [57:51<58:33,  1.16s/it]

 50%|████▉     | 2992/6015 [57:52<58:31,  1.16s/it]

 50%|████▉     | 2993/6015 [57:54<58:30,  1.16s/it]

 50%|████▉     | 2994/6015 [57:55<58:27,  1.16s/it]

 50%|████▉     | 2995/6015 [57:56<58:26,  1.16s/it]

 50%|████▉     | 2996/6015 [57:57<58:28,  1.16s/it]

 50%|████▉     | 2997/6015 [57:58<58:25,  1.16s/it]

 50%|████▉     | 2998/6015 [57:59<58:23,  1.16s/it]

 50%|████▉     | 2999/6015 [58:00<58:19,  1.16s/it]

 50%|████▉     | 3000/6015 [58:02<58:16,  1.16s/it]

 50%|████▉     | 3001/6015 [58:03<58:15,  1.16s/it]

 50%|████▉     | 3002/6015 [58:04<58:13,  1.16s/it]

 50%|████▉     | 3003/6015 [58:05<58:12,  1.16s/it]

 50%|████▉     | 3004/6015 [58:06<58:13,  1.16s/it]

 50%|████▉     | 3005/6015 [58:07<58:15,  1.16s/it]

 50%|████▉     | 3006/6015 [58:09<58:16,  1.16s/it]

 50%|████▉     | 3007/6015 [58:10<58:13,  1.16s/it]

 50%|█████     | 3008/6015 [58:11<58:17,  1.16s/it]

 50%|█████     | 3009/6015 [58:12<58:12,  1.16s/it]

 50%|█████     | 3010/6015 [58:13<58:11,  1.16s/it]

 50%|█████     | 3011/6015 [58:14<58:09,  1.16s/it]

 50%|█████     | 3012/6015 [58:16<58:07,  1.16s/it]

 50%|█████     | 3013/6015 [58:17<58:02,  1.16s/it]

 50%|█████     | 3014/6015 [58:18<58:02,  1.16s/it]

 50%|█████     | 3015/6015 [58:19<58:03,  1.16s/it]

 50%|█████     | 3016/6015 [58:20<58:04,  1.16s/it]

 50%|█████     | 3017/6015 [58:21<58:07,  1.16s/it]

 50%|█████     | 3018/6015 [58:23<58:06,  1.16s/it]

 50%|█████     | 3019/6015 [58:24<58:05,  1.16s/it]

 50%|█████     | 3020/6015 [58:25<58:02,  1.16s/it]

 50%|█████     | 3021/6015 [58:26<58:00,  1.16s/it]

 50%|█████     | 3022/6015 [58:27<57:57,  1.16s/it]

 50%|█████     | 3023/6015 [58:28<57:56,  1.16s/it]

 50%|█████     | 3024/6015 [58:30<57:54,  1.16s/it]

 50%|█████     | 3025/6015 [58:31<57:50,  1.16s/it]

 50%|█████     | 3026/6015 [58:32<57:48,  1.16s/it]

 50%|█████     | 3027/6015 [58:33<57:45,  1.16s/it]

 50%|█████     | 3028/6015 [58:34<57:47,  1.16s/it]

 50%|█████     | 3029/6015 [58:35<57:45,  1.16s/it]

 50%|█████     | 3030/6015 [58:36<57:47,  1.16s/it]

 50%|█████     | 3031/6015 [58:38<57:49,  1.16s/it]

 50%|█████     | 3032/6015 [58:39<57:44,  1.16s/it]

 50%|█████     | 3033/6015 [58:40<57:43,  1.16s/it]

 50%|█████     | 3034/6015 [58:41<57:42,  1.16s/it]

 50%|█████     | 3035/6015 [58:42<57:42,  1.16s/it]

 50%|█████     | 3036/6015 [58:43<57:43,  1.16s/it]

 50%|█████     | 3037/6015 [58:45<57:39,  1.16s/it]

 51%|█████     | 3038/6015 [58:46<57:33,  1.16s/it]

 51%|█████     | 3039/6015 [58:47<57:35,  1.16s/it]

 51%|█████     | 3040/6015 [58:48<57:38,  1.16s/it]

 51%|█████     | 3041/6015 [58:49<57:40,  1.16s/it]

 51%|█████     | 3042/6015 [58:50<57:36,  1.16s/it]

 51%|█████     | 3043/6015 [58:52<57:35,  1.16s/it]

 51%|█████     | 3044/6015 [58:53<57:33,  1.16s/it]

 51%|█████     | 3045/6015 [58:54<57:31,  1.16s/it]

 51%|█████     | 3046/6015 [58:55<57:31,  1.16s/it]

 51%|█████     | 3047/6015 [58:56<57:28,  1.16s/it]

 51%|█████     | 3048/6015 [58:57<57:24,  1.16s/it]

 51%|█████     | 3049/6015 [58:59<57:23,  1.16s/it]

 51%|█████     | 3050/6015 [59:00<57:21,  1.16s/it]

 51%|█████     | 3051/6015 [59:01<57:18,  1.16s/it]

 51%|█████     | 3052/6015 [59:02<57:16,  1.16s/it]

 51%|█████     | 3053/6015 [59:03<57:17,  1.16s/it]

 51%|█████     | 3054/6015 [59:04<57:16,  1.16s/it]

 51%|█████     | 3055/6015 [59:06<57:15,  1.16s/it]

 51%|█████     | 3056/6015 [59:07<57:13,  1.16s/it]

 51%|█████     | 3057/6015 [59:08<57:12,  1.16s/it]

 51%|█████     | 3058/6015 [59:09<57:10,  1.16s/it]

 51%|█████     | 3059/6015 [59:10<57:09,  1.16s/it]

 51%|█████     | 3060/6015 [59:11<57:05,  1.16s/it]

 51%|█████     | 3061/6015 [59:12<57:07,  1.16s/it]

 51%|█████     | 3062/6015 [59:14<57:06,  1.16s/it]

 51%|█████     | 3063/6015 [59:15<57:00,  1.16s/it]

 51%|█████     | 3064/6015 [59:16<56:59,  1.16s/it]

 51%|█████     | 3065/6015 [59:17<57:01,  1.16s/it]

 51%|█████     | 3066/6015 [59:18<57:00,  1.16s/it]

 51%|█████     | 3067/6015 [59:19<56:59,  1.16s/it]

 51%|█████     | 3068/6015 [59:21<56:59,  1.16s/it]

 51%|█████     | 3069/6015 [59:22<57:01,  1.16s/it]

 51%|█████     | 3070/6015 [59:23<57:00,  1.16s/it]

 51%|█████     | 3071/6015 [59:24<57:01,  1.16s/it]

 51%|█████     | 3072/6015 [59:25<56:56,  1.16s/it]

 51%|█████     | 3073/6015 [59:26<56:53,  1.16s/it]

 51%|█████     | 3074/6015 [59:28<56:51,  1.16s/it]

 51%|█████     | 3075/6015 [59:29<56:52,  1.16s/it]

 51%|█████     | 3076/6015 [59:30<56:50,  1.16s/it]

 51%|█████     | 3077/6015 [59:31<56:51,  1.16s/it]

 51%|█████     | 3078/6015 [59:32<56:51,  1.16s/it]

 51%|█████     | 3079/6015 [59:33<56:52,  1.16s/it]

 51%|█████     | 3080/6015 [59:35<56:52,  1.16s/it]

 51%|█████     | 3081/6015 [59:36<56:51,  1.16s/it]

 51%|█████     | 3082/6015 [59:37<56:54,  1.16s/it]

 51%|█████▏    | 3083/6015 [59:38<56:53,  1.16s/it]

 51%|█████▏    | 3084/6015 [59:39<56:51,  1.16s/it]

 51%|█████▏    | 3085/6015 [59:40<56:46,  1.16s/it]

 51%|█████▏    | 3086/6015 [59:42<56:40,  1.16s/it]

 51%|█████▏    | 3087/6015 [59:43<56:39,  1.16s/it]

 51%|█████▏    | 3088/6015 [59:44<56:37,  1.16s/it]

 51%|█████▏    | 3089/6015 [59:45<56:35,  1.16s/it]

 51%|█████▏    | 3090/6015 [59:46<56:36,  1.16s/it]

 51%|█████▏    | 3091/6015 [59:47<56:36,  1.16s/it]

 51%|█████▏    | 3092/6015 [59:48<56:38,  1.16s/it]

 51%|█████▏    | 3093/6015 [59:50<56:35,  1.16s/it]

 51%|█████▏    | 3094/6015 [59:51<56:37,  1.16s/it]

 51%|█████▏    | 3095/6015 [59:52<56:38,  1.16s/it]

 51%|█████▏    | 3096/6015 [59:53<56:34,  1.16s/it]

 51%|█████▏    | 3097/6015 [59:54<56:30,  1.16s/it]

 52%|█████▏    | 3098/6015 [59:55<56:31,  1.16s/it]

 52%|█████▏    | 3099/6015 [59:57<56:28,  1.16s/it]

 52%|█████▏    | 3100/6015 [59:58<56:29,  1.16s/it]

 52%|█████▏    | 3101/6015 [59:59<56:26,  1.16s/it]

 52%|█████▏    | 3102/6015 [1:00:00<56:23,  1.16s/it]

 52%|█████▏    | 3103/6015 [1:00:01<56:24,  1.16s/it]

 52%|█████▏    | 3104/6015 [1:00:02<56:21,  1.16s/it]

 52%|█████▏    | 3105/6015 [1:00:04<56:18,  1.16s/it]

 52%|█████▏    | 3106/6015 [1:00:05<56:19,  1.16s/it]

 52%|█████▏    | 3107/6015 [1:00:06<56:21,  1.16s/it]

 52%|█████▏    | 3108/6015 [1:00:07<56:18,  1.16s/it]

 52%|█████▏    | 3109/6015 [1:00:08<56:21,  1.16s/it]

 52%|█████▏    | 3110/6015 [1:00:09<56:23,  1.16s/it]

 52%|█████▏    | 3111/6015 [1:00:11<56:21,  1.16s/it]

 52%|█████▏    | 3112/6015 [1:00:12<56:20,  1.16s/it]

 52%|█████▏    | 3113/6015 [1:00:13<56:22,  1.17s/it]

 52%|█████▏    | 3114/6015 [1:00:14<56:20,  1.17s/it]

 52%|█████▏    | 3115/6015 [1:00:15<56:14,  1.16s/it]

 52%|█████▏    | 3116/6015 [1:00:16<56:11,  1.16s/it]

 52%|█████▏    | 3117/6015 [1:00:18<56:05,  1.16s/it]

 52%|█████▏    | 3118/6015 [1:00:19<56:04,  1.16s/it]

 52%|█████▏    | 3119/6015 [1:00:20<56:02,  1.16s/it]

 52%|█████▏    | 3120/6015 [1:00:21<56:00,  1.16s/it]

 52%|█████▏    | 3121/6015 [1:00:22<56:00,  1.16s/it]

 52%|█████▏    | 3122/6015 [1:00:23<55:59,  1.16s/it]

 52%|█████▏    | 3123/6015 [1:00:25<56:00,  1.16s/it]

 52%|█████▏    | 3124/6015 [1:00:26<56:05,  1.16s/it]

 52%|█████▏    | 3125/6015 [1:00:27<56:27,  1.17s/it]

 52%|█████▏    | 3126/6015 [1:00:28<56:17,  1.17s/it]

 52%|█████▏    | 3127/6015 [1:00:29<56:08,  1.17s/it]

 52%|█████▏    | 3128/6015 [1:00:30<56:07,  1.17s/it]

 52%|█████▏    | 3129/6015 [1:00:32<56:06,  1.17s/it]

logging
logging the anndata

 52%|█████▏    | 3130/6015 [1:00:33<59:00,  1.23s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 52%|█████▏    | 3131/6015 [1:00:34<57:56,  1.21s/it]

 52%|█████▏    | 3132/6015 [1:00:35<57:16,  1.19s/it]

 52%|█████▏    | 3133/6015 [1:00:36<56:41,  1.18s/it]

 52%|█████▏    | 3134/6015 [1:00:38<56:17,  1.17s/it]

 52%|█████▏    | 3135/6015 [1:00:39<56:00,  1.17s/it]

 52%|█████▏    | 3136/6015 [1:00:40<55:49,  1.16s/it]

 52%|█████▏    | 3137/6015 [1:00:41<55:40,  1.16s/it]

 52%|█████▏    | 3138/6015 [1:00:42<55:35,  1.16s/it]

 52%|█████▏    | 3139/6015 [1:00:43<55:29,  1.16s/it]

 52%|█████▏    | 3140/6015 [1:00:44<55:26,  1.16s/it]

 52%|█████▏    | 3141/6015 [1:00:46<55:22,  1.16s/it]

 52%|█████▏    | 3142/6015 [1:00:47<55:22,  1.16s/it]

 52%|█████▏    | 3143/6015 [1:00:48<55:15,  1.15s/it]

 52%|█████▏    | 3144/6015 [1:00:49<55:22,  1.16s/it]

 52%|█████▏    | 3145/6015 [1:00:50<55:19,  1.16s/it]

 52%|█████▏    | 3146/6015 [1:00:51<55:18,  1.16s/it]

 52%|█████▏    | 3147/6015 [1:00:53<55:16,  1.16s/it]

 52%|█████▏    | 3148/6015 [1:00:54<55:16,  1.16s/it]

 52%|█████▏    | 3149/6015 [1:00:55<55:16,  1.16s/it]

 52%|█████▏    | 3150/6015 [1:00:56<55:13,  1.16s/it]

 52%|█████▏    | 3151/6015 [1:00:57<55:08,  1.16s/it]

 52%|█████▏    | 3152/6015 [1:00:58<55:06,  1.15s/it]

 52%|█████▏    | 3153/6015 [1:00:59<55:02,  1.15s/it]

 52%|█████▏    | 3154/6015 [1:01:01<55:04,  1.15s/it]

 52%|█████▏    | 3155/6015 [1:01:02<55:05,  1.16s/it]

 52%|█████▏    | 3156/6015 [1:01:03<55:07,  1.16s/it]

 52%|█████▏    | 3157/6015 [1:01:04<55:07,  1.16s/it]

 53%|█████▎    | 3158/6015 [1:01:05<55:06,  1.16s/it]

 53%|█████▎    | 3159/6015 [1:01:06<55:02,  1.16s/it]

 53%|█████▎    | 3160/6015 [1:01:08<55:01,  1.16s/it]

 53%|█████▎    | 3161/6015 [1:01:09<55:02,  1.16s/it]

 53%|█████▎    | 3162/6015 [1:01:10<55:02,  1.16s/it]

 53%|█████▎    | 3163/6015 [1:01:11<54:57,  1.16s/it]

 53%|█████▎    | 3164/6015 [1:01:12<54:57,  1.16s/it]

 53%|█████▎    | 3165/6015 [1:01:13<54:51,  1.16s/it]

 53%|█████▎    | 3166/6015 [1:01:15<54:50,  1.16s/it]

 53%|█████▎    | 3167/6015 [1:01:16<54:50,  1.16s/it]

 53%|█████▎    | 3168/6015 [1:01:17<54:47,  1.15s/it]

 53%|█████▎    | 3169/6015 [1:01:18<54:47,  1.15s/it]

 53%|█████▎    | 3170/6015 [1:01:19<54:44,  1.15s/it]

 53%|█████▎    | 3171/6015 [1:01:20<54:42,  1.15s/it]

 53%|█████▎    | 3172/6015 [1:01:21<54:44,  1.16s/it]

 53%|█████▎    | 3173/6015 [1:01:23<54:41,  1.15s/it]

 53%|█████▎    | 3174/6015 [1:01:24<54:40,  1.15s/it]

 53%|█████▎    | 3175/6015 [1:01:25<54:38,  1.15s/it]

 53%|█████▎    | 3176/6015 [1:01:26<54:39,  1.16s/it]

 53%|█████▎    | 3177/6015 [1:01:27<54:35,  1.15s/it]

 53%|█████▎    | 3178/6015 [1:01:28<54:37,  1.16s/it]

 53%|█████▎    | 3179/6015 [1:01:30<54:34,  1.15s/it]

 53%|█████▎    | 3180/6015 [1:01:31<54:35,  1.16s/it]

 53%|█████▎    | 3181/6015 [1:01:32<54:32,  1.15s/it]

 53%|█████▎    | 3182/6015 [1:01:33<54:30,  1.15s/it]

 53%|█████▎    | 3183/6015 [1:01:34<54:30,  1.15s/it]

 53%|█████▎    | 3184/6015 [1:01:35<54:31,  1.16s/it]

 53%|█████▎    | 3185/6015 [1:01:36<54:31,  1.16s/it]

 53%|█████▎    | 3186/6015 [1:01:38<54:32,  1.16s/it]

 53%|█████▎    | 3187/6015 [1:01:39<54:30,  1.16s/it]

 53%|█████▎    | 3188/6015 [1:01:40<54:27,  1.16s/it]

 53%|█████▎    | 3189/6015 [1:01:41<54:25,  1.16s/it]

 53%|█████▎    | 3190/6015 [1:01:42<54:25,  1.16s/it]

 53%|█████▎    | 3191/6015 [1:01:43<54:27,  1.16s/it]

 53%|█████▎    | 3192/6015 [1:01:45<54:25,  1.16s/it]

 53%|█████▎    | 3193/6015 [1:01:46<54:21,  1.16s/it]

 53%|█████▎    | 3194/6015 [1:01:47<54:19,  1.16s/it]

 53%|█████▎    | 3195/6015 [1:01:48<54:22,  1.16s/it]

 53%|█████▎    | 3196/6015 [1:01:49<54:18,  1.16s/it]

 53%|█████▎    | 3197/6015 [1:01:50<54:21,  1.16s/it]

 53%|█████▎    | 3198/6015 [1:01:51<54:15,  1.16s/it]

 53%|█████▎    | 3199/6015 [1:01:53<54:14,  1.16s/it]

 53%|█████▎    | 3200/6015 [1:01:54<54:12,  1.16s/it]

 53%|█████▎    | 3201/6015 [1:01:55<54:13,  1.16s/it]

 53%|█████▎    | 3202/6015 [1:01:56<54:12,  1.16s/it]

 53%|█████▎    | 3203/6015 [1:01:57<54:13,  1.16s/it]

 53%|█████▎    | 3204/6015 [1:01:58<54:10,  1.16s/it]

 53%|█████▎    | 3205/6015 [1:02:00<54:08,  1.16s/it]

 53%|█████▎    | 3206/6015 [1:02:01<54:05,  1.16s/it]

 53%|█████▎    | 3207/6015 [1:02:02<54:04,  1.16s/it]

 53%|█████▎    | 3208/6015 [1:02:03<54:03,  1.16s/it]

 53%|█████▎    | 3209/6015 [1:02:04<54:05,  1.16s/it]

 53%|█████▎    | 3210/6015 [1:02:05<54:04,  1.16s/it]

 53%|█████▎    | 3211/6015 [1:02:07<54:00,  1.16s/it]

 53%|█████▎    | 3212/6015 [1:02:08<53:58,  1.16s/it]

 53%|█████▎    | 3213/6015 [1:02:09<53:58,  1.16s/it]

 53%|█████▎    | 3214/6015 [1:02:10<54:02,  1.16s/it]

 53%|█████▎    | 3215/6015 [1:02:11<54:00,  1.16s/it]

 53%|█████▎    | 3216/6015 [1:02:12<53:56,  1.16s/it]

 53%|█████▎    | 3217/6015 [1:02:13<53:54,  1.16s/it]

 53%|█████▎    | 3218/6015 [1:02:15<53:54,  1.16s/it]

 54%|█████▎    | 3219/6015 [1:02:16<53:53,  1.16s/it]

 54%|█████▎    | 3220/6015 [1:02:17<53:53,  1.16s/it]

 54%|█████▎    | 3221/6015 [1:02:18<53:50,  1.16s/it]

 54%|█████▎    | 3222/6015 [1:02:19<53:51,  1.16s/it]

 54%|█████▎    | 3223/6015 [1:02:20<53:50,  1.16s/it]

 54%|█████▎    | 3224/6015 [1:02:22<53:49,  1.16s/it]

 54%|█████▎    | 3225/6015 [1:02:23<53:48,  1.16s/it]

 54%|█████▎    | 3226/6015 [1:02:24<53:46,  1.16s/it]

 54%|█████▎    | 3227/6015 [1:02:25<53:43,  1.16s/it]

 54%|█████▎    | 3228/6015 [1:02:26<53:41,  1.16s/it]

 54%|█████▎    | 3229/6015 [1:02:27<53:39,  1.16s/it]

 54%|█████▎    | 3230/6015 [1:02:28<53:39,  1.16s/it]

 54%|█████▎    | 3231/6015 [1:02:30<53:38,  1.16s/it]

 54%|█████▎    | 3232/6015 [1:02:31<53:37,  1.16s/it]

 54%|█████▎    | 3233/6015 [1:02:32<53:38,  1.16s/it]

 54%|█████▍    | 3234/6015 [1:02:33<53:39,  1.16s/it]

 54%|█████▍    | 3235/6015 [1:02:34<53:33,  1.16s/it]

 54%|█████▍    | 3236/6015 [1:02:35<53:31,  1.16s/it]

 54%|█████▍    | 3237/6015 [1:02:37<53:29,  1.16s/it]

 54%|█████▍    | 3238/6015 [1:02:38<53:30,  1.16s/it]

 54%|█████▍    | 3239/6015 [1:02:39<53:29,  1.16s/it]

 54%|█████▍    | 3240/6015 [1:02:40<53:30,  1.16s/it]

 54%|█████▍    | 3241/6015 [1:02:41<53:29,  1.16s/it]

 54%|█████▍    | 3242/6015 [1:02:42<53:27,  1.16s/it]

 54%|█████▍    | 3243/6015 [1:02:44<53:26,  1.16s/it]

 54%|█████▍    | 3244/6015 [1:02:45<53:25,  1.16s/it]

 54%|█████▍    | 3245/6015 [1:02:46<53:24,  1.16s/it]

 54%|█████▍    | 3246/6015 [1:02:47<53:17,  1.15s/it]

 54%|█████▍    | 3247/6015 [1:02:48<53:19,  1.16s/it]

 54%|█████▍    | 3248/6015 [1:02:49<53:20,  1.16s/it]

 54%|█████▍    | 3249/6015 [1:02:50<53:21,  1.16s/it]

 54%|█████▍    | 3250/6015 [1:02:52<53:21,  1.16s/it]

 54%|█████▍    | 3251/6015 [1:02:53<53:20,  1.16s/it]

 54%|█████▍    | 3252/6015 [1:02:54<53:19,  1.16s/it]

 54%|█████▍    | 3253/6015 [1:02:55<53:17,  1.16s/it]

 54%|█████▍    | 3254/6015 [1:02:56<53:17,  1.16s/it]

 54%|█████▍    | 3255/6015 [1:02:57<53:14,  1.16s/it]

 54%|█████▍    | 3256/6015 [1:02:59<53:15,  1.16s/it]

 54%|█████▍    | 3257/6015 [1:03:00<53:14,  1.16s/it]

 54%|█████▍    | 3258/6015 [1:03:01<53:10,  1.16s/it]

 54%|█████▍    | 3259/6015 [1:03:02<53:10,  1.16s/it]

 54%|█████▍    | 3260/6015 [1:03:03<53:12,  1.16s/it]

 54%|█████▍    | 3261/6015 [1:03:04<53:10,  1.16s/it]

 54%|█████▍    | 3262/6015 [1:03:06<53:07,  1.16s/it]

 54%|█████▍    | 3263/6015 [1:03:07<53:02,  1.16s/it]

 54%|█████▍    | 3264/6015 [1:03:08<53:02,  1.16s/it]

 54%|█████▍    | 3265/6015 [1:03:09<53:00,  1.16s/it]

 54%|█████▍    | 3266/6015 [1:03:10<52:59,  1.16s/it]

 54%|█████▍    | 3267/6015 [1:03:11<52:56,  1.16s/it]

 54%|█████▍    | 3268/6015 [1:03:12<52:58,  1.16s/it]

 54%|█████▍    | 3269/6015 [1:03:14<52:58,  1.16s/it]

 54%|█████▍    | 3270/6015 [1:03:15<52:54,  1.16s/it]

 54%|█████▍    | 3271/6015 [1:03:16<52:57,  1.16s/it]

 54%|█████▍    | 3272/6015 [1:03:17<52:55,  1.16s/it]

 54%|█████▍    | 3273/6015 [1:03:18<52:53,  1.16s/it]

 54%|█████▍    | 3274/6015 [1:03:19<52:49,  1.16s/it]

 54%|█████▍    | 3275/6015 [1:03:21<52:48,  1.16s/it]

 54%|█████▍    | 3276/6015 [1:03:22<52:51,  1.16s/it]

 54%|█████▍    | 3277/6015 [1:03:23<52:48,  1.16s/it]

 54%|█████▍    | 3278/6015 [1:03:24<52:43,  1.16s/it]

 55%|█████▍    | 3279/6015 [1:03:25<52:40,  1.16s/it]

 55%|█████▍    | 3280/6015 [1:03:26<52:39,  1.16s/it]

 55%|█████▍    | 3281/6015 [1:03:27<52:39,  1.16s/it]

 55%|█████▍    | 3282/6015 [1:03:29<52:38,  1.16s/it]

 55%|█████▍    | 3283/6015 [1:03:30<52:40,  1.16s/it]

 55%|█████▍    | 3284/6015 [1:03:31<52:39,  1.16s/it]

 55%|█████▍    | 3285/6015 [1:03:32<52:38,  1.16s/it]

 55%|█████▍    | 3286/6015 [1:03:33<52:33,  1.16s/it]

 55%|█████▍    | 3287/6015 [1:03:34<52:32,  1.16s/it]

 55%|█████▍    | 3288/6015 [1:03:36<52:32,  1.16s/it]

 55%|█████▍    | 3289/6015 [1:03:37<52:30,  1.16s/it]

 55%|█████▍    | 3290/6015 [1:03:38<52:30,  1.16s/it]

 55%|█████▍    | 3291/6015 [1:03:39<52:28,  1.16s/it]

 55%|█████▍    | 3292/6015 [1:03:40<52:28,  1.16s/it]

 55%|█████▍    | 3293/6015 [1:03:41<52:27,  1.16s/it]

 55%|█████▍    | 3294/6015 [1:03:43<52:28,  1.16s/it]

 55%|█████▍    | 3295/6015 [1:03:44<52:24,  1.16s/it]

 55%|█████▍    | 3296/6015 [1:03:45<52:22,  1.16s/it]

 55%|█████▍    | 3297/6015 [1:03:46<52:20,  1.16s/it]

 55%|█████▍    | 3298/6015 [1:03:47<52:24,  1.16s/it]

 55%|█████▍    | 3299/6015 [1:03:48<52:23,  1.16s/it]

 55%|█████▍    | 3300/6015 [1:03:49<52:21,  1.16s/it]

 55%|█████▍    | 3301/6015 [1:03:51<52:20,  1.16s/it]

 55%|█████▍    | 3302/6015 [1:03:52<52:20,  1.16s/it]

 55%|█████▍    | 3303/6015 [1:03:53<52:17,  1.16s/it]

 55%|█████▍    | 3304/6015 [1:03:54<52:14,  1.16s/it]

 55%|█████▍    | 3305/6015 [1:03:55<52:09,  1.15s/it]

 55%|█████▍    | 3306/6015 [1:03:56<52:09,  1.16s/it]

 55%|█████▍    | 3307/6015 [1:03:58<52:09,  1.16s/it]

 55%|█████▍    | 3308/6015 [1:03:59<52:10,  1.16s/it]

 55%|█████▌    | 3309/6015 [1:04:00<52:11,  1.16s/it]

 55%|█████▌    | 3310/6015 [1:04:01<52:16,  1.16s/it]

 55%|█████▌    | 3311/6015 [1:04:02<52:12,  1.16s/it]

 55%|█████▌    | 3312/6015 [1:04:03<52:11,  1.16s/it]

 55%|█████▌    | 3313/6015 [1:04:05<52:09,  1.16s/it]

 55%|█████▌    | 3314/6015 [1:04:06<52:05,  1.16s/it]

 55%|█████▌    | 3315/6015 [1:04:07<52:05,  1.16s/it]

 55%|█████▌    | 3316/6015 [1:04:08<52:05,  1.16s/it]

 55%|█████▌    | 3317/6015 [1:04:09<52:03,  1.16s/it]

 55%|█████▌    | 3318/6015 [1:04:10<52:02,  1.16s/it]

 55%|█████▌    | 3319/6015 [1:04:11<52:00,  1.16s/it]

 55%|█████▌    | 3320/6015 [1:04:13<52:03,  1.16s/it]

 55%|█████▌    | 3321/6015 [1:04:14<51:59,  1.16s/it]

 55%|█████▌    | 3322/6015 [1:04:15<51:59,  1.16s/it]

 55%|█████▌    | 3323/6015 [1:04:16<51:54,  1.16s/it]

 55%|█████▌    | 3324/6015 [1:04:17<51:53,  1.16s/it]

 55%|█████▌    | 3325/6015 [1:04:18<51:49,  1.16s/it]

 55%|█████▌    | 3326/6015 [1:04:20<51:47,  1.16s/it]

 55%|█████▌    | 3327/6015 [1:04:21<51:50,  1.16s/it]

 55%|█████▌    | 3328/6015 [1:04:22<51:48,  1.16s/it]

 55%|█████▌    | 3329/6015 [1:04:23<51:49,  1.16s/it]

 55%|█████▌    | 3330/6015 [1:04:24<51:49,  1.16s/it]

 55%|█████▌    | 3331/6015 [1:04:25<51:50,  1.16s/it]

 55%|█████▌    | 3332/6015 [1:04:26<51:45,  1.16s/it]

 55%|█████▌    | 3333/6015 [1:04:28<51:47,  1.16s/it]

 55%|█████▌    | 3334/6015 [1:04:29<51:45,  1.16s/it]

 55%|█████▌    | 3335/6015 [1:04:30<51:42,  1.16s/it]

 55%|█████▌    | 3336/6015 [1:04:31<51:40,  1.16s/it]

 55%|█████▌    | 3337/6015 [1:04:32<51:36,  1.16s/it]

 55%|█████▌    | 3338/6015 [1:04:33<51:36,  1.16s/it]

 56%|█████▌    | 3339/6015 [1:04:35<51:33,  1.16s/it]

 56%|█████▌    | 3340/6015 [1:04:36<51:32,  1.16s/it]

 56%|█████▌    | 3341/6015 [1:04:37<51:32,  1.16s/it]

 56%|█████▌    | 3342/6015 [1:04:38<51:31,  1.16s/it]

 56%|█████▌    | 3343/6015 [1:04:39<51:32,  1.16s/it]

 56%|█████▌    | 3344/6015 [1:04:40<51:29,  1.16s/it]

 56%|█████▌    | 3345/6015 [1:04:42<51:27,  1.16s/it]

 56%|█████▌    | 3346/6015 [1:04:43<51:27,  1.16s/it]

 56%|█████▌    | 3347/6015 [1:04:44<51:25,  1.16s/it]

 56%|█████▌    | 3348/6015 [1:04:45<51:26,  1.16s/it]

 56%|█████▌    | 3349/6015 [1:04:46<51:25,  1.16s/it]

 56%|█████▌    | 3350/6015 [1:04:47<51:23,  1.16s/it]

 56%|█████▌    | 3351/6015 [1:04:48<51:22,  1.16s/it]

 56%|█████▌    | 3352/6015 [1:04:50<51:19,  1.16s/it]

 56%|█████▌    | 3353/6015 [1:04:51<51:15,  1.16s/it]

 56%|█████▌    | 3354/6015 [1:04:52<51:12,  1.15s/it]

 56%|█████▌    | 3355/6015 [1:04:53<51:12,  1.16s/it]

 56%|█████▌    | 3356/6015 [1:04:54<51:14,  1.16s/it]

 56%|█████▌    | 3357/6015 [1:04:55<51:15,  1.16s/it]

 56%|█████▌    | 3358/6015 [1:04:57<51:15,  1.16s/it]

 56%|█████▌    | 3359/6015 [1:04:58<51:15,  1.16s/it]

 56%|█████▌    | 3360/6015 [1:04:59<51:11,  1.16s/it]

 56%|█████▌    | 3361/6015 [1:05:00<51:12,  1.16s/it]

 56%|█████▌    | 3362/6015 [1:05:01<51:10,  1.16s/it]

 56%|█████▌    | 3363/6015 [1:05:02<51:08,  1.16s/it]

 56%|█████▌    | 3364/6015 [1:05:04<51:06,  1.16s/it]

 56%|█████▌    | 3365/6015 [1:05:05<51:06,  1.16s/it]

 56%|█████▌    | 3366/6015 [1:05:06<51:05,  1.16s/it]

 56%|█████▌    | 3367/6015 [1:05:07<51:16,  1.16s/it]

 56%|█████▌    | 3368/6015 [1:05:08<53:26,  1.21s/it]

 56%|█████▌    | 3369/6015 [1:05:09<52:42,  1.20s/it]

 56%|█████▌    | 3370/6015 [1:05:11<52:13,  1.18s/it]

 56%|█████▌    | 3371/6015 [1:05:12<51:53,  1.18s/it]

 56%|█████▌    | 3372/6015 [1:05:13<51:35,  1.17s/it]

 56%|█████▌    | 3373/6015 [1:05:14<51:23,  1.17s/it]

 56%|█████▌    | 3374/6015 [1:05:15<51:15,  1.16s/it]

 56%|█████▌    | 3375/6015 [1:05:16<51:08,  1.16s/it]

 56%|█████▌    | 3376/6015 [1:05:18<51:43,  1.18s/it]

 56%|█████▌    | 3377/6015 [1:05:19<51:27,  1.17s/it]

 56%|█████▌    | 3378/6015 [1:05:20<51:15,  1.17s/it]

 56%|█████▌    | 3379/6015 [1:05:21<51:06,  1.16s/it]

 56%|█████▌    | 3380/6015 [1:05:22<51:02,  1.16s/it]

 56%|█████▌    | 3381/6015 [1:05:23<50:55,  1.16s/it]

 56%|█████▌    | 3382/6015 [1:05:25<50:54,  1.16s/it]

 56%|█████▌    | 3383/6015 [1:05:26<50:56,  1.16s/it]

 56%|█████▋    | 3384/6015 [1:05:27<50:51,  1.16s/it]

 56%|█████▋    | 3385/6015 [1:05:28<50:49,  1.16s/it]

 56%|█████▋    | 3386/6015 [1:05:29<50:46,  1.16s/it]

 56%|█████▋    | 3387/6015 [1:05:30<50:41,  1.16s/it]

 56%|█████▋    | 3388/6015 [1:05:32<50:44,  1.16s/it]

 56%|█████▋    | 3389/6015 [1:05:33<50:44,  1.16s/it]

 56%|█████▋    | 3390/6015 [1:05:34<50:46,  1.16s/it]

 56%|█████▋    | 3391/6015 [1:05:35<50:45,  1.16s/it]

 56%|█████▋    | 3392/6015 [1:05:36<50:44,  1.16s/it]

 56%|█████▋    | 3393/6015 [1:05:37<50:44,  1.16s/it]

 56%|█████▋    | 3394/6015 [1:05:39<50:43,  1.16s/it]

 56%|█████▋    | 3395/6015 [1:05:40<50:39,  1.16s/it]

 56%|█████▋    | 3396/6015 [1:05:41<50:39,  1.16s/it]

 56%|█████▋    | 3397/6015 [1:05:42<50:37,  1.16s/it]

 56%|█████▋    | 3398/6015 [1:05:43<50:37,  1.16s/it]

 57%|█████▋    | 3399/6015 [1:05:44<50:31,  1.16s/it]

 57%|█████▋    | 3400/6015 [1:05:45<50:31,  1.16s/it]

 57%|█████▋    | 3401/6015 [1:05:47<50:24,  1.16s/it]

 57%|█████▋    | 3402/6015 [1:05:48<50:22,  1.16s/it]

 57%|█████▋    | 3403/6015 [1:05:49<50:22,  1.16s/it]

 57%|█████▋    | 3404/6015 [1:05:50<50:22,  1.16s/it]

 57%|█████▋    | 3405/6015 [1:05:51<50:21,  1.16s/it]

 57%|█████▋    | 3406/6015 [1:05:52<50:21,  1.16s/it]

 57%|█████▋    | 3407/6015 [1:05:54<50:22,  1.16s/it]

 57%|█████▋    | 3408/6015 [1:05:55<50:20,  1.16s/it]

 57%|█████▋    | 3409/6015 [1:05:56<50:17,  1.16s/it]

 57%|█████▋    | 3410/6015 [1:05:57<50:16,  1.16s/it]

 57%|█████▋    | 3411/6015 [1:05:58<50:12,  1.16s/it]

 57%|█████▋    | 3412/6015 [1:05:59<50:11,  1.16s/it]

 57%|█████▋    | 3413/6015 [1:06:01<50:09,  1.16s/it]

 57%|█████▋    | 3414/6015 [1:06:02<50:09,  1.16s/it]

 57%|█████▋    | 3415/6015 [1:06:03<50:08,  1.16s/it]

 57%|█████▋    | 3416/6015 [1:06:04<50:10,  1.16s/it]

 57%|█████▋    | 3417/6015 [1:06:05<50:11,  1.16s/it]

 57%|█████▋    | 3418/6015 [1:06:06<50:09,  1.16s/it]

 57%|█████▋    | 3419/6015 [1:06:07<50:08,  1.16s/it]

 57%|█████▋    | 3420/6015 [1:06:09<50:08,  1.16s/it]

 57%|█████▋    | 3421/6015 [1:06:10<50:03,  1.16s/it]

 57%|█████▋    | 3422/6015 [1:06:11<50:02,  1.16s/it]

 57%|█████▋    | 3423/6015 [1:06:12<50:02,  1.16s/it]

 57%|█████▋    | 3424/6015 [1:06:13<50:02,  1.16s/it]

 57%|█████▋    | 3425/6015 [1:06:14<50:01,  1.16s/it]

 57%|█████▋    | 3426/6015 [1:06:16<50:01,  1.16s/it]

 57%|█████▋    | 3427/6015 [1:06:17<49:58,  1.16s/it]

 57%|█████▋    | 3428/6015 [1:06:18<49:59,  1.16s/it]

 57%|█████▋    | 3429/6015 [1:06:19<49:57,  1.16s/it]

 57%|█████▋    | 3430/6015 [1:06:20<49:57,  1.16s/it]

 57%|█████▋    | 3431/6015 [1:06:21<49:55,  1.16s/it]

 57%|█████▋    | 3432/6015 [1:06:23<49:52,  1.16s/it]

 57%|█████▋    | 3433/6015 [1:06:24<49:48,  1.16s/it]

 57%|█████▋    | 3434/6015 [1:06:25<49:48,  1.16s/it]

 57%|█████▋    | 3435/6015 [1:06:26<49:49,  1.16s/it]

 57%|█████▋    | 3436/6015 [1:06:27<49:47,  1.16s/it]

 57%|█████▋    | 3437/6015 [1:06:28<49:47,  1.16s/it]

 57%|█████▋    | 3438/6015 [1:06:29<49:47,  1.16s/it]

 57%|█████▋    | 3439/6015 [1:06:31<49:46,  1.16s/it]

 57%|█████▋    | 3440/6015 [1:06:32<49:45,  1.16s/it]

 57%|█████▋    | 3441/6015 [1:06:33<49:44,  1.16s/it]

 57%|█████▋    | 3442/6015 [1:06:34<49:41,  1.16s/it]

 57%|█████▋    | 3443/6015 [1:06:35<49:38,  1.16s/it]

 57%|█████▋    | 3444/6015 [1:06:36<49:37,  1.16s/it]

 57%|█████▋    | 3445/6015 [1:06:38<49:38,  1.16s/it]

 57%|█████▋    | 3446/6015 [1:06:39<49:43,  1.16s/it]

 57%|█████▋    | 3447/6015 [1:06:40<49:40,  1.16s/it]

 57%|█████▋    | 3448/6015 [1:06:41<49:39,  1.16s/it]

 57%|█████▋    | 3449/6015 [1:06:42<49:37,  1.16s/it]

 57%|█████▋    | 3450/6015 [1:06:43<49:34,  1.16s/it]

 57%|█████▋    | 3451/6015 [1:06:45<49:35,  1.16s/it]

 57%|█████▋    | 3452/6015 [1:06:46<49:34,  1.16s/it]

 57%|█████▋    | 3453/6015 [1:06:47<49:29,  1.16s/it]

 57%|█████▋    | 3454/6015 [1:06:48<49:28,  1.16s/it]

 57%|█████▋    | 3455/6015 [1:06:49<49:24,  1.16s/it]

 57%|█████▋    | 3456/6015 [1:06:50<49:23,  1.16s/it]

 57%|█████▋    | 3457/6015 [1:06:52<49:24,  1.16s/it]

 57%|█████▋    | 3458/6015 [1:06:53<49:26,  1.16s/it]

 58%|█████▊    | 3459/6015 [1:06:54<49:23,  1.16s/it]

 58%|█████▊    | 3460/6015 [1:06:55<49:24,  1.16s/it]

 58%|█████▊    | 3461/6015 [1:06:56<49:20,  1.16s/it]

 58%|█████▊    | 3462/6015 [1:06:57<49:23,  1.16s/it]

 58%|█████▊    | 3463/6015 [1:06:58<49:19,  1.16s/it]

 58%|█████▊    | 3464/6015 [1:07:00<49:18,  1.16s/it]

 58%|█████▊    | 3465/6015 [1:07:01<49:15,  1.16s/it]

 58%|█████▊    | 3466/6015 [1:07:02<49:13,  1.16s/it]

 58%|█████▊    | 3467/6015 [1:07:03<49:14,  1.16s/it]

 58%|█████▊    | 3468/6015 [1:07:04<49:11,  1.16s/it]

 58%|█████▊    | 3469/6015 [1:07:05<49:09,  1.16s/it]

 58%|█████▊    | 3470/6015 [1:07:07<49:10,  1.16s/it]

 58%|█████▊    | 3471/6015 [1:07:08<49:09,  1.16s/it]

 58%|█████▊    | 3472/6015 [1:07:09<49:09,  1.16s/it]

 58%|█████▊    | 3473/6015 [1:07:10<49:08,  1.16s/it]

 58%|█████▊    | 3474/6015 [1:07:11<49:06,  1.16s/it]

 58%|█████▊    | 3475/6015 [1:07:12<49:04,  1.16s/it]

 58%|█████▊    | 3476/6015 [1:07:14<49:01,  1.16s/it]

 58%|█████▊    | 3477/6015 [1:07:15<48:59,  1.16s/it]

 58%|█████▊    | 3478/6015 [1:07:16<49:00,  1.16s/it]

 58%|█████▊    | 3479/6015 [1:07:17<49:03,  1.16s/it]

 58%|█████▊    | 3480/6015 [1:07:18<49:02,  1.16s/it]

 58%|█████▊    | 3481/6015 [1:07:19<49:00,  1.16s/it]

 58%|█████▊    | 3482/6015 [1:07:20<48:59,  1.16s/it]

 58%|█████▊    | 3483/6015 [1:07:22<49:00,  1.16s/it]

 58%|█████▊    | 3484/6015 [1:07:23<48:59,  1.16s/it]

 58%|█████▊    | 3485/6015 [1:07:24<48:56,  1.16s/it]

 58%|█████▊    | 3486/6015 [1:07:25<48:53,  1.16s/it]

 58%|█████▊    | 3487/6015 [1:07:26<48:50,  1.16s/it]

 58%|█████▊    | 3488/6015 [1:07:27<48:48,  1.16s/it]

 58%|█████▊    | 3489/6015 [1:07:29<48:50,  1.16s/it]

 58%|█████▊    | 3490/6015 [1:07:30<48:48,  1.16s/it]

 58%|█████▊    | 3491/6015 [1:07:31<48:48,  1.16s/it]

 58%|█████▊    | 3492/6015 [1:07:32<48:45,  1.16s/it]

 58%|█████▊    | 3493/6015 [1:07:33<48:45,  1.16s/it]

 58%|█████▊    | 3494/6015 [1:07:34<48:46,  1.16s/it]

 58%|█████▊    | 3495/6015 [1:07:36<48:44,  1.16s/it]

 58%|█████▊    | 3496/6015 [1:07:37<48:41,  1.16s/it]

 58%|█████▊    | 3497/6015 [1:07:38<48:40,  1.16s/it]

 58%|█████▊    | 3498/6015 [1:07:39<48:40,  1.16s/it]

 58%|█████▊    | 3499/6015 [1:07:40<48:38,  1.16s/it]

 58%|█████▊    | 3500/6015 [1:07:41<48:36,  1.16s/it]

 58%|█████▊    | 3501/6015 [1:07:43<48:35,  1.16s/it]

 58%|█████▊    | 3502/6015 [1:07:44<48:35,  1.16s/it]

 58%|█████▊    | 3503/6015 [1:07:45<48:34,  1.16s/it]

 58%|█████▊    | 3504/6015 [1:07:46<48:37,  1.16s/it]

 58%|█████▊    | 3505/6015 [1:07:47<48:37,  1.16s/it]

 58%|█████▊    | 3506/6015 [1:07:48<48:31,  1.16s/it]

 58%|█████▊    | 3507/6015 [1:07:50<48:29,  1.16s/it]

 58%|█████▊    | 3508/6015 [1:07:51<48:31,  1.16s/it]

 58%|█████▊    | 3509/6015 [1:07:52<48:30,  1.16s/it]

 58%|█████▊    | 3510/6015 [1:07:53<48:28,  1.16s/it]

 58%|█████▊    | 3511/6015 [1:07:54<48:24,  1.16s/it]

 58%|█████▊    | 3512/6015 [1:07:55<48:22,  1.16s/it]

 58%|█████▊    | 3513/6015 [1:07:56<48:20,  1.16s/it]

 58%|█████▊    | 3514/6015 [1:07:58<48:18,  1.16s/it]

 58%|█████▊    | 3515/6015 [1:07:59<48:19,  1.16s/it]

 58%|█████▊    | 3516/6015 [1:08:00<48:19,  1.16s/it]

 58%|█████▊    | 3517/6015 [1:08:01<48:17,  1.16s/it]

 58%|█████▊    | 3518/6015 [1:08:02<48:19,  1.16s/it]

 59%|█████▊    | 3519/6015 [1:08:03<48:16,  1.16s/it]

 59%|█████▊    | 3520/6015 [1:08:05<48:14,  1.16s/it]

 59%|█████▊    | 3521/6015 [1:08:06<48:19,  1.16s/it]

 59%|█████▊    | 3522/6015 [1:08:07<48:16,  1.16s/it]

 59%|█████▊    | 3523/6015 [1:08:08<48:15,  1.16s/it]

 59%|█████▊    | 3524/6015 [1:08:09<48:12,  1.16s/it]

 59%|█████▊    | 3525/6015 [1:08:10<48:09,  1.16s/it]

 59%|█████▊    | 3526/6015 [1:08:12<48:05,  1.16s/it]

 59%|█████▊    | 3527/6015 [1:08:13<48:05,  1.16s/it]

 59%|█████▊    | 3528/6015 [1:08:14<48:04,  1.16s/it]

 59%|█████▊    | 3529/6015 [1:08:15<48:01,  1.16s/it]

 59%|█████▊    | 3530/6015 [1:08:16<48:02,  1.16s/it]

 59%|█████▊    | 3531/6015 [1:08:17<48:03,  1.16s/it]

 59%|█████▊    | 3532/6015 [1:08:19<48:02,  1.16s/it]

 59%|█████▊    | 3533/6015 [1:08:20<48:05,  1.16s/it]

 59%|█████▉    | 3534/6015 [1:08:21<48:05,  1.16s/it]

 59%|█████▉    | 3535/6015 [1:08:22<48:01,  1.16s/it]

 59%|█████▉    | 3536/6015 [1:08:23<47:58,  1.16s/it]

 59%|█████▉    | 3537/6015 [1:08:24<47:58,  1.16s/it]

 59%|█████▉    | 3538/6015 [1:08:25<47:55,  1.16s/it]

 59%|█████▉    | 3539/6015 [1:08:27<47:54,  1.16s/it]

 59%|█████▉    | 3540/6015 [1:08:28<47:55,  1.16s/it]

 59%|█████▉    | 3541/6015 [1:08:29<47:50,  1.16s/it]

 59%|█████▉    | 3542/6015 [1:08:30<47:51,  1.16s/it]

 59%|█████▉    | 3543/6015 [1:08:31<47:49,  1.16s/it]

 59%|█████▉    | 3544/6015 [1:08:32<47:49,  1.16s/it]

 59%|█████▉    | 3545/6015 [1:08:34<47:49,  1.16s/it]

 59%|█████▉    | 3546/6015 [1:08:35<47:46,  1.16s/it]

 59%|█████▉    | 3547/6015 [1:08:36<47:44,  1.16s/it]

 59%|█████▉    | 3548/6015 [1:08:37<47:38,  1.16s/it]

 59%|█████▉    | 3549/6015 [1:08:38<47:37,  1.16s/it]

 59%|█████▉    | 3550/6015 [1:08:39<47:40,  1.16s/it]

 59%|█████▉    | 3551/6015 [1:08:41<47:43,  1.16s/it]

 59%|█████▉    | 3552/6015 [1:08:42<47:43,  1.16s/it]

 59%|█████▉    | 3553/6015 [1:08:43<47:42,  1.16s/it]

 59%|█████▉    | 3554/6015 [1:08:44<47:41,  1.16s/it]

 59%|█████▉    | 3555/6015 [1:08:45<47:39,  1.16s/it]

 59%|█████▉    | 3556/6015 [1:08:46<47:35,  1.16s/it]

 59%|█████▉    | 3557/6015 [1:08:48<47:33,  1.16s/it]

 59%|█████▉    | 3558/6015 [1:08:49<47:32,  1.16s/it]

 59%|█████▉    | 3559/6015 [1:08:50<47:31,  1.16s/it]

 59%|█████▉    | 3560/6015 [1:08:51<47:27,  1.16s/it]

 59%|█████▉    | 3561/6015 [1:08:52<47:27,  1.16s/it]

 59%|█████▉    | 3562/6015 [1:08:53<47:26,  1.16s/it]

 59%|█████▉    | 3563/6015 [1:08:55<47:27,  1.16s/it]

 59%|█████▉    | 3564/6015 [1:08:56<47:29,  1.16s/it]

 59%|█████▉    | 3565/6015 [1:08:57<47:27,  1.16s/it]

 59%|█████▉    | 3566/6015 [1:08:58<47:27,  1.16s/it]

 59%|█████▉    | 3567/6015 [1:08:59<47:25,  1.16s/it]

 59%|█████▉    | 3568/6015 [1:09:00<47:19,  1.16s/it]

 59%|█████▉    | 3569/6015 [1:09:01<47:18,  1.16s/it]

 59%|█████▉    | 3570/6015 [1:09:03<47:18,  1.16s/it]

 59%|█████▉    | 3571/6015 [1:09:04<47:14,  1.16s/it]

 59%|█████▉    | 3572/6015 [1:09:05<47:13,  1.16s/it]

 59%|█████▉    | 3573/6015 [1:09:06<47:12,  1.16s/it]

 59%|█████▉    | 3574/6015 [1:09:07<47:13,  1.16s/it]

 59%|█████▉    | 3575/6015 [1:09:08<47:12,  1.16s/it]

 59%|█████▉    | 3576/6015 [1:09:10<47:10,  1.16s/it]

 59%|█████▉    | 3577/6015 [1:09:11<47:08,  1.16s/it]

 59%|█████▉    | 3578/6015 [1:09:12<47:08,  1.16s/it]

 60%|█████▉    | 3579/6015 [1:09:13<47:06,  1.16s/it]

 60%|█████▉    | 3580/6015 [1:09:14<47:04,  1.16s/it]

 60%|█████▉    | 3581/6015 [1:09:15<47:02,  1.16s/it]

 60%|█████▉    | 3582/6015 [1:09:17<47:05,  1.16s/it]

 60%|█████▉    | 3583/6015 [1:09:18<47:04,  1.16s/it]

 60%|█████▉    | 3584/6015 [1:09:19<47:04,  1.16s/it]

 60%|█████▉    | 3585/6015 [1:09:20<47:03,  1.16s/it]

 60%|█████▉    | 3586/6015 [1:09:21<47:00,  1.16s/it]

 60%|█████▉    | 3587/6015 [1:09:22<46:59,  1.16s/it]

 60%|█████▉    | 3588/6015 [1:09:24<46:58,  1.16s/it]

 60%|█████▉    | 3589/6015 [1:09:25<46:52,  1.16s/it]

 60%|█████▉    | 3590/6015 [1:09:26<46:51,  1.16s/it]

 60%|█████▉    | 3591/6015 [1:09:27<46:53,  1.16s/it]

 60%|█████▉    | 3592/6015 [1:09:28<46:55,  1.16s/it]

 60%|█████▉    | 3593/6015 [1:09:29<46:57,  1.16s/it]

 60%|█████▉    | 3594/6015 [1:09:31<46:55,  1.16s/it]

 60%|█████▉    | 3595/6015 [1:09:32<46:55,  1.16s/it]

 60%|█████▉    | 3596/6015 [1:09:33<46:55,  1.16s/it]

 60%|█████▉    | 3597/6015 [1:09:34<46:54,  1.16s/it]

 60%|█████▉    | 3598/6015 [1:09:35<46:53,  1.16s/it]

 60%|█████▉    | 3599/6015 [1:09:36<46:50,  1.16s/it]

 60%|█████▉    | 3600/6015 [1:09:37<46:47,  1.16s/it]

 60%|█████▉    | 3601/6015 [1:09:39<46:43,  1.16s/it]

 60%|█████▉    | 3602/6015 [1:09:40<46:42,  1.16s/it]

 60%|█████▉    | 3603/6015 [1:09:41<46:38,  1.16s/it]

 60%|█████▉    | 3604/6015 [1:09:42<46:39,  1.16s/it]

 60%|█████▉    | 3605/6015 [1:09:43<46:39,  1.16s/it]

 60%|█████▉    | 3606/6015 [1:09:44<46:38,  1.16s/it]

 60%|█████▉    | 3607/6015 [1:09:46<46:35,  1.16s/it]

 60%|█████▉    | 3608/6015 [1:09:47<46:32,  1.16s/it]

 60%|██████    | 3609/6015 [1:09:48<46:35,  1.16s/it]

 60%|██████    | 3610/6015 [1:09:49<46:42,  1.17s/it]

 60%|██████    | 3611/6015 [1:09:50<46:37,  1.16s/it]

 60%|██████    | 3612/6015 [1:09:51<46:36,  1.16s/it]

 60%|██████    | 3613/6015 [1:09:53<46:32,  1.16s/it]

 60%|██████    | 3614/6015 [1:09:54<46:27,  1.16s/it]

 60%|██████    | 3615/6015 [1:09:55<46:27,  1.16s/it]

 60%|██████    | 3616/6015 [1:09:56<46:24,  1.16s/it]

 60%|██████    | 3617/6015 [1:09:57<46:24,  1.16s/it]

 60%|██████    | 3618/6015 [1:09:58<46:24,  1.16s/it]

 60%|██████    | 3619/6015 [1:10:00<46:27,  1.16s/it]

 60%|██████    | 3620/6015 [1:10:01<46:27,  1.16s/it]

 60%|██████    | 3621/6015 [1:10:02<46:26,  1.16s/it]

 60%|██████    | 3622/6015 [1:10:03<46:26,  1.16s/it]

 60%|██████    | 3623/6015 [1:10:04<46:25,  1.16s/it]

 60%|██████    | 3624/6015 [1:10:05<46:24,  1.16s/it]

 60%|██████    | 3625/6015 [1:10:07<46:22,  1.16s/it]

 60%|██████    | 3626/6015 [1:10:08<46:18,  1.16s/it]

 60%|██████    | 3627/6015 [1:10:09<46:14,  1.16s/it]

 60%|██████    | 3628/6015 [1:10:10<46:13,  1.16s/it]

 60%|██████    | 3629/6015 [1:10:11<46:14,  1.16s/it]

 60%|██████    | 3630/6015 [1:10:12<46:11,  1.16s/it]

 60%|██████    | 3631/6015 [1:10:14<46:10,  1.16s/it]

 60%|██████    | 3632/6015 [1:10:15<46:06,  1.16s/it]

 60%|██████    | 3633/6015 [1:10:16<46:01,  1.16s/it]

 60%|██████    | 3634/6015 [1:10:17<46:01,  1.16s/it]

 60%|██████    | 3635/6015 [1:10:18<46:01,  1.16s/it]

 60%|██████    | 3636/6015 [1:10:19<46:01,  1.16s/it]

 60%|██████    | 3637/6015 [1:10:20<46:00,  1.16s/it]

 60%|██████    | 3638/6015 [1:10:22<46:00,  1.16s/it]

 60%|██████    | 3639/6015 [1:10:23<45:57,  1.16s/it]

 61%|██████    | 3640/6015 [1:10:24<45:59,  1.16s/it]

 61%|██████    | 3641/6015 [1:10:25<46:01,  1.16s/it]

 61%|██████    | 3642/6015 [1:10:26<45:58,  1.16s/it]

 61%|██████    | 3643/6015 [1:10:27<45:56,  1.16s/it]

 61%|██████    | 3644/6015 [1:10:29<45:53,  1.16s/it]

 61%|██████    | 3645/6015 [1:10:30<45:51,  1.16s/it]

 61%|██████    | 3646/6015 [1:10:31<45:48,  1.16s/it]

 61%|██████    | 3647/6015 [1:10:32<45:48,  1.16s/it]

 61%|██████    | 3648/6015 [1:10:33<45:49,  1.16s/it]

 61%|██████    | 3649/6015 [1:10:34<45:51,  1.16s/it]

 61%|██████    | 3650/6015 [1:10:36<45:52,  1.16s/it]

 61%|██████    | 3651/6015 [1:10:37<45:50,  1.16s/it]

 61%|██████    | 3652/6015 [1:10:38<45:46,  1.16s/it]

 61%|██████    | 3653/6015 [1:10:39<45:44,  1.16s/it]

 61%|██████    | 3654/6015 [1:10:40<45:43,  1.16s/it]

 61%|██████    | 3655/6015 [1:10:41<45:40,  1.16s/it]

 61%|██████    | 3656/6015 [1:10:43<45:39,  1.16s/it]

 61%|██████    | 3657/6015 [1:10:44<45:39,  1.16s/it]

 61%|██████    | 3658/6015 [1:10:45<45:36,  1.16s/it]

 61%|██████    | 3659/6015 [1:10:46<45:34,  1.16s/it]

 61%|██████    | 3660/6015 [1:10:47<45:36,  1.16s/it]

 61%|██████    | 3661/6015 [1:10:48<45:35,  1.16s/it]

 61%|██████    | 3662/6015 [1:10:50<45:34,  1.16s/it]

 61%|██████    | 3663/6015 [1:10:51<45:33,  1.16s/it]

 61%|██████    | 3664/6015 [1:10:52<45:33,  1.16s/it]

 61%|██████    | 3665/6015 [1:10:53<45:31,  1.16s/it]

 61%|██████    | 3666/6015 [1:10:54<45:31,  1.16s/it]

 61%|██████    | 3667/6015 [1:10:55<45:27,  1.16s/it]

 61%|██████    | 3668/6015 [1:10:57<45:27,  1.16s/it]

 61%|██████    | 3669/6015 [1:10:58<45:25,  1.16s/it]

 61%|██████    | 3670/6015 [1:10:59<45:22,  1.16s/it]

 61%|██████    | 3671/6015 [1:11:00<45:20,  1.16s/it]

 61%|██████    | 3672/6015 [1:11:01<45:19,  1.16s/it]

 61%|██████    | 3673/6015 [1:11:02<45:18,  1.16s/it]

 61%|██████    | 3674/6015 [1:11:03<45:16,  1.16s/it]

 61%|██████    | 3675/6015 [1:11:05<45:15,  1.16s/it]

 61%|██████    | 3676/6015 [1:11:06<45:12,  1.16s/it]

 61%|██████    | 3677/6015 [1:11:07<45:17,  1.16s/it]

 61%|██████    | 3678/6015 [1:11:08<45:16,  1.16s/it]

 61%|██████    | 3679/6015 [1:11:09<45:13,  1.16s/it]

 61%|██████    | 3680/6015 [1:11:10<45:13,  1.16s/it]

 61%|██████    | 3681/6015 [1:11:12<45:13,  1.16s/it]

 61%|██████    | 3682/6015 [1:11:13<45:14,  1.16s/it]

 61%|██████    | 3683/6015 [1:11:14<45:13,  1.16s/it]

 61%|██████    | 3684/6015 [1:11:15<45:10,  1.16s/it]

 61%|██████▏   | 3685/6015 [1:11:16<45:07,  1.16s/it]

 61%|██████▏   | 3686/6015 [1:11:17<45:04,  1.16s/it]

 61%|██████▏   | 3687/6015 [1:11:19<45:02,  1.16s/it]

 61%|██████▏   | 3688/6015 [1:11:20<45:02,  1.16s/it]

 61%|██████▏   | 3689/6015 [1:11:21<45:00,  1.16s/it]

 61%|██████▏   | 3690/6015 [1:11:22<44:59,  1.16s/it]

 61%|██████▏   | 3691/6015 [1:11:23<44:58,  1.16s/it]

 61%|██████▏   | 3692/6015 [1:11:24<44:57,  1.16s/it]

 61%|██████▏   | 3693/6015 [1:11:26<44:57,  1.16s/it]

 61%|██████▏   | 3694/6015 [1:11:27<44:56,  1.16s/it]

 61%|██████▏   | 3695/6015 [1:11:28<44:56,  1.16s/it]

 61%|██████▏   | 3696/6015 [1:11:29<44:53,  1.16s/it]

 61%|██████▏   | 3697/6015 [1:11:30<44:53,  1.16s/it]

 61%|██████▏   | 3698/6015 [1:11:31<44:51,  1.16s/it]

 61%|██████▏   | 3699/6015 [1:11:33<44:49,  1.16s/it]

 62%|██████▏   | 3700/6015 [1:11:34<44:47,  1.16s/it]

 62%|██████▏   | 3701/6015 [1:11:35<44:48,  1.16s/it]

 62%|██████▏   | 3702/6015 [1:11:36<44:46,  1.16s/it]

 62%|██████▏   | 3703/6015 [1:11:37<44:46,  1.16s/it]

 62%|██████▏   | 3704/6015 [1:11:38<44:46,  1.16s/it]

 62%|██████▏   | 3705/6015 [1:11:39<44:46,  1.16s/it]

 62%|██████▏   | 3706/6015 [1:11:41<44:46,  1.16s/it]

 62%|██████▏   | 3707/6015 [1:11:42<44:45,  1.16s/it]

 62%|██████▏   | 3708/6015 [1:11:43<44:46,  1.16s/it]

 62%|██████▏   | 3709/6015 [1:11:44<44:43,  1.16s/it]

 62%|██████▏   | 3710/6015 [1:11:45<44:42,  1.16s/it]

 62%|██████▏   | 3711/6015 [1:11:46<44:38,  1.16s/it]

 62%|██████▏   | 3712/6015 [1:11:48<44:35,  1.16s/it]

 62%|██████▏   | 3713/6015 [1:11:49<44:34,  1.16s/it]

 62%|██████▏   | 3714/6015 [1:11:50<44:32,  1.16s/it]

 62%|██████▏   | 3715/6015 [1:11:51<44:33,  1.16s/it]

 62%|██████▏   | 3716/6015 [1:11:52<44:32,  1.16s/it]

 62%|██████▏   | 3717/6015 [1:11:53<44:31,  1.16s/it]

 62%|██████▏   | 3718/6015 [1:11:55<44:30,  1.16s/it]

 62%|██████▏   | 3719/6015 [1:11:56<44:31,  1.16s/it]

 62%|██████▏   | 3720/6015 [1:11:57<44:30,  1.16s/it]

 62%|██████▏   | 3721/6015 [1:11:58<44:29,  1.16s/it]

 62%|██████▏   | 3722/6015 [1:11:59<44:27,  1.16s/it]

 62%|██████▏   | 3723/6015 [1:12:00<44:25,  1.16s/it]

 62%|██████▏   | 3724/6015 [1:12:02<44:23,  1.16s/it]

 62%|██████▏   | 3725/6015 [1:12:03<44:21,  1.16s/it]

 62%|██████▏   | 3726/6015 [1:12:04<44:19,  1.16s/it]

 62%|██████▏   | 3727/6015 [1:12:05<44:17,  1.16s/it]

 62%|██████▏   | 3728/6015 [1:12:06<44:16,  1.16s/it]

 62%|██████▏   | 3729/6015 [1:12:07<44:16,  1.16s/it]

 62%|██████▏   | 3730/6015 [1:12:09<44:16,  1.16s/it]

 62%|██████▏   | 3731/6015 [1:12:10<44:17,  1.16s/it]

 62%|██████▏   | 3732/6015 [1:12:11<44:19,  1.16s/it]

 62%|██████▏   | 3733/6015 [1:12:12<44:18,  1.17s/it]

 62%|██████▏   | 3734/6015 [1:12:13<44:17,  1.17s/it]

 62%|██████▏   | 3735/6015 [1:12:14<44:15,  1.16s/it]

 62%|██████▏   | 3736/6015 [1:12:16<44:14,  1.16s/it]

 62%|██████▏   | 3737/6015 [1:12:17<44:10,  1.16s/it]

 62%|██████▏   | 3738/6015 [1:12:18<44:11,  1.16s/it]

 62%|██████▏   | 3739/6015 [1:12:19<44:11,  1.17s/it]

 62%|██████▏   | 3740/6015 [1:12:20<44:09,  1.16s/it]

 62%|██████▏   | 3741/6015 [1:12:21<44:06,  1.16s/it]

 62%|██████▏   | 3742/6015 [1:12:23<44:06,  1.16s/it]

 62%|██████▏   | 3743/6015 [1:12:24<44:03,  1.16s/it]

 62%|██████▏   | 3744/6015 [1:12:25<44:00,  1.16s/it]

 62%|██████▏   | 3745/6015 [1:12:26<43:57,  1.16s/it]

 62%|██████▏   | 3746/6015 [1:12:27<43:55,  1.16s/it]

 62%|██████▏   | 3747/6015 [1:12:28<43:52,  1.16s/it]

 62%|██████▏   | 3748/6015 [1:12:29<43:51,  1.16s/it]

 62%|██████▏   | 3749/6015 [1:12:31<43:53,  1.16s/it]

 62%|██████▏   | 3750/6015 [1:12:32<43:56,  1.16s/it]

 62%|██████▏   | 3751/6015 [1:12:33<43:54,  1.16s/it]

 62%|██████▏   | 3752/6015 [1:12:34<43:53,  1.16s/it]

 62%|██████▏   | 3753/6015 [1:12:35<43:53,  1.16s/it]

 62%|██████▏   | 3754/6015 [1:12:36<43:51,  1.16s/it]

 62%|██████▏   | 3755/6015 [1:12:38<43:51,  1.16s/it]

logging
logging the anndata

 62%|██████▏   | 3756/6015 [1:12:39<45:18,  1.20s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 62%|██████▏   | 3757/6015 [1:12:40<44:44,  1.19s/it]

 62%|██████▏   | 3758/6015 [1:12:41<44:20,  1.18s/it]

 62%|██████▏   | 3759/6015 [1:12:42<44:01,  1.17s/it]

 63%|██████▎   | 3760/6015 [1:12:44<43:50,  1.17s/it]

 63%|██████▎   | 3761/6015 [1:12:45<43:41,  1.16s/it]

 63%|██████▎   | 3762/6015 [1:12:46<43:35,  1.16s/it]

 63%|██████▎   | 3763/6015 [1:12:47<43:34,  1.16s/it]

 63%|██████▎   | 3764/6015 [1:12:48<43:29,  1.16s/it]

 63%|██████▎   | 3765/6015 [1:12:49<43:24,  1.16s/it]

 63%|██████▎   | 3766/6015 [1:12:50<43:19,  1.16s/it]

 63%|██████▎   | 3767/6015 [1:12:52<43:18,  1.16s/it]

 63%|██████▎   | 3768/6015 [1:12:53<43:15,  1.16s/it]

 63%|██████▎   | 3769/6015 [1:12:54<43:17,  1.16s/it]

 63%|██████▎   | 3770/6015 [1:12:55<43:16,  1.16s/it]

 63%|██████▎   | 3771/6015 [1:12:56<43:15,  1.16s/it]

 63%|██████▎   | 3772/6015 [1:12:57<43:12,  1.16s/it]

 63%|██████▎   | 3773/6015 [1:12:59<43:13,  1.16s/it]

 63%|██████▎   | 3774/6015 [1:13:00<43:10,  1.16s/it]

 63%|██████▎   | 3775/6015 [1:13:01<43:09,  1.16s/it]

 63%|██████▎   | 3776/6015 [1:13:02<43:07,  1.16s/it]

 63%|██████▎   | 3777/6015 [1:13:03<43:07,  1.16s/it]

 63%|██████▎   | 3778/6015 [1:13:04<43:04,  1.16s/it]

 63%|██████▎   | 3779/6015 [1:13:06<43:03,  1.16s/it]

 63%|██████▎   | 3780/6015 [1:13:07<43:02,  1.16s/it]

 63%|██████▎   | 3781/6015 [1:13:08<43:01,  1.16s/it]

 63%|██████▎   | 3782/6015 [1:13:09<43:00,  1.16s/it]

 63%|██████▎   | 3783/6015 [1:13:10<42:57,  1.15s/it]

 63%|██████▎   | 3784/6015 [1:13:11<42:57,  1.16s/it]

 63%|██████▎   | 3785/6015 [1:13:12<42:55,  1.15s/it]

 63%|██████▎   | 3786/6015 [1:13:14<42:54,  1.16s/it]

 63%|██████▎   | 3787/6015 [1:13:15<42:54,  1.16s/it]

 63%|██████▎   | 3788/6015 [1:13:16<42:52,  1.16s/it]

 63%|██████▎   | 3789/6015 [1:13:17<42:53,  1.16s/it]

 63%|██████▎   | 3790/6015 [1:13:18<42:51,  1.16s/it]

 63%|██████▎   | 3791/6015 [1:13:19<42:52,  1.16s/it]

 63%|██████▎   | 3792/6015 [1:13:21<42:51,  1.16s/it]

 63%|██████▎   | 3793/6015 [1:13:22<42:48,  1.16s/it]

 63%|██████▎   | 3794/6015 [1:13:23<42:46,  1.16s/it]

 63%|██████▎   | 3795/6015 [1:13:24<42:45,  1.16s/it]

 63%|██████▎   | 3796/6015 [1:13:25<42:45,  1.16s/it]

 63%|██████▎   | 3797/6015 [1:13:26<42:44,  1.16s/it]

 63%|██████▎   | 3798/6015 [1:13:27<42:44,  1.16s/it]

 63%|██████▎   | 3799/6015 [1:13:29<42:41,  1.16s/it]

 63%|██████▎   | 3800/6015 [1:13:30<42:41,  1.16s/it]

 63%|██████▎   | 3801/6015 [1:13:31<42:40,  1.16s/it]

 63%|██████▎   | 3802/6015 [1:13:32<42:39,  1.16s/it]

 63%|██████▎   | 3803/6015 [1:13:33<42:35,  1.16s/it]

 63%|██████▎   | 3804/6015 [1:13:34<42:30,  1.15s/it]

 63%|██████▎   | 3805/6015 [1:13:36<42:30,  1.15s/it]

 63%|██████▎   | 3806/6015 [1:13:37<42:30,  1.15s/it]

 63%|██████▎   | 3807/6015 [1:13:38<42:29,  1.15s/it]

 63%|██████▎   | 3808/6015 [1:13:39<42:31,  1.16s/it]

 63%|██████▎   | 3809/6015 [1:13:40<42:28,  1.16s/it]

 63%|██████▎   | 3810/6015 [1:13:41<42:29,  1.16s/it]

 63%|██████▎   | 3811/6015 [1:13:43<42:27,  1.16s/it]

 63%|██████▎   | 3812/6015 [1:13:44<42:24,  1.15s/it]

 63%|██████▎   | 3813/6015 [1:13:45<42:24,  1.16s/it]

 63%|██████▎   | 3814/6015 [1:13:46<42:22,  1.16s/it]

 63%|██████▎   | 3815/6015 [1:13:47<42:22,  1.16s/it]

 63%|██████▎   | 3816/6015 [1:13:48<42:22,  1.16s/it]

 63%|██████▎   | 3817/6015 [1:13:49<42:22,  1.16s/it]

 63%|██████▎   | 3818/6015 [1:13:51<42:22,  1.16s/it]

 63%|██████▎   | 3819/6015 [1:13:52<42:19,  1.16s/it]

 64%|██████▎   | 3820/6015 [1:13:53<42:17,  1.16s/it]

 64%|██████▎   | 3821/6015 [1:13:54<42:16,  1.16s/it]

 64%|██████▎   | 3822/6015 [1:13:55<42:15,  1.16s/it]

 64%|██████▎   | 3823/6015 [1:13:56<42:13,  1.16s/it]

 64%|██████▎   | 3824/6015 [1:13:58<42:13,  1.16s/it]

 64%|██████▎   | 3825/6015 [1:13:59<42:12,  1.16s/it]

 64%|██████▎   | 3826/6015 [1:14:00<42:12,  1.16s/it]

 64%|██████▎   | 3827/6015 [1:14:01<42:11,  1.16s/it]

 64%|██████▎   | 3828/6015 [1:14:02<42:10,  1.16s/it]

 64%|██████▎   | 3829/6015 [1:14:03<42:06,  1.16s/it]

 64%|██████▎   | 3830/6015 [1:14:04<42:06,  1.16s/it]

 64%|██████▎   | 3831/6015 [1:14:06<42:04,  1.16s/it]

 64%|██████▎   | 3832/6015 [1:14:07<42:05,  1.16s/it]

 64%|██████▎   | 3833/6015 [1:14:08<42:05,  1.16s/it]

 64%|██████▎   | 3834/6015 [1:14:09<42:03,  1.16s/it]

 64%|██████▍   | 3835/6015 [1:14:10<42:01,  1.16s/it]

 64%|██████▍   | 3836/6015 [1:14:11<41:57,  1.16s/it]

 64%|██████▍   | 3837/6015 [1:14:13<41:54,  1.15s/it]

 64%|██████▍   | 3838/6015 [1:14:14<41:53,  1.15s/it]

 64%|██████▍   | 3839/6015 [1:14:15<41:53,  1.16s/it]

 64%|██████▍   | 3840/6015 [1:14:16<41:54,  1.16s/it]

 64%|██████▍   | 3841/6015 [1:14:17<41:53,  1.16s/it]

 64%|██████▍   | 3842/6015 [1:14:18<41:53,  1.16s/it]

 64%|██████▍   | 3843/6015 [1:14:20<41:52,  1.16s/it]

 64%|██████▍   | 3844/6015 [1:14:21<41:51,  1.16s/it]

 64%|██████▍   | 3845/6015 [1:14:22<41:50,  1.16s/it]

 64%|██████▍   | 3846/6015 [1:14:23<41:48,  1.16s/it]

 64%|██████▍   | 3847/6015 [1:14:24<41:47,  1.16s/it]

 64%|██████▍   | 3848/6015 [1:14:25<41:43,  1.16s/it]

 64%|██████▍   | 3849/6015 [1:14:26<41:42,  1.16s/it]

 64%|██████▍   | 3850/6015 [1:14:28<41:41,  1.16s/it]

 64%|██████▍   | 3851/6015 [1:14:29<41:45,  1.16s/it]

 64%|██████▍   | 3852/6015 [1:14:30<41:44,  1.16s/it]

 64%|██████▍   | 3853/6015 [1:14:31<41:40,  1.16s/it]

 64%|██████▍   | 3854/6015 [1:14:32<41:41,  1.16s/it]

 64%|██████▍   | 3855/6015 [1:14:33<41:43,  1.16s/it]

 64%|██████▍   | 3856/6015 [1:14:35<41:42,  1.16s/it]

 64%|██████▍   | 3857/6015 [1:14:36<41:39,  1.16s/it]

 64%|██████▍   | 3858/6015 [1:14:37<41:36,  1.16s/it]

 64%|██████▍   | 3859/6015 [1:14:38<41:32,  1.16s/it]

 64%|██████▍   | 3860/6015 [1:14:39<41:30,  1.16s/it]

 64%|██████▍   | 3861/6015 [1:14:40<41:31,  1.16s/it]

 64%|██████▍   | 3862/6015 [1:14:41<41:30,  1.16s/it]

 64%|██████▍   | 3863/6015 [1:14:43<41:30,  1.16s/it]

 64%|██████▍   | 3864/6015 [1:14:44<41:30,  1.16s/it]

 64%|██████▍   | 3865/6015 [1:14:45<41:29,  1.16s/it]

 64%|██████▍   | 3866/6015 [1:14:46<41:26,  1.16s/it]

 64%|██████▍   | 3867/6015 [1:14:47<41:25,  1.16s/it]

 64%|██████▍   | 3868/6015 [1:14:48<41:22,  1.16s/it]

 64%|██████▍   | 3869/6015 [1:14:50<41:20,  1.16s/it]

 64%|██████▍   | 3870/6015 [1:14:51<41:20,  1.16s/it]

 64%|██████▍   | 3871/6015 [1:14:52<41:20,  1.16s/it]

 64%|██████▍   | 3872/6015 [1:14:53<41:19,  1.16s/it]

 64%|██████▍   | 3873/6015 [1:14:54<41:16,  1.16s/it]

 64%|██████▍   | 3874/6015 [1:14:55<41:17,  1.16s/it]

 64%|██████▍   | 3875/6015 [1:14:57<41:16,  1.16s/it]

 64%|██████▍   | 3876/6015 [1:14:58<41:13,  1.16s/it]

 64%|██████▍   | 3877/6015 [1:14:59<41:12,  1.16s/it]

 64%|██████▍   | 3878/6015 [1:15:00<41:08,  1.16s/it]

 64%|██████▍   | 3879/6015 [1:15:01<41:08,  1.16s/it]

 65%|██████▍   | 3880/6015 [1:15:02<41:08,  1.16s/it]

 65%|██████▍   | 3881/6015 [1:15:03<41:09,  1.16s/it]

 65%|██████▍   | 3882/6015 [1:15:05<41:05,  1.16s/it]

 65%|██████▍   | 3883/6015 [1:15:06<41:04,  1.16s/it]

 65%|██████▍   | 3884/6015 [1:15:07<41:03,  1.16s/it]

 65%|██████▍   | 3885/6015 [1:15:08<41:02,  1.16s/it]

 65%|██████▍   | 3886/6015 [1:15:09<41:01,  1.16s/it]

 65%|██████▍   | 3887/6015 [1:15:10<41:01,  1.16s/it]

 65%|██████▍   | 3888/6015 [1:15:12<40:58,  1.16s/it]

 65%|██████▍   | 3889/6015 [1:15:13<40:59,  1.16s/it]

 65%|██████▍   | 3890/6015 [1:15:14<41:00,  1.16s/it]

 65%|██████▍   | 3891/6015 [1:15:15<40:58,  1.16s/it]

 65%|██████▍   | 3892/6015 [1:15:16<40:57,  1.16s/it]

 65%|██████▍   | 3893/6015 [1:15:17<40:57,  1.16s/it]

 65%|██████▍   | 3894/6015 [1:15:19<40:55,  1.16s/it]

 65%|██████▍   | 3895/6015 [1:15:20<40:54,  1.16s/it]

 65%|██████▍   | 3896/6015 [1:15:21<40:53,  1.16s/it]

 65%|██████▍   | 3897/6015 [1:15:22<40:50,  1.16s/it]

 65%|██████▍   | 3898/6015 [1:15:23<40:48,  1.16s/it]

 65%|██████▍   | 3899/6015 [1:15:24<40:49,  1.16s/it]

 65%|██████▍   | 3900/6015 [1:15:25<40:47,  1.16s/it]

 65%|██████▍   | 3901/6015 [1:15:27<40:46,  1.16s/it]

 65%|██████▍   | 3902/6015 [1:15:28<40:47,  1.16s/it]

 65%|██████▍   | 3903/6015 [1:15:29<40:43,  1.16s/it]

 65%|██████▍   | 3904/6015 [1:15:30<40:41,  1.16s/it]

 65%|██████▍   | 3905/6015 [1:15:31<40:38,  1.16s/it]

 65%|██████▍   | 3906/6015 [1:15:32<40:38,  1.16s/it]

 65%|██████▍   | 3907/6015 [1:15:34<40:38,  1.16s/it]

 65%|██████▍   | 3908/6015 [1:15:35<40:39,  1.16s/it]

 65%|██████▍   | 3909/6015 [1:15:36<40:39,  1.16s/it]

 65%|██████▌   | 3910/6015 [1:15:37<40:43,  1.16s/it]

 65%|██████▌   | 3911/6015 [1:15:38<40:41,  1.16s/it]

 65%|██████▌   | 3912/6015 [1:15:39<40:38,  1.16s/it]

 65%|██████▌   | 3913/6015 [1:15:41<40:36,  1.16s/it]

 65%|██████▌   | 3914/6015 [1:15:42<40:36,  1.16s/it]

 65%|██████▌   | 3915/6015 [1:15:43<40:33,  1.16s/it]

 65%|██████▌   | 3916/6015 [1:15:44<40:30,  1.16s/it]

 65%|██████▌   | 3917/6015 [1:15:45<40:29,  1.16s/it]

 65%|██████▌   | 3918/6015 [1:15:46<40:24,  1.16s/it]

 65%|██████▌   | 3919/6015 [1:15:47<40:22,  1.16s/it]

 65%|██████▌   | 3920/6015 [1:15:49<40:22,  1.16s/it]

 65%|██████▌   | 3921/6015 [1:15:50<40:23,  1.16s/it]

 65%|██████▌   | 3922/6015 [1:15:51<40:23,  1.16s/it]

 65%|██████▌   | 3923/6015 [1:15:52<40:22,  1.16s/it]

 65%|██████▌   | 3924/6015 [1:15:53<40:22,  1.16s/it]

 65%|██████▌   | 3925/6015 [1:15:54<40:20,  1.16s/it]

 65%|██████▌   | 3926/6015 [1:15:56<40:18,  1.16s/it]

 65%|██████▌   | 3927/6015 [1:15:57<40:17,  1.16s/it]

 65%|██████▌   | 3928/6015 [1:15:58<40:17,  1.16s/it]

 65%|██████▌   | 3929/6015 [1:15:59<40:15,  1.16s/it]

 65%|██████▌   | 3930/6015 [1:16:00<40:12,  1.16s/it]

 65%|██████▌   | 3931/6015 [1:16:01<40:10,  1.16s/it]

 65%|██████▌   | 3932/6015 [1:16:02<40:09,  1.16s/it]

 65%|██████▌   | 3933/6015 [1:16:04<40:09,  1.16s/it]

 65%|██████▌   | 3934/6015 [1:16:05<40:07,  1.16s/it]

 65%|██████▌   | 3935/6015 [1:16:06<40:07,  1.16s/it]

 65%|██████▌   | 3936/6015 [1:16:07<40:05,  1.16s/it]

 65%|██████▌   | 3937/6015 [1:16:08<40:01,  1.16s/it]

 65%|██████▌   | 3938/6015 [1:16:09<40:02,  1.16s/it]

 65%|██████▌   | 3939/6015 [1:16:11<40:03,  1.16s/it]

 66%|██████▌   | 3940/6015 [1:16:12<40:03,  1.16s/it]

 66%|██████▌   | 3941/6015 [1:16:13<40:02,  1.16s/it]

 66%|██████▌   | 3942/6015 [1:16:14<39:59,  1.16s/it]

 66%|██████▌   | 3943/6015 [1:16:15<39:58,  1.16s/it]

 66%|██████▌   | 3944/6015 [1:16:16<39:58,  1.16s/it]

 66%|██████▌   | 3945/6015 [1:16:18<39:56,  1.16s/it]

 66%|██████▌   | 3946/6015 [1:16:19<39:54,  1.16s/it]

 66%|██████▌   | 3947/6015 [1:16:20<39:54,  1.16s/it]

 66%|██████▌   | 3948/6015 [1:16:21<39:53,  1.16s/it]

 66%|██████▌   | 3949/6015 [1:16:22<39:53,  1.16s/it]

 66%|██████▌   | 3950/6015 [1:16:23<39:54,  1.16s/it]

 66%|██████▌   | 3951/6015 [1:16:24<39:52,  1.16s/it]

 66%|██████▌   | 3952/6015 [1:16:26<39:52,  1.16s/it]

 66%|██████▌   | 3953/6015 [1:16:27<39:50,  1.16s/it]

 66%|██████▌   | 3954/6015 [1:16:28<39:51,  1.16s/it]

 66%|██████▌   | 3955/6015 [1:16:29<39:50,  1.16s/it]

 66%|██████▌   | 3956/6015 [1:16:30<39:46,  1.16s/it]

 66%|██████▌   | 3957/6015 [1:16:31<39:44,  1.16s/it]

 66%|██████▌   | 3958/6015 [1:16:33<39:44,  1.16s/it]

 66%|██████▌   | 3959/6015 [1:16:34<39:43,  1.16s/it]

 66%|██████▌   | 3960/6015 [1:16:35<39:39,  1.16s/it]

 66%|██████▌   | 3961/6015 [1:16:36<39:38,  1.16s/it]

 66%|██████▌   | 3962/6015 [1:16:37<39:38,  1.16s/it]

 66%|██████▌   | 3963/6015 [1:16:38<39:37,  1.16s/it]

 66%|██████▌   | 3964/6015 [1:16:40<39:35,  1.16s/it]

 66%|██████▌   | 3965/6015 [1:16:41<39:31,  1.16s/it]

 66%|██████▌   | 3966/6015 [1:16:42<39:30,  1.16s/it]

 66%|██████▌   | 3967/6015 [1:16:43<39:32,  1.16s/it]

 66%|██████▌   | 3968/6015 [1:16:44<39:31,  1.16s/it]

 66%|██████▌   | 3969/6015 [1:16:45<39:31,  1.16s/it]

 66%|██████▌   | 3970/6015 [1:16:47<39:30,  1.16s/it]

 66%|██████▌   | 3971/6015 [1:16:48<39:30,  1.16s/it]

 66%|██████▌   | 3972/6015 [1:16:49<39:27,  1.16s/it]

 66%|██████▌   | 3973/6015 [1:16:50<39:26,  1.16s/it]

 66%|██████▌   | 3974/6015 [1:16:51<39:25,  1.16s/it]

 66%|██████▌   | 3975/6015 [1:16:52<39:23,  1.16s/it]

 66%|██████▌   | 3976/6015 [1:16:53<39:21,  1.16s/it]

 66%|██████▌   | 3977/6015 [1:16:55<39:19,  1.16s/it]

 66%|██████▌   | 3978/6015 [1:16:56<39:15,  1.16s/it]

 66%|██████▌   | 3979/6015 [1:16:57<39:14,  1.16s/it]

 66%|██████▌   | 3980/6015 [1:16:58<39:12,  1.16s/it]

 66%|██████▌   | 3981/6015 [1:16:59<39:14,  1.16s/it]

 66%|██████▌   | 3982/6015 [1:17:00<39:13,  1.16s/it]

 66%|██████▌   | 3983/6015 [1:17:02<39:12,  1.16s/it]

 66%|██████▌   | 3984/6015 [1:17:03<39:13,  1.16s/it]

 66%|██████▋   | 3985/6015 [1:17:04<39:12,  1.16s/it]

 66%|██████▋   | 3986/6015 [1:17:05<39:10,  1.16s/it]

 66%|██████▋   | 3987/6015 [1:17:06<39:09,  1.16s/it]

 66%|██████▋   | 3988/6015 [1:17:07<39:07,  1.16s/it]

 66%|██████▋   | 3989/6015 [1:17:09<39:06,  1.16s/it]

 66%|██████▋   | 3990/6015 [1:17:10<39:04,  1.16s/it]

 66%|██████▋   | 3991/6015 [1:17:11<39:04,  1.16s/it]

 66%|██████▋   | 3992/6015 [1:17:12<39:01,  1.16s/it]

 66%|██████▋   | 3993/6015 [1:17:13<39:00,  1.16s/it]

 66%|██████▋   | 3994/6015 [1:17:14<38:59,  1.16s/it]

 66%|██████▋   | 3995/6015 [1:17:15<38:59,  1.16s/it]

 66%|██████▋   | 3996/6015 [1:17:17<38:58,  1.16s/it]

 66%|██████▋   | 3997/6015 [1:17:18<38:59,  1.16s/it]

 66%|██████▋   | 3998/6015 [1:17:19<38:57,  1.16s/it]

 66%|██████▋   | 3999/6015 [1:17:20<38:54,  1.16s/it]

 67%|██████▋   | 4000/6015 [1:17:21<38:53,  1.16s/it]

 67%|██████▋   | 4001/6015 [1:17:22<38:51,  1.16s/it]

 67%|██████▋   | 4002/6015 [1:17:24<38:52,  1.16s/it]

 67%|██████▋   | 4003/6015 [1:17:25<38:51,  1.16s/it]

 67%|██████▋   | 4004/6015 [1:17:26<38:51,  1.16s/it]

 67%|██████▋   | 4005/6015 [1:17:27<38:52,  1.16s/it]

 67%|██████▋   | 4006/6015 [1:17:28<38:48,  1.16s/it]

 67%|██████▋   | 4007/6015 [1:17:29<38:46,  1.16s/it]

 67%|██████▋   | 4008/6015 [1:17:31<38:44,  1.16s/it]

 67%|██████▋   | 4009/6015 [1:17:32<38:42,  1.16s/it]

 67%|██████▋   | 4010/6015 [1:17:33<38:41,  1.16s/it]

 67%|██████▋   | 4011/6015 [1:17:34<38:42,  1.16s/it]

 67%|██████▋   | 4012/6015 [1:17:35<38:40,  1.16s/it]

 67%|██████▋   | 4013/6015 [1:17:36<38:39,  1.16s/it]

 67%|██████▋   | 4014/6015 [1:17:37<38:39,  1.16s/it]

 67%|██████▋   | 4015/6015 [1:17:39<38:37,  1.16s/it]

 67%|██████▋   | 4016/6015 [1:17:40<38:36,  1.16s/it]

 67%|██████▋   | 4017/6015 [1:17:41<38:35,  1.16s/it]

 67%|██████▋   | 4018/6015 [1:17:42<38:33,  1.16s/it]

 67%|██████▋   | 4019/6015 [1:17:43<38:30,  1.16s/it]

 67%|██████▋   | 4020/6015 [1:17:44<38:29,  1.16s/it]

 67%|██████▋   | 4021/6015 [1:17:46<38:29,  1.16s/it]

 67%|██████▋   | 4022/6015 [1:17:47<38:28,  1.16s/it]

 67%|██████▋   | 4023/6015 [1:17:48<38:30,  1.16s/it]

 67%|██████▋   | 4024/6015 [1:17:49<38:30,  1.16s/it]

 67%|██████▋   | 4025/6015 [1:17:50<38:30,  1.16s/it]

 67%|██████▋   | 4026/6015 [1:17:51<38:27,  1.16s/it]

 67%|██████▋   | 4027/6015 [1:17:53<38:26,  1.16s/it]

 67%|██████▋   | 4028/6015 [1:17:54<38:24,  1.16s/it]

 67%|██████▋   | 4029/6015 [1:17:55<38:26,  1.16s/it]

 67%|██████▋   | 4030/6015 [1:17:56<38:25,  1.16s/it]

 67%|██████▋   | 4031/6015 [1:17:57<38:23,  1.16s/it]

 67%|██████▋   | 4032/6015 [1:17:58<38:21,  1.16s/it]

 67%|██████▋   | 4033/6015 [1:18:00<38:16,  1.16s/it]

 67%|██████▋   | 4034/6015 [1:18:01<38:14,  1.16s/it]

 67%|██████▋   | 4035/6015 [1:18:02<38:13,  1.16s/it]

 67%|██████▋   | 4036/6015 [1:18:03<38:12,  1.16s/it]

 67%|██████▋   | 4037/6015 [1:18:04<38:10,  1.16s/it]

 67%|██████▋   | 4038/6015 [1:18:05<38:09,  1.16s/it]

 67%|██████▋   | 4039/6015 [1:18:06<38:09,  1.16s/it]

 67%|██████▋   | 4040/6015 [1:18:08<38:07,  1.16s/it]

 67%|██████▋   | 4041/6015 [1:18:09<38:06,  1.16s/it]

 67%|██████▋   | 4042/6015 [1:18:10<38:06,  1.16s/it]

 67%|██████▋   | 4043/6015 [1:18:11<38:05,  1.16s/it]

 67%|██████▋   | 4044/6015 [1:18:12<38:03,  1.16s/it]

 67%|██████▋   | 4045/6015 [1:18:13<38:01,  1.16s/it]

 67%|██████▋   | 4046/6015 [1:18:15<37:58,  1.16s/it]

 67%|██████▋   | 4047/6015 [1:18:16<37:58,  1.16s/it]

 67%|██████▋   | 4048/6015 [1:18:17<37:59,  1.16s/it]

 67%|██████▋   | 4049/6015 [1:18:18<37:58,  1.16s/it]

 67%|██████▋   | 4050/6015 [1:18:19<37:57,  1.16s/it]

 67%|██████▋   | 4051/6015 [1:18:20<37:55,  1.16s/it]

 67%|██████▋   | 4052/6015 [1:18:22<37:54,  1.16s/it]

 67%|██████▋   | 4053/6015 [1:18:23<37:53,  1.16s/it]

 67%|██████▋   | 4054/6015 [1:18:24<37:51,  1.16s/it]

 67%|██████▋   | 4055/6015 [1:18:25<37:50,  1.16s/it]

 67%|██████▋   | 4056/6015 [1:18:26<37:48,  1.16s/it]

 67%|██████▋   | 4057/6015 [1:18:27<37:47,  1.16s/it]

 67%|██████▋   | 4058/6015 [1:18:28<37:46,  1.16s/it]

 67%|██████▋   | 4059/6015 [1:18:30<37:46,  1.16s/it]

 67%|██████▋   | 4060/6015 [1:18:31<37:45,  1.16s/it]

 68%|██████▊   | 4061/6015 [1:18:32<37:46,  1.16s/it]

 68%|██████▊   | 4062/6015 [1:18:33<37:44,  1.16s/it]

 68%|██████▊   | 4063/6015 [1:18:34<37:43,  1.16s/it]

 68%|██████▊   | 4064/6015 [1:18:35<37:41,  1.16s/it]

 68%|██████▊   | 4065/6015 [1:18:37<37:39,  1.16s/it]

 68%|██████▊   | 4066/6015 [1:18:38<37:38,  1.16s/it]

 68%|██████▊   | 4067/6015 [1:18:39<37:37,  1.16s/it]

 68%|██████▊   | 4068/6015 [1:18:40<37:36,  1.16s/it]

 68%|██████▊   | 4069/6015 [1:18:41<37:35,  1.16s/it]

 68%|██████▊   | 4070/6015 [1:18:42<37:36,  1.16s/it]

 68%|██████▊   | 4071/6015 [1:18:44<37:32,  1.16s/it]

 68%|██████▊   | 4072/6015 [1:18:45<37:31,  1.16s/it]

 68%|██████▊   | 4073/6015 [1:18:46<37:30,  1.16s/it]

 68%|██████▊   | 4074/6015 [1:18:47<37:27,  1.16s/it]

 68%|██████▊   | 4075/6015 [1:18:48<37:25,  1.16s/it]

 68%|██████▊   | 4076/6015 [1:18:49<37:25,  1.16s/it]

 68%|██████▊   | 4077/6015 [1:18:50<37:23,  1.16s/it]

 68%|██████▊   | 4078/6015 [1:18:52<37:22,  1.16s/it]

 68%|██████▊   | 4079/6015 [1:18:53<37:24,  1.16s/it]

 68%|██████▊   | 4080/6015 [1:18:54<37:24,  1.16s/it]

 68%|██████▊   | 4081/6015 [1:18:55<37:22,  1.16s/it]

 68%|██████▊   | 4082/6015 [1:18:56<37:20,  1.16s/it]

 68%|██████▊   | 4083/6015 [1:18:57<37:22,  1.16s/it]

 68%|██████▊   | 4084/6015 [1:18:59<37:18,  1.16s/it]

 68%|██████▊   | 4085/6015 [1:19:00<37:16,  1.16s/it]

 68%|██████▊   | 4086/6015 [1:19:01<37:17,  1.16s/it]

 68%|██████▊   | 4087/6015 [1:19:02<37:18,  1.16s/it]

 68%|██████▊   | 4088/6015 [1:19:03<37:18,  1.16s/it]

 68%|██████▊   | 4089/6015 [1:19:04<37:14,  1.16s/it]

 68%|██████▊   | 4090/6015 [1:19:06<37:11,  1.16s/it]

 68%|██████▊   | 4091/6015 [1:19:07<37:08,  1.16s/it]

 68%|██████▊   | 4092/6015 [1:19:08<37:10,  1.16s/it]

 68%|██████▊   | 4093/6015 [1:19:09<37:09,  1.16s/it]

 68%|██████▊   | 4094/6015 [1:19:10<37:08,  1.16s/it]

 68%|██████▊   | 4095/6015 [1:19:11<37:07,  1.16s/it]

 68%|██████▊   | 4096/6015 [1:19:13<37:06,  1.16s/it]

 68%|██████▊   | 4097/6015 [1:19:14<37:06,  1.16s/it]

 68%|██████▊   | 4098/6015 [1:19:15<37:04,  1.16s/it]

 68%|██████▊   | 4099/6015 [1:19:16<37:01,  1.16s/it]

 68%|██████▊   | 4100/6015 [1:19:17<36:58,  1.16s/it]

 68%|██████▊   | 4101/6015 [1:19:18<36:57,  1.16s/it]

 68%|██████▊   | 4102/6015 [1:19:19<36:54,  1.16s/it]

 68%|██████▊   | 4103/6015 [1:19:21<36:55,  1.16s/it]

 68%|██████▊   | 4104/6015 [1:19:22<36:55,  1.16s/it]

 68%|██████▊   | 4105/6015 [1:19:23<36:54,  1.16s/it]

 68%|██████▊   | 4106/6015 [1:19:24<36:52,  1.16s/it]

 68%|██████▊   | 4107/6015 [1:19:25<36:53,  1.16s/it]

 68%|██████▊   | 4108/6015 [1:19:26<36:55,  1.16s/it]

 68%|██████▊   | 4109/6015 [1:19:28<36:53,  1.16s/it]

 68%|██████▊   | 4110/6015 [1:19:29<36:49,  1.16s/it]

 68%|██████▊   | 4111/6015 [1:19:30<36:47,  1.16s/it]

 68%|██████▊   | 4112/6015 [1:19:31<36:46,  1.16s/it]

 68%|██████▊   | 4113/6015 [1:19:32<36:42,  1.16s/it]

 68%|██████▊   | 4114/6015 [1:19:33<36:42,  1.16s/it]

 68%|██████▊   | 4115/6015 [1:19:35<36:42,  1.16s/it]

 68%|██████▊   | 4116/6015 [1:19:36<36:43,  1.16s/it]

 68%|██████▊   | 4117/6015 [1:19:37<36:43,  1.16s/it]

 68%|██████▊   | 4118/6015 [1:19:38<36:40,  1.16s/it]

 68%|██████▊   | 4119/6015 [1:19:39<36:37,  1.16s/it]

 68%|██████▊   | 4120/6015 [1:19:40<36:37,  1.16s/it]

 69%|██████▊   | 4121/6015 [1:19:42<36:36,  1.16s/it]

 69%|██████▊   | 4122/6015 [1:19:43<36:33,  1.16s/it]

 69%|██████▊   | 4123/6015 [1:19:44<36:32,  1.16s/it]

 69%|██████▊   | 4124/6015 [1:19:45<36:31,  1.16s/it]

 69%|██████▊   | 4125/6015 [1:19:46<36:31,  1.16s/it]

 69%|██████▊   | 4126/6015 [1:19:47<36:29,  1.16s/it]

 69%|██████▊   | 4127/6015 [1:19:48<36:29,  1.16s/it]

 69%|██████▊   | 4128/6015 [1:19:50<36:29,  1.16s/it]

 69%|██████▊   | 4129/6015 [1:19:51<36:27,  1.16s/it]

 69%|██████▊   | 4130/6015 [1:19:52<36:26,  1.16s/it]

 69%|██████▊   | 4131/6015 [1:19:53<36:25,  1.16s/it]

 69%|██████▊   | 4132/6015 [1:19:54<36:23,  1.16s/it]

 69%|██████▊   | 4133/6015 [1:19:55<36:21,  1.16s/it]

 69%|██████▊   | 4134/6015 [1:19:57<36:19,  1.16s/it]

 69%|██████▊   | 4135/6015 [1:19:58<36:18,  1.16s/it]

 69%|██████▉   | 4136/6015 [1:19:59<36:19,  1.16s/it]

 69%|██████▉   | 4137/6015 [1:20:00<36:19,  1.16s/it]

 69%|██████▉   | 4138/6015 [1:20:01<36:17,  1.16s/it]

 69%|██████▉   | 4139/6015 [1:20:02<36:16,  1.16s/it]

 69%|██████▉   | 4140/6015 [1:20:04<36:20,  1.16s/it]

 69%|██████▉   | 4141/6015 [1:20:05<36:17,  1.16s/it]

 69%|██████▉   | 4142/6015 [1:20:06<36:16,  1.16s/it]

 69%|██████▉   | 4143/6015 [1:20:07<36:13,  1.16s/it]

 69%|██████▉   | 4144/6015 [1:20:08<36:10,  1.16s/it]

 69%|██████▉   | 4145/6015 [1:20:09<36:11,  1.16s/it]

 69%|██████▉   | 4146/6015 [1:20:11<36:10,  1.16s/it]

 69%|██████▉   | 4147/6015 [1:20:12<36:09,  1.16s/it]

 69%|██████▉   | 4148/6015 [1:20:13<36:06,  1.16s/it]

 69%|██████▉   | 4149/6015 [1:20:14<36:03,  1.16s/it]

 69%|██████▉   | 4150/6015 [1:20:15<36:01,  1.16s/it]

 69%|██████▉   | 4151/6015 [1:20:16<36:03,  1.16s/it]

 69%|██████▉   | 4152/6015 [1:20:17<36:01,  1.16s/it]

 69%|██████▉   | 4153/6015 [1:20:19<36:01,  1.16s/it]

 69%|██████▉   | 4154/6015 [1:20:20<35:59,  1.16s/it]

 69%|██████▉   | 4155/6015 [1:20:21<35:59,  1.16s/it]

 69%|██████▉   | 4156/6015 [1:20:22<35:59,  1.16s/it]

 69%|██████▉   | 4157/6015 [1:20:23<35:56,  1.16s/it]

 69%|██████▉   | 4158/6015 [1:20:24<35:56,  1.16s/it]

 69%|██████▉   | 4159/6015 [1:20:26<35:54,  1.16s/it]

 69%|██████▉   | 4160/6015 [1:20:27<35:52,  1.16s/it]

 69%|██████▉   | 4161/6015 [1:20:28<35:51,  1.16s/it]

 69%|██████▉   | 4162/6015 [1:20:29<35:48,  1.16s/it]

 69%|██████▉   | 4163/6015 [1:20:30<35:46,  1.16s/it]

 69%|██████▉   | 4164/6015 [1:20:31<35:49,  1.16s/it]

 69%|██████▉   | 4165/6015 [1:20:33<35:48,  1.16s/it]

 69%|██████▉   | 4166/6015 [1:20:34<35:48,  1.16s/it]

 69%|██████▉   | 4167/6015 [1:20:35<35:47,  1.16s/it]

 69%|██████▉   | 4168/6015 [1:20:36<35:47,  1.16s/it]

 69%|██████▉   | 4169/6015 [1:20:37<35:42,  1.16s/it]

 69%|██████▉   | 4170/6015 [1:20:38<35:41,  1.16s/it]

 69%|██████▉   | 4171/6015 [1:20:40<35:38,  1.16s/it]

 69%|██████▉   | 4172/6015 [1:20:41<35:37,  1.16s/it]

 69%|██████▉   | 4173/6015 [1:20:42<35:35,  1.16s/it]

 69%|██████▉   | 4174/6015 [1:20:43<35:35,  1.16s/it]

 69%|██████▉   | 4175/6015 [1:20:44<35:33,  1.16s/it]

 69%|██████▉   | 4176/6015 [1:20:45<35:33,  1.16s/it]

 69%|██████▉   | 4177/6015 [1:20:46<35:32,  1.16s/it]

 69%|██████▉   | 4178/6015 [1:20:48<35:30,  1.16s/it]

 69%|██████▉   | 4179/6015 [1:20:49<35:30,  1.16s/it]

 69%|██████▉   | 4180/6015 [1:20:50<35:29,  1.16s/it]

 70%|██████▉   | 4181/6015 [1:20:51<35:27,  1.16s/it]

 70%|██████▉   | 4182/6015 [1:20:52<35:25,  1.16s/it]

 70%|██████▉   | 4183/6015 [1:20:53<35:23,  1.16s/it]

 70%|██████▉   | 4184/6015 [1:20:55<35:20,  1.16s/it]

 70%|██████▉   | 4185/6015 [1:20:56<35:22,  1.16s/it]

 70%|██████▉   | 4186/6015 [1:20:57<35:23,  1.16s/it]

 70%|██████▉   | 4187/6015 [1:20:58<35:23,  1.16s/it]

 70%|██████▉   | 4188/6015 [1:20:59<35:23,  1.16s/it]

 70%|██████▉   | 4189/6015 [1:21:00<35:23,  1.16s/it]

 70%|██████▉   | 4190/6015 [1:21:02<35:22,  1.16s/it]

 70%|██████▉   | 4191/6015 [1:21:03<35:22,  1.16s/it]

 70%|██████▉   | 4192/6015 [1:21:04<35:19,  1.16s/it]

 70%|██████▉   | 4193/6015 [1:21:05<35:15,  1.16s/it]

 70%|██████▉   | 4194/6015 [1:21:06<35:12,  1.16s/it]

 70%|██████▉   | 4195/6015 [1:21:07<35:11,  1.16s/it]

 70%|██████▉   | 4196/6015 [1:21:09<35:09,  1.16s/it]

 70%|██████▉   | 4197/6015 [1:21:10<35:08,  1.16s/it]

 70%|██████▉   | 4198/6015 [1:21:11<35:09,  1.16s/it]

 70%|██████▉   | 4199/6015 [1:21:12<35:09,  1.16s/it]

 70%|██████▉   | 4200/6015 [1:21:13<35:06,  1.16s/it]

 70%|██████▉   | 4201/6015 [1:21:14<35:05,  1.16s/it]

 70%|██████▉   | 4202/6015 [1:21:16<35:05,  1.16s/it]

 70%|██████▉   | 4203/6015 [1:21:17<35:04,  1.16s/it]

 70%|██████▉   | 4204/6015 [1:21:18<35:03,  1.16s/it]

 70%|██████▉   | 4205/6015 [1:21:19<35:01,  1.16s/it]

 70%|██████▉   | 4206/6015 [1:21:20<34:58,  1.16s/it]

 70%|██████▉   | 4207/6015 [1:21:21<35:01,  1.16s/it]

 70%|██████▉   | 4208/6015 [1:21:22<34:59,  1.16s/it]

 70%|██████▉   | 4209/6015 [1:21:24<34:55,  1.16s/it]

 70%|██████▉   | 4210/6015 [1:21:25<34:53,  1.16s/it]

 70%|███████   | 4211/6015 [1:21:26<34:51,  1.16s/it]

 70%|███████   | 4212/6015 [1:21:27<34:49,  1.16s/it]

 70%|███████   | 4213/6015 [1:21:28<34:50,  1.16s/it]

 70%|███████   | 4214/6015 [1:21:29<34:50,  1.16s/it]

 70%|███████   | 4215/6015 [1:21:31<34:52,  1.16s/it]

 70%|███████   | 4216/6015 [1:21:32<34:52,  1.16s/it]

 70%|███████   | 4217/6015 [1:21:33<34:50,  1.16s/it]

 70%|███████   | 4218/6015 [1:21:34<34:48,  1.16s/it]

 70%|███████   | 4219/6015 [1:21:35<34:45,  1.16s/it]

 70%|███████   | 4220/6015 [1:21:36<34:43,  1.16s/it]

 70%|███████   | 4221/6015 [1:21:38<34:43,  1.16s/it]

 70%|███████   | 4222/6015 [1:21:39<34:42,  1.16s/it]

 70%|███████   | 4223/6015 [1:21:40<34:40,  1.16s/it]

 70%|███████   | 4224/6015 [1:21:41<34:37,  1.16s/it]

 70%|███████   | 4225/6015 [1:21:42<34:38,  1.16s/it]

 70%|███████   | 4226/6015 [1:21:43<34:37,  1.16s/it]

 70%|███████   | 4227/6015 [1:21:45<34:37,  1.16s/it]

 70%|███████   | 4228/6015 [1:21:46<34:37,  1.16s/it]

 70%|███████   | 4229/6015 [1:21:47<34:37,  1.16s/it]

 70%|███████   | 4230/6015 [1:21:48<34:37,  1.16s/it]

 70%|███████   | 4231/6015 [1:21:49<34:34,  1.16s/it]

 70%|███████   | 4232/6015 [1:21:50<34:36,  1.16s/it]

 70%|███████   | 4233/6015 [1:21:52<34:32,  1.16s/it]

 70%|███████   | 4234/6015 [1:21:53<34:29,  1.16s/it]

 70%|███████   | 4235/6015 [1:21:54<34:25,  1.16s/it]

 70%|███████   | 4236/6015 [1:21:55<34:23,  1.16s/it]

 70%|███████   | 4237/6015 [1:21:56<34:22,  1.16s/it]

 70%|███████   | 4238/6015 [1:21:57<34:21,  1.16s/it]

 70%|███████   | 4239/6015 [1:21:58<34:20,  1.16s/it]

 70%|███████   | 4240/6015 [1:22:00<34:20,  1.16s/it]

 71%|███████   | 4241/6015 [1:22:01<34:21,  1.16s/it]

 71%|███████   | 4242/6015 [1:22:02<34:20,  1.16s/it]

 71%|███████   | 4243/6015 [1:22:03<34:18,  1.16s/it]

 71%|███████   | 4244/6015 [1:22:04<34:18,  1.16s/it]

 71%|███████   | 4245/6015 [1:22:05<34:15,  1.16s/it]

 71%|███████   | 4246/6015 [1:22:07<34:14,  1.16s/it]

 71%|███████   | 4247/6015 [1:22:08<34:13,  1.16s/it]

 71%|███████   | 4248/6015 [1:22:09<34:11,  1.16s/it]

 71%|███████   | 4249/6015 [1:22:10<34:09,  1.16s/it]

 71%|███████   | 4250/6015 [1:22:11<34:08,  1.16s/it]

 71%|███████   | 4251/6015 [1:22:12<34:08,  1.16s/it]

 71%|███████   | 4252/6015 [1:22:14<34:08,  1.16s/it]

 71%|███████   | 4253/6015 [1:22:15<34:09,  1.16s/it]

 71%|███████   | 4254/6015 [1:22:16<34:08,  1.16s/it]

 71%|███████   | 4255/6015 [1:22:17<34:09,  1.16s/it]

 71%|███████   | 4256/6015 [1:22:18<34:07,  1.16s/it]

 71%|███████   | 4257/6015 [1:22:19<34:05,  1.16s/it]

 71%|███████   | 4258/6015 [1:22:21<34:01,  1.16s/it]

 71%|███████   | 4259/6015 [1:22:22<34:00,  1.16s/it]

 71%|███████   | 4260/6015 [1:22:23<33:59,  1.16s/it]

 71%|███████   | 4261/6015 [1:22:24<34:00,  1.16s/it]

 71%|███████   | 4262/6015 [1:22:25<34:01,  1.16s/it]

 71%|███████   | 4263/6015 [1:22:26<34:01,  1.17s/it]

 71%|███████   | 4264/6015 [1:22:28<33:57,  1.16s/it]

 71%|███████   | 4265/6015 [1:22:29<33:53,  1.16s/it]

 71%|███████   | 4266/6015 [1:22:30<33:51,  1.16s/it]

 71%|███████   | 4267/6015 [1:22:31<33:50,  1.16s/it]

 71%|███████   | 4268/6015 [1:22:32<33:50,  1.16s/it]

 71%|███████   | 4269/6015 [1:22:33<33:51,  1.16s/it]

 71%|███████   | 4270/6015 [1:22:35<33:51,  1.16s/it]

 71%|███████   | 4271/6015 [1:22:36<33:49,  1.16s/it]

 71%|███████   | 4272/6015 [1:22:37<33:46,  1.16s/it]

 71%|███████   | 4273/6015 [1:22:38<33:43,  1.16s/it]

 71%|███████   | 4274/6015 [1:22:39<33:44,  1.16s/it]

 71%|███████   | 4275/6015 [1:22:40<33:44,  1.16s/it]

 71%|███████   | 4276/6015 [1:22:42<33:43,  1.16s/it]

 71%|███████   | 4277/6015 [1:22:43<33:41,  1.16s/it]

 71%|███████   | 4278/6015 [1:22:44<33:37,  1.16s/it]

 71%|███████   | 4279/6015 [1:22:45<33:34,  1.16s/it]

 71%|███████   | 4280/6015 [1:22:46<33:32,  1.16s/it]

 71%|███████   | 4281/6015 [1:22:47<33:33,  1.16s/it]

 71%|███████   | 4282/6015 [1:22:48<33:33,  1.16s/it]

 71%|███████   | 4283/6015 [1:22:50<33:31,  1.16s/it]

 71%|███████   | 4284/6015 [1:22:51<33:30,  1.16s/it]

 71%|███████   | 4285/6015 [1:22:52<33:28,  1.16s/it]

 71%|███████▏  | 4286/6015 [1:22:53<33:29,  1.16s/it]

 71%|███████▏  | 4287/6015 [1:22:54<33:27,  1.16s/it]

 71%|███████▏  | 4288/6015 [1:22:55<33:29,  1.16s/it]

 71%|███████▏  | 4289/6015 [1:22:57<33:26,  1.16s/it]

 71%|███████▏  | 4290/6015 [1:22:58<33:24,  1.16s/it]

 71%|███████▏  | 4291/6015 [1:22:59<33:20,  1.16s/it]

 71%|███████▏  | 4292/6015 [1:23:00<33:18,  1.16s/it]

 71%|███████▏  | 4293/6015 [1:23:01<33:19,  1.16s/it]

 71%|███████▏  | 4294/6015 [1:23:02<33:21,  1.16s/it]

 71%|███████▏  | 4295/6015 [1:23:04<33:19,  1.16s/it]

 71%|███████▏  | 4296/6015 [1:23:05<33:17,  1.16s/it]

 71%|███████▏  | 4297/6015 [1:23:06<33:16,  1.16s/it]

 71%|███████▏  | 4298/6015 [1:23:07<33:12,  1.16s/it]

 71%|███████▏  | 4299/6015 [1:23:08<33:13,  1.16s/it]

 71%|███████▏  | 4300/6015 [1:23:09<33:12,  1.16s/it]

 72%|███████▏  | 4301/6015 [1:23:11<33:10,  1.16s/it]

 72%|███████▏  | 4302/6015 [1:23:12<33:09,  1.16s/it]

 72%|███████▏  | 4303/6015 [1:23:13<33:07,  1.16s/it]

 72%|███████▏  | 4304/6015 [1:23:14<33:05,  1.16s/it]

 72%|███████▏  | 4305/6015 [1:23:15<33:04,  1.16s/it]

 72%|███████▏  | 4306/6015 [1:23:16<33:03,  1.16s/it]

 72%|███████▏  | 4307/6015 [1:23:18<33:02,  1.16s/it]

 72%|███████▏  | 4308/6015 [1:23:19<33:02,  1.16s/it]

 72%|███████▏  | 4309/6015 [1:23:20<33:01,  1.16s/it]

 72%|███████▏  | 4310/6015 [1:23:21<33:00,  1.16s/it]

 72%|███████▏  | 4311/6015 [1:23:22<32:59,  1.16s/it]

 72%|███████▏  | 4312/6015 [1:23:23<32:56,  1.16s/it]

 72%|███████▏  | 4313/6015 [1:23:24<32:55,  1.16s/it]

 72%|███████▏  | 4314/6015 [1:23:26<32:52,  1.16s/it]

 72%|███████▏  | 4315/6015 [1:23:27<32:54,  1.16s/it]

 72%|███████▏  | 4316/6015 [1:23:28<32:54,  1.16s/it]

 72%|███████▏  | 4317/6015 [1:23:29<32:55,  1.16s/it]

 72%|███████▏  | 4318/6015 [1:23:30<32:52,  1.16s/it]

 72%|███████▏  | 4319/6015 [1:23:31<32:52,  1.16s/it]

 72%|███████▏  | 4320/6015 [1:23:33<32:50,  1.16s/it]

 72%|███████▏  | 4321/6015 [1:23:34<32:47,  1.16s/it]

 72%|███████▏  | 4322/6015 [1:23:35<32:48,  1.16s/it]

 72%|███████▏  | 4323/6015 [1:23:36<32:47,  1.16s/it]

 72%|███████▏  | 4324/6015 [1:23:37<32:46,  1.16s/it]

 72%|███████▏  | 4325/6015 [1:23:38<32:44,  1.16s/it]

 72%|███████▏  | 4326/6015 [1:23:40<32:42,  1.16s/it]

 72%|███████▏  | 4327/6015 [1:23:41<32:41,  1.16s/it]

 72%|███████▏  | 4328/6015 [1:23:42<32:38,  1.16s/it]

 72%|███████▏  | 4329/6015 [1:23:43<32:40,  1.16s/it]

 72%|███████▏  | 4330/6015 [1:23:44<32:38,  1.16s/it]

 72%|███████▏  | 4331/6015 [1:23:45<32:35,  1.16s/it]

 72%|███████▏  | 4332/6015 [1:23:47<32:33,  1.16s/it]

 72%|███████▏  | 4333/6015 [1:23:48<32:32,  1.16s/it]

 72%|███████▏  | 4334/6015 [1:23:49<32:32,  1.16s/it]

 72%|███████▏  | 4335/6015 [1:23:50<32:32,  1.16s/it]

 72%|███████▏  | 4336/6015 [1:23:51<32:33,  1.16s/it]

 72%|███████▏  | 4337/6015 [1:23:52<32:31,  1.16s/it]

 72%|███████▏  | 4338/6015 [1:23:54<32:29,  1.16s/it]

 72%|███████▏  | 4339/6015 [1:23:55<32:27,  1.16s/it]

 72%|███████▏  | 4340/6015 [1:23:56<32:26,  1.16s/it]

 72%|███████▏  | 4341/6015 [1:23:57<32:25,  1.16s/it]

 72%|███████▏  | 4342/6015 [1:23:58<32:24,  1.16s/it]

 72%|███████▏  | 4343/6015 [1:23:59<32:24,  1.16s/it]

 72%|███████▏  | 4344/6015 [1:24:00<32:20,  1.16s/it]

 72%|███████▏  | 4345/6015 [1:24:02<32:20,  1.16s/it]

 72%|███████▏  | 4346/6015 [1:24:03<32:17,  1.16s/it]

 72%|███████▏  | 4347/6015 [1:24:04<32:18,  1.16s/it]

 72%|███████▏  | 4348/6015 [1:24:05<32:18,  1.16s/it]

 72%|███████▏  | 4349/6015 [1:24:06<32:18,  1.16s/it]

 72%|███████▏  | 4350/6015 [1:24:07<32:16,  1.16s/it]

 72%|███████▏  | 4351/6015 [1:24:09<32:16,  1.16s/it]

 72%|███████▏  | 4352/6015 [1:24:10<32:14,  1.16s/it]

 72%|███████▏  | 4353/6015 [1:24:11<32:13,  1.16s/it]

 72%|███████▏  | 4354/6015 [1:24:12<32:12,  1.16s/it]

 72%|███████▏  | 4355/6015 [1:24:13<32:10,  1.16s/it]

 72%|███████▏  | 4356/6015 [1:24:14<32:07,  1.16s/it]

 72%|███████▏  | 4357/6015 [1:24:16<32:06,  1.16s/it]

 72%|███████▏  | 4358/6015 [1:24:17<32:04,  1.16s/it]

 72%|███████▏  | 4359/6015 [1:24:18<32:03,  1.16s/it]

 72%|███████▏  | 4360/6015 [1:24:19<32:03,  1.16s/it]

 73%|███████▎  | 4361/6015 [1:24:20<32:02,  1.16s/it]

 73%|███████▎  | 4362/6015 [1:24:21<32:01,  1.16s/it]

 73%|███████▎  | 4363/6015 [1:24:23<32:01,  1.16s/it]

 73%|███████▎  | 4364/6015 [1:24:24<32:00,  1.16s/it]

 73%|███████▎  | 4365/6015 [1:24:25<31:58,  1.16s/it]

 73%|███████▎  | 4366/6015 [1:24:26<31:57,  1.16s/it]

 73%|███████▎  | 4367/6015 [1:24:27<31:58,  1.16s/it]

 73%|███████▎  | 4368/6015 [1:24:28<31:58,  1.16s/it]

 73%|███████▎  | 4369/6015 [1:24:30<31:56,  1.16s/it]

 73%|███████▎  | 4370/6015 [1:24:31<31:54,  1.16s/it]

 73%|███████▎  | 4371/6015 [1:24:32<31:50,  1.16s/it]

 73%|███████▎  | 4372/6015 [1:24:33<31:50,  1.16s/it]

 73%|███████▎  | 4373/6015 [1:24:34<31:50,  1.16s/it]

 73%|███████▎  | 4374/6015 [1:24:35<31:49,  1.16s/it]

 73%|███████▎  | 4375/6015 [1:24:37<31:47,  1.16s/it]

 73%|███████▎  | 4376/6015 [1:24:38<31:47,  1.16s/it]

 73%|███████▎  | 4377/6015 [1:24:39<31:46,  1.16s/it]

 73%|███████▎  | 4378/6015 [1:24:40<31:42,  1.16s/it]

 73%|███████▎  | 4379/6015 [1:24:41<31:40,  1.16s/it]

 73%|███████▎  | 4380/6015 [1:24:42<31:40,  1.16s/it]

 73%|███████▎  | 4381/6015 [1:24:44<31:41,  1.16s/it]

logging
logging the anndata

 73%|███████▎  | 4382/6015 [1:24:45<32:36,  1.20s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 73%|███████▎  | 4383/6015 [1:24:46<32:16,  1.19s/it]

 73%|███████▎  | 4384/6015 [1:24:47<31:58,  1.18s/it]

 73%|███████▎  | 4385/6015 [1:24:48<31:46,  1.17s/it]

 73%|███████▎  | 4386/6015 [1:24:49<31:36,  1.16s/it]

 73%|███████▎  | 4387/6015 [1:24:51<31:31,  1.16s/it]

 73%|███████▎  | 4388/6015 [1:24:52<31:27,  1.16s/it]

 73%|███████▎  | 4389/6015 [1:24:53<31:24,  1.16s/it]

 73%|███████▎  | 4390/6015 [1:24:54<31:21,  1.16s/it]

 73%|███████▎  | 4391/6015 [1:24:55<31:21,  1.16s/it]

 73%|███████▎  | 4392/6015 [1:24:56<31:18,  1.16s/it]

 73%|███████▎  | 4393/6015 [1:24:58<31:17,  1.16s/it]

 73%|███████▎  | 4394/6015 [1:24:59<31:13,  1.16s/it]

 73%|███████▎  | 4395/6015 [1:25:00<31:12,  1.16s/it]

 73%|███████▎  | 4396/6015 [1:25:01<31:10,  1.16s/it]

 73%|███████▎  | 4397/6015 [1:25:02<31:11,  1.16s/it]

 73%|███████▎  | 4398/6015 [1:25:03<31:10,  1.16s/it]

 73%|███████▎  | 4399/6015 [1:25:04<31:08,  1.16s/it]

 73%|███████▎  | 4400/6015 [1:25:06<31:10,  1.16s/it]

 73%|███████▎  | 4401/6015 [1:25:07<31:07,  1.16s/it]

 73%|███████▎  | 4402/6015 [1:25:08<31:05,  1.16s/it]

 73%|███████▎  | 4403/6015 [1:25:09<31:04,  1.16s/it]

 73%|███████▎  | 4404/6015 [1:25:10<31:02,  1.16s/it]

 73%|███████▎  | 4405/6015 [1:25:11<31:03,  1.16s/it]

 73%|███████▎  | 4406/6015 [1:25:13<31:02,  1.16s/it]

 73%|███████▎  | 4407/6015 [1:25:14<31:00,  1.16s/it]

 73%|███████▎  | 4408/6015 [1:25:15<30:59,  1.16s/it]

 73%|███████▎  | 4409/6015 [1:25:16<30:57,  1.16s/it]

 73%|███████▎  | 4410/6015 [1:25:17<30:55,  1.16s/it]

 73%|███████▎  | 4411/6015 [1:25:18<30:54,  1.16s/it]

 73%|███████▎  | 4412/6015 [1:25:19<30:52,  1.16s/it]

 73%|███████▎  | 4413/6015 [1:25:21<30:51,  1.16s/it]

 73%|███████▎  | 4414/6015 [1:25:22<30:51,  1.16s/it]

 73%|███████▎  | 4415/6015 [1:25:23<30:50,  1.16s/it]

 73%|███████▎  | 4416/6015 [1:25:24<30:49,  1.16s/it]

 73%|███████▎  | 4417/6015 [1:25:25<30:49,  1.16s/it]

 73%|███████▎  | 4418/6015 [1:25:26<30:49,  1.16s/it]

 73%|███████▎  | 4419/6015 [1:25:28<30:45,  1.16s/it]

 73%|███████▎  | 4420/6015 [1:25:29<30:45,  1.16s/it]

 73%|███████▎  | 4421/6015 [1:25:30<30:41,  1.16s/it]

 74%|███████▎  | 4422/6015 [1:25:31<30:40,  1.16s/it]

 74%|███████▎  | 4423/6015 [1:25:32<30:39,  1.16s/it]

 74%|███████▎  | 4424/6015 [1:25:33<30:38,  1.16s/it]

 74%|███████▎  | 4425/6015 [1:25:35<30:37,  1.16s/it]

 74%|███████▎  | 4426/6015 [1:25:36<30:37,  1.16s/it]

 74%|███████▎  | 4427/6015 [1:25:37<30:36,  1.16s/it]

 74%|███████▎  | 4428/6015 [1:25:38<30:34,  1.16s/it]

 74%|███████▎  | 4429/6015 [1:25:39<30:34,  1.16s/it]

 74%|███████▎  | 4430/6015 [1:25:40<30:32,  1.16s/it]

 74%|███████▎  | 4431/6015 [1:25:41<30:32,  1.16s/it]

 74%|███████▎  | 4432/6015 [1:25:43<30:32,  1.16s/it]

 74%|███████▎  | 4433/6015 [1:25:44<30:32,  1.16s/it]

 74%|███████▎  | 4434/6015 [1:25:45<30:32,  1.16s/it]

 74%|███████▎  | 4435/6015 [1:25:46<30:29,  1.16s/it]

 74%|███████▎  | 4436/6015 [1:25:47<30:28,  1.16s/it]

 74%|███████▍  | 4437/6015 [1:25:48<30:27,  1.16s/it]

 74%|███████▍  | 4438/6015 [1:25:50<30:26,  1.16s/it]

 74%|███████▍  | 4439/6015 [1:25:51<30:23,  1.16s/it]

 74%|███████▍  | 4440/6015 [1:25:52<30:22,  1.16s/it]

 74%|███████▍  | 4441/6015 [1:25:53<30:22,  1.16s/it]

 74%|███████▍  | 4442/6015 [1:25:54<30:19,  1.16s/it]

 74%|███████▍  | 4443/6015 [1:25:55<30:17,  1.16s/it]

 74%|███████▍  | 4444/6015 [1:25:57<30:15,  1.16s/it]

 74%|███████▍  | 4445/6015 [1:25:58<30:15,  1.16s/it]

 74%|███████▍  | 4446/6015 [1:25:59<30:13,  1.16s/it]

 74%|███████▍  | 4447/6015 [1:26:00<30:12,  1.16s/it]

 74%|███████▍  | 4448/6015 [1:26:01<30:11,  1.16s/it]

 74%|███████▍  | 4449/6015 [1:26:02<30:11,  1.16s/it]

 74%|███████▍  | 4450/6015 [1:26:03<30:09,  1.16s/it]

 74%|███████▍  | 4451/6015 [1:26:05<30:06,  1.16s/it]

 74%|███████▍  | 4452/6015 [1:26:06<30:06,  1.16s/it]

 74%|███████▍  | 4453/6015 [1:26:07<30:05,  1.16s/it]

 74%|███████▍  | 4454/6015 [1:26:08<30:04,  1.16s/it]

 74%|███████▍  | 4455/6015 [1:26:09<30:04,  1.16s/it]

 74%|███████▍  | 4456/6015 [1:26:10<30:02,  1.16s/it]

 74%|███████▍  | 4457/6015 [1:26:12<30:03,  1.16s/it]

 74%|███████▍  | 4458/6015 [1:26:13<30:01,  1.16s/it]

 74%|███████▍  | 4459/6015 [1:26:14<30:00,  1.16s/it]

 74%|███████▍  | 4460/6015 [1:26:15<29:59,  1.16s/it]

 74%|███████▍  | 4461/6015 [1:26:16<29:55,  1.16s/it]

 74%|███████▍  | 4462/6015 [1:26:17<29:53,  1.16s/it]

 74%|███████▍  | 4463/6015 [1:26:18<29:53,  1.16s/it]

 74%|███████▍  | 4464/6015 [1:26:20<29:54,  1.16s/it]

 74%|███████▍  | 4465/6015 [1:26:21<29:54,  1.16s/it]

 74%|███████▍  | 4466/6015 [1:26:22<29:52,  1.16s/it]

 74%|███████▍  | 4467/6015 [1:26:23<29:51,  1.16s/it]

 74%|███████▍  | 4468/6015 [1:26:24<29:49,  1.16s/it]

 74%|███████▍  | 4469/6015 [1:26:25<29:46,  1.16s/it]

 74%|███████▍  | 4470/6015 [1:26:27<29:44,  1.16s/it]

 74%|███████▍  | 4471/6015 [1:26:28<29:45,  1.16s/it]

 74%|███████▍  | 4472/6015 [1:26:29<29:45,  1.16s/it]

 74%|███████▍  | 4473/6015 [1:26:30<29:44,  1.16s/it]

 74%|███████▍  | 4474/6015 [1:26:31<29:42,  1.16s/it]

 74%|███████▍  | 4475/6015 [1:26:32<29:42,  1.16s/it]

 74%|███████▍  | 4476/6015 [1:26:34<29:39,  1.16s/it]

 74%|███████▍  | 4477/6015 [1:26:35<29:39,  1.16s/it]

 74%|███████▍  | 4478/6015 [1:26:36<29:36,  1.16s/it]

 74%|███████▍  | 4479/6015 [1:26:37<29:34,  1.16s/it]

 74%|███████▍  | 4480/6015 [1:26:38<29:33,  1.16s/it]

 74%|███████▍  | 4481/6015 [1:26:39<29:32,  1.16s/it]

 75%|███████▍  | 4482/6015 [1:26:40<29:32,  1.16s/it]

 75%|███████▍  | 4483/6015 [1:26:42<29:31,  1.16s/it]

 75%|███████▍  | 4484/6015 [1:26:43<29:31,  1.16s/it]

 75%|███████▍  | 4485/6015 [1:26:44<29:29,  1.16s/it]

 75%|███████▍  | 4486/6015 [1:26:45<29:28,  1.16s/it]

 75%|███████▍  | 4487/6015 [1:26:46<29:25,  1.16s/it]

 75%|███████▍  | 4488/6015 [1:26:47<29:25,  1.16s/it]

 75%|███████▍  | 4489/6015 [1:26:49<29:24,  1.16s/it]

 75%|███████▍  | 4490/6015 [1:26:50<29:24,  1.16s/it]

 75%|███████▍  | 4491/6015 [1:26:51<29:24,  1.16s/it]

 75%|███████▍  | 4492/6015 [1:26:52<29:24,  1.16s/it]

 75%|███████▍  | 4493/6015 [1:26:53<29:23,  1.16s/it]

 75%|███████▍  | 4494/6015 [1:26:54<29:21,  1.16s/it]

 75%|███████▍  | 4495/6015 [1:26:55<29:19,  1.16s/it]

 75%|███████▍  | 4496/6015 [1:26:57<29:18,  1.16s/it]

 75%|███████▍  | 4497/6015 [1:26:58<29:18,  1.16s/it]

 75%|███████▍  | 4498/6015 [1:26:59<29:15,  1.16s/it]

 75%|███████▍  | 4499/6015 [1:27:00<29:14,  1.16s/it]

 75%|███████▍  | 4500/6015 [1:27:01<29:11,  1.16s/it]

 75%|███████▍  | 4501/6015 [1:27:02<29:10,  1.16s/it]

 75%|███████▍  | 4502/6015 [1:27:04<29:10,  1.16s/it]

 75%|███████▍  | 4503/6015 [1:27:05<29:09,  1.16s/it]

 75%|███████▍  | 4504/6015 [1:27:06<29:08,  1.16s/it]

 75%|███████▍  | 4505/6015 [1:27:07<29:07,  1.16s/it]

 75%|███████▍  | 4506/6015 [1:27:08<29:05,  1.16s/it]

 75%|███████▍  | 4507/6015 [1:27:09<29:04,  1.16s/it]

 75%|███████▍  | 4508/6015 [1:27:11<29:02,  1.16s/it]

 75%|███████▍  | 4509/6015 [1:27:12<29:01,  1.16s/it]

 75%|███████▍  | 4510/6015 [1:27:13<28:59,  1.16s/it]

 75%|███████▍  | 4511/6015 [1:27:14<28:59,  1.16s/it]

 75%|███████▌  | 4512/6015 [1:27:15<28:57,  1.16s/it]

 75%|███████▌  | 4513/6015 [1:27:16<28:56,  1.16s/it]

 75%|███████▌  | 4514/6015 [1:27:17<28:55,  1.16s/it]

 75%|███████▌  | 4515/6015 [1:27:19<28:54,  1.16s/it]

 75%|███████▌  | 4516/6015 [1:27:20<28:54,  1.16s/it]

 75%|███████▌  | 4517/6015 [1:27:21<28:53,  1.16s/it]

 75%|███████▌  | 4518/6015 [1:27:22<28:51,  1.16s/it]

 75%|███████▌  | 4519/6015 [1:27:23<28:49,  1.16s/it]

 75%|███████▌  | 4520/6015 [1:27:24<28:49,  1.16s/it]

 75%|███████▌  | 4521/6015 [1:27:26<28:50,  1.16s/it]

 75%|███████▌  | 4522/6015 [1:27:27<28:48,  1.16s/it]

 75%|███████▌  | 4523/6015 [1:27:28<28:47,  1.16s/it]

 75%|███████▌  | 4524/6015 [1:27:29<28:46,  1.16s/it]

 75%|███████▌  | 4525/6015 [1:27:30<28:45,  1.16s/it]

 75%|███████▌  | 4526/6015 [1:27:31<28:44,  1.16s/it]

 75%|███████▌  | 4527/6015 [1:27:33<28:44,  1.16s/it]

 75%|███████▌  | 4528/6015 [1:27:34<28:40,  1.16s/it]

 75%|███████▌  | 4529/6015 [1:27:35<28:39,  1.16s/it]

 75%|███████▌  | 4530/6015 [1:27:36<28:38,  1.16s/it]

 75%|███████▌  | 4531/6015 [1:27:37<28:38,  1.16s/it]

 75%|███████▌  | 4532/6015 [1:27:38<28:37,  1.16s/it]

 75%|███████▌  | 4533/6015 [1:27:39<28:37,  1.16s/it]

 75%|███████▌  | 4534/6015 [1:27:41<28:35,  1.16s/it]

 75%|███████▌  | 4535/6015 [1:27:42<28:34,  1.16s/it]

 75%|███████▌  | 4536/6015 [1:27:43<28:33,  1.16s/it]

 75%|███████▌  | 4537/6015 [1:27:44<28:29,  1.16s/it]

 75%|███████▌  | 4538/6015 [1:27:45<28:27,  1.16s/it]

 75%|███████▌  | 4539/6015 [1:27:46<28:26,  1.16s/it]

 75%|███████▌  | 4540/6015 [1:27:48<28:26,  1.16s/it]

 75%|███████▌  | 4541/6015 [1:27:49<28:24,  1.16s/it]

 76%|███████▌  | 4542/6015 [1:27:50<28:24,  1.16s/it]

 76%|███████▌  | 4543/6015 [1:27:51<28:24,  1.16s/it]

 76%|███████▌  | 4544/6015 [1:27:52<28:22,  1.16s/it]

 76%|███████▌  | 4545/6015 [1:27:53<28:20,  1.16s/it]

 76%|███████▌  | 4546/6015 [1:27:55<28:19,  1.16s/it]

 76%|███████▌  | 4547/6015 [1:27:56<28:19,  1.16s/it]

 76%|███████▌  | 4548/6015 [1:27:57<28:20,  1.16s/it]

 76%|███████▌  | 4549/6015 [1:27:58<28:19,  1.16s/it]

 76%|███████▌  | 4550/6015 [1:27:59<28:16,  1.16s/it]

 76%|███████▌  | 4551/6015 [1:28:00<28:14,  1.16s/it]

 76%|███████▌  | 4552/6015 [1:28:01<28:13,  1.16s/it]

 76%|███████▌  | 4553/6015 [1:28:03<28:15,  1.16s/it]

 76%|███████▌  | 4554/6015 [1:28:04<28:14,  1.16s/it]

 76%|███████▌  | 4555/6015 [1:28:05<28:11,  1.16s/it]

 76%|███████▌  | 4556/6015 [1:28:06<28:09,  1.16s/it]

 76%|███████▌  | 4557/6015 [1:28:07<28:07,  1.16s/it]

 76%|███████▌  | 4558/6015 [1:28:08<28:05,  1.16s/it]

 76%|███████▌  | 4559/6015 [1:28:10<28:03,  1.16s/it]

 76%|███████▌  | 4560/6015 [1:28:11<28:01,  1.16s/it]

 76%|███████▌  | 4561/6015 [1:28:12<28:01,  1.16s/it]

 76%|███████▌  | 4562/6015 [1:28:13<28:01,  1.16s/it]

 76%|███████▌  | 4563/6015 [1:28:14<28:00,  1.16s/it]

 76%|███████▌  | 4564/6015 [1:28:15<27:59,  1.16s/it]

 76%|███████▌  | 4565/6015 [1:28:17<27:58,  1.16s/it]

 76%|███████▌  | 4566/6015 [1:28:18<27:56,  1.16s/it]

 76%|███████▌  | 4567/6015 [1:28:19<27:56,  1.16s/it]

 76%|███████▌  | 4568/6015 [1:28:20<27:53,  1.16s/it]

 76%|███████▌  | 4569/6015 [1:28:21<27:52,  1.16s/it]

 76%|███████▌  | 4570/6015 [1:28:22<27:51,  1.16s/it]

 76%|███████▌  | 4571/6015 [1:28:23<27:51,  1.16s/it]

 76%|███████▌  | 4572/6015 [1:28:25<27:51,  1.16s/it]

 76%|███████▌  | 4573/6015 [1:28:26<27:50,  1.16s/it]

 76%|███████▌  | 4574/6015 [1:28:27<27:48,  1.16s/it]

 76%|███████▌  | 4575/6015 [1:28:28<27:48,  1.16s/it]

 76%|███████▌  | 4576/6015 [1:28:29<27:45,  1.16s/it]

 76%|███████▌  | 4577/6015 [1:28:30<27:43,  1.16s/it]

 76%|███████▌  | 4578/6015 [1:28:32<27:41,  1.16s/it]

 76%|███████▌  | 4579/6015 [1:28:33<27:40,  1.16s/it]

 76%|███████▌  | 4580/6015 [1:28:34<27:40,  1.16s/it]

 76%|███████▌  | 4581/6015 [1:28:35<27:40,  1.16s/it]

 76%|███████▌  | 4582/6015 [1:28:36<27:39,  1.16s/it]

 76%|███████▌  | 4583/6015 [1:28:37<27:38,  1.16s/it]

 76%|███████▌  | 4584/6015 [1:28:39<27:37,  1.16s/it]

 76%|███████▌  | 4585/6015 [1:28:40<27:36,  1.16s/it]

 76%|███████▌  | 4586/6015 [1:28:41<27:35,  1.16s/it]

 76%|███████▋  | 4587/6015 [1:28:42<27:31,  1.16s/it]

 76%|███████▋  | 4588/6015 [1:28:43<27:30,  1.16s/it]

 76%|███████▋  | 4589/6015 [1:28:44<27:29,  1.16s/it]

 76%|███████▋  | 4590/6015 [1:28:45<27:29,  1.16s/it]

 76%|███████▋  | 4591/6015 [1:28:47<27:28,  1.16s/it]

 76%|███████▋  | 4592/6015 [1:28:48<27:28,  1.16s/it]

 76%|███████▋  | 4593/6015 [1:28:49<27:27,  1.16s/it]

 76%|███████▋  | 4594/6015 [1:28:50<27:26,  1.16s/it]

 76%|███████▋  | 4595/6015 [1:28:51<27:25,  1.16s/it]

 76%|███████▋  | 4596/6015 [1:28:52<27:24,  1.16s/it]

 76%|███████▋  | 4597/6015 [1:28:54<27:22,  1.16s/it]

 76%|███████▋  | 4598/6015 [1:28:55<27:21,  1.16s/it]

 76%|███████▋  | 4599/6015 [1:28:56<27:19,  1.16s/it]

 76%|███████▋  | 4600/6015 [1:28:57<27:16,  1.16s/it]

 76%|███████▋  | 4601/6015 [1:28:58<27:15,  1.16s/it]

 77%|███████▋  | 4602/6015 [1:28:59<27:14,  1.16s/it]

 77%|███████▋  | 4603/6015 [1:29:01<27:14,  1.16s/it]

 77%|███████▋  | 4604/6015 [1:29:02<27:17,  1.16s/it]

 77%|███████▋  | 4605/6015 [1:29:03<27:14,  1.16s/it]

 77%|███████▋  | 4606/6015 [1:29:04<27:12,  1.16s/it]

 77%|███████▋  | 4607/6015 [1:29:05<27:11,  1.16s/it]

 77%|███████▋  | 4608/6015 [1:29:06<27:10,  1.16s/it]

 77%|███████▋  | 4609/6015 [1:29:07<27:10,  1.16s/it]

 77%|███████▋  | 4610/6015 [1:29:09<27:08,  1.16s/it]

 77%|███████▋  | 4611/6015 [1:29:10<27:06,  1.16s/it]

 77%|███████▋  | 4612/6015 [1:29:11<27:03,  1.16s/it]

 77%|███████▋  | 4613/6015 [1:29:12<27:02,  1.16s/it]

 77%|███████▋  | 4614/6015 [1:29:13<27:02,  1.16s/it]

 77%|███████▋  | 4615/6015 [1:29:14<27:00,  1.16s/it]

 77%|███████▋  | 4616/6015 [1:29:16<27:00,  1.16s/it]

 77%|███████▋  | 4617/6015 [1:29:17<26:59,  1.16s/it]

 77%|███████▋  | 4618/6015 [1:29:18<27:01,  1.16s/it]

 77%|███████▋  | 4619/6015 [1:29:19<26:59,  1.16s/it]

 77%|███████▋  | 4620/6015 [1:29:20<26:57,  1.16s/it]

 77%|███████▋  | 4621/6015 [1:29:21<26:54,  1.16s/it]

 77%|███████▋  | 4622/6015 [1:29:23<26:52,  1.16s/it]

 77%|███████▋  | 4623/6015 [1:29:24<26:51,  1.16s/it]

 77%|███████▋  | 4624/6015 [1:29:25<26:50,  1.16s/it]

 77%|███████▋  | 4625/6015 [1:29:26<26:49,  1.16s/it]

 77%|███████▋  | 4626/6015 [1:29:27<26:49,  1.16s/it]

 77%|███████▋  | 4627/6015 [1:29:28<26:48,  1.16s/it]

 77%|███████▋  | 4628/6015 [1:29:29<26:47,  1.16s/it]

 77%|███████▋  | 4629/6015 [1:29:31<26:45,  1.16s/it]

 77%|███████▋  | 4630/6015 [1:29:32<26:42,  1.16s/it]

 77%|███████▋  | 4631/6015 [1:29:33<26:40,  1.16s/it]

 77%|███████▋  | 4632/6015 [1:29:34<26:38,  1.16s/it]

 77%|███████▋  | 4633/6015 [1:29:35<26:38,  1.16s/it]

 77%|███████▋  | 4634/6015 [1:29:36<26:38,  1.16s/it]

 77%|███████▋  | 4635/6015 [1:29:38<26:38,  1.16s/it]

 77%|███████▋  | 4636/6015 [1:29:39<26:36,  1.16s/it]

 77%|███████▋  | 4637/6015 [1:29:40<26:35,  1.16s/it]

 77%|███████▋  | 4638/6015 [1:29:41<26:34,  1.16s/it]

 77%|███████▋  | 4639/6015 [1:29:42<26:33,  1.16s/it]

 77%|███████▋  | 4640/6015 [1:29:43<26:31,  1.16s/it]

 77%|███████▋  | 4641/6015 [1:29:45<26:29,  1.16s/it]

 77%|███████▋  | 4642/6015 [1:29:46<26:28,  1.16s/it]

 77%|███████▋  | 4643/6015 [1:29:47<26:28,  1.16s/it]

 77%|███████▋  | 4644/6015 [1:29:48<26:27,  1.16s/it]

 77%|███████▋  | 4645/6015 [1:29:49<26:27,  1.16s/it]

 77%|███████▋  | 4646/6015 [1:29:50<26:26,  1.16s/it]

 77%|███████▋  | 4647/6015 [1:29:51<26:26,  1.16s/it]

 77%|███████▋  | 4648/6015 [1:29:53<26:22,  1.16s/it]

 77%|███████▋  | 4649/6015 [1:29:54<26:21,  1.16s/it]

 77%|███████▋  | 4650/6015 [1:29:55<26:20,  1.16s/it]

 77%|███████▋  | 4651/6015 [1:29:56<26:17,  1.16s/it]

 77%|███████▋  | 4652/6015 [1:29:57<26:16,  1.16s/it]

 77%|███████▋  | 4653/6015 [1:29:58<26:17,  1.16s/it]

 77%|███████▋  | 4654/6015 [1:30:00<26:15,  1.16s/it]

 77%|███████▋  | 4655/6015 [1:30:01<26:15,  1.16s/it]

 77%|███████▋  | 4656/6015 [1:30:02<26:13,  1.16s/it]

 77%|███████▋  | 4657/6015 [1:30:03<26:14,  1.16s/it]

 77%|███████▋  | 4658/6015 [1:30:04<26:13,  1.16s/it]

 77%|███████▋  | 4659/6015 [1:30:05<26:11,  1.16s/it]

 77%|███████▋  | 4660/6015 [1:30:07<26:09,  1.16s/it]

 77%|███████▋  | 4661/6015 [1:30:08<26:07,  1.16s/it]

 78%|███████▊  | 4662/6015 [1:30:09<26:06,  1.16s/it]

 78%|███████▊  | 4663/6015 [1:30:10<26:07,  1.16s/it]

 78%|███████▊  | 4664/6015 [1:30:11<26:05,  1.16s/it]

 78%|███████▊  | 4665/6015 [1:30:12<26:07,  1.16s/it]

 78%|███████▊  | 4666/6015 [1:30:13<26:06,  1.16s/it]

 78%|███████▊  | 4667/6015 [1:30:15<26:05,  1.16s/it]

 78%|███████▊  | 4668/6015 [1:30:16<26:03,  1.16s/it]

 78%|███████▊  | 4669/6015 [1:30:17<26:03,  1.16s/it]

 78%|███████▊  | 4670/6015 [1:30:18<26:00,  1.16s/it]

 78%|███████▊  | 4671/6015 [1:30:19<25:58,  1.16s/it]

 78%|███████▊  | 4672/6015 [1:30:20<25:57,  1.16s/it]

 78%|███████▊  | 4673/6015 [1:30:22<25:55,  1.16s/it]

 78%|███████▊  | 4674/6015 [1:30:23<25:52,  1.16s/it]

 78%|███████▊  | 4675/6015 [1:30:24<25:51,  1.16s/it]

 78%|███████▊  | 4676/6015 [1:30:25<25:50,  1.16s/it]

 78%|███████▊  | 4677/6015 [1:30:26<25:51,  1.16s/it]

 78%|███████▊  | 4678/6015 [1:30:27<25:50,  1.16s/it]

 78%|███████▊  | 4679/6015 [1:30:29<25:49,  1.16s/it]

 78%|███████▊  | 4680/6015 [1:30:30<25:47,  1.16s/it]

 78%|███████▊  | 4681/6015 [1:30:31<25:48,  1.16s/it]

 78%|███████▊  | 4682/6015 [1:30:32<25:46,  1.16s/it]

 78%|███████▊  | 4683/6015 [1:30:33<25:44,  1.16s/it]

 78%|███████▊  | 4684/6015 [1:30:34<25:42,  1.16s/it]

 78%|███████▊  | 4685/6015 [1:30:36<25:40,  1.16s/it]

 78%|███████▊  | 4686/6015 [1:30:37<25:38,  1.16s/it]

 78%|███████▊  | 4687/6015 [1:30:38<25:38,  1.16s/it]

 78%|███████▊  | 4688/6015 [1:30:39<25:39,  1.16s/it]

 78%|███████▊  | 4689/6015 [1:30:40<25:38,  1.16s/it]

 78%|███████▊  | 4690/6015 [1:30:41<25:37,  1.16s/it]

 78%|███████▊  | 4691/6015 [1:30:42<25:35,  1.16s/it]

 78%|███████▊  | 4692/6015 [1:30:44<25:35,  1.16s/it]

 78%|███████▊  | 4693/6015 [1:30:45<25:33,  1.16s/it]

 78%|███████▊  | 4694/6015 [1:30:46<25:30,  1.16s/it]

 78%|███████▊  | 4695/6015 [1:30:47<25:29,  1.16s/it]

 78%|███████▊  | 4696/6015 [1:30:48<25:27,  1.16s/it]

 78%|███████▊  | 4697/6015 [1:30:49<25:26,  1.16s/it]

 78%|███████▊  | 4698/6015 [1:30:51<25:27,  1.16s/it]

 78%|███████▊  | 4699/6015 [1:30:52<25:26,  1.16s/it]

 78%|███████▊  | 4700/6015 [1:30:53<25:25,  1.16s/it]

 78%|███████▊  | 4701/6015 [1:30:54<25:23,  1.16s/it]

 78%|███████▊  | 4702/6015 [1:30:55<25:23,  1.16s/it]

 78%|███████▊  | 4703/6015 [1:30:56<25:21,  1.16s/it]

 78%|███████▊  | 4704/6015 [1:30:58<25:20,  1.16s/it]

 78%|███████▊  | 4705/6015 [1:30:59<25:19,  1.16s/it]

 78%|███████▊  | 4706/6015 [1:31:00<25:17,  1.16s/it]

 78%|███████▊  | 4707/6015 [1:31:01<25:16,  1.16s/it]

 78%|███████▊  | 4708/6015 [1:31:02<25:14,  1.16s/it]

 78%|███████▊  | 4709/6015 [1:31:03<25:14,  1.16s/it]

 78%|███████▊  | 4710/6015 [1:31:04<25:13,  1.16s/it]

 78%|███████▊  | 4711/6015 [1:31:06<25:11,  1.16s/it]

 78%|███████▊  | 4712/6015 [1:31:07<25:10,  1.16s/it]

 78%|███████▊  | 4713/6015 [1:31:08<25:09,  1.16s/it]

 78%|███████▊  | 4714/6015 [1:31:09<25:09,  1.16s/it]

 78%|███████▊  | 4715/6015 [1:31:10<25:07,  1.16s/it]

 78%|███████▊  | 4716/6015 [1:31:11<25:07,  1.16s/it]

 78%|███████▊  | 4717/6015 [1:31:13<25:05,  1.16s/it]

 78%|███████▊  | 4718/6015 [1:31:14<25:04,  1.16s/it]

 78%|███████▊  | 4719/6015 [1:31:15<25:03,  1.16s/it]

 78%|███████▊  | 4720/6015 [1:31:16<25:03,  1.16s/it]

 78%|███████▊  | 4721/6015 [1:31:17<25:01,  1.16s/it]

 79%|███████▊  | 4722/6015 [1:31:18<25:01,  1.16s/it]

 79%|███████▊  | 4723/6015 [1:31:20<24:59,  1.16s/it]

 79%|███████▊  | 4724/6015 [1:31:21<24:58,  1.16s/it]

 79%|███████▊  | 4725/6015 [1:31:22<24:56,  1.16s/it]

 79%|███████▊  | 4726/6015 [1:31:23<24:54,  1.16s/it]

 79%|███████▊  | 4727/6015 [1:31:24<24:52,  1.16s/it]

 79%|███████▊  | 4728/6015 [1:31:25<24:51,  1.16s/it]

 79%|███████▊  | 4729/6015 [1:31:27<24:50,  1.16s/it]

 79%|███████▊  | 4730/6015 [1:31:28<24:50,  1.16s/it]

 79%|███████▊  | 4731/6015 [1:31:29<24:48,  1.16s/it]

 79%|███████▊  | 4732/6015 [1:31:30<24:47,  1.16s/it]

 79%|███████▊  | 4733/6015 [1:31:31<24:45,  1.16s/it]

 79%|███████▊  | 4734/6015 [1:31:32<24:44,  1.16s/it]

 79%|███████▊  | 4735/6015 [1:31:33<24:42,  1.16s/it]

 79%|███████▊  | 4736/6015 [1:31:35<24:43,  1.16s/it]

 79%|███████▉  | 4737/6015 [1:31:36<24:42,  1.16s/it]

 79%|███████▉  | 4738/6015 [1:31:37<24:42,  1.16s/it]

 79%|███████▉  | 4739/6015 [1:31:38<24:41,  1.16s/it]

 79%|███████▉  | 4740/6015 [1:31:39<24:39,  1.16s/it]

 79%|███████▉  | 4741/6015 [1:31:40<24:38,  1.16s/it]

 79%|███████▉  | 4742/6015 [1:31:42<24:37,  1.16s/it]

 79%|███████▉  | 4743/6015 [1:31:43<24:35,  1.16s/it]

 79%|███████▉  | 4744/6015 [1:31:44<24:33,  1.16s/it]

 79%|███████▉  | 4745/6015 [1:31:45<24:32,  1.16s/it]

 79%|███████▉  | 4746/6015 [1:31:46<24:30,  1.16s/it]

 79%|███████▉  | 4747/6015 [1:31:47<24:29,  1.16s/it]

 79%|███████▉  | 4748/6015 [1:31:49<24:29,  1.16s/it]

 79%|███████▉  | 4749/6015 [1:31:50<24:30,  1.16s/it]

 79%|███████▉  | 4750/6015 [1:31:51<24:29,  1.16s/it]

 79%|███████▉  | 4751/6015 [1:31:52<24:28,  1.16s/it]

 79%|███████▉  | 4752/6015 [1:31:53<24:27,  1.16s/it]

 79%|███████▉  | 4753/6015 [1:31:54<24:25,  1.16s/it]

 79%|███████▉  | 4754/6015 [1:31:56<24:23,  1.16s/it]

 79%|███████▉  | 4755/6015 [1:31:57<24:22,  1.16s/it]

 79%|███████▉  | 4756/6015 [1:31:58<24:19,  1.16s/it]

 79%|███████▉  | 4757/6015 [1:31:59<24:18,  1.16s/it]

 79%|███████▉  | 4758/6015 [1:32:00<24:17,  1.16s/it]

 79%|███████▉  | 4759/6015 [1:32:01<24:17,  1.16s/it]

 79%|███████▉  | 4760/6015 [1:32:02<24:15,  1.16s/it]

 79%|███████▉  | 4761/6015 [1:32:04<24:13,  1.16s/it]

 79%|███████▉  | 4762/6015 [1:32:05<24:14,  1.16s/it]

 79%|███████▉  | 4763/6015 [1:32:06<24:13,  1.16s/it]

 79%|███████▉  | 4764/6015 [1:32:07<24:11,  1.16s/it]

 79%|███████▉  | 4765/6015 [1:32:08<24:10,  1.16s/it]

 79%|███████▉  | 4766/6015 [1:32:09<24:09,  1.16s/it]

 79%|███████▉  | 4767/6015 [1:32:11<24:06,  1.16s/it]

 79%|███████▉  | 4768/6015 [1:32:12<24:04,  1.16s/it]

 79%|███████▉  | 4769/6015 [1:32:13<24:05,  1.16s/it]

 79%|███████▉  | 4770/6015 [1:32:14<24:04,  1.16s/it]

 79%|███████▉  | 4771/6015 [1:32:15<24:04,  1.16s/it]

 79%|███████▉  | 4772/6015 [1:32:16<24:02,  1.16s/it]

 79%|███████▉  | 4773/6015 [1:32:18<24:00,  1.16s/it]

 79%|███████▉  | 4774/6015 [1:32:19<23:59,  1.16s/it]

 79%|███████▉  | 4775/6015 [1:32:20<23:58,  1.16s/it]

 79%|███████▉  | 4776/6015 [1:32:21<23:59,  1.16s/it]

 79%|███████▉  | 4777/6015 [1:32:22<24:04,  1.17s/it]

 79%|███████▉  | 4778/6015 [1:32:23<24:00,  1.16s/it]

 79%|███████▉  | 4779/6015 [1:32:25<23:58,  1.16s/it]

 79%|███████▉  | 4780/6015 [1:32:26<23:55,  1.16s/it]

 79%|███████▉  | 4781/6015 [1:32:27<23:54,  1.16s/it]

 80%|███████▉  | 4782/6015 [1:32:28<23:53,  1.16s/it]

 80%|███████▉  | 4783/6015 [1:32:29<23:51,  1.16s/it]

 80%|███████▉  | 4784/6015 [1:32:30<23:47,  1.16s/it]

 80%|███████▉  | 4785/6015 [1:32:32<23:46,  1.16s/it]

 80%|███████▉  | 4786/6015 [1:32:33<23:44,  1.16s/it]

 80%|███████▉  | 4787/6015 [1:32:34<23:43,  1.16s/it]

 80%|███████▉  | 4788/6015 [1:32:35<23:44,  1.16s/it]

 80%|███████▉  | 4789/6015 [1:32:36<23:44,  1.16s/it]

 80%|███████▉  | 4790/6015 [1:32:37<23:43,  1.16s/it]

 80%|███████▉  | 4791/6015 [1:32:38<23:40,  1.16s/it]

 80%|███████▉  | 4792/6015 [1:32:40<23:38,  1.16s/it]

 80%|███████▉  | 4793/6015 [1:32:41<23:39,  1.16s/it]

 80%|███████▉  | 4794/6015 [1:32:42<23:37,  1.16s/it]

 80%|███████▉  | 4795/6015 [1:32:43<23:35,  1.16s/it]

 80%|███████▉  | 4796/6015 [1:32:44<23:33,  1.16s/it]

 80%|███████▉  | 4797/6015 [1:32:45<23:33,  1.16s/it]

 80%|███████▉  | 4798/6015 [1:32:47<23:33,  1.16s/it]

 80%|███████▉  | 4799/6015 [1:32:48<23:31,  1.16s/it]

 80%|███████▉  | 4800/6015 [1:32:49<23:30,  1.16s/it]

 80%|███████▉  | 4801/6015 [1:32:50<23:28,  1.16s/it]

 80%|███████▉  | 4802/6015 [1:32:51<23:29,  1.16s/it]

 80%|███████▉  | 4803/6015 [1:32:52<23:27,  1.16s/it]

 80%|███████▉  | 4804/6015 [1:32:54<23:25,  1.16s/it]

 80%|███████▉  | 4805/6015 [1:32:55<23:23,  1.16s/it]

 80%|███████▉  | 4806/6015 [1:32:56<23:22,  1.16s/it]

 80%|███████▉  | 4807/6015 [1:32:57<23:22,  1.16s/it]

 80%|███████▉  | 4808/6015 [1:32:58<23:20,  1.16s/it]

 80%|███████▉  | 4809/6015 [1:32:59<23:18,  1.16s/it]

 80%|███████▉  | 4810/6015 [1:33:01<23:18,  1.16s/it]

 80%|███████▉  | 4811/6015 [1:33:02<23:17,  1.16s/it]

 80%|████████  | 4812/6015 [1:33:03<23:16,  1.16s/it]

 80%|████████  | 4813/6015 [1:33:04<23:16,  1.16s/it]

 80%|████████  | 4814/6015 [1:33:05<23:15,  1.16s/it]

 80%|████████  | 4815/6015 [1:33:06<23:13,  1.16s/it]

 80%|████████  | 4816/6015 [1:33:08<23:12,  1.16s/it]

 80%|████████  | 4817/6015 [1:33:09<23:10,  1.16s/it]

 80%|████████  | 4818/6015 [1:33:10<23:07,  1.16s/it]

 80%|████████  | 4819/6015 [1:33:11<23:06,  1.16s/it]

 80%|████████  | 4820/6015 [1:33:12<23:06,  1.16s/it]

 80%|████████  | 4821/6015 [1:33:13<23:06,  1.16s/it]

 80%|████████  | 4822/6015 [1:33:14<23:05,  1.16s/it]

 80%|████████  | 4823/6015 [1:33:16<23:04,  1.16s/it]

 80%|████████  | 4824/6015 [1:33:17<23:03,  1.16s/it]

 80%|████████  | 4825/6015 [1:33:18<23:01,  1.16s/it]

 80%|████████  | 4826/6015 [1:33:19<23:02,  1.16s/it]

 80%|████████  | 4827/6015 [1:33:20<23:00,  1.16s/it]

 80%|████████  | 4828/6015 [1:33:21<22:59,  1.16s/it]

 80%|████████  | 4829/6015 [1:33:23<22:57,  1.16s/it]

 80%|████████  | 4830/6015 [1:33:24<22:54,  1.16s/it]

 80%|████████  | 4831/6015 [1:33:25<22:53,  1.16s/it]

 80%|████████  | 4832/6015 [1:33:26<22:52,  1.16s/it]

 80%|████████  | 4833/6015 [1:33:27<22:50,  1.16s/it]

 80%|████████  | 4834/6015 [1:33:28<22:50,  1.16s/it]

 80%|████████  | 4835/6015 [1:33:30<22:50,  1.16s/it]

 80%|████████  | 4836/6015 [1:33:31<22:50,  1.16s/it]

 80%|████████  | 4837/6015 [1:33:32<22:49,  1.16s/it]

 80%|████████  | 4838/6015 [1:33:33<22:49,  1.16s/it]

 80%|████████  | 4839/6015 [1:33:34<22:46,  1.16s/it]

 80%|████████  | 4840/6015 [1:33:35<22:44,  1.16s/it]

 80%|████████  | 4841/6015 [1:33:37<22:43,  1.16s/it]

 80%|████████  | 4842/6015 [1:33:38<22:43,  1.16s/it]

 81%|████████  | 4843/6015 [1:33:39<22:40,  1.16s/it]

 81%|████████  | 4844/6015 [1:33:40<22:38,  1.16s/it]

 81%|████████  | 4845/6015 [1:33:41<22:37,  1.16s/it]

 81%|████████  | 4846/6015 [1:33:42<22:35,  1.16s/it]

 81%|████████  | 4847/6015 [1:33:44<22:35,  1.16s/it]

 81%|████████  | 4848/6015 [1:33:45<22:35,  1.16s/it]

 81%|████████  | 4849/6015 [1:33:46<22:34,  1.16s/it]

 81%|████████  | 4850/6015 [1:33:47<22:33,  1.16s/it]

 81%|████████  | 4851/6015 [1:33:48<22:31,  1.16s/it]

 81%|████████  | 4852/6015 [1:33:49<22:29,  1.16s/it]

 81%|████████  | 4853/6015 [1:33:50<22:28,  1.16s/it]

 81%|████████  | 4854/6015 [1:33:52<22:27,  1.16s/it]

 81%|████████  | 4855/6015 [1:33:53<22:25,  1.16s/it]

 81%|████████  | 4856/6015 [1:33:54<22:22,  1.16s/it]

 81%|████████  | 4857/6015 [1:33:55<22:22,  1.16s/it]

 81%|████████  | 4858/6015 [1:33:56<22:21,  1.16s/it]

 81%|████████  | 4859/6015 [1:33:57<22:21,  1.16s/it]

 81%|████████  | 4860/6015 [1:33:59<22:20,  1.16s/it]

 81%|████████  | 4861/6015 [1:34:00<22:20,  1.16s/it]

 81%|████████  | 4862/6015 [1:34:01<22:21,  1.16s/it]

 81%|████████  | 4863/6015 [1:34:02<22:20,  1.16s/it]

 81%|████████  | 4864/6015 [1:34:03<22:18,  1.16s/it]

 81%|████████  | 4865/6015 [1:34:04<22:18,  1.16s/it]

 81%|████████  | 4866/6015 [1:34:06<22:17,  1.16s/it]

 81%|████████  | 4867/6015 [1:34:07<22:15,  1.16s/it]

 81%|████████  | 4868/6015 [1:34:08<22:12,  1.16s/it]

 81%|████████  | 4869/6015 [1:34:09<22:10,  1.16s/it]

 81%|████████  | 4870/6015 [1:34:10<22:09,  1.16s/it]

 81%|████████  | 4871/6015 [1:34:11<22:09,  1.16s/it]

 81%|████████  | 4872/6015 [1:34:13<22:08,  1.16s/it]

 81%|████████  | 4873/6015 [1:34:14<22:08,  1.16s/it]

 81%|████████  | 4874/6015 [1:34:15<22:07,  1.16s/it]

 81%|████████  | 4875/6015 [1:34:16<22:05,  1.16s/it]

 81%|████████  | 4876/6015 [1:34:17<22:03,  1.16s/it]

 81%|████████  | 4877/6015 [1:34:18<22:02,  1.16s/it]

 81%|████████  | 4878/6015 [1:34:20<22:02,  1.16s/it]

 81%|████████  | 4879/6015 [1:34:21<22:01,  1.16s/it]

 81%|████████  | 4880/6015 [1:34:22<22:00,  1.16s/it]

 81%|████████  | 4881/6015 [1:34:23<21:58,  1.16s/it]

 81%|████████  | 4882/6015 [1:34:24<21:57,  1.16s/it]

 81%|████████  | 4883/6015 [1:34:25<21:53,  1.16s/it]

 81%|████████  | 4884/6015 [1:34:26<21:52,  1.16s/it]

 81%|████████  | 4885/6015 [1:34:28<21:50,  1.16s/it]

 81%|████████  | 4886/6015 [1:34:29<21:50,  1.16s/it]

 81%|████████  | 4887/6015 [1:34:30<21:50,  1.16s/it]

 81%|████████▏ | 4888/6015 [1:34:31<21:50,  1.16s/it]

 81%|████████▏ | 4889/6015 [1:34:32<21:49,  1.16s/it]

 81%|████████▏ | 4890/6015 [1:34:33<21:48,  1.16s/it]

 81%|████████▏ | 4891/6015 [1:34:35<21:45,  1.16s/it]

 81%|████████▏ | 4892/6015 [1:34:36<21:45,  1.16s/it]

 81%|████████▏ | 4893/6015 [1:34:37<21:44,  1.16s/it]

 81%|████████▏ | 4894/6015 [1:34:38<21:41,  1.16s/it]

 81%|████████▏ | 4895/6015 [1:34:39<21:41,  1.16s/it]

 81%|████████▏ | 4896/6015 [1:34:40<21:41,  1.16s/it]

 81%|████████▏ | 4897/6015 [1:34:42<21:38,  1.16s/it]

 81%|████████▏ | 4898/6015 [1:34:43<21:37,  1.16s/it]

 81%|████████▏ | 4899/6015 [1:34:44<21:36,  1.16s/it]

 81%|████████▏ | 4900/6015 [1:34:45<21:35,  1.16s/it]

 81%|████████▏ | 4901/6015 [1:34:46<21:34,  1.16s/it]

 81%|████████▏ | 4902/6015 [1:34:47<21:33,  1.16s/it]

 82%|████████▏ | 4903/6015 [1:34:49<21:31,  1.16s/it]

 82%|████████▏ | 4904/6015 [1:34:50<21:29,  1.16s/it]

 82%|████████▏ | 4905/6015 [1:34:51<21:29,  1.16s/it]

 82%|████████▏ | 4906/6015 [1:34:52<21:29,  1.16s/it]

 82%|████████▏ | 4907/6015 [1:34:53<21:28,  1.16s/it]

 82%|████████▏ | 4908/6015 [1:34:54<21:27,  1.16s/it]

 82%|████████▏ | 4909/6015 [1:34:56<21:26,  1.16s/it]

 82%|████████▏ | 4910/6015 [1:34:57<21:23,  1.16s/it]

 82%|████████▏ | 4911/6015 [1:34:58<21:21,  1.16s/it]

 82%|████████▏ | 4912/6015 [1:34:59<21:19,  1.16s/it]

 82%|████████▏ | 4913/6015 [1:35:00<21:18,  1.16s/it]

 82%|████████▏ | 4914/6015 [1:35:01<21:16,  1.16s/it]

 82%|████████▏ | 4915/6015 [1:35:03<21:16,  1.16s/it]

 82%|████████▏ | 4916/6015 [1:35:04<21:15,  1.16s/it]

 82%|████████▏ | 4917/6015 [1:35:05<21:14,  1.16s/it]

 82%|████████▏ | 4918/6015 [1:35:06<21:14,  1.16s/it]

 82%|████████▏ | 4919/6015 [1:35:07<21:12,  1.16s/it]

 82%|████████▏ | 4920/6015 [1:35:08<21:11,  1.16s/it]

 82%|████████▏ | 4921/6015 [1:35:09<21:10,  1.16s/it]

 82%|████████▏ | 4922/6015 [1:35:11<21:08,  1.16s/it]

 82%|████████▏ | 4923/6015 [1:35:12<21:07,  1.16s/it]

 82%|████████▏ | 4924/6015 [1:35:13<21:07,  1.16s/it]

 82%|████████▏ | 4925/6015 [1:35:14<21:05,  1.16s/it]

 82%|████████▏ | 4926/6015 [1:35:15<21:04,  1.16s/it]

 82%|████████▏ | 4927/6015 [1:35:16<21:03,  1.16s/it]

 82%|████████▏ | 4928/6015 [1:35:18<21:03,  1.16s/it]

 82%|████████▏ | 4929/6015 [1:35:19<21:02,  1.16s/it]

 82%|████████▏ | 4930/6015 [1:35:20<21:00,  1.16s/it]

 82%|████████▏ | 4931/6015 [1:35:21<20:59,  1.16s/it]

 82%|████████▏ | 4932/6015 [1:35:22<20:57,  1.16s/it]

 82%|████████▏ | 4933/6015 [1:35:23<20:57,  1.16s/it]

 82%|████████▏ | 4934/6015 [1:35:25<20:55,  1.16s/it]

 82%|████████▏ | 4935/6015 [1:35:26<20:55,  1.16s/it]

 82%|████████▏ | 4936/6015 [1:35:27<20:53,  1.16s/it]

 82%|████████▏ | 4937/6015 [1:35:28<20:50,  1.16s/it]

 82%|████████▏ | 4938/6015 [1:35:29<20:48,  1.16s/it]

 82%|████████▏ | 4939/6015 [1:35:30<20:47,  1.16s/it]

 82%|████████▏ | 4940/6015 [1:35:32<20:47,  1.16s/it]

 82%|████████▏ | 4941/6015 [1:35:33<20:47,  1.16s/it]

 82%|████████▏ | 4942/6015 [1:35:34<20:45,  1.16s/it]

 82%|████████▏ | 4943/6015 [1:35:35<20:43,  1.16s/it]

 82%|████████▏ | 4944/6015 [1:35:36<20:43,  1.16s/it]

 82%|████████▏ | 4945/6015 [1:35:37<20:42,  1.16s/it]

 82%|████████▏ | 4946/6015 [1:35:38<20:40,  1.16s/it]

 82%|████████▏ | 4947/6015 [1:35:40<20:39,  1.16s/it]

 82%|████████▏ | 4948/6015 [1:35:41<20:37,  1.16s/it]

 82%|████████▏ | 4949/6015 [1:35:42<20:35,  1.16s/it]

 82%|████████▏ | 4950/6015 [1:35:43<20:35,  1.16s/it]

 82%|████████▏ | 4951/6015 [1:35:44<20:35,  1.16s/it]

 82%|████████▏ | 4952/6015 [1:35:45<20:36,  1.16s/it]

 82%|████████▏ | 4953/6015 [1:35:47<20:35,  1.16s/it]

 82%|████████▏ | 4954/6015 [1:35:48<20:34,  1.16s/it]

 82%|████████▏ | 4955/6015 [1:35:49<20:34,  1.16s/it]

 82%|████████▏ | 4956/6015 [1:35:50<20:32,  1.16s/it]

 82%|████████▏ | 4957/6015 [1:35:51<20:30,  1.16s/it]

 82%|████████▏ | 4958/6015 [1:35:52<20:29,  1.16s/it]

 82%|████████▏ | 4959/6015 [1:35:54<20:28,  1.16s/it]

 82%|████████▏ | 4960/6015 [1:35:55<20:26,  1.16s/it]

 82%|████████▏ | 4961/6015 [1:35:56<20:24,  1.16s/it]

 82%|████████▏ | 4962/6015 [1:35:57<20:24,  1.16s/it]

 83%|████████▎ | 4963/6015 [1:35:58<20:22,  1.16s/it]

 83%|████████▎ | 4964/6015 [1:35:59<20:20,  1.16s/it]

 83%|████████▎ | 4965/6015 [1:36:01<20:19,  1.16s/it]

 83%|████████▎ | 4966/6015 [1:36:02<20:18,  1.16s/it]

 83%|████████▎ | 4967/6015 [1:36:03<20:16,  1.16s/it]

 83%|████████▎ | 4968/6015 [1:36:04<20:16,  1.16s/it]

 83%|████████▎ | 4969/6015 [1:36:05<20:15,  1.16s/it]

 83%|████████▎ | 4970/6015 [1:36:06<20:14,  1.16s/it]

 83%|████████▎ | 4971/6015 [1:36:08<20:13,  1.16s/it]

 83%|████████▎ | 4972/6015 [1:36:09<20:12,  1.16s/it]

 83%|████████▎ | 4973/6015 [1:36:10<20:11,  1.16s/it]

 83%|████████▎ | 4974/6015 [1:36:11<20:11,  1.16s/it]

 83%|████████▎ | 4975/6015 [1:36:12<20:10,  1.16s/it]

 83%|████████▎ | 4976/6015 [1:36:13<20:09,  1.16s/it]

 83%|████████▎ | 4977/6015 [1:36:15<20:07,  1.16s/it]

 83%|████████▎ | 4978/6015 [1:36:16<20:05,  1.16s/it]

 83%|████████▎ | 4979/6015 [1:36:17<20:04,  1.16s/it]

 83%|████████▎ | 4980/6015 [1:36:18<20:02,  1.16s/it]

 83%|████████▎ | 4981/6015 [1:36:19<20:01,  1.16s/it]

 83%|████████▎ | 4982/6015 [1:36:20<20:00,  1.16s/it]

 83%|████████▎ | 4983/6015 [1:36:22<20:00,  1.16s/it]

 83%|████████▎ | 4984/6015 [1:36:23<20:00,  1.16s/it]

 83%|████████▎ | 4985/6015 [1:36:24<20:00,  1.17s/it]

 83%|████████▎ | 4986/6015 [1:36:25<19:58,  1.16s/it]

 83%|████████▎ | 4987/6015 [1:36:26<19:57,  1.17s/it]

 83%|████████▎ | 4988/6015 [1:36:27<19:55,  1.16s/it]

 83%|████████▎ | 4989/6015 [1:36:28<19:54,  1.16s/it]

 83%|████████▎ | 4990/6015 [1:36:30<19:52,  1.16s/it]

 83%|████████▎ | 4991/6015 [1:36:31<19:53,  1.17s/it]

 83%|████████▎ | 4992/6015 [1:36:32<19:52,  1.17s/it]

 83%|████████▎ | 4993/6015 [1:36:33<19:50,  1.17s/it]

 83%|████████▎ | 4994/6015 [1:36:34<19:48,  1.16s/it]

 83%|████████▎ | 4995/6015 [1:36:35<19:45,  1.16s/it]

 83%|████████▎ | 4996/6015 [1:36:37<19:43,  1.16s/it]

 83%|████████▎ | 4997/6015 [1:36:38<19:42,  1.16s/it]

 83%|████████▎ | 4998/6015 [1:36:39<19:41,  1.16s/it]

 83%|████████▎ | 4999/6015 [1:36:40<19:42,  1.16s/it]

 83%|████████▎ | 5000/6015 [1:36:41<19:41,  1.16s/it]

 83%|████████▎ | 5001/6015 [1:36:42<19:41,  1.16s/it]

 83%|████████▎ | 5002/6015 [1:36:44<19:40,  1.16s/it]

 83%|████████▎ | 5003/6015 [1:36:45<19:37,  1.16s/it]

 83%|████████▎ | 5004/6015 [1:36:46<19:36,  1.16s/it]

 83%|████████▎ | 5005/6015 [1:36:47<19:35,  1.16s/it]

 83%|████████▎ | 5006/6015 [1:36:48<19:32,  1.16s/it]

 83%|████████▎ | 5007/6015 [1:36:49<19:31,  1.16s/it]

logging
logging the anndata

 83%|████████▎ | 5008/6015 [1:36:51<20:09,  1.20s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 83%|████████▎ | 5009/6015 [1:36:52<19:55,  1.19s/it]

 83%|████████▎ | 5010/6015 [1:36:53<19:45,  1.18s/it]

 83%|████████▎ | 5011/6015 [1:36:54<19:37,  1.17s/it]

 83%|████████▎ | 5012/6015 [1:36:55<19:32,  1.17s/it]

 83%|████████▎ | 5013/6015 [1:36:57<19:27,  1.17s/it]

 83%|████████▎ | 5014/6015 [1:36:58<19:22,  1.16s/it]

 83%|████████▎ | 5015/6015 [1:36:59<19:20,  1.16s/it]

 83%|████████▎ | 5016/6015 [1:37:00<19:17,  1.16s/it]

 83%|████████▎ | 5017/6015 [1:37:01<19:15,  1.16s/it]

 83%|████████▎ | 5018/6015 [1:37:02<19:13,  1.16s/it]

 83%|████████▎ | 5019/6015 [1:37:03<19:11,  1.16s/it]

 83%|████████▎ | 5020/6015 [1:37:05<19:09,  1.16s/it]

 83%|████████▎ | 5021/6015 [1:37:06<19:08,  1.16s/it]

 83%|████████▎ | 5022/6015 [1:37:07<19:07,  1.16s/it]

 84%|████████▎ | 5023/6015 [1:37:08<19:06,  1.16s/it]

 84%|████████▎ | 5024/6015 [1:37:09<19:04,  1.15s/it]

 84%|████████▎ | 5025/6015 [1:37:10<19:04,  1.16s/it]

 84%|████████▎ | 5026/6015 [1:37:12<19:03,  1.16s/it]

 84%|████████▎ | 5027/6015 [1:37:13<19:01,  1.16s/it]

 84%|████████▎ | 5028/6015 [1:37:14<19:00,  1.16s/it]

 84%|████████▎ | 5029/6015 [1:37:15<18:59,  1.16s/it]

 84%|████████▎ | 5030/6015 [1:37:16<18:58,  1.16s/it]

 84%|████████▎ | 5031/6015 [1:37:17<18:56,  1.16s/it]

 84%|████████▎ | 5032/6015 [1:37:18<18:55,  1.16s/it]

 84%|████████▎ | 5033/6015 [1:37:20<18:55,  1.16s/it]

 84%|████████▎ | 5034/6015 [1:37:21<18:54,  1.16s/it]

 84%|████████▎ | 5035/6015 [1:37:22<18:53,  1.16s/it]

 84%|████████▎ | 5036/6015 [1:37:23<18:51,  1.16s/it]

 84%|████████▎ | 5037/6015 [1:37:24<18:49,  1.16s/it]

 84%|████████▍ | 5038/6015 [1:37:25<18:48,  1.15s/it]

 84%|████████▍ | 5039/6015 [1:37:27<18:47,  1.16s/it]

 84%|████████▍ | 5040/6015 [1:37:28<18:46,  1.16s/it]

 84%|████████▍ | 5041/6015 [1:37:29<18:45,  1.16s/it]

 84%|████████▍ | 5042/6015 [1:37:30<18:44,  1.16s/it]

 84%|████████▍ | 5043/6015 [1:37:31<18:43,  1.16s/it]

 84%|████████▍ | 5044/6015 [1:37:32<18:42,  1.16s/it]

 84%|████████▍ | 5045/6015 [1:37:33<18:41,  1.16s/it]

 84%|████████▍ | 5046/6015 [1:37:35<18:40,  1.16s/it]

 84%|████████▍ | 5047/6015 [1:37:36<18:39,  1.16s/it]

 84%|████████▍ | 5048/6015 [1:37:37<18:38,  1.16s/it]

 84%|████████▍ | 5049/6015 [1:37:38<18:36,  1.16s/it]

 84%|████████▍ | 5050/6015 [1:37:39<18:35,  1.16s/it]

 84%|████████▍ | 5051/6015 [1:37:40<18:34,  1.16s/it]

 84%|████████▍ | 5052/6015 [1:37:42<18:33,  1.16s/it]

 84%|████████▍ | 5053/6015 [1:37:43<18:31,  1.16s/it]

 84%|████████▍ | 5054/6015 [1:37:44<18:30,  1.16s/it]

 84%|████████▍ | 5055/6015 [1:37:45<18:28,  1.16s/it]

 84%|████████▍ | 5056/6015 [1:37:46<18:28,  1.16s/it]

 84%|████████▍ | 5057/6015 [1:37:47<18:28,  1.16s/it]

 84%|████████▍ | 5058/6015 [1:37:49<18:26,  1.16s/it]

 84%|████████▍ | 5059/6015 [1:37:50<18:25,  1.16s/it]

 84%|████████▍ | 5060/6015 [1:37:51<18:24,  1.16s/it]

 84%|████████▍ | 5061/6015 [1:37:52<18:23,  1.16s/it]

 84%|████████▍ | 5062/6015 [1:37:53<18:22,  1.16s/it]

 84%|████████▍ | 5063/6015 [1:37:54<18:20,  1.16s/it]

 84%|████████▍ | 5064/6015 [1:37:55<18:18,  1.15s/it]

 84%|████████▍ | 5065/6015 [1:37:57<18:17,  1.16s/it]

 84%|████████▍ | 5066/6015 [1:37:58<18:16,  1.16s/it]

 84%|████████▍ | 5067/6015 [1:37:59<18:15,  1.16s/it]

 84%|████████▍ | 5068/6015 [1:38:00<18:14,  1.16s/it]

 84%|████████▍ | 5069/6015 [1:38:01<18:14,  1.16s/it]

 84%|████████▍ | 5070/6015 [1:38:02<18:13,  1.16s/it]

 84%|████████▍ | 5071/6015 [1:38:04<18:14,  1.16s/it]

 84%|████████▍ | 5072/6015 [1:38:05<18:13,  1.16s/it]

 84%|████████▍ | 5073/6015 [1:38:06<18:12,  1.16s/it]

 84%|████████▍ | 5074/6015 [1:38:07<18:10,  1.16s/it]

 84%|████████▍ | 5075/6015 [1:38:08<18:07,  1.16s/it]

 84%|████████▍ | 5076/6015 [1:38:09<18:05,  1.16s/it]

 84%|████████▍ | 5077/6015 [1:38:11<18:04,  1.16s/it]

 84%|████████▍ | 5078/6015 [1:38:12<18:04,  1.16s/it]

 84%|████████▍ | 5079/6015 [1:38:13<18:03,  1.16s/it]

 84%|████████▍ | 5080/6015 [1:38:14<18:00,  1.16s/it]

 84%|████████▍ | 5081/6015 [1:38:15<18:00,  1.16s/it]

 84%|████████▍ | 5082/6015 [1:38:16<17:58,  1.16s/it]

 85%|████████▍ | 5083/6015 [1:38:17<17:57,  1.16s/it]

 85%|████████▍ | 5084/6015 [1:38:19<17:55,  1.16s/it]

 85%|████████▍ | 5085/6015 [1:38:20<17:52,  1.15s/it]

 85%|████████▍ | 5086/6015 [1:38:21<17:52,  1.15s/it]

 85%|████████▍ | 5087/6015 [1:38:22<17:52,  1.16s/it]

 85%|████████▍ | 5088/6015 [1:38:23<17:51,  1.16s/it]

 85%|████████▍ | 5089/6015 [1:38:24<17:51,  1.16s/it]

 85%|████████▍ | 5090/6015 [1:38:26<17:49,  1.16s/it]

 85%|████████▍ | 5091/6015 [1:38:27<17:48,  1.16s/it]

 85%|████████▍ | 5092/6015 [1:38:28<17:47,  1.16s/it]

 85%|████████▍ | 5093/6015 [1:38:29<17:45,  1.16s/it]

 85%|████████▍ | 5094/6015 [1:38:30<17:44,  1.16s/it]

 85%|████████▍ | 5095/6015 [1:38:31<17:43,  1.16s/it]

 85%|████████▍ | 5096/6015 [1:38:32<17:42,  1.16s/it]

 85%|████████▍ | 5097/6015 [1:38:34<17:41,  1.16s/it]

 85%|████████▍ | 5098/6015 [1:38:35<17:41,  1.16s/it]

 85%|████████▍ | 5099/6015 [1:38:36<17:40,  1.16s/it]

 85%|████████▍ | 5100/6015 [1:38:37<17:38,  1.16s/it]

 85%|████████▍ | 5101/6015 [1:38:38<17:37,  1.16s/it]

 85%|████████▍ | 5102/6015 [1:38:39<17:35,  1.16s/it]

 85%|████████▍ | 5103/6015 [1:38:41<17:33,  1.15s/it]

 85%|████████▍ | 5104/6015 [1:38:42<17:33,  1.16s/it]

 85%|████████▍ | 5105/6015 [1:38:43<17:32,  1.16s/it]

 85%|████████▍ | 5106/6015 [1:38:44<17:30,  1.16s/it]

 85%|████████▍ | 5107/6015 [1:38:45<17:31,  1.16s/it]

 85%|████████▍ | 5108/6015 [1:38:46<17:29,  1.16s/it]

 85%|████████▍ | 5109/6015 [1:38:48<17:27,  1.16s/it]

 85%|████████▍ | 5110/6015 [1:38:49<17:25,  1.16s/it]

 85%|████████▍ | 5111/6015 [1:38:50<17:25,  1.16s/it]

 85%|████████▍ | 5112/6015 [1:38:51<17:25,  1.16s/it]

 85%|████████▌ | 5113/6015 [1:38:52<17:23,  1.16s/it]

 85%|████████▌ | 5114/6015 [1:38:53<17:22,  1.16s/it]

 85%|████████▌ | 5115/6015 [1:38:54<17:21,  1.16s/it]

 85%|████████▌ | 5116/6015 [1:38:56<17:19,  1.16s/it]

 85%|████████▌ | 5117/6015 [1:38:57<17:18,  1.16s/it]

 85%|████████▌ | 5118/6015 [1:38:58<17:16,  1.16s/it]

 85%|████████▌ | 5119/6015 [1:38:59<17:16,  1.16s/it]

 85%|████████▌ | 5120/6015 [1:39:00<17:14,  1.16s/it]

 85%|████████▌ | 5121/6015 [1:39:01<17:13,  1.16s/it]

 85%|████████▌ | 5122/6015 [1:39:03<17:13,  1.16s/it]

 85%|████████▌ | 5123/6015 [1:39:04<17:11,  1.16s/it]

 85%|████████▌ | 5124/6015 [1:39:05<17:10,  1.16s/it]

 85%|████████▌ | 5125/6015 [1:39:06<17:10,  1.16s/it]

 85%|████████▌ | 5126/6015 [1:39:07<17:09,  1.16s/it]

 85%|████████▌ | 5127/6015 [1:39:08<17:08,  1.16s/it]

 85%|████████▌ | 5128/6015 [1:39:09<17:07,  1.16s/it]

 85%|████████▌ | 5129/6015 [1:39:11<17:06,  1.16s/it]

 85%|████████▌ | 5130/6015 [1:39:12<17:04,  1.16s/it]

 85%|████████▌ | 5131/6015 [1:39:13<17:03,  1.16s/it]

 85%|████████▌ | 5132/6015 [1:39:14<17:01,  1.16s/it]

 85%|████████▌ | 5133/6015 [1:39:15<16:58,  1.15s/it]

 85%|████████▌ | 5134/6015 [1:39:16<16:58,  1.16s/it]

 85%|████████▌ | 5135/6015 [1:39:18<16:57,  1.16s/it]

 85%|████████▌ | 5136/6015 [1:39:19<16:56,  1.16s/it]

 85%|████████▌ | 5137/6015 [1:39:20<16:56,  1.16s/it]

 85%|████████▌ | 5138/6015 [1:39:21<16:54,  1.16s/it]

 85%|████████▌ | 5139/6015 [1:39:22<16:52,  1.16s/it]

 85%|████████▌ | 5140/6015 [1:39:23<16:50,  1.16s/it]

 85%|████████▌ | 5141/6015 [1:39:25<16:49,  1.16s/it]

 85%|████████▌ | 5142/6015 [1:39:26<16:49,  1.16s/it]

 86%|████████▌ | 5143/6015 [1:39:27<16:48,  1.16s/it]

 86%|████████▌ | 5144/6015 [1:39:28<16:47,  1.16s/it]

 86%|████████▌ | 5145/6015 [1:39:29<16:46,  1.16s/it]

 86%|████████▌ | 5146/6015 [1:39:30<16:46,  1.16s/it]

 86%|████████▌ | 5147/6015 [1:39:31<16:44,  1.16s/it]

 86%|████████▌ | 5148/6015 [1:39:33<16:43,  1.16s/it]

 86%|████████▌ | 5149/6015 [1:39:34<16:41,  1.16s/it]

 86%|████████▌ | 5150/6015 [1:39:35<16:39,  1.16s/it]

 86%|████████▌ | 5151/6015 [1:39:36<16:38,  1.16s/it]

 86%|████████▌ | 5152/6015 [1:39:37<16:37,  1.16s/it]

 86%|████████▌ | 5153/6015 [1:39:38<16:37,  1.16s/it]

 86%|████████▌ | 5154/6015 [1:39:40<16:35,  1.16s/it]

 86%|████████▌ | 5155/6015 [1:39:41<16:35,  1.16s/it]

 86%|████████▌ | 5156/6015 [1:39:42<16:34,  1.16s/it]

 86%|████████▌ | 5157/6015 [1:39:43<16:32,  1.16s/it]

 86%|████████▌ | 5158/6015 [1:39:44<16:30,  1.16s/it]

 86%|████████▌ | 5159/6015 [1:39:45<16:29,  1.16s/it]

 86%|████████▌ | 5160/6015 [1:39:46<16:28,  1.16s/it]

 86%|████████▌ | 5161/6015 [1:39:48<16:27,  1.16s/it]

 86%|████████▌ | 5162/6015 [1:39:49<16:25,  1.16s/it]

 86%|████████▌ | 5163/6015 [1:39:50<16:25,  1.16s/it]

 86%|████████▌ | 5164/6015 [1:39:51<16:24,  1.16s/it]

 86%|████████▌ | 5165/6015 [1:39:52<16:23,  1.16s/it]

 86%|████████▌ | 5166/6015 [1:39:53<16:22,  1.16s/it]

 86%|████████▌ | 5167/6015 [1:39:55<16:20,  1.16s/it]

 86%|████████▌ | 5168/6015 [1:39:56<16:19,  1.16s/it]

 86%|████████▌ | 5169/6015 [1:39:57<16:17,  1.16s/it]

 86%|████████▌ | 5170/6015 [1:39:58<16:16,  1.16s/it]

 86%|████████▌ | 5171/6015 [1:39:59<16:16,  1.16s/it]

 86%|████████▌ | 5172/6015 [1:40:00<16:14,  1.16s/it]

 86%|████████▌ | 5173/6015 [1:40:02<16:14,  1.16s/it]

 86%|████████▌ | 5174/6015 [1:40:03<16:13,  1.16s/it]

 86%|████████▌ | 5175/6015 [1:40:04<16:11,  1.16s/it]

 86%|████████▌ | 5176/6015 [1:40:05<16:10,  1.16s/it]

 86%|████████▌ | 5177/6015 [1:40:06<16:08,  1.16s/it]

 86%|████████▌ | 5178/6015 [1:40:07<16:08,  1.16s/it]

 86%|████████▌ | 5179/6015 [1:40:08<16:06,  1.16s/it]

 86%|████████▌ | 5180/6015 [1:40:10<16:05,  1.16s/it]

 86%|████████▌ | 5181/6015 [1:40:11<16:05,  1.16s/it]

 86%|████████▌ | 5182/6015 [1:40:12<16:03,  1.16s/it]

 86%|████████▌ | 5183/6015 [1:40:13<16:03,  1.16s/it]

 86%|████████▌ | 5184/6015 [1:40:14<16:02,  1.16s/it]

 86%|████████▌ | 5185/6015 [1:40:15<16:01,  1.16s/it]

 86%|████████▌ | 5186/6015 [1:40:17<16:00,  1.16s/it]

 86%|████████▌ | 5187/6015 [1:40:18<15:59,  1.16s/it]

 86%|████████▋ | 5188/6015 [1:40:19<15:57,  1.16s/it]

 86%|████████▋ | 5189/6015 [1:40:20<15:56,  1.16s/it]

 86%|████████▋ | 5190/6015 [1:40:21<15:54,  1.16s/it]

 86%|████████▋ | 5191/6015 [1:40:22<15:53,  1.16s/it]

 86%|████████▋ | 5192/6015 [1:40:24<15:51,  1.16s/it]

 86%|████████▋ | 5193/6015 [1:40:25<15:51,  1.16s/it]

 86%|████████▋ | 5194/6015 [1:40:26<15:50,  1.16s/it]

 86%|████████▋ | 5195/6015 [1:40:27<15:51,  1.16s/it]

 86%|████████▋ | 5196/6015 [1:40:28<15:50,  1.16s/it]

 86%|████████▋ | 5197/6015 [1:40:29<15:56,  1.17s/it]

 86%|████████▋ | 5198/6015 [1:40:31<15:52,  1.17s/it]

 86%|████████▋ | 5199/6015 [1:40:32<15:48,  1.16s/it]

 86%|████████▋ | 5200/6015 [1:40:33<15:45,  1.16s/it]

 86%|████████▋ | 5201/6015 [1:40:34<15:44,  1.16s/it]

 86%|████████▋ | 5202/6015 [1:40:35<15:41,  1.16s/it]

 87%|████████▋ | 5203/6015 [1:40:36<15:40,  1.16s/it]

 87%|████████▋ | 5204/6015 [1:40:37<15:39,  1.16s/it]

 87%|████████▋ | 5205/6015 [1:40:39<15:37,  1.16s/it]

 87%|████████▋ | 5206/6015 [1:40:40<15:36,  1.16s/it]

 87%|████████▋ | 5207/6015 [1:40:41<15:35,  1.16s/it]

 87%|████████▋ | 5208/6015 [1:40:42<15:33,  1.16s/it]

 87%|████████▋ | 5209/6015 [1:40:43<15:32,  1.16s/it]

 87%|████████▋ | 5210/6015 [1:40:44<15:31,  1.16s/it]

 87%|████████▋ | 5211/6015 [1:40:46<15:29,  1.16s/it]

 87%|████████▋ | 5212/6015 [1:40:47<15:30,  1.16s/it]

 87%|████████▋ | 5213/6015 [1:40:48<15:29,  1.16s/it]

 87%|████████▋ | 5214/6015 [1:40:49<15:28,  1.16s/it]

 87%|████████▋ | 5215/6015 [1:40:50<15:26,  1.16s/it]

 87%|████████▋ | 5216/6015 [1:40:51<15:25,  1.16s/it]

 87%|████████▋ | 5217/6015 [1:40:53<15:24,  1.16s/it]

 87%|████████▋ | 5218/6015 [1:40:54<15:22,  1.16s/it]

 87%|████████▋ | 5219/6015 [1:40:55<15:21,  1.16s/it]

 87%|████████▋ | 5220/6015 [1:40:56<15:20,  1.16s/it]

 87%|████████▋ | 5221/6015 [1:40:57<15:19,  1.16s/it]

 87%|████████▋ | 5222/6015 [1:40:58<15:18,  1.16s/it]

 87%|████████▋ | 5223/6015 [1:40:59<15:17,  1.16s/it]

 87%|████████▋ | 5224/6015 [1:41:01<15:16,  1.16s/it]

 87%|████████▋ | 5225/6015 [1:41:02<15:14,  1.16s/it]

 87%|████████▋ | 5226/6015 [1:41:03<15:13,  1.16s/it]

 87%|████████▋ | 5227/6015 [1:41:04<15:11,  1.16s/it]

 87%|████████▋ | 5228/6015 [1:41:05<15:10,  1.16s/it]

 87%|████████▋ | 5229/6015 [1:41:06<15:09,  1.16s/it]

 87%|████████▋ | 5230/6015 [1:41:08<15:08,  1.16s/it]

 87%|████████▋ | 5231/6015 [1:41:09<15:07,  1.16s/it]

 87%|████████▋ | 5232/6015 [1:41:10<15:05,  1.16s/it]

 87%|████████▋ | 5233/6015 [1:41:11<15:05,  1.16s/it]

 87%|████████▋ | 5234/6015 [1:41:12<15:04,  1.16s/it]

 87%|████████▋ | 5235/6015 [1:41:13<15:03,  1.16s/it]

 87%|████████▋ | 5236/6015 [1:41:15<15:03,  1.16s/it]

 87%|████████▋ | 5237/6015 [1:41:16<15:01,  1.16s/it]

 87%|████████▋ | 5238/6015 [1:41:17<15:00,  1.16s/it]

 87%|████████▋ | 5239/6015 [1:41:18<14:58,  1.16s/it]

 87%|████████▋ | 5240/6015 [1:41:19<14:57,  1.16s/it]

 87%|████████▋ | 5241/6015 [1:41:20<14:55,  1.16s/it]

 87%|████████▋ | 5242/6015 [1:41:21<14:55,  1.16s/it]

 87%|████████▋ | 5243/6015 [1:41:23<14:54,  1.16s/it]

 87%|████████▋ | 5244/6015 [1:41:24<14:53,  1.16s/it]

 87%|████████▋ | 5245/6015 [1:41:25<14:52,  1.16s/it]

 87%|████████▋ | 5246/6015 [1:41:26<14:51,  1.16s/it]

 87%|████████▋ | 5247/6015 [1:41:27<14:50,  1.16s/it]

 87%|████████▋ | 5248/6015 [1:41:28<14:49,  1.16s/it]

 87%|████████▋ | 5249/6015 [1:41:30<14:48,  1.16s/it]

 87%|████████▋ | 5250/6015 [1:41:31<14:47,  1.16s/it]

 87%|████████▋ | 5251/6015 [1:41:32<14:45,  1.16s/it]

 87%|████████▋ | 5252/6015 [1:41:33<14:43,  1.16s/it]

 87%|████████▋ | 5253/6015 [1:41:34<14:41,  1.16s/it]

 87%|████████▋ | 5254/6015 [1:41:35<14:39,  1.16s/it]

 87%|████████▋ | 5255/6015 [1:41:37<14:39,  1.16s/it]

 87%|████████▋ | 5256/6015 [1:41:38<14:38,  1.16s/it]

 87%|████████▋ | 5257/6015 [1:41:39<14:37,  1.16s/it]

 87%|████████▋ | 5258/6015 [1:41:40<14:36,  1.16s/it]

 87%|████████▋ | 5259/6015 [1:41:41<14:34,  1.16s/it]

 87%|████████▋ | 5260/6015 [1:41:42<14:33,  1.16s/it]

 87%|████████▋ | 5261/6015 [1:41:43<14:32,  1.16s/it]

 87%|████████▋ | 5262/6015 [1:41:45<14:30,  1.16s/it]

 87%|████████▋ | 5263/6015 [1:41:46<14:30,  1.16s/it]

 88%|████████▊ | 5264/6015 [1:41:47<14:29,  1.16s/it]

 88%|████████▊ | 5265/6015 [1:41:48<14:28,  1.16s/it]

 88%|████████▊ | 5266/6015 [1:41:49<14:27,  1.16s/it]

 88%|████████▊ | 5267/6015 [1:41:50<14:26,  1.16s/it]

 88%|████████▊ | 5268/6015 [1:41:52<14:24,  1.16s/it]

 88%|████████▊ | 5269/6015 [1:41:53<14:24,  1.16s/it]

 88%|████████▊ | 5270/6015 [1:41:54<14:23,  1.16s/it]

 88%|████████▊ | 5271/6015 [1:41:55<14:21,  1.16s/it]

 88%|████████▊ | 5272/6015 [1:41:56<14:19,  1.16s/it]

 88%|████████▊ | 5273/6015 [1:41:57<14:18,  1.16s/it]

 88%|████████▊ | 5274/6015 [1:41:59<14:17,  1.16s/it]

 88%|████████▊ | 5275/6015 [1:42:00<14:17,  1.16s/it]

 88%|████████▊ | 5276/6015 [1:42:01<14:17,  1.16s/it]

 88%|████████▊ | 5277/6015 [1:42:02<14:16,  1.16s/it]

 88%|████████▊ | 5278/6015 [1:42:03<14:14,  1.16s/it]

 88%|████████▊ | 5279/6015 [1:42:04<14:13,  1.16s/it]

 88%|████████▊ | 5280/6015 [1:42:05<14:12,  1.16s/it]

 88%|████████▊ | 5281/6015 [1:42:07<14:10,  1.16s/it]

 88%|████████▊ | 5282/6015 [1:42:08<14:09,  1.16s/it]

 88%|████████▊ | 5283/6015 [1:42:09<14:07,  1.16s/it]

 88%|████████▊ | 5284/6015 [1:42:10<14:06,  1.16s/it]

 88%|████████▊ | 5285/6015 [1:42:11<14:05,  1.16s/it]

 88%|████████▊ | 5286/6015 [1:42:12<14:04,  1.16s/it]

 88%|████████▊ | 5287/6015 [1:42:14<14:03,  1.16s/it]

 88%|████████▊ | 5288/6015 [1:42:15<14:02,  1.16s/it]

 88%|████████▊ | 5289/6015 [1:42:16<14:01,  1.16s/it]

 88%|████████▊ | 5290/6015 [1:42:17<14:00,  1.16s/it]

 88%|████████▊ | 5291/6015 [1:42:18<13:58,  1.16s/it]

 88%|████████▊ | 5292/6015 [1:42:19<13:56,  1.16s/it]

 88%|████████▊ | 5293/6015 [1:42:21<13:55,  1.16s/it]

 88%|████████▊ | 5294/6015 [1:42:22<13:54,  1.16s/it]

 88%|████████▊ | 5295/6015 [1:42:23<13:53,  1.16s/it]

 88%|████████▊ | 5296/6015 [1:42:24<13:52,  1.16s/it]

 88%|████████▊ | 5297/6015 [1:42:25<13:51,  1.16s/it]

 88%|████████▊ | 5298/6015 [1:42:26<13:50,  1.16s/it]

 88%|████████▊ | 5299/6015 [1:42:27<13:50,  1.16s/it]

 88%|████████▊ | 5300/6015 [1:42:29<13:49,  1.16s/it]

 88%|████████▊ | 5301/6015 [1:42:30<13:47,  1.16s/it]

 88%|████████▊ | 5302/6015 [1:42:31<13:46,  1.16s/it]

 88%|████████▊ | 5303/6015 [1:42:32<13:46,  1.16s/it]

 88%|████████▊ | 5304/6015 [1:42:33<13:46,  1.16s/it]

 88%|████████▊ | 5305/6015 [1:42:34<13:45,  1.16s/it]

 88%|████████▊ | 5306/6015 [1:42:36<13:42,  1.16s/it]

 88%|████████▊ | 5307/6015 [1:42:37<13:41,  1.16s/it]

 88%|████████▊ | 5308/6015 [1:42:38<13:38,  1.16s/it]

 88%|████████▊ | 5309/6015 [1:42:39<13:37,  1.16s/it]

 88%|████████▊ | 5310/6015 [1:42:40<13:36,  1.16s/it]

 88%|████████▊ | 5311/6015 [1:42:41<13:36,  1.16s/it]

 88%|████████▊ | 5312/6015 [1:42:43<13:35,  1.16s/it]

 88%|████████▊ | 5313/6015 [1:42:44<13:33,  1.16s/it]

 88%|████████▊ | 5314/6015 [1:42:45<13:32,  1.16s/it]

 88%|████████▊ | 5315/6015 [1:42:46<13:31,  1.16s/it]

 88%|████████▊ | 5316/6015 [1:42:47<13:29,  1.16s/it]

 88%|████████▊ | 5317/6015 [1:42:48<13:28,  1.16s/it]

 88%|████████▊ | 5318/6015 [1:42:50<13:27,  1.16s/it]

 88%|████████▊ | 5319/6015 [1:42:51<13:25,  1.16s/it]

 88%|████████▊ | 5320/6015 [1:42:52<13:25,  1.16s/it]

 88%|████████▊ | 5321/6015 [1:42:53<13:25,  1.16s/it]

 88%|████████▊ | 5322/6015 [1:42:54<13:24,  1.16s/it]

 88%|████████▊ | 5323/6015 [1:42:55<13:22,  1.16s/it]

 89%|████████▊ | 5324/6015 [1:42:56<13:21,  1.16s/it]

 89%|████████▊ | 5325/6015 [1:42:58<13:20,  1.16s/it]

 89%|████████▊ | 5326/6015 [1:42:59<13:18,  1.16s/it]

 89%|████████▊ | 5327/6015 [1:43:00<13:17,  1.16s/it]

 89%|████████▊ | 5328/6015 [1:43:01<13:16,  1.16s/it]

 89%|████████▊ | 5329/6015 [1:43:02<13:14,  1.16s/it]

 89%|████████▊ | 5330/6015 [1:43:03<13:12,  1.16s/it]

 89%|████████▊ | 5331/6015 [1:43:05<13:12,  1.16s/it]

 89%|████████▊ | 5332/6015 [1:43:06<13:11,  1.16s/it]

 89%|████████▊ | 5333/6015 [1:43:07<13:10,  1.16s/it]

 89%|████████▊ | 5334/6015 [1:43:08<13:09,  1.16s/it]

 89%|████████▊ | 5335/6015 [1:43:09<13:08,  1.16s/it]

 89%|████████▊ | 5336/6015 [1:43:10<13:07,  1.16s/it]

 89%|████████▊ | 5337/6015 [1:43:12<13:07,  1.16s/it]

 89%|████████▊ | 5338/6015 [1:43:13<13:05,  1.16s/it]

 89%|████████▉ | 5339/6015 [1:43:14<13:03,  1.16s/it]

 89%|████████▉ | 5340/6015 [1:43:15<13:02,  1.16s/it]

 89%|████████▉ | 5341/6015 [1:43:16<13:00,  1.16s/it]

 89%|████████▉ | 5342/6015 [1:43:17<13:00,  1.16s/it]

 89%|████████▉ | 5343/6015 [1:43:18<12:59,  1.16s/it]

 89%|████████▉ | 5344/6015 [1:43:20<12:58,  1.16s/it]

 89%|████████▉ | 5345/6015 [1:43:21<12:57,  1.16s/it]

 89%|████████▉ | 5346/6015 [1:43:22<12:55,  1.16s/it]

 89%|████████▉ | 5347/6015 [1:43:23<12:53,  1.16s/it]

 89%|████████▉ | 5348/6015 [1:43:24<12:52,  1.16s/it]

 89%|████████▉ | 5349/6015 [1:43:25<12:50,  1.16s/it]

 89%|████████▉ | 5350/6015 [1:43:27<12:50,  1.16s/it]

 89%|████████▉ | 5351/6015 [1:43:28<12:49,  1.16s/it]

 89%|████████▉ | 5352/6015 [1:43:29<12:48,  1.16s/it]

 89%|████████▉ | 5353/6015 [1:43:30<12:46,  1.16s/it]

 89%|████████▉ | 5354/6015 [1:43:31<12:45,  1.16s/it]

 89%|████████▉ | 5355/6015 [1:43:32<12:45,  1.16s/it]

 89%|████████▉ | 5356/6015 [1:43:34<12:44,  1.16s/it]

 89%|████████▉ | 5357/6015 [1:43:35<12:44,  1.16s/it]

 89%|████████▉ | 5358/6015 [1:43:36<12:43,  1.16s/it]

 89%|████████▉ | 5359/6015 [1:43:37<12:41,  1.16s/it]

 89%|████████▉ | 5360/6015 [1:43:38<12:39,  1.16s/it]

 89%|████████▉ | 5361/6015 [1:43:39<12:39,  1.16s/it]

 89%|████████▉ | 5362/6015 [1:43:41<12:37,  1.16s/it]

 89%|████████▉ | 5363/6015 [1:43:42<12:37,  1.16s/it]

 89%|████████▉ | 5364/6015 [1:43:43<12:35,  1.16s/it]

 89%|████████▉ | 5365/6015 [1:43:44<12:33,  1.16s/it]

 89%|████████▉ | 5366/6015 [1:43:45<12:31,  1.16s/it]

 89%|████████▉ | 5367/6015 [1:43:46<12:31,  1.16s/it]

 89%|████████▉ | 5368/6015 [1:43:47<12:30,  1.16s/it]

 89%|████████▉ | 5369/6015 [1:43:49<12:29,  1.16s/it]

 89%|████████▉ | 5370/6015 [1:43:50<12:28,  1.16s/it]

 89%|████████▉ | 5371/6015 [1:43:51<12:26,  1.16s/it]

 89%|████████▉ | 5372/6015 [1:43:52<12:26,  1.16s/it]

 89%|████████▉ | 5373/6015 [1:43:53<12:25,  1.16s/it]

 89%|████████▉ | 5374/6015 [1:43:54<12:22,  1.16s/it]

 89%|████████▉ | 5375/6015 [1:43:56<12:21,  1.16s/it]

 89%|████████▉ | 5376/6015 [1:43:57<12:20,  1.16s/it]

 89%|████████▉ | 5377/6015 [1:43:58<12:19,  1.16s/it]

 89%|████████▉ | 5378/6015 [1:43:59<12:18,  1.16s/it]

 89%|████████▉ | 5379/6015 [1:44:00<12:17,  1.16s/it]

 89%|████████▉ | 5380/6015 [1:44:01<12:16,  1.16s/it]

 89%|████████▉ | 5381/6015 [1:44:03<12:16,  1.16s/it]

 89%|████████▉ | 5382/6015 [1:44:04<12:14,  1.16s/it]

 89%|████████▉ | 5383/6015 [1:44:05<12:14,  1.16s/it]

 90%|████████▉ | 5384/6015 [1:44:06<12:13,  1.16s/it]

 90%|████████▉ | 5385/6015 [1:44:07<12:11,  1.16s/it]

 90%|████████▉ | 5386/6015 [1:44:08<12:10,  1.16s/it]

 90%|████████▉ | 5387/6015 [1:44:10<12:08,  1.16s/it]

 90%|████████▉ | 5388/6015 [1:44:11<12:06,  1.16s/it]

 90%|████████▉ | 5389/6015 [1:44:12<12:06,  1.16s/it]

 90%|████████▉ | 5390/6015 [1:44:13<12:05,  1.16s/it]

 90%|████████▉ | 5391/6015 [1:44:14<12:04,  1.16s/it]

 90%|████████▉ | 5392/6015 [1:44:15<12:03,  1.16s/it]

 90%|████████▉ | 5393/6015 [1:44:16<12:02,  1.16s/it]

 90%|████████▉ | 5394/6015 [1:44:18<12:01,  1.16s/it]

 90%|████████▉ | 5395/6015 [1:44:19<12:00,  1.16s/it]

 90%|████████▉ | 5396/6015 [1:44:20<11:58,  1.16s/it]

 90%|████████▉ | 5397/6015 [1:44:21<11:56,  1.16s/it]

 90%|████████▉ | 5398/6015 [1:44:22<11:55,  1.16s/it]

 90%|████████▉ | 5399/6015 [1:44:23<11:54,  1.16s/it]

 90%|████████▉ | 5400/6015 [1:44:25<11:52,  1.16s/it]

 90%|████████▉ | 5401/6015 [1:44:26<11:52,  1.16s/it]

 90%|████████▉ | 5402/6015 [1:44:27<11:51,  1.16s/it]

 90%|████████▉ | 5403/6015 [1:44:28<11:51,  1.16s/it]

 90%|████████▉ | 5404/6015 [1:44:29<11:49,  1.16s/it]

 90%|████████▉ | 5405/6015 [1:44:30<11:48,  1.16s/it]

 90%|████████▉ | 5406/6015 [1:44:32<11:46,  1.16s/it]

 90%|████████▉ | 5407/6015 [1:44:33<11:45,  1.16s/it]

 90%|████████▉ | 5408/6015 [1:44:34<11:44,  1.16s/it]

 90%|████████▉ | 5409/6015 [1:44:35<11:42,  1.16s/it]

 90%|████████▉ | 5410/6015 [1:44:36<11:41,  1.16s/it]

 90%|████████▉ | 5411/6015 [1:44:37<11:39,  1.16s/it]

 90%|████████▉ | 5412/6015 [1:44:39<11:39,  1.16s/it]

 90%|████████▉ | 5413/6015 [1:44:40<11:38,  1.16s/it]

 90%|█████████ | 5414/6015 [1:44:41<11:37,  1.16s/it]

 90%|█████████ | 5415/6015 [1:44:42<11:36,  1.16s/it]

 90%|█████████ | 5416/6015 [1:44:43<11:36,  1.16s/it]

 90%|█████████ | 5417/6015 [1:44:44<11:35,  1.16s/it]

 90%|█████████ | 5418/6015 [1:44:46<11:34,  1.16s/it]

 90%|█████████ | 5419/6015 [1:44:47<11:31,  1.16s/it]

 90%|█████████ | 5420/6015 [1:44:48<11:31,  1.16s/it]

 90%|█████████ | 5421/6015 [1:44:49<11:30,  1.16s/it]

 90%|█████████ | 5422/6015 [1:44:50<11:29,  1.16s/it]

 90%|█████████ | 5423/6015 [1:44:51<11:28,  1.16s/it]

 90%|█████████ | 5424/6015 [1:44:52<11:27,  1.16s/it]

 90%|█████████ | 5425/6015 [1:44:54<11:25,  1.16s/it]

 90%|█████████ | 5426/6015 [1:44:55<11:23,  1.16s/it]

 90%|█████████ | 5427/6015 [1:44:56<11:22,  1.16s/it]

 90%|█████████ | 5428/6015 [1:44:57<11:20,  1.16s/it]

 90%|█████████ | 5429/6015 [1:44:58<11:19,  1.16s/it]

 90%|█████████ | 5430/6015 [1:44:59<11:18,  1.16s/it]

 90%|█████████ | 5431/6015 [1:45:01<11:17,  1.16s/it]

 90%|█████████ | 5432/6015 [1:45:02<11:17,  1.16s/it]

 90%|█████████ | 5433/6015 [1:45:03<11:16,  1.16s/it]

 90%|█████████ | 5434/6015 [1:45:04<11:15,  1.16s/it]

 90%|█████████ | 5435/6015 [1:45:05<11:14,  1.16s/it]

 90%|█████████ | 5436/6015 [1:45:06<11:12,  1.16s/it]

 90%|█████████ | 5437/6015 [1:45:08<11:11,  1.16s/it]

 90%|█████████ | 5438/6015 [1:45:09<11:09,  1.16s/it]

 90%|█████████ | 5439/6015 [1:45:10<11:08,  1.16s/it]

 90%|█████████ | 5440/6015 [1:45:11<11:06,  1.16s/it]

 90%|█████████ | 5441/6015 [1:45:12<11:06,  1.16s/it]

 90%|█████████ | 5442/6015 [1:45:13<11:04,  1.16s/it]

 90%|█████████ | 5443/6015 [1:45:15<11:03,  1.16s/it]

 91%|█████████ | 5444/6015 [1:45:16<11:01,  1.16s/it]

 91%|█████████ | 5445/6015 [1:45:17<11:01,  1.16s/it]

 91%|█████████ | 5446/6015 [1:45:18<11:00,  1.16s/it]

 91%|█████████ | 5447/6015 [1:45:19<10:59,  1.16s/it]

 91%|█████████ | 5448/6015 [1:45:20<10:57,  1.16s/it]

 91%|█████████ | 5449/6015 [1:45:22<10:56,  1.16s/it]

 91%|█████████ | 5450/6015 [1:45:23<10:55,  1.16s/it]

 91%|█████████ | 5451/6015 [1:45:24<10:54,  1.16s/it]

 91%|█████████ | 5452/6015 [1:45:25<10:53,  1.16s/it]

 91%|█████████ | 5453/6015 [1:45:26<10:52,  1.16s/it]

 91%|█████████ | 5454/6015 [1:45:27<10:52,  1.16s/it]

 91%|█████████ | 5455/6015 [1:45:28<10:51,  1.16s/it]

 91%|█████████ | 5456/6015 [1:45:30<10:49,  1.16s/it]

 91%|█████████ | 5457/6015 [1:45:31<10:48,  1.16s/it]

 91%|█████████ | 5458/6015 [1:45:32<10:46,  1.16s/it]

 91%|█████████ | 5459/6015 [1:45:33<10:45,  1.16s/it]

 91%|█████████ | 5460/6015 [1:45:34<10:44,  1.16s/it]

 91%|█████████ | 5461/6015 [1:45:35<10:42,  1.16s/it]

 91%|█████████ | 5462/6015 [1:45:37<10:41,  1.16s/it]

 91%|█████████ | 5463/6015 [1:45:38<10:39,  1.16s/it]

 91%|█████████ | 5464/6015 [1:45:39<10:39,  1.16s/it]

 91%|█████████ | 5465/6015 [1:45:40<10:38,  1.16s/it]

 91%|█████████ | 5466/6015 [1:45:41<10:37,  1.16s/it]

 91%|█████████ | 5467/6015 [1:45:42<10:36,  1.16s/it]

 91%|█████████ | 5468/6015 [1:45:44<10:34,  1.16s/it]

 91%|█████████ | 5469/6015 [1:45:45<10:33,  1.16s/it]

 91%|█████████ | 5470/6015 [1:45:46<10:32,  1.16s/it]

 91%|█████████ | 5471/6015 [1:45:47<10:31,  1.16s/it]

 91%|█████████ | 5472/6015 [1:45:48<10:30,  1.16s/it]

 91%|█████████ | 5473/6015 [1:45:49<10:28,  1.16s/it]

 91%|█████████ | 5474/6015 [1:45:51<10:28,  1.16s/it]

 91%|█████████ | 5475/6015 [1:45:52<10:27,  1.16s/it]

 91%|█████████ | 5476/6015 [1:45:53<10:26,  1.16s/it]

 91%|█████████ | 5477/6015 [1:45:54<10:26,  1.16s/it]

 91%|█████████ | 5478/6015 [1:45:55<10:25,  1.16s/it]

 91%|█████████ | 5479/6015 [1:45:56<10:23,  1.16s/it]

 91%|█████████ | 5480/6015 [1:45:58<10:21,  1.16s/it]

 91%|█████████ | 5481/6015 [1:45:59<10:20,  1.16s/it]

 91%|█████████ | 5482/6015 [1:46:00<10:19,  1.16s/it]

 91%|█████████ | 5483/6015 [1:46:01<10:18,  1.16s/it]

 91%|█████████ | 5484/6015 [1:46:02<10:16,  1.16s/it]

 91%|█████████ | 5485/6015 [1:46:03<10:15,  1.16s/it]

 91%|█████████ | 5486/6015 [1:46:04<10:14,  1.16s/it]

 91%|█████████ | 5487/6015 [1:46:06<10:13,  1.16s/it]

 91%|█████████ | 5488/6015 [1:46:07<10:12,  1.16s/it]

 91%|█████████▏| 5489/6015 [1:46:08<10:10,  1.16s/it]

 91%|█████████▏| 5490/6015 [1:46:09<10:08,  1.16s/it]

 91%|█████████▏| 5491/6015 [1:46:10<10:07,  1.16s/it]

 91%|█████████▏| 5492/6015 [1:46:11<10:07,  1.16s/it]

 91%|█████████▏| 5493/6015 [1:46:13<10:06,  1.16s/it]

 91%|█████████▏| 5494/6015 [1:46:14<10:05,  1.16s/it]

 91%|█████████▏| 5495/6015 [1:46:15<10:04,  1.16s/it]

 91%|█████████▏| 5496/6015 [1:46:16<10:02,  1.16s/it]

 91%|█████████▏| 5497/6015 [1:46:17<10:01,  1.16s/it]

 91%|█████████▏| 5498/6015 [1:46:18<10:01,  1.16s/it]

 91%|█████████▏| 5499/6015 [1:46:20<10:00,  1.16s/it]

 91%|█████████▏| 5500/6015 [1:46:21<09:58,  1.16s/it]

 91%|█████████▏| 5501/6015 [1:46:22<09:57,  1.16s/it]

 91%|█████████▏| 5502/6015 [1:46:23<09:55,  1.16s/it]

 91%|█████████▏| 5503/6015 [1:46:24<09:53,  1.16s/it]

 92%|█████████▏| 5504/6015 [1:46:25<09:52,  1.16s/it]

 92%|█████████▏| 5505/6015 [1:46:27<09:52,  1.16s/it]

 92%|█████████▏| 5506/6015 [1:46:28<09:51,  1.16s/it]

 92%|█████████▏| 5507/6015 [1:46:29<09:50,  1.16s/it]

 92%|█████████▏| 5508/6015 [1:46:30<09:49,  1.16s/it]

 92%|█████████▏| 5509/6015 [1:46:31<09:47,  1.16s/it]

 92%|█████████▏| 5510/6015 [1:46:32<09:46,  1.16s/it]

 92%|█████████▏| 5511/6015 [1:46:34<09:45,  1.16s/it]

 92%|█████████▏| 5512/6015 [1:46:35<09:44,  1.16s/it]

 92%|█████████▏| 5513/6015 [1:46:36<09:43,  1.16s/it]

 92%|█████████▏| 5514/6015 [1:46:37<09:41,  1.16s/it]

 92%|█████████▏| 5515/6015 [1:46:38<09:40,  1.16s/it]

 92%|█████████▏| 5516/6015 [1:46:39<09:39,  1.16s/it]

 92%|█████████▏| 5517/6015 [1:46:40<09:38,  1.16s/it]

 92%|█████████▏| 5518/6015 [1:46:42<09:37,  1.16s/it]

 92%|█████████▏| 5519/6015 [1:46:43<09:36,  1.16s/it]

 92%|█████████▏| 5520/6015 [1:46:44<09:35,  1.16s/it]

 92%|█████████▏| 5521/6015 [1:46:45<09:33,  1.16s/it]

 92%|█████████▏| 5522/6015 [1:46:46<09:32,  1.16s/it]

 92%|█████████▏| 5523/6015 [1:46:47<09:31,  1.16s/it]

 92%|█████████▏| 5524/6015 [1:46:49<09:30,  1.16s/it]

 92%|█████████▏| 5525/6015 [1:46:50<09:28,  1.16s/it]

 92%|█████████▏| 5526/6015 [1:46:51<09:28,  1.16s/it]

 92%|█████████▏| 5527/6015 [1:46:52<09:26,  1.16s/it]

 92%|█████████▏| 5528/6015 [1:46:53<09:25,  1.16s/it]

 92%|█████████▏| 5529/6015 [1:46:54<09:24,  1.16s/it]

 92%|█████████▏| 5530/6015 [1:46:56<09:24,  1.16s/it]

 92%|█████████▏| 5531/6015 [1:46:57<09:22,  1.16s/it]

 92%|█████████▏| 5532/6015 [1:46:58<09:21,  1.16s/it]

 92%|█████████▏| 5533/6015 [1:46:59<09:20,  1.16s/it]

 92%|█████████▏| 5534/6015 [1:47:00<09:19,  1.16s/it]

 92%|█████████▏| 5535/6015 [1:47:01<09:17,  1.16s/it]

 92%|█████████▏| 5536/6015 [1:47:03<09:16,  1.16s/it]

 92%|█████████▏| 5537/6015 [1:47:04<09:15,  1.16s/it]

 92%|█████████▏| 5538/6015 [1:47:05<09:14,  1.16s/it]

 92%|█████████▏| 5539/6015 [1:47:06<09:12,  1.16s/it]

 92%|█████████▏| 5540/6015 [1:47:07<09:12,  1.16s/it]

 92%|█████████▏| 5541/6015 [1:47:08<09:11,  1.16s/it]

 92%|█████████▏| 5542/6015 [1:47:10<09:10,  1.16s/it]

 92%|█████████▏| 5543/6015 [1:47:11<09:09,  1.16s/it]

 92%|█████████▏| 5544/6015 [1:47:12<09:07,  1.16s/it]

 92%|█████████▏| 5545/6015 [1:47:13<09:05,  1.16s/it]

 92%|█████████▏| 5546/6015 [1:47:14<09:04,  1.16s/it]

 92%|█████████▏| 5547/6015 [1:47:15<09:03,  1.16s/it]

 92%|█████████▏| 5548/6015 [1:47:17<09:02,  1.16s/it]

 92%|█████████▏| 5549/6015 [1:47:18<09:01,  1.16s/it]

 92%|█████████▏| 5550/6015 [1:47:19<08:59,  1.16s/it]

 92%|█████████▏| 5551/6015 [1:47:20<08:58,  1.16s/it]

 92%|█████████▏| 5552/6015 [1:47:21<08:56,  1.16s/it]

 92%|█████████▏| 5553/6015 [1:47:22<08:56,  1.16s/it]

 92%|█████████▏| 5554/6015 [1:47:23<08:55,  1.16s/it]

 92%|█████████▏| 5555/6015 [1:47:25<08:54,  1.16s/it]

 92%|█████████▏| 5556/6015 [1:47:26<08:52,  1.16s/it]

 92%|█████████▏| 5557/6015 [1:47:27<08:51,  1.16s/it]

 92%|█████████▏| 5558/6015 [1:47:28<08:50,  1.16s/it]

 92%|█████████▏| 5559/6015 [1:47:29<08:49,  1.16s/it]

 92%|█████████▏| 5560/6015 [1:47:30<08:48,  1.16s/it]

 92%|█████████▏| 5561/6015 [1:47:32<08:46,  1.16s/it]

 92%|█████████▏| 5562/6015 [1:47:33<08:45,  1.16s/it]

 92%|█████████▏| 5563/6015 [1:47:34<08:44,  1.16s/it]

 93%|█████████▎| 5564/6015 [1:47:35<08:43,  1.16s/it]

 93%|█████████▎| 5565/6015 [1:47:36<08:42,  1.16s/it]

 93%|█████████▎| 5566/6015 [1:47:37<08:41,  1.16s/it]

 93%|█████████▎| 5567/6015 [1:47:39<08:39,  1.16s/it]

 93%|█████████▎| 5568/6015 [1:47:40<08:38,  1.16s/it]

 93%|█████████▎| 5569/6015 [1:47:41<08:36,  1.16s/it]

 93%|█████████▎| 5570/6015 [1:47:42<08:35,  1.16s/it]

 93%|█████████▎| 5571/6015 [1:47:43<08:34,  1.16s/it]

 93%|█████████▎| 5572/6015 [1:47:44<08:33,  1.16s/it]

 93%|█████████▎| 5573/6015 [1:47:46<08:32,  1.16s/it]

 93%|█████████▎| 5574/6015 [1:47:47<08:31,  1.16s/it]

 93%|█████████▎| 5575/6015 [1:47:48<08:30,  1.16s/it]

 93%|█████████▎| 5576/6015 [1:47:49<08:29,  1.16s/it]

 93%|█████████▎| 5577/6015 [1:47:50<08:28,  1.16s/it]

 93%|█████████▎| 5578/6015 [1:47:51<08:27,  1.16s/it]

 93%|█████████▎| 5579/6015 [1:47:52<08:26,  1.16s/it]

 93%|█████████▎| 5580/6015 [1:47:54<08:25,  1.16s/it]

 93%|█████████▎| 5581/6015 [1:47:55<08:24,  1.16s/it]

 93%|█████████▎| 5582/6015 [1:47:56<08:23,  1.16s/it]

 93%|█████████▎| 5583/6015 [1:47:57<08:21,  1.16s/it]

 93%|█████████▎| 5584/6015 [1:47:58<08:20,  1.16s/it]

 93%|█████████▎| 5585/6015 [1:47:59<08:19,  1.16s/it]

 93%|█████████▎| 5586/6015 [1:48:01<08:18,  1.16s/it]

 93%|█████████▎| 5587/6015 [1:48:02<08:17,  1.16s/it]

 93%|█████████▎| 5588/6015 [1:48:03<08:16,  1.16s/it]

 93%|█████████▎| 5589/6015 [1:48:04<08:15,  1.16s/it]

 93%|█████████▎| 5590/6015 [1:48:05<08:14,  1.16s/it]

 93%|█████████▎| 5591/6015 [1:48:06<08:13,  1.16s/it]

 93%|█████████▎| 5592/6015 [1:48:08<08:12,  1.16s/it]

 93%|█████████▎| 5593/6015 [1:48:09<08:11,  1.16s/it]

 93%|█████████▎| 5594/6015 [1:48:10<08:10,  1.16s/it]

 93%|█████████▎| 5595/6015 [1:48:11<08:09,  1.17s/it]

 93%|█████████▎| 5596/6015 [1:48:12<08:07,  1.16s/it]

 93%|█████████▎| 5597/6015 [1:48:13<08:06,  1.16s/it]

 93%|█████████▎| 5598/6015 [1:48:15<08:05,  1.16s/it]

 93%|█████████▎| 5599/6015 [1:48:16<08:03,  1.16s/it]

 93%|█████████▎| 5600/6015 [1:48:17<08:01,  1.16s/it]

 93%|█████████▎| 5601/6015 [1:48:18<08:00,  1.16s/it]

 93%|█████████▎| 5602/6015 [1:48:19<07:59,  1.16s/it]

 93%|█████████▎| 5603/6015 [1:48:20<07:59,  1.16s/it]

 93%|█████████▎| 5604/6015 [1:48:22<07:58,  1.16s/it]

 93%|█████████▎| 5605/6015 [1:48:23<07:57,  1.16s/it]

 93%|█████████▎| 5606/6015 [1:48:24<07:56,  1.16s/it]

 93%|█████████▎| 5607/6015 [1:48:25<07:54,  1.16s/it]

 93%|█████████▎| 5608/6015 [1:48:26<07:53,  1.16s/it]

 93%|█████████▎| 5609/6015 [1:48:27<07:51,  1.16s/it]

 93%|█████████▎| 5610/6015 [1:48:29<07:50,  1.16s/it]

 93%|█████████▎| 5611/6015 [1:48:30<07:49,  1.16s/it]

 93%|█████████▎| 5612/6015 [1:48:31<07:48,  1.16s/it]

 93%|█████████▎| 5613/6015 [1:48:32<07:47,  1.16s/it]

 93%|█████████▎| 5614/6015 [1:48:33<07:46,  1.16s/it]

 93%|█████████▎| 5615/6015 [1:48:34<07:44,  1.16s/it]

 93%|█████████▎| 5616/6015 [1:48:36<07:43,  1.16s/it]

 93%|█████████▎| 5617/6015 [1:48:37<07:42,  1.16s/it]

 93%|█████████▎| 5618/6015 [1:48:38<07:41,  1.16s/it]

 93%|█████████▎| 5619/6015 [1:48:39<07:40,  1.16s/it]

 93%|█████████▎| 5620/6015 [1:48:40<07:39,  1.16s/it]

 93%|█████████▎| 5621/6015 [1:48:41<07:38,  1.16s/it]

 93%|█████████▎| 5622/6015 [1:48:42<07:37,  1.16s/it]

 93%|█████████▎| 5623/6015 [1:48:44<07:35,  1.16s/it]

 93%|█████████▎| 5624/6015 [1:48:45<07:34,  1.16s/it]

 94%|█████████▎| 5625/6015 [1:48:46<07:33,  1.16s/it]

 94%|█████████▎| 5626/6015 [1:48:47<07:31,  1.16s/it]

 94%|█████████▎| 5627/6015 [1:48:48<07:30,  1.16s/it]

 94%|█████████▎| 5628/6015 [1:48:49<07:29,  1.16s/it]

 94%|█████████▎| 5629/6015 [1:48:51<07:28,  1.16s/it]

 94%|█████████▎| 5630/6015 [1:48:52<07:27,  1.16s/it]

 94%|█████████▎| 5631/6015 [1:48:53<07:27,  1.16s/it]

 94%|█████████▎| 5632/6015 [1:48:54<07:26,  1.17s/it]

 94%|█████████▎| 5633/6015 [1:48:55<07:25,  1.17s/it]

logging
logging the anndata

 94%|█████████▎| 5634/6015 [1:48:57<07:41,  1.21s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 94%|█████████▎| 5635/6015 [1:48:58<07:34,  1.20s/it]

 94%|█████████▎| 5636/6015 [1:48:59<07:28,  1.18s/it]

 94%|█████████▎| 5637/6015 [1:49:00<07:24,  1.18s/it]

 94%|█████████▎| 5638/6015 [1:49:01<07:20,  1.17s/it]

 94%|█████████▎| 5639/6015 [1:49:02<07:17,  1.16s/it]

 94%|█████████▍| 5640/6015 [1:49:04<07:15,  1.16s/it]

 94%|█████████▍| 5641/6015 [1:49:05<07:13,  1.16s/it]

 94%|█████████▍| 5642/6015 [1:49:06<07:12,  1.16s/it]

 94%|█████████▍| 5643/6015 [1:49:07<07:10,  1.16s/it]

 94%|█████████▍| 5644/6015 [1:49:08<07:09,  1.16s/it]

 94%|█████████▍| 5645/6015 [1:49:09<07:08,  1.16s/it]

 94%|█████████▍| 5646/6015 [1:49:10<07:06,  1.16s/it]

 94%|█████████▍| 5647/6015 [1:49:12<07:04,  1.15s/it]

 94%|█████████▍| 5648/6015 [1:49:13<07:04,  1.16s/it]

 94%|█████████▍| 5649/6015 [1:49:14<07:03,  1.16s/it]

 94%|█████████▍| 5650/6015 [1:49:15<07:03,  1.16s/it]

 94%|█████████▍| 5651/6015 [1:49:16<07:02,  1.16s/it]

 94%|█████████▍| 5652/6015 [1:49:17<07:00,  1.16s/it]

 94%|█████████▍| 5653/6015 [1:49:19<06:59,  1.16s/it]

 94%|█████████▍| 5654/6015 [1:49:20<06:57,  1.16s/it]

 94%|█████████▍| 5655/6015 [1:49:21<06:56,  1.16s/it]

 94%|█████████▍| 5656/6015 [1:49:22<06:56,  1.16s/it]

 94%|█████████▍| 5657/6015 [1:49:23<06:54,  1.16s/it]

 94%|█████████▍| 5658/6015 [1:49:24<06:53,  1.16s/it]

 94%|█████████▍| 5659/6015 [1:49:26<06:51,  1.16s/it]

 94%|█████████▍| 5660/6015 [1:49:27<06:50,  1.16s/it]

 94%|█████████▍| 5661/6015 [1:49:28<06:49,  1.16s/it]

 94%|█████████▍| 5662/6015 [1:49:29<06:47,  1.16s/it]

 94%|█████████▍| 5663/6015 [1:49:30<06:46,  1.16s/it]

 94%|█████████▍| 5664/6015 [1:49:31<06:45,  1.16s/it]

 94%|█████████▍| 5665/6015 [1:49:32<06:44,  1.16s/it]

 94%|█████████▍| 5666/6015 [1:49:34<06:43,  1.16s/it]

 94%|█████████▍| 5667/6015 [1:49:35<06:42,  1.16s/it]

 94%|█████████▍| 5668/6015 [1:49:36<06:40,  1.16s/it]

 94%|█████████▍| 5669/6015 [1:49:37<06:40,  1.16s/it]

 94%|█████████▍| 5670/6015 [1:49:38<06:39,  1.16s/it]

 94%|█████████▍| 5671/6015 [1:49:39<06:37,  1.16s/it]

 94%|█████████▍| 5672/6015 [1:49:41<06:36,  1.16s/it]

 94%|█████████▍| 5673/6015 [1:49:42<06:35,  1.16s/it]

 94%|█████████▍| 5674/6015 [1:49:43<06:34,  1.16s/it]

 94%|█████████▍| 5675/6015 [1:49:44<06:33,  1.16s/it]

 94%|█████████▍| 5676/6015 [1:49:45<06:31,  1.16s/it]

 94%|█████████▍| 5677/6015 [1:49:46<06:30,  1.16s/it]

 94%|█████████▍| 5678/6015 [1:49:47<06:29,  1.16s/it]

 94%|█████████▍| 5679/6015 [1:49:49<06:28,  1.16s/it]

 94%|█████████▍| 5680/6015 [1:49:50<06:27,  1.16s/it]

 94%|█████████▍| 5681/6015 [1:49:51<06:26,  1.16s/it]

 94%|█████████▍| 5682/6015 [1:49:52<06:24,  1.16s/it]

 94%|█████████▍| 5683/6015 [1:49:53<06:24,  1.16s/it]

 94%|█████████▍| 5684/6015 [1:49:54<06:22,  1.16s/it]

 95%|█████████▍| 5685/6015 [1:49:56<06:21,  1.16s/it]

 95%|█████████▍| 5686/6015 [1:49:57<06:19,  1.15s/it]

 95%|█████████▍| 5687/6015 [1:49:58<06:18,  1.15s/it]

 95%|█████████▍| 5688/6015 [1:49:59<06:18,  1.16s/it]

 95%|█████████▍| 5689/6015 [1:50:00<06:17,  1.16s/it]

 95%|█████████▍| 5690/6015 [1:50:01<06:15,  1.16s/it]

 95%|█████████▍| 5691/6015 [1:50:03<06:14,  1.16s/it]

 95%|█████████▍| 5692/6015 [1:50:04<06:13,  1.16s/it]

 95%|█████████▍| 5693/6015 [1:50:05<06:12,  1.16s/it]

 95%|█████████▍| 5694/6015 [1:50:06<06:11,  1.16s/it]

 95%|█████████▍| 5695/6015 [1:50:07<06:09,  1.16s/it]

 95%|█████████▍| 5696/6015 [1:50:08<06:08,  1.16s/it]

 95%|█████████▍| 5697/6015 [1:50:09<06:07,  1.16s/it]

 95%|█████████▍| 5698/6015 [1:50:11<06:06,  1.16s/it]

 95%|█████████▍| 5699/6015 [1:50:12<06:05,  1.16s/it]

 95%|█████████▍| 5700/6015 [1:50:13<06:04,  1.16s/it]

 95%|█████████▍| 5701/6015 [1:50:14<06:03,  1.16s/it]

 95%|█████████▍| 5702/6015 [1:50:15<06:02,  1.16s/it]

 95%|█████████▍| 5703/6015 [1:50:16<06:00,  1.16s/it]

 95%|█████████▍| 5704/6015 [1:50:18<05:59,  1.16s/it]

 95%|█████████▍| 5705/6015 [1:50:19<05:58,  1.16s/it]

 95%|█████████▍| 5706/6015 [1:50:20<05:57,  1.16s/it]

 95%|█████████▍| 5707/6015 [1:50:21<05:56,  1.16s/it]

 95%|█████████▍| 5708/6015 [1:50:22<05:55,  1.16s/it]

 95%|█████████▍| 5709/6015 [1:50:23<05:54,  1.16s/it]

 95%|█████████▍| 5710/6015 [1:50:25<05:53,  1.16s/it]

 95%|█████████▍| 5711/6015 [1:50:26<05:52,  1.16s/it]

 95%|█████████▍| 5712/6015 [1:50:27<05:50,  1.16s/it]

 95%|█████████▍| 5713/6015 [1:50:28<05:49,  1.16s/it]

 95%|█████████▍| 5714/6015 [1:50:29<05:48,  1.16s/it]

 95%|█████████▌| 5715/6015 [1:50:30<05:46,  1.16s/it]

 95%|█████████▌| 5716/6015 [1:50:31<05:45,  1.16s/it]

 95%|█████████▌| 5717/6015 [1:50:33<05:44,  1.16s/it]

 95%|█████████▌| 5718/6015 [1:50:34<05:43,  1.16s/it]

 95%|█████████▌| 5719/6015 [1:50:35<05:42,  1.16s/it]

 95%|█████████▌| 5720/6015 [1:50:36<05:41,  1.16s/it]

 95%|█████████▌| 5721/6015 [1:50:37<05:40,  1.16s/it]

 95%|█████████▌| 5722/6015 [1:50:38<05:39,  1.16s/it]

 95%|█████████▌| 5723/6015 [1:50:40<05:37,  1.16s/it]

 95%|█████████▌| 5724/6015 [1:50:41<05:36,  1.16s/it]

 95%|█████████▌| 5725/6015 [1:50:42<05:35,  1.16s/it]

 95%|█████████▌| 5726/6015 [1:50:43<05:33,  1.16s/it]

 95%|█████████▌| 5727/6015 [1:50:44<05:32,  1.15s/it]

 95%|█████████▌| 5728/6015 [1:50:45<05:31,  1.16s/it]

 95%|█████████▌| 5729/6015 [1:50:46<05:30,  1.16s/it]

 95%|█████████▌| 5730/6015 [1:50:48<05:29,  1.16s/it]

 95%|█████████▌| 5731/6015 [1:50:49<05:28,  1.16s/it]

 95%|█████████▌| 5732/6015 [1:50:50<05:27,  1.16s/it]

 95%|█████████▌| 5733/6015 [1:50:51<05:25,  1.16s/it]

 95%|█████████▌| 5734/6015 [1:50:52<05:24,  1.16s/it]

 95%|█████████▌| 5735/6015 [1:50:53<05:23,  1.16s/it]

 95%|█████████▌| 5736/6015 [1:50:55<05:22,  1.16s/it]

 95%|█████████▌| 5737/6015 [1:50:56<05:21,  1.16s/it]

 95%|█████████▌| 5738/6015 [1:50:57<05:20,  1.16s/it]

 95%|█████████▌| 5739/6015 [1:50:58<05:19,  1.16s/it]

 95%|█████████▌| 5740/6015 [1:50:59<05:17,  1.16s/it]

 95%|█████████▌| 5741/6015 [1:51:00<05:16,  1.16s/it]

 95%|█████████▌| 5742/6015 [1:51:02<05:15,  1.16s/it]

 95%|█████████▌| 5743/6015 [1:51:03<05:14,  1.16s/it]

 95%|█████████▌| 5744/6015 [1:51:04<05:13,  1.16s/it]

 96%|█████████▌| 5745/6015 [1:51:05<05:12,  1.16s/it]

 96%|█████████▌| 5746/6015 [1:51:06<05:11,  1.16s/it]

 96%|█████████▌| 5747/6015 [1:51:07<05:10,  1.16s/it]

 96%|█████████▌| 5748/6015 [1:51:08<05:09,  1.16s/it]

 96%|█████████▌| 5749/6015 [1:51:10<05:08,  1.16s/it]

 96%|█████████▌| 5750/6015 [1:51:11<05:06,  1.16s/it]

 96%|█████████▌| 5751/6015 [1:51:12<05:05,  1.16s/it]

 96%|█████████▌| 5752/6015 [1:51:13<05:04,  1.16s/it]

 96%|█████████▌| 5753/6015 [1:51:14<05:02,  1.16s/it]

 96%|█████████▌| 5754/6015 [1:51:15<05:01,  1.16s/it]

 96%|█████████▌| 5755/6015 [1:51:17<05:00,  1.16s/it]

 96%|█████████▌| 5756/6015 [1:51:18<04:59,  1.16s/it]

 96%|█████████▌| 5757/6015 [1:51:19<04:58,  1.16s/it]

 96%|█████████▌| 5758/6015 [1:51:20<04:57,  1.16s/it]

 96%|█████████▌| 5759/6015 [1:51:21<04:55,  1.16s/it]

 96%|█████████▌| 5760/6015 [1:51:22<04:54,  1.16s/it]

 96%|█████████▌| 5761/6015 [1:51:23<04:53,  1.16s/it]

 96%|█████████▌| 5762/6015 [1:51:25<04:52,  1.16s/it]

 96%|█████████▌| 5763/6015 [1:51:26<04:51,  1.16s/it]

 96%|█████████▌| 5764/6015 [1:51:27<04:50,  1.16s/it]

 96%|█████████▌| 5765/6015 [1:51:28<04:49,  1.16s/it]

 96%|█████████▌| 5766/6015 [1:51:29<04:48,  1.16s/it]

 96%|█████████▌| 5767/6015 [1:51:30<04:47,  1.16s/it]

 96%|█████████▌| 5768/6015 [1:51:32<04:46,  1.16s/it]

 96%|█████████▌| 5769/6015 [1:51:33<04:45,  1.16s/it]

 96%|█████████▌| 5770/6015 [1:51:34<04:43,  1.16s/it]

 96%|█████████▌| 5771/6015 [1:51:35<04:42,  1.16s/it]

 96%|█████████▌| 5772/6015 [1:51:36<04:41,  1.16s/it]

 96%|█████████▌| 5773/6015 [1:51:37<04:39,  1.16s/it]

 96%|█████████▌| 5774/6015 [1:51:39<04:38,  1.16s/it]

 96%|█████████▌| 5775/6015 [1:51:40<04:37,  1.16s/it]

 96%|█████████▌| 5776/6015 [1:51:41<04:36,  1.16s/it]

 96%|█████████▌| 5777/6015 [1:51:42<04:35,  1.16s/it]

 96%|█████████▌| 5778/6015 [1:51:43<04:34,  1.16s/it]

 96%|█████████▌| 5779/6015 [1:51:44<04:33,  1.16s/it]

 96%|█████████▌| 5780/6015 [1:51:46<04:32,  1.16s/it]

 96%|█████████▌| 5781/6015 [1:51:47<04:30,  1.16s/it]

 96%|█████████▌| 5782/6015 [1:51:48<04:29,  1.16s/it]

 96%|█████████▌| 5783/6015 [1:51:49<04:28,  1.16s/it]

 96%|█████████▌| 5784/6015 [1:51:50<04:27,  1.16s/it]

 96%|█████████▌| 5785/6015 [1:51:51<04:26,  1.16s/it]

 96%|█████████▌| 5786/6015 [1:51:52<04:25,  1.16s/it]

 96%|█████████▌| 5787/6015 [1:51:54<04:23,  1.16s/it]

 96%|█████████▌| 5788/6015 [1:51:55<04:22,  1.16s/it]

 96%|█████████▌| 5789/6015 [1:51:56<04:21,  1.16s/it]

 96%|█████████▋| 5790/6015 [1:51:57<04:20,  1.16s/it]

 96%|█████████▋| 5791/6015 [1:51:58<04:19,  1.16s/it]

 96%|█████████▋| 5792/6015 [1:51:59<04:18,  1.16s/it]

 96%|█████████▋| 5793/6015 [1:52:01<04:16,  1.16s/it]

 96%|█████████▋| 5794/6015 [1:52:02<04:15,  1.16s/it]

 96%|█████████▋| 5795/6015 [1:52:03<04:14,  1.16s/it]

 96%|█████████▋| 5796/6015 [1:52:04<04:13,  1.16s/it]

 96%|█████████▋| 5797/6015 [1:52:05<04:12,  1.16s/it]

 96%|█████████▋| 5798/6015 [1:52:06<04:11,  1.16s/it]

 96%|█████████▋| 5799/6015 [1:52:07<04:10,  1.16s/it]

 96%|█████████▋| 5800/6015 [1:52:09<04:09,  1.16s/it]

 96%|█████████▋| 5801/6015 [1:52:10<04:08,  1.16s/it]

 96%|█████████▋| 5802/6015 [1:52:11<04:06,  1.16s/it]

 96%|█████████▋| 5803/6015 [1:52:12<04:05,  1.16s/it]

 96%|█████████▋| 5804/6015 [1:52:13<04:04,  1.16s/it]

 97%|█████████▋| 5805/6015 [1:52:14<04:03,  1.16s/it]

 97%|█████████▋| 5806/6015 [1:52:16<04:02,  1.16s/it]

 97%|█████████▋| 5807/6015 [1:52:17<04:01,  1.16s/it]

 97%|█████████▋| 5808/6015 [1:52:18<03:59,  1.16s/it]

 97%|█████████▋| 5809/6015 [1:52:19<03:58,  1.16s/it]

 97%|█████████▋| 5810/6015 [1:52:20<03:57,  1.16s/it]

 97%|█████████▋| 5811/6015 [1:52:21<03:55,  1.16s/it]

 97%|█████████▋| 5812/6015 [1:52:23<03:54,  1.16s/it]

 97%|█████████▋| 5813/6015 [1:52:24<03:53,  1.16s/it]

 97%|█████████▋| 5814/6015 [1:52:25<03:52,  1.16s/it]

 97%|█████████▋| 5815/6015 [1:52:26<03:51,  1.16s/it]

 97%|█████████▋| 5816/6015 [1:52:27<03:50,  1.16s/it]

 97%|█████████▋| 5817/6015 [1:52:28<03:49,  1.16s/it]

 97%|█████████▋| 5818/6015 [1:52:29<03:47,  1.16s/it]

 97%|█████████▋| 5819/6015 [1:52:31<03:46,  1.16s/it]

 97%|█████████▋| 5820/6015 [1:52:32<03:45,  1.16s/it]

 97%|█████████▋| 5821/6015 [1:52:33<03:44,  1.16s/it]

 97%|█████████▋| 5822/6015 [1:52:34<03:43,  1.16s/it]

 97%|█████████▋| 5823/6015 [1:52:35<03:42,  1.16s/it]

 97%|█████████▋| 5824/6015 [1:52:36<03:41,  1.16s/it]

 97%|█████████▋| 5825/6015 [1:52:38<03:40,  1.16s/it]

 97%|█████████▋| 5826/6015 [1:52:39<03:39,  1.16s/it]

 97%|█████████▋| 5827/6015 [1:52:40<03:37,  1.16s/it]

 97%|█████████▋| 5828/6015 [1:52:41<03:36,  1.16s/it]

 97%|█████████▋| 5829/6015 [1:52:42<03:35,  1.16s/it]

 97%|█████████▋| 5830/6015 [1:52:43<03:34,  1.16s/it]

 97%|█████████▋| 5831/6015 [1:52:45<03:33,  1.16s/it]

 97%|█████████▋| 5832/6015 [1:52:46<03:31,  1.16s/it]

 97%|█████████▋| 5833/6015 [1:52:47<03:30,  1.16s/it]

 97%|█████████▋| 5834/6015 [1:52:48<03:29,  1.16s/it]

 97%|█████████▋| 5835/6015 [1:52:49<03:28,  1.16s/it]

 97%|█████████▋| 5836/6015 [1:52:50<03:26,  1.16s/it]

 97%|█████████▋| 5837/6015 [1:52:51<03:25,  1.16s/it]

 97%|█████████▋| 5838/6015 [1:52:53<03:24,  1.16s/it]

 97%|█████████▋| 5839/6015 [1:52:54<03:23,  1.16s/it]

 97%|█████████▋| 5840/6015 [1:52:55<03:22,  1.16s/it]

 97%|█████████▋| 5841/6015 [1:52:56<03:21,  1.16s/it]

 97%|█████████▋| 5842/6015 [1:52:57<03:20,  1.16s/it]

 97%|█████████▋| 5843/6015 [1:52:58<03:19,  1.16s/it]

 97%|█████████▋| 5844/6015 [1:53:00<03:17,  1.16s/it]

 97%|█████████▋| 5845/6015 [1:53:01<03:16,  1.16s/it]

 97%|█████████▋| 5846/6015 [1:53:02<03:15,  1.16s/it]

 97%|█████████▋| 5847/6015 [1:53:03<03:14,  1.16s/it]

 97%|█████████▋| 5848/6015 [1:53:04<03:13,  1.16s/it]

 97%|█████████▋| 5849/6015 [1:53:05<03:12,  1.16s/it]

 97%|█████████▋| 5850/6015 [1:53:07<03:11,  1.16s/it]

 97%|█████████▋| 5851/6015 [1:53:08<03:10,  1.16s/it]

 97%|█████████▋| 5852/6015 [1:53:09<03:09,  1.16s/it]

 97%|█████████▋| 5853/6015 [1:53:10<03:07,  1.16s/it]

 97%|█████████▋| 5854/6015 [1:53:11<03:06,  1.16s/it]

 97%|█████████▋| 5855/6015 [1:53:12<03:05,  1.16s/it]

 97%|█████████▋| 5856/6015 [1:53:13<03:03,  1.16s/it]

 97%|█████████▋| 5857/6015 [1:53:15<03:02,  1.16s/it]

 97%|█████████▋| 5858/6015 [1:53:16<03:01,  1.16s/it]

 97%|█████████▋| 5859/6015 [1:53:17<03:00,  1.16s/it]

 97%|█████████▋| 5860/6015 [1:53:18<02:59,  1.16s/it]

 97%|█████████▋| 5861/6015 [1:53:19<02:58,  1.16s/it]

 97%|█████████▋| 5862/6015 [1:53:20<02:57,  1.16s/it]

 97%|█████████▋| 5863/6015 [1:53:22<02:55,  1.16s/it]

 97%|█████████▋| 5864/6015 [1:53:23<02:54,  1.16s/it]

 98%|█████████▊| 5865/6015 [1:53:24<02:53,  1.16s/it]

 98%|█████████▊| 5866/6015 [1:53:25<02:52,  1.16s/it]

 98%|█████████▊| 5867/6015 [1:53:26<02:51,  1.16s/it]

 98%|█████████▊| 5868/6015 [1:53:27<02:50,  1.16s/it]

 98%|█████████▊| 5869/6015 [1:53:29<02:48,  1.16s/it]

 98%|█████████▊| 5870/6015 [1:53:30<02:48,  1.16s/it]

 98%|█████████▊| 5871/6015 [1:53:31<02:46,  1.16s/it]

 98%|█████████▊| 5872/6015 [1:53:32<02:45,  1.16s/it]

 98%|█████████▊| 5873/6015 [1:53:33<02:44,  1.16s/it]

 98%|█████████▊| 5874/6015 [1:53:34<02:43,  1.16s/it]

 98%|█████████▊| 5875/6015 [1:53:35<02:42,  1.16s/it]

 98%|█████████▊| 5876/6015 [1:53:37<02:41,  1.16s/it]

 98%|█████████▊| 5877/6015 [1:53:38<02:39,  1.16s/it]

 98%|█████████▊| 5878/6015 [1:53:39<02:38,  1.16s/it]

 98%|█████████▊| 5879/6015 [1:53:40<02:37,  1.16s/it]

 98%|█████████▊| 5880/6015 [1:53:41<02:36,  1.16s/it]

 98%|█████████▊| 5881/6015 [1:53:42<02:35,  1.16s/it]

 98%|█████████▊| 5882/6015 [1:53:44<02:34,  1.16s/it]

 98%|█████████▊| 5883/6015 [1:53:45<02:33,  1.16s/it]

 98%|█████████▊| 5884/6015 [1:53:46<02:31,  1.16s/it]

 98%|█████████▊| 5885/6015 [1:53:47<02:30,  1.16s/it]

 98%|█████████▊| 5886/6015 [1:53:48<02:29,  1.16s/it]

 98%|█████████▊| 5887/6015 [1:53:49<02:28,  1.16s/it]

 98%|█████████▊| 5888/6015 [1:53:51<02:26,  1.16s/it]

 98%|█████████▊| 5889/6015 [1:53:52<02:25,  1.16s/it]

 98%|█████████▊| 5890/6015 [1:53:53<02:24,  1.16s/it]

 98%|█████████▊| 5891/6015 [1:53:54<02:23,  1.16s/it]

 98%|█████████▊| 5892/6015 [1:53:55<02:22,  1.16s/it]

 98%|█████████▊| 5893/6015 [1:53:56<02:21,  1.16s/it]

 98%|█████████▊| 5894/6015 [1:53:58<02:20,  1.16s/it]

 98%|█████████▊| 5895/6015 [1:53:59<02:19,  1.16s/it]

 98%|█████████▊| 5896/6015 [1:54:00<02:17,  1.16s/it]

 98%|█████████▊| 5897/6015 [1:54:01<02:16,  1.16s/it]

 98%|█████████▊| 5898/6015 [1:54:02<02:15,  1.16s/it]

 98%|█████████▊| 5899/6015 [1:54:03<02:14,  1.16s/it]

 98%|█████████▊| 5900/6015 [1:54:04<02:13,  1.16s/it]

 98%|█████████▊| 5901/6015 [1:54:06<02:11,  1.16s/it]

 98%|█████████▊| 5902/6015 [1:54:07<02:10,  1.16s/it]

 98%|█████████▊| 5903/6015 [1:54:08<02:09,  1.16s/it]

 98%|█████████▊| 5904/6015 [1:54:09<02:08,  1.16s/it]

 98%|█████████▊| 5905/6015 [1:54:10<02:07,  1.16s/it]

 98%|█████████▊| 5906/6015 [1:54:11<02:06,  1.16s/it]

 98%|█████████▊| 5907/6015 [1:54:13<02:05,  1.16s/it]

 98%|█████████▊| 5908/6015 [1:54:14<02:03,  1.16s/it]

 98%|█████████▊| 5909/6015 [1:54:15<02:02,  1.16s/it]

 98%|█████████▊| 5910/6015 [1:54:16<02:01,  1.16s/it]

 98%|█████████▊| 5911/6015 [1:54:17<02:00,  1.16s/it]

 98%|█████████▊| 5912/6015 [1:54:18<01:59,  1.16s/it]

 98%|█████████▊| 5913/6015 [1:54:20<01:58,  1.16s/it]

 98%|█████████▊| 5914/6015 [1:54:21<01:56,  1.16s/it]

 98%|█████████▊| 5915/6015 [1:54:22<01:55,  1.16s/it]

 98%|█████████▊| 5916/6015 [1:54:23<01:54,  1.16s/it]

 98%|█████████▊| 5917/6015 [1:54:24<01:53,  1.16s/it]

 98%|█████████▊| 5918/6015 [1:54:25<01:52,  1.16s/it]

 98%|█████████▊| 5919/6015 [1:54:26<01:51,  1.16s/it]

 98%|█████████▊| 5920/6015 [1:54:28<01:50,  1.16s/it]

 98%|█████████▊| 5921/6015 [1:54:29<01:49,  1.16s/it]

 98%|█████████▊| 5922/6015 [1:54:30<01:47,  1.16s/it]

 98%|█████████▊| 5923/6015 [1:54:31<01:46,  1.16s/it]

 98%|█████████▊| 5924/6015 [1:54:32<01:45,  1.16s/it]

 99%|█████████▊| 5925/6015 [1:54:33<01:44,  1.16s/it]

 99%|█████████▊| 5926/6015 [1:54:35<01:43,  1.16s/it]

 99%|█████████▊| 5927/6015 [1:54:36<01:41,  1.16s/it]

 99%|█████████▊| 5928/6015 [1:54:37<01:40,  1.16s/it]

 99%|█████████▊| 5929/6015 [1:54:38<01:39,  1.16s/it]

 99%|█████████▊| 5930/6015 [1:54:39<01:38,  1.16s/it]

 99%|█████████▊| 5931/6015 [1:54:40<01:37,  1.16s/it]

 99%|█████████▊| 5932/6015 [1:54:42<01:36,  1.16s/it]

 99%|█████████▊| 5933/6015 [1:54:43<01:35,  1.16s/it]

 99%|█████████▊| 5934/6015 [1:54:44<01:33,  1.16s/it]

 99%|█████████▊| 5935/6015 [1:54:45<01:32,  1.16s/it]

 99%|█████████▊| 5936/6015 [1:54:46<01:31,  1.16s/it]

 99%|█████████▊| 5937/6015 [1:54:47<01:30,  1.16s/it]

 99%|█████████▊| 5938/6015 [1:54:48<01:29,  1.16s/it]

 99%|█████████▊| 5939/6015 [1:54:50<01:28,  1.16s/it]

 99%|█████████▉| 5940/6015 [1:54:51<01:26,  1.16s/it]

 99%|█████████▉| 5941/6015 [1:54:52<01:25,  1.16s/it]

 99%|█████████▉| 5942/6015 [1:54:53<01:24,  1.16s/it]

 99%|█████████▉| 5943/6015 [1:54:54<01:23,  1.16s/it]

 99%|█████████▉| 5944/6015 [1:54:55<01:22,  1.16s/it]

 99%|█████████▉| 5945/6015 [1:54:57<01:21,  1.16s/it]

 99%|█████████▉| 5946/6015 [1:54:58<01:19,  1.16s/it]

 99%|█████████▉| 5947/6015 [1:54:59<01:18,  1.16s/it]

 99%|█████████▉| 5948/6015 [1:55:00<01:17,  1.16s/it]

 99%|█████████▉| 5949/6015 [1:55:01<01:16,  1.16s/it]

 99%|█████████▉| 5950/6015 [1:55:02<01:15,  1.16s/it]

 99%|█████████▉| 5951/6015 [1:55:04<01:14,  1.16s/it]

 99%|█████████▉| 5952/6015 [1:55:05<01:12,  1.16s/it]

 99%|█████████▉| 5953/6015 [1:55:06<01:11,  1.16s/it]

 99%|█████████▉| 5954/6015 [1:55:07<01:10,  1.16s/it]

 99%|█████████▉| 5955/6015 [1:55:08<01:09,  1.16s/it]

 99%|█████████▉| 5956/6015 [1:55:09<01:08,  1.16s/it]

 99%|█████████▉| 5957/6015 [1:55:11<01:07,  1.16s/it]

 99%|█████████▉| 5958/6015 [1:55:12<01:06,  1.16s/it]

 99%|█████████▉| 5959/6015 [1:55:13<01:04,  1.16s/it]

 99%|█████████▉| 5960/6015 [1:55:14<01:03,  1.16s/it]

 99%|█████████▉| 5961/6015 [1:55:15<01:02,  1.16s/it]

 99%|█████████▉| 5962/6015 [1:55:16<01:01,  1.16s/it]

 99%|█████████▉| 5963/6015 [1:55:17<01:00,  1.16s/it]

 99%|█████████▉| 5964/6015 [1:55:19<00:59,  1.16s/it]

 99%|█████████▉| 5965/6015 [1:55:20<00:57,  1.16s/it]

 99%|█████████▉| 5966/6015 [1:55:21<00:56,  1.16s/it]

 99%|█████████▉| 5967/6015 [1:55:22<00:55,  1.16s/it]

 99%|█████████▉| 5968/6015 [1:55:23<00:54,  1.16s/it]

 99%|█████████▉| 5969/6015 [1:55:24<00:53,  1.16s/it]

 99%|█████████▉| 5970/6015 [1:55:26<00:52,  1.16s/it]

 99%|█████████▉| 5971/6015 [1:55:27<00:51,  1.16s/it]

 99%|█████████▉| 5972/6015 [1:55:28<00:49,  1.16s/it]

 99%|█████████▉| 5973/6015 [1:55:29<00:48,  1.16s/it]

 99%|█████████▉| 5974/6015 [1:55:30<00:47,  1.16s/it]

 99%|█████████▉| 5975/6015 [1:55:31<00:46,  1.16s/it]

 99%|█████████▉| 5976/6015 [1:55:33<00:45,  1.16s/it]

 99%|█████████▉| 5977/6015 [1:55:34<00:44,  1.16s/it]

 99%|█████████▉| 5978/6015 [1:55:35<00:42,  1.16s/it]

 99%|█████████▉| 5979/6015 [1:55:36<00:41,  1.16s/it]

 99%|█████████▉| 5980/6015 [1:55:37<00:40,  1.16s/it]

 99%|█████████▉| 5981/6015 [1:55:38<00:39,  1.16s/it]

 99%|█████████▉| 5982/6015 [1:55:39<00:38,  1.16s/it]

 99%|█████████▉| 5983/6015 [1:55:41<00:37,  1.16s/it]

 99%|█████████▉| 5984/6015 [1:55:42<00:35,  1.16s/it]

100%|█████████▉| 5985/6015 [1:55:43<00:34,  1.16s/it]

100%|█████████▉| 5986/6015 [1:55:44<00:33,  1.16s/it]

100%|█████████▉| 5987/6015 [1:55:45<00:32,  1.16s/it]

100%|█████████▉| 5988/6015 [1:55:46<00:31,  1.16s/it]

100%|█████████▉| 5989/6015 [1:55:48<00:30,  1.16s/it]

100%|█████████▉| 5990/6015 [1:55:49<00:28,  1.16s/it]

100%|█████████▉| 5991/6015 [1:55:50<00:27,  1.16s/it]

100%|█████████▉| 5992/6015 [1:55:51<00:26,  1.16s/it]

100%|█████████▉| 5993/6015 [1:55:52<00:25,  1.16s/it]

100%|█████████▉| 5994/6015 [1:55:53<00:24,  1.16s/it]

100%|█████████▉| 5995/6015 [1:55:55<00:23,  1.16s/it]

100%|█████████▉| 5996/6015 [1:55:56<00:22,  1.16s/it]

100%|█████████▉| 5997/6015 [1:55:57<00:20,  1.16s/it]

100%|█████████▉| 5998/6015 [1:55:58<00:19,  1.16s/it]

100%|█████████▉| 5999/6015 [1:55:59<00:18,  1.16s/it]

100%|█████████▉| 6000/6015 [1:56:00<00:17,  1.16s/it]

100%|█████████▉| 6001/6015 [1:56:02<00:16,  1.16s/it]

100%|█████████▉| 6002/6015 [1:56:03<00:15,  1.16s/it]

100%|█████████▉| 6003/6015 [1:56:04<00:13,  1.16s/it]

100%|█████████▉| 6004/6015 [1:56:05<00:12,  1.16s/it]

100%|█████████▉| 6005/6015 [1:56:06<00:11,  1.16s/it]

100%|█████████▉| 6006/6015 [1:56:07<00:10,  1.16s/it]

100%|█████████▉| 6007/6015 [1:56:08<00:09,  1.16s/it]

100%|█████████▉| 6008/6015 [1:56:10<00:08,  1.16s/it]

100%|█████████▉| 6009/6015 [1:56:11<00:06,  1.16s/it]

100%|█████████▉| 6010/6015 [1:56:12<00:05,  1.16s/it]

100%|█████████▉| 6011/6015 [1:56:13<00:04,  1.16s/it]

100%|█████████▉| 6012/6015 [1:56:14<00:03,  1.16s/it]

100%|█████████▉| 6013/6015 [1:56:15<00:02,  1.16s/it]

100%|█████████▉| 6014/6015 [1:56:17<00:01,  1.16s/it]

100%|██████████| 6015/6015 [1:56:18<00:00,  1.09s/it]

100%|██████████| 6015/6015 [1:56:19<00:00,  1.16s/it]

logging the anndata
AnnData object with n_obs × n_vars = 24349 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

too few cells to embed into a umap
too few cells to compute a clustering

PairwiseArrays with keys: connectivities, distances

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.7195635 -11.484286  -12.558828  ... -11.723528  -11.3148985
 -11.708585 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.2959385 -12.1018    -13.0152445 ... -12.428722  -11.99109
 -12.336425 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.161508 -13.727162 -15.212095 ... -12.931157 -12.952843 -13.836475]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.97783  -11.709078 -12.782746 ... -11.693503 -11.424657 -11.881245]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.345622 -12.898764 -14.439694 ... -12.299085 -12.21589  -13.03944 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.265138  -12.0688505 -12.995547  ... -12.394809  -11.959673
 -12.304911 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.022028 -11.763946 -12.80237  ... -12.131845 -11.70487  -11.999883]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.997172 -12.060093 -12.659269 ... -11.993501 -11.959336 -12.089373]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.896472 -12.948051 -13.669446 ... -12.834214 -12.827954 -12.954361]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.985448 -12.132592 -12.796914 ... -12.176627 -12.225633 -12.289594]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.205371  -12.0379505 -12.597896  ... -11.938963  -12.173439
 -12.188969 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.22657   -13.847003  -15.177176  ... -14.171798  -14.114126
 -14.3769245]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.92172  -10.594208 -11.290123 ... -10.86766  -10.553691 -11.109114]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.82999  -8.593182 -9.657195 ... -9.107654 -8.537383 -9.200698]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.951687  -11.7294655 -12.750746  ... -11.999442  -11.569655
 -11.960171 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.5156825 3.5052395 3.5035448 ... 3.0727446 3.3184693 3.5773857]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.1273704 -5.823314  -5.3617234 ... -6.4886227 -6.217324  -6.3742814]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.159381  -9.915009  -9.510966 ... -10.368336 -10.069308 -10.2271  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.7302885 -8.799274  -8.422628  ... -8.567795  -8.633209  -8.676887 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.499561 -12.32275  -13.25331  ... -12.538524 -12.159553 -12.52949 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.821889 -13.721747 -14.562986 ... -13.585177 -13.400151 -13.892646]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.94855  -11.722333 -12.737138 ... -11.984886 -11.567978 -11.952698]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.6894755 -7.5151095 -7.797449  ... -7.5683317 -7.5505085 -7.9357343]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.385877 -10.155871 -11.730851 ... -10.212046  -9.597922 -10.43913 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.679513 -10.474739 -11.704456 ... -10.667167  -9.926197 -10.833454]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.104789 -11.893553 -12.804167 ... -12.1395   -11.732326 -12.110127]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.2102413 -4.0883284 -5.0773926 ... -2.9912362 -2.8812747 -3.7339392]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.364181  -4.202186  -5.078546  ... -3.51379   -3.3786364 -4.126841 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.2288184 -5.0242114 -5.848658  ... -4.5813813 -4.394314  -5.1030884]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.108991   -9.943688  -11.022193  ...  -9.8474655  -9.338949
 -10.324069 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.557666 -11.56102  -11.794804 ... -10.610551 -10.501242 -11.007627]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.405426  -11.226056  -11.646152  ... -10.656127  -10.634559
 -11.0774975]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.311029 -11.124313 -11.538946 ... -10.585271 -10.553426 -11.006752]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.513306 -10.268755 -11.126823 ... -10.654577 -10.273761 -10.483363]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.785819 -13.483246 -14.210788 ... -13.486535 -13.117854 -13.855922]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.5905285 -14.627749  -14.993517  ... -14.264058  -13.69117
 -14.34261  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.4465804 -7.174206  -7.8516316 ... -7.118503  -6.9513636 -7.5537863]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.1591825 -4.611629  -5.662002  ... -4.948171  -4.770573  -4.81599  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.239134 -10.261669 -11.000323 ... -10.654334 -10.19269  -10.270326]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.1882157 -4.5919523 -5.7464614 ... -4.850619  -4.667043  -4.7602034]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.496276 -10.303102 -11.268933 ... -10.675639 -10.294645 -10.464251]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.253973 -10.048954 -11.265798 ... -10.038977  -9.480039 -10.499683]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.391117 -13.031663 -13.682472 ... -13.066446 -13.174856 -13.394842]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.183474 -11.13907  -11.442881 ... -10.530722 -10.535047 -11.179393]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.922069 -8.840614 -9.834132 ... -9.113182 -8.854082 -9.250242]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.364263 -9.119028 -9.686029 ... -9.575546 -9.178188 -9.37338 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.316611 -12.132422 -13.063904 ... -12.451413 -12.01933  -12.366534]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.235861 -12.044342 -12.94456  ... -12.345953 -11.930797 -12.272592]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.183788 -11.995346 -12.943013 ... -12.29876  -11.875108 -12.226278]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.883204 -13.312862 -14.461178 ... -12.933709 -13.110691 -13.202784]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.26471  -12.066643 -12.977519 ... -12.404971 -11.967569 -12.317861]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.828369  -7.5451727 -8.275851  ... -7.4794955 -7.2821326 -7.8978815]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.348796 -9.422881 -9.665017 ... -8.888206 -8.761637 -9.435445]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.8714175 -6.579961  -7.3194036 ... -6.622699  -6.3758807 -6.958956 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.120903  -8.85578   -9.270397  ... -8.703723  -8.9511175 -8.884118 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.903437 -11.761592 -12.653501 ... -11.694485 -11.472554 -11.807868]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.380136  -13.319876  -13.999901  ... -13.070058  -12.7986355
 -13.16654  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.177761 -16.894848 -17.953865 ... -16.23616  -16.272339 -17.092447]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.4852679 3.568622  3.1259053 ... 3.1238043 3.2821698 3.6343646]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.06759   -11.957745  -12.730932  ... -12.339449  -11.7838955
 -12.03616  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.483658  -7.431102  -8.082802  ... -8.032974  -7.4511795 -7.687959 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.51586   -11.574332  -12.130641  ... -11.591593  -11.4938135
 -11.584717 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.14293  -11.970733 -12.859014 ... -12.269161 -11.866861 -12.193838]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.292412  -10.023923  -10.14426   ... -10.4629345 -10.12028
 -10.314298 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.972785  -13.600942  -14.692886  ... -13.96935   -13.7716675
 -14.021707 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.0352845 -6.909051  -7.851923  ... -7.2090383 -6.9298315 -7.2792993]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.240436 -8.16162  -9.077347 ... -8.445221 -8.179633 -8.464662]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.535238 -8.549695 -8.813365 ... -8.15147  -8.175308 -8.495777]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.142193 -16.054153 -16.697367 ... -16.235905 -15.786985 -16.436405]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.875242  5.0111876 4.4574723 ... 4.725571  4.80143   5.0753016]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.725353  -7.7042584 -8.349267  ... -7.6898203 -7.4158173 -7.776162 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.279937 -10.847156 -10.804228 ... -10.843584 -10.10933  -10.422158]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.2826   -11.303874 -11.67129  ... -10.722059 -10.648016 -11.036843]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.285365  -5.6106043 -6.728253  ... -5.64983   -5.392044  -5.5253854]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.51383  -13.142029 -13.493694 ... -13.384902 -13.147789 -13.163151]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.44668  -9.391541 -9.95726  ... -8.959154 -8.601218 -9.365679]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.512775 -13.351753 -14.126966 ... -13.060067 -12.785097 -13.244102]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.351585 -16.135284 -16.794466 ... -15.690694 -15.641444 -16.330297]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.514698 -11.31464  -12.523669 ... -11.402708 -10.852261 -11.585033]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.708335 -11.436361 -12.388294 ... -11.783226 -11.388443 -11.678775]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.3459625 -7.060044  -7.7499256 ... -7.067146  -6.832453  -7.433758 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.243202 -12.781016 -14.014336 ... -12.828745 -12.684815 -13.170992]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.453622  -10.202506  -11.113894  ... -10.178547   -9.900882
 -10.3844595]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.279915  -3.1459363 -2.7758074 ... -4.0391784 -3.6464846 -3.4160578]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.232981  -11.178996  -12.730484  ... -10.335491  -10.193652
 -11.0815935]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.392551  -4.6873884 -5.930542  ... -5.01352   -4.7609043 -4.9072695]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.5789943 -5.9688797 -7.1161304 ... -6.5058217 -6.2385488 -6.17397  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.2991083 2.5637798 2.3758802 ... 1.8561021 2.3947225 2.6493304]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.352585 -8.076464 -8.725464 ... -8.507139 -8.053612 -8.20191 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.510122  -9.302851 -10.064959 ...  -9.702274  -9.308738  -9.473207]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.338619 -9.118563 -9.868182 ... -9.507206 -9.10707  -9.279938]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.760661 -8.470416 -8.771787 ... -8.723096 -8.336227 -8.472688]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.109806 -8.902139 -8.819749 ... -9.108026 -8.78902  -8.812222]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.710642  -9.496185 -10.30034  ...  -9.916097  -9.493971  -9.673155]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.787178  -9.578162 -10.377187 ...  -9.998535  -9.574809  -9.744402]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.2571335 -15.232465  -15.850107  ... -15.055179  -14.999573
 -15.380757 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.730438 -11.572243 -12.542469 ... -11.783049 -11.33448  -11.787986]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.386997 -11.22174  -12.159556 ... -11.455624 -11.032672 -11.531957]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.9333224 -7.904818  -8.6583395 ... -8.238802  -7.94501   -8.247991 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.230572  -9.813968  -9.392267 ... -10.067765 -10.038046  -9.804571]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.07996  -12.168103 -12.385651 ... -12.748803 -12.312933 -12.058327]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.581084 -11.483332 -12.32495  ... -11.685908 -11.350883 -11.67625 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.8810487 -6.7544923 -7.2962    ... -7.2556868 -6.897846  -7.0494657]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.113557  -11.0151205 -11.746147  ... -11.35645   -10.994209
 -11.240023 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.10509  -8.045186 -8.569395 ... -8.417273 -8.161331 -8.280779]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.314216 -9.385848 -9.723494 ... -9.657888 -9.466164 -9.441541]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.659678  -9.665048 -10.017001 ...  -9.92267   -9.561795  -9.721106]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.311565 -10.175913 -10.806893 ... -10.59198  -10.114416 -10.438577]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.847667  -11.1118355 -11.472735  ... -11.187281  -11.028447
 -11.15556  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.839063 -10.337048 -10.10285  ... -10.416998 -10.370091 -10.16176 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.087497  -11.155441  -11.8856535 ... -11.25645   -11.079981
 -11.316482 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.474531 -8.447108 -8.73976  ... -8.977659 -8.592861 -8.664397]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.195075 -12.009236 -12.947155 ... -12.302955 -11.879232 -12.250539]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.210457 -12.027204 -12.899189 ... -12.312718 -11.881252 -12.251074]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.889677  -7.0516806 -7.473141  ... -7.632463  -7.374883  -7.57459  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.822511 -12.785319 -14.045691 ... -12.797101 -12.527915 -12.863143]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.9414964 -4.5048647 -5.946313  ... -4.7984996 -4.627291  -4.6594815]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.530708 -12.509086 -13.182235 ... -13.289064 -13.247165 -12.945054]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.941108  -9.860546 -10.520352 ...  -9.964916  -9.825889 -10.154365]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.556858 -9.6099   -9.758816 ... -9.897648 -9.41336  -9.568846]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.548037  -12.438467  -13.387151  ... -12.681582  -12.124478
 -12.4170685]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.675109 -10.84464  -10.815603 ... -11.545895 -11.051408 -10.734302]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.847875 -11.673726 -12.687636 ... -12.070966 -11.51833  -11.876939]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.324574  -9.263453  -9.9018   ... -10.027472  -9.237367  -9.419163]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.831286 -8.860219 -9.032006 ... -9.212008 -8.831475 -8.984899]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.420146 -10.439947 -10.531049 ... -10.9085   -10.41511  -10.419097]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.904445 -10.783694 -11.581427 ... -11.008153 -10.499272 -10.838426]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.906304 -10.841251 -11.511126 ... -10.841859 -10.325389 -10.683759]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.1829376 -7.014026  -7.636075  ... -7.6186585 -7.0918937 -7.2216883]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.6853    -11.539336  -12.510101  ... -11.968814  -11.60354
 -11.8811245]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.180139 -8.034671 -8.725029 ... -8.631971 -8.220838 -8.395143]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.148249  -6.97869   -7.6697516 ... -7.6493607 -7.102355  -7.2974005]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.1983705 -7.0470796 -7.718548  ... -7.804134  -7.351957  -7.517085 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.76293   -7.6191955 -8.295097  ... -8.371268  -7.91823   -8.072818 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.9706745 -12.016994  -12.263431  ... -12.580864  -12.035438
 -11.899471 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.18431  -8.123336 -8.902881 ... -8.21915  -8.044781 -8.304685]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.273457 -12.08582  -13.023383 ... -12.361119 -11.943965 -12.314911]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.58655    -9.678306   -9.908999  ... -10.166486   -9.788089
  -9.8311825]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.269661 -10.504545 -10.315149 ... -11.046238 -10.7819   -10.341158]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.604823 -12.589871 -13.027166 ... -13.391442 -12.708954 -12.635241]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.69227  -10.603904 -11.200644 ... -10.745621 -10.567761 -10.918583]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.865649  -7.0396843 -7.5203314 ... -7.647563  -7.3379493 -7.5157776]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.345553  -10.488008  -10.9916115 ... -10.595781  -10.445784
 -10.62743  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.556001 -10.409758 -11.126955 ... -10.630608 -10.365119 -10.744846]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.050936 -10.913474 -11.654819 ... -11.037802 -10.790161 -11.191165]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.877161  -7.0712247 -7.566432  ... -7.724034  -7.3587747 -7.5384393]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.036332 -8.978635 -9.684924 ... -9.279139 -8.995286 -9.316616]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.395493  -9.362916 -10.062529 ...  -9.663734  -9.371118  -9.673611]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.042766 -10.235618 -10.931727 ... -10.017076  -9.455017  -9.946904]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.847173 -11.786871 -12.483957 ... -11.888867 -11.637951 -11.887262]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.586376 -11.491273 -12.256365 ... -11.719706 -11.503411 -11.730845]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.288054  4.5289903 4.2325997 ... 3.7648957 4.2840853 4.489131 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.750788  -12.736666  -12.925427  ... -12.897502  -12.3355255
 -12.477543 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.7564297 -7.718233  -8.339053  ... -8.28073   -7.7207336 -7.9357057]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.038171 -9.028991 -9.875572 ... -9.453365 -8.741854 -9.073034]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.1697497 -7.004179  -7.6994505 ... -7.6695805 -7.122405  -7.3103337]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.599539 -8.460963 -9.140661 ... -9.107785 -8.553871 -8.653606]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.043924 -9.159358 -9.772397 ... -9.413941 -9.201557 -9.435682]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.347767 -8.51821  -9.021715 ... -8.667957 -8.514409 -8.717807]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.91954   -6.7553744 -7.4108706 ... -7.4037747 -6.8712826 -7.0581017]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.2024503 -7.197051  -7.3576546 ... -6.8822203 -6.6864667 -7.1317177]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.230877 -7.973928 -8.638049 ... -8.703783 -8.634867 -8.399703]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.15779   -11.957955  -13.027456  ... -11.956338  -11.542934
 -12.0543785]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.852424 -8.810572 -9.543491 ... -9.175474 -8.871071 -9.159548]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.15502  -9.098845 -9.847828 ... -9.468785 -9.157055 -9.452131]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.360004  -9.310392 -10.046846 ...  -9.680144  -9.358449  -9.642625]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.960082 -8.914482 -9.64626  ... -9.280591 -8.983234 -9.261367]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.251489  -12.068223  -12.98368   ... -12.382774  -11.956508
 -12.3018055]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.213941 -12.040054 -12.912032 ... -12.337448 -11.937197 -12.249465]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.006668 -11.841982 -12.76269  ... -12.065353 -11.710989 -12.057734]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.811007 -12.795511 -13.359772 ... -13.152455 -12.555119 -12.805385]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.562605  -8.560642  -9.298913  ... -8.686582  -8.5377865 -8.703767 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.673556  -9.742228 -10.044962 ...  -9.599786  -9.750976  -9.982943]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.694583 -11.57716  -12.447671 ... -11.726875 -11.421838 -11.77999 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.581076 -10.08476   -9.39672  ... -10.214534 -10.452929  -9.802619]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.458874 -12.193609 -13.338089 ... -12.381141 -11.970649 -12.67144 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.6480956 -6.489545  -7.3445106 ... -6.5099287 -6.2742515 -6.8256097]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.787085  -6.5442657 -7.384609  ... -6.2399054 -6.1009254 -6.7766433]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.766049 -11.601641 -12.815714 ... -11.185842 -10.822657 -11.953938]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.9074154 -5.3048463 -6.294271  ... -5.5763073 -5.203997  -5.284479 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.000295 -12.797855 -13.60444  ... -12.731567 -12.502411 -12.913052]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.002662 -13.909015 -14.416205 ... -13.265704 -13.383125 -13.832293]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.615377  -7.355416  -7.9536395 ... -7.0771217 -6.8260517 -7.5829787]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.7872214 -7.054068  -7.423367  ... -7.7313957 -7.4113564 -7.5267944]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.11827  -10.016797 -10.253708 ...  -9.352717  -9.245171  -9.492083]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.469926  -9.43269   -9.519981  ... -8.5297365 -8.4512415 -8.613546 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.31757   -12.10867   -13.053631  ... -12.412518  -11.987906
 -12.3508215]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.502562  -9.443324 -10.211348 ...  -9.656019  -9.494626  -9.810024]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.348095 -8.261113 -9.13723  ... -8.427136 -8.119057 -8.436798]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.207182  -9.86216  -10.790081 ...  -9.700008  -9.448193 -10.009056]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.970916 -11.357188 -12.165511 ... -11.649903 -11.512337 -11.882691]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.922231 -11.72262  -12.889344 ... -11.845514 -11.179037 -11.964209]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.9741235 -7.779363  -8.484058  ... -7.6588573 -7.3479395 -7.9217544]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.076003 -11.89435  -12.789419 ... -12.127295 -11.724373 -12.097569]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.42469  -11.530261 -11.929119 ... -11.43918  -11.348652 -11.453442]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.520835 -11.262342 -12.16688  ... -11.212113 -10.845395 -11.416534]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.879332  -8.569043  -9.376301  ... -8.619593  -8.4516535 -8.929345 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.903811 -8.585278 -9.392915 ... -8.690926 -8.487799 -8.98662 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.500456  -9.422618 -10.297583 ...  -9.478561  -9.228062  -9.473815]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.672277 -8.350827 -9.086444 ... -8.275025 -8.092173 -8.637204]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.683638 -8.362789 -9.144146 ... -8.326931 -8.128355 -8.670868]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.154147  -7.9003234 -8.712154  ... -7.916471  -7.727686  -8.2335   ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.02457  -11.968005 -12.650782 ... -11.590952 -11.301149 -11.828472]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.283043 -12.108271 -13.030906 ... -12.391871 -11.987008 -12.327281]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.272479  -7.9592857 -8.805005  ... -8.110062  -7.840693  -8.391483 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.274057 -12.08432  -12.998598 ... -12.412241 -11.973463 -12.319777]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.2508955 -7.949837  -8.782671  ... -8.089201  -7.824367  -8.368733 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.9067883 -7.6356244 -8.358529  ... -7.626674  -7.3523345 -7.97578  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.263381  -6.0621543 -6.8701906 ... -5.7008157 -5.4942923 -6.169351 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.266708  -12.065318  -12.991668  ... -12.3624935 -11.933049
 -12.296452 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.419007  -7.134506  -7.8606763 ... -7.180111  -6.948496  -7.511888 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.28969  -12.084075 -13.008969 ... -12.393968 -11.964904 -12.321924]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.2963   -12.089175 -13.015677 ... -12.402597 -11.970643 -12.328529]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.047468 -8.740606 -9.416886 ... -8.560995 -8.40508  -8.943327]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.291523 -12.987521 -13.778067 ... -13.025989 -12.672547 -13.115683]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.925034 -11.691942 -12.673491 ... -11.849044 -11.481688 -11.906191]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.503757  -8.317388  -9.343353  ... -8.089508  -7.8411384 -8.52093  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.3002396 -7.0246186 -8.05706   ... -7.0402603 -6.7384634 -7.4504666]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.570655  -8.132107  -8.995434  ... -8.302469  -7.8648043 -8.499244 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.314322 -10.169613 -10.664238 ...  -9.992712 -10.17021  -10.305614]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.2921295 -11.149794  -11.999521  ... -11.120108  -10.752598
 -11.332274 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.573968 -11.376126 -12.453549 ... -11.295028 -10.923495 -11.629171]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.696147  -9.573022 -10.386373 ...  -9.780437  -9.382077  -9.814629]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-17.837032 -17.382637 -18.75605  ... -17.305843 -17.384245 -17.954075]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.295673 -12.108342 -13.022563 ... -12.437511 -12.001502 -12.342701]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.579353 -10.548033 -11.311262 ... -10.525939 -10.388851 -10.668731]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.456102 -10.410637 -11.276643 ... -10.655053 -10.491684 -10.735067]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.1955633 -5.5700283 -6.608128  ... -6.105782  -5.8627386 -5.8350015]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.406905  -10.3027315 -10.63651   ... -10.064386  -10.264288
 -10.392098 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.101942  -11.837479  -12.750015  ... -11.8123045 -11.620766
 -12.141723 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.081006  -8.765654  -9.617622  ... -8.839651  -8.6428385 -9.12756  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.741645 -12.654142 -13.357883 ... -12.282618 -11.981171 -12.532702]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.297782 -12.109525 -13.021241 ... -12.436321 -12.002637 -12.337513]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.3139105 -8.202436  -8.671289  ... -8.189184  -8.046193  -8.293608 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.715532 -11.464547 -12.529975 ... -11.794915 -11.380593 -11.696259]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.751132 -11.852697 -12.46188  ... -11.790783 -11.700255 -11.75004 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.800255 -8.95597  -9.523531 ... -9.154619 -8.984534 -9.197996]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.519645  -7.461103  -7.9770994 ... -7.9604974 -7.7553544 -7.8501177]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.253555 -12.3401   -12.660986 ... -12.464868 -12.353792 -12.38362 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.744952 -10.110094 -10.380674 ...  -9.988661 -10.072706 -10.118578]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.619152  -11.652968  -12.518077  ... -11.146249  -11.142151
 -11.5485935]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.150496  -11.9432125 -12.916335  ... -12.223617  -11.802599
 -12.167628 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.945914  -8.858934  -9.740886  ... -9.11392   -8.851352  -9.2118025]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.447369 -8.396013 -9.169543 ... -8.506661 -8.306028 -8.548489]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.164741  -6.1565876 -6.104415  ... -6.4958954 -6.411542  -6.232363 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.9764566 -8.050856  -8.753152  ... -8.340491  -8.086081  -8.37991  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.550283  -6.5120325 -7.1249814 ... -6.9206295 -6.6252027 -6.8242803]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.221952  -12.03772   -12.889217  ... -12.30389   -11.8916235
 -12.250566 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.404151  -11.2063265 -12.054292  ... -11.453853  -10.667854
 -11.497272 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.088694  -11.887163  -12.776614  ... -12.1760845 -11.757672
 -12.1146555]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.399025  -12.163938  -13.109199  ... -12.4391575 -12.049199
 -12.4217415]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.016788  -11.826162  -12.636038  ... -11.726959  -11.4643755
 -11.853146 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.040928 -12.156597 -12.553808 ... -11.750838 -11.758278 -11.866213]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.191288 -12.002935 -12.950046 ... -12.305546 -11.883257 -12.234426]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.813889 -12.44772  -13.499949 ... -12.621723 -12.359534 -12.824725]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.807125  -8.4993725 -9.242039  ... -8.45001   -8.255435  -8.781942 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.597471 -11.46513  -12.317364 ... -11.148058 -10.920688 -11.555481]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.128772 -11.926445 -12.8047   ... -12.221327 -11.809412 -12.157506]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.20462  -11.980902 -12.965434 ... -12.220987 -11.897695 -12.25103 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.466927 -12.514446 -13.078365 ... -12.240089 -12.384331 -12.464017]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.310527 -12.114083 -13.073966 ... -12.418689 -12.001158 -12.3652  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.527265 -12.546111 -13.578735 ... -12.205237 -11.89905  -12.510607]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.901731 -8.595725 -9.371969 ... -8.542713 -8.338834 -8.893511]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.20985  -12.081076 -12.878461 ... -12.07904  -11.889842 -12.243061]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.45448   -5.8719163 -6.9700317 ... -6.3840127 -6.132877  -6.042683 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.744227  -5.1090364 -6.3558903 ... -5.384082  -5.2535243 -5.350347 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.964683 -10.872207 -11.722083 ... -10.246819  -9.93462  -10.63794 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.074776 -12.015347 -12.701719 ... -11.672714 -11.413243 -11.900203]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.498628 -12.4209   -13.196931 ... -12.167072 -11.876157 -12.327893]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.000511 -12.52399  -13.107586 ... -12.892902 -12.535823 -12.618628]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.3678164 -4.7045045 -5.673591  ... -4.982635  -4.592763  -4.7037597]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.846506 -11.645674 -12.634969 ... -11.944517 -11.491553 -11.882419]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.905117 -7.943388 -7.417075 ... -8.552129 -8.202444 -8.094919]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.62284  -15.40977  -16.351778 ... -15.449837 -15.162161 -15.684335]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.034855 -11.837788 -12.68552  ... -12.110987 -11.707277 -12.054779]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.043007 -13.169247 -13.554549 ... -12.449059 -12.35999  -12.561366]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.295432 -12.035476 -12.99763  ... -12.353548 -11.922601 -12.343837]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.226967 -12.042395 -12.976421 ... -12.348312 -11.918426 -12.265882]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.5700135 -7.2660165 -8.1576395 ... -7.307002  -7.072763  -7.65789  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.718975 -11.300294 -12.345976 ... -11.693235 -11.28419  -11.596083]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.545394 -12.142123 -12.982521 ... -12.325896 -11.973442 -12.098438]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.6449738 -4.2942247 -5.539846  ... -4.583094  -4.3951683 -4.4520445]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.227447  -7.9280696 -8.76509   ... -8.057628  -7.7890644 -8.343076 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.94525  -12.758345 -13.704708 ... -12.892557 -12.563308 -12.987803]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.85079  -8.099506 -8.562158 ... -8.628867 -8.397813 -8.470365]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.765999  -11.5388775 -12.478722  ... -11.590207  -11.290302
 -11.742313 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.4440694 -7.3704495 -8.047941  ... -8.001325  -7.349503  -7.614417 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.341508 -11.197665 -11.87515  ... -10.974285 -10.649587 -11.200223]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.435527  4.555387  4.0419335 ... 4.160177  4.3321495 4.660093 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.113823 -9.055647 -9.514954 ... -9.012396 -8.771727 -9.141183]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.0532453 3.2389631 3.0079756 ... 2.544867  2.984082  3.20851  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.320111  -6.169193  -5.7486377 ... -6.3994102 -6.1134624 -6.112703 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.1817708 3.3293383 3.0815694 ... 2.6347923 3.0248988 3.236933 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.0787098 3.1989994 2.785937  ... 2.7096963 2.9238956 3.2824955]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.306578 -9.193759 -9.367672 ... -9.206442 -9.077598 -9.23918 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.1448507 4.179465  4.1942782 ... 3.7515283 3.9945636 4.272703 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.432158 -10.220581 -11.198089 ... -10.634358 -10.229242 -10.415881]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.670223 -11.480964 -12.271128 ... -11.441435 -11.12281  -11.597966]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.010632 -6.776072 -7.525728 ... -6.598161 -6.363948 -7.002401]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.286796 -10.205966 -10.929748 ...  -9.61548   -9.390705 -10.119615]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.229402  -13.097097  -14.090406  ... -12.9338875 -12.656524
 -13.094817 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.237229 -10.032171 -10.858895 ... -10.258576  -9.985059 -10.176667]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.407709 -13.354687 -13.94861  ... -12.631029 -12.514561 -13.207669]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.091355  -11.8904705 -12.848871  ... -12.204443  -11.761366
 -12.129766 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.982321 -12.543558 -13.478029 ... -12.695753 -12.561556 -12.959952]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.168583 -11.981076 -12.906316 ... -12.22487  -11.825388 -12.21207 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.5700796 3.6554244 3.2386074 ... 3.2223651 3.3809369 3.7360625]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.971616 -9.816029 -9.995486 ... -9.639567 -9.594953 -9.99979 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.260994 -10.05893  -10.844927 ... -10.231572  -9.98626  -10.180858]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-18.026903 -17.684433 -19.084711 ... -16.992928 -17.100266 -18.087347]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.297341 -12.100288 -13.021209 ... -12.389938 -11.961542 -12.323061]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.297717 -12.10949  -13.022461 ... -12.438354 -12.003317 -12.344245]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.688713  -7.3961    -8.157354  ... -7.477236  -7.2406783 -7.7953534]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.415732 -12.34869  -13.11432  ... -12.136218 -11.595258 -12.331776]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.197457 -11.223777 -11.74284  ... -11.609664 -11.033449 -11.185444]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.936596 -11.713215 -12.62176  ... -11.867948 -11.534012 -11.938704]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.961402 -11.73865  -12.658879 ... -11.892353 -11.569089 -11.963132]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.27294  -12.084494 -12.966281 ... -12.379555 -11.959624 -12.315023]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.563632  -7.292774  -8.034341  ... -7.361724  -7.092133  -7.6554127]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.784341 -11.579848 -12.507973 ... -11.790697 -11.406387 -11.815516]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.103667  -8.80428   -9.607949  ... -8.852572  -8.635171  -9.1171255]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.061798 -13.022654 -13.576248 ... -12.35802  -12.217839 -12.609433]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.165565 -8.873924 -9.749847 ... -8.725678 -8.604858 -9.1431  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.145743 -14.92769  -16.143177 ... -14.755973 -14.585133 -15.177311]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.229579 -13.145803 -13.883448 ... -13.07703  -13.09331  -13.231065]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.712428 -11.568572 -12.435514 ... -11.69877  -11.445978 -11.832075]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.560185 -11.425215 -12.276865 ... -11.564375 -11.300476 -11.683852]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.275148 -12.077408 -12.990684 ... -12.422969 -11.964236 -12.30806 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.806709 -11.555735 -13.115814 ... -11.666979 -11.213442 -12.101143]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.816861 -11.593448 -12.623978 ... -11.838411 -11.415953 -11.811294]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.993501 -12.72945  -13.644369 ... -12.565549 -12.377735 -12.712693]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.6618373 2.7489235 2.4049473 ... 2.272059  2.4719746 2.8265452]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.137069 -11.934109 -12.903093 ... -12.210651 -11.788273 -12.152866]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.250678 -12.007528 -12.961876 ... -12.218073 -11.889364 -12.241207]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.55861  -12.388278 -13.202464 ... -12.420021 -12.19383  -12.609467]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.360167  -7.168574  -7.001389  ... -7.4679627 -7.280907  -7.4160175]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.585067  -11.364749  -12.142148  ... -11.6466255 -11.178773
 -11.629927 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.113693 -11.941147 -12.88589  ... -12.208929 -11.817781 -12.201936]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.841169  -9.742188 -10.055606 ...  -9.482837  -9.681382  -9.809668]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.475777 -12.033243 -13.023383 ... -12.428853 -12.101708 -12.329635]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.019545 -13.928323 -15.300221 ... -13.631693 -13.241928 -13.894471]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.102963 -11.890556 -12.81272  ... -12.192767 -11.75241  -12.139936]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.322436 -10.134467 -10.9155   ... -10.320732 -10.045249 -10.276451]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.826978  -7.5462575 -7.1391726 ... -7.9805336 -7.740324  -7.9280233]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.229099 -9.009163 -9.507941 ... -9.494477 -9.181484 -9.284533]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.240739 -10.215989 -10.624146 ...  -9.672995  -9.551871  -9.900616]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.58483   -8.4293995 -8.625905  ... -8.672929  -8.477917  -8.593579 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.292504  -8.011543  -8.901714  ... -8.067174  -7.7962456 -8.405826 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.604685 -11.317599 -11.557011 ... -11.102804 -11.674912 -11.285372]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.899338 -11.751192 -12.504011 ... -11.700824 -11.489831 -11.915641]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.087377 -8.781486 -9.699944 ... -8.685548 -8.538386 -9.08184 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.814654  -8.672795  -9.071736  ... -8.2693405 -8.276891  -8.551801 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.299357 -8.003556 -8.700016 ... -7.818649 -7.631374 -8.2183  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.717966 -10.709223 -10.870807 ...  -9.923502  -9.943215 -10.314557]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.482923 -9.121208 -9.646593 ... -9.492099 -9.329441 -9.447245]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.88541  -11.688509 -12.583326 ... -11.963499 -11.468372 -11.985985]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.9099638 4.0408216 3.470187  ... 3.7230604 3.8144388 4.033966 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.867735 -13.451948 -14.350849 ... -13.551833 -12.911899 -13.594737]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.937533 -11.875817 -12.451493 ... -11.358798 -11.143614 -11.686322]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.314658 -12.1251   -13.057095 ... -12.438865 -12.006407 -12.357768]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.47133  -12.454797 -13.163046 ... -12.207814 -12.142608 -12.434259]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.339277 -12.239475 -12.997734 ... -12.269319 -12.009905 -12.311868]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.883917 -14.675587 -15.592305 ... -14.373443 -14.170576 -14.77728 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.200358 -10.082614 -10.942221 ... -10.171824  -9.794765 -10.246592]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.4655604 -7.170497  -7.9456472 ... -7.2728076 -7.015607  -7.574081 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.563866  -7.302364  -8.055723  ... -7.5327435 -7.101465  -7.7604556]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.550075 -10.349591 -11.491927 ... -10.455049  -9.919559 -10.746633]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.475294 -10.284604 -11.429872 ... -10.360192  -9.822718 -10.678542]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.481532  -8.113935  -8.887261  ... -8.174103  -7.8682227 -8.423069 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.538128 -11.327764 -12.28068  ... -11.484054 -11.061783 -11.568773]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.034992 -8.682437 -9.438321 ... -8.7099   -8.382073 -8.937345]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.554638 -10.634522 -11.237    ... -10.273156  -9.785389 -10.556025]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.9571047 -7.755025  -8.499771  ... -7.826896  -7.4995217 -8.101305 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.46386  -13.363868 -14.429638 ... -13.243972 -13.061588 -13.490065]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.434441 -8.107894 -8.900371 ... -8.092016 -7.887561 -8.441968]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.294225 -14.271951 -14.693853 ... -13.980332 -13.852779 -14.272748]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.286888  -12.094704  -13.00521   ... -12.3757715 -11.947605
 -12.307853 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.006561 -8.689508 -9.498565 ... -8.655038 -8.442191 -8.997103]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.088987 -11.867716 -12.50385  ... -11.777954 -11.497929 -12.0289  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.458613  -13.181708  -14.003875  ... -12.5835905 -12.404783
 -13.126891 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.802714 -8.82135  -8.876823 ... -7.914931 -7.878113 -8.145547]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.185584 -12.098829 -12.917067 ... -11.993542 -11.735726 -12.108892]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.217942 -7.958824 -8.770373 ... -8.003914 -7.817356 -8.401806]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.295866  -7.967468  -8.734475  ... -7.954005  -7.7562404 -8.30337  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.040231 -11.826273 -12.747042 ... -12.066745 -11.674361 -12.082639]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.636502 -11.557218 -11.929554 ... -11.605513 -11.748607 -11.874358]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.034465  -7.9651146 -8.79541   ... -8.177143  -7.8781238 -8.218799 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.872953 -11.620451 -12.397472 ... -11.676713 -11.35161  -11.885556]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.172358  -8.8644905 -9.6568985 ... -8.83397   -8.626811  -9.1705265]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.005066  -10.903078  -11.498086  ... -10.3807335 -10.20721
 -10.697156 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.58474    -9.254217  -10.045329  ...  -8.5887985  -8.281483
  -9.128985 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.592661 -11.468345 -11.886784 ... -10.790533 -10.419359 -11.160261]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.37161  -9.021324 -9.894488 ... -9.071332 -8.856394 -9.390765]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.8758965 -7.6017528 -8.479911  ... -7.4348025 -7.259458  -7.883519 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.176151 -11.985026 -12.866138 ... -12.248341 -11.854802 -12.211688]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.618458 -8.355385 -9.230636 ... -8.169282 -8.015575 -8.618026]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.779928 -8.523618 -9.394218 ... -8.326209 -8.169589 -8.76654 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.023419 -10.823166 -11.642564 ... -10.581352 -10.197147 -10.918345]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.8849483 -7.6165986 -8.278523  ... -7.2845316 -7.150858  -7.7558517]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.5232   -11.271412 -12.11587  ... -11.254649 -10.90971  -11.405441]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.250842  -7.942986  -8.668636  ... -7.8689904 -7.674257  -8.238034 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.351118 -11.150926 -11.728508 ... -11.246617 -10.98977  -11.341125]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.5911    -8.340151  -9.258577  ... -8.11994   -7.9641314 -8.582363 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.357073 -10.199165 -10.866441 ...  -9.842487  -9.768979 -10.186365]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.66274  -8.368839 -9.129867 ... -8.347094 -8.141317 -8.68724 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.127748 -7.822878 -8.592816 ... -7.802403 -7.596207 -8.154469]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.139904 -10.93857  -11.627562 ... -10.349414 -10.0426   -10.957118]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.559905 -8.310562 -8.946917 ... -8.057552 -7.918109 -8.475623]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.4490333 3.5374749 3.079492  ... 3.0979595 3.2525373 3.596181 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.051506 -13.907126 -15.07077  ... -13.732486 -13.50063  -13.960355]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.188974  -11.990646  -12.914702  ... -12.264971  -11.8424635
 -12.210157 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.281666 -12.074976 -13.001535 ... -12.385632 -11.955541 -12.307069]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.223186  -15.625493  -17.35583   ... -15.8333025 -15.679665
 -16.181475 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.178506 -11.991851 -12.91093  ... -12.300139 -11.87396  -12.225082]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.3259115 -13.3880205 -13.686731  ... -12.872249  -12.899332
 -13.3362   ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.576851  -11.1345215 -12.039802  ... -11.478512  -11.189302
 -11.490383 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.2705398 -7.4638186 -7.9931674 ... -8.123747  -7.7767158 -7.9311347]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.523292  -8.278732  -9.285743  ... -8.145677  -7.94491   -8.6011305]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.972504 -8.703435 -9.63958  ... -8.498213 -8.349449 -8.959919]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.807165 -11.168977 -12.44407  ... -11.681871 -11.406588 -11.46131 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.925248 -8.597436 -9.56539  ... -8.490728 -8.335567 -8.928311]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.441456 -15.456535 -15.871814 ... -14.850344 -15.07436  -15.331776]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.427532  -4.892518  -6.194691  ... -4.9445305 -4.8762317 -4.9740095]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.079931 -11.874296 -12.391001 ... -11.441271 -11.349081 -11.693363]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.792551  -9.609717 -10.184265 ...  -9.781127  -9.561469  -9.751   ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.284617 -12.174105 -13.032172 ... -12.558649 -12.246718 -12.328757]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.233882 -12.046084 -12.945361 ... -12.355104 -11.924217 -12.278476]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.7696295 -14.554104  -16.127497  ... -14.465966  -14.199519
 -14.829995 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-19.537243 -19.233763 -20.56946  ... -18.21658  -18.45657  -19.618118]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.122086 -13.782542 -14.824033 ... -13.391372 -13.353845 -14.056845]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.805203 -11.58505  -12.627096 ... -11.830621 -11.414859 -11.803893]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.266064  -7.9960213 -8.77198   ... -8.050384  -7.748154  -8.354949 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.1866   -8.881314 -9.768293 ... -8.774248 -8.507775 -9.105248]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.368081 -12.581618 -12.773311 ... -12.069744 -12.182945 -12.227834]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.131555  -6.891106  -7.8164897 ... -7.5396323 -7.296646  -7.536008 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.053442  4.1596212 3.6725163 ... 3.7043903 3.8784785 4.1959977]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.403566 -16.081116 -17.791182 ... -15.769498 -15.633228 -16.247398]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.716386 -12.8377   -13.201536 ... -12.350425 -12.3442   -12.516841]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.572254  -4.7599826 -4.0292907 ... -5.3515587 -5.3085136 -4.961901 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.9428644 -6.093126  -5.378648  ... -6.7455425 -6.66372   -6.3593845]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.4684024 -4.654163  -3.912153  ... -5.295158  -5.2738447 -4.88182  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.4015803 -7.283336  -7.747149  ... -7.552822  -7.1668816 -7.5503874]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.0320406 3.014256  3.0358331 ... 2.5795321 2.8340619 3.1261585]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.049656  4.0455556 4.0736623 ... 3.5560048 3.770062  4.044667 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.678971  -4.7768817 -4.3003893 ... -5.673545  -5.3448796 -5.007261 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.3847184 3.5144792 3.270038  ... 2.8708503 3.222332  3.4240193]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.2378345 3.3737044 3.146899  ... 2.6801376 3.0544243 3.2648616]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.8961174 4.0270987 3.7957332 ... 3.350159  3.6983106 3.9252017]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.106064  3.2724674 3.0993583 ... 2.415605  2.877169  3.116757 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.0745928 3.2332406 3.0897284 ... 2.3822021 2.8432236 3.0684066]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.1397257 4.3053646 4.1401095 ... 3.4650133 3.9025195 4.128293 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.2053046 -4.7933187 -5.843832  ... -4.9628644 -5.0551176 -4.920248 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.704919 -10.47124  -10.800096 ... -10.785767 -10.579264 -10.681136]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.493605  -10.287144  -11.260107  ... -10.688953  -10.2912445
 -10.471503 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.270282  -10.073707  -10.99558   ... -10.499278  -10.084934
 -10.2685175]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.618695  -4.640684  -4.240811  ... -5.1449227 -4.8657928 -4.615258 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.5593207 3.5551844 3.5574098 ... 3.0762029 3.332403  3.594356 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.7294655 -12.376626  -13.360407  ... -12.648484  -12.393368
 -12.663054 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.7202835 4.8091536 4.322198  ... 4.4189515 4.540819  4.888205 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.4603348 3.4350264 3.4853265 ... 2.9490094 3.1694117 3.446331 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.990703 -8.630897 -8.99158  ... -9.235486 -8.925355 -9.006544]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.571827  -11.284571  -12.262742  ... -11.5791645 -11.201027
 -11.511564 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.5068054 -6.40937   -5.891961  ... -6.933842  -6.8658566 -6.6032014]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.443331 -10.237809 -11.199856 ... -10.628601 -10.238804 -10.429786]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.720683 -10.602119 -11.010578 ... -10.492158 -10.63503  -10.777513]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.419404 -11.407965 -11.905323 ... -10.84633  -10.637003 -11.128542]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.288916 -11.98538  -12.796677 ... -12.019596 -12.009553 -12.357068]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.318269 -12.01604  -12.815151 ... -12.050196 -12.042486 -12.394848]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.292164  -7.9953504 -8.708132  ... -7.86488   -7.6810164 -8.237356 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.771596 -8.462092 -9.286307 ... -8.536271 -8.352265 -8.811243]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[3.3630502 3.499423  3.0538247 ... 3.019001  3.2358797 3.5326781]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.409527 -11.248263 -11.8228   ... -11.147851 -11.023015 -11.453238]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.77286  -8.494554 -9.358625 ... -8.441263 -8.243116 -8.801655]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.1580057 -7.062776  -7.483668  ... -7.7267375 -7.3880973 -7.304209 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.435426 -12.127356 -13.135029 ... -12.432831 -12.052431 -12.487432]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.141505   -9.952289  -11.196066  ...  -9.897295   -9.340255
 -10.3606415]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.239498 -12.071333 -12.990838 ... -11.986276 -11.621091 -12.023417]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.60064  -11.356542 -12.365657 ... -11.6065   -11.207058 -11.530888]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.243012 -8.078218 -8.732426 ... -8.268872 -7.956277 -8.28141 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.832861 -11.648926 -12.5929   ... -11.917026 -11.417439 -11.928813]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.134589 -10.030239 -10.363069 ...  -9.812842  -9.992365 -10.13406 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.9279423 -6.7907996 -6.491762  ... -6.9495482 -6.8521347 -6.6663356]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.609357  -6.525222  -6.0732684 ... -6.631433  -6.5699034 -6.3210244]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.622515  -7.5136037 -7.7072678 ... -7.724962  -7.4769635 -7.5765514]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.690626  -7.5739202 -7.6372275 ... -7.7492805 -7.505291  -7.586729 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.8450503 -7.7331796 -7.824209  ... -7.8958983 -7.7326612 -7.723679 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.326424 -8.177108 -8.543448 ... -8.37237  -8.129055 -8.251098]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.407609  2.6118655 2.3955789 ... 1.8875533 2.357018  2.606857 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.105418  -7.9794135 -7.722032  ... -8.07804   -7.978744  -7.8591785]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.055644  -7.928038  -7.7434964 ... -8.08192   -7.9904375 -7.848301 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.802222  -7.6493034 -7.871823  ... -7.892197  -7.6944113 -7.719954 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.813284 -11.623357 -12.531952 ... -12.066779 -11.567708 -11.893216]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.985827 -11.767456 -12.695842 ... -12.24054  -11.705344 -11.949506]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.540057 -8.540511 -9.43846  ... -8.6896   -8.426173 -8.756993]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.80084   -9.805435 -10.650505 ... -10.188481  -9.871402 -10.085288]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.297447  -12.0974655 -13.023015  ... -12.400965  -11.9754305
 -12.32769  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.686357  -11.477596  -12.4737015 ... -11.741932  -11.228713
 -11.757515 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4.245113  4.356451  3.9731557 ... 3.9685123 4.1249943 4.468341 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.581031   -9.476623  -11.263061  ...  -9.3558235  -8.775517
  -9.933779 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.4983773 -6.222138  -7.386195  ... -6.424826  -5.921089  -6.7532005]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

PairwiseArrays with keys: connectivities, distances

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:66: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  sc.tl.leiden(n_adata, resolution=4.0)

{'cellxgene_census/dkd_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3432203389830508, 'macro': 0.25917444685094343, 'micro': 0.3432203389830508, 'weighted': 0.34017252137470233}}, 'cellxgene_census/dkd_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3550587343690792, 'macro': 0.27207633588309094, 'micro': 0.3550587343690792, 'weighted': 0.3524031871669568}}, 'cellxgene_census/dkd_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3561955286093217, 'macro': 0.2740563641826558, 'micro': 0.3561955286093217, 'weighted': 0.3538971563453317}}, 'cellxgene_census/dkd_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.361121636983706, 'macro': 0.2857142857142857, 'micro': 0.361121636983706, 'weighted': 0.361121636983706}}, 'cellxgene_census/gtex_v9_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4940849057506001, 'macro': 0.32408851632492214, 'micro': 0.4940849057506001, 'weighted': 0.46206164048799947}}, 'cellxgene_census/gtex_v9_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5688216892596455, 'macro': 0.5135325396389532, 'micro': 0.5688216892596455, 'weighted': 0.4995750709500925}}, 'cellxgene_census/gtex_v9_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5477059436913452, 'macro': 0.5371100686494984, 'micro': 0.5477059436913452, 'weighted': 0.5004916521764624}}, 'cellxgene_census/gtex_v9_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5477059436913452, 'macro': 0.5371100686494984, 'micro': 0.5477059436913452, 'weighted': 0.5004916521764624}}, 'cellxgene_census/hypomap_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9151834773007729, 'macro': 0.5292908086154148, 'micro': 0.9151834773007729, 'weighted': 0.8958082650738847}}, 'cellxgene_census/hypomap_cls': {'cell_type_ontology_term_id': {'accuracy': 0.968978102189781, 'macro': 0.7903908766961296, 'micro': 0.968978102189781, 'weighted': 0.9599403890312923}}, 'cellxgene_census/hypomap_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9662408759124088, 'macro': 0.7944891854261397, 'micro': 0.9662408759124088, 'weighted': 0.9600242874056126}}, 'cellxgene_census/hypomap_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.958029197080292, 'macro': 0.6603821577020906, 'micro': 0.958029197080292, 'weighted': 0.9567117318139766}}}
doing  cellxgene_census/mouse_pancreas_atlas

/lustre/fswork/projects/rech/xeg/uat95fg/scdataloader/scdataloader/utils.py:427: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  organismdf = pd.concat(organismdf)

predict epoch start

  0%|          | 0/4716 [00:00<?, ?it/s]

  0%|          | 1/4716 [00:05<7:02:43,  5.38s/it]

  0%|          | 2/4716 [00:06<3:46:49,  2.89s/it]

  0%|          | 3/4716 [00:07<2:43:41,  2.08s/it]

  0%|          | 4/4716 [00:08<2:13:54,  1.71s/it]

  0%|          | 5/4716 [00:09<1:57:24,  1.50s/it]

  0%|          | 6/4716 [00:11<1:47:35,  1.37s/it]

  0%|          | 7/4716 [00:12<1:41:21,  1.29s/it]

  0%|          | 8/4716 [00:13<1:37:16,  1.24s/it]

  0%|          | 9/4716 [00:14<1:34:46,  1.21s/it]

  0%|          | 10/4716 [00:15<1:32:54,  1.18s/it]

  0%|          | 11/4716 [00:16<1:31:33,  1.17s/it]

  0%|          | 12/4716 [00:17<1:30:40,  1.16s/it]

  0%|          | 13/4716 [00:18<1:29:59,  1.15s/it]

  0%|          | 14/4716 [00:20<1:29:35,  1.14s/it]

  0%|          | 15/4716 [00:21<1:29:13,  1.14s/it]

  0%|          | 16/4716 [00:22<1:29:05,  1.14s/it]

  0%|          | 17/4716 [00:23<1:28:56,  1.14s/it]

  0%|          | 18/4716 [00:24<1:28:56,  1.14s/it]

  0%|          | 19/4716 [00:25<1:28:52,  1.14s/it]

  0%|          | 20/4716 [00:26<1:28:51,  1.14s/it]

  0%|          | 21/4716 [00:28<1:28:48,  1.14s/it]

  0%|          | 22/4716 [00:29<1:28:47,  1.13s/it]

  0%|          | 23/4716 [00:30<1:28:48,  1.14s/it]

  1%|          | 24/4716 [00:31<1:28:48,  1.14s/it]

  1%|          | 25/4716 [00:32<1:28:46,  1.14s/it]

  1%|          | 26/4716 [00:33<1:28:47,  1.14s/it]

  1%|          | 27/4716 [00:34<1:28:43,  1.14s/it]

  1%|          | 28/4716 [00:35<1:28:39,  1.13s/it]

  1%|          | 29/4716 [00:37<1:28:37,  1.13s/it]

  1%|          | 30/4716 [00:38<1:28:37,  1.13s/it]

  1%|          | 31/4716 [00:39<1:28:34,  1.13s/it]

  1%|          | 32/4716 [00:40<1:28:36,  1.14s/it]

  1%|          | 33/4716 [00:41<1:28:36,  1.14s/it]

  1%|          | 34/4716 [00:42<1:28:34,  1.14s/it]

  1%|          | 35/4716 [00:43<1:28:37,  1.14s/it]

  1%|          | 36/4716 [00:45<1:28:37,  1.14s/it]

  1%|          | 37/4716 [00:46<1:28:36,  1.14s/it]

  1%|          | 38/4716 [00:47<1:28:38,  1.14s/it]

  1%|          | 39/4716 [00:48<1:28:38,  1.14s/it]

  1%|          | 40/4716 [00:49<1:28:39,  1.14s/it]

  1%|          | 41/4716 [00:50<1:28:37,  1.14s/it]

  1%|          | 42/4716 [00:51<1:28:37,  1.14s/it]

  1%|          | 43/4716 [00:53<1:28:47,  1.14s/it]

  1%|          | 44/4716 [00:54<1:28:39,  1.14s/it]

  1%|          | 45/4716 [00:55<1:28:40,  1.14s/it]

  1%|          | 46/4716 [00:56<1:28:38,  1.14s/it]

  1%|          | 47/4716 [00:57<1:28:37,  1.14s/it]

  1%|          | 48/4716 [00:58<1:28:37,  1.14s/it]

  1%|          | 49/4716 [00:59<1:28:40,  1.14s/it]

  1%|          | 50/4716 [01:00<1:28:38,  1.14s/it]

  1%|          | 51/4716 [01:02<1:28:36,  1.14s/it]

  1%|          | 52/4716 [01:03<1:28:40,  1.14s/it]

  1%|          | 53/4716 [01:04<1:28:44,  1.14s/it]

  1%|          | 54/4716 [01:05<1:28:41,  1.14s/it]

  1%|          | 55/4716 [01:06<1:28:43,  1.14s/it]

  1%|          | 56/4716 [01:07<1:28:41,  1.14s/it]

  1%|          | 57/4716 [01:08<1:28:39,  1.14s/it]

  1%|          | 58/4716 [01:10<1:28:33,  1.14s/it]

  1%|▏         | 59/4716 [01:11<1:28:31,  1.14s/it]

  1%|▏         | 60/4716 [01:12<1:28:35,  1.14s/it]

  1%|▏         | 61/4716 [01:13<1:28:29,  1.14s/it]

  1%|▏         | 62/4716 [01:14<1:28:26,  1.14s/it]

  1%|▏         | 63/4716 [01:15<1:28:26,  1.14s/it]

  1%|▏         | 64/4716 [01:16<1:28:27,  1.14s/it]

  1%|▏         | 65/4716 [01:18<1:28:24,  1.14s/it]

  1%|▏         | 66/4716 [01:19<1:28:21,  1.14s/it]

  1%|▏         | 67/4716 [01:20<1:28:23,  1.14s/it]

  1%|▏         | 68/4716 [01:21<1:28:22,  1.14s/it]

  1%|▏         | 69/4716 [01:22<1:28:24,  1.14s/it]

  1%|▏         | 70/4716 [01:23<1:28:21,  1.14s/it]

  2%|▏         | 71/4716 [01:24<1:28:22,  1.14s/it]

  2%|▏         | 72/4716 [01:26<1:28:22,  1.14s/it]

  2%|▏         | 73/4716 [01:27<1:28:23,  1.14s/it]

  2%|▏         | 74/4716 [01:28<1:28:26,  1.14s/it]

  2%|▏         | 75/4716 [01:29<1:28:21,  1.14s/it]

  2%|▏         | 76/4716 [01:30<1:28:24,  1.14s/it]

  2%|▏         | 77/4716 [01:31<1:28:24,  1.14s/it]

  2%|▏         | 78/4716 [01:32<1:28:22,  1.14s/it]

  2%|▏         | 79/4716 [01:34<1:28:19,  1.14s/it]

  2%|▏         | 80/4716 [01:35<1:28:15,  1.14s/it]

  2%|▏         | 81/4716 [01:36<1:28:14,  1.14s/it]

  2%|▏         | 82/4716 [01:37<1:28:13,  1.14s/it]

  2%|▏         | 83/4716 [01:38<1:28:14,  1.14s/it]

  2%|▏         | 84/4716 [01:39<1:28:15,  1.14s/it]

  2%|▏         | 85/4716 [01:40<1:28:17,  1.14s/it]

  2%|▏         | 86/4716 [01:42<1:28:12,  1.14s/it]

  2%|▏         | 87/4716 [01:43<1:28:09,  1.14s/it]

  2%|▏         | 88/4716 [01:44<1:28:09,  1.14s/it]

  2%|▏         | 89/4716 [01:45<1:28:06,  1.14s/it]

  2%|▏         | 90/4716 [01:46<1:28:11,  1.14s/it]

  2%|▏         | 91/4716 [01:47<1:28:08,  1.14s/it]

  2%|▏         | 92/4716 [01:48<1:28:07,  1.14s/it]

  2%|▏         | 93/4716 [01:50<1:28:08,  1.14s/it]

  2%|▏         | 94/4716 [01:51<1:28:09,  1.14s/it]

  2%|▏         | 95/4716 [01:52<1:28:08,  1.14s/it]

  2%|▏         | 96/4716 [01:53<1:28:08,  1.14s/it]

  2%|▏         | 97/4716 [01:54<1:28:10,  1.15s/it]

  2%|▏         | 98/4716 [01:55<1:28:11,  1.15s/it]

  2%|▏         | 99/4716 [01:56<1:28:07,  1.15s/it]

  2%|▏         | 100/4716 [01:58<1:28:08,  1.15s/it]

  2%|▏         | 101/4716 [01:59<1:28:07,  1.15s/it]

  2%|▏         | 102/4716 [02:00<1:28:07,  1.15s/it]

  2%|▏         | 103/4716 [02:01<1:28:06,  1.15s/it]

  2%|▏         | 104/4716 [02:02<1:28:02,  1.15s/it]

  2%|▏         | 105/4716 [02:03<1:28:03,  1.15s/it]

  2%|▏         | 106/4716 [02:04<1:28:01,  1.15s/it]

  2%|▏         | 107/4716 [02:06<1:27:58,  1.15s/it]

  2%|▏         | 108/4716 [02:07<1:27:59,  1.15s/it]

  2%|▏         | 109/4716 [02:08<1:28:02,  1.15s/it]

  2%|▏         | 110/4716 [02:09<1:28:00,  1.15s/it]

  2%|▏         | 111/4716 [02:10<1:27:56,  1.15s/it]

  2%|▏         | 112/4716 [02:11<1:27:59,  1.15s/it]

  2%|▏         | 113/4716 [02:13<1:27:56,  1.15s/it]

  2%|▏         | 114/4716 [02:14<1:28:00,  1.15s/it]

  2%|▏         | 115/4716 [02:15<1:27:57,  1.15s/it]

  2%|▏         | 116/4716 [02:16<1:27:53,  1.15s/it]

  2%|▏         | 117/4716 [02:17<1:27:58,  1.15s/it]

  3%|▎         | 118/4716 [02:18<1:27:59,  1.15s/it]

  3%|▎         | 119/4716 [02:19<1:27:55,  1.15s/it]

  3%|▎         | 120/4716 [02:21<1:27:54,  1.15s/it]

  3%|▎         | 121/4716 [02:22<1:27:55,  1.15s/it]

  3%|▎         | 122/4716 [02:23<1:27:54,  1.15s/it]

  3%|▎         | 123/4716 [02:24<1:27:53,  1.15s/it]

  3%|▎         | 124/4716 [02:25<1:27:49,  1.15s/it]

  3%|▎         | 125/4716 [02:26<1:27:45,  1.15s/it]

  3%|▎         | 126/4716 [02:27<1:27:43,  1.15s/it]

  3%|▎         | 127/4716 [02:29<1:27:45,  1.15s/it]

  3%|▎         | 128/4716 [02:30<1:27:48,  1.15s/it]

  3%|▎         | 129/4716 [02:31<1:27:42,  1.15s/it]

  3%|▎         | 130/4716 [02:32<1:27:41,  1.15s/it]

  3%|▎         | 131/4716 [02:33<1:27:41,  1.15s/it]

  3%|▎         | 132/4716 [02:34<1:27:43,  1.15s/it]

  3%|▎         | 133/4716 [02:35<1:27:43,  1.15s/it]

  3%|▎         | 134/4716 [02:37<1:27:45,  1.15s/it]

  3%|▎         | 135/4716 [02:38<1:27:53,  1.15s/it]

  3%|▎         | 136/4716 [02:39<1:27:53,  1.15s/it]

  3%|▎         | 137/4716 [02:40<1:27:47,  1.15s/it]

  3%|▎         | 138/4716 [02:41<1:27:42,  1.15s/it]

  3%|▎         | 139/4716 [02:42<1:27:40,  1.15s/it]

  3%|▎         | 140/4716 [02:44<1:27:39,  1.15s/it]

  3%|▎         | 141/4716 [02:45<1:27:35,  1.15s/it]

  3%|▎         | 142/4716 [02:46<1:27:35,  1.15s/it]

  3%|▎         | 143/4716 [02:47<1:27:32,  1.15s/it]

  3%|▎         | 144/4716 [02:48<1:27:31,  1.15s/it]

  3%|▎         | 145/4716 [02:49<1:27:33,  1.15s/it]

  3%|▎         | 146/4716 [02:50<1:27:32,  1.15s/it]

  3%|▎         | 147/4716 [02:52<1:27:39,  1.15s/it]

  3%|▎         | 148/4716 [02:53<1:27:36,  1.15s/it]

  3%|▎         | 149/4716 [02:54<1:27:37,  1.15s/it]

  3%|▎         | 150/4716 [02:55<1:27:38,  1.15s/it]

  3%|▎         | 151/4716 [02:56<1:27:34,  1.15s/it]

  3%|▎         | 152/4716 [02:57<1:27:33,  1.15s/it]

  3%|▎         | 153/4716 [02:58<1:27:33,  1.15s/it]

  3%|▎         | 154/4716 [03:00<1:27:34,  1.15s/it]

  3%|▎         | 155/4716 [03:01<1:27:29,  1.15s/it]

  3%|▎         | 156/4716 [03:02<1:27:24,  1.15s/it]

  3%|▎         | 157/4716 [03:03<1:27:23,  1.15s/it]

  3%|▎         | 158/4716 [03:04<1:27:25,  1.15s/it]

  3%|▎         | 159/4716 [03:05<1:27:27,  1.15s/it]

  3%|▎         | 160/4716 [03:07<1:27:29,  1.15s/it]

  3%|▎         | 161/4716 [03:08<1:27:32,  1.15s/it]

  3%|▎         | 162/4716 [03:09<1:27:28,  1.15s/it]

  3%|▎         | 163/4716 [03:10<1:27:24,  1.15s/it]

  3%|▎         | 164/4716 [03:11<1:27:20,  1.15s/it]

  3%|▎         | 165/4716 [03:12<1:27:14,  1.15s/it]

  4%|▎         | 166/4716 [03:13<1:27:19,  1.15s/it]

  4%|▎         | 167/4716 [03:15<1:27:16,  1.15s/it]

  4%|▎         | 168/4716 [03:16<1:27:14,  1.15s/it]

  4%|▎         | 169/4716 [03:17<1:27:12,  1.15s/it]

  4%|▎         | 170/4716 [03:18<1:27:12,  1.15s/it]

  4%|▎         | 171/4716 [03:19<1:27:13,  1.15s/it]

  4%|▎         | 172/4716 [03:20<1:27:12,  1.15s/it]

  4%|▎         | 173/4716 [03:22<1:27:11,  1.15s/it]

  4%|▎         | 174/4716 [03:23<1:27:11,  1.15s/it]

  4%|▎         | 175/4716 [03:24<1:27:16,  1.15s/it]

  4%|▎         | 176/4716 [03:25<1:27:07,  1.15s/it]

  4%|▍         | 177/4716 [03:26<1:27:02,  1.15s/it]

  4%|▍         | 178/4716 [03:27<1:27:01,  1.15s/it]

  4%|▍         | 179/4716 [03:28<1:26:59,  1.15s/it]

  4%|▍         | 180/4716 [03:30<1:27:05,  1.15s/it]

  4%|▍         | 181/4716 [03:31<1:27:06,  1.15s/it]

  4%|▍         | 182/4716 [03:32<1:27:07,  1.15s/it]

  4%|▍         | 183/4716 [03:33<1:27:03,  1.15s/it]

  4%|▍         | 184/4716 [03:34<1:27:04,  1.15s/it]

  4%|▍         | 185/4716 [03:35<1:26:59,  1.15s/it]

  4%|▍         | 186/4716 [03:36<1:26:58,  1.15s/it]

  4%|▍         | 187/4716 [03:38<1:26:58,  1.15s/it]

  4%|▍         | 188/4716 [03:39<1:27:02,  1.15s/it]

  4%|▍         | 189/4716 [03:40<1:26:59,  1.15s/it]

  4%|▍         | 190/4716 [03:41<1:27:04,  1.15s/it]

  4%|▍         | 191/4716 [03:42<1:27:03,  1.15s/it]

  4%|▍         | 192/4716 [03:43<1:26:59,  1.15s/it]

  4%|▍         | 193/4716 [03:45<1:26:59,  1.15s/it]

  4%|▍         | 194/4716 [03:46<1:27:05,  1.16s/it]

  4%|▍         | 195/4716 [03:47<1:27:03,  1.16s/it]

  4%|▍         | 196/4716 [03:48<1:26:58,  1.15s/it]

  4%|▍         | 197/4716 [03:49<1:26:54,  1.15s/it]

  4%|▍         | 198/4716 [03:50<1:26:57,  1.15s/it]

  4%|▍         | 199/4716 [03:51<1:26:54,  1.15s/it]

  4%|▍         | 200/4716 [03:53<1:26:50,  1.15s/it]

  4%|▍         | 201/4716 [03:54<1:26:53,  1.15s/it]

  4%|▍         | 202/4716 [03:55<1:26:48,  1.15s/it]

  4%|▍         | 203/4716 [03:56<1:26:43,  1.15s/it]

  4%|▍         | 204/4716 [03:57<1:26:41,  1.15s/it]

  4%|▍         | 205/4716 [03:58<1:26:38,  1.15s/it]

  4%|▍         | 206/4716 [04:00<1:26:42,  1.15s/it]

  4%|▍         | 207/4716 [04:01<1:26:40,  1.15s/it]

  4%|▍         | 208/4716 [04:02<1:26:40,  1.15s/it]

  4%|▍         | 209/4716 [04:03<1:26:35,  1.15s/it]

  4%|▍         | 210/4716 [04:04<1:26:34,  1.15s/it]

  4%|▍         | 211/4716 [04:05<1:26:35,  1.15s/it]

  4%|▍         | 212/4716 [04:06<1:26:34,  1.15s/it]

  5%|▍         | 213/4716 [04:08<1:26:39,  1.15s/it]

  5%|▍         | 214/4716 [04:09<1:26:37,  1.15s/it]

  5%|▍         | 215/4716 [04:10<1:26:33,  1.15s/it]

  5%|▍         | 216/4716 [04:11<1:26:30,  1.15s/it]

  5%|▍         | 217/4716 [04:12<1:26:30,  1.15s/it]

  5%|▍         | 218/4716 [04:13<1:26:33,  1.15s/it]

  5%|▍         | 219/4716 [04:15<1:26:27,  1.15s/it]

  5%|▍         | 220/4716 [04:16<1:26:28,  1.15s/it]

  5%|▍         | 221/4716 [04:17<1:26:31,  1.15s/it]

  5%|▍         | 222/4716 [04:18<1:26:32,  1.16s/it]

  5%|▍         | 223/4716 [04:19<1:26:27,  1.15s/it]

  5%|▍         | 224/4716 [04:20<1:26:28,  1.16s/it]

  5%|▍         | 225/4716 [04:21<1:26:24,  1.15s/it]

  5%|▍         | 226/4716 [04:23<1:26:27,  1.16s/it]

  5%|▍         | 227/4716 [04:24<1:26:19,  1.15s/it]

  5%|▍         | 228/4716 [04:25<1:26:20,  1.15s/it]

  5%|▍         | 229/4716 [04:26<1:26:19,  1.15s/it]

  5%|▍         | 230/4716 [04:27<1:26:23,  1.16s/it]

  5%|▍         | 231/4716 [04:28<1:26:24,  1.16s/it]

  5%|▍         | 232/4716 [04:30<1:26:23,  1.16s/it]

  5%|▍         | 233/4716 [04:31<1:26:23,  1.16s/it]

  5%|▍         | 234/4716 [04:32<1:26:23,  1.16s/it]

  5%|▍         | 235/4716 [04:33<1:26:17,  1.16s/it]

  5%|▌         | 236/4716 [04:34<1:26:07,  1.15s/it]

  5%|▌         | 237/4716 [04:35<1:26:08,  1.15s/it]

  5%|▌         | 238/4716 [04:37<1:26:11,  1.15s/it]

  5%|▌         | 239/4716 [04:38<1:26:10,  1.15s/it]

  5%|▌         | 240/4716 [04:39<1:26:09,  1.15s/it]

  5%|▌         | 241/4716 [04:40<1:26:10,  1.16s/it]

  5%|▌         | 242/4716 [04:41<1:26:07,  1.16s/it]

  5%|▌         | 243/4716 [04:42<1:26:06,  1.15s/it]

  5%|▌         | 244/4716 [04:43<1:26:03,  1.15s/it]

  5%|▌         | 245/4716 [04:45<1:26:01,  1.15s/it]

  5%|▌         | 246/4716 [04:46<1:26:03,  1.16s/it]

  5%|▌         | 247/4716 [04:47<1:26:01,  1.15s/it]

  5%|▌         | 248/4716 [04:48<1:25:59,  1.15s/it]

  5%|▌         | 249/4716 [04:49<1:26:03,  1.16s/it]

  5%|▌         | 250/4716 [04:50<1:26:03,  1.16s/it]

  5%|▌         | 251/4716 [04:52<1:26:01,  1.16s/it]

  5%|▌         | 252/4716 [04:53<1:26:08,  1.16s/it]

  5%|▌         | 253/4716 [04:54<1:26:10,  1.16s/it]

  5%|▌         | 254/4716 [04:55<1:26:11,  1.16s/it]

  5%|▌         | 255/4716 [04:56<1:26:10,  1.16s/it]

  5%|▌         | 256/4716 [04:57<1:25:57,  1.16s/it]

  5%|▌         | 257/4716 [04:58<1:25:53,  1.16s/it]

  5%|▌         | 258/4716 [05:00<1:25:44,  1.15s/it]

  5%|▌         | 259/4716 [05:01<1:25:45,  1.15s/it]

  6%|▌         | 260/4716 [05:02<1:25:49,  1.16s/it]

  6%|▌         | 261/4716 [05:03<1:25:46,  1.16s/it]

  6%|▌         | 262/4716 [05:04<1:25:44,  1.15s/it]

  6%|▌         | 263/4716 [05:05<1:25:44,  1.16s/it]

  6%|▌         | 264/4716 [05:07<1:25:45,  1.16s/it]

  6%|▌         | 265/4716 [05:08<1:25:39,  1.15s/it]

  6%|▌         | 266/4716 [05:09<1:25:36,  1.15s/it]

  6%|▌         | 267/4716 [05:10<1:25:40,  1.16s/it]

  6%|▌         | 268/4716 [05:11<1:25:40,  1.16s/it]

  6%|▌         | 269/4716 [05:12<1:25:44,  1.16s/it]

  6%|▌         | 270/4716 [05:14<1:25:46,  1.16s/it]

  6%|▌         | 271/4716 [05:15<1:25:43,  1.16s/it]

  6%|▌         | 272/4716 [05:16<1:25:42,  1.16s/it]

  6%|▌         | 273/4716 [05:17<1:25:35,  1.16s/it]

  6%|▌         | 274/4716 [05:18<1:25:29,  1.15s/it]

  6%|▌         | 275/4716 [05:19<1:25:30,  1.16s/it]

  6%|▌         | 276/4716 [05:20<1:25:32,  1.16s/it]

  6%|▌         | 277/4716 [05:22<1:25:31,  1.16s/it]

  6%|▌         | 278/4716 [05:23<1:25:30,  1.16s/it]

  6%|▌         | 279/4716 [05:24<1:25:31,  1.16s/it]

  6%|▌         | 280/4716 [05:25<1:25:28,  1.16s/it]

  6%|▌         | 281/4716 [05:26<1:25:30,  1.16s/it]

  6%|▌         | 282/4716 [05:27<1:25:26,  1.16s/it]

  6%|▌         | 283/4716 [05:29<1:25:28,  1.16s/it]

  6%|▌         | 284/4716 [05:30<1:25:22,  1.16s/it]

  6%|▌         | 285/4716 [05:31<1:25:22,  1.16s/it]

  6%|▌         | 286/4716 [05:32<1:25:28,  1.16s/it]

  6%|▌         | 287/4716 [05:33<1:25:28,  1.16s/it]

  6%|▌         | 288/4716 [05:34<1:25:20,  1.16s/it]

  6%|▌         | 289/4716 [05:35<1:25:23,  1.16s/it]

  6%|▌         | 290/4716 [05:37<1:25:18,  1.16s/it]

  6%|▌         | 291/4716 [05:38<1:25:12,  1.16s/it]

  6%|▌         | 292/4716 [05:39<1:25:06,  1.15s/it]

  6%|▌         | 293/4716 [05:40<1:25:10,  1.16s/it]

  6%|▌         | 294/4716 [05:41<1:25:14,  1.16s/it]

  6%|▋         | 295/4716 [05:42<1:25:08,  1.16s/it]

  6%|▋         | 296/4716 [05:44<1:25:09,  1.16s/it]

  6%|▋         | 297/4716 [05:45<1:25:07,  1.16s/it]

  6%|▋         | 298/4716 [05:46<1:25:02,  1.15s/it]

  6%|▋         | 299/4716 [05:47<1:25:02,  1.16s/it]

  6%|▋         | 300/4716 [05:48<1:25:04,  1.16s/it]

  6%|▋         | 301/4716 [05:49<1:25:01,  1.16s/it]

  6%|▋         | 302/4716 [05:50<1:24:59,  1.16s/it]

  6%|▋         | 303/4716 [05:52<1:24:57,  1.16s/it]

  6%|▋         | 304/4716 [05:53<1:24:54,  1.15s/it]

  6%|▋         | 305/4716 [05:54<1:24:56,  1.16s/it]

  6%|▋         | 306/4716 [05:55<1:24:55,  1.16s/it]

  7%|▋         | 307/4716 [05:56<1:24:52,  1.16s/it]

  7%|▋         | 308/4716 [05:57<1:24:49,  1.15s/it]

  7%|▋         | 309/4716 [05:59<1:24:49,  1.15s/it]

  7%|▋         | 310/4716 [06:00<1:24:47,  1.15s/it]

  7%|▋         | 311/4716 [06:01<1:24:52,  1.16s/it]

  7%|▋         | 312/4716 [06:02<1:24:52,  1.16s/it]

  7%|▋         | 313/4716 [06:03<1:24:53,  1.16s/it]

  7%|▋         | 314/4716 [06:04<1:24:49,  1.16s/it]

  7%|▋         | 315/4716 [06:06<1:24:52,  1.16s/it]

  7%|▋         | 316/4716 [06:07<1:24:56,  1.16s/it]

  7%|▋         | 317/4716 [06:08<1:24:56,  1.16s/it]

  7%|▋         | 318/4716 [06:09<1:24:57,  1.16s/it]

  7%|▋         | 319/4716 [06:10<1:24:57,  1.16s/it]

  7%|▋         | 320/4716 [06:11<1:24:55,  1.16s/it]

  7%|▋         | 321/4716 [06:12<1:24:45,  1.16s/it]

  7%|▋         | 322/4716 [06:14<1:24:46,  1.16s/it]

  7%|▋         | 323/4716 [06:15<1:24:43,  1.16s/it]

  7%|▋         | 324/4716 [06:16<1:24:44,  1.16s/it]

  7%|▋         | 325/4716 [06:17<1:24:44,  1.16s/it]

  7%|▋         | 326/4716 [06:18<1:24:45,  1.16s/it]

  7%|▋         | 327/4716 [06:19<1:24:40,  1.16s/it]

  7%|▋         | 328/4716 [06:21<1:24:43,  1.16s/it]

  7%|▋         | 329/4716 [06:22<1:24:37,  1.16s/it]

  7%|▋         | 330/4716 [06:23<1:24:32,  1.16s/it]

  7%|▋         | 331/4716 [06:24<1:24:29,  1.16s/it]

  7%|▋         | 332/4716 [06:25<1:24:26,  1.16s/it]

  7%|▋         | 333/4716 [06:26<1:24:29,  1.16s/it]

  7%|▋         | 334/4716 [06:28<1:24:25,  1.16s/it]

  7%|▋         | 335/4716 [06:29<1:24:24,  1.16s/it]

  7%|▋         | 336/4716 [06:30<1:24:25,  1.16s/it]

  7%|▋         | 337/4716 [06:31<1:24:24,  1.16s/it]

  7%|▋         | 338/4716 [06:32<1:24:24,  1.16s/it]

  7%|▋         | 339/4716 [06:33<1:24:17,  1.16s/it]

  7%|▋         | 340/4716 [06:34<1:24:19,  1.16s/it]

  7%|▋         | 341/4716 [06:36<1:24:15,  1.16s/it]

  7%|▋         | 342/4716 [06:37<1:24:17,  1.16s/it]

  7%|▋         | 343/4716 [06:38<1:24:17,  1.16s/it]

  7%|▋         | 344/4716 [06:39<1:24:18,  1.16s/it]

  7%|▋         | 345/4716 [06:40<1:24:22,  1.16s/it]

  7%|▋         | 346/4716 [06:41<1:24:29,  1.16s/it]

  7%|▋         | 347/4716 [06:43<1:24:23,  1.16s/it]

  7%|▋         | 348/4716 [06:44<1:24:18,  1.16s/it]

  7%|▋         | 349/4716 [06:45<1:24:13,  1.16s/it]

  7%|▋         | 350/4716 [06:46<1:24:09,  1.16s/it]

  7%|▋         | 351/4716 [06:47<1:24:13,  1.16s/it]

  7%|▋         | 352/4716 [06:48<1:24:13,  1.16s/it]

  7%|▋         | 353/4716 [06:50<1:24:12,  1.16s/it]

  8%|▊         | 354/4716 [06:51<1:24:07,  1.16s/it]

  8%|▊         | 355/4716 [06:52<1:24:11,  1.16s/it]

  8%|▊         | 356/4716 [06:53<1:24:07,  1.16s/it]

  8%|▊         | 357/4716 [06:54<1:24:11,  1.16s/it]

  8%|▊         | 358/4716 [06:55<1:24:09,  1.16s/it]

  8%|▊         | 359/4716 [06:56<1:24:02,  1.16s/it]

  8%|▊         | 360/4716 [06:58<1:24:05,  1.16s/it]

  8%|▊         | 361/4716 [06:59<1:24:00,  1.16s/it]

  8%|▊         | 362/4716 [07:00<1:23:56,  1.16s/it]

  8%|▊         | 363/4716 [07:01<1:23:54,  1.16s/it]

  8%|▊         | 364/4716 [07:02<1:23:57,  1.16s/it]

  8%|▊         | 365/4716 [07:03<1:24:01,  1.16s/it]

  8%|▊         | 366/4716 [07:05<1:24:02,  1.16s/it]

  8%|▊         | 367/4716 [07:06<1:23:58,  1.16s/it]

  8%|▊         | 368/4716 [07:07<1:23:56,  1.16s/it]

  8%|▊         | 369/4716 [07:08<1:23:54,  1.16s/it]

  8%|▊         | 370/4716 [07:09<1:23:51,  1.16s/it]

  8%|▊         | 371/4716 [07:10<1:23:44,  1.16s/it]

  8%|▊         | 372/4716 [07:12<1:23:47,  1.16s/it]

  8%|▊         | 373/4716 [07:13<1:23:40,  1.16s/it]

  8%|▊         | 374/4716 [07:14<1:23:43,  1.16s/it]

  8%|▊         | 375/4716 [07:15<1:23:47,  1.16s/it]

  8%|▊         | 376/4716 [07:16<1:23:47,  1.16s/it]

  8%|▊         | 377/4716 [07:17<1:23:42,  1.16s/it]

  8%|▊         | 378/4716 [07:18<1:23:45,  1.16s/it]

  8%|▊         | 379/4716 [07:20<1:23:39,  1.16s/it]

  8%|▊         | 380/4716 [07:21<1:23:36,  1.16s/it]

  8%|▊         | 381/4716 [07:22<1:23:33,  1.16s/it]

  8%|▊         | 382/4716 [07:23<1:23:35,  1.16s/it]

  8%|▊         | 383/4716 [07:24<1:23:42,  1.16s/it]

  8%|▊         | 384/4716 [07:25<1:23:40,  1.16s/it]

  8%|▊         | 385/4716 [07:27<1:23:40,  1.16s/it]

  8%|▊         | 386/4716 [07:28<1:23:36,  1.16s/it]

  8%|▊         | 387/4716 [07:29<1:23:41,  1.16s/it]

  8%|▊         | 388/4716 [07:30<1:23:35,  1.16s/it]

  8%|▊         | 389/4716 [07:31<1:23:34,  1.16s/it]

  8%|▊         | 390/4716 [07:32<1:23:28,  1.16s/it]

  8%|▊         | 391/4716 [07:34<1:23:25,  1.16s/it]

  8%|▊         | 392/4716 [07:35<1:23:23,  1.16s/it]

  8%|▊         | 393/4716 [07:36<1:23:25,  1.16s/it]

  8%|▊         | 394/4716 [07:37<1:23:23,  1.16s/it]

  8%|▊         | 395/4716 [07:38<1:23:21,  1.16s/it]

  8%|▊         | 396/4716 [07:39<1:23:23,  1.16s/it]

  8%|▊         | 397/4716 [07:40<1:23:27,  1.16s/it]

  8%|▊         | 398/4716 [07:42<1:23:24,  1.16s/it]

  8%|▊         | 399/4716 [07:43<1:23:20,  1.16s/it]

  8%|▊         | 400/4716 [07:44<1:23:13,  1.16s/it]

  9%|▊         | 401/4716 [07:45<1:23:16,  1.16s/it]

  9%|▊         | 402/4716 [07:46<1:23:14,  1.16s/it]

  9%|▊         | 403/4716 [07:47<1:23:11,  1.16s/it]

  9%|▊         | 404/4716 [07:49<1:23:12,  1.16s/it]

  9%|▊         | 405/4716 [07:50<1:23:13,  1.16s/it]

  9%|▊         | 406/4716 [07:51<1:23:09,  1.16s/it]

  9%|▊         | 407/4716 [07:52<1:23:12,  1.16s/it]

  9%|▊         | 408/4716 [07:53<1:23:12,  1.16s/it]

  9%|▊         | 409/4716 [07:54<1:23:06,  1.16s/it]

  9%|▊         | 410/4716 [07:56<1:23:04,  1.16s/it]

  9%|▊         | 411/4716 [07:57<1:23:03,  1.16s/it]

  9%|▊         | 412/4716 [07:58<1:23:03,  1.16s/it]

  9%|▉         | 413/4716 [07:59<1:23:07,  1.16s/it]

  9%|▉         | 414/4716 [08:00<1:23:09,  1.16s/it]

  9%|▉         | 415/4716 [08:01<1:23:10,  1.16s/it]

  9%|▉         | 416/4716 [08:02<1:23:05,  1.16s/it]

  9%|▉         | 417/4716 [08:04<1:23:17,  1.16s/it]

  9%|▉         | 418/4716 [08:05<1:23:11,  1.16s/it]

  9%|▉         | 419/4716 [08:06<1:23:06,  1.16s/it]

  9%|▉         | 420/4716 [08:07<1:23:01,  1.16s/it]

  9%|▉         | 421/4716 [08:08<1:22:57,  1.16s/it]

  9%|▉         | 422/4716 [08:09<1:22:59,  1.16s/it]

  9%|▉         | 423/4716 [08:11<1:23:01,  1.16s/it]

  9%|▉         | 424/4716 [08:12<1:22:58,  1.16s/it]

  9%|▉         | 425/4716 [08:13<1:22:59,  1.16s/it]

  9%|▉         | 426/4716 [08:14<1:22:57,  1.16s/it]

  9%|▉         | 427/4716 [08:15<1:22:53,  1.16s/it]

  9%|▉         | 428/4716 [08:16<1:22:47,  1.16s/it]

  9%|▉         | 429/4716 [08:18<1:22:47,  1.16s/it]

  9%|▉         | 430/4716 [08:19<1:22:45,  1.16s/it]

  9%|▉         | 431/4716 [08:20<1:22:44,  1.16s/it]

  9%|▉         | 432/4716 [08:21<1:22:47,  1.16s/it]

  9%|▉         | 433/4716 [08:22<1:22:45,  1.16s/it]

  9%|▉         | 434/4716 [08:23<1:22:42,  1.16s/it]

  9%|▉         | 435/4716 [08:24<1:22:35,  1.16s/it]

  9%|▉         | 436/4716 [08:26<1:22:31,  1.16s/it]

  9%|▉         | 437/4716 [08:27<1:22:33,  1.16s/it]

  9%|▉         | 438/4716 [08:28<1:22:39,  1.16s/it]

  9%|▉         | 439/4716 [08:29<1:22:40,  1.16s/it]

  9%|▉         | 440/4716 [08:30<1:22:41,  1.16s/it]

  9%|▉         | 441/4716 [08:31<1:22:42,  1.16s/it]

  9%|▉         | 442/4716 [08:33<1:22:40,  1.16s/it]

  9%|▉         | 443/4716 [08:34<1:22:44,  1.16s/it]

  9%|▉         | 444/4716 [08:35<1:22:35,  1.16s/it]

  9%|▉         | 445/4716 [08:36<1:22:26,  1.16s/it]

  9%|▉         | 446/4716 [08:37<1:22:25,  1.16s/it]

  9%|▉         | 447/4716 [08:38<1:22:21,  1.16s/it]

  9%|▉         | 448/4716 [08:40<1:22:20,  1.16s/it]

 10%|▉         | 449/4716 [08:41<1:22:21,  1.16s/it]

 10%|▉         | 450/4716 [08:42<1:22:22,  1.16s/it]

 10%|▉         | 451/4716 [08:43<1:22:27,  1.16s/it]

 10%|▉         | 452/4716 [08:44<1:22:23,  1.16s/it]

 10%|▉         | 453/4716 [08:45<1:22:23,  1.16s/it]

 10%|▉         | 454/4716 [08:47<1:22:24,  1.16s/it]

 10%|▉         | 455/4716 [08:48<1:22:22,  1.16s/it]

 10%|▉         | 456/4716 [08:49<1:22:15,  1.16s/it]

 10%|▉         | 457/4716 [08:50<1:22:14,  1.16s/it]

 10%|▉         | 458/4716 [08:51<1:22:14,  1.16s/it]

 10%|▉         | 459/4716 [08:52<1:22:12,  1.16s/it]

 10%|▉         | 460/4716 [08:53<1:22:16,  1.16s/it]

 10%|▉         | 461/4716 [08:55<1:22:17,  1.16s/it]

 10%|▉         | 462/4716 [08:56<1:22:18,  1.16s/it]

 10%|▉         | 463/4716 [08:57<1:22:16,  1.16s/it]

 10%|▉         | 464/4716 [08:58<1:22:10,  1.16s/it]

 10%|▉         | 465/4716 [08:59<1:22:11,  1.16s/it]

 10%|▉         | 466/4716 [09:00<1:22:07,  1.16s/it]

 10%|▉         | 467/4716 [09:02<1:22:03,  1.16s/it]

 10%|▉         | 468/4716 [09:03<1:22:03,  1.16s/it]

 10%|▉         | 469/4716 [09:04<1:22:00,  1.16s/it]

 10%|▉         | 470/4716 [09:05<1:22:06,  1.16s/it]

 10%|▉         | 471/4716 [09:06<1:22:03,  1.16s/it]

 10%|█         | 472/4716 [09:07<1:22:05,  1.16s/it]

 10%|█         | 473/4716 [09:09<1:21:58,  1.16s/it]

 10%|█         | 474/4716 [09:10<1:22:01,  1.16s/it]

 10%|█         | 475/4716 [09:11<1:21:58,  1.16s/it]

 10%|█         | 476/4716 [09:12<1:21:57,  1.16s/it]

 10%|█         | 477/4716 [09:13<1:21:54,  1.16s/it]

 10%|█         | 478/4716 [09:14<1:21:53,  1.16s/it]

 10%|█         | 479/4716 [09:16<1:21:52,  1.16s/it]

 10%|█         | 480/4716 [09:17<1:21:54,  1.16s/it]

 10%|█         | 481/4716 [09:18<1:21:58,  1.16s/it]

 10%|█         | 482/4716 [09:19<1:21:53,  1.16s/it]

 10%|█         | 483/4716 [09:20<1:22:00,  1.16s/it]

 10%|█         | 484/4716 [09:21<1:22:00,  1.16s/it]

 10%|█         | 485/4716 [09:22<1:21:58,  1.16s/it]

 10%|█         | 486/4716 [09:24<1:21:54,  1.16s/it]

 10%|█         | 487/4716 [09:25<1:21:48,  1.16s/it]

 10%|█         | 488/4716 [09:26<1:21:43,  1.16s/it]

 10%|█         | 489/4716 [09:27<1:21:40,  1.16s/it]

 10%|█         | 490/4716 [09:28<1:21:38,  1.16s/it]

 10%|█         | 491/4716 [09:29<1:21:39,  1.16s/it]

 10%|█         | 492/4716 [09:31<1:21:37,  1.16s/it]

 10%|█         | 493/4716 [09:32<1:21:32,  1.16s/it]

 10%|█         | 494/4716 [09:33<1:21:31,  1.16s/it]

 10%|█         | 495/4716 [09:34<1:21:30,  1.16s/it]

 11%|█         | 496/4716 [09:35<1:21:36,  1.16s/it]

 11%|█         | 497/4716 [09:36<1:21:38,  1.16s/it]

 11%|█         | 498/4716 [09:38<1:21:34,  1.16s/it]

 11%|█         | 499/4716 [09:39<1:21:30,  1.16s/it]

 11%|█         | 500/4716 [09:40<1:21:29,  1.16s/it]

 11%|█         | 501/4716 [09:41<1:21:32,  1.16s/it]

 11%|█         | 502/4716 [09:42<1:21:29,  1.16s/it]

 11%|█         | 503/4716 [09:43<1:21:23,  1.16s/it]

 11%|█         | 504/4716 [09:45<1:21:19,  1.16s/it]

 11%|█         | 505/4716 [09:46<1:21:17,  1.16s/it]

 11%|█         | 506/4716 [09:47<1:21:19,  1.16s/it]

 11%|█         | 507/4716 [09:48<1:21:22,  1.16s/it]

 11%|█         | 508/4716 [09:49<1:21:21,  1.16s/it]

 11%|█         | 509/4716 [09:50<1:21:18,  1.16s/it]

 11%|█         | 510/4716 [09:51<1:21:14,  1.16s/it]

 11%|█         | 511/4716 [09:53<1:21:19,  1.16s/it]

 11%|█         | 512/4716 [09:54<1:21:14,  1.16s/it]

 11%|█         | 513/4716 [09:55<1:21:12,  1.16s/it]

 11%|█         | 514/4716 [09:56<1:21:09,  1.16s/it]

 11%|█         | 515/4716 [09:57<1:21:04,  1.16s/it]

 11%|█         | 516/4716 [09:58<1:21:05,  1.16s/it]

 11%|█         | 517/4716 [10:00<1:21:12,  1.16s/it]

 11%|█         | 518/4716 [10:01<1:21:09,  1.16s/it]

 11%|█         | 519/4716 [10:02<1:21:07,  1.16s/it]

 11%|█         | 520/4716 [10:03<1:21:03,  1.16s/it]

 11%|█         | 521/4716 [10:04<1:21:03,  1.16s/it]

 11%|█         | 522/4716 [10:05<1:21:03,  1.16s/it]

 11%|█         | 523/4716 [10:07<1:20:58,  1.16s/it]

 11%|█         | 524/4716 [10:08<1:20:57,  1.16s/it]

 11%|█         | 525/4716 [10:09<1:20:54,  1.16s/it]

 11%|█         | 526/4716 [10:10<1:20:53,  1.16s/it]

 11%|█         | 527/4716 [10:11<1:20:56,  1.16s/it]

 11%|█         | 528/4716 [10:12<1:20:57,  1.16s/it]

 11%|█         | 529/4716 [10:13<1:20:56,  1.16s/it]

 11%|█         | 530/4716 [10:15<1:20:55,  1.16s/it]

 11%|█▏        | 531/4716 [10:16<1:20:52,  1.16s/it]

 11%|█▏        | 532/4716 [10:17<1:20:55,  1.16s/it]

 11%|█▏        | 533/4716 [10:18<1:20:52,  1.16s/it]

 11%|█▏        | 534/4716 [10:19<1:20:48,  1.16s/it]

 11%|█▏        | 535/4716 [10:20<1:20:43,  1.16s/it]

 11%|█▏        | 536/4716 [10:22<1:20:38,  1.16s/it]

 11%|█▏        | 537/4716 [10:23<1:20:43,  1.16s/it]

 11%|█▏        | 538/4716 [10:24<1:20:46,  1.16s/it]

 11%|█▏        | 539/4716 [10:25<1:20:43,  1.16s/it]

 11%|█▏        | 540/4716 [10:26<1:20:42,  1.16s/it]

 11%|█▏        | 541/4716 [10:27<1:20:49,  1.16s/it]

 11%|█▏        | 542/4716 [10:29<1:20:42,  1.16s/it]

 12%|█▏        | 543/4716 [10:30<1:20:35,  1.16s/it]

 12%|█▏        | 544/4716 [10:31<1:20:38,  1.16s/it]

 12%|█▏        | 545/4716 [10:32<1:20:35,  1.16s/it]

 12%|█▏        | 546/4716 [10:33<1:20:34,  1.16s/it]

 12%|█▏        | 547/4716 [10:34<1:20:30,  1.16s/it]

 12%|█▏        | 548/4716 [10:36<1:20:26,  1.16s/it]

 12%|█▏        | 549/4716 [10:37<1:20:24,  1.16s/it]

 12%|█▏        | 550/4716 [10:38<1:20:23,  1.16s/it]

 12%|█▏        | 551/4716 [10:39<1:20:20,  1.16s/it]

 12%|█▏        | 552/4716 [10:40<1:20:20,  1.16s/it]

 12%|█▏        | 553/4716 [10:41<1:20:23,  1.16s/it]

 12%|█▏        | 554/4716 [10:42<1:20:31,  1.16s/it]

 12%|█▏        | 555/4716 [10:44<1:20:29,  1.16s/it]

 12%|█▏        | 556/4716 [10:45<1:20:31,  1.16s/it]

 12%|█▏        | 557/4716 [10:46<1:20:32,  1.16s/it]

 12%|█▏        | 558/4716 [10:47<1:20:24,  1.16s/it]

 12%|█▏        | 559/4716 [10:48<1:20:23,  1.16s/it]

 12%|█▏        | 560/4716 [10:49<1:20:18,  1.16s/it]

 12%|█▏        | 561/4716 [10:51<1:20:14,  1.16s/it]

 12%|█▏        | 562/4716 [10:52<1:20:14,  1.16s/it]

 12%|█▏        | 563/4716 [10:53<1:20:16,  1.16s/it]

 12%|█▏        | 564/4716 [10:54<1:20:17,  1.16s/it]

 12%|█▏        | 565/4716 [10:55<1:20:14,  1.16s/it]

 12%|█▏        | 566/4716 [10:56<1:20:09,  1.16s/it]

 12%|█▏        | 567/4716 [10:58<1:20:12,  1.16s/it]

 12%|█▏        | 568/4716 [10:59<1:20:16,  1.16s/it]

 12%|█▏        | 569/4716 [11:00<1:20:10,  1.16s/it]

 12%|█▏        | 570/4716 [11:01<1:20:06,  1.16s/it]

 12%|█▏        | 571/4716 [11:02<1:20:03,  1.16s/it]

 12%|█▏        | 572/4716 [11:03<1:20:02,  1.16s/it]

 12%|█▏        | 573/4716 [11:05<1:20:00,  1.16s/it]

 12%|█▏        | 574/4716 [11:06<1:20:01,  1.16s/it]

 12%|█▏        | 575/4716 [11:07<1:20:03,  1.16s/it]

 12%|█▏        | 576/4716 [11:08<1:20:04,  1.16s/it]

 12%|█▏        | 577/4716 [11:09<1:20:02,  1.16s/it]

 12%|█▏        | 578/4716 [11:10<1:20:03,  1.16s/it]

 12%|█▏        | 579/4716 [11:11<1:20:06,  1.16s/it]

 12%|█▏        | 580/4716 [11:13<1:20:07,  1.16s/it]

 12%|█▏        | 581/4716 [11:14<1:20:04,  1.16s/it]

 12%|█▏        | 582/4716 [11:15<1:20:03,  1.16s/it]

 12%|█▏        | 583/4716 [11:16<1:19:54,  1.16s/it]

 12%|█▏        | 584/4716 [11:17<1:19:53,  1.16s/it]

 12%|█▏        | 585/4716 [11:18<1:19:50,  1.16s/it]

 12%|█▏        | 586/4716 [11:20<1:19:51,  1.16s/it]

 12%|█▏        | 587/4716 [11:21<1:19:51,  1.16s/it]

 12%|█▏        | 588/4716 [11:22<1:19:48,  1.16s/it]

 12%|█▏        | 589/4716 [11:23<1:19:44,  1.16s/it]

 13%|█▎        | 590/4716 [11:24<1:19:47,  1.16s/it]

 13%|█▎        | 591/4716 [11:25<1:19:52,  1.16s/it]

 13%|█▎        | 592/4716 [11:27<1:19:48,  1.16s/it]

 13%|█▎        | 593/4716 [11:28<1:19:44,  1.16s/it]

 13%|█▎        | 594/4716 [11:29<1:19:42,  1.16s/it]

 13%|█▎        | 595/4716 [11:30<1:19:38,  1.16s/it]

 13%|█▎        | 596/4716 [11:31<1:19:38,  1.16s/it]

 13%|█▎        | 597/4716 [11:32<1:19:41,  1.16s/it]

 13%|█▎        | 598/4716 [11:34<1:19:41,  1.16s/it]

 13%|█▎        | 599/4716 [11:35<1:19:41,  1.16s/it]

 13%|█▎        | 600/4716 [11:36<1:19:40,  1.16s/it]

 13%|█▎        | 601/4716 [11:37<1:19:37,  1.16s/it]

 13%|█▎        | 602/4716 [11:38<1:19:35,  1.16s/it]

 13%|█▎        | 603/4716 [11:39<1:19:34,  1.16s/it]

 13%|█▎        | 604/4716 [11:40<1:19:33,  1.16s/it]

 13%|█▎        | 605/4716 [11:42<1:19:31,  1.16s/it]

 13%|█▎        | 606/4716 [11:43<1:19:33,  1.16s/it]

 13%|█▎        | 607/4716 [11:44<1:19:33,  1.16s/it]

 13%|█▎        | 608/4716 [11:45<1:19:24,  1.16s/it]

 13%|█▎        | 609/4716 [11:46<1:19:18,  1.16s/it]

 13%|█▎        | 610/4716 [11:47<1:19:17,  1.16s/it]

 13%|█▎        | 611/4716 [11:49<1:19:16,  1.16s/it]

 13%|█▎        | 612/4716 [11:50<1:19:18,  1.16s/it]

 13%|█▎        | 613/4716 [11:51<1:19:19,  1.16s/it]

 13%|█▎        | 614/4716 [11:52<1:19:20,  1.16s/it]

 13%|█▎        | 615/4716 [11:53<1:19:18,  1.16s/it]

 13%|█▎        | 616/4716 [11:54<1:19:14,  1.16s/it]

 13%|█▎        | 617/4716 [11:56<1:19:18,  1.16s/it]

 13%|█▎        | 618/4716 [11:57<1:19:27,  1.16s/it]

 13%|█▎        | 619/4716 [11:58<1:19:21,  1.16s/it]

 13%|█▎        | 620/4716 [11:59<1:19:20,  1.16s/it]

 13%|█▎        | 621/4716 [12:00<1:19:13,  1.16s/it]

 13%|█▎        | 622/4716 [12:01<1:19:06,  1.16s/it]

 13%|█▎        | 623/4716 [12:03<1:19:05,  1.16s/it]

 13%|█▎        | 624/4716 [12:04<1:19:05,  1.16s/it]

 13%|█▎        | 625/4716 [12:05<1:19:04,  1.16s/it]

logging
logging the anndata

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 13%|█▎        | 626/4716 [12:07<1:42:55,  1.51s/it]

 13%|█▎        | 627/4716 [12:08<1:35:36,  1.40s/it]

 13%|█▎        | 628/4716 [12:10<1:30:36,  1.33s/it]

 13%|█▎        | 629/4716 [12:11<1:26:58,  1.28s/it]

 13%|█▎        | 630/4716 [12:12<1:24:28,  1.24s/it]

 13%|█▎        | 631/4716 [12:13<1:22:38,  1.21s/it]

 13%|█▎        | 632/4716 [12:14<1:21:21,  1.20s/it]

 13%|█▎        | 633/4716 [12:15<1:20:31,  1.18s/it]

 13%|█▎        | 634/4716 [12:16<1:19:59,  1.18s/it]

 13%|█▎        | 635/4716 [12:18<1:19:30,  1.17s/it]

 13%|█▎        | 636/4716 [12:19<1:19:14,  1.17s/it]

 14%|█▎        | 637/4716 [12:20<1:18:57,  1.16s/it]

 14%|█▎        | 638/4716 [12:21<1:18:52,  1.16s/it]

 14%|█▎        | 639/4716 [12:22<1:18:41,  1.16s/it]

 14%|█▎        | 640/4716 [12:23<1:18:32,  1.16s/it]

 14%|█▎        | 641/4716 [12:25<1:18:27,  1.16s/it]

 14%|█▎        | 642/4716 [12:26<1:18:28,  1.16s/it]

 14%|█▎        | 643/4716 [12:27<1:18:30,  1.16s/it]

 14%|█▎        | 644/4716 [12:28<1:18:26,  1.16s/it]

 14%|█▎        | 645/4716 [12:29<1:18:20,  1.15s/it]

 14%|█▎        | 646/4716 [12:30<1:18:19,  1.15s/it]

 14%|█▎        | 647/4716 [12:31<1:18:16,  1.15s/it]

 14%|█▎        | 648/4716 [12:33<1:18:13,  1.15s/it]

 14%|█▍        | 649/4716 [12:34<1:18:13,  1.15s/it]

 14%|█▍        | 650/4716 [12:35<1:18:16,  1.16s/it]

 14%|█▍        | 651/4716 [12:36<1:18:16,  1.16s/it]

 14%|█▍        | 652/4716 [12:37<1:18:19,  1.16s/it]

 14%|█▍        | 653/4716 [12:38<1:18:13,  1.16s/it]

 14%|█▍        | 654/4716 [12:40<1:18:13,  1.16s/it]

 14%|█▍        | 655/4716 [12:41<1:18:15,  1.16s/it]

 14%|█▍        | 656/4716 [12:42<1:18:18,  1.16s/it]

 14%|█▍        | 657/4716 [12:43<1:18:21,  1.16s/it]

 14%|█▍        | 658/4716 [12:44<1:18:19,  1.16s/it]

 14%|█▍        | 659/4716 [12:45<1:18:12,  1.16s/it]

 14%|█▍        | 660/4716 [12:46<1:18:09,  1.16s/it]

 14%|█▍        | 661/4716 [12:48<1:18:06,  1.16s/it]

 14%|█▍        | 662/4716 [12:49<1:18:04,  1.16s/it]

 14%|█▍        | 663/4716 [12:50<1:18:02,  1.16s/it]

 14%|█▍        | 664/4716 [12:51<1:17:57,  1.15s/it]

 14%|█▍        | 665/4716 [12:52<1:17:58,  1.15s/it]

 14%|█▍        | 666/4716 [12:53<1:17:57,  1.16s/it]

 14%|█▍        | 667/4716 [12:55<1:17:49,  1.15s/it]

 14%|█▍        | 668/4716 [12:56<1:17:50,  1.15s/it]

 14%|█▍        | 669/4716 [12:57<1:17:49,  1.15s/it]

 14%|█▍        | 670/4716 [12:58<1:17:53,  1.16s/it]

 14%|█▍        | 671/4716 [12:59<1:17:51,  1.15s/it]

 14%|█▍        | 672/4716 [13:00<1:17:51,  1.16s/it]

 14%|█▍        | 673/4716 [13:01<1:17:45,  1.15s/it]

 14%|█▍        | 674/4716 [13:03<1:17:44,  1.15s/it]

 14%|█▍        | 675/4716 [13:04<1:17:42,  1.15s/it]

 14%|█▍        | 676/4716 [13:05<1:17:39,  1.15s/it]

 14%|█▍        | 677/4716 [13:06<1:17:43,  1.15s/it]

 14%|█▍        | 678/4716 [13:07<1:17:43,  1.15s/it]

 14%|█▍        | 679/4716 [13:08<1:17:42,  1.16s/it]

 14%|█▍        | 680/4716 [13:10<1:17:45,  1.16s/it]

 14%|█▍        | 681/4716 [13:11<1:17:44,  1.16s/it]

 14%|█▍        | 682/4716 [13:12<1:17:41,  1.16s/it]

 14%|█▍        | 683/4716 [13:13<1:17:37,  1.15s/it]

 15%|█▍        | 684/4716 [13:14<1:17:38,  1.16s/it]

 15%|█▍        | 685/4716 [13:15<1:17:33,  1.15s/it]

 15%|█▍        | 686/4716 [13:16<1:17:36,  1.16s/it]

 15%|█▍        | 687/4716 [13:18<1:17:37,  1.16s/it]

 15%|█▍        | 688/4716 [13:19<1:17:33,  1.16s/it]

 15%|█▍        | 689/4716 [13:20<1:17:36,  1.16s/it]

 15%|█▍        | 690/4716 [13:21<1:17:36,  1.16s/it]

 15%|█▍        | 691/4716 [13:22<1:17:33,  1.16s/it]

 15%|█▍        | 692/4716 [13:23<1:17:30,  1.16s/it]

 15%|█▍        | 693/4716 [13:25<1:17:29,  1.16s/it]

 15%|█▍        | 694/4716 [13:26<1:17:27,  1.16s/it]

 15%|█▍        | 695/4716 [13:27<1:17:30,  1.16s/it]

 15%|█▍        | 696/4716 [13:28<1:17:29,  1.16s/it]

 15%|█▍        | 697/4716 [13:29<1:17:27,  1.16s/it]

 15%|█▍        | 698/4716 [13:30<1:17:24,  1.16s/it]

 15%|█▍        | 699/4716 [13:32<1:17:21,  1.16s/it]

 15%|█▍        | 700/4716 [13:33<1:17:21,  1.16s/it]

 15%|█▍        | 701/4716 [13:34<1:17:17,  1.15s/it]

 15%|█▍        | 702/4716 [13:35<1:17:16,  1.16s/it]

 15%|█▍        | 703/4716 [13:36<1:17:19,  1.16s/it]

 15%|█▍        | 704/4716 [13:37<1:17:19,  1.16s/it]

 15%|█▍        | 705/4716 [13:38<1:17:15,  1.16s/it]

 15%|█▍        | 706/4716 [13:40<1:17:14,  1.16s/it]

 15%|█▍        | 707/4716 [13:41<1:17:12,  1.16s/it]

 15%|█▌        | 708/4716 [13:42<1:17:08,  1.15s/it]

 15%|█▌        | 709/4716 [13:43<1:17:11,  1.16s/it]

 15%|█▌        | 710/4716 [13:44<1:17:08,  1.16s/it]

 15%|█▌        | 711/4716 [13:45<1:17:17,  1.16s/it]

 15%|█▌        | 712/4716 [13:47<1:17:18,  1.16s/it]

 15%|█▌        | 713/4716 [13:48<1:17:16,  1.16s/it]

 15%|█▌        | 714/4716 [13:49<1:17:13,  1.16s/it]

 15%|█▌        | 715/4716 [13:50<1:17:11,  1.16s/it]

 15%|█▌        | 716/4716 [13:51<1:17:10,  1.16s/it]

 15%|█▌        | 717/4716 [13:52<1:17:02,  1.16s/it]

 15%|█▌        | 718/4716 [13:53<1:17:07,  1.16s/it]

 15%|█▌        | 719/4716 [13:55<1:16:59,  1.16s/it]

 15%|█▌        | 720/4716 [13:56<1:16:59,  1.16s/it]

 15%|█▌        | 721/4716 [13:57<1:16:54,  1.16s/it]

 15%|█▌        | 722/4716 [13:58<1:16:50,  1.15s/it]

 15%|█▌        | 723/4716 [13:59<1:16:49,  1.15s/it]

 15%|█▌        | 724/4716 [14:00<1:16:53,  1.16s/it]

 15%|█▌        | 725/4716 [14:02<1:16:53,  1.16s/it]

 15%|█▌        | 726/4716 [14:03<1:16:50,  1.16s/it]

 15%|█▌        | 727/4716 [14:04<1:16:50,  1.16s/it]

 15%|█▌        | 728/4716 [14:05<1:16:45,  1.15s/it]

 15%|█▌        | 729/4716 [14:06<1:16:40,  1.15s/it]

 15%|█▌        | 730/4716 [14:07<1:16:37,  1.15s/it]

 16%|█▌        | 731/4716 [14:09<1:16:40,  1.15s/it]

 16%|█▌        | 732/4716 [14:10<1:16:43,  1.16s/it]

 16%|█▌        | 733/4716 [14:11<1:16:45,  1.16s/it]

 16%|█▌        | 734/4716 [14:12<1:16:41,  1.16s/it]

 16%|█▌        | 735/4716 [14:13<1:16:42,  1.16s/it]

 16%|█▌        | 736/4716 [14:14<1:16:37,  1.16s/it]

 16%|█▌        | 737/4716 [14:15<1:16:33,  1.15s/it]

 16%|█▌        | 738/4716 [14:17<1:16:29,  1.15s/it]

 16%|█▌        | 739/4716 [14:18<1:16:32,  1.15s/it]

 16%|█▌        | 740/4716 [14:19<1:16:32,  1.16s/it]

 16%|█▌        | 741/4716 [14:20<1:16:32,  1.16s/it]

 16%|█▌        | 742/4716 [14:21<1:16:31,  1.16s/it]

 16%|█▌        | 743/4716 [14:22<1:16:33,  1.16s/it]

 16%|█▌        | 744/4716 [14:24<1:16:34,  1.16s/it]

 16%|█▌        | 745/4716 [14:25<1:16:35,  1.16s/it]

 16%|█▌        | 746/4716 [14:26<1:16:29,  1.16s/it]

 16%|█▌        | 747/4716 [14:27<1:16:26,  1.16s/it]

 16%|█▌        | 748/4716 [14:28<1:16:24,  1.16s/it]

 16%|█▌        | 749/4716 [14:29<1:16:24,  1.16s/it]

 16%|█▌        | 750/4716 [14:30<1:16:27,  1.16s/it]

 16%|█▌        | 751/4716 [14:32<1:16:27,  1.16s/it]

 16%|█▌        | 752/4716 [14:33<1:16:28,  1.16s/it]

 16%|█▌        | 753/4716 [14:34<1:16:23,  1.16s/it]

 16%|█▌        | 754/4716 [14:35<1:16:23,  1.16s/it]

 16%|█▌        | 755/4716 [14:36<1:16:22,  1.16s/it]

 16%|█▌        | 756/4716 [14:37<1:16:15,  1.16s/it]

 16%|█▌        | 757/4716 [14:39<1:16:16,  1.16s/it]

 16%|█▌        | 758/4716 [14:40<1:16:14,  1.16s/it]

 16%|█▌        | 759/4716 [14:41<1:16:15,  1.16s/it]

 16%|█▌        | 760/4716 [14:42<1:16:15,  1.16s/it]

 16%|█▌        | 761/4716 [14:43<1:16:11,  1.16s/it]

 16%|█▌        | 762/4716 [14:44<1:16:10,  1.16s/it]

 16%|█▌        | 763/4716 [14:45<1:16:03,  1.15s/it]

 16%|█▌        | 764/4716 [14:47<1:16:02,  1.15s/it]

 16%|█▌        | 765/4716 [14:48<1:16:03,  1.16s/it]

 16%|█▌        | 766/4716 [14:49<1:16:07,  1.16s/it]

 16%|█▋        | 767/4716 [14:50<1:16:10,  1.16s/it]

 16%|█▋        | 768/4716 [14:51<1:16:06,  1.16s/it]

 16%|█▋        | 769/4716 [14:52<1:16:09,  1.16s/it]

 16%|█▋        | 770/4716 [14:54<1:16:09,  1.16s/it]

 16%|█▋        | 771/4716 [14:55<1:16:05,  1.16s/it]

 16%|█▋        | 772/4716 [14:56<1:16:02,  1.16s/it]

 16%|█▋        | 773/4716 [14:57<1:15:59,  1.16s/it]

 16%|█▋        | 774/4716 [14:58<1:15:58,  1.16s/it]

 16%|█▋        | 775/4716 [14:59<1:15:58,  1.16s/it]

 16%|█▋        | 776/4716 [15:01<1:15:55,  1.16s/it]

 16%|█▋        | 777/4716 [15:02<1:15:48,  1.15s/it]

 16%|█▋        | 778/4716 [15:03<1:15:43,  1.15s/it]

 17%|█▋        | 779/4716 [15:04<1:15:44,  1.15s/it]

 17%|█▋        | 780/4716 [15:05<1:15:48,  1.16s/it]

 17%|█▋        | 781/4716 [15:06<1:15:46,  1.16s/it]

 17%|█▋        | 782/4716 [15:07<1:15:46,  1.16s/it]

 17%|█▋        | 783/4716 [15:09<1:15:44,  1.16s/it]

 17%|█▋        | 784/4716 [15:10<1:15:40,  1.15s/it]

 17%|█▋        | 785/4716 [15:11<1:15:39,  1.15s/it]

 17%|█▋        | 786/4716 [15:12<1:15:38,  1.15s/it]

 17%|█▋        | 787/4716 [15:13<1:15:39,  1.16s/it]

 17%|█▋        | 788/4716 [15:14<1:15:41,  1.16s/it]

 17%|█▋        | 789/4716 [15:16<1:15:40,  1.16s/it]

 17%|█▋        | 790/4716 [15:17<1:15:37,  1.16s/it]

 17%|█▋        | 791/4716 [15:18<1:15:36,  1.16s/it]

 17%|█▋        | 792/4716 [15:19<1:15:31,  1.15s/it]

 17%|█▋        | 793/4716 [15:20<1:15:29,  1.15s/it]

 17%|█▋        | 794/4716 [15:21<1:15:27,  1.15s/it]

 17%|█▋        | 795/4716 [15:22<1:15:26,  1.15s/it]

 17%|█▋        | 796/4716 [15:24<1:15:24,  1.15s/it]

 17%|█▋        | 797/4716 [15:25<1:15:26,  1.15s/it]

 17%|█▋        | 798/4716 [15:26<1:15:27,  1.16s/it]

 17%|█▋        | 799/4716 [15:27<1:15:25,  1.16s/it]

 17%|█▋        | 800/4716 [15:28<1:15:26,  1.16s/it]

 17%|█▋        | 801/4716 [15:29<1:15:22,  1.16s/it]

 17%|█▋        | 802/4716 [15:31<1:15:21,  1.16s/it]

 17%|█▋        | 803/4716 [15:32<1:15:20,  1.16s/it]

 17%|█▋        | 804/4716 [15:33<1:15:20,  1.16s/it]

 17%|█▋        | 805/4716 [15:34<1:15:19,  1.16s/it]

 17%|█▋        | 806/4716 [15:35<1:15:18,  1.16s/it]

 17%|█▋        | 807/4716 [15:36<1:15:14,  1.16s/it]

 17%|█▋        | 808/4716 [15:37<1:15:17,  1.16s/it]

 17%|█▋        | 809/4716 [15:39<1:15:12,  1.15s/it]

 17%|█▋        | 810/4716 [15:40<1:15:15,  1.16s/it]

 17%|█▋        | 811/4716 [15:41<1:15:12,  1.16s/it]

 17%|█▋        | 812/4716 [15:42<1:15:11,  1.16s/it]

 17%|█▋        | 813/4716 [15:43<1:15:11,  1.16s/it]

 17%|█▋        | 814/4716 [15:44<1:15:10,  1.16s/it]

 17%|█▋        | 815/4716 [15:46<1:15:13,  1.16s/it]

 17%|█▋        | 816/4716 [15:47<1:15:09,  1.16s/it]

 17%|█▋        | 817/4716 [15:48<1:15:11,  1.16s/it]

 17%|█▋        | 818/4716 [15:49<1:15:04,  1.16s/it]

 17%|█▋        | 819/4716 [15:50<1:14:59,  1.15s/it]

 17%|█▋        | 820/4716 [15:51<1:14:58,  1.15s/it]

 17%|█▋        | 821/4716 [15:53<1:15:00,  1.16s/it]

 17%|█▋        | 822/4716 [15:54<1:15:02,  1.16s/it]

 17%|█▋        | 823/4716 [15:55<1:15:01,  1.16s/it]

 17%|█▋        | 824/4716 [15:56<1:15:00,  1.16s/it]

 17%|█▋        | 825/4716 [15:57<1:14:55,  1.16s/it]

 18%|█▊        | 826/4716 [15:58<1:14:52,  1.15s/it]

 18%|█▊        | 827/4716 [15:59<1:14:52,  1.16s/it]

 18%|█▊        | 828/4716 [16:01<1:14:54,  1.16s/it]

 18%|█▊        | 829/4716 [16:02<1:14:58,  1.16s/it]

 18%|█▊        | 830/4716 [16:03<1:14:56,  1.16s/it]

 18%|█▊        | 831/4716 [16:04<1:15:01,  1.16s/it]

 18%|█▊        | 832/4716 [16:05<1:15:01,  1.16s/it]

 18%|█▊        | 833/4716 [16:06<1:14:57,  1.16s/it]

 18%|█▊        | 834/4716 [16:08<1:14:56,  1.16s/it]

 18%|█▊        | 835/4716 [16:09<1:14:54,  1.16s/it]

 18%|█▊        | 836/4716 [16:10<1:14:49,  1.16s/it]

 18%|█▊        | 837/4716 [16:11<1:14:48,  1.16s/it]

 18%|█▊        | 838/4716 [16:12<1:14:44,  1.16s/it]

 18%|█▊        | 839/4716 [16:13<1:14:44,  1.16s/it]

 18%|█▊        | 840/4716 [16:14<1:14:37,  1.16s/it]

 18%|█▊        | 841/4716 [16:16<1:14:34,  1.15s/it]

 18%|█▊        | 842/4716 [16:17<1:14:40,  1.16s/it]

 18%|█▊        | 843/4716 [16:18<1:14:39,  1.16s/it]

 18%|█▊        | 844/4716 [16:19<1:14:39,  1.16s/it]

 18%|█▊        | 845/4716 [16:20<1:14:40,  1.16s/it]

 18%|█▊        | 846/4716 [16:21<1:14:36,  1.16s/it]

 18%|█▊        | 847/4716 [16:23<1:14:35,  1.16s/it]

 18%|█▊        | 848/4716 [16:24<1:14:31,  1.16s/it]

 18%|█▊        | 849/4716 [16:25<1:14:30,  1.16s/it]

 18%|█▊        | 850/4716 [16:26<1:14:26,  1.16s/it]

 18%|█▊        | 851/4716 [16:27<1:14:29,  1.16s/it]

 18%|█▊        | 852/4716 [16:28<1:14:28,  1.16s/it]

 18%|█▊        | 853/4716 [16:30<1:14:25,  1.16s/it]

 18%|█▊        | 854/4716 [16:31<1:14:22,  1.16s/it]

 18%|█▊        | 855/4716 [16:32<1:14:21,  1.16s/it]

 18%|█▊        | 856/4716 [16:33<1:14:22,  1.16s/it]

 18%|█▊        | 857/4716 [16:34<1:14:19,  1.16s/it]

 18%|█▊        | 858/4716 [16:35<1:14:20,  1.16s/it]

 18%|█▊        | 859/4716 [16:36<1:14:19,  1.16s/it]

 18%|█▊        | 860/4716 [16:38<1:14:17,  1.16s/it]

 18%|█▊        | 861/4716 [16:39<1:14:15,  1.16s/it]

 18%|█▊        | 862/4716 [16:40<1:14:13,  1.16s/it]

 18%|█▊        | 863/4716 [16:41<1:14:17,  1.16s/it]

 18%|█▊        | 864/4716 [16:42<1:14:18,  1.16s/it]

 18%|█▊        | 865/4716 [16:43<1:14:14,  1.16s/it]

 18%|█▊        | 866/4716 [16:45<1:14:14,  1.16s/it]

 18%|█▊        | 867/4716 [16:46<1:14:09,  1.16s/it]

 18%|█▊        | 868/4716 [16:47<1:14:10,  1.16s/it]

 18%|█▊        | 869/4716 [16:48<1:14:12,  1.16s/it]

 18%|█▊        | 870/4716 [16:49<1:14:08,  1.16s/it]

 18%|█▊        | 871/4716 [16:50<1:14:05,  1.16s/it]

 18%|█▊        | 872/4716 [16:52<1:14:13,  1.16s/it]

 19%|█▊        | 873/4716 [16:53<1:14:06,  1.16s/it]

 19%|█▊        | 874/4716 [16:54<1:14:08,  1.16s/it]

 19%|█▊        | 875/4716 [16:55<1:14:04,  1.16s/it]

 19%|█▊        | 876/4716 [16:56<1:14:02,  1.16s/it]

 19%|█▊        | 877/4716 [16:57<1:14:00,  1.16s/it]

 19%|█▊        | 878/4716 [16:58<1:14:00,  1.16s/it]

 19%|█▊        | 879/4716 [17:00<1:14:00,  1.16s/it]

 19%|█▊        | 880/4716 [17:01<1:14:03,  1.16s/it]

 19%|█▊        | 881/4716 [17:02<1:13:57,  1.16s/it]

 19%|█▊        | 882/4716 [17:03<1:13:53,  1.16s/it]

 19%|█▊        | 883/4716 [17:04<1:13:51,  1.16s/it]

 19%|█▊        | 884/4716 [17:05<1:13:50,  1.16s/it]

 19%|█▉        | 885/4716 [17:07<1:13:51,  1.16s/it]

 19%|█▉        | 886/4716 [17:08<1:13:51,  1.16s/it]

 19%|█▉        | 887/4716 [17:09<1:13:52,  1.16s/it]

 19%|█▉        | 888/4716 [17:10<1:14:04,  1.16s/it]

 19%|█▉        | 889/4716 [17:11<1:13:56,  1.16s/it]

 19%|█▉        | 890/4716 [17:12<1:13:54,  1.16s/it]

 19%|█▉        | 891/4716 [17:14<1:13:52,  1.16s/it]

 19%|█▉        | 892/4716 [17:15<1:13:48,  1.16s/it]

 19%|█▉        | 893/4716 [17:16<1:13:43,  1.16s/it]

 19%|█▉        | 894/4716 [17:17<1:13:44,  1.16s/it]

 19%|█▉        | 895/4716 [17:18<1:13:41,  1.16s/it]

 19%|█▉        | 896/4716 [17:19<1:13:41,  1.16s/it]

 19%|█▉        | 897/4716 [17:20<1:13:35,  1.16s/it]

 19%|█▉        | 898/4716 [17:22<1:13:36,  1.16s/it]

 19%|█▉        | 899/4716 [17:23<1:13:36,  1.16s/it]

 19%|█▉        | 900/4716 [17:24<1:13:36,  1.16s/it]

 19%|█▉        | 901/4716 [17:25<1:13:34,  1.16s/it]

 19%|█▉        | 902/4716 [17:26<1:13:36,  1.16s/it]

 19%|█▉        | 903/4716 [17:27<1:13:37,  1.16s/it]

 19%|█▉        | 904/4716 [17:29<1:13:36,  1.16s/it]

 19%|█▉        | 905/4716 [17:30<1:13:35,  1.16s/it]

 19%|█▉        | 906/4716 [17:31<1:13:30,  1.16s/it]

 19%|█▉        | 907/4716 [17:32<1:13:29,  1.16s/it]

 19%|█▉        | 908/4716 [17:33<1:13:24,  1.16s/it]

 19%|█▉        | 909/4716 [17:34<1:13:21,  1.16s/it]

 19%|█▉        | 910/4716 [17:35<1:13:23,  1.16s/it]

 19%|█▉        | 911/4716 [17:37<1:13:23,  1.16s/it]

 19%|█▉        | 912/4716 [17:38<1:13:23,  1.16s/it]

 19%|█▉        | 913/4716 [17:39<1:13:21,  1.16s/it]

 19%|█▉        | 914/4716 [17:40<1:13:22,  1.16s/it]

 19%|█▉        | 915/4716 [17:41<1:13:19,  1.16s/it]

 19%|█▉        | 916/4716 [17:42<1:13:19,  1.16s/it]

 19%|█▉        | 917/4716 [17:44<1:13:14,  1.16s/it]

 19%|█▉        | 918/4716 [17:45<1:13:18,  1.16s/it]

 19%|█▉        | 919/4716 [17:46<1:13:20,  1.16s/it]

 20%|█▉        | 920/4716 [17:47<1:13:18,  1.16s/it]

 20%|█▉        | 921/4716 [17:48<1:13:18,  1.16s/it]

 20%|█▉        | 922/4716 [17:49<1:13:17,  1.16s/it]

 20%|█▉        | 923/4716 [17:51<1:13:18,  1.16s/it]

 20%|█▉        | 924/4716 [17:52<1:13:17,  1.16s/it]

 20%|█▉        | 925/4716 [17:53<1:13:12,  1.16s/it]

 20%|█▉        | 926/4716 [17:54<1:13:12,  1.16s/it]

 20%|█▉        | 927/4716 [17:55<1:13:10,  1.16s/it]

 20%|█▉        | 928/4716 [17:56<1:13:08,  1.16s/it]

 20%|█▉        | 929/4716 [17:58<1:13:05,  1.16s/it]

 20%|█▉        | 930/4716 [17:59<1:13:08,  1.16s/it]

 20%|█▉        | 931/4716 [18:00<1:13:09,  1.16s/it]

 20%|█▉        | 932/4716 [18:01<1:13:12,  1.16s/it]

 20%|█▉        | 933/4716 [18:02<1:13:06,  1.16s/it]

 20%|█▉        | 934/4716 [18:03<1:13:08,  1.16s/it]

 20%|█▉        | 935/4716 [18:04<1:13:06,  1.16s/it]

 20%|█▉        | 936/4716 [18:06<1:13:04,  1.16s/it]

 20%|█▉        | 937/4716 [18:07<1:12:56,  1.16s/it]

 20%|█▉        | 938/4716 [18:08<1:12:52,  1.16s/it]

 20%|█▉        | 939/4716 [18:09<1:12:52,  1.16s/it]

 20%|█▉        | 940/4716 [18:10<1:12:49,  1.16s/it]

 20%|█▉        | 941/4716 [18:11<1:12:50,  1.16s/it]

 20%|█▉        | 942/4716 [18:13<1:12:49,  1.16s/it]

 20%|█▉        | 943/4716 [18:14<1:12:54,  1.16s/it]

 20%|██        | 944/4716 [18:15<1:12:52,  1.16s/it]

 20%|██        | 945/4716 [18:16<1:12:51,  1.16s/it]

 20%|██        | 946/4716 [18:17<1:12:49,  1.16s/it]

 20%|██        | 947/4716 [18:18<1:12:50,  1.16s/it]

 20%|██        | 948/4716 [18:20<1:12:48,  1.16s/it]

 20%|██        | 949/4716 [18:21<1:12:43,  1.16s/it]

 20%|██        | 950/4716 [18:22<1:12:43,  1.16s/it]

 20%|██        | 951/4716 [18:23<1:12:39,  1.16s/it]

 20%|██        | 952/4716 [18:24<1:12:39,  1.16s/it]

 20%|██        | 953/4716 [18:25<1:12:34,  1.16s/it]

 20%|██        | 954/4716 [18:26<1:12:37,  1.16s/it]

 20%|██        | 955/4716 [18:28<1:12:39,  1.16s/it]

 20%|██        | 956/4716 [18:29<1:12:37,  1.16s/it]

 20%|██        | 957/4716 [18:30<1:12:34,  1.16s/it]

 20%|██        | 958/4716 [18:31<1:12:31,  1.16s/it]

 20%|██        | 959/4716 [18:32<1:12:30,  1.16s/it]

 20%|██        | 960/4716 [18:33<1:12:23,  1.16s/it]

 20%|██        | 961/4716 [18:35<1:12:24,  1.16s/it]

 20%|██        | 962/4716 [18:36<1:12:26,  1.16s/it]

 20%|██        | 963/4716 [18:37<1:12:26,  1.16s/it]

 20%|██        | 964/4716 [18:38<1:12:27,  1.16s/it]

 20%|██        | 965/4716 [18:39<1:12:22,  1.16s/it]

 20%|██        | 966/4716 [18:40<1:12:24,  1.16s/it]

 21%|██        | 967/4716 [18:42<1:12:23,  1.16s/it]

 21%|██        | 968/4716 [18:43<1:12:20,  1.16s/it]

 21%|██        | 969/4716 [18:44<1:12:17,  1.16s/it]

 21%|██        | 970/4716 [18:45<1:12:13,  1.16s/it]

 21%|██        | 971/4716 [18:46<1:12:13,  1.16s/it]

 21%|██        | 972/4716 [18:47<1:12:15,  1.16s/it]

 21%|██        | 973/4716 [18:48<1:12:15,  1.16s/it]

 21%|██        | 974/4716 [18:50<1:12:16,  1.16s/it]

 21%|██        | 975/4716 [18:51<1:12:11,  1.16s/it]

 21%|██        | 976/4716 [18:52<1:12:12,  1.16s/it]

 21%|██        | 977/4716 [18:53<1:12:08,  1.16s/it]

 21%|██        | 978/4716 [18:54<1:12:09,  1.16s/it]

 21%|██        | 979/4716 [18:55<1:12:06,  1.16s/it]

 21%|██        | 980/4716 [18:57<1:12:01,  1.16s/it]

 21%|██        | 981/4716 [18:58<1:12:04,  1.16s/it]

 21%|██        | 982/4716 [18:59<1:12:05,  1.16s/it]

 21%|██        | 983/4716 [19:00<1:12:08,  1.16s/it]

 21%|██        | 984/4716 [19:01<1:12:05,  1.16s/it]

 21%|██        | 985/4716 [19:02<1:12:08,  1.16s/it]

 21%|██        | 986/4716 [19:04<1:12:08,  1.16s/it]

 21%|██        | 987/4716 [19:05<1:12:12,  1.16s/it]

 21%|██        | 988/4716 [19:06<1:12:05,  1.16s/it]

 21%|██        | 989/4716 [19:07<1:12:04,  1.16s/it]

 21%|██        | 990/4716 [19:08<1:11:59,  1.16s/it]

 21%|██        | 991/4716 [19:09<1:11:54,  1.16s/it]

 21%|██        | 992/4716 [19:10<1:11:53,  1.16s/it]

 21%|██        | 993/4716 [19:12<1:11:54,  1.16s/it]

 21%|██        | 994/4716 [19:13<1:11:53,  1.16s/it]

 21%|██        | 995/4716 [19:14<1:11:52,  1.16s/it]

 21%|██        | 996/4716 [19:15<1:11:51,  1.16s/it]

 21%|██        | 997/4716 [19:16<1:11:53,  1.16s/it]

 21%|██        | 998/4716 [19:17<1:11:49,  1.16s/it]

 21%|██        | 999/4716 [19:19<1:11:46,  1.16s/it]

 21%|██        | 1000/4716 [19:20<1:11:39,  1.16s/it]

 21%|██        | 1001/4716 [19:21<1:11:42,  1.16s/it]

 21%|██        | 1002/4716 [19:22<1:11:44,  1.16s/it]

 21%|██▏       | 1003/4716 [19:23<1:11:46,  1.16s/it]

 21%|██▏       | 1004/4716 [19:24<1:11:47,  1.16s/it]

 21%|██▏       | 1005/4716 [19:26<1:11:47,  1.16s/it]

 21%|██▏       | 1006/4716 [19:27<1:11:42,  1.16s/it]

 21%|██▏       | 1007/4716 [19:28<1:11:44,  1.16s/it]

 21%|██▏       | 1008/4716 [19:29<1:11:40,  1.16s/it]

 21%|██▏       | 1009/4716 [19:30<1:11:39,  1.16s/it]

 21%|██▏       | 1010/4716 [19:31<1:11:39,  1.16s/it]

 21%|██▏       | 1011/4716 [19:33<1:11:33,  1.16s/it]

 21%|██▏       | 1012/4716 [19:34<1:11:34,  1.16s/it]

 21%|██▏       | 1013/4716 [19:35<1:11:30,  1.16s/it]

 22%|██▏       | 1014/4716 [19:36<1:11:26,  1.16s/it]

 22%|██▏       | 1015/4716 [19:37<1:11:23,  1.16s/it]

 22%|██▏       | 1016/4716 [19:38<1:11:21,  1.16s/it]

 22%|██▏       | 1017/4716 [19:39<1:11:21,  1.16s/it]

 22%|██▏       | 1018/4716 [19:41<1:11:22,  1.16s/it]

 22%|██▏       | 1019/4716 [19:42<1:11:23,  1.16s/it]

 22%|██▏       | 1020/4716 [19:43<1:11:22,  1.16s/it]

 22%|██▏       | 1021/4716 [19:44<1:11:18,  1.16s/it]

 22%|██▏       | 1022/4716 [19:45<1:11:24,  1.16s/it]

 22%|██▏       | 1023/4716 [19:46<1:11:20,  1.16s/it]

 22%|██▏       | 1024/4716 [19:48<1:11:19,  1.16s/it]

 22%|██▏       | 1025/4716 [19:49<1:11:15,  1.16s/it]

 22%|██▏       | 1026/4716 [19:50<1:11:15,  1.16s/it]

 22%|██▏       | 1027/4716 [19:51<1:11:11,  1.16s/it]

 22%|██▏       | 1028/4716 [19:52<1:11:10,  1.16s/it]

 22%|██▏       | 1029/4716 [19:53<1:11:10,  1.16s/it]

 22%|██▏       | 1030/4716 [19:55<1:11:13,  1.16s/it]

 22%|██▏       | 1031/4716 [19:56<1:11:14,  1.16s/it]

 22%|██▏       | 1032/4716 [19:57<1:11:16,  1.16s/it]

 22%|██▏       | 1033/4716 [19:58<1:11:16,  1.16s/it]

 22%|██▏       | 1034/4716 [19:59<1:11:11,  1.16s/it]

 22%|██▏       | 1035/4716 [20:00<1:11:09,  1.16s/it]

 22%|██▏       | 1036/4716 [20:01<1:11:08,  1.16s/it]

 22%|██▏       | 1037/4716 [20:03<1:11:04,  1.16s/it]

 22%|██▏       | 1038/4716 [20:04<1:11:01,  1.16s/it]

 22%|██▏       | 1039/4716 [20:05<1:11:01,  1.16s/it]

 22%|██▏       | 1040/4716 [20:06<1:10:58,  1.16s/it]

 22%|██▏       | 1041/4716 [20:07<1:10:59,  1.16s/it]

 22%|██▏       | 1042/4716 [20:08<1:10:54,  1.16s/it]

 22%|██▏       | 1043/4716 [20:10<1:10:59,  1.16s/it]

 22%|██▏       | 1044/4716 [20:11<1:10:54,  1.16s/it]

 22%|██▏       | 1045/4716 [20:12<1:10:54,  1.16s/it]

 22%|██▏       | 1046/4716 [20:13<1:10:53,  1.16s/it]

 22%|██▏       | 1047/4716 [20:14<1:10:47,  1.16s/it]

 22%|██▏       | 1048/4716 [20:15<1:10:46,  1.16s/it]

 22%|██▏       | 1049/4716 [20:17<1:10:48,  1.16s/it]

 22%|██▏       | 1050/4716 [20:18<1:10:49,  1.16s/it]

 22%|██▏       | 1051/4716 [20:19<1:10:47,  1.16s/it]

 22%|██▏       | 1052/4716 [20:20<1:10:49,  1.16s/it]

 22%|██▏       | 1053/4716 [20:21<1:10:52,  1.16s/it]

 22%|██▏       | 1054/4716 [20:22<1:10:53,  1.16s/it]

 22%|██▏       | 1055/4716 [20:24<1:10:44,  1.16s/it]

 22%|██▏       | 1056/4716 [20:25<1:10:44,  1.16s/it]

 22%|██▏       | 1057/4716 [20:26<1:10:34,  1.16s/it]

 22%|██▏       | 1058/4716 [20:27<1:10:29,  1.16s/it]

 22%|██▏       | 1059/4716 [20:28<1:10:30,  1.16s/it]

 22%|██▏       | 1060/4716 [20:29<1:10:34,  1.16s/it]

 22%|██▏       | 1061/4716 [20:30<1:10:38,  1.16s/it]

 23%|██▎       | 1062/4716 [20:32<1:10:42,  1.16s/it]

 23%|██▎       | 1063/4716 [20:33<1:10:43,  1.16s/it]

 23%|██▎       | 1064/4716 [20:34<1:10:40,  1.16s/it]

 23%|██▎       | 1065/4716 [20:35<1:10:35,  1.16s/it]

 23%|██▎       | 1066/4716 [20:36<1:10:29,  1.16s/it]

 23%|██▎       | 1067/4716 [20:37<1:10:28,  1.16s/it]

 23%|██▎       | 1068/4716 [20:39<1:10:30,  1.16s/it]

 23%|██▎       | 1069/4716 [20:40<1:10:27,  1.16s/it]

 23%|██▎       | 1070/4716 [20:41<1:10:22,  1.16s/it]

 23%|██▎       | 1071/4716 [20:42<1:10:19,  1.16s/it]

 23%|██▎       | 1072/4716 [20:43<1:10:17,  1.16s/it]

 23%|██▎       | 1073/4716 [20:44<1:10:16,  1.16s/it]

 23%|██▎       | 1074/4716 [20:46<1:10:16,  1.16s/it]

 23%|██▎       | 1075/4716 [20:47<1:10:13,  1.16s/it]

 23%|██▎       | 1076/4716 [20:48<1:10:13,  1.16s/it]

 23%|██▎       | 1077/4716 [20:49<1:10:16,  1.16s/it]

 23%|██▎       | 1078/4716 [20:50<1:10:16,  1.16s/it]

 23%|██▎       | 1079/4716 [20:51<1:10:16,  1.16s/it]

 23%|██▎       | 1080/4716 [20:52<1:10:13,  1.16s/it]

 23%|██▎       | 1081/4716 [20:54<1:10:08,  1.16s/it]

 23%|██▎       | 1082/4716 [20:55<1:10:07,  1.16s/it]

 23%|██▎       | 1083/4716 [20:56<1:10:07,  1.16s/it]

 23%|██▎       | 1084/4716 [20:57<1:10:07,  1.16s/it]

 23%|██▎       | 1085/4716 [20:58<1:10:05,  1.16s/it]

 23%|██▎       | 1086/4716 [20:59<1:10:06,  1.16s/it]

 23%|██▎       | 1087/4716 [21:01<1:10:06,  1.16s/it]

 23%|██▎       | 1088/4716 [21:02<1:10:03,  1.16s/it]

 23%|██▎       | 1089/4716 [21:03<1:10:03,  1.16s/it]

 23%|██▎       | 1090/4716 [21:04<1:09:55,  1.16s/it]

 23%|██▎       | 1091/4716 [21:05<1:09:54,  1.16s/it]

 23%|██▎       | 1092/4716 [21:06<1:09:50,  1.16s/it]

 23%|██▎       | 1093/4716 [21:08<1:09:50,  1.16s/it]

 23%|██▎       | 1094/4716 [21:09<1:09:53,  1.16s/it]

 23%|██▎       | 1095/4716 [21:10<1:09:55,  1.16s/it]

 23%|██▎       | 1096/4716 [21:11<1:09:56,  1.16s/it]

 23%|██▎       | 1097/4716 [21:12<1:09:57,  1.16s/it]

 23%|██▎       | 1098/4716 [21:13<1:09:56,  1.16s/it]

 23%|██▎       | 1099/4716 [21:14<1:09:54,  1.16s/it]

 23%|██▎       | 1100/4716 [21:16<1:09:51,  1.16s/it]

 23%|██▎       | 1101/4716 [21:17<1:09:49,  1.16s/it]

 23%|██▎       | 1102/4716 [21:18<1:09:49,  1.16s/it]

 23%|██▎       | 1103/4716 [21:19<1:09:46,  1.16s/it]

 23%|██▎       | 1104/4716 [21:20<1:09:48,  1.16s/it]

 23%|██▎       | 1105/4716 [21:21<1:09:52,  1.16s/it]

 23%|██▎       | 1106/4716 [21:23<1:09:52,  1.16s/it]

 23%|██▎       | 1107/4716 [21:24<1:09:52,  1.16s/it]

 23%|██▎       | 1108/4716 [21:25<1:09:49,  1.16s/it]

 24%|██▎       | 1109/4716 [21:26<1:09:45,  1.16s/it]

 24%|██▎       | 1110/4716 [21:27<1:09:46,  1.16s/it]

 24%|██▎       | 1111/4716 [21:28<1:09:48,  1.16s/it]

 24%|██▎       | 1112/4716 [21:30<1:09:45,  1.16s/it]

 24%|██▎       | 1113/4716 [21:31<1:09:40,  1.16s/it]

 24%|██▎       | 1114/4716 [21:32<1:09:40,  1.16s/it]

 24%|██▎       | 1115/4716 [21:33<1:09:44,  1.16s/it]

 24%|██▎       | 1116/4716 [21:34<1:09:45,  1.16s/it]

 24%|██▎       | 1117/4716 [21:35<1:09:46,  1.16s/it]

 24%|██▎       | 1118/4716 [21:37<1:09:46,  1.16s/it]

 24%|██▎       | 1119/4716 [21:38<1:09:41,  1.16s/it]

 24%|██▎       | 1120/4716 [21:39<1:09:42,  1.16s/it]

 24%|██▍       | 1121/4716 [21:40<1:09:41,  1.16s/it]

 24%|██▍       | 1122/4716 [21:41<1:09:43,  1.16s/it]

 24%|██▍       | 1123/4716 [21:42<1:09:37,  1.16s/it]

 24%|██▍       | 1124/4716 [21:44<1:09:36,  1.16s/it]

 24%|██▍       | 1125/4716 [21:45<1:09:31,  1.16s/it]

 24%|██▍       | 1126/4716 [21:46<1:09:26,  1.16s/it]

 24%|██▍       | 1127/4716 [21:47<1:09:23,  1.16s/it]

 24%|██▍       | 1128/4716 [21:48<1:09:21,  1.16s/it]

 24%|██▍       | 1129/4716 [21:49<1:09:16,  1.16s/it]

 24%|██▍       | 1130/4716 [21:50<1:09:19,  1.16s/it]

 24%|██▍       | 1131/4716 [21:52<1:09:24,  1.16s/it]

 24%|██▍       | 1132/4716 [21:53<1:09:21,  1.16s/it]

 24%|██▍       | 1133/4716 [21:54<1:09:23,  1.16s/it]

 24%|██▍       | 1134/4716 [21:55<1:09:23,  1.16s/it]

 24%|██▍       | 1135/4716 [21:56<1:09:19,  1.16s/it]

 24%|██▍       | 1136/4716 [21:57<1:09:26,  1.16s/it]

 24%|██▍       | 1137/4716 [21:59<1:09:20,  1.16s/it]

 24%|██▍       | 1138/4716 [22:00<1:09:19,  1.16s/it]

 24%|██▍       | 1139/4716 [22:01<1:09:17,  1.16s/it]

 24%|██▍       | 1140/4716 [22:02<1:09:12,  1.16s/it]

 24%|██▍       | 1141/4716 [22:03<1:09:06,  1.16s/it]

 24%|██▍       | 1142/4716 [22:04<1:09:07,  1.16s/it]

 24%|██▍       | 1143/4716 [22:06<1:09:10,  1.16s/it]

 24%|██▍       | 1144/4716 [22:07<1:09:07,  1.16s/it]

 24%|██▍       | 1145/4716 [22:08<1:09:07,  1.16s/it]

 24%|██▍       | 1146/4716 [22:09<1:09:04,  1.16s/it]

 24%|██▍       | 1147/4716 [22:10<1:09:00,  1.16s/it]

 24%|██▍       | 1148/4716 [22:11<1:09:05,  1.16s/it]

 24%|██▍       | 1149/4716 [22:13<1:09:02,  1.16s/it]

 24%|██▍       | 1150/4716 [22:14<1:08:57,  1.16s/it]

 24%|██▍       | 1151/4716 [22:15<1:08:53,  1.16s/it]

 24%|██▍       | 1152/4716 [22:16<1:08:55,  1.16s/it]

 24%|██▍       | 1153/4716 [22:17<1:08:54,  1.16s/it]

 24%|██▍       | 1154/4716 [22:18<1:08:55,  1.16s/it]

 24%|██▍       | 1155/4716 [22:20<1:08:53,  1.16s/it]

 25%|██▍       | 1156/4716 [22:21<1:08:53,  1.16s/it]

 25%|██▍       | 1157/4716 [22:22<1:08:55,  1.16s/it]

 25%|██▍       | 1158/4716 [22:23<1:08:56,  1.16s/it]

 25%|██▍       | 1159/4716 [22:24<1:08:54,  1.16s/it]

 25%|██▍       | 1160/4716 [22:25<1:08:57,  1.16s/it]

 25%|██▍       | 1161/4716 [22:27<1:08:51,  1.16s/it]

 25%|██▍       | 1162/4716 [22:28<1:08:47,  1.16s/it]

 25%|██▍       | 1163/4716 [22:29<1:08:43,  1.16s/it]

 25%|██▍       | 1164/4716 [22:30<1:08:42,  1.16s/it]

 25%|██▍       | 1165/4716 [22:31<1:08:40,  1.16s/it]

 25%|██▍       | 1166/4716 [22:32<1:08:38,  1.16s/it]

 25%|██▍       | 1167/4716 [22:33<1:08:40,  1.16s/it]

 25%|██▍       | 1168/4716 [22:35<1:08:40,  1.16s/it]

 25%|██▍       | 1169/4716 [22:36<1:08:41,  1.16s/it]

 25%|██▍       | 1170/4716 [22:37<1:08:43,  1.16s/it]

 25%|██▍       | 1171/4716 [22:38<1:08:43,  1.16s/it]

 25%|██▍       | 1172/4716 [22:39<1:08:44,  1.16s/it]

 25%|██▍       | 1173/4716 [22:40<1:08:42,  1.16s/it]

 25%|██▍       | 1174/4716 [22:42<1:08:37,  1.16s/it]

 25%|██▍       | 1175/4716 [22:43<1:08:37,  1.16s/it]

 25%|██▍       | 1176/4716 [22:44<1:08:33,  1.16s/it]

 25%|██▍       | 1177/4716 [22:45<1:08:29,  1.16s/it]

 25%|██▍       | 1178/4716 [22:46<1:08:30,  1.16s/it]

 25%|██▌       | 1179/4716 [22:47<1:08:30,  1.16s/it]

 25%|██▌       | 1180/4716 [22:49<1:08:32,  1.16s/it]

 25%|██▌       | 1181/4716 [22:50<1:08:31,  1.16s/it]

 25%|██▌       | 1182/4716 [22:51<1:08:22,  1.16s/it]

 25%|██▌       | 1183/4716 [22:52<1:08:18,  1.16s/it]

 25%|██▌       | 1184/4716 [22:53<1:08:18,  1.16s/it]

 25%|██▌       | 1185/4716 [22:54<1:08:13,  1.16s/it]

 25%|██▌       | 1186/4716 [22:56<1:08:11,  1.16s/it]

 25%|██▌       | 1187/4716 [22:57<1:08:12,  1.16s/it]

 25%|██▌       | 1188/4716 [22:58<1:08:15,  1.16s/it]

 25%|██▌       | 1189/4716 [22:59<1:08:13,  1.16s/it]

 25%|██▌       | 1190/4716 [23:00<1:08:10,  1.16s/it]

 25%|██▌       | 1191/4716 [23:01<1:08:04,  1.16s/it]

 25%|██▌       | 1192/4716 [23:02<1:08:02,  1.16s/it]

 25%|██▌       | 1193/4716 [23:04<1:08:03,  1.16s/it]

 25%|██▌       | 1194/4716 [23:05<1:08:03,  1.16s/it]

 25%|██▌       | 1195/4716 [23:06<1:08:03,  1.16s/it]

 25%|██▌       | 1196/4716 [23:07<1:08:01,  1.16s/it]

 25%|██▌       | 1197/4716 [23:08<1:07:58,  1.16s/it]

 25%|██▌       | 1198/4716 [23:09<1:08:00,  1.16s/it]

 25%|██▌       | 1199/4716 [23:11<1:08:02,  1.16s/it]

 25%|██▌       | 1200/4716 [23:12<1:07:55,  1.16s/it]

 25%|██▌       | 1201/4716 [23:13<1:07:53,  1.16s/it]

 25%|██▌       | 1202/4716 [23:14<1:07:50,  1.16s/it]

 26%|██▌       | 1203/4716 [23:15<1:07:49,  1.16s/it]

 26%|██▌       | 1204/4716 [23:16<1:07:52,  1.16s/it]

 26%|██▌       | 1205/4716 [23:18<1:07:53,  1.16s/it]

 26%|██▌       | 1206/4716 [23:19<1:07:55,  1.16s/it]

 26%|██▌       | 1207/4716 [23:20<1:07:56,  1.16s/it]

 26%|██▌       | 1208/4716 [23:21<1:07:52,  1.16s/it]

 26%|██▌       | 1209/4716 [23:22<1:07:50,  1.16s/it]

 26%|██▌       | 1210/4716 [23:23<1:07:46,  1.16s/it]

 26%|██▌       | 1211/4716 [23:25<1:07:45,  1.16s/it]

 26%|██▌       | 1212/4716 [23:26<1:07:45,  1.16s/it]

 26%|██▌       | 1213/4716 [23:27<1:07:38,  1.16s/it]

 26%|██▌       | 1214/4716 [23:28<1:07:37,  1.16s/it]

 26%|██▌       | 1215/4716 [23:29<1:07:37,  1.16s/it]

 26%|██▌       | 1216/4716 [23:30<1:07:36,  1.16s/it]

 26%|██▌       | 1217/4716 [23:31<1:07:34,  1.16s/it]

 26%|██▌       | 1218/4716 [23:33<1:07:36,  1.16s/it]

 26%|██▌       | 1219/4716 [23:34<1:07:36,  1.16s/it]

 26%|██▌       | 1220/4716 [23:35<1:07:31,  1.16s/it]

 26%|██▌       | 1221/4716 [23:36<1:07:32,  1.16s/it]

 26%|██▌       | 1222/4716 [23:37<1:07:31,  1.16s/it]

 26%|██▌       | 1223/4716 [23:38<1:07:28,  1.16s/it]

 26%|██▌       | 1224/4716 [23:40<1:07:28,  1.16s/it]

 26%|██▌       | 1225/4716 [23:41<1:07:23,  1.16s/it]

 26%|██▌       | 1226/4716 [23:42<1:07:23,  1.16s/it]

 26%|██▌       | 1227/4716 [23:43<1:07:24,  1.16s/it]

 26%|██▌       | 1228/4716 [23:44<1:07:26,  1.16s/it]

 26%|██▌       | 1229/4716 [23:45<1:07:24,  1.16s/it]

 26%|██▌       | 1230/4716 [23:47<1:07:24,  1.16s/it]

 26%|██▌       | 1231/4716 [23:48<1:07:20,  1.16s/it]

 26%|██▌       | 1232/4716 [23:49<1:07:20,  1.16s/it]

 26%|██▌       | 1233/4716 [23:50<1:07:17,  1.16s/it]

 26%|██▌       | 1234/4716 [23:51<1:07:17,  1.16s/it]

 26%|██▌       | 1235/4716 [23:52<1:07:17,  1.16s/it]

 26%|██▌       | 1236/4716 [23:54<1:07:24,  1.16s/it]

 26%|██▌       | 1237/4716 [23:55<1:07:22,  1.16s/it]

 26%|██▋       | 1238/4716 [23:56<1:07:22,  1.16s/it]

 26%|██▋       | 1239/4716 [23:57<1:07:21,  1.16s/it]

 26%|██▋       | 1240/4716 [23:58<1:07:15,  1.16s/it]

 26%|██▋       | 1241/4716 [23:59<1:07:11,  1.16s/it]

 26%|██▋       | 1242/4716 [24:00<1:07:07,  1.16s/it]

 26%|██▋       | 1243/4716 [24:02<1:07:07,  1.16s/it]

 26%|██▋       | 1244/4716 [24:03<1:07:07,  1.16s/it]

 26%|██▋       | 1245/4716 [24:04<1:07:06,  1.16s/it]

 26%|██▋       | 1246/4716 [24:05<1:07:03,  1.16s/it]

 26%|██▋       | 1247/4716 [24:06<1:07:04,  1.16s/it]

 26%|██▋       | 1248/4716 [24:07<1:07:08,  1.16s/it]

 26%|██▋       | 1249/4716 [24:09<1:07:03,  1.16s/it]

 27%|██▋       | 1250/4716 [24:10<1:07:01,  1.16s/it]

 27%|██▋       | 1251/4716 [24:11<1:06:57,  1.16s/it]

logging
logging the anndata

 27%|██▋       | 1252/4716 [24:12<1:09:19,  1.20s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 27%|██▋       | 1253/4716 [24:13<1:08:29,  1.19s/it]

 27%|██▋       | 1254/4716 [24:15<1:07:53,  1.18s/it]

 27%|██▋       | 1255/4716 [24:16<1:07:30,  1.17s/it]

 27%|██▋       | 1256/4716 [24:17<1:07:13,  1.17s/it]

 27%|██▋       | 1257/4716 [24:18<1:07:03,  1.16s/it]

 27%|██▋       | 1258/4716 [24:19<1:06:50,  1.16s/it]

 27%|██▋       | 1259/4716 [24:20<1:06:45,  1.16s/it]

 27%|██▋       | 1260/4716 [24:21<1:06:41,  1.16s/it]

 27%|██▋       | 1261/4716 [24:23<1:06:38,  1.16s/it]

 27%|██▋       | 1262/4716 [24:24<1:06:34,  1.16s/it]

 27%|██▋       | 1263/4716 [24:25<1:06:30,  1.16s/it]

 27%|██▋       | 1264/4716 [24:26<1:06:31,  1.16s/it]

 27%|██▋       | 1265/4716 [24:27<1:06:29,  1.16s/it]

 27%|██▋       | 1266/4716 [24:28<1:06:29,  1.16s/it]

 27%|██▋       | 1267/4716 [24:30<1:06:27,  1.16s/it]

 27%|██▋       | 1268/4716 [24:31<1:06:25,  1.16s/it]

 27%|██▋       | 1269/4716 [24:32<1:06:22,  1.16s/it]

 27%|██▋       | 1270/4716 [24:33<1:06:23,  1.16s/it]

 27%|██▋       | 1271/4716 [24:34<1:06:25,  1.16s/it]

 27%|██▋       | 1272/4716 [24:35<1:06:22,  1.16s/it]

 27%|██▋       | 1273/4716 [24:36<1:06:22,  1.16s/it]

 27%|██▋       | 1274/4716 [24:38<1:06:18,  1.16s/it]

 27%|██▋       | 1275/4716 [24:39<1:06:17,  1.16s/it]

 27%|██▋       | 1276/4716 [24:40<1:06:13,  1.16s/it]

 27%|██▋       | 1277/4716 [24:41<1:06:13,  1.16s/it]

 27%|██▋       | 1278/4716 [24:42<1:06:14,  1.16s/it]

 27%|██▋       | 1279/4716 [24:43<1:06:12,  1.16s/it]

 27%|██▋       | 1280/4716 [24:45<1:06:14,  1.16s/it]

 27%|██▋       | 1281/4716 [24:46<1:06:09,  1.16s/it]

 27%|██▋       | 1282/4716 [24:47<1:06:10,  1.16s/it]

 27%|██▋       | 1283/4716 [24:48<1:06:10,  1.16s/it]

 27%|██▋       | 1284/4716 [24:49<1:06:06,  1.16s/it]

 27%|██▋       | 1285/4716 [24:50<1:06:05,  1.16s/it]

 27%|██▋       | 1286/4716 [24:52<1:06:04,  1.16s/it]

 27%|██▋       | 1287/4716 [24:53<1:06:05,  1.16s/it]

 27%|██▋       | 1288/4716 [24:54<1:05:59,  1.16s/it]

 27%|██▋       | 1289/4716 [24:55<1:05:59,  1.16s/it]

 27%|██▋       | 1290/4716 [24:56<1:06:03,  1.16s/it]

 27%|██▋       | 1291/4716 [24:57<1:05:58,  1.16s/it]

 27%|██▋       | 1292/4716 [24:58<1:05:58,  1.16s/it]

 27%|██▋       | 1293/4716 [25:00<1:05:58,  1.16s/it]

 27%|██▋       | 1294/4716 [25:01<1:05:59,  1.16s/it]

 27%|██▋       | 1295/4716 [25:02<1:05:59,  1.16s/it]

 27%|██▋       | 1296/4716 [25:03<1:06:03,  1.16s/it]

 28%|██▊       | 1297/4716 [25:04<1:05:57,  1.16s/it]

 28%|██▊       | 1298/4716 [25:05<1:05:54,  1.16s/it]

 28%|██▊       | 1299/4716 [25:07<1:05:51,  1.16s/it]

 28%|██▊       | 1300/4716 [25:08<1:05:52,  1.16s/it]

 28%|██▊       | 1301/4716 [25:09<1:05:47,  1.16s/it]

 28%|██▊       | 1302/4716 [25:10<1:05:55,  1.16s/it]

 28%|██▊       | 1303/4716 [25:11<1:05:52,  1.16s/it]

 28%|██▊       | 1304/4716 [25:12<1:05:47,  1.16s/it]

 28%|██▊       | 1305/4716 [25:13<1:05:43,  1.16s/it]

 28%|██▊       | 1306/4716 [25:15<1:05:40,  1.16s/it]

 28%|██▊       | 1307/4716 [25:16<1:05:41,  1.16s/it]

 28%|██▊       | 1308/4716 [25:17<1:05:40,  1.16s/it]

 28%|██▊       | 1309/4716 [25:18<1:05:41,  1.16s/it]

 28%|██▊       | 1310/4716 [25:19<1:05:39,  1.16s/it]

 28%|██▊       | 1311/4716 [25:20<1:05:36,  1.16s/it]

 28%|██▊       | 1312/4716 [25:22<1:05:35,  1.16s/it]

 28%|██▊       | 1313/4716 [25:23<1:05:31,  1.16s/it]

 28%|██▊       | 1314/4716 [25:24<1:05:27,  1.15s/it]

 28%|██▊       | 1315/4716 [25:25<1:05:25,  1.15s/it]

 28%|██▊       | 1316/4716 [25:26<1:05:28,  1.16s/it]

 28%|██▊       | 1317/4716 [25:27<1:05:29,  1.16s/it]

 28%|██▊       | 1318/4716 [25:29<1:05:28,  1.16s/it]

 28%|██▊       | 1319/4716 [25:30<1:05:26,  1.16s/it]

 28%|██▊       | 1320/4716 [25:31<1:05:27,  1.16s/it]

 28%|██▊       | 1321/4716 [25:32<1:05:26,  1.16s/it]

 28%|██▊       | 1322/4716 [25:33<1:05:23,  1.16s/it]

 28%|██▊       | 1323/4716 [25:34<1:05:26,  1.16s/it]

 28%|██▊       | 1324/4716 [25:35<1:05:22,  1.16s/it]

 28%|██▊       | 1325/4716 [25:37<1:05:21,  1.16s/it]

 28%|██▊       | 1326/4716 [25:38<1:05:21,  1.16s/it]

 28%|██▊       | 1327/4716 [25:39<1:05:20,  1.16s/it]

 28%|██▊       | 1328/4716 [25:40<1:05:21,  1.16s/it]

 28%|██▊       | 1329/4716 [25:41<1:05:18,  1.16s/it]

 28%|██▊       | 1330/4716 [25:42<1:05:18,  1.16s/it]

 28%|██▊       | 1331/4716 [25:44<1:05:12,  1.16s/it]

 28%|██▊       | 1332/4716 [25:45<1:05:11,  1.16s/it]

 28%|██▊       | 1333/4716 [25:46<1:05:12,  1.16s/it]

 28%|██▊       | 1334/4716 [25:47<1:05:10,  1.16s/it]

 28%|██▊       | 1335/4716 [25:48<1:05:12,  1.16s/it]

 28%|██▊       | 1336/4716 [25:49<1:05:12,  1.16s/it]

 28%|██▊       | 1337/4716 [25:50<1:05:10,  1.16s/it]

 28%|██▊       | 1338/4716 [25:52<1:05:06,  1.16s/it]

 28%|██▊       | 1339/4716 [25:53<1:05:01,  1.16s/it]

 28%|██▊       | 1340/4716 [25:54<1:05:02,  1.16s/it]

 28%|██▊       | 1341/4716 [25:55<1:04:59,  1.16s/it]

 28%|██▊       | 1342/4716 [25:56<1:05:01,  1.16s/it]

 28%|██▊       | 1343/4716 [25:57<1:05:00,  1.16s/it]

 28%|██▊       | 1344/4716 [25:59<1:04:59,  1.16s/it]

 29%|██▊       | 1345/4716 [26:00<1:04:57,  1.16s/it]

 29%|██▊       | 1346/4716 [26:01<1:05:00,  1.16s/it]

 29%|██▊       | 1347/4716 [26:02<1:04:56,  1.16s/it]

 29%|██▊       | 1348/4716 [26:03<1:04:53,  1.16s/it]

 29%|██▊       | 1349/4716 [26:04<1:04:55,  1.16s/it]

 29%|██▊       | 1350/4716 [26:06<1:04:55,  1.16s/it]

 29%|██▊       | 1351/4716 [26:07<1:04:57,  1.16s/it]

 29%|██▊       | 1352/4716 [26:08<1:04:57,  1.16s/it]

 29%|██▊       | 1353/4716 [26:09<1:04:54,  1.16s/it]

 29%|██▊       | 1354/4716 [26:10<1:04:51,  1.16s/it]

 29%|██▊       | 1355/4716 [26:11<1:04:51,  1.16s/it]

 29%|██▉       | 1356/4716 [26:12<1:04:47,  1.16s/it]

 29%|██▉       | 1357/4716 [26:14<1:04:48,  1.16s/it]

 29%|██▉       | 1358/4716 [26:15<1:04:43,  1.16s/it]

 29%|██▉       | 1359/4716 [26:16<1:04:41,  1.16s/it]

 29%|██▉       | 1360/4716 [26:17<1:04:38,  1.16s/it]

 29%|██▉       | 1361/4716 [26:18<1:04:37,  1.16s/it]

 29%|██▉       | 1362/4716 [26:19<1:04:35,  1.16s/it]

 29%|██▉       | 1363/4716 [26:21<1:04:39,  1.16s/it]

 29%|██▉       | 1364/4716 [26:22<1:04:36,  1.16s/it]

 29%|██▉       | 1365/4716 [26:23<1:04:36,  1.16s/it]

 29%|██▉       | 1366/4716 [26:24<1:04:32,  1.16s/it]

 29%|██▉       | 1367/4716 [26:25<1:04:29,  1.16s/it]

 29%|██▉       | 1368/4716 [26:26<1:04:29,  1.16s/it]

 29%|██▉       | 1369/4716 [26:28<1:04:32,  1.16s/it]

 29%|██▉       | 1370/4716 [26:29<1:04:28,  1.16s/it]

 29%|██▉       | 1371/4716 [26:30<1:04:31,  1.16s/it]

 29%|██▉       | 1372/4716 [26:31<1:04:30,  1.16s/it]

 29%|██▉       | 1373/4716 [26:32<1:04:27,  1.16s/it]

 29%|██▉       | 1374/4716 [26:33<1:04:27,  1.16s/it]

 29%|██▉       | 1375/4716 [26:34<1:04:27,  1.16s/it]

 29%|██▉       | 1376/4716 [26:36<1:04:26,  1.16s/it]

 29%|██▉       | 1377/4716 [26:37<1:04:24,  1.16s/it]

 29%|██▉       | 1378/4716 [26:38<1:04:18,  1.16s/it]

 29%|██▉       | 1379/4716 [26:39<1:04:18,  1.16s/it]

 29%|██▉       | 1380/4716 [26:40<1:04:19,  1.16s/it]

 29%|██▉       | 1381/4716 [26:41<1:04:19,  1.16s/it]

 29%|██▉       | 1382/4716 [26:43<1:04:18,  1.16s/it]

 29%|██▉       | 1383/4716 [26:44<1:04:16,  1.16s/it]

 29%|██▉       | 1384/4716 [26:45<1:04:15,  1.16s/it]

 29%|██▉       | 1385/4716 [26:46<1:04:11,  1.16s/it]

 29%|██▉       | 1386/4716 [26:47<1:04:07,  1.16s/it]

 29%|██▉       | 1387/4716 [26:48<1:04:07,  1.16s/it]

 29%|██▉       | 1388/4716 [26:49<1:04:05,  1.16s/it]

 29%|██▉       | 1389/4716 [26:51<1:04:05,  1.16s/it]

 29%|██▉       | 1390/4716 [26:52<1:04:09,  1.16s/it]

 29%|██▉       | 1391/4716 [26:53<1:04:09,  1.16s/it]

 30%|██▉       | 1392/4716 [26:54<1:04:06,  1.16s/it]

 30%|██▉       | 1393/4716 [26:55<1:04:03,  1.16s/it]

 30%|██▉       | 1394/4716 [26:56<1:04:01,  1.16s/it]

 30%|██▉       | 1395/4716 [26:58<1:04:01,  1.16s/it]

 30%|██▉       | 1396/4716 [26:59<1:03:56,  1.16s/it]

 30%|██▉       | 1397/4716 [27:00<1:03:55,  1.16s/it]

 30%|██▉       | 1398/4716 [27:01<1:03:57,  1.16s/it]

 30%|██▉       | 1399/4716 [27:02<1:03:58,  1.16s/it]

 30%|██▉       | 1400/4716 [27:03<1:03:57,  1.16s/it]

 30%|██▉       | 1401/4716 [27:05<1:03:56,  1.16s/it]

 30%|██▉       | 1402/4716 [27:06<1:03:54,  1.16s/it]

 30%|██▉       | 1403/4716 [27:07<1:03:54,  1.16s/it]

 30%|██▉       | 1404/4716 [27:08<1:03:47,  1.16s/it]

 30%|██▉       | 1405/4716 [27:09<1:03:44,  1.15s/it]

 30%|██▉       | 1406/4716 [27:10<1:03:42,  1.15s/it]

 30%|██▉       | 1407/4716 [27:11<1:03:44,  1.16s/it]

 30%|██▉       | 1408/4716 [27:13<1:03:48,  1.16s/it]

 30%|██▉       | 1409/4716 [27:14<1:03:48,  1.16s/it]

 30%|██▉       | 1410/4716 [27:15<1:03:49,  1.16s/it]

 30%|██▉       | 1411/4716 [27:16<1:03:46,  1.16s/it]

 30%|██▉       | 1412/4716 [27:17<1:03:42,  1.16s/it]

 30%|██▉       | 1413/4716 [27:18<1:03:41,  1.16s/it]

 30%|██▉       | 1414/4716 [27:20<1:03:38,  1.16s/it]

 30%|███       | 1415/4716 [27:21<1:03:37,  1.16s/it]

 30%|███       | 1416/4716 [27:22<1:03:32,  1.16s/it]

 30%|███       | 1417/4716 [27:23<1:03:29,  1.15s/it]

 30%|███       | 1418/4716 [27:24<1:03:30,  1.16s/it]

 30%|███       | 1419/4716 [27:25<1:03:31,  1.16s/it]

 30%|███       | 1420/4716 [27:26<1:03:30,  1.16s/it]

 30%|███       | 1421/4716 [27:28<1:03:31,  1.16s/it]

 30%|███       | 1422/4716 [27:29<1:03:33,  1.16s/it]

 30%|███       | 1423/4716 [27:30<1:03:29,  1.16s/it]

 30%|███       | 1424/4716 [27:31<1:03:29,  1.16s/it]

 30%|███       | 1425/4716 [27:32<1:03:24,  1.16s/it]

 30%|███       | 1426/4716 [27:33<1:03:20,  1.16s/it]

 30%|███       | 1427/4716 [27:35<1:03:19,  1.16s/it]

 30%|███       | 1428/4716 [27:36<1:03:19,  1.16s/it]

 30%|███       | 1429/4716 [27:37<1:03:18,  1.16s/it]

 30%|███       | 1430/4716 [27:38<1:03:19,  1.16s/it]

 30%|███       | 1431/4716 [27:39<1:03:15,  1.16s/it]

 30%|███       | 1432/4716 [27:40<1:03:14,  1.16s/it]

 30%|███       | 1433/4716 [27:42<1:03:12,  1.16s/it]

 30%|███       | 1434/4716 [27:43<1:03:09,  1.15s/it]

 30%|███       | 1435/4716 [27:44<1:03:08,  1.15s/it]

 30%|███       | 1436/4716 [27:45<1:03:11,  1.16s/it]

 30%|███       | 1437/4716 [27:46<1:03:14,  1.16s/it]

 30%|███       | 1438/4716 [27:47<1:03:12,  1.16s/it]

 31%|███       | 1439/4716 [27:48<1:03:09,  1.16s/it]

 31%|███       | 1440/4716 [27:50<1:03:08,  1.16s/it]

 31%|███       | 1441/4716 [27:51<1:03:08,  1.16s/it]

 31%|███       | 1442/4716 [27:52<1:03:02,  1.16s/it]

 31%|███       | 1443/4716 [27:53<1:03:04,  1.16s/it]

 31%|███       | 1444/4716 [27:54<1:03:04,  1.16s/it]

 31%|███       | 1445/4716 [27:55<1:03:02,  1.16s/it]

 31%|███       | 1446/4716 [27:57<1:03:01,  1.16s/it]

 31%|███       | 1447/4716 [27:58<1:02:58,  1.16s/it]

 31%|███       | 1448/4716 [27:59<1:02:58,  1.16s/it]

 31%|███       | 1449/4716 [28:00<1:02:56,  1.16s/it]

 31%|███       | 1450/4716 [28:01<1:02:59,  1.16s/it]

 31%|███       | 1451/4716 [28:02<1:02:58,  1.16s/it]

 31%|███       | 1452/4716 [28:03<1:02:53,  1.16s/it]

 31%|███       | 1453/4716 [28:05<1:02:52,  1.16s/it]

 31%|███       | 1454/4716 [28:06<1:02:52,  1.16s/it]

 31%|███       | 1455/4716 [28:07<1:02:55,  1.16s/it]

 31%|███       | 1456/4716 [28:08<1:02:52,  1.16s/it]

 31%|███       | 1457/4716 [28:09<1:02:51,  1.16s/it]

 31%|███       | 1458/4716 [28:10<1:02:50,  1.16s/it]

 31%|███       | 1459/4716 [28:12<1:02:49,  1.16s/it]

 31%|███       | 1460/4716 [28:13<1:02:46,  1.16s/it]

 31%|███       | 1461/4716 [28:14<1:02:44,  1.16s/it]

 31%|███       | 1462/4716 [28:15<1:02:44,  1.16s/it]

 31%|███       | 1463/4716 [28:16<1:02:46,  1.16s/it]

 31%|███       | 1464/4716 [28:17<1:02:52,  1.16s/it]

 31%|███       | 1465/4716 [28:19<1:02:49,  1.16s/it]

 31%|███       | 1466/4716 [28:20<1:02:56,  1.16s/it]

 31%|███       | 1467/4716 [28:21<1:02:48,  1.16s/it]

 31%|███       | 1468/4716 [28:22<1:02:45,  1.16s/it]

 31%|███       | 1469/4716 [28:23<1:02:44,  1.16s/it]

 31%|███       | 1470/4716 [28:24<1:02:44,  1.16s/it]

 31%|███       | 1471/4716 [28:26<1:02:40,  1.16s/it]

 31%|███       | 1472/4716 [28:27<1:02:37,  1.16s/it]

 31%|███       | 1473/4716 [28:28<1:02:31,  1.16s/it]

 31%|███▏      | 1474/4716 [28:29<1:02:31,  1.16s/it]

 31%|███▏      | 1475/4716 [28:30<1:02:26,  1.16s/it]

 31%|███▏      | 1476/4716 [28:31<1:02:27,  1.16s/it]

 31%|███▏      | 1477/4716 [28:32<1:02:29,  1.16s/it]

 31%|███▏      | 1478/4716 [28:34<1:02:27,  1.16s/it]

 31%|███▏      | 1479/4716 [28:35<1:02:22,  1.16s/it]

 31%|███▏      | 1480/4716 [28:36<1:02:25,  1.16s/it]

 31%|███▏      | 1481/4716 [28:37<1:02:21,  1.16s/it]

 31%|███▏      | 1482/4716 [28:38<1:02:20,  1.16s/it]

 31%|███▏      | 1483/4716 [28:39<1:02:18,  1.16s/it]

 31%|███▏      | 1484/4716 [28:41<1:02:17,  1.16s/it]

 31%|███▏      | 1485/4716 [28:42<1:02:19,  1.16s/it]

 32%|███▏      | 1486/4716 [28:43<1:02:16,  1.16s/it]

 32%|███▏      | 1487/4716 [28:44<1:02:18,  1.16s/it]

 32%|███▏      | 1488/4716 [28:45<1:02:18,  1.16s/it]

 32%|███▏      | 1489/4716 [28:46<1:02:15,  1.16s/it]

 32%|███▏      | 1490/4716 [28:47<1:02:14,  1.16s/it]

 32%|███▏      | 1491/4716 [28:49<1:02:12,  1.16s/it]

 32%|███▏      | 1492/4716 [28:50<1:02:10,  1.16s/it]

 32%|███▏      | 1493/4716 [28:51<1:02:10,  1.16s/it]

 32%|███▏      | 1494/4716 [28:52<1:02:06,  1.16s/it]

 32%|███▏      | 1495/4716 [28:53<1:02:07,  1.16s/it]

 32%|███▏      | 1496/4716 [28:54<1:02:06,  1.16s/it]

 32%|███▏      | 1497/4716 [28:56<1:02:07,  1.16s/it]

 32%|███▏      | 1498/4716 [28:57<1:02:05,  1.16s/it]

 32%|███▏      | 1499/4716 [28:58<1:02:01,  1.16s/it]

 32%|███▏      | 1500/4716 [28:59<1:02:00,  1.16s/it]

 32%|███▏      | 1501/4716 [29:00<1:02:00,  1.16s/it]

 32%|███▏      | 1502/4716 [29:01<1:01:56,  1.16s/it]

 32%|███▏      | 1503/4716 [29:03<1:01:58,  1.16s/it]

 32%|███▏      | 1504/4716 [29:04<1:02:00,  1.16s/it]

 32%|███▏      | 1505/4716 [29:05<1:02:01,  1.16s/it]

 32%|███▏      | 1506/4716 [29:06<1:01:58,  1.16s/it]

 32%|███▏      | 1507/4716 [29:07<1:01:57,  1.16s/it]

 32%|███▏      | 1508/4716 [29:08<1:01:55,  1.16s/it]

 32%|███▏      | 1509/4716 [29:09<1:01:55,  1.16s/it]

 32%|███▏      | 1510/4716 [29:11<1:01:53,  1.16s/it]

 32%|███▏      | 1511/4716 [29:12<1:01:49,  1.16s/it]

 32%|███▏      | 1512/4716 [29:13<1:01:45,  1.16s/it]

 32%|███▏      | 1513/4716 [29:14<1:01:47,  1.16s/it]

 32%|███▏      | 1514/4716 [29:15<1:01:47,  1.16s/it]

 32%|███▏      | 1515/4716 [29:16<1:01:46,  1.16s/it]

 32%|███▏      | 1516/4716 [29:18<1:01:46,  1.16s/it]

 32%|███▏      | 1517/4716 [29:19<1:01:47,  1.16s/it]

 32%|███▏      | 1518/4716 [29:20<1:01:47,  1.16s/it]

 32%|███▏      | 1519/4716 [29:21<1:01:43,  1.16s/it]

 32%|███▏      | 1520/4716 [29:22<1:01:42,  1.16s/it]

 32%|███▏      | 1521/4716 [29:23<1:01:36,  1.16s/it]

 32%|███▏      | 1522/4716 [29:25<1:01:34,  1.16s/it]

 32%|███▏      | 1523/4716 [29:26<1:01:36,  1.16s/it]

 32%|███▏      | 1524/4716 [29:27<1:01:40,  1.16s/it]

 32%|███▏      | 1525/4716 [29:28<1:01:38,  1.16s/it]

 32%|███▏      | 1526/4716 [29:29<1:01:38,  1.16s/it]

 32%|███▏      | 1527/4716 [29:30<1:01:37,  1.16s/it]

 32%|███▏      | 1528/4716 [29:31<1:01:34,  1.16s/it]

 32%|███▏      | 1529/4716 [29:33<1:01:36,  1.16s/it]

 32%|███▏      | 1530/4716 [29:34<1:01:32,  1.16s/it]

 32%|███▏      | 1531/4716 [29:35<1:01:29,  1.16s/it]

 32%|███▏      | 1532/4716 [29:36<1:01:28,  1.16s/it]

 33%|███▎      | 1533/4716 [29:37<1:01:27,  1.16s/it]

 33%|███▎      | 1534/4716 [29:38<1:01:23,  1.16s/it]

 33%|███▎      | 1535/4716 [29:40<1:01:18,  1.16s/it]

 33%|███▎      | 1536/4716 [29:41<1:01:19,  1.16s/it]

 33%|███▎      | 1537/4716 [29:42<1:01:20,  1.16s/it]

 33%|███▎      | 1538/4716 [29:43<1:01:19,  1.16s/it]

 33%|███▎      | 1539/4716 [29:44<1:01:20,  1.16s/it]

 33%|███▎      | 1540/4716 [29:45<1:01:18,  1.16s/it]

 33%|███▎      | 1541/4716 [29:47<1:01:17,  1.16s/it]

 33%|███▎      | 1542/4716 [29:48<1:01:15,  1.16s/it]

 33%|███▎      | 1543/4716 [29:49<1:01:14,  1.16s/it]

 33%|███▎      | 1544/4716 [29:50<1:01:09,  1.16s/it]

 33%|███▎      | 1545/4716 [29:51<1:01:09,  1.16s/it]

 33%|███▎      | 1546/4716 [29:52<1:01:07,  1.16s/it]

 33%|███▎      | 1547/4716 [29:53<1:01:08,  1.16s/it]

 33%|███▎      | 1548/4716 [29:55<1:01:10,  1.16s/it]

 33%|███▎      | 1549/4716 [29:56<1:01:10,  1.16s/it]

 33%|███▎      | 1550/4716 [29:57<1:01:09,  1.16s/it]

 33%|███▎      | 1551/4716 [29:58<1:01:07,  1.16s/it]

 33%|███▎      | 1552/4716 [29:59<1:01:05,  1.16s/it]

 33%|███▎      | 1553/4716 [30:00<1:01:01,  1.16s/it]

 33%|███▎      | 1554/4716 [30:02<1:00:58,  1.16s/it]

 33%|███▎      | 1555/4716 [30:03<1:00:57,  1.16s/it]

 33%|███▎      | 1556/4716 [30:04<1:00:55,  1.16s/it]

 33%|███▎      | 1557/4716 [30:05<1:00:54,  1.16s/it]

 33%|███▎      | 1558/4716 [30:06<1:00:55,  1.16s/it]

 33%|███▎      | 1559/4716 [30:07<1:00:53,  1.16s/it]

 33%|███▎      | 1560/4716 [30:09<1:00:50,  1.16s/it]

 33%|███▎      | 1561/4716 [30:10<1:00:56,  1.16s/it]

 33%|███▎      | 1562/4716 [30:11<1:00:56,  1.16s/it]

 33%|███▎      | 1563/4716 [30:12<1:00:54,  1.16s/it]

 33%|███▎      | 1564/4716 [30:13<1:00:50,  1.16s/it]

 33%|███▎      | 1565/4716 [30:14<1:00:47,  1.16s/it]

 33%|███▎      | 1566/4716 [30:15<1:00:45,  1.16s/it]

 33%|███▎      | 1567/4716 [30:17<1:00:45,  1.16s/it]

 33%|███▎      | 1568/4716 [30:18<1:00:46,  1.16s/it]

 33%|███▎      | 1569/4716 [30:19<1:00:46,  1.16s/it]

 33%|███▎      | 1570/4716 [30:20<1:00:43,  1.16s/it]

 33%|███▎      | 1571/4716 [30:21<1:00:43,  1.16s/it]

 33%|███▎      | 1572/4716 [30:22<1:00:42,  1.16s/it]

 33%|███▎      | 1573/4716 [30:24<1:00:40,  1.16s/it]

 33%|███▎      | 1574/4716 [30:25<1:00:37,  1.16s/it]

 33%|███▎      | 1575/4716 [30:26<1:00:35,  1.16s/it]

 33%|███▎      | 1576/4716 [30:27<1:00:35,  1.16s/it]

 33%|███▎      | 1577/4716 [30:28<1:00:33,  1.16s/it]

 33%|███▎      | 1578/4716 [30:29<1:00:32,  1.16s/it]

 33%|███▎      | 1579/4716 [30:31<1:00:32,  1.16s/it]

 34%|███▎      | 1580/4716 [30:32<1:00:34,  1.16s/it]

 34%|███▎      | 1581/4716 [30:33<1:00:34,  1.16s/it]

 34%|███▎      | 1582/4716 [30:34<1:00:33,  1.16s/it]

 34%|███▎      | 1583/4716 [30:35<1:00:33,  1.16s/it]

 34%|███▎      | 1584/4716 [30:36<1:00:35,  1.16s/it]

 34%|███▎      | 1585/4716 [30:38<1:00:36,  1.16s/it]

 34%|███▎      | 1586/4716 [30:39<1:00:33,  1.16s/it]

 34%|███▎      | 1587/4716 [30:40<1:00:29,  1.16s/it]

 34%|███▎      | 1588/4716 [30:41<1:00:28,  1.16s/it]

 34%|███▎      | 1589/4716 [30:42<1:00:22,  1.16s/it]

 34%|███▎      | 1590/4716 [30:43<1:00:19,  1.16s/it]

 34%|███▎      | 1591/4716 [30:44<1:00:17,  1.16s/it]

 34%|███▍      | 1592/4716 [30:46<1:00:18,  1.16s/it]

 34%|███▍      | 1593/4716 [30:47<1:00:18,  1.16s/it]

 34%|███▍      | 1594/4716 [30:48<1:00:19,  1.16s/it]

 34%|███▍      | 1595/4716 [30:49<1:00:17,  1.16s/it]

 34%|███▍      | 1596/4716 [30:50<1:00:15,  1.16s/it]

 34%|███▍      | 1597/4716 [30:51<1:00:15,  1.16s/it]

 34%|███▍      | 1598/4716 [30:53<1:00:15,  1.16s/it]

 34%|███▍      | 1599/4716 [30:54<1:00:10,  1.16s/it]

 34%|███▍      | 1600/4716 [30:55<1:00:10,  1.16s/it]

 34%|███▍      | 1601/4716 [30:56<1:00:08,  1.16s/it]

 34%|███▍      | 1602/4716 [30:57<1:00:04,  1.16s/it]

 34%|███▍      | 1603/4716 [30:58<1:00:05,  1.16s/it]

 34%|███▍      | 1604/4716 [31:00<1:00:09,  1.16s/it]

 34%|███▍      | 1605/4716 [31:01<1:00:08,  1.16s/it]

 34%|███▍      | 1606/4716 [31:02<1:00:09,  1.16s/it]

 34%|███▍      | 1607/4716 [31:03<1:00:04,  1.16s/it]

 34%|███▍      | 1608/4716 [31:04<1:00:00,  1.16s/it]

 34%|███▍      | 1609/4716 [31:05<59:54,  1.16s/it]

 34%|███▍      | 1610/4716 [31:06<59:56,  1.16s/it]

 34%|███▍      | 1611/4716 [31:08<59:55,  1.16s/it]

 34%|███▍      | 1612/4716 [31:09<59:55,  1.16s/it]

 34%|███▍      | 1613/4716 [31:10<59:54,  1.16s/it]

 34%|███▍      | 1614/4716 [31:11<59:56,  1.16s/it]

 34%|███▍      | 1615/4716 [31:12<59:53,  1.16s/it]

 34%|███▍      | 1616/4716 [31:13<1:00:00,  1.16s/it]

 34%|███▍      | 1617/4716 [31:15<59:54,  1.16s/it]

 34%|███▍      | 1618/4716 [31:16<59:54,  1.16s/it]

 34%|███▍      | 1619/4716 [31:17<59:53,  1.16s/it]

 34%|███▍      | 1620/4716 [31:18<59:47,  1.16s/it]

 34%|███▍      | 1621/4716 [31:19<59:44,  1.16s/it]

 34%|███▍      | 1622/4716 [31:20<59:43,  1.16s/it]

 34%|███▍      | 1623/4716 [31:22<59:42,  1.16s/it]

 34%|███▍      | 1624/4716 [31:23<59:44,  1.16s/it]

 34%|███▍      | 1625/4716 [31:24<59:46,  1.16s/it]

 34%|███▍      | 1626/4716 [31:25<59:43,  1.16s/it]

 34%|███▍      | 1627/4716 [31:26<59:40,  1.16s/it]

 35%|███▍      | 1628/4716 [31:27<59:38,  1.16s/it]

 35%|███▍      | 1629/4716 [31:29<59:34,  1.16s/it]

 35%|███▍      | 1630/4716 [31:30<59:33,  1.16s/it]

 35%|███▍      | 1631/4716 [31:31<59:31,  1.16s/it]

 35%|███▍      | 1632/4716 [31:32<59:30,  1.16s/it]

 35%|███▍      | 1633/4716 [31:33<59:32,  1.16s/it]

 35%|███▍      | 1634/4716 [31:34<59:34,  1.16s/it]

 35%|███▍      | 1635/4716 [31:35<59:30,  1.16s/it]

 35%|███▍      | 1636/4716 [31:37<59:28,  1.16s/it]

 35%|███▍      | 1637/4716 [31:38<59:25,  1.16s/it]

 35%|███▍      | 1638/4716 [31:39<59:22,  1.16s/it]

 35%|███▍      | 1639/4716 [31:40<59:24,  1.16s/it]

 35%|███▍      | 1640/4716 [31:41<59:24,  1.16s/it]

 35%|███▍      | 1641/4716 [31:42<59:24,  1.16s/it]

 35%|███▍      | 1642/4716 [31:44<59:29,  1.16s/it]

 35%|███▍      | 1643/4716 [31:45<59:27,  1.16s/it]

 35%|███▍      | 1644/4716 [31:46<59:24,  1.16s/it]

 35%|███▍      | 1645/4716 [31:47<59:22,  1.16s/it]

 35%|███▍      | 1646/4716 [31:48<59:16,  1.16s/it]

 35%|███▍      | 1647/4716 [31:49<59:18,  1.16s/it]

 35%|███▍      | 1648/4716 [31:51<59:17,  1.16s/it]

 35%|███▍      | 1649/4716 [31:52<59:16,  1.16s/it]

 35%|███▍      | 1650/4716 [31:53<59:12,  1.16s/it]

 35%|███▌      | 1651/4716 [31:54<59:14,  1.16s/it]

 35%|███▌      | 1652/4716 [31:55<59:08,  1.16s/it]

 35%|███▌      | 1653/4716 [31:56<59:05,  1.16s/it]

 35%|███▌      | 1654/4716 [31:57<59:06,  1.16s/it]

 35%|███▌      | 1655/4716 [31:59<59:04,  1.16s/it]

 35%|███▌      | 1656/4716 [32:00<59:05,  1.16s/it]

 35%|███▌      | 1657/4716 [32:01<59:06,  1.16s/it]

 35%|███▌      | 1658/4716 [32:02<59:06,  1.16s/it]

 35%|███▌      | 1659/4716 [32:03<59:03,  1.16s/it]

 35%|███▌      | 1660/4716 [32:04<58:59,  1.16s/it]

 35%|███▌      | 1661/4716 [32:06<59:00,  1.16s/it]

 35%|███▌      | 1662/4716 [32:07<58:57,  1.16s/it]

 35%|███▌      | 1663/4716 [32:08<58:53,  1.16s/it]

 35%|███▌      | 1664/4716 [32:09<58:52,  1.16s/it]

 35%|███▌      | 1665/4716 [32:10<58:50,  1.16s/it]

 35%|███▌      | 1666/4716 [32:11<58:50,  1.16s/it]

 35%|███▌      | 1667/4716 [32:13<58:53,  1.16s/it]

 35%|███▌      | 1668/4716 [32:14<58:55,  1.16s/it]

 35%|███▌      | 1669/4716 [32:15<58:56,  1.16s/it]

 35%|███▌      | 1670/4716 [32:16<58:53,  1.16s/it]

 35%|███▌      | 1671/4716 [32:17<58:51,  1.16s/it]

 35%|███▌      | 1672/4716 [32:18<58:46,  1.16s/it]

 35%|███▌      | 1673/4716 [32:19<58:46,  1.16s/it]

 35%|███▌      | 1674/4716 [32:21<58:43,  1.16s/it]

 36%|███▌      | 1675/4716 [32:22<58:42,  1.16s/it]

 36%|███▌      | 1676/4716 [32:23<58:41,  1.16s/it]

 36%|███▌      | 1677/4716 [32:24<58:41,  1.16s/it]

 36%|███▌      | 1678/4716 [32:25<58:40,  1.16s/it]

 36%|███▌      | 1679/4716 [32:26<58:41,  1.16s/it]

 36%|███▌      | 1680/4716 [32:28<58:38,  1.16s/it]

 36%|███▌      | 1681/4716 [32:29<58:40,  1.16s/it]

 36%|███▌      | 1682/4716 [32:30<58:35,  1.16s/it]

 36%|███▌      | 1683/4716 [32:31<58:35,  1.16s/it]

 36%|███▌      | 1684/4716 [32:32<58:35,  1.16s/it]

 36%|███▌      | 1685/4716 [32:33<58:32,  1.16s/it]

 36%|███▌      | 1686/4716 [32:35<58:30,  1.16s/it]

 36%|███▌      | 1687/4716 [32:36<58:31,  1.16s/it]

 36%|███▌      | 1688/4716 [32:37<58:32,  1.16s/it]

 36%|███▌      | 1689/4716 [32:38<58:33,  1.16s/it]

 36%|███▌      | 1690/4716 [32:39<58:30,  1.16s/it]

 36%|███▌      | 1691/4716 [32:40<58:27,  1.16s/it]

 36%|███▌      | 1692/4716 [32:42<58:28,  1.16s/it]

 36%|███▌      | 1693/4716 [32:43<58:24,  1.16s/it]

 36%|███▌      | 1694/4716 [32:44<58:20,  1.16s/it]

 36%|███▌      | 1695/4716 [32:45<58:17,  1.16s/it]

 36%|███▌      | 1696/4716 [32:46<58:19,  1.16s/it]

 36%|███▌      | 1697/4716 [32:47<58:18,  1.16s/it]

 36%|███▌      | 1698/4716 [32:48<58:20,  1.16s/it]

 36%|███▌      | 1699/4716 [32:50<58:18,  1.16s/it]

 36%|███▌      | 1700/4716 [32:51<58:16,  1.16s/it]

 36%|███▌      | 1701/4716 [32:52<58:14,  1.16s/it]

 36%|███▌      | 1702/4716 [32:53<58:11,  1.16s/it]

 36%|███▌      | 1703/4716 [32:54<58:15,  1.16s/it]

 36%|███▌      | 1704/4716 [32:55<58:10,  1.16s/it]

 36%|███▌      | 1705/4716 [32:57<58:09,  1.16s/it]

 36%|███▌      | 1706/4716 [32:58<58:09,  1.16s/it]

 36%|███▌      | 1707/4716 [32:59<58:06,  1.16s/it]

 36%|███▌      | 1708/4716 [33:00<58:02,  1.16s/it]

 36%|███▌      | 1709/4716 [33:01<58:00,  1.16s/it]

 36%|███▋      | 1710/4716 [33:02<57:59,  1.16s/it]

 36%|███▋      | 1711/4716 [33:04<58:03,  1.16s/it]

 36%|███▋      | 1712/4716 [33:05<58:04,  1.16s/it]

 36%|███▋      | 1713/4716 [33:06<58:03,  1.16s/it]

 36%|███▋      | 1714/4716 [33:07<58:01,  1.16s/it]

 36%|███▋      | 1715/4716 [33:08<58:00,  1.16s/it]

 36%|███▋      | 1716/4716 [33:09<58:03,  1.16s/it]

 36%|███▋      | 1717/4716 [33:11<58:02,  1.16s/it]

 36%|███▋      | 1718/4716 [33:12<57:59,  1.16s/it]

 36%|███▋      | 1719/4716 [33:13<57:54,  1.16s/it]

 36%|███▋      | 1720/4716 [33:14<57:53,  1.16s/it]

 36%|███▋      | 1721/4716 [33:15<57:51,  1.16s/it]

 37%|███▋      | 1722/4716 [33:16<57:48,  1.16s/it]

 37%|███▋      | 1723/4716 [33:17<57:47,  1.16s/it]

 37%|███▋      | 1724/4716 [33:19<57:46,  1.16s/it]

 37%|███▋      | 1725/4716 [33:20<57:48,  1.16s/it]

 37%|███▋      | 1726/4716 [33:21<57:47,  1.16s/it]

 37%|███▋      | 1727/4716 [33:22<57:47,  1.16s/it]

 37%|███▋      | 1728/4716 [33:23<57:47,  1.16s/it]

 37%|███▋      | 1729/4716 [33:24<57:44,  1.16s/it]

 37%|███▋      | 1730/4716 [33:26<57:39,  1.16s/it]

 37%|███▋      | 1731/4716 [33:27<57:38,  1.16s/it]

 37%|███▋      | 1732/4716 [33:28<57:37,  1.16s/it]

 37%|███▋      | 1733/4716 [33:29<57:37,  1.16s/it]

 37%|███▋      | 1734/4716 [33:30<57:36,  1.16s/it]

 37%|███▋      | 1735/4716 [33:31<57:37,  1.16s/it]

 37%|███▋      | 1736/4716 [33:33<57:38,  1.16s/it]

 37%|███▋      | 1737/4716 [33:34<57:38,  1.16s/it]

 37%|███▋      | 1738/4716 [33:35<57:36,  1.16s/it]

 37%|███▋      | 1739/4716 [33:36<57:34,  1.16s/it]

 37%|███▋      | 1740/4716 [33:37<57:33,  1.16s/it]

 37%|███▋      | 1741/4716 [33:38<57:32,  1.16s/it]

 37%|███▋      | 1742/4716 [33:39<57:28,  1.16s/it]

 37%|███▋      | 1743/4716 [33:41<57:27,  1.16s/it]

 37%|███▋      | 1744/4716 [33:42<57:27,  1.16s/it]

 37%|███▋      | 1745/4716 [33:43<57:26,  1.16s/it]

 37%|███▋      | 1746/4716 [33:44<57:25,  1.16s/it]

 37%|███▋      | 1747/4716 [33:45<57:26,  1.16s/it]

 37%|███▋      | 1748/4716 [33:46<57:25,  1.16s/it]

 37%|███▋      | 1749/4716 [33:48<57:19,  1.16s/it]

 37%|███▋      | 1750/4716 [33:49<57:28,  1.16s/it]

 37%|███▋      | 1751/4716 [33:50<57:21,  1.16s/it]

 37%|███▋      | 1752/4716 [33:51<57:22,  1.16s/it]

 37%|███▋      | 1753/4716 [33:52<57:15,  1.16s/it]

 37%|███▋      | 1754/4716 [33:53<57:13,  1.16s/it]

 37%|███▋      | 1755/4716 [33:55<57:15,  1.16s/it]

 37%|███▋      | 1756/4716 [33:56<57:17,  1.16s/it]

 37%|███▋      | 1757/4716 [33:57<57:20,  1.16s/it]

 37%|███▋      | 1758/4716 [33:58<57:18,  1.16s/it]

 37%|███▋      | 1759/4716 [33:59<57:15,  1.16s/it]

 37%|███▋      | 1760/4716 [34:00<57:13,  1.16s/it]

 37%|███▋      | 1761/4716 [34:02<57:10,  1.16s/it]

 37%|███▋      | 1762/4716 [34:03<57:07,  1.16s/it]

 37%|███▋      | 1763/4716 [34:04<57:07,  1.16s/it]

 37%|███▋      | 1764/4716 [34:05<57:05,  1.16s/it]

 37%|███▋      | 1765/4716 [34:06<57:03,  1.16s/it]

 37%|███▋      | 1766/4716 [34:07<57:00,  1.16s/it]

 37%|███▋      | 1767/4716 [34:09<56:58,  1.16s/it]

 37%|███▋      | 1768/4716 [34:10<56:56,  1.16s/it]

 38%|███▊      | 1769/4716 [34:11<56:53,  1.16s/it]

 38%|███▊      | 1770/4716 [34:12<56:52,  1.16s/it]

 38%|███▊      | 1771/4716 [34:13<56:49,  1.16s/it]

 38%|███▊      | 1772/4716 [34:14<56:49,  1.16s/it]

 38%|███▊      | 1773/4716 [34:15<56:49,  1.16s/it]

 38%|███▊      | 1774/4716 [34:17<56:50,  1.16s/it]

 38%|███▊      | 1775/4716 [34:18<56:49,  1.16s/it]

 38%|███▊      | 1776/4716 [34:19<56:47,  1.16s/it]

 38%|███▊      | 1777/4716 [34:20<56:47,  1.16s/it]

 38%|███▊      | 1778/4716 [34:21<56:43,  1.16s/it]

 38%|███▊      | 1779/4716 [34:22<56:41,  1.16s/it]

 38%|███▊      | 1780/4716 [34:24<56:41,  1.16s/it]

 38%|███▊      | 1781/4716 [34:25<56:41,  1.16s/it]

 38%|███▊      | 1782/4716 [34:26<56:41,  1.16s/it]

 38%|███▊      | 1783/4716 [34:27<56:40,  1.16s/it]

 38%|███▊      | 1784/4716 [34:28<56:42,  1.16s/it]

 38%|███▊      | 1785/4716 [34:29<56:38,  1.16s/it]

 38%|███▊      | 1786/4716 [34:31<56:37,  1.16s/it]

 38%|███▊      | 1787/4716 [34:32<56:39,  1.16s/it]

 38%|███▊      | 1788/4716 [34:33<56:35,  1.16s/it]

 38%|███▊      | 1789/4716 [34:34<56:34,  1.16s/it]

 38%|███▊      | 1790/4716 [34:35<56:33,  1.16s/it]

 38%|███▊      | 1791/4716 [34:36<56:30,  1.16s/it]

 38%|███▊      | 1792/4716 [34:37<56:27,  1.16s/it]

 38%|███▊      | 1793/4716 [34:39<56:28,  1.16s/it]

 38%|███▊      | 1794/4716 [34:40<56:29,  1.16s/it]

 38%|███▊      | 1795/4716 [34:41<56:29,  1.16s/it]

 38%|███▊      | 1796/4716 [34:42<56:24,  1.16s/it]

 38%|███▊      | 1797/4716 [34:43<56:23,  1.16s/it]

 38%|███▊      | 1798/4716 [34:44<56:23,  1.16s/it]

 38%|███▊      | 1799/4716 [34:46<56:22,  1.16s/it]

 38%|███▊      | 1800/4716 [34:47<56:21,  1.16s/it]

 38%|███▊      | 1801/4716 [34:48<56:22,  1.16s/it]

 38%|███▊      | 1802/4716 [34:49<56:22,  1.16s/it]

 38%|███▊      | 1803/4716 [34:50<56:19,  1.16s/it]

 38%|███▊      | 1804/4716 [34:51<56:19,  1.16s/it]

 38%|███▊      | 1805/4716 [34:53<56:18,  1.16s/it]

 38%|███▊      | 1806/4716 [34:54<56:15,  1.16s/it]

 38%|███▊      | 1807/4716 [34:55<56:15,  1.16s/it]

 38%|███▊      | 1808/4716 [34:56<56:11,  1.16s/it]

 38%|███▊      | 1809/4716 [34:57<56:11,  1.16s/it]

 38%|███▊      | 1810/4716 [34:58<56:08,  1.16s/it]

 38%|███▊      | 1811/4716 [35:00<56:04,  1.16s/it]

 38%|███▊      | 1812/4716 [35:01<56:06,  1.16s/it]

 38%|███▊      | 1813/4716 [35:02<56:05,  1.16s/it]

 38%|███▊      | 1814/4716 [35:03<56:02,  1.16s/it]

 38%|███▊      | 1815/4716 [35:04<56:06,  1.16s/it]

 39%|███▊      | 1816/4716 [35:05<56:07,  1.16s/it]

 39%|███▊      | 1817/4716 [35:06<56:04,  1.16s/it]

 39%|███▊      | 1818/4716 [35:08<56:03,  1.16s/it]

 39%|███▊      | 1819/4716 [35:09<56:02,  1.16s/it]

 39%|███▊      | 1820/4716 [35:10<55:59,  1.16s/it]

 39%|███▊      | 1821/4716 [35:11<55:59,  1.16s/it]

 39%|███▊      | 1822/4716 [35:12<55:57,  1.16s/it]

 39%|███▊      | 1823/4716 [35:13<55:56,  1.16s/it]

 39%|███▊      | 1824/4716 [35:15<55:52,  1.16s/it]

 39%|███▊      | 1825/4716 [35:16<55:51,  1.16s/it]

 39%|███▊      | 1826/4716 [35:17<55:47,  1.16s/it]

 39%|███▊      | 1827/4716 [35:18<55:45,  1.16s/it]

 39%|███▉      | 1828/4716 [35:19<55:44,  1.16s/it]

 39%|███▉      | 1829/4716 [35:20<55:47,  1.16s/it]

 39%|███▉      | 1830/4716 [35:22<55:48,  1.16s/it]

 39%|███▉      | 1831/4716 [35:23<55:46,  1.16s/it]

 39%|███▉      | 1832/4716 [35:24<55:45,  1.16s/it]

 39%|███▉      | 1833/4716 [35:25<55:44,  1.16s/it]

 39%|███▉      | 1834/4716 [35:26<55:43,  1.16s/it]

 39%|███▉      | 1835/4716 [35:27<55:41,  1.16s/it]

 39%|███▉      | 1836/4716 [35:29<55:39,  1.16s/it]

 39%|███▉      | 1837/4716 [35:30<55:35,  1.16s/it]

 39%|███▉      | 1838/4716 [35:31<55:35,  1.16s/it]

 39%|███▉      | 1839/4716 [35:32<55:36,  1.16s/it]

 39%|███▉      | 1840/4716 [35:33<55:38,  1.16s/it]

 39%|███▉      | 1841/4716 [35:34<55:36,  1.16s/it]

 39%|███▉      | 1842/4716 [35:35<55:38,  1.16s/it]

 39%|███▉      | 1843/4716 [35:37<55:38,  1.16s/it]

 39%|███▉      | 1844/4716 [35:38<55:38,  1.16s/it]

 39%|███▉      | 1845/4716 [35:39<55:33,  1.16s/it]

 39%|███▉      | 1846/4716 [35:40<55:31,  1.16s/it]

 39%|███▉      | 1847/4716 [35:41<55:26,  1.16s/it]

 39%|███▉      | 1848/4716 [35:42<55:25,  1.16s/it]

 39%|███▉      | 1849/4716 [35:44<55:22,  1.16s/it]

 39%|███▉      | 1850/4716 [35:45<55:20,  1.16s/it]

 39%|███▉      | 1851/4716 [35:46<55:19,  1.16s/it]

 39%|███▉      | 1852/4716 [35:47<55:19,  1.16s/it]

 39%|███▉      | 1853/4716 [35:48<55:17,  1.16s/it]

 39%|███▉      | 1854/4716 [35:49<55:16,  1.16s/it]

 39%|███▉      | 1855/4716 [35:51<55:19,  1.16s/it]

 39%|███▉      | 1856/4716 [35:52<55:19,  1.16s/it]

 39%|███▉      | 1857/4716 [35:53<55:20,  1.16s/it]

 39%|███▉      | 1858/4716 [35:54<55:19,  1.16s/it]

 39%|███▉      | 1859/4716 [35:55<55:16,  1.16s/it]

 39%|███▉      | 1860/4716 [35:56<55:15,  1.16s/it]

 39%|███▉      | 1861/4716 [35:58<55:14,  1.16s/it]

 39%|███▉      | 1862/4716 [35:59<55:12,  1.16s/it]

 40%|███▉      | 1863/4716 [36:00<55:12,  1.16s/it]

 40%|███▉      | 1864/4716 [36:01<55:10,  1.16s/it]

 40%|███▉      | 1865/4716 [36:02<55:06,  1.16s/it]

 40%|███▉      | 1866/4716 [36:03<55:08,  1.16s/it]

 40%|███▉      | 1867/4716 [36:04<55:13,  1.16s/it]

 40%|███▉      | 1868/4716 [36:06<55:06,  1.16s/it]

 40%|███▉      | 1869/4716 [36:07<55:04,  1.16s/it]

 40%|███▉      | 1870/4716 [36:08<55:04,  1.16s/it]

 40%|███▉      | 1871/4716 [36:09<55:01,  1.16s/it]

 40%|███▉      | 1872/4716 [36:10<55:04,  1.16s/it]

 40%|███▉      | 1873/4716 [36:11<55:02,  1.16s/it]

 40%|███▉      | 1874/4716 [36:13<55:05,  1.16s/it]

 40%|███▉      | 1875/4716 [36:14<55:05,  1.16s/it]

 40%|███▉      | 1876/4716 [36:15<55:03,  1.16s/it]

 40%|███▉      | 1877/4716 [36:16<55:01,  1.16s/it]

logging
logging the anndata

 40%|███▉      | 1878/4716 [36:17<56:16,  1.19s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 40%|███▉      | 1879/4716 [36:19<55:43,  1.18s/it]

 40%|███▉      | 1880/4716 [36:20<55:22,  1.17s/it]

 40%|███▉      | 1881/4716 [36:21<55:04,  1.17s/it]

 40%|███▉      | 1882/4716 [36:22<54:56,  1.16s/it]

 40%|███▉      | 1883/4716 [36:23<54:46,  1.16s/it]

 40%|███▉      | 1884/4716 [36:24<54:42,  1.16s/it]

 40%|███▉      | 1885/4716 [36:25<54:38,  1.16s/it]

 40%|███▉      | 1886/4716 [36:27<54:36,  1.16s/it]

 40%|████      | 1887/4716 [36:28<54:39,  1.16s/it]

 40%|████      | 1888/4716 [36:29<54:32,  1.16s/it]

 40%|████      | 1889/4716 [36:30<54:33,  1.16s/it]

 40%|████      | 1890/4716 [36:31<54:28,  1.16s/it]

 40%|████      | 1891/4716 [36:32<54:24,  1.16s/it]

 40%|████      | 1892/4716 [36:34<54:21,  1.15s/it]

 40%|████      | 1893/4716 [36:35<54:22,  1.16s/it]

 40%|████      | 1894/4716 [36:36<54:21,  1.16s/it]

 40%|████      | 1895/4716 [36:37<54:19,  1.16s/it]

 40%|████      | 1896/4716 [36:38<54:18,  1.16s/it]

 40%|████      | 1897/4716 [36:39<54:15,  1.15s/it]

 40%|████      | 1898/4716 [36:40<54:13,  1.15s/it]

 40%|████      | 1899/4716 [36:42<54:11,  1.15s/it]

 40%|████      | 1900/4716 [36:43<54:10,  1.15s/it]

 40%|████      | 1901/4716 [36:44<54:09,  1.15s/it]

 40%|████      | 1902/4716 [36:45<54:11,  1.16s/it]

 40%|████      | 1903/4716 [36:46<54:13,  1.16s/it]

 40%|████      | 1904/4716 [36:47<54:12,  1.16s/it]

 40%|████      | 1905/4716 [36:49<54:10,  1.16s/it]

 40%|████      | 1906/4716 [36:50<54:10,  1.16s/it]

 40%|████      | 1907/4716 [36:51<54:06,  1.16s/it]

 40%|████      | 1908/4716 [36:52<54:03,  1.16s/it]

 40%|████      | 1909/4716 [36:53<54:05,  1.16s/it]

 41%|████      | 1910/4716 [36:54<54:04,  1.16s/it]

 41%|████      | 1911/4716 [36:55<54:02,  1.16s/it]

 41%|████      | 1912/4716 [36:57<54:00,  1.16s/it]

 41%|████      | 1913/4716 [36:58<53:57,  1.16s/it]

 41%|████      | 1914/4716 [36:59<53:57,  1.16s/it]

 41%|████      | 1915/4716 [37:00<53:54,  1.15s/it]

 41%|████      | 1916/4716 [37:01<53:52,  1.15s/it]

 41%|████      | 1917/4716 [37:02<53:51,  1.15s/it]

 41%|████      | 1918/4716 [37:04<53:51,  1.16s/it]

 41%|████      | 1919/4716 [37:05<53:51,  1.16s/it]

 41%|████      | 1920/4716 [37:06<53:48,  1.15s/it]

 41%|████      | 1921/4716 [37:07<53:51,  1.16s/it]

 41%|████      | 1922/4716 [37:08<53:48,  1.16s/it]

 41%|████      | 1923/4716 [37:09<53:50,  1.16s/it]

 41%|████      | 1924/4716 [37:11<53:47,  1.16s/it]

 41%|████      | 1925/4716 [37:12<53:42,  1.15s/it]

 41%|████      | 1926/4716 [37:13<53:41,  1.15s/it]

 41%|████      | 1927/4716 [37:14<53:44,  1.16s/it]

 41%|████      | 1928/4716 [37:15<53:41,  1.16s/it]

 41%|████      | 1929/4716 [37:16<53:44,  1.16s/it]

 41%|████      | 1930/4716 [37:17<53:45,  1.16s/it]

 41%|████      | 1931/4716 [37:19<53:45,  1.16s/it]

 41%|████      | 1932/4716 [37:20<53:43,  1.16s/it]

 41%|████      | 1933/4716 [37:21<53:43,  1.16s/it]

 41%|████      | 1934/4716 [37:22<53:41,  1.16s/it]

 41%|████      | 1935/4716 [37:23<53:37,  1.16s/it]

 41%|████      | 1936/4716 [37:24<53:35,  1.16s/it]

 41%|████      | 1937/4716 [37:26<53:32,  1.16s/it]

 41%|████      | 1938/4716 [37:27<53:33,  1.16s/it]

 41%|████      | 1939/4716 [37:28<53:31,  1.16s/it]

 41%|████      | 1940/4716 [37:29<53:31,  1.16s/it]

 41%|████      | 1941/4716 [37:30<53:29,  1.16s/it]

 41%|████      | 1942/4716 [37:31<53:27,  1.16s/it]

 41%|████      | 1943/4716 [37:32<53:26,  1.16s/it]

 41%|████      | 1944/4716 [37:34<53:21,  1.15s/it]

 41%|████      | 1945/4716 [37:35<53:17,  1.15s/it]

 41%|████▏     | 1946/4716 [37:36<53:20,  1.16s/it]

 41%|████▏     | 1947/4716 [37:37<53:20,  1.16s/it]

 41%|████▏     | 1948/4716 [37:38<53:19,  1.16s/it]

 41%|████▏     | 1949/4716 [37:39<53:18,  1.16s/it]

 41%|████▏     | 1950/4716 [37:41<53:21,  1.16s/it]

 41%|████▏     | 1951/4716 [37:42<53:17,  1.16s/it]

 41%|████▏     | 1952/4716 [37:43<53:17,  1.16s/it]

 41%|████▏     | 1953/4716 [37:44<53:11,  1.16s/it]

 41%|████▏     | 1954/4716 [37:45<53:10,  1.16s/it]

 41%|████▏     | 1955/4716 [37:46<53:08,  1.15s/it]

 41%|████▏     | 1956/4716 [37:48<53:10,  1.16s/it]

 41%|████▏     | 1957/4716 [37:49<53:13,  1.16s/it]

 42%|████▏     | 1958/4716 [37:50<53:12,  1.16s/it]

 42%|████▏     | 1959/4716 [37:51<53:11,  1.16s/it]

 42%|████▏     | 1960/4716 [37:52<53:10,  1.16s/it]

 42%|████▏     | 1961/4716 [37:53<53:08,  1.16s/it]

 42%|████▏     | 1962/4716 [37:54<53:04,  1.16s/it]

 42%|████▏     | 1963/4716 [37:56<53:03,  1.16s/it]

 42%|████▏     | 1964/4716 [37:57<53:02,  1.16s/it]

 42%|████▏     | 1965/4716 [37:58<53:01,  1.16s/it]

 42%|████▏     | 1966/4716 [37:59<53:01,  1.16s/it]

 42%|████▏     | 1967/4716 [38:00<52:59,  1.16s/it]

 42%|████▏     | 1968/4716 [38:01<53:00,  1.16s/it]

 42%|████▏     | 1969/4716 [38:03<52:56,  1.16s/it]

 42%|████▏     | 1970/4716 [38:04<52:58,  1.16s/it]

 42%|████▏     | 1971/4716 [38:05<52:55,  1.16s/it]

 42%|████▏     | 1972/4716 [38:06<52:53,  1.16s/it]

 42%|████▏     | 1973/4716 [38:07<52:52,  1.16s/it]

 42%|████▏     | 1974/4716 [38:08<52:49,  1.16s/it]

 42%|████▏     | 1975/4716 [38:10<52:51,  1.16s/it]

 42%|████▏     | 1976/4716 [38:11<52:50,  1.16s/it]

 42%|████▏     | 1977/4716 [38:12<52:50,  1.16s/it]

 42%|████▏     | 1978/4716 [38:13<52:47,  1.16s/it]

 42%|████▏     | 1979/4716 [38:14<52:44,  1.16s/it]

 42%|████▏     | 1980/4716 [38:15<52:40,  1.16s/it]

 42%|████▏     | 1981/4716 [38:16<52:37,  1.15s/it]

 42%|████▏     | 1982/4716 [38:18<52:39,  1.16s/it]

 42%|████▏     | 1983/4716 [38:19<52:40,  1.16s/it]

 42%|████▏     | 1984/4716 [38:20<52:36,  1.16s/it]

 42%|████▏     | 1985/4716 [38:21<52:38,  1.16s/it]

 42%|████▏     | 1986/4716 [38:22<52:36,  1.16s/it]

 42%|████▏     | 1987/4716 [38:23<52:36,  1.16s/it]

 42%|████▏     | 1988/4716 [38:25<52:35,  1.16s/it]

 42%|████▏     | 1989/4716 [38:26<52:36,  1.16s/it]

 42%|████▏     | 1990/4716 [38:27<52:35,  1.16s/it]

 42%|████▏     | 1991/4716 [38:28<52:33,  1.16s/it]

 42%|████▏     | 1992/4716 [38:29<52:33,  1.16s/it]

 42%|████▏     | 1993/4716 [38:30<52:26,  1.16s/it]

 42%|████▏     | 1994/4716 [38:31<52:23,  1.15s/it]

 42%|████▏     | 1995/4716 [38:33<52:22,  1.16s/it]

 42%|████▏     | 1996/4716 [38:34<52:22,  1.16s/it]

 42%|████▏     | 1997/4716 [38:35<52:22,  1.16s/it]

 42%|████▏     | 1998/4716 [38:36<52:22,  1.16s/it]

 42%|████▏     | 1999/4716 [38:37<52:20,  1.16s/it]

 42%|████▏     | 2000/4716 [38:38<52:17,  1.16s/it]

 42%|████▏     | 2001/4716 [38:40<52:18,  1.16s/it]

 42%|████▏     | 2002/4716 [38:41<52:17,  1.16s/it]

 42%|████▏     | 2003/4716 [38:42<52:15,  1.16s/it]

 42%|████▏     | 2004/4716 [38:43<52:16,  1.16s/it]

 43%|████▎     | 2005/4716 [38:44<52:14,  1.16s/it]

 43%|████▎     | 2006/4716 [38:45<52:12,  1.16s/it]

 43%|████▎     | 2007/4716 [38:46<52:12,  1.16s/it]

 43%|████▎     | 2008/4716 [38:48<52:12,  1.16s/it]

 43%|████▎     | 2009/4716 [38:49<52:10,  1.16s/it]

 43%|████▎     | 2010/4716 [38:50<52:04,  1.15s/it]

 43%|████▎     | 2011/4716 [38:51<52:06,  1.16s/it]

 43%|████▎     | 2012/4716 [38:52<52:02,  1.15s/it]

 43%|████▎     | 2013/4716 [38:53<52:04,  1.16s/it]

 43%|████▎     | 2014/4716 [38:55<52:05,  1.16s/it]

 43%|████▎     | 2015/4716 [38:56<52:03,  1.16s/it]

 43%|████▎     | 2016/4716 [38:57<52:07,  1.16s/it]

 43%|████▎     | 2017/4716 [38:58<52:04,  1.16s/it]

 43%|████▎     | 2018/4716 [38:59<51:59,  1.16s/it]

 43%|████▎     | 2019/4716 [39:00<51:57,  1.16s/it]

 43%|████▎     | 2020/4716 [39:02<51:56,  1.16s/it]

 43%|████▎     | 2021/4716 [39:03<51:57,  1.16s/it]

 43%|████▎     | 2022/4716 [39:04<51:57,  1.16s/it]

 43%|████▎     | 2023/4716 [39:05<51:57,  1.16s/it]

 43%|████▎     | 2024/4716 [39:06<51:55,  1.16s/it]

 43%|████▎     | 2025/4716 [39:07<51:53,  1.16s/it]

 43%|████▎     | 2026/4716 [39:08<51:49,  1.16s/it]

 43%|████▎     | 2027/4716 [39:10<51:47,  1.16s/it]

 43%|████▎     | 2028/4716 [39:11<51:46,  1.16s/it]

 43%|████▎     | 2029/4716 [39:12<51:47,  1.16s/it]

 43%|████▎     | 2030/4716 [39:13<51:43,  1.16s/it]

 43%|████▎     | 2031/4716 [39:14<51:43,  1.16s/it]

 43%|████▎     | 2032/4716 [39:15<51:45,  1.16s/it]

 43%|████▎     | 2033/4716 [39:17<51:44,  1.16s/it]

 43%|████▎     | 2034/4716 [39:18<51:44,  1.16s/it]

 43%|████▎     | 2035/4716 [39:19<51:43,  1.16s/it]

 43%|████▎     | 2036/4716 [39:20<51:39,  1.16s/it]

 43%|████▎     | 2037/4716 [39:21<51:36,  1.16s/it]

 43%|████▎     | 2038/4716 [39:22<51:33,  1.16s/it]

 43%|████▎     | 2039/4716 [39:24<51:34,  1.16s/it]

 43%|████▎     | 2040/4716 [39:25<51:33,  1.16s/it]

 43%|████▎     | 2041/4716 [39:26<51:35,  1.16s/it]

 43%|████▎     | 2042/4716 [39:27<51:34,  1.16s/it]

 43%|████▎     | 2043/4716 [39:28<51:33,  1.16s/it]

 43%|████▎     | 2044/4716 [39:29<51:32,  1.16s/it]

 43%|████▎     | 2045/4716 [39:30<51:30,  1.16s/it]

 43%|████▎     | 2046/4716 [39:32<51:30,  1.16s/it]

 43%|████▎     | 2047/4716 [39:33<51:30,  1.16s/it]

 43%|████▎     | 2048/4716 [39:34<51:28,  1.16s/it]

 43%|████▎     | 2049/4716 [39:35<51:27,  1.16s/it]

 43%|████▎     | 2050/4716 [39:36<51:25,  1.16s/it]

 43%|████▎     | 2051/4716 [39:37<51:23,  1.16s/it]

 44%|████▎     | 2052/4716 [39:39<51:19,  1.16s/it]

 44%|████▎     | 2053/4716 [39:40<51:18,  1.16s/it]

 44%|████▎     | 2054/4716 [39:41<51:18,  1.16s/it]

 44%|████▎     | 2055/4716 [39:42<51:15,  1.16s/it]

 44%|████▎     | 2056/4716 [39:43<51:18,  1.16s/it]

 44%|████▎     | 2057/4716 [39:44<51:15,  1.16s/it]

 44%|████▎     | 2058/4716 [39:45<51:13,  1.16s/it]

 44%|████▎     | 2059/4716 [39:47<51:09,  1.16s/it]

 44%|████▎     | 2060/4716 [39:48<51:08,  1.16s/it]

 44%|████▎     | 2061/4716 [39:49<51:07,  1.16s/it]

 44%|████▎     | 2062/4716 [39:50<51:11,  1.16s/it]

 44%|████▎     | 2063/4716 [39:51<51:10,  1.16s/it]

 44%|████▍     | 2064/4716 [39:52<51:09,  1.16s/it]

 44%|████▍     | 2065/4716 [39:54<51:07,  1.16s/it]

 44%|████▍     | 2066/4716 [39:55<51:06,  1.16s/it]

 44%|████▍     | 2067/4716 [39:56<51:02,  1.16s/it]

 44%|████▍     | 2068/4716 [39:57<50:59,  1.16s/it]

 44%|████▍     | 2069/4716 [39:58<50:59,  1.16s/it]

 44%|████▍     | 2070/4716 [39:59<50:59,  1.16s/it]

 44%|████▍     | 2071/4716 [40:01<50:57,  1.16s/it]

 44%|████▍     | 2072/4716 [40:02<50:58,  1.16s/it]

 44%|████▍     | 2073/4716 [40:03<50:58,  1.16s/it]

 44%|████▍     | 2074/4716 [40:04<50:57,  1.16s/it]

 44%|████▍     | 2075/4716 [40:05<50:55,  1.16s/it]

 44%|████▍     | 2076/4716 [40:06<50:53,  1.16s/it]

 44%|████▍     | 2077/4716 [40:07<50:50,  1.16s/it]

 44%|████▍     | 2078/4716 [40:09<50:48,  1.16s/it]

 44%|████▍     | 2079/4716 [40:10<50:48,  1.16s/it]

 44%|████▍     | 2080/4716 [40:11<50:53,  1.16s/it]

 44%|████▍     | 2081/4716 [40:12<50:51,  1.16s/it]

 44%|████▍     | 2082/4716 [40:13<50:50,  1.16s/it]

 44%|████▍     | 2083/4716 [40:14<50:49,  1.16s/it]

 44%|████▍     | 2084/4716 [40:16<50:49,  1.16s/it]

 44%|████▍     | 2085/4716 [40:17<50:47,  1.16s/it]

 44%|████▍     | 2086/4716 [40:18<50:42,  1.16s/it]

 44%|████▍     | 2087/4716 [40:19<50:43,  1.16s/it]

 44%|████▍     | 2088/4716 [40:20<50:39,  1.16s/it]

 44%|████▍     | 2089/4716 [40:21<50:41,  1.16s/it]

 44%|████▍     | 2090/4716 [40:23<50:41,  1.16s/it]

 44%|████▍     | 2091/4716 [40:24<50:42,  1.16s/it]

 44%|████▍     | 2092/4716 [40:25<50:39,  1.16s/it]

 44%|████▍     | 2093/4716 [40:26<50:36,  1.16s/it]

 44%|████▍     | 2094/4716 [40:27<50:36,  1.16s/it]

 44%|████▍     | 2095/4716 [40:28<50:31,  1.16s/it]

 44%|████▍     | 2096/4716 [40:29<50:32,  1.16s/it]

 44%|████▍     | 2097/4716 [40:31<50:32,  1.16s/it]

 44%|████▍     | 2098/4716 [40:32<50:31,  1.16s/it]

 45%|████▍     | 2099/4716 [40:33<50:30,  1.16s/it]

 45%|████▍     | 2100/4716 [40:34<50:29,  1.16s/it]

 45%|████▍     | 2101/4716 [40:35<50:24,  1.16s/it]

 45%|████▍     | 2102/4716 [40:36<50:25,  1.16s/it]

 45%|████▍     | 2103/4716 [40:38<50:27,  1.16s/it]

 45%|████▍     | 2104/4716 [40:39<50:24,  1.16s/it]

 45%|████▍     | 2105/4716 [40:40<50:25,  1.16s/it]

 45%|████▍     | 2106/4716 [40:41<50:26,  1.16s/it]

 45%|████▍     | 2107/4716 [40:42<50:26,  1.16s/it]

 45%|████▍     | 2108/4716 [40:43<50:29,  1.16s/it]

 45%|████▍     | 2109/4716 [40:45<50:26,  1.16s/it]

 45%|████▍     | 2110/4716 [40:46<50:19,  1.16s/it]

 45%|████▍     | 2111/4716 [40:47<50:14,  1.16s/it]

 45%|████▍     | 2112/4716 [40:48<50:14,  1.16s/it]

 45%|████▍     | 2113/4716 [40:49<50:11,  1.16s/it]

 45%|████▍     | 2114/4716 [40:50<50:13,  1.16s/it]

 45%|████▍     | 2115/4716 [40:51<50:11,  1.16s/it]

 45%|████▍     | 2116/4716 [40:53<50:10,  1.16s/it]

 45%|████▍     | 2117/4716 [40:54<50:08,  1.16s/it]

 45%|████▍     | 2118/4716 [40:55<50:05,  1.16s/it]

 45%|████▍     | 2119/4716 [40:56<50:03,  1.16s/it]

 45%|████▍     | 2120/4716 [40:57<50:01,  1.16s/it]

 45%|████▍     | 2121/4716 [40:58<50:03,  1.16s/it]

 45%|████▍     | 2122/4716 [41:00<50:02,  1.16s/it]

 45%|████▌     | 2123/4716 [41:01<50:03,  1.16s/it]

 45%|████▌     | 2124/4716 [41:02<50:03,  1.16s/it]

 45%|████▌     | 2125/4716 [41:03<50:02,  1.16s/it]

 45%|████▌     | 2126/4716 [41:04<50:01,  1.16s/it]

 45%|████▌     | 2127/4716 [41:05<49:59,  1.16s/it]

 45%|████▌     | 2128/4716 [41:07<49:56,  1.16s/it]

 45%|████▌     | 2129/4716 [41:08<49:53,  1.16s/it]

 45%|████▌     | 2130/4716 [41:09<49:51,  1.16s/it]

 45%|████▌     | 2131/4716 [41:10<49:52,  1.16s/it]

 45%|████▌     | 2132/4716 [41:11<49:53,  1.16s/it]

 45%|████▌     | 2133/4716 [41:12<49:53,  1.16s/it]

 45%|████▌     | 2134/4716 [41:13<49:51,  1.16s/it]

 45%|████▌     | 2135/4716 [41:15<49:48,  1.16s/it]

 45%|████▌     | 2136/4716 [41:16<49:52,  1.16s/it]

 45%|████▌     | 2137/4716 [41:17<49:49,  1.16s/it]

 45%|████▌     | 2138/4716 [41:18<49:45,  1.16s/it]

 45%|████▌     | 2139/4716 [41:19<49:41,  1.16s/it]

 45%|████▌     | 2140/4716 [41:20<49:38,  1.16s/it]

 45%|████▌     | 2141/4716 [41:22<49:38,  1.16s/it]

 45%|████▌     | 2142/4716 [41:23<49:38,  1.16s/it]

 45%|████▌     | 2143/4716 [41:24<49:38,  1.16s/it]

 45%|████▌     | 2144/4716 [41:25<49:37,  1.16s/it]

 45%|████▌     | 2145/4716 [41:26<49:38,  1.16s/it]

 46%|████▌     | 2146/4716 [41:27<49:39,  1.16s/it]

 46%|████▌     | 2147/4716 [41:29<49:35,  1.16s/it]

 46%|████▌     | 2148/4716 [41:30<49:33,  1.16s/it]

 46%|████▌     | 2149/4716 [41:31<49:31,  1.16s/it]

 46%|████▌     | 2150/4716 [41:32<49:28,  1.16s/it]

 46%|████▌     | 2151/4716 [41:33<49:28,  1.16s/it]

 46%|████▌     | 2152/4716 [41:34<49:28,  1.16s/it]

 46%|████▌     | 2153/4716 [41:35<49:25,  1.16s/it]

 46%|████▌     | 2154/4716 [41:37<49:25,  1.16s/it]

 46%|████▌     | 2155/4716 [41:38<49:29,  1.16s/it]

 46%|████▌     | 2156/4716 [41:39<49:30,  1.16s/it]

 46%|████▌     | 2157/4716 [41:40<49:25,  1.16s/it]

 46%|████▌     | 2158/4716 [41:41<49:22,  1.16s/it]

 46%|████▌     | 2159/4716 [41:42<49:19,  1.16s/it]

 46%|████▌     | 2160/4716 [41:44<49:16,  1.16s/it]

 46%|████▌     | 2161/4716 [41:45<49:15,  1.16s/it]

 46%|████▌     | 2162/4716 [41:46<49:18,  1.16s/it]

 46%|████▌     | 2163/4716 [41:47<49:19,  1.16s/it]

 46%|████▌     | 2164/4716 [41:48<49:17,  1.16s/it]

 46%|████▌     | 2165/4716 [41:49<49:15,  1.16s/it]

 46%|████▌     | 2166/4716 [41:51<49:13,  1.16s/it]

 46%|████▌     | 2167/4716 [41:52<49:10,  1.16s/it]

 46%|████▌     | 2168/4716 [41:53<49:08,  1.16s/it]

 46%|████▌     | 2169/4716 [41:54<49:07,  1.16s/it]

 46%|████▌     | 2170/4716 [41:55<49:04,  1.16s/it]

 46%|████▌     | 2171/4716 [41:56<49:02,  1.16s/it]

 46%|████▌     | 2172/4716 [41:57<49:02,  1.16s/it]

 46%|████▌     | 2173/4716 [41:59<49:00,  1.16s/it]

 46%|████▌     | 2174/4716 [42:00<49:01,  1.16s/it]

 46%|████▌     | 2175/4716 [42:01<49:02,  1.16s/it]

 46%|████▌     | 2176/4716 [42:02<49:00,  1.16s/it]

 46%|████▌     | 2177/4716 [42:03<48:58,  1.16s/it]

 46%|████▌     | 2178/4716 [42:04<48:59,  1.16s/it]

 46%|████▌     | 2179/4716 [42:06<48:57,  1.16s/it]

 46%|████▌     | 2180/4716 [42:07<48:54,  1.16s/it]

 46%|████▌     | 2181/4716 [42:08<48:50,  1.16s/it]

 46%|████▋     | 2182/4716 [42:09<48:49,  1.16s/it]

 46%|████▋     | 2183/4716 [42:10<48:50,  1.16s/it]

 46%|████▋     | 2184/4716 [42:11<48:50,  1.16s/it]

 46%|████▋     | 2185/4716 [42:13<48:48,  1.16s/it]

 46%|████▋     | 2186/4716 [42:14<48:47,  1.16s/it]

 46%|████▋     | 2187/4716 [42:15<48:49,  1.16s/it]

 46%|████▋     | 2188/4716 [42:16<48:49,  1.16s/it]

 46%|████▋     | 2189/4716 [42:17<48:47,  1.16s/it]

 46%|████▋     | 2190/4716 [42:18<48:46,  1.16s/it]

 46%|████▋     | 2191/4716 [42:19<48:41,  1.16s/it]

 46%|████▋     | 2192/4716 [42:21<48:40,  1.16s/it]

 47%|████▋     | 2193/4716 [42:22<48:40,  1.16s/it]

 47%|████▋     | 2194/4716 [42:23<48:39,  1.16s/it]

 47%|████▋     | 2195/4716 [42:24<48:40,  1.16s/it]

 47%|████▋     | 2196/4716 [42:25<48:39,  1.16s/it]

 47%|████▋     | 2197/4716 [42:26<48:38,  1.16s/it]

 47%|████▋     | 2198/4716 [42:28<48:34,  1.16s/it]

 47%|████▋     | 2199/4716 [42:29<48:35,  1.16s/it]

 47%|████▋     | 2200/4716 [42:30<48:31,  1.16s/it]

 47%|████▋     | 2201/4716 [42:31<48:30,  1.16s/it]

 47%|████▋     | 2202/4716 [42:32<48:28,  1.16s/it]

 47%|████▋     | 2203/4716 [42:33<48:29,  1.16s/it]

 47%|████▋     | 2204/4716 [42:35<48:30,  1.16s/it]

 47%|████▋     | 2205/4716 [42:36<48:32,  1.16s/it]

 47%|████▋     | 2206/4716 [42:37<48:29,  1.16s/it]

 47%|████▋     | 2207/4716 [42:38<48:28,  1.16s/it]

 47%|████▋     | 2208/4716 [42:39<48:25,  1.16s/it]

 47%|████▋     | 2209/4716 [42:40<48:22,  1.16s/it]

 47%|████▋     | 2210/4716 [42:41<48:22,  1.16s/it]

 47%|████▋     | 2211/4716 [42:43<48:21,  1.16s/it]

 47%|████▋     | 2212/4716 [42:44<48:17,  1.16s/it]

 47%|████▋     | 2213/4716 [42:45<48:18,  1.16s/it]

 47%|████▋     | 2214/4716 [42:46<48:21,  1.16s/it]

 47%|████▋     | 2215/4716 [42:47<48:21,  1.16s/it]

 47%|████▋     | 2216/4716 [42:48<48:20,  1.16s/it]

 47%|████▋     | 2217/4716 [42:50<48:20,  1.16s/it]

 47%|████▋     | 2218/4716 [42:51<48:20,  1.16s/it]

 47%|████▋     | 2219/4716 [42:52<48:17,  1.16s/it]

 47%|████▋     | 2220/4716 [42:53<48:12,  1.16s/it]

 47%|████▋     | 2221/4716 [42:54<48:14,  1.16s/it]

 47%|████▋     | 2222/4716 [42:55<48:14,  1.16s/it]

 47%|████▋     | 2223/4716 [42:57<48:13,  1.16s/it]

 47%|████▋     | 2224/4716 [42:58<48:15,  1.16s/it]

 47%|████▋     | 2225/4716 [42:59<48:09,  1.16s/it]

 47%|████▋     | 2226/4716 [43:00<48:06,  1.16s/it]

 47%|████▋     | 2227/4716 [43:01<48:04,  1.16s/it]

 47%|████▋     | 2228/4716 [43:02<48:04,  1.16s/it]

 47%|████▋     | 2229/4716 [43:03<48:02,  1.16s/it]

 47%|████▋     | 2230/4716 [43:05<48:01,  1.16s/it]

 47%|████▋     | 2231/4716 [43:06<47:59,  1.16s/it]

 47%|████▋     | 2232/4716 [43:07<47:55,  1.16s/it]

 47%|████▋     | 2233/4716 [43:08<47:55,  1.16s/it]

 47%|████▋     | 2234/4716 [43:09<47:56,  1.16s/it]

 47%|████▋     | 2235/4716 [43:10<47:53,  1.16s/it]

 47%|████▋     | 2236/4716 [43:12<47:52,  1.16s/it]

 47%|████▋     | 2237/4716 [43:13<47:50,  1.16s/it]

 47%|████▋     | 2238/4716 [43:14<47:49,  1.16s/it]

 47%|████▋     | 2239/4716 [43:15<47:49,  1.16s/it]

 47%|████▋     | 2240/4716 [43:16<47:48,  1.16s/it]

 48%|████▊     | 2241/4716 [43:17<47:46,  1.16s/it]

 48%|████▊     | 2242/4716 [43:19<47:43,  1.16s/it]

 48%|████▊     | 2243/4716 [43:20<47:44,  1.16s/it]

 48%|████▊     | 2244/4716 [43:21<47:42,  1.16s/it]

 48%|████▊     | 2245/4716 [43:22<47:39,  1.16s/it]

 48%|████▊     | 2246/4716 [43:23<47:37,  1.16s/it]

 48%|████▊     | 2247/4716 [43:24<47:35,  1.16s/it]

 48%|████▊     | 2248/4716 [43:25<47:37,  1.16s/it]

 48%|████▊     | 2249/4716 [43:27<47:39,  1.16s/it]

 48%|████▊     | 2250/4716 [43:28<47:38,  1.16s/it]

 48%|████▊     | 2251/4716 [43:29<47:37,  1.16s/it]

 48%|████▊     | 2252/4716 [43:30<47:35,  1.16s/it]

 48%|████▊     | 2253/4716 [43:31<47:35,  1.16s/it]

 48%|████▊     | 2254/4716 [43:32<47:34,  1.16s/it]

 48%|████▊     | 2255/4716 [43:34<47:29,  1.16s/it]

 48%|████▊     | 2256/4716 [43:35<47:27,  1.16s/it]

 48%|████▊     | 2257/4716 [43:36<47:27,  1.16s/it]

 48%|████▊     | 2258/4716 [43:37<47:27,  1.16s/it]

 48%|████▊     | 2259/4716 [43:38<47:26,  1.16s/it]

 48%|████▊     | 2260/4716 [43:39<47:27,  1.16s/it]

 48%|████▊     | 2261/4716 [43:41<47:24,  1.16s/it]

 48%|████▊     | 2262/4716 [43:42<47:22,  1.16s/it]

 48%|████▊     | 2263/4716 [43:43<47:23,  1.16s/it]

 48%|████▊     | 2264/4716 [43:44<47:22,  1.16s/it]

 48%|████▊     | 2265/4716 [43:45<47:22,  1.16s/it]

 48%|████▊     | 2266/4716 [43:46<47:19,  1.16s/it]

 48%|████▊     | 2267/4716 [43:48<47:18,  1.16s/it]

 48%|████▊     | 2268/4716 [43:49<47:18,  1.16s/it]

 48%|████▊     | 2269/4716 [43:50<47:18,  1.16s/it]

 48%|████▊     | 2270/4716 [43:51<47:16,  1.16s/it]

 48%|████▊     | 2271/4716 [43:52<47:14,  1.16s/it]

 48%|████▊     | 2272/4716 [43:53<47:14,  1.16s/it]

 48%|████▊     | 2273/4716 [43:54<47:13,  1.16s/it]

 48%|████▊     | 2274/4716 [43:56<47:12,  1.16s/it]

 48%|████▊     | 2275/4716 [43:57<47:10,  1.16s/it]

 48%|████▊     | 2276/4716 [43:58<47:08,  1.16s/it]

 48%|████▊     | 2277/4716 [43:59<47:07,  1.16s/it]

 48%|████▊     | 2278/4716 [44:00<47:09,  1.16s/it]

 48%|████▊     | 2279/4716 [44:01<47:11,  1.16s/it]

 48%|████▊     | 2280/4716 [44:03<47:07,  1.16s/it]

 48%|████▊     | 2281/4716 [44:04<47:06,  1.16s/it]

 48%|████▊     | 2282/4716 [44:05<46:59,  1.16s/it]

 48%|████▊     | 2283/4716 [44:06<46:59,  1.16s/it]

 48%|████▊     | 2284/4716 [44:07<46:58,  1.16s/it]

 48%|████▊     | 2285/4716 [44:08<46:59,  1.16s/it]

 48%|████▊     | 2286/4716 [44:10<46:55,  1.16s/it]

 48%|████▊     | 2287/4716 [44:11<46:56,  1.16s/it]

 49%|████▊     | 2288/4716 [44:12<46:54,  1.16s/it]

 49%|████▊     | 2289/4716 [44:13<46:53,  1.16s/it]

 49%|████▊     | 2290/4716 [44:14<46:49,  1.16s/it]

 49%|████▊     | 2291/4716 [44:15<46:47,  1.16s/it]

 49%|████▊     | 2292/4716 [44:16<46:45,  1.16s/it]

 49%|████▊     | 2293/4716 [44:18<46:47,  1.16s/it]

 49%|████▊     | 2294/4716 [44:19<46:47,  1.16s/it]

 49%|████▊     | 2295/4716 [44:20<46:47,  1.16s/it]

 49%|████▊     | 2296/4716 [44:21<46:46,  1.16s/it]

 49%|████▊     | 2297/4716 [44:22<46:44,  1.16s/it]

 49%|████▊     | 2298/4716 [44:23<46:41,  1.16s/it]

 49%|████▊     | 2299/4716 [44:25<46:43,  1.16s/it]

 49%|████▉     | 2300/4716 [44:26<46:42,  1.16s/it]

 49%|████▉     | 2301/4716 [44:27<46:38,  1.16s/it]

 49%|████▉     | 2302/4716 [44:28<46:38,  1.16s/it]

 49%|████▉     | 2303/4716 [44:29<46:36,  1.16s/it]

 49%|████▉     | 2304/4716 [44:30<46:36,  1.16s/it]

 49%|████▉     | 2305/4716 [44:32<46:34,  1.16s/it]

 49%|████▉     | 2306/4716 [44:33<46:32,  1.16s/it]

 49%|████▉     | 2307/4716 [44:34<46:31,  1.16s/it]

 49%|████▉     | 2308/4716 [44:35<46:32,  1.16s/it]

 49%|████▉     | 2309/4716 [44:36<46:31,  1.16s/it]

 49%|████▉     | 2310/4716 [44:37<46:30,  1.16s/it]

 49%|████▉     | 2311/4716 [44:39<46:28,  1.16s/it]

 49%|████▉     | 2312/4716 [44:40<46:23,  1.16s/it]

 49%|████▉     | 2313/4716 [44:41<46:22,  1.16s/it]

 49%|████▉     | 2314/4716 [44:42<46:22,  1.16s/it]

 49%|████▉     | 2315/4716 [44:43<46:23,  1.16s/it]

 49%|████▉     | 2316/4716 [44:44<46:20,  1.16s/it]

 49%|████▉     | 2317/4716 [44:45<46:19,  1.16s/it]

 49%|████▉     | 2318/4716 [44:47<46:21,  1.16s/it]

 49%|████▉     | 2319/4716 [44:48<46:20,  1.16s/it]

 49%|████▉     | 2320/4716 [44:49<46:16,  1.16s/it]

 49%|████▉     | 2321/4716 [44:50<46:17,  1.16s/it]

 49%|████▉     | 2322/4716 [44:51<46:15,  1.16s/it]

 49%|████▉     | 2323/4716 [44:52<46:14,  1.16s/it]

 49%|████▉     | 2324/4716 [44:54<46:09,  1.16s/it]

 49%|████▉     | 2325/4716 [44:55<46:09,  1.16s/it]

 49%|████▉     | 2326/4716 [44:56<46:09,  1.16s/it]

 49%|████▉     | 2327/4716 [44:57<46:10,  1.16s/it]

 49%|████▉     | 2328/4716 [44:58<46:07,  1.16s/it]

 49%|████▉     | 2329/4716 [44:59<46:05,  1.16s/it]

 49%|████▉     | 2330/4716 [45:01<46:04,  1.16s/it]

 49%|████▉     | 2331/4716 [45:02<46:01,  1.16s/it]

 49%|████▉     | 2332/4716 [45:03<45:59,  1.16s/it]

 49%|████▉     | 2333/4716 [45:04<45:57,  1.16s/it]

 49%|████▉     | 2334/4716 [45:05<45:55,  1.16s/it]

 50%|████▉     | 2335/4716 [45:06<45:55,  1.16s/it]

 50%|████▉     | 2336/4716 [45:07<45:56,  1.16s/it]

 50%|████▉     | 2337/4716 [45:09<45:56,  1.16s/it]

 50%|████▉     | 2338/4716 [45:10<45:55,  1.16s/it]

 50%|████▉     | 2339/4716 [45:11<45:56,  1.16s/it]

 50%|████▉     | 2340/4716 [45:12<45:56,  1.16s/it]

 50%|████▉     | 2341/4716 [45:13<45:53,  1.16s/it]

 50%|████▉     | 2342/4716 [45:14<45:50,  1.16s/it]

 50%|████▉     | 2343/4716 [45:16<45:52,  1.16s/it]

 50%|████▉     | 2344/4716 [45:17<45:49,  1.16s/it]

 50%|████▉     | 2345/4716 [45:18<45:47,  1.16s/it]

 50%|████▉     | 2346/4716 [45:19<45:45,  1.16s/it]

 50%|████▉     | 2347/4716 [45:20<45:42,  1.16s/it]

 50%|████▉     | 2348/4716 [45:21<45:43,  1.16s/it]

 50%|████▉     | 2349/4716 [45:23<45:46,  1.16s/it]

 50%|████▉     | 2350/4716 [45:24<45:44,  1.16s/it]

 50%|████▉     | 2351/4716 [45:25<45:43,  1.16s/it]

 50%|████▉     | 2352/4716 [45:26<45:44,  1.16s/it]

 50%|████▉     | 2353/4716 [45:27<45:43,  1.16s/it]

 50%|████▉     | 2354/4716 [45:28<45:45,  1.16s/it]

 50%|████▉     | 2355/4716 [45:30<45:42,  1.16s/it]

 50%|████▉     | 2356/4716 [45:31<45:39,  1.16s/it]

 50%|████▉     | 2357/4716 [45:32<45:36,  1.16s/it]

 50%|█████     | 2358/4716 [45:33<45:36,  1.16s/it]

 50%|█████     | 2359/4716 [45:34<45:35,  1.16s/it]

 50%|█████     | 2360/4716 [45:35<45:34,  1.16s/it]

 50%|█████     | 2361/4716 [45:36<45:32,  1.16s/it]

 50%|█████     | 2362/4716 [45:38<45:33,  1.16s/it]

 50%|█████     | 2363/4716 [45:39<45:31,  1.16s/it]

 50%|█████     | 2364/4716 [45:40<45:30,  1.16s/it]

 50%|█████     | 2365/4716 [45:41<45:28,  1.16s/it]

 50%|█████     | 2366/4716 [45:42<45:28,  1.16s/it]

 50%|█████     | 2367/4716 [45:43<45:27,  1.16s/it]

 50%|█████     | 2368/4716 [45:45<45:26,  1.16s/it]

 50%|█████     | 2369/4716 [45:46<45:24,  1.16s/it]

 50%|█████     | 2370/4716 [45:47<45:21,  1.16s/it]

 50%|█████     | 2371/4716 [45:48<45:19,  1.16s/it]

 50%|█████     | 2372/4716 [45:49<45:19,  1.16s/it]

 50%|█████     | 2373/4716 [45:50<45:19,  1.16s/it]

 50%|█████     | 2374/4716 [45:52<45:19,  1.16s/it]

 50%|█████     | 2375/4716 [45:53<45:18,  1.16s/it]

 50%|█████     | 2376/4716 [45:54<45:14,  1.16s/it]

 50%|█████     | 2377/4716 [45:55<45:17,  1.16s/it]

 50%|█████     | 2378/4716 [45:56<45:15,  1.16s/it]

 50%|█████     | 2379/4716 [45:57<45:13,  1.16s/it]

 50%|█████     | 2380/4716 [45:59<45:12,  1.16s/it]

 50%|█████     | 2381/4716 [46:00<45:09,  1.16s/it]

 51%|█████     | 2382/4716 [46:01<45:06,  1.16s/it]

 51%|█████     | 2383/4716 [46:02<45:05,  1.16s/it]

 51%|█████     | 2384/4716 [46:03<45:06,  1.16s/it]

 51%|█████     | 2385/4716 [46:04<45:05,  1.16s/it]

 51%|█████     | 2386/4716 [46:06<45:04,  1.16s/it]

 51%|█████     | 2387/4716 [46:07<45:03,  1.16s/it]

 51%|█████     | 2388/4716 [46:08<45:01,  1.16s/it]

 51%|█████     | 2389/4716 [46:09<44:58,  1.16s/it]

 51%|█████     | 2390/4716 [46:10<44:58,  1.16s/it]

 51%|█████     | 2391/4716 [46:11<44:55,  1.16s/it]

 51%|█████     | 2392/4716 [46:12<44:54,  1.16s/it]

 51%|█████     | 2393/4716 [46:14<44:54,  1.16s/it]

 51%|█████     | 2394/4716 [46:15<44:55,  1.16s/it]

 51%|█████     | 2395/4716 [46:16<44:56,  1.16s/it]

 51%|█████     | 2396/4716 [46:17<44:55,  1.16s/it]

 51%|█████     | 2397/4716 [46:18<44:53,  1.16s/it]

 51%|█████     | 2398/4716 [46:19<44:51,  1.16s/it]

 51%|█████     | 2399/4716 [46:21<44:47,  1.16s/it]

 51%|█████     | 2400/4716 [46:22<44:46,  1.16s/it]

 51%|█████     | 2401/4716 [46:23<44:45,  1.16s/it]

 51%|█████     | 2402/4716 [46:24<44:42,  1.16s/it]

 51%|█████     | 2403/4716 [46:25<44:42,  1.16s/it]

 51%|█████     | 2404/4716 [46:26<44:43,  1.16s/it]

 51%|█████     | 2405/4716 [46:28<44:40,  1.16s/it]

 51%|█████     | 2406/4716 [46:29<44:40,  1.16s/it]

 51%|█████     | 2407/4716 [46:30<44:40,  1.16s/it]

 51%|█████     | 2408/4716 [46:31<44:39,  1.16s/it]

 51%|█████     | 2409/4716 [46:32<44:36,  1.16s/it]

 51%|█████     | 2410/4716 [46:33<44:37,  1.16s/it]

 51%|█████     | 2411/4716 [46:35<44:37,  1.16s/it]

 51%|█████     | 2412/4716 [46:36<44:38,  1.16s/it]

 51%|█████     | 2413/4716 [46:37<44:40,  1.16s/it]

 51%|█████     | 2414/4716 [46:38<44:39,  1.16s/it]

 51%|█████     | 2415/4716 [46:39<44:37,  1.16s/it]

 51%|█████     | 2416/4716 [46:40<44:35,  1.16s/it]

 51%|█████▏    | 2417/4716 [46:42<44:36,  1.16s/it]

 51%|█████▏    | 2418/4716 [46:43<44:30,  1.16s/it]

 51%|█████▏    | 2419/4716 [46:44<44:29,  1.16s/it]

 51%|█████▏    | 2420/4716 [46:45<44:25,  1.16s/it]

 51%|█████▏    | 2421/4716 [46:46<44:25,  1.16s/it]

 51%|█████▏    | 2422/4716 [46:47<44:23,  1.16s/it]

 51%|█████▏    | 2423/4716 [46:48<44:21,  1.16s/it]

 51%|█████▏    | 2424/4716 [46:50<44:20,  1.16s/it]

 51%|█████▏    | 2425/4716 [46:51<44:21,  1.16s/it]

 51%|█████▏    | 2426/4716 [46:52<44:23,  1.16s/it]

 51%|█████▏    | 2427/4716 [46:53<44:22,  1.16s/it]

 51%|█████▏    | 2428/4716 [46:54<44:21,  1.16s/it]

 52%|█████▏    | 2429/4716 [46:55<44:19,  1.16s/it]

 52%|█████▏    | 2430/4716 [46:57<44:38,  1.17s/it]

 52%|█████▏    | 2431/4716 [46:58<44:30,  1.17s/it]

 52%|█████▏    | 2432/4716 [46:59<44:23,  1.17s/it]

 52%|█████▏    | 2433/4716 [47:00<44:19,  1.17s/it]

 52%|█████▏    | 2434/4716 [47:01<44:16,  1.16s/it]

 52%|█████▏    | 2435/4716 [47:02<44:14,  1.16s/it]

 52%|█████▏    | 2436/4716 [47:04<44:09,  1.16s/it]

 52%|█████▏    | 2437/4716 [47:05<44:06,  1.16s/it]

 52%|█████▏    | 2438/4716 [47:06<44:19,  1.17s/it]

 52%|█████▏    | 2439/4716 [47:07<44:53,  1.18s/it]

 52%|█████▏    | 2440/4716 [47:08<44:35,  1.18s/it]

 52%|█████▏    | 2441/4716 [47:09<44:24,  1.17s/it]

 52%|█████▏    | 2442/4716 [47:11<44:13,  1.17s/it]

 52%|█████▏    | 2443/4716 [47:12<44:09,  1.17s/it]

 52%|█████▏    | 2444/4716 [47:13<44:06,  1.17s/it]

 52%|█████▏    | 2445/4716 [47:14<44:04,  1.16s/it]

 52%|█████▏    | 2446/4716 [47:15<44:02,  1.16s/it]

 52%|█████▏    | 2447/4716 [47:16<44:01,  1.16s/it]

 52%|█████▏    | 2448/4716 [47:18<43:59,  1.16s/it]

 52%|█████▏    | 2449/4716 [47:19<43:57,  1.16s/it]

 52%|█████▏    | 2450/4716 [47:20<43:51,  1.16s/it]

 52%|█████▏    | 2451/4716 [47:21<43:53,  1.16s/it]

 52%|█████▏    | 2452/4716 [47:22<43:51,  1.16s/it]

 52%|█████▏    | 2453/4716 [47:23<43:50,  1.16s/it]

 52%|█████▏    | 2454/4716 [47:25<43:52,  1.16s/it]

 52%|█████▏    | 2455/4716 [47:26<43:50,  1.16s/it]

 52%|█████▏    | 2456/4716 [47:27<43:47,  1.16s/it]

 52%|█████▏    | 2457/4716 [47:28<43:45,  1.16s/it]

 52%|█████▏    | 2458/4716 [47:29<43:42,  1.16s/it]

 52%|█████▏    | 2459/4716 [47:30<43:41,  1.16s/it]

 52%|█████▏    | 2460/4716 [47:32<43:38,  1.16s/it]

 52%|█████▏    | 2461/4716 [47:33<43:36,  1.16s/it]

 52%|█████▏    | 2462/4716 [47:34<43:36,  1.16s/it]

 52%|█████▏    | 2463/4716 [47:35<43:36,  1.16s/it]

 52%|█████▏    | 2464/4716 [47:36<43:37,  1.16s/it]

 52%|█████▏    | 2465/4716 [47:37<43:34,  1.16s/it]

 52%|█████▏    | 2466/4716 [47:39<43:32,  1.16s/it]

 52%|█████▏    | 2467/4716 [47:40<43:32,  1.16s/it]

 52%|█████▏    | 2468/4716 [47:41<43:31,  1.16s/it]

 52%|█████▏    | 2469/4716 [47:42<43:30,  1.16s/it]

 52%|█████▏    | 2470/4716 [47:43<43:25,  1.16s/it]

 52%|█████▏    | 2471/4716 [47:44<43:24,  1.16s/it]

 52%|█████▏    | 2472/4716 [47:46<43:24,  1.16s/it]

 52%|█████▏    | 2473/4716 [47:47<43:23,  1.16s/it]

 52%|█████▏    | 2474/4716 [47:48<43:22,  1.16s/it]

 52%|█████▏    | 2475/4716 [47:49<43:21,  1.16s/it]

 53%|█████▎    | 2476/4716 [47:50<43:18,  1.16s/it]

 53%|█████▎    | 2477/4716 [47:51<43:20,  1.16s/it]

 53%|█████▎    | 2478/4716 [47:52<43:22,  1.16s/it]

 53%|█████▎    | 2479/4716 [47:54<43:21,  1.16s/it]

 53%|█████▎    | 2480/4716 [47:55<43:19,  1.16s/it]

 53%|█████▎    | 2481/4716 [47:56<43:16,  1.16s/it]

 53%|█████▎    | 2482/4716 [47:57<43:13,  1.16s/it]

 53%|█████▎    | 2483/4716 [47:58<43:11,  1.16s/it]

 53%|█████▎    | 2484/4716 [47:59<43:08,  1.16s/it]

 53%|█████▎    | 2485/4716 [48:01<43:08,  1.16s/it]

 53%|█████▎    | 2486/4716 [48:02<43:09,  1.16s/it]

 53%|█████▎    | 2487/4716 [48:03<43:08,  1.16s/it]

 53%|█████▎    | 2488/4716 [48:04<43:08,  1.16s/it]

 53%|█████▎    | 2489/4716 [48:05<43:07,  1.16s/it]

 53%|█████▎    | 2490/4716 [48:06<43:06,  1.16s/it]

 53%|█████▎    | 2491/4716 [48:08<43:06,  1.16s/it]

 53%|█████▎    | 2492/4716 [48:09<43:03,  1.16s/it]

 53%|█████▎    | 2493/4716 [48:10<42:59,  1.16s/it]

 53%|█████▎    | 2494/4716 [48:11<42:57,  1.16s/it]

 53%|█████▎    | 2495/4716 [48:12<42:57,  1.16s/it]

 53%|█████▎    | 2496/4716 [48:13<42:56,  1.16s/it]

 53%|█████▎    | 2497/4716 [48:15<42:54,  1.16s/it]

 53%|█████▎    | 2498/4716 [48:16<42:52,  1.16s/it]

 53%|█████▎    | 2499/4716 [48:17<42:54,  1.16s/it]

 53%|█████▎    | 2500/4716 [48:18<42:55,  1.16s/it]

 53%|█████▎    | 2501/4716 [48:19<42:54,  1.16s/it]

 53%|█████▎    | 2502/4716 [48:20<42:52,  1.16s/it]

 53%|█████▎    | 2503/4716 [48:22<42:52,  1.16s/it]

logging
logging the anndata

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 53%|█████▎    | 2504/4716 [48:23<45:47,  1.24s/it]

 53%|█████▎    | 2505/4716 [48:24<44:48,  1.22s/it]

 53%|█████▎    | 2506/4716 [48:25<44:07,  1.20s/it]

 53%|█████▎    | 2507/4716 [48:26<43:39,  1.19s/it]

 53%|█████▎    | 2508/4716 [48:28<43:21,  1.18s/it]

 53%|█████▎    | 2509/4716 [48:29<43:04,  1.17s/it]

 53%|█████▎    | 2510/4716 [48:30<42:52,  1.17s/it]

 53%|█████▎    | 2511/4716 [48:31<42:45,  1.16s/it]

 53%|█████▎    | 2512/4716 [48:32<42:41,  1.16s/it]

 53%|█████▎    | 2513/4716 [48:33<42:34,  1.16s/it]

 53%|█████▎    | 2514/4716 [48:35<42:34,  1.16s/it]

 53%|█████▎    | 2515/4716 [48:36<42:29,  1.16s/it]

 53%|█████▎    | 2516/4716 [48:37<42:27,  1.16s/it]

 53%|█████▎    | 2517/4716 [48:38<42:25,  1.16s/it]

 53%|█████▎    | 2518/4716 [48:39<42:24,  1.16s/it]

 53%|█████▎    | 2519/4716 [48:40<42:24,  1.16s/it]

 53%|█████▎    | 2520/4716 [48:41<42:22,  1.16s/it]

 53%|█████▎    | 2521/4716 [48:43<42:22,  1.16s/it]

 53%|█████▎    | 2522/4716 [48:44<42:21,  1.16s/it]

 53%|█████▎    | 2523/4716 [48:45<42:18,  1.16s/it]

 54%|█████▎    | 2524/4716 [48:46<42:14,  1.16s/it]

 54%|█████▎    | 2525/4716 [48:47<42:12,  1.16s/it]

 54%|█████▎    | 2526/4716 [48:48<42:11,  1.16s/it]

 54%|█████▎    | 2527/4716 [48:50<42:12,  1.16s/it]

 54%|█████▎    | 2528/4716 [48:51<42:09,  1.16s/it]

 54%|█████▎    | 2529/4716 [48:52<42:07,  1.16s/it]

 54%|█████▎    | 2530/4716 [48:53<42:08,  1.16s/it]

 54%|█████▎    | 2531/4716 [48:54<42:03,  1.16s/it]

 54%|█████▎    | 2532/4716 [48:55<42:04,  1.16s/it]

 54%|█████▎    | 2533/4716 [48:56<42:02,  1.16s/it]

 54%|█████▎    | 2534/4716 [48:58<42:01,  1.16s/it]

 54%|█████▍    | 2535/4716 [48:59<42:01,  1.16s/it]

 54%|█████▍    | 2536/4716 [49:00<42:00,  1.16s/it]

 54%|█████▍    | 2537/4716 [49:01<42:01,  1.16s/it]

 54%|█████▍    | 2538/4716 [49:02<42:01,  1.16s/it]

 54%|█████▍    | 2539/4716 [49:03<41:58,  1.16s/it]

 54%|█████▍    | 2540/4716 [49:05<41:57,  1.16s/it]

 54%|█████▍    | 2541/4716 [49:06<41:55,  1.16s/it]

 54%|█████▍    | 2542/4716 [49:07<41:53,  1.16s/it]

 54%|█████▍    | 2543/4716 [49:08<41:52,  1.16s/it]

 54%|█████▍    | 2544/4716 [49:09<41:51,  1.16s/it]

 54%|█████▍    | 2545/4716 [49:10<41:50,  1.16s/it]

 54%|█████▍    | 2546/4716 [49:12<41:50,  1.16s/it]

 54%|█████▍    | 2547/4716 [49:13<41:46,  1.16s/it]

 54%|█████▍    | 2548/4716 [49:14<41:45,  1.16s/it]

 54%|█████▍    | 2549/4716 [49:15<41:44,  1.16s/it]

 54%|█████▍    | 2550/4716 [49:16<41:42,  1.16s/it]

 54%|█████▍    | 2551/4716 [49:17<41:42,  1.16s/it]

 54%|█████▍    | 2552/4716 [49:18<41:40,  1.16s/it]

 54%|█████▍    | 2553/4716 [49:20<41:41,  1.16s/it]

 54%|█████▍    | 2554/4716 [49:21<41:41,  1.16s/it]

 54%|█████▍    | 2555/4716 [49:22<41:39,  1.16s/it]

 54%|█████▍    | 2556/4716 [49:23<41:38,  1.16s/it]

 54%|█████▍    | 2557/4716 [49:24<41:38,  1.16s/it]

 54%|█████▍    | 2558/4716 [49:25<41:35,  1.16s/it]

 54%|█████▍    | 2559/4716 [49:27<41:35,  1.16s/it]

 54%|█████▍    | 2560/4716 [49:28<41:31,  1.16s/it]

 54%|█████▍    | 2561/4716 [49:29<41:29,  1.16s/it]

 54%|█████▍    | 2562/4716 [49:30<41:28,  1.16s/it]

 54%|█████▍    | 2563/4716 [49:31<41:29,  1.16s/it]

 54%|█████▍    | 2564/4716 [49:32<41:26,  1.16s/it]

 54%|█████▍    | 2565/4716 [49:33<41:27,  1.16s/it]

 54%|█████▍    | 2566/4716 [49:35<41:28,  1.16s/it]

 54%|█████▍    | 2567/4716 [49:36<41:28,  1.16s/it]

 54%|█████▍    | 2568/4716 [49:37<41:26,  1.16s/it]

 54%|█████▍    | 2569/4716 [49:38<41:28,  1.16s/it]

 54%|█████▍    | 2570/4716 [49:39<41:27,  1.16s/it]

 55%|█████▍    | 2571/4716 [49:40<41:26,  1.16s/it]

 55%|█████▍    | 2572/4716 [49:42<41:26,  1.16s/it]

 55%|█████▍    | 2573/4716 [49:43<41:22,  1.16s/it]

 55%|█████▍    | 2574/4716 [49:44<41:16,  1.16s/it]

 55%|█████▍    | 2575/4716 [49:45<41:18,  1.16s/it]

 55%|█████▍    | 2576/4716 [49:46<41:16,  1.16s/it]

 55%|█████▍    | 2577/4716 [49:47<41:16,  1.16s/it]

 55%|█████▍    | 2578/4716 [49:49<41:16,  1.16s/it]

 55%|█████▍    | 2579/4716 [49:50<41:13,  1.16s/it]

 55%|█████▍    | 2580/4716 [49:51<41:09,  1.16s/it]

 55%|█████▍    | 2581/4716 [49:52<41:06,  1.16s/it]

 55%|█████▍    | 2582/4716 [49:53<41:05,  1.16s/it]

 55%|█████▍    | 2583/4716 [49:54<41:07,  1.16s/it]

 55%|█████▍    | 2584/4716 [49:55<41:08,  1.16s/it]

 55%|█████▍    | 2585/4716 [49:57<41:06,  1.16s/it]

 55%|█████▍    | 2586/4716 [49:58<41:05,  1.16s/it]

 55%|█████▍    | 2587/4716 [49:59<41:04,  1.16s/it]

 55%|█████▍    | 2588/4716 [50:00<41:01,  1.16s/it]

 55%|█████▍    | 2589/4716 [50:01<41:00,  1.16s/it]

 55%|█████▍    | 2590/4716 [50:02<40:57,  1.16s/it]

 55%|█████▍    | 2591/4716 [50:04<40:57,  1.16s/it]

 55%|█████▍    | 2592/4716 [50:05<40:54,  1.16s/it]

 55%|█████▍    | 2593/4716 [50:06<40:55,  1.16s/it]

 55%|█████▌    | 2594/4716 [50:07<40:53,  1.16s/it]

 55%|█████▌    | 2595/4716 [50:08<40:53,  1.16s/it]

 55%|█████▌    | 2596/4716 [50:09<40:52,  1.16s/it]

 55%|█████▌    | 2597/4716 [50:11<40:50,  1.16s/it]

 55%|█████▌    | 2598/4716 [50:12<40:48,  1.16s/it]

 55%|█████▌    | 2599/4716 [50:13<40:46,  1.16s/it]

 55%|█████▌    | 2600/4716 [50:14<40:45,  1.16s/it]

 55%|█████▌    | 2601/4716 [50:15<40:45,  1.16s/it]

 55%|█████▌    | 2602/4716 [50:16<40:44,  1.16s/it]

 55%|█████▌    | 2603/4716 [50:17<40:44,  1.16s/it]

 55%|█████▌    | 2604/4716 [50:19<40:44,  1.16s/it]

 55%|█████▌    | 2605/4716 [50:20<40:44,  1.16s/it]

 55%|█████▌    | 2606/4716 [50:21<40:41,  1.16s/it]

 55%|█████▌    | 2607/4716 [50:22<40:39,  1.16s/it]

 55%|█████▌    | 2608/4716 [50:23<40:37,  1.16s/it]

 55%|█████▌    | 2609/4716 [50:24<40:37,  1.16s/it]

 55%|█████▌    | 2610/4716 [50:26<40:37,  1.16s/it]

 55%|█████▌    | 2611/4716 [50:27<40:34,  1.16s/it]

 55%|█████▌    | 2612/4716 [50:28<40:33,  1.16s/it]

 55%|█████▌    | 2613/4716 [50:29<40:32,  1.16s/it]

 55%|█████▌    | 2614/4716 [50:30<40:33,  1.16s/it]

 55%|█████▌    | 2615/4716 [50:31<40:31,  1.16s/it]

 55%|█████▌    | 2616/4716 [50:32<40:29,  1.16s/it]

 55%|█████▌    | 2617/4716 [50:34<40:28,  1.16s/it]

 56%|█████▌    | 2618/4716 [50:35<40:24,  1.16s/it]

 56%|█████▌    | 2619/4716 [50:36<40:23,  1.16s/it]

 56%|█████▌    | 2620/4716 [50:37<40:27,  1.16s/it]

 56%|█████▌    | 2621/4716 [50:38<40:27,  1.16s/it]

 56%|█████▌    | 2622/4716 [50:39<40:24,  1.16s/it]

 56%|█████▌    | 2623/4716 [50:41<40:24,  1.16s/it]

 56%|█████▌    | 2624/4716 [50:42<40:25,  1.16s/it]

 56%|█████▌    | 2625/4716 [50:43<40:24,  1.16s/it]

 56%|█████▌    | 2626/4716 [50:44<40:21,  1.16s/it]

 56%|█████▌    | 2627/4716 [50:45<40:20,  1.16s/it]

 56%|█████▌    | 2628/4716 [50:46<40:21,  1.16s/it]

 56%|█████▌    | 2629/4716 [50:48<40:19,  1.16s/it]

 56%|█████▌    | 2630/4716 [50:49<40:18,  1.16s/it]

 56%|█████▌    | 2631/4716 [50:50<40:14,  1.16s/it]

 56%|█████▌    | 2632/4716 [50:51<40:15,  1.16s/it]

 56%|█████▌    | 2633/4716 [50:52<40:11,  1.16s/it]

 56%|█████▌    | 2634/4716 [50:53<40:13,  1.16s/it]

 56%|█████▌    | 2635/4716 [50:55<40:10,  1.16s/it]

 56%|█████▌    | 2636/4716 [50:56<40:08,  1.16s/it]

 56%|█████▌    | 2637/4716 [50:57<40:05,  1.16s/it]

 56%|█████▌    | 2638/4716 [50:58<40:08,  1.16s/it]

 56%|█████▌    | 2639/4716 [50:59<40:04,  1.16s/it]

 56%|█████▌    | 2640/4716 [51:00<40:03,  1.16s/it]

 56%|█████▌    | 2641/4716 [51:01<40:00,  1.16s/it]

 56%|█████▌    | 2642/4716 [51:03<39:59,  1.16s/it]

 56%|█████▌    | 2643/4716 [51:04<39:58,  1.16s/it]

 56%|█████▌    | 2644/4716 [51:05<39:56,  1.16s/it]

 56%|█████▌    | 2645/4716 [51:06<39:56,  1.16s/it]

 56%|█████▌    | 2646/4716 [51:07<39:55,  1.16s/it]

 56%|█████▌    | 2647/4716 [51:08<39:52,  1.16s/it]

 56%|█████▌    | 2648/4716 [51:10<39:55,  1.16s/it]

 56%|█████▌    | 2649/4716 [51:11<39:52,  1.16s/it]

 56%|█████▌    | 2650/4716 [51:12<39:50,  1.16s/it]

 56%|█████▌    | 2651/4716 [51:13<39:50,  1.16s/it]

 56%|█████▌    | 2652/4716 [51:14<39:47,  1.16s/it]

 56%|█████▋    | 2653/4716 [51:15<39:49,  1.16s/it]

 56%|█████▋    | 2654/4716 [51:16<39:48,  1.16s/it]

 56%|█████▋    | 2655/4716 [51:18<39:47,  1.16s/it]

 56%|█████▋    | 2656/4716 [51:19<39:47,  1.16s/it]

 56%|█████▋    | 2657/4716 [51:20<39:45,  1.16s/it]

 56%|█████▋    | 2658/4716 [51:21<39:43,  1.16s/it]

 56%|█████▋    | 2659/4716 [51:22<39:39,  1.16s/it]

 56%|█████▋    | 2660/4716 [51:23<39:37,  1.16s/it]

 56%|█████▋    | 2661/4716 [51:25<39:36,  1.16s/it]

 56%|█████▋    | 2662/4716 [51:26<39:38,  1.16s/it]

 56%|█████▋    | 2663/4716 [51:27<39:38,  1.16s/it]

 56%|█████▋    | 2664/4716 [51:28<39:36,  1.16s/it]

 57%|█████▋    | 2665/4716 [51:29<39:35,  1.16s/it]

 57%|█████▋    | 2666/4716 [51:30<39:36,  1.16s/it]

 57%|█████▋    | 2667/4716 [51:32<39:35,  1.16s/it]

 57%|█████▋    | 2668/4716 [51:33<39:32,  1.16s/it]

 57%|█████▋    | 2669/4716 [51:34<39:29,  1.16s/it]

 57%|█████▋    | 2670/4716 [51:35<39:25,  1.16s/it]

 57%|█████▋    | 2671/4716 [51:36<39:24,  1.16s/it]

 57%|█████▋    | 2672/4716 [51:37<39:24,  1.16s/it]

 57%|█████▋    | 2673/4716 [51:38<39:25,  1.16s/it]

 57%|█████▋    | 2674/4716 [51:40<39:26,  1.16s/it]

 57%|█████▋    | 2675/4716 [51:41<39:26,  1.16s/it]

 57%|█████▋    | 2676/4716 [51:42<39:26,  1.16s/it]

 57%|█████▋    | 2677/4716 [51:43<39:22,  1.16s/it]

 57%|█████▋    | 2678/4716 [51:44<39:21,  1.16s/it]

 57%|█████▋    | 2679/4716 [51:45<39:19,  1.16s/it]

 57%|█████▋    | 2680/4716 [51:47<39:15,  1.16s/it]

 57%|█████▋    | 2681/4716 [51:48<39:14,  1.16s/it]

 57%|█████▋    | 2682/4716 [51:49<39:14,  1.16s/it]

 57%|█████▋    | 2683/4716 [51:50<39:18,  1.16s/it]

 57%|█████▋    | 2684/4716 [51:51<39:14,  1.16s/it]

 57%|█████▋    | 2685/4716 [51:52<39:14,  1.16s/it]

 57%|█████▋    | 2686/4716 [51:54<39:13,  1.16s/it]

 57%|█████▋    | 2687/4716 [51:55<39:10,  1.16s/it]

 57%|█████▋    | 2688/4716 [51:56<39:09,  1.16s/it]

 57%|█████▋    | 2689/4716 [51:57<39:08,  1.16s/it]

 57%|█████▋    | 2690/4716 [51:58<39:08,  1.16s/it]

 57%|█████▋    | 2691/4716 [51:59<39:05,  1.16s/it]

 57%|█████▋    | 2692/4716 [52:01<39:04,  1.16s/it]

 57%|█████▋    | 2693/4716 [52:02<39:02,  1.16s/it]

 57%|█████▋    | 2694/4716 [52:03<39:01,  1.16s/it]

 57%|█████▋    | 2695/4716 [52:04<39:01,  1.16s/it]

 57%|█████▋    | 2696/4716 [52:05<39:00,  1.16s/it]

 57%|█████▋    | 2697/4716 [52:06<38:58,  1.16s/it]

 57%|█████▋    | 2698/4716 [52:07<38:57,  1.16s/it]

 57%|█████▋    | 2699/4716 [52:09<38:57,  1.16s/it]

 57%|█████▋    | 2700/4716 [52:10<38:56,  1.16s/it]

 57%|█████▋    | 2701/4716 [52:11<38:56,  1.16s/it]

 57%|█████▋    | 2702/4716 [52:12<38:53,  1.16s/it]

 57%|█████▋    | 2703/4716 [52:13<38:50,  1.16s/it]

 57%|█████▋    | 2704/4716 [52:14<38:49,  1.16s/it]

 57%|█████▋    | 2705/4716 [52:16<38:47,  1.16s/it]

 57%|█████▋    | 2706/4716 [52:17<38:47,  1.16s/it]

 57%|█████▋    | 2707/4716 [52:18<38:47,  1.16s/it]

 57%|█████▋    | 2708/4716 [52:19<38:45,  1.16s/it]

 57%|█████▋    | 2709/4716 [52:20<38:44,  1.16s/it]

 57%|█████▋    | 2710/4716 [52:21<38:43,  1.16s/it]

 57%|█████▋    | 2711/4716 [52:23<38:42,  1.16s/it]

 58%|█████▊    | 2712/4716 [52:24<38:41,  1.16s/it]

 58%|█████▊    | 2713/4716 [52:25<38:39,  1.16s/it]

 58%|█████▊    | 2714/4716 [52:26<38:38,  1.16s/it]

 58%|█████▊    | 2715/4716 [52:27<38:36,  1.16s/it]

 58%|█████▊    | 2716/4716 [52:28<38:36,  1.16s/it]

 58%|█████▊    | 2717/4716 [52:29<38:35,  1.16s/it]

 58%|█████▊    | 2718/4716 [52:31<38:34,  1.16s/it]

 58%|█████▊    | 2719/4716 [52:32<38:33,  1.16s/it]

 58%|█████▊    | 2720/4716 [52:33<38:34,  1.16s/it]

 58%|█████▊    | 2721/4716 [52:34<38:30,  1.16s/it]

 58%|█████▊    | 2722/4716 [52:35<38:30,  1.16s/it]

 58%|█████▊    | 2723/4716 [52:36<38:29,  1.16s/it]

 58%|█████▊    | 2724/4716 [52:38<38:26,  1.16s/it]

 58%|█████▊    | 2725/4716 [52:39<38:25,  1.16s/it]

 58%|█████▊    | 2726/4716 [52:40<38:24,  1.16s/it]

 58%|█████▊    | 2727/4716 [52:41<38:24,  1.16s/it]

 58%|█████▊    | 2728/4716 [52:42<38:23,  1.16s/it]

 58%|█████▊    | 2729/4716 [52:43<38:23,  1.16s/it]

 58%|█████▊    | 2730/4716 [52:45<38:23,  1.16s/it]

 58%|█████▊    | 2731/4716 [52:46<38:21,  1.16s/it]

 58%|█████▊    | 2732/4716 [52:47<38:20,  1.16s/it]

 58%|█████▊    | 2733/4716 [52:48<38:18,  1.16s/it]

 58%|█████▊    | 2734/4716 [52:49<38:14,  1.16s/it]

 58%|█████▊    | 2735/4716 [52:50<38:14,  1.16s/it]

 58%|█████▊    | 2736/4716 [52:51<38:16,  1.16s/it]

 58%|█████▊    | 2737/4716 [52:53<38:13,  1.16s/it]

 58%|█████▊    | 2738/4716 [52:54<38:13,  1.16s/it]

 58%|█████▊    | 2739/4716 [52:55<38:11,  1.16s/it]

 58%|█████▊    | 2740/4716 [52:56<38:16,  1.16s/it]

 58%|█████▊    | 2741/4716 [52:57<38:13,  1.16s/it]

 58%|█████▊    | 2742/4716 [52:58<38:09,  1.16s/it]

 58%|█████▊    | 2743/4716 [53:00<38:08,  1.16s/it]

 58%|█████▊    | 2744/4716 [53:01<38:09,  1.16s/it]

 58%|█████▊    | 2745/4716 [53:02<38:09,  1.16s/it]

 58%|█████▊    | 2746/4716 [53:03<38:05,  1.16s/it]

 58%|█████▊    | 2747/4716 [53:04<38:00,  1.16s/it]

 58%|█████▊    | 2748/4716 [53:05<37:58,  1.16s/it]

 58%|█████▊    | 2749/4716 [53:07<37:56,  1.16s/it]

 58%|█████▊    | 2750/4716 [53:08<37:56,  1.16s/it]

 58%|█████▊    | 2751/4716 [53:09<37:55,  1.16s/it]

 58%|█████▊    | 2752/4716 [53:10<37:55,  1.16s/it]

 58%|█████▊    | 2753/4716 [53:11<37:55,  1.16s/it]

 58%|█████▊    | 2754/4716 [53:12<37:55,  1.16s/it]

 58%|█████▊    | 2755/4716 [53:14<37:54,  1.16s/it]

 58%|█████▊    | 2756/4716 [53:15<37:52,  1.16s/it]

 58%|█████▊    | 2757/4716 [53:16<37:49,  1.16s/it]

 58%|█████▊    | 2758/4716 [53:17<37:48,  1.16s/it]

 59%|█████▊    | 2759/4716 [53:18<37:46,  1.16s/it]

 59%|█████▊    | 2760/4716 [53:19<37:45,  1.16s/it]

 59%|█████▊    | 2761/4716 [53:20<37:44,  1.16s/it]

 59%|█████▊    | 2762/4716 [53:22<37:44,  1.16s/it]

 59%|█████▊    | 2763/4716 [53:23<37:45,  1.16s/it]

 59%|█████▊    | 2764/4716 [53:24<37:42,  1.16s/it]

 59%|█████▊    | 2765/4716 [53:25<37:41,  1.16s/it]

 59%|█████▊    | 2766/4716 [53:26<37:41,  1.16s/it]

 59%|█████▊    | 2767/4716 [53:27<37:41,  1.16s/it]

 59%|█████▊    | 2768/4716 [53:29<37:39,  1.16s/it]

 59%|█████▊    | 2769/4716 [53:30<37:36,  1.16s/it]

 59%|█████▊    | 2770/4716 [53:31<37:35,  1.16s/it]

 59%|█████▉    | 2771/4716 [53:32<37:34,  1.16s/it]

 59%|█████▉    | 2772/4716 [53:33<37:33,  1.16s/it]

 59%|█████▉    | 2773/4716 [53:34<37:32,  1.16s/it]

 59%|█████▉    | 2774/4716 [53:36<37:32,  1.16s/it]

 59%|█████▉    | 2775/4716 [53:37<37:31,  1.16s/it]

 59%|█████▉    | 2776/4716 [53:38<37:30,  1.16s/it]

 59%|█████▉    | 2777/4716 [53:39<37:29,  1.16s/it]

 59%|█████▉    | 2778/4716 [53:40<37:28,  1.16s/it]

 59%|█████▉    | 2779/4716 [53:41<37:25,  1.16s/it]

 59%|█████▉    | 2780/4716 [53:42<37:23,  1.16s/it]

 59%|█████▉    | 2781/4716 [53:44<37:22,  1.16s/it]

 59%|█████▉    | 2782/4716 [53:45<37:21,  1.16s/it]

 59%|█████▉    | 2783/4716 [53:46<37:21,  1.16s/it]

 59%|█████▉    | 2784/4716 [53:47<37:21,  1.16s/it]

 59%|█████▉    | 2785/4716 [53:48<37:20,  1.16s/it]

 59%|█████▉    | 2786/4716 [53:49<37:18,  1.16s/it]

 59%|█████▉    | 2787/4716 [53:51<37:17,  1.16s/it]

 59%|█████▉    | 2788/4716 [53:52<37:14,  1.16s/it]

 59%|█████▉    | 2789/4716 [53:53<37:13,  1.16s/it]

 59%|█████▉    | 2790/4716 [53:54<37:10,  1.16s/it]

 59%|█████▉    | 2791/4716 [53:55<37:10,  1.16s/it]

 59%|█████▉    | 2792/4716 [53:56<37:08,  1.16s/it]

 59%|█████▉    | 2793/4716 [53:58<37:08,  1.16s/it]

 59%|█████▉    | 2794/4716 [53:59<37:08,  1.16s/it]

 59%|█████▉    | 2795/4716 [54:00<37:08,  1.16s/it]

 59%|█████▉    | 2796/4716 [54:01<37:07,  1.16s/it]

 59%|█████▉    | 2797/4716 [54:02<37:05,  1.16s/it]

 59%|█████▉    | 2798/4716 [54:03<37:06,  1.16s/it]

 59%|█████▉    | 2799/4716 [54:05<37:05,  1.16s/it]

 59%|█████▉    | 2800/4716 [54:06<37:06,  1.16s/it]

 59%|█████▉    | 2801/4716 [54:07<37:04,  1.16s/it]

 59%|█████▉    | 2802/4716 [54:08<37:03,  1.16s/it]

 59%|█████▉    | 2803/4716 [54:09<37:01,  1.16s/it]

 59%|█████▉    | 2804/4716 [54:10<37:00,  1.16s/it]

 59%|█████▉    | 2805/4716 [54:11<36:56,  1.16s/it]

 59%|█████▉    | 2806/4716 [54:13<36:53,  1.16s/it]

 60%|█████▉    | 2807/4716 [54:14<36:52,  1.16s/it]

 60%|█████▉    | 2808/4716 [54:15<36:50,  1.16s/it]

 60%|█████▉    | 2809/4716 [54:16<36:51,  1.16s/it]

 60%|█████▉    | 2810/4716 [54:17<36:51,  1.16s/it]

 60%|█████▉    | 2811/4716 [54:18<36:49,  1.16s/it]

 60%|█████▉    | 2812/4716 [54:20<36:49,  1.16s/it]

 60%|█████▉    | 2813/4716 [54:21<36:50,  1.16s/it]

 60%|█████▉    | 2814/4716 [54:22<36:47,  1.16s/it]

 60%|█████▉    | 2815/4716 [54:23<36:45,  1.16s/it]

 60%|█████▉    | 2816/4716 [54:24<36:44,  1.16s/it]

 60%|█████▉    | 2817/4716 [54:25<36:43,  1.16s/it]

 60%|█████▉    | 2818/4716 [54:27<36:40,  1.16s/it]

 60%|█████▉    | 2819/4716 [54:28<36:40,  1.16s/it]

 60%|█████▉    | 2820/4716 [54:29<36:42,  1.16s/it]

 60%|█████▉    | 2821/4716 [54:30<36:42,  1.16s/it]

 60%|█████▉    | 2822/4716 [54:31<36:41,  1.16s/it]

 60%|█████▉    | 2823/4716 [54:32<36:41,  1.16s/it]

 60%|█████▉    | 2824/4716 [54:34<36:40,  1.16s/it]

 60%|█████▉    | 2825/4716 [54:35<36:38,  1.16s/it]

 60%|█████▉    | 2826/4716 [54:36<36:35,  1.16s/it]

 60%|█████▉    | 2827/4716 [54:37<36:33,  1.16s/it]

 60%|█████▉    | 2828/4716 [54:38<36:31,  1.16s/it]

 60%|█████▉    | 2829/4716 [54:39<36:34,  1.16s/it]

 60%|██████    | 2830/4716 [54:41<38:29,  1.22s/it]

 60%|██████    | 2831/4716 [54:42<37:50,  1.20s/it]

 60%|██████    | 2832/4716 [54:43<37:22,  1.19s/it]

 60%|██████    | 2833/4716 [54:44<37:04,  1.18s/it]

 60%|██████    | 2834/4716 [54:45<36:51,  1.17s/it]

 60%|██████    | 2835/4716 [54:47<36:42,  1.17s/it]

 60%|██████    | 2836/4716 [54:48<36:33,  1.17s/it]

 60%|██████    | 2837/4716 [54:49<36:28,  1.16s/it]

 60%|██████    | 2838/4716 [54:50<36:27,  1.16s/it]

 60%|██████    | 2839/4716 [54:51<36:26,  1.16s/it]

 60%|██████    | 2840/4716 [54:52<36:24,  1.16s/it]

 60%|██████    | 2841/4716 [54:54<36:21,  1.16s/it]

 60%|██████    | 2842/4716 [54:55<36:16,  1.16s/it]

 60%|██████    | 2843/4716 [54:56<36:14,  1.16s/it]

 60%|██████    | 2844/4716 [54:57<36:12,  1.16s/it]

 60%|██████    | 2845/4716 [54:58<36:09,  1.16s/it]

 60%|██████    | 2846/4716 [54:59<36:09,  1.16s/it]

 60%|██████    | 2847/4716 [55:00<36:10,  1.16s/it]

 60%|██████    | 2848/4716 [55:02<36:09,  1.16s/it]

 60%|██████    | 2849/4716 [55:03<36:09,  1.16s/it]

 60%|██████    | 2850/4716 [55:04<36:07,  1.16s/it]

 60%|██████    | 2851/4716 [55:05<36:04,  1.16s/it]

 60%|██████    | 2852/4716 [55:06<36:02,  1.16s/it]

 60%|██████    | 2853/4716 [55:07<36:03,  1.16s/it]

 61%|██████    | 2854/4716 [55:09<36:02,  1.16s/it]

 61%|██████    | 2855/4716 [55:10<35:58,  1.16s/it]

 61%|██████    | 2856/4716 [55:11<35:59,  1.16s/it]

 61%|██████    | 2857/4716 [55:12<35:58,  1.16s/it]

 61%|██████    | 2858/4716 [55:13<35:57,  1.16s/it]

 61%|██████    | 2859/4716 [55:14<35:57,  1.16s/it]

 61%|██████    | 2860/4716 [55:16<35:58,  1.16s/it]

 61%|██████    | 2861/4716 [55:17<35:56,  1.16s/it]

 61%|██████    | 2862/4716 [55:18<35:55,  1.16s/it]

 61%|██████    | 2863/4716 [55:19<35:52,  1.16s/it]

 61%|██████    | 2864/4716 [55:20<35:51,  1.16s/it]

 61%|██████    | 2865/4716 [55:21<35:48,  1.16s/it]

 61%|██████    | 2866/4716 [55:23<35:47,  1.16s/it]

 61%|██████    | 2867/4716 [55:24<35:45,  1.16s/it]

 61%|██████    | 2868/4716 [55:25<35:44,  1.16s/it]

 61%|██████    | 2869/4716 [55:26<35:43,  1.16s/it]

 61%|██████    | 2870/4716 [55:27<35:40,  1.16s/it]

 61%|██████    | 2871/4716 [55:28<35:39,  1.16s/it]

 61%|██████    | 2872/4716 [55:29<35:36,  1.16s/it]

 61%|██████    | 2873/4716 [55:31<35:35,  1.16s/it]

 61%|██████    | 2874/4716 [55:32<35:35,  1.16s/it]

 61%|██████    | 2875/4716 [55:33<35:35,  1.16s/it]

 61%|██████    | 2876/4716 [55:34<35:35,  1.16s/it]

 61%|██████    | 2877/4716 [55:35<35:33,  1.16s/it]

 61%|██████    | 2878/4716 [55:36<35:31,  1.16s/it]

 61%|██████    | 2879/4716 [55:38<35:32,  1.16s/it]

 61%|██████    | 2880/4716 [55:39<35:30,  1.16s/it]

 61%|██████    | 2881/4716 [55:40<35:28,  1.16s/it]

 61%|██████    | 2882/4716 [55:41<35:27,  1.16s/it]

 61%|██████    | 2883/4716 [55:42<35:26,  1.16s/it]

 61%|██████    | 2884/4716 [55:43<35:25,  1.16s/it]

 61%|██████    | 2885/4716 [55:45<35:23,  1.16s/it]

 61%|██████    | 2886/4716 [55:46<35:21,  1.16s/it]

 61%|██████    | 2887/4716 [55:47<35:22,  1.16s/it]

 61%|██████    | 2888/4716 [55:48<35:24,  1.16s/it]

 61%|██████▏   | 2889/4716 [55:49<35:23,  1.16s/it]

 61%|██████▏   | 2890/4716 [55:50<35:22,  1.16s/it]

 61%|██████▏   | 2891/4716 [55:52<35:22,  1.16s/it]

 61%|██████▏   | 2892/4716 [55:53<35:18,  1.16s/it]

 61%|██████▏   | 2893/4716 [55:54<35:17,  1.16s/it]

 61%|██████▏   | 2894/4716 [55:55<35:15,  1.16s/it]

 61%|██████▏   | 2895/4716 [55:56<35:13,  1.16s/it]

 61%|██████▏   | 2896/4716 [55:57<35:12,  1.16s/it]

 61%|██████▏   | 2897/4716 [55:58<35:10,  1.16s/it]

 61%|██████▏   | 2898/4716 [56:00<35:10,  1.16s/it]

 61%|██████▏   | 2899/4716 [56:01<35:09,  1.16s/it]

 61%|██████▏   | 2900/4716 [56:02<35:09,  1.16s/it]

 62%|██████▏   | 2901/4716 [56:03<35:09,  1.16s/it]

 62%|██████▏   | 2902/4716 [56:04<35:06,  1.16s/it]

 62%|██████▏   | 2903/4716 [56:05<35:04,  1.16s/it]

 62%|██████▏   | 2904/4716 [56:07<35:02,  1.16s/it]

 62%|██████▏   | 2905/4716 [56:08<35:02,  1.16s/it]

 62%|██████▏   | 2906/4716 [56:09<35:02,  1.16s/it]

 62%|██████▏   | 2907/4716 [56:10<34:57,  1.16s/it]

 62%|██████▏   | 2908/4716 [56:11<34:56,  1.16s/it]

 62%|██████▏   | 2909/4716 [56:12<34:57,  1.16s/it]

 62%|██████▏   | 2910/4716 [56:14<34:59,  1.16s/it]

 62%|██████▏   | 2911/4716 [56:15<34:57,  1.16s/it]

 62%|██████▏   | 2912/4716 [56:16<34:58,  1.16s/it]

 62%|██████▏   | 2913/4716 [56:17<34:59,  1.16s/it]

 62%|██████▏   | 2914/4716 [56:18<34:54,  1.16s/it]

 62%|██████▏   | 2915/4716 [56:19<34:53,  1.16s/it]

 62%|██████▏   | 2916/4716 [56:21<34:53,  1.16s/it]

 62%|██████▏   | 2917/4716 [56:22<34:53,  1.16s/it]

 62%|██████▏   | 2918/4716 [56:23<34:52,  1.16s/it]

 62%|██████▏   | 2919/4716 [56:24<34:50,  1.16s/it]

 62%|██████▏   | 2920/4716 [56:25<34:47,  1.16s/it]

 62%|██████▏   | 2921/4716 [56:26<34:46,  1.16s/it]

 62%|██████▏   | 2922/4716 [56:28<34:46,  1.16s/it]

 62%|██████▏   | 2923/4716 [56:29<34:43,  1.16s/it]

 62%|██████▏   | 2924/4716 [56:30<34:40,  1.16s/it]

 62%|██████▏   | 2925/4716 [56:31<34:39,  1.16s/it]

 62%|██████▏   | 2926/4716 [56:32<34:38,  1.16s/it]

 62%|██████▏   | 2927/4716 [56:33<34:37,  1.16s/it]

 62%|██████▏   | 2928/4716 [56:35<34:35,  1.16s/it]

 62%|██████▏   | 2929/4716 [56:36<34:33,  1.16s/it]

 62%|██████▏   | 2930/4716 [56:37<34:32,  1.16s/it]

 62%|██████▏   | 2931/4716 [56:38<34:31,  1.16s/it]

 62%|██████▏   | 2932/4716 [56:39<34:32,  1.16s/it]

 62%|██████▏   | 2933/4716 [56:40<34:32,  1.16s/it]

 62%|██████▏   | 2934/4716 [56:41<34:28,  1.16s/it]

 62%|██████▏   | 2935/4716 [56:43<34:26,  1.16s/it]

 62%|██████▏   | 2936/4716 [56:44<34:25,  1.16s/it]

 62%|██████▏   | 2937/4716 [56:45<34:26,  1.16s/it]

 62%|██████▏   | 2938/4716 [56:46<34:25,  1.16s/it]

 62%|██████▏   | 2939/4716 [56:47<34:23,  1.16s/it]

 62%|██████▏   | 2940/4716 [56:48<34:21,  1.16s/it]

 62%|██████▏   | 2941/4716 [56:50<34:22,  1.16s/it]

 62%|██████▏   | 2942/4716 [56:51<34:21,  1.16s/it]

 62%|██████▏   | 2943/4716 [56:52<34:20,  1.16s/it]

 62%|██████▏   | 2944/4716 [56:53<34:20,  1.16s/it]

 62%|██████▏   | 2945/4716 [56:54<34:20,  1.16s/it]

 62%|██████▏   | 2946/4716 [56:55<34:16,  1.16s/it]

 62%|██████▏   | 2947/4716 [56:57<34:13,  1.16s/it]

 63%|██████▎   | 2948/4716 [56:58<34:11,  1.16s/it]

 63%|██████▎   | 2949/4716 [56:59<34:11,  1.16s/it]

 63%|██████▎   | 2950/4716 [57:00<34:08,  1.16s/it]

 63%|██████▎   | 2951/4716 [57:01<34:07,  1.16s/it]

 63%|██████▎   | 2952/4716 [57:02<34:07,  1.16s/it]

 63%|██████▎   | 2953/4716 [57:04<34:07,  1.16s/it]

 63%|██████▎   | 2954/4716 [57:05<34:07,  1.16s/it]

 63%|██████▎   | 2955/4716 [57:06<34:08,  1.16s/it]

 63%|██████▎   | 2956/4716 [57:07<34:07,  1.16s/it]

 63%|██████▎   | 2957/4716 [57:08<34:06,  1.16s/it]

 63%|██████▎   | 2958/4716 [57:09<34:06,  1.16s/it]

 63%|██████▎   | 2959/4716 [57:11<34:04,  1.16s/it]

 63%|██████▎   | 2960/4716 [57:12<34:03,  1.16s/it]

 63%|██████▎   | 2961/4716 [57:13<33:59,  1.16s/it]

 63%|██████▎   | 2962/4716 [57:14<33:58,  1.16s/it]

 63%|██████▎   | 2963/4716 [57:15<33:56,  1.16s/it]

 63%|██████▎   | 2964/4716 [57:16<33:54,  1.16s/it]

 63%|██████▎   | 2965/4716 [57:17<33:52,  1.16s/it]

 63%|██████▎   | 2966/4716 [57:19<33:51,  1.16s/it]

 63%|██████▎   | 2967/4716 [57:20<33:51,  1.16s/it]

 63%|██████▎   | 2968/4716 [57:21<33:51,  1.16s/it]

 63%|██████▎   | 2969/4716 [57:22<33:51,  1.16s/it]

 63%|██████▎   | 2970/4716 [57:23<33:48,  1.16s/it]

 63%|██████▎   | 2971/4716 [57:24<33:46,  1.16s/it]

 63%|██████▎   | 2972/4716 [57:26<33:47,  1.16s/it]

 63%|██████▎   | 2973/4716 [57:27<33:44,  1.16s/it]

 63%|██████▎   | 2974/4716 [57:28<33:44,  1.16s/it]

 63%|██████▎   | 2975/4716 [57:29<33:43,  1.16s/it]

 63%|██████▎   | 2976/4716 [57:30<33:42,  1.16s/it]

 63%|██████▎   | 2977/4716 [57:31<33:41,  1.16s/it]

 63%|██████▎   | 2978/4716 [57:33<33:38,  1.16s/it]

 63%|██████▎   | 2979/4716 [57:34<33:36,  1.16s/it]

 63%|██████▎   | 2980/4716 [57:35<33:35,  1.16s/it]

 63%|██████▎   | 2981/4716 [57:36<33:34,  1.16s/it]

 63%|██████▎   | 2982/4716 [57:37<33:35,  1.16s/it]

 63%|██████▎   | 2983/4716 [57:38<33:34,  1.16s/it]

 63%|██████▎   | 2984/4716 [57:40<33:34,  1.16s/it]

 63%|██████▎   | 2985/4716 [57:41<33:33,  1.16s/it]

 63%|██████▎   | 2986/4716 [57:42<33:32,  1.16s/it]

 63%|██████▎   | 2987/4716 [57:43<33:30,  1.16s/it]

 63%|██████▎   | 2988/4716 [57:44<33:29,  1.16s/it]

 63%|██████▎   | 2989/4716 [57:45<33:27,  1.16s/it]

 63%|██████▎   | 2990/4716 [57:47<33:27,  1.16s/it]

 63%|██████▎   | 2991/4716 [57:48<33:25,  1.16s/it]

 63%|██████▎   | 2992/4716 [57:49<33:23,  1.16s/it]

 63%|██████▎   | 2993/4716 [57:50<33:21,  1.16s/it]

 63%|██████▎   | 2994/4716 [57:51<33:19,  1.16s/it]

 64%|██████▎   | 2995/4716 [57:52<33:20,  1.16s/it]

 64%|██████▎   | 2996/4716 [57:54<33:19,  1.16s/it]

 64%|██████▎   | 2997/4716 [57:55<33:18,  1.16s/it]

 64%|██████▎   | 2998/4716 [57:56<33:17,  1.16s/it]

 64%|██████▎   | 2999/4716 [57:57<33:16,  1.16s/it]

 64%|██████▎   | 3000/4716 [57:58<33:15,  1.16s/it]

 64%|██████▎   | 3001/4716 [57:59<33:14,  1.16s/it]

 64%|██████▎   | 3002/4716 [58:01<33:12,  1.16s/it]

 64%|██████▎   | 3003/4716 [58:02<33:10,  1.16s/it]

 64%|██████▎   | 3004/4716 [58:03<33:08,  1.16s/it]

 64%|██████▎   | 3005/4716 [58:04<33:05,  1.16s/it]

 64%|██████▎   | 3006/4716 [58:05<33:04,  1.16s/it]

 64%|██████▍   | 3007/4716 [58:06<33:03,  1.16s/it]

 64%|██████▍   | 3008/4716 [58:07<33:03,  1.16s/it]

 64%|██████▍   | 3009/4716 [58:09<33:03,  1.16s/it]

 64%|██████▍   | 3010/4716 [58:10<33:05,  1.16s/it]

 64%|██████▍   | 3011/4716 [58:11<33:04,  1.16s/it]

 64%|██████▍   | 3012/4716 [58:12<33:03,  1.16s/it]

 64%|██████▍   | 3013/4716 [58:13<33:03,  1.16s/it]

 64%|██████▍   | 3014/4716 [58:14<33:01,  1.16s/it]

 64%|██████▍   | 3015/4716 [58:16<33:00,  1.16s/it]

 64%|██████▍   | 3016/4716 [58:17<33:01,  1.17s/it]

 64%|██████▍   | 3017/4716 [58:18<32:57,  1.16s/it]

 64%|██████▍   | 3018/4716 [58:19<32:55,  1.16s/it]

 64%|██████▍   | 3019/4716 [58:20<32:52,  1.16s/it]

 64%|██████▍   | 3020/4716 [58:21<32:49,  1.16s/it]

 64%|██████▍   | 3021/4716 [58:23<32:50,  1.16s/it]

 64%|██████▍   | 3022/4716 [58:24<32:50,  1.16s/it]

 64%|██████▍   | 3023/4716 [58:25<32:48,  1.16s/it]

 64%|██████▍   | 3024/4716 [58:26<32:46,  1.16s/it]

 64%|██████▍   | 3025/4716 [58:27<32:44,  1.16s/it]

 64%|██████▍   | 3026/4716 [58:28<32:42,  1.16s/it]

 64%|██████▍   | 3027/4716 [58:30<32:42,  1.16s/it]

 64%|██████▍   | 3028/4716 [58:31<32:38,  1.16s/it]

 64%|██████▍   | 3029/4716 [58:32<32:39,  1.16s/it]

 64%|██████▍   | 3030/4716 [58:33<32:37,  1.16s/it]

 64%|██████▍   | 3031/4716 [58:34<32:38,  1.16s/it]

 64%|██████▍   | 3032/4716 [58:35<32:38,  1.16s/it]

 64%|██████▍   | 3033/4716 [58:37<32:37,  1.16s/it]

 64%|██████▍   | 3034/4716 [58:38<32:37,  1.16s/it]

 64%|██████▍   | 3035/4716 [58:39<32:34,  1.16s/it]

 64%|██████▍   | 3036/4716 [58:40<32:32,  1.16s/it]

 64%|██████▍   | 3037/4716 [58:41<32:31,  1.16s/it]

 64%|██████▍   | 3038/4716 [58:42<32:28,  1.16s/it]

 64%|██████▍   | 3039/4716 [58:44<32:27,  1.16s/it]

 64%|██████▍   | 3040/4716 [58:45<32:27,  1.16s/it]

 64%|██████▍   | 3041/4716 [58:46<32:27,  1.16s/it]

 65%|██████▍   | 3042/4716 [58:47<32:27,  1.16s/it]

 65%|██████▍   | 3043/4716 [58:48<32:26,  1.16s/it]

 65%|██████▍   | 3044/4716 [58:49<32:24,  1.16s/it]

 65%|██████▍   | 3045/4716 [58:50<32:23,  1.16s/it]

 65%|██████▍   | 3046/4716 [58:52<32:21,  1.16s/it]

 65%|██████▍   | 3047/4716 [58:53<32:18,  1.16s/it]

 65%|██████▍   | 3048/4716 [58:54<32:16,  1.16s/it]

 65%|██████▍   | 3049/4716 [58:55<32:16,  1.16s/it]

 65%|██████▍   | 3050/4716 [58:56<32:16,  1.16s/it]

 65%|██████▍   | 3051/4716 [58:57<32:15,  1.16s/it]

 65%|██████▍   | 3052/4716 [58:59<32:14,  1.16s/it]

 65%|██████▍   | 3053/4716 [59:00<32:13,  1.16s/it]

 65%|██████▍   | 3054/4716 [59:01<32:11,  1.16s/it]

 65%|██████▍   | 3055/4716 [59:02<32:10,  1.16s/it]

 65%|██████▍   | 3056/4716 [59:03<32:07,  1.16s/it]

 65%|██████▍   | 3057/4716 [59:04<32:09,  1.16s/it]

 65%|██████▍   | 3058/4716 [59:06<32:08,  1.16s/it]

 65%|██████▍   | 3059/4716 [59:07<32:08,  1.16s/it]

 65%|██████▍   | 3060/4716 [59:08<32:06,  1.16s/it]

 65%|██████▍   | 3061/4716 [59:09<32:04,  1.16s/it]

 65%|██████▍   | 3062/4716 [59:10<32:02,  1.16s/it]

 65%|██████▍   | 3063/4716 [59:11<31:59,  1.16s/it]

 65%|██████▍   | 3064/4716 [59:13<31:59,  1.16s/it]

 65%|██████▍   | 3065/4716 [59:14<31:57,  1.16s/it]

 65%|██████▌   | 3066/4716 [59:15<31:58,  1.16s/it]

 65%|██████▌   | 3067/4716 [59:16<31:59,  1.16s/it]

 65%|██████▌   | 3068/4716 [59:17<31:58,  1.16s/it]

 65%|██████▌   | 3069/4716 [59:18<31:58,  1.17s/it]

 65%|██████▌   | 3070/4716 [59:20<31:56,  1.16s/it]

 65%|██████▌   | 3071/4716 [59:21<31:55,  1.16s/it]

 65%|██████▌   | 3072/4716 [59:22<31:55,  1.17s/it]

 65%|██████▌   | 3073/4716 [59:23<31:52,  1.16s/it]

 65%|██████▌   | 3074/4716 [59:24<31:50,  1.16s/it]

 65%|██████▌   | 3075/4716 [59:25<31:48,  1.16s/it]

 65%|██████▌   | 3076/4716 [59:27<31:44,  1.16s/it]

 65%|██████▌   | 3077/4716 [59:28<31:44,  1.16s/it]

 65%|██████▌   | 3078/4716 [59:29<31:42,  1.16s/it]

 65%|██████▌   | 3079/4716 [59:30<31:41,  1.16s/it]

 65%|██████▌   | 3080/4716 [59:31<31:40,  1.16s/it]

 65%|██████▌   | 3081/4716 [59:32<31:38,  1.16s/it]

 65%|██████▌   | 3082/4716 [59:34<31:37,  1.16s/it]

 65%|██████▌   | 3083/4716 [59:35<31:36,  1.16s/it]

 65%|██████▌   | 3084/4716 [59:36<31:38,  1.16s/it]

 65%|██████▌   | 3085/4716 [59:37<31:37,  1.16s/it]

 65%|██████▌   | 3086/4716 [59:38<31:33,  1.16s/it]

 65%|██████▌   | 3087/4716 [59:39<31:30,  1.16s/it]

 65%|██████▌   | 3088/4716 [59:40<31:31,  1.16s/it]

 66%|██████▌   | 3089/4716 [59:42<31:30,  1.16s/it]

 66%|██████▌   | 3090/4716 [59:43<31:30,  1.16s/it]

 66%|██████▌   | 3091/4716 [59:44<31:28,  1.16s/it]

 66%|██████▌   | 3092/4716 [59:45<31:28,  1.16s/it]

 66%|██████▌   | 3093/4716 [59:46<31:25,  1.16s/it]

 66%|██████▌   | 3094/4716 [59:47<31:24,  1.16s/it]

 66%|██████▌   | 3095/4716 [59:49<31:24,  1.16s/it]

 66%|██████▌   | 3096/4716 [59:50<31:23,  1.16s/it]

 66%|██████▌   | 3097/4716 [59:51<31:22,  1.16s/it]

 66%|██████▌   | 3098/4716 [59:52<31:21,  1.16s/it]

 66%|██████▌   | 3099/4716 [59:53<31:18,  1.16s/it]

 66%|██████▌   | 3100/4716 [59:54<31:17,  1.16s/it]

 66%|██████▌   | 3101/4716 [59:56<31:15,  1.16s/it]

 66%|██████▌   | 3102/4716 [59:57<31:15,  1.16s/it]

 66%|██████▌   | 3103/4716 [59:58<31:14,  1.16s/it]

 66%|██████▌   | 3104/4716 [59:59<31:13,  1.16s/it]

 66%|██████▌   | 3105/4716 [1:00:00<31:12,  1.16s/it]

 66%|██████▌   | 3106/4716 [1:00:01<31:09,  1.16s/it]

 66%|██████▌   | 3107/4716 [1:00:03<31:07,  1.16s/it]

 66%|██████▌   | 3108/4716 [1:00:04<31:08,  1.16s/it]

 66%|██████▌   | 3109/4716 [1:00:05<31:08,  1.16s/it]

 66%|██████▌   | 3110/4716 [1:00:06<31:08,  1.16s/it]

 66%|██████▌   | 3111/4716 [1:00:07<31:07,  1.16s/it]

 66%|██████▌   | 3112/4716 [1:00:08<31:07,  1.16s/it]

 66%|██████▌   | 3113/4716 [1:00:10<31:06,  1.16s/it]

 66%|██████▌   | 3114/4716 [1:00:11<31:05,  1.16s/it]

 66%|██████▌   | 3115/4716 [1:00:12<31:02,  1.16s/it]

 66%|██████▌   | 3116/4716 [1:00:13<30:59,  1.16s/it]

 66%|██████▌   | 3117/4716 [1:00:14<30:57,  1.16s/it]

 66%|██████▌   | 3118/4716 [1:00:15<30:55,  1.16s/it]

 66%|██████▌   | 3119/4716 [1:00:17<30:52,  1.16s/it]

 66%|██████▌   | 3120/4716 [1:00:18<30:52,  1.16s/it]

 66%|██████▌   | 3121/4716 [1:00:19<30:49,  1.16s/it]

 66%|██████▌   | 3122/4716 [1:00:20<30:50,  1.16s/it]

 66%|██████▌   | 3123/4716 [1:00:21<30:49,  1.16s/it]

 66%|██████▌   | 3124/4716 [1:00:22<30:48,  1.16s/it]

 66%|██████▋   | 3125/4716 [1:00:23<30:50,  1.16s/it]

 66%|██████▋   | 3126/4716 [1:00:25<30:49,  1.16s/it]

 66%|██████▋   | 3127/4716 [1:00:26<30:48,  1.16s/it]

 66%|██████▋   | 3128/4716 [1:00:27<30:49,  1.16s/it]

 66%|██████▋   | 3129/4716 [1:00:28<30:45,  1.16s/it]

logging
logging the anndata

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 66%|██████▋   | 3130/4716 [1:00:30<33:23,  1.26s/it]

 66%|██████▋   | 3131/4716 [1:00:31<32:31,  1.23s/it]

 66%|██████▋   | 3132/4716 [1:00:32<31:53,  1.21s/it]

 66%|██████▋   | 3133/4716 [1:00:33<31:26,  1.19s/it]

 66%|██████▋   | 3134/4716 [1:00:34<31:07,  1.18s/it]

 66%|██████▋   | 3135/4716 [1:00:35<30:55,  1.17s/it]

 66%|██████▋   | 3136/4716 [1:00:37<30:47,  1.17s/it]

 67%|██████▋   | 3137/4716 [1:00:38<30:40,  1.17s/it]

 67%|██████▋   | 3138/4716 [1:00:39<30:35,  1.16s/it]

 67%|██████▋   | 3139/4716 [1:00:40<30:30,  1.16s/it]

 67%|██████▋   | 3140/4716 [1:00:41<30:25,  1.16s/it]

 67%|██████▋   | 3141/4716 [1:00:42<30:22,  1.16s/it]

 67%|██████▋   | 3142/4716 [1:00:43<30:20,  1.16s/it]

 67%|██████▋   | 3143/4716 [1:00:45<30:17,  1.16s/it]

 67%|██████▋   | 3144/4716 [1:00:46<30:18,  1.16s/it]

 67%|██████▋   | 3145/4716 [1:00:47<30:18,  1.16s/it]

 67%|██████▋   | 3146/4716 [1:00:48<30:17,  1.16s/it]

 67%|██████▋   | 3147/4716 [1:00:49<30:16,  1.16s/it]

 67%|██████▋   | 3148/4716 [1:00:50<30:14,  1.16s/it]

 67%|██████▋   | 3149/4716 [1:00:52<30:13,  1.16s/it]

 67%|██████▋   | 3150/4716 [1:00:53<30:14,  1.16s/it]

 67%|██████▋   | 3151/4716 [1:00:54<30:11,  1.16s/it]

 67%|██████▋   | 3152/4716 [1:00:55<30:09,  1.16s/it]

 67%|██████▋   | 3153/4716 [1:00:56<30:07,  1.16s/it]

 67%|██████▋   | 3154/4716 [1:00:57<30:05,  1.16s/it]

 67%|██████▋   | 3155/4716 [1:00:59<30:03,  1.16s/it]

 67%|██████▋   | 3156/4716 [1:01:00<30:03,  1.16s/it]

 67%|██████▋   | 3157/4716 [1:01:01<30:03,  1.16s/it]

 67%|██████▋   | 3158/4716 [1:01:02<30:01,  1.16s/it]

 67%|██████▋   | 3159/4716 [1:01:03<29:59,  1.16s/it]

 67%|██████▋   | 3160/4716 [1:01:04<29:58,  1.16s/it]

 67%|██████▋   | 3161/4716 [1:01:05<29:57,  1.16s/it]

 67%|██████▋   | 3162/4716 [1:01:07<29:55,  1.16s/it]

 67%|██████▋   | 3163/4716 [1:01:08<29:53,  1.16s/it]

 67%|██████▋   | 3164/4716 [1:01:09<29:54,  1.16s/it]

 67%|██████▋   | 3165/4716 [1:01:10<29:53,  1.16s/it]

 67%|██████▋   | 3166/4716 [1:01:11<29:53,  1.16s/it]

 67%|██████▋   | 3167/4716 [1:01:12<29:50,  1.16s/it]

 67%|██████▋   | 3168/4716 [1:01:14<29:49,  1.16s/it]

 67%|██████▋   | 3169/4716 [1:01:15<29:47,  1.16s/it]

 67%|██████▋   | 3170/4716 [1:01:16<29:46,  1.16s/it]

 67%|██████▋   | 3171/4716 [1:01:17<29:46,  1.16s/it]

 67%|██████▋   | 3172/4716 [1:01:18<29:44,  1.16s/it]

 67%|██████▋   | 3173/4716 [1:01:19<29:44,  1.16s/it]

 67%|██████▋   | 3174/4716 [1:01:21<29:44,  1.16s/it]

 67%|██████▋   | 3175/4716 [1:01:22<29:44,  1.16s/it]

 67%|██████▋   | 3176/4716 [1:01:23<29:43,  1.16s/it]

 67%|██████▋   | 3177/4716 [1:01:24<29:41,  1.16s/it]

 67%|██████▋   | 3178/4716 [1:01:25<29:40,  1.16s/it]

 67%|██████▋   | 3179/4716 [1:01:26<29:37,  1.16s/it]

 67%|██████▋   | 3180/4716 [1:01:27<29:35,  1.16s/it]

 67%|██████▋   | 3181/4716 [1:01:29<29:34,  1.16s/it]

 67%|██████▋   | 3182/4716 [1:01:30<29:34,  1.16s/it]

 67%|██████▋   | 3183/4716 [1:01:31<29:33,  1.16s/it]

 68%|██████▊   | 3184/4716 [1:01:32<29:31,  1.16s/it]

 68%|██████▊   | 3185/4716 [1:01:33<29:31,  1.16s/it]

 68%|██████▊   | 3186/4716 [1:01:34<29:29,  1.16s/it]

 68%|██████▊   | 3187/4716 [1:01:36<29:29,  1.16s/it]

 68%|██████▊   | 3188/4716 [1:01:37<29:26,  1.16s/it]

 68%|██████▊   | 3189/4716 [1:01:38<29:26,  1.16s/it]

 68%|██████▊   | 3190/4716 [1:01:39<29:25,  1.16s/it]

 68%|██████▊   | 3191/4716 [1:01:40<29:24,  1.16s/it]

 68%|██████▊   | 3192/4716 [1:01:41<29:23,  1.16s/it]

 68%|██████▊   | 3193/4716 [1:01:42<29:23,  1.16s/it]

 68%|██████▊   | 3194/4716 [1:01:44<29:22,  1.16s/it]

 68%|██████▊   | 3195/4716 [1:01:45<29:22,  1.16s/it]

 68%|██████▊   | 3196/4716 [1:01:46<29:21,  1.16s/it]

 68%|██████▊   | 3197/4716 [1:01:47<29:19,  1.16s/it]

 68%|██████▊   | 3198/4716 [1:01:48<29:15,  1.16s/it]

 68%|██████▊   | 3199/4716 [1:01:49<29:13,  1.16s/it]

 68%|██████▊   | 3200/4716 [1:01:51<29:12,  1.16s/it]

 68%|██████▊   | 3201/4716 [1:01:52<29:13,  1.16s/it]

 68%|██████▊   | 3202/4716 [1:01:53<29:11,  1.16s/it]

 68%|██████▊   | 3203/4716 [1:01:54<29:11,  1.16s/it]

 68%|██████▊   | 3204/4716 [1:01:55<29:10,  1.16s/it]

 68%|██████▊   | 3205/4716 [1:01:56<29:09,  1.16s/it]

 68%|██████▊   | 3206/4716 [1:01:58<29:07,  1.16s/it]

 68%|██████▊   | 3207/4716 [1:01:59<29:06,  1.16s/it]

 68%|██████▊   | 3208/4716 [1:02:00<29:05,  1.16s/it]

 68%|██████▊   | 3209/4716 [1:02:01<29:04,  1.16s/it]

 68%|██████▊   | 3210/4716 [1:02:02<29:03,  1.16s/it]

 68%|██████▊   | 3211/4716 [1:02:03<29:00,  1.16s/it]

 68%|██████▊   | 3212/4716 [1:02:04<28:58,  1.16s/it]

 68%|██████▊   | 3213/4716 [1:02:06<28:58,  1.16s/it]

 68%|██████▊   | 3214/4716 [1:02:07<28:58,  1.16s/it]

 68%|██████▊   | 3215/4716 [1:02:08<28:56,  1.16s/it]

 68%|██████▊   | 3216/4716 [1:02:09<28:55,  1.16s/it]

 68%|██████▊   | 3217/4716 [1:02:10<28:53,  1.16s/it]

 68%|██████▊   | 3218/4716 [1:02:11<28:52,  1.16s/it]

 68%|██████▊   | 3219/4716 [1:02:13<28:50,  1.16s/it]

 68%|██████▊   | 3220/4716 [1:02:14<28:48,  1.16s/it]

 68%|██████▊   | 3221/4716 [1:02:15<28:47,  1.16s/it]

 68%|██████▊   | 3222/4716 [1:02:16<28:48,  1.16s/it]

 68%|██████▊   | 3223/4716 [1:02:17<28:48,  1.16s/it]

 68%|██████▊   | 3224/4716 [1:02:18<28:47,  1.16s/it]

 68%|██████▊   | 3225/4716 [1:02:20<28:46,  1.16s/it]

 68%|██████▊   | 3226/4716 [1:02:21<28:44,  1.16s/it]

 68%|██████▊   | 3227/4716 [1:02:22<28:42,  1.16s/it]

 68%|██████▊   | 3228/4716 [1:02:23<28:41,  1.16s/it]

 68%|██████▊   | 3229/4716 [1:02:24<28:38,  1.16s/it]

 68%|██████▊   | 3230/4716 [1:02:25<28:39,  1.16s/it]

 69%|██████▊   | 3231/4716 [1:02:26<28:39,  1.16s/it]

 69%|██████▊   | 3232/4716 [1:02:28<28:37,  1.16s/it]

 69%|██████▊   | 3233/4716 [1:02:29<28:36,  1.16s/it]

 69%|██████▊   | 3234/4716 [1:02:30<28:33,  1.16s/it]

 69%|██████▊   | 3235/4716 [1:02:31<28:34,  1.16s/it]

 69%|██████▊   | 3236/4716 [1:02:32<28:34,  1.16s/it]

 69%|██████▊   | 3237/4716 [1:02:33<28:32,  1.16s/it]

 69%|██████▊   | 3238/4716 [1:02:35<28:29,  1.16s/it]

 69%|██████▊   | 3239/4716 [1:02:36<28:29,  1.16s/it]

 69%|██████▊   | 3240/4716 [1:02:37<28:27,  1.16s/it]

 69%|██████▊   | 3241/4716 [1:02:38<28:26,  1.16s/it]

 69%|██████▊   | 3242/4716 [1:02:39<28:25,  1.16s/it]

 69%|██████▉   | 3243/4716 [1:02:40<28:24,  1.16s/it]

 69%|██████▉   | 3244/4716 [1:02:42<28:23,  1.16s/it]

 69%|██████▉   | 3245/4716 [1:02:43<28:20,  1.16s/it]

 69%|██████▉   | 3246/4716 [1:02:44<28:20,  1.16s/it]

 69%|██████▉   | 3247/4716 [1:02:45<28:17,  1.16s/it]

 69%|██████▉   | 3248/4716 [1:02:46<28:17,  1.16s/it]

 69%|██████▉   | 3249/4716 [1:02:47<28:17,  1.16s/it]

 69%|██████▉   | 3250/4716 [1:02:48<28:15,  1.16s/it]

 69%|██████▉   | 3251/4716 [1:02:50<28:16,  1.16s/it]

 69%|██████▉   | 3252/4716 [1:02:51<28:15,  1.16s/it]

 69%|██████▉   | 3253/4716 [1:02:52<28:16,  1.16s/it]

 69%|██████▉   | 3254/4716 [1:02:53<28:12,  1.16s/it]

 69%|██████▉   | 3255/4716 [1:02:54<28:11,  1.16s/it]

 69%|██████▉   | 3256/4716 [1:02:55<28:10,  1.16s/it]

 69%|██████▉   | 3257/4716 [1:02:57<28:06,  1.16s/it]

 69%|██████▉   | 3258/4716 [1:02:58<28:05,  1.16s/it]

 69%|██████▉   | 3259/4716 [1:02:59<28:04,  1.16s/it]

 69%|██████▉   | 3260/4716 [1:03:00<28:04,  1.16s/it]

 69%|██████▉   | 3261/4716 [1:03:01<28:05,  1.16s/it]

 69%|██████▉   | 3262/4716 [1:03:02<28:04,  1.16s/it]

 69%|██████▉   | 3263/4716 [1:03:03<28:04,  1.16s/it]

 69%|██████▉   | 3264/4716 [1:03:05<28:02,  1.16s/it]

 69%|██████▉   | 3265/4716 [1:03:06<28:01,  1.16s/it]

 69%|██████▉   | 3266/4716 [1:03:07<28:01,  1.16s/it]

 69%|██████▉   | 3267/4716 [1:03:08<28:01,  1.16s/it]

 69%|██████▉   | 3268/4716 [1:03:09<27:57,  1.16s/it]

 69%|██████▉   | 3269/4716 [1:03:10<27:56,  1.16s/it]

 69%|██████▉   | 3270/4716 [1:03:12<27:53,  1.16s/it]

 69%|██████▉   | 3271/4716 [1:03:13<27:51,  1.16s/it]

 69%|██████▉   | 3272/4716 [1:03:14<27:49,  1.16s/it]

 69%|██████▉   | 3273/4716 [1:03:15<27:48,  1.16s/it]

 69%|██████▉   | 3274/4716 [1:03:16<27:47,  1.16s/it]

 69%|██████▉   | 3275/4716 [1:03:17<27:47,  1.16s/it]

 69%|██████▉   | 3276/4716 [1:03:19<27:46,  1.16s/it]

 69%|██████▉   | 3277/4716 [1:03:20<27:47,  1.16s/it]

 70%|██████▉   | 3278/4716 [1:03:21<27:45,  1.16s/it]

 70%|██████▉   | 3279/4716 [1:03:22<27:43,  1.16s/it]

 70%|██████▉   | 3280/4716 [1:03:23<27:41,  1.16s/it]

 70%|██████▉   | 3281/4716 [1:03:24<27:39,  1.16s/it]

 70%|██████▉   | 3282/4716 [1:03:25<27:38,  1.16s/it]

 70%|██████▉   | 3283/4716 [1:03:27<27:38,  1.16s/it]

 70%|██████▉   | 3284/4716 [1:03:28<27:35,  1.16s/it]

 70%|██████▉   | 3285/4716 [1:03:29<27:36,  1.16s/it]

 70%|██████▉   | 3286/4716 [1:03:30<27:36,  1.16s/it]

 70%|██████▉   | 3287/4716 [1:03:31<27:33,  1.16s/it]

 70%|██████▉   | 3288/4716 [1:03:32<27:31,  1.16s/it]

 70%|██████▉   | 3289/4716 [1:03:34<27:30,  1.16s/it]

 70%|██████▉   | 3290/4716 [1:03:35<27:29,  1.16s/it]

 70%|██████▉   | 3291/4716 [1:03:36<27:29,  1.16s/it]

 70%|██████▉   | 3292/4716 [1:03:37<27:28,  1.16s/it]

 70%|██████▉   | 3293/4716 [1:03:38<27:29,  1.16s/it]

 70%|██████▉   | 3294/4716 [1:03:39<27:27,  1.16s/it]

 70%|██████▉   | 3295/4716 [1:03:41<27:27,  1.16s/it]

 70%|██████▉   | 3296/4716 [1:03:42<27:25,  1.16s/it]

 70%|██████▉   | 3297/4716 [1:03:43<27:25,  1.16s/it]

 70%|██████▉   | 3298/4716 [1:03:44<27:22,  1.16s/it]

 70%|██████▉   | 3299/4716 [1:03:45<27:20,  1.16s/it]

 70%|██████▉   | 3300/4716 [1:03:46<27:18,  1.16s/it]

 70%|██████▉   | 3301/4716 [1:03:47<27:18,  1.16s/it]

 70%|███████   | 3302/4716 [1:03:49<27:17,  1.16s/it]

 70%|███████   | 3303/4716 [1:03:50<27:16,  1.16s/it]

 70%|███████   | 3304/4716 [1:03:51<27:15,  1.16s/it]

 70%|███████   | 3305/4716 [1:03:52<27:14,  1.16s/it]

 70%|███████   | 3306/4716 [1:03:53<27:12,  1.16s/it]

 70%|███████   | 3307/4716 [1:03:54<27:11,  1.16s/it]

 70%|███████   | 3308/4716 [1:03:56<27:10,  1.16s/it]

 70%|███████   | 3309/4716 [1:03:57<27:06,  1.16s/it]

 70%|███████   | 3310/4716 [1:03:58<27:06,  1.16s/it]

 70%|███████   | 3311/4716 [1:03:59<27:06,  1.16s/it]

 70%|███████   | 3312/4716 [1:04:00<27:05,  1.16s/it]

 70%|███████   | 3313/4716 [1:04:01<27:04,  1.16s/it]

 70%|███████   | 3314/4716 [1:04:03<27:03,  1.16s/it]

 70%|███████   | 3315/4716 [1:04:04<27:01,  1.16s/it]

 70%|███████   | 3316/4716 [1:04:05<27:00,  1.16s/it]

 70%|███████   | 3317/4716 [1:04:06<26:59,  1.16s/it]

 70%|███████   | 3318/4716 [1:04:07<27:00,  1.16s/it]

 70%|███████   | 3319/4716 [1:04:08<26:59,  1.16s/it]

 70%|███████   | 3320/4716 [1:04:09<27:00,  1.16s/it]

 70%|███████   | 3321/4716 [1:04:11<26:59,  1.16s/it]

 70%|███████   | 3322/4716 [1:04:12<26:57,  1.16s/it]

 70%|███████   | 3323/4716 [1:04:13<26:55,  1.16s/it]

 70%|███████   | 3324/4716 [1:04:14<26:54,  1.16s/it]

 71%|███████   | 3325/4716 [1:04:15<26:54,  1.16s/it]

 71%|███████   | 3326/4716 [1:04:16<26:52,  1.16s/it]

 71%|███████   | 3327/4716 [1:04:18<26:50,  1.16s/it]

 71%|███████   | 3328/4716 [1:04:19<26:48,  1.16s/it]

 71%|███████   | 3329/4716 [1:04:20<26:48,  1.16s/it]

 71%|███████   | 3330/4716 [1:04:21<26:45,  1.16s/it]

 71%|███████   | 3331/4716 [1:04:22<26:45,  1.16s/it]

 71%|███████   | 3332/4716 [1:04:23<26:44,  1.16s/it]

 71%|███████   | 3333/4716 [1:04:25<26:41,  1.16s/it]

 71%|███████   | 3334/4716 [1:04:26<26:40,  1.16s/it]

 71%|███████   | 3335/4716 [1:04:27<26:39,  1.16s/it]

 71%|███████   | 3336/4716 [1:04:28<26:38,  1.16s/it]

 71%|███████   | 3337/4716 [1:04:29<26:37,  1.16s/it]

 71%|███████   | 3338/4716 [1:04:30<26:37,  1.16s/it]

 71%|███████   | 3339/4716 [1:04:32<26:39,  1.16s/it]

 71%|███████   | 3340/4716 [1:04:33<26:36,  1.16s/it]

 71%|███████   | 3341/4716 [1:04:34<26:34,  1.16s/it]

 71%|███████   | 3342/4716 [1:04:35<26:33,  1.16s/it]

 71%|███████   | 3343/4716 [1:04:36<26:30,  1.16s/it]

 71%|███████   | 3344/4716 [1:04:37<26:28,  1.16s/it]

 71%|███████   | 3345/4716 [1:04:38<26:28,  1.16s/it]

 71%|███████   | 3346/4716 [1:04:40<26:26,  1.16s/it]

 71%|███████   | 3347/4716 [1:04:41<26:25,  1.16s/it]

 71%|███████   | 3348/4716 [1:04:42<26:25,  1.16s/it]

 71%|███████   | 3349/4716 [1:04:43<26:24,  1.16s/it]

 71%|███████   | 3350/4716 [1:04:44<26:21,  1.16s/it]

 71%|███████   | 3351/4716 [1:04:45<26:20,  1.16s/it]

 71%|███████   | 3352/4716 [1:04:47<26:19,  1.16s/it]

 71%|███████   | 3353/4716 [1:04:48<26:17,  1.16s/it]

 71%|███████   | 3354/4716 [1:04:49<26:16,  1.16s/it]

 71%|███████   | 3355/4716 [1:04:50<26:15,  1.16s/it]

 71%|███████   | 3356/4716 [1:04:51<26:15,  1.16s/it]

 71%|███████   | 3357/4716 [1:04:52<26:15,  1.16s/it]

 71%|███████   | 3358/4716 [1:04:54<26:13,  1.16s/it]

 71%|███████   | 3359/4716 [1:04:55<26:12,  1.16s/it]

 71%|███████   | 3360/4716 [1:04:56<26:11,  1.16s/it]

 71%|███████▏  | 3361/4716 [1:04:57<26:11,  1.16s/it]

 71%|███████▏  | 3362/4716 [1:04:58<26:10,  1.16s/it]

 71%|███████▏  | 3363/4716 [1:04:59<26:06,  1.16s/it]

 71%|███████▏  | 3364/4716 [1:05:00<26:05,  1.16s/it]

 71%|███████▏  | 3365/4716 [1:05:02<26:04,  1.16s/it]

 71%|███████▏  | 3366/4716 [1:05:03<26:03,  1.16s/it]

 71%|███████▏  | 3367/4716 [1:05:04<26:03,  1.16s/it]

 71%|███████▏  | 3368/4716 [1:05:05<26:02,  1.16s/it]

 71%|███████▏  | 3369/4716 [1:05:06<26:01,  1.16s/it]

 71%|███████▏  | 3370/4716 [1:05:07<26:02,  1.16s/it]

 71%|███████▏  | 3371/4716 [1:05:09<25:59,  1.16s/it]

 72%|███████▏  | 3372/4716 [1:05:10<25:58,  1.16s/it]

 72%|███████▏  | 3373/4716 [1:05:11<25:57,  1.16s/it]

 72%|███████▏  | 3374/4716 [1:05:12<25:55,  1.16s/it]

 72%|███████▏  | 3375/4716 [1:05:13<25:55,  1.16s/it]

 72%|███████▏  | 3376/4716 [1:05:14<25:58,  1.16s/it]

 72%|███████▏  | 3377/4716 [1:05:16<26:12,  1.17s/it]

 72%|███████▏  | 3378/4716 [1:05:17<26:09,  1.17s/it]

 72%|███████▏  | 3379/4716 [1:05:18<26:04,  1.17s/it]

 72%|███████▏  | 3380/4716 [1:05:19<26:01,  1.17s/it]

 72%|███████▏  | 3381/4716 [1:05:20<25:59,  1.17s/it]

 72%|███████▏  | 3382/4716 [1:05:21<25:55,  1.17s/it]

 72%|███████▏  | 3383/4716 [1:05:23<25:50,  1.16s/it]

 72%|███████▏  | 3384/4716 [1:05:24<25:48,  1.16s/it]

 72%|███████▏  | 3385/4716 [1:05:25<25:45,  1.16s/it]

 72%|███████▏  | 3386/4716 [1:05:26<25:44,  1.16s/it]

 72%|███████▏  | 3387/4716 [1:05:27<25:42,  1.16s/it]

 72%|███████▏  | 3388/4716 [1:05:28<25:40,  1.16s/it]

 72%|███████▏  | 3389/4716 [1:05:30<25:41,  1.16s/it]

 72%|███████▏  | 3390/4716 [1:05:31<25:39,  1.16s/it]

 72%|███████▏  | 3391/4716 [1:05:32<25:36,  1.16s/it]

 72%|███████▏  | 3392/4716 [1:05:33<25:34,  1.16s/it]

 72%|███████▏  | 3393/4716 [1:05:34<25:33,  1.16s/it]

 72%|███████▏  | 3394/4716 [1:05:35<25:31,  1.16s/it]

 72%|███████▏  | 3395/4716 [1:05:37<25:30,  1.16s/it]

 72%|███████▏  | 3396/4716 [1:05:38<25:29,  1.16s/it]

 72%|███████▏  | 3397/4716 [1:05:39<25:29,  1.16s/it]

 72%|███████▏  | 3398/4716 [1:05:40<25:29,  1.16s/it]

 72%|███████▏  | 3399/4716 [1:05:41<25:26,  1.16s/it]

 72%|███████▏  | 3400/4716 [1:05:42<25:26,  1.16s/it]

 72%|███████▏  | 3401/4716 [1:05:43<25:24,  1.16s/it]

 72%|███████▏  | 3402/4716 [1:05:45<25:23,  1.16s/it]

 72%|███████▏  | 3403/4716 [1:05:46<25:21,  1.16s/it]

 72%|███████▏  | 3404/4716 [1:05:47<25:20,  1.16s/it]

 72%|███████▏  | 3405/4716 [1:05:48<25:20,  1.16s/it]

 72%|███████▏  | 3406/4716 [1:05:49<25:18,  1.16s/it]

 72%|███████▏  | 3407/4716 [1:05:50<25:18,  1.16s/it]

 72%|███████▏  | 3408/4716 [1:05:52<25:17,  1.16s/it]

 72%|███████▏  | 3409/4716 [1:05:53<25:16,  1.16s/it]

 72%|███████▏  | 3410/4716 [1:05:54<25:14,  1.16s/it]

 72%|███████▏  | 3411/4716 [1:05:55<25:12,  1.16s/it]

 72%|███████▏  | 3412/4716 [1:05:56<25:11,  1.16s/it]

 72%|███████▏  | 3413/4716 [1:05:57<25:09,  1.16s/it]

 72%|███████▏  | 3414/4716 [1:05:59<25:08,  1.16s/it]

 72%|███████▏  | 3415/4716 [1:06:00<25:08,  1.16s/it]

 72%|███████▏  | 3416/4716 [1:06:01<25:07,  1.16s/it]

 72%|███████▏  | 3417/4716 [1:06:02<25:05,  1.16s/it]

 72%|███████▏  | 3418/4716 [1:06:03<25:06,  1.16s/it]

 72%|███████▏  | 3419/4716 [1:06:04<25:05,  1.16s/it]

 73%|███████▎  | 3420/4716 [1:06:05<25:03,  1.16s/it]

 73%|███████▎  | 3421/4716 [1:06:07<25:04,  1.16s/it]

 73%|███████▎  | 3422/4716 [1:06:08<25:02,  1.16s/it]

 73%|███████▎  | 3423/4716 [1:06:09<25:01,  1.16s/it]

 73%|███████▎  | 3424/4716 [1:06:10<24:59,  1.16s/it]

 73%|███████▎  | 3425/4716 [1:06:11<24:56,  1.16s/it]

 73%|███████▎  | 3426/4716 [1:06:12<24:55,  1.16s/it]

 73%|███████▎  | 3427/4716 [1:06:14<24:54,  1.16s/it]

 73%|███████▎  | 3428/4716 [1:06:15<24:55,  1.16s/it]

 73%|███████▎  | 3429/4716 [1:06:16<24:53,  1.16s/it]

 73%|███████▎  | 3430/4716 [1:06:17<24:52,  1.16s/it]

 73%|███████▎  | 3431/4716 [1:06:18<24:51,  1.16s/it]

 73%|███████▎  | 3432/4716 [1:06:19<24:51,  1.16s/it]

 73%|███████▎  | 3433/4716 [1:06:21<24:48,  1.16s/it]

 73%|███████▎  | 3434/4716 [1:06:22<24:47,  1.16s/it]

 73%|███████▎  | 3435/4716 [1:06:23<24:46,  1.16s/it]

 73%|███████▎  | 3436/4716 [1:06:24<24:45,  1.16s/it]

 73%|███████▎  | 3437/4716 [1:06:25<24:44,  1.16s/it]

 73%|███████▎  | 3438/4716 [1:06:26<24:43,  1.16s/it]

 73%|███████▎  | 3439/4716 [1:06:28<24:46,  1.16s/it]

 73%|███████▎  | 3440/4716 [1:06:29<24:45,  1.16s/it]

 73%|███████▎  | 3441/4716 [1:06:30<24:41,  1.16s/it]

 73%|███████▎  | 3442/4716 [1:06:31<24:40,  1.16s/it]

 73%|███████▎  | 3443/4716 [1:06:32<24:36,  1.16s/it]

 73%|███████▎  | 3444/4716 [1:06:33<24:35,  1.16s/it]

 73%|███████▎  | 3445/4716 [1:06:35<24:34,  1.16s/it]

 73%|███████▎  | 3446/4716 [1:06:36<24:32,  1.16s/it]

 73%|███████▎  | 3447/4716 [1:06:37<24:32,  1.16s/it]

 73%|███████▎  | 3448/4716 [1:06:38<24:34,  1.16s/it]

 73%|███████▎  | 3449/4716 [1:06:39<24:32,  1.16s/it]

 73%|███████▎  | 3450/4716 [1:06:40<24:30,  1.16s/it]

 73%|███████▎  | 3451/4716 [1:06:41<24:26,  1.16s/it]

 73%|███████▎  | 3452/4716 [1:06:43<24:26,  1.16s/it]

 73%|███████▎  | 3453/4716 [1:06:44<24:25,  1.16s/it]

 73%|███████▎  | 3454/4716 [1:06:45<24:23,  1.16s/it]

 73%|███████▎  | 3455/4716 [1:06:46<24:21,  1.16s/it]

 73%|███████▎  | 3456/4716 [1:06:47<24:21,  1.16s/it]

 73%|███████▎  | 3457/4716 [1:06:48<24:20,  1.16s/it]

 73%|███████▎  | 3458/4716 [1:06:50<24:19,  1.16s/it]

 73%|███████▎  | 3459/4716 [1:06:51<24:17,  1.16s/it]

 73%|███████▎  | 3460/4716 [1:06:52<24:16,  1.16s/it]

 73%|███████▎  | 3461/4716 [1:06:53<24:15,  1.16s/it]

 73%|███████▎  | 3462/4716 [1:06:54<24:14,  1.16s/it]

 73%|███████▎  | 3463/4716 [1:06:55<24:12,  1.16s/it]

 73%|███████▎  | 3464/4716 [1:06:57<24:12,  1.16s/it]

 73%|███████▎  | 3465/4716 [1:06:58<24:10,  1.16s/it]

 73%|███████▎  | 3466/4716 [1:06:59<24:10,  1.16s/it]

 74%|███████▎  | 3467/4716 [1:07:00<24:08,  1.16s/it]

 74%|███████▎  | 3468/4716 [1:07:01<24:07,  1.16s/it]

 74%|███████▎  | 3469/4716 [1:07:02<24:05,  1.16s/it]

 74%|███████▎  | 3470/4716 [1:07:04<24:05,  1.16s/it]

 74%|███████▎  | 3471/4716 [1:07:05<24:06,  1.16s/it]

 74%|███████▎  | 3472/4716 [1:07:06<24:03,  1.16s/it]

 74%|███████▎  | 3473/4716 [1:07:07<24:01,  1.16s/it]

 74%|███████▎  | 3474/4716 [1:07:08<24:00,  1.16s/it]

 74%|███████▎  | 3475/4716 [1:07:09<24:00,  1.16s/it]

 74%|███████▎  | 3476/4716 [1:07:10<23:59,  1.16s/it]

 74%|███████▎  | 3477/4716 [1:07:12<23:57,  1.16s/it]

 74%|███████▎  | 3478/4716 [1:07:13<23:56,  1.16s/it]

 74%|███████▍  | 3479/4716 [1:07:14<23:55,  1.16s/it]

 74%|███████▍  | 3480/4716 [1:07:15<23:55,  1.16s/it]

 74%|███████▍  | 3481/4716 [1:07:16<23:54,  1.16s/it]

 74%|███████▍  | 3482/4716 [1:07:17<23:52,  1.16s/it]

 74%|███████▍  | 3483/4716 [1:07:19<23:52,  1.16s/it]

 74%|███████▍  | 3484/4716 [1:07:20<23:51,  1.16s/it]

 74%|███████▍  | 3485/4716 [1:07:21<23:49,  1.16s/it]

 74%|███████▍  | 3486/4716 [1:07:22<23:47,  1.16s/it]

 74%|███████▍  | 3487/4716 [1:07:23<23:45,  1.16s/it]

 74%|███████▍  | 3488/4716 [1:07:24<23:44,  1.16s/it]

 74%|███████▍  | 3489/4716 [1:07:26<23:44,  1.16s/it]

 74%|███████▍  | 3490/4716 [1:07:27<23:44,  1.16s/it]

 74%|███████▍  | 3491/4716 [1:07:28<23:42,  1.16s/it]

 74%|███████▍  | 3492/4716 [1:07:29<23:40,  1.16s/it]

 74%|███████▍  | 3493/4716 [1:07:30<23:41,  1.16s/it]

 74%|███████▍  | 3494/4716 [1:07:31<23:39,  1.16s/it]

 74%|███████▍  | 3495/4716 [1:07:33<23:38,  1.16s/it]

 74%|███████▍  | 3496/4716 [1:07:34<23:37,  1.16s/it]

 74%|███████▍  | 3497/4716 [1:07:35<23:37,  1.16s/it]

 74%|███████▍  | 3498/4716 [1:07:36<23:36,  1.16s/it]

 74%|███████▍  | 3499/4716 [1:07:37<23:36,  1.16s/it]

 74%|███████▍  | 3500/4716 [1:07:38<23:33,  1.16s/it]

 74%|███████▍  | 3501/4716 [1:07:40<23:30,  1.16s/it]

 74%|███████▍  | 3502/4716 [1:07:41<23:28,  1.16s/it]

 74%|███████▍  | 3503/4716 [1:07:42<23:26,  1.16s/it]

 74%|███████▍  | 3504/4716 [1:07:43<23:24,  1.16s/it]

 74%|███████▍  | 3505/4716 [1:07:44<23:25,  1.16s/it]

 74%|███████▍  | 3506/4716 [1:07:45<23:24,  1.16s/it]

 74%|███████▍  | 3507/4716 [1:07:46<23:23,  1.16s/it]

 74%|███████▍  | 3508/4716 [1:07:48<23:25,  1.16s/it]

 74%|███████▍  | 3509/4716 [1:07:49<23:22,  1.16s/it]

 74%|███████▍  | 3510/4716 [1:07:50<23:21,  1.16s/it]

 74%|███████▍  | 3511/4716 [1:07:51<23:18,  1.16s/it]

 74%|███████▍  | 3512/4716 [1:07:52<23:18,  1.16s/it]

 74%|███████▍  | 3513/4716 [1:07:53<23:17,  1.16s/it]

 75%|███████▍  | 3514/4716 [1:07:55<23:14,  1.16s/it]

 75%|███████▍  | 3515/4716 [1:07:56<23:13,  1.16s/it]

 75%|███████▍  | 3516/4716 [1:07:57<23:12,  1.16s/it]

 75%|███████▍  | 3517/4716 [1:07:58<23:12,  1.16s/it]

 75%|███████▍  | 3518/4716 [1:07:59<23:11,  1.16s/it]

 75%|███████▍  | 3519/4716 [1:08:00<23:11,  1.16s/it]

 75%|███████▍  | 3520/4716 [1:08:02<23:11,  1.16s/it]

 75%|███████▍  | 3521/4716 [1:08:03<23:10,  1.16s/it]

 75%|███████▍  | 3522/4716 [1:08:04<23:07,  1.16s/it]

 75%|███████▍  | 3523/4716 [1:08:05<23:05,  1.16s/it]

 75%|███████▍  | 3524/4716 [1:08:06<23:03,  1.16s/it]

 75%|███████▍  | 3525/4716 [1:08:07<23:03,  1.16s/it]

 75%|███████▍  | 3526/4716 [1:08:09<23:02,  1.16s/it]

 75%|███████▍  | 3527/4716 [1:08:10<23:01,  1.16s/it]

 75%|███████▍  | 3528/4716 [1:08:11<22:59,  1.16s/it]

 75%|███████▍  | 3529/4716 [1:08:12<22:57,  1.16s/it]

 75%|███████▍  | 3530/4716 [1:08:13<22:57,  1.16s/it]

 75%|███████▍  | 3531/4716 [1:08:14<22:56,  1.16s/it]

 75%|███████▍  | 3532/4716 [1:08:16<22:55,  1.16s/it]

 75%|███████▍  | 3533/4716 [1:08:17<22:55,  1.16s/it]

 75%|███████▍  | 3534/4716 [1:08:18<22:54,  1.16s/it]

 75%|███████▍  | 3535/4716 [1:08:19<22:51,  1.16s/it]

 75%|███████▍  | 3536/4716 [1:08:20<22:49,  1.16s/it]

 75%|███████▌  | 3537/4716 [1:08:21<22:50,  1.16s/it]

 75%|███████▌  | 3538/4716 [1:08:23<22:49,  1.16s/it]

 75%|███████▌  | 3539/4716 [1:08:24<22:47,  1.16s/it]

 75%|███████▌  | 3540/4716 [1:08:25<22:44,  1.16s/it]

 75%|███████▌  | 3541/4716 [1:08:26<22:42,  1.16s/it]

 75%|███████▌  | 3542/4716 [1:08:27<22:43,  1.16s/it]

 75%|███████▌  | 3543/4716 [1:08:28<22:43,  1.16s/it]

 75%|███████▌  | 3544/4716 [1:08:29<22:42,  1.16s/it]

 75%|███████▌  | 3545/4716 [1:08:31<22:41,  1.16s/it]

 75%|███████▌  | 3546/4716 [1:08:32<22:41,  1.16s/it]

 75%|███████▌  | 3547/4716 [1:08:33<22:39,  1.16s/it]

 75%|███████▌  | 3548/4716 [1:08:34<22:36,  1.16s/it]

 75%|███████▌  | 3549/4716 [1:08:35<22:35,  1.16s/it]

 75%|███████▌  | 3550/4716 [1:08:36<22:33,  1.16s/it]

 75%|███████▌  | 3551/4716 [1:08:38<22:32,  1.16s/it]

 75%|███████▌  | 3552/4716 [1:08:39<22:31,  1.16s/it]

 75%|███████▌  | 3553/4716 [1:08:40<22:31,  1.16s/it]

 75%|███████▌  | 3554/4716 [1:08:41<22:29,  1.16s/it]

 75%|███████▌  | 3555/4716 [1:08:42<22:30,  1.16s/it]

 75%|███████▌  | 3556/4716 [1:08:43<22:30,  1.16s/it]

 75%|███████▌  | 3557/4716 [1:08:45<22:27,  1.16s/it]

 75%|███████▌  | 3558/4716 [1:08:46<22:25,  1.16s/it]

 75%|███████▌  | 3559/4716 [1:08:47<22:23,  1.16s/it]

 75%|███████▌  | 3560/4716 [1:08:48<22:22,  1.16s/it]

 76%|███████▌  | 3561/4716 [1:08:49<22:20,  1.16s/it]

 76%|███████▌  | 3562/4716 [1:08:50<22:19,  1.16s/it]

 76%|███████▌  | 3563/4716 [1:08:52<22:18,  1.16s/it]

 76%|███████▌  | 3564/4716 [1:08:53<22:18,  1.16s/it]

 76%|███████▌  | 3565/4716 [1:08:54<22:18,  1.16s/it]

 76%|███████▌  | 3566/4716 [1:08:55<22:17,  1.16s/it]

 76%|███████▌  | 3567/4716 [1:08:56<22:14,  1.16s/it]

 76%|███████▌  | 3568/4716 [1:08:57<22:12,  1.16s/it]

 76%|███████▌  | 3569/4716 [1:08:59<22:11,  1.16s/it]

 76%|███████▌  | 3570/4716 [1:09:00<22:10,  1.16s/it]

 76%|███████▌  | 3571/4716 [1:09:01<22:08,  1.16s/it]

 76%|███████▌  | 3572/4716 [1:09:02<22:08,  1.16s/it]

 76%|███████▌  | 3573/4716 [1:09:03<22:07,  1.16s/it]

 76%|███████▌  | 3574/4716 [1:09:04<22:06,  1.16s/it]

 76%|███████▌  | 3575/4716 [1:09:05<22:05,  1.16s/it]

 76%|███████▌  | 3576/4716 [1:09:07<22:05,  1.16s/it]

 76%|███████▌  | 3577/4716 [1:09:08<22:04,  1.16s/it]

 76%|███████▌  | 3578/4716 [1:09:09<22:02,  1.16s/it]

 76%|███████▌  | 3579/4716 [1:09:10<22:01,  1.16s/it]

 76%|███████▌  | 3580/4716 [1:09:11<22:00,  1.16s/it]

 76%|███████▌  | 3581/4716 [1:09:12<21:58,  1.16s/it]

 76%|███████▌  | 3582/4716 [1:09:14<21:56,  1.16s/it]

 76%|███████▌  | 3583/4716 [1:09:15<21:55,  1.16s/it]

 76%|███████▌  | 3584/4716 [1:09:16<21:54,  1.16s/it]

 76%|███████▌  | 3585/4716 [1:09:17<21:53,  1.16s/it]

 76%|███████▌  | 3586/4716 [1:09:18<21:53,  1.16s/it]

 76%|███████▌  | 3587/4716 [1:09:19<21:52,  1.16s/it]

 76%|███████▌  | 3588/4716 [1:09:21<21:51,  1.16s/it]

 76%|███████▌  | 3589/4716 [1:09:22<21:49,  1.16s/it]

 76%|███████▌  | 3590/4716 [1:09:23<21:49,  1.16s/it]

 76%|███████▌  | 3591/4716 [1:09:24<21:48,  1.16s/it]

 76%|███████▌  | 3592/4716 [1:09:25<21:46,  1.16s/it]

 76%|███████▌  | 3593/4716 [1:09:26<21:45,  1.16s/it]

 76%|███████▌  | 3594/4716 [1:09:28<21:44,  1.16s/it]

 76%|███████▌  | 3595/4716 [1:09:29<21:42,  1.16s/it]

 76%|███████▋  | 3596/4716 [1:09:30<21:41,  1.16s/it]

 76%|███████▋  | 3597/4716 [1:09:31<21:40,  1.16s/it]

 76%|███████▋  | 3598/4716 [1:09:32<21:39,  1.16s/it]

 76%|███████▋  | 3599/4716 [1:09:33<21:38,  1.16s/it]

 76%|███████▋  | 3600/4716 [1:09:35<21:39,  1.16s/it]

 76%|███████▋  | 3601/4716 [1:09:36<21:38,  1.16s/it]

 76%|███████▋  | 3602/4716 [1:09:37<21:36,  1.16s/it]

 76%|███████▋  | 3603/4716 [1:09:38<21:35,  1.16s/it]

 76%|███████▋  | 3604/4716 [1:09:39<21:34,  1.16s/it]

 76%|███████▋  | 3605/4716 [1:09:40<21:32,  1.16s/it]

 76%|███████▋  | 3606/4716 [1:09:42<21:30,  1.16s/it]

 76%|███████▋  | 3607/4716 [1:09:43<21:28,  1.16s/it]

 77%|███████▋  | 3608/4716 [1:09:44<21:27,  1.16s/it]

 77%|███████▋  | 3609/4716 [1:09:45<21:27,  1.16s/it]

 77%|███████▋  | 3610/4716 [1:09:46<21:26,  1.16s/it]

 77%|███████▋  | 3611/4716 [1:09:47<21:24,  1.16s/it]

 77%|███████▋  | 3612/4716 [1:09:49<21:24,  1.16s/it]

 77%|███████▋  | 3613/4716 [1:09:50<21:23,  1.16s/it]

 77%|███████▋  | 3614/4716 [1:09:51<21:21,  1.16s/it]

 77%|███████▋  | 3615/4716 [1:09:52<21:18,  1.16s/it]

 77%|███████▋  | 3616/4716 [1:09:53<21:17,  1.16s/it]

 77%|███████▋  | 3617/4716 [1:09:54<21:17,  1.16s/it]

 77%|███████▋  | 3618/4716 [1:09:55<21:15,  1.16s/it]

 77%|███████▋  | 3619/4716 [1:09:57<21:14,  1.16s/it]

 77%|███████▋  | 3620/4716 [1:09:58<21:14,  1.16s/it]

 77%|███████▋  | 3621/4716 [1:09:59<21:13,  1.16s/it]

 77%|███████▋  | 3622/4716 [1:10:00<21:11,  1.16s/it]

 77%|███████▋  | 3623/4716 [1:10:01<21:09,  1.16s/it]

 77%|███████▋  | 3624/4716 [1:10:02<21:07,  1.16s/it]

 77%|███████▋  | 3625/4716 [1:10:04<21:06,  1.16s/it]

 77%|███████▋  | 3626/4716 [1:10:05<21:04,  1.16s/it]

 77%|███████▋  | 3627/4716 [1:10:06<21:04,  1.16s/it]

 77%|███████▋  | 3628/4716 [1:10:07<21:03,  1.16s/it]

 77%|███████▋  | 3629/4716 [1:10:08<21:04,  1.16s/it]

 77%|███████▋  | 3630/4716 [1:10:09<21:02,  1.16s/it]

 77%|███████▋  | 3631/4716 [1:10:11<21:03,  1.16s/it]

 77%|███████▋  | 3632/4716 [1:10:12<21:02,  1.16s/it]

 77%|███████▋  | 3633/4716 [1:10:13<21:01,  1.16s/it]

 77%|███████▋  | 3634/4716 [1:10:14<21:01,  1.17s/it]

 77%|███████▋  | 3635/4716 [1:10:15<20:59,  1.16s/it]

 77%|███████▋  | 3636/4716 [1:10:16<20:57,  1.16s/it]

 77%|███████▋  | 3637/4716 [1:10:18<20:55,  1.16s/it]

 77%|███████▋  | 3638/4716 [1:10:19<20:53,  1.16s/it]

 77%|███████▋  | 3639/4716 [1:10:20<20:51,  1.16s/it]

 77%|███████▋  | 3640/4716 [1:10:21<20:50,  1.16s/it]

 77%|███████▋  | 3641/4716 [1:10:22<20:48,  1.16s/it]

 77%|███████▋  | 3642/4716 [1:10:23<20:49,  1.16s/it]

 77%|███████▋  | 3643/4716 [1:10:25<20:48,  1.16s/it]

 77%|███████▋  | 3644/4716 [1:10:26<20:47,  1.16s/it]

 77%|███████▋  | 3645/4716 [1:10:27<20:47,  1.16s/it]

 77%|███████▋  | 3646/4716 [1:10:28<20:45,  1.16s/it]

 77%|███████▋  | 3647/4716 [1:10:29<20:44,  1.16s/it]

 77%|███████▋  | 3648/4716 [1:10:30<20:43,  1.16s/it]

 77%|███████▋  | 3649/4716 [1:10:32<20:42,  1.16s/it]

 77%|███████▋  | 3650/4716 [1:10:33<20:40,  1.16s/it]

 77%|███████▋  | 3651/4716 [1:10:34<20:39,  1.16s/it]

 77%|███████▋  | 3652/4716 [1:10:35<20:36,  1.16s/it]

 77%|███████▋  | 3653/4716 [1:10:36<20:35,  1.16s/it]

 77%|███████▋  | 3654/4716 [1:10:37<20:34,  1.16s/it]

 78%|███████▊  | 3655/4716 [1:10:39<20:33,  1.16s/it]

 78%|███████▊  | 3656/4716 [1:10:40<20:32,  1.16s/it]

 78%|███████▊  | 3657/4716 [1:10:41<20:32,  1.16s/it]

 78%|███████▊  | 3658/4716 [1:10:42<20:30,  1.16s/it]

 78%|███████▊  | 3659/4716 [1:10:43<20:29,  1.16s/it]

 78%|███████▊  | 3660/4716 [1:10:44<20:27,  1.16s/it]

 78%|███████▊  | 3661/4716 [1:10:45<20:26,  1.16s/it]

 78%|███████▊  | 3662/4716 [1:10:47<20:25,  1.16s/it]

 78%|███████▊  | 3663/4716 [1:10:48<20:24,  1.16s/it]

 78%|███████▊  | 3664/4716 [1:10:49<20:23,  1.16s/it]

 78%|███████▊  | 3665/4716 [1:10:50<20:21,  1.16s/it]

 78%|███████▊  | 3666/4716 [1:10:51<20:22,  1.16s/it]

 78%|███████▊  | 3667/4716 [1:10:52<20:20,  1.16s/it]

 78%|███████▊  | 3668/4716 [1:10:54<20:19,  1.16s/it]

 78%|███████▊  | 3669/4716 [1:10:55<20:18,  1.16s/it]

 78%|███████▊  | 3670/4716 [1:10:56<20:16,  1.16s/it]

 78%|███████▊  | 3671/4716 [1:10:57<20:14,  1.16s/it]

 78%|███████▊  | 3672/4716 [1:10:58<20:11,  1.16s/it]

 78%|███████▊  | 3673/4716 [1:10:59<20:09,  1.16s/it]

 78%|███████▊  | 3674/4716 [1:11:01<20:08,  1.16s/it]

 78%|███████▊  | 3675/4716 [1:11:02<20:09,  1.16s/it]

 78%|███████▊  | 3676/4716 [1:11:03<20:07,  1.16s/it]

 78%|███████▊  | 3677/4716 [1:11:04<20:07,  1.16s/it]

 78%|███████▊  | 3678/4716 [1:11:05<20:04,  1.16s/it]

 78%|███████▊  | 3679/4716 [1:11:06<20:04,  1.16s/it]

 78%|███████▊  | 3680/4716 [1:11:08<20:03,  1.16s/it]

 78%|███████▊  | 3681/4716 [1:11:09<20:02,  1.16s/it]

 78%|███████▊  | 3682/4716 [1:11:10<20:01,  1.16s/it]

 78%|███████▊  | 3683/4716 [1:11:11<20:00,  1.16s/it]

 78%|███████▊  | 3684/4716 [1:11:12<19:58,  1.16s/it]

 78%|███████▊  | 3685/4716 [1:11:13<19:56,  1.16s/it]

 78%|███████▊  | 3686/4716 [1:11:15<19:56,  1.16s/it]

 78%|███████▊  | 3687/4716 [1:11:16<19:55,  1.16s/it]

 78%|███████▊  | 3688/4716 [1:11:17<19:54,  1.16s/it]

 78%|███████▊  | 3689/4716 [1:11:18<19:52,  1.16s/it]

 78%|███████▊  | 3690/4716 [1:11:19<19:51,  1.16s/it]

 78%|███████▊  | 3691/4716 [1:11:20<19:50,  1.16s/it]

 78%|███████▊  | 3692/4716 [1:11:21<19:49,  1.16s/it]

 78%|███████▊  | 3693/4716 [1:11:23<19:48,  1.16s/it]

 78%|███████▊  | 3694/4716 [1:11:24<19:46,  1.16s/it]

 78%|███████▊  | 3695/4716 [1:11:25<19:45,  1.16s/it]

 78%|███████▊  | 3696/4716 [1:11:26<19:43,  1.16s/it]

 78%|███████▊  | 3697/4716 [1:11:27<19:42,  1.16s/it]

 78%|███████▊  | 3698/4716 [1:11:28<19:41,  1.16s/it]

 78%|███████▊  | 3699/4716 [1:11:30<19:40,  1.16s/it]

 78%|███████▊  | 3700/4716 [1:11:31<19:39,  1.16s/it]

 78%|███████▊  | 3701/4716 [1:11:32<19:38,  1.16s/it]

 78%|███████▊  | 3702/4716 [1:11:33<19:37,  1.16s/it]

 79%|███████▊  | 3703/4716 [1:11:34<19:36,  1.16s/it]

 79%|███████▊  | 3704/4716 [1:11:35<19:35,  1.16s/it]

 79%|███████▊  | 3705/4716 [1:11:37<19:35,  1.16s/it]

 79%|███████▊  | 3706/4716 [1:11:38<19:33,  1.16s/it]

 79%|███████▊  | 3707/4716 [1:11:39<19:31,  1.16s/it]

 79%|███████▊  | 3708/4716 [1:11:40<19:29,  1.16s/it]

 79%|███████▊  | 3709/4716 [1:11:41<19:29,  1.16s/it]

 79%|███████▊  | 3710/4716 [1:11:42<19:29,  1.16s/it]

 79%|███████▊  | 3711/4716 [1:11:44<19:28,  1.16s/it]

 79%|███████▊  | 3712/4716 [1:11:45<19:27,  1.16s/it]

 79%|███████▊  | 3713/4716 [1:11:46<19:26,  1.16s/it]

 79%|███████▉  | 3714/4716 [1:11:47<19:25,  1.16s/it]

 79%|███████▉  | 3715/4716 [1:11:48<19:23,  1.16s/it]

 79%|███████▉  | 3716/4716 [1:11:49<19:23,  1.16s/it]

 79%|███████▉  | 3717/4716 [1:11:51<19:22,  1.16s/it]

 79%|███████▉  | 3718/4716 [1:11:52<19:21,  1.16s/it]

 79%|███████▉  | 3719/4716 [1:11:53<19:18,  1.16s/it]

 79%|███████▉  | 3720/4716 [1:11:54<19:17,  1.16s/it]

 79%|███████▉  | 3721/4716 [1:11:55<19:15,  1.16s/it]

 79%|███████▉  | 3722/4716 [1:11:56<19:15,  1.16s/it]

 79%|███████▉  | 3723/4716 [1:11:58<19:14,  1.16s/it]

 79%|███████▉  | 3724/4716 [1:11:59<19:13,  1.16s/it]

 79%|███████▉  | 3725/4716 [1:12:00<19:12,  1.16s/it]

 79%|███████▉  | 3726/4716 [1:12:01<19:13,  1.17s/it]

 79%|███████▉  | 3727/4716 [1:12:02<19:12,  1.16s/it]

 79%|███████▉  | 3728/4716 [1:12:03<19:09,  1.16s/it]

 79%|███████▉  | 3729/4716 [1:12:05<19:07,  1.16s/it]

 79%|███████▉  | 3730/4716 [1:12:06<19:06,  1.16s/it]

 79%|███████▉  | 3731/4716 [1:12:07<19:04,  1.16s/it]

 79%|███████▉  | 3732/4716 [1:12:08<19:03,  1.16s/it]

 79%|███████▉  | 3733/4716 [1:12:09<19:02,  1.16s/it]

 79%|███████▉  | 3734/4716 [1:12:10<19:01,  1.16s/it]

 79%|███████▉  | 3735/4716 [1:12:11<19:01,  1.16s/it]

 79%|███████▉  | 3736/4716 [1:12:13<19:00,  1.16s/it]

 79%|███████▉  | 3737/4716 [1:12:14<19:00,  1.16s/it]

 79%|███████▉  | 3738/4716 [1:12:15<18:58,  1.16s/it]

 79%|███████▉  | 3739/4716 [1:12:16<18:57,  1.16s/it]

 79%|███████▉  | 3740/4716 [1:12:17<18:56,  1.16s/it]

 79%|███████▉  | 3741/4716 [1:12:18<18:54,  1.16s/it]

 79%|███████▉  | 3742/4716 [1:12:20<18:52,  1.16s/it]

 79%|███████▉  | 3743/4716 [1:12:21<18:51,  1.16s/it]

 79%|███████▉  | 3744/4716 [1:12:22<18:49,  1.16s/it]

 79%|███████▉  | 3745/4716 [1:12:23<18:49,  1.16s/it]

 79%|███████▉  | 3746/4716 [1:12:24<18:48,  1.16s/it]

 79%|███████▉  | 3747/4716 [1:12:25<18:47,  1.16s/it]

 79%|███████▉  | 3748/4716 [1:12:27<18:46,  1.16s/it]

 79%|███████▉  | 3749/4716 [1:12:28<18:44,  1.16s/it]

 80%|███████▉  | 3750/4716 [1:12:29<18:44,  1.16s/it]

 80%|███████▉  | 3751/4716 [1:12:30<18:42,  1.16s/it]

 80%|███████▉  | 3752/4716 [1:12:31<18:40,  1.16s/it]

 80%|███████▉  | 3753/4716 [1:12:32<18:39,  1.16s/it]

 80%|███████▉  | 3754/4716 [1:12:34<18:37,  1.16s/it]

 80%|███████▉  | 3755/4716 [1:12:35<18:36,  1.16s/it]

logging
logging the anndata

 80%|███████▉  | 3756/4716 [1:12:36<19:20,  1.21s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 80%|███████▉  | 3757/4716 [1:12:37<19:04,  1.19s/it]

 80%|███████▉  | 3758/4716 [1:12:38<18:52,  1.18s/it]

 80%|███████▉  | 3759/4716 [1:12:40<18:44,  1.17s/it]

 80%|███████▉  | 3760/4716 [1:12:41<18:37,  1.17s/it]

 80%|███████▉  | 3761/4716 [1:12:42<18:32,  1.16s/it]

 80%|███████▉  | 3762/4716 [1:12:43<18:28,  1.16s/it]

 80%|███████▉  | 3763/4716 [1:12:44<18:25,  1.16s/it]

 80%|███████▉  | 3764/4716 [1:12:45<18:23,  1.16s/it]

 80%|███████▉  | 3765/4716 [1:12:46<18:21,  1.16s/it]

 80%|███████▉  | 3766/4716 [1:12:48<18:19,  1.16s/it]

 80%|███████▉  | 3767/4716 [1:12:49<18:18,  1.16s/it]

 80%|███████▉  | 3768/4716 [1:12:50<18:18,  1.16s/it]

 80%|███████▉  | 3769/4716 [1:12:51<18:16,  1.16s/it]

 80%|███████▉  | 3770/4716 [1:12:52<18:16,  1.16s/it]

 80%|███████▉  | 3771/4716 [1:12:53<18:13,  1.16s/it]

 80%|███████▉  | 3772/4716 [1:12:55<18:11,  1.16s/it]

 80%|████████  | 3773/4716 [1:12:56<18:10,  1.16s/it]

 80%|████████  | 3774/4716 [1:12:57<18:08,  1.16s/it]

 80%|████████  | 3775/4716 [1:12:58<18:07,  1.16s/it]

 80%|████████  | 3776/4716 [1:12:59<18:06,  1.16s/it]

 80%|████████  | 3777/4716 [1:13:00<18:05,  1.16s/it]

 80%|████████  | 3778/4716 [1:13:01<18:04,  1.16s/it]

 80%|████████  | 3779/4716 [1:13:03<18:02,  1.16s/it]

 80%|████████  | 3780/4716 [1:13:04<18:02,  1.16s/it]

 80%|████████  | 3781/4716 [1:13:05<18:01,  1.16s/it]

 80%|████████  | 3782/4716 [1:13:06<17:59,  1.16s/it]

 80%|████████  | 3783/4716 [1:13:07<18:00,  1.16s/it]

 80%|████████  | 3784/4716 [1:13:08<17:59,  1.16s/it]

 80%|████████  | 3785/4716 [1:13:10<18:00,  1.16s/it]

 80%|████████  | 3786/4716 [1:13:11<17:58,  1.16s/it]

 80%|████████  | 3787/4716 [1:13:12<17:55,  1.16s/it]

 80%|████████  | 3788/4716 [1:13:13<17:53,  1.16s/it]

 80%|████████  | 3789/4716 [1:13:14<17:52,  1.16s/it]

 80%|████████  | 3790/4716 [1:13:15<17:50,  1.16s/it]

 80%|████████  | 3791/4716 [1:13:17<17:49,  1.16s/it]

 80%|████████  | 3792/4716 [1:13:18<17:48,  1.16s/it]

 80%|████████  | 3793/4716 [1:13:19<17:46,  1.16s/it]

 80%|████████  | 3794/4716 [1:13:20<17:46,  1.16s/it]

 80%|████████  | 3795/4716 [1:13:21<17:43,  1.15s/it]

 80%|████████  | 3796/4716 [1:13:22<17:42,  1.16s/it]

 81%|████████  | 3797/4716 [1:13:23<17:41,  1.15s/it]

 81%|████████  | 3798/4716 [1:13:25<17:41,  1.16s/it]

 81%|████████  | 3799/4716 [1:13:26<17:40,  1.16s/it]

 81%|████████  | 3800/4716 [1:13:27<17:40,  1.16s/it]

 81%|████████  | 3801/4716 [1:13:28<17:38,  1.16s/it]

 81%|████████  | 3802/4716 [1:13:29<17:37,  1.16s/it]

 81%|████████  | 3803/4716 [1:13:30<17:35,  1.16s/it]

 81%|████████  | 3804/4716 [1:13:32<17:33,  1.16s/it]

 81%|████████  | 3805/4716 [1:13:33<17:33,  1.16s/it]

 81%|████████  | 3806/4716 [1:13:34<17:32,  1.16s/it]

 81%|████████  | 3807/4716 [1:13:35<17:31,  1.16s/it]

 81%|████████  | 3808/4716 [1:13:36<17:30,  1.16s/it]

 81%|████████  | 3809/4716 [1:13:37<17:29,  1.16s/it]

 81%|████████  | 3810/4716 [1:13:39<17:27,  1.16s/it]

 81%|████████  | 3811/4716 [1:13:40<17:26,  1.16s/it]

 81%|████████  | 3812/4716 [1:13:41<17:25,  1.16s/it]

 81%|████████  | 3813/4716 [1:13:42<17:23,  1.16s/it]

 81%|████████  | 3814/4716 [1:13:43<17:22,  1.16s/it]

 81%|████████  | 3815/4716 [1:13:44<17:21,  1.16s/it]

 81%|████████  | 3816/4716 [1:13:45<17:21,  1.16s/it]

 81%|████████  | 3817/4716 [1:13:47<17:20,  1.16s/it]

 81%|████████  | 3818/4716 [1:13:48<17:20,  1.16s/it]

 81%|████████  | 3819/4716 [1:13:49<17:19,  1.16s/it]

 81%|████████  | 3820/4716 [1:13:50<17:18,  1.16s/it]

 81%|████████  | 3821/4716 [1:13:51<17:16,  1.16s/it]

 81%|████████  | 3822/4716 [1:13:52<17:15,  1.16s/it]

 81%|████████  | 3823/4716 [1:13:54<17:13,  1.16s/it]

 81%|████████  | 3824/4716 [1:13:55<17:11,  1.16s/it]

 81%|████████  | 3825/4716 [1:13:56<17:10,  1.16s/it]

 81%|████████  | 3826/4716 [1:13:57<17:10,  1.16s/it]

 81%|████████  | 3827/4716 [1:13:58<17:10,  1.16s/it]

 81%|████████  | 3828/4716 [1:13:59<17:08,  1.16s/it]

 81%|████████  | 3829/4716 [1:14:01<17:10,  1.16s/it]

 81%|████████  | 3830/4716 [1:14:02<17:07,  1.16s/it]

 81%|████████  | 3831/4716 [1:14:03<17:06,  1.16s/it]

 81%|████████▏ | 3832/4716 [1:14:04<17:03,  1.16s/it]

 81%|████████▏ | 3833/4716 [1:14:05<17:01,  1.16s/it]

 81%|████████▏ | 3834/4716 [1:14:06<17:00,  1.16s/it]

 81%|████████▏ | 3835/4716 [1:14:07<16:59,  1.16s/it]

 81%|████████▏ | 3836/4716 [1:14:09<16:57,  1.16s/it]

 81%|████████▏ | 3837/4716 [1:14:10<16:57,  1.16s/it]

 81%|████████▏ | 3838/4716 [1:14:11<16:56,  1.16s/it]

 81%|████████▏ | 3839/4716 [1:14:12<16:55,  1.16s/it]

 81%|████████▏ | 3840/4716 [1:14:13<16:54,  1.16s/it]

 81%|████████▏ | 3841/4716 [1:14:14<16:53,  1.16s/it]

 81%|████████▏ | 3842/4716 [1:14:16<16:52,  1.16s/it]

 81%|████████▏ | 3843/4716 [1:14:17<16:52,  1.16s/it]

 82%|████████▏ | 3844/4716 [1:14:18<16:50,  1.16s/it]

 82%|████████▏ | 3845/4716 [1:14:19<16:48,  1.16s/it]

 82%|████████▏ | 3846/4716 [1:14:20<16:47,  1.16s/it]

 82%|████████▏ | 3847/4716 [1:14:21<16:44,  1.16s/it]

 82%|████████▏ | 3848/4716 [1:14:23<16:43,  1.16s/it]

 82%|████████▏ | 3849/4716 [1:14:24<16:42,  1.16s/it]

 82%|████████▏ | 3850/4716 [1:14:25<16:41,  1.16s/it]

 82%|████████▏ | 3851/4716 [1:14:26<16:40,  1.16s/it]

 82%|████████▏ | 3852/4716 [1:14:27<16:38,  1.16s/it]

 82%|████████▏ | 3853/4716 [1:14:28<16:37,  1.16s/it]

 82%|████████▏ | 3854/4716 [1:14:29<16:36,  1.16s/it]

 82%|████████▏ | 3855/4716 [1:14:31<16:35,  1.16s/it]

 82%|████████▏ | 3856/4716 [1:14:32<16:34,  1.16s/it]

 82%|████████▏ | 3857/4716 [1:14:33<16:34,  1.16s/it]

 82%|████████▏ | 3858/4716 [1:14:34<16:32,  1.16s/it]

 82%|████████▏ | 3859/4716 [1:14:35<16:31,  1.16s/it]

 82%|████████▏ | 3860/4716 [1:14:36<16:30,  1.16s/it]

 82%|████████▏ | 3861/4716 [1:14:38<16:30,  1.16s/it]

 82%|████████▏ | 3862/4716 [1:14:39<16:28,  1.16s/it]

 82%|████████▏ | 3863/4716 [1:14:40<16:26,  1.16s/it]

 82%|████████▏ | 3864/4716 [1:14:41<16:26,  1.16s/it]

 82%|████████▏ | 3865/4716 [1:14:42<16:25,  1.16s/it]

 82%|████████▏ | 3866/4716 [1:14:43<16:23,  1.16s/it]

 82%|████████▏ | 3867/4716 [1:14:44<16:22,  1.16s/it]

 82%|████████▏ | 3868/4716 [1:14:46<16:21,  1.16s/it]

 82%|████████▏ | 3869/4716 [1:14:47<16:20,  1.16s/it]

 82%|████████▏ | 3870/4716 [1:14:48<16:19,  1.16s/it]

 82%|████████▏ | 3871/4716 [1:14:49<16:17,  1.16s/it]

 82%|████████▏ | 3872/4716 [1:14:50<16:15,  1.16s/it]

 82%|████████▏ | 3873/4716 [1:14:51<16:13,  1.16s/it]

 82%|████████▏ | 3874/4716 [1:14:53<16:13,  1.16s/it]

 82%|████████▏ | 3875/4716 [1:14:54<16:12,  1.16s/it]

 82%|████████▏ | 3876/4716 [1:14:55<16:11,  1.16s/it]

 82%|████████▏ | 3877/4716 [1:14:56<16:10,  1.16s/it]

 82%|████████▏ | 3878/4716 [1:14:57<16:09,  1.16s/it]

 82%|████████▏ | 3879/4716 [1:14:58<16:08,  1.16s/it]

 82%|████████▏ | 3880/4716 [1:15:00<16:07,  1.16s/it]

 82%|████████▏ | 3881/4716 [1:15:01<16:06,  1.16s/it]

 82%|████████▏ | 3882/4716 [1:15:02<16:05,  1.16s/it]

 82%|████████▏ | 3883/4716 [1:15:03<16:03,  1.16s/it]

 82%|████████▏ | 3884/4716 [1:15:04<16:02,  1.16s/it]

 82%|████████▏ | 3885/4716 [1:15:05<16:01,  1.16s/it]

 82%|████████▏ | 3886/4716 [1:15:06<16:00,  1.16s/it]

 82%|████████▏ | 3887/4716 [1:15:08<15:59,  1.16s/it]

 82%|████████▏ | 3888/4716 [1:15:09<15:58,  1.16s/it]

 82%|████████▏ | 3889/4716 [1:15:10<15:57,  1.16s/it]

 82%|████████▏ | 3890/4716 [1:15:11<15:55,  1.16s/it]

 83%|████████▎ | 3891/4716 [1:15:12<15:53,  1.16s/it]

 83%|████████▎ | 3892/4716 [1:15:13<15:53,  1.16s/it]

 83%|████████▎ | 3893/4716 [1:15:15<15:52,  1.16s/it]

 83%|████████▎ | 3894/4716 [1:15:16<15:52,  1.16s/it]

 83%|████████▎ | 3895/4716 [1:15:17<15:50,  1.16s/it]

 83%|████████▎ | 3896/4716 [1:15:18<15:49,  1.16s/it]

 83%|████████▎ | 3897/4716 [1:15:19<15:49,  1.16s/it]

 83%|████████▎ | 3898/4716 [1:15:20<15:49,  1.16s/it]

 83%|████████▎ | 3899/4716 [1:15:22<15:48,  1.16s/it]

 83%|████████▎ | 3900/4716 [1:15:23<15:46,  1.16s/it]

 83%|████████▎ | 3901/4716 [1:15:24<15:45,  1.16s/it]

 83%|████████▎ | 3902/4716 [1:15:25<15:44,  1.16s/it]

 83%|████████▎ | 3903/4716 [1:15:26<15:44,  1.16s/it]

 83%|████████▎ | 3904/4716 [1:15:27<15:41,  1.16s/it]

 83%|████████▎ | 3905/4716 [1:15:28<15:40,  1.16s/it]

 83%|████████▎ | 3906/4716 [1:15:30<15:38,  1.16s/it]

 83%|████████▎ | 3907/4716 [1:15:31<15:36,  1.16s/it]

 83%|████████▎ | 3908/4716 [1:15:32<15:35,  1.16s/it]

 83%|████████▎ | 3909/4716 [1:15:33<15:35,  1.16s/it]

 83%|████████▎ | 3910/4716 [1:15:34<15:34,  1.16s/it]

 83%|████████▎ | 3911/4716 [1:15:35<15:33,  1.16s/it]

 83%|████████▎ | 3912/4716 [1:15:37<15:31,  1.16s/it]

 83%|████████▎ | 3913/4716 [1:15:38<15:29,  1.16s/it]

 83%|████████▎ | 3914/4716 [1:15:39<15:28,  1.16s/it]

 83%|████████▎ | 3915/4716 [1:15:40<15:26,  1.16s/it]

 83%|████████▎ | 3916/4716 [1:15:41<15:25,  1.16s/it]

 83%|████████▎ | 3917/4716 [1:15:42<15:24,  1.16s/it]

 83%|████████▎ | 3918/4716 [1:15:44<15:23,  1.16s/it]

 83%|████████▎ | 3919/4716 [1:15:45<15:22,  1.16s/it]

 83%|████████▎ | 3920/4716 [1:15:46<15:20,  1.16s/it]

 83%|████████▎ | 3921/4716 [1:15:47<15:20,  1.16s/it]

 83%|████████▎ | 3922/4716 [1:15:48<15:19,  1.16s/it]

 83%|████████▎ | 3923/4716 [1:15:49<15:18,  1.16s/it]

 83%|████████▎ | 3924/4716 [1:15:50<15:16,  1.16s/it]

 83%|████████▎ | 3925/4716 [1:15:52<15:15,  1.16s/it]

 83%|████████▎ | 3926/4716 [1:15:53<15:14,  1.16s/it]

 83%|████████▎ | 3927/4716 [1:15:54<15:13,  1.16s/it]

 83%|████████▎ | 3928/4716 [1:15:55<15:12,  1.16s/it]

 83%|████████▎ | 3929/4716 [1:15:56<15:11,  1.16s/it]

 83%|████████▎ | 3930/4716 [1:15:57<15:10,  1.16s/it]

 83%|████████▎ | 3931/4716 [1:15:59<15:09,  1.16s/it]

 83%|████████▎ | 3932/4716 [1:16:00<15:08,  1.16s/it]

 83%|████████▎ | 3933/4716 [1:16:01<15:07,  1.16s/it]

 83%|████████▎ | 3934/4716 [1:16:02<15:05,  1.16s/it]

 83%|████████▎ | 3935/4716 [1:16:03<15:03,  1.16s/it]

 83%|████████▎ | 3936/4716 [1:16:04<15:02,  1.16s/it]

 83%|████████▎ | 3937/4716 [1:16:06<15:01,  1.16s/it]

 84%|████████▎ | 3938/4716 [1:16:07<15:00,  1.16s/it]

 84%|████████▎ | 3939/4716 [1:16:08<15:00,  1.16s/it]

 84%|████████▎ | 3940/4716 [1:16:09<14:59,  1.16s/it]

 84%|████████▎ | 3941/4716 [1:16:10<14:59,  1.16s/it]

 84%|████████▎ | 3942/4716 [1:16:11<14:56,  1.16s/it]

 84%|████████▎ | 3943/4716 [1:16:12<14:55,  1.16s/it]

 84%|████████▎ | 3944/4716 [1:16:14<14:54,  1.16s/it]

 84%|████████▎ | 3945/4716 [1:16:15<14:52,  1.16s/it]

 84%|████████▎ | 3946/4716 [1:16:16<14:50,  1.16s/it]

 84%|████████▎ | 3947/4716 [1:16:17<14:49,  1.16s/it]

 84%|████████▎ | 3948/4716 [1:16:18<14:49,  1.16s/it]

 84%|████████▎ | 3949/4716 [1:16:19<14:48,  1.16s/it]

 84%|████████▍ | 3950/4716 [1:16:21<14:47,  1.16s/it]

 84%|████████▍ | 3951/4716 [1:16:22<14:46,  1.16s/it]

 84%|████████▍ | 3952/4716 [1:16:23<14:45,  1.16s/it]

 84%|████████▍ | 3953/4716 [1:16:24<14:44,  1.16s/it]

 84%|████████▍ | 3954/4716 [1:16:25<14:42,  1.16s/it]

 84%|████████▍ | 3955/4716 [1:16:26<14:41,  1.16s/it]

 84%|████████▍ | 3956/4716 [1:16:28<14:40,  1.16s/it]

 84%|████████▍ | 3957/4716 [1:16:29<14:40,  1.16s/it]

 84%|████████▍ | 3958/4716 [1:16:30<14:39,  1.16s/it]

 84%|████████▍ | 3959/4716 [1:16:31<14:37,  1.16s/it]

 84%|████████▍ | 3960/4716 [1:16:32<14:36,  1.16s/it]

 84%|████████▍ | 3961/4716 [1:16:33<14:35,  1.16s/it]

 84%|████████▍ | 3962/4716 [1:16:35<14:33,  1.16s/it]

 84%|████████▍ | 3963/4716 [1:16:36<14:32,  1.16s/it]

 84%|████████▍ | 3964/4716 [1:16:37<14:31,  1.16s/it]

 84%|████████▍ | 3965/4716 [1:16:38<14:30,  1.16s/it]

 84%|████████▍ | 3966/4716 [1:16:39<14:29,  1.16s/it]

 84%|████████▍ | 3967/4716 [1:16:40<14:27,  1.16s/it]

 84%|████████▍ | 3968/4716 [1:16:41<14:25,  1.16s/it]

 84%|████████▍ | 3969/4716 [1:16:43<14:24,  1.16s/it]

 84%|████████▍ | 3970/4716 [1:16:44<14:23,  1.16s/it]

 84%|████████▍ | 3971/4716 [1:16:45<14:22,  1.16s/it]

 84%|████████▍ | 3972/4716 [1:16:46<14:21,  1.16s/it]

 84%|████████▍ | 3973/4716 [1:16:47<14:19,  1.16s/it]

 84%|████████▍ | 3974/4716 [1:16:48<14:19,  1.16s/it]

 84%|████████▍ | 3975/4716 [1:16:50<14:18,  1.16s/it]

 84%|████████▍ | 3976/4716 [1:16:51<14:17,  1.16s/it]

 84%|████████▍ | 3977/4716 [1:16:52<14:15,  1.16s/it]

 84%|████████▍ | 3978/4716 [1:16:53<14:14,  1.16s/it]

 84%|████████▍ | 3979/4716 [1:16:54<14:13,  1.16s/it]

 84%|████████▍ | 3980/4716 [1:16:55<14:12,  1.16s/it]

 84%|████████▍ | 3981/4716 [1:16:57<14:11,  1.16s/it]

 84%|████████▍ | 3982/4716 [1:16:58<14:11,  1.16s/it]

 84%|████████▍ | 3983/4716 [1:16:59<14:09,  1.16s/it]

 84%|████████▍ | 3984/4716 [1:17:00<14:08,  1.16s/it]

 84%|████████▍ | 3985/4716 [1:17:01<14:06,  1.16s/it]

 85%|████████▍ | 3986/4716 [1:17:02<14:05,  1.16s/it]

 85%|████████▍ | 3987/4716 [1:17:03<14:03,  1.16s/it]

 85%|████████▍ | 3988/4716 [1:17:05<14:03,  1.16s/it]

 85%|████████▍ | 3989/4716 [1:17:06<14:02,  1.16s/it]

 85%|████████▍ | 3990/4716 [1:17:07<14:00,  1.16s/it]

 85%|████████▍ | 3991/4716 [1:17:08<13:59,  1.16s/it]

 85%|████████▍ | 3992/4716 [1:17:09<13:58,  1.16s/it]

 85%|████████▍ | 3993/4716 [1:17:10<13:58,  1.16s/it]

 85%|████████▍ | 3994/4716 [1:17:12<13:56,  1.16s/it]

 85%|████████▍ | 3995/4716 [1:17:13<13:55,  1.16s/it]

 85%|████████▍ | 3996/4716 [1:17:14<13:54,  1.16s/it]

 85%|████████▍ | 3997/4716 [1:17:15<13:53,  1.16s/it]

 85%|████████▍ | 3998/4716 [1:17:16<13:51,  1.16s/it]

 85%|████████▍ | 3999/4716 [1:17:17<13:51,  1.16s/it]

 85%|████████▍ | 4000/4716 [1:17:19<13:50,  1.16s/it]

 85%|████████▍ | 4001/4716 [1:17:20<13:48,  1.16s/it]

 85%|████████▍ | 4002/4716 [1:17:21<13:48,  1.16s/it]

 85%|████████▍ | 4003/4716 [1:17:22<13:47,  1.16s/it]

 85%|████████▍ | 4004/4716 [1:17:23<13:46,  1.16s/it]

 85%|████████▍ | 4005/4716 [1:17:24<13:44,  1.16s/it]

 85%|████████▍ | 4006/4716 [1:17:25<13:43,  1.16s/it]

 85%|████████▍ | 4007/4716 [1:17:27<13:41,  1.16s/it]

 85%|████████▍ | 4008/4716 [1:17:28<13:40,  1.16s/it]

 85%|████████▌ | 4009/4716 [1:17:29<13:39,  1.16s/it]

 85%|████████▌ | 4010/4716 [1:17:30<13:37,  1.16s/it]

 85%|████████▌ | 4011/4716 [1:17:31<13:36,  1.16s/it]

 85%|████████▌ | 4012/4716 [1:17:32<13:35,  1.16s/it]

 85%|████████▌ | 4013/4716 [1:17:34<13:35,  1.16s/it]

 85%|████████▌ | 4014/4716 [1:17:35<13:34,  1.16s/it]

 85%|████████▌ | 4015/4716 [1:17:36<13:33,  1.16s/it]

 85%|████████▌ | 4016/4716 [1:17:37<13:32,  1.16s/it]

 85%|████████▌ | 4017/4716 [1:17:38<13:31,  1.16s/it]

 85%|████████▌ | 4018/4716 [1:17:39<13:29,  1.16s/it]

 85%|████████▌ | 4019/4716 [1:17:41<13:28,  1.16s/it]

 85%|████████▌ | 4020/4716 [1:17:42<13:26,  1.16s/it]

 85%|████████▌ | 4021/4716 [1:17:43<13:25,  1.16s/it]

 85%|████████▌ | 4022/4716 [1:17:44<13:24,  1.16s/it]

 85%|████████▌ | 4023/4716 [1:17:45<13:22,  1.16s/it]

 85%|████████▌ | 4024/4716 [1:17:46<13:20,  1.16s/it]

 85%|████████▌ | 4025/4716 [1:17:48<13:19,  1.16s/it]

 85%|████████▌ | 4026/4716 [1:17:49<13:19,  1.16s/it]

 85%|████████▌ | 4027/4716 [1:17:50<13:18,  1.16s/it]

 85%|████████▌ | 4028/4716 [1:17:51<13:17,  1.16s/it]

 85%|████████▌ | 4029/4716 [1:17:52<13:16,  1.16s/it]

 85%|████████▌ | 4030/4716 [1:17:53<13:15,  1.16s/it]

 85%|████████▌ | 4031/4716 [1:17:54<13:14,  1.16s/it]

 85%|████████▌ | 4032/4716 [1:17:56<13:12,  1.16s/it]

 86%|████████▌ | 4033/4716 [1:17:57<13:10,  1.16s/it]

 86%|████████▌ | 4034/4716 [1:17:58<13:09,  1.16s/it]

 86%|████████▌ | 4035/4716 [1:17:59<13:08,  1.16s/it]

 86%|████████▌ | 4036/4716 [1:18:00<13:07,  1.16s/it]

 86%|████████▌ | 4037/4716 [1:18:01<13:07,  1.16s/it]

 86%|████████▌ | 4038/4716 [1:18:03<13:05,  1.16s/it]

 86%|████████▌ | 4039/4716 [1:18:04<13:04,  1.16s/it]

 86%|████████▌ | 4040/4716 [1:18:05<13:03,  1.16s/it]

 86%|████████▌ | 4041/4716 [1:18:06<13:01,  1.16s/it]

 86%|████████▌ | 4042/4716 [1:18:07<13:00,  1.16s/it]

 86%|████████▌ | 4043/4716 [1:18:08<12:59,  1.16s/it]

 86%|████████▌ | 4044/4716 [1:18:10<12:58,  1.16s/it]

 86%|████████▌ | 4045/4716 [1:18:11<12:57,  1.16s/it]

 86%|████████▌ | 4046/4716 [1:18:12<12:56,  1.16s/it]

 86%|████████▌ | 4047/4716 [1:18:13<12:56,  1.16s/it]

 86%|████████▌ | 4048/4716 [1:18:14<12:54,  1.16s/it]

 86%|████████▌ | 4049/4716 [1:18:15<12:53,  1.16s/it]

 86%|████████▌ | 4050/4716 [1:18:16<12:51,  1.16s/it]

 86%|████████▌ | 4051/4716 [1:18:18<12:51,  1.16s/it]

 86%|████████▌ | 4052/4716 [1:18:19<12:50,  1.16s/it]

 86%|████████▌ | 4053/4716 [1:18:20<12:48,  1.16s/it]

 86%|████████▌ | 4054/4716 [1:18:21<12:46,  1.16s/it]

 86%|████████▌ | 4055/4716 [1:18:22<12:45,  1.16s/it]

 86%|████████▌ | 4056/4716 [1:18:23<12:45,  1.16s/it]

 86%|████████▌ | 4057/4716 [1:18:25<12:43,  1.16s/it]

 86%|████████▌ | 4058/4716 [1:18:26<12:43,  1.16s/it]

 86%|████████▌ | 4059/4716 [1:18:27<12:41,  1.16s/it]

 86%|████████▌ | 4060/4716 [1:18:28<12:40,  1.16s/it]

 86%|████████▌ | 4061/4716 [1:18:29<12:39,  1.16s/it]

 86%|████████▌ | 4062/4716 [1:18:30<12:37,  1.16s/it]

 86%|████████▌ | 4063/4716 [1:18:32<12:36,  1.16s/it]

 86%|████████▌ | 4064/4716 [1:18:33<12:34,  1.16s/it]

 86%|████████▌ | 4065/4716 [1:18:34<12:33,  1.16s/it]

 86%|████████▌ | 4066/4716 [1:18:35<12:33,  1.16s/it]

 86%|████████▌ | 4067/4716 [1:18:36<12:32,  1.16s/it]

 86%|████████▋ | 4068/4716 [1:18:37<12:31,  1.16s/it]

 86%|████████▋ | 4069/4716 [1:18:38<12:29,  1.16s/it]

 86%|████████▋ | 4070/4716 [1:18:40<12:28,  1.16s/it]

 86%|████████▋ | 4071/4716 [1:18:41<12:27,  1.16s/it]

 86%|████████▋ | 4072/4716 [1:18:42<12:27,  1.16s/it]

 86%|████████▋ | 4073/4716 [1:18:43<12:26,  1.16s/it]

 86%|████████▋ | 4074/4716 [1:18:44<12:24,  1.16s/it]

 86%|████████▋ | 4075/4716 [1:18:45<12:24,  1.16s/it]

 86%|████████▋ | 4076/4716 [1:18:47<12:23,  1.16s/it]

 86%|████████▋ | 4077/4716 [1:18:48<12:22,  1.16s/it]

 86%|████████▋ | 4078/4716 [1:18:49<12:21,  1.16s/it]

 86%|████████▋ | 4079/4716 [1:18:50<12:19,  1.16s/it]

 87%|████████▋ | 4080/4716 [1:18:51<12:17,  1.16s/it]

 87%|████████▋ | 4081/4716 [1:18:52<12:16,  1.16s/it]

 87%|████████▋ | 4082/4716 [1:18:54<12:14,  1.16s/it]

 87%|████████▋ | 4083/4716 [1:18:55<12:12,  1.16s/it]

 87%|████████▋ | 4084/4716 [1:18:56<12:11,  1.16s/it]

 87%|████████▋ | 4085/4716 [1:18:57<12:10,  1.16s/it]

 87%|████████▋ | 4086/4716 [1:18:58<12:09,  1.16s/it]

 87%|████████▋ | 4087/4716 [1:18:59<12:08,  1.16s/it]

 87%|████████▋ | 4088/4716 [1:19:01<12:06,  1.16s/it]

 87%|████████▋ | 4089/4716 [1:19:02<12:05,  1.16s/it]

 87%|████████▋ | 4090/4716 [1:19:03<12:05,  1.16s/it]

 87%|████████▋ | 4091/4716 [1:19:04<12:03,  1.16s/it]

 87%|████████▋ | 4092/4716 [1:19:05<12:02,  1.16s/it]

 87%|████████▋ | 4093/4716 [1:19:06<12:01,  1.16s/it]

 87%|████████▋ | 4094/4716 [1:19:07<11:59,  1.16s/it]

 87%|████████▋ | 4095/4716 [1:19:09<11:59,  1.16s/it]

 87%|████████▋ | 4096/4716 [1:19:10<11:59,  1.16s/it]

 87%|████████▋ | 4097/4716 [1:19:11<11:58,  1.16s/it]

 87%|████████▋ | 4098/4716 [1:19:12<11:56,  1.16s/it]

 87%|████████▋ | 4099/4716 [1:19:13<11:55,  1.16s/it]

 87%|████████▋ | 4100/4716 [1:19:14<11:54,  1.16s/it]

 87%|████████▋ | 4101/4716 [1:19:16<11:53,  1.16s/it]

 87%|████████▋ | 4102/4716 [1:19:17<11:51,  1.16s/it]

 87%|████████▋ | 4103/4716 [1:19:18<11:50,  1.16s/it]

 87%|████████▋ | 4104/4716 [1:19:19<11:49,  1.16s/it]

 87%|████████▋ | 4105/4716 [1:19:20<11:48,  1.16s/it]

 87%|████████▋ | 4106/4716 [1:19:21<11:46,  1.16s/it]

 87%|████████▋ | 4107/4716 [1:19:23<11:45,  1.16s/it]

 87%|████████▋ | 4108/4716 [1:19:24<11:44,  1.16s/it]

 87%|████████▋ | 4109/4716 [1:19:25<11:42,  1.16s/it]

 87%|████████▋ | 4110/4716 [1:19:26<11:41,  1.16s/it]

 87%|████████▋ | 4111/4716 [1:19:27<11:39,  1.16s/it]

 87%|████████▋ | 4112/4716 [1:19:28<11:39,  1.16s/it]

 87%|████████▋ | 4113/4716 [1:19:29<11:38,  1.16s/it]

 87%|████████▋ | 4114/4716 [1:19:31<11:37,  1.16s/it]

 87%|████████▋ | 4115/4716 [1:19:32<11:36,  1.16s/it]

 87%|████████▋ | 4116/4716 [1:19:33<11:35,  1.16s/it]

 87%|████████▋ | 4117/4716 [1:19:34<11:33,  1.16s/it]

 87%|████████▋ | 4118/4716 [1:19:35<11:32,  1.16s/it]

 87%|████████▋ | 4119/4716 [1:19:36<11:31,  1.16s/it]

 87%|████████▋ | 4120/4716 [1:19:38<11:30,  1.16s/it]

 87%|████████▋ | 4121/4716 [1:19:39<11:29,  1.16s/it]

 87%|████████▋ | 4122/4716 [1:19:40<11:27,  1.16s/it]

 87%|████████▋ | 4123/4716 [1:19:41<11:27,  1.16s/it]

 87%|████████▋ | 4124/4716 [1:19:42<11:25,  1.16s/it]

 87%|████████▋ | 4125/4716 [1:19:43<11:24,  1.16s/it]

 87%|████████▋ | 4126/4716 [1:19:45<11:23,  1.16s/it]

 88%|████████▊ | 4127/4716 [1:19:46<11:22,  1.16s/it]

 88%|████████▊ | 4128/4716 [1:19:47<11:21,  1.16s/it]

 88%|████████▊ | 4129/4716 [1:19:48<11:20,  1.16s/it]

 88%|████████▊ | 4130/4716 [1:19:49<11:18,  1.16s/it]

 88%|████████▊ | 4131/4716 [1:19:50<11:18,  1.16s/it]

 88%|████████▊ | 4132/4716 [1:19:52<11:17,  1.16s/it]

 88%|████████▊ | 4133/4716 [1:19:53<11:16,  1.16s/it]

 88%|████████▊ | 4134/4716 [1:19:54<11:15,  1.16s/it]

 88%|████████▊ | 4135/4716 [1:19:55<11:13,  1.16s/it]

 88%|████████▊ | 4136/4716 [1:19:56<11:12,  1.16s/it]

 88%|████████▊ | 4137/4716 [1:19:57<11:10,  1.16s/it]

 88%|████████▊ | 4138/4716 [1:19:58<11:09,  1.16s/it]

 88%|████████▊ | 4139/4716 [1:20:00<11:09,  1.16s/it]

 88%|████████▊ | 4140/4716 [1:20:01<11:07,  1.16s/it]

 88%|████████▊ | 4141/4716 [1:20:02<11:06,  1.16s/it]

 88%|████████▊ | 4142/4716 [1:20:03<11:05,  1.16s/it]

 88%|████████▊ | 4143/4716 [1:20:04<11:03,  1.16s/it]

 88%|████████▊ | 4144/4716 [1:20:05<11:02,  1.16s/it]

 88%|████████▊ | 4145/4716 [1:20:07<11:01,  1.16s/it]

 88%|████████▊ | 4146/4716 [1:20:08<11:00,  1.16s/it]

 88%|████████▊ | 4147/4716 [1:20:09<11:00,  1.16s/it]

 88%|████████▊ | 4148/4716 [1:20:10<10:59,  1.16s/it]

 88%|████████▊ | 4149/4716 [1:20:11<10:57,  1.16s/it]

 88%|████████▊ | 4150/4716 [1:20:12<10:57,  1.16s/it]

 88%|████████▊ | 4151/4716 [1:20:14<10:55,  1.16s/it]

 88%|████████▊ | 4152/4716 [1:20:15<10:54,  1.16s/it]

 88%|████████▊ | 4153/4716 [1:20:16<10:53,  1.16s/it]

 88%|████████▊ | 4154/4716 [1:20:17<10:52,  1.16s/it]

 88%|████████▊ | 4155/4716 [1:20:18<10:50,  1.16s/it]

 88%|████████▊ | 4156/4716 [1:20:19<10:49,  1.16s/it]

 88%|████████▊ | 4157/4716 [1:20:21<10:48,  1.16s/it]

 88%|████████▊ | 4158/4716 [1:20:22<10:47,  1.16s/it]

 88%|████████▊ | 4159/4716 [1:20:23<10:46,  1.16s/it]

 88%|████████▊ | 4160/4716 [1:20:24<10:45,  1.16s/it]

 88%|████████▊ | 4161/4716 [1:20:25<10:44,  1.16s/it]

 88%|████████▊ | 4162/4716 [1:20:26<10:42,  1.16s/it]

 88%|████████▊ | 4163/4716 [1:20:27<10:41,  1.16s/it]

 88%|████████▊ | 4164/4716 [1:20:29<10:40,  1.16s/it]

 88%|████████▊ | 4165/4716 [1:20:30<10:38,  1.16s/it]

 88%|████████▊ | 4166/4716 [1:20:31<10:37,  1.16s/it]

 88%|████████▊ | 4167/4716 [1:20:32<10:36,  1.16s/it]

 88%|████████▊ | 4168/4716 [1:20:33<10:34,  1.16s/it]

 88%|████████▊ | 4169/4716 [1:20:34<10:34,  1.16s/it]

 88%|████████▊ | 4170/4716 [1:20:36<10:33,  1.16s/it]

 88%|████████▊ | 4171/4716 [1:20:37<10:32,  1.16s/it]

 88%|████████▊ | 4172/4716 [1:20:38<10:31,  1.16s/it]

 88%|████████▊ | 4173/4716 [1:20:39<10:29,  1.16s/it]

 89%|████████▊ | 4174/4716 [1:20:40<10:29,  1.16s/it]

 89%|████████▊ | 4175/4716 [1:20:41<10:27,  1.16s/it]

 89%|████████▊ | 4176/4716 [1:20:43<10:26,  1.16s/it]

 89%|████████▊ | 4177/4716 [1:20:44<10:24,  1.16s/it]

 89%|████████▊ | 4178/4716 [1:20:45<10:23,  1.16s/it]

 89%|████████▊ | 4179/4716 [1:20:46<10:22,  1.16s/it]

 89%|████████▊ | 4180/4716 [1:20:47<10:22,  1.16s/it]

 89%|████████▊ | 4181/4716 [1:20:48<10:20,  1.16s/it]

 89%|████████▊ | 4182/4716 [1:20:50<10:19,  1.16s/it]

 89%|████████▊ | 4183/4716 [1:20:51<10:18,  1.16s/it]

 89%|████████▊ | 4184/4716 [1:20:52<10:18,  1.16s/it]

 89%|████████▊ | 4185/4716 [1:20:53<10:16,  1.16s/it]

 89%|████████▉ | 4186/4716 [1:20:54<10:14,  1.16s/it]

 89%|████████▉ | 4187/4716 [1:20:55<10:14,  1.16s/it]

 89%|████████▉ | 4188/4716 [1:20:56<10:13,  1.16s/it]

 89%|████████▉ | 4189/4716 [1:20:58<10:11,  1.16s/it]

 89%|████████▉ | 4190/4716 [1:20:59<10:10,  1.16s/it]

 89%|████████▉ | 4191/4716 [1:21:00<10:10,  1.16s/it]

 89%|████████▉ | 4192/4716 [1:21:01<10:09,  1.16s/it]

 89%|████████▉ | 4193/4716 [1:21:02<10:07,  1.16s/it]

 89%|████████▉ | 4194/4716 [1:21:03<10:06,  1.16s/it]

 89%|████████▉ | 4195/4716 [1:21:05<10:04,  1.16s/it]

 89%|████████▉ | 4196/4716 [1:21:06<10:04,  1.16s/it]

 89%|████████▉ | 4197/4716 [1:21:07<10:03,  1.16s/it]

 89%|████████▉ | 4198/4716 [1:21:08<10:01,  1.16s/it]

 89%|████████▉ | 4199/4716 [1:21:09<10:01,  1.16s/it]

 89%|████████▉ | 4200/4716 [1:21:10<10:00,  1.16s/it]

 89%|████████▉ | 4201/4716 [1:21:12<09:59,  1.16s/it]

 89%|████████▉ | 4202/4716 [1:21:13<09:57,  1.16s/it]

 89%|████████▉ | 4203/4716 [1:21:14<09:55,  1.16s/it]

 89%|████████▉ | 4204/4716 [1:21:15<09:54,  1.16s/it]

 89%|████████▉ | 4205/4716 [1:21:16<09:53,  1.16s/it]

 89%|████████▉ | 4206/4716 [1:21:17<09:52,  1.16s/it]

 89%|████████▉ | 4207/4716 [1:21:19<09:50,  1.16s/it]

 89%|████████▉ | 4208/4716 [1:21:20<09:48,  1.16s/it]

 89%|████████▉ | 4209/4716 [1:21:21<09:48,  1.16s/it]

 89%|████████▉ | 4210/4716 [1:21:22<09:47,  1.16s/it]

 89%|████████▉ | 4211/4716 [1:21:23<09:45,  1.16s/it]

 89%|████████▉ | 4212/4716 [1:21:24<09:44,  1.16s/it]

 89%|████████▉ | 4213/4716 [1:21:26<09:42,  1.16s/it]

 89%|████████▉ | 4214/4716 [1:21:27<09:41,  1.16s/it]

 89%|████████▉ | 4215/4716 [1:21:28<09:40,  1.16s/it]

 89%|████████▉ | 4216/4716 [1:21:29<09:39,  1.16s/it]

 89%|████████▉ | 4217/4716 [1:21:30<09:38,  1.16s/it]

 89%|████████▉ | 4218/4716 [1:21:31<09:37,  1.16s/it]

 89%|████████▉ | 4219/4716 [1:21:32<09:36,  1.16s/it]

 89%|████████▉ | 4220/4716 [1:21:34<09:35,  1.16s/it]

 90%|████████▉ | 4221/4716 [1:21:35<09:34,  1.16s/it]

 90%|████████▉ | 4222/4716 [1:21:36<09:33,  1.16s/it]

 90%|████████▉ | 4223/4716 [1:21:37<09:32,  1.16s/it]

 90%|████████▉ | 4224/4716 [1:21:38<09:31,  1.16s/it]

 90%|████████▉ | 4225/4716 [1:21:39<09:29,  1.16s/it]

 90%|████████▉ | 4226/4716 [1:21:41<09:28,  1.16s/it]

 90%|████████▉ | 4227/4716 [1:21:42<09:26,  1.16s/it]

 90%|████████▉ | 4228/4716 [1:21:43<09:26,  1.16s/it]

 90%|████████▉ | 4229/4716 [1:21:44<09:24,  1.16s/it]

 90%|████████▉ | 4230/4716 [1:21:45<09:23,  1.16s/it]

 90%|████████▉ | 4231/4716 [1:21:46<09:23,  1.16s/it]

 90%|████████▉ | 4232/4716 [1:21:48<09:21,  1.16s/it]

 90%|████████▉ | 4233/4716 [1:21:49<09:20,  1.16s/it]

 90%|████████▉ | 4234/4716 [1:21:50<09:19,  1.16s/it]

 90%|████████▉ | 4235/4716 [1:21:51<09:18,  1.16s/it]

 90%|████████▉ | 4236/4716 [1:21:52<09:17,  1.16s/it]

 90%|████████▉ | 4237/4716 [1:21:53<09:15,  1.16s/it]

 90%|████████▉ | 4238/4716 [1:21:55<09:15,  1.16s/it]

 90%|████████▉ | 4239/4716 [1:21:56<09:13,  1.16s/it]

 90%|████████▉ | 4240/4716 [1:21:57<09:12,  1.16s/it]

 90%|████████▉ | 4241/4716 [1:21:58<09:11,  1.16s/it]

 90%|████████▉ | 4242/4716 [1:21:59<09:10,  1.16s/it]

 90%|████████▉ | 4243/4716 [1:22:00<09:09,  1.16s/it]

 90%|████████▉ | 4244/4716 [1:22:01<09:07,  1.16s/it]

 90%|█████████ | 4245/4716 [1:22:03<09:07,  1.16s/it]

 90%|█████████ | 4246/4716 [1:22:04<09:06,  1.16s/it]

 90%|█████████ | 4247/4716 [1:22:05<09:05,  1.16s/it]

 90%|█████████ | 4248/4716 [1:22:06<09:04,  1.16s/it]

 90%|█████████ | 4249/4716 [1:22:07<09:02,  1.16s/it]

 90%|█████████ | 4250/4716 [1:22:08<09:00,  1.16s/it]

 90%|█████████ | 4251/4716 [1:22:10<09:00,  1.16s/it]

 90%|█████████ | 4252/4716 [1:22:11<08:59,  1.16s/it]

 90%|█████████ | 4253/4716 [1:22:12<08:58,  1.16s/it]

 90%|█████████ | 4254/4716 [1:22:13<08:56,  1.16s/it]

 90%|█████████ | 4255/4716 [1:22:14<08:55,  1.16s/it]

 90%|█████████ | 4256/4716 [1:22:15<08:54,  1.16s/it]

 90%|█████████ | 4257/4716 [1:22:17<08:53,  1.16s/it]

 90%|█████████ | 4258/4716 [1:22:18<08:52,  1.16s/it]

 90%|█████████ | 4259/4716 [1:22:19<08:51,  1.16s/it]

 90%|█████████ | 4260/4716 [1:22:20<08:50,  1.16s/it]

 90%|█████████ | 4261/4716 [1:22:21<08:49,  1.16s/it]

 90%|█████████ | 4262/4716 [1:22:22<08:47,  1.16s/it]

 90%|█████████ | 4263/4716 [1:22:24<08:46,  1.16s/it]

 90%|█████████ | 4264/4716 [1:22:25<08:45,  1.16s/it]

 90%|█████████ | 4265/4716 [1:22:26<08:44,  1.16s/it]

 90%|█████████ | 4266/4716 [1:22:27<08:43,  1.16s/it]

 90%|█████████ | 4267/4716 [1:22:28<08:41,  1.16s/it]

 91%|█████████ | 4268/4716 [1:22:29<08:40,  1.16s/it]

 91%|█████████ | 4269/4716 [1:22:31<08:39,  1.16s/it]

 91%|█████████ | 4270/4716 [1:22:32<08:37,  1.16s/it]

 91%|█████████ | 4271/4716 [1:22:33<08:36,  1.16s/it]

 91%|█████████ | 4272/4716 [1:22:34<08:35,  1.16s/it]

 91%|█████████ | 4273/4716 [1:22:35<08:34,  1.16s/it]

 91%|█████████ | 4274/4716 [1:22:36<08:33,  1.16s/it]

 91%|█████████ | 4275/4716 [1:22:38<08:32,  1.16s/it]

 91%|█████████ | 4276/4716 [1:22:39<08:31,  1.16s/it]

 91%|█████████ | 4277/4716 [1:22:40<08:31,  1.16s/it]

 91%|█████████ | 4278/4716 [1:22:41<08:29,  1.16s/it]

 91%|█████████ | 4279/4716 [1:22:42<08:27,  1.16s/it]

 91%|█████████ | 4280/4716 [1:22:43<08:26,  1.16s/it]

 91%|█████████ | 4281/4716 [1:22:44<08:25,  1.16s/it]

 91%|█████████ | 4282/4716 [1:22:46<08:24,  1.16s/it]

 91%|█████████ | 4283/4716 [1:22:47<08:22,  1.16s/it]

 91%|█████████ | 4284/4716 [1:22:48<08:21,  1.16s/it]

 91%|█████████ | 4285/4716 [1:22:49<08:20,  1.16s/it]

 91%|█████████ | 4286/4716 [1:22:50<08:19,  1.16s/it]

 91%|█████████ | 4287/4716 [1:22:51<08:18,  1.16s/it]

 91%|█████████ | 4288/4716 [1:22:53<08:16,  1.16s/it]

 91%|█████████ | 4289/4716 [1:22:54<08:15,  1.16s/it]

 91%|█████████ | 4290/4716 [1:22:55<08:14,  1.16s/it]

 91%|█████████ | 4291/4716 [1:22:56<08:13,  1.16s/it]

 91%|█████████ | 4292/4716 [1:22:57<08:12,  1.16s/it]

 91%|█████████ | 4293/4716 [1:22:58<08:11,  1.16s/it]

 91%|█████████ | 4294/4716 [1:23:00<08:09,  1.16s/it]

 91%|█████████ | 4295/4716 [1:23:01<08:08,  1.16s/it]

 91%|█████████ | 4296/4716 [1:23:02<08:07,  1.16s/it]

 91%|█████████ | 4297/4716 [1:23:03<08:06,  1.16s/it]

 91%|█████████ | 4298/4716 [1:23:04<08:05,  1.16s/it]

 91%|█████████ | 4299/4716 [1:23:05<08:04,  1.16s/it]

 91%|█████████ | 4300/4716 [1:23:07<08:02,  1.16s/it]

 91%|█████████ | 4301/4716 [1:23:08<08:01,  1.16s/it]

 91%|█████████ | 4302/4716 [1:23:09<08:00,  1.16s/it]

 91%|█████████ | 4303/4716 [1:23:10<07:59,  1.16s/it]

 91%|█████████▏| 4304/4716 [1:23:11<07:58,  1.16s/it]

 91%|█████████▏| 4305/4716 [1:23:12<07:57,  1.16s/it]

 91%|█████████▏| 4306/4716 [1:23:14<07:56,  1.16s/it]

 91%|█████████▏| 4307/4716 [1:23:15<07:54,  1.16s/it]

 91%|█████████▏| 4308/4716 [1:23:16<07:53,  1.16s/it]

 91%|█████████▏| 4309/4716 [1:23:17<07:52,  1.16s/it]

 91%|█████████▏| 4310/4716 [1:23:18<07:50,  1.16s/it]

 91%|█████████▏| 4311/4716 [1:23:19<07:50,  1.16s/it]

 91%|█████████▏| 4312/4716 [1:23:20<07:49,  1.16s/it]

 91%|█████████▏| 4313/4716 [1:23:22<07:48,  1.16s/it]

 91%|█████████▏| 4314/4716 [1:23:23<07:46,  1.16s/it]

 91%|█████████▏| 4315/4716 [1:23:24<07:45,  1.16s/it]

 92%|█████████▏| 4316/4716 [1:23:25<07:44,  1.16s/it]

 92%|█████████▏| 4317/4716 [1:23:26<07:43,  1.16s/it]

 92%|█████████▏| 4318/4716 [1:23:27<07:42,  1.16s/it]

 92%|█████████▏| 4319/4716 [1:23:29<07:40,  1.16s/it]

 92%|█████████▏| 4320/4716 [1:23:30<07:39,  1.16s/it]

 92%|█████████▏| 4321/4716 [1:23:31<07:38,  1.16s/it]

 92%|█████████▏| 4322/4716 [1:23:32<07:37,  1.16s/it]

 92%|█████████▏| 4323/4716 [1:23:33<07:35,  1.16s/it]

 92%|█████████▏| 4324/4716 [1:23:34<07:34,  1.16s/it]

 92%|█████████▏| 4325/4716 [1:23:36<07:33,  1.16s/it]

 92%|█████████▏| 4326/4716 [1:23:37<07:32,  1.16s/it]

 92%|█████████▏| 4327/4716 [1:23:38<07:31,  1.16s/it]

 92%|█████████▏| 4328/4716 [1:23:39<07:31,  1.16s/it]

 92%|█████████▏| 4329/4716 [1:23:40<07:29,  1.16s/it]

 92%|█████████▏| 4330/4716 [1:23:41<07:28,  1.16s/it]

 92%|█████████▏| 4331/4716 [1:23:43<07:26,  1.16s/it]

 92%|█████████▏| 4332/4716 [1:23:44<07:25,  1.16s/it]

 92%|█████████▏| 4333/4716 [1:23:45<07:24,  1.16s/it]

 92%|█████████▏| 4334/4716 [1:23:46<07:23,  1.16s/it]

 92%|█████████▏| 4335/4716 [1:23:47<07:22,  1.16s/it]

 92%|█████████▏| 4336/4716 [1:23:48<07:21,  1.16s/it]

 92%|█████████▏| 4337/4716 [1:23:49<07:20,  1.16s/it]

 92%|█████████▏| 4338/4716 [1:23:51<07:19,  1.16s/it]

 92%|█████████▏| 4339/4716 [1:23:52<07:18,  1.16s/it]

 92%|█████████▏| 4340/4716 [1:23:53<07:17,  1.16s/it]

 92%|█████████▏| 4341/4716 [1:23:54<07:16,  1.16s/it]

 92%|█████████▏| 4342/4716 [1:23:55<07:14,  1.16s/it]

 92%|█████████▏| 4343/4716 [1:23:56<07:13,  1.16s/it]

 92%|█████████▏| 4344/4716 [1:23:58<07:12,  1.16s/it]

 92%|█████████▏| 4345/4716 [1:23:59<07:10,  1.16s/it]

 92%|█████████▏| 4346/4716 [1:24:00<07:09,  1.16s/it]

 92%|█████████▏| 4347/4716 [1:24:01<07:08,  1.16s/it]

 92%|█████████▏| 4348/4716 [1:24:02<07:07,  1.16s/it]

 92%|█████████▏| 4349/4716 [1:24:03<07:06,  1.16s/it]

 92%|█████████▏| 4350/4716 [1:24:05<07:05,  1.16s/it]

 92%|█████████▏| 4351/4716 [1:24:06<07:04,  1.16s/it]

 92%|█████████▏| 4352/4716 [1:24:07<07:03,  1.16s/it]

 92%|█████████▏| 4353/4716 [1:24:08<07:02,  1.16s/it]

 92%|█████████▏| 4354/4716 [1:24:09<07:00,  1.16s/it]

 92%|█████████▏| 4355/4716 [1:24:10<06:59,  1.16s/it]

 92%|█████████▏| 4356/4716 [1:24:12<06:57,  1.16s/it]

 92%|█████████▏| 4357/4716 [1:24:13<06:56,  1.16s/it]

 92%|█████████▏| 4358/4716 [1:24:14<06:55,  1.16s/it]

 92%|█████████▏| 4359/4716 [1:24:15<06:54,  1.16s/it]

 92%|█████████▏| 4360/4716 [1:24:16<06:53,  1.16s/it]

 92%|█████████▏| 4361/4716 [1:24:17<06:52,  1.16s/it]

 92%|█████████▏| 4362/4716 [1:24:19<06:51,  1.16s/it]

 93%|█████████▎| 4363/4716 [1:24:20<06:50,  1.16s/it]

 93%|█████████▎| 4364/4716 [1:24:21<06:49,  1.16s/it]

 93%|█████████▎| 4365/4716 [1:24:22<06:48,  1.16s/it]

 93%|█████████▎| 4366/4716 [1:24:23<06:47,  1.16s/it]

 93%|█████████▎| 4367/4716 [1:24:24<06:46,  1.16s/it]

 93%|█████████▎| 4368/4716 [1:24:26<06:44,  1.16s/it]

 93%|█████████▎| 4369/4716 [1:24:27<06:43,  1.16s/it]

 93%|█████████▎| 4370/4716 [1:24:28<06:42,  1.16s/it]

 93%|█████████▎| 4371/4716 [1:24:29<06:40,  1.16s/it]

 93%|█████████▎| 4372/4716 [1:24:30<06:39,  1.16s/it]

 93%|█████████▎| 4373/4716 [1:24:31<06:37,  1.16s/it]

 93%|█████████▎| 4374/4716 [1:24:32<06:36,  1.16s/it]

 93%|█████████▎| 4375/4716 [1:24:34<06:35,  1.16s/it]

 93%|█████████▎| 4376/4716 [1:24:35<06:34,  1.16s/it]

 93%|█████████▎| 4377/4716 [1:24:36<06:33,  1.16s/it]

 93%|█████████▎| 4378/4716 [1:24:37<06:32,  1.16s/it]

 93%|█████████▎| 4379/4716 [1:24:38<06:31,  1.16s/it]

 93%|█████████▎| 4380/4716 [1:24:39<06:30,  1.16s/it]

 93%|█████████▎| 4381/4716 [1:24:41<06:29,  1.16s/it]

logging
logging the anndata

 93%|█████████▎| 4382/4716 [1:24:42<06:44,  1.21s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 93%|█████████▎| 4383/4716 [1:24:43<06:38,  1.20s/it]

 93%|█████████▎| 4384/4716 [1:24:44<06:33,  1.18s/it]

 93%|█████████▎| 4385/4716 [1:24:45<06:29,  1.18s/it]

 93%|█████████▎| 4386/4716 [1:24:47<06:25,  1.17s/it]

 93%|█████████▎| 4387/4716 [1:24:48<06:23,  1.17s/it]

 93%|█████████▎| 4388/4716 [1:24:49<06:21,  1.16s/it]

 93%|█████████▎| 4389/4716 [1:24:50<06:20,  1.16s/it]

 93%|█████████▎| 4390/4716 [1:24:51<06:18,  1.16s/it]

 93%|█████████▎| 4391/4716 [1:24:52<06:17,  1.16s/it]

 93%|█████████▎| 4392/4716 [1:24:54<06:16,  1.16s/it]

 93%|█████████▎| 4393/4716 [1:24:55<06:14,  1.16s/it]

 93%|█████████▎| 4394/4716 [1:24:56<06:13,  1.16s/it]

 93%|█████████▎| 4395/4716 [1:24:57<06:11,  1.16s/it]

 93%|█████████▎| 4396/4716 [1:24:58<06:10,  1.16s/it]

 93%|█████████▎| 4397/4716 [1:24:59<06:09,  1.16s/it]

 93%|█████████▎| 4398/4716 [1:25:00<06:08,  1.16s/it]

 93%|█████████▎| 4399/4716 [1:25:02<06:07,  1.16s/it]

 93%|█████████▎| 4400/4716 [1:25:03<06:05,  1.16s/it]

 93%|█████████▎| 4401/4716 [1:25:04<06:05,  1.16s/it]

 93%|█████████▎| 4402/4716 [1:25:05<06:03,  1.16s/it]

 93%|█████████▎| 4403/4716 [1:25:06<06:02,  1.16s/it]

 93%|█████████▎| 4404/4716 [1:25:07<06:01,  1.16s/it]

 93%|█████████▎| 4405/4716 [1:25:09<05:59,  1.16s/it]

 93%|█████████▎| 4406/4716 [1:25:10<05:58,  1.16s/it]

 93%|█████████▎| 4407/4716 [1:25:11<05:57,  1.16s/it]

 93%|█████████▎| 4408/4716 [1:25:12<05:56,  1.16s/it]

 93%|█████████▎| 4409/4716 [1:25:13<05:55,  1.16s/it]

 94%|█████████▎| 4410/4716 [1:25:14<05:54,  1.16s/it]

 94%|█████████▎| 4411/4716 [1:25:16<05:52,  1.16s/it]

 94%|█████████▎| 4412/4716 [1:25:17<05:51,  1.16s/it]

 94%|█████████▎| 4413/4716 [1:25:18<05:50,  1.16s/it]

 94%|█████████▎| 4414/4716 [1:25:19<05:49,  1.16s/it]

 94%|█████████▎| 4415/4716 [1:25:20<05:48,  1.16s/it]

 94%|█████████▎| 4416/4716 [1:25:21<05:47,  1.16s/it]

 94%|█████████▎| 4417/4716 [1:25:22<05:46,  1.16s/it]

 94%|█████████▎| 4418/4716 [1:25:24<05:45,  1.16s/it]

 94%|█████████▎| 4419/4716 [1:25:25<05:44,  1.16s/it]

 94%|█████████▎| 4420/4716 [1:25:26<05:43,  1.16s/it]

 94%|█████████▎| 4421/4716 [1:25:27<05:42,  1.16s/it]

 94%|█████████▍| 4422/4716 [1:25:28<05:40,  1.16s/it]

 94%|█████████▍| 4423/4716 [1:25:29<05:39,  1.16s/it]

 94%|█████████▍| 4424/4716 [1:25:31<05:38,  1.16s/it]

 94%|█████████▍| 4425/4716 [1:25:32<05:37,  1.16s/it]

 94%|█████████▍| 4426/4716 [1:25:33<05:35,  1.16s/it]

 94%|█████████▍| 4427/4716 [1:25:34<05:34,  1.16s/it]

 94%|█████████▍| 4428/4716 [1:25:35<05:33,  1.16s/it]

 94%|█████████▍| 4429/4716 [1:25:36<05:32,  1.16s/it]

 94%|█████████▍| 4430/4716 [1:25:38<05:30,  1.16s/it]

 94%|█████████▍| 4431/4716 [1:25:39<05:29,  1.16s/it]

 94%|█████████▍| 4432/4716 [1:25:40<05:28,  1.16s/it]

 94%|█████████▍| 4433/4716 [1:25:41<05:27,  1.16s/it]

 94%|█████████▍| 4434/4716 [1:25:42<05:26,  1.16s/it]

 94%|█████████▍| 4435/4716 [1:25:43<05:25,  1.16s/it]

 94%|█████████▍| 4436/4716 [1:25:44<05:24,  1.16s/it]

 94%|█████████▍| 4437/4716 [1:25:46<05:23,  1.16s/it]

 94%|█████████▍| 4438/4716 [1:25:47<05:21,  1.16s/it]

 94%|█████████▍| 4439/4716 [1:25:48<05:20,  1.16s/it]

 94%|█████████▍| 4440/4716 [1:25:49<05:19,  1.16s/it]

 94%|█████████▍| 4441/4716 [1:25:50<05:18,  1.16s/it]

 94%|█████████▍| 4442/4716 [1:25:51<05:17,  1.16s/it]

 94%|█████████▍| 4443/4716 [1:25:53<05:16,  1.16s/it]

 94%|█████████▍| 4444/4716 [1:25:54<05:15,  1.16s/it]

 94%|█████████▍| 4445/4716 [1:25:55<05:13,  1.16s/it]

 94%|█████████▍| 4446/4716 [1:25:56<05:12,  1.16s/it]

 94%|█████████▍| 4447/4716 [1:25:57<05:11,  1.16s/it]

 94%|█████████▍| 4448/4716 [1:25:58<05:10,  1.16s/it]

 94%|█████████▍| 4449/4716 [1:26:00<05:09,  1.16s/it]

 94%|█████████▍| 4450/4716 [1:26:01<05:07,  1.16s/it]

 94%|█████████▍| 4451/4716 [1:26:02<05:06,  1.16s/it]

 94%|█████████▍| 4452/4716 [1:26:03<05:05,  1.16s/it]

 94%|█████████▍| 4453/4716 [1:26:04<05:04,  1.16s/it]

 94%|█████████▍| 4454/4716 [1:26:05<05:03,  1.16s/it]

 94%|█████████▍| 4455/4716 [1:26:06<05:02,  1.16s/it]

 94%|█████████▍| 4456/4716 [1:26:08<05:01,  1.16s/it]

 95%|█████████▍| 4457/4716 [1:26:09<05:00,  1.16s/it]

 95%|█████████▍| 4458/4716 [1:26:10<04:58,  1.16s/it]

 95%|█████████▍| 4459/4716 [1:26:11<04:57,  1.16s/it]

 95%|█████████▍| 4460/4716 [1:26:12<04:56,  1.16s/it]

 95%|█████████▍| 4461/4716 [1:26:13<04:55,  1.16s/it]

 95%|█████████▍| 4462/4716 [1:26:15<04:54,  1.16s/it]

 95%|█████████▍| 4463/4716 [1:26:16<04:53,  1.16s/it]

 95%|█████████▍| 4464/4716 [1:26:17<04:51,  1.16s/it]

 95%|█████████▍| 4465/4716 [1:26:18<04:50,  1.16s/it]

 95%|█████████▍| 4466/4716 [1:26:19<04:49,  1.16s/it]

 95%|█████████▍| 4467/4716 [1:26:20<04:48,  1.16s/it]

 95%|█████████▍| 4468/4716 [1:26:22<04:47,  1.16s/it]

 95%|█████████▍| 4469/4716 [1:26:23<04:45,  1.16s/it]

 95%|█████████▍| 4470/4716 [1:26:24<04:44,  1.16s/it]

 95%|█████████▍| 4471/4716 [1:26:25<04:43,  1.16s/it]

 95%|█████████▍| 4472/4716 [1:26:26<04:42,  1.16s/it]

 95%|█████████▍| 4473/4716 [1:26:27<04:41,  1.16s/it]

 95%|█████████▍| 4474/4716 [1:26:28<04:40,  1.16s/it]

 95%|█████████▍| 4475/4716 [1:26:30<04:39,  1.16s/it]

 95%|█████████▍| 4476/4716 [1:26:31<04:38,  1.16s/it]

 95%|█████████▍| 4477/4716 [1:26:32<04:37,  1.16s/it]

 95%|█████████▍| 4478/4716 [1:26:33<04:36,  1.16s/it]

 95%|█████████▍| 4479/4716 [1:26:34<04:35,  1.16s/it]

 95%|█████████▍| 4480/4716 [1:26:35<04:33,  1.16s/it]

 95%|█████████▌| 4481/4716 [1:26:37<04:32,  1.16s/it]

 95%|█████████▌| 4482/4716 [1:26:38<04:32,  1.16s/it]

 95%|█████████▌| 4483/4716 [1:26:39<04:30,  1.16s/it]

 95%|█████████▌| 4484/4716 [1:26:40<04:29,  1.16s/it]

 95%|█████████▌| 4485/4716 [1:26:41<04:27,  1.16s/it]

 95%|█████████▌| 4486/4716 [1:26:42<04:26,  1.16s/it]

 95%|█████████▌| 4487/4716 [1:26:44<04:25,  1.16s/it]

 95%|█████████▌| 4488/4716 [1:26:45<04:24,  1.16s/it]

 95%|█████████▌| 4489/4716 [1:26:46<04:22,  1.16s/it]

 95%|█████████▌| 4490/4716 [1:26:47<04:21,  1.16s/it]

 95%|█████████▌| 4491/4716 [1:26:48<04:20,  1.16s/it]

 95%|█████████▌| 4492/4716 [1:26:49<04:19,  1.16s/it]

 95%|█████████▌| 4493/4716 [1:26:51<04:17,  1.16s/it]

 95%|█████████▌| 4494/4716 [1:26:52<04:16,  1.16s/it]

 95%|█████████▌| 4495/4716 [1:26:53<04:15,  1.16s/it]

 95%|█████████▌| 4496/4716 [1:26:54<04:14,  1.16s/it]

 95%|█████████▌| 4497/4716 [1:26:55<04:13,  1.16s/it]

 95%|█████████▌| 4498/4716 [1:26:56<04:12,  1.16s/it]

 95%|█████████▌| 4499/4716 [1:26:57<04:11,  1.16s/it]

 95%|█████████▌| 4500/4716 [1:26:59<04:10,  1.16s/it]

 95%|█████████▌| 4501/4716 [1:27:00<04:09,  1.16s/it]

 95%|█████████▌| 4502/4716 [1:27:01<04:07,  1.16s/it]

 95%|█████████▌| 4503/4716 [1:27:02<04:06,  1.16s/it]

 96%|█████████▌| 4504/4716 [1:27:03<04:05,  1.16s/it]

 96%|█████████▌| 4505/4716 [1:27:04<04:04,  1.16s/it]

 96%|█████████▌| 4506/4716 [1:27:06<04:02,  1.16s/it]

 96%|█████████▌| 4507/4716 [1:27:07<04:01,  1.16s/it]

 96%|█████████▌| 4508/4716 [1:27:08<04:01,  1.16s/it]

 96%|█████████▌| 4509/4716 [1:27:09<03:59,  1.16s/it]

 96%|█████████▌| 4510/4716 [1:27:10<03:58,  1.16s/it]

 96%|█████████▌| 4511/4716 [1:27:11<03:57,  1.16s/it]

 96%|█████████▌| 4512/4716 [1:27:13<03:56,  1.16s/it]

 96%|█████████▌| 4513/4716 [1:27:14<03:55,  1.16s/it]

 96%|█████████▌| 4514/4716 [1:27:15<03:53,  1.16s/it]

 96%|█████████▌| 4515/4716 [1:27:16<03:53,  1.16s/it]

 96%|█████████▌| 4516/4716 [1:27:17<03:51,  1.16s/it]

 96%|█████████▌| 4517/4716 [1:27:18<03:50,  1.16s/it]

 96%|█████████▌| 4518/4716 [1:27:19<03:49,  1.16s/it]

 96%|█████████▌| 4519/4716 [1:27:21<03:48,  1.16s/it]

 96%|█████████▌| 4520/4716 [1:27:22<03:47,  1.16s/it]

 96%|█████████▌| 4521/4716 [1:27:23<03:46,  1.16s/it]

 96%|█████████▌| 4522/4716 [1:27:24<03:44,  1.16s/it]

 96%|█████████▌| 4523/4716 [1:27:25<03:43,  1.16s/it]

 96%|█████████▌| 4524/4716 [1:27:26<03:42,  1.16s/it]

 96%|█████████▌| 4525/4716 [1:27:28<03:41,  1.16s/it]

 96%|█████████▌| 4526/4716 [1:27:29<03:39,  1.16s/it]

 96%|█████████▌| 4527/4716 [1:27:30<03:38,  1.16s/it]

 96%|█████████▌| 4528/4716 [1:27:31<03:37,  1.16s/it]

 96%|█████████▌| 4529/4716 [1:27:32<03:36,  1.16s/it]

 96%|█████████▌| 4530/4716 [1:27:33<03:35,  1.16s/it]

 96%|█████████▌| 4531/4716 [1:27:35<03:34,  1.16s/it]

 96%|█████████▌| 4532/4716 [1:27:36<03:33,  1.16s/it]

 96%|█████████▌| 4533/4716 [1:27:37<03:32,  1.16s/it]

 96%|█████████▌| 4534/4716 [1:27:38<03:30,  1.16s/it]

 96%|█████████▌| 4535/4716 [1:27:39<03:29,  1.16s/it]

 96%|█████████▌| 4536/4716 [1:27:40<03:28,  1.16s/it]

 96%|█████████▌| 4537/4716 [1:27:41<03:27,  1.16s/it]

 96%|█████████▌| 4538/4716 [1:27:43<03:26,  1.16s/it]

 96%|█████████▌| 4539/4716 [1:27:44<03:25,  1.16s/it]

 96%|█████████▋| 4540/4716 [1:27:45<03:24,  1.16s/it]

 96%|█████████▋| 4541/4716 [1:27:46<03:22,  1.16s/it]

 96%|█████████▋| 4542/4716 [1:27:47<03:21,  1.16s/it]

 96%|█████████▋| 4543/4716 [1:27:48<03:20,  1.16s/it]

 96%|█████████▋| 4544/4716 [1:27:50<03:19,  1.16s/it]

 96%|█████████▋| 4545/4716 [1:27:51<03:18,  1.16s/it]

 96%|█████████▋| 4546/4716 [1:27:52<03:17,  1.16s/it]

 96%|█████████▋| 4547/4716 [1:27:53<03:15,  1.16s/it]

 96%|█████████▋| 4548/4716 [1:27:54<03:14,  1.16s/it]

 96%|█████████▋| 4549/4716 [1:27:55<03:13,  1.16s/it]

 96%|█████████▋| 4550/4716 [1:27:57<03:12,  1.16s/it]

 97%|█████████▋| 4551/4716 [1:27:58<03:11,  1.16s/it]

 97%|█████████▋| 4552/4716 [1:27:59<03:10,  1.16s/it]

 97%|█████████▋| 4553/4716 [1:28:00<03:08,  1.16s/it]

 97%|█████████▋| 4554/4716 [1:28:01<03:07,  1.16s/it]

 97%|█████████▋| 4555/4716 [1:28:02<03:06,  1.16s/it]

 97%|█████████▋| 4556/4716 [1:28:04<03:05,  1.16s/it]

 97%|█████████▋| 4557/4716 [1:28:05<03:04,  1.16s/it]

 97%|█████████▋| 4558/4716 [1:28:06<03:02,  1.16s/it]

 97%|█████████▋| 4559/4716 [1:28:07<03:01,  1.16s/it]

 97%|█████████▋| 4560/4716 [1:28:08<03:00,  1.16s/it]

 97%|█████████▋| 4561/4716 [1:28:09<02:59,  1.16s/it]

 97%|█████████▋| 4562/4716 [1:28:10<02:58,  1.16s/it]

 97%|█████████▋| 4563/4716 [1:28:12<02:57,  1.16s/it]

 97%|█████████▋| 4564/4716 [1:28:13<02:56,  1.16s/it]

 97%|█████████▋| 4565/4716 [1:28:14<02:55,  1.16s/it]

 97%|█████████▋| 4566/4716 [1:28:15<02:54,  1.16s/it]

 97%|█████████▋| 4567/4716 [1:28:16<02:52,  1.16s/it]

 97%|█████████▋| 4568/4716 [1:28:17<02:51,  1.16s/it]

 97%|█████████▋| 4569/4716 [1:28:19<02:50,  1.16s/it]

 97%|█████████▋| 4570/4716 [1:28:20<02:49,  1.16s/it]

 97%|█████████▋| 4571/4716 [1:28:21<02:48,  1.16s/it]

 97%|█████████▋| 4572/4716 [1:28:22<02:46,  1.16s/it]

 97%|█████████▋| 4573/4716 [1:28:23<02:45,  1.16s/it]

 97%|█████████▋| 4574/4716 [1:28:24<02:44,  1.16s/it]

 97%|█████████▋| 4575/4716 [1:28:26<02:43,  1.16s/it]

 97%|█████████▋| 4576/4716 [1:28:27<02:42,  1.16s/it]

 97%|█████████▋| 4577/4716 [1:28:28<02:41,  1.16s/it]

 97%|█████████▋| 4578/4716 [1:28:29<02:39,  1.16s/it]

 97%|█████████▋| 4579/4716 [1:28:30<02:38,  1.16s/it]

 97%|█████████▋| 4580/4716 [1:28:31<02:37,  1.16s/it]

 97%|█████████▋| 4581/4716 [1:28:32<02:36,  1.16s/it]

 97%|█████████▋| 4582/4716 [1:28:34<02:35,  1.16s/it]

 97%|█████████▋| 4583/4716 [1:28:35<02:34,  1.16s/it]

 97%|█████████▋| 4584/4716 [1:28:36<02:33,  1.16s/it]

 97%|█████████▋| 4585/4716 [1:28:37<02:31,  1.16s/it]

 97%|█████████▋| 4586/4716 [1:28:38<02:30,  1.16s/it]

 97%|█████████▋| 4587/4716 [1:28:39<02:29,  1.16s/it]

 97%|█████████▋| 4588/4716 [1:28:41<02:28,  1.16s/it]

 97%|█████████▋| 4589/4716 [1:28:42<02:27,  1.16s/it]

 97%|█████████▋| 4590/4716 [1:28:43<02:26,  1.16s/it]

 97%|█████████▋| 4591/4716 [1:28:44<02:24,  1.16s/it]

 97%|█████████▋| 4592/4716 [1:28:45<02:23,  1.16s/it]

 97%|█████████▋| 4593/4716 [1:28:46<02:22,  1.16s/it]

 97%|█████████▋| 4594/4716 [1:28:48<02:21,  1.16s/it]

 97%|█████████▋| 4595/4716 [1:28:49<02:20,  1.16s/it]

 97%|█████████▋| 4596/4716 [1:28:50<02:19,  1.16s/it]

 97%|█████████▋| 4597/4716 [1:28:51<02:17,  1.16s/it]

 97%|█████████▋| 4598/4716 [1:28:52<02:16,  1.16s/it]

 98%|█████████▊| 4599/4716 [1:28:53<02:15,  1.16s/it]

 98%|█████████▊| 4600/4716 [1:28:55<02:14,  1.16s/it]

 98%|█████████▊| 4601/4716 [1:28:56<02:13,  1.16s/it]

 98%|█████████▊| 4602/4716 [1:28:57<02:12,  1.16s/it]

 98%|█████████▊| 4603/4716 [1:28:58<02:10,  1.16s/it]

 98%|█████████▊| 4604/4716 [1:28:59<02:09,  1.16s/it]

 98%|█████████▊| 4605/4716 [1:29:00<02:08,  1.16s/it]

 98%|█████████▊| 4606/4716 [1:29:01<02:07,  1.16s/it]

 98%|█████████▊| 4607/4716 [1:29:03<02:06,  1.16s/it]

 98%|█████████▊| 4608/4716 [1:29:04<02:05,  1.16s/it]

 98%|█████████▊| 4609/4716 [1:29:05<02:04,  1.16s/it]

 98%|█████████▊| 4610/4716 [1:29:06<02:02,  1.16s/it]

 98%|█████████▊| 4611/4716 [1:29:07<02:01,  1.16s/it]

 98%|█████████▊| 4612/4716 [1:29:08<02:00,  1.16s/it]

 98%|█████████▊| 4613/4716 [1:29:10<01:59,  1.16s/it]

 98%|█████████▊| 4614/4716 [1:29:11<01:58,  1.16s/it]

 98%|█████████▊| 4615/4716 [1:29:12<01:56,  1.16s/it]

 98%|█████████▊| 4616/4716 [1:29:13<01:55,  1.16s/it]

 98%|█████████▊| 4617/4716 [1:29:14<01:54,  1.16s/it]

 98%|█████████▊| 4618/4716 [1:29:15<01:53,  1.16s/it]

 98%|█████████▊| 4619/4716 [1:29:17<01:52,  1.16s/it]

 98%|█████████▊| 4620/4716 [1:29:18<01:51,  1.16s/it]

 98%|█████████▊| 4621/4716 [1:29:19<01:50,  1.16s/it]

 98%|█████████▊| 4622/4716 [1:29:20<01:49,  1.16s/it]

 98%|█████████▊| 4623/4716 [1:29:21<01:47,  1.16s/it]

 98%|█████████▊| 4624/4716 [1:29:22<01:46,  1.16s/it]

 98%|█████████▊| 4625/4716 [1:29:24<01:45,  1.16s/it]

 98%|█████████▊| 4626/4716 [1:29:25<01:44,  1.16s/it]

 98%|█████████▊| 4627/4716 [1:29:26<01:43,  1.16s/it]

 98%|█████████▊| 4628/4716 [1:29:27<01:42,  1.16s/it]

 98%|█████████▊| 4629/4716 [1:29:28<01:41,  1.16s/it]

 98%|█████████▊| 4630/4716 [1:29:29<01:39,  1.16s/it]

 98%|█████████▊| 4631/4716 [1:29:30<01:38,  1.16s/it]

 98%|█████████▊| 4632/4716 [1:29:32<01:37,  1.16s/it]

 98%|█████████▊| 4633/4716 [1:29:33<01:36,  1.16s/it]

 98%|█████████▊| 4634/4716 [1:29:34<01:35,  1.16s/it]

 98%|█████████▊| 4635/4716 [1:29:35<01:33,  1.16s/it]

 98%|█████████▊| 4636/4716 [1:29:36<01:32,  1.16s/it]

 98%|█████████▊| 4637/4716 [1:29:37<01:31,  1.16s/it]

 98%|█████████▊| 4638/4716 [1:29:39<01:30,  1.16s/it]

 98%|█████████▊| 4639/4716 [1:29:40<01:29,  1.16s/it]

 98%|█████████▊| 4640/4716 [1:29:41<01:28,  1.16s/it]

 98%|█████████▊| 4641/4716 [1:29:42<01:27,  1.16s/it]

 98%|█████████▊| 4642/4716 [1:29:43<01:25,  1.16s/it]

 98%|█████████▊| 4643/4716 [1:29:44<01:24,  1.16s/it]

 98%|█████████▊| 4644/4716 [1:29:46<01:23,  1.16s/it]

 98%|█████████▊| 4645/4716 [1:29:47<01:22,  1.16s/it]

 99%|█████████▊| 4646/4716 [1:29:48<01:21,  1.16s/it]

 99%|█████████▊| 4647/4716 [1:29:49<01:19,  1.16s/it]

 99%|█████████▊| 4648/4716 [1:29:50<01:18,  1.16s/it]

 99%|█████████▊| 4649/4716 [1:29:51<01:17,  1.16s/it]

 99%|█████████▊| 4650/4716 [1:29:53<01:16,  1.16s/it]

 99%|█████████▊| 4651/4716 [1:29:54<01:15,  1.16s/it]

 99%|█████████▊| 4652/4716 [1:29:55<01:14,  1.16s/it]

 99%|█████████▊| 4653/4716 [1:29:56<01:13,  1.16s/it]

 99%|█████████▊| 4654/4716 [1:29:57<01:11,  1.16s/it]

 99%|█████████▊| 4655/4716 [1:29:58<01:10,  1.16s/it]

 99%|█████████▊| 4656/4716 [1:29:59<01:09,  1.16s/it]

 99%|█████████▊| 4657/4716 [1:30:01<01:08,  1.16s/it]

 99%|█████████▉| 4658/4716 [1:30:02<01:07,  1.16s/it]

 99%|█████████▉| 4659/4716 [1:30:03<01:06,  1.16s/it]

 99%|█████████▉| 4660/4716 [1:30:04<01:04,  1.16s/it]

 99%|█████████▉| 4661/4716 [1:30:05<01:03,  1.16s/it]

 99%|█████████▉| 4662/4716 [1:30:06<01:02,  1.16s/it]

 99%|█████████▉| 4663/4716 [1:30:08<01:01,  1.16s/it]

 99%|█████████▉| 4664/4716 [1:30:09<01:00,  1.16s/it]

 99%|█████████▉| 4665/4716 [1:30:10<00:59,  1.16s/it]

 99%|█████████▉| 4666/4716 [1:30:11<00:58,  1.16s/it]

 99%|█████████▉| 4667/4716 [1:30:12<00:56,  1.16s/it]

 99%|█████████▉| 4668/4716 [1:30:13<00:55,  1.16s/it]

 99%|█████████▉| 4669/4716 [1:30:15<00:54,  1.16s/it]

 99%|█████████▉| 4670/4716 [1:30:16<00:53,  1.16s/it]

 99%|█████████▉| 4671/4716 [1:30:17<00:52,  1.16s/it]

 99%|█████████▉| 4672/4716 [1:30:18<00:51,  1.16s/it]

 99%|█████████▉| 4673/4716 [1:30:19<00:49,  1.16s/it]

 99%|█████████▉| 4674/4716 [1:30:20<00:48,  1.16s/it]

 99%|█████████▉| 4675/4716 [1:30:22<00:47,  1.16s/it]

 99%|█████████▉| 4676/4716 [1:30:23<00:46,  1.16s/it]

 99%|█████████▉| 4677/4716 [1:30:24<00:45,  1.16s/it]

 99%|█████████▉| 4678/4716 [1:30:25<00:44,  1.16s/it]

 99%|█████████▉| 4679/4716 [1:30:26<00:42,  1.16s/it]

 99%|█████████▉| 4680/4716 [1:30:27<00:41,  1.16s/it]

 99%|█████████▉| 4681/4716 [1:30:28<00:40,  1.16s/it]

 99%|█████████▉| 4682/4716 [1:30:30<00:39,  1.16s/it]

 99%|█████████▉| 4683/4716 [1:30:31<00:38,  1.16s/it]

 99%|█████████▉| 4684/4716 [1:30:32<00:37,  1.16s/it]

 99%|█████████▉| 4685/4716 [1:30:33<00:35,  1.16s/it]

 99%|█████████▉| 4686/4716 [1:30:34<00:34,  1.16s/it]

 99%|█████████▉| 4687/4716 [1:30:35<00:33,  1.16s/it]

 99%|█████████▉| 4688/4716 [1:30:37<00:32,  1.16s/it]

 99%|█████████▉| 4689/4716 [1:30:38<00:31,  1.16s/it]

 99%|█████████▉| 4690/4716 [1:30:39<00:30,  1.16s/it]

 99%|█████████▉| 4691/4716 [1:30:40<00:29,  1.16s/it]

 99%|█████████▉| 4692/4716 [1:30:41<00:27,  1.16s/it]

100%|█████████▉| 4693/4716 [1:30:42<00:26,  1.16s/it]

100%|█████████▉| 4694/4716 [1:30:44<00:25,  1.16s/it]

100%|█████████▉| 4695/4716 [1:30:45<00:24,  1.16s/it]

100%|█████████▉| 4696/4716 [1:30:46<00:23,  1.16s/it]

100%|█████████▉| 4697/4716 [1:30:47<00:22,  1.16s/it]

100%|█████████▉| 4698/4716 [1:30:48<00:20,  1.16s/it]

100%|█████████▉| 4699/4716 [1:30:49<00:19,  1.16s/it]

100%|█████████▉| 4700/4716 [1:30:51<00:18,  1.16s/it]

100%|█████████▉| 4701/4716 [1:30:52<00:17,  1.16s/it]

100%|█████████▉| 4702/4716 [1:30:53<00:16,  1.16s/it]

100%|█████████▉| 4703/4716 [1:30:54<00:15,  1.16s/it]

100%|█████████▉| 4704/4716 [1:30:55<00:13,  1.16s/it]

100%|█████████▉| 4705/4716 [1:30:56<00:12,  1.16s/it]

100%|█████████▉| 4706/4716 [1:30:58<00:11,  1.16s/it]

100%|█████████▉| 4707/4716 [1:30:59<00:10,  1.16s/it]

100%|█████████▉| 4708/4716 [1:31:00<00:09,  1.16s/it]

100%|█████████▉| 4709/4716 [1:31:01<00:08,  1.16s/it]

100%|█████████▉| 4710/4716 [1:31:02<00:06,  1.16s/it]

100%|█████████▉| 4711/4716 [1:31:03<00:05,  1.16s/it]

100%|█████████▉| 4712/4716 [1:31:04<00:04,  1.16s/it]

100%|█████████▉| 4713/4716 [1:31:06<00:03,  1.16s/it]

100%|█████████▉| 4714/4716 [1:31:07<00:02,  1.16s/it]

100%|█████████▉| 4715/4716 [1:31:08<00:01,  1.16s/it]

100%|██████████| 4716/4716 [1:31:09<00:00,  1.09s/it]

100%|██████████| 4716/4716 [1:31:10<00:00,  1.16s/it]

logging the anndata
AnnData object with n_obs × n_vars = 21348 × 0
    obsm: 'scprint_emb_cell_type_ontology_term_id'

too few cells to embed into a umap
too few cells to compute a clustering

PairwiseArrays with keys: connectivities, distances

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.287484 -11.989463 -13.20863  ... -12.583885 -12.314246 -12.609221]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.985809 -13.276242 -13.43663  ... -13.841144 -13.547167 -13.864904]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -4.477737   -6.756337  -14.280708  ...  -6.7992826  -6.668708
  -7.9460278]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.761066 -11.122486 -13.725286 ... -11.633519 -11.3619   -11.944536]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -5.563417  -7.568652 -14.466716 ...  -7.817851  -7.628983  -8.804189]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.895839 -13.186821 -13.350326 ... -13.746996 -13.452167 -13.773611]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.229366 -13.519742 -13.349653 ... -14.106861 -13.853463 -14.159381]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.794867 -10.84093  -17.152773 ... -11.0454   -10.823778 -11.396638]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.2190275 -10.765096  -19.45139   ... -10.792162  -10.594416
 -11.430538 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.330017 -10.654705 -17.423859 ... -10.819649 -10.272215 -10.935268]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.496182 -11.715083 -12.46989  ... -11.897333 -11.999976 -11.975838]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.278299 -10.309966  -9.468797 ...  -9.987146  -9.719845  -9.780843]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.050238 -8.070519 -8.506696 ... -7.553948 -7.747567 -8.133632]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.9444587 -5.2740145 -6.5677285 ... -5.231249  -5.0769634 -5.5023003]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.432016  -12.3973875 -13.065432  ... -12.973306  -12.686366
 -12.998697 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.0199633 -5.4548035 -6.8026905 ... -7.181624  -7.068931  -6.9790373]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.432664 -12.944362 -13.64486  ... -14.444151 -14.330178 -14.174689]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.082926 -14.64516  -14.618319 ... -15.477577 -15.700336 -15.22035 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.047914   -7.8293395 -10.204275  ...  -6.8366175  -7.6054363
  -5.746549 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.557165 -12.895599 -11.458273 ... -13.402063 -13.168859 -13.520831]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.8891945 -10.456007   -1.4827731 ... -10.204595  -10.007399
 -10.286364 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.411076 -12.35542  -13.058616 ... -12.927512 -12.645891 -12.951714]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.6685727 -5.9726305 -4.2473006 ... -5.6020174 -5.904783  -5.9814157]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -5.9390216  -7.1307783 -12.231711  ...  -7.5100513  -7.5351686
  -7.9773126]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.518628 -8.253263 -9.625433 ... -8.286664 -8.036358 -8.612286]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.2657    -12.4974785 -13.014952  ... -12.989502  -12.817688
 -13.132156 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.6997268  1.5666019 -6.9128356 ...  1.2543775  0.8551386  0.9850533]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.5997553  -0.31621376 -6.161428   ... -0.8173988  -0.9893803
 -1.1970712 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.0551994 -1.840245  -6.122788  ... -2.1753173 -2.3681166 -2.6009245]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -4.4816484  -7.4488015 -10.5372505 ...  -7.8604302  -7.5799785
  -8.269826 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.974361 -9.077842 -7.762935 ... -9.274497 -9.8834   -9.941338]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.785023  -9.802533 -10.051939 ... -10.184184 -10.512713 -10.705669]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.62535   -9.734928  -9.983384 ... -10.119695 -10.429869 -10.633537]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.871876 -12.900875 -12.950448 ... -13.645598 -13.374892 -13.629536]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.498159 -11.887722 -11.680816 ... -11.849456 -11.795846 -12.232184]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.064697 -10.873729 -14.040176 ...  -9.664737 -10.237771 -10.21308 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.405754  -5.4308276 -4.9823136 ... -5.489148  -5.5038033 -6.100437 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.2172527 -8.184423  -6.775504  ... -8.776994  -8.793128  -9.130719 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.14148  -9.3889   -9.214126 ... -9.146021 -9.350203 -9.444359]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.116589  -6.890642  -4.847055  ... -7.248736  -7.6196218 -7.99009  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.925773 -12.770801 -13.436743 ... -13.521836 -13.214253 -13.475758]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -4.685574   -7.5494156 -10.844864  ...  -8.004365   -7.723624
  -8.39118  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.693683 -12.686161 -10.962235 ... -12.857137 -12.693822 -13.128894]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.6385384 -7.5090203 -6.175424  ... -7.4517365 -7.68787   -7.997325 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.563262  -5.598634  -8.136316  ... -5.8945746 -5.161117  -5.761967 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.611632 -12.949344 -13.937308 ... -13.840296 -13.688585 -13.714651]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.804099  -13.08242   -13.357047  ... -13.618562  -13.3218355
 -13.6381855]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.7320948 -5.3848157 -6.157395  ... -5.3873897 -5.4362097 -6.00925  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.1319504 -6.351383  -6.3357296 ... -6.288263  -6.382948  -6.702166 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.2818344 -4.592971  -5.7586794 ... -4.4766994 -4.6666594 -4.996949 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.048204  -9.873819  -8.361023 ... -10.492    -10.010408 -10.316443]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.265029 -11.873758 -10.298581 ... -12.509217 -12.207557 -12.498842]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.8263516 -10.795262  -10.204581  ... -10.357145  -10.688542
 -11.279371 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.066167 -10.88561  -11.380822 ... -10.254204 -10.758515 -11.433471]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.997096  -5.5750136 -7.238269  ... -7.515607  -6.892585  -7.062803 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.699676 -12.22743  -10.938386 ... -12.797558 -12.44115  -12.918122]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.0465465 -6.351281  -5.6649847 ... -6.534889  -6.026844  -6.4155173]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.096074 -10.227558 -16.29839  ... -10.371225 -10.196358 -10.517302]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.524464 -12.851044 -13.16173  ... -13.381951 -13.096921 -13.43098 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.421495  -14.649637  -14.3495865 ... -15.611189  -15.603521
 -15.472244 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.737554 -10.707609 -12.282183 ... -10.104747 -10.674869 -10.906208]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.0237951 -4.598405  -5.980298  ... -4.8234262 -4.150856  -5.0788145]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.6687882 -6.2606716 -7.807923  ... -6.5325265 -5.7908006 -6.73374  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.3564503 -5.228378  -7.1465087 ... -5.025883  -4.7304006 -5.7324443]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.836585 -13.559468 -12.872721 ... -13.34897  -13.053108 -13.957338]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.523873  -2.1922176 -4.1938357 ... -3.7396958 -3.6049511 -3.7993577]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.6300921 -4.98217   -7.623665  ... -4.828018  -4.713137  -5.198833 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.912075 -10.536242 -10.900797 ...  -9.497491 -10.491439  -9.563188]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.839729 -8.051523 -8.329064 ... -7.801067 -8.336449 -7.808369]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.172227  -8.127258  -7.0370965 ... -8.48273   -8.831151  -8.972401 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-16.557364 -14.817189 -10.762444 ... -14.869949 -15.214662 -14.767857]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.248211  -6.8688693 -5.302171  ... -6.8103504 -6.8322806 -7.2935414]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.508189  -11.9360285 -12.698212  ... -12.061065  -12.331954
 -12.997652 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.510901 -12.909922  -8.06255  ... -12.593613 -12.730295 -13.366408]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.285009  -8.406058 -13.216989 ...  -8.517834  -8.494229  -9.138161]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.957761 -13.088918 -12.85791  ... -13.607979 -13.452613 -13.690671]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.79768   -5.2079062 -5.4261317 ... -5.1247826 -5.2478037 -5.639466 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.831345 -11.335912 -12.75218  ... -11.503499 -11.415449 -12.130363]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.659568  -9.405951 -11.180708 ...  -9.665079  -9.916386 -10.289694]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.721435 -13.998008 -16.577452 ... -15.854246 -15.724533 -15.165467]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.296247  -4.598845  -4.0904007 ... -4.790012  -4.6688375 -5.2199755]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.007446  -6.5597205 -5.4019136 ... -6.426795  -7.012479  -7.1436343]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.70254  -10.943482  -8.768635 ... -11.570353 -11.394192 -11.78445 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.8347216 -6.736431  -7.9579153 ... -7.763946  -7.713925  -7.5261407]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.7166395 -11.746562  -12.548812  ... -12.513117  -12.365727
 -12.400925 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.644849 -12.302549 -12.447263 ... -13.035825 -12.789973 -12.981222]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.651367 -12.124066 -12.641703 ... -12.865677 -12.640229 -12.785969]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.300259 -11.662737 -12.322562 ... -12.194147 -12.265959 -12.092409]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.967659 -12.175027 -12.061098 ... -12.527388 -12.620509 -12.275615]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.685006 -12.41448  -12.620757 ... -13.121023 -12.851795 -13.05142 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.841312 -12.525695 -12.633386 ... -13.23274  -12.990679 -13.166236]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.542683 -11.841335 -13.42664  ... -11.092851 -11.288322 -11.903644]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.628817  -11.062242  -12.290138  ... -11.456295  -11.252275
 -11.5933695]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.032887  -10.759309  -12.336087  ... -11.252722  -10.9572525
 -11.381551 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.1514144 -5.302744  -5.1234927 ... -5.411278  -5.03455   -5.3016763]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.51158  -10.501108 -10.145207 ... -10.874497 -10.362879 -10.793329]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.2031918 -6.786381  -7.4350405 ... -6.8249683 -6.383801  -6.857884 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.9041986  -8.511894  -10.609056  ...  -8.494827   -8.104486
  -8.655339 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.0863905 -8.373499  -7.1983457 ... -8.4883585 -8.12237   -8.4504795]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.025848 -7.932262 -7.51037  ... -8.121782 -7.891109 -8.015515]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.331415   -9.575158  -14.9459715 ...  -9.451401   -9.01572
  -8.789013 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.546279 -10.369555 -14.989512 ... -10.071945  -9.62028   -9.058451]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.994695 -10.487198 -13.886617 ... -10.691419 -10.212703 -10.183113]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.454662  -6.8059573 -8.064316  ... -6.800448  -6.6489086 -6.5349507]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.284956 -12.635271 -12.842451 ... -13.165189 -12.844665 -13.208275]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.551579 -12.889299 -12.91472  ... -13.399706 -13.155082 -13.460032]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.7196074 -5.0170574 -7.306727  ... -5.063487  -4.093748  -3.8786557]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.266427  -9.535284 -12.240358 ...  -9.782866  -9.341119  -9.523187]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.673992  -5.1631584 -5.2731023 ... -5.4573336 -5.2189865 -5.6352906]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.505765 -12.615794 -20.431126 ... -12.651334 -12.179231 -12.39879 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.935725  -6.86316   -8.329001  ... -6.9951453 -6.373417  -7.1453123]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.417003 -10.475753 -10.43539  ... -11.188876 -10.25037  -11.42124 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.955772  -12.139024  -10.211     ... -12.6922455 -12.296033
 -12.77573  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.304611  -13.7509365 -13.384556  ... -14.438819  -13.667302
 -14.213727 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.804873  -11.5044985 -11.408019  ... -12.0553    -11.701501
 -12.098324 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.070047  -9.88728   -6.825069 ... -10.26305   -9.663275 -10.294799]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.6855474 -7.098758  -7.0026145 ... -7.0500913 -6.776224  -7.0515456]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.329944  -10.726725   -9.511376  ... -10.798488  -10.697606
 -10.8990345]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.759722 -8.249801 -8.963754 ... -8.266153 -8.507581 -8.530309]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.949098 -7.871306 -6.929604 ... -7.775539 -8.245149 -8.080137]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.7882032 -6.132205  -6.7696104 ... -6.5234566 -6.2230086 -6.419817 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.320482  -10.273349  -10.978812  ... -10.6527195 -10.2015505
 -10.537685 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.3818774 -6.9079595 -6.6788745 ... -7.1071444 -6.605988  -6.980969 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.228111  -5.9928308 -6.991961  ... -6.3791094 -5.9514675 -6.213287 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.1888742 -5.997426  -5.51799   ... -6.143925  -5.6405573 -5.9328694]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.9101505 -6.7340617 -6.24261   ... -6.9015718 -6.3840017 -6.679634 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.952932  -14.038834  -12.910096  ... -14.8169365 -14.2248955
 -14.549642 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.4195633 -5.6669965 -8.503746  ... -5.8661475 -5.18891   -6.1540837]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.491548 -12.685033 -12.822363 ... -13.185667 -12.91452  -13.225243]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.67272  -8.836261 -9.885718 ... -9.076209 -8.610065 -8.818452]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.709854 -11.289535 -13.038662 ... -11.227612 -11.024901 -10.422178]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.591696 -15.014695 -10.360703 ... -15.764249 -14.928473 -15.425118]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.497915  -7.572249  -7.1543055 ... -7.4209595 -7.1770554 -7.409024 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.1417084 -5.454366  -8.503887  ... -5.5501046 -4.5281925 -4.378277 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.026333  -9.359298 -11.655842 ...  -9.378031  -8.985534  -8.820601]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.232385  -7.4420877 -6.8698673 ... -7.4874225 -7.1938834 -7.624964 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.832597  -8.039979  -7.43736   ... -8.104398  -7.8384557 -8.245281 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.29343   -5.2615743 -8.313757  ... -5.1805286 -4.3674855 -4.0193987]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.5527577 -6.1699476 -6.608418  ... -6.1479077 -5.753681  -6.012618 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.335459  -6.9464054 -7.835117  ... -6.969466  -6.5850396 -6.814938 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.921874  -4.3624334 -9.384534  ... -2.9263318 -4.0906134 -3.0281117]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.5478897 -4.534898  -4.936373  ... -5.7506895 -5.7362347 -5.4247136]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.437965 -13.740335 -12.106407 ... -14.130072 -14.044673 -14.364862]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.4352255 -6.6504703 -6.152424  ... -6.7904553 -6.314376  -6.6705513]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.444447  -8.385662  -7.9975986 ... -8.871722  -8.21987   -8.727478 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.2945223 -6.0192375 -7.034761  ... -6.4058743 -5.9810405 -6.239598 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.689011  -7.9547544 -9.21621   ... -8.4653845 -8.0667715 -8.222879 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.872754  -6.451208  -7.5840416 ... -6.495232  -5.964555  -6.3388934]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.2595167 -5.4095044 -7.5762124 ... -5.304856  -4.9336786 -5.1251473]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.915919  -5.663284  -6.64568   ... -6.051592  -5.642525  -5.9205117]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.123946  -3.9782407 -6.024509  ... -3.938444  -3.6768546 -4.1823955]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -5.388908   -7.900959  -10.715091  ...  -7.5018253  -7.428905
  -7.894151 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.834036 -10.1049   -10.05632  ... -10.313784 -10.407687 -10.524007]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.542974  -6.2573395 -6.521601  ... -6.382965  -5.884464  -6.2717295]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.8794475 -6.64421   -7.0243344 ... -6.759962  -6.2836504 -6.674275 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.1448402 -6.950084  -7.2267737 ... -7.0656056 -6.6077747 -6.9967785]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.6980143 -6.378911  -6.692177  ... -6.503351  -6.0061626 -6.388737 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.672161  -13.0317135 -13.404591  ... -13.561422  -13.261872
 -13.595814 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.663526 -12.997537 -13.734995 ... -13.520011 -13.256571 -13.570407]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.537614 -11.909649 -13.014309 ... -12.351929 -12.090012 -12.475968]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.847264 -12.912204  -9.814838 ... -13.484299 -12.74596  -13.503964]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.8987913 -7.134859  -9.918427  ... -7.3691664 -6.6239276 -7.5068555]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -3.9062078  -5.9848595 -10.083806  ...  -5.821804   -5.2908454
  -5.93486  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.237306  -11.247724  -12.18973   ... -11.611007  -11.3552685
 -11.619216 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.301976 -11.564475 -16.142199 ... -11.533342 -11.153973 -11.277824]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.073571  -9.541085  -7.9982557 ... -9.321208  -9.01343   -9.476567 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.6767327 -3.4610548 -5.0626507 ... -3.2999814 -2.873302  -3.4123056]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.0411384 -3.059455  -6.234158  ... -3.0580263 -3.3834739 -3.685763 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.4166594 -5.7788715 -9.893237  ... -6.026378  -5.6105175 -6.481668 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.676933 -8.865882 -6.942507 ... -9.335812 -9.681051 -9.813997]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.078494 -12.647285 -12.399829 ... -13.070749 -12.975183 -13.423168]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.526926 -11.467027 -12.131776 ... -11.86962  -11.612105 -12.569631]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.306286  -5.400325  -6.519774  ... -5.565383  -5.8113937 -6.276708 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.238764  -5.607894  -8.427041  ... -5.655495  -4.558425  -4.2709384]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.778181 -10.835207 -11.486665 ... -11.456122 -11.556093 -11.502264]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.134531 -10.668986 -11.918112 ... -11.309222 -11.470249 -11.377391]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.736486 -13.180233 -13.286739 ... -13.747206 -13.49884  -13.843334]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.766516  -6.73632   -7.9242706 ... -6.864203  -6.251221  -6.877386 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.590595  -6.1279154 -9.386254  ... -6.345397  -5.720089  -6.735616 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.549839  -8.884146  -9.612438 ...  -9.175017  -9.606329 -10.016209]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.391382 -11.926705 -11.572767 ... -11.89207  -12.222544 -12.320507]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -5.694275  -8.34928  -13.939986 ...  -8.146889  -8.437851  -8.985798]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.7814107 -4.664527  -4.2725883 ... -4.5537314 -4.607481  -5.3561068]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.126291 -12.194809 -12.568859 ... -12.660689 -12.465201 -12.76021 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.939346 -10.336188 -15.605642 ... -10.429264 -10.371467 -10.575327]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.79382   -9.653698 -10.891352 ...  -9.655895  -9.763874  -9.850525]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.6615565 -6.599464  -7.1364613 ... -6.2603903 -6.505704  -6.909006 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.9002306 -6.826261  -6.5010843 ... -6.602626  -6.722211  -7.136592 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.1067586  -8.669484  -11.647333  ...  -9.276361   -8.759677

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.154159  -5.8269043 -5.932085  ... -5.6184764 -5.750738  -6.1612983]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.426651  -10.451321   -5.7957683 ... -10.839537  -10.821833
 -11.200545 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.680117 -12.920219 -13.163249 ... -13.449514 -13.133843 -13.444891]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.633165  -6.475359  -7.059065  ... -6.3599076 -6.482429  -6.8739343]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.95525  -13.227829 -13.349112 ... -13.779861 -13.501724 -13.806392]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.6495392 -6.4751797 -7.058989  ... -6.352369  -6.480059  -6.8645334]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.762308  -5.8517485 -6.974873  ... -5.875298  -6.062768  -6.4416084]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.0352948 -3.2853775 -6.7624674 ... -3.5570457 -3.768518  -4.006679 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.732091  -13.108306  -13.300909  ... -13.670951  -13.441032
 -13.7757015]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.7043977 -5.336229  -6.5895452 ... -5.169001  -5.3695383 -5.740221 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.81513  -13.175748 -13.262589 ... -13.730538 -13.492607 -13.816235]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.823857  -13.188116  -13.286177  ... -13.7395735 -13.502233
 -13.824312 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.647632  -6.607154  -6.3565793 ... -6.5413604 -6.8020525 -7.2015524]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.727553 -12.538034 -11.842071 ... -12.901815 -12.859843 -13.091899]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.7788315 -12.155647  -12.926708  ... -12.688705  -12.568605
 -12.959086 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.8364933 -5.462257  -5.717341  ... -5.482762  -5.413209  -6.098767 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.8353245 -4.5722337 -5.563988  ... -4.644284  -4.5635624 -5.183173 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.46408   -5.6240063 -5.6419272 ... -4.8508983 -5.438153  -5.4918065]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.2036676 -8.192322  -6.0445347 ... -8.040342  -8.285632  -8.283373 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.787844 -8.884706 -8.903689 ... -9.108934 -9.191808 -9.4342  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.492165  -8.705092 -11.193068 ...  -8.843179  -8.700462  -9.300446]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.2808604 -6.1986737 -6.8553367 ... -6.161761  -6.1293077 -6.2123733]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.597334  -13.137032   -3.9649873 ... -12.929907  -12.655652
 -13.591009 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.905404 -13.261391 -13.419196 ... -13.826342 -13.520666 -13.859245]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.1278286  -7.61707   -10.889088  ...  -7.469151   -7.2167373
  -7.7404313]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.4648438 -8.198103  -8.621225  ... -8.4182205 -7.7615857 -8.301086 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.118349 -10.434996  -8.068236 ... -11.06398  -10.895767 -11.240416]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.5058656 -8.225299  -6.2778726 ... -8.043054  -8.397639  -8.336084 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.012234 -10.335888 -11.184784 ... -10.602346 -10.52449  -11.140123]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.4181542 -7.0664544 -7.544272  ... -6.871227  -7.0777364 -7.436957 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.559616  -11.0231     -5.9938974 ... -11.363103  -11.341161
 -11.771568 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.978528 -13.296272 -13.420146 ... -13.856736 -13.569128 -13.883322]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.097506  -6.115221  -7.5797257 ... -6.1280246 -5.667231  -6.4499965]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.474601 -12.692473 -12.858407 ... -13.24431  -12.975057 -13.299542]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.510998 -10.006083 -12.839371 ... -10.165022  -9.705799  -9.94055 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.5494523 -6.010981  -7.691089  ... -5.972253  -5.5066137 -5.8018494]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.5381823 -6.1012354 -7.294659  ... -6.1948075 -5.501367  -6.211254 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.253138 -10.862971 -13.839194 ... -10.793158 -10.479825 -10.733948]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -5.817979   -6.828622  -10.729019  ...  -6.775746   -6.2078958
  -6.380027 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.2862   -9.101348 -7.766291 ... -9.843434 -9.515963 -9.970553]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.704943  -12.782818  -13.3743105 ... -13.360138  -13.05431
 -13.374294 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.7076707 -6.537474  -7.595376  ... -6.703121  -6.148932  -6.717058 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.0203123 -6.3098755 -8.984543  ... -6.5263486 -5.879009  -6.834031 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.66031  -10.370193  -9.426349 ... -11.518576 -11.080095 -10.895773]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.383768  -4.9310455 -6.221423  ... -4.958414  -4.455394  -4.843426 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.2293923 -4.536465  -6.792228  ... -4.5744357 -3.9828935 -4.596874 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.676726 -12.964097 -12.951713 ... -13.491561 -13.240164 -13.55043 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.762159 -11.561712 -12.500248 ... -12.052596 -11.878671 -12.245682]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.043791 -12.073751 -11.940199 ... -12.488037 -12.670895 -12.578577]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.661269 -12.8649   -13.250934 ... -13.425649 -13.094032 -13.424055]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.85214  -12.213469 -11.916132 ... -12.491216 -12.495529 -12.875228]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.366012  -6.3917446 -6.9194956 ... -6.2071385 -6.4902315 -6.8382897]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.099036  -9.221261  -7.606475 ...  -9.779637  -9.397282 -10.204409]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.731288 -12.9745   -13.036401 ... -13.537347 -13.314108 -13.613158]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.062107 -12.357836 -11.842688 ... -12.850814 -12.491036 -12.864863]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.31664  -12.304828  -8.073955 ... -12.58822  -12.156787 -12.303505]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.513774  -12.84047   -12.429546  ... -13.365092  -13.035436
 -13.3932295]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.323113  -9.467231  -9.520684 ...  -9.901157  -9.748428 -10.305776]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.2482862 -6.4058537 -6.825023  ... -6.2558284 -6.5372458 -6.95478  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.364996  -11.578596  -11.215826  ... -11.9612875 -11.864462
 -12.116504 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.126267  -11.121213   -8.5283785 ... -11.798311  -11.599778
 -11.948952 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.1691027 -7.213928  -5.521217  ... -7.426391  -7.780199  -8.183164 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.2756467 -8.2811775 -4.0956264 ... -8.710248  -8.68573   -9.335464 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.348576  -10.42622    -5.6206827 ... -10.688029  -10.689926
 -11.029318 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.821197 -11.77798   -7.818805 ... -12.250105 -12.171546 -12.527424]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-15.522765 -14.290472 -10.684594 ... -14.405222 -14.612461 -14.273732]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.231884 -8.560472 -5.938516 ... -8.998337 -9.355932 -9.503916]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.820081 -11.798445 -12.391966 ... -12.36824  -11.997409 -12.379931]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.046278 -13.991131 -10.821873 ... -14.862536 -14.499592 -14.279911]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.590623 -13.977624  -9.818326 ... -14.325055 -13.91004  -14.41144 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.631371 -12.819507 -12.981193 ... -13.381267 -13.161087 -13.455146]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.894824  -11.130284  -10.673652  ... -11.3119135 -11.91356
 -11.91956  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.019713 -12.785612 -12.804261 ... -13.214361 -13.072275 -13.375256]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.680781 -12.895139 -13.272488 ... -13.429435 -13.133888 -13.443157]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.9129019 -5.192734  -6.752938  ... -5.123975  -5.287971  -5.6387935]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.178499  -12.700641  -11.888904  ... -13.268376  -13.1380205
 -13.341955 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.877763 -13.517103 -11.836809 ... -13.791436 -14.068142 -13.919499]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.837309 -4.91949  -5.174359 ... -5.274241 -4.912888 -5.24765 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.563825  -6.384773  -7.003581  ... -6.2587743 -6.411283  -6.7970552]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.885189 -12.772359  -9.153502 ... -13.229267 -13.030828 -13.357903]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.284159  -11.409136  -13.173622  ... -11.9573765 -12.087277
 -11.792473 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.233848  -11.36628   -12.0830345 ... -11.980148  -11.720833
 -12.173851 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.1162114 -6.1802826 -5.4169965 ... -6.3137107 -5.9780517 -6.285633 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.0023837 -6.578785  -8.534406  ... -6.2375617 -6.63421   -6.4219093]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.8600926 -4.1410184 -5.4621754 ... -5.964258  -5.43665   -5.5813017]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.7037134 -8.124267  -2.9406269 ... -8.364517  -8.142752  -8.524079 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.5371537 -5.8072543 -6.646935  ... -7.030988  -6.930034  -6.8188334]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.337898 -8.807584 -8.832182 ... -9.061013 -9.008682 -8.798558]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.2079387 -5.7662015 -6.12939   ... -7.1450105 -7.0496206 -6.97937  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.5352917 -6.0405297 -8.079115  ... -7.8633614 -7.26478   -7.388351 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.1412115 -10.47824    -7.5379004 ... -11.045702  -10.817769
 -11.007805 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.4486856 -4.7435255 -6.5164046 ... -6.362459  -6.145472  -6.0886617]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.069998 -13.05198  -13.391376 ... -13.832316 -13.526602 -13.811405]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.209772 -10.108627 -10.680932 ... -10.095394 -10.082318 -10.121106]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.391728 -12.428193 -11.227102 ... -13.269806 -12.866899 -13.308181]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.544545 -10.124383 -15.548099 ...  -9.793541 -10.266875  -9.991588]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.479697 -12.643895 -12.927287 ... -13.207801 -12.888657 -13.222494]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.1953535 -12.697378  -12.242259  ... -13.009132  -12.892071
 -13.322558 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.82206  -12.229153 -12.793704 ... -12.712802 -12.421218 -12.801054]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.9652424 -5.5156264 -7.3725405 ... -7.4418616 -6.803195  -6.9791102]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.803507  -7.075892  -6.8125534 ... -6.470108  -6.8264427 -7.2111626]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.244738 -12.298098 -10.693142 ... -13.132485 -12.743586 -13.23896 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -5.942169 -10.540241  -9.823054 ... -10.097543 -10.406145 -11.48345 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.759496 -13.030627 -13.28238  ... -13.547168 -13.302788 -13.607598]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.981277 -13.289861 -13.427805 ... -13.856675 -13.569235 -13.883004]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.6480749 -5.5456085 -6.4370875 ... -5.287132  -5.5055876 -5.9069223]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -5.415965   -7.9489923 -12.814557  ...  -7.385499   -7.5829015
  -8.044146 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.829236 -10.848538 -11.27031  ... -11.047712 -10.754421 -11.032539]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.436188 -11.712476 -12.040735 ... -12.153564 -12.09483  -12.42304 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.427513 -11.756863 -11.963954 ... -12.210886 -12.142593 -12.500091]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.7264385 -13.051419  -13.085327  ... -13.575975  -13.310122
 -13.623215 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.4893246 -5.306471  -6.4523163 ... -4.96988   -5.2179656 -5.5716786]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.721307 -11.800884 -12.410879 ... -12.327622 -12.14803  -12.472089]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.9329467 -6.8229403 -7.400244  ... -6.4191976 -6.705358  -7.0826697]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.45433  -11.053934  -8.461195 ... -11.182649 -11.681291 -11.759745]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.401372   -6.2485986  -0.44113138 ... -6.081205   -6.3058686
 -6.7099214 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.967778 -12.226186  -4.718168 ... -12.493429 -12.190523 -13.053385]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.198843 -13.674727 -10.693451 ... -14.153869 -13.821534 -13.995589]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.8318696 -9.039723  -8.437864  ... -9.228412  -8.91374   -9.3680525]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.927543 -9.093062 -8.666839 ... -9.303735 -8.974518 -9.414458]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.674869  -12.913976  -12.8873625 ... -13.411141  -13.1338825
 -13.456838 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -4.797621   -8.283947  -11.329732  ...  -8.809907   -8.141973
  -9.3840475]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.339021 -12.136462 -13.20645  ... -12.711548 -12.452483 -12.741292]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.349261  -13.166549  -11.4864435 ... -13.995213  -13.686702
 -13.92332  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.016413 -6.639718 -8.539998 ... -8.543698 -7.952286 -8.044383]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.691527 -12.753272 -13.365833 ... -13.323107 -13.024797 -13.336622]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.205522  -12.478307  -12.880722  ... -12.960327  -12.701005
 -13.0529995]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.251492 -12.296338 -12.965114 ... -12.817383 -12.62097  -13.142472]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.45001   -10.058529   -8.801645  ... -10.70333   -10.671358
 -10.9056425]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.962972 -8.633533 -8.408727 ... -8.86176  -8.774407 -8.813616]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.708563 -12.124404 -12.548169 ... -12.609294 -12.249216 -12.618586]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.2136183 -7.782579  -5.9613104 ... -7.641186  -8.038635  -7.949394 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.387621 -13.609703 -12.60657  ... -13.956767 -13.912768 -14.139165]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.5337963 -8.222705  -8.71644   ... -7.928004  -8.291834  -8.341144 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.547298 -12.730611 -13.016692 ... -13.274601 -13.0342   -13.333466]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.1022835 -12.196925  -10.072651  ... -12.994457  -12.6318865
 -13.053558 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.132082  -10.650369   -7.3332443 ... -11.116975  -11.253151
 -10.9997425]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.012813 -12.714226 -13.113564 ... -13.50829  -13.316729 -13.358129]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.5520377 -8.063321  -9.642829  ... -8.21845   -8.236555  -8.915035 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.783446 -11.233928  -7.942291 ... -11.97178  -11.826868 -11.935221]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.2091208 -5.772435  -6.5967655 ... -5.710245  -5.763662  -6.329909 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.656996  -12.501355   -7.1330447 ... -12.479701  -12.220843

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.2333956  -6.103531   -0.39136335 ... -5.905703   -6.1016083
 -6.49656   ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.170739   -6.7394814 -12.919477  ...  -6.161125   -6.543734
  -6.3613415]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.074401  -5.6174564 -6.722759  ... -5.486425  -5.766972  -6.0239573]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.5172515  -7.4074135 -12.899541  ...  -6.8843455  -7.2775908
  -7.0236588]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.0699415 -12.412517  -11.866626  ... -13.341065  -12.862085
 -13.295546 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.247148 -11.438061 -11.914549 ... -11.626878 -11.460967 -11.740108]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.2154608 -2.3586428 -4.6020203 ... -3.7942336 -3.6399107 -3.9367669]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.59014  -11.047434 -12.46983  ... -10.427956 -10.948176 -10.851483]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.633584  -9.877381  -5.199577 ... -10.169745 -10.184895 -10.689333]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.797753  -13.058893  -13.358785  ... -13.5963955 -13.30614
 -13.621407 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.931824  -11.7086115 -11.569926  ... -12.174945  -12.223421
 -12.391116 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.30826  -12.392048 -12.586927 ... -12.854479 -12.708532 -12.988732]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.679366  -10.754945   -6.420993  ... -10.74512   -10.5120125
 -10.641423 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.31953    -8.061232  -11.082937  ...  -8.384364   -8.043568
  -8.7477455]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.2560365 -5.2431297 -6.202353  ... -4.923301  -5.14621   -5.545779 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.5722663 -6.0479274 -6.0489726 ... -5.8768144 -5.9632215 -6.343144 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.5105424  -8.911031  -11.654042  ...  -9.422126   -9.159302
  -9.697845 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -6.238308  -8.682626 -11.632897 ...  -9.191588  -8.921443  -9.485447]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.9016063 -5.3582582 -5.966207  ... -4.5450964 -5.216661  -5.382853 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.158527 -10.738698 -11.978156 ... -11.08644  -11.007115 -11.396372]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.3856354 -5.796784  -6.6837626 ... -4.887419  -5.642874  -5.771854 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.354292  -8.153111  -7.683876  ... -8.3178    -7.8464026 -8.660626 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.8578922 -5.7843795 -4.2774496 ... -5.6682878 -5.5383244 -6.228531 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.036252  -12.045099   -6.2611723 ... -12.5295725 -12.237805
 -12.81676  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.720899  -5.933144  -6.3087735 ... -5.756697  -6.040708  -6.4519033]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.715773 -13.874043 -10.870752 ... -14.750603 -13.965684 -14.534807]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.665391  -12.7152405 -12.934004  ... -13.1975765 -12.971014
 -13.2441   ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.407395  -6.5395665 -6.7574763 ... -6.392181  -6.6701536 -7.083664 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.948313 -10.34408  -10.536146 ... -10.404386 -10.205233 -10.287604]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.8166184 -8.355254  -7.6084847 ... -8.368042  -8.521759  -8.822782 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-9.957266 -9.007607 -9.883823 ... -9.519606 -9.673189 -9.678825]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.082779  -11.9003315 -10.661394  ... -12.43596   -12.333015
 -12.651135 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.9548862 -6.089373  -5.6358294 ... -6.1259604 -6.062585  -6.705078 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.529527  -5.719609  -6.0786138 ... -5.5071836 -5.793575  -6.193519 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.438061  -11.809085  -12.337354  ... -12.200452  -11.9991045
 -12.317724 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.268338 -10.762976  -6.627234 ... -10.615564 -10.483393 -10.651507]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.8422556 -4.2210007 -4.9879165 ... -4.076234  -3.9002562 -4.0076337]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.2042055 -11.255796  -11.623877  ... -11.738028  -11.561234
 -12.097938 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.6142287 -6.8096495 -7.108013  ... -6.648619  -6.9098167 -7.3261104]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.810396   -8.021677  -10.758273  ...  -7.469441   -7.930734
  -7.4950213]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.1295714 -4.704637  -5.6765175 ... -3.7609437 -4.4484425 -3.8647535]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.0843115 -7.519126  -8.796761  ... -6.9345818 -7.3869658 -6.866848 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.955067  -7.216256  -7.4056873 ... -7.135688  -7.419732  -7.8649173]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-2.90713   -4.5246797  2.33038   ... -4.3093624 -4.5835814 -4.934624 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.57225  -12.804776 -12.749177 ... -13.327392 -13.105511 -13.413149]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.6770618 -5.3224335  0.8720599 ... -5.1255746 -5.3794007 -5.756977 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.9174092  -5.5615582   0.23277217 ... -5.3916903  -5.651268
 -6.0256996 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.8187103 -4.6117773 -5.714124  ... -4.3097973 -4.4780774 -4.5679245]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.0506    -9.5523   -10.509076 ...  -9.476878  -9.651394  -9.679393]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.780365  -5.6072464 -6.1578608 ... -5.4222984 -5.6267333 -5.963177 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.729179 -10.810174 -10.944041 ... -11.078349 -11.084677 -11.296708]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.5763361 -5.178507   1.0850505 ... -4.996835  -5.256352  -5.6510158]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.9431324 -9.136453  -2.647661  ... -9.513312  -9.292501  -9.853781 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.990096 -6.232202 -6.364651 ... -6.027153 -6.319374 -6.707298]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.2804708 -5.5879254 -5.836537  ... -5.394173  -5.665248  -6.0930963]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.065341  -5.8822775 -7.3800106 ... -5.425005  -5.470017  -5.3858213]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.340181  -5.5753    -6.206526  ... -5.311189  -5.4608884 -5.6504593]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.9037204 -5.485492  -7.118798  ... -7.4186807 -6.8050113 -6.974827 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.662033  -12.139986   -4.4918637 ... -12.410997  -12.369409
 -12.806115 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.65495  -12.875747 -13.186002 ... -13.41919  -13.197194 -13.503564]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.799304  -13.158118  -13.3028145 ... -13.708945  -13.470363
 -13.798169 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.334862  -13.133907   -3.6375751 ... -12.935013  -12.767298
 -13.330472 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.6435585 -12.912571  -13.022159  ... -13.471436  -13.1714325
 -13.501109 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.609216 -11.548283  -9.902583 ... -11.69877  -11.917809 -12.155308]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.361642 -12.866922 -12.628318 ... -13.266271 -13.248934 -13.44885 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.900242  -6.0700765 -8.988125  ... -6.196247  -5.1530175 -4.9251275]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.2227376  -5.3044395   0.37828797 ... -5.2482967  -5.3257537
 -5.842125  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.8994038 -5.5917478  1.0109845 ... -5.4239326 -5.680821  -6.0914545]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.908708  -14.732981  -13.618617  ... -15.364282  -15.100427
 -15.6246805]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.9460475  -5.7696395   0.33708838 ... -5.6357446  -5.8566856
 -6.2728767 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.98942  -14.048229 -13.957682 ... -14.171648 -14.418607 -14.765974]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.298194  -7.533004  -2.3888466 ... -8.288532  -8.372163  -8.79761  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.532304 -11.721333 -11.895078 ... -12.138704 -12.375575 -12.549059]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.081025 -11.928409  -9.328287 ... -12.727935 -12.398793 -12.758561]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.415947 -11.616979 -11.838528 ... -12.214053 -11.778883 -12.148652]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.621009 -12.929002 -13.170903 ... -13.468053 -13.184856 -13.505024]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.208833  -11.218641   -4.158006  ... -11.4900875 -11.120836
 -11.964468 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -4.1820073  -9.4884615 -11.261541  ...  -8.566466   -8.902891
 -10.065234 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.746475 -11.502462 -12.796448 ... -12.128949 -11.904517 -13.094272]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.364914 -12.164235 -13.159716 ... -12.752615 -12.467467 -12.769832]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.6169512 -6.184861  -6.936798  ... -6.028244  -6.226839  -6.6247663]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.921576  -6.1606607 -5.581833  ... -5.9859    -6.323225  -6.784281 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.253751 -12.682735 -12.443645 ... -12.980406 -13.152837 -13.132354]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.560048  -4.8472075 -6.627264  ... -4.688295  -4.122663  -5.0163608]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.7866616 -4.2567606 -6.3361015 ... -6.022756  -5.531348  -5.7463565]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.039138 -10.21472  -10.767145 ... -10.040831 -10.007421 -10.272076]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.577784  -12.205525  -12.152214  ... -12.623385  -12.847642
 -12.9328785]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.17694  -13.39344   -9.039358 ... -14.585415 -13.920607 -13.739847]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-13.10287  -14.50174  -10.93202  ... -15.795855 -14.966161 -14.903262]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.151194 -13.738745  -9.152593 ... -15.124381 -14.14567  -14.128869]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.093633 -8.640364 -7.634996 ... -9.162306 -8.884577 -9.322891]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.420529  -6.45967   -8.0176525 ... -8.255496  -8.11005   -8.001142 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.4920115 -5.378211  -5.4733853 ... -7.139226  -6.9134636 -6.859747 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.98758  -14.305618  -9.870449 ... -15.404809 -14.705364 -14.400931]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.704085  -5.319872  -5.674704  ... -6.683539  -6.63161   -6.5492587]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.279653  -6.024754  -5.8766327 ... -7.432384  -7.3348427 -7.255785 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.5518827 -5.2414584 -5.388867  ... -6.6618576 -6.561255  -6.4917364]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.2367454 -7.4618487 -6.209205  ... -9.021363  -8.660164  -8.698427 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.3190765 -7.4387226 -5.821333  ... -8.918287  -8.647579  -8.638429 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.979251  -6.179063  -4.663398  ... -7.6786275 -7.385787  -7.418318 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.6467814 -7.2312207 -5.3200073 ... -7.5224085 -7.817387  -7.797525 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.59246  -12.34493  -12.149108 ... -12.771833 -12.841558 -12.608096]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.155177  -13.122216  -13.506768  ... -13.915254  -13.6034155
 -13.882511 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.152012 -13.098342 -13.506599 ... -13.917584 -13.611012 -13.870255]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-14.280088  -12.984826  -15.078951  ... -14.514614  -14.651869
 -14.0206175]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.0083356 -5.515429  -6.644111  ... -7.2314467 -7.1067843 -7.002966 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.500395  -14.097762   -7.3279815 ... -14.76455   -14.416366
 -14.938223 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.684088  -4.1449857 -5.591413  ... -6.077155  -5.507954  -5.6696033]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.128889  -5.9434686 -6.265284  ... -7.6975226 -7.486207  -7.41428  ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-12.867441 -13.737402 -13.750462 ... -14.775131 -14.341628 -14.542216]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.758439 -13.032218 -12.836454 ... -13.714712 -13.444957 -13.81648 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.597654 -13.287827 -12.479359 ... -14.416017 -13.323861 -13.731396]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.936314 -12.938945 -13.193865 ... -13.727558 -13.402227 -13.702975]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.2786446 -9.157644  -6.218372  ... -9.062768  -9.156741  -9.389137 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-8.731127 -7.96731  -8.30192  ... -7.859808 -8.485724 -8.114013]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.550322 -11.202486 -10.672561 ... -11.566621 -11.373018 -12.086344]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.490404 -11.199297 -10.650538 ... -11.555635 -11.346444 -12.064228]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.9240243 -5.600489  -6.1728516 ... -5.39022   -5.657019  -5.9492784]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.123137  -6.745028  -7.1424747 ... -6.5166016 -6.725648  -7.0799923]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-5.3414674 -4.7648983 -6.4965367 ... -6.411374  -5.896569  -6.0682945]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -7.9192514 -10.231532  -10.383705  ... -10.571551  -10.35584
 -10.898986 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.2034464 -6.331742  -1.0490704 ... -6.2664504 -6.3649898 -6.803949 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.682179 -13.401472 -12.618325 ... -14.667855 -13.901859 -14.22191 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.796913 -12.751646 -12.634275 ... -13.190137 -13.074104 -13.400265]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -4.5759864  -7.139639  -10.879608  ...  -7.5560594  -7.302188
  -7.919591 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.166143 -10.753178 -12.251413 ... -10.976759 -11.245516 -11.20316 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.363557  -12.256623  -12.14435   ... -12.769675  -12.595052
 -12.8964205]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.430067 -9.091895 -7.894291 ... -9.7305   -9.381595 -9.835291]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.986717 -11.809044 -12.529177 ... -12.251288 -12.020742 -12.373932]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.1526437 -7.980077  -5.9331994 ... -7.7894306 -8.135949  -8.0817375]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.239513  -10.3584175 -12.471849  ... -10.97524   -10.609997
 -10.560169 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.451885 -10.230843 -12.260906 ... -10.749611 -10.343521 -10.242325]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -8.854059  -9.648521 -10.031775 ... -10.229315  -9.958027 -10.134965]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.142392  -9.590176  -8.99485  ... -10.054958  -9.805215  -9.883952]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.232931  -10.175585   -9.7781515 ... -10.752267  -10.441727
 -10.509097 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.776133  -10.296517  -10.15458   ... -10.970156  -10.608212
 -10.8344555]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-7.4370217 -6.671111  -7.5910726 ... -7.840585  -7.715102  -7.588193 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.475961 -10.766909 -12.155054 ... -11.247676 -10.783911 -10.788797]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.368059 -10.869711 -12.389096 ... -11.426711 -10.920041 -10.964212]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-10.119014 -10.315876 -10.454839 ... -10.980655 -10.611809 -10.761255]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.032693  -12.0575905 -12.036946  ... -12.566921  -12.236967
 -12.597899 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.569571 -11.751049 -12.233623 ... -12.240401 -12.020097 -12.32324 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.7302012 -4.0396132 -4.7741446 ... -3.8494182 -3.5036895 -3.5798502]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.9398947 -7.517532  -8.933824  ... -7.5997868 -7.068186  -7.314357 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-11.765107 -13.133526 -13.285574 ... -13.684029 -13.438187 -13.775069]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ -9.655362 -11.714184 -12.593093 ... -12.193219 -12.030835 -12.44617 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-6.3068995 -4.6153035 -5.927769  ... -6.397511  -5.864455  -5.978107 ]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.5920501 -5.169995  -9.39146   ... -5.9192047 -4.9583397 -6.1484637]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(
/lustre/fswork/projects/rech/xeg/uat95fg/tmp/ipykernel_790256/3660401145.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.1689862 -3.7618127 -5.503271  ... -4.1035347 -3.475385  -4.5121617]' has dtype incompatible with float16, please explicitly cast to a compatible dtype first.
  pred.iloc[:, :] = zero_shot_annotation_with_refinement(

PairwiseArrays with keys: connectivities, distances

{'cellxgene_census/dkd_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3432203389830508, 'macro': 0.25917444685094343, 'micro': 0.3432203389830508, 'weighted': 0.34017252137470233}}, 'cellxgene_census/dkd_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3550587343690792, 'macro': 0.27207633588309094, 'micro': 0.3550587343690792, 'weighted': 0.3524031871669568}}, 'cellxgene_census/dkd_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3561955286093217, 'macro': 0.2740563641826558, 'micro': 0.3561955286093217, 'weighted': 0.3538971563453317}}, 'cellxgene_census/dkd_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.361121636983706, 'macro': 0.2857142857142857, 'micro': 0.361121636983706, 'weighted': 0.361121636983706}}, 'cellxgene_census/gtex_v9_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4940849057506001, 'macro': 0.32408851632492214, 'micro': 0.4940849057506001, 'weighted': 0.46206164048799947}}, 'cellxgene_census/gtex_v9_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5688216892596455, 'macro': 0.5135325396389532, 'micro': 0.5688216892596455, 'weighted': 0.4995750709500925}}, 'cellxgene_census/gtex_v9_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5477059436913452, 'macro': 0.5371100686494984, 'micro': 0.5477059436913452, 'weighted': 0.5004916521764624}}, 'cellxgene_census/gtex_v9_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5477059436913452, 'macro': 0.5371100686494984, 'micro': 0.5477059436913452, 'weighted': 0.5004916521764624}}, 'cellxgene_census/hypomap_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9151834773007729, 'macro': 0.5292908086154148, 'micro': 0.9151834773007729, 'weighted': 0.8958082650738847}}, 'cellxgene_census/hypomap_cls': {'cell_type_ontology_term_id': {'accuracy': 0.968978102189781, 'macro': 0.7903908766961296, 'micro': 0.968978102189781, 'weighted': 0.9599403890312923}}, 'cellxgene_census/hypomap_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9662408759124088, 'macro': 0.7944891854261397, 'micro': 0.9662408759124088, 'weighted': 0.9600242874056126}}, 'cellxgene_census/hypomap_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.958029197080292, 'macro': 0.6603821577020906, 'micro': 0.958029197080292, 'weighted': 0.9567117318139766}}, 'cellxgene_census/mouse_pancreas_atlas_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.598702764742082, 'macro': 0.3839277116615119, 'micro': 0.598702764742082, 'weighted': 0.5978596408520496}}, 'cellxgene_census/mouse_pancreas_atlas_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5476114818345514, 'macro': 0.3843360153905832, 'micro': 0.5476114818345514, 'weighted': 0.547029675418304}}, 'cellxgene_census/mouse_pancreas_atlas_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5480351657663383, 'macro': 0.3843863741903414, 'micro': 0.5480351657663383, 'weighted': 0.5476649933162399}}, 'cellxgene_census/mouse_pancreas_atlas_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5475055608516047, 'macro': 0.3841849306256633, 'micro': 0.5475055608516047, 'weighted': 0.5468712781582488}}}

In [14]:
metrics

{'cellxgene_census/dkd_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3432203389830508,
   'macro': 0.25917444685094343,
   'micro': 0.3432203389830508,
   'weighted': 0.34017252137470233}},
 'cellxgene_census/dkd_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3550587343690792,
   'macro': 0.27207633588309094,
   'micro': 0.3550587343690792,
   'weighted': 0.3524031871669568}},
 'cellxgene_census/dkd_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.3561955286093217,
   'macro': 0.2740563641826558,
   'micro': 0.3561955286093217,
   'weighted': 0.3538971563453317}},
 'cellxgene_census/dkd_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.361121636983706,
   'macro': 0.2857142857142857,
   'micro': 0.361121636983706,
   'weighted': 0.361121636983706}},
 'cellxgene_census/gtex_v9_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4940849057506001,
   'macro': 0.32408851632492214,
   'micro': 0.4940849057506001,
   'weighted': 0.46206164048799947}},
 'cellxgene_census/gtex_v9_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5688216892596455,
   'macro': 0.5135325396389532,
   'micro': 0.5688216892596455,
   'weighted': 0.4995750709500925}},
 'cellxgene_census/gtex_v9_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5477059436913452,
   'macro': 0.5371100686494984,
   'micro': 0.5477059436913452,
   'weighted': 0.5004916521764624}},
 'cellxgene_census/gtex_v9_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5477059436913452,
   'macro': 0.5371100686494984,
   'micro': 0.5477059436913452,
   'weighted': 0.5004916521764624}},
 'cellxgene_census/hypomap_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9151834773007729,
   'macro': 0.5292908086154148,
   'micro': 0.9151834773007729,
   'weighted': 0.8958082650738847}},
 'cellxgene_census/hypomap_cls': {'cell_type_ontology_term_id': {'accuracy': 0.968978102189781,
   'macro': 0.7903908766961296,
   'micro': 0.968978102189781,
   'weighted': 0.9599403890312923}},
 'cellxgene_census/hypomap_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9662408759124088,
   'macro': 0.7944891854261397,
   'micro': 0.9662408759124088,
   'weighted': 0.9600242874056126}},
 'cellxgene_census/hypomap_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.958029197080292,
   'macro': 0.6603821577020906,
   'micro': 0.958029197080292,
   'weighted': 0.9567117318139766}},
 'cellxgene_census/mouse_pancreas_atlas_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.598702764742082,
   'macro': 0.3839277116615119,
   'micro': 0.598702764742082,
   'weighted': 0.5978596408520496}},
 'cellxgene_census/mouse_pancreas_atlas_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5476114818345514,
   'macro': 0.3843360153905832,
   'micro': 0.5476114818345514,
   'weighted': 0.547029675418304}},
 'cellxgene_census/mouse_pancreas_atlas_smooth_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5480351657663383,
   'macro': 0.3843863741903414,
   'micro': 0.5480351657663383,
   'weighted': 0.5476649933162399}},
 'cellxgene_census/mouse_pancreas_atlas_clust_cls': {'cell_type_ontology_term_id': {'accuracy': 0.5475055608516047,
   'macro': 0.3841849306256633,
   'micro': 0.5475055608516047,
   'weighted': 0.5468712781582488}}}

# same with scPRINT-V1

In [15]:
metrics = {
    "dkd_ref_cls": {
        "accuracy": 0.6050132734327139,
        "macro": 0.45858384601691754,
        "micro": 0.6050132734327139,
        "weighted": 0.5752358078815335,
    },
    "dkd_cls": {
        "accuracy": 0.5608184918529746,
        "macro": 0.49302410982269285,
        "micro": 0.5608184918529746,
        "weighted": 0.5370188034467204,
    },
    "dkd_smooth_cls": {
        "accuracy": 0.5941644562334217,
        "macro": 0.5355514243377841,
        "micro": 0.5941644562334217,
        "weighted": 0.5827613925424003,
    },
    "dkd_clust_cls": {
        "accuracy": 0.5985221674876847,
        "macro": 0.5,
        "micro": 0.5985221674876847,
        "weighted": 0.5985221674876847,
    },
    "gtex_v9_ref_cls": {
        "accuracy": 0.5690731903254497,
        "macro": 0.3561412506114705,
        "micro": 0.5690731903254497,
        "weighted": 0.5111263506144524,
    },
    "gtex_v9_cls": {
        "accuracy": 0.47340980187695514,
        "macro": 0.4771516389245344,
        "micro": 0.47340980187695514,
        "weighted": 0.4105919407683359,
    },
    "gtex_v9_smooth_cls": {
        "accuracy": 0.49930483142161974,
        "macro": 0.45026649672378827,
        "micro": 0.49930483142161974,
        "weighted": 0.46767738060420655,
    },
    "gtex_v9_clust_cls": {
        "accuracy": 0.49930483142161974,
        "macro": 0.45026649672378827,
        "micro": 0.49930483142161974,
        "weighted": 0.46767738060420655,
    },
    "hypomap_ref_cls": {
        "accuracy": 0.9331843865688121,
        "macro": 0.5582565920511067,
        "micro": 0.9331843865688121,
        "weighted": 0.9095025274318423,
    },
    "hypomap_cls": {
        "accuracy": 0.9817518248175182,
        "macro": 0.8017862483599127,
        "micro": 0.9817518248175182,
        "weighted": 0.9743770548339135,
    },
    "hypomap_smooth_cls": {
        "accuracy": 0.9908759124087592,
        "macro": 0.8529747502946833,
        "micro": 0.9908759124087592,
        "weighted": 0.986699566363855,
    },
    "hypomap_clust_cls": {
        "accuracy": 0.9963503649635036,
        "macro": 0.8811979101634128,
        "micro": 0.9963503649635036,
        "weighted": 0.9945824700566079,
    },
    "mouse_pancreas_atlas_ref_cls": {
        "accuracy": 0.9168991697845367,
        "macro": 0.736673219519387,
        "micro": 0.9168991697845367,
        "weighted": 0.8911321328642097,
    },
    "mouse_pancreas_atlas_cls": {
        "accuracy": 0.9222539985171062,
        "macro": 0.7317299769023702,
        "micro": 0.9222539985171062,
        "weighted": 0.8935278968505191,
    },
    "mouse_pancreas_atlas_smooth_cls": {
        "accuracy": 0.9653638385764219,
        "macro": 0.7529330761341159,
        "micro": 0.9653638385764219,
        "weighted": 0.9564964495219883,
    },
    "mouse_pancreas_atlas_clust_cls": {
        "accuracy": 0.9721427814850122,
        "macro": 0.7654463915196114,
        "micro": 0.9721427814850122,
        "weighted": 0.9663853668888627,
    },
}

In [16]:
for k, v in metrics.items():
    print(f"{k}: {v['accuracy']}")

mouse_pancreas_atlas_ref_cls: 0.91554001759347
mouse_pancreas_atlas_cls: 0.9174917491749175
mouse_pancreas_atlas_smooth_cls: 0.9504950495049505
mouse_pancreas_atlas_clust_cls: 0.8943894389438944
hypomap_ref_cls: 0.9337637202052348
hypomap_cls: 0.9556962025316456
hypomap_smooth_cls: 0.9810126582278481
hypomap_clust_cls: 0.9936708860759493
gtex_v9_ref_cls: 0.5696326616489581
gtex_v9_cls: 0.19325153374233128
gtex_v9_smooth_cls: 0.2331288343558282
gtex_v9_clust_cls: 0.2331288343558282
dkd_ref_cls: 0.6029201551970594
dkd_cls: 0.6589708247185849
dkd_smooth_cls: 0.6890650126349644
dkd_clust_cls: 0.7259361359981622

In [17]:
for k, v in res_label.items():
    if k is None:
        continue
    print(f"{k.split('/')[1]}: ")
    for l, w in v.items():
        if w is None:
            continue
        print(f"    {l}: {w['accuracy']}")
    m = 0
    for l, w in metrics.items():
        if l.startswith(k.split("/")[1]):
            if w["accuracy"] > m:
                m = w["accuracy"]
    print(f"    scPRINT-2 (zero-shot): {m:.3f}")

dkd:
    knn: 0.949
    logistic_regression: 0.9572
    majority_vote: 0.2954
    mlp: 0.954
    naive_bayes: 0.9269
    random_labels: 0.1808
    scanvi: 0.957
    scanvi_scarches: 0.957
    scgpt_zeroshot: 0.8486
    scimilarity: 0.8869
    scimilarity_knn: 0.9553
    seurat_transferdata: 0.9541
    singler: 0.9147
    true_labels: 1
    uce: 0.1813
    xgboost: 0.9644
    geneformer: NA
    scgpt_finetuned: NA
    scprint: NA
    scPRINT-2 (zero-shot): 0.726
gtex_v9:
    knn: 0.8523
    logistic_regression: 0.8829
    majority_vote: 0.0799
    mlp: 0.7784
    naive_bayes: 0.7599
    random_labels: 0.0324
    scanvi: 0.8899
    scanvi_scarches: 0.8797
    scgpt_zeroshot: 0.6234
    scimilarity: 0.6665
    scimilarity_knn: 0.8253
    seurat_transferdata: 0.841
    singler: 0.7903
    true_labels: 1
    uce: 0.0054
    xgboost: 0.8328
    geneformer: NA
    scgpt_finetuned: NA
    scprint: NA
    scPRINT-2 (zero-shot): 0.570
hypomap:
    knn: 0.9954
    logistic_regression: 0.9964
    majority_vote: 0.4516
    mlp: 0.9973
    naive_bayes: 0.9945
    random_labels: 0.3157
    scanvi: 0.9973
    scanvi_scarches: 0.9964
    scgpt_zeroshot: NA
    scimilarity: NA
    scimilarity_knn: NA
    seurat_transferdata: 0.9964
    singler: 0.9927
    true_labels: 1
    uce: 0.3841
    xgboost: 0.9973
    geneformer: NA
    scgpt_finetuned: NA
    scprint: NA
    scPRINT-2 (zero-shot): 0.994
immune_cell_atlas:
    knn: 0.8144
    logistic_regression: 0.885
    majority_vote: 0.0058
    mlp: 0.8676
    naive_bayes: 0.6389
    random_labels: 0.0481
    scanvi: 0.8926
    scanvi_scarches: 0.9035
    scgpt_zeroshot: 0.6787
    scimilarity: 0.8354
    scimilarity_knn: 0.8752
    seurat_transferdata: 0.8269
    singler: NA
    true_labels: 1
    uce: 0.0366
    xgboost: 0.8192
    geneformer: NA
    scgpt_finetuned: NA
    scprint: NA
    scPRINT-2 (zero-shot): 0.000
mouse_pancreas_atlas:
    knn: 0.9756
    logistic_regression: 0.978
    majority_vote: 0.3239
    mlp: 0.9703
    naive_bayes: 0.9502
    random_labels: 0.172
    scanvi: 0.9768
    scanvi_scarches: 0.9781
    scgpt_zeroshot: NA
    scimilarity: NA
    scimilarity_knn: NA
    seurat_transferdata: 0.9659
    singler: NA
    true_labels: 1
    uce: 0.1666
    xgboost: 0.9752
    geneformer: NA
    scgpt_finetuned: NA
    scprint: NA
    scPRINT-2 (zero-shot): 0.950
tabula_sapiens:
    knn: 0.1725
    logistic_regression: 0.1831
    majority_vote: 0.0211
    mlp: 0.2887
    naive_bayes: 0.1585
    random_labels: 0.0176
    scanvi: 0.1725
    scanvi_scarches: 0.2711
    scgpt_zeroshot: 0.162
    scimilarity: 0.2007
    scimilarity_knn: 0.1866
    seurat_transferdata: 0.3768
    singler: 0.1725
    true_labels: 1
    uce: 0.0106
    xgboost: 0.243
    geneformer: NA
    scgpt_finetuned: NA
    scprint: NA
    scPRINT-2 (zero-shot): 0.000

In [18]:
import pandas as pd

In [19]:
emb = pd.DataFrame(
    data={
        "Isolated labels": [
            0.621361,
            0.387139,
            0.520031,
            0.544676,
        ],
        "KMeans NMI": [
            0.655657,
            0.570249,
            0.61668,
            0.516657,
        ],
        "KMeans ARI": [
            0.439839,
            0.225424,
            0.280595,
            0.35364,
        ],
        "Silhouette label": [
            0.562681,
            0.61172,
            0.503856,
            0.547946,
        ],
        "cLISI": [
            0.99952,
            1.0,
            0.996694,
            0.992218,
        ],
        "BRAS": [
            0.739654,
            0.786443,
            0.803204,
            0.761943,
        ],
        "iLISI": [
            0.043682,
            0.0,
            0.077398,
            0.19466,
        ],
        "KBET": [
            0.239296,
            0.844529,
            0.353033,
            0.4047,
        ],
        "Graph connectivity": [
            0.854861,
            0.826488,
            0.704139,
            0.857564,
        ],
        "PCR comparison": [
            0,
            0.41701,
            0.096562,
            0.736278,
        ],
        "Batch correction": [
            0.375498,
            0.574894,
            0.406867,
            0.552538,
        ],
        "Bio conservation": [
            0.655811,
            0.558906,
            0.583571,
            0.591027,
        ],
        "Total": [
            0.543686,
            0.565301,
            0.51289,
            0.575631,
        ],
    },
    index=["mouse_pancreas_atlas", "hypomap", "gtex_v9", "dkd"],
)

In [20]:
FACT = 1.5
emb.iloc[:, -1] * (1 + FACT) - (emb.iloc[:, -2] * FACT + emb.iloc[:, -3])

mouse_pancreas_atlas    5.000000e-07
hypomap                -5.000000e-07
gtex_v9                 1.500000e-06
dkd                    -1.000000e-06
dtype: float64

In [21]:
for k, v in res.items():
    if k is None:
        continue
    print(f"{k.split('/')[1]}: ")
    for l, w in v.items():
        cell = 0

        for c in [
            "ari",
            "nmi",
            "isolated_label_asw",
            "clisi",
            "asw_label",
        ]:
            if w[c] == "NA":
                continue
            cell += w[c]
        cell /= 5
        batch = 0

        for b in [
            "pcr",
            "graph_connectivity",
            "asw_batch",
            "ilisi",
            "kbet",
        ]:
            if w[b] == "NA":
                continue
            batch += w[b]
        batch /= 5
        total = cell * 0.4 + batch * 0.6
        print(f"    {l}: {total:.3f}")
    # print(f"         Bio: {cell:.3f}")
    # print(f"         Batch: {batch:.3f}")
    if k.split("/")[1] not in emb.index:
        continue
    print(f"   scPRINT-2 (zero-shot): {emb.loc[k.split('/')[1], 'Total']:.3f}")
    # print(f"         Bio: {emb.loc[k.split('/')[1], 'Bio conservation']:.3f}")
# print(f"         Batch: {emb.loc[k.split('/')[1], 'Batch correction']:.3f}")

# cell_cycle_conservation
# hvg_overlap
# isolated_label_asw

dkd:
    batchelor_fastmnn: 0.627
    batchelor_mnn_correct: 0.601
    bbknn: 0.365
    combat: 0.643
    embed_cell_types: 0.791
    embed_cell_types_jittered: 0.790
    geneformer: 0.150
    harmony: 0.660
    harmonypy: 0.657
    liger: 0.713
    mnnpy: 0.414
    no_integration: 0.491
    no_integration_batch: 0.466
    pyliger: 0.705
    scalex: 0.642
    scanorama: 0.420
    scanvi: 0.634
    scgpt_zeroshot: 0.555
    scimilarity: 0.548
    scvi: 0.635
    shuffle_integration: 0.467
    shuffle_integration_by_batch: 0.250
    shuffle_integration_by_cell_type: 0.724
    uce: 0.505
    scgpt_finetuned: 0.000
    scprint: 0.000
   scPRINT-2 (zero-shot): 0.576
gtex_v9:
    batchelor_fastmnn: 0.538
    batchelor_mnn_correct: 0.000
    bbknn: 0.335
    combat: 0.642
    embed_cell_types: 0.762
    embed_cell_types_jittered: 0.762
    geneformer: 0.231
    harmony: 0.617
    harmonypy: 0.618
    liger: 0.555
    mnnpy: 0.000
    no_integration: 0.545
    no_integration_batch: 0.553
    pyliger: 0.569
    scalex: 0.593
    scanorama: 0.323
    scanvi: 0.604
    scgpt_zeroshot: 0.556
    scimilarity: 0.552
    scvi: 0.617
    shuffle_integration: 0.438
    shuffle_integration_by_batch: 0.298
    shuffle_integration_by_cell_type: 0.674
    uce: 0.559
    scgpt_finetuned: 0.000
    scprint: 0.000
   scPRINT-2 (zero-shot): 0.513
hypomap:
    batchelor_fastmnn: 0.477
    batchelor_mnn_correct: 0.000
    bbknn: 0.338
    combat: 0.554
    embed_cell_types: 0.682
    embed_cell_types_jittered: 0.682
    geneformer: 0.000
    harmony: 0.521
    harmonypy: 0.522
    liger: 0.522
    mnnpy: 0.000
    no_integration: 0.435
    no_integration_batch: 0.527
    pyliger: 0.519
    scalex: 0.554
    scanorama: 0.294
    scanvi: 0.464
    scgpt_zeroshot: 0.000
    scimilarity: 0.000
    scvi: 0.469
    shuffle_integration: 0.383
    shuffle_integration_by_batch: 0.262
    shuffle_integration_by_cell_type: 0.505
    uce: 0.460
    scgpt_finetuned: 0.000
    scprint: 0.000
   scPRINT-2 (zero-shot): 0.565
immune_cell_atlas:
    batchelor_fastmnn: 0.608
    batchelor_mnn_correct: 0.000
    bbknn: 0.341
    combat: 0.620
    embed_cell_types: 0.862
    embed_cell_types_jittered: 0.861
    geneformer: 0.190
    harmony: 0.627
    harmonypy: 0.627
    liger: 0.622
    mnnpy: 0.000
    no_integration: 0.501
    no_integration_batch: 0.514
    pyliger: 0.625
    scalex: 0.607
    scanorama: 0.355
    scanvi: 0.649
    scgpt_zeroshot: 0.520
    scimilarity: 0.593
    scvi: 0.628
    shuffle_integration: 0.460
    shuffle_integration_by_batch: 0.279
    shuffle_integration_by_cell_type: 0.702
    uce: 0.548
    scgpt_finetuned: 0.000
    scprint: 0.000
mouse_pancreas_atlas:
    batchelor_fastmnn: 0.561
    batchelor_mnn_correct: 0.000
    bbknn: 0.330
    combat: 0.631
    embed_cell_types: 0.749
    embed_cell_types_jittered: 0.749
    geneformer: 0.000
    harmony: 0.592
    harmonypy: 0.589
    liger: 0.569
    mnnpy: 0.000
    no_integration: 0.576
    no_integration_batch: 0.571
    pyliger: 0.570
    scalex: 0.577
    scanorama: 0.465
    scanvi: 0.612
    scgpt_zeroshot: 0.000
    scimilarity: 0.000
    scvi: 0.607
    shuffle_integration: 0.459
    shuffle_integration_by_batch: 0.315
    shuffle_integration_by_cell_type: 0.642
    uce: 0.516
    scgpt_finetuned: 0.000
    scprint: 0.000
   scPRINT-2 (zero-shot): 0.544
tabula_sapiens:
    batchelor_fastmnn: 0.535
    batchelor_mnn_correct: 0.000
    bbknn: 0.290
    combat: 0.607
    embed_cell_types: 0.794
    embed_cell_types_jittered: 0.795
    geneformer: 0.232
    harmony: 0.556
    harmonypy: 0.555
    liger: 0.471
    mnnpy: 0.000
    no_integration: 0.499
    no_integration_batch: 0.530
    pyliger: 0.472
    scalex: 0.572
    scanorama: 0.314
    scanvi: 0.569
    scgpt_zeroshot: 0.522
    scimilarity: 0.505
    scvi: 0.564
    shuffle_integration: 0.394
    shuffle_integration_by_batch: 0.275
    shuffle_integration_by_cell_type: 0.624
    uce: 0.486
    scgpt_finetuned: 0.000
    scprint: 0.000

# same with finetuning batch

In [22]:
## ISSUE: many batches to correct, mmd might not be the right tool

## same with fine tuning class

<span id="papermill-error-cell" style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">Execution using papermill encountered an exception here and stopped:</span>

In [23]:
finetuner = FinetuneBatchClass(
    batch_key="donor_id",
    max_len=3000,
)

model, metrics[name + "_fine_tuning"] = finetuner(model=model, train_adata=adata)

TypeError: FinetuneBatchClass.__call__() got an unexpected keyword argument 'train_adata'

In [ ]:
metrics