<span style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">An Exception was encountered at '<a href="#papermill-error-cell">In [14]</a>'.</span>

# open problems (task batch correction / label proj)

In [1]:
import pandas as pd
import requests
import json
from scib_metrics.benchmark import Benchmarker, BioConservation, BatchCorrection
import scanpy as sc
from scprint import scPrint
from scdataloader import Preprocessor
from scprint.tasks import Embedder, FinetuneBatchClass
from scprint.tasks.cell_emb import compute_classification
from scprint.utils import zero_shot_annotation_with_refinement
import numpy as np
import os

%load_ext autoreload
%autoreload 2

/lustre/fswork/projects/rech/xeg/uat95fg/scPRINT/.venv/lib/python3.12/site-packages/transformers/utils/hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(

→ connected lamindb: jkobject/scprint2

/lustre/fswork/projects/rech/xeg/uat95fg/simpler_flash/src/simpler_flash/layer_norm.py:1044: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd
/lustre/fswork/projects/rech/xeg/uat95fg/simpler_flash/src/simpler_flash/layer_norm.py:1107: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd

In [2]:
! uv pip list | grep scib #same version as OP

scib                       1.1.7
scib-metrics               0.5.6

In [3]:
LOC = "./data/" #"/pasteur/appa/scratch/jkalfon/data/spcrint_data/"

In [4]:
if not os.path.exists("data/results_batch.json"):
    url = "https://raw.githubusercontent.com/openproblems-bio/website/main/results/batch_integration/data/results.json"
    response = requests.get(url)

    with open("data/results_batch.json", "w") as f:
        f.write(response.text)

if not os.path.exists("data/results_label.json"):
    url = "https://raw.githubusercontent.com/openproblems-bio/website/main/results/label_projection/data/results.json"
    response = requests.get(url)

    with open("data/results_label.json", "w") as f:
        f.write(response.text)

print("File downloaded successfully!")

File downloaded successfully!

In [5]:
res = {}
with open("data/results_batch.json", "r") as f:
    data_batch = json.load(f)
for dataset in data_batch:
    dataset_id = dataset["dataset_id"]
    if dataset_id not in res:
        res[dataset_id] = {}
    res[dataset_id].update({dataset["method_id"]: dataset["metric_values"]})

In [6]:
res_label = {}
with open("data/results_label.json", "r") as f:
    data_label = json.load(f)
for dataset in data_label:
    dataset_id = dataset["dataset_id"]
    if dataset_id not in res_label:
        res_label[dataset_id] = {}
    res_label[dataset_id].update({dataset["method_id"]: dataset["metric_values"]})

res_label.keys()

dict_keys(['cellxgene_census/dkd', 'cellxgene_census/gtex_v9', 'cellxgene_census/hypomap', 'cellxgene_census/immune_cell_atlas', 'cellxgene_census/mouse_pancreas_atlas', 'cellxgene_census/tabula_sapiens', None])

In [7]:
pd.DataFrame(res_label["cellxgene_census/dkd"])

,knn,logistic_regression,majority_vote,mlp,naive_bayes,random_labels,scanvi,scanvi_scarches,scgpt_zeroshot,scimilarity,scimilarity_knn,seurat_transferdata,singler,true_labels,uce,xgboost,geneformer,scgpt_finetuned,scprint
accuracy,0.9490,0.9572,0.2954,0.9540,0.9269,0.1808,0.9570,0.9570,0.8486,0.8869,0.9553,0.9541,0.9147,1,0.1813,0.9644,NA,NA,NA
f1_macro,0.9286,0.9413,0.0351,0.9245,0.9181,0.0774,0.9360,0.9366,0.5239,0.6233,0.9292,0.9344,0.9027,1,0.0743,0.9225,NA,NA,NA
f1_micro,0.9490,0.9572,0.2954,0.9540,0.9269,0.1808,0.9570,0.9570,0.8486,0.8869,0.9553,0.9541,0.9147,1,0.1813,0.9644,NA,NA,NA
f1_weighted,0.9487,0.9567,0.1347,0.9529,0.9296,0.1801,0.9579,0.9567,0.8339,0.8655,0.9556,0.9544,0.9192,1,0.1790,0.9634,NA,NA,NA

In [8]:
pd.DataFrame(res["cellxgene_census/dkd"])

,batchelor_fastmnn,batchelor_mnn_correct,bbknn,combat,embed_cell_types,embed_cell_types_jittered,geneformer,harmony,harmonypy,liger,mnnpy,no_integration,no_integration_batch,pyliger,scalex,scanorama,scanvi,scgpt_zeroshot,scimilarity,scvi,shuffle_integration,shuffle_integration_by_batch,shuffle_integration_by_cell_type,uce,scgpt_finetuned,scprint
ari,0.7599,0.757,0.7666,0.7673,1,1,0.0024,0.7867,0.7655,0.7463,0.1674,0.5999,0.2884,0.6633,0.6177,0.2302,0.7806,0.7597,0.7103,0.8284,-0.0001,0.0069,0.5604,0.508,NA,NA
asw_batch,0.894,0.799,NA,0.9123,0.9593,0.9573,0.4736,0.9066,0.905,0.8743,0.8846,0.8913,0.7086,0.8876,0.8582,0.9048,0.9099,0.8888,0.8264,0.9166,0.9426,0.9005,0.9328,0.9286,NA,NA
asw_label,0.6657,0.6657,NA,0.613,0.9897,0.9897,0.364,0.6466,0.6463,0.6295,0.5027,0.6276,0.5116,0.6284,0.5917,0.5009,0.6334,0.6318,0.7111,0.5754,0.4945,0.4895,0.6276,0.587,NA,NA
cell_cycle_conservation,0.8574,0.8692,NA,0.7925,0.8104,0.8099,0.0527,0.8495,0.8466,0.6013,0.3797,0.8248,0.8609,0.4286,0.3481,0.3818,0.6302,0.7563,0.6936,0.5349,0.0667,0.0726,0.7069,0.8451,NA,NA
clisi,1,1,0.9622,0.9997,1,1,0.7461,1,1,0.9991,0.8921,0.9998,0.9968,0.9995,0.9939,0.8857,1,0.9994,0.9997,0.9992,0.7301,0.7424,0.9998,0.999,NA,NA
graph_connectivity,0.9745,0.9696,0.984,0.9728,1,1,0.0109,0.977,0.9765,0.9628,0.5458,0.9701,0.5229,0.968,0.9278,0.5459,0.9962,0.9631,0.971,0.9812,0.2488,0.2596,0.9703,0.9568,NA,NA
hvg_overlap,NA,0.4293,NA,0.6649,NA,NA,NA,NA,NA,NA,0.4056,NA,NA,NA,0.2665,0.2484,NA,NA,NA,NA,0.6462,1,0.668,NA,NA,NA
ilisi,0.272,0.2893,0.3526,0.1644,0.4348,0.4305,0,0.333,0.3319,0.4223,0.1732,0.0754,0.0076,0.4235,0.3097,0.2657,0.3153,0.2272,0.2297,0.303,0.4782,0.0755,0.4322,0.2298,NA,NA
isolated_label_asw,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
isolated_label_f1,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
kbet,0.3806,0.2482,NA,0.1687,0.949,0.9433,0,0.4251,0.4187,0.7526,0,0.1529,0.0946,0.7672,0.3209,0.0001,0.2521,0.235,0.2235,0.2538,0.4093,0.0113,0.9511,0.2174,NA,NA
nmi,0.829,0.8248,0.8228,0.8306,1,1,0.0315,0.8322,0.8233,0.8002,0.2288,0.7735,0.5322,0.7619,0.6992,0.2268,0.8646,0.7909,0.7877,0.8495,0.0013,0.015,0.761,0.7228,NA,NA
pcr,0.5339,0.5344,NA,0.9998,0.5898,0.5896,0,0.6805,0.6897,0.8142,0.6494,0,1,0.7925,0.9998,0.5585,0.6277,0.19,0.1773,0.6671,0.9975,0,0.7788,0,NA,NA

In [9]:
model_checkpoint_file = "../models/ogvvg2z7-v1.ckpt"

In [10]:
model = scPrint.load_from_checkpoint(
    model_checkpoint_file, precpt_gene_emb=None, gene_pos_file=None
)
model = model.to("cuda")

FYI: scPrint is not attached to a `Trainer`.

In [11]:
datasets = {
    "cellxgene_census/dkd": "https://datasets.cellxgene.cziscience.com/46d8d92b-32e0-4ca5-9907-4dbf519c7fc3.h5ad",  # 0.3
    "cellxgene_census/gtex_v9": "https://datasets.cellxgene.cziscience.com/002308e1-0121-4aa1-b8f2-9d034cf44b0f.h5ad",  # 1gb
    "cellxgene_census/hypomap": "https://datasets.cellxgene.cziscience.com/d3be7423-d664-4913-89a9-a506cae4c28f.h5ad",  # 4gb
    "cellxgene_census/mouse_pancreas_atlas": "https://datasets.cellxgene.cziscience.com/49243c50-bf0c-4b10-87f8-55ec9f455399.h5ad",  # 4gb
    # "cellxgene_census/immune_cell_atlas": "https://datasets.cellxgene.cziscience.com/78819b62-0699-4672-8dc8-d9317b04d255.h5ad",  # 3gb
    # 'cellxgene_census/tabula_sapiens': 'https://datasets.cellxgene.cziscience.com/5a495302-b7cd-4bf9-853e-95627b00bb03.h5ad' # 42gb
}

test = {
    "cellxgene_census/dkd": ["control_3"],
    "cellxgene_census/gtex_v9": ["GTEX-16BQI"],
    "cellxgene_census/hypomap": ["SRR9000488"],
    "cellxgene_census/mouse_pancreas_atlas": [
        "mouse_pancreatic_islet_atlas_Hrovatin__VSG__MUC13639"
    ],
}

In [12]:
metrics = {}
metacell = True  # model.expr_emb_style == "metacell"

In [13]:
# TODO: most var + 4000 genes works better for batch correction

<span id="papermill-error-cell" style="color:red; font-family:Helvetica Neue, Helvetica, Arial, sans-serif; font-size:2em;">Execution using papermill encountered an exception here and stopped:</span>

In [14]:
for name, url in list(datasets.items())[:]:
    print("doing ", name)
    if not os.path.exists(LOC + "temp/" + name + "_proc.h5ad"):
        adata = sc.read(LOC + name + ".h5ad", backup_url=url)
        preprocessor = Preprocessor(
            force_preprocess=True,
            skip_validate=True,
            # drop_non_primary=False,
            is_symbol=False,
            do_postp=metacell,
        )
        adata = preprocessor(adata)
        if metacell:
            sc.pp.neighbors(adata, use_rep="X_pca")
        adata.write_h5ad(LOC + "temp/" + name + "_proc.h5ad")
    else:
        adata = sc.read(LOC + "temp/" + name + "_proc.h5ad")

    embed = Embedder(
        how="random expr",
        max_len=2300,
        num_workers=8,
        pred_embedding=["cell_type_ontology_term_id"],
        doplot=False,
    )
    n_adata, _ = embed(model, adata)
    metrics[name + "_ref_cls"] = compute_classification(
        n_adata,
        ["cell_type_ontology_term_id"],
        label_decoders=model.label_decoders,
        labels_hierarchy=model.labels_hierarchy,
    )
    n_adata_last = n_adata[n_adata.obs["donor_id"].isin(test[name])]
    metrics[name + "_cls"] = compute_classification(
        n_adata_last,
        ["cell_type_ontology_term_id"],
        label_decoders=model.label_decoders,
        labels_hierarchy=model.labels_hierarchy,
    )
    print(metrics)
    n_adata.obs = n_adata.obs.iloc[:, :100]
    n_adata.obsm["scprint_emb"] = sc.pp.pca(n_adata.obsm["scprint_emb"], chunked=True)
    # bm = Benchmarker(
    #    n_adata,
    #    batch_key="donor_id",  # "batch",  # batch, tech, assay_ontology_term_id, donor_id
    #    label_key="cell_type",  # celltype
    #    embedding_obsm_keys=["scprint_emb"],
    #    bio_conservation_metrics=BioConservation(),
    #    batch_correction_metrics=BatchCorrection(),
    #    n_jobs=10,
    # )
    # del n_adata, adata
    # bm.benchmark()
    # metrics[name + "_batch_corr"] = bm.get_results()
    # bm.plot_results_table(min_max_scale=False)
    # print(metrics[name + "_batch_corr"])

doing  cellxgene_census/dkd

/lustre/fswork/projects/rech/xeg/uat95fg/scdataloader/scdataloader/utils.py:427: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  organismdf = pd.concat(organismdf)

predict epoch start

  0%|          | 0/613 [00:00<?, ?it/s]

  0%|          | 1/613 [00:02<25:32,  2.50s/it]

  0%|          | 2/613 [00:02<11:50,  1.16s/it]

  0%|          | 3/613 [00:02<07:30,  1.35it/s]

  1%|          | 4/613 [00:03<05:26,  1.87it/s]

  1%|          | 5/613 [00:03<04:17,  2.36it/s]

  1%|          | 6/613 [00:03<03:35,  2.81it/s]

  1%|          | 7/613 [00:03<03:08,  3.21it/s]

  1%|▏         | 8/613 [00:04<02:51,  3.53it/s]

  1%|▏         | 9/613 [00:04<02:40,  3.76it/s]

  2%|▏         | 10/613 [00:04<02:32,  3.95it/s]

  2%|▏         | 11/613 [00:04<02:27,  4.09it/s]

  2%|▏         | 12/613 [00:04<02:23,  4.20it/s]

  2%|▏         | 13/613 [00:05<02:20,  4.28it/s]

  2%|▏         | 14/613 [00:05<02:18,  4.33it/s]

  2%|▏         | 15/613 [00:05<02:16,  4.37it/s]

  3%|▎         | 16/613 [00:05<02:15,  4.40it/s]

  3%|▎         | 17/613 [00:06<02:14,  4.43it/s]

  3%|▎         | 18/613 [00:06<02:14,  4.42it/s]

  3%|▎         | 19/613 [00:06<02:14,  4.43it/s]

  3%|▎         | 20/613 [00:06<02:14,  4.42it/s]

  3%|▎         | 21/613 [00:07<02:13,  4.43it/s]

  4%|▎         | 22/613 [00:07<02:13,  4.44it/s]

  4%|▍         | 23/613 [00:07<02:13,  4.43it/s]

  4%|▍         | 24/613 [00:07<02:12,  4.44it/s]

  4%|▍         | 25/613 [00:07<02:12,  4.43it/s]

  4%|▍         | 26/613 [00:08<02:12,  4.43it/s]

  4%|▍         | 27/613 [00:08<02:12,  4.42it/s]

  5%|▍         | 28/613 [00:08<02:12,  4.41it/s]

  5%|▍         | 29/613 [00:08<02:12,  4.40it/s]

  5%|▍         | 30/613 [00:09<02:11,  4.42it/s]

  5%|▌         | 31/613 [00:09<02:11,  4.42it/s]

  5%|▌         | 32/613 [00:09<02:11,  4.42it/s]

  5%|▌         | 33/613 [00:09<02:10,  4.43it/s]

  6%|▌         | 34/613 [00:09<02:10,  4.44it/s]

  6%|▌         | 35/613 [00:10<02:10,  4.43it/s]

  6%|▌         | 36/613 [00:10<02:10,  4.43it/s]

  6%|▌         | 37/613 [00:10<02:10,  4.43it/s]

  6%|▌         | 38/613 [00:10<02:09,  4.42it/s]

  6%|▋         | 39/613 [00:11<02:09,  4.43it/s]

  7%|▋         | 40/613 [00:11<02:09,  4.43it/s]

  7%|▋         | 41/613 [00:11<02:08,  4.44it/s]

  7%|▋         | 42/613 [00:11<02:08,  4.44it/s]

  7%|▋         | 43/613 [00:11<02:08,  4.44it/s]

  7%|▋         | 44/613 [00:12<02:08,  4.42it/s]

  7%|▋         | 45/613 [00:12<02:08,  4.43it/s]

  8%|▊         | 46/613 [00:12<02:08,  4.42it/s]

  8%|▊         | 47/613 [00:12<02:08,  4.42it/s]

  8%|▊         | 48/613 [00:13<02:07,  4.42it/s]

  8%|▊         | 49/613 [00:13<02:07,  4.42it/s]

  8%|▊         | 50/613 [00:13<02:07,  4.43it/s]

  8%|▊         | 51/613 [00:13<02:06,  4.44it/s]

  8%|▊         | 52/613 [00:14<02:06,  4.43it/s]

  9%|▊         | 53/613 [00:14<02:06,  4.43it/s]

  9%|▉         | 54/613 [00:14<02:06,  4.41it/s]

  9%|▉         | 55/613 [00:14<02:06,  4.41it/s]

  9%|▉         | 56/613 [00:14<02:06,  4.42it/s]

  9%|▉         | 57/613 [00:15<02:05,  4.42it/s]

  9%|▉         | 58/613 [00:15<02:05,  4.41it/s]

 10%|▉         | 59/613 [00:15<02:05,  4.42it/s]

 10%|▉         | 60/613 [00:15<02:04,  4.43it/s]

 10%|▉         | 61/613 [00:16<02:04,  4.43it/s]

 10%|█         | 62/613 [00:16<02:04,  4.44it/s]

 10%|█         | 63/613 [00:16<02:03,  4.45it/s]

 10%|█         | 64/613 [00:16<02:03,  4.43it/s]

 11%|█         | 65/613 [00:16<02:03,  4.43it/s]

 11%|█         | 66/613 [00:17<02:03,  4.43it/s]

 11%|█         | 67/613 [00:17<02:03,  4.41it/s]

 11%|█         | 68/613 [00:17<02:03,  4.42it/s]

 11%|█▏        | 69/613 [00:17<02:02,  4.43it/s]

 11%|█▏        | 70/613 [00:18<02:02,  4.43it/s]

 12%|█▏        | 71/613 [00:18<02:02,  4.44it/s]

 12%|█▏        | 72/613 [00:18<02:01,  4.44it/s]

 12%|█▏        | 73/613 [00:18<02:01,  4.43it/s]

 12%|█▏        | 74/613 [00:18<02:01,  4.43it/s]

 12%|█▏        | 75/613 [00:19<02:02,  4.41it/s]

 12%|█▏        | 76/613 [00:19<02:01,  4.41it/s]

 13%|█▎        | 77/613 [00:19<02:01,  4.41it/s]

 13%|█▎        | 78/613 [00:19<02:01,  4.41it/s]

 13%|█▎        | 79/613 [00:20<02:00,  4.41it/s]

 13%|█▎        | 80/613 [00:20<02:00,  4.41it/s]

 13%|█▎        | 81/613 [00:20<02:00,  4.41it/s]

 13%|█▎        | 82/613 [00:20<02:00,  4.41it/s]

 14%|█▎        | 83/613 [00:21<02:00,  4.41it/s]

 14%|█▎        | 84/613 [00:21<02:00,  4.41it/s]

 14%|█▍        | 85/613 [00:21<01:59,  4.43it/s]

 14%|█▍        | 86/613 [00:21<01:59,  4.43it/s]

 14%|█▍        | 87/613 [00:21<01:58,  4.42it/s]

 14%|█▍        | 88/613 [00:22<01:58,  4.42it/s]

 15%|█▍        | 89/613 [00:22<01:58,  4.42it/s]

 15%|█▍        | 90/613 [00:22<01:58,  4.42it/s]

 15%|█▍        | 91/613 [00:22<01:58,  4.42it/s]

 15%|█▌        | 92/613 [00:23<01:57,  4.42it/s]

 15%|█▌        | 93/613 [00:23<01:57,  4.41it/s]

 15%|█▌        | 94/613 [00:23<01:57,  4.41it/s]

 15%|█▌        | 95/613 [00:23<01:57,  4.42it/s]

 16%|█▌        | 96/613 [00:23<01:57,  4.42it/s]

 16%|█▌        | 97/613 [00:24<01:56,  4.42it/s]

 16%|█▌        | 98/613 [00:24<01:56,  4.41it/s]

 16%|█▌        | 99/613 [00:24<01:56,  4.43it/s]

 16%|█▋        | 100/613 [00:24<01:55,  4.43it/s]

 16%|█▋        | 101/613 [00:25<01:55,  4.42it/s]

 17%|█▋        | 102/613 [00:25<01:55,  4.43it/s]

 17%|█▋        | 103/613 [00:25<01:55,  4.42it/s]

 17%|█▋        | 104/613 [00:25<01:55,  4.42it/s]

 17%|█▋        | 105/613 [00:25<01:55,  4.42it/s]

 17%|█▋        | 106/613 [00:26<01:54,  4.42it/s]

 17%|█▋        | 107/613 [00:26<01:54,  4.40it/s]

 18%|█▊        | 108/613 [00:26<01:54,  4.41it/s]

 18%|█▊        | 109/613 [00:26<01:54,  4.41it/s]

 18%|█▊        | 110/613 [00:27<01:53,  4.41it/s]

 18%|█▊        | 111/613 [00:27<01:53,  4.42it/s]

 18%|█▊        | 112/613 [00:27<01:53,  4.40it/s]

 18%|█▊        | 113/613 [00:27<01:53,  4.41it/s]

 19%|█▊        | 114/613 [00:28<01:53,  4.40it/s]

 19%|█▉        | 115/613 [00:28<01:53,  4.40it/s]

 19%|█▉        | 116/613 [00:28<01:52,  4.40it/s]

 19%|█▉        | 117/613 [00:28<01:52,  4.41it/s]

 19%|█▉        | 118/613 [00:28<01:52,  4.41it/s]

 19%|█▉        | 119/613 [00:29<01:52,  4.41it/s]

 20%|█▉        | 120/613 [00:29<01:52,  4.40it/s]

 20%|█▉        | 121/613 [00:29<01:51,  4.41it/s]

 20%|█▉        | 122/613 [00:29<01:51,  4.41it/s]

 20%|██        | 123/613 [00:30<01:51,  4.41it/s]

 20%|██        | 124/613 [00:30<01:51,  4.40it/s]

 20%|██        | 125/613 [00:30<01:50,  4.40it/s]

 21%|██        | 126/613 [00:30<01:50,  4.40it/s]

 21%|██        | 127/613 [00:30<01:50,  4.41it/s]

 21%|██        | 128/613 [00:31<01:49,  4.42it/s]

 21%|██        | 129/613 [00:31<01:49,  4.42it/s]

 21%|██        | 130/613 [00:31<01:49,  4.41it/s]

 21%|██▏       | 131/613 [00:31<01:49,  4.41it/s]

 22%|██▏       | 132/613 [00:32<01:49,  4.40it/s]

 22%|██▏       | 133/613 [00:32<01:48,  4.41it/s]

 22%|██▏       | 134/613 [00:32<01:48,  4.41it/s]

 22%|██▏       | 135/613 [00:32<01:48,  4.40it/s]

 22%|██▏       | 136/613 [00:33<01:48,  4.40it/s]

 22%|██▏       | 137/613 [00:33<01:48,  4.40it/s]

 23%|██▎       | 138/613 [00:33<01:48,  4.40it/s]

 23%|██▎       | 139/613 [00:33<01:47,  4.40it/s]

 23%|██▎       | 140/613 [00:33<01:47,  4.40it/s]

 23%|██▎       | 141/613 [00:34<01:47,  4.40it/s]

 23%|██▎       | 142/613 [00:34<01:46,  4.41it/s]

 23%|██▎       | 143/613 [00:34<01:46,  4.41it/s]

 23%|██▎       | 144/613 [00:34<01:46,  4.40it/s]

 24%|██▎       | 145/613 [00:35<01:46,  4.40it/s]

 24%|██▍       | 146/613 [00:35<01:46,  4.39it/s]

 24%|██▍       | 147/613 [00:35<01:46,  4.39it/s]

 24%|██▍       | 148/613 [00:35<01:45,  4.40it/s]

 24%|██▍       | 149/613 [00:35<01:45,  4.40it/s]

 24%|██▍       | 150/613 [00:36<01:46,  4.37it/s]

 25%|██▍       | 151/613 [00:36<01:45,  4.38it/s]

 25%|██▍       | 152/613 [00:36<01:45,  4.38it/s]

 25%|██▍       | 153/613 [00:36<01:44,  4.39it/s]

 25%|██▌       | 154/613 [00:37<01:44,  4.40it/s]

 25%|██▌       | 155/613 [00:37<01:44,  4.40it/s]

 25%|██▌       | 156/613 [00:37<01:43,  4.41it/s]

 26%|██▌       | 157/613 [00:37<01:43,  4.41it/s]

 26%|██▌       | 158/613 [00:38<01:43,  4.41it/s]

 26%|██▌       | 159/613 [00:38<01:43,  4.40it/s]

 26%|██▌       | 160/613 [00:38<01:43,  4.40it/s]

 26%|██▋       | 161/613 [00:38<01:42,  4.40it/s]

 26%|██▋       | 162/613 [00:38<01:42,  4.41it/s]

 27%|██▋       | 163/613 [00:39<01:42,  4.40it/s]

 27%|██▋       | 164/613 [00:39<01:42,  4.39it/s]

 27%|██▋       | 165/613 [00:39<01:41,  4.39it/s]

 27%|██▋       | 166/613 [00:39<01:41,  4.40it/s]

 27%|██▋       | 167/613 [00:40<01:41,  4.40it/s]

 27%|██▋       | 168/613 [00:40<01:41,  4.39it/s]

 28%|██▊       | 169/613 [00:40<01:41,  4.40it/s]

 28%|██▊       | 170/613 [00:40<01:40,  4.39it/s]

 28%|██▊       | 171/613 [00:40<01:40,  4.39it/s]

 28%|██▊       | 172/613 [00:41<01:40,  4.38it/s]

 28%|██▊       | 173/613 [00:41<01:40,  4.39it/s]

 28%|██▊       | 174/613 [00:41<01:39,  4.40it/s]

 29%|██▊       | 175/613 [00:41<01:39,  4.39it/s]

 29%|██▊       | 176/613 [00:42<01:39,  4.39it/s]

 29%|██▉       | 177/613 [00:42<01:39,  4.40it/s]

 29%|██▉       | 178/613 [00:42<01:38,  4.39it/s]

 29%|██▉       | 179/613 [00:42<01:38,  4.40it/s]

 29%|██▉       | 180/613 [00:43<01:38,  4.39it/s]

 30%|██▉       | 181/613 [00:43<01:38,  4.39it/s]

 30%|██▉       | 182/613 [00:43<01:38,  4.39it/s]

 30%|██▉       | 183/613 [00:43<01:38,  4.38it/s]

 30%|███       | 184/613 [00:43<01:38,  4.37it/s]

 30%|███       | 185/613 [00:44<01:37,  4.38it/s]

 30%|███       | 186/613 [00:44<01:37,  4.38it/s]

 31%|███       | 187/613 [00:44<01:37,  4.38it/s]

 31%|███       | 188/613 [00:44<01:36,  4.38it/s]

 31%|███       | 189/613 [00:45<01:36,  4.38it/s]

 31%|███       | 190/613 [00:45<01:36,  4.38it/s]

 31%|███       | 191/613 [00:45<01:36,  4.39it/s]

 31%|███▏      | 192/613 [00:45<01:35,  4.39it/s]

 31%|███▏      | 193/613 [00:46<01:35,  4.38it/s]

 32%|███▏      | 194/613 [00:46<01:35,  4.39it/s]

 32%|███▏      | 195/613 [00:46<01:35,  4.39it/s]

 32%|███▏      | 196/613 [00:46<01:35,  4.39it/s]

 32%|███▏      | 197/613 [00:46<01:34,  4.39it/s]

 32%|███▏      | 198/613 [00:47<01:34,  4.39it/s]

 32%|███▏      | 199/613 [00:47<01:34,  4.39it/s]

 33%|███▎      | 200/613 [00:47<01:33,  4.40it/s]

 33%|███▎      | 201/613 [00:47<01:33,  4.39it/s]

 33%|███▎      | 202/613 [00:48<01:33,  4.39it/s]

 33%|███▎      | 203/613 [00:48<01:33,  4.39it/s]

 33%|███▎      | 204/613 [00:48<01:33,  4.38it/s]

 33%|███▎      | 205/613 [00:48<01:33,  4.36it/s]

 34%|███▎      | 206/613 [00:48<01:33,  4.37it/s]

 34%|███▍      | 207/613 [00:49<01:33,  4.36it/s]

 34%|███▍      | 208/613 [00:49<01:32,  4.38it/s]

 34%|███▍      | 209/613 [00:49<01:32,  4.38it/s]

 34%|███▍      | 210/613 [00:49<01:31,  4.38it/s]

 34%|███▍      | 211/613 [00:50<01:31,  4.38it/s]

 35%|███▍      | 212/613 [00:50<01:31,  4.38it/s]

 35%|███▍      | 213/613 [00:50<01:31,  4.39it/s]

 35%|███▍      | 214/613 [00:50<01:30,  4.39it/s]

 35%|███▌      | 215/613 [00:51<01:30,  4.38it/s]

 35%|███▌      | 216/613 [00:51<01:30,  4.38it/s]

 35%|███▌      | 217/613 [00:51<01:30,  4.38it/s]

 36%|███▌      | 218/613 [00:51<01:30,  4.39it/s]

 36%|███▌      | 219/613 [00:51<01:29,  4.38it/s]

 36%|███▌      | 220/613 [00:52<01:29,  4.39it/s]

 36%|███▌      | 221/613 [00:52<01:29,  4.37it/s]

 36%|███▌      | 222/613 [00:52<01:29,  4.38it/s]

 36%|███▋      | 223/613 [00:52<01:29,  4.38it/s]

 37%|███▋      | 224/613 [00:53<01:28,  4.38it/s]

 37%|███▋      | 225/613 [00:53<01:28,  4.38it/s]

 37%|███▋      | 226/613 [00:53<01:28,  4.37it/s]

 37%|███▋      | 227/613 [00:53<01:28,  4.38it/s]

 37%|███▋      | 228/613 [00:53<01:27,  4.38it/s]

 37%|███▋      | 229/613 [00:54<01:27,  4.39it/s]

 38%|███▊      | 230/613 [00:54<01:27,  4.38it/s]

 38%|███▊      | 231/613 [00:54<01:27,  4.38it/s]

 38%|███▊      | 232/613 [00:54<01:26,  4.38it/s]

 38%|███▊      | 233/613 [00:55<01:26,  4.39it/s]

 38%|███▊      | 234/613 [00:55<01:26,  4.39it/s]

 38%|███▊      | 235/613 [00:55<01:26,  4.39it/s]

 38%|███▊      | 236/613 [00:55<01:25,  4.40it/s]

 39%|███▊      | 237/613 [00:56<01:25,  4.40it/s]

 39%|███▉      | 238/613 [00:56<01:25,  4.39it/s]

 39%|███▉      | 239/613 [00:56<01:25,  4.40it/s]

 39%|███▉      | 240/613 [00:56<01:24,  4.40it/s]

 39%|███▉      | 241/613 [00:56<01:24,  4.40it/s]

 39%|███▉      | 242/613 [00:57<01:24,  4.38it/s]

 40%|███▉      | 243/613 [00:57<01:24,  4.39it/s]

 40%|███▉      | 244/613 [00:57<01:24,  4.39it/s]

 40%|███▉      | 245/613 [00:57<01:23,  4.39it/s]

 40%|████      | 246/613 [00:58<01:23,  4.39it/s]

 40%|████      | 247/613 [00:58<01:23,  4.39it/s]

 40%|████      | 248/613 [00:58<01:23,  4.38it/s]

 41%|████      | 249/613 [00:58<01:23,  4.37it/s]

 41%|████      | 250/613 [00:59<01:22,  4.39it/s]

 41%|████      | 251/613 [00:59<01:22,  4.38it/s]

 41%|████      | 252/613 [00:59<01:22,  4.39it/s]

 41%|████▏     | 253/613 [00:59<01:21,  4.39it/s]

 41%|████▏     | 254/613 [00:59<01:21,  4.39it/s]

 42%|████▏     | 255/613 [01:00<01:21,  4.38it/s]

 42%|████▏     | 256/613 [01:00<01:21,  4.38it/s]

 42%|████▏     | 257/613 [01:00<01:21,  4.38it/s]

 42%|████▏     | 258/613 [01:00<01:20,  4.39it/s]

 42%|████▏     | 259/613 [01:01<01:20,  4.39it/s]

 42%|████▏     | 260/613 [01:01<01:20,  4.39it/s]

 43%|████▎     | 261/613 [01:01<01:19,  4.40it/s]

 43%|████▎     | 262/613 [01:01<01:19,  4.41it/s]

 43%|████▎     | 263/613 [01:01<01:19,  4.40it/s]

 43%|████▎     | 264/613 [01:02<01:19,  4.40it/s]

 43%|████▎     | 265/613 [01:02<01:19,  4.39it/s]

 43%|████▎     | 266/613 [01:02<01:18,  4.40it/s]

 44%|████▎     | 267/613 [01:02<01:18,  4.39it/s]

 44%|████▎     | 268/613 [01:03<01:18,  4.40it/s]

 44%|████▍     | 269/613 [01:03<01:18,  4.39it/s]

 44%|████▍     | 270/613 [01:03<01:18,  4.38it/s]

 44%|████▍     | 271/613 [01:03<01:18,  4.38it/s]

 44%|████▍     | 272/613 [01:04<01:17,  4.39it/s]

 45%|████▍     | 273/613 [01:04<01:17,  4.39it/s]

 45%|████▍     | 274/613 [01:04<01:17,  4.38it/s]

 45%|████▍     | 275/613 [01:04<01:16,  4.39it/s]

 45%|████▌     | 276/613 [01:04<01:16,  4.39it/s]

 45%|████▌     | 277/613 [01:05<01:16,  4.39it/s]

 45%|████▌     | 278/613 [01:05<01:16,  4.40it/s]

 46%|████▌     | 279/613 [01:05<01:15,  4.40it/s]

 46%|████▌     | 280/613 [01:05<01:15,  4.40it/s]

 46%|████▌     | 281/613 [01:06<01:15,  4.39it/s]

 46%|████▌     | 282/613 [01:06<01:15,  4.39it/s]

 46%|████▌     | 283/613 [01:06<01:15,  4.39it/s]

 46%|████▋     | 284/613 [01:06<01:14,  4.39it/s]

 46%|████▋     | 285/613 [01:06<01:14,  4.39it/s]

 47%|████▋     | 286/613 [01:07<01:14,  4.39it/s]

 47%|████▋     | 287/613 [01:07<01:14,  4.38it/s]

 47%|████▋     | 288/613 [01:07<01:14,  4.38it/s]

 47%|████▋     | 289/613 [01:07<01:13,  4.38it/s]

 47%|████▋     | 290/613 [01:08<01:13,  4.37it/s]

 47%|████▋     | 291/613 [01:08<01:15,  4.28it/s]

 48%|████▊     | 292/613 [01:08<01:14,  4.32it/s]

 48%|████▊     | 293/613 [01:08<01:13,  4.33it/s]

 48%|████▊     | 294/613 [01:09<01:13,  4.35it/s]

 48%|████▊     | 295/613 [01:09<01:13,  4.35it/s]

 48%|████▊     | 296/613 [01:09<01:12,  4.34it/s]

 48%|████▊     | 297/613 [01:09<01:12,  4.36it/s]

 49%|████▊     | 298/613 [01:09<01:12,  4.36it/s]

 49%|████▉     | 299/613 [01:10<01:11,  4.36it/s]

 49%|████▉     | 300/613 [01:10<01:11,  4.37it/s]

 49%|████▉     | 301/613 [01:10<01:11,  4.37it/s]

 49%|████▉     | 302/613 [01:10<01:11,  4.36it/s]

 49%|████▉     | 303/613 [01:11<01:11,  4.36it/s]

 50%|████▉     | 304/613 [01:11<01:10,  4.36it/s]

 50%|████▉     | 305/613 [01:11<01:10,  4.37it/s]

 50%|████▉     | 306/613 [01:11<01:10,  4.38it/s]

 50%|█████     | 307/613 [01:12<01:09,  4.37it/s]

 50%|█████     | 308/613 [01:12<01:09,  4.39it/s]

 50%|█████     | 309/613 [01:12<01:09,  4.39it/s]

 51%|█████     | 310/613 [01:12<01:09,  4.39it/s]

 51%|█████     | 311/613 [01:12<01:08,  4.40it/s]

 51%|█████     | 312/613 [01:13<01:08,  4.40it/s]

 51%|█████     | 313/613 [01:13<01:08,  4.38it/s]

 51%|█████     | 314/613 [01:13<01:08,  4.38it/s]

 51%|█████▏    | 315/613 [01:13<01:08,  4.38it/s]

 52%|█████▏    | 316/613 [01:14<01:07,  4.39it/s]

 52%|█████▏    | 317/613 [01:14<01:07,  4.39it/s]

 52%|█████▏    | 318/613 [01:14<01:07,  4.39it/s]

 52%|█████▏    | 319/613 [01:14<01:06,  4.39it/s]

 52%|█████▏    | 320/613 [01:14<01:06,  4.39it/s]

 52%|█████▏    | 321/613 [01:15<01:06,  4.39it/s]

 53%|█████▎    | 322/613 [01:15<01:06,  4.40it/s]

 53%|█████▎    | 323/613 [01:15<01:06,  4.39it/s]

 53%|█████▎    | 324/613 [01:15<01:05,  4.39it/s]

 53%|█████▎    | 325/613 [01:16<01:05,  4.39it/s]

 53%|█████▎    | 326/613 [01:16<01:05,  4.37it/s]

 53%|█████▎    | 327/613 [01:16<01:05,  4.38it/s]

 54%|█████▎    | 328/613 [01:16<01:05,  4.37it/s]

 54%|█████▎    | 329/613 [01:17<01:04,  4.38it/s]

 54%|█████▍    | 330/613 [01:17<01:04,  4.38it/s]

 54%|█████▍    | 331/613 [01:17<01:04,  4.38it/s]

 54%|█████▍    | 332/613 [01:17<01:04,  4.38it/s]

 54%|█████▍    | 333/613 [01:17<01:03,  4.38it/s]

 54%|█████▍    | 334/613 [01:18<01:03,  4.37it/s]

 55%|█████▍    | 335/613 [01:18<01:03,  4.37it/s]

 55%|█████▍    | 336/613 [01:18<01:03,  4.38it/s]

 55%|█████▍    | 337/613 [01:18<01:03,  4.37it/s]

 55%|█████▌    | 338/613 [01:19<01:02,  4.37it/s]

 55%|█████▌    | 339/613 [01:19<01:02,  4.37it/s]

 55%|█████▌    | 340/613 [01:19<01:02,  4.37it/s]

 56%|█████▌    | 341/613 [01:19<01:02,  4.38it/s]

 56%|█████▌    | 342/613 [01:20<01:01,  4.38it/s]

 56%|█████▌    | 343/613 [01:20<01:01,  4.38it/s]

 56%|█████▌    | 344/613 [01:20<01:01,  4.37it/s]

 56%|█████▋    | 345/613 [01:20<01:01,  4.37it/s]

 56%|█████▋    | 346/613 [01:20<01:01,  4.37it/s]

 57%|█████▋    | 347/613 [01:21<01:00,  4.38it/s]

 57%|█████▋    | 348/613 [01:21<01:00,  4.39it/s]

 57%|█████▋    | 349/613 [01:21<01:00,  4.37it/s]

 57%|█████▋    | 350/613 [01:21<01:00,  4.37it/s]

 57%|█████▋    | 351/613 [01:22<00:59,  4.37it/s]

 57%|█████▋    | 352/613 [01:22<00:59,  4.37it/s]

 58%|█████▊    | 353/613 [01:22<00:59,  4.36it/s]

 58%|█████▊    | 354/613 [01:22<00:59,  4.36it/s]

 58%|█████▊    | 355/613 [01:22<00:59,  4.37it/s]

 58%|█████▊    | 356/613 [01:23<00:58,  4.37it/s]

 58%|█████▊    | 357/613 [01:23<00:58,  4.37it/s]

 58%|█████▊    | 358/613 [01:23<00:58,  4.38it/s]

 59%|█████▊    | 359/613 [01:23<00:58,  4.37it/s]

 59%|█████▊    | 360/613 [01:24<00:57,  4.36it/s]

 59%|█████▉    | 361/613 [01:24<00:57,  4.37it/s]

 59%|█████▉    | 362/613 [01:24<00:57,  4.37it/s]

 59%|█████▉    | 363/613 [01:24<00:57,  4.37it/s]

 59%|█████▉    | 364/613 [01:25<00:56,  4.37it/s]

 60%|█████▉    | 365/613 [01:25<00:56,  4.37it/s]

 60%|█████▉    | 366/613 [01:25<00:56,  4.38it/s]

 60%|█████▉    | 367/613 [01:25<00:56,  4.37it/s]

 60%|██████    | 368/613 [01:25<00:56,  4.37it/s]

 60%|██████    | 369/613 [01:26<00:55,  4.37it/s]

 60%|██████    | 370/613 [01:26<00:55,  4.38it/s]

 61%|██████    | 371/613 [01:26<00:55,  4.38it/s]

 61%|██████    | 372/613 [01:26<00:55,  4.37it/s]

 61%|██████    | 373/613 [01:27<00:54,  4.37it/s]

 61%|██████    | 374/613 [01:27<00:54,  4.37it/s]

 61%|██████    | 375/613 [01:27<00:54,  4.37it/s]

 61%|██████▏   | 376/613 [01:27<00:54,  4.37it/s]

 62%|██████▏   | 377/613 [01:28<00:53,  4.38it/s]

 62%|██████▏   | 378/613 [01:28<00:53,  4.37it/s]

 62%|██████▏   | 379/613 [01:28<00:53,  4.37it/s]

 62%|██████▏   | 380/613 [01:28<00:53,  4.37it/s]

 62%|██████▏   | 381/613 [01:28<00:53,  4.37it/s]

 62%|██████▏   | 382/613 [01:29<00:53,  4.35it/s]

 62%|██████▏   | 383/613 [01:29<00:52,  4.37it/s]

 63%|██████▎   | 384/613 [01:29<00:52,  4.37it/s]

 63%|██████▎   | 385/613 [01:29<00:52,  4.36it/s]

 63%|██████▎   | 386/613 [01:30<00:52,  4.36it/s]

 63%|██████▎   | 387/613 [01:30<00:51,  4.35it/s]

 63%|██████▎   | 388/613 [01:30<00:51,  4.36it/s]

 63%|██████▎   | 389/613 [01:30<00:51,  4.37it/s]

 64%|██████▎   | 390/613 [01:30<00:51,  4.36it/s]

 64%|██████▍   | 391/613 [01:31<00:50,  4.36it/s]

 64%|██████▍   | 392/613 [01:31<00:50,  4.36it/s]

 64%|██████▍   | 393/613 [01:31<00:50,  4.37it/s]

 64%|██████▍   | 394/613 [01:31<00:50,  4.38it/s]

 64%|██████▍   | 395/613 [01:32<00:49,  4.38it/s]

 65%|██████▍   | 396/613 [01:32<00:49,  4.38it/s]

 65%|██████▍   | 397/613 [01:32<00:49,  4.36it/s]

 65%|██████▍   | 398/613 [01:32<00:49,  4.36it/s]

 65%|██████▌   | 399/613 [01:33<00:48,  4.37it/s]

 65%|██████▌   | 400/613 [01:33<00:48,  4.38it/s]

 65%|██████▌   | 401/613 [01:33<00:48,  4.38it/s]

 66%|██████▌   | 402/613 [01:33<00:48,  4.37it/s]

 66%|██████▌   | 403/613 [01:33<00:48,  4.36it/s]

 66%|██████▌   | 404/613 [01:34<00:47,  4.35it/s]

 66%|██████▌   | 405/613 [01:34<00:47,  4.35it/s]

 66%|██████▌   | 406/613 [01:34<00:47,  4.34it/s]

 66%|██████▋   | 407/613 [01:34<00:47,  4.35it/s]

 67%|██████▋   | 408/613 [01:35<00:47,  4.33it/s]

 67%|██████▋   | 409/613 [01:35<00:46,  4.34it/s]

 67%|██████▋   | 410/613 [01:35<00:46,  4.34it/s]

 67%|██████▋   | 411/613 [01:35<00:46,  4.33it/s]

 67%|██████▋   | 412/613 [01:36<00:46,  4.34it/s]

 67%|██████▋   | 413/613 [01:36<00:46,  4.35it/s]

 68%|██████▊   | 414/613 [01:36<00:45,  4.35it/s]

 68%|██████▊   | 415/613 [01:36<00:45,  4.35it/s]

 68%|██████▊   | 416/613 [01:36<00:45,  4.35it/s]

 68%|██████▊   | 417/613 [01:37<00:45,  4.34it/s]

 68%|██████▊   | 418/613 [01:37<00:44,  4.35it/s]

 68%|██████▊   | 419/613 [01:37<00:44,  4.34it/s]

 69%|██████▊   | 420/613 [01:37<00:44,  4.34it/s]

 69%|██████▊   | 421/613 [01:38<00:44,  4.34it/s]

 69%|██████▉   | 422/613 [01:38<00:44,  4.33it/s]

 69%|██████▉   | 423/613 [01:38<00:43,  4.35it/s]

 69%|██████▉   | 424/613 [01:38<00:43,  4.35it/s]

 69%|██████▉   | 425/613 [01:39<00:43,  4.34it/s]

 69%|██████▉   | 426/613 [01:39<00:42,  4.35it/s]

 70%|██████▉   | 427/613 [01:39<00:42,  4.35it/s]

 70%|██████▉   | 428/613 [01:39<00:43,  4.29it/s]

 70%|██████▉   | 429/613 [01:39<00:42,  4.30it/s]

 70%|███████   | 430/613 [01:40<00:42,  4.31it/s]

 70%|███████   | 431/613 [01:40<00:42,  4.33it/s]

 70%|███████   | 432/613 [01:40<00:41,  4.34it/s]

 71%|███████   | 433/613 [01:40<00:41,  4.35it/s]

 71%|███████   | 434/613 [01:41<00:41,  4.34it/s]

 71%|███████   | 435/613 [01:41<00:41,  4.34it/s]

 71%|███████   | 436/613 [01:41<00:40,  4.32it/s]

 71%|███████▏  | 437/613 [01:41<00:40,  4.34it/s]

 71%|███████▏  | 438/613 [01:42<00:40,  4.34it/s]

 72%|███████▏  | 439/613 [01:42<00:40,  4.35it/s]

 72%|███████▏  | 440/613 [01:42<00:39,  4.35it/s]

 72%|███████▏  | 441/613 [01:42<00:39,  4.35it/s]

 72%|███████▏  | 442/613 [01:42<00:39,  4.36it/s]

 72%|███████▏  | 443/613 [01:43<00:39,  4.36it/s]

 72%|███████▏  | 444/613 [01:43<00:38,  4.36it/s]

 73%|███████▎  | 445/613 [01:43<00:38,  4.36it/s]

 73%|███████▎  | 446/613 [01:43<00:38,  4.36it/s]

 73%|███████▎  | 447/613 [01:44<00:38,  4.36it/s]

 73%|███████▎  | 448/613 [01:44<00:37,  4.35it/s]

 73%|███████▎  | 449/613 [01:44<00:37,  4.34it/s]

 73%|███████▎  | 450/613 [01:44<00:37,  4.34it/s]

 74%|███████▎  | 451/613 [01:45<00:37,  4.35it/s]

 74%|███████▎  | 452/613 [01:45<00:37,  4.34it/s]

 74%|███████▍  | 453/613 [01:45<00:36,  4.35it/s]

 74%|███████▍  | 454/613 [01:45<00:36,  4.34it/s]

 74%|███████▍  | 455/613 [01:45<00:36,  4.35it/s]

 74%|███████▍  | 456/613 [01:46<00:36,  4.35it/s]

 75%|███████▍  | 457/613 [01:46<00:35,  4.35it/s]

 75%|███████▍  | 458/613 [01:46<00:35,  4.35it/s]

 75%|███████▍  | 459/613 [01:46<00:35,  4.35it/s]

 75%|███████▌  | 460/613 [01:47<00:35,  4.34it/s]

 75%|███████▌  | 461/613 [01:47<00:34,  4.36it/s]

 75%|███████▌  | 462/613 [01:47<00:34,  4.35it/s]

 76%|███████▌  | 463/613 [01:47<00:34,  4.34it/s]

 76%|███████▌  | 464/613 [01:48<00:34,  4.35it/s]

 76%|███████▌  | 465/613 [01:48<00:34,  4.34it/s]

 76%|███████▌  | 466/613 [01:48<00:33,  4.34it/s]

 76%|███████▌  | 467/613 [01:48<00:33,  4.33it/s]

 76%|███████▋  | 468/613 [01:48<00:33,  4.32it/s]

 77%|███████▋  | 469/613 [01:49<00:33,  4.32it/s]

 77%|███████▋  | 470/613 [01:49<00:33,  4.32it/s]

 77%|███████▋  | 471/613 [01:49<00:32,  4.31it/s]

 77%|███████▋  | 472/613 [01:49<00:32,  4.32it/s]

 77%|███████▋  | 473/613 [01:50<00:32,  4.32it/s]

 77%|███████▋  | 474/613 [01:50<00:32,  4.32it/s]

 77%|███████▋  | 475/613 [01:50<00:31,  4.32it/s]

 78%|███████▊  | 476/613 [01:50<00:31,  4.32it/s]

 78%|███████▊  | 477/613 [01:51<00:31,  4.32it/s]

 78%|███████▊  | 478/613 [01:51<00:31,  4.32it/s]

 78%|███████▊  | 479/613 [01:51<00:31,  4.32it/s]

 78%|███████▊  | 480/613 [01:51<00:30,  4.31it/s]

 78%|███████▊  | 481/613 [01:51<00:30,  4.31it/s]

 79%|███████▊  | 482/613 [01:52<00:30,  4.31it/s]

 79%|███████▉  | 483/613 [01:52<00:30,  4.32it/s]

 79%|███████▉  | 484/613 [01:52<00:29,  4.31it/s]

 79%|███████▉  | 485/613 [01:52<00:29,  4.31it/s]

 79%|███████▉  | 486/613 [01:53<00:29,  4.31it/s]

 79%|███████▉  | 487/613 [01:53<00:29,  4.31it/s]

 80%|███████▉  | 488/613 [01:53<00:29,  4.30it/s]

 80%|███████▉  | 489/613 [01:53<00:28,  4.31it/s]

 80%|███████▉  | 490/613 [01:54<00:28,  4.32it/s]

 80%|████████  | 491/613 [01:54<00:28,  4.31it/s]

 80%|████████  | 492/613 [01:54<00:27,  4.32it/s]

 80%|████████  | 493/613 [01:54<00:27,  4.32it/s]

 81%|████████  | 494/613 [01:54<00:27,  4.31it/s]

 81%|████████  | 495/613 [01:55<00:27,  4.32it/s]

 81%|████████  | 496/613 [01:55<00:27,  4.33it/s]

 81%|████████  | 497/613 [01:55<00:26,  4.32it/s]

 81%|████████  | 498/613 [01:55<00:26,  4.32it/s]

 81%|████████▏ | 499/613 [01:56<00:26,  4.31it/s]

 82%|████████▏ | 500/613 [01:56<00:26,  4.32it/s]

 82%|████████▏ | 501/613 [01:56<00:25,  4.31it/s]

 82%|████████▏ | 502/613 [01:56<00:25,  4.32it/s]

 82%|████████▏ | 503/613 [01:57<00:25,  4.30it/s]

 82%|████████▏ | 504/613 [01:57<00:25,  4.30it/s]

 82%|████████▏ | 505/613 [01:57<00:25,  4.31it/s]

 83%|████████▎ | 506/613 [01:57<00:24,  4.32it/s]

 83%|████████▎ | 507/613 [01:57<00:24,  4.31it/s]

 83%|████████▎ | 508/613 [01:58<00:24,  4.32it/s]

 83%|████████▎ | 509/613 [01:58<00:24,  4.32it/s]

 83%|████████▎ | 510/613 [01:58<00:23,  4.33it/s]

 83%|████████▎ | 511/613 [01:58<00:23,  4.33it/s]

 84%|████████▎ | 512/613 [01:59<00:23,  4.31it/s]

 84%|████████▎ | 513/613 [01:59<00:23,  4.32it/s]

 84%|████████▍ | 514/613 [01:59<00:22,  4.33it/s]

 84%|████████▍ | 515/613 [01:59<00:22,  4.34it/s]

 84%|████████▍ | 516/613 [02:00<00:22,  4.34it/s]

 84%|████████▍ | 517/613 [02:00<00:22,  4.33it/s]

 85%|████████▍ | 518/613 [02:00<00:21,  4.33it/s]

 85%|████████▍ | 519/613 [02:00<00:21,  4.33it/s]

 85%|████████▍ | 520/613 [02:00<00:21,  4.33it/s]

 85%|████████▍ | 521/613 [02:01<00:21,  4.32it/s]

 85%|████████▌ | 522/613 [02:01<00:21,  4.31it/s]

 85%|████████▌ | 523/613 [02:01<00:20,  4.30it/s]

 85%|████████▌ | 524/613 [02:01<00:20,  4.30it/s]

 86%|████████▌ | 525/613 [02:02<00:20,  4.30it/s]

 86%|████████▌ | 526/613 [02:02<00:20,  4.31it/s]

 86%|████████▌ | 527/613 [02:02<00:19,  4.31it/s]

 86%|████████▌ | 528/613 [02:02<00:19,  4.30it/s]

 86%|████████▋ | 529/613 [02:03<00:19,  4.29it/s]

 86%|████████▋ | 530/613 [02:03<00:19,  4.28it/s]

 87%|████████▋ | 531/613 [02:03<00:19,  4.29it/s]

 87%|████████▋ | 532/613 [02:03<00:18,  4.28it/s]

 87%|████████▋ | 533/613 [02:04<00:18,  4.29it/s]

 87%|████████▋ | 534/613 [02:04<00:18,  4.29it/s]

 87%|████████▋ | 535/613 [02:04<00:18,  4.29it/s]

 87%|████████▋ | 536/613 [02:04<00:17,  4.29it/s]

 88%|████████▊ | 537/613 [02:04<00:17,  4.29it/s]

 88%|████████▊ | 538/613 [02:05<00:17,  4.28it/s]

 88%|████████▊ | 539/613 [02:05<00:17,  4.29it/s]

 88%|████████▊ | 540/613 [02:05<00:16,  4.29it/s]

 88%|████████▊ | 541/613 [02:05<00:16,  4.30it/s]

 88%|████████▊ | 542/613 [02:06<00:16,  4.30it/s]

 89%|████████▊ | 543/613 [02:06<00:16,  4.28it/s]

 89%|████████▊ | 544/613 [02:06<00:16,  4.30it/s]

 89%|████████▉ | 545/613 [02:06<00:15,  4.30it/s]

 89%|████████▉ | 546/613 [02:07<00:15,  4.29it/s]

 89%|████████▉ | 547/613 [02:07<00:15,  4.28it/s]

 89%|████████▉ | 548/613 [02:07<00:15,  4.28it/s]

 90%|████████▉ | 549/613 [02:07<00:14,  4.29it/s]

 90%|████████▉ | 550/613 [02:07<00:14,  4.28it/s]

 90%|████████▉ | 551/613 [02:08<00:14,  4.29it/s]

 90%|█████████ | 552/613 [02:08<00:14,  4.29it/s]

 90%|█████████ | 553/613 [02:08<00:13,  4.29it/s]

 90%|█████████ | 554/613 [02:08<00:13,  4.30it/s]

 91%|█████████ | 555/613 [02:09<00:13,  4.30it/s]

 91%|█████████ | 556/613 [02:09<00:13,  4.24it/s]

 91%|█████████ | 557/613 [02:09<00:13,  4.25it/s]

 91%|█████████ | 558/613 [02:09<00:12,  4.27it/s]

 91%|█████████ | 559/613 [02:10<00:12,  4.28it/s]

 91%|█████████▏| 560/613 [02:10<00:12,  4.28it/s]

 92%|█████████▏| 561/613 [02:10<00:12,  4.28it/s]

 92%|█████████▏| 562/613 [02:10<00:11,  4.30it/s]

 92%|█████████▏| 563/613 [02:11<00:11,  4.28it/s]

 92%|█████████▏| 564/613 [02:11<00:11,  4.29it/s]

 92%|█████████▏| 565/613 [02:11<00:11,  4.29it/s]

 92%|█████████▏| 566/613 [02:11<00:10,  4.30it/s]

 92%|█████████▏| 567/613 [02:11<00:10,  4.29it/s]

 93%|█████████▎| 568/613 [02:12<00:10,  4.29it/s]

 93%|█████████▎| 569/613 [02:12<00:10,  4.28it/s]

 93%|█████████▎| 570/613 [02:12<00:10,  4.29it/s]

 93%|█████████▎| 571/613 [02:12<00:09,  4.29it/s]

 93%|█████████▎| 572/613 [02:13<00:09,  4.30it/s]

 93%|█████████▎| 573/613 [02:13<00:09,  4.30it/s]

 94%|█████████▎| 574/613 [02:13<00:09,  4.28it/s]

 94%|█████████▍| 575/613 [02:13<00:08,  4.27it/s]

 94%|█████████▍| 576/613 [02:14<00:08,  4.28it/s]

 94%|█████████▍| 577/613 [02:14<00:08,  4.30it/s]

 94%|█████████▍| 578/613 [02:14<00:08,  4.29it/s]

 94%|█████████▍| 579/613 [02:14<00:07,  4.29it/s]

 95%|█████████▍| 580/613 [02:14<00:07,  4.25it/s]

 95%|█████████▍| 581/613 [02:15<00:07,  4.26it/s]

 95%|█████████▍| 582/613 [02:15<00:07,  4.28it/s]

 95%|█████████▌| 583/613 [02:15<00:07,  4.28it/s]

 95%|█████████▌| 584/613 [02:15<00:06,  4.29it/s]

 95%|█████████▌| 585/613 [02:16<00:06,  4.29it/s]

 96%|█████████▌| 586/613 [02:16<00:06,  4.29it/s]

 96%|█████████▌| 587/613 [02:16<00:06,  4.28it/s]

 96%|█████████▌| 588/613 [02:16<00:05,  4.27it/s]

 96%|█████████▌| 589/613 [02:17<00:05,  4.27it/s]

 96%|█████████▌| 590/613 [02:17<00:05,  4.28it/s]

 96%|█████████▋| 591/613 [02:17<00:05,  4.29it/s]

 97%|█████████▋| 592/613 [02:17<00:04,  4.28it/s]

 97%|█████████▋| 593/613 [02:18<00:04,  4.29it/s]

 97%|█████████▋| 594/613 [02:18<00:04,  4.28it/s]

 97%|█████████▋| 595/613 [02:18<00:04,  4.29it/s]

 97%|█████████▋| 596/613 [02:18<00:03,  4.28it/s]

 97%|█████████▋| 597/613 [02:18<00:03,  4.28it/s]

 98%|█████████▊| 598/613 [02:19<00:03,  4.29it/s]

 98%|█████████▊| 599/613 [02:19<00:03,  4.28it/s]

 98%|█████████▊| 600/613 [02:19<00:03,  4.29it/s]

 98%|█████████▊| 601/613 [02:19<00:02,  4.29it/s]

 98%|█████████▊| 602/613 [02:20<00:02,  4.29it/s]

 98%|█████████▊| 603/613 [02:20<00:02,  4.29it/s]

 99%|█████████▊| 604/613 [02:20<00:02,  4.28it/s]

 99%|█████████▊| 605/613 [02:20<00:01,  4.29it/s]

 99%|█████████▉| 606/613 [02:21<00:01,  4.29it/s]

 99%|█████████▉| 607/613 [02:21<00:01,  4.28it/s]

 99%|█████████▉| 608/613 [02:21<00:01,  4.29it/s]

 99%|█████████▉| 609/613 [02:21<00:00,  4.29it/s]

100%|█████████▉| 610/613 [02:21<00:00,  4.30it/s]

100%|█████████▉| 611/613 [02:22<00:00,  4.28it/s]

100%|█████████▉| 612/613 [02:22<00:00,  4.28it/s]

100%|██████████| 613/613 [02:23<00:00,  2.10it/s]

100%|██████████| 613/613 [02:23<00:00,  4.26it/s]

logging the anndata

AnnData object with n_obs × n_vars = 39176 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

too few cells to embed into a umap
too few cells to compute a clustering

{'cellxgene_census/dkd_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4937716969573208, 'macro': 0.38015219981782045, 'micro': 0.4937716969573208, 'weighted': 0.44125553939089207}}, 'cellxgene_census/dkd_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4630541871921182, 'macro': 0.39612779635380635, 'micro': 0.4630541871921182, 'weighted': 0.43238258813181274}}}

doing  cellxgene_census/gtex_v9

/lustre/fswork/projects/rech/xeg/uat95fg/scdataloader/scdataloader/utils.py:427: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  organismdf = pd.concat(organismdf)

predict epoch start

  0%|          | 0/3268 [00:00<?, ?it/s]

  0%|          | 1/3268 [00:04<3:39:30,  4.03s/it]

  0%|          | 2/3268 [00:04<1:37:46,  1.80s/it]

  0%|          | 3/3268 [00:04<58:55,  1.08s/it]

  0%|          | 4/3268 [00:04<40:25,  1.35it/s]

  0%|          | 5/3268 [00:04<30:15,  1.80it/s]

  0%|          | 6/3268 [00:05<24:05,  2.26it/s]

  0%|          | 7/3268 [00:05<20:10,  2.69it/s]

  0%|          | 8/3268 [00:05<17:36,  3.08it/s]

  0%|          | 9/3268 [00:05<16:01,  3.39it/s]

  0%|          | 10/3268 [00:06<14:50,  3.66it/s]

  0%|          | 11/3268 [00:06<14:00,  3.87it/s]

  0%|          | 12/3268 [00:06<13:27,  4.03it/s]

  0%|          | 13/3268 [00:06<13:04,  4.15it/s]

  0%|          | 14/3268 [00:06<12:48,  4.23it/s]

  0%|          | 15/3268 [00:07<12:38,  4.29it/s]

  0%|          | 16/3268 [00:07<12:29,  4.34it/s]

  1%|          | 17/3268 [00:07<12:24,  4.37it/s]

  1%|          | 18/3268 [00:07<12:20,  4.39it/s]

  1%|          | 19/3268 [00:08<12:18,  4.40it/s]

  1%|          | 20/3268 [00:08<12:16,  4.41it/s]

  1%|          | 21/3268 [00:08<12:15,  4.41it/s]

  1%|          | 22/3268 [00:08<12:13,  4.42it/s]

  1%|          | 23/3268 [00:08<12:13,  4.42it/s]

  1%|          | 24/3268 [00:09<12:13,  4.42it/s]

  1%|          | 25/3268 [00:09<12:12,  4.43it/s]

  1%|          | 26/3268 [00:09<12:11,  4.43it/s]

  1%|          | 27/3268 [00:09<12:13,  4.42it/s]

  1%|          | 28/3268 [00:10<12:11,  4.43it/s]

  1%|          | 29/3268 [00:10<12:13,  4.42it/s]

  1%|          | 30/3268 [00:10<12:12,  4.42it/s]

  1%|          | 31/3268 [00:10<12:15,  4.40it/s]

  1%|          | 32/3268 [00:11<12:14,  4.41it/s]

  1%|          | 33/3268 [00:11<12:12,  4.41it/s]

  1%|          | 34/3268 [00:11<12:11,  4.42it/s]

  1%|          | 35/3268 [00:11<12:12,  4.42it/s]

  1%|          | 36/3268 [00:11<12:10,  4.43it/s]

  1%|          | 37/3268 [00:12<12:11,  4.42it/s]

  1%|          | 38/3268 [00:12<12:13,  4.40it/s]

  1%|          | 39/3268 [00:12<12:11,  4.42it/s]

  1%|          | 40/3268 [00:12<12:10,  4.42it/s]

  1%|▏         | 41/3268 [00:13<12:12,  4.41it/s]

  1%|▏         | 42/3268 [00:13<12:10,  4.41it/s]

  1%|▏         | 43/3268 [00:13<12:09,  4.42it/s]

  1%|▏         | 44/3268 [00:13<12:10,  4.42it/s]

  1%|▏         | 45/3268 [00:13<12:08,  4.42it/s]

  1%|▏         | 46/3268 [00:14<12:09,  4.42it/s]

  1%|▏         | 47/3268 [00:14<12:09,  4.41it/s]

  1%|▏         | 48/3268 [00:14<12:09,  4.42it/s]

  1%|▏         | 49/3268 [00:14<12:09,  4.41it/s]

  2%|▏         | 50/3268 [00:15<12:09,  4.41it/s]

  2%|▏         | 51/3268 [00:15<12:09,  4.41it/s]

  2%|▏         | 52/3268 [00:15<12:11,  4.39it/s]

  2%|▏         | 53/3268 [00:15<12:11,  4.40it/s]

  2%|▏         | 54/3268 [00:16<12:10,  4.40it/s]

  2%|▏         | 55/3268 [00:16<12:08,  4.41it/s]

  2%|▏         | 56/3268 [00:16<12:08,  4.41it/s]

  2%|▏         | 57/3268 [00:16<12:06,  4.42it/s]

  2%|▏         | 58/3268 [00:16<12:06,  4.42it/s]

  2%|▏         | 59/3268 [00:17<12:05,  4.42it/s]

  2%|▏         | 60/3268 [00:17<12:07,  4.41it/s]

  2%|▏         | 61/3268 [00:17<12:06,  4.42it/s]

  2%|▏         | 62/3268 [00:17<12:05,  4.42it/s]

  2%|▏         | 63/3268 [00:18<12:07,  4.41it/s]

  2%|▏         | 64/3268 [00:18<12:07,  4.41it/s]

  2%|▏         | 65/3268 [00:18<12:07,  4.40it/s]

  2%|▏         | 66/3268 [00:18<12:07,  4.40it/s]

  2%|▏         | 67/3268 [00:18<12:06,  4.41it/s]

  2%|▏         | 68/3268 [00:19<12:05,  4.41it/s]

  2%|▏         | 69/3268 [00:19<12:03,  4.42it/s]

  2%|▏         | 70/3268 [00:19<12:03,  4.42it/s]

  2%|▏         | 71/3268 [00:19<12:03,  4.42it/s]

  2%|▏         | 72/3268 [00:20<12:06,  4.40it/s]

  2%|▏         | 73/3268 [00:20<12:03,  4.42it/s]

  2%|▏         | 74/3268 [00:20<12:03,  4.42it/s]

  2%|▏         | 75/3268 [00:20<12:04,  4.41it/s]

  2%|▏         | 76/3268 [00:21<12:02,  4.42it/s]

  2%|▏         | 77/3268 [00:21<12:00,  4.43it/s]

  2%|▏         | 78/3268 [00:21<12:01,  4.42it/s]

  2%|▏         | 79/3268 [00:21<12:01,  4.42it/s]

  2%|▏         | 80/3268 [00:21<12:12,  4.35it/s]

  2%|▏         | 81/3268 [00:22<12:09,  4.37it/s]

  3%|▎         | 82/3268 [00:22<12:07,  4.38it/s]

  3%|▎         | 83/3268 [00:22<12:08,  4.37it/s]

  3%|▎         | 84/3268 [00:22<12:03,  4.40it/s]

  3%|▎         | 85/3268 [00:23<12:01,  4.41it/s]

  3%|▎         | 86/3268 [00:23<12:01,  4.41it/s]

  3%|▎         | 87/3268 [00:23<12:01,  4.41it/s]

  3%|▎         | 88/3268 [00:23<12:01,  4.41it/s]

  3%|▎         | 89/3268 [00:23<12:00,  4.41it/s]

  3%|▎         | 90/3268 [00:24<11:59,  4.42it/s]

  3%|▎         | 91/3268 [00:24<11:58,  4.42it/s]

  3%|▎         | 92/3268 [00:24<11:58,  4.42it/s]

  3%|▎         | 93/3268 [00:24<11:56,  4.43it/s]

  3%|▎         | 94/3268 [00:25<11:57,  4.42it/s]

  3%|▎         | 95/3268 [00:25<12:00,  4.40it/s]

  3%|▎         | 96/3268 [00:25<11:58,  4.42it/s]

  3%|▎         | 97/3268 [00:25<11:59,  4.41it/s]

  3%|▎         | 98/3268 [00:26<11:59,  4.40it/s]

  3%|▎         | 99/3268 [00:26<11:57,  4.42it/s]

  3%|▎         | 100/3268 [00:26<11:57,  4.41it/s]

  3%|▎         | 101/3268 [00:26<11:57,  4.41it/s]

  3%|▎         | 102/3268 [00:26<11:56,  4.42it/s]

  3%|▎         | 103/3268 [00:27<11:57,  4.41it/s]

  3%|▎         | 104/3268 [00:27<11:57,  4.41it/s]

  3%|▎         | 105/3268 [00:27<11:57,  4.41it/s]

  3%|▎         | 106/3268 [00:27<11:58,  4.40it/s]

  3%|▎         | 107/3268 [00:28<11:56,  4.41it/s]

  3%|▎         | 108/3268 [00:28<11:55,  4.41it/s]

  3%|▎         | 109/3268 [00:28<11:58,  4.40it/s]

  3%|▎         | 110/3268 [00:28<11:58,  4.39it/s]

  3%|▎         | 111/3268 [00:28<11:58,  4.39it/s]

  3%|▎         | 112/3268 [00:29<11:58,  4.39it/s]

  3%|▎         | 113/3268 [00:29<12:00,  4.38it/s]

  3%|▎         | 114/3268 [00:29<12:01,  4.37it/s]

  4%|▎         | 115/3268 [00:29<11:59,  4.38it/s]

  4%|▎         | 116/3268 [00:30<11:57,  4.39it/s]

  4%|▎         | 117/3268 [00:30<11:59,  4.38it/s]

  4%|▎         | 118/3268 [00:30<11:58,  4.38it/s]

  4%|▎         | 119/3268 [00:30<11:58,  4.38it/s]

  4%|▎         | 120/3268 [00:31<12:01,  4.36it/s]

  4%|▎         | 121/3268 [00:31<11:59,  4.37it/s]

  4%|▎         | 122/3268 [00:31<11:57,  4.38it/s]

  4%|▍         | 123/3268 [00:31<11:56,  4.39it/s]

  4%|▍         | 124/3268 [00:31<11:55,  4.40it/s]

  4%|▍         | 125/3268 [00:32<11:55,  4.40it/s]

  4%|▍         | 126/3268 [00:32<11:54,  4.40it/s]

  4%|▍         | 127/3268 [00:32<11:54,  4.39it/s]

  4%|▍         | 128/3268 [00:32<11:55,  4.39it/s]

  4%|▍         | 129/3268 [00:33<11:53,  4.40it/s]

  4%|▍         | 130/3268 [00:33<11:54,  4.39it/s]

  4%|▍         | 131/3268 [00:33<11:54,  4.39it/s]

  4%|▍         | 132/3268 [00:33<11:52,  4.40it/s]

  4%|▍         | 133/3268 [00:33<11:52,  4.40it/s]

  4%|▍         | 134/3268 [00:34<11:52,  4.40it/s]

  4%|▍         | 135/3268 [00:34<11:53,  4.39it/s]

  4%|▍         | 136/3268 [00:34<11:52,  4.40it/s]

  4%|▍         | 137/3268 [00:34<11:52,  4.39it/s]

  4%|▍         | 138/3268 [00:35<11:52,  4.40it/s]

  4%|▍         | 139/3268 [00:35<11:52,  4.39it/s]

  4%|▍         | 140/3268 [00:35<11:54,  4.38it/s]

  4%|▍         | 141/3268 [00:35<11:53,  4.38it/s]

  4%|▍         | 142/3268 [00:36<11:52,  4.38it/s]

  4%|▍         | 143/3268 [00:36<11:52,  4.39it/s]

  4%|▍         | 144/3268 [00:36<11:51,  4.39it/s]

  4%|▍         | 145/3268 [00:36<11:50,  4.39it/s]

  4%|▍         | 146/3268 [00:36<11:50,  4.39it/s]

  4%|▍         | 147/3268 [00:37<11:51,  4.39it/s]

  5%|▍         | 148/3268 [00:37<11:52,  4.38it/s]

  5%|▍         | 149/3268 [00:37<11:50,  4.39it/s]

  5%|▍         | 150/3268 [00:37<11:51,  4.38it/s]

  5%|▍         | 151/3268 [00:38<11:50,  4.39it/s]

  5%|▍         | 152/3268 [00:38<11:49,  4.39it/s]

  5%|▍         | 153/3268 [00:38<11:49,  4.39it/s]

  5%|▍         | 154/3268 [00:38<11:49,  4.39it/s]

  5%|▍         | 155/3268 [00:38<11:47,  4.40it/s]

  5%|▍         | 156/3268 [00:39<11:47,  4.40it/s]

  5%|▍         | 157/3268 [00:39<11:50,  4.38it/s]

  5%|▍         | 158/3268 [00:39<11:49,  4.38it/s]

  5%|▍         | 159/3268 [00:39<11:48,  4.39it/s]

  5%|▍         | 160/3268 [00:40<11:47,  4.39it/s]

  5%|▍         | 161/3268 [00:40<11:48,  4.39it/s]

  5%|▍         | 162/3268 [00:40<11:48,  4.38it/s]

  5%|▍         | 163/3268 [00:40<11:48,  4.38it/s]

  5%|▌         | 164/3268 [00:41<11:50,  4.37it/s]

  5%|▌         | 165/3268 [00:41<11:50,  4.37it/s]

  5%|▌         | 166/3268 [00:41<11:47,  4.38it/s]

  5%|▌         | 167/3268 [00:41<11:47,  4.39it/s]

  5%|▌         | 168/3268 [00:41<11:46,  4.38it/s]

  5%|▌         | 169/3268 [00:42<11:48,  4.38it/s]

  5%|▌         | 170/3268 [00:42<11:47,  4.38it/s]

  5%|▌         | 171/3268 [00:42<11:48,  4.37it/s]

  5%|▌         | 172/3268 [00:42<11:48,  4.37it/s]

  5%|▌         | 173/3268 [00:43<11:49,  4.36it/s]

  5%|▌         | 174/3268 [00:43<11:48,  4.36it/s]

  5%|▌         | 175/3268 [00:43<11:47,  4.37it/s]

  5%|▌         | 176/3268 [00:43<11:49,  4.36it/s]

  5%|▌         | 177/3268 [00:44<11:47,  4.37it/s]

  5%|▌         | 178/3268 [00:44<11:47,  4.37it/s]

  5%|▌         | 179/3268 [00:44<11:55,  4.32it/s]

  6%|▌         | 180/3268 [00:44<11:50,  4.35it/s]

  6%|▌         | 181/3268 [00:44<11:49,  4.35it/s]

  6%|▌         | 182/3268 [00:45<11:47,  4.36it/s]

  6%|▌         | 183/3268 [00:45<11:46,  4.37it/s]

  6%|▌         | 184/3268 [00:45<11:48,  4.35it/s]

  6%|▌         | 185/3268 [00:45<11:46,  4.36it/s]

  6%|▌         | 186/3268 [00:46<11:46,  4.37it/s]

  6%|▌         | 187/3268 [00:46<11:44,  4.37it/s]

  6%|▌         | 188/3268 [00:46<11:44,  4.37it/s]

  6%|▌         | 189/3268 [00:46<11:45,  4.36it/s]

  6%|▌         | 190/3268 [00:46<11:44,  4.37it/s]

  6%|▌         | 191/3268 [00:47<11:44,  4.37it/s]

  6%|▌         | 192/3268 [00:47<11:43,  4.37it/s]

  6%|▌         | 193/3268 [00:47<11:42,  4.38it/s]

  6%|▌         | 194/3268 [00:47<11:43,  4.37it/s]

  6%|▌         | 195/3268 [00:48<11:43,  4.37it/s]

  6%|▌         | 196/3268 [00:48<11:41,  4.38it/s]

  6%|▌         | 197/3268 [00:48<11:42,  4.37it/s]

  6%|▌         | 198/3268 [00:48<11:41,  4.38it/s]

  6%|▌         | 199/3268 [00:49<11:40,  4.38it/s]

  6%|▌         | 200/3268 [00:49<11:42,  4.37it/s]

  6%|▌         | 201/3268 [00:49<11:41,  4.37it/s]

  6%|▌         | 202/3268 [00:49<11:41,  4.37it/s]

  6%|▌         | 203/3268 [00:49<11:42,  4.36it/s]

  6%|▌         | 204/3268 [00:50<11:42,  4.36it/s]

  6%|▋         | 205/3268 [00:50<11:41,  4.37it/s]

  6%|▋         | 206/3268 [00:50<11:41,  4.36it/s]

  6%|▋         | 207/3268 [00:50<11:39,  4.37it/s]

  6%|▋         | 208/3268 [00:51<11:39,  4.38it/s]

  6%|▋         | 209/3268 [00:51<11:39,  4.38it/s]

  6%|▋         | 210/3268 [00:51<11:38,  4.38it/s]

  6%|▋         | 211/3268 [00:51<11:38,  4.38it/s]

  6%|▋         | 212/3268 [00:52<11:42,  4.35it/s]

  7%|▋         | 213/3268 [00:52<11:39,  4.37it/s]

  7%|▋         | 214/3268 [00:52<11:38,  4.37it/s]

  7%|▋         | 215/3268 [00:52<11:36,  4.38it/s]

  7%|▋         | 216/3268 [00:52<11:38,  4.37it/s]

  7%|▋         | 217/3268 [00:53<11:39,  4.36it/s]

  7%|▋         | 218/3268 [00:53<11:37,  4.37it/s]

  7%|▋         | 219/3268 [00:53<11:38,  4.37it/s]

  7%|▋         | 220/3268 [00:53<11:38,  4.37it/s]

  7%|▋         | 221/3268 [00:54<11:38,  4.36it/s]

  7%|▋         | 222/3268 [00:54<11:36,  4.37it/s]

  7%|▋         | 223/3268 [00:54<11:36,  4.37it/s]

  7%|▋         | 224/3268 [00:54<11:36,  4.37it/s]

  7%|▋         | 225/3268 [00:54<11:37,  4.36it/s]

  7%|▋         | 226/3268 [00:55<11:38,  4.35it/s]

  7%|▋         | 227/3268 [00:55<11:36,  4.36it/s]

  7%|▋         | 228/3268 [00:55<11:36,  4.36it/s]

  7%|▋         | 229/3268 [00:55<11:34,  4.37it/s]

  7%|▋         | 230/3268 [00:56<11:35,  4.37it/s]

  7%|▋         | 231/3268 [00:56<11:34,  4.37it/s]

  7%|▋         | 232/3268 [00:56<11:34,  4.37it/s]

  7%|▋         | 233/3268 [00:56<11:33,  4.38it/s]

  7%|▋         | 234/3268 [00:57<11:32,  4.38it/s]

  7%|▋         | 235/3268 [00:57<11:32,  4.38it/s]

  7%|▋         | 236/3268 [00:57<11:32,  4.38it/s]

  7%|▋         | 237/3268 [00:57<11:32,  4.38it/s]

  7%|▋         | 238/3268 [00:57<11:31,  4.38it/s]

  7%|▋         | 239/3268 [00:58<11:30,  4.39it/s]

  7%|▋         | 240/3268 [00:58<11:30,  4.39it/s]

  7%|▋         | 241/3268 [00:58<11:31,  4.38it/s]

  7%|▋         | 242/3268 [00:58<11:31,  4.37it/s]

  7%|▋         | 243/3268 [00:59<11:30,  4.38it/s]

  7%|▋         | 244/3268 [00:59<11:30,  4.38it/s]

  7%|▋         | 245/3268 [00:59<11:29,  4.38it/s]

  8%|▊         | 246/3268 [00:59<11:30,  4.38it/s]

  8%|▊         | 247/3268 [01:00<11:29,  4.38it/s]

  8%|▊         | 248/3268 [01:00<11:29,  4.38it/s]

  8%|▊         | 249/3268 [01:00<11:31,  4.37it/s]

  8%|▊         | 250/3268 [01:00<11:30,  4.37it/s]

  8%|▊         | 251/3268 [01:00<11:29,  4.38it/s]

  8%|▊         | 252/3268 [01:01<11:31,  4.36it/s]

  8%|▊         | 253/3268 [01:01<11:32,  4.36it/s]

  8%|▊         | 254/3268 [01:01<11:31,  4.36it/s]

  8%|▊         | 255/3268 [01:01<11:31,  4.35it/s]

  8%|▊         | 256/3268 [01:02<11:31,  4.36it/s]

  8%|▊         | 257/3268 [01:02<11:29,  4.37it/s]

  8%|▊         | 258/3268 [01:02<11:28,  4.37it/s]

  8%|▊         | 259/3268 [01:02<11:27,  4.38it/s]

  8%|▊         | 260/3268 [01:02<11:25,  4.39it/s]

  8%|▊         | 261/3268 [01:03<11:25,  4.39it/s]

  8%|▊         | 262/3268 [01:03<11:25,  4.39it/s]

  8%|▊         | 263/3268 [01:03<11:23,  4.39it/s]

  8%|▊         | 264/3268 [01:03<11:25,  4.39it/s]

  8%|▊         | 265/3268 [01:04<11:24,  4.39it/s]

  8%|▊         | 266/3268 [01:04<11:24,  4.39it/s]

  8%|▊         | 267/3268 [01:04<11:25,  4.38it/s]

  8%|▊         | 268/3268 [01:04<11:24,  4.38it/s]

  8%|▊         | 269/3268 [01:05<11:27,  4.36it/s]

  8%|▊         | 270/3268 [01:05<11:27,  4.36it/s]

  8%|▊         | 271/3268 [01:05<11:26,  4.36it/s]

  8%|▊         | 272/3268 [01:05<11:27,  4.36it/s]

  8%|▊         | 273/3268 [01:05<11:26,  4.36it/s]

  8%|▊         | 274/3268 [01:06<11:28,  4.35it/s]

  8%|▊         | 275/3268 [01:06<11:28,  4.35it/s]

  8%|▊         | 276/3268 [01:06<11:28,  4.35it/s]

  8%|▊         | 277/3268 [01:06<11:27,  4.35it/s]

  9%|▊         | 278/3268 [01:07<11:26,  4.35it/s]

  9%|▊         | 279/3268 [01:07<11:26,  4.35it/s]

  9%|▊         | 280/3268 [01:07<11:24,  4.37it/s]

  9%|▊         | 281/3268 [01:07<11:23,  4.37it/s]

  9%|▊         | 282/3268 [01:08<11:25,  4.36it/s]

  9%|▊         | 283/3268 [01:08<11:24,  4.36it/s]

  9%|▊         | 284/3268 [01:08<11:23,  4.36it/s]

  9%|▊         | 285/3268 [01:08<11:23,  4.36it/s]

  9%|▉         | 286/3268 [01:08<11:22,  4.37it/s]

  9%|▉         | 287/3268 [01:09<11:23,  4.36it/s]

  9%|▉         | 288/3268 [01:09<11:22,  4.37it/s]

  9%|▉         | 289/3268 [01:09<11:21,  4.37it/s]

  9%|▉         | 290/3268 [01:09<11:22,  4.36it/s]

  9%|▉         | 291/3268 [01:10<11:24,  4.35it/s]

  9%|▉         | 292/3268 [01:10<11:21,  4.36it/s]

  9%|▉         | 293/3268 [01:10<11:22,  4.36it/s]

  9%|▉         | 294/3268 [01:10<11:20,  4.37it/s]

  9%|▉         | 295/3268 [01:11<11:18,  4.38it/s]

  9%|▉         | 296/3268 [01:11<11:20,  4.37it/s]

  9%|▉         | 297/3268 [01:11<11:20,  4.37it/s]

  9%|▉         | 298/3268 [01:11<11:20,  4.37it/s]

  9%|▉         | 299/3268 [01:11<11:21,  4.36it/s]

  9%|▉         | 300/3268 [01:12<11:17,  4.38it/s]

  9%|▉         | 301/3268 [01:12<11:17,  4.38it/s]

  9%|▉         | 302/3268 [01:12<11:21,  4.35it/s]

  9%|▉         | 303/3268 [01:12<11:19,  4.36it/s]

  9%|▉         | 304/3268 [01:13<11:17,  4.37it/s]

  9%|▉         | 305/3268 [01:13<11:14,  4.39it/s]

  9%|▉         | 306/3268 [01:13<11:13,  4.40it/s]

  9%|▉         | 307/3268 [01:13<11:14,  4.39it/s]

  9%|▉         | 308/3268 [01:13<11:13,  4.39it/s]

  9%|▉         | 309/3268 [01:14<11:13,  4.39it/s]

  9%|▉         | 310/3268 [01:14<11:13,  4.39it/s]

 10%|▉         | 311/3268 [01:14<11:12,  4.40it/s]

 10%|▉         | 312/3268 [01:14<11:12,  4.40it/s]

 10%|▉         | 313/3268 [01:15<11:12,  4.39it/s]

 10%|▉         | 314/3268 [01:15<11:13,  4.39it/s]

 10%|▉         | 315/3268 [01:15<11:14,  4.38it/s]

 10%|▉         | 316/3268 [01:15<11:13,  4.38it/s]

 10%|▉         | 317/3268 [01:16<11:13,  4.38it/s]

 10%|▉         | 318/3268 [01:16<11:13,  4.38it/s]

 10%|▉         | 319/3268 [01:16<11:13,  4.38it/s]

 10%|▉         | 320/3268 [01:16<11:13,  4.38it/s]

 10%|▉         | 321/3268 [01:16<11:13,  4.38it/s]

 10%|▉         | 322/3268 [01:17<11:11,  4.39it/s]

 10%|▉         | 323/3268 [01:17<11:11,  4.38it/s]

 10%|▉         | 324/3268 [01:17<11:10,  4.39it/s]

 10%|▉         | 325/3268 [01:17<11:10,  4.39it/s]

 10%|▉         | 326/3268 [01:18<11:11,  4.38it/s]

 10%|█         | 327/3268 [01:18<11:13,  4.37it/s]

 10%|█         | 328/3268 [01:18<11:13,  4.37it/s]

 10%|█         | 329/3268 [01:18<11:13,  4.36it/s]

 10%|█         | 330/3268 [01:19<11:11,  4.37it/s]

 10%|█         | 331/3268 [01:19<11:11,  4.37it/s]

 10%|█         | 332/3268 [01:19<11:09,  4.38it/s]

 10%|█         | 333/3268 [01:19<11:09,  4.38it/s]

 10%|█         | 334/3268 [01:19<11:10,  4.38it/s]

 10%|█         | 335/3268 [01:20<11:10,  4.38it/s]

 10%|█         | 336/3268 [01:20<11:09,  4.38it/s]

 10%|█         | 337/3268 [01:20<11:12,  4.36it/s]

 10%|█         | 338/3268 [01:20<11:12,  4.36it/s]

 10%|█         | 339/3268 [01:21<11:11,  4.36it/s]

 10%|█         | 340/3268 [01:21<11:10,  4.37it/s]

 10%|█         | 341/3268 [01:21<11:08,  4.38it/s]

 10%|█         | 342/3268 [01:21<11:07,  4.39it/s]

 10%|█         | 343/3268 [01:21<11:07,  4.38it/s]

 11%|█         | 344/3268 [01:22<11:07,  4.38it/s]

 11%|█         | 345/3268 [01:22<11:07,  4.38it/s]

 11%|█         | 346/3268 [01:22<11:08,  4.37it/s]

 11%|█         | 347/3268 [01:22<11:06,  4.38it/s]

 11%|█         | 348/3268 [01:23<11:05,  4.39it/s]

 11%|█         | 349/3268 [01:23<11:05,  4.38it/s]

 11%|█         | 350/3268 [01:23<11:05,  4.39it/s]

 11%|█         | 351/3268 [01:23<11:07,  4.37it/s]

 11%|█         | 352/3268 [01:24<11:08,  4.37it/s]

 11%|█         | 353/3268 [01:24<11:07,  4.36it/s]

 11%|█         | 354/3268 [01:24<11:08,  4.36it/s]

 11%|█         | 355/3268 [01:24<11:07,  4.36it/s]

 11%|█         | 356/3268 [01:24<11:08,  4.36it/s]

 11%|█         | 357/3268 [01:25<11:08,  4.35it/s]

 11%|█         | 358/3268 [01:25<11:07,  4.36it/s]

 11%|█         | 359/3268 [01:25<11:07,  4.36it/s]

 11%|█         | 360/3268 [01:25<11:07,  4.36it/s]

 11%|█         | 361/3268 [01:26<11:05,  4.37it/s]

 11%|█         | 362/3268 [01:26<11:05,  4.37it/s]

 11%|█         | 363/3268 [01:26<11:06,  4.36it/s]

 11%|█         | 364/3268 [01:26<11:05,  4.37it/s]

 11%|█         | 365/3268 [01:27<11:06,  4.35it/s]

 11%|█         | 366/3268 [01:27<11:05,  4.36it/s]

 11%|█         | 367/3268 [01:27<11:05,  4.36it/s]

 11%|█▏        | 368/3268 [01:27<11:05,  4.36it/s]

 11%|█▏        | 369/3268 [01:27<11:05,  4.36it/s]

 11%|█▏        | 370/3268 [01:28<11:05,  4.36it/s]

 11%|█▏        | 371/3268 [01:28<11:04,  4.36it/s]

 11%|█▏        | 372/3268 [01:28<11:05,  4.35it/s]

 11%|█▏        | 373/3268 [01:28<11:04,  4.35it/s]

 11%|█▏        | 374/3268 [01:29<11:03,  4.36it/s]

 11%|█▏        | 375/3268 [01:29<11:03,  4.36it/s]

 12%|█▏        | 376/3268 [01:29<11:03,  4.36it/s]

 12%|█▏        | 377/3268 [01:29<11:03,  4.36it/s]

 12%|█▏        | 378/3268 [01:29<11:01,  4.37it/s]

 12%|█▏        | 379/3268 [01:30<11:00,  4.37it/s]

 12%|█▏        | 380/3268 [01:30<11:00,  4.37it/s]

 12%|█▏        | 381/3268 [01:30<11:01,  4.36it/s]

 12%|█▏        | 382/3268 [01:30<11:01,  4.36it/s]

 12%|█▏        | 383/3268 [01:31<11:02,  4.36it/s]

 12%|█▏        | 384/3268 [01:31<11:02,  4.35it/s]

 12%|█▏        | 385/3268 [01:31<11:01,  4.36it/s]

 12%|█▏        | 386/3268 [01:31<11:00,  4.36it/s]

 12%|█▏        | 387/3268 [01:32<11:02,  4.35it/s]

 12%|█▏        | 388/3268 [01:32<11:01,  4.36it/s]

 12%|█▏        | 389/3268 [01:32<11:01,  4.35it/s]

 12%|█▏        | 390/3268 [01:32<11:03,  4.34it/s]

 12%|█▏        | 391/3268 [01:32<11:02,  4.34it/s]

 12%|█▏        | 392/3268 [01:33<11:00,  4.35it/s]

 12%|█▏        | 393/3268 [01:33<10:59,  4.36it/s]

 12%|█▏        | 394/3268 [01:33<11:00,  4.35it/s]

 12%|█▏        | 395/3268 [01:33<11:03,  4.33it/s]

 12%|█▏        | 396/3268 [01:34<11:01,  4.34it/s]

 12%|█▏        | 397/3268 [01:34<11:00,  4.35it/s]

 12%|█▏        | 398/3268 [01:34<11:04,  4.32it/s]

 12%|█▏        | 399/3268 [01:34<11:01,  4.33it/s]

 12%|█▏        | 400/3268 [01:35<11:00,  4.34it/s]

 12%|█▏        | 401/3268 [01:35<10:59,  4.35it/s]

 12%|█▏        | 402/3268 [01:35<10:58,  4.36it/s]

 12%|█▏        | 403/3268 [01:35<10:57,  4.36it/s]

 12%|█▏        | 404/3268 [01:35<10:56,  4.36it/s]

 12%|█▏        | 405/3268 [01:36<10:56,  4.36it/s]

 12%|█▏        | 406/3268 [01:36<10:57,  4.35it/s]

 12%|█▏        | 407/3268 [01:36<10:56,  4.36it/s]

 12%|█▏        | 408/3268 [01:36<10:57,  4.35it/s]

 13%|█▎        | 409/3268 [01:37<10:57,  4.35it/s]

 13%|█▎        | 410/3268 [01:37<10:57,  4.35it/s]

 13%|█▎        | 411/3268 [01:37<10:58,  4.34it/s]

 13%|█▎        | 412/3268 [01:37<10:57,  4.35it/s]

 13%|█▎        | 413/3268 [01:38<10:57,  4.34it/s]

 13%|█▎        | 414/3268 [01:38<10:56,  4.35it/s]

 13%|█▎        | 415/3268 [01:38<10:56,  4.35it/s]

 13%|█▎        | 416/3268 [01:38<10:55,  4.35it/s]

 13%|█▎        | 417/3268 [01:38<10:54,  4.35it/s]

 13%|█▎        | 418/3268 [01:39<10:55,  4.35it/s]

 13%|█▎        | 419/3268 [01:39<10:56,  4.34it/s]

 13%|█▎        | 420/3268 [01:39<10:55,  4.34it/s]

 13%|█▎        | 421/3268 [01:39<10:55,  4.34it/s]

 13%|█▎        | 422/3268 [01:40<10:57,  4.33it/s]

 13%|█▎        | 423/3268 [01:40<10:55,  4.34it/s]

 13%|█▎        | 424/3268 [01:40<10:55,  4.34it/s]

 13%|█▎        | 425/3268 [01:40<10:55,  4.34it/s]

 13%|█▎        | 426/3268 [01:41<10:54,  4.34it/s]

 13%|█▎        | 427/3268 [01:41<10:54,  4.34it/s]

 13%|█▎        | 428/3268 [01:41<10:54,  4.34it/s]

 13%|█▎        | 429/3268 [01:41<10:54,  4.33it/s]

 13%|█▎        | 430/3268 [01:41<10:53,  4.34it/s]

 13%|█▎        | 431/3268 [01:42<10:52,  4.35it/s]

 13%|█▎        | 432/3268 [01:42<10:52,  4.34it/s]

 13%|█▎        | 433/3268 [01:42<10:52,  4.35it/s]

 13%|█▎        | 434/3268 [01:42<10:51,  4.35it/s]

 13%|█▎        | 435/3268 [01:43<10:52,  4.34it/s]

 13%|█▎        | 436/3268 [01:43<10:50,  4.35it/s]

 13%|█▎        | 437/3268 [01:43<10:49,  4.36it/s]

 13%|█▎        | 438/3268 [01:43<10:51,  4.35it/s]

 13%|█▎        | 439/3268 [01:44<10:50,  4.35it/s]

 13%|█▎        | 440/3268 [01:44<10:51,  4.34it/s]

 13%|█▎        | 441/3268 [01:44<10:50,  4.34it/s]

 14%|█▎        | 442/3268 [01:44<10:50,  4.34it/s]

 14%|█▎        | 443/3268 [01:44<10:51,  4.34it/s]

 14%|█▎        | 444/3268 [01:45<10:50,  4.34it/s]

 14%|█▎        | 445/3268 [01:45<10:50,  4.34it/s]

 14%|█▎        | 446/3268 [01:45<10:51,  4.33it/s]

 14%|█▎        | 447/3268 [01:45<10:50,  4.34it/s]

 14%|█▎        | 448/3268 [01:46<10:50,  4.33it/s]

 14%|█▎        | 449/3268 [01:46<10:49,  4.34it/s]

 14%|█▍        | 450/3268 [01:46<10:48,  4.34it/s]

 14%|█▍        | 451/3268 [01:46<10:48,  4.34it/s]

 14%|█▍        | 452/3268 [01:47<10:47,  4.35it/s]

 14%|█▍        | 453/3268 [01:47<10:49,  4.33it/s]

 14%|█▍        | 454/3268 [01:47<10:50,  4.33it/s]

 14%|█▍        | 455/3268 [01:47<10:47,  4.34it/s]

 14%|█▍        | 456/3268 [01:47<10:46,  4.35it/s]

 14%|█▍        | 457/3268 [01:48<10:46,  4.35it/s]

 14%|█▍        | 458/3268 [01:48<10:44,  4.36it/s]

 14%|█▍        | 459/3268 [01:48<10:44,  4.36it/s]

 14%|█▍        | 460/3268 [01:48<10:44,  4.36it/s]

 14%|█▍        | 461/3268 [01:49<10:44,  4.36it/s]

 14%|█▍        | 462/3268 [01:49<10:44,  4.35it/s]

 14%|█▍        | 463/3268 [01:49<10:43,  4.36it/s]

 14%|█▍        | 464/3268 [01:49<10:44,  4.35it/s]

 14%|█▍        | 465/3268 [01:50<10:43,  4.35it/s]

 14%|█▍        | 466/3268 [01:50<10:44,  4.35it/s]

 14%|█▍        | 467/3268 [01:50<10:44,  4.34it/s]

 14%|█▍        | 468/3268 [01:50<10:45,  4.34it/s]

 14%|█▍        | 469/3268 [01:50<10:44,  4.34it/s]

 14%|█▍        | 470/3268 [01:51<10:44,  4.34it/s]

 14%|█▍        | 471/3268 [01:51<10:43,  4.35it/s]

 14%|█▍        | 472/3268 [01:51<10:44,  4.34it/s]

 14%|█▍        | 473/3268 [01:51<10:44,  4.33it/s]

 15%|█▍        | 474/3268 [01:52<10:45,  4.33it/s]

 15%|█▍        | 475/3268 [01:52<10:45,  4.33it/s]

 15%|█▍        | 476/3268 [01:52<10:44,  4.33it/s]

 15%|█▍        | 477/3268 [01:52<10:45,  4.32it/s]

 15%|█▍        | 478/3268 [01:53<10:46,  4.32it/s]

 15%|█▍        | 479/3268 [01:53<10:44,  4.33it/s]

 15%|█▍        | 480/3268 [01:53<10:43,  4.33it/s]

 15%|█▍        | 481/3268 [01:53<10:43,  4.33it/s]

 15%|█▍        | 482/3268 [01:53<10:42,  4.33it/s]

 15%|█▍        | 483/3268 [01:54<10:44,  4.32it/s]

 15%|█▍        | 484/3268 [01:54<10:44,  4.32it/s]

 15%|█▍        | 485/3268 [01:54<10:44,  4.32it/s]

 15%|█▍        | 486/3268 [01:54<10:45,  4.31it/s]

 15%|█▍        | 487/3268 [01:55<10:43,  4.32it/s]

 15%|█▍        | 488/3268 [01:55<10:44,  4.31it/s]

 15%|█▍        | 489/3268 [01:55<10:44,  4.31it/s]

 15%|█▍        | 490/3268 [01:55<10:44,  4.31it/s]

 15%|█▌        | 491/3268 [01:56<10:44,  4.31it/s]

 15%|█▌        | 492/3268 [01:56<10:43,  4.31it/s]

 15%|█▌        | 493/3268 [01:56<10:42,  4.32it/s]

 15%|█▌        | 494/3268 [01:56<10:40,  4.33it/s]

 15%|█▌        | 495/3268 [01:56<10:40,  4.33it/s]

 15%|█▌        | 496/3268 [01:57<10:39,  4.33it/s]

 15%|█▌        | 497/3268 [01:57<10:40,  4.33it/s]

 15%|█▌        | 498/3268 [01:57<10:42,  4.31it/s]

 15%|█▌        | 499/3268 [01:57<10:43,  4.31it/s]

 15%|█▌        | 500/3268 [01:58<10:40,  4.32it/s]

 15%|█▌        | 501/3268 [01:58<10:40,  4.32it/s]

 15%|█▌        | 502/3268 [01:58<10:39,  4.33it/s]

 15%|█▌        | 503/3268 [01:58<10:39,  4.33it/s]

 15%|█▌        | 504/3268 [01:59<10:39,  4.32it/s]

 15%|█▌        | 505/3268 [01:59<10:39,  4.32it/s]

 15%|█▌        | 506/3268 [01:59<10:38,  4.33it/s]

 16%|█▌        | 507/3268 [01:59<10:39,  4.32it/s]

 16%|█▌        | 508/3268 [01:59<10:37,  4.33it/s]

 16%|█▌        | 509/3268 [02:00<10:38,  4.32it/s]

 16%|█▌        | 510/3268 [02:00<10:37,  4.32it/s]

 16%|█▌        | 511/3268 [02:00<10:39,  4.31it/s]

 16%|█▌        | 512/3268 [02:00<10:40,  4.30it/s]

 16%|█▌        | 513/3268 [02:01<10:37,  4.32it/s]

 16%|█▌        | 514/3268 [02:01<10:36,  4.33it/s]

 16%|█▌        | 515/3268 [02:01<10:37,  4.32it/s]

 16%|█▌        | 516/3268 [02:01<10:36,  4.32it/s]

 16%|█▌        | 517/3268 [02:02<10:37,  4.31it/s]

 16%|█▌        | 518/3268 [02:02<10:40,  4.29it/s]

 16%|█▌        | 519/3268 [02:02<10:38,  4.30it/s]

 16%|█▌        | 520/3268 [02:02<10:38,  4.30it/s]

 16%|█▌        | 521/3268 [02:02<10:38,  4.30it/s]

 16%|█▌        | 522/3268 [02:03<10:38,  4.30it/s]

 16%|█▌        | 523/3268 [02:03<10:39,  4.29it/s]

 16%|█▌        | 524/3268 [02:03<10:38,  4.30it/s]

 16%|█▌        | 525/3268 [02:03<10:39,  4.29it/s]

 16%|█▌        | 526/3268 [02:04<10:38,  4.30it/s]

 16%|█▌        | 527/3268 [02:04<10:36,  4.30it/s]

 16%|█▌        | 528/3268 [02:04<10:35,  4.31it/s]

 16%|█▌        | 529/3268 [02:04<10:35,  4.31it/s]

 16%|█▌        | 530/3268 [02:05<10:36,  4.30it/s]

 16%|█▌        | 531/3268 [02:05<10:36,  4.30it/s]

 16%|█▋        | 532/3268 [02:05<10:36,  4.30it/s]

 16%|█▋        | 533/3268 [02:05<10:37,  4.29it/s]

 16%|█▋        | 534/3268 [02:06<10:36,  4.30it/s]

 16%|█▋        | 535/3268 [02:06<10:35,  4.30it/s]

 16%|█▋        | 536/3268 [02:06<10:36,  4.29it/s]

 16%|█▋        | 537/3268 [02:06<10:35,  4.30it/s]

 16%|█▋        | 538/3268 [02:06<10:35,  4.30it/s]

 16%|█▋        | 539/3268 [02:07<10:34,  4.30it/s]

 17%|█▋        | 540/3268 [02:07<10:34,  4.30it/s]

 17%|█▋        | 541/3268 [02:07<10:35,  4.29it/s]

 17%|█▋        | 542/3268 [02:07<10:35,  4.29it/s]

 17%|█▋        | 543/3268 [02:08<10:35,  4.29it/s]

 17%|█▋        | 544/3268 [02:08<10:36,  4.28it/s]

 17%|█▋        | 545/3268 [02:08<10:35,  4.28it/s]

 17%|█▋        | 546/3268 [02:08<10:36,  4.28it/s]

 17%|█▋        | 547/3268 [02:09<10:35,  4.28it/s]

 17%|█▋        | 548/3268 [02:09<10:35,  4.28it/s]

 17%|█▋        | 549/3268 [02:09<10:36,  4.27it/s]

 17%|█▋        | 550/3268 [02:09<10:36,  4.27it/s]

 17%|█▋        | 551/3268 [02:09<10:35,  4.28it/s]

 17%|█▋        | 552/3268 [02:10<10:33,  4.28it/s]

 17%|█▋        | 553/3268 [02:10<10:33,  4.29it/s]

 17%|█▋        | 554/3268 [02:10<10:35,  4.27it/s]

 17%|█▋        | 555/3268 [02:10<10:34,  4.28it/s]

 17%|█▋        | 556/3268 [02:11<10:34,  4.27it/s]

 17%|█▋        | 557/3268 [02:11<10:33,  4.28it/s]

 17%|█▋        | 558/3268 [02:11<10:31,  4.29it/s]

 17%|█▋        | 559/3268 [02:11<10:30,  4.30it/s]

 17%|█▋        | 560/3268 [02:12<10:32,  4.28it/s]

 17%|█▋        | 561/3268 [02:12<10:33,  4.27it/s]

 17%|█▋        | 562/3268 [02:12<10:32,  4.28it/s]

 17%|█▋        | 563/3268 [02:12<10:31,  4.28it/s]

 17%|█▋        | 564/3268 [02:13<10:31,  4.28it/s]

 17%|█▋        | 565/3268 [02:13<10:30,  4.29it/s]

 17%|█▋        | 566/3268 [02:13<10:29,  4.29it/s]

 17%|█▋        | 567/3268 [02:13<10:30,  4.28it/s]

 17%|█▋        | 568/3268 [02:13<10:30,  4.28it/s]

 17%|█▋        | 569/3268 [02:14<10:29,  4.29it/s]

 17%|█▋        | 570/3268 [02:14<10:29,  4.29it/s]

 17%|█▋        | 571/3268 [02:14<10:30,  4.28it/s]

 18%|█▊        | 572/3268 [02:14<10:29,  4.28it/s]

 18%|█▊        | 573/3268 [02:15<10:29,  4.28it/s]

 18%|█▊        | 574/3268 [02:15<10:29,  4.28it/s]

 18%|█▊        | 575/3268 [02:15<10:28,  4.29it/s]

 18%|█▊        | 576/3268 [02:15<10:27,  4.29it/s]

 18%|█▊        | 577/3268 [02:16<10:26,  4.29it/s]

 18%|█▊        | 578/3268 [02:16<10:27,  4.29it/s]

 18%|█▊        | 579/3268 [02:16<10:27,  4.28it/s]

 18%|█▊        | 580/3268 [02:16<10:27,  4.28it/s]

 18%|█▊        | 581/3268 [02:16<10:28,  4.28it/s]

 18%|█▊        | 582/3268 [02:17<10:26,  4.28it/s]

 18%|█▊        | 583/3268 [02:17<10:27,  4.28it/s]

 18%|█▊        | 584/3268 [02:17<10:28,  4.27it/s]

 18%|█▊        | 585/3268 [02:17<10:27,  4.27it/s]

 18%|█▊        | 586/3268 [02:18<10:27,  4.27it/s]

 18%|█▊        | 587/3268 [02:18<10:25,  4.28it/s]

 18%|█▊        | 588/3268 [02:18<10:26,  4.28it/s]

 18%|█▊        | 589/3268 [02:18<10:27,  4.27it/s]

 18%|█▊        | 590/3268 [02:19<10:24,  4.29it/s]

 18%|█▊        | 591/3268 [02:19<10:23,  4.29it/s]

 18%|█▊        | 592/3268 [02:19<10:24,  4.29it/s]

 18%|█▊        | 593/3268 [02:19<10:24,  4.28it/s]

 18%|█▊        | 594/3268 [02:20<10:25,  4.28it/s]

 18%|█▊        | 595/3268 [02:20<10:25,  4.27it/s]

 18%|█▊        | 596/3268 [02:20<10:25,  4.27it/s]

 18%|█▊        | 597/3268 [02:20<10:23,  4.28it/s]

 18%|█▊        | 598/3268 [02:20<10:22,  4.29it/s]

 18%|█▊        | 599/3268 [02:21<10:24,  4.27it/s]

 18%|█▊        | 600/3268 [02:21<10:22,  4.29it/s]

 18%|█▊        | 601/3268 [02:21<10:23,  4.28it/s]

 18%|█▊        | 602/3268 [02:21<10:24,  4.27it/s]

 18%|█▊        | 603/3268 [02:22<10:24,  4.27it/s]

 18%|█▊        | 604/3268 [02:22<10:22,  4.28it/s]

 19%|█▊        | 605/3268 [02:22<10:20,  4.29it/s]

 19%|█▊        | 606/3268 [02:22<10:21,  4.28it/s]

 19%|█▊        | 607/3268 [02:23<10:27,  4.24it/s]

 19%|█▊        | 608/3268 [02:23<10:25,  4.25it/s]

 19%|█▊        | 609/3268 [02:23<10:25,  4.25it/s]

 19%|█▊        | 610/3268 [02:23<10:23,  4.27it/s]

 19%|█▊        | 611/3268 [02:23<10:22,  4.26it/s]

 19%|█▊        | 612/3268 [02:24<10:23,  4.26it/s]

 19%|█▉        | 613/3268 [02:24<10:23,  4.26it/s]

 19%|█▉        | 614/3268 [02:24<10:23,  4.26it/s]

 19%|█▉        | 615/3268 [02:24<10:20,  4.27it/s]

 19%|█▉        | 616/3268 [02:25<10:20,  4.27it/s]

 19%|█▉        | 617/3268 [02:25<10:20,  4.27it/s]

 19%|█▉        | 618/3268 [02:25<10:20,  4.27it/s]

 19%|█▉        | 619/3268 [02:25<10:21,  4.26it/s]

 19%|█▉        | 620/3268 [02:26<10:20,  4.27it/s]

 19%|█▉        | 621/3268 [02:26<10:20,  4.27it/s]

 19%|█▉        | 622/3268 [02:26<10:21,  4.26it/s]

 19%|█▉        | 623/3268 [02:26<10:19,  4.27it/s]

 19%|█▉        | 624/3268 [02:27<10:19,  4.27it/s]

 19%|█▉        | 625/3268 [02:27<10:18,  4.27it/s]

logging
logging the anndata

 19%|█▉        | 626/3268 [02:29<30:30,  1.44it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 19%|█▉        | 627/3268 [02:29<24:21,  1.81it/s]

 19%|█▉        | 628/3268 [02:29<20:01,  2.20it/s]

 19%|█▉        | 629/3268 [02:29<16:59,  2.59it/s]

 19%|█▉        | 630/3268 [02:29<14:52,  2.95it/s]

 19%|█▉        | 631/3268 [02:30<13:24,  3.28it/s]

 19%|█▉        | 632/3268 [02:30<12:23,  3.55it/s]

 19%|█▉        | 633/3268 [02:30<11:39,  3.77it/s]

 19%|█▉        | 634/3268 [02:30<11:08,  3.94it/s]

 19%|█▉        | 635/3268 [02:31<10:47,  4.06it/s]

 19%|█▉        | 636/3268 [02:31<10:33,  4.15it/s]

 19%|█▉        | 637/3268 [02:31<10:24,  4.21it/s]

 20%|█▉        | 638/3268 [02:31<10:17,  4.26it/s]

 20%|█▉        | 639/3268 [02:32<10:17,  4.26it/s]

 20%|█▉        | 640/3268 [02:32<10:12,  4.29it/s]

 20%|█▉        | 641/3268 [02:32<10:08,  4.32it/s]

 20%|█▉        | 642/3268 [02:32<10:05,  4.33it/s]

 20%|█▉        | 643/3268 [02:32<10:02,  4.36it/s]

 20%|█▉        | 644/3268 [02:33<09:59,  4.37it/s]

 20%|█▉        | 645/3268 [02:33<09:59,  4.37it/s]

 20%|█▉        | 646/3268 [02:33<09:59,  4.37it/s]

 20%|█▉        | 647/3268 [02:33<09:57,  4.39it/s]

 20%|█▉        | 648/3268 [02:34<09:57,  4.38it/s]

 20%|█▉        | 649/3268 [02:34<09:57,  4.39it/s]

 20%|█▉        | 650/3268 [02:34<09:55,  4.40it/s]

 20%|█▉        | 651/3268 [02:34<09:55,  4.39it/s]

 20%|█▉        | 652/3268 [02:34<09:57,  4.38it/s]

 20%|█▉        | 653/3268 [02:35<09:57,  4.38it/s]

 20%|██        | 654/3268 [02:35<09:57,  4.37it/s]

 20%|██        | 655/3268 [02:35<09:57,  4.37it/s]

 20%|██        | 656/3268 [02:35<09:57,  4.37it/s]

 20%|██        | 657/3268 [02:36<09:58,  4.36it/s]

 20%|██        | 658/3268 [02:36<09:56,  4.38it/s]

 20%|██        | 659/3268 [02:36<09:56,  4.37it/s]

 20%|██        | 660/3268 [02:36<09:56,  4.37it/s]

 20%|██        | 661/3268 [02:37<09:55,  4.38it/s]

 20%|██        | 662/3268 [02:37<09:55,  4.38it/s]

 20%|██        | 663/3268 [02:37<09:54,  4.38it/s]

 20%|██        | 664/3268 [02:37<09:54,  4.38it/s]

 20%|██        | 665/3268 [02:37<09:53,  4.38it/s]

 20%|██        | 666/3268 [02:38<09:52,  4.39it/s]

 20%|██        | 667/3268 [02:38<09:52,  4.39it/s]

 20%|██        | 668/3268 [02:38<09:52,  4.39it/s]

 20%|██        | 669/3268 [02:38<09:52,  4.39it/s]

 21%|██        | 670/3268 [02:39<09:51,  4.39it/s]

 21%|██        | 671/3268 [02:39<09:51,  4.39it/s]

 21%|██        | 672/3268 [02:39<09:51,  4.39it/s]

 21%|██        | 673/3268 [02:39<09:53,  4.37it/s]

 21%|██        | 674/3268 [02:39<09:52,  4.38it/s]

 21%|██        | 675/3268 [02:40<09:58,  4.33it/s]

 21%|██        | 676/3268 [02:40<09:57,  4.34it/s]

 21%|██        | 677/3268 [02:40<09:55,  4.35it/s]

 21%|██        | 678/3268 [02:40<09:54,  4.36it/s]

 21%|██        | 679/3268 [02:41<09:52,  4.37it/s]

 21%|██        | 680/3268 [02:41<09:51,  4.38it/s]

 21%|██        | 681/3268 [02:41<09:50,  4.38it/s]

 21%|██        | 682/3268 [02:41<09:50,  4.38it/s]

 21%|██        | 683/3268 [02:42<09:48,  4.39it/s]

 21%|██        | 684/3268 [02:42<09:48,  4.39it/s]

 21%|██        | 685/3268 [02:42<09:48,  4.39it/s]

 21%|██        | 686/3268 [02:42<09:47,  4.40it/s]

 21%|██        | 687/3268 [02:42<09:47,  4.40it/s]

 21%|██        | 688/3268 [02:43<09:48,  4.39it/s]

 21%|██        | 689/3268 [02:43<09:48,  4.38it/s]

 21%|██        | 690/3268 [02:43<09:48,  4.38it/s]

 21%|██        | 691/3268 [02:43<09:47,  4.39it/s]

 21%|██        | 692/3268 [02:44<09:47,  4.39it/s]

 21%|██        | 693/3268 [02:44<09:47,  4.38it/s]

 21%|██        | 694/3268 [02:44<09:46,  4.39it/s]

 21%|██▏       | 695/3268 [02:44<09:46,  4.38it/s]

 21%|██▏       | 696/3268 [02:45<09:46,  4.39it/s]

 21%|██▏       | 697/3268 [02:45<09:45,  4.39it/s]

 21%|██▏       | 698/3268 [02:45<09:47,  4.37it/s]

 21%|██▏       | 699/3268 [02:45<09:46,  4.38it/s]

 21%|██▏       | 700/3268 [02:45<09:46,  4.38it/s]

 21%|██▏       | 701/3268 [02:46<09:46,  4.38it/s]

 21%|██▏       | 702/3268 [02:46<09:45,  4.38it/s]

 22%|██▏       | 703/3268 [02:46<09:45,  4.38it/s]

 22%|██▏       | 704/3268 [02:46<09:46,  4.37it/s]

 22%|██▏       | 705/3268 [02:47<09:46,  4.37it/s]

 22%|██▏       | 706/3268 [02:47<09:45,  4.37it/s]

 22%|██▏       | 707/3268 [02:47<09:46,  4.37it/s]

 22%|██▏       | 708/3268 [02:47<09:44,  4.38it/s]

 22%|██▏       | 709/3268 [02:47<09:43,  4.39it/s]

 22%|██▏       | 710/3268 [02:48<09:43,  4.38it/s]

 22%|██▏       | 711/3268 [02:48<09:44,  4.37it/s]

 22%|██▏       | 712/3268 [02:48<09:43,  4.38it/s]

 22%|██▏       | 713/3268 [02:48<09:43,  4.38it/s]

 22%|██▏       | 714/3268 [02:49<09:43,  4.38it/s]

 22%|██▏       | 715/3268 [02:49<09:42,  4.38it/s]

 22%|██▏       | 716/3268 [02:49<09:42,  4.38it/s]

 22%|██▏       | 717/3268 [02:49<09:43,  4.38it/s]

 22%|██▏       | 718/3268 [02:50<09:42,  4.37it/s]

 22%|██▏       | 719/3268 [02:50<09:42,  4.38it/s]

 22%|██▏       | 720/3268 [02:50<09:41,  4.38it/s]

 22%|██▏       | 721/3268 [02:50<09:41,  4.38it/s]

 22%|██▏       | 722/3268 [02:50<09:40,  4.38it/s]

 22%|██▏       | 723/3268 [02:51<09:41,  4.38it/s]

 22%|██▏       | 724/3268 [02:51<09:41,  4.38it/s]

 22%|██▏       | 725/3268 [02:51<09:41,  4.37it/s]

 22%|██▏       | 726/3268 [02:51<09:41,  4.37it/s]

 22%|██▏       | 727/3268 [02:52<09:40,  4.38it/s]

 22%|██▏       | 728/3268 [02:52<09:40,  4.37it/s]

 22%|██▏       | 729/3268 [02:52<09:41,  4.37it/s]

 22%|██▏       | 730/3268 [02:52<09:41,  4.37it/s]

 22%|██▏       | 731/3268 [02:53<09:40,  4.37it/s]

 22%|██▏       | 732/3268 [02:53<09:40,  4.37it/s]

 22%|██▏       | 733/3268 [02:53<09:39,  4.37it/s]

 22%|██▏       | 734/3268 [02:53<09:41,  4.36it/s]

 22%|██▏       | 735/3268 [02:53<09:41,  4.35it/s]

 23%|██▎       | 736/3268 [02:54<09:39,  4.37it/s]

 23%|██▎       | 737/3268 [02:54<09:38,  4.37it/s]

 23%|██▎       | 738/3268 [02:54<09:37,  4.38it/s]

 23%|██▎       | 739/3268 [02:54<09:36,  4.39it/s]

 23%|██▎       | 740/3268 [02:55<09:36,  4.39it/s]

 23%|██▎       | 741/3268 [02:55<09:35,  4.39it/s]

 23%|██▎       | 742/3268 [02:55<09:35,  4.39it/s]

 23%|██▎       | 743/3268 [02:55<09:36,  4.38it/s]

 23%|██▎       | 744/3268 [02:55<09:34,  4.39it/s]

 23%|██▎       | 745/3268 [02:56<09:35,  4.39it/s]

 23%|██▎       | 746/3268 [02:56<09:39,  4.36it/s]

 23%|██▎       | 747/3268 [02:56<09:36,  4.37it/s]

 23%|██▎       | 748/3268 [02:56<09:36,  4.37it/s]

 23%|██▎       | 749/3268 [02:57<09:35,  4.38it/s]

 23%|██▎       | 750/3268 [02:57<09:35,  4.38it/s]

 23%|██▎       | 751/3268 [02:57<09:34,  4.38it/s]

 23%|██▎       | 752/3268 [02:57<09:34,  4.38it/s]

 23%|██▎       | 753/3268 [02:58<09:34,  4.38it/s]

 23%|██▎       | 754/3268 [02:58<09:35,  4.37it/s]

 23%|██▎       | 755/3268 [02:58<09:34,  4.37it/s]

 23%|██▎       | 756/3268 [02:58<09:33,  4.38it/s]

 23%|██▎       | 757/3268 [02:58<09:32,  4.39it/s]

 23%|██▎       | 758/3268 [02:59<09:32,  4.39it/s]

 23%|██▎       | 759/3268 [02:59<09:32,  4.38it/s]

 23%|██▎       | 760/3268 [02:59<09:32,  4.38it/s]

 23%|██▎       | 761/3268 [02:59<09:33,  4.37it/s]

 23%|██▎       | 762/3268 [03:00<09:33,  4.37it/s]

 23%|██▎       | 763/3268 [03:00<09:33,  4.37it/s]

 23%|██▎       | 764/3268 [03:00<09:33,  4.37it/s]

 23%|██▎       | 765/3268 [03:00<09:34,  4.36it/s]

 23%|██▎       | 766/3268 [03:01<09:33,  4.36it/s]

 23%|██▎       | 767/3268 [03:01<09:33,  4.36it/s]

 24%|██▎       | 768/3268 [03:01<09:34,  4.36it/s]

 24%|██▎       | 769/3268 [03:01<09:34,  4.35it/s]

 24%|██▎       | 770/3268 [03:01<09:35,  4.34it/s]

 24%|██▎       | 771/3268 [03:02<09:34,  4.35it/s]

 24%|██▎       | 772/3268 [03:02<09:33,  4.35it/s]

 24%|██▎       | 773/3268 [03:02<09:33,  4.35it/s]

 24%|██▎       | 774/3268 [03:02<09:33,  4.35it/s]

 24%|██▎       | 775/3268 [03:03<09:32,  4.35it/s]

 24%|██▎       | 776/3268 [03:03<09:31,  4.36it/s]

 24%|██▍       | 777/3268 [03:03<09:31,  4.36it/s]

 24%|██▍       | 778/3268 [03:03<09:31,  4.36it/s]

 24%|██▍       | 779/3268 [03:04<09:32,  4.35it/s]

 24%|██▍       | 780/3268 [03:04<09:31,  4.36it/s]

 24%|██▍       | 781/3268 [03:04<09:30,  4.36it/s]

 24%|██▍       | 782/3268 [03:04<09:29,  4.37it/s]

 24%|██▍       | 783/3268 [03:04<09:30,  4.36it/s]

 24%|██▍       | 784/3268 [03:05<09:30,  4.36it/s]

 24%|██▍       | 785/3268 [03:05<09:29,  4.36it/s]

 24%|██▍       | 786/3268 [03:05<09:29,  4.36it/s]

 24%|██▍       | 787/3268 [03:05<09:28,  4.36it/s]

 24%|██▍       | 788/3268 [03:06<09:28,  4.36it/s]

 24%|██▍       | 789/3268 [03:06<09:28,  4.36it/s]

 24%|██▍       | 790/3268 [03:06<09:28,  4.36it/s]

 24%|██▍       | 791/3268 [03:06<09:28,  4.36it/s]

 24%|██▍       | 792/3268 [03:06<09:28,  4.36it/s]

 24%|██▍       | 793/3268 [03:07<09:27,  4.36it/s]

 24%|██▍       | 794/3268 [03:07<09:27,  4.36it/s]

 24%|██▍       | 795/3268 [03:07<09:27,  4.36it/s]

 24%|██▍       | 796/3268 [03:07<09:28,  4.35it/s]

 24%|██▍       | 797/3268 [03:08<09:28,  4.35it/s]

 24%|██▍       | 798/3268 [03:08<09:28,  4.34it/s]

 24%|██▍       | 799/3268 [03:08<09:27,  4.35it/s]

 24%|██▍       | 800/3268 [03:08<09:27,  4.35it/s]

 25%|██▍       | 801/3268 [03:09<09:25,  4.36it/s]

 25%|██▍       | 802/3268 [03:09<09:25,  4.36it/s]

 25%|██▍       | 803/3268 [03:09<09:25,  4.36it/s]

 25%|██▍       | 804/3268 [03:09<09:24,  4.36it/s]

 25%|██▍       | 805/3268 [03:09<09:25,  4.36it/s]

 25%|██▍       | 806/3268 [03:10<09:24,  4.36it/s]

 25%|██▍       | 807/3268 [03:10<09:24,  4.36it/s]

 25%|██▍       | 808/3268 [03:10<09:24,  4.36it/s]

 25%|██▍       | 809/3268 [03:10<09:24,  4.36it/s]

 25%|██▍       | 810/3268 [03:11<09:25,  4.34it/s]

 25%|██▍       | 811/3268 [03:11<09:25,  4.34it/s]

 25%|██▍       | 812/3268 [03:11<09:23,  4.35it/s]

 25%|██▍       | 813/3268 [03:11<09:23,  4.36it/s]

 25%|██▍       | 814/3268 [03:12<09:22,  4.36it/s]

 25%|██▍       | 815/3268 [03:12<09:23,  4.35it/s]

 25%|██▍       | 816/3268 [03:12<09:24,  4.34it/s]

 25%|██▌       | 817/3268 [03:12<09:26,  4.33it/s]

 25%|██▌       | 818/3268 [03:12<09:25,  4.34it/s]

 25%|██▌       | 819/3268 [03:13<09:24,  4.34it/s]

 25%|██▌       | 820/3268 [03:13<09:23,  4.35it/s]

 25%|██▌       | 821/3268 [03:13<09:22,  4.35it/s]

 25%|██▌       | 822/3268 [03:13<09:22,  4.35it/s]

 25%|██▌       | 823/3268 [03:14<09:20,  4.36it/s]

 25%|██▌       | 824/3268 [03:14<09:21,  4.35it/s]

 25%|██▌       | 825/3268 [03:14<09:20,  4.36it/s]

 25%|██▌       | 826/3268 [03:14<09:21,  4.35it/s]

 25%|██▌       | 827/3268 [03:15<09:20,  4.36it/s]

 25%|██▌       | 828/3268 [03:15<09:21,  4.35it/s]

 25%|██▌       | 829/3268 [03:15<09:20,  4.35it/s]

 25%|██▌       | 830/3268 [03:15<09:21,  4.34it/s]

 25%|██▌       | 831/3268 [03:15<09:21,  4.34it/s]

 25%|██▌       | 832/3268 [03:16<09:20,  4.35it/s]

 25%|██▌       | 833/3268 [03:16<09:21,  4.34it/s]

 26%|██▌       | 834/3268 [03:16<09:20,  4.34it/s]

 26%|██▌       | 835/3268 [03:16<09:20,  4.34it/s]

 26%|██▌       | 836/3268 [03:17<09:20,  4.34it/s]

 26%|██▌       | 837/3268 [03:17<09:19,  4.34it/s]

 26%|██▌       | 838/3268 [03:17<09:19,  4.34it/s]

 26%|██▌       | 839/3268 [03:17<09:19,  4.34it/s]

 26%|██▌       | 840/3268 [03:18<09:18,  4.35it/s]

 26%|██▌       | 841/3268 [03:18<09:18,  4.34it/s]

 26%|██▌       | 842/3268 [03:18<09:17,  4.35it/s]

 26%|██▌       | 843/3268 [03:18<09:17,  4.35it/s]

 26%|██▌       | 844/3268 [03:18<09:17,  4.35it/s]

 26%|██▌       | 845/3268 [03:19<09:17,  4.35it/s]

 26%|██▌       | 846/3268 [03:19<09:17,  4.35it/s]

 26%|██▌       | 847/3268 [03:19<09:17,  4.34it/s]

 26%|██▌       | 848/3268 [03:19<09:16,  4.35it/s]

 26%|██▌       | 849/3268 [03:20<09:16,  4.35it/s]

 26%|██▌       | 850/3268 [03:20<09:16,  4.35it/s]

 26%|██▌       | 851/3268 [03:20<09:16,  4.34it/s]

 26%|██▌       | 852/3268 [03:20<09:16,  4.34it/s]

 26%|██▌       | 853/3268 [03:21<09:15,  4.35it/s]

 26%|██▌       | 854/3268 [03:21<09:16,  4.34it/s]

 26%|██▌       | 855/3268 [03:21<09:15,  4.35it/s]

 26%|██▌       | 856/3268 [03:21<09:17,  4.33it/s]

 26%|██▌       | 857/3268 [03:21<09:17,  4.32it/s]

 26%|██▋       | 858/3268 [03:22<09:17,  4.32it/s]

 26%|██▋       | 859/3268 [03:22<09:15,  4.34it/s]

 26%|██▋       | 860/3268 [03:22<09:14,  4.34it/s]

 26%|██▋       | 861/3268 [03:22<09:14,  4.34it/s]

 26%|██▋       | 862/3268 [03:23<09:13,  4.35it/s]

 26%|██▋       | 863/3268 [03:23<09:12,  4.35it/s]

 26%|██▋       | 864/3268 [03:23<09:12,  4.35it/s]

 26%|██▋       | 865/3268 [03:23<09:12,  4.35it/s]

 26%|██▋       | 866/3268 [03:24<09:12,  4.34it/s]

 27%|██▋       | 867/3268 [03:24<09:12,  4.34it/s]

 27%|██▋       | 868/3268 [03:24<09:12,  4.35it/s]

 27%|██▋       | 869/3268 [03:24<09:12,  4.34it/s]

 27%|██▋       | 870/3268 [03:24<09:11,  4.35it/s]

 27%|██▋       | 871/3268 [03:25<09:11,  4.35it/s]

 27%|██▋       | 872/3268 [03:25<09:11,  4.35it/s]

 27%|██▋       | 873/3268 [03:25<09:10,  4.35it/s]

 27%|██▋       | 874/3268 [03:25<09:11,  4.34it/s]

 27%|██▋       | 875/3268 [03:26<09:11,  4.34it/s]

 27%|██▋       | 876/3268 [03:26<09:12,  4.33it/s]

 27%|██▋       | 877/3268 [03:26<09:14,  4.31it/s]

 27%|██▋       | 878/3268 [03:26<09:12,  4.33it/s]

 27%|██▋       | 879/3268 [03:27<09:11,  4.34it/s]

 27%|██▋       | 880/3268 [03:27<09:10,  4.34it/s]

 27%|██▋       | 881/3268 [03:27<09:08,  4.35it/s]

 27%|██▋       | 882/3268 [03:27<09:08,  4.35it/s]

 27%|██▋       | 883/3268 [03:27<09:10,  4.33it/s]

 27%|██▋       | 884/3268 [03:28<09:09,  4.34it/s]

 27%|██▋       | 885/3268 [03:28<09:09,  4.34it/s]

 27%|██▋       | 886/3268 [03:28<09:07,  4.35it/s]

 27%|██▋       | 887/3268 [03:28<09:05,  4.36it/s]

 27%|██▋       | 888/3268 [03:29<09:05,  4.37it/s]

 27%|██▋       | 889/3268 [03:29<09:03,  4.38it/s]

 27%|██▋       | 890/3268 [03:29<09:03,  4.38it/s]

 27%|██▋       | 891/3268 [03:29<09:03,  4.38it/s]

 27%|██▋       | 892/3268 [03:29<09:03,  4.37it/s]

 27%|██▋       | 893/3268 [03:30<09:05,  4.36it/s]

 27%|██▋       | 894/3268 [03:30<09:05,  4.35it/s]

 27%|██▋       | 895/3268 [03:30<09:05,  4.35it/s]

 27%|██▋       | 896/3268 [03:30<09:06,  4.34it/s]

 27%|██▋       | 897/3268 [03:31<09:06,  4.34it/s]

 27%|██▋       | 898/3268 [03:31<09:06,  4.33it/s]

 28%|██▊       | 899/3268 [03:31<09:06,  4.33it/s]

 28%|██▊       | 900/3268 [03:31<09:04,  4.35it/s]

 28%|██▊       | 901/3268 [03:32<09:04,  4.35it/s]

 28%|██▊       | 902/3268 [03:32<09:04,  4.34it/s]

 28%|██▊       | 903/3268 [03:32<09:03,  4.35it/s]

 28%|██▊       | 904/3268 [03:32<09:04,  4.34it/s]

 28%|██▊       | 905/3268 [03:32<09:03,  4.35it/s]

 28%|██▊       | 906/3268 [03:33<09:02,  4.35it/s]

 28%|██▊       | 907/3268 [03:33<09:04,  4.34it/s]

 28%|██▊       | 908/3268 [03:33<09:03,  4.34it/s]

 28%|██▊       | 909/3268 [03:33<09:03,  4.34it/s]

 28%|██▊       | 910/3268 [03:34<09:02,  4.34it/s]

 28%|██▊       | 911/3268 [03:34<09:01,  4.35it/s]

 28%|██▊       | 912/3268 [03:34<09:00,  4.36it/s]

 28%|██▊       | 913/3268 [03:34<09:00,  4.35it/s]

 28%|██▊       | 914/3268 [03:35<09:00,  4.35it/s]

 28%|██▊       | 915/3268 [03:35<09:01,  4.35it/s]

 28%|██▊       | 916/3268 [03:35<09:00,  4.35it/s]

 28%|██▊       | 917/3268 [03:35<09:00,  4.35it/s]

 28%|██▊       | 918/3268 [03:35<09:00,  4.35it/s]

 28%|██▊       | 919/3268 [03:36<09:01,  4.34it/s]

 28%|██▊       | 920/3268 [03:36<08:59,  4.35it/s]

 28%|██▊       | 921/3268 [03:36<08:59,  4.35it/s]

 28%|██▊       | 922/3268 [03:36<08:59,  4.35it/s]

 28%|██▊       | 923/3268 [03:37<08:58,  4.35it/s]

 28%|██▊       | 924/3268 [03:37<08:59,  4.35it/s]

 28%|██▊       | 925/3268 [03:37<08:58,  4.35it/s]

 28%|██▊       | 926/3268 [03:37<08:58,  4.35it/s]

 28%|██▊       | 927/3268 [03:38<08:58,  4.35it/s]

 28%|██▊       | 928/3268 [03:38<09:00,  4.33it/s]

 28%|██▊       | 929/3268 [03:38<08:59,  4.33it/s]

 28%|██▊       | 930/3268 [03:38<08:58,  4.34it/s]

 28%|██▊       | 931/3268 [03:38<08:57,  4.35it/s]

 29%|██▊       | 932/3268 [03:39<08:56,  4.36it/s]

 29%|██▊       | 933/3268 [03:39<08:55,  4.36it/s]

 29%|██▊       | 934/3268 [03:39<08:55,  4.36it/s]

 29%|██▊       | 935/3268 [03:39<08:54,  4.36it/s]

 29%|██▊       | 936/3268 [03:40<08:54,  4.36it/s]

 29%|██▊       | 937/3268 [03:40<08:54,  4.36it/s]

 29%|██▊       | 938/3268 [03:40<08:55,  4.35it/s]

 29%|██▊       | 939/3268 [03:40<08:55,  4.35it/s]

 29%|██▉       | 940/3268 [03:41<08:54,  4.35it/s]

 29%|██▉       | 941/3268 [03:41<08:54,  4.36it/s]

 29%|██▉       | 942/3268 [03:41<08:53,  4.36it/s]

 29%|██▉       | 943/3268 [03:41<08:53,  4.36it/s]

 29%|██▉       | 944/3268 [03:41<08:52,  4.36it/s]

 29%|██▉       | 945/3268 [03:42<08:52,  4.36it/s]

 29%|██▉       | 946/3268 [03:42<08:51,  4.37it/s]

 29%|██▉       | 947/3268 [03:42<08:52,  4.36it/s]

 29%|██▉       | 948/3268 [03:42<08:52,  4.36it/s]

 29%|██▉       | 949/3268 [03:43<08:53,  4.34it/s]

 29%|██▉       | 950/3268 [03:43<08:54,  4.33it/s]

 29%|██▉       | 951/3268 [03:43<08:53,  4.34it/s]

 29%|██▉       | 952/3268 [03:43<08:52,  4.35it/s]

 29%|██▉       | 953/3268 [03:44<08:53,  4.34it/s]

 29%|██▉       | 954/3268 [03:44<08:52,  4.35it/s]

 29%|██▉       | 955/3268 [03:44<08:51,  4.35it/s]

 29%|██▉       | 956/3268 [03:44<08:52,  4.34it/s]

 29%|██▉       | 957/3268 [03:44<08:52,  4.34it/s]

 29%|██▉       | 958/3268 [03:45<08:52,  4.34it/s]

 29%|██▉       | 959/3268 [03:45<08:50,  4.35it/s]

 29%|██▉       | 960/3268 [03:45<08:51,  4.35it/s]

 29%|██▉       | 961/3268 [03:45<08:51,  4.34it/s]

 29%|██▉       | 962/3268 [03:46<08:50,  4.34it/s]

 29%|██▉       | 963/3268 [03:46<08:50,  4.35it/s]

 29%|██▉       | 964/3268 [03:46<08:52,  4.32it/s]

 30%|██▉       | 965/3268 [03:46<08:51,  4.33it/s]

 30%|██▉       | 966/3268 [03:47<08:50,  4.34it/s]

 30%|██▉       | 967/3268 [03:47<08:49,  4.35it/s]

 30%|██▉       | 968/3268 [03:47<08:49,  4.35it/s]

 30%|██▉       | 969/3268 [03:47<08:48,  4.35it/s]

 30%|██▉       | 970/3268 [03:47<08:47,  4.35it/s]

 30%|██▉       | 971/3268 [03:48<08:48,  4.35it/s]

 30%|██▉       | 972/3268 [03:48<08:50,  4.32it/s]

 30%|██▉       | 973/3268 [03:48<08:49,  4.34it/s]

 30%|██▉       | 974/3268 [03:48<08:47,  4.34it/s]

 30%|██▉       | 975/3268 [03:49<08:47,  4.35it/s]

 30%|██▉       | 976/3268 [03:49<08:46,  4.35it/s]

 30%|██▉       | 977/3268 [03:49<08:46,  4.35it/s]

 30%|██▉       | 978/3268 [03:49<08:46,  4.35it/s]

 30%|██▉       | 979/3268 [03:49<08:46,  4.34it/s]

 30%|██▉       | 980/3268 [03:50<08:46,  4.34it/s]

 30%|███       | 981/3268 [03:50<08:46,  4.35it/s]

 30%|███       | 982/3268 [03:50<08:46,  4.34it/s]

 30%|███       | 983/3268 [03:50<08:45,  4.34it/s]

 30%|███       | 984/3268 [03:51<08:46,  4.34it/s]

 30%|███       | 985/3268 [03:51<08:46,  4.33it/s]

 30%|███       | 986/3268 [03:51<08:45,  4.34it/s]

 30%|███       | 987/3268 [03:51<08:46,  4.34it/s]

 30%|███       | 988/3268 [03:52<08:45,  4.34it/s]

 30%|███       | 989/3268 [03:52<08:46,  4.33it/s]

 30%|███       | 990/3268 [03:52<08:45,  4.33it/s]

 30%|███       | 991/3268 [03:52<08:45,  4.34it/s]

 30%|███       | 992/3268 [03:52<08:44,  4.34it/s]

 30%|███       | 993/3268 [03:53<08:44,  4.34it/s]

 30%|███       | 994/3268 [03:53<08:43,  4.34it/s]

 30%|███       | 995/3268 [03:53<08:43,  4.34it/s]

 30%|███       | 996/3268 [03:53<08:42,  4.34it/s]

 31%|███       | 997/3268 [03:54<08:43,  4.34it/s]

 31%|███       | 998/3268 [03:54<08:43,  4.34it/s]

 31%|███       | 999/3268 [03:54<08:43,  4.34it/s]

 31%|███       | 1000/3268 [03:54<08:42,  4.34it/s]

 31%|███       | 1001/3268 [03:55<08:42,  4.34it/s]

 31%|███       | 1002/3268 [03:55<08:41,  4.34it/s]

 31%|███       | 1003/3268 [03:55<08:41,  4.34it/s]

 31%|███       | 1004/3268 [03:55<08:41,  4.34it/s]

 31%|███       | 1005/3268 [03:55<08:40,  4.35it/s]

 31%|███       | 1006/3268 [03:56<08:40,  4.35it/s]

 31%|███       | 1007/3268 [03:56<08:41,  4.34it/s]

 31%|███       | 1008/3268 [03:56<08:40,  4.34it/s]

 31%|███       | 1009/3268 [03:56<08:41,  4.34it/s]

 31%|███       | 1010/3268 [03:57<08:40,  4.34it/s]

 31%|███       | 1011/3268 [03:57<08:40,  4.33it/s]

 31%|███       | 1012/3268 [03:57<08:40,  4.33it/s]

 31%|███       | 1013/3268 [03:57<08:40,  4.33it/s]

 31%|███       | 1014/3268 [03:58<08:39,  4.34it/s]

 31%|███       | 1015/3268 [03:58<08:41,  4.32it/s]

 31%|███       | 1016/3268 [03:58<08:40,  4.33it/s]

 31%|███       | 1017/3268 [03:58<08:39,  4.33it/s]

 31%|███       | 1018/3268 [03:58<08:39,  4.33it/s]

 31%|███       | 1019/3268 [03:59<08:39,  4.33it/s]

 31%|███       | 1020/3268 [03:59<08:39,  4.33it/s]

 31%|███       | 1021/3268 [03:59<08:38,  4.33it/s]

 31%|███▏      | 1022/3268 [03:59<08:38,  4.33it/s]

 31%|███▏      | 1023/3268 [04:00<08:38,  4.33it/s]

 31%|███▏      | 1024/3268 [04:00<08:38,  4.33it/s]

 31%|███▏      | 1025/3268 [04:00<08:38,  4.33it/s]

 31%|███▏      | 1026/3268 [04:00<08:37,  4.33it/s]

 31%|███▏      | 1027/3268 [04:01<08:37,  4.33it/s]

 31%|███▏      | 1028/3268 [04:01<08:39,  4.31it/s]

 31%|███▏      | 1029/3268 [04:01<08:38,  4.31it/s]

 32%|███▏      | 1030/3268 [04:01<08:38,  4.32it/s]

 32%|███▏      | 1031/3268 [04:01<08:37,  4.32it/s]

 32%|███▏      | 1032/3268 [04:02<08:37,  4.32it/s]

 32%|███▏      | 1033/3268 [04:02<08:37,  4.32it/s]

 32%|███▏      | 1034/3268 [04:02<08:35,  4.33it/s]

 32%|███▏      | 1035/3268 [04:02<08:36,  4.32it/s]

 32%|███▏      | 1036/3268 [04:03<08:36,  4.32it/s]

 32%|███▏      | 1037/3268 [04:03<08:35,  4.33it/s]

 32%|███▏      | 1038/3268 [04:03<08:35,  4.32it/s]

 32%|███▏      | 1039/3268 [04:03<08:35,  4.32it/s]

 32%|███▏      | 1040/3268 [04:04<08:35,  4.33it/s]

 32%|███▏      | 1041/3268 [04:04<08:34,  4.33it/s]

 32%|███▏      | 1042/3268 [04:04<08:35,  4.32it/s]

 32%|███▏      | 1043/3268 [04:04<08:35,  4.32it/s]

 32%|███▏      | 1044/3268 [04:04<08:35,  4.32it/s]

 32%|███▏      | 1045/3268 [04:05<08:34,  4.32it/s]

 32%|███▏      | 1046/3268 [04:05<08:35,  4.31it/s]

 32%|███▏      | 1047/3268 [04:05<08:34,  4.32it/s]

 32%|███▏      | 1048/3268 [04:05<08:35,  4.31it/s]

 32%|███▏      | 1049/3268 [04:06<08:35,  4.31it/s]

 32%|███▏      | 1050/3268 [04:06<08:34,  4.31it/s]

 32%|███▏      | 1051/3268 [04:06<08:34,  4.31it/s]

 32%|███▏      | 1052/3268 [04:06<08:35,  4.30it/s]

 32%|███▏      | 1053/3268 [04:07<08:34,  4.31it/s]

 32%|███▏      | 1054/3268 [04:07<08:34,  4.31it/s]

 32%|███▏      | 1055/3268 [04:07<08:34,  4.30it/s]

 32%|███▏      | 1056/3268 [04:07<08:34,  4.30it/s]

 32%|███▏      | 1057/3268 [04:08<08:34,  4.30it/s]

 32%|███▏      | 1058/3268 [04:08<08:32,  4.31it/s]

 32%|███▏      | 1059/3268 [04:08<08:31,  4.32it/s]

 32%|███▏      | 1060/3268 [04:08<08:31,  4.32it/s]

 32%|███▏      | 1061/3268 [04:08<08:31,  4.32it/s]

 32%|███▏      | 1062/3268 [04:09<08:30,  4.32it/s]

 33%|███▎      | 1063/3268 [04:09<08:28,  4.34it/s]

 33%|███▎      | 1064/3268 [04:09<08:27,  4.34it/s]

 33%|███▎      | 1065/3268 [04:09<08:29,  4.33it/s]

 33%|███▎      | 1066/3268 [04:10<08:29,  4.32it/s]

 33%|███▎      | 1067/3268 [04:10<08:29,  4.32it/s]

 33%|███▎      | 1068/3268 [04:10<08:29,  4.32it/s]

 33%|███▎      | 1069/3268 [04:10<08:29,  4.32it/s]

 33%|███▎      | 1070/3268 [04:11<08:29,  4.31it/s]

 33%|███▎      | 1071/3268 [04:11<08:29,  4.31it/s]

 33%|███▎      | 1072/3268 [04:11<08:28,  4.32it/s]

 33%|███▎      | 1073/3268 [04:11<08:28,  4.31it/s]

 33%|███▎      | 1074/3268 [04:11<08:28,  4.31it/s]

 33%|███▎      | 1075/3268 [04:12<08:29,  4.31it/s]

 33%|███▎      | 1076/3268 [04:12<08:28,  4.31it/s]

 33%|███▎      | 1077/3268 [04:12<08:26,  4.32it/s]

 33%|███▎      | 1078/3268 [04:12<08:26,  4.32it/s]

 33%|███▎      | 1079/3268 [04:13<08:25,  4.33it/s]

 33%|███▎      | 1080/3268 [04:13<08:25,  4.32it/s]

 33%|███▎      | 1081/3268 [04:13<08:26,  4.32it/s]

 33%|███▎      | 1082/3268 [04:13<08:25,  4.33it/s]

 33%|███▎      | 1083/3268 [04:14<08:24,  4.33it/s]

 33%|███▎      | 1084/3268 [04:14<08:23,  4.33it/s]

 33%|███▎      | 1085/3268 [04:14<08:24,  4.33it/s]

 33%|███▎      | 1086/3268 [04:14<08:23,  4.34it/s]

 33%|███▎      | 1087/3268 [04:14<08:22,  4.34it/s]

 33%|███▎      | 1088/3268 [04:15<08:23,  4.33it/s]

 33%|███▎      | 1089/3268 [04:15<08:23,  4.33it/s]

 33%|███▎      | 1090/3268 [04:15<08:23,  4.33it/s]

 33%|███▎      | 1091/3268 [04:15<08:23,  4.32it/s]

 33%|███▎      | 1092/3268 [04:16<08:23,  4.33it/s]

 33%|███▎      | 1093/3268 [04:16<08:22,  4.32it/s]

 33%|███▎      | 1094/3268 [04:16<08:23,  4.32it/s]

 34%|███▎      | 1095/3268 [04:16<08:24,  4.31it/s]

 34%|███▎      | 1096/3268 [04:17<08:24,  4.30it/s]

 34%|███▎      | 1097/3268 [04:17<08:24,  4.30it/s]

 34%|███▎      | 1098/3268 [04:17<08:24,  4.30it/s]

 34%|███▎      | 1099/3268 [04:17<08:24,  4.30it/s]

 34%|███▎      | 1100/3268 [04:17<08:23,  4.31it/s]

 34%|███▎      | 1101/3268 [04:18<08:22,  4.31it/s]

 34%|███▎      | 1102/3268 [04:18<08:24,  4.29it/s]

 34%|███▍      | 1103/3268 [04:18<08:23,  4.30it/s]

 34%|███▍      | 1104/3268 [04:18<08:24,  4.29it/s]

 34%|███▍      | 1105/3268 [04:19<08:22,  4.31it/s]

 34%|███▍      | 1106/3268 [04:19<08:22,  4.30it/s]

 34%|███▍      | 1107/3268 [04:19<08:22,  4.30it/s]

 34%|███▍      | 1108/3268 [04:19<08:21,  4.31it/s]

 34%|███▍      | 1109/3268 [04:20<08:21,  4.31it/s]

 34%|███▍      | 1110/3268 [04:20<08:21,  4.30it/s]

 34%|███▍      | 1111/3268 [04:20<08:21,  4.30it/s]

 34%|███▍      | 1112/3268 [04:20<08:21,  4.30it/s]

 34%|███▍      | 1113/3268 [04:20<08:20,  4.30it/s]

 34%|███▍      | 1114/3268 [04:21<08:21,  4.30it/s]

 34%|███▍      | 1115/3268 [04:21<08:21,  4.29it/s]

 34%|███▍      | 1116/3268 [04:21<08:21,  4.29it/s]

 34%|███▍      | 1117/3268 [04:21<08:20,  4.29it/s]

 34%|███▍      | 1118/3268 [04:22<08:21,  4.29it/s]

 34%|███▍      | 1119/3268 [04:22<08:20,  4.29it/s]

 34%|███▍      | 1120/3268 [04:22<08:19,  4.30it/s]

 34%|███▍      | 1121/3268 [04:22<08:18,  4.30it/s]

 34%|███▍      | 1122/3268 [04:23<08:19,  4.30it/s]

 34%|███▍      | 1123/3268 [04:23<08:24,  4.25it/s]

 34%|███▍      | 1124/3268 [04:23<08:22,  4.27it/s]

 34%|███▍      | 1125/3268 [04:23<08:21,  4.28it/s]

 34%|███▍      | 1126/3268 [04:24<08:19,  4.29it/s]

 34%|███▍      | 1127/3268 [04:24<08:18,  4.29it/s]

 35%|███▍      | 1128/3268 [04:24<08:17,  4.30it/s]

 35%|███▍      | 1129/3268 [04:24<08:17,  4.30it/s]

 35%|███▍      | 1130/3268 [04:24<08:17,  4.30it/s]

 35%|███▍      | 1131/3268 [04:25<08:16,  4.30it/s]

 35%|███▍      | 1132/3268 [04:25<08:15,  4.31it/s]

 35%|███▍      | 1133/3268 [04:25<08:16,  4.30it/s]

 35%|███▍      | 1134/3268 [04:25<08:15,  4.31it/s]

 35%|███▍      | 1135/3268 [04:26<08:15,  4.31it/s]

 35%|███▍      | 1136/3268 [04:26<08:15,  4.30it/s]

 35%|███▍      | 1137/3268 [04:26<08:14,  4.31it/s]

 35%|███▍      | 1138/3268 [04:26<08:15,  4.30it/s]

 35%|███▍      | 1139/3268 [04:27<08:14,  4.30it/s]

 35%|███▍      | 1140/3268 [04:27<08:15,  4.30it/s]

 35%|███▍      | 1141/3268 [04:27<08:14,  4.30it/s]

 35%|███▍      | 1142/3268 [04:27<08:13,  4.30it/s]

 35%|███▍      | 1143/3268 [04:27<08:14,  4.29it/s]

 35%|███▌      | 1144/3268 [04:28<08:15,  4.28it/s]

 35%|███▌      | 1145/3268 [04:28<08:15,  4.28it/s]

 35%|███▌      | 1146/3268 [04:28<08:15,  4.28it/s]

 35%|███▌      | 1147/3268 [04:28<08:16,  4.28it/s]

 35%|███▌      | 1148/3268 [04:29<08:15,  4.28it/s]

 35%|███▌      | 1149/3268 [04:29<08:15,  4.28it/s]

 35%|███▌      | 1150/3268 [04:29<08:15,  4.27it/s]

 35%|███▌      | 1151/3268 [04:29<08:15,  4.27it/s]

 35%|███▌      | 1152/3268 [04:30<08:15,  4.27it/s]

 35%|███▌      | 1153/3268 [04:30<08:14,  4.27it/s]

 35%|███▌      | 1154/3268 [04:30<08:14,  4.28it/s]

 35%|███▌      | 1155/3268 [04:30<08:13,  4.28it/s]

 35%|███▌      | 1156/3268 [04:31<08:13,  4.28it/s]

 35%|███▌      | 1157/3268 [04:31<08:12,  4.28it/s]

 35%|███▌      | 1158/3268 [04:31<08:12,  4.28it/s]

 35%|███▌      | 1159/3268 [04:31<08:11,  4.29it/s]

 35%|███▌      | 1160/3268 [04:31<08:12,  4.28it/s]

 36%|███▌      | 1161/3268 [04:32<08:11,  4.29it/s]

 36%|███▌      | 1162/3268 [04:32<08:10,  4.29it/s]

 36%|███▌      | 1163/3268 [04:32<08:14,  4.26it/s]

 36%|███▌      | 1164/3268 [04:32<08:12,  4.27it/s]

 36%|███▌      | 1165/3268 [04:33<08:12,  4.27it/s]

 36%|███▌      | 1166/3268 [04:33<08:10,  4.28it/s]

 36%|███▌      | 1167/3268 [04:33<08:11,  4.28it/s]

 36%|███▌      | 1168/3268 [04:33<08:11,  4.27it/s]

 36%|███▌      | 1169/3268 [04:34<08:11,  4.27it/s]

 36%|███▌      | 1170/3268 [04:34<08:10,  4.28it/s]

 36%|███▌      | 1171/3268 [04:34<08:10,  4.27it/s]

 36%|███▌      | 1172/3268 [04:34<08:10,  4.28it/s]

 36%|███▌      | 1173/3268 [04:34<08:10,  4.27it/s]

 36%|███▌      | 1174/3268 [04:35<08:11,  4.26it/s]

 36%|███▌      | 1175/3268 [04:35<08:10,  4.26it/s]

 36%|███▌      | 1176/3268 [04:35<08:09,  4.27it/s]

 36%|███▌      | 1177/3268 [04:35<08:08,  4.28it/s]

 36%|███▌      | 1178/3268 [04:36<08:09,  4.27it/s]

 36%|███▌      | 1179/3268 [04:36<08:08,  4.28it/s]

 36%|███▌      | 1180/3268 [04:36<08:08,  4.27it/s]

 36%|███▌      | 1181/3268 [04:36<08:08,  4.27it/s]

 36%|███▌      | 1182/3268 [04:37<08:08,  4.27it/s]

 36%|███▌      | 1183/3268 [04:37<08:09,  4.26it/s]

 36%|███▌      | 1184/3268 [04:37<08:07,  4.27it/s]

 36%|███▋      | 1185/3268 [04:37<08:06,  4.28it/s]

 36%|███▋      | 1186/3268 [04:38<08:05,  4.28it/s]

 36%|███▋      | 1187/3268 [04:38<08:06,  4.28it/s]

 36%|███▋      | 1188/3268 [04:38<08:06,  4.27it/s]

 36%|███▋      | 1189/3268 [04:38<08:06,  4.28it/s]

 36%|███▋      | 1190/3268 [04:38<08:06,  4.27it/s]

 36%|███▋      | 1191/3268 [04:39<08:05,  4.28it/s]

 36%|███▋      | 1192/3268 [04:39<08:04,  4.28it/s]

 37%|███▋      | 1193/3268 [04:39<08:05,  4.27it/s]

 37%|███▋      | 1194/3268 [04:39<08:05,  4.27it/s]

 37%|███▋      | 1195/3268 [04:40<08:06,  4.26it/s]

 37%|███▋      | 1196/3268 [04:40<08:05,  4.27it/s]

 37%|███▋      | 1197/3268 [04:40<08:05,  4.27it/s]

 37%|███▋      | 1198/3268 [04:40<08:04,  4.27it/s]

 37%|███▋      | 1199/3268 [04:41<08:05,  4.27it/s]

 37%|███▋      | 1200/3268 [04:41<08:05,  4.26it/s]

 37%|███▋      | 1201/3268 [04:41<08:06,  4.25it/s]

 37%|███▋      | 1202/3268 [04:41<08:04,  4.26it/s]

 37%|███▋      | 1203/3268 [04:42<08:04,  4.26it/s]

 37%|███▋      | 1204/3268 [04:42<08:03,  4.27it/s]

 37%|███▋      | 1205/3268 [04:42<08:03,  4.27it/s]

 37%|███▋      | 1206/3268 [04:42<08:02,  4.27it/s]

 37%|███▋      | 1207/3268 [04:42<08:03,  4.26it/s]

 37%|███▋      | 1208/3268 [04:43<08:02,  4.27it/s]

 37%|███▋      | 1209/3268 [04:43<08:00,  4.28it/s]

 37%|███▋      | 1210/3268 [04:43<08:00,  4.29it/s]

 37%|███▋      | 1211/3268 [04:43<08:00,  4.29it/s]

 37%|███▋      | 1212/3268 [04:44<08:00,  4.28it/s]

 37%|███▋      | 1213/3268 [04:44<08:02,  4.26it/s]

 37%|███▋      | 1214/3268 [04:44<08:01,  4.27it/s]

 37%|███▋      | 1215/3268 [04:44<08:01,  4.27it/s]

 37%|███▋      | 1216/3268 [04:45<08:01,  4.27it/s]

 37%|███▋      | 1217/3268 [04:45<07:59,  4.28it/s]

 37%|███▋      | 1218/3268 [04:45<07:59,  4.27it/s]

 37%|███▋      | 1219/3268 [04:45<07:58,  4.28it/s]

 37%|███▋      | 1220/3268 [04:45<07:58,  4.28it/s]

 37%|███▋      | 1221/3268 [04:46<07:59,  4.27it/s]

 37%|███▋      | 1222/3268 [04:46<07:58,  4.27it/s]

 37%|███▋      | 1223/3268 [04:46<07:58,  4.27it/s]

 37%|███▋      | 1224/3268 [04:46<07:57,  4.28it/s]

 37%|███▋      | 1225/3268 [04:47<07:57,  4.28it/s]

 38%|███▊      | 1226/3268 [04:47<07:58,  4.27it/s]

 38%|███▊      | 1227/3268 [04:47<07:57,  4.27it/s]

 38%|███▊      | 1228/3268 [04:47<07:58,  4.26it/s]

 38%|███▊      | 1229/3268 [04:48<07:58,  4.26it/s]

 38%|███▊      | 1230/3268 [04:48<07:57,  4.27it/s]

 38%|███▊      | 1231/3268 [04:48<07:56,  4.27it/s]

 38%|███▊      | 1232/3268 [04:48<07:55,  4.28it/s]

 38%|███▊      | 1233/3268 [04:49<07:55,  4.28it/s]

 38%|███▊      | 1234/3268 [04:49<07:55,  4.27it/s]

 38%|███▊      | 1235/3268 [04:49<07:55,  4.28it/s]

 38%|███▊      | 1236/3268 [04:49<07:55,  4.27it/s]

 38%|███▊      | 1237/3268 [04:49<07:55,  4.28it/s]

 38%|███▊      | 1238/3268 [04:50<07:55,  4.27it/s]

 38%|███▊      | 1239/3268 [04:50<07:56,  4.26it/s]

 38%|███▊      | 1240/3268 [04:50<07:56,  4.26it/s]

 38%|███▊      | 1241/3268 [04:50<07:56,  4.26it/s]

 38%|███▊      | 1242/3268 [04:51<07:55,  4.26it/s]

 38%|███▊      | 1243/3268 [04:51<07:54,  4.26it/s]

 38%|███▊      | 1244/3268 [04:51<07:55,  4.26it/s]

 38%|███▊      | 1245/3268 [04:51<07:55,  4.26it/s]

 38%|███▊      | 1246/3268 [04:52<07:54,  4.26it/s]

 38%|███▊      | 1247/3268 [04:52<07:53,  4.26it/s]

 38%|███▊      | 1248/3268 [04:52<07:53,  4.27it/s]

 38%|███▊      | 1249/3268 [04:52<07:54,  4.25it/s]

 38%|███▊      | 1250/3268 [04:53<07:54,  4.25it/s]

 38%|███▊      | 1251/3268 [04:53<07:54,  4.25it/s]

logging
logging the anndata

 38%|███▊      | 1252/3268 [04:55<24:09,  1.39it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 38%|███▊      | 1253/3268 [04:55<19:13,  1.75it/s]

 38%|███▊      | 1254/3268 [04:55<15:44,  2.13it/s]

 38%|███▊      | 1255/3268 [04:55<13:17,  2.52it/s]

 38%|███▊      | 1256/3268 [04:56<11:34,  2.90it/s]

 38%|███▊      | 1257/3268 [04:56<10:23,  3.23it/s]

 38%|███▊      | 1258/3268 [04:56<09:33,  3.50it/s]

 39%|███▊      | 1259/3268 [04:56<09:06,  3.68it/s]

 39%|███▊      | 1260/3268 [04:56<08:39,  3.86it/s]

 39%|███▊      | 1261/3268 [04:57<08:20,  4.01it/s]

 39%|███▊      | 1262/3268 [04:57<08:06,  4.12it/s]

 39%|███▊      | 1263/3268 [04:57<07:59,  4.18it/s]

 39%|███▊      | 1264/3268 [04:57<07:52,  4.24it/s]

 39%|███▊      | 1265/3268 [04:58<07:48,  4.27it/s]

 39%|███▊      | 1266/3268 [04:58<07:45,  4.30it/s]

 39%|███▉      | 1267/3268 [04:58<07:49,  4.26it/s]

 39%|███▉      | 1268/3268 [04:58<07:46,  4.29it/s]

 39%|███▉      | 1269/3268 [04:59<07:43,  4.31it/s]

 39%|███▉      | 1270/3268 [04:59<07:40,  4.34it/s]

 39%|███▉      | 1271/3268 [04:59<07:39,  4.35it/s]

 39%|███▉      | 1272/3268 [04:59<07:37,  4.36it/s]

 39%|███▉      | 1273/3268 [04:59<07:36,  4.37it/s]

 39%|███▉      | 1274/3268 [05:00<07:36,  4.37it/s]

 39%|███▉      | 1275/3268 [05:00<07:35,  4.38it/s]

 39%|███▉      | 1276/3268 [05:00<07:34,  4.38it/s]

 39%|███▉      | 1277/3268 [05:00<07:34,  4.38it/s]

 39%|███▉      | 1278/3268 [05:01<07:34,  4.38it/s]

 39%|███▉      | 1279/3268 [05:01<07:34,  4.38it/s]

 39%|███▉      | 1280/3268 [05:01<07:34,  4.38it/s]

 39%|███▉      | 1281/3268 [05:01<07:33,  4.38it/s]

 39%|███▉      | 1282/3268 [05:01<07:33,  4.38it/s]

 39%|███▉      | 1283/3268 [05:02<07:33,  4.38it/s]

 39%|███▉      | 1284/3268 [05:02<07:32,  4.38it/s]

 39%|███▉      | 1285/3268 [05:02<07:32,  4.38it/s]

 39%|███▉      | 1286/3268 [05:02<07:32,  4.38it/s]

 39%|███▉      | 1287/3268 [05:03<07:31,  4.38it/s]

 39%|███▉      | 1288/3268 [05:03<07:32,  4.38it/s]

 39%|███▉      | 1289/3268 [05:03<07:31,  4.39it/s]

 39%|███▉      | 1290/3268 [05:03<07:30,  4.39it/s]

 40%|███▉      | 1291/3268 [05:04<07:32,  4.37it/s]

 40%|███▉      | 1292/3268 [05:04<07:32,  4.37it/s]

 40%|███▉      | 1293/3268 [05:04<07:33,  4.36it/s]

 40%|███▉      | 1294/3268 [05:04<07:32,  4.36it/s]

 40%|███▉      | 1295/3268 [05:04<07:31,  4.37it/s]

 40%|███▉      | 1296/3268 [05:05<07:30,  4.37it/s]

 40%|███▉      | 1297/3268 [05:05<07:30,  4.38it/s]

 40%|███▉      | 1298/3268 [05:05<07:29,  4.38it/s]

 40%|███▉      | 1299/3268 [05:05<07:30,  4.37it/s]

 40%|███▉      | 1300/3268 [05:06<07:29,  4.38it/s]

 40%|███▉      | 1301/3268 [05:06<07:29,  4.38it/s]

 40%|███▉      | 1302/3268 [05:06<07:32,  4.34it/s]

 40%|███▉      | 1303/3268 [05:06<07:32,  4.34it/s]

 40%|███▉      | 1304/3268 [05:07<07:32,  4.34it/s]

 40%|███▉      | 1305/3268 [05:07<07:29,  4.36it/s]

 40%|███▉      | 1306/3268 [05:07<07:29,  4.37it/s]

 40%|███▉      | 1307/3268 [05:07<07:27,  4.38it/s]

 40%|████      | 1308/3268 [05:07<07:26,  4.39it/s]

 40%|████      | 1309/3268 [05:08<07:26,  4.39it/s]

 40%|████      | 1310/3268 [05:08<07:28,  4.36it/s]

 40%|████      | 1311/3268 [05:08<07:27,  4.37it/s]

 40%|████      | 1312/3268 [05:08<07:27,  4.38it/s]

 40%|████      | 1313/3268 [05:09<07:26,  4.38it/s]

 40%|████      | 1314/3268 [05:09<07:26,  4.37it/s]

 40%|████      | 1315/3268 [05:09<07:27,  4.37it/s]

 40%|████      | 1316/3268 [05:09<07:26,  4.37it/s]

 40%|████      | 1317/3268 [05:09<07:26,  4.37it/s]

 40%|████      | 1318/3268 [05:10<07:25,  4.37it/s]

 40%|████      | 1319/3268 [05:10<07:24,  4.38it/s]

 40%|████      | 1320/3268 [05:10<07:25,  4.38it/s]

 40%|████      | 1321/3268 [05:10<07:24,  4.38it/s]

 40%|████      | 1322/3268 [05:11<07:24,  4.38it/s]

 40%|████      | 1323/3268 [05:11<07:23,  4.38it/s]

 41%|████      | 1324/3268 [05:11<07:22,  4.39it/s]

 41%|████      | 1325/3268 [05:11<07:22,  4.39it/s]

 41%|████      | 1326/3268 [05:12<07:22,  4.39it/s]

 41%|████      | 1327/3268 [05:12<07:23,  4.38it/s]

 41%|████      | 1328/3268 [05:12<07:23,  4.38it/s]

 41%|████      | 1329/3268 [05:12<07:22,  4.38it/s]

 41%|████      | 1330/3268 [05:12<07:22,  4.38it/s]

 41%|████      | 1331/3268 [05:13<07:22,  4.38it/s]

 41%|████      | 1332/3268 [05:13<07:22,  4.37it/s]

 41%|████      | 1333/3268 [05:13<07:21,  4.38it/s]

 41%|████      | 1334/3268 [05:13<07:21,  4.38it/s]

 41%|████      | 1335/3268 [05:14<07:22,  4.37it/s]

 41%|████      | 1336/3268 [05:14<07:21,  4.38it/s]

 41%|████      | 1337/3268 [05:14<07:21,  4.37it/s]

 41%|████      | 1338/3268 [05:14<07:22,  4.36it/s]

 41%|████      | 1339/3268 [05:15<07:22,  4.36it/s]

 41%|████      | 1340/3268 [05:15<07:21,  4.37it/s]

 41%|████      | 1341/3268 [05:15<07:20,  4.37it/s]

 41%|████      | 1342/3268 [05:15<07:20,  4.37it/s]

 41%|████      | 1343/3268 [05:15<07:20,  4.37it/s]

 41%|████      | 1344/3268 [05:16<07:20,  4.37it/s]

 41%|████      | 1345/3268 [05:16<07:19,  4.37it/s]

 41%|████      | 1346/3268 [05:16<07:19,  4.37it/s]

 41%|████      | 1347/3268 [05:16<07:19,  4.37it/s]

 41%|████      | 1348/3268 [05:17<07:19,  4.37it/s]

 41%|████▏     | 1349/3268 [05:17<07:21,  4.35it/s]

 41%|████▏     | 1350/3268 [05:17<07:20,  4.36it/s]

 41%|████▏     | 1351/3268 [05:17<07:21,  4.35it/s]

 41%|████▏     | 1352/3268 [05:17<07:19,  4.36it/s]

 41%|████▏     | 1353/3268 [05:18<07:18,  4.36it/s]

 41%|████▏     | 1354/3268 [05:18<07:18,  4.36it/s]

 41%|████▏     | 1355/3268 [05:18<07:18,  4.37it/s]

 41%|████▏     | 1356/3268 [05:18<07:18,  4.36it/s]

 42%|████▏     | 1357/3268 [05:19<07:17,  4.36it/s]

 42%|████▏     | 1358/3268 [05:19<07:18,  4.35it/s]

 42%|████▏     | 1359/3268 [05:19<07:17,  4.36it/s]

 42%|████▏     | 1360/3268 [05:19<07:17,  4.36it/s]

 42%|████▏     | 1361/3268 [05:20<07:17,  4.35it/s]

 42%|████▏     | 1362/3268 [05:20<07:17,  4.36it/s]

 42%|████▏     | 1363/3268 [05:20<07:16,  4.36it/s]

 42%|████▏     | 1364/3268 [05:20<07:17,  4.35it/s]

 42%|████▏     | 1365/3268 [05:20<07:16,  4.36it/s]

 42%|████▏     | 1366/3268 [05:21<07:15,  4.36it/s]

 42%|████▏     | 1367/3268 [05:21<07:15,  4.36it/s]

 42%|████▏     | 1368/3268 [05:21<07:17,  4.35it/s]

 42%|████▏     | 1369/3268 [05:21<07:16,  4.36it/s]

 42%|████▏     | 1370/3268 [05:22<07:14,  4.36it/s]

 42%|████▏     | 1371/3268 [05:22<07:14,  4.36it/s]

 42%|████▏     | 1372/3268 [05:22<07:15,  4.36it/s]

 42%|████▏     | 1373/3268 [05:22<07:15,  4.36it/s]

 42%|████▏     | 1374/3268 [05:23<07:13,  4.37it/s]

 42%|████▏     | 1375/3268 [05:23<07:14,  4.36it/s]

 42%|████▏     | 1376/3268 [05:23<07:13,  4.36it/s]

 42%|████▏     | 1377/3268 [05:23<07:13,  4.36it/s]

 42%|████▏     | 1378/3268 [05:23<07:13,  4.36it/s]

 42%|████▏     | 1379/3268 [05:24<07:12,  4.36it/s]

 42%|████▏     | 1380/3268 [05:24<07:12,  4.36it/s]

 42%|████▏     | 1381/3268 [05:24<07:13,  4.35it/s]

 42%|████▏     | 1382/3268 [05:24<07:12,  4.36it/s]

 42%|████▏     | 1383/3268 [05:25<07:11,  4.36it/s]

 42%|████▏     | 1384/3268 [05:25<07:11,  4.37it/s]

 42%|████▏     | 1385/3268 [05:25<07:10,  4.37it/s]

 42%|████▏     | 1386/3268 [05:25<07:11,  4.36it/s]

 42%|████▏     | 1387/3268 [05:26<07:11,  4.36it/s]

 42%|████▏     | 1388/3268 [05:26<07:11,  4.36it/s]

 43%|████▎     | 1389/3268 [05:26<07:10,  4.36it/s]

 43%|████▎     | 1390/3268 [05:26<07:10,  4.36it/s]

 43%|████▎     | 1391/3268 [05:26<07:10,  4.36it/s]

 43%|████▎     | 1392/3268 [05:27<07:10,  4.36it/s]

 43%|████▎     | 1393/3268 [05:27<07:09,  4.36it/s]

 43%|████▎     | 1394/3268 [05:27<07:09,  4.36it/s]

 43%|████▎     | 1395/3268 [05:27<07:10,  4.35it/s]

 43%|████▎     | 1396/3268 [05:28<07:09,  4.36it/s]

 43%|████▎     | 1397/3268 [05:28<07:09,  4.36it/s]

 43%|████▎     | 1398/3268 [05:28<07:09,  4.36it/s]

 43%|████▎     | 1399/3268 [05:28<07:07,  4.37it/s]

 43%|████▎     | 1400/3268 [05:29<07:08,  4.36it/s]

 43%|████▎     | 1401/3268 [05:29<07:07,  4.36it/s]

 43%|████▎     | 1402/3268 [05:29<07:08,  4.36it/s]

 43%|████▎     | 1403/3268 [05:29<07:08,  4.36it/s]

 43%|████▎     | 1404/3268 [05:29<07:08,  4.35it/s]

 43%|████▎     | 1405/3268 [05:30<07:08,  4.35it/s]

 43%|████▎     | 1406/3268 [05:30<07:09,  4.34it/s]

 43%|████▎     | 1407/3268 [05:30<07:07,  4.35it/s]

 43%|████▎     | 1408/3268 [05:30<07:06,  4.36it/s]

 43%|████▎     | 1409/3268 [05:31<07:06,  4.36it/s]

 43%|████▎     | 1410/3268 [05:31<07:05,  4.37it/s]

 43%|████▎     | 1411/3268 [05:31<07:05,  4.37it/s]

 43%|████▎     | 1412/3268 [05:31<07:05,  4.37it/s]

 43%|████▎     | 1413/3268 [05:31<07:04,  4.37it/s]

 43%|████▎     | 1414/3268 [05:32<07:04,  4.36it/s]

 43%|████▎     | 1415/3268 [05:32<07:07,  4.33it/s]

 43%|████▎     | 1416/3268 [05:32<07:06,  4.34it/s]

 43%|████▎     | 1417/3268 [05:32<07:06,  4.34it/s]

 43%|████▎     | 1418/3268 [05:33<07:06,  4.34it/s]

 43%|████▎     | 1419/3268 [05:33<07:05,  4.34it/s]

 43%|████▎     | 1420/3268 [05:33<07:05,  4.34it/s]

 43%|████▎     | 1421/3268 [05:33<07:04,  4.35it/s]

 44%|████▎     | 1422/3268 [05:34<07:04,  4.35it/s]

 44%|████▎     | 1423/3268 [05:34<07:04,  4.34it/s]

 44%|████▎     | 1424/3268 [05:34<07:04,  4.35it/s]

 44%|████▎     | 1425/3268 [05:34<07:03,  4.35it/s]

 44%|████▎     | 1426/3268 [05:34<07:04,  4.34it/s]

 44%|████▎     | 1427/3268 [05:35<07:03,  4.35it/s]

 44%|████▎     | 1428/3268 [05:35<07:02,  4.35it/s]

 44%|████▎     | 1429/3268 [05:35<07:03,  4.35it/s]

 44%|████▍     | 1430/3268 [05:35<07:02,  4.36it/s]

 44%|████▍     | 1431/3268 [05:36<07:02,  4.35it/s]

 44%|████▍     | 1432/3268 [05:36<07:01,  4.35it/s]

 44%|████▍     | 1433/3268 [05:36<07:01,  4.35it/s]

 44%|████▍     | 1434/3268 [05:36<07:01,  4.35it/s]

 44%|████▍     | 1435/3268 [05:37<07:01,  4.35it/s]

 44%|████▍     | 1436/3268 [05:37<07:03,  4.33it/s]

 44%|████▍     | 1437/3268 [05:37<07:03,  4.33it/s]

 44%|████▍     | 1438/3268 [05:37<07:01,  4.34it/s]

 44%|████▍     | 1439/3268 [05:37<07:00,  4.34it/s]

 44%|████▍     | 1440/3268 [05:38<07:00,  4.35it/s]

 44%|████▍     | 1441/3268 [05:38<06:59,  4.35it/s]

 44%|████▍     | 1442/3268 [05:38<07:00,  4.34it/s]

 44%|████▍     | 1443/3268 [05:38<07:00,  4.34it/s]

 44%|████▍     | 1444/3268 [05:39<06:59,  4.35it/s]

 44%|████▍     | 1445/3268 [05:39<06:59,  4.35it/s]

 44%|████▍     | 1446/3268 [05:39<06:59,  4.35it/s]

 44%|████▍     | 1447/3268 [05:39<06:58,  4.35it/s]

 44%|████▍     | 1448/3268 [05:40<06:57,  4.36it/s]

 44%|████▍     | 1449/3268 [05:40<06:58,  4.35it/s]

 44%|████▍     | 1450/3268 [05:40<06:57,  4.35it/s]

 44%|████▍     | 1451/3268 [05:40<06:57,  4.35it/s]

 44%|████▍     | 1452/3268 [05:40<06:56,  4.36it/s]

 44%|████▍     | 1453/3268 [05:41<06:57,  4.35it/s]

 44%|████▍     | 1454/3268 [05:41<06:56,  4.35it/s]

 45%|████▍     | 1455/3268 [05:41<06:56,  4.35it/s]

 45%|████▍     | 1456/3268 [05:41<06:57,  4.34it/s]

 45%|████▍     | 1457/3268 [05:42<06:56,  4.35it/s]

 45%|████▍     | 1458/3268 [05:42<06:56,  4.35it/s]

 45%|████▍     | 1459/3268 [05:42<06:56,  4.34it/s]

 45%|████▍     | 1460/3268 [05:42<06:56,  4.34it/s]

 45%|████▍     | 1461/3268 [05:43<06:56,  4.34it/s]

 45%|████▍     | 1462/3268 [05:43<06:56,  4.33it/s]

 45%|████▍     | 1463/3268 [05:43<06:56,  4.33it/s]

 45%|████▍     | 1464/3268 [05:43<06:56,  4.33it/s]

 45%|████▍     | 1465/3268 [05:43<06:54,  4.35it/s]

 45%|████▍     | 1466/3268 [05:44<06:54,  4.35it/s]

 45%|████▍     | 1467/3268 [05:44<06:54,  4.35it/s]

 45%|████▍     | 1468/3268 [05:44<06:53,  4.35it/s]

 45%|████▍     | 1469/3268 [05:44<06:54,  4.34it/s]

 45%|████▍     | 1470/3268 [05:45<06:53,  4.35it/s]

 45%|████▌     | 1471/3268 [05:45<06:53,  4.35it/s]

 45%|████▌     | 1472/3268 [05:45<06:52,  4.35it/s]

 45%|████▌     | 1473/3268 [05:45<06:53,  4.34it/s]

 45%|████▌     | 1474/3268 [05:46<06:52,  4.35it/s]

 45%|████▌     | 1475/3268 [05:46<06:52,  4.34it/s]

 45%|████▌     | 1476/3268 [05:46<06:52,  4.34it/s]

 45%|████▌     | 1477/3268 [05:46<06:51,  4.35it/s]

 45%|████▌     | 1478/3268 [05:46<06:51,  4.35it/s]

 45%|████▌     | 1479/3268 [05:47<06:50,  4.36it/s]

 45%|████▌     | 1480/3268 [05:47<06:50,  4.35it/s]

 45%|████▌     | 1481/3268 [05:47<06:50,  4.35it/s]

 45%|████▌     | 1482/3268 [05:47<06:50,  4.35it/s]

 45%|████▌     | 1483/3268 [05:48<06:50,  4.35it/s]

 45%|████▌     | 1484/3268 [05:48<06:49,  4.35it/s]

 45%|████▌     | 1485/3268 [05:48<06:49,  4.35it/s]

 45%|████▌     | 1486/3268 [05:48<06:49,  4.36it/s]

 46%|████▌     | 1487/3268 [05:49<06:49,  4.35it/s]

 46%|████▌     | 1488/3268 [05:49<06:48,  4.36it/s]

 46%|████▌     | 1489/3268 [05:49<06:48,  4.35it/s]

 46%|████▌     | 1490/3268 [05:49<06:48,  4.35it/s]

 46%|████▌     | 1491/3268 [05:49<06:48,  4.35it/s]

 46%|████▌     | 1492/3268 [05:50<06:48,  4.35it/s]

 46%|████▌     | 1493/3268 [05:50<06:47,  4.35it/s]

 46%|████▌     | 1494/3268 [05:50<06:47,  4.35it/s]

 46%|████▌     | 1495/3268 [05:50<06:47,  4.35it/s]

 46%|████▌     | 1496/3268 [05:51<06:47,  4.35it/s]

 46%|████▌     | 1497/3268 [05:51<06:47,  4.35it/s]

 46%|████▌     | 1498/3268 [05:51<06:47,  4.35it/s]

 46%|████▌     | 1499/3268 [05:51<06:47,  4.34it/s]

 46%|████▌     | 1500/3268 [05:52<06:48,  4.33it/s]

 46%|████▌     | 1501/3268 [05:52<06:47,  4.34it/s]

 46%|████▌     | 1502/3268 [05:52<06:47,  4.33it/s]

 46%|████▌     | 1503/3268 [05:52<06:46,  4.34it/s]

 46%|████▌     | 1504/3268 [05:52<06:46,  4.34it/s]

 46%|████▌     | 1505/3268 [05:53<06:46,  4.34it/s]

 46%|████▌     | 1506/3268 [05:53<06:45,  4.34it/s]

 46%|████▌     | 1507/3268 [05:53<06:45,  4.35it/s]

 46%|████▌     | 1508/3268 [05:53<06:46,  4.33it/s]

 46%|████▌     | 1509/3268 [05:54<06:45,  4.34it/s]

 46%|████▌     | 1510/3268 [05:54<06:44,  4.34it/s]

 46%|████▌     | 1511/3268 [05:54<06:44,  4.35it/s]

 46%|████▋     | 1512/3268 [05:54<06:43,  4.35it/s]

 46%|████▋     | 1513/3268 [05:55<06:44,  4.34it/s]

 46%|████▋     | 1514/3268 [05:55<06:42,  4.36it/s]

 46%|████▋     | 1515/3268 [05:55<06:42,  4.36it/s]

 46%|████▋     | 1516/3268 [05:55<06:42,  4.35it/s]

 46%|████▋     | 1517/3268 [05:55<06:43,  4.34it/s]

 46%|████▋     | 1518/3268 [05:56<06:42,  4.34it/s]

 46%|████▋     | 1519/3268 [05:56<06:43,  4.34it/s]

 47%|████▋     | 1520/3268 [05:56<06:42,  4.35it/s]

 47%|████▋     | 1521/3268 [05:56<06:41,  4.35it/s]

 47%|████▋     | 1522/3268 [05:57<06:41,  4.35it/s]

 47%|████▋     | 1523/3268 [05:57<06:41,  4.35it/s]

 47%|████▋     | 1524/3268 [05:57<06:41,  4.35it/s]

 47%|████▋     | 1525/3268 [05:57<06:40,  4.35it/s]

 47%|████▋     | 1526/3268 [05:57<06:40,  4.35it/s]

 47%|████▋     | 1527/3268 [05:58<06:39,  4.36it/s]

 47%|████▋     | 1528/3268 [05:58<06:41,  4.34it/s]

 47%|████▋     | 1529/3268 [05:58<06:40,  4.34it/s]

 47%|████▋     | 1530/3268 [05:58<06:40,  4.34it/s]

 47%|████▋     | 1531/3268 [05:59<06:39,  4.34it/s]

 47%|████▋     | 1532/3268 [05:59<06:40,  4.34it/s]

 47%|████▋     | 1533/3268 [05:59<06:40,  4.34it/s]

 47%|████▋     | 1534/3268 [05:59<06:40,  4.33it/s]

 47%|████▋     | 1535/3268 [06:00<06:38,  4.35it/s]

 47%|████▋     | 1536/3268 [06:00<06:38,  4.35it/s]

 47%|████▋     | 1537/3268 [06:00<06:37,  4.35it/s]

 47%|████▋     | 1538/3268 [06:00<06:37,  4.35it/s]

 47%|████▋     | 1539/3268 [06:00<06:37,  4.35it/s]

 47%|████▋     | 1540/3268 [06:01<06:37,  4.35it/s]

 47%|████▋     | 1541/3268 [06:01<06:38,  4.34it/s]

 47%|████▋     | 1542/3268 [06:01<06:37,  4.34it/s]

 47%|████▋     | 1543/3268 [06:01<06:37,  4.34it/s]

 47%|████▋     | 1544/3268 [06:02<06:36,  4.34it/s]

 47%|████▋     | 1545/3268 [06:02<06:36,  4.34it/s]

 47%|████▋     | 1546/3268 [06:02<06:35,  4.35it/s]

 47%|████▋     | 1547/3268 [06:02<06:36,  4.34it/s]

 47%|████▋     | 1548/3268 [06:03<06:35,  4.34it/s]

 47%|████▋     | 1549/3268 [06:03<06:34,  4.36it/s]

 47%|████▋     | 1550/3268 [06:03<06:35,  4.35it/s]

 47%|████▋     | 1551/3268 [06:03<06:36,  4.33it/s]

 47%|████▋     | 1552/3268 [06:03<06:36,  4.33it/s]

 48%|████▊     | 1553/3268 [06:04<06:35,  4.34it/s]

 48%|████▊     | 1554/3268 [06:04<06:35,  4.34it/s]

 48%|████▊     | 1555/3268 [06:04<06:34,  4.34it/s]

 48%|████▊     | 1556/3268 [06:04<06:34,  4.33it/s]

 48%|████▊     | 1557/3268 [06:05<06:33,  4.35it/s]

 48%|████▊     | 1558/3268 [06:05<06:32,  4.35it/s]

 48%|████▊     | 1559/3268 [06:05<06:32,  4.35it/s]

 48%|████▊     | 1560/3268 [06:05<06:32,  4.35it/s]

 48%|████▊     | 1561/3268 [06:06<06:32,  4.35it/s]

 48%|████▊     | 1562/3268 [06:06<06:31,  4.35it/s]

 48%|████▊     | 1563/3268 [06:06<06:32,  4.35it/s]

 48%|████▊     | 1564/3268 [06:06<06:32,  4.34it/s]

 48%|████▊     | 1565/3268 [06:06<06:31,  4.35it/s]

 48%|████▊     | 1566/3268 [06:07<06:30,  4.35it/s]

 48%|████▊     | 1567/3268 [06:07<06:30,  4.35it/s]

 48%|████▊     | 1568/3268 [06:07<06:30,  4.36it/s]

 48%|████▊     | 1569/3268 [06:07<06:30,  4.35it/s]

 48%|████▊     | 1570/3268 [06:08<06:30,  4.34it/s]

 48%|████▊     | 1571/3268 [06:08<06:31,  4.34it/s]

 48%|████▊     | 1572/3268 [06:08<06:30,  4.34it/s]

 48%|████▊     | 1573/3268 [06:08<06:29,  4.35it/s]

 48%|████▊     | 1574/3268 [06:09<06:29,  4.35it/s]

 48%|████▊     | 1575/3268 [06:09<06:29,  4.34it/s]

 48%|████▊     | 1576/3268 [06:09<06:28,  4.35it/s]

 48%|████▊     | 1577/3268 [06:09<06:28,  4.35it/s]

 48%|████▊     | 1578/3268 [06:09<06:28,  4.35it/s]

 48%|████▊     | 1579/3268 [06:10<06:28,  4.34it/s]

 48%|████▊     | 1580/3268 [06:10<06:29,  4.33it/s]

 48%|████▊     | 1581/3268 [06:10<06:29,  4.33it/s]

 48%|████▊     | 1582/3268 [06:10<06:28,  4.34it/s]

 48%|████▊     | 1583/3268 [06:11<06:28,  4.34it/s]

 48%|████▊     | 1584/3268 [06:11<06:27,  4.35it/s]

 49%|████▊     | 1585/3268 [06:11<06:27,  4.35it/s]

 49%|████▊     | 1586/3268 [06:11<06:27,  4.34it/s]

 49%|████▊     | 1587/3268 [06:12<06:26,  4.34it/s]

 49%|████▊     | 1588/3268 [06:12<06:27,  4.34it/s]

 49%|████▊     | 1589/3268 [06:12<06:27,  4.34it/s]

 49%|████▊     | 1590/3268 [06:12<06:27,  4.33it/s]

 49%|████▊     | 1591/3268 [06:12<06:28,  4.32it/s]

 49%|████▊     | 1592/3268 [06:13<06:27,  4.33it/s]

 49%|████▊     | 1593/3268 [06:13<06:26,  4.33it/s]

 49%|████▉     | 1594/3268 [06:13<06:27,  4.32it/s]

 49%|████▉     | 1595/3268 [06:13<06:26,  4.33it/s]

 49%|████▉     | 1596/3268 [06:14<06:26,  4.33it/s]

 49%|████▉     | 1597/3268 [06:14<06:25,  4.33it/s]

 49%|████▉     | 1598/3268 [06:14<06:25,  4.33it/s]

 49%|████▉     | 1599/3268 [06:14<06:25,  4.33it/s]

 49%|████▉     | 1600/3268 [06:15<06:24,  4.34it/s]

 49%|████▉     | 1601/3268 [06:15<06:24,  4.34it/s]

 49%|████▉     | 1602/3268 [06:15<06:25,  4.32it/s]

 49%|████▉     | 1603/3268 [06:15<06:25,  4.32it/s]

 49%|████▉     | 1604/3268 [06:15<06:25,  4.32it/s]

 49%|████▉     | 1605/3268 [06:16<06:24,  4.33it/s]

 49%|████▉     | 1606/3268 [06:16<06:23,  4.33it/s]

 49%|████▉     | 1607/3268 [06:16<06:23,  4.33it/s]

 49%|████▉     | 1608/3268 [06:16<06:22,  4.34it/s]

 49%|████▉     | 1609/3268 [06:17<06:23,  4.33it/s]

 49%|████▉     | 1610/3268 [06:17<06:23,  4.32it/s]

 49%|████▉     | 1611/3268 [06:17<06:22,  4.33it/s]

 49%|████▉     | 1612/3268 [06:17<06:22,  4.33it/s]

 49%|████▉     | 1613/3268 [06:18<06:21,  4.34it/s]

 49%|████▉     | 1614/3268 [06:18<06:20,  4.34it/s]

 49%|████▉     | 1615/3268 [06:18<06:20,  4.34it/s]

 49%|████▉     | 1616/3268 [06:18<06:20,  4.34it/s]

 49%|████▉     | 1617/3268 [06:18<06:21,  4.33it/s]

 50%|████▉     | 1618/3268 [06:19<06:20,  4.33it/s]

 50%|████▉     | 1619/3268 [06:19<06:20,  4.33it/s]

 50%|████▉     | 1620/3268 [06:19<06:21,  4.32it/s]

 50%|████▉     | 1621/3268 [06:19<06:20,  4.33it/s]

 50%|████▉     | 1622/3268 [06:20<06:19,  4.33it/s]

 50%|████▉     | 1623/3268 [06:20<06:19,  4.33it/s]

 50%|████▉     | 1624/3268 [06:20<06:19,  4.33it/s]

 50%|████▉     | 1625/3268 [06:20<06:19,  4.33it/s]

 50%|████▉     | 1626/3268 [06:21<06:19,  4.32it/s]

 50%|████▉     | 1627/3268 [06:21<06:19,  4.33it/s]

 50%|████▉     | 1628/3268 [06:21<06:19,  4.32it/s]

 50%|████▉     | 1629/3268 [06:21<06:18,  4.33it/s]

 50%|████▉     | 1630/3268 [06:21<06:18,  4.33it/s]

 50%|████▉     | 1631/3268 [06:22<06:18,  4.32it/s]

 50%|████▉     | 1632/3268 [06:22<06:18,  4.33it/s]

 50%|████▉     | 1633/3268 [06:22<06:18,  4.32it/s]

 50%|█████     | 1634/3268 [06:22<06:17,  4.33it/s]

 50%|█████     | 1635/3268 [06:23<06:17,  4.32it/s]

 50%|█████     | 1636/3268 [06:23<06:17,  4.32it/s]

 50%|█████     | 1637/3268 [06:23<06:18,  4.31it/s]

 50%|█████     | 1638/3268 [06:23<06:17,  4.32it/s]

 50%|█████     | 1639/3268 [06:24<06:17,  4.32it/s]

 50%|█████     | 1640/3268 [06:24<06:16,  4.32it/s]

 50%|█████     | 1641/3268 [06:24<06:16,  4.33it/s]

 50%|█████     | 1642/3268 [06:24<06:15,  4.33it/s]

 50%|█████     | 1643/3268 [06:24<06:15,  4.33it/s]

 50%|█████     | 1644/3268 [06:25<06:15,  4.32it/s]

 50%|█████     | 1645/3268 [06:25<06:14,  4.33it/s]

 50%|█████     | 1646/3268 [06:25<06:13,  4.34it/s]

 50%|█████     | 1647/3268 [06:25<06:13,  4.34it/s]

 50%|█████     | 1648/3268 [06:26<06:13,  4.33it/s]

 50%|█████     | 1649/3268 [06:26<06:14,  4.33it/s]

 50%|█████     | 1650/3268 [06:26<06:13,  4.33it/s]

 51%|█████     | 1651/3268 [06:26<06:14,  4.32it/s]

 51%|█████     | 1652/3268 [06:27<06:15,  4.31it/s]

 51%|█████     | 1653/3268 [06:27<06:14,  4.32it/s]

 51%|█████     | 1654/3268 [06:27<06:13,  4.32it/s]

 51%|█████     | 1655/3268 [06:27<06:13,  4.31it/s]

 51%|█████     | 1656/3268 [06:27<06:14,  4.30it/s]

 51%|█████     | 1657/3268 [06:28<06:14,  4.30it/s]

 51%|█████     | 1658/3268 [06:28<06:13,  4.31it/s]

 51%|█████     | 1659/3268 [06:28<06:13,  4.31it/s]

 51%|█████     | 1660/3268 [06:28<06:12,  4.32it/s]

 51%|█████     | 1661/3268 [06:29<06:12,  4.31it/s]

 51%|█████     | 1662/3268 [06:29<06:12,  4.31it/s]

 51%|█████     | 1663/3268 [06:29<06:11,  4.32it/s]

 51%|█████     | 1664/3268 [06:29<06:11,  4.32it/s]

 51%|█████     | 1665/3268 [06:30<06:12,  4.30it/s]

 51%|█████     | 1666/3268 [06:30<06:11,  4.31it/s]

 51%|█████     | 1667/3268 [06:30<06:10,  4.32it/s]

 51%|█████     | 1668/3268 [06:30<06:11,  4.30it/s]

 51%|█████     | 1669/3268 [06:30<06:10,  4.31it/s]

 51%|█████     | 1670/3268 [06:31<06:10,  4.32it/s]

 51%|█████     | 1671/3268 [06:31<06:10,  4.31it/s]

 51%|█████     | 1672/3268 [06:31<06:09,  4.31it/s]

 51%|█████     | 1673/3268 [06:31<06:10,  4.31it/s]

 51%|█████     | 1674/3268 [06:32<06:10,  4.31it/s]

 51%|█████▏    | 1675/3268 [06:32<06:09,  4.31it/s]

 51%|█████▏    | 1676/3268 [06:32<06:08,  4.32it/s]

 51%|█████▏    | 1677/3268 [06:32<06:08,  4.32it/s]

 51%|█████▏    | 1678/3268 [06:33<06:07,  4.32it/s]

 51%|█████▏    | 1679/3268 [06:33<06:06,  4.33it/s]

 51%|█████▏    | 1680/3268 [06:33<06:06,  4.33it/s]

 51%|█████▏    | 1681/3268 [06:33<06:08,  4.31it/s]

 51%|█████▏    | 1682/3268 [06:34<06:07,  4.32it/s]

 51%|█████▏    | 1683/3268 [06:34<06:07,  4.31it/s]

 52%|█████▏    | 1684/3268 [06:34<06:07,  4.31it/s]

 52%|█████▏    | 1685/3268 [06:34<06:07,  4.30it/s]

 52%|█████▏    | 1686/3268 [06:34<06:07,  4.31it/s]

 52%|█████▏    | 1687/3268 [06:35<06:06,  4.32it/s]

 52%|█████▏    | 1688/3268 [06:35<06:06,  4.32it/s]

 52%|█████▏    | 1689/3268 [06:35<06:05,  4.32it/s]

 52%|█████▏    | 1690/3268 [06:35<06:04,  4.33it/s]

 52%|█████▏    | 1691/3268 [06:36<06:04,  4.32it/s]

 52%|█████▏    | 1692/3268 [06:36<06:04,  4.32it/s]

 52%|█████▏    | 1693/3268 [06:36<06:04,  4.32it/s]

 52%|█████▏    | 1694/3268 [06:36<06:03,  4.33it/s]

 52%|█████▏    | 1695/3268 [06:37<06:03,  4.32it/s]

 52%|█████▏    | 1696/3268 [06:37<06:04,  4.31it/s]

 52%|█████▏    | 1697/3268 [06:37<06:05,  4.30it/s]

 52%|█████▏    | 1698/3268 [06:37<06:04,  4.31it/s]

 52%|█████▏    | 1699/3268 [06:37<06:04,  4.31it/s]

 52%|█████▏    | 1700/3268 [06:38<06:04,  4.30it/s]

 52%|█████▏    | 1701/3268 [06:38<06:03,  4.31it/s]

 52%|█████▏    | 1702/3268 [06:38<06:03,  4.31it/s]

 52%|█████▏    | 1703/3268 [06:38<06:01,  4.32it/s]

 52%|█████▏    | 1704/3268 [06:39<06:01,  4.33it/s]

 52%|█████▏    | 1705/3268 [06:39<06:01,  4.33it/s]

 52%|█████▏    | 1706/3268 [06:39<06:01,  4.32it/s]

 52%|█████▏    | 1707/3268 [06:39<06:01,  4.32it/s]

 52%|█████▏    | 1708/3268 [06:40<06:01,  4.32it/s]

 52%|█████▏    | 1709/3268 [06:40<06:00,  4.33it/s]

 52%|█████▏    | 1710/3268 [06:40<06:00,  4.32it/s]

 52%|█████▏    | 1711/3268 [06:40<06:00,  4.32it/s]

 52%|█████▏    | 1712/3268 [06:40<05:59,  4.32it/s]

 52%|█████▏    | 1713/3268 [06:41<05:59,  4.33it/s]

 52%|█████▏    | 1714/3268 [06:41<05:58,  4.33it/s]

 52%|█████▏    | 1715/3268 [06:41<05:59,  4.32it/s]

 53%|█████▎    | 1716/3268 [06:41<05:59,  4.32it/s]

 53%|█████▎    | 1717/3268 [06:42<05:58,  4.32it/s]

 53%|█████▎    | 1718/3268 [06:42<05:58,  4.32it/s]

 53%|█████▎    | 1719/3268 [06:42<05:59,  4.31it/s]

 53%|█████▎    | 1720/3268 [06:42<05:59,  4.31it/s]

 53%|█████▎    | 1721/3268 [06:43<05:58,  4.31it/s]

 53%|█████▎    | 1722/3268 [06:43<05:58,  4.31it/s]

 53%|█████▎    | 1723/3268 [06:43<05:58,  4.31it/s]

 53%|█████▎    | 1724/3268 [06:43<05:58,  4.30it/s]

 53%|█████▎    | 1725/3268 [06:43<05:59,  4.29it/s]

 53%|█████▎    | 1726/3268 [06:44<05:58,  4.30it/s]

 53%|█████▎    | 1727/3268 [06:44<05:58,  4.30it/s]

 53%|█████▎    | 1728/3268 [06:44<05:57,  4.30it/s]

 53%|█████▎    | 1729/3268 [06:44<05:57,  4.30it/s]

 53%|█████▎    | 1730/3268 [06:45<05:58,  4.29it/s]

 53%|█████▎    | 1731/3268 [06:45<05:58,  4.29it/s]

 53%|█████▎    | 1732/3268 [06:45<05:57,  4.30it/s]

 53%|█████▎    | 1733/3268 [06:45<05:58,  4.28it/s]

 53%|█████▎    | 1734/3268 [06:46<05:58,  4.28it/s]

 53%|█████▎    | 1735/3268 [06:46<05:58,  4.28it/s]

 53%|█████▎    | 1736/3268 [06:46<05:58,  4.27it/s]

 53%|█████▎    | 1737/3268 [06:46<05:57,  4.28it/s]

 53%|█████▎    | 1738/3268 [06:47<05:57,  4.28it/s]

 53%|█████▎    | 1739/3268 [06:47<05:58,  4.27it/s]

 53%|█████▎    | 1740/3268 [06:47<05:58,  4.26it/s]

 53%|█████▎    | 1741/3268 [06:47<05:56,  4.28it/s]

 53%|█████▎    | 1742/3268 [06:47<05:55,  4.29it/s]

 53%|█████▎    | 1743/3268 [06:48<05:54,  4.30it/s]

 53%|█████▎    | 1744/3268 [06:48<05:54,  4.30it/s]

 53%|█████▎    | 1745/3268 [06:48<05:54,  4.29it/s]

 53%|█████▎    | 1746/3268 [06:48<05:54,  4.30it/s]

 53%|█████▎    | 1747/3268 [06:49<05:53,  4.30it/s]

 53%|█████▎    | 1748/3268 [06:49<05:53,  4.31it/s]

 54%|█████▎    | 1749/3268 [06:49<05:52,  4.31it/s]

 54%|█████▎    | 1750/3268 [06:49<05:52,  4.31it/s]

 54%|█████▎    | 1751/3268 [06:50<05:54,  4.28it/s]

 54%|█████▎    | 1752/3268 [06:50<05:53,  4.28it/s]

 54%|█████▎    | 1753/3268 [06:50<05:53,  4.29it/s]

 54%|█████▎    | 1754/3268 [06:50<05:52,  4.29it/s]

 54%|█████▎    | 1755/3268 [06:50<05:52,  4.29it/s]

 54%|█████▎    | 1756/3268 [06:51<05:52,  4.29it/s]

 54%|█████▍    | 1757/3268 [06:51<05:51,  4.30it/s]

 54%|█████▍    | 1758/3268 [06:51<05:50,  4.30it/s]

 54%|█████▍    | 1759/3268 [06:51<05:50,  4.30it/s]

 54%|█████▍    | 1760/3268 [06:52<05:50,  4.30it/s]

 54%|█████▍    | 1761/3268 [06:52<05:50,  4.29it/s]

 54%|█████▍    | 1762/3268 [06:52<05:50,  4.30it/s]

 54%|█████▍    | 1763/3268 [06:52<05:50,  4.29it/s]

 54%|█████▍    | 1764/3268 [06:53<05:50,  4.29it/s]

 54%|█████▍    | 1765/3268 [06:53<05:50,  4.29it/s]

 54%|█████▍    | 1766/3268 [06:53<05:50,  4.29it/s]

 54%|█████▍    | 1767/3268 [06:53<05:49,  4.30it/s]

 54%|█████▍    | 1768/3268 [06:53<05:48,  4.30it/s]

 54%|█████▍    | 1769/3268 [06:54<05:49,  4.29it/s]

 54%|█████▍    | 1770/3268 [06:54<05:49,  4.28it/s]

 54%|█████▍    | 1771/3268 [06:54<05:50,  4.27it/s]

 54%|█████▍    | 1772/3268 [06:54<05:49,  4.28it/s]

 54%|█████▍    | 1773/3268 [06:55<05:49,  4.27it/s]

 54%|█████▍    | 1774/3268 [06:55<05:50,  4.27it/s]

 54%|█████▍    | 1775/3268 [06:55<05:52,  4.24it/s]

 54%|█████▍    | 1776/3268 [06:55<05:51,  4.25it/s]

 54%|█████▍    | 1777/3268 [06:56<05:49,  4.26it/s]

 54%|█████▍    | 1778/3268 [06:56<05:48,  4.27it/s]

 54%|█████▍    | 1779/3268 [06:56<05:48,  4.27it/s]

 54%|█████▍    | 1780/3268 [06:56<05:47,  4.28it/s]

 54%|█████▍    | 1781/3268 [06:57<05:47,  4.27it/s]

 55%|█████▍    | 1782/3268 [06:57<05:47,  4.28it/s]

 55%|█████▍    | 1783/3268 [06:57<05:47,  4.27it/s]

 55%|█████▍    | 1784/3268 [06:57<05:48,  4.26it/s]

 55%|█████▍    | 1785/3268 [06:57<05:47,  4.27it/s]

 55%|█████▍    | 1786/3268 [06:58<05:48,  4.26it/s]

 55%|█████▍    | 1787/3268 [06:58<05:46,  4.27it/s]

 55%|█████▍    | 1788/3268 [06:58<05:46,  4.28it/s]

 55%|█████▍    | 1789/3268 [06:58<05:45,  4.28it/s]

 55%|█████▍    | 1790/3268 [06:59<05:45,  4.28it/s]

 55%|█████▍    | 1791/3268 [06:59<05:45,  4.27it/s]

 55%|█████▍    | 1792/3268 [06:59<05:45,  4.28it/s]

 55%|█████▍    | 1793/3268 [06:59<05:45,  4.27it/s]

 55%|█████▍    | 1794/3268 [07:00<05:45,  4.27it/s]

 55%|█████▍    | 1795/3268 [07:00<05:44,  4.28it/s]

 55%|█████▍    | 1796/3268 [07:00<05:43,  4.28it/s]

 55%|█████▍    | 1797/3268 [07:00<05:43,  4.28it/s]

 55%|█████▌    | 1798/3268 [07:01<05:43,  4.28it/s]

 55%|█████▌    | 1799/3268 [07:01<05:43,  4.28it/s]

 55%|█████▌    | 1800/3268 [07:01<05:42,  4.28it/s]

 55%|█████▌    | 1801/3268 [07:01<05:43,  4.27it/s]

 55%|█████▌    | 1802/3268 [07:01<05:42,  4.28it/s]

 55%|█████▌    | 1803/3268 [07:02<05:42,  4.28it/s]

 55%|█████▌    | 1804/3268 [07:02<05:42,  4.28it/s]

 55%|█████▌    | 1805/3268 [07:02<05:42,  4.28it/s]

 55%|█████▌    | 1806/3268 [07:02<05:41,  4.28it/s]

 55%|█████▌    | 1807/3268 [07:03<05:45,  4.23it/s]

 55%|█████▌    | 1808/3268 [07:03<05:43,  4.25it/s]

 55%|█████▌    | 1809/3268 [07:03<05:42,  4.26it/s]

 55%|█████▌    | 1810/3268 [07:03<05:41,  4.26it/s]

 55%|█████▌    | 1811/3268 [07:04<05:41,  4.27it/s]

 55%|█████▌    | 1812/3268 [07:04<05:43,  4.24it/s]

 55%|█████▌    | 1813/3268 [07:04<05:42,  4.25it/s]

 56%|█████▌    | 1814/3268 [07:04<05:41,  4.26it/s]

 56%|█████▌    | 1815/3268 [07:05<05:40,  4.27it/s]

 56%|█████▌    | 1816/3268 [07:05<05:39,  4.28it/s]

 56%|█████▌    | 1817/3268 [07:05<05:38,  4.28it/s]

 56%|█████▌    | 1818/3268 [07:05<05:41,  4.25it/s]

 56%|█████▌    | 1819/3268 [07:05<05:41,  4.25it/s]

 56%|█████▌    | 1820/3268 [07:06<05:40,  4.26it/s]

 56%|█████▌    | 1821/3268 [07:06<05:40,  4.25it/s]

 56%|█████▌    | 1822/3268 [07:06<05:41,  4.24it/s]

 56%|█████▌    | 1823/3268 [07:06<05:40,  4.25it/s]

 56%|█████▌    | 1824/3268 [07:07<05:38,  4.26it/s]

 56%|█████▌    | 1825/3268 [07:07<05:38,  4.26it/s]

 56%|█████▌    | 1826/3268 [07:07<05:38,  4.26it/s]

 56%|█████▌    | 1827/3268 [07:07<05:37,  4.27it/s]

 56%|█████▌    | 1828/3268 [07:08<05:37,  4.27it/s]

 56%|█████▌    | 1829/3268 [07:08<05:36,  4.28it/s]

 56%|█████▌    | 1830/3268 [07:08<05:36,  4.28it/s]

 56%|█████▌    | 1831/3268 [07:08<05:35,  4.28it/s]

 56%|█████▌    | 1832/3268 [07:08<05:36,  4.27it/s]

 56%|█████▌    | 1833/3268 [07:09<05:36,  4.26it/s]

 56%|█████▌    | 1834/3268 [07:09<05:36,  4.26it/s]

 56%|█████▌    | 1835/3268 [07:09<05:35,  4.27it/s]

 56%|█████▌    | 1836/3268 [07:09<05:35,  4.27it/s]

 56%|█████▌    | 1837/3268 [07:10<05:36,  4.26it/s]

 56%|█████▌    | 1838/3268 [07:10<05:36,  4.25it/s]

 56%|█████▋    | 1839/3268 [07:10<05:35,  4.26it/s]

 56%|█████▋    | 1840/3268 [07:10<05:34,  4.27it/s]

 56%|█████▋    | 1841/3268 [07:11<05:34,  4.27it/s]

 56%|█████▋    | 1842/3268 [07:11<05:33,  4.28it/s]

 56%|█████▋    | 1843/3268 [07:11<05:33,  4.27it/s]

 56%|█████▋    | 1844/3268 [07:11<05:34,  4.26it/s]

 56%|█████▋    | 1845/3268 [07:12<05:33,  4.26it/s]

 56%|█████▋    | 1846/3268 [07:12<05:33,  4.26it/s]

 57%|█████▋    | 1847/3268 [07:12<05:33,  4.26it/s]

 57%|█████▋    | 1848/3268 [07:12<05:33,  4.26it/s]

 57%|█████▋    | 1849/3268 [07:12<05:32,  4.27it/s]

 57%|█████▋    | 1850/3268 [07:13<05:31,  4.27it/s]

 57%|█████▋    | 1851/3268 [07:13<05:32,  4.26it/s]

 57%|█████▋    | 1852/3268 [07:13<05:32,  4.25it/s]

 57%|█████▋    | 1853/3268 [07:13<05:32,  4.26it/s]

 57%|█████▋    | 1854/3268 [07:14<05:32,  4.25it/s]

 57%|█████▋    | 1855/3268 [07:14<05:31,  4.26it/s]

 57%|█████▋    | 1856/3268 [07:14<05:31,  4.26it/s]

 57%|█████▋    | 1857/3268 [07:14<05:30,  4.27it/s]

 57%|█████▋    | 1858/3268 [07:15<05:31,  4.26it/s]

 57%|█████▋    | 1859/3268 [07:15<05:30,  4.26it/s]

 57%|█████▋    | 1860/3268 [07:15<05:30,  4.27it/s]

 57%|█████▋    | 1861/3268 [07:15<05:29,  4.27it/s]

 57%|█████▋    | 1862/3268 [07:16<05:29,  4.27it/s]

 57%|█████▋    | 1863/3268 [07:16<05:28,  4.27it/s]

 57%|█████▋    | 1864/3268 [07:16<05:28,  4.27it/s]

 57%|█████▋    | 1865/3268 [07:16<05:28,  4.27it/s]

 57%|█████▋    | 1866/3268 [07:16<05:29,  4.26it/s]

 57%|█████▋    | 1867/3268 [07:17<05:29,  4.25it/s]

 57%|█████▋    | 1868/3268 [07:17<05:28,  4.26it/s]

 57%|█████▋    | 1869/3268 [07:17<05:28,  4.26it/s]

 57%|█████▋    | 1870/3268 [07:17<05:28,  4.25it/s]

 57%|█████▋    | 1871/3268 [07:18<05:28,  4.25it/s]

 57%|█████▋    | 1872/3268 [07:18<05:27,  4.26it/s]

 57%|█████▋    | 1873/3268 [07:18<05:27,  4.26it/s]

 57%|█████▋    | 1874/3268 [07:18<05:27,  4.26it/s]

 57%|█████▋    | 1875/3268 [07:19<05:27,  4.25it/s]

 57%|█████▋    | 1876/3268 [07:19<05:26,  4.26it/s]

 57%|█████▋    | 1877/3268 [07:19<05:26,  4.26it/s]

logging
logging the anndata

 57%|█████▋    | 1878/3268 [07:21<16:04,  1.44it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 57%|█████▋    | 1879/3268 [07:21<12:49,  1.80it/s]

 58%|█████▊    | 1880/3268 [07:21<10:32,  2.20it/s]

 58%|█████▊    | 1881/3268 [07:21<08:56,  2.59it/s]

 58%|█████▊    | 1882/3268 [07:22<07:50,  2.95it/s]

 58%|█████▊    | 1883/3268 [07:22<07:03,  3.27it/s]

 58%|█████▊    | 1884/3268 [07:22<06:31,  3.53it/s]

 58%|█████▊    | 1885/3268 [07:22<06:09,  3.74it/s]

 58%|█████▊    | 1886/3268 [07:23<05:52,  3.92it/s]

 58%|█████▊    | 1887/3268 [07:23<05:41,  4.05it/s]

 58%|█████▊    | 1888/3268 [07:23<05:34,  4.13it/s]

 58%|█████▊    | 1889/3268 [07:23<05:27,  4.21it/s]

 58%|█████▊    | 1890/3268 [07:24<05:24,  4.25it/s]

 58%|█████▊    | 1891/3268 [07:24<05:20,  4.29it/s]

 58%|█████▊    | 1892/3268 [07:24<05:18,  4.32it/s]

 58%|█████▊    | 1893/3268 [07:24<05:17,  4.33it/s]

 58%|█████▊    | 1894/3268 [07:24<05:15,  4.36it/s]

 58%|█████▊    | 1895/3268 [07:25<05:14,  4.37it/s]

 58%|█████▊    | 1896/3268 [07:25<05:13,  4.38it/s]

 58%|█████▊    | 1897/3268 [07:25<05:12,  4.38it/s]

 58%|█████▊    | 1898/3268 [07:25<05:12,  4.38it/s]

 58%|█████▊    | 1899/3268 [07:26<05:12,  4.38it/s]

 58%|█████▊    | 1900/3268 [07:26<05:12,  4.38it/s]

 58%|█████▊    | 1901/3268 [07:26<05:12,  4.38it/s]

 58%|█████▊    | 1902/3268 [07:26<05:12,  4.37it/s]

 58%|█████▊    | 1903/3268 [07:27<05:11,  4.38it/s]

 58%|█████▊    | 1904/3268 [07:27<05:11,  4.38it/s]

 58%|█████▊    | 1905/3268 [07:27<05:11,  4.38it/s]

 58%|█████▊    | 1906/3268 [07:27<05:11,  4.38it/s]

 58%|█████▊    | 1907/3268 [07:27<05:12,  4.36it/s]

 58%|█████▊    | 1908/3268 [07:28<05:10,  4.37it/s]

 58%|█████▊    | 1909/3268 [07:28<05:11,  4.37it/s]

 58%|█████▊    | 1910/3268 [07:28<05:10,  4.37it/s]

 58%|█████▊    | 1911/3268 [07:28<05:10,  4.37it/s]

 59%|█████▊    | 1912/3268 [07:29<05:10,  4.37it/s]

 59%|█████▊    | 1913/3268 [07:29<05:10,  4.36it/s]

 59%|█████▊    | 1914/3268 [07:29<05:10,  4.36it/s]

 59%|█████▊    | 1915/3268 [07:29<05:09,  4.37it/s]

 59%|█████▊    | 1916/3268 [07:29<05:08,  4.38it/s]

 59%|█████▊    | 1917/3268 [07:30<05:08,  4.38it/s]

 59%|█████▊    | 1918/3268 [07:30<05:08,  4.37it/s]

 59%|█████▊    | 1919/3268 [07:30<05:08,  4.38it/s]

 59%|█████▉    | 1920/3268 [07:30<05:07,  4.38it/s]

 59%|█████▉    | 1921/3268 [07:31<05:07,  4.38it/s]

 59%|█████▉    | 1922/3268 [07:31<05:06,  4.39it/s]

 59%|█████▉    | 1923/3268 [07:31<05:06,  4.38it/s]

 59%|█████▉    | 1924/3268 [07:31<05:08,  4.35it/s]

 59%|█████▉    | 1925/3268 [07:32<05:07,  4.36it/s]

 59%|█████▉    | 1926/3268 [07:32<05:07,  4.36it/s]

 59%|█████▉    | 1927/3268 [07:32<05:06,  4.37it/s]

 59%|█████▉    | 1928/3268 [07:32<05:06,  4.37it/s]

 59%|█████▉    | 1929/3268 [07:32<05:06,  4.36it/s]

 59%|█████▉    | 1930/3268 [07:33<05:05,  4.37it/s]

 59%|█████▉    | 1931/3268 [07:33<05:06,  4.37it/s]

 59%|█████▉    | 1932/3268 [07:33<05:06,  4.37it/s]

 59%|█████▉    | 1933/3268 [07:33<05:05,  4.37it/s]

 59%|█████▉    | 1934/3268 [07:34<05:06,  4.36it/s]

 59%|█████▉    | 1935/3268 [07:34<05:06,  4.35it/s]

 59%|█████▉    | 1936/3268 [07:34<05:05,  4.36it/s]

 59%|█████▉    | 1937/3268 [07:34<05:05,  4.36it/s]

 59%|█████▉    | 1938/3268 [07:35<05:04,  4.36it/s]

 59%|█████▉    | 1939/3268 [07:35<05:04,  4.36it/s]

 59%|█████▉    | 1940/3268 [07:35<05:04,  4.36it/s]

 59%|█████▉    | 1941/3268 [07:35<05:03,  4.37it/s]

 59%|█████▉    | 1942/3268 [07:35<05:03,  4.37it/s]

 59%|█████▉    | 1943/3268 [07:36<05:03,  4.37it/s]

 59%|█████▉    | 1944/3268 [07:36<05:03,  4.36it/s]

 60%|█████▉    | 1945/3268 [07:36<05:03,  4.35it/s]

 60%|█████▉    | 1946/3268 [07:36<05:03,  4.36it/s]

 60%|█████▉    | 1947/3268 [07:37<05:02,  4.36it/s]

 60%|█████▉    | 1948/3268 [07:37<05:02,  4.37it/s]

 60%|█████▉    | 1949/3268 [07:37<05:01,  4.37it/s]

 60%|█████▉    | 1950/3268 [07:37<05:00,  4.38it/s]

 60%|█████▉    | 1951/3268 [07:38<05:00,  4.38it/s]

 60%|█████▉    | 1952/3268 [07:38<05:01,  4.37it/s]

 60%|█████▉    | 1953/3268 [07:38<05:01,  4.37it/s]

 60%|█████▉    | 1954/3268 [07:38<05:00,  4.37it/s]

 60%|█████▉    | 1955/3268 [07:38<04:59,  4.38it/s]

 60%|█████▉    | 1956/3268 [07:39<04:59,  4.38it/s]

 60%|█████▉    | 1957/3268 [07:39<04:59,  4.38it/s]

 60%|█████▉    | 1958/3268 [07:39<04:59,  4.38it/s]

 60%|█████▉    | 1959/3268 [07:39<04:59,  4.37it/s]

 60%|█████▉    | 1960/3268 [07:40<04:59,  4.37it/s]

 60%|██████    | 1961/3268 [07:40<04:59,  4.37it/s]

 60%|██████    | 1962/3268 [07:40<04:59,  4.36it/s]

 60%|██████    | 1963/3268 [07:40<04:59,  4.36it/s]

 60%|██████    | 1964/3268 [07:40<04:59,  4.36it/s]

 60%|██████    | 1965/3268 [07:41<04:59,  4.35it/s]

 60%|██████    | 1966/3268 [07:41<04:58,  4.36it/s]

 60%|██████    | 1967/3268 [07:41<04:58,  4.36it/s]

 60%|██████    | 1968/3268 [07:41<05:01,  4.31it/s]

 60%|██████    | 1969/3268 [07:42<05:00,  4.33it/s]

 60%|██████    | 1970/3268 [07:42<04:59,  4.33it/s]

 60%|██████    | 1971/3268 [07:42<04:58,  4.34it/s]

 60%|██████    | 1972/3268 [07:42<04:58,  4.34it/s]

 60%|██████    | 1973/3268 [07:43<04:57,  4.35it/s]

 60%|██████    | 1974/3268 [07:43<04:57,  4.35it/s]

 60%|██████    | 1975/3268 [07:43<04:56,  4.36it/s]

 60%|██████    | 1976/3268 [07:43<04:57,  4.35it/s]

 60%|██████    | 1977/3268 [07:43<04:56,  4.36it/s]

 61%|██████    | 1978/3268 [07:44<04:55,  4.37it/s]

 61%|██████    | 1979/3268 [07:44<04:55,  4.37it/s]

 61%|██████    | 1980/3268 [07:44<04:55,  4.36it/s]

 61%|██████    | 1981/3268 [07:44<04:55,  4.36it/s]

 61%|██████    | 1982/3268 [07:45<04:54,  4.36it/s]

 61%|██████    | 1983/3268 [07:45<04:54,  4.36it/s]

 61%|██████    | 1984/3268 [07:45<04:54,  4.36it/s]

 61%|██████    | 1985/3268 [07:45<04:54,  4.35it/s]

 61%|██████    | 1986/3268 [07:46<04:54,  4.36it/s]

 61%|██████    | 1987/3268 [07:46<04:53,  4.36it/s]

 61%|██████    | 1988/3268 [07:46<04:53,  4.37it/s]

 61%|██████    | 1989/3268 [07:46<04:53,  4.36it/s]

 61%|██████    | 1990/3268 [07:46<04:54,  4.34it/s]

 61%|██████    | 1991/3268 [07:47<04:53,  4.36it/s]

 61%|██████    | 1992/3268 [07:47<04:53,  4.34it/s]

 61%|██████    | 1993/3268 [07:47<04:53,  4.35it/s]

 61%|██████    | 1994/3268 [07:47<04:52,  4.35it/s]

 61%|██████    | 1995/3268 [07:48<04:52,  4.36it/s]

 61%|██████    | 1996/3268 [07:48<04:51,  4.36it/s]

 61%|██████    | 1997/3268 [07:48<04:50,  4.37it/s]

 61%|██████    | 1998/3268 [07:48<04:50,  4.37it/s]

 61%|██████    | 1999/3268 [07:49<04:50,  4.37it/s]

 61%|██████    | 2000/3268 [07:49<04:51,  4.36it/s]

 61%|██████    | 2001/3268 [07:49<04:50,  4.36it/s]

 61%|██████▏   | 2002/3268 [07:49<04:50,  4.36it/s]

 61%|██████▏   | 2003/3268 [07:49<04:50,  4.35it/s]

 61%|██████▏   | 2004/3268 [07:50<04:50,  4.35it/s]

 61%|██████▏   | 2005/3268 [07:50<04:50,  4.35it/s]

 61%|██████▏   | 2006/3268 [07:50<04:50,  4.35it/s]

 61%|██████▏   | 2007/3268 [07:50<04:49,  4.35it/s]

 61%|██████▏   | 2008/3268 [07:51<04:49,  4.35it/s]

 61%|██████▏   | 2009/3268 [07:51<04:49,  4.36it/s]

 62%|██████▏   | 2010/3268 [07:51<04:48,  4.36it/s]

 62%|██████▏   | 2011/3268 [07:51<04:47,  4.37it/s]

 62%|██████▏   | 2012/3268 [07:52<04:49,  4.34it/s]

 62%|██████▏   | 2013/3268 [07:52<04:48,  4.34it/s]

 62%|██████▏   | 2014/3268 [07:52<04:48,  4.35it/s]

 62%|██████▏   | 2015/3268 [07:52<04:47,  4.36it/s]

 62%|██████▏   | 2016/3268 [07:52<04:47,  4.35it/s]

 62%|██████▏   | 2017/3268 [07:53<04:46,  4.36it/s]

 62%|██████▏   | 2018/3268 [07:53<04:46,  4.36it/s]

 62%|██████▏   | 2019/3268 [07:53<04:46,  4.35it/s]

 62%|██████▏   | 2020/3268 [07:53<04:46,  4.36it/s]

 62%|██████▏   | 2021/3268 [07:54<04:46,  4.35it/s]

 62%|██████▏   | 2022/3268 [07:54<04:45,  4.36it/s]

 62%|██████▏   | 2023/3268 [07:54<04:45,  4.36it/s]

 62%|██████▏   | 2024/3268 [07:54<04:45,  4.36it/s]

 62%|██████▏   | 2025/3268 [07:54<04:45,  4.35it/s]

 62%|██████▏   | 2026/3268 [07:55<04:45,  4.35it/s]

 62%|██████▏   | 2027/3268 [07:55<04:45,  4.35it/s]

 62%|██████▏   | 2028/3268 [07:55<04:44,  4.35it/s]

 62%|██████▏   | 2029/3268 [07:55<04:44,  4.35it/s]

 62%|██████▏   | 2030/3268 [07:56<04:44,  4.35it/s]

 62%|██████▏   | 2031/3268 [07:56<04:44,  4.35it/s]

 62%|██████▏   | 2032/3268 [07:56<04:44,  4.35it/s]

 62%|██████▏   | 2033/3268 [07:56<04:43,  4.36it/s]

 62%|██████▏   | 2034/3268 [07:57<04:42,  4.36it/s]

 62%|██████▏   | 2035/3268 [07:57<04:42,  4.36it/s]

 62%|██████▏   | 2036/3268 [07:57<04:42,  4.36it/s]

 62%|██████▏   | 2037/3268 [07:57<04:42,  4.35it/s]

 62%|██████▏   | 2038/3268 [07:57<04:42,  4.36it/s]

 62%|██████▏   | 2039/3268 [07:58<04:42,  4.35it/s]

 62%|██████▏   | 2040/3268 [07:58<04:42,  4.35it/s]

 62%|██████▏   | 2041/3268 [07:58<04:42,  4.35it/s]

 62%|██████▏   | 2042/3268 [07:58<04:42,  4.35it/s]

 63%|██████▎   | 2043/3268 [07:59<04:42,  4.34it/s]

 63%|██████▎   | 2044/3268 [07:59<04:41,  4.35it/s]

 63%|██████▎   | 2045/3268 [07:59<04:42,  4.34it/s]

 63%|██████▎   | 2046/3268 [07:59<04:41,  4.34it/s]

 63%|██████▎   | 2047/3268 [08:00<04:42,  4.33it/s]

 63%|██████▎   | 2048/3268 [08:00<04:41,  4.33it/s]

 63%|██████▎   | 2049/3268 [08:00<04:40,  4.34it/s]

 63%|██████▎   | 2050/3268 [08:00<04:40,  4.35it/s]

 63%|██████▎   | 2051/3268 [08:00<04:42,  4.31it/s]

 63%|██████▎   | 2052/3268 [08:01<04:41,  4.32it/s]

 63%|██████▎   | 2053/3268 [08:01<04:40,  4.33it/s]

 63%|██████▎   | 2054/3268 [08:01<04:39,  4.34it/s]

 63%|██████▎   | 2055/3268 [08:01<04:39,  4.33it/s]

 63%|██████▎   | 2056/3268 [08:02<04:39,  4.34it/s]

 63%|██████▎   | 2057/3268 [08:02<04:38,  4.35it/s]

 63%|██████▎   | 2058/3268 [08:02<04:38,  4.34it/s]

 63%|██████▎   | 2059/3268 [08:02<04:39,  4.33it/s]

 63%|██████▎   | 2060/3268 [08:03<04:38,  4.33it/s]

 63%|██████▎   | 2061/3268 [08:03<04:38,  4.33it/s]

 63%|██████▎   | 2062/3268 [08:03<04:37,  4.34it/s]

 63%|██████▎   | 2063/3268 [08:03<04:37,  4.35it/s]

 63%|██████▎   | 2064/3268 [08:03<04:37,  4.34it/s]

 63%|██████▎   | 2065/3268 [08:04<04:36,  4.35it/s]

 63%|██████▎   | 2066/3268 [08:04<04:36,  4.34it/s]

 63%|██████▎   | 2067/3268 [08:04<04:36,  4.34it/s]

 63%|██████▎   | 2068/3268 [08:04<04:37,  4.33it/s]

 63%|██████▎   | 2069/3268 [08:05<04:37,  4.32it/s]

 63%|██████▎   | 2070/3268 [08:05<04:36,  4.33it/s]

 63%|██████▎   | 2071/3268 [08:05<04:36,  4.33it/s]

 63%|██████▎   | 2072/3268 [08:05<04:36,  4.33it/s]

 63%|██████▎   | 2073/3268 [08:06<04:35,  4.34it/s]

 63%|██████▎   | 2074/3268 [08:06<04:34,  4.34it/s]

 63%|██████▎   | 2075/3268 [08:06<04:34,  4.34it/s]

 64%|██████▎   | 2076/3268 [08:06<04:34,  4.34it/s]

 64%|██████▎   | 2077/3268 [08:06<04:34,  4.33it/s]

 64%|██████▎   | 2078/3268 [08:07<04:34,  4.34it/s]

 64%|██████▎   | 2079/3268 [08:07<04:33,  4.34it/s]

 64%|██████▎   | 2080/3268 [08:07<04:33,  4.35it/s]

 64%|██████▎   | 2081/3268 [08:07<04:32,  4.35it/s]

 64%|██████▎   | 2082/3268 [08:08<04:32,  4.35it/s]

 64%|██████▎   | 2083/3268 [08:08<04:33,  4.34it/s]

 64%|██████▍   | 2084/3268 [08:08<04:32,  4.35it/s]

 64%|██████▍   | 2085/3268 [08:08<04:32,  4.35it/s]

 64%|██████▍   | 2086/3268 [08:09<04:31,  4.35it/s]

 64%|██████▍   | 2087/3268 [08:09<04:31,  4.34it/s]

 64%|██████▍   | 2088/3268 [08:09<04:32,  4.34it/s]

 64%|██████▍   | 2089/3268 [08:09<04:31,  4.34it/s]

 64%|██████▍   | 2090/3268 [08:09<04:31,  4.33it/s]

 64%|██████▍   | 2091/3268 [08:10<04:31,  4.33it/s]

 64%|██████▍   | 2092/3268 [08:10<04:31,  4.34it/s]

 64%|██████▍   | 2093/3268 [08:10<04:31,  4.33it/s]

 64%|██████▍   | 2094/3268 [08:10<04:31,  4.33it/s]

 64%|██████▍   | 2095/3268 [08:11<04:30,  4.33it/s]

 64%|██████▍   | 2096/3268 [08:11<04:30,  4.33it/s]

 64%|██████▍   | 2097/3268 [08:11<04:30,  4.33it/s]

 64%|██████▍   | 2098/3268 [08:11<04:30,  4.32it/s]

 64%|██████▍   | 2099/3268 [08:12<04:30,  4.33it/s]

 64%|██████▍   | 2100/3268 [08:12<04:31,  4.31it/s]

 64%|██████▍   | 2101/3268 [08:12<04:30,  4.32it/s]

 64%|██████▍   | 2102/3268 [08:12<04:29,  4.32it/s]

 64%|██████▍   | 2103/3268 [08:12<04:29,  4.33it/s]

 64%|██████▍   | 2104/3268 [08:13<04:29,  4.32it/s]

 64%|██████▍   | 2105/3268 [08:13<04:28,  4.34it/s]

 64%|██████▍   | 2106/3268 [08:13<04:28,  4.33it/s]

 64%|██████▍   | 2107/3268 [08:13<04:27,  4.34it/s]

 65%|██████▍   | 2108/3268 [08:14<04:27,  4.33it/s]

 65%|██████▍   | 2109/3268 [08:14<04:27,  4.33it/s]

 65%|██████▍   | 2110/3268 [08:14<04:27,  4.34it/s]

 65%|██████▍   | 2111/3268 [08:14<04:26,  4.34it/s]

 65%|██████▍   | 2112/3268 [08:15<04:26,  4.33it/s]

 65%|██████▍   | 2113/3268 [08:15<04:25,  4.34it/s]

 65%|██████▍   | 2114/3268 [08:15<04:25,  4.35it/s]

 65%|██████▍   | 2115/3268 [08:15<04:25,  4.35it/s]

 65%|██████▍   | 2116/3268 [08:15<04:25,  4.34it/s]

 65%|██████▍   | 2117/3268 [08:16<04:25,  4.34it/s]

 65%|██████▍   | 2118/3268 [08:16<04:24,  4.35it/s]

 65%|██████▍   | 2119/3268 [08:16<04:24,  4.34it/s]

 65%|██████▍   | 2120/3268 [08:16<04:24,  4.34it/s]

 65%|██████▍   | 2121/3268 [08:17<04:23,  4.35it/s]

 65%|██████▍   | 2122/3268 [08:17<04:23,  4.35it/s]

 65%|██████▍   | 2123/3268 [08:17<04:23,  4.34it/s]

 65%|██████▍   | 2124/3268 [08:17<04:23,  4.34it/s]

 65%|██████▌   | 2125/3268 [08:18<04:23,  4.34it/s]

 65%|██████▌   | 2126/3268 [08:18<04:23,  4.33it/s]

 65%|██████▌   | 2127/3268 [08:18<04:23,  4.33it/s]

 65%|██████▌   | 2128/3268 [08:18<04:22,  4.34it/s]

 65%|██████▌   | 2129/3268 [08:18<04:22,  4.34it/s]

 65%|██████▌   | 2130/3268 [08:19<04:21,  4.34it/s]

 65%|██████▌   | 2131/3268 [08:19<04:21,  4.34it/s]

 65%|██████▌   | 2132/3268 [08:19<04:21,  4.35it/s]

 65%|██████▌   | 2133/3268 [08:19<04:21,  4.34it/s]

 65%|██████▌   | 2134/3268 [08:20<04:21,  4.33it/s]

 65%|██████▌   | 2135/3268 [08:20<04:21,  4.33it/s]

 65%|██████▌   | 2136/3268 [08:20<04:21,  4.33it/s]

 65%|██████▌   | 2137/3268 [08:20<04:20,  4.34it/s]

 65%|██████▌   | 2138/3268 [08:21<04:20,  4.34it/s]

 65%|██████▌   | 2139/3268 [08:21<04:19,  4.35it/s]

 65%|██████▌   | 2140/3268 [08:21<04:18,  4.36it/s]

 66%|██████▌   | 2141/3268 [08:21<04:18,  4.36it/s]

 66%|██████▌   | 2142/3268 [08:21<04:19,  4.35it/s]

 66%|██████▌   | 2143/3268 [08:22<04:18,  4.35it/s]

 66%|██████▌   | 2144/3268 [08:22<04:18,  4.35it/s]

 66%|██████▌   | 2145/3268 [08:22<04:18,  4.35it/s]

 66%|██████▌   | 2146/3268 [08:22<04:18,  4.34it/s]

 66%|██████▌   | 2147/3268 [08:23<04:18,  4.34it/s]

 66%|██████▌   | 2148/3268 [08:23<04:17,  4.34it/s]

 66%|██████▌   | 2149/3268 [08:23<04:18,  4.33it/s]

 66%|██████▌   | 2150/3268 [08:23<04:18,  4.33it/s]

 66%|██████▌   | 2151/3268 [08:24<04:18,  4.33it/s]

 66%|██████▌   | 2152/3268 [08:24<04:17,  4.33it/s]

 66%|██████▌   | 2153/3268 [08:24<04:16,  4.34it/s]

 66%|██████▌   | 2154/3268 [08:24<04:17,  4.33it/s]

 66%|██████▌   | 2155/3268 [08:24<04:17,  4.33it/s]

 66%|██████▌   | 2156/3268 [08:25<04:16,  4.34it/s]

 66%|██████▌   | 2157/3268 [08:25<04:16,  4.33it/s]

 66%|██████▌   | 2158/3268 [08:25<04:19,  4.28it/s]

 66%|██████▌   | 2159/3268 [08:25<04:18,  4.29it/s]

 66%|██████▌   | 2160/3268 [08:26<04:17,  4.30it/s]

 66%|██████▌   | 2161/3268 [08:26<04:16,  4.31it/s]

 66%|██████▌   | 2162/3268 [08:26<04:16,  4.32it/s]

 66%|██████▌   | 2163/3268 [08:26<04:16,  4.32it/s]

 66%|██████▌   | 2164/3268 [08:27<04:15,  4.32it/s]

 66%|██████▌   | 2165/3268 [08:27<04:14,  4.33it/s]

 66%|██████▋   | 2166/3268 [08:27<04:14,  4.33it/s]

 66%|██████▋   | 2167/3268 [08:27<04:14,  4.33it/s]

 66%|██████▋   | 2168/3268 [08:27<04:15,  4.31it/s]

 66%|██████▋   | 2169/3268 [08:28<04:13,  4.33it/s]

 66%|██████▋   | 2170/3268 [08:28<04:14,  4.32it/s]

 66%|██████▋   | 2171/3268 [08:28<04:13,  4.32it/s]

 66%|██████▋   | 2172/3268 [08:28<04:13,  4.33it/s]

 66%|██████▋   | 2173/3268 [08:29<04:12,  4.33it/s]

 67%|██████▋   | 2174/3268 [08:29<04:12,  4.33it/s]

 67%|██████▋   | 2175/3268 [08:29<04:11,  4.34it/s]

 67%|██████▋   | 2176/3268 [08:29<04:11,  4.34it/s]

 67%|██████▋   | 2177/3268 [08:30<04:11,  4.34it/s]

 67%|██████▋   | 2178/3268 [08:30<04:11,  4.33it/s]

 67%|██████▋   | 2179/3268 [08:30<04:11,  4.33it/s]

 67%|██████▋   | 2180/3268 [08:30<04:13,  4.30it/s]

 67%|██████▋   | 2181/3268 [08:30<04:11,  4.32it/s]

 67%|██████▋   | 2182/3268 [08:31<04:10,  4.33it/s]

 67%|██████▋   | 2183/3268 [08:31<04:10,  4.34it/s]

 67%|██████▋   | 2184/3268 [08:31<04:09,  4.35it/s]

 67%|██████▋   | 2185/3268 [08:31<04:08,  4.35it/s]

 67%|██████▋   | 2186/3268 [08:32<04:08,  4.35it/s]

 67%|██████▋   | 2187/3268 [08:32<04:08,  4.36it/s]

 67%|██████▋   | 2188/3268 [08:32<04:07,  4.36it/s]

 67%|██████▋   | 2189/3268 [08:32<04:07,  4.35it/s]

 67%|██████▋   | 2190/3268 [08:33<04:07,  4.36it/s]

 67%|██████▋   | 2191/3268 [08:33<04:07,  4.34it/s]

 67%|██████▋   | 2192/3268 [08:33<04:07,  4.34it/s]

 67%|██████▋   | 2193/3268 [08:33<04:06,  4.35it/s]

 67%|██████▋   | 2194/3268 [08:33<04:07,  4.34it/s]

 67%|██████▋   | 2195/3268 [08:34<04:07,  4.33it/s]

 67%|██████▋   | 2196/3268 [08:34<04:06,  4.34it/s]

 67%|██████▋   | 2197/3268 [08:34<04:06,  4.35it/s]

 67%|██████▋   | 2198/3268 [08:34<04:07,  4.33it/s]

 67%|██████▋   | 2199/3268 [08:35<04:06,  4.34it/s]

 67%|██████▋   | 2200/3268 [08:35<04:06,  4.34it/s]

 67%|██████▋   | 2201/3268 [08:35<04:05,  4.35it/s]

 67%|██████▋   | 2202/3268 [08:35<04:05,  4.35it/s]

 67%|██████▋   | 2203/3268 [08:36<04:05,  4.34it/s]

 67%|██████▋   | 2204/3268 [08:36<04:04,  4.35it/s]

 67%|██████▋   | 2205/3268 [08:36<04:04,  4.34it/s]

 68%|██████▊   | 2206/3268 [08:36<04:05,  4.32it/s]

 68%|██████▊   | 2207/3268 [08:36<04:05,  4.33it/s]

 68%|██████▊   | 2208/3268 [08:37<04:05,  4.32it/s]

 68%|██████▊   | 2209/3268 [08:37<04:04,  4.33it/s]

 68%|██████▊   | 2210/3268 [08:37<04:04,  4.33it/s]

 68%|██████▊   | 2211/3268 [08:37<04:04,  4.33it/s]

 68%|██████▊   | 2212/3268 [08:38<04:03,  4.34it/s]

 68%|██████▊   | 2213/3268 [08:38<04:03,  4.32it/s]

 68%|██████▊   | 2214/3268 [08:38<04:04,  4.32it/s]

 68%|██████▊   | 2215/3268 [08:38<04:03,  4.33it/s]

 68%|██████▊   | 2216/3268 [08:39<04:02,  4.33it/s]

 68%|██████▊   | 2217/3268 [08:39<04:02,  4.34it/s]

 68%|██████▊   | 2218/3268 [08:39<04:01,  4.34it/s]

 68%|██████▊   | 2219/3268 [08:39<04:02,  4.33it/s]

 68%|██████▊   | 2220/3268 [08:39<04:01,  4.34it/s]

 68%|██████▊   | 2221/3268 [08:40<04:01,  4.34it/s]

 68%|██████▊   | 2222/3268 [08:40<04:01,  4.34it/s]

 68%|██████▊   | 2223/3268 [08:40<04:00,  4.34it/s]

 68%|██████▊   | 2224/3268 [08:40<04:00,  4.34it/s]

 68%|██████▊   | 2225/3268 [08:41<04:00,  4.34it/s]

 68%|██████▊   | 2226/3268 [08:41<03:59,  4.34it/s]

 68%|██████▊   | 2227/3268 [08:41<03:59,  4.34it/s]

 68%|██████▊   | 2228/3268 [08:41<03:58,  4.35it/s]

 68%|██████▊   | 2229/3268 [08:42<03:59,  4.34it/s]

 68%|██████▊   | 2230/3268 [08:42<03:59,  4.33it/s]

 68%|██████▊   | 2231/3268 [08:42<03:59,  4.34it/s]

 68%|██████▊   | 2232/3268 [08:42<03:59,  4.33it/s]

 68%|██████▊   | 2233/3268 [08:42<03:58,  4.34it/s]

 68%|██████▊   | 2234/3268 [08:43<03:58,  4.33it/s]

 68%|██████▊   | 2235/3268 [08:43<03:59,  4.32it/s]

 68%|██████▊   | 2236/3268 [08:43<03:58,  4.33it/s]

 68%|██████▊   | 2237/3268 [08:43<03:58,  4.33it/s]

 68%|██████▊   | 2238/3268 [08:44<03:59,  4.30it/s]

 69%|██████▊   | 2239/3268 [08:44<03:59,  4.30it/s]

 69%|██████▊   | 2240/3268 [08:44<03:58,  4.30it/s]

 69%|██████▊   | 2241/3268 [08:44<03:58,  4.31it/s]

 69%|██████▊   | 2242/3268 [08:45<03:57,  4.32it/s]

 69%|██████▊   | 2243/3268 [08:45<03:57,  4.32it/s]

 69%|██████▊   | 2244/3268 [08:45<03:56,  4.34it/s]

 69%|██████▊   | 2245/3268 [08:45<03:56,  4.33it/s]

 69%|██████▊   | 2246/3268 [08:45<03:55,  4.34it/s]

 69%|██████▉   | 2247/3268 [08:46<03:56,  4.32it/s]

 69%|██████▉   | 2248/3268 [08:46<03:55,  4.33it/s]

 69%|██████▉   | 2249/3268 [08:46<03:55,  4.34it/s]

 69%|██████▉   | 2250/3268 [08:46<03:54,  4.34it/s]

 69%|██████▉   | 2251/3268 [08:47<03:54,  4.33it/s]

 69%|██████▉   | 2252/3268 [08:47<03:53,  4.35it/s]

 69%|██████▉   | 2253/3268 [08:47<03:53,  4.34it/s]

 69%|██████▉   | 2254/3268 [08:47<03:53,  4.34it/s]

 69%|██████▉   | 2255/3268 [08:48<03:53,  4.34it/s]

 69%|██████▉   | 2256/3268 [08:48<03:53,  4.34it/s]

 69%|██████▉   | 2257/3268 [08:48<03:52,  4.34it/s]

 69%|██████▉   | 2258/3268 [08:48<03:52,  4.33it/s]

 69%|██████▉   | 2259/3268 [08:48<03:53,  4.33it/s]

 69%|██████▉   | 2260/3268 [08:49<03:52,  4.33it/s]

 69%|██████▉   | 2261/3268 [08:49<03:52,  4.33it/s]

 69%|██████▉   | 2262/3268 [08:49<03:52,  4.33it/s]

 69%|██████▉   | 2263/3268 [08:49<03:51,  4.34it/s]

 69%|██████▉   | 2264/3268 [08:50<03:52,  4.33it/s]

 69%|██████▉   | 2265/3268 [08:50<03:51,  4.33it/s]

 69%|██████▉   | 2266/3268 [08:50<03:51,  4.34it/s]

 69%|██████▉   | 2267/3268 [08:50<03:51,  4.33it/s]

 69%|██████▉   | 2268/3268 [08:51<03:51,  4.33it/s]

 69%|██████▉   | 2269/3268 [08:51<03:50,  4.33it/s]

 69%|██████▉   | 2270/3268 [08:51<03:50,  4.32it/s]

 69%|██████▉   | 2271/3268 [08:51<03:50,  4.33it/s]

 70%|██████▉   | 2272/3268 [08:51<03:50,  4.33it/s]

 70%|██████▉   | 2273/3268 [08:52<03:49,  4.33it/s]

 70%|██████▉   | 2274/3268 [08:52<03:49,  4.33it/s]

 70%|██████▉   | 2275/3268 [08:52<03:49,  4.32it/s]

 70%|██████▉   | 2276/3268 [08:52<03:49,  4.33it/s]

 70%|██████▉   | 2277/3268 [08:53<03:49,  4.32it/s]

 70%|██████▉   | 2278/3268 [08:53<03:49,  4.32it/s]

 70%|██████▉   | 2279/3268 [08:53<03:48,  4.33it/s]

 70%|██████▉   | 2280/3268 [08:53<03:48,  4.32it/s]

 70%|██████▉   | 2281/3268 [08:54<03:48,  4.31it/s]

 70%|██████▉   | 2282/3268 [08:54<03:48,  4.32it/s]

 70%|██████▉   | 2283/3268 [08:54<03:48,  4.32it/s]

 70%|██████▉   | 2284/3268 [08:54<03:48,  4.31it/s]

 70%|██████▉   | 2285/3268 [08:54<03:47,  4.32it/s]

 70%|██████▉   | 2286/3268 [08:55<03:47,  4.31it/s]

 70%|██████▉   | 2287/3268 [08:55<03:47,  4.31it/s]

 70%|███████   | 2288/3268 [08:55<03:47,  4.31it/s]

 70%|███████   | 2289/3268 [08:55<03:47,  4.30it/s]

 70%|███████   | 2290/3268 [08:56<03:46,  4.31it/s]

 70%|███████   | 2291/3268 [08:56<03:46,  4.31it/s]

 70%|███████   | 2292/3268 [08:56<03:46,  4.30it/s]

 70%|███████   | 2293/3268 [08:56<03:45,  4.32it/s]

 70%|███████   | 2294/3268 [08:57<03:45,  4.31it/s]

 70%|███████   | 2295/3268 [08:57<03:45,  4.31it/s]

 70%|███████   | 2296/3268 [08:57<03:45,  4.30it/s]

 70%|███████   | 2297/3268 [08:57<03:46,  4.30it/s]

 70%|███████   | 2298/3268 [08:57<03:45,  4.30it/s]

 70%|███████   | 2299/3268 [08:58<03:45,  4.31it/s]

 70%|███████   | 2300/3268 [08:58<03:45,  4.30it/s]

 70%|███████   | 2301/3268 [08:58<03:44,  4.31it/s]

 70%|███████   | 2302/3268 [08:58<03:44,  4.31it/s]

 70%|███████   | 2303/3268 [08:59<03:43,  4.31it/s]

 71%|███████   | 2304/3268 [08:59<03:43,  4.31it/s]

 71%|███████   | 2305/3268 [08:59<03:43,  4.31it/s]

 71%|███████   | 2306/3268 [08:59<03:42,  4.32it/s]

 71%|███████   | 2307/3268 [09:00<03:42,  4.32it/s]

 71%|███████   | 2308/3268 [09:00<03:42,  4.32it/s]

 71%|███████   | 2309/3268 [09:00<03:41,  4.32it/s]

 71%|███████   | 2310/3268 [09:00<03:41,  4.32it/s]

 71%|███████   | 2311/3268 [09:01<03:41,  4.32it/s]

 71%|███████   | 2312/3268 [09:01<03:40,  4.33it/s]

 71%|███████   | 2313/3268 [09:01<03:41,  4.32it/s]

 71%|███████   | 2314/3268 [09:01<03:40,  4.32it/s]

 71%|███████   | 2315/3268 [09:01<03:40,  4.32it/s]

 71%|███████   | 2316/3268 [09:02<03:40,  4.32it/s]

 71%|███████   | 2317/3268 [09:02<03:39,  4.32it/s]

 71%|███████   | 2318/3268 [09:02<03:39,  4.32it/s]

 71%|███████   | 2319/3268 [09:02<03:39,  4.32it/s]

 71%|███████   | 2320/3268 [09:03<03:39,  4.32it/s]

 71%|███████   | 2321/3268 [09:03<03:39,  4.31it/s]

 71%|███████   | 2322/3268 [09:03<03:39,  4.31it/s]

 71%|███████   | 2323/3268 [09:03<03:39,  4.31it/s]

 71%|███████   | 2324/3268 [09:04<03:39,  4.30it/s]

 71%|███████   | 2325/3268 [09:04<03:39,  4.30it/s]

 71%|███████   | 2326/3268 [09:04<03:39,  4.29it/s]

 71%|███████   | 2327/3268 [09:04<03:39,  4.29it/s]

 71%|███████   | 2328/3268 [09:04<03:38,  4.30it/s]

 71%|███████▏  | 2329/3268 [09:05<03:38,  4.29it/s]

 71%|███████▏  | 2330/3268 [09:05<03:37,  4.31it/s]

 71%|███████▏  | 2331/3268 [09:05<03:37,  4.31it/s]

 71%|███████▏  | 2332/3268 [09:05<03:37,  4.31it/s]

 71%|███████▏  | 2333/3268 [09:06<03:36,  4.31it/s]

 71%|███████▏  | 2334/3268 [09:06<03:36,  4.32it/s]

 71%|███████▏  | 2335/3268 [09:06<03:35,  4.32it/s]

 71%|███████▏  | 2336/3268 [09:06<03:35,  4.32it/s]

 72%|███████▏  | 2337/3268 [09:07<03:35,  4.32it/s]

 72%|███████▏  | 2338/3268 [09:07<03:34,  4.33it/s]

 72%|███████▏  | 2339/3268 [09:07<03:34,  4.33it/s]

 72%|███████▏  | 2340/3268 [09:07<03:34,  4.33it/s]

 72%|███████▏  | 2341/3268 [09:07<03:34,  4.32it/s]

 72%|███████▏  | 2342/3268 [09:08<03:34,  4.31it/s]

 72%|███████▏  | 2343/3268 [09:08<03:34,  4.32it/s]

 72%|███████▏  | 2344/3268 [09:08<03:33,  4.32it/s]

 72%|███████▏  | 2345/3268 [09:08<03:33,  4.32it/s]

 72%|███████▏  | 2346/3268 [09:09<03:33,  4.31it/s]

 72%|███████▏  | 2347/3268 [09:09<03:33,  4.31it/s]

 72%|███████▏  | 2348/3268 [09:09<03:33,  4.30it/s]

 72%|███████▏  | 2349/3268 [09:09<03:33,  4.30it/s]

 72%|███████▏  | 2350/3268 [09:10<03:34,  4.29it/s]

 72%|███████▏  | 2351/3268 [09:10<03:33,  4.30it/s]

 72%|███████▏  | 2352/3268 [09:10<03:33,  4.29it/s]

 72%|███████▏  | 2353/3268 [09:10<03:32,  4.30it/s]

 72%|███████▏  | 2354/3268 [09:10<03:33,  4.29it/s]

 72%|███████▏  | 2355/3268 [09:11<03:33,  4.28it/s]

 72%|███████▏  | 2356/3268 [09:11<03:32,  4.29it/s]

 72%|███████▏  | 2357/3268 [09:11<03:32,  4.29it/s]

 72%|███████▏  | 2358/3268 [09:11<03:31,  4.29it/s]

 72%|███████▏  | 2359/3268 [09:12<03:31,  4.30it/s]

 72%|███████▏  | 2360/3268 [09:12<03:31,  4.30it/s]

 72%|███████▏  | 2361/3268 [09:12<03:30,  4.30it/s]

 72%|███████▏  | 2362/3268 [09:12<03:30,  4.29it/s]

 72%|███████▏  | 2363/3268 [09:13<03:31,  4.29it/s]

 72%|███████▏  | 2364/3268 [09:13<03:30,  4.30it/s]

 72%|███████▏  | 2365/3268 [09:13<03:30,  4.30it/s]

 72%|███████▏  | 2366/3268 [09:13<03:30,  4.29it/s]

 72%|███████▏  | 2367/3268 [09:14<03:29,  4.30it/s]

 72%|███████▏  | 2368/3268 [09:14<03:29,  4.30it/s]

 72%|███████▏  | 2369/3268 [09:14<03:29,  4.29it/s]

 73%|███████▎  | 2370/3268 [09:14<03:29,  4.29it/s]

 73%|███████▎  | 2371/3268 [09:14<03:28,  4.29it/s]

 73%|███████▎  | 2372/3268 [09:15<03:28,  4.30it/s]

 73%|███████▎  | 2373/3268 [09:15<03:28,  4.30it/s]

 73%|███████▎  | 2374/3268 [09:15<03:27,  4.31it/s]

 73%|███████▎  | 2375/3268 [09:15<03:27,  4.30it/s]

 73%|███████▎  | 2376/3268 [09:16<03:27,  4.29it/s]

 73%|███████▎  | 2377/3268 [09:16<03:27,  4.29it/s]

 73%|███████▎  | 2378/3268 [09:16<03:27,  4.29it/s]

 73%|███████▎  | 2379/3268 [09:16<03:26,  4.30it/s]

 73%|███████▎  | 2380/3268 [09:17<03:26,  4.30it/s]

 73%|███████▎  | 2381/3268 [09:17<03:26,  4.29it/s]

 73%|███████▎  | 2382/3268 [09:17<03:26,  4.30it/s]

 73%|███████▎  | 2383/3268 [09:17<03:26,  4.30it/s]

 73%|███████▎  | 2384/3268 [09:17<03:26,  4.29it/s]

 73%|███████▎  | 2385/3268 [09:18<03:25,  4.29it/s]

 73%|███████▎  | 2386/3268 [09:18<03:25,  4.29it/s]

 73%|███████▎  | 2387/3268 [09:18<03:25,  4.29it/s]

 73%|███████▎  | 2388/3268 [09:18<03:25,  4.28it/s]

 73%|███████▎  | 2389/3268 [09:19<03:26,  4.26it/s]

 73%|███████▎  | 2390/3268 [09:19<03:25,  4.27it/s]

 73%|███████▎  | 2391/3268 [09:19<03:24,  4.28it/s]

 73%|███████▎  | 2392/3268 [09:19<03:23,  4.30it/s]

 73%|███████▎  | 2393/3268 [09:20<03:23,  4.31it/s]

 73%|███████▎  | 2394/3268 [09:20<03:23,  4.30it/s]

 73%|███████▎  | 2395/3268 [09:20<03:22,  4.31it/s]

 73%|███████▎  | 2396/3268 [09:20<03:22,  4.30it/s]

 73%|███████▎  | 2397/3268 [09:20<03:22,  4.30it/s]

 73%|███████▎  | 2398/3268 [09:21<03:22,  4.30it/s]

 73%|███████▎  | 2399/3268 [09:21<03:22,  4.29it/s]

 73%|███████▎  | 2400/3268 [09:21<03:22,  4.29it/s]

 73%|███████▎  | 2401/3268 [09:21<03:22,  4.29it/s]

 74%|███████▎  | 2402/3268 [09:22<03:22,  4.27it/s]

 74%|███████▎  | 2403/3268 [09:22<03:22,  4.28it/s]

 74%|███████▎  | 2404/3268 [09:22<03:21,  4.28it/s]

 74%|███████▎  | 2405/3268 [09:22<03:21,  4.28it/s]

 74%|███████▎  | 2406/3268 [09:23<03:21,  4.29it/s]

 74%|███████▎  | 2407/3268 [09:23<03:21,  4.28it/s]

 74%|███████▎  | 2408/3268 [09:23<03:21,  4.27it/s]

 74%|███████▎  | 2409/3268 [09:23<03:21,  4.27it/s]

 74%|███████▎  | 2410/3268 [09:24<03:20,  4.28it/s]

 74%|███████▍  | 2411/3268 [09:24<03:20,  4.28it/s]

 74%|███████▍  | 2412/3268 [09:24<03:19,  4.28it/s]

 74%|███████▍  | 2413/3268 [09:24<03:19,  4.29it/s]

 74%|███████▍  | 2414/3268 [09:24<03:19,  4.29it/s]

 74%|███████▍  | 2415/3268 [09:25<03:18,  4.29it/s]

 74%|███████▍  | 2416/3268 [09:25<03:19,  4.27it/s]

 74%|███████▍  | 2417/3268 [09:25<03:18,  4.28it/s]

 74%|███████▍  | 2418/3268 [09:25<03:18,  4.29it/s]

 74%|███████▍  | 2419/3268 [09:26<03:18,  4.29it/s]

 74%|███████▍  | 2420/3268 [09:26<03:18,  4.28it/s]

 74%|███████▍  | 2421/3268 [09:26<03:17,  4.28it/s]

 74%|███████▍  | 2422/3268 [09:26<03:17,  4.28it/s]

 74%|███████▍  | 2423/3268 [09:27<03:17,  4.28it/s]

 74%|███████▍  | 2424/3268 [09:27<03:17,  4.28it/s]

 74%|███████▍  | 2425/3268 [09:27<03:17,  4.26it/s]

 74%|███████▍  | 2426/3268 [09:27<03:17,  4.26it/s]

 74%|███████▍  | 2427/3268 [09:28<03:17,  4.26it/s]

 74%|███████▍  | 2428/3268 [09:28<03:16,  4.27it/s]

 74%|███████▍  | 2429/3268 [09:28<03:16,  4.27it/s]

 74%|███████▍  | 2430/3268 [09:28<03:16,  4.25it/s]

 74%|███████▍  | 2431/3268 [09:28<03:16,  4.25it/s]

 74%|███████▍  | 2432/3268 [09:29<03:16,  4.26it/s]

 74%|███████▍  | 2433/3268 [09:29<03:15,  4.27it/s]

 74%|███████▍  | 2434/3268 [09:29<03:15,  4.27it/s]

 75%|███████▍  | 2435/3268 [09:29<03:15,  4.25it/s]

 75%|███████▍  | 2436/3268 [09:30<03:15,  4.26it/s]

 75%|███████▍  | 2437/3268 [09:30<03:14,  4.26it/s]

 75%|███████▍  | 2438/3268 [09:30<03:14,  4.27it/s]

 75%|███████▍  | 2439/3268 [09:30<03:14,  4.27it/s]

 75%|███████▍  | 2440/3268 [09:31<03:14,  4.27it/s]

 75%|███████▍  | 2441/3268 [09:31<03:13,  4.26it/s]

 75%|███████▍  | 2442/3268 [09:31<03:14,  4.26it/s]

 75%|███████▍  | 2443/3268 [09:31<03:13,  4.27it/s]

 75%|███████▍  | 2444/3268 [09:31<03:13,  4.26it/s]

 75%|███████▍  | 2445/3268 [09:32<03:13,  4.25it/s]

 75%|███████▍  | 2446/3268 [09:32<03:13,  4.26it/s]

 75%|███████▍  | 2447/3268 [09:32<03:12,  4.25it/s]

 75%|███████▍  | 2448/3268 [09:32<03:12,  4.26it/s]

 75%|███████▍  | 2449/3268 [09:33<03:12,  4.26it/s]

 75%|███████▍  | 2450/3268 [09:33<03:11,  4.26it/s]

 75%|███████▌  | 2451/3268 [09:33<03:11,  4.27it/s]

 75%|███████▌  | 2452/3268 [09:33<03:11,  4.26it/s]

 75%|███████▌  | 2453/3268 [09:34<03:11,  4.27it/s]

 75%|███████▌  | 2454/3268 [09:34<03:10,  4.27it/s]

 75%|███████▌  | 2455/3268 [09:34<03:10,  4.27it/s]

 75%|███████▌  | 2456/3268 [09:34<03:10,  4.26it/s]

 75%|███████▌  | 2457/3268 [09:35<03:10,  4.25it/s]

 75%|███████▌  | 2458/3268 [09:35<03:10,  4.26it/s]

 75%|███████▌  | 2459/3268 [09:35<03:10,  4.26it/s]

 75%|███████▌  | 2460/3268 [09:35<03:09,  4.26it/s]

 75%|███████▌  | 2461/3268 [09:35<03:08,  4.27it/s]

 75%|███████▌  | 2462/3268 [09:36<03:09,  4.26it/s]

 75%|███████▌  | 2463/3268 [09:36<03:08,  4.26it/s]

 75%|███████▌  | 2464/3268 [09:36<03:09,  4.25it/s]

 75%|███████▌  | 2465/3268 [09:36<03:09,  4.24it/s]

 75%|███████▌  | 2466/3268 [09:37<03:09,  4.24it/s]

 75%|███████▌  | 2467/3268 [09:37<03:09,  4.24it/s]

 76%|███████▌  | 2468/3268 [09:37<03:07,  4.26it/s]

 76%|███████▌  | 2469/3268 [09:37<03:07,  4.26it/s]

 76%|███████▌  | 2470/3268 [09:38<03:07,  4.26it/s]

 76%|███████▌  | 2471/3268 [09:38<03:06,  4.27it/s]

 76%|███████▌  | 2472/3268 [09:38<03:06,  4.27it/s]

 76%|███████▌  | 2473/3268 [09:38<03:06,  4.27it/s]

 76%|███████▌  | 2474/3268 [09:39<03:06,  4.26it/s]

 76%|███████▌  | 2475/3268 [09:39<03:06,  4.25it/s]

 76%|███████▌  | 2476/3268 [09:39<03:05,  4.26it/s]

 76%|███████▌  | 2477/3268 [09:39<03:05,  4.26it/s]

 76%|███████▌  | 2478/3268 [09:39<03:05,  4.27it/s]

 76%|███████▌  | 2479/3268 [09:40<03:04,  4.27it/s]

 76%|███████▌  | 2480/3268 [09:40<03:04,  4.27it/s]

 76%|███████▌  | 2481/3268 [09:40<03:04,  4.28it/s]

 76%|███████▌  | 2482/3268 [09:40<03:03,  4.28it/s]

 76%|███████▌  | 2483/3268 [09:41<03:03,  4.27it/s]

 76%|███████▌  | 2484/3268 [09:41<03:03,  4.27it/s]

 76%|███████▌  | 2485/3268 [09:41<03:03,  4.26it/s]

 76%|███████▌  | 2486/3268 [09:41<03:03,  4.27it/s]

 76%|███████▌  | 2487/3268 [09:42<03:02,  4.27it/s]

 76%|███████▌  | 2488/3268 [09:42<03:02,  4.27it/s]

 76%|███████▌  | 2489/3268 [09:42<03:03,  4.25it/s]

 76%|███████▌  | 2490/3268 [09:42<03:02,  4.25it/s]

 76%|███████▌  | 2491/3268 [09:43<03:02,  4.25it/s]

 76%|███████▋  | 2492/3268 [09:43<03:02,  4.25it/s]

 76%|███████▋  | 2493/3268 [09:43<03:02,  4.26it/s]

 76%|███████▋  | 2494/3268 [09:43<03:01,  4.26it/s]

 76%|███████▋  | 2495/3268 [09:43<03:01,  4.25it/s]

 76%|███████▋  | 2496/3268 [09:44<03:01,  4.25it/s]

 76%|███████▋  | 2497/3268 [09:44<03:01,  4.25it/s]

 76%|███████▋  | 2498/3268 [09:44<03:01,  4.25it/s]

 76%|███████▋  | 2499/3268 [09:44<03:00,  4.25it/s]

 76%|███████▋  | 2500/3268 [09:45<03:00,  4.25it/s]

 77%|███████▋  | 2501/3268 [09:45<03:00,  4.26it/s]

 77%|███████▋  | 2502/3268 [09:45<03:00,  4.25it/s]

 77%|███████▋  | 2503/3268 [09:45<02:59,  4.25it/s]

logging
logging the anndata

 77%|███████▋  | 2504/3268 [09:47<08:47,  1.45it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 77%|███████▋  | 2505/3268 [09:47<07:01,  1.81it/s]

 77%|███████▋  | 2506/3268 [09:48<05:47,  2.19it/s]

 77%|███████▋  | 2507/3268 [09:48<04:54,  2.58it/s]

 77%|███████▋  | 2508/3268 [09:48<04:18,  2.94it/s]

 77%|███████▋  | 2509/3268 [09:48<03:52,  3.26it/s]

 77%|███████▋  | 2510/3268 [09:48<03:35,  3.53it/s]

 77%|███████▋  | 2511/3268 [09:49<03:21,  3.75it/s]

 77%|███████▋  | 2512/3268 [09:49<03:13,  3.91it/s]

 77%|███████▋  | 2513/3268 [09:49<03:06,  4.04it/s]

 77%|███████▋  | 2514/3268 [09:49<03:02,  4.14it/s]

 77%|███████▋  | 2515/3268 [09:50<02:58,  4.21it/s]

 77%|███████▋  | 2516/3268 [09:50<02:57,  4.25it/s]

 77%|███████▋  | 2517/3268 [09:50<02:54,  4.29it/s]

 77%|███████▋  | 2518/3268 [09:50<02:53,  4.32it/s]

 77%|███████▋  | 2519/3268 [09:51<02:53,  4.31it/s]

 77%|███████▋  | 2520/3268 [09:51<02:52,  4.33it/s]

 77%|███████▋  | 2521/3268 [09:51<02:51,  4.34it/s]

 77%|███████▋  | 2522/3268 [09:51<02:51,  4.35it/s]

 77%|███████▋  | 2523/3268 [09:51<02:50,  4.37it/s]

 77%|███████▋  | 2524/3268 [09:52<02:50,  4.37it/s]

 77%|███████▋  | 2525/3268 [09:52<02:49,  4.38it/s]

 77%|███████▋  | 2526/3268 [09:52<02:49,  4.37it/s]

 77%|███████▋  | 2527/3268 [09:52<02:49,  4.36it/s]

 77%|███████▋  | 2528/3268 [09:53<02:49,  4.37it/s]

 77%|███████▋  | 2529/3268 [09:53<02:48,  4.38it/s]

 77%|███████▋  | 2530/3268 [09:53<02:49,  4.35it/s]

 77%|███████▋  | 2531/3268 [09:53<02:49,  4.36it/s]

 77%|███████▋  | 2532/3268 [09:54<02:48,  4.36it/s]

 78%|███████▊  | 2533/3268 [09:54<02:48,  4.36it/s]

 78%|███████▊  | 2534/3268 [09:54<02:48,  4.37it/s]

 78%|███████▊  | 2535/3268 [09:54<02:47,  4.37it/s]

 78%|███████▊  | 2536/3268 [09:54<02:47,  4.37it/s]

 78%|███████▊  | 2537/3268 [09:55<02:47,  4.37it/s]

 78%|███████▊  | 2538/3268 [09:55<02:47,  4.36it/s]

 78%|███████▊  | 2539/3268 [09:55<02:47,  4.36it/s]

 78%|███████▊  | 2540/3268 [09:55<02:46,  4.36it/s]

 78%|███████▊  | 2541/3268 [09:56<02:46,  4.37it/s]

 78%|███████▊  | 2542/3268 [09:56<02:46,  4.37it/s]

 78%|███████▊  | 2543/3268 [09:56<02:45,  4.37it/s]

 78%|███████▊  | 2544/3268 [09:56<02:45,  4.37it/s]

 78%|███████▊  | 2545/3268 [09:56<02:45,  4.37it/s]

 78%|███████▊  | 2546/3268 [09:57<02:45,  4.36it/s]

 78%|███████▊  | 2547/3268 [09:57<02:45,  4.36it/s]

 78%|███████▊  | 2548/3268 [09:57<02:45,  4.36it/s]

 78%|███████▊  | 2549/3268 [09:57<02:45,  4.36it/s]

 78%|███████▊  | 2550/3268 [09:58<02:44,  4.37it/s]

 78%|███████▊  | 2551/3268 [09:58<02:44,  4.37it/s]

 78%|███████▊  | 2552/3268 [09:58<02:44,  4.37it/s]

 78%|███████▊  | 2553/3268 [09:58<02:43,  4.37it/s]

 78%|███████▊  | 2554/3268 [09:59<02:43,  4.38it/s]

 78%|███████▊  | 2555/3268 [09:59<02:43,  4.37it/s]

 78%|███████▊  | 2556/3268 [09:59<02:43,  4.37it/s]

 78%|███████▊  | 2557/3268 [09:59<02:43,  4.36it/s]

 78%|███████▊  | 2558/3268 [09:59<02:44,  4.33it/s]

 78%|███████▊  | 2559/3268 [10:00<02:43,  4.34it/s]

 78%|███████▊  | 2560/3268 [10:00<02:42,  4.35it/s]

 78%|███████▊  | 2561/3268 [10:00<02:42,  4.35it/s]

 78%|███████▊  | 2562/3268 [10:00<02:42,  4.36it/s]

 78%|███████▊  | 2563/3268 [10:01<02:41,  4.35it/s]

 78%|███████▊  | 2564/3268 [10:01<02:41,  4.37it/s]

 78%|███████▊  | 2565/3268 [10:01<02:40,  4.37it/s]

 79%|███████▊  | 2566/3268 [10:01<02:40,  4.37it/s]

 79%|███████▊  | 2567/3268 [10:02<02:40,  4.37it/s]

 79%|███████▊  | 2568/3268 [10:02<02:40,  4.36it/s]

 79%|███████▊  | 2569/3268 [10:02<02:40,  4.36it/s]

 79%|███████▊  | 2570/3268 [10:02<02:39,  4.37it/s]

 79%|███████▊  | 2571/3268 [10:02<02:39,  4.37it/s]

 79%|███████▊  | 2572/3268 [10:03<02:39,  4.36it/s]

 79%|███████▊  | 2573/3268 [10:03<02:38,  4.37it/s]

 79%|███████▉  | 2574/3268 [10:03<02:38,  4.38it/s]

 79%|███████▉  | 2575/3268 [10:03<02:38,  4.37it/s]

 79%|███████▉  | 2576/3268 [10:04<02:38,  4.37it/s]

 79%|███████▉  | 2577/3268 [10:04<02:38,  4.36it/s]

 79%|███████▉  | 2578/3268 [10:04<02:38,  4.35it/s]

 79%|███████▉  | 2579/3268 [10:04<02:38,  4.36it/s]

 79%|███████▉  | 2580/3268 [10:05<02:37,  4.36it/s]

 79%|███████▉  | 2581/3268 [10:05<02:37,  4.36it/s]

 79%|███████▉  | 2582/3268 [10:05<02:37,  4.37it/s]

 79%|███████▉  | 2583/3268 [10:05<02:36,  4.37it/s]

 79%|███████▉  | 2584/3268 [10:05<02:36,  4.36it/s]

 79%|███████▉  | 2585/3268 [10:06<02:36,  4.37it/s]

 79%|███████▉  | 2586/3268 [10:06<02:36,  4.37it/s]

 79%|███████▉  | 2587/3268 [10:06<02:35,  4.37it/s]

 79%|███████▉  | 2588/3268 [10:06<02:35,  4.37it/s]

 79%|███████▉  | 2589/3268 [10:07<02:35,  4.36it/s]

 79%|███████▉  | 2590/3268 [10:07<02:35,  4.37it/s]

 79%|███████▉  | 2591/3268 [10:07<02:35,  4.36it/s]

 79%|███████▉  | 2592/3268 [10:07<02:35,  4.36it/s]

 79%|███████▉  | 2593/3268 [10:07<02:34,  4.37it/s]

 79%|███████▉  | 2594/3268 [10:08<02:34,  4.36it/s]

 79%|███████▉  | 2595/3268 [10:08<02:34,  4.36it/s]

 79%|███████▉  | 2596/3268 [10:08<02:34,  4.36it/s]

 79%|███████▉  | 2597/3268 [10:08<02:34,  4.35it/s]

 79%|███████▉  | 2598/3268 [10:09<02:33,  4.36it/s]

 80%|███████▉  | 2599/3268 [10:09<02:34,  4.34it/s]

 80%|███████▉  | 2600/3268 [10:09<02:33,  4.35it/s]

 80%|███████▉  | 2601/3268 [10:09<02:33,  4.36it/s]

 80%|███████▉  | 2602/3268 [10:10<02:33,  4.34it/s]

 80%|███████▉  | 2603/3268 [10:10<02:33,  4.34it/s]

 80%|███████▉  | 2604/3268 [10:10<02:32,  4.35it/s]

 80%|███████▉  | 2605/3268 [10:10<02:32,  4.35it/s]

 80%|███████▉  | 2606/3268 [10:10<02:32,  4.35it/s]

 80%|███████▉  | 2607/3268 [10:11<02:31,  4.36it/s]

 80%|███████▉  | 2608/3268 [10:11<02:31,  4.36it/s]

 80%|███████▉  | 2609/3268 [10:11<02:31,  4.34it/s]

 80%|███████▉  | 2610/3268 [10:11<02:31,  4.35it/s]

 80%|███████▉  | 2611/3268 [10:12<02:30,  4.36it/s]

 80%|███████▉  | 2612/3268 [10:12<02:30,  4.37it/s]

 80%|███████▉  | 2613/3268 [10:12<02:30,  4.36it/s]

 80%|███████▉  | 2614/3268 [10:12<02:30,  4.35it/s]

 80%|████████  | 2615/3268 [10:13<02:29,  4.36it/s]

 80%|████████  | 2616/3268 [10:13<02:30,  4.35it/s]

 80%|████████  | 2617/3268 [10:13<02:31,  4.31it/s]

 80%|████████  | 2618/3268 [10:13<02:29,  4.33it/s]

 80%|████████  | 2619/3268 [10:13<02:29,  4.34it/s]

 80%|████████  | 2620/3268 [10:14<02:29,  4.35it/s]

 80%|████████  | 2621/3268 [10:14<02:28,  4.36it/s]

 80%|████████  | 2622/3268 [10:14<02:28,  4.36it/s]

 80%|████████  | 2623/3268 [10:14<02:27,  4.37it/s]

 80%|████████  | 2624/3268 [10:15<02:27,  4.36it/s]

 80%|████████  | 2625/3268 [10:15<02:27,  4.35it/s]

 80%|████████  | 2626/3268 [10:15<02:27,  4.35it/s]

 80%|████████  | 2627/3268 [10:15<02:27,  4.36it/s]

 80%|████████  | 2628/3268 [10:16<02:26,  4.36it/s]

 80%|████████  | 2629/3268 [10:16<02:26,  4.35it/s]

 80%|████████  | 2630/3268 [10:16<02:26,  4.35it/s]

 81%|████████  | 2631/3268 [10:16<02:26,  4.36it/s]

 81%|████████  | 2632/3268 [10:16<02:25,  4.36it/s]

 81%|████████  | 2633/3268 [10:17<02:25,  4.36it/s]

 81%|████████  | 2634/3268 [10:17<02:25,  4.36it/s]

 81%|████████  | 2635/3268 [10:17<02:25,  4.35it/s]

 81%|████████  | 2636/3268 [10:17<02:25,  4.35it/s]

 81%|████████  | 2637/3268 [10:18<02:26,  4.31it/s]

 81%|████████  | 2638/3268 [10:18<02:25,  4.32it/s]

 81%|████████  | 2639/3268 [10:18<02:25,  4.33it/s]

 81%|████████  | 2640/3268 [10:18<02:24,  4.34it/s]

 81%|████████  | 2641/3268 [10:19<02:24,  4.34it/s]

 81%|████████  | 2642/3268 [10:19<02:23,  4.36it/s]

 81%|████████  | 2643/3268 [10:19<02:23,  4.35it/s]

 81%|████████  | 2644/3268 [10:19<02:23,  4.34it/s]

 81%|████████  | 2645/3268 [10:19<02:23,  4.35it/s]

 81%|████████  | 2646/3268 [10:20<02:23,  4.34it/s]

 81%|████████  | 2647/3268 [10:20<02:22,  4.35it/s]

 81%|████████  | 2648/3268 [10:20<02:23,  4.33it/s]

 81%|████████  | 2649/3268 [10:20<02:23,  4.32it/s]

 81%|████████  | 2650/3268 [10:21<02:22,  4.33it/s]

 81%|████████  | 2651/3268 [10:21<02:22,  4.34it/s]

 81%|████████  | 2652/3268 [10:21<02:22,  4.33it/s]

 81%|████████  | 2653/3268 [10:21<02:21,  4.34it/s]

 81%|████████  | 2654/3268 [10:22<02:21,  4.34it/s]

 81%|████████  | 2655/3268 [10:22<02:21,  4.34it/s]

 81%|████████▏ | 2656/3268 [10:22<02:21,  4.33it/s]

 81%|████████▏ | 2657/3268 [10:22<02:20,  4.34it/s]

 81%|████████▏ | 2658/3268 [10:22<02:20,  4.35it/s]

 81%|████████▏ | 2659/3268 [10:23<02:20,  4.34it/s]

 81%|████████▏ | 2660/3268 [10:23<02:19,  4.35it/s]

 81%|████████▏ | 2661/3268 [10:23<02:19,  4.36it/s]

 81%|████████▏ | 2662/3268 [10:23<02:19,  4.36it/s]

 81%|████████▏ | 2663/3268 [10:24<02:19,  4.34it/s]

 82%|████████▏ | 2664/3268 [10:24<02:19,  4.34it/s]

 82%|████████▏ | 2665/3268 [10:24<02:19,  4.34it/s]

 82%|████████▏ | 2666/3268 [10:24<02:18,  4.35it/s]

 82%|████████▏ | 2667/3268 [10:25<02:18,  4.35it/s]

 82%|████████▏ | 2668/3268 [10:25<02:18,  4.34it/s]

 82%|████████▏ | 2669/3268 [10:25<02:17,  4.35it/s]

 82%|████████▏ | 2670/3268 [10:25<02:17,  4.35it/s]

 82%|████████▏ | 2671/3268 [10:25<02:17,  4.36it/s]

 82%|████████▏ | 2672/3268 [10:26<02:16,  4.35it/s]

 82%|████████▏ | 2673/3268 [10:26<02:17,  4.34it/s]

 82%|████████▏ | 2674/3268 [10:26<02:16,  4.34it/s]

 82%|████████▏ | 2675/3268 [10:26<02:16,  4.34it/s]

 82%|████████▏ | 2676/3268 [10:27<02:17,  4.32it/s]

 82%|████████▏ | 2677/3268 [10:27<02:16,  4.33it/s]

 82%|████████▏ | 2678/3268 [10:27<02:16,  4.34it/s]

 82%|████████▏ | 2679/3268 [10:27<02:15,  4.33it/s]

 82%|████████▏ | 2680/3268 [10:28<02:15,  4.33it/s]

 82%|████████▏ | 2681/3268 [10:28<02:15,  4.34it/s]

 82%|████████▏ | 2682/3268 [10:28<02:14,  4.34it/s]

 82%|████████▏ | 2683/3268 [10:28<02:14,  4.34it/s]

 82%|████████▏ | 2684/3268 [10:28<02:14,  4.34it/s]

 82%|████████▏ | 2685/3268 [10:29<02:14,  4.34it/s]

 82%|████████▏ | 2686/3268 [10:29<02:14,  4.34it/s]

 82%|████████▏ | 2687/3268 [10:29<02:13,  4.34it/s]

 82%|████████▏ | 2688/3268 [10:29<02:13,  4.35it/s]

 82%|████████▏ | 2689/3268 [10:30<02:13,  4.33it/s]

 82%|████████▏ | 2690/3268 [10:30<02:13,  4.34it/s]

 82%|████████▏ | 2691/3268 [10:30<02:13,  4.34it/s]

 82%|████████▏ | 2692/3268 [10:30<02:12,  4.34it/s]

 82%|████████▏ | 2693/3268 [10:31<02:12,  4.34it/s]

 82%|████████▏ | 2694/3268 [10:31<02:12,  4.35it/s]

 82%|████████▏ | 2695/3268 [10:31<02:11,  4.34it/s]

 82%|████████▏ | 2696/3268 [10:31<02:11,  4.34it/s]

 83%|████████▎ | 2697/3268 [10:31<02:11,  4.34it/s]

 83%|████████▎ | 2698/3268 [10:32<02:11,  4.34it/s]

 83%|████████▎ | 2699/3268 [10:32<02:11,  4.34it/s]

 83%|████████▎ | 2700/3268 [10:32<02:11,  4.33it/s]

 83%|████████▎ | 2701/3268 [10:32<02:10,  4.34it/s]

 83%|████████▎ | 2702/3268 [10:33<02:10,  4.34it/s]

 83%|████████▎ | 2703/3268 [10:33<02:10,  4.33it/s]

 83%|████████▎ | 2704/3268 [10:33<02:10,  4.32it/s]

 83%|████████▎ | 2705/3268 [10:33<02:10,  4.32it/s]

 83%|████████▎ | 2706/3268 [10:34<02:09,  4.33it/s]

 83%|████████▎ | 2707/3268 [10:34<02:09,  4.33it/s]

 83%|████████▎ | 2708/3268 [10:34<02:09,  4.32it/s]

 83%|████████▎ | 2709/3268 [10:34<02:09,  4.32it/s]

 83%|████████▎ | 2710/3268 [10:34<02:08,  4.34it/s]

 83%|████████▎ | 2711/3268 [10:35<02:08,  4.33it/s]

 83%|████████▎ | 2712/3268 [10:35<02:08,  4.34it/s]

 83%|████████▎ | 2713/3268 [10:35<02:08,  4.33it/s]

 83%|████████▎ | 2714/3268 [10:35<02:07,  4.33it/s]

 83%|████████▎ | 2715/3268 [10:36<02:07,  4.34it/s]

 83%|████████▎ | 2716/3268 [10:36<02:07,  4.34it/s]

 83%|████████▎ | 2717/3268 [10:36<02:06,  4.34it/s]

 83%|████████▎ | 2718/3268 [10:36<02:06,  4.34it/s]

 83%|████████▎ | 2719/3268 [10:37<02:06,  4.34it/s]

 83%|████████▎ | 2720/3268 [10:37<02:06,  4.35it/s]

 83%|████████▎ | 2721/3268 [10:37<02:05,  4.35it/s]

 83%|████████▎ | 2722/3268 [10:37<02:06,  4.33it/s]

 83%|████████▎ | 2723/3268 [10:37<02:05,  4.34it/s]

 83%|████████▎ | 2724/3268 [10:38<02:05,  4.33it/s]

 83%|████████▎ | 2725/3268 [10:38<02:05,  4.34it/s]

 83%|████████▎ | 2726/3268 [10:38<02:04,  4.34it/s]

 83%|████████▎ | 2727/3268 [10:38<02:04,  4.34it/s]

 83%|████████▎ | 2728/3268 [10:39<02:04,  4.34it/s]

 84%|████████▎ | 2729/3268 [10:39<02:04,  4.32it/s]

 84%|████████▎ | 2730/3268 [10:39<02:04,  4.32it/s]

 84%|████████▎ | 2731/3268 [10:39<02:04,  4.33it/s]

 84%|████████▎ | 2732/3268 [10:40<02:03,  4.33it/s]

 84%|████████▎ | 2733/3268 [10:40<02:03,  4.34it/s]

 84%|████████▎ | 2734/3268 [10:40<02:03,  4.34it/s]

 84%|████████▎ | 2735/3268 [10:40<02:03,  4.33it/s]

 84%|████████▎ | 2736/3268 [10:40<02:02,  4.34it/s]

 84%|████████▍ | 2737/3268 [10:41<02:02,  4.33it/s]

 84%|████████▍ | 2738/3268 [10:41<02:02,  4.33it/s]

 84%|████████▍ | 2739/3268 [10:41<02:02,  4.33it/s]

 84%|████████▍ | 2740/3268 [10:41<02:01,  4.33it/s]

 84%|████████▍ | 2741/3268 [10:42<02:01,  4.34it/s]

 84%|████████▍ | 2742/3268 [10:42<02:01,  4.34it/s]

 84%|████████▍ | 2743/3268 [10:42<02:00,  4.34it/s]

 84%|████████▍ | 2744/3268 [10:42<02:00,  4.35it/s]

 84%|████████▍ | 2745/3268 [10:42<02:00,  4.35it/s]

 84%|████████▍ | 2746/3268 [10:43<02:00,  4.34it/s]

 84%|████████▍ | 2747/3268 [10:43<01:59,  4.34it/s]

 84%|████████▍ | 2748/3268 [10:43<01:59,  4.35it/s]

 84%|████████▍ | 2749/3268 [10:43<01:59,  4.34it/s]

 84%|████████▍ | 2750/3268 [10:44<01:59,  4.34it/s]

 84%|████████▍ | 2751/3268 [10:44<01:59,  4.33it/s]

 84%|████████▍ | 2752/3268 [10:44<01:58,  4.34it/s]

 84%|████████▍ | 2753/3268 [10:44<01:58,  4.34it/s]

 84%|████████▍ | 2754/3268 [10:45<01:58,  4.34it/s]

 84%|████████▍ | 2755/3268 [10:45<01:58,  4.34it/s]

 84%|████████▍ | 2756/3268 [10:45<01:58,  4.34it/s]

 84%|████████▍ | 2757/3268 [10:45<01:57,  4.34it/s]

 84%|████████▍ | 2758/3268 [10:45<01:57,  4.34it/s]

 84%|████████▍ | 2759/3268 [10:46<01:57,  4.34it/s]

 84%|████████▍ | 2760/3268 [10:46<01:56,  4.35it/s]

 84%|████████▍ | 2761/3268 [10:46<01:56,  4.34it/s]

 85%|████████▍ | 2762/3268 [10:46<01:57,  4.32it/s]

 85%|████████▍ | 2763/3268 [10:47<01:56,  4.33it/s]

 85%|████████▍ | 2764/3268 [10:47<01:56,  4.33it/s]

 85%|████████▍ | 2765/3268 [10:47<01:55,  4.34it/s]

 85%|████████▍ | 2766/3268 [10:47<01:55,  4.35it/s]

 85%|████████▍ | 2767/3268 [10:48<01:55,  4.36it/s]

 85%|████████▍ | 2768/3268 [10:48<01:54,  4.36it/s]

 85%|████████▍ | 2769/3268 [10:48<01:54,  4.36it/s]

 85%|████████▍ | 2770/3268 [10:48<01:54,  4.35it/s]

 85%|████████▍ | 2771/3268 [10:48<01:54,  4.34it/s]

 85%|████████▍ | 2772/3268 [10:49<01:54,  4.34it/s]

 85%|████████▍ | 2773/3268 [10:49<01:54,  4.34it/s]

 85%|████████▍ | 2774/3268 [10:49<01:54,  4.33it/s]

 85%|████████▍ | 2775/3268 [10:49<01:54,  4.31it/s]

 85%|████████▍ | 2776/3268 [10:50<01:53,  4.32it/s]

 85%|████████▍ | 2777/3268 [10:50<01:53,  4.32it/s]

 85%|████████▌ | 2778/3268 [10:50<01:53,  4.33it/s]

 85%|████████▌ | 2779/3268 [10:50<01:53,  4.32it/s]

 85%|████████▌ | 2780/3268 [10:51<01:52,  4.32it/s]

 85%|████████▌ | 2781/3268 [10:51<01:52,  4.33it/s]

 85%|████████▌ | 2782/3268 [10:51<01:52,  4.33it/s]

 85%|████████▌ | 2783/3268 [10:51<01:52,  4.32it/s]

 85%|████████▌ | 2784/3268 [10:51<01:51,  4.34it/s]

 85%|████████▌ | 2785/3268 [10:52<01:51,  4.34it/s]

 85%|████████▌ | 2786/3268 [10:52<01:51,  4.33it/s]

 85%|████████▌ | 2787/3268 [10:52<01:50,  4.34it/s]

 85%|████████▌ | 2788/3268 [10:52<01:50,  4.34it/s]

 85%|████████▌ | 2789/3268 [10:53<01:50,  4.34it/s]

 85%|████████▌ | 2790/3268 [10:53<01:50,  4.34it/s]

 85%|████████▌ | 2791/3268 [10:53<01:50,  4.33it/s]

 85%|████████▌ | 2792/3268 [10:53<01:49,  4.34it/s]

 85%|████████▌ | 2793/3268 [10:54<01:49,  4.34it/s]

 85%|████████▌ | 2794/3268 [10:54<01:49,  4.31it/s]

 86%|████████▌ | 2795/3268 [10:54<01:49,  4.33it/s]

 86%|████████▌ | 2796/3268 [10:54<01:49,  4.32it/s]

 86%|████████▌ | 2797/3268 [10:54<01:48,  4.32it/s]

 86%|████████▌ | 2798/3268 [10:55<01:48,  4.32it/s]

 86%|████████▌ | 2799/3268 [10:55<01:48,  4.31it/s]

 86%|████████▌ | 2800/3268 [10:55<01:48,  4.32it/s]

 86%|████████▌ | 2801/3268 [10:55<01:47,  4.33it/s]

 86%|████████▌ | 2802/3268 [10:56<01:47,  4.33it/s]

 86%|████████▌ | 2803/3268 [10:56<01:47,  4.33it/s]

 86%|████████▌ | 2804/3268 [10:56<01:47,  4.33it/s]

 86%|████████▌ | 2805/3268 [10:56<01:46,  4.34it/s]

 86%|████████▌ | 2806/3268 [10:57<01:46,  4.33it/s]

 86%|████████▌ | 2807/3268 [10:57<01:46,  4.33it/s]

 86%|████████▌ | 2808/3268 [10:57<01:46,  4.34it/s]

 86%|████████▌ | 2809/3268 [10:57<01:46,  4.33it/s]

 86%|████████▌ | 2810/3268 [10:57<01:45,  4.32it/s]

 86%|████████▌ | 2811/3268 [10:58<01:45,  4.33it/s]

 86%|████████▌ | 2812/3268 [10:58<01:45,  4.34it/s]

 86%|████████▌ | 2813/3268 [10:58<01:44,  4.34it/s]

 86%|████████▌ | 2814/3268 [10:58<01:44,  4.35it/s]

 86%|████████▌ | 2815/3268 [10:59<01:44,  4.33it/s]

 86%|████████▌ | 2816/3268 [10:59<01:44,  4.34it/s]

 86%|████████▌ | 2817/3268 [10:59<01:44,  4.34it/s]

 86%|████████▌ | 2818/3268 [10:59<01:43,  4.34it/s]

 86%|████████▋ | 2819/3268 [11:00<01:43,  4.34it/s]

 86%|████████▋ | 2820/3268 [11:00<01:43,  4.34it/s]

 86%|████████▋ | 2821/3268 [11:00<01:42,  4.34it/s]

 86%|████████▋ | 2822/3268 [11:00<01:42,  4.35it/s]

 86%|████████▋ | 2823/3268 [11:00<01:42,  4.35it/s]

 86%|████████▋ | 2824/3268 [11:01<01:42,  4.35it/s]

 86%|████████▋ | 2825/3268 [11:01<01:41,  4.35it/s]

 86%|████████▋ | 2826/3268 [11:01<01:41,  4.35it/s]

 87%|████████▋ | 2827/3268 [11:01<01:41,  4.35it/s]

 87%|████████▋ | 2828/3268 [11:02<01:41,  4.35it/s]

 87%|████████▋ | 2829/3268 [11:02<01:40,  4.35it/s]

 87%|████████▋ | 2830/3268 [11:02<01:40,  4.35it/s]

 87%|████████▋ | 2831/3268 [11:02<01:40,  4.35it/s]

 87%|████████▋ | 2832/3268 [11:03<01:40,  4.34it/s]

 87%|████████▋ | 2833/3268 [11:03<01:40,  4.34it/s]

 87%|████████▋ | 2834/3268 [11:03<01:40,  4.34it/s]

 87%|████████▋ | 2835/3268 [11:03<01:39,  4.35it/s]

 87%|████████▋ | 2836/3268 [11:03<01:39,  4.35it/s]

 87%|████████▋ | 2837/3268 [11:04<01:39,  4.34it/s]

 87%|████████▋ | 2838/3268 [11:04<01:39,  4.34it/s]

 87%|████████▋ | 2839/3268 [11:04<01:38,  4.34it/s]

 87%|████████▋ | 2840/3268 [11:04<01:39,  4.32it/s]

 87%|████████▋ | 2841/3268 [11:05<01:38,  4.33it/s]

 87%|████████▋ | 2842/3268 [11:05<01:38,  4.33it/s]

 87%|████████▋ | 2843/3268 [11:05<01:38,  4.33it/s]

 87%|████████▋ | 2844/3268 [11:05<01:37,  4.33it/s]

 87%|████████▋ | 2845/3268 [11:06<01:37,  4.32it/s]

 87%|████████▋ | 2846/3268 [11:06<01:37,  4.33it/s]

 87%|████████▋ | 2847/3268 [11:06<01:37,  4.33it/s]

 87%|████████▋ | 2848/3268 [11:06<01:36,  4.33it/s]

 87%|████████▋ | 2849/3268 [11:06<01:36,  4.33it/s]

 87%|████████▋ | 2850/3268 [11:07<01:36,  4.32it/s]

 87%|████████▋ | 2851/3268 [11:07<01:36,  4.32it/s]

 87%|████████▋ | 2852/3268 [11:07<01:35,  4.33it/s]

 87%|████████▋ | 2853/3268 [11:07<01:35,  4.33it/s]

 87%|████████▋ | 2854/3268 [11:08<01:35,  4.34it/s]

 87%|████████▋ | 2855/3268 [11:08<01:35,  4.33it/s]

 87%|████████▋ | 2856/3268 [11:08<01:35,  4.32it/s]

 87%|████████▋ | 2857/3268 [11:08<01:34,  4.33it/s]

 87%|████████▋ | 2858/3268 [11:09<01:34,  4.33it/s]

 87%|████████▋ | 2859/3268 [11:09<01:34,  4.33it/s]

 88%|████████▊ | 2860/3268 [11:09<01:35,  4.28it/s]

 88%|████████▊ | 2861/3268 [11:09<01:34,  4.29it/s]

 88%|████████▊ | 2862/3268 [11:09<01:34,  4.30it/s]

 88%|████████▊ | 2863/3268 [11:10<01:33,  4.31it/s]

 88%|████████▊ | 2864/3268 [11:10<01:33,  4.31it/s]

 88%|████████▊ | 2865/3268 [11:10<01:33,  4.32it/s]

 88%|████████▊ | 2866/3268 [11:10<01:33,  4.32it/s]

 88%|████████▊ | 2867/3268 [11:11<01:32,  4.31it/s]

 88%|████████▊ | 2868/3268 [11:11<01:32,  4.32it/s]

 88%|████████▊ | 2869/3268 [11:11<01:32,  4.32it/s]

 88%|████████▊ | 2870/3268 [11:11<01:32,  4.31it/s]

 88%|████████▊ | 2871/3268 [11:12<01:31,  4.32it/s]

 88%|████████▊ | 2872/3268 [11:12<01:31,  4.32it/s]

 88%|████████▊ | 2873/3268 [11:12<01:31,  4.32it/s]

 88%|████████▊ | 2874/3268 [11:12<01:30,  4.33it/s]

 88%|████████▊ | 2875/3268 [11:13<01:30,  4.34it/s]

 88%|████████▊ | 2876/3268 [11:13<01:31,  4.28it/s]

 88%|████████▊ | 2877/3268 [11:13<01:30,  4.30it/s]

 88%|████████▊ | 2878/3268 [11:13<01:30,  4.31it/s]

 88%|████████▊ | 2879/3268 [11:13<01:30,  4.32it/s]

 88%|████████▊ | 2880/3268 [11:14<01:29,  4.32it/s]

 88%|████████▊ | 2881/3268 [11:14<01:29,  4.32it/s]

 88%|████████▊ | 2882/3268 [11:14<01:29,  4.32it/s]

 88%|████████▊ | 2883/3268 [11:14<01:29,  4.32it/s]

 88%|████████▊ | 2884/3268 [11:15<01:29,  4.31it/s]

 88%|████████▊ | 2885/3268 [11:15<01:28,  4.32it/s]

 88%|████████▊ | 2886/3268 [11:15<01:28,  4.32it/s]

 88%|████████▊ | 2887/3268 [11:15<01:28,  4.32it/s]

 88%|████████▊ | 2888/3268 [11:16<01:27,  4.33it/s]

 88%|████████▊ | 2889/3268 [11:16<01:27,  4.31it/s]

 88%|████████▊ | 2890/3268 [11:16<01:27,  4.33it/s]

 88%|████████▊ | 2891/3268 [11:16<01:27,  4.32it/s]

 88%|████████▊ | 2892/3268 [11:16<01:27,  4.31it/s]

 89%|████████▊ | 2893/3268 [11:17<01:26,  4.32it/s]

 89%|████████▊ | 2894/3268 [11:17<01:26,  4.31it/s]

 89%|████████▊ | 2895/3268 [11:17<01:26,  4.33it/s]

 89%|████████▊ | 2896/3268 [11:17<01:25,  4.33it/s]

 89%|████████▊ | 2897/3268 [11:18<01:25,  4.32it/s]

 89%|████████▊ | 2898/3268 [11:18<01:26,  4.30it/s]

 89%|████████▊ | 2899/3268 [11:18<01:25,  4.31it/s]

 89%|████████▊ | 2900/3268 [11:18<01:25,  4.31it/s]

 89%|████████▉ | 2901/3268 [11:19<01:25,  4.31it/s]

 89%|████████▉ | 2902/3268 [11:19<01:24,  4.31it/s]

 89%|████████▉ | 2903/3268 [11:19<01:24,  4.32it/s]

 89%|████████▉ | 2904/3268 [11:19<01:24,  4.32it/s]

 89%|████████▉ | 2905/3268 [11:19<01:24,  4.29it/s]

 89%|████████▉ | 2906/3268 [11:20<01:24,  4.31it/s]

 89%|████████▉ | 2907/3268 [11:20<01:23,  4.30it/s]

 89%|████████▉ | 2908/3268 [11:20<01:23,  4.31it/s]

 89%|████████▉ | 2909/3268 [11:20<01:23,  4.31it/s]

 89%|████████▉ | 2910/3268 [11:21<01:23,  4.30it/s]

 89%|████████▉ | 2911/3268 [11:21<01:22,  4.32it/s]

 89%|████████▉ | 2912/3268 [11:21<01:22,  4.32it/s]

 89%|████████▉ | 2913/3268 [11:21<01:22,  4.32it/s]

 89%|████████▉ | 2914/3268 [11:22<01:21,  4.32it/s]

 89%|████████▉ | 2915/3268 [11:22<01:21,  4.32it/s]

 89%|████████▉ | 2916/3268 [11:22<01:21,  4.32it/s]

 89%|████████▉ | 2917/3268 [11:22<01:21,  4.32it/s]

 89%|████████▉ | 2918/3268 [11:22<01:21,  4.27it/s]

 89%|████████▉ | 2919/3268 [11:23<01:21,  4.29it/s]

 89%|████████▉ | 2920/3268 [11:23<01:20,  4.30it/s]

 89%|████████▉ | 2921/3268 [11:23<01:20,  4.30it/s]

 89%|████████▉ | 2922/3268 [11:23<01:20,  4.30it/s]

 89%|████████▉ | 2923/3268 [11:24<01:20,  4.30it/s]

 89%|████████▉ | 2924/3268 [11:24<01:19,  4.31it/s]

 90%|████████▉ | 2925/3268 [11:24<01:19,  4.30it/s]

 90%|████████▉ | 2926/3268 [11:24<01:19,  4.30it/s]

 90%|████████▉ | 2927/3268 [11:25<01:19,  4.29it/s]

 90%|████████▉ | 2928/3268 [11:25<01:19,  4.30it/s]

 90%|████████▉ | 2929/3268 [11:25<01:18,  4.31it/s]

 90%|████████▉ | 2930/3268 [11:25<01:18,  4.31it/s]

 90%|████████▉ | 2931/3268 [11:26<01:18,  4.29it/s]

 90%|████████▉ | 2932/3268 [11:26<01:18,  4.29it/s]

 90%|████████▉ | 2933/3268 [11:26<01:17,  4.30it/s]

 90%|████████▉ | 2934/3268 [11:26<01:17,  4.31it/s]

 90%|████████▉ | 2935/3268 [11:26<01:17,  4.31it/s]

 90%|████████▉ | 2936/3268 [11:27<01:16,  4.31it/s]

 90%|████████▉ | 2937/3268 [11:27<01:16,  4.32it/s]

 90%|████████▉ | 2938/3268 [11:27<01:16,  4.32it/s]

 90%|████████▉ | 2939/3268 [11:27<01:16,  4.32it/s]

 90%|████████▉ | 2940/3268 [11:28<01:16,  4.31it/s]

 90%|████████▉ | 2941/3268 [11:28<01:15,  4.31it/s]

 90%|█████████ | 2942/3268 [11:28<01:15,  4.32it/s]

 90%|█████████ | 2943/3268 [11:28<01:15,  4.32it/s]

 90%|█████████ | 2944/3268 [11:29<01:15,  4.30it/s]

 90%|█████████ | 2945/3268 [11:29<01:14,  4.31it/s]

 90%|█████████ | 2946/3268 [11:29<01:14,  4.31it/s]

 90%|█████████ | 2947/3268 [11:29<01:14,  4.31it/s]

 90%|█████████ | 2948/3268 [11:29<01:14,  4.31it/s]

 90%|█████████ | 2949/3268 [11:30<01:13,  4.31it/s]

 90%|█████████ | 2950/3268 [11:30<01:13,  4.30it/s]

 90%|█████████ | 2951/3268 [11:30<01:13,  4.30it/s]

 90%|█████████ | 2952/3268 [11:30<01:13,  4.30it/s]

 90%|█████████ | 2953/3268 [11:31<01:13,  4.30it/s]

 90%|█████████ | 2954/3268 [11:31<01:12,  4.31it/s]

 90%|█████████ | 2955/3268 [11:31<01:12,  4.32it/s]

 90%|█████████ | 2956/3268 [11:31<01:12,  4.31it/s]

 90%|█████████ | 2957/3268 [11:32<01:12,  4.30it/s]

 91%|█████████ | 2958/3268 [11:32<01:12,  4.30it/s]

 91%|█████████ | 2959/3268 [11:32<01:11,  4.30it/s]

 91%|█████████ | 2960/3268 [11:32<01:11,  4.31it/s]

 91%|█████████ | 2961/3268 [11:32<01:11,  4.32it/s]

 91%|█████████ | 2962/3268 [11:33<01:10,  4.32it/s]

 91%|█████████ | 2963/3268 [11:33<01:10,  4.32it/s]

 91%|█████████ | 2964/3268 [11:33<01:10,  4.32it/s]

 91%|█████████ | 2965/3268 [11:33<01:10,  4.32it/s]

 91%|█████████ | 2966/3268 [11:34<01:09,  4.32it/s]

 91%|█████████ | 2967/3268 [11:34<01:09,  4.31it/s]

 91%|█████████ | 2968/3268 [11:34<01:09,  4.32it/s]

 91%|█████████ | 2969/3268 [11:34<01:09,  4.32it/s]

 91%|█████████ | 2970/3268 [11:35<01:08,  4.33it/s]

 91%|█████████ | 2971/3268 [11:35<01:08,  4.31it/s]

 91%|█████████ | 2972/3268 [11:35<01:08,  4.30it/s]

 91%|█████████ | 2973/3268 [11:35<01:08,  4.30it/s]

 91%|█████████ | 2974/3268 [11:35<01:08,  4.29it/s]

 91%|█████████ | 2975/3268 [11:36<01:08,  4.29it/s]

 91%|█████████ | 2976/3268 [11:36<01:07,  4.29it/s]

 91%|█████████ | 2977/3268 [11:36<01:07,  4.29it/s]

 91%|█████████ | 2978/3268 [11:36<01:07,  4.28it/s]

 91%|█████████ | 2979/3268 [11:37<01:07,  4.29it/s]

 91%|█████████ | 2980/3268 [11:37<01:07,  4.29it/s]

 91%|█████████ | 2981/3268 [11:37<01:06,  4.29it/s]

 91%|█████████ | 2982/3268 [11:37<01:06,  4.28it/s]

 91%|█████████▏| 2983/3268 [11:38<01:06,  4.28it/s]

 91%|█████████▏| 2984/3268 [11:38<01:06,  4.27it/s]

 91%|█████████▏| 2985/3268 [11:38<01:06,  4.28it/s]

 91%|█████████▏| 2986/3268 [11:38<01:05,  4.28it/s]

 91%|█████████▏| 2987/3268 [11:39<01:05,  4.29it/s]

 91%|█████████▏| 2988/3268 [11:39<01:05,  4.27it/s]

 91%|█████████▏| 2989/3268 [11:39<01:05,  4.27it/s]

 91%|█████████▏| 2990/3268 [11:39<01:05,  4.26it/s]

 92%|█████████▏| 2991/3268 [11:39<01:04,  4.27it/s]

 92%|█████████▏| 2992/3268 [11:40<01:04,  4.27it/s]

 92%|█████████▏| 2993/3268 [11:40<01:04,  4.25it/s]

 92%|█████████▏| 2994/3268 [11:40<01:04,  4.26it/s]

 92%|█████████▏| 2995/3268 [11:40<01:03,  4.27it/s]

 92%|█████████▏| 2996/3268 [11:41<01:03,  4.28it/s]

 92%|█████████▏| 2997/3268 [11:41<01:03,  4.29it/s]

 92%|█████████▏| 2998/3268 [11:41<01:02,  4.29it/s]

 92%|█████████▏| 2999/3268 [11:41<01:02,  4.30it/s]

 92%|█████████▏| 3000/3268 [11:42<01:02,  4.30it/s]

 92%|█████████▏| 3001/3268 [11:42<01:02,  4.30it/s]

 92%|█████████▏| 3002/3268 [11:42<01:02,  4.29it/s]

 92%|█████████▏| 3003/3268 [11:42<01:01,  4.28it/s]

 92%|█████████▏| 3004/3268 [11:42<01:01,  4.30it/s]

 92%|█████████▏| 3005/3268 [11:43<01:01,  4.30it/s]

 92%|█████████▏| 3006/3268 [11:43<01:01,  4.29it/s]

 92%|█████████▏| 3007/3268 [11:43<01:00,  4.29it/s]

 92%|█████████▏| 3008/3268 [11:43<01:00,  4.28it/s]

 92%|█████████▏| 3009/3268 [11:44<01:00,  4.29it/s]

 92%|█████████▏| 3010/3268 [11:44<01:00,  4.29it/s]

 92%|█████████▏| 3011/3268 [11:44<00:59,  4.29it/s]

 92%|█████████▏| 3012/3268 [11:44<00:59,  4.29it/s]

 92%|█████████▏| 3013/3268 [11:45<00:59,  4.28it/s]

 92%|█████████▏| 3014/3268 [11:45<00:59,  4.29it/s]

 92%|█████████▏| 3015/3268 [11:45<00:58,  4.29it/s]

 92%|█████████▏| 3016/3268 [11:45<00:58,  4.29it/s]

 92%|█████████▏| 3017/3268 [11:46<00:58,  4.29it/s]

 92%|█████████▏| 3018/3268 [11:46<00:58,  4.29it/s]

 92%|█████████▏| 3019/3268 [11:46<00:57,  4.30it/s]

 92%|█████████▏| 3020/3268 [11:46<00:57,  4.30it/s]

 92%|█████████▏| 3021/3268 [11:46<00:57,  4.29it/s]

 92%|█████████▏| 3022/3268 [11:47<00:57,  4.30it/s]

 93%|█████████▎| 3023/3268 [11:47<00:57,  4.30it/s]

 93%|█████████▎| 3024/3268 [11:47<00:56,  4.29it/s]

 93%|█████████▎| 3025/3268 [11:47<00:56,  4.28it/s]

 93%|█████████▎| 3026/3268 [11:48<00:56,  4.26it/s]

 93%|█████████▎| 3027/3268 [11:48<00:56,  4.27it/s]

 93%|█████████▎| 3028/3268 [11:48<00:56,  4.26it/s]

 93%|█████████▎| 3029/3268 [11:48<00:56,  4.26it/s]

 93%|█████████▎| 3030/3268 [11:49<00:55,  4.27it/s]

 93%|█████████▎| 3031/3268 [11:49<00:55,  4.26it/s]

 93%|█████████▎| 3032/3268 [11:49<00:55,  4.27it/s]

 93%|█████████▎| 3033/3268 [11:49<00:55,  4.27it/s]

 93%|█████████▎| 3034/3268 [11:49<00:54,  4.27it/s]

 93%|█████████▎| 3035/3268 [11:50<00:54,  4.27it/s]

 93%|█████████▎| 3036/3268 [11:50<00:54,  4.27it/s]

 93%|█████████▎| 3037/3268 [11:50<00:53,  4.28it/s]

 93%|█████████▎| 3038/3268 [11:50<00:53,  4.27it/s]

 93%|█████████▎| 3039/3268 [11:51<00:53,  4.27it/s]

 93%|█████████▎| 3040/3268 [11:51<00:53,  4.26it/s]

 93%|█████████▎| 3041/3268 [11:51<00:53,  4.27it/s]

 93%|█████████▎| 3042/3268 [11:51<00:52,  4.27it/s]

 93%|█████████▎| 3043/3268 [11:52<00:52,  4.27it/s]

 93%|█████████▎| 3044/3268 [11:52<00:52,  4.27it/s]

 93%|█████████▎| 3045/3268 [11:52<00:52,  4.28it/s]

 93%|█████████▎| 3046/3268 [11:52<00:52,  4.27it/s]

 93%|█████████▎| 3047/3268 [11:53<00:51,  4.27it/s]

 93%|█████████▎| 3048/3268 [11:53<00:51,  4.27it/s]

 93%|█████████▎| 3049/3268 [11:53<00:51,  4.23it/s]

 93%|█████████▎| 3050/3268 [11:53<00:51,  4.23it/s]

 93%|█████████▎| 3051/3268 [11:53<00:51,  4.23it/s]

 93%|█████████▎| 3052/3268 [11:54<00:50,  4.25it/s]

 93%|█████████▎| 3053/3268 [11:54<00:50,  4.25it/s]

 93%|█████████▎| 3054/3268 [11:54<00:50,  4.25it/s]

 93%|█████████▎| 3055/3268 [11:54<00:50,  4.26it/s]

 94%|█████████▎| 3056/3268 [11:55<00:49,  4.26it/s]

 94%|█████████▎| 3057/3268 [11:55<00:49,  4.26it/s]

 94%|█████████▎| 3058/3268 [11:55<00:49,  4.26it/s]

 94%|█████████▎| 3059/3268 [11:55<00:49,  4.26it/s]

 94%|█████████▎| 3060/3268 [11:56<00:48,  4.26it/s]

 94%|█████████▎| 3061/3268 [11:56<00:48,  4.26it/s]

 94%|█████████▎| 3062/3268 [11:56<00:48,  4.27it/s]

 94%|█████████▎| 3063/3268 [11:56<00:47,  4.27it/s]

 94%|█████████▍| 3064/3268 [11:57<00:47,  4.26it/s]

 94%|█████████▍| 3065/3268 [11:57<00:47,  4.26it/s]

 94%|█████████▍| 3066/3268 [11:57<00:47,  4.26it/s]

 94%|█████████▍| 3067/3268 [11:57<00:47,  4.27it/s]

 94%|█████████▍| 3068/3268 [11:57<00:46,  4.27it/s]

 94%|█████████▍| 3069/3268 [11:58<00:46,  4.28it/s]

 94%|█████████▍| 3070/3268 [11:58<00:46,  4.27it/s]

 94%|█████████▍| 3071/3268 [11:58<00:46,  4.26it/s]

 94%|█████████▍| 3072/3268 [11:58<00:45,  4.27it/s]

 94%|█████████▍| 3073/3268 [11:59<00:45,  4.27it/s]

 94%|█████████▍| 3074/3268 [11:59<00:45,  4.27it/s]

 94%|█████████▍| 3075/3268 [11:59<00:45,  4.27it/s]

 94%|█████████▍| 3076/3268 [11:59<00:44,  4.27it/s]

 94%|█████████▍| 3077/3268 [12:00<00:44,  4.28it/s]

 94%|█████████▍| 3078/3268 [12:00<00:44,  4.27it/s]

 94%|█████████▍| 3079/3268 [12:00<00:44,  4.27it/s]

 94%|█████████▍| 3080/3268 [12:00<00:43,  4.28it/s]

 94%|█████████▍| 3081/3268 [12:01<00:43,  4.28it/s]

 94%|█████████▍| 3082/3268 [12:01<00:43,  4.28it/s]

 94%|█████████▍| 3083/3268 [12:01<00:43,  4.28it/s]

 94%|█████████▍| 3084/3268 [12:01<00:43,  4.27it/s]

 94%|█████████▍| 3085/3268 [12:01<00:42,  4.27it/s]

 94%|█████████▍| 3086/3268 [12:02<00:42,  4.27it/s]

 94%|█████████▍| 3087/3268 [12:02<00:42,  4.28it/s]

 94%|█████████▍| 3088/3268 [12:02<00:42,  4.28it/s]

 95%|█████████▍| 3089/3268 [12:02<00:41,  4.27it/s]

 95%|█████████▍| 3090/3268 [12:03<00:41,  4.27it/s]

 95%|█████████▍| 3091/3268 [12:03<00:41,  4.26it/s]

 95%|█████████▍| 3092/3268 [12:03<00:41,  4.26it/s]

 95%|█████████▍| 3093/3268 [12:03<00:41,  4.26it/s]

 95%|█████████▍| 3094/3268 [12:04<00:40,  4.26it/s]

 95%|█████████▍| 3095/3268 [12:04<00:40,  4.27it/s]

 95%|█████████▍| 3096/3268 [12:04<00:40,  4.26it/s]

 95%|█████████▍| 3097/3268 [12:04<00:40,  4.26it/s]

 95%|█████████▍| 3098/3268 [12:04<00:39,  4.25it/s]

 95%|█████████▍| 3099/3268 [12:05<00:39,  4.24it/s]

 95%|█████████▍| 3100/3268 [12:05<00:39,  4.26it/s]

 95%|█████████▍| 3101/3268 [12:05<00:39,  4.26it/s]

 95%|█████████▍| 3102/3268 [12:05<00:38,  4.26it/s]

 95%|█████████▍| 3103/3268 [12:06<00:38,  4.26it/s]

 95%|█████████▍| 3104/3268 [12:06<00:38,  4.26it/s]

 95%|█████████▌| 3105/3268 [12:06<00:38,  4.26it/s]

 95%|█████████▌| 3106/3268 [12:06<00:38,  4.26it/s]

 95%|█████████▌| 3107/3268 [12:07<00:37,  4.25it/s]

 95%|█████████▌| 3108/3268 [12:07<00:37,  4.25it/s]

 95%|█████████▌| 3109/3268 [12:07<00:37,  4.25it/s]

 95%|█████████▌| 3110/3268 [12:07<00:37,  4.26it/s]

 95%|█████████▌| 3111/3268 [12:08<00:36,  4.26it/s]

 95%|█████████▌| 3112/3268 [12:08<00:36,  4.26it/s]

 95%|█████████▌| 3113/3268 [12:08<00:36,  4.26it/s]

 95%|█████████▌| 3114/3268 [12:08<00:36,  4.25it/s]

 95%|█████████▌| 3115/3268 [12:08<00:35,  4.26it/s]

 95%|█████████▌| 3116/3268 [12:09<00:35,  4.25it/s]

 95%|█████████▌| 3117/3268 [12:09<00:35,  4.25it/s]

 95%|█████████▌| 3118/3268 [12:09<00:35,  4.26it/s]

 95%|█████████▌| 3119/3268 [12:09<00:35,  4.25it/s]

 95%|█████████▌| 3120/3268 [12:10<00:34,  4.25it/s]

 96%|█████████▌| 3121/3268 [12:10<00:34,  4.25it/s]

 96%|█████████▌| 3122/3268 [12:10<00:34,  4.23it/s]

 96%|█████████▌| 3123/3268 [12:10<00:34,  4.23it/s]

 96%|█████████▌| 3124/3268 [12:11<00:34,  4.23it/s]

 96%|█████████▌| 3125/3268 [12:11<00:33,  4.25it/s]

 96%|█████████▌| 3126/3268 [12:11<00:33,  4.26it/s]

 96%|█████████▌| 3127/3268 [12:11<00:33,  4.26it/s]

 96%|█████████▌| 3128/3268 [12:12<00:32,  4.25it/s]

 96%|█████████▌| 3129/3268 [12:12<00:32,  4.25it/s]

logging
logging the anndata

 96%|█████████▌| 3130/3268 [12:25<09:21,  4.07s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 96%|█████████▌| 3131/3268 [12:25<06:40,  2.92s/it]

 96%|█████████▌| 3132/3268 [12:25<04:47,  2.11s/it]

 96%|█████████▌| 3133/3268 [12:25<03:28,  1.55s/it]

 96%|█████████▌| 3134/3268 [12:26<02:34,  1.15s/it]

 96%|█████████▌| 3135/3268 [12:26<01:56,  1.14it/s]

 96%|█████████▌| 3136/3268 [12:26<01:29,  1.47it/s]

 96%|█████████▌| 3137/3268 [12:26<01:11,  1.84it/s]

 96%|█████████▌| 3138/3268 [12:27<00:58,  2.23it/s]

 96%|█████████▌| 3139/3268 [12:27<00:49,  2.62it/s]

 96%|█████████▌| 3140/3268 [12:27<00:43,  2.98it/s]

 96%|█████████▌| 3141/3268 [12:27<00:38,  3.30it/s]

 96%|█████████▌| 3142/3268 [12:28<00:35,  3.57it/s]

 96%|█████████▌| 3143/3268 [12:28<00:33,  3.78it/s]

 96%|█████████▌| 3144/3268 [12:28<00:31,  3.95it/s]

 96%|█████████▌| 3145/3268 [12:28<00:30,  4.06it/s]

 96%|█████████▋| 3146/3268 [12:28<00:29,  4.16it/s]

 96%|█████████▋| 3147/3268 [12:29<00:28,  4.23it/s]

 96%|█████████▋| 3148/3268 [12:29<00:28,  4.28it/s]

 96%|█████████▋| 3149/3268 [12:29<00:27,  4.31it/s]

 96%|█████████▋| 3150/3268 [12:29<00:27,  4.34it/s]

 96%|█████████▋| 3151/3268 [12:30<00:26,  4.35it/s]

 96%|█████████▋| 3152/3268 [12:30<00:26,  4.37it/s]

 96%|█████████▋| 3153/3268 [12:30<00:26,  4.38it/s]

 97%|█████████▋| 3154/3268 [12:30<00:26,  4.38it/s]

 97%|█████████▋| 3155/3268 [12:31<00:25,  4.38it/s]

 97%|█████████▋| 3156/3268 [12:31<00:25,  4.38it/s]

 97%|█████████▋| 3157/3268 [12:31<00:25,  4.37it/s]

 97%|█████████▋| 3158/3268 [12:31<00:25,  4.38it/s]

 97%|█████████▋| 3159/3268 [12:31<00:24,  4.38it/s]

 97%|█████████▋| 3160/3268 [12:32<00:24,  4.38it/s]

 97%|█████████▋| 3161/3268 [12:32<00:24,  4.38it/s]

 97%|█████████▋| 3162/3268 [12:32<00:24,  4.38it/s]

 97%|█████████▋| 3163/3268 [12:32<00:23,  4.38it/s]

 97%|█████████▋| 3164/3268 [12:33<00:23,  4.38it/s]

 97%|█████████▋| 3165/3268 [12:33<00:23,  4.36it/s]

 97%|█████████▋| 3166/3268 [12:33<00:23,  4.36it/s]

 97%|█████████▋| 3167/3268 [12:33<00:23,  4.37it/s]

 97%|█████████▋| 3168/3268 [12:33<00:22,  4.37it/s]

 97%|█████████▋| 3169/3268 [12:34<00:22,  4.38it/s]

 97%|█████████▋| 3170/3268 [12:34<00:22,  4.38it/s]

 97%|█████████▋| 3171/3268 [12:34<00:22,  4.38it/s]

 97%|█████████▋| 3172/3268 [12:34<00:21,  4.38it/s]

 97%|█████████▋| 3173/3268 [12:35<00:21,  4.37it/s]

 97%|█████████▋| 3174/3268 [12:35<00:21,  4.38it/s]

 97%|█████████▋| 3175/3268 [12:35<00:21,  4.38it/s]

 97%|█████████▋| 3176/3268 [12:35<00:20,  4.38it/s]

 97%|█████████▋| 3177/3268 [12:36<00:20,  4.38it/s]

 97%|█████████▋| 3178/3268 [12:36<00:20,  4.39it/s]

 97%|█████████▋| 3179/3268 [12:36<00:20,  4.38it/s]

 97%|█████████▋| 3180/3268 [12:36<00:20,  4.38it/s]

 97%|█████████▋| 3181/3268 [12:36<00:19,  4.36it/s]

 97%|█████████▋| 3182/3268 [12:37<00:19,  4.37it/s]

 97%|█████████▋| 3183/3268 [12:37<00:19,  4.38it/s]

 97%|█████████▋| 3184/3268 [12:37<00:19,  4.38it/s]

 97%|█████████▋| 3185/3268 [12:37<00:18,  4.38it/s]

 97%|█████████▋| 3186/3268 [12:38<00:18,  4.37it/s]

 98%|█████████▊| 3187/3268 [12:38<00:18,  4.38it/s]

 98%|█████████▊| 3188/3268 [12:38<00:18,  4.38it/s]

 98%|█████████▊| 3189/3268 [12:38<00:17,  4.39it/s]

 98%|█████████▊| 3190/3268 [12:38<00:17,  4.40it/s]

 98%|█████████▊| 3191/3268 [12:39<00:17,  4.39it/s]

 98%|█████████▊| 3192/3268 [12:39<00:17,  4.39it/s]

 98%|█████████▊| 3193/3268 [12:39<00:17,  4.39it/s]

 98%|█████████▊| 3194/3268 [12:39<00:16,  4.38it/s]

 98%|█████████▊| 3195/3268 [12:40<00:16,  4.38it/s]

 98%|█████████▊| 3196/3268 [12:40<00:16,  4.38it/s]

 98%|█████████▊| 3197/3268 [12:40<00:16,  4.38it/s]

 98%|█████████▊| 3198/3268 [12:40<00:15,  4.38it/s]

 98%|█████████▊| 3199/3268 [12:41<00:15,  4.38it/s]

 98%|█████████▊| 3200/3268 [12:41<00:15,  4.39it/s]

 98%|█████████▊| 3201/3268 [12:41<00:15,  4.39it/s]

 98%|█████████▊| 3202/3268 [12:41<00:15,  4.38it/s]

 98%|█████████▊| 3203/3268 [12:41<00:14,  4.39it/s]

 98%|█████████▊| 3204/3268 [12:42<00:14,  4.39it/s]

 98%|█████████▊| 3205/3268 [12:42<00:14,  4.39it/s]

 98%|█████████▊| 3206/3268 [12:42<00:14,  4.38it/s]

 98%|█████████▊| 3207/3268 [12:42<00:13,  4.39it/s]

 98%|█████████▊| 3208/3268 [12:43<00:13,  4.39it/s]

 98%|█████████▊| 3209/3268 [12:43<00:13,  4.38it/s]

 98%|█████████▊| 3210/3268 [12:43<00:13,  4.38it/s]

 98%|█████████▊| 3211/3268 [12:43<00:13,  4.38it/s]

 98%|█████████▊| 3212/3268 [12:44<00:12,  4.38it/s]

 98%|█████████▊| 3213/3268 [12:44<00:12,  4.37it/s]

 98%|█████████▊| 3214/3268 [12:44<00:12,  4.38it/s]

 98%|█████████▊| 3215/3268 [12:44<00:12,  4.38it/s]

 98%|█████████▊| 3216/3268 [12:44<00:11,  4.38it/s]

 98%|█████████▊| 3217/3268 [12:45<00:11,  4.35it/s]

 98%|█████████▊| 3218/3268 [12:45<00:11,  4.35it/s]

 99%|█████████▊| 3219/3268 [12:45<00:11,  4.36it/s]

 99%|█████████▊| 3220/3268 [12:45<00:10,  4.36it/s]

 99%|█████████▊| 3221/3268 [12:46<00:10,  4.36it/s]

 99%|█████████▊| 3222/3268 [12:46<00:10,  4.37it/s]

 99%|█████████▊| 3223/3268 [12:46<00:10,  4.37it/s]

 99%|█████████▊| 3224/3268 [12:46<00:10,  4.37it/s]

 99%|█████████▊| 3225/3268 [12:46<00:09,  4.37it/s]

 99%|█████████▊| 3226/3268 [12:47<00:09,  4.36it/s]

 99%|█████████▊| 3227/3268 [12:47<00:09,  4.34it/s]

 99%|█████████▉| 3228/3268 [12:47<00:09,  4.36it/s]

 99%|█████████▉| 3229/3268 [12:47<00:08,  4.36it/s]

 99%|█████████▉| 3230/3268 [12:48<00:08,  4.36it/s]

 99%|█████████▉| 3231/3268 [12:48<00:08,  4.37it/s]

 99%|█████████▉| 3232/3268 [12:48<00:08,  4.36it/s]

 99%|█████████▉| 3233/3268 [12:48<00:08,  4.37it/s]

 99%|█████████▉| 3234/3268 [12:49<00:07,  4.37it/s]

 99%|█████████▉| 3235/3268 [12:49<00:07,  4.37it/s]

 99%|█████████▉| 3236/3268 [12:49<00:07,  4.37it/s]

 99%|█████████▉| 3237/3268 [12:49<00:07,  4.37it/s]

 99%|█████████▉| 3238/3268 [12:49<00:06,  4.36it/s]

 99%|█████████▉| 3239/3268 [12:50<00:06,  4.36it/s]

 99%|█████████▉| 3240/3268 [12:50<00:06,  4.36it/s]

 99%|█████████▉| 3241/3268 [12:50<00:06,  4.37it/s]

 99%|█████████▉| 3242/3268 [12:50<00:05,  4.35it/s]

 99%|█████████▉| 3243/3268 [12:51<00:05,  4.34it/s]

 99%|█████████▉| 3244/3268 [12:51<00:05,  4.35it/s]

 99%|█████████▉| 3245/3268 [12:51<00:05,  4.35it/s]

 99%|█████████▉| 3246/3268 [12:51<00:05,  4.35it/s]

 99%|█████████▉| 3247/3268 [12:52<00:04,  4.37it/s]

 99%|█████████▉| 3248/3268 [12:52<00:04,  4.37it/s]

 99%|█████████▉| 3249/3268 [12:52<00:04,  4.36it/s]

 99%|█████████▉| 3250/3268 [12:52<00:04,  4.36it/s]

 99%|█████████▉| 3251/3268 [12:52<00:03,  4.37it/s]

100%|█████████▉| 3252/3268 [12:53<00:03,  4.37it/s]

100%|█████████▉| 3253/3268 [12:53<00:03,  4.37it/s]

100%|█████████▉| 3254/3268 [12:53<00:03,  4.38it/s]

100%|█████████▉| 3255/3268 [12:53<00:02,  4.38it/s]

100%|█████████▉| 3256/3268 [12:54<00:02,  4.38it/s]

100%|█████████▉| 3257/3268 [12:54<00:02,  4.38it/s]

100%|█████████▉| 3258/3268 [12:54<00:02,  4.38it/s]

100%|█████████▉| 3259/3268 [12:54<00:02,  4.38it/s]

100%|█████████▉| 3260/3268 [12:55<00:01,  4.37it/s]

100%|█████████▉| 3261/3268 [12:55<00:01,  4.38it/s]

100%|█████████▉| 3262/3268 [12:55<00:01,  4.37it/s]

100%|█████████▉| 3263/3268 [12:55<00:01,  4.36it/s]

100%|█████████▉| 3264/3268 [12:55<00:00,  4.36it/s]

100%|█████████▉| 3265/3268 [12:56<00:00,  4.36it/s]

100%|█████████▉| 3266/3268 [12:56<00:00,  4.37it/s]

100%|█████████▉| 3267/3268 [12:56<00:00,  4.38it/s]

100%|██████████| 3268/3268 [12:56<00:00,  4.97it/s]

100%|██████████| 3268/3268 [12:57<00:00,  4.20it/s]

logging the anndata

AnnData object with n_obs × n_vars = 8806 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

too few cells to embed into a umap
too few cells to compute a clustering

{'cellxgene_census/dkd_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4937716969573208, 'macro': 0.38015219981782045, 'micro': 0.4937716969573208, 'weighted': 0.44125553939089207}}, 'cellxgene_census/dkd_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4630541871921182, 'macro': 0.39612779635380635, 'micro': 0.4630541871921182, 'weighted': 0.43238258813181274}}, 'cellxgene_census/gtex_v9_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.662801373334736, 'macro': 0.45113362926393386, 'micro': 0.662801373334736, 'weighted': 0.6076783134412977}}, 'cellxgene_census/gtex_v9_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4894855752519986, 'macro': 0.5275646372211268, 'micro': 0.4894855752519986, 'weighted': 0.45377925621844867}}}

doing  cellxgene_census/hypomap

/lustre/fswork/projects/rech/xeg/uat95fg/scdataloader/scdataloader/utils.py:427: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  organismdf = pd.concat(organismdf)

predict epoch start

  0%|          | 0/6015 [00:00<?, ?it/s]

  0%|          | 1/6015 [00:05<9:38:03,  5.77s/it]

  0%|          | 2/6015 [00:05<4:11:18,  2.51s/it]

  0%|          | 3/6015 [00:06<2:27:10,  1.47s/it]

  0%|          | 4/6015 [00:06<1:37:57,  1.02it/s]

  0%|          | 5/6015 [00:06<1:10:39,  1.42it/s]

  0%|          | 6/6015 [00:06<54:15,  1.85it/s]

  0%|          | 7/6015 [00:07<43:50,  2.28it/s]

  0%|          | 8/6015 [00:07<37:00,  2.70it/s]

  0%|          | 9/6015 [00:07<32:36,  3.07it/s]

  0%|          | 10/6015 [00:07<29:29,  3.39it/s]

  0%|          | 11/6015 [00:08<27:18,  3.66it/s]

  0%|          | 12/6015 [00:08<25:47,  3.88it/s]

  0%|          | 13/6015 [00:08<24:43,  4.05it/s]

  0%|          | 14/6015 [00:08<24:01,  4.16it/s]

  0%|          | 15/6015 [00:08<23:30,  4.25it/s]

  0%|          | 16/6015 [00:09<23:14,  4.30it/s]

  0%|          | 17/6015 [00:09<22:58,  4.35it/s]

  0%|          | 18/6015 [00:09<22:51,  4.37it/s]

  0%|          | 19/6015 [00:09<22:47,  4.39it/s]

  0%|          | 20/6015 [00:10<22:42,  4.40it/s]

  0%|          | 21/6015 [00:10<22:38,  4.41it/s]

  0%|          | 22/6015 [00:10<22:38,  4.41it/s]

  0%|          | 23/6015 [00:10<22:33,  4.43it/s]

  0%|          | 24/6015 [00:10<22:33,  4.43it/s]

  0%|          | 25/6015 [00:11<22:33,  4.42it/s]

  0%|          | 26/6015 [00:11<22:35,  4.42it/s]

  0%|          | 27/6015 [00:11<22:34,  4.42it/s]

  0%|          | 28/6015 [00:11<22:39,  4.40it/s]

  0%|          | 29/6015 [00:12<22:36,  4.41it/s]

  0%|          | 30/6015 [00:12<22:35,  4.42it/s]

  1%|          | 31/6015 [00:12<22:35,  4.41it/s]

  1%|          | 32/6015 [00:12<22:33,  4.42it/s]

  1%|          | 33/6015 [00:12<22:28,  4.44it/s]

  1%|          | 34/6015 [00:13<22:26,  4.44it/s]

  1%|          | 35/6015 [00:13<22:30,  4.43it/s]

  1%|          | 36/6015 [00:13<22:31,  4.43it/s]

  1%|          | 37/6015 [00:13<22:29,  4.43it/s]

  1%|          | 38/6015 [00:14<22:30,  4.43it/s]

  1%|          | 39/6015 [00:14<22:30,  4.42it/s]

  1%|          | 40/6015 [00:14<22:29,  4.43it/s]

  1%|          | 41/6015 [00:14<22:31,  4.42it/s]

  1%|          | 42/6015 [00:15<22:31,  4.42it/s]

  1%|          | 43/6015 [00:15<22:30,  4.42it/s]

  1%|          | 44/6015 [00:15<22:26,  4.43it/s]

  1%|          | 45/6015 [00:15<22:27,  4.43it/s]

  1%|          | 46/6015 [00:15<22:24,  4.44it/s]

  1%|          | 47/6015 [00:16<22:25,  4.43it/s]

  1%|          | 48/6015 [00:16<22:28,  4.43it/s]

  1%|          | 49/6015 [00:16<22:28,  4.42it/s]

  1%|          | 50/6015 [00:16<22:28,  4.42it/s]

  1%|          | 51/6015 [00:17<22:27,  4.43it/s]

  1%|          | 52/6015 [00:17<22:41,  4.38it/s]

  1%|          | 53/6015 [00:17<22:36,  4.40it/s]

  1%|          | 54/6015 [00:17<22:34,  4.40it/s]

  1%|          | 55/6015 [00:17<22:29,  4.42it/s]

  1%|          | 56/6015 [00:18<22:30,  4.41it/s]

  1%|          | 57/6015 [00:18<22:28,  4.42it/s]

  1%|          | 58/6015 [00:18<22:28,  4.42it/s]

  1%|          | 59/6015 [00:18<22:28,  4.42it/s]

  1%|          | 60/6015 [00:19<22:28,  4.42it/s]

  1%|          | 61/6015 [00:19<22:26,  4.42it/s]

  1%|          | 62/6015 [00:19<22:27,  4.42it/s]

  1%|          | 63/6015 [00:19<22:27,  4.42it/s]

  1%|          | 64/6015 [00:19<22:28,  4.41it/s]

  1%|          | 65/6015 [00:20<22:27,  4.41it/s]

  1%|          | 66/6015 [00:20<22:26,  4.42it/s]

  1%|          | 67/6015 [00:20<22:28,  4.41it/s]

  1%|          | 68/6015 [00:20<22:25,  4.42it/s]

  1%|          | 69/6015 [00:21<22:23,  4.43it/s]

  1%|          | 70/6015 [00:21<22:21,  4.43it/s]

  1%|          | 71/6015 [00:21<22:23,  4.42it/s]

  1%|          | 72/6015 [00:21<22:22,  4.43it/s]

  1%|          | 73/6015 [00:22<22:26,  4.41it/s]

  1%|          | 74/6015 [00:22<22:24,  4.42it/s]

  1%|          | 75/6015 [00:22<22:25,  4.41it/s]

  1%|▏         | 76/6015 [00:22<22:27,  4.41it/s]

  1%|▏         | 77/6015 [00:22<22:42,  4.36it/s]

  1%|▏         | 78/6015 [00:23<22:38,  4.37it/s]

  1%|▏         | 79/6015 [00:23<22:36,  4.38it/s]

  1%|▏         | 80/6015 [00:23<22:32,  4.39it/s]

  1%|▏         | 81/6015 [00:23<22:30,  4.39it/s]

  1%|▏         | 82/6015 [00:24<22:30,  4.39it/s]

  1%|▏         | 83/6015 [00:24<22:27,  4.40it/s]

  1%|▏         | 84/6015 [00:24<22:29,  4.39it/s]

  1%|▏         | 85/6015 [00:24<22:34,  4.38it/s]

  1%|▏         | 86/6015 [00:24<22:30,  4.39it/s]

  1%|▏         | 87/6015 [00:25<22:27,  4.40it/s]

  1%|▏         | 88/6015 [00:25<22:27,  4.40it/s]

  1%|▏         | 89/6015 [00:25<22:22,  4.41it/s]

  1%|▏         | 90/6015 [00:25<22:22,  4.41it/s]

  2%|▏         | 91/6015 [00:26<22:24,  4.41it/s]

  2%|▏         | 92/6015 [00:26<22:23,  4.41it/s]

  2%|▏         | 93/6015 [00:26<22:26,  4.40it/s]

  2%|▏         | 94/6015 [00:26<22:23,  4.41it/s]

  2%|▏         | 95/6015 [00:27<22:24,  4.40it/s]

  2%|▏         | 96/6015 [00:27<22:26,  4.40it/s]

  2%|▏         | 97/6015 [00:27<22:25,  4.40it/s]

  2%|▏         | 98/6015 [00:27<22:25,  4.40it/s]

  2%|▏         | 99/6015 [00:27<22:25,  4.40it/s]

  2%|▏         | 100/6015 [00:28<22:23,  4.40it/s]

  2%|▏         | 101/6015 [00:28<22:25,  4.40it/s]

  2%|▏         | 102/6015 [00:28<22:26,  4.39it/s]

  2%|▏         | 103/6015 [00:28<22:27,  4.39it/s]

  2%|▏         | 104/6015 [00:29<22:25,  4.39it/s]

  2%|▏         | 105/6015 [00:29<22:25,  4.39it/s]

  2%|▏         | 106/6015 [00:29<22:24,  4.39it/s]

  2%|▏         | 107/6015 [00:29<22:25,  4.39it/s]

  2%|▏         | 108/6015 [00:29<22:20,  4.41it/s]

  2%|▏         | 109/6015 [00:30<22:19,  4.41it/s]

  2%|▏         | 110/6015 [00:30<22:20,  4.41it/s]

  2%|▏         | 111/6015 [00:30<22:17,  4.41it/s]

  2%|▏         | 112/6015 [00:30<22:18,  4.41it/s]

  2%|▏         | 113/6015 [00:31<22:18,  4.41it/s]

  2%|▏         | 114/6015 [00:31<22:19,  4.41it/s]

  2%|▏         | 115/6015 [00:31<22:21,  4.40it/s]

  2%|▏         | 116/6015 [00:31<22:21,  4.40it/s]

  2%|▏         | 117/6015 [00:32<22:18,  4.41it/s]

  2%|▏         | 118/6015 [00:32<22:20,  4.40it/s]

  2%|▏         | 119/6015 [00:32<22:28,  4.37it/s]

  2%|▏         | 120/6015 [00:32<22:26,  4.38it/s]

  2%|▏         | 121/6015 [00:32<22:27,  4.38it/s]

  2%|▏         | 122/6015 [00:33<22:23,  4.39it/s]

  2%|▏         | 123/6015 [00:33<22:19,  4.40it/s]

  2%|▏         | 124/6015 [00:33<22:18,  4.40it/s]

  2%|▏         | 125/6015 [00:33<22:16,  4.41it/s]

  2%|▏         | 126/6015 [00:34<22:17,  4.40it/s]

  2%|▏         | 127/6015 [00:34<22:19,  4.40it/s]

  2%|▏         | 128/6015 [00:34<22:18,  4.40it/s]

  2%|▏         | 129/6015 [00:34<22:20,  4.39it/s]

  2%|▏         | 130/6015 [00:35<22:21,  4.39it/s]

  2%|▏         | 131/6015 [00:35<22:20,  4.39it/s]

  2%|▏         | 132/6015 [00:35<22:18,  4.39it/s]

  2%|▏         | 133/6015 [00:35<22:19,  4.39it/s]

  2%|▏         | 134/6015 [00:35<22:20,  4.39it/s]

  2%|▏         | 135/6015 [00:36<22:20,  4.39it/s]

  2%|▏         | 136/6015 [00:36<22:19,  4.39it/s]

  2%|▏         | 137/6015 [00:36<22:20,  4.38it/s]

  2%|▏         | 138/6015 [00:36<22:20,  4.39it/s]

  2%|▏         | 139/6015 [00:37<22:17,  4.39it/s]

  2%|▏         | 140/6015 [00:37<22:15,  4.40it/s]

  2%|▏         | 141/6015 [00:37<22:16,  4.40it/s]

  2%|▏         | 142/6015 [00:37<22:15,  4.40it/s]

  2%|▏         | 143/6015 [00:37<22:14,  4.40it/s]

  2%|▏         | 144/6015 [00:38<22:20,  4.38it/s]

  2%|▏         | 145/6015 [00:38<22:23,  4.37it/s]

  2%|▏         | 146/6015 [00:38<22:23,  4.37it/s]

  2%|▏         | 147/6015 [00:38<22:20,  4.38it/s]

  2%|▏         | 148/6015 [00:39<22:21,  4.37it/s]

  2%|▏         | 149/6015 [00:39<22:22,  4.37it/s]

  2%|▏         | 150/6015 [00:39<22:20,  4.37it/s]

  3%|▎         | 151/6015 [00:39<22:24,  4.36it/s]

  3%|▎         | 152/6015 [00:40<22:22,  4.37it/s]

  3%|▎         | 153/6015 [00:40<22:16,  4.39it/s]

  3%|▎         | 154/6015 [00:40<22:14,  4.39it/s]

  3%|▎         | 155/6015 [00:40<22:14,  4.39it/s]

  3%|▎         | 156/6015 [00:40<22:18,  4.38it/s]

  3%|▎         | 157/6015 [00:41<22:18,  4.38it/s]

  3%|▎         | 158/6015 [00:41<22:18,  4.37it/s]

  3%|▎         | 159/6015 [00:41<22:18,  4.37it/s]

  3%|▎         | 160/6015 [00:41<22:17,  4.38it/s]

  3%|▎         | 161/6015 [00:42<22:15,  4.38it/s]

  3%|▎         | 162/6015 [00:42<22:15,  4.38it/s]

  3%|▎         | 163/6015 [00:42<22:16,  4.38it/s]

  3%|▎         | 164/6015 [00:42<22:14,  4.38it/s]

  3%|▎         | 165/6015 [00:42<22:18,  4.37it/s]

  3%|▎         | 166/6015 [00:43<22:17,  4.37it/s]

  3%|▎         | 167/6015 [00:43<22:18,  4.37it/s]

  3%|▎         | 168/6015 [00:43<22:16,  4.38it/s]

  3%|▎         | 169/6015 [00:43<22:14,  4.38it/s]

  3%|▎         | 170/6015 [00:44<22:15,  4.38it/s]

  3%|▎         | 171/6015 [00:44<22:17,  4.37it/s]

  3%|▎         | 172/6015 [00:44<22:14,  4.38it/s]

  3%|▎         | 173/6015 [00:44<22:16,  4.37it/s]

  3%|▎         | 174/6015 [00:45<22:15,  4.37it/s]

  3%|▎         | 175/6015 [00:45<22:13,  4.38it/s]

  3%|▎         | 176/6015 [00:45<22:15,  4.37it/s]

  3%|▎         | 177/6015 [00:45<22:16,  4.37it/s]

  3%|▎         | 178/6015 [00:45<22:14,  4.37it/s]

  3%|▎         | 179/6015 [00:46<22:12,  4.38it/s]

  3%|▎         | 180/6015 [00:46<22:19,  4.35it/s]

  3%|▎         | 181/6015 [00:46<22:17,  4.36it/s]

  3%|▎         | 182/6015 [00:46<22:17,  4.36it/s]

  3%|▎         | 183/6015 [00:47<22:13,  4.37it/s]

  3%|▎         | 184/6015 [00:47<22:13,  4.37it/s]

  3%|▎         | 185/6015 [00:47<22:13,  4.37it/s]

  3%|▎         | 186/6015 [00:47<22:12,  4.37it/s]

  3%|▎         | 187/6015 [00:48<22:11,  4.38it/s]

  3%|▎         | 188/6015 [00:48<22:10,  4.38it/s]

  3%|▎         | 189/6015 [00:48<22:09,  4.38it/s]

  3%|▎         | 190/6015 [00:48<22:11,  4.38it/s]

  3%|▎         | 191/6015 [00:48<22:10,  4.38it/s]

  3%|▎         | 192/6015 [00:49<22:12,  4.37it/s]

  3%|▎         | 193/6015 [00:49<22:12,  4.37it/s]

  3%|▎         | 194/6015 [00:49<22:09,  4.38it/s]

  3%|▎         | 195/6015 [00:49<22:08,  4.38it/s]

  3%|▎         | 196/6015 [00:50<22:08,  4.38it/s]

  3%|▎         | 197/6015 [00:50<22:06,  4.38it/s]

  3%|▎         | 198/6015 [00:50<22:06,  4.38it/s]

  3%|▎         | 199/6015 [00:50<22:08,  4.38it/s]

  3%|▎         | 200/6015 [00:50<22:06,  4.38it/s]

  3%|▎         | 201/6015 [00:51<22:11,  4.37it/s]

  3%|▎         | 202/6015 [00:51<22:27,  4.32it/s]

  3%|▎         | 203/6015 [00:51<22:19,  4.34it/s]

  3%|▎         | 204/6015 [00:51<22:14,  4.35it/s]

  3%|▎         | 205/6015 [00:52<22:11,  4.36it/s]

  3%|▎         | 206/6015 [00:52<22:10,  4.37it/s]

  3%|▎         | 207/6015 [00:52<22:11,  4.36it/s]

  3%|▎         | 208/6015 [00:52<22:08,  4.37it/s]

  3%|▎         | 209/6015 [00:53<22:07,  4.37it/s]

  3%|▎         | 210/6015 [00:53<22:11,  4.36it/s]

  4%|▎         | 211/6015 [00:53<22:08,  4.37it/s]

  4%|▎         | 212/6015 [00:53<22:10,  4.36it/s]

  4%|▎         | 213/6015 [00:53<22:10,  4.36it/s]

  4%|▎         | 214/6015 [00:54<22:09,  4.36it/s]

  4%|▎         | 215/6015 [00:54<22:08,  4.37it/s]

  4%|▎         | 216/6015 [00:54<22:05,  4.38it/s]

  4%|▎         | 217/6015 [00:54<22:06,  4.37it/s]

  4%|▎         | 218/6015 [00:55<22:08,  4.36it/s]

  4%|▎         | 219/6015 [00:55<22:03,  4.38it/s]

  4%|▎         | 220/6015 [00:55<22:02,  4.38it/s]

  4%|▎         | 221/6015 [00:55<22:02,  4.38it/s]

  4%|▎         | 222/6015 [00:56<22:01,  4.38it/s]

  4%|▎         | 223/6015 [00:56<22:00,  4.39it/s]

  4%|▎         | 224/6015 [00:56<22:03,  4.38it/s]

  4%|▎         | 225/6015 [00:56<22:01,  4.38it/s]

  4%|▍         | 226/6015 [00:56<22:04,  4.37it/s]

  4%|▍         | 227/6015 [00:57<22:05,  4.37it/s]

  4%|▍         | 228/6015 [00:57<22:08,  4.35it/s]

  4%|▍         | 229/6015 [00:57<22:08,  4.35it/s]

  4%|▍         | 230/6015 [00:57<22:06,  4.36it/s]

  4%|▍         | 231/6015 [00:58<22:06,  4.36it/s]

  4%|▍         | 232/6015 [00:58<22:06,  4.36it/s]

  4%|▍         | 233/6015 [00:58<22:05,  4.36it/s]

  4%|▍         | 234/6015 [00:58<22:06,  4.36it/s]

  4%|▍         | 235/6015 [00:59<22:10,  4.34it/s]

  4%|▍         | 236/6015 [00:59<22:07,  4.35it/s]

  4%|▍         | 237/6015 [00:59<22:07,  4.35it/s]

  4%|▍         | 238/6015 [00:59<22:06,  4.35it/s]

  4%|▍         | 239/6015 [00:59<22:05,  4.36it/s]

  4%|▍         | 240/6015 [01:00<22:05,  4.36it/s]

  4%|▍         | 241/6015 [01:00<22:04,  4.36it/s]

  4%|▍         | 242/6015 [01:00<22:04,  4.36it/s]

  4%|▍         | 243/6015 [01:00<22:03,  4.36it/s]

  4%|▍         | 244/6015 [01:01<22:01,  4.37it/s]

  4%|▍         | 245/6015 [01:01<22:02,  4.36it/s]

  4%|▍         | 246/6015 [01:01<22:02,  4.36it/s]

  4%|▍         | 247/6015 [01:01<22:09,  4.34it/s]

  4%|▍         | 248/6015 [01:01<22:09,  4.34it/s]

  4%|▍         | 249/6015 [01:02<22:08,  4.34it/s]

  4%|▍         | 250/6015 [01:02<22:06,  4.35it/s]

  4%|▍         | 251/6015 [01:02<22:01,  4.36it/s]

  4%|▍         | 252/6015 [01:02<22:02,  4.36it/s]

  4%|▍         | 253/6015 [01:03<22:01,  4.36it/s]

  4%|▍         | 254/6015 [01:03<22:01,  4.36it/s]

  4%|▍         | 255/6015 [01:03<22:03,  4.35it/s]

  4%|▍         | 256/6015 [01:03<22:00,  4.36it/s]

  4%|▍         | 257/6015 [01:04<21:58,  4.37it/s]

  4%|▍         | 258/6015 [01:04<21:57,  4.37it/s]

  4%|▍         | 259/6015 [01:04<21:54,  4.38it/s]

  4%|▍         | 260/6015 [01:04<21:54,  4.38it/s]

  4%|▍         | 261/6015 [01:04<21:53,  4.38it/s]

  4%|▍         | 262/6015 [01:05<21:50,  4.39it/s]

  4%|▍         | 263/6015 [01:05<21:50,  4.39it/s]

  4%|▍         | 264/6015 [01:05<21:58,  4.36it/s]

  4%|▍         | 265/6015 [01:05<21:56,  4.37it/s]

  4%|▍         | 266/6015 [01:06<21:57,  4.36it/s]

  4%|▍         | 267/6015 [01:06<21:55,  4.37it/s]

  4%|▍         | 268/6015 [01:06<21:54,  4.37it/s]

  4%|▍         | 269/6015 [01:06<21:53,  4.38it/s]

  4%|▍         | 270/6015 [01:07<21:52,  4.38it/s]

  5%|▍         | 271/6015 [01:07<21:53,  4.37it/s]

  5%|▍         | 272/6015 [01:07<21:51,  4.38it/s]

  5%|▍         | 273/6015 [01:07<21:52,  4.37it/s]

  5%|▍         | 274/6015 [01:07<21:55,  4.36it/s]

  5%|▍         | 275/6015 [01:08<21:54,  4.37it/s]

  5%|▍         | 276/6015 [01:08<21:54,  4.37it/s]

  5%|▍         | 277/6015 [01:08<21:54,  4.36it/s]

  5%|▍         | 278/6015 [01:08<21:51,  4.37it/s]

  5%|▍         | 279/6015 [01:09<21:51,  4.37it/s]

  5%|▍         | 280/6015 [01:09<21:51,  4.37it/s]

  5%|▍         | 281/6015 [01:09<21:50,  4.37it/s]

  5%|▍         | 282/6015 [01:09<21:53,  4.36it/s]

  5%|▍         | 283/6015 [01:10<21:52,  4.37it/s]

  5%|▍         | 284/6015 [01:10<21:53,  4.36it/s]

  5%|▍         | 285/6015 [01:10<21:55,  4.36it/s]

  5%|▍         | 286/6015 [01:10<21:55,  4.35it/s]

  5%|▍         | 287/6015 [01:10<21:55,  4.36it/s]

  5%|▍         | 288/6015 [01:11<21:55,  4.35it/s]

  5%|▍         | 289/6015 [01:11<21:54,  4.36it/s]

  5%|▍         | 290/6015 [01:11<21:59,  4.34it/s]

  5%|▍         | 291/6015 [01:11<21:55,  4.35it/s]

  5%|▍         | 292/6015 [01:12<21:55,  4.35it/s]

  5%|▍         | 293/6015 [01:12<21:55,  4.35it/s]

  5%|▍         | 294/6015 [01:12<21:51,  4.36it/s]

  5%|▍         | 295/6015 [01:12<21:49,  4.37it/s]

  5%|▍         | 296/6015 [01:12<21:51,  4.36it/s]

  5%|▍         | 297/6015 [01:13<21:50,  4.36it/s]

  5%|▍         | 298/6015 [01:13<21:50,  4.36it/s]

  5%|▍         | 299/6015 [01:13<21:54,  4.35it/s]

  5%|▍         | 300/6015 [01:13<21:50,  4.36it/s]

  5%|▌         | 301/6015 [01:14<21:49,  4.36it/s]

  5%|▌         | 302/6015 [01:14<21:53,  4.35it/s]

  5%|▌         | 303/6015 [01:14<21:50,  4.36it/s]

  5%|▌         | 304/6015 [01:14<21:48,  4.37it/s]

  5%|▌         | 305/6015 [01:15<21:46,  4.37it/s]

  5%|▌         | 306/6015 [01:15<21:44,  4.38it/s]

  5%|▌         | 307/6015 [01:15<21:44,  4.38it/s]

  5%|▌         | 308/6015 [01:15<21:42,  4.38it/s]

  5%|▌         | 309/6015 [01:15<21:43,  4.38it/s]

  5%|▌         | 310/6015 [01:16<21:42,  4.38it/s]

  5%|▌         | 311/6015 [01:16<21:40,  4.39it/s]

  5%|▌         | 312/6015 [01:16<21:40,  4.39it/s]

  5%|▌         | 313/6015 [01:16<21:43,  4.37it/s]

  5%|▌         | 314/6015 [01:17<21:42,  4.38it/s]

  5%|▌         | 315/6015 [01:17<21:43,  4.37it/s]

  5%|▌         | 316/6015 [01:17<21:40,  4.38it/s]

  5%|▌         | 317/6015 [01:17<21:40,  4.38it/s]

  5%|▌         | 318/6015 [01:18<21:42,  4.37it/s]

  5%|▌         | 319/6015 [01:18<21:41,  4.38it/s]

  5%|▌         | 320/6015 [01:18<21:43,  4.37it/s]

  5%|▌         | 321/6015 [01:18<21:43,  4.37it/s]

  5%|▌         | 322/6015 [01:18<21:43,  4.37it/s]

  5%|▌         | 323/6015 [01:19<21:45,  4.36it/s]

  5%|▌         | 324/6015 [01:19<21:45,  4.36it/s]

  5%|▌         | 325/6015 [01:19<21:46,  4.36it/s]

  5%|▌         | 326/6015 [01:19<21:45,  4.36it/s]

  5%|▌         | 327/6015 [01:20<21:42,  4.37it/s]

  5%|▌         | 328/6015 [01:20<21:41,  4.37it/s]

  5%|▌         | 329/6015 [01:20<21:43,  4.36it/s]

  5%|▌         | 330/6015 [01:20<21:40,  4.37it/s]

  6%|▌         | 331/6015 [01:21<21:42,  4.36it/s]

  6%|▌         | 332/6015 [01:21<21:42,  4.36it/s]

  6%|▌         | 333/6015 [01:21<21:42,  4.36it/s]

  6%|▌         | 334/6015 [01:21<21:41,  4.36it/s]

  6%|▌         | 335/6015 [01:21<21:42,  4.36it/s]

  6%|▌         | 336/6015 [01:22<21:42,  4.36it/s]

  6%|▌         | 337/6015 [01:22<21:43,  4.36it/s]

  6%|▌         | 338/6015 [01:22<21:41,  4.36it/s]

  6%|▌         | 339/6015 [01:22<21:40,  4.36it/s]

  6%|▌         | 340/6015 [01:23<21:40,  4.37it/s]

  6%|▌         | 341/6015 [01:23<21:38,  4.37it/s]

  6%|▌         | 342/6015 [01:23<21:41,  4.36it/s]

  6%|▌         | 343/6015 [01:23<21:38,  4.37it/s]

  6%|▌         | 344/6015 [01:23<21:37,  4.37it/s]

  6%|▌         | 345/6015 [01:24<21:42,  4.35it/s]

  6%|▌         | 346/6015 [01:24<21:40,  4.36it/s]

  6%|▌         | 347/6015 [01:24<21:39,  4.36it/s]

  6%|▌         | 348/6015 [01:24<21:38,  4.36it/s]

  6%|▌         | 349/6015 [01:25<21:36,  4.37it/s]

  6%|▌         | 350/6015 [01:25<21:35,  4.37it/s]

  6%|▌         | 351/6015 [01:25<21:36,  4.37it/s]

  6%|▌         | 352/6015 [01:25<21:39,  4.36it/s]

  6%|▌         | 353/6015 [01:26<21:40,  4.35it/s]

  6%|▌         | 354/6015 [01:26<21:43,  4.34it/s]

  6%|▌         | 355/6015 [01:26<21:42,  4.34it/s]

  6%|▌         | 356/6015 [01:26<21:44,  4.34it/s]

  6%|▌         | 357/6015 [01:26<21:41,  4.35it/s]

  6%|▌         | 358/6015 [01:27<21:37,  4.36it/s]

  6%|▌         | 359/6015 [01:27<21:39,  4.35it/s]

  6%|▌         | 360/6015 [01:27<21:37,  4.36it/s]

  6%|▌         | 361/6015 [01:27<21:40,  4.35it/s]

  6%|▌         | 362/6015 [01:28<21:42,  4.34it/s]

  6%|▌         | 363/6015 [01:28<21:42,  4.34it/s]

  6%|▌         | 364/6015 [01:28<21:43,  4.34it/s]

  6%|▌         | 365/6015 [01:28<21:42,  4.34it/s]

  6%|▌         | 366/6015 [01:29<21:39,  4.35it/s]

  6%|▌         | 367/6015 [01:29<21:41,  4.34it/s]

  6%|▌         | 368/6015 [01:29<21:38,  4.35it/s]

  6%|▌         | 369/6015 [01:29<21:40,  4.34it/s]

  6%|▌         | 370/6015 [01:29<21:41,  4.34it/s]

  6%|▌         | 371/6015 [01:30<21:36,  4.35it/s]

  6%|▌         | 372/6015 [01:30<21:41,  4.33it/s]

  6%|▌         | 373/6015 [01:30<21:38,  4.34it/s]

  6%|▌         | 374/6015 [01:30<21:38,  4.34it/s]

  6%|▌         | 375/6015 [01:31<21:40,  4.34it/s]

  6%|▋         | 376/6015 [01:31<21:36,  4.35it/s]

  6%|▋         | 377/6015 [01:31<21:39,  4.34it/s]

  6%|▋         | 378/6015 [01:31<21:39,  4.34it/s]

  6%|▋         | 379/6015 [01:32<21:38,  4.34it/s]

  6%|▋         | 380/6015 [01:32<21:40,  4.33it/s]

  6%|▋         | 381/6015 [01:32<21:39,  4.33it/s]

  6%|▋         | 382/6015 [01:32<21:39,  4.33it/s]

  6%|▋         | 383/6015 [01:32<21:37,  4.34it/s]

  6%|▋         | 384/6015 [01:33<21:33,  4.35it/s]

  6%|▋         | 385/6015 [01:33<21:36,  4.34it/s]

  6%|▋         | 386/6015 [01:33<21:36,  4.34it/s]

  6%|▋         | 387/6015 [01:33<21:37,  4.34it/s]

  6%|▋         | 388/6015 [01:34<21:37,  4.34it/s]

  6%|▋         | 389/6015 [01:34<21:34,  4.34it/s]

  6%|▋         | 390/6015 [01:34<21:34,  4.35it/s]

  7%|▋         | 391/6015 [01:34<21:33,  4.35it/s]

  7%|▋         | 392/6015 [01:35<21:33,  4.35it/s]

  7%|▋         | 393/6015 [01:35<21:34,  4.34it/s]

  7%|▋         | 394/6015 [01:35<21:32,  4.35it/s]

  7%|▋         | 395/6015 [01:35<21:31,  4.35it/s]

  7%|▋         | 396/6015 [01:35<21:34,  4.34it/s]

  7%|▋         | 397/6015 [01:36<21:33,  4.34it/s]

  7%|▋         | 398/6015 [01:36<21:34,  4.34it/s]

  7%|▋         | 399/6015 [01:36<21:35,  4.33it/s]

  7%|▋         | 400/6015 [01:36<21:33,  4.34it/s]

  7%|▋         | 401/6015 [01:37<21:33,  4.34it/s]

  7%|▋         | 402/6015 [01:37<21:35,  4.33it/s]

  7%|▋         | 403/6015 [01:37<21:35,  4.33it/s]

  7%|▋         | 404/6015 [01:37<21:36,  4.33it/s]

  7%|▋         | 405/6015 [01:38<21:35,  4.33it/s]

  7%|▋         | 406/6015 [01:38<21:33,  4.33it/s]

  7%|▋         | 407/6015 [01:38<21:34,  4.33it/s]

  7%|▋         | 408/6015 [01:38<21:33,  4.33it/s]

  7%|▋         | 409/6015 [01:38<21:35,  4.33it/s]

  7%|▋         | 410/6015 [01:39<21:32,  4.34it/s]

  7%|▋         | 411/6015 [01:39<21:31,  4.34it/s]

  7%|▋         | 412/6015 [01:39<21:30,  4.34it/s]

  7%|▋         | 413/6015 [01:39<21:30,  4.34it/s]

  7%|▋         | 414/6015 [01:40<21:31,  4.34it/s]

  7%|▋         | 415/6015 [01:40<21:32,  4.33it/s]

  7%|▋         | 416/6015 [01:40<21:28,  4.34it/s]

  7%|▋         | 417/6015 [01:40<21:32,  4.33it/s]

  7%|▋         | 418/6015 [01:41<21:32,  4.33it/s]

  7%|▋         | 419/6015 [01:41<21:33,  4.32it/s]

  7%|▋         | 420/6015 [01:41<21:33,  4.33it/s]

  7%|▋         | 421/6015 [01:41<21:35,  4.32it/s]

  7%|▋         | 422/6015 [01:41<21:35,  4.32it/s]

  7%|▋         | 423/6015 [01:42<21:33,  4.32it/s]

  7%|▋         | 424/6015 [01:42<21:30,  4.33it/s]

  7%|▋         | 425/6015 [01:42<21:30,  4.33it/s]

  7%|▋         | 426/6015 [01:42<21:28,  4.34it/s]

  7%|▋         | 427/6015 [01:43<21:36,  4.31it/s]

  7%|▋         | 428/6015 [01:43<21:34,  4.32it/s]

  7%|▋         | 429/6015 [01:43<21:32,  4.32it/s]

  7%|▋         | 430/6015 [01:43<21:31,  4.32it/s]

  7%|▋         | 431/6015 [01:44<21:35,  4.31it/s]

  7%|▋         | 432/6015 [01:44<21:31,  4.32it/s]

  7%|▋         | 433/6015 [01:44<21:29,  4.33it/s]

  7%|▋         | 434/6015 [01:44<21:27,  4.34it/s]

  7%|▋         | 435/6015 [01:44<21:30,  4.32it/s]

  7%|▋         | 436/6015 [01:45<21:29,  4.33it/s]

  7%|▋         | 437/6015 [01:45<21:25,  4.34it/s]

  7%|▋         | 438/6015 [01:45<21:25,  4.34it/s]

  7%|▋         | 439/6015 [01:45<21:29,  4.32it/s]

  7%|▋         | 440/6015 [01:46<21:26,  4.33it/s]

  7%|▋         | 441/6015 [01:46<21:26,  4.33it/s]

  7%|▋         | 442/6015 [01:46<21:25,  4.34it/s]

  7%|▋         | 443/6015 [01:46<21:26,  4.33it/s]

  7%|▋         | 444/6015 [01:47<21:27,  4.33it/s]

  7%|▋         | 445/6015 [01:47<21:25,  4.33it/s]

  7%|▋         | 446/6015 [01:47<21:25,  4.33it/s]

  7%|▋         | 447/6015 [01:47<21:27,  4.32it/s]

  7%|▋         | 448/6015 [01:47<21:25,  4.33it/s]

  7%|▋         | 449/6015 [01:48<21:24,  4.33it/s]

  7%|▋         | 450/6015 [01:48<21:25,  4.33it/s]

  7%|▋         | 451/6015 [01:48<21:21,  4.34it/s]

  8%|▊         | 452/6015 [01:48<21:21,  4.34it/s]

  8%|▊         | 453/6015 [01:49<21:21,  4.34it/s]

  8%|▊         | 454/6015 [01:49<21:22,  4.34it/s]

  8%|▊         | 455/6015 [01:49<21:21,  4.34it/s]

  8%|▊         | 456/6015 [01:49<21:17,  4.35it/s]

  8%|▊         | 457/6015 [01:50<21:20,  4.34it/s]

  8%|▊         | 458/6015 [01:50<21:18,  4.35it/s]

  8%|▊         | 459/6015 [01:50<21:17,  4.35it/s]

  8%|▊         | 460/6015 [01:50<21:18,  4.35it/s]

  8%|▊         | 461/6015 [01:50<21:18,  4.35it/s]

  8%|▊         | 462/6015 [01:51<21:16,  4.35it/s]

  8%|▊         | 463/6015 [01:51<21:15,  4.35it/s]

  8%|▊         | 464/6015 [01:51<21:14,  4.35it/s]

  8%|▊         | 465/6015 [01:51<21:16,  4.35it/s]

  8%|▊         | 466/6015 [01:52<21:16,  4.35it/s]

  8%|▊         | 467/6015 [01:52<21:18,  4.34it/s]

  8%|▊         | 468/6015 [01:52<21:23,  4.32it/s]

  8%|▊         | 469/6015 [01:52<21:23,  4.32it/s]

  8%|▊         | 470/6015 [01:53<21:26,  4.31it/s]

  8%|▊         | 471/6015 [01:53<21:27,  4.31it/s]

  8%|▊         | 472/6015 [01:53<21:24,  4.32it/s]

  8%|▊         | 473/6015 [01:53<21:22,  4.32it/s]

  8%|▊         | 474/6015 [01:53<21:22,  4.32it/s]

  8%|▊         | 475/6015 [01:54<21:21,  4.32it/s]

  8%|▊         | 476/6015 [01:54<21:22,  4.32it/s]

  8%|▊         | 477/6015 [01:54<21:22,  4.32it/s]

  8%|▊         | 478/6015 [01:54<21:22,  4.32it/s]

  8%|▊         | 479/6015 [01:55<21:23,  4.31it/s]

  8%|▊         | 480/6015 [01:55<21:22,  4.32it/s]

  8%|▊         | 481/6015 [01:55<21:23,  4.31it/s]

  8%|▊         | 482/6015 [01:55<21:24,  4.31it/s]

  8%|▊         | 483/6015 [01:56<21:26,  4.30it/s]

  8%|▊         | 484/6015 [01:56<21:25,  4.30it/s]

  8%|▊         | 485/6015 [01:56<21:23,  4.31it/s]

  8%|▊         | 486/6015 [01:56<21:21,  4.31it/s]

  8%|▊         | 487/6015 [01:56<21:22,  4.31it/s]

  8%|▊         | 488/6015 [01:57<21:22,  4.31it/s]

  8%|▊         | 489/6015 [01:57<21:23,  4.31it/s]

  8%|▊         | 490/6015 [01:57<21:21,  4.31it/s]

  8%|▊         | 491/6015 [01:57<21:22,  4.31it/s]

  8%|▊         | 492/6015 [01:58<21:24,  4.30it/s]

  8%|▊         | 493/6015 [01:58<21:21,  4.31it/s]

  8%|▊         | 494/6015 [01:58<21:19,  4.31it/s]

  8%|▊         | 495/6015 [01:58<21:22,  4.31it/s]

  8%|▊         | 496/6015 [01:59<21:20,  4.31it/s]

  8%|▊         | 497/6015 [01:59<21:21,  4.30it/s]

  8%|▊         | 498/6015 [01:59<21:18,  4.32it/s]

  8%|▊         | 499/6015 [01:59<21:19,  4.31it/s]

  8%|▊         | 500/6015 [01:59<21:15,  4.32it/s]

  8%|▊         | 501/6015 [02:00<21:14,  4.33it/s]

  8%|▊         | 502/6015 [02:00<21:14,  4.33it/s]

  8%|▊         | 503/6015 [02:00<21:14,  4.33it/s]

  8%|▊         | 504/6015 [02:00<21:16,  4.32it/s]

  8%|▊         | 505/6015 [02:01<21:16,  4.32it/s]

  8%|▊         | 506/6015 [02:01<21:13,  4.33it/s]

  8%|▊         | 507/6015 [02:01<21:13,  4.33it/s]

  8%|▊         | 508/6015 [02:01<21:16,  4.32it/s]

  8%|▊         | 509/6015 [02:02<21:13,  4.32it/s]

  8%|▊         | 510/6015 [02:02<21:15,  4.32it/s]

  8%|▊         | 511/6015 [02:02<21:20,  4.30it/s]

  9%|▊         | 512/6015 [02:02<21:21,  4.30it/s]

  9%|▊         | 513/6015 [02:03<21:21,  4.29it/s]

  9%|▊         | 514/6015 [02:03<21:18,  4.30it/s]

  9%|▊         | 515/6015 [02:03<21:17,  4.31it/s]

  9%|▊         | 516/6015 [02:03<21:21,  4.29it/s]

  9%|▊         | 517/6015 [02:03<21:20,  4.29it/s]

  9%|▊         | 518/6015 [02:04<21:20,  4.29it/s]

  9%|▊         | 519/6015 [02:04<21:18,  4.30it/s]

  9%|▊         | 520/6015 [02:04<21:23,  4.28it/s]

  9%|▊         | 521/6015 [02:04<21:23,  4.28it/s]

  9%|▊         | 522/6015 [02:05<21:22,  4.28it/s]

  9%|▊         | 523/6015 [02:05<21:22,  4.28it/s]

  9%|▊         | 524/6015 [02:05<21:23,  4.28it/s]

  9%|▊         | 525/6015 [02:05<21:21,  4.28it/s]

  9%|▊         | 526/6015 [02:06<21:25,  4.27it/s]

  9%|▉         | 527/6015 [02:06<21:22,  4.28it/s]

  9%|▉         | 528/6015 [02:06<21:21,  4.28it/s]

  9%|▉         | 529/6015 [02:06<21:25,  4.27it/s]

  9%|▉         | 530/6015 [02:06<21:21,  4.28it/s]

  9%|▉         | 531/6015 [02:07<21:20,  4.28it/s]

  9%|▉         | 532/6015 [02:07<21:21,  4.28it/s]

  9%|▉         | 533/6015 [02:07<21:18,  4.29it/s]

  9%|▉         | 534/6015 [02:07<21:21,  4.28it/s]

  9%|▉         | 535/6015 [02:08<21:19,  4.28it/s]

  9%|▉         | 536/6015 [02:08<21:19,  4.28it/s]

  9%|▉         | 537/6015 [02:08<21:17,  4.29it/s]

  9%|▉         | 538/6015 [02:08<21:18,  4.28it/s]

  9%|▉         | 539/6015 [02:09<21:19,  4.28it/s]

  9%|▉         | 540/6015 [02:09<21:20,  4.28it/s]

  9%|▉         | 541/6015 [02:09<21:17,  4.28it/s]

  9%|▉         | 542/6015 [02:09<21:17,  4.28it/s]

  9%|▉         | 543/6015 [02:10<21:16,  4.29it/s]

  9%|▉         | 544/6015 [02:10<21:14,  4.29it/s]

  9%|▉         | 545/6015 [02:10<21:17,  4.28it/s]

  9%|▉         | 546/6015 [02:10<21:15,  4.29it/s]

  9%|▉         | 547/6015 [02:10<21:16,  4.29it/s]

  9%|▉         | 548/6015 [02:11<21:15,  4.28it/s]

  9%|▉         | 549/6015 [02:11<21:14,  4.29it/s]

  9%|▉         | 550/6015 [02:11<21:13,  4.29it/s]

  9%|▉         | 551/6015 [02:11<21:12,  4.29it/s]

  9%|▉         | 552/6015 [02:12<21:12,  4.29it/s]

  9%|▉         | 553/6015 [02:12<21:16,  4.28it/s]

  9%|▉         | 554/6015 [02:12<21:16,  4.28it/s]

  9%|▉         | 555/6015 [02:12<21:16,  4.28it/s]

  9%|▉         | 556/6015 [02:13<21:38,  4.20it/s]

  9%|▉         | 557/6015 [02:13<21:30,  4.23it/s]

  9%|▉         | 558/6015 [02:13<21:21,  4.26it/s]

  9%|▉         | 559/6015 [02:13<21:16,  4.27it/s]

  9%|▉         | 560/6015 [02:13<21:19,  4.26it/s]

  9%|▉         | 561/6015 [02:14<21:20,  4.26it/s]

  9%|▉         | 562/6015 [02:14<21:16,  4.27it/s]

  9%|▉         | 563/6015 [02:14<21:16,  4.27it/s]

  9%|▉         | 564/6015 [02:14<21:13,  4.28it/s]

  9%|▉         | 565/6015 [02:15<21:12,  4.28it/s]

  9%|▉         | 566/6015 [02:15<21:13,  4.28it/s]

  9%|▉         | 567/6015 [02:15<21:13,  4.28it/s]

  9%|▉         | 568/6015 [02:15<21:12,  4.28it/s]

  9%|▉         | 569/6015 [02:16<21:12,  4.28it/s]

  9%|▉         | 570/6015 [02:16<21:12,  4.28it/s]

  9%|▉         | 571/6015 [02:16<21:14,  4.27it/s]

 10%|▉         | 572/6015 [02:16<21:09,  4.29it/s]

 10%|▉         | 573/6015 [02:17<21:11,  4.28it/s]

 10%|▉         | 574/6015 [02:17<21:12,  4.28it/s]

 10%|▉         | 575/6015 [02:17<21:11,  4.28it/s]

 10%|▉         | 576/6015 [02:17<21:09,  4.28it/s]

 10%|▉         | 577/6015 [02:17<21:07,  4.29it/s]

 10%|▉         | 578/6015 [02:18<21:08,  4.29it/s]

 10%|▉         | 579/6015 [02:18<21:19,  4.25it/s]

 10%|▉         | 580/6015 [02:18<21:15,  4.26it/s]

 10%|▉         | 581/6015 [02:18<21:15,  4.26it/s]

 10%|▉         | 582/6015 [02:19<21:13,  4.27it/s]

 10%|▉         | 583/6015 [02:19<21:10,  4.27it/s]

 10%|▉         | 584/6015 [02:19<21:12,  4.27it/s]

 10%|▉         | 585/6015 [02:19<21:11,  4.27it/s]

 10%|▉         | 586/6015 [02:20<21:13,  4.26it/s]

 10%|▉         | 587/6015 [02:20<21:10,  4.27it/s]

 10%|▉         | 588/6015 [02:20<21:11,  4.27it/s]

 10%|▉         | 589/6015 [02:20<21:14,  4.26it/s]

 10%|▉         | 590/6015 [02:21<21:10,  4.27it/s]

 10%|▉         | 591/6015 [02:21<21:09,  4.27it/s]

 10%|▉         | 592/6015 [02:21<21:07,  4.28it/s]

 10%|▉         | 593/6015 [02:21<21:08,  4.27it/s]

 10%|▉         | 594/6015 [02:21<21:08,  4.27it/s]

 10%|▉         | 595/6015 [02:22<21:10,  4.26it/s]

 10%|▉         | 596/6015 [02:22<21:09,  4.27it/s]

 10%|▉         | 597/6015 [02:22<21:06,  4.28it/s]

 10%|▉         | 598/6015 [02:22<21:08,  4.27it/s]

 10%|▉         | 599/6015 [02:23<21:08,  4.27it/s]

 10%|▉         | 600/6015 [02:23<21:06,  4.27it/s]

 10%|▉         | 601/6015 [02:23<21:07,  4.27it/s]

 10%|█         | 602/6015 [02:23<21:06,  4.27it/s]

 10%|█         | 603/6015 [02:24<21:06,  4.27it/s]

 10%|█         | 604/6015 [02:24<21:07,  4.27it/s]

 10%|█         | 605/6015 [02:24<21:04,  4.28it/s]

 10%|█         | 606/6015 [02:24<21:05,  4.27it/s]

 10%|█         | 607/6015 [02:24<21:04,  4.28it/s]

 10%|█         | 608/6015 [02:25<21:06,  4.27it/s]

 10%|█         | 609/6015 [02:25<21:08,  4.26it/s]

 10%|█         | 610/6015 [02:25<21:07,  4.26it/s]

 10%|█         | 611/6015 [02:25<21:07,  4.26it/s]

 10%|█         | 612/6015 [02:26<21:07,  4.26it/s]

 10%|█         | 613/6015 [02:26<21:06,  4.26it/s]

 10%|█         | 614/6015 [02:26<21:07,  4.26it/s]

 10%|█         | 615/6015 [02:26<21:05,  4.27it/s]

 10%|█         | 616/6015 [02:27<21:05,  4.27it/s]

 10%|█         | 617/6015 [02:27<21:06,  4.26it/s]

 10%|█         | 618/6015 [02:27<21:05,  4.27it/s]

 10%|█         | 619/6015 [02:27<21:06,  4.26it/s]

 10%|█         | 620/6015 [02:28<21:04,  4.27it/s]

 10%|█         | 621/6015 [02:28<21:05,  4.26it/s]

 10%|█         | 622/6015 [02:28<21:07,  4.26it/s]

 10%|█         | 623/6015 [02:28<21:06,  4.26it/s]

 10%|█         | 624/6015 [02:28<21:05,  4.26it/s]

 10%|█         | 625/6015 [02:29<21:03,  4.27it/s]

logging
logging the anndata

 10%|█         | 626/6015 [02:30<44:05,  2.04it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 10%|█         | 627/6015 [02:30<37:21,  2.40it/s]

 10%|█         | 628/6015 [02:30<32:15,  2.78it/s]

 10%|█         | 629/6015 [02:30<28:43,  3.13it/s]

 10%|█         | 630/6015 [02:31<26:12,  3.42it/s]

 10%|█         | 631/6015 [02:31<24:26,  3.67it/s]

 11%|█         | 632/6015 [02:31<23:14,  3.86it/s]

 11%|█         | 633/6015 [02:31<22:22,  4.01it/s]

 11%|█         | 634/6015 [02:32<21:46,  4.12it/s]

 11%|█         | 635/6015 [02:32<21:27,  4.18it/s]

 11%|█         | 636/6015 [02:32<21:08,  4.24it/s]

 11%|█         | 637/6015 [02:32<20:57,  4.28it/s]

 11%|█         | 638/6015 [02:33<20:48,  4.31it/s]

 11%|█         | 639/6015 [02:33<20:41,  4.33it/s]

 11%|█         | 640/6015 [02:33<20:36,  4.35it/s]

 11%|█         | 641/6015 [02:33<20:32,  4.36it/s]

 11%|█         | 642/6015 [02:33<20:30,  4.37it/s]

 11%|█         | 643/6015 [02:34<20:31,  4.36it/s]

 11%|█         | 644/6015 [02:34<20:29,  4.37it/s]

 11%|█         | 645/6015 [02:34<20:27,  4.38it/s]

 11%|█         | 646/6015 [02:34<20:39,  4.33it/s]

 11%|█         | 647/6015 [02:35<20:35,  4.35it/s]

 11%|█         | 648/6015 [02:35<20:32,  4.36it/s]

 11%|█         | 649/6015 [02:35<20:27,  4.37it/s]

 11%|█         | 650/6015 [02:35<20:26,  4.37it/s]

 11%|█         | 651/6015 [02:36<20:24,  4.38it/s]

 11%|█         | 652/6015 [02:36<20:23,  4.38it/s]

 11%|█         | 653/6015 [02:36<20:23,  4.38it/s]

 11%|█         | 654/6015 [02:36<20:22,  4.39it/s]

 11%|█         | 655/6015 [02:36<20:22,  4.38it/s]

 11%|█         | 656/6015 [02:37<20:22,  4.38it/s]

 11%|█         | 657/6015 [02:37<20:22,  4.38it/s]

 11%|█         | 658/6015 [02:37<20:22,  4.38it/s]

 11%|█         | 659/6015 [02:37<20:22,  4.38it/s]

 11%|█         | 660/6015 [02:38<20:20,  4.39it/s]

 11%|█         | 661/6015 [02:38<20:20,  4.39it/s]

 11%|█         | 662/6015 [02:38<20:21,  4.38it/s]

 11%|█         | 663/6015 [02:38<20:20,  4.39it/s]

 11%|█         | 664/6015 [02:38<20:21,  4.38it/s]

 11%|█         | 665/6015 [02:39<20:22,  4.37it/s]

 11%|█         | 666/6015 [02:39<20:20,  4.38it/s]

 11%|█         | 667/6015 [02:39<20:19,  4.38it/s]

 11%|█         | 668/6015 [02:39<20:19,  4.39it/s]

 11%|█         | 669/6015 [02:40<20:17,  4.39it/s]

 11%|█         | 670/6015 [02:40<20:18,  4.39it/s]

 11%|█         | 671/6015 [02:40<20:24,  4.36it/s]

 11%|█         | 672/6015 [02:40<20:23,  4.37it/s]

 11%|█         | 673/6015 [02:41<20:23,  4.36it/s]

 11%|█         | 674/6015 [02:41<20:20,  4.38it/s]

 11%|█         | 675/6015 [02:41<20:21,  4.37it/s]

 11%|█         | 676/6015 [02:41<20:21,  4.37it/s]

 11%|█▏        | 677/6015 [02:41<20:20,  4.37it/s]

 11%|█▏        | 678/6015 [02:42<20:19,  4.38it/s]

 11%|█▏        | 679/6015 [02:42<20:19,  4.37it/s]

 11%|█▏        | 680/6015 [02:42<20:18,  4.38it/s]

 11%|█▏        | 681/6015 [02:42<20:18,  4.38it/s]

 11%|█▏        | 682/6015 [02:43<20:28,  4.34it/s]

 11%|█▏        | 683/6015 [02:43<20:22,  4.36it/s]

 11%|█▏        | 684/6015 [02:43<20:23,  4.36it/s]

 11%|█▏        | 685/6015 [02:43<20:21,  4.36it/s]

 11%|█▏        | 686/6015 [02:44<20:19,  4.37it/s]

 11%|█▏        | 687/6015 [02:44<20:19,  4.37it/s]

 11%|█▏        | 688/6015 [02:44<20:18,  4.37it/s]

 11%|█▏        | 689/6015 [02:44<20:17,  4.38it/s]

 11%|█▏        | 690/6015 [02:44<20:20,  4.36it/s]

 11%|█▏        | 691/6015 [02:45<20:18,  4.37it/s]

 12%|█▏        | 692/6015 [02:45<20:18,  4.37it/s]

 12%|█▏        | 693/6015 [02:45<20:22,  4.35it/s]

 12%|█▏        | 694/6015 [02:45<20:19,  4.36it/s]

 12%|█▏        | 695/6015 [02:46<20:19,  4.36it/s]

 12%|█▏        | 696/6015 [02:46<20:17,  4.37it/s]

 12%|█▏        | 697/6015 [02:46<20:18,  4.36it/s]

 12%|█▏        | 698/6015 [02:46<20:18,  4.36it/s]

 12%|█▏        | 699/6015 [02:46<20:15,  4.37it/s]

 12%|█▏        | 700/6015 [02:47<20:16,  4.37it/s]

 12%|█▏        | 701/6015 [02:47<20:14,  4.37it/s]

 12%|█▏        | 702/6015 [02:47<20:15,  4.37it/s]

 12%|█▏        | 703/6015 [02:47<20:16,  4.37it/s]

 12%|█▏        | 704/6015 [02:48<20:19,  4.36it/s]

 12%|█▏        | 705/6015 [02:48<20:16,  4.36it/s]

 12%|█▏        | 706/6015 [02:48<20:16,  4.36it/s]

 12%|█▏        | 707/6015 [02:48<20:15,  4.37it/s]

 12%|█▏        | 708/6015 [02:49<20:14,  4.37it/s]

 12%|█▏        | 709/6015 [02:49<20:15,  4.37it/s]

 12%|█▏        | 710/6015 [02:49<20:13,  4.37it/s]

 12%|█▏        | 711/6015 [02:49<20:14,  4.37it/s]

 12%|█▏        | 712/6015 [02:49<20:16,  4.36it/s]

 12%|█▏        | 713/6015 [02:50<20:16,  4.36it/s]

 12%|█▏        | 714/6015 [02:50<20:15,  4.36it/s]

 12%|█▏        | 715/6015 [02:50<20:15,  4.36it/s]

 12%|█▏        | 716/6015 [02:50<20:13,  4.37it/s]

 12%|█▏        | 717/6015 [02:51<20:11,  4.37it/s]

 12%|█▏        | 718/6015 [02:51<20:10,  4.38it/s]

 12%|█▏        | 719/6015 [02:51<20:11,  4.37it/s]

 12%|█▏        | 720/6015 [02:51<20:15,  4.36it/s]

 12%|█▏        | 721/6015 [02:52<20:11,  4.37it/s]

 12%|█▏        | 722/6015 [02:52<20:10,  4.37it/s]

 12%|█▏        | 723/6015 [02:52<20:11,  4.37it/s]

 12%|█▏        | 724/6015 [02:52<20:08,  4.38it/s]

 12%|█▏        | 725/6015 [02:52<20:08,  4.38it/s]

 12%|█▏        | 726/6015 [02:53<20:06,  4.38it/s]

 12%|█▏        | 727/6015 [02:53<20:07,  4.38it/s]

 12%|█▏        | 728/6015 [02:53<20:11,  4.36it/s]

 12%|█▏        | 729/6015 [02:53<20:11,  4.36it/s]

 12%|█▏        | 730/6015 [02:54<20:11,  4.36it/s]

 12%|█▏        | 731/6015 [02:54<20:12,  4.36it/s]

 12%|█▏        | 732/6015 [02:54<20:11,  4.36it/s]

 12%|█▏        | 733/6015 [02:54<20:11,  4.36it/s]

 12%|█▏        | 734/6015 [02:55<20:09,  4.37it/s]

 12%|█▏        | 735/6015 [02:55<20:10,  4.36it/s]

 12%|█▏        | 736/6015 [02:55<20:10,  4.36it/s]

 12%|█▏        | 737/6015 [02:55<20:06,  4.37it/s]

 12%|█▏        | 738/6015 [02:55<20:06,  4.37it/s]

 12%|█▏        | 739/6015 [02:56<20:08,  4.36it/s]

 12%|█▏        | 740/6015 [02:56<20:08,  4.36it/s]

 12%|█▏        | 741/6015 [02:56<20:12,  4.35it/s]

 12%|█▏        | 742/6015 [02:56<20:10,  4.36it/s]

 12%|█▏        | 743/6015 [02:57<20:06,  4.37it/s]

 12%|█▏        | 744/6015 [02:57<20:08,  4.36it/s]

 12%|█▏        | 745/6015 [02:57<20:08,  4.36it/s]

 12%|█▏        | 746/6015 [02:57<20:08,  4.36it/s]

 12%|█▏        | 747/6015 [02:57<20:08,  4.36it/s]

 12%|█▏        | 748/6015 [02:58<20:05,  4.37it/s]

 12%|█▏        | 749/6015 [02:58<20:06,  4.36it/s]

 12%|█▏        | 750/6015 [02:58<20:07,  4.36it/s]

 12%|█▏        | 751/6015 [02:58<20:05,  4.37it/s]

 13%|█▎        | 752/6015 [02:59<20:06,  4.36it/s]

 13%|█▎        | 753/6015 [02:59<20:07,  4.36it/s]

 13%|█▎        | 754/6015 [02:59<20:06,  4.36it/s]

 13%|█▎        | 755/6015 [02:59<20:05,  4.36it/s]

 13%|█▎        | 756/6015 [03:00<20:09,  4.35it/s]

 13%|█▎        | 757/6015 [03:00<20:08,  4.35it/s]

 13%|█▎        | 758/6015 [03:00<20:07,  4.35it/s]

 13%|█▎        | 759/6015 [03:00<20:06,  4.36it/s]

 13%|█▎        | 760/6015 [03:00<20:05,  4.36it/s]

 13%|█▎        | 761/6015 [03:01<20:07,  4.35it/s]

 13%|█▎        | 762/6015 [03:01<20:05,  4.36it/s]

 13%|█▎        | 763/6015 [03:01<20:04,  4.36it/s]

 13%|█▎        | 764/6015 [03:01<20:04,  4.36it/s]

 13%|█▎        | 765/6015 [03:02<20:08,  4.35it/s]

 13%|█▎        | 766/6015 [03:02<20:07,  4.35it/s]

 13%|█▎        | 767/6015 [03:02<20:04,  4.36it/s]

 13%|█▎        | 768/6015 [03:02<20:03,  4.36it/s]

 13%|█▎        | 769/6015 [03:03<20:04,  4.36it/s]

 13%|█▎        | 770/6015 [03:03<20:02,  4.36it/s]

 13%|█▎        | 771/6015 [03:03<20:02,  4.36it/s]

 13%|█▎        | 772/6015 [03:03<20:02,  4.36it/s]

 13%|█▎        | 773/6015 [03:03<20:01,  4.36it/s]

 13%|█▎        | 774/6015 [03:04<20:00,  4.37it/s]

 13%|█▎        | 775/6015 [03:04<20:06,  4.34it/s]

 13%|█▎        | 776/6015 [03:04<20:03,  4.35it/s]

 13%|█▎        | 777/6015 [03:04<20:02,  4.36it/s]

 13%|█▎        | 778/6015 [03:05<20:02,  4.36it/s]

 13%|█▎        | 779/6015 [03:05<20:02,  4.35it/s]

 13%|█▎        | 780/6015 [03:05<20:02,  4.36it/s]

 13%|█▎        | 781/6015 [03:05<20:00,  4.36it/s]

 13%|█▎        | 782/6015 [03:06<20:00,  4.36it/s]

 13%|█▎        | 783/6015 [03:06<20:02,  4.35it/s]

 13%|█▎        | 784/6015 [03:06<20:01,  4.35it/s]

 13%|█▎        | 785/6015 [03:06<20:00,  4.35it/s]

 13%|█▎        | 786/6015 [03:06<20:06,  4.33it/s]

 13%|█▎        | 787/6015 [03:07<20:03,  4.34it/s]

 13%|█▎        | 788/6015 [03:07<20:04,  4.34it/s]

 13%|█▎        | 789/6015 [03:07<20:01,  4.35it/s]

 13%|█▎        | 790/6015 [03:07<20:03,  4.34it/s]

 13%|█▎        | 791/6015 [03:08<20:06,  4.33it/s]

 13%|█▎        | 792/6015 [03:08<20:07,  4.33it/s]

 13%|█▎        | 793/6015 [03:08<20:06,  4.33it/s]

 13%|█▎        | 794/6015 [03:08<20:10,  4.31it/s]

 13%|█▎        | 795/6015 [03:09<20:06,  4.33it/s]

 13%|█▎        | 796/6015 [03:09<20:04,  4.33it/s]

 13%|█▎        | 797/6015 [03:09<20:01,  4.34it/s]

 13%|█▎        | 798/6015 [03:09<19:59,  4.35it/s]

 13%|█▎        | 799/6015 [03:09<20:00,  4.34it/s]

 13%|█▎        | 800/6015 [03:10<20:00,  4.34it/s]

 13%|█▎        | 801/6015 [03:10<20:00,  4.34it/s]

 13%|█▎        | 802/6015 [03:10<20:03,  4.33it/s]

 13%|█▎        | 803/6015 [03:10<20:00,  4.34it/s]

 13%|█▎        | 804/6015 [03:11<19:58,  4.35it/s]

 13%|█▎        | 805/6015 [03:11<19:58,  4.35it/s]

 13%|█▎        | 806/6015 [03:11<19:56,  4.35it/s]

 13%|█▎        | 807/6015 [03:11<19:57,  4.35it/s]

 13%|█▎        | 808/6015 [03:12<19:59,  4.34it/s]

 13%|█▎        | 809/6015 [03:12<19:59,  4.34it/s]

 13%|█▎        | 810/6015 [03:12<19:59,  4.34it/s]

 13%|█▎        | 811/6015 [03:12<19:57,  4.34it/s]

 13%|█▎        | 812/6015 [03:12<19:57,  4.34it/s]

 14%|█▎        | 813/6015 [03:13<19:58,  4.34it/s]

 14%|█▎        | 814/6015 [03:13<19:55,  4.35it/s]

 14%|█▎        | 815/6015 [03:13<19:54,  4.35it/s]

 14%|█▎        | 816/6015 [03:13<19:55,  4.35it/s]

 14%|█▎        | 817/6015 [03:14<19:57,  4.34it/s]

 14%|█▎        | 818/6015 [03:14<19:58,  4.34it/s]

 14%|█▎        | 819/6015 [03:14<19:58,  4.33it/s]

 14%|█▎        | 820/6015 [03:14<19:57,  4.34it/s]

 14%|█▎        | 821/6015 [03:15<19:56,  4.34it/s]

 14%|█▎        | 822/6015 [03:15<19:53,  4.35it/s]

 14%|█▎        | 823/6015 [03:15<19:53,  4.35it/s]

 14%|█▎        | 824/6015 [03:15<19:55,  4.34it/s]

 14%|█▎        | 825/6015 [03:15<19:54,  4.35it/s]

 14%|█▎        | 826/6015 [03:16<19:55,  4.34it/s]

 14%|█▎        | 827/6015 [03:16<19:55,  4.34it/s]

 14%|█▍        | 828/6015 [03:16<19:53,  4.34it/s]

 14%|█▍        | 829/6015 [03:16<19:53,  4.35it/s]

 14%|█▍        | 830/6015 [03:17<19:53,  4.34it/s]

 14%|█▍        | 831/6015 [03:17<19:51,  4.35it/s]

 14%|█▍        | 832/6015 [03:17<19:52,  4.35it/s]

 14%|█▍        | 833/6015 [03:17<19:52,  4.35it/s]

 14%|█▍        | 834/6015 [03:17<19:48,  4.36it/s]

 14%|█▍        | 835/6015 [03:18<19:50,  4.35it/s]

 14%|█▍        | 836/6015 [03:18<19:52,  4.34it/s]

 14%|█▍        | 837/6015 [03:18<19:51,  4.35it/s]

 14%|█▍        | 838/6015 [03:18<19:54,  4.34it/s]

 14%|█▍        | 839/6015 [03:19<19:51,  4.34it/s]

 14%|█▍        | 840/6015 [03:19<19:52,  4.34it/s]

 14%|█▍        | 841/6015 [03:19<19:52,  4.34it/s]

 14%|█▍        | 842/6015 [03:19<19:50,  4.35it/s]

 14%|█▍        | 843/6015 [03:20<19:50,  4.34it/s]

 14%|█▍        | 844/6015 [03:20<19:51,  4.34it/s]

 14%|█▍        | 845/6015 [03:20<19:51,  4.34it/s]

 14%|█▍        | 846/6015 [03:20<19:49,  4.34it/s]

 14%|█▍        | 847/6015 [03:20<19:49,  4.34it/s]

 14%|█▍        | 848/6015 [03:21<19:49,  4.34it/s]

 14%|█▍        | 849/6015 [03:21<19:48,  4.35it/s]

 14%|█▍        | 850/6015 [03:21<19:48,  4.35it/s]

 14%|█▍        | 851/6015 [03:21<19:50,  4.34it/s]

 14%|█▍        | 852/6015 [03:22<19:51,  4.33it/s]

 14%|█▍        | 853/6015 [03:22<19:49,  4.34it/s]

 14%|█▍        | 854/6015 [03:22<19:48,  4.34it/s]

 14%|█▍        | 855/6015 [03:22<19:49,  4.34it/s]

 14%|█▍        | 856/6015 [03:23<19:47,  4.34it/s]

 14%|█▍        | 857/6015 [03:23<19:47,  4.35it/s]

 14%|█▍        | 858/6015 [03:23<19:46,  4.35it/s]

 14%|█▍        | 859/6015 [03:23<19:45,  4.35it/s]

 14%|█▍        | 860/6015 [03:23<19:46,  4.34it/s]

 14%|█▍        | 861/6015 [03:24<19:44,  4.35it/s]

 14%|█▍        | 862/6015 [03:24<19:45,  4.35it/s]

 14%|█▍        | 863/6015 [03:24<19:44,  4.35it/s]

 14%|█▍        | 864/6015 [03:24<19:47,  4.34it/s]

 14%|█▍        | 865/6015 [03:25<19:47,  4.34it/s]

 14%|█▍        | 866/6015 [03:25<19:45,  4.34it/s]

 14%|█▍        | 867/6015 [03:25<19:44,  4.35it/s]

 14%|█▍        | 868/6015 [03:25<19:45,  4.34it/s]

 14%|█▍        | 869/6015 [03:26<19:43,  4.35it/s]

 14%|█▍        | 870/6015 [03:26<19:45,  4.34it/s]

 14%|█▍        | 871/6015 [03:26<19:48,  4.33it/s]

 14%|█▍        | 872/6015 [03:26<19:46,  4.33it/s]

 15%|█▍        | 873/6015 [03:26<19:46,  4.33it/s]

 15%|█▍        | 874/6015 [03:27<19:44,  4.34it/s]

 15%|█▍        | 875/6015 [03:27<19:44,  4.34it/s]

 15%|█▍        | 876/6015 [03:27<19:45,  4.33it/s]

 15%|█▍        | 877/6015 [03:27<19:44,  4.34it/s]

 15%|█▍        | 878/6015 [03:28<19:44,  4.34it/s]

 15%|█▍        | 879/6015 [03:28<19:45,  4.33it/s]

 15%|█▍        | 880/6015 [03:28<19:44,  4.33it/s]

 15%|█▍        | 881/6015 [03:28<19:44,  4.33it/s]

 15%|█▍        | 882/6015 [03:29<19:42,  4.34it/s]

 15%|█▍        | 883/6015 [03:29<19:45,  4.33it/s]

 15%|█▍        | 884/6015 [03:29<19:45,  4.33it/s]

 15%|█▍        | 885/6015 [03:29<19:42,  4.34it/s]

 15%|█▍        | 886/6015 [03:29<19:42,  4.34it/s]

 15%|█▍        | 887/6015 [03:30<19:43,  4.33it/s]

 15%|█▍        | 888/6015 [03:30<19:41,  4.34it/s]

 15%|█▍        | 889/6015 [03:30<19:40,  4.34it/s]

 15%|█▍        | 890/6015 [03:30<19:38,  4.35it/s]

 15%|█▍        | 891/6015 [03:31<19:36,  4.36it/s]

 15%|█▍        | 892/6015 [03:31<19:39,  4.34it/s]

 15%|█▍        | 893/6015 [03:31<19:38,  4.35it/s]

 15%|█▍        | 894/6015 [03:31<19:39,  4.34it/s]

 15%|█▍        | 895/6015 [03:32<19:45,  4.32it/s]

 15%|█▍        | 896/6015 [03:32<19:45,  4.32it/s]

 15%|█▍        | 897/6015 [03:32<19:46,  4.31it/s]

 15%|█▍        | 898/6015 [03:32<19:46,  4.31it/s]

 15%|█▍        | 899/6015 [03:32<19:44,  4.32it/s]

 15%|█▍        | 900/6015 [03:33<19:41,  4.33it/s]

 15%|█▍        | 901/6015 [03:33<19:39,  4.34it/s]

 15%|█▍        | 902/6015 [03:33<19:39,  4.34it/s]

 15%|█▌        | 903/6015 [03:33<19:37,  4.34it/s]

 15%|█▌        | 904/6015 [03:34<19:38,  4.34it/s]

 15%|█▌        | 905/6015 [03:34<19:38,  4.34it/s]

 15%|█▌        | 906/6015 [03:34<19:35,  4.35it/s]

 15%|█▌        | 907/6015 [03:34<19:36,  4.34it/s]

 15%|█▌        | 908/6015 [03:35<19:38,  4.33it/s]

 15%|█▌        | 909/6015 [03:35<19:37,  4.34it/s]

 15%|█▌        | 910/6015 [03:35<19:35,  4.34it/s]

 15%|█▌        | 911/6015 [03:35<19:40,  4.32it/s]

 15%|█▌        | 912/6015 [03:35<19:37,  4.33it/s]

 15%|█▌        | 913/6015 [03:36<19:36,  4.34it/s]

 15%|█▌        | 914/6015 [03:36<19:34,  4.34it/s]

 15%|█▌        | 915/6015 [03:36<19:36,  4.33it/s]

 15%|█▌        | 916/6015 [03:36<19:37,  4.33it/s]

 15%|█▌        | 917/6015 [03:37<19:37,  4.33it/s]

 15%|█▌        | 918/6015 [03:37<19:38,  4.32it/s]

 15%|█▌        | 919/6015 [03:37<19:38,  4.32it/s]

 15%|█▌        | 920/6015 [03:37<19:35,  4.33it/s]

 15%|█▌        | 921/6015 [03:38<19:37,  4.33it/s]

 15%|█▌        | 922/6015 [03:38<19:36,  4.33it/s]

 15%|█▌        | 923/6015 [03:38<19:36,  4.33it/s]

 15%|█▌        | 924/6015 [03:38<19:37,  4.32it/s]

 15%|█▌        | 925/6015 [03:38<19:35,  4.33it/s]

 15%|█▌        | 926/6015 [03:39<19:34,  4.33it/s]

 15%|█▌        | 927/6015 [03:39<19:43,  4.30it/s]

 15%|█▌        | 928/6015 [03:39<19:39,  4.31it/s]

 15%|█▌        | 929/6015 [03:39<19:37,  4.32it/s]

 15%|█▌        | 930/6015 [03:40<19:33,  4.33it/s]

 15%|█▌        | 931/6015 [03:40<19:31,  4.34it/s]

 15%|█▌        | 932/6015 [03:40<19:30,  4.34it/s]

 16%|█▌        | 933/6015 [03:40<19:27,  4.35it/s]

 16%|█▌        | 934/6015 [03:41<19:29,  4.34it/s]

 16%|█▌        | 935/6015 [03:41<19:29,  4.34it/s]

 16%|█▌        | 936/6015 [03:41<19:31,  4.34it/s]

 16%|█▌        | 937/6015 [03:41<19:33,  4.33it/s]

 16%|█▌        | 938/6015 [03:41<19:30,  4.34it/s]

 16%|█▌        | 939/6015 [03:42<19:28,  4.34it/s]

 16%|█▌        | 940/6015 [03:42<19:26,  4.35it/s]

 16%|█▌        | 941/6015 [03:42<19:24,  4.36it/s]

 16%|█▌        | 942/6015 [03:42<19:24,  4.36it/s]

 16%|█▌        | 943/6015 [03:43<19:25,  4.35it/s]

 16%|█▌        | 944/6015 [03:43<19:27,  4.34it/s]

 16%|█▌        | 945/6015 [03:43<19:27,  4.34it/s]

 16%|█▌        | 946/6015 [03:43<19:25,  4.35it/s]

 16%|█▌        | 947/6015 [03:44<19:26,  4.35it/s]

 16%|█▌        | 948/6015 [03:44<19:28,  4.34it/s]

 16%|█▌        | 949/6015 [03:44<19:28,  4.34it/s]

 16%|█▌        | 950/6015 [03:44<19:29,  4.33it/s]

 16%|█▌        | 951/6015 [03:44<19:31,  4.32it/s]

 16%|█▌        | 952/6015 [03:45<19:27,  4.34it/s]

 16%|█▌        | 953/6015 [03:45<19:27,  4.34it/s]

 16%|█▌        | 954/6015 [03:45<19:26,  4.34it/s]

 16%|█▌        | 955/6015 [03:45<19:26,  4.34it/s]

 16%|█▌        | 956/6015 [03:46<19:28,  4.33it/s]

 16%|█▌        | 957/6015 [03:46<19:27,  4.33it/s]

 16%|█▌        | 958/6015 [03:46<19:26,  4.34it/s]

 16%|█▌        | 959/6015 [03:46<19:26,  4.33it/s]

 16%|█▌        | 960/6015 [03:47<19:24,  4.34it/s]

 16%|█▌        | 961/6015 [03:47<19:24,  4.34it/s]

 16%|█▌        | 962/6015 [03:47<19:24,  4.34it/s]

 16%|█▌        | 963/6015 [03:47<19:25,  4.33it/s]

 16%|█▌        | 964/6015 [03:47<19:24,  4.34it/s]

 16%|█▌        | 965/6015 [03:48<19:23,  4.34it/s]

 16%|█▌        | 966/6015 [03:48<19:22,  4.34it/s]

 16%|█▌        | 967/6015 [03:48<19:22,  4.34it/s]

 16%|█▌        | 968/6015 [03:48<19:22,  4.34it/s]

 16%|█▌        | 969/6015 [03:49<19:25,  4.33it/s]

 16%|█▌        | 970/6015 [03:49<19:25,  4.33it/s]

 16%|█▌        | 971/6015 [03:49<19:25,  4.33it/s]

 16%|█▌        | 972/6015 [03:49<19:24,  4.33it/s]

 16%|█▌        | 973/6015 [03:50<19:21,  4.34it/s]

 16%|█▌        | 974/6015 [03:50<19:20,  4.34it/s]

 16%|█▌        | 975/6015 [03:50<19:22,  4.33it/s]

 16%|█▌        | 976/6015 [03:50<19:21,  4.34it/s]

 16%|█▌        | 977/6015 [03:50<19:22,  4.34it/s]

 16%|█▋        | 978/6015 [03:51<19:23,  4.33it/s]

 16%|█▋        | 979/6015 [03:51<19:27,  4.31it/s]

 16%|█▋        | 980/6015 [03:51<19:29,  4.31it/s]

 16%|█▋        | 981/6015 [03:51<19:26,  4.31it/s]

 16%|█▋        | 982/6015 [03:52<19:29,  4.30it/s]

 16%|█▋        | 983/6015 [03:52<19:30,  4.30it/s]

 16%|█▋        | 984/6015 [03:52<19:28,  4.30it/s]

 16%|█▋        | 985/6015 [03:52<19:28,  4.31it/s]

 16%|█▋        | 986/6015 [03:53<19:23,  4.32it/s]

 16%|█▋        | 987/6015 [03:53<19:23,  4.32it/s]

 16%|█▋        | 988/6015 [03:53<19:23,  4.32it/s]

 16%|█▋        | 989/6015 [03:53<19:22,  4.32it/s]

 16%|█▋        | 990/6015 [03:53<19:20,  4.33it/s]

 16%|█▋        | 991/6015 [03:54<19:20,  4.33it/s]

 16%|█▋        | 992/6015 [03:54<19:19,  4.33it/s]

 17%|█▋        | 993/6015 [03:54<19:20,  4.33it/s]

 17%|█▋        | 994/6015 [03:54<19:18,  4.34it/s]

 17%|█▋        | 995/6015 [03:55<19:19,  4.33it/s]

 17%|█▋        | 996/6015 [03:55<19:20,  4.33it/s]

 17%|█▋        | 997/6015 [03:55<19:20,  4.32it/s]

 17%|█▋        | 998/6015 [03:55<19:22,  4.32it/s]

 17%|█▋        | 999/6015 [03:56<19:19,  4.32it/s]

 17%|█▋        | 1000/6015 [03:56<19:17,  4.33it/s]

 17%|█▋        | 1001/6015 [03:56<19:17,  4.33it/s]

 17%|█▋        | 1002/6015 [03:56<19:16,  4.33it/s]

 17%|█▋        | 1003/6015 [03:56<19:16,  4.33it/s]

 17%|█▋        | 1004/6015 [03:57<19:17,  4.33it/s]

 17%|█▋        | 1005/6015 [03:57<19:15,  4.34it/s]

 17%|█▋        | 1006/6015 [03:57<19:16,  4.33it/s]

 17%|█▋        | 1007/6015 [03:57<19:14,  4.34it/s]

 17%|█▋        | 1008/6015 [03:58<19:17,  4.32it/s]

 17%|█▋        | 1009/6015 [03:58<19:20,  4.32it/s]

 17%|█▋        | 1010/6015 [03:58<19:17,  4.32it/s]

 17%|█▋        | 1011/6015 [03:58<19:18,  4.32it/s]

 17%|█▋        | 1012/6015 [03:59<19:20,  4.31it/s]

 17%|█▋        | 1013/6015 [03:59<19:24,  4.29it/s]

 17%|█▋        | 1014/6015 [03:59<19:24,  4.29it/s]

 17%|█▋        | 1015/6015 [03:59<19:21,  4.31it/s]

 17%|█▋        | 1016/6015 [03:59<19:19,  4.31it/s]

 17%|█▋        | 1017/6015 [04:00<19:18,  4.31it/s]

 17%|█▋        | 1018/6015 [04:00<19:16,  4.32it/s]

 17%|█▋        | 1019/6015 [04:00<19:19,  4.31it/s]

 17%|█▋        | 1020/6015 [04:00<19:16,  4.32it/s]

 17%|█▋        | 1021/6015 [04:01<19:20,  4.30it/s]

 17%|█▋        | 1022/6015 [04:01<19:22,  4.30it/s]

 17%|█▋        | 1023/6015 [04:01<19:18,  4.31it/s]

 17%|█▋        | 1024/6015 [04:01<19:18,  4.31it/s]

 17%|█▋        | 1025/6015 [04:02<19:16,  4.32it/s]

 17%|█▋        | 1026/6015 [04:02<19:17,  4.31it/s]

 17%|█▋        | 1027/6015 [04:02<19:17,  4.31it/s]

 17%|█▋        | 1028/6015 [04:02<19:16,  4.31it/s]

 17%|█▋        | 1029/6015 [04:03<19:15,  4.31it/s]

 17%|█▋        | 1030/6015 [04:03<19:15,  4.31it/s]

 17%|█▋        | 1031/6015 [04:03<19:15,  4.31it/s]

 17%|█▋        | 1032/6015 [04:03<19:16,  4.31it/s]

 17%|█▋        | 1033/6015 [04:03<19:18,  4.30it/s]

 17%|█▋        | 1034/6015 [04:04<19:18,  4.30it/s]

 17%|█▋        | 1035/6015 [04:04<19:17,  4.30it/s]

 17%|█▋        | 1036/6015 [04:04<19:15,  4.31it/s]

 17%|█▋        | 1037/6015 [04:04<19:19,  4.29it/s]

 17%|█▋        | 1038/6015 [04:05<19:29,  4.26it/s]

 17%|█▋        | 1039/6015 [04:05<19:23,  4.28it/s]

 17%|█▋        | 1040/6015 [04:05<19:22,  4.28it/s]

 17%|█▋        | 1041/6015 [04:05<19:19,  4.29it/s]

 17%|█▋        | 1042/6015 [04:06<19:19,  4.29it/s]

 17%|█▋        | 1043/6015 [04:06<19:17,  4.29it/s]

 17%|█▋        | 1044/6015 [04:06<19:14,  4.31it/s]

 17%|█▋        | 1045/6015 [04:06<19:13,  4.31it/s]

 17%|█▋        | 1046/6015 [04:06<19:15,  4.30it/s]

 17%|█▋        | 1047/6015 [04:07<19:14,  4.30it/s]

 17%|█▋        | 1048/6015 [04:07<19:17,  4.29it/s]

 17%|█▋        | 1049/6015 [04:07<19:14,  4.30it/s]

 17%|█▋        | 1050/6015 [04:07<19:14,  4.30it/s]

 17%|█▋        | 1051/6015 [04:08<19:12,  4.31it/s]

 17%|█▋        | 1052/6015 [04:08<19:14,  4.30it/s]

 18%|█▊        | 1053/6015 [04:08<19:14,  4.30it/s]

 18%|█▊        | 1054/6015 [04:08<19:11,  4.31it/s]

 18%|█▊        | 1055/6015 [04:09<19:12,  4.30it/s]

 18%|█▊        | 1056/6015 [04:09<19:12,  4.30it/s]

 18%|█▊        | 1057/6015 [04:09<19:14,  4.29it/s]

 18%|█▊        | 1058/6015 [04:09<19:14,  4.29it/s]

 18%|█▊        | 1059/6015 [04:09<19:10,  4.31it/s]

 18%|█▊        | 1060/6015 [04:10<19:08,  4.31it/s]

 18%|█▊        | 1061/6015 [04:10<19:11,  4.30it/s]

 18%|█▊        | 1062/6015 [04:10<19:09,  4.31it/s]

 18%|█▊        | 1063/6015 [04:10<19:06,  4.32it/s]

 18%|█▊        | 1064/6015 [04:11<19:04,  4.32it/s]

 18%|█▊        | 1065/6015 [04:11<19:07,  4.31it/s]

 18%|█▊        | 1066/6015 [04:11<19:09,  4.31it/s]

 18%|█▊        | 1067/6015 [04:11<19:07,  4.31it/s]

 18%|█▊        | 1068/6015 [04:12<19:07,  4.31it/s]

 18%|█▊        | 1069/6015 [04:12<19:10,  4.30it/s]

 18%|█▊        | 1070/6015 [04:12<19:08,  4.30it/s]

 18%|█▊        | 1071/6015 [04:12<19:10,  4.30it/s]

 18%|█▊        | 1072/6015 [04:13<19:08,  4.30it/s]

 18%|█▊        | 1073/6015 [04:13<19:10,  4.30it/s]

 18%|█▊        | 1074/6015 [04:13<19:10,  4.29it/s]

 18%|█▊        | 1075/6015 [04:13<19:07,  4.30it/s]

 18%|█▊        | 1076/6015 [04:13<19:07,  4.30it/s]

 18%|█▊        | 1077/6015 [04:14<19:06,  4.31it/s]

 18%|█▊        | 1078/6015 [04:14<19:06,  4.31it/s]

 18%|█▊        | 1079/6015 [04:14<19:09,  4.29it/s]

 18%|█▊        | 1080/6015 [04:14<19:07,  4.30it/s]

 18%|█▊        | 1081/6015 [04:15<19:05,  4.31it/s]

 18%|█▊        | 1082/6015 [04:15<19:05,  4.30it/s]

 18%|█▊        | 1083/6015 [04:15<19:02,  4.32it/s]

 18%|█▊        | 1084/6015 [04:15<19:00,  4.32it/s]

 18%|█▊        | 1085/6015 [04:16<19:01,  4.32it/s]

 18%|█▊        | 1086/6015 [04:16<19:00,  4.32it/s]

 18%|█▊        | 1087/6015 [04:16<19:01,  4.32it/s]

 18%|█▊        | 1088/6015 [04:16<19:00,  4.32it/s]

 18%|█▊        | 1089/6015 [04:16<19:01,  4.31it/s]

 18%|█▊        | 1090/6015 [04:17<19:00,  4.32it/s]

 18%|█▊        | 1091/6015 [04:17<18:59,  4.32it/s]

 18%|█▊        | 1092/6015 [04:17<19:01,  4.31it/s]

 18%|█▊        | 1093/6015 [04:17<19:04,  4.30it/s]

 18%|█▊        | 1094/6015 [04:18<19:03,  4.30it/s]

 18%|█▊        | 1095/6015 [04:18<19:04,  4.30it/s]

 18%|█▊        | 1096/6015 [04:18<19:04,  4.30it/s]

 18%|█▊        | 1097/6015 [04:18<19:05,  4.29it/s]

 18%|█▊        | 1098/6015 [04:19<19:07,  4.28it/s]

 18%|█▊        | 1099/6015 [04:19<19:06,  4.29it/s]

 18%|█▊        | 1100/6015 [04:19<19:08,  4.28it/s]

 18%|█▊        | 1101/6015 [04:19<19:07,  4.28it/s]

 18%|█▊        | 1102/6015 [04:19<19:06,  4.28it/s]

 18%|█▊        | 1103/6015 [04:20<19:08,  4.28it/s]

 18%|█▊        | 1104/6015 [04:20<19:05,  4.29it/s]

 18%|█▊        | 1105/6015 [04:20<19:03,  4.29it/s]

 18%|█▊        | 1106/6015 [04:20<19:03,  4.29it/s]

 18%|█▊        | 1107/6015 [04:21<19:02,  4.30it/s]

 18%|█▊        | 1108/6015 [04:21<19:07,  4.27it/s]

 18%|█▊        | 1109/6015 [04:21<19:07,  4.27it/s]

 18%|█▊        | 1110/6015 [04:21<19:09,  4.27it/s]

 18%|█▊        | 1111/6015 [04:22<19:10,  4.26it/s]

 18%|█▊        | 1112/6015 [04:22<19:08,  4.27it/s]

 19%|█▊        | 1113/6015 [04:22<19:06,  4.28it/s]

 19%|█▊        | 1114/6015 [04:22<19:08,  4.27it/s]

 19%|█▊        | 1115/6015 [04:23<19:05,  4.28it/s]

 19%|█▊        | 1116/6015 [04:23<19:03,  4.28it/s]

 19%|█▊        | 1117/6015 [04:23<19:05,  4.28it/s]

 19%|█▊        | 1118/6015 [04:23<19:03,  4.28it/s]

 19%|█▊        | 1119/6015 [04:23<19:02,  4.29it/s]

 19%|█▊        | 1120/6015 [04:24<19:00,  4.29it/s]

 19%|█▊        | 1121/6015 [04:24<18:59,  4.29it/s]

 19%|█▊        | 1122/6015 [04:24<18:59,  4.29it/s]

 19%|█▊        | 1123/6015 [04:24<18:58,  4.30it/s]

 19%|█▊        | 1124/6015 [04:25<18:59,  4.29it/s]

 19%|█▊        | 1125/6015 [04:25<19:00,  4.29it/s]

 19%|█▊        | 1126/6015 [04:25<18:58,  4.30it/s]

 19%|█▊        | 1127/6015 [04:25<19:00,  4.29it/s]

 19%|█▉        | 1128/6015 [04:26<18:59,  4.29it/s]

 19%|█▉        | 1129/6015 [04:26<18:59,  4.29it/s]

 19%|█▉        | 1130/6015 [04:26<19:00,  4.28it/s]

 19%|█▉        | 1131/6015 [04:26<18:59,  4.29it/s]

 19%|█▉        | 1132/6015 [04:26<18:59,  4.29it/s]

 19%|█▉        | 1133/6015 [04:27<19:03,  4.27it/s]

 19%|█▉        | 1134/6015 [04:27<19:02,  4.27it/s]

 19%|█▉        | 1135/6015 [04:27<19:01,  4.27it/s]

 19%|█▉        | 1136/6015 [04:27<18:58,  4.29it/s]

 19%|█▉        | 1137/6015 [04:28<18:59,  4.28it/s]

 19%|█▉        | 1138/6015 [04:28<18:59,  4.28it/s]

 19%|█▉        | 1139/6015 [04:28<18:59,  4.28it/s]

 19%|█▉        | 1140/6015 [04:28<18:59,  4.28it/s]

 19%|█▉        | 1141/6015 [04:29<18:54,  4.30it/s]

 19%|█▉        | 1142/6015 [04:29<18:53,  4.30it/s]

 19%|█▉        | 1143/6015 [04:29<18:54,  4.30it/s]

 19%|█▉        | 1144/6015 [04:29<18:53,  4.30it/s]

 19%|█▉        | 1145/6015 [04:30<18:54,  4.29it/s]

 19%|█▉        | 1146/6015 [04:30<18:53,  4.29it/s]

 19%|█▉        | 1147/6015 [04:30<18:55,  4.29it/s]

 19%|█▉        | 1148/6015 [04:30<18:57,  4.28it/s]

 19%|█▉        | 1149/6015 [04:30<18:55,  4.29it/s]

 19%|█▉        | 1150/6015 [04:31<18:55,  4.29it/s]

 19%|█▉        | 1151/6015 [04:31<18:56,  4.28it/s]

 19%|█▉        | 1152/6015 [04:31<18:56,  4.28it/s]

 19%|█▉        | 1153/6015 [04:31<18:59,  4.27it/s]

 19%|█▉        | 1154/6015 [04:32<18:57,  4.28it/s]

 19%|█▉        | 1155/6015 [04:32<18:59,  4.27it/s]

 19%|█▉        | 1156/6015 [04:32<18:57,  4.27it/s]

 19%|█▉        | 1157/6015 [04:32<18:57,  4.27it/s]

 19%|█▉        | 1158/6015 [04:33<18:58,  4.27it/s]

 19%|█▉        | 1159/6015 [04:33<18:53,  4.28it/s]

 19%|█▉        | 1160/6015 [04:33<18:55,  4.27it/s]

 19%|█▉        | 1161/6015 [04:33<19:02,  4.25it/s]

 19%|█▉        | 1162/6015 [04:34<18:59,  4.26it/s]

 19%|█▉        | 1163/6015 [04:34<18:57,  4.27it/s]

 19%|█▉        | 1164/6015 [04:34<18:57,  4.26it/s]

 19%|█▉        | 1165/6015 [04:34<18:59,  4.26it/s]

 19%|█▉        | 1166/6015 [04:34<18:58,  4.26it/s]

 19%|█▉        | 1167/6015 [04:35<19:03,  4.24it/s]

 19%|█▉        | 1168/6015 [04:35<19:04,  4.23it/s]

 19%|█▉        | 1169/6015 [04:35<19:01,  4.25it/s]

 19%|█▉        | 1170/6015 [04:35<18:57,  4.26it/s]

 19%|█▉        | 1171/6015 [04:36<18:57,  4.26it/s]

 19%|█▉        | 1172/6015 [04:36<18:56,  4.26it/s]

 20%|█▉        | 1173/6015 [04:36<18:59,  4.25it/s]

 20%|█▉        | 1174/6015 [04:36<18:56,  4.26it/s]

 20%|█▉        | 1175/6015 [04:37<18:56,  4.26it/s]

 20%|█▉        | 1176/6015 [04:37<18:52,  4.27it/s]

 20%|█▉        | 1177/6015 [04:37<18:53,  4.27it/s]

 20%|█▉        | 1178/6015 [04:37<18:55,  4.26it/s]

 20%|█▉        | 1179/6015 [04:37<18:53,  4.27it/s]

 20%|█▉        | 1180/6015 [04:38<18:54,  4.26it/s]

 20%|█▉        | 1181/6015 [04:38<18:55,  4.26it/s]

 20%|█▉        | 1182/6015 [04:38<18:54,  4.26it/s]

 20%|█▉        | 1183/6015 [04:38<18:56,  4.25it/s]

 20%|█▉        | 1184/6015 [04:39<18:52,  4.26it/s]

 20%|█▉        | 1185/6015 [04:39<18:54,  4.26it/s]

 20%|█▉        | 1186/6015 [04:39<18:54,  4.26it/s]

 20%|█▉        | 1187/6015 [04:39<18:54,  4.26it/s]

 20%|█▉        | 1188/6015 [04:40<18:56,  4.25it/s]

 20%|█▉        | 1189/6015 [04:40<18:53,  4.26it/s]

 20%|█▉        | 1190/6015 [04:40<18:52,  4.26it/s]

 20%|█▉        | 1191/6015 [04:40<18:49,  4.27it/s]

 20%|█▉        | 1192/6015 [04:41<18:48,  4.28it/s]

 20%|█▉        | 1193/6015 [04:41<18:53,  4.26it/s]

 20%|█▉        | 1194/6015 [04:41<18:51,  4.26it/s]

 20%|█▉        | 1195/6015 [04:41<18:50,  4.26it/s]

 20%|█▉        | 1196/6015 [04:41<18:53,  4.25it/s]

 20%|█▉        | 1197/6015 [04:42<18:56,  4.24it/s]

 20%|█▉        | 1198/6015 [04:42<18:52,  4.25it/s]

 20%|█▉        | 1199/6015 [04:42<18:49,  4.26it/s]

 20%|█▉        | 1200/6015 [04:42<18:52,  4.25it/s]

 20%|█▉        | 1201/6015 [04:43<18:50,  4.26it/s]

 20%|█▉        | 1202/6015 [04:43<18:50,  4.26it/s]

 20%|██        | 1203/6015 [04:43<18:50,  4.26it/s]

 20%|██        | 1204/6015 [04:43<18:49,  4.26it/s]

 20%|██        | 1205/6015 [04:44<18:51,  4.25it/s]

 20%|██        | 1206/6015 [04:44<18:50,  4.25it/s]

 20%|██        | 1207/6015 [04:44<18:50,  4.25it/s]

 20%|██        | 1208/6015 [04:44<18:51,  4.25it/s]

 20%|██        | 1209/6015 [04:45<18:47,  4.26it/s]

 20%|██        | 1210/6015 [04:45<18:46,  4.27it/s]

 20%|██        | 1211/6015 [04:45<18:46,  4.26it/s]

 20%|██        | 1212/6015 [04:45<18:46,  4.26it/s]

 20%|██        | 1213/6015 [04:45<18:46,  4.26it/s]

 20%|██        | 1214/6015 [04:46<18:47,  4.26it/s]

 20%|██        | 1215/6015 [04:46<18:46,  4.26it/s]

 20%|██        | 1216/6015 [04:46<18:46,  4.26it/s]

 20%|██        | 1217/6015 [04:46<18:45,  4.26it/s]

 20%|██        | 1218/6015 [04:47<18:46,  4.26it/s]

 20%|██        | 1219/6015 [04:47<18:44,  4.27it/s]

 20%|██        | 1220/6015 [04:47<18:44,  4.26it/s]

 20%|██        | 1221/6015 [04:47<18:45,  4.26it/s]

 20%|██        | 1222/6015 [04:48<18:45,  4.26it/s]

 20%|██        | 1223/6015 [04:48<18:44,  4.26it/s]

 20%|██        | 1224/6015 [04:48<18:42,  4.27it/s]

 20%|██        | 1225/6015 [04:48<18:42,  4.27it/s]

 20%|██        | 1226/6015 [04:49<18:43,  4.26it/s]

 20%|██        | 1227/6015 [04:49<18:43,  4.26it/s]

 20%|██        | 1228/6015 [04:49<18:43,  4.26it/s]

 20%|██        | 1229/6015 [04:49<18:43,  4.26it/s]

 20%|██        | 1230/6015 [04:49<18:42,  4.26it/s]

 20%|██        | 1231/6015 [04:50<18:46,  4.25it/s]

 20%|██        | 1232/6015 [04:50<18:46,  4.24it/s]

 20%|██        | 1233/6015 [04:50<18:46,  4.24it/s]

 21%|██        | 1234/6015 [04:50<18:44,  4.25it/s]

 21%|██        | 1235/6015 [04:51<18:45,  4.25it/s]

 21%|██        | 1236/6015 [04:51<18:45,  4.25it/s]

 21%|██        | 1237/6015 [04:51<18:46,  4.24it/s]

 21%|██        | 1238/6015 [04:51<18:48,  4.23it/s]

 21%|██        | 1239/6015 [04:52<18:44,  4.25it/s]

 21%|██        | 1240/6015 [04:52<18:44,  4.25it/s]

 21%|██        | 1241/6015 [04:52<18:45,  4.24it/s]

 21%|██        | 1242/6015 [04:52<18:44,  4.25it/s]

 21%|██        | 1243/6015 [04:53<18:44,  4.24it/s]

 21%|██        | 1244/6015 [04:53<18:41,  4.25it/s]

 21%|██        | 1245/6015 [04:53<18:41,  4.25it/s]

 21%|██        | 1246/6015 [04:53<18:42,  4.25it/s]

 21%|██        | 1247/6015 [04:53<18:42,  4.25it/s]

 21%|██        | 1248/6015 [04:54<18:45,  4.24it/s]

 21%|██        | 1249/6015 [04:54<18:42,  4.25it/s]

 21%|██        | 1250/6015 [04:54<18:41,  4.25it/s]

 21%|██        | 1251/6015 [04:54<18:40,  4.25it/s]

logging
logging the anndata

 21%|██        | 1252/6015 [07:17<56:39:03, 42.82s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 21%|██        | 1253/6015 [07:17<39:45:01, 30.05s/it]

 21%|██        | 1254/6015 [07:17<27:54:38, 21.10s/it]

 21%|██        | 1255/6015 [07:17<19:37:21, 14.84s/it]

 21%|██        | 1256/6015 [07:18<13:49:20, 10.46s/it]

 21%|██        | 1257/6015 [07:18<9:45:47,  7.39s/it]

 21%|██        | 1258/6015 [07:18<6:55:20,  5.24s/it]

 21%|██        | 1259/6015 [07:18<4:56:03,  3.73s/it]

 21%|██        | 1260/6015 [07:18<3:32:34,  2.68s/it]

 21%|██        | 1261/6015 [07:19<2:34:06,  1.94s/it]

 21%|██        | 1262/6015 [07:19<1:53:13,  1.43s/it]

 21%|██        | 1263/6015 [07:19<1:24:36,  1.07s/it]

 21%|██        | 1264/6015 [07:19<1:04:33,  1.23it/s]

 21%|██        | 1265/6015 [07:20<50:32,  1.57it/s]

 21%|██        | 1266/6015 [07:20<40:44,  1.94it/s]

 21%|██        | 1267/6015 [07:20<33:51,  2.34it/s]

 21%|██        | 1268/6015 [07:20<29:00,  2.73it/s]

 21%|██        | 1269/6015 [07:20<25:38,  3.08it/s]

 21%|██        | 1270/6015 [07:21<23:19,  3.39it/s]

 21%|██        | 1271/6015 [07:21<21:42,  3.64it/s]

 21%|██        | 1272/6015 [07:21<20:33,  3.85it/s]

 21%|██        | 1273/6015 [07:21<19:45,  4.00it/s]

 21%|██        | 1274/6015 [07:22<19:11,  4.12it/s]

 21%|██        | 1275/6015 [07:22<18:48,  4.20it/s]

 21%|██        | 1276/6015 [07:22<18:29,  4.27it/s]

 21%|██        | 1277/6015 [07:22<18:19,  4.31it/s]

 21%|██        | 1278/6015 [07:23<18:11,  4.34it/s]

 21%|██▏       | 1279/6015 [07:23<18:05,  4.36it/s]

 21%|██▏       | 1280/6015 [07:23<18:01,  4.38it/s]

 21%|██▏       | 1281/6015 [07:23<17:58,  4.39it/s]

 21%|██▏       | 1282/6015 [07:23<17:57,  4.39it/s]

 21%|██▏       | 1283/6015 [07:24<17:58,  4.39it/s]

 21%|██▏       | 1284/6015 [07:24<17:56,  4.40it/s]

 21%|██▏       | 1285/6015 [07:24<17:54,  4.40it/s]

 21%|██▏       | 1286/6015 [07:24<17:54,  4.40it/s]

 21%|██▏       | 1287/6015 [07:25<17:51,  4.41it/s]

 21%|██▏       | 1288/6015 [07:25<17:51,  4.41it/s]

 21%|██▏       | 1289/6015 [07:25<17:51,  4.41it/s]

 21%|██▏       | 1290/6015 [07:25<17:49,  4.42it/s]

 21%|██▏       | 1291/6015 [07:25<17:47,  4.43it/s]

 21%|██▏       | 1292/6015 [07:26<17:50,  4.41it/s]

 21%|██▏       | 1293/6015 [07:26<17:48,  4.42it/s]

 22%|██▏       | 1294/6015 [07:26<17:48,  4.42it/s]

 22%|██▏       | 1295/6015 [07:26<17:48,  4.42it/s]

 22%|██▏       | 1296/6015 [07:27<17:54,  4.39it/s]

 22%|██▏       | 1297/6015 [07:27<17:53,  4.40it/s]

 22%|██▏       | 1298/6015 [07:27<17:55,  4.39it/s]

 22%|██▏       | 1299/6015 [07:27<17:53,  4.39it/s]

 22%|██▏       | 1300/6015 [07:27<17:52,  4.39it/s]

 22%|██▏       | 1301/6015 [07:28<17:50,  4.40it/s]

 22%|██▏       | 1302/6015 [07:28<17:48,  4.41it/s]

 22%|██▏       | 1303/6015 [07:28<17:47,  4.41it/s]

 22%|██▏       | 1304/6015 [07:28<17:46,  4.42it/s]

 22%|██▏       | 1305/6015 [07:29<17:46,  4.42it/s]

 22%|██▏       | 1306/6015 [07:29<17:49,  4.40it/s]

 22%|██▏       | 1307/6015 [07:29<17:48,  4.41it/s]

 22%|██▏       | 1308/6015 [07:29<17:47,  4.41it/s]

 22%|██▏       | 1309/6015 [07:30<17:48,  4.40it/s]

 22%|██▏       | 1310/6015 [07:30<17:45,  4.42it/s]

 22%|██▏       | 1311/6015 [07:30<17:44,  4.42it/s]

 22%|██▏       | 1312/6015 [07:30<17:47,  4.41it/s]

 22%|██▏       | 1313/6015 [07:30<17:44,  4.42it/s]

 22%|██▏       | 1314/6015 [07:31<17:45,  4.41it/s]

 22%|██▏       | 1315/6015 [07:31<17:44,  4.41it/s]

 22%|██▏       | 1316/6015 [07:31<17:45,  4.41it/s]

 22%|██▏       | 1317/6015 [07:31<17:46,  4.41it/s]

 22%|██▏       | 1318/6015 [07:32<17:45,  4.41it/s]

 22%|██▏       | 1319/6015 [07:32<17:45,  4.41it/s]

 22%|██▏       | 1320/6015 [07:32<17:47,  4.40it/s]

 22%|██▏       | 1321/6015 [07:32<17:46,  4.40it/s]

 22%|██▏       | 1322/6015 [07:32<17:46,  4.40it/s]

 22%|██▏       | 1323/6015 [07:33<17:48,  4.39it/s]

 22%|██▏       | 1324/6015 [07:33<17:46,  4.40it/s]

 22%|██▏       | 1325/6015 [07:33<17:44,  4.40it/s]

 22%|██▏       | 1326/6015 [07:33<17:45,  4.40it/s]

 22%|██▏       | 1327/6015 [07:34<17:43,  4.41it/s]

 22%|██▏       | 1328/6015 [07:34<17:41,  4.41it/s]

 22%|██▏       | 1329/6015 [07:34<17:41,  4.41it/s]

 22%|██▏       | 1330/6015 [07:34<17:41,  4.41it/s]

 22%|██▏       | 1331/6015 [07:35<17:41,  4.41it/s]

 22%|██▏       | 1332/6015 [07:35<17:43,  4.40it/s]

 22%|██▏       | 1333/6015 [07:35<17:45,  4.40it/s]

 22%|██▏       | 1334/6015 [07:35<17:47,  4.39it/s]

 22%|██▏       | 1335/6015 [07:35<17:46,  4.39it/s]

 22%|██▏       | 1336/6015 [07:36<17:46,  4.39it/s]

 22%|██▏       | 1337/6015 [07:36<17:46,  4.39it/s]

 22%|██▏       | 1338/6015 [07:36<17:43,  4.40it/s]

 22%|██▏       | 1339/6015 [07:36<17:42,  4.40it/s]

 22%|██▏       | 1340/6015 [07:37<17:43,  4.40it/s]

 22%|██▏       | 1341/6015 [07:37<17:44,  4.39it/s]

 22%|██▏       | 1342/6015 [07:37<17:43,  4.39it/s]

 22%|██▏       | 1343/6015 [07:37<17:43,  4.39it/s]

 22%|██▏       | 1344/6015 [07:37<17:40,  4.40it/s]

 22%|██▏       | 1345/6015 [07:38<17:40,  4.40it/s]

 22%|██▏       | 1346/6015 [07:38<17:43,  4.39it/s]

 22%|██▏       | 1347/6015 [07:38<17:41,  4.40it/s]

 22%|██▏       | 1348/6015 [07:38<17:42,  4.39it/s]

 22%|██▏       | 1349/6015 [07:39<17:45,  4.38it/s]

 22%|██▏       | 1350/6015 [07:39<17:43,  4.39it/s]

 22%|██▏       | 1351/6015 [07:39<17:42,  4.39it/s]

 22%|██▏       | 1352/6015 [07:39<17:41,  4.39it/s]

 22%|██▏       | 1353/6015 [07:40<17:39,  4.40it/s]

 23%|██▎       | 1354/6015 [07:40<17:38,  4.40it/s]

 23%|██▎       | 1355/6015 [07:40<17:40,  4.40it/s]

 23%|██▎       | 1356/6015 [07:40<17:42,  4.39it/s]

 23%|██▎       | 1357/6015 [07:40<17:43,  4.38it/s]

 23%|██▎       | 1358/6015 [07:41<17:41,  4.39it/s]

 23%|██▎       | 1359/6015 [07:41<17:40,  4.39it/s]

 23%|██▎       | 1360/6015 [07:41<17:38,  4.40it/s]

 23%|██▎       | 1361/6015 [07:41<17:38,  4.40it/s]

 23%|██▎       | 1362/6015 [07:42<17:42,  4.38it/s]

 23%|██▎       | 1363/6015 [07:42<17:41,  4.38it/s]

 23%|██▎       | 1364/6015 [07:42<17:41,  4.38it/s]

 23%|██▎       | 1365/6015 [07:42<17:41,  4.38it/s]

 23%|██▎       | 1366/6015 [07:43<17:43,  4.37it/s]

 23%|██▎       | 1367/6015 [07:43<17:40,  4.38it/s]

 23%|██▎       | 1368/6015 [07:43<17:40,  4.38it/s]

 23%|██▎       | 1369/6015 [07:43<17:42,  4.37it/s]

 23%|██▎       | 1370/6015 [07:43<17:39,  4.38it/s]

 23%|██▎       | 1371/6015 [07:44<17:39,  4.38it/s]

 23%|██▎       | 1372/6015 [07:44<17:41,  4.37it/s]

 23%|██▎       | 1373/6015 [07:44<17:40,  4.38it/s]

 23%|██▎       | 1374/6015 [07:44<17:39,  4.38it/s]

 23%|██▎       | 1375/6015 [07:45<17:40,  4.38it/s]

 23%|██▎       | 1376/6015 [07:45<17:38,  4.38it/s]

 23%|██▎       | 1377/6015 [07:45<17:37,  4.39it/s]

 23%|██▎       | 1378/6015 [07:45<17:37,  4.39it/s]

 23%|██▎       | 1379/6015 [07:45<17:34,  4.40it/s]

 23%|██▎       | 1380/6015 [07:46<17:34,  4.40it/s]

 23%|██▎       | 1381/6015 [07:46<17:34,  4.40it/s]

 23%|██▎       | 1382/6015 [07:46<17:33,  4.40it/s]

 23%|██▎       | 1383/6015 [07:46<17:33,  4.40it/s]

 23%|██▎       | 1384/6015 [07:47<17:35,  4.39it/s]

 23%|██▎       | 1385/6015 [07:47<17:34,  4.39it/s]

 23%|██▎       | 1386/6015 [07:47<17:35,  4.38it/s]

 23%|██▎       | 1387/6015 [07:47<17:37,  4.38it/s]

 23%|██▎       | 1388/6015 [07:48<17:36,  4.38it/s]

 23%|██▎       | 1389/6015 [07:48<17:36,  4.38it/s]

 23%|██▎       | 1390/6015 [07:48<17:34,  4.38it/s]

 23%|██▎       | 1391/6015 [07:48<17:35,  4.38it/s]

 23%|██▎       | 1392/6015 [07:48<17:37,  4.37it/s]

 23%|██▎       | 1393/6015 [07:49<17:36,  4.38it/s]

 23%|██▎       | 1394/6015 [07:49<17:33,  4.38it/s]

 23%|██▎       | 1395/6015 [07:49<17:33,  4.39it/s]

 23%|██▎       | 1396/6015 [07:49<17:32,  4.39it/s]

 23%|██▎       | 1397/6015 [07:50<17:36,  4.37it/s]

 23%|██▎       | 1398/6015 [07:50<17:35,  4.37it/s]

 23%|██▎       | 1399/6015 [07:50<17:34,  4.38it/s]

 23%|██▎       | 1400/6015 [07:50<17:36,  4.37it/s]

 23%|██▎       | 1401/6015 [07:50<17:34,  4.37it/s]

 23%|██▎       | 1402/6015 [07:51<17:32,  4.38it/s]

 23%|██▎       | 1403/6015 [07:51<17:32,  4.38it/s]

 23%|██▎       | 1404/6015 [07:51<17:33,  4.38it/s]

 23%|██▎       | 1405/6015 [07:51<17:31,  4.38it/s]

 23%|██▎       | 1406/6015 [07:52<17:31,  4.38it/s]

 23%|██▎       | 1407/6015 [07:52<17:32,  4.38it/s]

 23%|██▎       | 1408/6015 [07:52<17:32,  4.38it/s]

 23%|██▎       | 1409/6015 [07:52<17:32,  4.38it/s]

 23%|██▎       | 1410/6015 [07:53<17:32,  4.38it/s]

 23%|██▎       | 1411/6015 [07:53<17:31,  4.38it/s]

 23%|██▎       | 1412/6015 [07:53<17:29,  4.39it/s]

 23%|██▎       | 1413/6015 [07:53<17:29,  4.39it/s]

 24%|██▎       | 1414/6015 [07:53<17:30,  4.38it/s]

 24%|██▎       | 1415/6015 [07:54<17:30,  4.38it/s]

 24%|██▎       | 1416/6015 [07:54<17:29,  4.38it/s]

 24%|██▎       | 1417/6015 [07:54<17:32,  4.37it/s]

 24%|██▎       | 1418/6015 [07:54<17:30,  4.38it/s]

 24%|██▎       | 1419/6015 [07:55<17:30,  4.38it/s]

 24%|██▎       | 1420/6015 [07:55<17:30,  4.37it/s]

 24%|██▎       | 1421/6015 [07:55<17:30,  4.37it/s]

 24%|██▎       | 1422/6015 [07:55<17:34,  4.35it/s]

 24%|██▎       | 1423/6015 [07:56<17:33,  4.36it/s]

 24%|██▎       | 1424/6015 [07:56<17:34,  4.35it/s]

 24%|██▎       | 1425/6015 [07:56<17:32,  4.36it/s]

 24%|██▎       | 1426/6015 [07:56<17:31,  4.37it/s]

 24%|██▎       | 1427/6015 [07:56<17:30,  4.37it/s]

 24%|██▎       | 1428/6015 [07:57<17:31,  4.36it/s]

 24%|██▍       | 1429/6015 [07:57<17:30,  4.36it/s]

 24%|██▍       | 1430/6015 [07:57<17:31,  4.36it/s]

 24%|██▍       | 1431/6015 [07:57<17:30,  4.36it/s]

 24%|██▍       | 1432/6015 [07:58<17:29,  4.37it/s]

 24%|██▍       | 1433/6015 [07:58<17:29,  4.36it/s]

 24%|██▍       | 1434/6015 [07:58<17:26,  4.38it/s]

 24%|██▍       | 1435/6015 [07:58<17:28,  4.37it/s]

 24%|██▍       | 1436/6015 [07:58<17:29,  4.36it/s]

 24%|██▍       | 1437/6015 [07:59<17:30,  4.36it/s]

 24%|██▍       | 1438/6015 [07:59<17:31,  4.35it/s]

 24%|██▍       | 1439/6015 [07:59<17:31,  4.35it/s]

 24%|██▍       | 1440/6015 [07:59<17:28,  4.36it/s]

 24%|██▍       | 1441/6015 [08:00<17:26,  4.37it/s]

 24%|██▍       | 1442/6015 [08:00<17:23,  4.38it/s]

 24%|██▍       | 1443/6015 [08:00<17:24,  4.38it/s]

 24%|██▍       | 1444/6015 [08:00<17:25,  4.37it/s]

 24%|██▍       | 1445/6015 [08:01<17:25,  4.37it/s]

 24%|██▍       | 1446/6015 [08:01<17:26,  4.37it/s]

 24%|██▍       | 1447/6015 [08:01<17:27,  4.36it/s]

 24%|██▍       | 1448/6015 [08:01<17:24,  4.37it/s]

 24%|██▍       | 1449/6015 [08:01<17:24,  4.37it/s]

 24%|██▍       | 1450/6015 [08:02<17:24,  4.37it/s]

 24%|██▍       | 1451/6015 [08:02<17:23,  4.37it/s]

 24%|██▍       | 1452/6015 [08:02<17:24,  4.37it/s]

 24%|██▍       | 1453/6015 [08:02<17:25,  4.36it/s]

 24%|██▍       | 1454/6015 [08:03<17:26,  4.36it/s]

 24%|██▍       | 1455/6015 [08:03<17:25,  4.36it/s]

 24%|██▍       | 1456/6015 [08:03<17:24,  4.36it/s]

 24%|██▍       | 1457/6015 [08:03<17:25,  4.36it/s]

 24%|██▍       | 1458/6015 [08:04<17:23,  4.37it/s]

 24%|██▍       | 1459/6015 [08:04<17:22,  4.37it/s]

 24%|██▍       | 1460/6015 [08:04<17:22,  4.37it/s]

 24%|██▍       | 1461/6015 [08:04<17:23,  4.36it/s]

 24%|██▍       | 1462/6015 [08:04<17:24,  4.36it/s]

 24%|██▍       | 1463/6015 [08:05<17:25,  4.36it/s]

 24%|██▍       | 1464/6015 [08:05<17:24,  4.36it/s]

 24%|██▍       | 1465/6015 [08:05<17:24,  4.36it/s]

 24%|██▍       | 1466/6015 [08:05<17:24,  4.35it/s]

 24%|██▍       | 1467/6015 [08:06<17:28,  4.34it/s]

 24%|██▍       | 1468/6015 [08:06<17:25,  4.35it/s]

 24%|██▍       | 1469/6015 [08:06<17:24,  4.35it/s]

 24%|██▍       | 1470/6015 [08:06<17:23,  4.35it/s]

 24%|██▍       | 1471/6015 [08:07<17:22,  4.36it/s]

 24%|██▍       | 1472/6015 [08:07<17:22,  4.36it/s]

 24%|██▍       | 1473/6015 [08:07<17:21,  4.36it/s]

 25%|██▍       | 1474/6015 [08:07<17:20,  4.36it/s]

 25%|██▍       | 1475/6015 [08:07<17:18,  4.37it/s]

 25%|██▍       | 1476/6015 [08:08<17:18,  4.37it/s]

 25%|██▍       | 1477/6015 [08:08<17:19,  4.36it/s]

 25%|██▍       | 1478/6015 [08:08<17:19,  4.36it/s]

 25%|██▍       | 1479/6015 [08:08<17:19,  4.36it/s]

 25%|██▍       | 1480/6015 [08:09<17:20,  4.36it/s]

 25%|██▍       | 1481/6015 [08:09<17:19,  4.36it/s]

 25%|██▍       | 1482/6015 [08:09<17:18,  4.37it/s]

 25%|██▍       | 1483/6015 [08:09<17:19,  4.36it/s]

 25%|██▍       | 1484/6015 [08:09<17:18,  4.36it/s]

 25%|██▍       | 1485/6015 [08:10<17:19,  4.36it/s]

 25%|██▍       | 1486/6015 [08:10<17:18,  4.36it/s]

 25%|██▍       | 1487/6015 [08:10<17:19,  4.36it/s]

 25%|██▍       | 1488/6015 [08:10<17:18,  4.36it/s]

 25%|██▍       | 1489/6015 [08:11<17:17,  4.36it/s]

 25%|██▍       | 1490/6015 [08:11<17:21,  4.34it/s]

 25%|██▍       | 1491/6015 [08:11<17:20,  4.35it/s]

 25%|██▍       | 1492/6015 [08:11<17:19,  4.35it/s]

 25%|██▍       | 1493/6015 [08:12<17:20,  4.35it/s]

 25%|██▍       | 1494/6015 [08:12<17:17,  4.36it/s]

 25%|██▍       | 1495/6015 [08:12<17:17,  4.36it/s]

 25%|██▍       | 1496/6015 [08:12<17:17,  4.35it/s]

 25%|██▍       | 1497/6015 [08:12<17:15,  4.36it/s]

 25%|██▍       | 1498/6015 [08:13<17:15,  4.36it/s]

 25%|██▍       | 1499/6015 [08:13<17:15,  4.36it/s]

 25%|██▍       | 1500/6015 [08:13<17:13,  4.37it/s]

 25%|██▍       | 1501/6015 [08:13<17:15,  4.36it/s]

 25%|██▍       | 1502/6015 [08:14<17:15,  4.36it/s]

 25%|██▍       | 1503/6015 [08:14<17:16,  4.35it/s]

 25%|██▌       | 1504/6015 [08:14<17:16,  4.35it/s]

 25%|██▌       | 1505/6015 [08:14<17:13,  4.36it/s]

 25%|██▌       | 1506/6015 [08:15<17:14,  4.36it/s]

 25%|██▌       | 1507/6015 [08:15<17:16,  4.35it/s]

 25%|██▌       | 1508/6015 [08:15<17:13,  4.36it/s]

 25%|██▌       | 1509/6015 [08:15<17:11,  4.37it/s]

 25%|██▌       | 1510/6015 [08:15<17:12,  4.37it/s]

 25%|██▌       | 1511/6015 [08:16<17:10,  4.37it/s]

 25%|██▌       | 1512/6015 [08:16<17:13,  4.36it/s]

 25%|██▌       | 1513/6015 [08:16<17:10,  4.37it/s]

 25%|██▌       | 1514/6015 [08:16<17:10,  4.37it/s]

 25%|██▌       | 1515/6015 [08:17<17:11,  4.36it/s]

 25%|██▌       | 1516/6015 [08:17<17:10,  4.36it/s]

 25%|██▌       | 1517/6015 [08:17<17:11,  4.36it/s]

 25%|██▌       | 1518/6015 [08:17<17:11,  4.36it/s]

 25%|██▌       | 1519/6015 [08:18<17:10,  4.36it/s]

 25%|██▌       | 1520/6015 [08:18<17:12,  4.35it/s]

 25%|██▌       | 1521/6015 [08:18<17:17,  4.33it/s]

 25%|██▌       | 1522/6015 [08:18<17:16,  4.34it/s]

 25%|██▌       | 1523/6015 [08:18<17:15,  4.34it/s]

 25%|██▌       | 1524/6015 [08:19<17:11,  4.35it/s]

 25%|██▌       | 1525/6015 [08:19<17:12,  4.35it/s]

 25%|██▌       | 1526/6015 [08:19<17:11,  4.35it/s]

 25%|██▌       | 1527/6015 [08:19<17:09,  4.36it/s]

 25%|██▌       | 1528/6015 [08:20<17:08,  4.36it/s]

 25%|██▌       | 1529/6015 [08:20<17:10,  4.36it/s]

 25%|██▌       | 1530/6015 [08:20<17:09,  4.35it/s]

 25%|██▌       | 1531/6015 [08:20<17:08,  4.36it/s]

 25%|██▌       | 1532/6015 [08:21<17:07,  4.36it/s]

 25%|██▌       | 1533/6015 [08:21<17:07,  4.36it/s]

 26%|██▌       | 1534/6015 [08:21<17:07,  4.36it/s]

 26%|██▌       | 1535/6015 [08:21<17:06,  4.36it/s]

 26%|██▌       | 1536/6015 [08:21<17:08,  4.36it/s]

 26%|██▌       | 1537/6015 [08:22<17:08,  4.36it/s]

 26%|██▌       | 1538/6015 [08:22<17:06,  4.36it/s]

 26%|██▌       | 1539/6015 [08:22<17:06,  4.36it/s]

 26%|██▌       | 1540/6015 [08:22<17:10,  4.34it/s]

 26%|██▌       | 1541/6015 [08:23<17:10,  4.34it/s]

 26%|██▌       | 1542/6015 [08:23<17:10,  4.34it/s]

 26%|██▌       | 1543/6015 [08:23<17:08,  4.35it/s]

 26%|██▌       | 1544/6015 [08:23<17:07,  4.35it/s]

 26%|██▌       | 1545/6015 [08:24<17:06,  4.35it/s]

 26%|██▌       | 1546/6015 [08:24<17:05,  4.36it/s]

 26%|██▌       | 1547/6015 [08:24<17:05,  4.36it/s]

 26%|██▌       | 1548/6015 [08:24<17:07,  4.35it/s]

 26%|██▌       | 1549/6015 [08:24<17:04,  4.36it/s]

 26%|██▌       | 1550/6015 [08:25<17:04,  4.36it/s]

 26%|██▌       | 1551/6015 [08:25<17:04,  4.36it/s]

 26%|██▌       | 1552/6015 [08:25<17:05,  4.35it/s]

 26%|██▌       | 1553/6015 [08:25<17:06,  4.35it/s]

 26%|██▌       | 1554/6015 [08:26<17:03,  4.36it/s]

 26%|██▌       | 1555/6015 [08:26<17:03,  4.36it/s]

 26%|██▌       | 1556/6015 [08:26<17:03,  4.35it/s]

 26%|██▌       | 1557/6015 [08:26<17:01,  4.37it/s]

 26%|██▌       | 1558/6015 [08:26<17:02,  4.36it/s]

 26%|██▌       | 1559/6015 [08:27<17:01,  4.36it/s]

 26%|██▌       | 1560/6015 [08:27<17:00,  4.36it/s]

 26%|██▌       | 1561/6015 [08:27<17:00,  4.36it/s]

 26%|██▌       | 1562/6015 [08:27<16:59,  4.37it/s]

 26%|██▌       | 1563/6015 [08:28<16:57,  4.37it/s]

 26%|██▌       | 1564/6015 [08:28<17:00,  4.36it/s]

 26%|██▌       | 1565/6015 [08:28<16:57,  4.37it/s]

 26%|██▌       | 1566/6015 [08:28<16:57,  4.37it/s]

 26%|██▌       | 1567/6015 [08:29<17:00,  4.36it/s]

 26%|██▌       | 1568/6015 [08:29<16:58,  4.37it/s]

 26%|██▌       | 1569/6015 [08:29<16:57,  4.37it/s]

 26%|██▌       | 1570/6015 [08:29<16:57,  4.37it/s]

 26%|██▌       | 1571/6015 [08:29<16:58,  4.36it/s]

 26%|██▌       | 1572/6015 [08:30<16:57,  4.36it/s]

 26%|██▌       | 1573/6015 [08:30<16:56,  4.37it/s]

 26%|██▌       | 1574/6015 [08:30<16:56,  4.37it/s]

 26%|██▌       | 1575/6015 [08:30<16:56,  4.37it/s]

 26%|██▌       | 1576/6015 [08:31<16:55,  4.37it/s]

 26%|██▌       | 1577/6015 [08:31<16:59,  4.35it/s]

 26%|██▌       | 1578/6015 [08:31<16:57,  4.36it/s]

 26%|██▋       | 1579/6015 [08:31<16:58,  4.36it/s]

 26%|██▋       | 1580/6015 [08:32<16:59,  4.35it/s]

 26%|██▋       | 1581/6015 [08:32<16:58,  4.35it/s]

 26%|██▋       | 1582/6015 [08:32<16:58,  4.35it/s]

 26%|██▋       | 1583/6015 [08:32<16:59,  4.35it/s]

 26%|██▋       | 1584/6015 [08:32<16:59,  4.35it/s]

 26%|██▋       | 1585/6015 [08:33<16:58,  4.35it/s]

 26%|██▋       | 1586/6015 [08:33<16:58,  4.35it/s]

 26%|██▋       | 1587/6015 [08:33<16:58,  4.35it/s]

 26%|██▋       | 1588/6015 [08:33<16:57,  4.35it/s]

 26%|██▋       | 1589/6015 [08:34<16:57,  4.35it/s]

 26%|██▋       | 1590/6015 [08:34<16:55,  4.36it/s]

 26%|██▋       | 1591/6015 [08:34<16:55,  4.36it/s]

 26%|██▋       | 1592/6015 [08:34<16:55,  4.36it/s]

 26%|██▋       | 1593/6015 [08:35<16:57,  4.34it/s]

 27%|██▋       | 1594/6015 [08:35<16:58,  4.34it/s]

 27%|██▋       | 1595/6015 [08:35<16:54,  4.36it/s]

 27%|██▋       | 1596/6015 [08:35<16:55,  4.35it/s]

 27%|██▋       | 1597/6015 [08:35<16:56,  4.35it/s]

 27%|██▋       | 1598/6015 [08:36<16:56,  4.34it/s]

 27%|██▋       | 1599/6015 [08:36<16:55,  4.35it/s]

 27%|██▋       | 1600/6015 [08:36<16:54,  4.35it/s]

 27%|██▋       | 1601/6015 [08:36<16:54,  4.35it/s]

 27%|██▋       | 1602/6015 [08:37<16:52,  4.36it/s]

 27%|██▋       | 1603/6015 [08:37<16:50,  4.37it/s]

 27%|██▋       | 1604/6015 [08:37<16:52,  4.36it/s]

 27%|██▋       | 1605/6015 [08:37<16:53,  4.35it/s]

 27%|██▋       | 1606/6015 [08:38<16:52,  4.35it/s]

 27%|██▋       | 1607/6015 [08:38<16:56,  4.33it/s]

 27%|██▋       | 1608/6015 [08:38<16:55,  4.34it/s]

 27%|██▋       | 1609/6015 [08:38<16:56,  4.34it/s]

 27%|██▋       | 1610/6015 [08:38<16:55,  4.34it/s]

 27%|██▋       | 1611/6015 [08:39<16:55,  4.34it/s]

 27%|██▋       | 1612/6015 [08:39<16:54,  4.34it/s]

 27%|██▋       | 1613/6015 [08:39<16:56,  4.33it/s]

 27%|██▋       | 1614/6015 [08:39<16:53,  4.34it/s]

 27%|██▋       | 1615/6015 [08:40<16:53,  4.34it/s]

 27%|██▋       | 1616/6015 [08:40<16:52,  4.34it/s]

 27%|██▋       | 1617/6015 [08:40<16:52,  4.34it/s]

 27%|██▋       | 1618/6015 [08:40<16:53,  4.34it/s]

 27%|██▋       | 1619/6015 [08:40<16:52,  4.34it/s]

 27%|██▋       | 1620/6015 [08:41<16:52,  4.34it/s]

 27%|██▋       | 1621/6015 [08:41<16:52,  4.34it/s]

 27%|██▋       | 1622/6015 [08:41<16:48,  4.35it/s]

 27%|██▋       | 1623/6015 [08:41<16:48,  4.35it/s]

 27%|██▋       | 1624/6015 [08:42<16:49,  4.35it/s]

 27%|██▋       | 1625/6015 [08:42<16:51,  4.34it/s]

 27%|██▋       | 1626/6015 [08:42<16:52,  4.34it/s]

 27%|██▋       | 1627/6015 [08:42<16:51,  4.34it/s]

 27%|██▋       | 1628/6015 [08:43<16:49,  4.34it/s]

 27%|██▋       | 1629/6015 [08:43<16:52,  4.33it/s]

 27%|██▋       | 1630/6015 [08:43<16:50,  4.34it/s]

 27%|██▋       | 1631/6015 [08:43<16:50,  4.34it/s]

 27%|██▋       | 1632/6015 [08:43<16:55,  4.32it/s]

 27%|██▋       | 1633/6015 [08:44<16:54,  4.32it/s]

 27%|██▋       | 1634/6015 [08:44<16:52,  4.33it/s]

 27%|██▋       | 1635/6015 [08:44<16:50,  4.34it/s]

 27%|██▋       | 1636/6015 [08:44<16:47,  4.35it/s]

 27%|██▋       | 1637/6015 [08:45<16:49,  4.34it/s]

 27%|██▋       | 1638/6015 [08:45<16:47,  4.34it/s]

 27%|██▋       | 1639/6015 [08:45<16:49,  4.34it/s]

 27%|██▋       | 1640/6015 [08:45<16:49,  4.33it/s]

 27%|██▋       | 1641/6015 [08:46<16:48,  4.34it/s]

 27%|██▋       | 1642/6015 [08:46<16:48,  4.34it/s]

 27%|██▋       | 1643/6015 [08:46<16:48,  4.34it/s]

 27%|██▋       | 1644/6015 [08:46<16:47,  4.34it/s]

 27%|██▋       | 1645/6015 [08:46<16:49,  4.33it/s]

 27%|██▋       | 1646/6015 [08:47<16:47,  4.34it/s]

 27%|██▋       | 1647/6015 [08:47<16:48,  4.33it/s]

 27%|██▋       | 1648/6015 [08:47<16:49,  4.33it/s]

 27%|██▋       | 1649/6015 [08:47<16:48,  4.33it/s]

 27%|██▋       | 1650/6015 [08:48<16:48,  4.33it/s]

 27%|██▋       | 1651/6015 [08:48<16:49,  4.32it/s]

 27%|██▋       | 1652/6015 [08:48<16:47,  4.33it/s]

 27%|██▋       | 1653/6015 [08:48<16:48,  4.33it/s]

 27%|██▋       | 1654/6015 [08:49<16:48,  4.33it/s]

 28%|██▊       | 1655/6015 [08:49<16:48,  4.32it/s]

 28%|██▊       | 1656/6015 [08:49<16:48,  4.32it/s]

 28%|██▊       | 1657/6015 [08:49<16:47,  4.32it/s]

 28%|██▊       | 1658/6015 [08:49<16:47,  4.32it/s]

 28%|██▊       | 1659/6015 [08:50<16:47,  4.33it/s]

 28%|██▊       | 1660/6015 [08:50<16:46,  4.33it/s]

 28%|██▊       | 1661/6015 [08:50<16:46,  4.33it/s]

 28%|██▊       | 1662/6015 [08:50<16:46,  4.33it/s]

 28%|██▊       | 1663/6015 [08:51<16:46,  4.32it/s]

 28%|██▊       | 1664/6015 [08:51<16:45,  4.33it/s]

 28%|██▊       | 1665/6015 [08:51<16:45,  4.33it/s]

 28%|██▊       | 1666/6015 [08:51<16:45,  4.33it/s]

 28%|██▊       | 1667/6015 [08:52<16:46,  4.32it/s]

 28%|██▊       | 1668/6015 [08:52<16:46,  4.32it/s]

 28%|██▊       | 1669/6015 [08:52<16:45,  4.32it/s]

 28%|██▊       | 1670/6015 [08:52<16:44,  4.32it/s]

 28%|██▊       | 1671/6015 [08:53<16:44,  4.33it/s]

 28%|██▊       | 1672/6015 [08:53<16:44,  4.32it/s]

 28%|██▊       | 1673/6015 [08:53<16:43,  4.33it/s]

 28%|██▊       | 1674/6015 [08:53<16:43,  4.33it/s]

 28%|██▊       | 1675/6015 [08:53<16:44,  4.32it/s]

 28%|██▊       | 1676/6015 [08:54<16:43,  4.33it/s]

 28%|██▊       | 1677/6015 [08:54<16:41,  4.33it/s]

 28%|██▊       | 1678/6015 [08:54<16:43,  4.32it/s]

 28%|██▊       | 1679/6015 [08:54<16:42,  4.32it/s]

 28%|██▊       | 1680/6015 [08:55<16:41,  4.33it/s]

 28%|██▊       | 1681/6015 [08:55<16:43,  4.32it/s]

 28%|██▊       | 1682/6015 [08:55<16:40,  4.33it/s]

 28%|██▊       | 1683/6015 [08:55<16:41,  4.32it/s]

 28%|██▊       | 1684/6015 [08:56<16:41,  4.33it/s]

 28%|██▊       | 1685/6015 [08:56<16:37,  4.34it/s]

 28%|██▊       | 1686/6015 [08:56<16:37,  4.34it/s]

 28%|██▊       | 1687/6015 [08:56<16:38,  4.33it/s]

 28%|██▊       | 1688/6015 [08:56<16:39,  4.33it/s]

 28%|██▊       | 1689/6015 [08:57<16:38,  4.33it/s]

 28%|██▊       | 1690/6015 [08:57<16:36,  4.34it/s]

 28%|██▊       | 1691/6015 [08:57<16:39,  4.33it/s]

 28%|██▊       | 1692/6015 [08:57<16:38,  4.33it/s]

 28%|██▊       | 1693/6015 [08:58<16:37,  4.33it/s]

 28%|██▊       | 1694/6015 [08:58<16:39,  4.32it/s]

 28%|██▊       | 1695/6015 [08:58<16:39,  4.32it/s]

 28%|██▊       | 1696/6015 [08:58<16:39,  4.32it/s]

 28%|██▊       | 1697/6015 [08:59<16:42,  4.31it/s]

 28%|██▊       | 1698/6015 [08:59<16:40,  4.32it/s]

 28%|██▊       | 1699/6015 [08:59<16:41,  4.31it/s]

 28%|██▊       | 1700/6015 [08:59<16:44,  4.30it/s]

 28%|██▊       | 1701/6015 [08:59<16:42,  4.30it/s]

 28%|██▊       | 1702/6015 [09:00<16:42,  4.30it/s]

 28%|██▊       | 1703/6015 [09:00<16:38,  4.32it/s]

 28%|██▊       | 1704/6015 [09:00<16:37,  4.32it/s]

 28%|██▊       | 1705/6015 [09:00<16:37,  4.32it/s]

 28%|██▊       | 1706/6015 [09:01<16:35,  4.33it/s]

 28%|██▊       | 1707/6015 [09:01<16:35,  4.33it/s]

 28%|██▊       | 1708/6015 [09:01<16:35,  4.33it/s]

 28%|██▊       | 1709/6015 [09:01<16:33,  4.33it/s]

 28%|██▊       | 1710/6015 [09:02<16:33,  4.33it/s]

 28%|██▊       | 1711/6015 [09:02<16:31,  4.34it/s]

 28%|██▊       | 1712/6015 [09:02<16:32,  4.33it/s]

 28%|██▊       | 1713/6015 [09:02<16:31,  4.34it/s]

 28%|██▊       | 1714/6015 [09:02<16:31,  4.34it/s]

 29%|██▊       | 1715/6015 [09:03<16:33,  4.33it/s]

 29%|██▊       | 1716/6015 [09:03<16:32,  4.33it/s]

 29%|██▊       | 1717/6015 [09:03<16:32,  4.33it/s]

 29%|██▊       | 1718/6015 [09:03<16:31,  4.33it/s]

 29%|██▊       | 1719/6015 [09:04<16:32,  4.33it/s]

 29%|██▊       | 1720/6015 [09:04<16:35,  4.31it/s]

 29%|██▊       | 1721/6015 [09:04<16:37,  4.31it/s]

 29%|██▊       | 1722/6015 [09:04<16:36,  4.31it/s]

 29%|██▊       | 1723/6015 [09:05<16:36,  4.31it/s]

 29%|██▊       | 1724/6015 [09:05<16:36,  4.31it/s]

 29%|██▊       | 1725/6015 [09:05<16:35,  4.31it/s]

 29%|██▊       | 1726/6015 [09:05<16:36,  4.31it/s]

 29%|██▊       | 1727/6015 [09:05<16:34,  4.31it/s]

 29%|██▊       | 1728/6015 [09:06<16:35,  4.31it/s]

 29%|██▊       | 1729/6015 [09:06<16:38,  4.29it/s]

 29%|██▉       | 1730/6015 [09:06<16:39,  4.29it/s]

 29%|██▉       | 1731/6015 [09:06<16:41,  4.28it/s]

 29%|██▉       | 1732/6015 [09:07<16:38,  4.29it/s]

 29%|██▉       | 1733/6015 [09:07<16:37,  4.29it/s]

 29%|██▉       | 1734/6015 [09:07<16:37,  4.29it/s]

 29%|██▉       | 1735/6015 [09:07<16:40,  4.28it/s]

 29%|██▉       | 1736/6015 [09:08<16:41,  4.27it/s]

 29%|██▉       | 1737/6015 [09:08<16:37,  4.29it/s]

 29%|██▉       | 1738/6015 [09:08<16:36,  4.29it/s]

 29%|██▉       | 1739/6015 [09:08<16:35,  4.30it/s]

 29%|██▉       | 1740/6015 [09:08<16:34,  4.30it/s]

 29%|██▉       | 1741/6015 [09:09<16:34,  4.30it/s]

 29%|██▉       | 1742/6015 [09:09<16:32,  4.30it/s]

 29%|██▉       | 1743/6015 [09:09<16:33,  4.30it/s]

 29%|██▉       | 1744/6015 [09:09<16:34,  4.29it/s]

 29%|██▉       | 1745/6015 [09:10<16:33,  4.30it/s]

 29%|██▉       | 1746/6015 [09:10<16:32,  4.30it/s]

 29%|██▉       | 1747/6015 [09:10<16:31,  4.31it/s]

 29%|██▉       | 1748/6015 [09:10<16:34,  4.29it/s]

 29%|██▉       | 1749/6015 [09:11<16:34,  4.29it/s]

 29%|██▉       | 1750/6015 [09:11<16:32,  4.30it/s]

 29%|██▉       | 1751/6015 [09:11<16:31,  4.30it/s]

 29%|██▉       | 1752/6015 [09:11<16:32,  4.29it/s]

 29%|██▉       | 1753/6015 [09:12<16:30,  4.30it/s]

 29%|██▉       | 1754/6015 [09:12<16:30,  4.30it/s]

 29%|██▉       | 1755/6015 [09:12<16:28,  4.31it/s]

 29%|██▉       | 1756/6015 [09:12<16:28,  4.31it/s]

 29%|██▉       | 1757/6015 [09:12<16:29,  4.30it/s]

 29%|██▉       | 1758/6015 [09:13<16:27,  4.31it/s]

 29%|██▉       | 1759/6015 [09:13<16:27,  4.31it/s]

 29%|██▉       | 1760/6015 [09:13<16:27,  4.31it/s]

 29%|██▉       | 1761/6015 [09:13<16:28,  4.30it/s]

 29%|██▉       | 1762/6015 [09:14<16:29,  4.30it/s]

 29%|██▉       | 1763/6015 [09:14<16:28,  4.30it/s]

 29%|██▉       | 1764/6015 [09:14<16:28,  4.30it/s]

 29%|██▉       | 1765/6015 [09:14<16:27,  4.30it/s]

 29%|██▉       | 1766/6015 [09:15<16:25,  4.31it/s]

 29%|██▉       | 1767/6015 [09:15<16:25,  4.31it/s]

 29%|██▉       | 1768/6015 [09:15<16:23,  4.32it/s]

 29%|██▉       | 1769/6015 [09:15<16:26,  4.30it/s]

 29%|██▉       | 1770/6015 [09:15<16:27,  4.30it/s]

 29%|██▉       | 1771/6015 [09:16<16:25,  4.30it/s]

 29%|██▉       | 1772/6015 [09:16<16:28,  4.29it/s]

 29%|██▉       | 1773/6015 [09:16<16:33,  4.27it/s]

 29%|██▉       | 1774/6015 [09:16<16:32,  4.27it/s]

 30%|██▉       | 1775/6015 [09:17<16:32,  4.27it/s]

 30%|██▉       | 1776/6015 [09:17<16:31,  4.28it/s]

 30%|██▉       | 1777/6015 [09:17<16:33,  4.26it/s]

 30%|██▉       | 1778/6015 [09:17<16:34,  4.26it/s]

 30%|██▉       | 1779/6015 [09:18<16:34,  4.26it/s]

 30%|██▉       | 1780/6015 [09:18<16:31,  4.27it/s]

 30%|██▉       | 1781/6015 [09:18<16:29,  4.28it/s]

 30%|██▉       | 1782/6015 [09:18<16:30,  4.28it/s]

 30%|██▉       | 1783/6015 [09:19<16:31,  4.27it/s]

 30%|██▉       | 1784/6015 [09:19<16:31,  4.27it/s]

 30%|██▉       | 1785/6015 [09:19<16:31,  4.27it/s]

 30%|██▉       | 1786/6015 [09:19<16:28,  4.28it/s]

 30%|██▉       | 1787/6015 [09:19<16:31,  4.26it/s]

 30%|██▉       | 1788/6015 [09:20<16:39,  4.23it/s]

 30%|██▉       | 1789/6015 [09:20<16:33,  4.25it/s]

 30%|██▉       | 1790/6015 [09:20<16:32,  4.26it/s]

 30%|██▉       | 1791/6015 [09:20<16:31,  4.26it/s]

 30%|██▉       | 1792/6015 [09:21<16:29,  4.27it/s]

 30%|██▉       | 1793/6015 [09:21<16:32,  4.26it/s]

 30%|██▉       | 1794/6015 [09:21<16:32,  4.25it/s]

 30%|██▉       | 1795/6015 [09:21<16:33,  4.25it/s]

 30%|██▉       | 1796/6015 [09:22<16:30,  4.26it/s]

 30%|██▉       | 1797/6015 [09:22<16:29,  4.26it/s]

 30%|██▉       | 1798/6015 [09:22<16:30,  4.26it/s]

 30%|██▉       | 1799/6015 [09:22<16:29,  4.26it/s]

 30%|██▉       | 1800/6015 [09:22<16:27,  4.27it/s]

 30%|██▉       | 1801/6015 [09:23<16:25,  4.28it/s]

 30%|██▉       | 1802/6015 [09:23<16:24,  4.28it/s]

 30%|██▉       | 1803/6015 [09:23<16:23,  4.28it/s]

 30%|██▉       | 1804/6015 [09:23<16:22,  4.29it/s]

 30%|███       | 1805/6015 [09:24<16:25,  4.27it/s]

 30%|███       | 1806/6015 [09:24<16:24,  4.28it/s]

 30%|███       | 1807/6015 [09:24<16:24,  4.27it/s]

 30%|███       | 1808/6015 [09:24<16:25,  4.27it/s]

 30%|███       | 1809/6015 [09:25<16:26,  4.27it/s]

 30%|███       | 1810/6015 [09:25<16:23,  4.28it/s]

 30%|███       | 1811/6015 [09:25<16:22,  4.28it/s]

 30%|███       | 1812/6015 [09:25<16:23,  4.28it/s]

 30%|███       | 1813/6015 [09:26<16:22,  4.28it/s]

 30%|███       | 1814/6015 [09:26<16:21,  4.28it/s]

 30%|███       | 1815/6015 [09:26<16:22,  4.28it/s]

 30%|███       | 1816/6015 [09:26<16:36,  4.21it/s]

 30%|███       | 1817/6015 [09:26<16:31,  4.24it/s]

 30%|███       | 1818/6015 [09:27<16:28,  4.24it/s]

 30%|███       | 1819/6015 [09:27<16:26,  4.25it/s]

 30%|███       | 1820/6015 [09:27<16:25,  4.26it/s]

 30%|███       | 1821/6015 [09:27<16:24,  4.26it/s]

 30%|███       | 1822/6015 [09:28<16:23,  4.26it/s]

 30%|███       | 1823/6015 [09:28<16:24,  4.26it/s]

 30%|███       | 1824/6015 [09:28<16:22,  4.27it/s]

 30%|███       | 1825/6015 [09:28<16:22,  4.26it/s]

 30%|███       | 1826/6015 [09:29<16:23,  4.26it/s]

 30%|███       | 1827/6015 [09:29<16:21,  4.27it/s]

 30%|███       | 1828/6015 [09:29<16:19,  4.28it/s]

 30%|███       | 1829/6015 [09:29<16:18,  4.28it/s]

 30%|███       | 1830/6015 [09:30<16:18,  4.28it/s]

 30%|███       | 1831/6015 [09:30<16:19,  4.27it/s]

 30%|███       | 1832/6015 [09:30<16:19,  4.27it/s]

 30%|███       | 1833/6015 [09:30<16:20,  4.26it/s]

 30%|███       | 1834/6015 [09:30<16:19,  4.27it/s]

 31%|███       | 1835/6015 [09:31<16:17,  4.28it/s]

 31%|███       | 1836/6015 [09:31<16:16,  4.28it/s]

 31%|███       | 1837/6015 [09:31<16:17,  4.27it/s]

 31%|███       | 1838/6015 [09:31<16:18,  4.27it/s]

 31%|███       | 1839/6015 [09:32<16:16,  4.28it/s]

 31%|███       | 1840/6015 [09:32<16:16,  4.27it/s]

 31%|███       | 1841/6015 [09:32<16:16,  4.27it/s]

 31%|███       | 1842/6015 [09:32<16:15,  4.28it/s]

 31%|███       | 1843/6015 [09:33<16:15,  4.28it/s]

 31%|███       | 1844/6015 [09:33<16:15,  4.28it/s]

 31%|███       | 1845/6015 [09:33<16:16,  4.27it/s]

 31%|███       | 1846/6015 [09:33<16:16,  4.27it/s]

 31%|███       | 1847/6015 [09:34<16:16,  4.27it/s]

 31%|███       | 1848/6015 [09:34<16:17,  4.26it/s]

 31%|███       | 1849/6015 [09:34<16:14,  4.27it/s]

 31%|███       | 1850/6015 [09:34<16:17,  4.26it/s]

 31%|███       | 1851/6015 [09:34<16:18,  4.25it/s]

 31%|███       | 1852/6015 [09:35<16:22,  4.24it/s]

 31%|███       | 1853/6015 [09:35<16:20,  4.24it/s]

 31%|███       | 1854/6015 [09:35<16:17,  4.26it/s]

 31%|███       | 1855/6015 [09:35<16:18,  4.25it/s]

 31%|███       | 1856/6015 [09:36<16:16,  4.26it/s]

 31%|███       | 1857/6015 [09:36<16:16,  4.26it/s]

 31%|███       | 1858/6015 [09:36<16:16,  4.26it/s]

 31%|███       | 1859/6015 [09:36<16:14,  4.26it/s]

 31%|███       | 1860/6015 [09:37<16:14,  4.26it/s]

 31%|███       | 1861/6015 [09:37<16:15,  4.26it/s]

 31%|███       | 1862/6015 [09:37<16:13,  4.26it/s]

 31%|███       | 1863/6015 [09:37<16:14,  4.26it/s]

 31%|███       | 1864/6015 [09:38<16:12,  4.27it/s]

 31%|███       | 1865/6015 [09:38<16:13,  4.26it/s]

 31%|███       | 1866/6015 [09:38<16:14,  4.26it/s]

 31%|███       | 1867/6015 [09:38<16:12,  4.26it/s]

 31%|███       | 1868/6015 [09:38<16:12,  4.26it/s]

 31%|███       | 1869/6015 [09:39<16:11,  4.27it/s]

 31%|███       | 1870/6015 [09:39<16:11,  4.26it/s]

 31%|███       | 1871/6015 [09:39<16:11,  4.27it/s]

 31%|███       | 1872/6015 [09:39<16:11,  4.26it/s]

 31%|███       | 1873/6015 [09:40<16:12,  4.26it/s]

 31%|███       | 1874/6015 [09:40<16:09,  4.27it/s]

 31%|███       | 1875/6015 [09:40<16:12,  4.26it/s]

 31%|███       | 1876/6015 [09:40<16:15,  4.25it/s]

 31%|███       | 1877/6015 [09:41<16:12,  4.25it/s]

logging
logging the anndata

 31%|███       | 1878/6015 [09:42<35:53,  1.92it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 31%|███       | 1879/6015 [09:42<29:49,  2.31it/s]

 31%|███▏      | 1880/6015 [09:42<25:34,  2.70it/s]

 31%|███▏      | 1881/6015 [09:42<22:36,  3.05it/s]

 31%|███▏      | 1882/6015 [09:43<20:32,  3.35it/s]

 31%|███▏      | 1883/6015 [09:43<19:04,  3.61it/s]

 31%|███▏      | 1884/6015 [09:43<18:04,  3.81it/s]

 31%|███▏      | 1885/6015 [09:43<17:22,  3.96it/s]

 31%|███▏      | 1886/6015 [09:44<16:53,  4.07it/s]

 31%|███▏      | 1887/6015 [09:44<16:31,  4.16it/s]

 31%|███▏      | 1888/6015 [09:44<16:16,  4.23it/s]

 31%|███▏      | 1889/6015 [09:44<16:07,  4.27it/s]

 31%|███▏      | 1890/6015 [09:44<16:00,  4.30it/s]

 31%|███▏      | 1891/6015 [09:45<15:55,  4.32it/s]

 31%|███▏      | 1892/6015 [09:45<15:50,  4.34it/s]

 31%|███▏      | 1893/6015 [09:45<15:47,  4.35it/s]

 31%|███▏      | 1894/6015 [09:45<15:44,  4.36it/s]

 32%|███▏      | 1895/6015 [09:46<15:42,  4.37it/s]

 32%|███▏      | 1896/6015 [09:46<15:42,  4.37it/s]

 32%|███▏      | 1897/6015 [09:46<15:39,  4.38it/s]

 32%|███▏      | 1898/6015 [09:46<15:39,  4.38it/s]

 32%|███▏      | 1899/6015 [09:47<15:39,  4.38it/s]

 32%|███▏      | 1900/6015 [09:47<15:38,  4.38it/s]

 32%|███▏      | 1901/6015 [09:47<15:38,  4.38it/s]

 32%|███▏      | 1902/6015 [09:47<15:39,  4.38it/s]

 32%|███▏      | 1903/6015 [09:47<15:39,  4.38it/s]

 32%|███▏      | 1904/6015 [09:48<15:38,  4.38it/s]

 32%|███▏      | 1905/6015 [09:48<15:37,  4.38it/s]

 32%|███▏      | 1906/6015 [09:48<15:38,  4.38it/s]

 32%|███▏      | 1907/6015 [09:48<15:39,  4.37it/s]

 32%|███▏      | 1908/6015 [09:49<15:38,  4.38it/s]

 32%|███▏      | 1909/6015 [09:49<15:37,  4.38it/s]

 32%|███▏      | 1910/6015 [09:49<15:37,  4.38it/s]

 32%|███▏      | 1911/6015 [09:49<15:36,  4.38it/s]

 32%|███▏      | 1912/6015 [09:50<15:37,  4.38it/s]

 32%|███▏      | 1913/6015 [09:50<15:37,  4.37it/s]

 32%|███▏      | 1914/6015 [09:50<15:44,  4.34it/s]

 32%|███▏      | 1915/6015 [09:50<15:42,  4.35it/s]

 32%|███▏      | 1916/6015 [09:50<15:41,  4.36it/s]

 32%|███▏      | 1917/6015 [09:51<15:40,  4.36it/s]

 32%|███▏      | 1918/6015 [09:51<15:39,  4.36it/s]

 32%|███▏      | 1919/6015 [09:51<15:37,  4.37it/s]

 32%|███▏      | 1920/6015 [09:51<15:39,  4.36it/s]

 32%|███▏      | 1921/6015 [09:52<15:38,  4.36it/s]

 32%|███▏      | 1922/6015 [09:52<15:37,  4.37it/s]

 32%|███▏      | 1923/6015 [09:52<15:38,  4.36it/s]

 32%|███▏      | 1924/6015 [09:52<15:39,  4.36it/s]

 32%|███▏      | 1925/6015 [09:52<15:36,  4.37it/s]

 32%|███▏      | 1926/6015 [09:53<15:36,  4.37it/s]

 32%|███▏      | 1927/6015 [09:53<15:37,  4.36it/s]

 32%|███▏      | 1928/6015 [09:53<15:35,  4.37it/s]

 32%|███▏      | 1929/6015 [09:53<15:34,  4.37it/s]

 32%|███▏      | 1930/6015 [09:54<15:34,  4.37it/s]

 32%|███▏      | 1931/6015 [09:54<15:36,  4.36it/s]

 32%|███▏      | 1932/6015 [09:54<15:38,  4.35it/s]

 32%|███▏      | 1933/6015 [09:54<15:38,  4.35it/s]

 32%|███▏      | 1934/6015 [09:55<15:37,  4.35it/s]

 32%|███▏      | 1935/6015 [09:55<15:38,  4.35it/s]

 32%|███▏      | 1936/6015 [09:55<15:35,  4.36it/s]

 32%|███▏      | 1937/6015 [09:55<15:36,  4.36it/s]

 32%|███▏      | 1938/6015 [09:55<15:35,  4.36it/s]

 32%|███▏      | 1939/6015 [09:56<15:34,  4.36it/s]

 32%|███▏      | 1940/6015 [09:56<15:36,  4.35it/s]

 32%|███▏      | 1941/6015 [09:56<15:35,  4.35it/s]

 32%|███▏      | 1942/6015 [09:56<15:33,  4.36it/s]

 32%|███▏      | 1943/6015 [09:57<15:35,  4.35it/s]

 32%|███▏      | 1944/6015 [09:57<15:34,  4.36it/s]

 32%|███▏      | 1945/6015 [09:57<15:34,  4.35it/s]

 32%|███▏      | 1946/6015 [09:57<15:34,  4.36it/s]

 32%|███▏      | 1947/6015 [09:58<15:35,  4.35it/s]

 32%|███▏      | 1948/6015 [09:58<15:32,  4.36it/s]

 32%|███▏      | 1949/6015 [09:58<15:31,  4.36it/s]

 32%|███▏      | 1950/6015 [09:58<15:33,  4.35it/s]

 32%|███▏      | 1951/6015 [09:58<15:32,  4.36it/s]

 32%|███▏      | 1952/6015 [09:59<15:32,  4.36it/s]

 32%|███▏      | 1953/6015 [09:59<15:32,  4.35it/s]

 32%|███▏      | 1954/6015 [09:59<15:31,  4.36it/s]

 33%|███▎      | 1955/6015 [09:59<15:29,  4.37it/s]

 33%|███▎      | 1956/6015 [10:00<15:30,  4.36it/s]

 33%|███▎      | 1957/6015 [10:00<15:30,  4.36it/s]

 33%|███▎      | 1958/6015 [10:00<15:30,  4.36it/s]

 33%|███▎      | 1959/6015 [10:00<15:31,  4.36it/s]

 33%|███▎      | 1960/6015 [10:01<15:32,  4.35it/s]

 33%|███▎      | 1961/6015 [10:01<15:31,  4.35it/s]

 33%|███▎      | 1962/6015 [10:01<15:28,  4.36it/s]

 33%|███▎      | 1963/6015 [10:01<15:28,  4.36it/s]

 33%|███▎      | 1964/6015 [10:01<15:40,  4.31it/s]

 33%|███▎      | 1965/6015 [10:02<15:34,  4.33it/s]

 33%|███▎      | 1966/6015 [10:02<15:32,  4.34it/s]

 33%|███▎      | 1967/6015 [10:02<15:29,  4.35it/s]

 33%|███▎      | 1968/6015 [10:02<15:28,  4.36it/s]

 33%|███▎      | 1969/6015 [10:03<15:29,  4.35it/s]

 33%|███▎      | 1970/6015 [10:03<15:26,  4.37it/s]

 33%|███▎      | 1971/6015 [10:03<15:25,  4.37it/s]

 33%|███▎      | 1972/6015 [10:03<15:26,  4.37it/s]

 33%|███▎      | 1973/6015 [10:04<15:25,  4.37it/s]

 33%|███▎      | 1974/6015 [10:04<15:25,  4.36it/s]

 33%|███▎      | 1975/6015 [10:04<15:26,  4.36it/s]

 33%|███▎      | 1976/6015 [10:04<15:25,  4.36it/s]

 33%|███▎      | 1977/6015 [10:04<15:24,  4.37it/s]

 33%|███▎      | 1978/6015 [10:05<15:24,  4.37it/s]

 33%|███▎      | 1979/6015 [10:05<15:22,  4.37it/s]

 33%|███▎      | 1980/6015 [10:05<15:22,  4.37it/s]

 33%|███▎      | 1981/6015 [10:05<15:22,  4.37it/s]

 33%|███▎      | 1982/6015 [10:06<15:22,  4.37it/s]

 33%|███▎      | 1983/6015 [10:06<15:24,  4.36it/s]

 33%|███▎      | 1984/6015 [10:06<15:22,  4.37it/s]

 33%|███▎      | 1985/6015 [10:06<15:24,  4.36it/s]

 33%|███▎      | 1986/6015 [10:06<15:26,  4.35it/s]

 33%|███▎      | 1987/6015 [10:07<15:24,  4.36it/s]

 33%|███▎      | 1988/6015 [10:07<15:24,  4.36it/s]

 33%|███▎      | 1989/6015 [10:07<15:23,  4.36it/s]

 33%|███▎      | 1990/6015 [10:07<15:23,  4.36it/s]

 33%|███▎      | 1991/6015 [10:08<15:24,  4.35it/s]

 33%|███▎      | 1992/6015 [10:08<15:22,  4.36it/s]

 33%|███▎      | 1993/6015 [10:08<15:22,  4.36it/s]

 33%|███▎      | 1994/6015 [10:08<15:22,  4.36it/s]

 33%|███▎      | 1995/6015 [10:09<15:23,  4.35it/s]

 33%|███▎      | 1996/6015 [10:09<15:23,  4.35it/s]

 33%|███▎      | 1997/6015 [10:09<15:24,  4.35it/s]

 33%|███▎      | 1998/6015 [10:09<15:24,  4.34it/s]

 33%|███▎      | 1999/6015 [10:09<15:23,  4.35it/s]

 33%|███▎      | 2000/6015 [10:10<15:21,  4.36it/s]

 33%|███▎      | 2001/6015 [10:10<15:20,  4.36it/s]

 33%|███▎      | 2002/6015 [10:10<15:21,  4.36it/s]

 33%|███▎      | 2003/6015 [10:10<15:20,  4.36it/s]

 33%|███▎      | 2004/6015 [10:11<15:21,  4.35it/s]

 33%|███▎      | 2005/6015 [10:11<15:18,  4.36it/s]

 33%|███▎      | 2006/6015 [10:11<15:19,  4.36it/s]

 33%|███▎      | 2007/6015 [10:11<15:20,  4.36it/s]

 33%|███▎      | 2008/6015 [10:12<15:19,  4.36it/s]

 33%|███▎      | 2009/6015 [10:12<15:21,  4.35it/s]

 33%|███▎      | 2010/6015 [10:12<15:22,  4.34it/s]

 33%|███▎      | 2011/6015 [10:12<15:20,  4.35it/s]

 33%|███▎      | 2012/6015 [10:12<15:21,  4.34it/s]

 33%|███▎      | 2013/6015 [10:13<15:21,  4.34it/s]

 33%|███▎      | 2014/6015 [10:13<15:20,  4.35it/s]

 33%|███▎      | 2015/6015 [10:13<15:19,  4.35it/s]

 34%|███▎      | 2016/6015 [10:13<15:19,  4.35it/s]

 34%|███▎      | 2017/6015 [10:14<15:19,  4.35it/s]

 34%|███▎      | 2018/6015 [10:14<15:19,  4.35it/s]

 34%|███▎      | 2019/6015 [10:14<15:18,  4.35it/s]

 34%|███▎      | 2020/6015 [10:14<15:19,  4.35it/s]

 34%|███▎      | 2021/6015 [10:15<15:17,  4.35it/s]

 34%|███▎      | 2022/6015 [10:15<15:17,  4.35it/s]

 34%|███▎      | 2023/6015 [10:15<15:18,  4.35it/s]

 34%|███▎      | 2024/6015 [10:15<15:17,  4.35it/s]

 34%|███▎      | 2025/6015 [10:15<15:17,  4.35it/s]

 34%|███▎      | 2026/6015 [10:16<15:18,  4.34it/s]

 34%|███▎      | 2027/6015 [10:16<15:17,  4.35it/s]

 34%|███▎      | 2028/6015 [10:16<15:16,  4.35it/s]

 34%|███▎      | 2029/6015 [10:16<15:17,  4.34it/s]

 34%|███▎      | 2030/6015 [10:17<15:16,  4.35it/s]

 34%|███▍      | 2031/6015 [10:17<15:15,  4.35it/s]

 34%|███▍      | 2032/6015 [10:17<15:16,  4.35it/s]

 34%|███▍      | 2033/6015 [10:17<15:16,  4.35it/s]

 34%|███▍      | 2034/6015 [10:18<15:15,  4.35it/s]

 34%|███▍      | 2035/6015 [10:18<15:14,  4.35it/s]

 34%|███▍      | 2036/6015 [10:18<15:16,  4.34it/s]

 34%|███▍      | 2037/6015 [10:18<15:16,  4.34it/s]

 34%|███▍      | 2038/6015 [10:18<15:14,  4.35it/s]

 34%|███▍      | 2039/6015 [10:19<15:15,  4.34it/s]

 34%|███▍      | 2040/6015 [10:19<15:21,  4.31it/s]

 34%|███▍      | 2041/6015 [10:19<15:19,  4.32it/s]

 34%|███▍      | 2042/6015 [10:19<15:19,  4.32it/s]

 34%|███▍      | 2043/6015 [10:20<15:17,  4.33it/s]

 34%|███▍      | 2044/6015 [10:20<15:16,  4.33it/s]

 34%|███▍      | 2045/6015 [10:20<15:15,  4.34it/s]

 34%|███▍      | 2046/6015 [10:20<15:14,  4.34it/s]

 34%|███▍      | 2047/6015 [10:21<15:13,  4.34it/s]

 34%|███▍      | 2048/6015 [10:21<15:13,  4.34it/s]

 34%|███▍      | 2049/6015 [10:21<15:14,  4.34it/s]

 34%|███▍      | 2050/6015 [10:21<15:15,  4.33it/s]

 34%|███▍      | 2051/6015 [10:21<15:13,  4.34it/s]

 34%|███▍      | 2052/6015 [10:22<15:11,  4.35it/s]

 34%|███▍      | 2053/6015 [10:22<15:12,  4.34it/s]

 34%|███▍      | 2054/6015 [10:22<15:10,  4.35it/s]

 34%|███▍      | 2055/6015 [10:22<15:10,  4.35it/s]

 34%|███▍      | 2056/6015 [10:23<15:10,  4.35it/s]

 34%|███▍      | 2057/6015 [10:23<15:12,  4.34it/s]

 34%|███▍      | 2058/6015 [10:23<15:12,  4.34it/s]

 34%|███▍      | 2059/6015 [10:23<15:10,  4.35it/s]

 34%|███▍      | 2060/6015 [10:24<15:11,  4.34it/s]

 34%|███▍      | 2061/6015 [10:24<15:11,  4.34it/s]

 34%|███▍      | 2062/6015 [10:24<15:11,  4.34it/s]

 34%|███▍      | 2063/6015 [10:24<15:11,  4.33it/s]

 34%|███▍      | 2064/6015 [10:24<15:10,  4.34it/s]

 34%|███▍      | 2065/6015 [10:25<15:08,  4.35it/s]

 34%|███▍      | 2066/6015 [10:25<15:08,  4.34it/s]

 34%|███▍      | 2067/6015 [10:25<15:09,  4.34it/s]

 34%|███▍      | 2068/6015 [10:25<15:09,  4.34it/s]

 34%|███▍      | 2069/6015 [10:26<15:10,  4.34it/s]

 34%|███▍      | 2070/6015 [10:26<15:08,  4.34it/s]

 34%|███▍      | 2071/6015 [10:26<15:09,  4.34it/s]

 34%|███▍      | 2072/6015 [10:26<15:08,  4.34it/s]

 34%|███▍      | 2073/6015 [10:27<15:07,  4.34it/s]

 34%|███▍      | 2074/6015 [10:27<15:15,  4.30it/s]

 34%|███▍      | 2075/6015 [10:27<15:13,  4.31it/s]

 35%|███▍      | 2076/6015 [10:27<15:10,  4.33it/s]

 35%|███▍      | 2077/6015 [10:27<15:09,  4.33it/s]

 35%|███▍      | 2078/6015 [10:28<15:08,  4.33it/s]

 35%|███▍      | 2079/6015 [10:28<15:07,  4.34it/s]

 35%|███▍      | 2080/6015 [10:28<15:08,  4.33it/s]

 35%|███▍      | 2081/6015 [10:28<15:07,  4.34it/s]

 35%|███▍      | 2082/6015 [10:29<15:08,  4.33it/s]

 35%|███▍      | 2083/6015 [10:29<15:06,  4.34it/s]

 35%|███▍      | 2084/6015 [10:29<15:07,  4.33it/s]

 35%|███▍      | 2085/6015 [10:29<15:09,  4.32it/s]

 35%|███▍      | 2086/6015 [10:30<15:08,  4.33it/s]

 35%|███▍      | 2087/6015 [10:30<15:07,  4.33it/s]

 35%|███▍      | 2088/6015 [10:30<15:08,  4.32it/s]

 35%|███▍      | 2089/6015 [10:30<15:07,  4.33it/s]

 35%|███▍      | 2090/6015 [10:30<15:08,  4.32it/s]

 35%|███▍      | 2091/6015 [10:31<15:07,  4.32it/s]

 35%|███▍      | 2092/6015 [10:31<15:08,  4.32it/s]

 35%|███▍      | 2093/6015 [10:31<15:07,  4.32it/s]

 35%|███▍      | 2094/6015 [10:31<15:06,  4.33it/s]

 35%|███▍      | 2095/6015 [10:32<15:05,  4.33it/s]

 35%|███▍      | 2096/6015 [10:32<15:05,  4.33it/s]

 35%|███▍      | 2097/6015 [10:32<15:06,  4.32it/s]

 35%|███▍      | 2098/6015 [10:32<15:06,  4.32it/s]

 35%|███▍      | 2099/6015 [10:33<15:05,  4.33it/s]

 35%|███▍      | 2100/6015 [10:33<15:04,  4.33it/s]

 35%|███▍      | 2101/6015 [10:33<15:02,  4.34it/s]

 35%|███▍      | 2102/6015 [10:33<15:02,  4.34it/s]

 35%|███▍      | 2103/6015 [10:33<15:02,  4.34it/s]

 35%|███▍      | 2104/6015 [10:34<15:01,  4.34it/s]

 35%|███▍      | 2105/6015 [10:34<15:01,  4.34it/s]

 35%|███▌      | 2106/6015 [10:34<15:01,  4.34it/s]

 35%|███▌      | 2107/6015 [10:34<15:01,  4.34it/s]

 35%|███▌      | 2108/6015 [10:35<15:00,  4.34it/s]

 35%|███▌      | 2109/6015 [10:35<15:01,  4.33it/s]

 35%|███▌      | 2110/6015 [10:35<15:00,  4.34it/s]

 35%|███▌      | 2111/6015 [10:35<15:01,  4.33it/s]

 35%|███▌      | 2112/6015 [10:36<15:03,  4.32it/s]

 35%|███▌      | 2113/6015 [10:36<15:03,  4.32it/s]

 35%|███▌      | 2114/6015 [10:36<15:03,  4.32it/s]

 35%|███▌      | 2115/6015 [10:36<15:01,  4.32it/s]

 35%|███▌      | 2116/6015 [10:36<15:01,  4.33it/s]

 35%|███▌      | 2117/6015 [10:37<15:03,  4.32it/s]

 35%|███▌      | 2118/6015 [10:37<15:00,  4.33it/s]

 35%|███▌      | 2119/6015 [10:37<14:59,  4.33it/s]

 35%|███▌      | 2120/6015 [10:37<14:58,  4.33it/s]

 35%|███▌      | 2121/6015 [10:38<15:03,  4.31it/s]

 35%|███▌      | 2122/6015 [10:38<15:02,  4.31it/s]

 35%|███▌      | 2123/6015 [10:38<14:59,  4.33it/s]

 35%|███▌      | 2124/6015 [10:38<14:58,  4.33it/s]

 35%|███▌      | 2125/6015 [10:39<14:59,  4.33it/s]

 35%|███▌      | 2126/6015 [10:39<14:56,  4.34it/s]

 35%|███▌      | 2127/6015 [10:39<14:58,  4.33it/s]

 35%|███▌      | 2128/6015 [10:39<14:57,  4.33it/s]

 35%|███▌      | 2129/6015 [10:39<14:58,  4.33it/s]

 35%|███▌      | 2130/6015 [10:40<14:57,  4.33it/s]

 35%|███▌      | 2131/6015 [10:40<14:55,  4.34it/s]

 35%|███▌      | 2132/6015 [10:40<14:55,  4.34it/s]

 35%|███▌      | 2133/6015 [10:40<14:56,  4.33it/s]

 35%|███▌      | 2134/6015 [10:41<14:54,  4.34it/s]

 35%|███▌      | 2135/6015 [10:41<14:54,  4.34it/s]

 36%|███▌      | 2136/6015 [10:41<14:53,  4.34it/s]

 36%|███▌      | 2137/6015 [10:41<14:54,  4.34it/s]

 36%|███▌      | 2138/6015 [10:42<14:54,  4.33it/s]

 36%|███▌      | 2139/6015 [10:42<14:51,  4.35it/s]

 36%|███▌      | 2140/6015 [10:42<14:50,  4.35it/s]

 36%|███▌      | 2141/6015 [10:42<14:51,  4.35it/s]

 36%|███▌      | 2142/6015 [10:42<14:52,  4.34it/s]

 36%|███▌      | 2143/6015 [10:43<14:54,  4.33it/s]

 36%|███▌      | 2144/6015 [10:43<14:54,  4.33it/s]

 36%|███▌      | 2145/6015 [10:43<14:54,  4.33it/s]

 36%|███▌      | 2146/6015 [10:43<14:53,  4.33it/s]

 36%|███▌      | 2147/6015 [10:44<14:52,  4.33it/s]

 36%|███▌      | 2148/6015 [10:44<14:53,  4.33it/s]

 36%|███▌      | 2149/6015 [10:44<14:52,  4.33it/s]

 36%|███▌      | 2150/6015 [10:44<14:52,  4.33it/s]

 36%|███▌      | 2151/6015 [10:45<14:51,  4.34it/s]

 36%|███▌      | 2152/6015 [10:45<14:55,  4.31it/s]

 36%|███▌      | 2153/6015 [10:45<14:54,  4.32it/s]

 36%|███▌      | 2154/6015 [10:45<14:54,  4.32it/s]

 36%|███▌      | 2155/6015 [10:45<14:52,  4.33it/s]

 36%|███▌      | 2156/6015 [10:46<14:52,  4.33it/s]

 36%|███▌      | 2157/6015 [10:46<14:51,  4.33it/s]

 36%|███▌      | 2158/6015 [10:46<14:49,  4.34it/s]

 36%|███▌      | 2159/6015 [10:46<14:50,  4.33it/s]

 36%|███▌      | 2160/6015 [10:47<14:56,  4.30it/s]

 36%|███▌      | 2161/6015 [10:47<14:53,  4.32it/s]

 36%|███▌      | 2162/6015 [10:47<14:52,  4.32it/s]

 36%|███▌      | 2163/6015 [10:47<14:50,  4.32it/s]

 36%|███▌      | 2164/6015 [10:48<14:52,  4.31it/s]

 36%|███▌      | 2165/6015 [10:48<14:53,  4.31it/s]

 36%|███▌      | 2166/6015 [10:48<14:50,  4.32it/s]

 36%|███▌      | 2167/6015 [10:48<14:50,  4.32it/s]

 36%|███▌      | 2168/6015 [10:48<14:50,  4.32it/s]

 36%|███▌      | 2169/6015 [10:49<14:49,  4.33it/s]

 36%|███▌      | 2170/6015 [10:49<14:48,  4.33it/s]

 36%|███▌      | 2171/6015 [10:49<14:46,  4.34it/s]

 36%|███▌      | 2172/6015 [10:49<14:46,  4.33it/s]

 36%|███▌      | 2173/6015 [10:50<14:49,  4.32it/s]

 36%|███▌      | 2174/6015 [10:50<14:46,  4.33it/s]

 36%|███▌      | 2175/6015 [10:50<14:46,  4.33it/s]

 36%|███▌      | 2176/6015 [10:50<14:47,  4.33it/s]

 36%|███▌      | 2177/6015 [10:51<14:47,  4.32it/s]

 36%|███▌      | 2178/6015 [10:51<14:47,  4.32it/s]

 36%|███▌      | 2179/6015 [10:51<14:46,  4.33it/s]

 36%|███▌      | 2180/6015 [10:51<14:46,  4.32it/s]

 36%|███▋      | 2181/6015 [10:51<14:46,  4.33it/s]

 36%|███▋      | 2182/6015 [10:52<14:46,  4.33it/s]

 36%|███▋      | 2183/6015 [10:52<14:46,  4.32it/s]

 36%|███▋      | 2184/6015 [10:52<14:44,  4.33it/s]

 36%|███▋      | 2185/6015 [10:52<14:43,  4.34it/s]

 36%|███▋      | 2186/6015 [10:53<14:42,  4.34it/s]

 36%|███▋      | 2187/6015 [10:53<14:40,  4.35it/s]

 36%|███▋      | 2188/6015 [10:53<14:41,  4.34it/s]

 36%|███▋      | 2189/6015 [10:53<14:41,  4.34it/s]

 36%|███▋      | 2190/6015 [10:54<14:41,  4.34it/s]

 36%|███▋      | 2191/6015 [10:54<14:41,  4.34it/s]

 36%|███▋      | 2192/6015 [10:54<14:40,  4.34it/s]

 36%|███▋      | 2193/6015 [10:54<14:39,  4.34it/s]

 36%|███▋      | 2194/6015 [10:54<14:39,  4.35it/s]

 36%|███▋      | 2195/6015 [10:55<14:37,  4.36it/s]

 37%|███▋      | 2196/6015 [10:55<14:37,  4.35it/s]

 37%|███▋      | 2197/6015 [10:55<14:39,  4.34it/s]

 37%|███▋      | 2198/6015 [10:55<14:38,  4.35it/s]

 37%|███▋      | 2199/6015 [10:56<14:38,  4.34it/s]

 37%|███▋      | 2200/6015 [10:56<14:40,  4.33it/s]

 37%|███▋      | 2201/6015 [10:56<14:39,  4.34it/s]

 37%|███▋      | 2202/6015 [10:56<14:40,  4.33it/s]

 37%|███▋      | 2203/6015 [10:57<14:40,  4.33it/s]

 37%|███▋      | 2204/6015 [10:57<14:42,  4.32it/s]

 37%|███▋      | 2205/6015 [10:57<14:43,  4.31it/s]

 37%|███▋      | 2206/6015 [10:57<14:41,  4.32it/s]

 37%|███▋      | 2207/6015 [10:57<14:40,  4.32it/s]

 37%|███▋      | 2208/6015 [10:58<14:45,  4.30it/s]

 37%|███▋      | 2209/6015 [10:58<14:42,  4.31it/s]

 37%|███▋      | 2210/6015 [10:58<14:42,  4.31it/s]

 37%|███▋      | 2211/6015 [10:58<14:40,  4.32it/s]

 37%|███▋      | 2212/6015 [10:59<14:40,  4.32it/s]

 37%|███▋      | 2213/6015 [10:59<14:40,  4.32it/s]

 37%|███▋      | 2214/6015 [10:59<14:38,  4.32it/s]

 37%|███▋      | 2215/6015 [10:59<14:38,  4.33it/s]

 37%|███▋      | 2216/6015 [11:00<14:39,  4.32it/s]

 37%|███▋      | 2217/6015 [11:00<14:37,  4.33it/s]

 37%|███▋      | 2218/6015 [11:00<14:38,  4.32it/s]

 37%|███▋      | 2219/6015 [11:00<14:38,  4.32it/s]

 37%|███▋      | 2220/6015 [11:00<14:36,  4.33it/s]

 37%|███▋      | 2221/6015 [11:01<14:35,  4.33it/s]

 37%|███▋      | 2222/6015 [11:01<14:34,  4.34it/s]

 37%|███▋      | 2223/6015 [11:01<14:37,  4.32it/s]

 37%|███▋      | 2224/6015 [11:01<14:36,  4.32it/s]

 37%|███▋      | 2225/6015 [11:02<14:35,  4.33it/s]

 37%|███▋      | 2226/6015 [11:02<14:35,  4.33it/s]

 37%|███▋      | 2227/6015 [11:02<14:35,  4.33it/s]

 37%|███▋      | 2228/6015 [11:02<14:37,  4.32it/s]

 37%|███▋      | 2229/6015 [11:03<14:39,  4.31it/s]

 37%|███▋      | 2230/6015 [11:03<14:40,  4.30it/s]

 37%|███▋      | 2231/6015 [11:03<14:40,  4.30it/s]

 37%|███▋      | 2232/6015 [11:03<14:40,  4.29it/s]

 37%|███▋      | 2233/6015 [11:03<14:37,  4.31it/s]

 37%|███▋      | 2234/6015 [11:04<14:36,  4.31it/s]

 37%|███▋      | 2235/6015 [11:04<14:37,  4.31it/s]

 37%|███▋      | 2236/6015 [11:04<14:36,  4.31it/s]

 37%|███▋      | 2237/6015 [11:04<14:35,  4.31it/s]

 37%|███▋      | 2238/6015 [11:05<14:36,  4.31it/s]

 37%|███▋      | 2239/6015 [11:05<14:37,  4.30it/s]

 37%|███▋      | 2240/6015 [11:05<14:35,  4.31it/s]

 37%|███▋      | 2241/6015 [11:05<14:35,  4.31it/s]

 37%|███▋      | 2242/6015 [11:06<14:35,  4.31it/s]

 37%|███▋      | 2243/6015 [11:06<14:36,  4.30it/s]

 37%|███▋      | 2244/6015 [11:06<14:35,  4.31it/s]

 37%|███▋      | 2245/6015 [11:06<14:34,  4.31it/s]

 37%|███▋      | 2246/6015 [11:06<14:36,  4.30it/s]

 37%|███▋      | 2247/6015 [11:07<14:35,  4.31it/s]

 37%|███▋      | 2248/6015 [11:07<14:32,  4.32it/s]

 37%|███▋      | 2249/6015 [11:07<14:31,  4.32it/s]

 37%|███▋      | 2250/6015 [11:07<14:29,  4.33it/s]

 37%|███▋      | 2251/6015 [11:08<14:30,  4.32it/s]

 37%|███▋      | 2252/6015 [11:08<14:29,  4.33it/s]

 37%|███▋      | 2253/6015 [11:08<14:31,  4.31it/s]

 37%|███▋      | 2254/6015 [11:08<14:32,  4.31it/s]

 37%|███▋      | 2255/6015 [11:09<14:31,  4.31it/s]

 38%|███▊      | 2256/6015 [11:09<14:31,  4.32it/s]

 38%|███▊      | 2257/6015 [11:09<14:31,  4.31it/s]

 38%|███▊      | 2258/6015 [11:09<14:29,  4.32it/s]

 38%|███▊      | 2259/6015 [11:10<14:31,  4.31it/s]

 38%|███▊      | 2260/6015 [11:10<14:29,  4.32it/s]

 38%|███▊      | 2261/6015 [11:10<14:30,  4.31it/s]

 38%|███▊      | 2262/6015 [11:10<14:31,  4.31it/s]

 38%|███▊      | 2263/6015 [11:10<14:29,  4.32it/s]

 38%|███▊      | 2264/6015 [11:11<14:28,  4.32it/s]

 38%|███▊      | 2265/6015 [11:11<14:28,  4.32it/s]

 38%|███▊      | 2266/6015 [11:11<14:28,  4.32it/s]

 38%|███▊      | 2267/6015 [11:11<14:27,  4.32it/s]

 38%|███▊      | 2268/6015 [11:12<14:27,  4.32it/s]

 38%|███▊      | 2269/6015 [11:12<14:28,  4.31it/s]

 38%|███▊      | 2270/6015 [11:12<14:28,  4.31it/s]

 38%|███▊      | 2271/6015 [11:12<14:27,  4.32it/s]

 38%|███▊      | 2272/6015 [11:13<14:26,  4.32it/s]

 38%|███▊      | 2273/6015 [11:13<14:26,  4.32it/s]

 38%|███▊      | 2274/6015 [11:13<14:27,  4.31it/s]

 38%|███▊      | 2275/6015 [11:13<14:29,  4.30it/s]

 38%|███▊      | 2276/6015 [11:13<14:28,  4.30it/s]

 38%|███▊      | 2277/6015 [11:14<14:28,  4.31it/s]

 38%|███▊      | 2278/6015 [11:14<14:30,  4.29it/s]

 38%|███▊      | 2279/6015 [11:14<14:28,  4.30it/s]

 38%|███▊      | 2280/6015 [11:14<14:28,  4.30it/s]

 38%|███▊      | 2281/6015 [11:15<14:26,  4.31it/s]

 38%|███▊      | 2282/6015 [11:15<14:26,  4.31it/s]

 38%|███▊      | 2283/6015 [11:15<14:28,  4.29it/s]

 38%|███▊      | 2284/6015 [11:15<14:27,  4.30it/s]

 38%|███▊      | 2285/6015 [11:16<14:27,  4.30it/s]

 38%|███▊      | 2286/6015 [11:16<14:25,  4.31it/s]

 38%|███▊      | 2287/6015 [11:16<14:25,  4.31it/s]

 38%|███▊      | 2288/6015 [11:16<14:28,  4.29it/s]

 38%|███▊      | 2289/6015 [11:16<14:25,  4.30it/s]

 38%|███▊      | 2290/6015 [11:17<14:26,  4.30it/s]

 38%|███▊      | 2291/6015 [11:17<14:25,  4.30it/s]

 38%|███▊      | 2292/6015 [11:17<14:27,  4.29it/s]

 38%|███▊      | 2293/6015 [11:17<14:28,  4.29it/s]

 38%|███▊      | 2294/6015 [11:18<14:26,  4.29it/s]

 38%|███▊      | 2295/6015 [11:18<14:24,  4.30it/s]

 38%|███▊      | 2296/6015 [11:18<14:24,  4.30it/s]

 38%|███▊      | 2297/6015 [11:18<14:24,  4.30it/s]

 38%|███▊      | 2298/6015 [11:19<14:24,  4.30it/s]

 38%|███▊      | 2299/6015 [11:19<14:23,  4.30it/s]

 38%|███▊      | 2300/6015 [11:19<14:24,  4.30it/s]

 38%|███▊      | 2301/6015 [11:19<14:23,  4.30it/s]

 38%|███▊      | 2302/6015 [11:19<14:21,  4.31it/s]

 38%|███▊      | 2303/6015 [11:20<14:22,  4.30it/s]

 38%|███▊      | 2304/6015 [11:20<14:22,  4.30it/s]

 38%|███▊      | 2305/6015 [11:20<14:22,  4.30it/s]

 38%|███▊      | 2306/6015 [11:20<14:20,  4.31it/s]

 38%|███▊      | 2307/6015 [11:21<14:20,  4.31it/s]

 38%|███▊      | 2308/6015 [11:21<14:22,  4.30it/s]

 38%|███▊      | 2309/6015 [11:21<14:22,  4.29it/s]

 38%|███▊      | 2310/6015 [11:21<14:24,  4.28it/s]

 38%|███▊      | 2311/6015 [11:22<14:23,  4.29it/s]

 38%|███▊      | 2312/6015 [11:22<14:21,  4.30it/s]

 38%|███▊      | 2313/6015 [11:22<14:21,  4.29it/s]

 38%|███▊      | 2314/6015 [11:22<14:20,  4.30it/s]

 38%|███▊      | 2315/6015 [11:23<14:17,  4.32it/s]

 39%|███▊      | 2316/6015 [11:23<14:18,  4.31it/s]

 39%|███▊      | 2317/6015 [11:23<14:22,  4.29it/s]

 39%|███▊      | 2318/6015 [11:23<14:20,  4.29it/s]

 39%|███▊      | 2319/6015 [11:23<14:19,  4.30it/s]

 39%|███▊      | 2320/6015 [11:24<14:16,  4.31it/s]

 39%|███▊      | 2321/6015 [11:24<14:17,  4.31it/s]

 39%|███▊      | 2322/6015 [11:24<14:17,  4.31it/s]

 39%|███▊      | 2323/6015 [11:24<14:19,  4.30it/s]

 39%|███▊      | 2324/6015 [11:25<14:19,  4.30it/s]

 39%|███▊      | 2325/6015 [11:25<14:18,  4.30it/s]

 39%|███▊      | 2326/6015 [11:25<14:17,  4.30it/s]

 39%|███▊      | 2327/6015 [11:25<14:20,  4.29it/s]

 39%|███▊      | 2328/6015 [11:26<14:17,  4.30it/s]

 39%|███▊      | 2329/6015 [11:26<14:15,  4.31it/s]

 39%|███▊      | 2330/6015 [11:26<14:14,  4.31it/s]

 39%|███▉      | 2331/6015 [11:26<14:16,  4.30it/s]

 39%|███▉      | 2332/6015 [11:26<14:16,  4.30it/s]

 39%|███▉      | 2333/6015 [11:27<14:15,  4.31it/s]

 39%|███▉      | 2334/6015 [11:27<14:13,  4.31it/s]

 39%|███▉      | 2335/6015 [11:27<14:14,  4.31it/s]

 39%|███▉      | 2336/6015 [11:27<14:14,  4.30it/s]

 39%|███▉      | 2337/6015 [11:28<14:16,  4.29it/s]

 39%|███▉      | 2338/6015 [11:28<14:16,  4.30it/s]

 39%|███▉      | 2339/6015 [11:28<14:14,  4.30it/s]

 39%|███▉      | 2340/6015 [11:28<14:13,  4.30it/s]

 39%|███▉      | 2341/6015 [11:29<14:14,  4.30it/s]

 39%|███▉      | 2342/6015 [11:29<14:13,  4.30it/s]

 39%|███▉      | 2343/6015 [11:29<14:12,  4.31it/s]

 39%|███▉      | 2344/6015 [11:29<14:14,  4.30it/s]

 39%|███▉      | 2345/6015 [11:29<14:16,  4.29it/s]

 39%|███▉      | 2346/6015 [11:30<14:14,  4.29it/s]

 39%|███▉      | 2347/6015 [11:30<14:14,  4.29it/s]

 39%|███▉      | 2348/6015 [11:30<14:14,  4.29it/s]

 39%|███▉      | 2349/6015 [11:30<14:17,  4.27it/s]

 39%|███▉      | 2350/6015 [11:31<14:16,  4.28it/s]

 39%|███▉      | 2351/6015 [11:31<14:15,  4.29it/s]

 39%|███▉      | 2352/6015 [11:31<14:14,  4.28it/s]

 39%|███▉      | 2353/6015 [11:31<14:13,  4.29it/s]

 39%|███▉      | 2354/6015 [11:32<14:13,  4.29it/s]

 39%|███▉      | 2355/6015 [11:32<14:13,  4.29it/s]

 39%|███▉      | 2356/6015 [11:32<14:14,  4.28it/s]

 39%|███▉      | 2357/6015 [11:32<14:13,  4.28it/s]

 39%|███▉      | 2358/6015 [11:33<14:12,  4.29it/s]

 39%|███▉      | 2359/6015 [11:33<14:11,  4.29it/s]

 39%|███▉      | 2360/6015 [11:33<14:12,  4.29it/s]

 39%|███▉      | 2361/6015 [11:33<14:11,  4.29it/s]

 39%|███▉      | 2362/6015 [11:33<14:13,  4.28it/s]

 39%|███▉      | 2363/6015 [11:34<14:13,  4.28it/s]

 39%|███▉      | 2364/6015 [11:34<14:13,  4.28it/s]

 39%|███▉      | 2365/6015 [11:34<14:11,  4.28it/s]

 39%|███▉      | 2366/6015 [11:34<14:14,  4.27it/s]

 39%|███▉      | 2367/6015 [11:35<14:12,  4.28it/s]

 39%|███▉      | 2368/6015 [11:35<14:14,  4.27it/s]

 39%|███▉      | 2369/6015 [11:35<14:11,  4.28it/s]

 39%|███▉      | 2370/6015 [11:35<14:13,  4.27it/s]

 39%|███▉      | 2371/6015 [11:36<14:15,  4.26it/s]

 39%|███▉      | 2372/6015 [11:36<14:12,  4.27it/s]

 39%|███▉      | 2373/6015 [11:36<14:10,  4.28it/s]

 39%|███▉      | 2374/6015 [11:36<14:09,  4.28it/s]

 39%|███▉      | 2375/6015 [11:37<14:11,  4.27it/s]

 40%|███▉      | 2376/6015 [11:37<14:15,  4.25it/s]

 40%|███▉      | 2377/6015 [11:37<14:12,  4.27it/s]

 40%|███▉      | 2378/6015 [11:37<14:12,  4.27it/s]

 40%|███▉      | 2379/6015 [11:37<14:10,  4.27it/s]

 40%|███▉      | 2380/6015 [11:38<14:08,  4.28it/s]

 40%|███▉      | 2381/6015 [11:38<14:11,  4.27it/s]

 40%|███▉      | 2382/6015 [11:38<14:11,  4.27it/s]

 40%|███▉      | 2383/6015 [11:38<14:09,  4.28it/s]

 40%|███▉      | 2384/6015 [11:39<14:07,  4.28it/s]

 40%|███▉      | 2385/6015 [11:39<14:06,  4.29it/s]

 40%|███▉      | 2386/6015 [11:39<14:06,  4.29it/s]

 40%|███▉      | 2387/6015 [11:39<14:05,  4.29it/s]

 40%|███▉      | 2388/6015 [11:40<14:04,  4.29it/s]

 40%|███▉      | 2389/6015 [11:40<14:05,  4.29it/s]

 40%|███▉      | 2390/6015 [11:40<14:05,  4.29it/s]

 40%|███▉      | 2391/6015 [11:40<14:04,  4.29it/s]

 40%|███▉      | 2392/6015 [11:40<14:02,  4.30it/s]

 40%|███▉      | 2393/6015 [11:41<14:02,  4.30it/s]

 40%|███▉      | 2394/6015 [11:41<14:04,  4.29it/s]

 40%|███▉      | 2395/6015 [11:41<14:05,  4.28it/s]

 40%|███▉      | 2396/6015 [11:41<14:05,  4.28it/s]

 40%|███▉      | 2397/6015 [11:42<14:04,  4.29it/s]

 40%|███▉      | 2398/6015 [11:42<14:05,  4.28it/s]

 40%|███▉      | 2399/6015 [11:42<14:07,  4.27it/s]

 40%|███▉      | 2400/6015 [11:42<14:07,  4.26it/s]

 40%|███▉      | 2401/6015 [11:43<14:09,  4.26it/s]

 40%|███▉      | 2402/6015 [11:43<14:07,  4.26it/s]

 40%|███▉      | 2403/6015 [11:43<14:07,  4.26it/s]

 40%|███▉      | 2404/6015 [11:43<14:06,  4.27it/s]

 40%|███▉      | 2405/6015 [11:44<14:10,  4.25it/s]

 40%|████      | 2406/6015 [11:44<14:09,  4.25it/s]

 40%|████      | 2407/6015 [11:44<14:07,  4.26it/s]

 40%|████      | 2408/6015 [11:44<14:07,  4.25it/s]

 40%|████      | 2409/6015 [11:44<14:07,  4.26it/s]

 40%|████      | 2410/6015 [11:45<14:07,  4.25it/s]

 40%|████      | 2411/6015 [11:45<14:05,  4.26it/s]

 40%|████      | 2412/6015 [11:45<14:05,  4.26it/s]

 40%|████      | 2413/6015 [11:45<14:05,  4.26it/s]

 40%|████      | 2414/6015 [11:46<14:07,  4.25it/s]

 40%|████      | 2415/6015 [11:46<14:06,  4.25it/s]

 40%|████      | 2416/6015 [11:46<14:06,  4.25it/s]

 40%|████      | 2417/6015 [11:46<14:06,  4.25it/s]

 40%|████      | 2418/6015 [11:47<14:04,  4.26it/s]

 40%|████      | 2419/6015 [11:47<14:05,  4.26it/s]

 40%|████      | 2420/6015 [11:47<14:06,  4.25it/s]

 40%|████      | 2421/6015 [11:47<14:06,  4.25it/s]

 40%|████      | 2422/6015 [11:48<14:03,  4.26it/s]

 40%|████      | 2423/6015 [11:48<14:03,  4.26it/s]

 40%|████      | 2424/6015 [11:48<14:04,  4.25it/s]

 40%|████      | 2425/6015 [11:48<14:05,  4.25it/s]

 40%|████      | 2426/6015 [11:48<14:05,  4.25it/s]

 40%|████      | 2427/6015 [11:49<14:03,  4.25it/s]

 40%|████      | 2428/6015 [11:49<14:01,  4.26it/s]

 40%|████      | 2429/6015 [11:49<14:00,  4.27it/s]

 40%|████      | 2430/6015 [11:49<14:00,  4.27it/s]

 40%|████      | 2431/6015 [11:50<14:01,  4.26it/s]

 40%|████      | 2432/6015 [11:50<14:00,  4.26it/s]

 40%|████      | 2433/6015 [11:50<14:02,  4.25it/s]

 40%|████      | 2434/6015 [11:50<14:04,  4.24it/s]

 40%|████      | 2435/6015 [11:51<14:02,  4.25it/s]

 40%|████      | 2436/6015 [11:51<14:01,  4.26it/s]

 41%|████      | 2437/6015 [11:51<14:00,  4.26it/s]

 41%|████      | 2438/6015 [11:51<14:03,  4.24it/s]

 41%|████      | 2439/6015 [11:52<14:06,  4.23it/s]

 41%|████      | 2440/6015 [11:52<14:04,  4.23it/s]

 41%|████      | 2441/6015 [11:52<14:04,  4.23it/s]

 41%|████      | 2442/6015 [11:52<14:04,  4.23it/s]

 41%|████      | 2443/6015 [11:52<14:03,  4.24it/s]

 41%|████      | 2444/6015 [11:53<14:01,  4.24it/s]

 41%|████      | 2445/6015 [11:53<14:02,  4.24it/s]

 41%|████      | 2446/6015 [11:53<14:02,  4.24it/s]

 41%|████      | 2447/6015 [11:53<14:00,  4.25it/s]

 41%|████      | 2448/6015 [11:54<13:59,  4.25it/s]

 41%|████      | 2449/6015 [11:54<14:00,  4.24it/s]

 41%|████      | 2450/6015 [11:54<13:57,  4.26it/s]

 41%|████      | 2451/6015 [11:54<13:58,  4.25it/s]

 41%|████      | 2452/6015 [11:55<13:57,  4.25it/s]

 41%|████      | 2453/6015 [11:55<13:55,  4.26it/s]

 41%|████      | 2454/6015 [11:55<13:55,  4.26it/s]

 41%|████      | 2455/6015 [11:55<13:55,  4.26it/s]

 41%|████      | 2456/6015 [11:56<13:56,  4.25it/s]

 41%|████      | 2457/6015 [11:56<13:55,  4.26it/s]

 41%|████      | 2458/6015 [11:56<13:56,  4.25it/s]

 41%|████      | 2459/6015 [11:56<13:57,  4.25it/s]

 41%|████      | 2460/6015 [11:56<13:55,  4.25it/s]

 41%|████      | 2461/6015 [11:57<13:53,  4.26it/s]

 41%|████      | 2462/6015 [11:57<13:53,  4.26it/s]

 41%|████      | 2463/6015 [11:57<13:54,  4.26it/s]

 41%|████      | 2464/6015 [11:57<13:58,  4.24it/s]

 41%|████      | 2465/6015 [11:58<13:57,  4.24it/s]

 41%|████      | 2466/6015 [11:58<13:58,  4.23it/s]

 41%|████      | 2467/6015 [11:58<13:56,  4.24it/s]

 41%|████      | 2468/6015 [11:58<13:54,  4.25it/s]

 41%|████      | 2469/6015 [11:59<13:53,  4.25it/s]

 41%|████      | 2470/6015 [11:59<13:53,  4.25it/s]

 41%|████      | 2471/6015 [11:59<13:53,  4.25it/s]

 41%|████      | 2472/6015 [11:59<13:51,  4.26it/s]

 41%|████      | 2473/6015 [12:00<13:52,  4.26it/s]

 41%|████      | 2474/6015 [12:00<13:51,  4.26it/s]

 41%|████      | 2475/6015 [12:00<13:50,  4.26it/s]

 41%|████      | 2476/6015 [12:00<13:49,  4.27it/s]

 41%|████      | 2477/6015 [12:00<13:51,  4.26it/s]

 41%|████      | 2478/6015 [12:01<13:50,  4.26it/s]

 41%|████      | 2479/6015 [12:01<13:49,  4.26it/s]

 41%|████      | 2480/6015 [12:01<13:50,  4.26it/s]

 41%|████      | 2481/6015 [12:01<13:52,  4.25it/s]

 41%|████▏     | 2482/6015 [12:02<13:49,  4.26it/s]

 41%|████▏     | 2483/6015 [12:02<13:50,  4.25it/s]

 41%|████▏     | 2484/6015 [12:02<13:51,  4.25it/s]

 41%|████▏     | 2485/6015 [12:02<13:52,  4.24it/s]

 41%|████▏     | 2486/6015 [12:03<13:52,  4.24it/s]

 41%|████▏     | 2487/6015 [12:03<13:50,  4.25it/s]

 41%|████▏     | 2488/6015 [12:03<13:50,  4.25it/s]

 41%|████▏     | 2489/6015 [12:03<13:50,  4.25it/s]

 41%|████▏     | 2490/6015 [12:04<13:50,  4.24it/s]

 41%|████▏     | 2491/6015 [12:04<13:52,  4.23it/s]

 41%|████▏     | 2492/6015 [12:04<13:50,  4.24it/s]

 41%|████▏     | 2493/6015 [12:04<13:51,  4.24it/s]

 41%|████▏     | 2494/6015 [12:04<13:50,  4.24it/s]

 41%|████▏     | 2495/6015 [12:05<13:49,  4.24it/s]

 41%|████▏     | 2496/6015 [12:05<13:48,  4.25it/s]

 42%|████▏     | 2497/6015 [12:05<13:47,  4.25it/s]

 42%|████▏     | 2498/6015 [12:05<13:48,  4.24it/s]

 42%|████▏     | 2499/6015 [12:06<13:48,  4.24it/s]

 42%|████▏     | 2500/6015 [12:06<13:47,  4.25it/s]

 42%|████▏     | 2501/6015 [12:06<13:48,  4.24it/s]

 42%|████▏     | 2502/6015 [12:06<13:47,  4.25it/s]

 42%|████▏     | 2503/6015 [12:07<13:46,  4.25it/s]

logging
logging the anndata

 42%|████▏     | 2504/6015 [16:04<69:35:17, 71.35s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 42%|████▏     | 2505/6015 [16:04<48:46:16, 50.02s/it]

 42%|████▏     | 2506/6015 [16:04<34:11:51, 35.08s/it]

 42%|████▏     | 2507/6015 [16:05<23:59:51, 24.63s/it]

 42%|████▏     | 2508/6015 [16:05<16:51:34, 17.31s/it]

 42%|████▏     | 2509/6015 [16:05<11:51:51, 12.18s/it]

 42%|████▏     | 2510/6015 [16:05<8:22:12,  8.60s/it]

 42%|████▏     | 2511/6015 [16:05<5:55:23,  6.09s/it]

 42%|████▏     | 2512/6015 [16:06<4:12:41,  4.33s/it]

 42%|████▏     | 2513/6015 [16:06<3:00:47,  3.10s/it]

 42%|████▏     | 2514/6015 [16:06<2:10:26,  2.24s/it]

 42%|████▏     | 2515/6015 [16:06<1:35:13,  1.63s/it]

 42%|████▏     | 2516/6015 [16:07<1:10:35,  1.21s/it]

 42%|████▏     | 2517/6015 [16:07<53:22,  1.09it/s]

 42%|████▏     | 2518/6015 [16:07<41:19,  1.41it/s]

 42%|████▏     | 2519/6015 [16:07<32:51,  1.77it/s]

 42%|████▏     | 2520/6015 [16:08<26:59,  2.16it/s]

 42%|████▏     | 2521/6015 [16:08<22:50,  2.55it/s]

 42%|████▏     | 2522/6015 [16:08<19:54,  2.92it/s]

 42%|████▏     | 2523/6015 [16:08<17:52,  3.26it/s]

 42%|████▏     | 2524/6015 [16:08<16:26,  3.54it/s]

 42%|████▏     | 2525/6015 [16:09<15:25,  3.77it/s]

 42%|████▏     | 2526/6015 [16:09<14:43,  3.95it/s]

 42%|████▏     | 2527/6015 [16:09<14:14,  4.08it/s]

 42%|████▏     | 2528/6015 [16:09<13:54,  4.18it/s]

 42%|████▏     | 2529/6015 [16:10<13:40,  4.25it/s]

 42%|████▏     | 2530/6015 [16:10<13:30,  4.30it/s]

 42%|████▏     | 2531/6015 [16:10<13:22,  4.34it/s]

 42%|████▏     | 2532/6015 [16:10<13:17,  4.37it/s]

 42%|████▏     | 2533/6015 [16:10<13:13,  4.39it/s]

 42%|████▏     | 2534/6015 [16:11<13:11,  4.40it/s]

 42%|████▏     | 2535/6015 [16:11<13:10,  4.40it/s]

 42%|████▏     | 2536/6015 [16:11<13:08,  4.41it/s]

 42%|████▏     | 2537/6015 [16:11<13:09,  4.41it/s]

 42%|████▏     | 2538/6015 [16:12<13:09,  4.41it/s]

 42%|████▏     | 2539/6015 [16:12<13:08,  4.41it/s]

 42%|████▏     | 2540/6015 [16:12<13:08,  4.41it/s]

 42%|████▏     | 2541/6015 [16:12<13:09,  4.40it/s]

 42%|████▏     | 2542/6015 [16:12<13:07,  4.41it/s]

 42%|████▏     | 2543/6015 [16:13<13:06,  4.41it/s]

 42%|████▏     | 2544/6015 [16:13<13:06,  4.41it/s]

 42%|████▏     | 2545/6015 [16:13<13:05,  4.42it/s]

 42%|████▏     | 2546/6015 [16:13<13:04,  4.42it/s]

 42%|████▏     | 2547/6015 [16:14<13:05,  4.41it/s]

 42%|████▏     | 2548/6015 [16:14<13:04,  4.42it/s]

 42%|████▏     | 2549/6015 [16:14<13:05,  4.41it/s]

 42%|████▏     | 2550/6015 [16:14<13:10,  4.38it/s]

 42%|████▏     | 2551/6015 [16:15<13:06,  4.40it/s]

 42%|████▏     | 2552/6015 [16:15<13:06,  4.41it/s]

 42%|████▏     | 2553/6015 [16:15<13:05,  4.41it/s]

 42%|████▏     | 2554/6015 [16:15<13:05,  4.41it/s]

 42%|████▏     | 2555/6015 [16:15<13:05,  4.40it/s]

 42%|████▏     | 2556/6015 [16:16<13:04,  4.41it/s]

 43%|████▎     | 2557/6015 [16:16<13:04,  4.41it/s]

 43%|████▎     | 2558/6015 [16:16<13:05,  4.40it/s]

 43%|████▎     | 2559/6015 [16:16<13:02,  4.41it/s]

 43%|████▎     | 2560/6015 [16:17<13:02,  4.41it/s]

 43%|████▎     | 2561/6015 [16:17<13:03,  4.41it/s]

 43%|████▎     | 2562/6015 [16:17<13:06,  4.39it/s]

 43%|████▎     | 2563/6015 [16:17<13:05,  4.40it/s]

 43%|████▎     | 2564/6015 [16:17<13:05,  4.40it/s]

 43%|████▎     | 2565/6015 [16:18<13:03,  4.40it/s]

 43%|████▎     | 2566/6015 [16:18<13:03,  4.40it/s]

 43%|████▎     | 2567/6015 [16:18<13:04,  4.40it/s]

 43%|████▎     | 2568/6015 [16:18<13:03,  4.40it/s]

 43%|████▎     | 2569/6015 [16:19<13:03,  4.40it/s]

 43%|████▎     | 2570/6015 [16:19<13:02,  4.41it/s]

 43%|████▎     | 2571/6015 [16:19<13:04,  4.39it/s]

 43%|████▎     | 2572/6015 [16:19<13:03,  4.40it/s]

 43%|████▎     | 2573/6015 [16:20<13:03,  4.39it/s]

 43%|████▎     | 2574/6015 [16:20<13:02,  4.40it/s]

 43%|████▎     | 2575/6015 [16:20<13:02,  4.40it/s]

 43%|████▎     | 2576/6015 [16:20<13:01,  4.40it/s]

 43%|████▎     | 2577/6015 [16:20<13:03,  4.39it/s]

 43%|████▎     | 2578/6015 [16:21<13:04,  4.38it/s]

 43%|████▎     | 2579/6015 [16:21<13:02,  4.39it/s]

 43%|████▎     | 2580/6015 [16:21<13:02,  4.39it/s]

 43%|████▎     | 2581/6015 [16:21<13:02,  4.39it/s]

 43%|████▎     | 2582/6015 [16:22<13:01,  4.39it/s]

 43%|████▎     | 2583/6015 [16:22<13:01,  4.39it/s]

 43%|████▎     | 2584/6015 [16:22<13:02,  4.39it/s]

 43%|████▎     | 2585/6015 [16:22<13:01,  4.39it/s]

 43%|████▎     | 2586/6015 [16:22<13:00,  4.39it/s]

 43%|████▎     | 2587/6015 [16:23<13:02,  4.38it/s]

 43%|████▎     | 2588/6015 [16:23<13:01,  4.38it/s]

 43%|████▎     | 2589/6015 [16:23<13:00,  4.39it/s]

 43%|████▎     | 2590/6015 [16:23<12:57,  4.40it/s]

 43%|████▎     | 2591/6015 [16:24<12:57,  4.40it/s]

 43%|████▎     | 2592/6015 [16:24<12:57,  4.40it/s]

 43%|████▎     | 2593/6015 [16:24<12:55,  4.41it/s]

 43%|████▎     | 2594/6015 [16:24<12:58,  4.40it/s]

 43%|████▎     | 2595/6015 [16:25<12:59,  4.39it/s]

 43%|████▎     | 2596/6015 [16:25<12:58,  4.39it/s]

 43%|████▎     | 2597/6015 [16:25<12:57,  4.40it/s]

 43%|████▎     | 2598/6015 [16:25<12:58,  4.39it/s]

 43%|████▎     | 2599/6015 [16:25<12:56,  4.40it/s]

 43%|████▎     | 2600/6015 [16:26<12:56,  4.40it/s]

 43%|████▎     | 2601/6015 [16:26<12:59,  4.38it/s]

 43%|████▎     | 2602/6015 [16:26<12:58,  4.38it/s]

 43%|████▎     | 2603/6015 [16:26<12:57,  4.39it/s]

 43%|████▎     | 2604/6015 [16:27<12:54,  4.40it/s]

 43%|████▎     | 2605/6015 [16:27<12:54,  4.40it/s]

 43%|████▎     | 2606/6015 [16:27<12:54,  4.40it/s]

 43%|████▎     | 2607/6015 [16:27<12:55,  4.40it/s]

 43%|████▎     | 2608/6015 [16:28<12:58,  4.38it/s]

 43%|████▎     | 2609/6015 [16:28<12:57,  4.38it/s]

 43%|████▎     | 2610/6015 [16:28<12:56,  4.39it/s]

 43%|████▎     | 2611/6015 [16:28<12:56,  4.38it/s]

 43%|████▎     | 2612/6015 [16:28<12:55,  4.39it/s]

 43%|████▎     | 2613/6015 [16:29<12:55,  4.38it/s]

 43%|████▎     | 2614/6015 [16:29<12:55,  4.38it/s]

 43%|████▎     | 2615/6015 [16:29<12:54,  4.39it/s]

 43%|████▎     | 2616/6015 [16:29<12:54,  4.39it/s]

 44%|████▎     | 2617/6015 [16:30<12:53,  4.39it/s]

 44%|████▎     | 2618/6015 [16:30<12:52,  4.39it/s]

 44%|████▎     | 2619/6015 [16:30<12:53,  4.39it/s]

 44%|████▎     | 2620/6015 [16:30<12:53,  4.39it/s]

 44%|████▎     | 2621/6015 [16:30<12:52,  4.39it/s]

 44%|████▎     | 2622/6015 [16:31<12:54,  4.38it/s]

 44%|████▎     | 2623/6015 [16:31<12:54,  4.38it/s]

 44%|████▎     | 2624/6015 [16:31<12:54,  4.38it/s]

 44%|████▎     | 2625/6015 [16:31<12:55,  4.37it/s]

 44%|████▎     | 2626/6015 [16:32<12:54,  4.37it/s]

 44%|████▎     | 2627/6015 [16:32<12:53,  4.38it/s]

 44%|████▎     | 2628/6015 [16:32<12:52,  4.38it/s]

 44%|████▎     | 2629/6015 [16:32<12:51,  4.39it/s]

 44%|████▎     | 2630/6015 [16:33<12:52,  4.38it/s]

 44%|████▎     | 2631/6015 [16:33<12:51,  4.39it/s]

 44%|████▍     | 2632/6015 [16:33<12:50,  4.39it/s]

 44%|████▍     | 2633/6015 [16:33<12:50,  4.39it/s]

 44%|████▍     | 2634/6015 [16:33<12:51,  4.38it/s]

 44%|████▍     | 2635/6015 [16:34<12:48,  4.40it/s]

 44%|████▍     | 2636/6015 [16:34<12:48,  4.40it/s]

 44%|████▍     | 2637/6015 [16:34<12:49,  4.39it/s]

 44%|████▍     | 2638/6015 [16:34<12:49,  4.39it/s]

 44%|████▍     | 2639/6015 [16:35<12:51,  4.38it/s]

 44%|████▍     | 2640/6015 [16:35<12:50,  4.38it/s]

 44%|████▍     | 2641/6015 [16:35<12:56,  4.35it/s]

 44%|████▍     | 2642/6015 [16:35<12:54,  4.36it/s]

 44%|████▍     | 2643/6015 [16:35<12:52,  4.37it/s]

 44%|████▍     | 2644/6015 [16:36<12:51,  4.37it/s]

 44%|████▍     | 2645/6015 [16:36<12:51,  4.37it/s]

 44%|████▍     | 2646/6015 [16:36<12:49,  4.38it/s]

 44%|████▍     | 2647/6015 [16:36<12:49,  4.37it/s]

 44%|████▍     | 2648/6015 [16:37<12:51,  4.36it/s]

 44%|████▍     | 2649/6015 [16:37<12:50,  4.37it/s]

 44%|████▍     | 2650/6015 [16:37<12:49,  4.37it/s]

 44%|████▍     | 2651/6015 [16:37<12:49,  4.37it/s]

 44%|████▍     | 2652/6015 [16:38<12:49,  4.37it/s]

 44%|████▍     | 2653/6015 [16:38<12:48,  4.37it/s]

 44%|████▍     | 2654/6015 [16:38<12:48,  4.38it/s]

 44%|████▍     | 2655/6015 [16:38<12:46,  4.38it/s]

 44%|████▍     | 2656/6015 [16:38<12:48,  4.37it/s]

 44%|████▍     | 2657/6015 [16:39<12:49,  4.36it/s]

 44%|████▍     | 2658/6015 [16:39<12:49,  4.36it/s]

 44%|████▍     | 2659/6015 [16:39<12:48,  4.37it/s]

 44%|████▍     | 2660/6015 [16:39<12:47,  4.37it/s]

 44%|████▍     | 2661/6015 [16:40<12:46,  4.38it/s]

 44%|████▍     | 2662/6015 [16:40<12:46,  4.37it/s]

 44%|████▍     | 2663/6015 [16:40<12:46,  4.37it/s]

 44%|████▍     | 2664/6015 [16:40<12:46,  4.37it/s]

 44%|████▍     | 2665/6015 [16:41<12:45,  4.38it/s]

 44%|████▍     | 2666/6015 [16:41<12:45,  4.38it/s]

 44%|████▍     | 2667/6015 [16:41<12:45,  4.38it/s]

 44%|████▍     | 2668/6015 [16:41<12:45,  4.37it/s]

 44%|████▍     | 2669/6015 [16:41<12:46,  4.36it/s]

 44%|████▍     | 2670/6015 [16:42<12:45,  4.37it/s]

 44%|████▍     | 2671/6015 [16:42<12:45,  4.37it/s]

 44%|████▍     | 2672/6015 [16:42<12:48,  4.35it/s]

 44%|████▍     | 2673/6015 [16:42<12:46,  4.36it/s]

 44%|████▍     | 2674/6015 [16:43<12:46,  4.36it/s]

 44%|████▍     | 2675/6015 [16:43<12:43,  4.37it/s]

 44%|████▍     | 2676/6015 [16:43<12:42,  4.38it/s]

 45%|████▍     | 2677/6015 [16:43<12:43,  4.37it/s]

 45%|████▍     | 2678/6015 [16:43<12:42,  4.38it/s]

 45%|████▍     | 2679/6015 [16:44<12:42,  4.38it/s]

 45%|████▍     | 2680/6015 [16:44<12:43,  4.37it/s]

 45%|████▍     | 2681/6015 [16:44<12:41,  4.38it/s]

 45%|████▍     | 2682/6015 [16:44<12:41,  4.38it/s]

 45%|████▍     | 2683/6015 [16:45<12:41,  4.37it/s]

 45%|████▍     | 2684/6015 [16:45<12:43,  4.36it/s]

 45%|████▍     | 2685/6015 [16:45<12:43,  4.36it/s]

 45%|████▍     | 2686/6015 [16:45<12:43,  4.36it/s]

 45%|████▍     | 2687/6015 [16:46<12:42,  4.37it/s]

 45%|████▍     | 2688/6015 [16:46<12:42,  4.37it/s]

 45%|████▍     | 2689/6015 [16:46<12:39,  4.38it/s]

 45%|████▍     | 2690/6015 [16:46<12:38,  4.38it/s]

 45%|████▍     | 2691/6015 [16:46<12:39,  4.38it/s]

 45%|████▍     | 2692/6015 [16:47<12:38,  4.38it/s]

 45%|████▍     | 2693/6015 [16:47<12:37,  4.38it/s]

 45%|████▍     | 2694/6015 [16:47<12:38,  4.38it/s]

 45%|████▍     | 2695/6015 [16:47<12:38,  4.38it/s]

 45%|████▍     | 2696/6015 [16:48<12:38,  4.38it/s]

 45%|████▍     | 2697/6015 [16:48<12:38,  4.37it/s]

 45%|████▍     | 2698/6015 [16:48<12:37,  4.38it/s]

 45%|████▍     | 2699/6015 [16:48<12:38,  4.37it/s]

 45%|████▍     | 2700/6015 [16:49<12:38,  4.37it/s]

 45%|████▍     | 2701/6015 [16:49<12:39,  4.37it/s]

 45%|████▍     | 2702/6015 [16:49<12:39,  4.36it/s]

 45%|████▍     | 2703/6015 [16:49<12:37,  4.37it/s]

 45%|████▍     | 2704/6015 [16:49<12:37,  4.37it/s]

 45%|████▍     | 2705/6015 [16:50<12:37,  4.37it/s]

 45%|████▍     | 2706/6015 [16:50<12:37,  4.37it/s]

 45%|████▌     | 2707/6015 [16:50<12:38,  4.36it/s]

 45%|████▌     | 2708/6015 [16:50<12:36,  4.37it/s]

 45%|████▌     | 2709/6015 [16:51<12:35,  4.37it/s]

 45%|████▌     | 2710/6015 [16:51<12:35,  4.37it/s]

 45%|████▌     | 2711/6015 [16:51<12:35,  4.37it/s]

 45%|████▌     | 2712/6015 [16:51<12:37,  4.36it/s]

 45%|████▌     | 2713/6015 [16:52<12:36,  4.36it/s]

 45%|████▌     | 2714/6015 [16:52<12:36,  4.37it/s]

 45%|████▌     | 2715/6015 [16:52<12:37,  4.35it/s]

 45%|████▌     | 2716/6015 [16:52<12:39,  4.34it/s]

 45%|████▌     | 2717/6015 [16:52<12:37,  4.35it/s]

 45%|████▌     | 2718/6015 [16:53<12:38,  4.35it/s]

 45%|████▌     | 2719/6015 [16:53<12:35,  4.36it/s]

 45%|████▌     | 2720/6015 [16:53<12:34,  4.37it/s]

 45%|████▌     | 2721/6015 [16:53<12:35,  4.36it/s]

 45%|████▌     | 2722/6015 [16:54<12:32,  4.37it/s]

 45%|████▌     | 2723/6015 [16:54<12:31,  4.38it/s]

 45%|████▌     | 2724/6015 [16:54<12:32,  4.37it/s]

 45%|████▌     | 2725/6015 [16:54<12:31,  4.38it/s]

 45%|████▌     | 2726/6015 [16:54<12:31,  4.37it/s]

 45%|████▌     | 2727/6015 [16:55<12:33,  4.37it/s]

 45%|████▌     | 2728/6015 [16:55<12:32,  4.37it/s]

 45%|████▌     | 2729/6015 [16:55<12:33,  4.36it/s]

 45%|████▌     | 2730/6015 [16:55<12:32,  4.36it/s]

 45%|████▌     | 2731/6015 [16:56<12:32,  4.36it/s]

 45%|████▌     | 2732/6015 [16:56<12:33,  4.36it/s]

 45%|████▌     | 2733/6015 [16:56<12:32,  4.36it/s]

 45%|████▌     | 2734/6015 [16:56<12:31,  4.37it/s]

 45%|████▌     | 2735/6015 [16:57<12:31,  4.36it/s]

 45%|████▌     | 2736/6015 [16:57<12:31,  4.37it/s]

 46%|████▌     | 2737/6015 [16:57<12:33,  4.35it/s]

 46%|████▌     | 2738/6015 [16:57<12:32,  4.35it/s]

 46%|████▌     | 2739/6015 [16:57<12:33,  4.35it/s]

 46%|████▌     | 2740/6015 [16:58<12:31,  4.36it/s]

 46%|████▌     | 2741/6015 [16:58<12:30,  4.36it/s]

 46%|████▌     | 2742/6015 [16:58<12:29,  4.37it/s]

 46%|████▌     | 2743/6015 [16:58<12:29,  4.36it/s]

 46%|████▌     | 2744/6015 [16:59<12:29,  4.36it/s]

 46%|████▌     | 2745/6015 [16:59<12:29,  4.36it/s]

 46%|████▌     | 2746/6015 [16:59<12:28,  4.37it/s]

 46%|████▌     | 2747/6015 [16:59<12:28,  4.37it/s]

 46%|████▌     | 2748/6015 [17:00<12:28,  4.37it/s]

 46%|████▌     | 2749/6015 [17:00<12:28,  4.36it/s]

 46%|████▌     | 2750/6015 [17:00<12:27,  4.37it/s]

 46%|████▌     | 2751/6015 [17:00<12:27,  4.37it/s]

 46%|████▌     | 2752/6015 [17:00<12:26,  4.37it/s]

 46%|████▌     | 2753/6015 [17:01<12:25,  4.37it/s]

 46%|████▌     | 2754/6015 [17:01<12:26,  4.37it/s]

 46%|████▌     | 2755/6015 [17:01<12:25,  4.38it/s]

 46%|████▌     | 2756/6015 [17:01<12:24,  4.37it/s]

 46%|████▌     | 2757/6015 [17:02<12:26,  4.37it/s]

 46%|████▌     | 2758/6015 [17:02<12:25,  4.37it/s]

 46%|████▌     | 2759/6015 [17:02<12:25,  4.37it/s]

 46%|████▌     | 2760/6015 [17:02<12:26,  4.36it/s]

 46%|████▌     | 2761/6015 [17:02<12:25,  4.37it/s]

 46%|████▌     | 2762/6015 [17:03<12:25,  4.36it/s]

 46%|████▌     | 2763/6015 [17:03<12:24,  4.37it/s]

 46%|████▌     | 2764/6015 [17:03<12:23,  4.37it/s]

 46%|████▌     | 2765/6015 [17:03<12:21,  4.38it/s]

 46%|████▌     | 2766/6015 [17:04<12:20,  4.39it/s]

 46%|████▌     | 2767/6015 [17:04<12:19,  4.39it/s]

 46%|████▌     | 2768/6015 [17:04<12:20,  4.38it/s]

 46%|████▌     | 2769/6015 [17:04<12:19,  4.39it/s]

 46%|████▌     | 2770/6015 [17:05<12:21,  4.37it/s]

 46%|████▌     | 2771/6015 [17:05<12:23,  4.37it/s]

 46%|████▌     | 2772/6015 [17:05<12:23,  4.36it/s]

 46%|████▌     | 2773/6015 [17:05<12:24,  4.35it/s]

 46%|████▌     | 2774/6015 [17:05<12:23,  4.36it/s]

 46%|████▌     | 2775/6015 [17:06<12:22,  4.37it/s]

 46%|████▌     | 2776/6015 [17:06<12:23,  4.36it/s]

 46%|████▌     | 2777/6015 [17:06<12:23,  4.35it/s]

 46%|████▌     | 2778/6015 [17:06<12:21,  4.36it/s]

 46%|████▌     | 2779/6015 [17:07<12:22,  4.36it/s]

 46%|████▌     | 2780/6015 [17:07<12:22,  4.36it/s]

 46%|████▌     | 2781/6015 [17:07<12:22,  4.36it/s]

 46%|████▋     | 2782/6015 [17:07<12:21,  4.36it/s]

 46%|████▋     | 2783/6015 [17:08<12:23,  4.34it/s]

 46%|████▋     | 2784/6015 [17:08<12:23,  4.34it/s]

 46%|████▋     | 2785/6015 [17:08<12:22,  4.35it/s]

 46%|████▋     | 2786/6015 [17:08<12:22,  4.35it/s]

 46%|████▋     | 2787/6015 [17:08<12:21,  4.35it/s]

 46%|████▋     | 2788/6015 [17:09<12:20,  4.36it/s]

 46%|████▋     | 2789/6015 [17:09<12:20,  4.36it/s]

 46%|████▋     | 2790/6015 [17:09<12:21,  4.35it/s]

 46%|████▋     | 2791/6015 [17:09<12:19,  4.36it/s]

 46%|████▋     | 2792/6015 [17:10<12:19,  4.36it/s]

 46%|████▋     | 2793/6015 [17:10<12:19,  4.35it/s]

 46%|████▋     | 2794/6015 [17:10<12:19,  4.36it/s]

 46%|████▋     | 2795/6015 [17:10<12:18,  4.36it/s]

 46%|████▋     | 2796/6015 [17:11<12:19,  4.35it/s]

 47%|████▋     | 2797/6015 [17:11<12:19,  4.35it/s]

 47%|████▋     | 2798/6015 [17:11<12:19,  4.35it/s]

 47%|████▋     | 2799/6015 [17:11<12:19,  4.35it/s]

 47%|████▋     | 2800/6015 [17:11<12:20,  4.34it/s]

 47%|████▋     | 2801/6015 [17:12<12:18,  4.35it/s]

 47%|████▋     | 2802/6015 [17:12<12:20,  4.34it/s]

 47%|████▋     | 2803/6015 [17:12<12:19,  4.34it/s]

 47%|████▋     | 2804/6015 [17:12<12:17,  4.35it/s]

 47%|████▋     | 2805/6015 [17:13<12:17,  4.35it/s]

 47%|████▋     | 2806/6015 [17:13<12:16,  4.35it/s]

 47%|████▋     | 2807/6015 [17:13<12:15,  4.36it/s]

 47%|████▋     | 2808/6015 [17:13<12:14,  4.37it/s]

 47%|████▋     | 2809/6015 [17:14<12:13,  4.37it/s]

 47%|████▋     | 2810/6015 [17:14<12:14,  4.36it/s]

 47%|████▋     | 2811/6015 [17:14<12:14,  4.36it/s]

 47%|████▋     | 2812/6015 [17:14<12:13,  4.37it/s]

 47%|████▋     | 2813/6015 [17:14<12:12,  4.37it/s]

 47%|████▋     | 2814/6015 [17:15<12:13,  4.37it/s]

 47%|████▋     | 2815/6015 [17:15<12:11,  4.37it/s]

 47%|████▋     | 2816/6015 [17:15<12:11,  4.37it/s]

 47%|████▋     | 2817/6015 [17:15<12:12,  4.37it/s]

 47%|████▋     | 2818/6015 [17:16<12:10,  4.38it/s]

 47%|████▋     | 2819/6015 [17:16<12:09,  4.38it/s]

 47%|████▋     | 2820/6015 [17:16<12:09,  4.38it/s]

 47%|████▋     | 2821/6015 [17:16<12:10,  4.37it/s]

 47%|████▋     | 2822/6015 [17:16<12:12,  4.36it/s]

 47%|████▋     | 2823/6015 [17:17<12:10,  4.37it/s]

 47%|████▋     | 2824/6015 [17:17<12:10,  4.37it/s]

 47%|████▋     | 2825/6015 [17:17<12:11,  4.36it/s]

 47%|████▋     | 2826/6015 [17:17<12:10,  4.36it/s]

 47%|████▋     | 2827/6015 [17:18<12:11,  4.36it/s]

 47%|████▋     | 2828/6015 [17:18<12:10,  4.36it/s]

 47%|████▋     | 2829/6015 [17:18<12:13,  4.34it/s]

 47%|████▋     | 2830/6015 [17:18<12:13,  4.34it/s]

 47%|████▋     | 2831/6015 [17:19<12:11,  4.35it/s]

 47%|████▋     | 2832/6015 [17:19<12:11,  4.35it/s]

 47%|████▋     | 2833/6015 [17:19<12:13,  4.34it/s]

 47%|████▋     | 2834/6015 [17:19<12:11,  4.35it/s]

 47%|████▋     | 2835/6015 [17:19<12:10,  4.35it/s]

 47%|████▋     | 2836/6015 [17:20<12:11,  4.35it/s]

 47%|████▋     | 2837/6015 [17:20<12:11,  4.34it/s]

 47%|████▋     | 2838/6015 [17:20<12:10,  4.35it/s]

 47%|████▋     | 2839/6015 [17:20<12:08,  4.36it/s]

 47%|████▋     | 2840/6015 [17:21<12:08,  4.36it/s]

 47%|████▋     | 2841/6015 [17:21<12:08,  4.35it/s]

 47%|████▋     | 2842/6015 [17:21<12:08,  4.35it/s]

 47%|████▋     | 2843/6015 [17:21<12:09,  4.35it/s]

 47%|████▋     | 2844/6015 [17:22<12:10,  4.34it/s]

 47%|████▋     | 2845/6015 [17:22<12:08,  4.35it/s]

 47%|████▋     | 2846/6015 [17:22<12:07,  4.36it/s]

 47%|████▋     | 2847/6015 [17:22<12:05,  4.36it/s]

 47%|████▋     | 2848/6015 [17:22<12:07,  4.35it/s]

 47%|████▋     | 2849/6015 [17:23<12:08,  4.35it/s]

 47%|████▋     | 2850/6015 [17:23<12:07,  4.35it/s]

 47%|████▋     | 2851/6015 [17:23<12:05,  4.36it/s]

 47%|████▋     | 2852/6015 [17:23<12:05,  4.36it/s]

 47%|████▋     | 2853/6015 [17:24<12:03,  4.37it/s]

 47%|████▋     | 2854/6015 [17:24<12:03,  4.37it/s]

 47%|████▋     | 2855/6015 [17:24<12:03,  4.37it/s]

 47%|████▋     | 2856/6015 [17:24<12:06,  4.35it/s]

 47%|████▋     | 2857/6015 [17:25<12:07,  4.34it/s]

 48%|████▊     | 2858/6015 [17:25<12:06,  4.34it/s]

 48%|████▊     | 2859/6015 [17:25<12:07,  4.34it/s]

 48%|████▊     | 2860/6015 [17:25<12:08,  4.33it/s]

 48%|████▊     | 2861/6015 [17:25<12:06,  4.34it/s]

 48%|████▊     | 2862/6015 [17:26<12:06,  4.34it/s]

 48%|████▊     | 2863/6015 [17:26<12:06,  4.34it/s]

 48%|████▊     | 2864/6015 [17:26<12:07,  4.33it/s]

 48%|████▊     | 2865/6015 [17:26<12:07,  4.33it/s]

 48%|████▊     | 2866/6015 [17:27<12:07,  4.33it/s]

 48%|████▊     | 2867/6015 [17:27<12:06,  4.33it/s]

 48%|████▊     | 2868/6015 [17:27<12:07,  4.32it/s]

 48%|████▊     | 2869/6015 [17:27<12:06,  4.33it/s]

 48%|████▊     | 2870/6015 [17:28<12:06,  4.33it/s]

 48%|████▊     | 2871/6015 [17:28<12:09,  4.31it/s]

 48%|████▊     | 2872/6015 [17:28<12:07,  4.32it/s]

 48%|████▊     | 2873/6015 [17:28<12:07,  4.32it/s]

 48%|████▊     | 2874/6015 [17:28<12:04,  4.34it/s]

 48%|████▊     | 2875/6015 [17:29<12:03,  4.34it/s]

 48%|████▊     | 2876/6015 [17:29<12:04,  4.33it/s]

 48%|████▊     | 2877/6015 [17:29<12:02,  4.34it/s]

 48%|████▊     | 2878/6015 [17:29<12:01,  4.35it/s]

 48%|████▊     | 2879/6015 [17:30<12:07,  4.31it/s]

 48%|████▊     | 2880/6015 [17:30<12:05,  4.32it/s]

 48%|████▊     | 2881/6015 [17:30<12:05,  4.32it/s]

 48%|████▊     | 2882/6015 [17:30<12:03,  4.33it/s]

 48%|████▊     | 2883/6015 [17:31<12:02,  4.33it/s]

 48%|████▊     | 2884/6015 [17:31<12:01,  4.34it/s]

 48%|████▊     | 2885/6015 [17:31<12:01,  4.34it/s]

 48%|████▊     | 2886/6015 [17:31<12:01,  4.34it/s]

 48%|████▊     | 2887/6015 [17:31<12:03,  4.32it/s]

 48%|████▊     | 2888/6015 [17:32<12:01,  4.33it/s]

 48%|████▊     | 2889/6015 [17:32<12:01,  4.33it/s]

 48%|████▊     | 2890/6015 [17:32<11:59,  4.34it/s]

 48%|████▊     | 2891/6015 [17:32<11:59,  4.34it/s]

 48%|████▊     | 2892/6015 [17:33<11:58,  4.35it/s]

 48%|████▊     | 2893/6015 [17:33<11:58,  4.35it/s]

 48%|████▊     | 2894/6015 [17:33<11:59,  4.34it/s]

 48%|████▊     | 2895/6015 [17:33<12:00,  4.33it/s]

 48%|████▊     | 2896/6015 [17:34<12:00,  4.33it/s]

 48%|████▊     | 2897/6015 [17:34<12:01,  4.32it/s]

 48%|████▊     | 2898/6015 [17:34<11:59,  4.33it/s]

 48%|████▊     | 2899/6015 [17:34<11:58,  4.33it/s]

 48%|████▊     | 2900/6015 [17:34<11:58,  4.33it/s]

 48%|████▊     | 2901/6015 [17:35<11:57,  4.34it/s]

 48%|████▊     | 2902/6015 [17:35<11:57,  4.34it/s]

 48%|████▊     | 2903/6015 [17:35<12:00,  4.32it/s]

 48%|████▊     | 2904/6015 [17:35<11:59,  4.33it/s]

 48%|████▊     | 2905/6015 [17:36<11:59,  4.32it/s]

 48%|████▊     | 2906/6015 [17:36<11:58,  4.33it/s]

 48%|████▊     | 2907/6015 [17:36<11:57,  4.33it/s]

 48%|████▊     | 2908/6015 [17:36<11:57,  4.33it/s]

 48%|████▊     | 2909/6015 [17:37<11:56,  4.34it/s]

 48%|████▊     | 2910/6015 [17:37<11:56,  4.34it/s]

 48%|████▊     | 2911/6015 [17:37<11:56,  4.33it/s]

 48%|████▊     | 2912/6015 [17:37<11:56,  4.33it/s]

 48%|████▊     | 2913/6015 [17:37<11:55,  4.34it/s]

 48%|████▊     | 2914/6015 [17:38<11:54,  4.34it/s]

 48%|████▊     | 2915/6015 [17:38<11:55,  4.33it/s]

 48%|████▊     | 2916/6015 [17:38<11:58,  4.31it/s]

 48%|████▊     | 2917/6015 [17:38<11:56,  4.33it/s]

 49%|████▊     | 2918/6015 [17:39<11:55,  4.33it/s]

 49%|████▊     | 2919/6015 [17:39<11:57,  4.31it/s]

 49%|████▊     | 2920/6015 [17:39<11:56,  4.32it/s]

 49%|████▊     | 2921/6015 [17:39<11:55,  4.32it/s]

 49%|████▊     | 2922/6015 [17:40<11:53,  4.33it/s]

 49%|████▊     | 2923/6015 [17:40<11:56,  4.32it/s]

 49%|████▊     | 2924/6015 [17:40<11:55,  4.32it/s]

 49%|████▊     | 2925/6015 [17:40<11:54,  4.33it/s]

 49%|████▊     | 2926/6015 [17:40<11:54,  4.32it/s]

 49%|████▊     | 2927/6015 [17:41<11:56,  4.31it/s]

 49%|████▊     | 2928/6015 [17:41<11:54,  4.32it/s]

 49%|████▊     | 2929/6015 [17:41<11:55,  4.31it/s]

 49%|████▊     | 2930/6015 [17:41<11:53,  4.32it/s]

 49%|████▊     | 2931/6015 [17:42<11:53,  4.32it/s]

 49%|████▊     | 2932/6015 [17:42<11:54,  4.31it/s]

 49%|████▉     | 2933/6015 [17:42<11:53,  4.32it/s]

 49%|████▉     | 2934/6015 [17:42<11:53,  4.32it/s]

 49%|████▉     | 2935/6015 [17:43<11:53,  4.32it/s]

 49%|████▉     | 2936/6015 [17:43<11:52,  4.32it/s]

 49%|████▉     | 2937/6015 [17:43<11:51,  4.33it/s]

 49%|████▉     | 2938/6015 [17:43<11:50,  4.33it/s]

 49%|████▉     | 2939/6015 [17:43<11:52,  4.32it/s]

 49%|████▉     | 2940/6015 [17:44<11:52,  4.31it/s]

 49%|████▉     | 2941/6015 [17:44<11:52,  4.31it/s]

 49%|████▉     | 2942/6015 [17:44<11:51,  4.32it/s]

 49%|████▉     | 2943/6015 [17:44<11:51,  4.32it/s]

 49%|████▉     | 2944/6015 [17:45<11:50,  4.32it/s]

 49%|████▉     | 2945/6015 [17:45<11:50,  4.32it/s]

 49%|████▉     | 2946/6015 [17:45<11:50,  4.32it/s]

 49%|████▉     | 2947/6015 [17:45<11:51,  4.31it/s]

 49%|████▉     | 2948/6015 [17:46<11:50,  4.32it/s]

 49%|████▉     | 2949/6015 [17:46<11:49,  4.32it/s]

 49%|████▉     | 2950/6015 [17:46<11:49,  4.32it/s]

 49%|████▉     | 2951/6015 [17:46<11:49,  4.32it/s]

 49%|████▉     | 2952/6015 [17:46<11:49,  4.32it/s]

 49%|████▉     | 2953/6015 [17:47<11:49,  4.31it/s]

 49%|████▉     | 2954/6015 [17:47<11:49,  4.31it/s]

 49%|████▉     | 2955/6015 [17:47<11:47,  4.32it/s]

 49%|████▉     | 2956/6015 [17:47<11:48,  4.32it/s]

 49%|████▉     | 2957/6015 [17:48<11:49,  4.31it/s]

 49%|████▉     | 2958/6015 [17:48<11:52,  4.29it/s]

 49%|████▉     | 2959/6015 [17:48<11:49,  4.31it/s]

 49%|████▉     | 2960/6015 [17:48<11:47,  4.32it/s]

 49%|████▉     | 2961/6015 [17:49<11:47,  4.31it/s]

 49%|████▉     | 2962/6015 [17:49<11:47,  4.32it/s]

 49%|████▉     | 2963/6015 [17:49<11:46,  4.32it/s]

 49%|████▉     | 2964/6015 [17:49<11:45,  4.33it/s]

 49%|████▉     | 2965/6015 [17:49<11:43,  4.34it/s]

 49%|████▉     | 2966/6015 [17:50<11:42,  4.34it/s]

 49%|████▉     | 2967/6015 [17:50<11:43,  4.33it/s]

 49%|████▉     | 2968/6015 [17:50<11:43,  4.33it/s]

 49%|████▉     | 2969/6015 [17:50<11:41,  4.34it/s]

 49%|████▉     | 2970/6015 [17:51<11:41,  4.34it/s]

 49%|████▉     | 2971/6015 [17:51<11:42,  4.34it/s]

 49%|████▉     | 2972/6015 [17:51<11:43,  4.33it/s]

 49%|████▉     | 2973/6015 [17:51<11:44,  4.32it/s]

 49%|████▉     | 2974/6015 [17:52<11:44,  4.32it/s]

 49%|████▉     | 2975/6015 [17:52<11:44,  4.31it/s]

 49%|████▉     | 2976/6015 [17:52<11:45,  4.31it/s]

 49%|████▉     | 2977/6015 [17:52<11:45,  4.30it/s]

 50%|████▉     | 2978/6015 [17:53<11:45,  4.30it/s]

 50%|████▉     | 2979/6015 [17:53<11:44,  4.31it/s]

 50%|████▉     | 2980/6015 [17:53<11:45,  4.30it/s]

 50%|████▉     | 2981/6015 [17:53<11:45,  4.30it/s]

 50%|████▉     | 2982/6015 [17:53<11:43,  4.31it/s]

 50%|████▉     | 2983/6015 [17:54<11:42,  4.31it/s]

 50%|████▉     | 2984/6015 [17:54<11:43,  4.31it/s]

 50%|████▉     | 2985/6015 [17:54<11:43,  4.31it/s]

 50%|████▉     | 2986/6015 [17:54<11:42,  4.31it/s]

 50%|████▉     | 2987/6015 [17:55<11:42,  4.31it/s]

 50%|████▉     | 2988/6015 [17:55<11:42,  4.31it/s]

 50%|████▉     | 2989/6015 [17:55<11:45,  4.29it/s]

 50%|████▉     | 2990/6015 [17:55<11:43,  4.30it/s]

 50%|████▉     | 2991/6015 [17:56<11:43,  4.30it/s]

 50%|████▉     | 2992/6015 [17:56<11:42,  4.30it/s]

 50%|████▉     | 2993/6015 [17:56<11:42,  4.30it/s]

 50%|████▉     | 2994/6015 [17:56<11:42,  4.30it/s]

 50%|████▉     | 2995/6015 [17:56<11:41,  4.30it/s]

 50%|████▉     | 2996/6015 [17:57<11:42,  4.30it/s]

 50%|████▉     | 2997/6015 [17:57<11:40,  4.31it/s]

 50%|████▉     | 2998/6015 [17:57<11:39,  4.31it/s]

 50%|████▉     | 2999/6015 [17:57<11:41,  4.30it/s]

 50%|████▉     | 3000/6015 [17:58<11:40,  4.31it/s]

 50%|████▉     | 3001/6015 [17:58<11:40,  4.30it/s]

 50%|████▉     | 3002/6015 [17:58<11:39,  4.31it/s]

 50%|████▉     | 3003/6015 [17:58<11:39,  4.31it/s]

 50%|████▉     | 3004/6015 [17:59<11:40,  4.30it/s]

 50%|████▉     | 3005/6015 [17:59<11:38,  4.31it/s]

 50%|████▉     | 3006/6015 [17:59<11:39,  4.30it/s]

 50%|████▉     | 3007/6015 [17:59<11:38,  4.31it/s]

 50%|█████     | 3008/6015 [17:59<11:38,  4.30it/s]

 50%|█████     | 3009/6015 [18:00<11:40,  4.29it/s]

 50%|█████     | 3010/6015 [18:00<11:38,  4.30it/s]

 50%|█████     | 3011/6015 [18:00<11:37,  4.31it/s]

 50%|█████     | 3012/6015 [18:00<11:37,  4.31it/s]

 50%|█████     | 3013/6015 [18:01<11:36,  4.31it/s]

 50%|█████     | 3014/6015 [18:01<11:36,  4.31it/s]

 50%|█████     | 3015/6015 [18:01<11:36,  4.31it/s]

 50%|█████     | 3016/6015 [18:01<11:37,  4.30it/s]

 50%|█████     | 3017/6015 [18:02<11:36,  4.30it/s]

 50%|█████     | 3018/6015 [18:02<11:34,  4.32it/s]

 50%|█████     | 3019/6015 [18:02<11:35,  4.31it/s]

 50%|█████     | 3020/6015 [18:02<11:35,  4.31it/s]

 50%|█████     | 3021/6015 [18:02<11:35,  4.30it/s]

 50%|█████     | 3022/6015 [18:03<11:36,  4.30it/s]

 50%|█████     | 3023/6015 [18:03<11:35,  4.30it/s]

 50%|█████     | 3024/6015 [18:03<11:35,  4.30it/s]

 50%|█████     | 3025/6015 [18:03<11:38,  4.28it/s]

 50%|█████     | 3026/6015 [18:04<11:38,  4.28it/s]

 50%|█████     | 3027/6015 [18:04<11:37,  4.29it/s]

 50%|█████     | 3028/6015 [18:04<11:36,  4.29it/s]

 50%|█████     | 3029/6015 [18:04<11:37,  4.28it/s]

 50%|█████     | 3030/6015 [18:05<11:38,  4.28it/s]

 50%|█████     | 3031/6015 [18:05<11:38,  4.27it/s]

 50%|█████     | 3032/6015 [18:05<11:38,  4.27it/s]

 50%|█████     | 3033/6015 [18:05<11:38,  4.27it/s]

 50%|█████     | 3034/6015 [18:06<11:38,  4.27it/s]

 50%|█████     | 3035/6015 [18:06<11:38,  4.27it/s]

 50%|█████     | 3036/6015 [18:06<11:36,  4.28it/s]

 50%|█████     | 3037/6015 [18:06<11:36,  4.28it/s]

 51%|█████     | 3038/6015 [18:06<11:35,  4.28it/s]

 51%|█████     | 3039/6015 [18:07<11:35,  4.28it/s]

 51%|█████     | 3040/6015 [18:07<11:35,  4.28it/s]

 51%|█████     | 3041/6015 [18:07<11:33,  4.29it/s]

 51%|█████     | 3042/6015 [18:07<11:33,  4.28it/s]

 51%|█████     | 3043/6015 [18:08<11:34,  4.28it/s]

 51%|█████     | 3044/6015 [18:08<11:32,  4.29it/s]

 51%|█████     | 3045/6015 [18:08<11:34,  4.28it/s]

 51%|█████     | 3046/6015 [18:08<11:33,  4.28it/s]

 51%|█████     | 3047/6015 [18:09<11:35,  4.27it/s]

 51%|█████     | 3048/6015 [18:09<11:35,  4.27it/s]

 51%|█████     | 3049/6015 [18:09<11:35,  4.26it/s]

 51%|█████     | 3050/6015 [18:09<11:34,  4.27it/s]

 51%|█████     | 3051/6015 [18:10<11:33,  4.28it/s]

 51%|█████     | 3052/6015 [18:10<11:32,  4.28it/s]

 51%|█████     | 3053/6015 [18:10<11:33,  4.27it/s]

 51%|█████     | 3054/6015 [18:10<11:31,  4.28it/s]

 51%|█████     | 3055/6015 [18:10<11:31,  4.28it/s]

 51%|█████     | 3056/6015 [18:11<11:31,  4.28it/s]

 51%|█████     | 3057/6015 [18:11<11:32,  4.27it/s]

 51%|█████     | 3058/6015 [18:11<11:33,  4.26it/s]

 51%|█████     | 3059/6015 [18:11<11:32,  4.27it/s]

 51%|█████     | 3060/6015 [18:12<11:32,  4.27it/s]

 51%|█████     | 3061/6015 [18:12<11:32,  4.26it/s]

 51%|█████     | 3062/6015 [18:12<11:31,  4.27it/s]

 51%|█████     | 3063/6015 [18:12<11:31,  4.27it/s]

 51%|█████     | 3064/6015 [18:13<11:29,  4.28it/s]

 51%|█████     | 3065/6015 [18:13<11:31,  4.26it/s]

 51%|█████     | 3066/6015 [18:13<11:30,  4.27it/s]

 51%|█████     | 3067/6015 [18:13<11:30,  4.27it/s]

 51%|█████     | 3068/6015 [18:13<11:30,  4.27it/s]

 51%|█████     | 3069/6015 [18:14<11:27,  4.29it/s]

 51%|█████     | 3070/6015 [18:14<11:27,  4.28it/s]

 51%|█████     | 3071/6015 [18:14<11:29,  4.27it/s]

 51%|█████     | 3072/6015 [18:14<11:30,  4.26it/s]

 51%|█████     | 3073/6015 [18:15<11:31,  4.26it/s]

 51%|█████     | 3074/6015 [18:15<11:29,  4.26it/s]

 51%|█████     | 3075/6015 [18:15<11:30,  4.26it/s]

 51%|█████     | 3076/6015 [18:15<11:29,  4.27it/s]

 51%|█████     | 3077/6015 [18:16<11:27,  4.27it/s]

 51%|█████     | 3078/6015 [18:16<11:28,  4.27it/s]

 51%|█████     | 3079/6015 [18:16<11:27,  4.27it/s]

 51%|█████     | 3080/6015 [18:16<11:25,  4.28it/s]

 51%|█████     | 3081/6015 [18:17<11:25,  4.28it/s]

 51%|█████     | 3082/6015 [18:17<11:27,  4.27it/s]

 51%|█████▏    | 3083/6015 [18:17<11:27,  4.26it/s]

 51%|█████▏    | 3084/6015 [18:17<11:26,  4.27it/s]

 51%|█████▏    | 3085/6015 [18:17<11:27,  4.26it/s]

 51%|█████▏    | 3086/6015 [18:18<11:26,  4.27it/s]

 51%|█████▏    | 3087/6015 [18:18<11:24,  4.28it/s]

 51%|█████▏    | 3088/6015 [18:18<11:24,  4.28it/s]

 51%|█████▏    | 3089/6015 [18:18<11:24,  4.28it/s]

 51%|█████▏    | 3090/6015 [18:19<11:25,  4.27it/s]

 51%|█████▏    | 3091/6015 [18:19<11:25,  4.27it/s]

 51%|█████▏    | 3092/6015 [18:19<11:23,  4.27it/s]

 51%|█████▏    | 3093/6015 [18:19<11:23,  4.27it/s]

 51%|█████▏    | 3094/6015 [18:20<11:22,  4.28it/s]

 51%|█████▏    | 3095/6015 [18:20<11:23,  4.27it/s]

 51%|█████▏    | 3096/6015 [18:20<11:24,  4.27it/s]

 51%|█████▏    | 3097/6015 [18:20<11:22,  4.27it/s]

 52%|█████▏    | 3098/6015 [18:21<11:22,  4.27it/s]

 52%|█████▏    | 3099/6015 [18:21<11:23,  4.27it/s]

 52%|█████▏    | 3100/6015 [18:21<11:22,  4.27it/s]

 52%|█████▏    | 3101/6015 [18:21<11:21,  4.27it/s]

 52%|█████▏    | 3102/6015 [18:21<11:21,  4.28it/s]

 52%|█████▏    | 3103/6015 [18:22<11:21,  4.27it/s]

 52%|█████▏    | 3104/6015 [18:22<11:22,  4.27it/s]

 52%|█████▏    | 3105/6015 [18:22<11:21,  4.27it/s]

 52%|█████▏    | 3106/6015 [18:22<11:21,  4.27it/s]

 52%|█████▏    | 3107/6015 [18:23<11:19,  4.28it/s]

 52%|█████▏    | 3108/6015 [18:23<11:19,  4.28it/s]

 52%|█████▏    | 3109/6015 [18:23<11:19,  4.28it/s]

 52%|█████▏    | 3110/6015 [18:23<11:21,  4.26it/s]

 52%|█████▏    | 3111/6015 [18:24<11:22,  4.25it/s]

 52%|█████▏    | 3112/6015 [18:24<11:21,  4.26it/s]

 52%|█████▏    | 3113/6015 [18:24<11:21,  4.26it/s]

 52%|█████▏    | 3114/6015 [18:24<11:21,  4.26it/s]

 52%|█████▏    | 3115/6015 [18:24<11:20,  4.26it/s]

 52%|█████▏    | 3116/6015 [18:25<11:20,  4.26it/s]

 52%|█████▏    | 3117/6015 [18:25<11:20,  4.26it/s]

 52%|█████▏    | 3118/6015 [18:25<11:19,  4.26it/s]

 52%|█████▏    | 3119/6015 [18:25<11:19,  4.26it/s]

 52%|█████▏    | 3120/6015 [18:26<11:18,  4.26it/s]

 52%|█████▏    | 3121/6015 [18:26<11:21,  4.24it/s]

 52%|█████▏    | 3122/6015 [18:26<11:20,  4.25it/s]

 52%|█████▏    | 3123/6015 [18:26<11:19,  4.26it/s]

 52%|█████▏    | 3124/6015 [18:27<11:18,  4.26it/s]

 52%|█████▏    | 3125/6015 [18:27<11:17,  4.27it/s]

 52%|█████▏    | 3126/6015 [18:27<11:17,  4.26it/s]

 52%|█████▏    | 3127/6015 [18:27<11:16,  4.27it/s]

 52%|█████▏    | 3128/6015 [18:28<11:16,  4.27it/s]

 52%|█████▏    | 3129/6015 [18:28<11:16,  4.27it/s]

logging
logging the anndata

 52%|█████▏    | 3130/6015 [20:31<29:38:30, 36.99s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 52%|█████▏    | 3131/6015 [20:31<20:48:07, 25.97s/it]

 52%|█████▏    | 3132/6015 [20:31<14:36:42, 18.25s/it]

 52%|█████▏    | 3133/6015 [20:31<10:16:44, 12.84s/it]

 52%|█████▏    | 3134/6015 [20:31<7:14:51,  9.06s/it]

 52%|█████▏    | 3135/6015 [20:32<5:07:32,  6.41s/it]

 52%|█████▏    | 3136/6015 [20:32<3:38:27,  4.55s/it]

 52%|█████▏    | 3137/6015 [20:32<2:36:07,  3.25s/it]

 52%|█████▏    | 3138/6015 [20:32<1:52:30,  2.35s/it]

 52%|█████▏    | 3139/6015 [20:33<1:21:58,  1.71s/it]

 52%|█████▏    | 3140/6015 [20:33<1:00:36,  1.26s/it]

 52%|█████▏    | 3141/6015 [20:33<45:38,  1.05it/s]

 52%|█████▏    | 3142/6015 [20:33<35:10,  1.36it/s]

 52%|█████▏    | 3143/6015 [20:33<27:51,  1.72it/s]

 52%|█████▏    | 3144/6015 [20:34<22:44,  2.10it/s]

 52%|█████▏    | 3145/6015 [20:34<19:09,  2.50it/s]

 52%|█████▏    | 3146/6015 [20:34<16:39,  2.87it/s]

 52%|█████▏    | 3147/6015 [20:34<14:53,  3.21it/s]

 52%|█████▏    | 3148/6015 [20:35<13:38,  3.50it/s]

 52%|█████▏    | 3149/6015 [20:35<12:45,  3.74it/s]

 52%|█████▏    | 3150/6015 [20:35<12:10,  3.92it/s]

 52%|█████▏    | 3151/6015 [20:35<11:43,  4.07it/s]

 52%|█████▏    | 3152/6015 [20:36<11:26,  4.17it/s]

 52%|█████▏    | 3153/6015 [20:36<11:15,  4.24it/s]

 52%|█████▏    | 3154/6015 [20:36<11:05,  4.30it/s]

 52%|█████▏    | 3155/6015 [20:36<11:01,  4.33it/s]

 52%|█████▏    | 3156/6015 [20:36<10:57,  4.35it/s]

 52%|█████▏    | 3157/6015 [20:37<10:53,  4.37it/s]

 53%|█████▎    | 3158/6015 [20:37<10:51,  4.39it/s]

 53%|█████▎    | 3159/6015 [20:37<10:49,  4.40it/s]

 53%|█████▎    | 3160/6015 [20:37<10:49,  4.40it/s]

 53%|█████▎    | 3161/6015 [20:38<10:48,  4.40it/s]

 53%|█████▎    | 3162/6015 [20:38<10:47,  4.41it/s]

 53%|█████▎    | 3163/6015 [20:38<10:47,  4.40it/s]

 53%|█████▎    | 3164/6015 [20:38<10:47,  4.40it/s]

 53%|█████▎    | 3165/6015 [20:38<10:46,  4.41it/s]

 53%|█████▎    | 3166/6015 [20:39<10:46,  4.41it/s]

 53%|█████▎    | 3167/6015 [20:39<10:45,  4.41it/s]

 53%|█████▎    | 3168/6015 [20:39<10:44,  4.42it/s]

 53%|█████▎    | 3169/6015 [20:39<10:44,  4.42it/s]

 53%|█████▎    | 3170/6015 [20:40<10:45,  4.41it/s]

 53%|█████▎    | 3171/6015 [20:40<10:43,  4.42it/s]

 53%|█████▎    | 3172/6015 [20:40<10:44,  4.41it/s]

 53%|█████▎    | 3173/6015 [20:40<10:44,  4.41it/s]

 53%|█████▎    | 3174/6015 [20:41<10:44,  4.41it/s]

 53%|█████▎    | 3175/6015 [20:41<10:45,  4.40it/s]

 53%|█████▎    | 3176/6015 [20:41<10:46,  4.39it/s]

 53%|█████▎    | 3177/6015 [20:41<10:46,  4.39it/s]

 53%|█████▎    | 3178/6015 [20:41<10:45,  4.39it/s]

 53%|█████▎    | 3179/6015 [20:42<10:44,  4.40it/s]

 53%|█████▎    | 3180/6015 [20:42<10:44,  4.40it/s]

 53%|█████▎    | 3181/6015 [20:42<10:45,  4.39it/s]

 53%|█████▎    | 3182/6015 [20:42<10:42,  4.41it/s]

 53%|█████▎    | 3183/6015 [20:43<10:43,  4.40it/s]

 53%|█████▎    | 3184/6015 [20:43<10:43,  4.40it/s]

 53%|█████▎    | 3185/6015 [20:43<10:41,  4.41it/s]

 53%|█████▎    | 3186/6015 [20:43<10:39,  4.42it/s]

 53%|█████▎    | 3187/6015 [20:43<10:40,  4.42it/s]

 53%|█████▎    | 3188/6015 [20:44<10:38,  4.43it/s]

 53%|█████▎    | 3189/6015 [20:44<10:40,  4.41it/s]

 53%|█████▎    | 3190/6015 [20:44<10:39,  4.41it/s]

 53%|█████▎    | 3191/6015 [20:44<10:39,  4.41it/s]

 53%|█████▎    | 3192/6015 [20:45<10:40,  4.41it/s]

 53%|█████▎    | 3193/6015 [20:45<10:38,  4.42it/s]

 53%|█████▎    | 3194/6015 [20:45<10:39,  4.41it/s]

 53%|█████▎    | 3195/6015 [20:45<10:40,  4.41it/s]

 53%|█████▎    | 3196/6015 [20:46<10:41,  4.40it/s]

 53%|█████▎    | 3197/6015 [20:46<10:41,  4.39it/s]

 53%|█████▎    | 3198/6015 [20:46<10:41,  4.39it/s]

 53%|█████▎    | 3199/6015 [20:46<10:40,  4.40it/s]

 53%|█████▎    | 3200/6015 [20:46<10:40,  4.40it/s]

 53%|█████▎    | 3201/6015 [20:47<10:40,  4.39it/s]

 53%|█████▎    | 3202/6015 [20:47<10:38,  4.40it/s]

 53%|█████▎    | 3203/6015 [20:47<10:38,  4.41it/s]

 53%|█████▎    | 3204/6015 [20:47<10:37,  4.41it/s]

 53%|█████▎    | 3205/6015 [20:48<10:37,  4.41it/s]

 53%|█████▎    | 3206/6015 [20:48<10:37,  4.41it/s]

 53%|█████▎    | 3207/6015 [20:48<10:38,  4.40it/s]

 53%|█████▎    | 3208/6015 [20:48<10:39,  4.39it/s]

 53%|█████▎    | 3209/6015 [20:48<10:38,  4.40it/s]

 53%|█████▎    | 3210/6015 [20:49<10:45,  4.35it/s]

 53%|█████▎    | 3211/6015 [20:49<10:42,  4.37it/s]

 53%|█████▎    | 3212/6015 [20:49<10:40,  4.38it/s]

 53%|█████▎    | 3213/6015 [20:49<10:38,  4.39it/s]

 53%|█████▎    | 3214/6015 [20:50<10:37,  4.39it/s]

 53%|█████▎    | 3215/6015 [20:50<10:38,  4.39it/s]

 53%|█████▎    | 3216/6015 [20:50<10:36,  4.39it/s]

 53%|█████▎    | 3217/6015 [20:50<10:36,  4.39it/s]

 53%|█████▎    | 3218/6015 [20:51<10:36,  4.39it/s]

 54%|█████▎    | 3219/6015 [20:51<10:35,  4.40it/s]

 54%|█████▎    | 3220/6015 [20:51<10:35,  4.40it/s]

 54%|█████▎    | 3221/6015 [20:51<10:35,  4.39it/s]

 54%|█████▎    | 3222/6015 [20:51<10:34,  4.40it/s]

 54%|█████▎    | 3223/6015 [20:52<10:34,  4.40it/s]

 54%|█████▎    | 3224/6015 [20:52<10:36,  4.38it/s]

 54%|█████▎    | 3225/6015 [20:52<10:37,  4.38it/s]

 54%|█████▎    | 3226/6015 [20:52<10:38,  4.37it/s]

 54%|█████▎    | 3227/6015 [20:53<10:36,  4.38it/s]

 54%|█████▎    | 3228/6015 [20:53<10:35,  4.39it/s]

 54%|█████▎    | 3229/6015 [20:53<10:35,  4.39it/s]

 54%|█████▎    | 3230/6015 [20:53<10:33,  4.39it/s]

 54%|█████▎    | 3231/6015 [20:53<10:34,  4.39it/s]

 54%|█████▎    | 3232/6015 [20:54<10:34,  4.39it/s]

 54%|█████▎    | 3233/6015 [20:54<10:33,  4.39it/s]

 54%|█████▍    | 3234/6015 [20:54<10:34,  4.38it/s]

 54%|█████▍    | 3235/6015 [20:54<10:34,  4.38it/s]

 54%|█████▍    | 3236/6015 [20:55<10:34,  4.38it/s]

 54%|█████▍    | 3237/6015 [20:55<10:35,  4.37it/s]

 54%|█████▍    | 3238/6015 [20:55<10:33,  4.39it/s]

 54%|█████▍    | 3239/6015 [20:55<10:34,  4.38it/s]

 54%|█████▍    | 3240/6015 [20:56<10:34,  4.37it/s]

 54%|█████▍    | 3241/6015 [20:56<10:33,  4.38it/s]

 54%|█████▍    | 3242/6015 [20:56<10:32,  4.38it/s]

 54%|█████▍    | 3243/6015 [20:56<10:32,  4.38it/s]

 54%|█████▍    | 3244/6015 [20:56<10:33,  4.37it/s]

 54%|█████▍    | 3245/6015 [20:57<10:33,  4.37it/s]

 54%|█████▍    | 3246/6015 [20:57<10:33,  4.37it/s]

 54%|█████▍    | 3247/6015 [20:57<10:33,  4.37it/s]

 54%|█████▍    | 3248/6015 [20:57<10:32,  4.37it/s]

 54%|█████▍    | 3249/6015 [20:58<10:32,  4.38it/s]

 54%|█████▍    | 3250/6015 [20:58<10:31,  4.38it/s]

 54%|█████▍    | 3251/6015 [20:58<10:31,  4.38it/s]

 54%|█████▍    | 3252/6015 [20:58<10:30,  4.38it/s]

 54%|█████▍    | 3253/6015 [20:58<10:30,  4.38it/s]

 54%|█████▍    | 3254/6015 [20:59<10:30,  4.38it/s]

 54%|█████▍    | 3255/6015 [20:59<10:29,  4.38it/s]

 54%|█████▍    | 3256/6015 [20:59<10:28,  4.39it/s]

 54%|█████▍    | 3257/6015 [20:59<10:28,  4.39it/s]

 54%|█████▍    | 3258/6015 [21:00<10:28,  4.39it/s]

 54%|█████▍    | 3259/6015 [21:00<10:28,  4.38it/s]

 54%|█████▍    | 3260/6015 [21:00<10:29,  4.38it/s]

 54%|█████▍    | 3261/6015 [21:00<10:29,  4.37it/s]

 54%|█████▍    | 3262/6015 [21:01<10:29,  4.38it/s]

 54%|█████▍    | 3263/6015 [21:01<10:28,  4.38it/s]

 54%|█████▍    | 3264/6015 [21:01<10:27,  4.38it/s]

 54%|█████▍    | 3265/6015 [21:01<10:28,  4.38it/s]

 54%|█████▍    | 3266/6015 [21:01<10:27,  4.38it/s]

 54%|█████▍    | 3267/6015 [21:02<10:27,  4.38it/s]

 54%|█████▍    | 3268/6015 [21:02<10:27,  4.38it/s]

 54%|█████▍    | 3269/6015 [21:02<10:27,  4.38it/s]

 54%|█████▍    | 3270/6015 [21:02<10:26,  4.38it/s]

 54%|█████▍    | 3271/6015 [21:03<10:27,  4.37it/s]

 54%|█████▍    | 3272/6015 [21:03<10:25,  4.38it/s]

 54%|█████▍    | 3273/6015 [21:03<10:25,  4.38it/s]

 54%|█████▍    | 3274/6015 [21:03<10:26,  4.38it/s]

 54%|█████▍    | 3275/6015 [21:04<10:24,  4.39it/s]

 54%|█████▍    | 3276/6015 [21:04<10:25,  4.38it/s]

 54%|█████▍    | 3277/6015 [21:04<10:28,  4.35it/s]

 54%|█████▍    | 3278/6015 [21:04<10:28,  4.35it/s]

 55%|█████▍    | 3279/6015 [21:04<10:29,  4.35it/s]

 55%|█████▍    | 3280/6015 [21:05<10:28,  4.35it/s]

 55%|█████▍    | 3281/6015 [21:05<10:27,  4.36it/s]

 55%|█████▍    | 3282/6015 [21:05<10:27,  4.36it/s]

 55%|█████▍    | 3283/6015 [21:05<10:26,  4.36it/s]

 55%|█████▍    | 3284/6015 [21:06<10:27,  4.35it/s]

 55%|█████▍    | 3285/6015 [21:06<10:27,  4.35it/s]

 55%|█████▍    | 3286/6015 [21:06<10:24,  4.37it/s]

 55%|█████▍    | 3287/6015 [21:06<10:23,  4.37it/s]

 55%|█████▍    | 3288/6015 [21:07<10:24,  4.37it/s]

 55%|█████▍    | 3289/6015 [21:07<10:22,  4.38it/s]

 55%|█████▍    | 3290/6015 [21:07<10:23,  4.37it/s]

 55%|█████▍    | 3291/6015 [21:07<10:23,  4.37it/s]

 55%|█████▍    | 3292/6015 [21:07<10:24,  4.36it/s]

 55%|█████▍    | 3293/6015 [21:08<10:25,  4.35it/s]

 55%|█████▍    | 3294/6015 [21:08<10:24,  4.36it/s]

 55%|█████▍    | 3295/6015 [21:08<10:24,  4.36it/s]

 55%|█████▍    | 3296/6015 [21:08<10:23,  4.36it/s]

 55%|█████▍    | 3297/6015 [21:09<10:25,  4.34it/s]

 55%|█████▍    | 3298/6015 [21:09<10:24,  4.35it/s]

 55%|█████▍    | 3299/6015 [21:09<10:23,  4.35it/s]

 55%|█████▍    | 3300/6015 [21:09<10:22,  4.36it/s]

 55%|█████▍    | 3301/6015 [21:09<10:21,  4.37it/s]

 55%|█████▍    | 3302/6015 [21:10<10:20,  4.37it/s]

 55%|█████▍    | 3303/6015 [21:10<10:19,  4.37it/s]

 55%|█████▍    | 3304/6015 [21:10<10:21,  4.37it/s]

 55%|█████▍    | 3305/6015 [21:10<10:21,  4.36it/s]

 55%|█████▍    | 3306/6015 [21:11<10:20,  4.37it/s]

 55%|█████▍    | 3307/6015 [21:11<10:19,  4.37it/s]

 55%|█████▍    | 3308/6015 [21:11<10:20,  4.36it/s]

 55%|█████▌    | 3309/6015 [21:11<10:19,  4.37it/s]

 55%|█████▌    | 3310/6015 [21:12<10:19,  4.37it/s]

 55%|█████▌    | 3311/6015 [21:12<10:19,  4.36it/s]

 55%|█████▌    | 3312/6015 [21:12<10:18,  4.37it/s]

 55%|█████▌    | 3313/6015 [21:12<10:18,  4.37it/s]

 55%|█████▌    | 3314/6015 [21:12<10:18,  4.36it/s]

 55%|█████▌    | 3315/6015 [21:13<10:18,  4.37it/s]

 55%|█████▌    | 3316/6015 [21:13<10:17,  4.37it/s]

 55%|█████▌    | 3317/6015 [21:13<10:16,  4.37it/s]

 55%|█████▌    | 3318/6015 [21:13<10:16,  4.38it/s]

 55%|█████▌    | 3319/6015 [21:14<10:15,  4.38it/s]

 55%|█████▌    | 3320/6015 [21:14<10:14,  4.39it/s]

 55%|█████▌    | 3321/6015 [21:14<10:14,  4.38it/s]

 55%|█████▌    | 3322/6015 [21:14<10:15,  4.38it/s]

 55%|█████▌    | 3323/6015 [21:15<10:14,  4.38it/s]

 55%|█████▌    | 3324/6015 [21:15<10:15,  4.37it/s]

 55%|█████▌    | 3325/6015 [21:15<10:14,  4.37it/s]

 55%|█████▌    | 3326/6015 [21:15<10:14,  4.37it/s]

 55%|█████▌    | 3327/6015 [21:15<10:14,  4.37it/s]

 55%|█████▌    | 3328/6015 [21:16<10:15,  4.37it/s]

 55%|█████▌    | 3329/6015 [21:16<10:15,  4.37it/s]

 55%|█████▌    | 3330/6015 [21:16<10:14,  4.37it/s]

 55%|█████▌    | 3331/6015 [21:16<10:15,  4.36it/s]

 55%|█████▌    | 3332/6015 [21:17<10:14,  4.36it/s]

 55%|█████▌    | 3333/6015 [21:17<10:14,  4.36it/s]

 55%|█████▌    | 3334/6015 [21:17<10:13,  4.37it/s]

 55%|█████▌    | 3335/6015 [21:17<10:14,  4.36it/s]

 55%|█████▌    | 3336/6015 [21:17<10:15,  4.35it/s]

 55%|█████▌    | 3337/6015 [21:18<10:14,  4.36it/s]

 55%|█████▌    | 3338/6015 [21:18<10:14,  4.36it/s]

 56%|█████▌    | 3339/6015 [21:18<10:13,  4.36it/s]

 56%|█████▌    | 3340/6015 [21:18<10:12,  4.37it/s]

 56%|█████▌    | 3341/6015 [21:19<10:12,  4.36it/s]

 56%|█████▌    | 3342/6015 [21:19<10:11,  4.37it/s]

 56%|█████▌    | 3343/6015 [21:19<10:11,  4.37it/s]

 56%|█████▌    | 3344/6015 [21:19<10:11,  4.37it/s]

 56%|█████▌    | 3345/6015 [21:20<10:11,  4.37it/s]

 56%|█████▌    | 3346/6015 [21:20<10:11,  4.36it/s]

 56%|█████▌    | 3347/6015 [21:20<10:13,  4.35it/s]

 56%|█████▌    | 3348/6015 [21:20<10:12,  4.36it/s]

 56%|█████▌    | 3349/6015 [21:20<10:12,  4.35it/s]

 56%|█████▌    | 3350/6015 [21:21<10:12,  4.35it/s]

 56%|█████▌    | 3351/6015 [21:21<10:12,  4.35it/s]

 56%|█████▌    | 3352/6015 [21:21<10:11,  4.35it/s]

 56%|█████▌    | 3353/6015 [21:21<10:10,  4.36it/s]

 56%|█████▌    | 3354/6015 [21:22<10:09,  4.37it/s]

 56%|█████▌    | 3355/6015 [21:22<10:10,  4.36it/s]

 56%|█████▌    | 3356/6015 [21:22<10:10,  4.36it/s]

 56%|█████▌    | 3357/6015 [21:22<10:10,  4.36it/s]

 56%|█████▌    | 3358/6015 [21:23<10:09,  4.36it/s]

 56%|█████▌    | 3359/6015 [21:23<10:09,  4.36it/s]

 56%|█████▌    | 3360/6015 [21:23<10:08,  4.36it/s]

 56%|█████▌    | 3361/6015 [21:23<10:07,  4.37it/s]

 56%|█████▌    | 3362/6015 [21:23<10:06,  4.37it/s]

 56%|█████▌    | 3363/6015 [21:24<10:06,  4.37it/s]

 56%|█████▌    | 3364/6015 [21:24<10:06,  4.37it/s]

 56%|█████▌    | 3365/6015 [21:24<10:06,  4.37it/s]

 56%|█████▌    | 3366/6015 [21:24<10:07,  4.36it/s]

 56%|█████▌    | 3367/6015 [21:25<10:09,  4.35it/s]

 56%|█████▌    | 3368/6015 [21:25<10:09,  4.34it/s]

 56%|█████▌    | 3369/6015 [21:25<10:07,  4.35it/s]

 56%|█████▌    | 3370/6015 [21:25<10:09,  4.34it/s]

 56%|█████▌    | 3371/6015 [21:26<10:08,  4.34it/s]

 56%|█████▌    | 3372/6015 [21:26<10:07,  4.35it/s]

 56%|█████▌    | 3373/6015 [21:26<10:06,  4.35it/s]

 56%|█████▌    | 3374/6015 [21:26<10:06,  4.35it/s]

 56%|█████▌    | 3375/6015 [21:26<10:05,  4.36it/s]

 56%|█████▌    | 3376/6015 [21:27<10:05,  4.36it/s]

 56%|█████▌    | 3377/6015 [21:27<10:07,  4.34it/s]

 56%|█████▌    | 3378/6015 [21:27<10:06,  4.35it/s]

 56%|█████▌    | 3379/6015 [21:27<10:05,  4.35it/s]

 56%|█████▌    | 3380/6015 [21:28<10:04,  4.36it/s]

 56%|█████▌    | 3381/6015 [21:28<10:04,  4.35it/s]

 56%|█████▌    | 3382/6015 [21:28<10:04,  4.35it/s]

 56%|█████▌    | 3383/6015 [21:28<10:03,  4.36it/s]

 56%|█████▋    | 3384/6015 [21:29<10:03,  4.36it/s]

 56%|█████▋    | 3385/6015 [21:29<10:03,  4.36it/s]

 56%|█████▋    | 3386/6015 [21:29<10:02,  4.36it/s]

 56%|█████▋    | 3387/6015 [21:29<10:02,  4.36it/s]

 56%|█████▋    | 3388/6015 [21:29<10:02,  4.36it/s]

 56%|█████▋    | 3389/6015 [21:30<10:01,  4.37it/s]

 56%|█████▋    | 3390/6015 [21:30<10:02,  4.36it/s]

 56%|█████▋    | 3391/6015 [21:30<10:00,  4.37it/s]

 56%|█████▋    | 3392/6015 [21:30<10:00,  4.37it/s]

 56%|█████▋    | 3393/6015 [21:31<09:59,  4.38it/s]

 56%|█████▋    | 3394/6015 [21:31<09:58,  4.38it/s]

 56%|█████▋    | 3395/6015 [21:31<09:59,  4.37it/s]

 56%|█████▋    | 3396/6015 [21:31<09:59,  4.37it/s]

 56%|█████▋    | 3397/6015 [21:31<09:59,  4.36it/s]

 56%|█████▋    | 3398/6015 [21:32<10:00,  4.36it/s]

 57%|█████▋    | 3399/6015 [21:32<10:00,  4.36it/s]

 57%|█████▋    | 3400/6015 [21:32<10:00,  4.35it/s]

 57%|█████▋    | 3401/6015 [21:32<10:01,  4.35it/s]

 57%|█████▋    | 3402/6015 [21:33<10:00,  4.35it/s]

 57%|█████▋    | 3403/6015 [21:33<10:00,  4.35it/s]

 57%|█████▋    | 3404/6015 [21:33<10:00,  4.35it/s]

 57%|█████▋    | 3405/6015 [21:33<09:59,  4.36it/s]

 57%|█████▋    | 3406/6015 [21:34<09:59,  4.35it/s]

 57%|█████▋    | 3407/6015 [21:34<09:59,  4.35it/s]

 57%|█████▋    | 3408/6015 [21:34<09:59,  4.35it/s]

 57%|█████▋    | 3409/6015 [21:34<09:58,  4.35it/s]

 57%|█████▋    | 3410/6015 [21:34<09:57,  4.36it/s]

 57%|█████▋    | 3411/6015 [21:35<09:58,  4.35it/s]

 57%|█████▋    | 3412/6015 [21:35<09:58,  4.35it/s]

 57%|█████▋    | 3413/6015 [21:35<09:57,  4.35it/s]

 57%|█████▋    | 3414/6015 [21:35<09:58,  4.35it/s]

 57%|█████▋    | 3415/6015 [21:36<09:58,  4.34it/s]

 57%|█████▋    | 3416/6015 [21:36<09:59,  4.34it/s]

 57%|█████▋    | 3417/6015 [21:36<09:59,  4.34it/s]

 57%|█████▋    | 3418/6015 [21:36<09:57,  4.35it/s]

 57%|█████▋    | 3419/6015 [21:37<09:57,  4.35it/s]

 57%|█████▋    | 3420/6015 [21:37<09:56,  4.35it/s]

 57%|█████▋    | 3421/6015 [21:37<09:56,  4.35it/s]

 57%|█████▋    | 3422/6015 [21:37<09:57,  4.34it/s]

 57%|█████▋    | 3423/6015 [21:37<09:57,  4.34it/s]

 57%|█████▋    | 3424/6015 [21:38<09:56,  4.34it/s]

 57%|█████▋    | 3425/6015 [21:38<09:57,  4.33it/s]

 57%|█████▋    | 3426/6015 [21:38<09:56,  4.34it/s]

 57%|█████▋    | 3427/6015 [21:38<09:54,  4.35it/s]

 57%|█████▋    | 3428/6015 [21:39<09:55,  4.34it/s]

 57%|█████▋    | 3429/6015 [21:39<09:54,  4.35it/s]

 57%|█████▋    | 3430/6015 [21:39<09:54,  4.34it/s]

 57%|█████▋    | 3431/6015 [21:39<09:55,  4.34it/s]

 57%|█████▋    | 3432/6015 [21:40<09:55,  4.34it/s]

 57%|█████▋    | 3433/6015 [21:40<09:55,  4.34it/s]

 57%|█████▋    | 3434/6015 [21:40<09:54,  4.34it/s]

 57%|█████▋    | 3435/6015 [21:40<09:53,  4.35it/s]

 57%|█████▋    | 3436/6015 [21:40<09:52,  4.35it/s]

 57%|█████▋    | 3437/6015 [21:41<09:52,  4.35it/s]

 57%|█████▋    | 3438/6015 [21:41<09:52,  4.35it/s]

 57%|█████▋    | 3439/6015 [21:41<09:51,  4.35it/s]

 57%|█████▋    | 3440/6015 [21:41<09:50,  4.36it/s]

 57%|█████▋    | 3441/6015 [21:42<09:50,  4.36it/s]

 57%|█████▋    | 3442/6015 [21:42<09:49,  4.36it/s]

 57%|█████▋    | 3443/6015 [21:42<09:48,  4.37it/s]

 57%|█████▋    | 3444/6015 [21:42<09:48,  4.37it/s]

 57%|█████▋    | 3445/6015 [21:43<09:47,  4.38it/s]

 57%|█████▋    | 3446/6015 [21:43<09:46,  4.38it/s]

 57%|█████▋    | 3447/6015 [21:43<09:47,  4.37it/s]

 57%|█████▋    | 3448/6015 [21:43<09:46,  4.38it/s]

 57%|█████▋    | 3449/6015 [21:43<09:45,  4.38it/s]

 57%|█████▋    | 3450/6015 [21:44<09:45,  4.38it/s]

 57%|█████▋    | 3451/6015 [21:44<09:45,  4.38it/s]

 57%|█████▋    | 3452/6015 [21:44<09:47,  4.36it/s]

 57%|█████▋    | 3453/6015 [21:44<09:47,  4.36it/s]

 57%|█████▋    | 3454/6015 [21:45<09:48,  4.35it/s]

 57%|█████▋    | 3455/6015 [21:45<09:50,  4.34it/s]

 57%|█████▋    | 3456/6015 [21:45<09:49,  4.34it/s]

 57%|█████▋    | 3457/6015 [21:45<09:49,  4.34it/s]

 57%|█████▋    | 3458/6015 [21:46<09:51,  4.32it/s]

 58%|█████▊    | 3459/6015 [21:46<09:51,  4.32it/s]

 58%|█████▊    | 3460/6015 [21:46<09:50,  4.33it/s]

 58%|█████▊    | 3461/6015 [21:46<09:49,  4.34it/s]

 58%|█████▊    | 3462/6015 [21:46<09:49,  4.33it/s]

 58%|█████▊    | 3463/6015 [21:47<09:47,  4.34it/s]

 58%|█████▊    | 3464/6015 [21:47<09:46,  4.35it/s]

 58%|█████▊    | 3465/6015 [21:47<09:47,  4.34it/s]

 58%|█████▊    | 3466/6015 [21:47<09:47,  4.34it/s]

 58%|█████▊    | 3467/6015 [21:48<09:46,  4.34it/s]

 58%|█████▊    | 3468/6015 [21:48<09:46,  4.34it/s]

 58%|█████▊    | 3469/6015 [21:48<09:44,  4.35it/s]

 58%|█████▊    | 3470/6015 [21:48<09:43,  4.36it/s]

 58%|█████▊    | 3471/6015 [21:49<09:45,  4.35it/s]

 58%|█████▊    | 3472/6015 [21:49<09:44,  4.35it/s]

 58%|█████▊    | 3473/6015 [21:49<09:43,  4.35it/s]

 58%|█████▊    | 3474/6015 [21:49<09:43,  4.36it/s]

 58%|█████▊    | 3475/6015 [21:49<09:42,  4.36it/s]

 58%|█████▊    | 3476/6015 [21:50<09:43,  4.35it/s]

 58%|█████▊    | 3477/6015 [21:50<09:41,  4.36it/s]

 58%|█████▊    | 3478/6015 [21:50<09:41,  4.36it/s]

 58%|█████▊    | 3479/6015 [21:50<09:41,  4.36it/s]

 58%|█████▊    | 3480/6015 [21:51<09:40,  4.36it/s]

 58%|█████▊    | 3481/6015 [21:51<09:42,  4.35it/s]

 58%|█████▊    | 3482/6015 [21:51<09:43,  4.34it/s]

 58%|█████▊    | 3483/6015 [21:51<09:42,  4.35it/s]

 58%|█████▊    | 3484/6015 [21:51<09:42,  4.35it/s]

 58%|█████▊    | 3485/6015 [21:52<09:43,  4.34it/s]

 58%|█████▊    | 3486/6015 [21:52<09:43,  4.34it/s]

 58%|█████▊    | 3487/6015 [21:52<09:43,  4.33it/s]

 58%|█████▊    | 3488/6015 [21:52<09:42,  4.34it/s]

 58%|█████▊    | 3489/6015 [21:53<09:43,  4.33it/s]

 58%|█████▊    | 3490/6015 [21:53<09:42,  4.34it/s]

 58%|█████▊    | 3491/6015 [21:53<09:42,  4.33it/s]

 58%|█████▊    | 3492/6015 [21:53<09:43,  4.33it/s]

 58%|█████▊    | 3493/6015 [21:54<09:42,  4.33it/s]

 58%|█████▊    | 3494/6015 [21:54<09:42,  4.33it/s]

 58%|█████▊    | 3495/6015 [21:54<09:41,  4.33it/s]

 58%|█████▊    | 3496/6015 [21:54<09:40,  4.34it/s]

 58%|█████▊    | 3497/6015 [21:54<09:40,  4.33it/s]

 58%|█████▊    | 3498/6015 [21:55<09:40,  4.33it/s]

 58%|█████▊    | 3499/6015 [21:55<09:39,  4.34it/s]

 58%|█████▊    | 3500/6015 [21:55<09:39,  4.34it/s]

 58%|█████▊    | 3501/6015 [21:55<09:40,  4.33it/s]

 58%|█████▊    | 3502/6015 [21:56<09:40,  4.33it/s]

 58%|█████▊    | 3503/6015 [21:56<09:39,  4.34it/s]

 58%|█████▊    | 3504/6015 [21:56<09:37,  4.35it/s]

 58%|█████▊    | 3505/6015 [21:56<09:37,  4.34it/s]

 58%|█████▊    | 3506/6015 [21:57<09:38,  4.34it/s]

 58%|█████▊    | 3507/6015 [21:57<09:37,  4.35it/s]

 58%|█████▊    | 3508/6015 [21:57<09:37,  4.34it/s]

 58%|█████▊    | 3509/6015 [21:57<09:37,  4.34it/s]

 58%|█████▊    | 3510/6015 [21:57<09:36,  4.34it/s]

 58%|█████▊    | 3511/6015 [21:58<09:38,  4.33it/s]

 58%|█████▊    | 3512/6015 [21:58<09:37,  4.33it/s]

 58%|█████▊    | 3513/6015 [21:58<09:37,  4.33it/s]

 58%|█████▊    | 3514/6015 [21:58<09:36,  4.33it/s]

 58%|█████▊    | 3515/6015 [21:59<09:36,  4.34it/s]

 58%|█████▊    | 3516/6015 [21:59<09:35,  4.34it/s]

 58%|█████▊    | 3517/6015 [21:59<09:36,  4.34it/s]

 58%|█████▊    | 3518/6015 [21:59<09:35,  4.34it/s]

 59%|█████▊    | 3519/6015 [22:00<09:34,  4.34it/s]

 59%|█████▊    | 3520/6015 [22:00<09:34,  4.34it/s]

 59%|█████▊    | 3521/6015 [22:00<09:34,  4.34it/s]

 59%|█████▊    | 3522/6015 [22:00<09:35,  4.33it/s]

 59%|█████▊    | 3523/6015 [22:00<09:34,  4.34it/s]

 59%|█████▊    | 3524/6015 [22:01<09:34,  4.33it/s]

 59%|█████▊    | 3525/6015 [22:01<09:34,  4.33it/s]

 59%|█████▊    | 3526/6015 [22:01<09:37,  4.31it/s]

 59%|█████▊    | 3527/6015 [22:01<09:37,  4.31it/s]

 59%|█████▊    | 3528/6015 [22:02<09:36,  4.32it/s]

 59%|█████▊    | 3529/6015 [22:02<09:35,  4.32it/s]

 59%|█████▊    | 3530/6015 [22:02<09:35,  4.32it/s]

 59%|█████▊    | 3531/6015 [22:02<09:33,  4.33it/s]

 59%|█████▊    | 3532/6015 [22:03<09:33,  4.33it/s]

 59%|█████▊    | 3533/6015 [22:03<09:33,  4.33it/s]

 59%|█████▉    | 3534/6015 [22:03<09:33,  4.33it/s]

 59%|█████▉    | 3535/6015 [22:03<09:34,  4.32it/s]

 59%|█████▉    | 3536/6015 [22:03<09:34,  4.32it/s]

 59%|█████▉    | 3537/6015 [22:04<09:33,  4.32it/s]

 59%|█████▉    | 3538/6015 [22:04<09:33,  4.32it/s]

 59%|█████▉    | 3539/6015 [22:04<09:32,  4.33it/s]

 59%|█████▉    | 3540/6015 [22:04<09:32,  4.32it/s]

 59%|█████▉    | 3541/6015 [22:05<09:32,  4.32it/s]

 59%|█████▉    | 3542/6015 [22:05<09:33,  4.31it/s]

 59%|█████▉    | 3543/6015 [22:05<09:32,  4.32it/s]

 59%|█████▉    | 3544/6015 [22:05<09:32,  4.32it/s]

 59%|█████▉    | 3545/6015 [22:06<09:31,  4.32it/s]

 59%|█████▉    | 3546/6015 [22:06<09:31,  4.32it/s]

 59%|█████▉    | 3547/6015 [22:06<09:30,  4.33it/s]

 59%|█████▉    | 3548/6015 [22:06<09:31,  4.32it/s]

 59%|█████▉    | 3549/6015 [22:07<09:31,  4.32it/s]

 59%|█████▉    | 3550/6015 [22:07<09:31,  4.31it/s]

 59%|█████▉    | 3551/6015 [22:07<09:31,  4.31it/s]

 59%|█████▉    | 3552/6015 [22:07<09:31,  4.31it/s]

 59%|█████▉    | 3553/6015 [22:07<09:30,  4.31it/s]

 59%|█████▉    | 3554/6015 [22:08<09:31,  4.31it/s]

 59%|█████▉    | 3555/6015 [22:08<09:29,  4.32it/s]

 59%|█████▉    | 3556/6015 [22:08<09:29,  4.32it/s]

 59%|█████▉    | 3557/6015 [22:08<09:29,  4.32it/s]

 59%|█████▉    | 3558/6015 [22:09<09:28,  4.32it/s]

 59%|█████▉    | 3559/6015 [22:09<09:29,  4.31it/s]

 59%|█████▉    | 3560/6015 [22:09<09:29,  4.31it/s]

 59%|█████▉    | 3561/6015 [22:09<09:29,  4.31it/s]

 59%|█████▉    | 3562/6015 [22:10<09:28,  4.32it/s]

 59%|█████▉    | 3563/6015 [22:10<09:26,  4.33it/s]

 59%|█████▉    | 3564/6015 [22:10<09:26,  4.33it/s]

 59%|█████▉    | 3565/6015 [22:10<09:33,  4.27it/s]

 59%|█████▉    | 3566/6015 [22:10<09:30,  4.29it/s]

 59%|█████▉    | 3567/6015 [22:11<09:29,  4.30it/s]

 59%|█████▉    | 3568/6015 [22:11<09:27,  4.31it/s]

 59%|█████▉    | 3569/6015 [22:11<09:27,  4.31it/s]

 59%|█████▉    | 3570/6015 [22:11<09:27,  4.31it/s]

 59%|█████▉    | 3571/6015 [22:12<09:25,  4.32it/s]

 59%|█████▉    | 3572/6015 [22:12<09:24,  4.33it/s]

 59%|█████▉    | 3573/6015 [22:12<09:25,  4.32it/s]

 59%|█████▉    | 3574/6015 [22:12<09:26,  4.31it/s]

 59%|█████▉    | 3575/6015 [22:13<09:27,  4.30it/s]

 59%|█████▉    | 3576/6015 [22:13<09:26,  4.30it/s]

 59%|█████▉    | 3577/6015 [22:13<09:26,  4.30it/s]

 59%|█████▉    | 3578/6015 [22:13<09:27,  4.29it/s]

 60%|█████▉    | 3579/6015 [22:13<09:25,  4.31it/s]

 60%|█████▉    | 3580/6015 [22:14<09:24,  4.31it/s]

 60%|█████▉    | 3581/6015 [22:14<09:24,  4.31it/s]

 60%|█████▉    | 3582/6015 [22:14<09:23,  4.32it/s]

 60%|█████▉    | 3583/6015 [22:14<09:24,  4.31it/s]

 60%|█████▉    | 3584/6015 [22:15<09:30,  4.26it/s]

 60%|█████▉    | 3585/6015 [22:15<09:27,  4.28it/s]

 60%|█████▉    | 3586/6015 [22:15<09:25,  4.30it/s]

 60%|█████▉    | 3587/6015 [22:15<09:23,  4.31it/s]

 60%|█████▉    | 3588/6015 [22:16<09:22,  4.32it/s]

 60%|█████▉    | 3589/6015 [22:16<09:22,  4.32it/s]

 60%|█████▉    | 3590/6015 [22:16<09:21,  4.32it/s]

 60%|█████▉    | 3591/6015 [22:16<09:20,  4.32it/s]

 60%|█████▉    | 3592/6015 [22:16<09:20,  4.32it/s]

 60%|█████▉    | 3593/6015 [22:17<09:19,  4.33it/s]

 60%|█████▉    | 3594/6015 [22:17<09:20,  4.32it/s]

 60%|█████▉    | 3595/6015 [22:17<09:19,  4.32it/s]

 60%|█████▉    | 3596/6015 [22:17<09:18,  4.33it/s]

 60%|█████▉    | 3597/6015 [22:18<09:19,  4.33it/s]

 60%|█████▉    | 3598/6015 [22:18<09:19,  4.32it/s]

 60%|█████▉    | 3599/6015 [22:18<09:19,  4.32it/s]

 60%|█████▉    | 3600/6015 [22:18<09:20,  4.31it/s]

 60%|█████▉    | 3601/6015 [22:19<09:19,  4.31it/s]

 60%|█████▉    | 3602/6015 [22:19<09:20,  4.30it/s]

 60%|█████▉    | 3603/6015 [22:19<09:20,  4.30it/s]

 60%|█████▉    | 3604/6015 [22:19<09:26,  4.26it/s]

 60%|█████▉    | 3605/6015 [22:20<09:24,  4.27it/s]

 60%|█████▉    | 3606/6015 [22:20<09:22,  4.29it/s]

 60%|█████▉    | 3607/6015 [22:20<09:21,  4.29it/s]

 60%|█████▉    | 3608/6015 [22:20<09:21,  4.29it/s]

 60%|██████    | 3609/6015 [22:20<09:20,  4.29it/s]

 60%|██████    | 3610/6015 [22:21<09:20,  4.29it/s]

 60%|██████    | 3611/6015 [22:21<09:19,  4.29it/s]

 60%|██████    | 3612/6015 [22:21<09:20,  4.28it/s]

 60%|██████    | 3613/6015 [22:21<09:21,  4.28it/s]

 60%|██████    | 3614/6015 [22:22<09:20,  4.28it/s]

 60%|██████    | 3615/6015 [22:22<09:19,  4.29it/s]

 60%|██████    | 3616/6015 [22:22<09:18,  4.29it/s]

 60%|██████    | 3617/6015 [22:22<09:18,  4.29it/s]

 60%|██████    | 3618/6015 [22:23<09:18,  4.29it/s]

 60%|██████    | 3619/6015 [22:23<09:17,  4.30it/s]

 60%|██████    | 3620/6015 [22:23<09:17,  4.30it/s]

 60%|██████    | 3621/6015 [22:23<09:17,  4.30it/s]

 60%|██████    | 3622/6015 [22:23<09:16,  4.30it/s]

 60%|██████    | 3623/6015 [22:24<09:16,  4.30it/s]

 60%|██████    | 3624/6015 [22:24<09:15,  4.30it/s]

 60%|██████    | 3625/6015 [22:24<09:15,  4.30it/s]

 60%|██████    | 3626/6015 [22:24<09:18,  4.28it/s]

 60%|██████    | 3627/6015 [22:25<09:16,  4.29it/s]

 60%|██████    | 3628/6015 [22:25<09:16,  4.29it/s]

 60%|██████    | 3629/6015 [22:25<09:15,  4.29it/s]

 60%|██████    | 3630/6015 [22:25<09:15,  4.30it/s]

 60%|██████    | 3631/6015 [22:26<09:14,  4.30it/s]

 60%|██████    | 3632/6015 [22:26<09:13,  4.30it/s]

 60%|██████    | 3633/6015 [22:26<09:14,  4.30it/s]

 60%|██████    | 3634/6015 [22:26<09:13,  4.30it/s]

 60%|██████    | 3635/6015 [22:26<09:13,  4.30it/s]

 60%|██████    | 3636/6015 [22:27<09:13,  4.30it/s]

 60%|██████    | 3637/6015 [22:27<09:12,  4.30it/s]

 60%|██████    | 3638/6015 [22:27<09:13,  4.29it/s]

 60%|██████    | 3639/6015 [22:27<09:12,  4.30it/s]

 61%|██████    | 3640/6015 [22:28<09:11,  4.31it/s]

 61%|██████    | 3641/6015 [22:28<09:11,  4.30it/s]

 61%|██████    | 3642/6015 [22:28<09:12,  4.29it/s]

 61%|██████    | 3643/6015 [22:28<09:11,  4.30it/s]

 61%|██████    | 3644/6015 [22:29<09:10,  4.30it/s]

 61%|██████    | 3645/6015 [22:29<09:09,  4.31it/s]

 61%|██████    | 3646/6015 [22:29<09:10,  4.31it/s]

 61%|██████    | 3647/6015 [22:29<09:10,  4.30it/s]

 61%|██████    | 3648/6015 [22:30<09:09,  4.30it/s]

 61%|██████    | 3649/6015 [22:30<09:10,  4.30it/s]

 61%|██████    | 3650/6015 [22:30<09:10,  4.30it/s]

 61%|██████    | 3651/6015 [22:30<09:11,  4.29it/s]

 61%|██████    | 3652/6015 [22:30<09:12,  4.28it/s]

 61%|██████    | 3653/6015 [22:31<09:11,  4.28it/s]

 61%|██████    | 3654/6015 [22:31<09:12,  4.27it/s]

 61%|██████    | 3655/6015 [22:31<09:12,  4.27it/s]

 61%|██████    | 3656/6015 [22:31<09:12,  4.27it/s]

 61%|██████    | 3657/6015 [22:32<09:12,  4.26it/s]

 61%|██████    | 3658/6015 [22:32<09:11,  4.27it/s]

 61%|██████    | 3659/6015 [22:32<09:10,  4.28it/s]

 61%|██████    | 3660/6015 [22:32<09:09,  4.28it/s]

 61%|██████    | 3661/6015 [22:33<09:09,  4.28it/s]

 61%|██████    | 3662/6015 [22:33<09:11,  4.27it/s]

 61%|██████    | 3663/6015 [22:33<09:09,  4.28it/s]

 61%|██████    | 3664/6015 [22:33<09:11,  4.26it/s]

 61%|██████    | 3665/6015 [22:33<09:11,  4.26it/s]

 61%|██████    | 3666/6015 [22:34<09:10,  4.27it/s]

 61%|██████    | 3667/6015 [22:34<09:09,  4.27it/s]

 61%|██████    | 3668/6015 [22:34<09:09,  4.27it/s]

 61%|██████    | 3669/6015 [22:34<09:08,  4.27it/s]

 61%|██████    | 3670/6015 [22:35<09:07,  4.28it/s]

 61%|██████    | 3671/6015 [22:35<09:07,  4.28it/s]

 61%|██████    | 3672/6015 [22:35<09:08,  4.27it/s]

 61%|██████    | 3673/6015 [22:35<09:08,  4.27it/s]

 61%|██████    | 3674/6015 [22:36<09:07,  4.28it/s]

 61%|██████    | 3675/6015 [22:36<09:07,  4.27it/s]

 61%|██████    | 3676/6015 [22:36<09:07,  4.27it/s]

 61%|██████    | 3677/6015 [22:36<09:07,  4.27it/s]

 61%|██████    | 3678/6015 [22:37<09:06,  4.28it/s]

 61%|██████    | 3679/6015 [22:37<09:08,  4.26it/s]

 61%|██████    | 3680/6015 [22:37<09:09,  4.25it/s]

 61%|██████    | 3681/6015 [22:37<09:07,  4.26it/s]

 61%|██████    | 3682/6015 [22:37<09:06,  4.27it/s]

 61%|██████    | 3683/6015 [22:38<09:05,  4.27it/s]

 61%|██████    | 3684/6015 [22:38<09:05,  4.27it/s]

 61%|██████▏   | 3685/6015 [22:38<09:05,  4.27it/s]

 61%|██████▏   | 3686/6015 [22:38<09:05,  4.27it/s]

 61%|██████▏   | 3687/6015 [22:39<09:07,  4.25it/s]

 61%|██████▏   | 3688/6015 [22:39<09:05,  4.27it/s]

 61%|██████▏   | 3689/6015 [22:39<09:04,  4.27it/s]

 61%|██████▏   | 3690/6015 [22:39<09:06,  4.25it/s]

 61%|██████▏   | 3691/6015 [22:40<09:05,  4.26it/s]

 61%|██████▏   | 3692/6015 [22:40<09:04,  4.26it/s]

 61%|██████▏   | 3693/6015 [22:40<09:04,  4.27it/s]

 61%|██████▏   | 3694/6015 [22:40<09:03,  4.27it/s]

 61%|██████▏   | 3695/6015 [22:41<09:03,  4.27it/s]

 61%|██████▏   | 3696/6015 [22:41<09:02,  4.27it/s]

 61%|██████▏   | 3697/6015 [22:41<09:02,  4.27it/s]

 61%|██████▏   | 3698/6015 [22:41<09:01,  4.28it/s]

 61%|██████▏   | 3699/6015 [22:41<09:02,  4.27it/s]

 62%|██████▏   | 3700/6015 [22:42<09:03,  4.26it/s]

 62%|██████▏   | 3701/6015 [22:42<09:04,  4.25it/s]

 62%|██████▏   | 3702/6015 [22:42<09:02,  4.26it/s]

 62%|██████▏   | 3703/6015 [22:42<09:01,  4.27it/s]

 62%|██████▏   | 3704/6015 [22:43<09:02,  4.26it/s]

 62%|██████▏   | 3705/6015 [22:43<09:01,  4.27it/s]

 62%|██████▏   | 3706/6015 [22:43<08:59,  4.28it/s]

 62%|██████▏   | 3707/6015 [22:43<09:00,  4.27it/s]

 62%|██████▏   | 3708/6015 [22:44<09:00,  4.27it/s]

 62%|██████▏   | 3709/6015 [22:44<09:01,  4.26it/s]

 62%|██████▏   | 3710/6015 [22:44<09:01,  4.25it/s]

 62%|██████▏   | 3711/6015 [22:44<09:02,  4.25it/s]

 62%|██████▏   | 3712/6015 [22:45<09:01,  4.25it/s]

 62%|██████▏   | 3713/6015 [22:45<08:59,  4.27it/s]

 62%|██████▏   | 3714/6015 [22:45<08:58,  4.27it/s]

 62%|██████▏   | 3715/6015 [22:45<08:59,  4.27it/s]

 62%|██████▏   | 3716/6015 [22:45<08:59,  4.26it/s]

 62%|██████▏   | 3717/6015 [22:46<08:58,  4.27it/s]

 62%|██████▏   | 3718/6015 [22:46<08:58,  4.26it/s]

 62%|██████▏   | 3719/6015 [22:46<08:58,  4.26it/s]

 62%|██████▏   | 3720/6015 [22:46<08:58,  4.26it/s]

 62%|██████▏   | 3721/6015 [22:47<08:57,  4.27it/s]

 62%|██████▏   | 3722/6015 [22:47<08:58,  4.26it/s]

 62%|██████▏   | 3723/6015 [22:47<08:58,  4.26it/s]

 62%|██████▏   | 3724/6015 [22:47<08:58,  4.25it/s]

 62%|██████▏   | 3725/6015 [22:48<08:57,  4.26it/s]

 62%|██████▏   | 3726/6015 [22:48<08:56,  4.27it/s]

 62%|██████▏   | 3727/6015 [22:48<08:55,  4.27it/s]

 62%|██████▏   | 3728/6015 [22:48<08:55,  4.27it/s]

 62%|██████▏   | 3729/6015 [22:48<08:54,  4.27it/s]

 62%|██████▏   | 3730/6015 [22:49<08:55,  4.27it/s]

 62%|██████▏   | 3731/6015 [22:49<08:54,  4.27it/s]

 62%|██████▏   | 3732/6015 [22:49<08:55,  4.27it/s]

 62%|██████▏   | 3733/6015 [22:49<08:54,  4.27it/s]

 62%|██████▏   | 3734/6015 [22:50<08:53,  4.27it/s]

 62%|██████▏   | 3735/6015 [22:50<08:53,  4.27it/s]

 62%|██████▏   | 3736/6015 [22:50<08:53,  4.27it/s]

 62%|██████▏   | 3737/6015 [22:50<08:52,  4.27it/s]

 62%|██████▏   | 3738/6015 [22:51<08:54,  4.26it/s]

 62%|██████▏   | 3739/6015 [22:51<08:54,  4.26it/s]

 62%|██████▏   | 3740/6015 [22:51<08:55,  4.25it/s]

 62%|██████▏   | 3741/6015 [22:51<08:54,  4.25it/s]

 62%|██████▏   | 3742/6015 [22:52<08:54,  4.26it/s]

 62%|██████▏   | 3743/6015 [22:52<08:53,  4.26it/s]

 62%|██████▏   | 3744/6015 [22:52<08:53,  4.26it/s]

 62%|██████▏   | 3745/6015 [22:52<08:52,  4.26it/s]

 62%|██████▏   | 3746/6015 [22:52<08:51,  4.27it/s]

 62%|██████▏   | 3747/6015 [22:53<08:53,  4.25it/s]

 62%|██████▏   | 3748/6015 [22:53<08:53,  4.25it/s]

 62%|██████▏   | 3749/6015 [22:53<08:53,  4.24it/s]

 62%|██████▏   | 3750/6015 [22:53<08:53,  4.25it/s]

 62%|██████▏   | 3751/6015 [22:54<08:51,  4.26it/s]

 62%|██████▏   | 3752/6015 [22:54<08:50,  4.27it/s]

 62%|██████▏   | 3753/6015 [22:54<08:51,  4.26it/s]

 62%|██████▏   | 3754/6015 [22:54<08:51,  4.26it/s]

 62%|██████▏   | 3755/6015 [22:55<08:51,  4.25it/s]

logging
logging the anndata

 62%|██████▏   | 3756/6015 [26:27<40:02:23, 63.81s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 62%|██████▏   | 3757/6015 [26:27<28:03:39, 44.74s/it]

 62%|██████▏   | 3758/6015 [26:27<19:40:35, 31.38s/it]

 62%|██████▏   | 3759/6015 [26:27<13:48:35, 22.04s/it]

 63%|██████▎   | 3760/6015 [26:28<9:42:16, 15.49s/it]

 63%|██████▎   | 3761/6015 [26:28<6:49:56, 10.91s/it]

 63%|██████▎   | 3762/6015 [26:28<4:49:23,  7.71s/it]

 63%|██████▎   | 3763/6015 [26:28<3:25:01,  5.46s/it]

 63%|██████▎   | 3764/6015 [26:29<2:25:58,  3.89s/it]

 63%|██████▎   | 3765/6015 [26:29<1:44:39,  2.79s/it]

 63%|██████▎   | 3766/6015 [26:29<1:15:46,  2.02s/it]

 63%|██████▎   | 3767/6015 [26:29<55:33,  1.48s/it]

 63%|██████▎   | 3768/6015 [26:29<41:24,  1.11s/it]

 63%|██████▎   | 3769/6015 [26:30<31:31,  1.19it/s]

 63%|██████▎   | 3770/6015 [26:30<24:35,  1.52it/s]

 63%|██████▎   | 3771/6015 [26:30<19:45,  1.89it/s]

 63%|██████▎   | 3772/6015 [26:30<16:20,  2.29it/s]

 63%|██████▎   | 3773/6015 [26:31<13:57,  2.68it/s]

 63%|██████▎   | 3774/6015 [26:31<12:18,  3.03it/s]

 63%|██████▎   | 3775/6015 [26:31<11:08,  3.35it/s]

 63%|██████▎   | 3776/6015 [26:31<10:19,  3.61it/s]

 63%|██████▎   | 3777/6015 [26:31<09:45,  3.82it/s]

 63%|██████▎   | 3778/6015 [26:32<09:20,  3.99it/s]

 63%|██████▎   | 3779/6015 [26:32<09:04,  4.11it/s]

 63%|██████▎   | 3780/6015 [26:32<08:52,  4.20it/s]

 63%|██████▎   | 3781/6015 [26:32<08:43,  4.27it/s]

 63%|██████▎   | 3782/6015 [26:33<08:37,  4.32it/s]

 63%|██████▎   | 3783/6015 [26:33<08:33,  4.35it/s]

 63%|██████▎   | 3784/6015 [26:33<08:29,  4.38it/s]

 63%|██████▎   | 3785/6015 [26:33<08:28,  4.39it/s]

 63%|██████▎   | 3786/6015 [26:34<08:27,  4.39it/s]

 63%|██████▎   | 3787/6015 [26:34<08:26,  4.40it/s]

 63%|██████▎   | 3788/6015 [26:34<08:26,  4.40it/s]

 63%|██████▎   | 3789/6015 [26:34<08:25,  4.40it/s]

 63%|██████▎   | 3790/6015 [26:34<08:24,  4.41it/s]

 63%|██████▎   | 3791/6015 [26:35<08:24,  4.41it/s]

 63%|██████▎   | 3792/6015 [26:35<08:23,  4.41it/s]

 63%|██████▎   | 3793/6015 [26:35<08:23,  4.41it/s]

 63%|██████▎   | 3794/6015 [26:35<08:23,  4.41it/s]

 63%|██████▎   | 3795/6015 [26:36<08:23,  4.41it/s]

 63%|██████▎   | 3796/6015 [26:36<08:22,  4.42it/s]

 63%|██████▎   | 3797/6015 [26:36<08:22,  4.41it/s]

 63%|██████▎   | 3798/6015 [26:36<08:23,  4.41it/s]

 63%|██████▎   | 3799/6015 [26:36<08:23,  4.40it/s]

 63%|██████▎   | 3800/6015 [26:37<08:24,  4.39it/s]

 63%|██████▎   | 3801/6015 [26:37<08:23,  4.40it/s]

 63%|██████▎   | 3802/6015 [26:37<08:25,  4.38it/s]

 63%|██████▎   | 3803/6015 [26:37<08:24,  4.39it/s]

 63%|██████▎   | 3804/6015 [26:38<08:22,  4.40it/s]

 63%|██████▎   | 3805/6015 [26:38<08:22,  4.40it/s]

 63%|██████▎   | 3806/6015 [26:38<08:22,  4.39it/s]

 63%|██████▎   | 3807/6015 [26:38<08:22,  4.40it/s]

 63%|██████▎   | 3808/6015 [26:39<08:21,  4.40it/s]

 63%|██████▎   | 3809/6015 [26:39<08:23,  4.38it/s]

 63%|██████▎   | 3810/6015 [26:39<08:22,  4.39it/s]

 63%|██████▎   | 3811/6015 [26:39<08:22,  4.38it/s]

 63%|██████▎   | 3812/6015 [26:39<08:21,  4.39it/s]

 63%|██████▎   | 3813/6015 [26:40<08:20,  4.40it/s]

 63%|██████▎   | 3814/6015 [26:40<08:21,  4.39it/s]

 63%|██████▎   | 3815/6015 [26:40<08:20,  4.39it/s]

 63%|██████▎   | 3816/6015 [26:40<08:21,  4.38it/s]

 63%|██████▎   | 3817/6015 [26:41<08:21,  4.39it/s]

 63%|██████▎   | 3818/6015 [26:41<08:20,  4.39it/s]

 63%|██████▎   | 3819/6015 [26:41<08:21,  4.38it/s]

 64%|██████▎   | 3820/6015 [26:41<08:20,  4.38it/s]

 64%|██████▎   | 3821/6015 [26:41<08:20,  4.39it/s]

 64%|██████▎   | 3822/6015 [26:42<08:18,  4.40it/s]

 64%|██████▎   | 3823/6015 [26:42<08:19,  4.39it/s]

 64%|██████▎   | 3824/6015 [26:42<08:17,  4.41it/s]

 64%|██████▎   | 3825/6015 [26:42<08:16,  4.41it/s]

 64%|██████▎   | 3826/6015 [26:43<08:17,  4.40it/s]

 64%|██████▎   | 3827/6015 [26:43<08:16,  4.41it/s]

 64%|██████▎   | 3828/6015 [26:43<08:16,  4.41it/s]

 64%|██████▎   | 3829/6015 [26:43<08:15,  4.41it/s]

 64%|██████▎   | 3830/6015 [26:44<08:17,  4.39it/s]

 64%|██████▎   | 3831/6015 [26:44<08:17,  4.39it/s]

 64%|██████▎   | 3832/6015 [26:44<08:16,  4.40it/s]

 64%|██████▎   | 3833/6015 [26:44<08:15,  4.41it/s]

 64%|██████▎   | 3834/6015 [26:44<08:15,  4.40it/s]

 64%|██████▍   | 3835/6015 [26:45<08:15,  4.40it/s]

 64%|██████▍   | 3836/6015 [26:45<08:15,  4.40it/s]

 64%|██████▍   | 3837/6015 [26:45<08:13,  4.41it/s]

 64%|██████▍   | 3838/6015 [26:45<08:13,  4.41it/s]

 64%|██████▍   | 3839/6015 [26:46<08:13,  4.41it/s]

 64%|██████▍   | 3840/6015 [26:46<08:13,  4.40it/s]

 64%|██████▍   | 3841/6015 [26:46<08:14,  4.40it/s]

 64%|██████▍   | 3842/6015 [26:46<08:12,  4.41it/s]

 64%|██████▍   | 3843/6015 [26:46<08:12,  4.41it/s]

 64%|██████▍   | 3844/6015 [26:47<08:12,  4.41it/s]

 64%|██████▍   | 3845/6015 [26:47<08:11,  4.41it/s]

 64%|██████▍   | 3846/6015 [26:47<08:12,  4.41it/s]

 64%|██████▍   | 3847/6015 [26:47<08:12,  4.41it/s]

 64%|██████▍   | 3848/6015 [26:48<08:11,  4.41it/s]

 64%|██████▍   | 3849/6015 [26:48<08:11,  4.40it/s]

 64%|██████▍   | 3850/6015 [26:48<08:13,  4.39it/s]

 64%|██████▍   | 3851/6015 [26:48<08:12,  4.40it/s]

 64%|██████▍   | 3852/6015 [26:49<08:12,  4.40it/s]

 64%|██████▍   | 3853/6015 [26:49<08:12,  4.39it/s]

 64%|██████▍   | 3854/6015 [26:49<08:11,  4.40it/s]

 64%|██████▍   | 3855/6015 [26:49<08:10,  4.40it/s]

 64%|██████▍   | 3856/6015 [26:49<08:10,  4.40it/s]

 64%|██████▍   | 3857/6015 [26:50<08:10,  4.40it/s]

 64%|██████▍   | 3858/6015 [26:50<08:11,  4.39it/s]

 64%|██████▍   | 3859/6015 [26:50<08:10,  4.39it/s]

 64%|██████▍   | 3860/6015 [26:50<08:10,  4.39it/s]

 64%|██████▍   | 3861/6015 [26:51<08:11,  4.38it/s]

 64%|██████▍   | 3862/6015 [26:51<08:11,  4.38it/s]

 64%|██████▍   | 3863/6015 [26:51<08:09,  4.39it/s]

 64%|██████▍   | 3864/6015 [26:51<08:09,  4.39it/s]

 64%|██████▍   | 3865/6015 [26:51<08:09,  4.40it/s]

 64%|██████▍   | 3866/6015 [26:52<08:09,  4.39it/s]

 64%|██████▍   | 3867/6015 [26:52<08:11,  4.37it/s]

 64%|██████▍   | 3868/6015 [26:52<08:10,  4.38it/s]

 64%|██████▍   | 3869/6015 [26:52<08:10,  4.37it/s]

 64%|██████▍   | 3870/6015 [26:53<08:08,  4.39it/s]

 64%|██████▍   | 3871/6015 [26:53<08:09,  4.38it/s]

 64%|██████▍   | 3872/6015 [26:53<08:09,  4.38it/s]

 64%|██████▍   | 3873/6015 [26:53<08:08,  4.39it/s]

 64%|██████▍   | 3874/6015 [26:54<08:07,  4.39it/s]

 64%|██████▍   | 3875/6015 [26:54<08:07,  4.39it/s]

 64%|██████▍   | 3876/6015 [26:54<08:07,  4.39it/s]

 64%|██████▍   | 3877/6015 [26:54<08:06,  4.39it/s]

 64%|██████▍   | 3878/6015 [26:54<08:07,  4.39it/s]

 64%|██████▍   | 3879/6015 [26:55<08:09,  4.36it/s]

 65%|██████▍   | 3880/6015 [26:55<08:08,  4.37it/s]

 65%|██████▍   | 3881/6015 [26:55<08:07,  4.38it/s]

 65%|██████▍   | 3882/6015 [26:55<08:06,  4.38it/s]

 65%|██████▍   | 3883/6015 [26:56<08:06,  4.38it/s]

 65%|██████▍   | 3884/6015 [26:56<08:05,  4.39it/s]

 65%|██████▍   | 3885/6015 [26:56<08:05,  4.39it/s]

 65%|██████▍   | 3886/6015 [26:56<08:06,  4.38it/s]

 65%|██████▍   | 3887/6015 [26:57<08:04,  4.39it/s]

 65%|██████▍   | 3888/6015 [26:57<08:04,  4.39it/s]

 65%|██████▍   | 3889/6015 [26:57<08:05,  4.38it/s]

 65%|██████▍   | 3890/6015 [26:57<08:04,  4.38it/s]

 65%|██████▍   | 3891/6015 [26:57<08:05,  4.37it/s]

 65%|██████▍   | 3892/6015 [26:58<08:04,  4.38it/s]

 65%|██████▍   | 3893/6015 [26:58<08:04,  4.38it/s]

 65%|██████▍   | 3894/6015 [26:58<08:04,  4.37it/s]

 65%|██████▍   | 3895/6015 [26:58<08:03,  4.38it/s]

 65%|██████▍   | 3896/6015 [26:59<08:03,  4.38it/s]

 65%|██████▍   | 3897/6015 [26:59<08:02,  4.39it/s]

 65%|██████▍   | 3898/6015 [26:59<08:02,  4.39it/s]

 65%|██████▍   | 3899/6015 [26:59<08:03,  4.37it/s]

 65%|██████▍   | 3900/6015 [26:59<08:04,  4.37it/s]

 65%|██████▍   | 3901/6015 [27:00<08:02,  4.38it/s]

 65%|██████▍   | 3902/6015 [27:00<08:03,  4.37it/s]

 65%|██████▍   | 3903/6015 [27:00<08:03,  4.37it/s]

 65%|██████▍   | 3904/6015 [27:00<08:03,  4.37it/s]

 65%|██████▍   | 3905/6015 [27:01<08:03,  4.36it/s]

 65%|██████▍   | 3906/6015 [27:01<08:03,  4.36it/s]

 65%|██████▍   | 3907/6015 [27:01<08:02,  4.37it/s]

 65%|██████▍   | 3908/6015 [27:01<08:02,  4.37it/s]

 65%|██████▍   | 3909/6015 [27:02<08:01,  4.38it/s]

 65%|██████▌   | 3910/6015 [27:02<08:01,  4.38it/s]

 65%|██████▌   | 3911/6015 [27:02<08:01,  4.37it/s]

 65%|██████▌   | 3912/6015 [27:02<08:01,  4.36it/s]

 65%|██████▌   | 3913/6015 [27:02<08:00,  4.37it/s]

 65%|██████▌   | 3914/6015 [27:03<08:00,  4.37it/s]

 65%|██████▌   | 3915/6015 [27:03<08:02,  4.35it/s]

 65%|██████▌   | 3916/6015 [27:03<08:01,  4.36it/s]

 65%|██████▌   | 3917/6015 [27:03<08:00,  4.37it/s]

 65%|██████▌   | 3918/6015 [27:04<07:59,  4.37it/s]

 65%|██████▌   | 3919/6015 [27:04<08:00,  4.36it/s]

 65%|██████▌   | 3920/6015 [27:04<08:00,  4.36it/s]

 65%|██████▌   | 3921/6015 [27:04<07:59,  4.37it/s]

 65%|██████▌   | 3922/6015 [27:05<08:00,  4.35it/s]

 65%|██████▌   | 3923/6015 [27:05<07:59,  4.37it/s]

 65%|██████▌   | 3924/6015 [27:05<07:58,  4.37it/s]

 65%|██████▌   | 3925/6015 [27:05<08:00,  4.35it/s]

 65%|██████▌   | 3926/6015 [27:05<07:58,  4.37it/s]

 65%|██████▌   | 3927/6015 [27:06<07:59,  4.36it/s]

 65%|██████▌   | 3928/6015 [27:06<07:57,  4.37it/s]

 65%|██████▌   | 3929/6015 [27:06<07:58,  4.36it/s]

 65%|██████▌   | 3930/6015 [27:06<07:57,  4.36it/s]

 65%|██████▌   | 3931/6015 [27:07<07:56,  4.37it/s]

 65%|██████▌   | 3932/6015 [27:07<07:57,  4.36it/s]

 65%|██████▌   | 3933/6015 [27:07<07:58,  4.36it/s]

 65%|██████▌   | 3934/6015 [27:07<08:02,  4.31it/s]

 65%|██████▌   | 3935/6015 [27:08<07:59,  4.34it/s]

 65%|██████▌   | 3936/6015 [27:08<07:57,  4.35it/s]

 65%|██████▌   | 3937/6015 [27:08<07:56,  4.36it/s]

 65%|██████▌   | 3938/6015 [27:08<07:56,  4.36it/s]

 65%|██████▌   | 3939/6015 [27:08<07:56,  4.36it/s]

 66%|██████▌   | 3940/6015 [27:09<07:56,  4.36it/s]

 66%|██████▌   | 3941/6015 [27:09<07:56,  4.35it/s]

 66%|██████▌   | 3942/6015 [27:09<07:54,  4.37it/s]

 66%|██████▌   | 3943/6015 [27:09<07:54,  4.37it/s]

 66%|██████▌   | 3944/6015 [27:10<07:56,  4.35it/s]

 66%|██████▌   | 3945/6015 [27:10<07:55,  4.36it/s]

 66%|██████▌   | 3946/6015 [27:10<07:55,  4.35it/s]

 66%|██████▌   | 3947/6015 [27:10<07:53,  4.36it/s]

 66%|██████▌   | 3948/6015 [27:10<07:53,  4.37it/s]

 66%|██████▌   | 3949/6015 [27:11<07:52,  4.37it/s]

 66%|██████▌   | 3950/6015 [27:11<07:52,  4.37it/s]

 66%|██████▌   | 3951/6015 [27:11<07:53,  4.36it/s]

 66%|██████▌   | 3952/6015 [27:11<07:53,  4.36it/s]

 66%|██████▌   | 3953/6015 [27:12<07:56,  4.32it/s]

 66%|██████▌   | 3954/6015 [27:12<07:55,  4.34it/s]

 66%|██████▌   | 3955/6015 [27:12<07:53,  4.35it/s]

 66%|██████▌   | 3956/6015 [27:12<07:52,  4.36it/s]

 66%|██████▌   | 3957/6015 [27:13<07:53,  4.35it/s]

 66%|██████▌   | 3958/6015 [27:13<07:52,  4.36it/s]

 66%|██████▌   | 3959/6015 [27:13<07:51,  4.36it/s]

 66%|██████▌   | 3960/6015 [27:13<07:52,  4.35it/s]

 66%|██████▌   | 3961/6015 [27:13<07:50,  4.37it/s]

 66%|██████▌   | 3962/6015 [27:14<07:50,  4.36it/s]

 66%|██████▌   | 3963/6015 [27:14<07:49,  4.37it/s]

 66%|██████▌   | 3964/6015 [27:14<07:49,  4.37it/s]

 66%|██████▌   | 3965/6015 [27:14<07:49,  4.37it/s]

 66%|██████▌   | 3966/6015 [27:15<07:48,  4.38it/s]

 66%|██████▌   | 3967/6015 [27:15<07:48,  4.37it/s]

 66%|██████▌   | 3968/6015 [27:15<07:48,  4.37it/s]

 66%|██████▌   | 3969/6015 [27:15<07:48,  4.36it/s]

 66%|██████▌   | 3970/6015 [27:16<07:49,  4.36it/s]

 66%|██████▌   | 3971/6015 [27:16<07:49,  4.36it/s]

 66%|██████▌   | 3972/6015 [27:16<07:49,  4.35it/s]

 66%|██████▌   | 3973/6015 [27:16<07:49,  4.35it/s]

 66%|██████▌   | 3974/6015 [27:16<07:48,  4.36it/s]

 66%|██████▌   | 3975/6015 [27:17<07:48,  4.36it/s]

 66%|██████▌   | 3976/6015 [27:17<07:48,  4.35it/s]

 66%|██████▌   | 3977/6015 [27:17<07:48,  4.35it/s]

 66%|██████▌   | 3978/6015 [27:17<07:47,  4.36it/s]

 66%|██████▌   | 3979/6015 [27:18<07:47,  4.35it/s]

 66%|██████▌   | 3980/6015 [27:18<07:46,  4.36it/s]

 66%|██████▌   | 3981/6015 [27:18<07:45,  4.37it/s]

 66%|██████▌   | 3982/6015 [27:18<07:47,  4.35it/s]

 66%|██████▌   | 3983/6015 [27:19<07:46,  4.36it/s]

 66%|██████▌   | 3984/6015 [27:19<07:46,  4.36it/s]

 66%|██████▋   | 3985/6015 [27:19<07:44,  4.37it/s]

 66%|██████▋   | 3986/6015 [27:19<07:44,  4.36it/s]

 66%|██████▋   | 3987/6015 [27:19<07:45,  4.36it/s]

 66%|██████▋   | 3988/6015 [27:20<07:45,  4.36it/s]

 66%|██████▋   | 3989/6015 [27:20<07:45,  4.36it/s]

 66%|██████▋   | 3990/6015 [27:20<07:44,  4.36it/s]

 66%|██████▋   | 3991/6015 [27:20<07:44,  4.35it/s]

 66%|██████▋   | 3992/6015 [27:21<07:45,  4.35it/s]

 66%|██████▋   | 3993/6015 [27:21<07:44,  4.35it/s]

 66%|██████▋   | 3994/6015 [27:21<07:43,  4.36it/s]

 66%|██████▋   | 3995/6015 [27:21<07:43,  4.36it/s]

 66%|██████▋   | 3996/6015 [27:22<07:43,  4.35it/s]

 66%|██████▋   | 3997/6015 [27:22<07:44,  4.34it/s]

 66%|██████▋   | 3998/6015 [27:22<07:45,  4.33it/s]

 66%|██████▋   | 3999/6015 [27:22<07:43,  4.35it/s]

 67%|██████▋   | 4000/6015 [27:22<07:42,  4.36it/s]

 67%|██████▋   | 4001/6015 [27:23<07:42,  4.35it/s]

 67%|██████▋   | 4002/6015 [27:23<07:41,  4.37it/s]

 67%|██████▋   | 4003/6015 [27:23<07:40,  4.37it/s]

 67%|██████▋   | 4004/6015 [27:23<07:40,  4.36it/s]

 67%|██████▋   | 4005/6015 [27:24<07:40,  4.36it/s]

 67%|██████▋   | 4006/6015 [27:24<07:41,  4.35it/s]

 67%|██████▋   | 4007/6015 [27:24<07:40,  4.36it/s]

 67%|██████▋   | 4008/6015 [27:24<07:39,  4.36it/s]

 67%|██████▋   | 4009/6015 [27:24<07:40,  4.35it/s]

 67%|██████▋   | 4010/6015 [27:25<07:39,  4.36it/s]

 67%|██████▋   | 4011/6015 [27:25<07:39,  4.36it/s]

 67%|██████▋   | 4012/6015 [27:25<07:39,  4.36it/s]

 67%|██████▋   | 4013/6015 [27:25<07:39,  4.35it/s]

 67%|██████▋   | 4014/6015 [27:26<07:40,  4.35it/s]

 67%|██████▋   | 4015/6015 [27:26<07:38,  4.36it/s]

 67%|██████▋   | 4016/6015 [27:26<07:38,  4.36it/s]

 67%|██████▋   | 4017/6015 [27:26<07:37,  4.36it/s]

 67%|██████▋   | 4018/6015 [27:27<07:36,  4.37it/s]

 67%|██████▋   | 4019/6015 [27:27<07:36,  4.38it/s]

 67%|██████▋   | 4020/6015 [27:27<07:35,  4.38it/s]

 67%|██████▋   | 4021/6015 [27:27<07:35,  4.38it/s]

 67%|██████▋   | 4022/6015 [27:27<07:36,  4.37it/s]

 67%|██████▋   | 4023/6015 [27:28<07:36,  4.36it/s]

 67%|██████▋   | 4024/6015 [27:28<07:37,  4.36it/s]

 67%|██████▋   | 4025/6015 [27:28<07:37,  4.35it/s]

 67%|██████▋   | 4026/6015 [27:28<07:37,  4.35it/s]

 67%|██████▋   | 4027/6015 [27:29<07:36,  4.36it/s]

 67%|██████▋   | 4028/6015 [27:29<07:36,  4.35it/s]

 67%|██████▋   | 4029/6015 [27:29<07:36,  4.35it/s]

 67%|██████▋   | 4030/6015 [27:29<07:35,  4.35it/s]

 67%|██████▋   | 4031/6015 [27:30<07:37,  4.34it/s]

 67%|██████▋   | 4032/6015 [27:30<07:35,  4.35it/s]

 67%|██████▋   | 4033/6015 [27:30<07:34,  4.36it/s]

 67%|██████▋   | 4034/6015 [27:30<07:35,  4.35it/s]

 67%|██████▋   | 4035/6015 [27:30<07:34,  4.35it/s]

 67%|██████▋   | 4036/6015 [27:31<07:35,  4.35it/s]

 67%|██████▋   | 4037/6015 [27:31<07:34,  4.35it/s]

 67%|██████▋   | 4038/6015 [27:31<07:34,  4.35it/s]

 67%|██████▋   | 4039/6015 [27:31<07:33,  4.36it/s]

 67%|██████▋   | 4040/6015 [27:32<07:33,  4.36it/s]

 67%|██████▋   | 4041/6015 [27:32<07:33,  4.35it/s]

 67%|██████▋   | 4042/6015 [27:32<07:34,  4.34it/s]

 67%|██████▋   | 4043/6015 [27:32<07:33,  4.35it/s]

 67%|██████▋   | 4044/6015 [27:33<07:33,  4.35it/s]

 67%|██████▋   | 4045/6015 [27:33<07:33,  4.34it/s]

 67%|██████▋   | 4046/6015 [27:33<07:32,  4.35it/s]

 67%|██████▋   | 4047/6015 [27:33<07:32,  4.35it/s]

 67%|██████▋   | 4048/6015 [27:33<07:31,  4.35it/s]

 67%|██████▋   | 4049/6015 [27:34<07:31,  4.35it/s]

 67%|██████▋   | 4050/6015 [27:34<07:31,  4.36it/s]

 67%|██████▋   | 4051/6015 [27:34<07:30,  4.36it/s]

 67%|██████▋   | 4052/6015 [27:34<07:30,  4.36it/s]

 67%|██████▋   | 4053/6015 [27:35<07:29,  4.36it/s]

 67%|██████▋   | 4054/6015 [27:35<07:30,  4.35it/s]

 67%|██████▋   | 4055/6015 [27:35<07:31,  4.34it/s]

 67%|██████▋   | 4056/6015 [27:35<07:29,  4.35it/s]

 67%|██████▋   | 4057/6015 [27:36<07:30,  4.34it/s]

 67%|██████▋   | 4058/6015 [27:36<07:30,  4.34it/s]

 67%|██████▋   | 4059/6015 [27:36<07:29,  4.35it/s]

 67%|██████▋   | 4060/6015 [27:36<07:29,  4.35it/s]

 68%|██████▊   | 4061/6015 [27:36<07:28,  4.35it/s]

 68%|██████▊   | 4062/6015 [27:37<07:28,  4.35it/s]

 68%|██████▊   | 4063/6015 [27:37<07:28,  4.35it/s]

 68%|██████▊   | 4064/6015 [27:37<07:27,  4.36it/s]

 68%|██████▊   | 4065/6015 [27:37<07:27,  4.36it/s]

 68%|██████▊   | 4066/6015 [27:38<07:27,  4.35it/s]

 68%|██████▊   | 4067/6015 [27:38<07:26,  4.37it/s]

 68%|██████▊   | 4068/6015 [27:38<07:25,  4.37it/s]

 68%|██████▊   | 4069/6015 [27:38<07:25,  4.37it/s]

 68%|██████▊   | 4070/6015 [27:38<07:24,  4.38it/s]

 68%|██████▊   | 4071/6015 [27:39<07:24,  4.38it/s]

 68%|██████▊   | 4072/6015 [27:39<07:23,  4.38it/s]

 68%|██████▊   | 4073/6015 [27:39<07:24,  4.37it/s]

 68%|██████▊   | 4074/6015 [27:39<07:24,  4.36it/s]

 68%|██████▊   | 4075/6015 [27:40<07:24,  4.37it/s]

 68%|██████▊   | 4076/6015 [27:40<07:24,  4.37it/s]

 68%|██████▊   | 4077/6015 [27:40<07:24,  4.36it/s]

 68%|██████▊   | 4078/6015 [27:40<07:23,  4.37it/s]

 68%|██████▊   | 4079/6015 [27:41<07:24,  4.36it/s]

 68%|██████▊   | 4080/6015 [27:41<07:24,  4.35it/s]

 68%|██████▊   | 4081/6015 [27:41<07:25,  4.34it/s]

 68%|██████▊   | 4082/6015 [27:41<07:24,  4.34it/s]

 68%|██████▊   | 4083/6015 [27:41<07:24,  4.35it/s]

 68%|██████▊   | 4084/6015 [27:42<07:24,  4.34it/s]

 68%|██████▊   | 4085/6015 [27:42<07:24,  4.34it/s]

 68%|██████▊   | 4086/6015 [27:42<07:23,  4.35it/s]

 68%|██████▊   | 4087/6015 [27:42<07:22,  4.35it/s]

 68%|██████▊   | 4088/6015 [27:43<07:23,  4.35it/s]

 68%|██████▊   | 4089/6015 [27:43<07:22,  4.36it/s]

 68%|██████▊   | 4090/6015 [27:43<07:22,  4.35it/s]

 68%|██████▊   | 4091/6015 [27:43<07:23,  4.34it/s]

 68%|██████▊   | 4092/6015 [27:44<07:23,  4.34it/s]

 68%|██████▊   | 4093/6015 [27:44<07:22,  4.34it/s]

 68%|██████▊   | 4094/6015 [27:44<07:23,  4.34it/s]

 68%|██████▊   | 4095/6015 [27:44<07:22,  4.34it/s]

 68%|██████▊   | 4096/6015 [27:44<07:21,  4.34it/s]

 68%|██████▊   | 4097/6015 [27:45<07:20,  4.35it/s]

 68%|██████▊   | 4098/6015 [27:45<07:19,  4.36it/s]

 68%|██████▊   | 4099/6015 [27:45<07:20,  4.35it/s]

 68%|██████▊   | 4100/6015 [27:45<07:19,  4.35it/s]

 68%|██████▊   | 4101/6015 [27:46<07:20,  4.35it/s]

 68%|██████▊   | 4102/6015 [27:46<07:25,  4.29it/s]

 68%|██████▊   | 4103/6015 [27:46<07:23,  4.31it/s]

 68%|██████▊   | 4104/6015 [27:46<07:22,  4.32it/s]

 68%|██████▊   | 4105/6015 [27:47<07:21,  4.33it/s]

 68%|██████▊   | 4106/6015 [27:47<07:20,  4.34it/s]

 68%|██████▊   | 4107/6015 [27:47<07:20,  4.33it/s]

 68%|██████▊   | 4108/6015 [27:47<07:19,  4.34it/s]

 68%|██████▊   | 4109/6015 [27:47<07:19,  4.33it/s]

 68%|██████▊   | 4110/6015 [27:48<07:19,  4.33it/s]

 68%|██████▊   | 4111/6015 [27:48<07:18,  4.34it/s]

 68%|██████▊   | 4112/6015 [27:48<07:18,  4.34it/s]

 68%|██████▊   | 4113/6015 [27:48<07:18,  4.34it/s]

 68%|██████▊   | 4114/6015 [27:49<07:17,  4.34it/s]

 68%|██████▊   | 4115/6015 [27:49<07:17,  4.34it/s]

 68%|██████▊   | 4116/6015 [27:49<07:18,  4.34it/s]

 68%|██████▊   | 4117/6015 [27:49<07:18,  4.33it/s]

 68%|██████▊   | 4118/6015 [27:50<07:17,  4.33it/s]

 68%|██████▊   | 4119/6015 [27:50<07:17,  4.33it/s]

 68%|██████▊   | 4120/6015 [27:50<07:17,  4.33it/s]

 69%|██████▊   | 4121/6015 [27:50<07:16,  4.33it/s]

 69%|██████▊   | 4122/6015 [27:50<07:16,  4.34it/s]

 69%|██████▊   | 4123/6015 [27:51<07:15,  4.34it/s]

 69%|██████▊   | 4124/6015 [27:51<07:15,  4.34it/s]

 69%|██████▊   | 4125/6015 [27:51<07:14,  4.35it/s]

 69%|██████▊   | 4126/6015 [27:51<07:14,  4.35it/s]

 69%|██████▊   | 4127/6015 [27:52<07:15,  4.34it/s]

 69%|██████▊   | 4128/6015 [27:52<07:14,  4.34it/s]

 69%|██████▊   | 4129/6015 [27:52<07:14,  4.34it/s]

 69%|██████▊   | 4130/6015 [27:52<07:13,  4.35it/s]

 69%|██████▊   | 4131/6015 [27:53<07:13,  4.35it/s]

 69%|██████▊   | 4132/6015 [27:53<07:12,  4.36it/s]

 69%|██████▊   | 4133/6015 [27:53<07:13,  4.34it/s]

 69%|██████▊   | 4134/6015 [27:53<07:12,  4.35it/s]

 69%|██████▊   | 4135/6015 [27:53<07:12,  4.34it/s]

 69%|██████▉   | 4136/6015 [27:54<07:12,  4.35it/s]

 69%|██████▉   | 4137/6015 [27:54<07:12,  4.35it/s]

 69%|██████▉   | 4138/6015 [27:54<07:12,  4.34it/s]

 69%|██████▉   | 4139/6015 [27:54<07:11,  4.35it/s]

 69%|██████▉   | 4140/6015 [27:55<07:11,  4.34it/s]

 69%|██████▉   | 4141/6015 [27:55<07:11,  4.34it/s]

 69%|██████▉   | 4142/6015 [27:55<07:10,  4.35it/s]

 69%|██████▉   | 4143/6015 [27:55<07:12,  4.33it/s]

 69%|██████▉   | 4144/6015 [27:56<07:11,  4.34it/s]

 69%|██████▉   | 4145/6015 [27:56<07:11,  4.33it/s]

 69%|██████▉   | 4146/6015 [27:56<07:11,  4.33it/s]

 69%|██████▉   | 4147/6015 [27:56<07:10,  4.34it/s]

 69%|██████▉   | 4148/6015 [27:56<07:10,  4.34it/s]

 69%|██████▉   | 4149/6015 [27:57<07:10,  4.34it/s]

 69%|██████▉   | 4150/6015 [27:57<07:10,  4.34it/s]

 69%|██████▉   | 4151/6015 [27:57<07:10,  4.33it/s]

 69%|██████▉   | 4152/6015 [27:57<07:09,  4.33it/s]

 69%|██████▉   | 4153/6015 [27:58<07:09,  4.33it/s]

 69%|██████▉   | 4154/6015 [27:58<07:10,  4.33it/s]

 69%|██████▉   | 4155/6015 [27:58<07:09,  4.33it/s]

 69%|██████▉   | 4156/6015 [27:58<07:09,  4.33it/s]

 69%|██████▉   | 4157/6015 [27:59<07:08,  4.33it/s]

 69%|██████▉   | 4158/6015 [27:59<07:08,  4.34it/s]

 69%|██████▉   | 4159/6015 [27:59<07:08,  4.34it/s]

 69%|██████▉   | 4160/6015 [27:59<07:09,  4.32it/s]

 69%|██████▉   | 4161/6015 [27:59<07:08,  4.33it/s]

 69%|██████▉   | 4162/6015 [28:00<07:08,  4.33it/s]

 69%|██████▉   | 4163/6015 [28:00<07:07,  4.33it/s]

 69%|██████▉   | 4164/6015 [28:00<07:08,  4.32it/s]

 69%|██████▉   | 4165/6015 [28:00<07:08,  4.32it/s]

 69%|██████▉   | 4166/6015 [28:01<07:07,  4.33it/s]

 69%|██████▉   | 4167/6015 [28:01<07:07,  4.32it/s]

 69%|██████▉   | 4168/6015 [28:01<07:07,  4.32it/s]

 69%|██████▉   | 4169/6015 [28:01<07:07,  4.32it/s]

 69%|██████▉   | 4170/6015 [28:02<07:07,  4.32it/s]

 69%|██████▉   | 4171/6015 [28:02<07:06,  4.32it/s]

 69%|██████▉   | 4172/6015 [28:02<07:05,  4.33it/s]

 69%|██████▉   | 4173/6015 [28:02<07:06,  4.32it/s]

 69%|██████▉   | 4174/6015 [28:02<07:05,  4.33it/s]

 69%|██████▉   | 4175/6015 [28:03<07:06,  4.31it/s]

 69%|██████▉   | 4176/6015 [28:03<07:04,  4.33it/s]

 69%|██████▉   | 4177/6015 [28:03<07:05,  4.32it/s]

 69%|██████▉   | 4178/6015 [28:03<07:05,  4.32it/s]

 69%|██████▉   | 4179/6015 [28:04<07:04,  4.32it/s]

 69%|██████▉   | 4180/6015 [28:04<07:04,  4.33it/s]

 70%|██████▉   | 4181/6015 [28:04<07:04,  4.33it/s]

 70%|██████▉   | 4182/6015 [28:04<07:03,  4.33it/s]

 70%|██████▉   | 4183/6015 [28:05<07:03,  4.33it/s]

 70%|██████▉   | 4184/6015 [28:05<07:03,  4.33it/s]

 70%|██████▉   | 4185/6015 [28:05<07:03,  4.33it/s]

 70%|██████▉   | 4186/6015 [28:05<07:03,  4.32it/s]

 70%|██████▉   | 4187/6015 [28:05<07:03,  4.31it/s]

 70%|██████▉   | 4188/6015 [28:06<07:03,  4.31it/s]

 70%|██████▉   | 4189/6015 [28:06<07:03,  4.31it/s]

 70%|██████▉   | 4190/6015 [28:06<07:02,  4.32it/s]

 70%|██████▉   | 4191/6015 [28:06<07:02,  4.32it/s]

 70%|██████▉   | 4192/6015 [28:07<07:01,  4.32it/s]

 70%|██████▉   | 4193/6015 [28:07<07:01,  4.32it/s]

 70%|██████▉   | 4194/6015 [28:07<07:01,  4.32it/s]

 70%|██████▉   | 4195/6015 [28:07<07:01,  4.32it/s]

 70%|██████▉   | 4196/6015 [28:08<07:00,  4.32it/s]

 70%|██████▉   | 4197/6015 [28:08<07:00,  4.32it/s]

 70%|██████▉   | 4198/6015 [28:08<07:00,  4.32it/s]

 70%|██████▉   | 4199/6015 [28:08<07:00,  4.32it/s]

 70%|██████▉   | 4200/6015 [28:08<06:59,  4.32it/s]

 70%|██████▉   | 4201/6015 [28:09<07:00,  4.32it/s]

 70%|██████▉   | 4202/6015 [28:09<06:59,  4.32it/s]

 70%|██████▉   | 4203/6015 [28:09<06:59,  4.32it/s]

 70%|██████▉   | 4204/6015 [28:09<06:59,  4.32it/s]

 70%|██████▉   | 4205/6015 [28:10<06:59,  4.32it/s]

 70%|██████▉   | 4206/6015 [28:10<06:58,  4.32it/s]

 70%|██████▉   | 4207/6015 [28:10<06:58,  4.32it/s]

 70%|██████▉   | 4208/6015 [28:10<06:57,  4.33it/s]

 70%|██████▉   | 4209/6015 [28:11<06:58,  4.32it/s]

 70%|██████▉   | 4210/6015 [28:11<06:57,  4.32it/s]

 70%|███████   | 4211/6015 [28:11<06:56,  4.33it/s]

 70%|███████   | 4212/6015 [28:11<06:57,  4.32it/s]

 70%|███████   | 4213/6015 [28:11<06:57,  4.32it/s]

 70%|███████   | 4214/6015 [28:12<06:56,  4.33it/s]

 70%|███████   | 4215/6015 [28:12<06:56,  4.32it/s]

 70%|███████   | 4216/6015 [28:12<06:55,  4.33it/s]

 70%|███████   | 4217/6015 [28:12<06:55,  4.33it/s]

 70%|███████   | 4218/6015 [28:13<06:54,  4.33it/s]

 70%|███████   | 4219/6015 [28:13<06:56,  4.32it/s]

 70%|███████   | 4220/6015 [28:13<06:55,  4.32it/s]

 70%|███████   | 4221/6015 [28:13<06:54,  4.33it/s]

 70%|███████   | 4222/6015 [28:14<06:54,  4.33it/s]

 70%|███████   | 4223/6015 [28:14<06:54,  4.32it/s]

 70%|███████   | 4224/6015 [28:14<06:54,  4.33it/s]

 70%|███████   | 4225/6015 [28:14<06:54,  4.32it/s]

 70%|███████   | 4226/6015 [28:14<06:55,  4.30it/s]

 70%|███████   | 4227/6015 [28:15<06:55,  4.30it/s]

 70%|███████   | 4228/6015 [28:15<06:55,  4.30it/s]

 70%|███████   | 4229/6015 [28:15<06:55,  4.30it/s]

 70%|███████   | 4230/6015 [28:15<06:55,  4.30it/s]

 70%|███████   | 4231/6015 [28:16<06:54,  4.30it/s]

 70%|███████   | 4232/6015 [28:16<06:55,  4.29it/s]

 70%|███████   | 4233/6015 [28:16<06:54,  4.30it/s]

 70%|███████   | 4234/6015 [28:16<06:54,  4.30it/s]

 70%|███████   | 4235/6015 [28:17<06:53,  4.30it/s]

 70%|███████   | 4236/6015 [28:17<06:53,  4.30it/s]

 70%|███████   | 4237/6015 [28:17<06:53,  4.30it/s]

 70%|███████   | 4238/6015 [28:17<06:53,  4.30it/s]

 70%|███████   | 4239/6015 [28:18<06:53,  4.29it/s]

 70%|███████   | 4240/6015 [28:18<06:53,  4.29it/s]

 71%|███████   | 4241/6015 [28:18<06:53,  4.29it/s]

 71%|███████   | 4242/6015 [28:18<06:52,  4.30it/s]

 71%|███████   | 4243/6015 [28:18<06:51,  4.30it/s]

 71%|███████   | 4244/6015 [28:19<06:52,  4.30it/s]

 71%|███████   | 4245/6015 [28:19<06:51,  4.30it/s]

 71%|███████   | 4246/6015 [28:19<06:51,  4.30it/s]

 71%|███████   | 4247/6015 [28:19<06:50,  4.30it/s]

 71%|███████   | 4248/6015 [28:20<06:50,  4.30it/s]

 71%|███████   | 4249/6015 [28:20<06:50,  4.30it/s]

 71%|███████   | 4250/6015 [28:20<06:50,  4.30it/s]

 71%|███████   | 4251/6015 [28:20<06:50,  4.30it/s]

 71%|███████   | 4252/6015 [28:21<06:49,  4.30it/s]

 71%|███████   | 4253/6015 [28:21<06:49,  4.30it/s]

 71%|███████   | 4254/6015 [28:21<06:50,  4.29it/s]

 71%|███████   | 4255/6015 [28:21<06:49,  4.30it/s]

 71%|███████   | 4256/6015 [28:21<06:49,  4.30it/s]

 71%|███████   | 4257/6015 [28:22<06:48,  4.30it/s]

 71%|███████   | 4258/6015 [28:22<06:48,  4.30it/s]

 71%|███████   | 4259/6015 [28:22<06:48,  4.30it/s]

 71%|███████   | 4260/6015 [28:22<06:48,  4.30it/s]

 71%|███████   | 4261/6015 [28:23<06:48,  4.30it/s]

 71%|███████   | 4262/6015 [28:23<06:47,  4.30it/s]

 71%|███████   | 4263/6015 [28:23<06:47,  4.30it/s]

 71%|███████   | 4264/6015 [28:23<06:46,  4.30it/s]

 71%|███████   | 4265/6015 [28:24<06:47,  4.30it/s]

 71%|███████   | 4266/6015 [28:24<06:46,  4.30it/s]

 71%|███████   | 4267/6015 [28:24<06:47,  4.29it/s]

 71%|███████   | 4268/6015 [28:24<06:46,  4.29it/s]

 71%|███████   | 4269/6015 [28:25<06:46,  4.29it/s]

 71%|███████   | 4270/6015 [28:25<06:45,  4.30it/s]

 71%|███████   | 4271/6015 [28:25<06:44,  4.31it/s]

 71%|███████   | 4272/6015 [28:25<06:44,  4.31it/s]

 71%|███████   | 4273/6015 [28:25<06:45,  4.30it/s]

 71%|███████   | 4274/6015 [28:26<06:47,  4.27it/s]

 71%|███████   | 4275/6015 [28:26<06:46,  4.28it/s]

 71%|███████   | 4276/6015 [28:26<06:45,  4.29it/s]

 71%|███████   | 4277/6015 [28:26<06:45,  4.29it/s]

 71%|███████   | 4278/6015 [28:27<06:45,  4.28it/s]

 71%|███████   | 4279/6015 [28:27<06:46,  4.27it/s]

 71%|███████   | 4280/6015 [28:27<06:46,  4.27it/s]

 71%|███████   | 4281/6015 [28:27<06:46,  4.27it/s]

 71%|███████   | 4282/6015 [28:28<06:45,  4.28it/s]

 71%|███████   | 4283/6015 [28:28<06:45,  4.27it/s]

 71%|███████   | 4284/6015 [28:28<06:45,  4.27it/s]

 71%|███████   | 4285/6015 [28:28<06:45,  4.27it/s]

 71%|███████▏  | 4286/6015 [28:28<06:44,  4.28it/s]

 71%|███████▏  | 4287/6015 [28:29<06:43,  4.28it/s]

 71%|███████▏  | 4288/6015 [28:29<06:43,  4.28it/s]

 71%|███████▏  | 4289/6015 [28:29<06:43,  4.28it/s]

 71%|███████▏  | 4290/6015 [28:29<06:43,  4.28it/s]

 71%|███████▏  | 4291/6015 [28:30<06:43,  4.27it/s]

 71%|███████▏  | 4292/6015 [28:30<06:43,  4.27it/s]

 71%|███████▏  | 4293/6015 [28:30<06:41,  4.28it/s]

 71%|███████▏  | 4294/6015 [28:30<06:41,  4.29it/s]

 71%|███████▏  | 4295/6015 [28:31<06:41,  4.28it/s]

 71%|███████▏  | 4296/6015 [28:31<06:40,  4.29it/s]

 71%|███████▏  | 4297/6015 [28:31<06:41,  4.28it/s]

 71%|███████▏  | 4298/6015 [28:31<06:40,  4.28it/s]

 71%|███████▏  | 4299/6015 [28:32<06:40,  4.28it/s]

 71%|███████▏  | 4300/6015 [28:32<06:41,  4.27it/s]

 72%|███████▏  | 4301/6015 [28:32<06:40,  4.28it/s]

 72%|███████▏  | 4302/6015 [28:32<06:40,  4.28it/s]

 72%|███████▏  | 4303/6015 [28:32<06:41,  4.26it/s]

 72%|███████▏  | 4304/6015 [28:33<06:41,  4.26it/s]

 72%|███████▏  | 4305/6015 [28:33<06:41,  4.26it/s]

 72%|███████▏  | 4306/6015 [28:33<06:41,  4.26it/s]

 72%|███████▏  | 4307/6015 [28:33<06:40,  4.27it/s]

 72%|███████▏  | 4308/6015 [28:34<06:39,  4.27it/s]

 72%|███████▏  | 4309/6015 [28:34<06:39,  4.28it/s]

 72%|███████▏  | 4310/6015 [28:34<06:39,  4.27it/s]

 72%|███████▏  | 4311/6015 [28:34<06:38,  4.27it/s]

 72%|███████▏  | 4312/6015 [28:35<06:38,  4.27it/s]

 72%|███████▏  | 4313/6015 [28:35<06:39,  4.26it/s]

 72%|███████▏  | 4314/6015 [28:35<06:38,  4.27it/s]

 72%|███████▏  | 4315/6015 [28:35<06:38,  4.26it/s]

 72%|███████▏  | 4316/6015 [28:35<06:38,  4.27it/s]

 72%|███████▏  | 4317/6015 [28:36<06:37,  4.27it/s]

 72%|███████▏  | 4318/6015 [28:36<06:37,  4.27it/s]

 72%|███████▏  | 4319/6015 [28:36<06:36,  4.27it/s]

 72%|███████▏  | 4320/6015 [28:36<06:36,  4.27it/s]

 72%|███████▏  | 4321/6015 [28:37<06:35,  4.28it/s]

 72%|███████▏  | 4322/6015 [28:37<06:35,  4.28it/s]

 72%|███████▏  | 4323/6015 [28:37<06:36,  4.27it/s]

 72%|███████▏  | 4324/6015 [28:37<06:35,  4.27it/s]

 72%|███████▏  | 4325/6015 [28:38<06:35,  4.27it/s]

 72%|███████▏  | 4326/6015 [28:38<06:34,  4.28it/s]

 72%|███████▏  | 4327/6015 [28:38<06:35,  4.27it/s]

 72%|███████▏  | 4328/6015 [28:38<06:35,  4.27it/s]

 72%|███████▏  | 4329/6015 [28:39<06:34,  4.28it/s]

 72%|███████▏  | 4330/6015 [28:39<06:34,  4.27it/s]

 72%|███████▏  | 4331/6015 [28:39<06:34,  4.27it/s]

 72%|███████▏  | 4332/6015 [28:39<06:33,  4.28it/s]

 72%|███████▏  | 4333/6015 [28:39<06:32,  4.28it/s]

 72%|███████▏  | 4334/6015 [28:40<06:32,  4.28it/s]

 72%|███████▏  | 4335/6015 [28:40<06:33,  4.27it/s]

 72%|███████▏  | 4336/6015 [28:40<06:33,  4.27it/s]

 72%|███████▏  | 4337/6015 [28:40<06:33,  4.27it/s]

 72%|███████▏  | 4338/6015 [28:41<06:33,  4.26it/s]

 72%|███████▏  | 4339/6015 [28:41<06:32,  4.27it/s]

 72%|███████▏  | 4340/6015 [28:41<06:32,  4.26it/s]

 72%|███████▏  | 4341/6015 [28:41<06:32,  4.27it/s]

 72%|███████▏  | 4342/6015 [28:42<06:33,  4.26it/s]

 72%|███████▏  | 4343/6015 [28:42<06:34,  4.24it/s]

 72%|███████▏  | 4344/6015 [28:42<06:32,  4.25it/s]

 72%|███████▏  | 4345/6015 [28:42<06:32,  4.26it/s]

 72%|███████▏  | 4346/6015 [28:43<06:31,  4.26it/s]

 72%|███████▏  | 4347/6015 [28:43<06:30,  4.27it/s]

 72%|███████▏  | 4348/6015 [28:43<06:30,  4.26it/s]

 72%|███████▏  | 4349/6015 [28:43<06:30,  4.27it/s]

 72%|███████▏  | 4350/6015 [28:43<06:30,  4.27it/s]

 72%|███████▏  | 4351/6015 [28:44<06:31,  4.26it/s]

 72%|███████▏  | 4352/6015 [28:44<06:30,  4.26it/s]

 72%|███████▏  | 4353/6015 [28:44<06:29,  4.26it/s]

 72%|███████▏  | 4354/6015 [28:44<06:29,  4.27it/s]

 72%|███████▏  | 4355/6015 [28:45<06:29,  4.27it/s]

 72%|███████▏  | 4356/6015 [28:45<06:30,  4.25it/s]

 72%|███████▏  | 4357/6015 [28:45<06:29,  4.25it/s]

 72%|███████▏  | 4358/6015 [28:45<06:30,  4.25it/s]

 72%|███████▏  | 4359/6015 [28:46<06:28,  4.26it/s]

 72%|███████▏  | 4360/6015 [28:46<06:28,  4.26it/s]

 73%|███████▎  | 4361/6015 [28:46<06:32,  4.21it/s]

 73%|███████▎  | 4362/6015 [28:46<06:31,  4.22it/s]

 73%|███████▎  | 4363/6015 [28:47<06:30,  4.24it/s]

 73%|███████▎  | 4364/6015 [28:47<06:28,  4.25it/s]

 73%|███████▎  | 4365/6015 [28:47<06:27,  4.25it/s]

 73%|███████▎  | 4366/6015 [28:47<06:28,  4.25it/s]

 73%|███████▎  | 4367/6015 [28:47<06:27,  4.25it/s]

 73%|███████▎  | 4368/6015 [28:48<06:27,  4.25it/s]

 73%|███████▎  | 4369/6015 [28:48<06:26,  4.26it/s]

 73%|███████▎  | 4370/6015 [28:48<06:26,  4.26it/s]

 73%|███████▎  | 4371/6015 [28:48<06:25,  4.26it/s]

 73%|███████▎  | 4372/6015 [28:49<06:25,  4.26it/s]

 73%|███████▎  | 4373/6015 [28:49<06:25,  4.25it/s]

 73%|███████▎  | 4374/6015 [28:49<06:25,  4.26it/s]

 73%|███████▎  | 4375/6015 [28:49<06:25,  4.26it/s]

 73%|███████▎  | 4376/6015 [28:50<06:25,  4.25it/s]

 73%|███████▎  | 4377/6015 [28:50<06:25,  4.25it/s]

 73%|███████▎  | 4378/6015 [28:50<06:25,  4.25it/s]

 73%|███████▎  | 4379/6015 [28:50<06:24,  4.25it/s]

 73%|███████▎  | 4380/6015 [28:51<06:24,  4.25it/s]

 73%|███████▎  | 4381/6015 [28:51<06:23,  4.26it/s]

logging
logging the anndata

 73%|███████▎  | 4382/6015 [28:52<13:24,  2.03it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 73%|███████▎  | 4383/6015 [28:52<11:15,  2.42it/s]

 73%|███████▎  | 4384/6015 [28:52<09:43,  2.79it/s]

 73%|███████▎  | 4385/6015 [28:53<08:39,  3.14it/s]

 73%|███████▎  | 4386/6015 [28:53<07:54,  3.43it/s]

 73%|███████▎  | 4387/6015 [28:53<07:23,  3.67it/s]

 73%|███████▎  | 4388/6015 [28:53<07:01,  3.86it/s]

 73%|███████▎  | 4389/6015 [28:53<06:45,  4.01it/s]

 73%|███████▎  | 4390/6015 [28:54<06:34,  4.12it/s]

 73%|███████▎  | 4391/6015 [28:54<06:27,  4.19it/s]

 73%|███████▎  | 4392/6015 [28:54<06:22,  4.25it/s]

 73%|███████▎  | 4393/6015 [28:54<06:18,  4.28it/s]

 73%|███████▎  | 4394/6015 [28:55<06:16,  4.31it/s]

 73%|███████▎  | 4395/6015 [28:55<06:19,  4.27it/s]

 73%|███████▎  | 4396/6015 [28:55<06:16,  4.30it/s]

 73%|███████▎  | 4397/6015 [28:55<06:14,  4.32it/s]

 73%|███████▎  | 4398/6015 [28:56<06:12,  4.34it/s]

 73%|███████▎  | 4399/6015 [28:56<06:11,  4.35it/s]

 73%|███████▎  | 4400/6015 [28:56<06:10,  4.36it/s]

 73%|███████▎  | 4401/6015 [28:56<06:09,  4.37it/s]

 73%|███████▎  | 4402/6015 [28:56<06:09,  4.36it/s]

 73%|███████▎  | 4403/6015 [28:57<06:09,  4.37it/s]

 73%|███████▎  | 4404/6015 [28:57<06:09,  4.36it/s]

 73%|███████▎  | 4405/6015 [28:57<06:08,  4.37it/s]

 73%|███████▎  | 4406/6015 [28:57<06:08,  4.37it/s]

 73%|███████▎  | 4407/6015 [28:58<06:07,  4.38it/s]

 73%|███████▎  | 4408/6015 [28:58<06:07,  4.37it/s]

 73%|███████▎  | 4409/6015 [28:58<06:07,  4.37it/s]

 73%|███████▎  | 4410/6015 [28:58<06:06,  4.38it/s]

 73%|███████▎  | 4411/6015 [28:58<06:07,  4.37it/s]

 73%|███████▎  | 4412/6015 [28:59<06:06,  4.37it/s]

 73%|███████▎  | 4413/6015 [28:59<06:06,  4.38it/s]

 73%|███████▎  | 4414/6015 [28:59<06:05,  4.38it/s]

 73%|███████▎  | 4415/6015 [28:59<06:06,  4.36it/s]

 73%|███████▎  | 4416/6015 [29:00<06:05,  4.37it/s]

 73%|███████▎  | 4417/6015 [29:00<06:05,  4.37it/s]

 73%|███████▎  | 4418/6015 [29:00<06:04,  4.38it/s]

 73%|███████▎  | 4419/6015 [29:00<06:04,  4.38it/s]

 73%|███████▎  | 4420/6015 [29:01<06:03,  4.38it/s]

 73%|███████▎  | 4421/6015 [29:01<06:03,  4.38it/s]

 74%|███████▎  | 4422/6015 [29:01<06:04,  4.37it/s]

 74%|███████▎  | 4423/6015 [29:01<06:04,  4.37it/s]

 74%|███████▎  | 4424/6015 [29:01<06:03,  4.37it/s]

 74%|███████▎  | 4425/6015 [29:02<06:03,  4.37it/s]

 74%|███████▎  | 4426/6015 [29:02<06:03,  4.37it/s]

 74%|███████▎  | 4427/6015 [29:02<06:03,  4.37it/s]

 74%|███████▎  | 4428/6015 [29:02<06:02,  4.37it/s]

 74%|███████▎  | 4429/6015 [29:03<06:02,  4.37it/s]

 74%|███████▎  | 4430/6015 [29:03<06:02,  4.38it/s]

 74%|███████▎  | 4431/6015 [29:03<06:01,  4.38it/s]

 74%|███████▎  | 4432/6015 [29:03<06:01,  4.37it/s]

 74%|███████▎  | 4433/6015 [29:04<06:02,  4.36it/s]

 74%|███████▎  | 4434/6015 [29:04<06:01,  4.37it/s]

 74%|███████▎  | 4435/6015 [29:04<06:02,  4.36it/s]

 74%|███████▎  | 4436/6015 [29:04<06:01,  4.36it/s]

 74%|███████▍  | 4437/6015 [29:04<06:02,  4.35it/s]

 74%|███████▍  | 4438/6015 [29:05<06:01,  4.36it/s]

 74%|███████▍  | 4439/6015 [29:05<06:01,  4.36it/s]

 74%|███████▍  | 4440/6015 [29:05<06:01,  4.36it/s]

 74%|███████▍  | 4441/6015 [29:05<06:00,  4.37it/s]

 74%|███████▍  | 4442/6015 [29:06<06:00,  4.36it/s]

 74%|███████▍  | 4443/6015 [29:06<06:01,  4.35it/s]

 74%|███████▍  | 4444/6015 [29:06<06:00,  4.36it/s]

 74%|███████▍  | 4445/6015 [29:06<06:00,  4.35it/s]

 74%|███████▍  | 4446/6015 [29:06<06:00,  4.36it/s]

 74%|███████▍  | 4447/6015 [29:07<05:59,  4.36it/s]

 74%|███████▍  | 4448/6015 [29:07<06:00,  4.35it/s]

 74%|███████▍  | 4449/6015 [29:07<05:59,  4.36it/s]

 74%|███████▍  | 4450/6015 [29:07<05:59,  4.36it/s]

 74%|███████▍  | 4451/6015 [29:08<05:58,  4.36it/s]

 74%|███████▍  | 4452/6015 [29:08<05:57,  4.37it/s]

 74%|███████▍  | 4453/6015 [29:08<05:57,  4.37it/s]

 74%|███████▍  | 4454/6015 [29:08<05:57,  4.37it/s]

 74%|███████▍  | 4455/6015 [29:09<05:57,  4.36it/s]

 74%|███████▍  | 4456/6015 [29:09<05:57,  4.36it/s]

 74%|███████▍  | 4457/6015 [29:09<05:57,  4.36it/s]

 74%|███████▍  | 4458/6015 [29:09<05:56,  4.37it/s]

 74%|███████▍  | 4459/6015 [29:09<05:56,  4.37it/s]

 74%|███████▍  | 4460/6015 [29:10<05:55,  4.37it/s]

 74%|███████▍  | 4461/6015 [29:10<05:55,  4.37it/s]

 74%|███████▍  | 4462/6015 [29:10<05:55,  4.36it/s]

 74%|███████▍  | 4463/6015 [29:10<05:57,  4.35it/s]

 74%|███████▍  | 4464/6015 [29:11<05:56,  4.35it/s]

 74%|███████▍  | 4465/6015 [29:11<05:55,  4.36it/s]

 74%|███████▍  | 4466/6015 [29:11<05:55,  4.36it/s]

 74%|███████▍  | 4467/6015 [29:11<05:54,  4.36it/s]

 74%|███████▍  | 4468/6015 [29:12<05:53,  4.37it/s]

 74%|███████▍  | 4469/6015 [29:12<05:53,  4.37it/s]

 74%|███████▍  | 4470/6015 [29:12<05:53,  4.37it/s]

 74%|███████▍  | 4471/6015 [29:12<05:52,  4.38it/s]

 74%|███████▍  | 4472/6015 [29:12<05:52,  4.38it/s]

 74%|███████▍  | 4473/6015 [29:13<05:52,  4.37it/s]

 74%|███████▍  | 4474/6015 [29:13<05:53,  4.36it/s]

 74%|███████▍  | 4475/6015 [29:13<05:52,  4.36it/s]

 74%|███████▍  | 4476/6015 [29:13<05:52,  4.37it/s]

 74%|███████▍  | 4477/6015 [29:14<05:53,  4.36it/s]

 74%|███████▍  | 4478/6015 [29:14<05:53,  4.35it/s]

 74%|███████▍  | 4479/6015 [29:14<05:52,  4.36it/s]

 74%|███████▍  | 4480/6015 [29:14<05:52,  4.36it/s]

 74%|███████▍  | 4481/6015 [29:15<05:53,  4.34it/s]

 75%|███████▍  | 4482/6015 [29:15<05:51,  4.36it/s]

 75%|███████▍  | 4483/6015 [29:15<05:50,  4.37it/s]

 75%|███████▍  | 4484/6015 [29:15<05:50,  4.36it/s]

 75%|███████▍  | 4485/6015 [29:15<05:51,  4.36it/s]

 75%|███████▍  | 4486/6015 [29:16<05:51,  4.36it/s]

 75%|███████▍  | 4487/6015 [29:16<05:50,  4.36it/s]

 75%|███████▍  | 4488/6015 [29:16<05:50,  4.36it/s]

 75%|███████▍  | 4489/6015 [29:16<05:50,  4.36it/s]

 75%|███████▍  | 4490/6015 [29:17<05:49,  4.37it/s]

 75%|███████▍  | 4491/6015 [29:17<05:49,  4.36it/s]

 75%|███████▍  | 4492/6015 [29:17<05:50,  4.35it/s]

 75%|███████▍  | 4493/6015 [29:17<05:49,  4.36it/s]

 75%|███████▍  | 4494/6015 [29:17<05:49,  4.35it/s]

 75%|███████▍  | 4495/6015 [29:18<05:48,  4.36it/s]

 75%|███████▍  | 4496/6015 [29:18<05:48,  4.36it/s]

 75%|███████▍  | 4497/6015 [29:18<05:48,  4.36it/s]

 75%|███████▍  | 4498/6015 [29:18<05:50,  4.33it/s]

 75%|███████▍  | 4499/6015 [29:19<05:49,  4.34it/s]

 75%|███████▍  | 4500/6015 [29:19<05:49,  4.34it/s]

 75%|███████▍  | 4501/6015 [29:19<05:47,  4.35it/s]

 75%|███████▍  | 4502/6015 [29:19<05:47,  4.35it/s]

 75%|███████▍  | 4503/6015 [29:20<05:48,  4.33it/s]

 75%|███████▍  | 4504/6015 [29:20<05:47,  4.34it/s]

 75%|███████▍  | 4505/6015 [29:20<05:47,  4.34it/s]

 75%|███████▍  | 4506/6015 [29:20<05:46,  4.35it/s]

 75%|███████▍  | 4507/6015 [29:20<05:46,  4.35it/s]

 75%|███████▍  | 4508/6015 [29:21<05:46,  4.34it/s]

 75%|███████▍  | 4509/6015 [29:21<05:45,  4.35it/s]

 75%|███████▍  | 4510/6015 [29:21<05:45,  4.36it/s]

 75%|███████▍  | 4511/6015 [29:21<05:45,  4.36it/s]

 75%|███████▌  | 4512/6015 [29:22<05:46,  4.34it/s]

 75%|███████▌  | 4513/6015 [29:22<05:46,  4.34it/s]

 75%|███████▌  | 4514/6015 [29:22<05:45,  4.35it/s]

 75%|███████▌  | 4515/6015 [29:22<05:45,  4.35it/s]

 75%|███████▌  | 4516/6015 [29:23<05:45,  4.34it/s]

 75%|███████▌  | 4517/6015 [29:23<05:44,  4.35it/s]

 75%|███████▌  | 4518/6015 [29:23<05:44,  4.35it/s]

 75%|███████▌  | 4519/6015 [29:23<05:44,  4.34it/s]

 75%|███████▌  | 4520/6015 [29:23<05:43,  4.35it/s]

 75%|███████▌  | 4521/6015 [29:24<05:43,  4.35it/s]

 75%|███████▌  | 4522/6015 [29:24<05:43,  4.35it/s]

 75%|███████▌  | 4523/6015 [29:24<05:42,  4.35it/s]

 75%|███████▌  | 4524/6015 [29:24<05:42,  4.35it/s]

 75%|███████▌  | 4525/6015 [29:25<05:42,  4.36it/s]

 75%|███████▌  | 4526/6015 [29:25<05:42,  4.34it/s]

 75%|███████▌  | 4527/6015 [29:25<05:42,  4.34it/s]

 75%|███████▌  | 4528/6015 [29:25<05:41,  4.35it/s]

 75%|███████▌  | 4529/6015 [29:26<05:41,  4.35it/s]

 75%|███████▌  | 4530/6015 [29:26<05:42,  4.33it/s]

 75%|███████▌  | 4531/6015 [29:26<05:42,  4.33it/s]

 75%|███████▌  | 4532/6015 [29:26<05:41,  4.34it/s]

 75%|███████▌  | 4533/6015 [29:26<05:41,  4.34it/s]

 75%|███████▌  | 4534/6015 [29:27<05:40,  4.35it/s]

 75%|███████▌  | 4535/6015 [29:27<05:40,  4.35it/s]

 75%|███████▌  | 4536/6015 [29:27<05:39,  4.36it/s]

 75%|███████▌  | 4537/6015 [29:27<05:39,  4.36it/s]

 75%|███████▌  | 4538/6015 [29:28<05:38,  4.36it/s]

 75%|███████▌  | 4539/6015 [29:28<05:38,  4.36it/s]

 75%|███████▌  | 4540/6015 [29:28<05:38,  4.36it/s]

 75%|███████▌  | 4541/6015 [29:28<05:38,  4.36it/s]

 76%|███████▌  | 4542/6015 [29:29<05:38,  4.35it/s]

 76%|███████▌  | 4543/6015 [29:29<05:39,  4.34it/s]

 76%|███████▌  | 4544/6015 [29:29<05:38,  4.34it/s]

 76%|███████▌  | 4545/6015 [29:29<05:38,  4.34it/s]

 76%|███████▌  | 4546/6015 [29:29<05:38,  4.34it/s]

 76%|███████▌  | 4547/6015 [29:30<05:38,  4.33it/s]

 76%|███████▌  | 4548/6015 [29:30<05:38,  4.34it/s]

 76%|███████▌  | 4549/6015 [29:30<05:37,  4.34it/s]

 76%|███████▌  | 4550/6015 [29:30<05:37,  4.34it/s]

 76%|███████▌  | 4551/6015 [29:31<05:37,  4.34it/s]

 76%|███████▌  | 4552/6015 [29:31<05:36,  4.35it/s]

 76%|███████▌  | 4553/6015 [29:31<05:36,  4.34it/s]

 76%|███████▌  | 4554/6015 [29:31<05:36,  4.34it/s]

 76%|███████▌  | 4555/6015 [29:32<05:35,  4.35it/s]

 76%|███████▌  | 4556/6015 [29:32<05:35,  4.35it/s]

 76%|███████▌  | 4557/6015 [29:32<05:36,  4.34it/s]

 76%|███████▌  | 4558/6015 [29:32<05:35,  4.34it/s]

 76%|███████▌  | 4559/6015 [29:32<05:35,  4.34it/s]

 76%|███████▌  | 4560/6015 [29:33<05:35,  4.34it/s]

 76%|███████▌  | 4561/6015 [29:33<05:35,  4.34it/s]

 76%|███████▌  | 4562/6015 [29:33<05:35,  4.34it/s]

 76%|███████▌  | 4563/6015 [29:33<05:35,  4.33it/s]

 76%|███████▌  | 4564/6015 [29:34<05:36,  4.32it/s]

 76%|███████▌  | 4565/6015 [29:34<05:36,  4.31it/s]

 76%|███████▌  | 4566/6015 [29:34<05:35,  4.32it/s]

 76%|███████▌  | 4567/6015 [29:34<05:34,  4.33it/s]

 76%|███████▌  | 4568/6015 [29:35<05:33,  4.34it/s]

 76%|███████▌  | 4569/6015 [29:35<05:33,  4.34it/s]

 76%|███████▌  | 4570/6015 [29:35<05:32,  4.34it/s]

 76%|███████▌  | 4571/6015 [29:35<05:32,  4.34it/s]

 76%|███████▌  | 4572/6015 [29:35<05:32,  4.34it/s]

 76%|███████▌  | 4573/6015 [29:36<05:32,  4.34it/s]

 76%|███████▌  | 4574/6015 [29:36<05:32,  4.34it/s]

 76%|███████▌  | 4575/6015 [29:36<05:31,  4.34it/s]

 76%|███████▌  | 4576/6015 [29:36<05:31,  4.35it/s]

 76%|███████▌  | 4577/6015 [29:37<05:30,  4.34it/s]

 76%|███████▌  | 4578/6015 [29:37<05:30,  4.34it/s]

 76%|███████▌  | 4579/6015 [29:37<05:30,  4.35it/s]

 76%|███████▌  | 4580/6015 [29:37<05:30,  4.35it/s]

 76%|███████▌  | 4581/6015 [29:38<05:29,  4.35it/s]

 76%|███████▌  | 4582/6015 [29:38<05:29,  4.35it/s]

 76%|███████▌  | 4583/6015 [29:38<05:29,  4.34it/s]

 76%|███████▌  | 4584/6015 [29:38<05:29,  4.35it/s]

 76%|███████▌  | 4585/6015 [29:38<05:28,  4.35it/s]

 76%|███████▌  | 4586/6015 [29:39<05:29,  4.34it/s]

 76%|███████▋  | 4587/6015 [29:39<05:28,  4.34it/s]

 76%|███████▋  | 4588/6015 [29:39<05:28,  4.34it/s]

 76%|███████▋  | 4589/6015 [29:39<05:29,  4.33it/s]

 76%|███████▋  | 4590/6015 [29:40<05:28,  4.33it/s]

 76%|███████▋  | 4591/6015 [29:40<05:28,  4.33it/s]

 76%|███████▋  | 4592/6015 [29:40<05:27,  4.34it/s]

 76%|███████▋  | 4593/6015 [29:40<05:27,  4.34it/s]

 76%|███████▋  | 4594/6015 [29:41<05:27,  4.34it/s]

 76%|███████▋  | 4595/6015 [29:41<05:27,  4.34it/s]

 76%|███████▋  | 4596/6015 [29:41<05:27,  4.33it/s]

 76%|███████▋  | 4597/6015 [29:41<05:27,  4.33it/s]

 76%|███████▋  | 4598/6015 [29:41<05:27,  4.33it/s]

 76%|███████▋  | 4599/6015 [29:42<05:27,  4.33it/s]

 76%|███████▋  | 4600/6015 [29:42<05:26,  4.33it/s]

 76%|███████▋  | 4601/6015 [29:42<05:25,  4.34it/s]

 77%|███████▋  | 4602/6015 [29:42<05:25,  4.34it/s]

 77%|███████▋  | 4603/6015 [29:43<05:24,  4.34it/s]

 77%|███████▋  | 4604/6015 [29:43<05:25,  4.33it/s]

 77%|███████▋  | 4605/6015 [29:43<05:25,  4.33it/s]

 77%|███████▋  | 4606/6015 [29:43<05:25,  4.33it/s]

 77%|███████▋  | 4607/6015 [29:44<05:25,  4.33it/s]

 77%|███████▋  | 4608/6015 [29:44<05:24,  4.33it/s]

 77%|███████▋  | 4609/6015 [29:44<05:24,  4.33it/s]

 77%|███████▋  | 4610/6015 [29:44<05:24,  4.33it/s]

 77%|███████▋  | 4611/6015 [29:44<05:23,  4.34it/s]

 77%|███████▋  | 4612/6015 [29:45<05:23,  4.34it/s]

 77%|███████▋  | 4613/6015 [29:45<05:23,  4.34it/s]

 77%|███████▋  | 4614/6015 [29:45<05:23,  4.33it/s]

 77%|███████▋  | 4615/6015 [29:45<05:23,  4.33it/s]

 77%|███████▋  | 4616/6015 [29:46<05:22,  4.33it/s]

 77%|███████▋  | 4617/6015 [29:46<05:22,  4.33it/s]

 77%|███████▋  | 4618/6015 [29:46<05:21,  4.34it/s]

 77%|███████▋  | 4619/6015 [29:46<05:21,  4.34it/s]

 77%|███████▋  | 4620/6015 [29:47<05:21,  4.34it/s]

 77%|███████▋  | 4621/6015 [29:47<05:21,  4.34it/s]

 77%|███████▋  | 4622/6015 [29:47<05:23,  4.30it/s]

 77%|███████▋  | 4623/6015 [29:47<05:23,  4.31it/s]

 77%|███████▋  | 4624/6015 [29:47<05:21,  4.32it/s]

 77%|███████▋  | 4625/6015 [29:48<05:21,  4.33it/s]

 77%|███████▋  | 4626/6015 [29:48<05:21,  4.32it/s]

 77%|███████▋  | 4627/6015 [29:48<05:20,  4.34it/s]

 77%|███████▋  | 4628/6015 [29:48<05:20,  4.33it/s]

 77%|███████▋  | 4629/6015 [29:49<05:20,  4.32it/s]

 77%|███████▋  | 4630/6015 [29:49<05:20,  4.33it/s]

 77%|███████▋  | 4631/6015 [29:49<05:19,  4.33it/s]

 77%|███████▋  | 4632/6015 [29:49<05:19,  4.33it/s]

 77%|███████▋  | 4633/6015 [29:50<05:19,  4.33it/s]

 77%|███████▋  | 4634/6015 [29:50<05:18,  4.33it/s]

 77%|███████▋  | 4635/6015 [29:50<05:18,  4.34it/s]

 77%|███████▋  | 4636/6015 [29:50<05:18,  4.33it/s]

 77%|███████▋  | 4637/6015 [29:50<05:18,  4.33it/s]

 77%|███████▋  | 4638/6015 [29:51<05:18,  4.32it/s]

 77%|███████▋  | 4639/6015 [29:51<05:17,  4.33it/s]

 77%|███████▋  | 4640/6015 [29:51<05:16,  4.34it/s]

 77%|███████▋  | 4641/6015 [29:51<05:16,  4.34it/s]

 77%|███████▋  | 4642/6015 [29:52<05:16,  4.33it/s]

 77%|███████▋  | 4643/6015 [29:52<05:15,  4.35it/s]

 77%|███████▋  | 4644/6015 [29:52<05:15,  4.35it/s]

 77%|███████▋  | 4645/6015 [29:52<05:14,  4.35it/s]

 77%|███████▋  | 4646/6015 [29:53<05:14,  4.35it/s]

 77%|███████▋  | 4647/6015 [29:53<05:14,  4.35it/s]

 77%|███████▋  | 4648/6015 [29:53<05:14,  4.34it/s]

 77%|███████▋  | 4649/6015 [29:53<05:14,  4.34it/s]

 77%|███████▋  | 4650/6015 [29:53<05:14,  4.34it/s]

 77%|███████▋  | 4651/6015 [29:54<05:14,  4.33it/s]

 77%|███████▋  | 4652/6015 [29:54<05:15,  4.32it/s]

 77%|███████▋  | 4653/6015 [29:54<05:15,  4.32it/s]

 77%|███████▋  | 4654/6015 [29:54<05:14,  4.33it/s]

 77%|███████▋  | 4655/6015 [29:55<05:14,  4.32it/s]

 77%|███████▋  | 4656/6015 [29:55<05:13,  4.33it/s]

 77%|███████▋  | 4657/6015 [29:55<05:15,  4.31it/s]

 77%|███████▋  | 4658/6015 [29:55<05:15,  4.30it/s]

 77%|███████▋  | 4659/6015 [29:56<05:14,  4.32it/s]

 77%|███████▋  | 4660/6015 [29:56<05:14,  4.32it/s]

 77%|███████▋  | 4661/6015 [29:56<05:13,  4.32it/s]

 78%|███████▊  | 4662/6015 [29:56<05:12,  4.33it/s]

 78%|███████▊  | 4663/6015 [29:56<05:12,  4.32it/s]

 78%|███████▊  | 4664/6015 [29:57<05:12,  4.33it/s]

 78%|███████▊  | 4665/6015 [29:57<05:11,  4.33it/s]

 78%|███████▊  | 4666/6015 [29:57<05:11,  4.32it/s]

 78%|███████▊  | 4667/6015 [29:57<05:11,  4.33it/s]

 78%|███████▊  | 4668/6015 [29:58<05:11,  4.33it/s]

 78%|███████▊  | 4669/6015 [29:58<05:10,  4.33it/s]

 78%|███████▊  | 4670/6015 [29:58<05:10,  4.33it/s]

 78%|███████▊  | 4671/6015 [29:58<05:11,  4.31it/s]

 78%|███████▊  | 4672/6015 [29:59<05:10,  4.32it/s]

 78%|███████▊  | 4673/6015 [29:59<05:10,  4.32it/s]

 78%|███████▊  | 4674/6015 [29:59<05:10,  4.32it/s]

 78%|███████▊  | 4675/6015 [29:59<05:09,  4.33it/s]

 78%|███████▊  | 4676/6015 [29:59<05:09,  4.33it/s]

 78%|███████▊  | 4677/6015 [30:00<05:09,  4.33it/s]

 78%|███████▊  | 4678/6015 [30:00<05:08,  4.33it/s]

 78%|███████▊  | 4679/6015 [30:00<05:08,  4.33it/s]

 78%|███████▊  | 4680/6015 [30:00<05:10,  4.31it/s]

 78%|███████▊  | 4681/6015 [30:01<05:09,  4.31it/s]

 78%|███████▊  | 4682/6015 [30:01<05:09,  4.31it/s]

 78%|███████▊  | 4683/6015 [30:01<05:08,  4.31it/s]

 78%|███████▊  | 4684/6015 [30:01<05:08,  4.31it/s]

 78%|███████▊  | 4685/6015 [30:02<05:08,  4.30it/s]

 78%|███████▊  | 4686/6015 [30:02<05:07,  4.32it/s]

 78%|███████▊  | 4687/6015 [30:02<05:07,  4.33it/s]

 78%|███████▊  | 4688/6015 [30:02<05:06,  4.33it/s]

 78%|███████▊  | 4689/6015 [30:02<05:14,  4.21it/s]

 78%|███████▊  | 4690/6015 [30:03<05:11,  4.25it/s]

 78%|███████▊  | 4691/6015 [30:03<05:09,  4.28it/s]

 78%|███████▊  | 4692/6015 [30:03<05:07,  4.30it/s]

 78%|███████▊  | 4693/6015 [30:03<05:06,  4.31it/s]

 78%|███████▊  | 4694/6015 [30:04<05:05,  4.33it/s]

 78%|███████▊  | 4695/6015 [30:04<05:04,  4.33it/s]

 78%|███████▊  | 4696/6015 [30:04<05:04,  4.34it/s]

 78%|███████▊  | 4697/6015 [30:04<05:03,  4.35it/s]

 78%|███████▊  | 4698/6015 [30:05<05:03,  4.34it/s]

 78%|███████▊  | 4699/6015 [30:05<05:03,  4.33it/s]

 78%|███████▊  | 4700/6015 [30:05<05:03,  4.34it/s]

 78%|███████▊  | 4701/6015 [30:05<05:03,  4.33it/s]

 78%|███████▊  | 4702/6015 [30:05<05:03,  4.33it/s]

 78%|███████▊  | 4703/6015 [30:06<05:02,  4.34it/s]

 78%|███████▊  | 4704/6015 [30:06<05:02,  4.33it/s]

 78%|███████▊  | 4705/6015 [30:06<05:03,  4.32it/s]

 78%|███████▊  | 4706/6015 [30:06<05:03,  4.32it/s]

 78%|███████▊  | 4707/6015 [30:07<05:02,  4.32it/s]

 78%|███████▊  | 4708/6015 [30:07<05:02,  4.32it/s]

 78%|███████▊  | 4709/6015 [30:07<05:01,  4.33it/s]

 78%|███████▊  | 4710/6015 [30:07<05:01,  4.33it/s]

 78%|███████▊  | 4711/6015 [30:08<05:00,  4.34it/s]

 78%|███████▊  | 4712/6015 [30:08<05:00,  4.33it/s]

 78%|███████▊  | 4713/6015 [30:08<05:01,  4.33it/s]

 78%|███████▊  | 4714/6015 [30:08<05:00,  4.33it/s]

 78%|███████▊  | 4715/6015 [30:08<05:01,  4.32it/s]

 78%|███████▊  | 4716/6015 [30:09<05:00,  4.33it/s]

 78%|███████▊  | 4717/6015 [30:09<05:00,  4.32it/s]

 78%|███████▊  | 4718/6015 [30:09<04:59,  4.33it/s]

 78%|███████▊  | 4719/6015 [30:09<04:59,  4.33it/s]

 78%|███████▊  | 4720/6015 [30:10<04:59,  4.32it/s]

 78%|███████▊  | 4721/6015 [30:10<04:59,  4.32it/s]

 79%|███████▊  | 4722/6015 [30:10<04:59,  4.31it/s]

 79%|███████▊  | 4723/6015 [30:10<04:59,  4.31it/s]

 79%|███████▊  | 4724/6015 [30:11<04:58,  4.32it/s]

 79%|███████▊  | 4725/6015 [30:11<04:58,  4.32it/s]

 79%|███████▊  | 4726/6015 [30:11<04:58,  4.32it/s]

 79%|███████▊  | 4727/6015 [30:11<04:58,  4.32it/s]

 79%|███████▊  | 4728/6015 [30:12<04:57,  4.32it/s]

 79%|███████▊  | 4729/6015 [30:12<04:57,  4.33it/s]

 79%|███████▊  | 4730/6015 [30:12<04:56,  4.33it/s]

 79%|███████▊  | 4731/6015 [30:12<04:56,  4.33it/s]

 79%|███████▊  | 4732/6015 [30:12<04:55,  4.34it/s]

 79%|███████▊  | 4733/6015 [30:13<04:55,  4.34it/s]

 79%|███████▊  | 4734/6015 [30:13<04:55,  4.33it/s]

 79%|███████▊  | 4735/6015 [30:13<04:55,  4.33it/s]

 79%|███████▊  | 4736/6015 [30:13<04:55,  4.33it/s]

 79%|███████▉  | 4737/6015 [30:14<04:55,  4.32it/s]

 79%|███████▉  | 4738/6015 [30:14<04:55,  4.31it/s]

 79%|███████▉  | 4739/6015 [30:14<04:56,  4.31it/s]

 79%|███████▉  | 4740/6015 [30:14<04:55,  4.32it/s]

 79%|███████▉  | 4741/6015 [30:15<04:55,  4.32it/s]

 79%|███████▉  | 4742/6015 [30:15<04:55,  4.30it/s]

 79%|███████▉  | 4743/6015 [30:15<04:55,  4.31it/s]

 79%|███████▉  | 4744/6015 [30:15<04:54,  4.31it/s]

 79%|███████▉  | 4745/6015 [30:15<04:54,  4.32it/s]

 79%|███████▉  | 4746/6015 [30:16<04:53,  4.32it/s]

 79%|███████▉  | 4747/6015 [30:16<04:54,  4.31it/s]

 79%|███████▉  | 4748/6015 [30:16<04:54,  4.30it/s]

 79%|███████▉  | 4749/6015 [30:16<04:54,  4.30it/s]

 79%|███████▉  | 4750/6015 [30:17<04:53,  4.31it/s]

 79%|███████▉  | 4751/6015 [30:17<04:53,  4.31it/s]

 79%|███████▉  | 4752/6015 [30:17<04:53,  4.31it/s]

 79%|███████▉  | 4753/6015 [30:17<04:52,  4.32it/s]

 79%|███████▉  | 4754/6015 [30:18<04:53,  4.30it/s]

 79%|███████▉  | 4755/6015 [30:18<04:53,  4.29it/s]

 79%|███████▉  | 4756/6015 [30:18<04:52,  4.31it/s]

 79%|███████▉  | 4757/6015 [30:18<04:52,  4.30it/s]

 79%|███████▉  | 4758/6015 [30:18<04:51,  4.31it/s]

 79%|███████▉  | 4759/6015 [30:19<04:51,  4.31it/s]

 79%|███████▉  | 4760/6015 [30:19<04:51,  4.31it/s]

 79%|███████▉  | 4761/6015 [30:19<04:49,  4.32it/s]

 79%|███████▉  | 4762/6015 [30:19<04:49,  4.33it/s]

 79%|███████▉  | 4763/6015 [30:20<04:49,  4.32it/s]

 79%|███████▉  | 4764/6015 [30:20<04:49,  4.33it/s]

 79%|███████▉  | 4765/6015 [30:20<04:49,  4.32it/s]

 79%|███████▉  | 4766/6015 [30:20<04:48,  4.33it/s]

 79%|███████▉  | 4767/6015 [30:21<04:48,  4.33it/s]

 79%|███████▉  | 4768/6015 [30:21<04:48,  4.33it/s]

 79%|███████▉  | 4769/6015 [30:21<04:48,  4.32it/s]

 79%|███████▉  | 4770/6015 [30:21<04:48,  4.32it/s]

 79%|███████▉  | 4771/6015 [30:21<04:48,  4.32it/s]

 79%|███████▉  | 4772/6015 [30:22<04:47,  4.32it/s]

 79%|███████▉  | 4773/6015 [30:22<04:47,  4.32it/s]

 79%|███████▉  | 4774/6015 [30:22<04:47,  4.32it/s]

 79%|███████▉  | 4775/6015 [30:22<04:47,  4.32it/s]

 79%|███████▉  | 4776/6015 [30:23<04:46,  4.32it/s]

 79%|███████▉  | 4777/6015 [30:23<04:46,  4.32it/s]

 79%|███████▉  | 4778/6015 [30:23<04:47,  4.30it/s]

 79%|███████▉  | 4779/6015 [30:23<04:46,  4.31it/s]

 79%|███████▉  | 4780/6015 [30:24<04:46,  4.31it/s]

 79%|███████▉  | 4781/6015 [30:24<04:46,  4.31it/s]

 80%|███████▉  | 4782/6015 [30:24<04:45,  4.32it/s]

 80%|███████▉  | 4783/6015 [30:24<04:45,  4.32it/s]

 80%|███████▉  | 4784/6015 [30:24<04:45,  4.31it/s]

 80%|███████▉  | 4785/6015 [30:25<04:45,  4.32it/s]

 80%|███████▉  | 4786/6015 [30:25<04:44,  4.32it/s]

 80%|███████▉  | 4787/6015 [30:25<04:44,  4.32it/s]

 80%|███████▉  | 4788/6015 [30:25<04:44,  4.31it/s]

 80%|███████▉  | 4789/6015 [30:26<04:44,  4.31it/s]

 80%|███████▉  | 4790/6015 [30:26<04:46,  4.27it/s]

 80%|███████▉  | 4791/6015 [30:26<04:45,  4.28it/s]

 80%|███████▉  | 4792/6015 [30:26<04:44,  4.29it/s]

 80%|███████▉  | 4793/6015 [30:27<04:44,  4.30it/s]

 80%|███████▉  | 4794/6015 [30:27<04:44,  4.30it/s]

 80%|███████▉  | 4795/6015 [30:27<04:43,  4.31it/s]

 80%|███████▉  | 4796/6015 [30:27<04:42,  4.31it/s]

 80%|███████▉  | 4797/6015 [30:27<04:42,  4.30it/s]

 80%|███████▉  | 4798/6015 [30:28<04:42,  4.31it/s]

 80%|███████▉  | 4799/6015 [30:28<04:42,  4.30it/s]

 80%|███████▉  | 4800/6015 [30:28<04:42,  4.30it/s]

 80%|███████▉  | 4801/6015 [30:28<04:42,  4.30it/s]

 80%|███████▉  | 4802/6015 [30:29<04:42,  4.30it/s]

 80%|███████▉  | 4803/6015 [30:29<04:41,  4.30it/s]

 80%|███████▉  | 4804/6015 [30:29<04:42,  4.29it/s]

 80%|███████▉  | 4805/6015 [30:29<04:41,  4.30it/s]

 80%|███████▉  | 4806/6015 [30:30<04:41,  4.30it/s]

 80%|███████▉  | 4807/6015 [30:30<04:41,  4.29it/s]

 80%|███████▉  | 4808/6015 [30:30<04:40,  4.31it/s]

 80%|███████▉  | 4809/6015 [30:30<04:40,  4.30it/s]

 80%|███████▉  | 4810/6015 [30:31<04:40,  4.30it/s]

 80%|███████▉  | 4811/6015 [30:31<04:40,  4.30it/s]

 80%|████████  | 4812/6015 [30:31<04:39,  4.30it/s]

 80%|████████  | 4813/6015 [30:31<04:39,  4.30it/s]

 80%|████████  | 4814/6015 [30:31<04:39,  4.30it/s]

 80%|████████  | 4815/6015 [30:32<04:39,  4.29it/s]

 80%|████████  | 4816/6015 [30:32<04:39,  4.29it/s]

 80%|████████  | 4817/6015 [30:32<04:39,  4.28it/s]

 80%|████████  | 4818/6015 [30:32<04:38,  4.29it/s]

 80%|████████  | 4819/6015 [30:33<04:37,  4.31it/s]

 80%|████████  | 4820/6015 [30:33<04:37,  4.31it/s]

 80%|████████  | 4821/6015 [30:33<04:36,  4.31it/s]

 80%|████████  | 4822/6015 [30:33<04:36,  4.31it/s]

 80%|████████  | 4823/6015 [30:34<04:35,  4.32it/s]

 80%|████████  | 4824/6015 [30:34<04:35,  4.32it/s]

 80%|████████  | 4825/6015 [30:34<04:36,  4.30it/s]

 80%|████████  | 4826/6015 [30:34<04:36,  4.30it/s]

 80%|████████  | 4827/6015 [30:34<04:36,  4.29it/s]

 80%|████████  | 4828/6015 [30:35<04:36,  4.29it/s]

 80%|████████  | 4829/6015 [30:35<04:36,  4.29it/s]

 80%|████████  | 4830/6015 [30:35<04:36,  4.29it/s]

 80%|████████  | 4831/6015 [30:35<04:35,  4.30it/s]

 80%|████████  | 4832/6015 [30:36<04:35,  4.29it/s]

 80%|████████  | 4833/6015 [30:36<04:35,  4.30it/s]

 80%|████████  | 4834/6015 [30:36<04:33,  4.31it/s]

 80%|████████  | 4835/6015 [30:36<04:34,  4.30it/s]

 80%|████████  | 4836/6015 [30:37<04:33,  4.30it/s]

 80%|████████  | 4837/6015 [30:37<04:33,  4.31it/s]

 80%|████████  | 4838/6015 [30:37<04:32,  4.32it/s]

 80%|████████  | 4839/6015 [30:37<04:32,  4.32it/s]

 80%|████████  | 4840/6015 [30:37<04:32,  4.32it/s]

 80%|████████  | 4841/6015 [30:38<04:33,  4.29it/s]

 80%|████████  | 4842/6015 [30:38<04:32,  4.30it/s]

 81%|████████  | 4843/6015 [30:38<04:32,  4.30it/s]

 81%|████████  | 4844/6015 [30:38<04:31,  4.31it/s]

 81%|████████  | 4845/6015 [30:39<04:31,  4.31it/s]

 81%|████████  | 4846/6015 [30:39<04:31,  4.31it/s]

 81%|████████  | 4847/6015 [30:39<04:30,  4.32it/s]

 81%|████████  | 4848/6015 [30:39<04:30,  4.31it/s]

 81%|████████  | 4849/6015 [30:40<04:31,  4.30it/s]

 81%|████████  | 4850/6015 [30:40<04:31,  4.30it/s]

 81%|████████  | 4851/6015 [30:40<04:31,  4.29it/s]

 81%|████████  | 4852/6015 [30:40<04:31,  4.29it/s]

 81%|████████  | 4853/6015 [30:41<04:31,  4.28it/s]

 81%|████████  | 4854/6015 [30:41<04:31,  4.28it/s]

 81%|████████  | 4855/6015 [30:41<04:30,  4.28it/s]

 81%|████████  | 4856/6015 [30:41<04:30,  4.28it/s]

 81%|████████  | 4857/6015 [30:41<04:30,  4.29it/s]

 81%|████████  | 4858/6015 [30:42<04:29,  4.29it/s]

 81%|████████  | 4859/6015 [30:42<04:29,  4.29it/s]

 81%|████████  | 4860/6015 [30:42<04:29,  4.28it/s]

 81%|████████  | 4861/6015 [30:42<04:30,  4.27it/s]

 81%|████████  | 4862/6015 [30:43<04:29,  4.28it/s]

 81%|████████  | 4863/6015 [30:43<04:29,  4.28it/s]

 81%|████████  | 4864/6015 [30:43<04:29,  4.28it/s]

 81%|████████  | 4865/6015 [30:43<04:29,  4.27it/s]

 81%|████████  | 4866/6015 [30:44<04:29,  4.27it/s]

 81%|████████  | 4867/6015 [30:44<04:28,  4.27it/s]

 81%|████████  | 4868/6015 [30:44<04:28,  4.28it/s]

 81%|████████  | 4869/6015 [30:44<04:27,  4.28it/s]

 81%|████████  | 4870/6015 [30:44<04:27,  4.28it/s]

 81%|████████  | 4871/6015 [30:45<04:26,  4.29it/s]

 81%|████████  | 4872/6015 [30:45<04:26,  4.29it/s]

 81%|████████  | 4873/6015 [30:45<04:26,  4.29it/s]

 81%|████████  | 4874/6015 [30:45<04:26,  4.28it/s]

 81%|████████  | 4875/6015 [30:46<04:25,  4.29it/s]

 81%|████████  | 4876/6015 [30:46<04:25,  4.28it/s]

 81%|████████  | 4877/6015 [30:46<04:25,  4.29it/s]

 81%|████████  | 4878/6015 [30:46<04:25,  4.29it/s]

 81%|████████  | 4879/6015 [30:47<04:25,  4.28it/s]

 81%|████████  | 4880/6015 [30:47<04:24,  4.29it/s]

 81%|████████  | 4881/6015 [30:47<04:24,  4.29it/s]

 81%|████████  | 4882/6015 [30:47<04:23,  4.30it/s]

 81%|████████  | 4883/6015 [30:48<04:24,  4.29it/s]

 81%|████████  | 4884/6015 [30:48<04:23,  4.29it/s]

 81%|████████  | 4885/6015 [30:48<04:23,  4.29it/s]

 81%|████████  | 4886/6015 [30:48<04:23,  4.29it/s]

 81%|████████  | 4887/6015 [30:48<04:22,  4.29it/s]

 81%|████████▏ | 4888/6015 [30:49<04:22,  4.29it/s]

 81%|████████▏ | 4889/6015 [30:49<04:22,  4.29it/s]

 81%|████████▏ | 4890/6015 [30:49<04:22,  4.28it/s]

 81%|████████▏ | 4891/6015 [30:49<04:22,  4.28it/s]

 81%|████████▏ | 4892/6015 [30:50<04:22,  4.28it/s]

 81%|████████▏ | 4893/6015 [30:50<04:21,  4.29it/s]

 81%|████████▏ | 4894/6015 [30:50<04:22,  4.28it/s]

 81%|████████▏ | 4895/6015 [30:50<04:21,  4.28it/s]

 81%|████████▏ | 4896/6015 [30:51<04:21,  4.28it/s]

 81%|████████▏ | 4897/6015 [30:51<04:21,  4.28it/s]

 81%|████████▏ | 4898/6015 [30:51<04:20,  4.29it/s]

 81%|████████▏ | 4899/6015 [30:51<04:20,  4.28it/s]

 81%|████████▏ | 4900/6015 [30:51<04:20,  4.28it/s]

 81%|████████▏ | 4901/6015 [30:52<04:20,  4.28it/s]

 81%|████████▏ | 4902/6015 [30:52<04:19,  4.28it/s]

 82%|████████▏ | 4903/6015 [30:52<04:19,  4.28it/s]

 82%|████████▏ | 4904/6015 [30:52<04:20,  4.26it/s]

 82%|████████▏ | 4905/6015 [30:53<04:21,  4.25it/s]

 82%|████████▏ | 4906/6015 [30:53<04:20,  4.26it/s]

 82%|████████▏ | 4907/6015 [30:53<04:21,  4.25it/s]

 82%|████████▏ | 4908/6015 [30:53<04:19,  4.26it/s]

 82%|████████▏ | 4909/6015 [30:54<04:20,  4.25it/s]

 82%|████████▏ | 4910/6015 [30:54<04:19,  4.26it/s]

 82%|████████▏ | 4911/6015 [30:54<04:19,  4.26it/s]

 82%|████████▏ | 4912/6015 [30:54<04:19,  4.26it/s]

 82%|████████▏ | 4913/6015 [30:55<04:18,  4.26it/s]

 82%|████████▏ | 4914/6015 [30:55<04:18,  4.26it/s]

 82%|████████▏ | 4915/6015 [30:55<04:18,  4.26it/s]

 82%|████████▏ | 4916/6015 [30:55<04:18,  4.26it/s]

 82%|████████▏ | 4917/6015 [30:55<04:17,  4.26it/s]

 82%|████████▏ | 4918/6015 [30:56<04:17,  4.27it/s]

 82%|████████▏ | 4919/6015 [30:56<04:16,  4.27it/s]

 82%|████████▏ | 4920/6015 [30:56<04:19,  4.23it/s]

 82%|████████▏ | 4921/6015 [30:56<04:18,  4.23it/s]

 82%|████████▏ | 4922/6015 [30:57<04:17,  4.24it/s]

 82%|████████▏ | 4923/6015 [30:57<04:16,  4.25it/s]

 82%|████████▏ | 4924/6015 [30:57<04:16,  4.25it/s]

 82%|████████▏ | 4925/6015 [30:57<04:16,  4.26it/s]

 82%|████████▏ | 4926/6015 [30:58<04:15,  4.26it/s]

 82%|████████▏ | 4927/6015 [30:58<04:15,  4.25it/s]

 82%|████████▏ | 4928/6015 [30:58<04:16,  4.24it/s]

 82%|████████▏ | 4929/6015 [30:58<04:15,  4.25it/s]

 82%|████████▏ | 4930/6015 [30:59<04:15,  4.25it/s]

 82%|████████▏ | 4931/6015 [30:59<04:16,  4.23it/s]

 82%|████████▏ | 4932/6015 [30:59<04:15,  4.24it/s]

 82%|████████▏ | 4933/6015 [30:59<04:14,  4.26it/s]

 82%|████████▏ | 4934/6015 [30:59<04:13,  4.26it/s]

 82%|████████▏ | 4935/6015 [31:00<04:13,  4.26it/s]

 82%|████████▏ | 4936/6015 [31:00<04:13,  4.25it/s]

 82%|████████▏ | 4937/6015 [31:00<04:13,  4.25it/s]

 82%|████████▏ | 4938/6015 [31:00<04:13,  4.26it/s]

 82%|████████▏ | 4939/6015 [31:01<04:12,  4.26it/s]

 82%|████████▏ | 4940/6015 [31:01<04:12,  4.25it/s]

 82%|████████▏ | 4941/6015 [31:01<04:11,  4.26it/s]

 82%|████████▏ | 4942/6015 [31:01<04:11,  4.26it/s]

 82%|████████▏ | 4943/6015 [31:02<04:11,  4.26it/s]

 82%|████████▏ | 4944/6015 [31:02<04:11,  4.25it/s]

 82%|████████▏ | 4945/6015 [31:02<04:11,  4.25it/s]

 82%|████████▏ | 4946/6015 [31:02<04:11,  4.25it/s]

 82%|████████▏ | 4947/6015 [31:03<04:11,  4.25it/s]

 82%|████████▏ | 4948/6015 [31:03<04:10,  4.26it/s]

 82%|████████▏ | 4949/6015 [31:03<04:10,  4.26it/s]

 82%|████████▏ | 4950/6015 [31:03<04:09,  4.26it/s]

 82%|████████▏ | 4951/6015 [31:03<04:10,  4.26it/s]

 82%|████████▏ | 4952/6015 [31:04<04:09,  4.26it/s]

 82%|████████▏ | 4953/6015 [31:04<04:09,  4.26it/s]

 82%|████████▏ | 4954/6015 [31:04<04:08,  4.26it/s]

 82%|████████▏ | 4955/6015 [31:04<04:11,  4.22it/s]

 82%|████████▏ | 4956/6015 [31:05<04:10,  4.22it/s]

 82%|████████▏ | 4957/6015 [31:05<04:09,  4.23it/s]

 82%|████████▏ | 4958/6015 [31:05<04:09,  4.24it/s]

 82%|████████▏ | 4959/6015 [31:05<04:08,  4.25it/s]

 82%|████████▏ | 4960/6015 [31:06<04:08,  4.24it/s]

 82%|████████▏ | 4961/6015 [31:06<04:08,  4.25it/s]

 82%|████████▏ | 4962/6015 [31:06<04:07,  4.25it/s]

 83%|████████▎ | 4963/6015 [31:06<04:07,  4.26it/s]

 83%|████████▎ | 4964/6015 [31:07<04:06,  4.26it/s]

 83%|████████▎ | 4965/6015 [31:07<04:07,  4.25it/s]

 83%|████████▎ | 4966/6015 [31:07<04:06,  4.25it/s]

 83%|████████▎ | 4967/6015 [31:07<04:06,  4.25it/s]

 83%|████████▎ | 4968/6015 [31:07<04:06,  4.25it/s]

 83%|████████▎ | 4969/6015 [31:08<04:06,  4.25it/s]

 83%|████████▎ | 4970/6015 [31:08<04:06,  4.25it/s]

 83%|████████▎ | 4971/6015 [31:08<04:05,  4.26it/s]

 83%|████████▎ | 4972/6015 [31:08<04:04,  4.26it/s]

 83%|████████▎ | 4973/6015 [31:09<04:04,  4.26it/s]

 83%|████████▎ | 4974/6015 [31:09<04:04,  4.26it/s]

 83%|████████▎ | 4975/6015 [31:09<04:04,  4.25it/s]

 83%|████████▎ | 4976/6015 [31:09<04:04,  4.24it/s]

 83%|████████▎ | 4977/6015 [31:10<04:05,  4.24it/s]

 83%|████████▎ | 4978/6015 [31:10<04:04,  4.25it/s]

 83%|████████▎ | 4979/6015 [31:10<04:03,  4.25it/s]

 83%|████████▎ | 4980/6015 [31:10<04:03,  4.25it/s]

 83%|████████▎ | 4981/6015 [31:11<04:03,  4.25it/s]

 83%|████████▎ | 4982/6015 [31:11<04:03,  4.25it/s]

 83%|████████▎ | 4983/6015 [31:11<04:02,  4.25it/s]

 83%|████████▎ | 4984/6015 [31:11<04:02,  4.25it/s]

 83%|████████▎ | 4985/6015 [31:11<04:02,  4.25it/s]

 83%|████████▎ | 4986/6015 [31:12<04:01,  4.26it/s]

 83%|████████▎ | 4987/6015 [31:12<04:01,  4.26it/s]

 83%|████████▎ | 4988/6015 [31:12<04:01,  4.25it/s]

 83%|████████▎ | 4989/6015 [31:12<04:01,  4.24it/s]

 83%|████████▎ | 4990/6015 [31:13<04:02,  4.23it/s]

 83%|████████▎ | 4991/6015 [31:13<04:01,  4.23it/s]

 83%|████████▎ | 4992/6015 [31:13<04:01,  4.24it/s]

 83%|████████▎ | 4993/6015 [31:13<04:00,  4.24it/s]

 83%|████████▎ | 4994/6015 [31:14<04:00,  4.25it/s]

 83%|████████▎ | 4995/6015 [31:14<03:59,  4.25it/s]

 83%|████████▎ | 4996/6015 [31:14<03:59,  4.25it/s]

 83%|████████▎ | 4997/6015 [31:14<03:59,  4.25it/s]

 83%|████████▎ | 4998/6015 [31:15<03:59,  4.25it/s]

 83%|████████▎ | 4999/6015 [31:15<03:59,  4.25it/s]

 83%|████████▎ | 5000/6015 [31:15<03:59,  4.24it/s]

 83%|████████▎ | 5001/6015 [31:15<03:58,  4.25it/s]

 83%|████████▎ | 5002/6015 [31:15<03:58,  4.25it/s]

 83%|████████▎ | 5003/6015 [31:16<03:58,  4.24it/s]

 83%|████████▎ | 5004/6015 [31:16<03:57,  4.25it/s]

 83%|████████▎ | 5005/6015 [31:16<03:57,  4.25it/s]

 83%|████████▎ | 5006/6015 [31:16<03:58,  4.24it/s]

 83%|████████▎ | 5007/6015 [31:17<03:57,  4.24it/s]

logging
logging the anndata

 83%|████████▎ | 5008/6015 [31:18<08:41,  1.93it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 83%|████████▎ | 5009/6015 [31:18<07:13,  2.32it/s]

 83%|████████▎ | 5010/6015 [31:18<06:12,  2.70it/s]

 83%|████████▎ | 5011/6015 [31:19<05:29,  3.05it/s]

 83%|████████▎ | 5012/6015 [31:19<04:59,  3.35it/s]

 83%|████████▎ | 5013/6015 [31:19<04:38,  3.60it/s]

 83%|████████▎ | 5014/6015 [31:19<04:23,  3.80it/s]

 83%|████████▎ | 5015/6015 [31:19<04:12,  3.95it/s]

 83%|████████▎ | 5016/6015 [31:20<04:05,  4.07it/s]

 83%|████████▎ | 5017/6015 [31:20<04:00,  4.15it/s]

 83%|████████▎ | 5018/6015 [31:20<03:56,  4.22it/s]

 83%|████████▎ | 5019/6015 [31:20<03:53,  4.27it/s]

 83%|████████▎ | 5020/6015 [31:21<03:51,  4.30it/s]

 83%|████████▎ | 5021/6015 [31:21<03:50,  4.32it/s]

 83%|████████▎ | 5022/6015 [31:21<03:49,  4.34it/s]

 84%|████████▎ | 5023/6015 [31:21<03:48,  4.35it/s]

 84%|████████▎ | 5024/6015 [31:22<03:47,  4.36it/s]

 84%|████████▎ | 5025/6015 [31:22<03:46,  4.36it/s]

 84%|████████▎ | 5026/6015 [31:22<03:48,  4.32it/s]

 84%|████████▎ | 5027/6015 [31:22<03:47,  4.34it/s]

 84%|████████▎ | 5028/6015 [31:22<03:47,  4.34it/s]

 84%|████████▎ | 5029/6015 [31:23<03:46,  4.35it/s]

 84%|████████▎ | 5030/6015 [31:23<03:45,  4.36it/s]

 84%|████████▎ | 5031/6015 [31:23<03:45,  4.36it/s]

 84%|████████▎ | 5032/6015 [31:23<03:45,  4.36it/s]

 84%|████████▎ | 5033/6015 [31:24<03:45,  4.36it/s]

 84%|████████▎ | 5034/6015 [31:24<03:44,  4.36it/s]

 84%|████████▎ | 5035/6015 [31:24<03:44,  4.36it/s]

 84%|████████▎ | 5036/6015 [31:24<03:44,  4.36it/s]

 84%|████████▎ | 5037/6015 [31:24<03:44,  4.36it/s]

 84%|████████▍ | 5038/6015 [31:25<03:44,  4.35it/s]

 84%|████████▍ | 5039/6015 [31:25<03:44,  4.35it/s]

 84%|████████▍ | 5040/6015 [31:25<03:43,  4.35it/s]

 84%|████████▍ | 5041/6015 [31:25<03:43,  4.36it/s]

 84%|████████▍ | 5042/6015 [31:26<03:43,  4.35it/s]

 84%|████████▍ | 5043/6015 [31:26<03:43,  4.36it/s]

 84%|████████▍ | 5044/6015 [31:26<03:42,  4.36it/s]

 84%|████████▍ | 5045/6015 [31:26<03:42,  4.36it/s]

 84%|████████▍ | 5046/6015 [31:27<03:41,  4.37it/s]

 84%|████████▍ | 5047/6015 [31:27<03:41,  4.37it/s]

 84%|████████▍ | 5048/6015 [31:27<03:41,  4.37it/s]

 84%|████████▍ | 5049/6015 [31:27<03:41,  4.37it/s]

 84%|████████▍ | 5050/6015 [31:27<03:41,  4.36it/s]

 84%|████████▍ | 5051/6015 [31:28<03:40,  4.37it/s]

 84%|████████▍ | 5052/6015 [31:28<03:40,  4.37it/s]

 84%|████████▍ | 5053/6015 [31:28<03:41,  4.35it/s]

 84%|████████▍ | 5054/6015 [31:28<03:41,  4.35it/s]

 84%|████████▍ | 5055/6015 [31:29<03:40,  4.35it/s]

 84%|████████▍ | 5056/6015 [31:29<03:40,  4.35it/s]

 84%|████████▍ | 5057/6015 [31:29<03:39,  4.36it/s]

 84%|████████▍ | 5058/6015 [31:29<03:39,  4.36it/s]

 84%|████████▍ | 5059/6015 [31:30<03:39,  4.36it/s]

 84%|████████▍ | 5060/6015 [31:30<03:38,  4.36it/s]

 84%|████████▍ | 5061/6015 [31:30<03:39,  4.35it/s]

 84%|████████▍ | 5062/6015 [31:30<03:38,  4.36it/s]

 84%|████████▍ | 5063/6015 [31:30<03:38,  4.36it/s]

 84%|████████▍ | 5064/6015 [31:31<03:37,  4.36it/s]

 84%|████████▍ | 5065/6015 [31:31<03:39,  4.33it/s]

 84%|████████▍ | 5066/6015 [31:31<03:38,  4.34it/s]

 84%|████████▍ | 5067/6015 [31:31<03:38,  4.34it/s]

 84%|████████▍ | 5068/6015 [31:32<03:38,  4.34it/s]

 84%|████████▍ | 5069/6015 [31:32<03:37,  4.35it/s]

 84%|████████▍ | 5070/6015 [31:32<03:37,  4.35it/s]

 84%|████████▍ | 5071/6015 [31:32<03:36,  4.36it/s]

 84%|████████▍ | 5072/6015 [31:33<03:36,  4.35it/s]

 84%|████████▍ | 5073/6015 [31:33<03:36,  4.35it/s]

 84%|████████▍ | 5074/6015 [31:33<03:36,  4.35it/s]

 84%|████████▍ | 5075/6015 [31:33<03:35,  4.35it/s]

 84%|████████▍ | 5076/6015 [31:33<03:36,  4.35it/s]

 84%|████████▍ | 5077/6015 [31:34<03:35,  4.34it/s]

 84%|████████▍ | 5078/6015 [31:34<03:35,  4.35it/s]

 84%|████████▍ | 5079/6015 [31:34<03:34,  4.36it/s]

 84%|████████▍ | 5080/6015 [31:34<03:34,  4.36it/s]

 84%|████████▍ | 5081/6015 [31:35<03:33,  4.37it/s]

 84%|████████▍ | 5082/6015 [31:35<03:33,  4.37it/s]

 85%|████████▍ | 5083/6015 [31:35<03:33,  4.37it/s]

 85%|████████▍ | 5084/6015 [31:35<03:33,  4.37it/s]

 85%|████████▍ | 5085/6015 [31:36<03:33,  4.36it/s]

 85%|████████▍ | 5086/6015 [31:36<03:33,  4.35it/s]

 85%|████████▍ | 5087/6015 [31:36<03:33,  4.36it/s]

 85%|████████▍ | 5088/6015 [31:36<03:32,  4.35it/s]

 85%|████████▍ | 5089/6015 [31:36<03:32,  4.35it/s]

 85%|████████▍ | 5090/6015 [31:37<03:32,  4.35it/s]

 85%|████████▍ | 5091/6015 [31:37<03:32,  4.35it/s]

 85%|████████▍ | 5092/6015 [31:37<03:31,  4.36it/s]

 85%|████████▍ | 5093/6015 [31:37<03:31,  4.36it/s]

 85%|████████▍ | 5094/6015 [31:38<03:31,  4.35it/s]

 85%|████████▍ | 5095/6015 [31:38<03:31,  4.35it/s]

 85%|████████▍ | 5096/6015 [31:38<03:31,  4.35it/s]

 85%|████████▍ | 5097/6015 [31:38<03:30,  4.36it/s]

 85%|████████▍ | 5098/6015 [31:38<03:30,  4.35it/s]

 85%|████████▍ | 5099/6015 [31:39<03:31,  4.34it/s]

 85%|████████▍ | 5100/6015 [31:39<03:30,  4.35it/s]

 85%|████████▍ | 5101/6015 [31:39<03:30,  4.34it/s]

 85%|████████▍ | 5102/6015 [31:39<03:30,  4.34it/s]

 85%|████████▍ | 5103/6015 [31:40<03:30,  4.34it/s]

 85%|████████▍ | 5104/6015 [31:40<03:29,  4.34it/s]

 85%|████████▍ | 5105/6015 [31:40<03:29,  4.35it/s]

 85%|████████▍ | 5106/6015 [31:40<03:28,  4.36it/s]

 85%|████████▍ | 5107/6015 [31:41<03:28,  4.36it/s]

 85%|████████▍ | 5108/6015 [31:41<03:28,  4.36it/s]

 85%|████████▍ | 5109/6015 [31:41<03:28,  4.34it/s]

 85%|████████▍ | 5110/6015 [31:41<03:28,  4.35it/s]

 85%|████████▍ | 5111/6015 [31:41<03:28,  4.33it/s]

 85%|████████▍ | 5112/6015 [31:42<03:28,  4.33it/s]

 85%|████████▌ | 5113/6015 [31:42<03:28,  4.33it/s]

 85%|████████▌ | 5114/6015 [31:42<03:27,  4.34it/s]

 85%|████████▌ | 5115/6015 [31:42<03:27,  4.34it/s]

 85%|████████▌ | 5116/6015 [31:43<03:26,  4.35it/s]

 85%|████████▌ | 5117/6015 [31:43<03:26,  4.35it/s]

 85%|████████▌ | 5118/6015 [31:43<03:26,  4.35it/s]

 85%|████████▌ | 5119/6015 [31:43<03:25,  4.36it/s]

 85%|████████▌ | 5120/6015 [31:44<03:25,  4.35it/s]

 85%|████████▌ | 5121/6015 [31:44<03:25,  4.35it/s]

 85%|████████▌ | 5122/6015 [31:44<03:25,  4.35it/s]

 85%|████████▌ | 5123/6015 [31:44<03:25,  4.34it/s]

 85%|████████▌ | 5124/6015 [31:44<03:24,  4.35it/s]

 85%|████████▌ | 5125/6015 [31:45<03:24,  4.35it/s]

 85%|████████▌ | 5126/6015 [31:45<03:24,  4.34it/s]

 85%|████████▌ | 5127/6015 [31:45<03:24,  4.34it/s]

 85%|████████▌ | 5128/6015 [31:45<03:24,  4.34it/s]

 85%|████████▌ | 5129/6015 [31:46<03:24,  4.34it/s]

 85%|████████▌ | 5130/6015 [31:46<03:23,  4.34it/s]

 85%|████████▌ | 5131/6015 [31:46<03:23,  4.35it/s]

 85%|████████▌ | 5132/6015 [31:46<03:22,  4.35it/s]

 85%|████████▌ | 5133/6015 [31:47<03:22,  4.35it/s]

 85%|████████▌ | 5134/6015 [31:47<03:22,  4.34it/s]

 85%|████████▌ | 5135/6015 [31:47<03:22,  4.35it/s]

 85%|████████▌ | 5136/6015 [31:47<03:22,  4.33it/s]

 85%|████████▌ | 5137/6015 [31:47<03:22,  4.33it/s]

 85%|████████▌ | 5138/6015 [31:48<03:22,  4.34it/s]

 85%|████████▌ | 5139/6015 [31:48<03:21,  4.34it/s]

 85%|████████▌ | 5140/6015 [31:48<03:21,  4.34it/s]

 85%|████████▌ | 5141/6015 [31:48<03:21,  4.35it/s]

 85%|████████▌ | 5142/6015 [31:49<03:20,  4.34it/s]

 86%|████████▌ | 5143/6015 [31:49<03:20,  4.35it/s]

 86%|████████▌ | 5144/6015 [31:49<03:20,  4.34it/s]

 86%|████████▌ | 5145/6015 [31:49<03:20,  4.34it/s]

 86%|████████▌ | 5146/6015 [31:50<03:20,  4.34it/s]

 86%|████████▌ | 5147/6015 [31:50<03:19,  4.34it/s]

 86%|████████▌ | 5148/6015 [31:50<03:19,  4.34it/s]

 86%|████████▌ | 5149/6015 [31:50<03:19,  4.33it/s]

 86%|████████▌ | 5150/6015 [31:50<03:19,  4.33it/s]

 86%|████████▌ | 5151/6015 [31:51<03:19,  4.34it/s]

 86%|████████▌ | 5152/6015 [31:51<03:18,  4.34it/s]

 86%|████████▌ | 5153/6015 [31:51<03:18,  4.34it/s]

 86%|████████▌ | 5154/6015 [31:51<03:18,  4.35it/s]

 86%|████████▌ | 5155/6015 [31:52<03:17,  4.34it/s]

 86%|████████▌ | 5156/6015 [31:52<03:17,  4.35it/s]

 86%|████████▌ | 5157/6015 [31:52<03:17,  4.35it/s]

 86%|████████▌ | 5158/6015 [31:52<03:17,  4.34it/s]

 86%|████████▌ | 5159/6015 [31:53<03:17,  4.35it/s]

 86%|████████▌ | 5160/6015 [31:53<03:17,  4.34it/s]

 86%|████████▌ | 5161/6015 [31:53<03:16,  4.34it/s]

 86%|████████▌ | 5162/6015 [31:53<03:16,  4.33it/s]

 86%|████████▌ | 5163/6015 [31:53<03:16,  4.33it/s]

 86%|████████▌ | 5164/6015 [31:54<03:16,  4.33it/s]

 86%|████████▌ | 5165/6015 [31:54<03:16,  4.33it/s]

 86%|████████▌ | 5166/6015 [31:54<03:16,  4.32it/s]

 86%|████████▌ | 5167/6015 [31:54<03:15,  4.33it/s]

 86%|████████▌ | 5168/6015 [31:55<03:15,  4.32it/s]

 86%|████████▌ | 5169/6015 [31:55<03:15,  4.33it/s]

 86%|████████▌ | 5170/6015 [31:55<03:15,  4.31it/s]

 86%|████████▌ | 5171/6015 [31:55<03:15,  4.32it/s]

 86%|████████▌ | 5172/6015 [31:56<03:15,  4.32it/s]

 86%|████████▌ | 5173/6015 [31:56<03:14,  4.32it/s]

 86%|████████▌ | 5174/6015 [31:56<03:14,  4.32it/s]

 86%|████████▌ | 5175/6015 [31:56<03:14,  4.33it/s]

 86%|████████▌ | 5176/6015 [31:56<03:13,  4.33it/s]

 86%|████████▌ | 5177/6015 [31:57<03:13,  4.33it/s]

 86%|████████▌ | 5178/6015 [31:57<03:13,  4.32it/s]

 86%|████████▌ | 5179/6015 [31:57<03:13,  4.32it/s]

 86%|████████▌ | 5180/6015 [31:57<03:13,  4.31it/s]

 86%|████████▌ | 5181/6015 [31:58<03:13,  4.32it/s]

 86%|████████▌ | 5182/6015 [31:58<03:12,  4.32it/s]

 86%|████████▌ | 5183/6015 [31:58<03:12,  4.33it/s]

 86%|████████▌ | 5184/6015 [31:58<03:12,  4.32it/s]

 86%|████████▌ | 5185/6015 [31:59<03:12,  4.32it/s]

 86%|████████▌ | 5186/6015 [31:59<03:11,  4.32it/s]

 86%|████████▌ | 5187/6015 [31:59<03:11,  4.32it/s]

 86%|████████▋ | 5188/6015 [31:59<03:10,  4.33it/s]

 86%|████████▋ | 5189/6015 [31:59<03:10,  4.33it/s]

 86%|████████▋ | 5190/6015 [32:00<03:10,  4.33it/s]

 86%|████████▋ | 5191/6015 [32:00<03:10,  4.33it/s]

 86%|████████▋ | 5192/6015 [32:00<03:10,  4.33it/s]

 86%|████████▋ | 5193/6015 [32:00<03:09,  4.33it/s]

 86%|████████▋ | 5194/6015 [32:01<03:09,  4.33it/s]

 86%|████████▋ | 5195/6015 [32:01<03:09,  4.32it/s]

 86%|████████▋ | 5196/6015 [32:01<03:09,  4.33it/s]

 86%|████████▋ | 5197/6015 [32:01<03:08,  4.33it/s]

 86%|████████▋ | 5198/6015 [32:02<03:08,  4.32it/s]

 86%|████████▋ | 5199/6015 [32:02<03:08,  4.33it/s]

 86%|████████▋ | 5200/6015 [32:02<03:08,  4.33it/s]

 86%|████████▋ | 5201/6015 [32:02<03:07,  4.33it/s]

 86%|████████▋ | 5202/6015 [32:02<03:07,  4.33it/s]

 87%|████████▋ | 5203/6015 [32:03<03:07,  4.33it/s]

 87%|████████▋ | 5204/6015 [32:03<03:07,  4.33it/s]

 87%|████████▋ | 5205/6015 [32:03<03:06,  4.33it/s]

 87%|████████▋ | 5206/6015 [32:03<03:06,  4.33it/s]

 87%|████████▋ | 5207/6015 [32:04<03:06,  4.34it/s]

 87%|████████▋ | 5208/6015 [32:04<03:05,  4.34it/s]

 87%|████████▋ | 5209/6015 [32:04<03:05,  4.34it/s]

 87%|████████▋ | 5210/6015 [32:04<03:05,  4.34it/s]

 87%|████████▋ | 5211/6015 [32:05<03:05,  4.32it/s]

 87%|████████▋ | 5212/6015 [32:05<03:05,  4.33it/s]

 87%|████████▋ | 5213/6015 [32:05<03:05,  4.33it/s]

 87%|████████▋ | 5214/6015 [32:05<03:04,  4.33it/s]

 87%|████████▋ | 5215/6015 [32:05<03:04,  4.34it/s]

 87%|████████▋ | 5216/6015 [32:06<03:04,  4.34it/s]

 87%|████████▋ | 5217/6015 [32:06<03:04,  4.34it/s]

 87%|████████▋ | 5218/6015 [32:06<03:03,  4.34it/s]

 87%|████████▋ | 5219/6015 [32:06<03:03,  4.34it/s]

 87%|████████▋ | 5220/6015 [32:07<03:03,  4.34it/s]

 87%|████████▋ | 5221/6015 [32:07<03:02,  4.34it/s]

 87%|████████▋ | 5222/6015 [32:07<03:02,  4.34it/s]

 87%|████████▋ | 5223/6015 [32:07<03:02,  4.34it/s]

 87%|████████▋ | 5224/6015 [32:08<03:02,  4.33it/s]

 87%|████████▋ | 5225/6015 [32:08<03:02,  4.33it/s]

 87%|████████▋ | 5226/6015 [32:08<03:02,  4.33it/s]

 87%|████████▋ | 5227/6015 [32:08<03:02,  4.32it/s]

 87%|████████▋ | 5228/6015 [32:08<03:01,  4.33it/s]

 87%|████████▋ | 5229/6015 [32:09<03:01,  4.33it/s]

 87%|████████▋ | 5230/6015 [32:09<03:01,  4.33it/s]

 87%|████████▋ | 5231/6015 [32:09<03:00,  4.33it/s]

 87%|████████▋ | 5232/6015 [32:09<03:00,  4.33it/s]

 87%|████████▋ | 5233/6015 [32:10<03:00,  4.33it/s]

 87%|████████▋ | 5234/6015 [32:10<03:00,  4.33it/s]

 87%|████████▋ | 5235/6015 [32:10<03:00,  4.32it/s]

 87%|████████▋ | 5236/6015 [32:10<03:00,  4.32it/s]

 87%|████████▋ | 5237/6015 [32:11<02:59,  4.33it/s]

 87%|████████▋ | 5238/6015 [32:11<02:59,  4.32it/s]

 87%|████████▋ | 5239/6015 [32:11<02:59,  4.32it/s]

 87%|████████▋ | 5240/6015 [32:11<02:59,  4.33it/s]

 87%|████████▋ | 5241/6015 [32:11<02:59,  4.32it/s]

 87%|████████▋ | 5242/6015 [32:12<02:59,  4.31it/s]

 87%|████████▋ | 5243/6015 [32:12<02:59,  4.31it/s]

 87%|████████▋ | 5244/6015 [32:12<02:58,  4.32it/s]

 87%|████████▋ | 5245/6015 [32:12<02:58,  4.33it/s]

 87%|████████▋ | 5246/6015 [32:13<02:57,  4.33it/s]

 87%|████████▋ | 5247/6015 [32:13<02:57,  4.33it/s]

 87%|████████▋ | 5248/6015 [32:13<02:57,  4.31it/s]

 87%|████████▋ | 5249/6015 [32:13<02:57,  4.31it/s]

 87%|████████▋ | 5250/6015 [32:14<02:58,  4.30it/s]

 87%|████████▋ | 5251/6015 [32:14<02:57,  4.30it/s]

 87%|████████▋ | 5252/6015 [32:14<02:57,  4.31it/s]

 87%|████████▋ | 5253/6015 [32:14<02:56,  4.32it/s]

 87%|████████▋ | 5254/6015 [32:15<02:56,  4.30it/s]

 87%|████████▋ | 5255/6015 [32:15<02:56,  4.32it/s]

 87%|████████▋ | 5256/6015 [32:15<02:55,  4.32it/s]

 87%|████████▋ | 5257/6015 [32:15<02:55,  4.32it/s]

 87%|████████▋ | 5258/6015 [32:15<02:55,  4.32it/s]

 87%|████████▋ | 5259/6015 [32:16<02:55,  4.32it/s]

 87%|████████▋ | 5260/6015 [32:16<02:54,  4.32it/s]

 87%|████████▋ | 5261/6015 [32:16<02:54,  4.32it/s]

 87%|████████▋ | 5262/6015 [32:16<02:54,  4.31it/s]

 87%|████████▋ | 5263/6015 [32:17<02:54,  4.32it/s]

 88%|████████▊ | 5264/6015 [32:17<02:53,  4.32it/s]

 88%|████████▊ | 5265/6015 [32:17<02:53,  4.32it/s]

 88%|████████▊ | 5266/6015 [32:17<02:52,  4.33it/s]

 88%|████████▊ | 5267/6015 [32:18<02:52,  4.33it/s]

 88%|████████▊ | 5268/6015 [32:18<02:52,  4.33it/s]

 88%|████████▊ | 5269/6015 [32:18<02:52,  4.33it/s]

 88%|████████▊ | 5270/6015 [32:18<02:52,  4.32it/s]

 88%|████████▊ | 5271/6015 [32:18<02:51,  4.33it/s]

 88%|████████▊ | 5272/6015 [32:19<02:51,  4.34it/s]

 88%|████████▊ | 5273/6015 [32:19<02:51,  4.33it/s]

 88%|████████▊ | 5274/6015 [32:19<02:51,  4.32it/s]

 88%|████████▊ | 5275/6015 [32:19<02:51,  4.31it/s]

 88%|████████▊ | 5276/6015 [32:20<02:51,  4.31it/s]

 88%|████████▊ | 5277/6015 [32:20<02:51,  4.31it/s]

 88%|████████▊ | 5278/6015 [32:20<02:51,  4.31it/s]

 88%|████████▊ | 5279/6015 [32:20<02:50,  4.31it/s]

 88%|████████▊ | 5280/6015 [32:21<02:50,  4.32it/s]

 88%|████████▊ | 5281/6015 [32:21<02:49,  4.32it/s]

 88%|████████▊ | 5282/6015 [32:21<02:49,  4.32it/s]

 88%|████████▊ | 5283/6015 [32:21<02:49,  4.32it/s]

 88%|████████▊ | 5284/6015 [32:21<02:49,  4.32it/s]

 88%|████████▊ | 5285/6015 [32:22<02:50,  4.29it/s]

 88%|████████▊ | 5286/6015 [32:22<02:49,  4.30it/s]

 88%|████████▊ | 5287/6015 [32:22<02:48,  4.31it/s]

 88%|████████▊ | 5288/6015 [32:22<02:48,  4.32it/s]

 88%|████████▊ | 5289/6015 [32:23<02:48,  4.32it/s]

 88%|████████▊ | 5290/6015 [32:23<02:47,  4.32it/s]

 88%|████████▊ | 5291/6015 [32:23<02:47,  4.32it/s]

 88%|████████▊ | 5292/6015 [32:23<02:47,  4.32it/s]

 88%|████████▊ | 5293/6015 [32:24<02:47,  4.32it/s]

 88%|████████▊ | 5294/6015 [32:24<02:46,  4.32it/s]

 88%|████████▊ | 5295/6015 [32:24<02:46,  4.33it/s]

 88%|████████▊ | 5296/6015 [32:24<02:45,  4.33it/s]

 88%|████████▊ | 5297/6015 [32:24<02:46,  4.32it/s]

 88%|████████▊ | 5298/6015 [32:25<02:46,  4.32it/s]

 88%|████████▊ | 5299/6015 [32:25<02:45,  4.33it/s]

 88%|████████▊ | 5300/6015 [32:25<02:45,  4.33it/s]

 88%|████████▊ | 5301/6015 [32:25<02:45,  4.32it/s]

 88%|████████▊ | 5302/6015 [32:26<02:44,  4.32it/s]

 88%|████████▊ | 5303/6015 [32:26<02:44,  4.32it/s]

 88%|████████▊ | 5304/6015 [32:26<02:44,  4.33it/s]

 88%|████████▊ | 5305/6015 [32:26<02:44,  4.32it/s]

 88%|████████▊ | 5306/6015 [32:27<02:44,  4.31it/s]

 88%|████████▊ | 5307/6015 [32:27<02:45,  4.28it/s]

 88%|████████▊ | 5308/6015 [32:27<02:44,  4.29it/s]

 88%|████████▊ | 5309/6015 [32:27<02:44,  4.30it/s]

 88%|████████▊ | 5310/6015 [32:27<02:43,  4.31it/s]

 88%|████████▊ | 5311/6015 [32:28<02:43,  4.31it/s]

 88%|████████▊ | 5312/6015 [32:28<02:42,  4.32it/s]

 88%|████████▊ | 5313/6015 [32:28<02:42,  4.33it/s]

 88%|████████▊ | 5314/6015 [32:28<02:42,  4.32it/s]

 88%|████████▊ | 5315/6015 [32:29<02:41,  4.33it/s]

 88%|████████▊ | 5316/6015 [32:29<02:41,  4.33it/s]

 88%|████████▊ | 5317/6015 [32:29<02:41,  4.33it/s]

 88%|████████▊ | 5318/6015 [32:29<02:40,  4.34it/s]

 88%|████████▊ | 5319/6015 [32:30<02:40,  4.33it/s]

 88%|████████▊ | 5320/6015 [32:30<02:40,  4.34it/s]

 88%|████████▊ | 5321/6015 [32:30<02:40,  4.34it/s]

 88%|████████▊ | 5322/6015 [32:30<02:39,  4.34it/s]

 88%|████████▊ | 5323/6015 [32:30<02:39,  4.34it/s]

 89%|████████▊ | 5324/6015 [32:31<02:39,  4.33it/s]

 89%|████████▊ | 5325/6015 [32:31<02:39,  4.34it/s]

 89%|████████▊ | 5326/6015 [32:31<02:38,  4.34it/s]

 89%|████████▊ | 5327/6015 [32:31<02:38,  4.34it/s]

 89%|████████▊ | 5328/6015 [32:32<02:38,  4.34it/s]

 89%|████████▊ | 5329/6015 [32:32<02:38,  4.33it/s]

 89%|████████▊ | 5330/6015 [32:32<02:38,  4.33it/s]

 89%|████████▊ | 5331/6015 [32:32<02:38,  4.32it/s]

 89%|████████▊ | 5332/6015 [32:33<02:38,  4.32it/s]

 89%|████████▊ | 5333/6015 [32:33<02:37,  4.32it/s]

 89%|████████▊ | 5334/6015 [32:33<02:37,  4.32it/s]

 89%|████████▊ | 5335/6015 [32:33<02:37,  4.32it/s]

 89%|████████▊ | 5336/6015 [32:33<02:36,  4.33it/s]

 89%|████████▊ | 5337/6015 [32:34<02:36,  4.34it/s]

 89%|████████▊ | 5338/6015 [32:34<02:36,  4.32it/s]

 89%|████████▉ | 5339/6015 [32:34<02:36,  4.33it/s]

 89%|████████▉ | 5340/6015 [32:34<02:35,  4.33it/s]

 89%|████████▉ | 5341/6015 [32:35<02:35,  4.33it/s]

 89%|████████▉ | 5342/6015 [32:35<02:35,  4.32it/s]

 89%|████████▉ | 5343/6015 [32:35<02:35,  4.31it/s]

 89%|████████▉ | 5344/6015 [32:35<02:35,  4.31it/s]

 89%|████████▉ | 5345/6015 [32:36<02:35,  4.31it/s]

 89%|████████▉ | 5346/6015 [32:36<02:34,  4.32it/s]

 89%|████████▉ | 5347/6015 [32:36<02:34,  4.32it/s]

 89%|████████▉ | 5348/6015 [32:36<02:34,  4.33it/s]

 89%|████████▉ | 5349/6015 [32:36<02:33,  4.34it/s]

 89%|████████▉ | 5350/6015 [32:37<02:33,  4.32it/s]

 89%|████████▉ | 5351/6015 [32:37<02:34,  4.31it/s]

 89%|████████▉ | 5352/6015 [32:37<02:33,  4.32it/s]

 89%|████████▉ | 5353/6015 [32:37<02:33,  4.32it/s]

 89%|████████▉ | 5354/6015 [32:38<02:32,  4.32it/s]

 89%|████████▉ | 5355/6015 [32:38<02:32,  4.32it/s]

 89%|████████▉ | 5356/6015 [32:38<02:32,  4.32it/s]

 89%|████████▉ | 5357/6015 [32:38<02:32,  4.33it/s]

 89%|████████▉ | 5358/6015 [32:39<02:31,  4.33it/s]

 89%|████████▉ | 5359/6015 [32:39<02:31,  4.32it/s]

 89%|████████▉ | 5360/6015 [32:39<02:31,  4.32it/s]

 89%|████████▉ | 5361/6015 [32:39<02:31,  4.32it/s]

 89%|████████▉ | 5362/6015 [32:39<02:31,  4.32it/s]

 89%|████████▉ | 5363/6015 [32:40<02:31,  4.31it/s]

 89%|████████▉ | 5364/6015 [32:40<02:31,  4.31it/s]

 89%|████████▉ | 5365/6015 [32:40<02:30,  4.32it/s]

 89%|████████▉ | 5366/6015 [32:40<02:30,  4.31it/s]

 89%|████████▉ | 5367/6015 [32:41<02:30,  4.29it/s]

 89%|████████▉ | 5368/6015 [32:41<02:30,  4.30it/s]

 89%|████████▉ | 5369/6015 [32:41<02:30,  4.30it/s]

 89%|████████▉ | 5370/6015 [32:41<02:30,  4.30it/s]

 89%|████████▉ | 5371/6015 [32:42<02:29,  4.30it/s]

 89%|████████▉ | 5372/6015 [32:42<02:29,  4.30it/s]

 89%|████████▉ | 5373/6015 [32:42<02:28,  4.31it/s]

 89%|████████▉ | 5374/6015 [32:42<02:28,  4.31it/s]

 89%|████████▉ | 5375/6015 [32:43<02:28,  4.31it/s]

 89%|████████▉ | 5376/6015 [32:43<02:28,  4.31it/s]

 89%|████████▉ | 5377/6015 [32:43<02:28,  4.30it/s]

 89%|████████▉ | 5378/6015 [32:43<02:27,  4.32it/s]

 89%|████████▉ | 5379/6015 [32:43<02:27,  4.32it/s]

 89%|████████▉ | 5380/6015 [32:44<02:27,  4.31it/s]

 89%|████████▉ | 5381/6015 [32:44<02:26,  4.32it/s]

 89%|████████▉ | 5382/6015 [32:44<02:26,  4.32it/s]

 89%|████████▉ | 5383/6015 [32:44<02:26,  4.32it/s]

 90%|████████▉ | 5384/6015 [32:45<02:26,  4.32it/s]

 90%|████████▉ | 5385/6015 [32:45<02:26,  4.31it/s]

 90%|████████▉ | 5386/6015 [32:45<02:25,  4.31it/s]

 90%|████████▉ | 5387/6015 [32:45<02:25,  4.31it/s]

 90%|████████▉ | 5388/6015 [32:46<02:25,  4.30it/s]

 90%|████████▉ | 5389/6015 [32:46<02:25,  4.29it/s]

 90%|████████▉ | 5390/6015 [32:46<02:25,  4.30it/s]

 90%|████████▉ | 5391/6015 [32:46<02:24,  4.31it/s]

 90%|████████▉ | 5392/6015 [32:46<02:24,  4.31it/s]

 90%|████████▉ | 5393/6015 [32:47<02:24,  4.31it/s]

 90%|████████▉ | 5394/6015 [32:47<02:24,  4.31it/s]

 90%|████████▉ | 5395/6015 [32:47<02:24,  4.30it/s]

 90%|████████▉ | 5396/6015 [32:47<02:23,  4.31it/s]

 90%|████████▉ | 5397/6015 [32:48<02:23,  4.31it/s]

 90%|████████▉ | 5398/6015 [32:48<02:23,  4.31it/s]

 90%|████████▉ | 5399/6015 [32:48<02:22,  4.33it/s]

 90%|████████▉ | 5400/6015 [32:48<02:22,  4.32it/s]

 90%|████████▉ | 5401/6015 [32:49<02:22,  4.32it/s]

 90%|████████▉ | 5402/6015 [32:49<02:22,  4.30it/s]

 90%|████████▉ | 5403/6015 [32:49<02:22,  4.30it/s]

 90%|████████▉ | 5404/6015 [32:49<02:21,  4.30it/s]

 90%|████████▉ | 5405/6015 [32:49<02:21,  4.31it/s]

 90%|████████▉ | 5406/6015 [32:50<02:21,  4.30it/s]

 90%|████████▉ | 5407/6015 [32:50<02:21,  4.31it/s]

 90%|████████▉ | 5408/6015 [32:50<02:20,  4.31it/s]

 90%|████████▉ | 5409/6015 [32:50<02:20,  4.31it/s]

 90%|████████▉ | 5410/6015 [32:51<02:20,  4.31it/s]

 90%|████████▉ | 5411/6015 [32:51<02:20,  4.31it/s]

 90%|████████▉ | 5412/6015 [32:51<02:19,  4.31it/s]

 90%|████████▉ | 5413/6015 [32:51<02:19,  4.31it/s]

 90%|█████████ | 5414/6015 [32:52<02:19,  4.30it/s]

 90%|█████████ | 5415/6015 [32:52<02:19,  4.30it/s]

 90%|█████████ | 5416/6015 [32:52<02:19,  4.30it/s]

 90%|█████████ | 5417/6015 [32:52<02:18,  4.30it/s]

 90%|█████████ | 5418/6015 [32:52<02:18,  4.31it/s]

 90%|█████████ | 5419/6015 [32:53<02:18,  4.30it/s]

 90%|█████████ | 5420/6015 [32:53<02:18,  4.29it/s]

 90%|█████████ | 5421/6015 [32:53<02:18,  4.28it/s]

 90%|█████████ | 5422/6015 [32:53<02:18,  4.28it/s]

 90%|█████████ | 5423/6015 [32:54<02:17,  4.29it/s]

 90%|█████████ | 5424/6015 [32:54<02:17,  4.29it/s]

 90%|█████████ | 5425/6015 [32:54<02:17,  4.30it/s]

 90%|█████████ | 5426/6015 [32:54<02:17,  4.30it/s]

 90%|█████████ | 5427/6015 [32:55<02:16,  4.29it/s]

 90%|█████████ | 5428/6015 [32:55<02:16,  4.30it/s]

 90%|█████████ | 5429/6015 [32:55<02:16,  4.30it/s]

 90%|█████████ | 5430/6015 [32:55<02:15,  4.30it/s]

 90%|█████████ | 5431/6015 [32:56<02:15,  4.30it/s]

 90%|█████████ | 5432/6015 [32:56<02:15,  4.29it/s]

 90%|█████████ | 5433/6015 [32:56<02:15,  4.30it/s]

 90%|█████████ | 5434/6015 [32:56<02:15,  4.30it/s]

 90%|█████████ | 5435/6015 [32:56<02:14,  4.30it/s]

 90%|█████████ | 5436/6015 [32:57<02:14,  4.30it/s]

 90%|█████████ | 5437/6015 [32:57<02:14,  4.29it/s]

 90%|█████████ | 5438/6015 [32:57<02:14,  4.30it/s]

 90%|█████████ | 5439/6015 [32:57<02:14,  4.29it/s]

 90%|█████████ | 5440/6015 [32:58<02:13,  4.30it/s]

 90%|█████████ | 5441/6015 [32:58<02:13,  4.30it/s]

 90%|█████████ | 5442/6015 [32:58<02:13,  4.30it/s]

 90%|█████████ | 5443/6015 [32:58<02:12,  4.30it/s]

 91%|█████████ | 5444/6015 [32:59<02:12,  4.30it/s]

 91%|█████████ | 5445/6015 [32:59<02:12,  4.31it/s]

 91%|█████████ | 5446/6015 [32:59<02:11,  4.31it/s]

 91%|█████████ | 5447/6015 [32:59<02:12,  4.29it/s]

 91%|█████████ | 5448/6015 [32:59<02:11,  4.30it/s]

 91%|█████████ | 5449/6015 [33:00<02:11,  4.30it/s]

 91%|█████████ | 5450/6015 [33:00<02:11,  4.31it/s]

 91%|█████████ | 5451/6015 [33:00<02:11,  4.30it/s]

 91%|█████████ | 5452/6015 [33:00<02:10,  4.30it/s]

 91%|█████████ | 5453/6015 [33:01<02:10,  4.30it/s]

 91%|█████████ | 5454/6015 [33:01<02:10,  4.30it/s]

 91%|█████████ | 5455/6015 [33:01<02:10,  4.30it/s]

 91%|█████████ | 5456/6015 [33:01<02:09,  4.31it/s]

 91%|█████████ | 5457/6015 [33:02<02:09,  4.30it/s]

 91%|█████████ | 5458/6015 [33:02<02:09,  4.30it/s]

 91%|█████████ | 5459/6015 [33:02<02:09,  4.29it/s]

 91%|█████████ | 5460/6015 [33:02<02:09,  4.30it/s]

 91%|█████████ | 5461/6015 [33:02<02:08,  4.30it/s]

 91%|█████████ | 5462/6015 [33:03<02:08,  4.30it/s]

 91%|█████████ | 5463/6015 [33:03<02:08,  4.30it/s]

 91%|█████████ | 5464/6015 [33:03<02:07,  4.31it/s]

 91%|█████████ | 5465/6015 [33:03<02:07,  4.30it/s]

 91%|█████████ | 5466/6015 [33:04<02:07,  4.30it/s]

 91%|█████████ | 5467/6015 [33:04<02:07,  4.31it/s]

 91%|█████████ | 5468/6015 [33:04<02:07,  4.30it/s]

 91%|█████████ | 5469/6015 [33:04<02:06,  4.31it/s]

 91%|█████████ | 5470/6015 [33:05<02:06,  4.31it/s]

 91%|█████████ | 5471/6015 [33:05<02:06,  4.29it/s]

 91%|█████████ | 5472/6015 [33:05<02:06,  4.29it/s]

 91%|█████████ | 5473/6015 [33:05<02:06,  4.30it/s]

 91%|█████████ | 5474/6015 [33:06<02:05,  4.30it/s]

 91%|█████████ | 5475/6015 [33:06<02:05,  4.29it/s]

 91%|█████████ | 5476/6015 [33:06<02:05,  4.28it/s]

 91%|█████████ | 5477/6015 [33:06<02:05,  4.28it/s]

 91%|█████████ | 5478/6015 [33:06<02:05,  4.27it/s]

 91%|█████████ | 5479/6015 [33:07<02:05,  4.28it/s]

 91%|█████████ | 5480/6015 [33:07<02:04,  4.28it/s]

 91%|█████████ | 5481/6015 [33:07<02:04,  4.28it/s]

 91%|█████████ | 5482/6015 [33:07<02:04,  4.28it/s]

 91%|█████████ | 5483/6015 [33:08<02:04,  4.28it/s]

 91%|█████████ | 5484/6015 [33:08<02:03,  4.29it/s]

 91%|█████████ | 5485/6015 [33:08<02:03,  4.29it/s]

 91%|█████████ | 5486/6015 [33:08<02:03,  4.29it/s]

 91%|█████████ | 5487/6015 [33:09<02:02,  4.30it/s]

 91%|█████████ | 5488/6015 [33:09<02:02,  4.29it/s]

 91%|█████████▏| 5489/6015 [33:09<02:02,  4.29it/s]

 91%|█████████▏| 5490/6015 [33:09<02:02,  4.28it/s]

 91%|█████████▏| 5491/6015 [33:09<02:02,  4.28it/s]

 91%|█████████▏| 5492/6015 [33:10<02:02,  4.28it/s]

 91%|█████████▏| 5493/6015 [33:10<02:01,  4.28it/s]

 91%|█████████▏| 5494/6015 [33:10<02:02,  4.26it/s]

 91%|█████████▏| 5495/6015 [33:10<02:01,  4.27it/s]

 91%|█████████▏| 5496/6015 [33:11<02:01,  4.27it/s]

 91%|█████████▏| 5497/6015 [33:11<02:01,  4.27it/s]

 91%|█████████▏| 5498/6015 [33:11<02:00,  4.28it/s]

 91%|█████████▏| 5499/6015 [33:11<02:01,  4.26it/s]

 91%|█████████▏| 5500/6015 [33:12<02:00,  4.26it/s]

 91%|█████████▏| 5501/6015 [33:12<02:00,  4.27it/s]

 91%|█████████▏| 5502/6015 [33:12<02:00,  4.27it/s]

 91%|█████████▏| 5503/6015 [33:12<01:59,  4.28it/s]

 92%|█████████▏| 5504/6015 [33:13<01:59,  4.27it/s]

 92%|█████████▏| 5505/6015 [33:13<01:59,  4.28it/s]

 92%|█████████▏| 5506/6015 [33:13<01:58,  4.28it/s]

 92%|█████████▏| 5507/6015 [33:13<01:58,  4.29it/s]

 92%|█████████▏| 5508/6015 [33:13<01:58,  4.29it/s]

 92%|█████████▏| 5509/6015 [33:14<01:58,  4.29it/s]

 92%|█████████▏| 5510/6015 [33:14<01:57,  4.29it/s]

 92%|█████████▏| 5511/6015 [33:14<01:57,  4.29it/s]

 92%|█████████▏| 5512/6015 [33:14<01:57,  4.29it/s]

 92%|█████████▏| 5513/6015 [33:15<01:57,  4.28it/s]

 92%|█████████▏| 5514/6015 [33:15<01:57,  4.27it/s]

 92%|█████████▏| 5515/6015 [33:15<01:56,  4.29it/s]

 92%|█████████▏| 5516/6015 [33:15<01:56,  4.29it/s]

 92%|█████████▏| 5517/6015 [33:16<01:56,  4.29it/s]

 92%|█████████▏| 5518/6015 [33:16<01:55,  4.29it/s]

 92%|█████████▏| 5519/6015 [33:16<01:55,  4.29it/s]

 92%|█████████▏| 5520/6015 [33:16<01:55,  4.29it/s]

 92%|█████████▏| 5521/6015 [33:16<01:55,  4.29it/s]

 92%|█████████▏| 5522/6015 [33:17<01:54,  4.29it/s]

 92%|█████████▏| 5523/6015 [33:17<01:54,  4.30it/s]

 92%|█████████▏| 5524/6015 [33:17<01:54,  4.29it/s]

 92%|█████████▏| 5525/6015 [33:17<01:54,  4.28it/s]

 92%|█████████▏| 5526/6015 [33:18<01:54,  4.28it/s]

 92%|█████████▏| 5527/6015 [33:18<01:55,  4.21it/s]

 92%|█████████▏| 5528/6015 [33:18<01:55,  4.22it/s]

 92%|█████████▏| 5529/6015 [33:18<01:54,  4.23it/s]

 92%|█████████▏| 5530/6015 [33:19<01:54,  4.23it/s]

 92%|█████████▏| 5531/6015 [33:19<01:54,  4.24it/s]

 92%|█████████▏| 5532/6015 [33:19<01:53,  4.25it/s]

 92%|█████████▏| 5533/6015 [33:19<01:53,  4.25it/s]

 92%|█████████▏| 5534/6015 [33:20<01:52,  4.26it/s]

 92%|█████████▏| 5535/6015 [33:20<01:52,  4.26it/s]

 92%|█████████▏| 5536/6015 [33:20<01:52,  4.27it/s]

 92%|█████████▏| 5537/6015 [33:20<01:52,  4.27it/s]

 92%|█████████▏| 5538/6015 [33:20<01:51,  4.27it/s]

 92%|█████████▏| 5539/6015 [33:21<01:51,  4.26it/s]

 92%|█████████▏| 5540/6015 [33:21<01:51,  4.26it/s]

 92%|█████████▏| 5541/6015 [33:21<01:51,  4.26it/s]

 92%|█████████▏| 5542/6015 [33:21<01:51,  4.25it/s]

 92%|█████████▏| 5543/6015 [33:22<01:50,  4.26it/s]

 92%|█████████▏| 5544/6015 [33:22<01:50,  4.26it/s]

 92%|█████████▏| 5545/6015 [33:22<01:50,  4.26it/s]

 92%|█████████▏| 5546/6015 [33:22<01:50,  4.26it/s]

 92%|█████████▏| 5547/6015 [33:23<01:50,  4.25it/s]

 92%|█████████▏| 5548/6015 [33:23<01:49,  4.25it/s]

 92%|█████████▏| 5549/6015 [33:23<01:49,  4.24it/s]

 92%|█████████▏| 5550/6015 [33:23<01:49,  4.24it/s]

 92%|█████████▏| 5551/6015 [33:24<01:49,  4.24it/s]

 92%|█████████▏| 5552/6015 [33:24<01:49,  4.24it/s]

 92%|█████████▏| 5553/6015 [33:24<01:48,  4.25it/s]

 92%|█████████▏| 5554/6015 [33:24<01:48,  4.25it/s]

 92%|█████████▏| 5555/6015 [33:24<01:48,  4.24it/s]

 92%|█████████▏| 5556/6015 [33:25<01:48,  4.24it/s]

 92%|█████████▏| 5557/6015 [33:25<01:48,  4.24it/s]

 92%|█████████▏| 5558/6015 [33:25<01:47,  4.24it/s]

 92%|█████████▏| 5559/6015 [33:25<01:47,  4.25it/s]

 92%|█████████▏| 5560/6015 [33:26<01:47,  4.25it/s]

 92%|█████████▏| 5561/6015 [33:26<01:46,  4.25it/s]

 92%|█████████▏| 5562/6015 [33:26<01:46,  4.25it/s]

 92%|█████████▏| 5563/6015 [33:26<01:46,  4.24it/s]

 93%|█████████▎| 5564/6015 [33:27<01:46,  4.25it/s]

 93%|█████████▎| 5565/6015 [33:27<01:45,  4.25it/s]

 93%|█████████▎| 5566/6015 [33:27<01:45,  4.26it/s]

 93%|█████████▎| 5567/6015 [33:27<01:45,  4.25it/s]

 93%|█████████▎| 5568/6015 [33:28<01:45,  4.25it/s]

 93%|█████████▎| 5569/6015 [33:28<01:44,  4.25it/s]

 93%|█████████▎| 5570/6015 [33:28<01:44,  4.25it/s]

 93%|█████████▎| 5571/6015 [33:28<01:44,  4.23it/s]

 93%|█████████▎| 5572/6015 [33:28<01:44,  4.23it/s]

 93%|█████████▎| 5573/6015 [33:29<01:44,  4.24it/s]

 93%|█████████▎| 5574/6015 [33:29<01:43,  4.25it/s]

 93%|█████████▎| 5575/6015 [33:29<01:43,  4.25it/s]

 93%|█████████▎| 5576/6015 [33:29<01:43,  4.25it/s]

 93%|█████████▎| 5577/6015 [33:30<01:42,  4.25it/s]

 93%|█████████▎| 5578/6015 [33:30<01:42,  4.25it/s]

 93%|█████████▎| 5579/6015 [33:30<01:42,  4.25it/s]

 93%|█████████▎| 5580/6015 [33:30<01:42,  4.26it/s]

 93%|█████████▎| 5581/6015 [33:31<01:42,  4.22it/s]

 93%|█████████▎| 5582/6015 [33:31<01:42,  4.22it/s]

 93%|█████████▎| 5583/6015 [33:31<01:42,  4.23it/s]

 93%|█████████▎| 5584/6015 [33:31<01:41,  4.24it/s]

 93%|█████████▎| 5585/6015 [33:32<01:41,  4.24it/s]

 93%|█████████▎| 5586/6015 [33:32<01:41,  4.25it/s]

 93%|█████████▎| 5587/6015 [33:32<01:40,  4.24it/s]

 93%|█████████▎| 5588/6015 [33:32<01:40,  4.24it/s]

 93%|█████████▎| 5589/6015 [33:33<01:40,  4.25it/s]

 93%|█████████▎| 5590/6015 [33:33<01:40,  4.25it/s]

 93%|█████████▎| 5591/6015 [33:33<01:39,  4.25it/s]

 93%|█████████▎| 5592/6015 [33:33<01:39,  4.25it/s]

 93%|█████████▎| 5593/6015 [33:33<01:39,  4.25it/s]

 93%|█████████▎| 5594/6015 [33:34<01:38,  4.26it/s]

 93%|█████████▎| 5595/6015 [33:34<01:38,  4.26it/s]

 93%|█████████▎| 5596/6015 [33:34<01:38,  4.26it/s]

 93%|█████████▎| 5597/6015 [33:34<01:38,  4.26it/s]

 93%|█████████▎| 5598/6015 [33:35<01:38,  4.25it/s]

 93%|█████████▎| 5599/6015 [33:35<01:37,  4.26it/s]

 93%|█████████▎| 5600/6015 [33:35<01:37,  4.25it/s]

 93%|█████████▎| 5601/6015 [33:35<01:37,  4.25it/s]

 93%|█████████▎| 5602/6015 [33:36<01:37,  4.25it/s]

 93%|█████████▎| 5603/6015 [33:36<01:36,  4.25it/s]

 93%|█████████▎| 5604/6015 [33:36<01:36,  4.26it/s]

 93%|█████████▎| 5605/6015 [33:36<01:36,  4.26it/s]

 93%|█████████▎| 5606/6015 [33:36<01:36,  4.26it/s]

 93%|█████████▎| 5607/6015 [33:37<01:35,  4.25it/s]

 93%|█████████▎| 5608/6015 [33:37<01:35,  4.26it/s]

 93%|█████████▎| 5609/6015 [33:37<01:35,  4.26it/s]

 93%|█████████▎| 5610/6015 [33:37<01:35,  4.25it/s]

 93%|█████████▎| 5611/6015 [33:38<01:35,  4.24it/s]

 93%|█████████▎| 5612/6015 [33:38<01:34,  4.25it/s]

 93%|█████████▎| 5613/6015 [33:38<01:34,  4.25it/s]

 93%|█████████▎| 5614/6015 [33:38<01:34,  4.26it/s]

 93%|█████████▎| 5615/6015 [33:39<01:34,  4.24it/s]

 93%|█████████▎| 5616/6015 [33:39<01:33,  4.25it/s]

 93%|█████████▎| 5617/6015 [33:39<01:33,  4.25it/s]

 93%|█████████▎| 5618/6015 [33:39<01:33,  4.25it/s]

 93%|█████████▎| 5619/6015 [33:40<01:33,  4.25it/s]

 93%|█████████▎| 5620/6015 [33:40<01:32,  4.25it/s]

 93%|█████████▎| 5621/6015 [33:40<01:32,  4.25it/s]

 93%|█████████▎| 5622/6015 [33:40<01:32,  4.25it/s]

 93%|█████████▎| 5623/6015 [33:40<01:32,  4.25it/s]

 93%|█████████▎| 5624/6015 [33:41<01:31,  4.26it/s]

 94%|█████████▎| 5625/6015 [33:41<01:31,  4.25it/s]

 94%|█████████▎| 5626/6015 [33:41<01:31,  4.25it/s]

 94%|█████████▎| 5627/6015 [33:41<01:31,  4.24it/s]

 94%|█████████▎| 5628/6015 [33:42<01:31,  4.23it/s]

 94%|█████████▎| 5629/6015 [33:42<01:31,  4.23it/s]

 94%|█████████▎| 5630/6015 [33:42<01:30,  4.23it/s]

 94%|█████████▎| 5631/6015 [33:42<01:30,  4.24it/s]

 94%|█████████▎| 5632/6015 [33:43<01:30,  4.23it/s]

 94%|█████████▎| 5633/6015 [33:43<01:30,  4.23it/s]

logging
logging the anndata

 94%|█████████▎| 5634/6015 [33:44<03:13,  1.96it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 94%|█████████▎| 5635/6015 [33:44<02:41,  2.35it/s]

 94%|█████████▎| 5636/6015 [33:44<02:18,  2.73it/s]

 94%|█████████▎| 5637/6015 [33:45<02:02,  3.08it/s]

 94%|█████████▎| 5638/6015 [33:45<01:51,  3.38it/s]

 94%|█████████▎| 5639/6015 [33:45<01:43,  3.62it/s]

 94%|█████████▍| 5640/6015 [33:45<01:38,  3.81it/s]

 94%|█████████▍| 5641/6015 [33:46<01:34,  3.96it/s]

 94%|█████████▍| 5642/6015 [33:46<01:31,  4.07it/s]

 94%|█████████▍| 5643/6015 [33:46<01:29,  4.16it/s]

 94%|█████████▍| 5644/6015 [33:46<01:28,  4.22it/s]

 94%|█████████▍| 5645/6015 [33:47<01:26,  4.25it/s]

 94%|█████████▍| 5646/6015 [33:47<01:26,  4.29it/s]

 94%|█████████▍| 5647/6015 [33:47<01:25,  4.31it/s]

 94%|█████████▍| 5648/6015 [33:47<01:24,  4.32it/s]

 94%|█████████▍| 5649/6015 [33:47<01:24,  4.33it/s]

 94%|█████████▍| 5650/6015 [33:48<01:24,  4.34it/s]

 94%|█████████▍| 5651/6015 [33:48<01:23,  4.35it/s]

 94%|█████████▍| 5652/6015 [33:48<01:23,  4.36it/s]

 94%|█████████▍| 5653/6015 [33:48<01:23,  4.35it/s]

 94%|█████████▍| 5654/6015 [33:49<01:22,  4.37it/s]

 94%|█████████▍| 5655/6015 [33:49<01:22,  4.36it/s]

 94%|█████████▍| 5656/6015 [33:49<01:22,  4.36it/s]

 94%|█████████▍| 5657/6015 [33:49<01:22,  4.35it/s]

 94%|█████████▍| 5658/6015 [33:50<01:22,  4.35it/s]

 94%|█████████▍| 5659/6015 [33:50<01:21,  4.35it/s]

 94%|█████████▍| 5660/6015 [33:50<01:21,  4.35it/s]

 94%|█████████▍| 5661/6015 [33:50<01:21,  4.35it/s]

 94%|█████████▍| 5662/6015 [33:50<01:20,  4.36it/s]

 94%|█████████▍| 5663/6015 [33:51<01:20,  4.36it/s]

 94%|█████████▍| 5664/6015 [33:51<01:20,  4.36it/s]

 94%|█████████▍| 5665/6015 [33:51<01:20,  4.36it/s]

 94%|█████████▍| 5666/6015 [33:51<01:20,  4.35it/s]

 94%|█████████▍| 5667/6015 [33:52<01:19,  4.35it/s]

 94%|█████████▍| 5668/6015 [33:52<01:19,  4.36it/s]

 94%|█████████▍| 5669/6015 [33:52<01:19,  4.36it/s]

 94%|█████████▍| 5670/6015 [33:52<01:19,  4.37it/s]

 94%|█████████▍| 5671/6015 [33:52<01:18,  4.37it/s]

 94%|█████████▍| 5672/6015 [33:53<01:18,  4.37it/s]

 94%|█████████▍| 5673/6015 [33:53<01:18,  4.37it/s]

 94%|█████████▍| 5674/6015 [33:53<01:18,  4.36it/s]

 94%|█████████▍| 5675/6015 [33:53<01:18,  4.35it/s]

 94%|█████████▍| 5676/6015 [33:54<01:17,  4.35it/s]

 94%|█████████▍| 5677/6015 [33:54<01:17,  4.36it/s]

 94%|█████████▍| 5678/6015 [33:54<01:17,  4.36it/s]

 94%|█████████▍| 5679/6015 [33:54<01:16,  4.37it/s]

 94%|█████████▍| 5680/6015 [33:55<01:16,  4.36it/s]

 94%|█████████▍| 5681/6015 [33:55<01:16,  4.36it/s]

 94%|█████████▍| 5682/6015 [33:55<01:16,  4.36it/s]

 94%|█████████▍| 5683/6015 [33:55<01:16,  4.36it/s]

 94%|█████████▍| 5684/6015 [33:55<01:15,  4.36it/s]

 95%|█████████▍| 5685/6015 [33:56<01:15,  4.35it/s]

 95%|█████████▍| 5686/6015 [33:56<01:15,  4.34it/s]

 95%|█████████▍| 5687/6015 [33:56<01:15,  4.34it/s]

 95%|█████████▍| 5688/6015 [33:56<01:15,  4.35it/s]

 95%|█████████▍| 5689/6015 [33:57<01:15,  4.35it/s]

 95%|█████████▍| 5690/6015 [33:57<01:14,  4.35it/s]

 95%|█████████▍| 5691/6015 [33:57<01:14,  4.35it/s]

 95%|█████████▍| 5692/6015 [33:57<01:14,  4.36it/s]

 95%|█████████▍| 5693/6015 [33:58<01:13,  4.36it/s]

 95%|█████████▍| 5694/6015 [33:58<01:13,  4.35it/s]

 95%|█████████▍| 5695/6015 [33:58<01:13,  4.36it/s]

 95%|█████████▍| 5696/6015 [33:58<01:13,  4.36it/s]

 95%|█████████▍| 5697/6015 [33:58<01:12,  4.36it/s]

 95%|█████████▍| 5698/6015 [33:59<01:12,  4.36it/s]

 95%|█████████▍| 5699/6015 [33:59<01:12,  4.35it/s]

 95%|█████████▍| 5700/6015 [33:59<01:12,  4.35it/s]

 95%|█████████▍| 5701/6015 [33:59<01:12,  4.34it/s]

 95%|█████████▍| 5702/6015 [34:00<01:12,  4.33it/s]

 95%|█████████▍| 5703/6015 [34:00<01:11,  4.35it/s]

 95%|█████████▍| 5704/6015 [34:00<01:11,  4.35it/s]

 95%|█████████▍| 5705/6015 [34:00<01:11,  4.35it/s]

 95%|█████████▍| 5706/6015 [34:01<01:10,  4.36it/s]

 95%|█████████▍| 5707/6015 [34:01<01:10,  4.36it/s]

 95%|█████████▍| 5708/6015 [34:01<01:10,  4.36it/s]

 95%|█████████▍| 5709/6015 [34:01<01:10,  4.36it/s]

 95%|█████████▍| 5710/6015 [34:01<01:10,  4.35it/s]

 95%|█████████▍| 5711/6015 [34:02<01:09,  4.37it/s]

 95%|█████████▍| 5712/6015 [34:02<01:09,  4.36it/s]

 95%|█████████▍| 5713/6015 [34:02<01:09,  4.36it/s]

 95%|█████████▍| 5714/6015 [34:02<01:09,  4.36it/s]

 95%|█████████▌| 5715/6015 [34:03<01:08,  4.35it/s]

 95%|█████████▌| 5716/6015 [34:03<01:08,  4.35it/s]

 95%|█████████▌| 5717/6015 [34:03<01:08,  4.34it/s]

 95%|█████████▌| 5718/6015 [34:03<01:08,  4.34it/s]

 95%|█████████▌| 5719/6015 [34:04<01:08,  4.35it/s]

 95%|█████████▌| 5720/6015 [34:04<01:07,  4.35it/s]

 95%|█████████▌| 5721/6015 [34:04<01:07,  4.34it/s]

 95%|█████████▌| 5722/6015 [34:04<01:07,  4.35it/s]

 95%|█████████▌| 5723/6015 [34:04<01:07,  4.35it/s]

 95%|█████████▌| 5724/6015 [34:05<01:06,  4.35it/s]

 95%|█████████▌| 5725/6015 [34:05<01:06,  4.35it/s]

 95%|█████████▌| 5726/6015 [34:05<01:06,  4.36it/s]

 95%|█████████▌| 5727/6015 [34:05<01:06,  4.36it/s]

 95%|█████████▌| 5728/6015 [34:06<01:05,  4.35it/s]

 95%|█████████▌| 5729/6015 [34:06<01:05,  4.35it/s]

 95%|█████████▌| 5730/6015 [34:06<01:05,  4.36it/s]

 95%|█████████▌| 5731/6015 [34:06<01:05,  4.35it/s]

 95%|█████████▌| 5732/6015 [34:07<01:05,  4.35it/s]

 95%|█████████▌| 5733/6015 [34:07<01:04,  4.35it/s]

 95%|█████████▌| 5734/6015 [34:07<01:04,  4.35it/s]

 95%|█████████▌| 5735/6015 [34:07<01:04,  4.35it/s]

 95%|█████████▌| 5736/6015 [34:07<01:04,  4.35it/s]

 95%|█████████▌| 5737/6015 [34:08<01:03,  4.35it/s]

 95%|█████████▌| 5738/6015 [34:08<01:03,  4.35it/s]

 95%|█████████▌| 5739/6015 [34:08<01:03,  4.35it/s]

 95%|█████████▌| 5740/6015 [34:08<01:03,  4.34it/s]

 95%|█████████▌| 5741/6015 [34:09<01:03,  4.34it/s]

 95%|█████████▌| 5742/6015 [34:09<01:02,  4.34it/s]

 95%|█████████▌| 5743/6015 [34:09<01:02,  4.35it/s]

 95%|█████████▌| 5744/6015 [34:09<01:02,  4.35it/s]

 96%|█████████▌| 5745/6015 [34:09<01:02,  4.34it/s]

 96%|█████████▌| 5746/6015 [34:10<01:01,  4.35it/s]

 96%|█████████▌| 5747/6015 [34:10<01:01,  4.35it/s]

 96%|█████████▌| 5748/6015 [34:10<01:01,  4.34it/s]

 96%|█████████▌| 5749/6015 [34:10<01:01,  4.35it/s]

 96%|█████████▌| 5750/6015 [34:11<01:00,  4.35it/s]

 96%|█████████▌| 5751/6015 [34:11<01:00,  4.35it/s]

 96%|█████████▌| 5752/6015 [34:11<01:00,  4.35it/s]

 96%|█████████▌| 5753/6015 [34:11<01:00,  4.35it/s]

 96%|█████████▌| 5754/6015 [34:12<01:00,  4.35it/s]

 96%|█████████▌| 5755/6015 [34:12<00:59,  4.35it/s]

 96%|█████████▌| 5756/6015 [34:12<00:59,  4.35it/s]

 96%|█████████▌| 5757/6015 [34:12<00:59,  4.35it/s]

 96%|█████████▌| 5758/6015 [34:12<00:59,  4.35it/s]

 96%|█████████▌| 5759/6015 [34:13<00:58,  4.35it/s]

 96%|█████████▌| 5760/6015 [34:13<00:58,  4.35it/s]

 96%|█████████▌| 5761/6015 [34:13<00:58,  4.35it/s]

 96%|█████████▌| 5762/6015 [34:13<00:58,  4.36it/s]

 96%|█████████▌| 5763/6015 [34:14<00:57,  4.35it/s]

 96%|█████████▌| 5764/6015 [34:14<00:57,  4.35it/s]

 96%|█████████▌| 5765/6015 [34:14<00:57,  4.36it/s]

 96%|█████████▌| 5766/6015 [34:14<00:57,  4.35it/s]

 96%|█████████▌| 5767/6015 [34:15<00:57,  4.35it/s]

 96%|█████████▌| 5768/6015 [34:15<00:56,  4.35it/s]

 96%|█████████▌| 5769/6015 [34:15<00:56,  4.34it/s]

 96%|█████████▌| 5770/6015 [34:15<00:56,  4.34it/s]

 96%|█████████▌| 5771/6015 [34:15<00:56,  4.33it/s]

 96%|█████████▌| 5772/6015 [34:16<00:56,  4.33it/s]

 96%|█████████▌| 5773/6015 [34:16<00:55,  4.33it/s]

 96%|█████████▌| 5774/6015 [34:16<00:55,  4.34it/s]

 96%|█████████▌| 5775/6015 [34:16<00:55,  4.34it/s]

 96%|█████████▌| 5776/6015 [34:17<00:55,  4.33it/s]

 96%|█████████▌| 5777/6015 [34:17<00:54,  4.33it/s]

 96%|█████████▌| 5778/6015 [34:17<00:54,  4.34it/s]

 96%|█████████▌| 5779/6015 [34:17<00:54,  4.33it/s]

 96%|█████████▌| 5780/6015 [34:18<00:54,  4.34it/s]

 96%|█████████▌| 5781/6015 [34:18<00:53,  4.34it/s]

 96%|█████████▌| 5782/6015 [34:18<00:53,  4.34it/s]

 96%|█████████▌| 5783/6015 [34:18<00:53,  4.34it/s]

 96%|█████████▌| 5784/6015 [34:18<00:53,  4.34it/s]

 96%|█████████▌| 5785/6015 [34:19<00:52,  4.34it/s]

 96%|█████████▌| 5786/6015 [34:19<00:52,  4.34it/s]

 96%|█████████▌| 5787/6015 [34:19<00:52,  4.34it/s]

 96%|█████████▌| 5788/6015 [34:19<00:52,  4.33it/s]

 96%|█████████▌| 5789/6015 [34:20<00:52,  4.34it/s]

 96%|█████████▋| 5790/6015 [34:20<00:51,  4.33it/s]

 96%|█████████▋| 5791/6015 [34:20<00:51,  4.33it/s]

 96%|█████████▋| 5792/6015 [34:20<00:51,  4.33it/s]

 96%|█████████▋| 5793/6015 [34:21<00:51,  4.33it/s]

 96%|█████████▋| 5794/6015 [34:21<00:51,  4.33it/s]

 96%|█████████▋| 5795/6015 [34:21<00:50,  4.34it/s]

 96%|█████████▋| 5796/6015 [34:21<00:50,  4.33it/s]

 96%|█████████▋| 5797/6015 [34:21<00:50,  4.34it/s]

 96%|█████████▋| 5798/6015 [34:22<00:50,  4.33it/s]

 96%|█████████▋| 5799/6015 [34:22<00:49,  4.34it/s]

 96%|█████████▋| 5800/6015 [34:22<00:49,  4.31it/s]

 96%|█████████▋| 5801/6015 [34:22<00:49,  4.32it/s]

 96%|█████████▋| 5802/6015 [34:23<00:49,  4.32it/s]

 96%|█████████▋| 5803/6015 [34:23<00:48,  4.33it/s]

 96%|█████████▋| 5804/6015 [34:23<00:48,  4.33it/s]

 97%|█████████▋| 5805/6015 [34:23<00:48,  4.33it/s]

 97%|█████████▋| 5806/6015 [34:24<00:48,  4.33it/s]

 97%|█████████▋| 5807/6015 [34:24<00:48,  4.30it/s]

 97%|█████████▋| 5808/6015 [34:24<00:48,  4.31it/s]

 97%|█████████▋| 5809/6015 [34:24<00:47,  4.31it/s]

 97%|█████████▋| 5810/6015 [34:24<00:47,  4.32it/s]

 97%|█████████▋| 5811/6015 [34:25<00:47,  4.32it/s]

 97%|█████████▋| 5812/6015 [34:25<00:47,  4.32it/s]

 97%|█████████▋| 5813/6015 [34:25<00:46,  4.33it/s]

 97%|█████████▋| 5814/6015 [34:25<00:46,  4.34it/s]

 97%|█████████▋| 5815/6015 [34:26<00:46,  4.34it/s]

 97%|█████████▋| 5816/6015 [34:26<00:45,  4.34it/s]

 97%|█████████▋| 5817/6015 [34:26<00:45,  4.34it/s]

 97%|█████████▋| 5818/6015 [34:26<00:45,  4.34it/s]

 97%|█████████▋| 5819/6015 [34:27<00:45,  4.33it/s]

 97%|█████████▋| 5820/6015 [34:27<00:45,  4.32it/s]

 97%|█████████▋| 5821/6015 [34:27<00:44,  4.33it/s]

 97%|█████████▋| 5822/6015 [34:27<00:44,  4.32it/s]

 97%|█████████▋| 5823/6015 [34:27<00:44,  4.32it/s]

 97%|█████████▋| 5824/6015 [34:28<00:44,  4.32it/s]

 97%|█████████▋| 5825/6015 [34:28<00:43,  4.32it/s]

 97%|█████████▋| 5826/6015 [34:28<00:44,  4.30it/s]

 97%|█████████▋| 5827/6015 [34:28<00:43,  4.30it/s]

 97%|█████████▋| 5828/6015 [34:29<00:43,  4.31it/s]

 97%|█████████▋| 5829/6015 [34:29<00:43,  4.32it/s]

 97%|█████████▋| 5830/6015 [34:29<00:42,  4.32it/s]

 97%|█████████▋| 5831/6015 [34:29<00:42,  4.31it/s]

 97%|█████████▋| 5832/6015 [34:30<00:42,  4.32it/s]

 97%|█████████▋| 5833/6015 [34:30<00:42,  4.32it/s]

 97%|█████████▋| 5834/6015 [34:30<00:42,  4.31it/s]

 97%|█████████▋| 5835/6015 [34:30<00:41,  4.31it/s]

 97%|█████████▋| 5836/6015 [34:31<00:41,  4.31it/s]

 97%|█████████▋| 5837/6015 [34:31<00:41,  4.32it/s]

 97%|█████████▋| 5838/6015 [34:31<00:40,  4.32it/s]

 97%|█████████▋| 5839/6015 [34:31<00:40,  4.31it/s]

 97%|█████████▋| 5840/6015 [34:31<00:40,  4.32it/s]

 97%|█████████▋| 5841/6015 [34:32<00:40,  4.32it/s]

 97%|█████████▋| 5842/6015 [34:32<00:40,  4.32it/s]

 97%|█████████▋| 5843/6015 [34:32<00:39,  4.33it/s]

 97%|█████████▋| 5844/6015 [34:32<00:39,  4.32it/s]

 97%|█████████▋| 5845/6015 [34:33<00:39,  4.32it/s]

 97%|█████████▋| 5846/6015 [34:33<00:39,  4.32it/s]

 97%|█████████▋| 5847/6015 [34:33<00:38,  4.32it/s]

 97%|█████████▋| 5848/6015 [34:33<00:38,  4.32it/s]

 97%|█████████▋| 5849/6015 [34:34<00:38,  4.32it/s]

 97%|█████████▋| 5850/6015 [34:34<00:38,  4.31it/s]

 97%|█████████▋| 5851/6015 [34:34<00:37,  4.32it/s]

 97%|█████████▋| 5852/6015 [34:34<00:37,  4.32it/s]

 97%|█████████▋| 5853/6015 [34:34<00:37,  4.33it/s]

 97%|█████████▋| 5854/6015 [34:35<00:37,  4.33it/s]

 97%|█████████▋| 5855/6015 [34:35<00:36,  4.33it/s]

 97%|█████████▋| 5856/6015 [34:35<00:36,  4.33it/s]

 97%|█████████▋| 5857/6015 [34:35<00:36,  4.33it/s]

 97%|█████████▋| 5858/6015 [34:36<00:36,  4.33it/s]

 97%|█████████▋| 5859/6015 [34:36<00:35,  4.33it/s]

 97%|█████████▋| 5860/6015 [34:36<00:35,  4.34it/s]

 97%|█████████▋| 5861/6015 [34:36<00:35,  4.33it/s]

 97%|█████████▋| 5862/6015 [34:37<00:35,  4.33it/s]

 97%|█████████▋| 5863/6015 [34:37<00:35,  4.32it/s]

 97%|█████████▋| 5864/6015 [34:37<00:34,  4.32it/s]

 98%|█████████▊| 5865/6015 [34:37<00:34,  4.33it/s]

 98%|█████████▊| 5866/6015 [34:37<00:34,  4.33it/s]

 98%|█████████▊| 5867/6015 [34:38<00:34,  4.33it/s]

 98%|█████████▊| 5868/6015 [34:38<00:34,  4.32it/s]

 98%|█████████▊| 5869/6015 [34:38<00:33,  4.32it/s]

 98%|█████████▊| 5870/6015 [34:38<00:33,  4.33it/s]

 98%|█████████▊| 5871/6015 [34:39<00:33,  4.33it/s]

 98%|█████████▊| 5872/6015 [34:39<00:33,  4.33it/s]

 98%|█████████▊| 5873/6015 [34:39<00:32,  4.33it/s]

 98%|█████████▊| 5874/6015 [34:39<00:32,  4.33it/s]

 98%|█████████▊| 5875/6015 [34:40<00:32,  4.27it/s]

 98%|█████████▊| 5876/6015 [34:40<00:32,  4.29it/s]

 98%|█████████▊| 5877/6015 [34:40<00:32,  4.30it/s]

 98%|█████████▊| 5878/6015 [34:40<00:31,  4.31it/s]

 98%|█████████▊| 5879/6015 [34:40<00:31,  4.31it/s]

 98%|█████████▊| 5880/6015 [34:41<00:31,  4.31it/s]

 98%|█████████▊| 5881/6015 [34:41<00:30,  4.33it/s]

 98%|█████████▊| 5882/6015 [34:41<00:30,  4.33it/s]

 98%|█████████▊| 5883/6015 [34:41<00:30,  4.32it/s]

 98%|█████████▊| 5884/6015 [34:42<00:30,  4.32it/s]

 98%|█████████▊| 5885/6015 [34:42<00:30,  4.32it/s]

 98%|█████████▊| 5886/6015 [34:42<00:29,  4.33it/s]

 98%|█████████▊| 5887/6015 [34:42<00:29,  4.32it/s]

 98%|█████████▊| 5888/6015 [34:43<00:29,  4.32it/s]

 98%|█████████▊| 5889/6015 [34:43<00:29,  4.32it/s]

 98%|█████████▊| 5890/6015 [34:43<00:28,  4.32it/s]

 98%|█████████▊| 5891/6015 [34:43<00:28,  4.32it/s]

 98%|█████████▊| 5892/6015 [34:43<00:28,  4.33it/s]

 98%|█████████▊| 5893/6015 [34:44<00:28,  4.33it/s]

 98%|█████████▊| 5894/6015 [34:44<00:27,  4.34it/s]

 98%|█████████▊| 5895/6015 [34:44<00:27,  4.35it/s]

 98%|█████████▊| 5896/6015 [34:44<00:27,  4.35it/s]

 98%|█████████▊| 5897/6015 [34:45<00:27,  4.35it/s]

 98%|█████████▊| 5898/6015 [34:45<00:26,  4.34it/s]

 98%|█████████▊| 5899/6015 [34:45<00:26,  4.34it/s]

 98%|█████████▊| 5900/6015 [34:45<00:26,  4.33it/s]

 98%|█████████▊| 5901/6015 [34:46<00:26,  4.33it/s]

 98%|█████████▊| 5902/6015 [34:46<00:26,  4.33it/s]

 98%|█████████▊| 5903/6015 [34:46<00:25,  4.33it/s]

 98%|█████████▊| 5904/6015 [34:46<00:25,  4.32it/s]

 98%|█████████▊| 5905/6015 [34:46<00:25,  4.33it/s]

 98%|█████████▊| 5906/6015 [34:47<00:25,  4.32it/s]

 98%|█████████▊| 5907/6015 [34:47<00:24,  4.33it/s]

 98%|█████████▊| 5908/6015 [34:47<00:24,  4.32it/s]

 98%|█████████▊| 5909/6015 [34:47<00:24,  4.29it/s]

 98%|█████████▊| 5910/6015 [34:48<00:24,  4.31it/s]

 98%|█████████▊| 5911/6015 [34:48<00:24,  4.31it/s]

 98%|█████████▊| 5912/6015 [34:48<00:23,  4.30it/s]

 98%|█████████▊| 5913/6015 [34:48<00:23,  4.30it/s]

 98%|█████████▊| 5914/6015 [34:49<00:23,  4.30it/s]

 98%|█████████▊| 5915/6015 [34:49<00:23,  4.30it/s]

 98%|█████████▊| 5916/6015 [34:49<00:22,  4.31it/s]

 98%|█████████▊| 5917/6015 [34:49<00:22,  4.32it/s]

 98%|█████████▊| 5918/6015 [34:49<00:22,  4.32it/s]

 98%|█████████▊| 5919/6015 [34:50<00:22,  4.32it/s]

 98%|█████████▊| 5920/6015 [34:50<00:21,  4.32it/s]

 98%|█████████▊| 5921/6015 [34:50<00:21,  4.31it/s]

 98%|█████████▊| 5922/6015 [34:50<00:21,  4.31it/s]

 98%|█████████▊| 5923/6015 [34:51<00:21,  4.32it/s]

 98%|█████████▊| 5924/6015 [34:51<00:21,  4.32it/s]

 99%|█████████▊| 5925/6015 [34:51<00:20,  4.32it/s]

 99%|█████████▊| 5926/6015 [34:51<00:20,  4.32it/s]

 99%|█████████▊| 5927/6015 [34:52<00:20,  4.32it/s]

 99%|█████████▊| 5928/6015 [34:52<00:20,  4.33it/s]

 99%|█████████▊| 5929/6015 [34:52<00:19,  4.32it/s]

 99%|█████████▊| 5930/6015 [34:52<00:19,  4.31it/s]

 99%|█████████▊| 5931/6015 [34:52<00:19,  4.32it/s]

 99%|█████████▊| 5932/6015 [34:53<00:19,  4.32it/s]

 99%|█████████▊| 5933/6015 [34:53<00:18,  4.33it/s]

 99%|█████████▊| 5934/6015 [34:53<00:18,  4.33it/s]

 99%|█████████▊| 5935/6015 [34:53<00:18,  4.32it/s]

 99%|█████████▊| 5936/6015 [34:54<00:18,  4.32it/s]

 99%|█████████▊| 5937/6015 [34:54<00:18,  4.32it/s]

 99%|█████████▊| 5938/6015 [34:54<00:17,  4.32it/s]

 99%|█████████▊| 5939/6015 [34:54<00:17,  4.33it/s]

 99%|█████████▉| 5940/6015 [34:55<00:17,  4.33it/s]

 99%|█████████▉| 5941/6015 [34:55<00:17,  4.33it/s]

 99%|█████████▉| 5942/6015 [34:55<00:16,  4.34it/s]

 99%|█████████▉| 5943/6015 [34:55<00:16,  4.34it/s]

 99%|█████████▉| 5944/6015 [34:55<00:16,  4.34it/s]

 99%|█████████▉| 5945/6015 [34:56<00:16,  4.33it/s]

 99%|█████████▉| 5946/6015 [34:56<00:15,  4.33it/s]

 99%|█████████▉| 5947/6015 [34:56<00:15,  4.33it/s]

 99%|█████████▉| 5948/6015 [34:56<00:15,  4.34it/s]

 99%|█████████▉| 5949/6015 [34:57<00:15,  4.32it/s]

 99%|█████████▉| 5950/6015 [34:57<00:15,  4.33it/s]

 99%|█████████▉| 5951/6015 [34:57<00:14,  4.33it/s]

 99%|█████████▉| 5952/6015 [34:57<00:14,  4.34it/s]

 99%|█████████▉| 5953/6015 [34:58<00:14,  4.33it/s]

 99%|█████████▉| 5954/6015 [34:58<00:14,  4.33it/s]

 99%|█████████▉| 5955/6015 [34:58<00:13,  4.34it/s]

 99%|█████████▉| 5956/6015 [34:58<00:13,  4.34it/s]

 99%|█████████▉| 5957/6015 [34:58<00:13,  4.33it/s]

 99%|█████████▉| 5958/6015 [34:59<00:13,  4.32it/s]

 99%|█████████▉| 5959/6015 [34:59<00:12,  4.32it/s]

 99%|█████████▉| 5960/6015 [34:59<00:12,  4.32it/s]

 99%|█████████▉| 5961/6015 [34:59<00:12,  4.33it/s]

 99%|█████████▉| 5962/6015 [35:00<00:12,  4.31it/s]

 99%|█████████▉| 5963/6015 [35:00<00:12,  4.33it/s]

 99%|█████████▉| 5964/6015 [35:00<00:11,  4.32it/s]

 99%|█████████▉| 5965/6015 [35:00<00:11,  4.33it/s]

 99%|█████████▉| 5966/6015 [35:01<00:11,  4.33it/s]

 99%|█████████▉| 5967/6015 [35:01<00:11,  4.33it/s]

 99%|█████████▉| 5968/6015 [35:01<00:10,  4.33it/s]

 99%|█████████▉| 5969/6015 [35:01<00:10,  4.33it/s]

 99%|█████████▉| 5970/6015 [35:01<00:10,  4.33it/s]

 99%|█████████▉| 5971/6015 [35:02<00:10,  4.33it/s]

 99%|█████████▉| 5972/6015 [35:02<00:09,  4.32it/s]

 99%|█████████▉| 5973/6015 [35:02<00:09,  4.31it/s]

 99%|█████████▉| 5974/6015 [35:02<00:09,  4.32it/s]

 99%|█████████▉| 5975/6015 [35:03<00:09,  4.31it/s]

 99%|█████████▉| 5976/6015 [35:03<00:09,  4.32it/s]

 99%|█████████▉| 5977/6015 [35:03<00:08,  4.32it/s]

 99%|█████████▉| 5978/6015 [35:03<00:08,  4.29it/s]

 99%|█████████▉| 5979/6015 [35:04<00:08,  4.30it/s]

 99%|█████████▉| 5980/6015 [35:04<00:08,  4.31it/s]

 99%|█████████▉| 5981/6015 [35:04<00:07,  4.32it/s]

 99%|█████████▉| 5982/6015 [35:04<00:07,  4.31it/s]

 99%|█████████▉| 5983/6015 [35:05<00:07,  4.31it/s]

 99%|█████████▉| 5984/6015 [35:05<00:07,  4.33it/s]

100%|█████████▉| 5985/6015 [35:05<00:06,  4.33it/s]

100%|█████████▉| 5986/6015 [35:05<00:06,  4.32it/s]

100%|█████████▉| 5987/6015 [35:05<00:06,  4.32it/s]

100%|█████████▉| 5988/6015 [35:06<00:06,  4.31it/s]

100%|█████████▉| 5989/6015 [35:06<00:06,  4.32it/s]

100%|█████████▉| 5990/6015 [35:06<00:05,  4.31it/s]

100%|█████████▉| 5991/6015 [35:06<00:05,  4.31it/s]

100%|█████████▉| 5992/6015 [35:07<00:05,  4.32it/s]

100%|█████████▉| 5993/6015 [35:07<00:05,  4.32it/s]

100%|█████████▉| 5994/6015 [35:07<00:04,  4.31it/s]

100%|█████████▉| 5995/6015 [35:07<00:04,  4.31it/s]

100%|█████████▉| 5996/6015 [35:08<00:04,  4.30it/s]

100%|█████████▉| 5997/6015 [35:08<00:04,  4.31it/s]

100%|█████████▉| 5998/6015 [35:08<00:03,  4.31it/s]

100%|█████████▉| 5999/6015 [35:08<00:03,  4.31it/s]

100%|█████████▉| 6000/6015 [35:08<00:03,  4.31it/s]

100%|█████████▉| 6001/6015 [35:09<00:03,  4.31it/s]

100%|█████████▉| 6002/6015 [35:09<00:03,  4.32it/s]

100%|█████████▉| 6003/6015 [35:09<00:02,  4.32it/s]

100%|█████████▉| 6004/6015 [35:09<00:02,  4.32it/s]

100%|█████████▉| 6005/6015 [35:10<00:02,  4.33it/s]

100%|█████████▉| 6006/6015 [35:10<00:02,  4.33it/s]

100%|█████████▉| 6007/6015 [35:10<00:01,  4.32it/s]

100%|█████████▉| 6008/6015 [35:10<00:01,  4.31it/s]

100%|█████████▉| 6009/6015 [35:11<00:01,  4.31it/s]

100%|█████████▉| 6010/6015 [35:11<00:01,  4.32it/s]

100%|█████████▉| 6011/6015 [35:11<00:00,  4.32it/s]

100%|█████████▉| 6012/6015 [35:11<00:00,  4.33it/s]

100%|█████████▉| 6013/6015 [35:11<00:00,  4.33it/s]

100%|█████████▉| 6014/6015 [35:12<00:00,  4.33it/s]

100%|██████████| 6015/6015 [35:12<00:00,  5.12it/s]

100%|██████████| 6015/6015 [35:13<00:00,  2.85it/s]

logging the anndata

AnnData object with n_obs × n_vars = 24349 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

too few cells to embed into a umap
too few cells to compute a clustering

{'cellxgene_census/dkd_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4937716969573208, 'macro': 0.38015219981782045, 'micro': 0.4937716969573208, 'weighted': 0.44125553939089207}}, 'cellxgene_census/dkd_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4630541871921182, 'macro': 0.39612779635380635, 'micro': 0.4630541871921182, 'weighted': 0.43238258813181274}}, 'cellxgene_census/gtex_v9_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.662801373334736, 'macro': 0.45113362926393386, 'micro': 0.662801373334736, 'weighted': 0.6076783134412977}}, 'cellxgene_census/gtex_v9_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4894855752519986, 'macro': 0.5275646372211268, 'micro': 0.4894855752519986, 'weighted': 0.45377925621844867}}, 'cellxgene_census/hypomap_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.8986192115347146, 'macro': 0.5346630203398964, 'micro': 0.8986192115347146, 'weighted': 0.8782631897011843}}, 'cellxgene_census/hypomap_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9525547445255474, 'macro': 0.6734592457544935, 'micro': 0.9525547445255474, 'weighted': 0.9472890166071732}}}

doing  cellxgene_census/mouse_pancreas_atlas

/lustre/fswork/projects/rech/xeg/uat95fg/scdataloader/scdataloader/utils.py:427: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  organismdf = pd.concat(organismdf)

predict epoch start

  0%|          | 0/4716 [00:00<?, ?it/s]

  0%|          | 1/4716 [00:03<4:49:40,  3.69s/it]

  0%|          | 2/4716 [00:03<2:09:50,  1.65s/it]

  0%|          | 3/4716 [00:04<1:18:49,  1.00s/it]

  0%|          | 4/4716 [00:04<54:43,  1.43it/s]

  0%|          | 5/4716 [00:04<41:27,  1.89it/s]

  0%|          | 6/4716 [00:04<33:24,  2.35it/s]

  0%|          | 7/4716 [00:05<28:18,  2.77it/s]

  0%|          | 8/4716 [00:05<24:55,  3.15it/s]

  0%|          | 9/4716 [00:05<22:46,  3.45it/s]

  0%|          | 10/4716 [00:05<21:14,  3.69it/s]

  0%|          | 11/4716 [00:05<20:09,  3.89it/s]

  0%|          | 12/4716 [00:06<19:23,  4.04it/s]

  0%|          | 13/4716 [00:06<18:55,  4.14it/s]

  0%|          | 14/4716 [00:06<18:36,  4.21it/s]

  0%|          | 15/4716 [00:06<18:17,  4.28it/s]

  0%|          | 16/4716 [00:07<18:08,  4.32it/s]

  0%|          | 17/4716 [00:07<18:01,  4.34it/s]

  0%|          | 18/4716 [00:07<17:56,  4.36it/s]

  0%|          | 19/4716 [00:07<17:54,  4.37it/s]

  0%|          | 20/4716 [00:08<17:49,  4.39it/s]

  0%|          | 21/4716 [00:08<17:48,  4.39it/s]

  0%|          | 22/4716 [00:08<17:48,  4.39it/s]

  0%|          | 23/4716 [00:08<17:56,  4.36it/s]

  1%|          | 24/4716 [00:08<17:53,  4.37it/s]

  1%|          | 25/4716 [00:09<17:50,  4.38it/s]

  1%|          | 26/4716 [00:09<17:47,  4.39it/s]

  1%|          | 27/4716 [00:09<17:46,  4.40it/s]

  1%|          | 28/4716 [00:09<17:45,  4.40it/s]

  1%|          | 29/4716 [00:10<17:47,  4.39it/s]

  1%|          | 30/4716 [00:10<17:47,  4.39it/s]

  1%|          | 31/4716 [00:10<17:46,  4.39it/s]

  1%|          | 32/4716 [00:10<17:46,  4.39it/s]

  1%|          | 33/4716 [00:10<17:49,  4.38it/s]

  1%|          | 34/4716 [00:11<17:45,  4.39it/s]

  1%|          | 35/4716 [00:11<17:45,  4.40it/s]

  1%|          | 36/4716 [00:11<17:44,  4.40it/s]

  1%|          | 37/4716 [00:11<17:43,  4.40it/s]

  1%|          | 38/4716 [00:12<17:43,  4.40it/s]

  1%|          | 39/4716 [00:12<17:44,  4.40it/s]

  1%|          | 40/4716 [00:12<17:42,  4.40it/s]

  1%|          | 41/4716 [00:12<17:42,  4.40it/s]

  1%|          | 42/4716 [00:13<17:42,  4.40it/s]

  1%|          | 43/4716 [00:13<17:42,  4.40it/s]

  1%|          | 44/4716 [00:13<17:43,  4.39it/s]

  1%|          | 45/4716 [00:13<17:43,  4.39it/s]

  1%|          | 46/4716 [00:13<17:45,  4.38it/s]

  1%|          | 47/4716 [00:14<17:47,  4.38it/s]

  1%|          | 48/4716 [00:14<17:44,  4.38it/s]

  1%|          | 49/4716 [00:14<17:45,  4.38it/s]

  1%|          | 50/4716 [00:14<17:45,  4.38it/s]

  1%|          | 51/4716 [00:15<17:44,  4.38it/s]

  1%|          | 52/4716 [00:15<17:45,  4.38it/s]

  1%|          | 53/4716 [00:15<17:44,  4.38it/s]

  1%|          | 54/4716 [00:15<17:41,  4.39it/s]

  1%|          | 55/4716 [00:15<17:41,  4.39it/s]

  1%|          | 56/4716 [00:16<17:42,  4.39it/s]

  1%|          | 57/4716 [00:16<17:43,  4.38it/s]

  1%|          | 58/4716 [00:16<17:43,  4.38it/s]

  1%|▏         | 59/4716 [00:16<17:43,  4.38it/s]

  1%|▏         | 60/4716 [00:17<17:41,  4.38it/s]

  1%|▏         | 61/4716 [00:17<17:44,  4.37it/s]

  1%|▏         | 62/4716 [00:17<17:43,  4.38it/s]

  1%|▏         | 63/4716 [00:17<17:40,  4.39it/s]

  1%|▏         | 64/4716 [00:18<17:40,  4.39it/s]

  1%|▏         | 65/4716 [00:18<17:38,  4.39it/s]

  1%|▏         | 66/4716 [00:18<17:37,  4.40it/s]

  1%|▏         | 67/4716 [00:18<17:38,  4.39it/s]

  1%|▏         | 68/4716 [00:18<17:37,  4.40it/s]

  1%|▏         | 69/4716 [00:19<17:38,  4.39it/s]

  1%|▏         | 70/4716 [00:19<17:37,  4.39it/s]

  2%|▏         | 71/4716 [00:19<17:40,  4.38it/s]

  2%|▏         | 72/4716 [00:19<17:38,  4.39it/s]

  2%|▏         | 73/4716 [00:20<17:36,  4.39it/s]

  2%|▏         | 74/4716 [00:20<17:35,  4.40it/s]

  2%|▏         | 75/4716 [00:20<17:37,  4.39it/s]

  2%|▏         | 76/4716 [00:20<17:36,  4.39it/s]

  2%|▏         | 77/4716 [00:20<17:35,  4.39it/s]

  2%|▏         | 78/4716 [00:21<17:38,  4.38it/s]

  2%|▏         | 79/4716 [00:21<17:38,  4.38it/s]

  2%|▏         | 80/4716 [00:21<17:38,  4.38it/s]

  2%|▏         | 81/4716 [00:21<17:39,  4.37it/s]

  2%|▏         | 82/4716 [00:22<17:38,  4.38it/s]

  2%|▏         | 83/4716 [00:22<17:38,  4.38it/s]

  2%|▏         | 84/4716 [00:22<17:39,  4.37it/s]

  2%|▏         | 85/4716 [00:22<17:37,  4.38it/s]

  2%|▏         | 86/4716 [00:23<17:38,  4.37it/s]

  2%|▏         | 87/4716 [00:23<17:37,  4.38it/s]

  2%|▏         | 88/4716 [00:23<17:37,  4.38it/s]

  2%|▏         | 89/4716 [00:23<17:37,  4.37it/s]

  2%|▏         | 90/4716 [00:23<18:14,  4.23it/s]

  2%|▏         | 91/4716 [00:24<18:01,  4.28it/s]

  2%|▏         | 92/4716 [00:24<17:56,  4.30it/s]

  2%|▏         | 93/4716 [00:24<17:50,  4.32it/s]

  2%|▏         | 94/4716 [00:24<17:46,  4.33it/s]

  2%|▏         | 95/4716 [00:25<17:45,  4.34it/s]

  2%|▏         | 96/4716 [00:25<17:40,  4.36it/s]

  2%|▏         | 97/4716 [00:25<17:39,  4.36it/s]

  2%|▏         | 98/4716 [00:25<17:39,  4.36it/s]

  2%|▏         | 99/4716 [00:26<17:36,  4.37it/s]

  2%|▏         | 100/4716 [00:26<17:35,  4.37it/s]

  2%|▏         | 101/4716 [00:26<17:35,  4.37it/s]

  2%|▏         | 102/4716 [00:26<17:33,  4.38it/s]

  2%|▏         | 103/4716 [00:26<17:33,  4.38it/s]

  2%|▏         | 104/4716 [00:27<17:34,  4.37it/s]

  2%|▏         | 105/4716 [00:27<17:33,  4.38it/s]

  2%|▏         | 106/4716 [00:27<17:34,  4.37it/s]

  2%|▏         | 107/4716 [00:27<17:36,  4.36it/s]

  2%|▏         | 108/4716 [00:28<17:35,  4.37it/s]

  2%|▏         | 109/4716 [00:28<17:35,  4.36it/s]

  2%|▏         | 110/4716 [00:28<17:34,  4.37it/s]

  2%|▏         | 111/4716 [00:28<17:33,  4.37it/s]

  2%|▏         | 112/4716 [00:29<17:32,  4.37it/s]

  2%|▏         | 113/4716 [00:29<17:32,  4.37it/s]

  2%|▏         | 114/4716 [00:29<17:33,  4.37it/s]

  2%|▏         | 115/4716 [00:29<17:31,  4.38it/s]

  2%|▏         | 116/4716 [00:29<17:30,  4.38it/s]

  2%|▏         | 117/4716 [00:30<17:33,  4.37it/s]

  3%|▎         | 118/4716 [00:30<17:34,  4.36it/s]

  3%|▎         | 119/4716 [00:30<17:34,  4.36it/s]

  3%|▎         | 120/4716 [00:30<17:34,  4.36it/s]

  3%|▎         | 121/4716 [00:31<17:35,  4.35it/s]

  3%|▎         | 122/4716 [00:31<17:32,  4.37it/s]

  3%|▎         | 123/4716 [00:31<17:32,  4.36it/s]

  3%|▎         | 124/4716 [00:31<17:32,  4.36it/s]

  3%|▎         | 125/4716 [00:32<17:32,  4.36it/s]

  3%|▎         | 126/4716 [00:32<17:32,  4.36it/s]

  3%|▎         | 127/4716 [00:32<17:32,  4.36it/s]

  3%|▎         | 128/4716 [00:32<17:32,  4.36it/s]

  3%|▎         | 129/4716 [00:32<17:31,  4.36it/s]

  3%|▎         | 130/4716 [00:33<17:31,  4.36it/s]

  3%|▎         | 131/4716 [00:33<17:30,  4.36it/s]

  3%|▎         | 132/4716 [00:33<17:31,  4.36it/s]

  3%|▎         | 133/4716 [00:33<17:30,  4.36it/s]

  3%|▎         | 134/4716 [00:34<17:31,  4.36it/s]

  3%|▎         | 135/4716 [00:34<17:30,  4.36it/s]

  3%|▎         | 136/4716 [00:34<17:29,  4.37it/s]

  3%|▎         | 137/4716 [00:34<17:29,  4.36it/s]

  3%|▎         | 138/4716 [00:34<17:30,  4.36it/s]

  3%|▎         | 139/4716 [00:35<17:29,  4.36it/s]

  3%|▎         | 140/4716 [00:35<17:30,  4.36it/s]

  3%|▎         | 141/4716 [00:35<17:29,  4.36it/s]

  3%|▎         | 142/4716 [00:35<17:29,  4.36it/s]

  3%|▎         | 143/4716 [00:36<17:28,  4.36it/s]

  3%|▎         | 144/4716 [00:36<17:26,  4.37it/s]

  3%|▎         | 145/4716 [00:36<17:28,  4.36it/s]

  3%|▎         | 146/4716 [00:36<17:28,  4.36it/s]

  3%|▎         | 147/4716 [00:37<17:26,  4.36it/s]

  3%|▎         | 148/4716 [00:37<17:27,  4.36it/s]

  3%|▎         | 149/4716 [00:37<17:28,  4.35it/s]

  3%|▎         | 150/4716 [00:37<17:27,  4.36it/s]

  3%|▎         | 151/4716 [00:37<17:28,  4.35it/s]

  3%|▎         | 152/4716 [00:38<17:27,  4.36it/s]

  3%|▎         | 153/4716 [00:38<17:27,  4.36it/s]

  3%|▎         | 154/4716 [00:38<17:26,  4.36it/s]

  3%|▎         | 155/4716 [00:38<17:25,  4.36it/s]

  3%|▎         | 156/4716 [00:39<17:24,  4.37it/s]

  3%|▎         | 157/4716 [00:39<17:24,  4.36it/s]

  3%|▎         | 158/4716 [00:39<17:23,  4.37it/s]

  3%|▎         | 159/4716 [00:39<17:22,  4.37it/s]

  3%|▎         | 160/4716 [00:40<17:22,  4.37it/s]

  3%|▎         | 161/4716 [00:40<17:22,  4.37it/s]

  3%|▎         | 162/4716 [00:40<17:24,  4.36it/s]

  3%|▎         | 163/4716 [00:40<17:23,  4.36it/s]

  3%|▎         | 164/4716 [00:40<17:26,  4.35it/s]

  3%|▎         | 165/4716 [00:41<17:24,  4.36it/s]

  4%|▎         | 166/4716 [00:41<17:22,  4.36it/s]

  4%|▎         | 167/4716 [00:41<17:24,  4.35it/s]

  4%|▎         | 168/4716 [00:41<17:28,  4.34it/s]

  4%|▎         | 169/4716 [00:42<17:29,  4.33it/s]

  4%|▎         | 170/4716 [00:42<17:30,  4.33it/s]

  4%|▎         | 171/4716 [00:42<17:26,  4.34it/s]

  4%|▎         | 172/4716 [00:42<17:24,  4.35it/s]

  4%|▎         | 173/4716 [00:43<17:24,  4.35it/s]

  4%|▎         | 174/4716 [00:43<17:24,  4.35it/s]

  4%|▎         | 175/4716 [00:43<17:24,  4.35it/s]

  4%|▎         | 176/4716 [00:43<17:23,  4.35it/s]

  4%|▍         | 177/4716 [00:43<17:20,  4.36it/s]

  4%|▍         | 178/4716 [00:44<17:20,  4.36it/s]

  4%|▍         | 179/4716 [00:44<17:21,  4.36it/s]

  4%|▍         | 180/4716 [00:44<17:21,  4.36it/s]

  4%|▍         | 181/4716 [00:44<17:20,  4.36it/s]

  4%|▍         | 182/4716 [00:45<17:19,  4.36it/s]

  4%|▍         | 183/4716 [00:45<17:21,  4.35it/s]

  4%|▍         | 184/4716 [00:45<17:21,  4.35it/s]

  4%|▍         | 185/4716 [00:45<17:19,  4.36it/s]

  4%|▍         | 186/4716 [00:46<17:21,  4.35it/s]

  4%|▍         | 187/4716 [00:46<17:22,  4.34it/s]

  4%|▍         | 188/4716 [00:46<17:23,  4.34it/s]

  4%|▍         | 189/4716 [00:46<17:25,  4.33it/s]

  4%|▍         | 190/4716 [00:46<17:22,  4.34it/s]

  4%|▍         | 191/4716 [00:47<17:22,  4.34it/s]

  4%|▍         | 192/4716 [00:47<17:23,  4.34it/s]

  4%|▍         | 193/4716 [00:47<17:23,  4.34it/s]

  4%|▍         | 194/4716 [00:47<17:23,  4.33it/s]

  4%|▍         | 195/4716 [00:48<17:21,  4.34it/s]

  4%|▍         | 196/4716 [00:48<17:21,  4.34it/s]

  4%|▍         | 197/4716 [00:48<17:21,  4.34it/s]

  4%|▍         | 198/4716 [00:48<17:18,  4.35it/s]

  4%|▍         | 199/4716 [00:48<17:18,  4.35it/s]

  4%|▍         | 200/4716 [00:49<17:21,  4.33it/s]

  4%|▍         | 201/4716 [00:49<17:18,  4.35it/s]

  4%|▍         | 202/4716 [00:49<17:17,  4.35it/s]

  4%|▍         | 203/4716 [00:49<17:20,  4.34it/s]

  4%|▍         | 204/4716 [00:50<17:19,  4.34it/s]

  4%|▍         | 205/4716 [00:50<17:18,  4.34it/s]

  4%|▍         | 206/4716 [00:50<17:17,  4.35it/s]

  4%|▍         | 207/4716 [00:50<17:18,  4.34it/s]

  4%|▍         | 208/4716 [00:51<17:19,  4.34it/s]

  4%|▍         | 209/4716 [00:51<17:17,  4.34it/s]

  4%|▍         | 210/4716 [00:51<17:17,  4.34it/s]

  4%|▍         | 211/4716 [00:51<17:16,  4.35it/s]

  4%|▍         | 212/4716 [00:51<17:16,  4.35it/s]

  5%|▍         | 213/4716 [00:52<17:16,  4.34it/s]

  5%|▍         | 214/4716 [00:52<17:17,  4.34it/s]

  5%|▍         | 215/4716 [00:52<17:17,  4.34it/s]

  5%|▍         | 216/4716 [00:52<17:18,  4.33it/s]

  5%|▍         | 217/4716 [00:53<17:15,  4.34it/s]

  5%|▍         | 218/4716 [00:53<17:17,  4.34it/s]

  5%|▍         | 219/4716 [00:53<17:16,  4.34it/s]

  5%|▍         | 220/4716 [00:53<17:16,  4.34it/s]

  5%|▍         | 221/4716 [00:54<17:16,  4.34it/s]

  5%|▍         | 222/4716 [00:54<17:15,  4.34it/s]

  5%|▍         | 223/4716 [00:54<17:14,  4.34it/s]

  5%|▍         | 224/4716 [00:54<17:14,  4.34it/s]

  5%|▍         | 225/4716 [00:54<17:12,  4.35it/s]

  5%|▍         | 226/4716 [00:55<17:12,  4.35it/s]

  5%|▍         | 227/4716 [00:55<17:14,  4.34it/s]

  5%|▍         | 228/4716 [00:55<17:12,  4.35it/s]

  5%|▍         | 229/4716 [00:55<17:11,  4.35it/s]

  5%|▍         | 230/4716 [00:56<17:10,  4.35it/s]

  5%|▍         | 231/4716 [00:56<17:11,  4.35it/s]

  5%|▍         | 232/4716 [00:56<17:12,  4.34it/s]

  5%|▍         | 233/4716 [00:56<17:10,  4.35it/s]

  5%|▍         | 234/4716 [00:57<17:13,  4.34it/s]

  5%|▍         | 235/4716 [00:57<17:11,  4.34it/s]

  5%|▌         | 236/4716 [00:57<17:10,  4.35it/s]

  5%|▌         | 237/4716 [00:57<17:11,  4.34it/s]

  5%|▌         | 238/4716 [00:57<17:14,  4.33it/s]

  5%|▌         | 239/4716 [00:58<17:12,  4.34it/s]

  5%|▌         | 240/4716 [00:58<17:12,  4.33it/s]

  5%|▌         | 241/4716 [00:58<17:10,  4.34it/s]

  5%|▌         | 242/4716 [00:58<17:10,  4.34it/s]

  5%|▌         | 243/4716 [00:59<17:10,  4.34it/s]

  5%|▌         | 244/4716 [00:59<17:09,  4.34it/s]

  5%|▌         | 245/4716 [00:59<17:09,  4.34it/s]

  5%|▌         | 246/4716 [00:59<17:09,  4.34it/s]

  5%|▌         | 247/4716 [01:00<17:10,  4.34it/s]

  5%|▌         | 248/4716 [01:00<17:11,  4.33it/s]

  5%|▌         | 249/4716 [01:00<17:08,  4.34it/s]

  5%|▌         | 250/4716 [01:00<17:07,  4.35it/s]

  5%|▌         | 251/4716 [01:00<17:07,  4.35it/s]

  5%|▌         | 252/4716 [01:01<17:06,  4.35it/s]

  5%|▌         | 253/4716 [01:01<17:08,  4.34it/s]

  5%|▌         | 254/4716 [01:01<17:06,  4.35it/s]

  5%|▌         | 255/4716 [01:01<17:06,  4.35it/s]

  5%|▌         | 256/4716 [01:02<17:07,  4.34it/s]

  5%|▌         | 257/4716 [01:02<17:05,  4.35it/s]

  5%|▌         | 258/4716 [01:02<17:06,  4.34it/s]

  5%|▌         | 259/4716 [01:02<17:09,  4.33it/s]

  6%|▌         | 260/4716 [01:03<17:06,  4.34it/s]

  6%|▌         | 261/4716 [01:03<17:03,  4.35it/s]

  6%|▌         | 262/4716 [01:03<17:02,  4.36it/s]

  6%|▌         | 263/4716 [01:03<16:59,  4.37it/s]

  6%|▌         | 264/4716 [01:03<16:58,  4.37it/s]

  6%|▌         | 265/4716 [01:04<17:00,  4.36it/s]

  6%|▌         | 266/4716 [01:04<17:02,  4.35it/s]

  6%|▌         | 267/4716 [01:04<17:03,  4.35it/s]

  6%|▌         | 268/4716 [01:04<17:01,  4.35it/s]

  6%|▌         | 269/4716 [01:05<17:03,  4.35it/s]

  6%|▌         | 270/4716 [01:05<17:03,  4.35it/s]

  6%|▌         | 271/4716 [01:05<17:03,  4.34it/s]

  6%|▌         | 272/4716 [01:05<17:05,  4.33it/s]

  6%|▌         | 273/4716 [01:06<17:05,  4.33it/s]

  6%|▌         | 274/4716 [01:06<17:04,  4.34it/s]

  6%|▌         | 275/4716 [01:06<17:05,  4.33it/s]

  6%|▌         | 276/4716 [01:06<17:03,  4.34it/s]

  6%|▌         | 277/4716 [01:06<17:02,  4.34it/s]

  6%|▌         | 278/4716 [01:07<17:04,  4.33it/s]

  6%|▌         | 279/4716 [01:07<17:02,  4.34it/s]

  6%|▌         | 280/4716 [01:07<17:02,  4.34it/s]

  6%|▌         | 281/4716 [01:07<17:02,  4.34it/s]

  6%|▌         | 282/4716 [01:08<17:02,  4.34it/s]

  6%|▌         | 283/4716 [01:08<17:01,  4.34it/s]

  6%|▌         | 284/4716 [01:08<17:01,  4.34it/s]

  6%|▌         | 285/4716 [01:08<17:00,  4.34it/s]

  6%|▌         | 286/4716 [01:09<17:02,  4.33it/s]

  6%|▌         | 287/4716 [01:09<17:01,  4.34it/s]

  6%|▌         | 288/4716 [01:09<17:01,  4.33it/s]

  6%|▌         | 289/4716 [01:09<17:01,  4.33it/s]

  6%|▌         | 290/4716 [01:09<17:02,  4.33it/s]

  6%|▌         | 291/4716 [01:10<17:01,  4.33it/s]

  6%|▌         | 292/4716 [01:10<16:59,  4.34it/s]

  6%|▌         | 293/4716 [01:10<16:57,  4.35it/s]

  6%|▌         | 294/4716 [01:10<16:59,  4.34it/s]

  6%|▋         | 295/4716 [01:11<16:57,  4.34it/s]

  6%|▋         | 296/4716 [01:11<16:58,  4.34it/s]

  6%|▋         | 297/4716 [01:11<16:58,  4.34it/s]

  6%|▋         | 298/4716 [01:11<16:59,  4.33it/s]

  6%|▋         | 299/4716 [01:12<17:00,  4.33it/s]

  6%|▋         | 300/4716 [01:12<16:59,  4.33it/s]

  6%|▋         | 301/4716 [01:12<16:59,  4.33it/s]

  6%|▋         | 302/4716 [01:12<16:58,  4.33it/s]

  6%|▋         | 303/4716 [01:12<16:56,  4.34it/s]

  6%|▋         | 304/4716 [01:13<16:56,  4.34it/s]

  6%|▋         | 305/4716 [01:13<16:56,  4.34it/s]

  6%|▋         | 306/4716 [01:13<16:55,  4.34it/s]

  7%|▋         | 307/4716 [01:13<16:54,  4.34it/s]

  7%|▋         | 308/4716 [01:14<16:52,  4.35it/s]

  7%|▋         | 309/4716 [01:14<16:52,  4.35it/s]

  7%|▋         | 310/4716 [01:14<16:52,  4.35it/s]

  7%|▋         | 311/4716 [01:14<16:50,  4.36it/s]

  7%|▋         | 312/4716 [01:15<16:50,  4.36it/s]

  7%|▋         | 313/4716 [01:15<16:50,  4.36it/s]

  7%|▋         | 314/4716 [01:15<16:50,  4.35it/s]

  7%|▋         | 315/4716 [01:15<16:51,  4.35it/s]

  7%|▋         | 316/4716 [01:15<16:49,  4.36it/s]

  7%|▋         | 317/4716 [01:16<16:50,  4.35it/s]

  7%|▋         | 318/4716 [01:16<16:51,  4.35it/s]

  7%|▋         | 319/4716 [01:16<16:50,  4.35it/s]

  7%|▋         | 320/4716 [01:16<16:48,  4.36it/s]

  7%|▋         | 321/4716 [01:17<16:49,  4.36it/s]

  7%|▋         | 322/4716 [01:17<16:47,  4.36it/s]

  7%|▋         | 323/4716 [01:17<16:50,  4.35it/s]

  7%|▋         | 324/4716 [01:17<16:52,  4.34it/s]

  7%|▋         | 325/4716 [01:18<16:52,  4.34it/s]

  7%|▋         | 326/4716 [01:18<16:52,  4.34it/s]

  7%|▋         | 327/4716 [01:18<16:49,  4.35it/s]

  7%|▋         | 328/4716 [01:18<16:51,  4.34it/s]

  7%|▋         | 329/4716 [01:18<16:51,  4.34it/s]

  7%|▋         | 330/4716 [01:19<16:50,  4.34it/s]

  7%|▋         | 331/4716 [01:19<16:50,  4.34it/s]

  7%|▋         | 332/4716 [01:19<16:50,  4.34it/s]

  7%|▋         | 333/4716 [01:19<16:51,  4.33it/s]

  7%|▋         | 334/4716 [01:20<16:55,  4.31it/s]

  7%|▋         | 335/4716 [01:20<16:53,  4.32it/s]

  7%|▋         | 336/4716 [01:20<16:54,  4.32it/s]

  7%|▋         | 337/4716 [01:20<16:52,  4.32it/s]

  7%|▋         | 338/4716 [01:21<16:52,  4.33it/s]

  7%|▋         | 339/4716 [01:21<16:51,  4.33it/s]

  7%|▋         | 340/4716 [01:21<16:49,  4.33it/s]

  7%|▋         | 341/4716 [01:21<16:48,  4.34it/s]

  7%|▋         | 342/4716 [01:21<16:49,  4.33it/s]

  7%|▋         | 343/4716 [01:22<16:47,  4.34it/s]

  7%|▋         | 344/4716 [01:22<16:48,  4.34it/s]

  7%|▋         | 345/4716 [01:22<16:50,  4.33it/s]

  7%|▋         | 346/4716 [01:22<16:48,  4.33it/s]

  7%|▋         | 347/4716 [01:23<16:48,  4.33it/s]

  7%|▋         | 348/4716 [01:23<16:47,  4.34it/s]

  7%|▋         | 349/4716 [01:23<16:45,  4.34it/s]

  7%|▋         | 350/4716 [01:23<16:45,  4.34it/s]

  7%|▋         | 351/4716 [01:24<16:44,  4.34it/s]

  7%|▋         | 352/4716 [01:24<16:47,  4.33it/s]

  7%|▋         | 353/4716 [01:24<16:50,  4.32it/s]

  8%|▊         | 354/4716 [01:24<16:48,  4.32it/s]

  8%|▊         | 355/4716 [01:24<16:49,  4.32it/s]

  8%|▊         | 356/4716 [01:25<16:50,  4.31it/s]

  8%|▊         | 357/4716 [01:25<16:50,  4.31it/s]

  8%|▊         | 358/4716 [01:25<16:49,  4.32it/s]

  8%|▊         | 359/4716 [01:25<16:47,  4.33it/s]

  8%|▊         | 360/4716 [01:26<16:46,  4.33it/s]

  8%|▊         | 361/4716 [01:26<16:47,  4.32it/s]

  8%|▊         | 362/4716 [01:26<16:45,  4.33it/s]

  8%|▊         | 363/4716 [01:26<16:44,  4.33it/s]

  8%|▊         | 364/4716 [01:27<16:44,  4.33it/s]

  8%|▊         | 365/4716 [01:27<16:45,  4.33it/s]

  8%|▊         | 366/4716 [01:27<16:48,  4.31it/s]

  8%|▊         | 367/4716 [01:27<16:45,  4.32it/s]

  8%|▊         | 368/4716 [01:27<16:46,  4.32it/s]

  8%|▊         | 369/4716 [01:28<16:45,  4.32it/s]

  8%|▊         | 370/4716 [01:28<16:42,  4.34it/s]

  8%|▊         | 371/4716 [01:28<16:42,  4.33it/s]

  8%|▊         | 372/4716 [01:28<16:48,  4.31it/s]

  8%|▊         | 373/4716 [01:29<16:48,  4.31it/s]

  8%|▊         | 374/4716 [01:29<16:48,  4.31it/s]

  8%|▊         | 375/4716 [01:29<16:47,  4.31it/s]

  8%|▊         | 376/4716 [01:29<16:45,  4.32it/s]

  8%|▊         | 377/4716 [01:30<16:46,  4.31it/s]

  8%|▊         | 378/4716 [01:30<16:43,  4.32it/s]

  8%|▊         | 379/4716 [01:30<16:44,  4.32it/s]

  8%|▊         | 380/4716 [01:30<16:42,  4.32it/s]

  8%|▊         | 381/4716 [01:30<16:40,  4.33it/s]

  8%|▊         | 382/4716 [01:31<16:40,  4.33it/s]

  8%|▊         | 383/4716 [01:31<16:44,  4.32it/s]

  8%|▊         | 384/4716 [01:31<16:42,  4.32it/s]

  8%|▊         | 385/4716 [01:31<16:44,  4.31it/s]

  8%|▊         | 386/4716 [01:32<16:41,  4.32it/s]

  8%|▊         | 387/4716 [01:32<16:42,  4.32it/s]

  8%|▊         | 388/4716 [01:32<16:41,  4.32it/s]

  8%|▊         | 389/4716 [01:32<16:41,  4.32it/s]

  8%|▊         | 390/4716 [01:33<16:41,  4.32it/s]

  8%|▊         | 391/4716 [01:33<16:39,  4.33it/s]

  8%|▊         | 392/4716 [01:33<16:37,  4.34it/s]

  8%|▊         | 393/4716 [01:33<16:38,  4.33it/s]

  8%|▊         | 394/4716 [01:33<16:39,  4.32it/s]

  8%|▊         | 395/4716 [01:34<16:51,  4.27it/s]

  8%|▊         | 396/4716 [01:34<16:49,  4.28it/s]

  8%|▊         | 397/4716 [01:34<16:45,  4.29it/s]

  8%|▊         | 398/4716 [01:34<16:44,  4.30it/s]

  8%|▊         | 399/4716 [01:35<16:42,  4.30it/s]

  8%|▊         | 400/4716 [01:35<16:41,  4.31it/s]

  9%|▊         | 401/4716 [01:35<16:43,  4.30it/s]

  9%|▊         | 402/4716 [01:35<16:42,  4.30it/s]

  9%|▊         | 403/4716 [01:36<16:41,  4.31it/s]

  9%|▊         | 404/4716 [01:36<16:42,  4.30it/s]

  9%|▊         | 405/4716 [01:36<16:41,  4.30it/s]

  9%|▊         | 406/4716 [01:36<16:39,  4.31it/s]

  9%|▊         | 407/4716 [01:36<16:41,  4.30it/s]

  9%|▊         | 408/4716 [01:37<16:39,  4.31it/s]

  9%|▊         | 409/4716 [01:37<16:39,  4.31it/s]

  9%|▊         | 410/4716 [01:37<16:39,  4.31it/s]

  9%|▊         | 411/4716 [01:37<16:38,  4.31it/s]

  9%|▊         | 412/4716 [01:38<16:35,  4.32it/s]

  9%|▉         | 413/4716 [01:38<16:36,  4.32it/s]

  9%|▉         | 414/4716 [01:38<16:35,  4.32it/s]

  9%|▉         | 415/4716 [01:38<16:36,  4.31it/s]

  9%|▉         | 416/4716 [01:39<16:36,  4.32it/s]

  9%|▉         | 417/4716 [01:39<16:37,  4.31it/s]

  9%|▉         | 418/4716 [01:39<16:36,  4.31it/s]

  9%|▉         | 419/4716 [01:39<16:36,  4.31it/s]

  9%|▉         | 420/4716 [01:39<16:37,  4.31it/s]

  9%|▉         | 421/4716 [01:40<16:39,  4.30it/s]

  9%|▉         | 422/4716 [01:40<16:37,  4.31it/s]

  9%|▉         | 423/4716 [01:40<16:37,  4.31it/s]

  9%|▉         | 424/4716 [01:40<16:36,  4.31it/s]

  9%|▉         | 425/4716 [01:41<16:37,  4.30it/s]

  9%|▉         | 426/4716 [01:41<16:37,  4.30it/s]

  9%|▉         | 427/4716 [01:41<16:34,  4.31it/s]

  9%|▉         | 428/4716 [01:41<16:34,  4.31it/s]

  9%|▉         | 429/4716 [01:42<16:33,  4.31it/s]

  9%|▉         | 430/4716 [01:42<16:34,  4.31it/s]

  9%|▉         | 431/4716 [01:42<16:38,  4.29it/s]

  9%|▉         | 432/4716 [01:42<16:35,  4.31it/s]

  9%|▉         | 433/4716 [01:43<16:32,  4.32it/s]

  9%|▉         | 434/4716 [01:43<16:31,  4.32it/s]

  9%|▉         | 435/4716 [01:43<16:31,  4.32it/s]

  9%|▉         | 436/4716 [01:43<16:30,  4.32it/s]

  9%|▉         | 437/4716 [01:43<16:29,  4.32it/s]

  9%|▉         | 438/4716 [01:44<16:29,  4.32it/s]

  9%|▉         | 439/4716 [01:44<16:31,  4.32it/s]

  9%|▉         | 440/4716 [01:44<16:30,  4.32it/s]

  9%|▉         | 441/4716 [01:44<16:33,  4.30it/s]

  9%|▉         | 442/4716 [01:45<16:33,  4.30it/s]

  9%|▉         | 443/4716 [01:45<16:30,  4.31it/s]

  9%|▉         | 444/4716 [01:45<16:29,  4.32it/s]

  9%|▉         | 445/4716 [01:45<16:30,  4.31it/s]

  9%|▉         | 446/4716 [01:46<16:32,  4.30it/s]

  9%|▉         | 447/4716 [01:46<16:35,  4.29it/s]

  9%|▉         | 448/4716 [01:46<16:32,  4.30it/s]

 10%|▉         | 449/4716 [01:46<16:33,  4.30it/s]

 10%|▉         | 450/4716 [01:46<16:31,  4.30it/s]

 10%|▉         | 451/4716 [01:47<16:29,  4.31it/s]

 10%|▉         | 452/4716 [01:47<16:29,  4.31it/s]

 10%|▉         | 453/4716 [01:47<16:28,  4.31it/s]

 10%|▉         | 454/4716 [01:47<16:27,  4.31it/s]

 10%|▉         | 455/4716 [01:48<16:29,  4.30it/s]

 10%|▉         | 456/4716 [01:48<16:27,  4.31it/s]

 10%|▉         | 457/4716 [01:48<16:27,  4.31it/s]

 10%|▉         | 458/4716 [01:48<16:26,  4.32it/s]

 10%|▉         | 459/4716 [01:49<16:26,  4.32it/s]

 10%|▉         | 460/4716 [01:49<16:28,  4.31it/s]

 10%|▉         | 461/4716 [01:49<16:28,  4.31it/s]

 10%|▉         | 462/4716 [01:49<16:26,  4.31it/s]

 10%|▉         | 463/4716 [01:49<16:24,  4.32it/s]

 10%|▉         | 464/4716 [01:50<16:21,  4.33it/s]

 10%|▉         | 465/4716 [01:50<16:22,  4.33it/s]

 10%|▉         | 466/4716 [01:50<16:22,  4.33it/s]

 10%|▉         | 467/4716 [01:50<16:24,  4.32it/s]

 10%|▉         | 468/4716 [01:51<16:27,  4.30it/s]

 10%|▉         | 469/4716 [01:51<16:26,  4.31it/s]

 10%|▉         | 470/4716 [01:51<16:27,  4.30it/s]

 10%|▉         | 471/4716 [01:51<16:27,  4.30it/s]

 10%|█         | 472/4716 [01:52<16:28,  4.29it/s]

 10%|█         | 473/4716 [01:52<16:29,  4.29it/s]

 10%|█         | 474/4716 [01:52<16:28,  4.29it/s]

 10%|█         | 475/4716 [01:52<16:27,  4.29it/s]

 10%|█         | 476/4716 [01:52<16:26,  4.30it/s]

 10%|█         | 477/4716 [01:53<16:28,  4.29it/s]

 10%|█         | 478/4716 [01:53<16:28,  4.29it/s]

 10%|█         | 479/4716 [01:53<16:27,  4.29it/s]

 10%|█         | 480/4716 [01:53<16:28,  4.28it/s]

 10%|█         | 481/4716 [01:54<16:28,  4.29it/s]

 10%|█         | 482/4716 [01:54<16:27,  4.29it/s]

 10%|█         | 483/4716 [01:54<16:26,  4.29it/s]

 10%|█         | 484/4716 [01:54<16:25,  4.29it/s]

 10%|█         | 485/4716 [01:55<16:26,  4.29it/s]

 10%|█         | 486/4716 [01:55<16:26,  4.29it/s]

 10%|█         | 487/4716 [01:55<16:25,  4.29it/s]

 10%|█         | 488/4716 [01:55<16:24,  4.29it/s]

 10%|█         | 489/4716 [01:56<16:23,  4.30it/s]

 10%|█         | 490/4716 [01:56<16:21,  4.31it/s]

 10%|█         | 491/4716 [01:56<16:21,  4.30it/s]

 10%|█         | 492/4716 [01:56<16:21,  4.30it/s]

 10%|█         | 493/4716 [01:56<16:22,  4.30it/s]

 10%|█         | 494/4716 [01:57<16:25,  4.28it/s]

 10%|█         | 495/4716 [01:57<16:25,  4.28it/s]

 11%|█         | 496/4716 [01:57<16:24,  4.29it/s]

 11%|█         | 497/4716 [01:57<16:22,  4.29it/s]

 11%|█         | 498/4716 [01:58<16:22,  4.29it/s]

 11%|█         | 499/4716 [01:58<16:23,  4.29it/s]

 11%|█         | 500/4716 [01:58<16:20,  4.30it/s]

 11%|█         | 501/4716 [01:58<16:21,  4.29it/s]

 11%|█         | 502/4716 [01:59<16:22,  4.29it/s]

 11%|█         | 503/4716 [01:59<16:21,  4.29it/s]

 11%|█         | 504/4716 [01:59<16:22,  4.29it/s]

 11%|█         | 505/4716 [01:59<16:19,  4.30it/s]

 11%|█         | 506/4716 [01:59<16:20,  4.29it/s]

 11%|█         | 507/4716 [02:00<16:21,  4.29it/s]

 11%|█         | 508/4716 [02:00<16:27,  4.26it/s]

 11%|█         | 509/4716 [02:00<16:25,  4.27it/s]

 11%|█         | 510/4716 [02:00<16:22,  4.28it/s]

 11%|█         | 511/4716 [02:01<16:22,  4.28it/s]

 11%|█         | 512/4716 [02:01<16:22,  4.28it/s]

 11%|█         | 513/4716 [02:01<16:19,  4.29it/s]

 11%|█         | 514/4716 [02:01<16:17,  4.30it/s]

 11%|█         | 515/4716 [02:02<16:15,  4.31it/s]

 11%|█         | 516/4716 [02:02<16:14,  4.31it/s]

 11%|█         | 517/4716 [02:02<16:17,  4.30it/s]

 11%|█         | 518/4716 [02:02<16:17,  4.29it/s]

 11%|█         | 519/4716 [02:03<16:17,  4.29it/s]

 11%|█         | 520/4716 [02:03<16:17,  4.29it/s]

 11%|█         | 521/4716 [02:03<16:20,  4.28it/s]

 11%|█         | 522/4716 [02:03<16:24,  4.26it/s]

 11%|█         | 523/4716 [02:03<16:22,  4.27it/s]

 11%|█         | 524/4716 [02:04<16:24,  4.26it/s]

 11%|█         | 525/4716 [02:04<16:22,  4.27it/s]

 11%|█         | 526/4716 [02:04<16:20,  4.27it/s]

 11%|█         | 527/4716 [02:04<16:23,  4.26it/s]

 11%|█         | 528/4716 [02:05<16:20,  4.27it/s]

 11%|█         | 529/4716 [02:05<16:21,  4.26it/s]

 11%|█         | 530/4716 [02:05<16:24,  4.25it/s]

 11%|█▏        | 531/4716 [02:05<16:23,  4.26it/s]

 11%|█▏        | 532/4716 [02:06<16:24,  4.25it/s]

 11%|█▏        | 533/4716 [02:06<16:20,  4.27it/s]

 11%|█▏        | 534/4716 [02:06<16:21,  4.26it/s]

 11%|█▏        | 535/4716 [02:06<16:20,  4.26it/s]

 11%|█▏        | 536/4716 [02:07<16:21,  4.26it/s]

 11%|█▏        | 537/4716 [02:07<16:19,  4.26it/s]

 11%|█▏        | 538/4716 [02:07<16:17,  4.28it/s]

 11%|█▏        | 539/4716 [02:07<16:21,  4.26it/s]

 11%|█▏        | 540/4716 [02:07<16:20,  4.26it/s]

 11%|█▏        | 541/4716 [02:08<16:19,  4.26it/s]

 11%|█▏        | 542/4716 [02:08<16:18,  4.26it/s]

 12%|█▏        | 543/4716 [02:08<16:19,  4.26it/s]

 12%|█▏        | 544/4716 [02:08<16:17,  4.27it/s]

 12%|█▏        | 545/4716 [02:09<16:21,  4.25it/s]

 12%|█▏        | 546/4716 [02:09<16:21,  4.25it/s]

 12%|█▏        | 547/4716 [02:09<16:21,  4.25it/s]

 12%|█▏        | 548/4716 [02:09<16:18,  4.26it/s]

 12%|█▏        | 549/4716 [02:10<16:19,  4.25it/s]

 12%|█▏        | 550/4716 [02:10<16:21,  4.24it/s]

 12%|█▏        | 551/4716 [02:10<16:18,  4.26it/s]

 12%|█▏        | 552/4716 [02:10<16:16,  4.27it/s]

 12%|█▏        | 553/4716 [02:11<16:15,  4.27it/s]

 12%|█▏        | 554/4716 [02:11<16:16,  4.26it/s]

 12%|█▏        | 555/4716 [02:11<16:19,  4.25it/s]

 12%|█▏        | 556/4716 [02:11<16:18,  4.25it/s]

 12%|█▏        | 557/4716 [02:11<16:17,  4.25it/s]

 12%|█▏        | 558/4716 [02:12<16:13,  4.27it/s]

 12%|█▏        | 559/4716 [02:12<16:13,  4.27it/s]

 12%|█▏        | 560/4716 [02:12<16:17,  4.25it/s]

 12%|█▏        | 561/4716 [02:12<16:16,  4.25it/s]

 12%|█▏        | 562/4716 [02:13<16:16,  4.26it/s]

 12%|█▏        | 563/4716 [02:13<16:14,  4.26it/s]

 12%|█▏        | 564/4716 [02:13<16:13,  4.26it/s]

 12%|█▏        | 565/4716 [02:13<16:18,  4.24it/s]

 12%|█▏        | 566/4716 [02:14<16:16,  4.25it/s]

 12%|█▏        | 567/4716 [02:14<16:15,  4.25it/s]

 12%|█▏        | 568/4716 [02:14<16:15,  4.25it/s]

 12%|█▏        | 569/4716 [02:14<16:16,  4.25it/s]

 12%|█▏        | 570/4716 [02:15<16:15,  4.25it/s]

 12%|█▏        | 571/4716 [02:15<16:16,  4.25it/s]

 12%|█▏        | 572/4716 [02:15<16:13,  4.26it/s]

 12%|█▏        | 573/4716 [02:15<16:12,  4.26it/s]

 12%|█▏        | 574/4716 [02:15<16:14,  4.25it/s]

 12%|█▏        | 575/4716 [02:16<16:13,  4.26it/s]

 12%|█▏        | 576/4716 [02:16<16:11,  4.26it/s]

 12%|█▏        | 577/4716 [02:16<16:10,  4.26it/s]

 12%|█▏        | 578/4716 [02:16<16:10,  4.26it/s]

 12%|█▏        | 579/4716 [02:17<16:10,  4.26it/s]

 12%|█▏        | 580/4716 [02:17<16:14,  4.24it/s]

 12%|█▏        | 581/4716 [02:17<16:14,  4.24it/s]

 12%|█▏        | 582/4716 [02:17<16:13,  4.25it/s]

 12%|█▏        | 583/4716 [02:18<16:09,  4.26it/s]

 12%|█▏        | 584/4716 [02:18<16:09,  4.26it/s]

 12%|█▏        | 585/4716 [02:18<16:09,  4.26it/s]

 12%|█▏        | 586/4716 [02:18<16:08,  4.26it/s]

 12%|█▏        | 587/4716 [02:18<16:08,  4.26it/s]

 12%|█▏        | 588/4716 [02:19<16:09,  4.26it/s]

 12%|█▏        | 589/4716 [02:19<16:11,  4.25it/s]

 13%|█▎        | 590/4716 [02:19<16:11,  4.24it/s]

 13%|█▎        | 591/4716 [02:19<16:11,  4.25it/s]

 13%|█▎        | 592/4716 [02:20<16:13,  4.24it/s]

 13%|█▎        | 593/4716 [02:20<16:10,  4.25it/s]

 13%|█▎        | 594/4716 [02:20<16:09,  4.25it/s]

 13%|█▎        | 595/4716 [02:20<16:09,  4.25it/s]

 13%|█▎        | 596/4716 [02:21<16:08,  4.26it/s]

 13%|█▎        | 597/4716 [02:21<16:07,  4.26it/s]

 13%|█▎        | 598/4716 [02:21<16:04,  4.27it/s]

 13%|█▎        | 599/4716 [02:21<16:05,  4.27it/s]

 13%|█▎        | 600/4716 [02:22<16:04,  4.27it/s]

 13%|█▎        | 601/4716 [02:22<16:04,  4.27it/s]

 13%|█▎        | 602/4716 [02:22<16:06,  4.25it/s]

 13%|█▎        | 603/4716 [02:22<16:06,  4.25it/s]

 13%|█▎        | 604/4716 [02:22<16:05,  4.26it/s]

 13%|█▎        | 605/4716 [02:23<16:06,  4.25it/s]

 13%|█▎        | 606/4716 [02:23<16:08,  4.24it/s]

 13%|█▎        | 607/4716 [02:23<16:08,  4.24it/s]

 13%|█▎        | 608/4716 [02:23<16:06,  4.25it/s]

 13%|█▎        | 609/4716 [02:24<16:06,  4.25it/s]

 13%|█▎        | 610/4716 [02:24<16:05,  4.25it/s]

 13%|█▎        | 611/4716 [02:24<16:07,  4.24it/s]

 13%|█▎        | 612/4716 [02:24<16:08,  4.24it/s]

 13%|█▎        | 613/4716 [02:25<16:07,  4.24it/s]

 13%|█▎        | 614/4716 [02:25<16:06,  4.25it/s]

 13%|█▎        | 615/4716 [02:25<16:04,  4.25it/s]

 13%|█▎        | 616/4716 [02:25<16:05,  4.25it/s]

 13%|█▎        | 617/4716 [02:26<16:05,  4.24it/s]

 13%|█▎        | 618/4716 [02:26<16:05,  4.25it/s]

 13%|█▎        | 619/4716 [02:26<16:04,  4.25it/s]

 13%|█▎        | 620/4716 [02:26<16:03,  4.25it/s]

 13%|█▎        | 621/4716 [02:26<16:02,  4.25it/s]

 13%|█▎        | 622/4716 [02:27<16:01,  4.26it/s]

 13%|█▎        | 623/4716 [02:27<16:01,  4.26it/s]

 13%|█▎        | 624/4716 [02:27<16:02,  4.25it/s]

 13%|█▎        | 625/4716 [02:27<16:00,  4.26it/s]

logging
logging the anndata

 13%|█▎        | 626/4716 [02:29<36:26,  1.87it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 13%|█▎        | 627/4716 [02:29<30:09,  2.26it/s]

 13%|█▎        | 628/4716 [02:29<25:43,  2.65it/s]

 13%|█▎        | 629/4716 [02:29<22:41,  3.00it/s]

 13%|█▎        | 630/4716 [02:30<20:33,  3.31it/s]

 13%|█▎        | 631/4716 [02:30<19:02,  3.58it/s]

 13%|█▎        | 632/4716 [02:30<17:59,  3.78it/s]

 13%|█▎        | 633/4716 [02:30<17:15,  3.94it/s]

 13%|█▎        | 634/4716 [02:30<16:50,  4.04it/s]

 13%|█▎        | 635/4716 [02:31<16:26,  4.14it/s]

 13%|█▎        | 636/4716 [02:31<16:12,  4.19it/s]

 14%|█▎        | 637/4716 [02:31<16:00,  4.24it/s]

 14%|█▎        | 638/4716 [02:31<15:52,  4.28it/s]

 14%|█▎        | 639/4716 [02:32<15:46,  4.31it/s]

 14%|█▎        | 640/4716 [02:32<15:42,  4.33it/s]

 14%|█▎        | 641/4716 [02:32<15:39,  4.34it/s]

 14%|█▎        | 642/4716 [02:32<15:41,  4.33it/s]

 14%|█▎        | 643/4716 [02:33<15:39,  4.34it/s]

 14%|█▎        | 644/4716 [02:33<15:41,  4.33it/s]

 14%|█▎        | 645/4716 [02:33<15:38,  4.34it/s]

 14%|█▎        | 646/4716 [02:33<15:38,  4.34it/s]

 14%|█▎        | 647/4716 [02:33<15:36,  4.34it/s]

 14%|█▎        | 648/4716 [02:34<15:37,  4.34it/s]

 14%|█▍        | 649/4716 [02:34<15:37,  4.34it/s]

 14%|█▍        | 650/4716 [02:34<15:35,  4.35it/s]

 14%|█▍        | 651/4716 [02:34<15:33,  4.35it/s]

 14%|█▍        | 652/4716 [02:35<15:34,  4.35it/s]

 14%|█▍        | 653/4716 [02:35<15:33,  4.35it/s]

 14%|█▍        | 654/4716 [02:35<15:31,  4.36it/s]

 14%|█▍        | 655/4716 [02:35<15:33,  4.35it/s]

 14%|█▍        | 656/4716 [02:36<15:31,  4.36it/s]

 14%|█▍        | 657/4716 [02:36<15:31,  4.36it/s]

 14%|█▍        | 658/4716 [02:36<15:30,  4.36it/s]

 14%|█▍        | 659/4716 [02:36<15:31,  4.36it/s]

 14%|█▍        | 660/4716 [02:36<15:30,  4.36it/s]

 14%|█▍        | 661/4716 [02:37<15:28,  4.37it/s]

 14%|█▍        | 662/4716 [02:37<15:30,  4.36it/s]

 14%|█▍        | 663/4716 [02:37<15:29,  4.36it/s]

 14%|█▍        | 664/4716 [02:37<15:27,  4.37it/s]

 14%|█▍        | 665/4716 [02:38<15:29,  4.36it/s]

 14%|█▍        | 666/4716 [02:38<15:27,  4.37it/s]

 14%|█▍        | 667/4716 [02:38<15:27,  4.37it/s]

 14%|█▍        | 668/4716 [02:38<15:30,  4.35it/s]

 14%|█▍        | 669/4716 [02:39<15:30,  4.35it/s]

 14%|█▍        | 670/4716 [02:39<15:29,  4.35it/s]

 14%|█▍        | 671/4716 [02:39<15:31,  4.34it/s]

 14%|█▍        | 672/4716 [02:39<15:30,  4.34it/s]

 14%|█▍        | 673/4716 [02:39<15:31,  4.34it/s]

 14%|█▍        | 674/4716 [02:40<15:31,  4.34it/s]

 14%|█▍        | 675/4716 [02:40<15:29,  4.35it/s]

 14%|█▍        | 676/4716 [02:40<15:28,  4.35it/s]

 14%|█▍        | 677/4716 [02:40<15:28,  4.35it/s]

 14%|█▍        | 678/4716 [02:41<15:26,  4.36it/s]

 14%|█▍        | 679/4716 [02:41<15:26,  4.36it/s]

 14%|█▍        | 680/4716 [02:41<15:26,  4.36it/s]

 14%|█▍        | 681/4716 [02:41<15:25,  4.36it/s]

 14%|█▍        | 682/4716 [02:42<15:27,  4.35it/s]

 14%|█▍        | 683/4716 [02:42<15:26,  4.35it/s]

 15%|█▍        | 684/4716 [02:42<15:26,  4.35it/s]

 15%|█▍        | 685/4716 [02:42<15:26,  4.35it/s]

 15%|█▍        | 686/4716 [02:42<15:29,  4.34it/s]

 15%|█▍        | 687/4716 [02:43<15:28,  4.34it/s]

 15%|█▍        | 688/4716 [02:43<15:27,  4.34it/s]

 15%|█▍        | 689/4716 [02:43<15:25,  4.35it/s]

 15%|█▍        | 690/4716 [02:43<15:24,  4.35it/s]

 15%|█▍        | 691/4716 [02:44<15:25,  4.35it/s]

 15%|█▍        | 692/4716 [02:44<15:25,  4.35it/s]

 15%|█▍        | 693/4716 [02:44<15:25,  4.35it/s]

 15%|█▍        | 694/4716 [02:44<15:26,  4.34it/s]

 15%|█▍        | 695/4716 [02:45<15:24,  4.35it/s]

 15%|█▍        | 696/4716 [02:45<15:23,  4.35it/s]

 15%|█▍        | 697/4716 [02:45<15:22,  4.35it/s]

 15%|█▍        | 698/4716 [02:45<15:21,  4.36it/s]

 15%|█▍        | 699/4716 [02:45<15:20,  4.36it/s]

 15%|█▍        | 700/4716 [02:46<15:21,  4.36it/s]

 15%|█▍        | 701/4716 [02:46<15:21,  4.36it/s]

 15%|█▍        | 702/4716 [02:46<15:20,  4.36it/s]

 15%|█▍        | 703/4716 [02:46<15:24,  4.34it/s]

 15%|█▍        | 704/4716 [02:47<15:23,  4.34it/s]

 15%|█▍        | 705/4716 [02:47<15:22,  4.35it/s]

 15%|█▍        | 706/4716 [02:47<15:21,  4.35it/s]

 15%|█▍        | 707/4716 [02:47<15:20,  4.35it/s]

 15%|█▌        | 708/4716 [02:47<15:20,  4.36it/s]

 15%|█▌        | 709/4716 [02:48<15:18,  4.36it/s]

 15%|█▌        | 710/4716 [02:48<15:19,  4.36it/s]

 15%|█▌        | 711/4716 [02:48<15:19,  4.36it/s]

 15%|█▌        | 712/4716 [02:48<15:18,  4.36it/s]

 15%|█▌        | 713/4716 [02:49<15:18,  4.36it/s]

 15%|█▌        | 714/4716 [02:49<15:17,  4.36it/s]

 15%|█▌        | 715/4716 [02:49<15:17,  4.36it/s]

 15%|█▌        | 716/4716 [02:49<15:17,  4.36it/s]

 15%|█▌        | 717/4716 [02:50<15:15,  4.37it/s]

 15%|█▌        | 718/4716 [02:50<15:15,  4.37it/s]

 15%|█▌        | 719/4716 [02:50<15:17,  4.36it/s]

 15%|█▌        | 720/4716 [02:50<15:17,  4.35it/s]

 15%|█▌        | 721/4716 [02:50<15:16,  4.36it/s]

 15%|█▌        | 722/4716 [02:51<15:24,  4.32it/s]

 15%|█▌        | 723/4716 [02:51<15:22,  4.33it/s]

 15%|█▌        | 724/4716 [02:51<15:20,  4.34it/s]

 15%|█▌        | 725/4716 [02:51<15:18,  4.35it/s]

 15%|█▌        | 726/4716 [02:52<15:18,  4.34it/s]

 15%|█▌        | 727/4716 [02:52<15:17,  4.35it/s]

 15%|█▌        | 728/4716 [02:52<15:15,  4.36it/s]

 15%|█▌        | 729/4716 [02:52<15:16,  4.35it/s]

 15%|█▌        | 730/4716 [02:53<15:16,  4.35it/s]

 16%|█▌        | 731/4716 [02:53<15:16,  4.35it/s]

 16%|█▌        | 732/4716 [02:53<15:19,  4.33it/s]

 16%|█▌        | 733/4716 [02:53<15:17,  4.34it/s]

 16%|█▌        | 734/4716 [02:53<15:15,  4.35it/s]

 16%|█▌        | 735/4716 [02:54<15:15,  4.35it/s]

 16%|█▌        | 736/4716 [02:54<15:13,  4.36it/s]

 16%|█▌        | 737/4716 [02:54<15:13,  4.35it/s]

 16%|█▌        | 738/4716 [02:54<15:12,  4.36it/s]

 16%|█▌        | 739/4716 [02:55<15:15,  4.35it/s]

 16%|█▌        | 740/4716 [02:55<15:15,  4.34it/s]

 16%|█▌        | 741/4716 [02:55<15:14,  4.35it/s]

 16%|█▌        | 742/4716 [02:55<15:13,  4.35it/s]

 16%|█▌        | 743/4716 [02:56<15:12,  4.35it/s]

 16%|█▌        | 744/4716 [02:56<15:12,  4.35it/s]

 16%|█▌        | 745/4716 [02:56<15:13,  4.35it/s]

 16%|█▌        | 746/4716 [02:56<15:14,  4.34it/s]

 16%|█▌        | 747/4716 [02:56<15:12,  4.35it/s]

 16%|█▌        | 748/4716 [02:57<15:12,  4.35it/s]

 16%|█▌        | 749/4716 [02:57<15:13,  4.34it/s]

 16%|█▌        | 750/4716 [02:57<15:12,  4.34it/s]

 16%|█▌        | 751/4716 [02:57<15:13,  4.34it/s]

 16%|█▌        | 752/4716 [02:58<15:12,  4.35it/s]

 16%|█▌        | 753/4716 [02:58<15:12,  4.34it/s]

 16%|█▌        | 754/4716 [02:58<15:13,  4.34it/s]

 16%|█▌        | 755/4716 [02:58<15:10,  4.35it/s]

 16%|█▌        | 756/4716 [02:59<15:12,  4.34it/s]

 16%|█▌        | 757/4716 [02:59<15:12,  4.34it/s]

 16%|█▌        | 758/4716 [02:59<15:14,  4.33it/s]

 16%|█▌        | 759/4716 [02:59<15:13,  4.33it/s]

 16%|█▌        | 760/4716 [02:59<15:12,  4.34it/s]

 16%|█▌        | 761/4716 [03:00<15:11,  4.34it/s]

 16%|█▌        | 762/4716 [03:00<15:12,  4.34it/s]

 16%|█▌        | 763/4716 [03:00<15:12,  4.33it/s]

 16%|█▌        | 764/4716 [03:00<15:13,  4.33it/s]

 16%|█▌        | 765/4716 [03:01<15:11,  4.33it/s]

 16%|█▌        | 766/4716 [03:01<15:12,  4.33it/s]

 16%|█▋        | 767/4716 [03:01<15:11,  4.33it/s]

 16%|█▋        | 768/4716 [03:01<15:10,  4.33it/s]

 16%|█▋        | 769/4716 [03:02<15:08,  4.34it/s]

 16%|█▋        | 770/4716 [03:02<15:10,  4.33it/s]

 16%|█▋        | 771/4716 [03:02<15:10,  4.33it/s]

 16%|█▋        | 772/4716 [03:02<15:10,  4.33it/s]

 16%|█▋        | 773/4716 [03:02<15:09,  4.33it/s]

 16%|█▋        | 774/4716 [03:03<15:09,  4.33it/s]

 16%|█▋        | 775/4716 [03:03<15:09,  4.33it/s]

 16%|█▋        | 776/4716 [03:03<15:07,  4.34it/s]

 16%|█▋        | 777/4716 [03:03<15:07,  4.34it/s]

 16%|█▋        | 778/4716 [03:04<15:07,  4.34it/s]

 17%|█▋        | 779/4716 [03:04<15:06,  4.34it/s]

 17%|█▋        | 780/4716 [03:04<15:06,  4.34it/s]

 17%|█▋        | 781/4716 [03:04<15:07,  4.33it/s]

 17%|█▋        | 782/4716 [03:05<15:06,  4.34it/s]

 17%|█▋        | 783/4716 [03:05<15:07,  4.33it/s]

 17%|█▋        | 784/4716 [03:05<15:05,  4.34it/s]

 17%|█▋        | 785/4716 [03:05<15:05,  4.34it/s]

 17%|█▋        | 786/4716 [03:05<15:04,  4.34it/s]

 17%|█▋        | 787/4716 [03:06<15:02,  4.35it/s]

 17%|█▋        | 788/4716 [03:06<15:05,  4.34it/s]

 17%|█▋        | 789/4716 [03:06<15:07,  4.33it/s]

 17%|█▋        | 790/4716 [03:06<15:07,  4.33it/s]

 17%|█▋        | 791/4716 [03:07<15:08,  4.32it/s]

 17%|█▋        | 792/4716 [03:07<15:06,  4.33it/s]

 17%|█▋        | 793/4716 [03:07<15:04,  4.34it/s]

 17%|█▋        | 794/4716 [03:07<15:05,  4.33it/s]

 17%|█▋        | 795/4716 [03:08<15:02,  4.34it/s]

 17%|█▋        | 796/4716 [03:08<15:05,  4.33it/s]

 17%|█▋        | 797/4716 [03:08<15:05,  4.33it/s]

 17%|█▋        | 798/4716 [03:08<15:07,  4.32it/s]

 17%|█▋        | 799/4716 [03:08<15:06,  4.32it/s]

 17%|█▋        | 800/4716 [03:09<15:05,  4.33it/s]

 17%|█▋        | 801/4716 [03:09<15:03,  4.33it/s]

 17%|█▋        | 802/4716 [03:09<15:04,  4.33it/s]

 17%|█▋        | 803/4716 [03:09<15:03,  4.33it/s]

 17%|█▋        | 804/4716 [03:10<15:03,  4.33it/s]

 17%|█▋        | 805/4716 [03:10<15:01,  4.34it/s]

 17%|█▋        | 806/4716 [03:10<15:02,  4.33it/s]

 17%|█▋        | 807/4716 [03:10<15:04,  4.32it/s]

 17%|█▋        | 808/4716 [03:11<15:02,  4.33it/s]

 17%|█▋        | 809/4716 [03:11<15:03,  4.33it/s]

 17%|█▋        | 810/4716 [03:11<15:04,  4.32it/s]

 17%|█▋        | 811/4716 [03:11<15:03,  4.32it/s]

 17%|█▋        | 812/4716 [03:11<15:02,  4.32it/s]

 17%|█▋        | 813/4716 [03:12<15:00,  4.33it/s]

 17%|█▋        | 814/4716 [03:12<15:01,  4.33it/s]

 17%|█▋        | 815/4716 [03:12<15:01,  4.33it/s]

 17%|█▋        | 816/4716 [03:12<15:00,  4.33it/s]

 17%|█▋        | 817/4716 [03:13<14:59,  4.33it/s]

 17%|█▋        | 818/4716 [03:13<14:59,  4.33it/s]

 17%|█▋        | 819/4716 [03:13<14:58,  4.34it/s]

 17%|█▋        | 820/4716 [03:13<15:01,  4.32it/s]

 17%|█▋        | 821/4716 [03:14<14:59,  4.33it/s]

 17%|█▋        | 822/4716 [03:14<15:00,  4.32it/s]

 17%|█▋        | 823/4716 [03:14<15:00,  4.32it/s]

 17%|█▋        | 824/4716 [03:14<14:58,  4.33it/s]

 17%|█▋        | 825/4716 [03:14<14:57,  4.34it/s]

 18%|█▊        | 826/4716 [03:15<15:00,  4.32it/s]

 18%|█▊        | 827/4716 [03:15<14:58,  4.33it/s]

 18%|█▊        | 828/4716 [03:15<14:58,  4.33it/s]

 18%|█▊        | 829/4716 [03:15<14:56,  4.33it/s]

 18%|█▊        | 830/4716 [03:16<14:57,  4.33it/s]

 18%|█▊        | 831/4716 [03:16<14:59,  4.32it/s]

 18%|█▊        | 832/4716 [03:16<14:57,  4.33it/s]

 18%|█▊        | 833/4716 [03:16<14:56,  4.33it/s]

 18%|█▊        | 834/4716 [03:17<14:57,  4.32it/s]

 18%|█▊        | 835/4716 [03:17<14:56,  4.33it/s]

 18%|█▊        | 836/4716 [03:17<14:56,  4.33it/s]

 18%|█▊        | 837/4716 [03:17<14:55,  4.33it/s]

 18%|█▊        | 838/4716 [03:17<14:57,  4.32it/s]

 18%|█▊        | 839/4716 [03:18<14:57,  4.32it/s]

 18%|█▊        | 840/4716 [03:18<14:55,  4.33it/s]

 18%|█▊        | 841/4716 [03:18<14:54,  4.33it/s]

 18%|█▊        | 842/4716 [03:18<15:01,  4.30it/s]

 18%|█▊        | 843/4716 [03:19<14:58,  4.31it/s]

 18%|█▊        | 844/4716 [03:19<14:55,  4.32it/s]

 18%|█▊        | 845/4716 [03:19<14:53,  4.33it/s]

 18%|█▊        | 846/4716 [03:19<14:53,  4.33it/s]

 18%|█▊        | 847/4716 [03:20<14:54,  4.32it/s]

 18%|█▊        | 848/4716 [03:20<14:52,  4.33it/s]

 18%|█▊        | 849/4716 [03:20<14:51,  4.34it/s]

 18%|█▊        | 850/4716 [03:20<14:53,  4.33it/s]

 18%|█▊        | 851/4716 [03:20<14:53,  4.33it/s]

 18%|█▊        | 852/4716 [03:21<14:52,  4.33it/s]

 18%|█▊        | 853/4716 [03:21<14:51,  4.33it/s]

 18%|█▊        | 854/4716 [03:21<14:50,  4.34it/s]

 18%|█▊        | 855/4716 [03:21<14:50,  4.34it/s]

 18%|█▊        | 856/4716 [03:22<14:49,  4.34it/s]

 18%|█▊        | 857/4716 [03:22<14:50,  4.33it/s]

 18%|█▊        | 858/4716 [03:22<14:51,  4.33it/s]

 18%|█▊        | 859/4716 [03:22<14:50,  4.33it/s]

 18%|█▊        | 860/4716 [03:23<14:52,  4.32it/s]

 18%|█▊        | 861/4716 [03:23<14:51,  4.33it/s]

 18%|█▊        | 862/4716 [03:23<14:52,  4.32it/s]

 18%|█▊        | 863/4716 [03:23<14:52,  4.32it/s]

 18%|█▊        | 864/4716 [03:23<14:53,  4.31it/s]

 18%|█▊        | 865/4716 [03:24<14:51,  4.32it/s]

 18%|█▊        | 866/4716 [03:24<14:51,  4.32it/s]

 18%|█▊        | 867/4716 [03:24<14:50,  4.32it/s]

 18%|█▊        | 868/4716 [03:24<14:49,  4.33it/s]

 18%|█▊        | 869/4716 [03:25<14:48,  4.33it/s]

 18%|█▊        | 870/4716 [03:25<14:49,  4.32it/s]

 18%|█▊        | 871/4716 [03:25<15:01,  4.27it/s]

 18%|█▊        | 872/4716 [03:25<14:56,  4.29it/s]

 19%|█▊        | 873/4716 [03:26<14:54,  4.30it/s]

 19%|█▊        | 874/4716 [03:26<14:52,  4.31it/s]

 19%|█▊        | 875/4716 [03:26<14:51,  4.31it/s]

 19%|█▊        | 876/4716 [03:26<14:52,  4.30it/s]

 19%|█▊        | 877/4716 [03:26<14:49,  4.31it/s]

 19%|█▊        | 878/4716 [03:27<14:50,  4.31it/s]

 19%|█▊        | 879/4716 [03:27<14:49,  4.32it/s]

 19%|█▊        | 880/4716 [03:27<14:48,  4.32it/s]

 19%|█▊        | 881/4716 [03:27<14:47,  4.32it/s]

 19%|█▊        | 882/4716 [03:28<14:45,  4.33it/s]

 19%|█▊        | 883/4716 [03:28<14:45,  4.33it/s]

 19%|█▊        | 884/4716 [03:28<14:45,  4.33it/s]

 19%|█▉        | 885/4716 [03:28<14:45,  4.33it/s]

 19%|█▉        | 886/4716 [03:29<14:44,  4.33it/s]

 19%|█▉        | 887/4716 [03:29<14:43,  4.33it/s]

 19%|█▉        | 888/4716 [03:29<14:41,  4.34it/s]

 19%|█▉        | 889/4716 [03:29<14:41,  4.34it/s]

 19%|█▉        | 890/4716 [03:29<14:40,  4.35it/s]

 19%|█▉        | 891/4716 [03:30<14:41,  4.34it/s]

 19%|█▉        | 892/4716 [03:30<14:40,  4.34it/s]

 19%|█▉        | 893/4716 [03:30<14:43,  4.33it/s]

 19%|█▉        | 894/4716 [03:30<14:45,  4.32it/s]

 19%|█▉        | 895/4716 [03:31<14:45,  4.32it/s]

 19%|█▉        | 896/4716 [03:31<14:44,  4.32it/s]

 19%|█▉        | 897/4716 [03:31<14:43,  4.32it/s]

 19%|█▉        | 898/4716 [03:31<14:42,  4.32it/s]

 19%|█▉        | 899/4716 [03:32<14:42,  4.33it/s]

 19%|█▉        | 900/4716 [03:32<14:46,  4.31it/s]

 19%|█▉        | 901/4716 [03:32<14:46,  4.31it/s]

 19%|█▉        | 902/4716 [03:32<14:46,  4.30it/s]

 19%|█▉        | 903/4716 [03:33<14:44,  4.31it/s]

 19%|█▉        | 904/4716 [03:33<14:44,  4.31it/s]

 19%|█▉        | 905/4716 [03:33<14:43,  4.31it/s]

 19%|█▉        | 906/4716 [03:33<14:41,  4.32it/s]

 19%|█▉        | 907/4716 [03:33<14:42,  4.31it/s]

 19%|█▉        | 908/4716 [03:34<14:41,  4.32it/s]

 19%|█▉        | 909/4716 [03:34<14:40,  4.32it/s]

 19%|█▉        | 910/4716 [03:34<14:40,  4.32it/s]

 19%|█▉        | 911/4716 [03:34<14:38,  4.33it/s]

 19%|█▉        | 912/4716 [03:35<14:41,  4.32it/s]

 19%|█▉        | 913/4716 [03:35<14:41,  4.31it/s]

 19%|█▉        | 914/4716 [03:35<14:45,  4.29it/s]

 19%|█▉        | 915/4716 [03:35<14:47,  4.28it/s]

 19%|█▉        | 916/4716 [03:36<14:44,  4.30it/s]

 19%|█▉        | 917/4716 [03:36<14:42,  4.30it/s]

 19%|█▉        | 918/4716 [03:36<14:42,  4.30it/s]

 19%|█▉        | 919/4716 [03:36<14:39,  4.32it/s]

 20%|█▉        | 920/4716 [03:36<14:38,  4.32it/s]

 20%|█▉        | 921/4716 [03:37<14:39,  4.31it/s]

 20%|█▉        | 922/4716 [03:37<14:38,  4.32it/s]

 20%|█▉        | 923/4716 [03:37<14:38,  4.32it/s]

 20%|█▉        | 924/4716 [03:37<14:37,  4.32it/s]

 20%|█▉        | 925/4716 [03:38<14:38,  4.32it/s]

 20%|█▉        | 926/4716 [03:38<14:39,  4.31it/s]

 20%|█▉        | 927/4716 [03:38<14:39,  4.31it/s]

 20%|█▉        | 928/4716 [03:38<14:38,  4.31it/s]

 20%|█▉        | 929/4716 [03:39<14:37,  4.32it/s]

 20%|█▉        | 930/4716 [03:39<14:35,  4.32it/s]

 20%|█▉        | 931/4716 [03:39<14:35,  4.33it/s]

 20%|█▉        | 932/4716 [03:39<14:33,  4.33it/s]

 20%|█▉        | 933/4716 [03:39<14:33,  4.33it/s]

 20%|█▉        | 934/4716 [03:40<14:33,  4.33it/s]

 20%|█▉        | 935/4716 [03:40<14:35,  4.32it/s]

 20%|█▉        | 936/4716 [03:40<14:33,  4.33it/s]

 20%|█▉        | 937/4716 [03:40<14:32,  4.33it/s]

 20%|█▉        | 938/4716 [03:41<14:31,  4.34it/s]

 20%|█▉        | 939/4716 [03:41<14:31,  4.33it/s]

 20%|█▉        | 940/4716 [03:41<14:28,  4.35it/s]

 20%|█▉        | 941/4716 [03:41<14:28,  4.35it/s]

 20%|█▉        | 942/4716 [03:42<14:29,  4.34it/s]

 20%|█▉        | 943/4716 [03:42<14:28,  4.35it/s]

 20%|██        | 944/4716 [03:42<14:28,  4.34it/s]

 20%|██        | 945/4716 [03:42<14:29,  4.34it/s]

 20%|██        | 946/4716 [03:42<14:29,  4.34it/s]

 20%|██        | 947/4716 [03:43<14:29,  4.33it/s]

 20%|██        | 948/4716 [03:43<14:29,  4.34it/s]

 20%|██        | 949/4716 [03:43<14:29,  4.33it/s]

 20%|██        | 950/4716 [03:43<14:31,  4.32it/s]

 20%|██        | 951/4716 [03:44<14:31,  4.32it/s]

 20%|██        | 952/4716 [03:44<14:33,  4.31it/s]

 20%|██        | 953/4716 [03:44<14:32,  4.31it/s]

 20%|██        | 954/4716 [03:44<14:32,  4.31it/s]

 20%|██        | 955/4716 [03:45<14:31,  4.32it/s]

 20%|██        | 956/4716 [03:45<14:31,  4.31it/s]

 20%|██        | 957/4716 [03:45<14:30,  4.32it/s]

 20%|██        | 958/4716 [03:45<14:30,  4.32it/s]

 20%|██        | 959/4716 [03:45<14:29,  4.32it/s]

 20%|██        | 960/4716 [03:46<14:28,  4.32it/s]

 20%|██        | 961/4716 [03:46<14:28,  4.32it/s]

 20%|██        | 962/4716 [03:46<14:27,  4.33it/s]

 20%|██        | 963/4716 [03:46<14:27,  4.33it/s]

 20%|██        | 964/4716 [03:47<14:27,  4.32it/s]

 20%|██        | 965/4716 [03:47<14:25,  4.33it/s]

 20%|██        | 966/4716 [03:47<14:26,  4.33it/s]

 21%|██        | 967/4716 [03:47<14:26,  4.33it/s]

 21%|██        | 968/4716 [03:48<14:28,  4.31it/s]

 21%|██        | 969/4716 [03:48<14:28,  4.32it/s]

 21%|██        | 970/4716 [03:48<14:26,  4.32it/s]

 21%|██        | 971/4716 [03:48<14:25,  4.33it/s]

 21%|██        | 972/4716 [03:48<14:26,  4.32it/s]

 21%|██        | 973/4716 [03:49<14:25,  4.33it/s]

 21%|██        | 974/4716 [03:49<14:25,  4.32it/s]

 21%|██        | 975/4716 [03:49<14:26,  4.32it/s]

 21%|██        | 976/4716 [03:49<14:24,  4.33it/s]

 21%|██        | 977/4716 [03:50<14:23,  4.33it/s]

 21%|██        | 978/4716 [03:50<14:24,  4.32it/s]

 21%|██        | 979/4716 [03:50<14:24,  4.33it/s]

 21%|██        | 980/4716 [03:50<14:23,  4.33it/s]

 21%|██        | 981/4716 [03:51<14:23,  4.32it/s]

 21%|██        | 982/4716 [03:51<14:24,  4.32it/s]

 21%|██        | 983/4716 [03:51<14:25,  4.32it/s]

 21%|██        | 984/4716 [03:51<14:24,  4.32it/s]

 21%|██        | 985/4716 [03:51<14:24,  4.32it/s]

 21%|██        | 986/4716 [03:52<14:26,  4.31it/s]

 21%|██        | 987/4716 [03:52<14:24,  4.31it/s]

 21%|██        | 988/4716 [03:52<14:24,  4.31it/s]

 21%|██        | 989/4716 [03:52<14:32,  4.27it/s]

 21%|██        | 990/4716 [03:53<14:29,  4.28it/s]

 21%|██        | 991/4716 [03:53<14:27,  4.29it/s]

 21%|██        | 992/4716 [03:53<14:25,  4.30it/s]

 21%|██        | 993/4716 [03:53<14:24,  4.31it/s]

 21%|██        | 994/4716 [03:54<14:25,  4.30it/s]

 21%|██        | 995/4716 [03:54<14:23,  4.31it/s]

 21%|██        | 996/4716 [03:54<14:22,  4.32it/s]

 21%|██        | 997/4716 [03:54<14:22,  4.31it/s]

 21%|██        | 998/4716 [03:55<14:22,  4.31it/s]

 21%|██        | 999/4716 [03:55<14:23,  4.31it/s]

 21%|██        | 1000/4716 [03:55<14:21,  4.31it/s]

 21%|██        | 1001/4716 [03:55<14:22,  4.31it/s]

 21%|██        | 1002/4716 [03:55<14:26,  4.28it/s]

 21%|██▏       | 1003/4716 [03:56<14:23,  4.30it/s]

 21%|██▏       | 1004/4716 [03:56<14:22,  4.30it/s]

 21%|██▏       | 1005/4716 [03:56<14:21,  4.31it/s]

 21%|██▏       | 1006/4716 [03:56<14:22,  4.30it/s]

 21%|██▏       | 1007/4716 [03:57<14:23,  4.29it/s]

 21%|██▏       | 1008/4716 [03:57<14:21,  4.31it/s]

 21%|██▏       | 1009/4716 [03:57<14:21,  4.30it/s]

 21%|██▏       | 1010/4716 [03:57<14:20,  4.31it/s]

 21%|██▏       | 1011/4716 [03:58<14:23,  4.29it/s]

 21%|██▏       | 1012/4716 [03:58<14:22,  4.29it/s]

 21%|██▏       | 1013/4716 [03:58<14:19,  4.31it/s]

 22%|██▏       | 1014/4716 [03:58<14:19,  4.30it/s]

 22%|██▏       | 1015/4716 [03:58<14:19,  4.30it/s]

 22%|██▏       | 1016/4716 [03:59<14:20,  4.30it/s]

 22%|██▏       | 1017/4716 [03:59<14:22,  4.29it/s]

 22%|██▏       | 1018/4716 [03:59<14:20,  4.30it/s]

 22%|██▏       | 1019/4716 [03:59<14:19,  4.30it/s]

 22%|██▏       | 1020/4716 [04:00<14:17,  4.31it/s]

 22%|██▏       | 1021/4716 [04:00<14:22,  4.28it/s]

 22%|██▏       | 1022/4716 [04:00<14:20,  4.29it/s]

 22%|██▏       | 1023/4716 [04:00<14:18,  4.30it/s]

 22%|██▏       | 1024/4716 [04:01<14:17,  4.30it/s]

 22%|██▏       | 1025/4716 [04:01<14:17,  4.31it/s]

 22%|██▏       | 1026/4716 [04:01<14:16,  4.31it/s]

 22%|██▏       | 1027/4716 [04:01<14:19,  4.29it/s]

 22%|██▏       | 1028/4716 [04:01<14:19,  4.29it/s]

 22%|██▏       | 1029/4716 [04:02<14:20,  4.29it/s]

 22%|██▏       | 1030/4716 [04:02<14:18,  4.29it/s]

 22%|██▏       | 1031/4716 [04:02<14:18,  4.29it/s]

 22%|██▏       | 1032/4716 [04:02<14:18,  4.29it/s]

 22%|██▏       | 1033/4716 [04:03<14:17,  4.30it/s]

 22%|██▏       | 1034/4716 [04:03<14:16,  4.30it/s]

 22%|██▏       | 1035/4716 [04:03<14:16,  4.30it/s]

 22%|██▏       | 1036/4716 [04:03<14:15,  4.30it/s]

 22%|██▏       | 1037/4716 [04:04<14:15,  4.30it/s]

 22%|██▏       | 1038/4716 [04:04<14:15,  4.30it/s]

 22%|██▏       | 1039/4716 [04:04<14:13,  4.31it/s]

 22%|██▏       | 1040/4716 [04:04<14:14,  4.30it/s]

 22%|██▏       | 1041/4716 [04:05<14:13,  4.30it/s]

 22%|██▏       | 1042/4716 [04:05<14:13,  4.30it/s]

 22%|██▏       | 1043/4716 [04:05<14:14,  4.30it/s]

 22%|██▏       | 1044/4716 [04:05<14:12,  4.31it/s]

 22%|██▏       | 1045/4716 [04:05<14:14,  4.29it/s]

 22%|██▏       | 1046/4716 [04:06<14:14,  4.29it/s]

 22%|██▏       | 1047/4716 [04:06<14:14,  4.29it/s]

 22%|██▏       | 1048/4716 [04:06<14:15,  4.29it/s]

 22%|██▏       | 1049/4716 [04:06<14:13,  4.30it/s]

 22%|██▏       | 1050/4716 [04:07<14:14,  4.29it/s]

 22%|██▏       | 1051/4716 [04:07<14:13,  4.29it/s]

 22%|██▏       | 1052/4716 [04:07<14:13,  4.30it/s]

 22%|██▏       | 1053/4716 [04:07<14:13,  4.29it/s]

 22%|██▏       | 1054/4716 [04:08<14:10,  4.30it/s]

 22%|██▏       | 1055/4716 [04:08<14:12,  4.29it/s]

 22%|██▏       | 1056/4716 [04:08<14:11,  4.30it/s]

 22%|██▏       | 1057/4716 [04:08<14:10,  4.30it/s]

 22%|██▏       | 1058/4716 [04:08<14:10,  4.30it/s]

 22%|██▏       | 1059/4716 [04:09<14:09,  4.30it/s]

 22%|██▏       | 1060/4716 [04:09<14:08,  4.31it/s]

 22%|██▏       | 1061/4716 [04:09<14:10,  4.30it/s]

 23%|██▎       | 1062/4716 [04:09<14:08,  4.31it/s]

 23%|██▎       | 1063/4716 [04:10<14:06,  4.32it/s]

 23%|██▎       | 1064/4716 [04:10<14:12,  4.29it/s]

 23%|██▎       | 1065/4716 [04:10<14:11,  4.29it/s]

 23%|██▎       | 1066/4716 [04:10<14:10,  4.29it/s]

 23%|██▎       | 1067/4716 [04:11<14:09,  4.30it/s]

 23%|██▎       | 1068/4716 [04:11<14:09,  4.30it/s]

 23%|██▎       | 1069/4716 [04:11<14:10,  4.29it/s]

 23%|██▎       | 1070/4716 [04:11<14:09,  4.29it/s]

 23%|██▎       | 1071/4716 [04:11<14:11,  4.28it/s]

 23%|██▎       | 1072/4716 [04:12<14:10,  4.29it/s]

 23%|██▎       | 1073/4716 [04:12<14:09,  4.29it/s]

 23%|██▎       | 1074/4716 [04:12<14:09,  4.29it/s]

 23%|██▎       | 1075/4716 [04:12<14:07,  4.29it/s]

 23%|██▎       | 1076/4716 [04:13<14:07,  4.30it/s]

 23%|██▎       | 1077/4716 [04:13<14:05,  4.31it/s]

 23%|██▎       | 1078/4716 [04:13<14:04,  4.31it/s]

 23%|██▎       | 1079/4716 [04:13<14:06,  4.30it/s]

 23%|██▎       | 1080/4716 [04:14<14:04,  4.31it/s]

 23%|██▎       | 1081/4716 [04:14<14:03,  4.31it/s]

 23%|██▎       | 1082/4716 [04:14<14:02,  4.31it/s]

 23%|██▎       | 1083/4716 [04:14<14:02,  4.31it/s]

 23%|██▎       | 1084/4716 [04:15<14:03,  4.30it/s]

 23%|██▎       | 1085/4716 [04:15<14:03,  4.30it/s]

 23%|██▎       | 1086/4716 [04:15<14:03,  4.30it/s]

 23%|██▎       | 1087/4716 [04:15<14:04,  4.30it/s]

 23%|██▎       | 1088/4716 [04:15<14:02,  4.31it/s]

 23%|██▎       | 1089/4716 [04:16<14:02,  4.31it/s]

 23%|██▎       | 1090/4716 [04:16<14:01,  4.31it/s]

 23%|██▎       | 1091/4716 [04:16<14:00,  4.31it/s]

 23%|██▎       | 1092/4716 [04:16<14:01,  4.31it/s]

 23%|██▎       | 1093/4716 [04:17<14:01,  4.30it/s]

 23%|██▎       | 1094/4716 [04:17<14:03,  4.30it/s]

 23%|██▎       | 1095/4716 [04:17<14:03,  4.29it/s]

 23%|██▎       | 1096/4716 [04:17<14:11,  4.25it/s]

 23%|██▎       | 1097/4716 [04:18<14:09,  4.26it/s]

 23%|██▎       | 1098/4716 [04:18<14:06,  4.27it/s]

 23%|██▎       | 1099/4716 [04:18<14:07,  4.27it/s]

 23%|██▎       | 1100/4716 [04:18<14:06,  4.27it/s]

 23%|██▎       | 1101/4716 [04:18<14:03,  4.28it/s]

 23%|██▎       | 1102/4716 [04:19<14:03,  4.28it/s]

 23%|██▎       | 1103/4716 [04:19<14:03,  4.28it/s]

 23%|██▎       | 1104/4716 [04:19<14:04,  4.28it/s]

 23%|██▎       | 1105/4716 [04:19<14:04,  4.27it/s]

 23%|██▎       | 1106/4716 [04:20<14:04,  4.28it/s]

 23%|██▎       | 1107/4716 [04:20<14:02,  4.28it/s]

 23%|██▎       | 1108/4716 [04:20<14:01,  4.29it/s]

 24%|██▎       | 1109/4716 [04:20<14:02,  4.28it/s]

 24%|██▎       | 1110/4716 [04:21<14:06,  4.26it/s]

 24%|██▎       | 1111/4716 [04:21<14:04,  4.27it/s]

 24%|██▎       | 1112/4716 [04:21<14:05,  4.26it/s]

 24%|██▎       | 1113/4716 [04:21<14:05,  4.26it/s]

 24%|██▎       | 1114/4716 [04:22<14:05,  4.26it/s]

 24%|██▎       | 1115/4716 [04:22<14:04,  4.27it/s]

 24%|██▎       | 1116/4716 [04:22<14:02,  4.27it/s]

 24%|██▎       | 1117/4716 [04:22<14:01,  4.28it/s]

 24%|██▎       | 1118/4716 [04:22<14:00,  4.28it/s]

 24%|██▎       | 1119/4716 [04:23<14:00,  4.28it/s]

 24%|██▎       | 1120/4716 [04:23<13:59,  4.28it/s]

 24%|██▍       | 1121/4716 [04:23<13:58,  4.29it/s]

 24%|██▍       | 1122/4716 [04:23<13:57,  4.29it/s]

 24%|██▍       | 1123/4716 [04:24<13:59,  4.28it/s]

 24%|██▍       | 1124/4716 [04:24<14:02,  4.26it/s]

 24%|██▍       | 1125/4716 [04:24<14:00,  4.27it/s]

 24%|██▍       | 1126/4716 [04:24<13:58,  4.28it/s]

 24%|██▍       | 1127/4716 [04:25<13:58,  4.28it/s]

 24%|██▍       | 1128/4716 [04:25<13:59,  4.28it/s]

 24%|██▍       | 1129/4716 [04:25<13:59,  4.27it/s]

 24%|██▍       | 1130/4716 [04:25<13:58,  4.27it/s]

 24%|██▍       | 1131/4716 [04:25<13:57,  4.28it/s]

 24%|██▍       | 1132/4716 [04:26<13:57,  4.28it/s]

 24%|██▍       | 1133/4716 [04:26<13:56,  4.28it/s]

 24%|██▍       | 1134/4716 [04:26<13:54,  4.29it/s]

 24%|██▍       | 1135/4716 [04:26<13:55,  4.29it/s]

 24%|██▍       | 1136/4716 [04:27<13:56,  4.28it/s]

 24%|██▍       | 1137/4716 [04:27<13:57,  4.27it/s]

 24%|██▍       | 1138/4716 [04:27<13:58,  4.27it/s]

 24%|██▍       | 1139/4716 [04:27<13:55,  4.28it/s]

 24%|██▍       | 1140/4716 [04:28<13:54,  4.28it/s]

 24%|██▍       | 1141/4716 [04:28<13:53,  4.29it/s]

 24%|██▍       | 1142/4716 [04:28<13:54,  4.28it/s]

 24%|██▍       | 1143/4716 [04:28<13:54,  4.28it/s]

 24%|██▍       | 1144/4716 [04:29<13:55,  4.28it/s]

 24%|██▍       | 1145/4716 [04:29<13:54,  4.28it/s]

 24%|██▍       | 1146/4716 [04:29<13:52,  4.29it/s]

 24%|██▍       | 1147/4716 [04:29<13:53,  4.28it/s]

 24%|██▍       | 1148/4716 [04:29<13:57,  4.26it/s]

 24%|██▍       | 1149/4716 [04:30<13:57,  4.26it/s]

 24%|██▍       | 1150/4716 [04:30<13:56,  4.26it/s]

 24%|██▍       | 1151/4716 [04:30<14:04,  4.22it/s]

 24%|██▍       | 1152/4716 [04:30<14:00,  4.24it/s]

 24%|██▍       | 1153/4716 [04:31<13:59,  4.25it/s]

 24%|██▍       | 1154/4716 [04:31<13:58,  4.25it/s]

 24%|██▍       | 1155/4716 [04:31<13:58,  4.25it/s]

 25%|██▍       | 1156/4716 [04:31<13:58,  4.24it/s]

 25%|██▍       | 1157/4716 [04:32<13:58,  4.24it/s]

 25%|██▍       | 1158/4716 [04:32<13:59,  4.24it/s]

 25%|██▍       | 1159/4716 [04:32<13:56,  4.25it/s]

 25%|██▍       | 1160/4716 [04:32<13:56,  4.25it/s]

 25%|██▍       | 1161/4716 [04:33<13:56,  4.25it/s]

 25%|██▍       | 1162/4716 [04:33<13:56,  4.25it/s]

 25%|██▍       | 1163/4716 [04:33<13:54,  4.26it/s]

 25%|██▍       | 1164/4716 [04:33<13:52,  4.27it/s]

 25%|██▍       | 1165/4716 [04:33<13:54,  4.26it/s]

 25%|██▍       | 1166/4716 [04:34<13:52,  4.26it/s]

 25%|██▍       | 1167/4716 [04:34<13:54,  4.25it/s]

 25%|██▍       | 1168/4716 [04:34<13:58,  4.23it/s]

 25%|██▍       | 1169/4716 [04:34<13:56,  4.24it/s]

 25%|██▍       | 1170/4716 [04:35<13:54,  4.25it/s]

 25%|██▍       | 1171/4716 [04:35<13:55,  4.24it/s]

 25%|██▍       | 1172/4716 [04:35<13:55,  4.24it/s]

 25%|██▍       | 1173/4716 [04:35<13:54,  4.24it/s]

 25%|██▍       | 1174/4716 [04:36<13:52,  4.25it/s]

 25%|██▍       | 1175/4716 [04:36<13:52,  4.25it/s]

 25%|██▍       | 1176/4716 [04:36<13:51,  4.26it/s]

 25%|██▍       | 1177/4716 [04:36<13:50,  4.26it/s]

 25%|██▍       | 1178/4716 [04:37<13:49,  4.26it/s]

 25%|██▌       | 1179/4716 [04:37<13:48,  4.27it/s]

 25%|██▌       | 1180/4716 [04:37<13:48,  4.27it/s]

 25%|██▌       | 1181/4716 [04:37<13:51,  4.25it/s]

 25%|██▌       | 1182/4716 [04:37<13:52,  4.24it/s]

 25%|██▌       | 1183/4716 [04:38<13:54,  4.23it/s]

 25%|██▌       | 1184/4716 [04:38<13:50,  4.25it/s]

 25%|██▌       | 1185/4716 [04:38<13:50,  4.25it/s]

 25%|██▌       | 1186/4716 [04:38<13:49,  4.25it/s]

 25%|██▌       | 1187/4716 [04:39<13:49,  4.25it/s]

 25%|██▌       | 1188/4716 [04:39<13:51,  4.24it/s]

 25%|██▌       | 1189/4716 [04:39<13:49,  4.25it/s]

 25%|██▌       | 1190/4716 [04:39<13:49,  4.25it/s]

 25%|██▌       | 1191/4716 [04:40<13:48,  4.26it/s]

 25%|██▌       | 1192/4716 [04:40<13:48,  4.26it/s]

 25%|██▌       | 1193/4716 [04:40<13:49,  4.25it/s]

 25%|██▌       | 1194/4716 [04:40<13:50,  4.24it/s]

 25%|██▌       | 1195/4716 [04:41<13:50,  4.24it/s]

 25%|██▌       | 1196/4716 [04:41<13:50,  4.24it/s]

 25%|██▌       | 1197/4716 [04:41<13:52,  4.23it/s]

 25%|██▌       | 1198/4716 [04:41<13:51,  4.23it/s]

 25%|██▌       | 1199/4716 [04:41<13:49,  4.24it/s]

 25%|██▌       | 1200/4716 [04:42<13:48,  4.25it/s]

 25%|██▌       | 1201/4716 [04:42<13:46,  4.25it/s]

 25%|██▌       | 1202/4716 [04:42<13:45,  4.26it/s]

 26%|██▌       | 1203/4716 [04:42<13:45,  4.26it/s]

 26%|██▌       | 1204/4716 [04:43<13:45,  4.25it/s]

 26%|██▌       | 1205/4716 [04:43<13:47,  4.24it/s]

 26%|██▌       | 1206/4716 [04:43<13:45,  4.25it/s]

 26%|██▌       | 1207/4716 [04:43<13:47,  4.24it/s]

 26%|██▌       | 1208/4716 [04:44<13:46,  4.24it/s]

 26%|██▌       | 1209/4716 [04:44<13:43,  4.26it/s]

 26%|██▌       | 1210/4716 [04:44<13:43,  4.26it/s]

 26%|██▌       | 1211/4716 [04:44<13:43,  4.25it/s]

 26%|██▌       | 1212/4716 [04:45<13:43,  4.26it/s]

 26%|██▌       | 1213/4716 [04:45<13:43,  4.25it/s]

 26%|██▌       | 1214/4716 [04:45<13:46,  4.24it/s]

 26%|██▌       | 1215/4716 [04:45<13:45,  4.24it/s]

 26%|██▌       | 1216/4716 [04:45<13:43,  4.25it/s]

 26%|██▌       | 1217/4716 [04:46<13:43,  4.25it/s]

 26%|██▌       | 1218/4716 [04:46<13:45,  4.24it/s]

 26%|██▌       | 1219/4716 [04:46<13:42,  4.25it/s]

 26%|██▌       | 1220/4716 [04:46<13:42,  4.25it/s]

 26%|██▌       | 1221/4716 [04:47<13:42,  4.25it/s]

 26%|██▌       | 1222/4716 [04:47<13:42,  4.25it/s]

 26%|██▌       | 1223/4716 [04:47<13:40,  4.26it/s]

 26%|██▌       | 1224/4716 [04:47<13:41,  4.25it/s]

 26%|██▌       | 1225/4716 [04:48<13:43,  4.24it/s]

 26%|██▌       | 1226/4716 [04:48<13:43,  4.24it/s]

 26%|██▌       | 1227/4716 [04:48<13:43,  4.24it/s]

 26%|██▌       | 1228/4716 [04:48<13:43,  4.24it/s]

 26%|██▌       | 1229/4716 [04:49<13:41,  4.25it/s]

 26%|██▌       | 1230/4716 [04:49<13:40,  4.25it/s]

 26%|██▌       | 1231/4716 [04:49<13:39,  4.25it/s]

 26%|██▌       | 1232/4716 [04:49<13:41,  4.24it/s]

 26%|██▌       | 1233/4716 [04:49<13:44,  4.23it/s]

 26%|██▌       | 1234/4716 [04:50<13:42,  4.24it/s]

 26%|██▌       | 1235/4716 [04:50<13:40,  4.24it/s]

 26%|██▌       | 1236/4716 [04:50<13:42,  4.23it/s]

 26%|██▌       | 1237/4716 [04:50<13:43,  4.22it/s]

 26%|██▋       | 1238/4716 [04:51<13:41,  4.23it/s]

 26%|██▋       | 1239/4716 [04:51<13:41,  4.23it/s]

 26%|██▋       | 1240/4716 [04:51<13:44,  4.21it/s]

 26%|██▋       | 1241/4716 [04:51<13:43,  4.22it/s]

 26%|██▋       | 1242/4716 [04:52<13:42,  4.22it/s]

 26%|██▋       | 1243/4716 [04:52<13:43,  4.22it/s]

 26%|██▋       | 1244/4716 [04:52<13:40,  4.23it/s]

 26%|██▋       | 1245/4716 [04:52<13:39,  4.23it/s]

 26%|██▋       | 1246/4716 [04:53<13:40,  4.23it/s]

 26%|██▋       | 1247/4716 [04:53<13:39,  4.24it/s]

 26%|██▋       | 1248/4716 [04:53<13:37,  4.24it/s]

 26%|██▋       | 1249/4716 [04:53<13:35,  4.25it/s]

 27%|██▋       | 1250/4716 [04:53<13:35,  4.25it/s]

 27%|██▋       | 1251/4716 [04:54<13:35,  4.25it/s]

logging
logging the anndata

 27%|██▋       | 1252/4716 [04:55<31:20,  1.84it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 27%|██▋       | 1253/4716 [04:55<25:54,  2.23it/s]

 27%|██▋       | 1254/4716 [04:55<22:04,  2.61it/s]

 27%|██▋       | 1255/4716 [04:56<19:25,  2.97it/s]

 27%|██▋       | 1256/4716 [04:56<17:34,  3.28it/s]

 27%|██▋       | 1257/4716 [04:56<16:14,  3.55it/s]

 27%|██▋       | 1258/4716 [04:56<15:22,  3.75it/s]

 27%|██▋       | 1259/4716 [04:57<14:44,  3.91it/s]

 27%|██▋       | 1260/4716 [04:57<14:15,  4.04it/s]

 27%|██▋       | 1261/4716 [04:57<13:57,  4.13it/s]

 27%|██▋       | 1262/4716 [04:57<13:46,  4.18it/s]

 27%|██▋       | 1263/4716 [04:58<13:36,  4.23it/s]

 27%|██▋       | 1264/4716 [04:58<13:28,  4.27it/s]

 27%|██▋       | 1265/4716 [04:58<13:22,  4.30it/s]

 27%|██▋       | 1266/4716 [04:58<13:20,  4.31it/s]

 27%|██▋       | 1267/4716 [04:58<13:17,  4.32it/s]

 27%|██▋       | 1268/4716 [04:59<13:16,  4.33it/s]

 27%|██▋       | 1269/4716 [04:59<13:14,  4.34it/s]

 27%|██▋       | 1270/4716 [04:59<13:13,  4.34it/s]

 27%|██▋       | 1271/4716 [04:59<13:11,  4.35it/s]

 27%|██▋       | 1272/4716 [05:00<13:11,  4.35it/s]

 27%|██▋       | 1273/4716 [05:00<13:11,  4.35it/s]

 27%|██▋       | 1274/4716 [05:00<13:09,  4.36it/s]

 27%|██▋       | 1275/4716 [05:00<13:10,  4.35it/s]

 27%|██▋       | 1276/4716 [05:01<13:11,  4.35it/s]

 27%|██▋       | 1277/4716 [05:01<13:09,  4.36it/s]

 27%|██▋       | 1278/4716 [05:01<13:08,  4.36it/s]

 27%|██▋       | 1279/4716 [05:01<13:07,  4.36it/s]

 27%|██▋       | 1280/4716 [05:01<13:07,  4.36it/s]

 27%|██▋       | 1281/4716 [05:02<13:07,  4.36it/s]

 27%|██▋       | 1282/4716 [05:02<13:07,  4.36it/s]

 27%|██▋       | 1283/4716 [05:02<13:07,  4.36it/s]

 27%|██▋       | 1284/4716 [05:02<13:06,  4.36it/s]

 27%|██▋       | 1285/4716 [05:03<13:06,  4.36it/s]

 27%|██▋       | 1286/4716 [05:03<13:10,  4.34it/s]

 27%|██▋       | 1287/4716 [05:03<13:10,  4.34it/s]

 27%|██▋       | 1288/4716 [05:03<13:09,  4.34it/s]

 27%|██▋       | 1289/4716 [05:03<13:07,  4.35it/s]

 27%|██▋       | 1290/4716 [05:04<13:08,  4.34it/s]

 27%|██▋       | 1291/4716 [05:04<13:07,  4.35it/s]

 27%|██▋       | 1292/4716 [05:04<13:09,  4.33it/s]

 27%|██▋       | 1293/4716 [05:04<13:08,  4.34it/s]

 27%|██▋       | 1294/4716 [05:05<13:06,  4.35it/s]

 27%|██▋       | 1295/4716 [05:05<13:06,  4.35it/s]

 27%|██▋       | 1296/4716 [05:05<13:03,  4.36it/s]

 28%|██▊       | 1297/4716 [05:05<13:04,  4.36it/s]

 28%|██▊       | 1298/4716 [05:06<13:03,  4.36it/s]

 28%|██▊       | 1299/4716 [05:06<13:03,  4.36it/s]

 28%|██▊       | 1300/4716 [05:06<13:06,  4.34it/s]

 28%|██▊       | 1301/4716 [05:06<13:04,  4.35it/s]

 28%|██▊       | 1302/4716 [05:06<13:05,  4.35it/s]

 28%|██▊       | 1303/4716 [05:07<13:06,  4.34it/s]

 28%|██▊       | 1304/4716 [05:07<13:04,  4.35it/s]

 28%|██▊       | 1305/4716 [05:07<13:03,  4.35it/s]

 28%|██▊       | 1306/4716 [05:07<13:03,  4.35it/s]

 28%|██▊       | 1307/4716 [05:08<13:02,  4.36it/s]

 28%|██▊       | 1308/4716 [05:08<13:01,  4.36it/s]

 28%|██▊       | 1309/4716 [05:08<13:01,  4.36it/s]

 28%|██▊       | 1310/4716 [05:08<13:01,  4.36it/s]

 28%|██▊       | 1311/4716 [05:09<13:02,  4.35it/s]

 28%|██▊       | 1312/4716 [05:09<13:01,  4.36it/s]

 28%|██▊       | 1313/4716 [05:09<13:01,  4.35it/s]

 28%|██▊       | 1314/4716 [05:09<13:03,  4.34it/s]

 28%|██▊       | 1315/4716 [05:09<13:01,  4.35it/s]

 28%|██▊       | 1316/4716 [05:10<13:01,  4.35it/s]

 28%|██▊       | 1317/4716 [05:10<13:02,  4.35it/s]

 28%|██▊       | 1318/4716 [05:10<13:00,  4.35it/s]

 28%|██▊       | 1319/4716 [05:10<13:01,  4.35it/s]

 28%|██▊       | 1320/4716 [05:11<13:01,  4.35it/s]

 28%|██▊       | 1321/4716 [05:11<13:00,  4.35it/s]

 28%|██▊       | 1322/4716 [05:11<12:59,  4.35it/s]

 28%|██▊       | 1323/4716 [05:11<12:57,  4.36it/s]

 28%|██▊       | 1324/4716 [05:12<12:56,  4.37it/s]

 28%|██▊       | 1325/4716 [05:12<12:57,  4.36it/s]

 28%|██▊       | 1326/4716 [05:12<12:59,  4.35it/s]

 28%|██▊       | 1327/4716 [05:12<12:59,  4.35it/s]

 28%|██▊       | 1328/4716 [05:12<12:57,  4.36it/s]

 28%|██▊       | 1329/4716 [05:13<12:58,  4.35it/s]

 28%|██▊       | 1330/4716 [05:13<12:59,  4.35it/s]

 28%|██▊       | 1331/4716 [05:13<12:57,  4.35it/s]

 28%|██▊       | 1332/4716 [05:13<12:57,  4.35it/s]

 28%|██▊       | 1333/4716 [05:14<12:57,  4.35it/s]

 28%|██▊       | 1334/4716 [05:14<12:57,  4.35it/s]

 28%|██▊       | 1335/4716 [05:14<12:57,  4.35it/s]

 28%|██▊       | 1336/4716 [05:14<12:57,  4.35it/s]

 28%|██▊       | 1337/4716 [05:15<12:57,  4.34it/s]

 28%|██▊       | 1338/4716 [05:15<12:57,  4.35it/s]

 28%|██▊       | 1339/4716 [05:15<12:56,  4.35it/s]

 28%|██▊       | 1340/4716 [05:15<12:55,  4.35it/s]

 28%|██▊       | 1341/4716 [05:15<12:56,  4.34it/s]

 28%|██▊       | 1342/4716 [05:16<12:57,  4.34it/s]

 28%|██▊       | 1343/4716 [05:16<12:58,  4.33it/s]

 28%|██▊       | 1344/4716 [05:16<12:57,  4.34it/s]

 29%|██▊       | 1345/4716 [05:16<12:57,  4.33it/s]

 29%|██▊       | 1346/4716 [05:17<12:58,  4.33it/s]

 29%|██▊       | 1347/4716 [05:17<12:59,  4.32it/s]

 29%|██▊       | 1348/4716 [05:17<12:57,  4.33it/s]

 29%|██▊       | 1349/4716 [05:17<12:57,  4.33it/s]

 29%|██▊       | 1350/4716 [05:18<12:56,  4.34it/s]

 29%|██▊       | 1351/4716 [05:18<12:57,  4.33it/s]

 29%|██▊       | 1352/4716 [05:18<12:55,  4.34it/s]

 29%|██▊       | 1353/4716 [05:18<12:54,  4.34it/s]

 29%|██▊       | 1354/4716 [05:18<12:52,  4.35it/s]

 29%|██▊       | 1355/4716 [05:19<12:51,  4.36it/s]

 29%|██▉       | 1356/4716 [05:19<12:53,  4.34it/s]

 29%|██▉       | 1357/4716 [05:19<12:54,  4.34it/s]

 29%|██▉       | 1358/4716 [05:19<12:53,  4.34it/s]

 29%|██▉       | 1359/4716 [05:20<12:53,  4.34it/s]

 29%|██▉       | 1360/4716 [05:20<12:53,  4.34it/s]

 29%|██▉       | 1361/4716 [05:20<12:53,  4.34it/s]

 29%|██▉       | 1362/4716 [05:20<12:53,  4.34it/s]

 29%|██▉       | 1363/4716 [05:21<12:51,  4.35it/s]

 29%|██▉       | 1364/4716 [05:21<12:50,  4.35it/s]

 29%|██▉       | 1365/4716 [05:21<12:50,  4.35it/s]

 29%|██▉       | 1366/4716 [05:21<12:49,  4.36it/s]

 29%|██▉       | 1367/4716 [05:21<12:49,  4.35it/s]

 29%|██▉       | 1368/4716 [05:22<12:50,  4.34it/s]

 29%|██▉       | 1369/4716 [05:22<12:52,  4.33it/s]

 29%|██▉       | 1370/4716 [05:22<12:51,  4.34it/s]

 29%|██▉       | 1371/4716 [05:22<12:50,  4.34it/s]

 29%|██▉       | 1372/4716 [05:23<12:49,  4.34it/s]

 29%|██▉       | 1373/4716 [05:23<12:48,  4.35it/s]

 29%|██▉       | 1374/4716 [05:23<12:47,  4.36it/s]

 29%|██▉       | 1375/4716 [05:23<12:47,  4.35it/s]

 29%|██▉       | 1376/4716 [05:24<12:48,  4.35it/s]

 29%|██▉       | 1377/4716 [05:24<12:47,  4.35it/s]

 29%|██▉       | 1378/4716 [05:24<12:47,  4.35it/s]

 29%|██▉       | 1379/4716 [05:24<12:48,  4.34it/s]

 29%|██▉       | 1380/4716 [05:24<12:48,  4.34it/s]

 29%|██▉       | 1381/4716 [05:25<12:48,  4.34it/s]

 29%|██▉       | 1382/4716 [05:25<12:47,  4.35it/s]

 29%|██▉       | 1383/4716 [05:25<12:48,  4.34it/s]

 29%|██▉       | 1384/4716 [05:25<12:49,  4.33it/s]

 29%|██▉       | 1385/4716 [05:26<12:47,  4.34it/s]

 29%|██▉       | 1386/4716 [05:26<12:47,  4.34it/s]

 29%|██▉       | 1387/4716 [05:26<12:52,  4.31it/s]

 29%|██▉       | 1388/4716 [05:26<12:52,  4.31it/s]

 29%|██▉       | 1389/4716 [05:27<12:50,  4.32it/s]

 29%|██▉       | 1390/4716 [05:27<12:47,  4.33it/s]

 29%|██▉       | 1391/4716 [05:27<12:49,  4.32it/s]

 30%|██▉       | 1392/4716 [05:27<12:47,  4.33it/s]

 30%|██▉       | 1393/4716 [05:27<12:46,  4.33it/s]

 30%|██▉       | 1394/4716 [05:28<12:46,  4.33it/s]

 30%|██▉       | 1395/4716 [05:28<12:47,  4.33it/s]

 30%|██▉       | 1396/4716 [05:28<12:46,  4.33it/s]

 30%|██▉       | 1397/4716 [05:28<12:47,  4.32it/s]

 30%|██▉       | 1398/4716 [05:29<12:45,  4.34it/s]

 30%|██▉       | 1399/4716 [05:29<12:46,  4.33it/s]

 30%|██▉       | 1400/4716 [05:29<12:47,  4.32it/s]

 30%|██▉       | 1401/4716 [05:29<12:49,  4.31it/s]

 30%|██▉       | 1402/4716 [05:30<12:49,  4.31it/s]

 30%|██▉       | 1403/4716 [05:30<12:48,  4.31it/s]

 30%|██▉       | 1404/4716 [05:30<12:49,  4.31it/s]

 30%|██▉       | 1405/4716 [05:30<12:48,  4.31it/s]

 30%|██▉       | 1406/4716 [05:30<12:46,  4.32it/s]

 30%|██▉       | 1407/4716 [05:31<12:45,  4.32it/s]

 30%|██▉       | 1408/4716 [05:31<12:54,  4.27it/s]

 30%|██▉       | 1409/4716 [05:31<12:49,  4.30it/s]

 30%|██▉       | 1410/4716 [05:31<12:48,  4.30it/s]

 30%|██▉       | 1411/4716 [05:32<12:46,  4.31it/s]

 30%|██▉       | 1412/4716 [05:32<12:44,  4.32it/s]

 30%|██▉       | 1413/4716 [05:32<12:43,  4.33it/s]

 30%|██▉       | 1414/4716 [05:32<12:41,  4.33it/s]

 30%|███       | 1415/4716 [05:33<12:41,  4.33it/s]

 30%|███       | 1416/4716 [05:33<12:41,  4.33it/s]

 30%|███       | 1417/4716 [05:33<12:42,  4.32it/s]

 30%|███       | 1418/4716 [05:33<12:43,  4.32it/s]

 30%|███       | 1419/4716 [05:33<12:43,  4.32it/s]

 30%|███       | 1420/4716 [05:34<12:44,  4.31it/s]

 30%|███       | 1421/4716 [05:34<12:44,  4.31it/s]

 30%|███       | 1422/4716 [05:34<12:41,  4.32it/s]

 30%|███       | 1423/4716 [05:34<12:40,  4.33it/s]

 30%|███       | 1424/4716 [05:35<12:42,  4.32it/s]

 30%|███       | 1425/4716 [05:35<12:41,  4.32it/s]

 30%|███       | 1426/4716 [05:35<12:42,  4.32it/s]

 30%|███       | 1427/4716 [05:35<12:40,  4.33it/s]

 30%|███       | 1428/4716 [05:36<12:40,  4.32it/s]

 30%|███       | 1429/4716 [05:36<12:39,  4.33it/s]

 30%|███       | 1430/4716 [05:36<12:45,  4.29it/s]

 30%|███       | 1431/4716 [05:36<12:43,  4.30it/s]

 30%|███       | 1432/4716 [05:36<12:42,  4.30it/s]

 30%|███       | 1433/4716 [05:37<12:40,  4.32it/s]

 30%|███       | 1434/4716 [05:37<12:41,  4.31it/s]

 30%|███       | 1435/4716 [05:37<12:38,  4.32it/s]

 30%|███       | 1436/4716 [05:37<12:39,  4.32it/s]

 30%|███       | 1437/4716 [05:38<12:41,  4.31it/s]

 30%|███       | 1438/4716 [05:38<12:41,  4.31it/s]

 31%|███       | 1439/4716 [05:38<12:41,  4.30it/s]

 31%|███       | 1440/4716 [05:38<12:40,  4.31it/s]

 31%|███       | 1441/4716 [05:39<12:40,  4.31it/s]

 31%|███       | 1442/4716 [05:39<12:40,  4.30it/s]

 31%|███       | 1443/4716 [05:39<12:39,  4.31it/s]

 31%|███       | 1444/4716 [05:39<12:37,  4.32it/s]

 31%|███       | 1445/4716 [05:39<12:37,  4.32it/s]

 31%|███       | 1446/4716 [05:40<12:37,  4.32it/s]

 31%|███       | 1447/4716 [05:40<12:36,  4.32it/s]

 31%|███       | 1448/4716 [05:40<12:34,  4.33it/s]

 31%|███       | 1449/4716 [05:40<12:35,  4.32it/s]

 31%|███       | 1450/4716 [05:41<12:35,  4.32it/s]

 31%|███       | 1451/4716 [05:41<12:37,  4.31it/s]

 31%|███       | 1452/4716 [05:41<12:37,  4.31it/s]

 31%|███       | 1453/4716 [05:41<12:34,  4.32it/s]

 31%|███       | 1454/4716 [05:42<12:33,  4.33it/s]

 31%|███       | 1455/4716 [05:42<12:33,  4.33it/s]

 31%|███       | 1456/4716 [05:42<12:31,  4.34it/s]

 31%|███       | 1457/4716 [05:42<12:32,  4.33it/s]

 31%|███       | 1458/4716 [05:42<12:35,  4.31it/s]

 31%|███       | 1459/4716 [05:43<12:34,  4.32it/s]

 31%|███       | 1460/4716 [05:43<12:33,  4.32it/s]

 31%|███       | 1461/4716 [05:43<12:32,  4.33it/s]

 31%|███       | 1462/4716 [05:43<12:33,  4.32it/s]

 31%|███       | 1463/4716 [05:44<12:33,  4.32it/s]

 31%|███       | 1464/4716 [05:44<12:31,  4.33it/s]

 31%|███       | 1465/4716 [05:44<12:31,  4.32it/s]

 31%|███       | 1466/4716 [05:44<12:30,  4.33it/s]

 31%|███       | 1467/4716 [05:45<12:29,  4.33it/s]

 31%|███       | 1468/4716 [05:45<12:30,  4.33it/s]

 31%|███       | 1469/4716 [05:45<12:29,  4.33it/s]

 31%|███       | 1470/4716 [05:45<12:28,  4.34it/s]

 31%|███       | 1471/4716 [05:45<12:29,  4.33it/s]

 31%|███       | 1472/4716 [05:46<12:28,  4.34it/s]

 31%|███       | 1473/4716 [05:46<12:29,  4.33it/s]

 31%|███▏      | 1474/4716 [05:46<12:30,  4.32it/s]

 31%|███▏      | 1475/4716 [05:46<12:29,  4.32it/s]

 31%|███▏      | 1476/4716 [05:47<12:30,  4.32it/s]

 31%|███▏      | 1477/4716 [05:47<12:29,  4.32it/s]

 31%|███▏      | 1478/4716 [05:47<12:30,  4.32it/s]

 31%|███▏      | 1479/4716 [05:47<12:30,  4.32it/s]

 31%|███▏      | 1480/4716 [05:48<12:32,  4.30it/s]

 31%|███▏      | 1481/4716 [05:48<12:30,  4.31it/s]

 31%|███▏      | 1482/4716 [05:48<12:28,  4.32it/s]

 31%|███▏      | 1483/4716 [05:48<12:29,  4.31it/s]

 31%|███▏      | 1484/4716 [05:48<12:29,  4.31it/s]

 31%|███▏      | 1485/4716 [05:49<12:27,  4.32it/s]

 32%|███▏      | 1486/4716 [05:49<12:27,  4.32it/s]

 32%|███▏      | 1487/4716 [05:49<12:30,  4.30it/s]

 32%|███▏      | 1488/4716 [05:49<12:29,  4.31it/s]

 32%|███▏      | 1489/4716 [05:50<12:28,  4.31it/s]

 32%|███▏      | 1490/4716 [05:50<12:25,  4.33it/s]

 32%|███▏      | 1491/4716 [05:50<12:25,  4.32it/s]

 32%|███▏      | 1492/4716 [05:50<12:25,  4.32it/s]

 32%|███▏      | 1493/4716 [05:51<12:25,  4.32it/s]

 32%|███▏      | 1494/4716 [05:51<12:25,  4.32it/s]

 32%|███▏      | 1495/4716 [05:51<12:26,  4.31it/s]

 32%|███▏      | 1496/4716 [05:51<12:24,  4.32it/s]

 32%|███▏      | 1497/4716 [05:52<12:26,  4.31it/s]

 32%|███▏      | 1498/4716 [05:52<12:24,  4.32it/s]

 32%|███▏      | 1499/4716 [05:52<12:25,  4.32it/s]

 32%|███▏      | 1500/4716 [05:52<12:25,  4.31it/s]

 32%|███▏      | 1501/4716 [05:52<12:34,  4.26it/s]

 32%|███▏      | 1502/4716 [05:53<12:31,  4.28it/s]

 32%|███▏      | 1503/4716 [05:53<12:26,  4.30it/s]

 32%|███▏      | 1504/4716 [05:53<12:25,  4.31it/s]

 32%|███▏      | 1505/4716 [05:53<12:24,  4.31it/s]

 32%|███▏      | 1506/4716 [05:54<12:21,  4.33it/s]

 32%|███▏      | 1507/4716 [05:54<12:21,  4.33it/s]

 32%|███▏      | 1508/4716 [05:54<12:21,  4.33it/s]

 32%|███▏      | 1509/4716 [05:54<12:23,  4.32it/s]

 32%|███▏      | 1510/4716 [05:55<12:24,  4.31it/s]

 32%|███▏      | 1511/4716 [05:55<12:22,  4.32it/s]

 32%|███▏      | 1512/4716 [05:55<12:21,  4.32it/s]

 32%|███▏      | 1513/4716 [05:55<12:19,  4.33it/s]

 32%|███▏      | 1514/4716 [05:55<12:17,  4.34it/s]

 32%|███▏      | 1515/4716 [05:56<12:18,  4.34it/s]

 32%|███▏      | 1516/4716 [05:56<12:19,  4.33it/s]

 32%|███▏      | 1517/4716 [05:56<12:17,  4.34it/s]

 32%|███▏      | 1518/4716 [05:56<12:19,  4.33it/s]

 32%|███▏      | 1519/4716 [05:57<12:20,  4.31it/s]

 32%|███▏      | 1520/4716 [05:57<12:19,  4.32it/s]

 32%|███▏      | 1521/4716 [05:57<12:19,  4.32it/s]

 32%|███▏      | 1522/4716 [05:57<12:18,  4.32it/s]

 32%|███▏      | 1523/4716 [05:58<12:20,  4.31it/s]

 32%|███▏      | 1524/4716 [05:58<12:20,  4.31it/s]

 32%|███▏      | 1525/4716 [05:58<12:19,  4.31it/s]

 32%|███▏      | 1526/4716 [05:58<12:19,  4.31it/s]

 32%|███▏      | 1527/4716 [05:58<12:20,  4.31it/s]

 32%|███▏      | 1528/4716 [05:59<12:20,  4.31it/s]

 32%|███▏      | 1529/4716 [05:59<12:20,  4.31it/s]

 32%|███▏      | 1530/4716 [05:59<12:18,  4.31it/s]

 32%|███▏      | 1531/4716 [05:59<12:19,  4.31it/s]

 32%|███▏      | 1532/4716 [06:00<12:17,  4.32it/s]

 33%|███▎      | 1533/4716 [06:00<12:16,  4.32it/s]

 33%|███▎      | 1534/4716 [06:00<12:15,  4.33it/s]

 33%|███▎      | 1535/4716 [06:00<12:15,  4.33it/s]

 33%|███▎      | 1536/4716 [06:01<12:15,  4.32it/s]

 33%|███▎      | 1537/4716 [06:01<12:16,  4.32it/s]

 33%|███▎      | 1538/4716 [06:01<12:15,  4.32it/s]

 33%|███▎      | 1539/4716 [06:01<12:15,  4.32it/s]

 33%|███▎      | 1540/4716 [06:01<12:17,  4.31it/s]

 33%|███▎      | 1541/4716 [06:02<12:16,  4.31it/s]

 33%|███▎      | 1542/4716 [06:02<12:16,  4.31it/s]

 33%|███▎      | 1543/4716 [06:02<12:16,  4.31it/s]

 33%|███▎      | 1544/4716 [06:02<12:15,  4.31it/s]

 33%|███▎      | 1545/4716 [06:03<12:15,  4.31it/s]

 33%|███▎      | 1546/4716 [06:03<12:16,  4.30it/s]

 33%|███▎      | 1547/4716 [06:03<12:16,  4.30it/s]

 33%|███▎      | 1548/4716 [06:03<12:19,  4.29it/s]

 33%|███▎      | 1549/4716 [06:04<12:15,  4.31it/s]

 33%|███▎      | 1550/4716 [06:04<12:14,  4.31it/s]

 33%|███▎      | 1551/4716 [06:04<12:13,  4.32it/s]

 33%|███▎      | 1552/4716 [06:04<12:12,  4.32it/s]

 33%|███▎      | 1553/4716 [06:04<12:12,  4.32it/s]

 33%|███▎      | 1554/4716 [06:05<12:13,  4.31it/s]

 33%|███▎      | 1555/4716 [06:05<12:11,  4.32it/s]

 33%|███▎      | 1556/4716 [06:05<12:10,  4.33it/s]

 33%|███▎      | 1557/4716 [06:05<12:18,  4.28it/s]

 33%|███▎      | 1558/4716 [06:06<12:15,  4.30it/s]

 33%|███▎      | 1559/4716 [06:06<12:12,  4.31it/s]

 33%|███▎      | 1560/4716 [06:06<12:09,  4.32it/s]

 33%|███▎      | 1561/4716 [06:06<12:08,  4.33it/s]

 33%|███▎      | 1562/4716 [06:07<12:07,  4.34it/s]

 33%|███▎      | 1563/4716 [06:07<12:05,  4.35it/s]

 33%|███▎      | 1564/4716 [06:07<12:06,  4.34it/s]

 33%|███▎      | 1565/4716 [06:07<12:07,  4.33it/s]

 33%|███▎      | 1566/4716 [06:07<12:06,  4.33it/s]

 33%|███▎      | 1567/4716 [06:08<12:06,  4.34it/s]

 33%|███▎      | 1568/4716 [06:08<12:05,  4.34it/s]

 33%|███▎      | 1569/4716 [06:08<12:05,  4.34it/s]

 33%|███▎      | 1570/4716 [06:08<12:06,  4.33it/s]

 33%|███▎      | 1571/4716 [06:09<12:05,  4.34it/s]

 33%|███▎      | 1572/4716 [06:09<12:05,  4.33it/s]

 33%|███▎      | 1573/4716 [06:09<12:05,  4.33it/s]

 33%|███▎      | 1574/4716 [06:09<12:06,  4.32it/s]

 33%|███▎      | 1575/4716 [06:10<12:07,  4.32it/s]

 33%|███▎      | 1576/4716 [06:10<12:07,  4.32it/s]

 33%|███▎      | 1577/4716 [06:10<12:06,  4.32it/s]

 33%|███▎      | 1578/4716 [06:10<12:06,  4.32it/s]

 33%|███▎      | 1579/4716 [06:10<12:05,  4.33it/s]

 34%|███▎      | 1580/4716 [06:11<12:07,  4.31it/s]

 34%|███▎      | 1581/4716 [06:11<12:07,  4.31it/s]

 34%|███▎      | 1582/4716 [06:11<12:07,  4.31it/s]

 34%|███▎      | 1583/4716 [06:11<12:05,  4.32it/s]

 34%|███▎      | 1584/4716 [06:12<12:04,  4.32it/s]

 34%|███▎      | 1585/4716 [06:12<12:04,  4.32it/s]

 34%|███▎      | 1586/4716 [06:12<12:04,  4.32it/s]

 34%|███▎      | 1587/4716 [06:12<12:02,  4.33it/s]

 34%|███▎      | 1588/4716 [06:13<12:03,  4.33it/s]

 34%|███▎      | 1589/4716 [06:13<12:01,  4.33it/s]

 34%|███▎      | 1590/4716 [06:13<12:01,  4.33it/s]

 34%|███▎      | 1591/4716 [06:13<12:02,  4.33it/s]

 34%|███▍      | 1592/4716 [06:14<12:02,  4.32it/s]

 34%|███▍      | 1593/4716 [06:14<12:02,  4.32it/s]

 34%|███▍      | 1594/4716 [06:14<12:02,  4.32it/s]

 34%|███▍      | 1595/4716 [06:14<12:01,  4.33it/s]

 34%|███▍      | 1596/4716 [06:14<12:02,  4.32it/s]

 34%|███▍      | 1597/4716 [06:15<12:01,  4.32it/s]

 34%|███▍      | 1598/4716 [06:15<12:02,  4.32it/s]

 34%|███▍      | 1599/4716 [06:15<12:01,  4.32it/s]

 34%|███▍      | 1600/4716 [06:15<12:01,  4.32it/s]

 34%|███▍      | 1601/4716 [06:16<12:00,  4.32it/s]

 34%|███▍      | 1602/4716 [06:16<11:59,  4.33it/s]

 34%|███▍      | 1603/4716 [06:16<11:58,  4.33it/s]

 34%|███▍      | 1604/4716 [06:16<12:00,  4.32it/s]

 34%|███▍      | 1605/4716 [06:17<12:00,  4.32it/s]

 34%|███▍      | 1606/4716 [06:17<12:00,  4.31it/s]

 34%|███▍      | 1607/4716 [06:17<12:01,  4.31it/s]

 34%|███▍      | 1608/4716 [06:17<12:00,  4.32it/s]

 34%|███▍      | 1609/4716 [06:17<11:59,  4.32it/s]

 34%|███▍      | 1610/4716 [06:18<12:01,  4.30it/s]

 34%|███▍      | 1611/4716 [06:18<12:00,  4.31it/s]

 34%|███▍      | 1612/4716 [06:18<12:02,  4.30it/s]

 34%|███▍      | 1613/4716 [06:18<12:01,  4.30it/s]

 34%|███▍      | 1614/4716 [06:19<12:00,  4.31it/s]

 34%|███▍      | 1615/4716 [06:19<11:59,  4.31it/s]

 34%|███▍      | 1616/4716 [06:19<11:58,  4.31it/s]

 34%|███▍      | 1617/4716 [06:19<12:00,  4.30it/s]

 34%|███▍      | 1618/4716 [06:20<11:59,  4.30it/s]

 34%|███▍      | 1619/4716 [06:20<11:59,  4.31it/s]

 34%|███▍      | 1620/4716 [06:20<12:00,  4.30it/s]

 34%|███▍      | 1621/4716 [06:20<11:59,  4.30it/s]

 34%|███▍      | 1622/4716 [06:20<11:58,  4.31it/s]

 34%|███▍      | 1623/4716 [06:21<11:57,  4.31it/s]

 34%|███▍      | 1624/4716 [06:21<11:59,  4.30it/s]

 34%|███▍      | 1625/4716 [06:21<11:59,  4.29it/s]

 34%|███▍      | 1626/4716 [06:21<11:57,  4.31it/s]

 34%|███▍      | 1627/4716 [06:22<11:57,  4.31it/s]

 35%|███▍      | 1628/4716 [06:22<11:56,  4.31it/s]

 35%|███▍      | 1629/4716 [06:22<11:58,  4.30it/s]

 35%|███▍      | 1630/4716 [06:22<11:57,  4.30it/s]

 35%|███▍      | 1631/4716 [06:23<11:56,  4.30it/s]

 35%|███▍      | 1632/4716 [06:23<11:58,  4.30it/s]

 35%|███▍      | 1633/4716 [06:23<11:58,  4.29it/s]

 35%|███▍      | 1634/4716 [06:23<11:56,  4.30it/s]

 35%|███▍      | 1635/4716 [06:23<11:55,  4.31it/s]

 35%|███▍      | 1636/4716 [06:24<11:55,  4.31it/s]

 35%|███▍      | 1637/4716 [06:24<11:55,  4.31it/s]

 35%|███▍      | 1638/4716 [06:24<11:54,  4.31it/s]

 35%|███▍      | 1639/4716 [06:24<11:54,  4.31it/s]

 35%|███▍      | 1640/4716 [06:25<11:56,  4.30it/s]

 35%|███▍      | 1641/4716 [06:25<11:56,  4.29it/s]

 35%|███▍      | 1642/4716 [06:25<11:54,  4.30it/s]

 35%|███▍      | 1643/4716 [06:25<11:53,  4.31it/s]

 35%|███▍      | 1644/4716 [06:26<11:53,  4.30it/s]

 35%|███▍      | 1645/4716 [06:26<11:54,  4.30it/s]

 35%|███▍      | 1646/4716 [06:26<11:53,  4.30it/s]

 35%|███▍      | 1647/4716 [06:26<11:52,  4.31it/s]

 35%|███▍      | 1648/4716 [06:27<11:51,  4.31it/s]

 35%|███▍      | 1649/4716 [06:27<11:52,  4.31it/s]

 35%|███▍      | 1650/4716 [06:27<11:52,  4.30it/s]

 35%|███▌      | 1651/4716 [06:27<11:53,  4.30it/s]

 35%|███▌      | 1652/4716 [06:27<11:53,  4.29it/s]

 35%|███▌      | 1653/4716 [06:28<11:52,  4.30it/s]

 35%|███▌      | 1654/4716 [06:28<11:53,  4.29it/s]

 35%|███▌      | 1655/4716 [06:28<11:52,  4.30it/s]

 35%|███▌      | 1656/4716 [06:28<11:52,  4.30it/s]

 35%|███▌      | 1657/4716 [06:29<11:51,  4.30it/s]

 35%|███▌      | 1658/4716 [06:29<11:54,  4.28it/s]

 35%|███▌      | 1659/4716 [06:29<11:54,  4.28it/s]

 35%|███▌      | 1660/4716 [06:29<11:51,  4.29it/s]

 35%|███▌      | 1661/4716 [06:30<11:52,  4.29it/s]

 35%|███▌      | 1662/4716 [06:30<11:51,  4.29it/s]

 35%|███▌      | 1663/4716 [06:30<11:50,  4.30it/s]

 35%|███▌      | 1664/4716 [06:30<11:52,  4.28it/s]

 35%|███▌      | 1665/4716 [06:30<11:51,  4.29it/s]

 35%|███▌      | 1666/4716 [06:31<11:49,  4.30it/s]

 35%|███▌      | 1667/4716 [06:31<11:48,  4.30it/s]

 35%|███▌      | 1668/4716 [06:31<11:48,  4.30it/s]

 35%|███▌      | 1669/4716 [06:31<11:50,  4.29it/s]

 35%|███▌      | 1670/4716 [06:32<11:48,  4.30it/s]

 35%|███▌      | 1671/4716 [06:32<11:49,  4.29it/s]

 35%|███▌      | 1672/4716 [06:32<11:48,  4.29it/s]

 35%|███▌      | 1673/4716 [06:32<11:53,  4.26it/s]

 35%|███▌      | 1674/4716 [06:33<11:53,  4.26it/s]

 36%|███▌      | 1675/4716 [06:33<11:49,  4.28it/s]

 36%|███▌      | 1676/4716 [06:33<11:50,  4.28it/s]

 36%|███▌      | 1677/4716 [06:33<11:50,  4.28it/s]

 36%|███▌      | 1678/4716 [06:34<11:48,  4.29it/s]

 36%|███▌      | 1679/4716 [06:34<11:47,  4.29it/s]

 36%|███▌      | 1680/4716 [06:34<11:47,  4.29it/s]

 36%|███▌      | 1681/4716 [06:34<11:47,  4.29it/s]

 36%|███▌      | 1682/4716 [06:34<11:47,  4.29it/s]

 36%|███▌      | 1683/4716 [06:35<11:47,  4.29it/s]

 36%|███▌      | 1684/4716 [06:35<11:46,  4.29it/s]

 36%|███▌      | 1685/4716 [06:35<11:45,  4.30it/s]

 36%|███▌      | 1686/4716 [06:35<11:46,  4.29it/s]

 36%|███▌      | 1687/4716 [06:36<11:47,  4.28it/s]

 36%|███▌      | 1688/4716 [06:36<11:46,  4.29it/s]

 36%|███▌      | 1689/4716 [06:36<11:44,  4.30it/s]

 36%|███▌      | 1690/4716 [06:36<11:44,  4.29it/s]

 36%|███▌      | 1691/4716 [06:37<11:46,  4.28it/s]

 36%|███▌      | 1692/4716 [06:37<11:46,  4.28it/s]

 36%|███▌      | 1693/4716 [06:37<11:43,  4.29it/s]

 36%|███▌      | 1694/4716 [06:37<11:43,  4.29it/s]

 36%|███▌      | 1695/4716 [06:37<11:43,  4.29it/s]

 36%|███▌      | 1696/4716 [06:38<11:41,  4.30it/s]

 36%|███▌      | 1697/4716 [06:38<11:42,  4.30it/s]

 36%|███▌      | 1698/4716 [06:38<11:43,  4.29it/s]

 36%|███▌      | 1699/4716 [06:38<11:43,  4.29it/s]

 36%|███▌      | 1700/4716 [06:39<11:44,  4.28it/s]

 36%|███▌      | 1701/4716 [06:39<11:43,  4.28it/s]

 36%|███▌      | 1702/4716 [06:39<11:43,  4.28it/s]

 36%|███▌      | 1703/4716 [06:39<11:42,  4.29it/s]

 36%|███▌      | 1704/4716 [06:40<11:40,  4.30it/s]

 36%|███▌      | 1705/4716 [06:40<11:42,  4.29it/s]

 36%|███▌      | 1706/4716 [06:40<11:40,  4.30it/s]

 36%|███▌      | 1707/4716 [06:40<11:39,  4.30it/s]

 36%|███▌      | 1708/4716 [06:40<11:39,  4.30it/s]

 36%|███▌      | 1709/4716 [06:41<11:37,  4.31it/s]

 36%|███▋      | 1710/4716 [06:41<11:36,  4.32it/s]

 36%|███▋      | 1711/4716 [06:41<11:35,  4.32it/s]

 36%|███▋      | 1712/4716 [06:41<11:37,  4.31it/s]

 36%|███▋      | 1713/4716 [06:42<11:38,  4.30it/s]

 36%|███▋      | 1714/4716 [06:42<11:37,  4.30it/s]

 36%|███▋      | 1715/4716 [06:42<11:37,  4.30it/s]

 36%|███▋      | 1716/4716 [06:42<11:39,  4.29it/s]

 36%|███▋      | 1717/4716 [06:43<11:38,  4.29it/s]

 36%|███▋      | 1718/4716 [06:43<11:38,  4.29it/s]

 36%|███▋      | 1719/4716 [06:43<11:38,  4.29it/s]

 36%|███▋      | 1720/4716 [06:43<11:39,  4.28it/s]

 36%|███▋      | 1721/4716 [06:44<11:39,  4.28it/s]

 37%|███▋      | 1722/4716 [06:44<11:40,  4.27it/s]

 37%|███▋      | 1723/4716 [06:44<11:41,  4.27it/s]

 37%|███▋      | 1724/4716 [06:44<11:39,  4.28it/s]

 37%|███▋      | 1725/4716 [06:44<11:38,  4.28it/s]

 37%|███▋      | 1726/4716 [06:45<11:38,  4.28it/s]

 37%|███▋      | 1727/4716 [06:45<11:39,  4.27it/s]

 37%|███▋      | 1728/4716 [06:45<11:40,  4.27it/s]

 37%|███▋      | 1729/4716 [06:45<11:39,  4.27it/s]

 37%|███▋      | 1730/4716 [06:46<11:39,  4.27it/s]

 37%|███▋      | 1731/4716 [06:46<11:40,  4.26it/s]

 37%|███▋      | 1732/4716 [06:46<11:38,  4.27it/s]

 37%|███▋      | 1733/4716 [06:46<11:38,  4.27it/s]

 37%|███▋      | 1734/4716 [06:47<11:38,  4.27it/s]

 37%|███▋      | 1735/4716 [06:47<11:37,  4.27it/s]

 37%|███▋      | 1736/4716 [06:47<11:38,  4.27it/s]

 37%|███▋      | 1737/4716 [06:47<11:37,  4.27it/s]

 37%|███▋      | 1738/4716 [06:47<11:37,  4.27it/s]

 37%|███▋      | 1739/4716 [06:48<11:37,  4.27it/s]

 37%|███▋      | 1740/4716 [06:48<11:37,  4.27it/s]

 37%|███▋      | 1741/4716 [06:48<11:35,  4.28it/s]

 37%|███▋      | 1742/4716 [06:48<11:34,  4.29it/s]

 37%|███▋      | 1743/4716 [06:49<11:33,  4.28it/s]

 37%|███▋      | 1744/4716 [06:49<11:34,  4.28it/s]

 37%|███▋      | 1745/4716 [06:49<11:33,  4.28it/s]

 37%|███▋      | 1746/4716 [06:49<11:34,  4.28it/s]

 37%|███▋      | 1747/4716 [06:50<11:32,  4.29it/s]

 37%|███▋      | 1748/4716 [06:50<11:32,  4.28it/s]

 37%|███▋      | 1749/4716 [06:50<11:33,  4.28it/s]

 37%|███▋      | 1750/4716 [06:50<11:33,  4.28it/s]

 37%|███▋      | 1751/4716 [06:51<11:33,  4.28it/s]

 37%|███▋      | 1752/4716 [06:51<11:31,  4.28it/s]

 37%|███▋      | 1753/4716 [06:51<11:31,  4.29it/s]

 37%|███▋      | 1754/4716 [06:51<11:34,  4.27it/s]

 37%|███▋      | 1755/4716 [06:51<11:32,  4.28it/s]

 37%|███▋      | 1756/4716 [06:52<11:33,  4.27it/s]

 37%|███▋      | 1757/4716 [06:52<11:31,  4.28it/s]

 37%|███▋      | 1758/4716 [06:52<11:32,  4.27it/s]

 37%|███▋      | 1759/4716 [06:52<11:40,  4.22it/s]

 37%|███▋      | 1760/4716 [06:53<11:36,  4.24it/s]

 37%|███▋      | 1761/4716 [06:53<11:36,  4.24it/s]

 37%|███▋      | 1762/4716 [06:53<11:34,  4.26it/s]

 37%|███▋      | 1763/4716 [06:53<11:31,  4.27it/s]

 37%|███▋      | 1764/4716 [06:54<11:31,  4.27it/s]

 37%|███▋      | 1765/4716 [06:54<11:29,  4.28it/s]

 37%|███▋      | 1766/4716 [06:54<11:35,  4.24it/s]

 37%|███▋      | 1767/4716 [06:54<11:43,  4.19it/s]

 37%|███▋      | 1768/4716 [06:55<11:39,  4.21it/s]

 38%|███▊      | 1769/4716 [06:55<11:38,  4.22it/s]

 38%|███▊      | 1770/4716 [06:55<11:35,  4.23it/s]

 38%|███▊      | 1771/4716 [06:55<11:34,  4.24it/s]

 38%|███▊      | 1772/4716 [06:55<11:32,  4.25it/s]

 38%|███▊      | 1773/4716 [06:56<11:32,  4.25it/s]

 38%|███▊      | 1774/4716 [06:56<11:32,  4.25it/s]

 38%|███▊      | 1775/4716 [06:56<11:31,  4.25it/s]

 38%|███▊      | 1776/4716 [06:56<11:30,  4.25it/s]

 38%|███▊      | 1777/4716 [06:57<11:30,  4.26it/s]

 38%|███▊      | 1778/4716 [06:57<11:29,  4.26it/s]

 38%|███▊      | 1779/4716 [06:57<11:37,  4.21it/s]

 38%|███▊      | 1780/4716 [06:57<11:55,  4.10it/s]

 38%|███▊      | 1781/4716 [06:58<11:47,  4.15it/s]

 38%|███▊      | 1782/4716 [06:58<11:41,  4.18it/s]

 38%|███▊      | 1783/4716 [06:58<11:37,  4.21it/s]

 38%|███▊      | 1784/4716 [06:58<11:33,  4.23it/s]

 38%|███▊      | 1785/4716 [06:59<11:30,  4.25it/s]

 38%|███▊      | 1786/4716 [06:59<11:29,  4.25it/s]

 38%|███▊      | 1787/4716 [06:59<11:30,  4.24it/s]

 38%|███▊      | 1788/4716 [06:59<11:29,  4.24it/s]

 38%|███▊      | 1789/4716 [07:00<11:27,  4.26it/s]

 38%|███▊      | 1790/4716 [07:00<11:29,  4.24it/s]

 38%|███▊      | 1791/4716 [07:00<11:29,  4.24it/s]

 38%|███▊      | 1792/4716 [07:00<11:27,  4.25it/s]

 38%|███▊      | 1793/4716 [07:00<11:27,  4.25it/s]

 38%|███▊      | 1794/4716 [07:01<11:26,  4.25it/s]

 38%|███▊      | 1795/4716 [07:01<11:28,  4.24it/s]

 38%|███▊      | 1796/4716 [07:01<11:26,  4.25it/s]

 38%|███▊      | 1797/4716 [07:01<11:26,  4.25it/s]

 38%|███▊      | 1798/4716 [07:02<11:27,  4.24it/s]

 38%|███▊      | 1799/4716 [07:02<11:26,  4.25it/s]

 38%|███▊      | 1800/4716 [07:02<11:26,  4.25it/s]

 38%|███▊      | 1801/4716 [07:02<11:26,  4.25it/s]

 38%|███▊      | 1802/4716 [07:03<11:26,  4.24it/s]

 38%|███▊      | 1803/4716 [07:03<11:26,  4.24it/s]

 38%|███▊      | 1804/4716 [07:03<11:24,  4.25it/s]

 38%|███▊      | 1805/4716 [07:03<11:27,  4.24it/s]

 38%|███▊      | 1806/4716 [07:04<11:27,  4.23it/s]

 38%|███▊      | 1807/4716 [07:04<11:27,  4.23it/s]

 38%|███▊      | 1808/4716 [07:04<11:26,  4.24it/s]

 38%|███▊      | 1809/4716 [07:04<11:25,  4.24it/s]

 38%|███▊      | 1810/4716 [07:04<11:24,  4.25it/s]

 38%|███▊      | 1811/4716 [07:05<11:26,  4.23it/s]

 38%|███▊      | 1812/4716 [07:05<11:26,  4.23it/s]

 38%|███▊      | 1813/4716 [07:05<11:25,  4.24it/s]

 38%|███▊      | 1814/4716 [07:05<11:23,  4.25it/s]

 38%|███▊      | 1815/4716 [07:06<11:24,  4.24it/s]

 39%|███▊      | 1816/4716 [07:06<11:25,  4.23it/s]

 39%|███▊      | 1817/4716 [07:06<11:24,  4.23it/s]

 39%|███▊      | 1818/4716 [07:06<11:26,  4.22it/s]

 39%|███▊      | 1819/4716 [07:07<11:24,  4.23it/s]

 39%|███▊      | 1820/4716 [07:07<11:25,  4.22it/s]

 39%|███▊      | 1821/4716 [07:07<11:24,  4.23it/s]

 39%|███▊      | 1822/4716 [07:07<11:30,  4.19it/s]

 39%|███▊      | 1823/4716 [07:08<11:27,  4.21it/s]

 39%|███▊      | 1824/4716 [07:08<11:23,  4.23it/s]

 39%|███▊      | 1825/4716 [07:08<11:23,  4.23it/s]

 39%|███▊      | 1826/4716 [07:08<11:22,  4.23it/s]

 39%|███▊      | 1827/4716 [07:08<11:20,  4.24it/s]

 39%|███▉      | 1828/4716 [07:09<11:21,  4.24it/s]

 39%|███▉      | 1829/4716 [07:09<11:22,  4.23it/s]

 39%|███▉      | 1830/4716 [07:09<11:21,  4.23it/s]

 39%|███▉      | 1831/4716 [07:09<11:20,  4.24it/s]

 39%|███▉      | 1832/4716 [07:10<11:18,  4.25it/s]

 39%|███▉      | 1833/4716 [07:10<11:20,  4.24it/s]

 39%|███▉      | 1834/4716 [07:10<11:21,  4.23it/s]

 39%|███▉      | 1835/4716 [07:10<11:17,  4.25it/s]

 39%|███▉      | 1836/4716 [07:11<11:18,  4.24it/s]

 39%|███▉      | 1837/4716 [07:11<11:19,  4.24it/s]

 39%|███▉      | 1838/4716 [07:11<11:19,  4.24it/s]

 39%|███▉      | 1839/4716 [07:11<11:19,  4.23it/s]

 39%|███▉      | 1840/4716 [07:12<11:18,  4.24it/s]

 39%|███▉      | 1841/4716 [07:12<11:17,  4.24it/s]

 39%|███▉      | 1842/4716 [07:12<11:17,  4.24it/s]

 39%|███▉      | 1843/4716 [07:12<11:16,  4.25it/s]

 39%|███▉      | 1844/4716 [07:12<11:16,  4.25it/s]

 39%|███▉      | 1845/4716 [07:13<11:15,  4.25it/s]

 39%|███▉      | 1846/4716 [07:13<11:15,  4.25it/s]

 39%|███▉      | 1847/4716 [07:13<11:16,  4.24it/s]

 39%|███▉      | 1848/4716 [07:13<11:13,  4.26it/s]

 39%|███▉      | 1849/4716 [07:14<11:13,  4.25it/s]

 39%|███▉      | 1850/4716 [07:14<11:13,  4.26it/s]

 39%|███▉      | 1851/4716 [07:14<11:15,  4.24it/s]

 39%|███▉      | 1852/4716 [07:14<11:15,  4.24it/s]

 39%|███▉      | 1853/4716 [07:15<11:14,  4.25it/s]

 39%|███▉      | 1854/4716 [07:15<11:14,  4.24it/s]

 39%|███▉      | 1855/4716 [07:15<11:14,  4.24it/s]

 39%|███▉      | 1856/4716 [07:15<11:12,  4.25it/s]

 39%|███▉      | 1857/4716 [07:16<11:12,  4.25it/s]

 39%|███▉      | 1858/4716 [07:16<11:11,  4.25it/s]

 39%|███▉      | 1859/4716 [07:16<11:11,  4.26it/s]

 39%|███▉      | 1860/4716 [07:16<11:11,  4.25it/s]

 39%|███▉      | 1861/4716 [07:16<11:12,  4.25it/s]

 39%|███▉      | 1862/4716 [07:17<11:12,  4.24it/s]

 40%|███▉      | 1863/4716 [07:17<11:11,  4.25it/s]

 40%|███▉      | 1864/4716 [07:17<11:10,  4.25it/s]

 40%|███▉      | 1865/4716 [07:17<11:10,  4.25it/s]

 40%|███▉      | 1866/4716 [07:18<11:09,  4.26it/s]

 40%|███▉      | 1867/4716 [07:18<11:09,  4.25it/s]

 40%|███▉      | 1868/4716 [07:18<11:08,  4.26it/s]

 40%|███▉      | 1869/4716 [07:18<11:09,  4.25it/s]

 40%|███▉      | 1870/4716 [07:19<11:08,  4.26it/s]

 40%|███▉      | 1871/4716 [07:19<11:10,  4.25it/s]

 40%|███▉      | 1872/4716 [07:19<11:11,  4.23it/s]

 40%|███▉      | 1873/4716 [07:19<11:11,  4.24it/s]

 40%|███▉      | 1874/4716 [07:20<11:10,  4.24it/s]

 40%|███▉      | 1875/4716 [07:20<11:09,  4.24it/s]

 40%|███▉      | 1876/4716 [07:20<11:09,  4.24it/s]

 40%|███▉      | 1877/4716 [07:20<11:12,  4.22it/s]

logging
logging the anndata

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 40%|███▉      | 1878/4716 [07:22<30:01,  1.58it/s]

 40%|███▉      | 1879/4716 [07:22<24:21,  1.94it/s]

 40%|███▉      | 1880/4716 [07:22<20:17,  2.33it/s]

 40%|███▉      | 1881/4716 [07:23<17:26,  2.71it/s]

 40%|███▉      | 1882/4716 [07:23<15:26,  3.06it/s]

 40%|███▉      | 1883/4716 [07:23<14:01,  3.37it/s]

 40%|███▉      | 1884/4716 [07:23<13:03,  3.61it/s]

 40%|███▉      | 1885/4716 [07:23<12:24,  3.80it/s]

 40%|███▉      | 1886/4716 [07:24<11:55,  3.95it/s]

 40%|████      | 1887/4716 [07:24<11:36,  4.06it/s]

 40%|████      | 1888/4716 [07:24<11:22,  4.15it/s]

 40%|████      | 1889/4716 [07:24<11:12,  4.21it/s]

 40%|████      | 1890/4716 [07:25<11:04,  4.25it/s]

 40%|████      | 1891/4716 [07:25<10:58,  4.29it/s]

 40%|████      | 1892/4716 [07:25<10:54,  4.32it/s]

 40%|████      | 1893/4716 [07:25<10:51,  4.33it/s]

 40%|████      | 1894/4716 [07:25<10:50,  4.34it/s]

 40%|████      | 1895/4716 [07:26<10:49,  4.34it/s]

 40%|████      | 1896/4716 [07:26<10:48,  4.35it/s]

 40%|████      | 1897/4716 [07:26<10:48,  4.35it/s]

 40%|████      | 1898/4716 [07:26<10:48,  4.35it/s]

 40%|████      | 1899/4716 [07:27<10:46,  4.35it/s]

 40%|████      | 1900/4716 [07:27<10:45,  4.36it/s]

 40%|████      | 1901/4716 [07:27<10:45,  4.36it/s]

 40%|████      | 1902/4716 [07:27<10:44,  4.36it/s]

 40%|████      | 1903/4716 [07:28<10:44,  4.36it/s]

 40%|████      | 1904/4716 [07:28<10:47,  4.34it/s]

 40%|████      | 1905/4716 [07:28<10:48,  4.34it/s]

 40%|████      | 1906/4716 [07:28<10:46,  4.35it/s]

 40%|████      | 1907/4716 [07:28<10:46,  4.34it/s]

 40%|████      | 1908/4716 [07:29<10:45,  4.35it/s]

 40%|████      | 1909/4716 [07:29<10:45,  4.35it/s]

 41%|████      | 1910/4716 [07:29<10:43,  4.36it/s]

 41%|████      | 1911/4716 [07:29<10:45,  4.35it/s]

 41%|████      | 1912/4716 [07:30<10:45,  4.34it/s]

 41%|████      | 1913/4716 [07:30<10:44,  4.35it/s]

 41%|████      | 1914/4716 [07:30<10:44,  4.35it/s]

 41%|████      | 1915/4716 [07:30<10:46,  4.33it/s]

 41%|████      | 1916/4716 [07:31<10:44,  4.34it/s]

 41%|████      | 1917/4716 [07:31<10:45,  4.34it/s]

 41%|████      | 1918/4716 [07:31<10:43,  4.34it/s]

 41%|████      | 1919/4716 [07:31<10:42,  4.35it/s]

 41%|████      | 1920/4716 [07:31<10:42,  4.35it/s]

 41%|████      | 1921/4716 [07:32<10:40,  4.36it/s]

 41%|████      | 1922/4716 [07:32<10:42,  4.35it/s]

 41%|████      | 1923/4716 [07:32<10:42,  4.35it/s]

 41%|████      | 1924/4716 [07:32<10:44,  4.34it/s]

 41%|████      | 1925/4716 [07:33<10:44,  4.33it/s]

 41%|████      | 1926/4716 [07:33<10:43,  4.33it/s]

 41%|████      | 1927/4716 [07:33<10:42,  4.34it/s]

 41%|████      | 1928/4716 [07:33<10:42,  4.34it/s]

 41%|████      | 1929/4716 [07:34<10:41,  4.35it/s]

 41%|████      | 1930/4716 [07:34<10:39,  4.35it/s]

 41%|████      | 1931/4716 [07:34<10:40,  4.35it/s]

 41%|████      | 1932/4716 [07:34<10:42,  4.34it/s]

 41%|████      | 1933/4716 [07:34<10:42,  4.33it/s]

 41%|████      | 1934/4716 [07:35<10:40,  4.34it/s]

 41%|████      | 1935/4716 [07:35<10:41,  4.34it/s]

 41%|████      | 1936/4716 [07:35<10:41,  4.33it/s]

 41%|████      | 1937/4716 [07:35<10:40,  4.34it/s]

 41%|████      | 1938/4716 [07:36<10:39,  4.34it/s]

 41%|████      | 1939/4716 [07:36<10:39,  4.34it/s]

 41%|████      | 1940/4716 [07:36<10:37,  4.36it/s]

 41%|████      | 1941/4716 [07:36<10:36,  4.36it/s]

 41%|████      | 1942/4716 [07:37<10:37,  4.35it/s]

 41%|████      | 1943/4716 [07:37<10:38,  4.34it/s]

 41%|████      | 1944/4716 [07:37<10:38,  4.34it/s]

 41%|████      | 1945/4716 [07:37<10:36,  4.35it/s]

 41%|████▏     | 1946/4716 [07:37<10:38,  4.34it/s]

 41%|████▏     | 1947/4716 [07:38<10:36,  4.35it/s]

 41%|████▏     | 1948/4716 [07:38<10:35,  4.36it/s]

 41%|████▏     | 1949/4716 [07:38<10:36,  4.35it/s]

 41%|████▏     | 1950/4716 [07:38<10:35,  4.35it/s]

 41%|████▏     | 1951/4716 [07:39<10:35,  4.35it/s]

 41%|████▏     | 1952/4716 [07:39<10:35,  4.35it/s]

 41%|████▏     | 1953/4716 [07:39<10:35,  4.35it/s]

 41%|████▏     | 1954/4716 [07:39<10:34,  4.35it/s]

 41%|████▏     | 1955/4716 [07:40<10:33,  4.36it/s]

 41%|████▏     | 1956/4716 [07:40<10:35,  4.34it/s]

 41%|████▏     | 1957/4716 [07:40<10:34,  4.35it/s]

 42%|████▏     | 1958/4716 [07:40<10:34,  4.35it/s]

 42%|████▏     | 1959/4716 [07:40<10:34,  4.35it/s]

 42%|████▏     | 1960/4716 [07:41<10:35,  4.34it/s]

 42%|████▏     | 1961/4716 [07:41<10:34,  4.34it/s]

 42%|████▏     | 1962/4716 [07:41<10:33,  4.34it/s]

 42%|████▏     | 1963/4716 [07:41<10:34,  4.34it/s]

 42%|████▏     | 1964/4716 [07:42<10:32,  4.35it/s]

 42%|████▏     | 1965/4716 [07:42<10:39,  4.30it/s]

 42%|████▏     | 1966/4716 [07:42<15:20,  2.99it/s]

 42%|████▏     | 1967/4716 [07:43<13:52,  3.30it/s]

 42%|████▏     | 1968/4716 [07:43<12:52,  3.56it/s]

 42%|████▏     | 1969/4716 [07:43<12:09,  3.77it/s]

 42%|████▏     | 1970/4716 [07:43<11:39,  3.92it/s]

 42%|████▏     | 1971/4716 [07:44<11:18,  4.05it/s]

 42%|████▏     | 1972/4716 [07:44<11:03,  4.14it/s]

 42%|████▏     | 1973/4716 [07:44<11:12,  4.08it/s]

 42%|████▏     | 1974/4716 [07:44<10:59,  4.16it/s]

 42%|████▏     | 1975/4716 [07:44<10:50,  4.21it/s]

 42%|████▏     | 1976/4716 [07:45<10:44,  4.25it/s]

 42%|████▏     | 1977/4716 [07:45<10:39,  4.28it/s]

 42%|████▏     | 1978/4716 [07:45<10:35,  4.31it/s]

 42%|████▏     | 1979/4716 [07:45<10:40,  4.27it/s]

 42%|████▏     | 1980/4716 [07:46<10:36,  4.30it/s]

 42%|████▏     | 1981/4716 [07:46<10:36,  4.30it/s]

 42%|████▏     | 1982/4716 [07:46<10:33,  4.31it/s]

 42%|████▏     | 1983/4716 [07:46<10:32,  4.32it/s]

 42%|████▏     | 1984/4716 [07:47<10:30,  4.34it/s]

 42%|████▏     | 1985/4716 [07:47<10:30,  4.33it/s]

 42%|████▏     | 1986/4716 [07:47<10:30,  4.33it/s]

 42%|████▏     | 1987/4716 [07:47<10:32,  4.32it/s]

 42%|████▏     | 1988/4716 [07:47<10:31,  4.32it/s]

 42%|████▏     | 1989/4716 [07:48<10:31,  4.32it/s]

 42%|████▏     | 1990/4716 [07:48<10:28,  4.33it/s]

 42%|████▏     | 1991/4716 [07:48<10:29,  4.33it/s]

 42%|████▏     | 1992/4716 [07:48<10:28,  4.33it/s]

 42%|████▏     | 1993/4716 [07:49<10:27,  4.34it/s]

 42%|████▏     | 1994/4716 [07:49<10:26,  4.34it/s]

 42%|████▏     | 1995/4716 [07:49<10:26,  4.35it/s]

 42%|████▏     | 1996/4716 [07:49<10:25,  4.35it/s]

 42%|████▏     | 1997/4716 [07:50<10:25,  4.35it/s]

 42%|████▏     | 1998/4716 [07:50<10:24,  4.35it/s]

 42%|████▏     | 1999/4716 [07:50<10:23,  4.36it/s]

 42%|████▏     | 2000/4716 [07:50<10:24,  4.35it/s]

 42%|████▏     | 2001/4716 [07:50<10:23,  4.36it/s]

 42%|████▏     | 2002/4716 [07:51<10:23,  4.36it/s]

 42%|████▏     | 2003/4716 [07:51<10:22,  4.36it/s]

 42%|████▏     | 2004/4716 [07:51<10:21,  4.36it/s]

 43%|████▎     | 2005/4716 [07:51<10:21,  4.36it/s]

 43%|████▎     | 2006/4716 [07:52<10:22,  4.36it/s]

 43%|████▎     | 2007/4716 [07:52<10:22,  4.35it/s]

 43%|████▎     | 2008/4716 [07:52<10:22,  4.35it/s]

 43%|████▎     | 2009/4716 [07:52<10:22,  4.35it/s]

 43%|████▎     | 2010/4716 [07:53<10:22,  4.35it/s]

 43%|████▎     | 2011/4716 [07:53<10:23,  4.34it/s]

 43%|████▎     | 2012/4716 [07:53<10:22,  4.35it/s]

 43%|████▎     | 2013/4716 [07:53<10:22,  4.34it/s]

 43%|████▎     | 2014/4716 [07:53<10:22,  4.34it/s]

 43%|████▎     | 2015/4716 [07:54<10:22,  4.34it/s]

 43%|████▎     | 2016/4716 [07:54<10:23,  4.33it/s]

 43%|████▎     | 2017/4716 [07:54<10:22,  4.34it/s]

 43%|████▎     | 2018/4716 [07:54<10:23,  4.33it/s]

 43%|████▎     | 2019/4716 [07:55<10:23,  4.33it/s]

 43%|████▎     | 2020/4716 [07:55<10:24,  4.32it/s]

 43%|████▎     | 2021/4716 [07:55<10:23,  4.32it/s]

 43%|████▎     | 2022/4716 [07:55<10:23,  4.32it/s]

 43%|████▎     | 2023/4716 [07:56<10:23,  4.32it/s]

 43%|████▎     | 2024/4716 [07:56<10:22,  4.32it/s]

 43%|████▎     | 2025/4716 [07:56<10:21,  4.33it/s]

 43%|████▎     | 2026/4716 [07:56<10:21,  4.33it/s]

 43%|████▎     | 2027/4716 [07:56<10:21,  4.33it/s]

 43%|████▎     | 2028/4716 [07:57<10:20,  4.33it/s]

 43%|████▎     | 2029/4716 [07:57<10:19,  4.33it/s]

 43%|████▎     | 2030/4716 [07:57<10:19,  4.33it/s]

 43%|████▎     | 2031/4716 [07:57<10:20,  4.33it/s]

 43%|████▎     | 2032/4716 [07:58<10:20,  4.32it/s]

 43%|████▎     | 2033/4716 [07:58<10:19,  4.33it/s]

 43%|████▎     | 2034/4716 [07:58<10:18,  4.33it/s]

 43%|████▎     | 2035/4716 [07:58<10:18,  4.33it/s]

 43%|████▎     | 2036/4716 [07:59<10:18,  4.33it/s]

 43%|████▎     | 2037/4716 [07:59<10:20,  4.32it/s]

 43%|████▎     | 2038/4716 [07:59<10:18,  4.33it/s]

 43%|████▎     | 2039/4716 [07:59<10:18,  4.33it/s]

 43%|████▎     | 2040/4716 [07:59<10:18,  4.32it/s]

 43%|████▎     | 2041/4716 [08:00<10:18,  4.33it/s]

 43%|████▎     | 2042/4716 [08:00<10:18,  4.32it/s]

 43%|████▎     | 2043/4716 [08:00<10:17,  4.33it/s]

 43%|████▎     | 2044/4716 [08:00<10:19,  4.31it/s]

 43%|████▎     | 2045/4716 [08:01<10:19,  4.31it/s]

 43%|████▎     | 2046/4716 [08:01<10:17,  4.32it/s]

 43%|████▎     | 2047/4716 [08:01<10:17,  4.33it/s]

 43%|████▎     | 2048/4716 [08:01<10:17,  4.32it/s]

 43%|████▎     | 2049/4716 [08:02<10:16,  4.32it/s]

 43%|████▎     | 2050/4716 [08:02<10:16,  4.33it/s]

 43%|████▎     | 2051/4716 [08:02<10:17,  4.32it/s]

 44%|████▎     | 2052/4716 [08:02<10:15,  4.33it/s]

 44%|████▎     | 2053/4716 [08:02<10:15,  4.32it/s]

 44%|████▎     | 2054/4716 [08:03<10:14,  4.33it/s]

 44%|████▎     | 2055/4716 [08:03<10:13,  4.33it/s]

 44%|████▎     | 2056/4716 [08:03<10:14,  4.33it/s]

 44%|████▎     | 2057/4716 [08:03<10:12,  4.34it/s]

 44%|████▎     | 2058/4716 [08:04<10:12,  4.34it/s]

 44%|████▎     | 2059/4716 [08:04<10:14,  4.32it/s]

 44%|████▎     | 2060/4716 [08:04<10:14,  4.32it/s]

 44%|████▎     | 2061/4716 [08:04<10:13,  4.33it/s]

 44%|████▎     | 2062/4716 [08:05<10:12,  4.33it/s]

 44%|████▎     | 2063/4716 [08:05<10:11,  4.34it/s]

 44%|████▍     | 2064/4716 [08:05<10:11,  4.33it/s]

 44%|████▍     | 2065/4716 [08:05<10:10,  4.34it/s]

 44%|████▍     | 2066/4716 [08:05<10:10,  4.34it/s]

 44%|████▍     | 2067/4716 [08:06<10:10,  4.34it/s]

 44%|████▍     | 2068/4716 [08:06<10:10,  4.34it/s]

 44%|████▍     | 2069/4716 [08:06<10:11,  4.33it/s]

 44%|████▍     | 2070/4716 [08:06<10:10,  4.33it/s]

 44%|████▍     | 2071/4716 [08:07<10:11,  4.33it/s]

 44%|████▍     | 2072/4716 [08:07<10:11,  4.33it/s]

 44%|████▍     | 2073/4716 [08:07<10:10,  4.33it/s]

 44%|████▍     | 2074/4716 [08:07<10:11,  4.32it/s]

 44%|████▍     | 2075/4716 [08:08<10:12,  4.31it/s]

 44%|████▍     | 2076/4716 [08:08<10:12,  4.31it/s]

 44%|████▍     | 2077/4716 [08:08<10:11,  4.31it/s]

 44%|████▍     | 2078/4716 [08:08<10:11,  4.32it/s]

 44%|████▍     | 2079/4716 [08:09<10:10,  4.32it/s]

 44%|████▍     | 2080/4716 [08:09<10:09,  4.32it/s]

 44%|████▍     | 2081/4716 [08:09<10:08,  4.33it/s]

 44%|████▍     | 2082/4716 [08:09<10:10,  4.32it/s]

 44%|████▍     | 2083/4716 [08:09<10:10,  4.31it/s]

 44%|████▍     | 2084/4716 [08:10<10:09,  4.32it/s]

 44%|████▍     | 2085/4716 [08:10<10:09,  4.32it/s]

 44%|████▍     | 2086/4716 [08:10<10:08,  4.32it/s]

 44%|████▍     | 2087/4716 [08:10<10:07,  4.33it/s]

 44%|████▍     | 2088/4716 [08:11<10:08,  4.32it/s]

 44%|████▍     | 2089/4716 [08:11<10:08,  4.31it/s]

 44%|████▍     | 2090/4716 [08:11<10:08,  4.31it/s]

 44%|████▍     | 2091/4716 [08:11<10:07,  4.32it/s]

 44%|████▍     | 2092/4716 [08:12<10:07,  4.32it/s]

 44%|████▍     | 2093/4716 [08:12<10:08,  4.31it/s]

 44%|████▍     | 2094/4716 [08:12<10:07,  4.32it/s]

 44%|████▍     | 2095/4716 [08:12<10:06,  4.32it/s]

 44%|████▍     | 2096/4716 [08:12<10:06,  4.32it/s]

 44%|████▍     | 2097/4716 [08:13<10:06,  4.32it/s]

 44%|████▍     | 2098/4716 [08:13<10:06,  4.32it/s]

 45%|████▍     | 2099/4716 [08:13<10:09,  4.29it/s]

 45%|████▍     | 2100/4716 [08:13<10:06,  4.31it/s]

 45%|████▍     | 2101/4716 [08:14<10:06,  4.31it/s]

 45%|████▍     | 2102/4716 [08:14<10:06,  4.31it/s]

 45%|████▍     | 2103/4716 [08:14<10:05,  4.32it/s]

 45%|████▍     | 2104/4716 [08:14<10:05,  4.31it/s]

 45%|████▍     | 2105/4716 [08:15<10:03,  4.33it/s]

 45%|████▍     | 2106/4716 [08:15<10:03,  4.32it/s]

 45%|████▍     | 2107/4716 [08:15<10:03,  4.32it/s]

 45%|████▍     | 2108/4716 [08:15<10:02,  4.33it/s]

 45%|████▍     | 2109/4716 [08:15<10:02,  4.33it/s]

 45%|████▍     | 2110/4716 [08:16<10:02,  4.33it/s]

 45%|████▍     | 2111/4716 [08:16<10:01,  4.33it/s]

 45%|████▍     | 2112/4716 [08:16<10:01,  4.33it/s]

 45%|████▍     | 2113/4716 [08:16<10:02,  4.32it/s]

 45%|████▍     | 2114/4716 [08:17<10:01,  4.33it/s]

 45%|████▍     | 2115/4716 [08:17<10:02,  4.31it/s]

 45%|████▍     | 2116/4716 [08:17<10:02,  4.32it/s]

 45%|████▍     | 2117/4716 [08:17<10:00,  4.32it/s]

 45%|████▍     | 2118/4716 [08:18<10:00,  4.32it/s]

 45%|████▍     | 2119/4716 [08:18<10:00,  4.33it/s]

 45%|████▍     | 2120/4716 [08:18<10:00,  4.32it/s]

 45%|████▍     | 2121/4716 [08:18<10:01,  4.31it/s]

 45%|████▍     | 2122/4716 [08:18<10:00,  4.32it/s]

 45%|████▌     | 2123/4716 [08:19<09:59,  4.33it/s]

 45%|████▌     | 2124/4716 [08:19<09:59,  4.33it/s]

 45%|████▌     | 2125/4716 [08:19<10:08,  4.26it/s]

 45%|████▌     | 2126/4716 [08:19<10:06,  4.27it/s]

 45%|████▌     | 2127/4716 [08:20<10:03,  4.29it/s]

 45%|████▌     | 2128/4716 [08:20<10:01,  4.30it/s]

 45%|████▌     | 2129/4716 [08:20<10:00,  4.31it/s]

 45%|████▌     | 2130/4716 [08:20<09:59,  4.32it/s]

 45%|████▌     | 2131/4716 [08:21<09:59,  4.31it/s]

 45%|████▌     | 2132/4716 [08:21<09:59,  4.31it/s]

 45%|████▌     | 2133/4716 [08:21<09:58,  4.31it/s]

 45%|████▌     | 2134/4716 [08:21<09:59,  4.31it/s]

 45%|████▌     | 2135/4716 [08:21<09:59,  4.31it/s]

 45%|████▌     | 2136/4716 [08:22<09:59,  4.31it/s]

 45%|████▌     | 2137/4716 [08:22<09:58,  4.31it/s]

 45%|████▌     | 2138/4716 [08:22<09:56,  4.32it/s]

 45%|████▌     | 2139/4716 [08:22<09:56,  4.32it/s]

 45%|████▌     | 2140/4716 [08:23<09:55,  4.33it/s]

 45%|████▌     | 2141/4716 [08:23<09:54,  4.33it/s]

 45%|████▌     | 2142/4716 [08:23<09:54,  4.33it/s]

 45%|████▌     | 2143/4716 [08:23<09:54,  4.33it/s]

 45%|████▌     | 2144/4716 [08:24<09:53,  4.33it/s]

 45%|████▌     | 2145/4716 [08:24<09:53,  4.33it/s]

 46%|████▌     | 2146/4716 [08:24<09:53,  4.33it/s]

 46%|████▌     | 2147/4716 [08:24<09:55,  4.32it/s]

 46%|████▌     | 2148/4716 [08:24<09:55,  4.31it/s]

 46%|████▌     | 2149/4716 [08:25<09:53,  4.32it/s]

 46%|████▌     | 2150/4716 [08:25<09:54,  4.32it/s]

 46%|████▌     | 2151/4716 [08:25<09:53,  4.32it/s]

 46%|████▌     | 2152/4716 [08:25<09:53,  4.32it/s]

 46%|████▌     | 2153/4716 [08:26<09:56,  4.30it/s]

 46%|████▌     | 2154/4716 [08:26<09:54,  4.31it/s]

 46%|████▌     | 2155/4716 [08:26<09:54,  4.31it/s]

 46%|████▌     | 2156/4716 [08:26<09:53,  4.31it/s]

 46%|████▌     | 2157/4716 [08:27<09:54,  4.31it/s]

 46%|████▌     | 2158/4716 [08:27<09:52,  4.32it/s]

 46%|████▌     | 2159/4716 [08:27<09:52,  4.32it/s]

 46%|████▌     | 2160/4716 [08:27<09:51,  4.32it/s]

 46%|████▌     | 2161/4716 [08:27<09:51,  4.32it/s]

 46%|████▌     | 2162/4716 [08:28<09:51,  4.32it/s]

 46%|████▌     | 2163/4716 [08:28<09:51,  4.31it/s]

 46%|████▌     | 2164/4716 [08:28<09:50,  4.32it/s]

 46%|████▌     | 2165/4716 [08:28<09:51,  4.31it/s]

 46%|████▌     | 2166/4716 [08:29<09:50,  4.32it/s]

 46%|████▌     | 2167/4716 [08:29<09:50,  4.31it/s]

 46%|████▌     | 2168/4716 [08:29<09:49,  4.32it/s]

 46%|████▌     | 2169/4716 [08:29<09:50,  4.32it/s]

 46%|████▌     | 2170/4716 [08:30<09:49,  4.32it/s]

 46%|████▌     | 2171/4716 [08:30<09:50,  4.31it/s]

 46%|████▌     | 2172/4716 [08:30<09:49,  4.32it/s]

 46%|████▌     | 2173/4716 [08:30<09:48,  4.32it/s]

 46%|████▌     | 2174/4716 [08:31<09:51,  4.30it/s]

 46%|████▌     | 2175/4716 [08:31<09:49,  4.31it/s]

 46%|████▌     | 2176/4716 [08:31<09:50,  4.30it/s]

 46%|████▌     | 2177/4716 [08:31<09:49,  4.31it/s]

 46%|████▌     | 2178/4716 [08:31<09:48,  4.31it/s]

 46%|████▌     | 2179/4716 [08:32<09:48,  4.31it/s]

 46%|████▌     | 2180/4716 [08:32<09:47,  4.32it/s]

 46%|████▌     | 2181/4716 [08:32<09:46,  4.32it/s]

 46%|████▋     | 2182/4716 [08:32<09:45,  4.33it/s]

 46%|████▋     | 2183/4716 [08:33<09:45,  4.33it/s]

 46%|████▋     | 2184/4716 [08:33<09:45,  4.33it/s]

 46%|████▋     | 2185/4716 [08:33<09:43,  4.33it/s]

 46%|████▋     | 2186/4716 [08:33<09:43,  4.34it/s]

 46%|████▋     | 2187/4716 [08:34<09:43,  4.33it/s]

 46%|████▋     | 2188/4716 [08:34<09:43,  4.33it/s]

 46%|████▋     | 2189/4716 [08:34<09:43,  4.33it/s]

 46%|████▋     | 2190/4716 [08:34<09:42,  4.33it/s]

 46%|████▋     | 2191/4716 [08:34<09:42,  4.33it/s]

 46%|████▋     | 2192/4716 [08:35<09:43,  4.32it/s]

 47%|████▋     | 2193/4716 [08:35<09:43,  4.33it/s]

 47%|████▋     | 2194/4716 [08:35<09:42,  4.33it/s]

 47%|████▋     | 2195/4716 [08:35<09:43,  4.32it/s]

 47%|████▋     | 2196/4716 [08:36<09:42,  4.33it/s]

 47%|████▋     | 2197/4716 [08:36<09:42,  4.33it/s]

 47%|████▋     | 2198/4716 [08:36<09:41,  4.33it/s]

 47%|████▋     | 2199/4716 [08:36<09:40,  4.34it/s]

 47%|████▋     | 2200/4716 [08:37<09:39,  4.34it/s]

 47%|████▋     | 2201/4716 [08:37<09:40,  4.33it/s]

 47%|████▋     | 2202/4716 [08:37<09:41,  4.33it/s]

 47%|████▋     | 2203/4716 [08:37<09:42,  4.31it/s]

 47%|████▋     | 2204/4716 [08:37<09:43,  4.30it/s]

 47%|████▋     | 2205/4716 [08:38<09:42,  4.31it/s]

 47%|████▋     | 2206/4716 [08:38<09:41,  4.32it/s]

 47%|████▋     | 2207/4716 [08:38<09:40,  4.32it/s]

 47%|████▋     | 2208/4716 [08:38<09:41,  4.32it/s]

 47%|████▋     | 2209/4716 [08:39<09:39,  4.32it/s]

 47%|████▋     | 2210/4716 [08:39<09:41,  4.31it/s]

 47%|████▋     | 2211/4716 [08:39<09:41,  4.31it/s]

 47%|████▋     | 2212/4716 [08:39<09:41,  4.30it/s]

 47%|████▋     | 2213/4716 [08:40<09:42,  4.30it/s]

 47%|████▋     | 2214/4716 [08:40<09:40,  4.31it/s]

 47%|████▋     | 2215/4716 [08:40<09:40,  4.31it/s]

 47%|████▋     | 2216/4716 [08:40<09:40,  4.31it/s]

 47%|████▋     | 2217/4716 [08:40<09:42,  4.29it/s]

 47%|████▋     | 2218/4716 [08:41<09:40,  4.30it/s]

 47%|████▋     | 2219/4716 [08:41<09:39,  4.31it/s]

 47%|████▋     | 2220/4716 [08:41<09:39,  4.31it/s]

 47%|████▋     | 2221/4716 [08:41<09:38,  4.32it/s]

 47%|████▋     | 2222/4716 [08:42<09:36,  4.32it/s]

 47%|████▋     | 2223/4716 [08:42<09:36,  4.32it/s]

 47%|████▋     | 2224/4716 [08:42<09:36,  4.33it/s]

 47%|████▋     | 2225/4716 [08:42<09:35,  4.33it/s]

 47%|████▋     | 2226/4716 [08:43<09:35,  4.33it/s]

 47%|████▋     | 2227/4716 [08:43<09:35,  4.33it/s]

 47%|████▋     | 2228/4716 [08:43<09:35,  4.32it/s]

 47%|████▋     | 2229/4716 [08:43<09:36,  4.31it/s]

 47%|████▋     | 2230/4716 [08:43<09:36,  4.32it/s]

 47%|████▋     | 2231/4716 [08:44<09:37,  4.30it/s]

 47%|████▋     | 2232/4716 [08:44<09:38,  4.30it/s]

 47%|████▋     | 2233/4716 [08:44<09:38,  4.29it/s]

 47%|████▋     | 2234/4716 [08:44<09:39,  4.28it/s]

 47%|████▋     | 2235/4716 [08:45<09:37,  4.30it/s]

 47%|████▋     | 2236/4716 [08:45<09:37,  4.30it/s]

 47%|████▋     | 2237/4716 [08:45<09:36,  4.30it/s]

 47%|████▋     | 2238/4716 [08:45<09:38,  4.28it/s]

 47%|████▋     | 2239/4716 [08:46<09:37,  4.29it/s]

 47%|████▋     | 2240/4716 [08:46<09:39,  4.27it/s]

 48%|████▊     | 2241/4716 [08:46<09:37,  4.29it/s]

 48%|████▊     | 2242/4716 [08:46<09:35,  4.30it/s]

 48%|████▊     | 2243/4716 [08:47<09:34,  4.30it/s]

 48%|████▊     | 2244/4716 [08:47<09:35,  4.30it/s]

 48%|████▊     | 2245/4716 [08:47<09:36,  4.28it/s]

 48%|████▊     | 2246/4716 [08:47<09:35,  4.29it/s]

 48%|████▊     | 2247/4716 [08:47<09:34,  4.30it/s]

 48%|████▊     | 2248/4716 [08:48<09:32,  4.31it/s]

 48%|████▊     | 2249/4716 [08:48<09:32,  4.31it/s]

 48%|████▊     | 2250/4716 [08:48<09:34,  4.29it/s]

 48%|████▊     | 2251/4716 [08:48<09:33,  4.30it/s]

 48%|████▊     | 2252/4716 [08:49<09:32,  4.31it/s]

 48%|████▊     | 2253/4716 [08:49<09:31,  4.31it/s]

 48%|████▊     | 2254/4716 [08:49<09:30,  4.32it/s]

 48%|████▊     | 2255/4716 [08:49<09:32,  4.30it/s]

 48%|████▊     | 2256/4716 [08:50<09:30,  4.31it/s]

 48%|████▊     | 2257/4716 [08:50<09:30,  4.31it/s]

 48%|████▊     | 2258/4716 [08:50<09:32,  4.30it/s]

 48%|████▊     | 2259/4716 [08:50<09:31,  4.30it/s]

 48%|████▊     | 2260/4716 [08:50<09:30,  4.31it/s]

 48%|████▊     | 2261/4716 [08:51<09:29,  4.31it/s]

 48%|████▊     | 2262/4716 [08:51<09:29,  4.31it/s]

 48%|████▊     | 2263/4716 [08:51<09:31,  4.29it/s]

 48%|████▊     | 2264/4716 [08:51<09:31,  4.29it/s]

 48%|████▊     | 2265/4716 [08:52<09:31,  4.29it/s]

 48%|████▊     | 2266/4716 [08:52<09:30,  4.30it/s]

 48%|████▊     | 2267/4716 [08:52<09:29,  4.30it/s]

 48%|████▊     | 2268/4716 [08:52<09:30,  4.29it/s]

 48%|████▊     | 2269/4716 [08:53<09:28,  4.31it/s]

 48%|████▊     | 2270/4716 [08:53<09:28,  4.30it/s]

 48%|████▊     | 2271/4716 [08:53<09:28,  4.30it/s]

 48%|████▊     | 2272/4716 [08:53<09:27,  4.30it/s]

 48%|████▊     | 2273/4716 [08:53<09:28,  4.29it/s]

 48%|████▊     | 2274/4716 [08:54<09:27,  4.30it/s]

 48%|████▊     | 2275/4716 [08:54<09:28,  4.29it/s]

 48%|████▊     | 2276/4716 [08:54<09:29,  4.28it/s]

 48%|████▊     | 2277/4716 [08:54<09:28,  4.29it/s]

 48%|████▊     | 2278/4716 [08:55<09:28,  4.29it/s]

 48%|████▊     | 2279/4716 [08:55<09:27,  4.30it/s]

 48%|████▊     | 2280/4716 [08:55<09:26,  4.30it/s]

 48%|████▊     | 2281/4716 [08:55<09:25,  4.30it/s]

 48%|████▊     | 2282/4716 [08:56<09:24,  4.31it/s]

 48%|████▊     | 2283/4716 [08:56<09:26,  4.29it/s]

 48%|████▊     | 2284/4716 [08:56<09:26,  4.30it/s]

 48%|████▊     | 2285/4716 [08:56<09:25,  4.30it/s]

 48%|████▊     | 2286/4716 [08:57<09:25,  4.30it/s]

 48%|████▊     | 2287/4716 [08:57<09:24,  4.30it/s]

 49%|████▊     | 2288/4716 [08:57<09:25,  4.29it/s]

 49%|████▊     | 2289/4716 [08:57<09:26,  4.29it/s]

 49%|████▊     | 2290/4716 [08:57<09:25,  4.29it/s]

 49%|████▊     | 2291/4716 [08:58<09:26,  4.28it/s]

 49%|████▊     | 2292/4716 [08:58<09:24,  4.29it/s]

 49%|████▊     | 2293/4716 [08:58<09:24,  4.29it/s]

 49%|████▊     | 2294/4716 [08:58<09:25,  4.28it/s]

 49%|████▊     | 2295/4716 [08:59<09:25,  4.28it/s]

 49%|████▊     | 2296/4716 [08:59<09:25,  4.28it/s]

 49%|████▊     | 2297/4716 [08:59<09:25,  4.28it/s]

 49%|████▊     | 2298/4716 [08:59<09:25,  4.28it/s]

 49%|████▊     | 2299/4716 [09:00<09:26,  4.27it/s]

 49%|████▉     | 2300/4716 [09:00<09:24,  4.28it/s]

 49%|████▉     | 2301/4716 [09:00<09:25,  4.27it/s]

 49%|████▉     | 2302/4716 [09:00<09:24,  4.27it/s]

 49%|████▉     | 2303/4716 [09:00<09:23,  4.28it/s]

 49%|████▉     | 2304/4716 [09:01<09:22,  4.29it/s]

 49%|████▉     | 2305/4716 [09:01<09:21,  4.29it/s]

 49%|████▉     | 2306/4716 [09:01<09:21,  4.29it/s]

 49%|████▉     | 2307/4716 [09:01<09:22,  4.28it/s]

 49%|████▉     | 2308/4716 [09:02<09:20,  4.29it/s]

 49%|████▉     | 2309/4716 [09:02<09:21,  4.29it/s]

 49%|████▉     | 2310/4716 [09:02<09:19,  4.30it/s]

 49%|████▉     | 2311/4716 [09:02<09:19,  4.29it/s]

 49%|████▉     | 2312/4716 [09:03<09:19,  4.29it/s]

 49%|████▉     | 2313/4716 [09:03<09:20,  4.28it/s]

 49%|████▉     | 2314/4716 [09:03<09:21,  4.28it/s]

 49%|████▉     | 2315/4716 [09:03<09:19,  4.29it/s]

 49%|████▉     | 2316/4716 [09:04<09:18,  4.29it/s]

 49%|████▉     | 2317/4716 [09:04<09:20,  4.28it/s]

 49%|████▉     | 2318/4716 [09:04<09:19,  4.29it/s]

 49%|████▉     | 2319/4716 [09:04<09:18,  4.29it/s]

 49%|████▉     | 2320/4716 [09:04<09:17,  4.29it/s]

 49%|████▉     | 2321/4716 [09:05<09:17,  4.29it/s]

 49%|████▉     | 2322/4716 [09:05<09:17,  4.29it/s]

 49%|████▉     | 2323/4716 [09:05<09:17,  4.29it/s]

 49%|████▉     | 2324/4716 [09:05<09:17,  4.29it/s]

 49%|████▉     | 2325/4716 [09:06<09:16,  4.29it/s]

 49%|████▉     | 2326/4716 [09:06<09:16,  4.30it/s]

 49%|████▉     | 2327/4716 [09:06<09:17,  4.29it/s]

 49%|████▉     | 2328/4716 [09:06<09:15,  4.30it/s]

 49%|████▉     | 2329/4716 [09:07<09:15,  4.30it/s]

 49%|████▉     | 2330/4716 [09:07<09:15,  4.30it/s]

 49%|████▉     | 2331/4716 [09:07<09:15,  4.29it/s]

 49%|████▉     | 2332/4716 [09:07<09:15,  4.29it/s]

 49%|████▉     | 2333/4716 [09:07<09:13,  4.30it/s]

 49%|████▉     | 2334/4716 [09:08<09:13,  4.31it/s]

 50%|████▉     | 2335/4716 [09:08<09:12,  4.31it/s]

 50%|████▉     | 2336/4716 [09:08<09:11,  4.31it/s]

 50%|████▉     | 2337/4716 [09:08<09:13,  4.30it/s]

 50%|████▉     | 2338/4716 [09:09<09:13,  4.30it/s]

 50%|████▉     | 2339/4716 [09:09<09:12,  4.30it/s]

 50%|████▉     | 2340/4716 [09:09<09:11,  4.31it/s]

 50%|████▉     | 2341/4716 [09:09<09:10,  4.31it/s]

 50%|████▉     | 2342/4716 [09:10<09:11,  4.31it/s]

 50%|████▉     | 2343/4716 [09:10<09:12,  4.29it/s]

 50%|████▉     | 2344/4716 [09:10<09:11,  4.30it/s]

 50%|████▉     | 2345/4716 [09:10<09:13,  4.29it/s]

 50%|████▉     | 2346/4716 [09:10<09:12,  4.29it/s]

 50%|████▉     | 2347/4716 [09:11<09:13,  4.28it/s]

 50%|████▉     | 2348/4716 [09:11<09:15,  4.27it/s]

 50%|████▉     | 2349/4716 [09:11<09:16,  4.26it/s]

 50%|████▉     | 2350/4716 [09:11<09:15,  4.26it/s]

 50%|████▉     | 2351/4716 [09:12<09:13,  4.27it/s]

 50%|████▉     | 2352/4716 [09:12<09:13,  4.27it/s]

 50%|████▉     | 2353/4716 [09:12<09:13,  4.27it/s]

 50%|████▉     | 2354/4716 [09:12<09:12,  4.27it/s]

 50%|████▉     | 2355/4716 [09:13<09:12,  4.28it/s]

 50%|████▉     | 2356/4716 [09:13<09:11,  4.28it/s]

 50%|████▉     | 2357/4716 [09:13<09:10,  4.28it/s]

 50%|█████     | 2358/4716 [09:13<09:11,  4.28it/s]

 50%|█████     | 2359/4716 [09:14<09:09,  4.29it/s]

 50%|█████     | 2360/4716 [09:14<09:10,  4.28it/s]

 50%|█████     | 2361/4716 [09:14<09:10,  4.28it/s]

 50%|█████     | 2362/4716 [09:14<09:10,  4.28it/s]

 50%|█████     | 2363/4716 [09:14<09:10,  4.27it/s]

 50%|█████     | 2364/4716 [09:15<09:11,  4.27it/s]

 50%|█████     | 2365/4716 [09:15<09:10,  4.27it/s]

 50%|█████     | 2366/4716 [09:15<09:10,  4.27it/s]

 50%|█████     | 2367/4716 [09:15<09:09,  4.27it/s]

 50%|█████     | 2368/4716 [09:16<09:09,  4.27it/s]

 50%|█████     | 2369/4716 [09:16<09:08,  4.28it/s]

 50%|█████     | 2370/4716 [09:16<09:09,  4.27it/s]

 50%|█████     | 2371/4716 [09:16<09:08,  4.27it/s]

 50%|█████     | 2372/4716 [09:17<09:08,  4.27it/s]

 50%|█████     | 2373/4716 [09:17<09:08,  4.27it/s]

 50%|█████     | 2374/4716 [09:17<09:07,  4.28it/s]

 50%|█████     | 2375/4716 [09:17<09:06,  4.28it/s]

 50%|█████     | 2376/4716 [09:18<09:08,  4.27it/s]

 50%|█████     | 2377/4716 [09:18<09:06,  4.28it/s]

 50%|█████     | 2378/4716 [09:18<09:07,  4.27it/s]

 50%|█████     | 2379/4716 [09:18<09:06,  4.27it/s]

 50%|█████     | 2380/4716 [09:18<09:06,  4.28it/s]

 50%|█████     | 2381/4716 [09:19<09:05,  4.28it/s]

 51%|█████     | 2382/4716 [09:19<09:05,  4.28it/s]

 51%|█████     | 2383/4716 [09:19<09:04,  4.28it/s]

 51%|█████     | 2384/4716 [09:19<09:04,  4.28it/s]

 51%|█████     | 2385/4716 [09:20<09:03,  4.29it/s]

 51%|█████     | 2386/4716 [09:20<09:04,  4.28it/s]

 51%|█████     | 2387/4716 [09:20<09:03,  4.28it/s]

 51%|█████     | 2388/4716 [09:20<09:02,  4.29it/s]

 51%|█████     | 2389/4716 [09:21<09:03,  4.28it/s]

 51%|█████     | 2390/4716 [09:21<09:03,  4.28it/s]

 51%|█████     | 2391/4716 [09:21<09:04,  4.27it/s]

 51%|█████     | 2392/4716 [09:21<09:03,  4.27it/s]

 51%|█████     | 2393/4716 [09:21<09:03,  4.27it/s]

 51%|█████     | 2394/4716 [09:22<09:03,  4.28it/s]

 51%|█████     | 2395/4716 [09:22<09:03,  4.27it/s]

 51%|█████     | 2396/4716 [09:22<09:03,  4.27it/s]

 51%|█████     | 2397/4716 [09:22<09:04,  4.26it/s]

 51%|█████     | 2398/4716 [09:23<09:02,  4.27it/s]

 51%|█████     | 2399/4716 [09:23<09:02,  4.27it/s]

 51%|█████     | 2400/4716 [09:23<09:03,  4.26it/s]

 51%|█████     | 2401/4716 [09:23<09:03,  4.26it/s]

 51%|█████     | 2402/4716 [09:24<09:03,  4.25it/s]

 51%|█████     | 2403/4716 [09:24<09:04,  4.25it/s]

 51%|█████     | 2404/4716 [09:24<09:03,  4.25it/s]

 51%|█████     | 2405/4716 [09:24<09:04,  4.25it/s]

 51%|█████     | 2406/4716 [09:25<09:02,  4.25it/s]

 51%|█████     | 2407/4716 [09:25<09:02,  4.25it/s]

 51%|█████     | 2408/4716 [09:25<09:03,  4.25it/s]

 51%|█████     | 2409/4716 [09:25<09:04,  4.24it/s]

 51%|█████     | 2410/4716 [09:25<09:04,  4.24it/s]

 51%|█████     | 2411/4716 [09:26<09:02,  4.25it/s]

 51%|█████     | 2412/4716 [09:26<09:02,  4.25it/s]

 51%|█████     | 2413/4716 [09:26<09:03,  4.24it/s]

 51%|█████     | 2414/4716 [09:26<09:01,  4.25it/s]

 51%|█████     | 2415/4716 [09:27<09:02,  4.24it/s]

 51%|█████     | 2416/4716 [09:27<09:00,  4.25it/s]

 51%|█████▏    | 2417/4716 [09:27<09:00,  4.25it/s]

 51%|█████▏    | 2418/4716 [09:27<09:00,  4.25it/s]

 51%|█████▏    | 2419/4716 [09:28<09:00,  4.25it/s]

 51%|█████▏    | 2420/4716 [09:28<09:00,  4.25it/s]

 51%|█████▏    | 2421/4716 [09:28<09:00,  4.25it/s]

 51%|█████▏    | 2422/4716 [09:28<08:58,  4.26it/s]

 51%|█████▏    | 2423/4716 [09:29<08:58,  4.26it/s]

 51%|█████▏    | 2424/4716 [09:29<08:58,  4.25it/s]

 51%|█████▏    | 2425/4716 [09:29<09:00,  4.24it/s]

 51%|█████▏    | 2426/4716 [09:29<08:59,  4.25it/s]

 51%|█████▏    | 2427/4716 [09:29<08:59,  4.24it/s]

 51%|█████▏    | 2428/4716 [09:30<09:00,  4.24it/s]

 52%|█████▏    | 2429/4716 [09:30<08:57,  4.25it/s]

 52%|█████▏    | 2430/4716 [09:30<08:57,  4.25it/s]

 52%|█████▏    | 2431/4716 [09:30<08:56,  4.26it/s]

 52%|█████▏    | 2432/4716 [09:31<08:57,  4.25it/s]

 52%|█████▏    | 2433/4716 [09:31<08:56,  4.25it/s]

 52%|█████▏    | 2434/4716 [09:31<08:55,  4.26it/s]

 52%|█████▏    | 2435/4716 [09:31<08:56,  4.25it/s]

 52%|█████▏    | 2436/4716 [09:32<08:55,  4.26it/s]

 52%|█████▏    | 2437/4716 [09:32<08:55,  4.26it/s]

 52%|█████▏    | 2438/4716 [09:32<08:56,  4.25it/s]

 52%|█████▏    | 2439/4716 [09:32<08:57,  4.24it/s]

 52%|█████▏    | 2440/4716 [09:33<08:56,  4.24it/s]

 52%|█████▏    | 2441/4716 [09:33<08:55,  4.25it/s]

 52%|█████▏    | 2442/4716 [09:33<08:54,  4.25it/s]

 52%|█████▏    | 2443/4716 [09:33<08:53,  4.26it/s]

 52%|█████▏    | 2444/4716 [09:33<08:54,  4.25it/s]

 52%|█████▏    | 2445/4716 [09:34<08:55,  4.24it/s]

 52%|█████▏    | 2446/4716 [09:34<08:54,  4.25it/s]

 52%|█████▏    | 2447/4716 [09:34<08:55,  4.23it/s]

 52%|█████▏    | 2448/4716 [09:34<08:56,  4.23it/s]

 52%|█████▏    | 2449/4716 [09:35<08:55,  4.23it/s]

 52%|█████▏    | 2450/4716 [09:35<08:54,  4.24it/s]

 52%|█████▏    | 2451/4716 [09:35<08:52,  4.25it/s]

 52%|█████▏    | 2452/4716 [09:35<08:52,  4.25it/s]

 52%|█████▏    | 2453/4716 [09:36<08:53,  4.24it/s]

 52%|█████▏    | 2454/4716 [09:36<08:51,  4.25it/s]

 52%|█████▏    | 2455/4716 [09:36<08:51,  4.25it/s]

 52%|█████▏    | 2456/4716 [09:36<08:51,  4.25it/s]

 52%|█████▏    | 2457/4716 [09:37<08:51,  4.25it/s]

 52%|█████▏    | 2458/4716 [09:37<08:52,  4.24it/s]

 52%|█████▏    | 2459/4716 [09:37<08:51,  4.25it/s]

 52%|█████▏    | 2460/4716 [09:37<08:51,  4.25it/s]

 52%|█████▏    | 2461/4716 [09:37<08:49,  4.26it/s]

 52%|█████▏    | 2462/4716 [09:38<08:49,  4.25it/s]

 52%|█████▏    | 2463/4716 [09:38<08:49,  4.25it/s]

 52%|█████▏    | 2464/4716 [09:38<08:50,  4.25it/s]

 52%|█████▏    | 2465/4716 [09:38<08:51,  4.24it/s]

 52%|█████▏    | 2466/4716 [09:39<08:50,  4.24it/s]

 52%|█████▏    | 2467/4716 [09:39<08:51,  4.23it/s]

 52%|█████▏    | 2468/4716 [09:39<08:50,  4.24it/s]

 52%|█████▏    | 2469/4716 [09:39<08:50,  4.24it/s]

 52%|█████▏    | 2470/4716 [09:40<08:50,  4.23it/s]

 52%|█████▏    | 2471/4716 [09:40<08:49,  4.24it/s]

 52%|█████▏    | 2472/4716 [09:40<08:48,  4.25it/s]

 52%|█████▏    | 2473/4716 [09:40<08:49,  4.24it/s]

 52%|█████▏    | 2474/4716 [09:41<08:48,  4.24it/s]

 52%|█████▏    | 2475/4716 [09:41<08:47,  4.25it/s]

 53%|█████▎    | 2476/4716 [09:41<08:46,  4.25it/s]

 53%|█████▎    | 2477/4716 [09:41<08:47,  4.24it/s]

 53%|█████▎    | 2478/4716 [09:41<08:47,  4.24it/s]

 53%|█████▎    | 2479/4716 [09:42<08:47,  4.24it/s]

 53%|█████▎    | 2480/4716 [09:42<08:48,  4.23it/s]

 53%|█████▎    | 2481/4716 [09:42<08:48,  4.23it/s]

 53%|█████▎    | 2482/4716 [09:42<08:48,  4.23it/s]

 53%|█████▎    | 2483/4716 [09:43<08:47,  4.24it/s]

 53%|█████▎    | 2484/4716 [09:43<08:46,  4.24it/s]

 53%|█████▎    | 2485/4716 [09:43<08:47,  4.23it/s]

 53%|█████▎    | 2486/4716 [09:43<08:45,  4.25it/s]

 53%|█████▎    | 2487/4716 [09:44<08:44,  4.25it/s]

 53%|█████▎    | 2488/4716 [09:44<08:44,  4.25it/s]

 53%|█████▎    | 2489/4716 [09:44<08:44,  4.25it/s]

 53%|█████▎    | 2490/4716 [09:44<08:44,  4.25it/s]

 53%|█████▎    | 2491/4716 [09:45<08:44,  4.25it/s]

 53%|█████▎    | 2492/4716 [09:45<08:45,  4.24it/s]

 53%|█████▎    | 2493/4716 [09:45<08:44,  4.24it/s]

 53%|█████▎    | 2494/4716 [09:45<08:44,  4.24it/s]

 53%|█████▎    | 2495/4716 [09:46<08:43,  4.24it/s]

 53%|█████▎    | 2496/4716 [09:46<08:43,  4.24it/s]

 53%|█████▎    | 2497/4716 [09:46<08:42,  4.24it/s]

 53%|█████▎    | 2498/4716 [09:46<08:42,  4.25it/s]

 53%|█████▎    | 2499/4716 [09:46<08:42,  4.25it/s]

 53%|█████▎    | 2500/4716 [09:47<08:41,  4.25it/s]

 53%|█████▎    | 2501/4716 [09:47<08:41,  4.25it/s]

 53%|█████▎    | 2502/4716 [09:47<08:43,  4.23it/s]

 53%|█████▎    | 2503/4716 [09:47<08:42,  4.24it/s]

logging
logging the anndata

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 53%|█████▎    | 2504/4716 [11:44<21:36:31, 35.17s/it]

 53%|█████▎    | 2505/4716 [11:44<15:10:25, 24.71s/it]

 53%|█████▎    | 2506/4716 [11:45<10:39:30, 17.36s/it]

 53%|█████▎    | 2507/4716 [11:45<7:29:57, 12.22s/it]

 53%|█████▎    | 2508/4716 [11:45<5:17:19,  8.62s/it]

 53%|█████▎    | 2509/4716 [11:45<3:44:32,  6.10s/it]

 53%|█████▎    | 2510/4716 [11:45<2:39:35,  4.34s/it]

 53%|█████▎    | 2511/4716 [11:46<1:54:08,  3.11s/it]

 53%|█████▎    | 2512/4716 [11:46<1:22:21,  2.24s/it]

 53%|█████▎    | 2513/4716 [11:46<1:00:07,  1.64s/it]

 53%|█████▎    | 2514/4716 [11:46<44:33,  1.21s/it]

 53%|█████▎    | 2515/4716 [11:47<33:40,  1.09it/s]

 53%|█████▎    | 2516/4716 [11:47<26:02,  1.41it/s]

 53%|█████▎    | 2517/4716 [11:47<20:41,  1.77it/s]

 53%|█████▎    | 2518/4716 [11:47<16:58,  2.16it/s]

 53%|█████▎    | 2519/4716 [11:48<14:21,  2.55it/s]

 53%|█████▎    | 2520/4716 [11:48<12:32,  2.92it/s]

 53%|█████▎    | 2521/4716 [11:48<11:16,  3.25it/s]

 53%|█████▎    | 2522/4716 [11:48<10:22,  3.53it/s]

 53%|█████▎    | 2523/4716 [11:48<09:45,  3.75it/s]

 54%|█████▎    | 2524/4716 [11:49<09:18,  3.92it/s]

 54%|█████▎    | 2525/4716 [11:49<08:59,  4.06it/s]

 54%|█████▎    | 2526/4716 [11:49<08:46,  4.16it/s]

 54%|█████▎    | 2527/4716 [11:49<08:38,  4.22it/s]

 54%|█████▎    | 2528/4716 [11:50<08:30,  4.28it/s]

 54%|█████▎    | 2529/4716 [11:50<08:25,  4.33it/s]

 54%|█████▎    | 2530/4716 [11:50<08:21,  4.36it/s]

 54%|█████▎    | 2531/4716 [11:50<08:19,  4.37it/s]

 54%|█████▎    | 2532/4716 [11:50<08:19,  4.37it/s]

 54%|█████▎    | 2533/4716 [11:51<08:17,  4.38it/s]

 54%|█████▎    | 2534/4716 [11:51<08:17,  4.39it/s]

 54%|█████▍    | 2535/4716 [11:51<08:16,  4.39it/s]

 54%|█████▍    | 2536/4716 [11:51<08:15,  4.40it/s]

 54%|█████▍    | 2537/4716 [11:52<08:15,  4.39it/s]

 54%|█████▍    | 2538/4716 [11:52<08:16,  4.39it/s]

 54%|█████▍    | 2539/4716 [11:52<08:15,  4.39it/s]

 54%|█████▍    | 2540/4716 [11:52<08:16,  4.38it/s]

 54%|█████▍    | 2541/4716 [11:53<08:16,  4.38it/s]

 54%|█████▍    | 2542/4716 [11:53<08:16,  4.38it/s]

 54%|█████▍    | 2543/4716 [11:53<08:15,  4.39it/s]

 54%|█████▍    | 2544/4716 [11:53<08:14,  4.39it/s]

 54%|█████▍    | 2545/4716 [11:53<08:14,  4.39it/s]

 54%|█████▍    | 2546/4716 [11:54<08:14,  4.39it/s]

 54%|█████▍    | 2547/4716 [11:54<08:12,  4.41it/s]

 54%|█████▍    | 2548/4716 [11:54<08:11,  4.41it/s]

 54%|█████▍    | 2549/4716 [11:54<08:11,  4.41it/s]

 54%|█████▍    | 2550/4716 [11:55<08:11,  4.41it/s]

 54%|█████▍    | 2551/4716 [11:55<08:11,  4.40it/s]

 54%|█████▍    | 2552/4716 [11:55<08:12,  4.40it/s]

 54%|█████▍    | 2553/4716 [11:55<08:16,  4.36it/s]

 54%|█████▍    | 2554/4716 [11:55<08:14,  4.37it/s]

 54%|█████▍    | 2555/4716 [11:56<08:12,  4.38it/s]

 54%|█████▍    | 2556/4716 [11:56<08:11,  4.39it/s]

 54%|█████▍    | 2557/4716 [11:56<08:10,  4.40it/s]

 54%|█████▍    | 2558/4716 [11:56<08:13,  4.38it/s]

 54%|█████▍    | 2559/4716 [11:57<08:12,  4.38it/s]

 54%|█████▍    | 2560/4716 [11:57<08:11,  4.38it/s]

 54%|█████▍    | 2561/4716 [11:57<08:09,  4.40it/s]

 54%|█████▍    | 2562/4716 [11:57<08:09,  4.40it/s]

 54%|█████▍    | 2563/4716 [11:58<08:10,  4.39it/s]

 54%|█████▍    | 2564/4716 [11:58<08:09,  4.40it/s]

 54%|█████▍    | 2565/4716 [11:58<08:09,  4.40it/s]

 54%|█████▍    | 2566/4716 [11:58<08:09,  4.39it/s]

 54%|█████▍    | 2567/4716 [11:58<08:08,  4.40it/s]

 54%|█████▍    | 2568/4716 [11:59<08:09,  4.39it/s]

 54%|█████▍    | 2569/4716 [11:59<08:09,  4.39it/s]

 54%|█████▍    | 2570/4716 [11:59<08:13,  4.35it/s]

 55%|█████▍    | 2571/4716 [11:59<08:12,  4.36it/s]

 55%|█████▍    | 2572/4716 [12:00<08:09,  4.38it/s]

 55%|█████▍    | 2573/4716 [12:00<08:09,  4.38it/s]

 55%|█████▍    | 2574/4716 [12:00<08:09,  4.37it/s]

 55%|█████▍    | 2575/4716 [12:00<08:09,  4.37it/s]

 55%|█████▍    | 2576/4716 [12:01<08:08,  4.38it/s]

 55%|█████▍    | 2577/4716 [12:01<08:08,  4.38it/s]

 55%|█████▍    | 2578/4716 [12:01<08:06,  4.39it/s]

 55%|█████▍    | 2579/4716 [12:01<08:06,  4.39it/s]

 55%|█████▍    | 2580/4716 [12:01<08:05,  4.40it/s]

 55%|█████▍    | 2581/4716 [12:02<08:04,  4.40it/s]

 55%|█████▍    | 2582/4716 [12:02<08:06,  4.39it/s]

 55%|█████▍    | 2583/4716 [12:02<08:07,  4.37it/s]

 55%|█████▍    | 2584/4716 [12:02<08:07,  4.37it/s]

 55%|█████▍    | 2585/4716 [12:03<08:08,  4.36it/s]

 55%|█████▍    | 2586/4716 [12:03<08:07,  4.37it/s]

 55%|█████▍    | 2587/4716 [12:03<08:06,  4.38it/s]

 55%|█████▍    | 2588/4716 [12:03<08:05,  4.38it/s]

 55%|█████▍    | 2589/4716 [12:03<08:04,  4.39it/s]

 55%|█████▍    | 2590/4716 [12:04<08:05,  4.38it/s]

 55%|█████▍    | 2591/4716 [12:04<08:04,  4.38it/s]

 55%|█████▍    | 2592/4716 [12:04<08:04,  4.38it/s]

 55%|█████▍    | 2593/4716 [12:04<08:04,  4.38it/s]

 55%|█████▌    | 2594/4716 [12:05<08:03,  4.39it/s]

 55%|█████▌    | 2595/4716 [12:05<08:04,  4.38it/s]

 55%|█████▌    | 2596/4716 [12:05<08:04,  4.37it/s]

 55%|█████▌    | 2597/4716 [12:05<08:05,  4.36it/s]

 55%|█████▌    | 2598/4716 [12:06<08:06,  4.36it/s]

 55%|█████▌    | 2599/4716 [12:06<08:05,  4.36it/s]

 55%|█████▌    | 2600/4716 [12:06<08:03,  4.37it/s]

 55%|█████▌    | 2601/4716 [12:06<08:03,  4.38it/s]

 55%|█████▌    | 2602/4716 [12:06<08:02,  4.38it/s]

 55%|█████▌    | 2603/4716 [12:07<08:01,  4.39it/s]

 55%|█████▌    | 2604/4716 [12:07<08:02,  4.38it/s]

 55%|█████▌    | 2605/4716 [12:07<08:03,  4.37it/s]

 55%|█████▌    | 2606/4716 [12:07<08:05,  4.34it/s]

 55%|█████▌    | 2607/4716 [12:08<08:04,  4.35it/s]

 55%|█████▌    | 2608/4716 [12:08<08:02,  4.37it/s]

 55%|█████▌    | 2609/4716 [12:08<08:02,  4.37it/s]

 55%|█████▌    | 2610/4716 [12:08<08:02,  4.36it/s]

 55%|█████▌    | 2611/4716 [12:08<08:01,  4.37it/s]

 55%|█████▌    | 2612/4716 [12:09<08:01,  4.37it/s]

 55%|█████▌    | 2613/4716 [12:09<08:01,  4.37it/s]

 55%|█████▌    | 2614/4716 [12:09<08:00,  4.38it/s]

 55%|█████▌    | 2615/4716 [12:09<07:59,  4.38it/s]

 55%|█████▌    | 2616/4716 [12:10<07:59,  4.38it/s]

 55%|█████▌    | 2617/4716 [12:10<07:59,  4.38it/s]

 56%|█████▌    | 2618/4716 [12:10<07:59,  4.38it/s]

 56%|█████▌    | 2619/4716 [12:10<07:59,  4.37it/s]

 56%|█████▌    | 2620/4716 [12:11<08:00,  4.37it/s]

 56%|█████▌    | 2621/4716 [12:11<07:59,  4.37it/s]

 56%|█████▌    | 2622/4716 [12:11<07:58,  4.38it/s]

 56%|█████▌    | 2623/4716 [12:11<07:57,  4.38it/s]

 56%|█████▌    | 2624/4716 [12:11<07:57,  4.38it/s]

 56%|█████▌    | 2625/4716 [12:12<07:56,  4.38it/s]

 56%|█████▌    | 2626/4716 [12:12<07:56,  4.39it/s]

 56%|█████▌    | 2627/4716 [12:12<07:57,  4.37it/s]

 56%|█████▌    | 2628/4716 [12:12<07:57,  4.37it/s]

 56%|█████▌    | 2629/4716 [12:13<07:56,  4.38it/s]

 56%|█████▌    | 2630/4716 [12:13<07:56,  4.38it/s]

 56%|█████▌    | 2631/4716 [12:13<07:55,  4.38it/s]

 56%|█████▌    | 2632/4716 [12:13<07:57,  4.37it/s]

 56%|█████▌    | 2633/4716 [12:14<07:56,  4.37it/s]

 56%|█████▌    | 2634/4716 [12:14<07:55,  4.38it/s]

 56%|█████▌    | 2635/4716 [12:14<07:55,  4.38it/s]

 56%|█████▌    | 2636/4716 [12:14<07:54,  4.38it/s]

 56%|█████▌    | 2637/4716 [12:14<07:54,  4.38it/s]

 56%|█████▌    | 2638/4716 [12:15<07:56,  4.36it/s]

 56%|█████▌    | 2639/4716 [12:15<07:55,  4.37it/s]

 56%|█████▌    | 2640/4716 [12:15<07:54,  4.37it/s]

 56%|█████▌    | 2641/4716 [12:15<07:54,  4.37it/s]

 56%|█████▌    | 2642/4716 [12:16<07:54,  4.37it/s]

 56%|█████▌    | 2643/4716 [12:16<07:54,  4.37it/s]

 56%|█████▌    | 2644/4716 [12:16<07:54,  4.37it/s]

 56%|█████▌    | 2645/4716 [12:16<07:52,  4.38it/s]

 56%|█████▌    | 2646/4716 [12:16<07:53,  4.38it/s]

 56%|█████▌    | 2647/4716 [12:17<07:52,  4.38it/s]

 56%|█████▌    | 2648/4716 [12:17<07:51,  4.38it/s]

 56%|█████▌    | 2649/4716 [12:17<07:52,  4.37it/s]

 56%|█████▌    | 2650/4716 [12:17<07:51,  4.38it/s]

 56%|█████▌    | 2651/4716 [12:18<07:51,  4.38it/s]

 56%|█████▌    | 2652/4716 [12:18<07:52,  4.37it/s]

 56%|█████▋    | 2653/4716 [12:18<07:52,  4.37it/s]

 56%|█████▋    | 2654/4716 [12:18<07:53,  4.36it/s]

 56%|█████▋    | 2655/4716 [12:19<07:51,  4.37it/s]

 56%|█████▋    | 2656/4716 [12:19<07:51,  4.37it/s]

 56%|█████▋    | 2657/4716 [12:19<07:52,  4.36it/s]

 56%|█████▋    | 2658/4716 [12:19<07:51,  4.37it/s]

 56%|█████▋    | 2659/4716 [12:19<07:52,  4.36it/s]

 56%|█████▋    | 2660/4716 [12:20<07:51,  4.36it/s]

 56%|█████▋    | 2661/4716 [12:20<07:50,  4.37it/s]

 56%|█████▋    | 2662/4716 [12:20<07:50,  4.36it/s]

 56%|█████▋    | 2663/4716 [12:20<07:49,  4.37it/s]

 56%|█████▋    | 2664/4716 [12:21<07:49,  4.37it/s]

 57%|█████▋    | 2665/4716 [12:21<07:50,  4.36it/s]

 57%|█████▋    | 2666/4716 [12:21<07:49,  4.36it/s]

 57%|█████▋    | 2667/4716 [12:21<07:50,  4.35it/s]

 57%|█████▋    | 2668/4716 [12:22<07:49,  4.36it/s]

 57%|█████▋    | 2669/4716 [12:22<07:49,  4.36it/s]

 57%|█████▋    | 2670/4716 [12:22<07:49,  4.36it/s]

 57%|█████▋    | 2671/4716 [12:22<07:48,  4.36it/s]

 57%|█████▋    | 2672/4716 [12:22<07:47,  4.37it/s]

 57%|█████▋    | 2673/4716 [12:23<07:47,  4.37it/s]

 57%|█████▋    | 2674/4716 [12:23<07:48,  4.36it/s]

 57%|█████▋    | 2675/4716 [12:23<07:47,  4.36it/s]

 57%|█████▋    | 2676/4716 [12:23<07:47,  4.36it/s]

 57%|█████▋    | 2677/4716 [12:24<07:47,  4.36it/s]

 57%|█████▋    | 2678/4716 [12:24<07:47,  4.36it/s]

 57%|█████▋    | 2679/4716 [12:24<07:48,  4.35it/s]

 57%|█████▋    | 2680/4716 [12:24<07:47,  4.35it/s]

 57%|█████▋    | 2681/4716 [12:25<07:46,  4.36it/s]

 57%|█████▋    | 2682/4716 [12:25<07:46,  4.36it/s]

 57%|█████▋    | 2683/4716 [12:25<07:45,  4.36it/s]

 57%|█████▋    | 2684/4716 [12:25<07:45,  4.37it/s]

 57%|█████▋    | 2685/4716 [12:25<07:45,  4.36it/s]

 57%|█████▋    | 2686/4716 [12:26<07:46,  4.35it/s]

 57%|█████▋    | 2687/4716 [12:26<07:46,  4.35it/s]

 57%|█████▋    | 2688/4716 [12:26<07:45,  4.36it/s]

 57%|█████▋    | 2689/4716 [12:26<07:46,  4.35it/s]

 57%|█████▋    | 2690/4716 [12:27<07:46,  4.35it/s]

 57%|█████▋    | 2691/4716 [12:27<07:45,  4.35it/s]

 57%|█████▋    | 2692/4716 [12:27<07:44,  4.35it/s]

 57%|█████▋    | 2693/4716 [12:27<07:44,  4.35it/s]

 57%|█████▋    | 2694/4716 [12:28<07:44,  4.36it/s]

 57%|█████▋    | 2695/4716 [12:28<07:44,  4.35it/s]

 57%|█████▋    | 2696/4716 [12:28<07:44,  4.35it/s]

 57%|█████▋    | 2697/4716 [12:28<07:43,  4.36it/s]

 57%|█████▋    | 2698/4716 [12:28<07:42,  4.36it/s]

 57%|█████▋    | 2699/4716 [12:29<07:42,  4.37it/s]

 57%|█████▋    | 2700/4716 [12:29<07:41,  4.36it/s]

 57%|█████▋    | 2701/4716 [12:29<07:43,  4.35it/s]

 57%|█████▋    | 2702/4716 [12:29<07:42,  4.35it/s]

 57%|█████▋    | 2703/4716 [12:30<07:42,  4.35it/s]

 57%|█████▋    | 2704/4716 [12:30<07:42,  4.35it/s]

 57%|█████▋    | 2705/4716 [12:30<07:41,  4.35it/s]

 57%|█████▋    | 2706/4716 [12:30<07:42,  4.34it/s]

 57%|█████▋    | 2707/4716 [12:30<07:42,  4.35it/s]

 57%|█████▋    | 2708/4716 [12:31<07:42,  4.34it/s]

 57%|█████▋    | 2709/4716 [12:31<07:41,  4.34it/s]

 57%|█████▋    | 2710/4716 [12:31<07:40,  4.36it/s]

 57%|█████▋    | 2711/4716 [12:31<07:40,  4.36it/s]

 58%|█████▊    | 2712/4716 [12:32<07:39,  4.36it/s]

 58%|█████▊    | 2713/4716 [12:32<07:41,  4.34it/s]

 58%|█████▊    | 2714/4716 [12:32<07:41,  4.34it/s]

 58%|█████▊    | 2715/4716 [12:32<07:40,  4.35it/s]

 58%|█████▊    | 2716/4716 [12:33<07:39,  4.36it/s]

 58%|█████▊    | 2717/4716 [12:33<07:38,  4.36it/s]

 58%|█████▊    | 2718/4716 [12:33<07:37,  4.36it/s]

 58%|█████▊    | 2719/4716 [12:33<07:38,  4.36it/s]

 58%|█████▊    | 2720/4716 [12:33<07:38,  4.35it/s]

 58%|█████▊    | 2721/4716 [12:34<07:37,  4.36it/s]

 58%|█████▊    | 2722/4716 [12:34<07:37,  4.36it/s]

 58%|█████▊    | 2723/4716 [12:34<07:36,  4.37it/s]

 58%|█████▊    | 2724/4716 [12:34<07:36,  4.37it/s]

 58%|█████▊    | 2725/4716 [12:35<07:36,  4.36it/s]

 58%|█████▊    | 2726/4716 [12:35<07:36,  4.36it/s]

 58%|█████▊    | 2727/4716 [12:35<07:36,  4.35it/s]

 58%|█████▊    | 2728/4716 [12:35<07:36,  4.35it/s]

 58%|█████▊    | 2729/4716 [12:36<07:35,  4.36it/s]

 58%|█████▊    | 2730/4716 [12:36<07:35,  4.36it/s]

 58%|█████▊    | 2731/4716 [12:36<07:36,  4.35it/s]

 58%|█████▊    | 2732/4716 [12:36<07:35,  4.35it/s]

 58%|█████▊    | 2733/4716 [12:36<07:36,  4.35it/s]

 58%|█████▊    | 2734/4716 [12:37<07:35,  4.35it/s]

 58%|█████▊    | 2735/4716 [12:37<07:35,  4.35it/s]

 58%|█████▊    | 2736/4716 [12:37<07:34,  4.36it/s]

 58%|█████▊    | 2737/4716 [12:37<07:33,  4.36it/s]

 58%|█████▊    | 2738/4716 [12:38<07:34,  4.35it/s]

 58%|█████▊    | 2739/4716 [12:38<07:34,  4.35it/s]

 58%|█████▊    | 2740/4716 [12:38<07:32,  4.36it/s]

 58%|█████▊    | 2741/4716 [12:38<07:32,  4.36it/s]

 58%|█████▊    | 2742/4716 [12:39<07:34,  4.35it/s]

 58%|█████▊    | 2743/4716 [12:39<07:33,  4.35it/s]

 58%|█████▊    | 2744/4716 [12:39<07:32,  4.35it/s]

 58%|█████▊    | 2745/4716 [12:39<07:32,  4.36it/s]

 58%|█████▊    | 2746/4716 [12:39<07:32,  4.35it/s]

 58%|█████▊    | 2747/4716 [12:40<07:32,  4.35it/s]

 58%|█████▊    | 2748/4716 [12:40<07:31,  4.36it/s]

 58%|█████▊    | 2749/4716 [12:40<07:32,  4.35it/s]

 58%|█████▊    | 2750/4716 [12:40<07:32,  4.35it/s]

 58%|█████▊    | 2751/4716 [12:41<07:31,  4.35it/s]

 58%|█████▊    | 2752/4716 [12:41<07:31,  4.35it/s]

 58%|█████▊    | 2753/4716 [12:41<07:31,  4.35it/s]

 58%|█████▊    | 2754/4716 [12:41<07:31,  4.35it/s]

 58%|█████▊    | 2755/4716 [12:42<07:30,  4.35it/s]

 58%|█████▊    | 2756/4716 [12:42<07:30,  4.35it/s]

 58%|█████▊    | 2757/4716 [12:42<07:30,  4.35it/s]

 58%|█████▊    | 2758/4716 [12:42<07:30,  4.34it/s]

 59%|█████▊    | 2759/4716 [12:42<07:29,  4.35it/s]

 59%|█████▊    | 2760/4716 [12:43<07:29,  4.35it/s]

 59%|█████▊    | 2761/4716 [12:43<07:29,  4.35it/s]

 59%|█████▊    | 2762/4716 [12:43<07:28,  4.35it/s]

 59%|█████▊    | 2763/4716 [12:43<07:29,  4.35it/s]

 59%|█████▊    | 2764/4716 [12:44<07:29,  4.34it/s]

 59%|█████▊    | 2765/4716 [12:44<07:27,  4.36it/s]

 59%|█████▊    | 2766/4716 [12:44<07:27,  4.36it/s]

 59%|█████▊    | 2767/4716 [12:44<07:26,  4.37it/s]

 59%|█████▊    | 2768/4716 [12:45<07:26,  4.36it/s]

 59%|█████▊    | 2769/4716 [12:45<07:26,  4.36it/s]

 59%|█████▊    | 2770/4716 [12:45<07:26,  4.36it/s]

 59%|█████▉    | 2771/4716 [12:45<07:26,  4.36it/s]

 59%|█████▉    | 2772/4716 [12:45<07:26,  4.35it/s]

 59%|█████▉    | 2773/4716 [12:46<07:25,  4.36it/s]

 59%|█████▉    | 2774/4716 [12:46<07:25,  4.35it/s]

 59%|█████▉    | 2775/4716 [12:46<07:25,  4.35it/s]

 59%|█████▉    | 2776/4716 [12:46<07:25,  4.35it/s]

 59%|█████▉    | 2777/4716 [12:47<07:25,  4.35it/s]

 59%|█████▉    | 2778/4716 [12:47<07:25,  4.35it/s]

 59%|█████▉    | 2779/4716 [12:47<07:25,  4.35it/s]

 59%|█████▉    | 2780/4716 [12:47<07:25,  4.34it/s]

 59%|█████▉    | 2781/4716 [12:47<07:25,  4.35it/s]

 59%|█████▉    | 2782/4716 [12:48<07:25,  4.34it/s]

 59%|█████▉    | 2783/4716 [12:48<07:26,  4.33it/s]

 59%|█████▉    | 2784/4716 [12:48<07:26,  4.33it/s]

 59%|█████▉    | 2785/4716 [12:48<07:25,  4.34it/s]

 59%|█████▉    | 2786/4716 [12:49<07:24,  4.34it/s]

 59%|█████▉    | 2787/4716 [12:49<07:24,  4.34it/s]

 59%|█████▉    | 2788/4716 [12:49<07:24,  4.34it/s]

 59%|█████▉    | 2789/4716 [12:49<07:24,  4.33it/s]

 59%|█████▉    | 2790/4716 [12:50<07:23,  4.35it/s]

 59%|█████▉    | 2791/4716 [12:50<07:22,  4.35it/s]

 59%|█████▉    | 2792/4716 [12:50<07:23,  4.34it/s]

 59%|█████▉    | 2793/4716 [12:50<07:22,  4.34it/s]

 59%|█████▉    | 2794/4716 [12:50<07:22,  4.34it/s]

 59%|█████▉    | 2795/4716 [12:51<07:23,  4.33it/s]

 59%|█████▉    | 2796/4716 [12:51<07:23,  4.33it/s]

 59%|█████▉    | 2797/4716 [12:51<07:23,  4.33it/s]

 59%|█████▉    | 2798/4716 [12:51<07:22,  4.34it/s]

 59%|█████▉    | 2799/4716 [12:52<07:21,  4.35it/s]

 59%|█████▉    | 2800/4716 [12:52<07:22,  4.33it/s]

 59%|█████▉    | 2801/4716 [12:52<07:20,  4.35it/s]

 59%|█████▉    | 2802/4716 [12:52<07:20,  4.35it/s]

 59%|█████▉    | 2803/4716 [12:53<07:19,  4.35it/s]

 59%|█████▉    | 2804/4716 [12:53<07:19,  4.35it/s]

 59%|█████▉    | 2805/4716 [12:53<07:20,  4.34it/s]

 59%|█████▉    | 2806/4716 [12:53<07:19,  4.35it/s]

 60%|█████▉    | 2807/4716 [12:53<07:18,  4.35it/s]

 60%|█████▉    | 2808/4716 [12:54<07:18,  4.35it/s]

 60%|█████▉    | 2809/4716 [12:54<07:17,  4.36it/s]

 60%|█████▉    | 2810/4716 [12:54<07:17,  4.35it/s]

 60%|█████▉    | 2811/4716 [12:54<07:17,  4.35it/s]

 60%|█████▉    | 2812/4716 [12:55<07:16,  4.36it/s]

 60%|█████▉    | 2813/4716 [12:55<07:16,  4.36it/s]

 60%|█████▉    | 2814/4716 [12:55<07:15,  4.36it/s]

 60%|█████▉    | 2815/4716 [12:55<07:15,  4.37it/s]

 60%|█████▉    | 2816/4716 [12:56<07:15,  4.36it/s]

 60%|█████▉    | 2817/4716 [12:56<07:15,  4.37it/s]

 60%|█████▉    | 2818/4716 [12:56<07:15,  4.36it/s]

 60%|█████▉    | 2819/4716 [12:56<07:15,  4.36it/s]

 60%|█████▉    | 2820/4716 [12:56<07:14,  4.36it/s]

 60%|█████▉    | 2821/4716 [12:57<07:15,  4.36it/s]

 60%|█████▉    | 2822/4716 [12:57<07:14,  4.36it/s]

 60%|█████▉    | 2823/4716 [12:57<07:14,  4.36it/s]

 60%|█████▉    | 2824/4716 [12:57<07:14,  4.36it/s]

 60%|█████▉    | 2825/4716 [12:58<07:13,  4.37it/s]

 60%|█████▉    | 2826/4716 [12:58<07:13,  4.36it/s]

 60%|█████▉    | 2827/4716 [12:58<07:14,  4.35it/s]

 60%|█████▉    | 2828/4716 [12:58<07:14,  4.35it/s]

 60%|█████▉    | 2829/4716 [12:59<07:14,  4.35it/s]

 60%|██████    | 2830/4716 [12:59<07:13,  4.35it/s]

 60%|██████    | 2831/4716 [12:59<07:12,  4.36it/s]

 60%|██████    | 2832/4716 [12:59<07:12,  4.35it/s]

 60%|██████    | 2833/4716 [12:59<07:12,  4.36it/s]

 60%|██████    | 2834/4716 [13:00<07:11,  4.36it/s]

 60%|██████    | 2835/4716 [13:00<07:13,  4.34it/s]

 60%|██████    | 2836/4716 [13:00<07:12,  4.35it/s]

 60%|██████    | 2837/4716 [13:00<07:13,  4.34it/s]

 60%|██████    | 2838/4716 [13:01<07:12,  4.34it/s]

 60%|██████    | 2839/4716 [13:01<07:12,  4.34it/s]

 60%|██████    | 2840/4716 [13:01<07:13,  4.33it/s]

 60%|██████    | 2841/4716 [13:01<07:12,  4.33it/s]

 60%|██████    | 2842/4716 [13:02<07:12,  4.34it/s]

 60%|██████    | 2843/4716 [13:02<07:12,  4.33it/s]

 60%|██████    | 2844/4716 [13:02<07:11,  4.34it/s]

 60%|██████    | 2845/4716 [13:02<07:11,  4.33it/s]

 60%|██████    | 2846/4716 [13:02<07:11,  4.33it/s]

 60%|██████    | 2847/4716 [13:03<07:11,  4.33it/s]

 60%|██████    | 2848/4716 [13:03<07:11,  4.33it/s]

 60%|██████    | 2849/4716 [13:03<07:10,  4.34it/s]

 60%|██████    | 2850/4716 [13:03<07:09,  4.35it/s]

 60%|██████    | 2851/4716 [13:04<07:08,  4.35it/s]

 60%|██████    | 2852/4716 [13:04<07:07,  4.36it/s]

 60%|██████    | 2853/4716 [13:04<07:07,  4.36it/s]

 61%|██████    | 2854/4716 [13:04<07:08,  4.35it/s]

 61%|██████    | 2855/4716 [13:05<07:07,  4.35it/s]

 61%|██████    | 2856/4716 [13:05<07:09,  4.33it/s]

 61%|██████    | 2857/4716 [13:05<07:08,  4.34it/s]

 61%|██████    | 2858/4716 [13:05<07:08,  4.33it/s]

 61%|██████    | 2859/4716 [13:05<07:08,  4.33it/s]

 61%|██████    | 2860/4716 [13:06<07:08,  4.33it/s]

 61%|██████    | 2861/4716 [13:06<07:09,  4.32it/s]

 61%|██████    | 2862/4716 [13:06<07:09,  4.31it/s]

 61%|██████    | 2863/4716 [13:06<07:10,  4.30it/s]

 61%|██████    | 2864/4716 [13:07<07:10,  4.30it/s]

 61%|██████    | 2865/4716 [13:07<07:08,  4.32it/s]

 61%|██████    | 2866/4716 [13:07<07:09,  4.31it/s]

 61%|██████    | 2867/4716 [13:07<07:08,  4.32it/s]

 61%|██████    | 2868/4716 [13:08<07:07,  4.33it/s]

 61%|██████    | 2869/4716 [13:08<07:06,  4.33it/s]

 61%|██████    | 2870/4716 [13:08<07:06,  4.33it/s]

 61%|██████    | 2871/4716 [13:08<07:05,  4.33it/s]

 61%|██████    | 2872/4716 [13:08<07:05,  4.33it/s]

 61%|██████    | 2873/4716 [13:09<07:05,  4.34it/s]

 61%|██████    | 2874/4716 [13:09<07:04,  4.34it/s]

 61%|██████    | 2875/4716 [13:09<07:04,  4.33it/s]

 61%|██████    | 2876/4716 [13:09<07:04,  4.34it/s]

 61%|██████    | 2877/4716 [13:10<07:03,  4.34it/s]

 61%|██████    | 2878/4716 [13:10<07:04,  4.33it/s]

 61%|██████    | 2879/4716 [13:10<07:03,  4.34it/s]

 61%|██████    | 2880/4716 [13:10<07:04,  4.33it/s]

 61%|██████    | 2881/4716 [13:11<07:03,  4.33it/s]

 61%|██████    | 2882/4716 [13:11<07:04,  4.32it/s]

 61%|██████    | 2883/4716 [13:11<07:03,  4.33it/s]

 61%|██████    | 2884/4716 [13:11<07:03,  4.33it/s]

 61%|██████    | 2885/4716 [13:11<07:03,  4.32it/s]

 61%|██████    | 2886/4716 [13:12<07:05,  4.30it/s]

 61%|██████    | 2887/4716 [13:12<07:04,  4.31it/s]

 61%|██████    | 2888/4716 [13:12<07:04,  4.31it/s]

 61%|██████▏   | 2889/4716 [13:12<07:03,  4.32it/s]

 61%|██████▏   | 2890/4716 [13:13<07:02,  4.32it/s]

 61%|██████▏   | 2891/4716 [13:13<07:02,  4.32it/s]

 61%|██████▏   | 2892/4716 [13:13<07:02,  4.32it/s]

 61%|██████▏   | 2893/4716 [13:13<07:01,  4.32it/s]

 61%|██████▏   | 2894/4716 [13:14<07:01,  4.32it/s]

 61%|██████▏   | 2895/4716 [13:14<07:01,  4.32it/s]

 61%|██████▏   | 2896/4716 [13:14<07:01,  4.32it/s]

 61%|██████▏   | 2897/4716 [13:14<07:00,  4.32it/s]

 61%|██████▏   | 2898/4716 [13:14<07:00,  4.32it/s]

 61%|██████▏   | 2899/4716 [13:15<07:00,  4.32it/s]

 61%|██████▏   | 2900/4716 [13:15<07:00,  4.32it/s]

 62%|██████▏   | 2901/4716 [13:15<07:00,  4.32it/s]

 62%|██████▏   | 2902/4716 [13:15<06:59,  4.32it/s]

 62%|██████▏   | 2903/4716 [13:16<06:59,  4.33it/s]

 62%|██████▏   | 2904/4716 [13:16<06:59,  4.32it/s]

 62%|██████▏   | 2905/4716 [13:16<06:58,  4.33it/s]

 62%|██████▏   | 2906/4716 [13:16<06:59,  4.32it/s]

 62%|██████▏   | 2907/4716 [13:17<07:03,  4.27it/s]

 62%|██████▏   | 2908/4716 [13:17<07:01,  4.29it/s]

 62%|██████▏   | 2909/4716 [13:17<07:00,  4.30it/s]

 62%|██████▏   | 2910/4716 [13:17<06:59,  4.31it/s]

 62%|██████▏   | 2911/4716 [13:17<06:59,  4.31it/s]

 62%|██████▏   | 2912/4716 [13:18<06:58,  4.31it/s]

 62%|██████▏   | 2913/4716 [13:18<06:57,  4.32it/s]

 62%|██████▏   | 2914/4716 [13:18<06:57,  4.32it/s]

 62%|██████▏   | 2915/4716 [13:18<06:56,  4.32it/s]

 62%|██████▏   | 2916/4716 [13:19<06:57,  4.31it/s]

 62%|██████▏   | 2917/4716 [13:19<06:56,  4.32it/s]

 62%|██████▏   | 2918/4716 [13:19<06:56,  4.32it/s]

 62%|██████▏   | 2919/4716 [13:19<06:56,  4.31it/s]

 62%|██████▏   | 2920/4716 [13:20<06:56,  4.32it/s]

 62%|██████▏   | 2921/4716 [13:20<06:55,  4.32it/s]

 62%|██████▏   | 2922/4716 [13:20<06:56,  4.31it/s]

 62%|██████▏   | 2923/4716 [13:20<06:55,  4.32it/s]

 62%|██████▏   | 2924/4716 [13:20<06:55,  4.32it/s]

 62%|██████▏   | 2925/4716 [13:21<06:55,  4.31it/s]

 62%|██████▏   | 2926/4716 [13:21<06:55,  4.31it/s]

 62%|██████▏   | 2927/4716 [13:21<06:55,  4.31it/s]

 62%|██████▏   | 2928/4716 [13:21<06:57,  4.29it/s]

 62%|██████▏   | 2929/4716 [13:22<06:56,  4.29it/s]

 62%|██████▏   | 2930/4716 [13:22<06:55,  4.30it/s]

 62%|██████▏   | 2931/4716 [13:22<06:55,  4.29it/s]

 62%|██████▏   | 2932/4716 [13:22<06:55,  4.29it/s]

 62%|██████▏   | 2933/4716 [13:23<06:55,  4.29it/s]

 62%|██████▏   | 2934/4716 [13:23<06:53,  4.30it/s]

 62%|██████▏   | 2935/4716 [13:23<06:54,  4.29it/s]

 62%|██████▏   | 2936/4716 [13:23<06:53,  4.31it/s]

 62%|██████▏   | 2937/4716 [13:24<06:53,  4.31it/s]

 62%|██████▏   | 2938/4716 [13:24<06:53,  4.30it/s]

 62%|██████▏   | 2939/4716 [13:24<06:52,  4.31it/s]

 62%|██████▏   | 2940/4716 [13:24<06:51,  4.31it/s]

 62%|██████▏   | 2941/4716 [13:24<06:51,  4.31it/s]

 62%|██████▏   | 2942/4716 [13:25<06:50,  4.32it/s]

 62%|██████▏   | 2943/4716 [13:25<06:51,  4.31it/s]

 62%|██████▏   | 2944/4716 [13:25<06:49,  4.32it/s]

 62%|██████▏   | 2945/4716 [13:25<06:49,  4.33it/s]

 62%|██████▏   | 2946/4716 [13:26<06:49,  4.32it/s]

 62%|██████▏   | 2947/4716 [13:26<06:50,  4.31it/s]

 63%|██████▎   | 2948/4716 [13:26<06:50,  4.31it/s]

 63%|██████▎   | 2949/4716 [13:26<06:49,  4.31it/s]

 63%|██████▎   | 2950/4716 [13:27<06:49,  4.32it/s]

 63%|██████▎   | 2951/4716 [13:27<06:50,  4.30it/s]

 63%|██████▎   | 2952/4716 [13:27<06:49,  4.31it/s]

 63%|██████▎   | 2953/4716 [13:27<06:49,  4.31it/s]

 63%|██████▎   | 2954/4716 [13:27<06:48,  4.31it/s]

 63%|██████▎   | 2955/4716 [13:28<06:47,  4.32it/s]

 63%|██████▎   | 2956/4716 [13:28<06:48,  4.31it/s]

 63%|██████▎   | 2957/4716 [13:28<06:47,  4.32it/s]

 63%|██████▎   | 2958/4716 [13:28<06:47,  4.31it/s]

 63%|██████▎   | 2959/4716 [13:29<06:47,  4.32it/s]

 63%|██████▎   | 2960/4716 [13:29<06:47,  4.31it/s]

 63%|██████▎   | 2961/4716 [13:29<06:47,  4.31it/s]

 63%|██████▎   | 2962/4716 [13:29<06:46,  4.31it/s]

 63%|██████▎   | 2963/4716 [13:30<06:45,  4.32it/s]

 63%|██████▎   | 2964/4716 [13:30<06:45,  4.32it/s]

 63%|██████▎   | 2965/4716 [13:30<06:44,  4.32it/s]

 63%|██████▎   | 2966/4716 [13:30<06:44,  4.33it/s]

 63%|██████▎   | 2967/4716 [13:30<06:44,  4.33it/s]

 63%|██████▎   | 2968/4716 [13:31<06:45,  4.32it/s]

 63%|██████▎   | 2969/4716 [13:31<06:44,  4.31it/s]

 63%|██████▎   | 2970/4716 [13:31<06:44,  4.32it/s]

 63%|██████▎   | 2971/4716 [13:31<06:44,  4.31it/s]

 63%|██████▎   | 2972/4716 [13:32<06:44,  4.31it/s]

 63%|██████▎   | 2973/4716 [13:32<06:43,  4.31it/s]

 63%|██████▎   | 2974/4716 [13:32<06:45,  4.30it/s]

 63%|██████▎   | 2975/4716 [13:32<06:44,  4.30it/s]

 63%|██████▎   | 2976/4716 [13:33<06:44,  4.30it/s]

 63%|██████▎   | 2977/4716 [13:33<06:44,  4.30it/s]

 63%|██████▎   | 2978/4716 [13:33<06:44,  4.30it/s]

 63%|██████▎   | 2979/4716 [13:33<06:44,  4.30it/s]

 63%|██████▎   | 2980/4716 [13:33<06:44,  4.29it/s]

 63%|██████▎   | 2981/4716 [13:34<06:44,  4.29it/s]

 63%|██████▎   | 2982/4716 [13:34<06:44,  4.29it/s]

 63%|██████▎   | 2983/4716 [13:34<06:43,  4.30it/s]

 63%|██████▎   | 2984/4716 [13:34<06:43,  4.30it/s]

 63%|██████▎   | 2985/4716 [13:35<06:42,  4.30it/s]

 63%|██████▎   | 2986/4716 [13:35<06:42,  4.30it/s]

 63%|██████▎   | 2987/4716 [13:35<06:41,  4.30it/s]

 63%|██████▎   | 2988/4716 [13:35<06:41,  4.30it/s]

 63%|██████▎   | 2989/4716 [13:36<06:42,  4.29it/s]

 63%|██████▎   | 2990/4716 [13:36<06:42,  4.29it/s]

 63%|██████▎   | 2991/4716 [13:36<06:41,  4.30it/s]

 63%|██████▎   | 2992/4716 [13:36<06:42,  4.29it/s]

 63%|██████▎   | 2993/4716 [13:37<06:41,  4.29it/s]

 63%|██████▎   | 2994/4716 [13:37<06:41,  4.29it/s]

 64%|██████▎   | 2995/4716 [13:37<06:41,  4.28it/s]

 64%|██████▎   | 2996/4716 [13:37<06:40,  4.29it/s]

 64%|██████▎   | 2997/4716 [13:37<06:39,  4.30it/s]

 64%|██████▎   | 2998/4716 [13:38<06:39,  4.30it/s]

 64%|██████▎   | 2999/4716 [13:38<06:39,  4.30it/s]

 64%|██████▎   | 3000/4716 [13:38<06:39,  4.29it/s]

 64%|██████▎   | 3001/4716 [13:38<06:38,  4.30it/s]

 64%|██████▎   | 3002/4716 [13:39<06:38,  4.30it/s]

 64%|██████▎   | 3003/4716 [13:39<06:38,  4.30it/s]

 64%|██████▎   | 3004/4716 [13:39<06:38,  4.30it/s]

 64%|██████▎   | 3005/4716 [13:39<06:38,  4.30it/s]

 64%|██████▎   | 3006/4716 [13:40<06:38,  4.30it/s]

 64%|██████▍   | 3007/4716 [13:40<06:37,  4.29it/s]

 64%|██████▍   | 3008/4716 [13:40<06:38,  4.29it/s]

 64%|██████▍   | 3009/4716 [13:40<06:37,  4.29it/s]

 64%|██████▍   | 3010/4716 [13:40<06:37,  4.29it/s]

 64%|██████▍   | 3011/4716 [13:41<06:36,  4.30it/s]

 64%|██████▍   | 3012/4716 [13:41<06:36,  4.29it/s]

 64%|██████▍   | 3013/4716 [13:41<06:36,  4.30it/s]

 64%|██████▍   | 3014/4716 [13:41<06:35,  4.30it/s]

 64%|██████▍   | 3015/4716 [13:42<06:35,  4.30it/s]

 64%|██████▍   | 3016/4716 [13:42<06:36,  4.29it/s]

 64%|██████▍   | 3017/4716 [13:42<06:34,  4.30it/s]

 64%|██████▍   | 3018/4716 [13:42<06:33,  4.31it/s]

 64%|██████▍   | 3019/4716 [13:43<06:33,  4.31it/s]

 64%|██████▍   | 3020/4716 [13:43<06:33,  4.31it/s]

 64%|██████▍   | 3021/4716 [13:43<06:34,  4.30it/s]

 64%|██████▍   | 3022/4716 [13:43<06:35,  4.29it/s]

 64%|██████▍   | 3023/4716 [13:43<06:35,  4.28it/s]

 64%|██████▍   | 3024/4716 [13:44<06:35,  4.28it/s]

 64%|██████▍   | 3025/4716 [13:44<06:35,  4.28it/s]

 64%|██████▍   | 3026/4716 [13:44<06:35,  4.27it/s]

 64%|██████▍   | 3027/4716 [13:44<06:35,  4.27it/s]

 64%|██████▍   | 3028/4716 [13:45<06:35,  4.27it/s]

 64%|██████▍   | 3029/4716 [13:45<06:35,  4.27it/s]

 64%|██████▍   | 3030/4716 [13:45<06:34,  4.28it/s]

 64%|██████▍   | 3031/4716 [13:45<06:34,  4.27it/s]

 64%|██████▍   | 3032/4716 [13:46<06:33,  4.28it/s]

 64%|██████▍   | 3033/4716 [13:46<06:33,  4.27it/s]

 64%|██████▍   | 3034/4716 [13:46<06:33,  4.27it/s]

 64%|██████▍   | 3035/4716 [13:46<06:33,  4.28it/s]

 64%|██████▍   | 3036/4716 [13:47<06:33,  4.27it/s]

 64%|██████▍   | 3037/4716 [13:47<06:32,  4.28it/s]

 64%|██████▍   | 3038/4716 [13:47<06:32,  4.28it/s]

 64%|██████▍   | 3039/4716 [13:47<06:33,  4.26it/s]

 64%|██████▍   | 3040/4716 [13:47<06:32,  4.27it/s]

 64%|██████▍   | 3041/4716 [13:48<06:31,  4.27it/s]

 65%|██████▍   | 3042/4716 [13:48<06:33,  4.26it/s]

 65%|██████▍   | 3043/4716 [13:48<06:33,  4.25it/s]

 65%|██████▍   | 3044/4716 [13:48<06:32,  4.26it/s]

 65%|██████▍   | 3045/4716 [13:49<06:32,  4.26it/s]

 65%|██████▍   | 3046/4716 [13:49<06:31,  4.26it/s]

 65%|██████▍   | 3047/4716 [13:49<06:31,  4.26it/s]

 65%|██████▍   | 3048/4716 [13:49<06:30,  4.28it/s]

 65%|██████▍   | 3049/4716 [13:50<06:30,  4.27it/s]

 65%|██████▍   | 3050/4716 [13:50<06:30,  4.26it/s]

 65%|██████▍   | 3051/4716 [13:50<06:30,  4.26it/s]

 65%|██████▍   | 3052/4716 [13:50<06:30,  4.26it/s]

 65%|██████▍   | 3053/4716 [13:51<06:30,  4.26it/s]

 65%|██████▍   | 3054/4716 [13:51<06:29,  4.26it/s]

 65%|██████▍   | 3055/4716 [13:51<06:32,  4.23it/s]

 65%|██████▍   | 3056/4716 [13:51<06:30,  4.25it/s]

 65%|██████▍   | 3057/4716 [13:51<06:30,  4.25it/s]

 65%|██████▍   | 3058/4716 [13:52<06:29,  4.25it/s]

 65%|██████▍   | 3059/4716 [13:52<06:29,  4.25it/s]

 65%|██████▍   | 3060/4716 [13:52<06:29,  4.25it/s]

 65%|██████▍   | 3061/4716 [13:52<06:29,  4.25it/s]

 65%|██████▍   | 3062/4716 [13:53<06:27,  4.26it/s]

 65%|██████▍   | 3063/4716 [13:53<06:29,  4.25it/s]

 65%|██████▍   | 3064/4716 [13:53<06:28,  4.25it/s]

 65%|██████▍   | 3065/4716 [13:53<06:28,  4.24it/s]

 65%|██████▌   | 3066/4716 [13:54<06:27,  4.25it/s]

 65%|██████▌   | 3067/4716 [13:54<06:26,  4.26it/s]

 65%|██████▌   | 3068/4716 [13:54<06:27,  4.26it/s]

 65%|██████▌   | 3069/4716 [13:54<06:25,  4.27it/s]

 65%|██████▌   | 3070/4716 [13:55<06:26,  4.26it/s]

 65%|██████▌   | 3071/4716 [13:55<06:26,  4.25it/s]

 65%|██████▌   | 3072/4716 [13:55<06:27,  4.24it/s]

 65%|██████▌   | 3073/4716 [13:55<06:27,  4.24it/s]

 65%|██████▌   | 3074/4716 [13:55<06:26,  4.25it/s]

 65%|██████▌   | 3075/4716 [13:56<06:26,  4.25it/s]

 65%|██████▌   | 3076/4716 [13:56<06:28,  4.22it/s]

 65%|██████▌   | 3077/4716 [13:56<06:26,  4.24it/s]

 65%|██████▌   | 3078/4716 [13:56<06:26,  4.24it/s]

 65%|██████▌   | 3079/4716 [13:57<06:25,  4.25it/s]

 65%|██████▌   | 3080/4716 [13:57<06:23,  4.26it/s]

 65%|██████▌   | 3081/4716 [13:57<06:25,  4.25it/s]

 65%|██████▌   | 3082/4716 [13:57<06:23,  4.26it/s]

 65%|██████▌   | 3083/4716 [13:58<06:23,  4.25it/s]

 65%|██████▌   | 3084/4716 [13:58<06:22,  4.26it/s]

 65%|██████▌   | 3085/4716 [13:58<06:22,  4.26it/s]

 65%|██████▌   | 3086/4716 [13:58<06:22,  4.26it/s]

 65%|██████▌   | 3087/4716 [13:59<06:21,  4.27it/s]

 65%|██████▌   | 3088/4716 [13:59<06:21,  4.27it/s]

 66%|██████▌   | 3089/4716 [13:59<06:20,  4.27it/s]

 66%|██████▌   | 3090/4716 [13:59<06:21,  4.26it/s]

 66%|██████▌   | 3091/4716 [13:59<06:23,  4.24it/s]

 66%|██████▌   | 3092/4716 [14:00<06:22,  4.25it/s]

 66%|██████▌   | 3093/4716 [14:00<06:22,  4.24it/s]

 66%|██████▌   | 3094/4716 [14:00<06:20,  4.26it/s]

 66%|██████▌   | 3095/4716 [14:00<06:20,  4.26it/s]

 66%|██████▌   | 3096/4716 [14:01<06:21,  4.24it/s]

 66%|██████▌   | 3097/4716 [14:01<06:21,  4.24it/s]

 66%|██████▌   | 3098/4716 [14:01<06:20,  4.25it/s]

 66%|██████▌   | 3099/4716 [14:01<06:19,  4.26it/s]

 66%|██████▌   | 3100/4716 [14:02<06:19,  4.26it/s]

 66%|██████▌   | 3101/4716 [14:02<06:19,  4.26it/s]

 66%|██████▌   | 3102/4716 [14:02<06:18,  4.26it/s]

 66%|██████▌   | 3103/4716 [14:02<06:18,  4.26it/s]

 66%|██████▌   | 3104/4716 [14:03<06:18,  4.26it/s]

 66%|██████▌   | 3105/4716 [14:03<06:18,  4.26it/s]

 66%|██████▌   | 3106/4716 [14:03<06:18,  4.26it/s]

 66%|██████▌   | 3107/4716 [14:03<06:18,  4.25it/s]

 66%|██████▌   | 3108/4716 [14:03<06:17,  4.26it/s]

 66%|██████▌   | 3109/4716 [14:04<06:16,  4.26it/s]

 66%|██████▌   | 3110/4716 [14:04<06:17,  4.26it/s]

 66%|██████▌   | 3111/4716 [14:04<06:17,  4.25it/s]

 66%|██████▌   | 3112/4716 [14:04<06:17,  4.25it/s]

 66%|██████▌   | 3113/4716 [14:05<06:16,  4.26it/s]

 66%|██████▌   | 3114/4716 [14:05<06:16,  4.26it/s]

 66%|██████▌   | 3115/4716 [14:05<06:15,  4.26it/s]

 66%|██████▌   | 3116/4716 [14:05<06:16,  4.24it/s]

 66%|██████▌   | 3117/4716 [14:06<06:16,  4.25it/s]

 66%|██████▌   | 3118/4716 [14:06<06:17,  4.23it/s]

 66%|██████▌   | 3119/4716 [14:06<06:16,  4.24it/s]

 66%|██████▌   | 3120/4716 [14:06<06:15,  4.25it/s]

 66%|██████▌   | 3121/4716 [14:07<06:15,  4.24it/s]

 66%|██████▌   | 3122/4716 [14:07<06:15,  4.25it/s]

 66%|██████▌   | 3123/4716 [14:07<06:14,  4.25it/s]

 66%|██████▌   | 3124/4716 [14:07<06:14,  4.25it/s]

 66%|██████▋   | 3125/4716 [14:07<06:14,  4.25it/s]

 66%|██████▋   | 3126/4716 [14:08<06:13,  4.26it/s]

 66%|██████▋   | 3127/4716 [14:08<06:12,  4.26it/s]

 66%|██████▋   | 3128/4716 [14:08<06:14,  4.24it/s]

 66%|██████▋   | 3129/4716 [14:08<06:13,  4.25it/s]

logging
logging the anndata

 66%|██████▋   | 3130/4716 [18:57<38:11:17, 86.68s/it]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 66%|██████▋   | 3131/4716 [18:57<26:44:48, 60.75s/it]

 66%|██████▋   | 3132/4716 [18:57<18:44:26, 42.59s/it]

 66%|██████▋   | 3133/4716 [18:57<13:08:23, 29.88s/it]

 66%|██████▋   | 3134/4716 [18:58<9:13:18, 20.99s/it]

 66%|██████▋   | 3135/4716 [18:58<6:28:50, 14.76s/it]

 66%|██████▋   | 3136/4716 [18:58<4:33:48, 10.40s/it]

 67%|██████▋   | 3137/4716 [18:58<3:13:19,  7.35s/it]

 67%|██████▋   | 3138/4716 [18:59<2:17:00,  5.21s/it]

 67%|██████▋   | 3139/4716 [18:59<1:37:37,  3.71s/it]

 67%|██████▋   | 3140/4716 [18:59<1:10:05,  2.67s/it]

 67%|██████▋   | 3141/4716 [18:59<50:47,  1.94s/it]

 67%|██████▋   | 3142/4716 [19:00<37:18,  1.42s/it]

 67%|██████▋   | 3143/4716 [19:00<27:51,  1.06s/it]

 67%|██████▋   | 3144/4716 [19:00<21:16,  1.23it/s]

 67%|██████▋   | 3145/4716 [19:00<16:39,  1.57it/s]

 67%|██████▋   | 3146/4716 [19:00<13:25,  1.95it/s]

 67%|██████▋   | 3147/4716 [19:01<11:09,  2.34it/s]

 67%|██████▋   | 3148/4716 [19:01<09:34,  2.73it/s]

 67%|██████▋   | 3149/4716 [19:01<08:27,  3.09it/s]

 67%|██████▋   | 3150/4716 [19:01<07:40,  3.40it/s]

 67%|██████▋   | 3151/4716 [19:02<07:07,  3.66it/s]

 67%|██████▋   | 3152/4716 [19:02<06:45,  3.86it/s]

 67%|██████▋   | 3153/4716 [19:02<06:28,  4.02it/s]

 67%|██████▋   | 3154/4716 [19:02<06:16,  4.14it/s]

 67%|██████▋   | 3155/4716 [19:02<06:09,  4.23it/s]

 67%|██████▋   | 3156/4716 [19:03<06:03,  4.29it/s]

 67%|██████▋   | 3157/4716 [19:03<05:59,  4.34it/s]

 67%|██████▋   | 3158/4716 [19:03<05:56,  4.37it/s]

 67%|██████▋   | 3159/4716 [19:03<05:55,  4.38it/s]

 67%|██████▋   | 3160/4716 [19:04<05:53,  4.40it/s]

 67%|██████▋   | 3161/4716 [19:04<05:53,  4.40it/s]

 67%|██████▋   | 3162/4716 [19:04<05:52,  4.41it/s]

 67%|██████▋   | 3163/4716 [19:04<05:52,  4.41it/s]

 67%|██████▋   | 3164/4716 [19:04<05:53,  4.39it/s]

 67%|██████▋   | 3165/4716 [19:05<05:53,  4.39it/s]

 67%|██████▋   | 3166/4716 [19:05<05:52,  4.40it/s]

 67%|██████▋   | 3167/4716 [19:05<05:51,  4.41it/s]

 67%|██████▋   | 3168/4716 [19:05<05:50,  4.42it/s]

 67%|██████▋   | 3169/4716 [19:06<05:49,  4.42it/s]

 67%|██████▋   | 3170/4716 [19:06<05:48,  4.43it/s]

 67%|██████▋   | 3171/4716 [19:06<05:48,  4.43it/s]

 67%|██████▋   | 3172/4716 [19:06<05:48,  4.42it/s]

 67%|██████▋   | 3173/4716 [19:07<05:48,  4.42it/s]

 67%|██████▋   | 3174/4716 [19:07<05:49,  4.42it/s]

 67%|██████▋   | 3175/4716 [19:07<05:49,  4.41it/s]

 67%|██████▋   | 3176/4716 [19:07<05:48,  4.42it/s]

 67%|██████▋   | 3177/4716 [19:07<05:47,  4.43it/s]

 67%|██████▋   | 3178/4716 [19:08<05:47,  4.43it/s]

 67%|██████▋   | 3179/4716 [19:08<05:46,  4.44it/s]

 67%|██████▋   | 3180/4716 [19:08<05:46,  4.44it/s]

 67%|██████▋   | 3181/4716 [19:08<05:47,  4.42it/s]

 67%|██████▋   | 3182/4716 [19:09<05:49,  4.39it/s]

 67%|██████▋   | 3183/4716 [19:09<05:48,  4.40it/s]

 68%|██████▊   | 3184/4716 [19:09<05:47,  4.41it/s]

 68%|██████▊   | 3185/4716 [19:09<05:48,  4.40it/s]

 68%|██████▊   | 3186/4716 [19:09<05:47,  4.40it/s]

 68%|██████▊   | 3187/4716 [19:10<05:46,  4.42it/s]

 68%|██████▊   | 3188/4716 [19:10<05:45,  4.42it/s]

 68%|██████▊   | 3189/4716 [19:10<05:45,  4.41it/s]

 68%|██████▊   | 3190/4716 [19:10<05:45,  4.42it/s]

 68%|██████▊   | 3191/4716 [19:11<05:45,  4.42it/s]

 68%|██████▊   | 3192/4716 [19:11<05:45,  4.41it/s]

 68%|██████▊   | 3193/4716 [19:11<05:45,  4.41it/s]

 68%|██████▊   | 3194/4716 [19:11<05:45,  4.40it/s]

 68%|██████▊   | 3195/4716 [19:11<05:45,  4.40it/s]

 68%|██████▊   | 3196/4716 [19:12<05:43,  4.42it/s]

 68%|██████▊   | 3197/4716 [19:12<05:43,  4.42it/s]

 68%|██████▊   | 3198/4716 [19:12<05:44,  4.41it/s]

 68%|██████▊   | 3199/4716 [19:12<05:43,  4.41it/s]

 68%|██████▊   | 3200/4716 [19:13<05:43,  4.41it/s]

 68%|██████▊   | 3201/4716 [19:13<05:42,  4.42it/s]

 68%|██████▊   | 3202/4716 [19:13<05:42,  4.42it/s]

 68%|██████▊   | 3203/4716 [19:13<05:42,  4.42it/s]

 68%|██████▊   | 3204/4716 [19:14<05:42,  4.41it/s]

 68%|██████▊   | 3205/4716 [19:14<05:42,  4.41it/s]

 68%|██████▊   | 3206/4716 [19:14<05:43,  4.40it/s]

 68%|██████▊   | 3207/4716 [19:14<05:42,  4.41it/s]

 68%|██████▊   | 3208/4716 [19:14<05:41,  4.41it/s]

 68%|██████▊   | 3209/4716 [19:15<05:41,  4.41it/s]

 68%|██████▊   | 3210/4716 [19:15<05:40,  4.42it/s]

 68%|██████▊   | 3211/4716 [19:15<05:40,  4.42it/s]

 68%|██████▊   | 3212/4716 [19:15<05:40,  4.42it/s]

 68%|██████▊   | 3213/4716 [19:16<05:39,  4.42it/s]

 68%|██████▊   | 3214/4716 [19:16<05:39,  4.42it/s]

 68%|██████▊   | 3215/4716 [19:16<05:40,  4.41it/s]

 68%|██████▊   | 3216/4716 [19:16<05:39,  4.41it/s]

 68%|██████▊   | 3217/4716 [19:16<05:40,  4.41it/s]

 68%|██████▊   | 3218/4716 [19:17<05:39,  4.41it/s]

 68%|██████▊   | 3219/4716 [19:17<05:38,  4.42it/s]

 68%|██████▊   | 3220/4716 [19:17<05:38,  4.42it/s]

 68%|██████▊   | 3221/4716 [19:17<05:38,  4.41it/s]

 68%|██████▊   | 3222/4716 [19:18<05:39,  4.41it/s]

 68%|██████▊   | 3223/4716 [19:18<05:39,  4.40it/s]

 68%|██████▊   | 3224/4716 [19:18<05:39,  4.39it/s]

 68%|██████▊   | 3225/4716 [19:18<05:39,  4.39it/s]

 68%|██████▊   | 3226/4716 [19:19<05:39,  4.39it/s]

 68%|██████▊   | 3227/4716 [19:19<05:39,  4.39it/s]

 68%|██████▊   | 3228/4716 [19:19<05:38,  4.39it/s]

 68%|██████▊   | 3229/4716 [19:19<05:38,  4.39it/s]

 68%|██████▊   | 3230/4716 [19:19<05:37,  4.41it/s]

 69%|██████▊   | 3231/4716 [19:20<05:37,  4.41it/s]

 69%|██████▊   | 3232/4716 [19:20<05:37,  4.40it/s]

 69%|██████▊   | 3233/4716 [19:20<05:36,  4.41it/s]

 69%|██████▊   | 3234/4716 [19:20<05:36,  4.40it/s]

 69%|██████▊   | 3235/4716 [19:21<05:36,  4.40it/s]

 69%|██████▊   | 3236/4716 [19:21<05:36,  4.39it/s]

 69%|██████▊   | 3237/4716 [19:21<05:36,  4.39it/s]

 69%|██████▊   | 3238/4716 [19:21<05:36,  4.40it/s]

 69%|██████▊   | 3239/4716 [19:21<05:35,  4.40it/s]

 69%|██████▊   | 3240/4716 [19:22<05:35,  4.40it/s]

 69%|██████▊   | 3241/4716 [19:22<05:35,  4.40it/s]

 69%|██████▊   | 3242/4716 [19:22<05:37,  4.37it/s]

 69%|██████▉   | 3243/4716 [19:22<05:36,  4.38it/s]

 69%|██████▉   | 3244/4716 [19:23<05:36,  4.38it/s]

 69%|██████▉   | 3245/4716 [19:23<05:35,  4.39it/s]

 69%|██████▉   | 3246/4716 [19:23<05:34,  4.39it/s]

 69%|██████▉   | 3247/4716 [19:23<05:34,  4.39it/s]

 69%|██████▉   | 3248/4716 [19:24<05:34,  4.38it/s]

 69%|██████▉   | 3249/4716 [19:24<05:34,  4.38it/s]

 69%|██████▉   | 3250/4716 [19:24<05:34,  4.38it/s]

 69%|██████▉   | 3251/4716 [19:24<05:33,  4.39it/s]

 69%|██████▉   | 3252/4716 [19:24<05:33,  4.39it/s]

 69%|██████▉   | 3253/4716 [19:25<05:32,  4.39it/s]

 69%|██████▉   | 3254/4716 [19:25<05:33,  4.39it/s]

 69%|██████▉   | 3255/4716 [19:25<05:33,  4.38it/s]

 69%|██████▉   | 3256/4716 [19:25<05:32,  4.38it/s]

 69%|██████▉   | 3257/4716 [19:26<05:31,  4.40it/s]

 69%|██████▉   | 3258/4716 [19:26<05:31,  4.39it/s]

 69%|██████▉   | 3259/4716 [19:26<05:31,  4.39it/s]

 69%|██████▉   | 3260/4716 [19:26<05:31,  4.39it/s]

 69%|██████▉   | 3261/4716 [19:26<05:31,  4.39it/s]

 69%|██████▉   | 3262/4716 [19:27<05:31,  4.39it/s]

 69%|██████▉   | 3263/4716 [19:27<05:31,  4.38it/s]

 69%|██████▉   | 3264/4716 [19:27<05:31,  4.38it/s]

 69%|██████▉   | 3265/4716 [19:27<05:31,  4.38it/s]

 69%|██████▉   | 3266/4716 [19:28<05:31,  4.38it/s]

 69%|██████▉   | 3267/4716 [19:28<05:30,  4.38it/s]

 69%|██████▉   | 3268/4716 [19:28<05:29,  4.39it/s]

 69%|██████▉   | 3269/4716 [19:28<05:29,  4.39it/s]

 69%|██████▉   | 3270/4716 [19:29<05:30,  4.38it/s]

 69%|██████▉   | 3271/4716 [19:29<05:30,  4.38it/s]

 69%|██████▉   | 3272/4716 [19:29<05:29,  4.38it/s]

 69%|██████▉   | 3273/4716 [19:29<05:29,  4.38it/s]

 69%|██████▉   | 3274/4716 [19:29<05:28,  4.39it/s]

 69%|██████▉   | 3275/4716 [19:30<05:29,  4.38it/s]

 69%|██████▉   | 3276/4716 [19:30<05:28,  4.38it/s]

 69%|██████▉   | 3277/4716 [19:30<05:27,  4.39it/s]

 70%|██████▉   | 3278/4716 [19:30<05:27,  4.39it/s]

 70%|██████▉   | 3279/4716 [19:31<05:27,  4.39it/s]

 70%|██████▉   | 3280/4716 [19:31<05:26,  4.39it/s]

 70%|██████▉   | 3281/4716 [19:31<05:26,  4.39it/s]

 70%|██████▉   | 3282/4716 [19:31<05:29,  4.36it/s]

 70%|██████▉   | 3283/4716 [19:32<05:28,  4.37it/s]

 70%|██████▉   | 3284/4716 [19:32<05:27,  4.37it/s]

 70%|██████▉   | 3285/4716 [19:32<05:27,  4.38it/s]

 70%|██████▉   | 3286/4716 [19:32<05:26,  4.37it/s]

 70%|██████▉   | 3287/4716 [19:32<05:26,  4.38it/s]

 70%|██████▉   | 3288/4716 [19:33<05:25,  4.39it/s]

 70%|██████▉   | 3289/4716 [19:33<05:24,  4.39it/s]

 70%|██████▉   | 3290/4716 [19:33<05:25,  4.38it/s]

 70%|██████▉   | 3291/4716 [19:33<05:24,  4.39it/s]

 70%|██████▉   | 3292/4716 [19:34<05:25,  4.38it/s]

 70%|██████▉   | 3293/4716 [19:34<05:27,  4.35it/s]

 70%|██████▉   | 3294/4716 [19:34<05:25,  4.36it/s]

 70%|██████▉   | 3295/4716 [19:34<05:25,  4.36it/s]

 70%|██████▉   | 3296/4716 [19:34<05:24,  4.38it/s]

 70%|██████▉   | 3297/4716 [19:35<05:24,  4.38it/s]

 70%|██████▉   | 3298/4716 [19:35<05:24,  4.37it/s]

 70%|██████▉   | 3299/4716 [19:35<05:23,  4.38it/s]

 70%|██████▉   | 3300/4716 [19:35<05:23,  4.38it/s]

 70%|██████▉   | 3301/4716 [19:36<05:23,  4.38it/s]

 70%|███████   | 3302/4716 [19:36<05:23,  4.37it/s]

 70%|███████   | 3303/4716 [19:36<05:23,  4.36it/s]

 70%|███████   | 3304/4716 [19:36<05:23,  4.37it/s]

 70%|███████   | 3305/4716 [19:37<05:23,  4.37it/s]

 70%|███████   | 3306/4716 [19:37<05:22,  4.37it/s]

 70%|███████   | 3307/4716 [19:37<05:22,  4.37it/s]

 70%|███████   | 3308/4716 [19:37<05:22,  4.37it/s]

 70%|███████   | 3309/4716 [19:37<05:22,  4.36it/s]

 70%|███████   | 3310/4716 [19:38<05:21,  4.37it/s]

 70%|███████   | 3311/4716 [19:38<05:21,  4.38it/s]

 70%|███████   | 3312/4716 [19:38<05:20,  4.38it/s]

 70%|███████   | 3313/4716 [19:38<05:20,  4.37it/s]

 70%|███████   | 3314/4716 [19:39<05:20,  4.37it/s]

 70%|███████   | 3315/4716 [19:39<05:20,  4.37it/s]

 70%|███████   | 3316/4716 [19:39<05:19,  4.38it/s]

 70%|███████   | 3317/4716 [19:39<05:20,  4.37it/s]

 70%|███████   | 3318/4716 [19:40<05:19,  4.38it/s]

 70%|███████   | 3319/4716 [19:40<05:19,  4.37it/s]

 70%|███████   | 3320/4716 [19:40<05:19,  4.37it/s]

 70%|███████   | 3321/4716 [19:40<05:18,  4.38it/s]

 70%|███████   | 3322/4716 [19:40<05:18,  4.38it/s]

 70%|███████   | 3323/4716 [19:41<05:18,  4.38it/s]

 70%|███████   | 3324/4716 [19:41<05:17,  4.38it/s]

 71%|███████   | 3325/4716 [19:41<05:17,  4.37it/s]

 71%|███████   | 3326/4716 [19:41<05:17,  4.38it/s]

 71%|███████   | 3327/4716 [19:42<05:17,  4.38it/s]

 71%|███████   | 3328/4716 [19:42<05:17,  4.37it/s]

 71%|███████   | 3329/4716 [19:42<05:17,  4.37it/s]

 71%|███████   | 3330/4716 [19:42<05:16,  4.38it/s]

 71%|███████   | 3331/4716 [19:42<05:16,  4.37it/s]

 71%|███████   | 3332/4716 [19:43<05:15,  4.39it/s]

 71%|███████   | 3333/4716 [19:43<05:15,  4.38it/s]

 71%|███████   | 3334/4716 [19:43<05:15,  4.38it/s]

 71%|███████   | 3335/4716 [19:43<05:15,  4.38it/s]

 71%|███████   | 3336/4716 [19:44<05:14,  4.38it/s]

 71%|███████   | 3337/4716 [19:44<05:14,  4.38it/s]

 71%|███████   | 3338/4716 [19:44<05:16,  4.35it/s]

 71%|███████   | 3339/4716 [19:44<05:16,  4.36it/s]

 71%|███████   | 3340/4716 [19:45<05:15,  4.36it/s]

 71%|███████   | 3341/4716 [19:45<05:15,  4.36it/s]

 71%|███████   | 3342/4716 [19:45<05:14,  4.36it/s]

 71%|███████   | 3343/4716 [19:45<05:13,  4.38it/s]

 71%|███████   | 3344/4716 [19:45<05:13,  4.38it/s]

 71%|███████   | 3345/4716 [19:46<05:13,  4.38it/s]

 71%|███████   | 3346/4716 [19:46<05:12,  4.38it/s]

 71%|███████   | 3347/4716 [19:46<05:12,  4.38it/s]

 71%|███████   | 3348/4716 [19:46<05:12,  4.38it/s]

 71%|███████   | 3349/4716 [19:47<05:11,  4.39it/s]

 71%|███████   | 3350/4716 [19:47<05:11,  4.38it/s]

 71%|███████   | 3351/4716 [19:47<05:11,  4.38it/s]

 71%|███████   | 3352/4716 [19:47<05:11,  4.38it/s]

 71%|███████   | 3353/4716 [19:48<05:11,  4.37it/s]

 71%|███████   | 3354/4716 [19:48<05:11,  4.38it/s]

 71%|███████   | 3355/4716 [19:48<05:11,  4.37it/s]

 71%|███████   | 3356/4716 [19:48<05:11,  4.37it/s]

 71%|███████   | 3357/4716 [19:48<05:10,  4.37it/s]

 71%|███████   | 3358/4716 [19:49<05:10,  4.38it/s]

 71%|███████   | 3359/4716 [19:49<05:10,  4.37it/s]

 71%|███████   | 3360/4716 [19:49<05:10,  4.37it/s]

 71%|███████▏  | 3361/4716 [19:49<05:10,  4.36it/s]

 71%|███████▏  | 3362/4716 [19:50<05:11,  4.34it/s]

 71%|███████▏  | 3363/4716 [19:50<05:10,  4.35it/s]

 71%|███████▏  | 3364/4716 [19:50<05:10,  4.35it/s]

 71%|███████▏  | 3365/4716 [19:50<05:09,  4.36it/s]

 71%|███████▏  | 3366/4716 [19:50<05:09,  4.37it/s]

 71%|███████▏  | 3367/4716 [19:51<05:08,  4.37it/s]

 71%|███████▏  | 3368/4716 [19:51<05:08,  4.38it/s]

 71%|███████▏  | 3369/4716 [19:51<05:07,  4.38it/s]

 71%|███████▏  | 3370/4716 [19:51<05:08,  4.37it/s]

 71%|███████▏  | 3371/4716 [19:52<05:07,  4.37it/s]

 72%|███████▏  | 3372/4716 [19:52<05:06,  4.38it/s]

 72%|███████▏  | 3373/4716 [19:52<05:07,  4.37it/s]

 72%|███████▏  | 3374/4716 [19:52<05:06,  4.37it/s]

 72%|███████▏  | 3375/4716 [19:53<05:06,  4.37it/s]

 72%|███████▏  | 3376/4716 [19:53<05:06,  4.38it/s]

 72%|███████▏  | 3377/4716 [19:53<05:05,  4.38it/s]

 72%|███████▏  | 3378/4716 [19:53<05:05,  4.38it/s]

 72%|███████▏  | 3379/4716 [19:53<05:05,  4.38it/s]

 72%|███████▏  | 3380/4716 [19:54<05:04,  4.38it/s]

 72%|███████▏  | 3381/4716 [19:54<05:04,  4.38it/s]

 72%|███████▏  | 3382/4716 [19:54<05:04,  4.39it/s]

 72%|███████▏  | 3383/4716 [19:54<05:04,  4.38it/s]

 72%|███████▏  | 3384/4716 [19:55<05:04,  4.37it/s]

 72%|███████▏  | 3385/4716 [19:55<05:03,  4.38it/s]

 72%|███████▏  | 3386/4716 [19:55<05:03,  4.38it/s]

 72%|███████▏  | 3387/4716 [19:55<05:03,  4.38it/s]

 72%|███████▏  | 3388/4716 [19:56<05:03,  4.38it/s]

 72%|███████▏  | 3389/4716 [19:56<05:03,  4.37it/s]

 72%|███████▏  | 3390/4716 [19:56<05:03,  4.38it/s]

 72%|███████▏  | 3391/4716 [19:56<05:02,  4.38it/s]

 72%|███████▏  | 3392/4716 [19:56<05:02,  4.38it/s]

 72%|███████▏  | 3393/4716 [19:57<05:01,  4.38it/s]

 72%|███████▏  | 3394/4716 [19:57<05:01,  4.38it/s]

 72%|███████▏  | 3395/4716 [19:57<05:02,  4.37it/s]

 72%|███████▏  | 3396/4716 [19:57<05:01,  4.38it/s]

 72%|███████▏  | 3397/4716 [19:58<05:01,  4.37it/s]

 72%|███████▏  | 3398/4716 [19:58<05:01,  4.37it/s]

 72%|███████▏  | 3399/4716 [19:58<05:01,  4.37it/s]

 72%|███████▏  | 3400/4716 [19:58<05:01,  4.37it/s]

 72%|███████▏  | 3401/4716 [19:58<05:00,  4.37it/s]

 72%|███████▏  | 3402/4716 [19:59<05:00,  4.37it/s]

 72%|███████▏  | 3403/4716 [19:59<05:01,  4.36it/s]

 72%|███████▏  | 3404/4716 [19:59<05:00,  4.37it/s]

 72%|███████▏  | 3405/4716 [19:59<05:00,  4.36it/s]

 72%|███████▏  | 3406/4716 [20:00<05:01,  4.34it/s]

 72%|███████▏  | 3407/4716 [20:00<05:01,  4.34it/s]

 72%|███████▏  | 3408/4716 [20:00<05:01,  4.34it/s]

 72%|███████▏  | 3409/4716 [20:00<04:59,  4.36it/s]

 72%|███████▏  | 3410/4716 [20:01<04:59,  4.37it/s]

 72%|███████▏  | 3411/4716 [20:01<04:59,  4.36it/s]

 72%|███████▏  | 3412/4716 [20:01<04:59,  4.36it/s]

 72%|███████▏  | 3413/4716 [20:01<04:58,  4.36it/s]

 72%|███████▏  | 3414/4716 [20:01<04:58,  4.36it/s]

 72%|███████▏  | 3415/4716 [20:02<04:57,  4.37it/s]

 72%|███████▏  | 3416/4716 [20:02<04:58,  4.36it/s]

 72%|███████▏  | 3417/4716 [20:02<04:58,  4.36it/s]

 72%|███████▏  | 3418/4716 [20:02<04:57,  4.37it/s]

 72%|███████▏  | 3419/4716 [20:03<04:57,  4.36it/s]

 73%|███████▎  | 3420/4716 [20:03<04:57,  4.36it/s]

 73%|███████▎  | 3421/4716 [20:03<04:56,  4.36it/s]

 73%|███████▎  | 3422/4716 [20:03<04:57,  4.35it/s]

 73%|███████▎  | 3423/4716 [20:04<04:56,  4.36it/s]

 73%|███████▎  | 3424/4716 [20:04<04:56,  4.36it/s]

 73%|███████▎  | 3425/4716 [20:04<04:56,  4.36it/s]

 73%|███████▎  | 3426/4716 [20:04<04:55,  4.37it/s]

 73%|███████▎  | 3427/4716 [20:04<04:55,  4.36it/s]

 73%|███████▎  | 3428/4716 [20:05<04:55,  4.36it/s]

 73%|███████▎  | 3429/4716 [20:05<04:55,  4.36it/s]

 73%|███████▎  | 3430/4716 [20:05<04:54,  4.36it/s]

 73%|███████▎  | 3431/4716 [20:05<04:56,  4.33it/s]

 73%|███████▎  | 3432/4716 [20:06<04:56,  4.33it/s]

 73%|███████▎  | 3433/4716 [20:06<04:54,  4.35it/s]

 73%|███████▎  | 3434/4716 [20:06<04:53,  4.37it/s]

 73%|███████▎  | 3435/4716 [20:06<04:53,  4.37it/s]

 73%|███████▎  | 3436/4716 [20:07<04:53,  4.36it/s]

 73%|███████▎  | 3437/4716 [20:07<04:52,  4.38it/s]

 73%|███████▎  | 3438/4716 [20:07<04:52,  4.37it/s]

 73%|███████▎  | 3439/4716 [20:07<04:51,  4.39it/s]

 73%|███████▎  | 3440/4716 [20:07<04:50,  4.39it/s]

 73%|███████▎  | 3441/4716 [20:08<04:50,  4.39it/s]

 73%|███████▎  | 3442/4716 [20:08<04:50,  4.39it/s]

 73%|███████▎  | 3443/4716 [20:08<04:49,  4.39it/s]

 73%|███████▎  | 3444/4716 [20:08<04:50,  4.38it/s]

 73%|███████▎  | 3445/4716 [20:09<04:49,  4.38it/s]

 73%|███████▎  | 3446/4716 [20:09<04:50,  4.38it/s]

 73%|███████▎  | 3447/4716 [20:09<04:53,  4.33it/s]

 73%|███████▎  | 3448/4716 [20:09<04:51,  4.34it/s]

 73%|███████▎  | 3449/4716 [20:10<04:50,  4.36it/s]

 73%|███████▎  | 3450/4716 [20:10<04:49,  4.38it/s]

 73%|███████▎  | 3451/4716 [20:10<04:48,  4.38it/s]

 73%|███████▎  | 3452/4716 [20:10<04:48,  4.38it/s]

 73%|███████▎  | 3453/4716 [20:10<04:48,  4.38it/s]

 73%|███████▎  | 3454/4716 [20:11<04:48,  4.38it/s]

 73%|███████▎  | 3455/4716 [20:11<04:48,  4.36it/s]

 73%|███████▎  | 3456/4716 [20:11<04:48,  4.37it/s]

 73%|███████▎  | 3457/4716 [20:11<04:47,  4.38it/s]

 73%|███████▎  | 3458/4716 [20:12<04:47,  4.38it/s]

 73%|███████▎  | 3459/4716 [20:12<04:47,  4.38it/s]

 73%|███████▎  | 3460/4716 [20:12<04:47,  4.37it/s]

 73%|███████▎  | 3461/4716 [20:12<04:47,  4.37it/s]

 73%|███████▎  | 3462/4716 [20:12<04:47,  4.37it/s]

 73%|███████▎  | 3463/4716 [20:13<04:47,  4.36it/s]

 73%|███████▎  | 3464/4716 [20:13<04:46,  4.37it/s]

 73%|███████▎  | 3465/4716 [20:13<04:46,  4.36it/s]

 73%|███████▎  | 3466/4716 [20:13<04:47,  4.35it/s]

 74%|███████▎  | 3467/4716 [20:14<04:46,  4.36it/s]

 74%|███████▎  | 3468/4716 [20:14<04:46,  4.36it/s]

 74%|███████▎  | 3469/4716 [20:14<04:45,  4.36it/s]

 74%|███████▎  | 3470/4716 [20:14<04:45,  4.36it/s]

 74%|███████▎  | 3471/4716 [20:15<04:45,  4.36it/s]

 74%|███████▎  | 3472/4716 [20:15<04:45,  4.36it/s]

 74%|███████▎  | 3473/4716 [20:15<04:44,  4.36it/s]

 74%|███████▎  | 3474/4716 [20:15<04:44,  4.37it/s]

 74%|███████▎  | 3475/4716 [20:15<04:43,  4.37it/s]

 74%|███████▎  | 3476/4716 [20:16<04:44,  4.36it/s]

 74%|███████▎  | 3477/4716 [20:16<04:43,  4.37it/s]

 74%|███████▎  | 3478/4716 [20:16<04:42,  4.38it/s]

 74%|███████▍  | 3479/4716 [20:16<04:42,  4.37it/s]

 74%|███████▍  | 3480/4716 [20:17<04:42,  4.38it/s]

 74%|███████▍  | 3481/4716 [20:17<04:42,  4.38it/s]

 74%|███████▍  | 3482/4716 [20:17<04:42,  4.37it/s]

 74%|███████▍  | 3483/4716 [20:17<04:42,  4.37it/s]

 74%|███████▍  | 3484/4716 [20:18<04:42,  4.36it/s]

 74%|███████▍  | 3485/4716 [20:18<04:43,  4.35it/s]

 74%|███████▍  | 3486/4716 [20:18<04:42,  4.35it/s]

 74%|███████▍  | 3487/4716 [20:18<04:42,  4.35it/s]

 74%|███████▍  | 3488/4716 [20:18<04:42,  4.35it/s]

 74%|███████▍  | 3489/4716 [20:19<04:41,  4.35it/s]

 74%|███████▍  | 3490/4716 [20:19<04:42,  4.35it/s]

 74%|███████▍  | 3491/4716 [20:19<04:41,  4.35it/s]

 74%|███████▍  | 3492/4716 [20:19<04:41,  4.35it/s]

 74%|███████▍  | 3493/4716 [20:20<04:41,  4.34it/s]

 74%|███████▍  | 3494/4716 [20:20<04:41,  4.35it/s]

 74%|███████▍  | 3495/4716 [20:20<04:40,  4.35it/s]

 74%|███████▍  | 3496/4716 [20:20<04:41,  4.34it/s]

 74%|███████▍  | 3497/4716 [20:21<04:40,  4.35it/s]

 74%|███████▍  | 3498/4716 [20:21<04:40,  4.34it/s]

 74%|███████▍  | 3499/4716 [20:21<04:40,  4.35it/s]

 74%|███████▍  | 3500/4716 [20:21<04:39,  4.36it/s]

 74%|███████▍  | 3501/4716 [20:21<04:39,  4.35it/s]

 74%|███████▍  | 3502/4716 [20:22<04:38,  4.36it/s]

 74%|███████▍  | 3503/4716 [20:22<04:38,  4.35it/s]

 74%|███████▍  | 3504/4716 [20:22<04:38,  4.35it/s]

 74%|███████▍  | 3505/4716 [20:22<04:38,  4.35it/s]

 74%|███████▍  | 3506/4716 [20:23<04:37,  4.36it/s]

 74%|███████▍  | 3507/4716 [20:23<04:37,  4.35it/s]

 74%|███████▍  | 3508/4716 [20:23<04:37,  4.36it/s]

 74%|███████▍  | 3509/4716 [20:23<04:37,  4.35it/s]

 74%|███████▍  | 3510/4716 [20:23<04:37,  4.34it/s]

 74%|███████▍  | 3511/4716 [20:24<04:37,  4.34it/s]

 74%|███████▍  | 3512/4716 [20:24<04:37,  4.34it/s]

 74%|███████▍  | 3513/4716 [20:24<04:36,  4.35it/s]

 75%|███████▍  | 3514/4716 [20:24<04:36,  4.35it/s]

 75%|███████▍  | 3515/4716 [20:25<04:36,  4.34it/s]

 75%|███████▍  | 3516/4716 [20:25<04:35,  4.36it/s]

 75%|███████▍  | 3517/4716 [20:25<04:35,  4.35it/s]

 75%|███████▍  | 3518/4716 [20:25<04:35,  4.34it/s]

 75%|███████▍  | 3519/4716 [20:26<04:35,  4.34it/s]

 75%|███████▍  | 3520/4716 [20:26<04:35,  4.34it/s]

 75%|███████▍  | 3521/4716 [20:26<04:35,  4.34it/s]

 75%|███████▍  | 3522/4716 [20:26<04:34,  4.35it/s]

 75%|███████▍  | 3523/4716 [20:26<04:34,  4.35it/s]

 75%|███████▍  | 3524/4716 [20:27<04:33,  4.35it/s]

 75%|███████▍  | 3525/4716 [20:27<04:34,  4.35it/s]

 75%|███████▍  | 3526/4716 [20:27<04:33,  4.34it/s]

 75%|███████▍  | 3527/4716 [20:27<04:33,  4.35it/s]

 75%|███████▍  | 3528/4716 [20:28<04:32,  4.35it/s]

 75%|███████▍  | 3529/4716 [20:28<04:32,  4.35it/s]

 75%|███████▍  | 3530/4716 [20:28<04:32,  4.35it/s]

 75%|███████▍  | 3531/4716 [20:28<04:32,  4.35it/s]

 75%|███████▍  | 3532/4716 [20:29<04:32,  4.35it/s]

 75%|███████▍  | 3533/4716 [20:29<04:32,  4.34it/s]

 75%|███████▍  | 3534/4716 [20:29<04:32,  4.34it/s]

 75%|███████▍  | 3535/4716 [20:29<04:31,  4.35it/s]

 75%|███████▍  | 3536/4716 [20:29<04:31,  4.34it/s]

 75%|███████▌  | 3537/4716 [20:30<04:31,  4.34it/s]

 75%|███████▌  | 3538/4716 [20:30<04:31,  4.34it/s]

 75%|███████▌  | 3539/4716 [20:30<04:31,  4.34it/s]

 75%|███████▌  | 3540/4716 [20:30<04:30,  4.34it/s]

 75%|███████▌  | 3541/4716 [20:31<04:30,  4.34it/s]

 75%|███████▌  | 3542/4716 [20:31<04:30,  4.33it/s]

 75%|███████▌  | 3543/4716 [20:31<04:30,  4.34it/s]

 75%|███████▌  | 3544/4716 [20:31<04:30,  4.33it/s]

 75%|███████▌  | 3545/4716 [20:32<04:30,  4.34it/s]

 75%|███████▌  | 3546/4716 [20:32<04:29,  4.35it/s]

 75%|███████▌  | 3547/4716 [20:32<04:29,  4.34it/s]

 75%|███████▌  | 3548/4716 [20:32<04:29,  4.34it/s]

 75%|███████▌  | 3549/4716 [20:32<04:28,  4.34it/s]

 75%|███████▌  | 3550/4716 [20:33<04:28,  4.34it/s]

 75%|███████▌  | 3551/4716 [20:33<04:28,  4.34it/s]

 75%|███████▌  | 3552/4716 [20:33<04:28,  4.34it/s]

 75%|███████▌  | 3553/4716 [20:33<04:27,  4.34it/s]

 75%|███████▌  | 3554/4716 [20:34<04:28,  4.33it/s]

 75%|███████▌  | 3555/4716 [20:34<04:28,  4.33it/s]

 75%|███████▌  | 3556/4716 [20:34<04:28,  4.32it/s]

 75%|███████▌  | 3557/4716 [20:34<04:27,  4.34it/s]

 75%|███████▌  | 3558/4716 [20:35<04:26,  4.35it/s]

 75%|███████▌  | 3559/4716 [20:35<04:26,  4.34it/s]

 75%|███████▌  | 3560/4716 [20:35<04:26,  4.34it/s]

 76%|███████▌  | 3561/4716 [20:35<04:25,  4.34it/s]

 76%|███████▌  | 3562/4716 [20:35<04:25,  4.34it/s]

 76%|███████▌  | 3563/4716 [20:36<04:25,  4.35it/s]

 76%|███████▌  | 3564/4716 [20:36<04:25,  4.34it/s]

 76%|███████▌  | 3565/4716 [20:36<04:25,  4.33it/s]

 76%|███████▌  | 3566/4716 [20:36<04:24,  4.34it/s]

 76%|███████▌  | 3567/4716 [20:37<04:24,  4.34it/s]

 76%|███████▌  | 3568/4716 [20:37<04:24,  4.35it/s]

 76%|███████▌  | 3569/4716 [20:37<04:24,  4.33it/s]

 76%|███████▌  | 3570/4716 [20:37<04:24,  4.33it/s]

 76%|███████▌  | 3571/4716 [20:38<04:23,  4.34it/s]

 76%|███████▌  | 3572/4716 [20:38<04:23,  4.34it/s]

 76%|███████▌  | 3573/4716 [20:38<04:23,  4.33it/s]

 76%|███████▌  | 3574/4716 [20:38<04:22,  4.34it/s]

 76%|███████▌  | 3575/4716 [20:38<04:23,  4.33it/s]

 76%|███████▌  | 3576/4716 [20:39<04:23,  4.33it/s]

 76%|███████▌  | 3577/4716 [20:39<04:24,  4.30it/s]

 76%|███████▌  | 3578/4716 [20:39<04:24,  4.31it/s]

 76%|███████▌  | 3579/4716 [20:39<04:23,  4.32it/s]

 76%|███████▌  | 3580/4716 [20:40<04:22,  4.33it/s]

 76%|███████▌  | 3581/4716 [20:40<04:22,  4.32it/s]

 76%|███████▌  | 3582/4716 [20:40<04:21,  4.34it/s]

 76%|███████▌  | 3583/4716 [20:40<04:21,  4.33it/s]

 76%|███████▌  | 3584/4716 [20:41<04:21,  4.33it/s]

 76%|███████▌  | 3585/4716 [20:41<04:21,  4.33it/s]

 76%|███████▌  | 3586/4716 [20:41<04:20,  4.33it/s]

 76%|███████▌  | 3587/4716 [20:41<04:20,  4.33it/s]

 76%|███████▌  | 3588/4716 [20:41<04:20,  4.34it/s]

 76%|███████▌  | 3589/4716 [20:42<04:20,  4.33it/s]

 76%|███████▌  | 3590/4716 [20:42<04:19,  4.34it/s]

 76%|███████▌  | 3591/4716 [20:42<04:18,  4.35it/s]

 76%|███████▌  | 3592/4716 [20:42<04:18,  4.35it/s]

 76%|███████▌  | 3593/4716 [20:43<04:17,  4.35it/s]

 76%|███████▌  | 3594/4716 [20:43<04:18,  4.35it/s]

 76%|███████▌  | 3595/4716 [20:43<04:17,  4.35it/s]

 76%|███████▋  | 3596/4716 [20:43<04:17,  4.34it/s]

 76%|███████▋  | 3597/4716 [20:44<04:18,  4.33it/s]

 76%|███████▋  | 3598/4716 [20:44<04:18,  4.33it/s]

 76%|███████▋  | 3599/4716 [20:44<04:17,  4.34it/s]

 76%|███████▋  | 3600/4716 [20:44<04:17,  4.33it/s]

 76%|███████▋  | 3601/4716 [20:44<04:17,  4.33it/s]

 76%|███████▋  | 3602/4716 [20:45<04:18,  4.31it/s]

 76%|███████▋  | 3603/4716 [20:45<04:17,  4.32it/s]

 76%|███████▋  | 3604/4716 [20:45<04:17,  4.32it/s]

 76%|███████▋  | 3605/4716 [20:45<04:17,  4.32it/s]

 76%|███████▋  | 3606/4716 [20:46<04:17,  4.32it/s]

 76%|███████▋  | 3607/4716 [20:46<04:16,  4.32it/s]

 77%|███████▋  | 3608/4716 [20:46<04:16,  4.32it/s]

 77%|███████▋  | 3609/4716 [20:46<04:16,  4.32it/s]

 77%|███████▋  | 3610/4716 [20:47<04:16,  4.32it/s]

 77%|███████▋  | 3611/4716 [20:47<04:15,  4.32it/s]

 77%|███████▋  | 3612/4716 [20:47<04:15,  4.32it/s]

 77%|███████▋  | 3613/4716 [20:47<04:15,  4.32it/s]

 77%|███████▋  | 3614/4716 [20:47<04:14,  4.32it/s]

 77%|███████▋  | 3615/4716 [20:48<04:14,  4.32it/s]

 77%|███████▋  | 3616/4716 [20:48<04:17,  4.27it/s]

 77%|███████▋  | 3617/4716 [20:48<04:16,  4.28it/s]

 77%|███████▋  | 3618/4716 [20:48<04:16,  4.29it/s]

 77%|███████▋  | 3619/4716 [20:49<04:15,  4.30it/s]

 77%|███████▋  | 3620/4716 [20:49<04:14,  4.30it/s]

 77%|███████▋  | 3621/4716 [20:49<04:14,  4.31it/s]

 77%|███████▋  | 3622/4716 [20:49<04:14,  4.30it/s]

 77%|███████▋  | 3623/4716 [20:50<04:13,  4.31it/s]

 77%|███████▋  | 3624/4716 [20:50<04:12,  4.32it/s]

 77%|███████▋  | 3625/4716 [20:50<04:12,  4.32it/s]

 77%|███████▋  | 3626/4716 [20:50<04:12,  4.32it/s]

 77%|███████▋  | 3627/4716 [20:50<04:11,  4.32it/s]

 77%|███████▋  | 3628/4716 [20:51<04:12,  4.32it/s]

 77%|███████▋  | 3629/4716 [20:51<04:11,  4.32it/s]

 77%|███████▋  | 3630/4716 [20:51<04:11,  4.32it/s]

 77%|███████▋  | 3631/4716 [20:51<04:11,  4.32it/s]

 77%|███████▋  | 3632/4716 [20:52<04:10,  4.32it/s]

 77%|███████▋  | 3633/4716 [20:52<04:10,  4.32it/s]

 77%|███████▋  | 3634/4716 [20:52<04:10,  4.32it/s]

 77%|███████▋  | 3635/4716 [20:52<04:09,  4.33it/s]

 77%|███████▋  | 3636/4716 [20:53<04:09,  4.33it/s]

 77%|███████▋  | 3637/4716 [20:53<04:09,  4.33it/s]

 77%|███████▋  | 3638/4716 [20:53<04:10,  4.31it/s]

 77%|███████▋  | 3639/4716 [20:53<04:10,  4.30it/s]

 77%|███████▋  | 3640/4716 [20:54<04:09,  4.32it/s]

 77%|███████▋  | 3641/4716 [20:54<04:09,  4.31it/s]

 77%|███████▋  | 3642/4716 [20:54<04:09,  4.31it/s]

 77%|███████▋  | 3643/4716 [20:54<04:08,  4.32it/s]

 77%|███████▋  | 3644/4716 [20:54<04:07,  4.33it/s]

 77%|███████▋  | 3645/4716 [20:55<04:08,  4.31it/s]

 77%|███████▋  | 3646/4716 [20:55<04:08,  4.31it/s]

 77%|███████▋  | 3647/4716 [20:55<04:08,  4.30it/s]

 77%|███████▋  | 3648/4716 [20:55<04:08,  4.30it/s]

 77%|███████▋  | 3649/4716 [20:56<04:07,  4.31it/s]

 77%|███████▋  | 3650/4716 [20:56<04:07,  4.31it/s]

 77%|███████▋  | 3651/4716 [20:56<04:07,  4.31it/s]

 77%|███████▋  | 3652/4716 [20:56<04:08,  4.29it/s]

 77%|███████▋  | 3653/4716 [20:57<04:07,  4.29it/s]

 77%|███████▋  | 3654/4716 [20:57<04:07,  4.29it/s]

 78%|███████▊  | 3655/4716 [20:57<04:08,  4.28it/s]

 78%|███████▊  | 3656/4716 [20:57<04:07,  4.29it/s]

 78%|███████▊  | 3657/4716 [20:57<04:07,  4.28it/s]

 78%|███████▊  | 3658/4716 [20:58<04:06,  4.29it/s]

 78%|███████▊  | 3659/4716 [20:58<04:06,  4.29it/s]

 78%|███████▊  | 3660/4716 [20:58<04:06,  4.28it/s]

 78%|███████▊  | 3661/4716 [20:58<04:05,  4.29it/s]

 78%|███████▊  | 3662/4716 [20:59<04:05,  4.29it/s]

 78%|███████▊  | 3663/4716 [20:59<04:05,  4.29it/s]

 78%|███████▊  | 3664/4716 [20:59<04:05,  4.29it/s]

 78%|███████▊  | 3665/4716 [20:59<04:06,  4.27it/s]

 78%|███████▊  | 3666/4716 [21:00<04:05,  4.28it/s]

 78%|███████▊  | 3667/4716 [21:00<04:04,  4.29it/s]

 78%|███████▊  | 3668/4716 [21:00<04:05,  4.27it/s]

 78%|███████▊  | 3669/4716 [21:00<04:05,  4.27it/s]

 78%|███████▊  | 3670/4716 [21:00<04:03,  4.29it/s]

 78%|███████▊  | 3671/4716 [21:01<04:03,  4.29it/s]

 78%|███████▊  | 3672/4716 [21:01<04:03,  4.29it/s]

 78%|███████▊  | 3673/4716 [21:01<04:03,  4.28it/s]

 78%|███████▊  | 3674/4716 [21:01<04:02,  4.29it/s]

 78%|███████▊  | 3675/4716 [21:02<04:02,  4.29it/s]

 78%|███████▊  | 3676/4716 [21:02<04:02,  4.29it/s]

 78%|███████▊  | 3677/4716 [21:02<04:03,  4.27it/s]

 78%|███████▊  | 3678/4716 [21:02<04:03,  4.27it/s]

 78%|███████▊  | 3679/4716 [21:03<04:02,  4.28it/s]

 78%|███████▊  | 3680/4716 [21:03<04:02,  4.27it/s]

 78%|███████▊  | 3681/4716 [21:03<04:01,  4.29it/s]

 78%|███████▊  | 3682/4716 [21:03<04:01,  4.29it/s]

 78%|███████▊  | 3683/4716 [21:04<04:01,  4.27it/s]

 78%|███████▊  | 3684/4716 [21:04<04:01,  4.28it/s]

 78%|███████▊  | 3685/4716 [21:04<04:01,  4.28it/s]

 78%|███████▊  | 3686/4716 [21:04<04:01,  4.27it/s]

 78%|███████▊  | 3687/4716 [21:04<04:00,  4.27it/s]

 78%|███████▊  | 3688/4716 [21:05<03:59,  4.28it/s]

 78%|███████▊  | 3689/4716 [21:05<03:59,  4.29it/s]

 78%|███████▊  | 3690/4716 [21:05<03:59,  4.28it/s]

 78%|███████▊  | 3691/4716 [21:05<04:00,  4.25it/s]

 78%|███████▊  | 3692/4716 [21:06<04:00,  4.26it/s]

 78%|███████▊  | 3693/4716 [21:06<03:59,  4.27it/s]

 78%|███████▊  | 3694/4716 [21:06<03:59,  4.27it/s]

 78%|███████▊  | 3695/4716 [21:06<03:58,  4.28it/s]

 78%|███████▊  | 3696/4716 [21:07<03:58,  4.28it/s]

 78%|███████▊  | 3697/4716 [21:07<03:58,  4.28it/s]

 78%|███████▊  | 3698/4716 [21:07<03:58,  4.28it/s]

 78%|███████▊  | 3699/4716 [21:07<03:57,  4.28it/s]

 78%|███████▊  | 3700/4716 [21:08<03:57,  4.28it/s]

 78%|███████▊  | 3701/4716 [21:08<03:57,  4.27it/s]

 78%|███████▊  | 3702/4716 [21:08<03:56,  4.28it/s]

 79%|███████▊  | 3703/4716 [21:08<03:57,  4.27it/s]

 79%|███████▊  | 3704/4716 [21:08<03:56,  4.28it/s]

 79%|███████▊  | 3705/4716 [21:09<03:56,  4.28it/s]

 79%|███████▊  | 3706/4716 [21:09<03:56,  4.28it/s]

 79%|███████▊  | 3707/4716 [21:09<03:55,  4.29it/s]

 79%|███████▊  | 3708/4716 [21:09<03:55,  4.27it/s]

 79%|███████▊  | 3709/4716 [21:10<03:55,  4.27it/s]

 79%|███████▊  | 3710/4716 [21:10<03:55,  4.27it/s]

 79%|███████▊  | 3711/4716 [21:10<03:54,  4.28it/s]

 79%|███████▊  | 3712/4716 [21:10<03:54,  4.28it/s]

 79%|███████▊  | 3713/4716 [21:11<03:53,  4.29it/s]

 79%|███████▉  | 3714/4716 [21:11<03:54,  4.28it/s]

 79%|███████▉  | 3715/4716 [21:11<03:54,  4.27it/s]

 79%|███████▉  | 3716/4716 [21:11<03:54,  4.27it/s]

 79%|███████▉  | 3717/4716 [21:11<03:53,  4.28it/s]

 79%|███████▉  | 3718/4716 [21:12<03:53,  4.28it/s]

 79%|███████▉  | 3719/4716 [21:12<03:53,  4.28it/s]

 79%|███████▉  | 3720/4716 [21:12<03:52,  4.28it/s]

 79%|███████▉  | 3721/4716 [21:12<03:52,  4.28it/s]

 79%|███████▉  | 3722/4716 [21:13<03:52,  4.28it/s]

 79%|███████▉  | 3723/4716 [21:13<03:52,  4.27it/s]

 79%|███████▉  | 3724/4716 [21:13<03:52,  4.26it/s]

 79%|███████▉  | 3725/4716 [21:13<03:52,  4.27it/s]

 79%|███████▉  | 3726/4716 [21:14<03:52,  4.26it/s]

 79%|███████▉  | 3727/4716 [21:14<03:51,  4.27it/s]

 79%|███████▉  | 3728/4716 [21:14<03:50,  4.28it/s]

 79%|███████▉  | 3729/4716 [21:14<03:50,  4.28it/s]

 79%|███████▉  | 3730/4716 [21:15<03:51,  4.26it/s]

 79%|███████▉  | 3731/4716 [21:15<03:51,  4.26it/s]

 79%|███████▉  | 3732/4716 [21:15<03:50,  4.27it/s]

 79%|███████▉  | 3733/4716 [21:15<03:50,  4.27it/s]

 79%|███████▉  | 3734/4716 [21:15<03:49,  4.27it/s]

 79%|███████▉  | 3735/4716 [21:16<03:49,  4.27it/s]

 79%|███████▉  | 3736/4716 [21:16<03:49,  4.27it/s]

 79%|███████▉  | 3737/4716 [21:16<03:49,  4.27it/s]

 79%|███████▉  | 3738/4716 [21:16<03:48,  4.27it/s]

 79%|███████▉  | 3739/4716 [21:17<03:48,  4.27it/s]

 79%|███████▉  | 3740/4716 [21:17<03:48,  4.27it/s]

 79%|███████▉  | 3741/4716 [21:17<03:48,  4.27it/s]

 79%|███████▉  | 3742/4716 [21:17<03:48,  4.27it/s]

 79%|███████▉  | 3743/4716 [21:18<03:48,  4.26it/s]

 79%|███████▉  | 3744/4716 [21:18<03:48,  4.25it/s]

 79%|███████▉  | 3745/4716 [21:18<03:48,  4.25it/s]

 79%|███████▉  | 3746/4716 [21:18<03:47,  4.26it/s]

 79%|███████▉  | 3747/4716 [21:19<03:47,  4.27it/s]

 79%|███████▉  | 3748/4716 [21:19<03:47,  4.26it/s]

 79%|███████▉  | 3749/4716 [21:19<03:46,  4.27it/s]

 80%|███████▉  | 3750/4716 [21:19<03:46,  4.27it/s]

 80%|███████▉  | 3751/4716 [21:19<03:45,  4.27it/s]

 80%|███████▉  | 3752/4716 [21:20<03:45,  4.28it/s]

 80%|███████▉  | 3753/4716 [21:20<03:45,  4.28it/s]

 80%|███████▉  | 3754/4716 [21:20<03:45,  4.27it/s]

 80%|███████▉  | 3755/4716 [21:20<03:44,  4.27it/s]

logging
logging the anndata

 80%|███████▉  | 3756/4716 [21:22<08:43,  1.83it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 80%|███████▉  | 3757/4716 [21:22<07:11,  2.22it/s]

 80%|███████▉  | 3758/4716 [21:22<06:07,  2.61it/s]

 80%|███████▉  | 3759/4716 [21:22<05:23,  2.96it/s]

 80%|███████▉  | 3760/4716 [21:23<04:52,  3.27it/s]

 80%|███████▉  | 3761/4716 [21:23<04:29,  3.54it/s]

 80%|███████▉  | 3762/4716 [21:23<04:14,  3.74it/s]

 80%|███████▉  | 3763/4716 [21:23<04:03,  3.92it/s]

 80%|███████▉  | 3764/4716 [21:23<03:55,  4.05it/s]

 80%|███████▉  | 3765/4716 [21:24<03:49,  4.15it/s]

 80%|███████▉  | 3766/4716 [21:24<03:45,  4.22it/s]

 80%|███████▉  | 3767/4716 [21:24<03:42,  4.26it/s]

 80%|███████▉  | 3768/4716 [21:24<03:40,  4.31it/s]

 80%|███████▉  | 3769/4716 [21:25<03:38,  4.33it/s]

 80%|███████▉  | 3770/4716 [21:25<03:37,  4.34it/s]

 80%|███████▉  | 3771/4716 [21:25<03:36,  4.36it/s]

 80%|███████▉  | 3772/4716 [21:25<03:36,  4.37it/s]

 80%|████████  | 3773/4716 [21:26<03:35,  4.37it/s]

 80%|████████  | 3774/4716 [21:26<03:34,  4.38it/s]

 80%|████████  | 3775/4716 [21:26<03:34,  4.39it/s]

 80%|████████  | 3776/4716 [21:26<03:33,  4.39it/s]

 80%|████████  | 3777/4716 [21:26<03:33,  4.39it/s]

 80%|████████  | 3778/4716 [21:27<03:33,  4.40it/s]

 80%|████████  | 3779/4716 [21:27<03:33,  4.40it/s]

 80%|████████  | 3780/4716 [21:27<03:32,  4.40it/s]

 80%|████████  | 3781/4716 [21:27<03:32,  4.40it/s]

 80%|████████  | 3782/4716 [21:28<03:32,  4.40it/s]

 80%|████████  | 3783/4716 [21:28<03:32,  4.38it/s]

 80%|████████  | 3784/4716 [21:28<03:32,  4.38it/s]

 80%|████████  | 3785/4716 [21:28<03:33,  4.37it/s]

 80%|████████  | 3786/4716 [21:29<03:32,  4.37it/s]

 80%|████████  | 3787/4716 [21:29<03:32,  4.38it/s]

 80%|████████  | 3788/4716 [21:29<03:32,  4.38it/s]

 80%|████████  | 3789/4716 [21:29<03:31,  4.38it/s]

 80%|████████  | 3790/4716 [21:29<03:31,  4.38it/s]

 80%|████████  | 3791/4716 [21:30<03:31,  4.38it/s]

 80%|████████  | 3792/4716 [21:30<03:30,  4.39it/s]

 80%|████████  | 3793/4716 [21:30<03:30,  4.40it/s]

 80%|████████  | 3794/4716 [21:30<03:29,  4.40it/s]

 80%|████████  | 3795/4716 [21:31<03:29,  4.39it/s]

 80%|████████  | 3796/4716 [21:31<03:29,  4.39it/s]

 81%|████████  | 3797/4716 [21:31<03:29,  4.38it/s]

 81%|████████  | 3798/4716 [21:31<03:29,  4.38it/s]

 81%|████████  | 3799/4716 [21:31<03:28,  4.39it/s]

 81%|████████  | 3800/4716 [21:32<03:29,  4.38it/s]

 81%|████████  | 3801/4716 [21:32<03:28,  4.38it/s]

 81%|████████  | 3802/4716 [21:32<03:28,  4.38it/s]

 81%|████████  | 3803/4716 [21:32<03:28,  4.37it/s]

 81%|████████  | 3804/4716 [21:33<03:28,  4.38it/s]

 81%|████████  | 3805/4716 [21:33<03:27,  4.38it/s]

 81%|████████  | 3806/4716 [21:33<03:27,  4.38it/s]

 81%|████████  | 3807/4716 [21:33<03:27,  4.38it/s]

 81%|████████  | 3808/4716 [21:34<03:27,  4.38it/s]

 81%|████████  | 3809/4716 [21:34<03:27,  4.38it/s]

 81%|████████  | 3810/4716 [21:34<03:26,  4.38it/s]

 81%|████████  | 3811/4716 [21:34<03:26,  4.38it/s]

 81%|████████  | 3812/4716 [21:34<03:26,  4.37it/s]

 81%|████████  | 3813/4716 [21:35<03:26,  4.38it/s]

 81%|████████  | 3814/4716 [21:35<03:26,  4.38it/s]

 81%|████████  | 3815/4716 [21:35<03:26,  4.37it/s]

 81%|████████  | 3816/4716 [21:35<03:25,  4.37it/s]

 81%|████████  | 3817/4716 [21:36<03:25,  4.37it/s]

 81%|████████  | 3818/4716 [21:36<03:25,  4.37it/s]

 81%|████████  | 3819/4716 [21:36<03:25,  4.36it/s]

 81%|████████  | 3820/4716 [21:36<03:25,  4.37it/s]

 81%|████████  | 3821/4716 [21:36<03:24,  4.38it/s]

 81%|████████  | 3822/4716 [21:37<03:24,  4.37it/s]

 81%|████████  | 3823/4716 [21:37<03:24,  4.37it/s]

 81%|████████  | 3824/4716 [21:37<03:24,  4.37it/s]

 81%|████████  | 3825/4716 [21:37<03:24,  4.37it/s]

 81%|████████  | 3826/4716 [21:38<03:23,  4.36it/s]

 81%|████████  | 3827/4716 [21:38<03:23,  4.38it/s]

 81%|████████  | 3828/4716 [21:38<03:22,  4.38it/s]

 81%|████████  | 3829/4716 [21:38<03:22,  4.38it/s]

 81%|████████  | 3830/4716 [21:39<03:21,  4.40it/s]

 81%|████████  | 3831/4716 [21:39<03:21,  4.38it/s]

 81%|████████▏ | 3832/4716 [21:39<03:22,  4.38it/s]

 81%|████████▏ | 3833/4716 [21:39<03:21,  4.38it/s]

 81%|████████▏ | 3834/4716 [21:39<03:21,  4.37it/s]

 81%|████████▏ | 3835/4716 [21:40<03:21,  4.37it/s]

 81%|████████▏ | 3836/4716 [21:40<03:22,  4.36it/s]

 81%|████████▏ | 3837/4716 [21:40<03:22,  4.35it/s]

 81%|████████▏ | 3838/4716 [21:40<03:21,  4.36it/s]

 81%|████████▏ | 3839/4716 [21:41<03:20,  4.37it/s]

 81%|████████▏ | 3840/4716 [21:41<03:20,  4.37it/s]

 81%|████████▏ | 3841/4716 [21:41<03:20,  4.37it/s]

 81%|████████▏ | 3842/4716 [21:41<03:19,  4.37it/s]

 81%|████████▏ | 3843/4716 [21:42<03:19,  4.37it/s]

 82%|████████▏ | 3844/4716 [21:42<03:19,  4.37it/s]

 82%|████████▏ | 3845/4716 [21:42<03:18,  4.38it/s]

 82%|████████▏ | 3846/4716 [21:42<03:18,  4.37it/s]

 82%|████████▏ | 3847/4716 [21:42<03:18,  4.38it/s]

 82%|████████▏ | 3848/4716 [21:43<03:18,  4.38it/s]

 82%|████████▏ | 3849/4716 [21:43<03:18,  4.37it/s]

 82%|████████▏ | 3850/4716 [21:43<03:18,  4.37it/s]

 82%|████████▏ | 3851/4716 [21:43<03:17,  4.37it/s]

 82%|████████▏ | 3852/4716 [21:44<03:17,  4.37it/s]

 82%|████████▏ | 3853/4716 [21:44<03:17,  4.38it/s]

 82%|████████▏ | 3854/4716 [21:44<03:17,  4.37it/s]

 82%|████████▏ | 3855/4716 [21:44<03:16,  4.37it/s]

 82%|████████▏ | 3856/4716 [21:44<03:16,  4.37it/s]

 82%|████████▏ | 3857/4716 [21:45<03:16,  4.37it/s]

 82%|████████▏ | 3858/4716 [21:45<03:16,  4.37it/s]

 82%|████████▏ | 3859/4716 [21:45<03:16,  4.37it/s]

 82%|████████▏ | 3860/4716 [21:45<03:16,  4.36it/s]

 82%|████████▏ | 3861/4716 [21:46<03:16,  4.35it/s]

 82%|████████▏ | 3862/4716 [21:46<03:16,  4.35it/s]

 82%|████████▏ | 3863/4716 [21:46<03:16,  4.35it/s]

 82%|████████▏ | 3864/4716 [21:46<03:15,  4.36it/s]

 82%|████████▏ | 3865/4716 [21:47<03:14,  4.37it/s]

 82%|████████▏ | 3866/4716 [21:47<03:14,  4.37it/s]

 82%|████████▏ | 3867/4716 [21:47<03:13,  4.38it/s]

 82%|████████▏ | 3868/4716 [21:47<03:13,  4.38it/s]

 82%|████████▏ | 3869/4716 [21:47<03:13,  4.37it/s]

 82%|████████▏ | 3870/4716 [21:48<03:13,  4.37it/s]

 82%|████████▏ | 3871/4716 [21:48<03:13,  4.37it/s]

 82%|████████▏ | 3872/4716 [21:48<03:13,  4.35it/s]

 82%|████████▏ | 3873/4716 [21:48<03:13,  4.36it/s]

 82%|████████▏ | 3874/4716 [21:49<03:13,  4.36it/s]

 82%|████████▏ | 3875/4716 [21:49<03:12,  4.37it/s]

 82%|████████▏ | 3876/4716 [21:49<03:12,  4.36it/s]

 82%|████████▏ | 3877/4716 [21:49<03:12,  4.37it/s]

 82%|████████▏ | 3878/4716 [21:50<03:11,  4.38it/s]

 82%|████████▏ | 3879/4716 [21:50<03:11,  4.38it/s]

 82%|████████▏ | 3880/4716 [21:50<03:11,  4.38it/s]

 82%|████████▏ | 3881/4716 [21:50<03:10,  4.38it/s]

 82%|████████▏ | 3882/4716 [21:50<03:10,  4.38it/s]

 82%|████████▏ | 3883/4716 [21:51<03:11,  4.36it/s]

 82%|████████▏ | 3884/4716 [21:51<03:10,  4.36it/s]

 82%|████████▏ | 3885/4716 [21:51<03:10,  4.36it/s]

 82%|████████▏ | 3886/4716 [21:51<03:10,  4.36it/s]

 82%|████████▏ | 3887/4716 [21:52<03:10,  4.36it/s]

 82%|████████▏ | 3888/4716 [21:52<03:10,  4.35it/s]

 82%|████████▏ | 3889/4716 [21:52<03:09,  4.36it/s]

 82%|████████▏ | 3890/4716 [21:52<03:09,  4.36it/s]

 83%|████████▎ | 3891/4716 [21:53<03:09,  4.36it/s]

 83%|████████▎ | 3892/4716 [21:53<03:10,  4.32it/s]

 83%|████████▎ | 3893/4716 [21:53<03:10,  4.33it/s]

 83%|████████▎ | 3894/4716 [21:53<03:09,  4.34it/s]

 83%|████████▎ | 3895/4716 [21:53<03:08,  4.35it/s]

 83%|████████▎ | 3896/4716 [21:54<03:08,  4.35it/s]

 83%|████████▎ | 3897/4716 [21:54<03:07,  4.36it/s]

 83%|████████▎ | 3898/4716 [21:54<03:07,  4.36it/s]

 83%|████████▎ | 3899/4716 [21:54<03:07,  4.36it/s]

 83%|████████▎ | 3900/4716 [21:55<03:07,  4.36it/s]

 83%|████████▎ | 3901/4716 [21:55<03:07,  4.36it/s]

 83%|████████▎ | 3902/4716 [21:55<03:07,  4.35it/s]

 83%|████████▎ | 3903/4716 [21:55<03:06,  4.36it/s]

 83%|████████▎ | 3904/4716 [21:56<03:06,  4.35it/s]

 83%|████████▎ | 3905/4716 [21:56<03:06,  4.36it/s]

 83%|████████▎ | 3906/4716 [21:56<03:06,  4.35it/s]

 83%|████████▎ | 3907/4716 [21:56<03:06,  4.34it/s]

 83%|████████▎ | 3908/4716 [21:56<03:05,  4.35it/s]

 83%|████████▎ | 3909/4716 [21:57<03:05,  4.35it/s]

 83%|████████▎ | 3910/4716 [21:57<03:07,  4.29it/s]

 83%|████████▎ | 3911/4716 [21:57<03:06,  4.32it/s]

 83%|████████▎ | 3912/4716 [21:57<03:05,  4.33it/s]

 83%|████████▎ | 3913/4716 [21:58<03:04,  4.34it/s]

 83%|████████▎ | 3914/4716 [21:58<03:04,  4.35it/s]

 83%|████████▎ | 3915/4716 [21:58<03:04,  4.34it/s]

 83%|████████▎ | 3916/4716 [21:58<03:03,  4.36it/s]

 83%|████████▎ | 3917/4716 [21:59<03:03,  4.36it/s]

 83%|████████▎ | 3918/4716 [21:59<03:03,  4.35it/s]

 83%|████████▎ | 3919/4716 [21:59<03:02,  4.36it/s]

 83%|████████▎ | 3920/4716 [21:59<03:02,  4.35it/s]

 83%|████████▎ | 3921/4716 [21:59<03:02,  4.35it/s]

 83%|████████▎ | 3922/4716 [22:00<03:02,  4.35it/s]

 83%|████████▎ | 3923/4716 [22:00<03:02,  4.34it/s]

 83%|████████▎ | 3924/4716 [22:00<03:02,  4.35it/s]

 83%|████████▎ | 3925/4716 [22:00<03:01,  4.35it/s]

 83%|████████▎ | 3926/4716 [22:01<03:01,  4.35it/s]

 83%|████████▎ | 3927/4716 [22:01<03:00,  4.36it/s]

 83%|████████▎ | 3928/4716 [22:01<03:00,  4.35it/s]

 83%|████████▎ | 3929/4716 [22:01<03:01,  4.33it/s]

 83%|████████▎ | 3930/4716 [22:01<03:01,  4.33it/s]

 83%|████████▎ | 3931/4716 [22:02<03:01,  4.34it/s]

 83%|████████▎ | 3932/4716 [22:02<03:00,  4.35it/s]

 83%|████████▎ | 3933/4716 [22:02<03:00,  4.35it/s]

 83%|████████▎ | 3934/4716 [22:02<02:59,  4.35it/s]

 83%|████████▎ | 3935/4716 [22:03<02:59,  4.36it/s]

 83%|████████▎ | 3936/4716 [22:03<02:59,  4.35it/s]

 83%|████████▎ | 3937/4716 [22:03<02:58,  4.35it/s]

 84%|████████▎ | 3938/4716 [22:03<02:58,  4.35it/s]

 84%|████████▎ | 3939/4716 [22:04<02:59,  4.34it/s]

 84%|████████▎ | 3940/4716 [22:04<02:58,  4.35it/s]

 84%|████████▎ | 3941/4716 [22:04<02:58,  4.35it/s]

 84%|████████▎ | 3942/4716 [22:04<02:58,  4.34it/s]

 84%|████████▎ | 3943/4716 [22:04<02:58,  4.34it/s]

 84%|████████▎ | 3944/4716 [22:05<02:57,  4.35it/s]

 84%|████████▎ | 3945/4716 [22:05<02:57,  4.35it/s]

 84%|████████▎ | 3946/4716 [22:05<02:57,  4.35it/s]

 84%|████████▎ | 3947/4716 [22:05<02:56,  4.35it/s]

 84%|████████▎ | 3948/4716 [22:06<02:56,  4.35it/s]

 84%|████████▎ | 3949/4716 [22:06<02:56,  4.35it/s]

 84%|████████▍ | 3950/4716 [22:06<02:55,  4.35it/s]

 84%|████████▍ | 3951/4716 [22:06<02:55,  4.36it/s]

 84%|████████▍ | 3952/4716 [22:07<02:55,  4.35it/s]

 84%|████████▍ | 3953/4716 [22:07<02:55,  4.35it/s]

 84%|████████▍ | 3954/4716 [22:07<02:54,  4.36it/s]

 84%|████████▍ | 3955/4716 [22:07<02:54,  4.36it/s]

 84%|████████▍ | 3956/4716 [22:07<02:55,  4.34it/s]

 84%|████████▍ | 3957/4716 [22:08<02:54,  4.34it/s]

 84%|████████▍ | 3958/4716 [22:08<02:54,  4.34it/s]

 84%|████████▍ | 3959/4716 [22:08<02:54,  4.35it/s]

 84%|████████▍ | 3960/4716 [22:08<02:53,  4.35it/s]

 84%|████████▍ | 3961/4716 [22:09<02:53,  4.34it/s]

 84%|████████▍ | 3962/4716 [22:09<02:53,  4.34it/s]

 84%|████████▍ | 3963/4716 [22:09<02:53,  4.34it/s]

 84%|████████▍ | 3964/4716 [22:09<02:53,  4.33it/s]

 84%|████████▍ | 3965/4716 [22:10<02:53,  4.33it/s]

 84%|████████▍ | 3966/4716 [22:10<02:52,  4.34it/s]

 84%|████████▍ | 3967/4716 [22:10<02:52,  4.35it/s]

 84%|████████▍ | 3968/4716 [22:10<02:51,  4.35it/s]

 84%|████████▍ | 3969/4716 [22:10<02:51,  4.35it/s]

 84%|████████▍ | 3970/4716 [22:11<02:51,  4.35it/s]

 84%|████████▍ | 3971/4716 [22:11<02:51,  4.35it/s]

 84%|████████▍ | 3972/4716 [22:11<02:51,  4.34it/s]

 84%|████████▍ | 3973/4716 [22:11<02:50,  4.35it/s]

 84%|████████▍ | 3974/4716 [22:12<02:50,  4.35it/s]

 84%|████████▍ | 3975/4716 [22:12<02:50,  4.34it/s]

 84%|████████▍ | 3976/4716 [22:12<02:50,  4.35it/s]

 84%|████████▍ | 3977/4716 [22:12<02:49,  4.35it/s]

 84%|████████▍ | 3978/4716 [22:13<02:49,  4.36it/s]

 84%|████████▍ | 3979/4716 [22:13<02:49,  4.35it/s]

 84%|████████▍ | 3980/4716 [22:13<02:49,  4.33it/s]

 84%|████████▍ | 3981/4716 [22:13<02:49,  4.33it/s]

 84%|████████▍ | 3982/4716 [22:13<02:49,  4.33it/s]

 84%|████████▍ | 3983/4716 [22:14<02:49,  4.33it/s]

 84%|████████▍ | 3984/4716 [22:14<02:48,  4.34it/s]

 84%|████████▍ | 3985/4716 [22:14<02:48,  4.34it/s]

 85%|████████▍ | 3986/4716 [22:14<02:47,  4.35it/s]

 85%|████████▍ | 3987/4716 [22:15<02:47,  4.35it/s]

 85%|████████▍ | 3988/4716 [22:15<02:47,  4.34it/s]

 85%|████████▍ | 3989/4716 [22:15<02:47,  4.35it/s]

 85%|████████▍ | 3990/4716 [22:15<02:47,  4.34it/s]

 85%|████████▍ | 3991/4716 [22:16<02:46,  4.35it/s]

 85%|████████▍ | 3992/4716 [22:16<02:46,  4.35it/s]

 85%|████████▍ | 3993/4716 [22:16<02:46,  4.34it/s]

 85%|████████▍ | 3994/4716 [22:16<02:46,  4.34it/s]

 85%|████████▍ | 3995/4716 [22:16<02:46,  4.33it/s]

 85%|████████▍ | 3996/4716 [22:17<02:46,  4.33it/s]

 85%|████████▍ | 3997/4716 [22:17<02:45,  4.34it/s]

 85%|████████▍ | 3998/4716 [22:17<02:45,  4.35it/s]

 85%|████████▍ | 3999/4716 [22:17<02:45,  4.33it/s]

 85%|████████▍ | 4000/4716 [22:18<02:45,  4.34it/s]

 85%|████████▍ | 4001/4716 [22:18<02:44,  4.34it/s]

 85%|████████▍ | 4002/4716 [22:18<02:44,  4.35it/s]

 85%|████████▍ | 4003/4716 [22:18<02:44,  4.34it/s]

 85%|████████▍ | 4004/4716 [22:19<02:43,  4.34it/s]

 85%|████████▍ | 4005/4716 [22:19<02:44,  4.33it/s]

 85%|████████▍ | 4006/4716 [22:19<02:43,  4.33it/s]

 85%|████████▍ | 4007/4716 [22:19<02:45,  4.30it/s]

 85%|████████▍ | 4008/4716 [22:19<02:44,  4.31it/s]

 85%|████████▌ | 4009/4716 [22:20<02:43,  4.32it/s]

 85%|████████▌ | 4010/4716 [22:20<02:42,  4.33it/s]

 85%|████████▌ | 4011/4716 [22:20<02:42,  4.34it/s]

 85%|████████▌ | 4012/4716 [22:20<02:42,  4.34it/s]

 85%|████████▌ | 4013/4716 [22:21<02:41,  4.35it/s]

 85%|████████▌ | 4014/4716 [22:21<02:41,  4.34it/s]

 85%|████████▌ | 4015/4716 [22:21<02:41,  4.34it/s]

 85%|████████▌ | 4016/4716 [22:21<02:41,  4.34it/s]

 85%|████████▌ | 4017/4716 [22:22<02:40,  4.35it/s]

 85%|████████▌ | 4018/4716 [22:22<02:40,  4.35it/s]

 85%|████████▌ | 4019/4716 [22:22<02:39,  4.36it/s]

 85%|████████▌ | 4020/4716 [22:22<02:39,  4.35it/s]

 85%|████████▌ | 4021/4716 [22:22<02:39,  4.36it/s]

 85%|████████▌ | 4022/4716 [22:23<02:39,  4.35it/s]

 85%|████████▌ | 4023/4716 [22:23<02:39,  4.34it/s]

 85%|████████▌ | 4024/4716 [22:23<02:39,  4.35it/s]

 85%|████████▌ | 4025/4716 [22:23<02:39,  4.33it/s]

 85%|████████▌ | 4026/4716 [22:24<02:39,  4.33it/s]

 85%|████████▌ | 4027/4716 [22:24<02:38,  4.34it/s]

 85%|████████▌ | 4028/4716 [22:24<02:38,  4.34it/s]

 85%|████████▌ | 4029/4716 [22:24<02:38,  4.34it/s]

 85%|████████▌ | 4030/4716 [22:25<02:38,  4.34it/s]

 85%|████████▌ | 4031/4716 [22:25<02:38,  4.32it/s]

 85%|████████▌ | 4032/4716 [22:25<02:38,  4.32it/s]

 86%|████████▌ | 4033/4716 [22:25<02:37,  4.33it/s]

 86%|████████▌ | 4034/4716 [22:25<02:37,  4.33it/s]

 86%|████████▌ | 4035/4716 [22:26<02:37,  4.33it/s]

 86%|████████▌ | 4036/4716 [22:26<02:37,  4.33it/s]

 86%|████████▌ | 4037/4716 [22:26<02:36,  4.33it/s]

 86%|████████▌ | 4038/4716 [22:26<02:36,  4.34it/s]

 86%|████████▌ | 4039/4716 [22:27<02:36,  4.34it/s]

 86%|████████▌ | 4040/4716 [22:27<02:36,  4.32it/s]

 86%|████████▌ | 4041/4716 [22:27<02:36,  4.33it/s]

 86%|████████▌ | 4042/4716 [22:27<02:35,  4.33it/s]

 86%|████████▌ | 4043/4716 [22:28<02:35,  4.33it/s]

 86%|████████▌ | 4044/4716 [22:28<02:35,  4.33it/s]

 86%|████████▌ | 4045/4716 [22:28<02:34,  4.33it/s]

 86%|████████▌ | 4046/4716 [22:28<02:34,  4.33it/s]

 86%|████████▌ | 4047/4716 [22:28<02:34,  4.34it/s]

 86%|████████▌ | 4048/4716 [22:29<02:34,  4.33it/s]

 86%|████████▌ | 4049/4716 [22:29<02:33,  4.33it/s]

 86%|████████▌ | 4050/4716 [22:29<02:33,  4.33it/s]

 86%|████████▌ | 4051/4716 [22:29<02:33,  4.33it/s]

 86%|████████▌ | 4052/4716 [22:30<02:33,  4.33it/s]

 86%|████████▌ | 4053/4716 [22:30<02:32,  4.34it/s]

 86%|████████▌ | 4054/4716 [22:30<02:32,  4.33it/s]

 86%|████████▌ | 4055/4716 [22:30<02:32,  4.34it/s]

 86%|████████▌ | 4056/4716 [22:31<02:32,  4.34it/s]

 86%|████████▌ | 4057/4716 [22:31<02:32,  4.33it/s]

 86%|████████▌ | 4058/4716 [22:31<02:31,  4.34it/s]

 86%|████████▌ | 4059/4716 [22:31<02:31,  4.34it/s]

 86%|████████▌ | 4060/4716 [22:31<02:31,  4.34it/s]

 86%|████████▌ | 4061/4716 [22:32<02:30,  4.34it/s]

 86%|████████▌ | 4062/4716 [22:32<02:30,  4.35it/s]

 86%|████████▌ | 4063/4716 [22:32<02:30,  4.35it/s]

 86%|████████▌ | 4064/4716 [22:32<02:30,  4.35it/s]

 86%|████████▌ | 4065/4716 [22:33<02:30,  4.34it/s]

 86%|████████▌ | 4066/4716 [22:33<02:29,  4.35it/s]

 86%|████████▌ | 4067/4716 [22:33<02:29,  4.35it/s]

 86%|████████▋ | 4068/4716 [22:33<02:28,  4.35it/s]

 86%|████████▋ | 4069/4716 [22:34<02:28,  4.35it/s]

 86%|████████▋ | 4070/4716 [22:34<02:28,  4.35it/s]

 86%|████████▋ | 4071/4716 [22:34<02:28,  4.35it/s]

 86%|████████▋ | 4072/4716 [22:34<02:27,  4.36it/s]

 86%|████████▋ | 4073/4716 [22:34<02:27,  4.36it/s]

 86%|████████▋ | 4074/4716 [22:35<02:27,  4.35it/s]

 86%|████████▋ | 4075/4716 [22:35<02:27,  4.35it/s]

 86%|████████▋ | 4076/4716 [22:35<02:27,  4.35it/s]

 86%|████████▋ | 4077/4716 [22:35<02:26,  4.36it/s]

 86%|████████▋ | 4078/4716 [22:36<02:26,  4.35it/s]

 86%|████████▋ | 4079/4716 [22:36<02:26,  4.35it/s]

 87%|████████▋ | 4080/4716 [22:36<02:26,  4.35it/s]

 87%|████████▋ | 4081/4716 [22:36<02:26,  4.33it/s]

 87%|████████▋ | 4082/4716 [22:37<02:26,  4.33it/s]

 87%|████████▋ | 4083/4716 [22:37<02:26,  4.33it/s]

 87%|████████▋ | 4084/4716 [22:37<02:26,  4.32it/s]

 87%|████████▋ | 4085/4716 [22:37<02:26,  4.31it/s]

 87%|████████▋ | 4086/4716 [22:37<02:25,  4.32it/s]

 87%|████████▋ | 4087/4716 [22:38<02:25,  4.33it/s]

 87%|████████▋ | 4088/4716 [22:38<02:25,  4.33it/s]

 87%|████████▋ | 4089/4716 [22:38<02:24,  4.33it/s]

 87%|████████▋ | 4090/4716 [22:38<02:24,  4.33it/s]

 87%|████████▋ | 4091/4716 [22:39<02:24,  4.33it/s]

 87%|████████▋ | 4092/4716 [22:39<02:24,  4.32it/s]

 87%|████████▋ | 4093/4716 [22:39<02:23,  4.33it/s]

 87%|████████▋ | 4094/4716 [22:39<02:23,  4.33it/s]

 87%|████████▋ | 4095/4716 [22:40<02:23,  4.33it/s]

 87%|████████▋ | 4096/4716 [22:40<02:23,  4.33it/s]

 87%|████████▋ | 4097/4716 [22:40<02:23,  4.32it/s]

 87%|████████▋ | 4098/4716 [22:40<02:22,  4.33it/s]

 87%|████████▋ | 4099/4716 [22:40<02:22,  4.33it/s]

 87%|████████▋ | 4100/4716 [22:41<02:22,  4.32it/s]

 87%|████████▋ | 4101/4716 [22:41<02:22,  4.33it/s]

 87%|████████▋ | 4102/4716 [22:41<02:21,  4.33it/s]

 87%|████████▋ | 4103/4716 [22:41<02:21,  4.32it/s]

 87%|████████▋ | 4104/4716 [22:42<02:21,  4.33it/s]

 87%|████████▋ | 4105/4716 [22:42<02:21,  4.33it/s]

 87%|████████▋ | 4106/4716 [22:42<02:20,  4.34it/s]

 87%|████████▋ | 4107/4716 [22:42<02:20,  4.34it/s]

 87%|████████▋ | 4108/4716 [22:43<02:20,  4.33it/s]

 87%|████████▋ | 4109/4716 [22:43<02:20,  4.32it/s]

 87%|████████▋ | 4110/4716 [22:43<02:20,  4.33it/s]

 87%|████████▋ | 4111/4716 [22:43<02:19,  4.33it/s]

 87%|████████▋ | 4112/4716 [22:43<02:19,  4.33it/s]

 87%|████████▋ | 4113/4716 [22:44<02:19,  4.32it/s]

 87%|████████▋ | 4114/4716 [22:44<02:19,  4.33it/s]

 87%|████████▋ | 4115/4716 [22:44<02:18,  4.33it/s]

 87%|████████▋ | 4116/4716 [22:44<02:18,  4.32it/s]

 87%|████████▋ | 4117/4716 [22:45<02:18,  4.32it/s]

 87%|████████▋ | 4118/4716 [22:45<02:18,  4.32it/s]

 87%|████████▋ | 4119/4716 [22:45<02:18,  4.31it/s]

 87%|████████▋ | 4120/4716 [22:45<02:18,  4.32it/s]

 87%|████████▋ | 4121/4716 [22:46<02:17,  4.31it/s]

 87%|████████▋ | 4122/4716 [22:46<02:17,  4.31it/s]

 87%|████████▋ | 4123/4716 [22:46<02:17,  4.32it/s]

 87%|████████▋ | 4124/4716 [22:46<02:17,  4.32it/s]

 87%|████████▋ | 4125/4716 [22:46<02:16,  4.32it/s]

 87%|████████▋ | 4126/4716 [22:47<02:17,  4.30it/s]

 88%|████████▊ | 4127/4716 [22:47<02:16,  4.31it/s]

 88%|████████▊ | 4128/4716 [22:47<02:16,  4.31it/s]

 88%|████████▊ | 4129/4716 [22:47<02:15,  4.32it/s]

 88%|████████▊ | 4130/4716 [22:48<02:15,  4.32it/s]

 88%|████████▊ | 4131/4716 [22:48<02:15,  4.33it/s]

 88%|████████▊ | 4132/4716 [22:48<02:14,  4.33it/s]

 88%|████████▊ | 4133/4716 [22:48<02:14,  4.32it/s]

 88%|████████▊ | 4134/4716 [22:49<02:14,  4.33it/s]

 88%|████████▊ | 4135/4716 [22:49<02:14,  4.33it/s]

 88%|████████▊ | 4136/4716 [22:49<02:14,  4.31it/s]

 88%|████████▊ | 4137/4716 [22:49<02:13,  4.33it/s]

 88%|████████▊ | 4138/4716 [22:49<02:13,  4.33it/s]

 88%|████████▊ | 4139/4716 [22:50<02:13,  4.33it/s]

 88%|████████▊ | 4140/4716 [22:50<02:12,  4.33it/s]

 88%|████████▊ | 4141/4716 [22:50<02:12,  4.33it/s]

 88%|████████▊ | 4142/4716 [22:50<02:12,  4.33it/s]

 88%|████████▊ | 4143/4716 [22:51<02:12,  4.32it/s]

 88%|████████▊ | 4144/4716 [22:51<02:12,  4.32it/s]

 88%|████████▊ | 4145/4716 [22:51<02:12,  4.32it/s]

 88%|████████▊ | 4146/4716 [22:51<02:12,  4.31it/s]

 88%|████████▊ | 4147/4716 [22:52<02:11,  4.31it/s]

 88%|████████▊ | 4148/4716 [22:52<02:11,  4.31it/s]

 88%|████████▊ | 4149/4716 [22:52<02:11,  4.32it/s]

 88%|████████▊ | 4150/4716 [22:52<02:11,  4.31it/s]

 88%|████████▊ | 4151/4716 [22:52<02:10,  4.31it/s]

 88%|████████▊ | 4152/4716 [22:53<02:10,  4.31it/s]

 88%|████████▊ | 4153/4716 [22:53<02:10,  4.32it/s]

 88%|████████▊ | 4154/4716 [22:53<02:10,  4.32it/s]

 88%|████████▊ | 4155/4716 [22:53<02:10,  4.31it/s]

 88%|████████▊ | 4156/4716 [22:54<02:09,  4.31it/s]

 88%|████████▊ | 4157/4716 [22:54<02:09,  4.32it/s]

 88%|████████▊ | 4158/4716 [22:54<02:09,  4.32it/s]

 88%|████████▊ | 4159/4716 [22:54<02:09,  4.31it/s]

 88%|████████▊ | 4160/4716 [22:55<02:09,  4.30it/s]

 88%|████████▊ | 4161/4716 [22:55<02:08,  4.31it/s]

 88%|████████▊ | 4162/4716 [22:55<02:08,  4.31it/s]

 88%|████████▊ | 4163/4716 [22:55<02:08,  4.31it/s]

 88%|████████▊ | 4164/4716 [22:55<02:07,  4.32it/s]

 88%|████████▊ | 4165/4716 [22:56<02:07,  4.31it/s]

 88%|████████▊ | 4166/4716 [22:56<02:07,  4.31it/s]

 88%|████████▊ | 4167/4716 [22:56<02:07,  4.31it/s]

 88%|████████▊ | 4168/4716 [22:56<02:07,  4.30it/s]

 88%|████████▊ | 4169/4716 [22:57<02:06,  4.31it/s]

 88%|████████▊ | 4170/4716 [22:57<02:06,  4.31it/s]

 88%|████████▊ | 4171/4716 [22:57<02:08,  4.26it/s]

 88%|████████▊ | 4172/4716 [22:57<02:07,  4.26it/s]

 88%|████████▊ | 4173/4716 [22:58<02:07,  4.27it/s]

 89%|████████▊ | 4174/4716 [22:58<02:06,  4.29it/s]

 89%|████████▊ | 4175/4716 [22:58<02:05,  4.29it/s]

 89%|████████▊ | 4176/4716 [22:58<02:05,  4.30it/s]

 89%|████████▊ | 4177/4716 [22:59<02:05,  4.31it/s]

 89%|████████▊ | 4178/4716 [22:59<02:04,  4.31it/s]

 89%|████████▊ | 4179/4716 [22:59<02:04,  4.31it/s]

 89%|████████▊ | 4180/4716 [22:59<02:04,  4.31it/s]

 89%|████████▊ | 4181/4716 [22:59<02:04,  4.31it/s]

 89%|████████▊ | 4182/4716 [23:00<02:03,  4.31it/s]

 89%|████████▊ | 4183/4716 [23:00<02:03,  4.30it/s]

 89%|████████▊ | 4184/4716 [23:00<02:04,  4.28it/s]

 89%|████████▊ | 4185/4716 [23:00<02:03,  4.30it/s]

 89%|████████▉ | 4186/4716 [23:01<02:03,  4.31it/s]

 89%|████████▉ | 4187/4716 [23:01<02:02,  4.31it/s]

 89%|████████▉ | 4188/4716 [23:01<02:02,  4.31it/s]

 89%|████████▉ | 4189/4716 [23:01<02:02,  4.30it/s]

 89%|████████▉ | 4190/4716 [23:02<02:02,  4.31it/s]

 89%|████████▉ | 4191/4716 [23:02<02:02,  4.30it/s]

 89%|████████▉ | 4192/4716 [23:02<02:01,  4.31it/s]

 89%|████████▉ | 4193/4716 [23:02<02:01,  4.29it/s]

 89%|████████▉ | 4194/4716 [23:02<02:01,  4.29it/s]

 89%|████████▉ | 4195/4716 [23:03<02:01,  4.30it/s]

 89%|████████▉ | 4196/4716 [23:03<02:00,  4.30it/s]

 89%|████████▉ | 4197/4716 [23:03<02:00,  4.29it/s]

 89%|████████▉ | 4198/4716 [23:03<02:00,  4.31it/s]

 89%|████████▉ | 4199/4716 [23:04<02:00,  4.31it/s]

 89%|████████▉ | 4200/4716 [23:04<01:59,  4.31it/s]

 89%|████████▉ | 4201/4716 [23:04<01:59,  4.31it/s]

 89%|████████▉ | 4202/4716 [23:04<01:59,  4.30it/s]

 89%|████████▉ | 4203/4716 [23:05<01:59,  4.31it/s]

 89%|████████▉ | 4204/4716 [23:05<01:59,  4.30it/s]

 89%|████████▉ | 4205/4716 [23:05<01:58,  4.30it/s]

 89%|████████▉ | 4206/4716 [23:05<01:58,  4.31it/s]

 89%|████████▉ | 4207/4716 [23:05<01:57,  4.31it/s]

 89%|████████▉ | 4208/4716 [23:06<01:57,  4.31it/s]

 89%|████████▉ | 4209/4716 [23:06<01:57,  4.30it/s]

 89%|████████▉ | 4210/4716 [23:06<01:57,  4.30it/s]

 89%|████████▉ | 4211/4716 [23:06<01:57,  4.31it/s]

 89%|████████▉ | 4212/4716 [23:07<01:57,  4.30it/s]

 89%|████████▉ | 4213/4716 [23:07<01:56,  4.31it/s]

 89%|████████▉ | 4214/4716 [23:07<01:56,  4.32it/s]

 89%|████████▉ | 4215/4716 [23:07<01:56,  4.31it/s]

 89%|████████▉ | 4216/4716 [23:08<01:55,  4.31it/s]

 89%|████████▉ | 4217/4716 [23:08<01:55,  4.31it/s]

 89%|████████▉ | 4218/4716 [23:08<01:55,  4.31it/s]

 89%|████████▉ | 4219/4716 [23:08<01:55,  4.30it/s]

 89%|████████▉ | 4220/4716 [23:09<01:55,  4.31it/s]

 90%|████████▉ | 4221/4716 [23:09<01:54,  4.32it/s]

 90%|████████▉ | 4222/4716 [23:09<01:54,  4.31it/s]

 90%|████████▉ | 4223/4716 [23:09<01:54,  4.29it/s]

 90%|████████▉ | 4224/4716 [23:09<01:54,  4.29it/s]

 90%|████████▉ | 4225/4716 [23:10<01:54,  4.29it/s]

 90%|████████▉ | 4226/4716 [23:10<01:54,  4.30it/s]

 90%|████████▉ | 4227/4716 [23:10<01:53,  4.30it/s]

 90%|████████▉ | 4228/4716 [23:10<01:53,  4.29it/s]

 90%|████████▉ | 4229/4716 [23:11<01:53,  4.30it/s]

 90%|████████▉ | 4230/4716 [23:11<01:53,  4.29it/s]

 90%|████████▉ | 4231/4716 [23:11<01:52,  4.30it/s]

 90%|████████▉ | 4232/4716 [23:11<01:52,  4.29it/s]

 90%|████████▉ | 4233/4716 [23:12<01:52,  4.28it/s]

 90%|████████▉ | 4234/4716 [23:12<01:52,  4.29it/s]

 90%|████████▉ | 4235/4716 [23:12<01:51,  4.30it/s]

 90%|████████▉ | 4236/4716 [23:12<01:51,  4.30it/s]

 90%|████████▉ | 4237/4716 [23:12<01:51,  4.28it/s]

 90%|████████▉ | 4238/4716 [23:13<01:51,  4.28it/s]

 90%|████████▉ | 4239/4716 [23:13<01:51,  4.29it/s]

 90%|████████▉ | 4240/4716 [23:13<01:51,  4.29it/s]

 90%|████████▉ | 4241/4716 [23:13<01:50,  4.30it/s]

 90%|████████▉ | 4242/4716 [23:14<01:50,  4.29it/s]

 90%|████████▉ | 4243/4716 [23:14<01:50,  4.29it/s]

 90%|████████▉ | 4244/4716 [23:14<01:49,  4.29it/s]

 90%|█████████ | 4245/4716 [23:14<01:49,  4.30it/s]

 90%|█████████ | 4246/4716 [23:15<01:49,  4.30it/s]

 90%|█████████ | 4247/4716 [23:15<01:49,  4.30it/s]

 90%|█████████ | 4248/4716 [23:15<01:49,  4.29it/s]

 90%|█████████ | 4249/4716 [23:15<01:48,  4.29it/s]

 90%|█████████ | 4250/4716 [23:15<01:48,  4.29it/s]

 90%|█████████ | 4251/4716 [23:16<01:48,  4.29it/s]

 90%|█████████ | 4252/4716 [23:16<01:47,  4.30it/s]

 90%|█████████ | 4253/4716 [23:16<01:47,  4.30it/s]

 90%|█████████ | 4254/4716 [23:16<01:47,  4.30it/s]

 90%|█████████ | 4255/4716 [23:17<01:47,  4.29it/s]

 90%|█████████ | 4256/4716 [23:17<01:47,  4.29it/s]

 90%|█████████ | 4257/4716 [23:17<01:46,  4.29it/s]

 90%|█████████ | 4258/4716 [23:17<01:46,  4.28it/s]

 90%|█████████ | 4259/4716 [23:18<01:47,  4.26it/s]

 90%|█████████ | 4260/4716 [23:18<01:46,  4.28it/s]

 90%|█████████ | 4261/4716 [23:18<01:46,  4.28it/s]

 90%|█████████ | 4262/4716 [23:18<01:45,  4.29it/s]

 90%|█████████ | 4263/4716 [23:19<01:45,  4.30it/s]

 90%|█████████ | 4264/4716 [23:19<01:45,  4.29it/s]

 90%|█████████ | 4265/4716 [23:19<01:45,  4.29it/s]

 90%|█████████ | 4266/4716 [23:19<01:45,  4.28it/s]

 90%|█████████ | 4267/4716 [23:19<01:44,  4.28it/s]

 91%|█████████ | 4268/4716 [23:20<01:44,  4.28it/s]

 91%|█████████ | 4269/4716 [23:20<01:44,  4.28it/s]

 91%|█████████ | 4270/4716 [23:20<01:43,  4.30it/s]

 91%|█████████ | 4271/4716 [23:20<01:43,  4.30it/s]

 91%|█████████ | 4272/4716 [23:21<01:43,  4.30it/s]

 91%|█████████ | 4273/4716 [23:21<01:43,  4.29it/s]

 91%|█████████ | 4274/4716 [23:21<01:43,  4.27it/s]

 91%|█████████ | 4275/4716 [23:21<01:42,  4.29it/s]

 91%|█████████ | 4276/4716 [23:22<01:42,  4.28it/s]

 91%|█████████ | 4277/4716 [23:22<01:43,  4.26it/s]

 91%|█████████ | 4278/4716 [23:22<01:43,  4.25it/s]

 91%|█████████ | 4279/4716 [23:22<01:42,  4.26it/s]

 91%|█████████ | 4280/4716 [23:22<01:42,  4.27it/s]

 91%|█████████ | 4281/4716 [23:23<01:42,  4.26it/s]

 91%|█████████ | 4282/4716 [23:23<01:41,  4.26it/s]

 91%|█████████ | 4283/4716 [23:23<01:41,  4.27it/s]

 91%|█████████ | 4284/4716 [23:23<01:41,  4.27it/s]

 91%|█████████ | 4285/4716 [23:24<01:40,  4.27it/s]

 91%|█████████ | 4286/4716 [23:24<01:40,  4.27it/s]

 91%|█████████ | 4287/4716 [23:24<01:40,  4.28it/s]

 91%|█████████ | 4288/4716 [23:24<01:40,  4.27it/s]

 91%|█████████ | 4289/4716 [23:25<01:39,  4.27it/s]

 91%|█████████ | 4290/4716 [23:25<01:39,  4.27it/s]

 91%|█████████ | 4291/4716 [23:25<01:39,  4.27it/s]

 91%|█████████ | 4292/4716 [23:25<01:39,  4.26it/s]

 91%|█████████ | 4293/4716 [23:26<01:39,  4.27it/s]

 91%|█████████ | 4294/4716 [23:26<01:38,  4.27it/s]

 91%|█████████ | 4295/4716 [23:26<01:38,  4.27it/s]

 91%|█████████ | 4296/4716 [23:26<01:38,  4.28it/s]

 91%|█████████ | 4297/4716 [23:26<01:38,  4.26it/s]

 91%|█████████ | 4298/4716 [23:27<01:37,  4.27it/s]

 91%|█████████ | 4299/4716 [23:27<01:37,  4.26it/s]

 91%|█████████ | 4300/4716 [23:27<01:37,  4.27it/s]

 91%|█████████ | 4301/4716 [23:27<01:37,  4.27it/s]

 91%|█████████ | 4302/4716 [23:28<01:37,  4.26it/s]

 91%|█████████ | 4303/4716 [23:28<01:36,  4.27it/s]

 91%|█████████▏| 4304/4716 [23:28<01:36,  4.26it/s]

 91%|█████████▏| 4305/4716 [23:28<01:36,  4.26it/s]

 91%|█████████▏| 4306/4716 [23:29<01:36,  4.26it/s]

 91%|█████████▏| 4307/4716 [23:29<01:35,  4.27it/s]

 91%|█████████▏| 4308/4716 [23:29<01:35,  4.28it/s]

 91%|█████████▏| 4309/4716 [23:29<01:35,  4.26it/s]

 91%|█████████▏| 4310/4716 [23:30<01:35,  4.26it/s]

 91%|█████████▏| 4311/4716 [23:30<01:35,  4.26it/s]

 91%|█████████▏| 4312/4716 [23:30<01:35,  4.25it/s]

 91%|█████████▏| 4313/4716 [23:30<01:34,  4.26it/s]

 91%|█████████▏| 4314/4716 [23:30<01:34,  4.27it/s]

 91%|█████████▏| 4315/4716 [23:31<01:34,  4.26it/s]

 92%|█████████▏| 4316/4716 [23:31<01:34,  4.26it/s]

 92%|█████████▏| 4317/4716 [23:31<01:33,  4.25it/s]

 92%|█████████▏| 4318/4716 [23:31<01:33,  4.27it/s]

 92%|█████████▏| 4319/4716 [23:32<01:33,  4.26it/s]

 92%|█████████▏| 4320/4716 [23:32<01:33,  4.26it/s]

 92%|█████████▏| 4321/4716 [23:32<01:32,  4.26it/s]

 92%|█████████▏| 4322/4716 [23:32<01:32,  4.26it/s]

 92%|█████████▏| 4323/4716 [23:33<01:32,  4.26it/s]

 92%|█████████▏| 4324/4716 [23:33<01:31,  4.26it/s]

 92%|█████████▏| 4325/4716 [23:33<01:31,  4.26it/s]

 92%|█████████▏| 4326/4716 [23:33<01:31,  4.27it/s]

 92%|█████████▏| 4327/4716 [23:34<01:31,  4.26it/s]

 92%|█████████▏| 4328/4716 [23:34<01:30,  4.27it/s]

 92%|█████████▏| 4329/4716 [23:34<01:30,  4.27it/s]

 92%|█████████▏| 4330/4716 [23:34<01:30,  4.26it/s]

 92%|█████████▏| 4331/4716 [23:34<01:30,  4.26it/s]

 92%|█████████▏| 4332/4716 [23:35<01:29,  4.27it/s]

 92%|█████████▏| 4333/4716 [23:35<01:29,  4.28it/s]

 92%|█████████▏| 4334/4716 [23:35<01:29,  4.27it/s]

 92%|█████████▏| 4335/4716 [23:35<01:29,  4.27it/s]

 92%|█████████▏| 4336/4716 [23:36<01:29,  4.27it/s]

 92%|█████████▏| 4337/4716 [23:36<01:29,  4.25it/s]

 92%|█████████▏| 4338/4716 [23:36<01:28,  4.26it/s]

 92%|█████████▏| 4339/4716 [23:36<01:28,  4.26it/s]

 92%|█████████▏| 4340/4716 [23:37<01:28,  4.26it/s]

 92%|█████████▏| 4341/4716 [23:37<01:27,  4.26it/s]

 92%|█████████▏| 4342/4716 [23:37<01:27,  4.26it/s]

 92%|█████████▏| 4343/4716 [23:37<01:27,  4.27it/s]

 92%|█████████▏| 4344/4716 [23:38<01:27,  4.25it/s]

 92%|█████████▏| 4345/4716 [23:38<01:27,  4.25it/s]

 92%|█████████▏| 4346/4716 [23:38<01:26,  4.26it/s]

 92%|█████████▏| 4347/4716 [23:38<01:26,  4.26it/s]

 92%|█████████▏| 4348/4716 [23:38<01:26,  4.26it/s]

 92%|█████████▏| 4349/4716 [23:39<01:26,  4.26it/s]

 92%|█████████▏| 4350/4716 [23:39<01:25,  4.26it/s]

 92%|█████████▏| 4351/4716 [23:39<01:25,  4.26it/s]

 92%|█████████▏| 4352/4716 [23:39<01:25,  4.24it/s]

 92%|█████████▏| 4353/4716 [23:40<01:25,  4.26it/s]

 92%|█████████▏| 4354/4716 [23:40<01:25,  4.25it/s]

 92%|█████████▏| 4355/4716 [23:40<01:24,  4.25it/s]

 92%|█████████▏| 4356/4716 [23:40<01:24,  4.26it/s]

 92%|█████████▏| 4357/4716 [23:41<01:24,  4.26it/s]

 92%|█████████▏| 4358/4716 [23:41<01:23,  4.26it/s]

 92%|█████████▏| 4359/4716 [23:41<01:23,  4.26it/s]

 92%|█████████▏| 4360/4716 [23:41<01:23,  4.27it/s]

 92%|█████████▏| 4361/4716 [23:41<01:23,  4.26it/s]

 92%|█████████▏| 4362/4716 [23:42<01:23,  4.26it/s]

 93%|█████████▎| 4363/4716 [23:42<01:22,  4.26it/s]

 93%|█████████▎| 4364/4716 [23:42<01:22,  4.26it/s]

 93%|█████████▎| 4365/4716 [23:42<01:22,  4.26it/s]

 93%|█████████▎| 4366/4716 [23:43<01:22,  4.26it/s]

 93%|█████████▎| 4367/4716 [23:43<01:22,  4.25it/s]

 93%|█████████▎| 4368/4716 [23:43<01:21,  4.25it/s]

 93%|█████████▎| 4369/4716 [23:43<01:21,  4.24it/s]

 93%|█████████▎| 4370/4716 [23:44<01:21,  4.25it/s]

 93%|█████████▎| 4371/4716 [23:44<01:21,  4.25it/s]

 93%|█████████▎| 4372/4716 [23:44<01:21,  4.24it/s]

 93%|█████████▎| 4373/4716 [23:44<01:20,  4.25it/s]

 93%|█████████▎| 4374/4716 [23:45<01:20,  4.25it/s]

 93%|█████████▎| 4375/4716 [23:45<01:20,  4.25it/s]

 93%|█████████▎| 4376/4716 [23:45<01:19,  4.25it/s]

 93%|█████████▎| 4377/4716 [23:45<01:19,  4.25it/s]

 93%|█████████▎| 4378/4716 [23:45<01:19,  4.25it/s]

 93%|█████████▎| 4379/4716 [23:46<01:19,  4.25it/s]

 93%|█████████▎| 4380/4716 [23:46<01:19,  4.25it/s]

 93%|█████████▎| 4381/4716 [23:46<01:18,  4.25it/s]

logging
logging the anndata

 93%|█████████▎| 4382/4716 [23:47<03:02,  1.83it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 93%|█████████▎| 4383/4716 [23:48<02:30,  2.22it/s]

 93%|█████████▎| 4384/4716 [23:48<02:07,  2.60it/s]

 93%|█████████▎| 4385/4716 [23:48<01:51,  2.96it/s]

 93%|█████████▎| 4386/4716 [23:48<01:40,  3.28it/s]

 93%|█████████▎| 4387/4716 [23:49<01:32,  3.55it/s]

 93%|█████████▎| 4388/4716 [23:49<01:27,  3.76it/s]

 93%|█████████▎| 4389/4716 [23:49<01:23,  3.93it/s]

 93%|█████████▎| 4390/4716 [23:49<01:20,  4.05it/s]

 93%|█████████▎| 4391/4716 [23:50<01:18,  4.16it/s]

 93%|█████████▎| 4392/4716 [23:50<01:16,  4.22it/s]

 93%|█████████▎| 4393/4716 [23:50<01:15,  4.27it/s]

 93%|█████████▎| 4394/4716 [23:50<01:14,  4.30it/s]

 93%|█████████▎| 4395/4716 [23:50<01:14,  4.33it/s]

 93%|█████████▎| 4396/4716 [23:51<01:13,  4.33it/s]

 93%|█████████▎| 4397/4716 [23:51<01:13,  4.34it/s]

 93%|█████████▎| 4398/4716 [23:51<01:13,  4.34it/s]

 93%|█████████▎| 4399/4716 [23:51<01:12,  4.35it/s]

 93%|█████████▎| 4400/4716 [23:52<01:12,  4.36it/s]

 93%|█████████▎| 4401/4716 [23:52<01:12,  4.35it/s]

 93%|█████████▎| 4402/4716 [23:52<01:12,  4.36it/s]

 93%|█████████▎| 4403/4716 [23:52<01:11,  4.37it/s]

 93%|█████████▎| 4404/4716 [23:53<01:11,  4.37it/s]

 93%|█████████▎| 4405/4716 [23:53<01:11,  4.38it/s]

 93%|█████████▎| 4406/4716 [23:53<01:10,  4.38it/s]

 93%|█████████▎| 4407/4716 [23:53<01:10,  4.37it/s]

 93%|█████████▎| 4408/4716 [23:53<01:10,  4.37it/s]

 93%|█████████▎| 4409/4716 [23:54<01:10,  4.36it/s]

 94%|█████████▎| 4410/4716 [23:54<01:10,  4.36it/s]

 94%|█████████▎| 4411/4716 [23:54<01:09,  4.37it/s]

 94%|█████████▎| 4412/4716 [23:54<01:09,  4.37it/s]

 94%|█████████▎| 4413/4716 [23:55<01:09,  4.37it/s]

 94%|█████████▎| 4414/4716 [23:55<01:08,  4.38it/s]

 94%|█████████▎| 4415/4716 [23:55<01:08,  4.37it/s]

 94%|█████████▎| 4416/4716 [23:55<01:08,  4.37it/s]

 94%|█████████▎| 4417/4716 [23:55<01:08,  4.38it/s]

 94%|█████████▎| 4418/4716 [23:56<01:08,  4.38it/s]

 94%|█████████▎| 4419/4716 [23:56<01:07,  4.38it/s]

 94%|█████████▎| 4420/4716 [23:56<01:07,  4.38it/s]

 94%|█████████▎| 4421/4716 [23:56<01:07,  4.37it/s]

 94%|█████████▍| 4422/4716 [23:57<01:07,  4.37it/s]

 94%|█████████▍| 4423/4716 [23:57<01:06,  4.38it/s]

 94%|█████████▍| 4424/4716 [23:57<01:06,  4.37it/s]

 94%|█████████▍| 4425/4716 [23:57<01:06,  4.37it/s]

 94%|█████████▍| 4426/4716 [23:58<01:06,  4.37it/s]

 94%|█████████▍| 4427/4716 [23:58<01:06,  4.38it/s]

 94%|█████████▍| 4428/4716 [23:58<01:05,  4.37it/s]

 94%|█████████▍| 4429/4716 [23:58<01:05,  4.38it/s]

 94%|█████████▍| 4430/4716 [23:58<01:05,  4.36it/s]

 94%|█████████▍| 4431/4716 [23:59<01:05,  4.36it/s]

 94%|█████████▍| 4432/4716 [23:59<01:05,  4.36it/s]

 94%|█████████▍| 4433/4716 [23:59<01:04,  4.36it/s]

 94%|█████████▍| 4434/4716 [23:59<01:04,  4.37it/s]

 94%|█████████▍| 4435/4716 [24:00<01:04,  4.37it/s]

 94%|█████████▍| 4436/4716 [24:00<01:04,  4.37it/s]

 94%|█████████▍| 4437/4716 [24:00<01:03,  4.37it/s]

 94%|█████████▍| 4438/4716 [24:00<01:03,  4.37it/s]

 94%|█████████▍| 4439/4716 [24:01<01:03,  4.36it/s]

 94%|█████████▍| 4440/4716 [24:01<01:03,  4.37it/s]

 94%|█████████▍| 4441/4716 [24:01<01:02,  4.37it/s]

 94%|█████████▍| 4442/4716 [24:01<01:02,  4.37it/s]

 94%|█████████▍| 4443/4716 [24:01<01:02,  4.37it/s]

 94%|█████████▍| 4444/4716 [24:02<01:02,  4.37it/s]

 94%|█████████▍| 4445/4716 [24:02<01:01,  4.37it/s]

 94%|█████████▍| 4446/4716 [24:02<01:01,  4.37it/s]

 94%|█████████▍| 4447/4716 [24:02<01:01,  4.37it/s]

 94%|█████████▍| 4448/4716 [24:03<01:01,  4.38it/s]

 94%|█████████▍| 4449/4716 [24:03<01:01,  4.37it/s]

 94%|█████████▍| 4450/4716 [24:03<01:01,  4.36it/s]

 94%|█████████▍| 4451/4716 [24:03<01:00,  4.36it/s]

 94%|█████████▍| 4452/4716 [24:03<01:00,  4.37it/s]

 94%|█████████▍| 4453/4716 [24:04<01:00,  4.34it/s]

 94%|█████████▍| 4454/4716 [24:04<01:00,  4.35it/s]

 94%|█████████▍| 4455/4716 [24:04<01:00,  4.35it/s]

 94%|█████████▍| 4456/4716 [24:04<00:59,  4.36it/s]

 95%|█████████▍| 4457/4716 [24:05<00:59,  4.37it/s]

 95%|█████████▍| 4458/4716 [24:05<00:59,  4.37it/s]

 95%|█████████▍| 4459/4716 [24:05<00:58,  4.37it/s]

 95%|█████████▍| 4460/4716 [24:05<00:58,  4.36it/s]

 95%|█████████▍| 4461/4716 [24:06<00:58,  4.36it/s]

 95%|█████████▍| 4462/4716 [24:06<00:58,  4.35it/s]

 95%|█████████▍| 4463/4716 [24:06<00:58,  4.36it/s]

 95%|█████████▍| 4464/4716 [24:06<00:57,  4.36it/s]

 95%|█████████▍| 4465/4716 [24:06<00:57,  4.37it/s]

 95%|█████████▍| 4466/4716 [24:07<00:57,  4.36it/s]

 95%|█████████▍| 4467/4716 [24:07<00:57,  4.36it/s]

 95%|█████████▍| 4468/4716 [24:07<00:56,  4.36it/s]

 95%|█████████▍| 4469/4716 [24:07<00:56,  4.36it/s]

 95%|█████████▍| 4470/4716 [24:08<00:56,  4.37it/s]

 95%|█████████▍| 4471/4716 [24:08<00:56,  4.37it/s]

 95%|█████████▍| 4472/4716 [24:08<00:55,  4.36it/s]

 95%|█████████▍| 4473/4716 [24:08<00:55,  4.35it/s]

 95%|█████████▍| 4474/4716 [24:09<00:55,  4.35it/s]

 95%|█████████▍| 4475/4716 [24:09<00:55,  4.36it/s]

 95%|█████████▍| 4476/4716 [24:09<00:55,  4.35it/s]

 95%|█████████▍| 4477/4716 [24:09<00:54,  4.36it/s]

 95%|█████████▍| 4478/4716 [24:09<00:54,  4.36it/s]

 95%|█████████▍| 4479/4716 [24:10<00:54,  4.35it/s]

 95%|█████████▍| 4480/4716 [24:10<00:54,  4.35it/s]

 95%|█████████▌| 4481/4716 [24:10<00:54,  4.35it/s]

 95%|█████████▌| 4482/4716 [24:10<00:53,  4.35it/s]

 95%|█████████▌| 4483/4716 [24:11<00:53,  4.36it/s]

 95%|█████████▌| 4484/4716 [24:11<00:53,  4.36it/s]

 95%|█████████▌| 4485/4716 [24:11<00:53,  4.36it/s]

 95%|█████████▌| 4486/4716 [24:11<00:52,  4.36it/s]

 95%|█████████▌| 4487/4716 [24:12<00:52,  4.37it/s]

 95%|█████████▌| 4488/4716 [24:12<00:52,  4.36it/s]

 95%|█████████▌| 4489/4716 [24:12<00:52,  4.36it/s]

 95%|█████████▌| 4490/4716 [24:12<00:51,  4.36it/s]

 95%|█████████▌| 4491/4716 [24:12<00:51,  4.35it/s]

 95%|█████████▌| 4492/4716 [24:13<00:51,  4.35it/s]

 95%|█████████▌| 4493/4716 [24:13<00:51,  4.34it/s]

 95%|█████████▌| 4494/4716 [24:13<00:50,  4.36it/s]

 95%|█████████▌| 4495/4716 [24:13<00:50,  4.35it/s]

 95%|█████████▌| 4496/4716 [24:14<00:50,  4.36it/s]

 95%|█████████▌| 4497/4716 [24:14<00:50,  4.37it/s]

 95%|█████████▌| 4498/4716 [24:14<00:50,  4.36it/s]

 95%|█████████▌| 4499/4716 [24:14<00:49,  4.36it/s]

 95%|█████████▌| 4500/4716 [24:15<00:49,  4.35it/s]

 95%|█████████▌| 4501/4716 [24:15<00:49,  4.34it/s]

 95%|█████████▌| 4502/4716 [24:15<00:49,  4.35it/s]

 95%|█████████▌| 4503/4716 [24:15<00:48,  4.36it/s]

 96%|█████████▌| 4504/4716 [24:15<00:48,  4.36it/s]

 96%|█████████▌| 4505/4716 [24:16<00:48,  4.36it/s]

 96%|█████████▌| 4506/4716 [24:16<00:48,  4.35it/s]

 96%|█████████▌| 4507/4716 [24:16<00:48,  4.35it/s]

 96%|█████████▌| 4508/4716 [24:16<00:47,  4.35it/s]

 96%|█████████▌| 4509/4716 [24:17<00:47,  4.35it/s]

 96%|█████████▌| 4510/4716 [24:17<00:47,  4.36it/s]

 96%|█████████▌| 4511/4716 [24:17<00:47,  4.35it/s]

 96%|█████████▌| 4512/4716 [24:17<00:46,  4.35it/s]

 96%|█████████▌| 4513/4716 [24:17<00:46,  4.36it/s]

 96%|█████████▌| 4514/4716 [24:18<00:46,  4.35it/s]

 96%|█████████▌| 4515/4716 [24:18<00:46,  4.35it/s]

 96%|█████████▌| 4516/4716 [24:18<00:45,  4.35it/s]

 96%|█████████▌| 4517/4716 [24:18<00:45,  4.35it/s]

 96%|█████████▌| 4518/4716 [24:19<00:45,  4.34it/s]

 96%|█████████▌| 4519/4716 [24:19<00:45,  4.35it/s]

 96%|█████████▌| 4520/4716 [24:19<00:45,  4.35it/s]

 96%|█████████▌| 4521/4716 [24:19<00:44,  4.35it/s]

 96%|█████████▌| 4522/4716 [24:20<00:44,  4.34it/s]

 96%|█████████▌| 4523/4716 [24:20<00:44,  4.34it/s]

 96%|█████████▌| 4524/4716 [24:20<00:44,  4.35it/s]

 96%|█████████▌| 4525/4716 [24:20<00:43,  4.36it/s]

 96%|█████████▌| 4526/4716 [24:20<00:43,  4.35it/s]

 96%|█████████▌| 4527/4716 [24:21<00:43,  4.35it/s]

 96%|█████████▌| 4528/4716 [24:21<00:43,  4.35it/s]

 96%|█████████▌| 4529/4716 [24:21<00:42,  4.35it/s]

 96%|█████████▌| 4530/4716 [24:21<00:42,  4.34it/s]

 96%|█████████▌| 4531/4716 [24:22<00:42,  4.33it/s]

 96%|█████████▌| 4532/4716 [24:22<00:42,  4.34it/s]

 96%|█████████▌| 4533/4716 [24:22<00:42,  4.34it/s]

 96%|█████████▌| 4534/4716 [24:22<00:41,  4.34it/s]

 96%|█████████▌| 4535/4716 [24:23<00:41,  4.35it/s]

 96%|█████████▌| 4536/4716 [24:23<00:41,  4.35it/s]

 96%|█████████▌| 4537/4716 [24:23<00:41,  4.35it/s]

 96%|█████████▌| 4538/4716 [24:23<00:40,  4.35it/s]

 96%|█████████▌| 4539/4716 [24:23<00:40,  4.35it/s]

 96%|█████████▋| 4540/4716 [24:24<00:40,  4.35it/s]

 96%|█████████▋| 4541/4716 [24:24<00:40,  4.36it/s]

 96%|█████████▋| 4542/4716 [24:24<00:39,  4.36it/s]

 96%|█████████▋| 4543/4716 [24:24<00:39,  4.36it/s]

 96%|█████████▋| 4544/4716 [24:25<00:39,  4.35it/s]

 96%|█████████▋| 4545/4716 [24:25<00:39,  4.34it/s]

 96%|█████████▋| 4546/4716 [24:25<00:39,  4.35it/s]

 96%|█████████▋| 4547/4716 [24:25<00:38,  4.34it/s]

 96%|█████████▋| 4548/4716 [24:26<00:38,  4.35it/s]

 96%|█████████▋| 4549/4716 [24:26<00:38,  4.35it/s]

 96%|█████████▋| 4550/4716 [24:26<00:38,  4.34it/s]

 97%|█████████▋| 4551/4716 [24:26<00:37,  4.35it/s]

 97%|█████████▋| 4552/4716 [24:26<00:37,  4.36it/s]

 97%|█████████▋| 4553/4716 [24:27<00:37,  4.34it/s]

 97%|█████████▋| 4554/4716 [24:27<00:37,  4.34it/s]

 97%|█████████▋| 4555/4716 [24:27<00:37,  4.33it/s]

 97%|█████████▋| 4556/4716 [24:27<00:36,  4.34it/s]

 97%|█████████▋| 4557/4716 [24:28<00:36,  4.34it/s]

 97%|█████████▋| 4558/4716 [24:28<00:36,  4.33it/s]

 97%|█████████▋| 4559/4716 [24:28<00:36,  4.35it/s]

 97%|█████████▋| 4560/4716 [24:28<00:35,  4.34it/s]

 97%|█████████▋| 4561/4716 [24:29<00:35,  4.34it/s]

 97%|█████████▋| 4562/4716 [24:29<00:35,  4.35it/s]

 97%|█████████▋| 4563/4716 [24:29<00:35,  4.35it/s]

 97%|█████████▋| 4564/4716 [24:29<00:34,  4.34it/s]

 97%|█████████▋| 4565/4716 [24:29<00:34,  4.34it/s]

 97%|█████████▋| 4566/4716 [24:30<00:34,  4.33it/s]

 97%|█████████▋| 4567/4716 [24:30<00:34,  4.34it/s]

 97%|█████████▋| 4568/4716 [24:30<00:34,  4.33it/s]

 97%|█████████▋| 4569/4716 [24:30<00:33,  4.33it/s]

 97%|█████████▋| 4570/4716 [24:31<00:33,  4.34it/s]

 97%|█████████▋| 4571/4716 [24:31<00:33,  4.33it/s]

 97%|█████████▋| 4572/4716 [24:31<00:33,  4.32it/s]

 97%|█████████▋| 4573/4716 [24:31<00:33,  4.33it/s]

 97%|█████████▋| 4574/4716 [24:32<00:32,  4.33it/s]

 97%|█████████▋| 4575/4716 [24:32<00:32,  4.34it/s]

 97%|█████████▋| 4576/4716 [24:32<00:32,  4.33it/s]

 97%|█████████▋| 4577/4716 [24:32<00:32,  4.33it/s]

 97%|█████████▋| 4578/4716 [24:32<00:32,  4.28it/s]

 97%|█████████▋| 4579/4716 [24:33<00:31,  4.30it/s]

 97%|█████████▋| 4580/4716 [24:33<00:31,  4.31it/s]

 97%|█████████▋| 4581/4716 [24:33<00:31,  4.33it/s]

 97%|█████████▋| 4582/4716 [24:33<00:30,  4.33it/s]

 97%|█████████▋| 4583/4716 [24:34<00:30,  4.33it/s]

 97%|█████████▋| 4584/4716 [24:34<00:30,  4.32it/s]

 97%|█████████▋| 4585/4716 [24:34<00:30,  4.33it/s]

 97%|█████████▋| 4586/4716 [24:34<00:30,  4.32it/s]

 97%|█████████▋| 4587/4716 [24:35<00:29,  4.32it/s]

 97%|█████████▋| 4588/4716 [24:35<00:29,  4.33it/s]

 97%|█████████▋| 4589/4716 [24:35<00:29,  4.33it/s]

 97%|█████████▋| 4590/4716 [24:35<00:29,  4.33it/s]

 97%|█████████▋| 4591/4716 [24:35<00:28,  4.34it/s]

 97%|█████████▋| 4592/4716 [24:36<00:28,  4.34it/s]

 97%|█████████▋| 4593/4716 [24:36<00:28,  4.35it/s]

 97%|█████████▋| 4594/4716 [24:36<00:28,  4.34it/s]

 97%|█████████▋| 4595/4716 [24:36<00:27,  4.34it/s]

 97%|█████████▋| 4596/4716 [24:37<00:27,  4.34it/s]

 97%|█████████▋| 4597/4716 [24:37<00:27,  4.33it/s]

 97%|█████████▋| 4598/4716 [24:37<00:27,  4.33it/s]

 98%|█████████▊| 4599/4716 [24:37<00:26,  4.34it/s]

 98%|█████████▊| 4600/4716 [24:38<00:26,  4.34it/s]

 98%|█████████▊| 4601/4716 [24:38<00:26,  4.34it/s]

 98%|█████████▊| 4602/4716 [24:38<00:26,  4.34it/s]

 98%|█████████▊| 4603/4716 [24:38<00:26,  4.34it/s]

 98%|█████████▊| 4604/4716 [24:38<00:25,  4.34it/s]

 98%|█████████▊| 4605/4716 [24:39<00:25,  4.34it/s]

 98%|█████████▊| 4606/4716 [24:39<00:25,  4.33it/s]

 98%|█████████▊| 4607/4716 [24:39<00:25,  4.34it/s]

 98%|█████████▊| 4608/4716 [24:39<00:24,  4.33it/s]

 98%|█████████▊| 4609/4716 [24:40<00:24,  4.32it/s]

 98%|█████████▊| 4610/4716 [24:40<00:24,  4.33it/s]

 98%|█████████▊| 4611/4716 [24:40<00:24,  4.34it/s]

 98%|█████████▊| 4612/4716 [24:40<00:24,  4.33it/s]

 98%|█████████▊| 4613/4716 [24:41<00:23,  4.33it/s]

 98%|█████████▊| 4614/4716 [24:41<00:23,  4.33it/s]

 98%|█████████▊| 4615/4716 [24:41<00:23,  4.34it/s]

 98%|█████████▊| 4616/4716 [24:41<00:23,  4.33it/s]

 98%|█████████▊| 4617/4716 [24:41<00:22,  4.32it/s]

 98%|█████████▊| 4618/4716 [24:42<00:22,  4.33it/s]

 98%|█████████▊| 4619/4716 [24:42<00:22,  4.33it/s]

 98%|█████████▊| 4620/4716 [24:42<00:22,  4.33it/s]

 98%|█████████▊| 4621/4716 [24:42<00:21,  4.34it/s]

 98%|█████████▊| 4622/4716 [24:43<00:21,  4.33it/s]

 98%|█████████▊| 4623/4716 [24:43<00:21,  4.34it/s]

 98%|█████████▊| 4624/4716 [24:43<00:21,  4.33it/s]

 98%|█████████▊| 4625/4716 [24:43<00:21,  4.33it/s]

 98%|█████████▊| 4626/4716 [24:44<00:20,  4.33it/s]

 98%|█████████▊| 4627/4716 [24:44<00:20,  4.32it/s]

 98%|█████████▊| 4628/4716 [24:44<00:20,  4.32it/s]

 98%|█████████▊| 4629/4716 [24:44<00:20,  4.33it/s]

 98%|█████████▊| 4630/4716 [24:44<00:19,  4.32it/s]

 98%|█████████▊| 4631/4716 [24:45<00:19,  4.33it/s]

 98%|█████████▊| 4632/4716 [24:45<00:19,  4.33it/s]

 98%|█████████▊| 4633/4716 [24:45<00:19,  4.32it/s]

 98%|█████████▊| 4634/4716 [24:45<00:18,  4.32it/s]

 98%|█████████▊| 4635/4716 [24:46<00:18,  4.32it/s]

 98%|█████████▊| 4636/4716 [24:46<00:18,  4.33it/s]

 98%|█████████▊| 4637/4716 [24:46<00:18,  4.33it/s]

 98%|█████████▊| 4638/4716 [24:46<00:18,  4.32it/s]

 98%|█████████▊| 4639/4716 [24:47<00:17,  4.33it/s]

 98%|█████████▊| 4640/4716 [24:47<00:17,  4.33it/s]

 98%|█████████▊| 4641/4716 [24:47<00:17,  4.33it/s]

 98%|█████████▊| 4642/4716 [24:47<00:17,  4.33it/s]

 98%|█████████▊| 4643/4716 [24:47<00:16,  4.33it/s]

 98%|█████████▊| 4644/4716 [24:48<00:16,  4.34it/s]

 98%|█████████▊| 4645/4716 [24:48<00:16,  4.35it/s]

 99%|█████████▊| 4646/4716 [24:48<00:16,  4.33it/s]

 99%|█████████▊| 4647/4716 [24:48<00:15,  4.34it/s]

 99%|█████████▊| 4648/4716 [24:49<00:15,  4.33it/s]

 99%|█████████▊| 4649/4716 [24:49<00:15,  4.33it/s]

 99%|█████████▊| 4650/4716 [24:49<00:15,  4.33it/s]

 99%|█████████▊| 4651/4716 [24:49<00:15,  4.33it/s]

 99%|█████████▊| 4652/4716 [24:50<00:14,  4.33it/s]

 99%|█████████▊| 4653/4716 [24:50<00:14,  4.33it/s]

 99%|█████████▊| 4654/4716 [24:50<00:14,  4.32it/s]

 99%|█████████▊| 4655/4716 [24:50<00:14,  4.32it/s]

 99%|█████████▊| 4656/4716 [24:50<00:13,  4.32it/s]

 99%|█████████▊| 4657/4716 [24:51<00:13,  4.32it/s]

 99%|█████████▉| 4658/4716 [24:51<00:13,  4.32it/s]

 99%|█████████▉| 4659/4716 [24:51<00:13,  4.31it/s]

 99%|█████████▉| 4660/4716 [24:51<00:12,  4.32it/s]

 99%|█████████▉| 4661/4716 [24:52<00:12,  4.32it/s]

 99%|█████████▉| 4662/4716 [24:52<00:12,  4.33it/s]

 99%|█████████▉| 4663/4716 [24:52<00:12,  4.32it/s]

 99%|█████████▉| 4664/4716 [24:52<00:12,  4.32it/s]

 99%|█████████▉| 4665/4716 [24:53<00:11,  4.33it/s]

 99%|█████████▉| 4666/4716 [24:53<00:11,  4.32it/s]

 99%|█████████▉| 4667/4716 [24:53<00:11,  4.33it/s]

 99%|█████████▉| 4668/4716 [24:53<00:11,  4.33it/s]

 99%|█████████▉| 4669/4716 [24:53<00:10,  4.34it/s]

 99%|█████████▉| 4670/4716 [24:54<00:10,  4.33it/s]

 99%|█████████▉| 4671/4716 [24:54<00:10,  4.34it/s]

 99%|█████████▉| 4672/4716 [24:54<00:10,  4.34it/s]

 99%|█████████▉| 4673/4716 [24:54<00:09,  4.34it/s]

 99%|█████████▉| 4674/4716 [24:55<00:09,  4.33it/s]

 99%|█████████▉| 4675/4716 [24:55<00:09,  4.33it/s]

 99%|█████████▉| 4676/4716 [24:55<00:09,  4.33it/s]

 99%|█████████▉| 4677/4716 [24:55<00:09,  4.32it/s]

 99%|█████████▉| 4678/4716 [24:56<00:08,  4.32it/s]

 99%|█████████▉| 4679/4716 [24:56<00:08,  4.31it/s]

 99%|█████████▉| 4680/4716 [24:56<00:08,  4.31it/s]

 99%|█████████▉| 4681/4716 [24:56<00:08,  4.32it/s]

 99%|█████████▉| 4682/4716 [24:56<00:07,  4.32it/s]

 99%|█████████▉| 4683/4716 [24:57<00:07,  4.32it/s]

 99%|█████████▉| 4684/4716 [24:57<00:07,  4.33it/s]

 99%|█████████▉| 4685/4716 [24:57<00:07,  4.33it/s]

 99%|█████████▉| 4686/4716 [24:57<00:06,  4.34it/s]

 99%|█████████▉| 4687/4716 [24:58<00:06,  4.34it/s]

 99%|█████████▉| 4688/4716 [24:58<00:06,  4.34it/s]

 99%|█████████▉| 4689/4716 [24:58<00:06,  4.34it/s]

 99%|█████████▉| 4690/4716 [24:58<00:05,  4.34it/s]

 99%|█████████▉| 4691/4716 [24:59<00:05,  4.34it/s]

 99%|█████████▉| 4692/4716 [24:59<00:05,  4.33it/s]

100%|█████████▉| 4693/4716 [24:59<00:05,  4.33it/s]

100%|█████████▉| 4694/4716 [24:59<00:05,  4.33it/s]

100%|█████████▉| 4695/4716 [24:59<00:04,  4.33it/s]

100%|█████████▉| 4696/4716 [25:00<00:04,  4.33it/s]

100%|█████████▉| 4697/4716 [25:00<00:04,  4.33it/s]

100%|█████████▉| 4698/4716 [25:00<00:04,  4.34it/s]

100%|█████████▉| 4699/4716 [25:00<00:03,  4.34it/s]

100%|█████████▉| 4700/4716 [25:01<00:03,  4.33it/s]

100%|█████████▉| 4701/4716 [25:01<00:03,  4.34it/s]

100%|█████████▉| 4702/4716 [25:01<00:03,  4.33it/s]

100%|█████████▉| 4703/4716 [25:01<00:02,  4.34it/s]

100%|█████████▉| 4704/4716 [25:02<00:02,  4.33it/s]

100%|█████████▉| 4705/4716 [25:02<00:02,  4.33it/s]

100%|█████████▉| 4706/4716 [25:02<00:02,  4.33it/s]

100%|█████████▉| 4707/4716 [25:02<00:02,  4.32it/s]

100%|█████████▉| 4708/4716 [25:02<00:01,  4.31it/s]

100%|█████████▉| 4709/4716 [25:03<00:01,  4.31it/s]

100%|█████████▉| 4710/4716 [25:03<00:01,  4.32it/s]

100%|█████████▉| 4711/4716 [25:03<00:01,  4.33it/s]

100%|█████████▉| 4712/4716 [25:03<00:00,  4.34it/s]

100%|█████████▉| 4713/4716 [25:04<00:00,  4.34it/s]

100%|█████████▉| 4714/4716 [25:04<00:00,  4.33it/s]

100%|█████████▉| 4715/4716 [25:04<00:00,  4.34it/s]

100%|██████████| 4716/4716 [25:04<00:00,  4.41it/s]

100%|██████████| 4716/4716 [25:05<00:00,  3.13it/s]

logging the anndata

AnnData object with n_obs × n_vars = 21348 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

too few cells to embed into a umap
too few cells to compute a clustering

{'cellxgene_census/dkd_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4937716969573208, 'macro': 0.38015219981782045, 'micro': 0.4937716969573208, 'weighted': 0.44125553939089207}}, 'cellxgene_census/dkd_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4630541871921182, 'macro': 0.39612779635380635, 'micro': 0.4630541871921182, 'weighted': 0.43238258813181274}}, 'cellxgene_census/gtex_v9_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.662801373334736, 'macro': 0.45113362926393386, 'micro': 0.662801373334736, 'weighted': 0.6076783134412977}}, 'cellxgene_census/gtex_v9_cls': {'cell_type_ontology_term_id': {'accuracy': 0.4894855752519986, 'macro': 0.5275646372211268, 'micro': 0.4894855752519986, 'weighted': 0.45377925621844867}}, 'cellxgene_census/hypomap_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.8986192115347146, 'macro': 0.5346630203398964, 'micro': 0.8986192115347146, 'weighted': 0.8782631897011843}}, 'cellxgene_census/hypomap_cls': {'cell_type_ontology_term_id': {'accuracy': 0.9525547445255474, 'macro': 0.6734592457544935, 'micro': 0.9525547445255474, 'weighted': 0.9472890166071732}}, 'cellxgene_census/mouse_pancreas_atlas_ref_cls': {'cell_type_ontology_term_id': {'accuracy': 0.6353696705188564, 'macro': 0.6829825924446588, 'micro': 0.6353696705188564, 'weighted': 0.5402847879953743}}, 'cellxgene_census/mouse_pancreas_atlas_cls': {'cell_type_ontology_term_id': {'accuracy': 0.7887935600042368, 'macro': 0.7095144808117735, 'micro': 0.7887935600042368, 'weighted': 0.711819695219025}}}

doing  cellxgene_census/immune_cell_atlas

/lustre/fswork/projects/rech/xeg/uat95fg/scdataloader/scdataloader/utils.py:427: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  organismdf = pd.concat(organismdf)

predict epoch start

  0%|          | 0/5153 [00:00<?, ?it/s]

  0%|          | 1/5153 [00:06<9:11:09,  6.42s/it]

  0%|          | 2/5153 [00:06<3:58:17,  2.78s/it]

  0%|          | 3/5153 [00:06<2:18:35,  1.61s/it]

  0%|          | 4/5153 [00:07<1:31:31,  1.07s/it]

  0%|          | 5/5153 [00:07<1:05:24,  1.31it/s]

  0%|          | 6/5153 [00:07<49:40,  1.73it/s]

  0%|          | 7/5153 [00:07<39:41,  2.16it/s]

  0%|          | 8/5153 [00:07<33:08,  2.59it/s]

  0%|          | 9/5153 [00:08<28:54,  2.97it/s]

  0%|          | 10/5153 [00:08<25:59,  3.30it/s]

  0%|          | 11/5153 [00:08<23:52,  3.59it/s]

  0%|          | 12/5153 [00:08<22:26,  3.82it/s]

  0%|          | 13/5153 [00:09<21:28,  3.99it/s]

  0%|          | 14/5153 [00:09<20:45,  4.13it/s]

  0%|          | 15/5153 [00:09<20:18,  4.22it/s]

  0%|          | 16/5153 [00:09<20:06,  4.26it/s]

  0%|          | 17/5153 [00:10<19:52,  4.31it/s]

  0%|          | 18/5153 [00:10<19:43,  4.34it/s]

  0%|          | 19/5153 [00:10<20:04,  4.26it/s]

  0%|          | 20/5153 [00:10<19:53,  4.30it/s]

  0%|          | 21/5153 [00:10<19:43,  4.33it/s]

  0%|          | 22/5153 [00:11<19:36,  4.36it/s]

  0%|          | 23/5153 [00:11<19:29,  4.38it/s]

  0%|          | 24/5153 [00:11<19:27,  4.39it/s]

  0%|          | 25/5153 [00:11<19:23,  4.41it/s]

  1%|          | 26/5153 [00:12<19:23,  4.41it/s]

  1%|          | 27/5153 [00:12<19:22,  4.41it/s]

  1%|          | 28/5153 [00:12<19:22,  4.41it/s]

  1%|          | 29/5153 [00:12<19:25,  4.39it/s]

  1%|          | 30/5153 [00:12<19:28,  4.38it/s]

  1%|          | 31/5153 [00:13<19:25,  4.39it/s]

  1%|          | 32/5153 [00:13<19:23,  4.40it/s]

  1%|          | 33/5153 [00:13<19:20,  4.41it/s]

  1%|          | 34/5153 [00:13<19:20,  4.41it/s]

  1%|          | 35/5153 [00:14<19:20,  4.41it/s]

  1%|          | 36/5153 [00:14<19:19,  4.41it/s]

  1%|          | 37/5153 [00:14<19:21,  4.41it/s]

  1%|          | 38/5153 [00:14<19:21,  4.40it/s]

  1%|          | 39/5153 [00:15<19:20,  4.41it/s]

  1%|          | 40/5153 [00:15<19:19,  4.41it/s]

  1%|          | 41/5153 [00:15<19:19,  4.41it/s]

  1%|          | 42/5153 [00:15<19:16,  4.42it/s]

  1%|          | 43/5153 [00:15<19:18,  4.41it/s]

  1%|          | 44/5153 [00:16<19:19,  4.41it/s]

  1%|          | 45/5153 [00:16<19:17,  4.41it/s]

  1%|          | 46/5153 [00:16<19:16,  4.41it/s]

  1%|          | 47/5153 [00:16<19:17,  4.41it/s]

  1%|          | 48/5153 [00:17<19:17,  4.41it/s]

  1%|          | 49/5153 [00:17<19:15,  4.42it/s]

  1%|          | 50/5153 [00:17<19:18,  4.40it/s]

  1%|          | 51/5153 [00:17<19:18,  4.41it/s]

  1%|          | 52/5153 [00:17<19:16,  4.41it/s]

  1%|          | 53/5153 [00:18<19:13,  4.42it/s]

  1%|          | 54/5153 [00:18<19:13,  4.42it/s]

  1%|          | 55/5153 [00:18<19:15,  4.41it/s]

  1%|          | 56/5153 [00:18<19:15,  4.41it/s]

  1%|          | 57/5153 [00:19<19:14,  4.41it/s]

  1%|          | 58/5153 [00:19<19:15,  4.41it/s]

  1%|          | 59/5153 [00:19<19:17,  4.40it/s]

  1%|          | 60/5153 [00:19<19:16,  4.40it/s]

  1%|          | 61/5153 [00:20<19:18,  4.40it/s]

  1%|          | 62/5153 [00:20<19:15,  4.40it/s]

  1%|          | 63/5153 [00:20<19:15,  4.40it/s]

  1%|          | 64/5153 [00:20<19:16,  4.40it/s]

  1%|▏         | 65/5153 [00:20<19:16,  4.40it/s]

  1%|▏         | 66/5153 [00:21<19:14,  4.41it/s]

  1%|▏         | 67/5153 [00:21<19:14,  4.41it/s]

  1%|▏         | 68/5153 [00:21<19:13,  4.41it/s]

  1%|▏         | 69/5153 [00:21<19:13,  4.41it/s]

  1%|▏         | 70/5153 [00:22<19:15,  4.40it/s]

  1%|▏         | 71/5153 [00:22<19:11,  4.41it/s]

  1%|▏         | 72/5153 [00:22<19:10,  4.42it/s]

  1%|▏         | 73/5153 [00:22<19:12,  4.41it/s]

  1%|▏         | 74/5153 [00:22<19:09,  4.42it/s]

  1%|▏         | 75/5153 [00:23<19:12,  4.41it/s]

  1%|▏         | 76/5153 [00:23<19:13,  4.40it/s]

  1%|▏         | 77/5153 [00:23<19:20,  4.37it/s]

  2%|▏         | 78/5153 [00:23<19:19,  4.38it/s]

  2%|▏         | 79/5153 [00:24<19:17,  4.38it/s]

  2%|▏         | 80/5153 [00:24<19:13,  4.40it/s]

  2%|▏         | 81/5153 [00:24<19:15,  4.39it/s]

  2%|▏         | 82/5153 [00:24<19:14,  4.39it/s]

  2%|▏         | 83/5153 [00:25<19:13,  4.40it/s]

  2%|▏         | 84/5153 [00:25<19:13,  4.40it/s]

  2%|▏         | 85/5153 [00:25<19:13,  4.39it/s]

  2%|▏         | 86/5153 [00:25<19:14,  4.39it/s]

  2%|▏         | 87/5153 [00:25<19:15,  4.39it/s]

  2%|▏         | 88/5153 [00:26<19:14,  4.39it/s]

  2%|▏         | 89/5153 [00:26<19:13,  4.39it/s]

  2%|▏         | 90/5153 [00:26<19:15,  4.38it/s]

  2%|▏         | 91/5153 [00:26<19:13,  4.39it/s]

  2%|▏         | 92/5153 [00:27<19:12,  4.39it/s]

  2%|▏         | 93/5153 [00:27<19:12,  4.39it/s]

  2%|▏         | 94/5153 [00:27<19:12,  4.39it/s]

  2%|▏         | 95/5153 [00:27<19:10,  4.40it/s]

  2%|▏         | 96/5153 [00:27<19:09,  4.40it/s]

  2%|▏         | 97/5153 [00:28<19:10,  4.39it/s]

  2%|▏         | 98/5153 [00:28<19:09,  4.40it/s]

  2%|▏         | 99/5153 [00:28<19:10,  4.39it/s]

  2%|▏         | 100/5153 [00:28<19:08,  4.40it/s]

  2%|▏         | 101/5153 [00:29<19:07,  4.40it/s]

  2%|▏         | 102/5153 [00:29<19:07,  4.40it/s]

  2%|▏         | 103/5153 [00:29<19:09,  4.39it/s]

  2%|▏         | 104/5153 [00:29<19:09,  4.39it/s]

  2%|▏         | 105/5153 [00:30<19:09,  4.39it/s]

  2%|▏         | 106/5153 [00:30<19:06,  4.40it/s]

  2%|▏         | 107/5153 [00:30<19:07,  4.40it/s]

  2%|▏         | 108/5153 [00:30<19:08,  4.39it/s]

  2%|▏         | 109/5153 [00:30<19:10,  4.38it/s]

  2%|▏         | 110/5153 [00:31<19:12,  4.38it/s]

  2%|▏         | 111/5153 [00:31<19:10,  4.38it/s]

  2%|▏         | 112/5153 [00:31<19:12,  4.38it/s]

  2%|▏         | 113/5153 [00:31<19:12,  4.37it/s]

  2%|▏         | 114/5153 [00:32<19:10,  4.38it/s]

  2%|▏         | 115/5153 [00:32<19:09,  4.38it/s]

  2%|▏         | 116/5153 [00:32<19:09,  4.38it/s]

  2%|▏         | 117/5153 [00:32<19:06,  4.39it/s]

  2%|▏         | 118/5153 [00:32<19:08,  4.39it/s]

  2%|▏         | 119/5153 [00:33<19:08,  4.38it/s]

  2%|▏         | 120/5153 [00:33<19:16,  4.35it/s]

  2%|▏         | 121/5153 [00:33<19:15,  4.35it/s]

  2%|▏         | 122/5153 [00:33<19:13,  4.36it/s]

  2%|▏         | 123/5153 [00:34<19:11,  4.37it/s]

  2%|▏         | 124/5153 [00:34<19:11,  4.37it/s]

  2%|▏         | 125/5153 [00:34<19:07,  4.38it/s]

  2%|▏         | 126/5153 [00:34<19:05,  4.39it/s]

  2%|▏         | 127/5153 [00:35<19:04,  4.39it/s]

  2%|▏         | 128/5153 [00:35<19:04,  4.39it/s]

  3%|▎         | 129/5153 [00:35<19:05,  4.39it/s]

  3%|▎         | 130/5153 [00:35<19:05,  4.38it/s]

  3%|▎         | 131/5153 [00:35<19:01,  4.40it/s]

  3%|▎         | 132/5153 [00:36<19:01,  4.40it/s]

  3%|▎         | 133/5153 [00:36<19:02,  4.39it/s]

  3%|▎         | 134/5153 [00:36<19:04,  4.38it/s]

  3%|▎         | 135/5153 [00:36<19:06,  4.38it/s]

  3%|▎         | 136/5153 [00:37<19:04,  4.38it/s]

  3%|▎         | 137/5153 [00:37<19:03,  4.39it/s]

  3%|▎         | 138/5153 [00:37<19:04,  4.38it/s]

  3%|▎         | 139/5153 [00:37<19:01,  4.39it/s]

  3%|▎         | 140/5153 [00:38<19:01,  4.39it/s]

  3%|▎         | 141/5153 [00:38<19:02,  4.39it/s]

  3%|▎         | 142/5153 [00:38<19:02,  4.39it/s]

  3%|▎         | 143/5153 [00:38<19:03,  4.38it/s]

  3%|▎         | 144/5153 [00:38<19:03,  4.38it/s]

  3%|▎         | 145/5153 [00:39<19:02,  4.38it/s]

  3%|▎         | 146/5153 [00:39<19:01,  4.39it/s]

  3%|▎         | 147/5153 [00:39<19:01,  4.39it/s]

  3%|▎         | 148/5153 [00:39<19:01,  4.38it/s]

  3%|▎         | 149/5153 [00:40<19:05,  4.37it/s]

  3%|▎         | 150/5153 [00:40<19:04,  4.37it/s]

  3%|▎         | 151/5153 [00:40<19:03,  4.38it/s]

  3%|▎         | 152/5153 [00:40<19:02,  4.38it/s]

  3%|▎         | 153/5153 [00:40<18:59,  4.39it/s]

  3%|▎         | 154/5153 [00:41<19:01,  4.38it/s]

  3%|▎         | 155/5153 [00:41<19:01,  4.38it/s]

  3%|▎         | 156/5153 [00:41<19:01,  4.38it/s]

  3%|▎         | 157/5153 [00:41<19:03,  4.37it/s]

  3%|▎         | 158/5153 [00:42<19:02,  4.37it/s]

  3%|▎         | 159/5153 [00:42<19:00,  4.38it/s]

  3%|▎         | 160/5153 [00:42<18:58,  4.38it/s]

  3%|▎         | 161/5153 [00:42<19:01,  4.37it/s]

  3%|▎         | 162/5153 [00:43<19:01,  4.37it/s]

  3%|▎         | 163/5153 [00:43<19:02,  4.37it/s]

  3%|▎         | 164/5153 [00:43<19:01,  4.37it/s]

  3%|▎         | 165/5153 [00:43<19:00,  4.37it/s]

  3%|▎         | 166/5153 [00:43<18:59,  4.38it/s]

  3%|▎         | 167/5153 [00:44<18:58,  4.38it/s]

  3%|▎         | 168/5153 [00:44<19:01,  4.37it/s]

  3%|▎         | 169/5153 [00:44<18:59,  4.38it/s]

  3%|▎         | 170/5153 [00:44<19:00,  4.37it/s]

  3%|▎         | 171/5153 [00:45<19:01,  4.36it/s]

  3%|▎         | 172/5153 [00:45<18:59,  4.37it/s]

  3%|▎         | 173/5153 [00:45<19:00,  4.37it/s]

  3%|▎         | 174/5153 [00:45<19:01,  4.36it/s]

  3%|▎         | 175/5153 [00:46<18:59,  4.37it/s]

  3%|▎         | 176/5153 [00:46<19:01,  4.36it/s]

  3%|▎         | 177/5153 [00:46<19:01,  4.36it/s]

  3%|▎         | 178/5153 [00:46<19:00,  4.36it/s]

  3%|▎         | 179/5153 [00:46<19:01,  4.36it/s]

  3%|▎         | 180/5153 [00:47<18:58,  4.37it/s]

  4%|▎         | 181/5153 [00:47<18:59,  4.36it/s]

  4%|▎         | 182/5153 [00:47<19:00,  4.36it/s]

  4%|▎         | 183/5153 [00:47<18:59,  4.36it/s]

  4%|▎         | 184/5153 [00:48<18:58,  4.36it/s]

  4%|▎         | 185/5153 [00:48<19:00,  4.36it/s]

  4%|▎         | 186/5153 [00:48<18:58,  4.36it/s]

  4%|▎         | 187/5153 [00:48<18:56,  4.37it/s]

  4%|▎         | 188/5153 [00:49<18:59,  4.36it/s]

  4%|▎         | 189/5153 [00:49<18:58,  4.36it/s]

  4%|▎         | 190/5153 [00:49<18:58,  4.36it/s]

  4%|▎         | 191/5153 [00:49<19:12,  4.30it/s]

  4%|▎         | 192/5153 [00:49<19:06,  4.33it/s]

  4%|▎         | 193/5153 [00:50<19:03,  4.34it/s]

  4%|▍         | 194/5153 [00:50<18:59,  4.35it/s]

  4%|▍         | 195/5153 [00:50<18:56,  4.36it/s]

  4%|▍         | 196/5153 [00:50<18:53,  4.37it/s]

  4%|▍         | 197/5153 [00:51<18:51,  4.38it/s]

  4%|▍         | 198/5153 [00:51<18:51,  4.38it/s]

  4%|▍         | 199/5153 [00:51<18:52,  4.37it/s]

  4%|▍         | 200/5153 [00:51<18:50,  4.38it/s]

  4%|▍         | 201/5153 [00:51<18:51,  4.37it/s]

  4%|▍         | 202/5153 [00:52<18:51,  4.37it/s]

  4%|▍         | 203/5153 [00:52<18:53,  4.37it/s]

  4%|▍         | 204/5153 [00:52<18:54,  4.36it/s]

  4%|▍         | 205/5153 [00:52<18:51,  4.37it/s]

  4%|▍         | 206/5153 [00:53<18:51,  4.37it/s]

  4%|▍         | 207/5153 [00:53<18:51,  4.37it/s]

  4%|▍         | 208/5153 [00:53<18:50,  4.37it/s]

  4%|▍         | 209/5153 [00:53<18:52,  4.37it/s]

  4%|▍         | 210/5153 [00:54<18:51,  4.37it/s]

  4%|▍         | 211/5153 [00:54<18:50,  4.37it/s]

  4%|▍         | 212/5153 [00:54<18:49,  4.37it/s]

  4%|▍         | 213/5153 [00:54<18:49,  4.37it/s]

  4%|▍         | 214/5153 [00:54<18:49,  4.37it/s]

  4%|▍         | 215/5153 [00:55<18:52,  4.36it/s]

  4%|▍         | 216/5153 [00:55<18:52,  4.36it/s]

  4%|▍         | 217/5153 [00:55<18:50,  4.37it/s]

  4%|▍         | 218/5153 [00:55<18:50,  4.36it/s]

  4%|▍         | 219/5153 [00:56<18:48,  4.37it/s]

  4%|▍         | 220/5153 [00:56<18:48,  4.37it/s]

  4%|▍         | 221/5153 [00:56<18:49,  4.37it/s]

  4%|▍         | 222/5153 [00:56<18:49,  4.37it/s]

  4%|▍         | 223/5153 [00:57<18:51,  4.36it/s]

  4%|▍         | 224/5153 [00:57<18:50,  4.36it/s]

  4%|▍         | 225/5153 [00:57<18:51,  4.36it/s]

  4%|▍         | 226/5153 [00:57<18:52,  4.35it/s]

  4%|▍         | 227/5153 [00:57<18:48,  4.36it/s]

  4%|▍         | 228/5153 [00:58<18:48,  4.37it/s]

  4%|▍         | 229/5153 [00:58<18:49,  4.36it/s]

  4%|▍         | 230/5153 [00:58<18:46,  4.37it/s]

  4%|▍         | 231/5153 [00:58<18:48,  4.36it/s]

  5%|▍         | 232/5153 [00:59<18:48,  4.36it/s]

  5%|▍         | 233/5153 [00:59<18:46,  4.37it/s]

  5%|▍         | 234/5153 [00:59<18:47,  4.36it/s]

  5%|▍         | 235/5153 [00:59<18:51,  4.35it/s]

  5%|▍         | 236/5153 [01:00<18:50,  4.35it/s]

  5%|▍         | 237/5153 [01:00<18:50,  4.35it/s]

  5%|▍         | 238/5153 [01:00<18:48,  4.35it/s]

  5%|▍         | 239/5153 [01:00<18:46,  4.36it/s]

  5%|▍         | 240/5153 [01:00<18:48,  4.35it/s]

  5%|▍         | 241/5153 [01:01<18:45,  4.36it/s]

  5%|▍         | 242/5153 [01:01<18:43,  4.37it/s]

  5%|▍         | 243/5153 [01:01<18:45,  4.36it/s]

  5%|▍         | 244/5153 [01:01<18:40,  4.38it/s]

  5%|▍         | 245/5153 [01:02<18:41,  4.38it/s]

  5%|▍         | 246/5153 [01:02<18:47,  4.35it/s]

  5%|▍         | 247/5153 [01:02<18:45,  4.36it/s]

  5%|▍         | 248/5153 [01:02<18:45,  4.36it/s]

  5%|▍         | 249/5153 [01:02<18:42,  4.37it/s]

  5%|▍         | 250/5153 [01:03<18:41,  4.37it/s]

  5%|▍         | 251/5153 [01:03<18:42,  4.37it/s]

  5%|▍         | 252/5153 [01:03<18:40,  4.37it/s]

  5%|▍         | 253/5153 [01:03<18:39,  4.38it/s]

  5%|▍         | 254/5153 [01:04<18:42,  4.37it/s]

  5%|▍         | 255/5153 [01:04<18:40,  4.37it/s]

  5%|▍         | 256/5153 [01:04<18:42,  4.36it/s]

  5%|▍         | 257/5153 [01:04<18:41,  4.37it/s]

  5%|▌         | 258/5153 [01:05<18:41,  4.36it/s]

  5%|▌         | 259/5153 [01:05<18:41,  4.36it/s]

  5%|▌         | 260/5153 [01:05<18:40,  4.37it/s]

  5%|▌         | 261/5153 [01:05<18:40,  4.37it/s]

  5%|▌         | 262/5153 [01:05<18:40,  4.37it/s]

  5%|▌         | 263/5153 [01:06<18:37,  4.38it/s]

  5%|▌         | 264/5153 [01:06<18:38,  4.37it/s]

  5%|▌         | 265/5153 [01:06<18:38,  4.37it/s]

  5%|▌         | 266/5153 [01:06<18:47,  4.34it/s]

  5%|▌         | 267/5153 [01:07<18:46,  4.34it/s]

  5%|▌         | 268/5153 [01:07<18:43,  4.35it/s]

  5%|▌         | 269/5153 [01:07<18:43,  4.35it/s]

  5%|▌         | 270/5153 [01:07<18:41,  4.35it/s]

  5%|▌         | 271/5153 [01:08<18:40,  4.36it/s]

  5%|▌         | 272/5153 [01:08<18:40,  4.36it/s]

  5%|▌         | 273/5153 [01:08<18:41,  4.35it/s]

  5%|▌         | 274/5153 [01:08<18:38,  4.36it/s]

  5%|▌         | 275/5153 [01:08<18:39,  4.36it/s]

  5%|▌         | 276/5153 [01:09<18:44,  4.34it/s]

  5%|▌         | 277/5153 [01:09<18:42,  4.35it/s]

  5%|▌         | 278/5153 [01:09<18:42,  4.34it/s]

  5%|▌         | 279/5153 [01:09<18:39,  4.35it/s]

  5%|▌         | 280/5153 [01:10<18:40,  4.35it/s]

  5%|▌         | 281/5153 [01:10<18:40,  4.35it/s]

  5%|▌         | 282/5153 [01:10<18:37,  4.36it/s]

  5%|▌         | 283/5153 [01:10<18:35,  4.37it/s]

  6%|▌         | 284/5153 [01:11<18:36,  4.36it/s]

  6%|▌         | 285/5153 [01:11<18:47,  4.32it/s]

  6%|▌         | 286/5153 [01:11<18:45,  4.32it/s]

  6%|▌         | 287/5153 [01:11<18:41,  4.34it/s]

  6%|▌         | 288/5153 [01:11<18:39,  4.35it/s]

  6%|▌         | 289/5153 [01:12<18:38,  4.35it/s]

  6%|▌         | 290/5153 [01:12<18:35,  4.36it/s]

  6%|▌         | 291/5153 [01:12<18:35,  4.36it/s]

  6%|▌         | 292/5153 [01:12<18:38,  4.35it/s]

  6%|▌         | 293/5153 [01:13<18:35,  4.35it/s]

  6%|▌         | 294/5153 [01:13<18:37,  4.35it/s]

  6%|▌         | 295/5153 [01:13<18:35,  4.35it/s]

  6%|▌         | 296/5153 [01:13<18:37,  4.35it/s]

  6%|▌         | 297/5153 [01:14<18:35,  4.35it/s]

  6%|▌         | 298/5153 [01:14<18:35,  4.35it/s]

  6%|▌         | 299/5153 [01:14<18:35,  4.35it/s]

  6%|▌         | 300/5153 [01:14<18:35,  4.35it/s]

  6%|▌         | 301/5153 [01:14<18:35,  4.35it/s]

  6%|▌         | 302/5153 [01:15<18:35,  4.35it/s]

  6%|▌         | 303/5153 [01:15<18:41,  4.33it/s]

  6%|▌         | 304/5153 [01:15<18:35,  4.35it/s]

  6%|▌         | 305/5153 [01:15<18:34,  4.35it/s]

  6%|▌         | 306/5153 [01:16<18:31,  4.36it/s]

  6%|▌         | 307/5153 [01:16<18:31,  4.36it/s]

  6%|▌         | 308/5153 [01:16<18:32,  4.36it/s]

  6%|▌         | 309/5153 [01:16<18:29,  4.37it/s]

  6%|▌         | 310/5153 [01:16<18:28,  4.37it/s]

  6%|▌         | 311/5153 [01:17<18:27,  4.37it/s]

  6%|▌         | 312/5153 [01:17<18:25,  4.38it/s]

  6%|▌         | 313/5153 [01:17<18:26,  4.37it/s]

  6%|▌         | 314/5153 [01:17<18:26,  4.38it/s]

  6%|▌         | 315/5153 [01:18<18:26,  4.37it/s]

  6%|▌         | 316/5153 [01:18<18:25,  4.37it/s]

  6%|▌         | 317/5153 [01:18<18:23,  4.38it/s]

  6%|▌         | 318/5153 [01:18<18:24,  4.38it/s]

  6%|▌         | 319/5153 [01:19<18:25,  4.37it/s]

  6%|▌         | 320/5153 [01:19<18:22,  4.38it/s]

  6%|▌         | 321/5153 [01:19<18:23,  4.38it/s]

  6%|▌         | 322/5153 [01:19<18:24,  4.37it/s]

  6%|▋         | 323/5153 [01:19<18:30,  4.35it/s]

  6%|▋         | 324/5153 [01:20<18:31,  4.35it/s]

  6%|▋         | 325/5153 [01:20<18:32,  4.34it/s]

  6%|▋         | 326/5153 [01:20<18:30,  4.35it/s]

  6%|▋         | 327/5153 [01:20<18:30,  4.35it/s]

  6%|▋         | 328/5153 [01:21<18:28,  4.35it/s]

  6%|▋         | 329/5153 [01:21<18:27,  4.36it/s]

  6%|▋         | 330/5153 [01:21<18:26,  4.36it/s]

  6%|▋         | 331/5153 [01:21<18:24,  4.36it/s]

  6%|▋         | 332/5153 [01:22<18:25,  4.36it/s]

  6%|▋         | 333/5153 [01:22<18:31,  4.34it/s]

  6%|▋         | 334/5153 [01:22<18:28,  4.35it/s]

  7%|▋         | 335/5153 [01:22<18:29,  4.34it/s]

  7%|▋         | 336/5153 [01:22<18:27,  4.35it/s]

  7%|▋         | 337/5153 [01:23<18:28,  4.34it/s]

  7%|▋         | 338/5153 [01:23<18:28,  4.34it/s]

  7%|▋         | 339/5153 [01:23<18:25,  4.36it/s]

  7%|▋         | 340/5153 [01:23<18:24,  4.36it/s]

  7%|▋         | 341/5153 [01:24<18:25,  4.35it/s]

  7%|▋         | 342/5153 [01:24<18:25,  4.35it/s]

  7%|▋         | 343/5153 [01:24<18:24,  4.35it/s]

  7%|▋         | 344/5153 [01:24<18:23,  4.36it/s]

  7%|▋         | 345/5153 [01:25<18:23,  4.36it/s]

  7%|▋         | 346/5153 [01:25<18:26,  4.34it/s]

  7%|▋         | 347/5153 [01:25<18:23,  4.35it/s]

  7%|▋         | 348/5153 [01:25<18:23,  4.35it/s]

  7%|▋         | 349/5153 [01:25<18:24,  4.35it/s]

  7%|▋         | 350/5153 [01:26<18:21,  4.36it/s]

  7%|▋         | 351/5153 [01:26<18:18,  4.37it/s]

  7%|▋         | 352/5153 [01:26<18:20,  4.36it/s]

  7%|▋         | 353/5153 [01:26<18:19,  4.36it/s]

  7%|▋         | 354/5153 [01:27<18:21,  4.36it/s]

  7%|▋         | 355/5153 [01:27<18:22,  4.35it/s]

  7%|▋         | 356/5153 [01:27<18:23,  4.35it/s]

  7%|▋         | 357/5153 [01:27<18:23,  4.35it/s]

  7%|▋         | 358/5153 [01:28<18:20,  4.36it/s]

  7%|▋         | 359/5153 [01:28<18:20,  4.36it/s]

  7%|▋         | 360/5153 [01:28<18:20,  4.36it/s]

  7%|▋         | 361/5153 [01:28<18:18,  4.36it/s]

  7%|▋         | 362/5153 [01:28<18:19,  4.36it/s]

  7%|▋         | 363/5153 [01:29<18:18,  4.36it/s]

  7%|▋         | 364/5153 [01:29<18:18,  4.36it/s]

  7%|▋         | 365/5153 [01:29<18:20,  4.35it/s]

  7%|▋         | 366/5153 [01:29<18:22,  4.34it/s]

  7%|▋         | 367/5153 [01:30<18:22,  4.34it/s]

  7%|▋         | 368/5153 [01:30<18:22,  4.34it/s]

  7%|▋         | 369/5153 [01:30<18:20,  4.35it/s]

  7%|▋         | 370/5153 [01:30<18:19,  4.35it/s]

  7%|▋         | 371/5153 [01:30<18:19,  4.35it/s]

  7%|▋         | 372/5153 [01:31<18:19,  4.35it/s]

  7%|▋         | 373/5153 [01:31<18:20,  4.35it/s]

  7%|▋         | 374/5153 [01:31<18:20,  4.34it/s]

  7%|▋         | 375/5153 [01:31<18:19,  4.34it/s]

  7%|▋         | 376/5153 [01:32<18:18,  4.35it/s]

  7%|▋         | 377/5153 [01:32<18:20,  4.34it/s]

  7%|▋         | 378/5153 [01:32<18:24,  4.32it/s]

  7%|▋         | 379/5153 [01:32<18:25,  4.32it/s]

  7%|▋         | 380/5153 [01:33<18:24,  4.32it/s]

  7%|▋         | 381/5153 [01:33<18:24,  4.32it/s]

  7%|▋         | 382/5153 [01:33<18:20,  4.33it/s]

  7%|▋         | 383/5153 [01:33<18:21,  4.33it/s]

  7%|▋         | 384/5153 [01:33<18:18,  4.34it/s]

  7%|▋         | 385/5153 [01:34<18:19,  4.33it/s]

  7%|▋         | 386/5153 [01:34<18:16,  4.35it/s]

  8%|▊         | 387/5153 [01:34<18:16,  4.35it/s]

  8%|▊         | 388/5153 [01:34<18:14,  4.35it/s]

  8%|▊         | 389/5153 [01:35<18:15,  4.35it/s]

  8%|▊         | 390/5153 [01:35<18:15,  4.35it/s]

  8%|▊         | 391/5153 [01:35<18:17,  4.34it/s]

  8%|▊         | 392/5153 [01:35<18:15,  4.35it/s]

  8%|▊         | 393/5153 [01:36<18:16,  4.34it/s]

  8%|▊         | 394/5153 [01:36<18:17,  4.34it/s]

  8%|▊         | 395/5153 [01:36<18:17,  4.33it/s]

  8%|▊         | 396/5153 [01:36<18:16,  4.34it/s]

  8%|▊         | 397/5153 [01:36<18:15,  4.34it/s]

  8%|▊         | 398/5153 [01:37<18:16,  4.34it/s]

  8%|▊         | 399/5153 [01:37<18:16,  4.33it/s]

  8%|▊         | 400/5153 [01:37<18:15,  4.34it/s]

  8%|▊         | 401/5153 [01:37<18:14,  4.34it/s]

  8%|▊         | 402/5153 [01:38<18:15,  4.33it/s]

  8%|▊         | 403/5153 [01:38<18:15,  4.34it/s]

  8%|▊         | 404/5153 [01:38<18:15,  4.33it/s]

  8%|▊         | 405/5153 [01:38<18:14,  4.34it/s]

  8%|▊         | 406/5153 [01:39<18:14,  4.34it/s]

  8%|▊         | 407/5153 [01:39<18:15,  4.33it/s]

  8%|▊         | 408/5153 [01:39<18:13,  4.34it/s]

  8%|▊         | 409/5153 [01:39<18:14,  4.33it/s]

  8%|▊         | 410/5153 [01:39<18:17,  4.32it/s]

  8%|▊         | 411/5153 [01:40<18:15,  4.33it/s]

  8%|▊         | 412/5153 [01:40<18:13,  4.34it/s]

  8%|▊         | 413/5153 [01:40<18:11,  4.34it/s]

  8%|▊         | 414/5153 [01:40<18:12,  4.34it/s]

  8%|▊         | 415/5153 [01:41<18:12,  4.34it/s]

  8%|▊         | 416/5153 [01:41<18:14,  4.33it/s]

  8%|▊         | 417/5153 [01:41<18:17,  4.32it/s]

  8%|▊         | 418/5153 [01:41<18:15,  4.32it/s]

  8%|▊         | 419/5153 [01:42<18:14,  4.32it/s]

  8%|▊         | 420/5153 [01:42<18:14,  4.33it/s]

  8%|▊         | 421/5153 [01:42<18:11,  4.34it/s]

  8%|▊         | 422/5153 [01:42<18:11,  4.33it/s]

  8%|▊         | 423/5153 [01:42<18:10,  4.34it/s]

  8%|▊         | 424/5153 [01:43<18:12,  4.33it/s]

  8%|▊         | 425/5153 [01:43<18:12,  4.33it/s]

  8%|▊         | 426/5153 [01:43<18:12,  4.33it/s]

  8%|▊         | 427/5153 [01:43<18:13,  4.32it/s]

  8%|▊         | 428/5153 [01:44<18:12,  4.32it/s]

  8%|▊         | 429/5153 [01:44<18:12,  4.32it/s]

  8%|▊         | 430/5153 [01:44<18:10,  4.33it/s]

  8%|▊         | 431/5153 [01:44<18:11,  4.33it/s]

  8%|▊         | 432/5153 [01:45<18:10,  4.33it/s]

  8%|▊         | 433/5153 [01:45<18:09,  4.33it/s]

  8%|▊         | 434/5153 [01:45<18:08,  4.33it/s]

  8%|▊         | 435/5153 [01:45<18:12,  4.32it/s]

  8%|▊         | 436/5153 [01:45<18:13,  4.32it/s]

  8%|▊         | 437/5153 [01:46<18:09,  4.33it/s]

  8%|▊         | 438/5153 [01:46<18:09,  4.33it/s]

  9%|▊         | 439/5153 [01:46<18:10,  4.32it/s]

  9%|▊         | 440/5153 [01:46<18:07,  4.33it/s]

  9%|▊         | 441/5153 [01:47<18:06,  4.34it/s]

  9%|▊         | 442/5153 [01:47<18:04,  4.34it/s]

  9%|▊         | 443/5153 [01:47<18:09,  4.32it/s]

  9%|▊         | 444/5153 [01:47<18:08,  4.32it/s]

  9%|▊         | 445/5153 [01:48<18:08,  4.33it/s]

  9%|▊         | 446/5153 [01:48<18:09,  4.32it/s]

  9%|▊         | 447/5153 [01:48<18:10,  4.31it/s]

  9%|▊         | 448/5153 [01:48<18:09,  4.32it/s]

  9%|▊         | 449/5153 [01:48<18:09,  4.32it/s]

  9%|▊         | 450/5153 [01:49<18:06,  4.33it/s]

  9%|▉         | 451/5153 [01:49<18:05,  4.33it/s]

  9%|▉         | 452/5153 [01:49<18:04,  4.33it/s]

  9%|▉         | 453/5153 [01:49<18:05,  4.33it/s]

  9%|▉         | 454/5153 [01:50<18:07,  4.32it/s]

  9%|▉         | 455/5153 [01:50<18:19,  4.27it/s]

  9%|▉         | 456/5153 [01:50<18:14,  4.29it/s]

  9%|▉         | 457/5153 [01:50<18:11,  4.30it/s]

  9%|▉         | 458/5153 [01:51<18:06,  4.32it/s]

  9%|▉         | 459/5153 [01:51<18:07,  4.32it/s]

  9%|▉         | 460/5153 [01:51<18:04,  4.33it/s]

  9%|▉         | 461/5153 [01:51<18:01,  4.34it/s]

  9%|▉         | 462/5153 [01:52<18:02,  4.33it/s]

  9%|▉         | 463/5153 [01:52<18:06,  4.32it/s]

  9%|▉         | 464/5153 [01:52<18:04,  4.32it/s]

  9%|▉         | 465/5153 [01:52<18:02,  4.33it/s]

  9%|▉         | 466/5153 [01:52<18:01,  4.33it/s]

  9%|▉         | 467/5153 [01:53<18:03,  4.33it/s]

  9%|▉         | 468/5153 [01:53<18:04,  4.32it/s]

  9%|▉         | 469/5153 [01:53<18:03,  4.32it/s]

  9%|▉         | 470/5153 [01:53<18:05,  4.32it/s]

  9%|▉         | 471/5153 [01:54<18:06,  4.31it/s]

  9%|▉         | 472/5153 [01:54<18:05,  4.31it/s]

  9%|▉         | 473/5153 [01:54<18:06,  4.31it/s]

  9%|▉         | 474/5153 [01:54<18:04,  4.31it/s]

  9%|▉         | 475/5153 [01:55<18:05,  4.31it/s]

  9%|▉         | 476/5153 [01:55<18:05,  4.31it/s]

  9%|▉         | 477/5153 [01:55<18:04,  4.31it/s]

  9%|▉         | 478/5153 [01:55<18:05,  4.31it/s]

  9%|▉         | 479/5153 [01:55<18:05,  4.31it/s]

  9%|▉         | 480/5153 [01:56<18:05,  4.31it/s]

  9%|▉         | 481/5153 [01:56<18:04,  4.31it/s]

  9%|▉         | 482/5153 [01:56<18:02,  4.32it/s]

  9%|▉         | 483/5153 [01:56<18:03,  4.31it/s]

  9%|▉         | 484/5153 [01:57<18:05,  4.30it/s]

  9%|▉         | 485/5153 [01:57<18:04,  4.31it/s]

  9%|▉         | 486/5153 [01:57<18:04,  4.30it/s]

  9%|▉         | 487/5153 [01:57<18:03,  4.31it/s]

  9%|▉         | 488/5153 [01:58<18:04,  4.30it/s]

  9%|▉         | 489/5153 [01:58<18:03,  4.30it/s]

 10%|▉         | 490/5153 [01:58<18:03,  4.30it/s]

 10%|▉         | 491/5153 [01:58<18:03,  4.30it/s]

 10%|▉         | 492/5153 [01:58<18:03,  4.30it/s]

 10%|▉         | 493/5153 [01:59<18:02,  4.30it/s]

 10%|▉         | 494/5153 [01:59<18:02,  4.30it/s]

 10%|▉         | 495/5153 [01:59<17:59,  4.32it/s]

 10%|▉         | 496/5153 [01:59<17:59,  4.31it/s]

 10%|▉         | 497/5153 [02:00<18:05,  4.29it/s]

 10%|▉         | 498/5153 [02:00<18:03,  4.30it/s]

 10%|▉         | 499/5153 [02:00<18:03,  4.30it/s]

 10%|▉         | 500/5153 [02:00<18:00,  4.31it/s]

 10%|▉         | 501/5153 [02:01<18:00,  4.31it/s]

 10%|▉         | 502/5153 [02:01<18:01,  4.30it/s]

 10%|▉         | 503/5153 [02:01<17:57,  4.31it/s]

 10%|▉         | 504/5153 [02:01<17:59,  4.31it/s]

 10%|▉         | 505/5153 [02:01<17:56,  4.32it/s]

 10%|▉         | 506/5153 [02:02<17:58,  4.31it/s]

 10%|▉         | 507/5153 [02:02<17:59,  4.30it/s]

 10%|▉         | 508/5153 [02:02<17:59,  4.30it/s]

 10%|▉         | 509/5153 [02:02<17:58,  4.31it/s]

 10%|▉         | 510/5153 [02:03<18:01,  4.29it/s]

 10%|▉         | 511/5153 [02:03<17:58,  4.30it/s]

 10%|▉         | 512/5153 [02:03<17:59,  4.30it/s]

 10%|▉         | 513/5153 [02:03<17:58,  4.30it/s]

 10%|▉         | 514/5153 [02:04<17:54,  4.32it/s]

 10%|▉         | 515/5153 [02:04<17:53,  4.32it/s]

 10%|█         | 516/5153 [02:04<17:52,  4.33it/s]

 10%|█         | 517/5153 [02:04<17:55,  4.31it/s]

 10%|█         | 518/5153 [02:05<17:56,  4.30it/s]

 10%|█         | 519/5153 [02:05<17:58,  4.30it/s]

 10%|█         | 520/5153 [02:05<17:59,  4.29it/s]

 10%|█         | 521/5153 [02:05<17:58,  4.30it/s]

 10%|█         | 522/5153 [02:05<17:59,  4.29it/s]

 10%|█         | 523/5153 [02:06<17:58,  4.29it/s]

 10%|█         | 524/5153 [02:06<17:58,  4.29it/s]

 10%|█         | 525/5153 [02:06<18:02,  4.28it/s]

 10%|█         | 526/5153 [02:06<17:58,  4.29it/s]

 10%|█         | 527/5153 [02:07<18:00,  4.28it/s]

 10%|█         | 528/5153 [02:07<18:12,  4.23it/s]

 10%|█         | 529/5153 [02:07<18:08,  4.25it/s]

 10%|█         | 530/5153 [02:07<18:06,  4.26it/s]

 10%|█         | 531/5153 [02:08<18:08,  4.25it/s]

 10%|█         | 532/5153 [02:08<18:06,  4.25it/s]

 10%|█         | 533/5153 [02:08<18:05,  4.25it/s]

 10%|█         | 534/5153 [02:08<18:03,  4.26it/s]

 10%|█         | 535/5153 [02:08<18:01,  4.27it/s]

 10%|█         | 536/5153 [02:09<17:58,  4.28it/s]

 10%|█         | 537/5153 [02:09<17:57,  4.28it/s]

 10%|█         | 538/5153 [02:09<17:55,  4.29it/s]

 10%|█         | 539/5153 [02:09<17:59,  4.27it/s]

 10%|█         | 540/5153 [02:10<17:57,  4.28it/s]

 10%|█         | 541/5153 [02:10<17:55,  4.29it/s]

 11%|█         | 542/5153 [02:10<17:56,  4.29it/s]

 11%|█         | 543/5153 [02:10<17:55,  4.29it/s]

 11%|█         | 544/5153 [02:11<17:52,  4.30it/s]

 11%|█         | 545/5153 [02:11<17:53,  4.29it/s]

 11%|█         | 546/5153 [02:11<17:52,  4.29it/s]

 11%|█         | 547/5153 [02:11<17:53,  4.29it/s]

 11%|█         | 548/5153 [02:12<17:52,  4.29it/s]

 11%|█         | 549/5153 [02:12<17:53,  4.29it/s]

 11%|█         | 550/5153 [02:12<17:52,  4.29it/s]

 11%|█         | 551/5153 [02:12<17:51,  4.30it/s]

 11%|█         | 552/5153 [02:12<17:50,  4.30it/s]

 11%|█         | 553/5153 [02:13<17:51,  4.29it/s]

 11%|█         | 554/5153 [02:13<17:51,  4.29it/s]

 11%|█         | 555/5153 [02:13<17:52,  4.29it/s]

 11%|█         | 556/5153 [02:13<17:58,  4.26it/s]

 11%|█         | 557/5153 [02:14<17:56,  4.27it/s]

 11%|█         | 558/5153 [02:14<17:53,  4.28it/s]

 11%|█         | 559/5153 [02:14<17:52,  4.28it/s]

 11%|█         | 560/5153 [02:14<17:54,  4.27it/s]

 11%|█         | 561/5153 [02:15<17:54,  4.27it/s]

 11%|█         | 562/5153 [02:15<17:54,  4.27it/s]

 11%|█         | 563/5153 [02:15<17:53,  4.28it/s]

 11%|█         | 564/5153 [02:15<17:51,  4.28it/s]

 11%|█         | 565/5153 [02:15<17:51,  4.28it/s]

 11%|█         | 566/5153 [02:16<17:52,  4.28it/s]

 11%|█         | 567/5153 [02:16<17:52,  4.28it/s]

 11%|█         | 568/5153 [02:16<17:53,  4.27it/s]

 11%|█         | 569/5153 [02:16<17:53,  4.27it/s]

 11%|█         | 570/5153 [02:17<17:52,  4.27it/s]

 11%|█         | 571/5153 [02:17<17:54,  4.26it/s]

 11%|█         | 572/5153 [02:17<17:50,  4.28it/s]

 11%|█         | 573/5153 [02:17<17:51,  4.27it/s]

 11%|█         | 574/5153 [02:18<17:50,  4.28it/s]

 11%|█         | 575/5153 [02:18<17:51,  4.27it/s]

 11%|█         | 576/5153 [02:18<17:50,  4.28it/s]

 11%|█         | 577/5153 [02:18<17:48,  4.28it/s]

 11%|█         | 578/5153 [02:19<17:49,  4.28it/s]

 11%|█         | 579/5153 [02:19<17:47,  4.28it/s]

 11%|█▏        | 580/5153 [02:19<17:47,  4.28it/s]

 11%|█▏        | 581/5153 [02:19<17:48,  4.28it/s]

 11%|█▏        | 582/5153 [02:19<17:47,  4.28it/s]

 11%|█▏        | 583/5153 [02:20<17:46,  4.28it/s]

 11%|█▏        | 584/5153 [02:20<17:46,  4.28it/s]

 11%|█▏        | 585/5153 [02:20<17:54,  4.25it/s]

 11%|█▏        | 586/5153 [02:20<17:53,  4.26it/s]

 11%|█▏        | 587/5153 [02:21<17:50,  4.26it/s]

 11%|█▏        | 588/5153 [02:21<17:51,  4.26it/s]

 11%|█▏        | 589/5153 [02:21<17:51,  4.26it/s]

 11%|█▏        | 590/5153 [02:21<17:47,  4.27it/s]

 11%|█▏        | 591/5153 [02:22<17:49,  4.27it/s]

 11%|█▏        | 592/5153 [02:22<17:48,  4.27it/s]

 12%|█▏        | 593/5153 [02:22<17:48,  4.27it/s]

 12%|█▏        | 594/5153 [02:22<17:49,  4.26it/s]

 12%|█▏        | 595/5153 [02:23<17:48,  4.27it/s]

 12%|█▏        | 596/5153 [02:23<17:50,  4.26it/s]

 12%|█▏        | 597/5153 [02:23<17:47,  4.27it/s]

 12%|█▏        | 598/5153 [02:23<17:46,  4.27it/s]

 12%|█▏        | 599/5153 [02:23<17:46,  4.27it/s]

 12%|█▏        | 600/5153 [02:24<17:46,  4.27it/s]

 12%|█▏        | 601/5153 [02:24<17:46,  4.27it/s]

 12%|█▏        | 602/5153 [02:24<17:45,  4.27it/s]

 12%|█▏        | 603/5153 [02:24<17:45,  4.27it/s]

 12%|█▏        | 604/5153 [02:25<17:43,  4.28it/s]

 12%|█▏        | 605/5153 [02:25<17:41,  4.28it/s]

 12%|█▏        | 606/5153 [02:25<17:42,  4.28it/s]

 12%|█▏        | 607/5153 [02:25<17:41,  4.28it/s]

 12%|█▏        | 608/5153 [02:26<17:42,  4.28it/s]

 12%|█▏        | 609/5153 [02:26<17:45,  4.27it/s]

 12%|█▏        | 610/5153 [02:26<17:44,  4.27it/s]

 12%|█▏        | 611/5153 [02:26<17:43,  4.27it/s]

 12%|█▏        | 612/5153 [02:26<17:44,  4.27it/s]

 12%|█▏        | 613/5153 [02:27<17:44,  4.26it/s]

 12%|█▏        | 614/5153 [02:27<17:46,  4.25it/s]

 12%|█▏        | 615/5153 [02:27<17:46,  4.26it/s]

 12%|█▏        | 616/5153 [02:27<17:47,  4.25it/s]

 12%|█▏        | 617/5153 [02:28<17:45,  4.26it/s]

 12%|█▏        | 618/5153 [02:28<17:44,  4.26it/s]

 12%|█▏        | 619/5153 [02:28<17:43,  4.26it/s]

 12%|█▏        | 620/5153 [02:28<17:41,  4.27it/s]

 12%|█▏        | 621/5153 [02:29<17:41,  4.27it/s]

 12%|█▏        | 622/5153 [02:29<17:43,  4.26it/s]

 12%|█▏        | 623/5153 [02:29<17:41,  4.27it/s]

 12%|█▏        | 624/5153 [02:29<17:42,  4.26it/s]

 12%|█▏        | 625/5153 [02:30<17:40,  4.27it/s]

logging
logging the anndata

 12%|█▏        | 626/5153 [02:31<48:17,  1.56it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 12%|█▏        | 627/5153 [02:31<38:55,  1.94it/s]

 12%|█▏        | 628/5153 [02:32<32:20,  2.33it/s]

 12%|█▏        | 629/5153 [02:32<27:48,  2.71it/s]

 12%|█▏        | 630/5153 [02:32<24:37,  3.06it/s]

 12%|█▏        | 631/5153 [02:32<22:24,  3.36it/s]

 12%|█▏        | 632/5153 [02:32<20:50,  3.62it/s]

 12%|█▏        | 633/5153 [02:33<19:43,  3.82it/s]

 12%|█▏        | 634/5153 [02:33<18:56,  3.98it/s]

 12%|█▏        | 635/5153 [02:33<18:24,  4.09it/s]

 12%|█▏        | 636/5153 [02:33<18:04,  4.17it/s]

 12%|█▏        | 637/5153 [02:34<17:47,  4.23it/s]

 12%|█▏        | 638/5153 [02:34<17:36,  4.27it/s]

 12%|█▏        | 639/5153 [02:34<17:27,  4.31it/s]

 12%|█▏        | 640/5153 [02:34<17:22,  4.33it/s]

 12%|█▏        | 641/5153 [02:35<17:22,  4.33it/s]

 12%|█▏        | 642/5153 [02:35<17:18,  4.34it/s]

 12%|█▏        | 643/5153 [02:35<17:17,  4.35it/s]

 12%|█▏        | 644/5153 [02:35<17:15,  4.35it/s]

 13%|█▎        | 645/5153 [02:35<17:11,  4.37it/s]

 13%|█▎        | 646/5153 [02:36<17:10,  4.37it/s]

 13%|█▎        | 647/5153 [02:36<17:09,  4.38it/s]

 13%|█▎        | 648/5153 [02:36<17:07,  4.39it/s]

 13%|█▎        | 649/5153 [02:36<17:06,  4.39it/s]

 13%|█▎        | 650/5153 [02:37<17:08,  4.38it/s]

 13%|█▎        | 651/5153 [02:37<17:06,  4.39it/s]

 13%|█▎        | 652/5153 [02:37<17:04,  4.39it/s]

 13%|█▎        | 653/5153 [02:37<17:04,  4.39it/s]

 13%|█▎        | 654/5153 [02:38<17:04,  4.39it/s]

 13%|█▎        | 655/5153 [02:38<17:06,  4.38it/s]

 13%|█▎        | 656/5153 [02:38<17:15,  4.34it/s]

 13%|█▎        | 657/5153 [02:38<17:13,  4.35it/s]

 13%|█▎        | 658/5153 [02:38<17:11,  4.36it/s]

 13%|█▎        | 659/5153 [02:39<17:09,  4.36it/s]

 13%|█▎        | 660/5153 [02:39<17:09,  4.37it/s]

 13%|█▎        | 661/5153 [02:39<17:09,  4.37it/s]

 13%|█▎        | 662/5153 [02:39<17:08,  4.37it/s]

 13%|█▎        | 663/5153 [02:40<17:09,  4.36it/s]

 13%|█▎        | 664/5153 [02:40<17:08,  4.36it/s]

 13%|█▎        | 665/5153 [02:40<17:06,  4.37it/s]

 13%|█▎        | 666/5153 [02:40<17:07,  4.37it/s]

 13%|█▎        | 667/5153 [02:40<17:07,  4.37it/s]

 13%|█▎        | 668/5153 [02:41<17:05,  4.38it/s]

 13%|█▎        | 669/5153 [02:41<17:04,  4.38it/s]

 13%|█▎        | 670/5153 [02:41<17:04,  4.38it/s]

 13%|█▎        | 671/5153 [02:41<17:02,  4.38it/s]

 13%|█▎        | 672/5153 [02:42<17:03,  4.38it/s]

 13%|█▎        | 673/5153 [02:42<17:06,  4.36it/s]

 13%|█▎        | 674/5153 [02:42<17:04,  4.37it/s]

 13%|█▎        | 675/5153 [02:42<17:03,  4.38it/s]

 13%|█▎        | 676/5153 [02:43<17:05,  4.37it/s]

 13%|█▎        | 677/5153 [02:43<17:03,  4.37it/s]

 13%|█▎        | 678/5153 [02:43<17:03,  4.37it/s]

 13%|█▎        | 679/5153 [02:43<17:09,  4.34it/s]

 13%|█▎        | 680/5153 [02:43<17:08,  4.35it/s]

 13%|█▎        | 681/5153 [02:44<17:06,  4.36it/s]

 13%|█▎        | 682/5153 [02:44<17:04,  4.36it/s]

 13%|█▎        | 683/5153 [02:44<17:03,  4.37it/s]

 13%|█▎        | 684/5153 [02:44<17:02,  4.37it/s]

 13%|█▎        | 685/5153 [02:45<17:01,  4.37it/s]

 13%|█▎        | 686/5153 [02:45<17:01,  4.37it/s]

 13%|█▎        | 687/5153 [02:45<16:59,  4.38it/s]

 13%|█▎        | 688/5153 [02:45<16:59,  4.38it/s]

 13%|█▎        | 689/5153 [02:46<17:02,  4.37it/s]

 13%|█▎        | 690/5153 [02:46<17:11,  4.33it/s]

 13%|█▎        | 691/5153 [02:46<17:07,  4.34it/s]

 13%|█▎        | 692/5153 [02:46<17:07,  4.34it/s]

 13%|█▎        | 693/5153 [02:46<17:02,  4.36it/s]

 13%|█▎        | 694/5153 [02:47<17:02,  4.36it/s]

 13%|█▎        | 695/5153 [02:47<17:00,  4.37it/s]

 14%|█▎        | 696/5153 [02:47<16:58,  4.38it/s]

 14%|█▎        | 697/5153 [02:47<16:57,  4.38it/s]

 14%|█▎        | 698/5153 [02:48<16:57,  4.38it/s]

 14%|█▎        | 699/5153 [02:48<16:57,  4.38it/s]

 14%|█▎        | 700/5153 [02:48<16:55,  4.38it/s]

 14%|█▎        | 701/5153 [02:48<16:57,  4.38it/s]

 14%|█▎        | 702/5153 [02:49<16:57,  4.38it/s]

 14%|█▎        | 703/5153 [02:49<16:57,  4.37it/s]

 14%|█▎        | 704/5153 [02:49<16:59,  4.37it/s]

 14%|█▎        | 705/5153 [02:49<16:58,  4.37it/s]

 14%|█▎        | 706/5153 [02:49<16:58,  4.37it/s]

 14%|█▎        | 707/5153 [02:50<16:56,  4.37it/s]

 14%|█▎        | 708/5153 [02:50<16:56,  4.37it/s]

 14%|█▍        | 709/5153 [02:50<16:58,  4.36it/s]

 14%|█▍        | 710/5153 [02:50<16:55,  4.38it/s]

 14%|█▍        | 711/5153 [02:51<16:55,  4.37it/s]

 14%|█▍        | 712/5153 [02:51<16:54,  4.38it/s]

 14%|█▍        | 713/5153 [02:51<16:52,  4.38it/s]

 14%|█▍        | 714/5153 [02:51<16:56,  4.37it/s]

 14%|█▍        | 715/5153 [02:51<16:57,  4.36it/s]

 14%|█▍        | 716/5153 [02:52<16:58,  4.36it/s]

 14%|█▍        | 717/5153 [02:52<16:56,  4.36it/s]

 14%|█▍        | 718/5153 [02:52<16:55,  4.37it/s]

 14%|█▍        | 719/5153 [02:52<16:55,  4.37it/s]

 14%|█▍        | 720/5153 [02:53<16:55,  4.36it/s]

 14%|█▍        | 721/5153 [02:53<16:54,  4.37it/s]

 14%|█▍        | 722/5153 [02:53<16:53,  4.37it/s]

 14%|█▍        | 723/5153 [02:53<16:54,  4.37it/s]

 14%|█▍        | 724/5153 [02:54<16:56,  4.36it/s]

 14%|█▍        | 725/5153 [02:54<16:57,  4.35it/s]

 14%|█▍        | 726/5153 [02:54<16:53,  4.37it/s]

 14%|█▍        | 727/5153 [02:54<16:53,  4.37it/s]

 14%|█▍        | 728/5153 [02:54<16:52,  4.37it/s]

 14%|█▍        | 729/5153 [02:55<16:52,  4.37it/s]

 14%|█▍        | 730/5153 [02:55<16:53,  4.36it/s]

 14%|█▍        | 731/5153 [02:55<16:53,  4.36it/s]

 14%|█▍        | 732/5153 [02:55<16:51,  4.37it/s]

 14%|█▍        | 733/5153 [02:56<16:51,  4.37it/s]

 14%|█▍        | 734/5153 [02:56<16:51,  4.37it/s]

 14%|█▍        | 735/5153 [02:56<16:52,  4.36it/s]

 14%|█▍        | 736/5153 [02:56<16:54,  4.35it/s]

 14%|█▍        | 737/5153 [02:57<16:52,  4.36it/s]

 14%|█▍        | 738/5153 [02:57<16:52,  4.36it/s]

 14%|█▍        | 739/5153 [02:57<16:51,  4.36it/s]

 14%|█▍        | 740/5153 [02:57<16:50,  4.37it/s]

 14%|█▍        | 741/5153 [02:57<16:51,  4.36it/s]

 14%|█▍        | 742/5153 [02:58<16:53,  4.35it/s]

 14%|█▍        | 743/5153 [02:58<16:51,  4.36it/s]

 14%|█▍        | 744/5153 [02:58<16:50,  4.36it/s]

 14%|█▍        | 745/5153 [02:58<16:58,  4.33it/s]

 14%|█▍        | 746/5153 [02:59<16:57,  4.33it/s]

 14%|█▍        | 747/5153 [02:59<16:55,  4.34it/s]

 15%|█▍        | 748/5153 [02:59<16:51,  4.35it/s]

 15%|█▍        | 749/5153 [02:59<16:51,  4.35it/s]

 15%|█▍        | 750/5153 [03:00<16:51,  4.35it/s]

 15%|█▍        | 751/5153 [03:00<16:49,  4.36it/s]

 15%|█▍        | 752/5153 [03:00<16:49,  4.36it/s]

 15%|█▍        | 753/5153 [03:00<16:48,  4.36it/s]

 15%|█▍        | 754/5153 [03:00<16:47,  4.36it/s]

 15%|█▍        | 755/5153 [03:01<16:50,  4.35it/s]

 15%|█▍        | 756/5153 [03:01<16:48,  4.36it/s]

 15%|█▍        | 757/5153 [03:01<16:49,  4.35it/s]

 15%|█▍        | 758/5153 [03:01<16:49,  4.35it/s]

 15%|█▍        | 759/5153 [03:02<16:49,  4.35it/s]

 15%|█▍        | 760/5153 [03:02<16:49,  4.35it/s]

 15%|█▍        | 761/5153 [03:02<16:50,  4.34it/s]

 15%|█▍        | 762/5153 [03:02<16:47,  4.36it/s]

 15%|█▍        | 763/5153 [03:02<16:46,  4.36it/s]

 15%|█▍        | 764/5153 [03:03<16:56,  4.32it/s]

 15%|█▍        | 765/5153 [03:03<16:53,  4.33it/s]

 15%|█▍        | 766/5153 [03:03<16:52,  4.33it/s]

 15%|█▍        | 767/5153 [03:03<16:50,  4.34it/s]

 15%|█▍        | 768/5153 [03:04<16:52,  4.33it/s]

 15%|█▍        | 769/5153 [03:04<16:50,  4.34it/s]

 15%|█▍        | 770/5153 [03:04<16:47,  4.35it/s]

 15%|█▍        | 771/5153 [03:04<16:46,  4.35it/s]

 15%|█▍        | 772/5153 [03:05<16:50,  4.34it/s]

 15%|█▌        | 773/5153 [03:05<16:48,  4.35it/s]

 15%|█▌        | 774/5153 [03:05<16:49,  4.34it/s]

 15%|█▌        | 775/5153 [03:05<16:47,  4.35it/s]

 15%|█▌        | 776/5153 [03:05<16:45,  4.35it/s]

 15%|█▌        | 777/5153 [03:06<16:46,  4.35it/s]

 15%|█▌        | 778/5153 [03:06<16:45,  4.35it/s]

 15%|█▌        | 779/5153 [03:06<16:44,  4.35it/s]

 15%|█▌        | 780/5153 [03:06<16:43,  4.36it/s]

 15%|█▌        | 781/5153 [03:07<16:44,  4.35it/s]

 15%|█▌        | 782/5153 [03:07<16:45,  4.35it/s]

 15%|█▌        | 783/5153 [03:07<16:45,  4.35it/s]

 15%|█▌        | 784/5153 [03:07<16:45,  4.35it/s]

 15%|█▌        | 785/5153 [03:08<16:44,  4.35it/s]

 15%|█▌        | 786/5153 [03:08<16:43,  4.35it/s]

 15%|█▌        | 787/5153 [03:08<16:44,  4.35it/s]

 15%|█▌        | 788/5153 [03:08<16:44,  4.34it/s]

 15%|█▌        | 789/5153 [03:08<16:44,  4.35it/s]

 15%|█▌        | 790/5153 [03:09<16:46,  4.34it/s]

 15%|█▌        | 791/5153 [03:09<16:46,  4.33it/s]

 15%|█▌        | 792/5153 [03:09<16:44,  4.34it/s]

 15%|█▌        | 793/5153 [03:09<16:44,  4.34it/s]

 15%|█▌        | 794/5153 [03:10<16:42,  4.35it/s]

 15%|█▌        | 795/5153 [03:10<16:44,  4.34it/s]

 15%|█▌        | 796/5153 [03:10<16:43,  4.34it/s]

 15%|█▌        | 797/5153 [03:10<16:40,  4.35it/s]

 15%|█▌        | 798/5153 [03:11<16:42,  4.34it/s]

 16%|█▌        | 799/5153 [03:11<16:42,  4.34it/s]

 16%|█▌        | 800/5153 [03:11<16:41,  4.35it/s]

 16%|█▌        | 801/5153 [03:11<16:40,  4.35it/s]

 16%|█▌        | 802/5153 [03:11<16:40,  4.35it/s]

 16%|█▌        | 803/5153 [03:12<16:40,  4.35it/s]

 16%|█▌        | 804/5153 [03:12<16:41,  4.34it/s]

 16%|█▌        | 805/5153 [03:12<16:39,  4.35it/s]

 16%|█▌        | 806/5153 [03:12<16:40,  4.34it/s]

 16%|█▌        | 807/5153 [03:13<16:40,  4.34it/s]

 16%|█▌        | 808/5153 [03:13<16:40,  4.34it/s]

 16%|█▌        | 809/5153 [03:13<16:40,  4.34it/s]

 16%|█▌        | 810/5153 [03:13<16:39,  4.35it/s]

 16%|█▌        | 811/5153 [03:14<16:40,  4.34it/s]

 16%|█▌        | 812/5153 [03:14<16:41,  4.34it/s]

 16%|█▌        | 813/5153 [03:14<16:39,  4.34it/s]

 16%|█▌        | 814/5153 [03:14<16:39,  4.34it/s]

 16%|█▌        | 815/5153 [03:14<16:39,  4.34it/s]

 16%|█▌        | 816/5153 [03:15<16:39,  4.34it/s]

 16%|█▌        | 817/5153 [03:15<16:38,  4.34it/s]

 16%|█▌        | 818/5153 [03:15<16:37,  4.35it/s]

 16%|█▌        | 819/5153 [03:15<16:37,  4.35it/s]

 16%|█▌        | 820/5153 [03:16<16:39,  4.33it/s]

 16%|█▌        | 821/5153 [03:16<16:37,  4.34it/s]

 16%|█▌        | 822/5153 [03:16<16:38,  4.34it/s]

 16%|█▌        | 823/5153 [03:16<16:39,  4.33it/s]

 16%|█▌        | 824/5153 [03:17<16:46,  4.30it/s]

 16%|█▌        | 825/5153 [03:17<16:44,  4.31it/s]

 16%|█▌        | 826/5153 [03:17<16:42,  4.32it/s]

 16%|█▌        | 827/5153 [03:17<16:39,  4.33it/s]

 16%|█▌        | 828/5153 [03:17<16:39,  4.33it/s]

 16%|█▌        | 829/5153 [03:18<16:37,  4.34it/s]

 16%|█▌        | 830/5153 [03:18<16:38,  4.33it/s]

 16%|█▌        | 831/5153 [03:18<16:39,  4.32it/s]

 16%|█▌        | 832/5153 [03:18<16:40,  4.32it/s]

 16%|█▌        | 833/5153 [03:19<16:42,  4.31it/s]

 16%|█▌        | 834/5153 [03:19<16:39,  4.32it/s]

 16%|█▌        | 835/5153 [03:19<16:37,  4.33it/s]

 16%|█▌        | 836/5153 [03:19<16:36,  4.33it/s]

 16%|█▌        | 837/5153 [03:20<16:35,  4.34it/s]

 16%|█▋        | 838/5153 [03:20<16:36,  4.33it/s]

 16%|█▋        | 839/5153 [03:20<16:37,  4.32it/s]

 16%|█▋        | 840/5153 [03:20<16:38,  4.32it/s]

 16%|█▋        | 841/5153 [03:20<16:38,  4.32it/s]

 16%|█▋        | 842/5153 [03:21<16:34,  4.33it/s]

 16%|█▋        | 843/5153 [03:21<16:33,  4.34it/s]

 16%|█▋        | 844/5153 [03:21<16:33,  4.34it/s]

 16%|█▋        | 845/5153 [03:21<16:32,  4.34it/s]

 16%|█▋        | 846/5153 [03:22<16:31,  4.34it/s]

 16%|█▋        | 847/5153 [03:22<16:32,  4.34it/s]

 16%|█▋        | 848/5153 [03:22<16:30,  4.34it/s]

 16%|█▋        | 849/5153 [03:22<16:30,  4.35it/s]

 16%|█▋        | 850/5153 [03:23<16:31,  4.34it/s]

 17%|█▋        | 851/5153 [03:23<16:31,  4.34it/s]

 17%|█▋        | 852/5153 [03:23<16:32,  4.33it/s]

 17%|█▋        | 853/5153 [03:23<16:30,  4.34it/s]

 17%|█▋        | 854/5153 [03:23<16:31,  4.33it/s]

 17%|█▋        | 855/5153 [03:24<16:31,  4.33it/s]

 17%|█▋        | 856/5153 [03:24<16:32,  4.33it/s]

 17%|█▋        | 857/5153 [03:24<16:30,  4.34it/s]

 17%|█▋        | 858/5153 [03:24<16:30,  4.34it/s]

 17%|█▋        | 859/5153 [03:25<16:30,  4.34it/s]

 17%|█▋        | 860/5153 [03:25<16:30,  4.33it/s]

 17%|█▋        | 861/5153 [03:25<16:28,  4.34it/s]

 17%|█▋        | 862/5153 [03:25<16:29,  4.34it/s]

 17%|█▋        | 863/5153 [03:26<16:28,  4.34it/s]

 17%|█▋        | 864/5153 [03:26<16:28,  4.34it/s]

 17%|█▋        | 865/5153 [03:26<16:30,  4.33it/s]

 17%|█▋        | 866/5153 [03:26<16:31,  4.33it/s]

 17%|█▋        | 867/5153 [03:26<16:28,  4.34it/s]

 17%|█▋        | 868/5153 [03:27<16:28,  4.34it/s]

 17%|█▋        | 869/5153 [03:27<16:25,  4.35it/s]

 17%|█▋        | 870/5153 [03:27<16:25,  4.35it/s]

 17%|█▋        | 871/5153 [03:27<16:25,  4.35it/s]

 17%|█▋        | 872/5153 [03:28<16:25,  4.34it/s]

 17%|█▋        | 873/5153 [03:28<16:27,  4.34it/s]

 17%|█▋        | 874/5153 [03:28<16:25,  4.34it/s]

 17%|█▋        | 875/5153 [03:28<16:27,  4.33it/s]

 17%|█▋        | 876/5153 [03:29<16:29,  4.32it/s]

 17%|█▋        | 877/5153 [03:29<16:26,  4.34it/s]

 17%|█▋        | 878/5153 [03:29<16:25,  4.34it/s]

 17%|█▋        | 879/5153 [03:29<16:25,  4.34it/s]

 17%|█▋        | 880/5153 [03:29<16:24,  4.34it/s]

 17%|█▋        | 881/5153 [03:30<16:25,  4.33it/s]

 17%|█▋        | 882/5153 [03:30<16:23,  4.34it/s]

 17%|█▋        | 883/5153 [03:30<16:25,  4.33it/s]

 17%|█▋        | 884/5153 [03:30<16:23,  4.34it/s]

 17%|█▋        | 885/5153 [03:31<16:22,  4.34it/s]

 17%|█▋        | 886/5153 [03:31<16:21,  4.35it/s]

 17%|█▋        | 887/5153 [03:31<16:20,  4.35it/s]

 17%|█▋        | 888/5153 [03:31<16:18,  4.36it/s]

 17%|█▋        | 889/5153 [03:32<16:17,  4.36it/s]

 17%|█▋        | 890/5153 [03:32<16:20,  4.35it/s]

 17%|█▋        | 891/5153 [03:32<16:18,  4.35it/s]

 17%|█▋        | 892/5153 [03:32<16:20,  4.34it/s]

 17%|█▋        | 893/5153 [03:32<16:20,  4.35it/s]

 17%|█▋        | 894/5153 [03:33<16:23,  4.33it/s]

 17%|█▋        | 895/5153 [03:33<16:24,  4.33it/s]

 17%|█▋        | 896/5153 [03:33<16:22,  4.33it/s]

 17%|█▋        | 897/5153 [03:33<16:21,  4.34it/s]

 17%|█▋        | 898/5153 [03:34<16:21,  4.34it/s]

 17%|█▋        | 899/5153 [03:34<16:20,  4.34it/s]

 17%|█▋        | 900/5153 [03:34<16:20,  4.34it/s]

 17%|█▋        | 901/5153 [03:34<16:20,  4.34it/s]

 18%|█▊        | 902/5153 [03:35<16:20,  4.33it/s]

 18%|█▊        | 903/5153 [03:35<16:20,  4.34it/s]

 18%|█▊        | 904/5153 [03:35<16:20,  4.34it/s]

 18%|█▊        | 905/5153 [03:35<16:20,  4.33it/s]

 18%|█▊        | 906/5153 [03:35<16:22,  4.32it/s]

 18%|█▊        | 907/5153 [03:36<16:21,  4.33it/s]

 18%|█▊        | 908/5153 [03:36<16:21,  4.32it/s]

 18%|█▊        | 909/5153 [03:36<16:19,  4.33it/s]

 18%|█▊        | 910/5153 [03:36<16:18,  4.34it/s]

 18%|█▊        | 911/5153 [03:37<16:19,  4.33it/s]

 18%|█▊        | 912/5153 [03:37<16:17,  4.34it/s]

 18%|█▊        | 913/5153 [03:37<16:19,  4.33it/s]

 18%|█▊        | 914/5153 [03:37<16:18,  4.33it/s]

 18%|█▊        | 915/5153 [03:38<16:18,  4.33it/s]

 18%|█▊        | 916/5153 [03:38<16:21,  4.32it/s]

 18%|█▊        | 917/5153 [03:38<16:18,  4.33it/s]

 18%|█▊        | 918/5153 [03:38<16:17,  4.33it/s]

 18%|█▊        | 919/5153 [03:38<16:19,  4.32it/s]

 18%|█▊        | 920/5153 [03:39<16:17,  4.33it/s]

 18%|█▊        | 921/5153 [03:39<16:19,  4.32it/s]

 18%|█▊        | 922/5153 [03:39<16:23,  4.30it/s]

 18%|█▊        | 923/5153 [03:39<16:20,  4.31it/s]

 18%|█▊        | 924/5153 [03:40<16:19,  4.32it/s]

 18%|█▊        | 925/5153 [03:40<16:17,  4.32it/s]

 18%|█▊        | 926/5153 [03:40<16:19,  4.32it/s]

 18%|█▊        | 927/5153 [03:40<16:19,  4.31it/s]

 18%|█▊        | 928/5153 [03:41<16:17,  4.32it/s]

 18%|█▊        | 929/5153 [03:41<16:17,  4.32it/s]

 18%|█▊        | 930/5153 [03:41<16:16,  4.33it/s]

 18%|█▊        | 931/5153 [03:41<16:14,  4.33it/s]

 18%|█▊        | 932/5153 [03:41<16:12,  4.34it/s]

 18%|█▊        | 933/5153 [03:42<16:10,  4.35it/s]

 18%|█▊        | 934/5153 [03:42<16:09,  4.35it/s]

 18%|█▊        | 935/5153 [03:42<16:09,  4.35it/s]

 18%|█▊        | 936/5153 [03:42<16:08,  4.35it/s]

 18%|█▊        | 937/5153 [03:43<16:11,  4.34it/s]

 18%|█▊        | 938/5153 [03:43<16:13,  4.33it/s]

 18%|█▊        | 939/5153 [03:43<16:10,  4.34it/s]

 18%|█▊        | 940/5153 [03:43<16:10,  4.34it/s]

 18%|█▊        | 941/5153 [03:44<16:12,  4.33it/s]

 18%|█▊        | 942/5153 [03:44<16:09,  4.34it/s]

 18%|█▊        | 943/5153 [03:44<16:10,  4.34it/s]

 18%|█▊        | 944/5153 [03:44<16:11,  4.33it/s]

 18%|█▊        | 945/5153 [03:44<16:10,  4.34it/s]

 18%|█▊        | 946/5153 [03:45<16:10,  4.33it/s]

 18%|█▊        | 947/5153 [03:45<16:08,  4.34it/s]

 18%|█▊        | 948/5153 [03:45<16:10,  4.34it/s]

 18%|█▊        | 949/5153 [03:45<16:09,  4.33it/s]

 18%|█▊        | 950/5153 [03:46<16:10,  4.33it/s]

 18%|█▊        | 951/5153 [03:46<16:11,  4.32it/s]

 18%|█▊        | 952/5153 [03:46<16:10,  4.33it/s]

 18%|█▊        | 953/5153 [03:46<16:08,  4.34it/s]

 19%|█▊        | 954/5153 [03:47<16:09,  4.33it/s]

 19%|█▊        | 955/5153 [03:47<16:09,  4.33it/s]

 19%|█▊        | 956/5153 [03:47<16:07,  4.34it/s]

 19%|█▊        | 957/5153 [03:47<16:09,  4.33it/s]

 19%|█▊        | 958/5153 [03:47<16:07,  4.34it/s]

 19%|█▊        | 959/5153 [03:48<16:06,  4.34it/s]

 19%|█▊        | 960/5153 [03:48<16:05,  4.34it/s]

 19%|█▊        | 961/5153 [03:48<16:08,  4.33it/s]

 19%|█▊        | 962/5153 [03:48<16:09,  4.32it/s]

 19%|█▊        | 963/5153 [03:49<16:10,  4.32it/s]

 19%|█▊        | 964/5153 [03:49<16:07,  4.33it/s]

 19%|█▊        | 965/5153 [03:49<16:09,  4.32it/s]

 19%|█▊        | 966/5153 [03:49<16:09,  4.32it/s]

 19%|█▉        | 967/5153 [03:50<16:05,  4.33it/s]

 19%|█▉        | 968/5153 [03:50<16:03,  4.34it/s]

 19%|█▉        | 969/5153 [03:50<16:03,  4.34it/s]

 19%|█▉        | 970/5153 [03:50<16:01,  4.35it/s]

 19%|█▉        | 971/5153 [03:50<16:01,  4.35it/s]

 19%|█▉        | 972/5153 [03:51<16:01,  4.35it/s]

 19%|█▉        | 973/5153 [03:51<16:01,  4.35it/s]

 19%|█▉        | 974/5153 [03:51<16:02,  4.34it/s]

 19%|█▉        | 975/5153 [03:51<16:00,  4.35it/s]

 19%|█▉        | 976/5153 [03:52<16:00,  4.35it/s]

 19%|█▉        | 977/5153 [03:52<16:01,  4.34it/s]

 19%|█▉        | 978/5153 [03:52<16:03,  4.33it/s]

 19%|█▉        | 979/5153 [03:52<16:05,  4.32it/s]

 19%|█▉        | 980/5153 [03:53<16:06,  4.32it/s]

 19%|█▉        | 981/5153 [03:53<16:08,  4.31it/s]

 19%|█▉        | 982/5153 [03:53<16:09,  4.30it/s]

 19%|█▉        | 983/5153 [03:53<16:07,  4.31it/s]

 19%|█▉        | 984/5153 [03:53<16:08,  4.31it/s]

 19%|█▉        | 985/5153 [03:54<16:10,  4.30it/s]

 19%|█▉        | 986/5153 [03:54<16:07,  4.31it/s]

 19%|█▉        | 987/5153 [03:54<16:09,  4.30it/s]

 19%|█▉        | 988/5153 [03:54<16:06,  4.31it/s]

 19%|█▉        | 989/5153 [03:55<16:05,  4.31it/s]

 19%|█▉        | 990/5153 [03:55<16:04,  4.32it/s]

 19%|█▉        | 991/5153 [03:55<16:02,  4.32it/s]

 19%|█▉        | 992/5153 [03:55<16:03,  4.32it/s]

 19%|█▉        | 993/5153 [03:56<16:07,  4.30it/s]

 19%|█▉        | 994/5153 [03:56<16:06,  4.30it/s]

 19%|█▉        | 995/5153 [03:56<16:05,  4.31it/s]

 19%|█▉        | 996/5153 [03:56<16:02,  4.32it/s]

 19%|█▉        | 997/5153 [03:56<16:02,  4.32it/s]

 19%|█▉        | 998/5153 [03:57<16:03,  4.31it/s]

 19%|█▉        | 999/5153 [03:57<16:01,  4.32it/s]

 19%|█▉        | 1000/5153 [03:57<16:00,  4.32it/s]

 19%|█▉        | 1001/5153 [03:57<16:00,  4.32it/s]

 19%|█▉        | 1002/5153 [03:58<15:58,  4.33it/s]

 19%|█▉        | 1003/5153 [03:58<16:00,  4.32it/s]

 19%|█▉        | 1004/5153 [03:58<15:59,  4.33it/s]

 20%|█▉        | 1005/5153 [03:58<16:00,  4.32it/s]

 20%|█▉        | 1006/5153 [03:59<16:02,  4.31it/s]

 20%|█▉        | 1007/5153 [03:59<16:01,  4.31it/s]

 20%|█▉        | 1008/5153 [03:59<15:59,  4.32it/s]

 20%|█▉        | 1009/5153 [03:59<15:58,  4.32it/s]

 20%|█▉        | 1010/5153 [03:59<16:00,  4.31it/s]

 20%|█▉        | 1011/5153 [04:00<16:00,  4.31it/s]

 20%|█▉        | 1012/5153 [04:00<15:57,  4.32it/s]

 20%|█▉        | 1013/5153 [04:00<16:00,  4.31it/s]

 20%|█▉        | 1014/5153 [04:00<15:59,  4.31it/s]

 20%|█▉        | 1015/5153 [04:01<15:58,  4.32it/s]

 20%|█▉        | 1016/5153 [04:01<15:58,  4.32it/s]

 20%|█▉        | 1017/5153 [04:01<15:55,  4.33it/s]

 20%|█▉        | 1018/5153 [04:01<15:56,  4.32it/s]

 20%|█▉        | 1019/5153 [04:02<15:58,  4.31it/s]

 20%|█▉        | 1020/5153 [04:02<15:54,  4.33it/s]

 20%|█▉        | 1021/5153 [04:02<15:56,  4.32it/s]

 20%|█▉        | 1022/5153 [04:02<15:57,  4.31it/s]

 20%|█▉        | 1023/5153 [04:03<15:57,  4.31it/s]

 20%|█▉        | 1024/5153 [04:03<15:57,  4.31it/s]

 20%|█▉        | 1025/5153 [04:03<15:55,  4.32it/s]

 20%|█▉        | 1026/5153 [04:03<15:55,  4.32it/s]

 20%|█▉        | 1027/5153 [04:03<16:06,  4.27it/s]

 20%|█▉        | 1028/5153 [04:04<16:01,  4.29it/s]

 20%|█▉        | 1029/5153 [04:04<15:59,  4.30it/s]

 20%|█▉        | 1030/5153 [04:04<15:57,  4.31it/s]

 20%|██        | 1031/5153 [04:04<15:58,  4.30it/s]

 20%|██        | 1032/5153 [04:05<15:58,  4.30it/s]

 20%|██        | 1033/5153 [04:05<15:56,  4.31it/s]

 20%|██        | 1034/5153 [04:05<15:57,  4.30it/s]

 20%|██        | 1035/5153 [04:05<15:58,  4.30it/s]

 20%|██        | 1036/5153 [04:06<15:55,  4.31it/s]

 20%|██        | 1037/5153 [04:06<15:55,  4.31it/s]

 20%|██        | 1038/5153 [04:06<15:54,  4.31it/s]

 20%|██        | 1039/5153 [04:06<15:54,  4.31it/s]

 20%|██        | 1040/5153 [04:06<15:59,  4.29it/s]

 20%|██        | 1041/5153 [04:07<15:56,  4.30it/s]

 20%|██        | 1042/5153 [04:07<15:55,  4.30it/s]

 20%|██        | 1043/5153 [04:07<15:53,  4.31it/s]

 20%|██        | 1044/5153 [04:07<15:55,  4.30it/s]

 20%|██        | 1045/5153 [04:08<15:57,  4.29it/s]

 20%|██        | 1046/5153 [04:08<15:56,  4.30it/s]

 20%|██        | 1047/5153 [04:08<15:58,  4.28it/s]

 20%|██        | 1048/5153 [04:08<15:55,  4.30it/s]

 20%|██        | 1049/5153 [04:09<15:53,  4.30it/s]

 20%|██        | 1050/5153 [04:09<15:54,  4.30it/s]

 20%|██        | 1051/5153 [04:09<15:52,  4.31it/s]

 20%|██        | 1052/5153 [04:09<15:52,  4.31it/s]

 20%|██        | 1053/5153 [04:09<15:56,  4.29it/s]

 20%|██        | 1054/5153 [04:10<15:55,  4.29it/s]

 20%|██        | 1055/5153 [04:10<15:54,  4.29it/s]

 20%|██        | 1056/5153 [04:10<15:52,  4.30it/s]

 21%|██        | 1057/5153 [04:10<15:52,  4.30it/s]

 21%|██        | 1058/5153 [04:11<15:52,  4.30it/s]

 21%|██        | 1059/5153 [04:11<15:49,  4.31it/s]

 21%|██        | 1060/5153 [04:11<15:50,  4.31it/s]

 21%|██        | 1061/5153 [04:11<15:51,  4.30it/s]

 21%|██        | 1062/5153 [04:12<15:50,  4.30it/s]

 21%|██        | 1063/5153 [04:12<15:48,  4.31it/s]

 21%|██        | 1064/5153 [04:12<15:45,  4.32it/s]

 21%|██        | 1065/5153 [04:12<15:48,  4.31it/s]

 21%|██        | 1066/5153 [04:13<15:48,  4.31it/s]

 21%|██        | 1067/5153 [04:13<15:46,  4.32it/s]

 21%|██        | 1068/5153 [04:13<15:48,  4.31it/s]

 21%|██        | 1069/5153 [04:13<15:47,  4.31it/s]

 21%|██        | 1070/5153 [04:13<15:47,  4.31it/s]

 21%|██        | 1071/5153 [04:14<15:47,  4.31it/s]

 21%|██        | 1072/5153 [04:14<15:49,  4.30it/s]

 21%|██        | 1073/5153 [04:14<15:51,  4.29it/s]

 21%|██        | 1074/5153 [04:14<15:49,  4.29it/s]

 21%|██        | 1075/5153 [04:15<15:50,  4.29it/s]

 21%|██        | 1076/5153 [04:15<15:49,  4.29it/s]

 21%|██        | 1077/5153 [04:15<15:45,  4.31it/s]

 21%|██        | 1078/5153 [04:15<15:44,  4.31it/s]

 21%|██        | 1079/5153 [04:16<15:46,  4.30it/s]

 21%|██        | 1080/5153 [04:16<15:45,  4.31it/s]

 21%|██        | 1081/5153 [04:16<15:45,  4.31it/s]

 21%|██        | 1082/5153 [04:16<15:43,  4.31it/s]

 21%|██        | 1083/5153 [04:16<15:44,  4.31it/s]

 21%|██        | 1084/5153 [04:17<15:44,  4.31it/s]

 21%|██        | 1085/5153 [04:17<15:42,  4.32it/s]

 21%|██        | 1086/5153 [04:17<15:41,  4.32it/s]

 21%|██        | 1087/5153 [04:17<15:40,  4.32it/s]

 21%|██        | 1088/5153 [04:18<15:41,  4.32it/s]

 21%|██        | 1089/5153 [04:18<15:41,  4.32it/s]

 21%|██        | 1090/5153 [04:18<15:40,  4.32it/s]

 21%|██        | 1091/5153 [04:18<15:41,  4.31it/s]

 21%|██        | 1092/5153 [04:19<15:46,  4.29it/s]

 21%|██        | 1093/5153 [04:19<15:44,  4.30it/s]

 21%|██        | 1094/5153 [04:19<15:45,  4.29it/s]

 21%|██        | 1095/5153 [04:19<15:45,  4.29it/s]

 21%|██▏       | 1096/5153 [04:19<15:44,  4.30it/s]

 21%|██▏       | 1097/5153 [04:20<15:45,  4.29it/s]

 21%|██▏       | 1098/5153 [04:20<15:46,  4.29it/s]

 21%|██▏       | 1099/5153 [04:20<15:45,  4.29it/s]

 21%|██▏       | 1100/5153 [04:20<15:45,  4.29it/s]

 21%|██▏       | 1101/5153 [04:21<15:44,  4.29it/s]

 21%|██▏       | 1102/5153 [04:21<15:43,  4.29it/s]

 21%|██▏       | 1103/5153 [04:21<15:42,  4.30it/s]

 21%|██▏       | 1104/5153 [04:21<15:42,  4.30it/s]

 21%|██▏       | 1105/5153 [04:22<15:41,  4.30it/s]

 21%|██▏       | 1106/5153 [04:22<15:41,  4.30it/s]

 21%|██▏       | 1107/5153 [04:22<15:42,  4.29it/s]

 22%|██▏       | 1108/5153 [04:22<15:41,  4.30it/s]

 22%|██▏       | 1109/5153 [04:22<15:41,  4.30it/s]

 22%|██▏       | 1110/5153 [04:23<15:41,  4.29it/s]

 22%|██▏       | 1111/5153 [04:23<15:42,  4.29it/s]

 22%|██▏       | 1112/5153 [04:23<15:43,  4.28it/s]

 22%|██▏       | 1113/5153 [04:23<15:41,  4.29it/s]

 22%|██▏       | 1114/5153 [04:24<15:44,  4.28it/s]

 22%|██▏       | 1115/5153 [04:24<15:43,  4.28it/s]

 22%|██▏       | 1116/5153 [04:24<15:41,  4.29it/s]

 22%|██▏       | 1117/5153 [04:24<15:40,  4.29it/s]

 22%|██▏       | 1118/5153 [04:25<15:41,  4.29it/s]

 22%|██▏       | 1119/5153 [04:25<15:42,  4.28it/s]

 22%|██▏       | 1120/5153 [04:25<15:41,  4.28it/s]

 22%|██▏       | 1121/5153 [04:25<15:39,  4.29it/s]

 22%|██▏       | 1122/5153 [04:26<15:39,  4.29it/s]

 22%|██▏       | 1123/5153 [04:26<15:39,  4.29it/s]

 22%|██▏       | 1124/5153 [04:26<15:40,  4.28it/s]

 22%|██▏       | 1125/5153 [04:26<15:42,  4.27it/s]

 22%|██▏       | 1126/5153 [04:26<15:40,  4.28it/s]

 22%|██▏       | 1127/5153 [04:27<15:39,  4.29it/s]

 22%|██▏       | 1128/5153 [04:27<15:38,  4.29it/s]

 22%|██▏       | 1129/5153 [04:27<15:41,  4.27it/s]

 22%|██▏       | 1130/5153 [04:27<15:42,  4.27it/s]

 22%|██▏       | 1131/5153 [04:28<15:38,  4.28it/s]

 22%|██▏       | 1132/5153 [04:28<15:38,  4.28it/s]

 22%|██▏       | 1133/5153 [04:28<15:41,  4.27it/s]

 22%|██▏       | 1134/5153 [04:28<15:39,  4.28it/s]

 22%|██▏       | 1135/5153 [04:29<15:41,  4.27it/s]

 22%|██▏       | 1136/5153 [04:29<15:38,  4.28it/s]

 22%|██▏       | 1137/5153 [04:29<15:38,  4.28it/s]

 22%|██▏       | 1138/5153 [04:29<15:38,  4.28it/s]

 22%|██▏       | 1139/5153 [04:30<15:35,  4.29it/s]

 22%|██▏       | 1140/5153 [04:30<15:33,  4.30it/s]

 22%|██▏       | 1141/5153 [04:30<15:32,  4.30it/s]

 22%|██▏       | 1142/5153 [04:30<15:31,  4.31it/s]

 22%|██▏       | 1143/5153 [04:30<15:33,  4.30it/s]

 22%|██▏       | 1144/5153 [04:31<15:33,  4.29it/s]

 22%|██▏       | 1145/5153 [04:31<15:36,  4.28it/s]

 22%|██▏       | 1146/5153 [04:31<15:36,  4.28it/s]

 22%|██▏       | 1147/5153 [04:31<15:38,  4.27it/s]

 22%|██▏       | 1148/5153 [04:32<15:42,  4.25it/s]

 22%|██▏       | 1149/5153 [04:32<15:39,  4.26it/s]

 22%|██▏       | 1150/5153 [04:32<15:37,  4.27it/s]

 22%|██▏       | 1151/5153 [04:32<15:39,  4.26it/s]

 22%|██▏       | 1152/5153 [04:33<15:37,  4.27it/s]

 22%|██▏       | 1153/5153 [04:33<15:38,  4.26it/s]

 22%|██▏       | 1154/5153 [04:33<15:35,  4.27it/s]

 22%|██▏       | 1155/5153 [04:33<15:36,  4.27it/s]

 22%|██▏       | 1156/5153 [04:33<15:39,  4.26it/s]

 22%|██▏       | 1157/5153 [04:34<15:38,  4.26it/s]

 22%|██▏       | 1158/5153 [04:34<15:40,  4.25it/s]

 22%|██▏       | 1159/5153 [04:34<15:36,  4.26it/s]

 23%|██▎       | 1160/5153 [04:34<15:35,  4.27it/s]

 23%|██▎       | 1161/5153 [04:35<15:38,  4.26it/s]

 23%|██▎       | 1162/5153 [04:35<15:37,  4.26it/s]

 23%|██▎       | 1163/5153 [04:35<15:36,  4.26it/s]

 23%|██▎       | 1164/5153 [04:35<15:34,  4.27it/s]

 23%|██▎       | 1165/5153 [04:36<15:35,  4.26it/s]

 23%|██▎       | 1166/5153 [04:36<15:32,  4.27it/s]

 23%|██▎       | 1167/5153 [04:36<15:33,  4.27it/s]

 23%|██▎       | 1168/5153 [04:36<15:34,  4.26it/s]

 23%|██▎       | 1169/5153 [04:37<15:34,  4.26it/s]

 23%|██▎       | 1170/5153 [04:37<15:34,  4.26it/s]

 23%|██▎       | 1171/5153 [04:37<15:39,  4.24it/s]

 23%|██▎       | 1172/5153 [04:37<15:37,  4.24it/s]

 23%|██▎       | 1173/5153 [04:37<15:37,  4.25it/s]

 23%|██▎       | 1174/5153 [04:38<15:33,  4.26it/s]

 23%|██▎       | 1175/5153 [04:38<15:33,  4.26it/s]

 23%|██▎       | 1176/5153 [04:38<15:34,  4.26it/s]

 23%|██▎       | 1177/5153 [04:38<15:31,  4.27it/s]

 23%|██▎       | 1178/5153 [04:39<15:32,  4.26it/s]

 23%|██▎       | 1179/5153 [04:39<15:31,  4.26it/s]

 23%|██▎       | 1180/5153 [04:39<15:36,  4.24it/s]

 23%|██▎       | 1181/5153 [04:39<15:36,  4.24it/s]

 23%|██▎       | 1182/5153 [04:40<15:36,  4.24it/s]

 23%|██▎       | 1183/5153 [04:40<15:37,  4.24it/s]

 23%|██▎       | 1184/5153 [04:40<15:33,  4.25it/s]

 23%|██▎       | 1185/5153 [04:40<15:33,  4.25it/s]

 23%|██▎       | 1186/5153 [04:41<15:33,  4.25it/s]

 23%|██▎       | 1187/5153 [04:41<15:32,  4.25it/s]

 23%|██▎       | 1188/5153 [04:41<15:31,  4.26it/s]

 23%|██▎       | 1189/5153 [04:41<15:29,  4.26it/s]

 23%|██▎       | 1190/5153 [04:41<15:29,  4.26it/s]

 23%|██▎       | 1191/5153 [04:42<15:28,  4.27it/s]

 23%|██▎       | 1192/5153 [04:42<15:29,  4.26it/s]

 23%|██▎       | 1193/5153 [04:42<15:32,  4.25it/s]

 23%|██▎       | 1194/5153 [04:42<15:29,  4.26it/s]

 23%|██▎       | 1195/5153 [04:43<15:29,  4.26it/s]

 23%|██▎       | 1196/5153 [04:43<15:29,  4.26it/s]

 23%|██▎       | 1197/5153 [04:43<15:30,  4.25it/s]

 23%|██▎       | 1198/5153 [04:43<15:27,  4.26it/s]

 23%|██▎       | 1199/5153 [04:44<15:26,  4.27it/s]

 23%|██▎       | 1200/5153 [04:44<15:28,  4.26it/s]

 23%|██▎       | 1201/5153 [04:44<15:30,  4.25it/s]

 23%|██▎       | 1202/5153 [04:44<15:29,  4.25it/s]

 23%|██▎       | 1203/5153 [04:45<15:29,  4.25it/s]

 23%|██▎       | 1204/5153 [04:45<15:27,  4.26it/s]

 23%|██▎       | 1205/5153 [04:45<15:26,  4.26it/s]

 23%|██▎       | 1206/5153 [04:45<15:24,  4.27it/s]

 23%|██▎       | 1207/5153 [04:45<15:26,  4.26it/s]

 23%|██▎       | 1208/5153 [04:46<15:26,  4.26it/s]

 23%|██▎       | 1209/5153 [04:46<15:23,  4.27it/s]

 23%|██▎       | 1210/5153 [04:46<15:23,  4.27it/s]

 24%|██▎       | 1211/5153 [04:46<15:23,  4.27it/s]

 24%|██▎       | 1212/5153 [04:47<15:22,  4.27it/s]

 24%|██▎       | 1213/5153 [04:47<15:24,  4.26it/s]

 24%|██▎       | 1214/5153 [04:47<15:23,  4.26it/s]

 24%|██▎       | 1215/5153 [04:47<15:23,  4.26it/s]

 24%|██▎       | 1216/5153 [04:48<15:23,  4.27it/s]

 24%|██▎       | 1217/5153 [04:48<15:23,  4.26it/s]

 24%|██▎       | 1218/5153 [04:48<15:25,  4.25it/s]

 24%|██▎       | 1219/5153 [04:48<15:24,  4.26it/s]

 24%|██▎       | 1220/5153 [04:49<15:23,  4.26it/s]

 24%|██▎       | 1221/5153 [04:49<15:24,  4.25it/s]

 24%|██▎       | 1222/5153 [04:49<15:23,  4.25it/s]

 24%|██▎       | 1223/5153 [04:49<15:23,  4.25it/s]

 24%|██▍       | 1224/5153 [04:49<15:24,  4.25it/s]

 24%|██▍       | 1225/5153 [04:50<15:23,  4.25it/s]

 24%|██▍       | 1226/5153 [04:50<15:25,  4.24it/s]

 24%|██▍       | 1227/5153 [04:50<15:23,  4.25it/s]

 24%|██▍       | 1228/5153 [04:50<15:23,  4.25it/s]

 24%|██▍       | 1229/5153 [04:51<15:27,  4.23it/s]

 24%|██▍       | 1230/5153 [04:51<15:23,  4.25it/s]

 24%|██▍       | 1231/5153 [04:51<15:23,  4.25it/s]

 24%|██▍       | 1232/5153 [04:51<15:22,  4.25it/s]

 24%|██▍       | 1233/5153 [04:52<15:22,  4.25it/s]

 24%|██▍       | 1234/5153 [04:52<15:22,  4.25it/s]

 24%|██▍       | 1235/5153 [04:52<15:21,  4.25it/s]

 24%|██▍       | 1236/5153 [04:52<15:23,  4.24it/s]

 24%|██▍       | 1237/5153 [04:53<15:23,  4.24it/s]

 24%|██▍       | 1238/5153 [04:53<15:23,  4.24it/s]

 24%|██▍       | 1239/5153 [04:53<15:24,  4.23it/s]

 24%|██▍       | 1240/5153 [04:53<15:22,  4.24it/s]

 24%|██▍       | 1241/5153 [04:53<15:20,  4.25it/s]

 24%|██▍       | 1242/5153 [04:54<15:21,  4.24it/s]

 24%|██▍       | 1243/5153 [04:54<15:20,  4.25it/s]

 24%|██▍       | 1244/5153 [04:54<15:19,  4.25it/s]

 24%|██▍       | 1245/5153 [04:54<15:19,  4.25it/s]

 24%|██▍       | 1246/5153 [04:55<15:19,  4.25it/s]

 24%|██▍       | 1247/5153 [04:55<15:21,  4.24it/s]

 24%|██▍       | 1248/5153 [04:55<15:19,  4.25it/s]

 24%|██▍       | 1249/5153 [04:55<15:20,  4.24it/s]

 24%|██▍       | 1250/5153 [04:56<15:22,  4.23it/s]

 24%|██▍       | 1251/5153 [04:56<15:19,  4.24it/s]

logging
logging the anndata

 24%|██▍       | 1252/5153 [04:57<43:34,  1.49it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 24%|██▍       | 1253/5153 [04:58<34:55,  1.86it/s]

 24%|██▍       | 1254/5153 [04:58<28:54,  2.25it/s]

 24%|██▍       | 1255/5153 [04:58<24:40,  2.63it/s]

 24%|██▍       | 1256/5153 [04:58<21:45,  2.99it/s]

 24%|██▍       | 1257/5153 [04:59<19:40,  3.30it/s]

 24%|██▍       | 1258/5153 [04:59<18:12,  3.56it/s]

 24%|██▍       | 1259/5153 [04:59<17:11,  3.78it/s]

 24%|██▍       | 1260/5153 [04:59<16:30,  3.93it/s]

 24%|██▍       | 1261/5153 [05:00<16:01,  4.05it/s]

 24%|██▍       | 1262/5153 [05:00<15:39,  4.14it/s]

 25%|██▍       | 1263/5153 [05:00<15:23,  4.21it/s]

 25%|██▍       | 1264/5153 [05:00<15:13,  4.26it/s]

 25%|██▍       | 1265/5153 [05:00<15:04,  4.30it/s]

 25%|██▍       | 1266/5153 [05:01<15:00,  4.32it/s]

 25%|██▍       | 1267/5153 [05:01<14:57,  4.33it/s]

 25%|██▍       | 1268/5153 [05:01<14:54,  4.34it/s]

 25%|██▍       | 1269/5153 [05:01<14:52,  4.35it/s]

 25%|██▍       | 1270/5153 [05:02<14:52,  4.35it/s]

 25%|██▍       | 1271/5153 [05:02<14:53,  4.35it/s]

 25%|██▍       | 1272/5153 [05:02<14:52,  4.35it/s]

 25%|██▍       | 1273/5153 [05:02<14:49,  4.36it/s]

 25%|██▍       | 1274/5153 [05:03<14:49,  4.36it/s]

 25%|██▍       | 1275/5153 [05:03<14:50,  4.35it/s]

 25%|██▍       | 1276/5153 [05:03<14:48,  4.36it/s]

 25%|██▍       | 1277/5153 [05:03<14:48,  4.36it/s]

 25%|██▍       | 1278/5153 [05:03<14:48,  4.36it/s]

 25%|██▍       | 1279/5153 [05:04<14:46,  4.37it/s]

 25%|██▍       | 1280/5153 [05:04<14:45,  4.37it/s]

 25%|██▍       | 1281/5153 [05:04<14:55,  4.32it/s]

 25%|██▍       | 1282/5153 [05:04<14:51,  4.34it/s]

 25%|██▍       | 1283/5153 [05:05<14:53,  4.33it/s]

 25%|██▍       | 1284/5153 [05:05<14:50,  4.35it/s]

 25%|██▍       | 1285/5153 [05:05<14:50,  4.34it/s]

 25%|██▍       | 1286/5153 [05:05<14:49,  4.35it/s]

 25%|██▍       | 1287/5153 [05:06<14:46,  4.36it/s]

 25%|██▍       | 1288/5153 [05:06<14:46,  4.36it/s]

 25%|██▌       | 1289/5153 [05:06<14:47,  4.36it/s]

 25%|██▌       | 1290/5153 [05:06<14:46,  4.36it/s]

 25%|██▌       | 1291/5153 [05:06<14:45,  4.36it/s]

 25%|██▌       | 1292/5153 [05:07<14:46,  4.36it/s]

 25%|██▌       | 1293/5153 [05:07<14:46,  4.35it/s]

 25%|██▌       | 1294/5153 [05:07<14:48,  4.34it/s]

 25%|██▌       | 1295/5153 [05:07<14:44,  4.36it/s]

 25%|██▌       | 1296/5153 [05:08<14:43,  4.36it/s]

 25%|██▌       | 1297/5153 [05:08<14:44,  4.36it/s]

 25%|██▌       | 1298/5153 [05:08<14:42,  4.37it/s]

 25%|██▌       | 1299/5153 [05:08<14:42,  4.37it/s]

 25%|██▌       | 1300/5153 [05:09<14:41,  4.37it/s]

 25%|██▌       | 1301/5153 [05:09<14:47,  4.34it/s]

 25%|██▌       | 1302/5153 [05:09<14:47,  4.34it/s]

 25%|██▌       | 1303/5153 [05:09<14:45,  4.35it/s]

 25%|██▌       | 1304/5153 [05:09<14:44,  4.35it/s]

 25%|██▌       | 1305/5153 [05:10<14:43,  4.35it/s]

 25%|██▌       | 1306/5153 [05:10<14:41,  4.36it/s]

 25%|██▌       | 1307/5153 [05:10<14:40,  4.37it/s]

 25%|██▌       | 1308/5153 [05:10<14:40,  4.36it/s]

 25%|██▌       | 1309/5153 [05:11<14:40,  4.36it/s]

 25%|██▌       | 1310/5153 [05:11<14:41,  4.36it/s]

 25%|██▌       | 1311/5153 [05:11<14:40,  4.36it/s]

 25%|██▌       | 1312/5153 [05:11<14:41,  4.36it/s]

 25%|██▌       | 1313/5153 [05:11<14:42,  4.35it/s]

 25%|██▌       | 1314/5153 [05:12<14:41,  4.36it/s]

 26%|██▌       | 1315/5153 [05:12<14:44,  4.34it/s]

 26%|██▌       | 1316/5153 [05:12<14:43,  4.34it/s]

 26%|██▌       | 1317/5153 [05:12<14:41,  4.35it/s]

 26%|██▌       | 1318/5153 [05:13<14:39,  4.36it/s]

 26%|██▌       | 1319/5153 [05:13<14:40,  4.36it/s]

 26%|██▌       | 1320/5153 [05:13<14:42,  4.34it/s]

 26%|██▌       | 1321/5153 [05:13<14:40,  4.35it/s]

 26%|██▌       | 1322/5153 [05:14<14:38,  4.36it/s]

 26%|██▌       | 1323/5153 [05:14<14:37,  4.37it/s]

 26%|██▌       | 1324/5153 [05:14<14:36,  4.37it/s]

 26%|██▌       | 1325/5153 [05:14<14:36,  4.37it/s]

 26%|██▌       | 1326/5153 [05:14<14:35,  4.37it/s]

 26%|██▌       | 1327/5153 [05:15<14:38,  4.36it/s]

 26%|██▌       | 1328/5153 [05:15<14:36,  4.37it/s]

 26%|██▌       | 1329/5153 [05:15<14:35,  4.37it/s]

 26%|██▌       | 1330/5153 [05:15<14:35,  4.37it/s]

 26%|██▌       | 1331/5153 [05:16<14:35,  4.37it/s]

 26%|██▌       | 1332/5153 [05:16<14:37,  4.35it/s]

 26%|██▌       | 1333/5153 [05:16<14:36,  4.36it/s]

 26%|██▌       | 1334/5153 [05:16<14:37,  4.35it/s]

 26%|██▌       | 1335/5153 [05:17<14:37,  4.35it/s]

 26%|██▌       | 1336/5153 [05:17<14:34,  4.36it/s]

 26%|██▌       | 1337/5153 [05:17<14:36,  4.36it/s]

 26%|██▌       | 1338/5153 [05:17<14:36,  4.35it/s]

 26%|██▌       | 1339/5153 [05:17<14:35,  4.35it/s]

 26%|██▌       | 1340/5153 [05:18<14:35,  4.36it/s]

 26%|██▌       | 1341/5153 [05:18<14:35,  4.35it/s]

 26%|██▌       | 1342/5153 [05:18<14:34,  4.36it/s]

 26%|██▌       | 1343/5153 [05:18<14:33,  4.36it/s]

 26%|██▌       | 1344/5153 [05:19<14:33,  4.36it/s]

 26%|██▌       | 1345/5153 [05:19<14:32,  4.36it/s]

 26%|██▌       | 1346/5153 [05:19<14:33,  4.36it/s]

 26%|██▌       | 1347/5153 [05:19<14:32,  4.36it/s]

 26%|██▌       | 1348/5153 [05:20<14:32,  4.36it/s]

 26%|██▌       | 1349/5153 [05:20<14:31,  4.36it/s]

 26%|██▌       | 1350/5153 [05:20<14:31,  4.36it/s]

 26%|██▌       | 1351/5153 [05:20<14:32,  4.36it/s]

 26%|██▌       | 1352/5153 [05:20<14:32,  4.36it/s]

 26%|██▋       | 1353/5153 [05:21<14:33,  4.35it/s]

 26%|██▋       | 1354/5153 [05:21<14:33,  4.35it/s]

 26%|██▋       | 1355/5153 [05:21<14:32,  4.35it/s]

 26%|██▋       | 1356/5153 [05:21<14:33,  4.35it/s]

 26%|██▋       | 1357/5153 [05:22<14:41,  4.31it/s]

 26%|██▋       | 1358/5153 [05:22<14:37,  4.32it/s]

 26%|██▋       | 1359/5153 [05:22<14:35,  4.33it/s]

 26%|██▋       | 1360/5153 [05:22<14:35,  4.33it/s]

 26%|██▋       | 1361/5153 [05:23<14:33,  4.34it/s]

 26%|██▋       | 1362/5153 [05:23<14:34,  4.33it/s]

 26%|██▋       | 1363/5153 [05:23<14:31,  4.35it/s]

 26%|██▋       | 1364/5153 [05:23<14:31,  4.35it/s]

 26%|██▋       | 1365/5153 [05:23<14:34,  4.33it/s]

 27%|██▋       | 1366/5153 [05:24<14:31,  4.34it/s]

 27%|██▋       | 1367/5153 [05:24<14:32,  4.34it/s]

 27%|██▋       | 1368/5153 [05:24<14:29,  4.35it/s]

 27%|██▋       | 1369/5153 [05:24<14:29,  4.35it/s]

 27%|██▋       | 1370/5153 [05:25<14:30,  4.35it/s]

 27%|██▋       | 1371/5153 [05:25<14:28,  4.35it/s]

 27%|██▋       | 1372/5153 [05:25<14:29,  4.35it/s]

 27%|██▋       | 1373/5153 [05:25<14:28,  4.35it/s]

 27%|██▋       | 1374/5153 [05:26<14:30,  4.34it/s]

 27%|██▋       | 1375/5153 [05:26<14:31,  4.34it/s]

 27%|██▋       | 1376/5153 [05:26<14:28,  4.35it/s]

 27%|██▋       | 1377/5153 [05:26<14:28,  4.35it/s]

 27%|██▋       | 1378/5153 [05:26<14:28,  4.34it/s]

 27%|██▋       | 1379/5153 [05:27<14:27,  4.35it/s]

 27%|██▋       | 1380/5153 [05:27<14:26,  4.36it/s]

 27%|██▋       | 1381/5153 [05:27<14:26,  4.35it/s]

 27%|██▋       | 1382/5153 [05:27<14:26,  4.35it/s]

 27%|██▋       | 1383/5153 [05:28<14:26,  4.35it/s]

 27%|██▋       | 1384/5153 [05:28<14:26,  4.35it/s]

 27%|██▋       | 1385/5153 [05:28<14:26,  4.35it/s]

 27%|██▋       | 1386/5153 [05:28<14:28,  4.34it/s]

 27%|██▋       | 1387/5153 [05:28<14:27,  4.34it/s]

 27%|██▋       | 1388/5153 [05:29<14:29,  4.33it/s]

 27%|██▋       | 1389/5153 [05:29<14:28,  4.34it/s]

 27%|██▋       | 1390/5153 [05:29<14:27,  4.34it/s]

 27%|██▋       | 1391/5153 [05:29<14:28,  4.33it/s]

 27%|██▋       | 1392/5153 [05:30<14:29,  4.33it/s]

 27%|██▋       | 1393/5153 [05:30<14:27,  4.33it/s]

 27%|██▋       | 1394/5153 [05:30<14:27,  4.34it/s]

 27%|██▋       | 1395/5153 [05:30<14:24,  4.35it/s]

 27%|██▋       | 1396/5153 [05:31<14:25,  4.34it/s]

 27%|██▋       | 1397/5153 [05:31<14:25,  4.34it/s]

 27%|██▋       | 1398/5153 [05:31<14:26,  4.33it/s]

 27%|██▋       | 1399/5153 [05:31<14:27,  4.33it/s]

 27%|██▋       | 1400/5153 [05:31<14:27,  4.33it/s]

 27%|██▋       | 1401/5153 [05:32<14:27,  4.33it/s]

 27%|██▋       | 1402/5153 [05:32<14:27,  4.32it/s]

 27%|██▋       | 1403/5153 [05:32<14:26,  4.33it/s]

 27%|██▋       | 1404/5153 [05:32<14:28,  4.32it/s]

 27%|██▋       | 1405/5153 [05:33<14:25,  4.33it/s]

 27%|██▋       | 1406/5153 [05:33<14:24,  4.33it/s]

 27%|██▋       | 1407/5153 [05:33<14:24,  4.33it/s]

 27%|██▋       | 1408/5153 [05:33<14:22,  4.34it/s]

 27%|██▋       | 1409/5153 [05:34<14:21,  4.35it/s]

 27%|██▋       | 1410/5153 [05:34<14:22,  4.34it/s]

 27%|██▋       | 1411/5153 [05:34<14:20,  4.35it/s]

 27%|██▋       | 1412/5153 [05:34<14:19,  4.35it/s]

 27%|██▋       | 1413/5153 [05:34<14:19,  4.35it/s]

 27%|██▋       | 1414/5153 [05:35<14:19,  4.35it/s]

 27%|██▋       | 1415/5153 [05:35<14:19,  4.35it/s]

 27%|██▋       | 1416/5153 [05:35<14:18,  4.35it/s]

 27%|██▋       | 1417/5153 [05:35<14:19,  4.35it/s]

 28%|██▊       | 1418/5153 [05:36<14:20,  4.34it/s]

 28%|██▊       | 1419/5153 [05:36<14:19,  4.34it/s]

 28%|██▊       | 1420/5153 [05:36<14:19,  4.34it/s]

 28%|██▊       | 1421/5153 [05:36<14:20,  4.33it/s]

 28%|██▊       | 1422/5153 [05:37<14:18,  4.35it/s]

 28%|██▊       | 1423/5153 [05:37<14:17,  4.35it/s]

 28%|██▊       | 1424/5153 [05:37<14:19,  4.34it/s]

 28%|██▊       | 1425/5153 [05:37<14:20,  4.33it/s]

 28%|██▊       | 1426/5153 [05:37<14:20,  4.33it/s]

 28%|██▊       | 1427/5153 [05:38<14:19,  4.34it/s]

 28%|██▊       | 1428/5153 [05:38<14:20,  4.33it/s]

 28%|██▊       | 1429/5153 [05:38<14:20,  4.33it/s]

 28%|██▊       | 1430/5153 [05:38<14:18,  4.34it/s]

 28%|██▊       | 1431/5153 [05:39<14:18,  4.34it/s]

 28%|██▊       | 1432/5153 [05:39<14:20,  4.32it/s]

 28%|██▊       | 1433/5153 [05:39<14:20,  4.32it/s]

 28%|██▊       | 1434/5153 [05:39<14:19,  4.33it/s]

 28%|██▊       | 1435/5153 [05:40<14:17,  4.34it/s]

 28%|██▊       | 1436/5153 [05:40<14:17,  4.34it/s]

 28%|██▊       | 1437/5153 [05:40<14:18,  4.33it/s]

 28%|██▊       | 1438/5153 [05:40<14:17,  4.33it/s]

 28%|██▊       | 1439/5153 [05:40<14:19,  4.32it/s]

 28%|██▊       | 1440/5153 [05:41<14:18,  4.32it/s]

 28%|██▊       | 1441/5153 [05:41<14:17,  4.33it/s]

 28%|██▊       | 1442/5153 [05:41<14:19,  4.32it/s]

 28%|██▊       | 1443/5153 [05:41<14:17,  4.33it/s]

 28%|██▊       | 1444/5153 [05:42<14:15,  4.33it/s]

 28%|██▊       | 1445/5153 [05:42<14:14,  4.34it/s]

 28%|██▊       | 1446/5153 [05:42<14:14,  4.34it/s]

 28%|██▊       | 1447/5153 [05:42<14:15,  4.33it/s]

 28%|██▊       | 1448/5153 [05:43<14:15,  4.33it/s]

 28%|██▊       | 1449/5153 [05:43<14:14,  4.33it/s]

 28%|██▊       | 1450/5153 [05:43<14:15,  4.33it/s]

 28%|██▊       | 1451/5153 [05:43<14:13,  4.34it/s]

 28%|██▊       | 1452/5153 [05:43<14:12,  4.34it/s]

 28%|██▊       | 1453/5153 [05:44<14:15,  4.33it/s]

 28%|██▊       | 1454/5153 [05:44<14:12,  4.34it/s]

 28%|██▊       | 1455/5153 [05:44<14:15,  4.32it/s]

 28%|██▊       | 1456/5153 [05:44<14:13,  4.33it/s]

 28%|██▊       | 1457/5153 [05:45<14:14,  4.33it/s]

 28%|██▊       | 1458/5153 [05:45<14:15,  4.32it/s]

 28%|██▊       | 1459/5153 [05:45<14:13,  4.33it/s]

 28%|██▊       | 1460/5153 [05:45<14:12,  4.33it/s]

 28%|██▊       | 1461/5153 [05:46<14:14,  4.32it/s]

 28%|██▊       | 1462/5153 [05:46<14:13,  4.32it/s]

 28%|██▊       | 1463/5153 [05:46<14:13,  4.32it/s]

 28%|██▊       | 1464/5153 [05:46<14:11,  4.33it/s]

 28%|██▊       | 1465/5153 [05:46<14:12,  4.33it/s]

 28%|██▊       | 1466/5153 [05:47<14:13,  4.32it/s]

 28%|██▊       | 1467/5153 [05:47<14:11,  4.33it/s]

 28%|██▊       | 1468/5153 [05:47<14:10,  4.33it/s]

 29%|██▊       | 1469/5153 [05:47<14:11,  4.33it/s]

 29%|██▊       | 1470/5153 [05:48<14:11,  4.33it/s]

 29%|██▊       | 1471/5153 [05:48<14:11,  4.33it/s]

 29%|██▊       | 1472/5153 [05:48<14:10,  4.33it/s]

 29%|██▊       | 1473/5153 [05:48<14:09,  4.33it/s]

 29%|██▊       | 1474/5153 [05:49<14:11,  4.32it/s]

 29%|██▊       | 1475/5153 [05:49<14:09,  4.33it/s]

 29%|██▊       | 1476/5153 [05:49<14:09,  4.33it/s]

 29%|██▊       | 1477/5153 [05:49<14:13,  4.31it/s]

 29%|██▊       | 1478/5153 [05:50<14:10,  4.32it/s]

 29%|██▊       | 1479/5153 [05:50<14:09,  4.33it/s]

 29%|██▊       | 1480/5153 [05:50<14:09,  4.33it/s]

 29%|██▊       | 1481/5153 [05:50<14:09,  4.32it/s]

 29%|██▉       | 1482/5153 [05:50<14:10,  4.32it/s]

 29%|██▉       | 1483/5153 [05:51<14:09,  4.32it/s]

 29%|██▉       | 1484/5153 [05:51<14:07,  4.33it/s]

 29%|██▉       | 1485/5153 [05:51<14:17,  4.28it/s]

 29%|██▉       | 1486/5153 [05:51<14:14,  4.29it/s]

 29%|██▉       | 1487/5153 [05:52<14:11,  4.31it/s]

 29%|██▉       | 1488/5153 [05:52<14:08,  4.32it/s]

 29%|██▉       | 1489/5153 [05:52<14:07,  4.32it/s]

 29%|██▉       | 1490/5153 [05:52<14:06,  4.33it/s]

 29%|██▉       | 1491/5153 [05:53<14:04,  4.34it/s]

 29%|██▉       | 1492/5153 [05:53<14:07,  4.32it/s]

 29%|██▉       | 1493/5153 [05:53<14:07,  4.32it/s]

 29%|██▉       | 1494/5153 [05:53<14:08,  4.31it/s]

 29%|██▉       | 1495/5153 [05:53<14:08,  4.31it/s]

 29%|██▉       | 1496/5153 [05:54<14:07,  4.31it/s]

 29%|██▉       | 1497/5153 [05:54<14:05,  4.32it/s]

 29%|██▉       | 1498/5153 [05:54<14:04,  4.33it/s]

 29%|██▉       | 1499/5153 [05:54<14:03,  4.33it/s]

 29%|██▉       | 1500/5153 [05:55<14:02,  4.33it/s]

 29%|██▉       | 1501/5153 [05:55<14:02,  4.33it/s]

 29%|██▉       | 1502/5153 [05:55<14:02,  4.33it/s]

 29%|██▉       | 1503/5153 [05:55<14:03,  4.33it/s]

 29%|██▉       | 1504/5153 [05:56<14:09,  4.29it/s]

 29%|██▉       | 1505/5153 [05:56<14:06,  4.31it/s]

 29%|██▉       | 1506/5153 [05:56<14:06,  4.31it/s]

 29%|██▉       | 1507/5153 [05:56<14:04,  4.32it/s]

 29%|██▉       | 1508/5153 [05:56<14:03,  4.32it/s]

 29%|██▉       | 1509/5153 [05:57<14:03,  4.32it/s]

 29%|██▉       | 1510/5153 [05:57<14:01,  4.33it/s]

 29%|██▉       | 1511/5153 [05:57<14:01,  4.33it/s]

 29%|██▉       | 1512/5153 [05:57<14:01,  4.33it/s]

 29%|██▉       | 1513/5153 [05:58<13:59,  4.34it/s]

 29%|██▉       | 1514/5153 [05:58<13:58,  4.34it/s]

 29%|██▉       | 1515/5153 [05:58<13:57,  4.34it/s]

 29%|██▉       | 1516/5153 [05:58<13:56,  4.35it/s]

 29%|██▉       | 1517/5153 [05:59<13:55,  4.35it/s]

 29%|██▉       | 1518/5153 [05:59<13:57,  4.34it/s]

 29%|██▉       | 1519/5153 [05:59<13:57,  4.34it/s]

 29%|██▉       | 1520/5153 [05:59<13:57,  4.34it/s]

 30%|██▉       | 1521/5153 [05:59<13:58,  4.33it/s]

 30%|██▉       | 1522/5153 [06:00<13:59,  4.33it/s]

 30%|██▉       | 1523/5153 [06:00<13:59,  4.33it/s]

 30%|██▉       | 1524/5153 [06:00<13:57,  4.33it/s]

 30%|██▉       | 1525/5153 [06:00<13:58,  4.33it/s]

 30%|██▉       | 1526/5153 [06:01<13:58,  4.32it/s]

 30%|██▉       | 1527/5153 [06:01<13:56,  4.33it/s]

 30%|██▉       | 1528/5153 [06:01<13:56,  4.33it/s]

 30%|██▉       | 1529/5153 [06:01<13:57,  4.32it/s]

 30%|██▉       | 1530/5153 [06:02<13:58,  4.32it/s]

 30%|██▉       | 1531/5153 [06:02<13:57,  4.32it/s]

 30%|██▉       | 1532/5153 [06:02<13:57,  4.32it/s]

 30%|██▉       | 1533/5153 [06:02<13:56,  4.33it/s]

 30%|██▉       | 1534/5153 [06:02<13:56,  4.33it/s]

 30%|██▉       | 1535/5153 [06:03<13:56,  4.33it/s]

 30%|██▉       | 1536/5153 [06:03<13:55,  4.33it/s]

 30%|██▉       | 1537/5153 [06:03<13:55,  4.33it/s]

 30%|██▉       | 1538/5153 [06:03<13:55,  4.33it/s]

 30%|██▉       | 1539/5153 [06:04<13:53,  4.34it/s]

 30%|██▉       | 1540/5153 [06:04<13:53,  4.34it/s]

 30%|██▉       | 1541/5153 [06:04<13:52,  4.34it/s]

 30%|██▉       | 1542/5153 [06:04<13:53,  4.33it/s]

 30%|██▉       | 1543/5153 [06:05<13:55,  4.32it/s]

 30%|██▉       | 1544/5153 [06:05<13:54,  4.33it/s]

 30%|██▉       | 1545/5153 [06:05<13:53,  4.33it/s]

 30%|███       | 1546/5153 [06:05<13:52,  4.33it/s]

 30%|███       | 1547/5153 [06:05<13:52,  4.33it/s]

 30%|███       | 1548/5153 [06:06<13:53,  4.32it/s]

 30%|███       | 1549/5153 [06:06<13:51,  4.33it/s]

 30%|███       | 1550/5153 [06:06<13:51,  4.33it/s]

 30%|███       | 1551/5153 [06:06<13:54,  4.32it/s]

 30%|███       | 1552/5153 [06:07<13:52,  4.33it/s]

 30%|███       | 1553/5153 [06:07<13:52,  4.32it/s]

 30%|███       | 1554/5153 [06:07<13:53,  4.32it/s]

 30%|███       | 1555/5153 [06:07<13:51,  4.33it/s]

 30%|███       | 1556/5153 [06:08<13:49,  4.34it/s]

 30%|███       | 1557/5153 [06:08<13:47,  4.35it/s]

 30%|███       | 1558/5153 [06:08<13:47,  4.35it/s]

 30%|███       | 1559/5153 [06:08<13:52,  4.32it/s]

 30%|███       | 1560/5153 [06:08<13:50,  4.33it/s]

 30%|███       | 1561/5153 [06:09<13:48,  4.33it/s]

 30%|███       | 1562/5153 [06:09<13:47,  4.34it/s]

 30%|███       | 1563/5153 [06:09<13:46,  4.34it/s]

 30%|███       | 1564/5153 [06:09<13:47,  4.34it/s]

 30%|███       | 1565/5153 [06:10<13:46,  4.34it/s]

 30%|███       | 1566/5153 [06:10<13:46,  4.34it/s]

 30%|███       | 1567/5153 [06:10<13:45,  4.35it/s]

 30%|███       | 1568/5153 [06:10<13:44,  4.35it/s]

 30%|███       | 1569/5153 [06:11<13:44,  4.35it/s]

 30%|███       | 1570/5153 [06:11<13:44,  4.35it/s]

 30%|███       | 1571/5153 [06:11<13:45,  4.34it/s]

 31%|███       | 1572/5153 [06:11<13:45,  4.34it/s]

 31%|███       | 1573/5153 [06:11<13:45,  4.34it/s]

 31%|███       | 1574/5153 [06:12<13:45,  4.34it/s]

 31%|███       | 1575/5153 [06:12<13:46,  4.33it/s]

 31%|███       | 1576/5153 [06:12<13:48,  4.32it/s]

 31%|███       | 1577/5153 [06:12<13:48,  4.32it/s]

 31%|███       | 1578/5153 [06:13<13:47,  4.32it/s]

 31%|███       | 1579/5153 [06:13<13:47,  4.32it/s]

 31%|███       | 1580/5153 [06:13<13:46,  4.33it/s]

 31%|███       | 1581/5153 [06:13<13:45,  4.33it/s]

 31%|███       | 1582/5153 [06:14<13:45,  4.33it/s]

 31%|███       | 1583/5153 [06:14<13:46,  4.32it/s]

 31%|███       | 1584/5153 [06:14<13:45,  4.32it/s]

 31%|███       | 1585/5153 [06:14<13:45,  4.32it/s]

 31%|███       | 1586/5153 [06:14<13:45,  4.32it/s]

 31%|███       | 1587/5153 [06:15<13:47,  4.31it/s]

 31%|███       | 1588/5153 [06:15<13:48,  4.30it/s]

 31%|███       | 1589/5153 [06:15<13:45,  4.32it/s]

 31%|███       | 1590/5153 [06:15<13:45,  4.32it/s]

 31%|███       | 1591/5153 [06:16<13:46,  4.31it/s]

 31%|███       | 1592/5153 [06:16<13:45,  4.32it/s]

 31%|███       | 1593/5153 [06:16<13:46,  4.31it/s]

 31%|███       | 1594/5153 [06:16<13:43,  4.32it/s]

 31%|███       | 1595/5153 [06:17<13:41,  4.33it/s]

 31%|███       | 1596/5153 [06:17<13:43,  4.32it/s]

 31%|███       | 1597/5153 [06:17<13:40,  4.34it/s]

 31%|███       | 1598/5153 [06:17<13:39,  4.34it/s]

 31%|███       | 1599/5153 [06:17<13:41,  4.33it/s]

 31%|███       | 1600/5153 [06:18<13:41,  4.33it/s]

 31%|███       | 1601/5153 [06:18<13:40,  4.33it/s]

 31%|███       | 1602/5153 [06:18<13:39,  4.33it/s]

 31%|███       | 1603/5153 [06:18<13:40,  4.33it/s]

 31%|███       | 1604/5153 [06:19<13:42,  4.32it/s]

 31%|███       | 1605/5153 [06:19<13:41,  4.32it/s]

 31%|███       | 1606/5153 [06:19<13:42,  4.31it/s]

 31%|███       | 1607/5153 [06:19<13:42,  4.31it/s]

 31%|███       | 1608/5153 [06:20<13:41,  4.31it/s]

 31%|███       | 1609/5153 [06:20<13:41,  4.31it/s]

 31%|███       | 1610/5153 [06:20<13:40,  4.32it/s]

 31%|███▏      | 1611/5153 [06:20<13:41,  4.31it/s]

 31%|███▏      | 1612/5153 [06:20<13:41,  4.31it/s]

 31%|███▏      | 1613/5153 [06:21<13:38,  4.32it/s]

 31%|███▏      | 1614/5153 [06:21<13:40,  4.31it/s]

 31%|███▏      | 1615/5153 [06:21<13:38,  4.32it/s]

 31%|███▏      | 1616/5153 [06:21<13:40,  4.31it/s]

 31%|███▏      | 1617/5153 [06:22<13:40,  4.31it/s]

 31%|███▏      | 1618/5153 [06:22<13:38,  4.32it/s]

 31%|███▏      | 1619/5153 [06:22<13:38,  4.32it/s]

 31%|███▏      | 1620/5153 [06:22<13:41,  4.30it/s]

 31%|███▏      | 1621/5153 [06:23<13:39,  4.31it/s]

 31%|███▏      | 1622/5153 [06:23<13:38,  4.32it/s]

 31%|███▏      | 1623/5153 [06:23<13:36,  4.32it/s]

 32%|███▏      | 1624/5153 [06:23<13:38,  4.31it/s]

 32%|███▏      | 1625/5153 [06:23<13:38,  4.31it/s]

 32%|███▏      | 1626/5153 [06:24<13:36,  4.32it/s]

 32%|███▏      | 1627/5153 [06:24<13:36,  4.32it/s]

 32%|███▏      | 1628/5153 [06:24<13:35,  4.32it/s]

 32%|███▏      | 1629/5153 [06:24<13:36,  4.32it/s]

 32%|███▏      | 1630/5153 [06:25<13:37,  4.31it/s]

 32%|███▏      | 1631/5153 [06:25<13:35,  4.32it/s]

 32%|███▏      | 1632/5153 [06:25<13:36,  4.31it/s]

 32%|███▏      | 1633/5153 [06:25<13:38,  4.30it/s]

 32%|███▏      | 1634/5153 [06:26<13:36,  4.31it/s]

 32%|███▏      | 1635/5153 [06:26<13:35,  4.31it/s]

 32%|███▏      | 1636/5153 [06:26<13:33,  4.32it/s]

 32%|███▏      | 1637/5153 [06:26<13:34,  4.32it/s]

 32%|███▏      | 1638/5153 [06:27<13:35,  4.31it/s]

 32%|███▏      | 1639/5153 [06:27<13:34,  4.31it/s]

 32%|███▏      | 1640/5153 [06:27<13:34,  4.31it/s]

 32%|███▏      | 1641/5153 [06:27<13:39,  4.28it/s]

 32%|███▏      | 1642/5153 [06:27<13:39,  4.28it/s]

 32%|███▏      | 1643/5153 [06:28<13:37,  4.29it/s]

 32%|███▏      | 1644/5153 [06:28<13:35,  4.31it/s]

 32%|███▏      | 1645/5153 [06:28<13:34,  4.31it/s]

 32%|███▏      | 1646/5153 [06:28<13:33,  4.31it/s]

 32%|███▏      | 1647/5153 [06:29<13:33,  4.31it/s]

 32%|███▏      | 1648/5153 [06:29<13:34,  4.31it/s]

 32%|███▏      | 1649/5153 [06:29<13:33,  4.31it/s]

 32%|███▏      | 1650/5153 [06:29<13:32,  4.31it/s]

 32%|███▏      | 1651/5153 [06:30<13:34,  4.30it/s]

 32%|███▏      | 1652/5153 [06:30<13:32,  4.31it/s]

 32%|███▏      | 1653/5153 [06:30<13:32,  4.31it/s]

 32%|███▏      | 1654/5153 [06:30<13:31,  4.31it/s]

 32%|███▏      | 1655/5153 [06:30<13:32,  4.31it/s]

 32%|███▏      | 1656/5153 [06:31<13:31,  4.31it/s]

 32%|███▏      | 1657/5153 [06:31<13:30,  4.31it/s]

 32%|███▏      | 1658/5153 [06:31<13:30,  4.31it/s]

 32%|███▏      | 1659/5153 [06:31<13:31,  4.30it/s]

 32%|███▏      | 1660/5153 [06:32<13:32,  4.30it/s]

 32%|███▏      | 1661/5153 [06:32<13:32,  4.30it/s]

 32%|███▏      | 1662/5153 [06:32<13:31,  4.30it/s]

 32%|███▏      | 1663/5153 [06:32<13:32,  4.30it/s]

 32%|███▏      | 1664/5153 [06:33<13:32,  4.29it/s]

 32%|███▏      | 1665/5153 [06:33<13:31,  4.30it/s]

 32%|███▏      | 1666/5153 [06:33<13:32,  4.29it/s]

 32%|███▏      | 1667/5153 [06:33<13:31,  4.30it/s]

 32%|███▏      | 1668/5153 [06:33<13:30,  4.30it/s]

 32%|███▏      | 1669/5153 [06:34<13:30,  4.30it/s]

 32%|███▏      | 1670/5153 [06:34<13:29,  4.30it/s]

 32%|███▏      | 1671/5153 [06:34<13:30,  4.30it/s]

 32%|███▏      | 1672/5153 [06:34<13:29,  4.30it/s]

 32%|███▏      | 1673/5153 [06:35<13:36,  4.26it/s]

 32%|███▏      | 1674/5153 [06:35<13:35,  4.27it/s]

 33%|███▎      | 1675/5153 [06:35<13:31,  4.28it/s]

 33%|███▎      | 1676/5153 [06:35<13:31,  4.29it/s]

 33%|███▎      | 1677/5153 [06:36<13:29,  4.29it/s]

 33%|███▎      | 1678/5153 [06:36<13:27,  4.30it/s]

 33%|███▎      | 1679/5153 [06:36<13:27,  4.30it/s]

 33%|███▎      | 1680/5153 [06:36<13:26,  4.30it/s]

 33%|███▎      | 1681/5153 [06:37<13:27,  4.30it/s]

 33%|███▎      | 1682/5153 [06:37<13:27,  4.30it/s]

 33%|███▎      | 1683/5153 [06:37<13:27,  4.30it/s]

 33%|███▎      | 1684/5153 [06:37<13:26,  4.30it/s]

 33%|███▎      | 1685/5153 [06:37<13:29,  4.28it/s]

 33%|███▎      | 1686/5153 [06:38<13:27,  4.29it/s]

 33%|███▎      | 1687/5153 [06:38<13:27,  4.29it/s]

 33%|███▎      | 1688/5153 [06:38<13:25,  4.30it/s]

 33%|███▎      | 1689/5153 [06:38<13:24,  4.31it/s]

 33%|███▎      | 1690/5153 [06:39<13:25,  4.30it/s]

 33%|███▎      | 1691/5153 [06:39<13:26,  4.29it/s]

 33%|███▎      | 1692/5153 [06:39<13:25,  4.29it/s]

 33%|███▎      | 1693/5153 [06:39<13:23,  4.30it/s]

 33%|███▎      | 1694/5153 [06:40<13:24,  4.30it/s]

 33%|███▎      | 1695/5153 [06:40<13:27,  4.28it/s]

 33%|███▎      | 1696/5153 [06:40<13:26,  4.29it/s]

 33%|███▎      | 1697/5153 [06:40<13:27,  4.28it/s]

 33%|███▎      | 1698/5153 [06:40<13:26,  4.29it/s]

 33%|███▎      | 1699/5153 [06:41<13:25,  4.29it/s]

 33%|███▎      | 1700/5153 [06:41<13:26,  4.28it/s]

 33%|███▎      | 1701/5153 [06:41<13:24,  4.29it/s]

 33%|███▎      | 1702/5153 [06:41<13:24,  4.29it/s]

 33%|███▎      | 1703/5153 [06:42<13:22,  4.30it/s]

 33%|███▎      | 1704/5153 [06:42<13:22,  4.30it/s]

 33%|███▎      | 1705/5153 [06:42<13:24,  4.29it/s]

 33%|███▎      | 1706/5153 [06:42<13:23,  4.29it/s]

 33%|███▎      | 1707/5153 [06:43<13:22,  4.29it/s]

 33%|███▎      | 1708/5153 [06:43<13:21,  4.30it/s]

 33%|███▎      | 1709/5153 [06:43<13:18,  4.31it/s]

 33%|███▎      | 1710/5153 [06:43<13:18,  4.31it/s]

 33%|███▎      | 1711/5153 [06:43<13:17,  4.31it/s]

 33%|███▎      | 1712/5153 [06:44<13:18,  4.31it/s]

 33%|███▎      | 1713/5153 [06:44<13:17,  4.31it/s]

 33%|███▎      | 1714/5153 [06:44<13:16,  4.32it/s]

 33%|███▎      | 1715/5153 [06:44<13:17,  4.31it/s]

 33%|███▎      | 1716/5153 [06:45<13:17,  4.31it/s]

 33%|███▎      | 1717/5153 [06:45<13:17,  4.31it/s]

 33%|███▎      | 1718/5153 [06:45<13:18,  4.30it/s]

 33%|███▎      | 1719/5153 [06:45<13:17,  4.30it/s]

 33%|███▎      | 1720/5153 [06:46<13:20,  4.29it/s]

 33%|███▎      | 1721/5153 [06:46<13:21,  4.28it/s]

 33%|███▎      | 1722/5153 [06:46<13:20,  4.29it/s]

 33%|███▎      | 1723/5153 [06:46<13:20,  4.29it/s]

 33%|███▎      | 1724/5153 [06:47<13:19,  4.29it/s]

 33%|███▎      | 1725/5153 [06:47<13:19,  4.29it/s]

 33%|███▎      | 1726/5153 [06:47<13:20,  4.28it/s]

 34%|███▎      | 1727/5153 [06:47<13:18,  4.29it/s]

 34%|███▎      | 1728/5153 [06:47<13:18,  4.29it/s]

 34%|███▎      | 1729/5153 [06:48<13:18,  4.29it/s]

 34%|███▎      | 1730/5153 [06:48<13:19,  4.28it/s]

 34%|███▎      | 1731/5153 [06:48<13:19,  4.28it/s]

 34%|███▎      | 1732/5153 [06:48<13:18,  4.29it/s]

 34%|███▎      | 1733/5153 [06:49<13:17,  4.29it/s]

 34%|███▎      | 1734/5153 [06:49<13:15,  4.30it/s]

 34%|███▎      | 1735/5153 [06:49<13:15,  4.29it/s]

 34%|███▎      | 1736/5153 [06:49<13:17,  4.28it/s]

 34%|███▎      | 1737/5153 [06:50<13:16,  4.29it/s]

 34%|███▎      | 1738/5153 [06:50<13:17,  4.28it/s]

 34%|███▎      | 1739/5153 [06:50<13:17,  4.28it/s]

 34%|███▍      | 1740/5153 [06:50<13:17,  4.28it/s]

 34%|███▍      | 1741/5153 [06:50<13:17,  4.28it/s]

 34%|███▍      | 1742/5153 [06:51<13:15,  4.29it/s]

 34%|███▍      | 1743/5153 [06:51<13:17,  4.28it/s]

 34%|███▍      | 1744/5153 [06:51<13:19,  4.26it/s]

 34%|███▍      | 1745/5153 [06:51<13:20,  4.26it/s]

 34%|███▍      | 1746/5153 [06:52<13:19,  4.26it/s]

 34%|███▍      | 1747/5153 [06:52<13:17,  4.27it/s]

 34%|███▍      | 1748/5153 [06:52<13:15,  4.28it/s]

 34%|███▍      | 1749/5153 [06:52<13:14,  4.28it/s]

 34%|███▍      | 1750/5153 [06:53<13:13,  4.29it/s]

 34%|███▍      | 1751/5153 [06:53<13:14,  4.28it/s]

 34%|███▍      | 1752/5153 [06:53<13:13,  4.28it/s]

 34%|███▍      | 1753/5153 [06:53<13:13,  4.29it/s]

 34%|███▍      | 1754/5153 [06:54<13:13,  4.29it/s]

 34%|███▍      | 1755/5153 [06:54<13:12,  4.29it/s]

 34%|███▍      | 1756/5153 [06:54<13:13,  4.28it/s]

 34%|███▍      | 1757/5153 [06:54<13:12,  4.28it/s]

 34%|███▍      | 1758/5153 [06:54<13:12,  4.29it/s]

 34%|███▍      | 1759/5153 [06:55<13:11,  4.29it/s]

 34%|███▍      | 1760/5153 [06:55<13:10,  4.29it/s]

 34%|███▍      | 1761/5153 [06:55<13:11,  4.28it/s]

 34%|███▍      | 1762/5153 [06:55<13:14,  4.27it/s]

 34%|███▍      | 1763/5153 [06:56<13:13,  4.27it/s]

 34%|███▍      | 1764/5153 [06:56<13:12,  4.27it/s]

 34%|███▍      | 1765/5153 [06:56<13:10,  4.29it/s]

 34%|███▍      | 1766/5153 [06:56<13:08,  4.30it/s]

 34%|███▍      | 1767/5153 [06:57<13:07,  4.30it/s]

 34%|███▍      | 1768/5153 [06:57<13:07,  4.30it/s]

 34%|███▍      | 1769/5153 [06:57<13:09,  4.28it/s]

 34%|███▍      | 1770/5153 [06:57<13:10,  4.28it/s]

 34%|███▍      | 1771/5153 [06:57<13:11,  4.28it/s]

 34%|███▍      | 1772/5153 [06:58<13:11,  4.27it/s]

 34%|███▍      | 1773/5153 [06:58<13:10,  4.27it/s]

 34%|███▍      | 1774/5153 [06:58<13:12,  4.26it/s]

 34%|███▍      | 1775/5153 [06:58<13:12,  4.26it/s]

 34%|███▍      | 1776/5153 [06:59<13:13,  4.26it/s]

 34%|███▍      | 1777/5153 [06:59<13:13,  4.26it/s]

 35%|███▍      | 1778/5153 [06:59<13:09,  4.27it/s]

 35%|███▍      | 1779/5153 [06:59<13:10,  4.27it/s]

 35%|███▍      | 1780/5153 [07:00<13:10,  4.27it/s]

 35%|███▍      | 1781/5153 [07:00<13:11,  4.26it/s]

 35%|███▍      | 1782/5153 [07:00<13:13,  4.25it/s]

 35%|███▍      | 1783/5153 [07:00<13:11,  4.26it/s]

 35%|███▍      | 1784/5153 [07:01<13:10,  4.26it/s]

 35%|███▍      | 1785/5153 [07:01<13:09,  4.27it/s]

 35%|███▍      | 1786/5153 [07:01<13:11,  4.26it/s]

 35%|███▍      | 1787/5153 [07:01<13:11,  4.25it/s]

 35%|███▍      | 1788/5153 [07:01<13:10,  4.26it/s]

 35%|███▍      | 1789/5153 [07:02<13:08,  4.27it/s]

 35%|███▍      | 1790/5153 [07:02<13:08,  4.26it/s]

 35%|███▍      | 1791/5153 [07:02<13:10,  4.26it/s]

 35%|███▍      | 1792/5153 [07:02<13:10,  4.25it/s]

 35%|███▍      | 1793/5153 [07:03<13:09,  4.25it/s]

 35%|███▍      | 1794/5153 [07:03<13:09,  4.26it/s]

 35%|███▍      | 1795/5153 [07:03<13:09,  4.25it/s]

 35%|███▍      | 1796/5153 [07:03<13:06,  4.27it/s]

 35%|███▍      | 1797/5153 [07:04<13:06,  4.27it/s]

 35%|███▍      | 1798/5153 [07:04<13:07,  4.26it/s]

 35%|███▍      | 1799/5153 [07:04<13:07,  4.26it/s]

 35%|███▍      | 1800/5153 [07:04<13:06,  4.26it/s]

 35%|███▍      | 1801/5153 [07:05<13:06,  4.26it/s]

 35%|███▍      | 1802/5153 [07:05<13:07,  4.26it/s]

 35%|███▍      | 1803/5153 [07:05<13:07,  4.26it/s]

 35%|███▌      | 1804/5153 [07:05<13:07,  4.25it/s]

 35%|███▌      | 1805/5153 [07:05<13:08,  4.25it/s]

 35%|███▌      | 1806/5153 [07:06<13:07,  4.25it/s]

 35%|███▌      | 1807/5153 [07:06<13:06,  4.25it/s]

 35%|███▌      | 1808/5153 [07:06<13:06,  4.25it/s]

 35%|███▌      | 1809/5153 [07:06<13:04,  4.26it/s]

 35%|███▌      | 1810/5153 [07:07<13:03,  4.27it/s]

 35%|███▌      | 1811/5153 [07:07<13:03,  4.26it/s]

 35%|███▌      | 1812/5153 [07:07<13:05,  4.25it/s]

 35%|███▌      | 1813/5153 [07:07<13:06,  4.25it/s]

 35%|███▌      | 1814/5153 [07:08<13:05,  4.25it/s]

 35%|███▌      | 1815/5153 [07:08<13:06,  4.24it/s]

 35%|███▌      | 1816/5153 [07:08<13:09,  4.23it/s]

 35%|███▌      | 1817/5153 [07:08<13:05,  4.25it/s]

 35%|███▌      | 1818/5153 [07:09<13:06,  4.24it/s]

 35%|███▌      | 1819/5153 [07:09<13:05,  4.25it/s]

 35%|███▌      | 1820/5153 [07:09<13:06,  4.24it/s]

 35%|███▌      | 1821/5153 [07:09<13:06,  4.24it/s]

 35%|███▌      | 1822/5153 [07:09<13:03,  4.25it/s]

 35%|███▌      | 1823/5153 [07:10<13:03,  4.25it/s]

 35%|███▌      | 1824/5153 [07:10<13:07,  4.23it/s]

 35%|███▌      | 1825/5153 [07:10<13:05,  4.24it/s]

 35%|███▌      | 1826/5153 [07:10<13:04,  4.24it/s]

 35%|███▌      | 1827/5153 [07:11<13:02,  4.25it/s]

 35%|███▌      | 1828/5153 [07:11<13:00,  4.26it/s]

 35%|███▌      | 1829/5153 [07:11<13:03,  4.24it/s]

 36%|███▌      | 1830/5153 [07:11<13:02,  4.25it/s]

 36%|███▌      | 1831/5153 [07:12<13:03,  4.24it/s]

 36%|███▌      | 1832/5153 [07:12<13:00,  4.25it/s]

 36%|███▌      | 1833/5153 [07:12<13:00,  4.25it/s]

 36%|███▌      | 1834/5153 [07:12<13:00,  4.25it/s]

 36%|███▌      | 1835/5153 [07:13<12:59,  4.26it/s]

 36%|███▌      | 1836/5153 [07:13<12:59,  4.25it/s]

 36%|███▌      | 1837/5153 [07:13<13:00,  4.25it/s]

 36%|███▌      | 1838/5153 [07:13<13:00,  4.25it/s]

 36%|███▌      | 1839/5153 [07:13<13:00,  4.25it/s]

 36%|███▌      | 1840/5153 [07:14<12:59,  4.25it/s]

 36%|███▌      | 1841/5153 [07:14<12:59,  4.25it/s]

 36%|███▌      | 1842/5153 [07:14<12:56,  4.27it/s]

 36%|███▌      | 1843/5153 [07:14<12:56,  4.26it/s]

 36%|███▌      | 1844/5153 [07:15<12:56,  4.26it/s]

 36%|███▌      | 1845/5153 [07:15<12:56,  4.26it/s]

 36%|███▌      | 1846/5153 [07:15<12:57,  4.25it/s]

 36%|███▌      | 1847/5153 [07:15<12:56,  4.26it/s]

 36%|███▌      | 1848/5153 [07:16<12:57,  4.25it/s]

 36%|███▌      | 1849/5153 [07:16<12:56,  4.26it/s]

 36%|███▌      | 1850/5153 [07:16<12:56,  4.26it/s]

 36%|███▌      | 1851/5153 [07:16<12:58,  4.24it/s]

 36%|███▌      | 1852/5153 [07:17<12:56,  4.25it/s]

 36%|███▌      | 1853/5153 [07:17<12:56,  4.25it/s]

 36%|███▌      | 1854/5153 [07:17<12:56,  4.25it/s]

 36%|███▌      | 1855/5153 [07:17<12:54,  4.26it/s]

 36%|███▌      | 1856/5153 [07:17<12:54,  4.26it/s]

 36%|███▌      | 1857/5153 [07:18<12:53,  4.26it/s]

 36%|███▌      | 1858/5153 [07:18<12:54,  4.25it/s]

 36%|███▌      | 1859/5153 [07:18<12:54,  4.25it/s]

 36%|███▌      | 1860/5153 [07:18<12:54,  4.25it/s]

 36%|███▌      | 1861/5153 [07:19<12:55,  4.24it/s]

 36%|███▌      | 1862/5153 [07:19<12:54,  4.25it/s]

 36%|███▌      | 1863/5153 [07:19<12:55,  4.24it/s]

 36%|███▌      | 1864/5153 [07:19<12:55,  4.24it/s]

 36%|███▌      | 1865/5153 [07:20<12:55,  4.24it/s]

 36%|███▌      | 1866/5153 [07:20<12:54,  4.24it/s]

 36%|███▌      | 1867/5153 [07:20<12:53,  4.25it/s]

 36%|███▋      | 1868/5153 [07:20<12:52,  4.25it/s]

 36%|███▋      | 1869/5153 [07:21<12:52,  4.25it/s]

 36%|███▋      | 1870/5153 [07:21<12:52,  4.25it/s]

 36%|███▋      | 1871/5153 [07:21<12:52,  4.25it/s]

 36%|███▋      | 1872/5153 [07:21<12:51,  4.25it/s]

 36%|███▋      | 1873/5153 [07:21<12:52,  4.24it/s]

 36%|███▋      | 1874/5153 [07:22<12:51,  4.25it/s]

 36%|███▋      | 1875/5153 [07:22<12:53,  4.24it/s]

 36%|███▋      | 1876/5153 [07:22<12:52,  4.24it/s]

 36%|███▋      | 1877/5153 [07:22<12:50,  4.25it/s]

logging
logging the anndata

 36%|███▋      | 1878/5153 [07:24<33:16,  1.64it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 36%|███▋      | 1879/5153 [07:24<27:00,  2.02it/s]

 36%|███▋      | 1880/5153 [07:24<22:38,  2.41it/s]

 37%|███▋      | 1881/5153 [07:25<19:33,  2.79it/s]

 37%|███▋      | 1882/5153 [07:25<17:27,  3.12it/s]

 37%|███▋      | 1883/5153 [07:25<15:57,  3.42it/s]

 37%|███▋      | 1884/5153 [07:25<14:52,  3.66it/s]

 37%|███▋      | 1885/5153 [07:25<14:08,  3.85it/s]

 37%|███▋      | 1886/5153 [07:26<13:40,  3.98it/s]

 37%|███▋      | 1887/5153 [07:26<13:18,  4.09it/s]

 37%|███▋      | 1888/5153 [07:26<13:02,  4.17it/s]

 37%|███▋      | 1889/5153 [07:26<12:50,  4.24it/s]

 37%|███▋      | 1890/5153 [07:27<12:44,  4.27it/s]

 37%|███▋      | 1891/5153 [07:27<12:40,  4.29it/s]

 37%|███▋      | 1892/5153 [07:27<12:36,  4.31it/s]

 37%|███▋      | 1893/5153 [07:27<12:33,  4.33it/s]

 37%|███▋      | 1894/5153 [07:28<12:31,  4.34it/s]

 37%|███▋      | 1895/5153 [07:28<12:30,  4.34it/s]

 37%|███▋      | 1896/5153 [07:28<12:29,  4.34it/s]

 37%|███▋      | 1897/5153 [07:28<12:27,  4.36it/s]

 37%|███▋      | 1898/5153 [07:28<12:26,  4.36it/s]

 37%|███▋      | 1899/5153 [07:29<12:27,  4.36it/s]

 37%|███▋      | 1900/5153 [07:29<12:25,  4.36it/s]

 37%|███▋      | 1901/5153 [07:29<12:24,  4.37it/s]

 37%|███▋      | 1902/5153 [07:29<12:24,  4.36it/s]

 37%|███▋      | 1903/5153 [07:30<12:23,  4.37it/s]

 37%|███▋      | 1904/5153 [07:30<12:22,  4.37it/s]

 37%|███▋      | 1905/5153 [07:30<12:23,  4.37it/s]

 37%|███▋      | 1906/5153 [07:30<12:23,  4.37it/s]

 37%|███▋      | 1907/5153 [07:31<12:24,  4.36it/s]

 37%|███▋      | 1908/5153 [07:31<12:23,  4.36it/s]

 37%|███▋      | 1909/5153 [07:31<12:22,  4.37it/s]

 37%|███▋      | 1910/5153 [07:31<12:22,  4.37it/s]

 37%|███▋      | 1911/5153 [07:31<12:22,  4.37it/s]

 37%|███▋      | 1912/5153 [07:32<12:23,  4.36it/s]

 37%|███▋      | 1913/5153 [07:32<12:22,  4.36it/s]

 37%|███▋      | 1914/5153 [07:32<12:21,  4.37it/s]

 37%|███▋      | 1915/5153 [07:32<12:21,  4.37it/s]

 37%|███▋      | 1916/5153 [07:33<12:21,  4.36it/s]

 37%|███▋      | 1917/5153 [07:33<12:21,  4.36it/s]

 37%|███▋      | 1918/5153 [07:33<12:21,  4.36it/s]

 37%|███▋      | 1919/5153 [07:33<12:21,  4.36it/s]

 37%|███▋      | 1920/5153 [07:34<12:21,  4.36it/s]

 37%|███▋      | 1921/5153 [07:34<12:21,  4.36it/s]

 37%|███▋      | 1922/5153 [07:34<12:19,  4.37it/s]

 37%|███▋      | 1923/5153 [07:34<12:21,  4.36it/s]

 37%|███▋      | 1924/5153 [07:34<12:24,  4.34it/s]

 37%|███▋      | 1925/5153 [07:35<12:25,  4.33it/s]

 37%|███▋      | 1926/5153 [07:35<12:24,  4.33it/s]

 37%|███▋      | 1927/5153 [07:35<12:22,  4.35it/s]

 37%|███▋      | 1928/5153 [07:35<12:20,  4.36it/s]

 37%|███▋      | 1929/5153 [07:36<12:19,  4.36it/s]

 37%|███▋      | 1930/5153 [07:36<12:18,  4.37it/s]

 37%|███▋      | 1931/5153 [07:36<12:18,  4.37it/s]

 37%|███▋      | 1932/5153 [07:36<12:18,  4.36it/s]

 38%|███▊      | 1933/5153 [07:37<12:16,  4.37it/s]

 38%|███▊      | 1934/5153 [07:37<12:17,  4.37it/s]

 38%|███▊      | 1935/5153 [07:37<12:18,  4.36it/s]

 38%|███▊      | 1936/5153 [07:37<12:18,  4.36it/s]

 38%|███▊      | 1937/5153 [07:37<12:20,  4.34it/s]

 38%|███▊      | 1938/5153 [07:38<12:18,  4.35it/s]

 38%|███▊      | 1939/5153 [07:38<12:19,  4.34it/s]

 38%|███▊      | 1940/5153 [07:38<12:18,  4.35it/s]

 38%|███▊      | 1941/5153 [07:38<12:16,  4.36it/s]

 38%|███▊      | 1942/5153 [07:39<12:16,  4.36it/s]

 38%|███▊      | 1943/5153 [07:39<12:15,  4.36it/s]

 38%|███▊      | 1944/5153 [07:39<12:15,  4.36it/s]

 38%|███▊      | 1945/5153 [07:39<12:16,  4.36it/s]

 38%|███▊      | 1946/5153 [07:39<12:14,  4.36it/s]

 38%|███▊      | 1947/5153 [07:40<12:14,  4.37it/s]

 38%|███▊      | 1948/5153 [07:40<12:14,  4.37it/s]

 38%|███▊      | 1949/5153 [07:40<12:13,  4.37it/s]

 38%|███▊      | 1950/5153 [07:40<12:14,  4.36it/s]

 38%|███▊      | 1951/5153 [07:41<12:15,  4.35it/s]

 38%|███▊      | 1952/5153 [07:41<12:13,  4.36it/s]

 38%|███▊      | 1953/5153 [07:41<12:14,  4.36it/s]

 38%|███▊      | 1954/5153 [07:41<12:14,  4.36it/s]

 38%|███▊      | 1955/5153 [07:42<12:12,  4.36it/s]

 38%|███▊      | 1956/5153 [07:42<12:13,  4.36it/s]

 38%|███▊      | 1957/5153 [07:42<12:13,  4.36it/s]

 38%|███▊      | 1958/5153 [07:42<12:14,  4.35it/s]

 38%|███▊      | 1959/5153 [07:42<12:13,  4.35it/s]

 38%|███▊      | 1960/5153 [07:43<12:12,  4.36it/s]

 38%|███▊      | 1961/5153 [07:43<12:13,  4.35it/s]

 38%|███▊      | 1962/5153 [07:43<12:13,  4.35it/s]

 38%|███▊      | 1963/5153 [07:43<12:14,  4.34it/s]

 38%|███▊      | 1964/5153 [07:44<12:16,  4.33it/s]

 38%|███▊      | 1965/5153 [07:44<12:14,  4.34it/s]

 38%|███▊      | 1966/5153 [07:44<12:12,  4.35it/s]

 38%|███▊      | 1967/5153 [07:44<12:11,  4.35it/s]

 38%|███▊      | 1968/5153 [07:45<12:10,  4.36it/s]

 38%|███▊      | 1969/5153 [07:45<12:09,  4.36it/s]

 38%|███▊      | 1970/5153 [07:45<12:10,  4.36it/s]

 38%|███▊      | 1971/5153 [07:45<12:08,  4.37it/s]

 38%|███▊      | 1972/5153 [07:45<12:10,  4.35it/s]

 38%|███▊      | 1973/5153 [07:46<12:11,  4.35it/s]

 38%|███▊      | 1974/5153 [07:46<12:11,  4.35it/s]

 38%|███▊      | 1975/5153 [07:46<12:11,  4.35it/s]

 38%|███▊      | 1976/5153 [07:46<12:10,  4.35it/s]

 38%|███▊      | 1977/5153 [07:47<12:10,  4.35it/s]

 38%|███▊      | 1978/5153 [07:47<12:09,  4.35it/s]

 38%|███▊      | 1979/5153 [07:47<12:07,  4.36it/s]

 38%|███▊      | 1980/5153 [07:47<12:07,  4.36it/s]

 38%|███▊      | 1981/5153 [07:48<12:07,  4.36it/s]

 38%|███▊      | 1982/5153 [07:48<12:07,  4.36it/s]

 38%|███▊      | 1983/5153 [07:48<12:08,  4.35it/s]

 39%|███▊      | 1984/5153 [07:48<12:07,  4.35it/s]

 39%|███▊      | 1985/5153 [07:48<12:06,  4.36it/s]

 39%|███▊      | 1986/5153 [07:49<12:06,  4.36it/s]

 39%|███▊      | 1987/5153 [07:49<12:05,  4.36it/s]

 39%|███▊      | 1988/5153 [07:49<12:06,  4.36it/s]

 39%|███▊      | 1989/5153 [07:49<12:08,  4.34it/s]

 39%|███▊      | 1990/5153 [07:50<12:07,  4.35it/s]

 39%|███▊      | 1991/5153 [07:50<12:06,  4.35it/s]

 39%|███▊      | 1992/5153 [07:50<12:06,  4.35it/s]

 39%|███▊      | 1993/5153 [07:50<12:06,  4.35it/s]

 39%|███▊      | 1994/5153 [07:51<12:06,  4.35it/s]

 39%|███▊      | 1995/5153 [07:51<12:05,  4.35it/s]

 39%|███▊      | 1996/5153 [07:51<12:07,  4.34it/s]

 39%|███▉      | 1997/5153 [07:51<12:07,  4.34it/s]

 39%|███▉      | 1998/5153 [07:51<12:05,  4.35it/s]

 39%|███▉      | 1999/5153 [07:52<12:05,  4.35it/s]

 39%|███▉      | 2000/5153 [07:52<12:04,  4.35it/s]

 39%|███▉      | 2001/5153 [07:52<12:03,  4.36it/s]

 39%|███▉      | 2002/5153 [07:52<12:04,  4.35it/s]

 39%|███▉      | 2003/5153 [07:53<12:04,  4.35it/s]

 39%|███▉      | 2004/5153 [07:53<12:03,  4.36it/s]

 39%|███▉      | 2005/5153 [07:53<12:03,  4.35it/s]

 39%|███▉      | 2006/5153 [07:53<12:02,  4.36it/s]

 39%|███▉      | 2007/5153 [07:54<12:03,  4.35it/s]

 39%|███▉      | 2008/5153 [07:54<12:06,  4.33it/s]

 39%|███▉      | 2009/5153 [07:54<12:04,  4.34it/s]

 39%|███▉      | 2010/5153 [07:54<12:04,  4.34it/s]

 39%|███▉      | 2011/5153 [07:54<12:03,  4.34it/s]

 39%|███▉      | 2012/5153 [07:55<12:03,  4.34it/s]

 39%|███▉      | 2013/5153 [07:55<12:04,  4.33it/s]

 39%|███▉      | 2014/5153 [07:55<12:03,  4.34it/s]

 39%|███▉      | 2015/5153 [07:55<12:02,  4.34it/s]

 39%|███▉      | 2016/5153 [07:56<12:05,  4.33it/s]

 39%|███▉      | 2017/5153 [07:56<12:04,  4.33it/s]

 39%|███▉      | 2018/5153 [07:56<12:04,  4.33it/s]

 39%|███▉      | 2019/5153 [07:56<12:02,  4.34it/s]

 39%|███▉      | 2020/5153 [07:57<12:01,  4.34it/s]

 39%|███▉      | 2021/5153 [07:57<12:02,  4.34it/s]

 39%|███▉      | 2022/5153 [07:57<12:00,  4.34it/s]

 39%|███▉      | 2023/5153 [07:57<12:00,  4.34it/s]

 39%|███▉      | 2024/5153 [07:57<12:01,  4.34it/s]

 39%|███▉      | 2025/5153 [07:58<12:02,  4.33it/s]

 39%|███▉      | 2026/5153 [07:58<12:01,  4.33it/s]

 39%|███▉      | 2027/5153 [07:58<12:00,  4.34it/s]

 39%|███▉      | 2028/5153 [07:58<12:01,  4.33it/s]

 39%|███▉      | 2029/5153 [07:59<12:02,  4.33it/s]

 39%|███▉      | 2030/5153 [07:59<12:00,  4.34it/s]

 39%|███▉      | 2031/5153 [07:59<12:00,  4.33it/s]

 39%|███▉      | 2032/5153 [07:59<12:01,  4.33it/s]

 39%|███▉      | 2033/5153 [08:00<12:00,  4.33it/s]

 39%|███▉      | 2034/5153 [08:00<12:01,  4.33it/s]

 39%|███▉      | 2035/5153 [08:00<11:58,  4.34it/s]

 40%|███▉      | 2036/5153 [08:00<11:59,  4.33it/s]

 40%|███▉      | 2037/5153 [08:00<11:58,  4.33it/s]

 40%|███▉      | 2038/5153 [08:01<11:56,  4.35it/s]

 40%|███▉      | 2039/5153 [08:01<11:55,  4.35it/s]

 40%|███▉      | 2040/5153 [08:01<11:57,  4.34it/s]

 40%|███▉      | 2041/5153 [08:01<11:58,  4.33it/s]

 40%|███▉      | 2042/5153 [08:02<11:58,  4.33it/s]

 40%|███▉      | 2043/5153 [08:02<11:57,  4.33it/s]

 40%|███▉      | 2044/5153 [08:02<11:56,  4.34it/s]

 40%|███▉      | 2045/5153 [08:02<11:56,  4.34it/s]

 40%|███▉      | 2046/5153 [08:02<11:55,  4.34it/s]

 40%|███▉      | 2047/5153 [08:03<11:57,  4.33it/s]

 40%|███▉      | 2048/5153 [08:03<11:57,  4.33it/s]

 40%|███▉      | 2049/5153 [08:03<11:56,  4.33it/s]

 40%|███▉      | 2050/5153 [08:03<11:56,  4.33it/s]

 40%|███▉      | 2051/5153 [08:04<11:58,  4.32it/s]

 40%|███▉      | 2052/5153 [08:04<11:57,  4.32it/s]

 40%|███▉      | 2053/5153 [08:04<11:58,  4.31it/s]

 40%|███▉      | 2054/5153 [08:04<11:58,  4.31it/s]

 40%|███▉      | 2055/5153 [08:05<11:58,  4.31it/s]

 40%|███▉      | 2056/5153 [08:05<11:57,  4.32it/s]

 40%|███▉      | 2057/5153 [08:05<11:56,  4.32it/s]

 40%|███▉      | 2058/5153 [08:05<11:56,  4.32it/s]

 40%|███▉      | 2059/5153 [08:06<11:55,  4.32it/s]

 40%|███▉      | 2060/5153 [08:06<11:55,  4.33it/s]

 40%|███▉      | 2061/5153 [08:06<11:56,  4.32it/s]

 40%|████      | 2062/5153 [08:06<11:55,  4.32it/s]

 40%|████      | 2063/5153 [08:06<11:56,  4.31it/s]

 40%|████      | 2064/5153 [08:07<11:55,  4.32it/s]

 40%|████      | 2065/5153 [08:07<11:53,  4.33it/s]

 40%|████      | 2066/5153 [08:07<11:53,  4.33it/s]

 40%|████      | 2067/5153 [08:07<11:52,  4.33it/s]

 40%|████      | 2068/5153 [08:08<11:53,  4.33it/s]

 40%|████      | 2069/5153 [08:08<11:53,  4.32it/s]

 40%|████      | 2070/5153 [08:08<11:51,  4.33it/s]

 40%|████      | 2071/5153 [08:08<11:51,  4.33it/s]

 40%|████      | 2072/5153 [08:09<11:52,  4.32it/s]

 40%|████      | 2073/5153 [08:09<11:51,  4.33it/s]

 40%|████      | 2074/5153 [08:09<11:50,  4.33it/s]

 40%|████      | 2075/5153 [08:09<11:50,  4.33it/s]

 40%|████      | 2076/5153 [08:09<11:51,  4.33it/s]

 40%|████      | 2077/5153 [08:10<11:50,  4.33it/s]

 40%|████      | 2078/5153 [08:10<11:49,  4.33it/s]

 40%|████      | 2079/5153 [08:10<11:49,  4.34it/s]

 40%|████      | 2080/5153 [08:10<11:49,  4.33it/s]

 40%|████      | 2081/5153 [08:11<11:48,  4.34it/s]

 40%|████      | 2082/5153 [08:11<11:49,  4.33it/s]

 40%|████      | 2083/5153 [08:11<11:55,  4.29it/s]

 40%|████      | 2084/5153 [08:11<11:55,  4.29it/s]

 40%|████      | 2085/5153 [08:12<11:54,  4.30it/s]

 40%|████      | 2086/5153 [08:12<11:51,  4.31it/s]

 41%|████      | 2087/5153 [08:12<11:50,  4.32it/s]

 41%|████      | 2088/5153 [08:12<11:51,  4.31it/s]

 41%|████      | 2089/5153 [08:12<11:49,  4.32it/s]

 41%|████      | 2090/5153 [08:13<11:49,  4.31it/s]

 41%|████      | 2091/5153 [08:13<11:48,  4.32it/s]

 41%|████      | 2092/5153 [08:13<11:48,  4.32it/s]

 41%|████      | 2093/5153 [08:13<11:48,  4.32it/s]

 41%|████      | 2094/5153 [08:14<11:48,  4.32it/s]

 41%|████      | 2095/5153 [08:14<11:47,  4.32it/s]

 41%|████      | 2096/5153 [08:14<11:48,  4.32it/s]

 41%|████      | 2097/5153 [08:14<11:47,  4.32it/s]

 41%|████      | 2098/5153 [08:15<11:46,  4.32it/s]

 41%|████      | 2099/5153 [08:15<11:46,  4.32it/s]

 41%|████      | 2100/5153 [08:15<11:47,  4.32it/s]

 41%|████      | 2101/5153 [08:15<11:46,  4.32it/s]

 41%|████      | 2102/5153 [08:15<11:47,  4.31it/s]

 41%|████      | 2103/5153 [08:16<11:46,  4.32it/s]

 41%|████      | 2104/5153 [08:16<11:44,  4.33it/s]

 41%|████      | 2105/5153 [08:16<11:44,  4.32it/s]

 41%|████      | 2106/5153 [08:16<11:44,  4.33it/s]

 41%|████      | 2107/5153 [08:17<11:44,  4.32it/s]

 41%|████      | 2108/5153 [08:17<11:43,  4.33it/s]

 41%|████      | 2109/5153 [08:17<11:46,  4.31it/s]

 41%|████      | 2110/5153 [08:17<11:45,  4.31it/s]

 41%|████      | 2111/5153 [08:18<11:43,  4.32it/s]

 41%|████      | 2112/5153 [08:18<11:43,  4.33it/s]

 41%|████      | 2113/5153 [08:18<11:44,  4.31it/s]

 41%|████      | 2114/5153 [08:18<11:43,  4.32it/s]

 41%|████      | 2115/5153 [08:18<11:42,  4.32it/s]

 41%|████      | 2116/5153 [08:19<11:41,  4.33it/s]

 41%|████      | 2117/5153 [08:19<11:42,  4.32it/s]

 41%|████      | 2118/5153 [08:19<11:42,  4.32it/s]

 41%|████      | 2119/5153 [08:19<11:41,  4.33it/s]

 41%|████      | 2120/5153 [08:20<11:40,  4.33it/s]

 41%|████      | 2121/5153 [08:20<11:41,  4.32it/s]

 41%|████      | 2122/5153 [08:20<11:39,  4.33it/s]

 41%|████      | 2123/5153 [08:20<11:38,  4.33it/s]

 41%|████      | 2124/5153 [08:21<11:37,  4.34it/s]

 41%|████      | 2125/5153 [08:21<11:38,  4.33it/s]

 41%|████▏     | 2126/5153 [08:21<11:39,  4.33it/s]

 41%|████▏     | 2127/5153 [08:21<11:37,  4.34it/s]

 41%|████▏     | 2128/5153 [08:21<11:37,  4.34it/s]

 41%|████▏     | 2129/5153 [08:22<11:38,  4.33it/s]

 41%|████▏     | 2130/5153 [08:22<11:37,  4.34it/s]

 41%|████▏     | 2131/5153 [08:22<11:37,  4.33it/s]

 41%|████▏     | 2132/5153 [08:22<11:38,  4.33it/s]

 41%|████▏     | 2133/5153 [08:23<11:38,  4.32it/s]

 41%|████▏     | 2134/5153 [08:23<11:38,  4.32it/s]

 41%|████▏     | 2135/5153 [08:23<11:37,  4.32it/s]

 41%|████▏     | 2136/5153 [08:23<11:37,  4.33it/s]

 41%|████▏     | 2137/5153 [08:24<11:37,  4.33it/s]

 41%|████▏     | 2138/5153 [08:24<11:36,  4.33it/s]

 42%|████▏     | 2139/5153 [08:24<11:35,  4.33it/s]

 42%|████▏     | 2140/5153 [08:24<11:34,  4.34it/s]

 42%|████▏     | 2141/5153 [08:24<11:34,  4.34it/s]

 42%|████▏     | 2142/5153 [08:25<11:35,  4.33it/s]

 42%|████▏     | 2143/5153 [08:25<11:34,  4.33it/s]

 42%|████▏     | 2144/5153 [08:25<11:36,  4.32it/s]

 42%|████▏     | 2145/5153 [08:25<11:36,  4.32it/s]

 42%|████▏     | 2146/5153 [08:26<11:36,  4.32it/s]

 42%|████▏     | 2147/5153 [08:26<11:35,  4.32it/s]

 42%|████▏     | 2148/5153 [08:26<11:41,  4.29it/s]

 42%|████▏     | 2149/5153 [08:26<11:37,  4.31it/s]

 42%|████▏     | 2150/5153 [08:27<11:37,  4.30it/s]

 42%|████▏     | 2151/5153 [08:27<11:35,  4.31it/s]

 42%|████▏     | 2152/5153 [08:27<11:36,  4.31it/s]

 42%|████▏     | 2153/5153 [08:27<11:36,  4.31it/s]

 42%|████▏     | 2154/5153 [08:27<11:34,  4.32it/s]

 42%|████▏     | 2155/5153 [08:28<11:34,  4.32it/s]

 42%|████▏     | 2156/5153 [08:28<11:35,  4.31it/s]

 42%|████▏     | 2157/5153 [08:28<11:34,  4.31it/s]

 42%|████▏     | 2158/5153 [08:28<11:34,  4.31it/s]

 42%|████▏     | 2159/5153 [08:29<11:33,  4.32it/s]

 42%|████▏     | 2160/5153 [08:29<11:33,  4.31it/s]

 42%|████▏     | 2161/5153 [08:29<11:33,  4.32it/s]

 42%|████▏     | 2162/5153 [08:29<11:33,  4.32it/s]

 42%|████▏     | 2163/5153 [08:30<11:31,  4.32it/s]

 42%|████▏     | 2164/5153 [08:30<11:31,  4.32it/s]

 42%|████▏     | 2165/5153 [08:30<11:30,  4.32it/s]

 42%|████▏     | 2166/5153 [08:30<11:31,  4.32it/s]

 42%|████▏     | 2167/5153 [08:30<11:30,  4.32it/s]

 42%|████▏     | 2168/5153 [08:31<11:31,  4.32it/s]

 42%|████▏     | 2169/5153 [08:31<11:31,  4.32it/s]

 42%|████▏     | 2170/5153 [08:31<11:32,  4.31it/s]

 42%|████▏     | 2171/5153 [08:31<11:32,  4.30it/s]

 42%|████▏     | 2172/5153 [08:32<11:31,  4.31it/s]

 42%|████▏     | 2173/5153 [08:32<11:32,  4.31it/s]

 42%|████▏     | 2174/5153 [08:32<11:32,  4.30it/s]

 42%|████▏     | 2175/5153 [08:32<11:29,  4.32it/s]

 42%|████▏     | 2176/5153 [08:33<11:29,  4.32it/s]

 42%|████▏     | 2177/5153 [08:33<11:28,  4.32it/s]

 42%|████▏     | 2178/5153 [08:33<11:29,  4.32it/s]

 42%|████▏     | 2179/5153 [08:33<11:30,  4.31it/s]

 42%|████▏     | 2180/5153 [08:34<11:28,  4.32it/s]

 42%|████▏     | 2181/5153 [08:34<11:27,  4.32it/s]

 42%|████▏     | 2182/5153 [08:34<11:30,  4.30it/s]

 42%|████▏     | 2183/5153 [08:34<11:27,  4.32it/s]

 42%|████▏     | 2184/5153 [08:34<11:26,  4.32it/s]

 42%|████▏     | 2185/5153 [08:35<11:25,  4.33it/s]

 42%|████▏     | 2186/5153 [08:35<11:24,  4.33it/s]

 42%|████▏     | 2187/5153 [08:35<11:23,  4.34it/s]

 42%|████▏     | 2188/5153 [08:35<11:22,  4.34it/s]

 42%|████▏     | 2189/5153 [08:36<11:23,  4.34it/s]

 42%|████▏     | 2190/5153 [08:36<11:22,  4.34it/s]

 43%|████▎     | 2191/5153 [08:36<11:23,  4.34it/s]

 43%|████▎     | 2192/5153 [08:36<11:24,  4.33it/s]

 43%|████▎     | 2193/5153 [08:37<11:23,  4.33it/s]

 43%|████▎     | 2194/5153 [08:37<11:21,  4.34it/s]

 43%|████▎     | 2195/5153 [08:37<11:20,  4.35it/s]

 43%|████▎     | 2196/5153 [08:37<11:20,  4.35it/s]

 43%|████▎     | 2197/5153 [08:37<11:20,  4.35it/s]

 43%|████▎     | 2198/5153 [08:38<11:21,  4.34it/s]

 43%|████▎     | 2199/5153 [08:38<11:21,  4.34it/s]

 43%|████▎     | 2200/5153 [08:38<11:22,  4.33it/s]

 43%|████▎     | 2201/5153 [08:38<11:22,  4.33it/s]

 43%|████▎     | 2202/5153 [08:39<11:21,  4.33it/s]

 43%|████▎     | 2203/5153 [08:39<11:24,  4.31it/s]

 43%|████▎     | 2204/5153 [08:39<11:21,  4.32it/s]

 43%|████▎     | 2205/5153 [08:39<11:22,  4.32it/s]

 43%|████▎     | 2206/5153 [08:40<11:24,  4.31it/s]

 43%|████▎     | 2207/5153 [08:40<11:22,  4.32it/s]

 43%|████▎     | 2208/5153 [08:40<11:21,  4.32it/s]

 43%|████▎     | 2209/5153 [08:40<11:20,  4.33it/s]

 43%|████▎     | 2210/5153 [08:40<11:20,  4.32it/s]

 43%|████▎     | 2211/5153 [08:41<11:19,  4.33it/s]

 43%|████▎     | 2212/5153 [08:41<11:18,  4.33it/s]

 43%|████▎     | 2213/5153 [08:41<11:20,  4.32it/s]

 43%|████▎     | 2214/5153 [08:41<11:20,  4.32it/s]

 43%|████▎     | 2215/5153 [08:42<11:21,  4.31it/s]

 43%|████▎     | 2216/5153 [08:42<11:22,  4.30it/s]

 43%|████▎     | 2217/5153 [08:42<11:20,  4.31it/s]

 43%|████▎     | 2218/5153 [08:42<11:19,  4.32it/s]

 43%|████▎     | 2219/5153 [08:43<11:19,  4.32it/s]

 43%|████▎     | 2220/5153 [08:43<11:18,  4.32it/s]

 43%|████▎     | 2221/5153 [08:43<11:20,  4.31it/s]

 43%|████▎     | 2222/5153 [08:43<11:19,  4.31it/s]

 43%|████▎     | 2223/5153 [08:43<11:17,  4.32it/s]

 43%|████▎     | 2224/5153 [08:44<11:16,  4.33it/s]

 43%|████▎     | 2225/5153 [08:44<11:15,  4.34it/s]

 43%|████▎     | 2226/5153 [08:44<11:14,  4.34it/s]

 43%|████▎     | 2227/5153 [08:44<11:15,  4.33it/s]

 43%|████▎     | 2228/5153 [08:45<11:15,  4.33it/s]

 43%|████▎     | 2229/5153 [08:45<11:15,  4.33it/s]

 43%|████▎     | 2230/5153 [08:45<11:16,  4.32it/s]

 43%|████▎     | 2231/5153 [08:45<11:17,  4.31it/s]

 43%|████▎     | 2232/5153 [08:46<11:19,  4.30it/s]

 43%|████▎     | 2233/5153 [08:46<11:17,  4.31it/s]

 43%|████▎     | 2234/5153 [08:46<11:18,  4.30it/s]

 43%|████▎     | 2235/5153 [08:46<11:17,  4.31it/s]

 43%|████▎     | 2236/5153 [08:46<11:17,  4.31it/s]

 43%|████▎     | 2237/5153 [08:47<11:18,  4.30it/s]

 43%|████▎     | 2238/5153 [08:47<11:17,  4.30it/s]

 43%|████▎     | 2239/5153 [08:47<11:16,  4.31it/s]

 43%|████▎     | 2240/5153 [08:47<11:15,  4.31it/s]

 43%|████▎     | 2241/5153 [08:48<11:16,  4.30it/s]

 44%|████▎     | 2242/5153 [08:48<11:16,  4.30it/s]

 44%|████▎     | 2243/5153 [08:48<11:15,  4.31it/s]

 44%|████▎     | 2244/5153 [08:48<11:14,  4.31it/s]

 44%|████▎     | 2245/5153 [08:49<11:14,  4.31it/s]

 44%|████▎     | 2246/5153 [08:49<11:13,  4.32it/s]

 44%|████▎     | 2247/5153 [08:49<11:14,  4.31it/s]

 44%|████▎     | 2248/5153 [08:49<11:13,  4.31it/s]

 44%|████▎     | 2249/5153 [08:49<11:13,  4.31it/s]

 44%|████▎     | 2250/5153 [08:50<11:15,  4.30it/s]

 44%|████▎     | 2251/5153 [08:50<11:14,  4.30it/s]

 44%|████▎     | 2252/5153 [08:50<11:15,  4.30it/s]

 44%|████▎     | 2253/5153 [08:50<11:15,  4.29it/s]

 44%|████▎     | 2254/5153 [08:51<11:14,  4.30it/s]

 44%|████▍     | 2255/5153 [08:51<11:14,  4.30it/s]

 44%|████▍     | 2256/5153 [08:51<11:13,  4.30it/s]

 44%|████▍     | 2257/5153 [08:51<11:13,  4.30it/s]

 44%|████▍     | 2258/5153 [08:52<11:12,  4.30it/s]

 44%|████▍     | 2259/5153 [08:52<11:11,  4.31it/s]

 44%|████▍     | 2260/5153 [08:52<11:10,  4.31it/s]

 44%|████▍     | 2261/5153 [08:52<11:10,  4.31it/s]

 44%|████▍     | 2262/5153 [08:53<11:10,  4.31it/s]

 44%|████▍     | 2263/5153 [08:53<11:11,  4.30it/s]

 44%|████▍     | 2264/5153 [08:53<11:10,  4.31it/s]

 44%|████▍     | 2265/5153 [08:53<11:10,  4.30it/s]

 44%|████▍     | 2266/5153 [08:53<11:09,  4.31it/s]

 44%|████▍     | 2267/5153 [08:54<11:08,  4.32it/s]

 44%|████▍     | 2268/5153 [08:54<11:08,  4.32it/s]

 44%|████▍     | 2269/5153 [08:54<11:08,  4.32it/s]

 44%|████▍     | 2270/5153 [08:54<11:09,  4.31it/s]

 44%|████▍     | 2271/5153 [08:55<11:10,  4.30it/s]

 44%|████▍     | 2272/5153 [08:55<11:08,  4.31it/s]

 44%|████▍     | 2273/5153 [08:55<11:07,  4.31it/s]

 44%|████▍     | 2274/5153 [08:55<11:08,  4.31it/s]

 44%|████▍     | 2275/5153 [08:56<11:07,  4.31it/s]

 44%|████▍     | 2276/5153 [08:56<11:07,  4.31it/s]

 44%|████▍     | 2277/5153 [08:56<11:07,  4.31it/s]

 44%|████▍     | 2278/5153 [08:56<11:07,  4.31it/s]

 44%|████▍     | 2279/5153 [08:56<11:08,  4.30it/s]

 44%|████▍     | 2280/5153 [08:57<11:07,  4.30it/s]

 44%|████▍     | 2281/5153 [08:57<11:07,  4.30it/s]

 44%|████▍     | 2282/5153 [08:57<11:06,  4.31it/s]

 44%|████▍     | 2283/5153 [08:57<11:07,  4.30it/s]

 44%|████▍     | 2284/5153 [08:58<11:07,  4.30it/s]

 44%|████▍     | 2285/5153 [08:58<11:06,  4.30it/s]

 44%|████▍     | 2286/5153 [08:58<11:06,  4.30it/s]

 44%|████▍     | 2287/5153 [08:58<11:07,  4.29it/s]

 44%|████▍     | 2288/5153 [08:59<11:07,  4.29it/s]

 44%|████▍     | 2289/5153 [08:59<11:06,  4.30it/s]

 44%|████▍     | 2290/5153 [08:59<11:05,  4.30it/s]

 44%|████▍     | 2291/5153 [08:59<11:06,  4.30it/s]

 44%|████▍     | 2292/5153 [08:59<11:07,  4.29it/s]

 44%|████▍     | 2293/5153 [09:00<11:07,  4.28it/s]

 45%|████▍     | 2294/5153 [09:00<11:07,  4.28it/s]

 45%|████▍     | 2295/5153 [09:00<11:05,  4.29it/s]

 45%|████▍     | 2296/5153 [09:00<11:06,  4.29it/s]

 45%|████▍     | 2297/5153 [09:01<11:05,  4.29it/s]

 45%|████▍     | 2298/5153 [09:01<11:03,  4.30it/s]

 45%|████▍     | 2299/5153 [09:01<11:03,  4.30it/s]

 45%|████▍     | 2300/5153 [09:01<11:03,  4.30it/s]

 45%|████▍     | 2301/5153 [09:02<11:03,  4.30it/s]

 45%|████▍     | 2302/5153 [09:02<11:04,  4.29it/s]

 45%|████▍     | 2303/5153 [09:02<11:03,  4.30it/s]

 45%|████▍     | 2304/5153 [09:02<11:03,  4.29it/s]

 45%|████▍     | 2305/5153 [09:03<11:06,  4.28it/s]

 45%|████▍     | 2306/5153 [09:03<11:04,  4.29it/s]

 45%|████▍     | 2307/5153 [09:03<11:04,  4.29it/s]

 45%|████▍     | 2308/5153 [09:03<11:02,  4.29it/s]

 45%|████▍     | 2309/5153 [09:03<11:02,  4.29it/s]

 45%|████▍     | 2310/5153 [09:04<11:03,  4.29it/s]

 45%|████▍     | 2311/5153 [09:04<11:01,  4.29it/s]

 45%|████▍     | 2312/5153 [09:04<11:02,  4.29it/s]

 45%|████▍     | 2313/5153 [09:04<11:01,  4.29it/s]

 45%|████▍     | 2314/5153 [09:05<11:00,  4.30it/s]

 45%|████▍     | 2315/5153 [09:05<11:01,  4.29it/s]

 45%|████▍     | 2316/5153 [09:05<11:01,  4.29it/s]

 45%|████▍     | 2317/5153 [09:05<11:01,  4.28it/s]

 45%|████▍     | 2318/5153 [09:06<11:00,  4.29it/s]

 45%|████▌     | 2319/5153 [09:06<11:00,  4.29it/s]

 45%|████▌     | 2320/5153 [09:06<11:00,  4.29it/s]

 45%|████▌     | 2321/5153 [09:06<10:59,  4.30it/s]

 45%|████▌     | 2322/5153 [09:06<10:59,  4.29it/s]

 45%|████▌     | 2323/5153 [09:07<11:01,  4.28it/s]

 45%|████▌     | 2324/5153 [09:07<11:00,  4.28it/s]

 45%|████▌     | 2325/5153 [09:07<11:01,  4.27it/s]

 45%|████▌     | 2326/5153 [09:07<11:00,  4.28it/s]

 45%|████▌     | 2327/5153 [09:08<11:01,  4.27it/s]

 45%|████▌     | 2328/5153 [09:08<11:03,  4.25it/s]

 45%|████▌     | 2329/5153 [09:08<10:59,  4.28it/s]

 45%|████▌     | 2330/5153 [09:08<10:57,  4.29it/s]

 45%|████▌     | 2331/5153 [09:09<10:56,  4.30it/s]

 45%|████▌     | 2332/5153 [09:09<10:56,  4.30it/s]

 45%|████▌     | 2333/5153 [09:09<11:02,  4.26it/s]

 45%|████▌     | 2334/5153 [09:09<11:00,  4.27it/s]

 45%|████▌     | 2335/5153 [09:10<10:59,  4.27it/s]

 45%|████▌     | 2336/5153 [09:10<10:57,  4.28it/s]

 45%|████▌     | 2337/5153 [09:10<10:55,  4.29it/s]

 45%|████▌     | 2338/5153 [09:10<10:54,  4.30it/s]

 45%|████▌     | 2339/5153 [09:10<10:52,  4.31it/s]

 45%|████▌     | 2340/5153 [09:11<10:52,  4.31it/s]

 45%|████▌     | 2341/5153 [09:11<10:52,  4.31it/s]

 45%|████▌     | 2342/5153 [09:11<10:53,  4.30it/s]

 45%|████▌     | 2343/5153 [09:11<10:53,  4.30it/s]

 45%|████▌     | 2344/5153 [09:12<10:52,  4.31it/s]

 46%|████▌     | 2345/5153 [09:12<10:52,  4.30it/s]

 46%|████▌     | 2346/5153 [09:12<10:54,  4.29it/s]

 46%|████▌     | 2347/5153 [09:12<10:55,  4.28it/s]

 46%|████▌     | 2348/5153 [09:13<10:57,  4.26it/s]

 46%|████▌     | 2349/5153 [09:13<10:55,  4.27it/s]

 46%|████▌     | 2350/5153 [09:13<10:56,  4.27it/s]

 46%|████▌     | 2351/5153 [09:13<10:57,  4.26it/s]

 46%|████▌     | 2352/5153 [09:13<10:55,  4.27it/s]

 46%|████▌     | 2353/5153 [09:14<10:54,  4.28it/s]

 46%|████▌     | 2354/5153 [09:14<10:53,  4.28it/s]

 46%|████▌     | 2355/5153 [09:14<10:54,  4.28it/s]

 46%|████▌     | 2356/5153 [09:14<10:55,  4.27it/s]

 46%|████▌     | 2357/5153 [09:15<10:53,  4.28it/s]

 46%|████▌     | 2358/5153 [09:15<10:54,  4.27it/s]

 46%|████▌     | 2359/5153 [09:15<10:55,  4.26it/s]

 46%|████▌     | 2360/5153 [09:15<10:54,  4.27it/s]

 46%|████▌     | 2361/5153 [09:16<10:53,  4.27it/s]

 46%|████▌     | 2362/5153 [09:16<10:52,  4.28it/s]

 46%|████▌     | 2363/5153 [09:16<10:52,  4.28it/s]

 46%|████▌     | 2364/5153 [09:16<10:53,  4.27it/s]

 46%|████▌     | 2365/5153 [09:17<10:52,  4.27it/s]

 46%|████▌     | 2366/5153 [09:17<10:51,  4.28it/s]

 46%|████▌     | 2367/5153 [09:17<10:50,  4.28it/s]

 46%|████▌     | 2368/5153 [09:17<10:51,  4.27it/s]

 46%|████▌     | 2369/5153 [09:17<10:51,  4.27it/s]

 46%|████▌     | 2370/5153 [09:18<10:50,  4.28it/s]

 46%|████▌     | 2371/5153 [09:18<10:49,  4.28it/s]

 46%|████▌     | 2372/5153 [09:18<10:51,  4.27it/s]

 46%|████▌     | 2373/5153 [09:18<10:49,  4.28it/s]

 46%|████▌     | 2374/5153 [09:19<10:50,  4.27it/s]

 46%|████▌     | 2375/5153 [09:19<10:48,  4.28it/s]

 46%|████▌     | 2376/5153 [09:19<10:49,  4.27it/s]

 46%|████▌     | 2377/5153 [09:19<10:51,  4.26it/s]

 46%|████▌     | 2378/5153 [09:20<10:49,  4.27it/s]

 46%|████▌     | 2379/5153 [09:20<10:49,  4.27it/s]

 46%|████▌     | 2380/5153 [09:20<10:48,  4.27it/s]

 46%|████▌     | 2381/5153 [09:20<10:48,  4.28it/s]

 46%|████▌     | 2382/5153 [09:20<10:47,  4.28it/s]

 46%|████▌     | 2383/5153 [09:21<10:46,  4.28it/s]

 46%|████▋     | 2384/5153 [09:21<10:47,  4.28it/s]

 46%|████▋     | 2385/5153 [09:21<10:48,  4.27it/s]

 46%|████▋     | 2386/5153 [09:21<10:46,  4.28it/s]

 46%|████▋     | 2387/5153 [09:22<10:46,  4.28it/s]

 46%|████▋     | 2388/5153 [09:22<10:45,  4.28it/s]

 46%|████▋     | 2389/5153 [09:22<10:45,  4.28it/s]

 46%|████▋     | 2390/5153 [09:22<10:46,  4.27it/s]

 46%|████▋     | 2391/5153 [09:23<10:45,  4.28it/s]

 46%|████▋     | 2392/5153 [09:23<10:43,  4.29it/s]

 46%|████▋     | 2393/5153 [09:23<10:42,  4.30it/s]

 46%|████▋     | 2394/5153 [09:23<10:41,  4.30it/s]

 46%|████▋     | 2395/5153 [09:24<10:44,  4.28it/s]

 46%|████▋     | 2396/5153 [09:24<10:44,  4.28it/s]

 47%|████▋     | 2397/5153 [09:24<10:43,  4.29it/s]

 47%|████▋     | 2398/5153 [09:24<10:43,  4.28it/s]

 47%|████▋     | 2399/5153 [09:24<10:43,  4.28it/s]

 47%|████▋     | 2400/5153 [09:25<10:46,  4.26it/s]

 47%|████▋     | 2401/5153 [09:25<10:46,  4.26it/s]

 47%|████▋     | 2402/5153 [09:25<10:45,  4.26it/s]

 47%|████▋     | 2403/5153 [09:25<10:46,  4.25it/s]

 47%|████▋     | 2404/5153 [09:26<10:45,  4.26it/s]

 47%|████▋     | 2405/5153 [09:26<10:45,  4.26it/s]

 47%|████▋     | 2406/5153 [09:26<10:45,  4.25it/s]

 47%|████▋     | 2407/5153 [09:26<10:44,  4.26it/s]

 47%|████▋     | 2408/5153 [09:27<10:45,  4.26it/s]

 47%|████▋     | 2409/5153 [09:27<10:44,  4.26it/s]

 47%|████▋     | 2410/5153 [09:27<10:45,  4.25it/s]

 47%|████▋     | 2411/5153 [09:27<10:45,  4.25it/s]

 47%|████▋     | 2412/5153 [09:28<10:44,  4.25it/s]

 47%|████▋     | 2413/5153 [09:28<10:45,  4.25it/s]

 47%|████▋     | 2414/5153 [09:28<10:44,  4.25it/s]

 47%|████▋     | 2415/5153 [09:28<10:42,  4.26it/s]

 47%|████▋     | 2416/5153 [09:28<10:42,  4.26it/s]

 47%|████▋     | 2417/5153 [09:29<10:41,  4.26it/s]

 47%|████▋     | 2418/5153 [09:29<10:42,  4.26it/s]

 47%|████▋     | 2419/5153 [09:29<10:42,  4.25it/s]

 47%|████▋     | 2420/5153 [09:29<10:42,  4.25it/s]

 47%|████▋     | 2421/5153 [09:30<10:44,  4.24it/s]

 47%|████▋     | 2422/5153 [09:30<10:41,  4.25it/s]

 47%|████▋     | 2423/5153 [09:30<10:42,  4.25it/s]

 47%|████▋     | 2424/5153 [09:30<10:42,  4.25it/s]

 47%|████▋     | 2425/5153 [09:31<10:41,  4.25it/s]

 47%|████▋     | 2426/5153 [09:31<10:41,  4.25it/s]

 47%|████▋     | 2427/5153 [09:31<10:40,  4.25it/s]

 47%|████▋     | 2428/5153 [09:31<10:41,  4.25it/s]

 47%|████▋     | 2429/5153 [09:32<10:39,  4.26it/s]

 47%|████▋     | 2430/5153 [09:32<10:39,  4.26it/s]

 47%|████▋     | 2431/5153 [09:32<10:41,  4.24it/s]

 47%|████▋     | 2432/5153 [09:32<10:39,  4.25it/s]

 47%|████▋     | 2433/5153 [09:32<10:38,  4.26it/s]

 47%|████▋     | 2434/5153 [09:33<10:38,  4.26it/s]

 47%|████▋     | 2435/5153 [09:33<10:39,  4.25it/s]

 47%|████▋     | 2436/5153 [09:33<10:39,  4.25it/s]

 47%|████▋     | 2437/5153 [09:33<10:37,  4.26it/s]

 47%|████▋     | 2438/5153 [09:34<10:37,  4.26it/s]

 47%|████▋     | 2439/5153 [09:34<10:37,  4.26it/s]

 47%|████▋     | 2440/5153 [09:34<10:36,  4.26it/s]

 47%|████▋     | 2441/5153 [09:34<10:37,  4.25it/s]

 47%|████▋     | 2442/5153 [09:35<10:36,  4.26it/s]

 47%|████▋     | 2443/5153 [09:35<10:34,  4.27it/s]

 47%|████▋     | 2444/5153 [09:35<10:34,  4.27it/s]

 47%|████▋     | 2445/5153 [09:35<10:36,  4.25it/s]

 47%|████▋     | 2446/5153 [09:36<10:36,  4.25it/s]

 47%|████▋     | 2447/5153 [09:36<10:37,  4.25it/s]

 48%|████▊     | 2448/5153 [09:36<10:38,  4.24it/s]

 48%|████▊     | 2449/5153 [09:36<10:37,  4.24it/s]

 48%|████▊     | 2450/5153 [09:36<10:35,  4.25it/s]

 48%|████▊     | 2451/5153 [09:37<10:35,  4.25it/s]

 48%|████▊     | 2452/5153 [09:37<10:34,  4.26it/s]

 48%|████▊     | 2453/5153 [09:37<10:34,  4.26it/s]

 48%|████▊     | 2454/5153 [09:37<10:33,  4.26it/s]

 48%|████▊     | 2455/5153 [09:38<10:33,  4.26it/s]

 48%|████▊     | 2456/5153 [09:38<10:34,  4.25it/s]

 48%|████▊     | 2457/5153 [09:38<10:33,  4.26it/s]

 48%|████▊     | 2458/5153 [09:38<10:33,  4.25it/s]

 48%|████▊     | 2459/5153 [09:39<10:33,  4.25it/s]

 48%|████▊     | 2460/5153 [09:39<10:33,  4.25it/s]

 48%|████▊     | 2461/5153 [09:39<10:32,  4.26it/s]

 48%|████▊     | 2462/5153 [09:39<10:31,  4.26it/s]

 48%|████▊     | 2463/5153 [09:40<10:31,  4.26it/s]

 48%|████▊     | 2464/5153 [09:40<10:33,  4.25it/s]

 48%|████▊     | 2465/5153 [09:40<10:33,  4.25it/s]

 48%|████▊     | 2466/5153 [09:40<10:33,  4.24it/s]

 48%|████▊     | 2467/5153 [09:40<10:31,  4.25it/s]

 48%|████▊     | 2468/5153 [09:41<10:30,  4.26it/s]

 48%|████▊     | 2469/5153 [09:41<10:30,  4.25it/s]

 48%|████▊     | 2470/5153 [09:41<10:31,  4.25it/s]

 48%|████▊     | 2471/5153 [09:41<10:32,  4.24it/s]

 48%|████▊     | 2472/5153 [09:42<10:32,  4.24it/s]

 48%|████▊     | 2473/5153 [09:42<10:32,  4.24it/s]

 48%|████▊     | 2474/5153 [09:42<10:31,  4.25it/s]

 48%|████▊     | 2475/5153 [09:42<10:32,  4.24it/s]

 48%|████▊     | 2476/5153 [09:43<10:34,  4.22it/s]

 48%|████▊     | 2477/5153 [09:43<10:32,  4.23it/s]

 48%|████▊     | 2478/5153 [09:43<10:33,  4.22it/s]

 48%|████▊     | 2479/5153 [09:43<10:30,  4.24it/s]

 48%|████▊     | 2480/5153 [09:44<10:31,  4.23it/s]

 48%|████▊     | 2481/5153 [09:44<10:31,  4.23it/s]

 48%|████▊     | 2482/5153 [09:44<10:29,  4.24it/s]

 48%|████▊     | 2483/5153 [09:44<10:29,  4.24it/s]

 48%|████▊     | 2484/5153 [09:44<10:29,  4.24it/s]

 48%|████▊     | 2485/5153 [09:45<10:30,  4.23it/s]

 48%|████▊     | 2486/5153 [09:45<10:28,  4.24it/s]

 48%|████▊     | 2487/5153 [09:45<10:28,  4.24it/s]

 48%|████▊     | 2488/5153 [09:45<10:29,  4.23it/s]

 48%|████▊     | 2489/5153 [09:46<10:28,  4.24it/s]

 48%|████▊     | 2490/5153 [09:46<10:27,  4.24it/s]

 48%|████▊     | 2491/5153 [09:46<10:27,  4.24it/s]

 48%|████▊     | 2492/5153 [09:46<10:27,  4.24it/s]

 48%|████▊     | 2493/5153 [09:47<10:28,  4.23it/s]

 48%|████▊     | 2494/5153 [09:47<10:26,  4.24it/s]

 48%|████▊     | 2495/5153 [09:47<10:27,  4.24it/s]

 48%|████▊     | 2496/5153 [09:47<10:26,  4.24it/s]

 48%|████▊     | 2497/5153 [09:48<10:25,  4.24it/s]

 48%|████▊     | 2498/5153 [09:48<10:25,  4.25it/s]

 48%|████▊     | 2499/5153 [09:48<10:23,  4.26it/s]

 49%|████▊     | 2500/5153 [09:48<10:23,  4.25it/s]

 49%|████▊     | 2501/5153 [09:48<10:23,  4.25it/s]

 49%|████▊     | 2502/5153 [09:49<10:25,  4.24it/s]

 49%|████▊     | 2503/5153 [09:49<10:25,  4.23it/s]

logging
logging the anndata

 49%|████▊     | 2504/5153 [09:50<26:14,  1.68it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 49%|████▊     | 2505/5153 [09:51<21:25,  2.06it/s]

 49%|████▊     | 2506/5153 [09:51<17:59,  2.45it/s]

 49%|████▊     | 2507/5153 [09:51<15:37,  2.82it/s]

 49%|████▊     | 2508/5153 [09:51<13:57,  3.16it/s]

 49%|████▊     | 2509/5153 [09:52<12:46,  3.45it/s]

 49%|████▊     | 2510/5153 [09:52<11:58,  3.68it/s]

 49%|████▊     | 2511/5153 [09:52<11:25,  3.86it/s]

 49%|████▊     | 2512/5153 [09:52<11:02,  3.99it/s]

 49%|████▉     | 2513/5153 [09:52<10:46,  4.08it/s]

 49%|████▉     | 2514/5153 [09:53<10:33,  4.17it/s]

 49%|████▉     | 2515/5153 [09:53<10:23,  4.23it/s]

 49%|████▉     | 2516/5153 [09:53<10:18,  4.26it/s]

 49%|████▉     | 2517/5153 [09:53<10:13,  4.30it/s]

 49%|████▉     | 2518/5153 [09:54<10:11,  4.31it/s]

 49%|████▉     | 2519/5153 [09:54<10:08,  4.33it/s]

 49%|████▉     | 2520/5153 [09:54<10:07,  4.34it/s]

 49%|████▉     | 2521/5153 [09:54<10:07,  4.33it/s]

 49%|████▉     | 2522/5153 [09:54<10:05,  4.35it/s]

 49%|████▉     | 2523/5153 [09:55<10:04,  4.35it/s]

 49%|████▉     | 2524/5153 [09:55<10:04,  4.35it/s]

 49%|████▉     | 2525/5153 [09:55<10:02,  4.36it/s]

 49%|████▉     | 2526/5153 [09:55<10:03,  4.36it/s]

 49%|████▉     | 2527/5153 [09:56<10:04,  4.35it/s]

 49%|████▉     | 2528/5153 [09:56<10:02,  4.36it/s]

 49%|████▉     | 2529/5153 [09:56<10:02,  4.36it/s]

 49%|████▉     | 2530/5153 [09:56<10:02,  4.35it/s]

 49%|████▉     | 2531/5153 [09:57<10:02,  4.35it/s]

 49%|████▉     | 2532/5153 [09:57<10:02,  4.35it/s]

 49%|████▉     | 2533/5153 [09:57<10:01,  4.35it/s]

 49%|████▉     | 2534/5153 [09:57<10:02,  4.35it/s]

 49%|████▉     | 2535/5153 [09:57<10:02,  4.35it/s]

 49%|████▉     | 2536/5153 [09:58<10:00,  4.36it/s]

 49%|████▉     | 2537/5153 [09:58<10:00,  4.36it/s]

 49%|████▉     | 2538/5153 [09:58<09:59,  4.36it/s]

 49%|████▉     | 2539/5153 [09:58<09:58,  4.37it/s]

 49%|████▉     | 2540/5153 [09:59<10:00,  4.35it/s]

 49%|████▉     | 2541/5153 [09:59<09:59,  4.36it/s]

 49%|████▉     | 2542/5153 [09:59<09:59,  4.35it/s]

 49%|████▉     | 2543/5153 [09:59<10:00,  4.34it/s]

 49%|████▉     | 2544/5153 [10:00<09:59,  4.35it/s]

 49%|████▉     | 2545/5153 [10:00<09:58,  4.36it/s]

 49%|████▉     | 2546/5153 [10:00<09:58,  4.36it/s]

 49%|████▉     | 2547/5153 [10:00<09:58,  4.36it/s]

 49%|████▉     | 2548/5153 [10:00<09:57,  4.36it/s]

 49%|████▉     | 2549/5153 [10:01<09:57,  4.36it/s]

 49%|████▉     | 2550/5153 [10:01<09:57,  4.36it/s]

 50%|████▉     | 2551/5153 [10:01<09:56,  4.36it/s]

 50%|████▉     | 2552/5153 [10:01<09:55,  4.37it/s]

 50%|████▉     | 2553/5153 [10:02<09:55,  4.37it/s]

 50%|████▉     | 2554/5153 [10:02<09:56,  4.36it/s]

 50%|████▉     | 2555/5153 [10:02<09:55,  4.36it/s]

 50%|████▉     | 2556/5153 [10:02<09:55,  4.36it/s]

 50%|████▉     | 2557/5153 [10:03<09:56,  4.35it/s]

 50%|████▉     | 2558/5153 [10:03<09:56,  4.35it/s]

 50%|████▉     | 2559/5153 [10:03<09:56,  4.35it/s]

 50%|████▉     | 2560/5153 [10:03<09:56,  4.34it/s]

 50%|████▉     | 2561/5153 [10:03<09:56,  4.34it/s]

 50%|████▉     | 2562/5153 [10:04<09:56,  4.34it/s]

 50%|████▉     | 2563/5153 [10:04<09:55,  4.35it/s]

 50%|████▉     | 2564/5153 [10:04<09:54,  4.35it/s]

 50%|████▉     | 2565/5153 [10:04<09:55,  4.35it/s]

 50%|████▉     | 2566/5153 [10:05<09:54,  4.35it/s]

 50%|████▉     | 2567/5153 [10:05<09:54,  4.35it/s]

 50%|████▉     | 2568/5153 [10:05<09:54,  4.35it/s]

 50%|████▉     | 2569/5153 [10:05<09:54,  4.35it/s]

 50%|████▉     | 2570/5153 [10:06<09:53,  4.35it/s]

 50%|████▉     | 2571/5153 [10:06<09:53,  4.35it/s]

 50%|████▉     | 2572/5153 [10:06<09:53,  4.35it/s]

 50%|████▉     | 2573/5153 [10:06<09:52,  4.36it/s]

 50%|████▉     | 2574/5153 [10:06<09:51,  4.36it/s]

 50%|████▉     | 2575/5153 [10:07<09:52,  4.35it/s]

 50%|████▉     | 2576/5153 [10:07<09:51,  4.35it/s]

 50%|█████     | 2577/5153 [10:07<09:51,  4.35it/s]

 50%|█████     | 2578/5153 [10:07<09:51,  4.35it/s]

 50%|█████     | 2579/5153 [10:08<09:51,  4.35it/s]

 50%|█████     | 2580/5153 [10:08<09:50,  4.36it/s]

 50%|█████     | 2581/5153 [10:08<09:50,  4.36it/s]

 50%|█████     | 2582/5153 [10:08<09:50,  4.35it/s]

 50%|█████     | 2583/5153 [10:09<09:50,  4.35it/s]

 50%|█████     | 2584/5153 [10:09<09:51,  4.35it/s]

 50%|█████     | 2585/5153 [10:09<09:50,  4.35it/s]

 50%|█████     | 2586/5153 [10:09<09:50,  4.35it/s]

 50%|█████     | 2587/5153 [10:09<09:49,  4.35it/s]

 50%|█████     | 2588/5153 [10:10<09:49,  4.35it/s]

 50%|█████     | 2589/5153 [10:10<09:49,  4.35it/s]

 50%|█████     | 2590/5153 [10:10<09:48,  4.36it/s]

 50%|█████     | 2591/5153 [10:10<09:49,  4.35it/s]

 50%|█████     | 2592/5153 [10:11<09:49,  4.35it/s]

 50%|█████     | 2593/5153 [10:11<09:48,  4.35it/s]

 50%|█████     | 2594/5153 [10:11<09:49,  4.34it/s]

 50%|█████     | 2595/5153 [10:11<09:48,  4.35it/s]

 50%|█████     | 2596/5153 [10:11<09:49,  4.34it/s]

 50%|█████     | 2597/5153 [10:12<09:50,  4.33it/s]

 50%|█████     | 2598/5153 [10:12<09:50,  4.33it/s]

 50%|█████     | 2599/5153 [10:12<09:48,  4.34it/s]

 50%|█████     | 2600/5153 [10:12<09:48,  4.34it/s]

 50%|█████     | 2601/5153 [10:13<09:47,  4.35it/s]

 50%|█████     | 2602/5153 [10:13<09:47,  4.34it/s]

 51%|█████     | 2603/5153 [10:13<09:45,  4.35it/s]

 51%|█████     | 2604/5153 [10:13<09:45,  4.36it/s]

 51%|█████     | 2605/5153 [10:14<09:44,  4.36it/s]

 51%|█████     | 2606/5153 [10:14<09:44,  4.36it/s]

 51%|█████     | 2607/5153 [10:14<09:46,  4.34it/s]

 51%|█████     | 2608/5153 [10:14<09:48,  4.32it/s]

 51%|█████     | 2609/5153 [10:14<09:47,  4.33it/s]

 51%|█████     | 2610/5153 [10:15<09:45,  4.34it/s]

 51%|█████     | 2611/5153 [10:15<09:45,  4.34it/s]

 51%|█████     | 2612/5153 [10:15<09:44,  4.35it/s]

 51%|█████     | 2613/5153 [10:15<09:43,  4.35it/s]

 51%|█████     | 2614/5153 [10:16<09:44,  4.35it/s]

 51%|█████     | 2615/5153 [10:16<09:42,  4.35it/s]

 51%|█████     | 2616/5153 [10:16<09:42,  4.35it/s]

 51%|█████     | 2617/5153 [10:16<09:41,  4.36it/s]

 51%|█████     | 2618/5153 [10:17<09:42,  4.35it/s]

 51%|█████     | 2619/5153 [10:17<09:43,  4.35it/s]

 51%|█████     | 2620/5153 [10:17<09:42,  4.35it/s]

 51%|█████     | 2621/5153 [10:17<09:42,  4.35it/s]

 51%|█████     | 2622/5153 [10:17<09:42,  4.35it/s]

 51%|█████     | 2623/5153 [10:18<09:41,  4.35it/s]

 51%|█████     | 2624/5153 [10:18<09:42,  4.34it/s]

 51%|█████     | 2625/5153 [10:18<09:41,  4.34it/s]

 51%|█████     | 2626/5153 [10:18<09:40,  4.35it/s]

 51%|█████     | 2627/5153 [10:19<09:40,  4.35it/s]

 51%|█████     | 2628/5153 [10:19<09:39,  4.36it/s]

 51%|█████     | 2629/5153 [10:19<09:39,  4.36it/s]

 51%|█████     | 2630/5153 [10:19<09:39,  4.35it/s]

 51%|█████     | 2631/5153 [10:20<09:40,  4.34it/s]

 51%|█████     | 2632/5153 [10:20<09:39,  4.35it/s]

 51%|█████     | 2633/5153 [10:20<09:38,  4.35it/s]

 51%|█████     | 2634/5153 [10:20<09:39,  4.35it/s]

 51%|█████     | 2635/5153 [10:20<09:40,  4.34it/s]

 51%|█████     | 2636/5153 [10:21<09:40,  4.33it/s]

 51%|█████     | 2637/5153 [10:21<09:41,  4.33it/s]

 51%|█████     | 2638/5153 [10:21<09:40,  4.33it/s]

 51%|█████     | 2639/5153 [10:21<09:38,  4.34it/s]

 51%|█████     | 2640/5153 [10:22<09:38,  4.34it/s]

 51%|█████▏    | 2641/5153 [10:22<09:39,  4.33it/s]

 51%|█████▏    | 2642/5153 [10:22<09:39,  4.33it/s]

 51%|█████▏    | 2643/5153 [10:22<09:40,  4.33it/s]

 51%|█████▏    | 2644/5153 [10:23<09:38,  4.34it/s]

 51%|█████▏    | 2645/5153 [10:23<09:37,  4.34it/s]

 51%|█████▏    | 2646/5153 [10:23<09:38,  4.34it/s]

 51%|█████▏    | 2647/5153 [10:23<09:37,  4.34it/s]

 51%|█████▏    | 2648/5153 [10:23<09:37,  4.34it/s]

 51%|█████▏    | 2649/5153 [10:24<09:36,  4.34it/s]

 51%|█████▏    | 2650/5153 [10:24<09:35,  4.35it/s]

 51%|█████▏    | 2651/5153 [10:24<09:36,  4.34it/s]

 51%|█████▏    | 2652/5153 [10:24<09:38,  4.32it/s]

 51%|█████▏    | 2653/5153 [10:25<09:38,  4.32it/s]

 52%|█████▏    | 2654/5153 [10:25<09:38,  4.32it/s]

 52%|█████▏    | 2655/5153 [10:25<09:36,  4.33it/s]

 52%|█████▏    | 2656/5153 [10:25<09:36,  4.33it/s]

 52%|█████▏    | 2657/5153 [10:26<09:36,  4.33it/s]

 52%|█████▏    | 2658/5153 [10:26<09:35,  4.33it/s]

 52%|█████▏    | 2659/5153 [10:26<09:35,  4.33it/s]

 52%|█████▏    | 2660/5153 [10:26<09:35,  4.33it/s]

 52%|█████▏    | 2661/5153 [10:26<09:35,  4.33it/s]

 52%|█████▏    | 2662/5153 [10:27<09:35,  4.33it/s]

 52%|█████▏    | 2663/5153 [10:27<09:35,  4.32it/s]

 52%|█████▏    | 2664/5153 [10:27<09:38,  4.30it/s]

 52%|█████▏    | 2665/5153 [10:27<09:38,  4.30it/s]

 52%|█████▏    | 2666/5153 [10:28<09:36,  4.31it/s]

 52%|█████▏    | 2667/5153 [10:28<09:36,  4.31it/s]

 52%|█████▏    | 2668/5153 [10:28<09:36,  4.31it/s]

 52%|█████▏    | 2669/5153 [10:28<09:34,  4.32it/s]

 52%|█████▏    | 2670/5153 [10:29<09:34,  4.33it/s]

 52%|█████▏    | 2671/5153 [10:29<09:34,  4.32it/s]

 52%|█████▏    | 2672/5153 [10:29<09:32,  4.33it/s]

 52%|█████▏    | 2673/5153 [10:29<09:32,  4.33it/s]

 52%|█████▏    | 2674/5153 [10:29<09:32,  4.33it/s]

 52%|█████▏    | 2675/5153 [10:30<09:31,  4.34it/s]

 52%|█████▏    | 2676/5153 [10:30<09:31,  4.34it/s]

 52%|█████▏    | 2677/5153 [10:30<09:30,  4.34it/s]

 52%|█████▏    | 2678/5153 [10:30<09:30,  4.34it/s]

 52%|█████▏    | 2679/5153 [10:31<09:30,  4.34it/s]

 52%|█████▏    | 2680/5153 [10:31<09:30,  4.33it/s]

 52%|█████▏    | 2681/5153 [10:31<09:32,  4.32it/s]

 52%|█████▏    | 2682/5153 [10:31<09:31,  4.32it/s]

 52%|█████▏    | 2683/5153 [10:32<09:30,  4.33it/s]

 52%|█████▏    | 2684/5153 [10:32<09:30,  4.33it/s]

 52%|█████▏    | 2685/5153 [10:32<09:29,  4.33it/s]

 52%|█████▏    | 2686/5153 [10:32<09:29,  4.34it/s]

 52%|█████▏    | 2687/5153 [10:32<09:29,  4.33it/s]

 52%|█████▏    | 2688/5153 [10:33<09:29,  4.33it/s]

 52%|█████▏    | 2689/5153 [10:33<09:28,  4.33it/s]

 52%|█████▏    | 2690/5153 [10:33<09:27,  4.34it/s]

 52%|█████▏    | 2691/5153 [10:33<09:30,  4.31it/s]

 52%|█████▏    | 2692/5153 [10:34<09:30,  4.32it/s]

 52%|█████▏    | 2693/5153 [10:34<09:28,  4.32it/s]

 52%|█████▏    | 2694/5153 [10:34<09:27,  4.33it/s]

 52%|█████▏    | 2695/5153 [10:34<09:27,  4.33it/s]

 52%|█████▏    | 2696/5153 [10:35<09:27,  4.33it/s]

 52%|█████▏    | 2697/5153 [10:35<09:26,  4.34it/s]

 52%|█████▏    | 2698/5153 [10:35<09:26,  4.33it/s]

 52%|█████▏    | 2699/5153 [10:35<09:25,  4.34it/s]

 52%|█████▏    | 2700/5153 [10:35<09:26,  4.33it/s]

 52%|█████▏    | 2701/5153 [10:36<09:26,  4.33it/s]

 52%|█████▏    | 2702/5153 [10:36<09:25,  4.34it/s]

 52%|█████▏    | 2703/5153 [10:36<09:25,  4.33it/s]

 52%|█████▏    | 2704/5153 [10:36<09:25,  4.33it/s]

 52%|█████▏    | 2705/5153 [10:37<09:24,  4.33it/s]

 53%|█████▎    | 2706/5153 [10:37<09:24,  4.33it/s]

 53%|█████▎    | 2707/5153 [10:37<09:25,  4.33it/s]

 53%|█████▎    | 2708/5153 [10:37<09:24,  4.33it/s]

 53%|█████▎    | 2709/5153 [10:38<09:24,  4.33it/s]

 53%|█████▎    | 2710/5153 [10:38<09:23,  4.33it/s]

 53%|█████▎    | 2711/5153 [10:38<09:24,  4.33it/s]

 53%|█████▎    | 2712/5153 [10:38<09:24,  4.32it/s]

 53%|█████▎    | 2713/5153 [10:38<09:24,  4.32it/s]

 53%|█████▎    | 2714/5153 [10:39<09:24,  4.32it/s]

 53%|█████▎    | 2715/5153 [10:39<09:24,  4.32it/s]

 53%|█████▎    | 2716/5153 [10:39<09:25,  4.31it/s]

 53%|█████▎    | 2717/5153 [10:39<09:24,  4.32it/s]

 53%|█████▎    | 2718/5153 [10:40<09:22,  4.33it/s]

 53%|█████▎    | 2719/5153 [10:40<09:23,  4.32it/s]

 53%|█████▎    | 2720/5153 [10:40<09:30,  4.27it/s]

 53%|█████▎    | 2721/5153 [10:40<09:26,  4.29it/s]

 53%|█████▎    | 2722/5153 [10:41<09:25,  4.30it/s]

 53%|█████▎    | 2723/5153 [10:41<09:22,  4.32it/s]

 53%|█████▎    | 2724/5153 [10:41<09:23,  4.31it/s]

 53%|█████▎    | 2725/5153 [10:41<09:22,  4.31it/s]

 53%|█████▎    | 2726/5153 [10:42<09:21,  4.32it/s]

 53%|█████▎    | 2727/5153 [10:42<09:20,  4.33it/s]

 53%|█████▎    | 2728/5153 [10:42<09:20,  4.33it/s]

 53%|█████▎    | 2729/5153 [10:42<09:19,  4.33it/s]

 53%|█████▎    | 2730/5153 [10:42<09:19,  4.33it/s]

 53%|█████▎    | 2731/5153 [10:43<09:18,  4.33it/s]

 53%|█████▎    | 2732/5153 [10:43<09:18,  4.34it/s]

 53%|█████▎    | 2733/5153 [10:43<09:17,  4.34it/s]

 53%|█████▎    | 2734/5153 [10:43<09:17,  4.34it/s]

 53%|█████▎    | 2735/5153 [10:44<09:18,  4.33it/s]

 53%|█████▎    | 2736/5153 [10:44<09:18,  4.33it/s]

 53%|█████▎    | 2737/5153 [10:44<09:19,  4.32it/s]

 53%|█████▎    | 2738/5153 [10:44<09:20,  4.31it/s]

 53%|█████▎    | 2739/5153 [10:45<09:18,  4.32it/s]

 53%|█████▎    | 2740/5153 [10:45<09:19,  4.31it/s]

 53%|█████▎    | 2741/5153 [10:45<09:18,  4.32it/s]

 53%|█████▎    | 2742/5153 [10:45<09:19,  4.31it/s]

 53%|█████▎    | 2743/5153 [10:45<09:18,  4.31it/s]

 53%|█████▎    | 2744/5153 [10:46<09:18,  4.31it/s]

 53%|█████▎    | 2745/5153 [10:46<09:17,  4.32it/s]

 53%|█████▎    | 2746/5153 [10:46<09:17,  4.32it/s]

 53%|█████▎    | 2747/5153 [10:46<09:16,  4.32it/s]

 53%|█████▎    | 2748/5153 [10:47<09:17,  4.32it/s]

 53%|█████▎    | 2749/5153 [10:47<09:18,  4.30it/s]

 53%|█████▎    | 2750/5153 [10:47<09:17,  4.31it/s]

 53%|█████▎    | 2751/5153 [10:47<09:16,  4.31it/s]

 53%|█████▎    | 2752/5153 [10:48<09:15,  4.32it/s]

 53%|█████▎    | 2753/5153 [10:48<09:15,  4.32it/s]

 53%|█████▎    | 2754/5153 [10:48<09:15,  4.32it/s]

 53%|█████▎    | 2755/5153 [10:48<09:14,  4.33it/s]

 53%|█████▎    | 2756/5153 [10:48<09:14,  4.32it/s]

 54%|█████▎    | 2757/5153 [10:49<09:14,  4.32it/s]

 54%|█████▎    | 2758/5153 [10:49<09:14,  4.32it/s]

 54%|█████▎    | 2759/5153 [10:49<09:13,  4.32it/s]

 54%|█████▎    | 2760/5153 [10:49<09:13,  4.33it/s]

 54%|█████▎    | 2761/5153 [10:50<09:12,  4.33it/s]

 54%|█████▎    | 2762/5153 [10:50<09:12,  4.33it/s]

 54%|█████▎    | 2763/5153 [10:50<09:11,  4.33it/s]

 54%|█████▎    | 2764/5153 [10:50<09:12,  4.33it/s]

 54%|█████▎    | 2765/5153 [10:51<09:11,  4.33it/s]

 54%|█████▎    | 2766/5153 [10:51<09:10,  4.34it/s]

 54%|█████▎    | 2767/5153 [10:51<09:10,  4.34it/s]

 54%|█████▎    | 2768/5153 [10:51<09:10,  4.33it/s]

 54%|█████▎    | 2769/5153 [10:51<09:09,  4.34it/s]

 54%|█████▍    | 2770/5153 [10:52<09:09,  4.34it/s]

 54%|█████▍    | 2771/5153 [10:52<09:08,  4.34it/s]

 54%|█████▍    | 2772/5153 [10:52<09:08,  4.34it/s]

 54%|█████▍    | 2773/5153 [10:52<09:09,  4.33it/s]

 54%|█████▍    | 2774/5153 [10:53<09:10,  4.32it/s]

 54%|█████▍    | 2775/5153 [10:53<09:09,  4.33it/s]

 54%|█████▍    | 2776/5153 [10:53<09:09,  4.32it/s]

 54%|█████▍    | 2777/5153 [10:53<09:09,  4.32it/s]

 54%|█████▍    | 2778/5153 [10:54<09:10,  4.31it/s]

 54%|█████▍    | 2779/5153 [10:54<09:09,  4.32it/s]

 54%|█████▍    | 2780/5153 [10:54<09:09,  4.32it/s]

 54%|█████▍    | 2781/5153 [10:54<09:07,  4.33it/s]

 54%|█████▍    | 2782/5153 [10:54<09:08,  4.33it/s]

 54%|█████▍    | 2783/5153 [10:55<09:08,  4.32it/s]

 54%|█████▍    | 2784/5153 [10:55<09:07,  4.33it/s]

 54%|█████▍    | 2785/5153 [10:55<09:07,  4.33it/s]

 54%|█████▍    | 2786/5153 [10:55<09:06,  4.33it/s]

 54%|█████▍    | 2787/5153 [10:56<09:07,  4.32it/s]

 54%|█████▍    | 2788/5153 [10:56<09:09,  4.31it/s]

 54%|█████▍    | 2789/5153 [10:56<09:08,  4.31it/s]

 54%|█████▍    | 2790/5153 [10:56<09:08,  4.31it/s]

 54%|█████▍    | 2791/5153 [10:57<09:08,  4.31it/s]

 54%|█████▍    | 2792/5153 [10:57<09:07,  4.31it/s]

 54%|█████▍    | 2793/5153 [10:57<09:08,  4.30it/s]

 54%|█████▍    | 2794/5153 [10:57<09:07,  4.31it/s]

 54%|█████▍    | 2795/5153 [10:57<09:06,  4.32it/s]

 54%|█████▍    | 2796/5153 [10:58<09:06,  4.31it/s]

 54%|█████▍    | 2797/5153 [10:58<09:05,  4.32it/s]

 54%|█████▍    | 2798/5153 [10:58<09:04,  4.33it/s]

 54%|█████▍    | 2799/5153 [10:58<09:04,  4.32it/s]

 54%|█████▍    | 2800/5153 [10:59<09:04,  4.32it/s]

 54%|█████▍    | 2801/5153 [10:59<09:04,  4.32it/s]

 54%|█████▍    | 2802/5153 [10:59<09:04,  4.32it/s]

 54%|█████▍    | 2803/5153 [10:59<09:03,  4.32it/s]

 54%|█████▍    | 2804/5153 [11:00<09:04,  4.31it/s]

 54%|█████▍    | 2805/5153 [11:00<09:04,  4.31it/s]

 54%|█████▍    | 2806/5153 [11:00<09:04,  4.31it/s]

 54%|█████▍    | 2807/5153 [11:00<09:03,  4.31it/s]

 54%|█████▍    | 2808/5153 [11:00<09:04,  4.31it/s]

 55%|█████▍    | 2809/5153 [11:01<09:03,  4.31it/s]

 55%|█████▍    | 2810/5153 [11:01<09:01,  4.33it/s]

 55%|█████▍    | 2811/5153 [11:01<09:00,  4.34it/s]

 55%|█████▍    | 2812/5153 [11:01<09:00,  4.33it/s]

 55%|█████▍    | 2813/5153 [11:02<08:59,  4.34it/s]

 55%|█████▍    | 2814/5153 [11:02<08:59,  4.34it/s]

 55%|█████▍    | 2815/5153 [11:02<09:01,  4.32it/s]

 55%|█████▍    | 2816/5153 [11:02<09:00,  4.32it/s]

 55%|█████▍    | 2817/5153 [11:03<09:00,  4.32it/s]

 55%|█████▍    | 2818/5153 [11:03<08:59,  4.33it/s]

 55%|█████▍    | 2819/5153 [11:03<08:58,  4.33it/s]

 55%|█████▍    | 2820/5153 [11:03<08:59,  4.32it/s]

 55%|█████▍    | 2821/5153 [11:03<08:58,  4.33it/s]

 55%|█████▍    | 2822/5153 [11:04<08:58,  4.33it/s]

 55%|█████▍    | 2823/5153 [11:04<08:57,  4.33it/s]

 55%|█████▍    | 2824/5153 [11:04<08:57,  4.33it/s]

 55%|█████▍    | 2825/5153 [11:04<08:57,  4.33it/s]

 55%|█████▍    | 2826/5153 [11:05<08:57,  4.33it/s]

 55%|█████▍    | 2827/5153 [11:05<08:58,  4.32it/s]

 55%|█████▍    | 2828/5153 [11:05<08:58,  4.32it/s]

 55%|█████▍    | 2829/5153 [11:05<08:59,  4.31it/s]

 55%|█████▍    | 2830/5153 [11:06<08:59,  4.30it/s]

 55%|█████▍    | 2831/5153 [11:06<08:58,  4.31it/s]

 55%|█████▍    | 2832/5153 [11:06<08:58,  4.31it/s]

 55%|█████▍    | 2833/5153 [11:06<08:58,  4.31it/s]

 55%|█████▍    | 2834/5153 [11:06<08:57,  4.32it/s]

 55%|█████▌    | 2835/5153 [11:07<08:56,  4.32it/s]

 55%|█████▌    | 2836/5153 [11:07<08:58,  4.30it/s]

 55%|█████▌    | 2837/5153 [11:07<08:57,  4.31it/s]

 55%|█████▌    | 2838/5153 [11:07<08:57,  4.31it/s]

 55%|█████▌    | 2839/5153 [11:08<08:56,  4.31it/s]

 55%|█████▌    | 2840/5153 [11:08<08:55,  4.32it/s]

 55%|█████▌    | 2841/5153 [11:08<08:56,  4.31it/s]

 55%|█████▌    | 2842/5153 [11:08<08:56,  4.31it/s]

 55%|█████▌    | 2843/5153 [11:09<08:57,  4.30it/s]

 55%|█████▌    | 2844/5153 [11:09<08:55,  4.31it/s]

 55%|█████▌    | 2845/5153 [11:09<08:54,  4.32it/s]

 55%|█████▌    | 2846/5153 [11:09<08:55,  4.31it/s]

 55%|█████▌    | 2847/5153 [11:10<08:53,  4.32it/s]

 55%|█████▌    | 2848/5153 [11:10<08:52,  4.33it/s]

 55%|█████▌    | 2849/5153 [11:10<08:52,  4.32it/s]

 55%|█████▌    | 2850/5153 [11:10<08:52,  4.32it/s]

 55%|█████▌    | 2851/5153 [11:10<08:53,  4.32it/s]

 55%|█████▌    | 2852/5153 [11:11<08:51,  4.33it/s]

 55%|█████▌    | 2853/5153 [11:11<08:50,  4.33it/s]

 55%|█████▌    | 2854/5153 [11:11<08:50,  4.33it/s]

 55%|█████▌    | 2855/5153 [11:11<08:50,  4.33it/s]

 55%|█████▌    | 2856/5153 [11:12<08:51,  4.32it/s]

 55%|█████▌    | 2857/5153 [11:12<08:54,  4.30it/s]

 55%|█████▌    | 2858/5153 [11:12<08:54,  4.30it/s]

 55%|█████▌    | 2859/5153 [11:12<08:53,  4.30it/s]

 56%|█████▌    | 2860/5153 [11:13<08:53,  4.30it/s]

 56%|█████▌    | 2861/5153 [11:13<08:51,  4.31it/s]

 56%|█████▌    | 2862/5153 [11:13<08:52,  4.30it/s]

 56%|█████▌    | 2863/5153 [11:13<08:51,  4.31it/s]

 56%|█████▌    | 2864/5153 [11:13<08:51,  4.30it/s]

 56%|█████▌    | 2865/5153 [11:14<08:50,  4.31it/s]

 56%|█████▌    | 2866/5153 [11:14<08:50,  4.31it/s]

 56%|█████▌    | 2867/5153 [11:14<08:51,  4.30it/s]

 56%|█████▌    | 2868/5153 [11:14<08:49,  4.32it/s]

 56%|█████▌    | 2869/5153 [11:15<08:50,  4.31it/s]

 56%|█████▌    | 2870/5153 [11:15<08:49,  4.31it/s]

 56%|█████▌    | 2871/5153 [11:15<08:50,  4.30it/s]

 56%|█████▌    | 2872/5153 [11:15<08:51,  4.29it/s]

 56%|█████▌    | 2873/5153 [11:16<08:50,  4.30it/s]

 56%|█████▌    | 2874/5153 [11:16<08:49,  4.31it/s]

 56%|█████▌    | 2875/5153 [11:16<08:49,  4.30it/s]

 56%|█████▌    | 2876/5153 [11:16<08:48,  4.31it/s]

 56%|█████▌    | 2877/5153 [11:16<08:47,  4.31it/s]

 56%|█████▌    | 2878/5153 [11:17<08:46,  4.32it/s]

 56%|█████▌    | 2879/5153 [11:17<08:46,  4.32it/s]

 56%|█████▌    | 2880/5153 [11:17<08:46,  4.31it/s]

 56%|█████▌    | 2881/5153 [11:17<08:46,  4.31it/s]

 56%|█████▌    | 2882/5153 [11:18<08:45,  4.32it/s]

 56%|█████▌    | 2883/5153 [11:18<08:45,  4.32it/s]

 56%|█████▌    | 2884/5153 [11:18<08:47,  4.30it/s]

 56%|█████▌    | 2885/5153 [11:18<08:47,  4.30it/s]

 56%|█████▌    | 2886/5153 [11:19<08:45,  4.31it/s]

 56%|█████▌    | 2887/5153 [11:19<08:45,  4.31it/s]

 56%|█████▌    | 2888/5153 [11:19<08:45,  4.31it/s]

 56%|█████▌    | 2889/5153 [11:19<08:45,  4.31it/s]

 56%|█████▌    | 2890/5153 [11:19<08:44,  4.31it/s]

 56%|█████▌    | 2891/5153 [11:20<08:45,  4.31it/s]

 56%|█████▌    | 2892/5153 [11:20<08:44,  4.31it/s]

 56%|█████▌    | 2893/5153 [11:20<08:45,  4.30it/s]

 56%|█████▌    | 2894/5153 [11:20<08:44,  4.30it/s]

 56%|█████▌    | 2895/5153 [11:21<08:45,  4.30it/s]

 56%|█████▌    | 2896/5153 [11:21<08:45,  4.29it/s]

 56%|█████▌    | 2897/5153 [11:21<08:45,  4.29it/s]

 56%|█████▌    | 2898/5153 [11:21<08:44,  4.30it/s]

 56%|█████▋    | 2899/5153 [11:22<08:43,  4.31it/s]

 56%|█████▋    | 2900/5153 [11:22<08:43,  4.30it/s]

 56%|█████▋    | 2901/5153 [11:22<08:43,  4.30it/s]

 56%|█████▋    | 2902/5153 [11:22<08:42,  4.31it/s]

 56%|█████▋    | 2903/5153 [11:23<08:41,  4.31it/s]

 56%|█████▋    | 2904/5153 [11:23<08:41,  4.31it/s]

 56%|█████▋    | 2905/5153 [11:23<08:42,  4.30it/s]

 56%|█████▋    | 2906/5153 [11:23<08:42,  4.30it/s]

 56%|█████▋    | 2907/5153 [11:23<08:41,  4.30it/s]

 56%|█████▋    | 2908/5153 [11:24<08:41,  4.31it/s]

 56%|█████▋    | 2909/5153 [11:24<08:41,  4.30it/s]

 56%|█████▋    | 2910/5153 [11:24<08:41,  4.30it/s]

 56%|█████▋    | 2911/5153 [11:24<08:40,  4.31it/s]

 57%|█████▋    | 2912/5153 [11:25<08:40,  4.31it/s]

 57%|█████▋    | 2913/5153 [11:25<08:40,  4.31it/s]

 57%|█████▋    | 2914/5153 [11:25<08:40,  4.30it/s]

 57%|█████▋    | 2915/5153 [11:25<08:40,  4.30it/s]

 57%|█████▋    | 2916/5153 [11:26<08:41,  4.29it/s]

 57%|█████▋    | 2917/5153 [11:26<08:40,  4.29it/s]

 57%|█████▋    | 2918/5153 [11:26<08:39,  4.30it/s]

 57%|█████▋    | 2919/5153 [11:26<08:40,  4.29it/s]

 57%|█████▋    | 2920/5153 [11:26<08:39,  4.30it/s]

 57%|█████▋    | 2921/5153 [11:27<08:39,  4.29it/s]

 57%|█████▋    | 2922/5153 [11:27<08:39,  4.29it/s]

 57%|█████▋    | 2923/5153 [11:27<08:40,  4.29it/s]

 57%|█████▋    | 2924/5153 [11:27<08:40,  4.28it/s]

 57%|█████▋    | 2925/5153 [11:28<08:39,  4.29it/s]

 57%|█████▋    | 2926/5153 [11:28<08:38,  4.30it/s]

 57%|█████▋    | 2927/5153 [11:28<08:37,  4.30it/s]

 57%|█████▋    | 2928/5153 [11:28<08:39,  4.28it/s]

 57%|█████▋    | 2929/5153 [11:29<08:39,  4.28it/s]

 57%|█████▋    | 2930/5153 [11:29<08:38,  4.29it/s]

 57%|█████▋    | 2931/5153 [11:29<08:37,  4.29it/s]

 57%|█████▋    | 2932/5153 [11:29<08:36,  4.30it/s]

 57%|█████▋    | 2933/5153 [11:29<08:36,  4.30it/s]

 57%|█████▋    | 2934/5153 [11:30<08:35,  4.30it/s]

 57%|█████▋    | 2935/5153 [11:30<08:36,  4.30it/s]

 57%|█████▋    | 2936/5153 [11:30<08:35,  4.30it/s]

 57%|█████▋    | 2937/5153 [11:30<08:35,  4.30it/s]

 57%|█████▋    | 2938/5153 [11:31<08:34,  4.31it/s]

 57%|█████▋    | 2939/5153 [11:31<08:34,  4.30it/s]

 57%|█████▋    | 2940/5153 [11:31<08:34,  4.30it/s]

 57%|█████▋    | 2941/5153 [11:31<08:33,  4.31it/s]

 57%|█████▋    | 2942/5153 [11:32<08:33,  4.31it/s]

 57%|█████▋    | 2943/5153 [11:32<08:34,  4.29it/s]

 57%|█████▋    | 2944/5153 [11:32<08:33,  4.30it/s]

 57%|█████▋    | 2945/5153 [11:32<08:32,  4.31it/s]

 57%|█████▋    | 2946/5153 [11:33<08:36,  4.27it/s]

 57%|█████▋    | 2947/5153 [11:33<08:35,  4.28it/s]

 57%|█████▋    | 2948/5153 [11:33<08:35,  4.28it/s]

 57%|█████▋    | 2949/5153 [11:33<08:34,  4.28it/s]

 57%|█████▋    | 2950/5153 [11:33<08:34,  4.28it/s]

 57%|█████▋    | 2951/5153 [11:34<08:35,  4.27it/s]

 57%|█████▋    | 2952/5153 [11:34<08:33,  4.29it/s]

 57%|█████▋    | 2953/5153 [11:34<08:33,  4.28it/s]

 57%|█████▋    | 2954/5153 [11:34<08:32,  4.29it/s]

 57%|█████▋    | 2955/5153 [11:35<08:32,  4.29it/s]

 57%|█████▋    | 2956/5153 [11:35<08:32,  4.29it/s]

 57%|█████▋    | 2957/5153 [11:35<08:32,  4.29it/s]

 57%|█████▋    | 2958/5153 [11:35<08:31,  4.29it/s]

 57%|█████▋    | 2959/5153 [11:36<08:29,  4.30it/s]

 57%|█████▋    | 2960/5153 [11:36<08:28,  4.31it/s]

 57%|█████▋    | 2961/5153 [11:36<08:28,  4.31it/s]

 57%|█████▋    | 2962/5153 [11:36<08:28,  4.31it/s]

 58%|█████▊    | 2963/5153 [11:36<08:27,  4.31it/s]

 58%|█████▊    | 2964/5153 [11:37<08:28,  4.30it/s]

 58%|█████▊    | 2965/5153 [11:37<08:31,  4.27it/s]

 58%|█████▊    | 2966/5153 [11:37<08:30,  4.29it/s]

 58%|█████▊    | 2967/5153 [11:37<08:29,  4.29it/s]

 58%|█████▊    | 2968/5153 [11:38<08:28,  4.30it/s]

 58%|█████▊    | 2969/5153 [11:38<08:27,  4.30it/s]

 58%|█████▊    | 2970/5153 [11:38<08:28,  4.29it/s]

 58%|█████▊    | 2971/5153 [11:38<08:27,  4.30it/s]

 58%|█████▊    | 2972/5153 [11:39<08:27,  4.30it/s]

 58%|█████▊    | 2973/5153 [11:39<08:27,  4.30it/s]

 58%|█████▊    | 2974/5153 [11:39<08:28,  4.29it/s]

 58%|█████▊    | 2975/5153 [11:39<08:28,  4.28it/s]

 58%|█████▊    | 2976/5153 [11:40<08:29,  4.27it/s]

 58%|█████▊    | 2977/5153 [11:40<08:29,  4.27it/s]

 58%|█████▊    | 2978/5153 [11:40<08:29,  4.27it/s]

 58%|█████▊    | 2979/5153 [11:40<08:27,  4.28it/s]

 58%|█████▊    | 2980/5153 [11:40<08:28,  4.27it/s]

 58%|█████▊    | 2981/5153 [11:41<08:28,  4.27it/s]

 58%|█████▊    | 2982/5153 [11:41<08:28,  4.27it/s]

 58%|█████▊    | 2983/5153 [11:41<08:28,  4.27it/s]

 58%|█████▊    | 2984/5153 [11:41<08:27,  4.28it/s]

 58%|█████▊    | 2985/5153 [11:42<08:26,  4.28it/s]

 58%|█████▊    | 2986/5153 [11:42<08:25,  4.29it/s]

 58%|█████▊    | 2987/5153 [11:42<08:26,  4.28it/s]

 58%|█████▊    | 2988/5153 [11:42<08:26,  4.27it/s]

 58%|█████▊    | 2989/5153 [11:43<08:25,  4.28it/s]

 58%|█████▊    | 2990/5153 [11:43<08:27,  4.26it/s]

 58%|█████▊    | 2991/5153 [11:43<08:26,  4.27it/s]

 58%|█████▊    | 2992/5153 [11:43<08:26,  4.27it/s]

 58%|█████▊    | 2993/5153 [11:43<08:26,  4.27it/s]

 58%|█████▊    | 2994/5153 [11:44<08:25,  4.28it/s]

 58%|█████▊    | 2995/5153 [11:44<08:24,  4.27it/s]

 58%|█████▊    | 2996/5153 [11:44<08:24,  4.27it/s]

 58%|█████▊    | 2997/5153 [11:44<08:24,  4.27it/s]

 58%|█████▊    | 2998/5153 [11:45<08:25,  4.27it/s]

 58%|█████▊    | 2999/5153 [11:45<08:23,  4.28it/s]

 58%|█████▊    | 3000/5153 [11:45<08:23,  4.28it/s]

 58%|█████▊    | 3001/5153 [11:45<08:23,  4.28it/s]

 58%|█████▊    | 3002/5153 [11:46<08:23,  4.27it/s]

 58%|█████▊    | 3003/5153 [11:46<08:23,  4.27it/s]

 58%|█████▊    | 3004/5153 [11:46<08:22,  4.27it/s]

 58%|█████▊    | 3005/5153 [11:46<08:22,  4.28it/s]

 58%|█████▊    | 3006/5153 [11:47<08:21,  4.28it/s]

 58%|█████▊    | 3007/5153 [11:47<08:22,  4.27it/s]

 58%|█████▊    | 3008/5153 [11:47<08:21,  4.27it/s]

 58%|█████▊    | 3009/5153 [11:47<08:21,  4.28it/s]

 58%|█████▊    | 3010/5153 [11:47<08:20,  4.28it/s]

 58%|█████▊    | 3011/5153 [11:48<08:20,  4.28it/s]

 58%|█████▊    | 3012/5153 [11:48<08:19,  4.29it/s]

 58%|█████▊    | 3013/5153 [11:48<08:19,  4.28it/s]

 58%|█████▊    | 3014/5153 [11:48<08:18,  4.29it/s]

 59%|█████▊    | 3015/5153 [11:49<08:19,  4.28it/s]

 59%|█████▊    | 3016/5153 [11:49<08:20,  4.27it/s]

 59%|█████▊    | 3017/5153 [11:49<08:18,  4.29it/s]

 59%|█████▊    | 3018/5153 [11:49<08:17,  4.29it/s]

 59%|█████▊    | 3019/5153 [11:50<08:17,  4.29it/s]

 59%|█████▊    | 3020/5153 [11:50<08:18,  4.28it/s]

 59%|█████▊    | 3021/5153 [11:50<08:19,  4.27it/s]

 59%|█████▊    | 3022/5153 [11:50<08:18,  4.27it/s]

 59%|█████▊    | 3023/5153 [11:50<08:17,  4.28it/s]

 59%|█████▊    | 3024/5153 [11:51<08:17,  4.28it/s]

 59%|█████▊    | 3025/5153 [11:51<08:18,  4.27it/s]

 59%|█████▊    | 3026/5153 [11:51<08:19,  4.25it/s]

 59%|█████▊    | 3027/5153 [11:51<08:19,  4.26it/s]

 59%|█████▉    | 3028/5153 [11:52<08:19,  4.26it/s]

 59%|█████▉    | 3029/5153 [11:52<08:19,  4.25it/s]

 59%|█████▉    | 3030/5153 [11:52<08:18,  4.26it/s]

 59%|█████▉    | 3031/5153 [11:52<08:18,  4.26it/s]

 59%|█████▉    | 3032/5153 [11:53<08:17,  4.27it/s]

 59%|█████▉    | 3033/5153 [11:53<08:18,  4.26it/s]

 59%|█████▉    | 3034/5153 [11:53<08:17,  4.26it/s]

 59%|█████▉    | 3035/5153 [11:53<08:17,  4.25it/s]

 59%|█████▉    | 3036/5153 [11:54<08:18,  4.25it/s]

 59%|█████▉    | 3037/5153 [11:54<08:16,  4.26it/s]

 59%|█████▉    | 3038/5153 [11:54<08:16,  4.26it/s]

 59%|█████▉    | 3039/5153 [11:54<08:15,  4.26it/s]

 59%|█████▉    | 3040/5153 [11:54<08:15,  4.26it/s]

 59%|█████▉    | 3041/5153 [11:55<08:15,  4.26it/s]

 59%|█████▉    | 3042/5153 [11:55<08:14,  4.27it/s]

 59%|█████▉    | 3043/5153 [11:55<08:15,  4.26it/s]

 59%|█████▉    | 3044/5153 [11:55<08:15,  4.26it/s]

 59%|█████▉    | 3045/5153 [11:56<08:15,  4.25it/s]

 59%|█████▉    | 3046/5153 [11:56<08:14,  4.26it/s]

 59%|█████▉    | 3047/5153 [11:56<08:14,  4.26it/s]

 59%|█████▉    | 3048/5153 [11:56<08:14,  4.26it/s]

 59%|█████▉    | 3049/5153 [11:57<08:15,  4.25it/s]

 59%|█████▉    | 3050/5153 [11:57<08:15,  4.25it/s]

 59%|█████▉    | 3051/5153 [11:57<08:15,  4.24it/s]

 59%|█████▉    | 3052/5153 [11:57<08:13,  4.26it/s]

 59%|█████▉    | 3053/5153 [11:58<08:14,  4.25it/s]

 59%|█████▉    | 3054/5153 [11:58<08:19,  4.20it/s]

 59%|█████▉    | 3055/5153 [11:58<08:16,  4.23it/s]

 59%|█████▉    | 3056/5153 [11:58<08:14,  4.24it/s]

 59%|█████▉    | 3057/5153 [11:58<08:13,  4.25it/s]

 59%|█████▉    | 3058/5153 [11:59<08:12,  4.25it/s]

 59%|█████▉    | 3059/5153 [11:59<08:13,  4.24it/s]

 59%|█████▉    | 3060/5153 [11:59<08:13,  4.24it/s]

 59%|█████▉    | 3061/5153 [11:59<08:14,  4.23it/s]

 59%|█████▉    | 3062/5153 [12:00<08:11,  4.26it/s]

 59%|█████▉    | 3063/5153 [12:00<08:11,  4.25it/s]

 59%|█████▉    | 3064/5153 [12:00<08:11,  4.25it/s]

 59%|█████▉    | 3065/5153 [12:00<08:11,  4.25it/s]

 59%|█████▉    | 3066/5153 [12:01<08:11,  4.25it/s]

 60%|█████▉    | 3067/5153 [12:01<08:10,  4.25it/s]

 60%|█████▉    | 3068/5153 [12:01<08:09,  4.26it/s]

 60%|█████▉    | 3069/5153 [12:01<08:09,  4.26it/s]

 60%|█████▉    | 3070/5153 [12:02<08:08,  4.26it/s]

 60%|█████▉    | 3071/5153 [12:02<08:10,  4.25it/s]

 60%|█████▉    | 3072/5153 [12:02<08:09,  4.25it/s]

 60%|█████▉    | 3073/5153 [12:02<08:09,  4.25it/s]

 60%|█████▉    | 3074/5153 [12:02<08:09,  4.24it/s]

 60%|█████▉    | 3075/5153 [12:03<08:09,  4.24it/s]

 60%|█████▉    | 3076/5153 [12:03<08:08,  4.25it/s]

 60%|█████▉    | 3077/5153 [12:03<08:08,  4.25it/s]

 60%|█████▉    | 3078/5153 [12:03<08:08,  4.25it/s]

 60%|█████▉    | 3079/5153 [12:04<08:07,  4.25it/s]

 60%|█████▉    | 3080/5153 [12:04<08:07,  4.25it/s]

 60%|█████▉    | 3081/5153 [12:04<08:07,  4.25it/s]

 60%|█████▉    | 3082/5153 [12:04<08:06,  4.25it/s]

 60%|█████▉    | 3083/5153 [12:05<08:07,  4.25it/s]

 60%|█████▉    | 3084/5153 [12:05<08:06,  4.25it/s]

 60%|█████▉    | 3085/5153 [12:05<08:08,  4.23it/s]

 60%|█████▉    | 3086/5153 [12:05<08:08,  4.23it/s]

 60%|█████▉    | 3087/5153 [12:06<08:06,  4.24it/s]

 60%|█████▉    | 3088/5153 [12:06<08:06,  4.25it/s]

 60%|█████▉    | 3089/5153 [12:06<08:06,  4.25it/s]

 60%|█████▉    | 3090/5153 [12:06<08:06,  4.24it/s]

 60%|█████▉    | 3091/5153 [12:06<08:05,  4.25it/s]

 60%|██████    | 3092/5153 [12:07<08:05,  4.25it/s]

 60%|██████    | 3093/5153 [12:07<08:04,  4.25it/s]

 60%|██████    | 3094/5153 [12:07<08:03,  4.26it/s]

 60%|██████    | 3095/5153 [12:07<08:03,  4.26it/s]

 60%|██████    | 3096/5153 [12:08<08:03,  4.25it/s]

 60%|██████    | 3097/5153 [12:08<08:02,  4.26it/s]

 60%|██████    | 3098/5153 [12:08<08:03,  4.25it/s]

 60%|██████    | 3099/5153 [12:08<08:03,  4.25it/s]

 60%|██████    | 3100/5153 [12:09<08:04,  4.24it/s]

 60%|██████    | 3101/5153 [12:09<08:03,  4.24it/s]

 60%|██████    | 3102/5153 [12:09<08:04,  4.24it/s]

 60%|██████    | 3103/5153 [12:09<08:04,  4.23it/s]

 60%|██████    | 3104/5153 [12:10<08:03,  4.23it/s]

 60%|██████    | 3105/5153 [12:10<08:04,  4.23it/s]

 60%|██████    | 3106/5153 [12:10<08:04,  4.23it/s]

 60%|██████    | 3107/5153 [12:10<08:04,  4.23it/s]

 60%|██████    | 3108/5153 [12:11<08:03,  4.23it/s]

 60%|██████    | 3109/5153 [12:11<08:01,  4.24it/s]

 60%|██████    | 3110/5153 [12:11<08:01,  4.25it/s]

 60%|██████    | 3111/5153 [12:11<08:02,  4.23it/s]

 60%|██████    | 3112/5153 [12:11<08:01,  4.24it/s]

 60%|██████    | 3113/5153 [12:12<08:00,  4.24it/s]

 60%|██████    | 3114/5153 [12:12<08:00,  4.25it/s]

 60%|██████    | 3115/5153 [12:12<08:00,  4.24it/s]

 60%|██████    | 3116/5153 [12:12<07:59,  4.25it/s]

 60%|██████    | 3117/5153 [12:13<07:59,  4.25it/s]

 61%|██████    | 3118/5153 [12:13<08:00,  4.24it/s]

 61%|██████    | 3119/5153 [12:13<07:58,  4.25it/s]

 61%|██████    | 3120/5153 [12:13<07:59,  4.24it/s]

 61%|██████    | 3121/5153 [12:14<07:59,  4.24it/s]

 61%|██████    | 3122/5153 [12:14<08:00,  4.23it/s]

 61%|██████    | 3123/5153 [12:14<08:00,  4.23it/s]

 61%|██████    | 3124/5153 [12:14<07:59,  4.23it/s]

 61%|██████    | 3125/5153 [12:15<07:58,  4.23it/s]

 61%|██████    | 3126/5153 [12:15<07:57,  4.25it/s]

 61%|██████    | 3127/5153 [12:15<07:56,  4.25it/s]

 61%|██████    | 3128/5153 [12:15<07:56,  4.25it/s]

 61%|██████    | 3129/5153 [12:15<07:56,  4.25it/s]

logging
logging the anndata

 61%|██████    | 3130/5153 [12:17<20:15,  1.66it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 61%|██████    | 3131/5153 [12:17<16:28,  2.04it/s]

 61%|██████    | 3132/5153 [12:17<13:55,  2.42it/s]

 61%|██████    | 3133/5153 [12:18<12:02,  2.80it/s]

 61%|██████    | 3134/5153 [12:18<10:44,  3.13it/s]

 61%|██████    | 3135/5153 [12:18<09:49,  3.42it/s]

 61%|██████    | 3136/5153 [12:18<09:10,  3.66it/s]

 61%|██████    | 3137/5153 [12:19<08:43,  3.85it/s]

 61%|██████    | 3138/5153 [12:19<08:24,  3.99it/s]

 61%|██████    | 3139/5153 [12:19<08:11,  4.10it/s]

 61%|██████    | 3140/5153 [12:19<08:01,  4.18it/s]

 61%|██████    | 3141/5153 [12:19<07:55,  4.23it/s]

 61%|██████    | 3142/5153 [12:20<07:51,  4.27it/s]

 61%|██████    | 3143/5153 [12:20<07:48,  4.29it/s]

 61%|██████    | 3144/5153 [12:20<07:45,  4.32it/s]

 61%|██████    | 3145/5153 [12:20<07:43,  4.33it/s]

 61%|██████    | 3146/5153 [12:21<07:43,  4.33it/s]

 61%|██████    | 3147/5153 [12:21<07:42,  4.34it/s]

 61%|██████    | 3148/5153 [12:21<07:42,  4.34it/s]

 61%|██████    | 3149/5153 [12:21<07:41,  4.35it/s]

 61%|██████    | 3150/5153 [12:21<07:40,  4.35it/s]

 61%|██████    | 3151/5153 [12:22<07:40,  4.35it/s]

 61%|██████    | 3152/5153 [12:22<07:39,  4.36it/s]

 61%|██████    | 3153/5153 [12:22<07:39,  4.36it/s]

 61%|██████    | 3154/5153 [12:22<07:39,  4.35it/s]

 61%|██████    | 3155/5153 [12:23<07:38,  4.36it/s]

 61%|██████    | 3156/5153 [12:23<07:37,  4.36it/s]

 61%|██████▏   | 3157/5153 [12:23<07:37,  4.36it/s]

 61%|██████▏   | 3158/5153 [12:23<07:37,  4.36it/s]

 61%|██████▏   | 3159/5153 [12:24<07:36,  4.37it/s]

 61%|██████▏   | 3160/5153 [12:24<07:37,  4.36it/s]

 61%|██████▏   | 3161/5153 [12:24<07:36,  4.36it/s]

 61%|██████▏   | 3162/5153 [12:24<07:36,  4.36it/s]

 61%|██████▏   | 3163/5153 [12:24<07:35,  4.37it/s]

 61%|██████▏   | 3164/5153 [12:25<07:34,  4.37it/s]

 61%|██████▏   | 3165/5153 [12:25<07:34,  4.37it/s]

 61%|██████▏   | 3166/5153 [12:25<07:34,  4.37it/s]

 61%|██████▏   | 3167/5153 [12:25<07:34,  4.37it/s]

 61%|██████▏   | 3168/5153 [12:26<07:35,  4.36it/s]

 61%|██████▏   | 3169/5153 [12:26<07:34,  4.36it/s]

 62%|██████▏   | 3170/5153 [12:26<07:34,  4.36it/s]

 62%|██████▏   | 3171/5153 [12:26<07:35,  4.35it/s]

 62%|██████▏   | 3172/5153 [12:27<07:35,  4.35it/s]

 62%|██████▏   | 3173/5153 [12:27<07:35,  4.34it/s]

 62%|██████▏   | 3174/5153 [12:27<07:34,  4.35it/s]

 62%|██████▏   | 3175/5153 [12:27<07:34,  4.35it/s]

 62%|██████▏   | 3176/5153 [12:27<07:34,  4.35it/s]

 62%|██████▏   | 3177/5153 [12:28<07:33,  4.36it/s]

 62%|██████▏   | 3178/5153 [12:28<07:34,  4.35it/s]

 62%|██████▏   | 3179/5153 [12:28<07:34,  4.35it/s]

 62%|██████▏   | 3180/5153 [12:28<07:34,  4.35it/s]

 62%|██████▏   | 3181/5153 [12:29<07:34,  4.34it/s]

 62%|██████▏   | 3182/5153 [12:29<07:33,  4.35it/s]

 62%|██████▏   | 3183/5153 [12:29<07:32,  4.36it/s]

 62%|██████▏   | 3184/5153 [12:29<07:32,  4.36it/s]

 62%|██████▏   | 3185/5153 [12:30<07:31,  4.36it/s]

 62%|██████▏   | 3186/5153 [12:30<07:31,  4.36it/s]

 62%|██████▏   | 3187/5153 [12:30<07:30,  4.36it/s]

 62%|██████▏   | 3188/5153 [12:30<07:30,  4.36it/s]

 62%|██████▏   | 3189/5153 [12:30<07:30,  4.36it/s]

 62%|██████▏   | 3190/5153 [12:31<07:30,  4.36it/s]

 62%|██████▏   | 3191/5153 [12:31<07:30,  4.35it/s]

 62%|██████▏   | 3192/5153 [12:31<07:32,  4.34it/s]

 62%|██████▏   | 3193/5153 [12:31<07:30,  4.35it/s]

 62%|██████▏   | 3194/5153 [12:32<07:31,  4.34it/s]

 62%|██████▏   | 3195/5153 [12:32<07:30,  4.35it/s]

 62%|██████▏   | 3196/5153 [12:32<07:29,  4.36it/s]

 62%|██████▏   | 3197/5153 [12:32<07:28,  4.36it/s]

 62%|██████▏   | 3198/5153 [12:33<07:28,  4.36it/s]

 62%|██████▏   | 3199/5153 [12:33<07:28,  4.36it/s]

 62%|██████▏   | 3200/5153 [12:33<07:27,  4.37it/s]

 62%|██████▏   | 3201/5153 [12:33<07:26,  4.37it/s]

 62%|██████▏   | 3202/5153 [12:33<07:26,  4.37it/s]

 62%|██████▏   | 3203/5153 [12:34<07:27,  4.36it/s]

 62%|██████▏   | 3204/5153 [12:34<07:26,  4.36it/s]

 62%|██████▏   | 3205/5153 [12:34<07:27,  4.35it/s]

 62%|██████▏   | 3206/5153 [12:34<07:28,  4.34it/s]

 62%|██████▏   | 3207/5153 [12:35<07:27,  4.35it/s]

 62%|██████▏   | 3208/5153 [12:35<07:27,  4.35it/s]

 62%|██████▏   | 3209/5153 [12:35<07:26,  4.35it/s]

 62%|██████▏   | 3210/5153 [12:35<07:27,  4.35it/s]

 62%|██████▏   | 3211/5153 [12:36<07:28,  4.33it/s]

 62%|██████▏   | 3212/5153 [12:36<07:26,  4.35it/s]

 62%|██████▏   | 3213/5153 [12:36<07:25,  4.35it/s]

 62%|██████▏   | 3214/5153 [12:36<07:25,  4.35it/s]

 62%|██████▏   | 3215/5153 [12:36<07:24,  4.36it/s]

 62%|██████▏   | 3216/5153 [12:37<07:24,  4.36it/s]

 62%|██████▏   | 3217/5153 [12:37<07:24,  4.36it/s]

 62%|██████▏   | 3218/5153 [12:37<07:23,  4.36it/s]

 62%|██████▏   | 3219/5153 [12:37<07:23,  4.36it/s]

 62%|██████▏   | 3220/5153 [12:38<07:24,  4.35it/s]

 63%|██████▎   | 3221/5153 [12:38<07:24,  4.34it/s]

 63%|██████▎   | 3222/5153 [12:38<07:25,  4.34it/s]

 63%|██████▎   | 3223/5153 [12:38<07:24,  4.34it/s]

 63%|██████▎   | 3224/5153 [12:38<07:25,  4.33it/s]

 63%|██████▎   | 3225/5153 [12:39<07:25,  4.33it/s]

 63%|██████▎   | 3226/5153 [12:39<07:24,  4.34it/s]

 63%|██████▎   | 3227/5153 [12:39<07:23,  4.34it/s]

 63%|██████▎   | 3228/5153 [12:39<07:22,  4.35it/s]

 63%|██████▎   | 3229/5153 [12:40<07:23,  4.34it/s]

 63%|██████▎   | 3230/5153 [12:40<07:23,  4.33it/s]

 63%|██████▎   | 3231/5153 [12:40<07:23,  4.33it/s]

 63%|██████▎   | 3232/5153 [12:40<07:23,  4.33it/s]

 63%|██████▎   | 3233/5153 [12:41<07:23,  4.33it/s]

 63%|██████▎   | 3234/5153 [12:41<07:22,  4.34it/s]

 63%|██████▎   | 3235/5153 [12:41<07:21,  4.34it/s]

 63%|██████▎   | 3236/5153 [12:41<07:21,  4.34it/s]

 63%|██████▎   | 3237/5153 [12:41<07:21,  4.34it/s]

 63%|██████▎   | 3238/5153 [12:42<07:21,  4.34it/s]

 63%|██████▎   | 3239/5153 [12:42<07:25,  4.29it/s]

 63%|██████▎   | 3240/5153 [12:42<07:24,  4.31it/s]

 63%|██████▎   | 3241/5153 [12:42<07:23,  4.31it/s]

 63%|██████▎   | 3242/5153 [12:43<07:22,  4.32it/s]

 63%|██████▎   | 3243/5153 [12:43<07:20,  4.33it/s]

 63%|██████▎   | 3244/5153 [12:43<07:21,  4.33it/s]

 63%|██████▎   | 3245/5153 [12:43<07:19,  4.34it/s]

 63%|██████▎   | 3246/5153 [12:44<07:19,  4.34it/s]

 63%|██████▎   | 3247/5153 [12:44<07:19,  4.34it/s]

 63%|██████▎   | 3248/5153 [12:44<07:18,  4.34it/s]

 63%|██████▎   | 3249/5153 [12:44<07:19,  4.33it/s]

 63%|██████▎   | 3250/5153 [12:44<07:19,  4.33it/s]

 63%|██████▎   | 3251/5153 [12:45<07:18,  4.34it/s]

 63%|██████▎   | 3252/5153 [12:45<07:17,  4.35it/s]

 63%|██████▎   | 3253/5153 [12:45<07:17,  4.34it/s]

 63%|██████▎   | 3254/5153 [12:45<07:16,  4.35it/s]

 63%|██████▎   | 3255/5153 [12:46<07:16,  4.35it/s]

 63%|██████▎   | 3256/5153 [12:46<07:16,  4.35it/s]

 63%|██████▎   | 3257/5153 [12:46<07:16,  4.34it/s]

 63%|██████▎   | 3258/5153 [12:46<07:16,  4.34it/s]

 63%|██████▎   | 3259/5153 [12:47<07:15,  4.35it/s]

 63%|██████▎   | 3260/5153 [12:47<07:15,  4.35it/s]

 63%|██████▎   | 3261/5153 [12:47<07:15,  4.35it/s]

 63%|██████▎   | 3262/5153 [12:47<07:14,  4.35it/s]

 63%|██████▎   | 3263/5153 [12:47<07:15,  4.34it/s]

 63%|██████▎   | 3264/5153 [12:48<07:15,  4.34it/s]

 63%|██████▎   | 3265/5153 [12:48<07:15,  4.34it/s]

 63%|██████▎   | 3266/5153 [12:48<07:15,  4.33it/s]

 63%|██████▎   | 3267/5153 [12:48<07:14,  4.34it/s]

 63%|██████▎   | 3268/5153 [12:49<07:15,  4.33it/s]

 63%|██████▎   | 3269/5153 [12:49<07:15,  4.32it/s]

 63%|██████▎   | 3270/5153 [12:49<07:14,  4.33it/s]

 63%|██████▎   | 3271/5153 [12:49<07:13,  4.34it/s]

 63%|██████▎   | 3272/5153 [12:50<07:13,  4.34it/s]

 64%|██████▎   | 3273/5153 [12:50<07:12,  4.35it/s]

 64%|██████▎   | 3274/5153 [12:50<07:12,  4.35it/s]

 64%|██████▎   | 3275/5153 [12:50<07:14,  4.32it/s]

 64%|██████▎   | 3276/5153 [12:50<07:13,  4.33it/s]

 64%|██████▎   | 3277/5153 [12:51<07:13,  4.33it/s]

 64%|██████▎   | 3278/5153 [12:51<07:12,  4.33it/s]

 64%|██████▎   | 3279/5153 [12:51<07:13,  4.33it/s]

 64%|██████▎   | 3280/5153 [12:51<07:13,  4.32it/s]

 64%|██████▎   | 3281/5153 [12:52<07:12,  4.33it/s]

 64%|██████▎   | 3282/5153 [12:52<07:12,  4.33it/s]

 64%|██████▎   | 3283/5153 [12:52<07:12,  4.33it/s]

 64%|██████▎   | 3284/5153 [12:52<07:10,  4.34it/s]

 64%|██████▎   | 3285/5153 [12:53<07:10,  4.34it/s]

 64%|██████▍   | 3286/5153 [12:53<07:09,  4.35it/s]

 64%|██████▍   | 3287/5153 [12:53<07:10,  4.33it/s]

 64%|██████▍   | 3288/5153 [12:53<07:10,  4.33it/s]

 64%|██████▍   | 3289/5153 [12:53<07:09,  4.34it/s]

 64%|██████▍   | 3290/5153 [12:54<07:10,  4.33it/s]

 64%|██████▍   | 3291/5153 [12:54<07:10,  4.32it/s]

 64%|██████▍   | 3292/5153 [12:54<07:10,  4.32it/s]

 64%|██████▍   | 3293/5153 [12:54<07:10,  4.32it/s]

 64%|██████▍   | 3294/5153 [12:55<07:09,  4.33it/s]

 64%|██████▍   | 3295/5153 [12:55<07:09,  4.33it/s]

 64%|██████▍   | 3296/5153 [12:55<07:08,  4.33it/s]

 64%|██████▍   | 3297/5153 [12:55<07:09,  4.33it/s]

 64%|██████▍   | 3298/5153 [12:56<07:09,  4.32it/s]

 64%|██████▍   | 3299/5153 [12:56<07:08,  4.33it/s]

 64%|██████▍   | 3300/5153 [12:56<07:07,  4.33it/s]

 64%|██████▍   | 3301/5153 [12:56<07:07,  4.33it/s]

 64%|██████▍   | 3302/5153 [12:56<07:06,  4.34it/s]

 64%|██████▍   | 3303/5153 [12:57<07:06,  4.34it/s]

 64%|██████▍   | 3304/5153 [12:57<07:06,  4.34it/s]

 64%|██████▍   | 3305/5153 [12:57<07:06,  4.34it/s]

 64%|██████▍   | 3306/5153 [12:57<07:05,  4.34it/s]

 64%|██████▍   | 3307/5153 [12:58<07:05,  4.34it/s]

 64%|██████▍   | 3308/5153 [12:58<07:05,  4.34it/s]

 64%|██████▍   | 3309/5153 [12:58<07:05,  4.33it/s]

 64%|██████▍   | 3310/5153 [12:58<07:05,  4.33it/s]

 64%|██████▍   | 3311/5153 [12:59<07:05,  4.33it/s]

 64%|██████▍   | 3312/5153 [12:59<07:06,  4.31it/s]

 64%|██████▍   | 3313/5153 [12:59<07:05,  4.32it/s]

 64%|██████▍   | 3314/5153 [12:59<07:05,  4.32it/s]

 64%|██████▍   | 3315/5153 [12:59<07:04,  4.33it/s]

 64%|██████▍   | 3316/5153 [13:00<07:04,  4.33it/s]

 64%|██████▍   | 3317/5153 [13:00<07:04,  4.32it/s]

 64%|██████▍   | 3318/5153 [13:00<07:04,  4.32it/s]

 64%|██████▍   | 3319/5153 [13:00<07:03,  4.33it/s]

 64%|██████▍   | 3320/5153 [13:01<07:03,  4.32it/s]

 64%|██████▍   | 3321/5153 [13:01<07:03,  4.33it/s]

 64%|██████▍   | 3322/5153 [13:01<07:03,  4.33it/s]

 64%|██████▍   | 3323/5153 [13:01<07:02,  4.33it/s]

 65%|██████▍   | 3324/5153 [13:02<07:02,  4.33it/s]

 65%|██████▍   | 3325/5153 [13:02<07:02,  4.32it/s]

 65%|██████▍   | 3326/5153 [13:02<07:01,  4.33it/s]

 65%|██████▍   | 3327/5153 [13:02<07:01,  4.33it/s]

 65%|██████▍   | 3328/5153 [13:02<07:03,  4.31it/s]

 65%|██████▍   | 3329/5153 [13:03<07:02,  4.32it/s]

 65%|██████▍   | 3330/5153 [13:03<07:01,  4.33it/s]

 65%|██████▍   | 3331/5153 [13:03<07:00,  4.33it/s]

 65%|██████▍   | 3332/5153 [13:03<07:00,  4.33it/s]

 65%|██████▍   | 3333/5153 [13:04<07:01,  4.32it/s]

 65%|██████▍   | 3334/5153 [13:04<07:00,  4.33it/s]

 65%|██████▍   | 3335/5153 [13:04<06:59,  4.33it/s]

 65%|██████▍   | 3336/5153 [13:04<06:59,  4.33it/s]

 65%|██████▍   | 3337/5153 [13:05<06:59,  4.33it/s]

 65%|██████▍   | 3338/5153 [13:05<07:00,  4.32it/s]

 65%|██████▍   | 3339/5153 [13:05<06:59,  4.32it/s]

 65%|██████▍   | 3340/5153 [13:05<06:59,  4.32it/s]

 65%|██████▍   | 3341/5153 [13:06<06:59,  4.32it/s]

 65%|██████▍   | 3342/5153 [13:06<06:59,  4.32it/s]

 65%|██████▍   | 3343/5153 [13:06<06:58,  4.33it/s]

 65%|██████▍   | 3344/5153 [13:06<06:58,  4.33it/s]

 65%|██████▍   | 3345/5153 [13:06<06:58,  4.32it/s]

 65%|██████▍   | 3346/5153 [13:07<06:58,  4.32it/s]

 65%|██████▍   | 3347/5153 [13:07<06:56,  4.33it/s]

 65%|██████▍   | 3348/5153 [13:07<06:56,  4.33it/s]

 65%|██████▍   | 3349/5153 [13:07<06:56,  4.33it/s]

 65%|██████▌   | 3350/5153 [13:08<06:55,  4.34it/s]

 65%|██████▌   | 3351/5153 [13:08<06:56,  4.33it/s]

 65%|██████▌   | 3352/5153 [13:08<06:56,  4.33it/s]

 65%|██████▌   | 3353/5153 [13:08<06:55,  4.33it/s]

 65%|██████▌   | 3354/5153 [13:09<06:55,  4.33it/s]

 65%|██████▌   | 3355/5153 [13:09<06:54,  4.34it/s]

 65%|██████▌   | 3356/5153 [13:09<06:54,  4.33it/s]

 65%|██████▌   | 3357/5153 [13:09<06:54,  4.33it/s]

 65%|██████▌   | 3358/5153 [13:09<06:54,  4.33it/s]

 65%|██████▌   | 3359/5153 [13:10<06:54,  4.33it/s]

 65%|██████▌   | 3360/5153 [13:10<06:54,  4.33it/s]

 65%|██████▌   | 3361/5153 [13:10<06:54,  4.32it/s]

 65%|██████▌   | 3362/5153 [13:10<06:54,  4.32it/s]

 65%|██████▌   | 3363/5153 [13:11<06:53,  4.33it/s]

 65%|██████▌   | 3364/5153 [13:11<06:53,  4.32it/s]

 65%|██████▌   | 3365/5153 [13:11<06:59,  4.27it/s]

 65%|██████▌   | 3366/5153 [13:11<06:56,  4.29it/s]

 65%|██████▌   | 3367/5153 [13:12<06:56,  4.29it/s]

 65%|██████▌   | 3368/5153 [13:12<06:55,  4.30it/s]

 65%|██████▌   | 3369/5153 [13:12<06:54,  4.31it/s]

 65%|██████▌   | 3370/5153 [13:12<06:54,  4.30it/s]

 65%|██████▌   | 3371/5153 [13:12<06:53,  4.31it/s]

 65%|██████▌   | 3372/5153 [13:13<06:53,  4.31it/s]

 65%|██████▌   | 3373/5153 [13:13<06:53,  4.31it/s]

 65%|██████▌   | 3374/5153 [13:13<06:52,  4.31it/s]

 65%|██████▌   | 3375/5153 [13:13<06:51,  4.32it/s]

 66%|██████▌   | 3376/5153 [13:14<06:51,  4.32it/s]

 66%|██████▌   | 3377/5153 [13:14<06:51,  4.32it/s]

 66%|██████▌   | 3378/5153 [13:14<06:50,  4.32it/s]

 66%|██████▌   | 3379/5153 [13:14<06:50,  4.32it/s]

 66%|██████▌   | 3380/5153 [13:15<06:50,  4.32it/s]

 66%|██████▌   | 3381/5153 [13:15<06:49,  4.33it/s]

 66%|██████▌   | 3382/5153 [13:15<06:49,  4.32it/s]

 66%|██████▌   | 3383/5153 [13:15<06:50,  4.32it/s]

 66%|██████▌   | 3384/5153 [13:15<06:48,  4.33it/s]

 66%|██████▌   | 3385/5153 [13:16<06:48,  4.33it/s]

 66%|██████▌   | 3386/5153 [13:16<06:48,  4.32it/s]

 66%|██████▌   | 3387/5153 [13:16<06:48,  4.32it/s]

 66%|██████▌   | 3388/5153 [13:16<06:48,  4.32it/s]

 66%|██████▌   | 3389/5153 [13:17<06:48,  4.32it/s]

 66%|██████▌   | 3390/5153 [13:17<06:47,  4.33it/s]

 66%|██████▌   | 3391/5153 [13:17<06:46,  4.33it/s]

 66%|██████▌   | 3392/5153 [13:17<06:45,  4.34it/s]

 66%|██████▌   | 3393/5153 [13:18<06:46,  4.33it/s]

 66%|██████▌   | 3394/5153 [13:18<06:46,  4.32it/s]

 66%|██████▌   | 3395/5153 [13:18<06:46,  4.33it/s]

 66%|██████▌   | 3396/5153 [13:18<06:46,  4.33it/s]

 66%|██████▌   | 3397/5153 [13:18<06:45,  4.33it/s]

 66%|██████▌   | 3398/5153 [13:19<06:44,  4.34it/s]

 66%|██████▌   | 3399/5153 [13:19<06:45,  4.33it/s]

 66%|██████▌   | 3400/5153 [13:19<06:45,  4.33it/s]

 66%|██████▌   | 3401/5153 [13:19<06:45,  4.32it/s]

 66%|██████▌   | 3402/5153 [13:20<06:45,  4.32it/s]

 66%|██████▌   | 3403/5153 [13:20<06:45,  4.32it/s]

 66%|██████▌   | 3404/5153 [13:20<06:44,  4.32it/s]

 66%|██████▌   | 3405/5153 [13:20<06:44,  4.32it/s]

 66%|██████▌   | 3406/5153 [13:21<06:44,  4.32it/s]

 66%|██████▌   | 3407/5153 [13:21<06:44,  4.32it/s]

 66%|██████▌   | 3408/5153 [13:21<06:44,  4.31it/s]

 66%|██████▌   | 3409/5153 [13:21<06:44,  4.31it/s]

 66%|██████▌   | 3410/5153 [13:21<06:44,  4.31it/s]

 66%|██████▌   | 3411/5153 [13:22<06:44,  4.31it/s]

 66%|██████▌   | 3412/5153 [13:22<06:44,  4.30it/s]

 66%|██████▌   | 3413/5153 [13:22<06:43,  4.32it/s]

 66%|██████▋   | 3414/5153 [13:22<06:42,  4.32it/s]

 66%|██████▋   | 3415/5153 [13:23<06:42,  4.32it/s]

 66%|██████▋   | 3416/5153 [13:23<06:43,  4.31it/s]

 66%|██████▋   | 3417/5153 [13:23<06:42,  4.31it/s]

 66%|██████▋   | 3418/5153 [13:23<06:41,  4.32it/s]

 66%|██████▋   | 3419/5153 [13:24<06:42,  4.31it/s]

 66%|██████▋   | 3420/5153 [13:24<06:41,  4.31it/s]

 66%|██████▋   | 3421/5153 [13:24<06:40,  4.32it/s]

 66%|██████▋   | 3422/5153 [13:24<06:41,  4.31it/s]

 66%|██████▋   | 3423/5153 [13:24<06:41,  4.31it/s]

 66%|██████▋   | 3424/5153 [13:25<06:41,  4.31it/s]

 66%|██████▋   | 3425/5153 [13:25<06:40,  4.31it/s]

 66%|██████▋   | 3426/5153 [13:25<06:40,  4.32it/s]

 67%|██████▋   | 3427/5153 [13:25<06:39,  4.32it/s]

 67%|██████▋   | 3428/5153 [13:26<06:39,  4.32it/s]

 67%|██████▋   | 3429/5153 [13:26<06:39,  4.31it/s]

 67%|██████▋   | 3430/5153 [13:26<06:40,  4.30it/s]

 67%|██████▋   | 3431/5153 [13:26<06:40,  4.30it/s]

 67%|██████▋   | 3432/5153 [13:27<06:40,  4.30it/s]

 67%|██████▋   | 3433/5153 [13:27<06:39,  4.31it/s]

 67%|██████▋   | 3434/5153 [13:27<06:37,  4.32it/s]

 67%|██████▋   | 3435/5153 [13:27<06:37,  4.32it/s]

 67%|██████▋   | 3436/5153 [13:27<06:36,  4.33it/s]

 67%|██████▋   | 3437/5153 [13:28<06:37,  4.32it/s]

 67%|██████▋   | 3438/5153 [13:28<06:37,  4.32it/s]

 67%|██████▋   | 3439/5153 [13:28<06:36,  4.32it/s]

 67%|██████▋   | 3440/5153 [13:28<06:35,  4.33it/s]

 67%|██████▋   | 3441/5153 [13:29<06:35,  4.33it/s]

 67%|██████▋   | 3442/5153 [13:29<06:34,  4.33it/s]

 67%|██████▋   | 3443/5153 [13:29<06:34,  4.33it/s]

 67%|██████▋   | 3444/5153 [13:29<06:34,  4.33it/s]

 67%|██████▋   | 3445/5153 [13:30<06:34,  4.33it/s]

 67%|██████▋   | 3446/5153 [13:30<06:34,  4.33it/s]

 67%|██████▋   | 3447/5153 [13:30<06:33,  4.34it/s]

 67%|██████▋   | 3448/5153 [13:30<06:32,  4.34it/s]

 67%|██████▋   | 3449/5153 [13:30<06:33,  4.34it/s]

 67%|██████▋   | 3450/5153 [13:31<06:32,  4.34it/s]

 67%|██████▋   | 3451/5153 [13:31<06:31,  4.34it/s]

 67%|██████▋   | 3452/5153 [13:31<06:32,  4.34it/s]

 67%|██████▋   | 3453/5153 [13:31<06:32,  4.33it/s]

 67%|██████▋   | 3454/5153 [13:32<06:33,  4.32it/s]

 67%|██████▋   | 3455/5153 [13:32<06:33,  4.32it/s]

 67%|██████▋   | 3456/5153 [13:32<06:32,  4.32it/s]

 67%|██████▋   | 3457/5153 [13:32<06:32,  4.32it/s]

 67%|██████▋   | 3458/5153 [13:33<06:32,  4.32it/s]

 67%|██████▋   | 3459/5153 [13:33<06:32,  4.32it/s]

 67%|██████▋   | 3460/5153 [13:33<06:31,  4.32it/s]

 67%|██████▋   | 3461/5153 [13:33<06:31,  4.32it/s]

 67%|██████▋   | 3462/5153 [13:34<06:32,  4.31it/s]

 67%|██████▋   | 3463/5153 [13:34<06:31,  4.31it/s]

 67%|██████▋   | 3464/5153 [13:34<06:31,  4.31it/s]

 67%|██████▋   | 3465/5153 [13:34<06:33,  4.29it/s]

 67%|██████▋   | 3466/5153 [13:34<06:31,  4.31it/s]

 67%|██████▋   | 3467/5153 [13:35<06:31,  4.30it/s]

 67%|██████▋   | 3468/5153 [13:35<06:30,  4.31it/s]

 67%|██████▋   | 3469/5153 [13:35<06:30,  4.31it/s]

 67%|██████▋   | 3470/5153 [13:35<06:30,  4.31it/s]

 67%|██████▋   | 3471/5153 [13:36<06:29,  4.32it/s]

 67%|██████▋   | 3472/5153 [13:36<06:29,  4.32it/s]

 67%|██████▋   | 3473/5153 [13:36<06:29,  4.31it/s]

 67%|██████▋   | 3474/5153 [13:36<06:29,  4.32it/s]

 67%|██████▋   | 3475/5153 [13:37<06:29,  4.31it/s]

 67%|██████▋   | 3476/5153 [13:37<06:28,  4.31it/s]

 67%|██████▋   | 3477/5153 [13:37<06:28,  4.32it/s]

 67%|██████▋   | 3478/5153 [13:37<06:28,  4.32it/s]

 68%|██████▊   | 3479/5153 [13:37<06:26,  4.33it/s]

 68%|██████▊   | 3480/5153 [13:38<06:26,  4.33it/s]

 68%|██████▊   | 3481/5153 [13:38<06:27,  4.32it/s]

 68%|██████▊   | 3482/5153 [13:38<06:27,  4.31it/s]

 68%|██████▊   | 3483/5153 [13:38<06:28,  4.30it/s]

 68%|██████▊   | 3484/5153 [13:39<06:27,  4.31it/s]

 68%|██████▊   | 3485/5153 [13:39<06:27,  4.30it/s]

 68%|██████▊   | 3486/5153 [13:39<06:27,  4.31it/s]

 68%|██████▊   | 3487/5153 [13:39<06:26,  4.31it/s]

 68%|██████▊   | 3488/5153 [13:40<06:26,  4.31it/s]

 68%|██████▊   | 3489/5153 [13:40<06:27,  4.29it/s]

 68%|██████▊   | 3490/5153 [13:40<06:26,  4.30it/s]

 68%|██████▊   | 3491/5153 [13:40<06:26,  4.30it/s]

 68%|██████▊   | 3492/5153 [13:40<06:26,  4.30it/s]

 68%|██████▊   | 3493/5153 [13:41<06:25,  4.30it/s]

 68%|██████▊   | 3494/5153 [13:41<06:25,  4.30it/s]

 68%|██████▊   | 3495/5153 [13:41<06:25,  4.30it/s]

 68%|██████▊   | 3496/5153 [13:41<06:25,  4.30it/s]

 68%|██████▊   | 3497/5153 [13:42<06:24,  4.31it/s]

 68%|██████▊   | 3498/5153 [13:42<06:24,  4.30it/s]

 68%|██████▊   | 3499/5153 [13:42<06:24,  4.30it/s]

 68%|██████▊   | 3500/5153 [13:42<06:23,  4.31it/s]

 68%|██████▊   | 3501/5153 [13:43<06:23,  4.31it/s]

 68%|██████▊   | 3502/5153 [13:43<06:23,  4.31it/s]

 68%|██████▊   | 3503/5153 [13:43<06:22,  4.31it/s]

 68%|██████▊   | 3504/5153 [13:43<06:22,  4.31it/s]

 68%|██████▊   | 3505/5153 [13:43<06:22,  4.31it/s]

 68%|██████▊   | 3506/5153 [13:44<06:22,  4.31it/s]

 68%|██████▊   | 3507/5153 [13:44<06:22,  4.30it/s]

 68%|██████▊   | 3508/5153 [13:44<06:21,  4.31it/s]

 68%|██████▊   | 3509/5153 [13:44<06:21,  4.31it/s]

 68%|██████▊   | 3510/5153 [13:45<06:21,  4.31it/s]

 68%|██████▊   | 3511/5153 [13:45<06:21,  4.31it/s]

 68%|██████▊   | 3512/5153 [13:45<06:21,  4.30it/s]

 68%|██████▊   | 3513/5153 [13:45<06:21,  4.30it/s]

 68%|██████▊   | 3514/5153 [13:46<06:21,  4.29it/s]

 68%|██████▊   | 3515/5153 [13:46<06:21,  4.29it/s]

 68%|██████▊   | 3516/5153 [13:46<06:20,  4.30it/s]

 68%|██████▊   | 3517/5153 [13:46<06:20,  4.30it/s]

 68%|██████▊   | 3518/5153 [13:47<06:19,  4.31it/s]

 68%|██████▊   | 3519/5153 [13:47<06:19,  4.30it/s]

 68%|██████▊   | 3520/5153 [13:47<06:19,  4.30it/s]

 68%|██████▊   | 3521/5153 [13:47<06:19,  4.30it/s]

 68%|██████▊   | 3522/5153 [13:47<06:19,  4.30it/s]

 68%|██████▊   | 3523/5153 [13:48<06:19,  4.29it/s]

 68%|██████▊   | 3524/5153 [13:48<06:18,  4.30it/s]

 68%|██████▊   | 3525/5153 [13:48<06:18,  4.30it/s]

 68%|██████▊   | 3526/5153 [13:48<06:19,  4.29it/s]

 68%|██████▊   | 3527/5153 [13:49<06:18,  4.29it/s]

 68%|██████▊   | 3528/5153 [13:49<06:18,  4.29it/s]

 68%|██████▊   | 3529/5153 [13:49<06:18,  4.29it/s]

 69%|██████▊   | 3530/5153 [13:49<06:18,  4.29it/s]

 69%|██████▊   | 3531/5153 [13:50<06:17,  4.30it/s]

 69%|██████▊   | 3532/5153 [13:50<06:16,  4.30it/s]

 69%|██████▊   | 3533/5153 [13:50<06:17,  4.29it/s]

 69%|██████▊   | 3534/5153 [13:50<06:17,  4.29it/s]

 69%|██████▊   | 3535/5153 [13:50<06:16,  4.30it/s]

 69%|██████▊   | 3536/5153 [13:51<06:17,  4.29it/s]

 69%|██████▊   | 3537/5153 [13:51<06:19,  4.26it/s]

 69%|██████▊   | 3538/5153 [13:51<06:18,  4.27it/s]

 69%|██████▊   | 3539/5153 [13:51<06:17,  4.28it/s]

 69%|██████▊   | 3540/5153 [13:52<06:16,  4.29it/s]

 69%|██████▊   | 3541/5153 [13:52<06:15,  4.29it/s]

 69%|██████▊   | 3542/5153 [13:52<06:15,  4.30it/s]

 69%|██████▉   | 3543/5153 [13:52<06:14,  4.30it/s]

 69%|██████▉   | 3544/5153 [13:53<06:13,  4.31it/s]

 69%|██████▉   | 3545/5153 [13:53<06:14,  4.29it/s]

 69%|██████▉   | 3546/5153 [13:53<06:13,  4.30it/s]

 69%|██████▉   | 3547/5153 [13:53<06:14,  4.29it/s]

 69%|██████▉   | 3548/5153 [13:53<06:14,  4.29it/s]

 69%|██████▉   | 3549/5153 [13:54<06:13,  4.29it/s]

 69%|██████▉   | 3550/5153 [13:54<06:14,  4.28it/s]

 69%|██████▉   | 3551/5153 [13:54<06:12,  4.30it/s]

 69%|██████▉   | 3552/5153 [13:54<06:12,  4.30it/s]

 69%|██████▉   | 3553/5153 [13:55<06:12,  4.30it/s]

 69%|██████▉   | 3554/5153 [13:55<06:13,  4.28it/s]

 69%|██████▉   | 3555/5153 [13:55<06:14,  4.27it/s]

 69%|██████▉   | 3556/5153 [13:55<06:13,  4.28it/s]

 69%|██████▉   | 3557/5153 [13:56<06:13,  4.28it/s]

 69%|██████▉   | 3558/5153 [13:56<06:12,  4.28it/s]

 69%|██████▉   | 3559/5153 [13:56<06:12,  4.28it/s]

 69%|██████▉   | 3560/5153 [13:56<06:12,  4.28it/s]

 69%|██████▉   | 3561/5153 [13:57<06:11,  4.28it/s]

 69%|██████▉   | 3562/5153 [13:57<06:10,  4.29it/s]

 69%|██████▉   | 3563/5153 [13:57<06:10,  4.29it/s]

 69%|██████▉   | 3564/5153 [13:57<06:09,  4.30it/s]

 69%|██████▉   | 3565/5153 [13:57<06:09,  4.30it/s]

 69%|██████▉   | 3566/5153 [13:58<06:08,  4.30it/s]

 69%|██████▉   | 3567/5153 [13:58<06:08,  4.30it/s]

 69%|██████▉   | 3568/5153 [13:58<06:08,  4.30it/s]

 69%|██████▉   | 3569/5153 [13:58<06:08,  4.30it/s]

 69%|██████▉   | 3570/5153 [13:59<06:07,  4.30it/s]

 69%|██████▉   | 3571/5153 [13:59<06:07,  4.30it/s]

 69%|██████▉   | 3572/5153 [13:59<06:07,  4.30it/s]

 69%|██████▉   | 3573/5153 [13:59<06:07,  4.30it/s]

 69%|██████▉   | 3574/5153 [14:00<06:07,  4.30it/s]

 69%|██████▉   | 3575/5153 [14:00<06:07,  4.29it/s]

 69%|██████▉   | 3576/5153 [14:00<06:08,  4.28it/s]

 69%|██████▉   | 3577/5153 [14:00<06:07,  4.28it/s]

 69%|██████▉   | 3578/5153 [14:00<06:07,  4.29it/s]

 69%|██████▉   | 3579/5153 [14:01<06:07,  4.29it/s]

 69%|██████▉   | 3580/5153 [14:01<06:06,  4.29it/s]

 69%|██████▉   | 3581/5153 [14:01<06:06,  4.29it/s]

 70%|██████▉   | 3582/5153 [14:01<06:05,  4.29it/s]

 70%|██████▉   | 3583/5153 [14:02<06:06,  4.29it/s]

 70%|██████▉   | 3584/5153 [14:02<06:05,  4.29it/s]

 70%|██████▉   | 3585/5153 [14:02<06:04,  4.30it/s]

 70%|██████▉   | 3586/5153 [14:02<06:04,  4.30it/s]

 70%|██████▉   | 3587/5153 [14:03<06:04,  4.30it/s]

 70%|██████▉   | 3588/5153 [14:03<06:04,  4.29it/s]

 70%|██████▉   | 3589/5153 [14:03<06:03,  4.30it/s]

 70%|██████▉   | 3590/5153 [14:03<06:05,  4.28it/s]

 70%|██████▉   | 3591/5153 [14:04<06:04,  4.28it/s]

 70%|██████▉   | 3592/5153 [14:04<06:03,  4.29it/s]

 70%|██████▉   | 3593/5153 [14:04<06:03,  4.30it/s]

 70%|██████▉   | 3594/5153 [14:04<06:02,  4.31it/s]

 70%|██████▉   | 3595/5153 [14:04<06:01,  4.31it/s]

 70%|██████▉   | 3596/5153 [14:05<06:01,  4.30it/s]

 70%|██████▉   | 3597/5153 [14:05<06:02,  4.29it/s]

 70%|██████▉   | 3598/5153 [14:05<06:02,  4.29it/s]

 70%|██████▉   | 3599/5153 [14:05<06:02,  4.28it/s]

 70%|██████▉   | 3600/5153 [14:06<06:02,  4.28it/s]

 70%|██████▉   | 3601/5153 [14:06<06:03,  4.27it/s]

 70%|██████▉   | 3602/5153 [14:06<06:02,  4.27it/s]

 70%|██████▉   | 3603/5153 [14:06<06:02,  4.27it/s]

 70%|██████▉   | 3604/5153 [14:07<06:02,  4.27it/s]

 70%|██████▉   | 3605/5153 [14:07<06:01,  4.28it/s]

 70%|██████▉   | 3606/5153 [14:07<06:01,  4.28it/s]

 70%|██████▉   | 3607/5153 [14:07<06:00,  4.29it/s]

 70%|███████   | 3608/5153 [14:07<06:01,  4.28it/s]

 70%|███████   | 3609/5153 [14:08<06:01,  4.27it/s]

 70%|███████   | 3610/5153 [14:08<06:01,  4.27it/s]

 70%|███████   | 3611/5153 [14:08<06:02,  4.26it/s]

 70%|███████   | 3612/5153 [14:08<06:01,  4.26it/s]

 70%|███████   | 3613/5153 [14:09<06:01,  4.27it/s]

 70%|███████   | 3614/5153 [14:09<06:00,  4.27it/s]

 70%|███████   | 3615/5153 [14:09<05:59,  4.27it/s]

 70%|███████   | 3616/5153 [14:09<06:00,  4.27it/s]

 70%|███████   | 3617/5153 [14:10<06:00,  4.26it/s]

 70%|███████   | 3618/5153 [14:10<06:00,  4.26it/s]

 70%|███████   | 3619/5153 [14:10<05:59,  4.26it/s]

 70%|███████   | 3620/5153 [14:10<05:58,  4.28it/s]

 70%|███████   | 3621/5153 [14:11<05:57,  4.28it/s]

 70%|███████   | 3622/5153 [14:11<05:57,  4.28it/s]

 70%|███████   | 3623/5153 [14:11<05:57,  4.28it/s]

 70%|███████   | 3624/5153 [14:11<05:56,  4.28it/s]

 70%|███████   | 3625/5153 [14:11<05:56,  4.28it/s]

 70%|███████   | 3626/5153 [14:12<05:56,  4.28it/s]

 70%|███████   | 3627/5153 [14:12<05:57,  4.27it/s]

 70%|███████   | 3628/5153 [14:12<05:56,  4.28it/s]

 70%|███████   | 3629/5153 [14:12<05:56,  4.27it/s]

 70%|███████   | 3630/5153 [14:13<05:56,  4.27it/s]

 70%|███████   | 3631/5153 [14:13<05:55,  4.28it/s]

 70%|███████   | 3632/5153 [14:13<05:55,  4.28it/s]

 71%|███████   | 3633/5153 [14:13<05:55,  4.28it/s]

 71%|███████   | 3634/5153 [14:14<05:55,  4.27it/s]

 71%|███████   | 3635/5153 [14:14<05:55,  4.27it/s]

 71%|███████   | 3636/5153 [14:14<05:55,  4.27it/s]

 71%|███████   | 3637/5153 [14:14<05:54,  4.27it/s]

 71%|███████   | 3638/5153 [14:15<05:53,  4.28it/s]

 71%|███████   | 3639/5153 [14:15<05:53,  4.28it/s]

 71%|███████   | 3640/5153 [14:15<05:53,  4.28it/s]

 71%|███████   | 3641/5153 [14:15<05:53,  4.27it/s]

 71%|███████   | 3642/5153 [14:15<05:54,  4.26it/s]

 71%|███████   | 3643/5153 [14:16<05:53,  4.27it/s]

 71%|███████   | 3644/5153 [14:16<05:53,  4.27it/s]

 71%|███████   | 3645/5153 [14:16<05:56,  4.23it/s]

 71%|███████   | 3646/5153 [14:16<05:54,  4.26it/s]

 71%|███████   | 3647/5153 [14:17<05:53,  4.26it/s]

 71%|███████   | 3648/5153 [14:17<05:53,  4.26it/s]

 71%|███████   | 3649/5153 [14:17<05:52,  4.26it/s]

 71%|███████   | 3650/5153 [14:17<05:52,  4.27it/s]

 71%|███████   | 3651/5153 [14:18<05:52,  4.26it/s]

 71%|███████   | 3652/5153 [14:18<05:52,  4.26it/s]

 71%|███████   | 3653/5153 [14:18<05:51,  4.26it/s]

 71%|███████   | 3654/5153 [14:18<05:51,  4.27it/s]

 71%|███████   | 3655/5153 [14:18<05:51,  4.26it/s]

 71%|███████   | 3656/5153 [14:19<05:51,  4.26it/s]

 71%|███████   | 3657/5153 [14:19<05:51,  4.25it/s]

 71%|███████   | 3658/5153 [14:19<05:50,  4.26it/s]

 71%|███████   | 3659/5153 [14:19<05:50,  4.26it/s]

 71%|███████   | 3660/5153 [14:20<05:51,  4.24it/s]

 71%|███████   | 3661/5153 [14:20<05:51,  4.25it/s]

 71%|███████   | 3662/5153 [14:20<05:50,  4.25it/s]

 71%|███████   | 3663/5153 [14:20<05:49,  4.27it/s]

 71%|███████   | 3664/5153 [14:21<05:49,  4.26it/s]

 71%|███████   | 3665/5153 [14:21<05:48,  4.27it/s]

 71%|███████   | 3666/5153 [14:21<05:49,  4.26it/s]

 71%|███████   | 3667/5153 [14:21<05:49,  4.25it/s]

 71%|███████   | 3668/5153 [14:22<05:48,  4.26it/s]

 71%|███████   | 3669/5153 [14:22<05:49,  4.25it/s]

 71%|███████   | 3670/5153 [14:22<05:50,  4.24it/s]

 71%|███████   | 3671/5153 [14:22<05:49,  4.24it/s]

 71%|███████▏  | 3672/5153 [14:22<05:49,  4.24it/s]

 71%|███████▏  | 3673/5153 [14:23<05:48,  4.25it/s]

 71%|███████▏  | 3674/5153 [14:23<05:47,  4.25it/s]

 71%|███████▏  | 3675/5153 [14:23<05:47,  4.26it/s]

 71%|███████▏  | 3676/5153 [14:23<05:46,  4.26it/s]

 71%|███████▏  | 3677/5153 [14:24<05:46,  4.26it/s]

 71%|███████▏  | 3678/5153 [14:24<05:45,  4.26it/s]

 71%|███████▏  | 3679/5153 [14:24<05:46,  4.26it/s]

 71%|███████▏  | 3680/5153 [14:24<05:47,  4.24it/s]

 71%|███████▏  | 3681/5153 [14:25<05:46,  4.25it/s]

 71%|███████▏  | 3682/5153 [14:25<05:45,  4.26it/s]

 71%|███████▏  | 3683/5153 [14:25<05:45,  4.25it/s]

 71%|███████▏  | 3684/5153 [14:25<05:45,  4.25it/s]

 72%|███████▏  | 3685/5153 [14:26<05:46,  4.24it/s]

 72%|███████▏  | 3686/5153 [14:26<05:45,  4.25it/s]

 72%|███████▏  | 3687/5153 [14:26<05:46,  4.24it/s]

 72%|███████▏  | 3688/5153 [14:26<05:44,  4.25it/s]

 72%|███████▏  | 3689/5153 [14:26<05:44,  4.24it/s]

 72%|███████▏  | 3690/5153 [14:27<05:45,  4.24it/s]

 72%|███████▏  | 3691/5153 [14:27<05:44,  4.25it/s]

 72%|███████▏  | 3692/5153 [14:27<05:44,  4.25it/s]

 72%|███████▏  | 3693/5153 [14:27<05:43,  4.25it/s]

 72%|███████▏  | 3694/5153 [14:28<05:43,  4.25it/s]

 72%|███████▏  | 3695/5153 [14:28<05:42,  4.26it/s]

 72%|███████▏  | 3696/5153 [14:28<05:42,  4.26it/s]

 72%|███████▏  | 3697/5153 [14:28<05:42,  4.25it/s]

 72%|███████▏  | 3698/5153 [14:29<05:42,  4.25it/s]

 72%|███████▏  | 3699/5153 [14:29<05:41,  4.25it/s]

 72%|███████▏  | 3700/5153 [14:29<05:42,  4.24it/s]

 72%|███████▏  | 3701/5153 [14:29<05:42,  4.24it/s]

 72%|███████▏  | 3702/5153 [14:30<05:41,  4.25it/s]

 72%|███████▏  | 3703/5153 [14:30<05:40,  4.26it/s]

 72%|███████▏  | 3704/5153 [14:30<05:40,  4.25it/s]

 72%|███████▏  | 3705/5153 [14:30<05:40,  4.26it/s]

 72%|███████▏  | 3706/5153 [14:30<05:39,  4.26it/s]

 72%|███████▏  | 3707/5153 [14:31<05:39,  4.25it/s]

 72%|███████▏  | 3708/5153 [14:31<05:39,  4.26it/s]

 72%|███████▏  | 3709/5153 [14:31<05:39,  4.25it/s]

 72%|███████▏  | 3710/5153 [14:31<05:39,  4.25it/s]

 72%|███████▏  | 3711/5153 [14:32<05:40,  4.24it/s]

 72%|███████▏  | 3712/5153 [14:32<05:40,  4.23it/s]

 72%|███████▏  | 3713/5153 [14:32<05:38,  4.25it/s]

 72%|███████▏  | 3714/5153 [14:32<05:37,  4.26it/s]

 72%|███████▏  | 3715/5153 [14:33<05:37,  4.26it/s]

 72%|███████▏  | 3716/5153 [14:33<05:38,  4.25it/s]

 72%|███████▏  | 3717/5153 [14:33<05:38,  4.25it/s]

 72%|███████▏  | 3718/5153 [14:33<05:38,  4.24it/s]

 72%|███████▏  | 3719/5153 [14:34<05:38,  4.24it/s]

 72%|███████▏  | 3720/5153 [14:34<05:37,  4.25it/s]

 72%|███████▏  | 3721/5153 [14:34<05:36,  4.26it/s]

 72%|███████▏  | 3722/5153 [14:34<05:36,  4.25it/s]

 72%|███████▏  | 3723/5153 [14:34<05:36,  4.25it/s]

 72%|███████▏  | 3724/5153 [14:35<05:36,  4.25it/s]

 72%|███████▏  | 3725/5153 [14:35<05:36,  4.25it/s]

 72%|███████▏  | 3726/5153 [14:35<05:36,  4.24it/s]

 72%|███████▏  | 3727/5153 [14:35<05:36,  4.24it/s]

 72%|███████▏  | 3728/5153 [14:36<05:36,  4.24it/s]

 72%|███████▏  | 3729/5153 [14:36<05:36,  4.24it/s]

 72%|███████▏  | 3730/5153 [14:36<05:35,  4.24it/s]

 72%|███████▏  | 3731/5153 [14:36<05:34,  4.25it/s]

 72%|███████▏  | 3732/5153 [14:37<05:34,  4.25it/s]

 72%|███████▏  | 3733/5153 [14:37<05:34,  4.25it/s]

 72%|███████▏  | 3734/5153 [14:37<05:34,  4.25it/s]

 72%|███████▏  | 3735/5153 [14:37<05:33,  4.26it/s]

 73%|███████▎  | 3736/5153 [14:38<05:33,  4.25it/s]

 73%|███████▎  | 3737/5153 [14:38<05:32,  4.25it/s]

 73%|███████▎  | 3738/5153 [14:38<05:33,  4.25it/s]

 73%|███████▎  | 3739/5153 [14:38<05:32,  4.25it/s]

 73%|███████▎  | 3740/5153 [14:38<05:32,  4.25it/s]

 73%|███████▎  | 3741/5153 [14:39<05:32,  4.24it/s]

 73%|███████▎  | 3742/5153 [14:39<05:32,  4.25it/s]

 73%|███████▎  | 3743/5153 [14:39<05:32,  4.24it/s]

 73%|███████▎  | 3744/5153 [14:39<05:32,  4.23it/s]

 73%|███████▎  | 3745/5153 [14:40<05:31,  4.24it/s]

 73%|███████▎  | 3746/5153 [14:40<05:32,  4.24it/s]

 73%|███████▎  | 3747/5153 [14:40<05:32,  4.23it/s]

 73%|███████▎  | 3748/5153 [14:40<05:32,  4.23it/s]

 73%|███████▎  | 3749/5153 [14:41<05:32,  4.23it/s]

 73%|███████▎  | 3750/5153 [14:41<05:32,  4.22it/s]

 73%|███████▎  | 3751/5153 [14:41<05:32,  4.22it/s]

 73%|███████▎  | 3752/5153 [14:41<05:30,  4.24it/s]

 73%|███████▎  | 3753/5153 [14:42<05:30,  4.24it/s]

 73%|███████▎  | 3754/5153 [14:42<05:33,  4.19it/s]

 73%|███████▎  | 3755/5153 [14:42<05:32,  4.21it/s]

logging
logging the anndata

 73%|███████▎  | 3756/5153 [14:44<14:04,  1.65it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 73%|███████▎  | 3757/5153 [14:44<11:26,  2.03it/s]

 73%|███████▎  | 3758/5153 [14:44<09:36,  2.42it/s]

 73%|███████▎  | 3759/5153 [14:44<08:18,  2.80it/s]

 73%|███████▎  | 3760/5153 [14:44<07:24,  3.14it/s]

 73%|███████▎  | 3761/5153 [14:45<06:46,  3.42it/s]

 73%|███████▎  | 3762/5153 [14:45<06:19,  3.66it/s]

 73%|███████▎  | 3763/5153 [14:45<06:01,  3.85it/s]

 73%|███████▎  | 3764/5153 [14:45<05:48,  3.99it/s]

 73%|███████▎  | 3765/5153 [14:46<05:39,  4.09it/s]

 73%|███████▎  | 3766/5153 [14:46<05:33,  4.16it/s]

 73%|███████▎  | 3767/5153 [14:46<05:27,  4.23it/s]

 73%|███████▎  | 3768/5153 [14:46<05:24,  4.27it/s]

 73%|███████▎  | 3769/5153 [14:46<05:22,  4.29it/s]

 73%|███████▎  | 3770/5153 [14:47<05:20,  4.31it/s]

 73%|███████▎  | 3771/5153 [14:47<05:19,  4.32it/s]

 73%|███████▎  | 3772/5153 [14:47<05:19,  4.32it/s]

 73%|███████▎  | 3773/5153 [14:47<05:18,  4.33it/s]

 73%|███████▎  | 3774/5153 [14:48<05:17,  4.34it/s]

 73%|███████▎  | 3775/5153 [14:48<05:17,  4.34it/s]

 73%|███████▎  | 3776/5153 [14:48<05:17,  4.34it/s]

 73%|███████▎  | 3777/5153 [14:48<05:16,  4.34it/s]

 73%|███████▎  | 3778/5153 [14:49<05:15,  4.36it/s]

 73%|███████▎  | 3779/5153 [14:49<05:15,  4.36it/s]

 73%|███████▎  | 3780/5153 [14:49<05:15,  4.36it/s]

 73%|███████▎  | 3781/5153 [14:49<05:15,  4.35it/s]

 73%|███████▎  | 3782/5153 [14:49<05:15,  4.34it/s]

 73%|███████▎  | 3783/5153 [14:50<05:14,  4.35it/s]

 73%|███████▎  | 3784/5153 [14:50<05:14,  4.35it/s]

 73%|███████▎  | 3785/5153 [14:50<05:14,  4.35it/s]

 73%|███████▎  | 3786/5153 [14:50<05:13,  4.36it/s]

 73%|███████▎  | 3787/5153 [14:51<05:13,  4.36it/s]

 74%|███████▎  | 3788/5153 [14:51<05:13,  4.36it/s]

 74%|███████▎  | 3789/5153 [14:51<05:12,  4.36it/s]

 74%|███████▎  | 3790/5153 [14:51<05:12,  4.35it/s]

 74%|███████▎  | 3791/5153 [14:52<05:13,  4.34it/s]

 74%|███████▎  | 3792/5153 [14:52<05:12,  4.35it/s]

 74%|███████▎  | 3793/5153 [14:52<05:12,  4.35it/s]

 74%|███████▎  | 3794/5153 [14:52<05:12,  4.34it/s]

 74%|███████▎  | 3795/5153 [14:52<05:11,  4.35it/s]

 74%|███████▎  | 3796/5153 [14:53<05:12,  4.35it/s]

 74%|███████▎  | 3797/5153 [14:53<05:11,  4.35it/s]

 74%|███████▎  | 3798/5153 [14:53<05:12,  4.34it/s]

 74%|███████▎  | 3799/5153 [14:53<05:11,  4.34it/s]

 74%|███████▎  | 3800/5153 [14:54<05:11,  4.35it/s]

 74%|███████▍  | 3801/5153 [14:54<05:10,  4.35it/s]

 74%|███████▍  | 3802/5153 [14:54<05:10,  4.35it/s]

 74%|███████▍  | 3803/5153 [14:54<05:10,  4.35it/s]

 74%|███████▍  | 3804/5153 [14:55<05:10,  4.35it/s]

 74%|███████▍  | 3805/5153 [14:55<05:10,  4.34it/s]

 74%|███████▍  | 3806/5153 [14:55<05:09,  4.35it/s]

 74%|███████▍  | 3807/5153 [14:55<05:09,  4.34it/s]

 74%|███████▍  | 3808/5153 [14:55<05:09,  4.35it/s]

 74%|███████▍  | 3809/5153 [14:56<05:09,  4.34it/s]

 74%|███████▍  | 3810/5153 [14:56<05:09,  4.34it/s]

 74%|███████▍  | 3811/5153 [14:56<05:08,  4.35it/s]

 74%|███████▍  | 3812/5153 [14:56<05:08,  4.35it/s]

 74%|███████▍  | 3813/5153 [14:57<05:08,  4.35it/s]

 74%|███████▍  | 3814/5153 [14:57<05:07,  4.35it/s]

 74%|███████▍  | 3815/5153 [14:57<05:07,  4.35it/s]

 74%|███████▍  | 3816/5153 [14:57<05:08,  4.34it/s]

 74%|███████▍  | 3817/5153 [14:58<05:07,  4.35it/s]

 74%|███████▍  | 3818/5153 [14:58<05:06,  4.35it/s]

 74%|███████▍  | 3819/5153 [14:58<05:06,  4.35it/s]

 74%|███████▍  | 3820/5153 [14:58<05:06,  4.35it/s]

 74%|███████▍  | 3821/5153 [14:58<05:06,  4.34it/s]

 74%|███████▍  | 3822/5153 [14:59<05:06,  4.34it/s]

 74%|███████▍  | 3823/5153 [14:59<05:06,  4.34it/s]

 74%|███████▍  | 3824/5153 [14:59<05:06,  4.34it/s]

 74%|███████▍  | 3825/5153 [14:59<05:06,  4.34it/s]

 74%|███████▍  | 3826/5153 [15:00<05:05,  4.34it/s]

 74%|███████▍  | 3827/5153 [15:00<05:05,  4.34it/s]

 74%|███████▍  | 3828/5153 [15:00<05:04,  4.35it/s]

 74%|███████▍  | 3829/5153 [15:00<05:04,  4.35it/s]

 74%|███████▍  | 3830/5153 [15:01<05:03,  4.36it/s]

 74%|███████▍  | 3831/5153 [15:01<05:04,  4.35it/s]

 74%|███████▍  | 3832/5153 [15:01<05:03,  4.36it/s]

 74%|███████▍  | 3833/5153 [15:01<05:02,  4.36it/s]

 74%|███████▍  | 3834/5153 [15:01<05:03,  4.35it/s]

 74%|███████▍  | 3835/5153 [15:02<05:02,  4.36it/s]

 74%|███████▍  | 3836/5153 [15:02<05:02,  4.36it/s]

 74%|███████▍  | 3837/5153 [15:02<05:01,  4.36it/s]

 74%|███████▍  | 3838/5153 [15:02<05:01,  4.36it/s]

 75%|███████▍  | 3839/5153 [15:03<05:01,  4.36it/s]

 75%|███████▍  | 3840/5153 [15:03<05:00,  4.37it/s]

 75%|███████▍  | 3841/5153 [15:03<05:00,  4.37it/s]

 75%|███████▍  | 3842/5153 [15:03<05:00,  4.36it/s]

 75%|███████▍  | 3843/5153 [15:04<05:00,  4.36it/s]

 75%|███████▍  | 3844/5153 [15:04<05:00,  4.35it/s]

 75%|███████▍  | 3845/5153 [15:04<05:00,  4.35it/s]

 75%|███████▍  | 3846/5153 [15:04<05:00,  4.34it/s]

 75%|███████▍  | 3847/5153 [15:04<05:00,  4.35it/s]

 75%|███████▍  | 3848/5153 [15:05<04:59,  4.35it/s]

 75%|███████▍  | 3849/5153 [15:05<04:59,  4.35it/s]

 75%|███████▍  | 3850/5153 [15:05<04:59,  4.35it/s]

 75%|███████▍  | 3851/5153 [15:05<04:59,  4.35it/s]

 75%|███████▍  | 3852/5153 [15:06<04:59,  4.35it/s]

 75%|███████▍  | 3853/5153 [15:06<04:59,  4.35it/s]

 75%|███████▍  | 3854/5153 [15:06<04:58,  4.35it/s]

 75%|███████▍  | 3855/5153 [15:06<04:58,  4.35it/s]

 75%|███████▍  | 3856/5153 [15:06<04:57,  4.35it/s]

 75%|███████▍  | 3857/5153 [15:07<04:57,  4.36it/s]

 75%|███████▍  | 3858/5153 [15:07<04:57,  4.36it/s]

 75%|███████▍  | 3859/5153 [15:07<04:57,  4.35it/s]

 75%|███████▍  | 3860/5153 [15:07<04:57,  4.34it/s]

 75%|███████▍  | 3861/5153 [15:08<04:56,  4.35it/s]

 75%|███████▍  | 3862/5153 [15:08<04:57,  4.34it/s]

 75%|███████▍  | 3863/5153 [15:08<04:58,  4.33it/s]

 75%|███████▍  | 3864/5153 [15:08<04:57,  4.33it/s]

 75%|███████▌  | 3865/5153 [15:09<04:57,  4.33it/s]

 75%|███████▌  | 3866/5153 [15:09<04:56,  4.33it/s]

 75%|███████▌  | 3867/5153 [15:09<04:55,  4.35it/s]

 75%|███████▌  | 3868/5153 [15:09<04:55,  4.35it/s]

 75%|███████▌  | 3869/5153 [15:09<04:55,  4.34it/s]

 75%|███████▌  | 3870/5153 [15:10<04:55,  4.34it/s]

 75%|███████▌  | 3871/5153 [15:10<04:55,  4.33it/s]

 75%|███████▌  | 3872/5153 [15:10<04:55,  4.34it/s]

 75%|███████▌  | 3873/5153 [15:10<04:55,  4.33it/s]

 75%|███████▌  | 3874/5153 [15:11<04:55,  4.33it/s]

 75%|███████▌  | 3875/5153 [15:11<04:54,  4.33it/s]

 75%|███████▌  | 3876/5153 [15:11<04:55,  4.33it/s]

 75%|███████▌  | 3877/5153 [15:11<04:54,  4.33it/s]

 75%|███████▌  | 3878/5153 [15:12<04:54,  4.33it/s]

 75%|███████▌  | 3879/5153 [15:12<04:53,  4.34it/s]

 75%|███████▌  | 3880/5153 [15:12<04:52,  4.35it/s]

 75%|███████▌  | 3881/5153 [15:12<04:52,  4.35it/s]

 75%|███████▌  | 3882/5153 [15:12<04:51,  4.35it/s]

 75%|███████▌  | 3883/5153 [15:13<04:51,  4.35it/s]

 75%|███████▌  | 3884/5153 [15:13<04:52,  4.34it/s]

 75%|███████▌  | 3885/5153 [15:13<04:52,  4.34it/s]

 75%|███████▌  | 3886/5153 [15:13<04:52,  4.34it/s]

 75%|███████▌  | 3887/5153 [15:14<04:51,  4.34it/s]

 75%|███████▌  | 3888/5153 [15:14<04:51,  4.34it/s]

 75%|███████▌  | 3889/5153 [15:14<04:51,  4.34it/s]

 75%|███████▌  | 3890/5153 [15:14<04:51,  4.33it/s]

 76%|███████▌  | 3891/5153 [15:15<04:50,  4.34it/s]

 76%|███████▌  | 3892/5153 [15:15<04:50,  4.34it/s]

 76%|███████▌  | 3893/5153 [15:15<04:50,  4.34it/s]

 76%|███████▌  | 3894/5153 [15:15<04:50,  4.33it/s]

 76%|███████▌  | 3895/5153 [15:15<04:50,  4.32it/s]

 76%|███████▌  | 3896/5153 [15:16<04:50,  4.33it/s]

 76%|███████▌  | 3897/5153 [15:16<04:49,  4.33it/s]

 76%|███████▌  | 3898/5153 [15:16<04:49,  4.33it/s]

 76%|███████▌  | 3899/5153 [15:16<04:49,  4.34it/s]

 76%|███████▌  | 3900/5153 [15:17<04:49,  4.33it/s]

 76%|███████▌  | 3901/5153 [15:17<04:49,  4.33it/s]

 76%|███████▌  | 3902/5153 [15:17<04:49,  4.32it/s]

 76%|███████▌  | 3903/5153 [15:17<04:48,  4.33it/s]

 76%|███████▌  | 3904/5153 [15:18<04:48,  4.33it/s]

 76%|███████▌  | 3905/5153 [15:18<04:48,  4.33it/s]

 76%|███████▌  | 3906/5153 [15:18<04:48,  4.32it/s]

 76%|███████▌  | 3907/5153 [15:18<04:48,  4.33it/s]

 76%|███████▌  | 3908/5153 [15:18<04:47,  4.33it/s]

 76%|███████▌  | 3909/5153 [15:19<04:46,  4.34it/s]

 76%|███████▌  | 3910/5153 [15:19<04:46,  4.34it/s]

 76%|███████▌  | 3911/5153 [15:19<04:46,  4.33it/s]

 76%|███████▌  | 3912/5153 [15:19<04:46,  4.34it/s]

 76%|███████▌  | 3913/5153 [15:20<04:46,  4.33it/s]

 76%|███████▌  | 3914/5153 [15:20<04:46,  4.33it/s]

 76%|███████▌  | 3915/5153 [15:20<04:45,  4.34it/s]

 76%|███████▌  | 3916/5153 [15:20<04:44,  4.34it/s]

 76%|███████▌  | 3917/5153 [15:21<04:45,  4.33it/s]

 76%|███████▌  | 3918/5153 [15:21<04:45,  4.32it/s]

 76%|███████▌  | 3919/5153 [15:21<04:45,  4.32it/s]

 76%|███████▌  | 3920/5153 [15:21<04:44,  4.33it/s]

 76%|███████▌  | 3921/5153 [15:21<04:44,  4.33it/s]

 76%|███████▌  | 3922/5153 [15:22<04:43,  4.34it/s]

 76%|███████▌  | 3923/5153 [15:22<04:43,  4.34it/s]

 76%|███████▌  | 3924/5153 [15:22<04:43,  4.33it/s]

 76%|███████▌  | 3925/5153 [15:22<04:43,  4.33it/s]

 76%|███████▌  | 3926/5153 [15:23<04:43,  4.33it/s]

 76%|███████▌  | 3927/5153 [15:23<04:43,  4.33it/s]

 76%|███████▌  | 3928/5153 [15:23<04:42,  4.33it/s]

 76%|███████▌  | 3929/5153 [15:23<04:42,  4.33it/s]

 76%|███████▋  | 3930/5153 [15:24<04:42,  4.33it/s]

 76%|███████▋  | 3931/5153 [15:24<04:42,  4.32it/s]

 76%|███████▋  | 3932/5153 [15:24<04:42,  4.32it/s]

 76%|███████▋  | 3933/5153 [15:24<04:41,  4.33it/s]

 76%|███████▋  | 3934/5153 [15:24<04:41,  4.32it/s]

 76%|███████▋  | 3935/5153 [15:25<04:41,  4.33it/s]

 76%|███████▋  | 3936/5153 [15:25<04:40,  4.33it/s]

 76%|███████▋  | 3937/5153 [15:25<04:41,  4.32it/s]

 76%|███████▋  | 3938/5153 [15:25<04:40,  4.33it/s]

 76%|███████▋  | 3939/5153 [15:26<04:40,  4.33it/s]

 76%|███████▋  | 3940/5153 [15:26<04:40,  4.32it/s]

 76%|███████▋  | 3941/5153 [15:26<04:39,  4.33it/s]

 76%|███████▋  | 3942/5153 [15:26<04:39,  4.33it/s]

 77%|███████▋  | 3943/5153 [15:27<04:39,  4.33it/s]

 77%|███████▋  | 3944/5153 [15:27<04:39,  4.33it/s]

 77%|███████▋  | 3945/5153 [15:27<04:39,  4.32it/s]

 77%|███████▋  | 3946/5153 [15:27<04:39,  4.32it/s]

 77%|███████▋  | 3947/5153 [15:27<04:38,  4.33it/s]

 77%|███████▋  | 3948/5153 [15:28<04:38,  4.32it/s]

 77%|███████▋  | 3949/5153 [15:28<04:38,  4.33it/s]

 77%|███████▋  | 3950/5153 [15:28<04:38,  4.32it/s]

 77%|███████▋  | 3951/5153 [15:28<04:38,  4.32it/s]

 77%|███████▋  | 3952/5153 [15:29<04:38,  4.32it/s]

 77%|███████▋  | 3953/5153 [15:29<04:37,  4.32it/s]

 77%|███████▋  | 3954/5153 [15:29<04:37,  4.32it/s]

 77%|███████▋  | 3955/5153 [15:29<04:37,  4.32it/s]

 77%|███████▋  | 3956/5153 [15:30<04:37,  4.32it/s]

 77%|███████▋  | 3957/5153 [15:30<04:36,  4.33it/s]

 77%|███████▋  | 3958/5153 [15:30<04:36,  4.33it/s]

 77%|███████▋  | 3959/5153 [15:30<04:35,  4.33it/s]

 77%|███████▋  | 3960/5153 [15:30<04:35,  4.33it/s]

 77%|███████▋  | 3961/5153 [15:31<04:35,  4.33it/s]

 77%|███████▋  | 3962/5153 [15:31<04:35,  4.33it/s]

 77%|███████▋  | 3963/5153 [15:31<04:35,  4.33it/s]

 77%|███████▋  | 3964/5153 [15:31<04:35,  4.32it/s]

 77%|███████▋  | 3965/5153 [15:32<04:34,  4.33it/s]

 77%|███████▋  | 3966/5153 [15:32<04:34,  4.33it/s]

 77%|███████▋  | 3967/5153 [15:32<04:34,  4.32it/s]

 77%|███████▋  | 3968/5153 [15:32<04:33,  4.33it/s]

 77%|███████▋  | 3969/5153 [15:33<04:33,  4.33it/s]

 77%|███████▋  | 3970/5153 [15:33<04:32,  4.33it/s]

 77%|███████▋  | 3971/5153 [15:33<04:32,  4.33it/s]

 77%|███████▋  | 3972/5153 [15:33<04:32,  4.33it/s]

 77%|███████▋  | 3973/5153 [15:34<04:32,  4.34it/s]

 77%|███████▋  | 3974/5153 [15:34<04:31,  4.33it/s]

 77%|███████▋  | 3975/5153 [15:34<04:31,  4.33it/s]

 77%|███████▋  | 3976/5153 [15:34<04:31,  4.34it/s]

 77%|███████▋  | 3977/5153 [15:34<04:31,  4.33it/s]

 77%|███████▋  | 3978/5153 [15:35<04:31,  4.32it/s]

 77%|███████▋  | 3979/5153 [15:35<04:31,  4.32it/s]

 77%|███████▋  | 3980/5153 [15:35<04:31,  4.33it/s]

 77%|███████▋  | 3981/5153 [15:35<04:30,  4.33it/s]

 77%|███████▋  | 3982/5153 [15:36<04:30,  4.33it/s]

 77%|███████▋  | 3983/5153 [15:36<04:30,  4.33it/s]

 77%|███████▋  | 3984/5153 [15:36<04:29,  4.33it/s]

 77%|███████▋  | 3985/5153 [15:36<04:29,  4.33it/s]

 77%|███████▋  | 3986/5153 [15:37<04:29,  4.33it/s]

 77%|███████▋  | 3987/5153 [15:37<04:29,  4.33it/s]

 77%|███████▋  | 3988/5153 [15:37<04:29,  4.33it/s]

 77%|███████▋  | 3989/5153 [15:37<04:28,  4.33it/s]

 77%|███████▋  | 3990/5153 [15:37<04:28,  4.32it/s]

 77%|███████▋  | 3991/5153 [15:38<04:32,  4.26it/s]

 77%|███████▋  | 3992/5153 [15:38<04:30,  4.29it/s]

 77%|███████▋  | 3993/5153 [15:38<04:30,  4.29it/s]

 78%|███████▊  | 3994/5153 [15:38<04:29,  4.30it/s]

 78%|███████▊  | 3995/5153 [15:39<04:28,  4.31it/s]

 78%|███████▊  | 3996/5153 [15:39<04:28,  4.31it/s]

 78%|███████▊  | 3997/5153 [15:39<04:27,  4.32it/s]

 78%|███████▊  | 3998/5153 [15:39<04:27,  4.32it/s]

 78%|███████▊  | 3999/5153 [15:40<04:27,  4.32it/s]

 78%|███████▊  | 4000/5153 [15:40<04:26,  4.32it/s]

 78%|███████▊  | 4001/5153 [15:40<04:26,  4.32it/s]

 78%|███████▊  | 4002/5153 [15:40<04:26,  4.33it/s]

 78%|███████▊  | 4003/5153 [15:40<04:26,  4.32it/s]

 78%|███████▊  | 4004/5153 [15:41<04:26,  4.31it/s]

 78%|███████▊  | 4005/5153 [15:41<04:25,  4.33it/s]

 78%|███████▊  | 4006/5153 [15:41<04:25,  4.33it/s]

 78%|███████▊  | 4007/5153 [15:41<04:24,  4.33it/s]

 78%|███████▊  | 4008/5153 [15:42<04:24,  4.33it/s]

 78%|███████▊  | 4009/5153 [15:42<04:24,  4.32it/s]

 78%|███████▊  | 4010/5153 [15:42<04:23,  4.33it/s]

 78%|███████▊  | 4011/5153 [15:42<04:24,  4.32it/s]

 78%|███████▊  | 4012/5153 [15:43<04:26,  4.28it/s]

 78%|███████▊  | 4013/5153 [15:43<04:25,  4.30it/s]

 78%|███████▊  | 4014/5153 [15:43<04:24,  4.30it/s]

 78%|███████▊  | 4015/5153 [15:43<04:23,  4.31it/s]

 78%|███████▊  | 4016/5153 [15:43<04:23,  4.31it/s]

 78%|███████▊  | 4017/5153 [15:44<04:22,  4.32it/s]

 78%|███████▊  | 4018/5153 [15:44<04:21,  4.33it/s]

 78%|███████▊  | 4019/5153 [15:44<04:21,  4.34it/s]

 78%|███████▊  | 4020/5153 [15:44<04:22,  4.32it/s]

 78%|███████▊  | 4021/5153 [15:45<04:21,  4.32it/s]

 78%|███████▊  | 4022/5153 [15:45<04:22,  4.32it/s]

 78%|███████▊  | 4023/5153 [15:45<04:21,  4.32it/s]

 78%|███████▊  | 4024/5153 [15:45<04:20,  4.33it/s]

 78%|███████▊  | 4025/5153 [15:46<04:20,  4.32it/s]

 78%|███████▊  | 4026/5153 [15:46<04:20,  4.32it/s]

 78%|███████▊  | 4027/5153 [15:46<04:21,  4.31it/s]

 78%|███████▊  | 4028/5153 [15:46<04:20,  4.31it/s]

 78%|███████▊  | 4029/5153 [15:46<04:20,  4.31it/s]

 78%|███████▊  | 4030/5153 [15:47<04:20,  4.31it/s]

 78%|███████▊  | 4031/5153 [15:47<04:20,  4.31it/s]

 78%|███████▊  | 4032/5153 [15:47<04:19,  4.31it/s]

 78%|███████▊  | 4033/5153 [15:47<04:19,  4.31it/s]

 78%|███████▊  | 4034/5153 [15:48<04:20,  4.29it/s]

 78%|███████▊  | 4035/5153 [15:48<04:20,  4.29it/s]

 78%|███████▊  | 4036/5153 [15:48<04:19,  4.31it/s]

 78%|███████▊  | 4037/5153 [15:48<04:19,  4.30it/s]

 78%|███████▊  | 4038/5153 [15:49<04:18,  4.31it/s]

 78%|███████▊  | 4039/5153 [15:49<04:17,  4.32it/s]

 78%|███████▊  | 4040/5153 [15:49<04:18,  4.31it/s]

 78%|███████▊  | 4041/5153 [15:49<04:17,  4.31it/s]

 78%|███████▊  | 4042/5153 [15:49<04:17,  4.31it/s]

 78%|███████▊  | 4043/5153 [15:50<04:17,  4.31it/s]

 78%|███████▊  | 4044/5153 [15:50<04:16,  4.32it/s]

 78%|███████▊  | 4045/5153 [15:50<04:16,  4.32it/s]

 79%|███████▊  | 4046/5153 [15:50<04:16,  4.32it/s]

 79%|███████▊  | 4047/5153 [15:51<04:15,  4.32it/s]

 79%|███████▊  | 4048/5153 [15:51<04:16,  4.31it/s]

 79%|███████▊  | 4049/5153 [15:51<04:15,  4.32it/s]

 79%|███████▊  | 4050/5153 [15:51<04:15,  4.31it/s]

 79%|███████▊  | 4051/5153 [15:52<04:15,  4.31it/s]

 79%|███████▊  | 4052/5153 [15:52<04:15,  4.31it/s]

 79%|███████▊  | 4053/5153 [15:52<04:14,  4.32it/s]

 79%|███████▊  | 4054/5153 [15:52<04:14,  4.32it/s]

 79%|███████▊  | 4055/5153 [15:52<04:14,  4.32it/s]

 79%|███████▊  | 4056/5153 [15:53<04:14,  4.32it/s]

 79%|███████▊  | 4057/5153 [15:53<04:13,  4.32it/s]

 79%|███████▉  | 4058/5153 [15:53<04:13,  4.32it/s]

 79%|███████▉  | 4059/5153 [15:53<04:13,  4.32it/s]

 79%|███████▉  | 4060/5153 [15:54<04:12,  4.33it/s]

 79%|███████▉  | 4061/5153 [15:54<04:11,  4.34it/s]

 79%|███████▉  | 4062/5153 [15:54<04:11,  4.34it/s]

 79%|███████▉  | 4063/5153 [15:54<04:10,  4.34it/s]

 79%|███████▉  | 4064/5153 [15:55<04:10,  4.34it/s]

 79%|███████▉  | 4065/5153 [15:55<04:10,  4.34it/s]

 79%|███████▉  | 4066/5153 [15:55<04:10,  4.33it/s]

 79%|███████▉  | 4067/5153 [15:55<04:10,  4.33it/s]

 79%|███████▉  | 4068/5153 [15:55<04:10,  4.34it/s]

 79%|███████▉  | 4069/5153 [15:56<04:10,  4.33it/s]

 79%|███████▉  | 4070/5153 [15:56<04:10,  4.33it/s]

 79%|███████▉  | 4071/5153 [15:56<04:09,  4.33it/s]

 79%|███████▉  | 4072/5153 [15:56<04:10,  4.32it/s]

 79%|███████▉  | 4073/5153 [15:57<04:09,  4.33it/s]

 79%|███████▉  | 4074/5153 [15:57<04:09,  4.33it/s]

 79%|███████▉  | 4075/5153 [15:57<04:08,  4.34it/s]

 79%|███████▉  | 4076/5153 [15:57<04:07,  4.34it/s]

 79%|███████▉  | 4077/5153 [15:58<04:07,  4.34it/s]

 79%|███████▉  | 4078/5153 [15:58<04:08,  4.33it/s]

 79%|███████▉  | 4079/5153 [15:58<04:08,  4.32it/s]

 79%|███████▉  | 4080/5153 [15:58<04:08,  4.32it/s]

 79%|███████▉  | 4081/5153 [15:59<04:08,  4.32it/s]

 79%|███████▉  | 4082/5153 [15:59<04:08,  4.31it/s]

 79%|███████▉  | 4083/5153 [15:59<04:09,  4.30it/s]

 79%|███████▉  | 4084/5153 [15:59<04:08,  4.30it/s]

 79%|███████▉  | 4085/5153 [15:59<04:07,  4.31it/s]

 79%|███████▉  | 4086/5153 [16:00<04:07,  4.32it/s]

 79%|███████▉  | 4087/5153 [16:00<04:06,  4.32it/s]

 79%|███████▉  | 4088/5153 [16:00<04:06,  4.32it/s]

 79%|███████▉  | 4089/5153 [16:00<04:07,  4.31it/s]

 79%|███████▉  | 4090/5153 [16:01<04:06,  4.31it/s]

 79%|███████▉  | 4091/5153 [16:01<04:06,  4.30it/s]

 79%|███████▉  | 4092/5153 [16:01<04:05,  4.32it/s]

 79%|███████▉  | 4093/5153 [16:01<04:05,  4.31it/s]

 79%|███████▉  | 4094/5153 [16:02<04:05,  4.31it/s]

 79%|███████▉  | 4095/5153 [16:02<04:05,  4.32it/s]

 79%|███████▉  | 4096/5153 [16:02<04:05,  4.31it/s]

 80%|███████▉  | 4097/5153 [16:02<04:04,  4.32it/s]

 80%|███████▉  | 4098/5153 [16:02<04:04,  4.32it/s]

 80%|███████▉  | 4099/5153 [16:03<04:04,  4.31it/s]

 80%|███████▉  | 4100/5153 [16:03<04:03,  4.32it/s]

 80%|███████▉  | 4101/5153 [16:03<04:03,  4.32it/s]

 80%|███████▉  | 4102/5153 [16:03<04:03,  4.32it/s]

 80%|███████▉  | 4103/5153 [16:04<04:02,  4.32it/s]

 80%|███████▉  | 4104/5153 [16:04<04:02,  4.32it/s]

 80%|███████▉  | 4105/5153 [16:04<04:02,  4.32it/s]

 80%|███████▉  | 4106/5153 [16:04<04:02,  4.32it/s]

 80%|███████▉  | 4107/5153 [16:05<04:02,  4.32it/s]

 80%|███████▉  | 4108/5153 [16:05<04:02,  4.31it/s]

 80%|███████▉  | 4109/5153 [16:05<04:02,  4.31it/s]

 80%|███████▉  | 4110/5153 [16:05<04:01,  4.31it/s]

 80%|███████▉  | 4111/5153 [16:05<04:01,  4.32it/s]

 80%|███████▉  | 4112/5153 [16:06<04:01,  4.31it/s]

 80%|███████▉  | 4113/5153 [16:06<04:01,  4.31it/s]

 80%|███████▉  | 4114/5153 [16:06<04:01,  4.31it/s]

 80%|███████▉  | 4115/5153 [16:06<04:01,  4.31it/s]

 80%|███████▉  | 4116/5153 [16:07<04:00,  4.31it/s]

 80%|███████▉  | 4117/5153 [16:07<04:00,  4.31it/s]

 80%|███████▉  | 4118/5153 [16:07<04:00,  4.31it/s]

 80%|███████▉  | 4119/5153 [16:07<04:00,  4.31it/s]

 80%|███████▉  | 4120/5153 [16:08<03:59,  4.31it/s]

 80%|███████▉  | 4121/5153 [16:08<03:59,  4.31it/s]

 80%|███████▉  | 4122/5153 [16:08<03:59,  4.31it/s]

 80%|████████  | 4123/5153 [16:08<03:59,  4.31it/s]

 80%|████████  | 4124/5153 [16:08<03:59,  4.30it/s]

 80%|████████  | 4125/5153 [16:09<03:58,  4.31it/s]

 80%|████████  | 4126/5153 [16:09<03:58,  4.31it/s]

 80%|████████  | 4127/5153 [16:09<03:58,  4.30it/s]

 80%|████████  | 4128/5153 [16:09<03:57,  4.31it/s]

 80%|████████  | 4129/5153 [16:10<03:57,  4.31it/s]

 80%|████████  | 4130/5153 [16:10<03:56,  4.32it/s]

 80%|████████  | 4131/5153 [16:10<03:56,  4.32it/s]

 80%|████████  | 4132/5153 [16:10<03:56,  4.31it/s]

 80%|████████  | 4133/5153 [16:11<03:56,  4.31it/s]

 80%|████████  | 4134/5153 [16:11<03:56,  4.31it/s]

 80%|████████  | 4135/5153 [16:11<03:56,  4.31it/s]

 80%|████████  | 4136/5153 [16:11<03:56,  4.31it/s]

 80%|████████  | 4137/5153 [16:11<03:55,  4.31it/s]

 80%|████████  | 4138/5153 [16:12<03:55,  4.32it/s]

 80%|████████  | 4139/5153 [16:12<03:55,  4.31it/s]

 80%|████████  | 4140/5153 [16:12<03:57,  4.26it/s]

 80%|████████  | 4141/5153 [16:12<03:56,  4.28it/s]

 80%|████████  | 4142/5153 [16:13<03:56,  4.28it/s]

 80%|████████  | 4143/5153 [16:13<03:55,  4.29it/s]

 80%|████████  | 4144/5153 [16:13<03:55,  4.29it/s]

 80%|████████  | 4145/5153 [16:13<03:54,  4.29it/s]

 80%|████████  | 4146/5153 [16:14<03:53,  4.31it/s]

 80%|████████  | 4147/5153 [16:14<03:53,  4.31it/s]

 80%|████████  | 4148/5153 [16:14<03:53,  4.31it/s]

 81%|████████  | 4149/5153 [16:14<03:53,  4.31it/s]

 81%|████████  | 4150/5153 [16:15<03:52,  4.31it/s]

 81%|████████  | 4151/5153 [16:15<03:52,  4.31it/s]

 81%|████████  | 4152/5153 [16:15<03:52,  4.31it/s]

 81%|████████  | 4153/5153 [16:15<03:53,  4.29it/s]

 81%|████████  | 4154/5153 [16:15<03:52,  4.30it/s]

 81%|████████  | 4155/5153 [16:16<03:52,  4.29it/s]

 81%|████████  | 4156/5153 [16:16<03:51,  4.30it/s]

 81%|████████  | 4157/5153 [16:16<03:51,  4.30it/s]

 81%|████████  | 4158/5153 [16:16<03:51,  4.30it/s]

 81%|████████  | 4159/5153 [16:17<03:51,  4.30it/s]

 81%|████████  | 4160/5153 [16:17<03:50,  4.30it/s]

 81%|████████  | 4161/5153 [16:17<03:50,  4.30it/s]

 81%|████████  | 4162/5153 [16:17<03:50,  4.30it/s]

 81%|████████  | 4163/5153 [16:18<03:50,  4.30it/s]

 81%|████████  | 4164/5153 [16:18<03:49,  4.31it/s]

 81%|████████  | 4165/5153 [16:18<03:49,  4.31it/s]

 81%|████████  | 4166/5153 [16:18<03:49,  4.31it/s]

 81%|████████  | 4167/5153 [16:18<03:49,  4.30it/s]

 81%|████████  | 4168/5153 [16:19<03:49,  4.29it/s]

 81%|████████  | 4169/5153 [16:19<03:49,  4.30it/s]

 81%|████████  | 4170/5153 [16:19<03:49,  4.29it/s]

 81%|████████  | 4171/5153 [16:19<03:48,  4.30it/s]

 81%|████████  | 4172/5153 [16:20<03:48,  4.29it/s]

 81%|████████  | 4173/5153 [16:20<03:48,  4.29it/s]

 81%|████████  | 4174/5153 [16:20<03:47,  4.30it/s]

 81%|████████  | 4175/5153 [16:20<03:48,  4.29it/s]

 81%|████████  | 4176/5153 [16:21<03:47,  4.30it/s]

 81%|████████  | 4177/5153 [16:21<03:46,  4.30it/s]

 81%|████████  | 4178/5153 [16:21<03:47,  4.29it/s]

 81%|████████  | 4179/5153 [16:21<03:46,  4.29it/s]

 81%|████████  | 4180/5153 [16:22<03:47,  4.28it/s]

 81%|████████  | 4181/5153 [16:22<03:47,  4.28it/s]

 81%|████████  | 4182/5153 [16:22<03:46,  4.29it/s]

 81%|████████  | 4183/5153 [16:22<03:46,  4.29it/s]

 81%|████████  | 4184/5153 [16:22<03:46,  4.29it/s]

 81%|████████  | 4185/5153 [16:23<03:46,  4.27it/s]

 81%|████████  | 4186/5153 [16:23<03:46,  4.28it/s]

 81%|████████▏ | 4187/5153 [16:23<03:45,  4.29it/s]

 81%|████████▏ | 4188/5153 [16:23<03:44,  4.29it/s]

 81%|████████▏ | 4189/5153 [16:24<03:43,  4.30it/s]

 81%|████████▏ | 4190/5153 [16:24<03:43,  4.31it/s]

 81%|████████▏ | 4191/5153 [16:24<03:43,  4.30it/s]

 81%|████████▏ | 4192/5153 [16:24<03:43,  4.30it/s]

 81%|████████▏ | 4193/5153 [16:25<03:42,  4.31it/s]

 81%|████████▏ | 4194/5153 [16:25<03:42,  4.31it/s]

 81%|████████▏ | 4195/5153 [16:25<03:42,  4.31it/s]

 81%|████████▏ | 4196/5153 [16:25<03:42,  4.30it/s]

 81%|████████▏ | 4197/5153 [16:25<03:42,  4.30it/s]

 81%|████████▏ | 4198/5153 [16:26<03:41,  4.30it/s]

 81%|████████▏ | 4199/5153 [16:26<03:42,  4.29it/s]

 82%|████████▏ | 4200/5153 [16:26<03:41,  4.30it/s]

 82%|████████▏ | 4201/5153 [16:26<03:41,  4.29it/s]

 82%|████████▏ | 4202/5153 [16:27<03:42,  4.28it/s]

 82%|████████▏ | 4203/5153 [16:27<03:41,  4.28it/s]

 82%|████████▏ | 4204/5153 [16:27<03:41,  4.29it/s]

 82%|████████▏ | 4205/5153 [16:27<03:40,  4.29it/s]

 82%|████████▏ | 4206/5153 [16:28<03:40,  4.29it/s]

 82%|████████▏ | 4207/5153 [16:28<03:40,  4.29it/s]

 82%|████████▏ | 4208/5153 [16:28<03:39,  4.30it/s]

 82%|████████▏ | 4209/5153 [16:28<03:40,  4.29it/s]

 82%|████████▏ | 4210/5153 [16:28<03:39,  4.29it/s]

 82%|████████▏ | 4211/5153 [16:29<03:39,  4.30it/s]

 82%|████████▏ | 4212/5153 [16:29<03:39,  4.29it/s]

 82%|████████▏ | 4213/5153 [16:29<03:38,  4.30it/s]

 82%|████████▏ | 4214/5153 [16:29<03:38,  4.30it/s]

 82%|████████▏ | 4215/5153 [16:30<03:37,  4.30it/s]

 82%|████████▏ | 4216/5153 [16:30<03:37,  4.30it/s]

 82%|████████▏ | 4217/5153 [16:30<03:37,  4.30it/s]

 82%|████████▏ | 4218/5153 [16:30<03:36,  4.31it/s]

 82%|████████▏ | 4219/5153 [16:31<03:37,  4.30it/s]

 82%|████████▏ | 4220/5153 [16:31<03:37,  4.30it/s]

 82%|████████▏ | 4221/5153 [16:31<03:36,  4.31it/s]

 82%|████████▏ | 4222/5153 [16:31<03:35,  4.31it/s]

 82%|████████▏ | 4223/5153 [16:32<03:35,  4.31it/s]

 82%|████████▏ | 4224/5153 [16:32<03:36,  4.29it/s]

 82%|████████▏ | 4225/5153 [16:32<03:37,  4.27it/s]

 82%|████████▏ | 4226/5153 [16:32<03:36,  4.29it/s]

 82%|████████▏ | 4227/5153 [16:32<03:36,  4.29it/s]

 82%|████████▏ | 4228/5153 [16:33<03:35,  4.29it/s]

 82%|████████▏ | 4229/5153 [16:33<03:35,  4.28it/s]

 82%|████████▏ | 4230/5153 [16:33<03:35,  4.27it/s]

 82%|████████▏ | 4231/5153 [16:33<03:35,  4.28it/s]

 82%|████████▏ | 4232/5153 [16:34<03:35,  4.28it/s]

 82%|████████▏ | 4233/5153 [16:34<03:35,  4.28it/s]

 82%|████████▏ | 4234/5153 [16:34<03:35,  4.27it/s]

 82%|████████▏ | 4235/5153 [16:34<03:34,  4.28it/s]

 82%|████████▏ | 4236/5153 [16:35<03:34,  4.28it/s]

 82%|████████▏ | 4237/5153 [16:35<03:33,  4.29it/s]

 82%|████████▏ | 4238/5153 [16:35<03:33,  4.28it/s]

 82%|████████▏ | 4239/5153 [16:35<03:33,  4.28it/s]

 82%|████████▏ | 4240/5153 [16:35<03:33,  4.27it/s]

 82%|████████▏ | 4241/5153 [16:36<03:33,  4.28it/s]

 82%|████████▏ | 4242/5153 [16:36<03:33,  4.27it/s]

 82%|████████▏ | 4243/5153 [16:36<03:33,  4.26it/s]

 82%|████████▏ | 4244/5153 [16:36<03:32,  4.27it/s]

 82%|████████▏ | 4245/5153 [16:37<03:32,  4.27it/s]

 82%|████████▏ | 4246/5153 [16:37<03:31,  4.28it/s]

 82%|████████▏ | 4247/5153 [16:37<03:31,  4.28it/s]

 82%|████████▏ | 4248/5153 [16:37<03:32,  4.26it/s]

 82%|████████▏ | 4249/5153 [16:38<03:32,  4.26it/s]

 82%|████████▏ | 4250/5153 [16:38<03:31,  4.26it/s]

 82%|████████▏ | 4251/5153 [16:38<03:31,  4.27it/s]

 83%|████████▎ | 4252/5153 [16:38<03:31,  4.26it/s]

 83%|████████▎ | 4253/5153 [16:39<03:31,  4.26it/s]

 83%|████████▎ | 4254/5153 [16:39<03:30,  4.26it/s]

 83%|████████▎ | 4255/5153 [16:39<03:30,  4.26it/s]

 83%|████████▎ | 4256/5153 [16:39<03:29,  4.27it/s]

 83%|████████▎ | 4257/5153 [16:39<03:29,  4.28it/s]

 83%|████████▎ | 4258/5153 [16:40<03:29,  4.28it/s]

 83%|████████▎ | 4259/5153 [16:40<03:29,  4.28it/s]

 83%|████████▎ | 4260/5153 [16:40<03:28,  4.28it/s]

 83%|████████▎ | 4261/5153 [16:40<03:28,  4.28it/s]

 83%|████████▎ | 4262/5153 [16:41<03:27,  4.29it/s]

 83%|████████▎ | 4263/5153 [16:41<03:27,  4.29it/s]

 83%|████████▎ | 4264/5153 [16:41<03:26,  4.30it/s]

 83%|████████▎ | 4265/5153 [16:41<03:26,  4.30it/s]

 83%|████████▎ | 4266/5153 [16:42<03:27,  4.28it/s]

 83%|████████▎ | 4267/5153 [16:42<03:27,  4.28it/s]

 83%|████████▎ | 4268/5153 [16:42<03:27,  4.27it/s]

 83%|████████▎ | 4269/5153 [16:42<03:26,  4.28it/s]

 83%|████████▎ | 4270/5153 [16:42<03:26,  4.28it/s]

 83%|████████▎ | 4271/5153 [16:43<03:26,  4.28it/s]

 83%|████████▎ | 4272/5153 [16:43<03:25,  4.28it/s]

 83%|████████▎ | 4273/5153 [16:43<03:25,  4.27it/s]

 83%|████████▎ | 4274/5153 [16:43<03:25,  4.27it/s]

 83%|████████▎ | 4275/5153 [16:44<03:25,  4.28it/s]

 83%|████████▎ | 4276/5153 [16:44<03:26,  4.25it/s]

 83%|████████▎ | 4277/5153 [16:44<03:25,  4.26it/s]

 83%|████████▎ | 4278/5153 [16:44<03:25,  4.26it/s]

 83%|████████▎ | 4279/5153 [16:45<03:25,  4.26it/s]

 83%|████████▎ | 4280/5153 [16:45<03:24,  4.26it/s]

 83%|████████▎ | 4281/5153 [16:45<03:25,  4.25it/s]

 83%|████████▎ | 4282/5153 [16:45<03:24,  4.26it/s]

 83%|████████▎ | 4283/5153 [16:46<03:24,  4.26it/s]

 83%|████████▎ | 4284/5153 [16:46<03:23,  4.27it/s]

 83%|████████▎ | 4285/5153 [16:46<03:23,  4.26it/s]

 83%|████████▎ | 4286/5153 [16:46<03:23,  4.25it/s]

 83%|████████▎ | 4287/5153 [16:46<03:24,  4.24it/s]

 83%|████████▎ | 4288/5153 [16:47<03:24,  4.24it/s]

 83%|████████▎ | 4289/5153 [16:47<03:22,  4.26it/s]

 83%|████████▎ | 4290/5153 [16:47<03:22,  4.26it/s]

 83%|████████▎ | 4291/5153 [16:47<03:22,  4.26it/s]

 83%|████████▎ | 4292/5153 [16:48<03:22,  4.25it/s]

 83%|████████▎ | 4293/5153 [16:48<03:22,  4.25it/s]

 83%|████████▎ | 4294/5153 [16:48<03:21,  4.26it/s]

 83%|████████▎ | 4295/5153 [16:48<03:21,  4.25it/s]

 83%|████████▎ | 4296/5153 [16:49<03:21,  4.25it/s]

 83%|████████▎ | 4297/5153 [16:49<03:21,  4.26it/s]

 83%|████████▎ | 4298/5153 [16:49<03:21,  4.25it/s]

 83%|████████▎ | 4299/5153 [16:49<03:20,  4.25it/s]

 83%|████████▎ | 4300/5153 [16:50<03:20,  4.26it/s]

 83%|████████▎ | 4301/5153 [16:50<03:20,  4.25it/s]

 83%|████████▎ | 4302/5153 [16:50<03:19,  4.26it/s]

 84%|████████▎ | 4303/5153 [16:50<03:20,  4.24it/s]

 84%|████████▎ | 4304/5153 [16:50<03:19,  4.25it/s]

 84%|████████▎ | 4305/5153 [16:51<03:20,  4.24it/s]

 84%|████████▎ | 4306/5153 [16:51<03:19,  4.24it/s]

 84%|████████▎ | 4307/5153 [16:51<03:19,  4.24it/s]

 84%|████████▎ | 4308/5153 [16:51<03:19,  4.24it/s]

 84%|████████▎ | 4309/5153 [16:52<03:18,  4.25it/s]

 84%|████████▎ | 4310/5153 [16:52<03:18,  4.25it/s]

 84%|████████▎ | 4311/5153 [16:52<03:18,  4.25it/s]

 84%|████████▎ | 4312/5153 [16:52<03:17,  4.25it/s]

 84%|████████▎ | 4313/5153 [16:53<03:17,  4.25it/s]

 84%|████████▎ | 4314/5153 [16:53<03:16,  4.26it/s]

 84%|████████▎ | 4315/5153 [16:53<03:16,  4.26it/s]

 84%|████████▍ | 4316/5153 [16:53<03:16,  4.25it/s]

 84%|████████▍ | 4317/5153 [16:54<03:16,  4.25it/s]

 84%|████████▍ | 4318/5153 [16:54<03:16,  4.25it/s]

 84%|████████▍ | 4319/5153 [16:54<03:15,  4.26it/s]

 84%|████████▍ | 4320/5153 [16:54<03:16,  4.24it/s]

 84%|████████▍ | 4321/5153 [16:54<03:15,  4.25it/s]

 84%|████████▍ | 4322/5153 [16:55<03:15,  4.26it/s]

 84%|████████▍ | 4323/5153 [16:55<03:15,  4.25it/s]

 84%|████████▍ | 4324/5153 [16:55<03:14,  4.26it/s]

 84%|████████▍ | 4325/5153 [16:55<03:14,  4.25it/s]

 84%|████████▍ | 4326/5153 [16:56<03:14,  4.25it/s]

 84%|████████▍ | 4327/5153 [16:56<03:14,  4.25it/s]

 84%|████████▍ | 4328/5153 [16:56<03:14,  4.25it/s]

 84%|████████▍ | 4329/5153 [16:56<03:13,  4.26it/s]

 84%|████████▍ | 4330/5153 [16:57<03:13,  4.25it/s]

 84%|████████▍ | 4331/5153 [16:57<03:13,  4.25it/s]

 84%|████████▍ | 4332/5153 [16:57<03:12,  4.26it/s]

 84%|████████▍ | 4333/5153 [16:57<03:12,  4.26it/s]

 84%|████████▍ | 4334/5153 [16:58<03:12,  4.26it/s]

 84%|████████▍ | 4335/5153 [16:58<03:12,  4.24it/s]

 84%|████████▍ | 4336/5153 [16:58<03:12,  4.25it/s]

 84%|████████▍ | 4337/5153 [16:58<03:11,  4.25it/s]

 84%|████████▍ | 4338/5153 [16:58<03:11,  4.25it/s]

 84%|████████▍ | 4339/5153 [16:59<03:11,  4.26it/s]

 84%|████████▍ | 4340/5153 [16:59<03:10,  4.26it/s]

 84%|████████▍ | 4341/5153 [16:59<03:10,  4.26it/s]

 84%|████████▍ | 4342/5153 [16:59<03:10,  4.25it/s]

 84%|████████▍ | 4343/5153 [17:00<03:10,  4.25it/s]

 84%|████████▍ | 4344/5153 [17:00<03:12,  4.20it/s]

 84%|████████▍ | 4345/5153 [17:00<03:11,  4.21it/s]

 84%|████████▍ | 4346/5153 [17:00<03:10,  4.23it/s]

 84%|████████▍ | 4347/5153 [17:01<03:09,  4.24it/s]

 84%|████████▍ | 4348/5153 [17:01<03:09,  4.24it/s]

 84%|████████▍ | 4349/5153 [17:01<03:09,  4.25it/s]

 84%|████████▍ | 4350/5153 [17:01<03:09,  4.24it/s]

 84%|████████▍ | 4351/5153 [17:02<03:08,  4.25it/s]

 84%|████████▍ | 4352/5153 [17:02<03:08,  4.26it/s]

 84%|████████▍ | 4353/5153 [17:02<03:07,  4.26it/s]

 84%|████████▍ | 4354/5153 [17:02<03:08,  4.25it/s]

 85%|████████▍ | 4355/5153 [17:02<03:08,  4.24it/s]

 85%|████████▍ | 4356/5153 [17:03<03:07,  4.25it/s]

 85%|████████▍ | 4357/5153 [17:03<03:07,  4.24it/s]

 85%|████████▍ | 4358/5153 [17:03<03:07,  4.24it/s]

 85%|████████▍ | 4359/5153 [17:03<03:07,  4.24it/s]

 85%|████████▍ | 4360/5153 [17:04<03:06,  4.25it/s]

 85%|████████▍ | 4361/5153 [17:04<03:06,  4.25it/s]

 85%|████████▍ | 4362/5153 [17:04<03:06,  4.25it/s]

 85%|████████▍ | 4363/5153 [17:04<03:06,  4.23it/s]

 85%|████████▍ | 4364/5153 [17:05<03:06,  4.23it/s]

 85%|████████▍ | 4365/5153 [17:05<03:06,  4.23it/s]

 85%|████████▍ | 4366/5153 [17:05<03:05,  4.23it/s]

 85%|████████▍ | 4367/5153 [17:05<03:05,  4.23it/s]

 85%|████████▍ | 4368/5153 [17:06<03:05,  4.23it/s]

 85%|████████▍ | 4369/5153 [17:06<03:05,  4.22it/s]

 85%|████████▍ | 4370/5153 [17:06<03:05,  4.23it/s]

 85%|████████▍ | 4371/5153 [17:06<03:04,  4.24it/s]

 85%|████████▍ | 4372/5153 [17:07<03:04,  4.24it/s]

 85%|████████▍ | 4373/5153 [17:07<03:04,  4.22it/s]

 85%|████████▍ | 4374/5153 [17:07<03:04,  4.23it/s]

 85%|████████▍ | 4375/5153 [17:07<03:04,  4.22it/s]

 85%|████████▍ | 4376/5153 [17:07<03:03,  4.23it/s]

 85%|████████▍ | 4377/5153 [17:08<03:03,  4.24it/s]

 85%|████████▍ | 4378/5153 [17:08<03:02,  4.24it/s]

 85%|████████▍ | 4379/5153 [17:08<03:02,  4.24it/s]

 85%|████████▍ | 4380/5153 [17:08<03:02,  4.24it/s]

 85%|████████▌ | 4381/5153 [17:09<03:02,  4.24it/s]

logging
logging the anndata

 85%|████████▌ | 4382/5153 [17:10<07:38,  1.68it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 85%|████████▌ | 4383/5153 [17:10<06:14,  2.06it/s]

 85%|████████▌ | 4384/5153 [17:11<05:14,  2.45it/s]

 85%|████████▌ | 4385/5153 [17:11<04:34,  2.80it/s]

 85%|████████▌ | 4386/5153 [17:11<04:04,  3.14it/s]

 85%|████████▌ | 4387/5153 [17:11<03:43,  3.42it/s]

 85%|████████▌ | 4388/5153 [17:11<03:29,  3.66it/s]

 85%|████████▌ | 4389/5153 [17:12<03:18,  3.85it/s]

 85%|████████▌ | 4390/5153 [17:12<03:11,  3.99it/s]

 85%|████████▌ | 4391/5153 [17:12<03:05,  4.10it/s]

 85%|████████▌ | 4392/5153 [17:12<03:02,  4.17it/s]

 85%|████████▌ | 4393/5153 [17:13<02:59,  4.23it/s]

 85%|████████▌ | 4394/5153 [17:13<02:57,  4.27it/s]

 85%|████████▌ | 4395/5153 [17:13<02:56,  4.30it/s]

 85%|████████▌ | 4396/5153 [17:13<02:55,  4.32it/s]

 85%|████████▌ | 4397/5153 [17:14<02:54,  4.32it/s]

 85%|████████▌ | 4398/5153 [17:14<02:54,  4.33it/s]

 85%|████████▌ | 4399/5153 [17:14<02:53,  4.34it/s]

 85%|████████▌ | 4400/5153 [17:14<02:53,  4.34it/s]

 85%|████████▌ | 4401/5153 [17:14<02:52,  4.35it/s]

 85%|████████▌ | 4402/5153 [17:15<02:52,  4.36it/s]

 85%|████████▌ | 4403/5153 [17:15<02:52,  4.36it/s]

 85%|████████▌ | 4404/5153 [17:15<02:51,  4.37it/s]

 85%|████████▌ | 4405/5153 [17:15<02:51,  4.37it/s]

 86%|████████▌ | 4406/5153 [17:16<02:51,  4.37it/s]

 86%|████████▌ | 4407/5153 [17:16<02:50,  4.37it/s]

 86%|████████▌ | 4408/5153 [17:16<02:50,  4.36it/s]

 86%|████████▌ | 4409/5153 [17:16<02:50,  4.36it/s]

 86%|████████▌ | 4410/5153 [17:16<02:50,  4.36it/s]

 86%|████████▌ | 4411/5153 [17:17<02:50,  4.36it/s]

 86%|████████▌ | 4412/5153 [17:17<02:49,  4.36it/s]

 86%|████████▌ | 4413/5153 [17:17<02:49,  4.37it/s]

 86%|████████▌ | 4414/5153 [17:17<02:49,  4.37it/s]

 86%|████████▌ | 4415/5153 [17:18<02:48,  4.37it/s]

 86%|████████▌ | 4416/5153 [17:18<02:48,  4.37it/s]

 86%|████████▌ | 4417/5153 [17:18<02:48,  4.36it/s]

 86%|████████▌ | 4418/5153 [17:18<02:48,  4.36it/s]

 86%|████████▌ | 4419/5153 [17:19<02:48,  4.35it/s]

 86%|████████▌ | 4420/5153 [17:19<02:48,  4.36it/s]

 86%|████████▌ | 4421/5153 [17:19<02:47,  4.36it/s]

 86%|████████▌ | 4422/5153 [17:19<02:48,  4.35it/s]

 86%|████████▌ | 4423/5153 [17:19<02:47,  4.36it/s]

 86%|████████▌ | 4424/5153 [17:20<02:47,  4.36it/s]

 86%|████████▌ | 4425/5153 [17:20<02:47,  4.36it/s]

 86%|████████▌ | 4426/5153 [17:20<02:47,  4.35it/s]

 86%|████████▌ | 4427/5153 [17:20<02:47,  4.35it/s]

 86%|████████▌ | 4428/5153 [17:21<02:46,  4.36it/s]

 86%|████████▌ | 4429/5153 [17:21<02:46,  4.35it/s]

 86%|████████▌ | 4430/5153 [17:21<02:46,  4.35it/s]

 86%|████████▌ | 4431/5153 [17:21<02:45,  4.36it/s]

 86%|████████▌ | 4432/5153 [17:22<02:45,  4.36it/s]

 86%|████████▌ | 4433/5153 [17:22<02:45,  4.36it/s]

 86%|████████▌ | 4434/5153 [17:22<02:44,  4.36it/s]

 86%|████████▌ | 4435/5153 [17:22<02:44,  4.36it/s]

 86%|████████▌ | 4436/5153 [17:22<02:44,  4.36it/s]

 86%|████████▌ | 4437/5153 [17:23<02:44,  4.36it/s]

 86%|████████▌ | 4438/5153 [17:23<02:44,  4.35it/s]

 86%|████████▌ | 4439/5153 [17:23<02:43,  4.36it/s]

 86%|████████▌ | 4440/5153 [17:23<02:43,  4.36it/s]

 86%|████████▌ | 4441/5153 [17:24<02:43,  4.35it/s]

 86%|████████▌ | 4442/5153 [17:24<02:43,  4.35it/s]

 86%|████████▌ | 4443/5153 [17:24<02:43,  4.34it/s]

 86%|████████▌ | 4444/5153 [17:24<02:43,  4.33it/s]

 86%|████████▋ | 4445/5153 [17:25<02:43,  4.33it/s]

 86%|████████▋ | 4446/5153 [17:25<02:43,  4.32it/s]

 86%|████████▋ | 4447/5153 [17:25<02:42,  4.34it/s]

 86%|████████▋ | 4448/5153 [17:25<02:42,  4.35it/s]

 86%|████████▋ | 4449/5153 [17:25<02:42,  4.34it/s]

 86%|████████▋ | 4450/5153 [17:26<02:41,  4.36it/s]

 86%|████████▋ | 4451/5153 [17:26<02:40,  4.36it/s]

 86%|████████▋ | 4452/5153 [17:26<02:40,  4.36it/s]

 86%|████████▋ | 4453/5153 [17:26<02:40,  4.37it/s]

 86%|████████▋ | 4454/5153 [17:27<02:40,  4.36it/s]

 86%|████████▋ | 4455/5153 [17:27<02:40,  4.35it/s]

 86%|████████▋ | 4456/5153 [17:27<02:40,  4.34it/s]

 86%|████████▋ | 4457/5153 [17:27<02:40,  4.34it/s]

 87%|████████▋ | 4458/5153 [17:28<02:39,  4.35it/s]

 87%|████████▋ | 4459/5153 [17:28<02:39,  4.34it/s]

 87%|████████▋ | 4460/5153 [17:28<02:39,  4.35it/s]

 87%|████████▋ | 4461/5153 [17:28<02:39,  4.35it/s]

 87%|████████▋ | 4462/5153 [17:28<02:39,  4.34it/s]

 87%|████████▋ | 4463/5153 [17:29<02:38,  4.34it/s]

 87%|████████▋ | 4464/5153 [17:29<02:38,  4.33it/s]

 87%|████████▋ | 4465/5153 [17:29<02:38,  4.33it/s]

 87%|████████▋ | 4466/5153 [17:29<02:38,  4.34it/s]

 87%|████████▋ | 4467/5153 [17:30<02:38,  4.33it/s]

 87%|████████▋ | 4468/5153 [17:30<02:38,  4.33it/s]

 87%|████████▋ | 4469/5153 [17:30<02:38,  4.32it/s]

 87%|████████▋ | 4470/5153 [17:30<02:37,  4.33it/s]

 87%|████████▋ | 4471/5153 [17:31<02:37,  4.34it/s]

 87%|████████▋ | 4472/5153 [17:31<02:37,  4.33it/s]

 87%|████████▋ | 4473/5153 [17:31<02:37,  4.33it/s]

 87%|████████▋ | 4474/5153 [17:31<02:36,  4.34it/s]

 87%|████████▋ | 4475/5153 [17:31<02:36,  4.34it/s]

 87%|████████▋ | 4476/5153 [17:32<02:36,  4.34it/s]

 87%|████████▋ | 4477/5153 [17:32<02:35,  4.34it/s]

 87%|████████▋ | 4478/5153 [17:32<02:35,  4.34it/s]

 87%|████████▋ | 4479/5153 [17:32<02:35,  4.34it/s]

 87%|████████▋ | 4480/5153 [17:33<02:34,  4.34it/s]

 87%|████████▋ | 4481/5153 [17:33<02:34,  4.34it/s]

 87%|████████▋ | 4482/5153 [17:33<02:34,  4.35it/s]

 87%|████████▋ | 4483/5153 [17:33<02:33,  4.35it/s]

 87%|████████▋ | 4484/5153 [17:34<02:33,  4.35it/s]

 87%|████████▋ | 4485/5153 [17:34<02:33,  4.35it/s]

 87%|████████▋ | 4486/5153 [17:34<02:33,  4.35it/s]

 87%|████████▋ | 4487/5153 [17:34<02:33,  4.34it/s]

 87%|████████▋ | 4488/5153 [17:34<02:33,  4.34it/s]

 87%|████████▋ | 4489/5153 [17:35<02:32,  4.34it/s]

 87%|████████▋ | 4490/5153 [17:35<02:32,  4.35it/s]

 87%|████████▋ | 4491/5153 [17:35<02:32,  4.35it/s]

 87%|████████▋ | 4492/5153 [17:35<02:32,  4.34it/s]

 87%|████████▋ | 4493/5153 [17:36<02:31,  4.35it/s]

 87%|████████▋ | 4494/5153 [17:36<02:31,  4.35it/s]

 87%|████████▋ | 4495/5153 [17:36<02:31,  4.35it/s]

 87%|████████▋ | 4496/5153 [17:36<02:31,  4.35it/s]

 87%|████████▋ | 4497/5153 [17:37<02:31,  4.34it/s]

 87%|████████▋ | 4498/5153 [17:37<02:30,  4.34it/s]

 87%|████████▋ | 4499/5153 [17:37<02:30,  4.34it/s]

 87%|████████▋ | 4500/5153 [17:37<02:30,  4.34it/s]

 87%|████████▋ | 4501/5153 [17:37<02:30,  4.34it/s]

 87%|████████▋ | 4502/5153 [17:38<02:30,  4.34it/s]

 87%|████████▋ | 4503/5153 [17:38<02:30,  4.33it/s]

 87%|████████▋ | 4504/5153 [17:38<02:29,  4.34it/s]

 87%|████████▋ | 4505/5153 [17:38<02:29,  4.32it/s]

 87%|████████▋ | 4506/5153 [17:39<02:29,  4.33it/s]

 87%|████████▋ | 4507/5153 [17:39<02:29,  4.33it/s]

 87%|████████▋ | 4508/5153 [17:39<02:28,  4.33it/s]

 88%|████████▊ | 4509/5153 [17:39<02:28,  4.34it/s]

 88%|████████▊ | 4510/5153 [17:40<02:27,  4.35it/s]

 88%|████████▊ | 4511/5153 [17:40<02:27,  4.34it/s]

 88%|████████▊ | 4512/5153 [17:40<02:27,  4.35it/s]

 88%|████████▊ | 4513/5153 [17:40<02:27,  4.34it/s]

 88%|████████▊ | 4514/5153 [17:40<02:27,  4.34it/s]

 88%|████████▊ | 4515/5153 [17:41<02:27,  4.34it/s]

 88%|████████▊ | 4516/5153 [17:41<02:27,  4.33it/s]

 88%|████████▊ | 4517/5153 [17:41<02:26,  4.34it/s]

 88%|████████▊ | 4518/5153 [17:41<02:26,  4.34it/s]

 88%|████████▊ | 4519/5153 [17:42<02:26,  4.33it/s]

 88%|████████▊ | 4520/5153 [17:42<02:26,  4.33it/s]

 88%|████████▊ | 4521/5153 [17:42<02:25,  4.33it/s]

 88%|████████▊ | 4522/5153 [17:42<02:25,  4.33it/s]

 88%|████████▊ | 4523/5153 [17:43<02:25,  4.34it/s]

 88%|████████▊ | 4524/5153 [17:43<02:24,  4.34it/s]

 88%|████████▊ | 4525/5153 [17:43<02:24,  4.35it/s]

 88%|████████▊ | 4526/5153 [17:43<02:24,  4.34it/s]

 88%|████████▊ | 4527/5153 [17:43<02:24,  4.32it/s]

 88%|████████▊ | 4528/5153 [17:44<02:25,  4.30it/s]

 88%|████████▊ | 4529/5153 [17:44<02:24,  4.31it/s]

 88%|████████▊ | 4530/5153 [17:44<02:24,  4.32it/s]

 88%|████████▊ | 4531/5153 [17:44<02:23,  4.32it/s]

 88%|████████▊ | 4532/5153 [17:45<02:23,  4.32it/s]

 88%|████████▊ | 4533/5153 [17:45<02:23,  4.33it/s]

 88%|████████▊ | 4534/5153 [17:45<02:23,  4.32it/s]

 88%|████████▊ | 4535/5153 [17:45<02:22,  4.33it/s]

 88%|████████▊ | 4536/5153 [17:46<02:22,  4.32it/s]

 88%|████████▊ | 4537/5153 [17:46<02:22,  4.33it/s]

 88%|████████▊ | 4538/5153 [17:46<02:21,  4.33it/s]

 88%|████████▊ | 4539/5153 [17:46<02:21,  4.34it/s]

 88%|████████▊ | 4540/5153 [17:46<02:21,  4.33it/s]

 88%|████████▊ | 4541/5153 [17:47<02:21,  4.34it/s]

 88%|████████▊ | 4542/5153 [17:47<02:20,  4.34it/s]

 88%|████████▊ | 4543/5153 [17:47<02:20,  4.34it/s]

 88%|████████▊ | 4544/5153 [17:47<02:20,  4.33it/s]

 88%|████████▊ | 4545/5153 [17:48<02:20,  4.33it/s]

 88%|████████▊ | 4546/5153 [17:48<02:19,  4.34it/s]

 88%|████████▊ | 4547/5153 [17:48<02:19,  4.34it/s]

 88%|████████▊ | 4548/5153 [17:48<02:19,  4.33it/s]

 88%|████████▊ | 4549/5153 [17:49<02:19,  4.33it/s]

 88%|████████▊ | 4550/5153 [17:49<02:19,  4.33it/s]

 88%|████████▊ | 4551/5153 [17:49<02:19,  4.33it/s]

 88%|████████▊ | 4552/5153 [17:49<02:18,  4.33it/s]

 88%|████████▊ | 4553/5153 [17:49<02:18,  4.32it/s]

 88%|████████▊ | 4554/5153 [17:50<02:18,  4.33it/s]

 88%|████████▊ | 4555/5153 [17:50<02:18,  4.33it/s]

 88%|████████▊ | 4556/5153 [17:50<02:17,  4.33it/s]

 88%|████████▊ | 4557/5153 [17:50<02:17,  4.34it/s]

 88%|████████▊ | 4558/5153 [17:51<02:17,  4.33it/s]

 88%|████████▊ | 4559/5153 [17:51<02:17,  4.31it/s]

 88%|████████▊ | 4560/5153 [17:51<02:17,  4.32it/s]

 89%|████████▊ | 4561/5153 [17:51<02:16,  4.33it/s]

 89%|████████▊ | 4562/5153 [17:52<02:16,  4.34it/s]

 89%|████████▊ | 4563/5153 [17:52<02:16,  4.33it/s]

 89%|████████▊ | 4564/5153 [17:52<02:16,  4.32it/s]

 89%|████████▊ | 4565/5153 [17:52<02:15,  4.33it/s]

 89%|████████▊ | 4566/5153 [17:52<02:15,  4.33it/s]

 89%|████████▊ | 4567/5153 [17:53<02:15,  4.31it/s]

 89%|████████▊ | 4568/5153 [17:53<02:15,  4.32it/s]

 89%|████████▊ | 4569/5153 [17:53<02:15,  4.32it/s]

 89%|████████▊ | 4570/5153 [17:53<02:14,  4.33it/s]

 89%|████████▊ | 4571/5153 [17:54<02:14,  4.32it/s]

 89%|████████▊ | 4572/5153 [17:54<02:14,  4.31it/s]

 89%|████████▊ | 4573/5153 [17:54<02:14,  4.32it/s]

 89%|████████▉ | 4574/5153 [17:54<02:13,  4.32it/s]

 89%|████████▉ | 4575/5153 [17:55<02:13,  4.32it/s]

 89%|████████▉ | 4576/5153 [17:55<02:13,  4.33it/s]

 89%|████████▉ | 4577/5153 [17:55<02:13,  4.32it/s]

 89%|████████▉ | 4578/5153 [17:55<02:12,  4.33it/s]

 89%|████████▉ | 4579/5153 [17:55<02:12,  4.32it/s]

 89%|████████▉ | 4580/5153 [17:56<02:12,  4.32it/s]

 89%|████████▉ | 4581/5153 [17:56<02:12,  4.33it/s]

 89%|████████▉ | 4582/5153 [17:56<02:12,  4.32it/s]

 89%|████████▉ | 4583/5153 [17:56<02:11,  4.32it/s]

 89%|████████▉ | 4584/5153 [17:57<02:11,  4.33it/s]

 89%|████████▉ | 4585/5153 [17:57<02:11,  4.32it/s]

 89%|████████▉ | 4586/5153 [17:57<02:11,  4.33it/s]

 89%|████████▉ | 4587/5153 [17:57<02:11,  4.32it/s]

 89%|████████▉ | 4588/5153 [17:58<02:10,  4.32it/s]

 89%|████████▉ | 4589/5153 [17:58<02:10,  4.32it/s]

 89%|████████▉ | 4590/5153 [17:58<02:10,  4.32it/s]

 89%|████████▉ | 4591/5153 [17:58<02:10,  4.32it/s]

 89%|████████▉ | 4592/5153 [17:58<02:09,  4.32it/s]

 89%|████████▉ | 4593/5153 [17:59<02:09,  4.31it/s]

 89%|████████▉ | 4594/5153 [17:59<02:09,  4.33it/s]

 89%|████████▉ | 4595/5153 [17:59<02:08,  4.33it/s]

 89%|████████▉ | 4596/5153 [17:59<02:08,  4.33it/s]

 89%|████████▉ | 4597/5153 [18:00<02:08,  4.33it/s]

 89%|████████▉ | 4598/5153 [18:00<02:08,  4.33it/s]

 89%|████████▉ | 4599/5153 [18:00<02:07,  4.33it/s]

 89%|████████▉ | 4600/5153 [18:00<02:07,  4.32it/s]

 89%|████████▉ | 4601/5153 [18:01<02:07,  4.32it/s]

 89%|████████▉ | 4602/5153 [18:01<02:07,  4.32it/s]

 89%|████████▉ | 4603/5153 [18:01<02:07,  4.32it/s]

 89%|████████▉ | 4604/5153 [18:01<02:07,  4.32it/s]

 89%|████████▉ | 4605/5153 [18:01<02:06,  4.32it/s]

 89%|████████▉ | 4606/5153 [18:02<02:06,  4.32it/s]

 89%|████████▉ | 4607/5153 [18:02<02:06,  4.33it/s]

 89%|████████▉ | 4608/5153 [18:02<02:06,  4.32it/s]

 89%|████████▉ | 4609/5153 [18:02<02:06,  4.30it/s]

 89%|████████▉ | 4610/5153 [18:03<02:05,  4.31it/s]

 89%|████████▉ | 4611/5153 [18:03<02:05,  4.31it/s]

 90%|████████▉ | 4612/5153 [18:03<02:05,  4.32it/s]

 90%|████████▉ | 4613/5153 [18:03<02:05,  4.32it/s]

 90%|████████▉ | 4614/5153 [18:04<02:04,  4.32it/s]

 90%|████████▉ | 4615/5153 [18:04<02:04,  4.33it/s]

 90%|████████▉ | 4616/5153 [18:04<02:04,  4.32it/s]

 90%|████████▉ | 4617/5153 [18:04<02:04,  4.30it/s]

 90%|████████▉ | 4618/5153 [18:04<02:04,  4.30it/s]

 90%|████████▉ | 4619/5153 [18:05<02:04,  4.31it/s]

 90%|████████▉ | 4620/5153 [18:05<02:03,  4.31it/s]

 90%|████████▉ | 4621/5153 [18:05<02:03,  4.30it/s]

 90%|████████▉ | 4622/5153 [18:05<02:03,  4.31it/s]

 90%|████████▉ | 4623/5153 [18:06<02:02,  4.32it/s]

 90%|████████▉ | 4624/5153 [18:06<02:02,  4.32it/s]

 90%|████████▉ | 4625/5153 [18:06<02:02,  4.31it/s]

 90%|████████▉ | 4626/5153 [18:06<02:02,  4.31it/s]

 90%|████████▉ | 4627/5153 [18:07<02:02,  4.30it/s]

 90%|████████▉ | 4628/5153 [18:07<02:01,  4.30it/s]

 90%|████████▉ | 4629/5153 [18:07<02:01,  4.31it/s]

 90%|████████▉ | 4630/5153 [18:07<02:01,  4.31it/s]

 90%|████████▉ | 4631/5153 [18:07<02:01,  4.31it/s]

 90%|████████▉ | 4632/5153 [18:08<02:00,  4.31it/s]

 90%|████████▉ | 4633/5153 [18:08<02:00,  4.32it/s]

 90%|████████▉ | 4634/5153 [18:08<02:00,  4.31it/s]

 90%|████████▉ | 4635/5153 [18:08<02:00,  4.30it/s]

 90%|████████▉ | 4636/5153 [18:09<01:59,  4.31it/s]

 90%|████████▉ | 4637/5153 [18:09<01:59,  4.31it/s]

 90%|█████████ | 4638/5153 [18:09<01:59,  4.32it/s]

 90%|█████████ | 4639/5153 [18:09<01:59,  4.32it/s]

 90%|█████████ | 4640/5153 [18:10<01:58,  4.32it/s]

 90%|█████████ | 4641/5153 [18:10<01:58,  4.32it/s]

 90%|█████████ | 4642/5153 [18:10<01:58,  4.32it/s]

 90%|█████████ | 4643/5153 [18:10<01:57,  4.33it/s]

 90%|█████████ | 4644/5153 [18:10<01:57,  4.34it/s]

 90%|█████████ | 4645/5153 [18:11<01:57,  4.34it/s]

 90%|█████████ | 4646/5153 [18:11<01:56,  4.34it/s]

 90%|█████████ | 4647/5153 [18:11<01:56,  4.33it/s]

 90%|█████████ | 4648/5153 [18:11<01:56,  4.32it/s]

 90%|█████████ | 4649/5153 [18:12<01:56,  4.32it/s]

 90%|█████████ | 4650/5153 [18:12<01:56,  4.33it/s]

 90%|█████████ | 4651/5153 [18:12<01:56,  4.31it/s]

 90%|█████████ | 4652/5153 [18:12<01:55,  4.32it/s]

 90%|█████████ | 4653/5153 [18:13<01:55,  4.31it/s]

 90%|█████████ | 4654/5153 [18:13<01:56,  4.30it/s]

 90%|█████████ | 4655/5153 [18:13<01:55,  4.30it/s]

 90%|█████████ | 4656/5153 [18:13<01:55,  4.29it/s]

 90%|█████████ | 4657/5153 [18:14<01:55,  4.29it/s]

 90%|█████████ | 4658/5153 [18:14<01:55,  4.30it/s]

 90%|█████████ | 4659/5153 [18:14<01:54,  4.30it/s]

 90%|█████████ | 4660/5153 [18:14<01:54,  4.30it/s]

 90%|█████████ | 4661/5153 [18:14<01:54,  4.30it/s]

 90%|█████████ | 4662/5153 [18:15<01:54,  4.30it/s]

 90%|█████████ | 4663/5153 [18:15<01:54,  4.29it/s]

 91%|█████████ | 4664/5153 [18:15<01:54,  4.28it/s]

 91%|█████████ | 4665/5153 [18:15<01:53,  4.30it/s]

 91%|█████████ | 4666/5153 [18:16<01:53,  4.31it/s]

 91%|█████████ | 4667/5153 [18:16<01:52,  4.31it/s]

 91%|█████████ | 4668/5153 [18:16<01:52,  4.31it/s]

 91%|█████████ | 4669/5153 [18:16<01:52,  4.32it/s]

 91%|█████████ | 4670/5153 [18:17<01:52,  4.30it/s]

 91%|█████████ | 4671/5153 [18:17<01:51,  4.31it/s]

 91%|█████████ | 4672/5153 [18:17<01:51,  4.30it/s]

 91%|█████████ | 4673/5153 [18:17<01:51,  4.31it/s]

 91%|█████████ | 4674/5153 [18:17<01:51,  4.30it/s]

 91%|█████████ | 4675/5153 [18:18<01:51,  4.30it/s]

 91%|█████████ | 4676/5153 [18:18<01:50,  4.31it/s]

 91%|█████████ | 4677/5153 [18:18<01:50,  4.30it/s]

 91%|█████████ | 4678/5153 [18:18<01:50,  4.29it/s]

 91%|█████████ | 4679/5153 [18:19<01:50,  4.29it/s]

 91%|█████████ | 4680/5153 [18:19<01:50,  4.30it/s]

 91%|█████████ | 4681/5153 [18:19<01:49,  4.30it/s]

 91%|█████████ | 4682/5153 [18:19<01:49,  4.30it/s]

 91%|█████████ | 4683/5153 [18:20<01:49,  4.30it/s]

 91%|█████████ | 4684/5153 [18:20<01:48,  4.31it/s]

 91%|█████████ | 4685/5153 [18:20<01:48,  4.31it/s]

 91%|█████████ | 4686/5153 [18:20<01:48,  4.32it/s]

 91%|█████████ | 4687/5153 [18:20<01:47,  4.33it/s]

 91%|█████████ | 4688/5153 [18:21<01:47,  4.32it/s]

 91%|█████████ | 4689/5153 [18:21<01:47,  4.33it/s]

 91%|█████████ | 4690/5153 [18:21<01:46,  4.34it/s]

 91%|█████████ | 4691/5153 [18:21<01:46,  4.34it/s]

 91%|█████████ | 4692/5153 [18:22<01:46,  4.34it/s]

 91%|█████████ | 4693/5153 [18:22<01:45,  4.35it/s]

 91%|█████████ | 4694/5153 [18:22<01:45,  4.34it/s]

 91%|█████████ | 4695/5153 [18:22<01:46,  4.30it/s]

 91%|█████████ | 4696/5153 [18:23<01:45,  4.32it/s]

 91%|█████████ | 4697/5153 [18:23<01:45,  4.32it/s]

 91%|█████████ | 4698/5153 [18:23<01:45,  4.33it/s]

 91%|█████████ | 4699/5153 [18:23<01:45,  4.32it/s]

 91%|█████████ | 4700/5153 [18:23<01:44,  4.32it/s]

 91%|█████████ | 4701/5153 [18:24<01:44,  4.33it/s]

 91%|█████████ | 4702/5153 [18:24<01:44,  4.33it/s]

 91%|█████████▏| 4703/5153 [18:24<01:44,  4.32it/s]

 91%|█████████▏| 4704/5153 [18:24<01:43,  4.32it/s]

 91%|█████████▏| 4705/5153 [18:25<01:43,  4.31it/s]

 91%|█████████▏| 4706/5153 [18:25<01:43,  4.32it/s]

 91%|█████████▏| 4707/5153 [18:25<01:43,  4.32it/s]

 91%|█████████▏| 4708/5153 [18:25<01:43,  4.32it/s]

 91%|█████████▏| 4709/5153 [18:26<01:42,  4.33it/s]

 91%|█████████▏| 4710/5153 [18:26<01:42,  4.32it/s]

 91%|█████████▏| 4711/5153 [18:26<01:42,  4.32it/s]

 91%|█████████▏| 4712/5153 [18:26<01:42,  4.32it/s]

 91%|█████████▏| 4713/5153 [18:26<01:41,  4.31it/s]

 91%|█████████▏| 4714/5153 [18:27<01:41,  4.31it/s]

 92%|█████████▏| 4715/5153 [18:27<01:41,  4.31it/s]

 92%|█████████▏| 4716/5153 [18:27<01:41,  4.30it/s]

 92%|█████████▏| 4717/5153 [18:27<01:41,  4.30it/s]

 92%|█████████▏| 4718/5153 [18:28<01:41,  4.30it/s]

 92%|█████████▏| 4719/5153 [18:28<01:40,  4.31it/s]

 92%|█████████▏| 4720/5153 [18:28<01:40,  4.31it/s]

 92%|█████████▏| 4721/5153 [18:28<01:40,  4.31it/s]

 92%|█████████▏| 4722/5153 [18:29<01:39,  4.32it/s]

 92%|█████████▏| 4723/5153 [18:29<01:39,  4.32it/s]

 92%|█████████▏| 4724/5153 [18:29<01:39,  4.32it/s]

 92%|█████████▏| 4725/5153 [18:29<01:38,  4.33it/s]

 92%|█████████▏| 4726/5153 [18:30<01:38,  4.32it/s]

 92%|█████████▏| 4727/5153 [18:30<01:38,  4.32it/s]

 92%|█████████▏| 4728/5153 [18:30<01:38,  4.32it/s]

 92%|█████████▏| 4729/5153 [18:30<01:38,  4.32it/s]

 92%|█████████▏| 4730/5153 [18:30<01:37,  4.33it/s]

 92%|█████████▏| 4731/5153 [18:31<01:37,  4.33it/s]

 92%|█████████▏| 4732/5153 [18:31<01:37,  4.33it/s]

 92%|█████████▏| 4733/5153 [18:31<01:37,  4.33it/s]

 92%|█████████▏| 4734/5153 [18:31<01:37,  4.32it/s]

 92%|█████████▏| 4735/5153 [18:32<01:36,  4.32it/s]

 92%|█████████▏| 4736/5153 [18:32<01:36,  4.32it/s]

 92%|█████████▏| 4737/5153 [18:32<01:36,  4.30it/s]

 92%|█████████▏| 4738/5153 [18:32<01:36,  4.30it/s]

 92%|█████████▏| 4739/5153 [18:33<01:36,  4.30it/s]

 92%|█████████▏| 4740/5153 [18:33<01:35,  4.31it/s]

 92%|█████████▏| 4741/5153 [18:33<01:35,  4.30it/s]

 92%|█████████▏| 4742/5153 [18:33<01:35,  4.29it/s]

 92%|█████████▏| 4743/5153 [18:33<01:35,  4.30it/s]

 92%|█████████▏| 4744/5153 [18:34<01:34,  4.31it/s]

 92%|█████████▏| 4745/5153 [18:34<01:34,  4.31it/s]

 92%|█████████▏| 4746/5153 [18:34<01:34,  4.30it/s]

 92%|█████████▏| 4747/5153 [18:34<01:34,  4.29it/s]

 92%|█████████▏| 4748/5153 [18:35<01:34,  4.30it/s]

 92%|█████████▏| 4749/5153 [18:35<01:33,  4.30it/s]

 92%|█████████▏| 4750/5153 [18:35<01:33,  4.30it/s]

 92%|█████████▏| 4751/5153 [18:35<01:33,  4.30it/s]

 92%|█████████▏| 4752/5153 [18:36<01:33,  4.31it/s]

 92%|█████████▏| 4753/5153 [18:36<01:32,  4.31it/s]

 92%|█████████▏| 4754/5153 [18:36<01:32,  4.31it/s]

 92%|█████████▏| 4755/5153 [18:36<01:32,  4.31it/s]

 92%|█████████▏| 4756/5153 [18:36<01:32,  4.32it/s]

 92%|█████████▏| 4757/5153 [18:37<01:32,  4.30it/s]

 92%|█████████▏| 4758/5153 [18:37<01:31,  4.31it/s]

 92%|█████████▏| 4759/5153 [18:37<01:31,  4.31it/s]

 92%|█████████▏| 4760/5153 [18:37<01:31,  4.30it/s]

 92%|█████████▏| 4761/5153 [18:38<01:30,  4.31it/s]

 92%|█████████▏| 4762/5153 [18:38<01:30,  4.31it/s]

 92%|█████████▏| 4763/5153 [18:38<01:30,  4.31it/s]

 92%|█████████▏| 4764/5153 [18:38<01:30,  4.31it/s]

 92%|█████████▏| 4765/5153 [18:39<01:30,  4.30it/s]

 92%|█████████▏| 4766/5153 [18:39<01:29,  4.31it/s]

 93%|█████████▎| 4767/5153 [18:39<01:29,  4.31it/s]

 93%|█████████▎| 4768/5153 [18:39<01:29,  4.31it/s]

 93%|█████████▎| 4769/5153 [18:39<01:29,  4.31it/s]

 93%|█████████▎| 4770/5153 [18:40<01:29,  4.30it/s]

 93%|█████████▎| 4771/5153 [18:40<01:28,  4.30it/s]

 93%|█████████▎| 4772/5153 [18:40<01:28,  4.31it/s]

 93%|█████████▎| 4773/5153 [18:40<01:28,  4.30it/s]

 93%|█████████▎| 4774/5153 [18:41<01:27,  4.31it/s]

 93%|█████████▎| 4775/5153 [18:41<01:27,  4.31it/s]

 93%|█████████▎| 4776/5153 [18:41<01:27,  4.31it/s]

 93%|█████████▎| 4777/5153 [18:41<01:27,  4.30it/s]

 93%|█████████▎| 4778/5153 [18:42<01:27,  4.29it/s]

 93%|█████████▎| 4779/5153 [18:42<01:26,  4.30it/s]

 93%|█████████▎| 4780/5153 [18:42<01:26,  4.30it/s]

 93%|█████████▎| 4781/5153 [18:42<01:26,  4.30it/s]

 93%|█████████▎| 4782/5153 [18:43<01:26,  4.31it/s]

 93%|█████████▎| 4783/5153 [18:43<01:26,  4.30it/s]

 93%|█████████▎| 4784/5153 [18:43<01:25,  4.30it/s]

 93%|█████████▎| 4785/5153 [18:43<01:25,  4.29it/s]

 93%|█████████▎| 4786/5153 [18:43<01:25,  4.28it/s]

 93%|█████████▎| 4787/5153 [18:44<01:25,  4.29it/s]

 93%|█████████▎| 4788/5153 [18:44<01:25,  4.29it/s]

 93%|█████████▎| 4789/5153 [18:44<01:24,  4.28it/s]

 93%|█████████▎| 4790/5153 [18:44<01:24,  4.29it/s]

 93%|█████████▎| 4791/5153 [18:45<01:24,  4.30it/s]

 93%|█████████▎| 4792/5153 [18:45<01:23,  4.30it/s]

 93%|█████████▎| 4793/5153 [18:45<01:23,  4.30it/s]

 93%|█████████▎| 4794/5153 [18:45<01:23,  4.29it/s]

 93%|█████████▎| 4795/5153 [18:46<01:23,  4.30it/s]

 93%|█████████▎| 4796/5153 [18:46<01:23,  4.29it/s]

 93%|█████████▎| 4797/5153 [18:46<01:22,  4.30it/s]

 93%|█████████▎| 4798/5153 [18:46<01:22,  4.28it/s]

 93%|█████████▎| 4799/5153 [18:46<01:22,  4.27it/s]

 93%|█████████▎| 4800/5153 [18:47<01:22,  4.28it/s]

 93%|█████████▎| 4801/5153 [18:47<01:22,  4.28it/s]

 93%|█████████▎| 4802/5153 [18:47<01:21,  4.28it/s]

 93%|█████████▎| 4803/5153 [18:47<01:21,  4.29it/s]

 93%|█████████▎| 4804/5153 [18:48<01:21,  4.29it/s]

 93%|█████████▎| 4805/5153 [18:48<01:20,  4.30it/s]

 93%|█████████▎| 4806/5153 [18:48<01:20,  4.30it/s]

 93%|█████████▎| 4807/5153 [18:48<01:20,  4.29it/s]

 93%|█████████▎| 4808/5153 [18:49<01:20,  4.30it/s]

 93%|█████████▎| 4809/5153 [18:49<01:20,  4.28it/s]

 93%|█████████▎| 4810/5153 [18:49<01:20,  4.29it/s]

 93%|█████████▎| 4811/5153 [18:49<01:19,  4.28it/s]

 93%|█████████▎| 4812/5153 [18:50<01:19,  4.28it/s]

 93%|█████████▎| 4813/5153 [18:50<01:19,  4.29it/s]

 93%|█████████▎| 4814/5153 [18:50<01:19,  4.29it/s]

 93%|█████████▎| 4815/5153 [18:50<01:18,  4.30it/s]

 93%|█████████▎| 4816/5153 [18:50<01:18,  4.30it/s]

 93%|█████████▎| 4817/5153 [18:51<01:18,  4.28it/s]

 93%|█████████▎| 4818/5153 [18:51<01:17,  4.30it/s]

 94%|█████████▎| 4819/5153 [18:51<01:17,  4.30it/s]

 94%|█████████▎| 4820/5153 [18:51<01:17,  4.31it/s]

 94%|█████████▎| 4821/5153 [18:52<01:17,  4.30it/s]

 94%|█████████▎| 4822/5153 [18:52<01:17,  4.29it/s]

 94%|█████████▎| 4823/5153 [18:52<01:16,  4.30it/s]

 94%|█████████▎| 4824/5153 [18:52<01:16,  4.31it/s]

 94%|█████████▎| 4825/5153 [18:53<01:16,  4.28it/s]

 94%|█████████▎| 4826/5153 [18:53<01:16,  4.28it/s]

 94%|█████████▎| 4827/5153 [18:53<01:16,  4.28it/s]

 94%|█████████▎| 4828/5153 [18:53<01:15,  4.29it/s]

 94%|█████████▎| 4829/5153 [18:53<01:15,  4.29it/s]

 94%|█████████▎| 4830/5153 [18:54<01:15,  4.29it/s]

 94%|█████████▍| 4831/5153 [18:54<01:15,  4.27it/s]

 94%|█████████▍| 4832/5153 [18:54<01:15,  4.28it/s]

 94%|█████████▍| 4833/5153 [18:54<01:14,  4.29it/s]

 94%|█████████▍| 4834/5153 [18:55<01:14,  4.30it/s]

 94%|█████████▍| 4835/5153 [18:55<01:14,  4.29it/s]

 94%|█████████▍| 4836/5153 [18:55<01:13,  4.30it/s]

 94%|█████████▍| 4837/5153 [18:55<01:13,  4.29it/s]

 94%|█████████▍| 4838/5153 [18:56<01:13,  4.29it/s]

 94%|█████████▍| 4839/5153 [18:56<01:13,  4.29it/s]

 94%|█████████▍| 4840/5153 [18:56<01:12,  4.29it/s]

 94%|█████████▍| 4841/5153 [18:56<01:12,  4.30it/s]

 94%|█████████▍| 4842/5153 [18:56<01:12,  4.30it/s]

 94%|█████████▍| 4843/5153 [18:57<01:12,  4.29it/s]

 94%|█████████▍| 4844/5153 [18:57<01:11,  4.30it/s]

 94%|█████████▍| 4845/5153 [18:57<01:11,  4.30it/s]

 94%|█████████▍| 4846/5153 [18:57<01:11,  4.31it/s]

 94%|█████████▍| 4847/5153 [18:58<01:11,  4.31it/s]

 94%|█████████▍| 4848/5153 [18:58<01:10,  4.31it/s]

 94%|█████████▍| 4849/5153 [18:58<01:10,  4.31it/s]

 94%|█████████▍| 4850/5153 [18:58<01:10,  4.29it/s]

 94%|█████████▍| 4851/5153 [18:59<01:10,  4.29it/s]

 94%|█████████▍| 4852/5153 [18:59<01:10,  4.27it/s]

 94%|█████████▍| 4853/5153 [18:59<01:10,  4.26it/s]

 94%|█████████▍| 4854/5153 [18:59<01:10,  4.25it/s]

 94%|█████████▍| 4855/5153 [19:00<01:10,  4.26it/s]

 94%|█████████▍| 4856/5153 [19:00<01:09,  4.27it/s]

 94%|█████████▍| 4857/5153 [19:00<01:09,  4.27it/s]

 94%|█████████▍| 4858/5153 [19:00<01:09,  4.27it/s]

 94%|█████████▍| 4859/5153 [19:00<01:08,  4.28it/s]

 94%|█████████▍| 4860/5153 [19:01<01:08,  4.27it/s]

 94%|█████████▍| 4861/5153 [19:01<01:08,  4.27it/s]

 94%|█████████▍| 4862/5153 [19:01<01:08,  4.28it/s]

 94%|█████████▍| 4863/5153 [19:01<01:07,  4.27it/s]

 94%|█████████▍| 4864/5153 [19:02<01:07,  4.28it/s]

 94%|█████████▍| 4865/5153 [19:02<01:07,  4.28it/s]

 94%|█████████▍| 4866/5153 [19:02<01:07,  4.28it/s]

 94%|█████████▍| 4867/5153 [19:02<01:06,  4.27it/s]

 94%|█████████▍| 4868/5153 [19:03<01:06,  4.26it/s]

 94%|█████████▍| 4869/5153 [19:03<01:06,  4.27it/s]

 95%|█████████▍| 4870/5153 [19:03<01:06,  4.26it/s]

 95%|█████████▍| 4871/5153 [19:03<01:06,  4.27it/s]

 95%|█████████▍| 4872/5153 [19:04<01:05,  4.27it/s]

 95%|█████████▍| 4873/5153 [19:04<01:05,  4.26it/s]

 95%|█████████▍| 4874/5153 [19:04<01:05,  4.27it/s]

 95%|█████████▍| 4875/5153 [19:04<01:05,  4.27it/s]

 95%|█████████▍| 4876/5153 [19:04<01:04,  4.28it/s]

 95%|█████████▍| 4877/5153 [19:05<01:04,  4.28it/s]

 95%|█████████▍| 4878/5153 [19:05<01:04,  4.27it/s]

 95%|█████████▍| 4879/5153 [19:05<01:04,  4.28it/s]

 95%|█████████▍| 4880/5153 [19:05<01:03,  4.28it/s]

 95%|█████████▍| 4881/5153 [19:06<01:03,  4.27it/s]

 95%|█████████▍| 4882/5153 [19:06<01:03,  4.26it/s]

 95%|█████████▍| 4883/5153 [19:06<01:03,  4.27it/s]

 95%|█████████▍| 4884/5153 [19:06<01:02,  4.28it/s]

 95%|█████████▍| 4885/5153 [19:07<01:02,  4.27it/s]

 95%|█████████▍| 4886/5153 [19:07<01:02,  4.26it/s]

 95%|█████████▍| 4887/5153 [19:07<01:02,  4.27it/s]

 95%|█████████▍| 4888/5153 [19:07<01:02,  4.27it/s]

 95%|█████████▍| 4889/5153 [19:07<01:01,  4.28it/s]

 95%|█████████▍| 4890/5153 [19:08<01:01,  4.27it/s]

 95%|█████████▍| 4891/5153 [19:08<01:01,  4.26it/s]

 95%|█████████▍| 4892/5153 [19:08<01:01,  4.27it/s]

 95%|█████████▍| 4893/5153 [19:08<01:00,  4.27it/s]

 95%|█████████▍| 4894/5153 [19:09<01:00,  4.28it/s]

 95%|█████████▍| 4895/5153 [19:09<01:00,  4.28it/s]

 95%|█████████▌| 4896/5153 [19:09<00:59,  4.29it/s]

 95%|█████████▌| 4897/5153 [19:09<00:59,  4.29it/s]

 95%|█████████▌| 4898/5153 [19:10<00:59,  4.28it/s]

 95%|█████████▌| 4899/5153 [19:10<00:59,  4.27it/s]

 95%|█████████▌| 4900/5153 [19:10<00:59,  4.26it/s]

 95%|█████████▌| 4901/5153 [19:10<00:59,  4.27it/s]

 95%|█████████▌| 4902/5153 [19:11<00:59,  4.25it/s]

 95%|█████████▌| 4903/5153 [19:11<00:58,  4.26it/s]

 95%|█████████▌| 4904/5153 [19:11<00:58,  4.26it/s]

 95%|█████████▌| 4905/5153 [19:11<00:58,  4.26it/s]

 95%|█████████▌| 4906/5153 [19:11<00:58,  4.25it/s]

 95%|█████████▌| 4907/5153 [19:12<00:57,  4.25it/s]

 95%|█████████▌| 4908/5153 [19:12<00:57,  4.26it/s]

 95%|█████████▌| 4909/5153 [19:12<00:57,  4.26it/s]

 95%|█████████▌| 4910/5153 [19:12<00:57,  4.26it/s]

 95%|█████████▌| 4911/5153 [19:13<00:56,  4.25it/s]

 95%|█████████▌| 4912/5153 [19:13<00:56,  4.26it/s]

 95%|█████████▌| 4913/5153 [19:13<00:56,  4.26it/s]

 95%|█████████▌| 4914/5153 [19:13<00:56,  4.26it/s]

 95%|█████████▌| 4915/5153 [19:14<00:55,  4.27it/s]

 95%|█████████▌| 4916/5153 [19:14<00:55,  4.26it/s]

 95%|█████████▌| 4917/5153 [19:14<00:55,  4.27it/s]

 95%|█████████▌| 4918/5153 [19:14<00:55,  4.27it/s]

 95%|█████████▌| 4919/5153 [19:15<00:54,  4.27it/s]

 95%|█████████▌| 4920/5153 [19:15<00:54,  4.26it/s]

 95%|█████████▌| 4921/5153 [19:15<00:54,  4.25it/s]

 96%|█████████▌| 4922/5153 [19:15<00:54,  4.26it/s]

 96%|█████████▌| 4923/5153 [19:15<00:54,  4.26it/s]

 96%|█████████▌| 4924/5153 [19:16<00:53,  4.26it/s]

 96%|█████████▌| 4925/5153 [19:16<00:53,  4.26it/s]

 96%|█████████▌| 4926/5153 [19:16<00:53,  4.26it/s]

 96%|█████████▌| 4927/5153 [19:16<00:52,  4.26it/s]

 96%|█████████▌| 4928/5153 [19:17<00:52,  4.26it/s]

 96%|█████████▌| 4929/5153 [19:17<00:52,  4.26it/s]

 96%|█████████▌| 4930/5153 [19:17<00:52,  4.26it/s]

 96%|█████████▌| 4931/5153 [19:17<00:52,  4.25it/s]

 96%|█████████▌| 4932/5153 [19:18<00:51,  4.26it/s]

 96%|█████████▌| 4933/5153 [19:18<00:51,  4.25it/s]

 96%|█████████▌| 4934/5153 [19:18<00:51,  4.25it/s]

 96%|█████████▌| 4935/5153 [19:18<00:51,  4.25it/s]

 96%|█████████▌| 4936/5153 [19:19<00:51,  4.25it/s]

 96%|█████████▌| 4937/5153 [19:19<00:50,  4.26it/s]

 96%|█████████▌| 4938/5153 [19:19<00:50,  4.26it/s]

 96%|█████████▌| 4939/5153 [19:19<00:50,  4.25it/s]

 96%|█████████▌| 4940/5153 [19:19<00:49,  4.26it/s]

 96%|█████████▌| 4941/5153 [19:20<00:49,  4.25it/s]

 96%|█████████▌| 4942/5153 [19:20<00:49,  4.25it/s]

 96%|█████████▌| 4943/5153 [19:20<00:49,  4.24it/s]

 96%|█████████▌| 4944/5153 [19:20<00:49,  4.24it/s]

 96%|█████████▌| 4945/5153 [19:21<00:49,  4.24it/s]

 96%|█████████▌| 4946/5153 [19:21<00:48,  4.24it/s]

 96%|█████████▌| 4947/5153 [19:21<00:48,  4.25it/s]

 96%|█████████▌| 4948/5153 [19:21<00:48,  4.25it/s]

 96%|█████████▌| 4949/5153 [19:22<00:48,  4.25it/s]

 96%|█████████▌| 4950/5153 [19:22<00:47,  4.24it/s]

 96%|█████████▌| 4951/5153 [19:22<00:47,  4.24it/s]

 96%|█████████▌| 4952/5153 [19:22<00:47,  4.25it/s]

 96%|█████████▌| 4953/5153 [19:23<00:47,  4.25it/s]

 96%|█████████▌| 4954/5153 [19:23<00:46,  4.25it/s]

 96%|█████████▌| 4955/5153 [19:23<00:46,  4.25it/s]

 96%|█████████▌| 4956/5153 [19:23<00:46,  4.24it/s]

 96%|█████████▌| 4957/5153 [19:23<00:46,  4.25it/s]

 96%|█████████▌| 4958/5153 [19:24<00:45,  4.25it/s]

 96%|█████████▌| 4959/5153 [19:24<00:45,  4.25it/s]

 96%|█████████▋| 4960/5153 [19:24<00:45,  4.26it/s]

 96%|█████████▋| 4961/5153 [19:24<00:45,  4.25it/s]

 96%|█████████▋| 4962/5153 [19:25<00:44,  4.25it/s]

 96%|█████████▋| 4963/5153 [19:25<00:44,  4.25it/s]

 96%|█████████▋| 4964/5153 [19:25<00:44,  4.24it/s]

 96%|█████████▋| 4965/5153 [19:25<00:44,  4.25it/s]

 96%|█████████▋| 4966/5153 [19:26<00:44,  4.25it/s]

 96%|█████████▋| 4967/5153 [19:26<00:43,  4.25it/s]

 96%|█████████▋| 4968/5153 [19:26<00:43,  4.25it/s]

 96%|█████████▋| 4969/5153 [19:26<00:43,  4.25it/s]

 96%|█████████▋| 4970/5153 [19:27<00:43,  4.25it/s]

 96%|█████████▋| 4971/5153 [19:27<00:42,  4.25it/s]

 96%|█████████▋| 4972/5153 [19:27<00:42,  4.25it/s]

 97%|█████████▋| 4973/5153 [19:27<00:42,  4.25it/s]

 97%|█████████▋| 4974/5153 [19:27<00:42,  4.24it/s]

 97%|█████████▋| 4975/5153 [19:28<00:41,  4.24it/s]

 97%|█████████▋| 4976/5153 [19:28<00:41,  4.24it/s]

 97%|█████████▋| 4977/5153 [19:28<00:41,  4.25it/s]

 97%|█████████▋| 4978/5153 [19:28<00:41,  4.25it/s]

 97%|█████████▋| 4979/5153 [19:29<00:40,  4.26it/s]

 97%|█████████▋| 4980/5153 [19:29<00:40,  4.26it/s]

 97%|█████████▋| 4981/5153 [19:29<00:40,  4.26it/s]

 97%|█████████▋| 4982/5153 [19:29<00:40,  4.25it/s]

 97%|█████████▋| 4983/5153 [19:30<00:40,  4.24it/s]

 97%|█████████▋| 4984/5153 [19:30<00:39,  4.24it/s]

 97%|█████████▋| 4985/5153 [19:30<00:39,  4.24it/s]

 97%|█████████▋| 4986/5153 [19:30<00:39,  4.25it/s]

 97%|█████████▋| 4987/5153 [19:31<00:39,  4.25it/s]

 97%|█████████▋| 4988/5153 [19:31<00:39,  4.19it/s]

 97%|█████████▋| 4989/5153 [19:31<00:39,  4.19it/s]

 97%|█████████▋| 4990/5153 [19:31<00:38,  4.21it/s]

 97%|█████████▋| 4991/5153 [19:31<00:38,  4.23it/s]

 97%|█████████▋| 4992/5153 [19:32<00:38,  4.23it/s]

 97%|█████████▋| 4993/5153 [19:32<00:37,  4.23it/s]

 97%|█████████▋| 4994/5153 [19:32<00:37,  4.23it/s]

 97%|█████████▋| 4995/5153 [19:32<00:37,  4.23it/s]

 97%|█████████▋| 4996/5153 [19:33<00:37,  4.24it/s]

 97%|█████████▋| 4997/5153 [19:33<00:36,  4.23it/s]

 97%|█████████▋| 4998/5153 [19:33<00:36,  4.24it/s]

 97%|█████████▋| 4999/5153 [19:33<00:36,  4.23it/s]

 97%|█████████▋| 5000/5153 [19:34<00:36,  4.23it/s]

 97%|█████████▋| 5001/5153 [19:34<00:35,  4.24it/s]

 97%|█████████▋| 5002/5153 [19:34<00:35,  4.23it/s]

 97%|█████████▋| 5003/5153 [19:34<00:35,  4.24it/s]

 97%|█████████▋| 5004/5153 [19:35<00:35,  4.24it/s]

 97%|█████████▋| 5005/5153 [19:35<00:34,  4.24it/s]

 97%|█████████▋| 5006/5153 [19:35<00:34,  4.24it/s]

 97%|█████████▋| 5007/5153 [19:35<00:34,  4.24it/s]

logging
logging the anndata

 97%|█████████▋| 5008/5153 [19:37<01:27,  1.66it/s]

AnnData object with n_obs × n_vars = 40064 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

 97%|█████████▋| 5009/5153 [19:37<01:10,  2.04it/s]

 97%|█████████▋| 5010/5153 [19:37<00:58,  2.43it/s]

 97%|█████████▋| 5011/5153 [19:37<00:50,  2.80it/s]

 97%|█████████▋| 5012/5153 [19:38<00:44,  3.14it/s]

 97%|█████████▋| 5013/5153 [19:38<00:40,  3.43it/s]

 97%|█████████▋| 5014/5153 [19:38<00:37,  3.66it/s]

 97%|█████████▋| 5015/5153 [19:38<00:35,  3.85it/s]

 97%|█████████▋| 5016/5153 [19:39<00:34,  4.00it/s]

 97%|█████████▋| 5017/5153 [19:39<00:33,  4.11it/s]

 97%|█████████▋| 5018/5153 [19:39<00:32,  4.15it/s]

 97%|█████████▋| 5019/5153 [19:39<00:31,  4.21it/s]

 97%|█████████▋| 5020/5153 [19:39<00:31,  4.25it/s]

 97%|█████████▋| 5021/5153 [19:40<00:30,  4.29it/s]

 97%|█████████▋| 5022/5153 [19:40<00:30,  4.31it/s]

 97%|█████████▋| 5023/5153 [19:40<00:30,  4.33it/s]

 97%|█████████▋| 5024/5153 [19:40<00:29,  4.34it/s]

 98%|█████████▊| 5025/5153 [19:41<00:29,  4.34it/s]

 98%|█████████▊| 5026/5153 [19:41<00:29,  4.34it/s]

 98%|█████████▊| 5027/5153 [19:41<00:29,  4.34it/s]

 98%|█████████▊| 5028/5153 [19:41<00:28,  4.34it/s]

 98%|█████████▊| 5029/5153 [19:42<00:28,  4.34it/s]

 98%|█████████▊| 5030/5153 [19:42<00:28,  4.34it/s]

 98%|█████████▊| 5031/5153 [19:42<00:28,  4.34it/s]

 98%|█████████▊| 5032/5153 [19:42<00:27,  4.35it/s]

 98%|█████████▊| 5033/5153 [19:42<00:27,  4.35it/s]

 98%|█████████▊| 5034/5153 [19:43<00:27,  4.35it/s]

 98%|█████████▊| 5035/5153 [19:43<00:27,  4.35it/s]

 98%|█████████▊| 5036/5153 [19:43<00:26,  4.35it/s]

 98%|█████████▊| 5037/5153 [19:43<00:26,  4.35it/s]

 98%|█████████▊| 5038/5153 [19:44<00:26,  4.36it/s]

 98%|█████████▊| 5039/5153 [19:44<00:26,  4.35it/s]

 98%|█████████▊| 5040/5153 [19:44<00:25,  4.36it/s]

 98%|█████████▊| 5041/5153 [19:44<00:25,  4.35it/s]

 98%|█████████▊| 5042/5153 [19:45<00:25,  4.35it/s]

 98%|█████████▊| 5043/5153 [19:45<00:25,  4.36it/s]

 98%|█████████▊| 5044/5153 [19:45<00:25,  4.35it/s]

 98%|█████████▊| 5045/5153 [19:45<00:24,  4.34it/s]

 98%|█████████▊| 5046/5153 [19:45<00:24,  4.34it/s]

 98%|█████████▊| 5047/5153 [19:46<00:24,  4.33it/s]

 98%|█████████▊| 5048/5153 [19:46<00:24,  4.34it/s]

 98%|█████████▊| 5049/5153 [19:46<00:23,  4.34it/s]

 98%|█████████▊| 5050/5153 [19:46<00:23,  4.35it/s]

 98%|█████████▊| 5051/5153 [19:47<00:23,  4.35it/s]

 98%|█████████▊| 5052/5153 [19:47<00:23,  4.36it/s]

 98%|█████████▊| 5053/5153 [19:47<00:22,  4.35it/s]

 98%|█████████▊| 5054/5153 [19:47<00:22,  4.34it/s]

 98%|█████████▊| 5055/5153 [19:48<00:22,  4.33it/s]

 98%|█████████▊| 5056/5153 [19:48<00:22,  4.35it/s]

 98%|█████████▊| 5057/5153 [19:48<00:22,  4.35it/s]

 98%|█████████▊| 5058/5153 [19:48<00:21,  4.34it/s]

 98%|█████████▊| 5059/5153 [19:48<00:21,  4.35it/s]

 98%|█████████▊| 5060/5153 [19:49<00:21,  4.35it/s]

 98%|█████████▊| 5061/5153 [19:49<00:21,  4.35it/s]

 98%|█████████▊| 5062/5153 [19:49<00:20,  4.36it/s]

 98%|█████████▊| 5063/5153 [19:49<00:20,  4.35it/s]

 98%|█████████▊| 5064/5153 [19:50<00:20,  4.33it/s]

 98%|█████████▊| 5065/5153 [19:50<00:20,  4.34it/s]

 98%|█████████▊| 5066/5153 [19:50<00:20,  4.34it/s]

 98%|█████████▊| 5067/5153 [19:50<00:19,  4.35it/s]

 98%|█████████▊| 5068/5153 [19:50<00:19,  4.35it/s]

 98%|█████████▊| 5069/5153 [19:51<00:19,  4.35it/s]

 98%|█████████▊| 5070/5153 [19:51<00:19,  4.36it/s]

 98%|█████████▊| 5071/5153 [19:51<00:18,  4.36it/s]

 98%|█████████▊| 5072/5153 [19:51<00:18,  4.34it/s]

 98%|█████████▊| 5073/5153 [19:52<00:18,  4.34it/s]

 98%|█████████▊| 5074/5153 [19:52<00:18,  4.34it/s]

 98%|█████████▊| 5075/5153 [19:52<00:17,  4.35it/s]

 99%|█████████▊| 5076/5153 [19:52<00:17,  4.35it/s]

 99%|█████████▊| 5077/5153 [19:53<00:17,  4.35it/s]

 99%|█████████▊| 5078/5153 [19:53<00:17,  4.35it/s]

 99%|█████████▊| 5079/5153 [19:53<00:16,  4.36it/s]

 99%|█████████▊| 5080/5153 [19:53<00:16,  4.36it/s]

 99%|█████████▊| 5081/5153 [19:53<00:16,  4.36it/s]

 99%|█████████▊| 5082/5153 [19:54<00:16,  4.36it/s]

 99%|█████████▊| 5083/5153 [19:54<00:16,  4.35it/s]

 99%|█████████▊| 5084/5153 [19:54<00:15,  4.35it/s]

 99%|█████████▊| 5085/5153 [19:54<00:15,  4.34it/s]

 99%|█████████▊| 5086/5153 [19:55<00:15,  4.35it/s]

 99%|█████████▊| 5087/5153 [19:55<00:15,  4.35it/s]

 99%|█████████▊| 5088/5153 [19:55<00:14,  4.35it/s]

 99%|█████████▉| 5089/5153 [19:55<00:14,  4.35it/s]

 99%|█████████▉| 5090/5153 [19:56<00:14,  4.34it/s]

 99%|█████████▉| 5091/5153 [19:56<00:14,  4.34it/s]

 99%|█████████▉| 5092/5153 [19:56<00:14,  4.34it/s]

 99%|█████████▉| 5093/5153 [19:56<00:13,  4.34it/s]

 99%|█████████▉| 5094/5153 [19:56<00:13,  4.35it/s]

 99%|█████████▉| 5095/5153 [19:57<00:13,  4.35it/s]

 99%|█████████▉| 5096/5153 [19:57<00:13,  4.34it/s]

 99%|█████████▉| 5097/5153 [19:57<00:12,  4.35it/s]

 99%|█████████▉| 5098/5153 [19:57<00:12,  4.35it/s]

 99%|█████████▉| 5099/5153 [19:58<00:12,  4.34it/s]

 99%|█████████▉| 5100/5153 [19:58<00:12,  4.34it/s]

 99%|█████████▉| 5101/5153 [19:58<00:11,  4.35it/s]

 99%|█████████▉| 5102/5153 [19:58<00:11,  4.35it/s]

 99%|█████████▉| 5103/5153 [19:59<00:11,  4.35it/s]

 99%|█████████▉| 5104/5153 [19:59<00:11,  4.35it/s]

 99%|█████████▉| 5105/5153 [19:59<00:11,  4.36it/s]

 99%|█████████▉| 5106/5153 [19:59<00:10,  4.35it/s]

 99%|█████████▉| 5107/5153 [19:59<00:10,  4.34it/s]

 99%|█████████▉| 5108/5153 [20:00<00:10,  4.35it/s]

 99%|█████████▉| 5109/5153 [20:00<00:10,  4.36it/s]

 99%|█████████▉| 5110/5153 [20:00<00:09,  4.36it/s]

 99%|█████████▉| 5111/5153 [20:00<00:09,  4.35it/s]

 99%|█████████▉| 5112/5153 [20:01<00:09,  4.34it/s]

 99%|█████████▉| 5113/5153 [20:01<00:09,  4.35it/s]

 99%|█████████▉| 5114/5153 [20:01<00:08,  4.34it/s]

 99%|█████████▉| 5115/5153 [20:01<00:08,  4.34it/s]

 99%|█████████▉| 5116/5153 [20:02<00:08,  4.34it/s]

 99%|█████████▉| 5117/5153 [20:02<00:08,  4.33it/s]

 99%|█████████▉| 5118/5153 [20:02<00:08,  4.34it/s]

 99%|█████████▉| 5119/5153 [20:02<00:07,  4.33it/s]

 99%|█████████▉| 5120/5153 [20:02<00:07,  4.34it/s]

 99%|█████████▉| 5121/5153 [20:03<00:07,  4.34it/s]

 99%|█████████▉| 5122/5153 [20:03<00:07,  4.35it/s]

 99%|█████████▉| 5123/5153 [20:03<00:06,  4.35it/s]

 99%|█████████▉| 5124/5153 [20:03<00:06,  4.36it/s]

 99%|█████████▉| 5125/5153 [20:04<00:06,  4.35it/s]

 99%|█████████▉| 5126/5153 [20:04<00:06,  4.35it/s]

 99%|█████████▉| 5127/5153 [20:04<00:05,  4.34it/s]

100%|█████████▉| 5128/5153 [20:04<00:05,  4.33it/s]

100%|█████████▉| 5129/5153 [20:05<00:05,  4.34it/s]

100%|█████████▉| 5130/5153 [20:05<00:05,  4.33it/s]

100%|█████████▉| 5131/5153 [20:05<00:05,  4.33it/s]

100%|█████████▉| 5132/5153 [20:05<00:04,  4.34it/s]

100%|█████████▉| 5133/5153 [20:05<00:04,  4.34it/s]

100%|█████████▉| 5134/5153 [20:06<00:04,  4.34it/s]

100%|█████████▉| 5135/5153 [20:06<00:04,  4.34it/s]

100%|█████████▉| 5136/5153 [20:06<00:03,  4.33it/s]

100%|█████████▉| 5137/5153 [20:06<00:03,  4.34it/s]

100%|█████████▉| 5138/5153 [20:07<00:03,  4.34it/s]

100%|█████████▉| 5139/5153 [20:07<00:03,  4.34it/s]

100%|█████████▉| 5140/5153 [20:07<00:02,  4.35it/s]

100%|█████████▉| 5141/5153 [20:07<00:02,  4.34it/s]

100%|█████████▉| 5142/5153 [20:08<00:02,  4.34it/s]

100%|█████████▉| 5143/5153 [20:08<00:02,  4.34it/s]

100%|█████████▉| 5144/5153 [20:08<00:02,  4.33it/s]

100%|█████████▉| 5145/5153 [20:08<00:01,  4.34it/s]

100%|█████████▉| 5146/5153 [20:08<00:01,  4.35it/s]

100%|█████████▉| 5147/5153 [20:09<00:01,  4.34it/s]

100%|█████████▉| 5148/5153 [20:09<00:01,  4.34it/s]

100%|█████████▉| 5149/5153 [20:09<00:00,  4.35it/s]

100%|█████████▉| 5150/5153 [20:09<00:00,  4.35it/s]

100%|█████████▉| 5151/5153 [20:10<00:00,  4.35it/s]

100%|█████████▉| 5152/5153 [20:10<00:00,  4.33it/s]

100%|██████████| 5153/5153 [20:10<00:00,  5.02it/s]

100%|██████████| 5153/5153 [20:11<00:00,  4.25it/s]

logging the anndata

AnnData object with n_obs × n_vars = 9250 × 0
    obs: 'pred_cell_type_ontology_term_id', 'pred_disease_ontology_term_id', 'pred_assay_ontology_term_id', 'pred_self_reported_ethnicity_ontology_term_id', 'pred_sex_ontology_term_id', 'pred_organism_ontology_term_id', 'conv_pred_cell_type_ontology_term_id', 'conv_pred_disease_ontology_term_id', 'conv_pred_assay_ontology_term_id', 'conv_pred_self_reported_ethnicity_ontology_term_id'
    obsm: 'scprint_emb_cell_type_ontology_term_id'

too few cells to embed into a umap
too few cells to compute a clustering

KeyError: 'cellxgene_census/immune_cell_atlas'

In [ ]:
metrics

In [ ]:
emb = pd.DataFrame(
    data={
        "Isolated labels": [
            0.566661,
            0.511032,
            0.509863
            0.657649,
        ],
        "KMeans NMI": [
            0.645338,
            0.238028,
            0.567372,
            0.426683
        ],
        "KMeans ARI": [
            0.31973,
            0.11652,
            0.391042,
            0.134236
        ],
        "Silhouette label": [
            0.508098,
            0.514257,
            0.54277,
            0.558273
        ],
        "cLISI": [
            0.997801,
            0.956136,
            0.999368,
            1.0
        ],
        "BRAS": [
            0.816372,
            0.74002,
            0.682742,
            0.778155
        ],
        "iLISI": [
            0.052263,
            0.150554,
            0.03697,
            0.0
        ],
        "KBET": [
            0.314974,
            0.169856,
            0.193596,
            0.849659
        ],
        "Graph connectivity": [
            0.764403,
            0.768737,
            0.872287,
            0.825514
        ],
        "PCR comparison": [
            0,
            0.269315,
            0,
            0,
        ],
        "Batch correction": [
            0.389602,
            0.419696,
            0.357119,
            0.490666
        ],
        "Bio conservation": [
            0.607526,
            0.467195,
            0.63164,
            0.525811
        ],
        "Total": [
            0.520356,
            0.448195,
            0.521832,
            0.511753
        ],
    },
    index=[
        "gtex_v9",
        "dkd",
        "hypomap",
        "mouse_pancreas_atlas",
    ],
)

In [ ]:
{
    "cellxgene_census/dkd_ref_cls": {
        "cell_type_ontology_term_id": {
            "accuracy": 0.4937716969573208,
            "macro": 0.38015219981782045,
            "micro": 0.4937716969573208,
            "weighted": 0.44125553939089207,
        }
    },
    "cellxgene_census/dkd_cls": {
        "cell_type_ontology_term_id": {
            "accuracy": 0.4630541871921182,
            "macro": 0.39612779635380635,
            "micro": 0.4630541871921182,
            "weighted": 0.43238258813181274,
        }
    },
    "cellxgene_census/gtex_v9_ref_cls": {
        "cell_type_ontology_term_id": {
            "accuracy": 0.662801373334736,
            "macro": 0.45113362926393386,
            "micro": 0.662801373334736,
            "weighted": 0.6076783134412977,
        }
    },
    "cellxgene_census/gtex_v9_cls": {
        "cell_type_ontology_term_id": {
            "accuracy": 0.4894855752519986,
            "macro": 0.5275646372211268,
            "micro": 0.4894855752519986,
            "weighted": 0.45377925621844867,
        }
    },
    "cellxgene_census/hypomap_ref_cls": {
        "cell_type_ontology_term_id": {
            "accuracy": 0.8986192115347146,
            "macro": 0.5346630203398964,
            "micro": 0.8986192115347146,
            "weighted": 0.8782631897011843,
        }
    },
    "cellxgene_census/hypomap_cls": {
        "cell_type_ontology_term_id": {
            "accuracy": 0.9525547445255474,
            "macro": 0.6734592457544935,
            "micro": 0.9525547445255474,
            "weighted": 0.9472890166071732,
        }
    },
    "cellxgene_census/mouse_pancreas_atlas_ref_cls": {
        "cell_type_ontology_term_id": {
            "accuracy": 0.6353696705188564,
            "macro": 0.6829825924446588,
            "micro": 0.6353696705188564,
            "weighted": 0.5402847879953743,
        }
    },
    "cellxgene_census/mouse_pancreas_atlas_cls": {
        "cell_type_ontology_term_id": {
            "accuracy": 0.7887935600042368,
            "macro": 0.7095144808117735,
            "micro": 0.7887935600042368,
            "weighted": 0.711819695219025,
        }
    },
}

In [ ]:
{
    "dkd_ref_cls": {
        "accuracy": 0.4937716969573208,
        "macro": 0.38015219981782045,
        "micro": 0.4937716969573208,
        "weighted": 0.44125553939089207,
    },
    "cellxgene_census/dkd_cls": {
        "accuracy": 0.4630541871921182,
        "macro": 0.39612779635380635,
        "micro": 0.4630541871921182,
        "weighted": 0.43238258813181274,
    },
    "gtex_v9_ref_cls": {
        "accuracy": 0.662801373334736,
        "macro": 0.45113362926393386,
        "micro": 0.662801373334736,
        "weighted": 0.6076783134412977,
    },
    "gtex_v9_cls": {
        "accuracy": 0.4894855752519986,
        "macro": 0.5275646372211268,
        "micro": 0.4894855752519986,
        "weighted": 0.45377925621844867,
    },
    "hypomap_ref_cls": {
        "accuracy": 0.8986192115347146,
        "macro": 0.5346630203398964,
        "micro": 0.8986192115347146,
        "weighted": 0.8782631897011843,
    },
    "hypomap_cls": {
        "accuracy": 0.9525547445255474,
        "macro": 0.6734592457544935,
        "micro": 0.9525547445255474,
        "weighted": 0.9472890166071732,
    },
    "mouse_pancreas_atlas_ref_cls": {
        "accuracy": 0.6353696705188564,
        "macro": 0.6829825924446588,
        "micro": 0.6353696705188564,
        "weighted": 0.5402847879953743,
    },
    "mouse_pancreas_atlas_cls": {
        "accuracy": 0.7887935600042368,
        "macro": 0.7095144808117735,
        "micro": 0.7887935600042368,
        "weighted": 0.711819695219025,
    },
}

In [ ]:
for k, v in metrics.items():
    print(f"{k}: {v['accuracy']}")

In [ ]:
for k, v in res_label.items():
    if k is None:
        continue
    print(f"{k.split('/')[1]}: ")
    for l, w in v.items():
        if w is None:
            continue
        print(f"    {l}: {w['accuracy']}")
    m = 0
    for l, w in metrics.items():
        if l.startswith(k.split("/")[1]):
            if w["accuracy"] > m:
                m = w["accuracy"]
    print(f"    scPRINT-2 (zero-shot): {m:.3f}")

In [ ]:
import pandas as pd

In [ ]:
FACT = 1.5
emb.iloc[:, -1] * (1 + FACT) - (emb.iloc[:, -2] * FACT + emb.iloc[:, -3])

In [ ]:
for k, v in res.items():
    if k is None:
        continue
    print(f"{k.split('/')[1]}: ")
    for l, w in v.items():
        cell = 0

        for c in [
            "ari",
            "nmi",
            "isolated_label_asw",
            "clisi",
            "asw_label",
        ]:
            if w[c] == "NA":
                continue
            cell += w[c]
        cell /= 5
        batch = 0

        for b in [
            "pcr",
            "graph_connectivity",
            "asw_batch",
            "ilisi",
            "kbet",
        ]:
            if w[b] == "NA":
                continue
            batch += w[b]
        batch /= 5
        total = cell * 0.4 + batch * 0.6
        print(f"    {l}: {total:.3f}")
    # print(f"         Bio: {cell:.3f}")
    # print(f"         Batch: {batch:.3f}")
    if k.split("/")[1] not in emb.index:
        continue
    print(f"   scPRINT-2 (zero-shot): {emb.loc[k.split('/')[1], 'Total']:.3f}")
    # print(f"         Bio: {emb.loc[k.split('/')[1], 'Bio conservation']:.3f}")
# print(f"         Batch: {emb.loc[k.split('/')[1], 'Batch correction']:.3f}")

# cell_cycle_conservation
# hvg_overlap
# isolated_label_asw

# same with finetuning batch

In [ ]:
## ISSUE: many batches to correct, mmd might not be the right tool

## same with fine tuning class

In [ ]:
finetuner = FinetuneBatchClass(
    batch_key="donor_id",
    max_len=3000,
)

model, metrics[name + "_fine_tuning"] = finetuner(model=model, train_adata=adata)

In [ ]:
metrics